#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L41 Illusion of pastoral peace
#+begin_verse
What particular anxiety spoils the country dweller's visit to the theatre?

The quite life of the country has never appealed to me.
City born and city bred,
	I have always regarded the country as something you look at through a train window,
		or something you occasionally visit during the weekend.
Most of my friends live in the city,
	yet they always go into raptures at the mere mention of the country.
Though they extol the virtues of the peaceful life,
	only one of them has ever gone to live in the country
	and he was back in town within six months.
Even he still lives under the illusion that country life is somehow superior to town life.
He is forever talking about the friendly people,
	the clean atmosphere, the closeness to nature and the gentle pace of living.
Nothing can be compared, he maintains,
	with the first cockcrow,
		the twittering of birds at dawn,
		the sight of the rising sun glinting on the trees and pastures.
This idyllic pastoral scene is only part of the picture.
My friend fails to mention the long and friendless winter evenings in front of the TV
	-- virtually the only form of entertainment.
He says nothing about the poor selection of goods in the shops,
	or about those unfortunate people
		who have to travel from the country to the city every day to get to work.
Why people are prepared to tolerate a four-hour journey each day
	for the dubious privilege of living in the country is beyond me.
They could be saved so much misery and expense if they chose to live in the city
	where they rightly belong.

If you can do without the few pastoral pleasures of the country,
	you will find the city can provide you with the best that life can offer.
You never have to travel miles to see your friends.
They invariably live nearby
	and are always available for an informal chat or ane evening's entertainment.
Some of my acquaintances in the country come up to town once or twice a year
	to visit the theatre as a special treat.
For them this is a major operation
	which involves considerable planning.
As the play draws to its close,
	they wonder whether they will ever catch that last train home.
The city dweller never experiences anxieties of this sort.
The latest exhibitions, films, or plays are only a short bus ride away.
Shopping, too, is always a pleasure.
There is so much variety that you never have to make do with second best.
Country people run wild
	when they go shopping in the city
		and stagger home loaded with as many of exotic items as they can carry.
Nor is the city without its moments of beauty.
There is something comforting about the warm glow shed by advertisements on cold wet winter nights.
Few things could be more impressive than the peace
	that descends on deserted city streets at weekends
		when the thousands that travel to work every day are tucked away in their homes in the country.
It has always been a mystery to me why city dwellers,
	who appreciate all these things,
		obstinately pretend that they would prefer to live in the country.
#+end_verse

** words
illusion [ЙӘЛҲluЛҗК’(Йҷ)n] n.е№»жғі
pastoral [ЛҲpГҰstЙҷrЙҷl] adj.з”°еӣӯзҡ„
breed [briЛҗd] v.еҹ№иӮІ
rapture [ЛҲrГҰptКғЙҷr] n.ж¬Је–ң
extol [ЙӘkЛҲstoКҠl] v.иөһзҫҺ
superior [suЛҗЛҲpЙӘriЙҷr] adj.дјҳи¶Ҡзҡ„
cockcrow [ЛҲkЙ‘ЛҗkkroКҠ] n.йёЎеҸ«
twitter [ЛҲtwЙӘtЙҷr] v.(йёҹ)еҗұеҗұеҸ«
glint [ЙЎlЙӘnt] v.й—ӘзғҒ
pasture [ЛҲpГҰstКғЙҷr] n.зү§еңә
idyllic [aЙӘЛҲdЙӘlЙӘk] adj.з”°еӣӯиҜ—зҡ„
virtually [ЛҲvЙңЛҗrtКғuЙҷli] adv.еҮ д№Һ,е·®дёҚеӨҡ
dubious [ЛҲduЛҗbiЙҷs] adj.еҸҜз–‘зҡ„,жҖҖз–‘зҡ„
privilege [ЛҲprЙӘvЙҷlЙӘdК’] n.зү№жқғ
misery [ЛҲmЙӘzЙҷri] n.иӢҰйҡҫ
acquaintance [ЙҷЛҲkweЙӘntЙҷns] n.зҶҹдәә
treat [triЛҗt] n.йҡҫеҫ—зҡ„д№җдәӢ,дә«еҸ—
dweller [ЛҲdwelЙҷr] n.еұ…дҪҸиҖ…
stagger [ЛҲstГҰЙЎЙҷr] v.ж‘Үжҷғ,и№’и·ҡ
exotic [ЙӘЙЎЛҲzЙ‘ЛҗtЙӘk] adj.ејӮд№ҺеҜ»еёёзҡ„,еӨ–жқҘзҡ„
glow [ЙЎloКҠ] n.зҷҪз»Үе…ү
descend [dЙӘЛҲsend] v.дёӢиҗҪ,йҷҚдёҙ
obstinately [ЛҲЙ‘ЛҗbstЙӘnЙҷtli] adv.еӣәжү§ең°,йЎҪеӣәең°

** еҚ•иҜҚйҖ еҸҘ
** еҸҚеӨҚеҗ¬з”өеҪұзүҮж®өзӣҙеҲ°жҮӮе…ій”®еҸҘ
** еӨҚд№ дәҢеҶҢиҜӯжі•(з¬”и®°жҲ–и§Ҷйў‘) & зәўзҡ®д№Ұ
** д№ жғҜз”Ёжі•йҖ еҸҘ
** и·ҹиҜ» 50йҒҚ
** Comprehension еҸҚеӨҚз»ғд№ 
** Ask me if еҶҷ+иҜ»
** ж‘ҳиҰҒеҶҷдҪң еҶҷ & еҜ№зӯ”жЎҲ
** tell the story еҸЈиҜӯеӨҚиҝ°
** composition йҳ…иҜ» жҲ– еҶҷдҪң
** Topics for discussion
