#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 48 The silent village
#+begin_verse
Why was the village silent?

In this much-travelled world,
	there are still thousands of places which are inaccessible to tourists.
We always assume that villagers in remote places are friendly and hospitable.
But people who are cut off not only from foreign tourists,
	but even from their own countrymen can be hostile to travellers.
Visits to really remotre villages are seldom enjoyable
	-- as my wife and I discovered during a tour through the Balkans.

We had spent several days in a small twon
	and visited a number of old churches in the vicinity.
These attracted many visitors,
	for they were not only of great architectural interest,
	but contained a large number of beautifully preserved frescoes as wll.
On the day before our departure, several bus loads of tourists descended on the town.
This was more than we could bear,
	so we decided to spend our last day exploring the countryside.
Taking a path which led out of the town,
	we crossed a few fields until we came to a dense wood.
We expected the path to end abruptly,
	but we found that it traced its way through the trees.
We tramped through the wood for over two hours until we arrived at a deep stream.
We could see that the path continued on the other sied,
	but we had no idea how we could get across the stream.
Suddenly my wife spotted a boat moored to the bank.
In it there was a boatman fast asleep.
We gently woke him up and asked him to ferry us to the other side.
Though he wa reluctant to do so at first, we eventually persuaded him to take us.

The path led to a tiny village perched on the steep sides of a mountain.
The place consisted of a straggling unmade road
	which was lined on either side by small houses.
Even under a clear blue sky, the village looked forbidding,
	as all the houses were built of grey mud bricks.
The village seemed deserted,
	the only sign of life being an ugly-looking black goat on a short length of rope
		tied to a tree in a field nearby.
Sitting down on a dilapidated wooden fence near the field,
	we opened a couple of tins of sardines and had a picnic lunch.
All at once, I noticed that my wife seemed to be filled with alarm.
Looking up I saw that we were surrounded by children in rags
	who were looking at us silently as we ate.
We offered them food and spoke to them kindly, but they remainded motionless.
I concluded that they were simply shy of strangers.
When we later walked down the main street of the village,
	we were followed by a silent procession of children.
The village which had seemed deserted, immediately came to life.
Faces appeared at windows.
Men in shirt sleeves stood outside their houses and glared at us.
Old women in black shawls peered at us from doorways.
The most frightening thing of all was that not a sound could be heard.
There was no doubt that we were unwelcome visitors.
We needed no further warning.
Turning back down the main street,
	we quickened our pace and made our way rapidly towards the stream
		where we hoped the boatman was waiting.
#+end_verse

** words
inaccessible [Àå…™n…ôkÀàses…ôb(…ô)l] adj.ÈöæÊé•ËøëÁöÑ
hospitable [Ààh…ësp…™t…ôb(…ô)l] adj.Â•ΩÂÆ¢ÁöÑ
hostile [Ààh…ëst(…ô)l] adj.‰∏çÂèãÂ•ΩÁöÑ
vicinity [v…™Ààs…™n…ôti] n.Âë®Âõ¥,ËøëÈÇª
architectural [Àå…ërk…™Ààtekt É…ôr…ôl] adj.Âª∫Á≠ëÁöÑ
fresco [Ààfresko ä] n.Â£ÅÁîª
abruptly […ô'br åptli] adv.Á™ÅÁÑ∂Âú∞
tramp [tr√¶mp] v.ÂæíÊ≠•Ë°åËøõ
moor [m är] v.Á≥ª(Ëàπ)
ferry [Ààferi] v.(Ê∏°Ëàπ)Ëøê
straggle [Ààstr√¶…°(…ô)l] v.ËîìÂª∂
dilapidated [d…™Ààl√¶p…™Àåde…™t…ôd] adj.ÈôàÊóßÁÝ¥ÁÉÇÁöÑ
sardine [s…ërÀàdin] n.Ê≤ô‰∏ÅÈ±º
rag [r√¶…°] n.ÁÝ¥ÁÉÇË°£Êúç
motionless [Ààmo ä É(…ô)nl…ôs] adj.‰∏çÂä®ÁöÑ
procession [pr…ôÀàse É(…ô)n] n.Ë°åÂàó
shawl [ É…îl] n.Êä´Â∑æ
peer [p…™r] v.ÂáùËßÜ
quicken [Ààkw…™k…ôn] v.ÂäÝÂø´

** ÂçïËØçÈÄÝÂè•
** ÂèçÂ§çÂê¨ÁîµÂΩ±ÁâáÊÆµÁõ¥Âà∞ÊáÇÂÖ≥ÈîÆÂè•
** Â§ç‰πÝ‰∫åÂÜåËØ≠Ê≥ï(Á¨îËÆ∞ÊàñËßÜÈ¢ë) & Á∫¢ÁöÆ‰π¶
** ‰πÝÊÉØÁî®Ê≥ïÈÄÝÂè•
** Ë∑üËØª 50ÈÅç
** Comprehension ÂèçÂ§çÁªÉ‰πÝ
** Ask me if ÂÜô+ËØª
** ÊëòË¶ÅÂÜô‰Ωú ÂÜô & ÂØπÁ≠îÊ°à
** tell the story Âè£ËØ≠Â§çËø∞
** composition ÈòÖËØª Êàñ ÂÜô‰Ωú
** Topics for discussion
