#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 25 Do the English speak English?

#+begin_verse
Why does the writer not understand the porter?

I arrived in London at last.
The railway station was big, black and dark.
I did *not know the way to my hotel*,
	so I asked a porter.
I not only spoke English very carefully, but very clearly as well.
The porter, however, could not understand me.
I repeated my question several times
	and at last he understood.
He answered me,
	but he spoke neither slowly nor clearly.
'I am a foreigner,' I said.
Then he spoke slowly,
	but I could not understand him.
My teacher never spoke English like that!
The porter and I looked at each other and smiled.
Then he said somethings and I understood it.
'You'll soon learn English!' he said.
I wonder, in England, each person speaks a different language.
The English understand each other,
	but I don't understand them!
Do they speak English?
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
