#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 26 The best art critics

#+begin_verse
Who is the student's best critic?

I am an art student
	and I paint a lot of pictures.
*Many people pretend that* they understand modern art.
They always tell you what a picture is 'about'.
Of course, many pictures are not 'about' anything.
They are just pretty patterns.
We like them in the same way
	that we like pretty curtain material.
I think that young children often appreciate modern pictures better than anyone else.
They notice more.
My sister is only seven,
	but she always tells me whether my pictures are good or not.
She came into my room yesterday.
'What are you doing?' she asked.
'I'm hanging this picture on the wall,' I answered.
'It's a new one. Do you like it?'
She looked at it critically for a moment.
'It's all right,' she said, 'but isn't it upside down?'
I looked at it again.
She was right! It was!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
