#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 31 Success story
#+begin_verse
What was Frank's first job?

Yesterday afternoon Frank Hawkins was telling me about his experience as a young man.
Before he retired,
	Frank was the head of a very large business company,
  but as a boy he used to work in a small shop.
*It was his job to repair bicycles*
	and at that time he used to work fourteen hours a day.
He saved money for years
	and in 1958 he bought a small workshop of his own.
*In his twenties* Frank used to make spare parts for aeroplanes.
At that time he had two helpers.
In a few years the small workshop had become a large factory
  which employed seven hundred and twenty-eight people.
Frank smiled when he remembered his hard early years and the long road to success.
He was still smiling
	when the door opened and his wife came in.
She wanted him to repair their grandson's bicycle.
#+end_verse

** 单词造句
1
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
