#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 32 Shopping made easy

#+begin_verse
Who was the thief?

People are not so honest as they once were.
The temptation to steal is greater than ever before -- especially in large shops.
A detective recently watched a well-dressed woman
	who always went into a large store on Monday mornings.
One Monday, there were fewer people in the shop than usual when the woman came in,
  so *it was easier for the detective to watch her*.
The woman first bought a few small articles.
After a little time, she chose one of the most expensive dresses in the shop
  and *handed it to an assistant* who *wrapped it up* for her as quickly as possible.

Then the woman simply took the parcel and walked out of the shop without paying.
When she was arrested,
	the detective found out that the shop assistant was her daughter.
The girl gave her mother a free dress once a week.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
