#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 36 Across the Channel

#+begin_verse
What happened when the snake charmer began to play jazz?

Debbie Hart is going to swim across the English Channel tomorrow.
She is going to set out from the French coast at five o'clock in the morning.
Debbie is only eleven years old
	and she *hopes to* *set up a new world record*.
She is a strong swimmer
	and many people feel that she *is sure to succeed*.
Debbie's father will set out with her in a small boat.
Mr. Hart has trained his daughter for years.
Tomorrow he will be watching her anxiously
	as she swims the long distance to England.
Debbie *intends to* *take short rests* every two hours.
She will have something to drink
	but she will not eat any solid food.
Most of Debbie's school friends will be waiting for her on the English coast.
Among them will be Debbie's mother,
	who swam the Channel herself when she was a girl.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
