#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 38 Everything except the weather
#+begin_verse
Why did Harrison sell his house so quickly?

My old friend, Harrison, had lived in the Mediterranean for many years
	before he returned to England.
He had often *dreamed of retiring* in England and had *planned to settle down* in the country.
He had no sooner returned than he bought a house and went to live there.
Almost immediately he bagan to *complain about the weather*, for even though it was still summer,
  it rained continually and it was often *bitterly cold*.
After so many years of sunshine, Harrison got a shock.
He acted as if he had never lived in England before.
In the end, it was more than he could bear.
He had hardly had time to settle down when he sold the house and left the country.
The dream he had had for so many years ended there.
Harrison had thought of everything except the weather.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
