#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 41 Do you call that a hat?

#+begin_verse
What kind of shopping does the writer enjoy, do you think?

'Do you call that a hat?' I said to my wife.
'You needn't be so rude about it,' my wife answered as she looked at herself in the mirror.
I sat down on one of those modern chairs with holes in it and waited.
We had been in the hat shop for half an hour
	and my wife was still in front of the mirror.
'We mustn't buy things we don't need,' I remarked suddenly.
I *regretted saying* it almost at once.
'You needn't have said that,' my wife answered.
'I needn't *remind you of that terrible tie* you bought yesterday.'
'I *find it beautiful*,' I said.
'A man can never have too may ties.'
'And a woman can't have too many hats,' she answered.
Ten minutes later we walked out of the shop together.
My wife was wearing a hat that looked like a lighthouse.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
