#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 42 Not very musical

#+begin_verse
What happened when the snake charmer began to play jazz?

As we had *had a long walk* through one of the markets of Old Delhi,
	we stopped at a square to have a rest.
After a time, we noticed a snake charmer with two large baskets *at the other side of* the square,
	so we went to have a look at him.
As soon as he saw us,
	he picked up a long pipe which was covered with coins and opened one of the baskets.
When he began to *play a tune*,
	we *had our first glimpse of the snake*.
It rose out of the basket and began to follow the movements of the pipe.
We were very much surprised when the snake charmer suddenly began to play jazz and modern pop songs.
The snake, however, *continued to 'dance'* slowly.
It obviously could not *tell the difference between Indian music and jazz*!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
