#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 43 Over the South Pole
#+begin_verse
How was the plane able to clear the mountains?

In 1929, three years after his flight over the North Pole,
	the American explorer, R.E. Byrd, successfully flew over the South Pole for the first time.
Though, at first, Byrd and his men were able to take a great many photographs of the mountains
		that lay below,
	they soon *ran into serious trouble*.
At *one point*, *it seemed certain that* their plane would crash.
It could only get over the mountains if it rose to 10,000 feet.
Byrd at once *ordered his men to throw* out two heavy food sacks.
The plane was then able to rise and it cleared the mountains by 400 feet.
Byrd now knew that he would be able to reach the South Pole which was 300 miles away,
	for there were no more mountains in sight.
The aircraft was able to fly over the endless white plains without difficulty.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
