#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 44 Through the forest
#+begin_verse
How did Mrs. Sterling get her bag back?

Mrs. Anne Sterling did not think of the risk she was taking
	when she ran through a forest after two men.
They had *rushed up to her*
	while she was *having a picnic* *at the edge of a forest* with her children
		and tried to steal her handbag.
In the struggle, the strap broke and, with the bag *in their possession*,
	both men started running through the trees.
Mrs. Sterling got so angry that she ran after them.
She was soon *out of breath*, but she continued to run.
When she *caught up with them*,
	she saw that they had sat down and were going through the contents of the bag,
	so she *ran straight at them*.
The men got such a fright that they dropped the bag and ran away.
"The strap needs mending," said Mrs. Sterling later, 'but they did not steal anything."
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
