#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 46 Expensive and uncomfortable

#+begin_verse
What did the man in this story do?

When a plane from London arrived at Sydney airport,
	workers began to unload a number of wooden boxes which contained clothing.
*No one could account for the fact that* one of the boxes was extremely heavy.
*It suddenly occurred to one of the workers to open* up the box.
He *was astonished at what* he found.
A man was lying in the box on top of a pile of woollen goods.
He was so surprised at being discovered that he did not even try to run away.
After he was arrested,
	the man *admitted hiding* in the box before the plane left London.
He had had a long and uncomfortable trip,
	for he had been confined to the wooden box for over eighteen hours.
The man was ordered to pay $3500 for the cost of the trip.
The normal price of a ticket is $2000!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
