* L49 The end of a dream
How did the dream end?

Tired of sleeping on the floor, a young man in Teheran saved up for years to buy a real bed.
For the first time in his life, he became the proud owner of a bed
	which had springs and a mattress.
Because the weather was very hot, he carried the bed on to the roof of his house.
He slept very well for the first two nights, but on the third night, a storm blew up.
A gust of wind swept the bed off the roof and sent it crashing into the courtyard below.
The young man did not wake up until the bed had struck the ground.
Although the bed was smashed to pieces, the man was miraculously unhurt.
When he woke up, he was still on the mattress.
Glancing at the bits of wood and metal that lay around him,
	the man sadly picked up the mattress and carried it into his house.
After he had put it on the floor, he promptly went to sleep again.

** words
tired adj.
real adj.
owner n.
spring n.
mattress n.
gust n.
sweep v.
courtyard n. 院子
smash v.
miraculously adv.
unhurt adj.
glance v.
promptly adv.

** Asking questions
1. The young man lived in Teheran. Where
	 Where did the young man lived?
	 
2. He was tired of sleeping on the floor. What/Who
	 What was he tired of?
	 Who was tired of sleeping on the floor?
	 
3. He saved up for years. How long / Why
	 How long did he save up?
	 Why did he save up for years?

4. He wanted to buy a real bed. What/Why
	 What did he want to buy?
	 Why did he want to buy a real bed?

5. He bought a bed with springs and a mattress. What kind/Why
	 What kind of bed did he buy?
	 Why did he buy a bed with springs and a mattress?

6. The weather was very hot. What... like
	 What was the weather like?

7. He carried his bed on to the roof. Where... to
	 Where did he carry his bed on to?

8. He slept very well. How/Who
	 How did he sleep?
	 Who slept very well?

9. A storm blew up on the third night. When
	 When did a storm blow up?

10. A gust of wind swept the bed off the roof. What/When
		What did a gust of wind sweep off the roof?
		When did a gust of wind sweep the bed off the root?

11. It landed in the courtyard. Where
		Where did it land?
		
** Summary Writing
A young man in Teheran bought a real bed for the first time in his life.
He slept on the roof of his house because the weather was hot.
Three nights later, the bed was swept off the roof during a storm.
The man was not only unhurt but still on his mattress.
The bed was in pieces.
He carried the mattress indoors.
He put it on the floor.
He went back to sleep.
As the bed was in pieces,
	he carried the mattress indoors and after he had put it on the floor he went back to sleep.

** Topics for discussion
1. Describe a storm that you've known or heard about. What kind of damage was done?
	 A storm blew up in Hangzhou.
	 We had to work in home and couldn't take subways.

2. Describe the most uncomfortable night you've ever spent.
	 I and my wife hurried to Hangzhou from Jinxian.
	 We didn't prepare sleeping bag.
	 We felt so cold that we didn't go to sleep promptly.

3. How does the climate affect the kind of houses and furniture people have?
	 Give as many examples as you can to illustrate your answer.
	 如果天气比较冷,房子会更注意保暖,家具更多使用woolen的.
