* L51 Reward for a virtue

** Pattern Drill
1T: paint the gate - mend
S1: Did you paint the gate last week?
S2: Yes, I mended it first and then I painted it.
give a lecture - write/prepare
	Did you give a lecture last week?
	Yes, I wrote it first and then I prepared it.

eat those vegetables - wash/cook
	Did you eat those vegetables last week?
	Yes, I washed them first and then I cooked them.

sell that machine - repair/ test
	Did you sell that machine last week?
	Yes, I repaired it first and then I tested it.

use your bicycle - clean/oil
	Did you use your bicycle last week?
	Yes, I cleaned it first and then I oiled it.

2T: go on a diet - beg
S1: He went on a diet once, didn't he?
S2: Yes, he did. His wife begged him to.
cook dinner - ask
	He cooked dinner once, didn't he?
	Yes, he did. His wife asked him to.

wear a hat - want
	He weared a hat once, didn't he?
	Yes, he did. His wife wanted him to.

iron a shirt - tell
	He ironed a shirt once, didn't he?
	Yes, he did. His wife told him to.

change his job - advise
	He changed his job once, didn't he?
	Yes, he did. His wife advised him to.

3T: find the body - return home
S1: When did she find the body?
S2: She found it when she returned home.
discover the gun - enter the room
	When did she discover the gun?
	She discovered it when she entered the room.

run to the phone - see the man
	When did she run to the phone?
	She ran to it when she saw the man. 

hear a noise - walk forward
	When did she heard a noise?
	She heard it when she walked forward.

drop the phone - fall to the floor
	When did she drop the phone?
	She dropped it when she fell to the floor.

4T: give a party this month
S1: Are they going to give a party this month?
S2: I don't expect so. They gave one last month.
buy a new house - this year
	Are they going to buy a new house this year?
	I don't expect so. They bought one last year.

have a haircut - this week
	Are they going to have a haircut this week?
	I don't expect so. They had a haircut last week.

enter for a race - this month
	Are they going to enter for a race this month?
	I don't expect so. They entered for a race last month

see a film - this month
	Are they going to see a film this month?
	I don't expect so. They saw a film last month.
	
** Ask questions
1. My friend is called Hugh. What
	 What is your friend called?
	 
2. He's always been fat. How long/Who
	 How long has he always been fat?
	 Who has always been fat?

3. He decided to go on a diet. Who/Why
	 Who decided to go on a diet?
	 Why did he decice to go on a diet?

4. He began his diet a week ago. When
	 When did he begin his diet?

5. He wrote out a list. What/When
	 What did he write out?
	 When did he write out a list?

6. It included all the food he loves. What
	 What did it include?

7. I paid him a visit yesterday. When
	 When did you pay him a visit?

8. I rang the bell. What...do
	 What did you do?

9. Hugh was as fat as ever. Who
	 Who was as fat as ever?

10. He led me into his room. Where
		Where did he lead me?

11. He hid a large parcel under his desk. Where/What/Who
		Where did he hide a large parcel?
		What did he hide under his desk?
		Who hid a large parcel under his desk?

12. He was very embarrassed. Who/Why
		Who was very embarrassed?
		Why was he very embarrssed?

** Summary Writing
Hugh is so fat that he has gone on a diet.
He has forbidden himself all the foods he likes, but he hasn't lost his weight.
He hid a large parcel under his desk when the writer visited him yesterday.
The parcel contained chocolate and sweets.
Hugh said that had to reward himeself occiasionally because his diet was so strict.

** Topics for discussion
1. Have you ever tried to give up something you like? Why? How successful were you?
	 I have tried to give up smoking because I am unhealty.
	 I tried to stop smoking for two weeks, then I succeed in giving up smoking.

2. Fat people are often very kind, cheerful and contented.
	 Can you suggest why such people might tend to be fat rather than thin?
	 They has been very hungry when they were very young.

3. What kind of bad habits are most difficult to break? Why?
	 Smoking.
	 You'll have a difficult time to forbid yourself to smoke.

