* L52 A pretty carpet
What is the writer's carpet made of?

We have just moved into a new house and I have been working hard all moring.
I have been trying to get my new room in order.
This has not been easy because I own over a thousand books.
To make matters worse, the room is rather small, so I have temporarily put my books on the floor.
At the moment, they cover every inch of floor space
	and I actually have to walk on them to get in or out of the room.
A short while ago, my sister helped me to carry one of my old bookcases up the stairs.
She went into my room and got a big surprise when she saw all those books on the floor.
'This is the prettiest carpet I have ever seen,' she said.
She gazed at it for some time then added,
	'You don't need bookcases at all. You can sit here in your spare time and read the carpet!'

** Pattern drill
1. upset-say goodbye to a friend
	 You look upset. What've you been doing?
	 I've been saying goodbye to a friend.

	 dirty-clean the garage
	 You look dirty. What've you been doing?
	 I've been cleaning the garage.

	 wet-walk in the rain
	 You look wet. What've you been doing?
	 I've been walking in the rain.

	 tired-work late
	 You look tired. What've you been doing?
	 I've been working late.

	 angry-fight
	 Your look angry. What've you been doing?
	 I've been fighting.

2. book-read-all day
	 Have you finished that book already!
	 Well, I've been reading it all day!

	 speech-prepare-all evening
	 Have you finished that speech already!
	 Well, I've been preparing it all evening!

	 book-study-all term
	 Have you finished that book already!
	 Well, I've been studying it all term.

	 work-do-all morning
	 Have you finished that work already!
	 Well, I've been doing it all morning.

	 fruit-eat-all evening
	 Have you finished that fruit already!
	 Well, I've been eating it all evening.

3. take their exams
	 Have they been taking their exams?
	 Yes, they have. They've taken five of them so far.

	 make the beds
	 Have they been making the beds?
	 Yes, they have. They've made five of them so far.

	 play their CDs
	 Have they been playing their CDs?
	 Yes, they have. They've played five of them so far.

	 open their presents
	 Have they been opening their presents?
	 Yes, they have. They've opened five of them so far.

	 correct the essays
	 Have they been correcting the essays?
	 Yes, they have. They've corrected five of them so far.

4. ring John up
	 Why hasn't she rung John up yet?
	 What do you mean? She's been ringing him up all morning.

	 do the housework
	 Why hasn't she done the housework yet?
	 What do you mean? She's been doing it all morning.

	 speak to Mary
	 Why hasn't she spoken to Mary yet?
	 What do you mean? She's been speaking to Mary all morning.

	 practise the piano
	 Why hasn't she practised the piano?
	 What do you mean? She's been practising the piano all morning.

	 do the washing
	 Why hasn't she done the washing?
	 What do you mean? She's been doing the washing  all morning.

* Ask questions
1. We've just moved into a new house. Where ... to
	 Where have you just moved to?

2. I've been working hard all morning. How long/Why/Who
	 How long have you been working hard?
	 Why have you been working hard all morning?
	 Who have been working hard all morning?

3. I've been trying to get my new room in order. What
	 What have you been trying to do?

4. This has been difficult. Why/What
	 Why has this been difficult?
	 What has been difficult?

5. I own over a thousand books. How many
	 How many books do you own?

6. The room is rather small. How big
	 How big is the room?

7. I've put the books on the floor. Where
	 Where have you put the books?

8. I have to walk on them to get in or out of the room. Why/When/What
	 Why do you have to walk on them?
	 When do you have to walk on them?
	 What do you have to walk on to get in or out of the room?

9. My sister helped me a short time ago. When/Who
	 When did my sister help me?
	 Who helped you a short time ago.

10. She got a big surprise. Who/When
		Who got a big surprise?
		When did she get a big surprise?

** summary writing
The writer has been trying to get his new room in order all morning.
This has proved difficult becase he owns over a thousand books
	which covered every inch of floor space at the moment.
His sister helped him to carry one of old bookcases up the stairs a short while ago.
She got a surprise when she saw his room, but she thought that the books made a pretty carpet.

** Topics for discussion
1. Do you enjoy moving house/changing the furniture in your room? Why/Why not?
	 I am tired of moving house.
	 It's a waste of money that we change the furniture in my room.
2. What sorts of books do you like reading? Give reasons for you choice.
	 I like program , science books.
	 It's useful and I find them insteresting.
3. Some people prefer watching television to reading books. Can television take the place of books?
	 Why/Why not?
	 Yes. Television contains more informations than books.
	 It includes video.
