* L53 Hot snake

What caused the fire?

At last fireman have put out a big forest fire in California.
Since then, they have been trying to find out how the fire began.
Forest fires are often caused by broken glass
	or by cigarette ends which people carelessly throw away.
Yesterday the fireman examined the ground carefully, but were not able to find any broken glass.
They were also quite sure that a cigarette end did not start the fire.
This morning, however, a fireman accidentally discovered the cause.
He noticed the remains of a snake
	which was wound round the electric wires of a 16,000-volt power line.
In this way, he was able to solve the mystery.
The explanation was simple but very unusual.
A bird had snatched up the snake from the ground and then dropped it on to the wires.
The snake then wound itself round the wires.
When it did so, it sent sparks down to the ground and these immediately started a fire.

** words
hot adj. 带电的
fireman n.
cause v.
examine v.
accidently adv.
remains n.
wire n.
volt n.
power line
solve v.
mystery n.
snatch v.
spark n.

** Pattern Drill
1T: a shoemarker
S1: How long have you been a shoemarker?
S2: I've been making shoes for a long time.

a stamp collector
	How long have you been a stamp collector?
	I've been collecting stamps for a long time.

a horse trainer
	How long have you been a horse trainer?
	I've been training horses for a long time.

a boat builder
	How long have you been a boat builder?
	I've been building boats for a long time.

a tax collector
	How long have you been a tax collector?
	I've been collecting taxs for a long time.


2T: teach - a year
S1: He didn't teach there for long, did he?
S2: No, he taught there for a year and then he left.

work-a few months
He didn't work there for long, did he?
No, he worked there for a year and then he left.

stay-two days
He didn't stay there for long, did he?
No, he stayed there for a year and then he left.

wait-half an hour
He didn't waited there for long, did he?
No, he waited there for a year and then he left.

sit-five minutes
He didn't sit there for long, did he?
No, he sat there for a year and then he left.

3T: dictionary
S1: Could you lend me your dictionary?
S2: I'm sorry, I lent it to Tom last week and he hasn't returned it yet.

suitcase
	Could you lend me your suitcase?
	I'm sorry, I lent it to Tom last week and he hasn't returned it yet.

bicycle
	Could you lend me your bicycle?
	I'm sorry, I lent it to Tom last week and he hasn't returned it yet.

French books
	Could you lend me your French books?
	I'm sorry, I lent them to Tom last week and he hasn't returned it yet.

car
	Could you lend me your car?
	I'm sorry, I lent it to Tom last week and he hasn't returned it yet.

** Asking questions
1. There's been a big forest fire in California. Where
	 Where has there been a big forest fire?
	 
2. Firemen have put it out. What/Who
	 What have firemen put out?
	 Who have put out the forest fire?

3. They've been trying to discover the cause. What/Who
	 What have they been trying to discover?
	 Who have been trying to discover the cause?

4. Fires are often caused by broken glass. What... by/How/What
	 What are Fires often caused by?
	 How are fires often caused?
	 What are often caused by broken glass?

5. They're also cauesd by cigarette ends. What else
	 What else are they also caused by?

6. The firemen examined the ground yesterday. When/What/Who
	 When did the firemen examine the ground?
	 What did the firemen examine yesterday?
	 Who examined the ground yesterday?

7. They looked for broken glass. What
	 What did they look for?

8. A fireman discovered the cause accidentally. How /What/Who
	 How did a fireman discover the cause?
	 What did a fireman discover accidentally?
	 Who discovered the cause accidentally?

** Summary writing
Now that firemen have put out a big forest fire in California.
	They have been trying to discover its cause.
- Now that: 由于
There was not any evidence that it was started by broken glass or by a cigarette end.
- There was no evidence that it was started by broken glass or by a cigarette end.
However, a fireman has just solved the mystery.
He noticed the remains of a snake which had been dropped by a bird on to some electric wires.
In winding it round itself, it had sent sparks down to the ground and this caused the fire.
- In winding itself round the wires, the snake had sent sparks to the ground and this caused the fire.

** Topics for discussion
1. Describe a fire you've seen or heard about.
	 When I was very young, a big fire was caused by my aunt.
	 Before she went to sleep, she had forgot to put out the fire which was boiling the water.

2. What are the most common causes of fires in towns/houses?
	 How can ordinary people help to prevent them?
	 Cigarette ends.
	 People must find out they have put out the fire after they finish smoking.

3. In what ways can modern techology endanger wild life?
	 By using smoke detectors.
