* L54 Sticky fingers 黏糊的
What two interruptions did the writer have?

After breakfast, I sent the children to school and then I went to the shops.
It was still early when I returned home.
The children were at school, my husband was at work and the house was quiet.
So I decided to make some meat pies.
In a short time I was busy mixing butter and flour and
	my hands were soon covered with sticky pastry.
At exactly that moment, the telephone rang.
Nothing could have been more annoying.
I picked up the receiver between two sticky fingers and
	was dismayed when I recognized the voice of Helen Bates.
It took me ten minutes to persuade her to ring back later.
At last I hung up the receiver.
What a mess!
There was pastry on my fingers, on the telephone, and on the doorknobs.
I had no sooner got back to the kitchen than the doorbell rang loud enough to wake the dead.
- I had hardly got back to the kitchen when the doorbell rang loud enough to wake the dead.
This time it was the postman and he wanted me to sign for a registered letter!

** words
sticky adj.
finger n.
pie n.
mix v.
pastry n.
annoying adj.
receiver n.
dismay v.
recognize v.
persuade v.
mess n.
doorknob n.
sign v.
register v.

had no sooner done ... than...
had hardly done ... when...

** Asking questions
1. I sent the children to school after breakfast. When/Where
	 When did you send the children to school?
	 Where did you send the children after breakfast?

2. I went to the shops. Where/When
	 Where did you go?
	 When did you go to the shops?

3. It was still early when I returned home. What time
	 What time was it still early?

4. My children were at school. Who/Where
	 Who were at school?
	 Where were your children?

5. My husband was at work. Where/Who
	 Where was your husband?
	 Who was at work?

6. I decided to make some meat pies. What
	 What did you decide to do?

7. I mixed some butter and flour. What
	 What did you mix?

8. My hands were soon covered with sticky pastry. What ... with
	 What were your hands soon covered with?

9. The telephone rang just then. When
	 When did the telephone ring?

10. I felt extremely annoyed. How
		How did you feel annoyed?

11. It was Helen Bates. Who
		Who was it?

** Summary writing
As soon as she returned from the shops, the writer began to make some meat pies.
When the telephone rang soon afterwards, her fingers were very sticky.
She spend ten minutes talking to Helen Bates on the telephone.
After that she looked at the mess she had made.
The fingers, the telephone and doorknobs were covered with pastry.
Just then the postman rang the doorbell.
He wanted her to sign for a registered letter.

** Composition
1. I put the cake in the oven. I forgot all about it. After putting
	 After putting the cake in the oven, I forgot all about it.

2. Two hours had passed. I smelled something burning. When
	 Two hours had passed when I smelled something burning.
	 When two hours had passed, I smelled something burning. when也可以用过去完成时

3. I went into the kitchen. I found it full of smoke. On going
	 On going into the kitchen, I found it full of smoke.

** Topics for discussion
1. Describe how you would bake a cake/make one of your favourite dishes.
	 First of all, I wash the vegetables and beef.
	 Then, I wash the dishes.
	 Next, I cook beef.
	 Finally, I am busy having beef with my wife.
	 
2. Do you enjoy visiting the shops?
	 Describe a typical shopping day.
	 No, I don't.
	 November 11th, there are a great many of online shoppings.

3. It is possible that in future we shall be able to see,
		 as well as hear people when we use the telephone.
	 Do you think this is a good idea? Why/ Why not?
	 Dreams of seeing people by the telephone have came true.
	 Yes. If you are in another city, you can see your old friend and your parents by the telephone.
