* L56 Faster than sound!
How fast did the winning car go?

Once a year, a race is held for old cars.
A lot of cars entered for this race last year
	and there was a great deal of excitement just before it began.
One of the most handsome cars was a Rolls-Royce Silver Ghost.
The most unusual car was a Benz which had only three wheels.
Built in 1885, it was the oldest car taking part.
After a great many loud explosions, the race began.
Many of the cars broke down on the course
	and some drivers spent more time under their cars than in them!
A few cars, however, completed the race.
The winning car reached a speed of forty miles an hour - much faster than any of its rivals.
It sped downhill at the end of the race and its driver had a lot of trouble trying to stop it.
The race gave everyone a great deal of pleasure.
It was very different from modern car races but no less exciting.

race - held - old cars
last year - excitement - just before
handsome - Rolls-Royce Silver Ghost
unusall - Benaz - three wheels
1885 - oldest car - taking part
loud explosions - race - began
broke down - course - under .. than in ..
a few - completed
winning car - a speed of forty miles an hour - its rivals
downhill - trouble - trying to stop
gave - a great deal of - pleasure
different - modern - no less

** words
sound n.
excitement n.
handsome adj.
Rolls-Royce
Benz n.
wheel n.
explosion n.
course n. 跑道;行程
rival n. 对手
speed v. 疾驶
downhill adv. 下坡

** Pattern Drill
1T: tall
S1: Are you as tall as John?
S2: I don't think so. I think John's a little taller than me.
clever
	Are you as clever as John?
	I don't think so. I think John's a little cleverer than me.

unlucky
	Are you as unlucky as John?
	I don't think so. I think John's a little unluckier than me.

efficient
	Are you as efficient as John?
	I don't think so. I think John's a little more efficient than me.

hard-working
	Are you as hard-working as John?
	I don't think so. I think John's a litte more hard-working than me.

2T: tall brother - height
S1: My brother is much taller than yours.
S2: He isn't! They're about the same height.
old house - age
	My house is much older than yours.
	It isn't! They're about the same age.

heavy parcel - weight
	My parcel is much heavier than yours.
	They aren't! They're about the same weight.

large shoes - size
	My shoes are much larger than yours.
	They aren't! They're about the same size.

long ruler - length
	My ruler is much longer than yours.
	It isn't! It's about the same length.

3T: Scotch - Irish  whisky
S1: Is Scotch whisky very different from Irish whisky?
S2: A Scot could tell you better than I can!
French - Italian wine
	Is French wine very different from Italian wine?
	A French could tell you better than I can!

American - British English
	Is American English very different from British English?
	An American could tell you better than I can!

German - Japanese stereos
	Are German stereos very different form Japanese stereos?
	An German could tell you better than I can!

Portuquese - Spanish art
	Is Portuquese art very different from Spanish art?
	A Portuquese could tell you better than I can!

4T: take jam
S1: What a lot of jam Tom's taken!
S2: Yes, he's taken much more than he did yesterday.
drink beer
	What a lot of beer Tom's drunk!
	Yes, he's drunk much more than he did yesterday.

do work
	What a lot of work Tom's done!
	Yes, he's done much more than he did yesterday.

paint pictures
	What a lot of pictures Tom's painted!
	Yes, he's painted many more than he did yesterday.

break glasses
	What a lot of glasses Tom's broken!
	Yes, he's broken many more than he did yesterday.

** Asking questions
1. The race for old cars is held once a year. How often
	 How often is the race for old cars held?

2. A lot of cars entered for it last year. How many / When
	 How many cars enterd for it last year?
	 When did a lot of cars enter for it?

3. One of the most handsome cars was a Rolls-Royce Silver Ghost. Which
	 Which car was a Rolls-Royce Silver Ghost?

4. The most unusual car was a Benz. Which
	 Which car was the most unusual car?

5. It had only three wheels. How many
	 How many wheels did it have?

6. It was built in 1885. When/What
	 When was it built?
	 What was built in 1885?

7. The race began with a great many loud explosions. How/Why
	 How did the race begin?
	 Why did the race begin with a great many loud explosions?

8. Many of the cars broke down on the course. How many / Where
	 How many cars broke down on the course?
	 Where did many of the cars break down?

9. A few completed the race. How many
	 How many completed the race?
	 
** Summary Writing
- A lot of old cars entered for the race.
- It is held once a year.
- 
- A great many loud explosions could be heard when they set off.
- Many cars broke donw during the race.
- A few managed to complete the course.
- 
- The winning car went downhill quickly.
- Its driver had a lot of difficulty trying to stop it.
A lot of old cars entered for the race which is held once a year.
A great many loud explosions could be heard when the cars set off
	and though many cars broke down during the race,
	a few managed to completed the course.
The winning car went downhill so quickly that its driver had a lot of difficulty trying to stop it.
	
** Composition
1. There was a loud explosion. My old car stopped. and
	 There was a loud explosiong and my old car stopped.
2. I got out. I wanted to have a look at the engine. to
	 I got out to have a look at the engine. 表目的
3. Then a man passed me. He was driving a large modern car. a man who
	 Then a man who was driving a large modern car passed me.
4. I waved to him. He did not stop. but
	 I waved to him but he did not stop.
5. I passed the large car later. Its driver was changing a wheel. When
	 When I passed the large car later, its driver was changing a wheel.

** Topics for discussion
1. Do you think old cars should be used or kept in museums? Why?
	 I think old cars shouldn't be used.
	 Because they may break down on the course, and their drivers will spent more time under them than in them.
2. Would you prefer to own something very old or very modern? Why?
	 I prefer to own something very old.
	 I think things are growing up.
3. Imagine it is the year 2100. In what way do you think things like cars, aeroplanes, buildings, ect. will differ from those of today?
	 Cars will be faster.
	 Aeroplanes will be more personal.
	 Building will be higher.
