#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* L57 Can I help you, madam?
#+begin_verse
Did the woman get what she wanted?

A woman in jeans stood at the window of an expensive shop.
Though she hesitated for a moment,
	she finally went in and *asked to see* a dress that was in the window.
The assistant who served her did not the way she was dressed.
Glancing at her scornfully, he told her that the dress was sold.
The woman walked out of the shop angrily and decided to punish the assistant next day.
She returned to the shop the following morning *dressed in* fur coat,
	with a handbag in one hand and a long umbrella in the other.
After *seeking out* the rude assistant, she asked for the same dress.
Not realizing who she was, the assistant *was eager to serve* her this time.
With great difficulty, he climbed into the shop window to get the dress.
As soon as she saw it, the woman she did not like it.
She enjoyed herself marking the assistant bring almost everything in the window
	before finally buying the dress she had first asked for.
#+end_verse
