* L63 She was not amused
Why did Jenny want to leav the wedding reception?

Jeremy Hampden has a large circle of friends and is very popular at parties.
Everybody admires him for his great sense of humour
	- everybody, that is, except his six-year-old daughter, Jenny.
Recently, one of Jeremy's closest friends asked him to make a speech at a wedding reception.
This is the sort of thing that Jeremy loves.
He prepared the speech carefully and went to the wedding with Jenny.
He had included a large number of funny stories in the speech and,
	of course, it was great success.
As soon as he had finished, Jenny told him she wanted to go home.
Jeremy was a little disappointed by this but he did as his daughter asked.
On the way home, he asked Jenny if she had enjoyed the speech.
To his surprise, she said she hadn't.
Jeremy asked her why this was so
	and	she told him that she did not like to see so many people laughing at him.
	
** words
circle [ˈsɜːk(ə)l] n. 圈子
admire [ədˈmaɪə(r)] v. 赞美
close [kləʊz] adj. 亲密的
wedding [ˈwedɪŋ] n. 婚礼
reception [rɪˈsepʃ(ə)n] n. 招待会
sort [sɔːt] n. 种类

** Pattern drill
1T: Be quiet!
S1: The teacher's telling you to be quiet.
S2: He's telling you to be quiet, too!
Take out - your exercise books!
	The teacher's taking out your exercise books.
	He's telling you to take out your exercise books, too!

Write out - the exercise on page ninety!
	The teacher's telling you to write out the exercise on page ninety!
	He's telling you to write out, too!

Look at - the words on the board!
	The teacher's telling you to look at the words on the board.
	He's telling you to look at, too!

Open - your books!
	The teacher's telling you to open your books.
	He's telling you to open, too!

2T: Please lend me a book
S1: She asked me to lend her a book.
S2: I advise you not to lend her anything!
buy me a present
	She asked me to buy her a present.
	I advise you not to buy her anything.

tell me a joke
	She asked me to tell her a joke.
	I advise you not to tell her anything.

bring me a glass
	She asked me to bring her a glass.
	I advise you not to bring her anything.

sell me some tickets
	She asked me to sell her some tickets.
	I advise you not to sell her anything.

3T: Why don't they pay her?
S1: He suggested that they should pay her.
S2: I hope they won't pay her!
sell the flat
	He suggested that they should sell the flat.
	I hope they won't sell the falt!

call a strike
	He suggested that they should call a strike.
	I hope they won't call a strike.

cut the tree down
	He suggested that they should cut the tree down.
	I hope they won't cut the tree down.

punish him
	He suggested that they should punish him.
	I hope they won't punish him.

4T: You must stay!
S1: He's still insisting that we should stay.
S2: Oh dear! His wife's just warned me not to stay!
help him
	He's still insisting that we should help him.
	Oh dear! His wife's just warned me not to help him!

sign the contract
	He's still insisting that we should sign the contract.
	Oh dear! His wife's just warned me not to sign the contract.

join them
	He's still insisting that we should join them.
	Oh dear! His wife's just warned me not to join them.

refuse the money
	He's still insisting that we should refuse the money.
	Oh dear! His wife's just warned me not to refuse the money.

** Asking questions
1. Jeremy Hampden has a large circle of friends. Who / How many
	 Who has a large circle of friends?
	 How many friends does Jeremy Hampden have?

2. He's very poular at parties. Where
	 Where is he very popular?

3. Everyone admires him for his sense of humour. Why
	 Why does everyone admire him?

4. His daughter is called Jenny. What
	 What is his daughter called?

5. She's six year old. How old
	 How old is she?

6. One of Jeremy's friends asked him to make a speech recently. When/Who
	 When did one of Jeremy's friends ask him to make a speech?
	 Who asked him to make a speech recently?

7. His friend wanted him to speak at a wedding reception. Where
	 Where did his friend want him to speak?

8. Jeremy loves this sort of thing. What
	 What does Jeremy love?

9. He prepared the speech carefully. How
	 How did he prepare the speech?

10. He took Jenny to the wedding. Who
		Who did he take to the wedding?
	
** Summary writing

When Jeremy Hampden who is greatly admired for his great sense of humour
	was invited to make a speech, he immediately agreed to do so.
Since the speech contained a lot of funny stories, it was a great success.
When his six-year-old daughter, Jenny, wanted to go home after his speech, Jeremy was disappointed.
She hadn't enjoyed it because she didn't like to see so many people laughing at him.

** Topics for discussion
1. Do you know any funny stories? Tell us one.
	 A beautiful girl sat down behind me and she had a package of biscuits.
	 Then a boy came to sit together.
	 As soon as he sat down, he snatched biscuits.
	 I was so hungry that I snatched too.
	 In the end, they kissed and said goodbye to me.
	 I was very embarrassed.

2. Describe a wedding you have been to.
	 A car was broken by me at my uncle's wedding.

3. What kind of speeches do you find boring/interesting?
	 Have you ever felt 'embarrassed' for the speaker? Why?
	 The leaders' speeches were always boring.
	 I felt extremely 'embarrased' for the men who were always telling lies to people.

