* L66 Sweet as honey!
What was 'sweet as honey' and why?

In 1963 a Lancaster bomber crashed on Wallis Island,
	a remote place in the South Pacific,
	a long way west of Samoa.
The plane wasn't too badly damaged,
	but over the years,	the crash was forgotten and the wreck remained undisturbed.
Then in 1989, twenty-six years after the crash,
	the plane was accidentally rediscovered in an aerial survey of the island.
By this time, a Lancaster bomber in reasonable condition was rare and worth rescuing.
The French authorities had the plane packeged and moved in parts back to France.
Now a group of enthusiast are going to have the plane restored.
It has four Rolls-Royce Merlin engines,
	but the group will need to have only three of them rebuilt.
Imagine their surprise and delight when they broke open the packing cases
	and found that the fourth engine was sweet as honey - still in perfect condition.
A colony of bees had turned the engine into a hive and it was totally presevered in beeswax!

** words
Lancaster n. 兰开斯特
bomber [ˈbɒmə(r)] n. 轰炸机
remote [rɪˈməʊt] adj. 偏僻的
Pacific [pəˈsɪfɪk] n. 太平洋
damage [ˈdæmɪdʒ] v. 毁坏
wreck [rek] n. 残骸
rediscover [ˌriːdɪˈskʌvə(r)] v. 重新发现
aerial [ˈeəriəl] adj. 航空的
survey [ˈsɜːveɪ] n. 调查
rescue [ˈreskjuː] v. 营救
package [ˈpækɪdʒ] v. 把...打包
enthusiast [ɪnˈθjuːziæst] n. 热心人
restore [rɪˈstɔː(r)] v. 修复
imagine [ɪˈmædʒɪn] v. 想象
packing [ˈpækɪŋ] case n. 包装箱
colony [ˈkɒləni] n. 群
bee [biː] n. 蜂
hive [haɪv] n. 蜂房
preserve [prɪˈzɜːv] v. 保护
beeswax [ˈbiːzwæks] n. 蜂蜡

** Pattern drill
1T: make the cake
S1: Did she make the cake herself?
S2: Good heavens no! She had it made in town.
cut her hair
	Did she cut her hair herself?
	Good heavens no! She had it cut in town.

make the curtains
	Did she make the curtains herself?
	Good heavens no! She had it made in town.

clean her boat
	Did she clean her boat herself?
	Good heavens no! She had it cleaned in town.

mend the typewriter
	Did she mend the typewriter herself?
	Good heavens no! She had it mended in town.
2T: hair-cut
S1: How nice your hair looks!
S2: Thank you. I've just had it cut.
carpet-cleaned
	How nice your carpet looks!
	Thank you. I've just had it cleaned.

kitchen-painted
	How nice your kitchen looks!
	Thank you. I've just had it painted.

floor-polished
	How nice your floor looks!
	Thank you. I've just had it polished.

house-redecorated
	How nice your house looks!
	Thank you. I've just had it redecorated.

3T: photos - your passport - taken
S1: You'll need some photos for your passport.
S2: I'll have some taken next week.
heating fires -the winnter- installed
	You'll need some heating fires for the winnter.
	I'll have some installed next week.

warm clothes-the journey-made
	You'll need some warm clothes for the journey.
	I'll have some made next week.

oil belts-your car-put in
	You'll need some oil belts for your car.
	I'll have some put in next week.

tables-the meeting-sent round
	You'll need some tables for the meeting.
	I'll have some sent round next week.

4T: clean his suit
S1: He says he's got to clean his suit.
S2: He can't clean it himself! Why doesn't he have it cleaned?
mend the stereo
	He says he's got to mend the stereo.
	He can't mend it himself! Why doesn't he have it mended?

test the engine
	He says he's got to test the engine.
	He can't test it himself! Why doestn't he have it tested?

paint the gate
	He says he's got to paint the gate.
	He can't paint it himself! Why doesn't he have it painted?

cut the trees down
	He says he's got to cut the trees down.
	He can't cut them down himselft. Why doesn't he have them cut down?

** Asking questions
1. In 1963 a Lancaster bomber crashed on Wallis Island. When/What/Where
	 When did a Lancaster bomber crash on Wallis Island?
	 What crashed on Wallis Island in 1963?
	 Where did a Lancaster bomber crash on Wallis Island in 1963?

2. The island is a long way west of Samoa. Where
	 Where is the island?

3. The plane wasn't too badly damaged. Why
	 Why wasn't the plane too badly damaged?

4. The wreck remained undisturbed. Why
	 Why did the wreck remain undisturbed?

5. It was rediscovered in 1989. When
	 When was it rediscovered?

6. The French authorities had the plane packaged and moved to France.Who /What
	 Who had the plane packaged and moved to France?
	 What did the French authorities had packaged?

7. Enthusiast are going to have it restored. Who/What
	 Who are going to have it restored?
	 What are enthusiast going to have restored?

8. They need to rebuild three of the four engines. How many
	 How many engines do they need to rebuild.

9. The fourth engine was still in perfect condition. How/What...like
	 How was the fourth engine?
	 What did the fourth engine like?
	 
** Summary writing
The Lancaster bormer wasn't too badly damaged
	when it crashed on a remote island in the south Pacific.
Then the wreck remained undisturbed for twenty-six years
	until it was discovered in an aerial suvery of the island.
The French authorities have the plane packed and moved in parts back to France where
	enthuziasts will be having it restored.
They will have to have three of engines rebuilt,
	but the fourth engine still in perfect condition
	because it was presevered in beeswax.

** Topics for discussion
1. Tell us about any plane crash you've heard about recently.
	 It's MH370 which crashed on the Tuzhu Island,
		a remote place in the South Pacific,
		a way east of Kota Bharu.
	 The C authorites said that the plane was defective product.
	 However, recently, people found out that the captain drove it towards the ground.
	 It's fairly certain that the captain had made big mistakes.
	 Finally, the C authorities lies to people.

2. Tell us about the pleasure of restoring old cars or planes.
	 Imagine our surprise and delight
		when we found that the old cars got fresh and could be used again.

3. Tell us about what you know about the habits of bees.
	 When I was very young, I touch a bee and it bit me very hard.
	 After I can't feel my finger, I touched it carefully.
	 In the end, my father sent me to the hospital.
