#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* labyrinths
#+begin_verse
Labyrinths have existed for well over 4,000 years.
Labyrinths and labyrinthine symbols have been found in regions
	as diverse as modern-day Turkey, Ireland, Greece, and India.
There are various designs of labyrinth
	but what they all have in common is a winding spiral path
		which leads to a central area.
There is one starting point at the entrance and the goal is to reach the central area.
Finding your way through a labyrinth involves many twists and turns,
	but it's not possible to get lost as there is only one single path.
	
In modern times, the word labyrinth has taken on a different meaning
	and is often used as a synonym for a maze.
A maze is quite different
	as it is a kind of puzzle with an intricate network of paths.
Mazes became fashionable in the 15th and 16th centuries in Europe,
	and can still be found in the gardens of great houses and palaces.
The paths are usually surrounded by thick, high hedges
	so that it's not possible to see over them.
Entering a maze usually involves getting lost a few times
	before using logic to work out the pattern
		and find your way to the centre and then out again.
There are lots of dead ends and paths which lead you back to where you started.
The word 'maze' is believed to come from a Scandinavian word for a state of confusion.
This is where the word 'amazing' comes from.

Labyrinths, on the other hand, have a very different function.
Although people now often refer to things they find complicated as labyrinths,
	this is not how they were seen in the past.
The winding spiral of the labyrinth has been used for centuries as a metaphor for life's journey.
It served as a spiritual reminder
	that there is purpose and meaning to our lives and helped to give people a sense of direction.
Labyrinths are thought to encourage a feeling of calm
	and have been used as a meditation and prayer tool in many cultures over many centuries.
	
The earliest examples of the labyrinth spiral pattern have been found carved into stone,
	from Sardinia to Scandinavia, from Arizona to India to Africa.
In Europe, these spiral carvings date from the late Bronze Age.
The Native American Pima tribe wove baskets with a circular labyrinth design
	that depicted their own cosmology.
In Ancient Greece, the labyrinth spiral was used on coins around four thousand years ago.
Labyrinths made of mosaics were commonly found
	in bathhouses, villas and tombs throughout the Roman Empire.
	
In Northern Europe, there were actual physical labyrinths designed for walking on.
These were cut into the turf or grass, usually in a circular pattern.
The origin of these walking labyrinths remains unclear,
	but they were probably used for fertility rites which may date back thousands of years.
Eleven examples of turf labyrinths survive today,
	including the largest one at Saffron Walden, England,
		which used to have a large tree in the middle of it.
		
More recently labyrinths have experienced something of a revival.
Some believe that walking a labyrinth promotes healing and mindfulness,
	and there are those who believe in its emotional and physical benefits,
		which include slower breathing and a restored sense of balance and perspective.
This idea has become so popular
	that labyrinths have been laid into the floors of spas,
		wellness centres and even prisons in recent years.
		
A pamphlet at Colorado Children's Hospital informs patients
	that 'walking a labyrinth can often calm people in the midst of a crisis'.
And apparently, it's not only patients who benefit.
Many visitors find walking a labyrinth less stressful than sitting in a corridor or waiting room.
Some doctors even walk the labyrinth during their breaks.
In some hospitals,
	patients who can't walk can have a paper 'finger labyrinth' brought to their bed.
The science behind the theory is a litle sketchy,
	but there are dozens of small-scale studies
		which support claims about the benefits of labyrinths.
For example, one study found
	that walking a labyrinth provided 'short-term calming, relaxation, and relief from anxiety'
		for Alzheimer's patients.
		
So, what is it about labyrinths that makes their appeal so universal? Well ...
#+end_verse
** expression
winding: adj. 弯曲的
spiral: n. a line in the form of a curve that winds around a central point, moving further away from the centre all the time
labyrinth: labyrinthine  adj.
	a large network of paths or passages which cross each other, making it very difficult to find your way
Bronze:a hard metal that is a mixture of copper and tin
cosmology: the science of the origin and structure of the universe, especially as studied in astronomy
mosaics: a pattern or picture made by fitting together small pieces of coloured stone, glass etc
villa:a big house in the country with a large garden
tomb: a stone structure above or below the ground where a dead person is buried
turf:a surface that consists of soil with grass on top, or an artificial surface that looks like this
revival: a process in which something becomes active or strong again
promote:to help something to develop or increase
restored:feeling better and stronger
wellness:the state of being healthy
pamphlet:a very thin book with paper covers, that gives information about something
crisis:a situation in which there are a lot of problems that must be dealt with quickly so that the situation does not get worse or more dangerous
corridor:a long narrow passage on a train or between rooms in a building, with doors leading off it
sketch:not thorough or complete, and not having enough details to be useful
--------------------
for st.: eg. for 1000 years
as diverse as: including many different types of people or things
have in common
lead to sp.
starting point
at the entrance
the goal is to do sth.
reach sp.
twists and turns: 玩玩扰扰
find sb's way (to sp.)
involve sth./doing sth.
it's not possible to do sth.
get adj.: be adj.
in modern times
take on: 用作
be used as: 被用作
a synonym for A: a word with the smeaning as another word in the slanguage
intricate: adj. containing many small parts or details that all work or fit together
a network of paths: 网状道路
become fashionable
be surrounded by sth.:
see over sp.: to walk around and examine (a place) carefully
hedges: a row of small bushes or trees growing close together, usually dividing one field or garden from another
use sth. to do sth.
work out
dead ends
be believed to do sth.
come from sp.
a state of confusion
refer to A as B
a metaphor for sth.
serve as: 被用于
a spiritual reminder: relating to your spirit rather than to your body or mind
purpose and meaning to our lives
help to do sth.
give sb. sth.
a sense of direction
be thought to do sth.
a feeling of sth.
the examples of sth.
be found done sth.: 被发现被做某事
be carved into stone: 被雕刻到石头
date from tp.
be used on sth.
around xx years ago
be made of
be designed for doing
be cut into
in a circular pattern
remain unclear: is unclear
fertility rites: 生育仪式
date back thousands of years
in the middle of sth.
experience a revival:
something of: to some degree
believe in sth.
a sense of sth.
be laid into: 被放置在
in recent years
inform sb. that ...
in the midst of sth.
find doing A adj.-er than doing B
during sb's breaks
be brought to sp.
dozens of sth.
for example
one study found that ...
relief from anxiety
make sth. adj.
