So, one thing that you also mentioned was,
	you know, we talked about individual differences in how people respond to emotions.
That's. You know, sort of at this.
This back-end of the model is
	often where cultural values, individual differences, personal histories, come into play
		and you know, shape the emotion experience as it occurs.
But also, all of these, you know, feedback arrows that go from,
	you know, how we respond to emotion to how we re-interpret.
This is what creates that dynamic that keeps spiral going.
Like a, a downward spiral for negative emotions.
Or, or an upwards spiral for positive emotions.
It's as if these.
Appraisals are these interpretive lenses that we get with an emotion.
kind of hang on and color the next circumstance.
So that when you're, when you're angry it's kind of like you have blame lenses on.
And you see everything else in terms of blame.
And this is how we get all these jags these, you know.
Emotional spirals.
So I don't want to leave you guys in the negative,
	but do you have any questions about this before we move along?
Were you talking about cognitive appraisal right there,
	so, the emotion happens
		and how you appraise it cognitively,
			is that what you're, is that what you're referring to?
			
Yeah.
This is sort of our, our mental mindset Okay. Of, of our circumstances.
Right.
Is what, you know, will determine the nature or the, the flavor of the negative emotion.
Or the, or the, positive emotion.
So, yeah.
I want to give you guys a, a chance to, you know, undo the last one.
And, experience something good.
So. Think of a time, just take a moment to think of a time that you know,
	things were going just so right for you.
When you know, whatever it was that happened made you kind of want to jump for joy, even.
So take a moment to relive that in your mind's eye.
Think about where you were, who you were with, what had just been happening.
And as you let that feeling grow, just observe, what does it.
Well, how does it feel?
What's the feeling on your face, in your body?
What does it make you want to do next?

You want more.
Yeah.
Yeah, definitely.
And you guys are so much more pleasant to look at, while you're, While you're reliving this.
So yeah, what else, what else stood out to you.

It's just a feeling of lightness and maybe sitting taller
	and I even found myself wanting to laugh out loud.
Yeah, just. Yeah. A feeling of joy.
Yeah, yeah so again, different flavor all together,
	but that, you know, showed up in sort of how you wanted to carry yourself.
	
Yeah. Anyone else?
I think mine was more pride,
	cause I was thinking a family member and,
		proud of what happened and kind of connection with my spouse because of that,
	so, it was more of a pride thing that came out.
Uh-huh, uh-huh, and so what did that make you want to do?
I don't, I don't, I don't know do wise I just,
	it was just made me feel really confident, I think and just comfortable.
So, I think comfort was the biggest thing.
Yeah, cool. Great example.

Mine is similar to that, so when you think about to do.
I'm thinking about sharing.
That you want people to know the recognition
	by looking at people or hugging or high five or fist bump
		but something when it's positive it's got to spread.
Exactly yeah I think one of the most common.
You know, action urges to use a jargon term
	that goes with positive emotions is share, be with others, hug, you know.
Find someone to share the good news with.
If you happen to be alone when something good happens
	it's like you gotta hurry up and try to find the next person.
You know, to, to share it with.

So, there are a lot of similarities between negative and positive emotions.
I mean, they, they're embodied feelings that you know,
	so just like negative emotions show up in, in, in how our muscles feel
		or how our faces feel, positive emotions do too.
And and just like negative emotions can be picked up by others.
You know, our positive emotions are going to show up in our posture.
How you carry yourself.
You know, and smiling.
Just that kind of, I mean, people kind of glow a little bit.
You know, there's like,
	there's a little bit of a radiance that starts to, you know, signal to others,
	yeah, here's a safe person, I want to connect here.
So they definitely have kind of a social broadcasting piece of them.
They show up in our voices and, and so on.
So that, you know, they have that embodied component.
They also, you know, stem from, all emotions stem from some change in our circumstance.
You know, something good for me, something bad for me has happened.
Now that circumstance can also be.
Mental circumstance.
So that you can create this through memory or through priority
	so you don't have to wait for something in the world to happen to create a positive emotion.
But how we interpret those is, is the, you know, sort of the gatekeeper as to
	whether this emotion is going to start.
We don't talk about coping with positive emotions in the same way
	you talk about coping with negative emotions.
Which is why I like the word response to emotion,
	because it's, it kind of fits with whether it's positive or negative.
But people still have values about whether, is this okay to feel, you know?
Some people feel like.
It's dangerous to feel good.
And so they kind of, try to speed past it really quickly.
But you know, so, equally,
	there's a kind of a matter of culture and personality,
	and, and sort of individual personal history
		that comes into shape whether people let a positive emotion kind of.
Fully bloom in a way or whether they're quick to move past it.

So. In schools we almost always attend to the negative posture face, you know.
And so I don't know if it's working with the school or working with my folks
	that if we ever recognize that this positivity is happening in kids.
Yeah, because you're so in tune to uh-oh, somethings wrong.
I need to address it.
Right, right. Well that's a great example of how, you know, the negative stuff just pops out
	because it's, you're typically signalling there's a, a problem to be addressed.
And and so one of the things that positive psychology can do is help us tune our eye to the.
To the other side of emotions, as well.
So we don't just think, you know, it's either ho-hum or negative.
Yeah. You know?
That there's a, there's a broader range.

This reminds of, of the athletic world.
And when you're talking about coaching.
The new wave of coaching, is that you focus on someone's strengths.
That's what you want to build up.
Now at the lower level, of course, you have to work on everything,
	but you know, college, professional sports,
	you have to develop the strengths
		and work in that versus just focusing on the negative, fix, fix, fix.
No, let's elevate the positive and work as a team, the collaboration.
Yeah, yeah. Oh, great example. Great example.

the, the spiraling aspect is, again, also very much in play with positive emotions.
And so just like a negative emotion kind of I,
	I feel like each emotion kind of implicitly takes as its job
		to recreate itself in the next minute.
So that, so that, you know, we have.
If we're angry or frustrated, we start seeing things in terms of blame.
And then that, that, kind of that, that blame game kind of takes over.
But the same can be true for positive emotions,
	like once we start feeling that oh, the situation I'm in is a gift, you know.
Then the next situation is a gift, and then gratitude starts to take hold.
And it's like this upward spiral that buoys you along.
So again, the dynamics that go with emotions are part of the,
	why they're, you know, I say they're the tiny engines
		that drive all of positive psychology because these spirals really can take off.
And each one kind of each emotion in this moment affects our emotions in the next moment.
And also, you know, to have this contagion effect too.

I, I have middle school daughters so I know the contagion effect well.
Because they either come in home really happy or not so happy.
And it does affect my emotion too.
Right, right.
It gives you different responsibility as a parent.
To be, you know, like. Echoing the right ones.
And, you know, trying to be there to receive the other ones.
So anyway, I'm, I think it's really important to get this foundation of emotions,
	not just being feelings but kind of a whole process.
That have this dynamic.
Spiraling potential.
Because that helps us see how we can make good use of that.
So thanks.
** expression

differences in: 
shape the emotion experience: 
spiral: 
It's as if + ...: 
get with sth.: 
hang on: 
