#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Reading to Learn the Art of Expression
#+begin_verse
When you read a short story, you may read it merely for pleasure.
When you read a biographical sketch, you may read it merely for information.
But as you are a learner of English, I think you should often read to learn the art of expression.
And for this purpose you may read either a short story or biographical sketch,
	either an essay or a news item, indeed, anything that is written in good current English.
	
Even from a short paragraph you may learn several forms of expression if you are observant enough.
Try to read the following paragraphs from BBC Modern English
	and notice the points of usage listed below.
	
Over 100 years ago she opened the first British hospital for women.
There are still very few of these hospitals in England.
This hospital is in Euston Road in London.
Its situation means that women from all over England can reach it quite easily.

Her aim when she opened the hospital was to provide a place
	where women could go and receive treatment from female doctors and nurses.
She also wanted the hospital to provide jobs for female doctors at a time
	when it was very difficult for them to find work.
Recently the authorities have tried to close the hospital.
They say that it is old-fashioned and wastes a lot of money.
However, the Government has decided that the hospital will stay open.
Many people feel very glad that the valuable service offered by this hospital will continue.

1. 'Over' More than.
2. 'in Euston Road' 'in ... Road'.
3. 'means that ...' 'means' takes an object clause introduced by 'that'.
4. 'from all over England' 'all over England' 'from all over England'.
5. 'receive treatment'. Patients receive treatment.
6. 'wanted the hospital to provide ...' 'We want them to do it'
7. 'at a time when ...' 'at a time when ...'
8. 'Recently the authorities have tried.' The present perfect is here used with recently
9. 'the Government has' 'the Government' can be considered singular.
10. 'decided that ...' 'Decided' takes an object clause introduced by 'that'.
11. 'stay open'. 'stay' can be a copulative verb.

In this way you will learn the art of expression very quickly;
	perhaps one or two paragraphs a day will teach you hundreds of forms of expression in a month,
	and these forms of expression will greatly improve your writing.
And if you can - I believe you can - commit to memory one or two paragraphs a day
	that you have alreay read in this way, the results will be still greater.
#+end_verse
*** expression
observant
- She is too observant to be spied on.
- The bodyguard was so observant that he caught a lot of thieves.
- If the bodyguard was observant enough, he would find out what it was like.
biographical sketch
- She is reading a biographical sketch which is written by Elon Musk.
- She couldn't afford to buy a biographical sketch when she was very young.
- On these occasions these biographical sketches will be sold out very quickly.
forms of ...
- There are several forms of expressions which are written by my students.
- She promised to provide me with hundreds of forms of expression.
- She claimed that studying these forms of expression would greatly improve my writing.
from all over England
- People from all over England are nervous about this panda which is found in China.
- Sorry to interrupt, but people from all over England have gathered round in front of our square. 
- People from all over England always receive a warm welcome
		at a time when it is difficult to find a job.
sb's aim is to do ...
- My wife's aim is to make a path around our house.
- His aim is to teach his dog to press his paw on the button.
- The beggar's aim is to stand on his head merely.
receive treatment (from sb.)
- He complained that his child didn't receive treatment from the doctor in the hospital.
- I wish that the poor men would receive treatment as well as the rich men.
- As he didn't receive treatment from his son, he went to the bar to grab a beer.
at a time when ...
- My cat was waiting for me behind the door at a time when I was busy working and got home late.
- Our vicar was always raising money at a time when the clock had been broken.
- She was waking up with a start at a time when the clock struck thirteen at one o'clock.
... clause
- To my surprise, 'of' takes an object clause introduced by 'what'.
- Mr. Leo has taught me an attribute clause.
- Believe it or not, you inappropriately recognized an object clause as an attribute clause.
stay adj.
- I wished that the hospital had stayed open.
- I wish that the hospital stayed open.
- If the hospital stayed open, you would receive treatment from female doctors.
