* War Bride Runs for Congress
#+begin_verse
A college drop-out and war bride of World War II,
  I raised three successful children and had a groundbreaking career in politics with campaigns,
    White House visits, and Presidential appointments.
At 62, I ran for Congress, the first woman in Virginia to be nominated by a major party.
Served 16 years (4 terms) as one of Virginia’s two elected representatives
  on the Republican National Committee, serving on the Executive Committee.
On first-name basis with Republican presidents from Gerald Ford forward.
Served 10 years on the White House Commission for Presidential Scholars.
Lost a close race for the state legislature but became valued aide to the majority leader.
Along the way, I graduated from college at age 54, the same day as my youngest child.
I was widowed at 82 and now, at 87, I have started Flo’s Bakery, LLC,
  to market mincemeat pie filling made from my greatgrandmother’s recipe.
#+end_verse
** expression
drop-out: n. 中途退学的人
bride [braɪd]: n. a woman at the time she gets married or just after she is married ⇨ groom新娘
groundbreaking [ˈɡraʊn(d)ˌbreɪkɪŋ]: adj. groundaking work involves making new discoveries, using new methods etc全新的
campaign [kæmˈpeɪn]: n. a series of actions intended to achieve a particular result relating to politics or business, or a social improvement运动
aide [eɪd] to sth./sb.: 辅助sth./sb.
recipe [ˈresəpi]: n. a set of instructions for cooking a particular type of food配方
