* War Bride Runs for Congress
#+begin_verse
A college drop-out and war bride of World War II,
  I raised three successful children and had a groundbreaking career in politics with campaigns,
    White House visits, and Presidential appointments.
At 62, I ran for Congress, the first woman in Virginia to be nominated by a major party.
Served 16 years (4 terms) as one of Virginia’s two elected representatives
  on the Republican National Committee, serving on the Executive Committee.
On first-name basis with Republican presidents from Gerald Ford forward.
Served 10 years on the White House Commission for Presidential Scholars.
Lost a close race for the state legislature but became valued aide to the majority leader.
Along the way, I graduated from college at age 54, the same day as my youngest child.
I was widowed at 82 and now, at 87, I have started Flo’s Bakery, LLC,
  to market mincemeat pie filling made from my greatgrandmother’s recipe.
#+end_verse
** expression
drop-out: n. 中途退学的人
bride [braɪd]: n. a woman at the time she gets married or just after she is married ⇨ groom新娘
groundbreaking [ˈɡraʊn(d)ˌbreɪkɪŋ]: adj. groundaking work involves making new discoveries, using new methods etc全新的
campaign [kæmˈpeɪn]: n. a series of actions intended to achieve a particular result relating to politics or business, or a social improvement运动
aide [eɪd] to sth./sb.: 辅助sth./sb.
recipe [ˈresəpi]: n. a set of instructions for cooking a particular type of food配方
** sentences
drop-out: n. 中途退学的人
- As a college drop-out, I was treated unfair by my father in our family.
- Watch and learn, that so-called college drop-out runs his huge international business.
- Why would you let such a college drop-out work for our corporation?
bride [braɪd]: n. a woman at the time she gets married or just after she is married ⇨ groom新娘
- She has been treated like an animal in the village because she was not a virgin as a bride-to-be.
- She looks amazing dressing up like a bride in the anniversary.
- No father would accuse a bride of her bad manners in her childhood. 
groundbreaking [ˈɡraʊn(d)ˌbreɪkɪŋ]: adj. groundbreaking work involves making new discoveries, using new methods etc全新的
- Our company is lack of energy, maybe we need to bring some new guys who are willing to do groundbreaking works.
- She got herself in trouble in this company in pursuit of groundbreaking works.
- The profit we have made last year is based on those groundbreaking rules our boss made.
campaign [kæmˈpeɪn]: n. a series of actions intended to achieve a particular result relating to politics or business, or a social improvement运动
- A great number of young student who has just gone to university lost their control in this campaign.
- The campaign proved successful, for sexual harassments almost can't be found in our communities.
- He advocates for a campaign in which we protect our foods from mouses.
aide [eɪd] to sth./sb.: 辅助sth./sb.
- She determined giving up her job aide to her child who has been taken a good care by her parents.
- I win a lot of praise aide to my direct manager.
- Aide to our boss, I work my butt up to finish this task before the meeting.
recipe [ˈresəpi]: n. a set of instructions for cooking a particular type of food配方
- It's said that the recipe can be dated back to 1000 years ago.
- The recipe which becomes popular with young people proved poisonous in our experiment.
- He goes out of his way to keep the secret of the recipe which has already been published abroad.
