#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Sometimes Life's a Rodeo
#+begin_verse
It was enough that the cowboy I married was a rodeo clown and bullfighter,
  complete with makeup box and blond wig.
It was enough that he wore baggy pants and football cleats to work
  darting around cross-bred brahmans and other snot-slinging bovine.
But when one of those 2,000-pound critters ran the length of him,
    tore off his right ear and broke several ribs,
  someone had to make sure the filler acts went on as promised.
That’s when wearing the pants in the family took on a whole new meaning for me.
Shoot a balloon out of another clown’s hand? Sure.
Find 'gold' in the arena dirt with a toilet-seat Geiger counter? No problem.
Match my husband’s timing and mannerisms? Not so easy.
Comedy is a lot harder than it looks.
It pays to pay attention,
  because sometimes life’s a rodeo, and you just might end up being the clown.
#+end_verse
** expression
