#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Sometimes Life's a Rodeo
#+begin_verse
It was enough that the cowboy I married was a rodeo clown and bullfighter,
  complete with makeup box and blond wig.
It was enough that he wore baggy pants and football cleats to work
  darting around cross-bred brahmans and other snot-slinging bovine.
But when one of those 2,000-pound critters ran the length of him,
    tore off his right ear and broke several ribs,
  someone had to make sure the filler acts went on as promised.
That’s when wearing the pants in the family took on a whole new meaning for me.
Shoot a balloon out of another clown's hand? Sure.
Find 'gold' in the arena dirt with a toilet-seat Geiger counter? No problem.
Match my husband’s timing and mannerisms? Not so easy.
Comedy is a lot harder than it looks.
It pays to pay attention,
  because sometimes life’s a rodeo, and you just might end up being the clown.
#+end_verse
** expression
rodeo [ˈroʊdioʊ]: n. a type of entertainment in which ↑cowboys ride wild horses, catch cattle with ropes, and ride in races牛仔竞技表演
wig [wɪɡ]: n. artificial hair that you wear on your head ⇨ toupée假发
baggy [ˈbæɡi]: adj.. baggy clothes are big and do not fit tightly on your body OPP tight松垮的
cleats [klit]: n. cleats [plural] American English a pair of sports shoes with these pieces attached to them, in order to prevent someone from slipping ⇨ spikes
dart around sb.: to move quickly and erratically around sb. 围着某人转悠
cross-bred: adj. 杂种的,杂交的
sling [slɪŋ]: v. to throw or put something somewhere with a careless movement and some force SYN chuck投掷
bovine [ˈboʊˌvaɪn]: adj. written slow and slightly stupid, like a cow – used to show disapproval
critter [ˈkrɪtər]: n. a creature, especially an animal畜生
run the length of sb.: 
tear off sth.: 
rib [rɪb]: n. one of the 12 pairs of curved bones that surround your chest肋骨
filler [ˈfɪlər]: n. a substance used to fill cracks in wood, walls etc, especially before you paint them补白
arena [əˈrinə]: n. a building with a large flat central area surrounded by seats, where sports or entertainments take place竞技场, 舞台
counter [ˈkaʊntər]: n. the place where you pay or are served in a shop, bank, restaurant etc柜台
mannerism [ˈmænəˌrɪzəm]: n. a way of speaking or moving that is typical of a particular person特殊习惯, 怪癖
pays to do sth.: 
