#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Sometimes Life's a Rodeo
#+begin_verse
It was enough that the cowboy I married was a rodeo clown and bullfighter,
  complete with makeup box and blond wig.
It was enough that he wore baggy pants and football cleats to work
  darting around cross-bred brahmans and other snot-slinging bovine.
But when one of those 2,000-pound critters ran the length of him,
    tore off his right ear and broke several ribs,
  someone had to make sure the filler acts went on as promised.
That’s when wearing the pants in the family took on a whole new meaning for me.
Shoot a balloon out of another clown's hand? Sure.
Find 'gold' in the arena dirt with a toilet-seat Geiger counter? No problem.
Match my husband’s timing and mannerisms? Not so easy.
Comedy is a lot harder than it looks.
It pays to pay attention,
  because sometimes life’s a rodeo, and you just might end up being the clown.
#+end_verse
** expression
rodeo [ˈroʊdioʊ]: n. a type of entertainment in which ↑cowboys ride wild horses, catch cattle with ropes, and ride in races牛仔竞技表演
makeup box: n.化妆箱
wig [wɪɡ]: n. artificial hair that you wear on your head ⇨ toupée假发
baggy [ˈbæɡi]: adj. baggy clothes are big and do not fit tightly on your body OPP tight松垮的
cleats [klit]: n. cleats [plural] American English a pair of sports shoes with these pieces attached to them, in order to prevent someone from slipping ⇨ spikes防滑鞋
dart around sb.: to move quickly and erratically around sb. 围着某人转悠
cross-bred: adj. 杂种的,杂交的
snot-slinging: adj. 流着鼻涕的
bovine [ˈboʊˌvaɪn]: adj. technical relating to cows牛的
critter [ˈkrɪtər]: n. a creature, especially an animal畜生
run the length of sb.: 踏过某人
tear off sth.: 扯掉某物
rib [rɪb]: n. one of the 12 pairs of curved bones that surround your chest肋骨
filler [ˈfɪlər]: n. a substance used to fill cracks in wood, walls etc, especially before you paint them补白
wearing the pants in the family: 当家做主
arena [əˈrinə]: n. a building with a large flat central area surrounded by seats, where sports or entertainments take place竞技场, 舞台
counter [ˈkaʊntər]: n. a piece of electrical equipment that counts something计时
mannerism [ˈmænəˌrɪzəm]: n. a way of speaking or moving that is typical of a particular person神态
It pays to do sth.: 做某事是值得的
** sentences
rodeo [ˈroʊdioʊ]: n. a type of entertainment in which ↑cowboys ride wild horses, catch cattle with ropes, and ride in races牛仔竞技表演
- In spite of rodeo showing up this night, she decided not to go with us.
- Thanks to my friend who is a staff of rodeo, we get two tickets.
- In the end, I couldn't bear the lousy customer in the rodeo.
makeup box: n.化妆箱
- My wife insisted putting her makeup box in the small suitcase, which distrubs me a great deal. 
- It's no use pretending the makeup box hasn't been prised up.
- To her surprise, her husband has painted the makeup box for their anniversary.
wig [wɪɡ]: n. artificial hair that you wear on your head ⇨ toupée假发
- Wearing the blond wig in the stage, my aunt looks pretty charming.
- Every one got a shock when they saw Monica wearing blond wig and dancing in the restaurant.
- No matter what wig you're dressed in, I am able to recognize you in the crowd.
baggy [ˈbæɡi]: adj. baggy clothes are big and do not fit tightly on your body OPP tight松垮的
- The teacher is always accusing her student dressing in baggy pants without any respect at all.
- I ask for refunding, because of the baggy pants, instead of the price.
- Her mother is holding on her ears, for she wore baggy in the party.
cleats [klit]: n. cleats [plural] American English a pair of sports shoes with these pieces attached to them, in order to prevent someone from slipping ⇨ spikes防滑鞋
- The cleats is by no means worth 1000 dollars, that's why I refuse to give it as gift to your nephew.
- Her nephew is so fanatical about collecting basketball cleats that he always spent all his pocket money fetching them.
- There are a pair of football cleats hanging on the peach branch.
dart around sb.: to move quickly and erratically around sb. 围着某人转悠
- No matter how long you dart around me, I can't afford to buy such an expensive can of milk powder.
- She never fails to lose attraction to young men darting around her. 
- She realized that she is beautiful when there're always young men darting around her in high school.
cross-bred: adj. 杂种的,杂交的
- The meat of this kind of cross-bred pig tastes awful.
- Every time I run into the cross-bred cat, she is alway smelly.
- The siblings quarrelled bitterly and her sister told her that she is cross-bred because she got adapted.
snot-slinging: adj. 流着鼻涕的
- I never dreamed of the snot-slinging girls in front of me would become my wife in the future.
- Our cat has been snot-slinging for a long time, she may have caught a rare disease.
- In my childhood, I have always been snot-slinging, that's why I was not very popular with my classmates.
bovine [ˈboʊˌvaɪn]: adj. technical relating to cows牛的
- I won't let a bovine doctor have an operation on my husband.
- These villagers are in recognition of the bovine doctor, who invented a specific way of tackling the rare virus. 
- The dinner is obviously bovine, for it's full of many kinds of beef.
critter [ˈkrɪtər]: n. a creature, especially an animal畜生
- There must be only one critter in our house, you or your dog. 
- Maybe people of their parental generation couldn't imagine that we treat a critter as a member of our family.
- The criter is not getting mad, she just gets hungry.
run the length of sb.: 踏过某人
- As the car ran the length of her husband, she couldn't help but  crying out and covering her eyes with her hands.
- Right here last night, you murdered your brother and ran the length of his body with the car he sent you.
- It's hard to imagine that a snot-slining cat run the length of you asking for your company.
tear off sth.: 扯掉某物
- She can't pay for the gamble, which caused the gangster tear off her ears.
- Tearing off her sister's ears, she called out to her mother.
- The gangsters may tear off your ears for the money you own them.
rib [rɪb]: n. one of the 12 pairs of curved bones that surround your chest肋骨
- It's said that her ribs have been broken in a car accident.
- You must ask for level so that the pain of your ribs may be released.
- How can you have my feeling, it is not your ribs that got broken in the car accident.
filler [ˈfɪlər]: n. a substance used to fill cracks in wood, walls etc, especially before you paint them补白
- It seemed that the filler acts succeeded in salvaging the terrible show previous.
- The programme doesn't end up at the right timing, so we must design some filler acts.
- The filler acts held by the host received a warm welcome.
wearing the pants in the family: 当家做主
- Wearing the pants in the family means I have more responsibilities in the future.
- Wearing the pants in the family means I may sacrifice some freedom for money that buys groceries and foods for my family.
- She is always reluctant to wear the pants in the family.
arena [əˈrinə]: n. a building with a large flat central area surrounded by seats, where sports or entertainments take place竞技场, 舞台
- It's an elaborate murder in the arena, instead of a regular security accident.
- Two prizefighter quarrelled bitterly, making an appointment that there will be a fight to settle all down in the arena.
- Our queen is now sitting on the dragon in the arena fighting against traitors.
counter [ˈkaʊntər]: n. a piece of electrical equipment that counts something计时器
- You're missing the point that this is only a counter, not something you can use as evidence in the court.
- In my youth, I often staring at the counter all afternoon without doing anything.
- Think about that a counter made in mid century is being sold for only 10 dollars.
mannerism [ˈmænəˌrɪzəm]: n. a way of speaking or moving that is typical of a particular person神态
- The cute girl is famous for mimicking her headmaster's mannerisms.
- It's no use micmicking your twin brother's mannerisms, I know who you are.
- It's naive to believe that micmicking the mannerisms famous stars would let you become them.
It pays to do sth.: 做某事是值得的
- It pays to contribute to our community as long as we all engage in.
- It pays to take a good care of the great generation who fighted for us in the world war II.
- It pays to buy expensive cans of milk powder that contribute to your baby's growth.

** sentences2
rodeo [ˈroʊdioʊ]: n. a type of entertainment in which ↑cowboys ride wild horses, catch cattle with ropes, and ride in races牛仔竞技表演
- In spite of the rodeo showing up this night, she decided not to go with us.
- Thanks to my friend who is a staff member of the rodeo, we got two tickets.
- In the end, I couldn't bear the lousy customers in the rodeo.
makeup box: n.化妆箱
- My wife insisted on putting her makeup box in the small suitcase, which disturbs me a great deal. 
- It's no use pretending the makeup box hasn't been pried up.
- To her surprise, her husband painted the makeup box for their anniversary.
wig [wɪɡ]: n. artificial hair that you wear on your head ⇨ toupée假发
- Wearing a blond wig on the stage, my aunt looks pretty charming.
- Everyone got a shock when they saw Monica wearing a blond wig and dancing in the restaurant.
- No matter what wig you're dressed in, I am able to recognize you in the crowd.
baggy [ˈbæɡi]: adj. baggy clothes are big and do not fit tightly on your body OPP tight松垮的
- The teacher is always accusing her student of dressing in baggy pants without any respect at all.
- I asked for a refund because of the baggy pants, instead of the price.
- Her mother held her by the ears, for she wore baggy clothes at the party.
cleats [klit]: n. cleats [plural] American English a pair of sports shoes with these pieces attached to them, in order to prevent someone from slipping ⇨ spikes防滑鞋
- The cleats are by no means worth 1000 dollars; that's why I refuse to give them as gift to your nephew.
- Her nephew is so fanatical about collecting basketball cleats that he always spends all his pocket money fetching them.
- There is a pair of football cleats hanging on the peach branch.
dart around sb.: to move quickly and erratically around sb. 围着某人转悠
- No matter how long you dart around me, I can't afford to buy such an expensive can of milk powder.
- She never fails to be attracted to young men darting around her. 
- She realized that she was beautiful when there were always young men darting around her in high school.
cross-bred: adj. 杂种的,杂交的
- The meat of this kind of cross-bred pig tastes awful.
- Every time I run into the cross-bred cat, she is always smelly.
- The siblings quarrelled bitterly and her sister told her that she was cross-bred because she was adopted.
snot-slinging: adj. 流着鼻涕的
- I never dreamed that the snot-slinging girl in front of me would become my wife in the future.
- Our cat has been snot-slinging for a long time; she may have caught a rare disease.
- In my childhood, I was always snot-slinging, that's why I was not very popular with my classmates.
bovine [ˈboʊˌvaɪn]: adj. technical relating to cows牛的
- I won't let a bovine doctor have an operation on my husband.
- These villagers is in memory of the bovine doctor, who invented a specific way of tackling the rare virus. 
- The dinner is obviously bovine, for it's full of many kinds of beef.
critter [ˈkrɪtər]: n. a creature, especially an animal畜生
- There must be only one critter in our house, you or your dog. 
- Maybe people of their parental generation couldn't imagine that we treat a critter as a member of our family.
- The critter is not getting mad, she just gets hungry.
run the length of sb.: 踏过某人
- As the car ran the length of her husband, she couldn't help crying out and covering her eyes with her hands.
- Right here last night, you murdered your brother and ran the length of his body with the car he sent you.
- It's hard to imagine that a snot-slinging cat runs the length of you asking for your company.
tear off sth.: 扯掉某物
- She couldn't pay for the gamble, which caused the gangster to tear off her ears.
- After tearing off her sister's ears, she called out to her mother.
- The gangsters may tear off your ears for the money you owe them.
rib [rɪb]: n. one of the 12 pairs of curved bones that surround your chest肋骨
- It's said that her ribs have been broken in a car accident.
- You must ask for leave so that the pain of your ribs may be released.
- How can you know my feeling, it is not your ribs that were broken in the car accident.
filler [ˈfɪlər]: n. a substance used to fill cracks in wood, walls etc, especially before you paint them补白
- It seemed that the filler acts succeeded in salvaging the terrible show previously.
- The programme doesn't end up at the right time, so we must design some filler acts.
- The filler acts held by the host received a warm welcome.
wearing the pants in the family: 当家做主
- Wearing the pants in the family means I will have more responsibilities in the future.
- Wearing the pants in the family means I may sacrifice some freedom for money that buys groceries and foods for my family.
- She is always reluctant to wear the pants in the family.
arena [əˈrinə]: n. a building with a large flat central area surrounded by seats, where sports or entertainments take place竞技场, 舞台
- It's an elaborate murder in the arena, instead of a regular security accident.
- Two prizefighters quarrelled bitterly, making an appointment that there will be a fight to settle it in the arena.
- Our queen is now sitting on the dragon in the arena fighting against traitors.
counter [ˈkaʊntər]: n. a piece of electrical equipment that counts something计时器
- You're missing the point that this is only a counter, not something you can use as evidence in court.
- In my youth, I often stared at the counter all afternoon without doing anything.
- Think about that a counter made in the mid-century is being sold for only 10 dollars.
mannerism [ˈmænəˌrɪzəm]: n. a way of speaking or moving that is typical of a particular person神态
- The cute girl is famous for mimicking her headmaster's mannerisms.
- It's no use mimicking your twin brother's mannerisms, I know who you are.
- It's naive to believe that mimicking the mannerisms famous stars would let you become them.
It pays to do sth.: 做某事是值得的
- It pays to contribute to our community as long as we all engage in it.
- It pays to take good care of the great generation who fought for us in world war II.
- It pays to buy expensive cans of milk powder that contribute to your baby's growth.
