#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 05 Picture Perfect Moment
#+begin_verse
On a cool October afternoon,
  I dropped off my seventeen-year-old, Mayree, for volleyball practice.
She jogged off toward the field, then suddenly turned back, ran to the car,
  and leaned in through the driver's side window.
'See y'all in a few,' she said, waving good-bye to her baby brother and sister.
Standing outside the window, her ponytail swaying slowly in the breeze,
    bathed in the glow of the setting sun behind her,
  she looked like an angel encircled by a golden halo, like a Fra Angelico painting.
I don't recall if I told her how much I loved her,
    or how proud I was of the amazing young woman she had become,
  before driving away that day.
I never saw her alive again.
But I thank God every day for leaving me with that beautiful final image of her.
#+end_verse
** expression
drop sb. off for sp./sth.: 送某人去某地/做某事
jog [dʒɑɡ] off: 慢跑
ponytail [ˈpoʊniˌteɪl]: hair tied together at the back of your head and falling like a horse’s tail马尾辫(一种发型)
in the breeze [briz]: 在微风中
a/the glow of sth.: 一束某物
encircle [ɪnˈsɜrk(ə)l]: to surround someone or something completely环绕, 围绕, 包围
halo [ˈheɪloʊ]: a bright circle that is often shown above or around the heads of holy people in religious art光环
drive away: 驅車離開
leave sb. with sth.: 给某人留下某物
** sentence
drop sb. off for sp./sth.: 送某人去某地/做某事
- It's no use asking your cruel father to drop me off for my yoga practice.
- No wonder she was eager to chat with him, for he dropped her off for shuttlecock practice.
- Despite the fact that he loves me, he's never willing to drop me off for work.
jog [dʒɑɡ] off: 慢跑
- Jogging off towards home, I felt happiness coming behind the glow of a sunset halo.
- There was a one-in-a-million chance that she jogged off around the street at midnight only for exercise.
- Imagine her satisfaction when she saw the stray cat jogging off towards her.
ponytail [ˈpoʊniˌteɪl]: hair tied together at the back of your head and falling like a horse’s tail马尾辫(一种发型)
- I don't mean to harass you, I just can't resist the temptation to touch your lovely ponytail which your mother spent all morning making.
- It took me almost half an hour to wait for my wife, who was doing her ponytail.
- Nowadays, this kind of ponytail is extremely popular with young women in this town.
in the breeze [briz]: 
- She is a goddess in my eyes, with her hair swaying in the breeze.
- In the breeze, our family felt a little cold sitting in a shady spot under the trees.
- There might be something wrong with the clock, which is swaying violently even in the breeze.
a/the glow of sth.: 一束某物
- Given his imprisonment of 16 years, the drug dealer is willing to sacrifice all his belongings for a glow of sunshine. 
- I can't recognize the license plate of the car in the accident due to a glow of light shining directly inot my eyes.
- A glow of sunshine shed light on a murder in obscurity committed by a group of elites.
encircle [ɪnˈsɜrk(ə)l]: to surround someone or something completely环绕, 围绕, 包围
- My wife is always asking me to take a photo in which she is encircled by candlelight .
- Encircled by young men who had crushes on her, she never dreamed of marrying an ordinary worker.
- Surrounded by loud music, he couldn't focus on his work and made a huge mistake.
halo [ˈheɪloʊ]: a bright circle that is often shown above or around the heads of holy people in religious art光环
- Having lost the halo of a great leader, he had his head cut down in the square.
- In spite of those so-called halos, I am only an ordinary teacher who dedicates his life to education.
- The consequence of the halo is far beyond her estimation, making it difficult for her to lead a normal life in this town.
drive away: 驅車離開
- He wouldn't drive away unless you return his baseball cards to him.
- Don Hector instructed us to drive away after we made the deal about the drug.
- The drug dealer drove away after burning down the car of the driver who had cut in line.
leave sb. with sth.: 给某人留下某物
- Thanks to the food your mother left with, we won't starve to death.
- Leaving him with the precious ring, the elf queen declared war on Tyrant Wu.
- The dictator left us with a great number of people all over the world who hold a grudge against us.
