#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 06 Loving Middle School
#+begin_verse
People think I'm crazy for teaching middle-schoolers.
The truth is that I enjoy learning about life from my students.
Here's what they've taught me.
You can be angry at someone one day
  and be best friends by the next if you're just willing to communicate.
Asking for help can be scary but usually works.
Snacks should always be shared; they taste better that way.
You can start believing in yourself
  if you make time to study for a test and then pass it.
Once in a while, you just need to put your head on your desk and rest.
But most importantly, it's never a bad day to giggle and smile.
#+end_verse
** expression
scary [ˈskeri]: adj. frightening害怕的
snack [snæk]: n. a small amount of food that is eaten between main meals or instead of a meal小吃,零食
Once in a while, ...: 偶尔
giggle [ˈɡɪɡ(ə)l]: v. to laugh quickly, quietly, and in a high voice, because something is funny or because you are nervous or embarrassed咯咯笑
** sentence
scary [ˈskeri]: adj. frightening害怕的
- I am always being scary when I try to ask someone for something that's important to me.
- Imagine my surprise when I found my girl was scary either.
- Every programmer in China is now scary of layoff due to the magnificent development.
snack [snæk]: n. a small amount of food that is eaten between main meals or instead of a meal小吃,零食
- She is always holding on a grudge against her classmate who is unwilling to share her with snacks.
- My wife asked me to eat all kinds of snacks with her in her hometown.
- This snack consists of a special kind of sugar, which makes it taste special.
Once in a while, ...: 偶尔
- Once in a while, keeping the status quo is betther than hard-working but unwise movements.
- Once in a while, my cat takes a stroll around our yard.
- Once in a while, God has opened a window for you before closing your door.
giggle [ˈɡɪɡ(ə)l]: v. to laugh quickly, quietly, and in a high voice, because something is funny or because you are nervous or embarrassed咯咯笑
- In my youth, my aunt used to stare at me when I giggle unintentionally.
- He becomes an expert at telling jokes that makes everyone giggle in public.
- Even though she doesn't mean to make fun of the poor girl, she giggled.
