#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 08 First-Time Mom at Age Sixty
#+begin_verse
It was the seventies and Women's Lib said I could have it all.
Marriage and motherhood could wait.
After college, I worked; traveled; learned to fly, scuba dive, and white-water raft.
I was forty-eight, however, when I finally married.
Too late for that last 'bucket list' wish, motherhood.
Or so I thought.
My son Jeff arrived when I was sixty.
My hubby Ken's son was thirty-eight, six feet tall, and unable to manage his own life anymore due to Huntington's disease.
Jeff unknowingly received this incurable genetic neurological disease from his biological mother.
From me, he would receive the benefits of a nursing education as well as a mother's love.
This sweet, uncomplaining manchild is now in diapers, can't speak, and is spoon-fed.
It's never too late to experience the joy and heartache of motherhood in whatever form it takes.
Excuse me now.
My baby needs me.
#+end_verse
** expression
