#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 09 Ninety-Day Wonder
#+begin_verse
My life pivots around a form letter I received in the mail in 1980.
The letter was addressed to 'Recent College Graduate'
  and held out the opportunity to attend the air force's Officer Training School.
If I completed the training, I would receive my commission
  and become what was known as a Ninety-Day Wonder.

I don't know how they got my name and address,
  I don't know why I just didn't toss the letter,
  and I don't know why I followed through to become an officer.
My family was astounded by my decision.
Though I felt a sense of calling,
  it was easier for me to tell them I wanted to see the world.
After more than thirty years, my mother still hasn't forgiven me for leaving home.
But she still takes pleasure in reminding me about my first exotic assignment,
  to Rapid City, South Dakota.
#+end_verse
** expression
pivot [ˈpɪvət] around sth./sub_clause: 取决于某物
a form letter: 套信
be addressed to sp.: 要寄往某地
held out the opportunity to do sth.: 提供机会去做某事
commission [kəˈmɪʃ(ə)n]: n. a group of people who have been given the official job of finding out about something or controlling something委托,任命
toss [tɔs]: to throw something, especially something light, with a quick gentle movement of your hand投,扔
follow through to do sth.: 继续做完某事
felt a sense of relief/calling/belonging: 有一种...的感觉
take pleasure in doing sth.: 享受做某事
exotic [ɪɡˈzɑtɪk]: adj. 异国的
assignment [əˈsaɪnmənt]: n. a piece of work that is given to someone as part of their job任务,作业
** sentence
pivot [ˈpɪvət] around sth./sub_clause: 取决于某物
- Imagine his dismay when he found his salary pivoted around the working hours.
- My energy during the daytime used to pivot around whether I fell fast asleep last night.
- This isn't small potatoes, for your life in the university pivots around your mentor's first impression of you.
a form letter: 套信
- He got so angry that he crumpled the form letter up.
- He was instructed to straighten the form letter out in 2 minutes.
- By no means would he demarcate the form letter into junk mail.
be addressed to sp.: 要寄往某地
- It's just a form letter that's addressed to my hometown.
- The bike addressed to his house was mistaken for his sister's.
- The letter addressed to his hometown corresponds to his love for his wife.
held out the opportunity to do sth.: 提供机会去做某事
- The enthusiasm of seeking treasure abroad held out the opportunity to explore new lands.
- My father held out the opportunity to run a successful business for me.
- The spring held out the opportunity to put those cats at risk.
commission [kəˈmɪʃ(ə)n]: n. a group of people who have been given the official job of finding out about something or controlling something委托,任命
- It's such a rare commission that I won't fail.
- It's our duty to finish the commission no matter what has happened.
- After finishing the special commission, the admiration from people held out the opportunity to rise to power for him.
toss [tɔs]: to throw something, especially something light, with a quick gentle movement of your hand投,扔
- Our neighbor turned to the committee, for some children tossed rubbish from upstairs.
- The gentleman has reprimanded your child for tossing junk all around the yard.
- A nice toss won him a soulmate who has accompanied with him for twenty years.
follow through to do sth.: 继续做完某事
- In the end, I followed through to develop the function after so many interruptions.
- The boy followed through to present her ex-girlfriend with a nice gift which he had prepared for two days.
- The rodeo followed through to perform the filler acts, even though the cow ran the length of his body.
felt a sense of relief/calling/belonging: 有一种...的感觉
- I felt a sense of relief, when I heard that he didn't want to go to the restaurant either.
- I can't tell you why I felt a sense of calling when I decided to give you some pocket money.
- My leader's kindness let me feel a sense of belonging, so I stayed at the company.
take pleasure in doing sth.: 享受做某事
- My wife takes pleasure in asking me to take photos of her. 
- My cat takes pleasure in pouncing on me as long as I get home.
- I take pleasure in sitting in a boat and doing nothing at all.
exotic [ɪɡˈzɑtɪk]: adj. 异国的
- He was absolutely killed in an exotic fight in the battlefield.
- I felt a sense of stress because I have to have those exotic foods. 
- The street proved amazing, for it was full of foreigners and exotic food.
assignment [əˈsaɪnmənt]: n. a piece of work that is given to someone as part of their job任务,作业
- You can believe in yourself if you make time to do the assignment and then pass the exam.
- The assignment proved complicated, for it took me all the morning to finish it.
- The assignment you gave me is so heavy that I had to work overnight.
