#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 09 Ninety-Day Wonder
#+begin_verse
My life pivots around a form letter I received in the mail in 1980.
The letter was addressed to 'Recent College Graduate'
  and held out the opportunity to attend the air force's Officer Training School.
If I completed the training, I would receive my commission
  and become what was known as a Ninety-Day Wonder.

I don't know how they got my name and address,
  I don't know why I just didn't toss the letter,
  and I don't know why I followed through to become an officer.
My family was astounded by my decision.
Though I felt a sense of calling, it was easier for me to tell them I wanted to see the world.
After more than thirty years, my mother still hasn't forgiven me for leaving home.
But she still takes pleasure in reminding me about my first exotic assignment,
  to Rapid City, South Dakota.
#+end_verse
** expression
pivot [ˈpɪvət] around sth./sub_clause: 取决于某物
a form letter: 套信
be addressed to sp.: 要寄往某地
held out the opportunity to do sth.: 提供机会去做某事
commission [kəˈmɪʃ(ə)n]: n. a group of people who have been given the official job of finding out about something or controlling something委托,任命
toss [tɔs]: to throw something, especially something light, with a quick gentle movement of your hand投,扔
follow through to do sth.: 继续做完某事
felt a sense of relief/calling/belonging: 有一种...的感觉
take pleasure in doing sth.: 享受做某事
exotic [ɪɡˈzɑtɪk]: adj. 异国的
assignment [əˈsaɪnmənt]: n. a piece of work that is given to someone as part of their job任务,作业
