#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 09 Ninety-Day Wonder
#+begin_verse
My life pivots around a form letter I received in the mail in 1980.
The letter was addressed to 'Recent College Graduate'
  and held out the opportunity to attend the air force's Officer Training School.
If I completed the training, I would receive my commission
  and become what was known as a Ninety-Day Wonder.

I don't know how they got my name and address,
  I don't know why I just didn't toss the letter,
  and I don't know why I followed through to become an officer.
My family was astounded by my decision.
Though I felt a sense of calling, it was easier for me to tell them I wanted to see the world.
After more than thirty years, my mother still hasn't forgiven me for leaving home.
But she still takes pleasure in reminding me about my first exotic assignment,
  to Rapid City, South Dakota.
#+end_verse
** expression
pivot around sth.: 
a form letter: 
was addressed to sp.: 
held out the opportunity to do sth.: 
commission: 
toss: 
follow through to do sth.: 
felt a sense of relief/calling/belonging: 
take pleasure in doing sth.: 
exotic: 
assignment: 
