#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Casie Kelly
* 101 Lost Life, Gave Life
#+begin_verse
I wanted to be famous.
I never knew my father, and my mother, even at twenty-seven, was just a child herself.
My childhood came and went very fast.
I was surrounded by partying, drugs, and alcohol and subject to abuse by my mom's many boyfriends.
I ran away at sixteen, addicted to crystal meth.
I met the man who would be my husband and got pregnant at seventeen, giving up my addiction
  because I wanted my child to have a better life.
We married on my eighteenth birthday, and had our third child at twenty-two.
I am now twenty-four and still working on my degree.
We struggle financially, but we do have love, we do give strength, and we do have each other.
My kids know the importance of school and have an involved mom who advocates for them.
I'm not famous, but my kids love me anyway.
#+end_verse
** expression
