#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Shirley Zindler
* 103 The Secret Life of Dog Catchers
#+begin_verse
My blond ponytail swings, and my rescued Great Dane waits by my side
  as I load my rifle and shotgun into my truck.
I'm an animal control officer, and I never know what the day will bring.
I've rescued injured puppies, sick bobcats, baby ducks,
  and just about every other creature you can imagine.
I've removed animals from terrible situations and pressed charges against neglectful owners.
I've chased horses down the highway at midnight, assisted on police raids,
  and removed pythons from apartments.
I've been threatened by gang members, bitten by dogs, and slashed in a cockfighting bust.
I've helped animals and people in mudslides, floods, and fires.
I drag home the abandoned, broken, and orphaned;
  and my husband and children help me rehabilitate them.
It's a life of tragedies and triumphs, of tears of pain and tears of joy.
This is my life.
#+end_verse
** expression
