#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Carla Bravo
* 106 My Mother's Book
#+begin_verse
For years my mother would tell me stories of her youth and places she had traveled.
She'd always end each tale with 'I should write that down,' knowing full well she never would.
Without telling her, I began to write her life story.
I researched where she grew up, went to school, worked, and lived.
I mapped out all the places she had visited and the important people she had met.
I included many wonderful pictures and had it bound.
When she became ill with lung cancer, I flew from California to Michigan to take care of her.
In my hand was that book.
There are no words to describe how happy she was or how important those pages made her feel.
She showed it to everyone.
When she passed away, it was on the table by her bed.
My gift of love helped her leave this world in peace.
#+end_verse
** expression
