#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Isaac Cubillos
* 107 We Love the Smell of Jet Fuel in the Morning
#+begin_verse
My sister and I grew up poor, but we didn't know it.
We lived in a navy town,
  and our favorite weekend adventure was boarding the warships,
    even when the public wasn't invited.
It was one place we were never turned away.
We loved the smell of jet fuel in the morning.
Each time, a crew member would ask, "Have you eaten?"
We'd shake our heads, which always meant no, and away we went to the mess hall.
Navy chow was the best, especially on an aircraft carrier.
As we became adults, we realized the sailors recognized our plight and fed us attention and food.
We're doing well today, and rarely get on board a Navy ship.
But when we do, we inhale the diesel, machine oil mixed with jet fuel;
  we smile and remember those days of adventure and Navy chow.
We'll always have a soft heart for sailors.
#+end_verse
** expression
