#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Kathryn Preston
* 108 Mother Nature's Stage
#+begin_verse
Not long after I was raped, I went into the woods.
As I hiked, two deer were on the hillside above me.
I lay on the ground watching them, but they didn't move.
Gingerly, I moved forward.
I'd only taken two steps when something rustled in the brush.
It was a deer, hit by a car and dying in front of my eyes.
I've never seen anything so profound.
The deer glared at me with an intense mixture of wild fear and self-protection.
Yet it was becoming so weak
  that as its eyes bore through me,
    its neck muscles began to weaken
    and the deer began to wobble in slow, concentric circles.
I've never seen such a simultaneous display of strength and vulnerability.
I know this event was a story enacted for me on Mother Nature's stage for clarity.
The deer's death was a reflection of my inner reality.
#+end_verse
** expression
