#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Anne Cavanaugh-Sawan
* 109 Sunday Car Ride
#+begin_verse
I remember a hot, crowded, wood-paneled station wagon.
The windows cranked all the way down to let in a desperately needed cool breeze.
No car seats or seat belts, just kids piled together.
Legs jumbled upon arms, across stomachs.
A lucky few in the way back, facing out, making faces at the cars behind us.
Bologna sandwiches, lemonade, mixed with the smell of diesel.
Mom and Dad in the front.
The AM radio playing the Bruins-Canadians game.
The newspaper spread across Mom's lap, her black hair tucked neatly back.
A few bags of just-picked apples from the orchard safely stashed between the seats,
  promises of apple pie, apple cakes, applesauce.
Dad pulling off suddenly to a roadside ice cream stand.
"Who wants a cone?
Only chocolate or vanilla, none of those fancy flavors."
Bodies unwinding.
Heads poking up.
Doors opened, we tumbled out.
That is what I remember.
#+end_verse
** expression
