#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 11 Do Angels Exist?
#+begin_verse
Yes—in folklore, fairy tales, and religious text,
  and on a lonely stretch of highway in Oklahoma.
Driving my old station wagon on a seemingly endless highway in rural Oklahoma,
  my front hood popped open into a vertical position
    while I was doing fifty-five in the right lane.
In a split second, darkness enveloped me.
Shaken, I eased onto the right shoulder.
In the middle of nowhere, with no tools, I gazed at the horizon.
I saw cornfields, but not a soul in sight.
Suddenly a man appeared out of seemingly thin air.
Without uttering one word,
  he reached into the side pockets of his overalls
    and came up with an assortment of tools.
With the dexterity of a mechanic, he fixed my broken hood latch.
I raised my face to thank him profusely,
  but all I saw was empty space where he stood a few seconds ago.
#+end_verse
** expression
wagon [ˈwæɡən]: n. a strong vehicle with four wheels, used for carrying heavy loads and usually pulled by horses ⇨ cart四轮马车, 货车
hood [hʊd]: n. a folding cover on a car or ↑pram, which gives protection from the rain引擎罩
pop open: 弹开
vertical [ˈvɜrtɪk(ə)l]: adj. pointing up in a line that forms an angle of 90° with a flat surface OPP horizontal ⇨ diagonal垂直的
lane [leɪn]: n. a narrow road in the countryside ⇨ path小路, 巷
envelop [enˈveləp]: v. to cover or wrap something or someone up completely包封, 遮盖, 包围
In a split second, + ...:刹那间, ...
horizon [həˈraɪz(ə)n]: on the horizon在水平的
in sight: 在视野内
came up with sth.: 拿出某物
an assortment of sth.: 一类东西
dexterity [dekˈsterəti]: n. skill and speed in doing something with your hands灵巧, 机敏
profuse [prəˈfjus]: adj. produced or existing in large quantities丰富的
** sentence
wagon [ˈwæɡən]: n. a strong vehicle with four wheels, used for carrying heavy loads and usually pulled by horses ⇨ cart四轮马车, 货车
- I made a mistake that caused our wagon to break down on the way.
- The maintenance of these lanes in the villages makes it possible for us to pull corns with wagons. 
- There are rare instances when wagons hit the highway.
hood [hʊd]: n. a folding cover on a car or ↑pram, which gives protection from the rain引擎盖
- The hood ceased to pop open after I had it repaired.
- You must have had the front hood repaired.
- The hood was torn off after the collision with a wagon.
pop open: 弹开
- A crew of staff saw it pop open in the ceremony.
- If the cat puts her paw on the button, the door will automatically pop open.
- When the army began to open fire, the door popped open all of a sudden.
vertical [ˈvɜrtɪk(ə)l]: adj. pointing up in a line that forms an angle of 90° with a flat surface OPP horizontal ⇨ diagonal垂直的
- My teacher in high school spent a morning teaching me how to draw a vertical line without any tools.
- Obviously, our baby is in an attempt to draw a vertical line.
- The door is vertical, for the water drops from it directly.
lane [leɪn]: n. a narrow road in the countryside ⇨ path小路, 巷
- It's you who mowed these farmers down on the lane.
- It occurred to him that he had lost his pocket money on the lane.
- Masses of raw meat on the lane told us what had happened on the battlefield.
envelop [enˈveləp]: v. to cover or wrap something or someone up completely包封, 遮盖, 包围
- Raw flesh enveloped the dog who used to be a stray.
- Darkness enveloped the girl, who was in rags.
- Worries and anxiety enveloped the boy, who used to be bullied by his cousins.
In a split second, + ...:刹那间, ...
- In a split second, I realized how my aunt protected me from invasion from outside threats.
- In a split second, my cat pounced on me at the sight of the cat snacks.
- In a split second, my wife gave me a tight hug and kissed me fiercely.
horizon [həˈraɪz(ə)n]: on the horizon在水平的
- He enjoys drawing horizontal line all the morning without caring about any other things.
- I was wandering whether you are drawing horizontal line. 
- I am pround of the captain, who sails a boat on the horizon  all the time.
in sight: 在视野内
- With a puma in sight, I had to shoot at him or else I would lose my life.
- I saw around the road, not a person in sight.
- How could I ask for a lift, without any car in sight?
came up with sth.: 拿出某物
- It occurred to me that my father used to come up with a stack of newspapers.
- It's no use coming up with the code when it is outdated.
- The gift you came up with was not decent enough.
an assortment of sth.: 一类东西
- He inferred that the assortment of tools belonged to our father.
- An assortment of iron tools was piled up in the corner.
- My mother is complaining about the assortment of tools that occupy the room.
dexterity [dekˈsterəti]: n. skill and speed in doing something with your hands灵巧, 机敏
- His dexterity in programming is beyond my imagination.
- In spite of his dexterity in programming, he is too old to get along with our young colleagues.
- He showed us his dexterity in the filler acts.
profuse [prəˈfjus]: adj. produced or existing in large quantities丰富的
- I have no idea how profuse the meal is.
- Because of the profuse foods, the drug slipped my mind. 
- The natives provided us with profuse food without any requirements. 
