#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 11 Do Angels Exist?
#+begin_verse
Yes—in folklore, fairy tales, and religious text, and on a lonely stretch of highway in Oklahoma.
Driving my old station wagon on a seemingly endless highway in rural Oklahoma, my front hood popped open into a vertical position while I was doing fifty-five in the right lane.
In a split second, darkness enveloped me.
Shaken, I eased onto the right shoulder.
In the middle of nowhere, with no tools, I gazed at the horizon.
I saw cornfields, but not a soul in sight.
Suddenly a man appeared out of seemingly thin air.
Without uttering one word, he reached into the side pockets of his overalls and came up with an assortment of tools.
With the dexterity of a mechanic, he fixed my broken hood latch.
I raised my face to thank him profusely, but all I saw was empty space where he stood a few seconds ago.
#+end_verse
** expression
