#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: JoAnn Cohen
* 110 Following Directions
#+begin_verse
I looked away, settling in a lounge chair, and it happened.
Stephen, my four-year-old son, disappeared.
He was playing in a swimming pool one moment, and then he was missing.
I scanned the water more carefully.
No Stephen.
I asked the lifeguard, who shook her head.
Only a mother could react with the intense panic that flooded me.
For twenty-five minutes, I searched frantically for a boy in a red swimsuit.
Then I noticed an announcement being repeated.
"If you are looking for a lost child, come to the courtesy booth."
I reached the booth breathless and noticed Stephen seated, leafing through a brochure.
He looked up.
"Mom!
Where have you been?" he demanded.
"Don't you remember telling me to come here if I couldn't find you?
Well?
Here I am!!!"
I shook my head.
If only I could follow directions as well as Stephen.
#+end_verse
** expression
