#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Krista Selph
* 111 My First Marathon...26.2 in 4:25
#+begin_verse
Early morning, cold air, thirtieth birthday gift to myself, here we go.
Fast pace, feeling easy, passing on the left and right;
  feels like how fast things have moved in the last ten years.
Mile six, people turn back for the half.
Twenty to go seems intimidating, like the tasks in front of me as I support a family
  while my husband is in Afghanistan.
Mile thirteen, still having fun...slowing down
  but thinking about parenting and how four babies changed things
    but how great each second is.
Mile twenty-one...this seems impossible...like running a coffee shop in a bad economy
  while working full time and finishing my PhD...what was I thinking?
Mile twenty-six...tears as I see my best friend waiting
  when I thought I could finish alone...
  wishing it was my husband
  but knowing my family is why I can and will persist
    with this exciting, painful, priceless thing we call life.
#+end_verse
** expression
