#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Katharine Hanschu
* 113 Legacy
#+begin_verse
Grandpa was a man of integrity.
He was a rancher who loved his family fiercely,
  and he passed down simple, yet important, life lessons.
My dad tells a story about helping his dad tediously wash borrowed farm equipment
  before they returned it to a neighbor.
'Why are we cleaning this?' he asked.
'It was dirty when we got it.'
'Always return something a little better than you found it' was Grandpa's reply.
A week after Grandpa's funeral,
  I helped my dad vacuum, wash, and refuel a car that he had borrowed from a friend.
After returning the vehicle, the friend leaned over to me and remarked,
  'Whenever I loan something to your dad,
    I know it will come back in even better shape.'
And that is my grandpa's legacy.
He left the world just a little better than he found it.
I hope I can do the same.
#+end_verse
** expression
