#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Teri Jones
* 116 Blue Laundry
#+begin_verse
Twenty-three years ago, I became a firefighter's wife.
I was told that it was going to be tough, but no one told me about the blue laundry.
Tons of blue laundry, saturated with the smell of smoke, sweat, and other things.
It seemed an endless cycle.
Year after year, he would bring home more blue shirts and blue pants,
  and all I could say was "No! Not more blue laundry!"
Then September 11, 2001, happened.
As we sat in the living room watching his firefighter brothers rushing into a flaming building,
  I turned to him and said, "Why would they run into that?"
He turned to me and said simply, "Because that's our job."
So that night as I put yet another load of blue laundry in the washing machine, I decided
  that maybe a little blue laundry was not such a big deal after all.
#+end_verse
** expression
