#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Leslie Kimiko Ward
* 117 I Choose to Continue Living
#+begin_verse
Sometimes this choice isn't easy.
Sometimes I'm incredibly homesick for the Great Collective we leave at birth
  and will return to again someday.
Sometimes the trials of being human, the pain we express and endure, feel like too much,
  and I weigh my choice against its opposite.
Sometimes the two come out almost even.
In Alaska, where I live, lots of people choose suicide.
Every year I know at least one.
One year I knew three.
Last year, in my friend's village of 350 people, three chose suicide.
I went to the village and taught the children how to fold origami cranes
  to practice making something beautiful.
In just a few days, we folded over 1,000 cranes.
I keep a strand in my car.
The rest are on display in the school library.
Through this experience, I remember that I am making the right choice.
#+end_verse
** expression
