#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Dawn Wilkerson
* 118 Serenity and Hope
#+begin_verse
In 2008, at the end of a complicated pregnancy, we lost our infant son.
The pain was tremendous.
Then, in mid-2009, we found out I was six weeks into an even more complicated pregnancy.
I tried to be hopeful, but there were so many telling me how dark the future looked.
As predicted, we were rushed to the hospital—three months early.
She weighed two pounds, thirteen ounces at delivery
  and was given only a fifty percent chance of survival.
I began to give up; she began to fight.
I watched her smile through pain, tubes, and surgeries.
She laughed at their restrictions and limitations.
At two years old, young Serenity has already taught me many lessons:
  Hope is always alive,
  you should never let others define your strengths,
  and living life bound by restrictions and limitations
    can only keep you from being the person you are capable of becoming.
#+end_verse
** expression
