#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Amy Gravino
* 119 The Last Piece of the Puzzle
#+begin_verse
Imagine your daughter.
What does she look like?
Maybe she is small.
Maybe she wears glasses.
Does she have friends?
Maybe she is the girl huddled in the corner at birthday parties,
  crying from being chased around with balloons by the other children,
    who know the noise of the balloons popping frightens her.
Maybe she comes home from school, nine years old, nine long years,
  and tells you she feels like killing herself.
Maybe she sits in the guidance counselor's office the next afternoon,
  trying to hold everything in her together for just one more day.
Maybe she grows up, a girl on the autism spectrum who now is a young woman,
  finding her way in a world that said there was no place for her.
Maybe she is helping others with autism spectrum disorders who face the same path
  that she herself once traveled.
Maybe she is me.
#+end_verse
** expression
