#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 12 Morning
#+begin_verse
Daybreak.
Cockatiel opens black eyes and unfolds gray wings.
Repeats his name: Papagana Papagana.
Papagana tosses kibbles.
Prefers seeds.
Muffin jumps on bed.
He's not allowed on furniture.
I put Muffin outside while husband sleeps.
Muffin barks.
Bring Muffin inside to avoid another complaint from neighbor
  a man allergic to pets, children, and noise.
Muffin eats kibbles under birdcage.
Runs to teenager's room, hops on bed, and licks teenager's face.
Teenager stretches.
Textbooks, remote control, and cell phone drop to floor.
In pajamas and bunny slippers, I step outside.
Bring in waterlogged newspaper.
Front lawn still wet from last night's rain.
From out of nowhere are hundreds of snails, the same used in French restaurants,
  but I keep kosher.
Accidentally crush escargot.
Remove slipper.
My rose garden, an explosion of colorful blooms, is framed within rainbow's arc.
On one foot, I begin my morning prayers of gratitude.
#+end_verse
** expression
daybreak [ˈdeɪˌbreɪk]: n. the time of day when light first appears SYN dawn拂晓
unfold [ʌnˈfoʊld]: v. if you unfold something that was folded, or if it unfolds, it opens out打开, 显露, 开展, 阐明
kibble [ˈkɪbl]: n. small round pieces of dried dog or cat food猫狗粮
be allergic [əˈlɜrdʒɪk] to sth.: 对某物过敏
cage [keɪdʒ]: n. a structure made of wires or bars in which birds or animals can be kept笼
hop [hɑp]: v. if a bird, an insect, or a small animal hops, it moves by making quick short jumps跳跃
pajama [pə'dʒɑːmə]: n. 睡衣
slipper [ˈslɪpər]: n. a light soft shoe that you wear at home拖鞋
waterlogged [ˈwɔtərˌlɔɡd]: adj. a waterlogged area of land is flooded with water and cannot be used浸满水的, 涝的
From out of nowhere are sth., ...(同位语): 不知不觉出现了某物,...
kosher [ˈkoʊʃər]: adj. kosher food is prepared according to Jewish law犹太教的
arc [ɑrk]: n. a curved shape or line弧, 弓形, 拱
prayer [prer]: n. words that you say when praying to God or gods祈祷
On one foot, ...: 单脚站着,...
** sentence
daybreak [ˈdeɪˌbreɪk]: n. the time of day when light first appears SYN dawn拂晓
- My wife gets used to waking us up at daybreak.
- Our boss is gonna bring in new crews at daybreak.
- It's amazing that our company will take over the biggest supermarket at daybreak.
unfold [ʌnˈfoʊld]: v. if you unfold something that was folded, or if it unfolds, it opens out打开, 显露, 开展, 阐明
- In educational settings, we tend to unfold our maps when getting lost in forests.
- We unfolded our letters, reaching an agreement on the same page.
- Unfolding your paper in case of this situation will be taken as questioning.
kibble [ˈkɪbl]: n. small round pieces of dried dog or cat food猫狗粮
- My cat will ask me for kibble as long as her plate is empty.
- I found we made an assumption that we had given enough kibble to our cat.
- Giving enough kibble to our cat proved valid, for she hasn't waken us up in midnight.
be allergic [əˈlɜrdʒɪk] to sth.: 对某物过敏
- Jimmy's brother, the famous lawyer, claimed that he was allergic to magnetism.
- I am allergic to any colleague, who looks like my cousin.
- He is allergic to criticism in public, which makes him annoyed.
cage [keɪdʒ]: n. a structure made of wires or bars in which birds or animals can be kept笼
- We have been confined to the cage for over two days.
- A man's body in a cage was salvaged by the local police.
- The local police are fanatical about searching for the sunken cage.
hop [hɑp]: v. if a bird, an insect, or a small animal hops, it moves by making quick short jumps跳跃
- Maybe she hopped onto bed because of the flamboyant bullion.
- You scared the hell out of my wits, and I almost hopped.
- He has been hopping for an hour, maybe you should remind him to have a rest.
pajama [pə'dʒɑːmə]: n. 睡衣
- Honey, you look sexy in the pajama.
- It comes as a surprise to me that the pajama costs her fifty dollars.
- I will protect my eyes from the flamboyant pajama.
slipper [ˈslɪpər]: n. a light soft shoe that you wear at home拖鞋
- My wife has already presented me with a pair of slippers.
- From out of nowhere is a slipper, which our child had searched for all day.
- It's impolite to toss your slippers downstairs.
waterlogged [ˈwɔtərˌlɔɡd]: adj. a waterlogged area of land is flooded with water and cannot be used浸满水的, 涝的
- My life largely pivots around a waterlogged letter.
- Unfolding the waterlogged letter, she found that her husband had an affair with her friend.
- We must dry the waterlogged clothes first.
From out of nowhere are sth., ...(同位语): 不知不觉出现了某物,...
- From out of nowhere are ants, who are trying to bring food back into their nest.
- From out of nowhere is the village, which is said to be a place full of treasure.
- From out of nowhere are local natives, who seem aggressive because of our arrival.
kosher [ˈkoʊʃər]: adj. kosher food is prepared according to Jewish law犹太教的
- Keeping kosher, I haven't had meat for lunch for a month.
- Keeping kosher, I am forbidden to have my hair cut in January.
- Keeping kosher, I am unwilling to hurt any little animals.
arc [ɑrk]: n. a curved shape or line弧, 弓形, 拱
- Come here, there is a rainbow arc in the sky.
- My teacher instructed me to draw an arc on the blackboard.
- There are three steps to drawing an arc.
prayer [prer]: n. words that you say when praying to God or gods祈祷
- Thanks to my prayer, you have been healed.
- May my prayer console you.
- My mother gets accustomed to saying a prayer of gratitude before meals.
On one foot, ...: 单脚站着,...
- On one foot, she is reading a long and dense book.
- On one foot, she begins her yoga meditation.
- On one foot, my wife finished her speech in the meeting.
