#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 12 Morning
#+begin_verse
Daybreak.
Cockatiel opens black eyes and unfolds gray wings.
Repeats his name: Papagana Papagana.
Papagana tosses kibbles.
Prefers seeds.
Muffin jumps on bed.
He's not allowed on furniture.
I put Muffin outside while husband sleeps.
Muffin barks.
Bring Muffin inside to avoid another complaint from neighbor—a man allergic to pets, children, and noise.
Muffin eats kibbles under birdcage.
Runs to teenager's room, hops on bed, and licks teenager's face.
Teenager stretches.
Textbooks, remote control, and cell phone drop to floor.
In pajamas and bunny slippers, I step outside.
Bring in waterlogged newspaper.
Front lawn still wet from last night's rain.
From out of nowhere are hundreds of snails—the same used in French restaurants—but I keep kosher.
Accidentally crush escargot.
Remove slipper.
My rose garden, an explosion of colorful blooms, is framed within rainbow's arc.
On one foot, I begin my morning prayers of gratitude.
#+end_verse
** expression
