#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: James McDonaugh
* 120 A Few Words about My Wife
#+begin_verse
Running a marathon is hard.
Running one blind with no assistance is unthinkable unless you're my wife, Amy.
At eleven, surgeries on a vascular anomaly in her face left Amy blind in her right eye
  with 20/400 vision in her left and no peripheral.
Doctors advised against pregnancy and sports.
In 2004, following the birth of our third child,
  Amy began running as a way to get back in shape
    and enjoy a short break from her responsibilities at home.
She steadily improved in speed and stamina and began competing in 5-K races.
Amy ran her first marathon in 2009 and qualified for Boston, which she ran the following year.
On May 1, 2011, Amy won the Flying Pig Marathon in Cincinnati in 2:58:10,
  just weeks after emergency surgery on her right cheek.
Amy's health issues persist, but so does her refusal to be confined or defined by her condition.
#+end_verse
** expression
