#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jeannie O'Sullivan
* 121 From Broken Home to Mended Fence
#+begin_verse
I was eight when my parents sat me down and gently told me they were divorcing,
  a moment that shattered my sense of well-being
    and sealed my conviction that a successful union wasn't possible.
Over the next three decades,
  my father remarried and separated again,
  my siblings and I navigated our own romances,
  and my parents gradually mended fences
    as family tragedies and triumphs,
        including my mother's severe respiratory disease,
      forced their interaction.
My father visited my mother daily during the last months of her life
  and was at her bedside when she took her final breath in May.
The lesson learned—
    that relationships evolve, change, and don't necessarily follow convention—
  was perfectly encapsulated in how my mother had filled out her hospital paperwork.
She listed my dad as the emergency contact and, in the How Known field, wrote 'Friend.'
#+end_verse
** expression
