#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: David Kuhn
* 122 The Sunny Side of Food Phobias
#+begin_verse
I loved eggs as a toddler.
I consumed them in such copious quantities
  that my parents might have shrewdly invested in a coop and a few score hens
    just to keep me sated.
My gluttonous affair with eggs continued
  until the day my rock star big sister proclaimed them 'yucky.'
That was more than thirty-five eggless years ago.
But there it was, the second course in a tasting menu my fiancé had treated us to:
  ravioli un uovo in sage brown butter.
Tucked inside this pasta parcel
  was perched a perfectly runny bit of yolk atop a nest of herbed ricotta.
I steeled myself against its undoubted awfulness and put food and fork to mouth.
From the first bite, I was ensorcelled.
Eating this thing was like consuming a bit of ambrosia: I felt nearly immortal
  while I savored its rich, golden goodness.
Can anyone spare a coop?
#+end_verse
** expression
