#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Darleene Hancock
* 125 My Wedding Day
#+begin_verse
Fifty-four years ago, my husband and I eloped to Yuma, Arizona.
Through a comedy of errors, bad directions, changes in law,
    and a gap in justices being sworn in,
  we were finally married in a little casino connected to a tiny dinner
    in Searchlight, Nevada.
For wedding rings, all we had was a party favor fake ring I found in the bottom of my purse.
The justice of the peace shook his head, gave Fred a sad look, and married us anyway.
We could pay him only two dollars because that was all we had left in our pockets.
Luckily, the gas station attendant gave us a wedding present of a full tank of gas.
Our life together followed suit: full of comedy, errors, and many directions
  but nevertheless very happy, with eight children and, so far, seven grandchildren.
And I wouldn't trade that wedding day for anything.
#+end_verse
** expression
