#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Larissa Allen
* 128 Cancer, Faith, and a Pastrami Sandwich
#+begin_verse
Sitting in a hospital bed with chemo chasing after late-stage colon cancer,
  I was at an emotional low
    when a gentleman pushed back my curtain and offered to make me a pastrami sandwich.
I protested, but he said he had been at his wife's side when she went through cancer
  and knew this was a way to give back.
"To eat is to heal" were his words as he smiled and backed out of the room.
My husband pushed the plate toward me, and I took a bite, soon inhaling the entire sandwich.
I will never know why my stomach accepted that sandwich or why it didn't taste like tin.
I just ate it like I had never eaten before.
Someone else who had walked in my shoes
    so boldly saying, "To eat is to heal,"
  made me think about how far a little faith can take you.
#+end_verse
** expression
