#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Chance Steeves
* 129 The Man with the Tattoos
#+begin_verse
My father had all sorts of interesting friends.
I remember one in particular:
  He was tall and large and had more hair than he knew what to do with.
His arms were covered in ink, a tangle of reds and blues and black
  that reminded me of chalk drawings on a faded driveway.
He came to our house and spoke with my father about the adult things grown folk talk about.
I paraded into the living room with my stuffed animals and Disney dolls
  and explained to him everything he needed to know
    about the things that were important to a five-year-old like me.
He listened and smiled and held all the toys I pushed into his arms.
Before he left, he stopped at the stairs and turned to me.
He smiled and thanked me.
Why?
'You're the only child I've met who isn't afraid of me.'
#+end_verse
** expression
