#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 13 Christmas in a Vending Machine
#+begin_verse
In 1997, I was in Vermont and was long-distance friends with a Mississippi girl.
After visiting in early December, we were in love.
On Christmas Eve, I found an airline running a last-minute special from Memphis to Boston.
When it came time for Christmas dinner, I learned that everything in Boston was closed on Christmas night.
We gathered our change and raided the hotel vending machine.
Our Christmas dinner was Funyuns, Hot Fries, Fritos, Snickers, and Cokes while watching TV.
It was perfect.
Parting was heartbreaking but temporary.
We were married by August.
We look back on our 'vending machine' Christmas and recognize how special it was.
Some people live their whole lives hoping for a special moment like that.
Christmas is not about where you are.
It's not about extravagant meals.
It's all about who you are with, grasping that moment and appreciating how special it is.
#+end_verse
** expression
