#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 13 Christmas in a Vending Machine
#+begin_verse
In 1997, I was in Vermont and was long-distance friends with a Mississippi girl.
After visiting in early December, we were in love.
On Christmas Eve, I found an airline running a last-minute special from Memphis to Boston.
When it came time for Christmas dinner,
  I learned that everything in Boston was closed on Christmas night.
We gathered our change and raided the hotel vending machine.
Our Christmas dinner was Funyuns, Hot Fries, Fritos, Snickers,
  and Cokes while watching TV.
It was perfect.
Parting was heartbreaking but temporary.
We were married by August.
We look back on our 'vending machine' Christmas and recognize how special it was.
Some people live their whole lives hoping for a special moment like that.
Christmas is not about where you are.
It's not about extravagant meals.
It's all about who you are with, grasping that moment and appreciating how special it is.
#+end_verse
** expression
airline [ˈerˌlaɪn]: n. a company that takes passengers and goods to different places by plane航线
last-minute: adj. happening or done as late as possible before something else happens最后的
raid [reɪd]: v. to go to a place that has supplies of food or drink and take some because you are hungry觅食
vend [vend]: v. to sell something贩卖
Funyuns: 洋葱卷
Fritos: 油炸玉米饼
Snicker: 士力架
parting [ˈpɑrtɪŋ]: n.分别 adj.离别的
look back on ...: 回忆...
live sb's life hoping for sth.: 终其一生期望某事
** sentences
airline [ˈerˌlaɪn]: n. a company that takes passengers and goods to different places by plane航线
- Obviously, this airline is much cheaper than that one of the company.
- My wife is always complaining about the airline, for it has changed its routine for several times.
- For most of history, there has been a special airline reserving for our president.
last-minute: adj. happening or done as late as possible before something else happens最后的
- He was eager to catch up with the last-minute bus yesterday.
- The last-minute meeting ran successfully, in which our bosses reached an important agreement.
- If you hesitated to charge your electric-motor, you wouldn't catch up with the last-minute train.
raid [reɪd]: v. to go to a place that has supplies of food or drink and take some because you are hungry觅食
- We raided the vending machine in the hotel, where we found nothing but a box of condom.
- After going through my bag and finding nothing that can feed us, I was gonna raid the vending machine.
- The baby needs feeding now, so go to raid the supermarket righ now.
vend [vend]: v. to sell something贩卖
- In the end, the software engineer losing his job gets used to vending stuffs in the street.
- It's no use pretending to be a disabled person and trying to vend us something we don't need at all.
- I'd like to raid the vending machine, is there anything you need at night?
parting [ˈpɑrtɪŋ]: n.分别 adj.离别的
- Parting turns out to be heartbreaking, for the mother has been crying and missing her long-distance baby all the time.
- I don't want any parting from you, so I will take the job.
- Parting time is always painful, you shouldn't have been at the platform.
look back on ...: 回忆...
- While we were riding our motor, my wife looked back on those nights we spent together watching exotic movies.
- When our classmates look back on the moment back in school, I was always out of the sight.
- Looking back on those year her husband had been losing the job, she burst into tears.
live sb's life hoping for sth.: 终其一生期望某事
- I live my life hoping for a good wife who is willing to take care of my pets.
- My father lives his life hoping for his heal from this special illness.
- My wife lives her life hoping for a vacation on which she was at a seaside resort.
