#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Donna Jarvis
* 132 It All Counts
#+begin_verse
At age twenty-three, a rhinoceros charged me.
I bungee jumped into a canyon.
And I dodged bullets in a crossfire in Kashmir.
At forty-three, I have a day job and mortgage.
I do laundry and dishes.
I drive a sensible family vehicle and hang out at Little League fields.
I don't believe my story is unique.
Only the details separate me from any middle-aged woman
  who must learn to navigate the daily mundane with the identity of her free-spirited youth.
My former "life" is no more extraordinary
  than the beauty and grace revealed in the ordinary...
    a kayak ride in the early morning mist...
    a harvest moon...
    watching my children breathe as they sleep.
If life is a journey and not a destination, then each stage holds the possibility for magic.
And somewhere between star-gazing in my twenties and grocery shopping in my forties,
  I have to believe...it all counts.
#+end_verse
** expression
