#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Caroline McCandless
* 133 Surf Soldiers
#+begin_verse
We're just kids, twenty-somethings sitting around a beach bonfire,
  drinking beer, and telling stories.
It's been a long day, but our faces glow with more than firelight.
Daniel and I love traveling, and we talk about where he traveled before Afghanistan.
They all cringe as they recall the smell of the poop lakes in Iraq, and Dorian laughs loudly.
We're just kids at the beach, but I realize what an outsider must see.
I'm surrounded by young soldiers, young vets, single/double amputees in wheelchairs,
  burn victims relaxing in the shadows, glass eyes twinkling from the flames.
They're wounded soldiers I'm helping rehabilitate with 'surf therapy.'
We surfed all day today and we'll surf all day tomorrow.
That's what an outsider would see,
  but in my mind, I'm just a girl with a surfboard sitting among heroes,
    trying to make them feel like a couple of kids at the beach.
#+end_verse
** expression
