#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Heather Farnath
* 134 Story Time
#+begin_verse
Weekends at my house are a blur of errands, muddy cleats,
  and half-finished home improvement projects.
The whole family is over, the windows are open, the game is on,
  the house smells like fall and dinner and bleach.
It takes approximately one afternoon for my kids to put their toys back exactly
  where they belong: the living room floor.
"This place was clean this morning," I say.
"Don't worry about it," Mom says.
"This is such a precious time in life.
Be careful you don't miss it."
She smiles when my son spills his drink, laughs as she pulls corn out of my hair.
By the time everyone leaves, I'm exhausted.
I forget the dishes in the sink and rest my head on my husband's chest.
"Look," he says as my daughter climbs up onto her brother's lap for a story.
I listen, thankful I didn't miss it.
#+end_verse
** expression
