#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Ailene Everts
* 136 Highway Sixty-Four
#+begin_verse
I work at a gas station on a busy highway on the way to a popular tourist site.
It's not a glamorous job—I clean bathrooms, I pick up trash, I mop floors,
  and I handle your oft-circulated cash.
I muddle through the language barriers, the difference in cultures,
  and sometimes it takes a game of charades to get the point across.
There are days when your patience wears thin with me just as mine does with you.
And Lord knows, I don't make a lot of money.
But through this job,
    through the heavy accents of your foreign tongue and the long hours I work every day,
  I have learned lessons
    that could have never been taught in school through books or lectures—
      patience, understanding, tolerance, and acceptance.
Acceptance that you are you, I am me, and that while we're all different, we're all still, a "we."
#+end_verse
** expression
