#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Patricia Anderson
* 139 My Butterfly
#+begin_verse
I noticed her sitting alone and sobbing.
I asked her, 'What's the matter, honey?'
She told me she 'didn't want to live here anymore.'
I asked, 'Where do you want to live?'
She said, 'I want to live where there is a ball and a swing.'
I said, 'We have a ball and swing.'
With tears, she replied, 'But there are no kids.'
Kids like herself.
She didn't know group homes existed,
  only the hospital unit she'd experienced with special needs kids.
Our girl is challenged with autism.
At fourteen, she knew living with kids like herself
  would mean having to sacrifice living with her own family.
And she did.
We knew she had to go.
'I like living here.'
She tells me on the telephone, 'I love you.'
I tell her through the lump in my throat, 'I love you, too, honey.
I'm so proud of you.'
#+end_verse
** expression
