#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Elliot Levanthal
* 140 A Real Love Story—Fairy Tales Do Happen
#+begin_verse
In 1985 at twenty-five years old,
  I briefly crossed paths in New Zealand with a beautiful Australian nurse named Julie.
My next stop was Melbourne, Australia.
I spent three days with Julie before a flight to Brisbane, Australia.
Realizing my mistake of leaving the love of my life,
  I took a twenty-four-hour bus ride back to her.
After seven more romantic days, never leaving each other's side,
  sadly I had to return to America for work.
We corresponded by mail for months (before Internet), and I gave her a Minnie Mouse for a gift.
We lost contact and moved on with our lives due to distance and marriages,
  and subsequently failed marriages.
Twenty-five years later, reuniting on Facebook, our romance blossomed.
She had kept the Minnie Mouse.
In July 2011, I proposed to my princess at the Disneyland Castle
  and on October 1, 2011, we got married in Las Vegas.
#+end_verse
** expression
