#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Dana Hinders
* 141 Making Friends with My Kitchen
#+begin_verse
When my son's kindergarten teacher had the kids draw pictures of their moms,
  he drew me baking a birthday cake.
A note on my refrigerator says, 'Deer Mom. Yor fud is gud.'
    (Translation: Dear Mom. Your food is good.)
If you asked me what I did best, cooking would be far down on the list.
I cook out of necessity.
Hungry family + tight budget = being forced to become friends with my kitchen.
I didn't have cash for a bakery birthday cake, and the meal
  that inspired my son's note was made out of leftovers and random cans from my pantry.
One day, after getting frustrated by a recipe that wouldn't turn out,
  I asked my son why he thought I was a good cook.
'Because you love us,' he said, as he reached over to give me a kiss on the cheek.
Yup.
That works for me.
#+end_verse
** expression
