#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Cathy Suarez
* 142 Katrina and Magnolias
#+begin_verse
It was the only place I could look without sobbing: the sky.
For the entire world that my eyes could see, there was nothing but wreckage from the savage storm.
Giant trees ripped from their roots deep within the earth
  and tossed around like toy cars in a child's tantrum.
Our home so lovingly built now bore the weight of the magnificent old trees,
  crushing the roof under mighty limbs.
'God, where can I look and not see total chaos?'
I looked up through tears when the answer whispered on the wind of a crystal clear blue sky.
'Yes, Lord, the sky is clean!'
It was the start of a new life, there in the midst of pain.
For all her might, Katrina had not won!
New life and hope really can blossom and spring forth in abundance
  if only we are willing to see through eyes of gratitude!
#+end_verse
** expression
