#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Barbara Gode Wiles
* 143 Microwave Toast
#+begin_verse
The fire in the microwave is out and the microwave is fried,
  but I guess that doesn't really matter without a little background.
Alan is fifty-five and my husband of twenty-five years,
  and I am losing him to a world I can't see or imagine.
The Parkinson's diagnosis I could live with, but the dementia is frightening.
He wanted toast, so he put the bread in the microwave and set it for five minutes.
I live in a house filled with smoke, dragons, purple dogs,
  people partying all the time, six-inch grizzly bears,
  and every other thing you can imagine.
None of it frightens him...it is just all there all the time for him.
He knows who I am but isn't always sure how to shower or dress.
I am losing him to a world that will take him away from me forever, but he'll still be here.
#+end_verse
** expression
