#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Maureen Haggerty
* 144 Stitches in Time
#+begin_verse
Brian's photograph captured his grandmother as I remembered her.
Marie loved to knit, creating a rainbow of tiny sweaters
  for new or expectant mothers among her only granddaughter's circle of friends.
After Marie's death, my cousin Jeanne came across the last sweater her mother had made
  and realized it was the perfect gift for her own daughter's baby shower.
Knowing there would be tears, Jeanne decided to present her gift after the others had been opened.
What she didn't know was that each of the guests, without discussing it with the others,
  had decided to give Patricia the sweater Marie had made for her baby.
Some of the sweaters were a bit frayed or faded from frequent wearing and washing.
Tiny fingers had tugged some slightly out of shape.
But every stitch was infused with generations of love
  that now warms Patricia's sons: Liam, Owen, and Jack.
#+end_verse
** expression
