#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Eleni Zaharopoulos
* 145 For Adrian, 150 Blessings Disguised as Words
#+begin_verse
I was born to Greeks, socialized in Queens, suffered school, raised wrong,
  then right, then wrong again.
I felt love—six years strong.
I've gone mad.
I've touched God's hands.
I've stretched this heart from east to west.
I've seen my father in his final rest.
I've made love upon the water's edge.
I've met the man I was to wed.
We shared quite a life, but then he died.
My feet have traveled far and wide,
  my eyes have cried a million tears,
  my head has held a weary spine,
  my heart's been known to praise the sky,
  and I've been told I like to rhyme.
I was born in May, on its eighth day.
My Jesus year is upon my heels, I'm barely past my troubled years.
My life has held momentous things.
Sometimes I think it's best to sing, and laugh and dance dance dance dance dance.
#+end_verse
** expression
