#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Cathy Cook
* 147 You Come and You Go
#+begin_verse
My son recently died at age thirty-six—young by the world's standards.
Disabilities left him as a five-year-old, completely uninhibited.
He 'fired' people long before Donald Trump!
He loved to pull out his imaginary gun (thumb and forefinger) and shout, 'Bang!'
  when he didn't like something someone said.
Then, he'd crack a smile and let out a big belly laugh.
A while ago someone famous died, and Aaron said convincingly, 'Mom, you know what?
You come and you go.'
He was right!
That's about as simple as you can get when describing life on Earth—you come and you go.
Over a hundred people attended his service, many giving glowing accounts of his zest for life
  and how he made them laugh.
The lesson Aaron taught is that life is short,
  and what better way to leave than to leave as a friend, and a funny friend at that.
#+end_verse
** expression
