#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Becky Mantooth
* 148 The Summer Nights of My Youth
#+begin_verse
I remember the summer nights of my youth.
A time filled with catching fireflies by the jarful,
  playing games of chase and hide and seek by the light of the moon,
  or lying on the ground searching for the constellations in the sky.
The family would gather on our porch, sipping hot coffee or sweet iced tea.
Our entertainment would be the telling and listening of stories
  or the blending of our voices as we sang in sweet harmony.
When the night would call us to our beds, I would face the open window,
  gazing up at the stars in the sky.
The gentle wind would fragrance my bedroom with the aroma of the honeysuckle that grew outside.
The sounds of nature and the train's whistle would lullaby me into the land of my dreams,
  as a shooting star would bid me good night.
#+end_verse
** expression
