#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 15 An Old Soul
#+begin_verse
Born at home, delivered by Dad.
First baby.
'There's an old soul,' the elders said.
Raised with freedom and encouraged to be curious.
A child of the great outdoors, both desert and pines.
'Three going on thirty,' Mom mumbled.
Big sister to baby brother.
Big spirit in a little body.
Determined, stubborn, inquisitive, and strong.
Always learning.
Working-class girl goes to college, twice.
But still paints houses with Dad and is handy with a brush.
Never stops working.
Seeks perfection, a great strength and flaw.
Wants to travel, to write, to love and be loved.
Most of all, wants to take care of loved ones.
Now thirty-five and still learning the language of life.
What next? Marriage? Children? Fame? Fortune? Many stones still unturned.
Now Dad has cancer.
Must be stronger than ever.
The journey unfolds and the rest is yet to be written. 
#+end_verse
** expression
