#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 16 Two Sets of Parents
#+begin_verse
I was born to a young soldier and his young wife.
Two years later, I became the only daughter of a retired sergeant and his wife with three sons.
At the age of twenty-two, after getting married and giving birth to my own daughter, I reunited with my birth parents, who were still married.
They apologized for giving me away and asked for forgiveness.
I advised them that everything happens for a reason and I had forgiven them long ago.
Reader, my two sets of parents have taught me very different life lessons.
My birth parents taught me to be resilient and flexible when life changes unexpectedly.
My adoptive parents taught me to forgive when those changes are caused by others or even me.
I feel blessed to have two sets of parents who have given me tools for survival.
Thank you for letting me share my story with you.
#+end_verse
** expression
