#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 16 Two Sets of Parents
#+begin_verse
I was born to a young soldier and his young wife.
Two years later, I became the only daughter
  of a retired sergeant and his wife with three sons.
At the age of twenty-two,
    after getting married and giving birth to my own daughter,
  I reunited with my birth parents, who were still married.
They apologized for giving me away and asked for forgiveness.
I advised them that everything happens for a reason and I had forgiven them long ago.
Reader, my two sets of parents have taught me very different life lessons.
My birth parents taught me to be resilient and flexible when life changes unexpectedly.
My adoptive parents taught me to forgive
  when those changes are caused by others or even me.
I feel blessed to have two sets of parents who have given me tools for survival.
Thank you for letting me share my story with you.
#+end_verse
** expression
sergeant [ˈsɑrdʒənt]: n. a low rank in the army, air force, police etc, or someone who has this rank捕头,士官
reunit with sb.: 与某人再聚首
give sb. away: 把某人送人
long ago: 很久以前
flexible [ˈfleksəb(ə)l]: adj. a person, plan etc that is flexible can change or be changed easily to suit any new situation OPP inflexible灵活的
adoptive [əˈdɑptɪv]: adj. an adoptive parent is one who has adopted a child收养关系的
feel blessed to have sth.: 感到被保佑拥有
advise sb. that: 告诉某人+ ...
** sentence
sergeant [ˈsɑrdʒənt]: n. a low rank in the army, air force, police etc, or someone who has this rank捕头,士官
- The sergeant must be punished for the loss of a ransom of $1000.
- She hired five sergeants to keep guard when we arrived at Beijing.
- It's more important than ever to release the two sergeants, who were confined in the cell last night.
reunit with sb.: 与某人再聚首
- Reuniting with her high school classmate, she admitted that she had a major crush on him.
- I was astonished at her reuniting with her husband abroad.
- It occurred to me that she had already reunited with her lost child on the street.
give sb. away: 把某人送人
- No one could account for the fact that a normal couple gave their daughter away.
- She has been feeling guilty since giving her daughter away.
- After unloading his woolen goods, he decided to give his daughter away.
long ago: 很久以前
- I must have returned your pen back to you long ago.
- Your lost bike should have been found long ago.
- She got used to drinking milk long ago. 
flexible [ˈfleksəb(ə)l]: adj. a person, plan etc that is flexible can change or be changed easily to suit any new situation OPP inflexible灵活的
- She inferred that the website was designed to be flexible.
- It's common sense that the more flexible you are, the better salary you may get.
- A flexible businessman won't scream at a customer because of a small profit.
adoptive [əˈdɑptɪv]: adj. an adoptive parent is one who has adopted a child收养关系的
- My father proved to be adoptive, for my blood type isn't the same as his.
- She got back at her adoptive parents, who took her away from her biological parents.
- In essence, her adoptive parents devoted their lives to her.
feel blessed to have sth.: 感到被保佑拥有
- I feel blessed to have a wife, who always encourages me when I run into serious troubles.
- I felt blessed to have a set of parents, who taught me tools for survival.
- I feel blessed to have joined the army, which fought for our country and people.
advise sb. that: 告诉某人+ ...
- She advised him that everyone is on their way to a destination.
- My wife advised me that I could listen to someone only when I keep quiet.
- The sergeant advised me that a phone worth less than $1000 wouldn't be taken seriously.
