#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 18 Chase the Day
#+begin_verse
I was my own worst fortune teller.
The future just meant more disappointment.
Childhood trauma was my excuse to stay closed and overly cautious.
Why invite more shame and pain? Then I met Chase.
The pound called her unadoptable.
They said years of physical and mental abuse prevented her from being 'normal.
' She would be better off dead.
We took her home.
Maybe I saw myself in this dog.
At first she snarled and tried to bite us.
I understood that need to put up a tough front.
But then Chase became open, happy, and fearless.
She didn't bear grudges against humans.
She explored her new world and wrestled her new dog friends.
She didn't dwell on the past as permission to avoid adventure.
Chase, as usual, perches on my back as I type this story about a creature who now embraces the future without looking over her shoulder.
#+end_verse
** expression
