* Night Blooming
#+begin_verse
Out my bedroom window to the thick, cool grass; the hot night air is spiked with jasmine.
He sneaks out the back from his house next door
    (his parents drink and my mom sleeps the exhausted sleep of single mothers),
  pimply, shower-damp, brown-eyed, and sixteen, smelling of soap and nerves.
We're clumsy, thrilled, ragged with yearning, first love eventually followed by first heartbreak.
Flash-forward, astonishingly, forty-some years,
    a brave new world of cell phones, the Internet, and Facebook,
  and there’s his daughter posting about her father,
    that he’s a good man, a widower now for two years.
She makes him chicken enchiladas and French toast.
She misses her mom.
Her friends LOL and Like her.
I conjure him with grayed, thinned hair and laugh lines carved deep in sun-wrecked skin.
I'm fourteen again, inhaling jasmine, the night-blooming kind.
#+end_verse
** expression
be spiked [spaɪk] with sth.: 参杂着...
jasmine [ˈdʒæzmɪn]: n. a plant that grows up a wall, fretc and has small sweet-smelling white or yellow flowers茉莉
sneak out from sp.: 从某地溜出来
pimply ['pɪmpli]: adj. 有疙瘩的
damp [dæmp]: slightly wet, often in an unpleasant way潮湿的
be ragged with sth.: 伴随着某物
Flash-forward, + ...: 时间飞快,...
toast [toʊst]: n.吐司 
conjure [ˈkʌndʒər]: to perform clever tricks in which you seem to make things appear, disappear, or change by magic(以咒文)召唤
be carved deep in sth.: 深刻在...
inhale [ɪnˈheɪl]: v. to athe in air, smoke, or gas OPP exhale吸入
** sentences
be spiked [spaɪk] with sth.: 参杂着...
- 
- 
- 
jasmine [ˈdʒæzmɪn]: n. a plant that grows up a wall, fretc and has small sweet-smelling white or yellow flowers茉莉
- 
- 
- 
sneak out from sp.: 从某地溜出来
- 
- 
- 
pimply ['pɪmpli]: adj. 有疙瘩的
- 
- 
- 
damp [dæmp]: slightly wet, often in an unpleasant way潮湿的
- 
- 
- 
be ragged with sth.: 伴随着某物
- 
- 
- 
Flash-forward, + ...: 时间飞快,...
- 
- 
- 
toast [toʊst]: n.吐司 
- 
- 
- 
conjure [ˈkʌndʒər]: to perform clever tricks in which you seem to make things appear, disappear, or change by magic(以咒文)召唤
- 
- 
- 
be carved deep in sth.: 深刻在...
- 
- 
- 
inhale [ɪnˈheɪl]: v. to athe in air, smoke, or gas OPP exhale吸入
- 
- 
- 
