#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Night Blooming
#+begin_verse
Out my bedroom window to the thick, cool grass; the hot night air is spiked with jasmine.
He sneaks out the back from his house next door
    (his parents drink and my mom sleeps the exhausted sleep of single mothers),
  pimply, shower-damp, brown-eyed, and sixteen, smelling of soap and nerves.
We're clumsy, thrilled, ragged with yearning, first love eventually followed by first heartbreak.
Flash-forward, astonishingly, forty-some years,
    a brave new world of cell phones, the Internet, and Facebook,
  and there’s his daughter posting about her father,
    that he’s a good man, a widower now for two years.
She makes him chicken enchiladas and French toast.
She misses her mom.
Her friends LOL and Like her.
I conjure him with grayed, thinned hair and laugh lines carved deep in sun-wrecked skin.
I'm fourteen again, inhaling jasmine, the night-blooming kind.
#+end_verse
** expression
be spiked [spaɪk] with sth.: 参杂着...
jasmine [ˈdʒæzmɪn]: n. a plant that grows up a wall, fretc and has small sweet-smelling white or yellow flowers茉莉
sneak out from sp.: 从某地溜出来
pimply ['pɪmpli]: adj. 有疙瘩的
damp [dæmp]: slightly wet, often in an unpleasant way潮湿的
be ragged with sth.: 伴随着某物
Flash-forward, + ...: 时间飞快,...
toast [toʊst]: n.吐司 
conjure [ˈkʌndʒər]: to perform clever tricks in which you seem to make things appear, disappear, or change by magic(以咒文)召唤
be carved deep in sth.: 深刻在...
inhale [ɪnˈheɪl]: v. to athe in air, smoke, or gas OPP exhale吸入
** sentences
be spiked [spaɪk] with sth.: 参杂着...
- Rushing up to the manager, she complained that the elevator was spiked with the smell of dog shit. 
- She caught up with her husband, because he didn't cleaned up the room yesterday.
- Believe it or not, the yard is spiked with a special type of perfume.
jasmine [ˈdʒæzmɪn]: n. a plant that grows up a wall, fretc and has small sweet-smelling white or yellow flowers茉莉
- I went through the drawer and didn't find any jasmine tea.
- The jasmine tea needs drying this Saturday.
- It was you who presented me with a nice cup of jasmine tea.
sneak out from sp.: 从某地溜出来
- When her father found her sneaking out from the house, he ran straight at her.
- In the end, she admitted sneaking out from the house because of the invitation of her boyfriend.
- When you sneaked out from the back door, your shadow was projected on the wall.
pimply ['pɪmpli]: adj. 有疙瘩的
- You should stop touching your pimply face for your own good.
- You masked the fact that your face got pimply because of the disease.
- Her polite manner has blacked out her pimply face.
damp [dæmp]: slightly wet, often in an unpleasant way潮湿的
- His perfect alibi dovetails with the damp floor.
- A kid on the block is trying to skate on the damp floor.
- You're not allowed to play basketball on the damp floor.
be ragged with sth.: 伴随着某物
- Ragged with thrill, she didn't mind giving you some pocket money.
- Ragged with satisfaction, they reached an agreement about the railway station.
- Ragged with happiness, she was brought up to be an actress.
Flash-forward, + ...: 时间飞快,...
- Flash-forward, our tiny baby can stand up and eat by herself.
- Flash-forward, the lights on the road have been powered up.
- Flash-forward, the focal point of technique has become artificial intelligence.
toast [toʊst]: n.吐司 
- Save me a piece of toast, for I did your homework yesterday.
- No one could account for the fact that she sacrificed her body for a piece of toast.
- The piece of toast spiked with mold should have been tossed in the rubbish.
conjure [ˈkʌndʒər]: to perform clever tricks in which you seem to make things appear, disappear, or change by magic(以咒文)召唤
- After the divorce, he conjured up his ex-girlfriend and shared his apartment with her for the rest of his life.
- We were astonished at her conjuring a real man on the stage.
- Flash-forward, he became an expert at conjuring little animals.
be carved deep in sth.: 深刻在...
- The word 'Made in America' has been carved deep in the bottom of the boat.
- The murder of the president has been carved deep in the heart of all Americans.
- His name is by no means carved deep in the heart of his people.
inhale [ɪnˈheɪl]: v. to athe in air, smoke, or gas OPP exhale吸入
- Inhale relaxation into your body, exhale tension out of your body.
- Suddenly, everyone jumped into inhaling the fresh air of the top of the mountain. 
- There was a very real possibility that she had inhaled too much poisonous gas.
