#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Sometimes it is the Destination
#+begin_verse
Wanderlust has served me well.
My mom says I was hopping the crib rail before I could walk.
I learned awe at the Grand Canyon and independence when I moved to Missouri for college.
I learned patience at Disneyland in the heat of August
  with my three overstimulated and oversugared children.
I learned that the French aren't as rude as many Americans might suggest,
  and neither are New Yorkers.
I felt truly blessed to listen to
  live jazz in the French Quarter just four months before Katrina.
That an everyday experience for some,
    like seeing a blue morpho butterfly take flight
      or a capuchin monkey eating fruit in Costa Rica,
  can bring tears to my eyes
  and instantly transport me back to those precious wonder years
  when everything from a bottle cap in the dirt outside a Stuckey's
    to the St. Louis Arch on a stormy afternoon was truly miraculous. 
#+end_verse
** expression
wanderlust: n. a strong desire to travel to different places旅行癖
crib: n. a bed for a baby or young child, with bars on the side to stop the baby from falling out SYN cot British English婴儿床
Quarter: n. one of four equal parts into which something can be divided ⇨ half, third季
take flight: 起飞
transport sb. back to st.: 带某人回到某时
wonder: n. a feeling of surprise and admiration for something very beautiful or new to you SYN awe奇迹
** setences
wanderlust: n. a strong desire to travel to different places旅行癖
- I inferred that he was married to a woman who used to have wanderlust.
- It's not the lack of money, it's only the wanderlust that she possesses.
- No wonder that the failure of his business has crushed his wanderlust.
crib: n. a bed for a baby or young child, with bars on the side to stop the baby from falling out SYN cot British English婴儿床
- My wife insisted on purchasing an expensive crib which was useless in my opinion.
- The boy who hopped over crib rail now rose to power after the Great War.
- My baby looked at and turned towards me, for she couldn't reach the crib rail.
Quarter: n. one of four equal parts into which something can be divided ⇨ half, third季
- It's common sense that people in the town feast and drink wine in the Drunk Quarter.
- There're many merchants popularizing their recipes in the Drunk Quarter.
- To my surprise, there were so many people gathering around the square in the Drunk Quarter.
take flight: 起飞
- It's no use pretending that you can take flight.
- The wings have been broken, there're little possibilities that the butterfly can take flight.
- It seemed that his career took flight since he started running his own business.
transport sb. back to st.: 带某人回到某时
- The memo transported me back to those precious years that we spent together.
- The snacks full of old memories transported me back to that hot night.
- Obviously, the broken piano transported him back to his youth.
wonder: n. a feeling of surprise and admiration for something very beautiful or new to you SYN awe奇迹
- The great wall must be one of the Greatest Wonders in the world.
- It's a waste of money from taxpayers' money, the natives said about the wonder. 
- The city mayor gets obsessed with building wonders to attract people from outside.
