#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 26 Your Officer
#+begin_verse
They shoot at me with weapons and words, and I fire back with courage and compassion.
It is my duty to turn chaos into composure, pandemonium into peace,
  not only with my muscle but with my mind.
I experience life and death and cry tears of joy and pain all at the same time.
The lessons of love and despair I have practiced since birth have prepared me for today.
I end my shift with more scars than when I began, some on my body, some in my heart.
There are comrades I have buried and many I have carried, ones who held my hand from the start.
I am here for your comfort, to serve and protect you,
  to catch the burden of displaced evil and deflect harm.
I bleed, I feel, I care, and I am real.
I am your officer.
Jenny Christoforakis, Chicago police officer.
他们用武器和言语向我射击，而我用勇气与慈悲还击。

我的职责，是将混乱化为镇定，将喧嚣与骚乱化为和平，
不仅凭借我的肌肉，也凭借我的头脑。

我经历着生与死，也在同一时刻流下喜悦与痛苦的泪水。
从出生起，我就在经历和练习着爱与绝望的教训，而这一切都让我为今天做好了准备。

结束一天的工作时，我身上的伤疤比开始时更多——
有些留在身体上，有些留在心里。

我埋葬过一些并肩作战的战友，也背负、搀扶过许多人；
他们中的一些人，从一开始就握着我的手。

我在这里，是为了给你安慰，为了服务你、保护你，
为了接住被转嫁而来的邪恶所带来的重负，并挡开伤害。

我会流血，我会感受，我会在乎，
而且我是真实存在的。

我是你的警官。

——Jenny Christoforakis，芝加哥警察
#+end_verse
** expression
shoot at sb.: 
fire back with sth.: 
It is my duty to do sth.: 
composure n.: 
pandemonium n.: 
scar n.: 
comrade n.: 
serve v.: 
displaced adj.: 
catch the burden of sth.: 
deflect v.: 
