#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 24 Your Officer
#+begin_verse
They shoot at me with weapons and words, and I fire back with courage and compassion.
It is my duty to turn chaos into composure, pandemonium into peace,
  not only with my muscle but with my mind.
I experience life and death and cry tears of joy and pain all at the same time.
The lessons of love and despair I have practiced since birth have prepared me for today.
I end my shift with more scars than when I began, some on my body, some in my heart.
There are comrades I have buried and many I have carried, ones who held my hand from the start.
I am here for your comfort, to serve and protect you,
  to catch the burden of displaced evil and deflect harm.
I bleed, I feel, I care, and I am real.
I am your officer.
Jenny Christoforakis, Chicago police officer.
#+end_verse
** expression
shoot at sb.: 充某人开枪
fire back with sth.: 用某物还击
It is my duty to do sth.: 做某事是我的义务
composure [kəmˈpoʊʒər] n.: the state of feeling or seeming calm镇静
pandemonium [ˌpændəˈmoʊniəm] n.: a situation in which there is a lot of noise because people are angry, confused or frightened SYN chaos喧嚣；大混乱
scar [skɑr] n.: a permanent mark that is left on your skin after you have had a cut or wound疤痕
comrade [ˈkɑmˌræd] n.: formal a friend, especially someone who shares difficult work or danger同志,伙伴
displaced [dɪsˈpleɪs] adj.: 转移的
catch the burden of sth.: 承担某事的重担
deflect [dɪˈflekt] v.: if someone or something deflects something that is moving, or if it deflects, it turns in a different direction抵挡
** sentence
shoot at sb.: 充某人开枪
- You should've shot at him when you were not sure that he died.
- Don't shoot at my cat, who has accompanied me since my birth.
- Our comrade can't resist the temptation to shoot at people with bare hands.
fire back with sth.: 用某物还击
- I should've fired back with the mistakes she made in the university.
- Wrapping up the dog shit, she fired back with the parcel.
- Firing back with anger, he threw a stone at his classmate, who took off his pants in public.
It is my duty to do sth.: 做某事是我的义务
- It is my duty to tell you what has happened when you're not here.
- It is our duty to offer the truth to the stupid as a journalist.
- Serving as a staff member, it is my duty to finish my work on time.
composure [kəmˈpoʊʒər] n.: the state of feeling or seeming calm镇静
- If I find it hard to keep my composure, I will stop making any decision.
- There was some composure on the board when we found some wreck in the salvage operation.
- I couldn't keep my composure when I learned that some pirates had sacked our village.
pandemonium [ˌpændəˈmoʊniəm] n.: a situation in which there is a lot of noise because people are angry, confused or frightened SYN chaos喧嚣；大混乱
- The so-called justice march ended up a massive pandemonium.
- It's your duty to settle down the pandemonium as a policeman.
- In the pandemonium, the lord and several of his knights had their heads cut.
scar [skɑr] n.: a permanent mark that is left on your skin after you have had a cut or wound疤痕
- No wonder he has been wearing a hat all day, for he was hiding his scar.
- Because of his scar on his face, he lost a large number of opportunities to get a good job.
- The crime he committed is why there's a scar on his face.
comrade [ˈkɑmˌræd] n.: formal a friend, especially someone who shares difficult work or danger同志,伙伴
- It is common sense that civil servants are called comrades in China.
- With a car with the red flag coming into the camp, the comrade stood to attention.
- He should be regarded as our comrade, not a useless tool.
displaced [dɪsˈpleɪs] adj.: 转移的
- The displaced treasure must have been found.
- The pirate takes no interest in anything but the displaced treasure.
- No one could account for the fact that the displaced treasure has been found by a sheep stealer.
catch the burden of sth.: 承担某事的重担
- In the end, she gave up catching the burden of raising up her sister.
- She was asked to catch the burden of settling down the queen who just lost her son.
- She caught the burden of bringing up all of her siblings.
deflect [dɪˈflekt] v.: if someone or something deflects something that is moving, or if it deflects, it turns in a different direction抵挡
- We must have knocked him to the ground to deflect his crime.
- If we failed to deflect our enemies, our wives and children would have been raped.
- She makes an attempt to deflect the wild dragon.
** CN
他们用武器和言语向我射击，而我用勇气与慈悲还击。

我的职责，是将混乱化为镇定，将喧嚣与骚乱化为和平，
不仅凭借我的肌肉，也凭借我的头脑。

我经历着生与死，也在同一时刻流下喜悦与痛苦的泪水。
从出生起，我就在经历和练习着爱与绝望的教训，而这一切都让我为今天做好了准备。

结束一天的工作时，我身上的伤疤比开始时更多——
有些留在身体上，有些留在心里。

我埋葬过一些并肩作战的战友，也背负、搀扶过许多人；
他们中的一些人，从一开始就握着我的手。

我在这里，是为了给你安慰，为了服务你、保护你，
为了接住被转嫁而来的邪恶所带来的重负，并挡开伤害。

我会流血，我会感受，我会在乎，
而且我是真实存在的。

我是你的警官。

——Jenny Christoforakis，芝加哥警察
