#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Amy Goss
* 25 My Father's Daughter
#+begin_verse
I learned toughness from my father.
We were burying my little girl today, the first granddaughter in the family.
Focusing on my father, I vowed to make it through this with dignity.
I wanted to throw myself to the ground and curse the God who had allowed this to happen.
Instead, I focused on my father,
  the man I had looked up to and tried to emulate all my life;
  the man who had faced every adversity and triumphed;
  the man who was determined to solve any crisis
    in an emotionless and dispassionate manner with courage and grace.
As the priest concluded a lovely Latin melody, my moment to shine had arrived.
My conduct had been impeccable, and surely my father's approval would be forthcoming.
Turning from the tiny white casket that would forever be etched in my mind,
  I saw my father stumble.
Sobbing, he fell into my arms.
#+end_verse
** expression
tough [tʌf]/toughness: adj.坚韧的 n. 坚韧
bury [ˈberi]: v. to put someone who has died in a ↑grave埋葬
vow to do sth.: 发誓做某事
with dignity: 有尊严地
look up to sb.: 高看某人
emulate [ˈemjəˌleɪt]: v. to do something or behave in the sway as someone else, especially because you admire them SYN imitate 效仿
all my life: 终身地
triumph [ˈtraɪəmf]: n.v. an important victory or success after a difficult struggle胜利
impeccable [ɪmˈpekəb(ə)l]: adj. without any faults and impossible to criticize SYN perfect无可挑剔的
stumble [ˈstʌmb(ə)l]: v. to hit your foot against something or put your foot down awkwardly while you are walking or running, so that you almost fall SYN trip绊倒
sob [sɑb]: v. to cry noisily while athing in short sudden bursts哭泣
** sentence
tough [tʌf]/toughness: adj.坚韧的 n. 坚韧
- The toughness of the newborn was beyond our imagination, for he kept sucking the bottle for a long time.
- Don't tell me I must be tough after I vomit a great deal.
- To my surprise, his toughness attracted me and we got married after I realized that.
bury [ˈberi]: v. to put someone who has died in a ↑grave埋葬
- The solider in the battle field is burying an old man who is in rags of uniform.
- The defining event was that the president held on a ritual to bury those criminals in public.
- Sir, we must prepare our way for burying our comrades who held on our hands from the start.
vow to do sth.: 发誓做某事
- He vowed to work for a company abroad with dignity.
- My wife vowed to lead a happy life in the city with dignity.
- Our leaders have vowed to turn over the reign of the tyrant.
with dignity: 有尊严地
- Leading a normal life in Beijing with dignity is not easy, you must face the challenge from people all over the country.
- We must provide our people an environment in which they work with dignity.
- No one could account for the fact that the crime of the war settled down in the capital with dignity. 
look up to sb.: 高看某人
- The women who he looked up to reported many important events.
- I never ask you for looking up to your daughter, but at least treat her with dignity.
- How could I look up to you in ruins after your commission?
emulate [ˈemjəˌleɪt]: v. to do something or behave in the sway as someone else, especially because you admire them SYN imitate 效仿
- I vowed to emulate my direct leader who is always very kind to his inferiors.
- Emulating his father, he caught the burden of conquering the whole land.
- You're my idol, I admire your composure and try to emulate.
all sb's life: 终身地
- I sweared to the seven gods that I kept it secret all my life.
- I vowed to take responsibility for myself all my life.
- She decided not to step on the land of the city all her life.
triumph [ˈtraɪəmf]: n.v. an important victory or success after a difficult struggle胜利
- The triumph in the battle field belongs to all our people.  
- The president desired for a triumph to prove his greatness.
- The triumph of the battle of bastards makes him the king in the north.
impeccable [ɪmˈpekəb(ə)l]: adj. without any faults and impossible to criticize SYN perfect无可挑剔的
- The goose's manner is graceful and impeccable.
- The show your unit prepared for the leader is impeccable.
- The code I write is impeccable, and it passed all test.
stumble [ˈstʌmb(ə)l]: v. to hit your foot against something or put your foot down awkwardly while you are walking or running, so that you almost fall SYN trip绊倒
- When he realized that people had learned it was him who set up the fire, he stumbled in public.
- I find it hard to prevent myself from stumbling when I have to speak in public.
- Obviously, the old man who stumbled just now need our help.
sob [sɑb]: v. to cry noisily while athing in short sudden bursts哭泣
- No one could account for the fact that our precious daught has been sobbing for the whole afternoon.
- She tried to embrace the little boy who was sobbing.
- Sobbing, the father tried to bury his first daughter.
