#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Amy Goss
* 25 My Father's Daughter
#+begin_verse
I learned toughness from my father.
We were burying my little girl today, the first granddaughter in the family.
Focusing on my father, I vowed to make it through this with dignity.
I wanted to throw myself to the ground and curse the God who had allowed this to happen.
Instead, I focused on my father,
  the man I had looked up to and tried to emulate all my life;
  the man who had faced every adversity and triumphed;
  the man who was determined to solve any crisis
    in an emotionless and dispassionate manner with courage and grace.
As the priest concluded a lovely Latin melody, my moment to shine had arrived.
My conduct had been impeccable, and surely my father's approval would be forthcoming.
Turning from the tiny white casket that would forever be etched in my mind,
  I saw my father stumble.
Sobbing, he fell into my arms.
#+end_verse
** expression
toughness: 
bury: 
vowed to: 
with dignity: 
looked up to: 
emulate: 
adversity: 
triumphed: 
dispassionate: 
melody: 
impeccable: 
forthcoming: 
