#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Loretta Chadwick
* 26 Nick's Military Milkshake
#+begin_verse
My son, Nick, joined the army reserves back in 2000.
Come 2006, and he was sent to Iraq for one year.
I prayed and had my church pray for his safety and trusted God for it.
After his return, he shared the following story at a family gathering.
He was leaving the dining facility one day and saw they were offering mango milkshakes.
He had never heard of that flavor, so he decided at the last minute to stop and get one.
Upon leaving the building, a bomb came over the wall
  and hit the ground in front of him, knocking him off his feet.
He said his first thought was 'D***, there goes my mango milkshake!'
My first thought upon hearing about this was 'Praise the Lord for life-saving mango milkshakes!'
#+end_verse
** expression
reserves [rɪˈzɜrv]: n. a supply of something kept to be used if it is needed后备
a family gathering: 家庭聚会
facility [fəˈsɪləti]: n. a special part of a piece of equipment or a system which makes it possible to do something设施~场所
Upon doing sth., +...: 一做完某事就, ...
knock sb off sb's feet: 把某人震倒
praise sb. for sth.: 为某事赞美某人
** sentence
reserves [rɪˈzɜrv]: n. a supply of something kept to be used if it is needed后勤
- Dreaming of being a pilot, he joined the army reserves.
- Tired of the dull daily routine in the army reserves, he asked to be sent to Iraq.
- Obviously, the honest man dedicated his life to our army reserves and should be treated well.
a family gathering: 家庭聚会
- He told us a story about a small land at the family gathering.
- No one was allowed to touch his precious granddaughter at the family gathering.
- I lent him $2000 at the family gathering in front of our parents, which he denied.
facility [fəˈsɪləti]: n. a special part of a piece of equipment or a system which makes it possible to do something设施~场所
- At last, we finished our interview at the dining facility.
- It smells terrible at the dining facility.
- The boy planned to send his girl a bunch of flowers at the dining facility.
Upon doing sth., +...: 一做完某事就, ...
- Upon hopping on the bed, the puppy licked my face and tried to wake me up.
- Upon waking up, he read his offer over and over again.
- Upon asking to leave, he refused to do any work at the dining facility.
knock sb off sb's feet: 把某人震倒
- I don't mean to knock him off his feet.
- My cousin used to knock me off my feet because I didn't follow his order.
- I hate to mention it, but he knocked me off my feet because of my better performance than his.
praise sb. for sth.: 为某事赞美某人
- No need to praise him for his work; that's his duty.
- I have to praise him for his kindness; it really helps me a great deal.
- My superior tends to praise me for my hard work.
