#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: C. A. Hamilton
* 27 An Even Swap
#+begin_verse
When I got engaged in my early twenties,
  my wife-to-be was a soft-spoken young lady
    who rarely raised her voice or spouted off a retort,
    regardless of the often-snarky remarks I made about one thing or another.
One day, I asked her why we got engaged but she got a diamond ring.
She said, 'Well, you're getting me.'
I said, 'But you're getting me!'
'Right,' she replied, just as calm as you please.
'And you had to put up a diamond ring to make it an even swap.'
#+end_verse
** expression
get engaged: 订婚
wife-to-be: n. 未婚妻
soft-spoken: adj. having a pleasant quiet voice说话温和的
spout [spaʊt] off a retort: 反驳一番
snarky [snɑrki]: adj. annoyed, or saying rude things in an annoyed or ↑sarcastic way尖刻的
swap [swɑp]: v.n. a situation in which you give something to someone and get another thing in return SYN exchange交换
** sentence
get engaged: 订婚
- No one could account for the fact that they got engaged after their quarrel.
- The actor who rose to fame overnight claimed that he got engaged after the concert.
- After getting engaged, they quarrelled bitterly over who should pay for the expense of the party.
wife-to-be: n. 未婚妻
- My wife-to-be used to be a soft-spoken young girl who had to quarrel with merchants for our business.
- Great minds think alike; it's not our duty to give a great deal of money to our wife-to-be.
- His wife-to-be asked him to prepare a diamond ring for her, which he couldn't afford.
soft-spoken: adj. having a pleasant quiet voice说话温和的
- I vowed to emulate my father, who is soft-spoken but tough.
- The soft-spoken woman turned out to be our new superior.
- I don't expect my inferior to be a soft-spoken midget.
spout [spaʊt] off a retort: 反驳一番
- In case he gets angry in the meeting, you must prepare how to spout off a retort.
- Because he spouted off a retort in the meeting, he increased in popularity in our company.
- After unfair treatment, he decided to spout off a retort in public. 
snarky [snɑrki]: adj. annoyed, or saying rude things in an annoyed or ↑sarcastic way尖刻的
- He was born in a family where every member was snarky.
- It's clear that you're snarky when you feel some pressure about work.
- You have crumpled my paper up; his voice was snarky.
swap: v.n. a situation in which you give something to someone and get another thing in return SYN exchange交换
- We tried to make it an even swap after so many mistakes that we made.
- It's totally an even swap, and I didn't take any advantage of you.
- Obviously, he just made an uneven swap, sacrificing his health for the high salary.
