#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Lindsay Hunter
* 28 The Sweet Life
#+begin_verse
There are things no one wants: slivers, cancer, road rage, breaking the last of the china.
The time your grandmother goes in to have her leg amputated
  and an orderly steals her engagement ring.
It's not that these things are good; they are, truly, awful.
The moment of moments, however, is when everything you do want—
    waking up warm against your husband's chest,
    the right kind of attention in a crowded room,
    the incredible magic of your child—
  reveals itself as the story of your misfortunes told in mirror type.
I am a bona fide crazy person.
I have prescriptions, and practices;
  with their help I have, unexpectedly, gotten pretty good at life.
And what I have now are precisely the blessings
  that a broken life turned out not to preclude,
    but, to my astonishment, to produce:
      actual love; safety; sweetness that threatens to never end.
#+end_verse
** expression
