#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Lindsay Hunter
* 28 The Sweet Life
#+begin_verse
There are things no one wants: slivers, cancer, road rage, breaking the last of the china.
The time your grandmother goes in to have her leg amputated
  and an orderly steals her engagement ring.
It's not that these things are good; they are, truly, awful.
The moment of moments, however, is when everything you do want—
    waking up warm against your husband's chest,
    the right kind of attention in a crowded room,
    the incredible magic of your child—
  reveals itself as the story of your misfortunes told in mirror type.
  
I am a bona fide crazy person.
I have prescriptions, and practices;
  with their help I have, unexpectedly, gotten pretty good at life.
And what I have now are precisely the blessings
  that a broken life turned out not to preclude, but, to my astonishment, to produce:
    actual love; safety; sweetness that threatens to never end.
#+end_verse
** expression
a sliver of sth.: a small pointed or thin piece that has been cut or broken off something长条
road rage: 路怒
amputate [ˈæmpjəˌteɪt] v.: to cut off someone’s arm, leg, finger etc during a medical operation切除(手臂,腿等)
orderly [ˈɔrdərli]: n. someone who does unskilled jobs in a hospital护工
The moment of moments, however, is when + ...: 然而，最最重要的那个时刻，是当……
in mirror type: 以镜像相反的方式
bona ['bəʊnə] fide ['fide]: 货真价实地
prescription [prɪˈskrɪpʃ(ə)n]: n. a piece of paper on which a doctor writes what medicine a sick person should have, so that they can get it from a ↑pharmacist ⇨ prescribe处方
preclude [prɪˈklud]: v.n. formal to prevent something or make something impossible排除
to my astonishment: adv. 令我吃惊的是...
** sentence
a sliver of sth.: a small pointed or thin piece that has been cut or broken off something长条
- He tossed a sliver of cake into my mouth, that's beyond my imagination.
- The biographical sketch begins with a sliver of cake.
- Because of the sliver of glass, he didn't have his perfect alibi anymore.
road rage: 路怒
- There's a road rage that a man beat a woman to death, for she broke the traffic rule.
- Because of road rage, he lost his temper and stabbed the innocent child.
- I will not give you a lift, for you do have road rage which is out of my control.
amputate v.: to cut off someone’s arm, leg, finger etc during a medical operation切除(手臂,腿等)
- I must have had my bile cyst amputated, for it's gonna infect other organs.
- My mother blamed me for having my bile cyst amputated.
- Having my bile cyst amputated, my digestive capacity becomes weaker and weaker.
orderly: someone who does unskilled jobs in a hospital护工
- I was looked after well by an orderly with whom I made a friend.
- He pointed out that the orderly had stolen her grandfather's engagement ring.
- The orderly lost her faith in her superior who promised her that she would get a good salary.
The moment of moments, however, is when + ...: 然而，最最重要的那个时刻，是当……
- The moment of moments, however, was when he asked to marry me in the cinema.
- The moment of moments, however, was when I swore my oath to him in front of the seven gods.
- The moment of moments, however, was when she risked her life to report the news in the Middle East.
in mirror type: 以镜像相反的方式
- Instead, I suffered from silvers, cancer, and breaking the last of the last china in mirror type.
- No one could account for the fact that everything appeared on the scene in mirror type.
- To my astonishment, the painter drew the profile in mirror type.
bona fide: 货真价实地
- I am a bona fide crazy person, so don't test my limitations in the meeting.
- It must be a bona fide pen made in America.
- She's a bona fide crazy woman who knocked my door in the midnight.
prescription: a piece of paper on which a doctor writes what medicine a sick person should have, so that they can get it from a ↑pharmacist ⇨ prescribe处方
- In China, without prescription you're not able to buy any pharmacy everywhere.
- The paper turned out to be a prescription full of urine.
- All I asked for is a prescription so that I can buy some pills in the midnight.
preclude: formal to prevent something or make something impossible排除
- The boss tried his best to preclude being late for the meeting.
- First of first, we must preclude the obvious stupid way of ruining our party.
- At a family gather, he precluded his daughter of being the heir of the house.
to my astonishment: 令我吃惊的是...
- To my astonishment, he is on time at work every day.
- To my astonishment, there's no one but the boy who kneeled finshing the work.
- To his astonishment, he had no choice but kill the woman who he truly love and slept with his father.
