#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jennifer Stimpson
* 30 My Life, Your Life?
#+begin_verse
It's a path: At first, you follow the one laid before you.
Then you blaze a new.
Then you realize some twists and turns got you quite far from where you intended to be
  until, after backtracking a few steps,
    you see that you were rushing and did not properly orienteer.
When you deliriously step ahead, exhausted, and find yourself a clearing,
  you realize it is exactly where you need to be—
    but had not imagined the true and pure joy of arrival until this very moment.
And the path you originally sought took you where you never thought you wanted to go.
And where you were taught to go turned out to be a locale
  that you are content to never, ever visit.
Because where you are instead is the best damn place you have ever, ever been.
#+end_verse
** expression
blaze [bleɪz] v.: blaze a trail to develop or do something new and important, or to do something important that no one has done before开辟
twists [twɪst] and turns: 曲折转弯
backtrack [ˈbækˌtræk]: v. to return by the sway that you came返回
delirious [dɪˈlɪriəs]: adj. extremely excited or happy极度兴奋的
until this very moment: 直到那一刻
locale [ləʊˈkæl]: n. the place where something happens or where the action takes place in a book or a film SYN setting现场
be content to do sth.: 满足于做某事
** sentence
blaze [bleɪz] v.: blaze a trail to develop or do something new and important, or to do something important that no one has done before开辟
- He was asked to blaze a way of developing new technology instead of following in his father's footsteps.
- His garden won a prize for blazing a new path across the field.
- Even though there are a great number of twists and turns, he succeeded in blazing a new business.
twists [twɪst] and turns: 曲折转弯
- There are some twists and turns, but he runs a successful business in the end.
- These twists and turns make us disoriented in the forest.
- No one could account for the fact that there are so many twists and turns in the palace.
backtrack [ˈbækˌtræk]: v. to return by the sway that you came返回
- Our dog succeeded in backtracking home after chasing us towards the field.
- It seems that there are some details we are missing on the scene, so we must backtrack.
- I prefer to backtrack rather than go to the house of our enemies.
delirious [dɪˈlɪriəs]: adj. extremely excited or happy极度兴奋的
- She was so delirious that she forgot to tell her father about her abortion.
- The hound is hunting for the sheep deliriously.
- No one dares to stop a delirious dog from biting his bone on the scene.
until this very moment: 直到那一刻
- I realized what I had done hurt her a great deal until this very moment.
- Until this very moment, the bastard realized that he was a Stark from beginning to end.
- Until this very moment, he confessed that he raped the princess following his lord's orders.
locale [ləʊˈkæl]: n. the place where something happens or where the action takes place in a book or a film SYN setting现场
- It's a filthy locale where our royal members seek their happiness at the expense of whores.
- It's a holy locale full of sacred god statues.
- It's a smelly locale that I am content to never visit.
be content to do sth.: 满足于做某事
- She is content to finish her homework before watching a cartoon.
- I am content to finish my work in a strict order.
- Compared to his brother, he is content to stay quiet in mirror type.
