#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Joe Rhatigan
* 31 Crybaby
#+begin_verse
The boys in my neighborhood called me crybaby.
I avoided situations that could set me off:
  I stayed away from bullies, tried not to draw the attention of teachers.
But inevitably, a bee sting, a cherished apple dropped in the dirt, would bring me to tears.
I remember the day I ran to the garage to get a Wiffle ball bat.
I turned my ankle on the hose stretched across the driveway and fell.
I gasped.
With slow-motion clarity, I saw my harsh choice: Be a crybaby or grow up.
My best friend patted me on the back, but I shrugged it off.
My dad didn't look embarrassed—for once.
I limped with pride into the house to get some ice.
And with practice, each day it became easier and easier,
  and the boys soon forgot that I used to cry.
Thirty-five years later, I wish I could remember how.
#+end_verse
** expression
set sb. off: 激发某人
sting [stɪŋ]: v. if an insect or a plant stings you, it makes a very small hole in your skin and you feel a sharp pain because of a poisonous substance叮
cherished [ˈtʃerɪʃ]: adj. if you cherish something, it is very important to you珍爱的
ball bat [bæt]: 球拍
gasp [ɡæsp]: v. to breathe in suddenly in a way that can be heard, especially because you are surprised or in pain倒吸一口气
With slow-motion clarity, + ...: 以慢动作清晰呈现, ...
harsh [hɑrʃ]: adj. harsh conditions are difficult to live in and very uncomfortable SYN severe残酷的
pat [pæt]: v. to lightly touch someone or something several times with your hand flat, especially to give comfort ⇨ stroke轻拍
for once: 曾经
limp [lɪmp]: v. to walk slowly and with difficulty because one leg is hurt or injured跛行
** sentence
set sb. off: 惹毛某人
- My aunt asked us not to set the baby off, for he had caught a cold.
- It was you who set off the baby, not me.
- In case of situations that could set his bride-to-be off, he pretended to be hit by a car.
sting [stɪŋ]: v. if an insect or a plant stings you, it makes a very small hole in your skin and you feel a sharp pain because of a poisonous substance叮
- My wife is always complaining about flies stinging her in the mountain.
- Because of your greed for snacks, our baby has been stung by a bee.
- No one could account for the fact that such a little baby has been stung by a bee.
cherished [ˈtʃerɪʃ]: adj. if you cherish something, it is very important to you珍爱的
- His cherished girl has been treated like a dog in the cell.
- What you cherish may not be valuable to these lords.
- He cherished the hope that he could work for a company abroad because of his English skills.
ball bat [bæt]: 球拍
- The slave has gained his independence because of the ball bat he won at the competition.
- The luckiest guy will win a pair of ball bats made in China.
- The athlete leads a happy life, which he desires after his retirement, touching his ball bats every day.
gasp [ɡæsp]: v. to breathe in suddenly in a way that can be heard, especially because you are surprised or in pain倒吸一口气
- She must have hurt her ankle and gasped.
- He gasped after he had been knocked off his feet.
- He narrowly avoided the charge of the bull, with customers gasping.
With slow-motion clarity, + ...: 以慢动作清晰呈现, ...
- With slow-motion clarity, he took a great number of pictures of his wife with bare feet.
- With slow-motion clarity, we have learned the mechanism of how our hearts pump.
- With slow-motion clarity, the shopkeeper crumpled the clothes up to teach his assistants.
harsh [hɑrʃ]: adj. harsh conditions are difficult to live in and very uncomfortable SYN severe残酷的
- Everyone would mistake him for a criminal in such harsh conditions.
- There is a harsh choice waiting for him to make: fight or flee.
- Without your father's awareness, you shouldn't have made such a harsh decision.
pat [pæt]: v. to lightly touch someone or something several times with your hand flat, especially to give comfort ⇨ stroke轻拍
- For example, you could pat his back to prevent him from crying.
- Patting the baby slipped my mind in front of the argument.
- By patting the backs of both colleagues, the manager succeeded in reconciling the engineer and the hr.
for once: 曾经
- I didn't like apples that my father cherished for once.
- The lady used to hate the bastard of her husband for once.
- For once, I got obsessed with gambling.
limp [lɪmp]: v. to walk slowly and with difficulty because one leg is hurt or injured跛行
- Let's face the dragon limping in front of us.
- The dragon limping in the pit used to fly across the land in one day.
- The man limping in the field turned out to be the greatest warrior in the seven kingdoms.

