#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Joe Rhatigan
* 31 Crybaby
#+begin_verse
The boys in my neighborhood called me crybaby.
I avoided situations that could set me off:
  I stayed away from bullies, tried not to draw the attention of teachers.
But inevitably, a bee sting, a cherished apple dropped in the dirt, would bring me to tears.
I remember the day I ran to the garage to get a Wiffle ball bat.
I turned my ankle on the hose stretched across the driveway and fell.
I gasped.
With slow-motion clarity, I saw my harsh choice: Be a crybaby or grow up.
My best friend patted me on the back, but I shrugged it off.
My dad didn't look embarrassed—for once.
I limped with pride into the house to get some ice.
And with practice, each day it became easier and easier,
  and the boys soon forgot that I used to cry.
Thirty-five years later, I wish I could remember how.
#+end_verse
** expression
