#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Marni Kleinfield-Hayes
* 32 Memento
#+begin_verse
It was a gorgeous day, so we went to Père Lachaise, a Parisian cemetery.
We played hopscotch on the cobblestone paths 'til we found the grave of Oscar Wilde
  and left red lipstick kisses behind.
Naturally, the ghost stories started.
Then came the things we were most afraid of.
The girls listed them on their fingers.
Then came my turn, and I couldn't think of a single thing.
I realized I used to be scared of everything, of bad things happening.
But then they did happen and I got through them.
I realized it was only the unknown that had been frightening.
Whatever came next, I could face it.
There in the cemetery, we were surrounded by death.
But the sun was out, the tulips were blooming like mad,
  and we were girls in summer dresses with lipstick-smeared mouths.
Life was still beautiful.
There was nothing to be scared of.
#+end_verse
** expression
