#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Leslie Jones
* 33 Linda's Shoes
#+begin_verse
The first few years that I attended Gresham Elementary School, it was predominantly white.
In fourth grade, the teacher came before our class to tell us
  that a colored family had enrolled in our school.
She said that we should treat them as we would want to be treated.
I was delighted when Linda was seated in front of me, and we soon became friends.
One morning during recess, we traded shoes for the rest of the day.
Linda's shoes were much cuter than my old saddle shoes, and they fit me perfectly.
Linda remained the only African American in our fourth-grade class,
  but by the time I reached eighth grade, our school had become predominantly African American.
Now, I was the only white student in my class.
And only then did I have some sense of what it was like to be in Linda's shoes.
#+end_verse
** expression
