#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Brian Morris
* 34 The Reunion
#+begin_verse
In 1952, three fellow farm boys and I made a vow
  to return to our hometown in twenty years...at noon on July 4.
We imagined big changes in town,
  so we decided to meet at the southwest corner of my parents' farm.
In 1972, I took my family back home without telling them why.
I hadn't mentioned the reunion to anyone over the intervening years.
At noon on the Fourth of July,
  I stood in my parents' farmyard staring at that corner, half a mile away,
    thrilled that the Reunion was about to happen.
Noon came and went, and no one appeared.
I spent the rest of the day wrapped in melancholy but enraptured by a stream of great memories.
I have often wondered, but until 2010 had never asked,
  if any of the others had thought about the Reunion.
By 2010, only one was still living.
#+end_verse
** expression
