#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Karen Dahl
* 35 Angry Mother
#+begin_verse
I work so hard to control the imprint on their innocent souls
  because I know that their bodies may be tiny,
    but their brains are sucking in every moment, every word, every gesture.
I can't depend on anyone else to do this work for me.
It's too important.
I know (theoretically) I can't do it perfectly, not without help.
So I go to therapy to exorcise my demons, my frustrations, my anxiety.
Forty-five minutes is not enough.
So I take breaks—dinner with a girlfriend, skipping bath time.
I work, sometimes, as much for the break as for the need to excel, accomplish, engage.
I tell myself that this work, mothering,
  is more important than all the things a career could provide.
At least while they're small.
All of this to prevent my own children from becoming what I know I already am: an angry mother.
#+end_verse
** expression
