#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Ann Cardinal
* 36 The New Year's Eve Lamppost
#+begin_verse
I'll never forget my mother's response
  when I asked if I could go with my friends to Times Square for New Year's Eve:
  "My mother told me not to go, and I went anyway.
I'm telling you not to go, but you're going to go anyway.
Just remember: Grab a lamppost."
We found a spot in the crowd a block from the glowing ball.
Right before midnight, I was picked up, the crowd dragging me along.
Just when panic set in, I was carried past a lamppost.
Reaching out and grabbing it, I stepped on the base and lifted myself above the crowd
  until I saw my chance for escape.
I often think about my mother's advice
  and find myself seeking that lamppost whenever I feel unwillingly carried along.
My lampposts have come in different forms throughout my life—family, friends —
  and I'm always grateful for the support they offer.
#+end_verse
** expression
