#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jannie Holland
* 37 Pork Chops and Pop-Tarts
#+begin_verse
The morning after my father stole me away from my mother in the middle of the night,
  I had leftover pork chops and strawberry Pop-Tarts for breakfast.
It was all he had around, but it was oh so good.
Mom's boyfriend had been molesting me, and I had been rescued.
I was confused.
I was happy to be with Daddy.
I was sad to be without Momma.
I was scared.
I was a lot of things.
But most of all, I was safe.
Twenty-three years later, home from college for the summer,
  Mom's new boyfriend assaulted and tried to rape me.
I fought back and escaped.
Life has taught me to fight.
And that includes fighting for a relationship with the woman who gave me life.
Loving her, like living, is just like that breakfast I had so long ago...
  a strange medley of the salty and the sweet.
#+end_verse
** expression
