#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jennifer Dykema
* 39 Lost
#+begin_verse
It's a strange feeling, going through life day by day, simply drifting.
My whole life I've been driven: to get the best grades in school,
  to go to college, to graduate, to start a career.
Yet when life falls apart,
    when my career isn't what I had thought,
    my marriage falling apart a mere six months after the wedding,
    my husband unemployed, the bills stacking up,
    when my clothes are getting holes and I can't afford to replace them,
  my drive starts to falter.
Nothing is as I expected, and I'm unsure of my purpose.
Confused and depressed, I make my way to a family birthday party.
My brothers start arguing about the philosophy of teleportation across the table at the top of their lungs,
  and I can't help but smile.
Here, at least, I know who I am.
For a moment, I am content to just be.
#+end_verse
** expression
