#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Angela McGowan
* 40 I Have a Sister
#+begin_verse
When I was six, as the younger sister of an autistic brother,
  I decided in a very childlike way
    that I would not be robbed of the "normal" sibling experience
  and therefore proclaimed to my mother, "I have a sister!"
Her response?
Crying.
It turns out there actually was a sister
  who would have been exactly one year, one month, and ten days older than me
    had she not been stillborn.
This rocked my previously death-free existence.
I won't go into the years of survivor's guilt from being the "normal one,"
  although to this day I still laugh when it comes up and I say,
    "Me? Normal? So much for that one, Mom."
When I was twelve, I met Marianne.
My best friend and soul sister.
I will never forget the moment she told me her birth date.
Exactly one year, one month, and ten days before mine.
#+end_verse
** expression
