#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Kit Vickery
* 41 Making End's Meat
#+begin_verse
At the end of the month, it's tough to make end's meat.
You don't have much money to spend until you get your next paycheck,
  but you've still got to eat, right?
So you have to do some creative cooking with what meat you already have at month's end
  when planning your meals.
I thought that was what the idiom 'ends meet' was referencing.
Imagine my chagrin when I found out it meant having enough income to meet your expenses.
Of course, when I verbalized the expression,
  no one suspected I was thinking in terms of ground beef.
How did I finally learn of my mistake?
By seeing it printed in a book.
What life lesson did I learn?
Read something other than text messages and e-mails.
Read a book, magazine, something professionally published.
Heck, you never know what you might learn from reading a couple paragraphs in a newspaper.
#+end_verse
** expression
