#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Greg Grantham
* 42 Can You Point Me to My Hometown?
#+begin_verse
'From the DC area.'
It's what I say when someone asks, 'Where are you from?'
It gets you there without getting too specific.
What I can't answer is 'Where is your hometown?'
Upper Marlboro, Maryland,
  where I was adopted, caught fireflies, played baseball, wrote little stories,
    and made slingshots and forts in the woods.
Great Falls, Virginia,
  where we moved for better schools, returned from college,
  where my parents live, and where we still visit for the holidays.
Richmond, where I met my wife, bought my first house, and brought home our first son.
And what about Atlanta,
  where I'm watching my sons grow, coaching their games, carving out a career,
    and learning to love gardening, guitar, and fly-fishing.
My wife says, 'Why does it matter?
Who cares?'
Well, Facebook does.
They just asked me to update my profile, and it got me thinking.
#+end_verse
** expression
