#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jim Moore
* 45 My Wealthy Life
#+begin_verse
At sixteen, my guitar and I found a captive audience at the local hospital.
I went from room to room and, miraculously, patients responded with smiles and laughter.
Doctors and nurses directed me to Billy, a little boy battling cancer.
I sang to him every day for two weeks,
  then one day his big blue eyes closed forever as I held his hand.
I was just a kid, but I realized that music had the power to change lives,
  and my career path was chosen for me.
A few years ago, after performing my song 'Dreams,' I was signing autographs,
  and a frail little lady with tears rolling down her cheeks gave me a bear hug.
She told me she had recently lost her husband of fifty years
  and, after hearing the song, realized she needed a new dream.
For years I thought wealth had eluded me.
I was wrong.
#+end_verse
** expression
