#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Robyn Pasto
* 47 Dakota
#+begin_verse
Dakota.
Perhaps you've heard of him.
He's our long-coat shepherd.
His endearing spirit attracts folks from all walks of life wherever we are,
  an outdoor café, the park.
"Stunning," "gorgeous," "puppy," "grand!"—words used to describe this beautiful, gentle giant.
Tourists and locals alike ask to take his photo.
He sits, smiles, and leaves a warm heart for the encounter.
"Can I pet him?"
Lots of pets.
"Can I hug him?"
Thin arms of the Goth-clad teen wrap snugly around his neck.
Strangers laugh, cry, remember love gone by,
  sharing their stories of joy and grief when their beloved companion's time ended.
Many lives sweetly touched.
So many friends made because of him.
Such an enriching impact on our human life.
Once in a lifetime a thing of such beauty is placed in your hands.
What you do with it is your gift to the world.
#+end_verse
** expression
