#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Linda Gerding
* 49 Life's Trials and Trails
#+begin_verse
Life blessed me with two great friends in the last ten years.
The first entered my life just as she had completed chemotherapy for breast cancer.
Our shared love of horses paired us together
  as we spent many nights in my barn awaiting the birth of my mare's first foal.
I like to think the unique experience helped Lois through some very difficult times.
When Pat came along to ride my other horse,
  the three of us spent many happy and often hilarious hours
    riding the bridle trails in Ohio and Indiana.
We celebrated each of Lois' milestones— five, then eight cancer-free years.
Then the unthinkable happened.
Pat was diagnosed with uterine cancer, and this time the prognosis was not so encouraging.
Still we ride, and we laugh, and sometimes we cry as we hope for one more of life's miracles.
#+end_verse
** expression
