#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Meghan Thompson
* 50 Sorry, Mom. . .
#+begin_verse
I should have 2.5 children, a mortgage, and a dog.
At least that's what my mother says.
Instead, I've chosen a month-to-month lease on a perfectly temporary apartment.
My 'mortgage payments' go much further than most;
  instead of a white picket fence,
    they pay for Dublin, Rome, Istanbul, and any other unfenced yard I may find.
I entertain first dates with boys of all shapes and sizes,
  second dates for the men who survive the first—
  and third dates, they're few and far between.
I've settled into a lifestyle of not settling.
Of striving to live each day as though it's my last.
To live for a week, a month, a year, a lifetime as a worldwide tourist,
  a pupil of the human condition, an observer of life, love, and loss.
I'm not a complete failure, though; I do have a dog.
#+end_verse
** expression
