#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Ann Paden
* 52 A Lesson Learned
#+begin_verse
In 1990 I left a big-city job to relocate to New Mexico
  and bought a small house in a predominately Hispanic neighborhood.
Taking a neighbor's advice, I hired Juan Lorenzo to clean out the fireplace and help with yard work.
He suggested spreading the ashes over the lawn "to neutralize acidity in the soil" and set to work.
Returning later accompanied by a visitor from Chicago, we found the yard white with ash.
"Looks like Chernobyl out there, doesn't it?"
Juan laughed, brushing ashes from his jacket.
I turned to my friend and asked aloud, "How does he know about Chernobyl?"
"The same way you do," she replied.
Her words came as a rebuke, but the lesson was not forgotten:
  Prejudice is insidious and can emerge unrecognized.
But there is more to this story.
Some years later that bilingual "yardman" and I were married!
We now live in his house.
#+end_verse
** expression
