#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Deanna Cisneros
* 53 War Angel
#+begin_verse
Crossing the border into Baghdad, my husband's unit settled in for a rare operational pause.
He realized the extreme lack of sleep, but the perimeter needed to be secured.
Soon, he was back home in bed,
  feeling the most comfortable he had ever felt...so warm...not cold at all, peaceful.
Suddenly, he felt our daughter tapping him.
She was tapping, tapping and saying, 'Daddy, wake up.
Daddy, Daddy, wake up.'
He woke with a start, thinking that he would be seeing our daughter's sweet face looking down at him.
Instead, he saw movement along the horizon!
Needless to say, the sighting was verified to be enemy forces,
  and the platoon was alerted in time.
The love and devotion for her father came through
  in such a strong, spiritual way I will never forget.
God used her to help!
A little girl!
We are all truly connected by love!
#+end_verse
** expression
