#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Karen Baum
* 57 Jumped Feet First Into Bucket List
#+begin_verse
Young and brave, I created a bucket list.
First up, skydiving.
My instructor sported a jump-related broken leg
  that made me question the 'affordable lessons' touted in his ad.
I boarded the junkyard-worthy plane.
I also landed with it.
Twice.
On my third attempt, I vowed to jump.
Hesitating at the open door, I felt a shove from behind.
The pilot pushed me!
As I tumbled through the air, I cried, 'Murderer!'
Saving me, the tether line automatically opened my chute.
My peaceful descent was abruptly disrupted by the hard impact of the ground.
Failing to deflate, the chute dragged me through a freshly plowed field toward railroad tracks.
An oncoming train whistled its warning.
Inches from the tracks, the chute collapsed.
My instructor drove up alongside the tangled mess, looked down at my dirt-covered face,
  and said, 'You should have picked bowling.'
#+end_verse
** expression
