#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Brandy Harris
* 58 The Power of Perspective
#+begin_verse
In 2008 I was diagnosed with Crohn's disease.
It affects the digestive tract with painful and embarrassing symptoms...and there's no cure.
I kept a positive attitude and made changes.
After a remission period, the familiar symptoms returned.
My well-being waned.
I blamed myself, isolated, and reverted inward.
I sacrificed my energy to the illness.
I was hospitalized and my energy returned.
Suddenly, I became terrified.
I knew the 'ups' as I knew the 'downs.'
I was waiting for the other shoe to drop.
Then, I read a book by someone with Crohn's.
She described the disease as her 'teacher.'
The concept thrilled me.
I could handle a 'Crohn's teacher.'
Now, even on tough days, I create.
My 'Crohn's teacher' helps me put my feelings into something tangible.
My morning ache is now a poem; my evening nausea is now a sketch.
Struggles and challenges can be your fuel.
#+end_verse
** expression
