#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: William Aiello
* 59 A Moment That Lasts a Lifetime
#+begin_verse
There's a moment that lasts a lifetime.
September 11, 2001, in a few moments, all that we were and thought we were was gone.
Growing up, parents and teachers taught us how good we had it in America.
The world admired, feared, and envied us.
With vast oceans on two sides and a strong military, we were safe from attack.
That morning I worked at a post office about nine miles from Ground Zero.
Within minutes of the attack, we saw the tragedy on the television in our lunchroom.
Outside, the sound of police sirens wailing, ambulances speeding, and roads blocked.
No longer were we safe or feared.
We came to realize that we were a society spoiled by television, sports, laziness, apathy.
Suddenly, issues of leniency, open borders, immigration, and security
    that had been ignored
  needed to be confronted.
America would never be the same.
#+end_verse
** expression
