#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Sarah Mendivel
* 60 White Confetti
#+begin_verse
I've never seen it snow, but I've been in love.
In this moment, if I acted on how I feel, I'd bolt down to the street.
"Taxi!
Downtown!"
We'd stop by the florist, buying everything: daisies, tulips, anything snow white.
Stop by a music shop having band practice.
"I'll pay you anything, come!"
We'd buy white confetti, candles.
We'd arrive outside her place, prepare.
I'd cover the sidewalk, armfuls of flowers.
It'd be dark now.
She'd walk home from work, music playing.
I'd stand in front of her.
We'd stay silent.
I'd outstretch my hand, take hers, surprising her.
I'd pull her in close, having waited so long to touch her.
Breathing her in, dancing, violins, stars.
Suddenly, white confetti would fall from above us—the taxi driver.
When she looked up, I'd tell her,
    because she couldn't be in Chicago to see winter's snow,
  I brought it to her.
#+end_verse
** expression
