#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Kevin McCarthy
* 61 Still Laugh, with Grapefruit
#+begin_verse
"He has a proud walk," said a homeless man with an eager grin.
Jasper does indeed.
He prances, actually.
Partly it's husky athleticism.
Partly it's Australian shepherd joy in work.
Mostly it's shameless grandstanding.
Jasper T. Fetchmeister insists on carrying everything— the larger, the longer, the better.
He carried the newspaper home half a mile for many years.
Unfortunately, we lived in such isolation that few witnessed the performance.
Every day, our thespian would step into deserted intersections,
  striking poses and listening for applause.
A couple of years ago, we moved to the city, and Jas achieved the fame for which he was destined.
Kids and old folks point gleefully at the chipper dog
  with the extra-floppy ears carrying an umbrella or a notebook or a grapefruit.
From Jasper I have learned to do one thing well.
Reliably, proudly, and with love.
The rewards will come.
#+end_verse
** expression
