#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Charlotte Counts
* 63 My First Love
#+begin_verse
He was my first love.
And the thing is, I never even knew it.
Thinking back, I now realize that he and I never kissed.
It was enough to just be together, with his arm around me,
  riding around in his cool black Mercury.
He was so handsome with his chiseled good looks and black leather jacket
  with upturned collar accentuating his ducktailed blond hair.
I close my eyes and the memories come flooding back.
The teenagers dance to music from the Mercury's radio, music that has been buried inside me.
They swim, smiling, unafraid and innocent, in the bone-chilling waters of an area strip mine.
He hands her, more than fifty years ago, the unexpected Christmas gifts,
  a green and white wool scarf and aurora borealis necklace.
Forever in my heart and mind, these are the memories of my first love.
#+end_verse
** expression
