#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Michelle Dedeo
* 64 A New Nurse
#+begin_verse
My first year working as a nurse, I picked up extra hours doing home visits for a hospice.
My visits focused around helping patients manage the acute symptoms
  that were causing them distress as they struggled to live with a terminal illness.
One particular visit I made was to "June," a kind lady needing an adjustment to her pain medication.
I listened as she talked about her long life (ninety-five years)
  and the fears she had after receiving a cancer diagnosis weeks before.
I sighed and looked her in the eyes without any idea of what to say.
She could see my struggle and said, "It's okay, dear.
I don't want sympathy.
Aging is a gift given to very few, and I have cherished it."
Ten years later, her words live in my heart.
The gift of aging isn't always easy to see and appreciate, but I try every day.
#+end_verse
** expression
