#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Chely Roach
* 65 I've Got Dirt: Memoirs of Your Housekeeper
#+begin_verse
As your housekeeper, I know infinitely more about you than you do me.
I know what you read, what you eat, what hides under your bed.
I know if you're OCD or if you cram your clutter
  into three poorly hidden clothesbaskets the day I come.
I know if you attend church or believe you're a pagan goddess.
I know your politics, your birth control, and that you take antidepressants.
I know if your kids are kindhearted or if they're Eddie Haskell–type jerks
  by how they speak to me when you're not around.
I know I am a safe avenue to vent about your husband's lack of intimacy,
  the neighbor's affair, your parents' favoritism of your sister.
I know to you I am "just a housekeeper," but I don't mind.
In you, I have received an honorary degree in sociology.
In exchange, you receive my discretion.
#+end_verse
** expression
