#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Arthur Thomas
* 66 Ugh, the Job
#+begin_verse
There's too much work!
It's too stressful!
We're not paid enough!
My coworkers are complaining again.
'Ay-yi-yi,' I mutter, and close my door.
The phone rings.
It's the office downer.
While listening politely, I take a mirror out of my drawer.
Only 10:30 and I don't recognize myself.
Thirty-three e-mails.
Busy work.
More calls.
I slurp my third cup of coffee.
It dribbles down my shirt and pools around the buttons.
The office crier needs to talk.
She sits across from me.
I force a look of concern and shake my head until someone saves me.
There's a knock.
The office gossip: 'Did you hear what just happened?'
'No.'
I slam the door.
A framed Les Mis Playbill cover falls to the floor.
Later, I'm home, staring into the mirror, observing who I am.
A smile forms.
Quitting was easy, actually.
#+end_verse
** expression
