#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Jayne Shearer
* 67 Just Another Day
#+begin_verse
Yesterday used to be my anniversary.
Now it's just another day.
It was a gradual erosion.
Like a sand castle, a place was built with towers and bridges.
It grew to something recognizable.
Not Cinderella's castle, but a fortress nonetheless.
Then the tide turned.
At first, damage was done to the perimeter.
Then each wave ate at the foundation until the crumbling began.
Eventually, the big breaker came, overwhelming the last defenses.
When the water receded, the castle was gone.
No one would ever know what had been.
It was created, it stood tall, it washed away.
Now, I'm just a witness.
I don't regret the effort spent while the sun was warm.
I don't curse the forces of nature that swept it away.
It's inevitable.
Things change.
People change.
What remains... or what has been re-created...is the beauty of a pristine beach as far as the eye can see.
#+end_verse
** expression
