#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Gary Gaertner
* 69 Balloons in the Morning
#+begin_verse
Who decided balloons help sell cars?
These past dozen years have taught me many things:
  answers for any objection;
  proper greetings for phone, Internet, or in person;
  how to make you buy NOW,
    parting with as much money as possible
      in the form of down payments, monthly payments, interest rates,
      and any and every product or service I can convince you is necessary and valuable.
What a life!
With crazy tent sales, slasher sales, and push/pull/drag sales,
  I've consumed more burgers, hotdogs, and popcorn than I ever dreamed I'd eat in a lifetime.
Salesman of the Month, trips, contests, spiffs.
They trick us to sell the cars the same way we trick you to buy them.
I'm not a robber or a con artist; it just feels like it sometimes.
I'm your friendly neighborhood car salesman.
Sign here, and here and here and here.
Thanks for your business.
#+end_verse
** expression
