#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Lynda Ritter
* 70 Baby
#+begin_verse
As a child, when asked, "What do you want to be when you grow up?" my answer was always the same.
"A mom."
I had dolls, cats, and dogs that got my maternal blessings.
When I reached my late teens, I was told my dreams would never be realized due to faulty hormones.
I would sit in church each Sunday, praying that God would let me be a mother.
Everywhere I turned, I was surrounded by pregnant women.
I eventually got on with my life, did the college thing, the apartment thing,
  and then the married thing.
My husband and I decided to try the infertility route,
  and after several years of trying, crying, and praying, I finally received my big wish.
I was pregnant and thirty!
Don't let anyone tell you God doesn't have a sense of humor!
At forty-two, I had surprise baby number two.
My life's complete!
#+end_verse
** expression
