#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Lara Dillman
* 73 The Father/Son Hug Chain
#+begin_verse
My ex-husband called uncharacteristically in tears.
His father had never told him he was proud.
This saddened me.
From a close family, I feared this would trickle from one generation to the next
  unless I broke the pattern.
I wanted more for my own son and decided I had to do something.
I sat down to pen the 'old man' a note.
I wrote eight words.
'Do not break the father/son hug chain.'
I was not brave enough to sign my name.
Days later, I received a call asking if I had seen his father.
Chokingly, he explained.
His father had shown up and without a word reached out and held him to his chest.
He was filled with emotion.
Years later, after the death of his father, he informed me
  that among the personal effects they found one neatly folded slip of paper.
It was not signed.
#+end_verse
** expression
