#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Tamara Christians
* 74 The Ballad of Maren Kast
#+begin_verse
She was there when I was born.
She helped me make mayonnaise from scratch.
She taught me to use chopsticks.
She forced me to like squid.
We drank bourbon and made plaster masks
  and discussed the world and all its trials and possibility.
She is fly-fishing, kaftans, papier-mâché.
She's the smell of a toasted English muffin with garlic simmered in butter,
  the sound of soft NPR jazz...so many things remind me of her.
Over the years she coached me on being a good friend, a good Christian,
  a good daughter and wife;
  and despite the many times I have fallen short of my expectations,
    she never made me feel as though I fell short of hers.
Grandma was an artist, a poet, a mother, a musician, a chef, a wife, a believer.
She radiated goodness and warmth.
Being with her felt like being home.
#+end_verse
** expression
