#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Keith Hoerner
* 75 Holy Water
#+begin_verse
During Mass, you knew when to genuflect and make the sign of the cross.
But how to build a constant contact with God,
    a God consciousness that would guide your mired mental state to greener pastures,
  remained well beyond your understanding.
For that, I feel sorry for you.
I stand at the kitchen sink washing the one thing I took from home after you died:
  the Madonna and Child statue I meditated on,
    kneeling before you, being beaten, traumatized, loving you, year after year.
I wash it gently,
  remembering the time you unknowingly soaked a statue of St. Joseph,
    carved out of salt, in a sink of warm water.
You did not realize it would dissolve, desert you like your man-made religion.
Only to return later, pushing your hands through the milky-white water,
  confused, almost frantic, as you thrashed about in search of what you had laid there.
#+end_verse
** expression
