#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Katherine Kingsley
* 77 Running Away
#+begin_verse
We all know the term running away,
  but in March 2011, I started actively using the term in a different way.
When my son's father left me for another woman,
  I found myself left with our son, our bills, our life, and a lot of unresolved feelings.
At the top was anger.
As an outlet for my pent-up frustration at the unfairness of life, I began running.
My sister purchased a buggy for my son's first birthday; and everywhere I ran, he went with me.
As I ran through the anger, I found other emotions I didn't know how to deal with.
Abandonment.
Loss.
PAIN.
I ran off the emotions and sixty-two pounds.
Life and the act of running seemed to simultaneously get easier,
  and now I run for my health and my enjoyment.
I never thought I would say that running away gave me back my life.
#+end_verse
** expression
