#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Courtney Roth
* 78 'EB'ing a Mommy
#+begin_verse
My name is Courtney Roth.
The birth of my son, Tripp, changed my life.
He was born with a rare genetic skin condition called epidermolysis bullosa.
His skin is missing the anchors that hold it together,
  meaning any type of friction causes his skin to blister—inside and out.
He was not supposed to live to be a year old and is now two years and counting.
He lives in bandages and in pain, has a feeding tube, a breathing tube, and has lost his eyesight.
Tripp has never spoken a word,
  yet he has touched countless lives around the world by his will to fight through this disease.
My little boy is my hero and has taught me more in two years than I've learned my entire life.
I know God has big things in store for him...whether it's here or in Heaven.
#+end_verse

Editor's Note: We are saddened to report that Courtney Roth's son Tripp passed away on January 14, 2012.
** expression
