#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Michael Roberto
* 80 Arctic Explorers
#+begin_verse
Ah, the magical words were spoken over the radio.
SNOW DAY!
There was instant electricity in the air.
I knew that as soon as I completed my shoveling obligations, I was free!
As excited as I was, there was another family member who was even more excited than me.
My beloved American Eskimo dog, Sitka, knew
  that a new adventure with her best friend was just an hour away.
Once I finished my shoveling, I stepped through the front door.
There Sitka sat at the top of the stairs with her tail wagging frantically.
She knew exactly what came next.
I strapped on her harness (which I knew made her feel like a REAL sled dog)
  and out the door we went.
The neighborhood we both grew up in magically transformed into a wonderland of snow and ice.
We were no longer boy and dog.
We were Arctic explorers.
#+end_verse
** expression
