#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Deborah Teeter
* 82 Christmas Card Humiliation
#+begin_verse
After starting a new job I was given address labels by the department secretary.
She said that the people in the department sent out Christmas cards.
Christmas Eve arrived.
I hadn't even bought Christmas cards.
I remembered that throughout the year charities would send greeting cards
  for various occasions asking for donations.
I knew I had a stack.
I found them and quickly sorted them based on the pictures on the front.
I selected anything that looked remotely like "Christmas," quickly signed them all,
  stuck on stamps, labels and threw them in the mailbox.
I was proud of myself for averting disaster.
A week later my boss asked me to his office and explained
  that he had had a terrible holiday; his wife had threatened to divorce him.
I asked why.
He said, "You sent me a 'Christmas' card that said, 'I think of you in my quietest moments.'"
#+end_verse
** expression
