#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Kaitlin Jandereski
* 83 Good Morning
#+begin_verse
Sprinklers are swatting the sidewalk instead of the usual alarm clock bruising my ears today,
  and I decide to step outside.
The air swirls through my nostrils.
Enlivened, my lab greets me,
  tackling me to the ground and slopping on my face
    merely to remind me that she loves me more than anybody else ever will.
The August heat hasn't clouted away the dew of the morning yet.
I decide to go for an easy run.
Or maybe I'll go for a hard run.
It's whatever because it's my morning.
A few roosters crow from the side of the Richards's barn down my dirt road.
And I run an extra mile just to see them peck at each other.
That "accomplished feeling" is tattooed to my chest all day long like a runner's race tag.
By 7:00 a.m., I have already poured myself a glass of lemonade to celebrate life.
#+end_verse
** expression
