#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Brian Falk
* 84 My Tattooed Arms
#+begin_verse
People think they can judge a book by its cover.
I wear my pain on my arms, but my battle scars prove my individuality.
I was born crippled, fitted for casts on my newly broken legs as a newborn.
I wore those funny-looking high-topped shoes
  when most everyone else wore shoes they actually liked, at least more than I liked my orthopedics.
I fell from a tree when I was fifteen and suffered a closed head injury,
  changing the direction of my life.
Because of paralysis on my left side, I dragged my leg.
I couldn't play basketball like before.
I had to learn everything over again.
My personality changed significantly.
I wasn't angry all the time.
The bully disappeared.
Basketball was my rehab.
Thirty-two years later, no one can tell I was crippled or paralyzed,
  but they do stare at my tattooed arms, turning from my smile.
#+end_verse
** expression
