#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Chelsee Pengal
* 85 Love Letters
#+begin_verse
In fifth grade, Brett liked me.
I knew because he teased me relentlessly.
One day, he stole the hat from my head and used it in a game of catch with his friends.
Later, I received a note that said, 'Sorry I took your hat.
I like you.
Do you like me? —Brett.'
My ten-year-old brain couldn't process the strange feelings I had,
  so I did what any girl who might like a boy would do when faced with this dilemma.
I wrote back, 'No.'
After Brett read the note, he immediately ran off and started joking with his friends
  as if nothing had happened, but the teasing stopped.
Permanently.
Almost twenty years later, I'm sure his heart has mended, but mine never has.
It's a little-known fact I learned that day in fifth grade:
  When you break someone's heart, a part of yours goes missing, too.
#+end_verse
** expression
