#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Deanne Brown
* 88 Some Moms Shop, We Rock
#+begin_verse
Four years ago, six crazy forty-something suburban housewives went out on a limb, bucked convention,
  and started a rock 'n' roll band.
There was one glitch.
Not one of us could play an instrument.
But that did not stop us.
We bought guitars, replaced the couch and coffee table with drums and amps,
  and left the dishes in the sink,
    stealing a few precious moments away from our kids, husbands, 'should and ought to's'
      to follow our souls and play some rock 'n' roll.
We practiced until we had blisters on top of blisters
  and that up, down, up pattern was ingrained in our brains.
When I was diagnosed with breast cancer, we practiced in between chemo treatments.
Last night we performed in front of three hundred people at 'Cocktails 4 the Cure'
  in honor of Breast Cancer Awareness Month
    and six women who refused to let anything stop them!
#+end_verse
** expression
