#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Erik Zeidler
* 89 Snake Bite
#+begin_verse
The venom worked fast.
I felt my body giving up.
Still conscious for the moment, I felt betrayed.
Snakebites are supposed to take hours to kill you, but only minutes passed until my heart stopped.
The next two days were condensed into a few moments of vague recollection.
From a distant chamber of my mind, I heard the echo of my savior's voice calling,
  "Kids from the Bronx don't die in the woods in Kansas!"
I could faintly hear the rhythmic beats of the chopper blades, beating as faintly as my heart,
  which had been suddenly shocked back to life.
I awoke to the warm touch of my mother's hand, appropriately present on the day of my rebirth.
I was blind from hypoxia, but I could see my future clearly.
I cannot deny my passion.
Though they nearly killed me, I have dedicated my life to the study of snakes.
#+end_verse
** expression
