#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Iman Mazioum
* 90 Dressing Down
#+begin_verse
I wear the Islamic headdress, hijab, while being modestly covered,
  and I am in my school's theater productions.
Naturally, I participate in dressing room shenanigans with enthusiasm
  because only females are present.
The first time changing into costume, I shed my loose clothing
  and heard a girl remark, "Wow, you have curves!"
I blushed at the compliment.
I thought to say something nice in return, only to look around the room
  and find every other girl wearing adorable bras and fancy undies.
I looked down at my standard my-mom-buys-my-underwear underwear.
Determined to step out of my cave, I bought seven sexy undies the next day.
Slowly changing in the dressing room, I heard, "OMGEEE, LEOPARD PRINT!
Well, I never suspected!"
Suddenly I felt great, like I was the newest member of an unspoken club;
  it was my rite of passage into femininity.
#+end_verse
** expression
