#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Sabina Vajraca
* 91 The Older Sister Era
#+begin_verse
Memories of my childhood are fragmented at best.
They come in snippets, a sudden sound transporting me into the mind of a six-year-old Bosnian girl,
  while a melancholy smile haunts my grown-up American lips.
But the moment my little brother was born is etched in there forever.
Perhaps because it marked the end of my reign.
My dethroning, an unceremonious affair, happened almost overnight;
  and I, as every monarch before me,
    harbored deep resentment and secret plans of regaining the crown.
We fought, laughed, cried, and loved our way
  through war, exile, emigration, and New York City;
  but when one August, some twenty-four years later,
      he went to sleep, never to wake up again,
    I found my dreams of queenship strangely gone.
Search as I might, all I'm left with is his laugh,
  contagious and disarming, transporting me to the older sister era instantly.
And I smile, tearfully.
#+end_verse
** expression
