#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Kristin Goethals
* 92 Faking It
#+begin_verse
I'm great at faking it. . . faking the high energy, the constant drive,
  the need to be right, the feeling of accomplishment, being a great mom, a good wife,
  and an exceptional teacher.
I love my kids, my husband, and my work every day, not necessarily in that order.
When asked how I do it, I smile and have no words of wisdom except for this.
I fake it every day.
You see the four well-behaved little boys who bask in my attention,
  the meals I prepare, the perfectly ordered house, the highly structured classroom,
  but you've missed my real life.
My real life is tantrums in the aisle, running out of diapers, arguing over the dog,
  lesson plans forgotten, headaches from stress, ulcers gnawing at my stomach.
You miss the real me, where somewhere along the line it isn't faking anymore.
My life is what you see and so much more.
#+end_verse
** expression
