#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Josh Kilen
* 93 Second Chances
#+begin_verse
I left her when she was six and a half months pregnant with our son. . . On Valentine's Day.
Did I mention that's also the day before her birthday?
Yes, I was a word you can't print in Reader's Digest.
The next eight years taught me some hard lessons as I lived the consequences of my choices.
One day, sitting in a Los Angeles jail cell, I realized
  that leaving her was the single biggest mistake of my life.
I vowed to do whatever it took to win her love again.
I went back, humbled myself, begged forgiveness,
  and did my best to show her the man I'd finally become.
Eight and a half years after walking away,
  I was down on one knee, heart pounding,
    asking that same woman to spend the rest of her life by my side
    and hoping for the impossible.
I'm so thankful Megan said yes.
#+end_verse
** expression
