#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Dennis Jarden
* 95 Snap Judgment
#+begin_verse
A trip to the bank left me with a huge dose of humility and a change of attitude
  that has altered my life.
Living in an area with few minorities, I was always alert to strangers
  that didn't belong in our community.
As I left the bank, there was one of "them" in my vehicle.
Approaching my car rapidly with a shout to confront the "thief"
    who was exiting my car carrying only a puzzled look and a smile on his face,
  his first words caused me to pause.
"I'm so sorry.
I thought this one was mine," he said, pointing to his car, parked next to mine,
  which was the same type and color.
All my bigotry, deep-seated and ugly, struck me like a lightning bolt
  and left me, hopefully forever.
I uttered a feeble "That's okay"
  as I recognized a great person, legend, and entertainer...Mr. Chuck Berry.
#+end_verse
** expression
