#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Laura Guillot
* 96 Don't Ever Think You Didn't Do Enough
#+begin_verse
Meghan was an infant with a heart defect
  that I cared for in the neonatal intensive care unit (NICU).
The day of her surgery arrived.
As the hours ticked on through the day and into the evening, we knew the news would not be good.
She was sent back to the NICU with multiple infusions and a pacemaker,
  only to be pronounced dead a few hours later.
At her funeral, her father called me to come into the family room.
He hugged me and said the words that have warmed me for years:
  "Don't ever think you didn't do enough."
Here was a family about to bury their infant and they were thanking me.
The little things I did for them—
    like timing her bath and feedings so that they could participate—
  gave them memories that they will have forever.
After many years, I still carry those same memories.
#+end_verse
** expression
