#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+AUTHOR: Linda Sumsion
* 99 The Twenty-Fourth of July
#+begin_verse
July 24 was Mother's favorite day.
She joyfully fed generations of parade-goers
  who came to the park on that annual Blackhawk celebration.
We five siblings testify to the popularity of her contribution;
  we peddled roasters full of Sloppy Joes.
Her culinary charity defined our lives.
Cornstarch pudding was a preschool panacea.
Teenage fears were swallowed with vegetable stew.
Peach cake accompanied birthdays and weddings.
Churned ice cream salved the sting of fifteen divorces.
Long after roaster and childhood house were empty,
  we siblings huddled in Mom's hospice room,
    hating the cancer that robbed her ability to eat,
    but remembering foods that connected us to her.
Baked rice for Frank's furlough.
Beet greens with tears at Sarah's suicide.
Apple buckle for Dad's burial.
Reciting our lives in recipes until that final day when she wondered, 'Is it summer?'
Her generous heart had guessed...
It was the twenty-fourth of July.
#+end_verse
** expression
