#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Emotions
#+begin_verse
Welcome to positive psychology.
I'm so glad you're here.
You know one of the key founders of the positive psychology movement, Mihaly Csikszentmihalyi,
	tells us that,
	to live a good life it's not enough to remove what is wrong with it,
		and positive psychology is two things at once.
First and foremost it's an active area of science.
That investigates, those positive things that we need to add to our lives to make them good.
Yet in addition, it's a movement, a dynamic force, the world over.
And I'm captivated by the image of you out there,
	being able to take your curiosity about positive psychology to the next level.
Just by taking this course, you'll gain skills to make a positive difference,
	not only in your own life, but also in the lives of others in your community.
Now imagine the positive ripples that radiate out from your efforts here.
And now imagine those positive ripples multiplied by thousands or tens of thousands.
You are part of something much larger here.
That's the positive psychology movement and you're right at the center of it.
Now I see the broad reach of this movement first hand,
	having been elected President of the International Positive Psychology Association.
Members of IPPA as we call it, hail from more than 70 countries
	and includes scientists and practitioners.
Alongside students and anyone else in an abiding interest, in positive psychology.
In fact, IPPA can help you maintain your connection to the positive psychology community,
	long after you've completed this course.
Now speaking of community, you'll notice that I teach this online course, as a small seminar
	and that you'll be taking it alongside four in video classmates, Brett, Kelly, Patrick, and Debby.
Now I chose this format for two reasons.
First, each of these people has a unique perspective on positive psychology,
	that I know you'll benefit from hearing.
Second, I think learning happens best through dialogue and sharing ideas.
And this small seminar format, allows this exchange in the videos themselves.
Also, from time to time in these videos, you'll see tiny yellow lines, bisect the timeline.
At each of those moments, and there's one coming up soon.
I'll pause the action, to give you a moment to reflect, or answer a quick question.
Doing so will heighten your engagement with positive psychology, so don't miss out.
And you know
	scientific studies show
		that whenever you shift, from passively absorbing course material to actively engaging with it,
			your learning accelerates.
So welcome to week one.
Let's begin.

Thanks so much for being here, everybody.
This is going to be a, a fun way to learn positive psychology together.
Before we get into it, I want to take a moment just to lay the playing field and get introductions.

I'm Barb Fredrickson.
I've been studying positive psychology even before there was positive psychology.
And, over the course of the weeks that we're together here we'll be diving into a lot of that more.
So, I'm going to just stay short with that.
But I'd, love to hear from each of you guys what draws you to positive psych
	what do you hope to do with it?
So just take a moment and we'll introduce ourselves.

My name is Debbie, I am a professor here and also an administrator
	and I think I'm blending my world's of athletics and business.
And so I apply positive psychology in everything that I do,
	from competition, to coaching, to inspiring others,
		and certainly in the classroom working with young people.
Having to stay positive, and help that tender age of 17 to 25.

And I'm Patrick.
I'm a professor here at UNC.
And teach in our school of education.
So, prepare teachers councilors, and principals.
I'm interested
	because, when I was a councilor with middle school kids, when we talked about something positive,
		they really responded.
Versus the problems they were having.
And so now I prepare counselors that way
	and study hope and some other things around positive psych.
Great. Kelly?

My name's Kelly, and I have a degree in psychology
	and then I went back to school to get certified as a holistic health coach.
I work with people who want to live more fully and deeply.
And I offer coaching to improve their health on any number of levels in mind, body, and spirit.
I'm especially excited about applying positive psychology to people who have chronic illness,
	based on my own experience with that.

And I'm Brett and I'm a phd student here at Carolina
	and I research positive emotions and try to use science, to help us understand
		how positive emotions shape our health and our social relationships with others and
		how we can utilize positive emotions.
In, in our everyday lives.

Great.
I am so grateful that you're all here, joining me with in this course.
Because your perspectives are going to mean so much to the other people who take this course,
	and through other means, so, thanks a lot.
I'm really grateful.
So I really love to refer back to Chris Peterson,
	a good friend of mine who has been a leader in positive psychology.
He used to say positive psychology is not a spectator's sport.
That, you have to dive right in and experience it,
	because otherwise it's just a bunch of abstract ideas.
So we, I want to start us off by getting us familiar with the concepts of emotion.
So I want you to have an emotion. Right now.
So you know, and we're going to start off with the bad.
I want you to think of relive a negative emotional experience.
Maybe something that was so frustrating that, you know, just made you want to explode.
And just take a moment to relive that in your mind.
Think about where you were,
	who you were with,
	what had just happened
	and as you begin to relive that in your mind,
		just notice whether you can make it grow for just a second of two.
And then, take a moment to reflect on what, what stands out, in that experience.
How does reliving this, make your body feel.
How d, what does it make your face feel like?
What thoughts come to mind?
What does it, what does it make you want to do?

My first thought is to reject it.
Yeah. I don't want to go back there, and so I'm getting rigid, and heart starts racing.
Right. Yeah. Right.
It's uncomfortable.
Right, so, with any emotional experience,
	we, they either fit with or against what we want
	and so a big part of emotion experience is that is this wanted or unwanted.
Mm-hm,.
And so there's often a you know, either a embrace it,
	I want to feel this way or you know I don't want to feel this way,
	so that, great example of just that you know responses to emotion are a big part of emotion.
You can't, you can't have an emotion without having a response to emotion at the same time.
Anyone else?

I wanted to echo something
	that you mentioned in that when I think about something that negative emotion.
You said your heart started racing
	and I, I have, I experience that too both in the moment
		when I'm experiencing it but even when I'm thinking about it.
Again, sometimes, you know, you can feel your, your heart racing, and kind of tense up.
And it's, like it's a very full body type of feeling.

Right, right.
One of the things that's so true of emotions is
	it's not, emotions aren't something that just sit up in your head.
Roll around in your skull.
They are embodied.
And there's no emotion that isn't embodied
	so it, it's going to affect of th, what happens in your heart.
It's going to affect your muscle tension.
It's going to you know, certainly affect aspects of how you carry yourself, even, so.
Anyone else want to join in?

I just, my, my reaction a little bit is I want to move on,
	so it's a little bit hard for me to come
		and, you know, process that negative thing.
Yeah.
I always try to be future-focused so if, you know, I try to move from that.
So it's hard for me to go back and do that reflection on negative stuff.

Right.
So again, I, I think there's a real way
	in which individual differences come into play here a lot,
	whereas, you know some people can't move on from the negative
		and then some people you know, want to move past them really quickly.
Again, so again, you're kind of preferences
	and home way of being with emotions kind of shows up right away.
Yeah.
One of the things that I wanted to just point out is there's a typical model.
Of emotion that help us understand sort of what's all happening, in an emotional experience.
I asked you to think about a circumstance that might have made you frustrated.
So, a lot of times, emotions they start as situated experiences.
So, you know, some way in which your current circumstance is good for you or bad for you,
	but it's not like there's an automatic connection between a situation
	and everybody is going to feel the same way.
How people interpret that situation is
	the, the place
		that turns an emotion into despair or hope or,
		you know, it kind of, it's,
			it's a major gateway into whether emotions are negative are positive,
		or what flavor of positive
		or what flavor of negative they'll be.
So that interpretation phase is often called, you know, the, the sense making or the appraisal,
	that comes out of it.
	
Brett, you mentioned, that, you could definitely feel the changes in,
		in you know, heart rate, or muscle tension,
	and so, one of the things I would want to point out is that,
		you know, that's not just a private experience.
I mean, what, what, how are other people going to be able to pick up on that,
	you know certainly, your face feels kind of a little bit different.
If you're holding your jaw tight, people can see that.
You know, if you're starting to get like, tense or whatever, people can see that.
This is part of emotions aren't just a private experience.
They are, you know, whether we like it or not, they're broadcast.
Their broadcast out so, those bodily changes show up in posture.
They show up in the tone of our voice.
The show up, you know, in you know,
	what people are picking up from our smiles or our frowns or scowls.
You know, so and then this last piece Debby, you started with that.

That of responses to emotions like oh, you know, do I want to, do I want to go there?
Would I, do I want to hold, hold back.
One thing that's I, I really want to emphasize is these responses to emotion are no small thing.
I mean they you can respond to a situation by, you know, like oh I don't want to feel this way.
I don't want to show anybody what I'm feeling.
You know I'm going to try to be kind of stone faced about it.
So one response would be to try to modify or clamp down on what you were feeling.
Another response would be like, oh, I want to think about this situation differently.
You know, you might think, you first come across something kind of scary.
Maybe going to a transition to high school.
You know, your, your example.
And then you can reframe it.
Oh, it's an opportunity to make new friends.
Or, you know, something.
Some kind of a, one response could be to, I don't want to feel this way,
	let me think about it differently.
Another response is to go and change the situation,
	you know, like this is a great situation.
I want to, you know, these people are kind of at odds with each other.
I want to bring them together or something like that.
So these, responses to emotion create this, like, dynamic change over time.
So it's sometimes people take emotions, just to be that feeling state,
	like, oh, I feel happy, or I feel irritated,
	but what we have is so much more in terms of, you know, there's the embodied.
Thoughts and a dynamic change in what, what those are.
So, from a scientific perspective we don't think of emotions as just a feeling state,
	it's an embodied feeling state
		that comes with action urges
		that comes with responses
		that get us to change the situation or, or change our, our thoughts.
So, anyway thanks for playing along with going, going to the negative for a moment.
But I appreciate that.
#+end_verse
** experession
positive psychology
be glad + ..
the founders of movement
it's not enough to do sth.
at once: at the same time
foremost :the best or most important
need to do sth.
add A. to B.
in addition
the world over
be captivated by sth. :to attract someone very much, and hold their attention
take sth. to sp.
sb's curiosity about sth.
take this course
gail skills
make a adj. difference
in sb's own life
in the lives of others
ripples
radiate out from sth.: spread out
be multiplied by number:
be part of sth.
be at the center of sth.
the broad reach of sth.
first hand
elect: to choose someone for an official position by voting 
as we call it
hail from
practitioners:someone who works as a doctor or a lawyer
be in an abiding interest
maintain sb's connection to sth.
complete this course
for two reasons
have a adj. perspective on sth.
benefit from doing
from time to time
bisect:formal to divide something into two equal parts
reflect
heighten sb's engagement with sth.
miss out
studies show that + ...
absorbing :
 enjoyable and interesting, and keeping your attention for a long time: 
accelerates: if a process accelerates or if something accelerates it, it happens faster than usual or sooner than you expect

a adj. way to do sth.
lay the playing field: 布置游戏场地

be diving into: start dong sth.
stay short with that
draw sb. to sth.

administrator

blend:to combine different things in a way that produces an effective or pleasant result, or to become combined in this way
my world's of sth.: 丰富的
tender age:tender age the time when you are young or do not have much experience

councilor:a member of a council
principals:someone who is in charge of a school
versus the problems

get certified as sjob.
holistic health coach:
	holistic medicine/treatment/healing etc medical treatment based on the belief that the whole person must be treated, not just the part of their body that has a disease
offer sth. to sb.
any number of levels in sth.
apply sth. to sb.
chronic illness
be based on

shape our health
in sb's everyday lives

through other means
spectator
dive right in :to start doing something with enthusiasm
get sb. familiar with
relive
	to remember or imagine something that happened in the past so clearly that you experience the semotions again
in sb's mind
stand out
come to mind

thought is to do 
gett rigid: used to describe someone who cannot move, especially because they are very frightened, shocked, or angry

fit with/against
embrace:  the act of holding someone close to you, especially as a sign of love
have a response to emotion  

tense up:very nervous and worried

affect of sth.

move on
future-focused
do reflection on sth.

come into play: it begins to be used or to have an effect
right away
a model of sth.
it's not like + ...
feel the same way
turns A into B

pick up
jaw
	one of the two bones that your teeth are in
in posture
frowns
scowls

hold back` to stop something from happening or advancing, or to keep someone from doing something
clamp down` to take strong action to stop or limit a harmful or unwanted activity
reframe` 再构造
it's an opportunity to do sth.
at odds with sb.`  not agreeing with each other
irritated` feeling annoyed and impatient about something
