#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 02 Lazy Summers
#+begin_verse
A single fly swooped around my head making that familiar buzzing sound.
I started to swat it away, but then stopped when I realized it made me happy.
How odd, I thought.
A fly is bringing a smile to my face.
I couldn't understand it until I heard the buzzing sound again.
Then I knew. It was the sound of summer.
It was that familiar buzzing that joined in the chorus of childhood laughter
	during so many lazy summers.
Suddenly I had memories of straw hats and bike rides and lazy rivers;
Fourth of July cookouts and campouts and hideouts; sunburns and secret forts and double-dog dares.
The memories swirled around my head like that fly, reminding me of some of my happiest days.
I decided
	the fly should stay with me today to accompany my thoughts while I reminisced some more. 
#+end_verse
** expression
swoop
- A single newbeen is swooping around my head.
- There are some flies swooping around the shit which you just stamped.
- If the police arrived on the scene, they would see a fly swooping around the shit.
buzz
- It's impossible for a cat to make a buzzing noise.
- I heard a buzzing sound in the morning which your iphone made.
- I heard a strange buzzing noise from the kitchen
--------------------
swat it away
- I wished I had swated it away at the first time.
- I tried to swat the fly away from my house.
- The woman who is swating a fly away is your English teacher.
bring a smile to my face
- The arrival of my friend, Zhangyan, always brings a smile to my face.
- It brought a smile to her face to receive a gift from her husband.
- He said he found Beijing very exciting, which brought a smile to my face.
A. join in the chorus of B.
- Just a moment earlier, some foreigners joined in the chorus of busmen who are striking.
- Some strange noises have joined in the chorus of these laughter.
- He joined in the chorus of the group to stand to attention.
have memories of
- After he had memories of life before his car accident, everything returned to normal.
- He makes no effort to have memories of the right answer.
- I'm glad that you have memories of your father's birthday.
swirl around
- The newbees swirled around her head, reminding her of some unpleasant time at the monastery.
- I couldn't fall asleep because the buzzing noises swirled around me last night.
- I attempted to prevent myself from the buzzing noises swirling around my head.
reminisce (about)
- A group of pop singer is reminiscing about the performance which they gave at the station.
- The captain has reminisced about the sinking colossal.
- A group of pianist was reminiscing about their hard early years.
