* 论良家子、小镇做题家们被设计好的人生
李新野的《指南》中，有这么一段话：“为什么我们这一代，最优秀、最努力、能力最强的一代中国男人，像犯人 一样关在学校里面20年甚至更久，然后就结婚，被一个老国女按着头，逼着在21年买房，逼着申请30年按揭贷款？为什么我们的人生，被安排着从20年的监狱生涯释放，进入了30年流放北上广深杭的劳改生涯？为什么我们被迫戴上了电子脚镣，每个月时间一到，三十年房贷就自动从我们帐户上扣款。“

这段话很直白、很扎心。自毕业工作以来，我就隐隐觉得人生有什么不对。

一、良家子、小镇做题家的困境

我是在三线建设的厂区长大，全家dang员，从小受的是红色熏陶，立志做一个对社会有用的人。最初我觉得异常是人不应该被困在三十年水泥壳子里，后来我发现高大上的工作大多都是草台班子唱戏而虫豸居其位，再后来便是被各种压力裹挟到结婚生子熬夜加班的那一套。只要心里有所放松、有所思考，便会有一种愧疚机制发作而不得不继续往前。

思来想去，咱们的这套体系，从一开始就不是为了“培养人”，而是为了 “筛选人”。听话、刷题、熬夜、不反抗，被教育好好读书=未来幸福。于是，我们被训练成服从、忍耐、负责、拼命。

在这套模式下，越努力、正直、守规矩的男生，便会越优秀、越讲责任，于是自身在恶劣的社会环境中被规训、绑定、消耗得越狠。结果就是前十八年，用最自律的人生，换一张大学入场券。进入大学后，往往面对的是高等教育的欺骗，当满怀信心打开礼盒时，礼盒里面却是空空如也。毕业后，所谓的大学敲门砖根本不保证幸福，只保证我们能继续干相对体面的活。

归根结底，我们良家子、小镇做题家走的是别人画好的社会主流赛道：读书→考学→上班→买房→结婚→养娃→还贷到老。

这条路上不能停，不能错，不能逃，不能抱怨。一旦踏上，前半生被教育规训，后半生被债务规训。每月自动扣款的贷款，让人不敢辞职，不敢生病，不敢任性，连崩溃都要挑时间，我们不是在生活，而是在 “履约”。所以家长压力大鸡娃，学生们考不好就抑郁、跳楼，社畜们被毕业优化也抑郁、跳楼。

在这套默认剧本里，老实、努力、负责任的男生最容易被用来消耗。青春被冗长的学业消耗，经济被房贷、婚姻绑死。最守规矩，最容易被道德绑架，也最容易被牺牲吃亏。我们克服欲望期待延时满足，但结果往往差强人意。仔细想想，我所崇拜的清华学神、港大天骄，也被这套体系逼出了抑郁症、强迫症。良家子、小镇做题家们痛苦啊，这不是因为我们弱，而是因为我们太好、太努力、太正直了。“躺平“思想，li工思维，ren矿这些词，正是所有入局者的对此情况的反思。

二、解放思想与寻找对策

这个剧本我们可以不演，放弃必须结婚、必须买房、必须按别人的期待活、必须背上 30 年枷锁的包袱。我们良家子、小镇做题家正直、努力、负责的做事，不是为了去填它们挖的坑。

第一步停止自我谴责，承认真相，否定被长久灌输的愧疚机制。我们已经努力了几十年，我们对得起所有人，唯独对不起自己，我们很少为自己而活。放弃那些宏大叙事吧，专注于把自己的生活过好。这并非精致利己，而是做真正的一个人。我们听话、努力、上进、负责，是任何国家、任何社会最宝贵的基本盘，我们不欠父母、不欠社会、不欠婚姻、不欠房子。之所以感到痛苦，是因为别人把我们当工具用太久了。我们没有对不起任何人，我们已经够努力了。

第二步把别人的剧本全部扔掉。社会给我们的默认剧本是：读书→考公/大厂→买房→结婚 →生娃→还贷 30 年→熬到老。这剧本我们不演了，不演 “必须买房”，不演 “必须结婚”，不演 “男人必须扛下一切”，不演 “让所有人满意”。这不是叛逆，而是拿回人生主权。

第三步按自己的标准来重新定义 “成功”。 我认为对于自身成功只有三条：身体舒服、心里不憋屈、手里有钱便手里有选择权。至于其他房子、车子、彩礼、婚姻、面子、别人的评价全部降级为可选项而非必须项。

第四步财务解绑。不背 30 年死刑判决书，现在的00后就比前辈们做的好，他们很通透。30 年房贷=卖身契≠资产，我们可以这样选：不买房、租房住，去低房价城市生活，买小的、便宜的，绝不背到窒息。不把房子当成结婚前提，不被房子绑架。

第五步婚恋解绑。不做供养者，只做合作者。现在婚恋环境高要求、高成本、高压力、低尊重，对老实男生最不友好。我们要守住三条底线：不扶贫、不舔、不单方面付出，不同心不同行不结婚，不被 “年龄到了” 绑架，结婚的唯一意义：两个人比一个人更快乐、更轻松。否则，单身永远优于烂婚姻。

第六步工作解绑。卖力气，不卖命。卖时间，不卖健康。能摸鱼就摸鱼，能准点走就准点走。不把公司当归宿，不把老板当亲人。2000年初的国企大下岗，就已经将无私奉献之类的东西扫进了历史垃圾堆。我们的命，比单位的业绩贵一万倍。单位就像青楼，我们要做的就是尽快赎身，而不是在里面争做头牌。

第七步探寻属于自己的人生模式。保住健康、不熬夜、不硬扛、不焦虑到崩溃。保住现金、少负债、少提前消费、不背巨债。降低欲望，不跟人比房、比车、比老婆、比彩礼。只对自己负责，先顾好自己，再谈其他。拥有随时离开的能力，不困在一座城、一份工作、一段关系里。自我拥有一段不被定义、不被绑架、不被消耗的剩余人生。我们前 20 年，在为分数活。工作后被压力逼着为房子活。但我们可以选择：为自己活。找到自己所热爱的事业和方向，因为热爱，所以追求卓越，因此有所成就。

愿良家子、小镇做题家被温柔以待，我们不是犯人，不是劳改犯，不是还债工具，不是供养者，不是空心人，不是必须满足所有人期待的工具人，我们只是我们自己。
