#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

评价的标准: 
	第一:不在别人的嘴上,而在自己的内心里.
	第二:在于客观事物(Critical Thinking)
	客观事物比自己内心更重要,但是事物的发展是由自己内心到客观事物的
如何活得轻松:
	1. 有一个非常清晰的界限,什么事情我对应做到什么程度就够了
	2. 在做到这个程度以后,把外界的声音屏蔽掉
	3. 做完1和2之后,看日子是越过越好,还是越过越差.越过越好说明自己做的对了,越过越差了说明自己做错了.
遇到事情奔着解决事情去,而不是我不爽我就要和别人干架.

** 如何活得轻松？
你要是在这个世界上想活得轻松一点，有些东西是要修炼出来的。
*第一是你要有一个非常清晰的界限，什么事情，你做到什么程度就行了。*
*第二是你做到这个程度之后，外界的声音你能屏蔽掉。*
至于你自己定义的这个界限合理不合理，没有这两点重要，这已经是后来的事情了。
合理不合理那是别人的评价问题，你自己觉得合理就行了。

上面这两点你修炼不出来，不只是家庭成员借钱这件事，你会发现生活到处充满了矛盾，会过得非常不开心。
你用不着狂躁什么，你希望别人按照你的方式来行事本质上就是你恐惧啊，你恐惧把自己表现出来，你恐惧别人对你有不好的评价。
你如坐针毡，歇斯底里，不都是因为你的情绪容易失控嘛。

就拿这件事来说，你有20万，你的大姑子第一次说可能要跟你借钱。
你当时就不舒服，没当面说。
这个就非常奇怪呀，对不对？
一件事情摆到你面前，你该怎么处理就怎么处理，不舒服有什么用，当你第一次听到这个想法的时候，你的内心已经暴躁不安了。

其实是一个人他的性格是什么样的，他的生活就会是什么样。
有一种人他是解决问题优先，另一种人是别人不爽了我就要跟别人干架。
前者一定比后者过得好这是毋庸置疑的。

她可能要借钱，你脑子当时就应该盘算好，这个钱借不借，借多少，怎么借，你要她怎么还心里想好了 盘算好了，等到事情真的出来了，你就把你的想法抛出来就行。
你有老公的话你就事先跟你老公通个气，这个事情我打算这么干。
因为他是你老公，他不是你的员工，你也需要给他一点尊重，所以你需要跟他解释一下你为什么这么干，道理在哪里。
他要是能跟你说出个123456，你就沟通一下，但是他如果是说什么他姐姐不容易什么乱七八糟的，试图用情感把你脑子搞晕，
你就判断一下你老公的收入能不能为他的想法买单，如果他一年能赚几百万的，听你老公的话让你老公喜欢你好处更大，你就听他的。

如果他收入不行，耳根子还软，脑子还迷糊，你就知道你老公是什么人，不搭理他就行了。
你就说天王老子来了这个事情也得这么办。
然后你该吃吃该喝喝该干嘛就干嘛去。
有什么好吵架的呢，别人想跟你吵，也吵不起来啊。
你看整个过程，我们没什么情绪的，就是该怎么处理你就怎么处理，别人想跟我们吵，我也不接招。

因为吵架亏本啊，我本来可以开开心心过一天，我脑子坏了我跟你吵架，溜溜球了。
我们都是解决问题是第一的。
有事就解决，没必要讲很多话，更没必要跟很多人解释什么，你只需要服务你的利益合作伙伴就行了。

坦白说，如果你抓着这个钱，是为了这个家的利益最大化，你的脑子能意识到这一点，你跟你老公的关系一般不会崩。
如果你这样了，还会崩，那这男人也不值得你持有。
你只要不亏本，你可以选择放弃，如果选择放弃亏本太大，那没办法了，这个事情就解决不了了，你尽量调整心态去接受吧，你选错了人，这个代价你要付的，这样起码你情绪上好过一点。
等到时间线拉长了再来看我们日子过得怎么样，越过越好了说明你那个界限没问题，越过越差了说明你脑子的认知有问题，你再学习再调整就行了。
所以你看我们过得多轻松啊，对吧。

时间长了，身边的人都知道你是这个性格了，奇妙的事情就发生了，没人会再来烦你了。
吾道一以贯之，别人都知道你的道了。

说的深奥一点，我常常讲周围的世界是一个人内心的映射，其实你自己的心是什么样，你周遭的世界就呈现一个什么状态。
有的时候别人认为我很自私的，那么他们就知道我在这个事情上一贯是自私的，他们慢慢地也就接受这个东西，不会来烦我了，对吧。
是因为吾道恒一，我的内心是稳定的，不动的，然后我的世界慢慢就会稳定下来，消停下来。
这个东西是要一点悟性去体会的，能体会出来，能做到，日子就能过得好。

体会不到的话麻烦不断，生活啊，工作啊之类的，会充满了各种各样的麻烦和矛盾，根源在这里！

* 人际的奥秘 

** 第二章 建立人际关系的基本准则

*** 第一节 正视自己
自己想成为什么样的人,取决于自己.少抱怨他人,多要求自己.

**** 确定自己要做什么样的人
1. 硬汉辛苦: 最怕变节; 如果无知,容易被利用; 做好了流芳百世
2. 顺民划不来: 听话
3. 隐士不容易: 不闻不问,都是别人的事; 没贡献也没麻烦
策略: 尽量当顺民,偶尔当硬汉,必要做隐士
	领导看的起我,就当硬汉;
	讲了领导不听,就当隐士;
	领导对我一般,就当顺民.
把这种策略当作自己的价值观,久而久之就会吸引志同道合的人.	

要成为什么的人?
尽量当顺民,偶尔当硬汉,必要做隐士.领导看的起就硬,看不起就隐,一般就顺.

**** 处理好自己和自己的关系
如何处理好自己和自己的关系?
合理地接纳自己.优点发扬,缺点慢慢改成优点(缺点也是有时空条件的)
不能接纳自己的人,情绪不稳定.和人相处要么刻意显优越,要么相当自卑.

对待别人的批评?
看看自己说话的人是谁,看他说的有没有道理.不要过分害怕得罪人,成了老好人.

**** 以实实在在为做人的准则
怎么做人?
分三部分: 实实在在做人,规规矩矩做事为地基; 随机应变才能建起大厦; 培养自己的声望

随机应变?
1. 不忘本的情况下随机应变.
	 解:要不要对老婆说谎? 要,但是要不在伤害老婆前提下, 对老婆有好处说谎.
2. 多听~多看了解环境,适应环境,然后再动脑筋改善环境,最后才是创造环境.
	 多听~多看意味着坏的也要听,防范于未然.
	 要少说:贸然说,信口开河降低了自己的信用.看准了再说,才能让别人高看一眼.
		解: 看准了, Critical Thinking

靠沟通能力来养望? 
沟通能力指的是,说的话别人听的进去,愿意接受,引起别人说同样的话,最后引起共同的行为.

*** 第二节 善待他人

**** 待人需要诚心

**** 待人需要诚心

**** 待人需要礼貌

**** 待人需有差别



*** 第三节 三大禁忌
锋芒毕露、自负和轻率

