#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* SECTION 1: STARTING THE DAY

** 1. First Thing in the Morning
#+begin_verse
Dan's alarm clock rings and he wakes up.
He gets out of bed.
He goes into the bathroom.
After using the toilet and flushing it, he washes his hands.
He brushes his teeth, shaves, and takes a shower .
He dries himself off with a towel.
Then he brushes his hair.
He gets dressed.
He makes breakfast and eats it.
Then he leaves the apartment.
#+end_verse

toilet
bowl
razor
shaving cream

** 2. Brushing Your Teeth/ Flossing
#+begin_verse
Jenny runs some water over her toothbrush.
She squeezes toothpaste onto her toothbrush.
She moves her toothbrush up and down and back and forth.
To rinse her mouth,
	she takes some water, swishes it back and forth in her mouth and spits it into the sink.
She rinses off her toothbrush.
Then she puts it back in the toothbrush rack.
#+end_verse

faucet
tube

*** She flosses her teeth by
#+begin_verse
She flosses her teeth by pulling out a long piece of floss,
	slipping it between her teeth and moving it back and forth and up and down.
#+end_verse

** 3. Taking a Shower
#+begin_verse
Dan pulls the shower curtain shut.
By turning the knob, he turns the water on.
He washes his hair with Shampoo and the rest of his body with soap.
Then he rinses off withwater.
After turning the water off, he steps out of the shower.
He takes a towel from the towel rack.
Then he dries himself off.
He wraps a towel around himself, and he dries his hair.
He puts some deodorant under his arms.
#+end_verse

shower head
on/off
knob
shampoo
bathmat
towel rack
blow-dryer

** 4. Getting Dressed - A Man
*** Tom puts on ...
#+begin_verse
Tom puts on some underwear, a T-shirt, some socks, some pants and a shirt.

Tom puts on his underwear.
Tom puts his underwear on.

Tom chooses some socks and puts them on.
Tom picks up his shirt and puts it on.
#+end_verse

*** A? Some? A pair of?
#+begin_verse
some pants
a pair of pants

some socks
a pair of socks

some shorts
a pair of shorts

some underwear
some underpants
a pair of underpants

a T-shirt

some shoes
a pair of shoes

a jacket

some pajamas
a pair of pajamas

a shirt

some glasses
a pair of glasses

You can say: “a sock” “a shoe".
BUT when talking about clothes, do NOT say: 'a pant','a pajama','an underpant','a short' 'a glass'.
#+end_verse

*** Putting on a Pair of Pants
#+begin_verse
Tom steps into his pants, then he pulls them up.
He fastens the waistband and zips up the fly.
He slips a belt through the belt loops and buckles it.
#+end_verse

