* NCE3 

* other(If they are too many, then split them)
** Let him Go, Olivia
It's over.
pass away
in recognition of sb.
write this story as a tribute to sb.
make it possible for sb to have done

** Children’s Engineering Workshops.
work together to do sth.
love doing
all the time
be to do
be attached to sth
from A to B:
work out
pick it up
mind doing
think up
come up with
the shape of sth.
clear up
move sth. to st.
up past the sp.

** stoicism
achieve sb's triumphs
the likes of [sth.]: is used to refer to people or things of a similar type or category
have access to sth.: possess the ability or permission to use, enter, or obtain something.
come to sb.: emphasizes the process of understanding or realization
in turn: used to explain how a series of actions or circumstances are interconnected
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."
put on ...: mean to organize, present, or perform a show, event, or production.
prime minister: the most important minister and leader of the government in some countries which have a parliament
the course of ...: is used to describe the progression or development of something over a period of time.
at the root of sth.: refers to the fundamental or foundational essence of a concept, idea, problem, or situation
resonate with: if something such as an event or a message resonates, it seems important or good to people, or continues to do this
refer to sth as sth.: regard sth. as sth.
	
