* Nacos
Nacos:
1. 注册中心: 服务在哪里?
2. 配置中心: 服务的配置放在哪里?
** Nacos-注册中心
注册中心:
- 服务注册
- 服务发现
- 健康检查
- 服务上下线
- 集群与AP/CP
*** 注册中心-服务注册
服务注册: 服务启动后,把服务名,IP,端口都告诉Nacos,Nacos把其记录下来. 一个服务,可以有多个服务实例.

服务名: user-service
IP: 192.168.1.10
端口: 8080

Nacos
user-service:
- 192.168.1.10:8080
- 192.168.1.11:8080
- 192.168.1.12:8080
*** 注册中心-服务发现
服务发现: 订单服务想调用用户服务,会问Nacos user-service在哪, 然后Nacos告诉真实的ip和端口地址.

*** 注册中心-健康检查
健康检查: Nacos需要知道哪些实例还活着

服务启动时,向Nacos注册了,这时候服务是正常的,但是后面如果知道其有没有挂?

**** 注册中心-健康检查-心跳
服务实例不停地向Nacos发送心跳包, 如果一段时间Nacos没有收到该实例的心跳, 就认为这个实例是不健康的

**** 注册中心-健康检查-为什么需要?
因为如果没有健康检查,可能某个服务实例已经挂掉了,Nacos仍然认为其是正常的

**** 注册中心-健康检查-不一定是服务主动发心跳
不一定是服务主动发心跳,也可能Nacos主动去检查服务实例状态

*** 注册中心-服务上下线
启动服务:
1. 注册到Nacos
2. 上线

服务正常关闭:
1. 从Nacos注销
2. 下线

*** 注册中心-集群与AP/CP
** Nacos-配置中心
配置在哪里,如何统一管理

为什么需要配置中心?
因为服务多了,同一服务的服务实例多. 如果需要改某个服务的配置,需要同时改多个服务实例的, 所以需要集中管理

Nacos不单单提供配置的存储,还可以动态刷新应用的部分配置.

# * RPC(Remote Procedure Call)远程过程调用

** Feign调用
1. Feign动态代理: 把Java方法调用转换成HTTP调用的描述
   Spring+Feign为其创建了一个FeignProxy代理对象. 代理读取接口上的服务名和Http Method,路径.
2. 服务发现
   Feign代理对象上只有服务名,所以需要问Nacos服务实例的具体地址.
3. 负载均衡: 由客户端负责负载均衡,用的是Spring Cloud LoadBalancer
4. 构造HTTP请求
   根据Proxy对象的ip~端口~path, 传参序列化成HTTP的请求体, 然后发HTTP请求
5. 其他服务实例收到请求,并且返回结果
6. 结果返回Feign, 把从收到的结果, 反序列化成对象.

** Gateway
