* MQ
** MQ为什么存在?
生产者把事情交给队列,不要求消费者立即完成. 以此换取,异步~解耦~抗流量的能力.

假设下单的业务逻辑是:
1. 用户下单
2. 增加订单
3. 扣库存
4. 发优惠券
5. 发短信
6. 记录积分
------------全部同步调用
缺点: 任何服务慢了,导致整个请求慢;任何服务挂了,影响下单
Order
  → Inventory
      → Coupon
          → SMS
              → Point
------------加入MQ
             ┌→ 库存服务
订单服务 → MQ ├→ 优惠券服务
             ├→ 短信服务
             └→ 积分服务
1. 异步: 原本需要等待下游完成,才能进行下一步,变成只发个消息
2. 解耦: 订单服务不需要关心下游,后续要增加新的下游,只需要订阅消息,不用修改订单服务
3. 削峰: 订单服务突然来了10万个请求,下游服务一秒只能处理5000个,MQ先把请求堆住,下游按自身能力慢慢消费
** 消息丢失
消息丢失: 生产者以为消息发出了,但是最终消费者没拿到
消息链路: 生产者->Broker(MQ服务器)->消费者
*** 1.生产者丢
mq.send(message)后,生产者不知道Broker到底收到没有

解决: 发送确认机制.生产者发送完之后,再向Broker确认是否成功
- RabbitMQ: Publisher Confirm
- Kafka: producer ack配置

*** 2.Broker自己丢
消息已经到MQ了,但是MQ服务内存里面的消息还未落库

解决: 消息持久化(磁盘)+副本机制. 确保即使一个Broker挂了,消息也不会丢
- 消息写入到日志文件
- 多副本
- acks=all

*** 3.消费者丢
两者模式:
- 先ack再执行业务: 执行业务过程中宕机,导致业务没执行,但是被消费了.
  1. 接受消息
  2. ack
  3. 执行业务. 
- 先执行业务再ack: 业务执行完,未ACK,导致MQ重复发送消息,消费重复
  1. 接受消息
  2. 执行业务
  3. ack
** 消费重复(保证消费幂等)
不要期望MQ只投递以此,而是让业务代码做到: 同一条消息执行多次,结果和执行一次一样.

具体解决方案:
1. 增加消费日志表,并给消息id增加唯一索引
2. 代码里面,先插入消息日志,如果报主键重复直接返回
3. 代码整体增加本地事务,确保插入消息日志和执行业务代码的原子性
** 消息积压
消息积压: 生产者生产速度>消费者处理消息的速度,导致MQ的消息越堆越多
*** 1.突然的流量高峰
平时:生产2000/s,消费2000/s
秒杀:生产10000/s,消费2000/s, 开始积压
这种情况本身也是MQ的削峰作用,积压最终可以消费掉,正常情况
*** 2.消费者出问题
消费者出问题情况:
1. 消费者宕机
2. 数据库变慢
3. 第三方接口超时
4. 消费代码出现异常
5. 某条消息反复重试
6. 消费者线程池满了
解决方案: 解决故障问题,提升消费能力
1. 增加消费实例
2. 增加消费线程
3. 增加MQ服务器的消费者并发度
** 消费失败
消费失败: 消费者拿到了消息,但业务没有成功执行

解决方案: 重试机制,每次重试间隔时间更长,重试次数到第一次后,直接ack确认
1. 第一次消费失败
2. 1秒后,第二次重试. 第二次消费失败
3. 5秒后,第三次重试. 第三次消费失败
4. 30秒后,第四次重试. 第四次消费失败, ack确认, 进入死信队列
5. 死信队列,通过人工处理
** 顺序消息
顺序消息解决了, 消息必须按某个业务顺序被消费,不能乱.
比如:
1. 创建订单
2. 支付成功
3. 发货
*** 为什么MQ会乱序?
为了提高吞吐量,MQ会有多个分区/队列+多个消费者并行处理.虽然发送顺序是A先B后,但可能完成顺序是B先A后.
*** 怎么保证顺序?
把需要保证顺序的消息,放到同一个队列/分区,并且由同一条消费链路串行处理.

局部有序: 比如不要求所有消息按时间顺序,只要求相同的orderId有顺序.
*** 要求顺序消费时,第2条消息失败了,第3条怎么办?
1. 阻塞+重试: 缺点坏消息可能堵塞整个队列
   2失败后,不继续处理后面的3.而是重试2,让2成功.
2. 有限重试->DLQ(死信队列)
   支付失败后,重试3次.如果还是失败,就放入死信队列.继续执行后面的消息.
   但是支持失败了,显然是不能发货的. 所以消费发货时, 要去查询订单状态是否是支付的,才能发货.
   不能完全依赖MQ,去保证业务的完整性.
3. 补偿机制: 达到最终一致性
   比如: 创建订单成功,扣款成功,增加积分(失败)
   可以先记录积分失败,然后定期扫描失败记录,重新执行积分操作
