* Java
** 集合
*** HashMap
HashMap: 通过key计算位置,快速找到Value
树化条件: 链表长度>=8 && 数组长度>=64
扩容条件: 全局大小超过阈值(数组长度*负载因子)

**** 1.hash冲突
不同Key可能得到相同的数组下标,产生Hash冲突,使用链表保存冲突的数据

**** 2.红黑树
同一个链表的大小太大时,查询的时间复杂度是O(n),树化降低时间复杂度为O(lgN)

树化条件: 链表长度>=8 && 数组长度>=64

不急于树化: 先扩容数组,让元素分散开

**** 3.扩容
put时,map的全局大小超过阈值(数组长度*负载因子),则发生扩容. 扩容为原来的两倍

**** 4.put
1. 根据key计算hash,再根据hash计算数组下标
2. 桶是否为空
   1. 是,直接放入
   2. 否,比较key
      1. key相同->覆盖value
      2. key不同->链表/红黑树中插入.链表过长则先判断树化条件,不满足则判断是否扩容
	 
*** concurrentHashMap
对比HashMap: 并发环境下适合使用

**** ConcurrentHashMap数据结构
数组+链表+红黑树

**** ConcurrentHashMap.put
put操作桶的两种情况处理: 
1. 桶是空的
   通过CAS把值放进去(如果这个位置是空的,就把A放进去)
   1. 成功
   2. 失败,则重新put
2. 桶已经有数据
   使用synchronized锁住桶的头节点A,等修改完成后再释放锁

关键点: 这里CAS和缩的颗粒度是桶,而不是整个Map.假如线程A和B在修改不同的桶时,两者没有锁竞争.

****  ConcurrentHashMap.get
get操作不加锁,通过volatile保持桶的可见性

*** ArrayList 1


*** CopyOnWriteArrayList
底层数组
读操作: 直接读取,不加锁,读很快
写操作:
- 加锁
- 复制旧数组,在新数组上修改
- 替换array引用
- volatile可见性,后续读取看到新数组


*** HashSet
为什么自定义对象经常要重写equals和hashCode?
如果只重写equals,比如o1.equals(o2)是true,但是两者的hash不一样.会导致两个对象分配到的桶不一样.
所以,如果equals()返回true,那么两个对象的hashCode()必须相同

** 并发

*** synchronized
synchronized:
- Java的内置互斥锁
- 同一把锁,同一时刻只有一个线程能进入synchronized保护的代码

**** synchronized锁的到底是什么?
#+begin_src java
  // synchronized锁的是对象
  // 锁的是lock对象
  synchronized (lock) {
  		doSomething();
  		}
  // 锁的是this对象
  synchronized void test() {
  		}
  // 锁的是这个Class对象
  static synchronized void test() {
  		}

#+end_src

**** synchronized如何保证线程安全?
synchronized三个特性:
1. 互斥: 不会被同时修改共享数据
2. 可见性: 由于对一个锁的unlock happens-before 后续对这个锁的lock.所以A释放锁之前的修改,对于获取锁的B是可见的.
3. 有序性: 对一个锁的unlock happens-before 后续对这个锁的lock.

**** synchronized可重入
同一线程可以多次获取同一把锁,每次进入锁,count+1,每次退出锁,count-1.最后count为0时,才真正释放锁.

#+begin_src java
  synchronized void a() {
  		b()
  									}
  synchronized void b() {}
  // 这里a和b都锁this,线程进入a获取this的锁,后面调用b(),又获取this.
  // 可以重复获取同一把锁
#+end_src

*** volatile
volatile保证可见性和一定的有序性,但不保证复合操作的原子性

**** 为什么需要volatile
一个变量,在主线程~线程A和线程B上有内存,在线程A修改了该变量的值,线程B不一定能看到.
使用volatile后,线程A修改了该值,线程B马上能看到

**** volatile不等于synchronized
线程A和线程B同时执行count++. count=10,线程A先读取10,计算11,再写入11.线程B先读取10,计算11,也再写入11.

**** volatile禁止特定的指令重排序
#+begin_src java
  int a = 0;
  volatile boolean ready = false;

  class ThreadA{
  void run() {
  				// 这里a的指令会先于ready的指令
	a=10;
	ready = true;
  }
  }
  class ThreadB{
  void run() {
  		if (ready) {
  				// 这里输出的是10,而不是0
	  System.out.println(a);
  		}
  }
  }
#+end_src

*** CAS(compare and swap)
CAS: 我准备修改一个值,但只有它没有改变,我才做修改
CAS的原子性: 在硬件和JVM层面实现的不可分割的原子操作

**** CAS的参数
这是一个原子操作. 如果V=E,则修改为N,否则返回false.
- V:variable 当前内存值
- E:Expected 期望是啥值
- N:New 改成啥值

**** CAS搭配自旋
CAS失败->重新读取->重新计算->再CAS
#+begin_src java
  while(true) {
  int oldV = count;
  int newV = oldV + 1;
  if(cas(count, oldV, newV)) {
	break;
  }
  }
#+end_src

AtomicInteger就是典型实现

**** CAS和synchronized的区别
synchronized悲观一点,先控制访问,再修改
CAS乐观一点,先尝试修改,冲突了再重试

*** AQS AbstractQueuedSynchronizer抽象队列同步器
AQS:
- 构建锁和同步器的基础框架
- 用state表示同步状态
- CAS修改state,抢不到的线程进入队列等待
  

**** AQS为什么存在?
实现锁需求:
1. 表示锁是否被占有: volatile
2. 多个线程抢锁,如何保证只有一个成功: CAS
3. 抢锁失败的线程放哪?
   一直自旋会非常消耗CPU,把抢锁失败的线程排队等待
   A释放后,唤醒B,B继续抢锁

**** 抢锁流程
1. 线程A尝试CAS(0->1)成功,拿到锁
2. 线程B尝试CAS(0->1)失败,进入AQS等待队列
3. 线程C尝试CAS(0->1)失败,也进入AQS等待队列
4. A执行完毕,释放锁,修改同步状态
5. 唤醒等待队列中的BC
6. B尝试获取锁...

线程park/unpack:
- 进入AQS线程后,线程park,挂起来避免一直占CPU
- 释放锁后,线程unpark,让它尝试获取锁

*** ReentrantLock
ReentrantLock是可重入的互斥锁,底层基于AQS实现

**** ReentrantLock的数据结构
#+begin_src java
  class ReentrantLock {
  		// 继承自AQS,有两个子类FairSync,UnFairSync
      Sync sync;
  }
  class AbstractQueuedSynchronizer {
  		// 同步状态
  		volatile int state;
  		// AQS等待队列
  		Node head;
  		Node tail;

  		// 独占锁的线程
  		private Thread exclusiveOwnerThread;
  }
#+end_src
**** ReentrantLock实现锁
利用AQS的state+CAS+等待队列实现锁

state: 在ReentrantLock代表重入次数,为0是表示锁未被持有,其他表示持有次数
- 每次lock,state+1
- 每次unlock,state-1
**** 公平锁和非公平锁
公平锁: 唤醒的时候,按队列顺序去唤醒
非公平锁: 唤醒的时候,不按队列顺序去唤醒
非公平锁比公平锁性能要好,是默认的.因为唤醒时,可能新来的E正好在CPU上执行,这样可以减少上下文切换成本

* Spring全家桶
* MySQL
* Redis
* MQ
* 微服务
