* MQ
** MQ为什么存在?
生产者把事情交给队列,不要求消费者立即完成. 以此换取,异步~解耦~抗流量的能力.

假设下单的业务逻辑是:
1. 用户下单
2. 增加订单
3. 扣库存
4. 发优惠券
5. 发短信
6. 记录积分
------------全部同步调用
缺点: 任何服务慢了,导致整个请求慢;任何服务挂了,影响下单
Order
  → Inventory
      → Coupon
          → SMS
              → Point
------------加入MQ
             ┌→ 库存服务
订单服务 → MQ ├→ 优惠券服务
             ├→ 短信服务
             └→ 积分服务
1. 异步: 原本需要等待下游完成,才能进行下一步,变成只发个消息
2. 解耦: 订单服务不需要关心下游,后续要增加新的下游,只需要订阅消息,不用修改订单服务
3. 削峰: 订单服务突然来了10万个请求,下游服务一秒只能处理5000个,MQ先把请求堆住,下游按自身能力慢慢消费
** 消息丢失
消息丢失: 生产者以为消息发出了,但是最终消费者没拿到
消息链路: 生产者->Broker(MQ服务器)->消费者
*** 1.生产者丢
mq.send(message)后,生产者不知道Broker到底收到没有

解决: 发送确认机制.生产者发送完之后,再向Broker确认是否成功
- RabbitMQ: Publisher Confirm
- Kafka: producer ack配置

*** 2.Broker自己丢
消息已经到MQ了,但是MQ服务内存里面的消息还未落库

解决: 消息持久化(磁盘)+副本机制. 确保即使一个Broker挂了,消息也不会丢
- 消息写入到日志文件
- 多副本
- acks=all

*** 3.消费者丢
两者模式:
- 先ack再执行业务: 执行业务过程中宕机,导致业务没执行,但是被消费了.
  1. 接受消息
  2. ack
  3. 执行业务. 
- 先执行业务再ack: 业务执行完,未ACK,导致MQ重复发送消息,消费重复
  1. 接受消息
  2. 执行业务
  3. ack
** 消费重复(保证消费幂等)
不要期望MQ只投递以此,而是让业务代码做到: 同一条消息执行多次,结果和执行一次一样.

具体解决方案:
1. 增加消费日志表,并给消息id增加唯一索引
2. 代码里面,先插入消息日志,如果报主键重复直接返回
3. 代码整体增加本地事务,确保插入消息日志和执行业务代码的原子性
