* Java
** 集合
*** HashMap
HashMap: 通过key计算位置,快速找到Value
树化条件: 链表长度>=8 && 数组长度>=64
扩容条件: 全局大小超过阈值(数组长度*负载因子)

**** 1.hash冲突
不同Key可能得到相同的数组下标,产生Hash冲突,使用链表保存冲突的数据

**** 2.红黑树
同一个链表的大小太大时,查询的时间复杂度是O(n),树化降低时间复杂度为O(lgN)

树化条件: 链表长度>=8 && 数组长度>=64

不急于树化: 先扩容数组,让元素分散开

**** 3.扩容
put时,map的全局大小超过阈值(数组长度*负载因子),则发生扩容. 扩容为原来的两倍

**** 4.put
1. 根据key计算hash,再根据hash计算数组下标
2. 桶是否为空
   1. 是,直接放入
   2. 否,比较key
      1. key相同->覆盖value
      2. key不同->链表/红黑树中插入.链表过长则先判断树化条件,不满足则判断是否扩容
	 
*** concurrentHashMap
对比HashMap: 并发环境下适合使用

**** ConcurrentHashMap数据结构
数组+链表+红黑树

**** ConcurrentHashMap.put
put操作桶的两种情况处理: 
1. 桶是空的
   通过CAS把值放进去(如果这个位置是空的,就把A放进去)
   1. 成功
   2. 失败,则重新put
2. 桶已经有数据
   使用synchronized锁住桶的头节点A,等修改完成后再释放锁

关键点: 这里CAS和缩的颗粒度是桶,而不是整个Map.假如线程A和B在修改不同的桶时,两者没有锁竞争.

****  ConcurrentHashMap.get
get操作不加锁,通过volatile保持桶的可见性

*** ArrayList 1


*** CopyOnWriteArrayList
底层数组
读操作: 直接读取,不加锁,读很快
写操作:
- 加锁
- 复制旧数组,在新数组上修改
- 替换array引用
- volatile可见性,后续读取看到新数组


*** HashSet
为什么自定义对象经常要重写equals和hashCode?
如果只重写equals,比如o1.equals(o2)是true,但是两者的hash不一样.会导致两个对象分配到的桶不一样.
所以,如果equals()返回true,那么两个对象的hashCode()必须相同

** 并发

*** synchronized
synchronized:
- Java的内置互斥锁
- 同一把锁,同一时刻只有一个线程能进入synchronized保护的代码

**** synchronized锁的到底是什么?
#+begin_src java
  // synchronized锁的是对象
  // 锁的是lock对象
  synchronized (lock) {
  		doSomething();
  		}
  // 锁的是this对象
  synchronized void test() {
  		}
  // 锁的是这个Class对象
  static synchronized void test() {
  		}

#+end_src

**** synchronized如何保证线程安全?
synchronized三个特性:
1. 互斥: 不会被同时修改共享数据
2. 可见性: 由于对一个锁的unlock happens-before 后续对这个锁的lock.所以A释放锁之前的修改,对于获取锁的B是可见的.
3. 有序性: 对一个锁的unlock happens-before 后续对这个锁的lock.

**** synchronized可重入
同一线程可以多次获取同一把锁,每次进入锁,count+1,每次退出锁,count-1.最后count为0时,才真正释放锁.

#+begin_src java
  synchronized void a() {
  		b()
  									}
  synchronized void b() {}
  // 这里a和b都锁this,线程进入a获取this的锁,后面调用b(),又获取this.
  // 可以重复获取同一把锁
#+end_src

*** volatile
volatile保证可见性和一定的有序性,但不保证复合操作的原子性

**** 为什么需要volatile
一个变量,在主线程~线程A和线程B上有内存,在线程A修改了该变量的值,线程B不一定能看到.
使用volatile后,线程A修改了该值,线程B马上能看到

**** volatile不等于synchronized
线程A和线程B同时执行count++. count=10,线程A先读取10,计算11,再写入11.线程B先读取10,计算11,也再写入11.

**** volatile禁止特定的指令重排序
#+begin_src java
  int a = 0;
  volatile boolean ready = false;

  class ThreadA{
  void run() {
  				// 这里a的指令会先于ready的指令
	a=10;
	ready = true;
  }
  }
  class ThreadB{
  void run() {
  		if (ready) {
  				// 这里输出的是10,而不是0
	  System.out.println(a);
  		}
  }
  }
#+end_src

*** CAS(compare and swap)
CAS: 我准备修改一个值,但只有它没有改变,我才做修改
CAS的原子性: 在硬件和JVM层面实现的不可分割的原子操作

**** CAS的参数
这是一个原子操作. 如果V=E,则修改为N,否则返回false.
- V:variable 当前内存值
- E:Expected 期望是啥值
- N:New 改成啥值

**** CAS搭配自旋
CAS失败->重新读取->重新计算->再CAS
#+begin_src java
  while(true) {
  int oldV = count;
  int newV = oldV + 1;
  if(cas(count, oldV, newV)) {
	break;
  }
  }
#+end_src

AtomicInteger就是典型实现

**** CAS和synchronized的区别
synchronized悲观一点,先控制访问,再修改
CAS乐观一点,先尝试修改,冲突了再重试

*** AQS AbstractQueuedSynchronizer抽象队列同步器
AQS:
- 构建锁和同步器的基础框架
- 用state表示同步状态
- CAS修改state,抢不到的线程进入队列等待
  

**** AQS为什么存在?
实现锁需求:
1. 表示锁是否被占有: volatile
2. 多个线程抢锁,如何保证只有一个成功: CAS
3. 抢锁失败的线程放哪?
   一直自旋会非常消耗CPU,把抢锁失败的线程排队等待
   A释放后,唤醒B,B继续抢锁

**** 抢锁流程
1. 线程A尝试CAS(0->1)成功,拿到锁
2. 线程B尝试CAS(0->1)失败,进入AQS等待队列
3. 线程C尝试CAS(0->1)失败,也进入AQS等待队列
4. A执行完毕,释放锁,修改同步状态
5. 唤醒等待队列中的BC
6. B尝试获取锁...

线程park/unpack:
- 进入AQS线程后,线程park,挂起来避免一直占CPU
- 释放锁后,线程unpark,让它尝试获取锁

*** ReentrantLock
ReentrantLock是可重入的互斥锁,底层基于AQS实现

**** ReentrantLock的数据结构
#+begin_src java
  class ReentrantLock {
  		// 继承自AQS,有两个子类FairSync,UnFairSync
      Sync sync;
  }
  class AbstractQueuedSynchronizer {
  		// 同步状态
  		volatile int state;
  		// AQS等待队列
  		Node head;
  		Node tail;

  		// 独占锁的线程
  		private Thread exclusiveOwnerThread;
  }
#+end_src
**** ReentrantLock实现锁
利用AQS的state+CAS+等待队列实现锁

state: 在ReentrantLock代表重入次数,为0是表示锁未被持有,其他表示持有次数
- 每次lock,state+1
- 每次unlock,state-1
**** 公平锁和非公平锁
公平锁: 唤醒的时候,按队列顺序去唤醒
非公平锁: 唤醒的时候,不按队列顺序去唤醒
非公平锁比公平锁性能要好,是默认的.因为唤醒时,可能新来的E正好在CPU上执行,这样可以减少上下文切换成本
** JVM
*** JVM内存结构
JVM内存结构: 线程共享和私有区域
- 堆(共): 存对象实例和数组
  + Young Generation
    - Eden
    - Suvivor 0
    - Suvivor 1
  + Old Generation
- 方法区(共): 存类/字段/方法信息,符号引用(System/out/println)
- 栈(私): 存局部变量和对象引用
- 本地方法栈(私): 调用C/C++实现的本地代码
- 程序计数器(私): 记录执行到哪条指令了,CPU用来做线程切换

#+begin_src java
  // user局部变量在栈中
  // new User对象存堆里
  User user = new User()
  		void test() {
  				// 局部变量在栈中
  				int a = 10;
  				// 对象引用在栈中
  				User user = new User();
  		}
#+end_src
*** 对象创建
对象创建流程:
1. 检查类加载
   类如果没有加载过,则进行加载流程
2. 分配内存:
   - 在堆中分配内存
   - 遇到并发,则线程在自己在堆里预留的空间分配
3. 内存初始化为零值
   #+begin_src java
     class User {
     		int age;
     		boolean active;
     		Object obj;
     		}
     // age = 0
     // active = false;
     // obj = null
   #+end_src
4. 设置对象头
   Mark Word
   - GC age
   - HashCode
   Class Pointer
   - 类的元数据
5. 执行构造方法: 为局部变量赋值
*** GC垃圾回收

**** GC垃圾回收-整理回收模型
1. new Object到Eden
2. Young Generation空间不足触发Young GC
3. 回收垃圾对象,存活对象进入Survivor
4. 多个Young GC, 对象一直存活则进入Old
5. Old Generation压力增加,Old GC,具体GC取决于垃圾收集器

**** GC垃圾回收-新生代
新生代=Eden+S0+S1
Young GC时,把存活对象从Eden+S0移动到S1,对象年龄+1;下一轮从Eden+S1移动到S0,对象年龄+1;循环...
比如: Eden AC存活,S0 E存活, 把ACE复制到S1中

Young=MinorGC: 发生较频繁,速度很快,可能STW

**** GC垃圾回收-进入Old
什么进入Old?
1. 年龄过大
2. Survivor空间不足,提前晋升

回收算法: 标记清除为主,标记整理的也有
Major GC: 

**** GC垃圾回收-GC Roots
四类主要GC Roots:
1. 栈中引用
2. 静态引用
3. 常量引用
4. 本地方法引用

从GC Roots出发,向下找其引用.
比如 A引用B,B引用C, C是可达的; 但是D引用E,GCRoot上没有D, D,E是不可达的. 由JVM回收
**** GC垃圾回收-垃圾回收算法
1. 标记清除: 标记垃圾然后清除
2. 标记复制: 把存活对象复制到另一块区域
3. 标记整理: 把存活对象移动到一起
**** Full GC
Full GC: 对堆进行全面垃圾回收
常见触发场景:
- 老年代空间压力大
- 晋升失败
- 大对象分配失败
- System.gc()
**** STW
STW: JVM在GC时,需要暂停Java应用线程

* Spring全家桶
* Spring Cloud
Spring Cloud组件及其作用
1. Nacos Dicovery: 服务注册~服务发现~健康检查
2. Nacos Config: 配置中心,动态配置
3. Gateway: 这个微服务系统对外的统一入口
   - 网关: 从外部到微服务系统的统一入口
   - 路由: 决定请求转发到哪个服务
   - 过滤: 对请求和响应统一处理
   - 鉴权: 通过Filter判断用户身份以及是否有访问权限
4. OpenFeign: 微服务之间的HTTP调用
5. Sentinel: 限流~熔断~降级

外部调用: Client->Gateway->Nacos->Service
内部调用: Service A -> OpenFeign -> Nacos -> Service B

* MySQL
* Redis
* MQ
RocketMQ
│
├── 为什么需要 MQ
│     ├── 异步
│     ├── 解耦
│     └── 削峰
│
├── 基本架构
│     ├── NameServer
│     ├── Broker
│     ├── Producer
│     ├── Consumer
│     ├── Topic
│     └── MessageQueue
│
├── 两条核心流程
│     │
│     ├── Broker启动
│     │      ↓
│     │   注册NameServer
│     │      ↓
│     │   上报路由 + 心跳
│     │
│     └── 消息流程
│            ↓
│        Producer
│            ↓
│       查询NameServer
│            ↓
│      选择MessageQueue
│            ↓
│          Broker
│            ↓
│         持久化
│            ↓
│         Consumer
│
├── 消息丢失
│     ├── Producer → 发送结果 + 重试
│     ├── Broker → CommitLog + 刷盘 + 副本
│     └── Consumer → 成功确认
│
├── 重复消费
│     └── 业务幂等
│
├── 消息积压
│     ├── Producer > Consumer
│     ├── 排查消费者故障
│     └── 增加消费能力 / Queue并行度
│
├── 消费失败
│     └── 重试 → 超过次数 → DLQ
│
├── 顺序消息
│     └── 相同业务Key → 同一MessageQueue → 顺序消费
│
└── 事务消息
      └── Half Message
             ↓
          本地事务
             ↓
       Commit / Rollback
             ↓
          事务回查
** RocketMQ基本组件
RocketMQ基本架构
1. Producer生产者: 发送消息的人
2. Consumer消费者: 处理消息的人
   Consumer Group: 把多个消息者当作一个组,消息可以只被一个消费者消费,而不是整组所有
3. Broker: RocketMQ核心服务器,真正负责接收~存储和投递消息
   BrokerA:
   - Queue0
   - Queue1
   BrokerB:
   - Queue2
   - Queue3
4. NameServer: RocketMQ的路由中心
   - 有哪些Broker
   - 哪些Topic在哪些Broker上
   - 相关路由信息
5. Topic: 消息的逻辑分类
6. MessageQueue: 消息队列,分布在Broker上
   一个Topic可能多个MessageQueue,提升并发能力
** RocketMQ基本架构
*** RocketMQ基本架构-Broker启动与注册
NameServer如何知道有哪些Broker?Topic在哪里?

1. Broker启动时,向NameServer注册,上报Broker/Topic等路由信息
2. Broker定期发送心跳,NameServer知道Broker是否存活
***  RocketMQ基本架构-消息生产->存储->消费
1. Producer发送消息时,从NameServer获取Topic路由.
   比如OrderTopic在BrokerA的Queue1和BrokerB的Queue2上.
2. Producer选择BrokerB的Queue2发送消息
3. BrokerB接收并持久化消息
4. Consumer订阅OrderTopic, 从BrokerB获取消息
5. 执行业务逻辑,消费成功
** 为什么需要MQ? 异步~解耦~削峰
订单服务,库存服务,优惠券服务,短信服务

MQ主要解决了三个问题: 异步~解耦和削峰
- 异步: 把不需要同步完成的业务通过消息交给消费者处理,降低接口响应时间
  如果创建订单后,要同步处理库存~优惠券...响应时间慢; 有MQ后,发送消息就可以了
- 解耦: 让生产者只负责发送消息,不依赖具体消费者
  如果没有MQ,短信服务挂了,会导致订单服务异常,影响核心业务
- 削峰: 通过MQ暂存瞬时大量消息,让消费者逐步消费,避免流量高峰打垮下游系统
  秒杀时,创建大量订单,如果下游TPS没那么强,同样会打垮下游服务

解决了这些问题的同时,也带来了新的问题
- 消息丢失
- 消息积压
- 重复消费
- 消费失败
- 顺序性
- 最终一致性
** 消息丢失
1. Producer到Broker发送过程中丢: 同步发送 或 带回调的异步发送
   失败时重试
2. Broker存储消息时丢: 把消息持久化到CommitLog
   刷盘策略:
   - 同步刷盘: 先存储消息, 成功后再告诉Producer成功.可靠性能差
   - 异步刷盘: 写入到内存缓存中,返回Producer,后台刷盘.性能好,可能丢失数据.
   副本机制:
   - 做主丛复制,这样即便一台故障,还有其他副本
3. Broker到Consumer消费过程中丢
   问题: Consumer收到消息后,告诉Broker消息处理成功.但实际执行业务时,执行失败.
   所以: Consumer先执行业务,告诉Broker执行是否成功,失败则Broker后续会发送消息重试
	有可能执行业务成功了,但是未告诉Broker成功,这时候需要做幂等处理
* 微服务
