* Java
** HashMap 1
** ConcurrentHashMap 1
*** 整体地图
ConcurrentHashMap
│
├── table：Node<K,V>[] 数组
│       │
│       ├── 空
│       │
│       ├── Node
│       │     └── Node -> Node -> Node   链表
│       │
│       └── TreeBin
│             └── TreeNode ...           红黑树
│
├── put()
│     │
│     ├── 空桶
│     │     └── CAS 插入
│     │
│     ├── 普通链表
│     │     └── synchronized(桶头节点)
│     │
│     ├── TreeBin
│     │     └── synchronized + 红黑树操作
│     │
│     └── MOVED: forwardingNode
│           └── 协助扩容
│
├── get()
│     └── 基本无锁
│
├── resize()
│     └── 多线程协作扩容
│
└── size()
      └── baseCount + CounterCell[]
*** 数据结构
#+begin_src java
  transient volatile Node<K, V>[] table;
  class Node<K, V> {
  		int hash;
  		K key;
  		V val;
  		Node<K, V> next;
  		}
#+end_src
*** 线程安全
Thread A操作桶3, Thread B操作桶5, 锁粒度到了桶级别(桶的第一个Node作为锁对象).
*** Put源码
1. put(key, value)
2. 找bucket
3. 进行操作
   1. 空桶,则CAS
   2. MOVED, 协助扩容
   3. 有数据, synchronized, 链表或红黑树
**** 空桶,则CAS,能显著提升性能
假如线程A,线程B,同时进入写入, 没有用CAS, 就发生A写入后,B写入,把A覆盖了.
实际处理是A或B先CAS,失败的,重试,会走synchronized.
**** 有数据,synchronized
假设链表里是A->B->C, 线程X写入X,线程Y写入Y. 会出现C.next=X,C.next=Y,造成最后结果是A->B->C->Y,X被覆盖掉了.
因为锁链表,所以可以多个线程同时操作不同的桶,所以性能好.
*** get无锁
因为val和next都是volatile, 读取的线程可以看到数据没有正在被修改.
同时可以确保其他线程可以看到val和next的修改.
*** 链表变红黑树
链表长度>=8, 并且table.length>=64,会树化.
当链表长度大,table.length小的时候,table会进行扩容,重新分布,链表长度会减少.
*** resize, 多线程协助扩容
线程A发现需要扩容,开始扩容; 线程B发现正在扩容,加入扩容,搬另外一部分.
*** moved, forwardingNode
forwardingNode的hash值为MOVD(-1),表示已经被搬走了.
去nextTable里面找值,这也是get能无锁的另一部分原因.
*** size
             size

              │
       ┌──────┴──────┐
       ↓             ↓
  baseCount      CounterCell[]
                     │
              ┌──────┼──────┐
              ↓      ↓      ↓
             C1     C2     C3
*** 完整设计
                   ConcurrentHashMap
                          │
                          ↓
                    Node[] table
                          │
             ┌────────────┼────────────┐
             ↓            ↓            ↓
            空桶         链表          TreeBin
             │            │              │
             ↓            ↓              ↓
            CAS       synchronized     红黑树
             │            │              │
             └────────────┼──────────────┘
                          ↓
                       put完成
                          │
                          ↓
                     addCount()
                          │
                          ↓
                     是否需要扩容
                          │
                     ┌────┴────┐
                     ↓         ↓
                    否         是
                              ↓
                         transfer()
                              │
                     ┌────────┴────────┐
                     ↓                 ↓
                 当前线程           其他线程
                     │                 │
                     └──── helpTransfer┘
                              │
                              ↓
                        ForwardingNode
                              │
                              ↓
                         新 table
** ArrayList 1
** CopyOnWriteArrayList 1
*** 数据结构
#+begin_src java
transient volatile Object[] array;
#+end_src
                    CopyOnWriteArrayList

                         array
                           │
             ┌─────────────┴─────────────┐
             ↓                           ↓
           read                         write
             │                           │
             ↓                           ↓
          不加锁                     加锁
             │                           │
             ↓                           ↓
        直接读数组                 复制数组
                                         │
                                         ↓
                                      修改副本
                                         │
                                         ↓
                                   替换 array
**** 为什么array必须volatile
当有读写线程时,array的改变,对于读线程立即可见
              Reader
                 │
       ┌─────────┼─────────┐
       ↓         ↓         ↓
      get       get       get
       │         │         │
       └─────────┼─────────┘
                 ↓
              oldArray


Writer
   ↓
lock
   ↓
copy
   ↓
modify
   ↓
publish newArray
**** 如果读线程正在读,写线程突然修改
假如oldArray是 ABCD
线程A在迭代oldArray时, oldArray被更新成新的内容ABCDE. 迭代的索引仍然和之前一致,并且会使用新数组.
** TreeMap 红黑树 1
** PriorityQueue 1
数组实现的二叉堆(逻辑是完全二叉树),默认小顶堆
*** 数据结构
Object[] queue;
        1
      /   \
     3     8
    / \
   5   7
[1, 3, 8, 5, 7]
// 父节点永远<=子节点,因此queue[0]永远是最小值
parent = (i - 1)/2
left=i*2+1
right=i*2+2
*** offer()插入
        1
       / \
      3   8
     /
    5
        1
       / \
      2   8
     / \
    5   3
*** poll()删除堆顶
        1
       / \
      3   8
     / \
    5   7
        7
       / \
      3   8
     /
    5
        3
       / \
      5   8
     /
    7
PriorityQueue
│
├── 数组
│   ├── parent = (i-1)/2
│   ├── left = 2i+1
│   └── right = 2i+2
│
├── 小顶堆
│   └── parent <= child
│
├── offer
│   └── siftUp
│
└── poll
    └── siftDown
* 并发
** synchronized
给一段代码加锁,确保这段代码同时只能一个线程执行,并保证线程之间的内存可见性.
synchronized
     │
     ├── 锁对象
     │
     ├── 互斥
     │
     ├── 可见性
     │
     ├── 可重入
     │
     └── JVM → Monitor
锁住共享资源 → 一个线程进入 → 其他线程等待 → 释放锁 → 下一个线程进入。
*** 核心原理
锁对象: this, obj, Xxx.class, 同一个Lock,才会互斥
- synchronized(obj)
- 锁实例方法=锁this
- 锁静态方法=锁Xx.class
Monitor(JVM管理对象锁谁持有,其他线程怎么办) + 锁优化
*** 三个核心特性
**** 1.互斥
同一时间,只能一个线程进入
**** 2.可见性
获取同一把锁后,线程A的修改(比如改count),会同步给线程B
**** 3.可重入
synchronized void a() {
    b();
}

synchronized void b() {
}
可以重复获取两次,然后会释放两次
** volatile
volatile告诉JVM:整个变量多线程贡献,每次读都看最新值,每次写让其他线程能看到

*** 可见性
#+begin_src java
// 这里ThreadA不会正常停止
  boolean running = true;
// 这里ThreadA会正常停止
  volatile boolean running = true;

  Thread A:
  while (running) {
  }

  Thread B:
  running = false;
#+end_src

*** 有序性
// 1. 分配内存
// 2. 初始化对象
// 3. instance指向这块内存
instance = new Singleton();
另一个线程看到instance为null,就会重复这个行为,所以不单单可以让别人看到,还会限制相关操作的乱序

*** 为什么count++无法保证
#+begin_src java
  volatile int count = 0;
  // A: 读0
  // B: 读0
  // A: +1 ->写1
  // B: +1 ->写1
  // 只能保证读写可见,但是不保证"读改写"操作不可分隔
  count++;
#+end_src

volatile
   ↓
可见性 + 有序性
   ↓
不能保证复合操作原子性


synchronized
   ↓
加锁
   ↓
互斥 + 可见性
   ↓
临界区内操作具有原子性效果

*** 总结
synchronized → 我让你们一个一个来
volatile      → 我保证你们看到最新状态

volatile
│
├── 作用
│   ├── 可见性
│   └── 有序性
│
├── 不保证
│   └── 复合操作原子性
│
├── 不是锁
│   └── 不会让其他线程阻塞等待
│
└── 底层
    └── JMM(内存模型) + 内存屏障 -> 可见性和顺序关系
** CAS
CAS = Compare And Swap
我认为变量是A,如果是,改成B;如果不是,什么都不做

*** CAS及问题
CAS自旋:实现乐观并发控制
- 读取值
- 计算新值
- CAS?
  + 成功,则结束
  + 不成功则重复
CAS的问题:
- 线程一直循环,耗CPU
- ABA问题: 虽然变量还是原来的值,但实际已经变化过,由A->B->A; 增加版本号解决
*** AtomicInteger等原子类
AtomicInteger.incrementAndGet(): 也是在CAS自旋
** AQS: AbstractQueuedSynchronizer
数据结构:
- state: 资源状态
- FIFO等待队列:
*** state
同步资源的状态,具体含义由子类定义
*** Node
#+begin_src java
  class Node {
  		// 是否等待
    volatile int waitStatus;
  		// 上个节点是
    volatile Node prev;
  		// 下个节点是
    volatile Node next;
  		// 哪个线程
    Thread waiter;
  }
#+end_src

线程
 ↓
尝试 CAS 修改 state
 ↓
成功？
 ├── 是 → 获得资源
 │
 └── 否
      ↓
   加入等待队列
      ↓
     park
      ↓
   线程睡眠
      ↓
   前面的线程释放资源
      ↓
    unpark
      ↓
   我醒了
      ↓
   再次尝试获取

             AQS
              │
     ┌────────┼────────┐
     │        │        │
    CAS     队列     park/unpark
     │        │        │
   抢资源    排队     睡眠/唤醒
*** AQS解决的问题
CAS自旋占用CPU,大量的线程进入队列休眠

公平锁
 ↓
尽量按队列来

非公平锁
 ↓
允许新来的见缝插针
** ReentrantLock 可重入锁
                 ReentrantLock
                       │
             ┌─────────┴─────────┐
             │                   │
          FairSync           NonfairSync
             │                   │
             └─────────┬─────────┘
                       ↓
                      AQS
                       │
              ┌────────┴────────┐
              │                 │
            state             等待队列
              │                 │
        表示锁的持有状态       Node → Node → Node
AQS负责抢不到如何排队,Reentrant负责锁怎么定义
#+begin_src java
  //最初,state=0
  // 第一次lock后,state=1
  lock.lock();
  a();
  // 第二次lock后,state=2
  lock.lock();
  b();
  // 第一次unlock后,state=1
  lock.unlock()
  // 第三次lock后,state=2
  lock.lock();
  c();
  // 第二次unlock后,state=1
  lock.unlock();
  // 第三次unlock后,state=0,彻底释放
  lock.unlock();
#+end_src

*** nonfairTryAcuqire 非公平锁
#+begin_src java
  final boolean nonfairTryAcuqire(int acquires) {
  		Thread current = Thread.currentThread();

  		int c = getState();
  		if (c == 0) {
	    if(compareAndSetState(0, acquires)) {
		setExclusiveOwnerThread(current);
	  	return true;
	    }
  		} else if (current = getExclusiveOwnThread()) {//这里不需要CAS
	  int next = c + acquires;

	  setState(nextc);
	  return true;
  		}

  		return false;
  }
#+end_src

                 ReentrantLock
                       │
                       ↓
                      AQS
                       │
              ┌────────┴────────┐
              │                 │
            state              队列
              │                 │
          锁的状态          等待的线程
              │                 │
              ↓                 ↓
       ┌─────────────┐     Node → Node
       │             │
    state == 0    state != 0
       │             │
      CAS        是不是自己？
       │          ↙       ↘
    成功         是         否
       │          │          │
    获得锁      state++     入队
                             ↓
                           park

*** ReentrantLock总结
ReentrantLock用AQS管理等待队列,用state记录锁的重入次数,用owner记录持有线程;
第一次靠CAS,自己重入直接增加state,别人抢不到进入AQS队列等待

** ThreadLocl
Thread
 ↓
ThreadLocalMap
 ↓
多个 Entry
 ↓
每个 Entry：
ThreadLocal → value

目的:为了线程之间某份完全隔离

场景:traceId,用于authentication, 用完后需要remove, 因为线程会复用
*** ThreadLocal.set()
#+begin_src java
  public void set(T value) {
      Thread t = Thread.currentThread();

  		// 找到整个线程自己的map
      ThreadLocalMap map = getMap(t);

      if (map != null) {
          map.set(this, value);
      } else {
          createMap(t, value);
      }
  }
#+end_src
** Atomic
                  Atomic
                     │
          ┌──────────┴──────────┐
          │                     │
     原子变量                  CAS
          │                     │
   AtomicInteger          compareAndSet
   AtomicLong                    │
   AtomicReference                ↓
                         安全地修改共享状态
AtomicInteger, AtomicLong, 就是做CAS操作,如果失败了就重试
因为有ABA的问题, 所以还有AtomicStampedReference,比较时不简单比较值,还比较版本号
** 线程池
             线程池
               │
        ┌──────┴──────┐
        │             │
      工作线程       任务队列
        │             │
   ┌────┼────┐        │
   ↓    ↓    ↓        ↓
  T1   T2   T3    Task → Task → Task
   │    │    │
   └────┴────┘
       不断取任务
*** 线程池-数据结构
ThreadPoolExecutor
│
├── Worker 集合
│     │
│     ├── Worker → Thread
│     ├── Worker → Thread
│     └── Worker → Thread
│
├── BlockingQueue
│     │
│     ├── Task
│     ├── Task
│     └── Task
│
├── corePoolSize: 最小池大小
├── maximumPoolSize: 最大池大小
└── RejectedExecutionHandler: 拒绝异常处理器
*** executor.execute(task) 执行任务
提交任务
   ↓
当前线程数 < corePoolSize？
   │
   ├── 是 → 创建核心线程执行
   │
   └── 否
        ↓
     放入任务队列
        │
        ├── 成功 → 等待线程取
        │
        └── 队列满了
              ↓
       当前线程数 < maximumPoolSize？
              │
              ├── 是 → 创建非核心线程
              │
              └── 否 → 拒绝任务
相当于一个工厂,来货了就开那几台常用机器.常用机器满了,就把货放传送带,传送带满了,就增加机器,增加机器超过厂房空间,就不接货了,货扔外面.
*** Executors.newFixedThreadPool(n) 线程池:固定n个线程
*** newSingleThreadExecutor 单线程串行执行,异步但不并发
*** newCachedThreadPool 无限个线程,来任务则创建线程
*** newScheduledThreadPool 定时执行任务
** 死锁
线程1拿到锁A,等待锁B;
线程2拿到锁B,等待锁A;
两者都不会释放,然后就一直等待.

满足条件:
- 锁只能一次被一个线程持有
- 拿到其中一个锁,等待另一个锁
- 线程2不能抢线程1的锁,只能等对方释放
- 拿锁和等待锁构成了一个循环
*** 解决方法
- 按顺序拿锁: 比如永远先锁A,再锁B. 这样会造成阻塞,线程1先拿到锁A,锁B,先执行完,线程2才能开始工作
- 超时自动释放: ReentrantLock 这样不会无限等待
** happens-before
A happens-before B: A的执行结果对B可见
例子:
- 线程A先获取锁,线程B在等待锁; 后续是A释放锁 happens-before B获取锁
- volatile 变量在线程A被修改,在线程B可见. 线程A修改变量 happens-before 线程B
传递性: A happens-before B, B happens-before C -> A happens-before C
* JVM
** JVM内存结构
                 JVM Runtime Data Areas
                         │
        ┌────────────────┴────────────────┐
        │                                 │
     线程共享                            线程私有
        │                                 │
 ┌──────┴───────┐                 ┌───────┴────────┐
 │              │                 │                │
堆 Heap     方法区 Method Area   虚拟机栈       程序计数器
 │              │                 │                │
实例          类信息             栈帧             当前指令
数组          常量              局部变量
            静态变量            操作数栈
                               方法调用
                               返回地址
                         
                              本地方法栈

HotSpot->Metaspace在方法区
*** 1.堆Heap - 对象实例,数组
- 线程共享
- 存储对象实例和数组
- GC管理这里
*** 2.虚拟机栈JVM Stack - 方法如何执行
#+begin_src java
  public void foo() {
  		int a = 10;
  		User user = new User();
  }
#+end_src
调用foo,创建栈帧. 每个线程有自己的栈
JVM Stack
    ↓
┌──────────────┐
│ foo() 栈帧    │
│              │
│ a = 10       │
│ user ────────┼──────→ 堆里的 User
│              │
└──────────────┘
栈帧里面有:
- 局部变量表
- 操作数栈
- 动态链接
- 方法返回地址
*** 3.程序计数器PC - 下一条执行什么
每个线程一个,程序计数器记录当前执行位置
*** 4.本地方法栈 - 执行native方法
*** 5.Method Area - 类的信息
类的结构信息
方法
字段信息
运行时常量池: 类名,方法名,字段名,方法描述
** 对象创建
对象创建步骤:
1. 类加载检查: 检查是否加载到方法区,没加载则加载
2. 在堆中分配对象: 刚分配出来,对实例变量做默认初始化
3. 设置对象头: !!!
4. 执行构造器
5. 返回引用, 存储到栈帧的局部变量里面
** 类加载
.class 文件
   ↓
加载 Loading
   ↓
连接 Linking
   ├── 验证
   ├── 准备
   └── 解析
   ↓
初始化 Initialization
*** 1.加载Loading
把.class文件加载到JVM,创建一个代表这个类的Class对象,建立类相关的运行时数据.
运行时信息:
User
├── 父类 Object
├── age 字段
├── eat() 方法
├── main() 方法
└── 运行时常量池
*** 2.验证Verification
字节码格式
有没有破坏JVM安全规则
类型是否正确
*** 3.准备Preparation
#+begin_src java
  class User {
  		static int count = 10;
  		static final int MAX = 100;
  }
#+end_src
给静态变量分配内存,并设置默认值(此时,count=0,而不是count=10)
*** 4.解析Resolution
User
eat
java/lang/Object
把这些符号引用,变成直接引用.也就是运行时常量池
*** 5.初始化initialization
#+begin_src java
class User {

    static int count = 10;

    static {
        System.out.println("User init");
    }
}
#+end_src
把static的变量赋值,执行static方法块
** 双亲委派
类加载器收到"加载整个类"的请求后,先不自己加载,而是先让父加载器加载;父加载器加载不了,才自己加载.

避免核心类被冒充. 比如你自己的java.lang.String类,无法冒充JDK的String
** GC
*** GC的整体回收模型
                    new Object
                        ↓
                       Eden
                        ↓
                  Eden 快满了
                        ↓
                    Young GC
                        ↓
              ┌─────────┴─────────┐
              ↓                   ↓
           垃圾对象             活对象
              ↓                   ↓
           回收掉              Survivor
                                  ↓
                            多次 Young GC
                                  ↓
                          ┌───────┴───────┐
                          ↓               ↓
                       死掉了          一直活着
                          ↓               ↓
                       回收掉            Old
                                          ↓
                                  老年代压力增加
                                          ↓
                              ┌───────────┴───────────┐
                              ↓                       ↓
                         老年代 GC                  G1
                                                      ↓
                                               并发标记
                                                      ↓
                                               Mixed GC
                                                      ↓
                                               回收 Old
*** STW
GC时,会停止所有线程. Stop the world
*** GC Root
GC Root -> main的局部变量 -> User -> Address
当对象A持有对象B, 对象B持有对象A. 但是GC Root不可达, 也要在GC时被回收掉
*** 堆
- 新生代 Young Generation
  + Eden: 标记复制
  + Survivor0: S0+Eden,标记复制到S1,然后清空
  + Survivor1:
- Old Generation: 传统是标记整理
*** Minor GC/ Major GC/ Full GC
- Minior GC: Young GC(Eden满了时进行)
  把Eden和Survivor的存活对象复制到Survivor或Old
  + STW
  + 比较快
- major GC: old GC(Old Generation快满了进行)
- Full GC: 整个堆
  对整个堆进行一次全面的垃圾回收, Young Generation(Eden+Survivor),Old Generation
  触发情况: JVM认为需要对整个堆进行一次彻底回收
  + 老年代空间不足
  + 年轻代晋升到老年代失败
  + 大对象分配内存失败
  + System.gc()被调用(不一定执行)
*** 清除方法
- 标记清除: 先标记删除,然后清除
- 标记整理: 先标记删除,再整理到一起,减少了内存碎片
- 标记复制: 先标记删除,再把活着的对象复制到Survivor
** OOM=Out of Memory(内存溢出)
1. 不断创建对象
2. 堆内存越来越慢
3. GC释放了空间
4. 继续创建对象
5. GC,但还是空间不足
6. OOM
*** 哪一块内存OOM了
- Java Heap: 堆
- Metaspace: 方法区
- Direct Memory: 堆外直接内存
** CPU飙高排查
CPU飙高如何排查?
1. 先top找到Java的PID(进程)
   top
   PID %CPU
   12345 500%
   比如%CPU=500%,表示Java进程占了5个CPU核心
2. 找出哪个线程CPU高,把线程ID转成16进制
   top -Hp 12345(Java的进程)
   PID %CPU
   12340 200%
   12351 180%
   12352 2%
   这就表示12340和12351,这两个线程有问题
3. 使用jstack找到相应的执行代码
   jstack 12345 > jstack.txt
4. CPU飙高的常见原因
   1. 死循环 while(true)
   2. 无限递归/异常重试
   3. 大量计算: 排序~JSON序列化~正则~加密~大数据量循环处理
   4. 频繁GC
** Full GC排查 先等等
* Spring全家桶
** Spring
Spring
│
├── IoC / DI
│    └── 管理对象
│
├── AOP
│    └── 在方法执行前后织入额外逻辑
│
├── Spring MVC
│    └── Web 请求处理
│
├── Spring Transaction
│    └── 事务管理
│
└── Spring Boot
     └── 快速配置和启动 Spring 应用
*** 1.IOC-Spring核心
假如OrderService需要UserService,那么我们需要手动配制 new OrderService(userService);
对象间依赖关系由程序员控制

Spring的IOC是:
告诉Spring各个Service, Spring来创建~保存对象,管理对象之间的依赖关系(注入依赖)
*** 2.DI--依赖注入
DI是IoC的具体实现方式
Spring启动时:
1. 扫描@Service
2. 创建UserService
3. 创建OrderService
4. 发现OrderService需要UserService,把UserService注入进去
*** 3.Spring容器
Spring IoC Container: ApplicationContext -> BeanFactory
里面有各类Bean
1. 各类Service: UserService~OrderService
2. 各类Dao
3. RedisTemplate,DataSource
*** 4.Bean生命周期 ???
1. 实例化
2. 依赖注入
3. 初始化
4. 使用
5. 销毁
*** 5.AOP
解决的是:很多业务需要的公共逻辑
- 日志
- 事务: 如果没有AOP就需要, 手动开始事务,业务代码,提交事务
- 权限
- 监控
- 缓存
*** 6.Spring为什么能做到AOP?
靠的是代理,真实对象被套了一层代理,在真实代码调用前后执行了这些AOP方法

代理种类:
- JDK动态代理
- CGLIB
** Bean生命周期
总体:
1. Spring创建Bean
2. 注入依赖
3. 初始化
4. 使用
5. 容器销毁时销毁Bean
*** 1.BeanDefinition
Spring启动时,扫描到@Service注解,由UserService生成BeanDefinition
BeanDefinition:
- 类型
- 作用域: 单例;每用一次一个;一个HTTP请求一个;一次Session一个
- 依赖关系
*** 2.实例化
根据BeanDefinition,new一个对象,里面还没有完成初始化
*** 3.属性注入/依赖注入
把这个对象需要的依赖也准备好
*** 4.Aware回调
Aware回调,可以让Bean获取Spring容器的信息
#+begin_src java
  public class UserService implements ApplicationContextAware {
  }
#+end_src
*** 5.BeanPostProcessor前置处理
Spring调用BeanPostProcessor前置处理,很多功能通过BeanPostProcessor扩展出来, 比如:
1. @Autowired
2. AOP
3. 其他的Bean增强

*** 6.初始化
两种常见的初始化
#+begin_src java
    @PostConstruct
    public void init() {
    }
  public class UserService implements InitializationBean {
  		@Override
  		public void afterPropertiesSet() {
  		}
  }
  @Bean(initMethod="init")
#+end_src

*** 7.BeanPostProcessor后置处理
AOP代理就是这个阶段产生的
- 代理

*** 8.Bean正式使用
*** 9.Bean销毁
@PreDestory
public void destroy() {
}
@Bean(destoryMethod="destory")
- 关闭连接
- 释放线程池
- 释放资源
** 循环依赖
A依赖B,B又依赖A时,Spring创建Bean就会形成环
*** Spring如何解决? 三级缓存
三级
“怎么拿到早期引用？” ObjectFactory,既有原始Bean,也有代理Bean早期引用获取的方法
        ↓
二级
“早期引用已经拿到了，放这里”. 到二级时,才放了原始,或代理Bean的早期引用
        ↓
一级
“Bean彻底初始化完成了，放这里”

一级：完整 Bean
二级：早期 Bean
三级：获取早期 Bean 的工厂

假如A和B相互依赖.
1. 创建A,把A放入三级缓存(ObjectFactory)
2. A需要B,这时去创建B
3. 发现B需要A,于是依次从一级~二级~三级缓存,在三级缓存找到A
4. 把A放入二级缓存,并注入到B,B完成,并放入一级缓存
5. 回到A,把B注入到A,A完成,放入一级缓存


                B需要A
                   ↓
              一级缓存？
              ↙       ↘
           有           没有
           ↓             ↓
        直接拿       二级缓存？
                     ↙       ↘
                   有         没有
                   ↓           ↓
                 直接拿      三级缓存
                                ↓
                         ObjectFactory
                                ↓
                          生成早期引用
                                ↓
                           放入二级
                                ↓
                            给 B 使用
** AOP
不修改原有业务代码,在方法执行前后织入额外逻辑

Spring并不是用原始对象执行方法,而是用代理对象执行方法

*** 横切关注点
比如一系列方法都需要日志,这就是横切关注点

*** Spring AOP的实现
- JDK动态代理: 基于接口,要求目标对象实现接口
- CGLIB: 基于继承,生成目标类的子类

*** AOP和BeanPostProcessor
执行BeanPostProcessor发现需要AOP,创建Proxy,Spring最终管理Proxy

AOP是功能,代理是实现手段,BeanPostProcessor时把代理植入Bean生命周期的扩展机制.

*** this.xxx()不触发AOP
this.xxx(),是自己调用方法,不是目标对象调用方法

@Transactional、@Cacheable、@Async
#+begin_src java
  public void a() {
  		// 这里不会触发事务,因为this.a()的对象是目标对象自己,不是代理对象
  		this.b();
  }
  @Transactional
  public void b() {
  }
#+end_src

** 事务传播
1. Required: 有事务则加入,没事务则创建
2. Requires_new: 不管有没有事务,都创建一个新事务 (记录操作日志)
3. Supports: 有事务就加入,没事务就没事务
4. Not_supported: 不使用事务
5. Mandatory: 必须有事务,否则报错

* Spring Boot
** 自动装配
SpringBoot根据项目里的依赖~配置和环境,自动创建并配置常用的Bean

SpringBoot通过Starter提供相关依赖,通过AutoConfiguration提供类路径~配置以及容器中已有Bean条件决定是否自动配置.
从而实现开箱即用,同时允许用户自定义Bean覆盖默认配置.
*** 自动装配核心例子
#+begin_src xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
#+end_src
#+begin_src java
@RestController
public class UserController {
}
#+end_src
1. 自动配置了Spring MVC
2. 自动配置了Tomcat
3. 自动创建了DispatcherServlet等Bean

*** 自动装配核心原理
1. @SpringBootApplication
2. @EnableAutoConfiguration
3. 读取SpringBoot提供的自动配置类
4. 根据@Conditional条件判断(项目环境),符合条件才创建Bean
5. 把这些Bean放入IoC容器

*** @SpingBootApplication
@SpringBootApplication约等价于:
1. @SpringBootConfiguration: 表示这是配置类
2. @EnableAutoConfiguration: 开启自动配置
3. @ComponentScan: 扫描@Component~@Service~@Controller

*** @EnableAutoConfiguration是真正的入口
Spring Boot有很多配置类:
- DataSourceAutoConfiguration
- RedisAutoConfiguration
- WebMvcAutoConfiguration
- JacksonAutoConfiguration
- TransactionAutoConfiguration
#+begin_src java
  @Configuration
  public class XxxAutoConfiguration {
  @Bean
  // 如果容器没有这个Bean,我才创建一个. 等于给了默认值,你可以覆盖默认配置
  // 所以不是所有的默认值都生效
  @ConditionalOnMissingBean
  public Xxx xxx() {
  	return new Xxx();
  }
  }
#+end_src

*** DataSource配置类
#+begin_src properties
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=123456
#+end_src
SpringBoot启动时,配置DataSource
1. DataSourceAutoConfiguration
2. 有没有DataSource?没有
3. 有没有相关数据库依赖(JDBC)?有
4. 有没有配置数据库连接信息?有
5. 创建DataSource,放入IoC容器
6. @Autowired DataSource,直接使用

*** 例子
引入Redis
1. RedisAutoConfiguration
2. 发生Redis相关类存在
3. 发现容器没有RedisTemplate,创建RedisTemplate

引入MyBatis: mybatis-boot-starter
1. MyBatisAutoConfiguration
2. 发现SqlSessionFactory不存在
3. 读取Application.yml
4. 创建SqlSessionFactory
5. 创建Mapper相关组件

*** Starter和AutoConfiguration
starter把需要的Jar包带进来

AutoConfiguration根据Jar和配置,自动创建Bean

                 SpringBoot启动
                       │
                       ↓
             @SpringBootApplication
                       │
             ┌─────────┴─────────┐
             ↓                   ↓
       ComponentScan      EnableAutoConfiguration
             ↓                   ↓
       扫描自己的代码       加载官方自动配置
                                 ↓
                         各种 @Conditional
                                 ↓
                    ┌────────────┴────────────┐
                    ↓                         ↓
                  条件满足                   条件不满足
                    ↓                         ↓
                创建 Bean                  不创建
                    ↓
                  IOC

* Spring MVC
1. HTTP请求
2. Tomcat
3. DispatcherServlet
4. HandlerMapping,找到Controller方法(HandlerMethod)
5. HandlerAdapter,参数解析
6. 调用Controller方法
7. 由HttpMessageConverter处理返回值
8. HTTP Response
** 请求处理流程-例子
http请求 GET /user/123?name=Tom
流程:
1. DispatcherServlet
2. HandlerMapping找到UserController.getUser()
3. HandlerAdpter,做参数解析,@PathVariable->123,Long,@RequestParam -> Tom,String
4. 调用 getUser(123,"Tom")
5. 返回User对象
6. 返回值处理器,HttpMessageConverter把User转成JSON(HTTP Body)
7. 最后转化成HTTP Response
* MySQL
** B+ Tree
数据库数据在磁盘上,所以数据库关心一次磁盘IO能不能拿很多数据
*** B+ Tree数据结构
                    [20 | 40]
                  /     |      \
                 /      |       \
          [5|10|15] [20|30|35] [40|50|60]
- 非叶子节点(负责导航): Key + 指针
  [20 | 40]
 /    |    \
↓     ↓     ↓
- 叶子节点: key+数据指针
[5 | 10 | 15]
[20 | 30 | 35]
[40 | 50 | 60]

叶子节点之间还有链表
[5|10|15]
    ↓
[20|30|35]
    ↓
[40|50|60]
*** 与B树的区别
B Tree: 数据可以存在所有节点
B+ Tree: 数据主要存在于叶子节点,非叶子节点主要负责索引;并且叶子节点之间还有链表
B Tree

       [20]
      /    \
   [10]    [30]
    ↓       ↓
  数据     数据
       [20]
      /    \
     ↓      ↓
 [10|15] [20|30]
    ↓       ↓
   数据    数据
*** B树为什么适合数据库
树的分叉很多,即便数据量大,树的高度也不会很高, 宽而矮
查询数据时,因为非叶子节点索引,和叶子节点范围数据,只需要访问很少的Page,从而降低磁盘IO
*** 插入数据怎么办?
没超过节点容量,在该节点增加值.
如果超过了节点容量,则该节点分裂成2个,同时修改父节点.
不断分裂,可能导致产生新Root
*** B+ Tree概览图
                 B+ Tree

                   Root
              [20 | 40 | 60]
              /    |    |    \
             ↓     ↓    ↓     ↓
         [5|10] [20|30] [40|50] [60|70]
             ↓      ↓      ↓       ↓
             └──────┴──────┴───────┘
                    叶子链表


非叶子节点：
    主要负责导航

叶子节点：
    存真正的数据/记录指针

叶子节点：
    按 Key 排序 + 链接

核心优势：
    高扇出 → 树矮 → 少磁盘 I/O
    叶子链表 → 范围查询优秀
** 聚簇索引
索引的叶子节点,存储的不是数据的地址,而是整行记录. 本质就是B+ Tree, 主键是key, 叶子节点存放完整的数据行
普通的二级索引的叶子节点存储的是: 索引列+主键值, 所以普通索引需要回表
*** 主键索引和二级索引
                主键索引
              （聚簇索引）
                   │
          ┌────────┴────────┐
          ↓                 ↓
       [10]              [20]
          ↓                 ↓
       完整数据           完整数据
       
       
        name 二级索引
              │
       ┌──────┴──────┐
       ↓             ↓
    [Jack]          [Tom]
       ↓             ↓
      id=8           id=10
                      │
                      ↓
                 回表到主键索引
                      │
                      ↓
                   完整数据
*** 为什么叫聚簇
数据记录本身按照聚簇的顺序组织在一起
一张表只有个一个聚簇索引: primary key > unique not null > rowid(隐藏)
为什么只能有一个,因为一张表只能按照一种顺序组织
** 二级索引
二级索引是一个B+ Tree, key是索引列, 叶子节点是索引列和主键
*** 为什么存主键,而不是存数据地址?
因为InnoDB的数据本身在聚簇索引里面

             聚簇索引
           （PRIMARY KEY）
                 ↓
          [id=1, 完整数据]
          [id=2, 完整数据]
          [id=3, 完整数据]
	     name 索引
                 ↓
          [Jack → id=3]
          [Tom  → id=1]
*** 按二级索引查询流程
SELECT * FROM user WHERE name = 'Tom';

回表:
name = Tom
    ↓
二级索引 B+ Tree
    ↓
找到 Tom
    ↓
得到主键 id=1
    ↓
拿 id=1 去查聚簇索引
    ↓
得到完整数据
*** 有一种情况无需回表
覆盖索引: 查询的列=索引列+主键
** 联合索引
一个索引同时包含多个字段,例如: (name, age)索引
索引的排序, 先按name排序,在name相同的情况下, 按age排序
*** 最左匹配原则
最左匹配原则: 联合索引从左往右匹配;遇到范围条件后,后面的列通常不能用于索引范围定位

各种索引情况
1. name = 'Tom', 使用索引
2. name = 'Tom' and age = 20, 使用索引
3. age = 20, 不能高效使用
4. name = 'Tom' and age > 20, 使用, 先找到Tom,在Tom这一段里面, 继续找age>20
*** 覆盖索引
当联合索引,包括所有需要的字段时,不用回表
*** 索引下推
多个判断条件,本来需要回表后再判断的条件,因为在索引里面也可以判断,提前判断,减少回表次数
** 索引失效
MySQL的B+ Tree不能快速缩小扫描范围
1. 索引列做函数或运算
   where year(creat_time)=2026
2. 不必要的隐式类型转换 字符串列和数字比较
3. 不符合联合索引最左匹配
4. Like左模糊
5. OR, 一边有索引,一边无索引
6. 表数据量太小
** explain
EXPLAIN用来查看SQL执行计划
*** Explain-type
type的值由好到差:
- const: 主键/唯一索引
- eq_ref
- ref: 普通二级索引
- range: 范围查询,因为B+可以定位一个范围
- index
- ALL: 全表扫描,导致无法有效使用索引
*** Explain-possible_keys
possible_keys: 可以被使用的索引,但是不一定被使用

*** Explain-key
key: 实际使用的key,比如possible_keys有两个,实际使用选了一个或没用

*** Explain-key_len
key_len: 使用的索引字节长度
比如a_b_c联合索引,根据key_len看索引使用了多少字节,可以判断用了联合索引哪些列

*** Explain-rows
rows: MySQL估计需要扫描/检查的记录数

*** Explain-Extra
Extra:
- Using index: 覆盖索引
- Using index condition: 索引下推
- Using where: 需要使用where过滤(可能是使用索引后,再进行where过滤)

*** Explain-recap
                    SQL
                     ↓
                  EXPLAIN
                     ↓
             查看执行计划
                     ↓
       ┌─────────────┼─────────────┐
       ↓             ↓             ↓
      type          key           rows
       ↓             ↓             ↓
怎么访问表？     用哪个索引？    扫多少？
       │             │
       ↓             ↓
 const/ref/range   联合索引？
 ALL               最左匹配？
                     │
                     ↓
                   Extra
                     ↓
       ┌─────────────┼─────────────┐
       ↓             ↓             ↓
 Using index   Using index condition  Using where
       ↓             ↓
   覆盖索引       索引下推

** MVCC
MVCC: Multi-Version Concurrency Control多版本并发控制,一个数据保存多个版本,让读和写尽量不相互堵塞

*** 为什么有MVCC?
如果事务A在修改数据,事务B在读数据.
- 没MVCC, B只能等待A修改完数据
- 有MVCC, B可以看到数据的旧版本(根据事务规则)

*** InnoDB的MVCC靠什么实现?
MVCC
 │
 ├── 隐藏字段
 │
 ├── Undo Log
 │
 └── Read View
1. Undo Log: 保存旧版本
   修改数据时,Undo Log会把历史版本数据保存,所以可以随便版本找数据
2. Read View: 决定能看到的版本
   事务A在修改数据,事务B在读数据.B看到的数据,不取决于数据库现在是什么,而是看B能看到的版本号.

*** MVCC和锁是什么关系?
普通快照读: A写, B读旧版本,互相不堵塞
For update: A写,B读, B是当前读,需要等A释放锁

** Redo Log
Redo Log: 记录"对数据的修改"(不是SQL),用于数据库崩溃后的恢复,是存储引擎层面的日志

*** 为什么需要Redo Log?
数据库真正的数据页在磁盘上,每次修改都直接去写磁盘会很慢.
InnoDb,先修改内存中Buffer Pool的数据页,然后写入到Redo Log, 最后由Redo Log慢慢写磁盘的数据页.

*** 数据库突然宕机怎么办
数据库重启,读取Redo Log, 发现之前需要恢复的修改,重新执行这些修改,恢复数据

** BinLog
Binlog: 用来记录数据库变更,主从复制,数据恢复的日志,是MySQLServer层面的日志

*** Redo Log和Binlog会不会不一致?
如果数据修改,只写了Redo Log,没写Binlog,会导致主库修改了值,从库没有
所以必须保证,两者都成功,否则不算提交

1. 第一阶段: Redo Log -> Prepare
2. 第二阶段: Binlog -> 成功 -> Redo Log -> COMMIT, 即便宕机,也能根据日志判断该事务是提交还是回滚
