* Java
** 集合
*** HashMap
HashMap: 通过key计算位置,快速找到Value
树化条件: 链表长度>=8 && 数组长度>=64
扩容条件: 全局大小超过阈值(数组长度*负载因子)

**** 1.hash冲突
不同Key可能得到相同的数组下标,产生Hash冲突,使用链表保存冲突的数据

**** 2.红黑树
同一个链表的大小太大时,查询的时间复杂度是O(n),树化降低时间复杂度为O(lgN)

树化条件: 链表长度>=8 && 数组长度>=64

不急于树化: 先扩容数组,让元素分散开

**** 3.扩容
put时,map的全局大小超过阈值(数组长度*负载因子),则发生扩容. 扩容为原来的两倍

**** 4.put
1. 根据key计算hash,再根据hash计算数组下标
2. 桶是否为空
   1. 是,直接放入
   2. 否,比较key
      1. key相同->覆盖value
      2. key不同->链表/红黑树中插入.链表过长则先判断树化条件,不满足则判断是否扩容
	 
*** concurrentHashMap
对比HashMap: 并发环境下适合使用

**** ConcurrentHashMap数据结构
数组+链表+红黑树

**** ConcurrentHashMap.put
put操作桶的两种情况处理: 
1. 桶是空的
   通过CAS把值放进去(如果这个位置是空的,就把A放进去)
   1. 成功
   2. 失败,则重新put
2. 桶已经有数据
   使用synchronized锁住桶的头节点A,等修改完成后再释放锁

关键点: 这里CAS和缩的颗粒度是桶,而不是整个Map.假如线程A和B在修改不同的桶时,两者没有锁竞争.

****  ConcurrentHashMap.get
get操作不加锁,通过volatile保持桶的可见性

*** ArrayList 1


*** CopyOnWriteArrayList
底层数组
读操作: 直接读取,不加锁,读很快
写操作:
- 加锁
- 复制旧数组,在新数组上修改
- 替换array引用
- volatile可见性,后续读取看到新数组


*** HashSet
为什么自定义对象经常要重写equals和hashCode?
如果只重写equals,比如o1.equals(o2)是true,但是两者的hash不一样.会导致两个对象分配到的桶不一样.
所以,如果equals()返回true,那么两个对象的hashCode()必须相同

** 并发

*** synchronized
synchronized:
- Java的内置互斥锁
- 同一把锁,同一时刻只有一个线程能进入synchronized保护的代码

**** synchronized锁的到底是什么?
#+begin_src java
  // synchronized锁的是对象
  // 锁的是lock对象
  synchronized (lock) {
  		doSomething();
  		}
  // 锁的是this对象
  synchronized void test() {
  		}
  // 锁的是这个Class对象
  static synchronized void test() {
  		}

#+end_src

**** synchronized如何保证线程安全?
synchronized三个特性:
1. 互斥: 不会被同时修改共享数据
2. 可见性: 由于对一个锁的unlock happens-before 后续对这个锁的lock.所以A释放锁之前的修改,对于获取锁的B是可见的.
3. 有序性: 对一个锁的unlock happens-before 后续对这个锁的lock.

**** synchronized可重入
同一线程可以多次获取同一把锁,每次进入锁,count+1,每次退出锁,count-1.最后count为0时,才真正释放锁.

#+begin_src java
  synchronized void a() {
  		b()
  									}
  synchronized void b() {}
  // 这里a和b都锁this,线程进入a获取this的锁,后面调用b(),又获取this.
  // 可以重复获取同一把锁
#+end_src

*** volatile
volatile保证可见性和一定的有序性,但不保证复合操作的原子性

**** 为什么需要

* Spring全家桶
* MySQL
* Redis
* MQ
* 微服务
