#+OPTIONS: \n:t num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Preparing for sleep with mindfulness
Falling asleep is about non-doing, so you're putting in an effrot to sleep, which is the opposite.

Tips:
- A regular time to go to bed and to wake up.
- Avoid watching television or computer before bed.
- meditation or naturally stretch like cats
- mindful walking indoors
- When you lie in bed, feel the in-breath and the out-breath.
  Rather than trying to sleep, just be with the breathing.
  Count your out-breaths from one to ten.
  Each time you breathe out, say the number to yourself.
  Every time your mind wanders off, begin again at one.
- If you’re lying in bed worrying, perhaps even about getting to sleep, accept your worries.
  Challenging or fighting thoughts just makes them more powerful.
  Note them, and gently come back to the feeling of the breath.

If you seem to be sleeping less than usual, try not to worry about it too much.
In fact, worrying about how little sleep you’re getting becomes a vicious circle.
Many people sleep far less than eight hours a day and most people have bad nights once in a while.
Not being able to sleep doesn’t mean something is wrong with you
  and lack of sleep is not the worst thing for your health.
  
* Using Mindfulness at Work
** Beginning the day mindfully
Walking meditation on your way

** Dropping in with mini meditations
From automatic pilot mode to mindful awareness mode.

Breathing space meditation: 3 stages
1. Become aware of your thoughts, emotions and bodily sensations.
2. Become aware of your own breathing.
3. Expand your awareness to the breath and the body as a whole.
When? How? Where?
- When: at set times or between activities. or you feel you need
- How: say in then breathn in, out then breath out.
  count from one to ten, cycle it.
- Where: A pure color background without any information

** Going from reacting to responding
A reaction is automatic thoughts, speech and behaviour to stimulus, like your boss criticising you.
A response is a more considered, balanced choice, often creative in reply to criticism,
  and leads to solving your problems rather than compounding them.

Sit on your chair, gaze downwards and begin to feel the sensations of your breath.
Notice if you’re breathing in a shallow or rapid way, due to your frustration,
  but try not to judge yourself.
Expand your awareness to a sense of your body as a whole.
Become mindful of the processes taking place inside you.
Feel the burning anger rising from the pit of your stomach up through your chest and throat,
  or the racing heart and dry mouth when you’re nervous.
Honour the feeling instead of criticising or blocking the emotion.
Experiment. Notice what happens if you don’t react as you normally do or feel like.
Try breathing into the feeling.
Bring kindness and curiosity to your emotions.

You may discover that
  the very act of being aware of your reaction changes the flavour of the sensation altogether.
Your relationship to the reaction changes an outburst, for example, to a more considered response.
Your tone of voice may subtly change from aggressive and demanding to being calmer and inquisitive.
The point is not to try and change anything,
  but just to sit back and watch what’s going on for a few moments.
To help you to bring a sense of curiosity when you’re about to react to a situation at work,
  try asking yourself the following questions slowly,
    one at a time, and giving yourself time for reflection:

- What feeling am I experiencing at the moment, here at work?
  How familiar is this feeling?
  Where do I feel the feeling in my body?
- What thoughts are passing through my mind at the moment?
  How judgemental are my thoughts?
  How understanding are my thoughts?
  How are my thoughts affecting my actions at work?
- How does my body feel at the moment?
  How tired do I feel at work?
  What effect has the recent level of work had on my body?
  How much discomfort can I feel at the moment in my body, and where is the source of it?
- Can I acknowledge my experiences here at work, just as they are?
  Am I able to respect my own rights as well as responsibilities in the actions I choose?
  What would be a wise way of responding right now, instead of my usual reaction?
  If I do react, can I acknowledge that I’m not perfect,
    and make my next decision a more mindful response?
    
Perhaps you’d go back to your manager and calmly explain why you feel frustrated.
You may become angry too, if you feel this is necessary, but without feeling out of control.
Perhaps you’d choose not to say anything today,
  but wait for things to settle before discussing the next step.
The idea is for you to be more creative in your response to this frustration
    rather than reacting in your usual way,
  if your usual way is unhelpful and leads to further problems.
  
The benefits of a considered, balanced response as opposed to an automatic reaction include:

- Lower levels of blood pressure, a cause of heart disease.
- Lower levels of stress hormones in your blood stream, leading to a healthier immune system.
- Improved relationships because you’re less likely
    to break down communication between colleagues if you’re in a calmer state of mind.
- A greater feeling of being in control,
    because you’re able to choose how you respond to others
      rather than automatically reacting involuntarily.
