* task3 课前作业
家庭作业:
材料: "The Best ..."
1. 读懂本文(单词+语法+习惯用法)
2. 摘抄习惯用法+句型
3. 跟读50遍(计数)
4. tell the story(可汉语)
5. 英语长难句,native speaker是否使用in dayly life
6. 收集疑惑

** material
Let Him Go, Olivia
Alejandro Arbide, San Antonio, Texas

There I was.
Upside down inside the swimming pool. Drowned.
My parents were screaming.
It must have been the summer of ’63.
It was a gloomy day.
Every Sunday we went to my grandparents’ house.
My cousins and I were playing alongside the pool.
I must have slipped.
At three years old, I did not know how to swim.
My mother was giving me CPR.
More than twenty or twenty-five minutes had gone by.
The ambulance had arrived.
Everybody was staring at my mother.
“Let him go, Olivia.It's over.”
Even my father had some feelings of resignation.
Yet, she never gave up.
I write this story as a tribute to my mother, who, only four years later, passed away.
And also in recognition of editors
	who made it possible for my mother to have read in Reader’s Digest the miracle
		made by another woman utilizing
	then recently discovered CPR.
