* task4: з≤ЊеРђ+з≤Њиѓї
жЙАвљ§зі†жЭРпЉЪ
еЙСйЫЕ16 зђђвЉАе•ЧзЬЯйҐШеРђвЉТзђђвЉАйҐШ
1. еЕИеРђвљВзЂ†пЉИвЉАеЃЪдЄНи¶БеЕИйШЕиѓїеРђвЉТиДЪжЬђпЉЙпЉМз≠ФйҐШпЉМиЃ∞ељХеѓєйФЩ
2. иЃ§зЬЯйШЕиѓїеРђвЉТиДЪжЬђпЉМж†Зж≥®жЙАжЬЙвљ£иѓНпЉИвљВдЄ≠еРЂдєЙпЉЙпЉМиѓ≠ж≥ХпЉИеПВиАГжЦ∞ж¶ВењµиЛ±иѓ≠еПКдЄЙжЬђиѓ≠ж≥Хдє¶пЉЙпЉМжСШжКДдє†жГѓвљ§ж≥ХпЉИеєґйА†еП•пЉЙ
3. еПНе§НиЈЯиѓїedgeжИЦеРђвЉТвЊ≥йҐСпЉМвљЖйЬАзЖЯиѓїжИРиѓµпЉМдљЖиѓЈиЈЯиѓїеИ∞вЊЬе§Яй°Ї
зХЕгАВжЛњдЄНеЗЖе∞±иЈЯиѓї50йБНгАВ
4. ж®°жЛЯиАГиѓХпЉМеРђвљВзЂ†пЉМз≠ФйҐШпЉМиЃ∞ељХеѓєйФЩгАВ
5. еѓєвљР1&4 з≠ФйҐШжГЕеЖµ
6. еБЪеЃМеЙН5ж≠•пЉМиѓЈжАЭиАГеєґеЖЩдЄЛпЉМгАРйШЕиѓїдЄОеРђвЉТгАСзЪДеЕ≥з≥їгАВ
** зЦСйЧЃ
1. зЯ•йБУжДПжАЭзЪДдє†жГѓзФ®ж≥Хи¶БдЄНи¶БжКД?
2. жСШжКДзЪДдє†жГѓзФ®ж≥Хе§™е§Ъ,йА†еП•е§™иАЧжЧґйЧідЇЖ,жАОдєИиІ£еЖ≥?
** дЄАиАГ
1. - 
	 F
2. tower
	 T
3. car
	 T
4. animals
	 T
5. bridge
	 T
6. 
	 F
7. delined
	 F
8.
	 F
9. Fradstone
	 T
10. ideas
		F
** Article
1: Hello. ChildrenвАЩs Engineering Workshops.

2: Oh hello.
I wanted some information about the workshops in the school holidays.

1: Sure.

2: I have two daughters who are interested.
The younger oneвАЩs Lydia, sheвАЩs four
вАУ do you take children as young as that?

1: Yes, our Tiny Engineers workshop is for four to five-year-olds.

2: What sorts of activities do they do?

1: All sorts.
For example, they work together to design a special cover that goes round an egg,
	so that when itвАЩs inside they can drop it from a height and it doesnвАЩt break.
Well, sometimes it does break
	but thatвАЩs part of the fun!

2: Right. And Lydia loves building things.
Is there any opportunity for her to do that?

1: Well, they have a competition to see who can make the highest tower.
YouвАЩd be amazed how high they can go.

2: Right.

1: But theyвАЩre learning all the time as well as having fun.
For example, one thing they do is to design and build a car thatвАЩs attached to a balloon,
	and the force of the air in that actually powers the car
	and makes it move along.
They go really fast too.

2: OK, well, all this sounds perfect.

2: Now Carly, thatвАЩs my older daughter,
		has just had her seventh birthday,
	so presumably sheвАЩd be in a different group?

1: Yes, sheвАЩd be in the Junior Engineers.
ThatвАЩs for children from six to eight.

2: And do they do the same sorts of activities?

1: Some are the same, but a bit more advanced.
So they work out how to build model vehicles, things like cars and trucks,
	but also how to construct animals using the same sorts of material and technique,
	and then they learn how they can program them and make them move.

2: So they learn a bit of coding?

1: They do.
They pick it up really quickly.
WeвАЩre there to help if they need it, but they learn from one another too.

2: Right. And do they have competitions too?

1: Yes, with the Junior Engineers,
	itвАЩs to use recycled materials like card and wood to build a bridge,
		and the longest one gets a prize.

2: That sounds fun.
I wouldnвАЩt mind doing that myself!

1: Then they have something a bit different,
	this is from Laokaoya website,
	which is to think up an idea for a five-minute movie and then film it,
	using special animation software.
YouвАЩd be amazed what they come up with.

2: And of course, thatвАЩs something they can put on their phone
	and take home to show all their friends.

1: Exactly.
And then they also build a robot in the shape of a human,
	and they decorate it
	and program it
		so that it can move its arms and legs.

2: Perfect.
	So, is it the same price as the Tiny Engineers?

1: ItвАЩs just a bit more: ¬£50 for the five weeks

2: And are the classes on a Monday, too?

1: They used to be,
	but we found it didnвАЩt give our staff enough time to clear up after the first workshop,
	so we moved them to Wednesdays.
The classes are held in the morning from ten to eleven.

2: OK. ThatвАЩs better for me actually.
And what about the location?
Where exactly are the workshops held?

1: TheyвАЩre in building 10A вАУ thereвАЩs a big sign on the door,
	you canвАЩt miss it,
	and thatвАЩs in Fradstone Industrial Estate.

2: Sorry?

1: Fradstone вАУ thatвАЩs F-R-A-D-S-T-O-N-E

2: And thatвАЩs in Grasford, isnвАЩt it?

1: Yes, up past the station.

2: And will I have any parking problems there?

1: No, thereвАЩs always plenty available.
So would you like to enrol Lydia and Carly now?

2: OK

1: So can I have your full name вА¶

** еНХиѓНйА†еП•жМЗеНЧ
- зљС:v.+v.еПШеМЦ жГЕжАБеК®иѓН+жЧґжАБзЪДиљђеПШ
- еЫЫеП•еЮЛиљђжНҐ
- жЦєеЉП/еЬ∞зВє/жЧґйЧі
- зїУеРИеЕґдїЦдє†жГѓзФ®ж≥Х
- еЕґдїЦеНХиѓН+иѓНжАІзїДеРИ
- еОЯжЦЗжСШжКД+еПШ

** words
- workshop: a room or building where tools and machines are used for making or repairing things
	1. What kinds of activities do the Chilren Engineering workshop have?
	2. How long did they clear up after the first workshop?
	3. What do you think of the activity after the first workshop?
- enrol: to officially arrange to join a school, university, or course, or to arrange for someone else to do this
	1. Harvard refused to enroll Jackie Ma ten times.
	2. He is ready to enroll his son.
	3. I enrolled the course of IELTS 10 days ago.

** expression
- what sorts of ...?
	1. What sorts of foods do they provide us?
	2. What sorts of cats are in the area?
	3. What sorts of temples are located in Mountain Feilai.
- work together to do sth.
	1. The team worked together to defeat EDG during a Lol race.
	2. The internet makes it possible for us to work together to achieve our goals.
	3. The search party worked together to reveal the secret.
- part of the fun
	1. Is that part of the fun?
	2. Why is that part of the fun?
	3. What is part of the fun?
- love doing
	1. I love swimming.
	2. I love swimming in the sea.
	3. My wife love watching the Korean drama on weekends.
- all the time
	1. He is sitting on the chair all the time.
	2. He was sitting on the chair all the time yesterday.
	3. He is complaining about Rachel all the time.
- be to do
	1. I'm to go to the temple.
	2. She's to propose to Chandler this night.
	3. I'm to enroll my daughter myself.
- be attached to sth
	1. The car is attached to balloon.
	2. The woman is staring at a cat that is attached to the tree.
	3. There is an ugly horse that is attached to the car.
- from six to eight
	1. The children from six to eight often take part in the junior engineers.
	2. The children from six to eight usually don't know how to swim.
	3. The children from six to eight is often dangerous to walk alongside swimming pool alone.
- work out
	1. They work out how to achieve their goals and they do it.
	2. Reading the paper makes it possible for Mr. Leo to work out how to teach his students efficiently.
	3. They has worked out how to spend their holidays.
- pick it up
	1. Will we pick it up quickly?
	2. What will we pick up quickly?
	3. How will we pick it up?
- mind doing
	1. He can't mind kicking his wife's ass.
	2. Would you mind opening the door?
	3. He wouldn't mind giving strangers a lift.
- think up
	1. The activity is to think up an idea for taking care of a cat and then play with it.
	2. She thinks up an idea for swimming on a Sunday.
	3. She thinks up an idea for climbing on a Sunday so that her husband could lose his weight.
- come up with
	1. She came up with an idea for enrolling herself.
	2. She comes up with an idea for travelling herself.
	3. You must come up with some ideas for repairing the bike.
- the shape of a human
	1. They also build a robot in the shape of cat.
	2. They are building a robot in the shape of cat.
	3. They have built a robot in the shape of cat.
- clear up
	1. It goes wrong, for the reason that the data wasn't cleared up.
	2. I don't mind clearing it up.
	3. Monica must have cleared it up before she cooked.
- move sth. to st.
	1. Mr. Leo moved reading to morning.
	2. Why did Mr. Leo move reading to afternoon?
	3. It must have given the staff enough time to clear up after the boss moves workshop to Wednesdays.
- up past the sp.
	1. The hospital is just up past the station.
	2. My wife wish that she knew the hospital is just up past the station.
	3. Why is the workshop up past the station.

** grammar
- in/at/on + жЧґйЧі
- who...еЃЪиѓ≠
- who ...еЃЊдїО
- as ... as
- so that
- as ... еГП
- how to
- would be
- how high they can go
- has done

