* Thinking in English

** sherwin
Why should I think in English?
Thinking in English a key point
	to move from being intermediate to upper-intermediate, advanced and native speaker level.

daily routine:
	1. reading time everyday
		 - repeat after audios
		 - review
	2. while leaving home until arriving at work
		 - watch English books
	3. spare time at work
		 - finish red cover books
		 - write essays
		 - read actively or just for fun
		 - review
	4. spare time while waitting a bus and so on
		 - read books
		 - watch dramas, movies
		 - describe something around you in English
		 - publish moment
	5. golden time
		 - learn NCE course
		 - learn intensive course
		 - talk to foreigner teachers
	6. short time before sleeping
		 - watch youtube, read book and so on
do as best as you:
	1. Don't use Chinese in short time before sleeping
	2. Do fun stuff in English as much as possible
	3. learn new concept in English straightaway
	4. stop translating while learning new concepts
		 - just google the new concept and go to images without translating it while learning it
	5. switch everything around you in English as possible as you can

** Leo
精读：上nce课；造句； 红皮书；重复间隔；
精听：跟读；nce电影片段
泛读：不求甚解地看书； 带着问题去找答案地看书；
泛听：电影；电视剧；广播；音乐；
写作：随意写点东西，比如朋友圈发点英文想法；以某个主题去搞素材，形成论证，比如雅思作文和topic For Disscussion.
口语：沉浸对话课程；对周边事物尝试用英语描述；hellotalk找母语者对话

我把这些事情分了什么时间做，以及按顺序排优先级（实在不想干某个事就换一下）。
工作划水时间：
       红皮书补全；作文写作；带问题泛读；重复间隔；不求甚解泛读

黄金时间（晚餐后直到休息前）：
      上nce；沉浸对话课程；hellotalk找外教

早中晚跟读时间：
       跟读；重复间隔

碎片时间：
       听美剧、看电影、电视剧；时不时用英语描述周边事物；发朋友圈

** linguamarina
So, thinking in English is a key thing for you
	to move *from being intermediate to upper-intermediate, advanced and native speaker level*.

I went to bed thinking in English, and I had a dream in English,
	and I woke up in the morning, and I realized I'm actually thinking in English.

rules for keeping thinking in English:
	1. travel to an English-speaking country.
	2. From now on I will only do fun stuff in English. YouTube video, Instagram, English books.
	3. learn the concept in English straightaway
	4. When you're learning a new concept you get rid of translation.
		 1. if you want to read more about photography or if you want to read more about filmmaking,
					blogging, do that in English.
		 2. if you encounter a new concept, you just Google it, you go to images,
					 and you read what that word means without translating it.
	5. Switch your phone, your smartphone, your laptop, to English.

