#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 1 A private conversation
#+begin_verse
Why did the writer complain to the people behind him?

Last week I *went to the theatre*.
I *had a very good seat*.
The play was very interesting.

I did not enjoy it.
A young man and a young woman were sitting behind me.
They were talking loudly.

I *got very angry*.
I could not hear the actors.
I turned round.
I looked at the man and the woman angrily.
They did not pay any attention.

*In the end*, I could not bear it.
I turned round again.
'I can't hear a word!' I said angrily.
'*It's none of your business*,' the young man said rudely. 'This is a private conversation.'
#+end_verse
** expression
private [ˈpraɪvət] adj.私人的
conversation [ˌkɒnvəˈseɪʃ(ə)n] n.谈话
theatre [ˈθɪətə(r)] n.戏院
seat [siːt] n.座位
play [pleɪ] n.戏
loudly [ˈlaʊdli] n.大声地
angry [ˈæŋɡri] adj.生气的
angrily [ˈæŋɡrəli] adv.生气地
attention [əˈtenʃ(ə)n] n.注意
bear [beə(r)] v.容忍
business [ˈbɪznəs] n.事
rudely [ˈruːdli] adv.粗鲁地

have a conversation: 谈话
take a seat: 坐座位
Is the seat taken?: 这个位置被坐了吗
How can you bear that?: 你怎么忍受那个的?
Don't be rude: 别粗鲁
--------------------
6123456:
	 6: When
	 1: 主
	 2: 谓/系
	 3: 宾/表
	 4: how
	 5: where
	 6: when
give me that book VS give it to me
1. 如何造一个英语句子: 123 
2. 如何造一个好的英文句子: 123456
3. 英语语序

go to the theatre: 去看戏
have a good seat: 有好座位
get angry: 变得生气
turn round: 转身
pay attention: 注意
in the end: 最终
couldn't bear it: 忍不了了
It's none of your business: 与你无关


** 单词造句
private adj.
- She goes to a private hospital.
- Why does she go to a private hospital?
- Don't go to a private hospital. It's dangerous!
- When did she go to a private hospital!
- She goes to a private hospital by bus.
conversation n.
- I had a conversation with her yesterday.
- This is a private conversation.
- How did you have a conversation with her?
- Why did you have a conversation with her yesterday?
- Where did you have a conversation with her yesterday?
theatre n.
- I've been to that theatre.
- He has never been to that theatre.
- Let's go to the theatre.
- How do we go to the theatre?
- When do we go to the theatre?
seat n.
- I have a good seat at home.
- Why did you have a good seat?
- Is the seat taken?
- I taked a seat in bedroom.
- Why do you take a seat now?
play n.
- It's interesting to watch a play.
- I'm watching a play with her.
- When did you watch a play?
- How did you watch a play?
- Why do you watch a play?
** 反复听电影片段
** Pattern Drill 写+读
-
		1T: walk - across the stage - show
		S1: How did she walk across the stage?
		S2: She walked very slowly across the stage.
	 - Behave - at the theatre - rude/bad
		 How did she behave at the theatre?
		 She behaved very rudely at the theatre?
	 - drive - through the park - quick/slow
		 How did she drive through the park?
		 She drived very slowly through the park.
	 - sleep - on the train - sound/quite
		 How did he sleep on the train?
		 He slept very quitely on the train.
	 - listen - to his story - patient/ careful
		 How did she listen to his story?
		 She listened carefully to his story.
-
		2T: hear the radio
		S1: I can hear the radio now. Can you?
		S2: Of course I can. I can hear it perfectly well.
	 - hear the actors
		 I can hear the actors now. Can you?
		 Of course I can. I can hear them perfectly well.
	 - see those men
		 I can see those men now. Can you?
		 Of course I can. I can see them perfectly well.
	 - see the theatre
		 I can see the theatre now. Can you?
		 Of course I can. I can see it perfectly well.
	 - see the police
		 I can see the policeman now. Can you?
		 Of course I can. I can see him perfectly well.
-
		3T: last night - a good talk on the radio - saw/heard
		S: I heard a good talk on the radio last night.
	 - just now - a voice/knock - at the door
		 I heard a knock at the door just now.
	 - last night - a cry/shout - outside
		 I heard a cry outside last night.
	 - at lunch - a fly/hair - in my soup
		 I saw a hair in my soup at lunch.
	 - last night - a camel/monkey - at the zoo.
		 I saw a camel at the zoo last week.
-
		4T: see the race - large - crowd
		S1: Didn't you see the race?
		S2: I couldn't. The crowd was too large.
	 - read the letter - small/bad - writing
		 Didn't you read the letter?
		 I couldn't. The writing was too small.
	 - see her face - poor/bad - light
		 Didn't you see her face?
		 I couldn't. The light was too poor.
	 - swim in the lake - could/deep - water.
		 Didn't you swim in the lake?
		 I couldn't. The water was too deep.
	 - finish your lunch - hot/salty - food
		 Didn't you finish your lunch?
		 I couldn't. The food was too salty.
** 给自己讲解
** 红皮书
** 习惯用法造句
go to the theatre
- I went to the theatre on Saturday.
- Did you go to the theatre on Saturday?
- Who went to the theatre on Saturday?
- When did you go to the theatre?
- How did you go to the theatre on Saturday?
have a good seat
- I had a good seat yesterday.
- Did you have a good seat yesterday?
- Who have a good seat yesterday?
- When did you have a good seat?
- How did you have a good seat?
get angry
- I got very angry yesterday.
- Why did you get angry yesterday?
- When did you got angry?
- Where did you get very angry?
- Did you get very angry yesterday.
turn round
- He always turns round in the class.
- Who always turns round in the class?
- How often does he turn round in the class?
- Why does he always turn round in the class?
- Where does he always turn round?
pay attention
- They did not pay any attention.
- Did they pay a attention?
- Why didn't they pay any attention?
- Who did not pay any attention?
- When did not they pay any attention?
in the end
- In the end, my mom and me went to the theatre.
- Did your mom and you go to the theatre in the end?
- Why did your mom and you go to the theatre in the end?
- Where did your mom and you go in the end?
- How did your mom and you go to the theatre in the end?
couldn't bear it
- I couldn't bear it.
- How could you bear it?
- Why could you bear it?
- Who could bear it?
- When couldn't you bear it?
It's none of your business
-
-
-
-
-
** 跟读至背诵
** Ask me if 写+读
1. I went to the theatre last week. When
	 When did you go to the theatre?
2. I had a good seat. What kind of
		What kind of seat did you have?
3. I saw an interesting play. What
		What did you see?
4. A young man and a young woman was sitting behind me. Who/When
		Who was sitting behind you?
		When was the young man and the young woman sitting?
5. They were talking loudly. How
		How were they talking?
6. I couldn't hear the actors. Who
	 Who couldn't hear the actors?
7. I turned round. What ... do
	 What did you do?
8. I looked at the man and the young woman angrily. How
	 How did you look at the man and the young woman?
** 摘要写作
The writer went to the theatre last week.
He did not enjoy the play.
A young man and a young woman were sitting behind me.
They were talking loudly, he couldn't hear the actors.
He turned around, and said "I can't hear a word".
The young man said "This is a private conversation".
** tell the story 口语
** Topics for discussion
- When did you last go to the theatre/cinema? Tell me about the play/film.
	 I last went to the cinema about two months ago when I was wanderring in the mall.
	 Suddenly it occurred to me that it's been a long time I haven't watched a movie with my wife.
	 It happened that there was a movie directed by Gong Qijun,
		who made several famous animated movies.
	 Of course, this was his another animated movie.
	 A boy who has lost his mother when he was very young moved to a new place
		where he met his mother-in-law.
	 It seemed that he didn't like his new mother.
	 After he quarrelled with his new classmates and injured himself,
		he found a secret which was between his mother and his mother-in-law.  
	 In the end, he got along well with his mother-in-law.
	 --------------------
	 I last went to the cinema about two months ago when I was wandering in the mall.
	 Suddenly, it occurred to me
		that *it had been a long time since* I had watched a movie with my wife.
	 *As luck would have it*, there was a movie directed by Gong Qijun,
		 who has made several famous animated movies.
	 Of course, this was another animated movie of his.
	 The movie *revolved around* a boy
		who had lost his mother at a very young age
			and moved to a new place where he met his mother-in-law.
	 It seemed that he didn't like his new mother.
	 After quarreling with his new classmates and injuring himself,
		he *discovered a secret* that involved his mother and his mother-in-law.
	 In the end, he managed to get along well with his mother-in-law.


- Do you get angry easily? What sort of thing makes you angry?
	 Yes, I get angry easily.
	 I got angry in the case in which I couldn't get it under control.
	 Like my wife complains about some household chores and I sleep in and so on.
	 --------------------
	 Yes, I do get angry easily.
	 I find it difficult to control my anger in certain situations.
	 For example, when my wife complains about household chores or when I oversleep,
	  it tends to provoke my anger.
- Would you like to be an actor? Why/Why not?
	 I wouldn't like to be an actor.
	 Because I'm too shy to disappear in TV.
	 And I don't like to get along with so many people.
	 Sometimes I'll fear that it will spoil my private life a lot if I rise to fame.
	 --------------------
	 I wouldn't like to be an actor.
	 I'm too shy to be comfortable appearing on TV,
		and I prefer not to *interact with* large groups of people.
	 Additionally, I fear that fame would *intrude too much on* my private life
		if I were to become well-known.
