#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 2 Breakfast or lunch?
#+begin_verse
Why was the writer's aunt surprised?

It was Sunday.
I never *get up early* on Sundays.
I sometimes stay in bed until lunchtime.

Last Sunday I got up very late.
I looked out of the window.
It was dark outside.
'What a day!' I thought. 'It's raining again.'

*Just then*, the telephone rang.
It was my aunt Lucy.
'I've just arrived by train,' she said.
'I'm coming to see you.'
'But I'm still *having breakfast*,' I said.
'What are you doing?' she asked.
'I'm having breakfast,' I repeated.
'Dear me,' she said. 'Do you always get up so late? It's one o'clock!'
#+end_verse
** expression
until [ʌnˈtɪl] prep.直到
outside [ˌaʊtˈsaɪd] adv.外面
ring [rɪŋ] v.(铃)响
aunt [ɑːnt] n.姑,姨
repeat [rɪˈpiːt] v.重复

repeat after me: 重复我

--------------------
am/is/are + doing:
	1. 动作正在发生;
	2. 动作已经开始,但未完成;
	3. 表近期计划(+未来时间)
	4. 一段时间正在发生的事情: today/this week/this year(阶段)连用
	5. 一段时间正在发生的变化: get/change/become/increase/rise/fall/grow/improve/begin/start

do/does: 动作发生在说话时发生不重要
	1. 习惯动作(一直/重复发生的事情)
	2. 客观事实
	3. 行为靠说话完成. I promise,suggest,apologise,advise,insist,agree,refuse

am/is/are + doing VS do/does
	- 正在发生的行为还没有完成 VS 一直/重复发生的事情
	- 暂时的情况 VS 长久的情况
	- I always do(总是做某事) VS I'm always doing(总是做某事到不正常的程度)

感叹句: 形容词需要升调
	What + (形容词) + n. (+ 主语 + 谓语)

频率adv.位置: 
	1. 动词前,be/助/情态动词后
	2. is/will/did省略句前
	3. probably won't;

get up early/late: 起床早/晚
just then: at a particular time in the past在那时
have breakfast: 吃早餐


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
-
		1T: John's sleeping
		S1: Where's John? He's late.
		S2: I think he's still sleeping.
	 - Jane's dressing
		 Where's Jane? She's late.
		 I think she's still dressing.
	 - Tom's getting ready
		 Where's Tom? He's late.
		 I think he's still getting ready.
	 - Lucy telephoning
		 Where's Lucy. She's late.
		 I think she's still telephoning.
	 - Jane's shaving
		 Where's Jane. She's late.
		 I think she's still shaving.
-
	 2T: clean the car - Sunday
	 S1: Why are you cleaning the car now?
	 S2: Because it's Sunday I always clean the car on Sunday.
	 - ring your aunt - saturday
		 Why are you ringing your aunt now?
		 Because it's Saturday. I always ring my aunt on Saturday.
	 - go to bank - Friday
		 Why are you going to the Bank?
		 Because it's Friday. I always go to the Bank on Friday.
	 - play football - Wednesday
		 Why are you playing football?
		 Because it's Wednesday. I always play football on Wednesday.
	 - Write to John - Thursday
		 Why are you writing to John?
		 Because it's Thursday. I always write to John on Thursday.
-
	 3t: drive very fast
	 s1: He's driving very fast these days.
	 s2: He doesn't usually drive very fast.
	 - drinking heavily
		 He's drinking heavily these days.
		 He doesn't usually drink heavily.
	 - cook well
		 He's cooking well these days.
		 He doesn't usually cook weel.
	 - write carefully
		 He's writing carefully these days.
		 He doesn't usually write carefully.
	 - get up early
		 He's getting up early these days.
		 He doesn't usually get up early.
-
		4t: rude people
		s1: What rude people!
		s2: Yes, they are rude, aren't they?
	 - a strange story
		 What a strange story.
		 Yes, it is strange, isn't it?
	 - a rude girl
		 What a rude girl.
		 Yes, she is rude, isn't she?
	 - a good party
		 What a good party.
		 Yes, it is good, isn't it?
	 - an interesting play
		 What an interesting play.
		 Yes, it is interesting, isn't it?
** 给自己讲解
** 红皮书
** 习惯用法造句
get up early/late
- I get up late last Saturday.
- Did you get up late last Saturday?
- When did you get up late?
- Why did you get up late last Saturday?
- How often do you get up late?
just then
- I give a hug to my just then.
- Did you give a hug to your wife just then?
- Why did you give a hug to your wife just then?
- When did you give a hug to your wife last time?
- How did you give a hug to your wife just then?
have breakfast
- I had breakfast today.
- Did you have breakfast today?
- When did you have breakfast?
- Where did you have breakfast today?
- How did you have breakfast?
** 跟读至背诵
** Ask me if 写+读
1. I get up late on Sunday. When
	 When do you get up late?
2. I sometime stay in bed until lunchtime. What ... do/Where
		What do you do until lunchtime?
		When do you stay in bed?
3. I got up very late last Sunday. When
		When did you get up very late?
4. I looked at out of the window. Where
		Where did you look?
5. My aunt Lucy telephoned just then. Who
		Who telephoned just then?
6. She'd come by train. How
	 How did she come?
7. She was coming to see me. Who/When
	 Who was coming to see you?
	 When was she coming to see you?
8. I said, "I'm still having breakfast." What
	 What did you say?
9. It was one o'clock. What time
	 What time was it?
** 摘要写作
The writer always gets up late on Sunday.
He got up very late last Sunday.
His aunt telephoned him.
She was coming to see him by train.
He said, "I'm still having breakfast."
His aunt was very surprise.
Because it was one o'clock.
** tell the story 口语
** Topics for discussion
1. Do you get up early or late? Do you find it easy/difficult to get up? Why?
2. What do you usually have for breakfast?
3. When do people visit friends and relatives in your country?
