#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 3 Please send me a card.
#+begin_verse
How many cards did the writer send?

Postcards always spoil my holidays.
Last summer, I went to Italy.
I visited museums and sat in public gardens.
A friendly waiter *taught me a few words of Italian*.
Then he *lent me a book*.
I read a few lines, but I did not understand a word.
Every day I *thought about* postcards.
My holidays passed quickly, but I did not send cards to my friends.
*On the last day* I made a big decision.
I got up early and bought thirty-seven cards.
I *spent the whole day in my room*, but I did not write a single card!
#+end_verse
** expression
send [send] v.寄,送
postcard [ˈpəʊstkɑːd] n.明信片
spoil [spɔɪl] v. 使索然无味,损坏
museum [mjuˈziːəm] n.博物馆
public [ˈpʌblɪk] adj.公共的
friendly [ˈfrendli] adj.友好的
waiter [ˈweɪtə(r)] n.服务员
lend [lend] v.借给
decision [dɪˈsɪʒ(ə)n] n.决定
whole [həʊl] adj.整个的
single [ˈsɪŋɡ(ə)l] adj.唯一的,单一的

buy sb. sth. = buy sth. for sb. 买东西给某人
send sb. sth. = send sth. to sb. 送东西给某人
lend sb. sth. = lend sth. to sb. 借东西给某人
borrow sth. from sb. / borrow sb. sth. 从某人那借东西
make a decision: 做决定

--------------------
was/were/did: 过去的状态(was/were) & 动作发生在过去(did) & 和过去时间点连用

teach sb. sth. 教某人某事
lend sb. sth. 借给某人某物
think about sth./sb. 想某人某物
on the last day 在最后一天
make a decision 做决定
send sth. to sb. 送某人某物
spend st. sw. 在某地花多少时间


** 单词造句
buy sb. sth.
- I bought my wife an expensive iphone 13.
- Did you buy your wife an expensive iphone 13?
- What did you buy for your wife?
- Why did you buy an expensive iphone 13 for your wife?
- When did you buy your wife an expensive iphone 13.
send sb. sth.
- I sent my wife the tea.
- Did you send your wife tea?
- Why did you send your wife tea?
- When did you send tea to your wife?
- How did you send tea to your brother?
lend sb. sth.
- I usually lend money to my friend!
- Did you lend money to your friend?
- Why did you lend money to your friend?
- What did you lend to your friend?
- Where did you lend money to your friend?
borrow sth. from sb.
- I borrow a book from public library yesterday.
- What did you borrow from public library yesterday?
- When did you borrow a book from library?
- Did you borrow a book from public library yesterday?
- How often do you borrow books from public library.
make a decision
- According to the fact, I made this decision.
- Did you make a decision about learning?
- What did you make?
- Why did you make this decision?
- When did you make this decision?
** 反复听电影片段
** Pattern Drill 写+读
- 
	 1t: work - at the weekend
	 s1: Do you ever work at the weekend?
	 s2: Yes, I worked last weekend.
	- catch a cold - in winter
		Do you ever catch a cold in winter?
		Yes, I caught a cold last winter.
	- stay in bed - at the weekend
		Do you ever stay in bed at the weekend?
		Yes, I stayed in bed last weekend.
	- watch TV - at night
		Do you ever watch TV at night?
		Yes, I watched TV last night.
	- play golf - in summer
		Do you ever play gold in summer?
		Yes, I played gold last summer.
** 给自己讲解
** 红皮书
** 习惯用法造句
teach sb. sth.
- Sedgewick taught me the knowledge of algorithms.
- Who taught you the knowledge of algorithms?
- Did Sedgewick teach you the knowledge of algorithms?
- Why did Sedgewick teach you the knowledge of algorithms?
think about sth.
- I think about it every night and every day.
- What do you think about every night and every day?
- How often do you think about it?
- Why do you think about it?
on the last day
- I had finished my homework on the last day.
- Did you have finished your homework on the last day?
- When have you finished your homework?
- When did you finish your homework on the last day?
spend st. sw.
- I spend the half day at the office.
- How long did we spend at the office?
- Where did you spend the whole day?
- Why did you spend the half day at the office?

** 跟读至背诵
** Ask me if 写+读
1. I went to Italy for my summer holidays. Where/Why/When
	 Where did you go for your summer holidays?
	 Why did you go to Italy for your summer holidays?
	 When did you go to Italy?
2. I visited museums. What/When
		What did you visit?
		When did you visit museums?
3. I sat in public gardens. Where
		Where did you sit?
4. I learnt a little Italian. How much
		How much Italian did you learn?
5. A friendly waiter taught me. Who
		Who taught you?
6. He read a book. What/Who
	 What did he read?
	 Who read a book?
7. I read a few lines. How many
	 How many lines did you read?
8. I thought about postcards every day. How often/ What
	 How often did you think about postcards?
	 What did you think everyday?
** 摘要写作
Postcards always spoilt his holidays.
He went to Italy last summer, but he thought about postcards every day.
He didn't send any postcards to his friends.
He made a big decision, he bought 37 cards on the last day.
He stayed in his room all day, but he didn't write any cards.
** tell the story 口语
** Topics for discussion
1. How did you spend your holidays last year? Where did you go and what did you do?
2. Talk about some of the things that can spoil a holiday.
3. What is the best way to learn a foreign language?
