#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 9 A cold welcome

#+begin_verse
What does 'a cold welcome' refer to?

On Wednesday evening, we went to the Town Hall.
It was *the last day of the year*
	and *a large crowd of* people had gathered under the Town Hall clock.
It would strike twelve *in twenty minutes' time*.
Fifteen minutes passed and then, at five to twelve, the clock stopped.
The big minute hand did not move.
We waited and waited, but nothing happened.
Suddenly someone shouted, 'It's two minutes past twelve! The clock has stopped!'
I looked at my watch.
It was true.
The big clock *refused to welcome* the New Year.
*At that moment* everybody *began to laugh* and sing.
#+end_verse
** expression
welcome [ˈwelkəm] v.n.欢迎.欢迎
crowd [kraʊd] n.人群
gather [ˈɡæðə(r)] v.聚集
hand [hænd] n.(表或机器的)指针
shout [ʃaʊt] v.喊叫
refuse [rɪˈfjuːz] v.拒绝
laugh [lɑːf] v.笑

a cold welcome 冷遇
a warm welcome 热遇
gather round 聚集在一起
shout at sb. 对某人大声呼叫
refuse to do sth. 拒绝去做某事
laugh at sb. 嘲笑某人

--------------------
at/on/in(时间)
	- on + 具体某一天
	- in + 年/季/月
	- at + 时间点

the last day of the year 这一年的最后一天
a large crowd of 大量的人群
in twenty minutes' time 二十分钟后
refuse to do sth. 拒绝去做某事
at that moment 在那一刻
begin to do sth. 开始做某事


** 单词造句
welcome 
- What a cold welcome is.
- What a warm welcome is.
- Welcome to Beijing.
- Thanks for welcome.
- You're welcome.
crowd gather
- A large crowd of angry farmers gathered in front of the Bar.
- A large crowd of hungry beggars had gathered in two minutes.
- A large crowd of people gather in front of the Bank.
- A large crowd of engineers gathered at the door.
- A large crowd of actors gathered in front of the theater.
hand
- They are trying to fix that hour hand.
- Are they trying to fix that hour hand.
- Why are they trying to fix that hour hand, nobody uses it!
- Who are trying to fix that hour hand?
- When were they trying to fix that hour hand?
shout
- Don't shout at me, it's not my fault.
- Don't shout to me, I can hear you clearly.
- The beggar shouted at the police.
- Why did the beggar shout at the police?
- Why did my father shout at me?
refuse to do sth.
- To my surprise, my wife refuses to teach me English.
- To my surprise, my wife refuses to enter for the competition.
- At that moment, my wife refused to work for the big firm.
- Up to now, my wife refuses to think about life.
- To my surprise, my wife refuses to make a path for me.
laugh
- She laughed at me while I was speaking English.
- Did she laugh at you while you were speaking English?
- Why did she laugh at you, while you were speaking English?
- When did she laugh at you?
- Who laughed at you while you were speaking English?

** 反复听电影片段
** Pattern Drill 写+读
-
		1t:grandmother
		s1:When was your grandmother born?
		s2:She was born in 1934.
	 - grandfather - 1928
		 When was your grandfather born?
		 He was born in 1928.
	 - father - 1950
		 When was your father born?
		 He was born in 1950.
	 - mother - 1953
		 When was your mother born?
		 She was born in 1953.
	 - aunt - 1949
		 When was your aunt born?
		 She was born in 1949.
-
		2t:grandmother-October 10th
		s1:When's your grandmother's birthday?
		s2:It's on October 19th.
	 - grandfather - July 6th
		 When's your grandfather's birthday?
		 It's on July 6th.
	 - father - Janunary 27th
		 When's your father's birthday?
		 It's on Janunary 27th.
	 - sister - August 12th
		 When's your sister's birthday?
		 It's on August 12th.
	 - niece - December 23rd
		 When's your niece's birthday?
		 It's on December 23rd.
-
		3t:at four o'clock - at teatime
		s1:John came to see me at four o'clock.
		s2:But I thought you were never at home at teatime.
	 - on Saturday - at the weekend
		 John came to see me on Saturday.
		 But I thought you were never at hoem at the weekend.
	 - Before lunch - in the morning
		 John came to see me before lunch.
		 But I thought you were never at home in the morning.
	 - after dinner - in the evening
		 John came to see me after dinner.
		 But I thought you were never at home in the morning.
	 - at midday - at lunchtime
		 John came to see me at midday.
		 But I thought you weree never at home at lunchtime.
-
		4t: on Sunday afternoon - in the morning
		s1: John's arriving on Sunday afternoon.
		s2: Oh, I thought he was arriving in the morning.
	 - early on Monday - at midday
		 John's arriving early on Monday.
		 Oh, I thought he was arriving at midday.
	 - next summer - in the autumn
		 John's arriving next summer.
		 Oh, I thought he was arriving in the autumn.
	 - during the week - at the weekend
		 John's arriving during the week.
		 Oh, I thought he was arriving at the weekend.
	 - on June 10th - in July
		 John's arriving on June 10th.
		 Oh, I thought he was arriving in July.
		 
** 给自己讲解
** 红皮书
** 习惯用法造句
the last day of the year
- On the last day of the year, I went to the theater.
- To our surprise, he has gone to America on the last day of the year.
- On the last day of the year, we had a great trip in Sanya.
- On the last day of the year, she made a big decision.
- On the last day of the year, she has sent a postcard to me.
a large crowd of ...
-
-
-
-
-
in twenty minutes' time
- I would work with you in twenty minutes' time.
- I would receive you a postcard in seven days' time.
- Would you work with me in twenty minutes' time?
- I would get up in twenty minutes' time.
- I would pay attention to the teacher in one minute's time.
refuse to do sth.
-
-
-
-
-
at that moment
- At that moment, everybody began to stand on his head and sing.
- Did everybody begin to stand on his head at that moment?
- Why did everybody begin to stand on his head at that moment?
- Where did everybody begin to stand on his hand at that moment?
- Who began to stand on his head at that moment?
begin to do sth.
-
-
-
-
-

** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
1. What did you do to celebrate the last New Year?
2. What other important days are there in the year? How do you celebrate them?
3. Have you, or a friend, ever been late because yourwatch had stopped? Tell us about it.
