#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 10 Not for jazz 

#+begin_verse
What happened to the clavichord?

We have an old musical instrument.
It is called a clavichord.
It *was made in* Germany in 1681.
Our clavichord is kept in the living-room.
It has *belonged to* our family for a long time.
The instrument was bought by my grandfather many years ago.
Recently it was damaged by a visitor.
She tried to *play jazz* on it!
She struck the keys too hard and two of the strings were broken.
My father was shocked.
Now we *are not allowed to touch* it.
It is being repaired by a friend of my father's.
#+end_verse
** expression
jazz [dʒæz] n.爵士音乐
musical [ˈmjuːzɪk(ə)l] adj.音乐的
instrument [ˈɪnstrəmənt] n.乐器
clavichord [ˈklævɪkɔːd] n.古钢琴
recently [ˈriːs(ə)ntli] adv.最近
damage [ˈdæmɪdʒ] v.损坏
key [kiː] n.琴键
string [strɪŋ] n.(乐器的)弦
shock [ʃɒk] v.使不悦或生气,震惊
allow [əˈlaʊ] v.允许,让
touch [tʌtʃ] v.触摸

be allowed to do sth. 被允许做某事
allow sb. to do sth. 允许某人做某事

--------------------
am/is/are+done
was/were+done
am/is/are+being+done
have/has+been+done

be made in sw. 某地制造
belong to sb. 属于某人
play jazz 弹爵士
be allowed to do sth. 被允许做某事


** 单词造句
jazz
- He began to play jazz when he was very young.
- Did he begin to play jazz when he was very young?
- When did he begin to play jazz?
- Listen, he is playing jazz.
- He is playing jazz tonight.
musical instrument
- He refused to lend me the musical instrument.
- Did he refuse to lend you the musical instrument?
- Why did he refuse to lend you the musical instrument?
- I got a musical instrument for my wife.
- Did you get the musical instrument for your wife?
clavichord
- The clavichord is being played by her.
- The clavichord was played by her last night.
- The clavichord is being played by her tonight.
- She has been played the clavichord last night.
- She plays the clavichord almost everyday.
recently
- Recently, the clavichord was damaged by a visitor.
- Was the clavichord damaged by the visitor recently?
- How was the clavichord damaged by the visitor recently?
- When was the clavichord damaged by the visitor?
- Where was the clavichord damaged by the visitor?
damage
-
-
-
-
-
key
- I sent a request for some keys.
- Did he send a request for some keys?
- I have gotten some keys for my wife?
- Have you gotten some keys for you wife?
- How did he send a request for some keys?
string
- This is the best string I've ever seen.
- This string is better than that one.
- The string is being repaired by my friend.
- Is this the best string you've ever seen?
- Why is the string being repaired by your friend?
shock
- This shock my father.
- Did this shock your father?
- Why did this shock your father?
- How did this shock your father?
- What shocked your father?
allow
- We're not allowed to smoke on the train.
- We're not allowed to touch things in the museums.
- My father allows me to watch TV on Friday night.
- My wife allows me to ride the bike every day.
- My wife doesn't allow me to play piano anymore.
touch
- Don't touch me!
- Don't touch that!
- The cat refuses to touch me.
- The children are not allowed to touch my cat.
- Did the cat touch me just now?

** 反复听电影片段
** Pattern Drill 写+读
-
		1t: the hovercraft, invented - an Englishman.
		s1: Who was the hovercraft invented by?
		s2: I think it was invented by an Englishman.
	 - the music, composed - a German
	 s1: Who was the music composed by?
	 s2: I think it was composed by a German.
	 - that chair, made - my grandfather
	 s1: Who was that chair made by?
	 s2: I think it was made by my grandfather.
	 - this car, designed - an Italian
	 s1: Who was the car designed by?
	 s2: I think it was designed by an Italian.
	 - that competition, won - my friend
	 s1: Who was that competition won by?
	 s2: I think it was won by my friend.
-
		2t: built this bridge - in 1937
		s1: Who built this bridge?
		s2: It was built in 1937 - that's all I know.
	 - wrote this play - in 1861
	  Who wrote this play?
	  It was wrote in 1861 - that's all I know.
	 - invented the telephone - in America in 1876
	  Who invented the telephone?
	  It was invented in America in 1876 - that's all I know.
	 - made this piano - in Germany
	  Who made this piano?
	  It was made in Germany - that's all I know.
	 - stole her diamonds - in the theater last night
	  Who stole her diamonds?
	  It was stole in the theater last night - that's all I know.
-
		3t:the house, painted
		s1:Has the house been painted yet?
		s2:It's being painted now.
	 - the TV, repaired
		Has the TV been repaired yet?
		It's being repaired now.
	 - the film, shown
		Has the film been shown yet?
		It's being shown now.
	 - the lunch, served
		Has the lunch been served yet?
		It's being served now.
	 - the stereo, mended
		Has the stereo been mended yet?
		It's being mended now.
4.
	 4t:house, painted - two years ago
	 s1:When was the house last painted?
	 s2:It was painted two years ago.
	 - car/stereo, repaired - last night
		When was the stereo last repaired?
		It was repaired last night.
	 - rent, paid - a month ago
		When was the rent last paid?
		It was paid a month ago.
	 - carpet, cleaned - on Saturday
		When was the carpet last cleaned?
		It was cleaned on Saturday.
		 
** 给自己讲解
** 红皮书
** 习惯用法造句
be made in sw.
- The chair was made in Hebei.
- Was the chair made in Hebei?
- Where was the chair made?
- How was the chair made in Hebei?
- The char must be made in Hebei.
belong to sb.
- The computer has belonged to me for two years.
- The computer will belong to you in twenty minutes.
- Has the computer belonged to you for two years?
- Who does the computer belong to?
- He tricked me out of a computer which has belonged to me for over two years.
play jazz
-
-
-
-
-
be(not) allow to do sth.
-
-
-
-
-

** 跟读至背诵
** Ask me if 写+读
1. Do you own an old musical instrument?
	 What kind of instrument do you own?
2. It's called a clavichord.
		What is it called?
3. It's kept in the living room.
		Where is it kept?
4. It was made in Germany.
		Where was it made?
		When was it made?
5. It was made in 1681.
		When was it made?
		What was made in 1681.
6. It has belonged to us for a long time.
	 How long has it belonged to us?
	 What has belonged to us for a long time?
	 Who has it belonged to for a long time?
7. It was bought by my grandfather.
	 Who was it bought by?
8. It was damaged recently. When
	 When was it damaged?

** 摘要写作
We own an old clavichord.
It was made in 1681.
My grandfather bought it many years ago.
A visitor damaged it recently.
She tried to play jazz on it.
She broke two of the strings.
It's being repaired by a friend of my father.

** tell the story 口语
** Topics for discussion
Have you got anything very old in your family? How long ago was it bought?
Have you ever damaged anything old? How was it repaired?
What kinds of things are easily broken?
