#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 16 A polite request

#+begin_verse
What was the polite request?

If you *park your car* in the wrong place, a traffic policeman will soon find it.
You will be very lucky if he lets you go without a ticket.
However, this does not always happen.
Traffic police are sometimes very polite.
During a holiday in Sweden, I found this note on my car:
	'Sir, we welcome you to our city.
This is a "No Parking" area.
You will enjoy your stay here if you *pay atention to* our street signs.
This note is only a reminder.'
If you receive a request like this, you cannot *fail to obey* it!
#+end_verse
** expression
park [pɑːk] v.停放(汽车)
traffic [ˈtræfɪk] n.交通
ticket [ˈtɪkɪt] n.交通违规罚款单
note [nəʊt] n.便条
area [ˈeəriə] n.地段
sign [saɪn] n.指示牌
reminder [rɪˈmaɪndə(r)] n.提示
fail [feɪl] v.无视,忘记
obey [əˈbeɪ] v.服从

make notes/ a note 做笔记
leave a note 留下便条
remind sb. of sth./sb. 使得某人想起某事或某人
fail to do sth. 失败做某事

--------------------
if从句
	- 主将从现
	- 主情从现
	- 主祈从现

park sb's car 停某人的车
pay attention to 注意到某事
	

** 单词造句
park
- Sir, you can't park your car here.
-	Why can't I park it here?
- Is there a parking lot near here, sir?
-	Look, we're not allowed to park here.
- I had an amusing experience while I was parking my car.
traffic
- Damn, a traffic jam.
- Our son is a traffic police and we're very proud of him.
- Those traffic lights have been broken by three kids last night.
- If there is a heavy traffic, we will be late.
- Pay atention to those traffic lights.
ticket
- If you park there, you will get a traffic ticket for that.
- A traffic police waved to me and asked me to stop, then he gave me a ticket.
- Zhangwei cannot afford to pay so many traffic tickets.
- I can't afford to pay an air ticket to Beijing.
- Now, you can pay for my ticket.
note
- I believe that you will make notes in my class.
- He asks me to leave a note.
- He refused to lend me his notes.
- I borrowed his notes from him.
- To my surprise, he has made notes last night.
area
- This is a "No Parking" area.
- Is this a "No Parking" area?
- Why is this a "No Parking" area?
- Don't park in a "No Parking" area?
- Why do you park your car in a "No Parking" area?
sign
- Can you read that sign?
- Look at that sign.
- Pay attention to these street's signs.
- The signs have been damaged by these kids.
- We can't afford to pay so many signs.
reminder
- This is only a reminder.
- It reminds me of my father.
- Why does it reminds you of your father?
- What reminds you of your father?
- The alarm clock reminds me of doing my homework.
fail
- He always fail to pay it back on time.
- I can't fail to do my homework.
- He fails to borrow the chess from his neighbor.
- He failed to get a telephone for his garage.
- He failed to write a single postcard.
obey
- We must obey the traffic rules.
- I refused to obey that stupid rules.
- Why did you refuse to obey that rules?
- I can't fail to obey a police request.
- Please obey his request.

** 反复听电影片段
** Pattern Drill 写+读
- 1
	- miss the train - go by taxi
	  You'll miss the train if you're not careful.
	  If I do, I'll go by taxi.
	- break that vase - buy a new one
		You'll break that vase if you're not careful.
		If I do, I'll buy a new one.
	- catch a cold - stay in bed
		You'll catch a cold if you're not careful.
		If I do, I'll stay in bed.
	- fail your test - try again
		You'll fail your test, if you're not careful.
		If I do, I'll try again.
	- lose your job - find an other
		You'll lose your job if you're not careful.
		If I do, I'll find an other.
- 2
	- clean the car
		Shall I clean the car for you?
		You can clean it if you want to.
	- post these parcels
		Shall I post these parcels for you?
		You can post them if you want to.
	- pay the bill
		Shall I pay the bill for you?
		You can pay it if you want to.
	- order the books
		Shall I order the books for you?
		You can order them if you want to.
	- take you to the theater
		Shall I take you to the theater for you?
		You can take me if you want to.
- 3
	- sell it
		What'll you do if he doesn't sell it?
		I'm sure he will sell it, but if he doesn't, I'll sell it myself.
	- write the letter
		What'll you do if he doesn't write the letter?
		I'm sure he will write it, but if he doesn't, I'll write it myself.
	- return the books
		What'll you do if he doesn't return the books?
		I'm sure he will return them, but if he doesn't, I'll return them myself.
	- repair the gate
		What'll you do if he doesn't repair the gate?
		I'm sure he will repair it, but if he doesn't, I'll repair it myself.
	- ring the police
		What'll you do if he doesn't ring the police?
		I'm sure he will ring them, but if he doesn't, I'll ring them myself.
- 4
	- speak to him - nervous
		Don't speak to him if he's nervous.
		Of course I shan't speak to him if he's nervous.
	- disturb him - working
		Don't disturb him if he's working.
		Of course I shan't disturb him if he's working.
** 给自己讲解
** 红皮书
** 习惯用法造句
park sb's car
- She parked her car in front of the theater last night.
- Did she park her car in front of the theater last night?
- Why didn't she park her car in front of theater last night?
- Where did she park her car last night?
- When did she park her car in front of the theater?
pay attention to
- You must pay attention to this video.
- Must I pay attention to this video?
- Why must I pay attention to this video?
- What will I get if I pay attention to this video?
- I'll give you an extra 1000 pounds a year if you pay attention to your work every day.
** 跟读至背诵
** Ask me if 写+读
1. Traffic police give parking tickets.
	 What do traffic police do?
	 Who give parking tickets?
2. They will soon find your car, if you park in the wrong place.
	 How quickly will they find your car, if you park in the wrong place?
3. Traffic police are sometimes very polite.
	 Who are sometimes very polite?
4. I went to Sweden for a holiday.
	 Where did I go for a holiday?
5. I found a note on my car.
	 What did you find on your car?
	 Where did you find a note?
6. It said, "Welcome to our city".
	 What did it say?
7. My car was in a "No Parking" area.
	 Where was my car?
	 What was in a "No Parking" area?
	 Whose car was in a "No Parking" area?
8. You'll enjoy your stay here.
	 What will you enjoy?
9. The note was only a reminded.
	 What was the note?
10. I obeyed the request.
		What did I do?
** 摘要写作
Traffic police usually give you a ticket if you park my car in the wrong place.
But the writer found a polite note on his car during a holiday in Sweden.
The traffic police wanted him to pay attention to street's signs.
Everyone cannot fail to obey a request like this.
** tell the story 口语
** Topics for discussion
What will happen if you park a car in the place in your city?
Is it useful to have a car in a city? Why/Why not?
Do you think the Swedish traffic police are always so polite? Why/Why not?
