#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 18 He often does this!
#+begin_verse
What had happened to the writer's bag?

After I had had lunch at a village pub, I looked for my bag.
I had left it on a chair beside the door and now it wasn't there!
As I was *looking for* it, the landlord came in.
'Did you *have a good meal*?' he asked.
'Yes, thank you,' I answered,
	'but I can't *pay the bill*.
I haven't got my bag.'
The landlord smiled and immmediately went out.
*In a few minutes* he returned with my bag and gave it back to me.
'I'm very sorry,' he said.
'My dog had taken it into the garden.
He often does this!'
#+end_verse
** expression
pub [pʌb] n.小酒店
landlord [ˈlændlɔːd] n.店主
bill [bɪl] n.账单

pay the bill 支付账单

--------------------
have 万能动词

look for 寻找
have a meal 吃饭
pay the bill 支付账单
in a few minutes 在几分钟内


** 单词造句
pub n.
- He drunk too heavy in that pub.
- The pub must be built in 1993.
- They built this pub years ago.
- The pub is being cleaned now so that you won't receive treatment.
- Don't park you car in front of the pub.
landlord n.
- It must be terrible to share a flat with your landlord.
- As soon as the landlord had left, they began to have a party.
- If the landlord asks why you come here, you can tell him that you are my friend.
- The landlord can't have been your friend.
- The landlord must have been sleeping well last night.
bill n.
- Leo will have to pay the bill.
- The bill have already been paid by my wife.
- If you fail to pay the bill, I'll remind of it.
- If you go to the restaurant with a beautiful girl, you can't refuse to pay the bill.
- I have never borrowed money from you, so now you can pay the bill.
** 反复听电影片段
** Pattern Drill 写+读
- 1
	- this shell
		Oh, I like this shell.
		You can have it if you want it. I've got lots of them.
	- this spoon
		Oh, I like this spoon.
		You can have it if you want it. I've got lots of them.
	- this tie
		Oh, I like this tie.
		You can have it if you want it. I've got lots of them.
	- these flowers
		Oh, I like these flowers.
		You can have it if you want it. I've got lots of them.
	- this card
		Oh, I like this card.
		You can have it if you want it. I've got lots of them.
- 2
	- the tickets
		Have you got the tickets?
		Good heavens, where are they? I had them a minute ago!
	- your handbag
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
Have you ever lost any money? If so, tell us what happened.
Describe the best meal you've ever had.
'The dog is a man's best friend.' Do you agree with this saying? Why/why not?
