#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 19 Sold out
#+begin_verse
When will the writer see the play?

'The play may begin at any moment,' I said.
'It may have begun already,' Susan answered.
I *hurried to the ticket office*.
'May I have two tickets please?' I asked.
'I'm sorry, we've *sold out*,' the girl said.
'*What a pity*!' Susan exclaimed.
Just then, a man hurried to the ticket office.
'Can I return these two tickets?' he asked.
'Certainly,' the girl said.
I went back to the ticket office *at once*.
'Could I have those two tickets please?' I asked.
'Certainly,' the girl said, 'but they're for next Wednesday's performance.
Do you still want them?'
'I *might as well* have them,' I said sadly.
#+end_verse
** ~
hurry [ˈhʌri] v.匆忙
ticket [ˈtɪkɪt] office [ˈɒfɪs]售票处
pity [ˈpɪti] n.令人遗憾的事
exclaim [ɪkˈskleɪm] v.大声说
return [rɪˈtɜːn] v.n.退回
sadly [ˈsædli] adv.悲哀地,丧气地

hurry to sw. 匆忙去某地
in a hurry 匆忙地
What a pity 多么遗憾
It's a pity that... 非常遗憾...
Don't yell at me. 别冲着我叫

--------------------
也许 现在-猜测: 
may/might (not)do
may/might (not)be adj./n.
may/might (not)be doing

也许 过去-猜测: 
may/might (not)have done
may/might (not)have been adj./n.
may/might (not)have been doing.

sold out 售完
at once (=immediately, soon) 立刻
might/may as well 最好


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
Is it always easy to get seats for the theatre in your country?
How do you like to spend your evenings?
If you're going on holiday, what do you have to book in advance?
