#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 20 One man in a boat

#+begin_verse
Why is fishing the writer's favourite sport?

Fishing is my favourite sport.
I often fish for hours without catching anything.
But this does not worry me.
Some fishermen are unlucky.
*Instead of catching fish*, they catch old boots and rubbish.
I am even less lucky.
I never catch anything -- not even old boots.
After having *spent whole mornings on the river*,
	I always go home with an empty bag.
'You must *give up fishing*!' my friends say.
'It's a waste of time.
'But they don't realize one important thing.
*I'm not really interested* in fishing.
I am only interested in sitting in a boat and doing nothing at all.
#+end_verse
** expression
catch [kætʃ] caught caught v.抓到
fisherman [ˈfɪʃəmən] n.钓鱼人,渔民
boot [buːt] n.靴子
rubbish [ˈrʌbɪʃ] n.垃圾
waste [weɪst] n v.浪费
realize [ˈriːəlaɪz] v.意识到

catch your eye 引起你的注意
catch a bus 赶公交车
watch your tongue 小心言辞
That's rubbish 这是垃圾
You're wasting time. 你在浪费时间
sb. realized that... 某人意识到...

--------------------
动名词:v-ing

instead of doing sth. 而不是做某事
spend st. sw. 在某地花费时间
give up doing sth. 放弃做某事
be interesting in doing sth. 对做某事赶兴趣
be keen on doing sth. 对做某事感兴趣
** 单词造句
catch [kætʃ] caught caught v.抓到
- The police have caught the theif.
- The thief has been caught by the police.
- Did you catch anything?
- It's a pity that you caught a pair of boots.
- If someone catches your eyes, you will watch your tongue.
fisherman [ˈfɪʃəmən] n.钓鱼人,渔民
- The fisherman has to get up very early in every morning.
- 
- 
- 
- 
boot [buːt] n.靴子
- 
- 
- 
- 
- 
rubbish [ˈrʌbɪʃ] n.垃圾
- 
- 
- 
- 
- 
waste [weɪst] n v.浪费
- 
- 
- 
- 
- 
realize [ˈriːəlaɪz] v.意识到
- 
- 
- 
- 
- 
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
What is your favourite pastime?
Do you think the writer is wasting his time? why/Why not?
Do you think the writer would like to work as a fisherman? Would you? Why/Why not?
