#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 21 Mad or not

#+begin_verse
Why do people think the writer is mad?

Aeroplanes are slowly *driving me mad*.
I live near an airport
	and passing planes can be heard night and day.
The airport was built years ago,
	but *for some reason* it could not be used then.
Last year, however, it *came into use*.
Over a hundred people must have been driven away from their homes by the noise.
I am one of the few people left.
Sometimes I think this house will be knocked down by a passing plane.
I have been offered *a large sum of money* to go away,
	but I *am determined to stay* here.
Everybody says I must be mad
	and they are probably right.
#+end_verse
** ~
mad [mæd] adj.发疯
reason [ˈriːz(ə)n] n.原因
sum [sʌm] n.量
determined [dɪˈtɜːmɪnd] adj.坚定的,下决心的

be mad at sb. 对某人很恼火
for some reason 因为一些原因
a large sum of money 一大笔钱
be determined to do sth. 决心做某事

--------------------
will/would be done
can/could be done
must be done
have to be done
must have been done

drive sb. mad 使某人发狂
for some reason 因为一些原因
come into use 投入使用


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
What kind of noises do you hear where you live?
Compare the noises heard in the country and in towns.
What problems do people face when they live near airports?
