#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 23 A new house

#+begin_verse
Why is the new house special?

I *had a letter from my sister* yesterday.
She lives in Nigeria.
In her letter, she said that she would come to England next year.
If she comes, she will *get a surprise*.
We are now living in a beautiful new house in the country.
Work on it had begun before my sister left.
The house was completed five months ago.
In my letter, I told her that she could stay with us.
The house has many large rooms
	and there is a lovely garden.
It is a very modern house,
	so it looks strange to some people.
It must be the only modern house in the district.
#+end_verse
** expression
complete [kəmˈpliːt] v.完成
modern [ˈmɒd(ə)n] adj.新式的,与以往不同的
strange [streɪndʒ] adj.奇怪的
district [ˈdɪstrɪkt] n.地区

You complete me. 你完成了我
have a letter from sb. 收到某人的信
get a surprise 得到个惊喜


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
What do you do to welcome a visitor to your home?
Would you rather live in an old house or a modern house? Why?
Imagine you are coming home after living abroad for some time. What would you want to do?
