#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 26 The best art critics

#+begin_verse
Who is the student's best critic?

I am an art student
	and I paint a lot of pictures.
*Many people pretend that* they understand modern art.
They always tell you what a picture is 'about'.
Of course, many pictures are not 'about' anything.
They are just pretty patterns.
We like them in the same way
	that we like pretty curtain material.
I think that young children often appreciate modern pictures better than anyone else.
They notice more.
My sister is only seven,
	but she always tells me whether my pictures are good or not.
She came into my room yesterday.
'What are you doing?' she asked.
'I'm hanging this picture on the wall,' I answered.
'It's a new one. Do you like it?'
She looked at it critically for a moment.
'It's all right,' she said, 'but isn't it upside down?'
I looked at it again.
She was right! It was!
#+end_verse
** expression
art [ɑːt] n.艺术
critic [ˈkrɪtɪk] n.评论家
paint [peɪnt] v.画
pretend [prɪˈtend] v.假装
pattern [ˈpæt(ə)n] n.图案
curtain [ˈkɜːt(ə)n] n.窗帘,幕布
material [məˈtɪəriəl] n.材料
appreciate [əˈpriːʃieɪt] v.鉴赏
notice [ˈnəʊtɪs] v.注意到
whether [ˈweðə(r)] conj.是否
hang [hæŋ] hung hung v.悬挂,吊
critically [ˈkrɪtɪkli] adv.批评地
upside [ˈʌpsaɪd] down 上下颠倒地

sb. pretend that ... 某人假装...
I really appreciate that. 我真的感激.



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
