#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 27 A wet night

#+begin_verse
What happened to the boys in the night?

Late in the afternoon, the boys *put up their tent* in the middle of a field.
As soon as this was done,
	they cooked a meal over an open fire.
They were all hungry
	and the food smelled good.
After a wonderful meal, they *told stories* and sang songs by the campfire.
But some time later it began to rain.
The boys felt tired
	so they *put out the fire* and crept into their tent.
Their sleeping bags were warm and comfortable,
	so they all slept soundly.
In the middle of the night, two boys *woke up* and began shouting.
The tent was full of water!
They all leapt out of their sleeping bags and hurried outside.
It was raining heavily
	and they found that a stream had formed in the field.
The stream wound its way across the field
	and then flowed right under their tent.
#+end_verse
** expression
tent [tent] n.帐篷
field [fild] n.田地,田野
smell [smel] smelt v.闻起来
wonderful [ˈwʌndərfəl] adj.极好的
campfire [ˈkæmpˌfaɪr] n.营火,篝火
creep [krip] v.爬行
sleeping [sliːp] bag 睡袋
comfortable [ˈkʌmfərtəb(ə)l] adj.舒适的,安逸的
soundly [ˈsaʊn(d)li] adv.香甜地
leap [lip] v.跳跃,跳起
heavily [ˈhevɪli] adv.大量地
stream [strim] n.小溪
form [fɔrm] v.形成
wind [waɪnd] wound wound v.蜿蜒
right [raɪt] adv.正好

put up the tent 搭起帐篷
tell a story/stories 讲个故事
put out the fire 扑灭火焰
begin doing sth. 开始做某事
wake up 醒来



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
