#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 29 Taxi!

#+begin_verse
Does Captain Fawcett think any trip is too dangerous?

Captain Ben Fawcett has bought an unusual taxi and has begun a new service.
The taxi is a small Swiss aeroplane called a 'Pilatus Porter'.
This wonderful plane can carry seven passengers.
The most surprising thing about it, however, is that it can land anywhere;
	on snow, water, or even on a ploughed field.
Captain Fawcett's first passengers was a doctor
	who flew from Birmingham to a lonely village in the Welsh mountains.
Since then, Captain Fawcett has flown passengers to many unusual places.
Once he landed on the roof of a block of flats and on another occasion,
	he landed in a deserted car park.
Captain Fawcett has just refused a strange request from a businessman.
The man wanted to fly to Rockall, a lonely island in the Atlantic Ocean,
	but Captain Fawcett did not take him
		because the trip was too dangerous.
#+end_verse
** expression
taxi [ˈtæksi] n.出租汽车
Pilatus Porter
land [lænd] v.着陆
plough [plaʊ] v.耕地
lonely [ˈloʊnli] adj.偏僻的,人迹罕至的
Welsh [welʃ] adj.威尔士的
roof [ruf] n.楼顶
block [blɑk] n.一座大楼
flat [flæt] n.公寓房
desert [ˈdezərt] v.废弃

take a taxi 乘坐出租车

--------------------
done做定语: 表被动一般/被动完成/主动完成(少)
	- done + n.
	- n. + done短语
	- 常常与there be句型连用
复习have done VS did



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
