#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 33 Out of the darkness
#+begin_verse
Why was the girl in the hospital?

Nearly a week passed before the girl was able to explain what had happened to her.
One afternoon she set out from the coast in a small boat and was caught in a storm.
Towards evening, the boat struck a rock and the girl jumped into the sea.
Then she swam to the shore after spending the whole night in the water.
Early next morning, she saw a light ahead.
She knew she was near the shore because the light *was high up* on the cliffs.
*On arriving* at the shore, the girl *struggled up* the cliff towards the light she had seen.
That was all she remembered.
When she woke up a day later, she found herself in hospital.
#+end_verse
** expression
darkness [ˈdɑrknəs] n.黑暗
explain [ɪkˈspleɪn] v.解释,叙述
coast [koʊst] n.海岸
storm [stɔrm] n.暴风雨
towards [təˈwɒrd] prep.向,朝;接近
rock [rɑk] n.岩石,礁石
shore [ʃɔr] n.海岸
light [laɪt] n.灯光
ahead [əˈhed] adv.在前面
cliff [klɪf] n.峭壁
struggle [ˈstrʌɡ(ə)l] v.挣扎
hospital [ˈhɑspɪt(ə)l] n.医院

struggle up 艰难地爬起来
explain sth. to sb. 向某人解释某事
go ahead 前进
 
--------------------
be high up 高高在上
On doing sth, ... 一做完某事,就...



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
