#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 38 Everything except the weather
#+begin_verse
Why did Harrison sell his house so quickly?

My old friend, Harrison,
	had lived in the Mediterranean for many years before he returned to England.
He had often *dreamed of retiring* in England and had *planned to settle down* in the country.
He had no sooner returned than he bought a house and went to live there.
Almost immediately he began to *complain about the weather*,
	for even though it was still summer, it rained continually and it was often *bitterly cold*.
After so many years of sunshine, Harrison got a shock.
He acted as if he had never lived in England before.
In the end, it was more than he could bear.
He had hardly had time to settle down when he sold the house and left the country.
The dream he had had for so many years ended there.
Harrison had thought of everything except the weather.
#+end_verse
** expression
except [ɪkˈsept] prep.除了
Mediterranean [ˌmedɪtəˈreɪniən] n.地中海
complain [kəmˈpleɪn] v.抱怨
continually [kən'tɪnjʊəlɪ] adv.不断地
bitterly [ˈbɪtərli] adv.刺骨地
sunshine [ˈsʌnˌʃaɪn] n.阳光

complain about sth. 抱怨某事
bitterly cold 刺痛地寒冷

--------------------
一前就后,过去完成时的固定句式
had hardly done ... when ...
had no sooner done ... than ...

dream of doing sth. 梦想做某事
plan to do 计划做某事
settle down 安顿下来



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
