#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 40 Food and talk
#+begin_verse
Was Mrs. Rumbold a good companion at dinner?

Last week at a dinner party, the hostess asked me to sit next to Mrs. Rumbold.
Mrs. Rumbold was a large, unsmiling lady in a tight black dress.
She did not even look up when I *took my seat* beside her.
Her eyes were fixed on her plate and in a short time, she *was busy eating*.
I tried to make conversation.
'A new play is coming to "The Globe" soon,' I said. "*Will you be seeing* it?"
'No,' she answered.
'Will you be spending your holidays abroad this year?' I asked.
'No,' she answered.
'Will you be staying in England?' I asked.
'No,' she answered.
*In despair*, I asked her whether she was enjoying her dinner.
'Young man,' she answered, 'if you ate more and talked less, we would both enjoy our dinner!'
#+end_verse
** expression
hostess [ˈhoʊstəs] n.女主人
unsmiling [ʌnˈsmaɪlɪŋ] adj.不笑的,严肃的
tight [taɪt] adj.紧身的
fix [fɪks] v.凝视
globe [ɡloʊb] n.地球
despair [dɪˈsper] n.绝望

in despair 绝望地

--------------------
虚拟语气(现在): 与现在事实相反
	If + did/were, 主+would/should/could/might do

take my seat 做我的座位
be busy doing sth. 忙于做某事
Will you be doing sth? 你会做某事吗?



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
