#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 44 Through the forest
#+begin_verse
How did Mrs. Sterling get her bag back?

Mrs. Anne Sterling did not think of the risk she was taking
	when she ran through a forest after two men.
They had *rushed up to her*
	while she was *having a picnic* *at the edge of a forest* with her children
		and tried to steal her handbag.
In the struggle, the strap broke and, with the bag *in their possession*,
	both men started running through the trees.
Mrs. Sterling got so angry that she ran after them.
She was soon *out of breath*, but she continued to run.
When she *caught up with them*,
	she saw that they had sat down and were going through the contents of the bag,
	so she *ran straight at them*.
The men got such a fright that they dropped the bag and ran away.
"The strap needs mending," said Mrs. Sterling later, 'but they did not steal anything."
#+end_verse
** expression
forest [ˈfɔrəst] n.森林
risk [rɪsk] n.危险,冒险
picnic [ˈpɪknɪk] n.野餐
edge [edʒ] n.边缘
strap [stræp] n.带,皮带
possession [pəˈzeʃ(ə)n] n.所有
breath [breθ] n.呼吸
contents [kənˈtent] n.(常用复数)内有的物品
mend [mend] v.修理

take a risk 冒险
have a picnic 野餐
at the edge of a forest 在森林的边缘
in sb's possession 在某人手中
out of breath 喘不过气来

rush up to sb. 冲向某人
catch up with sb.  追上某人
go through: 翻遍
need doing sth.: 需要被做某事
run straight at sb. 径直冲向某人



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
