#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 45 A clear conscience
#+begin_verse
How did Sam get his money back?

*The whole village soon learnt that* a large sum of money had been lost.
Sam Benton, the local butcher, had lost his wallet while taking his savings to the post office.
Sam was sure that the wallet must have been found by one of the villagers,
	but it was not *returned to him*.
Three months passed, and then one morning, Sam found his wallet outside his front door.
It had been wrapped up in newspaper
	and it contained half the money he had lost,
		together with a note which said: 'A thief, yes, but only 50 percent a thief!'
Two months later, some more money was sent to Sam with another note:
	'Only 25 percent a thief now!'
In time, all Sam's money was paid back in this way.
The last note said: 'I am 100 percent honest now!'
#+end_verse
** expression
clear [klɪr] adj.无罪的,不亏心的
conscience [ˈkɑnʃəns] n.良心,道德心
wallet [ˈwɑlət] n.皮夹,钱夹
savings [ˈseɪvɪŋ] n.存款
villager [ˈvɪlɪdʒər] n.村民
percent [pərˈsent] 百分之...

I have a clear conscience 我问心无愧
Are you 100 percent sure about this? 你百分百确定吗?

--------------------
be done

sb. learn that + 宾语从句 某人得知
return sth. to sb. 把某物归还给某人



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
