#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 46 Expensive and uncomfortable

#+begin_verse
What did the man in this story do?

When a plane from London arrived at Sydney airport,
	workers began to unload a number of wooden boxes which contained clothing.
*No one could account for the fact that* one of the boxes was extremely heavy.
*It suddenly occurred to one of the workers to open* up the box.
He *was astonished at what* he found.
A man was lying in the box on top of a pile of woollen goods.
He was so surprised at being discovered that he did not even try to run away.
After he was arrested,
	the man *admitted hiding* in the box before the plane left London.
He had had a long and uncomfortable trip,
	for he had been confined to the wooden box for over eighteen hours.
The man was ordered to pay 3500 dollars for the cost of the trip.
The normal price of a ticket is 2000 dollars!
#+end_verse
** expression
unload [ʌnˈloʊd] v.卸(货)
wooden [ˈwʊd(ə)n] adj.木制的
extremely [ɪkˈstrimli] adv.非常,极其
occur [əˈkɜr] v.发生
astonish [əˈstɑnɪʃ] v.使惊讶
pile [paɪl] n.堆
woolen [ˈwʊlən] n.羊毛的
goods [ɡʊdz] n.(常用复数)货物,商品
discover [dɪˈskʌvər] v.发现
admit [ədˈmɪt] v.承认
confine [kənˈfaɪn] v.关在(一个狭小的空间里)
normal [ˈnɔrm(ə)l] adj.正常的,通常的

It occurred to sb. that ... 某人突然想到……
It occurred to sb. to do sth. 某人突然想到做某事
be astonished at sth. 对某事感到惊讶
admit doing sth. 承认做过某事
sb. admit that... 某人承认……

--------------------
- 同位语: 补充说明的名词
I have just received a letter from my brother, Tim.

- 同位语从句: 完整(引导词不充当从句成分)句子补充说明名词.
No one could account for *the fact that* one of the boxes was extremely heavy.

What = the thing that/the person that
sb. account for the fact that + 句子 某人解释了这一事实



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
