#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 47 A thirsty ghost
#+begin_verse
What evidence is there of a ghost?

A public house which was recently bought by Mr. Ian Thompson *is up for sale*.
Mr. Thompson is going to sell it because it is haunted.
He told me that he could not go to sleep one night
	because he *heard a strange noise coming* from the bar.
The next morning, he found that
	the doors had been blocked by chairs and the furniture had been moved.
Though Mr. Thompson had turned the lights off before he went to bed,
	they were on in the morning.
He also said that he had found five empty whisky bottles
	which the ghost must have drunk the night before.
When I suggested that some villagers must have come in for a free drink,
	Mr. Thompson shook his head.
The villagers have told him that they will not accept the pub even if he gives it away.
#+end_verse
** expression
thirsty [ˈθɜrsti] adj.贪杯的
ghost [ɡoʊst] n.鬼魂
haunt [hɔnt] v.(鬼)来访,闹鬼
block [blɑk] v.堵
furniture [ˈfɜrnɪtʃər] n.家具
whisky [ˈhwɪski] n.威士忌酒
suggest [səɡˈdʒest] v.暗示
shake [ʃeɪk] shook [ʃʊk] shaken [ˈʃeɪkən] v.摇动
accept [əkˈsept] v.接受

shake sb's head 摇头

be up for sale 待售
hear sb./sth. doing sth. 听到某人/某事正在做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
