#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 48 Did you want to tell me something
#+begin_verse
Why did the writer become very worried?

Dentists always ask questions when *it is impossible for you to answer*.
My dentist had just pulled out one of my teeth and had told me to *rest for a while*.
I tried to say something, but my mouth was full of cotton wool.
He knew I collected match boxes and asked me whether my collection was growing.
He then asked me how my brother was and whether I liked my new job in London.
In answer to these questions I either nodded or made strange noises.
Meanwhile, my tongue was busy searching out the hole where the tooth had been.
I suddenly felt very worried, but could not say anything.
When the dentist at last removed the cotton wool from my mouth,
	I was able to tell him that he had pulled out the wrong tooth.
#+end_verse
** expression
pull [pʊl] v.拔
cotton [ˈkɑt(ə)n] wool [wʊl] (羊毛棉)药棉
collect [kəˈlekt] v.搜集
collection [kəˈlekʃ(ə)n] n.收藏品,收集品
nod [nɑd] v.点头
meanwhile [ˈminˌhwaɪl] adv.同时

private collection 私人收藏

It is impossible for sb. to do 做某事对某人来说是不可能的
... rest for a while 稍作休息


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
