#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 49 The end of a dream
#+begin_verse
How did the dream end?

*Tired of sleeping* on the floor,
	a young man in Teheran *saved up for years to buy* a real bed.
*For the first time in his life*,
	he became the proud owner of a bed which had springs and a mattress.
Because the weather was very hot,
	he carried the bed on to the roof of his house.
He slept very well for the first two nights,
	but on the third night, a storm blew up.
*A gust of wind swept* the bed off the roof and sent it crashing *into the courtyard* below.
The young man did not wake up until the bed had struck the ground.
Although the bed *was smashed to pieces*, the man was miraculously unhurt.
When he woke up, he was still on the mattress.
*Glancing at* the bits of wood and metal that lay around him,
	the man sadly picked up the mattress and carried it into his house.
After he had put it on the floor, he promptly *went to sleep* again.
#+end_verse
** expression
tired [ˈtaɪəd] adj.厌烦的
real [ˈriːəl; rɪəl] adj.真正的
owner [ˈəʊnə(r)] n.主人 own v.拥有
spring [sprɪŋ] n.弹簧
mattress [ˈmætrəs] n.床垫
gust [ɡʌst] n.一阵风
sweep [swiːp] swept [swept] swept v. 扫,刮
courtyard [ˈkɔːtjɑːd] n.院子
smash [smæʃ] v.碰碎,摔碎
miraculously [mɪˈrækjələsli] adv.奇迹般地
unhurt [ʌnˈhɜːt] adj.没有受伤的
glance [ɡlɑːns] v.扫视
promptly [ˈprɒmptli] adv.迅速地

get/be tired of sth./doing sth. 对某事/做某事感到厌倦
A gust of wind swept ... 一阵风吹过……
in the courtyard 在院子里
smash sth. to pieces 把某物粉碎
glance at sth. 扫一眼……

--------------------!!!
分词作状语 没找到部分被动
1. (not) doing
	 主动进行/主动一般
	 (being) (not) + adj.
2. done
	 被动一般/被动完成/主动完成(少)
3. having done
	 主动完成(发生在主句之前)
	 having been + adj. (主句之前的状态)
4. having been done 在N2-69课
	 主动完成被动(发生在主句之前)

save up for year to do sth. 攒一年的钱做某事
for the first time in sb's life 某人一生中第一次
go to sleep 入睡



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
