#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 50 Taken for a ride
#+begin_verse
Why did the writer not get off the bus at Woodford Green?

I love travelling in the country, but I don't like losing my way.
I went on an excursion recently, but my trip took me longer than I expected.
'I'm going to Woodford Green,' I said to the conductor as I got on the bus,
	'but I don't know where it is.'
'I'll tell you where to get off,' answered the conductor.
I sat in the front of the bus to get a good view of the countryside.
After some time, the bus stopped.
Looking round, I realized with a shock that I was the only passenger left on the bus.
'You'll have to get off here,' the conductor said. 'This is as far as we go.'
'Is this Woodford Green?' I asked.
'Oh dear,' said the conductor suddenly. 'I forgot to put you off.'
'It doesn't matter,' I said. 'I'll get off here.'
'We're going back now,' said the conductor.
'Well, in that case, I *prefer to stay* on the bus,' I answered.
#+end_verse
** expression
ride [raɪd] n.旅行
excursion [ɪkˈskɜrʒ(ə)n] n.远足
conductor [kənˈdʌktər] n.售票员
view [vju] n.景色

--------------------
do/does
am/is/are+doing
--------------------
prefer
	- prefer to do sth. = prefer doing sth. = I'd prefer to do sth
	- prefer a to b  &  prefer doing a to doing b
	- prefer to do a rather than (do) b.  &  I'd prefer to do a. rather than (do) b.



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
