#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 52 A pretty carpet

#+begin_verse
What is the writer's carpet made of?

We have just moved into a new house and I have been working hard all morning.
I have been trying to *get my new room in order*.
This has not been easy because I own over a thousand books.
*To make matters worse*, the room is rather small,
	so I have temporarily put my books on the floor.
At the moment, they cover *every inch of floor space*
	and I actually have to walk on them to get in or out of the room.
*A short while ago*, my sister *helped me to carry* one of my old bookcases up the stairs.
She went into my room and got a big surprise when she saw all those books on the floor.
'This is the prettiest carpet I have ever seen,' she said.
She *gazed at it* for some time then added, 'You don't need bookcases at all.'
'You can sit here *in your spare time* and read the carpet!'
#+end_verse
** expression
temporarily [ˈtemprərəli] adv.暂时地
inch [ɪntʃ] n.英寸(度量单位)
space [speɪs] n.空间
actually [ˈæktʃuəli] adv.实际上

every inch of sth. 每一寸的
That's actually a good idea 这确实是个好主意

--------------------
have been doing(不知持续与否):
	1. 过去进行的v.对现在有影响;
	2. 从过去持续(或重复!)到现在

get sth. in order 把某事整理好
To make matters worse... 使事情更糟糕,...
A short while ago... 不久之前
gaze at sth. 凝视某物
in sb's spare time... 在某人的业余时间
help sb. to do sth. 帮助某人做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
