#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 53 Hot snake

#+begin_verse
What caused the fire?

At last firemen have put out a big forest fire in California.
Since then, they have been trying to *find out* how the fire began.
Forest fires are often caused by broken glass
	or by cigarette ends which people carelessly *throw away*.
Yesterday the fireman examined the ground carefully, but were not able to find any broken glass.
They were also quite sure that a cigarette end did not start the fire.
This morning, however, a fireman accidentally *discovered the cause*.
He noticed *the remains of a snake*
	which was wound round the *electric wires* of a 16,000-volt power line.
In this way, he was able to *solve the mystery*.
The explanation was simple but very unusual.
A bird had snatched up the snake from the ground and then dropped it on to the wires.
The snake then wound itself round the wires.
When it did so, it sent sparks down to the ground and these immediately started a fire.
#+end_verse
** expression
hot [hɒt] adj.带电的,充电的
fireman [ˈfaɪəmən] n.消防队员
cause [kɔːz] v.引起 n.原因
examine [ɪɡˈzæmɪn] v.检查
accidentally [ˌæksɪˈdentəli] adv.意外地,偶然地
remains [rɪˈmeɪnz] n.尸体,残骸
wire [ˈwaɪə(r)] n.电线
volt [vəʊlt] n.伏特(电压单位)
power line [ˈpaʊə laɪn] 电力线
solve [sɒlv] v.解决
mystery [ˈmɪst(ə)ri] n.谜
snatch [snætʃ] v.抓住
spark [spɑːk] n.电火花

electrical wire / electric wire 电线
discover a cause 发现原因
the remains of a snake 蛇的残骸
solve + problem/mystery 解决问题/谜团
remain mystery 保持谜

--------------------
did
have done
have been doing

find out 发现
throw away 丢弃



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
