#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 53 Hot snake

#+begin_verse
What caused the fire?

At last firemen have put out a big forest fire in California.
Since then, they have been trying to *find out* how the fire began.
Forest fires are often caused by broken glass
	or by cigarette ends which people carelessly *throw away*.
Yesterday the fireman examined the ground carefully, but were not able to find any broken glass.
They were also quite sure that a cigarette end did not start the fire.
This morning, however, a fireman accidentally *discovered the cause*.
He noticed *the remains of a snake*
	which was wound round the *electric wires* of a 16,000-volt power line.
In this way, he was able to *solve the mystery*.
The explanation was simple but very unusual.
A bird had snatched up the snake from the ground and then dropped it on to the wires.
The snake then wound itself round the wires.
When it did so, it sent sparks down to the ground and these immediately started a fire.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
