#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 55 Not a gold mine
#+begin_verse
What did the team find?

Dreams of finding lost treasure almost *came true* recently.
A new machine called 'The Revealer' has been invented
	and it has *been used to detect* gold which has been buried in the ground.
The machine was used *in a cave* *near the seashore*
	where -- it is said - pirates used to hide gold.
The pirates would often bury gold in the cave and then fail to collect it.
*Armed with the new machine*, a search party went into the cave hoping to find buried treasure.
The leader of the party was examining the soil near the entrance to the cave
	when the machine showed that there was gold under the ground.
Very excited, the party dug a hole two feet deep.
They finally found a small gold coin which was almost worthless.
The party then searched the whole cave thoroughly
	but did not find anything except an empty tin trunk.
In spite of this,
	many people *are confident that* 'The Revealer' may reveal *something of value* *fairly soon*.
#+end_verse
** expression
gold [ɡəʊld] n.金子
mine [maɪn] n.矿
treasure [ˈtreʒə(r)] n.财宝
revealer [rɪˈvi:lə] n.探测器
invent [ɪnˈvent] v.发明
detect [dɪˈtekt] v.探测
bury [ˈberi] v.埋藏
cave [keɪv] n.山洞
seashore [ˈsiːʃɔː(r)] n.海岸
pirate [ˈpaɪrət] n.海盗
arm [ɑːm] v.武装
soil [sɔɪl] n.泥土
entrance [ˈentrəns] n.入口
finally [ˈfaɪnəli] adv.最后
worthless [ˈwɜːθləs] adj.毫无价值的
thoroughly [ˈθʌrəli] adv.彻底地
trunk [trʌŋk] n.行李箱
confident [ˈkɒnfɪdənt] adj.有信心的
value [ˈvæljuː] n.价值

own + a gold mine 拥有一座金矿
a treasure map 藏宝图
in a cave 在山洞里
near/to the seashore 靠近/靠近海岸
pirate stories 海盗的故事
arm sb./sth. with sth. 用某物武装某人
sb. be armed with sth. 某人被某物武装
in dry soil 在干燥的土壤中
find / miss + entrance 找到/错过+入口
You're worthless. 你一文不值
I'm not worthless.  我不是一文不值
car trunk 汽车后备箱
sb. be confident that ... + 句子 某人确信……
something of value 有价值的东西

--------------------
would do VS used to do
	- 过去状态只用used to do
	- used to do包含现在不发生了
	- used to do讨论过去习惯行为(不重要)
where & whose 引导的定语从句

dreams come true... 梦想成真
be used to do sth. 被用于做某事
fairly soon ... 很快……
I'm fairly certain that +句子 我很确定
I'm fairly confident that + 句子 我很确信



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
