#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 57 Can I help you, madam?
#+begin_verse
Did the woman get what she wanted?

A woman in jeans stood at the window of an expensive shop.
Though she hesitated for a moment,
	she finally went in and *asked to see* a dress that was in the window.
The assistant who served her did not like the way she was dressed.
Glancing at her scornfully, he told her that the dress was sold.
The woman walked out of the shop angrily and decided to punish the assistant next day.
She returned to the shop the following morning *dressed in* a fur coat,
	with a handbag in one hand and a long umbrella in the other.
After *seeking out* the rude assistant, she asked for the same dress.
Not realizing who she was, the assistant *was eager to serve* her this time.
With great difficulty, he climbed into the shop window to get the dress.
As soon as she saw it, the woman said she did not like it.
She enjoyed herself making the assistant bring almost everything in the window
	before finally buying the dress she had first asked for.
#+end_verse
** expression
madam [ˈmædəm] n.太太,夫人
jeans [dʒiːnz] n.牛仔裤
hesitate [ˈhezɪteɪt] v.犹豫,迟疑
serve [sɜːv] v.接待(顾客)
scornfully [ˈskɔːnfəli] adv.轻蔑地
punish [ˈpʌnɪʃ] v.惩罚
fur [fɜː(r)] n.裘皮
eager [ˈiːɡə(r)] adj.热切的,热情的

hesitate to do sth. 犹豫做某事
be eager to do sth. 渴望做某事
ask/laugh/look at/ said + scornfully 轻蔑地问/笑/看/说
look down on sb. 看不起某人

--------------------
the way that/in which(可省略) + ...: 特殊的定语从句,从句修饰the way
	1. The assistant who served her did not like the way she was dressed.
	2. I don't like the way (that) you talk to me.
	3. We want to know the way (in which) you learn new words.

ask to do sth. 请求做某事
be dressed in ... 穿着
seek out 寻找并找到
make sb. do sth. 使(迫使)某人做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
