#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 61 Trouble with the Hubble
#+begin_verse
What is the special importance of a telescope in space?

The Hubble telescope was launched into space by NASA on April 20, 1990
	at a cost of over a billion dollars.
*Right from the start* there was trouble with the Hubble.
The pictures it sent us were very disappointing
	because its main mirror was faulty.
NASA is now going to put the telescope right,
	so it will soon be sending up four astronauts to repair it.
The shuttle Endeavour will be taking the astronauts to the Hubble.
A robot-arm from the Endeavour will grab the telescope
	and hold it while the astronauts make the necessary repairs.
Of course, the Hubble is above the earth's atmosphere,
	so it will soon be sending us the clearest pictures of the stars
		and distant galaxies that we have ever seen.
The Hubble will tell us a great deal about the age and size of the universe.
By the time you read this,
	the Hubble's eagle eye will have sent us thousands and thousands of wonderful pictures.
#+end_verse
** expression
Hubble [hʌb(ə)l] n.哈勃
telescope [ˈteləˌskoʊp] n.望远镜
launch [lɔntʃ] v.发射
space [speɪs] n.空间
NASA [ˈnæsə] n. National Aeronautics and Space Administration
billion [ˈbɪljən] n.10亿
faulty [ˈfɔlti] adj.有错误的
astronaut [ˈæstrənɔːt] n.宇航员
shuttle [ˈʃʌt(ə)l] n.航天飞机
Endeavour [ɪn'devər] n."奋进"号
robot-arm [ˈroʊˌbɑt] [ɑrm] n.机器手
grab [ɡræb] v.抓
atmosphere [ˈætməˌsfɪr] n.大气层
distant [ˈdɪstənt] adj.遥远的
galaxy [ˈɡæləksi] n.星系
universe [ˈjunɪvərs] n.宇宙
eagle [ˈɪɡ(ə)l] eye 鹰眼

grab a beer/coffee 喝杯啤酒/咖啡

--------------------
will be doing
will have done
will have been doing: 动作持续(重复)到将来 ?

right from the start 从一开始



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
