#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 62 After the fire
#+begin_verse
What was the danger to the villagers after the fire?

Firemen had been fighting the forest fire for nearly three weeks
	before they could *get it under control*.
*A short time before*, great trees had covered the countryside *for miles around*.
Now, smoke still rose up from the warm ground over the desolate hills.
Winter was coming on and the hills threatened the surrounding villages with destruction,
	for heavy rain would not only wash away the soil
		but would cause serious floods as well.
When the fire had at last been put out,
	the forest authorities ordered several tons of a special type of grass-seed
		which would grow quickly.
The seed was sprayed over the ground in huge quantities by aeroplanes.
The planes had been planting seed for nearly a month when it began to rain.
By then, however, in many places the grass had already *taken root*.
*In place of* the great trees which had been growing there *for centuries*,
	patches of green had begun to appear in the blackened soil.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
