#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 63 She was not amused
#+begin_verse
Why did Jenny want to leave the wedding reception?

Jeremy Hampden has *a large circle of friends* and is very popular at parties.
Everybody *admires him for* his great *sense of humour*
	- everybody, that is, except his six-year-old daughter, Jenny.
Recently, one of Jeremy's *closest friends* asked him to *make a speech* *at a wedding reception*.
This is *the sort of* thing that Jeremy loves.
He prepared the speech carefully and went to the wedding with Jenny.
He had included *a large number of* funny stories in the speech and, of course, it was great success.
As soon as he had finished, Jenny told him she wanted to go home.
Jeremy was a little disappointed by this but he did as his daughter asked.
*On the way home*, he asked Jenny if she had enjoyed the speech.
To his surprise, she said she hadn't.
Jeremy asked her why this was so
	and	she told him that she did not like to see so many people laughing at him.
#+end_verse
** expression
circle [ˈsɜrk(ə)l] n.圈子
admire [ədˈmaɪr] v.赞美,钦佩
close [kloʊs] adj.亲密的
wedding [ˈwedɪŋ] n.婚礼
reception [rɪˈsepʃən] n.招待会
sort [sɔrt] n.种类

a large circle of friends 很大的朋友圈
admire sb. for sth./doing sth. 钦佩某人做某事
close friend 亲密的朋友
at the reception 在招待会上
what sort of/what kind of... 什么种类的
all sorts of/ all kinds of... 各种各样的

--------------------
as: in the way or manner that 按照...方式
	You'll do as I say and ask no questions.
like
as if
as though

sense of humour/humor 幽默感/幽默感
make a speech 发表演讲
a large number of ... 大量的+nc.
on the way home 在回家的路上



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
