#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 64 The Channel Tunnel
#+begin_verse
Why was the first tunnel not completed?

In 1858, a French engineer, Aime Thome de Gamond,
	arrived in England with a plan for a twenty-one-mile tunnel under the English Channel.
He said that it would *be possible to build* a platform in the centre of the Channel.
This platform would *serve as* a port and a railway station.
The Tunnel would be well-ventilated if tall chimneys were built *above sea level*.
In 1860, *a better plan was put forward* by an Englishman, William Low.
He suggested that a double railway-tunnel should be built.
This would *solve the problem of ventilation*,
	for if a train entered this tunnel, it would draw in fresh air behind it.
Forty-two years later a tunnel was actually begun.
If, at the time, the British had not feared invasion, it would have been completed.
The world had to wait almost another 100 years for the Channel Tunnel.
It was officially opened on March 7, 1994,
	finally connecting Britain to the European continent.
#+end_verse
** expression
tunnel [ˈtʌn(ə)l] n.隧道
port [pɔrt] n.港口
ventilate [ˈvent(ə)lˌeɪt] v.通风
chimney [ˈtʃɪmni] n.烟囱
sea	level [ˈlev(ə)l] 海平面
double [ˈdʌb(ə)l] adj.双的
ventilation [ˌvent(ə)lˈeɪʃ(ə)n] n.通风
fear [fɪr] v.害怕
invasion [ɪnˈveɪʒ(ə)n] n.入侵,侵略
officially [əˈfɪʃ(ə)li] adv.正式地
connect [kəˈnekt] v.连接
European [ˌjʊrəˈpiən] adj.欧洲的
continent [ˈkɑntɪnənt] n.大陆

in the tunnel 在隧道里
above/below sea level 高于/低于海平面
double check 仔细检查
Sb. fear that + 句子 某人担心

--------------------
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
suggest that ... (should) do ...

it is possible to do sth... 做某事是可能的
a serve as b: A当作B
solve the problem of a ... 解决…的问题
put forward a plan ... 提出一个计划



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
