#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 66 Sweet as honey!
#+begin_verse
What was 'sweet as honey' and why?

In 1963 a Lancaster bomber crashed on Wallis Island,
	a remote place in the South Pacific, a long way west of Samoa.
The plane wasn't too badly damaged,
	but *over the years*,	the crash was forgotten and the wreck remained undisturbed.
Then in 1989, twenty-six years after the crash,
	the plane was accidentally rediscovered in an aerial survey of the island.
By this time, a Lancaster bomber *in reasonable condition* was rare and *worth rescuing*.
The French authorities had the plane packaged and moved in parts back to France.
Now a group of enthusiast are going to have the plane restored.
It has four Rolls-Royce Merlin engines,
	but the group will need to have only three of them rebuilt.
Imagine their surprise and delight
	when they broke open the packing cases and found that the fourth engine was sweet as honey
		- still in perfect condition.
*A colony of bees* had *turned the engine into a hive* and it was totally preserved in beeswax!
#+end_verse
** expression
Lancaster [ˈlæŋkəstər] n.
bomber [ˈbɑmər] n.轰炸机
remote [rɪˈmoʊt] adj.偏僻的
Pacific [pəˈsɪfɪk] n.太平洋
damage [ˈdæmɪdʒ] v.毁灭
wreck [rek] n.残骸
rediscover [ˌridɪˈskʌvər] v.重新发现
aerial [ˈeriəl] adj.航空的
survey [ˈsɜrˌveɪ] n.调查
rescue [ˈreskju] v.营救
package [ˈpækɪdʒ] v.把...打包
enthusiast [ɪnˈθuziæst] n.热心人
restore [rɪˈstɔr] v.修复
imagine [ɪˈmædʒɪn] v.想象
packing case [ˈpækɪŋ] 包装箱
colony [ˈkɑləni] n.群
bee [bi] n.蜂
hive [haɪv] n.蜂房
preserve [prɪˈzɜrv] v.保护
beeswax [ˈbizˌwæks] n.蜂蜡

remote control 遥控
do a survey 进行调查
Can you imagine that? 你能想象吗?
It's hard to imagine. 这很难想象
A colony of bees 一群蜜蜂

--------------------
have sth. done = get sth. done: 1.使得某事被别人做;2.不幸的遭遇

over the years 多年来
in reasonable condition 在理想条件下
be worth doing... 值得做……
turn a into b. 把a变成b。



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
