#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 71 A famous clock
#+begin_verse
Has Big Ben ever gone wrong?

When you visit London,
	one of the first things you will see is Big Ben, the famous clock
		which can be heard *all over the world* on the BBC.
If the Houses of Parliament had not been *burned down* in 1834,
	the great clock would never have been erected.
Big Ben *takes its name* from sir Benjamin Hall
	who *was responsible for* the making of the clock
		when the new Houses of Parliament were being built.
It is not only of immense size, but is extremely accurate as well.
Officials from Greenwich Observatory have the clock checked twice a day.
On the BBC you can hear the clock
	when it is actually striking because microphones *are connected to* the clock tower.
Big Ben has rarely *gone wrong*.
Once, however, it failed to give the correct time.
A painter who had been working on the tower
	hung a pot of paint on one of the hands and slowed it down!
#+end_verse
** expression
parliament [ˈpɑrləmənt]: n.议会,国会
erect [ɪˈrekt]: v.建起
accurate [ˈækjərət]: adj.准确的
official [əˈfɪʃ(ə)l]: n.adj.官员,行政人员
Greenwich [ˈgrɪnɪdʒ]: n.
observatory [əbˈzɜrvəˌtɔri]: n.天文台
check [tʃek]: v.n.检查
microphone [ˈmaɪkrəˌfoʊn]: n.扩音器,麦克风
tower [ˈtaʊr]: n.塔

make it official: 使其正式化
double check: 复查
--------------------

all over the world: 全世界
burn down: 烧毁
take its name from: 以……命名
be responsible for: 对……负责
be connected to: 与……相连
go wrong: 出错



** DONE 单词造句
CLOSED: [2023-08-29 Tue 21:59]
parliament n.
erect v.
- Would you mind my erecting the tent by myself?
- I never enjoy erecting tents.
- The child who was only 5 years old managed to erect his camp.
- My wife insisted on erecting a gate in front of our house.
- We tried everything to prevent him from erecting the wall between his yard and ours.
accurate adj.
- I caught a sight of his watch, and I have to say it's accurate.
- It is no use pretending that the report is accurate.
- The poor reporter finished finding the accurate number.
- It is worth finding the accurate number.
- I am fairly certain that we did a accurate survey.
official n.adj. make it official
- It's hard to imagine that you have trouble with the officials.
- The official has been arrested after he removed the door from the man's house.
- The official became an expert at collecting stamps.
- The official trained his dog to press on buttons.
- The official pointed out that he deserves to be elected.
Greenwich n.
observatory n.
- Where's Tom? He has already gone to the observatory.
- If you were at the observatory right now, you would understand me.
- If you had been at the observatory at the time, you would have seen the drunk bowing.
- He spent the weekends at the observatory.
- The observatory has been burnt in 1980.
check v.n. double check
- Have you checked in the bathroom? I have checked everywhere.
- I'll double check that.
- I've checked all the thing in the box. Don't worry.
- Have you checked your key in your bag? Yes, I have.
- The girl began to check the room for her safety.
microphone n.
- He was being busy with the microphone all morning yesterday.
- After having caught sight of the microphone, he noticed that he had been listened to.
- The old gentleman taked the microphone clumsily.
- It's no use pretending that you haven't taken the microphone clumsily.
- The girl tried everything to avoid touching the dirty microphone.
tower n.
- The tower should have been closed this evening.
- The tower needn't have been opened this evening.
- The authorities claimed that because the tower had costed a lot of money, they will have it closed.
- The microphone is connected to the tower so that people could listen to on BBC.
- The worker managed to escape from the tower when the earthquake happened.

** DONE 反复听电影片段
CLOSED: [2023-08-29 Tue 21:36]
** DONE 习惯用法造句
CLOSED: [2023-08-29 Tue 22:16]
all over the world
- People all over the world saw that UFO last night.
- Did people all over the world see that UFO last night?
- When did people all over the would see that UFO.
- People taked part in the party from all over the world.
- There are many people who work for the company all over the world.
burn down
- He insisted on burning down the house.
- It's hard to imagine that he's pleased with burning down the tree.
- A car was burnt down and it held up the traffic.
- It's fortunate that the car isn't burnt down in the accident.
- His house was being burnt down when he was on the way home.
take its name from
- The machine takes its name from its inventor.
- Does the machine take its name from its inventor?
- Why does the machine take its name from a great man?
- The scientist fears that the street will not take its from him.
- The town takes its name from a captain, who had saved many people's lives in a flood.
be responsible for
- No matter what happened to the cat, you will be responsible for it.
- Three men were responsible for the drunk's safety.
- I'm responsible for my accomplishment.
- It occurred to me that you are the one who is responsible for the accident, not her.
- It's you who is responsible for all this.
be connected to
- Has the keyboard been conected to the computer right?
- The notice reminds me of that the bluetooth has already been connected to the computer.
- In spite of this, I am connected to my father in the village.
- She noticed that the microphone wasn't connected to the phone.
- It's no use pretending that you are connected to the people.
go wrong
- Don't feel sorry for me if anything goes wrong.
- Did anything still go wrong?
- If you hadn't won a prize for the competition, nothing wouldn't have gone wrong.
- He managed to prevent anything from going wrong.
- Suddenly, everything goes wrong.
** DONE 跟读至背诵
CLOSED: [2023-08-30 Wed 19:52]
** DONE Ask me if 写+读
CLOSED: [2023-08-30 Wed 20:02]
1. Big Ben is a famous clock.(What)
	 What is Big Ben?
2. It's in London.(Where)
		Where is it?
3. It's one of the first things a visitor sees. (What)
		What is it?
4. It can be heard all over the world.(Where)(Why)What)
		Where can it be heard?
		Why can it be heard all over the world?
		What can be heard all over the world?
5. You can hear it on the B.B.C.(How)
	 How can you hear it?
6. It's called after Sir Benjamin Hall.(Who)
	 Who is it called after?
7. He was responsible for making the clock.(What)Who)
	 What was he responsible for?
	 Who was responsible for making the clock?
8. The Houses of Parliament were burnt down in 1834.(What)(When)
	 What were burnt down in 1834?
	 When were the Houses of Parliament burnt down?
9. The clock was made when the new Houses of Parliament were being built.(When)
	 When was the clock made?
** DONE 摘要写作
CLOSED: [2023-08-30 Wed 20:11]
After the Houses of Parliament were burnt down in 1834,
	 Sir Benjamin Hall was made responsible for the construction of a huge clock,
		which became know as Big Ben.
Despite its immense size, it is very accurate,
	for officials from Greenwich Observatory have it checked twice a day.
The clock, which has rarely gone wrong,
	can be heard on the BBC when it is striking,
	because microphones ware connecteed to the clock tower.

** DONE tell the story 口语
CLOSED: [2023-08-30 Wed 20:01]

** Topics for discussion
- Describe a famous building you have visited and tell what you know of its history.
- Why is it necessary to have an international standard measure of time?
- How many foreign radio stations can you get on your radio?
	 Which do you listen to most frequently? Why?
