#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 72 A car called Bluebird
#+begin_verse
What mistake was made?

The great racing driver, Sir Malcolm Campbell, was the first man to drive at over 300 miles per hour.
He set up a new world record in September 1935 at Bonneville Salt Flats, Utah.
Bluebird, the car he was driving, had been specially built for him.
It was over 30 feet in length and had a 2,500-horsepower engine.
Although Campbell reached a speed of over 304 miles per hour,
	he *had great difficulty in controlling* the car because a tyre burst during the first run.
After his attempt,
	Campbell *was disappointed to learn that* his average speed had been 299 miles per hour.
However, a few days later, he was told that a mistake had been made.
His average speed had been 301 miles per hour.
Since that time, racing drivers have reached speeds over 600 miles an hour.
*Following in his father's footsteps* many years later,
	Sir Malcolm's son, Donald, also set up a world record.
Like his father, he was driving a car called Bluebird.
#+end_verse
** expression
racing [ˈreɪsɪŋ] n.竞赛
per [pɜr] prep.每
Utah ['ju:ta:] n.犹他(美国州)
horsepower [ˈhɔrsˌpaʊr] n.马力
burst [bɜː(r)st] v.爆裂
average [ˈæv(ə)rɪdʒ] adj.平均的
footstep [ˈfʊtˌstep] n.足迹

burst into tears 突然哭起来
follow in sb't footsteps 效法某人
--------------------
have difficulty in doing sth. 做某事有困难
be disappointed to learn that 某人了解到...很失望



** DONE 单词造句
CLOSED: [2023-08-30 Wed 21:29]
racing n.
- No one could account for the fact that a racing driver often risks his life like this.
- A racing driver is always busy with competitions.
- The racing driver has been burnt down, I feel sorry for him.
- Many girls are eager to look on the handsome racing driver.
- You should have a more relaible racing car, this is always breaking down.
per prep.
- I'll give you 11 dollars cash per night.
- The rooms in our hotel are twenty dollars per night, they are no higher in our town.
- The blue-collar workers were paid per day.
- The ticket of the Disney land is only twenty dollars per person.
- You shouldn't have drive at over 30 miles per hour.
Utah n.
horsepower n.
- A racing car has a 2,500-horsepower engine.
- He has difficulty in driving a racing car having a 2,500-horsepower engine.
- I am unaware of that the car has a 2,500-horsepower engine.
- I usedn't to know anything about horsepower.
- After surfing the Internet, I learnt a little bit about horsepower.
burst v. burst into tears
- I can't find something which makes you burst into tears.
- He suddenly bursted into tears.
- I used to burst into tears for a tragic story.
- The moment I heard the tragic story, I bursted into tear.
- I no sooner bursted into tear than I had heard the story.
average adj.
- She is the cleverest student in the class, the rest are average.
- She often takes a ride at a average speed.
- Mr Leo turned his attention to the average grade of his students.
- He is an average student in the school.
- An average car usually has a 2,500 horsepower engine.
footstep n. follow in sb't footsteps
- I'm not following in my father's footsteps.
- Rachel is sensitive about following in her mother's footsteps.
- At the time, I was unaware of the footsteps in my garden.
- The boy is instructed to following in his father footsteps.
- However, he refused to following his father's footstep in the edge of the forest.

** DONE 反复听电影片段
CLOSED: [2023-08-30 Wed 21:01]

** DONE 习惯用法造句
CLOSED: [2023-08-30 Wed 21:35]
have difficulty in doing sth.
- I have difficulty in getting close to the cat.
- I have difficulty in accepting criticism.
- The bull have difficulty in charging at the matador.
- I have difficulty in having a good sight of the view.
- I have difficulting in passing the exam.
be disappointed to learn that
- As a citizen, I am disappointed to learn that the thief has escaped.
- As a citizen, I am disappointed to learn that the city is out of control.
- I am disappointed to learn that the grasses has taken root.
- I am disappointed to learn that my son was following in my footsteps.
- I am disappointed to learn that he lost the source of information.
** DONE 跟读至背诵
CLOSED: [2023-09-01 Fri 20:49]
** DONE Ask me if 写+读
CLOSED: [2023-09-01 Fri 21:11]
1. Sir Malcolm Campbell was the first man to drive at over 300 m.p.h.(Who)
	 Who was the first man to drive at over 300 m.p.h?
2. He set up a new world record in September 1935.(When)(Who)
		When did he set up a new world record?
		Who set up a new world record in September 1935?
3. He was racing at Bonneville Salt Flats, Utah.(Where)(When)
		Where was he racing?
		When was he racing at Bonneville Salt Flats, Utah?
4. His car was called Bluebird.(What)(Whose)
		What was his car called?
		Whose car was called Bluebird?
5. It had been specially built for him.(Who)
		Who had it been specially built for?
6. It was over 30 feet long.(How long)
	 How long was it?
7. It had a 2,500 horsepower engine.(What kind of)
	 What kind of engine did it have?
8. Campbell's top speed was 304 miles per hour.(What)(Whose)
	 What was Campbell's top speed?
	 Whose top speed was 304 miles per hour?
9. A tyre burst on the first run.(When)
	 When did a tyre burst?
** DONE 摘要写作
CLOSED: [2023-09-01 Fri 21:09]
Sir Malcolm Campbell set up a land-speed record in 1935
	 driving a car called Bluebird, which had been specially built for him.
His average speed was incorrect declared to be 299 miles per hour,
	 but this mistake was corrected later.
He had averaged 301 miles an hour.
Years later, his son, Donald, also broke a record and his car was also called Bluebird.
** DONE tell the story 口语
CLOSED: [2023-09-01 Fri 21:09]
** Topics for discussion
- Do you enjoy travelling at great speed? Why/Why not?
- No one can use a car like Bluebird on theroad, so what is the purpose in building it?
- In the modern world, 'speed' sometimes seems to be all important.
		Do you think this is a good or a bad thing?
		Should we try to slow down a little? Why/Why not?
