#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 76 April Fool's Day
#+begin_verse
What was the joke?

'To end our special news bulletin,' said the voice of the television announcer,
	'we're going over to the macaroni fields of Calabria.
Macaroni has been grown in this area for over six hundred years.
Two of the leading growers, Giuseppe Moldova and Riccardo Brabante, tell me
	that they have been expecting a splendid crop this year
		and harvesting has begun earlier than usual.
Here you can see two workers who,
	between them, have just finished cutting three cartloads of golden brown macaroni stalks.
The whole village has been working day and night
	gathering and threshing this year's crop before the September rains.
On the right, you can see Mrs. Brabante herself.
She has been helping her husband for thirty years now.
Mrs .Brabante is talking to the manager of the local factory where the crop is processed.
This last scene shows you what will happen *at the end of the harvest*:
	the famous Calabrian macaroni-eating competition!
Signor Fratelli, the present champion, has won it every year since 1991.
And that ends our special bulletin for today, Thursday, April 1st.
We're now going back to the studio.'
#+end_verse
** expression
fool [ful] n.傻瓜
bulletin [ˈbʊlətɪn] n.新闻简报
announcer [əˈnaʊnsər] n.(电视,电台)播音员
macaroni [ˌmækəˈroʊni] n.通心面,空心面条
leading [ˈlidɪŋ] adj.主要的 + cause(s)
grower [ˈɡroʊr] n.种植者
splendid [ˈsplɛndid] adj.极好的 + idea/example/view/garden
stalk [stɔk] n.梗
gather [ˈɡæðər] v.收庄稼 thresh v.打(庄稼)
process [prəˈses] v.加工
Signor ['siːnjɔː] n.(意大利语)先生
present [ˈprezənt] adj.目前的
champion [ˈtʃæmpiən] n.冠军
studio [ˈstudiˌoʊ] n.播音室

on the bulletin board 在布告栏上
leading cause of ...的主要原因
What a splendid/brilliant idea! 多棒的主意啊!
--------------------
at the end of ... 在……结束时



** words
fool [ful] n.傻瓜
bulletin [ˈbʊlətɪn] n.新闻简报
announcer [əˈnaʊnsər] n.播音员
macaroni [ˌmækəˈroʊni] n.通心粉
leading [ˈlidɪŋ] adj.主要的
grower [ˈɡroʊr] n.种植者
splendid [ˈsplɛndid] adj.极好的
stalk [stɔk] n.梗
gather [ˈɡæðər] v.收庄稼
thresh [θreʃ] v.打(庄稼)
process [prəˈses] v.加工
Signor ['siːnjɔː] n.先生
present [ˈprezənt] adj.目前的
champion [ˈtʃæmpiən] n.冠军
studio [ˈstudiˌoʊ] n.播音室

** DONE 单词造句
CLOSED: [2023-09-11 Mon 21:24]
fool n.
- "You fool", Rachel sneered at Ross.
- You fool, get out of here.
- You fool, in case you can't read the notice.
- Ross and Rachel always play joke on each other on April Fool's day.
- Thank you for your coming there on April Fool's day.
bulletin  n. on the bulletin board
- A notice on the bulletin board says: Don't hitchhike to Paris.
- The bulletin board were covered with the names of the students who played truant from school.
- He read the photographs on the bulletin board over and over again.
- He was disappointed to learn that his name didn't appear on the bulletin board.
- If we made it official, it might be put on the bulletin board.
announcer n.
- All announcers in Beijing have been put to shame by Ross.
- The announcer insists on staying out of the limelight after work.
- The announcer had no sooner made himself comfortable
		than he started to tell stories about pirate.
- It's the announcer who is responsible for the accident, not the editor.
- The announcer tried to get close to the lions once more.
macaroni n.
- If you hadn't gone wrong, the macaroni would have been delicious.
- You needn't have eaten the macaroni that has grown rotten.
- My mom is always being busy with cooking macaroni.
- Let's suppose that you're eating macaroni when someone talk to you.
- I'm instructed to eat macaroni at breakfast, dinner, and lunch every day.
leading adj. leading cause of
- Smoking is one of leading causes of your impotence.
- Sitting for a long time is one of leading causes of your back pain.
- Making that stupid remark is one of leading causes of your fail.
- My father became a leading expert at volcanoes.
- You should have inquired about the leading causes of your impotence.
grower n.
- Sensitive about accepting criticism, the vegetable grower got very angry.
- Instead of a worker, he choose to become a vegetable grower.
- I am not allowed to be a vegetable grower by my father.
- The vegetable grower managed to cut down the crop in three days.
- The vegetable grower avoided entering for the competition.
splendid adj. + idea/example/view/garden What a splendid/brilliant idea!
- You decided to work hard. What a splendid idea!
- I was wondered how to make a splendid garden.
- It's hard to imagine that we met in a splendid garden.
- I'm dreaming of working for a splendid company.
- It's fortunate that my house has a splendid company.
stalk n.
- He managed to collect a parcel of corn stalks.
- The boxes are full of corn stalks.
- Pigs in China used to eat a lot of corn stalks.
- To my surprise, the pig tried to bite the corn stalk.
- The Chinese farmar has smashed the corn stalk to pieces in the courtyard.
process v.
- The young child was glancing at the processed food.
- He has wrote out of a long list of processed food full of salts and sugar.
- It was obvious that the processed food is full of fat and sugar.
- He has forbidden his children to eat any processed food.
- We often buy the processed food when we go camping.
Signor n.
present adj.
- At present, the baby elephant is holding up the line.
- At present, we're waiting in line in the supermarket.
- At present, we have double checked the macaroni.
- It is impossible for us to arrive at present on such short notice.
- At present, we have to put forward the plan.
champion n.
- The champion was able to solve the problem of broken car.
- Unaware of his rude behavior, the champion made that stupid remark.
- After having become the champion, she bursted into tears.
- Following in his father's footsteps, he becomes a football champion.
- The champion has difficulty in accepting criticism.
studio n.
- The police who first arrive on the scene carried a parcel to the studio.
- Thousands and thousands of wonderful photographs were taked in the studio.
- Ross has just bought a new studio and can't have a telephone for it.
- He was asked to get out of the studio.
- It's no use pretending that you had been in the studio.
** 反复听电影片段
** DONE Pattern Drill 写+读
CLOSED: [2023-09-11 Mon 22:33]
-
		1T: grow a beard
		S1: He's growing a beard.
		S2: Whatever for? He hasn't grown one before, has he?
	 - have an operation
		 He's having an operation.
		 Whatever for? He hasn't had one before, has he?
	 - give a speech
		 He's giving a speech.
		 Whatever for? He hasn't given one before, has he?
	 - write a book
		 He's writing a book?
		 Whatever for? He hasn't written one before, has he?
	 - buy a dog
		 He's buying a dog?
		 Whatever for? He hasn't bought one before, has he?
-
	 2T: his beard - grow
	 S1: What do you think of his beard?
	 S2: It's all right, but he hasn't been growing it for long, has he?
	 - my English - learn
		 What do you think of my English?
		 It's all right, but you haven't been learning it for long, have you?
	 - her car - drive
		 What do you think of her car?
		 It's all right, but she hasn't been driving it for long, has she?
	 - his glasses - wear
		 What do you think of his glasses?
		 It's all right, but he hasn't been wearing it for long, has he?
	 - my camera - use
		 What do you think of my camera?
		 It's all right, but you haven't been using it for long ,have you?
-
		3T: telephone me
		S1: He's been telephoning me all morning.
		S2: Don't exaggerate! He's only telephoned you twice.
	 - interrupt me
		 He's been interrupting me all morning.
		 Don't exaggerate! He's only interrupted you twice.
	 - repeat himself
		 He's been repeating himself all morning.
		 Don't exaggerate! He's only repeating himself twice.
	 - shout at me
		 He's been shouting at me all morning.
		 Don't exaggerate! He's only shouted at you twice.
	 - rush in and out
		 He's been rushing in and out all morning.
		 Don't exaggerate! He's only rushed in and out twice.
-
		4T: read magazines
		S1: Have you been reading magazines all the time I've been away?
		S2: No, I haven't read any since you left.
	 - write letters 
		 Have you written letters all the time I've been away?
		 No, I haven't written any since you left.
	 - do housework 
		 Have you done housework all the time I've been away?
		 No, I haven't done any since you left.
	 - listen to music 
		 Have you listened to music all the time I've been away?
		 No, I haven't listened any since you left.
	 - paint pictures 
		 Have you painted pictures all the time I've been away?
		 No, I haven't painted any since you left.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-11 Mon 21:24]
at the end of ...
- At the end of this week, I succeeded in hitchhiking to NewYork.
- At the end of the party, we all taked precautions so that we wouldn't get a cold.
- Why don't we dance at the end of the party?
- At the end of the year, he covered the bulletin board with messages.
- He hadn't broken his world record at the end of the century.
** DONE 跟读至背诵
CLOSED: [2023-09-12 Tue 20:48]
** DONE Ask me if 写+读
CLOSED: [2023-09-12 Tue 20:57]
1. It was Thursday, April 1st. What day
	 What was it?
2. There was a special news bulletin on television. What/When
		What was there on television?
		When was there a special new bulletin on television?
3. It ended with a programme about macaroni growing. What ... with
		What did it end with?
4. Viewers were shown the macaroni fields of Calabria. What
		What were viewers shown?
5. Macaroni has been grown there for over six hundred years. How long/Where
		How long has macaroni been grown there?
		Where has macaroni been grown for over six hundred years?
6. The leading growers have been expecting a splendid crop this year. What/Who
	 What have the leading growers been expecting this year?
	 Who have been expecting a splendid crop this year?
7. The film showed two workers. How many
	 How many workers did the film show?
8. Everyone has been working day and night. How hard/Why/Who
	 How hard has everyone been working?
	 Why has everyone been working day and night?
	 Who has been working day and night?
** DONE 摘要写作
CLOSED: [2023-09-12 Tue 21:27]
At end of new bulletin, the television announcer showed viewers fields in Calabria
	where the macaroni had been growned for six hundred years.
The harvesting had begun earlier this year
	and the whole village had been working hard before September rains.
The crop was processed in the local factory.
After harvest, it will happen the famous competition
	which Signor Fratelli had won every year since 1991.
It was end of bulletin on April 1st.

To end the special new bulletin,
	the television announcer showed viewers the macaroni fields of Calabria,
	where macaroni has been grown for over six hundred years.
Harvesting has begun earlier this year
	and the whole village has been working hard,
	gathering and threshing the crop befor the September rains.
The crop was processed in the local factory.
After the harvest, the famous Calabrian macaroni-eating competition,
	which Signor Fratelli has won every year since 199- will take place.
That ended the news bulletin for April 1st.

To end the special news bulletin,
	the television announcer showed viewers the macaroni fields of Calabria.
Macaroni has been grown here for over six hundred years.
This year harvesting has begun earlier.
The whole village has been working hard,
	gathering and threshing the crop befor the September rains,
	so that the crop was processed in the local factory.
After the harvest, the famous Calabria macaroni-eating competition will take place.
Signor Fratelli has won this competition every year since 1991.
With that ended the news bulletin on April 1st.
	
To end the news bulletin,
	the television announcer showed viewers the fields of Calabria.
Here, macaroni has been grown for over six hundred years.
This year, harvesting has begun earlier.
The whole village has been working hard,
	gathering and threshing the crop befor the September rains
	so that the crop was processed in the local factory.
After the harvest, the famous macaroni-eating competition will be held.
This has been won by Signor Fratelli every year since 1991.
With that, the news bulletin for April 1st ended.

** DONE tell the story 口语
CLOSED: [2023-09-12 Tue 21:27]
** Topics for discussion
