#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 81 Escape
#+begin_verse
Why did the prisoner attack the driver?

When he had killed the guard, the prisoner of war quickly dragged him into the bushes.
Working rapidly in the darkness, he soon *changed into* the dead man's clothes.
Now, dressed in a blue uniform and with a rifle over his shoulder,
	the prisoner marched boldly *up and down* in front of the camp.
He could hear shouting in the camp itself.
Lights were blazing and men were running here and there:
	they had just *discovered that* a prisoner had escaped.
At that moment, a large black car with four officers inside it, stopped at the camp gates.
The officers got out and the prisoner *stood to attention* and saluted as they passed.
When they had gone, the driver of the car came towards him.
The man obviously wanted to talk.
He was rather elderly with grey hair and clear blue eyes.
The prisoner felt sorry for him, but there was nothing else he could do.
As the man came near,
	the prisoner *knocked him to the ground* *with a sharp blow*.
Then, jumping into the car, he drove off as quickly as he could.
#+end_verse
** expression
prisoner [ˈprɪz(ə)nər] n.囚犯
bush [bʊʃ] n.灌木丛
rapidly ['ræpɪdli] adv.迅速地
uniform [ˈjunɪˌfɔrm] n.制服
rifle [ˈraɪf(ə)l] n.来福枪,步枪
shoulder [ˈʃoʊldər] n.肩
march [mɑrtʃ] v.行进
boldly ['bəʊldli] adv.大胆地
blaze [bleɪz] v.闪耀
salute [səˈlut] v.行礼
elderly [ˈeldərli] adj.n.上了年纪的
grey [ɡreɪ] adj.灰白的
sharp [ʃɑrp] adj.猛烈的 blow n.打击

grow/change/move... + rapidly 成长/改变/移动……+ 快速地
with a sharp blow 用一记猛击
--------------------
change into ... 换上...(衣服)
up and down ... 上上下下
sb. discovered that 某人发现
stand to attention 立正
knock him to the ground 击打某人在地


** words
prisoner [ˈprɪz(ə)nər] n.囚犯
bush [bʊʃ] n.灌木丛
rapidly ['ræpɪdli] adv.迅速地
uniform [ˈjunɪˌfɔrm] n.制服
rifle [ˈraɪf(ə)l] n.来福枪,步枪
shoulder [ˈʃoʊldər] n.肩
march [mɑrtʃ] v.行进
boldly ['bəʊldli] adv.大胆地
blaze [bleɪz] v.闪耀
salute [səˈlut] v.行礼
elderly [ˈeldərli] adj.上了年纪的
grey [ɡreɪ] adj.灰白的
sharp [ʃɑrp] adj.猛烈的
blow [bloʊ] n.打击

** DONE 单词造句
CLOSED: [2023-09-21 Thu 20:26]
prisoner n.
- When he realized that the prisoner had gone to the college, he felt frightened.
- There are two hundreds prisoner in all.
- The prisoner managed to hitchhike to Paris.
- The prisoner made no effort to escape from there.
- After the prisoner arrested, everything returned to normal.
bush n.
- I was curious to find out whether there was any person in the bush.
- He has made every effort to plant the bushes.
- He was given satisfaction from planting the bushes.
- The prisoner got the nerve to cross the bushes.
- The player likes hiding in the bushes.
rapidly adv. grow/change/move... + rapidly
- No matter what you do, the world would change rapidly.
- My cousin grows up so rapidly that he went to college last year.
- The flight attendant was moving rapidly and lost her temper.
- If you keep moving so rapidly, you will lose your weight.
- She was sure that a puma was moving rapidly in the bushes.
uniform n.
- The boy who is dressed in a school uniform has just lit a cigarette.
- His parents urged him to change into the school uniform.
- The uniform is so expensive that we couldn't afford to it.
- The security guard offered him a uniform and asked him to get out of here.
- I have lost my appetite because of my uniform which was covered with a body.
rifle n.
- He was used to being armed with a rifle in the army.
- He was given satisfaction from succeeding in buying a rifle.
- Armed wit a rifle, she has the nerve to ask for meat.
- Who entitled you to carry a rifle to the exhibition?
- I had to calm my nerve, for he was armed with a rifle.
shoulder n.
- This proved to be a lamb shoulder.
- At the end of the harvesting, he hurted his shoulder careless.
- It says on the bulletin board. A boy who played truant from school has hurted his shoulder.
- The actor stayed out of the limelight, for he hurted his shoulder.
- Don't be too hard on us and stop touching my shoulder.
march v.
- The baby elephant accompanied by four pretty girls marched along the main street.
- The flight attendant marched out of the plane.
- The solders are marching along the avenue right now.
- The solders will be marching along the street in 20 minutes.
- The girl marched out of the door and bursted into tears.
boldly adv.
- She finally rode a bike boldly over and over again.
- He came there and spoke boldy in front of the crowd.
- He got close to the puma at large boldly.
- The woman marched out of the manager's office boldly.
- The drunker was charging at the bull boldly.
blaze v.
- In the end, the lights were successfully blazing again.
- When the light was blazing, the prisoner immediately hid into the bushses.
- He was delight that the lights were blazing again.
- After the lights were blazing over and over again, he lost his temper.
- Though the sun is blazing, everyone in the village is working hard for the crop.
salute v.
- Even though he is Stephen Hawking, he still have to salute the leader in China.
- It's said that Stephen Hawking would have to salute the leader in Chian.
- When the mummy was cut open, all the doctors saluted it.
- He saluted the emperor and survived this event.
- He was disappointed to find out that his still had to salute the leader.
elderly adj.n.
- My father likes following elderly around.
- It was not long before I persuaded the elderly to buy our products.
- He covered the elderly with a warm coat.
- The elderly stamped out the fire to send a signal.
- We all were put to shame by the elderly who played got a good salary.
grey adj.
- I don't like that grey school uniform.
- The woman takes precautions so that her hair wouldn't be grey quickly.
- I have difficulty in finding your grey hair.
- I turned my attention to his grey socks.
- The bull looked on his grey clothes sympathetically.
sharp adj. blow n. with a sharp blow
- He was knocked down by a sharp blow on his head.
- I found out that she's a thief and knocked her to the ground with a sharp blow.
- Don't hit your brother with a sharp blow.
- I was wondering how to hit him with a sharp blow.
- No matter what you say, I will knock you to the ground with a sharp blow.
** DONE 反复听电影片段
CLOSED: [2023-09-21 Thu 20:34]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-21 Thu 20:26]
-
		1t: hall - five minutes
		s1: John said he'd be at the hall at six.
		s2: Well, if he's not here in five minutes, we'll have to go inside.
	 - theatre - half an hour
		 John said he'd be in the theatre at six.
		 Well, if he's not here in half an hour, we'll have to go inside.
	 - restaurant - ten minutes
		 John said he'd be in the restaurant at six.
		 Well, if he's not here in ten minutes, we'll have to go inside.
	 - stadium - a quarter of an hour
		 John said he'd be in the stadium at six.
		 Well, if he's not here in a quarter of an hour, we'll have to go inside.
	 - club - fifteen minutes.
		 John said he'd be at the club at six.
		 Well, if he's not here in fifteen minutes, we'll have to go inside.
-
		2t: library
		s1: Mary's just gone into the library.
		s2: That's funny! I've just come out of the library and I didn't see her in there.
	 - classroom
		 Mary's just gone into the classroom.
		 That's funny! I've just come out of the classroom and I didn't see her in there.
	 - restaurant
		 Mary's just gone into the restaurant.
		 That's funny! I've just come out of the restaurant and I didn't see her in there.
	 - dining room
		 Mary's just gone into the dining room.
		 That's funny! I've just come out of the dining room and I didn't see her in there.
	 - pub
		 Mary's just gone into the pub.
		 That's funny! I've just come out of the pub and I didn't see her in there.
-
		3t: the cake out of the oven - tin
		s1: Have you taken the cake out of the oven yet?
		s2: Yes, and I've put it in the tin.
	 - some ice from the fridge - jug
		 Have you taken some ice from the fridge.
		 Yes, and I've put it in the jug.
	 - the beef out of the fridge - oven
		 Have you taken the beef out of the fridge yet?
		 Yes, and I've put it in the oven.
	 - the apples out of the box - bowl
		 Have you taken the apples out of the box yet?
		 Yes, and I've put it in the bowl.
	 - some fruit from the basket - box
		 Have you taken some fruit from the basket yet?
		 Yes, and I've put it in the box.
-
		4t: jeans - a dress
		s1: Isn't she going to change out of those jeans?
		s2: Yes, she's going to change into a dress.
	 - shorts - a shirt and blouse
		 Isn't she going to change out of those shorts?
		 Yes, she's going to change into a shirt and blouse.
	 - overalls - a suit
		 Isn't she going to change out of those overalls?
		 Yes, she's going to change into a suit.
	 - wet clothes - something dry
		 Isn't she going to change out of those wet clothes?
		 Yes, she's going to change into something dry.
	 - old clothes - something new
		 Isn't she going to change out of those old clothes?
		 Yes, she's going to change into something new.
** DONE 给自己讲解
CLOSED: [2023-09-21 Thu 20:29]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-21 Thu 20:29]
change into ...
- The moment she gets home, she will change into the new clothes.
- Would you mind my changing into your clothes?
- You needn't have changed into your best clothes.
- Let's suppose that you have changed into your best clothes.
- He is used to changing into school uniform on weekends.
up and down ...
- He was walking up and down the archway yesterday.
- The solders kept marching up and down the street.
- The crowd marched up and down the street last week.
- The man is walking up and down inside the waiting room, for his wife is having an operation.
- He walked up and down the factory and double checked this piece of machinery.
sb. discovered that
- I discovered that my wife has a sense of humor.
- I discovered that my wife was making a speech in the party.
- I discovered that she bursted into tears at the reception.
- I discovered that my close friend had helped a lot.
- I discovered that my wife has a large circle of friends.
stand to attention
- At that time, I was busy standing to attention.
- We were instructed to stand to attention.
- The leader of the school standed to attention at reception over and over again.
- The students in China often spend a lot of time standing to attention.
- The students were trained to stand to attention in the university.
knock him to the ground
- She hit him so hard that she knocked him to the ground.
- Why do you knock her to the ground?
- Would you mind my knocking you to the ground? She said with a sneer.
- You shouldn't have knoced him to the ground.
- The police pointed out that the man knocked his wife to the ground.
** DONE 跟读至背诵
CLOSED: [2023-09-21 Thu 20:04]
** DONE Ask me if 写+读
CLOSED: [2023-09-21 Thu 20:10]
1. The prisoner of war escaped from a camp. Where...from/Who
	 Where did the prisoner of war escape from?
	 Who escaped from a camp?
2. He killed the guard. Who
		Who did he kill?
3. He dragged him into the bushes. Where
		Where did he dragged him?
4. He worked rapidly. How fast
		How fast did he work?
5. He changed into the dead man's clothes. What/Whose/Why
		What did he change into?
		Whose clothes did he change into?
		Why did he change into the dead man's clothes?
6. He was now dressed in a blue uniform. What/Who
	 What was he now dressed in?
	 Who was now dressed in a blue uniform?
7. He put a rifle over his shoulder. What
	 What did he put over his shoulder?
8. He marched boldly up and down in front of the camp. How/Where
	 How did he march up and down in front of the camp?
	 Where did he march boldly?
9. He could hear shouting in the camp itself. What
	 What could he hear in the camp itself?
** DONE 摘要写作
CLOSED: [2023-09-21 Thu 20:50]
After having killed the guard,
	the prisoner of war dragged him into the bushes and changed into his clothes.
The he put a rifle over his shoulder and marched up and down in front of the camp.
A short time afterwars, four officer drove up in a car,
	so he stood to attention and saluted.
When they had gone,
	the driver came towards him and after he had knocked him out,
	the prisoner jumped into the car and drove away.

As soon as he had killed the guard and dragged him into the bushes,
	the prisoner of war changed into the his clothes.
With a rifle over his shoulder, he was marching up and down in front of the camp
	when four officers drove up in a car.
He stood to attention and saluted.
When the driver came towards him, the prisoner knocked him out.
Then jumping into the car, he drove away.

** DONE tell the story 口语
CLOSED: [2023-09-21 Thu 20:50]
** Topics for discussion
