#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 82 Monster or fish?
#+begin_verse
What was the monster called?

Fishermen and sailors sometimes *claim to have seen* monsters in the sea.
Though people have often *laughed at* stories told by seamen,
	*it is now known that*
		many of these 'monsters' which have *at times* been sighted are simply strange fish.
Occasionally, unusual creatures are washed to the shore,
	but they are rarely caught *out at sea*.
Some time ago, however, a peculiar fish was caught near Madagascar.
A small fishing boat was carried miles out to sea by the powerful fish as it pulled on the line.
Realizing that this was no ordinary fish,
	the fisherman made every effort not to damage it *in any way*.
When it was eventually brought to shore,
	*it was found to be* over thirteen feet long.
It had a head like a horse,
	big blue eyes, shining silver skin, and a bright red tail.
The fish, which has since been sent to a museum
		where it is being examined by a scientist,
	is called an oarfish.
Such creatures have rarely been seen alive by man as they live at *a depth of* six hundred feet.
#+end_verse
** expression
monster [ˈmɑnstər] n.怪物
sailor [ˈseɪlər] n.海员
sight [saɪt] v.见到
creature [ˈkritʃər] n.动物,生物
peculiar [pɪˈkjuljər] adj.奇怪的,不寻常的
shining [ˈʃaɪnɪŋ] adj.闪闪发光的
oarfish ['ɔːfɪʃ] n.浆鱼

shining example 光辉榜样 
--------------------
claim to have done sth. 声称做过某事
laugh at ... 嘲笑某人
it is (well) known that ... 众所周知，……
at times 有时候
out at sea 在海上
in any way 以任何方式
it was found to be ... 它被发现是……
a depth of ...(34 ft) xx的深度


** words
monster [ˈmɑnstər] n.怪物
sailor [ˈseɪlər] n.海员
sight [saɪt] v.见到
creature [ˈkritʃər] n.动物,生物
peculiar [pɪˈkjuljər] adj.奇怪的,不寻常的
shining [ˈʃaɪnɪŋ] adj.闪闪发光的
oarfish ['ɔːfɪʃ] n.浆鱼

** DONE 单词造句
CLOSED: [2023-09-21 Thu 22:42]
monster n.
- The president is such a monster that everything can't return to normal.
- I suffered from a great deal the little monster.
- Calm down, she's not a monster.
- My cousin urged me to touch that monster.
- I don't have the nerve to talk to the monster.
sailor n.
- The sailor will be sailing from the Pinhurst Harbor.
- The sailor has been away from home for over six monthes.
- The sailor was pround of his captain.
- We are going to say goodbye to the sailors.
- The sailor has taken part in an important competition.
sight v.
- After have been traveling at sea for over a month, they managed to sight the land.
- We will sight the land in twenty minute's time.
- The puma at large has been sighted for several times in the forest.
- It's said that the monster was never been sighted.
- It was no long before she sighted the cat.
creature n.
- Oarfish is such an unusual creature that we all have never sighted it before.
- The unusual creature is obviously a private collection.
- The little boy was not allowed to touch the unusual creature.
- This unusual creature is asking him for food out at sea.
- He claimed to have seen an unusual creature out at sea.
peculiar adj.
- The detective is such a huge fan of various peculiar monsters.
- He was curious to find out why his mom is a big fan of various peculiar fish.
- In return for this, he sent me a peculiar toy.
- The peculiar is gathering round out at sea.
- Don't ask me to touch the peculiar fish over and over again.
shining adj. shining example
- The policeman is a shining example to us and we should help him keep order on that occasion.
- He gets such a good salary that he is a shining example to us.
- You're a shining example to us. I said in a strong voice.
- Sorry to interrupt, but she is indeed a shining example to me.
- Leo managed to speak English fluently and he is a shining example to me.
** DONE 反复听电影片段
CLOSED: [2023-09-22 Fri 20:28]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-22 Fri 20:31]
-
		1t: warn John
		s1: Someone must warn John immediately.
		s2: Don't worry. He's already been warned.
	 - find the girl
		 Someone must find the girl immediately.
		 Don't worry. She's already been found.
	 - make the tea
		 Some one must make the tea immediately.
		 Don't worry. It's already been made. 
	 - examine the body
		 Some one must examine the body immediately.
		 Don't worry. It's already been examined.
	 - light the fire
		 Some one must light the fire immediately.
		 Don't worry. It's already been lit.
-
		2t: men - caught
		s1: Have the men been caught yet?
		s2: One of them was caught yesterday, but the other hasn't been caught yet.
	 - letters - written
		 Have the letters been written yet?
		 One of them was written yesterday, but the other hasn't been written yet.
	 - messages - received
		 Have the messaged been received yet?
		 One of them was received yesterday, but the other hasn't been received yet.
	 - books - published
		 Have the books been published yet?
		 One of them was published yesterday, but the other hasn't been published yet.
	 - cars - found
		 Have the cars been found yet?
		 One of them was found yesterday, but the other hasn't been found yet.
-
		Be supposed to do
		3t: that man working
		s1: Why isn't that man working?
		s2: I don't know. He's supposed to be working.
	 - the children resting
		 Why aren't the children resting?
		 I don't know. They're supposed to be resting.
	 - those men digging
		 Why aren't those men digging?
		 I don't know. They're supposed to be digging.
	 - that boy washing the car
		 Why isn't that boy washing the car?
		 I don't know. He's supposed to be washing it.
	 - the plane flying to Paris
		 Why isn't the plane flying to Paris?
		 I don't know. It's supposed to be flying to Paris.
-
		4t: finish the job - hours
		s1: When will the job be finished?
		s2: I've no idea. It should have been finished hours ago.
	 - write the book - months
		 When will the book be written?
		 I've no idea. It should have been written months ago.
	 - mend the radio - days
		 When will the radio be mended?
		 I've no idea. It should have been mended days ago.
	 - draw up the agreement - weeks
		 When will the agreement be drawn up?
		 I've no idea. It should have been drawn up weeks ago.
	 - burn the rubbish - days
		 When will the rubbish be burnt?
		 I've no idea. It should have been burnt days ago.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-21 Thu 22:42]
claim to have done sth.
- She claimed to have driven on to the hometown.
- She claimed to have taken a lift.
- He claimed to have left a note on the car.
- She claimed to have parked his car in the street.
- She claimed to have hurried to the hospital.
laugh at ...
- She might have laughed at you at that moment.
- If they were keen on studying, they wouldn't have laughed at you.
- For some reason, the girl kept laughing at her boyfriend.
- Even her parents laughed at him for several times, his was determined to cross the Channel.
- She began to complain about her father and laugh at him.
it is (well) known that ...
- It is known that the guards discovered that a prisoner had escaped.
- It is known that the soldier must stand to the officer in that country.
- It is known that she wander up and down in front of the camp.
- It is known that she lost all her money in the village.
- It is known that the world is changing rapidly no matter what you do.
at times
- My wife feels frightened at times.
- I was disappointed to learn that my wife lose her temper at times.
- The worker fired his boss, for his boss lost his temper at times on these occasions.
- I am used to taking charge of my friend's cat at times.
- The terrorist plants a bomb on the plane at times.
out at sea
- The ship was now out at sea.
- The seaman discovered that the boat had been out at sea for over six months.
- The boat is out at sea of all time.
- She was sure that the boat was out at sea.
- The boat sent a signal out a sea.
in any way
- I'm trying to avoid arguing with my wife in any way.
- The plane is trying to touch down on the ground in any way.
- He insisted on living abroad in any way.
- She is offering her son foods in any way.
- The doctors is trying to prevent the mummy from falling to pieces in any way.
sth./sb. was found to be ...
- He was found to be a terrible godfather.
- The moment I am found to be worthless, I will fire my boss.
- As soon as he had been found to be worthless, he was fired by his boss.
- The story was found to be interesting.
- The monster was found to be an ordinary fish.
a depth of ...
- The lake is found to be over a depth of six hundred feet.
- The villager was delighted to find water at a depth of twenty meters.
- I don't have the nerve to hide in a cave at a depth of six hundred feet.
- Finding water at a depth of 600 meters gave him satisfaction.
- The mummy was found in a cave at depth of six hundred feet.
** DONE 跟读至背诵
CLOSED: [2023-09-22 Fri 19:57]
** DONE Ask me if 写+读
CLOSED: [2023-09-22 Fri 20:33]
1. Fishermen tell many stories. What/Who
	 What stories do Fishermen tell?
	 Who tell many stories?
2. They sometimes claim to have seen monsters in the sea. What/ Where
		What do they sometimes claim?
		Where do they sometimes claim to have seen monsters?
3. People laugh at stories told by seamen. What/Why
		What do people laugh at?
		Why do people laugh at stories told by seamen?
4. Many of these 'monsters' are simply strange fish. What
		What are many of these 'monsters'?
5. Unusual creatures are occasionally washed to the shore. How often/What kind
		How often are unusual creatures washed to the shore?
		What kind of creatures are occasionally washed to the shore?
6. They are rarely caught out at sea. Where
	 Where are they caught?
7. A peculiar fish was caught some time ago near Madagascar. Where/When
	 Where was a peculiar fish caught some time ago?
	 When was a peculiar fish caught near Madagascar?
8. It carried a small fishing boat miles out to sea. How far/What
	 How far did it carry a small fishing boat out to sea?
	 What did it carried miles out to sea?
	 
** DONE 摘要写作
CLOSED: [2023-09-22 Fri 20:24]
A strange fish was caught near Madagascar
	after having pulled a fishing boat miles out to sea.
Making every effort not to damage it, the fisherman brought it to shore.
The fish, which was thirteen feet long, with a head like a horse,
	was sent to a museum.
It was being examined by a schienti,
	who said it was an oarfish and that such creatures live at a depth of six hundred feet.

A strange fish was caught near Madagascar.
Though it pulled a fishing boat miles out to sea,
	the fisherman made every effort not to damage it.
On being brought to shore,
	the fish was found to be over thriteen feet and to had a head like a horse.
Now that it has been sent to a museum, it is being examined by a scientist.
It is called an oarfish and lives at depth of six hundred feet.

** DONE tell the story 口语
CLOSED: [2023-09-22 Fri 20:33]
** Topics for discussion
