#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 86 Out of control
#+begin_verse
What was the danger?

As the man tried to swing the speedboat round, the steering wheel *came away* in his hands.
He waved desperately to his companion, who had been water skiing for the last fifteen minutes.
Both men had hardly had time to realize what was happening
	when they were thrown violently into the sea.
The speedboat had struck a buoy,
	but it continued to move very quickly across the water.
Both men had just begun to swim towards the shore,
	when *they noticed with dismay* that the speedboat was moving *in a circle*.
It now came straight towards them *at tremendous speed*.
In less than a minute, it roared past them only a few feet away.
After it had passed,
	they swam on as quickly as they could because they knew that the boat would soon return.
They had just had enough time to swim out of danger
	when the boat again completed a circle.
On this occasion, however, it had slowed down considerably.
The petrol had nearly all *been used up*.
*Before long*, the noise dropped completely and the boat began to drift gently across the water.
#+end_verse
** expression
swing [swɪŋ] swung v.转向
speedboat [ˈspidˌboʊt] n.快艇
desperately [ˈdesp(ə)rət(ə)li] adv.绝望地
companion [kəmˈpænjən] n. 同伴,伙伴
water [ˈwɔtər] ski [ski] (由快艇牵引)滑水
buoy [ˈbui] n.浮标
dismay [dɪsˈmeɪ] n.沮丧
tremendous [trəˈmendəs] adj.巨大的
petrol [ˈpetrəl] n.汽油
drift [drɪft] v.漂动,漂流
gently [ˈdʒentli] adv.缓慢地,轻轻地

sb. noticed with dismay that + ... 某人惊慌地注意到……
at tremendous speed 以惊人的速度
--------------------
come away 脱落
move in a circle 以圈移动
be used up 用完
before long 不久之后


** words
swing [swɪŋ] v.转向
speedboat [ˈspidˌboʊt] n.快艇
desperately [ˈdesp(ə)rət(ə)li] adv.绝望地
companion [kəmˈpænjən] n.同伙,伙伴
water ski [ˈwɔtər-,ski] 滑水
buoy [ˈbui] n.浮标
dismay [dɪsˈmeɪ] n.沮丧
tremendous [trəˈmendəs] adj.巨大的
petrol [ˈpetrəl] n.汽油
drift [drɪft] v.漂动,漂流
gently [ˈdʒentli] adv.缓慢地,轻轻地

** DONE 单词造句
CLOSED: [2023-09-27 Wed 21:58]
swing swung v.
- In return for this, I teach her how to swing.
- His arms are used to swinging as he walks.
- It is no coincidence that they swing their cars round at the same time.
- He kept on swinging his car in the street.
- Instead of fishing, I am instered in swinging on the tree.
speedboat n.
- He was said to be so rich that he had a speedboat.
- The company made such a profit that the boss bought a speedboat.
- Joey was relieved to hear that the speedboat wasn't sold.
- We will remember him for his luxury speedboat.
- She is due to buy an entirely new speedboat.
desperately adv.
- They decided desperately to go on strike.
- He hasn't been studying English, and he will take the test desperately.
- The busmen objected desperately that the students will drive too fast.
- Under a lot of pressure, she got desperately to her children as possible as she could.
- He tried desperately to put forward the plan.
companion n.
- My companion is a huge fan of football.
- On the following day, my companion won the election.
- My companion is losing his temper in the game over and over again.
- My companion online was found to be my father.
- My companion has caught a peculiar fish out at sea.
water ski
- In his thirties, he devoted himself to water skiing.
- I love to go water ski on vacations.
- The girl insisted on going water skiing with her father.
- He is fanatical about water skiing.
- It is known that he used to go water skiing out at sea.
buoy n.
- I and my companion were swiming to the buoy at the same time.
- It is no use pretending that the buoy wasn't there.
- He discovered that the buoy wasn't there.
- The boat sailed rapidly towards the buoy.
- He swam up and down in front of the buoy.
dismay n. sb. noticed with dismay that + ...
- He noticed with dismay that the plants were growing rapidly.
- I noticed with dismay that he had knocked his wife to the ground.
- I noticed with dismay that the plane gain height slowly.
- She noticed with dismay that she couldn't send a signal to ask for help in the mountains.
- The driver noticed with dismay that a bomb had been planted.
tremendous adj. at tremendous speed
- This is such a tremendous honor that I follow in my father's footsteps.
- It will have tremendous effort on you.
- It entitled the speedboat to sail at tremendous speed.
- The busmen drived bus at two thieves at tremendous speed.
- The lottery carried hundreds of boxes of fruits to Paris at tremendous speed.
petrol n.
- I took precaution and met her at the petrol station.
- After a long journey, we found a petrol station in the village.
- It was not long before the petrol station was planted a bomb.
- "Get out of here", she shouted at me at the petrol station.
- Thank you for coming at the petrol station on such short notice.
drift v.
- The boat is drifting down the river.
- I'd like to be in a boat which is drifting down the river.
- The boy was disappointed to learn that the ball was drifting on the river.
- The boy noticed with dismay that his ball was drifting on the river.
- No one counld account for the fact that the boat was drifting on the river.
gently adv.
- He got close to her gently at the time.
- The examiner tapped gently on the window.
- I am instructed to treat my wife gently.
- For your safety, you'd better touch it gently.
- "Don't make that stupid remark.He has a very bad temper." She said gently.
** DONE 反复听电影片段
CLOSED: [2023-09-28 Thu 17:18]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-28 Thu 17:15]
-
		1t: post the letter
		s1: Did he post the letter when you asked him to?
		s2: He'd already posted it.
	 - pay the bill
		 Did he pay the bill when you asked him to?
		 He'd already paid it.
	 - mend the boat
		 Did he mend the boat when you asked him to?
		 He'd already mended it.
	 - cut the glass
		 Did he cut the glass when you asked him to?
		 He'd already cut it.
	 - sign the paper
		 Did he sign the paper when you asked him to?
		 He'd already signed it.
-
		2t: use - the iron - put away
		s1: Can I use the iron after you, please?
		s2: I'm sorry. I put it away after I'd used it.
	 - read - the paper - throw away
		 Can I read the paper after you, please?
		 I'm sorry. I threw it away after I'd read it.
	 - study - the note - tear up
		 Can I study the note after you, please?
		 I'm sorry. I tore it up after I'd studied it.
	 - talk to - the boy - send home
		 Can I talk to the boy after you, please?
		 I'm sorry. I send him home after I'd talked to him.
	 - look at - the photos - give to Mary
		 Can I look at the photos after you, please?
		 I'm sorry. I gave them to Mary after I'd looked at them.
-
		3t: see a bad film
		s1: Why did you see such a bad film?
		s2: I hadn't seen it before, so I didn't know it was bad.
	 - read a dull book
		 Why did you read such a dull book?
		 I hadn't read it before, so I didn't know it was dull.
	 - speak to a rude man
		 Why did you speak to such a rude man?
		 I hadn't spoken to him before, so I didn't know he was rude.
	 - order bad wine
		 Why did you order such a bad wine?
		 I hadn't ordered it, so I didn't know it was bad.
	 - use thick oil
		 Why did you use such thick oil?
		 I hadn't used it, so I didn't know it was thick.
-
		4t: hot - running
		s1: Why was he so hot when he got home?
		s2: He'd been running.
	 - tired - working angry - quarrelling
		 Why was he so tired when he got home?
		 He'd been working.
	 - hungry - swimming happy - celebrating
		 Why was he so hungry when he got home?
		 He'd been swimming.
	 - rude - drinking dirty - gardening
		 Why was he so rude when he got home?
		 He'd been drinking.
	 - nervous - fighting miserable - crying
		 Why was he so nervous when he got home?
		 He'd been fighting.
** DONE 给自己讲解
CLOSED: [2023-09-28 Thu 17:18]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-27 Wed 22:08]
come away
- The paper has started to come away from the bulletin.
- Let's suppose that the paper came away from the bulletin.
- I noticed with dismay that the paper had came away in my hands.
- The cat came away from my house.
- He managed to come away from the prison.
move in a circle
- Gather round and stand in a circle.
- Why don't we sit in a circle?
- A large crowd of young boys and young girls were walking in a circle.
- Pupils of the school were instructed to sit in a circle.
- A party of teacher refused to stand in a circle.
use up 
- She's used up all water in the desert.
- The petrol was used up before she drove to next village.
- It is said that he has used up all money.
- Why did you use up all the glue last night?
- The petrol was used up in twenty minutes' time.
before long
- Before long, I will build a wood bridge.
- Before long, the boat will cross the Atlantic.
- Before long, the search party received a warm welcome.
- Before long, she will also get a good salary.
- Before long, you will be allowed to go to Beijing.
** DONE 跟读至背诵
CLOSED: [2023-09-28 Thu 17:18]
** Ask me if 写+读
1. The man tried to swing the speedboat round. What...do
	 What did the man try to do?
2. The steering wheel came away in his hands as he did so. When
		When did the steering wheel come away in his hands?
3. He waved desperately to his companion. Who...to/Why/When
		Who did he wave desperately to?
		Why did he wave desperately to his companion?
		When did he wave desperately to his companion?
4. He was water skiing. What...doing
		What was he doing?
5. He had been water skiing for the last fifteen minutes. How long/Who
		How long had he been water skiing?
		Who had been water skiing for the last fifteen minutes?
6. Both men were thrown violently into the sea. How/When/Who
	 How were both men thrown into the sea?
	 When were both men thrown violently into the sea?
	 Who were thrown violently into the sea?
7. They had hardly had time to realize what was happening. How much time
	 How much time had they had to realize what was happening?
8. The boat had struck a buoy. What
	 What had the boat struck?
** DONE 摘要写作
CLOSED: [2023-09-28 Thu 17:39]
The moment the speedboat struck the buoy, both men were thrown into the water.
As it was moving off very quickly across the water,
	both men begun to swim towards the shore.
Turning in a circle, the speedboat came straight towards them.
After it had just missed them, both men swam util they were on out of danger.
When the boat returned it had lost speed.
Soon all the petrol was used up and it floated across the water.

Because the speedboat struck the buoy, both men were thrown into the water.
It was moving off very quickly 
	and, while the men were swimming towards the shore,
		it turned in a circle, came straight towards them and only just missed them.
The men had no sooner swum out of danger than the boat returned.
This time, however, it lost speed because all the petrol was used up
	and it floated across the water.

** DONE tell the story 口语
CLOSED: [2023-09-28 Thu 17:41]
** Topics for discussion
