#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 89 A slip of the tongue

#+begin_verse
Who made the only funny joke that evening and why?

People will *do anything to see* a free show ---- even if it is a bad one.
When *the news got round*
	that *a comedy show* would be presented at our local cinema by the P. and U. Bird Seed Company,
	we all rushed to see it.
We had to queue for hours to get in and there must have been several hundred people present
	just before the show began.
Unfortunately, the show was one of the dullest we have ever seen.
Those who failed to get in need not have *felt disappointed*,
	as many of the artistes who should have appeared did not come.
The only funny things we heard that evening
	came from the advertiser *at the beginning of the programme*.
He was obviously very nervous and for some minutes stood awkwardly before the microphone.
As soon as he opened his mouth, everyone *burst out laughing*.
We all know what the poor man should have said,
	but what he actually said was: 'This is the Poo and Ee Seed Bird Company.
Good ladies, evening and gentlemen!’
#+end_verse
** expression
slip [slɪp] n.小错误
comedy [ˈkɑmədi] n.喜剧
present [ˈprezənt] v.演出 adj.出席,到场的
queue [kju] v.n.排队
dull [dʌl] adj.枯燥,无味
artiste [ɑrˈtist] n.artist 艺人
advertiser [ˈædvərˌtaɪzər] n.报幕员

a slip of the tongue 口误
a comedy show 喜剧表演
hold up the queue 排队等候
--------------------
do anything to do sth. 尽一切努力做某事
the news get around 消息传开了
feel disappointed 感到失望
at the beginning of a. 在……的开始
burst out laughing 突然大笑

** words
slip [slɪp] n.小错误
comedy [ˈkɑmədi] n.喜剧
present [ˈprezənt] v.演出;adj.出席,到场的
queue [kju] v.排队
dull [dʌl] adj.枯燥,无味
artiste [ɑrˈtist] n.艺人
advertiser [ˈædvərˌtaɪzər] n.报幕员
** DONE 单词造句
CLOSED: [2023-10-07 Sat 09:52]
slip n. a slip of the tongue 
- It was obvious that it was just a slip of the tongue.
- A slip of the tongue made me say Jie instead of Baobei.
- Did I say $200? It must have been a slip of the tongue.
- It may be a slip of the tongue.
- Did I say he smashed everything to pieces? It must be a slip of the tongue.
comedy n. a comedy show
- They must have watched a comedy show last night.
- He has just written out a long list of comedy shows.
- This is the most instersting comedy show I've ever watched.
- He gets tired of wacthing comedy shows.
- A gust of wind swept the roof of the tent, the comedy show wasn't presented on time.
present v.adj.
- A comedy show will be presented at the square this night.
- They should have presented a comedy show tonight.
- They needn't have presented a comedy show tonight.
- They may presented a comeday show tonight.
- They must have presented a comedy show tonight.
queue v.n. hold up the queue
- Don't be too hard on us, don't hold up the queue.
- I heard the vegetarian holding up the queue.
- No one account for the fact that they are holding up the queue.
- The workers have decided to go on strike and hold up the queue.
- The poor man admited that he had held up the queue last night.
dull adj.
- It is the dullest comedy show I've ever seen.
- All work and no play have made me a dull boy.
- A dull boy shouldn't have gone to cinema on weekdays.
- A dull boy need playing more.
- The dull boy suggested that we have a picnic over and over again.
artiste n.artist
- Enough money enabled the artiste to build the bridge.
- If the artiste wasn't brought out to the mine, he would lose his life.
- I'll do anything to keep in touch with the artiste.
- The artiste is running out of his money.
- It makes the artiste to tear up his paper.
advertiser n.
- On the surface, the advertiser had a perfect alibi.
- In the end, we found out that the advertiser commited a murder.
- The advertiser confirmed that it wasn't a slip of tongue.
- The advertiser refused to tell the truth.
- The advertisers are moving in a circle.
** DONE 反复听电影片段
CLOSED: [2023-10-07 Sat 21:44]
** DONE Pattern Drill 写+读
CLOSED: [2023-10-07 Sat 21:48]
-
		1t: wash the dishes
		s1: She needn't have washed the dishes.
		s2: She had to wash them or her husband would have been furious with her.
	 - buy a paper
		 She needn't have bought a paper.
		 She had to buy a paper or her husband would have been furious with her.
	 - make the beds
		 She needn't have made the beds.
		 She had to make the beds or her husband would have been furious with her.
	 - visit Mary
		 She needn't have visited Mary.
		 She had to visit Mary or her husband would have been furious with her.
	 - cook lunch
		 She needn't have cooked lunch.
		 She had to cook lunch or her husband would have been furious with her.
-
		2t: type the letters
		s1: Didn't Mary type the letters yesterday?
		s2: They'd already been typed, so she didn't have to type them.
	 - buy the food
		 Didn't Mary buy the food yesterday?
		 It'd already been bought, so she didn't have to buy the food.
	 - prepare the speech
		 Didn't Mary prepare the speech yesterday?
		 It'd alreay been prepared, so she didn't have to prepare the speech.
	 - sell the tickets
		 Didn't Mary sell the tickets yesterday?
		 They'd already been sold, so she didn't have to sell the tickets.
	 - make the decision
		 Didn't Mary make the decision yesterday?
		 It'd already been made, so she didn't have to make the decision.
-
		3t: read - your eyes
		s1: You mustn't read so much or you'll strain your eyes.
		s2: I've got to do a lot of reading. It's part of my job.
	 - talk - your voice
		 You mustn't talk so much or you'll strain your voice.
		 I've got to do a lot of talking. It's part of my job.
	 - shout - your voice
		 You mustn't shout so much or you'll strain your voice.
		 I've got to do a lot of talking. It's part of my job.
	 - climb - your heart
		 You mustn't climb so much or you'll strain your heart.
		 I've got to do a lot of climbing. It's part of my job.
	 - carry - your back
		 You mustn't carry so much or you'll strain your back.
		 I've got to do a lot of carrying. It's part of my job.
-
		4t: arrived - delayed
		s1: I can't understand it. He ought to have arrived by now.
		s2: He must have been delayed.
	 - been here - kept at the office
		 I can't understand it. He ought to have been here by now.
		 He must have been kept at the office.
	 - come back - caught by the police
		 I can't understand it. He ought to have come back by now.
		 He must have been caught by the police.
	 - left home - taken ill
		 I can't understand it. He ought to have left home by now.
		 He must have been taken ill.
	 - done the job - arrested
		 I can't understand it. He ought to have done the job by now.
		 He must have been arrested.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-07 Sat 09:52]
do anything to do sth.
- My wife will do anything to go on vacation in summer.
- The petrol was almost used up, we must do anything to find a petrol station.
- He devoted himself to education and will do anything to help his students.
- I'll do anything to make agreement with the busmen.
- She will do anything to pass the exam.
the news get around
- When the news get around, the villagers began to make a tribution to the exhibition.
- The news get around that the agreement was reachoued about pay and work condition.
- When the news get around, everything bursted into cheers.
- The advertiser has stated that the news get around.
- When the news get around, he expressed his gratitude to the reporters.
feel disappointed
- I felt disappointed that my wife had ran out of her pocket money.
- I felt disappointed that my child had played a truent from school.
- I felt disappointed that nobody volunteered to make a contribution to our school.
- The strike have been continued for two weeks, we all felt disappointed.
- He felt disappointed that his wife lost her temper once more.
at the beginning of a.
- At the beginning of the Winter, they haven't decided to go on strike.
- At the beginning of the election, he is fanatical about objecting Mr. Wu.
- He claimed to have seen the monster at the beginning of July.
- At the beginning of the war, they made every effort to move to America.
- At the beginning of the war, they hope everything return to normal.
burst out laughing
- In the end, I turned around and bursted out laughing.
- I am delighted that my father bursted out laughing.
- He was offered a good job and bursted out laughing.
- It was a slip of the tongue and the flight attendant bursted into laughing.
- He made every effort not to burst out laughing, but he couldn't control himself.
** DONE 跟读至背诵
CLOSED: [2023-10-07 Sat 21:25]
** DONE Ask me if 写+读
CLOSED: [2023-10-07 Sat 21:31]
1. People like to see a free show. What
	 What do people like to do?
2. The P. & U. Bird Seed Company presented a comedy show. What kind/Who
		What kind of show did the P. & U. Bird Seed Company present?
		Who presented a comedy show?
3. It was presented at a cinema. Where
		Where was it presented?
4. The news got round. What
		What got round?
5. We all rushed to see it. What
		What did we all rush to see?
6. We had to queue to get in. Why
	 Why did we have to queue?
7. We queued for hours. How long/Who
	 How long did he queue?
	 Who queued for hours?
8. Several hundred people were present. How many
	 How many people were present?
9. The show was very dull. What...like
	 What was the show like?
10. The advertiser stood awkwardly before the microphone. How/Where
		How did the advertiser stand before the microphone?
		Where did the advertiser stand awkwardly?
** DONE 摘要写作
CLOSED: [2023-10-07 Sat 21:48]
The local cinema was packed
	because P. & U Bird Seed was presenting a free comedy show.
As many of artistes who should have appeared failed to turn up,
	the show was very dull.
The funniest thing was we heard came at the beginning from the advertiser
	who introduced programme saying:
	"This is the Poo and Ee Seed Bird Company.Good ladies, evening and gentlemen!".

The local cinema was packed.
The P. & U. Bird Seed Company was presenting a free comedy show,
	but many of artistes who should have appeared failed to turn up.
Because of this, the show was very dull.
The funniest thing we heard came at the beginning from the advertiser
	who introduced the programme saying:
	"This is the Poo and Ee Seed Bird Company.Good ladies, evening and gentlemen!".
** tell the story 口语
** Topics for discussion
