#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 90 What's for supper?

#+begin_verse
What kind of fish are they?

Fish and chips has always been a favourite dish in Britain,
	but as the oceans have been overfished, fish has become more and more expensive.
So it comes as a surprise to learn that giant fish are terrifying the divers on North Sea oil rigs.
Oil rigs have to be repaired frequently
	and divers, who often have to work in darkness a hundred feet under water,
		have *been frightened out of their wits* by giant fish bumping into them as they work.
Now they have had special cages made to *protect them from* these monsters.
The fish are not sharks or killer whales,
	but favourite eating varieties like cod and skate
		which grow to unnatural sizes, sometimes as much as twelve feet *in length*.
Three factors have caused these fish to grow so large:
	the warm water round the hot oil pipes under the sea;
	the plentiful supply of food thrown overboard by the crews on the rigs;
	*the total absence of* fishing boats around the oil rigs.
*As a result*, the fish just eat and eat and grow and grow in the lovely warm water.
Who eats who?
#+end_verse
** expression
chip [tʃɪp] n.油煎土豆片
overfish [ˌoʊvə'fɪʃ] v.过度捕捞
giant [ˈdʒaɪənt] adj.巨大的
terrify [ˈterəˌfaɪ] v.吓,使恐怖
diver [ˈdaɪvər] n.潜水员
oil rig [ɔɪl] [rɪɡ] 石油钻塔
wit [wɪt] n.(复数)理智,头脑
cage [keɪdʒ] n.笼
shark [ʃɑrk] n.鲨鱼
whale [hweɪl] n.鲸
variety [vəˈraɪəti] n.品种
cod [kɒd] n.鳕 skate n.鳐
factor [ˈfæktər] n.因素
crew [kru] n.全体工作人员

be scared/frightened out of sb's wits 把某人吓得魂不附体
a variety of 各种各样的
--------------------
it comes as a surprise to learn that + ... 得知...令人惊讶
protect a. from b. 保护A远离B
in length 在长度上(状语)
the (total) absence of ... 没有...
as a result 因此



** words
chip [tʃɪp] n.油煎土豆皮
overfish [ˌoʊvə'fɪʃ] v.过度捕捞
giant [ˈdʒaɪənt] adj.巨大的
terrify [ˈterəˌfaɪ] v.吓,使恐怖
diver [ˈdaɪvər] n.潜水员
oil rig [ɔɪl-rɪɡ] 石油钻塔
wit [wɪt] n.(复数)理智,头脑
cage [keɪdʒ] n.笼
shark [ʃɑrk] n.鲨鱼
whale [weɪl] n.鲸
variety [vəˈraɪəti] n.品种
cod [kɒd] n.鳕
skate [skeɪt] n.鳐
factor [ˈfæktər] n.因素
crew [kru] n.全体工作人员
** DONE 单词造句
CLOSED: [2023-10-08 Sun 22:06]
chip n.
- Did I say chip and fishes? It was a slip of the tongue.
- Would you mind my eating chip and fishes there?
- We've already ran out of chip and fishes.
- I felt disappointed, for we had chip and fishes tonight.
- She'll do anything to eat chip and fishes.
overfish v.
- The river has been overfished for over 10 years.
- It is the authorities who overfished the river, not the villagers.
- At the beginning of summer, the villagers overfished the river.
- When the news got around, the villagers overfished the river as soon as possible.
- It caused the authorities to overfish the river.
giant adj.
- The fisher claimed to have seen a giant fish bumping into him.
- They haven't caught the giant fish and lost heart.
- The giant fish was carried to the village fair.
- There is a giant fish on display.
- The giant fish on show is a killer whale.
terrify v.
- The strike gone on terrified me a great deal.
- It is known that he was terrified by the aliens.
- It was said that he was terrified by a giant fish out at sea.
- The boy who played truent from school will do anything to terrify his parents.
- The gangster who knocked her to the ground terrified me a great deal.
diver n.
- Even though I am a diver, I am unaware of the giant fish.
- The diver is fanatical about football.
- The diver failed to win the elections.
- The diver maked every effort not to damage it in any way.
- The diver urged him to swim out at sea.
oil rig
- You could have accepted the work in the oil rig.
- It is said that he jumped off the oil rig.
- I don't look forward to seeing you jump off the oil rig.
- If I were you, I wouldn't accept a work in the oil rig.
- I don't have the nerve to work in the oil rig.
wit n. be scared/frightened out of sb's wits
- It's obvious that the dog was frightened out of his wits.
- The boy was delighted that his daughter was scared out of her wits.
- Having cut the mummy open, the doctor was frightened out of his wits.
- He was frightened out of his wits, for he had a rare disease.
- Don't be too hard on me. I am scared out of my wits.
cage n.
- He covered the cage with a blanket.
- He noticed with dismay that the birds were not in the cage.
- The police who arrived on the scene saw a bird in the cage.
- The bird in the cage is trying to stay out of the limelight.
- There must have been a bird in the cage. The detective said in a weak voice.
shark n.
- It was found to be a shark.
- When he finally saw the real shark, he burst into tears.
- He decided to devote himself to studying sharks.
- He became an expert at sharks.
- He had a habit of studying sharks.
whale n.
- They claimed to have seen a whale jumping out the water yesterday morning.
- He pointed out that the whale had been killed.
- A number of whales are jumping out the water.
- It is said that the authorities had the whale killed.
- The captain pointed out that the whale is source of income.
variety n. a variety of
- It is my job to repair a variety of bicycle.
- I can get to office in a variety of way, don't worry me.
- As a captain, he will have to make a variety of decisions out at sea.
- He pretends that he knows a variety of birds in the cages.
- It is fortunate that you know a variety of volcanoes.
factor n.
- Leo said that it depended on a variety of factors.
- They was disappointed to learn that there were a variety of factors destorying the building.
- A variety of factors caused the elephant to hold up the traffice.
- A variety of factors caused the policeman to let her off.
- He feared that many factors can destory the attic.
crew n.
- The fire and police crews should have arrived on the scene in time.
- The crews have solve the problem of the ventilation of the tunnel.
- The crews have double checked the boat.
- The crews have been carrying the food to the boat.
- Right from the start, the crews got a good salary.
** DONE 反复听电影片段
CLOSED: [2023-10-09 Mon 19:36]
** DONE Pattern Drill 写+读
CLOSED: [2023-10-09 Mon 19:48]
-
		1t: a pen
		s1: I need a pen. Have you got one to spare?
		s2: I'm sorry. I've only got one and I need it myself.
	 - a stamp
		 I need a stamp. Have you got one to spare?
		 I'm sorry. I've only got one and I need it myself.
	 - a clock
		 I need a clock. Have you got one to spare?
		 I'm sorry. I've only got one and I need it myself.
	 - a radio
		 I need a radio. Have you got one to spare?
		 I'm sorry. I've only got one and I need it myself.
	 - a cup
		 I need a cup. Have you got one to spare?
		 I'm sorry. I've only got one and I need it myself.
-
		2t: bread or toast - for tea
		s1: Would you like break or toast for tea?
		s2: I'll have toast, if I may.
	 - eggs or fish - for dinner
		 Would you like eggs or fish for dinner?
		 I'll have eggs, if I may.
	 - cake or biscuits - for tea
		 Would you like cake or biscuits for tea?
		 I'll have biscuits, if I may.
	 - salad or rice - with your meat
		 Would you like salad or ice with your meat?
		 I'll have ice, if I may.
	 - jam or honey - with your toast
		 Would you like jam or honey with your toast?
		 I'll have jam, if I may.
-
		3t: irritable - a long walk
		s1: I feel very irritable.
		s2: Have a long walk and you'll feel better.
	 - dirty - a wash
		 I feel very dirty.
		 Have a wash and you'll feel better.
	 - cold - a hot bath
		 I feel very cold.
		 Have a hot bath and you'll feel better.
	 - tired - a rest
		 I feel very tired.
		 Have a rest and you'll feel better.
	 - hot - a swim
		 I feel hot.
		 Have a swim and you'll feel better.
-
		4t: cracked cup - mend
		s1: That cup is cracked. I'll have to have it mended.
		s2: Don't worry. I'll get it mended for you.
	 - dirty car - wash
		 That car is dirty. I'll have to have it washed.
		 Don't worry. I'll get it washed for you.
	 - broken radio - repair
		 That radio is broken. I'll have to have it repaired.
		 Don't worry. I'll get it repaired for you.
	 - long grass - cut
		 That grass is long. I'll have to have it cut.
		 Don't worry. I'll get it cut for you.
	 - old tree - cut down
		 That tree is old. I'll have to have it cut down.
		 Don't worry. I'll get it cut down for you.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-08 Sun 22:06]
it comes as a surprise to learn that + ...
- It comes as a surprise to learn that he threatend to kill himself.
- It comes as a surprise to learn that the grass takes root.
- It comes as a surprise to learn that China will open itself.
- It comes as a surprise to learn that he passed the exam.
- It comes as a surprise to learn that the fire crew got the fire under control.
protect a. from b.
- I must protect my father from himself.
- I have to protect my cat from eating dirty food.
- I can't protect me from smoking.
- I would like to protect you from anyone who wants to hurt you.
- He compained of being protected from alcohol for so long time.
in length
- The whale was found to be 300 meters in length.
- The river is as much as 300 kilometers in length.
- The railway is said to be 500 kilometers in length.
- The film was said to be over 3 hours in length.
- The lake is a total of 300 kilometers in length.
the (total) absence of ...
- A major problem is the absence of clean water in floods.
- The company informed us that we would be the absence of water.
- In the total absence of any evidence, the detective had to let him off.
- In the absence of my teacher, I was asked to keep order in the class.
- In the absence of my wife, I failed to do anything.
as a result
- As a result, he will devote himself to gardening.
- As a result, everyone will buy a gift to mark the occassion.
- As a result, we will remember him for his patience.
- As a result, he was due to sail out at sea.
- As a result, the workers decided to reach agreement about pay and work conditions.
** DONE 跟读至背诵
CLOSED: [2023-10-09 Mon 19:48]
** DONE Ask me if 写+读
CLOSED: [2023-10-09 Mon 19:54]
1. Fish and chips has always been a favourite dish in Britain. What/Where
	 What has always been a favourite dish in Britain?
	 Where has fish and chips always been a favourite dish?
2. Fish has become more expensive. Why
		Why has fish become more expensive?
3. Divers have to repair oil rigs. Who/What
		Who have to repair oil rigs?
		What do divers have to repair?
4. They often have to work in darkness. Where
		Where do they often have to work?
5. Giant fish often bump into them. What
		What often bump into them?
6. They have special cages to protect them. What
	 What do they have to protect them?
7. The fish are eating varieties. What kind of fish
	 What kind of fish are they?
8. They grow to unnatural sizes. How large
	 How large do they grow to?
9. The water is warm round the oil pipes. Where
	 Where is the water warm?
10. Food is supplied by the crews. What
		What is supplied by the crews?
** DONE 摘要写作
CLOSED: [2023-10-09 Mon 20:06]
Divers working on the North Sea oil rigs
	are often terrified by giant fish
		that bump into them when they are working in deep water.
These fish are not sharks or whales.
On the contrary, they are favourite eating varieties
	that grow to unnatural sizes.
Three factors caused them to grow so large:
	the first is the warmth from oil-pipes;
	the second is the supply of plentiful food;
  the third is the absence of fishing boat round the rigs.

Divers who work on the North Sea oil rigs
	are often terrified by gaint fish
	bumping into them while they are working in deep water.
These fish are not sharks or whales,
	but favourite eating varieties
		which grow to unnatural sizes.
Three factors caused this to happen:
	the warmth from the hot oil-pipes, the supply of plentiful food and the absence of fishing.
	

** DONE tell the story 口语
CLOSED: [2023-10-09 Mon 20:08]
** Topics for discussion
