#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 96 The dead return
#+begin_verse
What happens to the lanterns at the end of festival?

A Festival for the Dead is held once a year in Japan.
This festival is a cheerful occasion,
	for on this day, the dead are said to *return to their homes* and they are welcomed by the living.
As they *are expected to be* hungry after their long journey,
	*food is laid out* for them.
Specially-made lanterns are hung outside each house to help the dead to find their way.
All night long, people dance and sing.
In the early morning,
	the food that had been laid out for the dead is thrown into a river or into the sea
	as *it is considered unlucky for anyone living* to eat it.
In towns that are near the sea,
	the tiny lanterns which had been hung in the streets the night before,
		*are placed into* the water when the festival is over.
Thousands of lanterns slowly drift out to sea
	guiding the dead on their return journey to the other world.
This is a moving spectacle,
	for crowds of people stand on the shore
		watching the lanterns drifting away until they can be seen no more.

#+end_verse
** expression
festival [ˈfestɪv(ə)l] n.节目
lantern [ˈlæntə(r)n] n.灯笼
spectacle [ˈspektək(ə)l] n.景象,壮观,场面
moving [ˈmuvɪŋ] adj.

make a spectacle of oneself 出洋相
--------------------
return to sp. 回到某地
be expected to be 被期待做某事
sth. is laid out 某物被布置好了
it is considered unlucky for sb. doing 做某事被认为是不吉利的
be placed into 被放置进入

** words
festival [ˈfestɪv(ə)l] n.节日
lantern [ˈlæntə(r)n] n.灯笼
spectacle [ˈspektək(ə)l] n.景象,壮观,场面

** DONE 单词造句
CLOSED: [2023-10-18 Wed 19:52]
festival n.
- How long did the Spring Festival last for last year? He asked drily.
- The boy set the cron stalk on fire in the field at the festival.
- The building was burnt down at the festival.
- It says on the bulletin board. We're going on vacation at the festival.
- Don't get into such a mess at the Spring Festival.
lantern n.
- The workers are accustomed to make lanterns.
- I have been instructed in making lanterns.
- Thousands of lanterns were lined up on the floor of the square.
- He proved that there were a great many of lanterns in the basement.
- They compete against each other to make more lanterns.
spectacle n. make a spectacle of oneself
- Don't make a spectacle of yourself at the Spring festival.
- Although he made a spectacle of himself, he was still very popular with these young children.
- He who was reluctant to tell stories was making a spectacle of himself.
- He who is always late makes a spectacle of himself over and over again.
- The boy who failed to take the corn to pieces made a spectacle of himself.
moving adj.
- Didn't you find that story very moving?
- I hate to feel moving while I am watching a comedy.
- She was called in to tell a moving story.
- Instead of feeling moving, she got very angry.
- Soon afterwards, people all over the world know the building take its name from a moving story.
** DONE 反复听电影片段
CLOSED: [2023-10-19 Thu 19:45]
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-18 Wed 19:52]
return to sp.
- I am going to return to my hometown after I retire.
- The moment I get off work, I'll return to my home and watch TV.
- I used to return to my home running after the sunset.
- My mother usually orders me to return to my home as soon as possible.
- Mr. Leo was relieved to hear that I had returned to my home.
be expected to be
- My wife is expected to be angry.
- I am always expected to get a good salary.
- The students have been expected to be volunteers.
- The press was expected to tell people the truth.
- The busmen were not expected to go on a strike.
sth. is laid out
- Why is the food laid out?
- She has stated that thousands of mummy are laid out in the exhibition.
- A lot of vehicles are laid out on display.
- A variety of eating fishes are laid out for sale in the supermarket.
- He refused to lay out his precious pen.
it is considered unlucky for sb. doing
- It is considered unlucky for anyone touching the tree.
- It is considered unlucky for anyone having his hair cut.
- It is considered unlucky for him losing his life in a car accident.
- It is considered unlucky for the actor making a spectacle of himself.
- It is considered unlucky for him staying out of the limelight.
be placed into
- The parcel has already been placed into stones and sands.
- My garage was placed into a variety of furnitures the night before.
- The football was placed into water.
- I have trouble placing the lantern into water.
- The tent has been placed into the corn stalks.
** DONE 跟读至背诵
CLOSED: [2023-10-19 Thu 19:45]
** DONE Ask me if 写+读
CLOSED: [2023-10-19 Thu 19:50]
1. A Festival for the Dead is held in Japan. Where/What kind
	 Where is a Festival for the Dead held?
	 What kind of Festival is held in Japan?
2. It is held once a year. How often
		How often is it held?
3. The dead are said to return. Who
		Who are said to return?
4. They return to their homes. Where
		Where do they return?
5. They're welcomed by the living. Who
		Who are welcomed by the living?
6. Food is laid out for them. Who/What
	 Who is food laid out for?
	 What is laid out for them?
7. They're expected to be hungry. Who
	 Who are expected to be hungry?
8. Lanterns are specially made. What
	 What are specially made?
9. They're hung outside each house. Where
	 Where are they hung?
10. They're put there to help the dead. Why
		Why are they put there?
1- The living dance all night. How long
		How long do the living dance?
** DONE 摘要写作
CLOSED: [2023-10-19 Thu 20:02]
Japanese annual Festival for the dead is a cheerful occassion.
As the dead are said to return home,
	food is laid out for them
		and lanterns was lit to guide them on their way.
People dance and sing all night
	and the uneaten food is thrown into the sea or into a river the next morning.
In some places, the lanterns are placed on the sea
	and people watch from the shore until they drift out of sight.

Japanese annual Festival for the dead is a cheerful occassion,
	for the dead are said to return home.
Not only is food laid out for them,
	but lanterns are lit to guide them on their way as well
	while people dance and sing all night.
The uneaten food is thrown into the sea or into a river the next morning.
In some places, the lanterns are placed on the sea.
People watch them from the shore as they drift out of sight.

** DONE tell the story 口语
CLOSED: [2023-10-19 Thu 20:05]
** Topics for discussion
