#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 20th REAL GOOD IS SIMPLE
#+begin_verse
'Here's a way to think about what the masses regard as being 'good' things.
If you would first start by setting your mind upon things that are unquestionably good—wisdom,
  selfcontrol,
  justice,
  courage—with this preconception you'll no longer be able to listen to the popular refrain that there are too many good things to experience in a lifetime.
' —MARCUS AURELIUS,
  MEDITATIONS,
  5.12 s it that controversial to say that there are the things that people value (and pressure you to value as well)—and there are the things that are actually good? Or to question whether wealth and fame are all they are cracked up to be? As Seneca observed in one of his plays:
  'If only the hearts of the wealthy were opened to all!
How great the fears high fortune stirs up within them.
' For centuries,
  people have assumed that wealth would be a wonderful cure-all for their unhappiness or problems. Why else would they have worked so hard for it? But when people actually acquired the money and status they craved,
  they discovered it wasn't quite what they had hoped. The same is true of so many things we covet without really thinking. On the other hand,
  the 'good' that the Stoics advocate is simpler and more straightforward:
  wisdom,
  self-control,
  justice,
  courage.
No one who achieves these quiet virtues experiences buyer's remorse.
W
#+end_verse