#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 9th TEST YOUR IMPRESSIONS
#+begin_verse
'From the very beginning,
  make it your practice to say to every harsh impression,
  'you are an impression and not at all what you appear to be.
' Next,
  examine and test it by the rules you possess,
  the first and greatest of which is this—whether it belongs to the things in our control or not in our control,
  and if the latter,
  be prepared to respond,
  'It is nothing to me.
'' —EPICTETUS,
  ENCHIRIDION,
  1.
5 n an overly quantified world of policies and processes,
  some are swinging back in the other direction.
Bold leaders will 'trust their gut.' A spiritual guru will say that it's important to 'let your body guide you.' A friend trying to help us with a difficult decision might ask,
  'What feels right here?' These approaches to decision making contradict voluminous case studies in which people's instincts have led them right into trouble.
Our senses are wrong all the time!
As animals subjected to the slow force of evolution,
  we have developed all sorts of heuristics,
  biases,
  and emotional responses that might have worked well on the savannah but are totally counterproductive in today's world.
Part of Stoicism is cultivating the awareness that allows you to step back and analyze your own senses,
  question their accuracy,
  and proceed only with the positive and constructive ones.
Sure,
  it's tempting to throw discipline and order to the wind and go with what feels right—but if our many youthful regrets are any indication,
  what feels right right now doesn't always stand up well over time.
Hold your senses suspect.
Again,
  trust,
  but always verify.
T
#+end_verse