#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 19th OUR SPHERE OF IMPULSES
#+begin_verse
'Epictetus says we must discover the missing art of assent and pay special attention to the sphere of our impulses—that they are subject to reservation,
  to the common good,
  and that they are in proportion to actual worth.' —MARCUS AURELIUS,
  MEDITATIONS,
  11.
37 ere we have the emperor,
  the most powerful man in the world,
  quoting in his diary the wisdom of a former slave (and from what we know,
  Marcus might have had direct notes from Epictetus's lectures via one of his former students).
That wisdom was ultimately about surrender and serving the common good—about the limits of our power and the importance of checking our impulses—something every person in authority needs to hear.
Power and powerlessness seem so rarely to enter the same orbit—but when they do it can change the world.
Think about President Abraham Lincoln meeting with,
  corresponding with,
  and learning from Frederick Douglass,
  another former slave of considerable wisdom and insight.
In any case,
  all those men lived by the principles expressed here:
  that in our lives—whether we're experiencing great power or powerlessness —it's critical to leave room for what may happen and keep the common good and the actual worth of things front and center.
And,
  above all,
  be willing to learn from anyone and everyone,
  regardless of their station in life.
I
#+end_verse