#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 29th WASHING AWAY THE DUST OF LIFE
#+begin_verse
'Watch the stars in their courses and imagine yourself running alongside them. Think constantly on the changes of the elements into each other,
  for such thoughts wash away the dust of earthly life.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
47 t is almost impossible to stare up at the stars and not feel something.
As cosmologist Neil deGrasse Tyson has explained,
  the cosmos fills us with complicated emotions.
On the one hand,
  we feel an infinitesimal smallness in comparison to the vast universe;
  on the other,
  an extreme connectedness to this larger whole.
Obviously,
  given that we're in our bodies every day,
  it's tempting to think that's the most important thing in the world.
But we counteract that bias by looking at nature—at things much bigger than us.
A line from Seneca,
  which has since become a proverb,
  expresses Marcus's insight well:
  Mundus ipse est ingens deorum omnium templum (The world itself is a huge temple of all the gods).
Looking at the beautiful expanse of the sky is an antidote to the nagging pettiness of earthly concerns.
And it is good and sobering to lose yourself in that as often as you can.
I
#+end_verse