#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 26th THINGS HAPPEN IN TRAINING
#+begin_verse
'When your sparring partner scratches or head-butts you,
  you don't then make a show of it,
  or protest,
  or view him with suspicion or as plotting against you. And yet you keep an eye on him,
  not as an enemy or with suspicion,
  but with a healthy avoidance. You should act this way with all things in life. We should give a pass to many things with our fellow trainees. For,
  as I've said,
  it's possible to avoid without suspicion or hate.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
20 y seeing each day and each situation as a kind of training exercise,
  the stakes suddenly become a lot lower.
The way you interpret your own mistakes and the mistakes of others is suddenly a lot more generous.
It's certainly a more resilient attitude than going around acting like the stakes of every encounter put the championship on the line.
When you catch an elbow or an unfair blow today,
  shake off the pain and remind yourself:
  I'm learning.
My sparring partner is learning too.
This is practice for both of us—that's all.
I know a bit more about him or her,
  and from my reaction,
  they're going to learn a little bit more about me too.
S
#+end_verse