#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 28th WANTS MAKE YOU A SERVANT
#+begin_verse
'Tantalus:
  The highest power is— Thyestes:
  No power,
  if you desire nothing.' —SENECA,
  THYESTES,
  440 n the modern world,
  our interactions with tyranny are a bit more voluntary than they were in ancient times.
We put up with our controlling boss,
  though we could probably get a different job if we wanted.
We change how we dress or refrain from saying what we actually think?
Because we want to fit in with some cool group.
We put up with cruel critics or customers?
Because we want their approval.
In these cases,
  their power exists because of our wants.
You change that,
  and you're free.
The late fashion photographer Bill Cunningham occasionally declined to invoice magazines for his work.
When a young upstart asked him why that was,
  Cunningham's response was epic:
  'If you don't take money,
  they can't tell you what to do,
  kid.' Remember:
  taking the money,
  wanting the money—proverbially or literally—makes you a servant to the people who have it.
Indifference to it,
  as Seneca put it,
  turns the highest power into no power,
  at least as far as your life is concerned.
I
#+end_verse