#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 21st DON’T LET YOUR ATTENTION SLIDE
#+begin_verse
'When you let your attention slide for a bit,
  don't think you will get back a grip on it whenever you wish—instead,
  bear in mind that because of today's mistake everything that follows will be necessarily worse. . . . Is it possible to be free from error? Not by any means,
  but it is possible to be a person always stretching to avoid error. For we must be content to at least escape a few mistakes by never letting our attention slide.' —EPICTETUS,
  DISCOURSES,
  4.
12.
1;
  19 inifred Gallagher,
  in her book Rapt,
  quotes David Meyer,
  a cognitive scientist at the University of Michigan:
  'Einstein didn't invent the theory of relativity while he was multitasking at the Swiss patent office.' It came after,
  when he really had time to focus and study.
Attention matters—and in an era in which our attention is being fought for by every new app,
  website,
  article,
  book,
  tweet,
  and post,
  its value has only gone up.
Part of what Epictetus is saying here is that attention is a habit,
  and that letting your attention slip and wander builds bad habits and enables mistakes.
You'll never complete all your tasks if you allow yourself to be distracted with every tiny interruption.
Your attention is one of your most
#+end_verse