#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 16th OBSERVE CAUSE AND EFFECT
#+begin_verse
'Pay close attention in conversation to what is being said,
  and to what follows from any action. In the action,
  immediately look for the target,
  in words,
  listen closely to what's being signaled.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
4 hrough the work of the psychologist Albert Ellis,
  Stoicism has reached millions of people through what's known as cognitivebehavioral therapy (CBT).
As a form of a therapy,
  CBT helps patients identify destructive patterns in their thoughts and behavior so they can,
  over time,
  direct and influence them in a more positive direction.
Of course,
  Marcus Aurelius had no formal training in psychology,
  but his words here are as important as any doctor's.
He's asking you to become an observer of your own thoughts and the actions those thoughts provoke.
Where do they come from?
What biases do they contain?
Are they constructive or destructive?
Do they cause you to make mistakes or engage in behavior you later regret?
Look for patterns;
  find where cause meets effect.
Only when this is done can negative behavior patterns be broken;
  only then can real life improvements be made.
A
#+end_verse