#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 13th LESS IS MORE
#+begin_verse
'Don't act grudgingly,
  selfishly,
  without due diligence,
  or to be a contrarian. Don't overdress your thought in fine language. Don't be a person of too many words and too many deeds. . . . Be cheerful,
  not wanting outside help or the relief others might bring. A person needs to stand on their own,
  not be propped up.' —MARCUS AURELIUS,
  MEDITATIONS,
  3.
5 n most areas of life,
  the saying 'Less is more' stands true. For instance,
  the writers we admire tend to be masters of economy and brevity. What they leave out is just as important—sometimes more important—than what they leave in. There is a poem by Philip Levine titled 'He Would Never Use One Word Where None Would Do.
' And from Hamlet,
  the best of all—the retort from Queen Gertrude after a long,
  rhetorical speech from Polonius:
  'More matter with less art,
  ' she tells him. Get to the point! Imagine the emperor of Rome,
  with his captive audience and unlimited power,
  telling himself not to be a person of 'too many words and too many deeds.
' Let that be a reminder the next time you feel selfindulgent or a little full of yourself,
  the next time you feel like impressing people.T
#+end_verse