#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 23rd THE MIND IS ALL YOURS
#+begin_verse
'You have been formed of three parts—body,
  breath,
  and mind. Of these,
  the first two are yours insofar as they are only in your care. The third alone is truly yours.' —MARCUS AURELIUS,
  MEDITATIONS,
  12.
3 he body can be ravaged by disease or injured or disabled in a sudden accident.
It can be imprisoned or subjected to torture.
The breath can suddenly cease because our time has come,
  or because someone has taken it from us.
Breathing can grow labored because of exertion or illness as well.
But up until the very end,
  our mind is ours.
It's not that the other two parts of life that Marcus mentions—our body and our breath—don't matter.
They're just less 'ours' than our mind. You wouldn't spend much time fixing up a house that you rent,
  would you? Our mind is ours—free and clear. Let's make sure we treat it right.T
#+end_verse