#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 14th BECOMING AN EXPERT IN WHAT MATTERS
#+begin_verse
'Believe me,
  it's better to produce the balance-sheet of your own life than that of the grain market.' —SENECA,
  ON THE BREVITY OF LIFE,
  18.
3b he things that some people manage to be experts in:
  fantasy sports,
  celebrity trivia,
  derivatives and commodities markets,
  thirteenthcentury hygiene habits of the clergy.
We can get very good at what we're paid to do,
  or adept at a hobby we wish we could be paid to do.
Yet our own lives,
  habits,
  and tendencies might be a mystery to us.
Seneca was writing this important reminder to his father-in-law,
  who,
  as it happened,
  was for a time in charge of Rome's granary.
But then his position was revoked for political purposes.
Who really cares,
  Seneca was saying,
  now you can focus that energy on your inner life.
At the end of your time on this planet,
  what expertise is going to be more valuable—your understanding of matters of living and dying,
  or your knowledge of the '87 Bears? Which will help your children more— your insight into happiness and meaning,
  or that you followed breaking political news every day for thirty years?A
#+end_verse