#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* April 5th TRUST, BUT VERIFY
#+begin_verse
'First off,
  don't let the force of the impression carry you away. Say to it,
  'hold up a bit and let me see who you are and where you are from—let me put you to the test' .
.
.
' —EPICTETUS,
  DISCOURSES,
  2.18.24 ne of the wonders of your mind is the quickness with which it can comprehend and categorize things. As Malcolm Gladwell wrote in Blink,
  we are constantly making split-second decisions based on years of experience and knowledge as well as using the same skill to confirm prejudices,
  stereotypes,
  and assumptions. Clearly,
  the former thinking is a source of strength,
  whereas the latter is a great weakness. We lose very little by taking a beat to consider our own thoughts. Is this really so bad? What do I really know about this person? Why do I have such strong feelings here? Is anxiety really adding much to the situation? What's so special about __________? By asking these questions—by putting our impressions to the test as Epictetus recommends—we're less likely to be carried away by them or make a move on a mistaken or biased one. We're still free to use our instincts,
  but we should always,
  as the Russian proverb says,
  'trust,
  but verify.
'Y
#+end_verse