#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 7th FINDING THE RIGHT MENTORS
#+begin_verse
'We like to say that we don't get to choose our parents,
  that they were given by chance—yet we can truly choose whose children we'd like to be.' —SENECA,
  ON THE BREVITY OF LIFE,
  15.
3a e are fortunate enough that some of the greatest men and women in history have recorded their wisdom (and folly) in books and journals.
Many others have had their lives chronicled by a careful biographer—from Plutarch to Boswell to Robert Caro.
The literature available at your average library amounts to millions of pages and thousands of years of knowledge,
  insight,
  and experience.
Maybe your parents were poor role models,
  or you lacked a great mentor.
Yet if we choose to,
  we can easily access the wisdom of those who came before us—those whom we aspire to be like.
We not only owe it to ourselves to seek out this hard-won knowledge,
  we owe it to the people who took the time to record their experiences to try to carry on the traditions and follow their examples—to be the promising children of these noble parents.
E
#+end_verse