#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 26th TRY THE OPPOSITE
#+begin_verse
'What assistance can we find in the fight against habit? Try the opposite!' —EPICTETUS,
  DISCOURSES,
  1.
27.
4 iktor Frankl,
  the brilliant psychologist and Holocaust survivor,
  cured patients suffering from phobias or neurotic habits using a method he called 'paradoxical intention.' Let's say a patient couldn't sleep.
The standard therapy would have been something obvious,
  like relaxation techniques.
Frankl instead encouraged the patient to try not to fall asleep.
He found that shifting focus off the problem deflected the patient's obsessive attention away from it and allowed them to eventually sleep normally.
Fans of the TV show Seinfeld might remember an episode called 'The Opposite' where George Costanza magically improves his life by doing the opposite of whatever he'd normally do. 'If every instinct you have is wrong,
  ' Jerry says to him,
  'then the opposite would have to be right.
' The larger point is that sometimes our instincts or habits get stuck in a bad pattern that pushes us further from our natural,
  healthy selves. Now you shouldn't immediately toss out everything in your life— some stuff is working (you're reading this book!). But what if you explored opposites today? What if you broke the pattern?A
#+end_verse