#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 11th JUST DON’T MAKE THINGS WORSE
#+begin_verse
'How much more harmful are the consequences of anger and grief than the circumstances that aroused them in us!' —MARCUS AURELIUS,
  MEDITATIONS,
  11.
18.
8 he first rule of holes,
  goes the adage,
  is that 'if you find yourself in a hole,
  stop digging.' This might be the most violated piece of commonsense wisdom in the world.
Because what most of us do when something happens,
  goes wrong,
  or is inflicted on us is make it worse— first,
  by getting angry or feeling aggrieved,
  and next,
  by flailing around before we have much in the way of a plan.
Today,
  give yourself the most simple and doable of tasks:
  just don't make stuff worse.
Whatever happens,
  don't add angry or negative emotions to the equation.
Don't react for the sake of reacting.
Leave it as it is.
Stop digging.
Then plan your way out.
I
#+end_verse