#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 8th BRICK BY BORING BRICK
#+begin_verse
'You must build up your life action by action,
  and be content if each one achieves its goal as far as possible—and no one can keep you from this. But there will be some external obstacle! Perhaps,
  but no obstacle to acting with justice,
  self-control,
  and wisdom. But what if some other area of my action is thwarted? Well,
  gladly accept the obstacle for what it is and shift your attention to what is given,
  and another action will immediately take its place,
  one that better fits the life you are building.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
32 lite athletes in collegiate and professional sports increasingly follow a philosophy known as 'The Process.' It's a philosophy created by University of Alabama coach Nick Saban,
  who taught his players to ignore the big picture—important games,
  winning championships,
  the opponent's enormous lead—and focus instead on doing the absolutely smallest things well—practicing with full effort,
  finishing a specific play,
  converting on a single possession.
A season lasts months,
  a game lasts hours,
  catching up might be four touchdowns away,
  but a single play is only a few seconds.
And games and seasons are constituted by seconds.
If teams follow The Process,
  they tend to win.
They overcome obstacles and eventually make their way to the top without ever having focused on the obstacles directly.
If you follow The Process in your life —assembling the right actions in the right order,
  one right after another —you too will do well.
Not only that,
  you will be better equipped to make quick work of the obstacles along that path.
You'll be too busy putting one foot in front of the next to even notice the obstacles were there.
'R
#+end_verse