#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 9th SOLVE PROBLEMS EARLY
#+begin_verse
'There is no vice which lacks a defense,
  none that at the outset isn't modest and easily intervened—but after this the trouble spreads widely. If you allow it to get started you won't be able to control when it stops. Every emotion is at first weak. Later it rouses itself and gathers strength as it moves along—it's easier to slow it down than to supplant it.' —SENECA,
  MORAL LETTERS,
  106.
2b–3a ivers,
  ' Publilius Syrus reminds us with an epigram,
  'are easiest to cross at their source.
' That's what Seneca means too. The raging waters and deadly currents of bad habits,
  ill discipline,
  chaos,
  and dysfunction—somewhere they began as no more than just a slight trickle. Somewhere they are a placid lake or pond,
  even a bubbling underground spring. Which would you rather do—nearly drown in a dangerous crossing in a few weeks or cross now while it's still easy? It's up to you.T
#+end_verse