#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 1st ALWAYS HAVE A MENTAL REVERSE CLAUSE
#+begin_verse
'Indeed,
  no one can thwart the purposes of your mind—for they can't be touched by fire,
  steel,
  tyranny,
  slander,
  or anything.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
41 bstacles are a part of life—things happen,
  stuff gets in our way,
  situations go awry.
But nothing can stop the Stoic mind when it's operating properly,
  because in every course of action,
  it has retained 'a reverse clause.' What's that?
It's a backup option.
If a friend betrays us,
  our reverse clause is to learn from how this happened and how to forgive this person's mistake.
If we're thrown in prison,
  our reverse clause is that we can refuse to be broken by this change of events and try to be of service to our fellow prisoners.
When a technical glitch erases our work,
  our reverse clause is that we can start fresh and do it better this time.
Our progress can be impeded or disrupted,
  but the mind can always be changed—it retains the power to redirect the path.
Part of this is remembering the usual course of things—Murphy's Law states that 'if anything can go wrong,
  it will.' So we keep this reverse clause handy because we know we're probably going to have to use it.
No one can thwart that.
T
#+end_verse