#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 30th THE OBSTACLE IS THE WAY
#+begin_verse
'While it's true that someone can impede our actions,
  they can't impede our intentions and our attitudes,
  which have the power of being conditional and adaptable. For the mind adapts and converts any obstacle to its action into a means of achieving it. That which is an impediment to action is turned to advance action. The obstacle on the path becomes the way.' —MARCUS AURELIUS,
  MEDITATIONS,
  5.
20 oday,
  things will happen that will be contrary to your plans.
If not today,
  then certainly tomorrow.
As a result of these obstacles,
  you will not be able to do what you planned.
This is not as bad as it seems,
  because your mind is infinitely elastic and adaptable.
You have the power to use the Stoic exercise of turning obstacles upside down,
  which takes one negative circumstance and uses it as an opportunity to practice an unintended virtue or form of excellence.
If something prevents you from getting to your destination on time,
  then this is a chance to practice patience.
If an employee makes an expensive mistake,
  this is a chance to teach a valuable lesson.
If a computer glitch erases your work,
  it's a chance to start over with a clean slate.
If someone hurts you,
  it's a chance to practice forgiveness.
If something is hard,
  it is a chance to get stronger.
Try this line of thinking and see whether there is a situation in which one could not find some virtue to practice or derive some benefit.
There isn't one.
Every impediment can advance action in some form or another.
JULY DUTYT
#+end_verse