#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 28th NO SELF-FLAGELLATION NEEDED
#+begin_verse
'Philosophy calls for simple living,
  but not for penance—it's quite possible to be simple without being crude.' —SENECA,
  MORAL LETTERS,
  5.
5 arcus's meditations are filled with self-criticism and so are the writings of other Stoics.
It's important to remember,
  however,
  that that's as far as it goes.
There was no self-flagellation,
  no paying penance,
  no self-esteem issues from guilt or self-loathing.
You never hear them call themselves worthless pieces of crap,
  nor do they ever starve or cut themselves as punishment.
Their self-criticism is constructive.
Laying into yourself,
  unduly depriving yourself,
  punishing yourself —that's self-flagellation,
  not self-improvement.
No need to be too hard on yourself.
Hold yourself to a higher standard but not an impossible one.
And forgive yourself if and when you slip up.
'I
#+end_verse