#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 29th NO EXCUSES
#+begin_verse
'It is possible to curb your arrogance,
  to overcome pleasure and pain,
  to rise above your ambition,
  and to not be angry with stupid and ungrateful people—yes,
  even to care for them.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
8 was just born this way.
' 'I never learned anything different.
' 'My parents set a terrible example.
' 'Everyone else does it.
' What are these? Excuses that people use to justify staying as they are instead of striving to become better. Of course it's possible to curb our arrogance,
  control our anger,
  and be a caring person. How do you think others do it? Certainly their parents weren't perfect;
  they didn't come out of the womb incapable of ego or immune to temptation. They worked on it. They made it a priority. They solved it like they would solve any other problem:
  by dedicating themselves to finding a solution,
  making incremental progress until they did. They became who they are. Just like you can.T
#+end_verse