#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 20th CALM IS CONTAGIOUS
#+begin_verse
'If then it's not that the things you pursue or avoid are coming at you,
  but rather that you in a sense are seeking them out,
  at least try to keep your judgment of them steady,
  and they too will remain calm and you won't be seen chasing after or fleeing from them.' —MARCUS AURELIUS,
  MEDITATIONS,
  11.
11 here is a maxim that Navy SEALs pass from officer to officer,
  man to man.
In the midst of chaos,
  even in the fog of war,
  their battletested advice is this:
  'Calm is contagious.' Especially when that calm is coming from the man or woman in charge.
If the men begin to lose their wits,
  if the group is unsure of what to do next,
  it's the leader's job to do one thing:
  instill calm—not by force but by example.
That's who you want to be,
  whatever your line of work:
  the casual,
  relaxed person in every situation who tells everyone else to take a breath and not to worry.
Because you've got this.
Don't be the agitator,
  the paranoid,
  the worrier,
  or the irrational.
Be the calm,
  not the liability.
It will catch on.
I
#+end_verse