#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 13th LIFE IS A BATTLEFIELD
#+begin_verse
'Don't you know life is like a military campaign? One must serve on watch,
  another in reconnaissance,
  another on the front line. . . . So it is for us—each person's life is a kind of battle,
  and a long and varied one too. You must keep watch like a soldier and do everything commanded. . . . You have been stationed in a key post,
  not some lowly place,
  and not for a short time but for life.' —EPICTETUS,
  DISCOURSES,
  3.
24.
31–36 he writer Robert Greene often uses the phrase 'As in war,
  so in life.' It's an aphorism worth keeping close,
  because our life is a battle both literally and figuratively.
As a species,
  we fight to survive on a planet indifferent to our survival.
As individuals,
  we fight to survive among a species whose population numbers in the billions.
Even inside our own bodies,
  diverse bacteria battle it out.
Vivere est militare.
(To live is to fight.
) Today,
  you'll be fighting for your goal,
  fighting against impulses,
  fighting to be the person you want to be.
So what are the attributes necessary to win these many wars?
Discipline Fortitude Courage Clearheadedness Selflessness Sacrifice And which attributes lose wars?
Cowardice RashnessDisorganization Overconfidence Weakness Selfishness As in war,
  so these attributes matter in daily life.
T
#+end_verse