#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* June 12th A TRAINED MIND IS BETTER THAN ANY SCRIPT
#+begin_verse
'In this way you must understand how laughable it is to say,
  'Tell me what to do!
' What advice could I possibly give? No,
  a far better request is,
  'Train my mind to adapt to any circumstance.
' . . . In this way,
  if circumstances take you off script . . . you won't be desperate for a new prompting.' —EPICTETUS,
  DISCOURSES,
  2.
2.
20b–1;
  24b–25a t would be nice if someone could show us exactly what to do in every situation.
Indeed,
  this is what we spend a good portion of our lives doing:
  preparing for this,
  studying for that.
Saving for or anticipating some arbitrary point in the future.
But plans,
  as the boxer Mike Tyson pointed out,
  last only until you're punched in the face.
Stoics do not seek to have the answer for every question or a plan for every contingency.
Yet they're also not worried.
Why?
Because they have confidence that they'll be able to adapt and change with the circumstances.
Instead of looking for instruction,
  they cultivate skills like creativity,
  independence,
  self-confidence,
  ingenuity,
  and the ability to problem solve.
In this way,
  they are resilient instead of rigid.
We can practice the same.
Today,
  we will focus on the strategic rather than the tactical.
We'll remind ourselves that it's better to be taught than simply given,
  and better to be flexible than stick to a script.
T
#+end_verse