#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 13th FUELING THE HABIT BONFIRE
#+begin_verse
'Every habit and capability is confirmed and grows in its corresponding actions,
  walking by walking,
  and running by running . . . therefore,
  if you want to do something make a habit of it,
  if you don't want to do that,
  don't,
  but make a habit of something else instead. The same principle is at work in our state of mind. When you get angry,
  you've not only experienced that evil,
  but you've also reinforced a bad habit,
  adding fuel to the fire.' —EPICTETUS,
  DISCOURSES,
  2.
18.
1–5 e are what we repeatedly do,
  ' Aristotle said,
  'therefore,
  excellence is not an act but a habit.
' The Stoics add to that that we are a product of our thoughts ('Such as are your habitual thoughts,
  such also will be the character of your mind,
  ' Marcus Aurelius put it). Think about your activities of the last week as well as what you have planned for today and the week that follows. The person you'd like to be,
  or the person you see yourself as—how closely do your actions actually correspond to him or her? Which fire are you fueling? Which person are you becoming?I
#+end_verse