#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 20th QUALITY OVER QUANTITY
#+begin_verse
'What's the point of having countless books and libraries,
  whose titles could hardly be read through in a lifetime. The learner is not taught,
  but burdened by the sheer volume,
  and it's better to plant the seeds of a few authors than to be scattered about by many.' —SENECA,
  ON TRANQUILITY OF MIND,
  9.
4 here is no prize for having read the most books before you die.
Even if you were the most dedicated reader in the world—a book a day,
  even—your collection would probably never be bigger than a small branch library.
You'll never even come close to matching what's stored in the servers at Google Books or keep up with the hundreds of thousands of new titles published on Amazon each year.
What if,
  when it came to your reading and learning,
  you prioritized quality over quantity?
What if you read the few great books deeply instead of briefly skimming all the new books?
Your shelves might be emptier,
  but your brain and your life would be fuller.
T
#+end_verse