#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 25th WHERE TO FIND JOY
#+begin_verse
'Joy for human beings lies in proper human work. And proper human work consists in:
  acts of kindness to other human beings,
  disdain for the stirrings of the senses,
  identifying trustworthy impressions,
  and contemplating the natural order and all that happens in keeping with it.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
26 hen dog trainers are brought in to work with a dysfunctional or unhappy dog,
  they usually start with one question:
  'Do you take it for walks?' They ask because dogs were bred to do certain tasks—to do work—and when deprived of this essential part of their nature,
  they suffer and act out.
This is true no matter how spoiled and nice their life might be.
The same is true for humans.
When you hear the Stoics brush aside certain emotions or material luxuries,
  it's not because they don't enjoy them.
It's not because the Stoic life is one bereft of happiness or fun.
The Stoics simply mean to help us find our essence—to experience the joy of our proper human work.
H
#+end_verse