#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 22nd TODAY IS THE DAY
#+begin_verse
'You get what you deserve. Instead of being a good person today,
  you choose instead to become one tomorrow.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
22 'I don't complain about the lack of time . . . what little I have will go far enough. Today—this day—will achieve what no tomorrow will fail to speak about. I will lay siege to the gods and shake up the world.' —SENECA,
  MEDEA,
  423–425 e almost always know what the right thing is.
We know we should not get upset,
  that we shouldn't take this personally,
  that we should walk to the health food store instead of swinging by the drivethrough,
  that we need to sit down and focus for an hour.
The tougher part is deciding to do it in a given moment.
What stops us?
The author Steven Pressfield calls this force The Resistance.
As he put it in The War of Art,
  'We don't tell ourselves,
  'I'm never going to write my symphony.
' Instead we say,
  'I'm going to write my symphony;
  I'm just going to start tomorrow.
'' Today,
  not tomorrow,
  is the day that we can start to be good.
T
#+end_verse