#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 27th SWEAT THE SMALL STUFF
#+begin_verse
'Well-being is realized by small steps,
  but is truly no small thing.' —ZENO,
  QUOTED IN DIOGENES LAERTIUS,
  LIVES OF THE EMINENT PHILOSOPHERS,
  7.
1.
26 he famous biographer Diogenes Laertius attributes this quote to Zeno but admits that it might have also been said by Socrates,
  meaning that it may be a quote of a quote of a quote.
But does it really matter?
Truth is truth.
In this case,
  the truth is one we know well:
  the little things add up.
Someone is a good person not because they say they are,
  but because they take good actions.
One does not magically get one's act together—it is a matter of many individual choices.
It's a matter of getting up at the right time,
  making your bed,
  resisting shortcuts,
  investing in yourself,
  doing your work.
And make no mistake:
  while the individual action is small,
  its cumulative impact is not.
Think about all the small choices that will roll themselves out in front of you today.
Do you know which are the right way and which are the easy way?
Choose the right way,
  and watch as all these little things add up toward transformation.
I
#+end_verse