#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 2nd BE THE PERSON YOU WANT TO BE
#+begin_verse
'First tell yourself what kind of person you want to be,
  then do what you have to do. For in nearly every pursuit we see this to be the case. Those in athletic pursuit first choose the sport they want,
  and then do that work.' —EPICTETUS,
  DISCOURSES,
  3.
23.
1–2a n archer is highly unlikely to hit a target she did not aim for.
The same goes for you,
  whatever your target.
You are certain to miss the target if you don't bother to draw back and fire.
Our perceptions and principles guide us in the selection of what we want—but ultimately our actions determine whether we get there or not.
So yes,
  spend some time—real,
  uninterrupted time—thinking about what's important to you,
  what your priorities are.
Then,
  work toward that and forsake all the others.
It's not enough to wish and hope.
One must act—and act right.
M
#+end_verse