#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 23rd SHOW ME HOW TO LIVE
#+begin_verse
'Show me that the good life doesn't consist in its length,
  but in its use,
  and that it is possible—no,
  entirely too common—for a person who has had a long life to have lived too little.' —SENECA,
  MORAL LETTERS,
  49.
10b here's no need to show Seneca.
Show yourself.
That no matter how many years you're ultimately given,
  your life can be clearly and earnestly said to have been a long and full one.
We all know someone like that—someone we lost too early but even now think,
  If I could do half of what they did,
  I'll consider my life well lived.
The best way to get there is by focusing on what is here right now,
  on the task you have at hand—big or small.
As he says,
  by pouring ourselves fully and intentionally into the present,
  it 'gentle[s] the passing of time's precipitous flight.'W
#+end_verse