#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 19th LEARN, PRACTICE, TRAIN
#+begin_verse
'That's why the philosophers warn us not to be satisfied with mere learning,
  but to add practice and then training. For as time passes we forget what we learned and end up doing the opposite,
  and hold opinions the opposite of what we should.' —EPICTETUS,
  DISCOURSES,
  2.
9.
13–14 ery few people can simply watch an instructional video or hear something explained and then know,
  backward and forward,
  how to do it.
Most of us actually have to do something several times in order to truly learn.
One of the hallmarks of the martial arts,
  military training,
  and athletic training of almost any kind is the hours upon hours upon hours of monotonous practice.
An athlete at the highest level will train for years to perform movements that can last mere seconds—or less.
The two-minute drill,
  how to escape from a chokehold,
  the perfect jumper.
Simply knowing isn't enough.
It must be absorbed into the muscles and the body.
It must become part of us.
Or we risk losing it the second that we experience stress or difficulty.
It is true with philosophical principles as well.
You can't just hear something once and expect to rely on it when the world is crashing down around us.
Remember,
  Marcus Aurelius wasn't writing his meditations for other people.
He was actively meditating for himself.
Even as a successful,
  wise,
  and experienced man,
  he was until the last days of his life practicing and training himself to do the right thing.
Like a black belt,
  he was still showing up to the dojo every day to roll;
  like a professional athlete,
  he still showed up to practice each week—even though others probably thought it was unnecessary.
T
#+end_verse