#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 3rd SHOW, NOT TELL, WHAT YOU KNOW
#+begin_verse
'Those who receive the bare theories immediately want to spew them,
  as an upset stomach does its food. First digest your theories and you won't throw them up. Otherwise they will be raw,
  spoiled,
  and not nourishing. After you've digested them,
  show us the changes in your reasoned choices,
  just like the shoulders of gymnasts display their diet and training,
  and as the craft of artisans show in what they've learned.' —EPICTETUS,
  DISCOURSES,
  3.
21.
1–3 any of the Stoic aphorisms are simple to remember and even sound smart when quoted.
But that's not what philosophy is really about.
The goal is to turn these words into works.
As Musonius Rufus put it,
  the justification for philosophy is when 'one brings together sound teaching with sound conduct.' Today,
  or anytime,
  when you catch yourself wanting to condescendingly drop some knowledge that you have,
  grab it and ask:
  Would I be better saying words or letting my actions and choices illustrate that knowledge for me?
T
#+end_verse