#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* May 17th THE STOIC IS A WORK IN PROGRESS
#+begin_verse
'Show me someone sick and happy,
  in danger and happy,
  dying and happy,
  exiled and happy,
  disgraced and happy. Show me! By God,
  how much I'd like to see a Stoic. But since you can't show me someone that perfectly formed,
  at least show me someone actively forming themselves so,
  inclined in this way. . . . Show me!' —EPICTETUS,
  DISCOURSES,
  2.
19.
24–25a,
  28 nstead of seeing philosophy as an end to which one aspires,
  see it as something one applies.
Not occasionally,
  but over the course of a life —making incremental progress along the way.
Sustained execution,
  not shapeless epiphanies.
Epictetus loved to shake his students out of their smug satisfaction with their own progress.
He wanted to remind them—and now you—of the constant work and serious training needed every day if we are ever to approach that perfect form.
It's important for us to remember in our own journey to selfimprovement:
  one never arrives.
The sage—the perfect Stoic who behaves perfectly in every situation—is an ideal,
  not an end.
I
#+end_verse