#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 1-1 MOOC overview
#+begin_verse
Welcome to the Positive Psychiatry online course
	created by the Education Department at the Brain and Mind Center, University of Sydney.
We are a team of three psychiatrists
	who are passionate about community education as a means of empowerment.
That is Associate Professor Louise Nash, Associate Professor Loyola McLean, and myself.
We have brought together a large number of Australia's leading experts
		from psychiatry, psychology, and mental health research,
	to share their ideas.
We'll also hear from experts by experience - people
	who have lived with mental illness and share their stories of personal recovery.
	
Good mental health is about feeling good and functioning well.
And positive psychiatry is about building strength as well as fixing problems.
The course will also cover the fundamentals of mental illness
	and practical strategies for staying strong and enhancing well-being.
The course is organized into five modules, each designed to be covered in one week.

In the first module, we meet Tina,
	a lived experience and recovery expert who tells the first part of her story.
This module will cover positive mental health, stress, and resilience,
	and some of the important findings from Aristotle
		through to recent research on the correlates of happiness.
		
The second module is about the body and mind.
We will learn about the central importance of physical health and lifestyle,
	and how exercise can be used as an evidence-based treatment for common mental health conditions.
We will cover basic relaxation and mindfulness strategies,
	as well as personality strengths and how to identify your own strengths.
	
In the third module we talk about love and work,
	and introduce the complementary ideas of rest and play.
We will hear about attachment theory, social connections,
	and the ancient wisdom of Australian Aboriginal views on well-being.
We discuss the importance of contributing,
	and here you will find out whether or not work is good for you.
	
In the fourth module, we cover the major categories of mental illness;
	their symptoms, causes, and treatments.
This includes the more common conditions such as anxiety, depression, and addictions,
	as well as less common mental illness such as psychosis, schizophrenia, and bipolar disorder.
	
Our fifth and final module in this course will detail some of the many paths to recovery.
From early intervention through the philosophy of personal recovery, consumer support networks,
	creative arts as therapy, as well as spiritual and religious practices.
	
Within each module there will be many lectures and links to recommended readings.
There will be self-assessment questionnaires
	and practical homework tasks including SMART goal setting.
Assessments include quizzes and peer marked short answer questions.

So join us for the next five weeks on a shared journey of learning towards better mental health
	and better understanding of this fundamental aspect of our well-being.
#+end_verse
** expression
psychiatry [sɪˈkaɪətri] psychiatrist: n.n.the study and treatment of mental illnesses ⇨ psychology精神病学
brain [breɪn]: n. the organ inside your head that controls how you think, feel, and move脑
associate [əˈsoʊʃiət]: n. someone who you work or do business with SYN colleague合作人
strength [streŋθ]: n. the physical power and energy that makes someone strong OPP weakness优势
lifestyle [ˈlaɪfˌstaɪl]: n. the way a person or group of people live, including the place they live in, the things they own, the kind of job they do, and the activities they enjoy生活方式
mindfulness : n. 正念
complementary [ˌkɑmpləˈment(ə)ri]: adj. complementary things go well together, although they are usually different补充的, 补足的
category [ˈkætəɡəri]: n. a group of people or things that are all of the same type种类
anxiety [æŋˈzaɪəti]: n. the feeling of being very worried about something SYN concern焦虑
depression [dɪˈpreʃ(ə)n]: n. a medical condition that makes you very unhappy and anxious and often prevents you from living a normal life抑郁
psychosis [saɪˈkoʊsɪs]: n. a serious mental illness that can change your character and make you unable to behave in a normal way ⇨ psychotic精神错乱
schizophrenia [ˌskɪtsəˈfriniə]: n. a serious mental illness in which someone’s thoughts and feelings are not based on what is really happening around them[心]精神分裂症
bipolar [ˌbaɪˈpoʊlər]: adj. bipolar disorder technical ↑manic depression狂躁的
intervention [ˌɪntərˈvenʃ(ə)n]: n. the act of becoming involved in an argument, fight, or other difficult situation in order to change what happens干涉
quiz [kwɪz]: n. a competition or game in which people have to answer questions测验
peer [pɪr]: n. formal your peers are the people who are the same age as you, or who have the same type of job, social class etc同伴
--------------------
be passionate about sth.: 对某事充满热情
** ch.
1-1 慕课概述

欢迎来到由悉尼大学大脑与心智中心教育部创建的积极精神病学在线课程。
我们是一支由三位精神科医生组成的团队，热衷于通过社区教育来赋权大众。
他们是路易丝·纳什副教授、洛约拉·麦克莱恩副教授，以及我本人。
我们汇集了澳大利亚众多精神病学、心理学和心理健康研究领域的顶尖专家，与大家分享他们的见解。
我们还将听取“经验专家”的声音——那些曾经历精神疾病并分享个人康复故事的人。

良好的心理健康意味着感觉良好并具备良好的功能。
而积极精神病学不仅关注解决问题，还强调如何培养心理韧性与优势。
本课程还将涵盖精神疾病的基本知识，以及保持心理健康和提升幸福感的实用策略。
课程共分为五个模块，每个模块的设计都适用于一周的学习。

在第一模块中，我们将认识蒂娜——一位有着亲身经历的康复专家，她将讲述自己的故事。
本模块将探讨积极心理健康、压力与韧性，以及从亚里士多德到当代幸福感相关研究的重要发现。

第二模块关注身心健康。
我们将学习身体健康与生活方式对心理健康的重要性，并探讨运动如何作为循证治疗方法来应对常见心理健康问题。
本模块还将介绍基础放松技巧、正念策略，以及性格优势与如何识别自己的优势。

第三模块涉及爱与工作，并引入“休息与娱乐”这两个互补概念。
我们将学习依恋理论、社会联系，以及澳大利亚原住民关于幸福的古老智慧。
此外，我们还将探讨贡献的价值，并帮助你思考工作是否对你有益。

第四模块将介绍主要的精神疾病类别，包括其症状、成因和治疗方法。
涵盖内容包括焦虑、抑郁、成瘾等常见疾病，以及精神病、精神分裂症和双相情感障碍等较少见的精神疾病。

第五模块是本课程的最后一部分，我们将探讨多种康复路径。
内容包括早期干预、个人康复理念、患者支持网络、艺术治疗，以及精神与宗教实践等。

在每个模块中，都将包含多场讲座及推荐阅读材料的链接。
同时，还会有自我评估问卷和实践作业，例如SMART 目标设定。
评估内容包括测验以及由同伴评分的简答题。

欢迎加入我们的五周学习旅程，一起探索心理健康的奥秘，
共同提升对这一基本生命要素的理解！
** sentence
psychiatry [sɪˈkaɪətri] psychiatrist: n.n.the study and treatment of mental illnesses ⇨ psychology精神病学
- I am looking for a sophicated psychiatrist who can treat my father. 
- My grandmother living a long life in a village attributes my father's psychiatry to his disrespect to the god.
- Due to my father's psychiatry, my mother got divorced with him and left me since I was 3 years old.
brain [breɪn]: n. the organ inside your head that controls how you think, feel, and move脑
- The scientist is underway to research humanity brains.
- The scientist is trying to carry the monkey's brain far away from the village.
- It is believed that somewhere raw monkey's brains are regarded as delicacy.
associate [əˈsoʊʃiət]: n. someone who you work or do business with SYN colleague合作人
- Due to his brother's death, he is unwilling to be an associate of the corporation.
- Imagine being an associate of the famous corporation and working with these beautiful girls.
- What the associate have done in the court inspired awe in every attorneys in this corporation. 
strength [streŋθ]: n. the physical power and energy that makes someone strong OPP weakness优势
- Hordes of children have found their strengths in our workshops.
- You have forgot about the only strenth of a singer mother.
- Listen up, the associate is talking about your strengths and weaknesses.
lifestyle [ˈlaɪfˌstaɪl]: n. the way a person or group of people live, including the place they live in, the things they own, the kind of job they do, and the activities they enjoy生活方式
- After he was in the Hall of Fame basketball player, his lifestyle eventually have been changed.
- At the some point, the boxer who was adored by poor and rich alike had changed his lifestyle totally.
- In theory, you don't need to change your lifestyle after your retirement.
mindfulness : n. 正念
- Obviously, he has got to a mindfulness state.
- The ancient sport turns into an effective mindfulness exercise.
- The religious mindfulness exercise, thousands of years in the making, survives intact.
complementary [ˌkɑmpləˈment(ə)ri]: adj. complementary things go well together, although they are usually different补充的, 补足的
- The snacks are complementary and rice still remains the domain of your food.
- The mob is hanging around looking for some complementary money in the street.
- The complementary energy has slowed down the deterioration of the station.
category [ˈkætəɡəri]: n. a group of people or things that are all of the same type种类
- There are five categories of fruits decaying away in the warehouse.
- The associate will give you more time to deal with categories of cases.
- You are lucky enough to touch categories of cases in the first year of your job.
anxiety [æŋˈzaɪəti]: n. the feeling of being very worried about something SYN concern焦虑
- What's your next move for your anxiety inspired by your enemies?
- Saturated with anxiety, I am not able to fall asleep at night.
- Bit by bit anxiety is destorying the eminent lawyer.
depression [dɪˈpreʃ(ə)n]: n. a medical condition that makes you very unhappy and anxious and often prevents you from living a normal life抑郁
- The stuff precipitated out of these waters can treat depression. 
- I hope you treat your depression not in a pathological way.
- The psychiatrist created a perfect cast of this category of depression.
psychosis [saɪˈkoʊsɪs]: n. a serious mental illness that can change your character and make you unable to behave in a normal way ⇨ psychotic精神错乱
- You're not in the clear yet because your father is with psychosis.
- The patient with psychosis claimed to be seeing a mountain range.
- Any patient with psychosis will receive a warm welcome in the long-term care facility.
schizophrenia [ˌskɪtsəˈfriniə]: n. a serious mental illness in which someone’s thoughts and feelings are not based on what is really happening around them[心]精神分裂症
- His father with schizophrenia is scouting for enemies.
- The patient with schizophrenia hopes for a man who agrees with him.
- The patient with schizophrenia is trying to whack away the stone wall.
bipolar [ˌbaɪˈpoʊlər]: adj. bipolar disorder technical ↑manic depression狂躁的
- He has been diagnosed with bipolar disorder.
- We found the patient with bipolar disorder lying on a creek bank.
- The patient with bipolar disorder extracted the candy from the box.
intervention [ˌɪntərˈvenʃ(ə)n]: n. the act of becoming involved in an argument, fight, or other difficult situation in order to change what happens干涉
- Your husband's intervention in this case made it more difficult for us to exile the criminal.
- Your intervention makes me not able to concentrate on the game.
- The spokesman is accusing USA of intervention in other country's internal affairs.
quiz [kwɪz]: n. a competition or game in which people have to answer questions测验
- The quiz is full of dense and boring questions.
- An estimated 5 percent of students in our class can pass the quiz.
- The quiz is used to test your reading skills.
peer [pɪr]: n. formal your peers are the people who are the same age as you, or who have the same type of job, social class etc同伴
- Your peer is telling us funny stories at the party.
- It was embarrassing that your peer behaved so rude in the wedding.
- I am looking for my peer who was just telling pirate stories to you guys.
--------------------
be passionate about sth.: 对某事充满热情
- I am passionate about taking care of my cat beyond doubt.
- He is passionate about making surprises for his beautiful girlfriend.
- The programmer is so passionate about whoring that he has been called by police.
** sentence2
psychiatry [sɪˈkaɪətri] psychiatrist: n.n.the study and treatment of mental illnesses ⇨ psychology精神病学
- I am looking for a sophisticated psychiatrist who can treat my father. 
- My grandmother living a long life in a village attributes my father's psychiatry to his disrespect to the god.
- Due to my father's psychiatry my mother divorced him and left me when I was 3 years old.
brain [breɪn]: n. the organ inside your head that controls how you think, feel, and move脑
- The scientist is underway to research humanity's brains.
- The scientist is trying to carry the monkey's brain far away from the village.
- It is believed that somewhere raw monkey brains are regarded as a delicacy.
associate [əˈsoʊʃiət]: n. someone who you work or do business with SYN colleague合作人
- Due to his brother's death, he is unwilling to be an associate of the corporation.
- Imagine being an associate of a famous corporation and working with these beautiful girls.
- What the associate has done in the court inspired awe in every attorney in this corporation. 
strength [streŋθ]: n. the physical power and energy that makes someone strong OPP weakness优势
- Hordes of children have found their strengths in our workshops.
- You have forgotten about the only strength of a singer mother.
- Listen up, the associate is talking about your strengths and weaknesses.
lifestyle [ˈlaɪfˌstaɪl]: n. the way a person or group of people live, including the place they live in, the things they own, the kind of job they do, and the activities they enjoy生活方式
- After he was in the Hall of Basketball Players Fame, his lifestyle eventually has been changed.
- At some point, the boxer who was adored by poor and rich alike had changed his lifestyle totally.
- In theory, you don't need to change your lifestyle after your retirement.
mindfulness: n. 正念
- Obviously, he has got to a mindfulness state.
- The ancient sport turns into an effective mindfulness exercise.
- The religious mindfulness exercise, thousands of years in the making, survives intact.
complementary [ˌkɑmpləˈment(ə)ri]: adj. complementary things go well together, although they are usually different补充的, 补足的
- The snacks are complementary and rice still remains the domain of your food.
- The mob is hanging around looking for some complementary money in the street.
- The complementary energy has slowed down the deterioration of the station.
category [ˈkætəɡəri]: n. a group of people or things that are all of the same type种类
- There are five categories of fruits decaying away in the warehouse.
- The associate will give you more time to deal with categories of cases.
- You are lucky enough to touch categories of cases in the first year of your job.
anxiety [æŋˈzaɪəti]: n. the feeling of being very worried about something SYN concern焦虑
- What's your next move for your anxiety inspired by your enemies?
- Saturated with anxiety, I am not able to fall asleep at night.
- Bit by bit anxiety is destroying the eminent lawyer.
depression [dɪˈpreʃ(ə)n]: n. a medical condition that makes you very unhappy and anxious and often prevents you from living a normal life抑郁
- The stuff precipitated out of these waters can treat depression. 
- I hope you treat your depression not in a pathological way.
- The psychiatrist created a perfect cast of this category of depression.
psychosis [saɪˈkoʊsɪs]: n. a serious mental illness that can change your character and make you unable to behave in a normal way ⇨ psychotic精神错乱
- You're not in the clear yet because your father is with psychosis.
- The patient with psychosis claimed to be seeing a mountain range.
- Any patient with psychosis will receive a warm welcome in the long-term care facility.
schizophrenia [ˌskɪtsəˈfriniə]: n. a serious mental illness in which someone’s thoughts and feelings are not based on what is really happening around them[心]精神分裂症
- His father with schizophrenia is scouting for enemies.
- The patient with schizophrenia hopes for a man who agrees with him.
- The patient with schizophrenia is trying to whack away the stone wall.
bipolar [ˌbaɪˈpoʊlər]: adj. bipolar disorder technical ↑manic depression狂躁的
- He has been diagnosed with bipolar disorder.
- We found the patient with bipolar disorder lying on a creek bank.
- The patient with bipolar disorder extracted the candy from the box.
intervention [ˌɪntərˈvenʃ(ə)n]: n. the act of becoming involved in an argument, fight, or other difficult situation in order to change what happens干涉
- Your husband's intervention in this case made it more difficult for us to exile the criminal.
- Your intervention makes me not able to concentrate on the game.
- The spokesman is accusing the USA of intervening in other country's internal affairs.
quiz [kwɪz]: n. a competition or game in which people have to answer questions测验
- The quiz is full of dense and boring questions.
- An estimated 5 percent of students in our class can pass the quiz.
- The quiz is used to test your reading skills.
peer [pɪr]: n. formal your peers are the people who are the same age as you, or who have the same type of job, social class etc同伴
- Your peer is telling us funny stories at the party.
- It was so embarrassing that your peer behaved rudely at the wedding.
- I am looking for my peer who was just then telling pirate stories to you guys.
--------------------
be passionate about sth.: 对某事充满热情
- I am passionate about taking care of my cat beyond doubt.
- He is passionate about making surprises for his beautiful girlfriend.
- The programmer is so passionate about whoring that he has been called by police.
