#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-2 4 Trauma
#+begin_verse
Ourselves develop in relationship.
Initially, in attachment relationships in early childhood.
And then later, in the world of social connection.
This development is in every aspect of our being:
	physical, psychological, emotional, cultural, spiritual.
This connectedness for development and well-being is a theme
	you have been hearing about throughout the MOOC.
When we have flowing and lively sense of self, we tend to feel well and tend to flourish.

This talk however is about trauma,
	and trauma is a difficult subject because it's a difficult experience.
Trauma breaks down our being, our sense of self.
	And can break down how we feel about ourselves, others, and the world.
So, it's an important experience that impacts profoundly on our well-being.
We could think back to Tina's story in the first week of our MOOC,
	and the impact of childhood trauma on her sense of self,
	and her important and long road to recovery.
For a time, we didn't pay enough attention to just how common and just how damaging trauma could be.
We didn't realize just how many people seeking or needing help
	for their mental health had been impacted on by trauma.
Sometimes, sadly, the experience of mental illness and its treatment was traumatic in itself.

The good news is that we're in a time where we are realizing the huge impacts of trauma,
	and are actively developing our approach to it
		to help people, families, and communities recover and return to thriving.
In a phenomenon called post-traumatic growth,
	we can actually grow through trauma and eventually become stronger, more resilient than before.
This was Tina's story and it is the story of many.
We are realizing
	that repair, recovery, resilience, require us to foster personal and interpersonal connections,
	and over time integrate traumatic experiences into a new story of our self and a new way of being.
We both repay the old aspects of self and the old connections and we nurture the new.
I often think of this is the way trees heal.
The rings they lay down at their core will always tell the story of a tough year.
But if the tree survives, it often becomes stronger than before.
We are more than the story of our traumatic times.
We are people that reflect on ourselves and make meaning of our experiences and so,
	our recovery can be rich at multi-layered.
	
So what is trauma?
We certainly all have stress.
And we've heard about how universalities and ways to manage it are discussed in other MOOC talks.
The trauma is however more than simple stress.
It is a highly stressful life event or actually cumulative amount of stress
	that exceeds a person's capacity to regulate themselves and manage in the face of it.
So the event disturbs their equilibrium or what we call 'Homeostasis'.

Traumatic events include single events like a serious accident, assault, or disaster.
And also include long term situations like domestic violence, entrapment, or child abuse.
The stress diathesis model is central to understanding the distress
	associated with onset of mental health problems and stress system disorders.
It says that everyone has a level of risk for disorders to which stress adds.
And where there's enough of it, symptoms and disorders emerge.

A self-regulation involves every level of being.
So when trauma breaks it down, it can happen at any or all of these parts of our life.
Part of being tuned in to trauma is a challenge to health.
It's to recognize that I might notice the effects on my body,
	my mind, my relationships, my cultural life, or my spiritual life.
And those who know me or work with me might feel that in those areas
	where we come into contact and connection.
This recognition of trauma or in its effects is a crucial current issue in health.
Trauma can break down how we connect to others
	and tell our story and breakdown our trust in the world.
	
When trauma happens in childhood and adolescence.
In the very relationships of care in a home or community
		that is meant to keep us safe and help us grow,
	it can impact on how we develop and regulate ourselves in adulthood.
It can then become a risk factor in mental and physical health.
The big ace study in the USA investigating these adverse childhood experiences
	showed the knock-on effects on mental and physical health of childhood trauma.
So, post traumatic stress disorder
		which can follow experiencing or witnessing a single life threatening event
	is an important disorder.
Features of PTSD include nightmares, flashbacks, anxiety,
	and a tendency to avoid reminders of the trauma.
People with PTSD often have insomnia and/or depression,
	or use substances to try to deal with the symptoms.
However, we now understand that the most severe dysregulation occurs in people
	who as children lack a consistent caregiver or adequate experiences of safety and comfort.
The cumulative effect of this kind of trauma is called 'Complex trauma'
	and is a big contributor to many mental health disorders.
	
We need positive connection.
So for example, even daily devaluation in childhood, or neglect, can lead to an ongoing sense
	that I'm not worthwhile and impact my attachment state of mind and how I view myself.
Trauma causes shock, numbness, and feel
	and can cause dissociation or disconnection in the individual experiencing it,
		and those around them.
Dissociation describes the disconnection or disorganization of parts of mental and physical life
	that would normally be connected and healthily organized.
For some people these disconnections, dissociations or disorganizations are very severe.
For example, those with dissociative identity disorder
	can be disconnected from whole parts of themselves
		that then function at times as another state of self.
This problem with remembering who they are at different times
	can be very confusing for them and for those around them.
Strong feelings of confusion, disorientation, rage, disgust, helplessness, hopelessness,
	can emerge too.
The strong feelings and dissociation around trauma probably partly explain
	why trauma has often been hard to examine or recognize
		and can lie out of direct sight, out of mind.
When trauma happens in secrecy like abuse often does,
	then the difficulty in recognizing it and in seeing it is compounded.
	
These days we're trying to develop trauma-informed care,
	ways of caring for others and ourselves
		that understand how trauma breaks down consciousness and self.
And then, explores the pathways back to feeling whole and to flourishing.
Now, we often talk about a faith based approach to treatment.
Fundamentally, we first have to establish safety for those experiencing trauma,
	and the families and systems of care around them.
You can probably imagine that if I have grown up in an unsafe home or community,
	that safety might take a while to set up.
This step requires the listening, validation, and tuning in of carers and clinicians.
We take time to notice if someone is terrified and engage them in ways that help them feel safer.
After safety comes stabilization where we try to help the person find ways to feel supported.
Ways that can help them manage safely, to minimize the ongoing breakdown effects of trauma.
This helps them move away from other unsafe strategies like drugs and alcohol or self-harm.
Here some of the skills and strategies discussed in the MOOC
	can be crucial in fostering calm and hope, and settling down our body and mind
		which might be feeling terrified, anxious, angry, or frozen.
Here, relaxation, breathing, exercise, being validated in a caring relationship,
	mindfulness and meditation are some ways that help.
Each person needs the strategies to fit well with them.
And practicing them may also take some time.

Then, and only then, when we feel ready and supported,
	can we then think, feel, and work through what happened to us in a number of ways.
As trauma affects all aspects of being.
Any of these can be an initial window into recovery.
Trauma-focused cognitive behavior therapy and Eye Movement Desensitization
	are types of psychotherapy used for PTSD.
Body therapies, creative therapies, other psychotherapies, and neurofeedback can all have a place.
For some spiritual frame is important.
Something like meditation can work in a number of levels
	to bring about reconnection and new connections between mind and body.
So, integrative approaches help us
		counter the disconnections in mind, body, and soul caused by trauma
	and help us become whole again.
Those who've been through trauma need support to recover.
But sometimes they need time and evidence to believe that they can trust others again.
Trust the care we offer and even trust themselves.
Yet, we can resolve trauma to recover, grow from it, and flourish.
And it seems that the best way to do this is to do it together in safe company.
We don't have to do it alone.
#+end_verse
** expression
initially [ɪˈnɪʃ(ə)li]: adv. at the beginning最初, 开头
connectedness [kə'nektɪdnəs]: n. the feeling people have that they are members of a group in society and that they share particular qualities with other members of that group归属感
thrive [θraɪv]: v. to become very successful or very strong and healthy兴旺
repay [rɪˈpeɪ]: v. to pay back money that you have borrowed偿还, 报答, 报复
nurture [ˈnɜrtʃər]: v. to help a plan, idea, feeling etc to develop培育
heal [hil]: v. to make someone who is ill become healthy again, especially by using natural powers or prayer ⇨ cure治愈, 医治
exceed [ɪkˈsid]: v. to be more than a particular number or amount超越, 胜过
equilibrium [ˌekwɪˈlɪbriəm]: n. a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly平衡,均衡
assault [əˈsɔlt]: v. the crime of physically attacking someone侵犯
entrapment [ɪnˈtræpmənt]: n. the practice of trapping someone by tricking them, especially to show that they are guilty of a crime诱捕的行动,圈套
diathesis [daɪ'æθɪsɪs]: n. (易患某病)素质
adverse [ædˈvɜrs]: adj. not good or favourable不利的
flashback [ˈflæʃˌbæk]: n. a sudden very clear memory of something that happened to you in the past闪回
nightmare [ˈnaɪtˌmer]: n. a very frightening dream恶梦
consistent [kənˈsɪstənt]: adj. always behaving in the same way or having the same attitudes, standards etc – usually used to show approval OPP inconsistent一致的
numb [nʌm] numbness: adj.n. a part of your body that is numb is unable to feel anything, for example because you are very cold麻木的
dissociative [dɪ'soʊʃɪˌeɪtɪv]: adj. 分离的,游离的
compound [ˈkɑmˌpaʊnd]: v. to make a difficult situation worse by adding more problems恶化,加重
clinician [klɪˈnɪʃ(ə)n]: n. a doctor who treats and examines people, rather than one who does ↑research临床医生
--------------------
break down sth.: 破坏某事物
For a time, + ...: 一度
integrate A into B: 整合A进B
make meaning of sth.: 使某事物有意义
be meant to do sth.: 打算做某事
the knock on effects: 连锁反应
in secrecy: in secret秘密地
tune in of sb.: 聆听某人
have a place (in ...): 有一席之地
** ch.
4-2 4 创伤
我们在关系中发展自己。
最初是在幼儿期的依附关系中发展，然后在社会连接的世界中发展。
这种发展贯穿我们每个方面的存在：身体的、心理的、情感的、文化的、精神的。
为了发展和福祉的这种连接性是你在整个MOOC课程中一直听到的主题。
当我们拥有流动且充满活力的自我意识时，我们通常会感觉良好，并且往往会蓬勃发展。
然而，这次讲座是关于创伤的，创伤是一个困难的话题，因为它是一个困难的经历。
创伤打破我们的存在，打破我们的自我意识，并可能打破我们对自己、他人和世界的感受。
因此，它是一个对我们福祉产生深远影响的重要经历。
我们可以回想一下MOOC第一周中Tina的故事，儿童期创伤对她自我意识的影响，以及她重要且漫长的恢复之路。
曾几何时，我们没有足够重视创伤的普遍性和破坏性。
我们没有意识到有多少寻求或需要心理健康帮助的人受到了创伤的影响。
有时，令人遗憾的是，心理疾病的经历和治疗本身就具有创伤性。
好消息是，我们正处于一个认识到创伤巨大影响的时代，并且正在积极发展我们的应对方法，帮助个人、家庭和社区恢复并重新蓬勃发展。
在一种叫做创伤后成长的现象中，我们实际上可以通过创伤成长，并最终变得比以前更强大、更有韧性。
这是Tina的故事，也是许多人的故事。
我们正在认识到，修复、恢复、韧性需要我们培养个人和人际连接，并随着时间的推移，将创伤经历融入到我们自我和新的存在方式的故事中。
我们既赎回了自我的旧方面和旧的联系，也滋养了新的方面。
我常常认为这就像树木的愈合。
它们在核心部位形成的年轮永远讲述着艰难的年份的故事。
但如果树木存活下来，它通常会比以前更强壮。
我们不仅仅是创伤时期故事的延续。
我们是那些反思自我并赋予经历意义的人，因此，我们的恢复可以是丰富而多层次的。
那么，什么是创伤呢？
我们当然都有压力。
我们已经听到过其他MOOC讲座中关于压力的普遍性和管理方式的讨论。
然而，创伤却不仅仅是简单的压力。
它是一个高度紧张的生活事件，或者是积累起来的压力量，超出了一个人自我调节和应对的能力。
因此，这个事件扰乱了他们的平衡，或者我们称之为“体内平衡”。
创伤事件包括单一事件，如严重的事故、袭击或灾难，也包括长期的情况，如家庭暴力、困境或儿童虐待。
压力易感性模型是理解与精神健康问题的发生和压力系统失调相关的痛苦的核心。
它表明每个人都有一定程度的风险，而压力则增加了这种风险。
压力足够多时，症状和疾病就会出现。
自我调节涉及到每个存在层面。
所以当创伤打破它时，它可能发生在我们生活的任何部分或所有部分。
觉察到创伤是对健康的挑战。
这是要意识到，我可能注意到它对我的身体、心灵、关系、文化生活或精神生活的影响。
那些认识我或与我共事的人也可能感受到这些影响，这些影响发生在我们接触和联系的领域。
对创伤或其影响的认识是当今健康领域中的一个关键问题。
创伤可以打破我们与他人的连接，打破我们讲述自己故事的方式，并破坏我们对世界的信任。
当创伤发生在儿童和青少年时期，在家庭或社区中那些本应保护我们安全、帮助我们成长的关爱关系中时，它会影响我们在成年后如何发展和调节自己。
它也可能成为精神和身体健康的风险因素。
美国的大规模ACE研究调查了这些不良儿童经历，并展示了儿童创伤对心理和身体健康的连锁反应。
因此，创伤后应激障碍（PTSD），它可能在经历或目睹一次威胁生命的事件后发生，是一种重要的障碍。
创伤后应激障碍的特点包括噩梦、闪回、焦虑，以及避免与创伤相关的事物。
患有PTSD的人通常会有失眠和/或抑郁，或者使用物质来尝试应对症状。
然而，我们现在明白，最严重的自我调节失调发生在那些小时候缺乏持续照料者或缺乏足够安全感和舒适感的人身上。
这种创伤的积累效应被称为“复杂创伤”，它是许多心理健康障碍的重要贡献因素。
我们需要积极的连接。
例如，即使是儿童时期的每日贬低或忽视，也会导致一种持续的自我价值感缺失，进而影响我的依附状态和自我认知。
创伤会引发震惊、麻木感，甚至可能导致个体经历解离或与周围人的断裂。
解离是指心理和身体生活的各个部分失去联系或组织，它们通常是相互联系并健康组织的。
有些人这些解离、断裂或失调的现象非常严重。
例如，患有解离性身份障碍的人可能会与自己的某些部分断裂，甚至在某些时刻以另一种自我状态表现出来。
这种记不清自己在不同时间的身份的问题，对他们和他们周围的人来说都可能非常困惑。
强烈的混乱、迷失方向、愤怒、厌恶、无助、绝望的情绪也可能出现。
创伤相关的强烈情绪和联想可能部分解释了为什么创伤常常很难被检查或识别，并且可能会隐藏在视野之外、记忆之外。
当创伤发生在隐秘中，如虐待常常发生时，那么识别和看到创伤的难度就更大了。
现在，我们正在努力发展创伤知情护理，关爱他人和我们自己的方式，理解创伤如何打破意识和自我，然后探索恢复完整并蓬勃发展的路径。
现在，我们经常谈论基于信仰的治疗方法。
从根本上讲，我们首先必须为那些经历创伤的人以及他们周围的家庭和照料系统建立安全感。
你可以想象，如果我在一个不安全的家庭或社区中成长，那么安全感的建立可能需要一段时间。
这一步骤需要照料者和临床医生的倾听、确认和调适。
我们需要花时间去注意如果某人感到恐惧，并以帮助他们感到更安全的方式与他们接触。
在安全感之后是稳定化，我们尝试帮助个体找到能够让他们感到支持的方式，这些方式有助于他们安全地管理，从而减少创伤的持续破坏效应。
这帮助他们远离像药物和酒精或自残等不安全的应对方式。
这里，MOOC中讨论的一些技能和策略可能在促进平静与希望方面起到至关重要的作用，帮助我们安抚身体和心灵，这些可能感到恐惧、焦虑、愤怒或麻木。
这里，放松、呼吸、运动、在关爱的关系中得到肯定、正念和冥想是帮助的方式。
每个人都需要适合自己的策略。
并且练习这些策略可能也需要一些时间。
然后，只有当我们感到准备好和得到支持时，我们才能通过多种方式思考、感受和处理发生在我们身上的事情。
因为创伤影响了存在的各个方面，任何一个方面都可以成为恢复的初步窗口。
创伤聚焦的认知行为疗法和眼动脱敏是用于治疗PTSD的心理治疗方法。
身体疗法、创意疗法、其他心理治疗方法和神经反馈也可以发挥作用。
对一些人来说，精神框架很重要。
类似冥想的事情可以在多个层面上起作用，带来心灵与身体之间的重新连接和新的连接。
因此，综合方法帮助我们应对创伤带来的心灵、身体和灵魂的解离，帮助我们重新恢复完整。
经历过创伤的人需要支持来恢复。
但有时他们需要时间和证据来相信他们能够重新信任他人。
信任我们提供的关爱，甚至重新信任自己。
然而，我们可以解决创伤，恢复并从中成长，最终蓬勃发展。
看起来，最好的方法是和他人一起在安全的环境中完成这一切。
我们不需要孤军奋战。
** sentence
initially [ɪˈnɪʃ(ə)li]: adv. at the beginning最初, 开头
- Initially, I tried to establish a causal relationship between my trauma in childhood and my disorder.
- Initially, in addition to Lily our son socialize with no one in his class.
- Initially, sugar is often combined with milk in our family.
connectedness [kə'nektɪdnəs]: n. the feeling people have that they are members of a group in society and that they share particular qualities with other members of that group归属感
- In my childhood, I went out of my ways to seek connectedness in my family.
- The clinician took steps to get him a sense of connectedness at his home.
- A high sense of connectedness induced changes in the mind of the spy who was meant to betray us.
thrive [θraɪv]: v. to become very successful or very strong and healthy兴旺
- The outcome of our saving this year domenstrated a correlation between our faith and thriving.
- At the end of the day, the company didn't thrive any more and went bankrupt because of sex scandal.
- My brother's thriving alerted me to my own career which deserve my hard work.
repay [rɪˈpeɪ]: v. to pay back money that you have borrowed偿还, 报答, 报复
- Her care alerts me to repaying her kindness in a better way.
- He tends to think of the bill he paid as repaying my help last time.
- No one should perceive the little thing as repaying his great help.
nurture [ˈnɜrtʃər]: v. to help a plan, idea, feeling etc to develop培育
- The AI model ran complex series of calculations to come up with a plan of nurturing our project.
- You will never succeed in nurturing a good boy within a matter of weeks.
- Just because nurturing a college student under certain circumstance is difficult doesn't mean that's impossible.
heal [hil]: v. to make someone who is ill become healthy again, especially by using natural powers or prayer ⇨ cure治愈, 医治
- Healing the world sounds like a dream rather than a reality.
- All 3 of clinician are willing to heal the patients in the earthquake.
- The clinician played a crucial role in healing the patient with headaches.
exceed [ɪkˈsid]: v. to be more than a particular number or amount超越, 胜过
- The speed of the car taking head exceeds the fastest car in last competition.
- My score exceeding others in my class is always in demand.
- The worker picked on the fact that the weight of the box exceeded others a great deal.
equilibrium [ˌekwɪˈlɪbriəm]: n. a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly平衡,均衡
- In order not to upset economic equilibrium, the authorities invested a lot in building public facilities, bridges, roads, railways and so on.
- In one study, we found the equlibrium of a patient break down when he reminded of some traumatic events.
- My wife's emotional equilibrium is vulnerable in her ovulation cycle.
assault [əˈsɔlt]: v. the crime of physically attacking someone侵犯
- These youths were randomly assigned to assault family members of the dealer.
- The experience of cooking gave him the nudge to assault his wife who he used to respect.
- The detective is attuned to the dealer who used to assault students in the forest.
entrapment [ɪnˈtræpmənt]: n. the practice of trapping someone by tricking them, especially to show that they are guilty of a crime诱捕的行动,圈套
- Differing from my father, my grandfather was always being ripped off in entrapment.
- The entrapment resulted in his numbness and he took no interest in school activities. 
- It seemed that my friend I trusted was correlated with the entrapment in which I lost my savings.
diathesis [daɪ'æθɪsɪs]: n. (易患某病)素质
- Because of his diathesis, he developed fever for two weeks rather than two days in normal condition.
- Because of his diathesis, his clinician doesn't prescribe him any sedative medication.
- Because of his diathesis, he has to have an operation as soon as possible.
adverse [ædˈvɜrs]: adj. not good or favourable不利的
- What happened to him may be adverse throughout most of his life. 
- Rating your son's personalitiy in public has an adverse effect on his social relationships.
- Obviously, losing your attraction to your wife is adverse to your marriage.
flashback [ˈflæʃˌbæk]: n. a sudden very clear memory of something that happened to you in the past闪回
- Every time I enter the house, I am flooded with traumatic flashbacks.
- Initiately, these flashbacks don't activate my fight system.
- You need to get rid of those flashbacks which activate your fight system.
nightmare [ˈnaɪtˌmer]: n. a very frightening dream恶梦
- I had a nightmare, not because you did me a flavor, but because of my traumatic flashbacks.
- He tried to stay awake to block out the nightmare.
- The nightmare enhanced my memory of something disgusting.
consistent [kənˈsɪstənt]: adj. always behaving in the same way or having the same attitudes, standards etc – usually used to show approval OPP inconsistent一致的
- Because of the lack of consistent caregiver, he was diagnosed with post-traumatic stress disorder.
- This might explain why the school doesn't have a consistent headmaster. 
- The warlike knight who didn't swear to a consistent lord was sentenced to death.
numb [nʌm] numbness: adj.n. a part of your body that is numb is unable to feel anything, for example because you are very cold麻木的
- He was so numb when he heard someone playing matchmaker for him that I concerned about his mental health.
- Due to his numbness in the interview, he lost the opportunity to work for Apple.
- Due to his numbness in his family, his sons had no intention of offering money when he was in hospital.
dissociative [dɪ'soʊʃɪˌeɪtɪv]: adj. 分离的,游离的
- I always feel dissociative when I take part in a group activities.
- Feeling dissociative, he played truant from school again.
- When I feel dissociative, I always make a call to my best friend.
compound [ˈkɑmˌpaʊnd]: v. to make a difficult situation worse by adding more problems恶化,加重
- The patient who had an operation yesterday is developing fever now, which compounds his conditions.
- The job loss of his father compounded the broke family additionally.
- No one could account for the fact that the little cold compounded the conditions of the patient.
clinician [klɪˈnɪʃ(ə)n]: n. a doctor who treats and examines people, rather than one who does ↑research临床医生
- My wife has a close friend who was proposed by a clinician in her local hospital.
- The clinician was kept in prison because he revealed some products in the market that are adverse to our health.
- The clinician was diagnosed with post-traumatic stress disorder because of the entrapment.
--------------------
break down sth.: 破坏某事物
- The domestic violence breaks down his trust in relationships.
- The movement of the machine broke down the electrical nets underground.
- The peasants claimed that the electrical nets broke down their fortune.
For a time, + ...: 一度
- For a time, I had several close friends who enjoy me telling stories.
- For a time, my grandfather was obsessed with his exalted position in the family.
- For a time, my son-in-law went bankrupt because of the earthquake.
integrate A into B: 整合A进B
- The eminent writer is likely integrating the history in the village into his novel.
- Because of the copyright, I could integrate his story into my novel directly.
- Well, I succeeded in integrating the framework into our project.
make meaning of sth.: 使某事物有意义
- The story is dedicated to everyone who is trying to make meaning of every second in his or her life.
- His lifetime dedication makes meaning of every word in the speech.
- Her children's thriving makes meaning of her hard work.
be meant to do sth.: 注定做某事
- I am meant to achieve the exalted claim of papal authorities.
- She is meant to inherit the throne no matter what.
- No matter what he is meant to free the Holy Land from Muslims.
the knock on effects: 连锁反应
- I am shocked by the knock on effects on the little mistake I made carelessly.
- We must be focusing on the prevention, for we can't afford the knock on effects.
- The knock on effects on the revalution led to the emergence of the new mind.
in secrecy: in secret秘密地
- His wife has affairs with a clinician in secrecy, which compounds his mental condition.
- He was disappointed by his son, who engaged in drugs dealing in secrecy.
- What your husband have done in secrecy may bring about a disater to your family.
tune in of sb.: 聆听某人
- Tuning in of his father, he restored to the homeostasis.
- Tuning in of his father, he had the nudge to ask for the girl's phone number.
- Tuning in of his mother, he decided to have an operation in time.
have a place (in ...): 有一席之地
- My wife should have a place, who was being busy in the kitchen.
- My cat always has a place in barbecue.
- The entrepneur always has a place in our representative meeting.
** sentence2
initially [ɪˈnɪʃ(ə)li]: adv. at the beginning最初, 开头
- Initially, I tried to establish a causal relationship between my trauma in childhood and my disorder.
- Initially, in addition to Lily our son socialized with no one in his class.
- Initially, sugar is often combined with milk in our family.
connectedness [kə'nektɪdnəs]: n. the feeling people have that they are members of a group in society and that they share particular qualities with other members of that group归属感
- In my childhood, I went out of my way to seek connectedness in my family.
- The clinician took steps to get him a sense of connectedness at his home.
- A high sense of connectedness induced changes in the mind of the spy who was meant to betray us.
thrive [θraɪv]: v. to become very successful or very strong and healthy兴旺
- The outcome of our saving this year demonstrated a correlation between our faith and thriving.
- At the end of the day, the company didn't thrive anymore and went bankrupt because of a sex scandal.
- My brother's thriving alerted me to my career which deserves my hard work.
repay [rɪˈpeɪ]: v. to pay back money that you have borrowed偿还, 报答, 报复
- Her care alerts me to repay her kindness in a better way.
- He tends to think of the bill he paid as repaying my help last time.
- No one should perceive the little thing as repaying his great help.
nurture [ˈnɜrtʃər]: v. to help a plan, idea, feeling etc to develop培育
- The AI model ran a complex series of calculations to come up with a plan for nurturing our project.
- You will never succeed in nurturing a good boy within a matter of weeks.
- Just because nurturing a college student under certain circumstances is difficult doesn't mean it's impossible.
heal [hil]: v. to make someone who is ill become healthy again, especially by using natural powers or prayer ⇨ cure治愈, 医治
- Healing the world sounds like a dream rather than a reality.
- All three clinicians are willing to heal the patients in the earthquake.
- The clinician played a crucial role in healing the patient with headaches.
exceed [ɪkˈsid]: v. to be more than a particular number or amount超越, 胜过
- The speed of the car taking its head exceeds the fastest car in the last competition.
- My score exceeding others in my class is always in demand.
- The worker picked on the fact that the weight of the box exceeded others a great deal.
equilibrium [ˌekwɪˈlɪbriəm]: n. a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly平衡,均衡
- In order not to upset the economic equilibrium, the authorities invested a lot in building public facilities, bridges, roads, railways, and so on.
- In one study, we found the equilibrium of the patient broke down when he was reminded of some traumatic events.
- My wife's emotional equilibrium is vulnerable in her ovulation cycle.
assault [əˈsɔlt]: v. the crime of physically attacking someone侵犯
- These youths were randomly assigned to assault family members of the dealer.
- The experience of cooking gave him the nudge to assault his wife who he used to respect.
- The detective is attuned to the dealer who used to assault students in the forest.
entrapment [ɪnˈtræpmənt]: n. the practice of trapping someone by tricking them, especially to show that they are guilty of a crime诱捕的行动,圈套
- Differing from my father, my grandfather was always being ripped off in entrapment.
- The entrapment resulted in his numbness and he took no interest in school activities. 
- It seemed that my friend I trusted was correlated with the entrapment in which I lost my savings.
diathesis [daɪ'æθɪsɪs]: n. (易患某病)素质
- Because of his diathesis, he developed a fever for two weeks rather than two days in normal condition.
- Because of his diathesis, his clinician doesn't prescribe him any sedative medication.
- Because of his diathesis, he has to have an operation as soon as possible.
adverse [ædˈvɜrs]: adj. not good or favourable不利的
- What happened to him may be adverse throughout most of his life. 
- Rating your son's personality in public has an adverse effect on his social relationships.
- Obviously, losing your attraction to your wife is adverse to your marriage.
flashback [ˈflæʃˌbæk]: n. a sudden very clear memory of something that happened to you in the past闪回
- Every time I enter the house, I am flooded with traumatic flashbacks.
- Initiately, these flashbacks don't activate my fight system.
- You need to get rid of those flashbacks that activate your fight system.
nightmare [ˈnaɪtˌmer]: n. a very frightening dream恶梦
- I had a nightmare, not because you did me a favor, but because of my traumatic flashbacks.
- He tried to stay awake to block out the nightmare.
- The nightmare enhanced my memory of something disgusting.
consistent [kənˈsɪstənt]: adj. always behaving in the same way or having the same attitudes, standards etc – usually used to show approval OPP inconsistent一致的
- Because of the lack of a consistent caregiver, he was diagnosed with post-traumatic stress disorder.
- This might explain why the school doesn't have a consistent headmaster. 
- The warlike knight who didn't swear to a consistent lord was sentenced to death.
numb [nʌm] numbness: adj.n. a part of your body that is numb is unable to feel anything, for example because you are very cold麻木的
- He was so numb when he heard someone playing matchmaker for him that I was concerned about his mental health.
- Due to his numbness in the interview, he lost the opportunity to work for Apple.
- Due to his numbness in his family, his sons had no intention of offering money when he was in hospital.
dissociative [dɪ'soʊʃɪˌeɪtɪv]: adj. 分离的,游离的
- I always feel dissociative when I take part in a group activity.
- Feeling dissociative, he played truant from school again.
- When I feel dissociative, I always make a call to my best friend.
compound [ˈkɑmˌpaʊnd]: v. to make a difficult situation worse by adding more problems恶化,加重
- The patient who had an operation yesterday is developing a fever now, which compounds his condition.
- The job loss of his father compounded the broke family additionally.
- No one could account for the fact that the little cold compounded the conditions of the patient.
clinician [klɪˈnɪʃ(ə)n]: n. a doctor who treats and examines people, rather than one who does ↑research临床医生
- My wife has a close friend who was proposed by a clinician in her local hospital.
- The clinician was kept in prison because he revealed some products in the market that are adverse to our health.
- The clinician was diagnosed with post-traumatic stress disorder because of the entrapment.
--------------------
break down sth.: 破坏某事物
- Domestic violence breaks down his trust in relationships.
- The movement of the machine broke down the electrical nets underground.
- The peasants claimed that the electrical nets broke down their fortune.
For a time, + ...: 一度
- For a time, I had several close friends who enjoyed me telling stories.
- For a time, my grandfather was obsessed with his exalted position in the family.
- For a time, my son-in-law went bankrupt because of the earthquake.
integrate A into B: 整合A进B
- The eminent writer is likely integrating the history of the village into his novel.
- Because of the copyright, I could integrate his story into my novel directly.
- Well, I succeeded in integrating the framework into our project.
make meaning of sth.: 使某事物有意义
- The story is dedicated to everyone who is trying to make meaning of every second of his or her life.
- His lifetime dedication makes meaning of every word in the speech.
- Her children's thriving makes meaning of her hard work.
be meant to do sth.: 注定做某事
- I am meant to achieve the exalted claim of papal authorities.
- She is meant to inherit the throne no matter what.
- No matter what he is meant to free the Holy Land from Muslims.
the knock-on effects: 连锁反应
- I am shocked by the knock-on effects of the little mistake I made carelessly.
- We must be focusing on prevention, for we can't afford the knock-on effects.
- The knock-on effects of the revolution led to the emergence of the new mind.
in secrecy: in secret秘密地
- His wife has affairs with a clinician in secrecy, which compounds his mental condition.
- He was disappointed by his son, who engaged in drug dealing in secrecy.
- What your husband has done in secrecy may bring about a disaster to your family.
tune in of sb.: 聆听某人
- Tuning in of his father, he restored to homeostasis.
- Tuning in of his father, he had the nudge to ask for the girl's phone number.
- Tuning in of his mother, he decided to have an operation in time.
have a place (in ...): 有一席之地
- My wife should have a place, she was busy in the kitchen.
- My cat always has a place in a barbecue.
- The entrepreneur always has a place in our representative meeting.
