#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2-1 4 Parts of the brain
#+begin_verse
So, let's talk about the different parts of the brain and what they do.
Parts of the brain are functionalized for different purposes, they do different things.
Which is why damage to different parts of the brain has different effects.
It's why when you look at an fMRI scan or PET scan or some something that records neural activity,
	you could figure out based on the location of the activity what's going on.
So, the first thing to realize is I'm talking about the brain,
	but I'd be more precise and more inclusive
		if I talked about the brain and parts of the spinal cord.
So, you don't need your brain for everything.
There're certain activities we do that can happen without a brain.
Like sucking in newborns or pulling your limb back to withdraw from pain or vomiting.
But for everything else we talk about in this course, we'll really be talking about the brain.

So, some of the structures of the brain that are highly relevant are called subcortical,
	which means they're below the cortex, which means they're in the center of the brain.
This includes part of the brain like the medulla,
	which control certain automatic function
		like your heart rate, your blood pressure, swallowing, and so on.
It includes the cerebellum, which is involved in body balance and muscle coordination.
It contains about 30 billion neurons.
So, this isn't small potatoes.
The hypothalamus, which is involved in feeding and sex and thirst and different appetites.
We're going to talk about emotions or visceral desires, we'll return to those parts of the brain.

But for the aspects of psychology that are distinctive for us, that make us human,
	we're mostly focused on the outer layer, the cerebral cortex.
So, the cerebral cortex it is all crumpled up.
If you were to take a brain, pull out the cortex and straighten it out,
		like you're removing a rug you got from the trunk of your car and you have to straighten it out,
	it's about two feet square.
So, it's lot of crumpling to get it in.
It's about three millimeters thick.
This is where the action is.
This is where at least for the things I'm interested in, this is where it takes place.
Is where reasoning and language and complex perception comes from.
Fish don't have any cerebral cortex, reptiles and birds have a little bit,
	but primates, including humans, have a lot.
	
When you look at the cortex, you'll see it has two halves.
It has a left half and a right half.
For each of these halves, when you look at it,
	you can demarcate the brain, the cortex into different lobes.
There's going from your forehead and swooping to the back.
You have the frontal lobe conveniently enough on the front.
The parietal lobe, the occipital lobe, and the temporal lobe.
Each of these lobes, there's different things, which we'll talk about in a bit.

Another thing about the cortex though which is super interesting, is that it includes maps.
What I mean by this is it includes topographical maps
	where two things that are close together in the brain are similarly close together in the body.
So, there is a motor area
	where if you were to shock, parts of that brain, parts of the body would twitch accordingly.
Just like you'd expect, the middle finger is close to the thumb which is closer to elbow.
If it's close in the real-world and your body it's close to the brain
	and there is a primary somatosensory area, which is the sense organs.
There if you have somebody in the operating table and you shocked people,
	they would experience things, they might experience a sound or a flash of light or a touch.
In fact, in the occipital lobe, you have a map for vision
	and in the temporal lobe, you have a map for sound.
What's really cool is, I said the map is topographical,
	but the size of the brain areas don't correspond to the size of the actual body areas,
		but rather to the extent to which there's motor or sensory function.
So, artists have drawn pictures of people
	if their body was proportioned to the extent that their brain was.
You'd see the trunk of the body is relatively small,
	but their hands are enormous and the face is enormous because there's a whole lot of sensation.
There is much more sensation going on in your hand than in your whole back
	even though the back is physically larger.
So, part of the cortex is these projection areas.
But less than a quarter of the cortex contains projection areas.
As I said, the rest is involved with the cool stuff.
With language, with reasoning, with moral thoughts, and so on.

Then the question comes in, how do we know this?
How do we know what parts of the brain do what, what parts of the brain are involved, and why?
There's different answers.
So, one answer is we can scan the brain.
We can use MRI, which is a high-frequency magnetic field, to look at the activity of the brain,
	what parts are active when people do different things.
We can also look at so-called natural experiments
	when people have tumors or strokes or motorcycle accidents.
In damaged part of your brain and we can ask the question,
	what damage to which parts of the brain correspond to damage to which functions?
Through these different methods,
	we've learned about the different parts of the brain and what they do.
We could talk about some certain specific things that can go wrong
	due to brain damage or stroke or trauma.
	
So, for instance, there's Apraxia.
Apraxia is problems of actions.
So, you're unable to do an action
	like waving goodbye or picking up before or can bring some food to your mouth.
You're not paralyze.
You can make the movements if you have to,
	but you can't coordinate these basic movements into complex actions.
	
There's Agnosia.
Agnosia is a disorders of perception.
And they're not like you can't see, but you can't recognize.
Some is called psychic blindness.
People of various forms of Agnosia can describe a picture in terms of it's part,
	but can't recognize the objects that are being depicted.
That's a form of visual Agnosia.
There's also a specific Prosopagnosia, where you can't recognize faces.
Oliver Sacks wrote a wonderful book many years ago called The Man Who Mistook His Wife For a Hat.
This was a series of profiles of people who had surprising neurological disorders
	and the title case of the book was a man who actually had such an inability to recognize faces,
		he couldn't distinguishes his wife's face from that of a hat.
Milder forms of Prosopagnosia, which some people suffer from
	and to be honest, I got a little bit of some terrible faces.
Is that you could recognize faces as faces,
	but you can't recognize whose face they are and it's very hard for you to recognize people.
	
There's problems of sensory neglect.
You get disorders that block out one part of the world.
You might have damage to parts of your brain that would block out the left side of the world.
It's not just the sort of physical thing,
	when you ask somebody with such a disorder to draw clock for instance,
		they'll put all the numbers from one to 12 on the right side of the clock.
It's as if they don't think of the left side of the world again.
So, maybe it's not even a sensory problem, but an attentional problem.

There's Aphasia, which refers to disorders of language.
Some forms of aphasia are expressive like a Broca's Aphasia, where you can't really speak.
A famous case of somebody who can only use the word tan,
	would say tan, tan, tan, but couldn't say anything else.
Or then there's something that's called Receptive Aphasia,
		where you can speak although what you say doesn't make much sense,
	but also you have a terrible time understanding other people.
	
Then there's all sorts of other disorders.
There's the disorder which we talked about with regard to Phineas Gage and various forms of it.
There's damage to your brain, it's debatable whether this is true Phineas Gage,
	but there are other cases where it's much more clear.
Cause you to lose your moral sense, your sense of right and wrong,
		your ability to control yourself,
	to restrain yourself perhaps your conscience.

Now, we're going to talk about all of these things through the course but the moral here is that,
	A, there's some localization of function.
There's some sense in which it correspond to different brain areas.
B, again, this is an argument against dualism.
We can see that in that anyone who argued that the mind isn't the brain
	would be hard-pressed to explain why damage to the brain
			seems to affect some very intimate and very important aspects of ourselves.
#+end_verse
** expression
inclusive [ɪnˈklusɪv]: adj. an inclusive price or cost includes everything OPP exclusive包含的, 包括的
suck [sʌk]: v. to take air, liquid etc into your mouth by making your lips form a small hole and using the muscles of your mouth to pull it in吮吸
newborn [ˈnuˌbɔrn]: n. newborn child/baby/son etc a child that has just been born婴儿
vomit [ˈvɒmit]: v. to bring food or drink up from your stomach out through your mouth, because you are ill呕吐
cerebral [səˈribrəl]: adj. medical relating to or affecting your brain大脑的
cortex [ˈkɔrˌteks]: n. the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
cerebellum [ˌserəˈbeləm]: n. technical the bottom part of your brain that controls your muscles小脑
visceral [ˈvɪsərəl]: adj. literary visceral beliefs and attitudes are the result of strong feelings rather than careful thought肺腑的
distinctive [dɪˈstɪŋktɪv]: adj. having a special quality, character, or appearance that is different and easy to recognize独特的
rug [rʌɡ]: n. a piece of thick cloth or wool that covers part of a floor, used for warmth or as a decoration ⇨ mat, carpet(小)地毯, 垫子
reason [ˈriz(ə)n]: v. to form a particular judgment about a situation after carefully considering the facts推理
reptile [ˈreptɪl]: n. a type of animal, such as a snake or ↑lizard, whose body temperature changes according to the temperature around it, and that usually lays eggs to have babies爬行动物
primate [ˈpraɪmeɪt]: n. a member of the group of animals that includes humans and monkeys灵长类的动物
lobe [loʊb]: n. technical a round part of an organ in your body, especially in your brain or lungs(脑)叶
swoop [swup]: v. if a bird or aircraft swoops, it moves suddenly down through the air, especially in order to attack something俯冲
frontal [ˈfrʌnt(ə)l]: adj. medical relating to the front part of the head额骨的
parietal [pə'raɪətəl]: adj. 顶骨的
occipital [ɒk'sɪpətəl]: adj. 枕骨的
temporal [ˈtemp(ə)rəl]: adj. 太阳穴的
topography [təˈpɑɡrəfi] topographical: n.adj. the science of describing an area of land, or making maps of it地形学
motor [ˈmoʊtər]: adj. technical relating to nerves that make muscles move肌肉运动的
twitch [twɪtʃ]: v. if a part of someone’s body twitches, or if they twitch it, it makes a small sudden movement抽搐
somatosensory [ˌsoʊmətə'sensərɪ]: adj. (耳、目、口等以外的)体觉的
projection [prəˈdʒekʃ(ə)n]: n. the act of projecting a film or picture onto a screen投影
magnetic [mæɡˈnetɪk]: adj. concerning or produced by ↑magnetism磁的
tumor [ˈtumər]: n. a mass of diseased cells in your body that have divided and increased too quickly肿瘤
stroke [stroʊk]: n. if someone has a stroke, an ↑artery (=tube carrying blood) in their brain suddenly bursts or becomes blocked, so that they may die or be unable to use some muscles中风
motorcycle [ˈmoʊtərˌsaɪk(ə)l]: n. a fast two-wheeled vehicle with an engine SYN motorbike摩托车
psychic [ˈsaɪkɪk]: adj. affecting the mind rather than the body精神的
blind [blaɪnd] blindness: adj.n. unable to see瞎的, 盲目的
profile [ˈproʊˌfaɪl]: n. a side view of someone’s head侧面像
mild [maɪld]: adj. a mild illness or health problem is not serious温和的
sensory [ˈsensəri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
moral [ˈmɔrəl]: n. a practical lesson about what to do or how to behave, which you learn from a story or from something that happens to you ⇨ message教益
hard-pressed: adj. having a lot of problems and not enough money or time处于困境的
--------------------
spinal cord [ˈspaɪn(ə)l] [kɔrd]: 脊髓
this isn't small potatoes: 这可不是小事
crumple sth. up [ˈkrʌmp(ə)l]: 弄皱某物
straighten sth. out [ˈstreɪt(ə)n]: 变直弄直某物
demarcate A into B(s) [ˈdimɑrˌkeɪt]: 界定A为B(复数)
correspond to sth.: 对应于某事物
be proportioned to the extent: 与程度成比例
mistake A for B: 把A误认为B
** ch.
2-1 4 大脑的部分
那么，让我们来谈谈大脑的不同部分以及它们的功能。
大脑的不同部分被功能化用于不同的目的，它们执行不同的任务。
这就是为什么大脑的不同部分受到损伤会产生不同的影响。
这也是当你观察fMRI扫描、PET扫描或记录神经活动的工具时，你可以通过活动的位置推测出发生了什么。
首先要明白，我在谈论大脑，但如果我更加精确和包容，我应该说是大脑和脊髓的部分。
并不是所有的活动都需要大脑。
有些活动可以在没有大脑参与的情况下发生，比如新生儿的吸吮反射、手臂因疼痛而缩回或呕吐。
但在这门课程中讨论的其他所有内容，都会涉及大脑。
大脑中一些非常重要的结构被称为皮质下结构，意思是它们位于大脑皮层下方，也就是大脑中心区域。
这包括延髓，它控制一些自动功能，比如心率、血压、吞咽等。
还包括小脑，它参与身体平衡和肌肉协调。
小脑包含大约300亿个神经元，这并不是小数目。
还有下丘脑，它参与进食、性欲、口渴和其他各种欲望。
当我们讨论情绪或本能欲望时，我们会再次回到这些脑区。
然而，对人类心理学最独特的方面，我们主要关注的是大脑的外层——大脑皮层。
大脑皮层是皱折非常多的。
如果你把大脑取出并将皮层展开，就像从车后备箱里取出一块地毯并铺开，它大约有两平方英尺（约0.2平方米）。
为了塞进大脑中，需要大量的皱折。
大脑皮层大约有3毫米厚。
这里才是真正的“舞台”，至少对于我感兴趣的东西，这里是发生一切的地方。
推理、语言和复杂感知都来自这里。
鱼类没有大脑皮层，爬行动物和鸟类有一点点，灵长类动物（包括人类）有大量的大脑皮层。
当你观察大脑皮层时，你会发现它有两半——左半球和右半球。
对于每一半大脑皮层，你可以将其划分为不同的脑叶。
从前额向后延伸，依次是额叶、顶叶、枕叶和颞叶。
这些脑叶各自负责不同的功能，我们稍后会详细讨论。
大脑皮层中另一个非常有趣的特点是它包含地图。
这意味着大脑中靠近的两个区域通常对应身体中彼此靠近的部位。
在运动区中，如果刺激某个区域，相应的身体部位就会抽搐。
例如，中指在拇指旁边，而拇指又靠近手肘。
在现实世界中距离近的身体部位，在大脑中的表示也是相邻的。
还有初级躯体感觉区，它与感官器官有关。
如果你在手术中刺激这些区域，病人可能会体验到声音、闪光或触觉。
事实上，枕叶中存在一个视觉地图，颞叶中存在一个听觉地图。
更酷的是，这些地图是拓扑地图，但大脑区域的大小并不对应实际身体部位的大小，而是对应运动或感觉功能的程度。
艺术家曾绘制过如果人体按大脑区域大小比例来画的图片，身体躯干相对较小，但手和脸巨大，因为这些部位有更多的感觉输入。
大脑皮层的一部分是投射区，但投射区占不到皮层的四分之一。
其余部分涉及更复杂的功能，比如语言、推理和道德思考。
那么，我们如何知道这些信息呢？
有几种答案。
一种是通过脑部扫描。
我们可以使用MRI（磁共振成像），通过高频磁场来观察大脑活动，了解人在执行不同任务时哪些部位活跃。
另一种方法是通过所谓的自然实验，比如肿瘤、中风或摩托车事故造成的大脑损伤。
通过观察大脑的损伤区域及其对应的功能缺失，我们可以推断出不同脑区的作用。
通过这些方法，我们了解了大脑的不同部分及其功能。
现在，我们来谈谈大脑损伤或中风可能导致的一些特定障碍。
例如，**失用症（Apraxia）**是动作障碍。
患者无法执行某些动作，比如挥手再见或用叉子吃饭。
他们并不是瘫痪，而是无法协调这些基本动作形成复杂行为。
**失认症（Agnosia）**是感知障碍。
患者并非看不见，而是无法识别物体。
有一种被称为心因性盲视的类型，患者可以描述图像的部分，但无法识别图像所代表的物体。
特定类型的失认症叫做面孔失认症（Prosopagnosia），即患者无法识别面孔。
奥利弗·萨克斯曾写过一本著名的书《误把妻子当帽子的人》，其中描述了一位患者因无法识别面孔，竟将妻子的脸与帽子混淆。
轻度的面孔失认症让人能够识别面孔，但无法认出是谁，识别人变得非常困难。
还有感觉忽视症（Sensory Neglect），患者会忽视世界的一侧。
例如，如果右脑损伤，患者可能会忽视左侧世界。
当你让这些患者画一个钟表时，他们会把1到12的数字全部画在钟表的右半边，仿佛左侧世界不存在一样。
这可能不仅仅是感觉问题，更像是注意力问题。
**失语症（Aphasia）**指的是语言障碍。
**布洛卡失语症（Broca's Aphasia）**是一种表达性失语症，患者无法说话。
有一位著名患者只能说“tan, tan, tan”，再也说不出其他词语。
还有维尔尼克失语症（Wernicke's Aphasia），患者可以说话，但话语毫无意义，同时很难理解别人说的话。
还有很多其他障碍。
例如，关于**菲尼亚斯·盖奇（Phineas Gage）**的病例，涉及道德感的丧失、自我控制力的丧失，甚至良心的丧失。
通过这些病例，我们得到两个结论：
A，功能定位，即不同的大脑区域对应不同的功能。
B，这也是反对二元论（Dualism）的论据。
如果有人认为心灵与大脑无关，那么解释为什么大脑损伤会影响我们最亲密和重要的自我特征就会变得非常困难。	
** sentence
inclusive [ɪnˈklusɪv]: adj. an inclusive price or cost includes everything OPP exclusive包含的, 包括的
- These mutilated people shouldn't be vanishing from the inclusive community.
- This holiday season we are going to visit an inclusive monastery lying on the pass.
- You are able to consign the sweater to the inclusive closet.
suck [sʌk]: v. to take air, liquid etc into your mouth by making your lips form a small hole and using the muscles of your mouth to pull it in吮吸
- With the speech involved in his mistakes, the president began to suck his little finger.
- Imagine a day when you can suck delicious ice cream at a seaside resort for free.
- Without explicit conditions you are not allowed to suck ice cream.
newborn [ˈnuˌbɔrn]: n. newborn child/baby/son etc a child that has just been born婴儿
- The official was determined to foster a system of taking care for newborns in the town.
- The cohort with fevers is formed by 7 newborns and 3 adolescents.
- Newborns have never been treat so terrible like in the camp throughout human history.
vomit [ˈvɒmit]: v. to bring food or drink up from your stomach out through your mouth, because you are ill呕吐
- Obviously, the adolescant is describing his little sister developing vomiting.
- Because of my wife's pregancy and she will vomit in the bus, we failed to make a journey last weekend.
- At a seaside resort, she received a warm treatment after her vomiting.
cerebral [səˈribrəl]: adj. medical relating to or affecting your brain大脑的
cortex [ˈkɔrˌteks]: n. the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
cerebellum [ˌserəˈbeləm]: n. technical the bottom part of your brain that controls your muscles小脑
visceral [ˈvɪsərəl]: adj. literary visceral beliefs and attitudes are the result of strong feelings rather than careful thought肺腑的
- Everyone at the party expressed their visceral opinions about the community through this process.
- The citizen carried an obligation to articulate his visceral words in the court.
- From his visceral speaking in public, I knew he was unwilling to give away his property.
distinctive [dɪˈstɪŋktɪv]: adj. having a special quality, character, or appearance that is different and easy to recognize独特的
- The distinctive circumstance have obligated him to develop a system of protecting himself.
- His distinctive response to our presents is to return the flavor after a week.
- His method of researching is so distinctive that no one could account for his statistics.
rug [rʌɡ]: n. a piece of thick cloth or wool that covers part of a floor, used for warmth or as a decoration ⇨ mat, carpet(小)地毯, 垫子
- Getting a rug from the community for free, the old lady statisfied herself at the expense of her son.
- My wife gained a adorable piece of rug from the flight attendant.
- The patterns of rugs take many forms.
reason [ˈriz(ə)n]: v. to form a particular judgment about a situation after carefully considering the facts推理
- Proving inguilty, the innocent person must be indebted to his reasoning.
- His speaking in the meeting is read as his reasoning about the scandal.
- The enminent lawyer admired for his son's reasoning about the case.
reptile [ˈreptɪl]: n. a type of animal, such as a snake or ↑lizard, whose body temperature changes according to the temperature around it, and that usually lays eggs to have babies爬行动物
- This kind of capacity is exclusive to reptiles.
- Because of social pay off, we got enough money to protect this endanger kind of reptiles.
- You are missing the point, what I just expressed was that this kind of reptile is endanger due to human activities.
primate [ˈpraɪmeɪt]: n. a member of the group of animals that includes humans and monkeys灵长类的动物
- Chances are that primates are blessed with larger cerebral cortex.
- This sort of primates are found in many parts of the world.
- Believe it or not, primates are vanishing from the zoo that is famous for various primates.
lobe [loʊb]: n. technical a round part of an organ in your body, especially in your brain or lungs(脑)叶
swoop [swup]: v. if a bird or aircraft swoops, it moves suddenly down through the air, especially in order to attack something俯冲
- As soon as I call her, my cat will be swooping towards me from the scaffolding.
- No one could account for the fact that the bird was swooping towards me regardless its life.
- The plants at nearby airport swooping towards my house are driving me crazy.
frontal [ˈfrʌnt(ə)l]: adj. medical relating to the front part of the head额骨的
parietal [pə'raɪətəl]: adj. 顶骨的
occipital [ɒk'sɪpətəl]: adj. 枕骨的
temporal [ˈtemp(ə)rəl]: adj. 太阳穴的
topography [təˈpɑɡrəfi] topographical: n.adj. the science of describing an area of land, or making maps of it地形学
- I was shocked by the topographical map of my hometown in the first place.
- The topographical map shows the evidence of a earthquake in the past.
- The topographical map inspired me to become an explorer.
motor [ˈmoʊtər]: adj. technical relating to nerves that make muscles move肌肉运动的
- His motor area was badly damaged by the iron stick when he tried to explode the stone.
- There is something strange in his motor area.
- Some disorder in his motor area causes him lose control of his limbs.
twitch [twɪtʃ]: v. if a part of someone’s body twitches, or if they twitch it, it makes a small sudden movement抽搐
- The scanner shows that your baby is twicthing in your womb.
- The twitching girl has a 17% chance of being diagnosed with schizophrenia.
- The girl with schizophrenia has been twitching since she was sent to hospital.
somatosensory [ˌsoʊmətə'sensərɪ]: adj. (耳、目、口等以外的)体觉的
- The disorder of somatosensory system led to his blindness.
- He is an elite doctor who is famous for the disorders of somatosensory system.
- Because of the damage of somatosensory system, he can't be an athlete for the rest of his life.
projection [prəˈdʒekʃ(ə)n]: n. the act of projecting a film or picture onto a screen投影
- The mode of projection is reset by the factory.
- The projection technique is mature over the course of decades.
- The teachers at the school are using projection to teach some chemistry experiments.
magnetic [mæɡˈnetɪk]: adj. concerning or produced by ↑magnetism磁的
- The infant seems to take interest in a magnetic iron.
- In my childhood, I am aware that a sounder is formed by magnetic irons.
- Because of his selling magnetic wire, he was sentenced to be in prison for three years.
tumor [ˈtumər]: n. a mass of diseased cells in your body that have divided and increased too quickly肿瘤
- My niece is diagnosed with a tumor in her left ankle.
- My niece with a tumor in her left ankle has a difficult time in going to school. 
- I wish that my niece never had a tumor and led a normal life.
stroke [stroʊk]: n. if someone has a stroke, an ↑artery (=tube carrying blood) in their brain suddenly bursts or becomes blocked, so that they may die or be unable to use some muscles中风
- The hospital has built green channel for those patients who had a stroke suddenly.
- Our grandfather had a stroke and couldn't go out of the bed for two weeks.
- I'd rather die a stroke than run out of my money and lead a poor life for the rest of my life.
motorcycle [ˈmoʊtərˌsaɪk(ə)l]: n. a fast two-wheeled vehicle with an engine SYN motorbike摩托车
- What he called his lover was indeed a motorcycle in his garage.
- I was wanted for the police due to my missing motorcycle.
- My cat likes to lie on the seat of the motorcycle.
psychic [ˈsaɪkɪk]: adj. affecting the mind rather than the body精神的,超自然的
- The TV station has developed a series of programs debunk psychic phenomena.
- In this country, the psychic salvation gave way to secular concerns about people's life.
- Nowadays, this kind of psychic phenomena has some scientific hypotheses.
blind [blaɪnd] blindness: adj.n. unable to see瞎的, 盲目的
- It is evil to trick a blind old lady who used to devote herself to our community.
- Keeping in mind, you should step aside when running into a blind person.
- Absolutely, this path is designed for those blind people.
profile [ˈproʊˌfaɪl]: n. a side view of someone’s head侧面像
- I must admit that he lost his attraction to me because of his ugly profile.
- Why the director rated him so high is his handsome profile.
- This time, his handsome profile doesn't do the trick and he lost the opportunity to take part in the movie.
mild [maɪld]: adj. a mild illness or health problem is not serious温和的
- No need to worry, there are many operations that can treat a mild tumor.
- Because of his fail in a romantic relationship, he developed a mild schizophrenia.
- Although he develops a mild schizophrenia, the headmaster is still able to dedicate his life to the education.
sensory [ˈsensəri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
- Because schizophrenia is mild, his sensory functions still work well.
- He has a 17% chance of having the disorder of his sensory functions after the operation.
- After the operation, his sensory functions still work well, but his motor functions doesn't.
moral [ˈmɔrəl]: n. a practical lesson about what to do or how to behave, which you learn from a story or from something that happens to you ⇨ message教益
- The moral of the story is that we still can lead a meaningful life even if we develop a schizophrenia.
- The moral of the story is to instruct our children to obey traffic rules.
- The moral of the doctrines is that we should do our work with our goals in mind.
hard-pressed: adj. having a lot of problems and not enough money or time处于困境的
- He carrys an obligation to help his relatives who are hard-pressed.
- The firefighters is trying to help the hard-pressed cat who got caught on the high windowsill.
- Even an eminent lawyer could be hard-pressed because of difficult cases.
--------------------
spinal cord [ˈspaɪn(ə)l] [kɔrd]: 脊髓
- I have tasted spinal cord, not of human, not bad.
- The so-called psychic doctor claimed that I had some problem about my spinal cord.
- I am unwilling to dedicate my spinal cord to my cousin who used to bully me.
this isn't small potatoes: 这可不是小事
- Your cat is developing vomiting, this isn't small potatoes.
- My wife is full of negative emotions and she is pregnant, this isn't small potatoes.
- There is no baby in her womb in the scanner, this isn't small potatoes.
crumple sth. up: 弄皱某物
- My mother is always blaming me on crumpling newspapers up.
- My wife is working on my clothes which is crumpled up by accident.
- The lady is trying to straighten out the rug which was crumpled up by her son.
straighten sth. out: 变直弄直某物
- It's impossible to straighten out the paper without effective equipment.
- Equipped with new machine, the housewife yearns for straightening the rug out.
- I have a habit of straightening the blanket out before going to bed.
demarcate A into B(s): 界定A为B(复数)
- My deskmate used a chalk to demarcate the desk into two areas.
- My wife demarcated the day into two period, one of which I can watch TV, another of which she can. 
- The chalk marker seems to demarcate the room into two areas.
correspond to sth.: 对应于某事物
- My rising heart beat corresponds to my eagerness to work for the company.
- His out of breath corresponds to his excitement for the activity.
- The colors of the indication corresponds to different danger level.
be proportioned to the extend: 与程度成比例
- His social position is proportioned to the extend to which he dedicated his life to the society.
- His money is proportioned to the extend to which he sacrifices him.
- The prize is proportioned to the extend to which you struggle with the goal.
mistake A for B: 把A误认为B
- My wife got angry because I mistook her for another colleague.
- You have a 17% chance of mistaking your wife for another girl after she makes up.
- Obviously, she mistakes the plastic for something she could feast on.
** sentence2
inclusive [ɪnˈklusɪv]: adj. an inclusive price or cost includes everything OPP exclusive包含的, 包括的
- These mutilated people shouldn't be vanishing from the inclusive community.
- This holiday season we are going to visit an inclusive monastery lying on the pass.
- You can consign the sweater to the inclusive closet.
suck [sʌk]: v. to take air, liquid etc into your mouth by making your lips form a small hole and using the muscles of your mouth to pull it in吮吸
- With the speech involved in his mistakes, the president began to suck his little finger.
- Imagine a day when you can suck delicious ice cream at a seaside resort for free.
- Without explicit conditions, you are not allowed to suck ice cream.
newborn [ˈnuˌbɔrn]: n. newborn child/baby/son etc a child that has just been born婴儿
- The official was determined to foster a system of taking care of newborns in the town.
- The cohort with fevers is formed by 7 newborns and 3 adolescents.
- Newborns have never been treated so terribly as in the camp throughout human history.
vomit [ˈvɒmit]: v. to bring food or drink up from your stomach out through your mouth, because you are ill呕吐
- Obviously, the adolescent is describing his little sister developing vomiting.
- Because of my wife's pregnancy and she will vomit on the bus, we failed to make a journey last weekend.
- At a seaside resort, she received a warm treatment after her vomiting.
cerebral [səˈribrəl]: adj. medical relating to or affecting your brain大脑的
cortex [ˈkɔrˌteks]: n. the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
cerebellum [ˌserəˈbeləm]: n. technical the bottom part of your brain that controls your muscles小脑
visceral [ˈvɪsərəl]: adj. literary visceral beliefs and attitudes are the result of strong feelings rather than careful thought肺腑的
- Everyone at the party expressed their visceral opinions about the community through this process.
- The citizen carried an obligation to articulate his visceral words in the court.
- From his visceral speaking in public, I knew he was unwilling to give away his property.
distinctive [dɪˈstɪŋktɪv]: adj. having a special quality, character, or appearance that is different and easy to recognize独特的
- The distinctive circumstances have obligated him to develop a system of protecting himself.
- His distinctive response to our presents is to return the flavor after a week.
- His method of research is so distinctive that no one could account for his statistics.
rug [rʌɡ]: n. a piece of thick cloth or wool that covers part of a floor, used for warmth or as a decoration ⇨ mat, carpet(小)地毯, 垫子
- Getting a rug from the community for free, the old lady satisfied herself at the expense of her son.
- My wife gained an adorable piece of rug from the flight attendant.
- The patterns of rugs take many forms.
reason [ˈriz(ə)n]: v. to form a particular judgment about a situation after carefully considering the facts推理
- The innocent person must be indebted to his reasoning.
- His speaking in the meeting is read as his reasoning about the scandal.
- The eminent lawyer admired his son for his reasoning about the case.
reptile [ˈreptɪl]: n. a type of animal, such as a snake or ↑lizard, whose body temperature changes according to the temperature around it, and that usually lays eggs to have babies爬行动物
- This kind of capacity is exclusive to reptiles.
- Because of social payoff, we have enough money to protect this endangered kind of reptile.
- You are missing the point, what I just expressed was that this kind of reptile is endangered due to human activities.
primate [ˈpraɪmeɪt]: n. a member of the group of animals that includes humans and monkeys灵长类的动物
- Chances are that primates are blessed with a larger cerebral cortex.
- This sort of primate is found in many parts of the world.
- Believe it or not, primates are vanishing from the zoo that is famous for various primates.
lobe [loʊb]: n. technical a round part of an organ in your body, especially in your brain or lungs(脑)叶
swoop [swup]: v. if a bird or aircraft swoops, it moves suddenly down through the air, especially in order to attack something俯冲
- As soon as I call her, my cat will be swooping towards me from the scaffolding.
- No one could account for the fact that the bird was swooping towards me regardless of its life.
- The plants at the nearby airport swooping towards my house are driving me crazy.
frontal [ˈfrʌnt(ə)l]: adj. medical relating to the front part of the head额骨的
parietal [pə'raɪətəl]: adj. 顶骨的
occipital [ɒk'sɪpətəl]: adj. 枕骨的
temporal [ˈtemp(ə)rəl]: adj. 太阳穴的
topography [təˈpɑɡrəfi] topographical: n.adj. the science of describing an area of land, or making maps of it地形学
- I was shocked by the topographical map of my hometown in the first place.
- The topographical map shows the evidence of an earthquake in the past.
- The topographical map inspired me to become an explorer.
motor [ˈmoʊtər]: adj. technical relating to nerves that make muscles move肌肉运动的
- His motor area was badly damaged by the iron stick when he tried to explode the stone.
- There is something strange in his motor area.
- Some disorder in his motor area causes him to lose control of his limbs.
twitch [twɪtʃ]: v. if a part of someone’s body twitches, or if they twitch it, it makes a small sudden movement抽搐
- The scanner shows that your baby is twitching in your womb.
- The twitching girl has a 17% chance of being diagnosed with schizophrenia.
- The girl with schizophrenia has been twitching since she was sent to hospital.
somatosensory [ˌsoʊmətə'sensərɪ]: adj. (耳、目、口等以外的)体觉的
- The disorder of the somatosensory system led to his blindness.
- He is an elite doctor who is famous for the disorders of the somatosensory system.
- Because of the damage to the somatosensory system, he can't be an athlete for the rest of his life.
projection [prəˈdʒekʃ(ə)n]: n. the act of projecting a film or picture onto a screen投影
- The mode of projection is reset by the factory.
- The projection technique is mature over the course of decades.
- The teachers at the school are using projection to teach some chemistry experiments.
magnetic [mæɡˈnetɪk]: adj. concerning or produced by ↑magnetism磁的
- The infant seems to take an interest in a magnetic iron.
- In my childhood, I was aware that a sounder is formed by magnetic irons.
- Because of his selling magnetic wire, he was sentenced to be in prison for three years.
tumor [ˈtumər]: n. a mass of diseased cells in your body that have divided and increased too quickly肿瘤
- My niece is diagnosed with a tumor in her left ankle.
- My niece with a tumor in her left ankle has a difficult time going to school. 
- I wish that my niece never had a tumor and led a normal life.
stroke [stroʊk]: n. if someone has a stroke, an ↑artery (=tube carrying blood) in their brain suddenly bursts or becomes blocked, so that they may die or be unable to use some muscles中风
- The hospital has built a green channel for those patients who had a stroke suddenly.
- Our grandfather had a stroke and couldn't go out of bed for two weeks.
- I'd rather die a stroke than run out of money and lead a poor life for the rest of my life.
motorcycle [ˈmoʊtərˌsaɪk(ə)l]: n. a fast two-wheeled vehicle with an engine SYN motorbike摩托车
- What he called his lover was indeed a motorcycle in his garage.
- I was wanted by the police due to my missing motorcycle.
- My cat likes to lie on the seat of the motorcycle.
psychic [ˈsaɪkɪk]: adj. affecting the mind rather than the body精神的,超自然的
- The TV station has developed a series of programs to debunk psychic phenomena.
- In this country, psychic salvation gave way to secular concerns about people's lives.
- Nowadays, this kind of psychic phenomenon has some scientific hypotheses.
blind [blaɪnd] blindness: adj.n. unable to see瞎的, 盲目的
- It is evil to trick a blind old lady who used to devote herself to our community.
- Keeping in mind that you should step aside when running into a blind person.
- Absolutely, this path is designed for those blind people.
profile [ˈproʊˌfaɪl]: n. a side view of someone’s head侧面像
- I must admit that he lost his attraction to me because of his ugly profile.
- Why the director rated him so high is his handsome profile.
- This time, his handsome profile doesn't do the trick and he lost the opportunity to take part in the movie.
mild [maɪld]: adj. a mild illness or health problem is not serious温和的
- No need to worry, there are many operations that can treat a mild tumor.
- Because of his failure in a romantic relationship, he developed mild schizophrenia.
- Although he develops mild schizophrenia, the headmaster is still able to dedicate his life to education.
sensory [ˈsensəri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
- Because schizophrenia is mild, his sensory functions still work well.
- He has a 17% chance of having the disorder of his sensory functions after the operation.
- After the operation, his sensory functions still work well, but his motor functions don't.
moral [ˈmɔrəl]: n. a practical lesson about what to do or how to behave, which you learn from a story or from something that happens to you ⇨ message教益
- The moral of the story is that we still can lead a meaningful life even if we develop schizophrenia.
- The moral of the story is to instruct our children to obey traffic rules.
- The moral of the doctrines is that we should do our work with our goals in mind.
hard-pressed: adj. having a lot of problems and not enough money or time处于困境的
- He carries an obligation to help his relatives who are hard-pressed.
- The firefighters are trying to help the hard-pressed cat who got caught on the high windowsill.
- Even an eminent lawyer could be hard-pressed because of difficult cases.
--------------------
spinal cord [ˈspaɪn(ə)l] [kɔrd]: 脊髓
- I have tasted the spinal cord, not of humans, not bad.
- The so-called psychic doctor claimed that I had some problem with my spinal cord.
- I am unwilling to dedicate my spinal cord to my cousin who used to bully me.
this isn't small potatoes: 这可不是小事
- Your cat is developing vomiting, this isn't small potatoes.
- My wife is full of negative emotions and she is pregnant, this isn't small potatoes.
- There is no baby in her womb in the scanner, this isn't small potatoes.
crumple sth. up [ˈkrʌmp(ə)l]: 弄皱某物
- My mother is always blaming me on crumpling newspapers up.
- My wife is working on my clothes which is crumpled up by accident.
- The lady is trying to straighten out the rug which was crumpled up by her son.
straighten sth. out [ˈstreɪt(ə)n]: 变直弄直某物
- It's impossible to straighten out the paper without effective equipment.
- Equipped with a new machine, the housewife yearns to straighten the rug out.
- I have a habit of straightening the blanket out before going to bed.
demarcate A into B(s) [ˈdimɑrˌkeɪt]: 界定A为B(复数)
- My deskmate used chalk to demarcate the desk into two areas.
- My wife demarcated the day into two periods, one of which I can watch TV, another of which she can. 
- The chalk marker seems to demarcate the room into two areas.
correspond to sth.: 对应于某事物
- My rising heartbeat corresponds to my eagerness to work for the company.
- His sallow breath corresponds to his excitement for the activity.
- The colors of the indication correspond to different danger levels.
be proportioned to the extent: 与程度成比例
- His social position is proportioned to the extent to which he dedicated his life to society.
- His money is proportioned to the extent to which he sacrifices him.
- The prize is proportioned to the extent to which you struggle with the goal.
mistake A for B: 把A误认为B
- My wife got angry because I mistook her for another colleague.
- You have a 17% chance of mistaking your wife for another girl after she makes up.
- Obviously, she mistakes the plastic for something she could feast on.
