#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2-1 4 Parts of the brain
#+begin_verse
So, let's talk about the different parts of the brain and what they do.
Parts of the brain are functionalized for different purposes, they do different things.
Which is why damage to different parts of the brain has different effects.
It's why when you look at an fMRI scan or PET scan or some something that records neural activity,
	you could figure out based on the location of the activity what's going on.
So, the first thing to realize is I'm talking about the brain,
	but I'd be more precise and more inclusive
		if I talked about the brain and parts of the spinal cord.
So, you don't need your brain for everything.
There're certain activities we do that can happen without a brain.
Like sucking in newborns or pulling your limb back to withdraw from pain or vomiting.
But for everything else we talk about in this course, we'll really be talking about the brain.

So, some of the structures of the brain that are highly relevant are called subcortical,
	which means they're below the cortex, which means they're in the center of the brain.
This includes part of the brain like the medulla,
	which control certain automatic function
		like your heart rate, your blood pressure, swallowing, and so on.
It includes the cerebellum, which is involved in body balance and muscle coordination.
It contains about 30 billion neurons.
So, this isn't small potatoes.
The hypothalamus, which is involved in feeding and sex and thirst and different appetites.
We're going to talk about emotions or visceral desires, we'll return to those parts of the brain.

But for the aspects of psychology that are distinctive for us, that make us human,
	we're mostly focused on the outer layer, the cerebral cortex.
So, the cerebral cortex it is all crumpled up.
If you were to take a brain, pull out the cortex and straighten it out,
		like you're removing a rug you got from the trunk of your car and you have to straighten it out,
	it's about two feet square.
So, it's lot of crumpling to get it in.
It's about three millimeters thick.
This is where the action is.
This is where at least for the things I'm interested in, this is where it takes place.
Is where reasoning and language and complex perception comes from.
Fish don't have any cerebral cortex, reptiles and birds have a little bit,
	but primates, including humans, have a lot.
	
When you look at the cortex, you'll see it has two halves.
It has a left half and a right half.
For each of these halves, when you look at it,
	you can demarcate the brain, the cortex into different lobes.
There's going from your forehead and swooping to the back.
You have the frontal lobe conveniently enough on the front.
The parietal lobe, the occipital lobe, and the temporal lobe.
Each of these lobes, there's different things, which we'll talk about in a bit.

Another thing about the cortex though which is super interesting, is that it includes maps.
What I mean by this is it includes topographical maps
	where two things that are close together in the brain are similarly close together in the body.
So, there is a motor area
	where if you were to shock, parts of that brain, parts of the body would twitch accordingly.
Just like you'd expect, the middle finger is close to the thumb which is closer to elbow.
If it's close in the real-world and your body it's close to the brain
	and there is a primary somatosensory area, which is the sense organs.
There if you have somebody in the operating table and you shocked people,
	they would experience things, they might experience a sound or a flash of light or a touch.
In fact, in the occipital lobe, you have a map for vision
	and in the temporal lobe, you have a map for sound.
What's really cool is, I said the map is topographical,
	but the size of the brain areas don't correspond to the size of the actual body areas,
		but rather to the extent to which there's motor or sensory function.
So, artists have drawn pictures of people
	if their body was proportioned to the extent that their brain was.
You'd see the trunk of the body is relatively small,
	but their hands are enormous and the face is enormous because there's a whole lot of sensation.
There is much more sensation going on in your hand than in your whole back
	even though the back is physically apart.
So, part of the cortex is these projection areas.
But less than a quarter of the cortex contains projection areas.
As I said, the rest is involved with the cool stuff.
With language, with reasoning, with moral thoughts, and so on.

Then the question comes in, how do we know this?
How do we know what parts of the brain do what, what parts of the brain are involved, and why?
There's different answers.
So, one answer is we can scan the brain.
We can use MRI, which is a high-frequency magnetic field, to look at the activity of the brain,
	what parts are active when people do different things.
We can also look at so-called natural experiments
	when people have tumors or strokes or motorcycle accidents.
In damaged part of your brain and we can ask the question,
	what damage to which parts of the brain correspond to damage to which functions?
Through these different methods,
	we've learned about the different parts of the brain and what they do.
We could talk about some certain specific things that can go wrong
	due to brain damage or stroke or trauma.
	
So, for instance, there's Apraxia.
Apraxia is problems of actions.
So, you're unable to do an action
	like waving goodbye or picking up before or can bring some food to your mouth.
You're not paralyze.
You can make the movements if you have to,
	but you can't coordinate these basic movements into complex actions.
	
There's Agnosia.
Agnosia is a disorders of perception.
And they're not like you can't see, but you can't recognize.
Some is called psychic blindness.
People of various forms of Agnosia can describe a picture in terms of it's part,
	but can't recognize the objects that are being depicted.
That's a form of visual Agnosia.
There's also a specific Prosopagnosia, where you can't recognize faces.
Oliver Sacks wrote a wonderful book many years ago called The Man Who Mistook His Wife For a Hat.
This was a series of profiles of people who had surprising neurological disorders
	and the title case of the book was a man who actually had such an inability to recognize faces,
		he couldn't distinguishes his wife's face from that of a hat.
Milder forms of Prosopagnosia, which some people suffer from
	and to be honest, I got a little bit of some terrible faces.
Is that you could recognize faces as faces,
	but you can't recognize whose face they are and it's very hard for you to recognize people.
	
There's problems of sensory neglect.
You get disorders that block out one part of the world.
You might have damage to parts of your brain that would block out the left side of the world.
It's not just the sort of physical thing,
	when you ask somebody with such a disorder to draw clock for instance,
		they'll put all the numbers from one to 12 on the right side of the clock.
It's as if they don't think of the left side of the world again.
So, maybe it's not even a sensory problem, but an attentional problem.

There's Aphasia, which refers to disorders of language.
Some forms of aphasia are expressive like a Broca's Aphasia, where you can't really speak.
A famous case of somebody who can only use the word tan,
	would say tan, tan, tan, but couldn't say anything else.
Or then there's something that's called Receptive Aphasia,
		where you can speak although what you say doesn't make much sense,
	but also you have a terrible time understanding other people.
	
Then there's all sorts of other disorders.
There's the disorder which we talked about with regard to Phineas Gage and various forms of it.
Where damage to your brain, it's debatable whether this is true Phineas Gage,
	but there are other cases where it's much more clear.
Cause you to lose your moral sense, your sense of right and wrong,
		your ability to control yourself,
	to restrain yourself perhaps your conscience.

Now, we're going to talk about all of these things through the course but the moral here is that,
	A, there's some localization of function.
There's some sense in which it correspond to different brain areas.
B, again, this is an argument against dualism.
We can see that in that anyone who argued that the mind isn't the brain
	would be hard-pressed to explain why damage to the brain
			seems to affect some very intimate and very important aspects of ourselves.
#+end_verse
** expression
inclusive […™nЋИklus…™v]: adj. an inclusive price or cost includes everything OPP exclusiveеМЕеРЂзЪД, еМЕжЛђзЪД
suck [s Мk]: v. to take air, liquid etc into your mouth by making your lips form a small hole and using the muscles of your mouth to pull it inеРЃеРЄ
newborn [ЋИnuЋМb…Фrn]: n. newborn child/baby/son etc a child that has just been bornе©іеДњ
vomit [ЋИv…Тmit]: v. to bring food or drink up from your stomach out through your mouth, because you are illеСХеРР
cerebral [s…ЩЋИribr…Щl]: adj. medical relating to or affecting your brainе§ІиДСзЪД
cortex [ЋИk…ФrЋМteks]: n. the outer layer of an organ in your body, especially your brain(иДСжИЦиВЊзЪД)зЪЃе±В, зЪЃиі®
cerebellum [ЋМser…ЩЋИbel…Щm]: n. technical the bottom part of your brain that controls your musclesе∞ПиДС
visceral [ЋИv…™s…Щr…Щl]: adj. literary visceral beliefs and attitudes are the result of strong feelings rather than careful thoughtиВЇиЕСзЪД
distinctive [d…™ЋИst…™≈Лkt…™v]: adj. having a special quality, character, or appearance that is different and easy to recognizeзЛђзЙєзЪД
rug [r М…°]: n. a piece of thick cloth or wool that covers part of a floor, used for warmth or as a decoration вЗ® mat, carpet(е∞П)еЬ∞жѓѓ, еЮЂе≠Р
reason [ЋИriz(…Щ)n]: v. to form a particular judgment about a situation after carefully considering the factsжО®зРЖ
reptile [ЋИrept…™l]: n. a type of animal, such as a snake or вЖСlizard, whose body temperature changes according to the temperature around it, and that usually lays eggs to have babiesзИђи°МеК®зЙ©
primate [ЋИpra…™me…™t]: n. a member of the group of animals that includes humans and monkeysзБµйХњз±їзЪДеК®зЙ©
lobe [lo Кb]: n. technical a round part of an organ in your body, especially in your brain or lungs(иДС)еПґ
swoop [swup]: v. if a bird or aircraft swoops, it moves suddenly down through the air, especially in order to attack somethingдњѓеЖ≤
frontal [ЋИfr Мnt(…Щ)l]: adj. medical relating to the front part of the headйҐЭй™®зЪД
parietal [p…Щ'ra…™…Щt…Щl]: adj. й°ґй™®зЪД
occipital […Тk's…™p…Щt…Щl]: adj. жЮХй™®зЪД
temporal [ЋИtemp(…Щ)r…Щl]: adj. е§™йШ≥з©ізЪД
topography [t…ЩЋИp…С…°r…Щfi] topographical: n.adj. the science of describing an area of land, or making maps of itеЬ∞ељҐе≠¶
motor [ЋИmo Кt…Щr]: adj. technical relating to nerves that make muscles moveиВМиВЙињРеК®зЪД
twitch [tw…™t Г]: v. if a part of someoneвАЩs body twitches, or if they twitch it, it makes a small sudden movementжКљжРР
somatosensory [ЋМso Кm…Щt…Щ'sens…Щr…™]: adj. (иА≥гАБзЫЃгАБеП£з≠Йдї•е§ЦзЪД)дљУиІЙзЪД
projection [pr…ЩЋИd Тek Г(…Щ)n]: n. the act of projecting a film or picture onto a screenжКХељ±
magnetic [m√¶…°ЋИnet…™k]: adj. concerning or produced by вЖСmagnetismз£БзЪД
tumor [ЋИtum…Щr]: n. a mass of diseased cells in your body that have divided and increased too quicklyиВњзШ§
stroke [stro Кk]: n. if someone has a stroke, an вЖСartery (=tube carrying blood) in their brain suddenly bursts or becomes blocked, so that they may die or be unable to use some musclesдЄ≠й£О
motorcycle [ЋИmo Кt…ЩrЋМsa…™k(…Щ)l]: n. a fast two-wheeled vehicle with an engine SYN motorbikeжС©жЙШиљ¶
psychic [ЋИsa…™k…™k]: adj. affecting the mind rather than the bodyз≤Њз•ЮзЪД
blind [bla…™nd] blindness: adj.n. unable to seeзЮОзЪД, зЫ≤зЫЃзЪД
profile [ЋИpro КЋМfa…™l]: n. a side view of someoneвАЩs headдЊІйЭҐеГП
mild [ma…™ld]: adj. a mild illness or health problem is not seriousжЄ©еТМзЪД
sensory [ЋИsens…Щri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touchжДЯиІЙзЪД, жДЯеЃШзЪД
moral [ЋИm…Фr…Щl]: n. a practical lesson about what to do or how to behave, which you learn from a story or from something that happens to you вЗ® messageжХЩзЫК
hard-pressed: adj. having a lot of problems and not enough money or timeе§ДдЇОеЫ∞еҐГзЪД
--------------------
spinal cord [ЋИspa…™n(…Щ)l] [k…Фrd]: иДКйЂУ
this isn't small potatoes: ињЩеПѓдЄНжШѓе∞ПдЇЛ
crumple sth. up: еЉДзЪ±жЯРзЙ©
straighten sth. out: еПШзЫіеЉДзЫіжЯРзЙ©
demarcate A into B(s): зХМеЃЪAдЄЇB(е§НжХ∞)
correspond to sth.: еѓєеЇФдЇОжЯРдЇЛзЙ©
be proportioned to the extend: дЄОз®ЛеЇ¶жИРжѓФдЊЛ
mistake A for B: жККAиѓѓиЃ§дЄЇB
** ch.
	
** sentence
inclusive […™nЋИklus…™v]: adj. an inclusive price or cost includes everything OPP exclusiveеМЕеРЂзЪД, еМЕжЛђзЪД
- 
- 
- 
suck [s Мk]: v. to take air, liquid etc into your mouth by making your lips form a small hole and using the muscles of your mouth to pull it inеРЃеРЄ
- 
- 
- 
newborn [ЋИnuЋМb…Фrn]: n. newborn child/baby/son etc a child that has just been bornе©іеДњ
- 
- 
- 
vomit [ЋИv…Тmit]: v. to bring food or drink up from your stomach out through your mouth, because you are illеСХеРР
- 
- 
- 
cerebral [s…ЩЋИribr…Щl]: adj. medical relating to or affecting your brainе§ІиДСзЪД
- 
- 
- 
cortex [ЋИk…ФrЋМteks]: n. the outer layer of an organ in your body, especially your brain(иДСжИЦиВЊзЪД)зЪЃе±В, зЪЃиі®
- 
- 
- 
cerebellum [ЋМser…ЩЋИbel…Щm]: n. technical the bottom part of your brain that controls your musclesе∞ПиДС
- 
- 
- 
visceral [ЋИv…™s…Щr…Щl]: adj. literary visceral beliefs and attitudes are the result of strong feelings rather than careful thoughtиВЇиЕСзЪД
- 
- 
- 
distinctive [d…™ЋИst…™≈Лkt…™v]: adj. having a special quality, character, or appearance that is different and easy to recognizeзЛђзЙєзЪД
- 
- 
- 
rug [r М…°]: n. a piece of thick cloth or wool that covers part of a floor, used for warmth or as a decoration вЗ® mat, carpet(е∞П)еЬ∞жѓѓ, еЮЂе≠Р
- 
- 
- 
reason [ЋИriz(…Щ)n]: v. to form a particular judgment about a situation after carefully considering the factsжО®зРЖ
- 
- 
- 
reptile [ЋИrept…™l]: n. a type of animal, such as a snake or вЖСlizard, whose body temperature changes according to the temperature around it, and that usually lays eggs to have babiesзИђи°МеК®зЙ©
- 
- 
- 
primate [ЋИpra…™me…™t]: n. a member of the group of animals that includes humans and monkeysзБµйХњз±їзЪДеК®зЙ©
- 
- 
- 
lobe [lo Кb]: n. technical a round part of an organ in your body, especially in your brain or lungs(иДС)еПґ
- 
- 
- 
swoop [swup]: v. if a bird or aircraft swoops, it moves suddenly down through the air, especially in order to attack somethingдњѓеЖ≤
- 
- 
- 
frontal [ЋИfr Мnt(…Щ)l]: adj. medical relating to the front part of the headйҐЭй™®зЪД
parietal [p…Щ'ra…™…Щt…Щl]: adj. й°ґй™®зЪД
occipital […Тk's…™p…Щt…Щl]: adj. жЮХй™®зЪД
temporal [ЋИtemp(…Щ)r…Щl]: adj. е§™йШ≥з©ізЪД
topography [t…ЩЋИp…С…°r…Щfi] topographical: n.adj. the science of describing an area of land, or making maps of itеЬ∞ељҐе≠¶
- 
- 
- 
motor [ЋИmo Кt…Щr]: adj. technical relating to nerves that make muscles moveиВМиВЙињРеК®зЪД
- 
- 
- 
twitch [tw…™t Г]: v. if a part of someoneвАЩs body twitches, or if they twitch it, it makes a small sudden movementжКљжРР
- 
- 
- 
somatosensory [ЋМso Кm…Щt…Щ'sens…Щr…™]: adj. (иА≥гАБзЫЃгАБеП£з≠Йдї•е§ЦзЪД)дљУиІЙзЪД
- 
- 
- 
projection [pr…ЩЋИd Тek Г(…Щ)n]: n. the act of projecting a film or picture onto a screenжКХељ±
- 
- 
- 
magnetic [m√¶…°ЋИnet…™k]: adj. concerning or produced by вЖСmagnetismз£БзЪД
- 
- 
- 
tumor [ЋИtum…Щr]: n. a mass of diseased cells in your body that have divided and increased too quicklyиВњзШ§
- 
- 
- 
stroke [stro Кk]: n. if someone has a stroke, an вЖСartery (=tube carrying blood) in their brain suddenly bursts or becomes blocked, so that they may die or be unable to use some musclesдЄ≠й£О
- 
- 
- 
motorcycle [ЋИmo Кt…ЩrЋМsa…™k(…Щ)l]: n. a fast two-wheeled vehicle with an engine SYN motorbikeжС©жЙШиљ¶
- 
- 
- 
psychic [ЋИsa…™k…™k]: adj. affecting the mind rather than the bodyз≤Њз•ЮзЪД
- 
- 
- 
blind [bla…™nd] blindness: adj.n. unable to seeзЮОзЪД, зЫ≤зЫЃзЪД
- 
- 
- 
profile [ЋИpro КЋМfa…™l]: n. a side view of someoneвАЩs headдЊІйЭҐеГП
- 
- 
- 
mild [ma…™ld]: adj. a mild illness or health problem is not seriousжЄ©еТМзЪД
- 
- 
- 
sensory [ЋИsens…Щri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touchжДЯиІЙзЪД, жДЯеЃШзЪД
- 
- 
- 
moral [ЋИm…Фr…Щl]: n. a practical lesson about what to do or how to behave, which you learn from a story or from something that happens to you вЗ® messageжХЩзЫК
- 
- 
- 
hard-pressed: adj. having a lot of problems and not enough money or timeе§ДдЇОеЫ∞еҐГзЪД
- 
- 
- 
--------------------
spinal cord [ЋИspa…™n(…Щ)l] [k…Фrd]: иДКйЂУ
- 
- 
- 
this isn't small potatoes: ињЩеПѓдЄНжШѓе∞ПдЇЛ
- 
- 
- 
crumple sth. up: еЉДзЪ±жЯРзЙ©
- 
- 
- 
straighten sth. out: еПШзЫіеЉДзЫіжЯРзЙ©
- 
- 
- 
demarcate A into B(s): зХМеЃЪAдЄЇB(е§НжХ∞)
- 
- 
- 
correspond to sth.: еѓєеЇФдЇОжЯРдЇЛзЙ©
- 
- 
- 
be proportioned to the extend: дЄОз®ЛеЇ¶жИРжѓФдЊЛ
- 
- 
- 
mistake A for B: жККAиѓѓиЃ§дЄЇB
- 
- 
- 
