#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2-2 4 Defense mechanisms
#+begin_verse
So, suppose you survive these developmental stages and you're now an adult,
	and you're not out of the woods yet,
	there are all sorts of challenges and problems you're faced with.
One problem is that your Id is sending up all sorts of desires,
		all sorts of weird sick stuff, sexual and violent,
	and these are forbidden by the super ego.
It's not merely that you can't act upon them, so you shouldn't be thinking them,
	and so they get pushed down or repressed.
You could even imagine a sort of a metaphor of you pushing down something,
		like some water spraying out from leaks on a floor
	and you're jamming towels over it or something like that.
Some of this repressed stuff, as in my fine metaphor, spills out, you can't contain everything.
For Freud, it spills out in jokes and slips of the tongue and in dreams.

But also for Freud, there are other ways to cope with these desires.
There's other ways to repress them and these are what Freud described as defense mechanisms.
They defend the ego from this terrible stuff that's coming out from the Id,
	and some of these you may be familiar with.
We tend to use them in everyday language, another example of Freud's influence.
There's displacement, where you redirect shameful thoughts to more appropriate targets.
You can imagine a boy who hates his father,
	and that's really unacceptable, you shouldn't hate your father.
So instead, he bullies another kid or kicks the dog.
He turns his anger and his hatred towards his father
	to a more appropriate and more acceptable target.
So, there's sublimation.
Sublimation you take desires that are unacceptable
	and you displace them to more valuable activities.
So for instance, somebody who has a strong sexual desires of forbiddens
	might devote a lot of energy to his or her work or studies.
	
There's projection.
Projection is reducing anxiety
	by taking these impulses you have that you're ashamed of and attributing them to somebody else.
So, imagine a woman with strong homosexual desires, and because of how she was raised,
	her super ego tells her these are unacceptable, they're inappropriate.
So she becomes unconscious of them.
But she comes to believe that there are other women are sexually drawn to her.
Or you may really dislike somebody you shouldn't dislike,
	and then come to a conclusion, "Oh my gosh, this person must hate me."
Because your own shameful feelings are unacceptable, you will project them onto somebody else.

There's rationalization, where you have certain anxiety-producing thoughts
	and you reason them away into more acceptable ways.
So for instance, somebody might get pleasure,
	a father may get pleasure physically punishing his children.
But nobody wants to think that of themselves.
So the way he describes it to himself, the way he really believes it at the level of the self,
	the ego is that he's doing it for their own good.
You know in general, a lot of the bad things we do, we rationalize.

There's regression, and you see this in children
	where the idea is under certain forms of stress
		or stressful desires and stressful impulses from the id,
	you might retreat to a mode of behavior that's characteristic of an earlier stage.
So you see this in some sense a child might suddenly act like a much younger child.

Finally, there's reaction formation which is cool and of unintuitive,
	where you replace threatening wishes and fantasies with their opposites.
So you might express and finally say, "Oh, I love this person. This person is my favorite person."
As a way to mask the fact that you really don't love them at all, in fact, you hate them.

Now, these defense mechanisms proposed by Freud are just everyday life, we have them all the time.
But sometimes, we fail to properly repress the impulses from the id,
	and then you get into some real problems.
You get what Freud called hysteria.
Hysteria according to Freud are these symptoms which showed up quite often in Freud's time
	and maybe show up now only they're manifested in different ways,
		such as blindness and deafness without any physical cause, paralysis, tremblings,
			panic attacks, gaps of memory including amnesia and so on.
For Freud, these are nothing more than symptoms.
They're ways in which we keep our impulses, our memories, our desires under lock and key.
We keep forbidden stuff under lock and key.
The simplest example, for instance, is you had this horrible event, something you did,
	something you saw and you just can't cope with it, so you forget it.
You have a form of amnesia, where you black it out.
Freud believed that when these memories are recovered or when the impulses come to light,
	there's what he called catharsis, an explosive release, an emotional release of insight.
So, then when you're treating these hysterical symptoms,
	you'd want to get to them through ways that could facilitate this catharsis,
		facilitate this understanding.

Freud originally tried to get at this through hypnosis, but later on moved to free association,
	which is a tool that sometimes used.
The idea of free association is you give somebody a word and he says something back,
	but because it's so speeded, they don't have time to censor it.
Ideally, you get the true insight into what's working in their mind
	without the filtering powers that the ego and the super ego have.
So, for instance, a fanciful example is, we're in a session and I say, "Dog," and you say, "Cat,"
	and I say, "Lunch," and you say, "Sandwich," and I say, "Mother," and you say, "Sex."
Well, and then you're embarrassed.
You offer resistance.
You say, "Oh, I didn't mean to say that."
You don't go to your next appointment.
You get angry at the therapist.
This is part of the dance of psychoanalysis.
Freud used these methods and many others to explore inner conflicts,
	and what goes on in psychoanalysis and its success at reading people is a topic
		that we're going to get to at the very end of this course.
#+end_verse
** expression
leak [lik]: n. a small hole that lets liquid or gas flow into or out of something漏洞
jam [dʒæm]: v. BLOCK [intransitive and transitive] (also jam up) if a lot of people or vehicles jam a place, they fill it so that it is difficult to move SYN cram堵塞
target [ˈtɑrɡət]: n. AIM something that you are trying to achieve, such as a total, an amount, or a time SYN goal目标
hatred [ˈheɪtrəd]: n. an angry feeling of extreme dislike for someone or something OPP love憎恨
sublimate [ˈsʌblɪˌmeɪt] sublimation: v.n. technical to use the energy that comes from sexual feelings to do something, such as work or art, that is more acceptable to your society升华
regression [rɪˈɡreʃ(ə)n]: n. technical the act of thinking or behaving as you did at an earlier time of your life, such as when you were a child退化
retreat [rɪˈtrit]: v. ARMY to move away from the enemy after being defeated in battle OPP advance撤退
deaf [def] deafness: adj.n. physically unable to hear anything or unable to hear well ⇨ hearing impaired聋的
amnesia [æmˈniʒə]: n. the medical condition of not being able to remember anything失忆症
catharsis [kəˈθɑrsɪs]: n. formal the act or process of removing strong or violent emotions by expressing them through writing, talking, acting etc(精神或心理)疏泄, 宣泄
facilitate [fəˈsɪləˌteɪt]: v. to make it easier for a process or activity to happen促进
censor [ˈsensər]: v. to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
filter [ˈfɪltər]: v. to remove unwanted substances from water, air etc by passing it through a special substance or piece of equipment过滤
--------------------
be faced with sb./sth.: 面对某人/某事
send up: 发射
act upon sth./sb.: 根据某人/某事行动
spill out: 溢出
be drawn to sb.: 被某人吸引
project A onto B: 讲A投影到B上
for sb's own good: 为某人好
sb. masks the fact that + ...: 某人掩盖事实+...
panic attacks: 恐慌症
(keep sth.) under lock and key: 把某物锁起来
black sth. out: 忘记某事
** sentence
leak [lik]: n. a small hole that lets liquid or gas flow into or out of something漏洞
- I am trying to break down the means of fixing the leak into a few steps.
- The news waft its way towards people in the town that the project has some serious leaks and vulnerable to break into.
- Interpretation of a leak as a feature is a tradition of this software company.
jam [dʒæm]: v. BLOCK [intransitive and transitive] (also jam up) if a lot of people or vehicles jam a place, they fill it so that it is difficult to move SYN cram堵塞
- I did warm you of the traffic jam in rush hours.
- Because of traffic jam, I failed to go on a date with Susan.
- It seems that some meat has jammed between my teeth and I need to floss my teeth right now. 
target [ˈtɑrɡət]: n. AIM something that you are trying to achieve, such as a total, an amount, or a time SYN goal目标
- He tried to figure out his wife's target at bedtime.
- In the first place, the abbot's target wasn't in secular terms.
- If you cupped your hands over your mouth, you'd have realized the target of the operation.
hatred [ˈheɪtrəd]: n. an angry feeling of extreme dislike for someone or something OPP love憎恨
- I am too acclimatized to hatred to hit an innocent boy.
- Due to his hatred towards the pope, he will plan out the explosion to the last detail.
- His hatred towards those so-called experts led to him debunking some myths about the epidemic on the Internet.
sublimate [ˈsʌblɪˌmeɪt] sublimation: v.n. technical to use the energy that comes from sexual feelings to do something, such as work or art, that is more acceptable to your society升华
- In his eyes, the painting in the ceiling is synonymous with his lover and in one sense it's a sublimation.
- Beyond doubt, what his parents taught him sublimated him from time to time.
- It's not only a painting, but rather a sublimation of the artist's soul.
regression [rɪˈɡreʃ(ə)n]: n. technical the act of thinking or behaving as you did at an earlier time of your life, such as when you were a child退化
- While you regard her behaviors as a weakness, I defined it as a regression.
- When you run into regression, it seems that your brain and your mind is empty.
- As long as you become emotional, you have little or no control over your regression when something bad happens.
retreat [rɪˈtrit]: v. ARMY to move away from the enemy after being defeated in battle OPP advance撤退
- It was in a moring in the elementary school that I was so shy to meet my dream girl that I retreated in the crowd.
- His mother interfered with his life to the point of his retreating from his partners.
- If the chess player was separated from the group, I would retreat from it too.
deaf [def] deafness: adj.n. physically unable to hear anything or unable to hear well ⇨ hearing impaired聋的
- The symptom of the disorder sometimes manifested as short-time deafness.
- I admire the doctor for his preoccupations with a deaf old lady who is broke.
- The deaf old lady is quite well friendly and lovely.
amnesia [æmˈniʒə]: n. the medical condition of not being able to remember anything失忆症
- He has been told that his child had been diagnosed with amnesia.
- With amnesia he is hardwired to lead an unusual life.
- The underlying cause of his playing truant from school is his amnesia, so he should be forgiven.
catharsis [kəˈθɑrsɪs]: n. formal the act or process of removing strong or violent emotions by expressing them through writing, talking, acting etc(精神或心理)疏泄, 宣泄
- Everything may return to normal after his catharsis in the hospital.
- She has a habbit of lying to her parents, which is a catharsis for her.
- At last, he decided to turn in his brother who worked for pyramid schemes, which is really a catharsis for him.
facilitate [fəˈsɪləˌteɪt]: v. to make it easier for a process or activity to happen促进
- The computer which I asked my father to present is used to facilitate my English learning.
- The dramatic demographic changes must have facilitated the reordering of the society.
- The pope's temper and the artist's temperament facilitated the creation of the painting, one of the greatest Western art.
censor [ˈsensər]: v. to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
- The entrepreneur complained that his company had lost a great deal of money to censorship.
- The publish of the book is susceptible to censorship.
- The writer is closely related with the fraud, whose writing must be censored.
filter [ˈfɪltər]: v. to remove unwanted substances from water, air etc by passing it through a special substance or piece of equipment过滤
- Filtered information made the fraud likely.
- The presence of the new fraud motivated people to filter information.
- A sudden job loss stopped him from filtering the oil.
--------------------
be faced with sb./sth.: 面对某人/某事
- I am always faced with the economic crises you make.
- I don't dare to be faced with my parents who devote themselves to him after the failure of the examination.
- Obviously, you will be faced with an aging life partner.
send up: 发射
- It doesn't make sense that you are so happy and proud because the shuttle was sent up.
- There was a lot of excitement in the station when the rocket was being sent up.
- When news come to London, everyone was proud that their country is the first to send up a rocket in the world.
act upon sth./sb.: 根据某人/某事行动
- We must act upon our saving, otherwise we couldn't afford the apartment.
- We acted upon the instructions from our leader, thus it's none of our business.
- You can't completely act upon the instructions from your manage, which led to your colleagues' hatred towards you
spill out: 溢出
- You couldn't deny the fact that the oil spilt out last night.
- Because the oil is spilling out, we must ask our superior to send up instructions.
- The memory is spilling out, you must double check the code closely.
be drawn to sb.: 被某人吸引
- I have little or no control over the pretty lady who is drawn to me.
- She claimed to have been drawn to me at the first sight of me. 
- No one could account for the fact that the pretty is drawn to a worker.
project A onto B: 讲A投影到B上
- As long as I project the computer onto the TV, you will enjoy the movie.
- I like to project the website onto the TV whose screen is larger than my computer's.
- Projecting the document onto TV exhausted the boss.
for sb's own good: 为某人好
- My parents are always doing something disgusting for my own good.
- Stop doing such stupid thing for my own good.
- What motivated me to stop you from smoking is for your own good.
sb. masks the fact that + ...: 某人掩盖事实+...
- I masked the fact that I lost two hundreds dollars in the gamble.
- She tried to mask the fact that her husband is mutilated.
- She failed to mask the fact that she had played truant from school.
panic attacks: 恐慌症
- Because of my father's panic attacks, our family used to have a difficult time.
- Sold into the slavery by his friends, he developed panic attacks within the process.
- That's why your child developed panic attacks.
(keep sth.) under lock and key: 把某物锁起来
- It is no use keeping the control under lock and key.
- Shocked by his playing, our father kept the piano under lock and key.
- My father has kept the control under lock and key to stop me from playing video games.
black sth. out: 忘记某事
- I tried to black out the things I experienced in my childhood.
- You can't black out the tune which is in memory of our headmaster.
- He succeeded in blacking out his trauma which had haunted him for a long time.
** sentence2
leak [lik]: n. a small hole that lets liquid or gas flow into or out of something漏洞
- I am trying to break down the means of fixing the leak into a few steps.
- The news waft its way towards people in the town that the project has some serious leaks and vulnerable to break into.
- Interpretation of a leak as a feature is a tradition of this software company.
jam [dʒæm]: v. BLOCK [intransitive and transitive] (also jam up) if a lot of people or vehicles jam a place, they fill it so that it is difficult to move SYN cram堵塞
- I warned you of the traffic jams in rush hours.
- Because of a traffic jam, I failed to go on a date with Susan.
- It seems that some meat has jammed between my teeth and I need to floss my teeth right now. 
target [ˈtɑrɡət]: n. AIM something that you are trying to achieve, such as a total, an amount, or a time SYN goal目标
- He tried to figure out his wife's target at bedtime.
- In the first place, the abbot's target wasn't in secular terms.
- If you cupped your hands over your mouth, you'd have realized the target of the operation.
hatred [ˈheɪtrəd]: n. an angry feeling of extreme dislike for someone or something OPP love憎恨
- I am too acclimatized to hatred to hit an innocent boy.
- Due to his hatred towards the pope, he will plan out the explosion to the last detail.
- His hatred towards those so-called experts led to him debunking some myths about the epidemic on the Internet.
sublimate [ˈsʌblɪˌmeɪt] sublimation: v.n. technical to use the energy that comes from sexual feelings to do something, such as work or art, that is more acceptable to your society升华
- In his eyes, the painting on the ceiling is synonymous with his lover and in one sense it's a sublimation.
- Beyond doubt, what his parents taught him sublimated him from time to time.
- It's not only a painting but rather a sublimation of the artist's soul.
regression [rɪˈɡreʃ(ə)n]: n. technical the act of thinking or behaving as you did at an earlier time of your life, such as when you were a child退化
- While you regard her behaviors as a weakness, I defined it as a regression.
- When you run into regression, it seems that your brain and your minds are empty.
- As long as you become emotional, you have little or no control over your regression when something bad happens.
retreat [rɪˈtrit]: v. ARMY to move away from the enemy after being defeated in battle OPP advance撤退
- It was in the morning at the elementary school that I was so shy to meet my dream girl that I retreated into the crowd.
- His mother interfered with his life to the point of his retreating from his partners.
- If the chess player was separated from the group, I would retreat from it too.
deaf [def] deafness: adj.n. physically unable to hear anything or unable to hear well ⇨ hearing impaired聋的
- The symptom of the disorder sometimes manifested as short-time deafness.
- I admire the doctor for his preoccupations with a deaf old lady who is broke.
- The deaf old lady is quite well friendly and lovely.
amnesia [æmˈniʒə]: n. the medical condition of not being able to remember anything失忆症
- He has been told that his child had been diagnosed with amnesia.
- With amnesia, he is hardwired to lead an unusual life.
- The underlying cause of his playing truant from school is his amnesia, so he should be forgiven.
catharsis [kəˈθɑrsɪs]: n. formal the act or process of removing strong or violent emotions by expressing them through writing, talking, acting etc(精神或心理)疏泄, 宣泄
- Everything may return to normal after his catharsis in the hospital.
- She has a habit of lying to her parents, which is a catharsis for her.
- At last, he decided to turn in his brother who worked in pyramid schemes, which is really a catharsis for him.
facilitate [fəˈsɪləˌteɪt]: v. to make it easier for a process or activity to happen促进
- The computer which I asked my father to present is used to facilitate my English learning.
- The dramatic demographic changes must have facilitated the reordering of the society.
- The pope's temper and the artist's temperament facilitated the creation of the painting, one of the greatest Western art.
censor [ˈsensər]: v. to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
- The entrepreneur complained that his company had lost a great deal of money to censorship.
- The publishing of the book is susceptible to censorship.
- The writer is closely related to the fraud, whose writing must be censored.
filter [ˈfɪltər]: v. to remove unwanted substances from water, air etc by passing it through a special substance or piece of equipment过滤
- Filtered information made the fraud likely.
- The presence of the new fraud motivated people to filter information.
- A sudden job loss stopped him from filtering the oil.
--------------------
be faced with sb./sth.: 面对某人/某事
- I am always faced with the economic crises you make.
- I don't dare to be faced with my parents who devote themselves to him after the failure of the examination.
- Obviously, you will be faced with an aging life partner.
send up: 发射
- It doesn't make sense that you are so happy and proud because the shuttle was sent up.
- There was a lot of excitement in the station when the rocket was being sent up.
- When news came to London, everyone was proud that their country was the first to send up a rocket in the world.
act upon sth./sb.: 根据某人/某事行动
- We must act upon our savings, otherwise, we couldn't afford the apartment.
- We acted upon the instructions from our leader, thus it's none of our business.
- You can't completely act upon the instructions from your manager, which led to your colleagues' hatred towards you
spill out: 溢出
- You couldn't deny the fact that the oil spilled out last night.
- Because the oil is spilling out, we must ask our superior to send up instructions.
- The memory is spilling out, you must double-check the code closely.
be drawn to sb.: 被某人吸引
- I have little or no control over the pretty lady who is drawn to me.
- She claimed to have been drawn to me at the first sight of me. 
- No one could account for the fact that the pretty is drawn to a worker.
project A onto B: 讲A投影到B上
- As long as I project the computer onto the TV, you will enjoy the movie.
- I like to project the website onto the TV whose screen is larger than my computer's.
- Projecting the document onto TV exhausted the boss.
for sb's own good: 为某人好
- My parents are always doing something disgusting for my own good.
- Stop doing such stupid things for your own good.
- What motivated me to stop you from smoking is for your own good.
sb. masks the fact that + ...: 某人掩盖事实+...
- I masked the fact that I lost two hundred dollars in the gamble.
- She tried to mask the fact that her husband is mutilated.
- She failed to mask the fact that she had played truant from school.
panic attacks: 恐慌症
- Because of my father's panic attacks, our family used to have a difficult time.
- Sold into slavery by his friends, he developed panic attacks during the process.
- That's why your child developed panic attacks.
(keep sth.) under lock and key: 把某物锁起来
- It is no use keeping the control under lock and key.
- Shocked by his playing, our father kept the piano under lock and key.
- My father has kept the control under lock and key to stop me from playing video games.
black sth. out: 忘记某事
- I tried to black out the things I experienced in my childhood.
- You can't black out the tune which is in memory of our headmaster.
- He succeeded in blacking out his trauma which had haunted him for a long time.
