#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L02 Thirteen equals one
#+begin_verse
Was the vicar pleased that the clock was striking? Why?

Our vicar is always raising money for one cause or another,
	but he has never managed to get enough money to have the church clock repaired.
The big clock which used to strike the hours day and night
	was damaged many years ago and has been silent ever since.

One night, however, our vicar woke up with a start:
	the clock was striking the hours!
Looking at his watch, he saw that it was one o'clock,
	but the bell struck thirteen times before it stopped.
Armed wit a torch, the vicar went up into the clock tower to see what was going on.
In the torchlight, he caught sight of a figure
	whom he immediately recognized as Bill Wilkins, our local grocer.

'Whatever are you doing up here Bill?' asked the vicar in surprise.

'I'm trying to repair the bell,' answered Bill.
'I've been coming up here night after night for weeks now.
You see, I was hoping to give you a surprise.'

'You certainly did give me a surprise!' said the vicar.
'You've probably woken up everyone in the village as well.
Still, I'm glad the bell is working again.'

'That's the trouble, vicar,' answered Bill.
'It's working all right, but I'm afraid that at one o'clock
	it will strike thirteen times and there's nothing I can do about it.'

'We'll get used to that, Bill,' said the vicar.
'Thirteen is not as good as one, but it's better than nothing.
Now let's go downstairs and have a cup of tea.'
#+end_verse

** works
equal [ˈiːkwəl] v.等于
vicar [ˈvɪkə(r)] n.牧师
raise [reɪz] v.募集,筹(款)
torchlight [ˈtɔːtʃlaɪt] n.电筒光

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
