#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 03 An unknown goddess
#+begin_verse
How did the archaeologists know that the statue was a goddess?

Some time ago, *an interesting discovery was made* by archaeologists on the Aegean island of Kea.
An American team explored a temple
	which stands in an ancient city *on the promontory* of Ayia Irini.
The city at one time must have been prosperous,
	for it enjoyed a high level of civilization.
Houses -- often three storeys high -- were built of stone.
They had large rooms with beautifully decorated walls.
The city *was even equipped with* a *drainage system*,
	for a great many clay pipes were found beneath the narrow streets.

The temple which the archaeologists explored *was used as a place of worship*
	from the fifteenth century B.C. until Roman times.
In the most sacred room of the temple, clay fragments of fifteen statues were found.
Each of these represented a goddess and had, at one time, been painted.
The body of one statue was found among remains dating from the fifteen century B.C.
Its missing head *happened to be* among remains of the fifth century B.C.
This head must have been found in Classical times and carefully preserved.
It was very old and precious even then.
When the archaeologists reconstructed the fragments,
	they *were amazed to find that* the goddess *turned out be* a very modern-looking woman.
She stood three feet high and her hands rested on her hips.
She was wearing a full-length skirt which swept the ground.
*Despite her great age*, she was very graceful indeed,
	but, so far, the archaeologists have been unable to discover her identity.
#+end_verse

** words
goddness  n. 女神
archaeologist [ˌɑːkiˈɒlədʒɪst] n. 考古学家
Aegean [i:'dʒi:ən] adj. 爱琴海的
explore [ɪkˈsplɔː(r)] v. 考察
promontory [ˈprɒməntri] n. 海角
prosperous [ˈprɒspərəs] adj. 繁荣
civilization [ˌsɪvəlaɪˈzeɪʃ(ə)n] n. 文明
storey [ˈstɔːri] n. 楼层
drainage [ˈdreɪnɪdʒ] n. 排水
worship [ˈwɜːʃɪp] n. 崇拜
sacred [ˈseɪkrɪd] adj. 宗教的
fragment [ˈfræɡmənt] n. 碎片
remains [rɪˈmeɪnz] n. 碎片
classical [ˈklæsɪk(ə)l] adj. 古文明的
reconstruct [ˌriːkənˈstrʌkt] v. 修复
rest [rest] v. 倚放
hip [hɪp] n. 屁股
full-length adj. 拖地长的
graceful [ˈɡreɪsf(ə)l] adj. 优雅的
identity [aɪˈdentəti] n. 身份

** DONE 单词造句
CLOSED: [2023-10-23 Mon 22:35]
un...
goddess n. god
1. I never dreamed of dancing with my goddess.
2. I look forward to meeting a goddess.
3. Is Athena the Greek goddess of wisdom and war?
4. The goddess was charming at her first party.
5. All young woman in our town dream of being a Hollywood goddess.
archaeologist n. archaeology n.
1. I'm glad that the archaeologist is not talking about the Greek goddess any more.
2. These archaeologists get used to flying off course.
3. These archaeologists were equipped with the new guns.
4. These archaeologists were asked to wear helmets before they went into the cave.
5. I recognized him as an archaeologist who makes an interesting discovery recently.
Aegean adj.
explore v. explorer n. exploration n.
1. This archaeologist often risks his life to explore these caves.
2. The archaeologist is always exploring the valcanoes for one cause or another.
3. These explorers claimed to have seen a puma on the promontory.
4. These explorers were trapped in a gold mine.
5. These explorers convinced that there were a lot of pirates.
promontory n. on a/the promontory
1. It is disturbing to think that your wife always wants to visit the promontory.
2. The puma left a trail of dead on the promontory.
3. I spotted him making a proposal to his girl friend on the promontory.
4. These archaeology is talking about the history of the palace on the promontory.
5. A comedy show will be held on the promontory next night.
prosperous adj.
1. Don't live in a fantasy world. It's not a prosperous city.
2. I am reluctant to move to a prosperous city.
3. The city is popular with young men these days, it gets prosperous.
4. The country can't be prosperous.
5. What a prosperous city!
civilization n.
1. How did it enjoy a high level of civilization?
2. As it is, Chinese civilization is not the oldest in the world.
3. Chinese civilization turns out to be the oldest in the world.
4. Instead of modern civilizations, the team is insteret in ancient civilizations. 
5. China used to enjoy a high level of civilization? Are you being sarcastic?
storey n. story
1. We moved to a house which has four stories.
2. I used to live on the top story.
3. He claimed to live on the top story on Wall Street.
4. It is said that living on the top story will have a good luck.
5. The man on the top story is spying on him for two days.
drainage n. drainage system
1. The worker claimed to have repaired the drainage system.
2. The cat has been trapped in the drainage system for two days.
3. The floods cause these little animals to repair drainage system. 
4. On the surface, he is an expert at repairing drainage system.
5. Well, she succeed in removing the pipe from drainage system.
worship n.v. a is/was used as a place of worship
1. This room used to be used as a place of worship.
2. On the surface, he worships God.
3. My mother often spends two hours worshiping the god once a week.
4. I hate to workship any god or goddess since I was very young.
5. The archaeologist pointed out that this palace was used as a place of worship.
sacred adj. sacred room/temple/place
1. For one reason or another, the sacred temple has been burnt down many years ago.
2. The vicar often has a rest in the sacred room.
3. The sacred room was used as a place of worship.
4. Why is the cow a sacred man in India?
5. The most sacred room is full of candles.
fragment n.
1. The vicar has managed to get enough money to have the fragments reconstructed.
2. The archaeologists found fragments of statues in the courtyard.
3. The archaeologist found some fragments of tones underwater.
4. The archaelogist is equal to reconstruct the fragments of the goddess.
5. I caught sight of fragments of body in his room. 
remains n.
1. We'll have to visit the remains of the temple.
2. The archaeologist happened to find the remains of an ancient city.
3. These archaeologists convinced that this was the remains of an ancient civilization.
4. It occured to me that this must be the remains of an ancient city.
5. This may be the remains of the place of worship.
classical adj.
1. Why don't we listen to some classical music?
2. I find my daughter studying classical art.
3. I felt obliged to learn some classical music.
4. She said she prefers to study classical art than modern.
5. This classical music sounds good.
reconstruct v. re...
1. The archaeologist failed to reconstruct the fragments of Roman vase.
2. The authorities rufused to reconstruct these broken building.
3. Despite the fact that the city was destoryed during the war, it has been reconstructed soon.
4. The archaeologist gets used to reconstructing fragments of a statu.
5. The archaeologist returned China the fragments of vase.
rest n.v. hip n. have a rest
1. My wife is always resting her head on my shoulder on the bed.
2. I always rests my hands on my wife's hip when I am fast sleep.
3. At the edge of a forest, I spotted a man a resting his hands on another's hips.
4. Although he had a rest, he is still out of breath.
5. You put your hands on your hips, didn't you?
full-length adj.
1. She has trouble in wearing a full-length dress at the party.
2. She watched a musical wearing a full-length dress.
3. She is busy wearing a full-length dress.
4. Will you be wearing a full-length dress?
5. Why don't you wear a full-length dress?
graceful adj.
1. The woman who is dancing with my wife is graceful.
2. To be honest, she is not as graceful as a swan.
3. She was so graceful last night that everyone wanted to dance with her.
4. She was so graceful last night that I regreted not taking part in the party.
5. She was so graceful last night that she became a Hollywoord goddess.
identity n. identity card
1. I regreted losing my identity card.
2. Show me your identity or get out of here.
3. He was disappointed to learn that the police hasn't discovered her identity.
4. I proved that this was my identity card indeed.
5. Will you be carrying my identity card?
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
sb. make a (adj.) discovery of sth.
1. 
2. 
3. 
4. 
5. 
a. be equipped with b.
1. 
2. 
3. 
4. 
5. 
equip sb. with sth.
1. 
2. 
3. 
4. 
5. 
be used as
1. 
2. 
3. 
4. 
5. 
date from ... date back to ...
1. 
2. 
3. 
4. 
5. 
happen to do
1. 
2. 
3. 
4. 
5. 
be amazed to find that + ...
1. 
2. 
3. 
4. 
5. 
turn out to be ...
1. 
2. 
3. 
4. 
5. 
despite/despite the fact that ...
1. 
2. 
3. 
4. 
5. 
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
