#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 03 An unknown goddess
#+begin_verse
How did the archaeologists know that the statue was a goddess?

Some time ago, an interesting discovery was made by archaeologists on the Aegean island of Kea.
An American team explored a temple
	which stands in an ancient city on the promontory of Ayia Irini.
The city at one time must have been prosperous,
	for it enjoyed a high level of civilization.
Houses -- often three storeys high -- were built of stone.
They had large rooms with beautifully decorated walls.
The city was even equipped with a drainage system,
	for a great many clay pipes were found beneath the narrow streets.

The temple which the archaeologists explored was used as a place of worship
	from the fifteenth century B.C. until Roman times.
In the most sacred room of the temple, clay fragments of fifteen statues were found.
Each of these represented a goddess and had, at one time, been painted.
The body of one statue was found among remains dating from the fifteen century B.C.
Its missing head happened to be among remains of the fifth century B.C.
This head must have been found in Classical times and carefully preserved.
It was very old and precious even then.
When the archaeologists reconstructed the fragments,
	they were amazed to find that the goddess turned out be a very modern-looking woman.
She stood three feet high and her hands rested on her hips.
She was wearing a full-length skirt which swept the ground.
Despite her great age, she was very graceful indeed,
	but, so far, the archaeologists have been unable to discover her identity.
#+end_verse

** words
goddness  n. 女神
archaeologist [ˌɑːkiˈɒlədʒɪst] n. 考古学家
Aegean [i:'dʒi:ən] adj. 爱琴海的
explore [ɪkˈsplɔː(r)] v. 考察
promontory [ˈprɒməntri] n. 海角
prosperous [ˈprɒspərəs] adj. 繁荣
civilization [ˌsɪvəlaɪˈzeɪʃ(ə)n] n. 文明
storey [ˈstɔːri] n. 楼层
drainage [ˈdreɪnɪdʒ] n. 排水
worship [ˈwɜːʃɪp] n. 崇拜
sacred [ˈseɪkrɪd] adj. 宗教的
fragment [ˈfræɡmənt] n. 碎片
remains [rɪˈmeɪnz] n. 碎片
classical [ˈklæsɪk(ə)l] adj. 古文明的
reconstruct [ˌriːkənˈstrʌkt] v. 修复
rest [rest] v. 倚放
hip [hɪp] n. 屁股
full-length adj. 拖地长的
graceful [ˈɡreɪsf(ə)l] adj. 优雅的
identity [aɪˈdentəti] n. 身份

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
