#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L04 The double life of Alfred Bloggs
#+begin_verse
Why did Alf want a while-collar job?

These days, people who do manual work often receive far more money than people who work in offices.
People who work in offices
	are frequently referred to as 'white-collar workers' for the simple reason
	that they usually wear a collar and tie to go to work.
Such is human nature, that a great many people are often willing to
		sacrifice higher pay for the privilege of becoming white-collar workers.
This can give rise to curious situations,
	as it did in the case of Alfred Bloggs who worked as a dustman for the Ellesmere Corporation.

When he got married, Alf was too embassrassed to say anything to his wife about his job.
He simply told her that her worked for the Corporation.
Every morning, he left home dressed in a smart black suit.
#+end_verse

** words
manual [ˈmænjuəl] adj. 体力的
collar [ˈkɒlə(r)] n. 衣领
sacrifice [ˈsækrɪfaɪs] v. 牺牲
privilege [ˈprɪvəlɪdʒ] n. 好处
dustman [ˈdʌstmən] n. 清洁工
corporation [ˌkɔːpəˈreɪʃ(ə)n] n. 公司
overalls [ˈəʊvərɔːlz] n. 淋浴
shower [ˈʃaʊə(r)] n. 淋浴
secret [ˈsiːkrət] n. 秘密
status [ˈsteɪtəs] n. 地位
