#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 04 The double life of Alfred Bloggs
#+begin_verse
Why did Alf want a while-collar job?

*These days*,
	people who *do manual work* often receive *far more* money than people who work in offices.
People who work in offices
	*are frequently referred to as* '*white-collar workers*' *for the simple reason*
		that they usually wear a collar and tie to go to work.
*Such is human nature,*
	that a great many people *are often willing to sacrifice higher pay*
		for the privilege of becoming white-collar workers.
This can *give rise to* curious situations,
	as it did in the case of Alfred Bloggs who worked as a dustman for the Ellesmere Corporation.

When he got married, Alf *was too embarrassed to* say anything to his wife about his job.
He simply told her that he worked for the Corporation.
Every morning, he left home *dressed in* a smart black suit.
He then *changed into* overalls and spent the next eight hours as a dustman.
Before returning home at night, he *took a shower* and changed back into his suit.
Alf did this for over two years and his fellow dustmen kept his secret.
Alf's wife has never discovered that she married a dustman and she never will,
	for Alf has just found another job.
He will soon be working in an office.
He will be earning only *half as much as* he used to,
	but he feels that his rise in status is well worth the loss of money.
*From now on*, he will wear a suit all day and others will *call him Mr. Bloggs*, not Alf.
#+end_verse

** words
manual [ˈmænjuəl] adj. 体力的
collar [ˈkɒlə(r)] n. 衣领
sacrifice [ˈsækrɪfaɪs] v. 牺牲
privilege [ˈprɪvəlɪdʒ] n. 好处
dustman [ˈdʌstmən] n. 清洁工
corporation [ˌkɔːpəˈreɪʃ(ə)n] n. 公司
overalls [ˈəʊvərɔːlz] n. 淋浴
shower [ˈʃaʊə(r)] n. 淋浴
secret [ˈsiːkrət] n. 秘密
status [ˈsteɪtəs] n. 地位

** 单词造句
manual adj. n.  do manual work
1. 
2. 
3. 
4. 
5. 
collar n. white-collar/blue-collar workers
1. 
2. 
3. 
4. 
5. 
sacrifice v. n. make a sacrifice  sacrifice a. for b.
1. 
2. 
3. 
4. 
5. 
privilege n. have the privilege of doing sth.
1. 
2. 
3. 
4. 
5. 
dustman n.
1. 
2. 
3. 
4. 
5. 
corporation n.
1. 
2. 
3. 
4. 
5. 
overalls n.
1. 
2. 
3. 
4. 
5. 
shower n. take a shower
1. 
2. 
3. 
4. 
5. 
secret n. keep a secret  the secret of success  It's between you and me
1. 
2. 
3. 
4. 
5. 
status n. social status  status quo  keep the status quo
1. 
2. 
3. 
4. 
5. 
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
These days...
1. 
2. 
3. 
4. 
5. 
Far more adj./n.
1. 
2. 
3. 
4. 
5. 
a. be referred to as ... b.
1. 
2. 
3. 
4. 
5. 
refer to a. as b.
1. 
2. 
3. 
4. 
5. 
for the simple reason that + ...
1. 
2. 
3. 
4. 
5. 
Such is human nature, that + ...
1. 
2. 
3. 
4. 
5. 
be willing to do sth.
1. 
2. 
3. 
4. 
5. 
give rise to = lead to = cause
1. 
2. 
3. 
4. 
5. 
too embarrassed to do sth.
1. 
2. 
3. 
4. 
5. 
be dressed in
1. 
2. 
3. 
4. 
5. 
change into + [clothes]
1. 
2. 
3. 
4. 
5. 
half as much as ...
1. 
2. 
3. 
4. 
5. 
from now on
1. 
2. 
3. 
4. 
5. 
call me/him/her a.
1. 
2. 
3. 
4. 
5. 
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion

