#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 05 The facts
#+begin_verse
What was the consequence of the editor's insistence on facts and statistics?

Editors of newspapers and magazines often *go to extremes*
	to *provide their readers with* unimportant facts and statistics.
Last year a journalist had *been instructed by* a well-known magazine
	to *write an article on* the president's palace in a new African republic.
When the article arrived, the editor read the first sentence and then refused to publish it.
The article began: 'Hundreds of steps lead to the high wall which surrounds the president's palace.'
The editor at once sent the journalist a fax
	instructing him to *find out* the exact number of steps and the height of the wall.

The journalist immediately set out to obtain these important facts,
	but he *took a long time to send* them.
Meanwhile, the editor was *getting impatient*, for the magazine would soon *go to press*.
He sent the journalist two more faxes, but received no reply.
He sent yet another fax informing the journalist that if he did not reply soon he would *be fired*.
When the journalist again failed to reply,
	the editor reluctantly *published the article* as it had originally been written.
A week later, the editor at last received a fax from the journalist.
Not only had the poor man been arrested, but he had been sent to prison as well.
However, he had at last been allowed to *send a fax*
	in which he *informed the editor*
		that he had been arrested
			while counting the 1084 steps leading to the fifteen-foot wall
				which surrounded the president's palace.
#+end_verse

** words
editor [ˈedɪtər] n．编辑
extreme [ɪkˈstrim] n．极端
statistics [stə'tɪstɪks] n．统计数字
journalist [ˈdʒɜrn(ə)lɪst] n．新闻记者
president [ˈprezɪdənt] n．总统
palace [ˈpæləs] n．王宫；宏伟的住宅
publish [ˈpʌblɪʃ] v．出版
fax [fæks] n．传真
impatient [ɪmˈpeɪʃ(ə)nt] adj. 不耐烦的
fire [faɪr] v．解雇
originally [əˈrɪdʒən(ə)li] adv．起初，原先，从前

** 单词造句
editor n. edit v.
1. May I have the privilege of meeting the editor?
2. The editor usually calls me Sherwin.
3. Today, the CEO have the editor posted to a remote village.
4. The editor got so angry that he refused to publish the article.
5. The editor was instructed in publishing it soon.
extreme n.  go to extreme(s) to do sth.
1. The girl is making every effort to go to extremes.
2. He is always going to extremes to do every task.
3. Even if you went to extremes to make money, you wouldn't be happy.
4. People often go to extremes to keep status quo.
5. Because of his taking work seriously, he often goes to extremes.
statistics n. statistic
1. To the authorities, I am just another statistic.
2. The statistics suggest that she often goes home by bus.
3. The statistics suggest that he couldn't afford the house.
4. The statistics suggest that there are more people being fired than last year.
5. The statistics suggest that people who work in office earn only half much as they used to.
journalist n.
1. The journalist was too embarrassed to tell anything about the palace to his editor.
2. This can give rise to curious situation, as it did in the case of the journalist
	  who was sent to prison.
3. The journalist often goes to extreme to figure out the facts and statistics.
4. The book which was publish yesterday was edited by the journalist.
5. The journalist feels that his rise in status is well worth the loss of money.
president n.
1. The president changed into suit for the simple reason that he likes it.
2. The president was willing to tell stories.
3. The president was refered to as the grest man in American.
4. The president goes to extremes to keep the status quo.
5. 'Status quo.' The president ordered his men to do nothing.
palace n.
1. There are 1094 steps which leads to the wall which surrounds the palace.
2. The palace was burnt down for one reason or another.
3. From now on, people can visit the palace at liberty. 
4. Despite the fact that the palace was fired in 1989.
5. In the most sacred room of the palace, they found the fragments of fifteen statuses.
publish v.  publish + a book/an article/report
1. The journalist was amazed to find that his report had been published.
2. We're publishing the report in an hour.
3. The editor may have published the article already.
4. The editor can't have published the article.
5. The editor must have published the article.
fax n.v.  send sb. a fax
1. I'll send you a fax. Let's keep in touch with each other.
2. He has sent me a fax in which he told me his wife was pregnant.
3. I was too embarrased to send him any fax.
4. He has sent faxs hald as many as you.
5. From now on, it's easy for us to send anyone a fax in office.
impatient adj.  get impatient
1. The secret of success is don't get impatient.
2. In the end, the flight attendant got so impatinent that she lost her temper.
3. Don't be impatient and everything will soon return to normal.
4. Don't be impatient. Let's make it official.
5. You got so impatient that you didn't double check the garage.
fire v.  get/be fired
1. I regret to inform you that you're fired.
2. I was disappointed to learn that I got fired.
3. When the news came to me that I am fired, I bursted out tears.
4. No one could account for the fact that she got fired.
5. You are responsible for this failure, so you get fired.
originally adv.
1. I was wonder who lived there originally.
2. I have difficulty in finding out where she is from originally.
3. This sort of snake is found in America originally.
4. The palace was originally designed by the artiste, Mr. Sherwin.
5. That stupid remark was originally made by the journalist.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until
** 习惯用法造句
provide sb. with sth.
1. 
2. 
3. 
4. 
5. 
sb. be instructed to do sth.
1. 
2. 
3. 
4. 
5. 
instruct sb. to do sth.
1. 
2. 
3. 
4. 
5. 
write an article on/about sth.
1. 
2. 
3. 
4. 
5. 
find out sth.
1. 
2. 
3. 
4. 
5. 
sb. take a long time to do sth.
1. 
2. 
3. 
4. 
5. 
go to press
1. 
2. 
3. 
4. 
5. 
inform sb. that + ...
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
