#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L05 The facts
#+begin_verse
What was the consequence of the editor's insistence on facts and statistics?

Editors of newspapers and magazines often go to extremes
	to provide their readers with unimportant facts and statistics.
Last year a journalist had been instructed by a well-known magazine
	to write an article on the president's palace in a new African republic.
When the article arrived, the editor read the first sentence and then refused to publish it.
The article began: 'Hundreds of steps lead to the high wall which surrounds the president's palace.'
The editor at once sent the journalist a fax
	instructing him to find out the exact number of steps and the height of the wall.

The journalist immediately set out to obtain these important facts,
	but he took a long time to send them.
Meanwhile, the editor was getting impatient, for the magazine would soon go to press.
He sent the journalist two more faxes, but received no reply.
He sent yet another fax informing the journalist
	that if he did not reply soon he would be fired.
When the journalist again failed to reply,
	the editor reluctantly published the article as it had originally been written.
A week later, the editor at last received a fax from the journalist.
Not only had the poor man been arrested, but he had been sent to prison as well.
However, he had at last been allowed to send a fax
	in which he informed the editor
		that he had been arrested
			while counting the 1084 steps leading to the fifteen-foot wall
				which surrounded the president's palace.
#+end_verse

** words
editor [ˈedɪtər] n．编辑
extreme [ɪkˈstrim] n．极端
statistics [stə'tɪstɪks] n．统计数字
journalist [ˈdʒɜrn(ə)lɪst] n．新闻记者
president [ˈprezɪdənt] n．总统
palace [ˈpæləs] n．王宫；宏伟的住宅
publish [ˈpʌblɪʃ] v．出版
fax [fæks] n．传真
impatient [ɪmˈpeɪʃ(ə)nt] adj. 不耐烦的
fire [faɪr] v．解雇
originally [əˈrɪdʒən(ə)li] adv．起初，原先，从前

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
