#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L06 Smash-and-grab
#+begin_verse
How did Mr. Taylor try to stop the thieves?

The expensive shops in a famous arcade near Piccadilly were just opening.
At this time of morning, the arcade was almost empty.
Mr. Taylor, the owner of a jewellery shop was admiring a new window display.
Two of his assistants had been working busily since eight o'clock and had only just finished.
Diamond necklaces and rings had been beautifully arranged on a background of black velvet.
After gazing at the display for several minutes, Mr. Taylor went back into his shop.

The silence was suddenly broken
	when a large car, with its headlights and its horn blaring, roared down the arcade.
It came to a stop outside the jeweller's.
One man stayed at the wheel while two others with black
	stockings over their faces jumped out and smashed the window of the shop with iron bars.
While this was going on, Mr. Taylor was upstairs.
He and his staff began throwing furniture out of the window.
Chairs and tables went flying into the arcade.
One of the thieves was struck by a heavy statue,
	but he was too busy helping himself to diamonds to notice any pain.
The raid was all over in three minutes,
	for the men scrambled back into the car
	and it moved off at a fantastic speed.
Just as it was leaving,
	Mr. Taylor rushed out and ran after it throwing ashtrays and vases,
	but it was impossible to stop the thieves.
They had got away with thousands of pounds worth of diamonds.
#+end_verse

** words
smash-and-grab [smæʃ-ənd-'ɡræb] n. 砸橱窗抢劫
arcade [ɑːˈkeɪd] n. 有拱廊的街道
Piccadilly [ˌpɪkəˈdɪli] n. 皮卡迪利大街
jewellery [ˈdʒuːəlri] n. 珠宝
necklace [ˈnekləs] n. 项链
ring [rɪŋ] n. 戒指
background [ˈbækɡraʊnd] n. 背景
velvet [ˈvelvɪt] n. 天鹅绒
headlight [ˈhedlaɪt] n. 前灯
blare [bleə(r)] v. 嘟嘟声
staff [stɑːf] n. 全体工作人员
raid [reɪd] n. 偷袭
scramble [ˈskræmb(ə)l] v. 爬行
fantastic [fænˈtæstɪk] adj. 非常大的
ashtray [ˈæʃtreɪ] n. 烟灰缸

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
