#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 07 Mutilated ladies
#+begin_verse
Why did Jane cook John's wallet?

Has it ever happened to you?
Have you ever put your trousers in the washing machine
	and then remembered there was a large bank note in your back pocket?
When you rescued your trousers, did you find the note was whiter than white?
People who live in Britain needn't despair
	when they make mistakes like this (and a lot of people do)!
Fortunately for them, the Bank of England has a team
	called Mutilated Ladies which deals with claims from people
		who fed their money to a machine or to their dogs.
Dogs, it seems, love to chew up money!

A recent case concerns Jane Butlin whose fiance, John, runs a successful furniture business.
John had a very good day
	and put his wallet containing 3000 dollars into the microwave oven for safekeeping.
Then he and Jane went horse-riding.
When they got home, Jane cooked their dinner in the microwave oven and without realizing it,
	cooked her fiance's wallet as well.
Imagine their dismay when they found a beautifully-cooked wallet and notes turned to ash!
John went to see his bank manager who sent the remains of wallet
	and the money to the special department of the Bank of England in Newcastle: the Mutilated Ladies!
They examined the remains and John got all his money back.
'So long as there's something to identify, we will give people their money back,'
	said a spokeswoman for the Bank,
'Last year, we paid 1.5 million dollars on 21,000 claims.'
#+end_verse

** words
mutilate [ˈmjuːtɪleɪt] v. 使残缺不全
chew [tʃuː] v. 咀嚼
fiance [fiˈɒnseɪ; fiˈɑːnseɪ] n. 未婚夫
microwave [ˈmaɪkrəweɪv] n. 微波
oven [ˈʌv(ə)n] n. 炉灶
safekeeping [ˌseɪfˈkiːpɪŋ] n. 妥善保管
Newcastle [ˈnjuːkɑːsl] n. 纽卡斯尔
identify [aɪˈdentɪfaɪ] v. 鉴别
spokeswoman [ˈspəʊkswʊmən] n. 女发言人

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
