#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 07 Mutilated ladies
#+begin_verse
Why did Jane cook John's wallet?

Has it ever happened to you?
Have you ever put your trousers in the washing machine
	and then remembered there was a large bank note in your back pocket?
When you rescued your trousers, did you find the note was whiter than white?
People who live in Britain needn't despair
	when they make mistakes like this (and a lot of people do)!
Fortunately for them, the Bank of England has a team
	called Mutilated Ladies which *deals with* claims from people
		who fed their money to a machine or to their dogs.
Dogs, it seems, love to chew up money!

A recent case concerns Jane Butlin whose fiance, John, runs a successful furniture business.
John had a very good day
	and put his wallet containing 3000 dollars into the microwave oven *for safekeeping*.
Then he and Jane *went horse-riding*.
When they got home, Jane cooked their dinner in the microwave oven and without realizing it,
	cooked her fiance's wallet as well.
*Imagine their dismay when* they found a beautifully-cooked wallet and notes turned to ash!
John went to see his bank manager who sent the remains of wallet
	and the money to the special department of the Bank of England in Newcastle: the Mutilated Ladies!
They examined the remains and John got all his money back.
'*So long as* there's something to identify, we will give people their money back,'
	said a spokeswoman for the Bank,
'Last year, we paid 1.5 million dollars on 21,000 claims.'
#+end_verse

** words
mutilate [ˈmjuːtɪleɪt] v. 使残缺不全
chew [tʃuː] v. 咀嚼
fiance [fiˈɒnseɪ; fiˈɑːnseɪ] n. 未婚夫
microwave [ˈmaɪkrəweɪv] n. 微波
oven [ˈʌv(ə)n] n. 炉灶
safekeeping [ˌseɪfˈkiːpɪŋ] n. 妥善保管
Newcastle [ˈnjuːkɑːsl] n. 纽卡斯尔
identify [aɪˈdentɪfaɪ] v. 鉴别
spokeswoman [ˈspəʊkswʊmən] n. 女发言人

** DONE 单词造句
CLOSED: [2023-10-30 Mon 21:27]
mutilate v.
1. The prisoner was mutilated, for he has been tortured before.
2. He ran into serious trouble and was mutilated in the accident.
3. Mutilated ladies is an organization which recoginzed mutilated bank notes.
4. I regreted to inform you that your left leg was mutilated in the plane crash.
5. The pilot was disappointed to learn that his leg was mutilated in the place crash.
chew v. chew up  chewing gum
1. Are you chewing chocolate? My wife said with a sneer.
2. I haven't chew gum hald as much as you.
3. From now on, I quit chewing gum.
4. I promise that I will grab some chewing gum for you.
5. She was reluctant to chew up the rice. 
fiance n.
1. His fiance was too embarrassed to say hello to her when they met at the first time.
2. My fiance is going to write an article about ancient Greek rings.
3. His fiance called him baby.
4. At last, his fiance got impatient and left her alone at the airport.
5. Not only have I had my hair cut, but my fiance as well.
microwave n.
1. He has sold ten thousands of dollars worth microwaves.
2. He sent his customer a fax informing that the microwaves were sold out.
3. Despite the fact that he gets used to selling microwaves.
4. He went to extremes to get a free microwave from the market.
5. She is making a discovery of the microwave.
oven n.
1. If we buy the oven, we will have delicious roast duck tonight.
2. The moment the cat touched the oven, she scrambled back into her box.
3. He was amazed to find that her wife had already bought an oven.
4. He claimed that this oven can date back to his childhood.
5. In her youth, she always recognized an oven as an microwave.
safekeeping n.  for safekeeping
1. The authorities are always instructing people to do a lot of work for safekeeping.
2. You should have closed the door for safekeeping yesterday.
3. I'm glad that these detectives are waitting for safety at the airport.
4. The archaeologist refused to explore the ancient caves for safekeeping.
5. I felt obliged to give all my money to my wife for safekeeping.
identify v.
1. The security wasn't able to identify his boss and made a spectacle of himself.
2. The policeman is accustomed to identifing thieves.
3. They competed against each other to identify the photos of someone.
4. If you weren't identified, they wouldn't stand to attention.
5. Don't take that tone with me. Have you ever identified me?
spokeswoman n.
1. The spokeswoman claimed to have seen the soldiers.
2. After entiring, the spokeswoman devoted herself to garden.
3. The spokeswoman claimed that someone fired a shot through the window of embassy. 
4. The spokeswoman was found be the ambassador's wife.
5. The ambassador is very popular with these spokeswomen.
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-30 Mon 21:27]
deal with
1. If you lived in a fantasy world, you will not be able to deal with these troubles.
2. How do I deal with such a mess?
3. I hated to deal with the ambassador's affairs.
4. The ambassador managed to deal with this.
5. While the ambassador was fast asleep, I knocked at his door.
go doing
climbing dancing fishing hunting riding sailing shooting skating skiing swimming walking
1. I hate to go fishing on rainy days.
2. My wife often goes to extremes to go sailing.
3. If Chandler hadn't been fanatical about skating, he wouldn't have been mulilated.
4. Are you going shopping tonight?
5. I am due to go swimming on Saturday.
imagine sb's dismay when
1. Imagine my dismay when I found out that I had lost my child again.
2. Imagine my dismay when I found you had failed in the test.
3. Imagine your mother's dismay when she leant that you got into such a mess.
4. Imagine our dismay when the busmen went on a strike again.
5. Imagine her dismay when her fiance objected to her.
so long as + ...
1. So long as you love me, I don't care what you did.
2. We will provide you with foods so long as we reached agreement.
3. The gangster has stated that so long as we gave him an helicopter, he will relieve the poor man.
4. So long as they begin rescuing, everything will go smoothly.
5. So long as she was mutilated, I will offer her the job.
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
