#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L08 A famous monastery
#+begin_verse
What are the St. Bernard dogs used for?

The Great St. Benard Pass connects Switerland to Italy.
At 2,473 metres, it is the highest mountain pass in Europe.
The famous monastery of St. Bernard, which was founded in the eleventh century,
	lies about a mile away.
For hundreds of years,
	St. Bernard dogs have saved the lives of travellers crossing the dangerous Pass.
These friendly dogs, which were first brought from Asia,
	were used as watchdogs even in Roman times.
Now that a tunnel has been build through the mountains, the Pass is less dangerous,
	but each year, the dogs are still sent out into the snow whenever a traveller is in difficulty.
Despite the new tunnel, there are still a few people who rashly attempt to cross the Pass on foot.

During the summer months, the monastery is very busy,
	for it is visited by thousands of people who cross the Pass in cars.
As there are so many people about, the dogs have to be kept in a special enclosure.
In winter, however, life at the monastery is quite different.
The temperature drops to -30 and very few people attempt to cross the Pass.
The monks prefer winter to summer for they have more privacy.
The dogs have greater freedom, too,
	for they are allowed to wander outside their enclosure.
The only regular visitors to the monastery in winter are parties of skier
	who go there at Christmas and Easter.
These young people, who love the peace of the mountains,
	always receive a warm welcome at St. Bernard's monastery.
#+end_verse

** words
monastery [ˈmɒnəst(ə)ri] n. 寺庙
St. Bernard ['bə:nəd; bə'nɑ:d]
pass [pɑːs] n. 关隘
watchdog [ˈwɒtʃdɒɡ] n. 看门狗
rashly [ˈræʃli] adj. 鲁莽地
enclosure [ɪnˈkləʊʒə(r)] n. 围地
monk [mʌŋk] n. 和尚
privacy [ˈprɪvəsi] n. 清净
skier [ˈskiːə(r)] n. 滑雪者
Easter [ˈiːstə(r)] n. 复活节

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
