#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 08 A famous monastery
#+begin_verse
What are the St. Bernard dogs used for?

The Great St. Benard Pass *connects Switerland to Italy*.
At 2,473 metres, it is the highest mountain pass in Europe.
The famous monastery of St. Bernard, which was founded in the eleventh century,
	lies about a mile away.
*For hundreds of years*,
	St. Bernard dogs have saved the lives of travellers crossing the dangerous Pass.
These friendly dogs, which were first brought from Asia,
	were used as watchdogs even in Roman times.
*Now that* a tunnel has been build through the mountains, the Pass is less dangerous,
	but each year, the dogs are still sent out into the snow whenever a traveller *is in difficulty*.
Despite the new tunnel, there are still a few people who rashly *attempt to cross* the Pass on foot.

During the summer months, the monastery is very busy,
	for it is visited by thousands of people who cross the Pass in cars.
As there are so many people about, the dogs have to be kept in a special enclosure.
In winter, however, life at the monastery is quite different.
The temperature drops to minus 30 degrees and very few people attempt to cross the Pass.
The monks prefer winter to summer for they have more privacy.
The dogs have greater freedom, too,
	for they are allowed to wander outside their enclosure.
The only regular visitors to the monastery in winter are parties of skier
	who go there at Christmas and Easter.
These young people, who love the peace of the mountains,
	always *receive a warm welcome* at St. Bernard's monastery.
#+end_verse

** words
monastery [ˈmɒnəst(ə)ri] n. 寺庙
St. Bernard ['bə:nəd; bə'nɑ:d]
pass [pɑːs] n. 关隘
watchdog [ˈwɒtʃdɒɡ] n. 看门狗
rashly [ˈræʃli] adj. 鲁莽地
enclosure [ɪnˈkləʊʒə(r)] n. 围地
monk [mʌŋk] n. 和尚
privacy [ˈprɪvəsi] n. 清净
skier [ˈskiːə(r)] n. 滑雪者
Easter [ˈiːstə(r)] n. 复活节

** DONE 单词造句
CLOSED: [2023-11-01 Wed 21:09]
monastery n. St. Bernard
1. He will live in a monastery for the rest of his life.
2. Not only did they go to the monastery, but they went to the stream as well.
3. Not only did they go to the monastery, but they raised money as well.
4. Not only did they go to the monastery, but they went to theater as well.
5. The monastery has been burnt down for some reasons.
pass n.
1. The women and her babies were ordered to make for the mountain pass.
2. We took a long time to cross the mountain pass.
3. The monk is going to write an article on the famous Pass.
4. We were amazed to find that the woman had crossed the pass alone.
5. A party of skiers went to extremes to cross the pass.
watchdog n.
1. If you deal with the watchdog, I'll deal with the guard.
2. The watchdog was too embarrassed to go home.
3. All of us were put to shame by the watchdog who plays football so well.
4. The watchdog used to be called AngelaBaby.
5. The watchdog dressed in a wire is kept in the back yard now.
rashly adv.
1. The article shouldn't rashly go to press.
2. I must have acted rashly.
3. I rashly agree to reach an agreement.
4. I confirmed that I rashly changed into black stockings.
5. Such is human nature that we often regret what we rashly speak.
enclosure n.
1. Trust me, the dog would prefer this enclosure to that one.
2. The enclosure is the secret of success.
3. I need to keep a secret that you bought the enclosure without parents' permission.
4. Just stay in the enclosure and keep the status quo.
5. How does she keep a horse in a special enclosure?
monk n.
1. We are very proud of the monk.
2. Imagine his dismay when the monk had to take a shower in such a bathroom.
3. The monk goes to extremes to keep status quo in the monastery.
4. The monk are often given higher status for one reason or another.
5. The monk is expert at reading long dense books.
privacy n.  Can I get some privacy?
1. You should read privacy police carefully.
2. Oh, my dear. May I get some privacy?
3. The authorities claimed that people needn't privacy at all.
4. The CEO of the website stated that people in China prefer free service to privacy.
5. Dad, get out of my room for the simple reason that I need some privacy.
skier n.
1. These days this kind of equipment is very popular with skiers.
2. These skiers often risk their life in this way that they cross the dangerous Pass by themselves.
3. The skier has the privilege of feeding the dog kept in the enclosure.
4. He turned out to be a skier.
5. Despite the fact that you are a skier.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-01 Wed 21:09]
connect a. to b. = a. be connected to b.
1. The village which connects this village to world outside has broken down last night.
2. The worker succeeded in connecting the pipe to the drainage system of the city.
3. May I connect the wire to your computer?
4. You shouldn't have connected the wire to your computer.
5. The microphone made in China is connected to the tower.
for hundreds of years
1. His family has had power in the country for hundreds of years.
2. Their family has been worship the goddess for hundreds of years.
3. This picture has been in my house for hundreds of years.
4. This conviced me that my family has farmed in this area for hundreds of years.
5. Our family has lived in about her for hundreds of years.
Now that + ...(原因状从)
1. Now that you are a graduate, you will be free on a long vocation.
2. Now that the entrance of the museum is closed, we shall go home.
3. Now that you took money to pieces, we couldn't afford to take a bus.
4. You certainly gave me a surprise now that you repair the clock.
5. Now that the clerk is eager to get a better salary, he will do anything to sell it to you.   
be in difficulty
1. When I am in difficulty, it always remind me of my father.
2. We should pay more attention to the people who are in difficulty.
3. The nurse is in difficulty now that the patient is having an operation.
4. I'm fairly certain that my wife is in difficulty.
5. Our family used to be in difficulty.
attempt to do sth.
1. Not only did he attempt to buy the house, but he attempted to hold the Games as well.
2. Not only did he attempt to enter for the competition, but he intended to break the world record.
3. What a mess! I attempted to clean it up.
4. I attempted to train my cat pressing the button.
5. I attempted to get close to my girlfriend in the crowd.
receive a warm welcome
1. She was disappointed to find that she didn't receive a warm welcome.
2. I was just wondering if I would receive a warm welcome.
3. On that festive, every stranger coming to the village receive a warm welcome.
4. This group of pop singer received a warm welcome at the station.
5. If you made that stupid remark on the bulletin board, you wouldn't receive a warm welcome.
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
