#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L09 Flying cats
#+begin_verse
How do cats try to protect themselves when falling from great heights?

Cats never fail to fascinate human beings.
They can be friendly and affectionate towards humans,
	but they lead mysterious lives of their own as well.
They never become submissive like dogs and horses.
As a result, humans have learned to respect feline independence.
Most cats remain suspicious of humans all their lives.
One of the things that fascinates us most about cats is the popular belief
	that they have nine lives.
Apparently, there is a good deal of truth in this idea.
A cat's ability to survive falls is based on fact.

Recently the New York Animal Medical Centre made a study of 132 cats over a period of five months.
All these cats had one experience in common:
	they had fallen off high buildings, yet only eight of them died from shock or injuries.
Of course, New York is the ideal place for such an interesting study,
	because there is no shortage of tall buildings.
There are plenty of high-rise windowsills to fall from!
One cat, Sabrina, fell 32 storeys, yet only suffered from a broken tooth.
'Cats behave like well-trained paratroopers,' a doctor said.
It seems that the further cats fall, the less they are likely to injure themseleves.
In a long drop, they reach speeds of 60 miles an hour and more.
At high speeds, falling cats have time to relax.
They stretch out their legs like flying squirrels.
This increases their air-resistance and reduces the shock of impact when they hit the groud.
#+end_verse

** words
fascinate [ˈfæsɪneɪt] v. 迷住
affectionate [əˈfekʃənət] adj. 充满深情的
mysterious [mɪˈstɪəriəs] adj. 神秘的
submissive [səbˈmɪsɪv] adj. 服从的
feline [ˈfiːlaɪn] adj. 猫的
independence [ˌɪndɪˈpendəns] n. 独立的
high-rise [ˈhaɪ raɪz] adj. 高层的
windowsill [ˈwɪndəʊsɪl] n. 窗槛
paratrooper [ˈpærətruːpə(r)] n. 伞兵
squirrel [ˈskwɪrəl] n. 松鼠
air-resistance [rɪˈzɪstəns] n. 空气阻力
impact [ˈɪmpækt] n. 冲击力


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
