#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L11 Not guilty
#+begin_verse
What was the Customs Officer looking for?

Customs Officers are quite tolerant these days,
	but they can still stop you are going through the Green Channel and have nothing to declare.
Even really honest people are often made to feel guilty.
The hardened professional smuggler,
	on the other hand, is never troubled by such fellings,
	even if he has five hundred gold watches hidden in his suitcase.
When I returned from abroad recently,
	a particularly officious young Customers Officer clearly regarded me as a smuggler.

'Have you anything to declare?'he asked, looking me in the eye.
'No', I answered confidently.
'Would you mind unlocking this suitcase please?'
'Not at all', I answered.

The Officer went through the case with great care.
All the things I had packed so carefully were soon in a dreadful mess.
I felt sure I would never be able to close the case again.
Suddenly, I saw the Officer's face light up.
He had spotted a tiny bottle at the bottom of my case and he pounced on it with delight.

'Perfume, eh?' he asked sarcastically.
	'You should have declared that. Perfume is not exempt from import duty.'
'But it isn't perfume,' I said. 'It's hair gel.'
	Then I added with a smile, 'It's a strange mixture I make myself.'
As I expected, he did not believe me.
'Try it!' I said encouragingly.
The Officer unscrewed the cap and put the bottle to his nostrils.
He was greeted by an unpleasant smell which convinced him that I was telling the truth.
A few minutes later, I was able to hurry away with precious chalk marks on my baggage.
#+end_verse

** words
guilty [ˈɡɪlti] adj. 犯罪的,违法的
tolerant [ˈtɑːlərənt] adj. 宽容的
declare [dɪˈkler] v. 申报
hardened [ˈhɑrdnd] adj. 有经验的
professional [prəˈfeʃən(ə)l] adj. 职业的,专业的
smuggler [ˈsmʌɡ(ə)lər] n. 走私者
officious [əˈfɪʃəs] adj. 爱管闲事的
confidently [ˈkɑːnfɪdəntli] adv. 自信地
dreadful [ˈdredf(ə)l] adj. 可怕的
pounce [paʊns] v. 猛抓
perfume [pərˈfjuːm] n. 香水
sarcastically [sɑːrˈkæstɪkli] adv. 讽刺地
exempt [ɪɡˈzempt] adj. 被免除的
duty [ˈduːti] n. 税
mixture [ˈmɪkstʃər] n. 混合物
nostril [ˈnɑːstrəl] n. 鼻孔
chalk [tʃɔːk] n. 粉笔
baggage [ˈbæɡɪdʒ] n. 行李

