#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L12 Life on a desert island
#+begin_verse
What was exceptional about the men's stay on the desert island?

Most of us have formed an unrealistic picture of life on a desert island.
We sometimes imagine a desert island to be a sort of paradise where the sun always shines.
Life there is simple and good.
Ripe fruit falls from the trees and you never have to work.
The other side of the picture is quite the opposite.
Life on a desert island is wrectched.
You either starve to death or live like Robinson Crusoe,
	waiting for a boat which never comes.
Perhaps there is an element of truth in both these pictures,
	but few of us have had the opportunity to find out.

Two men who recently spent five days on a coral island wished they had stayed there longer.
They were taking a badly damaged boat from the Virgin Islands to Miami to have it repaired.
During the journey, their boat began to sink.
They quickly loaded a small rubber dinghy
	with food, matches, and cans of beer and rowed for a few miles across the Caribbean
	until they arrived at a tiny coral island.
There were hardly any trees on the island and there was no water,
	but this did not prove to be a problem.
The men collected rainwater in the rubber dinghy.
As they had brought a spear gun with them, they had plenty to eat.
They caught lobster and fish every day, and, as one of them put it 'ate like kings'.
When a passing tanker rescued them five days later,
	both men were genuinely sorry that they had to leave.
#+end_verse

** words
desert island ['dezət-aɪlənd] 荒岛
unrealistic [ˌʌnriːəˈlɪstɪk] adj.不真实的
paradise [ˈpærədaɪs] n.天堂,乐土
wretched [ˈretʃɪd] adj.可怜的,艰苦的
starve [stɑːrv] v.挨饿
element [ˈelɪmənt] n.成分
opportunity [ˌɑːpərˈtuːnəti] n.机会
coral [ˈkɔːrəl] n.珊瑚
Virgin islands ['və:dʒin] [ˈaɪləndz] 维尔京群岛
Miami [maɪˈæmi] n.迈阿密(美国最南的城市)
dinghy [ˈdɪŋi; ˈdɪŋɡi] n.救生筏,小船
Caribbean [ˌkærɪˈbiːən; kəˈrɪbiən] n.加勒比海
spear gun [spɪr ɡʌn] 捕鱼枪
tanker [ˈtæŋkər] n.油轮
genuinely [ˈdʒenjuɪnli] adv.由衷地
Robinson Crusoe [ˈrɑbɪnsən] [ˈkruːsoʊ] 鲁滨逊丶克鲁索

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
