#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 13 It's only me
#+begin_verse
What did the man expect to find under the stairs?

After her husband had gone to work,
	Mrs. Richards sent her children to school and went upstairs to her bedroom.
She was too excited to do any housework that morning,
	for in the evening she would be going to a *fancy-dress party* with her husband.
She intended to dress up as a ghost
	and as she had made her costume the night before, she *was impatient to* try it on.
Though the costume *consisted only of* a sheet, it was very effective.
After putting it on, Mrs Richards went downstairs.
She wanted to find out whether it would be comfortable to wear.

Just as Mrs. Richards was entering the dining room, there was a knock on the front door.
She knew that it must be the baker.
She had told him to come straight in
	if ever she failed to open the door and to leave the bread on the kitchen table.
Not wanting to frighten the poor man,
	Mrs Richards quickly hid in the small storeroom under the stairs.
She heard the front door open and heavy footsteps in the hall.
Suddenly the door of the storeroom was opened and a man entered,
	Mrs Richards realized that it must be the man from the Electricity Board
		who had come to read the metre.
She tried to explain the situation, saying 'It's only me', but it was too late.
The man *let out a cry* and jumped back several paces.
When Mrs. Richards walked towards him, he fled, slamming the door behind him.
#+end_verse

** words
costume [ˈkɑstum] n. 化装服
consist [kənˈsɪst] v. 由……组成
sheet [ʃit] n. 被单
effective [ɪˈfektɪv] adj. 有明显效果的，有作用的
comfortable [ˈkʌmfərtəb(ə)l] adj. 舒适的
storeroom [ˈstɔrˌrum] n. 储藏室
electricity [ˌilekˈtrɪsəti] n. 电
metre [ˈmitər] n. 电表
pace [peɪs] n. 一步
flee [fli] (fled [fled], fled) v. 逃走
slam [slæm] v. 砰地关上

** DONE 单词造句
CLOSED: [2023-11-11 Sat 20:24]
costume n.
1. I found you very beautiful in the costume party.
2. I saw you go to the costume party.
3. Leo stated that he had returned the costume to you last night.
4. It is said that we will be going to the costume party tonight.
5. I am going to be dressed up as a ghost in the costume party.
consist v.  consist of ...
1. You needn't have eaten the foods that consist only of sugar.
2. He was genuinely sorry that his paper consists only of two chapters.
3. The crowd which was waiting in line consisted of busmen and college students.
4. On the other hand it consists mostly of sugar and water.
5. I was made to eat foods which consists mostly of salt and sugar.
sheet n.
1. I wished that you had washed our sheet.
2. The sheet was so expensive that we couldn't afford to it.
3. I was greeted by an unpleasant smell which comes from the sheet.
4. You should have washed your sheet.
5. The sheet clinged to a mixture of hair gel and toothpaste.
effective adj.
1. Leo's English course turns out to be very effective.
2. Imagine my dismay when I found out that my child's study plan was not effective.
3. I always feel obliged to find more effective method.
4. I usually work very effectively, for I take my job seriously.
5. In the end Leo's English course proved effective.
comfortable adj.  make yourself comfortable
1. If you are so hard on us, how could we make ourselves comfortables?
2. I tried to make myself comfortabel in the chair.
3. Make yourself comfortable, help yourself to these fruits.
4. Why don't you grab a beer and make yourself comfortabel?
5. I usually take a long time to make myself comfortable on the bed.
storeroom n.
1. The boy claimed to have seen a puma in the storeroom.
2. There was some puma fur clinging to the knife in the storeroom.
3. The worker is going to read the electricity meter in the storeroom.
4. This is the storeroom which Harry Potter used to live in.
5. The gangsters stated that the diamonds were hidden in a storeroom.
electricity n. meter=metre n.
1. Turn off your computer, it's a waste of electricity.
2. When I was very young, my parents always ordered to turn off lights to save electricity.
3. The editor decided to publish an article on electricity meters.
4. Only workers for the Electricity Board have the privilege of reading the electricity meter.
5. You must have had your electricity meter repaired.
pace n.  at your own pace  The pace of life
1. Let me study at my own pace.
2. These days, people who do manual work are often used to the slow pace of life. 
3. I am willing to sacrifice higher pay for the slow pace of life.
4. I'm used to the fast pace of life in the uptown.
5. The fast pace of life is his secret of success.
flee fled v.
1. She complained that if the police had arrived on the scene, the thief wouldn't have fled.
2. After she had saw her father get angry, she fled and went to the school.
3. He fled for the simple reason that he realized that he hadn't finished his task.
4. Despite the fact that you feld in our wedding.
5. I happened to see a thief fleeing at the edge of the forest.
slam v. close
1. Equipped with a torchlight, the vicar slammed the door and went up to see what had happened.
2. The men is so rude that he is always slamming the door.
3. It is disturbing to think that your roomate is always slamming the door at midnight.
4. It is consider unlucky for people in China slamming the door in January.
5. The man set the house on fire, slamming the door.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-11 Sat 20:24]
fancy dress party
1. Fancy dress parties are popular with young men and women.
2. She is reluctant to go to the fancy dress party because of her ex-boyfriend.
3. His father went to extremes to prevent him from going to the fancy dress party.
4. The fancy dress party will be held in Disney land tonight.
5. It comes as a surprise to learn that a fancy dress party will be held tonight.
be impatient to do sth.
1. It comes as a surprise to learn that she was impatient to do housework.
2. It comes as a surprise to learn that the clerk was impatient to send me a book.
3. The cat was impatient to drink milk in the morning.
4. I was impatient to take a bath.
5. She was impatient to wrap the clothes up.
let out a cry
1. You needn't have let out a cry. It's only me.
2. I wish that she hadn't let out a cry.
3. Letting out a cry, she lost his patience.
4. Letting out a cry, she knocked him to the ground.
5. Letting out a cry, she stoond to attention.

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
