* Lesson 14 A noble gangster
#+begin_verse
How did Hawkwood make money in times of peace?

There was a time
	when the owners of shops and businesses in Chicago
		had to pay large sums of money to gangsters in return for ‘protection’.
If the money was not paid promptly,
	the gangsters would quickly put a man out of business by destroying his shop.
Obtaining 'protection money' is not a modern crime.
As long ago as the fourteenth century,
	an Englishman, Sir John Hawkwood, made the remarkable discovery
		that people would rather pay large sums of money
			than have their life work destroyed by gangsters.

Six hundred years ago,
	Sir John Hawkwood arrived in Italy with a band of soldiers and settled near Florence.
He soon made a name for himself and came to be known to the Italians as Giovanni Acuto.
Whenever the Italian city-states were at war with each other,
	Hawkwood used to hire his soldiers to princes
		who were willing to pay the high price he demanded.
In times of peace, when business was bad,
	Hawkwood and his men would march into a city-state and,
		after burning down a few farms,
	would offer to go away if protection money was paid to them.
Hawkwood made large sums of money in this way.
In spite of this, the Italians regarded him as a sort of hero.
When he died at the age of eighty,
	the Florentines gave him a state funeral
		and had a picture painted which was dedicated to the memory of
			'the most valiant soldier and most notable leader, Signor Giovanni Haukodue'.
#+end_verse

** words
gangster [ˈɡæŋstər] n. 歹徒，强盗
Chicago [ʃɪ'kɑ:ɡoʊ] n. 芝加哥（美国城市）
protection [prəˈtekʃən] n. 保护
promptly [ˈprɑmptli] adv. 准时地
destroy [dɪˈstrɔɪ] v. 毁掉；消灭
remarkable [rɪˈmɑrkəb(ə)l] adj. 不寻常的
band [bænd] /bænd/n. 帮，团伙
Florence ['flɔrəns] n. 佛罗伦萨（意大利城市）
city-state [ˈsɪti'steɪt] n. （古代）城邦
hire [ˈhaɪr] v. 租出，雇给
prince [prɪns] n. 君主，诸侯
Florentine ['flɒrəntaɪn] n. 佛罗伦萨人
funeral [ˈfjun(ə)rəl] n. 葬礼
dedicate [ˈdedɪˌkeɪt] v. 奉献，题献给
memory [ˈmem(ə)ri] n. 纪念
valiant [ˈvæliənt] adj. 英勇的
