#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L15 Fifty pence worth of trouble
#+begin_verse
Did George get anything for his fifty pence? What?

Children always appreciate small gifts of money.
Mum or dad, of course, provide a regular supply of pocket money,
	but uncles and aunts are always a source of extra income.
With some children, small sums go a long way.
If fifty pence pieces are not exchanged for sweets, they rattle for months inside money boxes.
Only very thrifty children managed to fill up a money box.
For most of them, fifty pence is a small price to pay for a nice big bar of chocolate.

My nephew, George, has a money box but it is always empty.
Very few of the fifty pence pieces and pound coins I have given him have found their way there.
I gave him fifty pence yesterday and advised him to save it.
Instead he bought himself fifty pence worth of trouble.
On his way to the sweet shop, he dropped his fifty pence
	and it bounced along the pavement and then disappeared down a drain.
George took off his jacket, rolled up his sleeves and pushed his right arm through the drain cover.
He could not find his fifty pence piece anywhere, and what is more, he could not get his arm out.
A crowd of people gathered round him and a lady rub his arm with soap and butter,
	but George was firmly stuck.
The fire brigade was called and two fire fighters freed George using a special type of grease.
George was not too upset by his experience
	because the lady who owns the sweet shop heard about his troubles
		and rewarded him with a large box of chocolates.
#+end_verse

** words
appreciate [əˈpriːʃieɪt] v.欣赏
pocket [ˈpɑːkɪt] money 零用钱
rattle [ˈræt(ə)l] v.格格作响
thrifty [ˈθrɪfti] adj.节俭的
nephew [ˈnefjuː] n.侄子
bounce [baʊns] v.弹起,跳起
pavement [ˈpeɪvmənt] n.人行道
stick [stɪk] v.卡住
brigade [brɪˈɡeɪd] n.旅,(消防)队
grease [ɡriːs] n.润滑油

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
