* Lesson 16 Mary had a little lamb
#+begin_verse
Was Dimitri right to apologize to his neighbour? Why not?

Mary and her husband Dimitri lived in the tiny village of Perachora in southern Greece.
One of Mary's prize possessions was a little white lamb which her husband had given her.
She kept it tied to a tree in a field during the day and went to fetch it every evening.
One evening, however, the lamb was missing.
The rope had been cut, so it was obvious that the lamb had been stolen.

When Dimitri came in from the fields, his wife told him what had happened.
Dimitri at once set out to find the thief.
He knew it would not prove difficult in such a small village.
After telling several of his friends about the theft,
	Dimitri found out that his neighbour, Aleko, had suddenly acquired a new lamb.
Dimitri immediately went to Aleko's house and angrily accused him of stealing the lamb.
He told him he had better return it or he would call the police.
Aleko denied taking it and led Dimitri into his backyard.
It was true that he had just bought a lamb, he explained, but his lamb was black.
Ashamed of having acted so rashly, Dimitri apologized to Aleko for having accused him.
While they were talking it began to rain and Dimitri stayed in Aleko's house until the rain stopped. When he went outside half an hour later, he was astonished to find that the little black lamb was almost white. Its wool, which had been dyed black, had been washed clean by the rain!
#+end_verse

** Words
prize [praɪz] adj. 珍贵的，宝贵的
tie [taɪ] v. 拴，系
theft [θeft] n．偷盗行为，偷盗案
accuse [əˈkjuz] v. 指控
deny [dɪˈnaɪ] v. 否认
ashamed [əˈʃeɪmd] adj．感到羞耻，惭愧
apologize [əˈpɒləˌdʒaɪz] v. 道歉
dye [daɪ] v. 染
