#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L17 The longest suspension bridge in the world
#+begin_verse
How is the bridge supported?

Verrazano, an Italian about whom little is known,
	sailed into New York Harbour in 1524 and named it Angouleme.
He described it as 'a very agreeable situation located within two small hills
	in the midst of which flowed a great river.'
Though Verrazano is by no means considered to be a great explorer,
	his name will probably remain immortal, for on November 21st, 1964,
	the longest suspension bridge in the world was named after him.

The Verrazano Bridge, which was designed by Othmar Ammann, joins Brooklyn to Staten Island.
It has a span of 4260 feet.
The bridge is so long that the shape of the earth had to be taken into account by its designer.
Two great towers support four huge cables.
The towers are built on immense underwater platforms made of steel and concrete.
The platforms extend to a depth of over 100 feet under the sea.
These alone took sixteen months to build.
Above the surface of the water, the towers rise to a height of nearly 700 feet.
They support the cables from which the bridge has been suspended.
Each of the four cables contains 26108 lengths of wire.
It has been estimated that if the bridge were packed with cars,
		it would still only be carrying a third of its total capacity.
However, size and strength are not the only important things about this bridge.
Despite its immensity, it is both simple and elegant,
	fulfilling its designer's dream to create 'an enormous object drawn as faintly as possible'.
#+end_verse

** words
suspension [səˈspenʃ(ə)n] n.吊
agreeable [əˈɡriːəb(ə)l] adj.宜人的
situation [ˌsɪtʃuˈeɪʃ(ə)n] n.地点
locate [ˈloʊkeɪt] v.位于
immortal [ɪˈmɔːrt(ə)l] adj.永生的
Brooklyn [ˈbrʊklɪn; ˈbrʊklən] n.布鲁克林
Staten [nil] n.斯塔顿
span [spæn] n.跨度
cable [ˈkeɪb(ə)l] n.缆索
concrete [ˈkɑːnkriːt] n.混凝土
suspend [səˈspend] v.悬挂
length [leŋθ] n.根,段
estimate [ˈestɪmət] v.估计
capacity [kəˈpæsəti] n.承受量
immensity [ɪˈmensəti] n.巨大
elegant [ˈelɪɡənt] adj.优美别致的
faintly [ˈfeɪntli] adv.微细地
