#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 18 Electric currents in modern art
#+begin_verse
How might some of the exhibits have been dangerous?

Modern sculpture *rarely* surprises us *any more*.
*The idea that* modern art can only be seen in museums *is mistaken*.
Even people who *take no interest in* art 
  cannot have failed to notice examples of modern sculpture on display in public places.
Strange forms stand in gardens, outside buildings and shops.
We have got quite used to them.
Some so called 'modern' pieces have been on display for nearly eighty years.

In spite of this,
	some people -including myself- were surprised by a recent exhibition of modern sculpture.
The first thing I saw when I entered the art gallery was a notice which said:
  'Do not touch the exhibits. Some of them are dangerous!'
The objects on display were pieces of moving sculpture.
Oddly shaped forms that are suspended from the ceiling and move *in response to* a gust of wind 
	*are quite familiar to* everybody.
These objects, however, were different.
Lined up against the wall, there were long thin wires *attached to* metal spheres.
The spheres had been magnetized and attracted or repelled each other all the time.
In the centre of the hall, there were a number of tall structures which contained coloured lights.
These lights flicker continuously like traffic lights which have *gone mad*.
Sparks were emitted from small black boxes and red lamps flashed *on and off* angrily.
*It was rather like* an exhibition of prehistoric electronic equipment.
These peculiar forms not only *seemed designed to shock* people emotionally, 
	but to give them electric shocks as well.
#+end_verse

** words
current [ˈkʌrənt] n. 电流
sculpture [ˈskʌlptʃə] n. 雕塑
mistaken [miˈsteɪk] adj. 错误的
gallery [ˈɡæləri] n. 美术馆
exhibit [ɪɡˈzɪbɪt] n. 展品，陈列品
oddly [ˈɑdli] adv. 古怪的
attach [əˈtætʃ] v. 连，系
sphere [sfɪr] n. 球体
magnetize [ˈmæɡnəˌtaɪz] v. 使磁化
repel [rɪˈpel] v. 排斥
flicker [ˈflɪkər] v. 闪烁
emit [ɪˈmɪt] v. 放射
flash [flæʃ]/ v. 闪光
prehistoric [ˌpriˈhɪstɔrɪk] adj. 史前的，老掉牙的
electronic [ˌilekˈtrɑnɪk] adj. 电子的
peculiar [pɪˈkjuljər] adj. 奇异的
shock [ʃɑk] v. 令人震惊，刺激人
emotionally [ɪˈmoʃənlɪ] adv. 感情上

** 单词造句
current n.  electric currents
sculpture n.  make/create a sculpture
1. 
2. 
3. 
4. 
5. 
mistaken adj.  be mistaken about sth./sb.
1. 
2. 
3. 
4. 
5. 
gallery n.
1. 
2. 
3. 
4. 
5. 
exhibit n.v. exhibition n.
1. 
2. 
3. 
4. 
5. 
oddly adv.  Oddly enough, + ...
1. 
2. 
3. 
4. 
5. 
attach v.  be attached to sb./sth. = attach a. to b.
1. 
2. 
3. 
4. 
5. 
sphere n.
1. 
2. 
3. 
4. 
5. 
magnetize v.
1. 
2. 
3. 
4. 
5. 
repel v.
1. 
2. 
3. 
4. 
5. 
flicker v.
1. 
2. 
3. 
4. 
5. 
emit v.
1. 
2. 
3. 
4. 
5. 
flash v.
1. 
2. 
3. 
4. 
5. 
prehistoric adj.
1. 
2. 
3. 
4. 
5. 
electronic adj.
1. 
2. 
3. 
4. 
5. 
peculiar adj.
1. 
2. 
3. 
4. 
5. 
shock v.n.  get/receive an electric shock  give you electric shocks
1. 
2. 
3. 
4. 
5. 
emotionally adv.
1. 
2. 
3. 
4. 
5. 

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
not any more = not any longer = no longer
1. 
2. 
3. 
4. 
5. 
The idea that + ... is mistaken
1. 
2. 
3. 
4. 
5. 
take no/ a great/an interest in
1. 
2. 
3. 
4. 
5. 
in response to
1. 
2. 
3. 
4. 
5. 
be/sound/look/seem familiar to sb.
1. 
2. 
3. 
4. 
5. 
go mad
1. 
2. 
3. 
4. 
5. 
on and off
1. 
2. 
3. 
4. 
5. 
It was rather like ...
1. 
2. 
3. 
4. 
5. 
seemed adj.(designed)  ...
1. 
2. 
3. 
4. 
5. 
be designed to do sth.
1. 
2. 
3. 
4. 
5. 
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
