#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 19 A very dear cat
#+begin_verse
Why was Rastus 'very dear' in more ways than one?

Kidnappers are rarely interested in animals,
	but they recently took considerable interest in Mrs. Eleanor Ramsay's cat.
Mrs. Eleanor Ramsay, a very wealthy old lady,
	has shared a flat with her cat, Rastus, for a great many years.
Rastus leads an orderly life.
He usually takes a short walk in the evenings and is always home by seven o'clock.
One evening, however, he failed to arrive.
Mrs. Ramsay got very worried.
She looked everywhere for him but could not find him.

Three days after Rastus' disappearance, Mrs. Ramsay received an anonymous letter.
The writer stated that Rastus was in safe hands and would be returned immediately
	if Mrs. Ramsay paid a ransom of 1,000 dollars.
Mrs. Ramsay was instructed to place the money in a cardboard box and to leave it outside her door.
At first, she decided to go to the police,
	but fearing that she would never see Rastus again
	-- the letter had made that quite clear --
	she changed her mind.
She withdrew 1,000 dollars from her bank and followed the kidnapper's instructions.
The next morning, the box had disappeared
	but Mrs. Ramsay was sure that the kidnapper would keep his word.
Sure enough, Rastus arrived punctually at seven o'clock that evening.
He looked very well, though he was rather thirsty, for he drank half a bottle of milk.
The police were astounded when Mrs. Ramsay told them what she had done.
She explained that Rastus was very dear to her.
Considering the amount she paid, he was dear in more ways than one!
#+end_verse

** words
dear [dɪr] adj. 亲爱的；珍贵的；昂贵的
kidnapper ['kɪdnæpə(r)] n. 绑架者，拐骗者
considerable [kənˈsɪd(ə)rəb(ə)l] adj. 相当大的
wealthy [ˈwelθi] adj. 富的，有钱的
orderly [ˈɔrdərli] adj. 有规律的
disappearance [ˌdɪsəˈpɪrəns] n. 失踪
anonymous [əˈnɑnɪməs] adj. 匿名的
ransom [ˈrænsəm] n. 赎金
cardboard [ˈkɑrdˌbɔrd] n. 硬纸板
withdraw [wɪðˈdrɔ] (withdrew [wið'dru:],withdrawn [wið'drɔ:n]) v.(从银行)取钱
punctually ['pʌŋktʃuəli] adv. 准时地
astound [əˈstaʊnd] v. 使吃惊

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
