#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 20 Pioneer pilots
#+begin_verse
What was the name of the first plane to fly across the English Channel?

In 1908 Lord Northcliffe offered a prize of 1,000 dollars to the first man
	who would fly across the English Channel.
Over a year passed before the first attempt was made.
On July 19th, 1909, in the early morning,
	Hubert Latham took off from the French coast in his plane the 'Antoinette IV'.
He had travelled only seven miles across the Channel
	when his engine failed and he was forced to land on the sea.
The 'Antoinette' floated on the water until Latham was picked up by a ship.

Two days later, Louis Bleriot arrived near Calais with a plane called 'No. XI'.
Bleriot had been making planes since 1905 and this was his latest model.
A week before, he had completed a successful overland flight
	during which he covered twenty-six miles.
Latham, however, did not give up easily.
He, too, arrived near Calais on the same day with a new 'Antoinette'.
It looked as if there would be an exciting race across the Channel.
Both planes were going to take off on July 25th, but Latham failed to get up early enough.
After making a short test flight at 4.15 a.m., Bleriot set off half an hour later.
His great flight lasted thirty-seven minutes.
When he landed near Dover, the first person to greet him was a local policeman.
Latham made another attempt a week later and got within half a mile of Dover,
	but he was unlucky again.
His engine failed and he landed on the sea for the second time.
#+end_verse

** words
pioneer [ˌpaɪəˈnɪr] n. 先驱
lord [lɒrd] n. 对（英国）贵族的尊称；勋爵
Calais [kæ'leɪ] n. 加来（法国港市）
overland [ˈoʊvərˌlænd] adj. 陆上的

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
