#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 01 down to ride for him
#+begin_verse
Humans of New York

"He makes me want to know about little things, so that I can teach him.
Like when we sit by this lake,
	I wish I knew what kind of turtle that was, so I could tell him.
And I want to figure out what kind of duck that is,
	so I can tell him all about it the next time we come."
"What do you want most for him?"
"Whatever his dreams are, I'm down to ride for him."
"What's your biggest fear for him?"
"That he won't try.
If he doesn't try, I'll be hurt.
Cause then we'll never know how far he'd get."
#+end_verse

*** 习惯用法造句
a so that b... N2L59
1. I try to make money so that I can afford to buy my wife's clothes.
2. I want to pass the IELTS, so that I can land a better job.
3. I applied for an MBA from Harvard, so that I can have an edge over my competitors.
I wish I knew that ... (尝试查阅wish的⽤法)
1. I wish I knew whether she was a lesbian.
2. I wish I knew that you had already graduated college.
3. I wish I knew that you can speak English fluently.
sb. figure out sth.
1. In the end, I figured out the number of steps which lead to the high wall.
2. Last night, I figured out the poor man who is working for Ellemes Corporation.
3. I figure out whether he is my brother-in-law.
be down to ride
1. If he doesn't try, I won't be down to ride for him. 
2. Whatever the situation is, I'm down to ride for you.
3. I'm down to ride for you, so that you can get enough money to have the clock repaired.
if ⼀般现在时，⼀般将来时。 N2L16
1. If you're down to ride for him, he'll be successful.
2. If you figure out what kind of turtle that is, you'll be able to tell him about it.
3. If she doesn't try to work hard, she won't be fluent in English.

*** Asking questions
1. Why does he want to know about little things?
	 so that he can teach his child.
2. Did the man know what kind of turtle that was?
	 No, he didn’t.
3. Why did the man want to know what kind of duck that was?
	 so he can tell his child all about it the next time they come.
4. What does the man want most for his child?
	 fulfill his dream.
5. What’s his biggest fear for the child?
	 He won’t even try.
