#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 02 You're the best dad ever
#+begin_verse
Just the other day a video *popped up* on Facebook.
It was only five years ago.
We were in the park.
I was pushing her on the bike, letting go.
We used to have so much fun together.
We'd always get ice cream.
She's a strawberry girl.
I'm a vanilla guy.
Chipwich, actually. I'm a Chipwich guy.
She'd give me a hug afterward, tell me I was the best dad ever.
We were such good friends.
But now it feels like we're so far apart.
She doesn't want to talk to me anymore.
Even when she's upset, she'll ignore me and go to her room.
It's like: C'mon. I was fifteen too.
I know what it's like.
But she'll come back, I know that.
They always come back.
But it does feels like you're getting your heart ripped out a little bit.
But look, I get it.
She's figuring out life.
You have to back off.
You have to give them space.
Cause if you charge after them and get all aggressive about it, you might push them away forever.
But they always come back, right?
One day she's gonna realize that I'm not the enemy and I'm really her dad, her friend.
I still get a flicker of it, every once in a while.
We had a really surreal moment last year.
Her birthday is March 17th.
She's a St. Paddy's Day birthday.
We always take her to a Spanish restaurant on Long Island, but this time we did something special.
Her uncle used to be a bodyguard for Taylor Swift, and we still know some people at the company.
So they got us tickets to her concert.
Fifth row seats. I mean, don't get me wrong.
We paid for them, but fifth row center.
She was crying.
I got a big hug. A big kiss. A 'Thank you, Dad.'
It wasn't 'You're the best dad ever.'
But it was a really big: 'Thank you, Dad.'
#+end_verse
** expressions
pop up
1. In the end, a porn video popped up on my desktop.
2. There was a time when a sort of advertisement was popping up on our desktop.
3. If your boss found out that a porn video popped on your desktop, you would get fired.
what it's like: to be familiar with how it feels to be or do something
1. I wish I knew what it was like.
2. If she knew what it was like, she wouldn't try.
3. She said she knew what it was like, but she hadn't.
rip out heart
1. If you go to the theater on her birthday, it will rip out your grandmother's heart.
2. When reports came to London, it ripped out the heart of our expert from London Zoo.
3. Don't be rude, it may rip out your wife's heart.
back off
1. I must back off to prevent me from making mistakes.
2. Please back off, it's none of your business.
3. She got so angry that she refused to back off.
get a flicker of: a feeling or expression of an emotion or quality that does not last very long
1. She must have been very upset just then, I get a flicker of it.
2. There must be a group of bodyguards spying on us, I got a flicker of it.
3. Our enemies are making for us, I got a flicker of it.
