#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 06 Smash-and-grab
#+begin_verse
How did Mr. Taylor try to stop the thieves?

The expensive shops in a famous arcade near Piccadilly were just opening.
At this time of morning, the arcade was almost empty.
Mr. Taylor, the owner of a jewellery shop was admiring a new window display.
Two of his assistants had been working busily since eight o'clock and had *only just* finished.
Diamond necklaces and rings had been beautifully arranged on a background of black velvet.
After gazing at the display for several minutes, Mr. Taylor went back into his shop.

The silence was suddenly broken
	when a large car, with its headlights on and its horn blaring, roared down the arcade.
It *came to a stop* outside the jeweller's.
One man stayed at the wheel
	while two others with black stockings over their faces
		jumped out and smashed the window of the shop with iron bars.
While this was going on, Mr. Taylor was upstairs.
He and his staff began throwing furniture out of the window.
Chairs and tables went flying into the arcade.
One of the thieves was struck by a heavy statue,
	but he was *too busy helping himself to diamonds to* notice any pain.
The raid was all over in three minutes,
	for the men scrambled back into the car
		and it moved off *at a fantastic speed*.
Just as it was leaving,
	Mr. Taylor rushed out and ran after it throwing ashtrays and vases,
	but it was impossible to stop the thieves.
They had got away with *thousands of pounds worth of diamonds*.
#+end_verse

** words
smash-and-grab [smæʃ-ənd-'ɡræb] n. 砸橱窗抢劫
arcade [ɑːˈkeɪd] n. 有拱廊的街道
Piccadilly [ˌpɪkəˈdɪli] n. 皮卡迪利大街
jewellery [ˈdʒuːəlri] n. 珠宝
necklace [ˈnekləs] n. 项链
ring [rɪŋ] n. 戒指
background [ˈbækɡraʊnd] n. 背景
velvet [ˈvelvɪt] n. 天鹅绒
headlight [ˈhedlaɪt] n. 前灯
blare [bleə(r)] v. 嘟嘟声
staff [stɑːf] n. 全体工作人员
raid [reɪd] n. 偷袭
scramble [ˈskræmb(ə)l] v. 爬行
fantastic [fænˈtæstɪk] adj. 非常大的
ashtray [ˈæʃtreɪ] n. 烟灰缸

** vocabulary
expensive: dear
almost: nearly
assistants: helpers
gazing: looking
several: a few, a number of
stayed: remained
smashed: broke to pieces

** DONE 单词造句
CLOSED: [2023-10-29 Sun 12:08]
smash-and-grab  smash sth. to pieces  grab a beer/coffee
1. They had a fight and they have only just smashed the book to pieces.
2. My cat is always smashing every toys to pieces.
3. Would you like to grab a coffee upstairs?
4. Make youself comfortable and grab a beer.
5. You needn't have smashed the coach to pieces.
arcade n.  go to the arcade
1. My wife was eager to go to the arcade so that she could buy a nice ice cream.
2. Why does she look down on those people who often go to the arcade?
3. I always hesitate to go to the arcade.
4. She takes three hour to go to the arcade every week.
5. I'm gonna write an article on the well-known arcade.
jewellery n. jewelry
1. The woman in front of the jewelry shop hesitated to buy that diamond.
2. At last, the woman got impatient in the jewellery shop.
3. He informed that he was going to write an article on the story of jewelry.
4. It's a waste of time making jewelry by youself.
5. She goes to extremes to make jwellery by herself.
necklace n.
1. I was wondering whether you are wearing a necklace.
2. From now on, I will not wear any necklace.
3. Imagine your husband bought a gold necklace, and come Christmas, he presented it to you.
4. The necklace looks so fantastic that she can't help buying it.
5. Not only had you bought that necklace, but an expensive ring as well.
ring n.
1. When I found out who stole the ring, I would send him to prison immediately.
2. Before you have an operation, you have to take your ring off.
3. I didn't give the ring to you for the simple reason that I couldn't afford it.
4. Why don't you change into that ring.
5. This can give rise to curious situations,
		as it did in the case of my wife who was always dressed in the ring. 
background n.  background music
1. It's obvious that they provided us with wrong background music.
2. I am too embarrassed to invite her to dance with me in such background music.
3. The background music reminds me of the day when I got fired.
4. My wife complained that in front of the street, car noise is like background music.
5. This background music which I provided with gave me satisfaction a great deal.
velvet n.
1. We like these pictures in the same way that we like velvet curtains.
2. She was reluctant to offer us a velvet curtain.
3. People who do manual work often like to buy velvet curtains.
4. I am willing to sacrifice the vase for the velvet curtains.
5. Not only had my wife bought a velvet curtains, but she bought a toy for our child.
headlight n.
1. Not only is the right headlight broken, but the left one as well.
2. The right headlight turn out to be broken.
3. I am used to the broken headlight.
4. Equipped with the headlight, the bike was useful again.
5. Despite the fact that the headlights both are broken.
blare v.
1. The radio from my neighbor is alway blaring day and night.
2. The boy is always blaring for one cause or another.
3. I heard the radio blaring in the midnight.
4. I convinced that the radio was blaring last night.
5. There is a horn blaring at the entrance of the museum.
staff n.
1. The manager has give us a lot of encouragement in the staff meeting.
2. In the meantime, all staff was fast asleep.
3. All staff was put to shame by Mr. Leo, for he has sold a million worth of food.
4. The manager was disappointed to learn that his staff was arrested.
5. The managedr instructed his staff to stand their attention to him.
raid n.v.
1. This event takes its name from a raid.
2. It's you who are responsible for the raid, not him.
3. The gangsters of New York is planning a raid once more.
4. Let's suppose that a ganster is raiding us.
5. It is no use pretending that you hadn't raided the jewelry shop.
scramble v.  scrambled eggs
1. I noticed that my wife had made scrambled eggs.
2. My wife managed to make some scrambled eggs.
3. Seeing a policeman charging at them, they scrambled back into their car.
4. They scrambled back into the ambassador with someone firing a shot.
5. The scrambled eggs are popular with young people in China.
fantastic adj.  at a fantastic speed  That's fantastic
1. The velvet curtain looks so fantastic that my wife bought it at once.
2. The stories that he told us at the reception are fantastic.
3. You look fantastic. I almost didn't recoginize you.
4. Having a large circle of friends is fantastic.
5. You're also a huge fan of Knight, that's fantastic.
ashtray n.
1. You should quit smoking, for you smell look like an ashtray.
2. My mother threatened to throw away the ashtray.
3. You needn't have thrown away that ashtray.
4. The ashtray which belongs to me has been cleaned up.
5. I'm gonna send my friend a beautiful ashtray.
** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-10-29 Sun 20:29]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-29 Sun 12:08]
only just  Just a moment earlier
1. I've only just ran out of the petrol.
2. I've only just carried some fruits to the classroom. 
3. I've only just taught her pressing the button.
4. I've only just borrowed a book from the library.
5. We only just touched with each other.
come to a stop
1. The car came to a stop behind my house.
2. The car came to a shop in my courtyard.
3. The car came to a stop for the simple reason that a boy was in the middle of road. 
4. The car came to a stop and two women got off it.
5. When two detectives were waitting in front of the entrance, a car came to a stop.
be too busy doing sth. to do sth.
1. My wife is too busy watching drama to reply my message.
2. I am too busy studying English to play with my cat.
3. My parents were too busy making money to take charge of me.
4. The authorities are too busy holding the Games to keep order.
5. The cat was too busy eating food to notice me.
money + worth of + n.
1. They are millions of dollars worth of diamonds.
2. We couldn't afford the millions of yuan worth of house.
3. She gets a good salary
		for the simple reason that she has sold millions of dollars worth of foods.
4. She was fired. Despite the fact that she sold ten thousands of dollars worth of foods.
5. You luck dog. The thousands of dollars worth of diamonds is yours now.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-10-29 Sun 20:29]
** DONE Ask me if 写+读
CLOSED: [2023-10-29 Sun 20:34]
1. The famous arcade was near Piccaddilly. Where
	 Where was the famous arcade?
2. The arcade was almost empty. Why
	 Why was the arcade almost empty?
3. Mr. Taylor and two of his assistants had been working since eight o'clock. How long
	 How long had Mr. Taylor and two of his assistants been working?
4. They had just finished the window display. What
	 What had they just finished?
5. The silence was broken. How
	 How was the silence broken?
6. The car came to a stop outside the jeweller's. Where
	 Where did the car come to a stop?
7. The thieves had black stockings over their faces. What
	 What did the thieves have over their faces?
8. Mr. Taylor was upstairs. Where
	 Where was Mr. Taylor?
9. The thief noticed any pain. Why didn't
	 Why didn't the thief notice any pain?
10. The raid lasted three minutes. How long
		How long did the raid last?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-10-29 Sun 20:47]
A large car entered an arcade near Piccadilly
	and stopped outside a jeweller's.
Two thieves got out of the car
	and smashed the shop window.
The owner of the shop was upstairs at the time,
	so he threw furniture at the thieves
		hitting one of them with a heavy statue.
The raid lasted only three minutes and the thieves drove away.
Running after them, the owner threw ashtrays and vases,
	but the thieves got away, stealing thousands of pounds worth of diamonds.

** DONE tell the story 口语复述
CLOSED: [2023-10-29 Sun 20:51]
** composition 阅读 或 写作
Seeing the thieves' car join the traffic on Piccadilly,
	Mr. Taylor took a taxi and followed them.
The taxi driver drove at full speed when Mr. Taylor told him what had happened.
There wasn't too much traffic at this time of the morning
	so there was a mad chase through the streets of London.
For a short time, the thieves' car was on the wrong side of the road and hit another car,
	but it did not stop.
Two policemen in a police car watched in amazement as the two vehicles went past,
	both breaking the speed limit.
Lights on and horn blaring,
	the police car chased both the speeding cars.
Mr. Taylor's taxi stopped when the traffic lights turned red.
The thieves ignored the traffic lights and got away.
Meanwhile, the police caught up with the taxi at the traffic lights
	and the taxi driver was charged with speeding.
They refused to let the driver off, even though Mr.Taylor carefully explained the situation.
However, the police informed another police car of the chase
	and ten minutes later the thieves' car was found abandoned in a side street.
The thieves had escaped on foot and disappeared among the crowd.

** Topics for discussion
