#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 09 Flying cats
#+begin_verse
How do cats try to protect themselves when falling from great heights?

Cats never fail to fascinate human beings.
They can be friendly and affectionate towards humans,
	but they *lead mysterious lives* of their own as well.
They never become submissive like dogs and horses.
As a result, humans have learned to respect feline independence.
Most cats remain suspicious of humans all their lives.
One of the things that fascinates us most about cats is the popular belief
	that they have nine lives.
Apparently, there is *a good deal of* truth in this idea.
A cat's ability to survive falls *is based on* fact.

Recently
	the New York Animal Medical Centre *made a study of* 132 cats over *a period of* five months.
All these cats *had one experience in common*:
	they had fallen off high buildings, yet only eight of them *died from* shock or injuries.
Of course, New York is the ideal place for such an interesting study,
	because *there is no shortage of* tall buildings.
There are plenty of high-rise windowsills to fall from!
One cat, Sabrina, fell 32 storeys, yet only suffered from a broken tooth.
'Cats behave like well-trained paratroopers,' a doctor said.
*It seems that* the further cats fall, the less they *are likely to* injure themseleves.
In a long drop, they reach speeds of 60 miles an hour and more.
At high speeds, falling cats have time to relax.
They stretch out their legs like flying squirrels.
This increases their air-resistance and reduces the shock of impact when they hit the groud.
#+end_verse

** words
fascinate [ˈfæsɪneɪt] v. 迷住
affectionate [əˈfekʃənət] adj. 充满深情的
mysterious [mɪˈstɪəriəs] adj. 神秘的
submissive [səbˈmɪsɪv] adj. 服从的
feline [ˈfiːlaɪn] adj. 猫的
independence [ˌɪndɪˈpendəns] n. 独立的
high-rise [ˈhaɪ raɪz] adj. 高层的
windowsill [ˈwɪndəʊsɪl] n. 窗槛
paratrooper [ˈpærətruːpə(r)] n. 伞兵
squirrel [ˈskwɪrəl] n. 松鼠
air-resistance [rɪˈzɪstəns] n. 空气阻力
impact [ˈɪmpækt] n. 冲击力

** vocabulary
affectionate: loving
as a result: consequently
remain: continue to be
there is no shortage of: there are plenty of
behave: act
injure: harm
increases: raises
reduces: cuts down
** DONE 单词造句
CLOSED: [2023-11-04 Sat 20:47]
fascinate v.
1. The story never fails to fascinate me.
2. My cat never fails to fascinate me when I get home.
3. I've chased after a great many of women, everyone fascinates me like you.
4. I have never been fascinated by the drama.
5. What a cut cat. It fascinates me a lot.
affectionate adj.
1. My wife is always affectionate towards me.
2. When your wife is in difficulty, you should be affectionate towards her.
3. It's said that he gave her an affectionate kiss last night.
4. The affectionate kiss he gave me reminded me of my ex-boyfriend.
5. I attempted to give her an affectionate kiss.
mysterious adj.
1. The goddess lives a mysterious life for hundreds of years.
2. The police was told by a mysterious call that the plane was planted a bomb.
3. This mysterious ring may be connected to the history of Greek.
4. Now that we couldn't find the mysterious visitor, let's grab a coffee. 
5. The mysterious car went to the arcade at a fantastic speed.
submissive adj.
1. My wife is so submissive that she would obey my every word.
2. You will be disappointed to learn that teachers in China want their students to be submissive.
3. Every patient in the hospital must be submissive.
4. He is always following his boss like a submissive dog.
5. The boys who played truent from school are rarely submissive.
feline adj.
1. She claimed to have seen a lot of feline mummies in Egypt.
2. Your feline friend is smash paper to pieces in the kitchen.
3. My feline friend is said to have nine lives.
4. I spent a lot of time trainning my feline friend to open the door.
5. Somehow, my feline friend loves to eat scrambled eggs.
independence n.  gained its independence
1. I have gained my independence since I was 19 years old.
2. It's obvious that parents should allow their children some independence.
3. In America, their children often gain their independence when they are 18 years old.
4. I find out that I don't gain my independence.
5. I should have gained my independence.
high-rise adj.
1. It is disturbing to think that a plant may fall off high-rise buildings.
2. The journalist is gonna write an article on high-rise buildings.
3. Not only are there a lot of high-rise building, but they are beautiful as well.
4. Unfortunately, the high-rise building got fired last night.
5. This building is only half as high as that high-rise building.
windowsill n.
1. The cat is sleeping on the windowsill.
2. There is a pair of binoculars on the windowsill.
3. The windowsill which was painted last night is broken.
4. I'm making a discovery of the history of windowsills.
5. We didn't get enough money to paint the windowsill.
paratrooper n.
1. The paratrooper woke up with a start at midnight.
2. The paratrooper caught sight of his fiancee in ths sky.
3. The paratrooper is equal to deal with the task.
4. The paratrooper was injured for one cause or another.
5. The paratrooper claimed to have seen a monster in the desert.
squirrel n.
1. This convinced me that it was a squirrel.
2. I spotted a squirrel eating nuts which was sent from visitors.
3. I felt obliged to save this poor squirrel.
4. The squirrel clinging to bush charged at me this morning.
5. It is considered unlucky for people seeing a squirrel in Japan in the morning.
air-resistance n.
1. It's disturbing to think that the car's speed was reduced by air-resistance.
2. The pilot is accustomed to speed up without air-resistence. 
3. Was the car's speed reduced by air-resistance.
4. You live in a fantasy world where cars' speed are not reduced by air-resistance.
5. Air-resistance prevents flying cat from dieing from falling from high-rise buildings.
impact n.  have/make an impact on
1. His father has such an impact on him that he follows in his father's footstep.
2. Faker, the player, makes an impact on everyone in Korea.
3. He has an impact on us, for he succeeded in broking world records over and over again.
4. These pirate stories have an impact on people all over the world.
5. The big corporation does have an impact on the global market.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-04 Sat 21:34]
** DONE 自己讲语法
CLOSED: [2023-11-04 Sat 21:36]
the 比较级(eg. more) ..., the 比较级(eg.more) ...: 比较级在句子中做比较成分
yet... conj.: 表惊讶的转折
** 反复读例句 !!!
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-04 Sat 21:18]
lead a adj. life
1. If the operation succeeded, Carol would have been able to lead a normal life.
2. Joe has been leading a double life, for he never told his wife anything about his job.
3. So long as we don't get divorce, we will have a normal life.
4. Even though Ross got divorce three times, he attempts to lead a normal life.
5. The monster leads a mysterious life for hundreds of years.
learn to do sth.
1. Now that you learned to do it by yourself, you have the nerve to deal with the task.
2. My cousin learned to drive after she aborted.
3. If you are in difficulty, you should learn to ask your partner for help.
4. I learned to gain my independence when I was very young.
5. My father has an impact on me, I learned to do his job too.
a good deal of/a great deal of un.
1. I spent a good deal of time in my room writting postcards.
2. Despite the fact you caused a good deal of trouble, your father didn't get angry.
3. He made a good deal of money, yet he never returned money to his friends.
4. There is a good deal of truth in this idea.
5. Because I received a good deal of pocket money, I gave it to my parents for safekeeping.
be based on
1. All of these are based on the belief that we can get a good salary in the future.
2. This film is said to be base on a true story. 
3. This is based on the fact that my wife loves me.
4. This is based on the belief that Mr. Leo takes his job seriously. 
5. This is based on the fact that the U.S. gained its independence from England.
make a study of sth
1. I made a study of Primates, for I need to write an article on them.
2. He is too busy making a study of French Culture to notice his wife.
3. He has made a closely study of human nature.
4. So long as you made a study of this by yourself, you will have the nerve to deal with it.
5. I am making a studying of cats these days.
a period of + st.
1. He claimed to have lived in New Zealand for a period of time.
2. My wife spent a period of time keeping touch with her teacher which teaches her design course.
3. Mr. Alf led a double life for a period of time.
4. My aunt goes on vocation in Hawaii for a period of time every year.
5. He made every effort to keep the status quo for a period of time.
have sth. in common
1. We did have some experiences in common for a period of time.
2. It is disturbing to think that they have nothing in common.
3. They don't know each other, yet they have a lot of experiences in common.
4. They have a habit of swimming in common.
5. I don't think we have something in common.
died from(事故) / died of(病)
1. The authories claimed that only five men died from this air crush.
2. It is said that she died of a rare disease.
3. If you drove fast yesterday, you might have died from this accident too.
4. I regreted to inform you that you father has died of cancer.
5. He has died from the accident and there is nothing we can do about it.
there is no shortage of
1. There is no shortage of people in China who are willing to do this job.
2. There is no shortage of workers who take this seriously.
3. There is no shortage of movies which refer to the history of Greek.
4. There is no shortage of actors who stay out of limelight.
5. There is no shortage of concern that your wife gave you.
It seems that + ...
1. It seems that she has drunk a good deal of milk.
2. It seems that you need to keep the secret.
3. It seems that I have the privilege of meeting the queen.
4. It seems that everything has returned to normal.
5. It seems that she has made a sacrifice again.
be likely to do sth.
1. I'm likely to study abroad.
2. My cousin was likely to died of cancer.
3. She is likely to make a discovery of these ancient remains.
4. She is likely to raise enough money to have the clock repaired.
5. I'm likely to lead a normal life after this.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-04 Sat 21:36]
** DONE Ask me if 写+读
CLOSED: [2023-11-04 Sat 21:43]
1. Cats fascinate human beings. Why
	 Why do cats fascinate human beings?
2. Human beings have learned to respect them. Why
	 Why have human beings learned to respect them?
3. Most cats remain suspicious of humans. Why
	 Why do most cats remain suspicious of humans?
4. Cats have nine lives. How many
	 How many lives do cats have?
5. There is a great deal of truth in the idea. Why
	 Why is there a great deal of truth in the idea?
6. Eight of the cats died from shock. How many of the cats
	 How many of the cats died from shock?
7. One cat suffered from a broken tooth. What
	 What did one cat suffer from?
8. Cats behave like well-trained paratroopers. How
	 How do cats behave?
9. They reach speeds of 60 miles an hour and more. What speeds
	 What speeds do they reach?
10. This reduces the shock of impact. How
		How does this reduce the shock of impact?
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-04 Sat 21:51]
The New York Animal Medical Center made a study of 132 cats.
All these cats had fallen off high buildings,
	yet only eight of them died from shock or injuries.
One cat, Sabrina, fell 32 storeys but only suffered from a broken tooth.
When falling at speeds of 60 miles an hour, cats stretch out their legs,
	which increases air-resistence and reduces the shock of impact on hitting the ground.

** DONE tell the story 口语复述
CLOSED: [2023-11-04 Sat 21:55]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-04 Sat 21:58]
Human beings like to keep dogs and cats.
Dogs are submissive and faithful to their masters, but cats like to be independent.
Cats are especially lovable when they are still kittens.
As kittens they like to play by chasing anything that moves.
That's how they learn to hunt mice, birds, insects and other small creatures.
A lot of people keep cats so they can have a pet.
As kittens grow into cats, they like to stay indoors.
They like regular meals and enjoy sleeping in front of a nice fire.
However, they also like going out.
During the day time and at night they like to go hunting.
Sometimes during the night they have fights with other cats.
Cats are very clean animals.
You often see them washing themselves.
Human beings are fascinated by their behaviour because cats are domestic animals,
	while at the same time they enjoy their independence.
** Topics for discussion
