#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 01 First thing in the morning
#+begin_verse
Dan's alarm clock rings and he wakes up.
He gets out of bed.
He goes into the bathroom.

After using the toilet and flushing it, he washes his hands.
He brushes his teeth, shaves, and takes a shower.
He dries himself off with a towel.
Then he brushes his hair.
He gets dressed.
He makes breakfast and eats it.
Then he leaves the apartment.
#+end_verse
** expression
bathroom [ˈbæθˌrum]: n. a room where there is a bath or ↑shower, a ↑basin, and sometimes a toilet浴室
toilet [ˈtɔɪlət]: n. a large bowl that you sit on to get rid of waste liquid or waste matter from your body抽水马桶
flush [flʌʃ]: v. if you flush a toilet, or if it flushes, you make water go through it to clean it冲洗
wash [wɑʃ]: v. to clean something using water and a type of soap洗
brush [brʌʃ]: v. an object that you use for cleaning, painting, making your hair tidy etc, made with a lot of hairs, ↑bristles, or thin pieces of plastic, fastened to a handle ⇨ broom刷, 掸, 拂
shave [ʃeɪv]: v. to cut off hair very close to the skin, especially from the face, using a ↑razor剃, 刮
--------------------
alarm clock: 闹钟
get out of bed: 起床
dry sb./sth. off: 烘干,弄干某人某物
get dressed: 穿衣服
make breakfast/lunch/dinner: 做早餐
** sentence
bathroom [ˈbæθˌrum]: n. a room where there is a bath or ↑shower, a ↑basin, and sometimes a toilet浴室
- Who's in the bathroom?
- It is in the bathroom that you murdered your wife who was taking a shower.
- My cat is forbidden to enter in the bathroom.
toilet [ˈtɔɪlət]: n. a large bowl that you sit on to get rid of waste liquid or waste matter from your body抽水马桶
- The cute boy fed his father with a cup of water which was from the toilet.
- My wife is complaining that I messed up the toilet over and over again.
- When Taiwanese actors come to the mainland, they always complain about the dirty toilets.
flush [flʌʃ]: v. if you flush a toilet, or if it flushes, you make water go through it to clean it冲洗
- I do think the cask needs flushing now.
- If you hadn't forgotten to flush the barrel, we wouldn't have been punished by our master.
- I am flushing the toilet under the command of our boss.
wash [wɑʃ]: v. to clean something using water and a type of soap洗
- Obviously, he has a difficult time in washing his hands full of a special kind of grease.
- On hitting my hands bitterly, my father began to wash my mud-filled hands.
- We call for your washing hands before you perform experiments in our laboratory.
brush [brʌʃ]: v. an object that you use for cleaning, painting, making your hair tidy etc, made with a lot of hairs, ↑bristles, or thin pieces of plastic, fastened to a handle ⇨ broom刷, 掸, 拂
- My wife spent half a morning brushing my desktop when we moved to our new house.
- The man is brushing his precious car with great care.
- If you brush my back, I will reward you with 1 yuan. My grandfather used to say that to me.
shave [ʃeɪv]: v. to cut off hair very close to the skin, especially from the face, using a ↑razor剃, 刮
- My wife pointed at my face pointing out that I forgot to shave in the morning.
- In fact, we are capable to shave our cat without hurting her.
- People in the community are appalled at the fact that someone had shaved the stray dog in the cold winter.
--------------------
alarm clock: 闹钟
- Don't forget to set the alarm clock, you have a driver test tomorrow.
- Because of being late for school, the grandson of our village head asked for an alarm clock.
- No one could account for the fact that the alarm clock worth of 100 dollars has broken down.
get out of bed: 起床
- I got out of bed late on Saturday feeling extremely hungry.
- When my aunt knocked at my door, I still hadn't got out of bed.
- On getting out of bed, he was given a birthday surprise when his family gathered round to celebrate it.
dry sb./sth. off: 烘干,弄干某人某物
- You haven't dried your body off again, you foot is still wet.
- Dry the cup off, otherwise your stomach may turn when you drink milk.
- My wife instructed me to dry off the desktop and fill bowls with rice.
get dressed: 穿衣服
- Wait for a minute, I am still getting dressed. I said in a loud voice.
- The vicious king sentenced his wife to death while getting dressed.
- The dog must have been in the possession of a master, for he gets dressed well.
make breakfast/lunch/dinner: 做早餐
- Tired of making breakfast, he goes to restaurant every morning.
- Tired of making breakfast, she asked her wife to make it on his own.
- Tired of making breakfast, she lost her temper and yelled at her husband.
** sentence2
bathroom [ˈbæθˌrum]: n. a room where there is a bath or ↑shower, a ↑basin, and sometimes a toilet浴室
- Who's in the bathroom?
- It is in the bathroom that you murdered your wife who was taking a shower.
- My cat is not allowed to enter the bathroom.
toilet [ˈtɔɪlət]: n. a large bowl that you sit on to get rid of waste liquid or waste matter from your body抽水马桶
- The cute boy fed his father with a cup of water which was from the toilet.
- My wife is complaining that I messed up the toilet over and over again.
- When Taiwanese actors come to the mainland, they always complain about the dirty toilets.
flush [flʌʃ]: v. if you flush a toilet, or if it flushes, you make water go through it to clean it冲洗
- I do think the cask needs flushing now.
- If you hadn't forgotten to flush the barrel, we wouldn't have been punished by our master.
- I am flushing the toilet under the command of our boss.
wash [wɑʃ]: v. to clean something using water and a type of soap洗
- Obviously, he has a difficult time washing his hands full of a special kind of grease.
- On hitting my hands bitterly, my father began to wash my mud-filled hands.
- We call for you to wash your hands before you perform experiments in our laboratory.
brush [brʌʃ]: v. an object that you use for cleaning, painting, making your hair tidy etc, made with a lot of hairs, ↑bristles, or thin pieces of plastic, fastened to a handle ⇨ broom刷, 掸, 拂
- My wife spent half a morning brushing my desktop when we moved to our new house.
- The man is brushing his precious car with great care.
- If you brush my back, I will reward you with 1 yuan. My grandfather used to say that to me.
shave [ʃeɪv]: v. to cut off hair very close to the skin, especially from the face, using a ↑razor剃, 刮
- My wife pointed at my face pointing out that I forgot to shave in the morning.
- In fact, we are capable of shaving our cat without hurting her.
- People in the community are appalled at the fact that someone had shaved the stray dog in the cold winter.
--------------------
alarm clock: 闹钟
- Don't forget to set the alarm clock, you have a driver test tomorrow.
- Because of being late for school, the grandson of our village head asked for an alarm clock.
- No one could account for the fact that the alarm clock worth 100 dollars has broken down.
get out of bed: 起床
- I got out of bed late on Saturday feeling extremely hungry.
- When my aunt knocked at my door, I still hadn't gotten out of bed.
- On getting out of bed, he was given a birthday surprise when his family gathered around to celebrate it.
dry sb./sth. off: 烘干,弄干某人某物
- You haven't dried your body off again, your foot is still wet.
- Dry the cup off, otherwise your stomach may turn when you drink milk.
- My wife instructed me to dry off the desktop and fill bowls with rice.
get dressed: 穿衣服
- Wait for a minute, I am still getting dressed. I said in a loud voice.
- The vicious king sentenced his wife to death while getting dressed.
- The dog must have been in the possession of a master, for he gets dressed well.
make breakfast/lunch/dinner: 做早餐
- Tired of making breakfast, he goes to the restaurant every morning.
- Tired of making breakfast, she asked her wife to make it on his own.
- Tired of making breakfast, she lost her temper and yelled at her husband.
