#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 02 Brushing your teeth and flossing
#+begin_verse
Jenny runs some water over her toothbrush.
She squeezes toothpaste onto her toothbrush.
She moves her toothbrush up and down, and back and forth.
To rinse her mouth,
	she takes some water, swishes it back and forth in her mouth and spits it into the sink.
She rinses off her toothbrush.
Then she puts it back in the toothbrush rack.

She flosses her teeth by pulling out a long piece of floss,
	slipping it between her teeth, and moving it back and forth and up and down.
#+end_verse
** expression
squeeze [skwiz]: v. to press something firmly together with your fingers or hand压榨, 挤
toothpaste [ˈtuθˌpeɪst]: n. a thick substance that you use to clean your teeth牙膏
toothbrush [ˈtuθˌbrʌʃ]: n. a small brush that you use for cleaning your teeth牙刷
swish [swɪʃ]: v. to move or make something move quickly through the air with a quiet sound带着嗖嗖声挥动
spit [spɪt]: v. to force a small amount of ↑saliva (=the liquid in your mouth) out of your mouth吐(唾沫), 吐出
sink [sɪŋk]: n. a large open container that you fill with water and use for washing yourself, washing dishes etc ⇨ basin水槽, 水池
rack [ræk]: n. a fror shelf that has bars or hooks on which you can put things架子
floss [flɑs]: v.n. to clean between your teeth using floss牙线/牙线清洁
--------------------
run some water (over sth.): 放水流过某物
up and down: 上上下下地
back and forth: 来来回回地
rinse [rɪns] off: 冲洗
pull out: 拨出/取出
** sentence
squeeze [skwiz]: v. to press something firmly together with your fingers or hand压榨, 挤
- He squeezed it so hard that the toothpaste has been used up. 
- If you squeezed it hard, you would still have enough toothpaste to brush your teeth.
- I squeeze frequently, Chandler replied to Phobee in an ironically voice.
toothpaste [ˈtuθˌpeɪst]: n. a thick substance that you use to clean your teeth牙膏
- The toothpaste is on promotion and its price has been reduced to 10% of normal.
- My wife was tempted in buying the toothpaste on promotion in the mall.
- I have no intention of purchasing any toothpaste, so you can stop assailed me at midnight. 
toothbrush [ˈtuθˌbrʌʃ]: n. a small brush that you use for cleaning your teeth牙刷
- I asked my aunt why she had used my toothbrush in the morning.
- The toothbrush on the base of which the word Hui was inscribed must be my sister's.
- My father thrusted a toothbrush into my hands when I was leaving the apartment.
swish [swɪʃ]: v. to move or make something move quickly through the air with a quiet sound带着嗖嗖声挥动
- Swishing some water back and forth in my mouth, I feel less spicy.
- Swishing some water back and forth in your mouth will relieve your sense of spicy.
- While swishing some water back and forth in his mouth, the water burst out on the desktop.
spit [spɪt]: v. to force a small amount of ↑saliva (=the liquid in your mouth) out of your mouth吐(唾沫), 吐出
- If you spit in public in the street, you will be fined 50 yuan.
- My wife is developing a fever and spitting a lot this morning.
- I can't become comfortable with your spitting in public.
sink [sɪŋk]: n. a large open container that you fill with water and use for washing yourself, washing dishes etc ⇨ basin水槽, 水池
- The plates are piled up high in the sink.
- The customer lodged a complain that flies took possession of our sinks.  
- The ants swarmed upon the meat in the sink.
rack [ræk]: n. a fror shelf that has bars or hooks on which you can put things架子
- My wife insisted on setting up a rack in front of the sink. 
- You shoule put your toothbursh back on the toothbrush rack.
- As long as the rack is broken, the wall will begin to be rotten.
floss [flɑs]: v.n. to clean between your teeth using floss牙线/牙线清洁
- He developed a relationship with a girl who flosses her teeth after lunch.
- The butcher has a habit of flossing his teeth after taking a shower.
- Consequently, I forgot to floss my teeth before I left the apartment.
--------------------
run some water (over sth.): 放水流过某物
- The peasants succeeded in running some water over their fields to get a good harvest.
- All you need to do is just to run some water through your cup, and you failed.
- If you kept running water, I would tell our parents you have wasted a lot of water.
up and down: 上上下下地
- You should brush your teeth up and down, otherwise they wouldn't be clean.
- When I brushed my teeth up and down, a woman went into the bathroom and took a piss.
- Don't shave up and down, or you will hurt your face carelessly.
back and forth: 来来回回地
- My teacher instructed me to read the book back and forth until I recited it.
- My neighbor below stairs lodged a complaint that our cat often runs around back and forth at midnight.
- Obviously, I received a warm welcome and my dog walked around me back and forth.
rinse [rɪns] off: 冲洗干净
- The cat is full of urine of rats, we need to rinse her off.
- I don't want to park my car in the basement, the rain will rinse off it.
- All sins you committed will be rinsed off in the fire.
pull out: 拨出/取出
- Pulling out a stick, he threatened to hit his child who was unwilling to do house chores.
- Pulling out a stick, he fiercely hit the face of the slave and ordered him to do house chores.
- Pulling out a piece of floss, the doctor flosses his broken teeth with great care.
** sentence2
squeeze [skwiz]: v. to press something firmly together with your fingers or hand压榨, 挤
- He squeezed it so hard that the toothpaste had been used up. 
- If you squeezed it hard, you would still have enough toothpaste to brush your teeth.
- I squeeze frequently, Chandler replied to Phobee in an ironic voice.
toothpaste [ˈtuθˌpeɪst]: n. a thick substance that you use to clean your teeth牙膏
- The toothpaste is on promotion and its price has been reduced to 10% of normal.
- My wife was tempted into buying toothpaste on promotion in the mall.
- I have no intention of purchasing any toothpaste, so you can stop assailing me at midnight. 
toothbrush [ˈtuθˌbrʌʃ]: n. a small brush that you use for cleaning your teeth牙刷
- I asked my aunt why she had used my toothbrush in the morning.
- The toothbrush on the base of which the word Hui was inscribed must be my sister's.
- My father thrust a toothbrush into my hands when I was leaving the apartment.
swish [swɪʃ]: v. to move or make something move quickly through the air with a quiet sound带着嗖嗖声挥动
- Swishing some water back and forth in my mouth, I feel less spicy.
- Swishing some water back and forth in your mouth will relieve your sense of spicy.
- While swishing some water back and forth in his mouth, the water burst out on the desktop.
spit [spɪt]: v. to force a small amount of ↑saliva (=the liquid in your mouth) out of your mouth吐(唾沫), 吐出
- If you spit in public in the street, you will be fined 50 yuan.
- My wife is developing a fever and spitting a lot this morning.
- I can't become comfortable with your spitting in public.
sink [sɪŋk]: n. a large open container that you fill with water and use for washing yourself, washing dishes etc ⇨ basin水槽, 水池
- The plates are piled up high in the sink.
- The customer lodged a complaint that flies took possession of our sinks.  
- The ants swarmed upon the meat in the sink.
rack [ræk]: n. a fror shelf that has bars or hooks on which you can put things架子
- My wife insisted on setting up a rack in front of the sink. 
- You should put your toothbrush back on the toothbrush rack.
- As long as the rack is broken, the wall will begin to be rotten.
floss [flɑs]: v.n. to clean between your teeth using floss牙线/牙线清洁
- He developed a relationship with a girl who flosses her teeth after lunch.
- The butcher has a habit of flossing his teeth after taking a shower.
- Consequently, I forgot to floss my teeth before I left the apartment.
--------------------
run some water (over sth.): 放水流过某物
- The peasants succeeded in running some water over their fields to get a good harvest.
- All you need to do is just to run some water through your cup, but you failed.
- If you kept running water, I would tell our parents you have wasted a lot of water.
up and down: 上上下下地
- You should brush your teeth up and down, otherwise they won't be clean.
- When I brushed my teeth up and down, a woman went into the bathroom and took a piss.
- Don't shave up and down, or you will hurt your face carelessly.
back and forth: 来来回回地
- My teacher instructed me to read the book back and forth until I recited it.
- My neighbor below stairs lodged a complaint that our cat often runs around back and forth at midnight.
- Obviously, I received a warm welcome and my dog walked around me back and forth.
rinse [rɪns] off: 冲洗干净
- The cat is full of the urine of rats, we need to rinse her off.
- I don't want to park my car in the basement, the rain will rinse off it.
- All sins you committed will be rinsed off in the fire.
pull out: 拨出/取出
- Pulling out a stick, he threatened to hit his child who was unwilling to do house chores.
- Pulling out a stick, he fiercely hit the face of the slave and ordered him to do house chores.
- Pulling out a piece of floss, the doctor flosses his broken teeth with great care.
