#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 04 Getting Dressed
#+begin_verse
Tom puts on some underwear, a T-shirt, some socks, some pants, and a shirt.

Tom steps into his pants, then he pulls them up.
He fastens the waistband and zips up the fly.
He slips a belt through the belt loops and buckles it.

Tom slips an arm into each sleeve.
He buttons the shirt and the cuffs.
He straightens his collar.
He tucks his shirt into his pants.
#+end_verse
** expression
fasten [ˈfæs(ə)n]: v. to join together the two sides of a coat, shirt, bag etc so that it is closed SYN do up OPP unfasten扣紧
waistband [ˈweɪs(t)ˌbænd]: n. the part of a skirt, trousers etc that fastens around your waist腰带
fly [flaɪ]: n. TROUSERS especially American English (also flies [plural] British English) the part at the front of a pair of trousers which you can open前档开口
loop [lup]: n. SHAPE OR LINE a shape like a curve or a circle made by a line curving back towards itself, or a piece of wire, string etc that has this shape环
buckle [ˈbʌk(ə)l]: v. to fasten a buckle, or be fastened with a buckle扣住
button [ˈbʌt(ə)n]: v. (also button up) to fasten clothes with buttons, or to be fastened with buttons扣住
cuff [kʌf]: n. American English a narrow piece of cloth turned upwards at the bottom of a trouser leg SYN turn-up British English袖口
straighten [ˈstreɪt(ə)n]: v. (also straighten out) to become straight, or to make something straight(使)弄直, 伸直
tuck [tʌk]: v. to push something, especially the edge of a piece of cloth or paper, into or behind something so that it looks tidier or stays in place挤进, 塞
--------------------
put on: 穿上
step into pants: 伸进裤子里
pull pants up: 拉起裤子
zip up/down the fly: 拉上拉链
