#+OPTIONS: \n:t num:nil html-postamble:nil

* task9-prereading 泛读实战2
材料: Santrock,J.W.(2017). Educational psychology 6th. McGraw-Hill Education.
1. task8 课前作业再来(体验很重要，有1章就有30章)
2. 制定阅读+听力的学习计划 (具体;6个月内;挑战性)
3. 回答如下问题(汉语) : 涉及您不适或者隐私的部分可以不发出来。
	 - What's most important to you in your life?
	 - Why do you care about those things?
	 - Do you have any long-term goals?
	 - Why are these goals important to you?
	 - What does it mean to have a good life?
	 - What does it mean to be a good person? If you were looking back on your life now, how would you like to be remembered?
	 - 以上这些问题与雅思托福考试的关系? 与提升英语水平的关系?
4. 泛读chapter 13 MOTIVATION,TEACHING,ANDLEARNING 中第二部分Achievement Processes ，第四部分选读部分。
	 算算大概等于做了几套真题阅读?
	 先完成再完美，不要记录单词含义，不要摘抄习惯用法，不要造句。
5. 练习skimming/scanning/summary/段首尾/Features/1.5h/阅读速度。
6. 记录下实战中的所有问题或困惑。
7. 阅读完请判断某水1中教育模式的利弊。
8. [选修] 按照今天提供的申请学校的思路，去查找目标学校，学完立刻实践，否则容易忘。


** 1. task8 课前作业再来(体验很重要，有1章就有30章)
** 2. 制定阅读+听力的学习计划 (具体;6个月内;挑战性)
本人上班族, 出门8点25, 到家晚上8点,双休.
--------------------名词解释
空时: 上班没工作时
黄金时间: 8-11点当中的两个小时
C1,2: Cambridge grammar 1,2
--------------------时间规划
不论工作忙或空:
	1. 早晨 20遍, 中午 10遍, 晚上跟读20遍, NCE2,3 / C1, 2/ 习惯用法造句
	2. 黄金时间: ielts课程/NCE2,3/humans of NewYork
空时: 1-5是配合黄金时间任务的作业,6-~看心情
	1. Topic
	2. Cambridge grammar 1,2
	3. ielts作业
	4. 习惯用法整理到文件中
	5. 习惯用法造句
	6. 泛读What Smart Students know?/Critical Thinking/...
	7. 刷reddit
	8. 精读美国读者
--------------------原则		 
原则:
	- 每日跟读必做
	- IELTS是第一优先级,黄金时间做
	- NCE2,3是第二优先级,黄金时间做,并且围绕NCE2,3,做对应其他所有的作业
	- 让自己围绕在英文世界
--------------------时间预估
时间估算: 6 * 4 = 24周
	- IELTS 学3周 剩21周
	- NCE2 学30课(已经完成66课) 5周 剩16周
	- NCE3 学27课 13周 剩3周
	- Humans of NewYork 学50课 3周 剩-1周
	- 两月一本泛读,预计能完成泛读3本

** 3. 回答如下问题(汉语) : 涉及您不适或者隐私的部分可以不发出来。
- What's most important to you in your life?
	幸福
- Why do you care about those things?
	我想让自己和身边的人过得更加幸福.
- Do you have any long-term goals?
	- 成为好丈夫,好父亲,好儿子和好朋友
	- 成为一个Stoics
	- 成为一个计算机科学家
	- 拥有批判性思维和逻辑推理的能力
	- 成为一个通才:方法论~进化心理学...这些都能掌握大道理,并且用来解决实际的问题
- Why are these goals important to you?
	+ 成为好丈夫,好父亲,好儿子和好朋友 我想让我爱的人也拥有幸福
	+ 成为计算机科学家,首先编程本身非常有趣,第二能够解决我和家人的生存问题
	+ Stoics: 清晰看到can和can't的那道界限,在内心当中真正的拥有幸福
	+ 批判性思维: 把纷扰地世界看的真切明白,做出正确行为
	+ 通才...解决实际的问题
- What does it mean to have a good life?
	他们都导向幸福,幸福就是好的生活.
- What does it mean to be a good person? If you were looking back on your life now, how would you like to be remembered?
	对身边的人和对自己都好的人,叫做好人.
	我希望我的孩子,记住我是他的好父亲;我的老婆,记住我是她的好丈夫;我的朋友,记得我是他们的好朋友.
- 以上这些问题与雅思托福考试的关系? 与提升英语水平的关系?
	这些事情都需要能力,需要从书中获取,然后在实践慢慢熟练.
	我需要提升英语,才能从以英文为载体的文本~媒体中获取相应的知识.
	然后随便考个雅思???

** 4. 泛读chapter 13 MOTIVATION,TEACHING,ANDLEARNING 中第二部分Achievement Processes ，第四部分选读部分。
完成

** 5. 练习skimming/scanning/summary/段首尾/Features/1.5h/阅读速度。
完成

** 6. 记录下实战中的所有问题或困惑。
1. 脑海会由英文翻译成中文的,没法用英语思考,怎么样才能用英语思考.
	 比如:1+2=3,在脑子是一加二等于,而不是one plus two equals three.
2. 翻英英字典时,会忍不住查中文意思,有时候会尝试自己用中文代换英英翻译的句子,是否有害?
	 比如: alienate的英文解释是 to do something that makes someone unfriendly or unwilling to support you.
				会忍不住翻译成中文"疏远",或者忍不住去看中文解释
3. 想要应用泛读的内容,是否需要和北极熊一样50遍?

** 7. 阅读完请判断某水1中教育模式的利弊。
利: 高考高分,也许能上个985/211,也有的可能成为蛊王
弊: 往后余生,可能都在治愈自己的痛苦.仿佛把一声的动力都用完了.

按书中的解释:
?水1中完全是extrinsic motivation: 通过老师的奖励或惩罚来实现控制他们,这样会几乎抹杀掉了自己Intrinsic motivation.
他们没有 Long-Term Goals,只有Challenging Goals.
也没有锻炼和发展自己延迟满足感的机会.
他们也没有Planning and Self-Monitoring,完全靠外部的监督
他们的VALUES是歪曲的,他们的PURPOSE只有高考.

** 8. [选修] 按照今天提供的申请学校的思路，去查找目标学校，学完立刻实践，否则容易忘。
