#+OPTIONS: \n:t
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil

** Children’s Engineering Workshops.
1: Hello. Children’s Engineering Workshops.

2: Oh hello.
I wanted some information about the workshops in the school holidays.

1: Sure.

2: I have two daughters who are interested.
The younger one’s Lydia, she’s four
– do you take children as young as that?

1: Yes, our Tiny Engineers workshop is for four to five-year-olds.

2: What sorts of activities do they do?

1: All sorts.
For example, they work together to design a special cover that goes round an egg,
	so that when it’s inside they can drop it from a height and it doesn’t break.
Well, sometimes it does break
	but that’s part of the fun!

2: Right. And Lydia loves building things.
Is there any opportunity for her to do that?

1: Well, they have a competition to see who can make the highest tower.
You’d be amazed how high they can go.

2: Right.

1: But they’re learning all the time as well as having fun.
For example, one thing they do is to design and build a car that’s attached to a balloon,
	and the force of the air in that actually powers the car
	and makes it move along.
They go really fast too.

2: OK, well, all this sounds perfect.

2: Now Carly, that’s my older daughter,
		has just had her seventh birthday,
	so presumably she’d be in a different group?

1: Yes, she’d be in the Junior Engineers.
That’s for children from six to eight.

2: And do they do the same sorts of activities?

1: Some are the same, but a bit more advanced.
So they work out how to build model vehicles, things like cars and trucks,
	but also how to construct animals using the same sorts of material and technique,
	and then they learn how they can program them and make them move.

2: So they learn a bit of coding?

1: They do.
They pick it up really quickly.
We’re there to help if they need it, but they learn from one another too.

2: Right. And do they have competitions too?

1: Yes, with the Junior Engineers,
	it’s to use recycled materials like card and wood to build a bridge,
		and the longest one gets a prize.

2: That sounds fun.
I wouldn’t mind doing that myself!

1: Then they have something a bit different,
	this is from Laokaoya website,
	which is to think up an idea for a five-minute movie and then film it,
	using special animation software.
You’d be amazed what they come up with.

2: And of course, that’s something they can put on their phone
	and take home to show all their friends.

1: Exactly.
And then they also build a robot in the shape of a human,
	and they decorate it
	and program it
		so that it can move its arms and legs.

2: Perfect.
	So, is it the same price as the Tiny Engineers?

1: It’s just a bit more: £50 for the five weeks

2: And are the classes on a Monday, too?

1: They used to be,
	but we found it didn’t give our staff enough time to clear up after the first workshop,
	so we moved them to Wednesdays.
The classes are held in the morning from ten to eleven.

2: OK. That’s better for me actually.
And what about the location?
Where exactly are the workshops held?


1: They’re in building 10A – there’s a big sign on the door,
	you can’t miss it,
	and that’s in Fradstone Industrial Estate.

2: Sorry?

1: Fradstone – that’s F-R-A-D-S-T-O-N-E

2: And that’s in Grasford, isn’t it?

1: Yes, up past the station.

2: And will I have any parking problems there?

1: No, there’s always plenty available.
So would you like to enrol Lydia and Carly now?

2: OK

1: So can I have your full name …
