#+OPTIONS: \n:t num:nil html-postamble:nil
* Task5 精听+精读 听力满分

** 一考
1.
	 F
2. publication
	 T
3. modern
	 F
4. model
	 F
5. noble
	 F
6. capitalism
	 F
7.
	 F
8.
	 F
9.
	 F
10. rules
		F

** 二考
9
1. practical
2. publication
3. choices
4. transformations
	 F negative
5. play
6. capitalism
7. depression
8. logic
9. opportunity
10. practices

		
** 三靠
1. practical
2. publication
3. choices
4. negetive
5. play
6. capitalism
7. depression
8. logic
9. opportunity
10. practice

** Stoicism
Ancient philosophy is not just about talking or lecturing,
	or even reading long, dense books.
In fact, it is something people have used throughout history
	– to solve their problems
		and to achieve their greatest triumphs.

Specifically, I am referring to Stoicism,
	which, in my opinion, is the most practical of all philosophies
		and therefore the most appealing.
Stoicism was founded in Ancient Greece by Zeno of Citium in the early 3rd century BC,
	but was practised by the likes of Epictetus, Cato, Seneca and Marcus Aurelius.
Amazingly, we still have access to these ideas,
	despite the fact that the most famous Stoics never wrote anything down for publication.
Cato definitely didn’t.
Marcus Aurelius never intended his Meditations to be anything but personal.
Seneca’s letters were, well,
	letters and Epictetus’ thoughts come to us by way of a note-taking student.

Stoic principles were based on the idea
	that its followers could have an unshakable happiness in this life
		and the key to achieving this was virtue.
The road to virtue, in turn, lay in understanding
	that destructive emotions, like anger and jealousy, are under our conscious control
		– they don’t have to control us,
	because we can learn to control them.
In the words of Epictetus:
	“external events I cannot control,
		but the choices I make with regard to them.
	I do control”.

The modern day philosopher and writer Nassim Nicholas Taleb defines a Stoic as someone
	who has a different perspective on experiences
		which most of us would see as wholly negative;
	a Stoic “transforms fear into caution,
		pain into transformation,
		mistakes into initiation and desire into undertaking”.
Using this definition as a model,
	we can see that throughout the centuries Stoicism has been practised in more recent history
			by kings, presidents, artists, writers and entrepreneurs.

The founding fathers of the United States were inspired by the philosophy.
George Washington was introduced to Stoicism by his neighbours at age seventeen,
	and later, put on a play based on the life of Cato to inspire his men.
Thomas Jefferson kept a copy of Seneca beside his bed.

Writers and artists have also been inspired by the stoics.
Eugène Delacroix, the renowned French Romantic artist
	(known best for his painting Liberty Leading the People) was an ardent Stoic,
	referring to it as his “consoling religion”.

The economist Adam Smith’s theories on capitalism were significantly influenced by the Stoicism
	that he studied as a schoolboy,
	under a teacher who had translated Marcus Aurelius works.

Today’s political leaders are no different,
	with many finding their inspiration from the ancient texts.
Former US president Bill Clinton rereads Marcus Aurelius every single year,
	and many have compared former President Obama’s calm leadership style to that of Cato.
Wen Jiabao the former prime minister of China,
	claims that Meditations is one of two books he travels with
	and that he has read it more than one hundred times over the course of his life.

Stoicism had a profound influence on Albert Ellis,
	who invented Cognitive Behaviour Therapy,
	which is used to help people manage their problems
		by changing the way that they think and behave.
It’s most commonly used to treat depression.
The idea is that we can take control of our lives
	by challenging the irrational beliefs
		that create our faulty thinking, symptoms and behaviours by using logic instead.

Stoicism has also become popular in the world of business.
Stoic principles can build the resilience and state of mind
		required to overcome setbacks
	because Stoics teach turning obstacles into opportunity.
A lesson every business entrepreneur needs to learn.

I would argue that studying Stoicism is as relevant today
	as it was 2,000 years ago,
	thanks to its brilliant insights into how to lead a good life.
At the very root of the thinking, there is a very simple way of living
	- control what you can and accept what you can’t.
This is not as easy as it sounds
	and will require considerable practice
	– it can take a lifetime to master.
The Stoics also believed the most important foundation
	for a good and happy life is not money, fame, power or pleasure,
	but having a disciplined and principled character
	– something which seems to resonate with many people today.

** all
- lecture: 说教
- dense: not able to understand things easily
- specifically: used when you are adding more exact information
- practical: effective
- appealing:  attractive or interesting
- meditations: serious thoughts about a particular subject
- virtue: moral goodness of character and behaviour
- destructive: causing damage to people or things
- conscious: awake and able to understand what is happening around you
- transformation: a complete change in someone or something
- initiation: the act of starting something such as an official process, a new plan etc
- undertaking: a promise to do something
- entrepreneur: someone who starts a new business or arranges business deals in order to make money, often in a way that involves financial risks
- ardent:  showing strong positive feelings about an activity and determination to succeed at it
- religion: a belief in one or more gods
- significantly: in an important way or to an important degree
- Former: previous
- Cognitive: related to the process of knowing, understanding, and learning something
- therapy: the treatment of an illness or injury over a fairly long period of time
- depression: a medical condition that makes you very unhappy and anxious and often prevents you from living a normal life
- irrational: not based on clear thought or reason
- symptom: something wrong with your body or mind which shows that you have a particular illness
- resilience: the ability to become strong, happy, or successful again after a difficult situation or event
- setback: a problem that delays or prevents progress, or makes things worse than they were
- obstacle: something that makes it difficult to achieve something
- relevant: directly relating to the subject or problem being discussed or considered

	
** expression
- achieve sb's triumphs
- the likes of ..:  is used to refer to people or things of a similar type or category
- have access to...:  possess the ability or permission to use, enter, or obtain something.
- come to sb.: emphasizes the process of understanding or realization
- in turn: used to explain how a series of actions or circumstances are interconnected
- with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."
- put on ...: mean to organize, present, or perform a show, event, or production.
- prime minister: the most important minister and leader of the government in some countries which have a parliament
- the course of ...: is used to describe the progression or development of something over a period of time.
- at the root of sth.: refers to the fundamental or foundational essence of a concept, idea, problem, or situation
- resonate with:  if something such as an event or a message resonates, it seems important or good to people, or continues to do this
- refer to sth as sth.: regard sth. as sth.

** grammar
- 同从
- 宾从
- with ... 独立主格

** questions while pre-reading
1. 即使跟读50之后,仍然没有看中文的感觉,好像差点什么
2. 跟读是不是练习由原来的拼音标成单词,变成直接读单词.
	 类似老外学中文,开始读字靠拼音,后面直接读一个字.
	 或者类似于游戏里面,由脑子里面想连招的一步步然后出手,变成不假思索的熟练连招.
3. 2考会不去听听力,而是靠自己回想
