#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 51 Reward for virtue

#+begin_verse
Why did Hugh's diet not work?

My friend, Hugh, has always been fat,
	but things got so bad recently that he decided to *go on a diet*.
He began his diet a week ago.
*First of all*, he *wrote out a long list of* all the foods which were forbidden.
The list included most of the things Hugh loves:
	butter, potatoes, rice, beer, milk, chocolate; and sweets.
Yesterday I *paid him a visit*.
I *rang the bell* and *was not surprised to see that* Hugh was still as fat as ever.
He led me into his room and hurriedly hid a large parcel under his desk.
*It was obvious that* he was very embarrassed.
When I asked him what he was doing,
	he smiled guiltily and then put the parcel on the desk.
He explained that his diet was so strict that he had to reward himself occasionally.
Then he showed me the contents of the parcel.
It contained five large bars of chocolate and three bags of sweets!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
