#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 55 Not a gold mine
#+begin_verse
What did the team find?

Dreams of finding lost treasure almost *came true* recently.
A new machine called 'The Revealer' has been invented
	and it has *been used to detect* gold which has been buried in the ground.
The machine was used *in a cave* *near the seashore*
	where -- it is said - pirates used to hide gold.
The pirates would often bury gold in the cave and then fail to collect it.
*Armed with the new machine*, a search party went into the cave hoping to find buried treasure.
The leader of the party was examining the soil near the entrance to the cave
	when the machine showed that there was gold under the ground.
Very excited, the party dug a hole two feet deep.
They finally found a small gold coin which was almost worthless.
The party then searched the whole cave thoroughly
	but did not find anything except an empty tin trunk.
In spite of this,
	many people *are confident that* 'The Revealer' may reveal *something of value* *fairly soon*.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
