#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 57 Can I help you, madam?
#+begin_verse
Did the woman get what she wanted?

A woman in jeans stood at the window of an expensive shop.
Though she hesitated for a moment,
	she finally went in and *asked to see* a dress that was in the window.
The assistant who served her did not like the way she was dressed.
Glancing at her scornfully, he told her that the dress was sold.
The woman walked out of the shop angrily and decided to punish the assistant next day.
She returned to the shop the following morning *dressed in* a fur coat,
	with a handbag in one hand and a long umbrella in the other.
After *seeking out* the rude assistant, she asked for the same dress.
Not realizing who she was, the assistant *was eager to serve* her this time.
With great difficulty, he climbed into the shop window to get the dress.
As soon as she saw it, the woman said she did not like it.
She enjoyed herself making the assistant bring almost everything in the window
	before finally buying the dress she had first asked for.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
