#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 64 The Channel Tunnel
#+begin_verse
Why was the first tunnel not completed?

In 1858, a French engineer, Aime Thome de Gamond,
	arrived in England with a plan for a twenty-one-mile tunnel under the English Channel.
He said that it would *be possible to build* a platform in the centre of the Channel.
This platform would *serve as* a port and a railway station.
The Tunnel would be well-ventilated if tall chimneys were built *above sea level*.
In 1860, *a better plan was put forward* by an Englishman, William Low.
He suggested that a double railway-tunnel should be built.
This would *solve the problem of ventilation*,
	for if a train entered this tunnel, it would draw in fresh air behind it.
Forty-two years later a tunnel was actually begun.
If, at the time, the British had not feared invasion, it would have been completed.
The world had to wait almost another 100 years for the Channel Tunnel.
It was officially opened on March 7, 1994,
	finally connecting Britain to the European continent.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
