
* Lesson 49 The end of a dream
#+begin_verse
How did the dream end?

*Tired of sleeping* on the floor,
	a young man in Teheran *saved up for years to buy* a real bed.
*For the first time in his life*,
	he became the proud owner of a bed which had springs and a mattress.
Because the weather was very hot,
	he carried the bed on to the roof of his house.
He slept very well for the first two nights,
	but on the third night, a storm blew up.
*A gust of wind swept* the bed off the roof and sent it crashing *into the courtyard* below.
The young man did not wake up until the bed had struck the ground.
Although the bed *was smashed to pieces*, the man was miraculously unhurt.
When he woke up, he was still on the mattress.
*Glancing at* the bits of wood and metal that lay around him,
	the man sadly picked up the mattress and carried it into his house.
After he had put it on the floor, he promptly *went to sleep* again.
#+end_verse

* Lesson 50 Taken for a ride
#+begin_verse
Why did the writer not get off the bus at Woodford Green?

I love travelling in the country, but I don't like losing my way.
I went on an excursion recently, but my trip took me longer than I expected.
'I'm going to Woodford Green,' I said to the conductor as I got on the bus,
	'but I don't know where it is.'
'I'll tell you where to get off,' answered the conductor.
I sat in the front of the bus to get a good view of the countryside.
After some time, the bus stopped.
Looking round, I realized with a shock that I was the only passenger left on the bus.
'You'll have to get off here,' the conductor said. 'This is as far as we go.'
'Is this Woodford Green?' I asked.
'Oh dear,' said the conductor suddenly. 'I forgot to put you off.'
'It doesn't matter,' I said. 'I'll get off here.'
'We're going back now,' said the conductor.
'Well, in that case, I *prefer to stay* on the bus,' I answered.
#+end_verse

* Lesson 51 Reward for virtue

#+begin_verse
Why did Hugh's diet not work?

My friend, Hugh, has always been fat,
	but things got so bad recently that he decided to *go on a diet*.
He began his diet a week ago.
*First of all*, he *wrote out a long list of* all the foods which were forbidden.
The list included most of the things Hugh loves:
	butter, potatoes, rice, beer, milk, chocolate; and sweets.
Yesterday I *paid him a visit*.
I *rang the bell* and *was not surprised to see that* Hugh was still as fat as ever.
He led me into his room and hurriedly hid a large parcel under his desk.
*It was obvious that* he was very embarrassed.
When I asked him what he was doing,
	he smiled guiltily and then put the parcel on the desk.
He explained that his diet was so strict that he had to reward himself occasionally.
Then he showed me the contents of the parcel.
It contained five large bars of chocolate and three bags of sweets!
#+end_verse

* Lesson 52 A pretty carpet

#+begin_verse
What is the writer's carpet made of?

We have just moved into a new house and I have been working hard all morning.
I have been trying to *get my new room in order*.
This has not been easy because I own over a thousand books.
*To make matters worse*, the room is rather small,
	so I have temporarily put my books on the floor.
At the moment, they cover *every inch of floor space*
	and I actually have to walk on them to get in or out of the room.
*A short while ago*, my sister *helped me to carry* one of my old bookcases up the stairs.
She went into my room and got a big surprise when she saw all those books on the floor.
'This is the prettiest carpet I have ever seen,' she said.
She *gazed at it* for some time then added, 'You don't need bookcases at all.'
'You can sit here *in your spare time* and read the carpet!'
#+end_verse

* Lesson 53 Hot snake

#+begin_verse
What caused the fire?

At last firemen have put out a big forest fire in California.
Since then, they have been trying to *find out* how the fire began.
Forest fires are often caused by broken glass
	or by cigarette ends which people carelessly *throw away*.
Yesterday the fireman examined the ground carefully, but were not able to find any broken glass.
They were also quite sure that a cigarette end did not start the fire.
This morning, however, a fireman accidentally *discovered the cause*.
He noticed *the remains of a snake*
	which was wound round the *electric wires* of a 16,000-volt power line.
In this way, he was able to *solve the mystery*.
The explanation was simple but very unusual.
A bird had snatched up the snake from the ground and then dropped it on to the wires.
The snake then wound itself round the wires.
When it did so, it sent sparks down to the ground and these immediately started a fire.
#+end_verse

* Lesson 54 Sticky fingers
#+begin_verse
What two interruptions did the writer have?

After breakfast, I *sent the children to school* and then I went to the shops.
It was still early when I returned home.
The children were at school, my husband was at work and the house was quiet.
So I *decided to make* some meat pies.
In a short time I *was busy mixing* butter and flour
	and my hands *were soon covered with sticky pastry*.
At exactly that moment, the telephone rang.
Nothing could have been more annoying.
I picked up the receiver between two sticky fingers
	and was dismayed when I *recognized the voice of Helen Bates*.
It *took me ten minutes to* *persuade her to ring* back later.
At last I *hung up* the receiver.
*What a mess*!
There was pastry on my fingers, on the telephone, and on the doorknobs.
I had no sooner got back to the kitchen than the doorbell rang loud enough to wake the dead.
This time it was the postman and he wanted me to *sign for a registered letter*!
#+end_verse

* Lesson 55 Not a gold mine
#+begin_verse
What did the team find?

Dreams of finding lost treasure almost *came true* recently.
A new machine called 'The Revealer' has been invented
	and it has *been used to detect* gold which has been buried in the ground.
The machine was used *in a cave* *near the seashore*
	where -- it is said - pirates used to hide gold.
The pirates would often bury gold in the cave and then fail to collect it.
*Armed with the new machine*, a search party went into the cave hoping to find buried treasure.
The leader of the party was examining the soil near the entrance to the cave
	when the machine showed that there was gold under the ground.
Very excited, the party dug a hole two feet deep.
They finally found a small gold coin which was almost worthless.
The party then searched the whole cave thoroughly
	but did not find anything except an empty tin trunk.
In spite of this,
	many people *are confident that* 'The Revealer' may reveal *something of value* *fairly soon*.
#+end_verse

* Lesson 56 Faster than sound!
#+begin_verse
How fast did the winning car go?

Once a year, a race is held for old cars.
A lot of cars entered for this race last year
	and there was a great deal of excitement just before it began.
One of the most handsome cars was a Rolls-Royce Silver Ghost.
The most unusual car was a Benz which had only three wheels.
Built in 1885, it was the oldest car taking part.
After a great many loud explosions, the race began.
Many of the cars *broke down* *on the course*
	and some drivers spent more time under their cars than in them!
A few cars, however, completed the race.
The winning car reached a speed of forty miles an hour - much faster than any of its rivals.
It sped downhill at the end of the race and its driver had a lot of trouble trying to stop it.
The race gave everyone *a great deal of* pleasure.
It *was very different from* modern car races but no less exciting.
#+end_verse

* Lesson 57 Can I help you, madam?
#+begin_verse
Did the woman get what she wanted?

A woman in jeans stood at the window of an expensive shop.
Though she hesitated for a moment,
	she finally went in and *asked to see* a dress that was in the window.
The assistant who served her did not like the way she was dressed.
Glancing at her scornfully, he told her that the dress was sold.
The woman walked out of the shop angrily and decided to punish the assistant next day.
She returned to the shop the following morning *dressed in* a fur coat,
	with a handbag in one hand and a long umbrella in the other.
After *seeking out* the rude assistant, she asked for the same dress.
Not realizing who she was, the assistant *was eager to serve* her this time.
With great difficulty, he climbed into the shop window to get the dress.
As soon as she saw it, the woman said she did not like it.
She enjoyed herself making the assistant bring almost everything in the window
	before finally buying the dress she had first asked for.
#+end_verse

* Lesson 58 A blessing in disguise?
#+begin_verse
Why does the vicar refuse to cut down the tree?

The tiny village of Frinley is said to possess a 'cursed tree'.
Because the tree was mentioned in a newspaper, the number of visitors to Frinley has now increased.
The tree was planted near the church fifty years ago,
	but it is only in recent years that it has gained an evil reputation.
It is said that if anyone touches the tree, he will have bad luck;
	if he picks a leaf, he will die.
Many villagers believe that the tree has already claimed *a number of* victims.
The vicar has been asked to have the tree cut down, but so far he has refused.
He has *pointed out that* the tree is a useful *source of income*,
	as tourists have been coming from all parts of the country to see it.
In spite of all that has been said,
	the tourists have been picking leaves and cutting their names on the tree-trunk.
So far, not one of them has been struck down by sudden death.
#+end_verse

* Lesson 59 In or out?
#+begin_verse
Why did Rex run away?

Our dog, Rex, used to sit outside our front gate and bark.
Every time he wanted to come into the garden he would bark until someone opened the gate.
As the neighbours *complained of* the noise,
	my husband *spent weeks training him to press* his paw on the latch to let himself in.
Rex soon became an expert at opening the gate.
However, when I was going out shopping last week,
	I noticed him in the garden near the gate.
This time he was barking so that someone would let him out!
Since then, he has developed another bad habit.
As soon as he opens the gate from the outside,
	he comes into the garden and waits until the gate shuts.
Then he sits and barks until someone lets him out.
After this he immediately lets himself in and begins barking again.
Yesterday my husband removed the gate and Rex got so annoyed we have not seen him since.
#+end_verse

* Lesson 60 The future
#+begin_verse
Does what Madam Bellinsky said come true?

At a village fair, I decided to visit a fortune-teller called Madam Bellinsky.
I went into her tent and she told me to sit down.
After I had given her some money, she looked into a crystal ball and said:
'*A relation of yours* is coming to see you.
She will be arriving this evening and intends to stay for a few days.
The moment you leave this tent, you will get a big surprise.
A woman you know well will rush towards you.
She will speak to you	and then she will lead you away from this place.
That is all.'

As soon as I went outside,
	I forgot all about Madam Bellinsky because my wife hurried towards me.
'Where have you been hiding?' she asked impatiently.
'Your sister will be here in less than an hour and we must be at the station to meet her.
We are late already.'
As she walked away,	I followed her out of the fair.
#+end_verse

* Lesson 61 Trouble with the Hubble
#+begin_verse
What is the special importance of a telescope in space?

The Hubble telescope was launched into space by NASA on April 20, 1990
	at a cost of over a billion dollars.
*Right from the start* there was trouble with the Hubble.
The pictures it sent us were very disappointing
	because its main mirror was faulty.
NASA is now going to put the telescope right,
	so it will soon be sending up four astronauts to repair it.
The shuttle Endeavour will be taking the astronauts to the Hubble.
A robot-arm from the Endeavour will grab the telescope
	and hold it while the astronauts make the necessary repairs.
Of course, the Hubble is above the earth's atmosphere,
	so it will soon be sending us the clearest pictures of the stars
		and distant galaxies that we have ever seen.
The Hubble will tell us a great deal about the age and size of the universe.
By the time you read this,
	the Hubble's eagle eye will have sent us thousands and thousands of wonderful pictures.
#+end_verse

* Lesson 62 After the fire
#+begin_verse
What was the danger to the villagers after the fire?

Firemen had been fighting the forest fire for nearly three weeks
	before they could *get it under control*.
*A short time before*, great trees had covered the countryside *for miles around*.
Now, smoke still rose up from the warm ground over the desolate hills.
Winter was coming on and the hills threatened the surrounding villages with destruction,
	for heavy rain would not only wash away the soil
		but would cause serious floods as well.
When the fire had at last been put out,
	the forest authorities ordered several tons of a special type of grass-seed
		which would grow quickly.
The seed was sprayed over the ground in huge quantities by aeroplanes.
The planes had been planting seed for nearly a month when it began to rain.
By then, however, in many places the grass had already *taken root*.
*In place of* the great trees which had been growing there *for centuries*,
	patches of green had begun to appear in the blackened soil.
#+end_verse

* Lesson 63 She was not amused
#+begin_verse
Why did Jenny want to leave the wedding reception?

Jeremy Hampden has *a large circle of friends* and is very popular at parties.
Everybody *admires him for* his great *sense of humour*
	- everybody, that is, except his six-year-old daughter, Jenny.
Recently, one of Jeremy's *closest friends* asked him to *make a speech* *at a wedding reception*.
This is *the sort of* thing that Jeremy loves.
He prepared the speech carefully and went to the wedding with Jenny.
He had included *a large number of* funny stories in the speech and, of course, it was great success.
As soon as he had finished, Jenny told him she wanted to go home.
Jeremy was a little disappointed by this but he did as his daughter asked.
*On the way home*, he asked Jenny if she had enjoyed the speech.
To his surprise, she said she hadn't.
Jeremy asked her why this was so
	and	she told him that she did not like to see so many people laughing at him.
#+end_verse

* Lesson 64 The Channel Tunnel
#+begin_verse
Why was the first tunnel not completed?

In 1858, a French engineer, Aime Thome de Gamond,
	arrived in England with a plan for a twenty-one-mile tunnel under the English Channel.
He said that it would *be possible to build* a platform in the centre of the Channel.
This platform would *serve as* a port and a railway station.
The Tunnel would be well-ventilated if tall chimneys were built *above sea level*.
In 1860, *a better plan was put forward* by an Englishman, William Low.
He suggested that a double railway-tunnel should be built.
This would *solve the problem of ventilation*,
	for if a train entered this tunnel, it would draw in fresh air behind it.
Forty-two years later a tunnel was actually begun.
If, at the time, the British had not feared invasion, it would have been completed.
The world had to wait almost another 100 years for the Channel Tunnel.
It was officially opened on March 7, 1994,
	finally connecting Britain to the European continent.
#+end_verse

* Lesson 65 Jumbo versus the police
#+begin_verse
Why did the police have to push Jumbo off the main street?

Last Christmas, the circus owner, Jimmy Gates,
	decided to take some presents to a children's hospital.
*Dressed up as* Father Christmas and accompanied by a 'guard of honour' of six pretty girls,
	he *set off* down the main street of the city riding a baby elephant called Jumbo.
He should have known that the police would never allow this sort of thing.
A policeman approached Jimmy and told him he ought to have gone along a side street
	as Jumbo was *holding up the traffic*.
Though Jimmy *agreed to go* at once, Jumbo refused to move.
Fifteen policemen had to push very hard to get him off the main street.
The police had a difficult time, but they were most amused.
'Jumbo must weigh a few tons,' said a policeman afterwards,
	'so *it was fortunate that* we didn't have to carry him.
Of course, we should arrest him,
	but as he has a good record, we shall *let him off* this time.'
#+end_verse

* Lesson 66 Sweet as honey!
#+begin_verse
What was 'sweet as honey' and why?

In 1963 a Lancaster bomber crashed on Wallis Island,
	a remote place in the South Pacific, a long way west of Samoa.
The plane wasn't too badly damaged,
	but *over the years*,	the crash was forgotten and the wreck remained undisturbed.
Then in 1989, twenty-six years after the crash,
	the plane was accidentally rediscovered in an aerial survey of the island.
By this time, a Lancaster bomber *in reasonable condition* was rare and *worth rescuing*.
The French authorities had the plane packaged and moved in parts back to France.
Now a group of enthusiast are going to have the plane restored.
It has four Rolls-Royce Merlin engines,
	but the group will need to have only three of them rebuilt.
Imagine their surprise and delight
	when they broke open the packing cases and found that the fourth engine was sweet as honey
		- still in perfect condition.
*A colony of bees* had *turned the engine into a hive* and it was totally preserved in beeswax!
#+end_verse

* Lesson 67 Volcanoes
#+begin_verse
Why does Tazieff risk his life like this?

Haroun Tazieff, the Polish scientist,
	has spent his lifetime studying active volcanoes and deep caves in all parts of the world.
In 1948, he went to Lake Kivu in the Congo to observe a new volcano which he later *named Kituro*.
Tazieff was able to *set up his camp* very close to the volcano while it was erupting violently.
Though he managed to take a number of brilliant photographs,
	he could not stay near the volcano for very long.
*He noticed that* a river of liquid rock was coming towards him.
It threatened to surround him completely,
	but Tazieff managed to escape just in time.
He waited until the volcano became quiet and he was able to return two days later.
This time, he managed to climb into the mouth of Kituro
	so that he could take photographs and measure temperatures.
Tazieff has often risked his life in this way.
He has been able to tell us more about active volcanoes than any man alive.
#+end_verse

* Lesson 68 Persistent
#+begin_verse
Why did Elizabeth tell Nigel that she was going to the dentist?

I crossed the street to *avoid meeting* him, but he saw me and came running towards me.
*It was no use pretending that* I had not seen him, so I waved to him.
I never *enjoy meeting* Nigel Dykes.
He never has anything to do.
*No matter how* busy you are,	he always *insists on coming* with you.
I had to think of a way of *preventing him from following me around* all morning.

'Hello, Nigel,' I said.
'*Fancy meeting you here*!'

'Hi, Elizabeth,' Nigel answered.
'*I was just wondering* how to spend the morning -- until I saw you.'
'You're not busy doing anything, are you?'

No, not at all, I answered.
'I'm going to...'

'*Would you mind my coming* with you?' he asked, before I had *finished speaking*.

'Not at all,' I lied, 'but I'm going to the dentist.'

'Then I'll come with you,' he answered.
'There's always plenty to read in the waiting room!'
#+end_verse

* Lesson 69 But not murder!
#+begin_verse
Do you think that the writer passed his driving test? Why?

I was being tested for a driving licence for the third time.
I had been asked to drive in heavy traffic and had done so successfully.
After having *been instructed to drive* out of town, I began to acquire confidence.
Sure that I had passed, I was almost beginning to enjoy my test.
The examiner must have *been pleased with* my performance,
	for he smiled and said, 'Just one more thing, Mr. Eames.
*Let us suppose that* a child suddenly crosses the road in front of you.
As soon as I *tap on the window*, you must stop within five feet.'
I *continued driving* and after some time, the examiner tapped loudly.
Though the sound could be heard clearly, it took me a long time to react.
I suddenly pressed the brake pedal hard and we were both thrown forward.
The examiner looked at me sadly.
'Mr. Eames,' he said, in a mournful voice, 'you have just killed that child!'
#+end_verse

* Lesson 70 Red for danger
#+begin_verse
How was the drunk removed from the ring?

During a bullfight, a drunk suddenly wandered into the middle of the ring.
The crowd began to shout, but the drunk *was unaware of* the danger.
The bull *was busy with the matador* *at the time*,
	but it suddenly *caught sight of* the drunk who was shouting rude remarks and waving a red cap.
Apparently *sensitive to* criticism,
	the bull forgot all about the matador and *charged at* the drunk.
The crowd suddenly *grew quiet*.
The drunk, however, seemed quite sure of himself.
When the bull *got close to him*, he clumsily *stepped aside* to let it pass.
The crowd *broke into cheers* and the drunk bowed.
By this time, however,
	three men had come into the ring and they quickly dragged the drunk to safety.
Even the bull seemed to *feel sorry for him*,
	for it *looked on* sympathetically
		until the drunk was *out of the way* before *once more* *turning its attention to the matador*.
#+end_verse

* Lesson 71 A famous clock
#+begin_verse
Has Big Ben ever gone wrong?

When you visit London,
	one of the first things you will see is Big Ben, the famous clock
		which can be heard *all over the world* on the BBC.
If the Houses of Parliament had not been *burned down* in 1834,
	the great clock would never have been erected.
Big Ben *takes its name* from sir Benjamin Hall
	who *was responsible for* the making of the clock
		when the new Houses of Parliament were being built.
It is not only of immense size, but is extremely accurate as well.
Officials from Greenwich Observatory have the clock checked twice a day.
On the BBC you can hear the clock
	when it is actually striking because microphones *are connected to* the clock tower.
Big Ben has rarely *gone wrong*.
Once, however, it failed to give the correct time.
A painter who had been working on the tower
	hung a pot of paint on one of the hands and slowed it down!
#+end_verse

* Lesson 72 A car called Bluebird
#+begin_verse
What mistake was made?

The great racing driver, Sir Malcolm Campbell, was the first man to drive at over 300 miles per hour.
He set up a new world record in September 1935 at Bonneville Salt Flats, Utah.
Bluebird, the car he was driving, had been specially built for him.
It was over 30 feet in length and had a 2,500-horsepower engine.
Although Campbell reached a speed of over 304 miles per hour,
	he *had great difficulty in controlling* the car because a tyre burst during the first run.
After his attempt,
	Campbell *was disappointed to learn that* his average speed had been 299 miles per hour.
However, a few days later, he was told that a mistake had been made.
His average speed had been 301 miles per hour.
Since that time, racing drivers have reached speeds over 600 miles an hour.
*Following in his father's footsteps* many years later,
	Sir Malcolm's son, Donald, also set up a world record.
Like his father, he was driving a car called Bluebird.
#+end_verse