#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 1-4 1.10 Differences & Biodiversity
#+begin_verse
Well, in the SSLD system, we pay a lot of attention to individual differences.
And differences can be a challenge in relationships.
Because, like when people are negotiating relationships,
	when someone thinks differently, acts differently,
			believes in different things, like looks at things differently,
		it can sometimes create a problem or a challenge.
So how can people understand the value of difference
	is an important first step in understanding relationships.
So a key concept that we are now taking in from the life sciences and the social sciences
	is this concept of biodiversity.
The SSLD system embraces what we call a diversity positive attitude,
	meaning that like we like diversity, we enjoy diversity.
We think that diversity is a good thing.

So why do we think so?
Well, first of all, biodiversity is actually a condition for human evolution.
I do not want to give you a whole lecture on biology here.
But like if you're interested,
	you can easily have access to
		like all sorts of interesting discussions and documentation on this concept of biodiversity.
So for natural selection to happen, we need to have biodiversity,
	so we have the like various variations of like manifestations of genes and phenomena,
		so that natural selection can take place.
So that is like one of the most important points.
The second point that I want to make is that relationship always involves differences, right?
So otherwise, like you will be only developing a relationship of a clone of yourself, right?
Anyone else that you're developing a relationship with, will have something that is different.
So being able to deal with the difference is actually the key to the success of any relationship.
And managing diversity, in our opinion, is part and parcel of human growth and evolution,
	whether we're talking about like individual personal growth or like collective social development.
The ability to manage diversity is always essential.
What we want you to remember is
	that being able to deal with differences is actually the key to the success of any relationship,
		and that managing diversity is part of human growth and evolution.
That is
	why understanding the importance of biodiversity would help you embrace the differences of others.
#+end_verse
** expression
diversity [daɪˈvɜrsəti]: n. the fact of including many different types of people or things差异, 多样性
individual [ˌɪndɪˈvɪdʒuəl]: adj. considered separately from other people or things in the sgroup个体的
lecture [ˈlektʃər]: n. a long talk on a particular subject that someone gives to a group of people, especially to students in a university ⇨ speech演讲, 讲稿
biology [baɪˈɑlədʒi]: n. the scientific study of living things生物学, 生物(总称)
documentation [ˌdɑkjumənˈteɪʃ(ə)n]: n. official documents, reports etc that are used to prove that something is true or correct文档
variation [ˌveriˈeɪʃ(ə)n]: n. a difference between similar things, or a change from the usual amount or form of something变种
gene [dʒin]: n. a part of a cell in a living thing that controls what it looks like, how it grows, and how it develops. People get their genes from their parents. ⇨ genetic[遗传]基因
phenomenon [fəˈnɑməˌnɑn] phenomena: n. something that happens or exists in society, science, or nature, especially something that is studied because it is difficult to understand现象
essential [ɪˈsenʃ(ə)l] essentially: adj.adv. extremely important and necessary根本的,极其重要的
--------------------
the first step in doing sth.: 做某事的第一步
take in from sth.: 从某事物中吸收
have access to sth.: possess the ability or permission to use, enter, or obtain something.能够获得某物
Otherwise, + ...: 否则,+ ...
develop a relationship with sb.: 和某人发展关系
part and parcel of sth.: 某物不可或缺的一部分
** sentence
diversity [daɪˈvɜrsəti]: n. the fact of including many different types of people or things差异, 多样性
- When you go to university, the first step in getting familiar with others is to embrace diversity.
- Embracing diversity is the key to make a profit in the war.
- The diversity of ethnics in the country was the main factor of the war.
individual [ˌɪndɪˈvɪdʒuəl]: adj. considered separately from other people or things in the some group个体的
- In the same envioronment, the accomplishments of you and your brother depend on individual differences.
- He realized to his horror that the man he was developing a relationship with was a man who only took care of his individual profit.
- Obviously, individual intelligence don't bring an end to collective intelligence.
lecture [ˈlektʃər]: n. a long talk on a particular subject that someone gives to a group of people, especially to students in a university ⇨ speech演讲, 讲稿
- Such is human nature, that we are more often willing to sacrifice a holiday for a useful lecture.
- It's a famous boxer who will hold a lecture in our school.
- Because of a heavy storm, the teacher delayed in holding the lecture.
biology [baɪˈɑlədʒi]: n. the scientific study of living things生物学, 生物(总称)
- He is an expert at biology, but on the other hand, he is bad at mathematics.
- The girl you are keeping in touch with has a habit of performing biology experiment on Saturday.
- The girl who cheated on a biology exam shall be punished five dollars.
documentation [ˌdɑkjumənˈteɪʃ(ə)n]: n. official documents, reports etc that are used to prove that something is true or correct文档
- When I quitted my job, my colleague was eager to ask me for the documentation of the project.
- Beyond doubts, these ancient documentation will continue into the next century.
- Your friend, Sam, is referencing documentations which prove that you are not a bastard, but the only heir to the Iron Throne.
variation [ˌveriˈeɪʃ(ə)n]: n. a difference between similar things, or a change from the usual amount or form of something变种
- This kind of business was another variation of pyramid scheme.
- Asking for protection money is another variation of criminal in the Modern Times.
- Your action is no doubts another variation of tax evasion.
gene [dʒin]: n. a part of a cell in a living thing that controls what it looks like, how it grows, and how it develops. People get their genes from their parents. ⇨ genetic[遗传]基因
- A group of scientists succeeded in cultivating a new spiece by gene technology.
- Gene technology was widely used in new fields.
- The variation of the gene led to the infertility of your wife.
phenomenon [fəˈnɑməˌnɑn] phenomena: n. something that happens or exists in society, science, or nature, especially something that is studied because it is difficult to understand现象
- This can lead to some curious phenomena, as it did in the case of Alf who worked for a big company abroad.
- No one could account for the phenomenon that more and more families chose to be dink.
- No one could account for the phenomenon that the sun rose from the west.
essential [ɪˈsenʃ(ə)l]: adj. extremely important and necessary基本的,极其重要的
- It's essential for me to have a good relationship with my family.
- It's essential for us to defeat them in the battlefield.
- It's essential for us to overrun the city which serves as the center of transportation.
--------------------
the first step in doing sth.: 做某事的第一步
- Figuring out why we need to do it is the first essential step in doing it. 
- The first step in passing the test is to have a good night.
- The first step in seizing power is to sack the capital of the empire.
take in from sth.: 从某事物中吸收
- The lesson we took in from the war is that peace was precious and vulnerable.
- The lesson we took in from the tragedy is there is no ship which is unsinkable.
- The lesson we took in from the usurper is that a king can never trust anyone.
have access to sth.: possess the ability or permission to use, enter, or obtain something.能够获得某物
- Having access to all sorts of English courses, he made progress in programming.
- During the floods, our people still had access to abundant food and shelters.
- Having access to snack, my cat seems to be very happy.
Otherwise, + ...: 否则,+ ...
- Otherwise, you will be punished five dollars for your rudeness in public.
- Otherwise, the workers trapped in mines will lose their hearts.
- Otherwise, the vicious king will never capture the hearts of people in the land.
develop a relationship with sb.: 和某人发展关系
- When I developed a relationship with a girl, her boyfriend appeared to be unhappy.
- Developing a relationship with a foreigner, you may be punished beheading for treason.
- Developing a relationship with a whore, the lord lost all of his men and property.
part and parcel of sth.: 某物不可或缺的一部分
- Making love with a man is part and parcel of being preganant.
- The spokesman for China claimed that Taiwan is part and parcel of China.
- Family is part and parcel of the life of a chemistry teacher who used to cook drugs.
** sentence2
diversity [daɪˈvɜrsəti]: n. the fact of including many different types of people or things差异, 多样性
- When you go to university, the first step in getting familiar with others is to embrace diversity.
- Embracing diversity is the key to making a profit in the war.
- The diversity of ethnics in the country was the main factor of the war.
individual [ˌɪndɪˈvɪdʒuəl]: adj. considered separately from other people or things in the some group个体的
- In the same environment, the accomplishments of you and your brother depend on individual differences.
- He realized to his horror that the man he was developing a relationship with was a man who only took care of his individual profit.
- Obviously, individual intelligence doesn't bring an end to collective intelligence.
lecture [ˈlektʃər]: n. a long talk on a particular subject that someone gives to a group of people, especially to students in a university ⇨ speech演讲, 讲稿
- Such is human nature, that we are more often willing to sacrifice a holiday for a useful lecture.
- It's a famous boxer who will give a lecture in our school.
- Because of a heavy storm, the teacher delayed in giving the lecture.
biology [baɪˈɑlədʒi]: n. the scientific study of living things生物学, 生物(总称)
- He is an expert at biology, but on the other hand, he is bad at mathematics.
- The girl you are keeping in touch with has a habit of performing biology experiments on Saturday.
- The girl who cheated on a biology exam shall be fined five dollars.
documentation [ˌdɑkjumənˈteɪʃ(ə)n]: n. official documents, reports etc that are used to prove that something is true or correct文档
- When I quit my job, my colleague was eager to ask me for the documentation of the project.
- Beyond doubt, these ancient documentations will continue into the next century.
- Your friend, Sam, is referencing documentation that proves that you are not a bastard, but the only heir to the Iron Throne.
variation [ˌveriˈeɪʃ(ə)n]: n. a difference between similar things, or a change from the usual amount or form of something变种
- This kind of business was another variation of a pyramid scheme.
- Asking for protection money is another variation of criminals in the Modern Times.
- Your action is no doubt another variation of tax evasion.
gene [dʒin]: n. a part of a cell in a living thing that controls what it looks like, how it grows, and how it develops. People get their genes from their parents. ⇨ genetic[遗传]基因
- A group of scientists succeeded in cultivating a new species by gene technology.
- Gene technology was widely used in new fields.
- The variation of the gene led to the infertility of your wife.
phenomenon [fəˈnɑməˌnɑn] phenomena: n. something that happens or exists in society, science, or nature, especially something that is studied because it is difficult to understand现象
- This can lead to some curious phenomena, as it did in the case of Alf who worked for a big company abroad.
- No one could account for the phenomenon that more and more families chose to dink.
- No one could account for the phenomenon that the sun rose from the west.
essential [ɪˈsenʃ(ə)l]: adj. extremely important and necessary基本的,极其重要的
- It's essential for me to have a good relationship with my family.
- It's essential for us to defeat them on the battlefield.
- It's essential for us to overrun the city which serves as the center of transportation.
--------------------
the first step in doing sth.: 做某事的第一步
- Figuring out why we need to do it is the first essential step in doing it. 
- The first step in passing the test is to have a good night.
- The first step in seizing power is to sack the capital of the empire.
take in from sth.: 从某事物中吸收
- The lesson we took in from the war is that peace is precious and vulnerable.
- The lesson we took in from the tragedy is there is no ship which is unsinkable.
- The lesson we took in from the usurper is that a king can never trust anyone.
have access to sth.: possess the ability or permission to use, enter, or obtain something.能够获得某物
- Having access to all sorts of English courses, he made progress in programming.
- During the floods, our people still had access to abundant food and shelter.
- Having access to snacks, my cat seems to be very happy.
Otherwise, + ...: 否则,+ ...
- Otherwise, you will be fined five dollars for your rudeness in public.
- Otherwise, the workers trapped in mines will lose their hearts.
- Otherwise, the vicious king will never capture the hearts of people in the land.
develop a relationship with sb.: 和某人发展关系
- When I developed a relationship with a girl, her boyfriend appeared to be unhappy.
- Developing a relationship with a foreigner, you may be punished by beheading for treason.
- Developing a relationship with a whore, the lord lost all of his men and property.
part and parcel of sth.: 某物不可或缺的一部分
- Making love with a man is part and parcel of being pregnant.
- The spokesman for China claimed that Taiwan is part and parcel of China.
- Family is part and parcel of the life of a chemistry teacher who used to cook drugs.
