#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2-3 2.11 Spontaneity
#+begin_verse
Right, so what I'm hearing is sort of on the individual level
		we have these patterns of attachment from early life that kind of follow us,
	and then on a broader level, there's these social scripts that we also follow.
But then, everything sounds predetermined,
	so where's that spontaneity or like following your heart?
Is there still a place for that? 

Well, I would say, yes, of course.
Because life would be like too boring without those.
What we would use as an analogy is,
	say for example, you're up for some fun moments like playing hockey or skiing.
What we are saying is
	that you have to learn the basic skills
		and then you also have to equip yourself with the right gear
			that fits your body, your size and your needs,
		and then you can go in and have fun.
Then you can ski, and have fun, and be spontaneous, and follow your heart.
But if you do not do that,
		and you just jump in without paying attention to these details,
	there's a huge chance that you would first not have fun and then,
		there is a very real possibility that you can get severely hurt.
So that I think it's an analogy that you use. 

Back to the relationship situation,
	our thinking is if you have spent some time reflecting on yourself,
			understanding your own needs and circumstances, characteristics, and capacity
		and you know what you're looking for in the relationship.
And you have sort of learned the basic skills
		for like communicating, interacting, building relationships,
	you will actually be more capable to get into situations where you can be spontaneous.
Because you can then trust yourself,
	like I can just sit down and relax and have a conversation and I know it will turn out well.
So that is the kind of self-efficacy or sense of ease that we want to establish in people
	so that they can really be going in there slow and enjoy the relationship.
#+end_verse
** expression
attachment [əˈtætʃmənt]: n. a feeling that you like or love someone or something and that you would be unhappy without them依恋
script [skrɪpt]: n. the written form of a speech, play, film etc ⇨ screenplay手稿, 手迹, 剧本
predetermined [ˌpridɪˈtɜrmɪnd]: adj. decided or arranged before something happens, so that it does not happen by chance预定的
analogy [əˈnælədʒi]: n. something that seems similar between two situations, processes etc类比
hockey [ˈhɒki]: n. a gplayed on grass by two teams of 11 players, with sticks and a ball SYN field hockey American English曲棍球
gear [ɡɪr]: n. the machinery in a vehicle such as a car, truck, or bicycle that you use to go comfortably at different speeds齿轮, 传动装置
capacity [kəˈpæsəti]: n. someone’s ability to do something OPP incapacity才能, 能力
efficacy [ˈefɪkəsi]: n. formal the ability of something to produce the right result SYN effectiveness OPP inefficacy功效, 效验
--------------------
on the individual level: 在个人层面上
on a broader level: 在更广泛的层面上
follow sb's heart: 跟随内心
say for example: 比如说
be up for sth./doing sth.: 准备好某事/做某事
go in (sth./doing sth.): 参加某事/做某事
jump in/into sth./doing sth.: 突然投入某事
there is a very real possibility that: 很有可能+...
be capable to do sth.: 有能力做某事
** sentence
attachment [əˈtætʃmənt]: n. a feeling that you like or love someone or something and that you would be unhappy without them依恋
- A child's attachment to his mother is the first step in building a good relationship. 
- The breakdown of his attachment to his father causes him to seek truth.
- His attachment to his father led him to find his long-last father.
script [skrɪpt]: n. the written form of a speech, play, film etc ⇨ screenplay手稿, 手迹, 剧本
- I still need to download scripts to understand videos in English.
- As the script put it: he is not a bastard, but the true heir to the Iron Throne.
- With script stolen by hackers, scriptwriter has to write a new ending.
predetermined [ˌpridɪˈtɜrmɪnd]: adj. decided or arranged before something happens, so that it does not happen by chance预定的
- No one could account for the fact that the fate of roles in the play are all predetermined.
- If all were predetermined, we could do nothing to change our fate.
- It seems to be predeterminded that the traitor would be killed by the girl whose family had been murdered at the wedding.
analogy [əˈnælədʒi]: n. something that seems similar between two situations, processes etc类比
- It's not exactly what I said, it's only an analogy.
- It's just an analogy, not because of who has said that, but because of what it is.
- It occurred to a butcher to make an analogy in the speech.
hockey [ˈhɒki]: n. a gplayed on grass by two teams of 11 players, with sticks and a ball SYN field hockey American English曲棍球
- He is a friend who used to invite me to play hockey in his house.
- Shame of being beaten in a hockey competition, he refused to play it in public.
- When we played hockey, our cat appeared and chased the ball.
gear [ɡɪr]: n. the machinery in a vehicle such as a car, truck, or bicycle that you use to go comfortably at different speeds齿轮, 传动装置,档
- When your car goes uphill, you'd better have it in second gear.
- In second gear, our car never reached a speed of 40 kilometers an hour.
- If your car keep in second gear, we must be late for taking part in the sail competition.
capacity [kəˈpæsəti]: n. someone’s ability to do something OPP incapacity才能, 能力
- Fortunately, his uncle admired his capacity for League of Legend and offered him money to pursue his game career.
- In his youth, his capacity for box emerged and was chosen by a prominent boxer.
- His capacity for box lets him enjoy tremendous popularity.
efficacy [ˈefɪkəsi]: n. formal the ability of something to produce the right result SYN effectiveness OPP inefficacy功效, 效验
- This kind of treatment has been eliminated, not because it lacks efficacy, but because of heavy side effects. 
- Its efficacy has already been proved during the plague.
- His death reminds me of the efficacy of a special kind of herb in the plain.
--------------------
on the individual level: 在个人层面上
- External event I cannot control, but I must plan out our march to the last detail on the individual level.
- On the individual level, he was never meant to be a good father.
- On the individual level, he was blessed with the capacity for war and politics.
on a broader level: 在更广泛的层面上
- On a broader level, he devoted himself to the country and his people.
- On a broader level, he never has enough time to spend with his child.
- On a broader level, the rate of abortion in teenagers is declining. 
follow sb's heart: 跟随内心
- When I hesitated to go to the jewelry shop, there is a voice telling me 'follow your heart'.
- Follow your heart and you will find the best path to the outlet.
- Follow your heart and ask yourself whether you will be put out of business or not.
say for example: 比如说
- Say for example, you lose your temper when an official fines you 50 yuan for spitting in public.
- Say for example, you fight yourself against bully taking your heart.
- Say for example, while you were working hard, your wife was cheating with her lover in your bed.
be up for sth./doing sth.: 准备好某事/做某事
- Are you up for an adventure in other land?
- The scriptwriter is up for bring a happy end to the series.
- The heroine, a dear noble lady who had always been so kind to everybody, was up for her revenge.
go in (sth./doing sth.): 参加某事/做某事
- If you don't prepare chopsticks and bowls, how can we go in our dinner?
- Going in our activity, he forgot all awful memeories about his family.
- I am not up for going in dinner with a hateful queen.
jump in/into sth./doing sth.: 突然投入某事
- Not equiped with weapons, he jumped in the fight and was killed by mistake.
- The cat jumped into having breakfast.
- If you jump in the competition, there's a very real possibility that you will be killed in action.
there is a very real possibility that: 很有可能+...
- There is a very real possibility that the kind gets mad because you keep assailing him.
- There is a very real possibility that our princess, a lovely girl who is admired by her people, is still a virgin.
- There is a very real possibility that the night watch will march the north before winter comes.
be capable to do sth.: 有能力做某事
- He is capable to seize power in the captal when we start a war in the north.
- He is capable to convert our king to the Protestant.
- Our king is capable to rule the seven kingdom again with his 70,000 cavalrymen.
** sentence2
attachment [əˈtætʃmənt]: n. a feeling that you like or love someone or something and that you would be unhappy without them依恋
- A child's attachment to his mother is the first step in building a good relationship. 
- The breakdown of his attachment to his father causes him to seek truth.
- His attachment to his father led him to find his long-lost father.
script [skrɪpt]: n. the written form of a speech, play, film etc ⇨ screenplay手稿, 手迹, 剧本
- I still need to download scripts to understand videos in English.
- As the script put it: he is not a bastard, but the true heir to the Iron Throne.
- With the script stolen by hackers, the scriptwriter has to write a new ending.
predetermined [ˌpridɪˈtɜrmɪnd]: adj. decided or arranged before something happens, so that it does not happen by chance预定的
- No one could account for the fact that the fate of roles in the play are all predetermined.
- If all were predetermined, we could do nothing to change our fate.
- It seems to be predetermined that the traitor would be killed by the girl whose family had been murdered at the wedding.
analogy [əˈnælədʒi]: n. something that seems similar between two situations, processes etc类比
- It's not exactly what I said, it's only an analogy.
- It's just an analogy, not because of who has said that, but because of what it is.
- It occurred to a butcher to make an analogy in the speech.
hockey [ˈhɒki]: n. a game played on grass by two teams of 11 players, with sticks and a ball SYN field hockey American English曲棍球
- He is a friend who used to invite me to play hockey in his house.
- Shame of being beaten in a hockey competition, he refused to play it in public.
- When we played hockey, our cat appeared and chased the ball.
gear [ɡɪr]: n. the machinery in a vehicle such as a car, truck, or bicycle that you use to go comfortably at different speeds齿轮, 传动装置,档
- When your car goes uphill, you'd better have it in second gear.
- In second gear, our car never reached a speed of 40 kilometers an hour.
- If your car is in second gear, we must be late to take part in the sail competition.
capacity [kəˈpæsəti]: n. someone’s ability to do something OPP incapacity才能, 能力
- Fortunately, his uncle admired his capacity for League of Legends and offered him money to pursue his game career.
- In his youth, his capacity for boxing emerged and was chosen by a prominent boxer.
- His capacity for box lets him enjoy tremendous popularity.
efficacy [ˈefɪkəsi]: n. formal the ability of something to produce the right result SYN effectiveness OPP inefficacy功效, 效验
- This kind of treatment has been eliminated, not because it lacks efficacy, but because of heavy side effects. 
- Its efficacy has already been proved during the plague.
- His death reminds me of the efficacy of a special kind of herb in the plain.
--------------------
on the individual level: 在个人层面上
- External events I cannot control, but I must plan out our march to the last detail on the individual level.
- On the individual level, he was never meant to be a good father.
- On the individual level, he was blessed with the capacity for war and politics.
on a broader level: 在更广泛的层面上
- On a broader level, he devoted himself to the country and his people.
- On a broader level, he never has enough time to spend with his child.
- On a broader level, the rate of abortion in teenagers is declining. 
follow sb's heart: 跟随内心
- When I hesitated to go to the jewelry shop, there was a voice telling me 'Follow your heart'.
- Follow your heart and you will find the best path to the outlet.
- Follow your heart and ask yourself whether you will be put out of business or not.
say for example: 比如说
- Say, for example, you lose your temper when an official fines you 50 yuan for spitting in public.
- Say, for example, you fight yourself against bully taking your heart.
- Say, for example, while you were working hard, your wife was cheating with her lover in your bed.
be up for sth./doing sth.: 准备好某事/做某事
- Are you up for an adventure in another land?
- The scriptwriter is up for bringing a happy end to the series.
- The heroine, a dear noble lady who had always been so kind to everybody, was up for her revenge.
go in (sth./doing sth.): 参加某事/做某事
- If you don't prepare chopsticks and bowls, how can we go in?
- Going in our activity, he forgot all the awful memeory about his family.
- I am not up for going in dinner with a hateful queen.
jump in/into sth./doing sth.: 突然投入某事
- Not equipped with weapons, he jumped in the fight and was killed by mistake.
- The cat jumped into having breakfast.
- If you jump in, there's a very real possibility that you will be killed in action.
there is a very real possibility that: 很有可能+...
- There is a very real possibility that the kind gets mad because you keep assailing him.
- There is a very real possibility that our princess, a lovely girl who is admired by her people, is still a virgin.
- There is a very real possibility that the night watch will march the north before winter comes.
be capable to do sth.: 有能力做某事
- He is capable to seize power in the capital when we start a war in the north.
- He is capable to convert our king to the Protestant.
- Our king is capable to rule the seven kingdoms again with his 70,000 cavalrymen.
** summary
On the invidual level, we have patterns of attachment from early life,
	and on a broader level, there're social scripts that we also follow.
Is there still a place for spontaneity or following your heart?
Yes, of course.
For example, you're up for playing hockey or skiing.
You have to learn the basic skills and equip yourself with the right gear
	so that you can go in and be spontaneous, and follow your heart.
However, if you just jump in without paying attention to these details,
	there's a very real possibility that you would not have fun and get severely hurt.
Back to relationship situation,
	if you have spent some time reflecting on yourself,
		 figuring out your own needs, characteristics, and capacity,
		and you know what you are looking for in the relationship,
		and you learned the basic skills, like communicating, interacting, and building relationship,
		you will be more capable to enjoy the relationship and be spontaneous. 
** summary2
On the individual level, we have patterns of attachment from early life,
	and on a broader level, there are social scripts that we also follow.
Is there still a place for spontaneity or following your heart?
Yes, of course.
For example, you're up for playing hockey or skiing.
You have to learn the basic skills and equip yourself with the right gear
	so that you can go in, be spontaneous, and follow your heart.
However, if you just jump in without paying attention to these details,
	there's a very real possibility that you would not have fun and get severely hurt.
Back to the relationship situation,
	if you have spent some time reflecting on yourself,
		 figuring out your own needs, characteristics, and capacity,
		and you know what you are looking for in the relationship,
		and you learned basic skills, like communicating, interacting, and building relationships,
		you will be more capable to enjoy the relationship and be spontaneous. 
