#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.14 Signifying Acts and Culture
#+begin_verse
You've talked about 'Signifying Acts',
	like bringing someone flowers or slamming a door
		and how they can actually represent underlying emotions.
I'm wondering if there are differences between cultures
	in the types of 'Signifying Acts' that they have.
Yes, certainly.
Say for example, bringing flowers is an expression of affection or friendship here in North America.
In most situations,
	we have actually elaborate rules regarding when to bring flowers home and what does it mean?
It can be bringing flowers to someone who's in the hospital.
It can be bringing flowers on Valentine's Day.
Those are generally well understood within this culture.

In some other cultures,
	expressions of affection is never done through bringing flowers
		and may be done through doing someone a favour or bringing food.
Slamming doors might be an effective expression of dissatisfaction or anger.
But you easily can imagine, in many parts of the world,
	doors are not really a common physical reality, so there's no door for you to slam.
There are like obviously cultural differences with all this.

Different cultures also have very strong rules on certain things.
Here in North America, we do not pay as much attention to.
One thing that I can think of is gender difference.
Here, say for example, hugging is a way to express like friendship, a connection,
	but if you go into a gender segregated culture, that is like taboo.
I remember I was actually taken off a car on the subway in Dubai to another car
	because that car was reserved for women and children and I went on that by mistake.
Because I was a visitor, so I was treated politely.
I imagine if you were a local person and people expect you to understand and respect that rule,
	I think the reaction would be slightly different.
[LAUGH]
When we move from one culture to another,
	we have to be very careful and pay attention to these cultural differences.
#+end_verse
** expression
signify [ˈsɪɡnɪˌfaɪ]: v. to represent, mean, or be a sign of something表示
regard [rɪˈɡɑrd]: v. as regards something formal relating to a particular subject – use this when you want to talk or write about a particular subject关系
gender [ˈdʒendər]: n. the fact of being male or female性别, 性
hug [hʌɡ]: v.n. to put your arms around someone and hold them tightly to show love or friendship SYN embrace拥抱
segregated [ˈseɡrəˌɡeɪtəd]: adj. a segregated school or other institution can only be attended by members of one sex, race, religion etc OPP integrated隔离的
taboo [təˈbu]: n. a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing(宗教)禁忌、避讳
reserve [rɪˈzɜrv]: v. to keep something so that it can be used by a particular person or for a particular purpose SYN set aside保留
--------------------
differences with sth.: 与...的不同
Valentine's Day: 情人节
by mistake: 错误地
** sentence
signify [ˈsɪɡnɪˌfaɪ]: v. to represent, mean, or be a sign of something表示
- She noticed the nuance of her husband's gesture which signified his anger. 
- Mr. Leo is such an affectionate man who signifys his emotions by acts.
- Your cat may have been signifying her hunger, so she kept making noises.
regard [rɪˈɡɑrd]: v. as regards something formal relating to a particular subject – use this when you want to talk or write about a particular subject关系
- The lord of Winterfell drew up a set of laws regarding when to start a war and how to keep oaths.
- The knight by no means broke oaths regarding his loyalty to the monarch.
- Regarding my loyalty to the monarch, I must sentence you to death because of your treason.
gender [ˈdʒendər]: n. the fact of being male or female性别, 性
- Disregarding gender differences, the teacher became popular with those women who were ruled in the society.
- In China, it is a taboo to pinpoint the gender of infant during the period of preganance.
- This lovely father have no desire for learning the gender of his baby.
hug [hʌɡ]: v.n. to put your arms around someone and hold them tightly to show love or friendship SYN embrace拥抱
- My daughter gave me a hug to reward me because I give her two tickets of Taylor Swift's concert.
- Daddy, hug. My son's words never fail to melt my heart.
- The father got very worried when he saw his daughter and a boy hugging togeter.
segregated [ˈseɡrəˌɡeɪtəd]: adj. a segregated school or other institution can only be attended by members of one sex, race, religion etc OPP integrated隔离的
- The existence of racially segregated school alarms us that the revolutionary is still on the way.
- The usurper built a number of ethno segregated churchs, so that he could put forward his plan.
- He fits well in the gender segregated school.
taboo [təˈbu]: n. a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing(宗教)禁忌、避讳
- In china, having your hair cut in January is a taboo beyond doubt.
- A taboo in this culture may be a popularity in another.
- Obviously, he is being punished because of the taboo he touched by mistake.
reserve [rɪˈzɜrv]: v. to keep something so that it can be used by a particular person or for a particular purpose SYN set aside保留
- The shoes I love have alreay been reserved for my uncle's daughter.
- Execuse me, the seats have been reserved for our customers.
- Even though the seat had been reserved, the customer still took it waiting for her husband.
--------------------
differences with sth.: 与...的不同
- Finishing homework in time is my difference with classmates who failed exam.
- The exam's differences with traditional ones are tremendous. 
- Disregarding the differences with social experiments, he performed the experiment abortively.
Valentine's Day: 情人节
- Out of his love of his wife, he planed out the party on Valentine's Day to last detail.
- She can't wait to receive gifts on Valentine's Day.
- On Valentine's Day, the boy confessed that he fell in love with the girl since junior high school.
by mistake: 错误地
- You should have mentioned your husband that he had taken a reserved seat by mistake.
- He took photos of the army by mistake.
- He has drawn an unacceptable conclusion about the budget of our country by mistake.
** sentence2
signify [ˈsɪɡnɪˌfaɪ]: v. to represent, mean, or be a sign of something表示
- She noticed the nuance of her husband's gesture which signified his anger. 
- Mr. Leo is such an affectionate man who signifies his emotions by acts.
- Your cat may have been signifying her hunger, so she kept making noises.
regard [rɪˈɡɑrd]: v. as regards something formal relating to a particular subject – use this when you want to talk or write about a particular subject关系
- The Lord of Winterfell drew up a set of laws regarding when to start a war and how to keep oaths.
- The knight by no means broke oaths regarding his loyalty to the monarch.
- Regarding my loyalty to the monarch, I must sentence you to death because of your treason.
gender [ˈdʒendər]: n. the fact of being male or female性别, 性
- Disregarding gender differences, the teacher became popular with those women who were mistreated in society.
- In China, it is taboo to pinpoint the gender of an infant during the period of pregnancy.
- This lovely father has no desire to learn the gender of his baby.
hug [hʌɡ]: v.n. to put your arms around someone and hold them tightly to show love or friendship SYN embrace拥抱
- My daughter gave me a hug to reward me because I give her two tickets of Taylor Swift's concert.
- Daddy, hug. My son's words never fail to melt my heart.
- The father got very worried when he saw his daughter and a boy hugging together.
segregated [ˈseɡrəˌɡeɪtəd]: adj. a segregated school or other institution can only be attended by members of one sex, race, religion etc OPP integrated隔离的
- The existence of racially segregated schools alarms us that the revolution is still on its way.
- The usurper built a number of ethnically segregated churches so that he could put forward his plan.
- He fits well in the gender-segregated school.
taboo [təˈbu]: n. a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing(宗教)禁忌、避讳
- In China, having your hair cut in January is taboo beyond doubt.
- Taboo in this culture may be a custom in another.
- Obviously, he is being punished because of the taboo he touched by mistake.
reserve [rɪˈzɜrv]: v. to keep something so that it can be used by a particular person or for a particular purpose SYN set aside保留
- The shoes I love have already been reserved for my uncle's daughter.
- Excuse me, the seats have been reserved for our customers.
- Even though the seat had been reserved, the customer still took it waiting for her husband.
--------------------
differences with sth.: 与...的不同
- Finishing homework on time is my difference with classmates who failed exams.
- The exam's differences with traditional ones are tremendous. 
- Disregarding the differences with social experiments, he performed the experiment abortively.
Valentine's Day: 情人节
- Out of his love for his wife, he planned out the party on Valentine's Day to the last detail.
- She can't wait to receive gifts on Valentine's Day.
- On Valentine's Day, the boy confessed that he had fallen in love with the girl since junior high school.
by mistake: 错误地
- You should have mentioned to your husband that he had taken a reserved seat by mistake.
- He took photos of the army by mistake.
- He has drawn an unacceptable conclusion about the country's budget by mistake.
