#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.12 Attributions 3 - Needs
#+begin_verse
Is an attribution always a response to an underlying need?
I would say that in most cases, but in some cases, it can all just be a habit.
Okay.
Because making simple attributions, as I said, consumes less energy.
Mm-hm.
To a lot of people, I just do not have that much psychological energy
	to put into this and think about this carefully and consider this in multiple dimensions.
It will be just easier for me to say, okay, this is how it works.

Actually, later on, when we have a chance to look at how research is done,
	we will find that even research scientists were making the same mistake.
We try to come up with very simple answers and we ask very simple questions.
One example that I can talk about here, and then later on in this course,
	hopefully, we'll have a chance to look into this in more detail.
Is very often people are interested in the idea of who are the people who are attractive?
What makes people attractive?

When you ask a question like this, you're asking, first of all, a very simple question.
That's an oversimplified question.
And then people come up with simple answers,
	if you're tall, you're blonde, that you're handsome or you're white or you're young or whatever.
You're more attractive than people who're not blonde, who are darker skinned,
	or if you're older or whatever.
So that is a simple attribution,
	you try to explain interpersonal attraction by referring to a very simple factor or variable.
	
The one question that we do not ask is you are attractive to whom?
[LAUGH]
[LAUGH]
What you find attractive may be very different from that what I find attractive.
So the reference group is again, overly simplified and homogenized or standardized.
When we start asking more nuanced, more complex set of questions,
	we obviously will have to spend more time finding the answers.
This is why a lot of people are just like okay, it's simple.
If you're taller, you're more attractive.
If you're blonde, you're more attractive.
That makes life simpler but this is actually an attribution error.
Seeking answers in this way, in my opinion, is not even the best way to do research.
Yeah.
#+end_verse
** expression
psychological [ˌsaɪkəˈlɑdʒɪk(ə)l]: adj. relating to the way that your mind works and the way that this affects your behaviour SYN mental心理(上)的
hopefully [ˈhoʊpfəli]: adv. a way of saying what you hope will happen, which some people think is incorrect有希望地
blonde [blɑnd]: adj. blonde hair is pale or yellow in colour金发碧眼的
skinned [skɪnd]: adj. having a skin of a specified type具有... 皮的
interpersonal [ˌɪntərˈpɜrsən(ə)l]: adj. relating to relationships between people人际的
variable [ˈveriəb(ə)l]: n. something that may be different in different situations, so that you cannot be sure what will happen OPP constant变量
homogenize [həˈmɑdʒəˌnaɪz]: v. to change something so that its parts become similar or the same同质化
nuance [ˈnuˌɑns]: n. a very slight, hardly noticeable difference in manner, colour, meaning etc ⇨ subtlety细微差别
complex [ˈkɑmˌpleks]: adj. consisting of many different parts and often difficult to understand SYN complicated OPP simple复杂的
--------------------
put into sth.: 投入
have a chance to do sth.: 有机会做某事
look into sth.: 调查研究某事
** sentence
psychological [ˌsaɪkəˈlɑdʒɪk(ə)l]: relating to the way that your mind works and the way that this affects your behaviour SYN mental心理(上)的
- The teacher didn't pay attention to my psychological state at all.
- His psychological state is so vulnerable that he can't fall into sleep because of an exciting TV series.
- No one could account for the fact that the girl's psychological state is so vulnerable after the raid.
hopefully [ˈhoʊpfəli]: a way of saying what you hope will happen, which some people think is incorrect有希望地
- Hopefully, I will move on to next village fair in an hour.
- Hopefully, you will be adored by poor and alike when you become our queen.
- Hopefully, you will be brought up to exercise swords and ride in the plain.
blonde [blɑnd]: blonde hair is pale or yellow in colour金发碧眼的
- The butcher's son never dreams of marrying to a blonde girl abroad.
- There is always hope that you will marry to a blonde noble in the south.
- I felt repulsive when the blonde girl took a piss in the mall in public.
skinned [skɪnd]: having a skin of a specified type具有... 皮的
- She is due to have an operation to erase red-skinned scar from her face.
- After fighting bitterly, a red-skinned scar left in her face for the rest of her life.
- The general is showing us red-skinned scars meaning that he contributed a lot to our country.
interpersonal [ˌɪntərˈpɜrsən(ə)l]: relating to relationships between people人际的
- I quake in every limb and in my soul in public because of the lack of interpersonl skills.
- My wife is blaming me for my lack of interpersonal skills and losing her face in public.
- I was eager to learn interpersonal skills to make myself comfortable in crowd.
variable [ˈveriəb(ə)l]: something that may be different in different situations, so that you cannot be sure what will happen OPP constant变量
- Whether you can take the Iron Throne depends on multiple variables.
- Depending on multiple variables, the experiment that we are performing is hard to expect.
- Failing to consider multiple variables, our king is winning the war in the battle field but losing it elsewhere.
homogenize [həˈmɑdʒəˌnaɪz]: to change something so that its parts become similar or the same同质化
- With the immigrants in the community homogenized, people are not blaming on them when something goes wrong.
- After years of conditioning, we are homogenized into this ethnocity.
- We must take advantage of our products when they are still different from others and haven't been homogenized.
nuance [ˈnuˌɑns]: n. a very slight, hardly noticeable difference in manner, colour, meaning etc ⇨ subtlety细微差别
- Aware of every nuance in her grandmother's voice, she recognized that it was the witch who was pretending her.
- Aware of the nuance in her husband gesture, she ran to her father and asked for help.
- Obviously, the snake could not tell the nuance of jazz music and Indian tradition music.
complex [ˈkɑmˌpleks]: consisting of many different parts and often difficult to understand SYN complicated OPP simple复杂的
- Full of complex emotions, he didn't refuse to conduct his brother to the labyrinth.
- The complex composition reminded him of a masterpiece by an Italian writer.
- Complex patterns are carved out of the dagger.
--------------------
put into sth.: 投入
- Before you put into reading, you should be with your dictionary which you can consult.
- Before you put into asking me complex question, you'd better try to tackle it on your own.
- Before the airport put into use, every inhabitant in the neighbor should be settled down elsewhere.
have a chance to do sth.: 有机会做某事
- Hopefully, you have a chance to overthrow his brutal regin.
- Hopefully, you have a chance to get out of the trap because of your dear father.
- You have a chance to live a happy life if you give up your power.
look into sth.: 调查研究某事
- Looking into the statue of a secret god, he was cursed into a yellow-skinned face.
- He feels it's his duty to look into the ghost in the farm.
- The police can't be bothered to look into the lost of lambs.
** sentence2
psychological [ˌsaɪkəˈlɑdʒɪk(ə)l]: relating to the way that your mind works and the way that this affects your behaviour SYN mental心理(上)的
- The teacher didn't pay attention to my psychological state at all.
- His psychological state is so vulnerable that he can't fall asleep because of an exciting TV series.
- No one could account for the fact that the girl's psychological state is so vulnerable after the raid.
hopefully [ˈhoʊpfəli]: a way of saying what you hope will happen, which some people think is incorrect有希望地
- Hopefully, I will move on to the next village fair in an hour.
- Hopefully, you will be adored by the poor and rich alike when you become our queen.
- Hopefully, you will be brought up to exercise swords and ride in the plain.
blonde [blɑnd]: blonde hair is pale or yellow in colour金发碧眼的
- The butcher's son never dreams of marrying a blonde girl abroad.
- There is always hope that you will marry a blonde noble in the south.
- I felt repulsive when the blonde girl took a piss in the mall in public.
skinned [skɪnd]: having a skin of a specified type具有... 皮的
- She is due to have an operation to erase a red-skinned scar from her face.
- After fighting bitterly, a red-skinned scar was left on her face for the rest of her life.
- The general is showing us red-skinned scars meaning that he contributed a lot to our country.
interpersonal [ˌɪntərˈpɜrsən(ə)l]: relating to relationships between people人际的
- I quake in every limb and in my soul in public because of the lack of interpersonal skills.
- My wife is blaming me for my lack of interpersonal skills and losing her face in public.
- I was eager to learn interpersonal skills to make myself comfortable in a crowd.
variable [ˈveriəb(ə)l]: something that may be different in different situations, so that you cannot be sure what will happen OPP constant变量
- Whether you can take the Iron Throne depends on multiple variables.
- Depending on multiple variables, the experiment that we are performing is hard to expect.
- Failing to consider multiple variables, our king is winning the war on the battlefield but losing it elsewhere.
homogenize [həˈmɑdʒəˌnaɪz]: to change something so that its parts become similar or the same同质化
- With the immigrants in the community homogenized, people are not blaming them when something goes wrong.
- After years of conditioning, we are homogenized into this ethnicity.
- We must take advantage of our products when they are different from others and haven't been homogenized.
nuance [ˈnuˌɑns]: n. a very slight, hardly noticeable difference in manner, colour, meaning etc ⇨ subtlety细微差别
- Aware of every nuance in her grandmother's voice, she recognized that it was the witch who was pretending to be her.
- Aware of the nuance in her husband's gesture, she ran to her father and asked for help.
- Obviously, the snake could not tell the nuance of jazz music and Indian traditional music.
complex [ˈkɑmˌpleks]: consisting of many different parts and often difficult to understand SYN complicated OPP simple复杂的
- Full of complex emotions, he didn't refuse to conduct his brother to the labyrinth.
- The complex composition reminded him of a masterpiece by an Italian writer.
- Complex patterns are carved out of the dagger.
--------------------
put into sth.: 投入
- Before you put into reading, you should be with your dictionary which you can consult.
- Before you put into the complex question, you'd better try to tackle it on your own.
- Before the airport is put into use, every inhabitant in the neighborhood should be settled down elsewhere.
have a chance to do sth.: 有机会做某事
- Hopefully, you have a chance to overthrow his brutal reign.
- Hopefully, you have a chance to get out of the trap because of your dear father.
- You have a chance to live a happy life if you give up your power.
look into sth.: 调查研究某事
- Looking into the statue of a secret god, he was cursed into a yellow-skinned face.
- He feels it's his duty to look into the ghost on the farm.
- The police can't be bothered to look into the loss of lambs.
** summary
In most cases an attribution is a response to an underlying need,
	but in some cases, it can be just a habit.
A lot of people do not have much psychological energe to put into this
	and consider this in multiple dimensions.
Research scientists are also making the same mistake,
	as they try to come up with simple answers and ask simple questions.
For example, what makes people attractive?
That's an oversimplified question and people come up with simple answers,
	like you're tall, blonde, or white.
This is a simple attribution, you explain interpersonal attraction by a very simple factor.
However, what you find attractive may be very different from me.
That indeed makes life simpler, but this is actually an attribution error.
Seeking answers in this way is not a good way to do research.
** summary2
In most cases, an attribution is a response to an underlying need,
	but in some cases, it can be just a habit.
A lot of people do not have much psychological energy to put into this
	and consider this in multiple dimensions.
Research scientists are also making the same mistake,
	as they try to come up with simple answers and ask simple questions.
For example, what makes people attractive?
That's an oversimplified question and people come up with simple answers,
	like you're tall, blonde, or white skinned.
This is a simple attribution, you explain interpersonal attraction by a very simple factor.
However, what you find attractive may be very different from mine.
That makes life simpler, but this is actually an attribution error.
Seeking answers in this way is not a good way to do research.
