#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.13 Signifying Acts
#+begin_verse
It sounds like in order to build more trust and to build better relationships,
	understanding the other person is really vital.
And so I'm wondering how to build that understanding and those skills at understanding other people.
Well, like in North America I think the emphasis is on listening.
So you listen carefully to the other person, what the other person is saying.
This is a very verbal culture and we privilege the spoken word.
But I have to say that careful listening is important
	and this is why we have like identify these different content areas
		like facts, attitude, emotions and needs.
But I also want to emphasize that we do not only gain understanding through listening.
If we pay attention, we observe to what other people are doing, right?
People sometimes can express their feelings and very significant emotional state
	through other channels than talking.
	
One of the concepts that I really want to introduce is the concept that I call 'Signifying Acts',
	which simply refers to acts or actions that we take that signify something.
Give you an example,
	in some cultures it is not appropriate for parents to apologize to their children
		if they've done something wrong.
So say for example,
	you have like a four year old walking down the hall
		and inadvertently take off the power line to her dad's computer.
And the dad yelled at her and then immediately, he felt bad,
	like I shouldn't be doing this to my four year old.
But then like maybe in his culture, apologizing might not be the best thing to do.
This person might then go up to his daughter and say hey,
	are you interested in taking a walk in the park, getting some ice cream, right?
That is sort of an indirect way of saying, I'm sorry.
I shouldn't have yelled at you, right.
That is considered a signifying act.

And one of the stories that I really like sharing and I actually had it in a book, right,
	is that we have this story from West China, like rural, mountainous area.
We had this girl who was betrothed to be married to a wealthier person because her family was broke.
She absolutely didn't want to get married to this guy,
	and her plan actually, was to commit suicide on her wedding night.
Before the wedding, she actually fell in love with another person.
So she was caught in very difficult position and then she had this filial obligation to her father.
So before she got married what she did was she walked down this mountainous area,
	it was like about ten kilometres walk, in this mountainous terrain, to go to the Yellow River,
		and get a bucket of water to take it home, to wash her father's feet.
So that is nothing was spoken, not a single word.
But it's a very intense, profound expression of emotion, right?
So this is what I mean by 'Signifying Acts'.

So being able to accurately decipher the code,
	'Signifying Acts' is a skill that we all need to learn.
And then, what I tried to point out earlier with this various examples is
	that this 'Signifying Acts' carry different meanings across different cultural contexts.
So what works in North America may not apply well in South America or in Africa or in Asia.
So a certain cultural understanding is also important for us
	to be able to understand or receive these messages correctly.
#+end_verse
** expression
trust [trʌst]: v.n. PEOPLE to believe that someone is honest or will not do anything bad or wrong OPP distrust, mistrust信任
vital [ˈvaɪt(ə)l]: adj. extremely important and necessary for something to succeed or exist SYN crucial至关重要的
verbal [ˈvɜrb(ə)l]: adj. spoken rather than written
privilege [ˈprɪvəlɪdʒ]: v. to treat some people or things better than others优先于
inadvertently [ˌɪnədˈvɜrt(ə)ntli]: adv. without realizing what you are doing SYN accidentally OPP deliberately不注意地
rural [ˈrʊrəl]: adj. happening in or relating to the countryside, not the city OPP urban乡下的, 田园的
mountainous [ˈmaʊnt(ə)nəs]: adj. a mountainous area has a lot of mountains多山的
broke [broʊk]: adj. having no money没钱的
filial [ˈfɪliəl]: adj. relating to the relationship of a son or daughter to their parents ⇨ parental子女的, 孝顺的
terrain [təˈreɪn]: n. a particular type of land地形
apply [əˈplaɪ]: v. to use something such as a method, idea, or law in a particular situation, activity, or process应用
--------------------
observe to sb./sth.: 注意到某人某事
through other channels than doing sth.: 通过其他渠道而不是做某事
take off the power line to sth.: 拔掉通往某物的电源线
be betrothed to sb.: 跟某人丁武
get/be married to sb. / marry sb.: 嫁给某人
commit suicide: 自杀
a bucket of sth.: 一桶某物
** sentence
trust [trʌst]: v.n. PEOPLE to believe that someone is honest or will not do anything bad or wrong OPP distrust, mistrust信任
- If you go out of your way to help your friend, trust will be built.
- In his pursuit of trust, he keeps his oaths and often does his friends favors.
- As the team has accomplished some achievement, teammates began to trust their captain spontaneously.
vital [ˈvaɪt(ə)l]: adj. extremely important and necessary for something to succeed or exist SYN crucial至关重要的
- Washing your hands is vital for the patient who is having an operation.
- Keeping fed your cat twice a day is vital for her to lose her weight.
- It's vital for him to exchange five dollars for a bucket of rice.
verbal [ˈvɜrb(ə)l]: adj. spoken rather than written口头的
- You're naive enough to believe in verbal words from the mouth of a shrewd merchant.
- Paying attention to listening is vital for us to understand others in a verbal culture.
- The verbal words show us his respect of our chairman.
privilege [ˈprɪvəlɪdʒ]: v. to treat some people or things better than others优先
- This country privileges women and children, for there're cars in the subway reserved for them.
- The stuff in the subway conducted me to the note, it says, 'This car privileges women and children'.
- The representive advocates that our society should privilege women in public.
inadvertently [ˌɪnədˈvɜrt(ə)ntli]: adv. without realizing what you are doing SYN accidentally OPP deliberately不注意地
- I noticed to my horror that my cat inadvertently set the kitchen on fire.
- My wife inadvertently interrupted my process of programming referring to her family.
- The lovely eccentric always adds color to our dull routine inadvertantly.
rural [ˈrʊrəl]: adj. happening in or relating to the countryside, not the city OPP urban乡下的, 田园的
- People in the city are always forming an unrealistic picture of life in the rural village.
- It holds fairs three times a week in the rural village.
- People in the rural village soon learnt that Mary had lost a little lamb.
mountainous [ˈmaʊnt(ə)nəs]: adj. a mountainous area has a lot of mountains多山的
- Whether the grasses take root is vital for people in the mountainous area, especially meeting floods.
- People in the mountainous area now can take advantage of prosperous expresses in China.
- People in the mountainous area benifit from the internet shopping on it.
broke [broʊk]: adj. having no money没钱的
- You insist on your vacation at seaside resort when our family is broke.
- A broke visitor asked me to do him a favor and I refused without hesitation.
- The woman must be married to a gay because her house ceases to produce gold and is getting broke.
filial [ˈfɪliəl]: adj. relating to the relationship of a son or daughter to their parents ⇨ parental子女的, 孝顺的
- You are my son and have filial obligation to me.
- Having filial obligation to his father, he had to give up the job of kingsguard and become the lord of his house.
- The prince was so filial that he ordered his men to kill those people who had abused his mother.
terrain [təˈreɪn]: n. a particular type of land地形
- Our wives will benefit from rockey terrain in the battlefield. 
- There is an army of robberies in the mountainous terrain.
- Without amply sustenance, our soldiers couldn't survive crossing the moutainous terrain.
apply [əˈplaɪ]: v. to use something such as a method, idea, or law in a particular situation, activity, or process应用
- Machine will be applied in the field so that we will not cultivate grain with bare hands.
- Applying machine in this way is not good for its life span.
- Applying machine invented to detect gold, the explorers soon found the treasure in the cave.
--------------------
observe to sb./sth.: 注意到某人某事
- If you had observed to what the coach did, you would have passed the driver exam.
- Have you observed to my new haircut, darling?
- The cat observed to a bird which was kept in the cage.
through other channels than doing sth.: 通过其他渠道而不是做某事
- You'd better get ships through other channels than marrying an old noble.
- The shrewd businessman arranged a settlement through other channels than comprising with workers.
- I will move on to the next village through other channels than taking a bus.
take off the power line to sth.: 拔掉通往某物的电源线
- I just took off the power line to your computer by mistake, it's not a big deal.
- It must be my cat who took off the power line to the electric cooker.
- You shall take off the power line to the electric cooker in three hours.
be betrothed to sb.: 跟某人定亲
- I am not free to marry your daughter, I have been betrothed to the house of Winterfell.
- The girl planned to commit suicide after she heard that she was betrothed to a richer family.
- I have been betrothed to prince and I would be the queen in the realm.
get/be married to sb. / marry sb.: 嫁给某人
- She can't bear to be married to a crippled lord.
- I shall not be married to the old king, because I refused his proposal.
- If you got married to the butcher, you would suffer from poor in this way.
commit suicide: 自杀
- If the police arrived on the scene, they would try to figure out why the girl committed suicide.
- As we said, aware that he will be killed the pig jumped in the well and commit suicide.
- It dawned on him that he could pretend to commit suicide to get rid of the abduction.
a bucket of sth.: 一桶某物
- In spite of bad weather, our father still has caught a bucket of fish.
- A boy is carrying a bucket of wall from the well.
- My aunt instructed me to carry a bucket of wall to the village fair.
** sentence2
trust [trʌst]: v.n. PEOPLE to believe that someone is honest or will not do anything bad or wrong OPP distrust, mistrust信任
- If you go out of your way to help your friend, trust will be built.
- In his pursuit of trust, he keeps his oaths and often does his friends favors.
- As the team has accomplished some achievements, teammates began to trust their captain spontaneously.
vital [ˈvaɪt(ə)l]: adj. extremely important and necessary for something to succeed or exist SYN crucial至关重要的
- Washing your hands is vital for the patient who is having an operation.
- Having your cat eat twice a day is vital for her to lose weight.
- It's vital for him to exchange five dollars for a bucket of rice.
verbal [ˈvɜrb(ə)l]: adj. spoken rather than written口头的
- You're naive enough to believe in verbal words from the mouth of a shrewd merchant.
- Paying attention to listening is vital for us to understand others in a verbal culture.
- The verbal words show us his respect for our chairman.
privilege [ˈprɪvəlɪdʒ]: v. to treat some people or things better than others优先
- This country privileges women and children, for there are cars in the subway reserved for them.
- The staff in the subway referred me to the note, which said, 'This car privileges women and children'.
- The representative advocates that our society should privilege women in public.
inadvertently [ˌɪnədˈvɜrt(ə)ntli]: adv. without realizing what you are doing SYN accidentally OPP deliberately不注意地
- I noticed to my horror that my cat inadvertently set the kitchen on fire.
- My wife inadvertently interrupted my programming process by referring to her family.
- The lovely eccentric always adds color to our dull routine inadvertently.
rural [ˈrʊrəl]: adj. happening in or relating to the countryside, not the city OPP urban乡下的, 田园的
- People in the city always form an unrealistic picture of life in the rural village.
- It holds fairs three times a week in the rural village.
- People in the rural village soon learned that Mary had lost a little lamb.
mountainous [ˈmaʊnt(ə)nəs]: adj. a mountainous area has a lot of mountains多山的
- Whether the grasses take root is vital for people in the mountainous area, especially when encountering floods.
- People in the mountainous area now can take advantage of prosperous expresses in China.
- People in the mountainous area benefit from the internet shopping on it.
broke [broʊk]: adj. having no money没钱的
- You insist on your vacation at a seaside resort when our family is broke.
- A broke visitor asked me to do him a favor and I refused without hesitation.
- The woman must be married to a gay because her house ceases to produce gold and is getting broke.
filial [ˈfɪliəl]: adj. relating to the relationship of a son or daughter to their parents ⇨ parental子女的, 孝顺的
- You are my son and have a filial obligation to me.
- Having a filial obligation to his father, he had to give up the job of kingsguard and become the lord of his house.
- The prince was so filial that he ordered his men to kill those people who had abused his mother.
terrain [təˈreɪn]: n. a particular type of land地形
- Our wives will benefit from rocky terrain on the battlefield. 
- There is an army of robberies in the mountainous terrain.
- Without ample sustenance, our soldiers couldn't survive crossing the mountainous terrain.
apply [əˈplaɪ]: v. to use something such as a method, idea, or law in a particular situation, activity, or process应用
- Machine will be applied in the field so that we will not cultivate grain with bare hands.
- Applying a machine in this way is not good for its life span.
- Applying the machine invented to detect gold, the explorers soon found the treasure in the cave.
--------------------
observe to sb./sth.: 注意到某人某事
- If you had observed to what the coach did, you would have passed the driver's exam.
- Have you observed to my new haircut, darling?
- The cat observed to a bird that was kept in the cage.
through other channels than doing sth.: 通过其他渠道而不是做某事
- You'd better get ships through other channels than marrying an old noble.
- The shrewd businessman arranged a settlement through other channels than comprising workers.
- I will move on to the next village through other channels than taking a bus.
take off the power line to sth.: 拔掉通往某物的电源线
- I just took off the power line to your computer by mistake, it's not a big deal.
- It must be my cat who took off the power line to the electric cooker.
- You shall take off the power line to the electric cooker in three hours.
be betrothed to sb.: 跟某人定亲
- I am not free to marry your daughter, I have been betrothed to the house of Winterfell.
- The girl planned to commit suicide after she heard that she was betrothed to a richer family.
- I have been betrothed to the prince and I would be the queen in the realm.
get/be married to sb. / marry sb.: 嫁给某人
- She can't bear to be married to a crippled lord.
- I shall not be married to the old king, because I refused his proposal.
- If you got married to the butcher, you would suffer from poor in this way.
commit suicide: 自杀
- If the police arrived on the scene, they would try to figure out why the girl committed suicide.
- As we said, aware that he would be killed the pig jumped into the well and committed suicide.
- It dawned on him that he could pretend to commit suicide to get rid of the abduction.
a bucket of sth.: 一桶某物
- In spite of bad weather, our father still has caught a bucket of fish.
- A boy is carrying a bucket of water from the well.
- My aunt instructed me to carry a bucket of water to the village fair.
** summary
Listening carefully to what the other person is saying is very important,
	so we have identified four different content areas: facts, attitude, emotions and needs.
But we do not only gain understanding through listening,
	because people can express their feelings and emotions through other channels than talking.
One of the ways is 'Signifying Acts' which refers to action people take to signify something.
For example, a father has just yelled at her five year old daughter
	because she inadvertently took off the power line to his computer.
Insteading of apologizing to her directly,
	he asked her whether she wanted to go to park and eat ice cream.
It meaned that he was sorry that he shouldn't have yelled at her.
'Signifying Acts' is a skill that we all need to learn to understand other people better.
Besides, it manifests very differently in different cultures.
** summary2
Listening carefully to what the other person is saying is very important,
	so we have identified four content areas: facts, attitude, emotions, and needs.
But we do not only gain understanding through listening,
	as people can express their feelings and emotions through other channels than talking.
One of the ways is 'Signifying Acts' which refers to actions people take to signify something.
For example, a father has just yelled at her five-year-old daughter
	because she inadvertently took off the power line to his computer.
Instead of apologizing to her directly,
	he asked her whether she wanted to go to the park and eat ice cream.
It meant that he was sorry that he shouldn't have yelled at her.
'Signifying Acts' is a skill that we all need to learn to understand other people better.
Besides, it manifests as different forms in different cultures.
