#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.19 Expression - Ideas 3 - Staying Attuned
#+begin_verse
It seems like being attuned to your audience or the other parties is so important
	and then I guess how can you tell if the metaphor you're using,
		for instance, they're understanding it and they're accepting your idea.
Well, you have already given the key word.
The key word is to stay attuned.

And how do we do that?
In SSLD, we're looking for specific behavioural markers when people can extend on your metaphor.
Mm-hm.
That means they have got the idea, or they can elaborate on it,
	or they can give you similar examples.
After, say for example, you have worked with 12-year-olds, with an apple,
	and then you bring in something else now and ask them, what is this?
If they can tell you a different way of classification, then you know that they have got the idea.
Say for example, after you've taken in the apple,
	and then you say you are bringing a cat and ask people, what is this?
It's a cat, what is a cat?
And then people can say well, it's an animal or it's a pet.
And then you can ask, so can the cat be something else?
And if they can answer, if someone can tell you,
	the cat can actually be a guide, be a therapist,
		or the cat can be a teacher, or the cat can be part of your decor.
The cat can be your message to your customer about how this space is an animal friendly space.
Then you know that these students are getting the idea.
So you stay attuned,
	you're looking for extension of your idea or specific application of it, elaboration.
	
And sometimes, especially in the pedagogical or educational setting, you can actually ask people.
What is the idea that you have got?
This skill of clarification actually works both ways,
	and this is something that we encourage in communication.
Sometimes you would just say to the other person that I just do not want to misunderstand you,
	so I'm going to tell you what I've heard from you is that what you are saying to me.
That it's like seeking clarification and confirmation.

Sometimes you can be doing the same.
Yeah, I just want to make sure that we're on the same page,
	I have talked about this, can you tell me what does that mean to you?
Does it make sense or because we don't want to be asking this question
	that can be taken as questioning or sometimes can be,
		some people can take it as humiliating question,
			you're thinking I don't understand you or I'm not following.
Instead of, do you understand?
Or repeat to me what I have told you, this is sort of a more didactic top-down approach,
	we would be asking what do you think of it?
Does it make sense to you?
How does it make sense to you?
Or sometimes to make the other party feel better,
	I've told you, do you see something wrong with this or what aspect of it you like better?
So, you can be asking questions like that to get direct feedback from the other person.
#+end_verse
** expression
specific [spəˈsɪfɪk]: adj. a specific thing, person, or group is one particular thing, person, or group OPP non-specific明确的
marker [ˈmɑːkə(r)]: n. an object, sign etc that shows the position of something标志
classification [ˌklæsɪfɪˈkeɪʃ(ə)n]: n. a process in which you put something into the group or class it belongs to ⇨ classify分类, 分级
therapist [ˈθerəpɪst]: n. someone who has been trained to give a particular form of treatment for physical or mental illness治疗专家
decor [deɪˈkɔr]: n. the way that the inside of a building is decorated装饰风格,装饰品
pedagogical [ˌpedəˈɡɑdʒɪk(ə)l]: adj. relating to teaching methods or the practice of teaching ⇨ educational教育学的
didactic [daɪˈdæktɪk]: adj. someone who is didactic is too eager to teach people things or give instructions说教的
humiliate [hjuˈmɪliˌeɪt]: v. to make someone feel ashamed or stupid, especially when other people are present SYN embarrass羞辱
--------------------
stay attuned: being in awareness or paying close attention to something保持关注
bring in sth.: 引入某物
take in sth.: 吸收某物
in the educational setting: 在教育的环境下
on the same page: 意见一致地
be taken as questioning: 被视为质疑
top-down approach: 自顶向下的方法
** sentence
specific [spəˈsɪfɪk]: adj. a specific thing, person, or group is one particular thing, person, or group OPP non-specific明确的
- Before you put into thinking about it, you'd better ask yourself a specific question.
- I need a specific answer whether you will be going to the meeting tomorrow.
- The non-specific loaction of electrons is part of our model for atoms.
marker [ˈmɑːkə(r)]: n. an object, sign etc that shows the position of something标志
- The police went out of his way to find any markers which the child left while he was being kidnappered. 
- His grandfather conducted him to the marker, which said: 'No parking.'
- The marker reminded the teacher of ancient creatures which have disappeared for two thousand years.
classification [ˌklæsɪfɪˈkeɪʃ(ə)n]: n. a process in which you put something into the group or class it belongs to ⇨ classify分类, 分级
- As a merchant, I must figure out the classification of wine according to quality.
- The programmer keeps making the classification of documents according to project.
- Making the classification of product according to date, the worker got exhausted and began to complain his superior.
therapist [ˈθerəpɪst]: n. someone who has been trained to give a particular form of treatment for physical or mental illness治疗专家
- It was the therapist who put forward the plan about the eradication campaign of pleague.
- Lying on the legs, my cat functions like a therapist when I am doing homework.
- The eminent therapist in the hospital was accused of sexual harassment by his male paitents.
decor [deɪˈkɔr]: n. the way that the inside of a building is decorated装饰风格,装饰品
- Tired of this kind of decor of an apartment, he came up with a very low price which is unacceptable in the market.
- When she opened the door, I noticed to my horror that she had spent all of her pocket money purchasing decors.
- It was disturbing to think that my daughter's room was full of decors and she refused to clean it up.
pedagogical [ˌpedəˈɡɑdʒɪk(ə)l]: adj. relating to teaching methods or the practice of teaching ⇨ educational教育学的
- The headmaster in the high school decided to bring in a new pedagogical method next semester.
- The pedagogical purpose is to help students become a soldier on the battlefield.
- In the pursuit of the pedagogical purpose, the teacher devoted himself to his students.
didactic [daɪˈdæktɪk]: adj. someone who is didactic is too eager to teach people things or give instructions说教的
- It seems that I am meant to be a didactic father.
- Running into his didactic father in the amusementpark, he kept hidden on the bush.
- Other than that, he is eager to meet his didactic father.
humiliate [hjuˈmɪliˌeɪt]: v. to make someone feel ashamed or stupid, especially when other people are present SYN embarrass羞辱
- In revenge for humiliating her while she was in prison, the queen had her knight raped the nun.
- Because of my anxiety, what I asked in class was always being taken as humiliating questions.
- The lady has been humiliating since she got married to the crippled lord.
--------------------
stay attuned: being in awareness or paying close attention to something保持关注
- If you had stayed attuned, you would have passed the driver's exam.
- Staying attuned to the concert of Taylor Swift, he immediately bought two tickets when message came to the internet.
- Staying attuned to his debt, he paid it on time after he got his salary.
bring in sth.: 引入某物
- The official insisted on bringing in some grains which are cultivated in the mountainous area.
- The official brought in some grass which would take root in the hill.
- The headmaster brought in some kind of grains to solve the lack of sustenance in this town.
take in sth.: 吸收某物
- I should be answering myself whether I take in knowledge my teacher teaches.
- The grasses can take in sustenance even if they are in extreme of salinity.
- This is marker whether our children take in the concept of time.
in the educational setting: 在教育的环境下
- The lawyer can take advantage of his knowledge in the educational setting.
- In the educational setting, he is acquainted with the concept of therapy.
- In the educational setting, he stayed attuned to a new generation of audiences. 
on the same page: 意见一致地
- Trust will be built when we are on the same page.
- They punished the criminal of starting a war on the same page.
- We treated the mad king on the same page.
be taken as questioning: 被视为质疑
- Whatever I have done is taken as questioning when you make such stupid remarks.
- When you interrupt people's speech in public, they would take it as questioning.
- In the face of being taken as questioning, he explain his pedagogical purpose to the headmaster.
top-down approach: 自顶向下的方法
- A top-down approach means to me that I can be an expert at programming.
- The project fits the top-down approach well.
- The top-down approach was designed to tackle issues about building relationships.
** sentence2
specific [spəˈsɪfɪk]: adj. a specific thing, person, or group is one particular thing, person, or group OPP non-specific明确的
- Before you deliberate on it, you'd better ask yourself a specific question.
- I need a specific answer about whether you will be going to the meeting tomorrow.
- The non-specific location of electrons is part of our model for atoms.
marker [ˈmɑːkə(r)]: n. an object, sign etc that shows the position of something标志
- The policeman went out of his way to find any markers that the child left while he was being kidnapped. 
- His grandfather conducted him to the marker, which said: 'No parking.'
- The marker reminded the teacher of ancient creatures which have disappeared for two thousand years.
classification [ˌklæsɪfɪˈkeɪʃ(ə)n]: n. a process in which you put something into the group or class it belongs to ⇨ classify分类, 分级
- As a merchant, I must figure out the classification of wine according to quality.
- The programmer made the classification of documents according to projects.
- Making the classification of product according to date, the worker got exhausted and began to complain to his superior.
therapist [ˈθerəpɪst]: n. someone who has been trained to give a particular form of treatment for physical or mental illness治疗专家
- It was the therapist who put forward the plan for the eradication campaign of plague.
- Lying on the legs, my cat functions like a therapist when I am doing homework.
- The eminent therapist in the hospital was accused of sexual harassment by his male patients.
decor [deɪˈkɔr]: n. the way that the inside of a building is decorated装饰风格,装饰品
- Tired of this kind of decor of an apartment, he came up with a very low price which is unacceptable in the market.
- When she opened the door, I noticed to my horror that she had spent all of her pocket money purchasing decors.
- It was disturbing to think that my daughter's room was full of decor and she refused to clean it up.
pedagogical [ˌpedəˈɡɑdʒɪk(ə)l]: adj. relating to teaching methods or the practice of teaching ⇨ educational教育学的
- The headmaster in the high school decided to bring in a new pedagogical method next semester.
- The pedagogical purpose is to help students become soldiers on the battlefield.
- In the pursuit of the pedagogical purpose, the teacher devoted himself to his students.
didactic [daɪˈdæktɪk]: adj. someone who is didactic is too eager to teach people things or give instructions说教的
- It seems that I am meant to be a didactic father.
- Running into his didactic father in the amusement park, he kept hidden in the bush.
- Other than that, he is eager to meet his didactic father.
humiliate [hjuˈmɪliˌeɪt]: v. to make someone feel ashamed or stupid, especially when other people are present SYN embarrass羞辱
- In revenge for humiliating her while she was in prison, the queen had her knight raped the nun.
- Because of my anxiety, what I asked in class was always being taken as humiliating questions.
- The lady has been humiliated since she got married to the crippled lord.
--------------------
stay attuned: being in awareness or paying close attention to something保持关注
- If you had stayed attuned, you would have passed the driver's exam.
- Staying attuned to the concert of Taylor Swift, he immediately bought two tickets when messages came to the internet.
- Staying attuned to his debt, he paid it on time after he got his salary.
bring in sth.: 引入某物
- The official insisted on bringing in some grains which are cultivated in the mountainous area.
- The official brought in some grass which would take root in the hill.
- The headmaster brought in some kind of grains to solve the lack of sustenance in this town.
take in sth.: 吸收某物
- I should be answering myself whether I take in knowledge my teacher teaches.
- The grasses can take in sustenance even if they are in an extreme environment of salinity.
- This is a marker of whether our children take in the concept of time.
in the educational setting: 在教育的环境下
- The lawyer can take advantage of his knowledge in the educational setting.
- In the educational setting, he is acquainted with the concept of therapy.
- In the educational setting, he stayed attuned to a new generation of audiences. 
on the same page: 意见一致地
- Trust will be built when we are on the same page.
- They punished the criminal for starting a war on the same page.
- We treated the mad king on the same page.
be taken as questioning: 被视为质疑
- Whatever I have done is taken as questioning when you make such stupid remarks.
- When you interrupt people's speech in public, they would take it as questioning.
- In the face of being taken as questioning, he explains his pedagogical purpose to the headmaster.
top-down approach: 自顶向下的方法
- A top-down approach means to me that I can be an expert at programming.
- The project fits the top-down approach well.
- The top-down approach was designed to tackle issues about building relationships.
