#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.21 Expression - Emotions 2 - Regulation
#+begin_verse
It sounds like emotional regulation,
	not just emotional expression, but the regulation of emotions is really important.
Yes.
I wonder if you could talk a little bit more about that.
Yeah, well, like I just said, when you're expressing emotions, you feel emotional.
And being able to regulate your own emotion is actually a very important human capacity.

There is a concept in biology, which is also utilized a lot in psychology.
That is the concept of homeostasis, the so-called normal state that we tend to return to.
We have a sort of a normal heart rate or blood pressure.
It can change when you're active, or when you're aroused,
	or when you're dealing with some external challenge.
But it'll, body temperature as well but then everything will return to more or less the same level.
So with emotions, we hope the same thing will happen.
So you get excited, you get stimulated, you get aroused,
	hopefully, you'll be returning to a relatively calm and stable state.
But if it doesn't happen, it can then become a mental health challenge,
	like people who are chronically depressed, for example.
Or people who feel sad, and they might have good reasons for feeling that,
	but the problem is that they do not return to a more stable state in which you are not sad.
Or if you're anxious,
	which is probably a natural response to external stress or threat or challenge.
But, again, if you’re constantly in that state
		and you do not return to a more relaxed and calm state,
	something is wrong with your emotional accumulation.
Problems with emotional regulation
	can actually become severe mental health or even physical health issues.
	
In an interpersonal relationship, if you're not able to regulate your emotion,
	then you have a higher chance of doing things or saying things that you later regret.
So it is obviously a good thing for us to be able to become aware of our emotional experience
	and be able to increase our capacity for regulating it.
And I just want to say this, we're not talking about suppressing your emotions,
		we're not talking about denying your emotions,
	those are actually not helpful.
Good emotional regulation actually is predicated on,
	I know that I'm feeling this,
		I know that I'm angry, I know that I am anxious, or I'm sad or depressed, doesn't matter.
I know that I have those feelings and I accept that I have those feelings.
But I also understand that,
	yeah, I know I have those feelings
		but I have the capacity to return to this, sort of homeostasis state.
Then I feel more comfortable and relaxed
	and when I try to express my emotions
		I know that this is what I need to do now, but I will get to a different state after that.
I think that is an important understanding.
#+end_verse
** expression
homeostasis [ˌhəʊmiə'steɪsɪs]: n. 体内平衡
arouse [əˈraʊz]: v. arouse interest/expectations etc to make you become interested, expect something etc唤醒, 唤起
external [ɪkˈstɜrn(ə)l]: adj. OUTSIDE PART relating to the outside of something or of a person’s body OPP internal外国的,外部的
stimulate [ˈstɪmjəˌleɪt]: v. to encourage or help an activity to begin or develop further OPP suppress刺激, 激励
chronic [ˈkrɑnɪk] chronically: adj.adv. a chronic disease or illness is one that continues for a long time and cannot be cured ⇨ acute慢性的, 延续很长的
depressed [dɪˈprest]: adj. suffering from a medical condition in which you are so unhappy that you cannot live a normal life抑郁的
stress [stres]: n. continuous feelings of worry about your work or personal life, that prevent you from relaxing ⇨ strain压力
--------------------
return to the same state/level: 返回到相同的状态/级别
be predicated on sth.: 基于/取决于某事物
have the capacity to do sth.: 有才能/能力去做某事
** sentence
homeostasis [ˌhəʊmiə'steɪsɪs]: n. 体内平衡
- Failing to return to homeostasis, he has gotten depressing for a long period of time.
- Being able to return to homeostasis is very important for us to regulate our emotions.
- After developing fever, the infected gradually returned to homeostasis.
arouse [əˈraʊz]: arouse interest/expectations etc to make you become interested, expect something etc唤醒, 唤起
- The robots in the park have been aroused and began to overthrow the management of humen.
- The man in black coat fell in love with the woman who turned out to be a robot and tried to arouse her.
- The place is evil, a witch is trying to arouse the devil in the hell.
external [ɪkˈstɜrn(ə)l]: OUTSIDE PART relating to the outside of something or of a person’s body OPP internal外国的,外部的
- The king went out of his way to control external events, starting a war on the continent.
- External events we can't control, a general in the castle mumbled in a weak voice.
- It is the external nomads who destroyed your civilization and killed your people, not us.
stimulate [ˈstɪmjəˌleɪt]: to encourage or help an activity to begin or develop further OPP suppress刺激, 激励
- The physician used matters from the lesion to stimulate the inoculated boy.
- Beyond doubt, the diplomatic policy has stimulated the merchants who trade across the sea.
- The hanging of Lord Stark stimulated his son, who started a war with the house of Lanister.
chronic [ˈkrɑnɪk] chronically: a chronic disease or illness is one that continues for a long time and cannot be cured ⇨ acute慢性的, 延续很长的
- I feel sorry for my father's chronic mental illness.
- My teacher raised money, because of my father's chronic mental illness.
- On arriving at home, I was told that my father suffered from chronic mental illness.
depressed [dɪˈprest]: suffering from a medical condition in which you are so unhappy that you cannot live a normal life抑郁的
- The test is designed to help patients who get chronically depressed.
- The patient who gets depressed ran out of his money in the inpatient department.
- I almost got depressed when my wife got me under a huge debt.
stress [stres]: continuous feelings of worry about your work or personal life, that prevent you from relaxing ⇨ strain压力
- My wife's laughing at me because of my poor accent put a lot of stress on me.
- Stop putting any stress on your child, or she will get depressed.
- Because of heavy stress, the player developed vomitting after he was defeated in the adversarial game.
--------------------
return to the same state/level: 返回到相同的状态/级别
- The infected boy has returned to the normal state after developing fever for a day.
- After the conflict had been resolved, their friendship returned to the normal state.
- After returning to the calm state, the king gave up cutting her throat up.
be predicated on sth.: 基于/取决于某事物
- Whether he is dead or alive is predicated on the result of the war between two houses.
- Learning English is predicated on a variety of factors, so I can't figure it out now.
- The king's privilege is predicated on his armies beyond the wall.
have the capacity to do sth.: 有才能/能力去做某事
- A witcher claimed that she had the capacity to save our king's life.
- The boy has the capacity to communicate with a foreigner, even if he doesn't know any foreign language.
- His wife has the capacity to tell the nuance of his gestures.
** sentence2
homeostasis [ˌhəʊmiə'steɪsɪs]: n. 体内平衡
- Failing to return to homeostasis, he has gotten depressed for a long period of time.
- Being able to return to homeostasis is very important for us to regulate our emotions.
- After developing a fever, the infected gradually returned to homeostasis.
arouse [əˈraʊz]: arouse interest/expectations etc to make you become interested, expect something etc唤醒, 唤起
- The robots in the park that have been aroused began to overthrow the management of humans.
- The man in black coat fell in love with the woman who turned out to be a robot and tried to arouse her.
- The place is evil, a witch is trying to arouse the devil in hell.
external [ɪkˈstɜrn(ə)l]: OUTSIDE PART relating to the outside of something or of a person’s body OPP internal外国的,外部的
- The king went out of his way to control external events, starting a war on the continent.
- External events we can't control, a general in the castle mumbled in a weak voice.
- It is the external nomads who destroyed your civilization and killed your people, not us.
stimulate [ˈstɪmjəˌleɪt]: to encourage or help an activity to begin or develop further OPP suppress刺激, 激励
- The physician used matters from the lesion to stimulate the inoculated boy.
- Beyond doubt, the diplomatic policy has stimulated the merchants who trade across the sea.
- The hanging of Lord Stark stimulated his son, who started a war with the house of Lannister.
chronic [ˈkrɑnɪk] chronically: a chronic disease or illness is one that continues for a long time and cannot be cured ⇨ acute慢性的, 延续很长的
- I feel sorry for my father's chronic mental illness.
- My teacher raised money, because of my father's chronic mental illness.
- On arriving home, I was told that my father suffered from chronic mental illness.
depressed [dɪˈprest]: suffering from a medical condition in which you are so unhappy that you cannot live a normal life抑郁的
- The test is designed to help patients who get chronically depressed.
- The patient who gets depressed ran out of money in the inpatient department.
- I almost got depressed when my wife got me under a huge debt.
stress [stres]: continuous feelings of worry about your work or personal life, that prevent you from relaxing ⇨ strain压力
- My wife's laughing at me because of my poor accent put a lot of stress on me.
- Stop putting any stress on your child, or she will get depressed.
- Because of heavy stress, the player developed vomiting after he was defeated in the adversarial game.
--------------------
return to the same state/level: 返回到相同的状态/级别
- The infected boy has returned to a normal state after developing a fever for a day.
- After the conflict had been resolved, their friendship returned to a normal state.
- After returning to a calm state, the king gave up cutting her throat up.
be predicated on sth.: 基于/取决于某事物
- Whether he is dead or alive is predicated on the result of the war between two houses.
- Learning English is predicated on a variety of factors, so I can't figure it out now.
- The king's privilege is predicated on his armies beyond the wall.
have the capacity to do sth.: 有才能/能力去做某事
- A witcher claimed that she had the capacity to save our king's life.
- The boy has the capacity to communicate with a foreigner, even if he doesn't know any foreign language.
- His wife has the capacity to tell the nuance of his gestures.
