#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.16 Expression - Facts
#+begin_verse
In this section we will be talking about expression.
Expression, just like reception, is a very important component of communication.
I'm wondering if you want to start
	by talking about facts and how can we present facts in the best possible manner?
	
Well, I'm almost feeling very nervous now as I have to answer this question.
Because the entire business of academia and maybe education
	is about how we present certain facts effectively.
And I'm not sure when I'm answering your question.
I'm not sure.
Are we doing this right, even, ourselves?
What I can say is that there is obviously a whole scholarship on how can we present facts better.
At the university, we have specialists
	who are helping our graduate students and undergrad students write better
		so that they present facts and ideas better.
And in some disciplines in the sciences
	they have really organized structures for people to present things.
What you did in the experiment, what happened?
What are the results?
How do you analyze the data?
So we have actually very well-established protocols for presenting facts.
And in some disciplines like management schools or in law,
	people are trained to present facts in a certain way
		in order to achieve whatever objective they have.
If you were presenting facts in a court, in an adversarial situation,
	versus you're presenting facts to your client as a lawyer, well, you do it differently.
So we're probably not going to get into details in those.

What we may want to be focusing on is when we're in an interpersonal situation,
	when we're trying to develop a relationship, how we are going to present facts.
And what facts should we be presenting?
I think the important thing here of course is to look at the purpose of our engagement.
Are we trying to build friendship here?
Or are we trying to start a romantic relationship here?
Or are we trying to sell something [LAUGH]?
Or am I trying to resolve conflict?
The kind of facts that you are trying to present
	is always contingent upon the purpose of the engagement.
	
So what do you plan to accomplish?
And then effective communication is based on a good understanding of your partner
	or the person that you're interacting with.
What are this person's N3C?
If you know the person's needs, circumstances, characteristics and capacity,
	then it will be like selecting presentation of facts according.
And I think that's the general principle.
Say for example, if I know that you really have pent-up emotions that you need to be letting out.
Presenting facts that would further provoke you [LAUGH].
[LAUGH] Obviously would not help, right?
So I would be presenting facts that would make it easier for you
	to have an alternate construction of reality and reframe your situation.
And give you maybe the perfect excuse to share some of your feelings.

Let me give you an example.
If I'm talking to someone about being bullied at work.
And you have a lot of pent-up feelings.
I have a range of options to select, to tell you facts about.
I can tell you that you know what, 60% of women working in Canada have experienced that.
That is one set of facts, right?
And if I tell you that well, people who utilize services within the system to address it,
	like harassment offices or HR departments, or talking to a union representative who can help you.
That is another kind of fact that I can present to you.
If I find that you're very interested in talking about the personality of the bullier,
	then I can say, well,
		people who bully are usually people
			with poor self-image and inadequate social skills themselves.
And those people who generally do not even have good mental health.
And I understand that by sharing this with you it is not how accurate the facts are that matters.
It is to give you an opportunity to express your emotions in the way
	that you feel comfortable with.
All right?

So that is, I think, the key idea now, when we're talking about what facts are we communicating.
And then we do not obviously rule out
	that in some situations all you need would be simple, straightforward facts.
Like, I'm going to Japan, [LAUGH] I'm going to Kyoto,
	do you know hotels that are clean, convenient, and affordable?
Then I can be responding to it in a more matter of fact manner.
Expression of facts depends on the purpose of engagement,
	whether you are trying to build a friendship or establishing a romantic relationship.
You should also have a good understanding of your partner's N3C,
		their needs, circumstances, characteristics, and capacity,
	in order to communicate effectively.
If you've forgotten what N3C stands for, please check out module one, lecture 1.6.
#+end_verse
** expression
component [kəmˈpoʊnənt]: n. one of several parts that together make up a whole machine, system etc SYN constituent组成部分
academia [ˌækəˈdimiə]: n. the activities and work done at universities and colleges, or the teachers and students involved in it学术界
scholarship [ˈskɑlərˌʃɪp]: n. the knowledge, work, or methods involved in serious studying学问
specialist [ˈspeʃ(ə)lɪst]: n. someone who knows a lot about a particular subject, or is very skilled at it SYN expert专家
discipline [ˈdɪsəplɪn]: n. an area of knowledge or teaching, especially one such as history, chemistry, mathematics etc that is studied at a university学科
structure [ˈstrʌktʃər]: n. the way in which the parts of something are connected with each other and form a whole, or the thing that these parts make up ⇨ structural结构
analyze [ˈæn(ə)lˌaɪz] analyse: v. to examine or think about something carefully, in order to understand it分析
protocol [ˈproʊtəˌkɔl]: n. a system of rules about the correct way to behave on an official occasion协议
adversarial [ˌædvɜrˈseriəl]: adj. an adversarial system, especially in politics and the law, is one in which two sides oppose and attack each other对抗(性)的
resolve [rɪˈzɑlv]: v. to find a satisfactory way of dealing with a problem or difficulty SYN solve ⇨ settle解决
pent-up [ˌpen-up]: adj. pent-up feelings or energy have not been expressed or used for a long time被压抑的
provoke [prəˈvoʊk]: v. to cause a reaction or feeling, especially a sudden one ⇨ provocation煽动
bully [ˈbʊli] bullier: v.n. someone who uses their strength or power to frighten or hurt someone who is weaker霸凌
harassment [həˈræsmənt]: n. when someone behaves in an unpleasant or threatening way towards you骚扰
personality [ˌpɜrsəˈnæləti]: n. someone’s character, especially the way they behave towards other people个性
--------------------
graduate students: 研究生
undergrad students: 本科生
be contingent upon sth.: 取决于某事物
a range of sth.: 一系列某事物
rule out that + ...: 排除掉+...
stand for sth./sb.: 代表某人/某事
** sentence
component [kəmˈpoʊnənt]: n. one of several parts that together make up a whole machine, system etc SYN constituent组成部分
- Exercise is one of key component of being expert at English.
- These robots are one of key component of the factory.
- Missing key component of the machine, we can't use it to detect gold in the cave.
academia [ˌækəˈdimiə]: n. the activities and work done at universities and colleges, or the teachers and students involved in it学术界
- She has been trained to counsel a king in academia for many years.
- There is a piece of breaking news in academia.
- The scandal in academia was revealed after a journalist had published an article about it in the press.
scholarship [ˈskɑlərˌʃɪp]: n. the knowledge, work, or methods involved in serious studying学问
- Few of us in seat couldn't publish a piece of scholarship for the rest of your life.
- His lifetime of scholarship may end because of being accused of sex harassment.
- The murder he committed in public brought an end to his lifetime of scholarship.
specialist [ˈspeʃ(ə)lɪst]: n. someone who knows a lot about a particular subject, or is very skilled at it SYN expert专家
- The student is alwaysing raising issues about the subject which only specialists are able to answer.
- It's not common that an eminent specialist will come to a hospital in the district.
- As the virus spread all over the city and threatened the whole country, the specialist felt obliged to invest the cause of the epidemic.
discipline [ˈdɪsəplɪn]: n. an area of knowledge or teaching, especially one such as history, chemistry, mathematics etc that is studied at a university学科
- Beyond doubt, the study of an academic discipline has changed his life.
- Consequently, the study of an academic discipline has rarely been utilized in industry.
- The study of this academic discipline gave way to its utilization in industry.
structure [ˈstrʌktʃər]: n. the way in which the parts of something are connected with each other and form a whole, or the thing that these parts make up ⇨ structural结构
- As long as the new programmer is acquinted with the structure of the project, I will leave our company.
- Not acquinted with the structure of the project, the programmer often ran into trouble while coding.
- If you were familiar with the structure of the machine, you would make such stupid remarks.
analyze [ˈæn(ə)lˌaɪz] analyse: v. to examine or think about something carefully, in order to understand it分析
- There is a wonderful tool to analyze the statistics, but we lacks its licence and may take legel risks.
- His method to analyze the statistics of sales became popular with people in the company, so he was promoted by his superior.
- Failing to analyze the statistics, our CEO decided to gamble.
protocol [ˈproʊtəˌkɔl]: n. a system of rules about the correct way to behave on an official occasion协议
- The protocol is made up of two objects and a set of rules. 
- The internet protocol is designed to transfer files between two computers.
- Disobeying the protocol, you can't be connected to your partner. 
adversarial [ˌædvɜrˈseriəl]: adj. an adversarial system, especially in politics and the law, is one in which two sides oppose and attack each other对抗(性)的
- Winners take all in an adversarial game.
- In the adversarial game, he behaved very bravely and was admired by poor and rich alike.
- In the adversarial game, he behaved as a coward and was abused by his fans.
resolve [rɪˈzɑlv]: v. to find a satisfactory way of dealing with a problem or difficulty SYN solve ⇨ settle解决
- Because of lack of social interaction skills, he was reluctant to resolve conflicts between his inferiors.
- I appreciate that you help resolve the conflict between me and my colleague.
- The specialist has been trained to resolve conflict in reltionships for many years.
pent-up [ˌpen-up]: adj. pent-up feelings or energy have not been expressed or used for a long time被压抑的
- Follow your heart and let your pent-up emotions out.
- He is not capable to express his pent-up emotions to his wife.
- Because the prince was killed in action, the king's pent-up emotions led him to start a war with the neighbor.
provoke [prəˈvoʊk]: v. to cause a reaction or feeling, especially a sudden one ⇨ provocation激起
- Tax increase without the approval of the paliament provoked wide-spread criticism and rebellions.
- The behangings of three innocent persons provoked that people held grudge against the king.
- A piece of cake flowing across the street provoked a series of catastrophes.
bully [ˈbʊli] bullier: v.n. someone who uses their strength or power to frighten or hurt someone who is weaker霸凌
- He claimed that he hadn't bullied any his teammate when he was in the team.
- The bullier was accused of robbing his teammate's gift.
- The headmaster rounded up bullier to stand trial in front of all staffs of the high school.
harassment [həˈræsmənt]: n. when someone behaves in an unpleasant or threatening way towards you骚扰
- The sexual harrassment brought about the downfall of the headmaster who had devoted himself to education for nearly twenty years.
- Justice has not been done, when sexual harrassment still prevailed in office.
- The old gentleman, who was always so kind to everybody, was accused of sexual harassment in his youth.
personality [ˌpɜrsəˈnæləti]: n. someone’s character, especially the way they behave towards other people个性,性格
- It is important for us to be able to figure out the personality of the person who you are trying to build relationship with.
- His warlike personality by no means makes him a great knight.
- His vulnerable personality caused him to lose his lead in his class.
--------------------
graduate students: 研究生
- The so-called teacher turned out to be a graduate student.
- Our academy could not afford so many graduate students.
- The graduate student lost his temper when he learnt that he still had a difficult time finding an appropriate job. 
undergrad students: 本科生
- Obviously, our boss takes the undergrad student seriously.
- Nowadays, more and more undergrad students take interest in playing truant from school.
- There are increasing undergrad students who get obsessed with video games after surviving grim high schools.
be contingent upon sth.: 取决于某事物
- Whether you step out of the cell is contingent upon the emotions of the king.
- Whether the watchdogs are kept in closure is contingent upon the number of visitors at the monastery.
- Whether I give you pocket money is contingent upon the money I made this year.
a range of sth.: 一系列某事物
- A range of TV series made me familiar with English voices.
- A range of catastrophes made the great boxer live in poverty for the rest of his life.
- The king set up a range of laws prohibiting digging up graves.
rule out that + ...: 排除掉+...
- The visitor ruled out that he was a robot.
- My wife ruled out that our son had been kidnapped.
- The butcher ruled out that his family had been bombed in an air raid.
stand for sth./sb.: 代表某人/某事
- Standing for our people, I have to do what benefit them.
- Standing for staffs in the high school, the headmaster raised up money to have the classrooms repaired.
- Standing for people in the community, I arranged the settlement with the company.
** sentence2
component [kəmˈpoʊnənt]: n. one of several parts that together make up a whole machine, system etc SYN constituent组成部分
- Exercise is one of the key components of being an expert in English.
- These robots are one of the key components of the factory.
- The machine misses a key component, we can't use it to detect gold in the cave.
academia [ˌækəˈdimiə]: n. the activities and work done at universities and colleges, or the teachers and students involved in it学术界
- She has been trained to counsel a king in academia for many years.
- There is some breaking news about robots in academia.
- The scandal in academia was revealed after a journalist had published an article about it in the press.
scholarship [ˈskɑlərˌʃɪp]: n. the knowledge, work, or methods involved in serious studying学问
- Few of us in seats couldn't publish a piece of scholarship for the rest of our lives.
- His lifetime of scholarship may end because of being accused of sexual harassment.
- The murder he committed in public brought an end to his lifetime of scholarship.
specialist [ˈspeʃ(ə)lɪst]: n. someone who knows a lot about a particular subject, or is very skilled at it SYN expert专家
- The student is always raising issues about the subject which only specialists are able to answer.
- It's not common that an eminent specialist will come to a hospital in the district.
- As the virus spread all over the city and threatened the whole country, the specialist felt obliged to discern the cause of the epidemic.
discipline [ˈdɪsəplɪn]: n. an area of knowledge or teaching, especially one such as history, chemistry, mathematics etc that is studied at a university学科
- Beyond doubt, the study of an academic discipline has changed his life.
- Consequently, the study of an academic discipline has rarely been utilized in industry.
- The study of this academic discipline gave way to its utilization in industry.
structure [ˈstrʌktʃər]: n. the way in which the parts of something are connected with each other and form a whole, or the thing that these parts make up ⇨ structural结构
- As long as the new programmer is acquainted with the structure of the project, I will leave our company.
- Not acquainted with the structure of the project, the programmer often ran into trouble while coding.
- If you were familiar with the structure of the machine, you would make such stupid remarks.
analyze [ˈæn(ə)lˌaɪz] analyse: v. to examine or think about something carefully, in order to understand it分析
- There is a wonderful tool to analyze the statistics, but we lack its licenses and may take legal risks.
- His method of analyzing the statistics of sales became popular with people in the company, so he was promoted by his superior.
- Failing to analyze the statistics, our CEO decided to gamble.
protocol [ˈproʊtəˌkɔl]: n. a system of rules about the correct way to behave on an official occasion协议
- The protocol is made up of two objects and a set of rules. 
- The internet protocol is designed to transfer files between two computers.
- If you disobey the protocol, you can't connect to your partner. 
adversarial [ˌædvɜrˈseriəl]: adj. an adversarial system, especially in politics and the law, is one in which two sides oppose and attack each other对抗(性)的
- Winners take all in an adversarial game.
- In the adversarial game, he behaved very bravely and was admired by poor and rich alike.
- In the adversarial game, he behaved as a coward and was abused by his fans.
resolve [rɪˈzɑlv]: v. to find a satisfactory way of dealing with a problem or difficulty SYN solve ⇨ settle解决
- Because of the lack of social interaction skills, he was reluctant to resolve conflicts between his inferiors.
- I appreciate that you helped resolve the conflict between me and my colleague.
- The specialist has been trained to resolve conflict in relationships for many years.
pent-up [ˌpen-up]: adj. pent-up feelings or energy have not been expressed or used for a long time被压抑的
- Follow your heart and let your pent-up emotions out.
- He is not capable of expressing his pent-up emotions to his wife.
- Because the prince was killed in action, the king's pent-up emotions led him to start a war with the neighbor.
provoke [prəˈvoʊk]: v. to cause a reaction or feeling, especially a sudden one ⇨ provocation激起
- Tax increases without the approval of the parliament provoked widespread criticism and rebellions.
- The hangings of three innocent persons provoked people to hold a grudge against the king.
- A piece of cake flowing across the street provoked a series of catastrophes.
bully [ˈbʊli] bullier: v.n. someone who uses their strength or power to frighten or hurt someone who is weaker霸凌
- He claimed that he hadn't bullied any of his teammates.
- The bullier was accused of robbing his teammate's gift.
- The headmaster rounded up bulliers to stand trial in front of all staff of the high school.
harassment [həˈræsmənt]: n. when someone behaves in an unpleasant or threatening way towards you骚扰
- The sexual harassment brought about the downfall of the headmaster who had devoted himself to education for nearly twenty years.
- Justice has not been done when sexual harassment still prevails in office.
- The old gentleman, who was always so kind to everybody, was accused of sexual harassment in his youth.
personality [ˌpɜrsəˈnæləti]: n. someone’s character, especially the way they behave towards other people个性,性格
- It is important for us to be able to figure out the personality of the person who you are trying to build a relationship with.
- His warlike personality by no means makes him a great knight.
- His vulnerable personality caused him to lose his lead in his class.
--------------------
graduate students: 研究生
- The so-called teacher turned out to be a graduate student.
- Our academy could not afford so many graduate students.
- The graduate student lost his temper when he learned that he still had a difficult time finding an appropriate job. 
undergrad students: 本科生
- Obviously, our boss takes the undergrad student seriously.
- Nowadays, more and more undergrad students take interest in playing truant from school.
- There is an increasing number of undergrad students who get obsessed with video games after surviving grim high schools.
be contingent upon sth.: 取决于某事物
- Whether you step out of the cell is contingent upon the emotions of the king.
- Whether the watchdogs are kept in closure is contingent upon the number of visitors at the monastery.
- Whether I give you pocket money is contingent upon the money I made this year.
a range of sth.: 一系列某事物
- A range of TV series made me familiar with English voices.
- A range of catastrophes made the great boxer live in poverty for the rest of his life.
- The king set up a range of laws prohibiting digging up graves.
rule out that + ...: 排除掉+...
- The visitor ruled out that he was a robot.
- My wife ruled out that our son had been kidnapped.
- The butcher ruled out that his family had been bombed in an air raid.
stand for sth./sb.: 代表某人/某事
- Standing for our people, I have to do what benefits them.
- Standing for the staff in the high school, the headmaster raised money to have the classrooms repaired.
- Standing for people in the community, I arranged the settlement with the company.
