#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.17 Expression - Ideas 1 - Matching N3C
#+begin_verse
It sounds, like you said,
	the purpose of what you're saying and the audience of who you're saying it to
		is really important with facts.
Now I imagine with ideas, it's even more complex than that.

When we're talking about the expression of ideas,
	we want to express in a way that's effective
		and what is effective actually depends on what is the purpose of the communication.
If I'm trying to convince you of something or I want you to do something,
	that's different ways to really communicating an idea.
For instance, if we have an idea of going to do something together.
I was thinking of going on a canoe trip
		and you were thinking of going to a shopping mall
	or the other way around, or I want to go to a concert and you want to go camping.
These are different ideas, and when we say, I don't think this is a good idea,
	what we are essentially saying this is not the way that I wanted, that doesn't address my needs.
When we run into situations like this,
	we try to understand what this other person's needs might be and then try to address it
		and then come up with something that we also want to do.
So that is the negotiation of two sets of needs and circumstances, characteristics,
	and sometimes we have to pay attention to capacity as well.
The N3Cs of two individuals have to match for us to come up with a good idea.
So that is one way to look at it.
#+end_verse
** expression
canoe [kəˈnu]: n. a long light boat that is pointed at both ends and which you move along using a ↑paddle独木舟, 轻舟
match [mætʃ]: v. if one thing matches another, or if two things match, they look attractive together because they are a similar colour, pattern etc ⇨ matching匹配
--------------------
have an/the idea of doing sth.: 有做某事的想法
the other way around, + ...: 倒过来, +...
address sb's need(s): 满足某人的需要
** sentence
canoe [kəˈnu]: n. a long light boat that is pointed at both ends and which you move along using a ↑paddle独木舟, 轻舟
- My mother complained that my father sat in a canoe and did nothing at all all day. 
- There is a canoe we can take advantage of to cross the river.
- Being disused for many years, the canoe needs mending.
match [mætʃ]: v. if one thing matches another, or if two things match, they look attractive together because they are a similar colour, pattern etc ⇨ matching匹配
- If our bluetooths match, we will be able to transfer files between each other.
- The remote control used to manipulate micro wave oven can't match our TV.
- The princess was betrothed to a lord which was thought to match her in the country.
--------------------
have an idea of doing sth.: 有做某事的想法
- Having an idea of going on a vacation at seaside resort, she began to save money and asked her husband for pocket money.
- Our cat has an idea of sneaking into our bedroom and lying on the bed.
- As long as you have an idea of getting divorced, you will be overwhelmed by it all the time.
the other way around, + ...: 倒过来, +...
- The other way around, our enemies lost their hearts because of the lack of sustenance.
- The other way around, our rivals can't find a way to the portal.
- The other way around, you didn't lost 3 yuan and have saved 7 yuan.
address sb's needs: 满足某人的需要
- How to address his wife's needs to go on a vacation at seaside resort drives him mad.
- If I address your needs to keep the cat, you promise me that you will learn it by hearts.
- His father never fails to be affectionate towards him and address his needs in time.
** sentence2
canoe [kəˈnu]: n. a long light boat that is pointed at both ends and which you move along using a ↑paddle独木舟, 轻舟
- My mother complained that my father sat in a canoe and did nothing at all all day. 
- There is a canoe we can take advantage of to cross the river.
- For being disused for many years, the canoe needs mending.
match [mætʃ]: v. if one thing matches another, or if two things match, they look attractive together because they are a similar colour, pattern etc ⇨ matching匹配
- If our Bluetooth match, we will be able to transfer files between each other.
- The remote control used to manipulate micro wave oven can't match our TV.
- The princess was betrothed to a lord who was thought to match her in the country.
--------------------
have an/the idea of doing sth.: 有做某事的想法
- Having an idea of going on a vacation at a seaside resort, she began to save money and asked her husband for pocket money.
- Our cat has the idea of sneaking into our bedroom and lying on the bed.
- As long as you have an idea of getting divorced, you will be overwhelmed by it all the time.
the other way around, + ...: 倒过来, +...
- The other way around, our enemies lost their hearts because of the lack of sustenance.
- The other way around, our rivals can't find a way to the portal.
- The other way around, you didn't lose 3 yuan and have saved 7 yuan.
address sb's need(s): 满足某人的需要
- How to address his wife's need to go on a vacation at a seaside resort drives him mad.
- If I address your needs to keep the cat, you promise me that you will learn it by heart.
- His father never fails to be affectionate towards him and address his needs in time.
