#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-1 4.3 The 6 Domains of Our Lifeworld
#+begin_verse
Okay, so now I can definitely see
	why a simple cost benefit analysis really doesn't do the trick
		in explaining all of our behaviours and understanding of a relationship.
So obviously then we need something a little bit more complex to understand.
Why do we go into relationships and leave them, right?
Yeah, well I think one of frameworks that we use in the SSLD system
	is to look at human life in six domains.
So we look at the Environment, we look at the Body, we look at Motivation, we look at Cognition.
Emotion and Behaviour.
So when people are talking about like a relationship,
	people actually get involved by mobilizing,
		sort of like not exactly an even coordinated action or operation involving these six domains.
		
So say for example, when we are in the same physical environment.
Like when you talk about office romance for instance, right.
And two persons in a same office, but they may seem to be like in the same environment.
But like if one person is sort of in a more senior position and another person in a junior position.
They are not actually in the same environment, alright?

And when we talk about body or physical characteristics.
We understand that you know,
	there is actually no objective value or meaning that we can assign to physical features.
Like say for example, we talk about skin colour.
Some people are attracted to certain skin colour,
	some people feel good about their skin colour, some people don't.
So again it is not standard,
	people have very different takes on their body
		and like we can say the same thing about body build, right?
Like some people prefer people who are taller.
Some people want themselves to be taller.
But some people are just happy with whatever they are.
Some people want to have like more sexy figures, some people don't really pay too much attention.
So and then there are other physical characteristics that some people may pay a lot of attention to.
Like some people are obsessed with hair maybe,
	some people are obsessed with ears or eyes, you know.
So we have an endless list of individual differences when we talk about the body.

And then when we talk about motivation,
	it is also important to recognize
		that not everyone assigns the same significance to relationship.
Some people can be more focused on their family of origin
	than a new relationship that's developing.
Some people want to, you know,
	get this courtship like engagement marriage and raising a family done with that
		then focus on his or her career.
All right, so, but to some people, relationship is central to their lives.
So again, like in the motivation domain, people can be very different.

And when we come to cognition,
	then obviously like we have different values, different world views, different belief systems,
	and then we also spend a fair bit of time earlier in this course
		talking about the scripts that you have internalized.
Or you have started authoring for yourself, and it is very much in the cognitive domain.

And then in the emotional domain,
	then obviously people have different emotional needs, and different emotional patterns.
Some people get very excited by a certain gestures of caring and love, some people don't, right.
Some people have tremendous problems regulating themselves emotionally and get over-aroused.
Some people can get easily frustrated and then get angry.
Some people don't.
So, again, in the emotional domain you have all sorts of individual and interpersonal differences.
And then when it comes to the actual behaviour,
	like how people actually behave and what do they actually say, what do they actually do,
		there's a huge diversity there.
		
So this is why when we look at relationships
	we really have to engage with all these six domains at least,
		[LAUGH] I would say, there actually can be more.
So a simple cost benefit arithmetic analysis, I don't think would do the trick.

To summarize the six domains of life mentioned in lecture.
They are Environment where you are in a given time.
Physical body, characteristics and features of ourselves and others.
Motivation such as needs, wants, incentives for what we are doing.
Cognition, your thoughts, ideas, values and belief system.
Emotion,
	which are your feelings and emotional patterns, needs, reactions, regulation abilities, etc.
And lastly, behaviour of how we actually say something,
	what we do, or how we react in a given interaction.
These six domains
	will provide a more comprehensive picture of the human experience within a relationship.
#+end_verse
** expression
domain [doʊˈmeɪn]: n. an area of land owned and controlled by one person or government, especially in the past领域
motivate [ˈmoʊtɪˌveɪt] motivation: v.n. the reason why you want to do something动机
cognition [kɑɡˈnɪʃ(ə)n]: n. formal the process of knowing, understanding, and learning something SYN thought认知
mobilize [ˈmoʊb(ə)lˌaɪz]: v. to encourage people to support something in an active way动员
coordinate [koʊˈɔrdɪnət]: v. to organize an activity so that the people involved in it work well together and achieve a good result协调
senior [ˈsinjər]: adj. having a higher position, level, or rank ⇨ junior地位较高的, 高级的
junior [ˈdʒuniər]: adj. having a low rank in an organization or profession OPP senior下级, (年龄、职位等)较低者
courtship [ˈkɔrtˌʃɪp]: n. the period of time during which a man and woman have a romantic relationship before marrying求爱,求爱期
internalize [ɪn'tɜ:nəlaɪz]: v. if you internalize a particular belief, attitude, behaviour etc, it becomes part of your character内化
incentive [ɪnˈsentɪv]: n. something that encourages you to work harder, start a new activity etc ⇨ motivation激励
--------------------
do the trick: 奏效,起作用
be attracted to sth.: 被某事物所吸引
body build: 体型
have very different takes on sth.: 对某事有不同的看法
is central to sth./sb.: 对某人/某事是首要的

** sentence
domain [doʊˈmeɪn]: n. an area of land owned and controlled by one person or government, especially in the past领域
- Seeking for extraterrestrial life is inside the domain of astrobiology.
- Making a profit is viewed as the domain of the manager in our boss's eyes.
- Hunting for a puma at large is outside the domian of the expert from the zoo.
motivate [ˈmoʊtɪˌveɪt] motivation: v.n. the reason why you want to do something动机
- I still can't figure out my motivation of learning English.
- Her motivation of getting married is to raise a family.
- The abbot's motivation of taking advantage of laymen is that the monastery had fallen into debt under his predecessors.
cognition [kɑɡˈnɪʃ(ə)n]: n. formal the process of knowing, understanding, and learning something SYN thought认知
- His cognition of the kingdom originates from his predecessors.
- The proverbial, you can't make money beyond your cognition, becomes popular with young people in China.
- What has happened to the doctor who has a skeleton in the cupboard is beyond my cognition.
mobilize [ˈmoʊb(ə)lˌaɪz]: v. to encourage people to support something in an active way动员
- There is an increasing number of people on the Internt mobilizing support for stopping examining virus everyday.
- As the monastery had fallen into debt under his predecessors, he failed to mobilze monks to work.
- Having no mercy on his people, the prince went out his way to mobilize his people to fight on the battlefield.
coordinate [koʊˈɔrdɪnət]: v. to organize an activity so that the people involved in it work well together and achieve a good result协调
- A coordinated gesture she gave in emergency surprised everyone in the theater.
- The woman he fell in love with and was trying to teach dance turned out to be a cooradinated dancer.
- The coordinated gesture takes him two days to exercise.
senior [ˈsinjər]: adj. having a higher position, level, or rank ⇨ junior地位较高的, 高级的
- With the inflation, these jobs that used to require for junior engineer only accepts senior now.
- His motivation of working hard is to become a senior engineer in this company in two years.
- These days, senior programmers don't get a good salary anymore.
junior [ˈdʒuniər]: adj. having a low rank in an organization or profession OPP senior下级, (年龄、职位等)较低者
- It was a junior doctor who inoculated me.
- On arriving home, I found a needle that must be what a junior nurse leave.
- In this company, you will be seeing that a senior engineer reprimands a junior in public.
courtship [ˈkɔrtˌʃɪp]: n. the period of time during which a man and woman have a romantic relationship before marrying求爱,求爱期
- After three weeks courtship, she was betrothed to the French.
- In the period of courtship, his behaviours make her not want to get married to him.
- In the period of courtship, he fell into debt because of expensive gifts she asked for.
internalize [ɪn'tɜ:nəlaɪz]: v. if you internalize a particular belief, attitude, behaviour etc, it becomes part of your character内化
- My method of learning English is to read an article aloud over and over again until I internalized it. 
- This belief seemed to be easy, but I found it difficult to internalize it.
- What Mr. Leo taught in the course has not been internalized by you.
incentive [ɪnˈsentɪv]: n. something that encourages you to work harder, start a new activity etc ⇨ motivation激励
- So to speak, I have no incentive to study English hard.
- Pocket money provided an incentive for me to study hard in my youth.
- My wife lacks any incentive to get the cat fed on time.
--------------------
do the trick: 奏效,起作用
- The experiment we performed will do the trick.
- My capacity of speaking English fluently will do the trick in the market.
- It is hard to say that the monetary policy will do the trick when our country is at war.
be attracted to sth.: 被某事物所吸引
- My wife is attracted to a good-looking bunch of flowers in the grocery.
- The hare was attracted to a piece of grasses and lost the game.
- Mr. Simpson is attracted to the library which is free and open all the day.
body build: 体型
- The man who is trying to lose weight gets obsessed with perfect body build.
- Because of nice body build, he was cast in the role of the hero.
- No woman can't resist temptation to admire his perfect body build.
have very different takes on sth.: 对某事有不同的看法
- The couple who had very different takes on the event quarrelled bitterly.
- Obviously, my wife and I have very different takes on going on a vacation abroad.
- People who have very different takes on strike come to an conclusion now.
is central to sth./sb.: 对某人/某事是首要的
- Raising the family is central to the manager who is often reprimanded by his boss in public.
- Restoring to homeostasis is central to a patient who just had an operation.
- Internalizing the contents of the article is central to me who look forward to using English in practice.
** sentence2
domain [doʊˈmeɪn]: n. an area of land owned and controlled by one person or government, especially in the past领域
- Seeking for extraterrestrial life is inside the domain of astrobiology.
- Making a profit is viewed as the domain of the manager in our boss's eyes.
- Hunting for a puma at large is outside the domain of the expert from the zoo.
motivate [ˈmoʊtɪˌveɪt] motivation: v.n. the reason why you want to do something动机
- I still can't figure out my motivation for learning English.
- Her motivation for getting married is to raise a family.
- The abbot's motivation for taking advantage of laymen is that the monastery had fallen into debt under his predecessors.
cognition [kɑɡˈnɪʃ(ə)n]: n. formal the process of knowing, understanding, and learning something SYN thought认知
- His cognition of the kingdom originates from his predecessors.
- The proverbial, you can't make money beyond your cognition, become popular with young people in China.
- What has happened to the doctor who has a skeleton in the cupboard is beyond my cognition.
mobilize [ˈmoʊb(ə)lˌaɪz]: v. to encourage people to support something in an active way动员
- There is an increasing number of people on the Internet mobilizing support for stopping examining the virus every day.
- As the monastery had fallen into debt under his predecessors, he failed to mobilize monks to work.
- Having no mercy on his people, the prince went out of his way to mobilize his people to fight on the battlefield.
coordinate [koʊˈɔrdɪnət]: v. to organize an activity so that the people involved in it work well together and achieve a good result协调
- A coordinated gesture she gave in an emergency surprised everyone in the theater.
- The woman he fell in love with and was trying to teach dance turned out to be a coordinated dancer.
- The coordinated gesture takes him two days to exercise.
senior [ˈsinjər]: adj. having a higher position, level, or rank ⇨ junior地位较高的, 高级的
- With the inflation, these jobs that used to be required for junior engineers only accept seniors now.
- His motivation for working hard is to become a senior engineer in this company in two years.
- These days, senior programmers don't get a good salary anymore.
junior [ˈdʒuniər]: adj. having a low rank in an organization or profession OPP senior下级, (年龄、职位等)较低者
- It was a junior doctor who inoculated me.
- On arriving home, I found a needle that must be what a junior nurse left.
- In this company, you will see that a senior engineer reprimands a junior in public.
courtship [ˈkɔrtˌʃɪp]: n. the period of time during which a man and woman have a romantic relationship before marrying求爱,求爱期
- After three weeks of courtship, she was betrothed to the French.
- In the period of courtship, his behaviors make her not want to get married to him.
- In the period of courtship, he fell into debt because of expensive gifts she asked for.
internalize [ɪn'tɜ:nəlaɪz]: v. if you internalize a particular belief, attitude, behaviour etc, it becomes part of your character内化
- My method of learning English is to read an article aloud over and over again until I internalize it. 
- This belief seemed to be easy, but I found it difficult to internalize it.
- What Mr. Leo taught in the course has not been internalized by you.
incentive [ɪnˈsentɪv]: n. something that encourages you to work harder, start a new activity etc ⇨ motivation激励
- So to speak, I have no incentive to study English hard.
- Pocket money provided an incentive for me to study hard in my youth.
- My wife lacks any incentive to get the cat fed on time.
--------------------
do the trick: 奏效,起作用
- The experiment we performed will do the trick.
- My capacity to speak English fluently will do the trick in the market.
- It is hard to say that the monetary policy will do the trick when our country is at war.
be attracted to sth.: 被某事物所吸引
- My wife is attracted to a good-looking bunch of flowers in the grocery.
- The hare was attracted to a piece of grass and lost the game.
- Mr. Simpson is attracted to the library which is free and open all day.
body build: 体型
- The man who is trying to lose weight gets obsessed with perfect body build.
- Because of nice body build, he was cast in the role of the hero.
- No woman can't resist the temptation to admire his perfect body build.
have very different takes on sth.: 对某事有不同的看法
- The couple who had very different takes on the event quarrelled bitterly.
- Obviously, my wife and I have very different takes on going on a vacation abroad.
- People who have very different takes on strike come to a conclusion now.
is central to sth./sb.: 对某人/某事是首要的
- Raising the family is central to the manager who is often reprimanded by his boss in public.
- Restoring to homeostasis is central to a patient who just had an operation.
- Internalizing the contents of the article is central to the student who looks forward to using English in practice.
