#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.13 Fear of Intimacy
#+begin_verse
Some people talk a lot about this sort of fear of intimacy that is inherent in some relationships.
And I'm wondering if you can explain what that's all about.
Well, you know, fear is very easily triggered when you get close to someone.
The reason is actually pretty simple
	because when you get intimate, or when you get close to someone, you're more exposed.
	
You're showing more of yourself,
	and to be very honest, most people, majority of people,
		are not 100% wholly comfortable with who they are.
We all have, like you know, unpleasant history,
	we all have our sort of like dark side, things that we ourselves do not even accept.
That can be like trauma, or they are like things that we have done before that we are not proud of.
So, when we are getting close, and these are going to be disclosed.
Some people will feel very anxious.
Like would this person accept this part of me?

So, you can see that even couples who have been together for a long time,
	they're still keeping certain things secret.
They're not telling each other.
It can be like something that is really silly like,
	you know, some insensitive thing that you did as a child, as a teenager
		that you just did not feel proud of,
	but you do not want your partner to know, right?
But then, when you get closer and closer,
	it becomes increasing difficult for you to sort of like not share that,
		because you also want to be understood and taken as who you really are.
So I think as people get closer, right,
	this fear can be triggered because of these like sense of being exposed, and feeling vulnerable.
	
This is what psychologists have been talking about,
	like I don't know all who, like 70 or 80 years now, about this Approach-Avoidance Conflict.
On the one hand, we want to get close while we are approaching,
	but as we get up to a certain point, the discomfort increases and we want to avoid.
So there is tendency to either stop or withdraw.
Fortunately some people would be able to get at the balance point, where it's just comfortable,
	but some people can actually be experiencing this tension all the time,
		you know, like wanting to get closer, but also wanting to protect oneself and stay away.
It can be pretty tormenting for people to be caught in a situation like this.
And it is also not uncommon for people to feel such discomfort
	that you just quit and say okay, like, I'm out of here, it's too much.
	
So this fear of intimacy, I think it's pretty easily understandable
	and well, I just want to say
		that if you're afraid of getting closer, it doesn't mean that you're sick.
It doesn't mean that you have a huge problem.
I just want to say that maybe it's just the human thing, like many people actually have that.
#+end_verse
** expression
inherent [ɪnˈherənt]: adj. a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
wholly [ˈhoʊli]: adv. completely完全的
disclose [dɪsˈkloʊz]: v. to make something publicly known, especially after it has been kept secret SYN reveal揭露
insensitive [ɪnˈsensətɪv]: adj. not noticing, or not taking the care to notice, other people’s feelings, and not realizing when they are upset or when something that you do will upset them麻木不仁的
vulnerable [ˈvʌln(ə)rəb(ə)l]: adj. someone who is vulnerable can be easily harmed or hurt易受攻击的,脆弱的
withdraw [wɪðˈdrɔ]: v. to stop taking part in an activity, belonging to an organization etc, or to make someone do this退出
torment [tɔrˈment]: v. to make someone suffer a lot, especially mentally折磨
--------------------
keep sth. secret: 保持某事秘密
all the time: 一直
** sentence
inherent [ɪnˈherənt]: adj. a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
- It is his inherent characteristics that drove him mad.
- We shouldn't attribute his failure only to his inherent characteristics.
- He attributes the disintegration of the group to the inherent flaws.
wholly [ˈhoʊli]: adv. completely完全的
- Related to his death, I have wholly taken my responsibility all the time.
- He gave me no choice but killing him, my hands are wholly clean.
- Consistent with Shane, I believe that his hands are wholly clean.
disclose [dɪsˈkloʊz]: v. to make something publicly known, especially after it has been kept secret SYN reveal揭露
- The broadcast puts into disclosing scandals about hospitals.
- You still have a chance to disclose the criminal of his death.
- The detective is looking into the scene to disclose the real criminal.
insensitive [ɪnˈsensətɪv]: adj. not noticing, or not taking the care to notice, other people’s feelings, and not realizing when they are upset or when something that you do will upset them麻木不仁的
- The girl observed to the boy who is insensitive to the request of a old lady. 
- I did do something insensitive that I took care of our baby through other channels than getting into panic.
- My wife accused me of being insensitive to our unborn baby. 
vulnerable [ˈvʌln(ə)rəb(ə)l]: adj. someone who is vulnerable can be easily harmed or hurt易受攻击的,脆弱的
- Your works are vulnerable, for there's a huge chance that your child take the power line to your computer.
- My emotions are vulnerable and I am afraid of getting too close to any partner.
- The vulnerable is forced to be betrothed to a lord which she doesn't love.
withdraw [wɪðˈdrɔ]: v. to stop taking part in an activity, belonging to an organization etc, or to make someone do this退出
- The relationship you want to withdraw is precious to me.
- She will withdraw the marriage throughout other channels than committing suicide.
- A bucket of water means a signal of withdrawing the group.
torment [tɔrˈment]: v. to make someone suffer a lot, especially mentally折磨
- The sheriff who fell in love with his brother's wife was being tormented by the relationship.
- Something insensitive I did in the past torments me a great deal.
- Marring to the bastard who slaughtered her people torments her all the time.
--------------------
keep sth. secret: 保持某事秘密
- I want to tell you something that you must keep secret for me.
- If I told you I ran into the walker, would you keep it secret for me?
- Keep it secret, she is actually the infamous witch.
all the time: 一直
- My wife is complaining about the price of the beef all the time.
- She shared her apartment with her precious cat all the time.
- The country is at war with its neighbor all the time.
** sentence2
inherent [ɪnˈherənt]: adj. a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
- It is his inherent characteristics that drove him mad.
- We shouldn't attribute his failure only to his inherent characteristics.
- He attributes the disintegration of the group to the inherent flaws.
wholly [ˈhoʊli]: adv. completely完全的
- Related to his death, I have wholly taken my responsibility all the time.
- He gave me no choice but to kill him, my hands are wholly clean.
- Consistent with Shane, I believe that his hands are wholly clean.
disclose [dɪsˈkloʊz]: v. to make something publicly known, especially after it has been kept secret SYN reveal揭露
- The broadcast that the TV puts into discloses scandals about hospitals.
- You still have a chance to disclose the criminal of his death.
- The detective is looking into the scene to disclose the real criminal.
insensitive [ɪnˈsensətɪv]: adj. not noticing, or not taking the care to notice, other people’s feelings, and not realizing when they are upset or when something that you do will upset them麻木不仁的
- The girl observed to the boy who is insensitive to the request of an old lady. 
- I did do something insensitive, but I took care of our baby through other channels than getting into panic.
- My wife accused me of being insensitive to our unborn baby. 
vulnerable [ˈvʌln(ə)rəb(ə)l]: adj. someone who is vulnerable can be easily harmed or hurt易受攻击的,脆弱的
- Your works are vulnerable, for there's a huge chance that your child take the power line to your computer.
- My emotions are vulnerable and I am afraid of getting too close to any partner.
- The vulnerable is forced to be betrothed to a lord which she doesn't love.
withdraw [wɪðˈdrɔ]: v. to stop taking part in an activity, belonging to an organization etc, or to make someone do this退出
- The relationship you want to withdraw is precious to me.
- She will withdraw the marriage through other channels than committing suicide.
- A bucket of water means a signal of withdrawing the group.
torment [tɔrˈment]: v. to make someone suffer a lot, especially mentally折磨
- The sheriff who fell in love with his brother's wife was being tormented by the relationship.
- Something insensitive I did in the past torments me a great deal.
- Marring to the bastard who slaughtered her people torments her all the time.
--------------------
keep sth. secret: 保持某事秘密
- I want to tell you something that you must keep secret.
- If I told you I ran into the walker, would you keep it secret for me?
- Keep it secret, she is actually the infamous witch.
all the time: 一直
- My wife is complaining about the price of the beef all the time.
- She shared her apartment with her precious cat all the time.
- The country is at war with its neighbor all the time.
