#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.18 Physical Intimacy and Presence
#+begin_verse
So you promised me that we could talk a bit more about physical intimacy.
A big part of a lot of people's idea of physical intimacy comes down to sex.
And then of course, we have a lot of stereotypes about you know who enjoys sex more,
	like you know the male persuasion liking sex more.
People getting into relationships just so they can engage in sexual relations.
Is there truth to any of these stereotypes?
Well, I think with any stereotype, there are always exceptions, right?
So obviously, there are a lot of people who,
	at least think that sex is the thing that they're after.
And then like in the media, we are also increasing the portraying of women
		as active seekers of pleasurable sexual experience,
	which in a way is a good thing, but it also falls to another stereotype.
	
So what is important from my perspective is that people know what they want and what they need.
And we have already said what you want is not necessarily what you need.
Like some people want sex because they need self-affirmation, they need to be accepted.
Some people want sex because they need physical pleasure.
Some people want sex because they need to please other people to get positive feedback.
Some people want sex
	because they need to get to somewhere or get something done through having sex with people.
So, you know like the need that's driving the sex can be very varied,
	and sex is just one of the many ways that people can utilize to meet those needs.
	
So, and then it also takes us back to this idea of physical intimacy versus sex.
Because sex is also very difficult to define, you know.
Bill Clinton once tried, without much success, right,
	convincing the world that oral sex is not really sex.
And maybe, only genital penetration is sex, some people still stick to that kind of imagination.
So we have to understand that physical intimacy actually entails way more than that.
Some people will feel very intimate physically
	when they are sitting by the fire side and reading to each other
		or like taking a walk in the woods.
Some people would feel like physically very intimate just by sitting next to each other.
So like the idea of physical intimacy is actually pretty fluid.
And I don't want to say that like sex is categorically different.
No, it is only part of it.
And then of course, how much physical intimacy is involved in the act of sex itself also varies.
Like when you talk about people who are getting sex from like sex workers, for instance.
They may have sex, but they may not be physically intimate at all, right?
Yeah.
So it is important to be able to distinguish between these two concepts.

Yeah, I mean, even going off of that,
	you can literally not be physically together at all,
		but still be engaged in what some people define as sex.
So, you know, People talk about sexting, or cyber sex,
	or even, you were mentioning earlier in an interesting documentary
		where people had sex telepathically.
So there really is a range in terms of how we define it, isn't there?
Yeah, I think this is actually another good point.
And I don't not want to confuse people, but that's another concept, right,
	which is probably not familiar to most people in the social sciences.
It is the idea of presence.
So you can be like in Toronto, you know, communicating with someone in Ecuador,
	and there's a huge geographical distance, but you can feel the person's presence right here.
And for some people,
	you can actually say that I actually feel physically very intimate with this person
		even though we're just like having a conversation on Skype.
That is totally like comprehensible.
And then when you're talking about people having cyber sex or sexting,
	the extent to which it feels physically present also varies.
Like for some people, they are very conscious,
	we just like this is just the image, this is just text.
To some people, they actually feel the physical presence.
Some people feel their own physical response.
Some people are better able to communicate a physical response to others through images and words.
Some people are less capable.
So like the experience, the quality of the experience actually varies a lot.
Yeah, but I think you're pointing out a very important dimension.
So physical intimacy has to be understood within a context,
	which is more than physical distance or geographical distance, yeah.
#+end_verse
** expression
stereotype [ˈsteriəˌtaɪp]: n. a belief or idea of what a particular type of person or thing is like. Stereotypes are often unfair or untrue刻板印象
persuasion [pərˈsweɪʒ(ə)n]: n. the act of persuading someone to do something说服
sexual [ˈsekʃuəl]: adj. relating to the physical activity of sex性的
seeker [ˈsikər]: n. someone who is trying to find or get something搜索者
pleasurable [ˈpleʒərəbəl]: adj. enjoyable OPP unpleasant快乐的, 愉快的
affirm [əˈfɜrm] affirmation [æfɜrˈmeɪʃ(ə)n]: v.n. to state publicly that something is true SYN confirm确认, 肯定
oral [ˈɔrəl]: adj. spoken, not written口头的
genital [ˈdʒenɪt(ə)l]: n. relating to or affecting the outer sex organs男生殖器
penetrate [ˈpenəˌtreɪt] penetration [ˌpenəˈtreɪʃ(ə)n]: v.n. when something or someone enters or passes through something, especially when this is difficult穿过,插入
categorically [ˌkætəˈɡɔrɪkli]: adv. in such a sure and certain way that there is no doubt无条件的, 绝对的
sexting [ˈsekstɪŋ]: n. n. the activity of sending sexual text messages or sexual pictures of yourself to someone using a mobile phone色情短信
documentary [ˌdɑkjəˈment(ə)ri]: n. a film or a television or radio programme that gives detailed information about a particular subject纪录片
telepathically [ˌtelɪˈpæθɪkli]: adv. someone who is telepathic has a mysterious ability to know what other people are thinking心灵感应地
presence [ˈprezəns]: n. when someone or something is present in a particular place OPP absence存在
comprehensible [ˌkɑmprəˈhensəb(ə)l]: adj. easy to understand SYN understandable OPP incomprehensible可理解的
image [ˈɪmɪdʒ]: n. a picture of an object in a mirror or in the ↑lens of a camera图象
geographical [ˌdʒiəˈɡræfɪk(ə)l]: adj. relating to the place in an area, country etc where something or someone is地理的
--------------------
come down to sth.: 归结为某物
fall to sth.: 归属于某物
next to sb./sth.: 在某人某物旁边
go off of sth.: 脱离某物
** ch.
4-3 4.18 身体亲密与存在感

所以你答应过我，我们可以更多地谈谈身体上的亲密关系。
很多人对身体亲密的理解，很大一部分集中在性上。
当然，我们也有很多关于谁更享受性的刻板印象，
比如认为男性更喜欢性，或者有人进入关系只是为了进行性行为。
这些刻板印象有多少是真实的呢？
嗯，我认为任何刻板印象都有例外，对吧？
显然有很多人，至少认为性是他们追求的目标。
此外，在媒体中，我们也越来越多地看到女性被描绘成
主动寻求愉悦性体验的形象，这在某种程度上是件好事，但也可能成为另一种刻板印象。

从我的角度来看，重要的是人们清楚自己想要什么以及需要什么。
我们之前也说过，想要的不一定是需要的。
比如，有些人想要性，因为他们需要自我肯定，渴望被接受。
有些人想要性，因为他们需要身体的愉悦。
有些人想要性，因为他们希望取悦他人以获得正面反馈。
还有一些人想要性，是因为他们需要通过性行为达到某种目的或实现某些目标。
所以，推动性行为的需求是多种多样的，而性只是人们满足这些需求的众多方式之一。

这也把我们带回到身体亲密与性之间的区别这个话题上。
因为性本身也很难定义。
比如比尔·克林顿曾经尝试说服世人，口交不算真正的性，但并不成功，对吧？
有些人可能仍然认为只有生殖器的插入才算性。
因此，我们必须理解身体亲密实际上包含的范围远远超过性本身。
有些人会觉得，当他们坐在火炉旁为对方朗读，或在树林里散步时，非常亲密。
有些人仅仅是坐在彼此身旁，也能感受到身体上的亲密。
因此，身体亲密的概念实际上是相当灵活的。
我并不是要说性完全与之不同。
不，性只是其中的一部分。
当然，性行为本身涉及的身体亲密程度也有很大差异。
比如，当你谈到人们从性工作者那里获得性行为的情况时，
他们可能发生了性行为，但完全没有身体上的亲密感，对吧？
是的。
所以，能够区分这两个概念非常重要。

是的，甚至在此基础上，
你实际上可以完全没有身体接触，但仍然参与某些人定义为性的行为。
比如，人们谈论的“情色短信（sexting）”或“网络性行为（cyber sex）”，
甚至你之前提到的一个有趣的纪录片，其中有人通过“心灵感应”进行性行为。
所以，如何定义性确实存在很大的范围，对吧？
是的，我认为这是另一个很好的观点。
我不想让人感到困惑，但这里涉及另一个概念，
这可能是大多数人、甚至社会科学领域的人都不太熟悉的，
那就是“存在感”的概念。
比如，你可能人在多伦多，与厄瓜多尔的某人交流，
地理距离非常遥远，但你可能感觉到对方就在你身边。
对于一些人来说，
他们可能会说，即使我们只是通过 Skype 交谈，我仍然感到身体上非常亲密。
这是完全可以理解的。
当谈到人们进行网络性行为或情色短信时，
他们对“身体存在感”的感受也有所不同。
有些人非常清楚这只是影像或文字，
但对另一些人来说，他们确实感受到身体的存在感，
甚至感受到自己的身体反应。
有些人更善于通过图片和文字将身体反应传递给他人，
而有些人不太擅长。
因此，这种体验的质量实际上差异很大。
是的，但我认为你指出了一个非常重要的维度。
身体亲密必须在一个超越身体距离或地理距离的上下文中理解。
** sentence
stereotype [ˈsteriəˌtaɪp]: n. a belief or idea of what a particular type of person or thing is like. Stereotypes are often unfair or untrue刻板印象
- From the onset, you have a stereotype about undergrad students. 
- The stereotype about the fraction of the party is forming in an incremental manner.
- It occurs to me to question the stereotype of workers who are going on a strike.
persuasion [pərˈsweɪʒ(ə)n]: n. the act of persuading someone to do something说服
- You must articulate your persuasion in an incremental way.
- He must posit that your persuasion is justice.
- Your persuasion reminded me of my mom, who was alway complaining about everything around her.
sexual [ˈsekʃuəl]: adj. relating to the physical activity of sex性的
- The professor is trying to teach us the pros and cons of sexual relations.
- The sexual course made in America will put in use next week.
- There is no evidence proving that she had sexual relation with me before she was murdered.
seeker [ˈsikər]: n. someone who is trying to find or get something搜索者
- Your mother is right in being a seeker of lost treasure.
- Let's take another angle to look at those seekers from the plain.
- When some seekers run into serious trouble, these watchdogs often help a great deal.
pleasurable [ˈpleʒərəbəl]: adj. enjoyable OPP unpleasant快乐的, 愉快的
- I must ensure that it will be a pleasurable date because it's your first.
- You have all the reason to believe that your daughter who is betrothed to our king is pleasurable.
- He is reminiscing about the pleasurable date in his high school.
affirm [əˈfɜrm] affirmation [æfɜrˈmeɪʃ(ə)n]: v.n. to state publicly that something is true SYN confirm确认, 肯定
- When I am at times of difficulty, your affirmation really backed up me.
- I can feel your affirmation coming from your eyes.
- The authorities affirmed that there were still Chinese sticking around in the country.
oral [ˈɔrəl]: adj. spoken, not written口头的
- It is disgusting that the president tries convincing that oral sex is not really sex in public.
- Given what your oral story is, we need to go back to the scene to affirm it.
- From his perspective, an oral promise is not defined as an actual promise.
genital [ˈdʒenɪt(ə)l]: n. relating to or affecting the outer sex organs男生殖器
- He finds there is a scar on his genital.
- He had his genital cut when he was trying to rape a policewoman.
- The bastard had his genital cut when he was in prison.
penetrate [ˈpenəˌtreɪt] penetration [ˌpenəˈtreɪʃ(ə)n]: v.n. when something or someone enters or passes through something, especially when this is difficult穿过,插入
- She was naive enough to believe that her boyfriend wouldn't penetrate and beyond doubt, she is pregnant.
- The sexual course sheds light on how genital penetrates while having sex.
- Because the genital penetration kicked in, you must avoid being pregnant.
categorically [ˌkætəˈɡɔrɪkli]: adv. in such a sure and certain way that there is no doubt无条件的, 绝对的
- Everyone in the camp is obligated to obey my instructions categorically.
- A soldier who didn't obey my instructions categorically had his head cut.
- Following in his father's footsteps, he swore his loyalty to the king categorically.
sexting [ˈsekstɪŋ]: n. the activity of sending sexual text messages or sexual pictures of yourself to someone using a mobile phone色情短信
- Maybe you need to talk to your son, whose phone is full of sexting.
- A piece of sexting trys to seduce me to a gamble website.
- The piece of sexting begins with the image of a bunch of flowers.
documentary [ˌdɑkjəˈment(ə)ri]: n. a film or a television or radio programme that gives detailed information about a particular subject纪录片
- The documentary shows us what our earth might be down the road.
- I learn that puma is found in America in a documentary.
- She has a habit of watching documentaries after school.
telepathically [ˌtelɪˈpæθɪkli]: adv. someone who is telepathic has a mysterious ability to know what other people are thinking心灵感应地
- The vicar claimed to have received message from the God telepathically.
- The witch is trying to communicate with her husband telepathically.
- It seems that we fell in love with each other telepathically.
presence [ˈprezəns]: n. when someone or something is present in a particular place OPP absence存在
- The presence of the stray cat gives us a lot of comfort.
- The presence of your father seems to do the trick.
- My cat is attracted to the presence of the butterfly on the grass.
comprehensible [ˌkɑmprəˈhensəb(ə)l]: adj. easy to understand SYN understandable OPP incomprehensible可理解的
- I went through the times of difficulty, so for me his behaviors were comprehensible.
- His obsession with perfect body build is not so comprehensible.
- The contents of his story is so comprehensible that I can't resist the temptation to tell my son.
image [ˈɪmɪdʒ]: n. a picture of an object in a mirror or in the ↑lens of a camera图象
- He has different takes on the image of a worker who is parading.
- The presence of naked images is central to your son's health.
- I don't the website full of naked images.
geographical [ˌdʒiəˈɡræfɪk(ə)l]: adj. relating to the place in an area, country etc where something or someone is地理的
- Despite the geographical distance, he is still manipulating his inferiors to do house chores.
- The geographical distance seems to be the boundary between you and me.
- Despite the geographical distance, the couple still get married in the Internet.
--------------------
come down to sth.: 归结为某物
- The idea of phisical intimacy comes down to sex.
- The source of support comes down to your wife's dedication.
- The sense of being accepted comes down to your recognition.
fall to sth.: 归属于某物
- Your idea of men involed in sexual relations falls to a stereotype.
- Applying 5G to education falls to an unrealistic dream.
- The harnessment of enviornment falls to the sustainable way of developing.
next to sb./sth.: 在某人某物旁边
- Your father is next to your headmaster.
- It come up for me that I could sit next to the girl.
- The cat sitting next to you is mine.
go off of sth.: 脱离某物
- Going off of his influence, she gets down to earth.
- Going off of the authorities' harnessment, many entrepreneurs set up factories in the city.
- Going off of her control, I'm growing up in an incremental way.
** sentence2
stereotype [ˈsteriəˌtaɪp]: n. a belief or idea of what a particular type of person or thing is like. Stereotypes are often unfair or untrue刻板印象
- From the onset, you have a stereotype about undergrad students. 
- The stereotype about the fraction of the party is forming in an incremental manner.
- It occurs to me to question the stereotype of workers who are going on a strike.
persuasion [pərˈsweɪʒ(ə)n]: n. the act of persuading someone to do something说服
- You must articulate your persuasion in an incremental way.
- He must posit that your persuasion is justice.
- Your persuasion reminded me of my mom, who was always complaining about everything around her.
sexual [ˈsekʃuəl]: adj. relating to the physical activity of sex性的
- The professor is trying to teach us the pros and cons of sexual relations.
- The sexual course made in America will be put into use next week.
- There is no evidence proving that she had a sexual relationship with me before she was murdered.
seeker [ˈsikər]: n. someone who is trying to find or get something搜索者
- Your mother is right in being a seeker of lost treasure.
- Let's take another angle to look at those seekers from the plain.
- When some seekers run into serious trouble, these watchdogs often help a great deal.
pleasurable [ˈpleʒərəbəl]: adj. enjoyable OPP unpleasant快乐的, 愉快的
- I must ensure that it will be a pleasurable date because it's your first.
- You have all the reason to believe that your daughter who is betrothed to our king is pleasurable.
- He is reminiscing about the pleasurable date in his high school.
affirm [əˈfɜrm] affirmation [æfɜrˈmeɪʃ(ə)n]: v.n. to state publicly that something is true SYN confirm确认, 肯定
- When I am at times of difficulty, your affirmation really backs me up.
- I can feel your affirmation coming from your eyes.
- The authorities affirmed that there were still Chinese sticking around in the country.
oral [ˈɔrəl]: adj. spoken, not written口头的
- It is disgusting that the president tries convincing that oral sex is not really sex in public.
- Given what your oral story is, we need to go back to the scene to affirm it.
- From his perspective, an oral promise is not defined as an actual promise.
genital [ˈdʒenɪt(ə)l]: n. relating to or affecting the outer sex organs男生殖器的
- He finds there is a genital scar.
- He had his genital organ cut when he was trying to rape a policewoman.
- The bastard had his genital organ cut when he was in prison.
penetrate [ˈpenəˌtreɪt] penetration [ˌpenəˈtreɪʃ(ə)n]: v.n. when something or someone enters or passes through something, especially when this is difficult穿过,插入
- She was naive enough to believe that her boyfriend wouldn't penetrate and beyond doubt, she is pregnant.
- The sexual course sheds light on how genital penetrates while having sex.
- Because the genital penetration kicked in, you must avoid being pregnant.
categorically [ˌkætəˈɡɔrɪkli]: adv. in such a sure and certain way that there is no doubt无条件的, 绝对的
- Everyone in the camp is obligated to obey my instructions categorically.
- A soldier who didn't obey my instructions categorically had his head cut.
- Following in his father's footsteps, he swore his loyalty to the king categorically.
sexting [ˈsekstɪŋ]: n. the activity of sending sexual text messages or sexual pictures of yourself to someone using a mobile phone色情短信
- Maybe you need to talk to your son, whose phone is full of sexting.
- A piece of sexting tries to seduce me to a gambling website.
- The piece of sexting begins with the image of a bunch of flowers.
documentary [ˌdɑkjəˈment(ə)ri]: n. a film or a television or radio programme that gives detailed information about a particular subject纪录片
- The documentary shows us what our earth might be down the road.
- I learned in a documentary that puma is found in America.
- She has a habit of watching documentaries after school.
telepathically [ˌtelɪˈpæθɪkli]: adv. someone who is telepathic has a mysterious ability to know what other people are thinking心灵感应地
- The vicar claimed to have received messages from the god telepathically.
- The witch is trying to communicate with her husband telepathically.
- It seems that we fell in love with each other telepathically.
presence [ˈprezəns]: n. when someone or something is present in a particular place OPP absence存在
- The presence of the stray cat gives us a lot of comfort.
- The presence of your father seems to do the trick.
- My cat is attracted to the presence of the butterfly on the grass.
comprehensible [ˌkɑmprəˈhensəb(ə)l]: adj. easy to understand SYN understandable OPP incomprehensible可理解的
- I went through times of difficulty, so for me his behaviors were comprehensible.
- His obsession with perfect body build is not so comprehensible.
- The contents of his story are so comprehensible that I can't resist the temptation to tell my son.
image [ˈɪmɪdʒ]: n. a picture of an object in a mirror or in the ↑lens of a camera图象
- He has different takes on the image of a worker who is parading.
- The presence of naked images is central to your son's health.
- I don't like the website full of naked images.
geographical [ˌdʒiəˈɡræfɪk(ə)l]: adj. relating to the place in an area, country etc where something or someone is地理的
- Despite the geographical distance, he is still manipulating his inferiors to do house chores.
- The geographical distance seems to be the boundary between you and me.
- Despite the geographical distance, the couple still get married on the Internet.
--------------------
come down to sth.: 归结为某物
- The idea of physical intimacy comes down to sex.
- The source of support comes down to your wife's dedication.
- The sense of being accepted comes down to your recognition.
fall to sth.: 归属于某物
- Your idea of men involved in sexual relations falls to a stereotype.
- Applying 5G to education falls to an unrealistic dream.
- The harnessing of environments falls to the sustainable way of developing.
next to sb./sth.: 在某人某物旁边
- Your father is next to your headmaster.
- It comes up for me that I could sit next to the girl.
- The cat sitting next to you is mine.
go off of sth.: 脱离某物
- Going off of his influence, she gets down to earth.
- Going off of the authorities' harnessing, many entrepreneurs set up factories in the city.
- Going off of her control, I'm growing up in an incremental way.
