#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.14 Fear of Commitment
#+begin_verse
I'm wondering as well though, is fear of commitment, when people are commitment-phobias,
	that's different from a fear of intimacy?
This is very good question.
Some people see commitment and intimacy as closely connected.
Some people may even think that it is equivalent.
And obviously there is also the social script, reinforcing the idea that.
Okay, the most intimate that two individuals can get is to get married, right?
And then this whole idea of marriage
	is suddenly loaded with all these ideas about intimacy and commitment and all that.
	
But I think conceptually, intimacy and commitment can be quite independent.
So, I can easily imagine two individuals being very close, being very intimate with each other.
And they can share everything with each other and they feel very comfortable in that relationship.
But they also realize that they're constantly moving around, and maybe changing and growing.
So they may even consciously, deliberately make the decision to not commit to anything,
	and leave it open.
And I think there is like some beauty in this kind of like open relationship.
And I don't think wanting to commit is necessarily good or bad.

It works well for some people.
Some people actually enjoy the sense of security, predictability, and order.
But for some people, being tied down, committing to something that you do not know.
Especially the commitment also implies
	that you cannot be free to explore who you are, your interest, your potential,
		and grow and develop into the person that you can be.
It's not necessarily a good choice,
	so some people would say you know that's not for me, I just want to move ahead,
		I want to like develop my own life, get a better understanding of who I am.
And maybe later, right, in the later phase of life,
	this person will choose to settle into a more stable relationship.
	
I just do not think that everyone should follow the same script.
Like some people will feel very ready to be committed when they're 16, right?
[LAUGH] Some people will still be figuring things out when they're in their 70s.
So I think each individual can have his or her own schedule so to speak,
	so I don't think the fear of commitment in itself is a problem.
I think finding a relationship that actually works for both partners is the key idea in SSLD.
#+end_verse
** expression
commitment [kəˈmɪtmənt]: n. a promise to do something or to behave in a particular way承诺
phobia [ˈfoʊbiə]: n. a strong unreasonable fear of something恐惧症
equivalent [ɪˈkwɪvələnt]: adj. having the same value, purpose, job etc as a person or thing of a different kind相等的,相当的
--------------------
commit to sth./doing sth.: 承诺做某事
be tied down (by sth.): 被某事所束缚
** ch.
4-3 4.14 对承诺的恐惧

我也在想，恐惧承诺是否与亲密关系的恐惧不同，尤其是当人们有承诺恐惧症时？

这是一个非常好的问题。

有些人把承诺和亲密看作是紧密相连的。有些人甚至认为它们是等同的。显然，社会脚本也在强化这种观念：两个个体之间最亲密的关系就是结婚，对吧？然后婚姻的概念突然被赋予了关于亲密、承诺等诸多的思想。

但我认为，从概念上讲，亲密关系和承诺是可以独立的。我可以很容易想象两个个体非常亲近，彼此之间非常亲密，他们可以分享一切，并且在这段关系中感到非常舒适。但他们也意识到自己在不断变化，可能在成长。因此，他们甚至会有意识地、故意地决定不对任何事情做出承诺，保持开放的状态。

我认为，这种开放的关系中有某种美感。我不认为渴望承诺一定是好事或坏事。

它对某些人来说很合适。有些人其实享受那种安全感、可预测性和秩序感。但对某些人来说，被束缚、承诺做一些自己还不确定的事，特别是承诺意味着你不能自由探索自己是谁，不能自由追寻自己的兴趣、潜力，不能成长和发展成自己可以成为的人。对这些人来说，这不一定是一个好选择。所以有些人会说：“这不适合我，我只想向前走，我想发展自己的生活，更好地理解自己。”也许过一段时间，到了人生的某个阶段，这个人会选择进入一段更稳定的关系。

我只是觉得不是每个人都应该遵循同样的脚本。有些人在16岁时就会觉得非常准备好去承诺，对吧？[笑] 有些人到70岁时仍然在摸索。所以我认为每个人可以有自己的节奏，所谓的“时间表”，因此我认为对承诺的恐惧本身并不是一个问题。我认为，找到一段对双方都有效的关系，才是SSLD中的关键概念。
** sentence
commitment [kəˈmɪtmənt]: n. a promise to do something or to behave in a particular way承诺
- He didn't notice the differences between commitment and intimacy.
- He has been tied down by commitment he made on Valentine's Day.
- He felt guilty of breaking commitment by mistake.
phobia [ˈfoʊbiə]: n. a strong unreasonable fear of something恐惧症
- I has a phobia about social contact.   
- Nowadays, graduate students are developing phobias about finding a respectable job in society.
- Whether your baby has a phobia about study in school is contingent upon your attitude.
equivalent [ɪˈkwɪvələnt]: adj. having the same value, purpose, job etc as a person or thing of a different kind相等的,相当的
- The words like it doesn't matter in such situation is equivalent to I get very angry.
- The money you presented to me is equivalent to a range of catastrophes.
- He tried to rule out some answers that are obviously not equivalent to the formula.
--------------------
commit to sth./doing sth.: 承诺做某事
- The thing you committed to hasn't been completed now.
- The famous director committed to nothing while we were in a romantic relationship.
- The entrepreneur committed to setting up three factories in the suburbs of the city.
be tied down (by sth.): 被某事所束缚
- Tied down by the commitment, the pope had to fight against these nomads on the battlefield.
- The walker is being tied down by the chains.
- Don't be too hard on yourself, you were being tied down by the chain then.
** sentence2
commitment [kəˈmɪtmənt]: n. a promise to do something or to behave in a particular way承诺
- He didn't notice the differences between commitment and intimacy.
- He has been tied down by his commitment on Valentine's Day.
- He felt guilty of breaking commitment by mistake.
phobia [ˈfoʊbiə]: n. a strong unreasonable fear of something恐惧症
- I have a phobia about social contact.   
- Nowadays, graduate students are developing phobias about finding a respectable job in society.
- Whether your baby has a phobia about studying in school is contingent upon your attitude.
equivalent [ɪˈkwɪvələnt]: adj. having the same value, purpose, job etc as a person or thing of a different kind相等的,相当的
- The words like it doesn't matter in such a situation is equivalent to I get very angry.
- The money you presented to me is equivalent to a range of catastrophes.
- He tried to rule out some answers that are obviously not equivalent to the formula.
--------------------
commit to sth./doing sth.: 承诺做某事
- The thing you committed to hasn't been completed now.
- The famous director committed to nothing while we were in a romantic relationship.
- The entrepreneur committed to setting up three factories in the suburbs of the city.
be tied down (by sth.): 被某事所束缚
- Tied down by the commitment, the pope had to fight against these nomads on the battlefield.
- The walker is being tied down by the chains.
- Don't be too hard on yourself, you were being tied down by the chain then.
