#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.12 Idea of Intimacy 2
#+begin_verse
Right and I guess those are some of the things
	that are really important to you in terms of a relationship.
And I mean, I think a lot of things you mentioned are like,
	there's a certain level of intensity there, right?
Which you said maybe not everyone wants in a relationship.
Is that okay if not everyone wants to reach
	that kind of intense growth-enhancing and self-actualization sort of level?
	
Yeah, absolutely.
I would say, you know I said earlier, like I think when I was younger, I was more idealistic.
I was hoping
	that maybe everyone getting involved in relationships should be striving toward the same ideal.
Then as I grow and I gain more experience,
	I realize that is not, first of all, something that everyone wants.
It may not even be something that everyone needs.
It might not even be something that is good for everyone.
Some people are pretty happy being in a relationship that is functional,
	like taking care of each other and then things become routine and familiar.
It gives them a sense of order, a sense of familiarity, of security.
And they just enjoy it, and I think that's perfectly fine.
Like not everyone wants to grow and change and constantly.
So I think that's perfectly okay.

The key thing here is of course that the two partners are wanting the same thing, right?
So like, it would be a problem if someone really wants to grow and develop.
While the other person is saying don't change, I want everything to stay the same.
Then it would create some kind of tension, and sometimes it will not be sustainable.
But I would say if both partners have their needs addressed and gratified
	and they're enjoying the relationship, the relationship is working for them.
I don't see any reason
	why they should be striving towards the same ideals that I am aspiring,
	like, they are just my thing.
#+end_verse
** expression
self-actualization [self][ˌæktʃʊəlaɪ'zeɪʃən]: n. when someone achieves what they want through work or in their personal life
idealistic [aɪˌdiəˈlɪstɪk]: adj. believing that you should live according to high standards and principles, even if they cannot really be achieved, or showing this belief ⇨ realistic理想主义的
functional [ˈfʌŋkʃən(ə)l]: adj. relating to the purpose of something功能的
familiarity [fəˌmɪlɪˈerəti]: n. the quality of being well-known to you熟悉,亲密
aspire [əˈspaɪr]: v. to desire and work towards achieving something important追求
--------------------
strive toward: 努力追求
stay the same: 保持不变
** sentence
self-actualization [self][ˌæktʃʊəlaɪ'zeɪʃən]: n. when someone achieves what they want through work or in their personal life自我实现
- When refering to his self-actualization, he always keeps silence.
- Refering to his self-actualization, he's always talking about his dream of opening a restaurant in the district.
- That means to him his self-actualization will be achieved through the marriage.
idealistic [aɪˌdiəˈlɪstɪk]: adj. believing that you should live according to high standards and principles, even if they cannot really be achieved, or showing this belief ⇨ realistic理想主义的
- That means to an idealistic writer his story will never be played on the stage.
- For that matter, the boy who played truant from school was idealistic.
- My father guesses that the official we tried to present with gift is idealistic.
functional [ˈfʌŋkʃən(ə)l]: adj. relating to the purpose of something功能的
- The sheriff's colleague guesses that their marriage is only functional and his wife is still in love with him.
- Whether the marriage between you and our king is functional is up to your sentiment.
- With regard to friendships, he tends to develop functional relationships with his colleagues.
familiarity [fəˌmɪlɪˈerəti]: n. the quality of being well-known to you熟悉,亲密
- Because of a sense of familiarity, his family has been really growth-enhancing in his youth.
- The tailor looks like my aunt, which gives me a sense of familiarity.
- It shows me that the stray cat has a sense of familiarity.
aspire [əˈspaɪr]: v. to desire and work towards achieving something important追求
- The boy from a single mother family was already in the positon to aspire his goal in the college. 
- The boy is in an advantageous position to aspire the love of our boss's daughter.
- You still don't make sense of your classmate who is aspiring the love of your sister.
--------------------
strive toward: 努力追求
- The conditions I strove toward in my youth are basic in terms of a rich family.
- A large number of immigrants strove toward real estate, which drove up its price.
- You still don't make sense of what you are striking toward.
stay the same: 保持不变
- If we stayed the same, we wouldn't buy an apartment in the uptown.
- Two sheriffs quarrelled bitterly whether they should leave for New York or stay the same.
- If you stayed the same at the edge of the forest, your mother wouldn't get worried about you.
** sentence2
self-actualization [self][ˌæktʃʊəlaɪ'zeɪʃən]: n. when someone achieves what they want through work or in their personal life自我实现
- When referring to his self-actualization, he always keeps silent.
- Referring to his self-actualization, he's always talking about his dream of opening a restaurant in the district.
- That means to him his self-actualization will be achieved through the marriage.
idealistic [aɪˌdiəˈlɪstɪk]: adj. believing that you should live according to high standards and principles, even if they cannot really be achieved, or showing this belief ⇨ realistic理想主义的
- That means to an idealistic writer his story will never be played on the stage.
- For that matter, the boy who played truant from school was idealistic.
- My father guesses that the official we tried to present with a gift is idealistic.
functional [ˈfʌŋkʃən(ə)l]: adj. relating to the purpose of something功能的
- The sheriff's colleague guesses that their marriage is only functional and his wife is still in love with him.
- Whether the marriage between you and our king is functional is up to your sentiment.
- With regard to friendships, he tends to develop functional relationships with his colleagues.
familiarity [fəˌmɪlɪˈerəti]: n. the quality of being well-known to you熟悉,亲密
- Because of a sense of familiarity, his family has been really growth-enhancing in his youth.
- The tailor looks like my aunt, which gives me a sense of familiarity.
- It shows me that the stray cat has a sense of familiarity.
aspire [əˈspaɪr]: v. to desire and work towards achieving something important追求
- The boy was already in the position to aspire to his goal in college. 
- The boy is in an advantageous position to aspire to the love of our boss's daughter.
- You still don't make sense of your classmate who is aspiring to the love of your sister.
--------------------
strive toward: 努力追求
- The conditions I strove toward in my youth are basic in terms of a rich family.
- A large number of immigrants strove toward real estate, which drove up its price.
- You still don't make sense of what you are striking toward.
stay the same: 保持不变
- If we stayed the same, we wouldn't buy an apartment in the uptown.
- Two sheriffs quarreled bitterly about whether they should leave for New York or stay the same.
- If you stayed the same at the edge of the forest, your mother wouldn't get worried about you.
