#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-4 4.21 Growth and Intimacy
#+begin_verse
With the idea of personal growth in a relationship, how does that relate back to intimacy exactly?
Well, like in an earlier comment that I made,
	I was talking about you know how when you are in a safe space that you have created with someone,
and when there is trust, it'd be easier for you to be exploring
		like you know, the not so savoury aspects of yourself,
	then you will be able to look at sort of your own problems, weakness, darkness.
When you are in the safe space, you feel supported, accepted, embraced by the other person.
It's actually easier for you to do that,
	and especially when you're getting positive feedback and support from the other person,
		you may have more courage, motivation to go in and explore yourself, right?
So, that is the idea of that depth we talked about,
	it lets you achieve a deeper understanding of yourself.
And if you have two participants in a relationship doing that together,
	then what we are imagining
		is like a deeper understanding of oneself, and also, deeper mutual understanding, right?
		
And that is our belief that if you have a deeper understanding of your issues,
	and you're able to make sense of them, you'll also be better able to work through them.
Or if those're sort of like difficulties or challenges, you may be better able to overcome, right?
So that is growth, and you become a better person.
You understand yourself better.
You're in better control of your internal processes.
And you can actually be like feeling better to just like be yourself
	without worrying about you know, negative, like dark sides of you showing up and ruining things.
So yeah, I think that is actually a very idealized imagination of
	how people can grow in an intimate relationship.
#+end_verse
** expression
not savoury ['seɪvəri]: adj. not very savoury/none too savoury unpleasant or morally unacceptable ⇨ unsavoury不光彩
mutual [ˈmjutʃuəl]: adj. mutual feelings such as respect, trust, or hatred are feelings that two or more people have for each other ⇨ reciprocal相互的
negative [ˈneɡətɪv]: adj. BAD harmful, unpleasant, or not wanted OPP positive负面的
--------------------
work through (sth.): 解决/克服某事
** ch.
4-4 4.21 成长与亲密

关于在一段关系中实现个人成长，这与亲密关系究竟有什么联系呢？
就像我之前提到的，当你和某个人共同创造了一个安全的空间，并且有了信任，就会更容易去探索你自己那些不那么令人满意的方面。你可以直面自己的问题、弱点和阴暗面。
在这个安全的空间里，你会感到被支持、被接受、被对方拥抱。在这样的状态下，尤其是当你得到对方的积极反馈和支持时，你可能会更有勇气和动力去探索自己，对吗？
这就是我们之前提到的那种深度，它让你对自己有更深入的理解。
如果在一段关系中有两个人一起这样做，那么我们设想的是，双方不仅会对自己有更深的理解，也会对彼此有更深的理解，对吧？

我们相信，当你对自己的问题有更深的理解，并且能够理清它们，你也会更有能力去处理这些问题。或者面对那些困难和挑战时，你可能会更容易克服它们，对吧？
这就是成长。你变成了一个更好的人。你更了解自己，更能掌控自己的内在过程。
这样，你就能更自在地做自己，而不用担心自己的负面或阴暗面突然显现，破坏一切。
所以，我认为这是一个关于人们如何在亲密关系中成长的非常理想化的想象。
** sentence
not savoury ['seɪvəri]: adj. not very savoury/none too savoury unpleasant or morally unacceptable ⇨ unsavoury不光彩
- She tends to keep not savoury aspects of her child to herself.
- The monster tried to insulate his not savoury aspects from the goddess he fell into love with.
- All you want to learn is my not savoury of myself that's what I am unwilling to express.
mutual [ˈmjutʃuəl]: adj. mutual feelings such as respect, trust, or hatred are feelings that two or more people have for each other ⇨ reciprocal相互的
- The understanding between us should be mutual, so you can't keep it to yourself.
- Their mutal love for each other led to the combination of two houses.
- If the  falls to me, we will both share mutual interests.
negative [ˈneɡətɪv]: adj. BAD harmful, unpleasant, or not wanted OPP positive负面的
- The man sitting next to you this afternoon is full of negative emotions.
- You can't express your negative opinions in public, you'd better insulate it from children.
- His idea about history is so negative that his students turn him in.
--------------------
work through (sth.): 解决/克服某事
- Going off my wife, I am still able to work through house chores.
- If you have a competition in terms, you'd better work through your fears.
- There are a lot of troubles that I worked through when I build the project.
** sentence2
not savoury ['seɪvəri]: adj. not very savoury/none too savoury unpleasant or morally unacceptable ⇨ unsavoury不光彩
- She tends to keep not savoury aspects of her child to herself.
- The monster tried to insulate his not savoury aspects from the goddess he fell into love with.
- All you want to learn is my not savoury of myself that's what I am unwilling to express.
mutual [ˈmjutʃuəl]: adj. mutual feelings such as respect, trust, or hatred are feelings that two or more people have for each other ⇨ reciprocal相互的
- The understanding between us should be mutual, so you can't keep it to yourself.
- Their mutual love for each other led to the combination of two houses.
- If the statue falls to me, we will both share mutual interests.
negative [ˈneɡətɪv]: adj. BAD harmful, unpleasant, or not wanted OPP positive负面的
- The man sitting next to you this afternoon is full of negative emotions.
- You can't express your negative opinions in public, you'd better insulate it from children.
- His idea about history is so negative that his students turn him in.
--------------------
work through (sth.): 解决/克服某事
- Going off my wife, I am still able to work through house chores.
- If you have a competition in terms, you'd better work through your fears.
- I worked through a lot of troubles when I built the project.
