#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-4 4.23 Happenings or Rituals?
#+begin_verse
And so you just mentioned something called happenings,
	can you just elaborate on what that is?
A happening is something that is not usual.
That is not routine, right?
And something happens, right?
So say for example, if you celebrate your birthday every year you go to the same bakery.
You get the same like I don't know like chestnut or blueberry cake.
And like you brew the same coffee.
You invite the same people.
That is a birthday party, but is not a happening, right?
It is an event, right?
A happening is like something that is not routine.
It can be planned, it can be staged, but like it is something that is unusual, right? Yeah.

So you do things slightly differently.
Like a surprise party may be a happening.
But if you have a surprise party every year [LAUGH] for your birthday then it.
It doesn't like, it doesn't come across as a surprise anymore.
And it's not a happening.
So, and I know that I'm very biased here.
Like I think happenings are great, right?
But then of course there are people who do not want happenings.
People who want things to be predictable.
They want things to be routine, right?
And so yeah, I understand that.
Like, I'm a happenings person.

But like there are also people who really value, like doing things the same way.
And I have some respect for that
	because one of the things that people are beginning to understand better is the role of rituals.
And you know that certain rituals are basically the same sequence of events that had happened
	or they are performed over and over for hundreds of years or maybe over a thousand years, right?
Right.
People are practicing these traditional rituals, and it still carries a certain force.
It also has an impact on people and makes people feel a sense of stability.
And then the other thing, which we haven't really been talking too much about in this course,
	is the sense of community.
Although we're talking about relationships.
So, very often when people are negotiating a relationship,
	some people have deliberately chosen to follow a certain script, a certain pattern.
Because by doing so, they feel that they are part of a community.
So, one obvious example is when you talk about religious community.
So like some people practice the same religious rituals,
	which may also condition and govern their intimacy behaviour.
When they do that,
	they feel that they're part of the community and they both want that, and that would be fine.
#+end_verse
** expression
bakery [ˈbeɪk(ə)ri]: n. a place where bread and cakes are baked, or a shop where they are sold面包店
chestnut [ˈtʃesˌnʌt]: n. a smooth red-brown nut that you can eat板栗
blueberry [ˈbluˌberi]: n. a small blue fruit, or the plant it grows on蓝莓
brew [bru]: v. if a drink of tea or coffee is brewing, the taste is getting into the hot water沏(茶,咖啡)
predictable [prɪˈdɪktəb(ə)l]: adj. if something or someone is predictable, you know what will happen or what they will do – sometimes used to show disapproval可预言的
--------------------
come across as n./adj.: come over as adj./n.: 显得是...
** ch.
4-4 4.23 事件还是仪式？
你刚刚提到了一个叫做“事件”的东西，你能解释一下那是什么吗？
“事件”是指不寻常的事情。
这不是日常的，对吧？
并且会发生某些事情，对吧？
举个例子，如果你每年庆祝生日，都去同一家面包店。
你买的是同样的，比如栗子蛋糕或者蓝莓蛋糕。
而且你煮的是同样的咖啡。
你邀请的是同样的人。
那是一个生日聚会，但不是一个“事件”，对吧？
那是一个事件，对吧？
“事件”是指不寻常的事情。
它可以是计划好的，也可以是安排好的，但它是非凡的，对吧？
是的。
所以你做事情会有些不同。
比如惊喜派对可能就是一个“事件”。
但如果你每年生日都举办惊喜派对[笑]，那么……
它就不再是惊喜了。
那就不再是“事件”了。
所以，我知道我在这里非常偏颇。
我认为“事件”很棒，对吧？
但当然，也有一些人不喜欢“事件”。
那些希望事物可以预测的人。
他们希望事情是有规律的，对吧？
所以我明白了。
我自己是喜欢“事件”的人。
但也有一些人非常重视做事方式的一致性。
我对这种做法有些尊重，因为人们开始更加理解仪式的作用。
你知道，某些仪式基本上是相同的事件顺序，它们已经持续了几百年，甚至上千年，对吧？
对。
人们正在践行这些传统仪式，它依然具有某种力量。
它对人们产生影响，并使人们感到一种稳定感。
还有另一点，我们在这门课上没怎么提到，那就是社区感。
尽管我们在讨论关系。
所以，当人们在协商关系时，很多时候有人故意选择遵循某种剧本、某种模式。
因为通过这样做，他们感到自己是社区的一部分。
一个明显的例子是当你谈论宗教社区时。
有些人会实践相同的宗教仪式，这也可能影响并规范他们的亲密行为。
当他们这样做时，他们感到自己是社区的一部分，他们都希望这样，这样是可以的。
** sentence
bakery [ˈbeɪk(ə)ri]: n. a place where bread and cakes are baked, or a shop where they are sold面包店
- He worked through his bake skills in the bakery.
- My keys ring must fall on the bakery.
- The parking spot may fall to the bakery.
chestnut [ˈtʃesˌnʌt]: n. a smooth red-brown nut that you can eat板栗
- On one end of spectrum, people feast on chestnut every day.
- When he collected chestnuts outside, he got bogged down with quarrels with natives.
- My wife spoke to me that she was baised towards chestnut cake.
blueberry [ˈbluˌberi]: n. a small blue fruit, or the plant it grows on蓝莓
- Indulge me in a momentary tangent, the blueberry is so expensive that we can't afford it.
- The cultivation of blueberry developed a model for a set of business.
- The sales of blueberry in this month agreed with the model that's published in an article.
brew [bru]: v. if a drink of tea or coffee is brewing, the taste is getting into the hot water沏(茶,咖啡)
- It might be time for us to brew tea and have a rest after hard works.
- There will be more orders to come, so we need to brew more preparing for that.
- The cup of tea is said to be brewed up by your grandfather.
predictable [prɪˈdɪktəb(ə)l]: adj. if something or someone is predictable, you know what will happen or what they will do – sometimes used to show disapproval可预言的
- After we quarrelled bitterly, I realized that our marriage would be predictable and tragic.
- It is predictable that these walkers will stick together in no time.
- The thing that happened yesterday was obviously predictable.
--------------------
come across as n./adj.: come over as adj./n.: 显得是...
- The question that comes across as convoluted is easy to tackle with your patience.
- A surprise birthday that has happened over and over again doesn't come across as a surprise anymore.
- What our cat did came across as intelligent.
** sentence2
bakery [ˈbeɪk(ə)ri]: n. a place where bread and cakes are baked, or a shop where they are sold面包店
- He worked through his baking skills in the bakery.
- My keys ring must fall on the bakery.
- The parking spot may fall to the bakery.
chestnut [ˈtʃesˌnʌt]: n. a smooth red-brown nut that you can eat板栗
- On one end of the spectrum, people feast on chestnuts every day.
- When he collected chestnuts outside, he got bogged down with quarrels with natives.
- My wife told me that she was biased toward chestnut cake.
blueberry [ˈbluˌberi]: n. a small blue fruit, or the plant it grows on蓝莓
- Indulge me in a momentary tangent, the blueberry is so expensive that we can't afford it.
- The cultivation of blueberries developed a model for a set of businesses.
- The sales of blueberries this month agreed with the model that's published in an article.
brew [bru]: v. if a drink of tea or coffee is brewing, the taste is getting into the hot water沏(茶,咖啡)
- It might be time for us to brew tea and rest after hard work.
- There will be more orders to come, so we need to brew more preparing for that.
- The cup of tea is said to be brewed up by your grandfather.
predictable [prɪˈdɪktəb(ə)l]: adj. if something or someone is predictable, you know what will happen or what they will do – sometimes used to show disapproval可预言的
- After we quarreled bitterly, I realized that our marriage would be predictable and tragic.
- It is predictable that these walkers will stick together in no time.
- The thing that happened yesterday was obviously predictable.
--------------------
come across as n./adj.: come over as adj./n.: 显得是...
- The question that comes across as convoluted is easy to tackle with your patience.
- A surprise birthday that has happened over and over again doesn't come across as a surprise anymore.
- What our cat did came across as intelligent.
