#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.4 Six Domains of Transformation - Emotion & Motivation
#+begin_verse
And then, how do needs and motivation fit into that as a kind of other domain?
So following along with this divorce example, which is a kind of transformation,
	some people look at it as like a termination even.
But if you have ongoing unfinished business, like custody of the children you know and all that,
	the relationship actually is not terminated.
It's actually transformed.
So and I just mentioned
	that whatever choice that you have made, there would be like an emotional dimension to it.
And then the emotion obviously is connected to whether your needs are being met or not.

Some people who are in the break up situation,
		or in the divorce situation, or in any kind of drastic transformation,
	the key consideration obviously is like, am I going to be able to meet my needs, right?
So if this is the kind of needs that this relationship is supposed to meet,
	it can be like provision of physical, material resources,
	like the house you live in, like a car to drive, and you know, steady monthly income to depend on.
If I'm going to lose that, like some of my needs will not be met.

Like in this relationship in which I'm depending on for like a sense of security,
	or some people actually are dependent on relationship for their identity.
Like some people do not really know who they are,
	but they are known as the spouse of this famous singer [LAUGH] or >> right,
		the partner of this designer or photographer, you know.
So, and all of a sudden, their identity [LAUGH] would be questioned.
But then, you can also imagine for some people,
	that's exactly because they find a good way to define themselves
		that they feel comfortable to transform the relationship.
So, yeah, like the motivation part is important.
It's the need that are met or not met in the transformed relationship.
And, in our opinion, the most important thing to look at, when you're transforming a relationship
	is to try to make sure that your own needs are being met.
	
And especially like those emotional needs around feeling okay, right?
Mm-hm.
Would be an important aspect as well, so emotional gratification, that kind of thing?
Yeah, I think from our experience,
		working with people going through drastic transformation of relationships,
	the key issue very often is not only about the relationship, it's usually about self.
Like people, are they feeling okay about themselves?
Are they questioning themselves?
Are they questioning their own worth as a human being?
Unfortunately, some people who go through difficult transformation,
		who come to the position of believing that they are worthless,
	or they have failed, or they're not worthwhile, attractive people.
And some people may be so upset and disturbed by this experience
	that they may actually do things that are harmful to themselves.
Yeah, so I think it's really important
	that when we're looking at emotions and needs,
		we will be focusing on the needs that pertains to one's sense of self worth, like identity.
That's really important, yeah.
#+end_verse
** expression
terminate [ˈtɜrmɪˌneɪt] termination: v.n. formal if something terminates, or if you terminate it, it ends SYN end停止, 结束, 终止
ongoing [ˈɑnˌɡoʊɪŋ]: adj. continuing, or continuing to develop正在进行的
custody [ˈkʌstədi]: n. the right to take care of a child, given to one of their parents when they have ↑divorced抚养权
provision [prəˈvɪʒ(ə)n]: n. when you provide something that someone needs now or in the future供应
spouse [spaʊs]: n. a husband or wife配偶(指夫或妻)
worthwhile [ˌwɜrθˈhwaɪl]: adj. if something is worthwhile, it is important or useful, or you gain something from it值得的
--------------------
follow along (with) sth./sb.: 跟随某物/某人
** ch.
5-1 5.4 六大转变领域 - 情感与动机

然后，需求和动机如何融入其中，成为另一种领域呢？
接着以离婚这个例子来说明，这是一种转变。
有些人将其视为一种结束，但如果存在未完成的事情，比如孩子的抚养权问题等等，
那么这种关系实际上并没有真正结束，而是被转变了。
所以，我刚刚提到，不管你做出了什么选择，都会有情感层面的影响。
而情感显然与需求是否得到满足密切相关。
在分手、离婚或任何剧烈转变的情况下，关键的考虑因素显然是：
“我是否能够满足自己的需求？” 对吧？

如果这是这段关系本应该满足的需求，比如提供物质上的资源，
比如你居住的房子、一辆车，或者是一个可以依赖的稳定月收入。
如果我失去了这些，那我的一些需求就无法得到满足。
比如，这段关系让我获得一种安全感，
或者有些人甚至依赖关系来确立自己的身份认同。
有些人可能并不真正了解自己是谁，但他们以“某位著名歌手的配偶” [笑] 或者
“某位设计师或摄影师的伴侣”而闻名。
然而，突然之间，他们的身份认同 [笑] 就会被质疑。

但你也可以想象，对某些人来说，
正是因为他们找到了一个良好的方式去重新定义自己，
他们才会觉得可以轻松地去转变这种关系。
所以，是的，动机部分是很重要的。
转变后的关系是否能满足需求，是关键所在。

在我们看来，转变一段关系时最重要的事情，
就是要确保自己的需求得到满足。
尤其是那些与“感到没问题”相关的情感需求，对吧？
嗯哼。这也是一个很重要的方面，比如情感满足之类的。

根据我们的经验，在与经历剧烈关系转变的人打交道时，
关键问题往往不仅仅是关于关系本身，通常还涉及“自我”。
比如，这些人是否对自己感觉良好？他们是否在质疑自己？
是否在质疑自己作为一个人的价值？
不幸的是，一些经历过痛苦转变的人，
会因此认为自己毫无价值，或者认为自己失败了，
觉得自己不是一个值得被爱、有吸引力的人。

有些人甚至可能因为这一经历而感到极度沮丧和不安，
进而做出一些对自己有害的事情。
所以，我认为，当我们讨论情感和需求时，
我们需要特别关注那些与自我价值感、身份认同相关的需求。
这一点真的很重要，是的。
** sentence
terminate [ˈtɜrmɪˌneɪt] termination: v.n. formal if something terminates, or if you terminate it, it ends SYN end停止, 结束, 终止
- As long as your relationship is terminated, you can't draw any energy from your husband anymore.
- With the terminated marriage, she has to dig up coal in harsher working conditions.
- With the diplomatic relationships terminated, their boundary is being walled off.
ongoing [ˈɑnˌɡoʊɪŋ]: adj. continuing, or continuing to develop正在进行的
- Besides the fifteen tasks, the rest of the tasks is ongoing.
- The strike which was started two weeks ago is ongoing.
- The infection of small pox is ongoing on the continent.
custody [ˈkʌstədi]: n. the right to take care of a child, given to one of their parents when they have ↑divorced抚养权
- My heart is not built from sand and stones, so I will not give up the custody of the children.
- My custody of the children is derived from my property and social position.
- The old man is in posession of the custody of his grandson in a pinch.
provision [prəˈvɪʒ(ə)n]: n. when you provide something that someone needs now or in the future供应
- Without the provision from the empire, we couldn't afford the minimum wage of our soldiers.
- He married me only because of the provision of material resource.
- Your love for is built from sand without the provision of material resource.
spouse [spaʊs]: n. a husband or wife配偶(指夫或妻)
- The fascinating lady is said to be the spouse of a famous singer.
- The spouse of the official is in the face of her husband's downfall.
- The corruption of his spouse during the election brought about his downfall.
worthwhile [ˌwɜrθˈhwaɪl]: adj. if something is worthwhile, it is important or useful, or you gain something from it值得的
- In his youth, he is often transferred between his father's house and his mother's house, which makes him think marriage is not worthwhile.
- Whether the marriage is worthwhile or not depends on whether both of you meet your needs.
- The snack is worthwhile that makes my cat happier than usual.
--------------------
follow along sth./sb.: 跟随某物/某人
- Following along my husband for so long, I am a little tired of him.
- You shouldn't have followed along the tiny fraction of the party.
- Following along my cat out there, I found he has made several girlfriends.
** sentence2
terminate [ˈtɜrmɪˌneɪt] termination: v.n. formal if something terminates, or if you terminate it, it ends SYN end停止, 结束, 终止
- As long as your relationship is terminated, you can't draw any energy from your husband anymore.
- With the terminated marriage, she has to dig up coal in harsher working conditions.
- With the diplomatic relationships terminated, their boundary is being walled off.
ongoing [ˈɑnˌɡoʊɪŋ]: adj. continuing, or continuing to develop正在进行的
- Besides the fifteen tasks, the rest of the tasks are ongoing.
- The strike which was started two weeks ago is ongoing.
- The infection of smallpox is ongoing on the continent.
custody [ˈkʌstədi]: n. the right to take care of a child, given to one of their parents when they have ↑divorced抚养权
- My heart is not built from sand and stones, so I will not give up the custody of the children.
- My custody of the children is derived from my property and social position.
- The old man is in possession of the custody of his grandson in a pinch.
provision [prəˈvɪʒ(ə)n]: n. when you provide something that someone needs now or in the future供应
- Without the provision from the empire, we couldn't afford the minimum wage of our soldiers.
- He married me only because of the provision of material resources.
- Your love for is built from nothing without the provision of material resources.
spouse [spaʊs]: n. a husband or wife配偶(指夫或妻)
- The fascinating lady is said to be the spouse of a famous singer.
- The spouse of the official is aggressive in the face of her husband's downfall.
- The corruption of his spouse during the election brought about his downfall.
worthwhile [ˌwɜrθˈhwaɪl]: adj. if something is worthwhile, it is important or useful, or you gain something from it值得的
- In his youth, he is often transferred between his father's house and his mother's house, which makes him think marriage is not worthwhile.
- Whether the marriage is worthwhile or not depends on whether both of you meet your needs.
- The snack is worthwhile, that makes my cat happier than usual.
--------------------
follow along with sth./sb.: 跟随某物/某人
- Following along with my husband for so long, I am a little tired of him.
- You shouldn't have followed along with the tiny fraction of the party.
- Following along with my cat out there, I found he has made several girlfriends.

