#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.2 Six Domains of Transformation - Environment
#+begin_verse
Right, so you know in this day and age we have so many social connections and relationships,
	some of which ultimately might just fizzle out.
It really just can't last, are time-limited like you said.
Or the other ones I imagine in order for them to possess really have to be transformed.
So what is involved in transforming a relationship?

Well, like maybe we will first offer a conceptual framework for understanding this.
And then like we can also get to
	sort of like be more practical aspect of how to manage those transformation.
Well, in the SSLD model obviously, we talk about human life as having six domains.
And first aspect would be the environment, the reality that we find ourselves in.
So when we are making a drastic transformation in a relationship.
Say for example if two persons who are living together who are married
	and then they decide that they are not going to live together any more.
Or they're going to be separated.
Then obviously the physical environment changes.
Like you are not sleeping on the same bed anymore.
You're not living in the same house any more.
Or you have people who get resettled to another city or another country.
Then again, the very physical reality of the relationship would be changed.
So when do you do that, you know. you have to deal with, to manage like the implication of this.
You may say for example, you used to get rides to work and now you don't get it anymore.
You may have to get a bike and go to work.

And then the other thing is when you go through this transformation,
	the other aspect of external reality that's really important
		is the social scripts that govern this transformation.
Say for example, in the West, in most situations
	when you are separated or when you break up with someone, or when you get divorced,
		many of the social obligations will almost automatically be removed, right.
If someone told you that like I'm breaking up with you
	then you can almost safely assume
		that you don't need to go to his mother's birthday party next February.
So that's the kind of social scripts that sort of direct people, but as we have said before,
	you know like how do people follow those scripts is pretty much like personal choice as well.
	
In SSLD, the six domains of human life
	is a comprehensive framework for understanding human experience within its social context.
One of the domains introduced here is environment and social reality,
	which for instance could be the physical environment.
One of the aspects of external reality that's really important in governing a transformation
	is social script.
Social scripts direct and govern people or their lives
	and it's interesting to also look at how they choose to follow these scripts.
#+end_verse
** expression
drastic [ˈdræstɪk]: adj. extreme and sudden急剧的
implication [ˌɪmplɪˈkeɪʃ(ə)n]: n. a possible future effect or result of an action, event, decision etc可能的影响(作用)
obligation [ˌɑblɪˈɡeɪʃ(ə)n]: n. a moral or legal duty to do something义务
--------------------
fizzle out [ˈfɪz(ə)l]: to gradually end, often in a disappointing or weak way逐渐消散
break up with sb.: 和某人分手
get rides to do sth.: 搭顺风车去做某事
As sb. has said/known ..., + ...: 正如某人说过/知道..., ...
** ch.
5-1 5.2 六个转变领域 - 环境
好的，所以你知道，在当今时代，我们有这么多的社会联系和人际关系，其中有些关系最终可能会逐渐消失，真的无法长久，就像你说的那样是有时间限制的。
或者我想，其他一些关系为了继续下去，必须经历某种转变。
那么，转变一段关系到底涉及什么呢？
嗯，也许我们可以首先提供一个概念框架来理解这一点。
然后，我们也可以更实际地探讨如何管理这些转变。
在SSLD模型中，我们显然将人类生活分为六个领域。
第一个方面是环境，也就是我们所处的现实世界。
因此，当我们在一段关系中进行重大转变时，比如说，两个人住在一起，结了婚，然后他们决定不再住在一起了，或者决定分开。
那么，显然，物理环境会发生变化。
比如你不再睡在同一张床上了。
你们不再住在同一间房子里了。
或者有人搬到另一个城市，另一个国家。
那么，同样，关系的物理现实也会发生改变。
所以当你这么做时，你知道，你必须处理和管理这些转变带来的影响。
举个例子，你以前可能有人载你上班，现在就没有了。
你可能需要买一辆自行车去上班。
然后，当你经历这种转变时，另一个非常重要的外部现实方面是管理这种转变的社会脚本。
比如说，在西方，在大多数情况下，当你分手或离婚时，许多社会义务几乎会自动解除，对吧。
如果有人告诉你“我和你分手了”，那么你几乎可以肯定你不需要参加他母亲明年二月的生日派对了。
这就是那种指导人们行为的社会脚本，但正如我们之前所说的，人们如何遵循这些脚本基本上还是个人的选择。
在SSLD中，人类生活的六个领域是一个全面的框架，用于理解人类在社会背景中的经验。
这里介绍的一个领域是环境和社会现实，例如物理环境。
一个非常重要的外部现实方面是社会脚本。
社会脚本指导和规范人们的生活。
同时，观察人们如何选择遵循这些脚本也是一件非常有趣的事情。
** sentence
drastic [ˈdræstɪk]: adj. extreme and sudden急剧的
- What is most remarkable about this country is a drastic transformation it has made decades.
- The soldier is doing drastic action hitting the surface of tank.
- The empire threatens drastic action towards its neigbor countries.
implication [ˌɪmplɪˈkeɪʃ(ə)n]: n. a possible future effect or result of an action, event, decision etc可能的影响(作用)
- The oil is flowing with the house, so you must deal with the implication of it.
- The army is composed of mutilated soldiers, you should think about the implication of it on the battlefield.
- You should consider the implication of executing people that are the basic building block of the camp.
obligation [ˌɑblɪˈɡeɪʃ(ə)n]: n. a moral or legal duty to do something义务
- My aunt carried obligation to take care of me when I was in high school.
- You have an obligation to clean up the foods in the back of our fridge. 
- She claimed that she had no obligation to wash the fridge.
--------------------
fizzle out [ˈfɪz(ə)l]: to gradually end, often in a disappointing or weak way逐渐消散
- The relationship between me and my friend at kindergarten has already fizzled out.
- The fossil, millions of years in the making, has fizzled out after the operation.
- The mummy is fizzling out because of the failure of the operation.
break up with sb.: 和某人分手
- As long as you break up with Mike, your child will only be a gleam in your eyes. 
- The beautiful woman broke up with an explorer who often risks his life on the flanks of volcanoes.
- Phibee has to break up with her boyfriend who is hired by a Russian university.
get rides to do sth.: 搭顺风车去做某事
- Needless to say, I get rides to work.
- If you break up with me, you can't get rides to go to school anymore.
- My wife used to get rides to go to school.
As sb. has said/known ..., + ...: 正如某人说过/知道..., ...
- As we have learnt from the previous session, many relationships that're timed-limited may fizzle out.
- As we have said before, she has to handle implication of the divorce.
- As we have mentioned before, our cat always desires a delicious snack can.
** sentence2
drastic [ˈdræstɪk]: adj. extreme and sudden急剧的
- What is most remarkable about this country is the drastic transformation it has made over the decades.
- The soldier is doing drastic action hitting the surface of the tank.
- The empire threatens drastic action towards its neighbor countries.
implication [ˌɪmplɪˈkeɪʃ(ə)n]: n. a possible future effect or result of an action, event, decision etc可能的影响(作用)
- The oil is flowing with the house, so you must deal with its implications.
- The army is composed of mutilated soldiers, you should think about the implications of it on the battlefield.
- You should consider the implication of executing people who are the basic building block of the camp.
obligation [ˌɑblɪˈɡeɪʃ(ə)n]: n. a moral or legal duty to do something义务
- My aunt carried an obligation to take care of me when I was in high school.
- You have an obligation to clean up the junk in the back of our fridge. 
- She claimed that she had no obligation to wash the fridge.
--------------------
fizzle out [ˈfɪz(ə)l]: to gradually end, often in a disappointing or weak way逐渐消散
- The relationship between me and my friend at kindergarten has already fizzled out.
- The fossil, millions of years in the making, has fizzled out after the operation.
- The mummy is fizzling out because of the failure of the operation.
break up with sb.: 和某人分手
- As long as you break up with Mike, your child will only be a gleam in your eyes. 
- The beautiful woman broke up with an explorer who often risks his life on the flanks of volcanoes.
- Phibee has to break up with her boyfriend who is hired by a Russian university.
get rides to do sth.: 搭顺风车去做某事
- Needless to say, I get rides to work.
- If you break up with me, you can't get rides to go to school anymore.
- My wife used to get rides to go to school.
As sb. has said/known ..., + ...: 正如某人说过/知道..., ...
- As we have learned from the previous session, many relationships that are timed-limited may fizzle out.
- As we have said before, she has to handle the implications of the divorce.
- As we have mentioned before, our cat always desires a delicious snack can.
