#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.5 Six Domains of Transformation - Body & Behaviour
#+begin_verse
Okay, and then you're kind of talking about
	how we can potentially harm ourselves or that kind of thing?
And that relates then to the body and how the body fits into this whole puzzle?
Yeah.
Yeah, obviously when relationships change, even bodily response will change.
Right.
So we were talking about intimate relationships, for instance,
	like we talked about physical intimacy in previous sessions.
Say for example, you have two persons who are in a physically intimate relationship
	and then they now decide that that it's not what they want to continue with anymore.
So obviously when they see each other,
	all right, their bodies will be stay more distant, and they don't touch each other.
Okay.
You know, and then certain kind of bodily responses will either be ignored or suppressed, right,
		rather than express and encourage,
	so the body will be going through adjustment as well.
And of course, when you're going through like a major transition,
	your emotions, your cognition and everything will also impact on your body.
And it is not uncommon for people going through major transformation in their relationships
	to experience the physical complaints	like you know indigestion or you know headaches.
And sometimes like sleep-related problems can be like bodily responses as well.
So you have the body obviously is implicated in all of this.

Right so literally our somatic or kind of involuntary responses
	are affected by these chief transform relationships.
So ultimately I guess this all boils down to our behaviours and how we end up acting?
Yeah, very true.
So I think from our discussion you can probably see
	that when in SSLD we talk about the six domains,
		but they're not discrete, they're actually interacting with each other.
Yeah.
Right?
So the body like one of the things that some people would do
	is they do something drastic to their body when the relationship is transformed.
Previously, we talked about transformation as it is all about breakups or whatever.
But transformation can also be transforming from friendship to being lovers, right?
Because it's also a transformation.
Transforming from like coworkers to being partners.
So some people would choose to do something drastic to their body,
	like one example that I can easily think of is like people putting tattoos on their body.
All right?
And to mark the change of a relationship, all right.
So it is not uncommon.

so but you're right, like the behaviour is actually connected to
		like our emotions, our motivation, how do we think about things and changes in the environment.
So all these six domains that we have talked about,
		they actually would be like interacting with each other
	and it would be not easy for us to sort of like delineate every possible process.
But I think as a conceptual framework, right,
	people can probably use the six domains as the reference.
To look at, okay, so what are going to change?
And like how this change taking place, and what can we do within each domain?
Right?
Bearing in mind that the boundaries among them are not really discrete and rigid.
#+end_verse
** expression
potentially [pəˈtenʃəli]: adv. something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
bodily [ˈbɑdɪli]: adj. related to the human body身体的
indigestion [ˌɪndɪˈdʒestʃ(ə)n]: n. pain that you get when your stomach cannot break down food that you have eaten ⇨ heartburn消化不良
implicate [ˈɪmplɪˌkeɪt]: v. to show or suggest that someone is involved in a crime or dishonest act牵扯
literally [ˈlɪt(ə)rəli]: adv. according to the most basic or original meaning of a word or expression字面意义地
somatic [səʊ'mætɪk]: adj. Relating to the body, especially as distinct from the mind肉体的
involuntary [ɪnˈvɑlənˌteri]: adj. an involuntary movement, sound, reaction etc is one that you make suddenly and without intending to because you cannot control yourself无意的
discrete [dɪˈskrit]: adj. clearly separate不连续的
tattoo [tæˈtu]: n. a picture or writing that is permanently marked on your skin using a needle and ink纹身
delineate [dɪˈlɪniˌeɪt]: v. to describe or draw something carefully so that people can understand it描绘
rigid [ˈrɪdʒɪd]: adj. rigid methods, systems etc are very strict and difficult to change OPP flexible僵化的
--------------------
boil down to sth.: 归结为某物
Bearing in mind that + ...: keeping in mind that +...牢记着 +...
** ch.
5-1 5.5 六个转变领域——身体与行为

好的，你在谈论我们如何可能伤害自己或类似的事情？
这与身体以及身体在整个问题中的角色有关吗？
是的。
显然，当关系发生变化时，甚至身体的反应也会发生变化。
对。
我们之前谈论的是亲密关系，比如我们在之前的课程中讨论过身体上的亲密。
比如说，两个人处于身体亲密的关系中，但现在他们决定不再继续这样的关系。
显然，当他们见面时，他们的身体会保持更远的距离，不会触碰对方。
好的。
然后某些类型的身体反应要么被忽略，要么被压抑，对吧？
而不是被表达和鼓励，所以身体也会经历调整。
当然，当你经历重大转变时，你的情绪、认知以及一切也会影响到你的身体。
对于那些经历重大关系转变的人来说，出现一些身体上的不适并不罕见，
比如说消化不良或者头痛，有时与睡眠相关的问题也可以是身体的反应。
因此，身体显然参与了这一切。
是的，所以从字面上看，我们的身体反应或者说一些非自主反应都会受到这些重大关系变化的影响。

所以最终，这一切都会归结到我们的行为以及我们如何行动上，对吗？
是的，非常正确。
从我们的讨论中，你可能已经看到，当我们在SSLD中谈论六个领域时，
它们并不是独立的，而是相互作用的。
对吧？
所以，比如身体，有些人在关系发生变化时会对身体做出一些剧烈的改变。
之前我们谈论过，转变主要是关于分手或类似的事情。
但转变也可以是从朋友变成恋人，对吧？
因为这也是一种转变。
从同事变成合作伙伴也是一种转变。
所以有些人会选择对身体做一些剧烈的事情，比如一个我很容易想到的例子是，人们在身体上纹身。
对吧？
以此来标记关系的变化。
所以这并不罕见，但你是对的。
行为实际上与我们的情感、动机、我们如何看待事物以及环境中的变化有关联。
所以我们谈论的这六个领域，
它们实际上是相互作用的，很难明确界定每一个可能的过程。
但我认为，作为一个概念框架，人们可能可以将这六个领域作为参考。
来看一看，好吧，哪些会发生变化？
这些变化是如何发生的，我们在每个领域内可以做些什么？
对吧？
记住，这些领域之间的界限并不是明确和僵硬的。
** sentence
potentially [pəˈtenʃəli]: adv. something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
- The patient succeeded in moblizing the immune system in a potentially harmful situation.
- When facing extreme challenges, your body will regard them as potentially harmful things.
- These programmers are concentrated in potentially serious bugs before it is deployed.
bodily [ˈbɑdɪli]: adj. related to the human body身体的
- Well, your bodily interactions are bonded to how much exercise you have done every day.
- It is just a spontaneously bodily interaction that doesn't mean I dislike you.
- Watch out for the bodily response of the athlete.
indigestion [ˌɪndɪˈdʒestʃ(ə)n]: n. pain that you get when your stomach cannot break down food that you have eaten ⇨ heartburn消化不良
- There is at least one way to relieve your indigestion.
- The relief of her indigestion matters to me, my lord.
- You boy who is suffering from indigestion may have to go to hospital.
implicate [ˈɪmplɪˌkeɪt]: v. to show or suggest that someone is involved in a crime or dishonest act牵扯
- You're the outermost one from our party, and we don't want you to be implicated in the scandal.
- The president being implicated in the scandal is kind of like a systematic corruption.
- All of us implicated in the crime may be executed in front of people.
literally [ˈlɪt(ə)rəli]: adv. according to the most basic or original meaning of a word or expression字面意义地
- The lost turtle is literally in our kitchen. 
- The puma at large is literally wandering around the street.
- You should literally maximize the attraction of two building blocks.
somatic [səʊ'mætɪk]: adj. Relating to the body, especially as distinct from the mind肉体的
- The perfume maximizes the somatic attraction of you and me.
- The ants bunched up together caused my somatic discomfort.
- I don't like sick humor that caused my somatic discomfort.
involuntary [ɪnˈvɑlənˌteri]: adj. an involuntary movement, sound, reaction etc is one that you make suddenly and without intending to because you cannot control yourself无意的
- No one can imagine that an involuntary movement brought about the president's downfall.
- His involuntary reaction led these stones fly apart.
- YOu involuntary reactions doesn't help anyone especially when your wife's suffering from indigestion.
discrete [dɪˈskrit]: adj. clearly separate不连续的
- He is sitting in between the discrete railway.
- The particles that scientists picked up from outter space has been discrete decades before.
- The balls are arranged in 3D space, which is discrete.
tattoo [tæˈtu]: n. a picture or writing that is permanently marked on your skin using a needle and ink纹身
- He put a tattoo on his body in order to bond with his girlfriend.
- I can't join the army because of the damn tattoo which you urged me to put.
- You'd better break up your girlfriend with a tattoo on her face.
delineate [dɪˈlɪniˌeɪt]: v. to describe or draw something carefully so that people can understand it描绘
- It's time to expand our model to delineate the story.
- We have a flat representation of the house delineated by my father.
- Our teacher goes out of his way to delineate the house in three dimensions.
rigid [ˈrɪdʒɪd]: adj. rigid methods, systems etc are very strict and difficult to change OPP flexible僵化的
- Spoiler alert, the congressman chose the rigid way to scrutinize the factory.
- Needless to say, the monastery fell into debt under the rigid abbot.
- Our company didn't make a profit last year due to the rigid system.
--------------------
boil down to sth.: 归结为某物
- My failure of marriage and my child's education boil down to my bad choice at college.
- These six domains boil down to what we want is not necessary what we need.
- The forest fire can't just boil down to a cigarette end.
Bearing in mind that + ...: keeping in mind that +...牢记着 +...
- Bearing in mind that I am your husband who is supposed to protect you from anyone.
- Bearing in mind that you cat is suffering from indigestion.
- Bearing in mind that there is still a puma at large.
** sentence2
potentially [pəˈtenʃəli]: adv. something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
- The patient succeeded in mobilizing the immune system in a potentially harmful situation.
- When facing extreme challenges, your body will regard them as potentially harmful things.
- These programmers are concentrated on potentially serious bugs before it is deployed.
bodily [ˈbɑdɪli]: adj. related to the human body身体的
- Well, your bodily interactions are bonded to how much exercise you have done every day.
- It is just a spontaneous bodily interaction that doesn't mean I dislike you.
- Watch out for the bodily response of the athlete.
indigestion [ˌɪndɪˈdʒestʃ(ə)n]: n. pain that you get when your stomach cannot break down food that you have eaten ⇨ heartburn消化不良
- There is at least one way to relieve your indigestion.
- The relief of her indigestion matters to me, my lord.
- You boy who is suffering from indigestion may have to go to hospital.
implicate [ˈɪmplɪˌkeɪt]: v. to show or suggest that someone is involved in a crime or dishonest act牵扯
- You're the outermost one from our party, and we don't want you to be implicated in the scandal.
- The president being implicated in the scandal is kind of like systematic corruption.
- All of us implicated in the crime may be executed in front of people.
literally [ˈlɪt(ə)rəli]: adv. according to the most basic or original meaning of a word or expression字面意义地
- The lost turtle is literally in our kitchen. 
- The puma at large is literally wandering around the street.
- You should literally maximize the attraction of two building blocks.
somatic [səʊ'mætɪk]: adj. Relating to the body, especially as distinct from the mind肉体的
- The perfume maximizes the somatic attraction of you and me.
- The ants bunched up together caused my somatic discomfort.
- I don't like sick humor that caused my somatic discomfort.
involuntary [ɪnˈvɑlənˌteri]: adj. an involuntary movement, sound, reaction etc is one that you make suddenly and without intending to because you cannot control yourself无意的
- No one can imagine that an involuntary movement brought about the president's downfall.
- His involuntary reaction led these stones to fly apart.
- Your involuntary reactions don't help anyone especially when your wife's suffering from indigestion.
discrete [dɪˈskrit]: adj. clearly separate不连续的
- He is sitting in between the discrete railway.
- The particles picked up from outer space have been discrete decades before.
- The balls are arranged in 3D space, which is discrete.
tattoo [tæˈtu]: n. a picture or writing that is permanently marked on your skin using a needle and ink纹身
- He put a tattoo on his body in order to bond with his girlfriend.
- I can't join the army because of the damn tattoo which you urged me to put.
- You'd better break up your girlfriend with a tattoo on her face.
delineate [dɪˈlɪniˌeɪt]: v. to describe or draw something carefully so that people can understand it描绘
- It's time to expand our model to delineate the story.
- We have a flat representation of the house delineated by my father.
- Our teacher goes out of his way to delineate the house in three dimensions.
rigid [ˈrɪdʒɪd]: adj. rigid methods, systems etc are very strict and difficult to change OPP flexible僵化的
- Spoiler alert, the congressman chose the rigid way to scrutinize the factory.
- Needless to say, the monastery fell into debt under the rigid abbot.
- Our company didn't make a profit last year due to the rigid system.
--------------------
boil down to sth.: 归结为某物
- My failure in marriage and my child's education boil down to my bad choice at college.
- These six domains boil down to what we want is not necessarily what we need.
- The forest fire can't just boil down to a cigarette end.
Bearing in mind that + ...: keeping in mind that +...牢记着 +...
- Bearing in mind that I am your husband who is supposed to protect you from anyone.
- Bearing in mind that your cat is suffering from indigestion.
- Bearing in mind that there is still a puma at large.
