#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.3 Six Domains of Transformation - Cognition
#+begin_verse
And kind of going off of the scripts, from my understanding it's not just part of the environment.
But there's also really a cognitive aspect to following the script, right?
That's true, like people first of all they choose a script they want to follow.
And then in whatever relationship they may negotiate the kind of script that they would both follow.
And then if some of the people who have been taking this course
	might have started authoring a script that is quite different than the prevailing social script.
So all these are possible.
So it is important that when the reality changes and the environment changes
	and then we're making reference to whatever's shared social script out there.
Again, some kind of effective communication might be necessary.

And a counter example is when this breaks down.
Like when you have really aggressive hostile divorces, for instance.
Then you know, they do not really have a script that both party would follow.
Like, you know, should I have the dog and should you keep those records
	or like who owns the house, who owns the boat?
When they are in high conflict
	it means that there is no agreement on the script, so part of that is cognitive.
But you can also see that a good part of that is very emotional as well.
#+end_verse
** expression
cognitive [ˈkɑɡnətɪv]: adj. related to the process of knowing, understanding, and learning something认知的, 认识的
author [ˈɔθər]: v. to be the writer of a book, report etc编写
aggressive [əˈɡresɪv]: adj.  behaving in an angry threatening way, as if you want to fight or attack someone好斗的,侵略性的,攻击性的
hostile [ˈhɑst(ə)l]: adj. angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
own [oʊn]: v. to have something which belongs to you, especially because you have bought it, been given it etc and it is legally yours ⇨ possess拥有
--------------------
make reference to sth.: refer to参考/提及/指代...
out there: 在那里
in conflict: 争斗中
** ch.
5-1 5.3 六个转变领域 - 认知
而且从剧本的角度来说，根据我的理解，这不仅仅是环境的一部分，
而且遵循剧本的过程中其实也有一个认知方面的因素，对吧？
这是真的，首先人们会选择他们想要遵循的剧本。
然后在任何关系中，他们可能会协商出一个双方都能遵循的剧本。
如果一些参加过这个课程的人可能已经开始编写一个与现有社会剧本截然不同的剧本，那也是可能的。
所以这些都是可能的。
因此，当现实发生变化，环境发生变化，我们开始参考外面共享的社会剧本时，
有效的沟通可能是必要的。
一个反例是当这种沟通破裂时，比如在非常激烈的敌对离婚中，
那时你知道，双方并没有共同遵循的剧本。
比如说，我是不是该养狗，你是不是该保留那些记录，
或者谁拥有房子，谁拥有船？
当他们处于高度冲突时，就意味着他们在剧本上没有达成一致，
所以部分问题是认知上的。
但你也可以看到，这其中有很大一部分其实也是情感上的。
** sentence
cognitive [ˈkɑɡnətɪv]: adj. related to the process of knowing, understanding, and learning something认知的, 认识的
- There's a cognitive aspect to sharing the same basic goal.
- I have an idea of taking a course about cognitive behavioral therapy.
- It is the cognitive issue that prevents you from perpetuating the existence of the country.
author [ˈɔθər]: v. to be the writer of a book, report etc编写
- The philosopher stayed alive in prison to author the book called the Republic. 
- The entrepreneur sets up some workshops in which writers author popular novels in the Internet.
- The entrepreneur can't resist the temptation to keep these writers authoring novels.
aggressive [əˈɡresɪv]: adj.  behaving in an angry threatening way, as if you want to fight or attack someone好斗的,侵略性的
- These aggressive knights are unable to read those assembly instructions.
- The empire was getting aggressive for raw materials on the continent.
- If the workers had got paid, they wouldn't have been aggressive and have stopped going on a strike.
hostile [ˈhɑst(ə)l]: adj. angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
- Why don't send your hostile mail off?
- The worker became hostile when he was asked to assemble those parts into robots after work.
- The hostile elephant will be transported to a forest that's full of fruits.
own [oʊn]: v. to have something which belongs to you, especially because you have bought it, been given it etc and it is legally yours ⇨ possess拥有
- The old man who owns two daughters was killed in action.
- The shrewd businessman was said to own an expensive antique shop.
- I am always dreaming of owing a big house in the district.
--------------------
make reference to sth.: refer to提及到某事
- We are making reference to whatever social scripts we share.
- He is constantly making reference to my post, which disturbs me a great deal.
- I can see the light in his eyes when I make reference to his cat.
out there: 在那里
- He is burning some houses down out there.
- The deer and the boy were simultaneously shot by a hunter out there.
- They were bitten by some walkers out there.
in conflict: 争斗中
- The party whip plotted to bring about his downfall in conflict.
- You shouldn't have gathered the two coworkers in conflict.
- The couples in conflict decided to get divorced although it's almost possible to do it legally in their cultures.
** sentence2
cognitive [ˈkɑɡnətɪv]: adj. related to the process of knowing, understanding, and learning something认知的, 认识的
- There's a cognitive aspect to sharing the same basic goal.
- I have an idea of taking a course about cognitive behavioral therapy.
- It is the cognitive issue that prevents you from perpetuating the existence of the country.
author [ˈɔθər]: v. to be the writer of a book, report etc编写
- The philosopher stayed alive in prison to author the book called The Republic. 
- The entrepreneur sets up some workshops in which writers author popular novels on the Internet.
- The entrepreneur can't resist the temptation to keep these writers authoring novels.
aggressive [əˈɡresɪv]: adj.  behaving in an angry threatening way, as if you want to fight or attack someone好斗的,侵略性的
- These aggressive knights are unable to read those assembly instructions.
- The empire was getting aggressive for raw materials on the continent.
- If the workers had been paid, they wouldn't have been aggressive and have stopped going on strike.
hostile [ˈhɑst(ə)l]: adj. angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
- Why don't you send your hostile mail off?
- The worker became hostile when he was asked to assemble those parts into robots after work.
- The hostile elephant will be transported to a forest that's full of fruits.
own [oʊn]: v. to have something which belongs to you, especially because you have bought it, been given it etc and it is legally yours ⇨ possess拥有
- The old man who owns two daughters was killed in action.
- The shrewd businessman was said to own an expensive antique shop.
- I dream of owning a big house in the district.
--------------------
make reference to sth.: refer to提及到某事
- We made reference to whatever social scripts we shared.
- He is constantly making reference to my post, which disturbs me a great deal.
- I can see the light in his eyes when I make reference to his cat.
out there: 在那里
- He is burning some houses down out there.
- The deer and the boy were simultaneously shot by a hunter out there.
- They were bitten by some walkers out there.
in conflict: 争斗中
- The party whip plotted to bring about his downfall in conflict.
- You shouldn't have gathered the two coworkers in conflict.
- The couples in conflict decided to get divorced although it's almost possible to do it legally in their cultures.
