#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 05 The facts
#+begin_verse
What was the consequence of the editor's insistence on facts and statistics?

Editors of newspapers and magazines often *go to extremes*
	to *provide their readers with* unimportant facts and statistics.
Last year a journalist had *been instructed by* a well-known magazine
	to *write an article on* the president's palace in a new African republic.
When the article arrived, the editor read the first sentence and then refused to publish it.
The article began: 'Hundreds of steps lead to the high wall which surrounds the president's palace.'
The editor at once sent the journalist a fax
	instructing him to *find out* the exact number of steps and the height of the wall.

The journalist immediately set out to obtain these important facts,
	but he *took a long time to send* them.
Meanwhile, the editor was *getting impatient*, for the magazine would soon *go to press*.
He sent the journalist two more faxes, but received no reply.
He sent yet another fax informing the journalist that if he did not reply soon he would *be fired*.
When the journalist again failed to reply,
	the editor reluctantly *published the article* as it had originally been written.
A week later, the editor at last received a fax from the journalist.
Not only had the poor man been arrested, but he had been sent to prison as well.
However, he had at last been allowed to *send a fax*
	in which he *informed the editor*
		that he had been arrested
			while counting the 1084 steps
				leading to the fifteen-foot wall which surrounded the president's palace.
#+end_verse
** expression
editor: [ˈedɪtər] n. edit v.编辑
extreme: [ɪkˈstrim] n.极端
statistics: [stə'tɪstɪks] n. statistic 统计数字
journalist: [ˈdʒɜrn(ə)lɪst] n.新闻记者
president: [ˈprezɪdənt] n.总统
palace: [ˈpæləs] n.王宫;宏伟的住宅
publish: [ˈpʌblɪʃ] v.出版
fax: [fæks] n.v.传真
impatient: [ɪmˈpeɪʃ(ə)nt] adj.不耐烦的
fire: [faɪr] v.解雇
originally: [əˈrɪdʒən(ə)li] adv.起初,原先,从前

go to extreme(s) to do sth.: 极端地做某事
publish + a book/an article/report: 出版一本书/一篇文章/报告
send sb. a fax: 给某人发传真
get impatient: 变得不耐烦
get/be fired: 被炒鱿鱼
--------------------
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until
--------------------
provide sb. with sth.: 为某人提供某物
sb. be instructed to do sth.: 某人被指示去做某事
instruct sb. to do sth.: 指示某人去做某事
write an article on/about sth.: 写一篇关于某事的文章
find out sth.: to discover, learn, or verify something发现,查明某事
sb. take a long time to do sth.: 某人花了很长时间去做某事
go to press: 送印
inform sb. that + ...: 通知某人+...

** vocabulary
journalist: reporter
instructed: ordered
well-known: famous
publish: print, issue
surrounds: encircles
fired: dismissed
reluctantly: unwillingly

** words
editor [ˈedɪtər] n．编辑
extreme [ɪkˈstrim] n．极端
statistics [stə'tɪstɪks] n．统计数字
journalist [ˈdʒɜrn(ə)lɪst] n．新闻记者
president [ˈprezɪdənt] n．总统
palace [ˈpæləs] n．王宫；宏伟的住宅
publish [ˈpʌblɪʃ] v．出版
fax [fæks] n．传真
impatient [ɪmˈpeɪʃ(ə)nt] adj. 不耐烦的
fire [faɪr] v．解雇
originally [əˈrɪdʒən(ə)li] adv．起初，原先，从前

** DONE 单词造句
CLOSED: [2023-10-28 Sat 19:52]
editor n. edit v.
- May I have the privilege of meeting the editor?
- The editor usually calls me Sherwin.
- Today, the CEO have the editor posted to a remote village.
- The editor got so angry that he refused to publish the article.
- The editor was instructed in publishing it soon.
extreme n.  go to extreme(s) to do sth.
- The girl is making every effort to go to extremes.
- He is always going to extremes to do every task.
- Even if you went to extremes to make money, you wouldn't be happy.
- People often go to extremes to keep status quo.
- Because of his taking work seriously, he often goes to extremes.
statistics n. statistic
- To the authorities, I am just another statistic.
- The statistics suggest that she often goes home by bus.
- The statistics suggest that he couldn't afford the house.
- The statistics suggest that there are more people being fired than last year.
- The statistics suggest that people who work in office earn only half much as they used to.
journalist n.
- The journalist was too embarrassed to tell anything about the palace to his editor.
- This can give rise to curious situation, as it did in the case of the journalist
	  who was sent to prison.
- The journalist often goes to extreme to figure out the facts and statistics.
- The book which was publish yesterday was edited by the journalist.
- The journalist feels that his rise in status is well worth the loss of money.
president n.
- The president changed into suit for the simple reason that he likes it.
- The president was willing to tell stories.
- The president was refered to as the grest man in American.
- The president goes to extremes to keep the status quo.
- 'Status quo.' The president ordered his men to do nothing.
palace n.
- There are 1094 steps which leads to the wall which surrounds the palace.
- The palace was burnt down for one reason or another.
- From now on, people can visit the palace at liberty.
- Despite the fact that the palace was fired in 1989.
- In the most sacred room of the palace, they found the fragments of fifteen statuses.
publish v.  publish + a book/an article/report
- The journalist was amazed to find that his report had been published.
- We're publishing the report in an hour.
- The editor may have published the article already.
- The editor can't have published the article.
- The editor must have published the article.
fax n.v.  send sb. a fax
- I'll send you a fax. Let's keep in touch with each other.
- He has sent me a fax in which he told me his wife was pregnant.
- I was too embarrased to send him any fax.
- He has sent faxs hald as many as you.
- From now on, it's easy for us to send anyone a fax in office.
impatient adj.  get impatient
- The secret of success is don't get impatient.
- In the end, the flight attendant got so impatinent that she lost her temper.
- Don't be impatient and everything will soon return to normal.
- Don't be impatient. Let's make it official.
- You got so impatient that you didn't double check the garage.
fire v.  get/be fired
- I regret to inform you that you're fired.
- I was disappointed to learn that I got fired.
- When the news came to me that I am fired, I bursted out tears.
- No one could account for the fact that she got fired.
- You are responsible for this failure, so you get fired.
originally adv.
- I was wonder who lived there originally.
- I have difficulty in finding out where she is from originally.
- This sort of snake is found in America originally.
- The palace was originally designed by the artiste, Mr. Sherwin.
- That stupid remark was originally made by the journalist.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-10-28 Sat 20:28]
** DONE 复习二册语法(笔记或视频) & 红皮书
CLOSED: [2023-10-28 Sat 19:52]
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until
** DONE 习惯用法造句
CLOSED: [2023-10-28 Sat 20:13]
provide sb. with sth.
- Have you ever asked a complete stranger to provide you with toilet paper?
- The journalist failed to provide the editor with true facts and statistics.
- When I was a young boy, my father provided me with many pirate stories.
- I was too embarrassed to provide him with any drink.
- I promise if you provide me with some apples, I will give you fifty pences.
sb. be instructed to do sth.  instruct sb. to do sth.
- I was instructed to do a lot of work when I was very young.
- My grandfather instructed us to help him.
- The soldiers were instructed to stand attention to the minister.
- My boss is always instructing me to send his companies faxes.
- Despite the fact that the cat was instructed to press the button.
write an article on/about sth.
- You don't have the prvilege of writing an article on my private life.
- It's none of your business. Don't write any article about it.
- People who do manual work rarely write an article on their lifes.
- He is writting an article on the president's palace which dated from fifteenth century.
- He refused to write an article about this meeting.
find out sth.
- I did find out what to do in the future.
- She found out that her boyfriend is going to give her a surprise.
- I find out that I don't get enough money to buy a house in China city.
- The detective immediately found out the truth that she had killed her husband.
- The elderly finds out the fact that the boy is palying truent from school.
sb. take a long time to do sth.
- I took a long time to find a job.
- He took a long time to stay out of limelight.
- He took a long time to make a profit.
- The cat took a long time to prevent himself from the water of stream.
- She took a long time to take photographs on vacation.
go to press
- I am curious to find out whether he succeeded in going to press.
- We are due to go to press in an hour.
- We needn't have gone to press.
- Who entitled you to go to press in such short time?
- The editor was instructed to go to press in two hours.
inform sb. that + ...
- I regret to inform you that your father is fired.
- I inform you that you must keep the secret.
- I inform you that it's your turn.
- I inform you that you will have the authority to meet the queen.
- I inform you that the forest fire was put out.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-10-28 Sat 20:28]
** DONE Ask me if 写+读
CLOSED: [2023-10-28 Sat 20:34]
1. The editor refused to publish the article. Why
	 Why did the editor refuse to publish the article?
2. The article began: 'Hundreds of steps...' How
		How did the article begin?
3. The editor sent the journalist a fax. Why
		Why did the editor send the journalist a fax?
4. The journalist would be fired. Why
		Why would the journalist be fired?
5. The journalist failed to reply. Why
		Why did the journalist fail to reply?
6. The editor published the article. When
	 When did the editor publish the article?
7. The editor received a fax. When
	 When did the editor receive a fax?
8. The poor man had been arrested. Why
	 Why had the poor man been arrested?
9. He had been allowed to send a fax. What ... do
	 What had he been allowed to do?
10. He had been counting the steps. What
		What had he been counting?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-10-28 Sat 20:43]
Though the journalist immediately set out to get the facts
		after receiving the instructions from his editor,
	he didn't send them at once.
Meanwhile, the editor was getting impatient,
	so he sent three faxes,
	finally threatening to fire him.
When the last fax wasn't answered, the article was printed in its original form.
The journalist at last sent a fax a week later
	explaining that he had been imprisoned
		because of counting the steps and measuring the height of the wall.

** DONE tell the story 口语复述
CLOSED: [2023-10-28 Sat 20:48]
** DONE composition 阅读 或 写作
CLOSED: [2023-10-28 Sat 20:55]
The journalist counted the number of steps
	as he wearily climbed up to the high wall surrounding the president's palace.
On arriving at the main gate, he sat down to get his breath back.
He then produced a tape measure in order to measure the wall.
While he was busy measuring the wall,
	a policeman approached him and asked him what he was doing.
Though the journalist explained
	he was a reporter and his editor had asked him to find out the exact height of the wall,
	the policeman refused to believe him.
He was arrested and sent to prison
	because the police though that he might be a spy
		or might even want to assassinate the president.
When the journalist insisted he was innocent,
	he made things worse for himself.
This proved to the police
	that the man certainly was guilty and deserved to stay in prison indefinitely.

** Topics for discussion
