#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 07 Mutilated ladies
#+begin_verse
Why did Jane cook John's wallet?

Has it ever happened to you?
Have you ever put your trousers in the washing machine
	and then remembered there was a large bank note in your back pocket?
When you rescued your trousers, did you find the note was whiter than white?
People who live in Britain needn't despair
	when they make mistakes like this (and a lot of people do)!
Fortunately for them, the Bank of England has a team
	called Mutilated Ladies which *deals with* claims from people
		who fed their money to a machine or to their dogs.
Dogs, it seems, love to chew up money!

A recent case concerns Jane Butlin whose fiance, John, runs a successful furniture business.
John had a very good day
	and put his wallet containing 3000 dollars into the microwave oven *for safekeeping*.
Then he and Jane *went horse-riding*.
When they got home, Jane cooked their dinner in the microwave oven and without realizing it,
	cooked her fiance's wallet as well.
*Imagine their dismay when* they found a beautifully-cooked wallet and notes turned to ash!
John went to see his bank manager who sent the remains of wallet
	and the money to the special department of the Bank of England in Newcastle: the Mutilated Ladies!
They examined the remains and John got all his money back.
'*So long as* there's something to identify, we will give people their money back,'
	said a spokeswoman for the Bank,
'Last year, we paid 1.5 million dollars on 21,000 claims.'
#+end_verse
** expression
mutilate: [ˈmjut(ə)lˌeɪt] v. damage someone’s body, especially by cutting or removing part of it使残缺不全
chew: [tʃu] v. chew up  chewing gum咀嚼
fiance: [ˌfiən'seɪ] n.未婚夫
microwave: [ˈmaɪkrəˌweɪv] n.微波,微波炉
oven: [ˈʌv(ə)n] n.炉灶
safekeeping: [seɪfˈkipɪŋ] n.妥善保管
Newcastle: [ˈnjuːkɑːsl] n.
identify: [aɪˈdentɪˌfaɪ] v.鉴定,识别
spokeswoman: [ˈspoʊksˌwʊmən] n.女发言人

chewing gum: 口香糖
for safekeeping: 为了妥善保管
--------------------
deal with: 处理
go doing sth.: 去做某事
Imagine sb's dismay when + ...: 想象某人的沮丧当...
so long as + ..., sb. will do sth.: 只要...,某人就会做某事

** words
mutilate [ˈmjuːtɪleɪt] v. 使残缺不全
chew [tʃuː] v. 咀嚼
fiance [fiˈɒnseɪ; fiˈɑːnseɪ] n. 未婚夫
microwave [ˈmaɪkrəweɪv] n. 微波
oven [ˈʌv(ə)n] n. 炉灶
safekeeping [ˌseɪfˈkiːpɪŋ] n. 妥善保管
Newcastle [ˈnjuːkɑːsl] n. 纽卡斯尔
identify [aɪˈdentɪfaɪ] v. 鉴别
spokeswoman [ˈspəʊkswʊmən] n. 女发言人

** DONE 单词造句
CLOSED: [2023-10-30 Mon 21:27]
mutilate v.
- The prisoner was mutilated, for he has been tortured before.
- He ran into serious trouble and was mutilated in the accident.
- Mutilated ladies is an organization which recoginzed mutilated bank notes.
- I regreted to inform you that your left leg was mutilated in the plane crash.
- The pilot was disappointed to learn that his leg was mutilated in the place crash.
chew v. chew up  chewing gum
- Are you chewing chocolate? My wife said with a sneer.
- I haven't chew gum hald as much as you.
- From now on, I quit chewing gum.
- I promise that I will grab some chewing gum for you.
- She was reluctant to chew up the rice.
fiance n.
- His fiance was too embarrassed to say hello to her when they met at the first time.
- My fiance is going to write an article about ancient Greek rings.
- His fiance called him baby.
- At last, his fiance got impatient and left her alone at the airport.
- Not only have I had my hair cut, but my fiance as well.
microwave n.
- He has sold ten thousands of dollars worth microwaves.
- He sent his customer a fax informing that the microwaves were sold out.
- Despite the fact that he gets used to selling microwaves.
- He went to extremes to get a free microwave from the market.
- She is making a discovery of the microwave.
oven n.
- If we buy the oven, we will have delicious roast duck tonight.
- The moment the cat touched the oven, she scrambled back into her box.
- He was amazed to find that her wife had already bought an oven.
- He claimed that this oven can date back to his childhood.
- In her youth, she always recognized an oven as an microwave.
safekeeping n.  for safekeeping
- The authorities are always instructing people to do a lot of work for safekeeping.
- You should have closed the door for safekeeping yesterday.
- I'm glad that these detectives are waitting for safety at the airport.
- The archaeologist refused to explore the ancient caves for safekeeping.
- I felt obliged to give all my money to my wife for safekeeping.
identify v.
- The security wasn't able to identify his boss and made a spectacle of himself.
- The policeman is accustomed to identifing thieves.
- They competed against each other to identify the photos of someone.
- If you weren't identified, they wouldn't stand to attention.
- Don't take that tone with me. Have you ever identified me?
spokeswoman n.
- The spokeswoman claimed to have seen the soldiers.
- After entiring, the spokeswoman devoted herself to garden.
- The spokeswoman claimed that someone fired a shot through the window of embassy.
- The spokeswoman was found be the ambassador's wife.
- The ambassador is very popular with these spokeswomen.
** vocabulary
happened: occurred
remembered: recalled
fortunately: luckily
concerns: is about
dismay: sadness
the remains: what was left
department: section

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-10-31 Tue 20:05]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-30 Mon 21:27]
deal with
- If you lived in a fantasy world, you will not be able to deal with these troubles.
- How do I deal with such a mess?
- I hated to deal with the ambassador's affairs.
- The ambassador managed to deal with this.
- While the ambassador was fast asleep, I knocked at his door.
go doing
climbing dancing fishing hunting riding sailing shooting skating skiing swimming walking
- I hate to go fishing on rainy days.
- My wife often goes to extremes to go sailing.
- If Chandler hadn't been fanatical about skating, he wouldn't have been mulilated.
- Are you going shopping tonight?
- I am due to go swimming on Saturday.
imagine sb's dismay when
- Imagine my dismay when I found out that I had lost my child again.
- Imagine my dismay when I found you had failed in the test.
- Imagine your mother's dismay when she leant that you got into such a mess.
- Imagine our dismay when the busmen went on a strike again.
- Imagine her dismay when her fiance objected to her.
so long as + ...
- So long as you love me, I don't care what you did.
- We will provide you with foods so long as we reached agreement.
- The gangster has stated that so long as we gave him an helicopter, he will relieve the poor man.
- So long as they begin rescuing, everything will go smoothly.
- So long as she was mutilated, I will offer her the job.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-10-31 Tue 20:05]
** DONE Ask me if 写+读
CLOSED: [2023-10-31 Tue 20:12]
1. Clothes put in the washing machine sometimes contain bank notes. What
	 What do clothes put in the washing machine sometime contain?
2. The Mutilated Ladies department deals with claims for money. What
		What does the Mutilated Ladies department deal with?
3. John runs a furniture business. What kind
		What kind of business does John run?
4. He put a wallet containing 3000 dollars into the microwave oven. What
		What did he put into the microwave oven?
5. He had told his fiance, Jane, about this. Why hadn't
		Why hadn't he told his fiance, Jane, about this?
6. She cooked the dinner. Where
	 Where did she cook the dinner?
7. The notes turned into ash. What
	 What did the notes turn into?
8. The bank manager sent the remains to Newcastle. Where
	 Where did the bank manager send the remains to?
9. John got his money back. What
	 What did John get back?
10. They could identify the notes. How
		How could they identify the notes?

	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-10-31 Tue 20:23]
John Butlin runs a successful furniture business
	and after a very good day,
		he put his wallet containing 3000 dollars into the microwave oven for safekeeping.
Then he and his fiancee, Jane, went horse-riding,
	after which Jane cooked their dinner in the microwave oven
		only to find to their dismay that the money had been destroyed.
John went and saw his bank manager,
	who sent the remains to the Mutilated Ladies
		who identified the reamins and returned the money.

** DONE tell the story 口语复述
CLOSED: [2023-10-31 Tue 20:26]
** composition 阅读 或 写作
Jane opened the oven door and saw that her meal was ready to serve.
She took the food out of the oven and in doing so,
	noticed something strange inside the oven which she couldn't recognize.
So she went to find John and told him about it.
In dismay, John quickly explained
	that he had put his wallet containing the day's takings into the oven for safekeeping.

They both rushed to the oven and saw that the money had been destroyed.
At first they didn't know what to do.
John wanted to throw the money away, but Jane wouldn't let him.
'lt's best not to disturb the wallet,' Jane said.
'You can see all the money is there, even if it has been destroyed.'
Jane told John to go and see his bank manager for advice,
	so the next day John took the wallet and the ashes to the bank.
** Topics for discussion
