#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 10 The loss of the Titanic
#+begin_verse
What would have happened if only two of the sixteen water-tight compartments had been flooded?

The great ship, Titanic, sailed for New York from Southampton on April 10th, 1912.
She was carrying 1,316 passengers and *a crew of* 891.
Even by modern standards, the 46,000 ton Titanic was a colossal ship.
At that time, however, she was not only the largest ship that had ever been built,
		but *was regarded as* unsinkable,
	for she had sixteen watertight compartments.
Even if two of these were flooded, she would still be able to float.
The tragic sinking of this great liner will always be remembered,
	for she went down on her first voyage with heavy loss of life.

Four days after setting out,
	while the Titanic was sailing across the icy waters of the North Atlantic,
	a huge iceberg was suddenly spotted by a lookout.
After the *alarm had been given*, the great ship turned sharply to avoid a direct collision.
The Titanic turned just *in time*, narrowly missing the immense wall of ice
	which rose over 100 feet out of the water beside her.
Suddenly, there was a slight trembling sound from below,
	and the captain went down to see what had happened.
The noise had been so faint that no one thought that the ship had been damaged.
Below, the captain *realized to his horror that* the Titanic was sinking rapidly,
	for five of her sixteen watertight compartments had already been flooded!
*The order to abandon ship was given* and hundreds of people plunged into the icy water.
As there were not enough lifeboats for everybody, 1,500 lives were lost.
#+end_verse
** expression
Southampton: [saʊθ'hæmptənˌ saʊ'θæmp-]
colossal: [kəˈlɑs(ə)l] adj.庞大的
watertight: [ˈwɔtərˌtaɪt] adj.不漏水的
compartment: [kəmˈpɑrtmənt] n.(轮船的)密封舱
flood: [flʌd] v.充满水
float: [floʊt] v.漂浮,漂浮
tragic: [ˈtrædʒɪk] adj.悲惨的
liner: [ˈlaɪnər] n. a large ship for passengers班船
voyage: [ˈvɔɪɪdʒ] n.航行
iceberg: [ˈaɪsˌbɜrɡ] n.冰山
lookout: [ˈlʊkˌaʊt] n. someone whose duty is to watch carefully for something, especially for danger瞭望员
collision: [kəˈlɪʒ(ə)n] n.碰撞
narrowly: [ˈneroʊli] adv.刚刚,勉强地
miss: [mɪs] v.避开
slight: [slaɪt] adj.轻微的
tremble: [ˈtremb(ə)l] v.  to shake slightly in a way that you cannot control, especially because you are upset or frightened震颤
faint: [feɪnt] adj.微弱的
horror: [ˈhɔrər] n.  to sb's horror  horror movie恐惧
abandon: [əˈbændən] v.抛弃
plunge: [plʌndʒ] v.投入, 跳入
lifeboat: [ˈlaɪfˌboʊt] n.救生船
--------------------
a crew of: eg. ~ workers; ~ painter; ~ waiters一群...
be regarded as + adj./n.: 被认为是
give an alarm: give a warn of danger发出警报
in time: not late; punctual.及时
realized to his horror that: 惊恐的意识到...
give an order: 下命令

** words
Southampton [saʊθ'hæmptən] n. 南安普敦
colossal [kəˈlɑs(ə)l] adj. 庞大的
watertight [ˈwɔtərˌtaɪt] adj. 不漏水的
compartment [kəmˈpɑrtmənt] n. 轮船的密封舱
flood [flʌd] v. 充满水
float [floʊt] v. 漂浮
tragic [ˈtrædʒɪk] adj. 悲惨的
liner [ˈlaɪnər] n. 班船
voyage [ˈvɔɪɪdʒ] n. 航行
iceberg [ˈaɪsˌbɜrɡ] n. 冰山
lookout [ˈlʊkˌaʊt] n. 瞭望员
collision [kəˈlɪʒ(ə)n] n. 碰撞
narrowly [ˈneroʊli] adv. 刚刚,勉强地
miss [mɪs] v. 避开
slight [slaɪt] adj. 轻微的
faint [feɪnt] adj. 微弱的
horror [ˈhɔrər] n. 恐惧
abandon [əˈbændən] v. 抛弃
plunge [plʌndʒ] v. 投入,跳入
lifeboat [ˈlaɪfˌboʊt] n. 救生船

** Vocabulary
colossal: immense,huge
regarded: considered, thought to be
compartments: sections,divisions
flooded: filled with water
float: stay on the surface of the water
avoid: escape, miss
narrowly: only just

** DONE 单词造句
CLOSED: [2023-11-06 Mon 19:35]
Southampton
colossal adj.
- Instead of catching fishes, I catch nothing. This is a colossal waste of time.
- The colossal has been burnt down last night for one reason or another.
- To our surprise, there is a colossal wooden statue in his garden.
- Somehow, I have made such a colossal mistake.
- If you didn't make such a colossal mistake, you wouldn't be fired.
watertight adj.
- If I didn't wear watertight clothes, I would be in difficulty now.
- As long as the tire is watertight, we will be safe now.
- I learned to make a watertight bag in the factory.
- These clothes have one thing in common: they are watertight.
- He is making a study of the watertight compartment.
compartment n.
- The detective pointed out that the house has a compartment.
- The compartment used to be connected to the garage.
- The compartment of the house hasn't been found for hundreds of years.
- The flight attendant lost her temper, for the customer was reluctant to leave the compartment.
- No one has been allowed to live in compartents.
flood v.
- Imagine my wife's dismay when she found out that the kitchen was flooded.
- The authorities confirmed that all villages have been flooded.
- The boys went to extremes to flood the garage.
- Even if two of the compartments were flooded, the ship would still be able to float.
- Because the room was flooded, I have to deal with it for a long time.
float v.
- The lookout claimed to have spotted some leaves floating on the water.
- The captain found the body floating nearby and call out to the police.
- We couldn't swim in the river, for the simple reason that the boat is floating nearby.
- This turned out to be a boat floating on the river.
- The man love to sit in a boat floating on the river.
tragic adj.
- She decided to make a sacrifice when she heard the tragic news.
- When the tragic news arrived, all of us bursted into tears.
- This is tragic news, and I felt oblige to keep the secret.
- My cat died from a tragic accident last year.
- I was just wondering what was the tragic news.
liner n.
- She never dreamed of sailing to America in a large liner.
- I woke up with a start, realizing that I was in a large liner.
- The ocean liner was said to sail for Shanghai from New York.
- He used to be a waiter who worked on a large liner.
- Suddenly a large liner was spotted by a lookout.
voyage n.
- She must have been a passenger on our first voyage.
- You will have a happy voyage to London.
- I thought we need to rest after a long voyage.
- She loves to sail out at sea after her first voyage.
- It is well known that the colossal ship sank on her first voyage.
iceberg n.
- The lookout claimed to have seen an iceberg.
- The tragic news came to America that the liner had hit an iceberg.
- He is fanatical about iceberg.
- He caught sight of a figure which seems to be an iceberg.
- It is disturbing to think that the ship may hit an iceberg in the icy waters of Atlantic.
lookout n.
- The look out died from a tragic accident.
- This entitle the lookout to live in the compartment.
- The lookout lost his nerve when he spotted  a huge iceberg.
- It was not long before the lookout died of a rare disease.
- The lookout claimed to have seen an iceberg moving in front of the ship.
collision n.
- The busman and I turned sharply to avoid a collision.
- The actor took precaution in a colllision so that no one can recognize him.
- The detective made a study of traffic collisions in the city.
- It is fortunate that no one was injuried in the collision.
- The report came to the Zoo that five elephants were injuried in a collision.
narrowly adv.
- Alan was said to narrowly avoid an accident.
- I narrowly missed the man who stole my wallet last night.
- He has narrowly won the elections.
- She stated that she narrowly failed the exam.
- The lucky woman narrowly broke the world record.
miss v.
- He missed his exam, for he was too late.
- If you didn't miss lunch, you wouldn't be so hungry.
- If I didn't miss her, I would get married to her now.
- It is still possible to miss the train if you don't hurry to the station.
- Although we missed the chance, we should put forward our plan.
slight adj.
- He takes his job so seriously that he still went to work while getting a slight fever.
- If you get a slight fever, you should go home.
- I should warn you, there's only a slight chance it works.
- We will stick to our plan which wll make a slight change.
- These old builds have made a slight change for hundreds of years.
tremble v.
- My body is likely to tremble when I lose nerve.
- You needn't have threatened to kill him, because his whole body is trembling now.
- My body is out of control and trembling all the time.
- It is considered unlucky for somebody trembling in front of the goddess.
- I am expected to tremble and make a spectabcle of myself.
faint adj.
- The faint noise they make, the more likely we are to use them.
- She claimed to have heard a faint sound from the compartment.
- As long as there is a faint sound, the dog will recognize it.
- Seeing a faint light, the vicar went up to find out what had happened.
- My wife always detects a faint smell of perfume when I meet other women.
horror n.  to sb's horror  horror movie
- A circle of friends are watching a Japanese horror movie together.
- To my horror, I found my brother beautiful.
- To his horror, he found that his legs had been mutilated.
- To my horror, I was mutilated in the tragic accident.
- To her horror, she forgets to provide them with background music.
abandon v.
- The abandoned ship is floating on the river.
- Well, you are busy abandoning your children.
- She has written an article on abandoned dogs.
- In the end, the girl got impatient and decided to abandon her cat.
- Who entitles you to abandon your dogs?
plunge v.
- We are not allowed to plunge into water.
- Don't even try to plunge into water and get such a mess.
- If you plunge into water again, we will kick your ass.
- If you didn't plunge into water, we would be swimming now.
- People in this town who do manual work love to plunge into water after their work.
lifeboat n.
- Why don't you sacrifice some money for a lifeboat?
- I have the privilege of using the lifeboat.
- There are not enough lifeboats on the river.
- The man who owns a lifeboat often makes a sacrifice.
- The man who owns a lifeboat used to be a waiter working on a colossal ship.
** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-06 Mon 20:00]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-06 Mon 19:52]
a crew of
- He will be writting an article on a crew of workers in the theater.
- Did a crew of painter go into a high-rise building?
- He is telling a story which is based on a crew of waiters.
- A crew of waiters are watching a Japanese horror movie.
- To his horror, a crew of worker was setting his house on fire.
be regarded as + adj./n.
- The man who has red hair have been regarded as dangerous by police.
- It's disturbing to think that I am regarded as ugly by my wife.
- He has been regarded as dangerous by police for a period of time every year.
- She may have been regarded as the most beautiful woman in China.
- To his horror, he realized that he was regarded as dangerous by police.
give an alarm
- So long as you give an alarm, your children will rush out of the house.
- Now that the alarm was given, I am being considered as dangerous by people.
- So long as the alarm is given, the bus will come to stop.
- As long as the alarm was given, the workered stopped to rescue.
- If the alarm was given, there would be less people injuried.
in time
- The article has been published in time.
- My wife changed into her new dress in time.
- The girl is reluctant to finish her housework in time.
- Thanks to my classmate, I finish it in time.
- If you don't carry your identify card, you will not be here in time.
realized to his horror that
- I realized to my horror that my passwort had been stolen by that girl.
- I realized to my horror that she had fallen love in her teacher.
- I realized to my horror that he was equiped with a gun.
- I realized to my horror that I still didn't get enough money to study abroad.
- I realized to my horror that I had made a colossal mistake.
give an order
- Mr. Leo gave an order to read aloud.
- I gave an order to charge at the ball.
- The order to hit the balloon was given.
- The order to set the museum on fire was gaven.
- Why did you give such a stupid order?
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-06 Mon 20:00]
** DONE Ask me if 写+读
CLOSED: [2023-11-06 Mon 20:12]
1. The Titanic sailed from Southampton. Where
	 Where did the Titanic sail from?
2. She was carrying 1,316 passengers. How many passengers
		How many passengers was she carrying?
3. She was regarded as unsinkable. Why
		Why was she regarded as unsinkable?
4. She had sixteen watertight compartments. How many
		How many watertight compartments did she have?
5. An iceberg was spotted. How many days after setting out
		How many days after setting out was an iceberg spotted?
6. The ship turned sharply. Why
	 Why did the ship turn sharply?
7. The wall of ice rose over 100 feet out of the water. How high
	 How high did the wall of ice rise?
8. The captain realized the ship was sinking. What
	 What did the captain realize?
9. Five of her compartments had been flooded. How many
	 How may of her compartments had been flooded?
10. 1,500 lives were lost. How many
		How many lives were lost?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-06 Mon 20:21]
The Titanic was sailing across the icy waters of the North Atlantic
	when an iceberg was seen by a lookout.
After the alarm was given, the ship turned sharply and sail alongside it.
Suddenly, a faint noise was heard from below,
	so the captain went down to investigate,
	only to found that five of the sixteen compartments had been flooded.
On hearing the order to abandon ship, people jumped overboard,
	but 1,500 peole were drowned because there are not enough lifeboats for everyone.
	
** DONE tell the story 口语复述
CLOSED: [2023-11-06 Mon 20:26]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-06 Mon 20:34]
The Titanic began to sink, slowly at first.
The order to abandon ship was unexpected, so passengers and crew were completely unprepared.
It was the middle of the night.
Some people were asleep in their cabins.
Others were on deck admiring the brilliant night sky and the giant icebergs rising above them.
Others were eating and dancing in the wonderful ballrooms on the ship.
The immediate effect was panic and confusion.
People began rushing in all directions, wondering what to do next.
The cold was indescribable and many passengers were still in their night clothes.

Members of the crew came up from below and began to lower the lifeboats.
It was a case of women and children first,
	but it soon became obvious that there weren't enough lifeboats for everyone,
	so people jumped overboard into the freezing water in order to save their lives.
Some of those swimming in the water struggled to get into the lifeboats,
	but most of them were already full.
The Titanic sank rapidly, carrying many people down with it.
There were cries of despair from people in the water
	as they watched the lifeboats moving away and were left to drown in the icy ocean.
** Topics for discussion
