#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 12 Life on a desert island
#+begin_verse
What was exceptional about the men's stay on the desert island?

Most of us have *formed an unrealistic picture of* life on a desert island.
We sometimes *imagine a desert island to be a sort of* paradise where the sun always shines.
Life there is simple and good.
Ripe fruit falls from the trees and you never have to work.
The other side of the picture is quite the opposite.
Life on a desert island is wrectched.
You either *starve to death* or live like Robinson Crusoe,
	waiting for a boat which never comes.
Perhaps there is *an element of truth* in both these pictures,
	but few of us have *had the opportunity to* find out.

Two men who recently spent five days on a coral island *wished they had stayed* there longer.
They were taking a badly damaged boat from the Virgin Islands to Miami to have it repaired.
During the journey, their boat began to sink.
They quickly *loaded a small rubber dinghy with* food, matches, and cans of beer
		and rowed for a few miles across the Caribbean
	until they arrived at a tiny coral island.
There were hardly any trees on the island and there was no water,
	but this did not prove to be a problem.
The men collected rainwater in the rubber dinghy.
As they had brought a spear gun with them, they had plenty to eat.
They caught lobster and fish every day, and, *as one of them put it* 'ate like kings'.
When a passing tanker rescued them five days later,
	both men *were genuinely sorry that* they had to leave.
#+end_verse
** expression
desert: [ˈdezərt] island 荒岛
unrealistic: [ˌʌnriəˈlɪstɪk] adj.不真实的
paradise: [ˈperəˌdaɪs] n.天堂,乐土
wretched: [ˈretʃəd] adj. someone who is wretched is very unhappy or ill, and you feel sorry for them可怜的,艰苦的
starve: [stɑrv] v.挨饿
element: [ˈelɪmənt] n.成分
opportunity: [ˌɑpərˈtunəti] n.机会
coral: [ˈkɔrəl] n.珊瑚
Virgin: [ˈvɜrdʒɪn] Islands
Miami: [maɪ'æmi] n.
dinghy: [ˈdɪŋi] n.皮艇
Caribbean: [ˌkerɪˈbiən] n.加勒比海
spear: [spɪr] gun: 鱼叉枪
lobster: [ˈlɑbstər] n.龙虾
tanker: [ˈtæŋkər] n.油轮
genuinely: [ˈdʒenjuɪnli] adv.由衷地

have an opportunity to do sth.: have the privilege of doing sth.有机会做某事
an element of truth/danger: 有点..
starve to death: 饿死
sb. be genuinely sorry that + ...某人真的很抱歉+...
--------------------
wish that sb. did: 现在虚拟
wish that sb. had done: 过去虚拟
--------------------
formed an unrealistic picture of sth.:对某事有不切实际的想象
imagine sth./sb. to be n./adj.: 把某事想象成
a sort of: 某种程度上/一种
wish that + ...: 希望+...
load a. with b.: 用B装载A
As sb. put it: 如某人所说

** words
desert island ['dezət-aɪlənd] 荒岛
unrealistic [ˌʌnriːəˈlɪstɪk] adj.不真实的
paradise [ˈpærədaɪs] n.天堂,乐土
wretched [ˈretʃɪd] adj.可怜的,艰苦的
starve [stɑːrv] v.挨饿
element [ˈelɪmənt] n.成分
opportunity [ˌɑːpərˈtuːnəti] n.机会
coral [ˈkɔːrəl] n.珊瑚
Virgin islands ['və:dʒin] [ˈaɪləndz] 维尔京群岛
Miami [maɪˈæmi] n.迈阿密(美国最南的城市)
dinghy [ˈdɪŋi; ˈdɪŋɡi] n.救生筏,小船
Caribbean [ˌkærɪˈbiːən; kəˈrɪbiən] n.加勒比海
spear gun [spɪr ɡʌn] 捕鱼枪
tanker [ˈtæŋkər] n.油轮
genuinely [ˈdʒenjuɪnli] adv.由衷地
Robinson Crusoe [ˈrɑbɪnsən] [ˈkruːsoʊ] 鲁滨逊丶克鲁索

** vocabulary
picture: image
wretched: miserable
starve to death: die of hunger
opportunity: chance
repaired: fixed, mended
loaded: filled, stacked
dinghy: small boat

** DONE 单词造句
CLOSED: [2023-11-10 Fri 19:59]
desert island
- If you were on a desert island, what would you like to carry most?
- There is a strange mixture on the desert island.
- Image his dismay when he found that he was on a desert island alone.
- I was always being greeted by an unpleasant smell on the desert island.
- I was made to cook by myself on the desert island.
unrealistic adj.
- On the other hand, this idea proved to be unrealistic.
- The order given by the captain proved to be unrealistic.
- I found it unrealistic that a puma was still at large.
- This proved to be unrealistic, for there was no puma on a desert island.
- It is unrealistic that perfume will be exempted from import duty.
paradise n.
- They was disappointed to find that the countryside is not a paradise.
- So long as humen don't come here anymore, it will soon be a paradise of fishing.
- The village used to be regarded as a paradise.
- If you provided us with some background music, this bar would be a paradise.
- The journalist is instructed to write an article about this paradise.
wretched adj.
- They lived in a wretched conditions, for most of them had cancers.
- He found out that the wretched animal had been killed last night.
- She was so kind that she often provided these wretched animal with some foods.
- She went to extremes to get away from wretched place.
- This village turned out to be a wretched place, instead of a paradise.
starve v.  starve to death
- As the authorities didn't provide enough food with them, many of them have starved in floods.
- If there were only one man like you in the world, I'd starve to death.
- If I didn't have the privilege of going to the desert island, I'd starve to death.
- She may be starving, for she is extremely weak.
- This convinced me that the wretched animal was starving.
element n.  an element of truth/danger
- I was relieved to hear that there was still an element of truth in this pirate story.
- The zoo has stated that there is an element of danger in climbing this mountain.
- My wife proved that rise in status was a key element in our decision.
- There is an element  of danger in knocking the security to the ground.
- There must be an element of truth in this statistics.
opportunity n.  have an opportunity to do sth.
- I'm glad I have an opportunity to go to disneyland.
- I'm sure that I have an opportunity to go to university.
- It was not long before that she had an opportunity to break the wrold record.
- The detective had an opportunity to catch the thieves.
- We have only an opportunity to send a signal to have us rescued.
coral n.
- It was not long before we found out that she was expert at coral.
- She carried a basket of fruits to the coral island.
- It is you who should be responsible for the coral island, not me.
- I have been living on a coral island for ten years, I am tired of world outside.
- The scientist named the coral island the Swag.
Virgin Islands
Miami n.
dinghy n.
- We couldn't sail to the other bank of the river. Despite the fact that we get a dinghy.
- I didn't have enough money to have my dinghy repaired.
- It's hard to imagine that this wonderful dinghy belongs to me.
- The dinghy is now holding up the traffic on the river.
- This dinghy is going to set out to Miami this night.
Caribbean n.
spear gun
- The spear gun is regarded as precious, for he double checks it every day.
- I must have lost my spear gun on the way home.
- All sorts of spear gun will be on show on this exhibition.
- A large circle of my friends are expert at spear gun.
- Euiped with a spear gun, I sat in the boat on the river.
lobster n.
- The moment I see the lobster, you should fire a shot.
- I have a habit of eating lobster on weekends.
- You should have removed dirty soil from the lobster.
- Lobsters are a source of income in this village.
- Somehow lobsters had a bad reputation for spreading diseases in this country.
tanker n.
- If we missed the tanker, we would never be rescued.
- It is a blessing that a passing tanker rescued us.
- The order to abandon the tanker was given by the captain.
- The tanker broke down last night out at sea.
- On the other hand, this businessman is eager to have a tanker.
genuinely adv.  sb. be geuninely sorry that + ...
- I'm geuninely sorry that I kicked your ass last night.
- I'm geuninely sorry that we have sold it out.
- She's geuninely sorry that she has made a colossal mistake at the meeting.
- I'm genuinely sorry that the games will be cancelled.
- I'm genuinely sorry that I didn't preventing you from hurt.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-10 Fri 20:19]
** 复习二册语法(笔记或视频) & 红皮书
wish that sb. did: 现在虚拟
wish that sb. had done: 过去虚拟

** DONE 习惯用法造句
CLOSED: [2023-11-09 Thu 22:19]
formed an unrealistic picture of a.
- Why do most people form an unrealistic picture of life abroad?
- No one could account for the fact
		that people who do manual work often
			formed an unrealistic picture of people's life who work in offices.
- She used to form an unrealistic picture of the man she will marry to.
- My wife used to form an unrealistic picture of cat's nature.
- She formed an unrealistic picture of life at the famous monostery.
imagine sth./sb. to be n./adj.
- I used to imagine myself to be a hero who saves the world.
- My wife has imagined me to be a millionaire for ten years.
- It was obvious that the cat imagined this to be a can of foods.
- When I was going on a diet, I always imagined the chair to be a bread.
- I prefered to imagine my father to be a hero.
a sort of
- He is a sort of people who believe in ancient philosophy.
- He is following her around some like a kind of dog.
- He ran straight at her like a kind of angry bull.
- She is a sort of cat who behaves like dogs.
- She is a sort of cat who has a habit of catching mouse.
quite the opposite
- Quite the opposite, she ran into serous trouble.
- Quite the opposite, she was able to settle down in New York.
- Quiet the opposite, we couldn't afford a new car.
- Quiet the opposite, I never dreamed of marrying you.
- Quiet the opposite, she is always complaining about you.
wish that + ...
- I wished that I had a good reputation for taking job seriously.
- I wished that you had washed my clothes.
- I wished that this tanker had belonged to me.
- I wished that I worked hard in high school.
- I wished that I hadn't argued with my wife last night.
load a. with b.
- You needn't have loaded your car with fruits .
- The boat loaded with goods received a warm welcome.
- The truck loaded with diamond needn't cleaning now.
- It seems that the truck was loaded with too much goods.
- The truck was said to be loaded with 100,000 dollars worth of diamonds.
As sb. put it
- As my father put it "reading, reading and reading".
- As my wife put it "If you didn't finish it, you might run into serious trouble".
- As Aristole put it "I prefer truth to my teacher".
- As the headmaster used to put it "It is never too old to learn".
- As Leo put it "I counldn't tell the difference from Britsh and American English".

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-10 Fri 20:19]
** DONE Ask me if 写+读
CLOSED: [2023-11-10 Fri 20:26]
1. We imagine a desert island to be a sort of paradise. How
	 How do we imagine a desert island to be?
2. Ripe fruit falls from the trees. What
		What falls from the trees?
		Where does ripe fruit fall from?
3. You never have to work. Why
		Why do you never have to work?
4. Two men spent five days on a coral island. How many days
		How many days did two men spend on a coral island?
5. They wished they had stayed there longer. Why
		Why did they wish they had stayed there longer?
6. They were taking their badly damaged boat to Miami. Where
	 Where were they taking their badly damaged boat to?
7. The boat began to sink. When
	 When did the boat begin to sink?
8. They loaded it with food. What
	 What did they load it with?
	 What did they load with food?
9. They rowed a few miles across the Caribbean. Where
	 Where did they row a few miles?
10. They collected rainwater in the rubber dinghy. Where
		Where did they collect rainwater?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-10 Fri 20:37]
As the men's boat was damaged,
	they were taking it from Virgin Islands to Miami 
	when on the way it boat began to sink on the way.
After having loaded food, matches, and cans of beer on to their rubber dinghy,
	the two men rowed a few miles across the Caribbean util they arrived at a tiny coral island.
There they collected water in the rubber dinghy
	and catching fish and lobster with a spear gun.
For five days, they ate 'like kings' until they were rescued by a passing tanker.
	

** DONE tell the story 口语复述
CLOSED: [2023-11-10 Fri 20:40]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-10 Fri 20:45]
The ship went down and everyone was drowned.
I was the only one who managed to jump into the sea.
I clung to a plank in the water for several hours till I was washed up on a desert island.
I slept on the beach for a very long time -- I can't remember how long.
When I woke up, I was hungry and thirsty, so I decided to explore the island.
It was uninhabited, but I found plenty of fruit which had fallen from the trees.
I lived on coconuts and pineapples and there was plenty of fresh spring water.

I tried to hunt wild animals with my bare hands(small pigs and other creatures),
	but I failed to catch anything.
So I spent my days swimming in the warm clear water and lying in the sun.
One afternoon while I was lying on the beach as usual, I saw a boat on the horizon.
I signalled with my white shirt and shouted as loudly as I could.
Fortunately, someone on the boat saw me and I was rescued.
Of course, I was pleased to get back to civilization,
	but I was very sorry to leave this island paradise.

** Topics for discussion
