#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 13 It's only me
#+begin_verse
What did the man expect to find under the stairs?

After her husband had gone to work,
	Mrs. Richards sent her children to school and went upstairs to her bedroom.
She was too excited to do any housework that morning,
	for in the evening she would be going to a *fancy-dress party* with her husband.
She intended to dress up as a ghost
	and as she had made her costume the night before, she *was impatient to* try it on.
Though the costume *consisted only of* a sheet, it was very effective.
After putting it on, Mrs Richards went downstairs.
She wanted to find out whether it would be comfortable to wear.

Just as Mrs. Richards was entering the dining room, there was a knock on the front door.
She knew that it must be the baker.
She had told him to come straight in
	if ever she failed to open the door and to leave the bread on the kitchen table.
Not wanting to frighten the poor man,
	Mrs Richards quickly hid in the small storeroom under the stairs.
She heard the front door open and heavy footsteps in the hall.
Suddenly the door of the storeroom was opened and a man entered,
	Mrs Richards realized that it must be the man from the Electricity Board
		who had come to read the metre.
She tried to explain the situation, saying 'It's only me', but it was too late.
The man *let out a cry* and jumped back several paces.
When Mrs. Richards walked towards him, he fled, slamming the door behind him.
#+end_verse
** expression
costume: [ˈkɑstum] n.化装服
consist: [kənˈsɪst] v.由...组成
sheet: [ʃit] n.a large piece of thin cloth that you put on a bed to lie on or lie under被单
effective: [ɪˈfektɪv] adj.有明显效果的,有作用的
comfortable: [ˈkʌmfərtəb(ə)l] adj.舒适的
storeroom: [ˈstɔrˌrum] n.储藏室
electricity: [ˌilekˈtrɪsəti] n. meter=metre n. 电表
pace: [peɪs] n.一步
flee: [fli] fled v. to leave somewhere very quickly, in order to escape from danger逃走
slam: [slæm] v. close砰地关上

consist of ...: be made up of; be composed of; comprise 由...组成
make yourself comfortable: to sit, lie, move, or behave in a such a way that you are relaxed and free from pain
at your own pace: you do it at a speed that is comfortable for yo
The pace of life:
--------------------
fancy dress party: 化妆舞会
be impatient to do sth.: 急于做某事
let out a cry: 大叫一声

** words
costume [ˈkɑstum] n. 化装服
consist [kənˈsɪst] v. 由……组成
sheet [ʃit] n. 被单
effective [ɪˈfektɪv] adj. 有明显效果的，有作用的
comfortable [ˈkʌmfərtəb(ə)l] adj. 舒适的
storeroom [ˈstɔrˌrum] n. 储藏室
electricity [ˌilekˈtrɪsəti] n. 电
metre [ˈmitər] n. 电表
pace [peɪs] n. 一步
flee [fli] (fled [fled], fled) v. 逃走
slam [slæm] v. 砰地关上

** DONE 单词造句
CLOSED: [2023-11-11 Sat 20:24]
costume n.
- I found you very beautiful in the costume party.
- I saw you go to the costume party.
- Leo stated that he had returned the costume to you last night.
- It is said that we will be going to the costume party tonight.
- I am going to dress up as a ghost in the costume party.
consist v.  consist of ...
- You needn't have eaten the foods that consist only of sugar.
- He was genuinely sorry that his paper consists only of two chapters.
- The crowd which was waiting in line consisted of busmen and college students.
- On the other hand it consists mostly of sugar and water.
- I was made to eat foods which consists mostly of salt and sugar.
sheet n.
- I wished that you had washed our sheet.
- The sheet was so expensive that we couldn't afford to it.
- I was greeted by an unpleasant smell which comes from the sheet.
- You should have washed your sheet.
- The sheet clinged to a mixture of hair gel and toothpaste.
effective adj.
- Leo's English course turns out to be very effective.
- Imagine my dismay when I found out that my child's study plan was not effective.
- I always feel obliged to find more effective method.
- I usually work very effectively, for I take my job seriously.
- In the end Leo's English course proved effective.
comfortable adj.  make yourself comfortable
- If you are so hard on us, how could we make ourselves comfortables?
- I tried to make myself comfortabel in the chair.
- Make yourself comfortable, help yourself to these fruits.
- Why don't you grab a beer and make yourself comfortabel?
- I usually take a long time to make myself comfortable on the bed.
storeroom n.
- The boy claimed to have seen a puma in the storeroom.
- There was some puma fur clinging to the knife in the storeroom.
- The worker is going to read the electricity meter in the storeroom.
- This is the storeroom which Harry Potter used to live in.
- The gangsters stated that the diamonds were hidden in a storeroom.
electricity n. meter=metre n.
- Turn off your computer, it's a waste of electricity.
- When I was very young, my parents always ordered to turn off lights to save electricity.
- The editor decided to publish an article on electricity meters.
- Only workers for the Electricity Board have the privilege of reading the electricity meter.
- You must have had your electricity meter repaired.
pace n.  at your own pace  The pace of life
- Let me study at my own pace.
- These days, people who do manual work are often used to the slow pace of life.
- I am willing to sacrifice higher pay for the slow pace of life.
- I'm used to the fast pace of life in the uptown.
- The fast pace of life is his secret of success.
flee fled v.
- She complained that if the police had arrived on the scene, the thief wouldn't have fled.
- After she had saw her father get angry, she fled and went to the school.
- He fled for the simple reason that he realized that he hadn't finished his task.
- Despite the fact that you feld in our wedding.
- I happened to see a thief fleeing at the edge of the forest.
slam v. close
- Equipped with a torchlight, the vicar slammed the door and went up to see what had happened.
- The men is so rude that he is always slamming the door.
- It is disturbing to think that your roomate is always slamming the door at midnight.
- It is consider unlucky for people in China slamming the door in January.
- The man set the house on fire, slamming the door.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-12 Sun 11:28]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-11 Sat 20:24]
fancy dress party
- Fancy dress parties are popular with young men and women.
- She is reluctant to go to the fancy dress party because of her ex-boyfriend.
- His father went to extremes to prevent him from going to the fancy dress party.
- The fancy dress party will be held in Disney land tonight.
- It comes as a surprise to learn that a fancy dress party will be held tonight.
be impatient to do sth.
- It comes as a surprise to learn that she was impatient to do housework.
- It comes as a surprise to learn that the clerk was impatient to send me a book.
- The cat was impatient to drink milk in the morning.
- I was impatient to take a bath.
- She was impatient to wrap the clothes up.
let out a cry
- You needn't have let out a cry. It's only me.
- I wish that she hadn't let out a cry.
- Letting out a cry, she lost his patience.
- Letting out a cry, she knocked him to the ground.
- Letting out a cry, she stoond to attention.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-12 Sun 11:28]
** DONE Ask me if 写+读
CLOSED: [2023-11-12 Sun 11:33]
1. Mrs. Richards went upstairs to her bedroom. Where
	 Where did Mr. Richards go?
2. She would be going to a fancy-dress party that evening. Where
		Where would she be going to that evening?
3. She had made her costume the night before. When
		When had she made her costume?
4. She was impatient to try it on. Why
		Why was she impatient to try it on?
5. The costume consisted of a sheet. What
		What did the costume consist of?
6. There was a knock at the door. When
	 When was there a knock at the door?
7. She hid in the storeroom under the stairs. Where
	 Where did she hide?
8. She heard the front door open. Who
	 Who heard the front door open?
9. It was the man from the Electricity Board. Who
	 Who was it?
10. The man fled. When
		When did the man flee?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-12 Sun 11:44]
Mrs. Richards had dressed up as a ghost
	and was going into the dining room when there was a knock on the door.
Thinking it was the baker,
	she hid in the storeroom under the stairs.
She heard footsteps in the hall
	and then the man from Electricity Board opened the storeroom door.
Though Mrs. Richards said 'It's only me',
	he got a bad fright.
When she walked towards him,
	he fled, slaming the front door behind him.

** DONE tell the story 口语复述
CLOSED: [2023-11-12 Sun 11:47]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-12 Sun 11:50]
Mrs. Richards immediately went upstairs and took off her costume.
She felt sorry for the poor man from the Electricity Board,
	but at the same time she was rather amused.
Suddenly, there was a knock at the front door and Mrs. Richards opened it at once.
The electricity man had returned accompanied by a policeman,
	so she invited both in.
The man told Mrs.Richards that he had tried to read her metre
	and that there was a ghost in the storeroom.
Though Mrs. Richards explained that she had dressed up as a ghost,
	he refused to believe her.
She told him to open the storeroom door, but he was too frightened,
	so she opened it herself.
While the electricity man and the policeman were looking for the ghost in the storeroom,
	Mrs. Richards fetched her costume.
She showed it to both men and only then did they believe her.

** Topics for discussion
