#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 18 Electric currents in modern art
#+begin_verse
How might some of the exhibits have been dangerous?

Modern sculpture *rarely* surprises us *any more*.
*The idea that* modern art can only be seen in museums *is mistaken*.
Even people who *take no interest in* art 
  cannot have failed to notice examples of modern sculpture on display in public places.
Strange forms stand in gardens, outside buildings and shops.
We have got quite used to them.
Some so called 'modern' pieces have been on display for nearly eighty years.

In spite of this,
	some people -including myself- were surprised by a recent exhibition of modern sculpture.
The first thing I saw when I entered the art gallery was a notice which said:
  'Do not touch the exhibits. Some of them are dangerous!'
The objects on display were pieces of moving sculpture.
Oddly shaped forms that are suspended from the ceiling and move *in response to* a gust of wind 
	*are quite familiar to* everybody.
These objects, however, were different.
Lined up against the wall, there were long thin wires *attached to* metal spheres.
The spheres had been magnetized and attracted or repelled each other all the time.
In the centre of the hall, there were a number of tall structures which contained coloured lights.
These lights flicker continuously like traffic lights which have *gone mad*.
Sparks were emitted from small black boxes and red lamps flashed *on and off* angrily.
*It was rather like* an exhibition of prehistoric electronic equipment.
These peculiar forms not only *seemed designed to shock* people emotionally, 
	but to give them electric shocks as well.
#+end_verse
** expression
current: [ˈkʌrənt] n.  electric current 电流
sculpture: [ˈskʌlptʃə] n. an object made out of stone, wood, clay etc by an artist雕塑
mistaken: [miˈsteɪk] adj.错误的
gallery: [ˈɡæləri] n. a large building where people can see famous pieces of art美术馆
exhibit: [ɪɡˈzɪbɪt] n.v. exhibition n. to show something in a public place so that people can go to see it展品,陈列品
oddly: [ˈɑdli] adv. in a strange or unusual way古怪的
attach: [əˈtætʃ] v. to fasten or connect one object to another连,系
sphere: [sfɪr] n. a ball shape球体hemisphere
magnetize: [ˈmæɡnəˌtaɪz] v.使磁化
repel: [rɪˈpel] v.排斥
flicker: [ˈflɪkər] v. to burn or shine with an unsteady light that goes on and off quickly闪烁
emit: [ɪˈmɪt] v. to send out gas, heat, light, sound etc放射
flash: [flæʃ] v.闪光
prehistoric: [ˌpriˈhɪstɔrɪk] adj.史前的,老掉牙的
electronic: [ˌilekˈtrɑnɪk] adj.电子的
peculiar: [pɪˈkjuljər] adj. strange, unfamiliar, or a little surprising奇异的
shock: [ʃɑk] v.n.震惊
emotionally: [ɪˈmoʃənlɪ] adv. relating to your feelings or how you control them感情上

make a sculpture / create a sculpture: 制作雕塑
be mistaken about sth./sb.: confused or wrong about对某人/事物有误解
Oddly enough, + ...: Strangely, unexpectedly奇怪地, ...
be attached to sb./sth. = attach a. to b.: 把A绑到B上
get an electric shock: 被电击
receive an electric shock: 被电击
give you electric shocks: 给你电击
--------------------
not any more = not any longer = no longer: 不再
The idea that + ... is mistaken: 想法xx是错的
take no/ a great/an interest in: 对...不感兴趣
in response to sth.: 回应某事
be/sound/look/seem familiar to sb.: 对某人看起来很熟悉
go mad: 发疯
on and off: 断断续续
It was rather like ...: 这很像...
seem adj.(designed) to do sth.: be designed to do sth.似乎被设计去做某事
be designed to do sth.: seem designed to do sth.被设计成做某事

** vocabulary
on display: exhibited
oddly: peculiarly strangely
suspended: hung
response: answer
familiar: well-known
attached: connected
flickered continuously: shone unsteadily all the time

** words
current [ˈkʌrənt] n. 电流
sculpture [ˈskʌlptʃə] n. 雕塑
mistaken [miˈsteɪk] adj. 错误的
gallery [ˈɡæləri] n. 美术馆
exhibit [ɪɡˈzɪbɪt] n. 展品，陈列品
oddly [ˈɑdli] adv. 古怪的
attach [əˈtætʃ] v. 连，系
sphere [sfɪr] n. 球体
magnetize [ˈmæɡnəˌtaɪz] v. 使磁化
repel [rɪˈpel] v. 排斥
flicker [ˈflɪkər] v. 闪烁
emit [ɪˈmɪt] v. 放射
flash [flæʃ]/ v. 闪光
prehistoric [ˌpriˈhɪstɔrɪk] adj. 史前的，老掉牙的
electronic [ˌilekˈtrɑnɪk] adj. 电子的
peculiar [pɪˈkjuljər] adj. 奇异的
shock [ʃɑk] v. 令人震惊，刺激人
emotionally [ɪˈmoʃənlɪ] adv. 感情上

** DONE 单词造句
CLOSED: [2023-11-20 Mon 22:56]
current n.  electric currents
sculpture n.  make/create a sculpture
- It was not long before, she took an interest in the sculpture.
- The worker soon gets used to making a sculpture.
- It was my job to create a sculpture.
- She pretended that she could make a sculpture.
- I really appreciate that you made a sculpture for me.
mistaken adj.  be mistaken about sth./sb.
- Fearing he must be mistaken, he soon put out the fire.
- He woke up with a start, and found that he was mistaken about his children.
- I used to have a mistaken idea that cats have nine lives.
- As long as I put up the tent, I realized that I was mistaken about the order.
- He was mistaken about these cars' owners, for they still parked in front of his gate.
gallery n.
- She always has trouble with visiting the gallery for one reason or another.
- If you hadn't gone to the gallery, I would have kicked your ass.
- Once upon a time, there was a gallery.
- It is easy for you to hitchhike to the gallery.
- The gallery was said to be named after the president.
exhibit n.v. exhibition n.
- He couldn't resist the temptation of stealing these exhibits.
- He denied taking all these exhibits.
- If you token the exhibit, we would give you a electric shock.
- The exhibit was wrapped up and handed to the detective.
- These painting will be exhibited in the gallery.
oddly adv.  Oddly enough, + ...
- Oddly enough, I didn't hand my key to my wife.
- Oddly enough, it is easy for my cat to swim.
- She explain this oddly to her husband.
- The girl who is swimming is struggling up oddly.
- We never except our bikes to be found oddly.
attach v.  be attached to sb./sth. = attach a. to b.
- The ticket which police gave me was attached to my car headlight.
- She managed to attach the lamp to the wall.
- A short while ago, your father attached your ball to the gate.
- Don't attach it to the door, you did get me a fright.
- Shortly afterwards, she attached the anchor to the huge cable.
sphere n.
- The customer has sent a request for a large number of metal spheres.
- Up to now, we have made two special types of metal spheres.
- In return for my sister's sphere, I sent her a postcard.
- My child is always asking me for mental spheres.
- She won a prize which was exchanged for a mental sphere.
magnetize v.
- The spheres can't have been magnetized.
- The spheres must have been magnetized.
- The spheres may be magnetized.
- The spheres must be magnetized.
- The spheres needn't have been magnetized.
repel v.
- I refused to pay the bill, for the woman really repelled me.
- At that moment, both spheres which had been magnetized repelled each other.
- My classmate repelled me and I was not allowed to touch him.
- Don't make such stupid remark anymore, for you will probably repel everyone.
- The man who laughed at me in the meeting repelled me a great deal.
flicker v.
- These candles flicker once a minutes.
- I realized to my horror that the light was still flickering.
- My wife asked me to recover the light which was flickering.
- I am likely to give her a surprise when she saw these candles flickering in the room.
- The cigarette is flickering at the edge of forest.
emit v.
- She was greeted by a peculiar smell which was emited from the special type of fruit.
- After sparks were emited from these boxes, all returned to normal again.
- She made no effort to emit a cry.
- The factory has been emitting smelly smokes for over ten years.
- These sphere kept on emitting sparks for a long time.
flash v.
- I have already flashed my headlights towards you.
- Don't flash your headlights at me anymore.
- She made every effort to flash her headlights at the boat.
- For your own protection, the red warning is flashing on and off.
- It is obvious that there is a light flashing on and off.
prehistoric adj.
- I found my dress prehistoric.
- My wife is sure that my coloured hair is prehistoric.
- When she was used to playing the game, it was prehistoric.
- All these clothes on show is prehistoric.
- It is well known that New Concept English is prehistoric.
electronic adj.
- You got into such a mess. Your bed is covered with electronic equipments.
- The summlgers never feel guilty even if they hide 10 electronic equipment in their suitcase.
- The order to turn off all electronic equipments was give.
- The alarm was given that these electronic equipments were set on fire.
- These electronic equipments are regarded as prehistoric.
peculiar adj.
- He was greeted by a peculiar smell from the kitchen when his wife was cooking.
- There is no shortage of peculiar corals.
- Everyone was astonihsed to find that there were so many peculiar sculptures on display.
- This bag is full of peculiar diamonds.
- Fulfilling his dream, he saw so many peculiar sculptures in the gallery.
shock v.n.  get/receive an electric shock  give you electric shocks
- My father has received an electric shock.
- If you made such stupid remarks any more, we would give you electric shocks.
- My father was shocked emotionally, so we wasn't allowed to touch his toys.
- The boy has received an electric shock and has suffered from it.
- Many people got an electric shock in the floods.
emotionally adv.
- How was it designed to shock people emotionally?
- She explained her experience emotionally to us.
- She is telling us a pirate story emotionally.
- She emotionally advised me to give her a lift.
- He emotionally formed an unrealistic picture of the life in US.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-21 Tue 20:52]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-20 Mon 22:55]
not any more = not any longer = no longer
- You don't have an opportunity to meet the actress any more.
- On the other hand, I won't be greeted by the peculiar smell any more.
- Perfume is no longer exempted from import duty.
- I don't feel guilty for that any longer.
- I don't smoke any more.
The idea that + ... is mistaken
- The idea that there is no shortage of foods and water is mistaken.
- The idea that the statue is a goddess is mistaken.
- The idea that cats have nine lives is mistaken.
- The idea that she died from a plane crash is mistaken.
- The idea that she has a perfert alibi is mistaken.
take no/ a great/an interest in
- It was not long before, my cat takes a great interest in the ball.
- My cat takes an interest in a toy which I have just bought.
- My wife takes a great interest in taking photographs.
- Imagine my wife's dismay when she found I take no interest in this suit.
- I take no interest in scrambled eggs.
in response to
- She cooked a lobster in response to my scrambled eggs.
- The book goes to press in response to her hard work.
- She refused to publish the article in response to our demand.
- The website will write an article in response to our demand.
- The leader keeps the status quo in response to other's demand.
be/sound/look/seem familiar to sb.
- Somehow the cat seems familiar to me.
- The woman who does manual work sounds familiar to me.
- The rhythm of the music sounds familiar to me.
- The ticket she gave me seems familiar to me.
- Somehow the wallet seems familiar to me.
go mad
- If we still keep the status quo, she will go mad.
- Don't ask me to make a sacrifice, I will go mad.
- Don't make such noises any more, I will go mad.
- Don't call me Mr. Big, I will go mad.
- You'd better return it to me or I will go mad.
on and off
- I has made sacrifices on and off for ten years.
- I volunteer to drive bus on and off.
- The perfume is exempted from import duty on and off.
- She told me about her experience on and off.
- This company made a profit on and off.
It was rather like ...
- It was rather like being pregant.
- It was rather like dying from cancer.
- It was rather like having a perfer alibi.
- It was rather like a gentle man.
- It was rather like a puma at large.
seemed adj.(designed)  ...
- Our father seemed angry about our behaviours.
- She seemed angry about the noise from outside.
- She seemed angry about the remarks he made.
- She seemed angry about being put out of her business.
- She seemed angry about the boys who played truent from school.
be designed to do sth.
- It is designed to provide protection.
- It is designed to play background music.
- It is designed to be loaded with diamonds.
- It is designed to take a rest.
- It is designed to give an alarm.
** 跟读 50遍
** Comprehension 反复练习
** DONE Ask me if 写+读
CLOSED: [2023-11-21 Tue 21:01]
1. Modern sculpture rarely surprises us any more. Why
	 Why does modern sculpture rarely surprise us any more?
2. Examples of modern sculpture are on display in public places. Where
		Where are examples of modern sculpture on display?
3. Some pieces have been on display for nearly eighty years. How long
		How long have some pieces been on display?
4. The notice said 'Do not touch'. What
		What did the notice say?
5. The objects on display were pieces of moving sculpture. What
		What were the objects on display?
6. The spheres had been magnetized. How
	 How had the spheres been magnetized?
7. They attracted and repelled each other. Why
	 Why did they attract and repell each other?
8. The tall structures contained coloured lights. What
	 What contained coloured lights?
	 What did the tall structures contain?
9. They were like traffic lights which have gone mad. What... like
	 What were they like?
10. Sparks were emitted from small black boxes. How
		How were sparks emitted from small black boxes?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-21 Tue 21:11]
On entering the art gallery, the writer saw a notice
	which forbade people to touch the exhibits because they were dangerous.
The exhibition consisted of pieces of moving scuplture.
Against a wall, the writer saw long thin wires attached to metal spheres,
	which had been magnetized and attracted or repelled each other.
In the centre of the hall tall were structures containing coloured lights
	which went on and off.
Sparks were emitted from black boxes and red lamps flashed on and off angrily.

** DONE tell the story 口语复述
CLOSED: [2023-11-21 Tue 21:19]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-21 Tue 21:23]
Recently I went to the Royal Academy in London to see the summer exhibition.
The work of many artists was on display and the exhibition aroused a lot of public interest.
Crowds of people filled the galleries.
The pictures were, with a few exceptions, mainly by relatively unknown artists.
Many of them were traditional pictures of landscapes and portraits.
I particularly liked a picture of an old farm house by a stream with a few sheep in a field.
The strangest picture I saw was an untitled abstract painting by a well-known modern artist.

It consisted of swirls of different colours
	which had been rubbed into the canvas with the artist's fingers.
The picture looked a mess, but was also very effective, attracting a lot of comment.
I couldn't help overhearing what people said,
	things like 'I could paint a picture like that with my eyes shut'
		or 'Look how perfect the sunset is in that painting.
		I'd love to own a picture like that' and so on.
There is no doubt it was an excellent exhibition
	because there were so many different styles on display.
There was something to suit everyone, but only if you could afford the high prices!

** Topics for discussion
