#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 28 Five pounds too dear
#+begin_verse
Why was even five pounds 'too dear'?

Small boats loaded with wares *sped to the great liner* as she was entering the harbour.
Before she had anchored,
	the men from the boats had climbed on board
	and the decks were soon covered with colourful rugs from Persia,
		silks from India, copper coffee pots, and beautiful handmade silverware.
It was difficult not to be tempted.
Many of the tourists on board had begun *bargaining with the tradesmen*,
	but I decided not to buy anything until I had disembarked.

I had no sooner got off the ship than I *was assailed by a man*
	who wanted to sell me a diamond ring.
I *had no intention of* buying one,
	but I *could not conceal the fact that* I *was impressed by* the size of the diamonds.
Some of them were as big as marbles.
The man *went to great lengths to prove that* the diamonds were real.
As we were walking past a shop,
	he held a diamond firmly against the window and made a deep impression in the glass.
It took me over half an hour to *get rid of him*.

The next man to approach me was selling expensive pens and watches.
I examined one of the pens closely.
It certainly looked genuine.
*At the base of the gold cap*, the words 'made in the USA' had been neatly inscribed.
The man said that the pen was worth 50 dollars,
	but *as a special favour*, he would *let me have it* for 30 dollars.
I shook my head and held up five fingers *indicating that* I was willing to pay 5 dollars.
Gesticulating wildly, the man acted as if he found my offer outrageous,
	but he eventually *reduced the price to 10 dollars*.
Shrugging my shoulders,
	I began to walk away when, a moment later, he ran after me and *thrust the pen into* my hands.
Though he kept *throwing up his arms* in despair, he readily accepted the 5 dollars I gave him.
I felt especially pleased with my wonderful bargain -- until I *got back to the ship*.
No matter how hard I tried,
	it was impossible to *fill this beautiful pen with ink*
	and *to this day* it has never written a single word!
#+end_verse
** expression
wares [wer] n. silverware n.:器物  银器
anchor: [ˈæŋkər] v.n.停航下锚
deck: [dek] n.甲板
tempt: [tempt] v.吸引;引诱
bargain: [ˈbɑrɡən] v.n.讨价还价
disembark: [ˌdɪsɪmˈbɑrk] v. to get off a ship下船上岸
assail: [əˈseɪl] v.骚扰
marble: [ˈmɑrb(ə)l] n.大理石
inscribe: [ɪnˈskraɪb] v.雕刻
favour: [ˈfeɪvər] n. favor 优惠
gesticulate: [dʒəˈstɪkjəˌleɪt] v.做手势
outrageous: [aʊtˈreɪdʒəs] adj.不公的
thrust: [θrʌst] v.猛塞

on the deck: 在甲板上
tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.: 引诱某人做某事
bargain with sb.: 和某人讨价还价
make a bargain with ...: 和某人讨价还价
be assailed by sb.: 被某人骚扰
A be inscribed on B A被雕刻在B上
as a special/personal favor (to sb.): 作为对某人的特殊优惠
do me a favor: 帮我个忙
it is outrageous (that) + ...: xx使非常不公的
thrust sth. into sw. (especially my hands): 猛塞某物在某处 
--------------------
speed to sp.: 加速到某地
sb. have no intention of doing sth.: 某人无意做某事
I can't conceal the fact that + ...: 我无法隐藏事实+...
sb. be impressed by sth.: 某人对某事印象深刻/被打动
go to great lengths to do sth.: 努力做某事
prove that + ...: 证明+...
go to great lengths to prove that + ...: 努力证明
get rid of sb.: 摆脱某人
at the base of sth.: 在...的基础上
let me have it: 给我吧
indicate that + ...: 表示...
reduce the price to $: 减少价格到...
throw up one's arms: 举起胳膊
get back to sp.: 回到某地
fill a. with b.: 用B充满A
to this day: 直到今天 by now

** words
wares [werz] n. 货物,商品
anchor [ˈæŋkər] v. 停航下锚
deck [dek] n. 甲板
silverware [ˈsɪlvərwer] n. 银器
tempt [tempt] v. 吸引;引诱
bargain [ˈbɑːrɡən] v. 讨价还价
disembark [ˌdɪsɪmˈbɑːrk] v. 下船上岸
assail [əˈseɪl] v. 纠缠
marble [ˈmɑːrb(ə)l] n. 小玻璃球
inscribe [ɪnˈskraɪb] v. 刻写,雕
favour [ˈfeɪvər] n. 好处,优惠
gesticulate [dʒeˈstɪkjuleɪt] v. (讲话时)打手势
outrageous [aʊtˈreɪdʒəs] adj. 出人意料的; 令人不悦的
thrust [θrʌst] v. 硬塞给

** vocabulary
loaded with wares: piled high with goods
liner: passenger ship
rugs: mats, small carpets
bargaining: arguing about the price
went to great lengths: did everything he could
impression: mark, scratch
to get rid of him: to make him go away

** DONE 单词造句
CLOSED: [2023-12-14 Thu 19:17]
wares n. silverware n.
- The ship loaded with wares is sinking.
- These craftsmen decided to sell their wares at the village fair.
- It is not allowed to sell wares at the square.
- The authorities forbid us to sell wares here.
- The officer claimed that these wares is not exempted from import duty.
anchor v.n.
- The boy didn't follow his father's instruction to anchor the ship.
- After greeted by an unpleasant smell, he anchored the boat and arrived on the scene.
- The ship needn't have been anchored at the harbour.
- On the the other, the anchor has already been broken.
- I'm genuinely sorry that I didn't arrive on time because the anchor has been broken.
deck n.  on the deck
- He realized to his horror that his baby is sleeping on the deck.
- The order to gather round on the deck was given.
- I am a little tired, for I has been wandering on the deck.
- You will have a good view on the deck.
- Why don't we grab a beer on the deck?
tempt v.  tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.
- The archaeologist which is not tempted to touch it is the exception to the general rule.
- In studying English, she is tempted to read science fiction.
- I seem to be tempted to disembark in advance.
- My cousin makes every effort to tempt me into smoking again.
- I was greeted by a familiar smell which tempted me to light up a cigarette.
bargain v.n.  bargain with sb.  make a bargain with ...
- I always fail to bargain with these vendors by the lake.
- Those busmen going on a strike refused to make a bargain with their boss in this way.
- It is said that she lives by bargaining with us.
- In the light of this rule, I have made a bargain with devil.
- I should have made a bargain with devil.
disembark v.
- As long as I spoted my wife waving to me, I disembarked.
- If I have seen you waitting for me, I would have already disembarked.
- In his effort to sell me this product, I disembarked.
- If you had disembarked at that time, you would have gotten a pen for nothing.
- The anchor enables us to disembark at this harbour.
assail v.  be assailed by sb.
- I was assailed by doubts why police asked me to station..
- It is no use pretending that you aren't assailed by doubts.
- I was assailed by the enthusiasm of my pupils.
- It is difficult to be assailed by a vendor in the open in this country.
- I was free from being assailed by his enthusiasm.
marble n.
- He grabed these marbles with great ease.
- He has eaten this marble and has consequences.
- Because of the marble, one of my close friends held a grudge against me when I was very young.
- These marbles which her mother presented to her gave her spiritual comfort.
- The marble dyed red is the exception to the rule.
inscribe v.  be inscribed on sth.
- People in German gave him a state funeral and his name has been insrcibed on monument.
- My aunt told me that my wife's name was inscribed on headstone of my grandfather.
- Instead of my wife's name, I chose to inscrib my father's name on the pen.
- It is difficult to inscribe so many words on the wood.
- The machine made it possible for me to inscribe these words on the plate.
favour n. favor  as a special/personal favor (to sb.)  do me a favor
- As my wife, I am asking you to do me a favor.
- And as a special favor, she had a really good seat.
- I want you to reconsider it as a personal favor to me.
- As a special favor, I will offer 5 dollars a pound for your pizza.
- It is anticipated that local people will do us a favor.
gesticulate v.
- I was gesticulating at her to capture her attention.
- Wildly as he gesticulated, we failed to say the magic word.
- Wildly as he gesticulated, we didn't have a subtle mind.
- I was influenced by the guy who gesticulated at me wildly.
- Before gesticulating at her, he had been smiling.
outrageous adj.  it is outrageous (that)
- It is outrageous that you classify tramps as beggars.
- It is outrageous that the pupil has a better salary than me.
- It is outrageous that you didn't say the magic word.
- It is outrageous that you have bad taste in clothes.
- It is outrageous that she leaped out at you in the exhibition.
thrust v.  thrust sth. into sw. (especially my hands)
- My aunt thrust pocket money into my hands.
- You needn't have thrusted ice cream into my mouth.
- You grandmother is about to thrust snacks into your pocket.
- As long as the bell rang, the student thrusted his paper into my hands.
- It is all very well that your friend thrusts marbles into your hands.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-14 Thu 20:39]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-14 Thu 19:35]
speed to sw.
- If you speed to the station, you may catch the train.
- I'm exhasuted, for I has been speeding to office.
- I starved to death after I had sped to school.
- I couldn't speed to the theatre because of broken car.
- The doctor was speeding to hospital to have an operation.
sb. have no intention of doing sth.
- He has no intention of doing housework. This made my hair stand on.
- I have no intention of being a medical student.
- I have no intention of having a skeleton in the cupboard.
- I have no intention of listening to you.
- I have no intention of using vivid sayings.
I can't conceal the fact that + ...
- I try to conceal the fact that my stomach turned.
- He failed to conceal the fact that he didn't pass the test.
- He managed to conceal the fact that he hadn't taken a shower.
- I can't concel the fact that I felt sick to my stomach at the idea of her.
- He managed to conceal the fact that these clothes his wife bought didn't appeal to him.
sb. be impressed by sth.
- I was impressed by the buildings.
- The sad truth is that I wasn't impressed by the gift she gave me.
- I was impressed by the meal which she cooked for me.
- I was impressed by the fact that she has received so many praises.
- I was impressed by the story she read to me last night.
go to great lengths to do sth.
- I went to great lengths to write out the paper in full.
- I went to great lengths to play a joken on him.
- I went to great lengths to make a speech in front of students.
- She went to great lengths to change into the dress which she bought last year.
- My cat went to great lengths to capture my attention.
prove that + ...
- My cat proved that cats never fascinate human beings.
- It proved that she had already gained her independence.
- It proved that she received a warm welcome.
- It proved that she is in difficulty.
- It proved that the microphone is connected to the tower.
get rid of sb.
- We managed to get rid of my grandmother by speeding to forest.
- I'm glad that I got rid of him in the morning.
- Why don't we just get rid of him?
- It is easy to get rid of the police.
- I'm tired of getting rid of these tramps.
at the base of sth.
- It is said that there is a door at the base of the tower.
- She will insribe an article about tramps at the base of statue.
- My cat soon disappeared at the base of the bed.
- I'm genuinely sorry that you found my ex-girlfriend's name at the base of statue.
- There is a big hole at the base of the tree.
let me have it
- If you give me $5, I might let you have it.
- It is difficult to let me have it.
- If you gave me $5, I would let you have it.
- If you had given me $5, I would have let you have it.
- I'm not gonna let you have it.
indicate that + ...
- This indicates that we put tramps in the same class as beggars.
- This indicates that he treated me with contempt.
- This would indicate that I am envious of the man who works for alibaba.
- My investigations also indicate that she passed the test with great ease.
- This would indicate that he was afflicted by these anxieties.
reduce the price to $
- This indicates that the house would reduce the price to $100,000.
- After I bargain with him, he agreed to reduce the price to $100.
- We have made a bargain with each other and he will reduce the price to $100.
- It is difficult to reduce the price $100 this summar.
- If you reduced the price to $100,000, your house will soon be sold out.
throw up one's arms
- In studying English, she is always throwing up her arms.
- You needn't have thrown up your arms in the class.
- The man who is throwing up his arms is the exception to this general rule.
- She threw up her arms and has consequences.
- Less people in the apartment made it possible for me to throw up my arms.
get back to sw.
- The bicycle has made it possible for me to get back to museum.
- I was anxious to get back to work as quickly as possible.
- She got back to the village fair and got biscuits for nothing.
- If you got back to work, you would be free to do housework.
- She claimed that the ambassador has got back to his country.
fill a. with b.
- It comes as a surprise to learn that my cat filled the bottle with little stone.
- At the absence of his parents, the baby managed to fill the bottle with water.
- I chose to fill the blue bottle with water.
- In the light of this statement, the bottle is now filled with air.
- I'm busy filling the bottle with water. This really gave me spiritual comfort.
to this day
- To this day, I haven't sent my wife any gift.
- To this day, I am free to pay taxes.
- To this day, this kind of perfume is not exempted from import duty.
- To this day, the police is quite tolerant of these thieves.
- To this day, I haven't lit up any cigarette.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-14 Thu 20:39]
** DONE Ask me if 写+读
CLOSED: [2023-12-14 Thu 20:43]
1. Small boats sped to the great liner. Why
	 Why did small boats speed to the great liner?
2. Men from the boats climbed on board. Who
		Who climbed on board?
3. Tourists began bargaining with the men. How many
		How many tourists began bargaining with the men?
4. The writer decided not to buy anything. What
		What did the writer decide?
5. The writer was impressed by the size of the diamonds. Who
		Who was impressed by the size of the diamonds?
6. It took half an hour to get rid of the man. How long
	 How long did it take to get rid of the man?
7. The words 'made in the USA' were inscribed on the cap. Where
	 Where were the words 'made in the USA' inscribed?
8. The man originally offered to sell the pen for $30. How much
	 How much did the man originally offer to sell the pen?
9. The man agreed to sell the pen for $- How much
	 How much did the man agree to sell the pen?
10. It was impossible to fill the pen with ink. Why
		Why was it impossible to fill the pen with ink?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-14 Thu 20:54]
The man to approach me was selling pens and watches.
I examined a pen and found the words 'made in the USA' inscribed on the gold cap.
The man wanted to sell it for $30, but I was willing to pay $5.
After he reduced the price to $10, I began to walk away.
A moment later, he thrust the pen into my hands for $5.
I felt very pleased with my bargain until I found it couldn't write a single word.

The next man who approached him was selling watches and pens,
	and when the writer looked at one, it looked genuine.
The man said it worth $50 but the writer could have it for $30.
The writer offered him $5 and waited.
Eventually, as the writer was walking away, the man agreed and took $5.
The writer was very pleased --until he was back on board.
The pen was impossible to fill.
It has never written a word since.

** DONE tell the story 口语复述
CLOSED: [2023-12-14 Thu 20:58]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-14 Thu 21:02]
The writer had only just got rid of a man who was trying to sell a diamond ring
	when another man approached him with some expensive pens and watches.
When he held them up for the writer to look at, the writer showed quite a lot of interest.
'Can I see one of the pens?' the writer asked the man.
They all looked genuine.
The man handed the writer one and said: 'It's a beautiful pen, sir.
	It's worth $50, but you can have it for $30.'
When the writer offered him just $5, there was an argument about the price,
	but eventually the man said: 'You can have it for $10, sir. That's the least I can take.'

As the writer walked away shrugging his shoulders the man followed him.
'I can't really do it, sir----I'm almost giving it away,' he said, 'but you can have it for $5.'
The writer was obviously very pleased.
He gave the man $5, took the pen, and the man disappeared quickly into the crowd.
The writer was extremely pleased: he had bought a very expensive pen for just $5.
What a bargain!
Later, back on board ship,
	the writer discovered why the man had been in such a hurry to get away:
		you couldn't fill the pen with ink and it just didn't work!
It wasn't such a 'bargain' after all!

** Topics for discussion
