#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 30 The death of a ghost
#+begin_verse
Why did the two brothers keep the secret?

*For years*, villagers believed that Endly Farm was haunted.
The farm was owned by two brothers, Joe and Bob Cox.
They employed a few farmhands, but no one was willing to work there long.
*Every time* a worker gave up his job, he told the same story.
Farm labourers said that they always *woke up to find that* work had been done overnight.
Hay had been cut and cowsheds had been cleaned.
A farm worker, who *stayed up* all night,
	claimed to have seen a figure cutting corn *in the moonlight*.
In time, *it became an accepted fact that*
	the Cox brothers employed a conscientious ghost that did most of their work for them.

No one *suspected that* there might be someone else on the farm who had never been seen.
This was indeed the case.
A short time ago, villagers were astonished to learn that the ghost of Endley had died.
Everyone went to the funeral, for the 'ghost' was *none other than* Eric Cox,
	a third brother who *was supposed to* have died as a young man.
After the funeral, Joe and Bob revealed a secret which they had kept for over fifty years.

Eric had been the *eldest* son of the family, very much older than his two brothers.
He had been obliged to join the army during the Second World War.
As he hated army life, he decided to desert his regiment.
When he learnt that he would be sent abroad,
	he returned to the farm and his father hid him until the end of the war.
Fearing the authorities, Eric *remained in hiding* after the war as well.
His father told everybody that Eric had *been killed in action*.
The only other people who knew the secret were Joe and Bob.
They did not even tell their wives.
When their father died, they *thought it their duty to keep Eric in hiding*.
All these years, Eric had lived as a recluse.
He used to sleep during the day and work at night,
	quite unaware of the fact that he had become the ghost of Endley.
When he died, however, his brothers *found it impossible to* keep the secret any longer.
#+end_verse
** expression
labourer: ['leɪbərər] n. laborer劳动者
overnight: [ˈoʊvərˌnaɪt] adv.一夜之间
hay: [heɪ] n.干草
corn: [kɔrn] n.谷物
moonlight: [ˈmunˌlaɪt] n.月光
conscientious: [ˌkɑnʃiˈenʃəs] adj.认真的
suspect: [ˈsʌˌspekt] v.怀疑
desert: [ˈdezərt] v.开小差
regiment: [ˈredʒɪmənt] n.团(军队)
action: [ˈækʃ(ə)n] n.战斗
recluse: [ˈrekˌlus] n.隐士

stay overnight in the hay: to sleep somewhere for one night在干草中过夜
in the moonlight: 在月光下
suspect (that) + ...: 怀疑+...
a regiment of ...: 一团/群...
be killed in action: 战斗中牺牲
--------------------
every time: 时间状语 = whenever
wake up to find that + ...: 醒来发现+...
old elder eldest: 只能sb.,不能接sth.,也不能接than
	older oldest: 既能sb.,也能sth.
--------------------
for years: 数年
stay up (overnight): 熬夜
it became an accepted fact that + ...: 这已成为公认的事实+...
be supposed to be/do sth.: 应该是/做某事
remain in doing sth.: proceed to do sth.继续做某事
none other than: 不是其他人是
think it one's duty to do sth.: 认为做某事是某人的义务
keep sb. in hiding: 藏起某人
find it impossible to do sth.: 发现做某事不可能

** Words
labourer [ˈleɪbərər] n.劳动者
overngiht adv.一夜期间
hay [heɪ] n.干草
corn [kɔːrn] n.谷物
moonlight [ˈmuːnlaɪt] n.月光
conscientious [ˌkɑːnʃiˈenʃəs] adj.认真的
suspect [səˈspekt] v.怀疑
desert [ˈdezərt] v.(军队)开小差
regiment [ˈredʒɪmənt] n.(军队)团
action [ˈækʃ(ə)n] n.战斗
recluse [ˈrekluːs] n.隐士

** vocabulary
was willing: wanted, was prepared
labourers: farmhand, farm worker
claimed: said that, maintained that
an accepted fact: a general truth
conscientious: extremely careful
astonished: surprised
revealed: made known, told

** DONE 单词造句
CLOSED: [2023-12-18 Mon 22:11]
labourer n. laborer
- The farm laborer went to great lengths to make his son laugh to tears.
- The farm laborer found it hard to finish the task by the last day of the year.
- Whether the farm laborer finished the task or not largely depends on whether he worked hard.
- The director based his film on a real story about a farm laborer.
- To compensate for his unpleasant experience, the farm laborer went on a strike.
overnight adv.  stay overnight in the hay
- I have stayed overnight in the hay. This really gave me spiritual comfort.
- I was impressed by the farm laborer who stayed overnight in the hay.
- I can't conceal the fact that they stayed overnight in the hay.
- I have no intention of staying overnight in the hay.
- It is outrageous that you decided to stay overnight in the hay.
hay n.
- For instance, I found my cat hiding in the hay.
- Oddly enough, there is some puma fur in the hay.
- The baby sped to the hay when he was in farm for the first time.
- I used to hide in the hay in my youth.
- The woman hiding in the hay seems to be the exception  to the rule.
corn n.
- I hate to eat corn bread for breakfast.
- The woman was said to live by selling corn bread.
- The corn breads have been sold out, would you like anything else?
- It is difficult to eat corn bread without our parents' permission.
- She has been afflicted by the rotten corn bread.
moonlight n.  in the moonlight
- I never grudged asking you for marrying to me in the moonlight.
- He used to buy corn breads from the lady in the moonlight.
- She divised a plan to repair her car in the moonlight.
- There is no doubt that it can't capture my attention in the moonlight.
- She loves to dance in the moonlight.
conscientious adj.
- He is so conscientious that he takes his job seriously all the time.
- The conscientious worker has good taste in clothes.
- He is a conscientious headmaster, and every student admired him for his hard working.
- There is no doubt that he is a conscientious worker.
- There is a danger that a conscientious worker makes tremendous mistakes.
suspect v.  suspect (that) + ... 
- I suspected that you had used out of your pocket money.
- I suspected that our son was influenced by that boy.
- I suspected that the boat was strucked by a heavy shower.
- I suspected that he didn't have a perfect alibi.
- I suspected that the skeleton might leap out at us.
desert v.  a regiment of
- It is all very well a soldier never deserts army.
- It makes her hair stand on end, when she heard that she was deserted by her husband.
- As he deserted the army in his youth, he was judged by the military court.
- To varying degrees, he didn't desert the army.
- He has a skeleton in the cupboard, for he deserted the army during the world war.
regiment n.
- You should have returned to your regiment.
- It gave me the impression that he had returned to his regiment.
- There is a regiment of rabbits in the hay.
- He couldn't conceal the fact that his son had deserted the regiment.
- He showed me to the regiment at once.
action n.  be killed in action
- The medical student has been killed in action.
- It ruined his day when he heard that his son was killed in action.
- The enemy took possession of the city and he was killed in action.
- The sad truth is that your son have been killed in action.
- When he heard that his son was killed in action, his stomach turned.
recluse n.
- I never expected the recluse to listen to me.
- The recluse doesn't have cause to ask you for money.
- She insisted that the recluse should read the story to her.
- Much to my surprise, the recluse was none other than the gangster.
- I found it impossible to talk to the recluse.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-19 Tue 20:13]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-18 Mon 22:10]
every time: 时间状语 = whenever
- Every time I get back home, my cat runs straight at me.
- Every time I pay for, I will receive a message from alipay.
- Every time he hides in the hay, he has the impluse to go home.
- Every time I meet her, I want to tell her I love her.
- Every time I take a shower, I starve to death.
wake up to find that + ...
- I woke up to find that the clock was striking.
- She woke up to find that she was deserted by her husband.
- She woke up to find that the boat was loaded with goods.
- She woke up to find that the cat starved to death.
- She woke up to find that the captain had gave an order.
for years
- For years, she has been asking for meals.
- For years, she hitchhiked to Paris.
- For years, the perfume is exempted from import duty.
- For years, both brothers have one thing in common: they take insterest in English.
- For years, he made a study of ancient philosophy.
stay up
- I don't want to stay up this night.
- I asked my wife to take a shower, for I didn't want to stay up any more.
- She is likely to stay up tonight.
- She is supposed to not stay up any longer.
- She leads a meaning life and stays up for a long time.
it became an accepted fact that + ...
- It became an accepted fact that cats have nine lives.
- It became an accepted fact that there is no shortage of tall building in New York.
- It became an accepted fact that the film is based on a real story.
- It became an accepted fact that cats never fail to fascinate human beings.
- It became an accepted fact that the microphone has been conntected to the Big Ben.
be supposed to be/do sth.
- I was supposed to work hard.
- We were supposed to receive a warm welcome at the monastery.
- He was supposed to be a editor.
- The country was supposed to gain its independence 7 years ago.
- The microphone was supposed to connected to the big clock in London.
remain in doing
- It convinced him that he shouldn't remain in hiding in the hay.
- The boy who played truent from school remained in hiding behind the archway.
- Imagine her dismay when she found her father still remain in hiding.
- He ordered his men to remain in hiding in the hay.
- Because of the enemy, they had to remain in hiding.
none other than
- You will found that it was none other than the baker.
- It was none other than the gasman who was read the meter.
- The kidnapper was none other than his cousin.
- The boy who played truent from school was none other than your son.
- It was none other than you who gave birth to me.
think it one's duty to do sth.
- I thought it my duty to go on a strike.
- She considered it her duty to give birth to her baby.
- She thought it her duty to join the army.
- I though it my duty to be a good husand and father.
- These days, people don't think it their duty to give birth to their children.
keep sb. in hiding
- The actor kept the paper in hiding until the curtain went down.
- My cousin kept the book I borrowed in hiding until I quarreled with him.
- I kept my book in hiding so that it would be taken by my cousin.
- I kept the clothes in hiding to give my wife a surprise on her birthday.
- For instance, he kept my pocket money in hiding.
find it impossible to do sth.
- You found it impossible to get out of the room.
- The editor found it possible to publish a book.
- I found it impossible to send her a fax.
- He found it impossible to ice-skate in public.
- She found it impossible to ask her aunt for pocket money.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-19 Tue 20:13]
** DONE Ask me if 写+读
CLOSED: [2023-12-19 Tue 20:17]
1. Endley Farm was owned by the Cox brothers. Which farm
	 Which farm was owned by the Cox brothers?
2. Work was done overnight. What kind
		What kind of work was done overnight?
3. A farm worker claimed to have seen a figure cutting corn. Who
		Who claimed to have seen a figure cutting corn?
4. The brothers employed a conscientious ghost. Why
		Why did the brothers employ a conscientious ghost?
5. The villagers learnt that the ghost of Endley had died. When
		When did the villagers learn that the ghost of Endley had died?
6. Everyone went to Eric Cox's funeral. Whose
	 Whose funeral did everyone go to?
7. Eric had joined the army during the Second World War. When
	 When had Eric joined the army?
8. Eric deserted his regiment. Why
	 Why did Eric desert his regiment?
9. His father hid him during and after the war. Who
	 Who hid him during and after the war?
10. Eric had lived as a recluse all these years. How
		How had Eric lived all these years?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-19 Tue 20:32]
Eric joined the army during the Second World War.
As he hated army life and learnt that he would be send abroad,
	he got back to the farm and his father hid him during and after the war.
His father told everyone he was killed in action.
Joe and Bob, his two brothers, who knew the secret,
	kept him in hiding for over fifty years. 
They didn't even tell their wives and Eric had lived as a recluse.
His death made it impossible to keep it any longer.

Eric joined the army during the Second World War, but hated army life, so he deserted.
He returned to the farm where his father hid him until the end of the war,
	and he remained in hiding after the war.
His father told everyone that he had been killed in action.
Joe and Bob kept the secret, so Eric lived as a recluse.
He slept during the day and worked at night, so he became the 'ghost of Endley'.

** DONE tell the story 口语复述
CLOSED: [2023-12-19 Tue 20:34]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-19 Tue 20:39]
When I came in to work one morning I noticed that work had been done overnight
	-some hay had been cut and the cowsheds and other buildings had been cleaned,
	so l decided to stay up all the next night to try to solve the mystery.
	(I didn't tell Joe and Bob, of course.)
I hid in the barn and waited.
Obviously I fell asleep because I suddenly woke up to find that it was dark.
I went straight to the cowshed and found that it had already been cleaned.
Then I went out to the Fields where I could just see a figure working;
	I couldn't see whether it was a man, or a woman, or perhaps a ghost.

I was scared, so I rushed back to the farmhouse and woke up the others.
We all went out to the fields to see who it was, but when we got there, there was no one there.
When I was in the fields before, I didn't know what or who the figure was.
But now I was sure it was a ghost
	so I immediately decided not to work at Endley Farm any longer
	and handed in my resignation.
When I told my story to the villagers,
	many of them still didn't believe me,
	even though they knew that something strange had been going on at Endley Farm for years.

** Topics for discussion
