#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 35 Justice was done
#+begin_verse
The word 'justice' is given two different meanings in the text.
What is the distinction between them?

The word justice is usually associated with *courts of law*.
We might say
	that *justice has been done* when a man's *innocence or guilt has been proved beyond doubt*.
Justice is part of the complex machinery of the law.
Those who seek it *undertake an arduous journey* and can never be sure that they will find it.
Judges, *however* wise or eminent, are human and can *make mistakes*.

*There are rare instances when* justice almost *ceases to be* an *abstract concept*.
Reward or punishment are *meted out* quite *independent of human interference*.
At such times, justice acts like a living force.
When we use a phrase like 'it serves him right',
	we are, *in part*, admitting
		that a certain set of circumstances has enabled justice to act *of its own accord*.

When a thief was caught *on the premises of* a large jewelery store one morning,
	the shop assistants must have found it impossible to resist the temptation
		to say 'it serves him right.'
The shop was an old converted house with many large, disused fireplaces and tall, narrow chimneys.
Towards midday, a girl heard a muffled cry coming from behind one of the walls.
As the cry was repeated several times,
	she *ran to tell* the manager who promptly *rang up* the fire brigade.
The cry had certainly come from one of the chimneys,
	but as there were so many of them, the fire fighters could not be certain which one it was.
They located the right chimney by *tapping at* the walls and *listening for* the man's cries.
After chipping through a wall which was eighteen inches thick,
	they found that a man had been trapped in the chimney.
As it was extremely narrow, the man *was unable to* move,
	but the fire fighters were eventually able to free him by cutting a huge hole in the wall.
The sorry-looking, blackened figure that emerged,
	admitted at once that he had tried to *break into* the shop during the night
		but had got stuck in the chimney.
He had been there for nearly ten hours.
Justice had been done even before the man *was handed over to* the police.
#+end_verse
** expression
justice: [ˈdʒʌstɪs] n.正义,公正;司法
court: [kɔrt] n.法院
law: n.法律
innocence: [ˈɪnəs(ə)ns] n.无辜
undertake: [ˌʌndərˈteɪk] v.承担;着手做
arduous: [ˈɑrdjuəs] adj.艰苦的
abstract: [æbˈstrækt] adj.抽象的
concept: n.概念,观念
mete: [mit] out 给予,处置
interference: [ˌɪntərˈfɪrəns] n.干涉
accord: [əˈkɔrd] n.一致
premises: [ˈpremɪsəz] n.房屋
convert: [ˈkɑnˌvɜrt] v.转变
disused: [dɪsˈjuzd] adj.废弃的
fireplace: [ˈfaɪrˌpleɪs] n.壁炉
muffle: [ˈmʌf(ə)l] v.捂住
chip: [tʃɪp] v.砍
blacken: [ˈblækən] v.使变黑
emerge: [ɪˈmɜrdʒ] v.(从某处)出现

justice has been done/served: 正义得到伸张
court of law; courts of law: 法庭
prove sb's innocence: 证明某人的无辜
undertake a task/a project/research/a study/a journey: 承担重任
arduous task of doing sth./arduous journey: 做某事的重任
go through/embark on/begin arduous journey: 开始艰辛的旅程
understand + abstract concept: 理解抽象概念
interference in sth.: 对某事的干涉
Sorry for the interference, + ...: 很抱歉打扰了, ...
I hope you don't mind the interference, but + ...: 我希望你不介意打扰,但是+...
of sb's/sth's own accord: you do it because you want to, without being asked or forced处于某人的自愿
on the premises of a.: 在A的前提下
convert a. to/into b.: 把A变成B
emerge from sp.: 从某处出现
--------------------
however = no matter how 让步状语
get + done 被动
--------------------
beyond doubt: 毫无疑问
make mistakes: 犯错
There are rare instances when + ...: 有极少例子当...
cease to do: 不再去做
be independent of: 独立于
in part: 部分地
run to tell sb.: 跑去告诉某人
ring up: call sb. by phone打电话
tap at sth.: 敲击某物
listen for ...: 为...而听
be unable to do sth.: 不能做某事
break into sp.: 破门而入
be handed over to sb.: 被移交给

** words
justice [ˈdʒʌstɪs] n.正义,公正;司法
court [kɔːrt] n.法院
law [lɔː] n.法律
innocence [ˈɪnəsns] n.无辜
undertake [ˌʌndərˈteɪk] v.承担;着手做
arduous [ˈɑːrdʒuəs] adj.艰苦的
abstract [ˈæbstrækt] adj.抽象的
concept [ˈkɑːnsept] n.概念,观念
mete [miːt] out 给予,处置
interference [ˌɪntərˈfɪrəns] n.干涉
accord [əˈkɔːrd] n.一致
premises [ˈpremɪsɪz] n.房屋
convert [kənˈvɜːrt] v.转变,改变
disused [ˌdɪsˈjuːzd] adj.不再用的,废弃的
fireplace [ˈfaɪərpleɪs] n.璧炉
muffle [ˈmʌf(ə)l] v.捂住,厌抑
chip [tʃɪp] v.砍
blacken [ˈblækən] v.使变黑
emerge [ɪˈmɜːrdʒ] v.(从某处)出现

** DONE 单词造句
CLOSED: [2024-01-02 Tue 15:23]
justice n.  justice has been done/served
- I was bent on describing to my wife what happened in the court and how justice has been done.
- He cherished the hope that justice would be done after the ganster was arrested.
- The lawyer said that justice has been done and can't be bothered to help him anymore.
- There is always hope that justice has been served by the authorities in China.
- There was a time when justice was done in the society.
court n. law n.  court of law; courts of law
- In the court of law, he managed to piece together all the information that had come to light.
- In the court of law, the blacksmith carved a hero from the large stone.
- In the court of law, the judge made a mistake by chance.
- Above all, we are in the court of law and smoking is not allowed here.
- She was bent on revealing the fact in the courts of law.
innocence n.  prove sb's innocence
- In the court of law, the lawyer managed to prove her innocence.
- The teacher prised the box open and proved his students' innocence.
- My room was littered with empty beer glasses and this proved my innocence.
- She claimed that as she had a perfect alibi, she proved her innocence.
- I'm glad that an unopned junk mail proved my innocence.
undertake v.  undertake a task/a project/research/a study/a journey
- She undertook the task of cleaning up in the labyrinth of room.
- The boy undertakes the task of cleaning up the room which was littered with flowers.
- I mustered up the courage to undertake a journey to be fluent in English.
- She undertookk a project which was expected to make a profit.
- I undertook a journey to prove that she is innocent.
arduous adj.
	arduous task of doing sth./arduous journey
	go through/embark on/begin arduous journey
- The moment the order was given, he embarked on the arduous journey to break into the house.
- The fire brigade arrived on the scene and begun arduous journey to rescue people.
- Undertaking the project is an arduous task that has an influence on me for the rest of my life.
- Feeding the cat is not an arduous task that took you several hours.
- She was going through the arduous journey to bring up her three children by her own.
abstract adj. concept n.  understand + abstract concept
- I broke my attention so that I couldn't understand the abstract concept.
- There was a time when I couldn't understand the abstract concept like love and happiness.
- I made tremendous mistakes on these abstract concepts.
- If you understood the abstract concept, you would have solved the problem.
- It became accepted fact that he was bent on understanding these abstract concept in mathematic.
mete out
- Mr. Leo meted out extra assignments to those students who played truent from school.
- The students who cheated on the test must be meted out punishments.
- The punishment was not meted out, for the guy has a perfect alibi.
- Mr. Leo can't be bothered to mete out these students who talked on the phone in the class.
- The poor girl cherished the hope that he would be meted out in the end.
interference n.  interference in sth.
	Sorry for the interference, + ...
	I hop you don't mind the interference, but + ...
- Sorry for the interference, may I use your phone for a moment?
- Sorry for the interference, I think you have lost your key.
- Sorry for the interference, our company begins to make a profit.
- I hope you don't mind the interference, but you have made some mistakes.
- I hope you don't mind the interference, but your wife is having an operation.
accord n.  of sb's/sth's own accord
- My child described to me of his own accord what happened in his school.
- I picked up of my own accord in the station.
- I decided to go to the antique shop of my own accord.
- You must study hard of your own accord.
- These passers-by got the traffic on the move again of their own accord.
premises n.  on the premises of a.
- Whether you believed or not, the monster never dies on the premises.
- Sure enough, smoking was not allowed to on the premises of a large jewelry.
- She happened to make a real discovery on the premises of a large jewelry.
- There is some confusion about the premises of our company.
- Oddly enough, the lottery driver was drawing up alongside our boss on the premises.
convert v.  convert a. to/into b.
- She decribed to me how the old factory converted to a mall.
- There is a store which was coverted into a bus station in the suburbs.
- The authorities ordered the farmer to covert the field into forest.
- It is a catastrophe for me that you and father converted my room into wash room.
- It's outrageous that he converted a polluted factory into a house.
disused adj.
- There are a disused rail station in my hometown.
- We used to take a long walk alongside the disused rail way.
- We should drive alongside the disused rail way until we arrived our hotel.
- The disused chimney proved to be dangerous, for some stray dogs live there.
- The cat used to live in the disused fireplace.
fireplace n.
- She ran into fireplace while playing football.
- This was a prelude to an accident which they set the fireplace on fire.
- There are countless disused fireplaces in the suburbs.
- The cat who was born in the fireplace was raised by me.
- I was under the impression that the fireplace was useful.
muffle v.
- She is always complaining about the muffled voices from the next room.
- If you muffle your voice, how could I hear it?
- All of a sudden, I heard a muffled cry coming from the attic.
- She tried to muffle the clock by throwing it in the bushes.
- If you muffled your voices in public, we would have benefited from this.
chip v.
- After chipping through the wall, I was astonished to find that there were countless gold coins.
- After chipping through the wall, it astounded me that my daugter kept her pocket money in there.
- After chipping through the wall, it comes as a suprise to learn that there are some cameras.
- After chipping through the wall, we realized to our horror that it was made of sands and bones.
- After chipping through the wall, we found a man attempting to break into our house.
blacken v.
- Oddly enough, the smoke didn't blacken his face.
- With his face blackened, the fire fighter received a warm welcome.
- As the fire fighter rescued five people in difficulty, his face was blackened.
- Now that we have one thing in common: our faces have been blacken.
- She tried to recoginze a blacken figure after the fire.
emerge v.  emerge from
- The shy boy emerged from the room and learnt to study English.
- It seems that our cat emerged from at the bottom of the bed.
- As a gun emerged from the gangster's shirt, the crowd begun to be quiet.
- There is no shortage of rabbits emerging from bushes in America.
- The woman claimed to have seen a puma emerge from the bush, no one takes it seriously.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2024-01-02 Tue 20:19]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2024-01-02 Tue 15:23]
beyond doubt
- The America managed to gained its independence from England beyond doubt.
- The pop singer who gave five performances in our town has an impact on us beyond doubt.
- I love to lead a peaceful life beyond doubt.
- The film was based on a truly bargain hunter beyond doubt.
- The microphone has been conncted to the tower beyond doubt.
make mistakes
- Oddly enough, the man who made tremendous mistakes receive a warm welcome at the monastery.
- I managed to make fewer mistakes and pass the test.
- She made so many mistakes that she failed the test.
- I had made a mistake that I provide her with a song which reminded her of her dead father.
- My teacher informed me that I made no mistake on this test.
There are rare instances when + ...
- There are rare instances when people are willing to give up smoking.
- There are rare instances when your mother makes scrambled eggs for dinner.
- There are rare instances when your father drives at a fantatis speed on highway.
- There are rare instances when she fails tests.
- There are rare instances when she writes an article on hotel.
cease to do
- My wife asked me to cease to stay overnight.
- I am gonna cease to stay overnight on Christmas day.
- I never cease to provide my wife with anniversity gifts.
- She ceased to take care fo her baby and began to cry.
- The detective ceased to keep guard in front of the door.
be independent of
- I didn't go to university, for the simple reason that I am independent of other opinions.
- Independent of his parents, his company managed to make a profit.
- Such is human nature, that parents are more likely to make their children independent of them.
- Independent of other opinions, I decided to live abroad.
- I lead a meaningful life which is independent of my parents.
in part
- My cousin was willing to work in Shanghai,
		in part, because she thought she could wander around the street in the city.
- I went to extremes to publish a book about you, in part, because of my dead cat.
- I got impatient last night, in part, because you ate my sandwich.
- I was too embarrassed to say anything in the contest, in part, because of bad microphone.
- I was willing to go to the party, in part, because of your absence.
run to tell sb.
- My dog ran to tell me something that happened in the kitchen.
- My daughter ran to tell me that my wife was dressed in an old-fashion skirt.
- I ran to tell my boss who was reading story to his son.
- She ran to tell her partner who turned out to be a monster.
- I ran to tell Jack who was equipped with a specail type of machine.
ring up
- I had to ring up my boss, for I found a ring dating back to ancient times.
- The manager rang up the police, for someone asked him for protection money.
- I was amazed to find that my dog has rung up me.
- It astounded me that she didn't ring up me while she was in difficult.
- I was astonished to find that the man who rang up the police turned out to be a dog.
tap at sth.
- A bargain hunter may tap at the surface and listen for the voice if it is necessary.
- The teacher tapped at the boy's head, for he dyed her hair red.
- She tapped at the wall and threatened to put me out of business.
- She tapped at the window and tried to recognize the material of the window.
- I wished I had tapped at the wall to give your an alarm.
listen for ...
- Whenever I arrive at the hotel, I would listen for the voice of the stream.
- Every one is listening for audios, but few of us will pass the test.
- I realized to my horror that he is listening for the voice coming from the next room.
- If you listened for, you would realize that an alarm was given.
- If you listened for the course, you would not regard it as some magic words.
be unable to do sth.
- I am unable to go to work in time today.
- I am unable to make a study of philosophy any longer.
- I am unable to stand on my head, in part, because of my injury.
- I am unable to gain my independence, for I get a bad salary.
- She is unable to marry you, for you couldn't afford to pay it.
break into sp.
- The gangster went to extremes to break into the room.
- The man who broke into the house last night was arrested and was judged in courts of law.
- These gangsters are likely to break into the jail.
- Imagine his dismay when he found his house was broken into.
- There was a time when police often broke into the houses of innocent people.
be handed over to
- The man who was handed over to the jail turned out to be our ambassador.
- She was handed over to the police, as she tried to break into a premisies of the jewelry store.
- You'd better hold our breath, or you will be handed over to the jail.
- I spoted him being handed over to the police.
- This convinced me that my wife was handed over to the jail because of her criminals.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2024-01-02 Tue 20:19]
** DONE Ask me if 写+读
CLOSED: [2024-01-02 Tue 20:24]
1. The word justice is usually associated with courts of law. What
	 What is the word justice usually associated with?
2. Judges can make mistakes. Who
		Who can make mistakes?
3. Justice sometimes acts like a living force. When
		When does justice act like a living force?
4. The thief was caught on the premises of a large jewellery store. Where
		Where was the thief caught?
5. A girl heard a muffled cry coming from a chimney. What
		What did a girl hear coming from a chimney?
6. The manager rang up the fire brigade. Why
	 Why did the manager ring up the fire brigade?
7. They located the right chimney by tapping the walls. How
	 How did they locate the right chimney?
8. The fire fighters freed the thief by cutting a hole in the wall. How
	 How did the fire fighters free the thief?
9. The man had tried to break into the shop during the night. When
	 When had the man tried to break into the shop?
10. The man had been stuck in the chimney for ten hours. How long
		How long had the man been stuck in the chimney?

** DONE 摘要写作 写 & 对答案
CLOSED: [2024-01-02 Tue 20:39]
Towards midday, a girl in the jewellery heard a muffled cry
	coming from behind one of the walls several times.
She told the manager who promptly rang up the fire brigade.
As there were so many of chimneys, the fire fighters located the right one by tapping at the walls.
After chipping through a wall, they found a man had been trapped in the chimney.
The fire fighters managed to free him by cutting a huge hole in the wall.

A girl in the jewellery store heard muffled cries coming from behind a wall.
When she heard the cry again, she went and told the manager who rang the fire brigade.
When they arrived, the fire fighters found the right chimney by tapping the wall and listening.
They chipped through a thick wall and found the man
	who could not move because the chimney was so narrow.
They finally freed him by cutting a large hole in the wall.

** DONE tell the story 口语复述
CLOSED: [2024-01-02 Tue 20:39]
** DONE composition 阅读 或 写作
CLOSED: [2024-01-02 Tue 20:42]
There is a large jewellery store in the town that I have often wanted to rob.
A few weeks ago I started planning the theft and kept a close watch on the shop.
I noticed when people went in and out, when they started and finished work, and so on.
And I noticed the chimneys, too.
One night I climbed onto the roof of the store and looked for a way in.
One of the chimneys seemed wide enough for me to get in, so I started climbing down.
Very soon, however, I got stuck and had to climb out again.
I didn't give up.
I looked around, found another chimney that looked quite wide at the top and climbed down that one.
Again I got stuck.

This time, however, I was really stuck.
I could climb neither up nor down.
At first I struggled to try to free myself, but I couldn't get out.
Then I started to get scared and started sweating.
I tried to calm myself by quietly counting and thinking of pleasant things.
But nothing worked and finally l started shouting for help.
Nothing happened, everything was dark and silent, and I got more and more frightened.
I think I went to sleep because I suddenly realized that light was shining down the chimney.
I shouted and shouted.
Eventually I heard tapping and was finally freed by fire fighters
	who had smashed a hole in the chimney.

** Topics for discussion
