#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 36 A chance in a million
#+begin_verse
What was the chance in a million?

We are less credulous than we used to be.
In the nineteenth century, a novelist would *bring his history to a conclusion*
	by presenting his readers with a series of coincidences -- most of them *wildly improbable*.
Readers happily *accepted the fact that* an obscure maidservant was really the hero's mother.
A long-lost brother, who *was presumed dead*, was really alive all the time
	and wickedly *plotting to bring about the hero's downfall*.
*And so on*.
Modern readers would find such naive solutions totally unacceptable.
Yet, in real life, circumstances do sometimes *conspire to* bring about coincidences
	which *anyone but* a nineteenth century novelist would find incredible.

When I was a boy,
	my grandfather told me
		how a German taxi driver, Franz Bussman, found a brother
			who *was thought to* have been killed twenty years before.
While on a walking tour with his wife, he *stopped to* talk to a workman.
After they had gone on,
	Mrs. Bussman *commented on the workman's close resemblance to her husband*
		and even *suggested that* he might be his brother.
Franz *poured scorn on* the idea,
	pointing out that his brother had been killed in action during the war.
Though Mrs. Bussman *was fully acquainted with* this story,
	she thought that *there was a chance in a million that* she might be right.
A few days later, she sent a boy to the workman to ask him
	if his name was Hans Bussman.
*Needless to say*, the man's name was Hans Bussman and he really was Franz's long-lost brother.
When the brothers *were reunited*, Hans explained how it was that he was still alive.
After having been wounded *towards the end of the war*,
	he had been sent to hospital and *was separated from* his unit.
The hospital had been bombed and Hans had *made his way back into* Western Germany on foot.
Meanwhile, his unit was lost and all records of him had been destroyed.
Hans *returned to* his family home,
	but the house had been bombed
		and no one in the neighbourhood knew what had *become of* the inhabitants.
*Assuming that* his family had been killed during an air raid,
	Hans settled down in a village fifty miles away where he had remained ever since.
#+end_verse
** expression
credulous: [ˈkredjələs] adj. 轻信的
improbable: [ɪmˈprɑbəb(ə)l] adj. 不大可能的
obscure: [əbˈskjʊr] adj. 不起眼的
maidservant: [ˈmeɪdˌsɜrvənt] n. 女仆
presume: [prɪˈzum] v. 假定
wickedly: ['wɪkɪdli] adv. 心眼坏地
plot: [plɑt] v. 密谋
downfall: [ˈdaʊnˌfɔl] n. 倒台
naive: [nɑˈiv] adj. 天真的
unacceptable: [ˌʌnəkˈseptəb(ə)l] adj.不能接受的
conspire: [kənˈspaɪr] v.巧合促成
incredible: [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance: [rɪˈzembləns] n.相似
scorn: [skɔrn] n.嘲弄
acquaint: [əˈkweɪnt] v.使了解
reunite: [ˌrijuˈnaɪt] v.使团聚
assume: [əˈsum] v.假定,认为

It seems (highly/wildly) improbable that + ...: 似乎不可能
be presumed dead/innocent/guilty: 假定死亡/无辜/有罪
presume that + ...: 假定...
plot to do sth.: 密谋做某事
plot against sb.: 暗算某人
lead to sb's downfall: 导致某人的垮台
bring about sb's downfall: 使某人垮台
it be naive enough to believe/think + ...: 相信/认为+...是足够天真的
sb. be naive enough to believe/think + ...:某人足够天真才会相信/认为+...
it be unacceptable to do sth.: 做某事是不可接受的
conspire to do sth.: 合谋做某事
it is incredible (to sb.) that + ...: 难以置信的
it is incredible how + ...: 难以置信多么地...
it is incredible to do sth.: 做某事是难以置信的
bear a close/strong/striking resemblance to sb./sth.: 对某人/物非常相似
bear little/no resemblance to sb./sth.: 对某人/物不相似
resemblance to ...: 对...的相似
pour scorn on: 嘲笑
pour scorn on the idea/suggestion/plan/advice: 嘲笑...
acquaint sb. with sth.: 使某人熟悉某事物
sb. be acquainted with sth.: 某人熟悉了某物
be reunited with sb.: 和某人团聚
assuming that + ...: 假设...
it seems/is reasonable to assume that + ...: 假设...是合理的
--------------------
to do 非谓语结构
--------------------
a chance in a million: 百万分之一
bring ... to a conclusion: 把...结束
sb. accepted the fact that: 某人接受事实...
bring about sth.: 引起某事
and so on: 等等
anyone but: 所有人除了...
be thought to: 被认为...
stop to do:停下来去做某事 VS stop doing sth: 停下来做的事情
comment on sth./sb.: 评论...
suggest that + ...: 建议虚拟语气; 假设不用虚拟语气
there is/was a chance that + ...: ...有可能
needless to say: 不用说
towards the end of + sth.: 接近...的结尾
be separated from: 与...分离
make one's way back to sp.: 回某地
return to: 回去
What become of: 怎么了

** words
credulous [ˈkredʒələs] adj.轻信的
improbable [ɪmˈprɑːbəbl] ad.不太可能的
obscure [əbˈskjʊr] adj.不起眼的
maidservant [ˈmeɪdsɜːrvənt] n.女仆
presume [prɪˈzuːm] v.假定
wickedly [ˈwɪkɪdli] adv.心眼坏地
plot [plɑːt] v.密谋
downfall [ˈdaʊnfɔːl] n.倒台
naive [naɪˈiːv] adj.天真的
unacceptable [ˌʌnəkˈseptəbl] adj.不能接受的
conspire [kənˈspaɪər] v.(事件)巧合促成
incredible [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance [rɪˈzembləns] n.相似
scorn [skɔːrn] n.嘲弄
acquaint [əˈkweɪnt] v.使了解
reunite [ˌriːjuˈnaɪt] v.使团聚
assume [əˈsuːm] v.假定,认为

** DONE vocabulary
CLOSED: [2024-01-05 Fri 19:39]
credulous: willing to believe without proof
a conclusion: an ending
improbable: not likely to happen, unlikely
presumed: believed to be, assumed to be
plotting: secretly planning
totally: completely
bring about: cause to happen

** DONE 单词造句
CLOSED: [2024-01-04 Thu 09:54]
credulous adj.
- He is less credulous than he used to be, for he has some opinions based on his values.
- He is not credulous so that he avoided being fooled by authorities.
- I am so credulous that I am unable to make a decision by myself.
- The credulous boy played truent from school by listening to his partner.
- If you were less credulous, you would make less mistakes.
improbable adj.  It seems (highly/wildly) improbable that + ...
- It seems improbable that a pretty broke into the jewelry store during night.
- It seems improbable that the gangster has been handed over to the US government.
- It seems improbable that she has ran to tell her parents.
- It seems improbable that she made no mistake on the exam.
- It seems improbable that justice ceases to be an abstract concept in such situation.
obscure adj.
- The obscure maidservant claimed that justice has been done in the courts of law.
- The obscure prizefighter managed to prove his innocence.
- The obscure artist who wanted to rise to fame undertook an ardulous task.
- It is an obscure student who understands these abstract concepts.
- The obscure grocer turned out to be the ganster who broke into the store.
maidservant n.
- The maidservant went through arduous journey in the desert island of her own accord.
- The maidservant was invited to do housework in a desert island.
- In those days, maidservants were more likely to get a good salary.
- The maidservant converted the house into her grocery.
- A figure that emerged from the room was recognized as a maidservant.
presume v.  be presumed dead/innocent/guilty  presume that + ...
- If he had been presumsed dead, his wife would have had a perfect alibi.
- The gangster was presumed innocent by his lawyer in the courts of law.
- I presumed that you had passed the exam.
- She presumed that I cheated on her on vocation.
- I begged my wife not to presumed that I had cheated on her in New York.
wickedly adv.
- He wickedly described to me how to kidnap a lovable cat.
- The witch wickedly begged the princess to drink some water in the well.
- The evil boy wickedly prised the chest open.
- Wickedly laughing, he kicked his partner's ass.
- The witch wickedly carved a ghost out of the wood.
plot v.  plot to do sth.  plot against sb.
- There is always hope that a ugly gilr plots against heroine in these stories.
- He ploted to breakn into the antique shop.
- In the labyrinth of the room, they ploted to play truent from school.
- He cherished the hope that they ploted to betray against the king.
- The mere fact that they ploted to cheat on exam has a bad influence in our school.
downfall n.  lead to sb's downfall  bring about sb's downfall
- The mistakes she made in the contest led to her downfall by chance.
- Above all, such stupid remarks might lead to your downfall.
- My wife described to me how she brought about her boss' downfall.
- No one but enemy will benefit from the accident which brought about his downfall.
- The affairs piled up and led to his downfall.
naive adj.  it be naive enough to believe/think + ...  sb. be naive enough to believe/think + ...
- I am naive enough to believe that kindness will always be rewarded.
- She is naive enough to think that a man who runs a successful business is gonna marry her.
- It is naive enough to believe that she collided with a car on April 1st.
- It is naive enough to think that  a dog caused a series of accidents.
- I am naive enough to believe that you have told me the truth.
unacceptable adj.  it be unacceptable to do sth.
- It is unacceptable to reduce your wife to tears.
- It is unacceptable to keep an eye on my neighbor while studying.
- It is unacceptable to set the boat on fire.
- It is unacceptable to set up a chain of reactions.
- It is unacceptable to talk on the phone in the open air.
conspire v.  conspire to
- They conspired to kill a regiment of stray dogs.
- I was under the impression that they conspired to cheat on the exam.
- This gave me the impression that they conspired to kidnap my cat.
- They conspired to stay overnight in the hay.
- I woke up to find that they conspired to keep me in hiding.
incredible adj.
	it is incredible (to sb.) that + ...
	it is incredible how + ...
	it is incredible to do sth.
- It is incredible to me that he is willing to show me to his room.
- It is incredible how he sold a diamond as large as marbles.
- It is incredible how she poisoned her five husbands in her youth.
- It is incredible to bring a parcel of diamonds with my wife.
- It is incredible to me that he turns out to be a medical student.
resemblance n.
	bear a close/strong/striking resemblance to sb./sth.
	bear little/no resemblance to sb./sth.
	resemblance to ...
- Following in his father's footsteps, he bears a close resemblance to his father.
- The young lady claimed that his husband bears a strong resemblance to the workman.
- Some neighbors said that he bears little resemblance to his son.
- It gave me the impression that we bear a string resemblance to each other.
- His strong resemblance to a pirate makes my hair stand on end.
scorn n.  pour scorn on (idea/suggestion/plan/advice)
- It is all very well that you pour scorn on someone who discuss you.
- He is always pouring scorn on advice others give in his youth.
- He was about to pour scorn on her suggestion when his teacher came in.
- Once upon a time, there is a prince pouring scorn on his fellow soldier.
- I poured scorn on the advice that we concealed from our boss the fact that the project failed.
acquint v.  acquaint sb. with sth.  sb. be acquainted with sth.
- My wife was quite acquainted with my habit of smoking after dinner.
- My wife seems to be acquainted with the science fiction which was published recently.
- To varying degrees, I am acquainted with the monastery at St. Bernard.
- Even if you are acquainted with my body, please don't come in while I am taking a bath.
- These skiers were quite acquainted with the monastery where they received a warm welcom.
reunite v.  be reunited with sb.
- Imagine my dismay when I found that I could be reunited with my wife even after the war.
- So long as I am reunited with my child, I will deal with your problem.
- For your own protection, you'd better be reunited with your parents.
- The noble was reunited with his people and was given a state funeral.
- We'll be reunited with each other in US.
assume v.  assuming that + ...  it seems/is reasonable to assume that + ...
- It seems to assume that our company made a profit.
- Assuming that he was dead, they moved to a street.
- Assuming that he had finished homework, he was about to go to party.
- Assuming that they had an opportunity to meet queen, they were dressed in smart suits.
- Assuming that the boat was loaded with treasure, a group of pirates let out a cry.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2024-01-05 Fri 19:35]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2024-01-04 Thu 11:25]
a chance in a million
- There is a chance in a million that you win the lottery.
- There is a chance in a million that I make a name for myself.
- There was a chance in a million that she came to play football.
- There is a chance in a million that he offers to do the dishes.
- There is a chance in a million that our company makes a profit this year.
bring ... to a conclusion
- As the writer was put out of business, he couldn't bring his novel to a conclusion.
- He brought his novel to a conclusion by a accident setting up a series of reactions.
- He brought his novel to a conclusion by appearing a driver who pulled up.
- He brought his novel to a conclusion by getting the traffic on the move again.
- He brought his story to a conclusion
		by the situation that prince and princess live happily together.
sb. accepted the fact that 
- We accepted the fact that our child failed the exam.
- He accepted the fact that his son was killed in action during war.
- The boss accepted the fact that his workmen was in traffic jam.
- He accepted the fact that his room was littered with junk foods.
- I accepeted the fact that the chest I hid was prised open by someone.
bring about
- This brought about the kidnap of my cat.
- They conspired to destory the suspended bridge
		so that this brought about the downfall of our president.
- They plotted to bring about the president's downfall.
- Everyone cherishes the hope that this brought about the president's downfall.
- The mere fact that it brought about the president's downfall has a deep influence on me.
and so on
- A rabbit was carved from a wood, and so on.
- The kidnapper asked for a ransom of $10,000, and so on.
- Considering his lovable cat, he agreed to pay a ransom of $10,000, and so on.
- Following my father's instrcutions, I kept my word and went to the police, and so on.
- She explained that there were girls, boys, and so on.
anyone but
- My fellow told me that anyone but you takes the task seriously.
- Anyone but you changed your mind and followed Mr Leo's instructions.
- Sure enough, anyone but your husband commited a murder.
- Anyone but the poor gilr didn't leav in an orderly fashion.
- It astounded me that anyone but you went in front of the camp up and down.
be thought to
- The woman was thought to be a servant who poisoned her five husbands.
- The puma was thought to escape from a private collector.
- I was thought to take my job seriously.
- He was thought to be killed in action during war.
- He was thought to have seen a puma at large.
stop to do
- I stopped to prove it right.
- He stopped to catch sight of his father.
- I'm glad that you stopped to study.
- He stopped to have a rest in the afternoon.
- He stopped to show his identity car to the security in front of the gate.
comment on
- It is disturbing to hear that someone comments on a film that we haven't seen.
- She gets used to commenting on other's personal lifes in the open.
- No one will comment on a room that was used as a place of worship.
- It is considered unlucky for people commenting on god at the monastery.
- She was expect to comment on our story in the contest.
suggest that + ...
- I suggest that she played truent from school.
- I suggest that this will cause an strange situation.
- She suggests that she got enough money to buy the house.
- I suggest that I get used to working in office.
- She suggests that the room was used a place of worship.
there is/was a chance that + ...
- There is a chance that she will give us a surprise.
- There is a chance that the archaeologist made a real discovery.
- There is a chance that a bargain hunter found something valuable in antique shop.
- There is a chance that she recognized your brother as her father.
- There is a chance that she was quipped with a torchlight.
needless to say
- Needless to say, she happened to wander around the park.
- Needless to say, the ring dates back to 10th century.
- Needless to say, he was amazed to find that they had to abandon ship.
- Needless to say, it turned out to be a little boy.
- Needless to say, he sacrificed his pocket money for a long journey.
towards the end of + sth.
- People return to their home towards the end of the year.
- I'll keep the secret towards the end of the month.
- You'll have the privilege of meeting the queen towards the end of the year.
- She didn't take a shower towards the end of the year.
- We are gonna to keep the status quo towards the end of the year.
be separated from
- He was separetaed from his unit and survived.
- It was me who was separeted from my parents at very young age.
- Such is human nature, that we are unwilling to be separeted from our couple.
- This can give rise to curious situation,
		as it did in the case of Mr. Leo who was separeted from his wife.
- The man separeted from his wife during the war was persumed dead.
make one's way back to
- The turtle goes to extreme to make its way back to the sea.
- In the end, the snake makes its way back to the cave.
- It only took me five minutes to make my way back to the house.
- The man called Leo made his way back to the US.
- She published a book on a princess who made her way back to the castle.
return to
- He suggests that he returned to the house before and had a perfect alibi.
- I was willing to return to my house now.
- Changed into dress, she returned to her house.
- As he returned to his house on duty, he got fired.
- She sent me a fax which asked me to return to office in time.
What become of
- I didn't know what become of her three years ago.
- I was gonna write an article on what become of the inhabitants.
- I didn't know what become of her, why did she smash everything to pieces?
- Imagine his dismay when he found out what become of his parents.
- So long as you tell me what become of her, I will reward you with $100.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2024-01-05 Fri 19:35]
** DONE Ask me if 写+读
CLOSED: [2024-01-05 Fri 19:44]
1. We are less credulous than we used to be. Why
	 Why are we less credulous than we used to be?
2. Novel readers used to accept wildly improbable endings. What
		What did novel readers use to accept?
3. Modern readers could accept such solutions. Why couldn't
		Why couldn't modern readers accept such solutions?
4. Incredible coincidences occur in real life. When
		When do incredible coincidences occur in real life?
5. Franz recognized his brother when he first met him. Why didn't
		Why didn't Franz recognized his brother when he first met him?
6. Mrs. Bussman discovered that the workman was Franz's long-lost brother. How
	 How did Mrs. Bussman discover that the workman was Franz's long-lost brother?
7. Hans had been sent to hospital after he had been wounded. When
	 When had Hans been sent to hospital?
8. The hospital had been bombed. What
	 What had been bombed?
9. All records of him had been destoryed. What
	 What had been destoryed?
10. Hans had settled down in a village fifty miles away. Where
		Where had Hans settled down?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2024-01-05 Fri 19:57]
Hans Busman had been sent to hospital and was separated from his unit.
The hospital was bombed so that he had to return to his home.
Because his unit was lost, all his records missed.
He found the house had been bombed and on one knew what had happened to his family.
Then he settled down in a village where he had remained ever since
	util he met Franz and his wife.

Hans had been wounded towards the end of the war, taken to hospital and separted from his unit.
When the hospital had been bombed, he had returned to West Germany on foot.
Meantime, his unit had been lost and all records of him destoryed.
He returned to the family home to find the house bombed.
Assuming all his family were dead,
	he settled in a village 50 miles away wwhere he had lived until he met Franz and his wife.


** DONE tell the story 口语复述
CLOSED: [2024-01-05 Fri 20:01]
** composition 阅读 或 写作
When the war finished,
	Franz Bussman did everything he could to get information about his brother Hans.
With no information, he reluctantly assumed his brother was dead and gave up the search.
With no family, and having been unable to find his brother,
	Franz found it difficult to settle down.
Over the years he moved from place to place and from job to job,
	never staying very long in one place.
When he met Anna (now Mrs. Bussman),he was working as a waiter in a hotel.
He and Anna got married and Franz settled down at last.
He moved from the dinning room into the kitchen of the hotel and became a cook.
But this did not last very long.

He was talking to a friend one day, a taxi driver,
	who suggested that they should go into partnership.
So they did, and Franz became a taxi driver.
He and the friend drove taxis themselves,
	but they also soon owned four more taxis and employed four drivers.
He visited his home town once to visit his old house, but it was a sad visit.
There was a large modern block of flats where his family house used to be.
And although he spoke to some of the apartment owners,
	no one remembered him or his family.
Now that he has finally found his brother Hans,
	he and Anna are planning to invite Hans to come
		and live near them
		and work as a taxi driver in the company.

** Topics for discussion
