#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 40 Who's who
#+begin_verse
How did the policeman discover that the whole thing was a joke?

It has never been explained
	why university students seem to enjoy practical jokes more than anyone else.
Students specilize in a particular type of practical joke: the hoax.
Inviting the fire brigade to put out a nonexistent fire is a crude form of deception
	which on self-respecting student would ever indulge in.
Students often create amusing situations
	which are funny to everyone except the victims.

When a student recently saw two workmen using a pneumatic drill outside his university,
	he immediately telephoned the police and informed them
		that two students dressed up as workmen were tearing up the road with a pneumatic drill.
As soon as he had hung up,
	he went over to the workmen and told them
		that if a policeman ordered them to go away, they were not to take him seriously.
He added that a student had dressed up as a policeman
	and was playing all sorts of silly jokes on people.
Both the police and the workmen were grateful to the student for this piece of advance information.

The student hid in an archway nearby where he could watch and hear everything that went on.
Sure enough, a policeman arrived on the scene and politely asked the workmen to go away.
When he received a very rude reply from one of the workmen,
	he threatened to remove them by force.
The workmen told him to do as he pleased and the policeman telephoned for help.
Shortly afterwards, four more policemen arrived and remonstrated with the workmen.
As the men refused to stop working,
	the police attempted to seize the pneumatic drill.
The workmen struggled fiercely and one of them lost his temper.
He threatened to call the police.
As this, the police pointed out ironically
	that this would hardly be necessary as the men were already under arrest.
Pretending to speak seriously,
	one of the workmen asked if he might make a telephone call before being taken to the station.
Permission was granted and a policeman accompanied him to a pay phone.
Only when he saw that the man was actually telephoning the police
	did he realize that they had all been the victims of a hoax.
#+end_verse

** words
hoax [hoʊks] n.骗局
deception [dɪˈsepʃ(ə)n] n.骗局
self-respecting adj.自重的
indulge [ɪnˈdʌldʒ] v.使沉迷
pneumatic [nuːˈmætɪk] adj.气动的
drill [drɪl] n.钻
silly [ˈsɪli] adj.无意义的
advance [ædˈvæns] adj.预先的
archway [ˈɑːrtʃweɪ] n.拱形门楼
remonstrate [rɪˈmɑːnstreɪt] v.规劝
ironically [aɪˈrɑːnɪkli] adv.讽刺地
permission [pərˈmɪʃ(ə)n] n.许可
grant [ɡrænt] v.同意

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
