#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 41 Illusion of pastoral peace
#+begin_verse
What particular anxiety spoils the country dweller's visit to the theatre?

The quite life of the country has never appealed to me.
City born and city bred,
	I have always regarded the country as something you look at through a train window,
		or something you occasionally visit during the weekend.
Most of my friends live in the city,
	yet they always go into raptures at the mere mention of the country.
Though they extol the virtues of the peaceful life,
	only one of them has ever gone to live in the country
	and he was back in town within six months.
Even he still lives under the illusion that country life is somehow superior to town life.
He is forever talking about the friendly people,
	the clean atmosphere, the closeness to nature and the gentle pace of living.
Nothing can be compared, he maintains,
	with the first cockcrow,
		the twittering of birds at dawn,
		the sight of the rising sun glinting on the trees and pastures.
This idyllic pastoral scene is only part of the picture.
My friend fails to mention the long and friendless winter evenings in front of the TV
	-- virtually the only form of entertainment.
He says nothing about the poor selection of goods in the shops,
	or about those unfortunate people
		who have to travel from the country to the city every day to get to work.
Why people are prepared to tolerate a four-hour journey each day
	for the dubious privilege of living in the country is beyond me.
They could be saved so much misery and expense if they chose to live in the city
	where they rightly belong.

If you can do without the few pastoral pleasures of the country,
	you will find the city can provide you with the best that life can offer.
You never have to travel miles to see your friends.
They invariably live nearby
	and are always available for an informal chat or ane evening's entertainment.
Some of my acquaintances in the country come up to town once or twice a year
	to visit the theatre as a special treat.
For them this is a major operation
	which involves considerable planning.
As the play draws to its close,
	they wonder whether they will ever catch that last train home.
The city dweller never experiences anxieties of this sort.
The latest exhibitions, films, or plays are only a short bus ride away.
Shopping, too, is always a pleasure.
There is so much variety that you never have to make do with second best.
Country people run wild
	when they go shopping in the city
		and stagger home loaded with as many of exotic items as they can carry.
Nor is the city without its moments of beauty.
There is something comforting about the warm glow shed by advertisements on cold wet winter nights.
Few things could be more impressive than the peace
	that descends on deserted city streets at weekends
		when the thousands that travel to work every day are tucked away in their homes in the country.
It has always been a mystery to me why city dwellers,
	who appreciate all these things,
		obstinately pretend that they would prefer to live in the country.
#+end_verse

** words
illusion [ɪˈluːʒ(ə)n] n.幻想
pastoral [ˈpæstərəl] adj.田园的
breed [briːd] v.培育
rapture [ˈræptʃər] n.欣喜
extol [ɪkˈstoʊl] v.赞美
superior [suːˈpɪriər] adj.优越的
cockcrow [ˈkɑːkkroʊ] n.鸡叫
twitter [ˈtwɪtər] v.(鸟)吱吱叫
glint [ɡlɪnt] v.闪烁
pasture [ˈpæstʃər] n.牧场
idyllic [aɪˈdɪlɪk] adj.田园诗的
virtually [ˈvɜːrtʃuəli] adv.几乎,差不多
dubious [ˈduːbiəs] adj.可疑的,怀疑的
privilege [ˈprɪvəlɪdʒ] n.特权
misery [ˈmɪzəri] n.苦难
acquaintance [əˈkweɪntəns] n.熟人
treat [triːt] n.难得的乐事,享受
dweller [ˈdwelər] n.居住者
stagger [ˈstæɡər] v.摇晃,蹒跚
exotic [ɪɡˈzɑːtɪk] adj.异乎寻常的,外来的
glow [ɡloʊ] n.白织光
descend [dɪˈsend] v.下落,降临
obstinately [ˈɑːbstɪnətli] adv.固执地,顽固地

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
