#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 42 Modern cavemen
#+begin_verse
With what does the writer compare the Gouffre Berger?

Cave exploration, or pot-holing, as it has come to be known, is a relatively new sport.
Perhaps it is the desire for solitude or the chance of making an unexpected discovery
	that lures people down to the depths of the earth.
It is impossible to give a satisfactory explanation for a pot-holer's motives.
For him, caves have the same peculiar fascination which high mountains have for the climber.
They arouse instincts which can only be dimly understood.

Exploring really deep caves is not a task for the Sunday afternoon rambler.
Such undertakings require the precise planning and foresight of military operations.
It can take as long as eight days to rig up rope ladders
	and to establish supply bases before a descent can be made into a very deep cave.
Precautions of this sort are necessary,
	for it is impossible to foretell the exact nature of the difficulties
		which will confront the pot-holder.
The deepest known cave in the world is the Goffre Berger near Grenoble.
It extends to a depth of 3723 feet.
This immense chasm has been formed by an underground stream
	which has tunnelled a course through a flaw in the rocks.
The entrance to the cave is on a plateau in the Dauphine Alps.
As it is only six feet across, it is barely noticeable.
The cave might never have been discovered
	had not the entrance been spotted by the distinguished French pot-holer, Berger.
Since its discovery, it has become a sort of pot-holers' Everest.
Though a number of descents have been made, much of it still remains to be explored.

A team of pot-holers recently went down the Gouffre Berger.
After entering the narrow gap on the plateau,
	they climbed down the steep sides of the cave until they came to a narrow corridor.
They had to edge their way along this,
	sometimes wading across shallow streams, or swimming across deep pools.
Suddenly they came to a waterfall which dropped into an underground lake at the bottom of the cave.
They plunged into the lake, and after loading their gear on an inflatable rubber dinghy,
	let the current carry them to the other side.
To protect themselves from the icy water, they had to wear special rubber suits.
At the far end of the lake,
	they came to huge piles of rubble which had been washed up by the water.
In this part of the cave,
	they could hear an insistent booming sound
		which they found
	was caused by a small waterspout shooting down into a pool from the roof of the cave.
Squeezing through a cleft in the rocks,
	the pot-holers arrived at an enormous cavern, the size of a huge concert hall.
After switching on powerful are lights
	they saw great stalagmites -- some of them over forty feet high
	-- rising up like tree-trunks to meet the stalactites suspended from the roof.
Round about, piles of limestone glistened in all the colors of the rainbow.
In the eerie silence of the cavern,
	the only sound that could be heard
#+end_verse

** words
cavemen ['keivmən] n.洞穴人
pot [pɑːt]-holing n.洞穴探险
solitude [ˈsɑːlətuːd] n.孤独,寂寞
lure [lʊr] v.引诱
pot [pɑːt]-holer n.洞穴探险者
rambler [ˈræmblər] n.漫步者
undertaking [ˌʌndərˈteɪkɪŋ] n.任务
foresight [ˈfɔːrsaɪt] n.预见
foretell [fɔːrˈtel] v.预言
Grenoble [ɡrəˈnoʊbəl] n.
chasm [ˈkæzəm] n.断层,裂口
flaw [flɔː] n.小裂缝
distinguished [dɪˈstɪŋɡwɪʃt] adj.杰出的
Everest [ˈevərəst] n.珠穆朗玛峰
wade [weɪd] v.涉水
waterfall [ˈwɔːtərfɔːl] n.瀑布
gear [ɡɪr] n.一套用具
inflatable [ɪnˈfleɪtəbl] adj.可充气的
rubble [ˈrʌbl] n.碎瓦
insistent [ɪnˈsɪstənt] adj.连续的
boom [buːm] v.轰鸣
waterspout [ˈwɔːtərspaʊt] n.强大的水柱
cleft [kleft] n.裂隙,开口
cavern [ˈkævərn] n.大洞穴
stalagmite [stəˈlæɡmaɪt] n.石笋
stalactite [stəˈlæktaɪt] n.钟乳石
limestone [ˈlaɪmstoʊn] n.石灰石
glisten [ˈɡlɪs(ə)n] v.闪烁
eerie [ˈɪri] adj.可怕的
dome [doʊm] n.圆顶

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
