#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 45 The power of the press
#+begin_verse
Does the writer think the parents were lucky or unlucky to gain prosperity in this way? Why?

In democratic countries any efforts to restrict the freedom of the press are righly condemned.
However, this freedom can easily be abused.
Stories about people often attract far more public attention than political events.
Though we may enjoy reading about the lives of others,
	it is extremely doubtful whether we would equally enjoy reading about ourselves.
Acting on the contention that facts are sacred,
	reporters can cause untold suffering to individuals
		by publishing details about their private lives.
Newspapers exert such tremendous influence
	that they can not	only bring about major changes to the lives of ordinary people
		but can even overthrow a government.

The story of a poor family that acquired fame and fortune overnight,
	dramatically illustrates the power of the press.
The family lived in Aberdeen, a small town of 23,000 inhabitants in South Dakota.
As the parents had five children, life was a perpetual struggle against poverty.
They were expecting their six child and were faced with even more pressing economic problems.
If they had only had one more child,
	the fact would have passed unnoticed.
They would have continued to struggle against economic odds and would have lived in obscurity.
But they suddenly became the parents of quintuplets, four girls and a boy,
	an event which radically changed their lives.
The day after the birth of the five children,
	an airplane arrived in Aberdeen bringing sixty reporter and photographers.

The rise to fame was swift
Television cameras and newspapers carried the news to everyone in the country.
Newspapers and magazines offered the family huge sums
	for the exclusive rights to publish stories and photographs.
Gifts poured in not only from unknown people,
	but from baby food and soap manufacturers who wished to advertise their products.
The olf farmhouse the family lived in was to be replaced by a new $500,000 home.
Reporters kept pressing for interviews so lawyers had to be employed to act as spokesmen
	for the family at press conferences.
While the five babies were still quietly sleeping in oxygen tents in a hospital nursery,
	their parents were paying the price for fame.
It would never again be possible for them to lead normal lives.
They had become the victims of commercialization,
	for their names had acquired a market value.
Instead of being five new family members,
	these children had immediately become a commodity.
#+end_verse

** words
democratic [ˌdeməˈkrætɪk] adj.民主的
restrict [rɪˈstrɪkt] v.限制
abuse [əˈbjuːs] v.滥用
contention [kənˈtenʃ(ə)n] n.论点
untold [ˌʌnˈtoʊld] adj.数不尽的,无限的
south [saʊθ] Dakota
perpetual [pərˈpetʃuəl] adj.永久的
quintuplet [kwɪnˈtʌplət] n.五胞胎之一
obscurity [əbˈskjʊrəti] n.默默无闻
radically [ˈrædɪkli] adv.彻底地
exclusive [ɪkˈskluːsɪv] adj.独占的
nursery [ˈnɜːrsəri] n.保育室
commercialization [kəˌmɜːrʃələˈzeɪʃn] n.商品化
commodity [kəˈmɑːdəti] n.商品

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
