#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 47 Too high a price?
#+begin_verse
What does the writer describe as an 'amusing old-fashioned source of noise'?

Pollution is the price we pay fro an overpopulated, over-industrialized planet.
When you come to think about it,
	there are only four ways you can deal with rubbish:
		dump it, burn it, turn it into something you can use again, attempt to produce less of it.
We keep trying all four methods,
	but the sheer volume of rubbish we produce world wide threatens to overwhelm us.

Rubbish, however, is only part of the problem of polluting our planet.
The need to produce ever-increasing quantities of cheap food
	leads to a different kind of pollution.
Industrialized farming methods produce cheap meat products: beef, pork and chicken.
The use of pesticides and fertilizers produces cheap grain and vegetables.
The price we pay for cheap food may be already too high:
	Mad Cow Disease(BSE) in cattle,
	salmonella in chicken and eggs,
	and listeria in dairy products.
And if you think you'll abandon meat and become a vegetarian,
	you have the choice of very expensive organically-grown vegetables
		or a steady diet peticiles every time
			you think you're eating fresh salads and vegetables,
	or just having an innocent glass of water.

However, there is an even more insidious kind of pollution
	that particularly affects urban areas and invades our daily lives, and that is noise.
Burglar alarms going off at any time of the day or night
	serve only to annoy passers-by and actually assist burglars to burgle.
Car alarms constantly scream at us in the street and are a source of profound irritation.
A recent survey of the effects of noise revealed(surprisingly?)
	that dogs barking incessantly in the night
		rated the highest form of noise pollution on a scale ranging from 1 to 7.
The survey revealed a large number of source of noise that we really dislike.
Lawn mowers whining on a summer's day,
	late-night parties in apartment blocks,
	noisy neighbours,
	vehicles of all kinds,
	especially large container trucks thundering through quiet villages,
	planes and helicopters flying overhead,
	large radios carried round in public places and played at maximum volume.
New technology has also made its own contribution to noise.
A lot of people object to mobile phones,
	especially when they are used in public places like restaurants or on public transport.
Loud conversations on mobile phones invade our thoughts
	or interrupt the pleasure of meeting friends for a quiet chat.
The noise pollution survey
	revealed a rather surprising and possibly amusing old-fashioned source of noise.
It turned out to be snoring!
Men were found to the worst offenders.
It was revealed that 20% of men in their mid-thirties snore.
This figure rises to a staggering 60% of men in their sixties.
Against these figures, it was found that only 5% of women snore regularyly,
	while the rest are constantly woken or kept awake by their trumpeting partner.
Whatever the source of noise, one thing is certain:
	silence, it seems, has become a golden memory.
#+end_verse

** words
pollution [pəˈluːʃ(ə)n] n.污染
overpopulated [ˌoʊvərˈpɑːpjuleɪtɪd] adj.人口多的
over industrialized [ˈoʊvər][ɪnˈdʌstriəlaɪzd] -adj.过度工业化的
sheer [ʃɪr] adj.纯粹的,不参杂的
worldwide [ˌwɜːrldˈwaɪd] adv.在全世界
overwhelm [ˌoʊvərˈwelm] v.降服
pollute [pəˈluːt] v.污染
pesticide [ˈpestəsaɪd] n.杀虫剂
fertilizer [ˈfɜːrtəlaɪzər] n.肥料
salmonella [ˌsælməˈnelə] n.沙门氏菌
listeria [lɪˈstɪriə] n.李斯特杆菌
vegetarian [ˌvedʒəˈteriən] n.吃素的人
organically [ɔːrˈɡænɪkli]-grown adj.有机培植的
insidious [ɪnˈsɪdiəs] adj.暗中为害的
urban [ˈɜːrbən] adj.城市的
burglar [ˈbɜːrɡlər] n.窃贼
burgle [ˈbɜːrɡl] v.入室偷窃
scream [skriːm] v.尖叫
profound [prəˈfaʊnd] adj.极度的
irritation [ˌɪrɪˈteɪʃ(ə)n] n.烦躁
incessantly [ɪnˈses(ə)ntli] adv.连续不断地
whine [waɪn] v.发呜呜声
helicopter [ˈhelɪkɑːptər] n.直升飞机
maximum [ˈmæksɪməm] adj.最大的
technology [tekˈnɑːlədʒi] n.技术
contribution [ˌkɑːntrɪˈbjuːʃ(ə)n] n.贡献
mobile [ˌmoˈbil] adj.可移动的
snore [snɔːr] v.打鼾
offender [əˈfendər] n.冒犯者
staggering [ˈstæɡərɪŋ] adj.令人惊愕的
trumpet [ˈtrʌmpɪt] v.吹号
partner [ˈpɑːrtnər] n.伙伴

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
