#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 51 Predicting the future
#+begin_verse
What was the 'future' electronic development that Leon Bagrit wasn't able to foresee?

Predicting the future is notoriously difficult.
Who could have imagined, in the mid 1970s, for example, that by the end of 20th century,
	computers would be as common in people's homes as TV sets?
In the 1970s, computers were common enough,
	but only in big business, government departments, and large organizations.
These were the so-called mainframe machines.
Mainframe computers were very large indeed,	often occupying whole air-conditioned rooms,
	employing full-time technicians and run on specially-written software.
Though these large machines still exist,
	many of their functions have been taken over by small powerful personal computers,
		commonly known as PCs.

In 1975, a primitive machine called the Altair, was launched in the USA.
It can properly be described as the first 'home computer'
	and it pointed the way to the future.
This was followed, at the end of the 1970s, by a machine called an Apple.
In the early 1980s, the computer giant, IBM produced the world's first Personal Computer.
This ran on an 'operating system' called DOS, produced by a then small Company named Microsoft.
The IBM Personal Computers was widely copied.
From those humble beginnings,
	we have seen the development of the user-friendly home computers and multimedia machines
		which are in common use today.

Considering how recent these development are,
	it is even more remarkable that as long as the 1960s,
	an Englishman, Leo Bagrit, was able to predict some of the uses of computers which we know today.
Bagrit dismissed the idea that computers would learn to 'think' for themselves
	and would 'rule the world', which people liked to believe in those days.
Bagrit foresaw a time when computers would be small enough to hold in the hand,
	when they would be used in hospitals to help doctors to diagnose illnesses,
		when thet would relieve office workers and accountants of dull, repetitive clerical work.
All these computer uses have become commonplace.
Of course, Leon Bagrit could not possibly have foreseen the development of the Internet,
	the worldwide system that enables us to communicate instantly with anyone
		in any part of the world by using computers linked to telephone networks.
Nor could he have foreseen how we could use the Internet
	to obtain information on every know subject,
	so we can read it on a screen in our homes and even print it as well if we want to.
Computers have become smaller and smaller, more and more powerful and cheaper and cheaper.
This is what makes Leon Bagrit's predictions particularly remarkable.
If he, or someone like him, were alive today,
#+end_verse

** words
notoriously [noʊˈtɔrɪəslɪ] adv.众所周知地
mainframe [ˈmeɪnˌfreɪm] n.主机,中央处理机
full-time adj.专职的
technician [tekˈnɪʃ(ə)n] n.技师
software [ˈsɔf(t)ˌwer] n.软件
IBM (Internation Business Machines)
DOS (Disk Operating System)
Microsoft ['maikrəusɔft] n.微软公司
user-friendly adj.容易操作的,好用的
multimedia [ˌmʌltaɪˈmidiə] adj.多媒体的
alternative [ɔlˈtɜrnətɪv] adj.选择的
diagnose [ˈdaɪəɡˌnoʊz] v.诊断
relieve [rɪˈliv] v.减轻
accountant [əˈkaʊntənt] n.会计
repetitive [rɪˈpetətɪv] adj.重复的
clerical [ˈklerɪk(ə)l] adj.办公室工作的
Internet [ˈintɜrnɛt] n.国际交互网
network [ˈnetˌwɜrk] n.网络

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
