#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+begin_verse
We throw around the word 'joy' casually.
'I'm overjoyed at the news.'
'She's a joy to be around.'
'It's a joyous occasion.'
But none of those examples really touches on true joy.
They are closer to 'cheer' than anything else.
Cheerfulness is surface level.

Joy, to Seneca, is a deep state of being.
It is what we feel inside us and has little to do with smiles or laughing.
So when people say that the Stoics are dour or depressive,
  they're really missing the point.
Who cares if someone is bubbly when times are good?
What kind of accomplishment is that?

But can you be fully content with your life,
  can you bravely face what life has in store from one day to the next,
  can you bounce back from every kind of adversity without losing a step,
  can you be a source of strength and inspiration to others around you?
That's Stoic joy—the joy that comes from purpose, excellence, and duty.
It's a serious thing far more serious than a smile or a chipper voice.
#+end_verse
