#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 02 Using Social Emotional Intelligence to foster Immensely Human Interaction
#+begin_verse
Welcome back.
We're going to tackle the following essential question.
How can knowing more about ourselves help us and learn more about others.
The way we'll open this up
	is referencing a really remarkable mid century TV show called The Twilight Zone.
In the opening episode, the very first series,
	they tackled this question of what would happen to us
		when we had to go into space
			and be separated from other human beings for an extended period of time.
This debuted before people were sent in space.
And it was a very interesting question, one of course, not truly tested in that context.
They basically came to the conclusion in the show
		and unfortunately we know from other experiences and research,
	that it is almost insufferable to be disconnected from other human beings.
We have an illusion
	that it is possible for us to be completely independent
		and be functional without other people.
As they captured in the episode in the barrier of loneliness,
	the palpable desperate need of the human animal to be with his or her fellow humans.
Up there in the vastness of space, in the void,
	that is this guy up there is an enemy known as isolation.
And again, the core point of that is isolation is something that is devastating to us.
In our focus in this part, when we talk about connecting with our own emotions,
	will help you understand the way in which that can allow us to be more connected about others.
Be more empathetic and build those higher quality connections.
#+end_verse
** expression
reference [ˈref(ə)rəns]: v. to mention another book, article etc that contains information connected with the subject you are writing about涉及, 参考
twilight [ˈtwaɪˌlaɪt]: n. the small amount of light in the sky as the day ends黎明, 微光
episode [ˈepɪˌsoʊd]: n. a television or radio programme that is one of a series of programmes in which the story is continued each week ⇨ series集
extended [ɪkˈstendəd]: adj. made longer or bigger长期的
debut [deɪˈbju]: v. to appear in public or become available for the first time初次登场, 开张
insufferable [ɪnˈsʌfərəb(ə)l]: adj. extremely annoying or unpleasant SYN unbearable难以忍受的
functional [ˈfʌŋkʃən(ə)l]: adj. something that is functional is working correctly SYN operational正常工作的
barrier [ˈberiər]: n. a physical object that keeps two areas, people etc apart屏障
palpable [ˈpælpəb(ə)l]: adj. a feeling that is palpable is so strong that other people notice it and can feel it around them OPP impalpable明显的
desperate [ˈdesp(ə)rət]: adj. willing to do anything to change a very bad situation, and not caring about danger令人绝望的
empathy [ˈempəθi] empathetic: n.adj. the ability to understand other people’s feelings and problems ⇨ sympathy同情心的,共情的
--------------------
open sth. up/ open up sth.: 打开某物
very first: 非常早的
come to the conclusion: 得出结论
be disconnected from sth./sb.: 与某人/某物断绝联系
the core point of sth.: 某事物的核心要点
** sentence
reference [ˈref(ə)rəns]: v. to mention another book, article etc that contains information connected with the subject you are writing about涉及, 查阅, 参考
- You need to reference more treatises to complete yours.
- Referencing to an old book in the library, Sams ensured that his name was not Jon Snow and he was not a bastard.
- Referencing to an ancient sheet of paper, the vicar sentenced the heretic to death.
twilight [ˈtwaɪˌlaɪt]: n. the small amount of light in the sky as the day ends黄昏, 微光
- I used to walk aroundside the river with my father at twilight.
- He ordered his men to fly over the South Pole at twilight.
- What I met at the twilight will stay in the minds of me.
episode [ˈepɪˌsoʊd]: n. a television or radio programme that is one of a series of programmes in which the story is continued each week ⇨ series集
- The bottom line I can't afford to so expensive episodes because of economic crises.
- The spokesman for this company claimed to have spent more than 1 million dollars each episode.
- Have you ever watched episode 8, my precious?
extended [ɪkˈstendəd]: adj. made longer or bigger长期的
- His father hasn't been standing for he for an extended period of time.
- He has been lack of friends for an extended period of time.
- Because of social upheaval the country was chaotic in politics for an extended period of time.
debut [deɪˈbju]: v. to appear in public or become available for the first time初次登场, 开张
- A band of gangsters stole three thousands dollars worth of diamond when the jwelery shop debuted.
- The sad truth is that the panda which is founded in China will not debut in our country.
- As long as the panda debuts, people will cheer up.
insufferable [ɪnˈsʌfərəb(ə)l]: adj. extremely annoying or unpleasant SYN unbearable难以忍受的
- Remaining calm under the stress is hard, the emotion is insufferable to me.
- The unfair terms of treaty is insufferable to me, I will not sign it up.
- His words alerted me to the insufferable terms of the treaty.
functional [ˈfʌŋkʃən(ə)l]: adj. something that is functional is working correctly SYN operational正常工作的
- I don't think the washing machine need mending, it's still functional.
- The old lady is bargaining with the owner of the shop for a functional TV.
- In my youth, I desired for a functional TV which my cousin possessed.
barrier [ˈberiər]: n. a physical object that keeps two areas, people etc apart屏障
- He decided to do away with himself in the barrier of loneliness.
- If the barrier broke down, the Asiatic nomads would sack our city in no time.
- Our barrier was being attcked by a band of wolves.
palpable [ˈpælpəb(ə)l]: adj. a feeling that is palpable is so strong that other people notice it and can feel it around them OPP impalpable明显的
- When the manager entered and interrupted the meeting, everyone around the table had a palpable sense of stress.
- His palpable sense of honor won him a large circle of close friends.
- It's a palpable lie that you are so stupid to believe it.
desperate [ˈdesp(ə)rət]: adj. willing to do anything to change a very bad situation, and not caring about danger令人绝望的
- With harvest decreasing, peasants in this castle grew more and more desperate. 
- The desperate peasants used a cow shit to hit the face of the vicious king.
- He realized to his horror that the workers trapped in the mine grew desperate.
empathy [ˈempəθi] empathetic: n.adj. the ability to understand other people’s feelings and problems ⇨ sympathy同情心的,共情的
- Our so-called vicious king proved to be empathetic in floods.
- It's evil that you took advantage of an empathetic gentleman.
- The empathetic lord asked the queen and her bastard to leave as soon as possible.
--------------------
open sth. up/ open up sth.: 打开某物
- You're not supposed to open up the present which our parent will give us tomorrow.
- Open it up, or I will beat you.
- It occurs to a worker to open the box up.
very first: 非常早的
- In very first episodes, the role has been sent to prison.
- In very first episodes, the father of the hero was sentenced to death because he deserted his regiment.
- In very first episodes, the heroine lost her husband and became mother of dragons.
come to the conclusion: 得出结论
- My wife came to the conclusion that she deserves to go on vacation on seaside resort.
- Your former superior must come to the conclusion that you are such an idiot.
- Sams came to the conclusion that his mate was not a bastard but a true heir to the iron throne.
be disconnected from sth./sb.: 与某人/某物断绝联系
- Disconnected from my mother, I suffered a great deal since she left me at the castle.
- Disconnected from his daughter, he asked a staff to boardcast his words.
- Disconnected from me, my father advised my cousins to seek me.
the core point of sth.: 某事物的核心要点
- The core point of program was to test, test, and test.
- The core point of agreement is to improve the working conditions and pays.
- The core point of treaty is let the former programmer take responsibility for the project.
** sentence2
reference [ˈref(ə)rəns]: v. to mention another book, article etc that contains information connected with the subject you are writing about涉及, 查阅, 参考
- You need to reference more treatises to complete yours.
- Referencing an old book in the library, Sam ensured that his name was not Jon Snow and he was not a bastard.
- Referencing an ancient sheet of paper, the vicar sentenced the heretic to death.
twilight [ˈtwaɪˌlaɪt]: n. the small amount of light in the sky as the day ends黄昏, 微光
- I used to walk alongside the river with my father at twilight.
- He ordered his men to fly over the South Pole at twilight.
- What I met at the twilight will stay in my mind.
episode [ˈepɪˌsoʊd]: n. a television or radio programme that is one of a series of programmes in which the story is continued each week ⇨ series集
- The bottom line I can't afford to so expensive episodes because of economic crises.
- The spokesman for this company claimed to have spent more than 1 million dollars each episode.
- Have you ever watched episode 8, my precious?
extended [ɪkˈstendəd]: adj. made longer or bigger长期的
- His father hasn't been standing for him for an extended period of time.
- He has been lacking friends for an extended period of time.
- Because of social upheaval the country was chaotic in politics for an extended period of time.
debut [deɪˈbju]: v. to appear in public or become available for the first time初次登场, 开张
- A band of gangsters stole three thousand dollars worth of diamonds when the jewelry shop debuted.
- The sad truth is that the Panda which was founded in China will not debut in our country.
- As long as the panda debuts, people will cheer up.
insufferable [ɪnˈsʌfərəb(ə)l]: adj. extremely annoying or unpleasant SYN unbearable难以忍受的
- Remaining calm under the stress is hard, the emotion is insufferable to me.
- The unfair terms of the treaty are insufferable to me, I will not sign it up.
- His words alerted me to the insufferable terms of the treaty.
functional [ˈfʌŋkʃən(ə)l]: adj. something that is functional is working correctly SYN operational正常工作的
- I don't think the washing machine needs mending, it's still functional.
- The old lady is bargaining with the owner of the shop for a functional TV.
- In my youth, I desired a functional TV which my cousin possessed.
barrier [ˈberiər]: n. a physical object that keeps two areas, people etc apart屏障
- He decided to do away with himself in the barrier of loneliness.
- If the barrier broke down, the Asiatic nomads would sack our city in no time.
- Our barrier was being attacked by a band of wolves.
palpable [ˈpælpəb(ə)l]: adj. a feeling that is palpable is so strong that other people notice it and can feel it around them OPP impalpable明显的
- When the manager entered and interrupted the meeting, everyone around the table had a palpable sense of stress.
- His palpable sense of honor won him a large circle of close friends.
- It's a palpable lie that you are so stupid to believe it.
desperate [ˈdesp(ə)rət]: adj. willing to do anything to change a very bad situation, and not caring about danger令人绝望的
- With harvest decreasing, peasants in this castle grew more and more desperate. 
- The desperate peasants used cow shit to hit the face of the vicious king.
- He realized to his horror that the workers trapped in the mine grew desperate.
empathy [ˈempəθi] empathetic: n.adj. the ability to understand other people’s feelings and problems ⇨ sympathy同情心的,共情的
- Our so-called vicious king proved to be empathetic in floods.
- It's evil that you took advantage of an empathetic gentleman.
- The empathetic lord asked the queen and her bastard to leave as soon as possible.
--------------------
open sth. up/ open up sth.: 打开某物
- You're not supposed to open up the present which our parents will give us tomorrow.
- Open it up, or I will beat you.
- It occurs to a worker to open the box up.
very first: 非常早的
- In the very first episode, the role has been sent to prison.
- In the very first episode, the father of the hero is sentenced to death because he deserted his regiment.
- In the very first episodes, the heroine loses her husband and becomes the mother of dragons.
come to the conclusion: 得出结论
- My wife came to the conclusion that she deserves to go on vacation at a seaside resort.
- Your former superior must come to the conclusion that you are such an idiot.
- Sams came to the conclusion that his mate was not a bastard but a true heir to the Iron Throne.
be disconnected from sth./sb.: 与某人/某物断绝联系
- Disconnected from my mother, I suffered a great deal since she left me at the castle.
- Disconnected from his daughter, he asked staff to broadcast his words.
- Disconnected from me, my father advised my cousins to seek me.
the core point of sth.: 某事物的核心要点
- The core point of programming was to test, test, and test.
- The core point of the agreement is to improve the working conditions and pay.
- The core point of the treaty is to let the former programmer take responsibility for the project.
