#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 01 Welcome to the Meeting Debrief
#+begin_verse
Did you notice all the inappropriate things Cheri did?
I entered the room, another person's meeting, and interrupted their meeting.
I destroyed the meeting's ambiance or environment.
People were shocked.
Did you see their eyes?
I was accusatory.
I was demanding.
I voiced some of the beliefs I had about Jeffrey and teamwork.
What I said can never be erased.
I was haughty and self-indulgent.
I believe that I am better than other people.
I would venture to guess that you are appalled by my behavior.
I am embarrassed every time I watch that!
But Jeffrey also had some issues that I hope you noted.
He didn't stand up for himself.
Perhaps he was afraid.
Perhaps there is fear in this organization.
He and others may not have psychological safety in this company or department.
If that is the case,
	then performance will also be lacking or be at a far lower level than it could be.
And everyone around the table is uncomfortable.
They hear Jeffrey's words and feel bad, possibly for Jeffrey, possibly for themselves.
The meeting will never recover from this.
It would be best to cancel the agenda and meet another time.
The behavior of Cheri will always stay in the minds of everyone in that meeting.
Bottom line, it is bad on both sides, Bad Behavior, Bad Culture.
Lack of highly developed social emotional intelligence.
We can all do better. 
#+end_verse
** expression
debrief [dɪˈbrif]: v. to ask someone questions about a job they have just done or an experience they have just had, in order to gather information ⇨ brief询问
ambiance [ˈæmbiəns]: n. the qualities and character of a particular place and the way these make you feel SYN atmosphere周围环境, 气氛
accusatory [əˈkjuːzətɔːri]: adj. an accusatory remark or look from someone shows that they think you have done something wrong控诉的, 指责的
demanding [dɪˈmændɪŋ]: adj. expecting a lot of attention or expecting to have things exactly the way you want them, especially in a way that is not fair过分要求的, 苛求的
voice [vɔɪs]: v. to tell people your opinions or feelings about a particular subject表达, 吐露
teamwork [ˈtiːmwɜːrk]: n. when a group of people work effectively together合作
erase [ɪˈreɪs]: v. to get rid of something so that it has gone completely and no longer exists抹去, 擦掉, 消磁
haughty [ˈhɔti]: adj. behaving in a proud unfriendly way ⇨ stuck up傲慢的
indulgent [ɪnˈdʌldʒənt] indulge: adj.v. willing to allow someone, especially a child, to do or have whatever they want, even if this is not good for them纵容的
department [dɪˈpɑrtmənt] : n. one of the groups of people who work together in a particular part of a large organization such as a hospital, university, company, or government部门
agenda [əˈdʒendə]: n. a list of problems or subjects that a government, organization etc is planning to deal with日程
intelligent intelligence [ɪnˈtelɪdʒəns]: adj.n. the ability to learn, understand, and think about things智能
--------------------
venture to do sth.: 冒险做某事
stand up for sb.: 为某人辩护
stay in the minds of sb.: 留在某人脑海中
The bottom line + ...: 最重要的是, + ...
** sentence
debrief [dɪˈbrif]: v. to ask someone questions about a job they have just done or an experience they have just had, in order to gather information ⇨ brief询问
- The scientists who made a remarkable discovery were being debriefing.
- The girl who was debriefed was said to be the longest daughter of the lord.
- He is always full of energetic when he is debriefed.
ambiance [ˈæmbiəns]: n. the qualities and character of a particular place and the way these make you feel SYN atmosphere周围环境, 气氛
- A welcoming ambiance in my hometown did give me a surprise.
- The poor child noticed to his horror that there was a hazardous ambiance when he arrived home.
- A hazardous ambiance drove him to look everywhere for his cat.
accusatory [əˈkjuːzətɔːri]: adj. an accusatory remark or look from someone shows that they think you have done something wrong控诉的, 指责的
- People must have been accusatory when you interrupted another person's meeting.
- Why don't you be accusatory?
- Your mother is being accusatory, you must have done something forbidden.
demanding [dɪˈmændɪŋ]: adj. expecting a lot of attention or expecting to have things exactly the way you want them, especially in a way that is not fair过分要求的, 苛求的
- The demanding accountant is playing naked dance with her tits out.
- In sum, my former superior is by no means demanding.
- He condemned his superior as a demanding old witch.
voice [vɔɪs]: v. to tell people your opinions or feelings about a particular subject表达, 吐露
- The abbot voiced his concern about the monastery's worsening debt.
- Although my father has never voiced his concern for me, his kindness stayed in my minds.
- The witch voices her compliaint about the lord who burned her house down.
teamwork [ˈtiːmwɜːrk]: n. when a group of people work effectively together合作
- There is no teamwork in such a terrible ambiance.
- We need more teamwork to achieve our democratic goals.
- When he received kindness from his mate, he thought it to be teamwork.
erase [ɪˈreɪs]: v. to get rid of something so that it has gone completely and no longer exists抹去, 擦掉, 消磁
- The queen's memory of naked shame parade will never be erased.
- Your memory should have been erased, he said in a weak voice.
- When he double-checked his answers, he quickly erased the wrong answers.
haughty [ˈhɔti]: adj. behaving in a proud unfriendly way ⇨ stuck up傲慢的
- In my childhood, I was spoiled by my grandfather and a little haughty.
- The haughty queen was punished to be paraded through the street.
- The huaghty knight who didn't obey the rule was sentenced to death by the lord.
indulgent [ɪnˈdʌldʒənt] indulge: adj.v. willing to allow someone, especially a child, to do or have whatever they want, even if this is not good for them纵容的
- If you kept indulging your son in your territory, he might meet his death in the continent.
- The indulgent girl dared to play truant from school.
- The indulgent prince met his death at the hands of the lord Stark.
department [dɪˈpɑrtmənt] : n. one of the groups of people who work together in a particular part of a large organization such as a hospital, university, company, or government部门
- Because of unemployment, our department may cease to exist.
- The department is blessed with a friendly ambiance.
- The department blessed with a friendly ambiance proved more collective intelligent.
agenda [əˈdʒendə]: n. a list of problems or subjects that a government, organization etc is planning to deal with日程
- A vacation in Sanya is not on my agenda.
- Beyond doubts, there are a lot of vocation on seaside resorts on her agenda.
- The meething should be erased on our department's agenda.
intelligent intelligence [ɪnˈtelɪdʒəns]: adj.n. the ability to learn, understand, and think about things智能
- The lord offered to provide him with an intelligent robot.
- The robot proved intelligent, for it finished a lot house chores which it was not expected to do.
- The cooker is intelligent, which can be linked to your application on your phone.
--------------------
venture to do sth.: 冒险做某事
- He ventured to make a diary in the memory of his murder.
- The crime ventured to publish a fiction about his murder. 
- My wife ventured to gamble with all of our wealth.
stand up for sb.: 为某人辩护
- The primary student says, if you didn't stand up for us, you would be punished in our case in the future.
- The usurper lost no time in standing up for his wife.
- The woman who stood up for you is being abused in the prison.
stay in the minds of sb.: 留在某人脑海中
- Your kindness will always stay in the minds of us.
- The natives gave him a state funeral and his honor would stay in the minds of them.
- Son, I am pround of you, your honor will stay in the mind of our people.
Bottom line, + ...: 最重要的是, + ...
- Bottom line, the usurper has already lost his heart in the battle.
- Bottom line, these haught knights tend to defect to our side.
- Bottom line, your wife is starving to death because of the punishment.
** sentence2
debrief [dɪˈbrif]: v. to ask someone questions about a job they have just done or an experience they have just had, in order to gather information ⇨ brief询问
- The scientists who made a remarkable discovery were being debriefed.
- The girl who was debriefed was said to be the longest daughter of the lord.
- He is always full of energetic when he is debriefed.
ambiance [ˈæmbiəns]: n. the qualities and character of a particular place and the way these make you feel SYN atmosphere周围环境, 气氛
- A welcoming ambiance in my hometown did surprise me.
- The poor child noticed to his horror that there was a hazardous ambiance when he arrived home.
- A hazardous ambiance drove him to look everywhere for his cat.
accusatory [əˈkjuːzətɔːri]: adj. an accusatory remark or look from someone shows that they think you have done something wrong控诉的, 指责的
- People must have been accusatory when you interrupted another person's meeting.
- Why don't you be accusatory?
- Your mother is being accusatory, you must have done something forbidden.
demanding [dɪˈmændɪŋ]: adj. expecting a lot of attention or expecting to have things exactly the way you want them, especially in a way that is not fair过分要求的, 苛求的
- The demanding accountant is playing naked dance with her tits out.
- In sum, my former superior is by no means demanding.
- He condemned his superior as a demanding old witch.
voice [vɔɪs]: v. to tell people your opinions or feelings about a particular subject表达, 吐露
- The abbot voiced his concern about the monastery's worsening debt.
- Although my father has never voiced his concern for me, his kindness stayed in the minds of me.
- The witch voices her complaint about the lord who burned her house down.
teamwork [ˈtiːmwɜːrk]: n. when a group of people work effectively together合作
- There is no teamwork in such a terrible ambiance.
- We need more teamwork to achieve our democratic goals.
- When he received kindness from his mate, he thought it to be teamwork.
erase [ɪˈreɪs]: v. to get rid of something so that it has gone completely and no longer exists抹去, 擦掉, 消磁
- The queen's memory of the naked shame parade will never be erased.
- Your memory should have been erased, he said in a weak voice.
- When he double-checked his answers, he quickly erased the wrong answers.
haughty [ˈhɔti]: adj. behaving in a proud unfriendly way ⇨ stuck up傲慢的
- In my childhood, I was spoiled by my grandfather and a little haughty.
- The haughty queen was punished to be paraded through the street.
- The haughty knight who didn't obey the rule was sentenced to death by the lord.
indulgent [ɪnˈdʌldʒənt] indulge: adj.v. willing to allow someone, especially a child, to do or have whatever they want, even if this is not good for them纵容的
- If you kept indulging your son in your territory, he might meet his death in the continent.
- The indulgent girl dared to play truant from school.
- The indulgent prince met his death at the hands of the lord Stark.
department [dɪˈpɑrtmənt] : n. one of the groups of people who work together in a particular part of a large organization such as a hospital, university, company, or government部门
- Because of unemployment, our department may cease to exist.
- The department is blessed with a friendly ambiance.
- The department blessed with a friendly ambiance proved more collectively intelligent.
agenda [əˈdʒendə]: n. a list of problems or subjects that a government, organization etc is planning to deal with日程
- A vacation in Sanya is not on my agenda.
- Beyond doubt, there are a lot of vocations on seaside resorts on her agenda.
- The meeting should be erased from our department's agenda.
intelligent intelligence [ɪnˈtelɪdʒəns]: adj.n. the ability to learn, understand, and think about things智能
- The lord offered to provide him with an intelligent robot.
- The robot proved intelligent, for it finished a lot house chores which it was not expected to do.
- The cooker is intelligent and can be linked to your application on your phone.
--------------------
venture to do sth.: 冒险做某事
- He ventured to make a diary in the memory of his murder.
- The crime ventured to publish a fiction about his murder. 
- My wife ventured to gamble with all of our wealth.
stand up for sb.: 为某人辩护
- The primary student says, if you didn't stand up for us, you would be punished in our case in the future.
- The usurper lost no time in standing up for his wife.
- The woman who stood up for you is being abused in the prison.
stay in the minds of sb.: 留在某人脑海中
- Your kindness will always stay in the minds of us.
- The natives gave him a state funeral and his honor would stay in the minds of them.
- Son, I am proud of you, your honor will stay in the minds of our people.
The bottom line + ...: 最重要的是...
- The bottom line the usurper has already lost his heart in the battle.
- The bottom line these haughty knights tend to defect to our side.
- The bottom line your wife is starving to death because of the punishment.
** summary
Because I entered and interrupted another person's meeting, the meeting's ambiance was destoryed.
I continued to voice some beliefs about Jeffrey and teamwork,
	believing that I am better than other people.
Everyone in the meeting was appalled by my behavior than would stay in the minds of them.
Yet Jeffrey didn't stand up for himself.
Maybe he was afraid or there is fair in this organization.
The meeting has been spoiled and it'd be best to cancel it.
It's lack of highly developed social emotional intelligence.
** summary2
Because I entered and interrupted another person's meeting, the meeting's ambiance was destroyed.
I continued to voice some beliefs about Jeffrey and teamwork,
	believing that I am better than other people.
Everyone in the meeting was appalled by my behavior which would stay in their minds.
Yet Jeffrey didn't stand up for himself.
Maybe he was afraid or there is fear in this organization.
The meeting has been spoiled and it'd be best to cancel it.
It's lack of highly developed social-emotional intelligence.
