#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 28 No Parking

#+begin_verse
What is Jasper White's problem?

Jasper White is one of those rare people
	who believes in ancient myths.
He has just bought a new house in the city,
	but ever since he moved in,
	he has *had trouble with cars* and their owners.
When he returns home at night,
	he always finds that someone has parked a car outside his gate.
Because of this, he has not been able to get his own car into his garage even once.
Jasper has put up 'No Parking' signs outside his gate,
	but these have not *had any effect*.
Now he has put an ugly stone head over the gate.
It is one of the ugliest faces I have ever seen.
I asked him what it was
	and he told me that it was Medusa, the Gorgon.
Jasper hopes that she will turn cars and their owners to stone.
But none of them has been turned to stone yet!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
