#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 30 Football or polo?
#+begin_verse
What happened to the man in the boat?

The Wayle is a small river that cuts across the park near my home.
I like sitting by the Wayle on fine afternoons.
It was warm last Sunday, so I went and sat on the river bank as usual.
Some children were playing games on the bank and there were some people rowing on the river.
Suddenly, one of the children kicked a ball very hard and it went towards a passing boat.
Some people on the bank *called out to the man* in the boat, but he did not hear them.
The ball struck him so hard that he nearly fell into the water.
I turned to look at the children, but there weren't any in sight: they had all run away!
The man laughed when he realized what had happened.
He called out to the children and threw the ball back to the bank.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
