#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 39 Am I all right?

#+begin_verse
Why did Mr. Gilbert telephone Dr. Millington?

While John Gilbert was in hospital,
	he asked his doctor to tell him whether his operation had been successful,
	but the doctor *refused to do so*.
The following day, the patient *asked for a bedside telephone*.
When he was alone, he telephoned the hospital exchange and asked for Doctor Millington.
When the doctor answered the phone,
	Mr. Gilbert said he was *inquiring about a certain patient*, a Mr. John Gilbert.
He asked if Mr. Gilbert's operation had been successful and the doctor told him that it had been.
He then asked when Mr. Gilbert would *be allowed to go* home
	and the doctor told him that he would have to stay in hospital for another two weeks.
Then Dr. Millington asked the caller if he was a relative of the patient.
'No,' the patient answered. 
'I am Mr. John Gilbert.'
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
