#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 40 Food and talk
#+begin_verse
Was Mrs. Rumbold a good companion at dinner?

Last week at a dinner party, the hostess asked me to sit next to Mrs. Rumbold.
Mrs. Rumbold was a large, unsmiling lady in a tight black dress.
She did not even look up when I *took my seat* beside her.
Her eyes were fixed on her plate and in a short time, she *was busy eating*.
I tried to make conversation.
'A new play is coming to "The Globe" soon,' I said. "*Will you be seeing* it?"
'No,' she answered.
'Will you be spending your holidays abroad this year?' I asked.
'No,' she answered.
'Will you be staying in England?' I asked.
'No,' she answered.
*In despair*, I asked her whether she was enjoying her dinner.
'Young man,' she answered, 'if you ate more and talked less, we would both enjoy our dinner!'
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
