#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 25 Do the English speak English?
#+begin_verse
Why does the writer not understand the porter?

I arrived in London at last.
The railway station was big, black and dark.
I did *not know the way to my hotel*,
	so I asked a porter.
I not only spoke English very carefully, but very clearly as well.
The porter, however, could not understand me.
I repeated my question several times
	and at last he understood.
He answered me,
	but he spoke neither slowly nor clearly.
'I am a foreigner,' I said.
Then he spoke slowly,
	but I could not understand him.
My teacher never spoke English like that!
The porter and I looked at each other and smiled.
Then he said somethings and I understood it.
'You'll soon learn English!' he said.
I wonder, in England, each person speaks a different language.
The English understand each other,
	but I don't understand them!
Do they speak English?
#+end_verse

* Lesson 26 The best art critics
#+begin_verse
Who is the student's best critic?

I am an art student
	and I paint a lot of pictures.
*Many people pretend that* they understand modern art.
They always tell you what a picture is 'about'.
Of course, many pictures are not 'about' anything.
They are just pretty patterns.
We like them in the same way
	that we like pretty curtain material.
I think that young children often appreciate modern pictures better than anyone else.
They notice more.
My sister is only seven,
	but she always tells me whether my pictures are good or not.
She came into my room yesterday.
'What are you doing?' she asked.
'I'm hanging this picture on the wall,' I answered.
'It's a new one. Do you like it?'
She looked at it critically for a moment.
'It's all right,' she said, 'but isn't it upside down?'
I looked at it again.
She was right! It was!
#+end_verse

* Lesson 27 A wet night
#+begin_verse
What happened to the boys in the night?

Late in the afternoon, the boys *put up their tent* in the middle of a field.
As soon as this was done,
	they cooked a meal over an open fire.
They were all hungry
	and the food smelled good.
After a wonderful meal, they *told stories* and sang songs by the campfire.
But some time later it began to rain.
The boys felt tired
	so they *put out the fire* and crept into their tent.
Their sleeping bags were warm and comfortable,
	so they all slept soundly.
In the middle of the night, two boys *woke up* and began shouting.
The tent was full of water!
They all leapt out of their sleeping bags and hurried outside.
It was raining heavily
	and they found that a stream had formed in the field.
The stream wound its way across the field
	and then flowed right under their tent.
#+end_verse
* Lesson 28 No Parking

#+begin_verse
What is Jasper White's problem?

Jasper White is one of those rare people
	who believes in ancient myths.
He has just bought a new house in the city,
	but ever since he moved in,
	he has *had trouble with cars* and their owners.
When he returns home at night,
	he always finds that someone has parked a car outside his gate.
Because of this, he has not been able to get his own car into his garage even once.
Jasper has put up 'No Parking' signs outside his gate,
	but these have not *had any effect*.
Now he has put an ugly stone head over the gate.
It is one of the ugliest faces I have ever seen.
I asked him what it was
	and he told me that it was Medusa, the Gorgon.
Jasper hopes that she will turn cars and their owners to stone.
But none of them has been turned to stone yet!
#+end_verse
* Lesson 29 Taxi!

#+begin_verse
Does Captain Fawcett think any trip is too dangerous?

Captain Ben Fawcett has bought an unusual taxi and has begun a new service.
The taxi is a small Swiss aeroplane called a 'Pilatus Porter'.
This wonderful plane can carry seven passengers.
The most surprising thing about it, however, is that it can land anywhere;
	on snow, water, or even on a ploughed field.
Captain Fawcett's first passengers was a doctor
	who flew from Birmingham to a lonely village in the Welsh mountains.
Since then, Captain Fawcett has flown passengers to many unusual places.
Once he landed on the roof of a block of flats and on another occasion,
	he landed in a deserted car park.
Captain Fawcett has just refused a strange request from a businessman.
The man wanted to fly to Rockall, a lonely island in the Atlantic Ocean,
	but Captain Fawcett did not take him
		because the trip was too dangerous.
#+end_verse
* Lesson 30 Football or polo?
#+begin_verse
What happened to the man in the boat?

The Wayle is a small river that cuts across the park near my home.
I like sitting by the Wayle on fine afternoons.
It was warm last Sunday, so I went and sat on the river bank as usual.
Some children were playing games on the bank and there were some people rowing on the river.
Suddenly, one of the children kicked a ball very hard and it went towards a passing boat.
Some people on the bank *called out to the man* in the boat, but he did not hear them.
The ball struck him so hard that he nearly fell into the water.
I turned to look at the children, but there weren't any in sight: they had all run away!
The man laughed when he realized what had happened.
He called out to the children and threw the ball back to the bank.
#+end_verse
* Lesson 31 Success story
#+begin_verse
What was Frank's first job?

Yesterday afternoon Frank Hawkins was telling me about his experience as a young man.
Before he retired,
	Frank was the head of a very large business company,
  but as a boy he used to work in a small shop.
*It was his job to repair bicycles*
	and at that time he used to work fourteen hours a day.
He saved money for years
	and in 1958 he bought a small workshop of his own.
*In his twenties* Frank used to make spare parts for aeroplanes.
At that time he had two helpers.
In a few years the small workshop had become a large factory
  which employed seven hundred and twenty-eight people.
Frank smiled when he remembered his hard early years and the long road to success.
He was still smiling
	when the door opened and his wife came in.
She wanted him to repair their grandson's bicycle.
#+end_verse
* Lesson 32 Shopping made easy

#+begin_verse
Who was the thief?

People are not so honest as they once were.
The temptation to steal is greater than ever before -- especially in large shops.
A detective recently watched a well-dressed woman
	who always went into a large store on Monday mornings.
One Monday, there were fewer people in the shop than usual when the woman came in,
  so *it was easier for the detective to watch her*.
The woman first bought a few small articles.
After a little time, she chose one of the most expensive dresses in the shop
  and *handed it to an assistant* who *wrapped it up* for her as quickly as possible.

Then the woman simply took the parcel and walked out of the shop without paying.
When she was arrested,
	the detective found out that the shop assistant was her daughter.
The girl gave her mother a free dress once a week.
#+end_verse
* Lesson 33 Out of the darkness
#+begin_verse
Why was the girl in the hospital?

Nearly a week passed before the girl was able to explain what had happened to her.
One afternoon she set out from the coast in a small boat and was caught in a storm.
Towards evening, the boat struck a rock and the girl jumped into the sea.
Then she swam to the shore after spending the whole night in the water.
Early next morning, she saw a light ahead.
She knew she was near the shore because the light *was high up* on the cliffs.
*On arriving* at the shore, the girl *struggled up* the cliff towards the light she had seen.
That was all she remembered.
When she woke up a day later, she found herself in hospital.
#+end_verse
* Lesson 34 Quick work

#+begin_verse
How long had the police taken to find his bicycle?

Dan Robinson has been worried all week.
Last Tuesday he received a letter from the local police.
In the letter he was asked to *call at* the station.
Dan wondered why he was wanted by the police,
	but he went to the station yesterday and now he is not worried anymore.
At the station, he was told by a smiling policeman that his bicycle has been found.
Five days ago, the policeman told him,
	the bicycle was picked up in a small village four hundred miles away.
It is now being sent to his home by train.
Dan was most surprised when he heard the news.
He was amused too, because he never *expected the bicycle to be found*.
It was stolen twenty years ago when Dan was a boy of fifteen!
#+end_verse
* Lesson 35 Stop thief!
#+begin_verse
How did Roy stop the thieves?

Roy Trenton used to drive a taxi.
*A short while ago*, however, he became a bus driver and he has not *regretted it*.
He is finding his new work far more exciting.
When he was driving along Catford Street recently,
	he saw two thieves *rush out of* a shop and run towards a waiting car.
One of them was carrying a bag full of money.
Roy acted quickly and drove the bus straight at the thieves.
The one with money *got such a fright* that he dropped the bag.
As the thieves were trying to get away in their car, Roy drove his bus into the back of it.
While the battered car was moving away, Roy stopped his bus and telephoned the police.
The thieves' car was badly damaged and easy to recognized.
*Shortly afterwards*, the police stopped the car and both men were arrested.
#+end_verse
* Lesson 36 Across the Channel

#+begin_verse
What is Debbie going to try to do?

Debbie Hart is going to swim across the English Channel tomorrow.
She is going to set out from the French coast at five o'clock in the morning.
Debbie is only eleven years old and she *hopes to set up a new world record*.
She is a strong swimmer and many people feel that she *is sure to succeed*.
Debbie's father will set out with her in a small boat.
Mr. Hart has trained his daughter for years.
Tomorrow he will be watching her anxiously as she swims the long distance to England.
Debbie *intends to take short rests* every two hours.
She will have something to drink but she will not eat any solid food.
Most of Debbie's school friends will be waiting for her on the English coast.
Among them will be Debbie's mother, who swam the Channel herself when she was a girl.
#+end_verse
* Lesson 37 The Olympic Games
#+begin_verse
When was the last time this country hosted the Olympic Games?

*The Olympic Games will be held* in our country in four years' time.
As a great many people will be visiting the country,
	the government will be building new hotels, an immense stadium,
		and a new Olympic-standard swimming pool.
They will also be building new roads and a special railway line.
The Games will be held just outside the captial and the whole area will be called 'Olympic City'.
Workers will have completed the new roads by the end of this year.
By the end of next year, they will have finished work on the new stadium.
The fantastic modern buildings have been designed by Kurt Gunter.
Everybody will be watching anxiously as the new buildings go on.
We are all very excited and are *looking forward to the Olympic Games*
	because they have never held before in the country.
#+end_verse
* Lesson 38 Everything except the weather
#+begin_verse
Why did Harrison sell his house so quickly?

My old friend, Harrison,
	had lived in the Mediterranean for many years before he returned to England.
He had often *dreamed of retiring* in England and had *planned to settle down* in the country.
He had no sooner returned than he bought a house and went to live there.
Almost immediately he began to *complain about the weather*,
	for even though it was still summer, it rained continually and it was often *bitterly cold*.
After so many years of sunshine, Harrison got a shock.
He acted as if he had never lived in England before.
In the end, it was more than he could bear.
He had hardly had time to settle down when he sold the house and left the country.
The dream he had had for so many years ended there.
Harrison had thought of everything except the weather.
#+end_verse
* Lesson 39 Am I all right?

#+begin_verse
Why did Mr. Gilbert telephone Dr. Millington?

While John Gilbert was in hospital,
	he asked his doctor to tell him whether his operation had been successful,
	but the doctor *refused to do so*.
The following day, the patient *asked for a bedside telephone*.
When he was alone, he telephoned the hospital exchange and asked for Doctor Millington.
When the doctor answered the phone,
	Mr. Gilbert said he was *inquiring about a certain patient*, a Mr. John Gilbert.
He asked if Mr. Gilbert's operation had been successful and the doctor told him that it had been.
He then asked when Mr. Gilbert would *be allowed to go* home
	and the doctor told him that he would have to stay in hospital for another two weeks.
Then Dr. Millington asked the caller if he was a relative of the patient.
'No,' the patient answered. 
'I am Mr. John Gilbert.'
#+end_verse
* Lesson 40 Food and talk
#+begin_verse
Was Mrs. Rumbold a good companion at dinner?

Last week at a dinner party, the hostess asked me to sit next to Mrs. Rumbold.
Mrs. Rumbold was a large, unsmiling lady in a tight black dress.
She did not even look up when I *took my seat* beside her.
Her eyes were fixed on her plate and in a short time, she *was busy eating*.
I tried to make conversation.
'A new play is coming to "The Globe" soon,' I said. "*Will you be seeing* it?"
'No,' she answered.
'Will you be spending your holidays abroad this year?' I asked.
'No,' she answered.
'Will you be staying in England?' I asked.
'No,' she answered.
*In despair*, I asked her whether she was enjoying her dinner.
'Young man,' she answered, 'if you ate more and talked less, we would both enjoy our dinner!'
#+end_verse
* Lesson 41 Do you call that a hat?

#+begin_verse
What kind of shopping does the writer enjoy, do you think?

'Do you call that a hat?' I said to my wife.
'You needn't be so rude about it,' my wife answered as she looked at herself in the mirror.
I sat down on one of those modern chairs with holes in it and waited.
We had been in the hat shop for half an hour and my wife was still in front of the mirror.
'We mustn't buy things we don't need,' I remarked suddenly.
I *regretted saying* it almost at once.
'You needn't have said that,' my wife answered.
'I needn't *remind you of that terrible tie* you bought yesterday.'
'I *find it beautiful*,' I said. 'A man can never have too many ties.'
'And a woman can't have too many hats,' she answered.
Ten minutes later we walked out of the shop together.
My wife was wearing a hat that looked like a lighthouse.
#+end_verse
* Lesson 42 Not very musical

#+begin_verse
What happened when the snake charmer began to play jazz?

As we had *had a long walk* through one of the markets of Old Delhi,
	we stopped at a square to have a rest.
After a time, we noticed a snake charmer with two large baskets *at the other side of* the square,
	so we went to have a look at him.
As soon as he saw us,
	he picked up a long pipe which was covered with coins and opened one of the baskets.
When he began to *play a tune*,
	we *had our first glimpse of the snake*.
It rose out of the basket and began to follow the movements of the pipe.
We were very much surprised when the snake charmer suddenly began to play jazz and modern pop songs.
The snake, however, *continued to 'dance'* slowly.
It obviously could not *tell the difference between Indian music and jazz*!
#+end_verse
* Lesson 43 Over the South Pole
#+begin_verse
How was the plane able to clear the mountains?

In 1929, three years after his flight over the North Pole,
	the American explorer, R.E. Byrd, successfully flew over the South Pole for the first time.
Though, at first,
	Byrd and his men were able to take a great many photographs of the mountains that lay below,
	they soon *ran into serious trouble*.
*At one point*, *it seemed certain that* their plane would crash.
It could only get over the mountains if it rose to 10,000 feet.
Byrd at once *ordered his men to throw* out two heavy food sacks.
The plane was then able to rise and it cleared the mountains by 400 feet.
Byrd now knew that he would be able to reach the South Pole which was 300 miles away,
	for there were no more mountains in sight.
The aircraft was able to fly over the endless white plains without difficulty.
#+end_verse
* Lesson 44 Through the forest
#+begin_verse
How did Mrs. Sterling get her bag back?

Mrs. Anne Sterling did not think of the risk she was taking
	when she ran through a forest after two men.
They had *rushed up to her*
	while she was *having a picnic* *at the edge of a forest* with her children
		and tried to steal her handbag.
In the struggle, the strap broke and, with the bag *in their possession*,
	both men started running through the trees.
Mrs. Sterling got so angry that she ran after them.
She was soon *out of breath*, but she continued to run.
When she *caught up with them*,
	she saw that they had sat down and were going through the contents of the bag,
	so she *ran straight at them*.
The men got such a fright that they dropped the bag and ran away.
"The strap needs mending," said Mrs. Sterling later, 'but they did not steal anything."
#+end_verse
* Lesson 45 A clear conscience
#+begin_verse
How did Sam get his money back?

*The whole village soon learnt that* a large sum of money had been lost.
Sam Benton, the local butcher, had lost his wallet while taking his savings to the post office.
Sam was sure that the wallet must have been found by one of the villagers,
	but it was not *returned to him*.
Three months passed, and then one morning, Sam found his wallet outside his front door.
It had been wrapped up in newspaper
	and it contained half the money he had lost,
		together with a note which said: 'A thief, yes, but only 50 percent a thief!'
Two months later, some more money was sent to Sam with another note:
	'Only 25 percent a thief now!'
In time, all Sam's money was paid back in this way.
The last note said: 'I am 100 percent honest now!'
#+end_verse
* Lesson 46 Expensive and uncomfortable

#+begin_verse
What did the man in this story do?

When a plane from London arrived at Sydney airport,
	workers began to unload a number of wooden boxes which contained clothing.
*No one could account for the fact that* one of the boxes was extremely heavy.
*It suddenly occurred to one of the workers to open* up the box.
He *was astonished at what* he found.
A man was lying in the box on top of a pile of woollen goods.
He was so surprised at being discovered that he did not even try to run away.
After he was arrested,
	the man *admitted hiding* in the box before the plane left London.
He had had a long and uncomfortable trip,
	for he had been confined to the wooden box for over eighteen hours.
The man was ordered to pay 3500 dollars for the cost of the trip.
The normal price of a ticket is 2000 dollars!
#+end_verse
* Lesson 47 A thirsty ghost
#+begin_verse
What evidence is there of a ghost?

A public house which was recently bought by Mr. Ian Thompson *is up for sale*.
Mr. Thompson is going to sell it because it is haunted.
He told me that he could not go to sleep one night
	because he *heard a strange noise coming* from the bar.
The next morning, he found that
	the doors had been blocked by chairs and the furniture had been moved.
Though Mr. Thompson had turned the lights off before he went to bed,
	they were on in the morning.
He also said that he had found five empty whisky bottles
	which the ghost must have drunk the night before.
When I suggested that some villagers must have come in for a free drink,
	Mr. Thompson shook his head.
The villagers have told him that they will not accept the pub even if he gives it away.
#+end_verse
* Lesson 48 Did you want to tell me something
#+begin_verse
Why did the writer become very worried?

Dentists always ask questions when *it is impossible for you to answer*.
My dentist had just pulled out one of my teeth and had told me to *rest for a while*.
I tried to say something, but my mouth was full of cotton wool.
He knew I collected match boxes and asked me whether my collection was growing.
He then asked me how my brother was and whether I liked my new job in London.
In answer to these questions I either nodded or made strange noises.
Meanwhile, my tongue was busy searching out the hole where the tooth had been.
I suddenly felt very worried, but could not say anything.
When the dentist at last removed the cotton wool from my mouth,
	I was able to tell him that he had pulled out the wrong tooth.
#+end_verse
