#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 1-2 1 Stress
#+begin_verse
Stress, stress, stress.
We seem to read about stress everywhere, and more and more,
	it's seen as a factor in our health, affecting body, mind, and brain.
So in this talk, we're going to spend a little time on stress,
	its positive and more difficult sides, and what to do to tame it.
This will dovetail with a lot of the other talks on our MOOC
	because stress is one of the newer kids on the block,
		and we need to know a lot about it to promote our well-being and flourishing.
		
The whole idea comes out of notions from last century,
	that human beings, like other animals,
		like to operate within a comfortable zone a lot of the time.
Nowadays, we call that our window of tolerance.
We don't mind getting towards the edge of the zone for a little while.
For example, we can enjoy getting excited, a little anxious, a little angry, or a little scared,
	if it's in a good and safe enough cause.
Most people might enjoy something like getting excited about the outcome of the footy match,
		that's what Australian's call football, or in a ball game,
	and getting terrified in a safe way, by the ride on, say, a roller coaster.
However, part of our eagerness to do these things
	is we know that they're mostly safe for the majority.
And the feelings and body sensations will settle safely,
	and we will feel back to normal
		some time not too long after the game, or the big day out at the amusement park.
		
When we get out of our comfort zone,
	the stress begins to dramatically rise, and then we find situations distressing.
We can notice changes in our body
		like pulse rate rising uncomfortably, blood pressure escalating,
	or we feel distressing levels of emotion.
At even more extreme levels,
	we can begin to feel frozen or trapped, or even disconnect or dissociate.
Then, we need to use ways to calm back down and feel more comfortable.
Most of us do this best
	by using soothing from others and ways we've learnt through life to calm down.
	
After particularly stressful events or periods,
	we may even need a solid period of rest and recovery.
We don't always make time for that in our busy modern lives.
Positive psychiatry talks about using ways to settle that promote our well-being and don't hurt us.
So, using our connecting conversations with others,
	good exercise, that mindfulness, meditation, breathing to calm down,
		rather than drugs or alcohol, just as an example.
When we can't manage the high stress,
	it can begin to do damage to our well-being and become traumatic,
		meaning that our normal coping is overwhelmed.
The good news is that even here we can often recover,
	and often become more resilient in the process.
At other times, cumulative or overwhelming stress is traumatic.
And then we need strong pathways to recovery, and what's called post-traumatic growth.
That's where we grow as a result of difficult circumstances.

Just to be clear, stress is not just all in the mind.
Our bodies really feel it.
And too much stress can contribute to many illnesses in times when mental health breaks down.
Stress triggers inflammation for example,
	and cumulative stress can literally become disorganizing for our mental and physical life.
So, learning to manage it becomes a keystone of our well being and health.

Stress regulation and stress management
	are essential part of positive psychology and positive psychiatry.
Today, we think of it as a hierarchy of stress management at the top of those strategies
	that really help us connect to ourselves and others.
And help our brains, bodies, minds reconnect, and be restored and nourished after stress.
Stephen Porges, a psychiatrist in the US,
	has been describing that we have a social nervous system,
		evolved to manage stress best via our social connections.
So at the top of the hierarchy for managing stress are the ways
	we connect and calm and soothe each other in relationships and connective conversations.
Our facial expression, and our capacities to speak and use body language,
	have actually developed in evolution to help this process.
For example, we really value and feel better
	when somebody shows, by expression and gesture, that they get us and what we're talking about.
We begin to calm down.
We feel really good after a shared laugh or occasionally a shared cry,
	and the sharing is the connecting
		that actually nourishes a part of our nervous system called the parasympathetic nervous system.
		
We hear a lot about the sympathetic nervous system, the so-called fight and flight system.
And people have known for a long time
	that the sympathetic nervous system connects with our immediate response to high stress,
		and we see it at work in the innovation of heart and blood vessels.
It makes our pulse rate and our blood pressure go up like the accelerated pedal of a car.
However, our rest and digest and restore system is the parasympathetic system.
It works in our gut and our digestive system.
It has connections like a brake to our heart.
It powers up all of those muscles of facial expression that we were just talking about.
So the social soothing comes from parasympathetic input.
Some of it's from fast-talking nerves covered in a substance called myelin.
And they connect upwards to the most important conscious thinking parts of our brain,
	and to many systems.
However, we also have parasympathetic input
	from an older nervous system with fibers that are unmyelinated.
They move slower but deeper, and are responsible for some of those deep feelings in our middle
	when we are stressed and distressed.
The terrible deep feeling of grief, for example.
When stress really overwhelms us, we can get in to that older parasympathetic state of withdrawal,
	when the older parasympathetic system is dominating.
In that state, we need to slow down, take it easy, and warm up.
Sometimes literally, sometimes emotionally.
Take time, get good care to recover.
After a period of more active symptoms of illness for example, whether mental or general medical,
	some people find they have a period of deep fatigue
		where they need to take things more slowly to restore energy
			and come back to their normal selves.
			
These days then, with a little science to back up the art of relaxation and stress relief,
	we encourage people to find the ways to calm down
		and to find stress and stress management strategies that work for them.
Meditation and mindfulness are powerfully effective,
	and they seem to offer a space to connect to ourselves,
		and literally help us to connect our body, brain, mind.
However, do take lots of social soothing.
Don't be afraid to get fit and busy, for example, with exercise,
	which uses the sympathetic system wisely.
But also watch when the older, deeper system, your gut,
	is telling you that you're very tired or overwhelmed,
		and need to slow down and really rest and restore in quiet ways.
Hopefully you're going to tune in to other talks
	which cover stress management through great strategies
		like relaxation, mindfulness, exercise, creativity, and play.
I love to use many of them.
Find what works for you and use them daily,
	and help your kids and those you care for to find their favorite ways.
So, as we learn to surf our stress, we get stronger.
Flexibility fosters resilience and highly connected minds and bodies, and our flourishing.
#+end_verse
** expression
flourish [ˈflɜrɪʃ]: v. to develop well and be successful SYN thrive兴旺
sensation [senˈseɪʃ(ə)n]: n. a feeling that you get from one of your five senses, especially the sense of touch感觉
pulse [pʌls]: n. the regular beat that can be felt, for example at your wrist, as your heart pumps blood around your body ⇨ heartbeat脉搏
escalate [ˈeskəˌleɪt]: v. if fighting, violence, or a bad situation escalates, or if someone escalates it, it becomes much worse不断升级
soothe [suð]: v. to make someone feel calmer and less anxious, upset, or angry抚慰,安慰
inflammation [ˌɪnfləˈmeɪʃ(ə)n]: n. swelling and pain in part of your body, which is often red and feels hot炎症, 发炎
keystone [ˈkiˌstoʊn]: n. ormal the most important part of an idea, belief, or process that influences how it develops基础,主旨
accelerate [əkˈseləˌreɪt]: v. if a process accelerates or if something accelerates it, it happens faster than usual or sooner than you expect加速, 促进
gut [ɡʌt]: n. all the organs in someone’s body, especially when they have come out of their body内脏
digestive [daɪˈdʒestɪv]: adj. connected with the process of digestion消化的
grief [ɡrif]: n. extreme sadness, especially because someone you love has died悲痛
fatigue [fəˈtiɡ]: n. very great tiredness SYN exhaustion疲乏
flexibility [ˌfleksəˈbɪləti]: n. the ability to change or be changed easily to suit a different situation灵活性
--------------------
dovetail with sth. [ˈdʌvˌteɪl]: 与某事物吻合
a kid on the block: 新手(街区的小孩)
Nowadays, + ...: 现今, + ...
mind doing sth.: 介意做某事
for a little while: 一小段时间
for the majority: 绝大多数
in times when + ...: 当...
power up sth.: 给某物通电
** sentence
flourish [ˈflɜrɪʃ]: v. to develop well and be successful SYN thrive兴旺
- The entrepreneur claimed that he kept chatting with his friends to flourish his busniess. 
- First of all, only after we deal with our traumas, do we tend to be flourishing.
- I am gonna make a call to my friend wishing her business flourish.
sensation [senˈseɪʃ(ə)n]: n. a feeling that you get from one of your five senses, especially the sense of touch感觉
- I have a sensation that he is all around us.
- There is another part to taking care of body sensation, without which we could achive our true nature.
- He must ignore her sensation with no way of riding her to hospital.
pulse [pʌls]: n. the regular beat that can be felt, for example at your wrist, as your heart pumps blood around your body ⇨ heartbeat脉搏
- There is a graphic interface showing the dynamic of your pulse rate.
- You can watch your pulse rate on the website of the utility company.
- His pulse rate raising dramatically lies in the stress he is being under.
escalate [ˈeskəˌleɪt]: v. if fighting, violence, or a bad situation escalates, or if someone escalates it, it becomes much worse不断升级
- Our relationship escalating was prior to our marriage.
- Due to your abortion and so-call my carelessness, our sentiment gets escalating in a linear fashion.
- With the conflict between the two countries escalating, people on the border had to move to other safer places.
soothe [suð]: v. to make someone feel calmer and less anxious, upset, or angry抚慰,安慰
- I had no idea that he had soothed you after we quarrelled.
- My wife is feeling my heart beating trying to soothe me from anger.
- He is an expert at soothing patients in the surgery team.
inflammation [ˌɪnfləˈmeɪʃ(ə)n]: n. swelling and pain in part of your body, which is often red and feels hot炎症, 发炎
- The inflammation points to an epidemic traced back to the Medival Ages.
- It is as if his inflammation is escalating beyond our expectation.
- Meaning that because of the inflammation you are not allowed to walk on your feet.
keystone [ˈkiˌstoʊn]: n. ormal the most important part of an idea, belief, or process that influences how it develops基础,主旨
- The next best thing is to figure out the keystone of the article.
- After you cut it open, you will find the robot's keystone is merely a chip.
- In reality, the keystone of the corporation is this kind of high-processed food that is popular with young people all over the world.
accelerate [əkˈseləˌreɪt]: v. if a process accelerates or if something accelerates it, it happens faster than usual or sooner than you expect加速, 促进
- Her husband accelerated dramatically, which made her wary of their safety down the road.
- The sex scandal ends up accelerating the destory of his company.
- That's when the driver accelerated it as the engine of the car broke down.
gut [ɡʌt]: n. all the organs in someone’s body, especially when they have come out of their body内脏
- What you need to get started is to examine your digestive gut in the hospital.
- The waiter gets a good salary enough for him to examine his gut in the hospital.
- I am willing to accompany with you, but my gut is protesting for my hunger.
digestive [daɪˈdʒestɪv]: adj. connected with the process of digestion消化的
- The patient diagnosed with digestive disorder has already been prescribed by your wife.
- Because of digestive disorder, he refused to go to school even though it didn't matter.
- The warrior trimmed the body to some digestive guts.
grief [ɡrif]: n. extreme sadness, especially because someone you love has died悲痛
- Because of the sensation of grief, she was unwilling to take part in her husband's funeral.
- He buried his son died of the bubonic plague with grief.
- With grief, everyone was reminiscing the headmaster who dedicated his life to the school.
fatigue [fəˈtiɡ]: n. very great tiredness SYN exhaustion疲乏
- I am always unwilling to take photographs for my wife with fatigue when we are on vacations.
- His deep feeling of fatigue rose from his controlling wife.
- With fatigue I insisted on finishing my homework.
flexibility [ˌfleksəˈbɪləti]: n. the ability to change or be changed easily to suit a different situation灵活性
- Our leader admires for his flexibility at the important meeting.
- The next thing he did showed us his flexibility under stressful conditions.
- Due to the flexbility of the cat, we failed to capture it in the enclosure.
--------------------
dovetail with sth. [ˈdʌvˌteɪl]: 与某事物吻合
- I must admit that your behavior at the wedding dovetails with your reputation.
- To my surprise, his kindness doesn't dovetail with what you described him.
- The trace of the cat dovetails with the feline habits.
a kid on the block: 新手(街区的小孩)
- As a kid on the block, I am not supposed to speak in public.
- When I was a kid on the block, the headmaster gave me the nuts to pursue my dream.
- Imagine your teacher's dismay when he found you couldn't cope with a kid on the block.
Nowadays, + ...: 现今, + ...
- Nowadays, girls often ask a large sum of money from their fiance in China.
- Nowadays, people don't have the nuts to take care of a person lying on the road. 
- Nowadays, many men in China spend less money even than a dog.
mind doing sth.: 介意做某事
- I don't mind reminiscing about your marriage.
- Minding giving pocket money, he didn't stay for dinner.
- My wife must have minded washing dinner on her own.
for a little while: 一小段时间
- Would you like babysit my daughter for a little while?
- Our cat has been drinking water for a little while since we moved to the new apartment.
- The water and electricity will be off for a little while.
for the majority: 绝大多数
- We tend to believe those sports are safety for the majority.
- My wife has done the house chores for the majority.
- The puma will not attack a human for the majority.
in times when + ...: 当...
- I was distressful in times when my mother passed away.
- Our cat was cheerful in times when I offered her snack.
- My wife felt satisfied in time when she learned that she had an opportunity to work for Apple.
power up sth.: 给某物通电
- Let's power up the TV, the programme may have already started.
- Powering up my Switch, let's enjoy new games our father presented to us.
- 
