#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-1 2 Creative selves
#+begin_verse
Mental well-being depends on an ongoing relationship of renewal with the environment.
As social beings, humans depend on communication and relationships with others for their well being.
The individual mind is dependent on communication through language,
	using symbols to understand and participate in the world.

From the beginning of life, humans have the ability to communicate.
Babies are able to cry to express other emotions, to take turns,
	and respond musically to the rhythm and pitch of conversation.
They do all of these things in relationship with parents or carers
	who engage with their baby in communication and play.
It's a process
	that allows the baby to use the environment through other people as a means of growth.
The human genome provides many potentials for each individual,
	but requires interaction with a good enough environment of responsive carers.
This way, the infant can develop the capacities
	that will allow him or her to become a fully participating member of the human community.
Compared with other species, human babies are highly dependent on adults.
They take many years to develop the skills to care for themselves.

Infants are not born with a sense of self.
This develops over time as part of our second nature.
It depends on early learning.
The sense of self arises through the experience of feeling during communication and exploration.
These aspects of mental life take time to become established.
A sense of self is a positive achievement reflecting a sense of value in the individual.
Positive and negative emotions need to be processed differently through early relationships.
These relationships soothe distress on the one hand,
	and amplify a sense of aliveness in the infant on the other.
This contributes to the sense of value in the infant,
	establishing a space for learning from others known as the Zone of Proximal Development.
	
At birth, we are thrown into the human world,
	a world where one has a place in a complex matrix of relationships
		that has great meaning for each individual.
Human beings, like all other species, operate within the physical world,
	but humans are unique in that we also operate in a symbolic sphere.
This is to say, that humans grow inside a world of language as well as the physical world.
They are able to participate emotionally and physically from the very beginning.

Feelings and emotions are a component of all human experience,
	acting as an in-built value system that allows the infants and adults
		to asses their experience, selecting interactions that promote aliveness and growth.
This can be described as using your gut feeling or instinct or intuition.
The types of feelings
		that arise for each person as they engage with others in the broader environment
	become characteristic for each individual.
Over the last few decades, research has reexamined the role of feeling in mental life.
A sense of aliveness is central to well-being and the development of mental life.
All living organisms seek to explore the environment
	in order to find what they need to survive and thrive.
This tendency has been called the seeking system.
And is part of an innate repertoire
	that for humans extends to the relational and symbolic aspects of life.
This underpins the yearning for connection,
	and the search for meaning that characterize human lives.
It also means that a large part of mental life, in health, is oriented towards the future.
A sense of meaning is not fixed or external to individuals
	but is created through communication, relationships, and building skills.
Reality is confirmed by the recognition and response of others in communicative exchange,
	that is, in a conversation.
This is one reason why people seek help for mental disturbances.
They have a need for re-grounding their position through a safe and validating relationship.
A sense of self can become disorganized through trauma, stress or illness.
And healing relationships are needed to restore the self.

For a long time, play was seen as a matter for children.
This view has changed in recent decades.
Play takes two forms.
Physical play is shared in common with other mammal species
	and is probably crucial to the development of
		a broad emotional range and a sense of urgency and confidence in demanding physical activities.
Another kind of play characteristically human is symbolic play,
	where the child, safe in the knowledge of having a secure base with a carer not too far away,
		will happily play with toys and other objects in the environment,
			often talking as he or she plays.
The toys come to represent aspects of the child's imagination
	and have a symbolic rather than simply a literal value.
This kind of play helps the child develop a strong sense of their inner world,
	which gives rise to the capacity for reflection and the sense of ownership of mental life.
A sense of self is not fully present until these capacities have developed.
Play is now seen as necessary for creative engagement throughout life.
For these developments to occur, the infant depends upon a responsive environment,
	where there is interactive play between infant and carer.
This is a situation which generates a particular kind of pleasure that neither could gain alone.
It is these relationships that help generate personality and social character.

In situations of trauma there can be a deficit in this type of relationship
	that means that the individual doesn't have the opportunity
		to gain a sense of his or her own value and capacities in relation to others.
Psychotherapy seeks to use this model of affective development, emotional development,
	to provide a containing and responsive relationship
		where the patient can be recognized, validated, and responded to.
In doing this, the therapist will bring something new into the relationship,
	something from the therapist's self.
This process of working with what is given by the patient and contributing something new
	is a strategy that actively promotes the growth of a healthy self.
A person can then develop the ability
	to integrate difficult experiences into an overall affirming narrative and life experience.
We seek to reestablish the zone of proximal development.
#+end_verse
** expression
mental [ˈment(ə)l]: adj. relating to the health or state of someone’s mind ⇨ psychiatric精神的
symbol [ˈsɪmb(ə)l]: n. a picture or shape that has a particular meaning or represents a particular organization or idea ⇨ sign符号,记号,象征
pitch [pɪtʃ]: n. how high or low a note or other sound is音高
carer ['kerər]: n. someone who looks after an old or ill person at home SYN caretaker American English看护者
genome [ˈdʒiˌnoʊm]: n. all the ↑genes in one type of living thing ⇨ DNA[生]基因组
responsive [rɪˈspɑnsɪv]: adj. eager to communicate with people, and to react to them in a positive way反应积极的
species [ˈspisiz]: n. a group of animals or plants whose members are similar and can breed together to produce young animals or plants ⇨ genus物种
process [prəˈses]: v. to deal with an official document, request etc in the usual way处理
soothe [suð]: v. to make someone feel calmer and less anxious, upset, or angry抚慰
amplify [ˈæmplɪˌfaɪ]: v. formal to increase the effects or strength of something放大, 增强
aliveness : n. the condition of living or the state of being alive活力
matrix [ˈmeɪtrɪks]: n. an arrangement of numbers, letters, or signs in rows and ↑columns that you consider to be one amount, and that you use in solving mathematical problems矩阵
unique [juˈnik]: adj. being the only one of its kind唯一的
in-built: adj. an inbuilt quality, feature etc is part of the nature of someone or something嵌入的
assess [əˈses]: v. to make a judgment about a person or situation after thinking carefully about it SYN judge评估
instinct [ˈɪnstɪŋkt]: n. a natural tendency to behave in a particular way or a natural ability to know something, which is not learned ⇨ intuition本能,直觉
intuition [ˌɪntuˈɪʃ(ə)n]: n. the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
characteristic [ˌkerəktəˈrɪstɪk]: adj. very typical of a particular thing or of someone’s character独特的,典型的
innate [ˈɪˌneɪt]: adj. an innate quality or ability is something you are born with先天的, 天生的
underpin [ˌʌndərˈpɪn]: v. to give strength or support to something and to help it succeed巩固, 支撑
fixed [fɪkst]: adj. fixed times, amounts, meanings etc cannot be changed SYN set固定的
disturbance [dɪˈstɜrbəns]: n. something that interrupts what you are doing, or the act of making this happen干扰
validate [ˈvælɪˌdeɪt]: v. to make someone feel that their ideas and feelings are respected and considered seriously使得到认同
heal [hil]: v. if a wound or a broken bone heals or is healed, the flesh, skin, or bone grows back together and becomes healthy again治愈
ownership [ˈoʊnərˌʃɪp]: n. the fact of owning something所有权, 物主身份
deficit [ˈdefəsɪt]: n. the difference between the amount of something that you have and the higher amount that you need ⇨ shortfall赤字, 不足额
affective [əˈfektɪv]: adj. relating to or having an effect on the emotions情感的
--------------------
take turns: 轮流
gut feeling: 直觉
be oriented towards sth.: 针对某事物
extend to sth.: 延伸到某事物
A be shared in common with B: A和B有共同之处
in the knowledge of sth./having sth.: 在知道某事下
** ch.
3-1 2 创造性的自我

心理健康依赖于与环境的持续更新关系。
作为社会性动物，人类的福祉依赖于与他人的沟通和关系。
个体的心智依赖于通过语言的沟通，利用符号来理解和参与世界。

从生命的起点开始，人类就具备了沟通的能力。
婴儿能够哭泣来表达其他情感，能够轮流互动，并能随着对话的节奏和音调作出音乐性反应。
他们通过与父母或看护者的互动进行这一切，他们与父母或看护者通过沟通和游戏建立关系。
这是一个让婴儿通过他人的环境作为成长手段的过程。
人类基因组为每个个体提供了许多潜能，但需要与一个足够响应的看护者环境互动。
通过这种方式，婴儿可以发展出允许他或她成为人类社会中完全参与者的能力。

与其他物种相比，人类婴儿高度依赖成年人。
他们需要许多年才能发展出照顾自己的技能。
婴儿出生时并没有自我意识。
这种意识随着时间的推移而发展，成为我们第二天性的一部分。
它依赖于早期的学习。
自我意识通过沟通和探索中的体验产生。
这些心理生活的方面需要时间才能确立。

自我意识是一个积极的成就，反映了个体对自身价值的认知。
积极和消极的情感需要通过早期的关系以不同的方式来处理。
这些关系一方面安抚困扰，另一方面增强婴儿的生命感。
这有助于婴儿的价值感的建立，为从他人那里学习提供了空间，这被称为近距离发展区。

出生时，我们被抛入人类的世界，一个人在这个复杂关系网络中有一席之地，而这些关系对每个个体都有重要意义。
人类像所有其他物种一样，存在于物质世界中，但人类的独特之处在于我们也存在于象征性的领域中。
也就是说，人类在语言的世界和物质的世界中共同成长。
从一开始，他们就能够在情感和身体上参与其中。
情感是所有人类体验的一部分，充当了内建的价值系统，帮助婴儿和成人评估他们的体验，选择那些促进生命感和成长的互动。
这可以被描述为利用直觉、感觉或本能。
每个人在与他人和更广泛环境互动时产生的情感类型，逐渐成为个体的特征。

在过去几十年中，研究重新审视了情感在心理生活中的角色。
生命感对心理健康和心理生活的发展至关重要。
所有活生生的生物都寻求探索环境，以寻找他们生存和繁荣所需的东西。
这种倾向被称为寻求系统。
它是一个天生的能力，对于人类来说，扩展到关系和象征性的生活方面。
这为人类生活中的联系渴望和寻找意义提供了基础。
这也意味着，健康的心理生活的很大一部分面向未来。

意义感不是固定的或外部的，而是通过沟通、关系和技能的建立创造出来的。
现实通过他人在交流中的认可和回应来确认，也就是说，通过对话。
这就是为什么人们寻求心理困扰帮助的原因之一。
他们有通过安全和认可的关系重新找到自身定位的需求。
自我意识可能会因创伤、压力或疾病而变得紊乱。
而治疗关系则是恢复自我的必要条件。

很长一段时间，游戏被视为儿童的事。
这一观点在最近几十年发生了变化。
游戏有两种形式。
身体游戏是与其他哺乳动物共同拥有的，可能对广泛的情感范围和对要求高强度身体活动的紧迫感和自信心的培养至关重要。
另一种典型的人类游戏是象征性游戏，孩子在有着一个可靠的看护者作为安全基地的情况下，会开心地与玩具和其他环境中的物品玩耍，通常一边玩耍一边说话。
这些玩具代表了孩子想象的某些方面，具有象征性的意义，而不仅仅是字面上的价值。
这种游戏帮助孩子发展他们内心世界的强烈意识，从而培养反思能力，并对心智生活产生主权感。
在这些能力发展之前，自我意识并未完全形成。
如今，游戏被视为一生中创造性参与的必要条件。
为了实现这些发展，婴儿依赖于一个有反应的环境，其中婴儿和看护者之间有互动性的游戏。
这是一个产生特定类型愉悦的情境，单独一方无法获得这种愉悦。
正是这些关系有助于塑造个性和社会性格。

在创伤的情境中，这种类型的关系可能会出现缺失，导致个体没有机会在与他人的关系中获得自己的价值和能力的认同。
心理治疗旨在利用这种情感发展模型，提供一个包容和反应的关系，在这种关系中，患者可以得到认同、验证和回应。
在此过程中，治疗师将带入一些新的东西，来自治疗师自身的东西。
这种与患者给予的内容合作并贡献新东西的过程，是一种积极促进健康自我成长的策略。
这样，个体可以发展出将困难的经历整合到一个肯定的叙事和生命体验中的能力。
我们寻求重新建立近距离发展区。
** sentence
mental [ˈment(ə)l]: adj. relating to the health or state of someone’s mind ⇨ psychiatric精神的
- Maybe you should stay attuned to your husband's mental state because he is running water into other's fields.
- The patient with mental illness closes against his carer who used to have an intimate relatioship with him.
- When you see water quirt out of a patient's mouth, you won't make such remark about mental illness.
symbol [ˈsɪmb(ə)l]: n. a picture or shape that has a particular meaning or represents a particular organization or idea ⇨ sign符号,记号,象征
- The symbol of the ancient empire remains in the wall with very little wear and tear.
- The symbol in the ceiling gave new resonance to those visitors.
- The symbol represents how many times this school have run races.
pitch [pɪtʃ]: n. how high or low a note or other sound is音高
- My baby, who repsonsed musically to the pitch of my voice, caught the eye of my wife. 
- When you receive eletric shocks to your hands, you won't notice the change of his pitch.
- Don't be too hard on me, he said with a high pitch.
carer ['kerər]: n. someone who looks after an old or ill person at home SYN caretaker American English看护者
- We need to distract carers from the door when Tom is sneaking into the house.
- The carer soothes the infant better when he has these toys than when he is with bare hands.
- The high picth of the infant's cry sent the carer's minds wandering.
genome [ˈdʒiˌnoʊm]: n. all the ↑genes in one type of living thing ⇨ DNA[生]基因组
- The research for the genome is subjected to the lack of money.
- The genome provides many potentials for humanities, who also live in the symbolic world.
- The scientist is describing the affect of genome on a scale from an ant to a person.
responsive [rɪˈspɑnsɪv]: adj. eager to communicate with people, and to react to them in a positive way反应积极的
- I must admit that your child is responsive in class.
- The cat responsed to our voice, which means that she is responsive after the car accident.
- A responsive parent should be good at coping with his or her baby crying.
species [ˈspisiz]: n. a group of animals or plants whose members are similar and can breed together to produce young animals or plants ⇨ genus物种
- Please take your hands off the book entitled The Origin of Species.
- The medication acts on this kind of species doesn't mean it acts well on human either.
- The extinction of the species on the island is beyond our expectation.
process [prəˈses]: v. to deal with an official document, request etc in the usual way处理
- The junior engineer gets promoted along with ways to process data effectively.
- Our company began to make a profit along with ways to process requests from customers.
- Tailing it to the company, our programmer processed and updated the project.
soothe [suð]: v. to make someone feel calmer and less anxious, upset, or angry抚慰
- The key to soothing your wife is to satisfied her emotional needs.
- A click away, the carer will pay you a visit and help soothe your infant.
- The lady refused to soothe her singer husband when he told something in his heart, which undermined his faith in her.
amplify [ˈæmplɪˌfaɪ]: v. formal to increase the effects or strength of something放大, 增强
- The background music of the movie amplified our fears in the scenario.
- Somehow, soothing from her husband amplified her fears about the future.
- The breakdown of trust in the authorities amplified damage of the social upheaval.
aliveness : n. the condition of living or the state of being alive活力
- A sense of aliveness helps him compete with those famous players.
- I could feel a sense of her aliveness from various perspectives.
- More recently, I couldn't feel a sense of aliveness because of mental illness.
matrix [ˈmeɪtrɪks]: n. an arrangement of numbers, letters, or signs in rows and ↑columns that you consider to be one amount, and that you use in solving mathematical problems矩阵
- He keeps in mind how to process the question about matrix.
- The test will multiply the amount of questions about matrix to help you find your weakness.
- The scientist will solve the question about matrix on TV in real time.
unique [juˈnik]: adj. being the only one of its kind唯一的
- The weight of the patient is unique at several points in the day.
- I allow time for you to find the unique key to open the door.
- Obviously, your wife aims at the unique activity, the Hot Balloon.
in-built: adj. an inbuilt quality, feature etc is part of the nature of someone or something嵌入的
- There is an in-built value system that assesses the value of my experience.
- Tuining in to broadcast, the person took interest in this kind of in-built chip.
- Take a guess whether the chip is in-built.
assess [əˈses]: v. to make a judgment about a person or situation after thinking carefully about it SYN judge评估
- Having little connection to my ex-wife, I prefer not to assess her mental life.
- The anomymous assessment made him unaccountable for its outcome.
- With assessment comes the change, our company began to make a profit.
instinct [ˈɪnstɪŋkt]: n. a natural tendency to behave in a particular way or a natural ability to know something, which is not learned ⇨ intuition本能,直觉
- The famous actor ensures that he doesn't take part in a movie which his instinct hates.
- Due to my instinct, I was unwilling to play truant from school when they asked me to.
- Depending on your instinct rather than facts and logic leaves you less informed than before you went to school.
intuition [ˌɪntuˈɪʃ(ə)n]: n. the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
- According to my intuition, you will pass the exam and lead a successful life.
- A big farm couldn't take the plunge just because of your intuition.
- It is a common saying that your first intuition always trys to protect you.
characteristic [ˌkerəktəˈrɪstɪk]: adj. very typical of a particular thing or of someone’s character独特的,典型的
- It appears that the actor who refused our boss is characteristic.
- His characteristic introducation made a strong impression on our boss.
- In one case, characteristic behavors don't fill the ecological niche.
innate [ˈɪˌneɪt]: adj. an innate quality or ability is something you are born with先天的, 天生的
- My wife has an innate ability to attract dogs. 
- The elephant has an innate ability to recognize people who he met.
- Our cat has an innate ability to recognize colors.
underpin [ˌʌndərˈpɪn]: v. to give strength or support to something and to help it succeed巩固, 支撑
- His crossing path with our boss on a boat underpined his social state in the company.
- The rule, speaking in public isn't limited to managers, underpins the democracy of our company.
- After years apart, my uncle has underpined his social state in the town.
fixed [fɪkst]: adj. fixed times, amounts, meanings etc cannot be changed SYN set固定的
- The profit he made goes beyond the fixed salary you offer.
- The therapist believes that a person's capacity to make friends is not fixed even though he is aging.
- The shape of our cat is fixed in adulthood.
disturbance [dɪˈstɜrbəns]: n. something that interrupts what you are doing, or the act of making this happen干扰
- Because of your disturbance in this afternoon, I fails to encode the framework into our project.
- It is hard for to takcle problems with your disturbance all the time.
- The police is trying to keep track of the deal with his relative's disturbance.
validate [ˈvælɪˌdeɪt]: v. to make someone feel that their ideas and feelings are respected and considered seriously使得到认同
- If you want to show concern for your wife, she should be validated in what she has done for you.
- The soldier was validated by his general because he kept standing guard when running into storm.
- I comforted my wife with those words in which she was validated in house chores.
heal [hil]: v. if a wound or a broken bone heals or is healed, the flesh, skin, or bone grows back together and becomes healthy again治愈
- It is hard to escape the conclusion that he has been healed and avoided going to school.
- Even a prisoner in captivity will be healed in the activity.
- Given that his mental illness is hard to be healed, she got divorced from him.
ownership [ˈoʊnərˌʃɪp]: n. the fact of owning something所有权, 物主身份
- It is more important than ever to gain the ownership of your house.
- The ownership of the field brought about peasant revolts.
- The Army of Revolution promised that the peasants would gain the ownership of fields.
deficit [ˈdefəsɪt]: n. the difference between the amount of something that you have and the higher amount that you need ⇨ shortfall赤字, 不足额
- There is a huge deficit of $500 in our family.
- Because of the deficit last month, I decided not to buy the car.
- Instead of compensating for the deficit last month, the housewife kept purchasing something expensive and unnecessary.
affective [əˈfektɪv]: adj. relating to or having an effect on the emotions情感的
- After his wife refused to soothe him in the programme, his affective disorders erupted.
- No one care about his affective disorders and asks him to soothe his unpolite wife.
- After his breakup with our coworker, he was diagnosed with affective disorders.
--------------------
take turns: 轮流
- We take turns to take good care of the infant.
- Neglecting the warning, the peasants took turns to steal the power line.
- Ignoring the rules, our colleagues took turns to be late for work.
gut feeling: 直觉
- Due to gut feeling, I asked out the girl, who is my wife now.
- Due to gut feeling, I refused to sign for the document.
- Due to gut feeling, I refused to make an agreement with the company.
be oriented towards sth.: 针对某事物
- Oriented towards serious mental illness, he was sent to America to have an operation.
- Oriented towards the future, I am determined to save money when I am able to work.
- Oriented towards stray dogs, the lady offered them with poisonous foods.
extend to sth.: 延伸到某事物
- Extending to our project, I need to encode the framework into it. 
- Extending to a company, everyone should obey the rule and those who break it should be punished.
- Extending to a country, the Party should represent the common interest of people. 
A be shared in common with B: A和B有共同之处
- Beyond doubt, Chinese is shared in common with English.
- A cat is shared in common with a dog when they are raised up in the same apartment.
- Your wife is shared in common with my wife, who loves to journey abroad.
in the knowledge of sth./having sth.: 在知道某事下
- In the knowledge of my dog hiding under the couch, I began to enjoy snacks.
- In the knowledge of his wife's absense, he led my girlfriend to his apartment.
- In the knowledge of the existence of heavy guns, he ordered his men to surrender.
** sentence2
mental [ˈment(ə)l]: adj. relating to the health or state of someone’s mind ⇨ psychiatric精神的
- Maybe you should stay attuned to your husband's mental state because he is running water into other people's fields.
- The patient with mental illness closes against his carer who used to have an intimate relationship with him.
- When you see water squirt out of a patient's mouth, you won't make such remarks about mental illness.
symbol [ˈsɪmb(ə)l]: n. a picture or shape that has a particular meaning or represents a particular organization or idea ⇨ sign符号,记号,象征
- The symbol of the ancient empire remains on the wall with very little wear and tear.
- The symbol in the ceiling gave new resonance to those visitors.
- The symbol represents how many times this school has run races.
pitch [pɪtʃ]: n. how high or low a note or other sound is音高
- My baby, who responded musically to the pitch of my voice, caught the eye of my wife. 
- When you receive electric shocks to your hands, you won't notice the change of his pitch.
- Don't be too hard on me, he said with a high pitch.
carer ['kerər]: n. someone who looks after an old or ill person at home SYN caretaker American English看护者
- We need to distract carers from the door when Tom is sneaking into the house.
- The carer soothes the infant better when he has these toys than when he is with bare hands.
- The high pitch of the infant's cry sent the carer's mind wandering.
genome [ˈdʒiˌnoʊm]: n. all the ↑genes in one type of living thing ⇨ DNA[生]基因组
- The research for the genome is subjected to the lack of money.
- The genome provides many potentials for humanities, who also live in the symbolic world.
- The scientist is describing the effect of the genome on a scale from an ant to a person.
responsive [rɪˈspɑnsɪv]: adj. eager to communicate with people, and to react to them in a positive way反应积极的
- I must admit that your child is responsive in class.
- The cat responded to our voice, meaning she was responsive after the car accident.
- A responsive parent should be good at coping with his or her baby crying.
species [ˈspisiz]: n. a group of animals or plants whose members are similar and can breed together to produce young animals or plants ⇨ genus物种
- Please take your hands off the book entitled The Origin of Species.
- The medication acts on this kind of species doesn't mean it acts well on humans either.
- The extinction of the species on the island is beyond our expectations.
process [prəˈses]: v. to deal with an official document, request etc in the usual way处理
- The junior engineer gets promoted along with ways to process data effectively.
- Our company began to make a profit along with ways to process requests from customers.
- Tailing it to the company, our programmer processed and updated the project.
soothe [suð]: v. to make someone feel calmer and less anxious, upset, or angry抚慰
- The key to soothing your wife is to satisfy her emotional needs.
- A click away, the carer will pay you a visit and help soothe your infant.
- The lady refused to soothe her singer husband when he told something in his heart, which undermined his faith in her.
amplify [ˈæmplɪˌfaɪ]: v. formal to increase the effects or strength of something放大, 增强
- The background music of the movie amplified our fears in the scenario.
- Somehow, soothing from her husband amplified her fears about the future.
- The breakdown of trust in the authorities amplified the damage of the social upheaval.
aliveness : n. the condition of living or the state of being alive活力
- A sense of aliveness helps him compete with those famous players.
- I could feel a sense of her aliveness from various perspectives.
- More recently, I couldn't feel a sense of aliveness because of mental illness.
matrix [ˈmeɪtrɪks]: n. an arrangement of numbers, letters, or signs in rows and ↑columns that you consider to be one amount, and that you use in solving mathematical problems矩阵
- He keeps in mind how to process the question about the matrix.
- The test will multiply the number of questions about the matrix to help you find your weakness.
- The scientist will solve the question about the matrix on TV in real-time.
unique [juˈnik]: adj. being the only one of its kind唯一的
- The weight of the patient is unique at several points in the day.
- I allow time for you to find the unique key to open the door.
- Obviously, your wife aims at the unique activity, the Hot Balloon.
in-built: adj. an inbuilt quality, feature etc is part of the nature of someone or something嵌入的
- There is an in-built value system that assesses the value of my experience.
- Tuning in to the broadcast, the person took interest in this kind of in-built chip.
- Take a guess whether the chip is in-built.
assess [əˈses]: v. to make a judgment about a person or situation after thinking carefully about it SYN judge评估
- Having little connection to my ex-wife, I prefer not to assess her mental life.
- The anonymous assessment made him unaccountable for its outcome.
- With assessment comes the change, and our company began to make a profit.
instinct [ˈɪnstɪŋkt]: n. a natural tendency to behave in a particular way or a natural ability to know something, which is not learned ⇨ intuition本能,直觉
- The famous actor ensures that he doesn't take part in a movie which his instinct hates.
- Due to my instinct, I was unwilling to play truant from school when they asked me to.
- Depending on your instinct rather than facts and logic leaves you less informed than before you went to school.
intuition [ˌɪntuˈɪʃ(ə)n]: n. the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
- According to my intuition, you will pass the exam and lead a successful life.
- A big farm couldn't take the plunge just because of your intuition.
- It is a common saying that your first intuition always tries to protect you.
characteristic [ˌkerəktəˈrɪstɪk]: adj. very typical of a particular thing or of someone’s character独特的,典型的
- It appears that the actor who refused our boss is characteristic.
- His characteristic introduction made a strong impression on our boss.
- In one case, characteristic behaviors don't fill the ecological niche.
innate [ˈɪˌneɪt]: adj. an innate quality or ability is something you are born with先天的, 天生的
- My wife has an innate ability to attract dogs. 
- The elephant has an innate ability to recognize people who he met.
- Our cat has an innate ability to recognize colors.
underpin [ˌʌndərˈpɪn]: v. to give strength or support to something and to help it succeed巩固, 支撑
- His crossing path with our boss on a boat underpins his social state in the company.
- The rule, that speaking in public isn't limited to managers, underpins the democracy of our company.
- After years apart, my uncle has underpinned his social state in the town.
fixed [fɪkst]: adj. fixed times, amounts, meanings etc cannot be changed SYN set固定的
- The profit he made goes beyond the fixed salary you offer.
- The therapist believes that a person's capacity to make friends is not fixed even though he is aging.
- The shape of our cat is fixed in adulthood.
disturbance [dɪˈstɜrbəns]: n. something that interrupts what you are doing, or the act of making this happen干扰
- Because of your disturbance this afternoon, I failed to encode the framework into our project.
- It is hard for to takcle problems with your disturbance all the time.
- The policeman was trying to keep track of the dealer with his relative's disturbance.
validate [ˈvælɪˌdeɪt]: v. to make someone feel that their ideas and feelings are respected and considered seriously使得到认同
- If you want to show concern for your wife, she should be validated in what she has done for you.
- The soldier was validated by his general because he kept standing guard when running into a storm.
- I comforted my wife with those words in which she was validated in house chores.
heal [hil]: v. if a wound or a broken bone heals or is healed, the flesh, skin, or bone grows back together and becomes healthy again治愈
- It is hard to escape the conclusion that he has been healed and avoided going to school.
- Even a prisoner in captivity will be healed in the activity.
- Given that his mental illness is hard to heal, she got divorced from him.
ownership [ˈoʊnərˌʃɪp]: n. the fact of owning something所有权, 物主身份
- It is more important than ever to gain ownership of your house.
- The ownership of the field brought about peasant revolts.
- The Army of Revolution promised that the peasants would gain the ownership of fields.
deficit [ˈdefəsɪt]: n. the difference between the amount of something that you have and the higher amount that you need ⇨ shortfall赤字, 不足额
- There is a huge deficit of $500 in our family.
- Because of the deficit last month, I decided not to buy the car.
- Instead of compensating for the deficit last month, the housewife kept purchasing something expensive and unnecessary.
affective [əˈfektɪv]: adj. relating to or having an effect on the emotions情感的
- After his wife refused to soothe him in the program, his affective disorders erupted.
- No one cares about his affective disorders and asks him to soothe his unpolite wife.
- After his breakup with our coworker, he was diagnosed with affective disorders.
--------------------
take turns: 轮流
- We take turns to take good care of the infant.
- Neglecting the warning, the peasants took turns stealing the power line.
- Ignoring the rules, our colleagues took turns to be late for work.
gut feeling: 直觉
- Due to gut feeling, I asked out the girl, who is my wife now.
- Due to gut feeling, I refused to sign the document.
- Due to gut feeling, I refused to make an agreement with the company.
be oriented towards sth.: 针对某事物
- Oriented towards serious mental illness, he was sent to America to have an operation.
- Oriented towards the future, I am determined to save money when I am able to work.
- Oriented towards stray dogs, the lady offered poisonous foods to them.
extend to sth.: 延伸到某事物
- Extending to our project, I need to encode the framework into it. 
- Extending to a company, everyone should obey the rule and those who break it should be punished.
- Extending to a country, the Party should represent the common interest of the people. 
A be shared in common with B: A和B有共同之处
- Beyond doubt, Chinese is shared in common with English.
- A cat is shared in common with a dog when they are brought up in the same apartment.
- Your wife is shared in common with my wife, who loves to journey abroad.
in the knowledge of sth./having sth.: 在知道某事下
- In the knowledge of my dog hiding under the couch, I began to enjoy snacks.
- In the knowledge of his wife's absence, he led my girlfriend to his apartment.
- In the knowledge of the existence of heavy guns, he ordered his men to surrender.
