#+OPTIONS: \n:t num:nil html-postamble:nil

* task11-prereading

作业1： task2 ⼤作⽂
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?

读： 70%
1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
2. 泛读&泛听这个话题（尽量别看范⽂）
3. 随⼿记下新的内容+结构+表达
练： 20%
1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。（控制在500字左右，不限时间）
改： 10%
1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改，但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）
	 
** task10课上:为啥先教写作，而非口语?
写作=内容+结构+表达(单词~语法~习惯用法)
口语=内容+结构+表达(单词~语法~习惯用法)+语音(连读~语调~变音~自然拼读法则~音标)
从这方面可以认为写作是口语的基础.
而且写作的反复修改可以使人变得精确,更加的有逻辑性.由此带来的好处是口语更有逻辑性,不至于前言不搭后语.

** 读： 70%
1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
2. 泛读&泛听这个话题（尽量别看范⽂）
3. 随⼿记下新的内容+结构+表达

** 练： 20%
1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。（控制在500字左右，不限时间）

** 改： 10%
1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改，但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）

** 作文: Why should we learn more about the history of our houses and how to do it?
There are some motivations for us to research the history of the houses where we live in.
1. Rehabilitation
2. Curiosity
3. Connection
4. Save money.
Some motivations are practical and can show tangible results.
They will let us possess a more emotional flavor about our houses and embrace our houses' quirks.

Unfortunately, many houses have been stripped of their original charm
	and renovated to the style which their previous owner liked.
We discover what changed over time
	and unearth original configuration and architectural details
		so that we could have the ability to bring back them to the original style
			and combine modern conveniences.
In my opinion, I am always plain inquisitive about the history of my house.
Occasionally, I come across something weird during my renovations.
I would want to know the accomplishment, which the past occupations has made.
One of benefits of learning about the history of them is discovering your roots and creating a connection with family.
The house not only provides people with a sense of being part of a continuum,
	but gives meaning to the present and future.
Sometimes, you may save money if you learn a lot about your house.
You will have a better understanding of the condition of building material,
	finishes, and utilities electric system update.
You will be aware of whether asbestos or lead-based paint is still present.
This will prevent you from leading to costly surprises.

There are so many benefits of find out about the history of our houses.
However, how to reach it is always a mystery to us.

Let me show you some methods to get it.

Look closely at your house.
There are always rafters in attic and bricks in the basement,
	which may help you know how old your house is.
The different-size bricks also mean the different construction cycles.

Be your own archaeologist.
If you scope out your backyard, you may look at buried treasure, which contains some old things.
To contact your local archaeologist society often give you more informations than you want.

Talk to people.
Talk to people no matter who they are but can provide you more information about the house,
	like your neighbors, local business owners even the mailman.

Learn the history of the are.
Try to know how old the city is. Are there any major events take part in?

	 
** Benefits of Researching a Home’s History drift
Our old house turned 100 years old in 2016. 
Throw it a birthday party.
The motivation for me to research.
1. Rehabilitation.
2. Historical Designation.
3. Curiosity.
4. Connection.
5. Save money.
are practical and show tangible results.
possess a more emotional flavor.
am still in the process of learning.
gather information
piece together story.
embrace its quirks
*** 1. Rehabilitation
be strippped of
be renovated to

infuse historical charm back into their old houses
discover the timeline of their ol house
unearth original configuration and architectural details
What changed in the house over time?
Have the rooms always been in same place

gain an insight into
have the ability to
bring back
be cognizant that ...
be quite different as further detailed in ...
combine modern conveniences while still retaining their home's historic character
has modern conveniences with sth.
*** 2. Historic Designation
determine it's eligibility for a formal historic designation
a variety of historic designations through local, state, and national levels

demonstrate a significant connection to history, person, or architecture

uncover its role in history or culture

- Financial incentives via tax-credits
- Technical assistance from experts
- Special exemptions from building codes
*** 3. Curiosity
be plain inquisitive about
be curios about the physical aspects of the house
come across something weird during you renovations

The past occupations.
accomplishment
occupations
*** 4. Connection
Genealogy
Discovering your roots and create a connection with family
apply the same approach to finding meaning through genealogy of the past owners of their old houses
provide people with a sense of being part of a continuum, psychologically and emotionally healthy
give meaning to the present and future
*** 5 save money
provides a better understanding of the condition of building material, finishes, and utilities
electrical system update
asbestos or lead-based paint is still present.

lead to costly surprises
develop a proactive strategy
develop a more accurate budget and timeline for major projects and regular maintenance
let's face it, nobody wants to be in that situation

** How to Learn More About the History of Your Home
Tracking down property records and researching other documents can shed light on the life of a house.

Establish a chain of title.
the first thing: trace the owners of the property.
Ask for the information contained on the property card, which will include your name as the owner,
	the name of the person you bought it from, the property address and an assessor's property map
	at your local assessor's office or online.

Follow your house's past.
town clerk's offices keep copies of property deeds, which you can follow back.
start with the person you bought the house from, trace who they purchased the home from, and so on.

Ask for help.
Local historical societies, local libraries, town hall, even genealogists could probably help.

Fllow the people.
explore the social history of the people who lived in the house.

** 10 Ways to Resarch Your Home's history
- Look closely at you house.
	rafters in attic and bricks in the basement / how old your house might be.
	dates or stamps left by the builder
	different-size bricks/ different construction cycles
	old wallpaper or paint/ be traced back to a popular period style
- Be your own archaeologist
	scope out your backyard/ look at buried treasure
	contact your local archaeology society
- talk to people
	your neighbors, local business owners, the mailman
- learn the history of the area
	how old the city
	major event take place in
	ask questions in order to see beyond the surface
- check your historic district status
	check with your local planning department or historic preservation commission.
- Research land and property records
	deed or title search can tell you who owned the property
	tax records can tell you how the property has changed over time.
- Look up local census data
	Census records can tell you more about the lives of previous owners,
		like the number of children in the house, cost of the home,
			 whether the home had a radio, and more.
- Contact with your local historic society and visit your public library

	
** questions
1. 总结的时候不知道说什么了.
2. 行文非常松散,缺乏条理性
