#+OPTIONS: \n:t num:nil html-postamble:nil
* task3 课前作业 复述
家庭作业:
材料: "The Best ..."
1. 读懂本文(单词+语法+习惯用法)
2. 摘抄习惯用法+句型
3. 跟读本文50遍(计数)
4. tell the story(可汉语)
5. 英语长难句,native speaker是否使用in dayly life? 用,我听Chandler讲过
6. 收集疑惑
疑惑:
1. 如何造出更好的句子? 单词造句指南
2. Tell the story,是不是对口语和写作有帮助?
3. tell the story 对口语, 写作的帮助的逻辑是什么?

** material
Let Him Go, Olivia
Alejandro Arbide, San Antonio, Texas

There I was.
Upside down inside the swimming pool. Drowned.
My parents were screaming.
It must have been the summer of ’63.
It was a gloomy day.
Every Sunday we went to my grandparents’ house.
My cousins and I were playing alongside the pool.
I must have slipped.
At three years old, I did not know how to swim.
My mother was giving me CPR.
More than twenty or twenty-five minutes had gone by.
The ambulance had arrived.
Everybody was staring at my mother.
“Let him go, Olivia. It's over.”
Even my father had some feelings of resignation.
Yet, she never gave up.
I write this story as a tribute to my mother, who, only four years later, passed away.
And also in recognition of editors
	who made it possible for my mother to have read in Reader’s Digest the miracle
		made by another woman utilizing then recently discovered CPR.

** 单词造句指南
- 网:v.+v.变化 情态动词+时态的转变
- 四句型转换
- 方式/地点/时间
- 结合其他习惯用法
- 其他单词+词性组合
- 原文摘抄+变

** point
- let sb go
- There I was.倒装
- drowned
- were doing
- must have been
- the summer of '63
- alongside sp.
- how to
- give sb sth
- more than
- had done
- It's over.
- have feelings of resignation
- give up
- write this story as a tribute to sb.
- pass away
- in recognition of sb.
- make it possible for sb to have done
- utilize
	
** words
- drowned [draʊn]
	1. Twelve years ago, my villager drowned while swimming alone.
	2. My villager has been drowned for over 10 years.
	3. I'm sorry that my villager drowned at only 12 years old.
- utilize [ˈjut(ə)lˌaɪz]
	1. Utilizing CPR makes it possible to save his child.
	2. In recognition of my father, who has utilized the tool.
	3. It's a miracle achieved by the great woman who utilized CPR.

** expression
- the summer of '63
	1. It is the summer of '63.
	2. The authorities always instructed the workers to do outdoor work in the summer of '63.
	3. The authorities instructed the workers to do outdoor work in the summer of '63.
- give sb sth
	1. My best friend has given me a lot of comfort.
	2. It's necessary for you to give your father a desk.
	3. She has never given her husband an apple.
- It's over.
- give up
	1. Royal never gives up during the race.
	2. It's necessary for you to give up immediately.
	3. You should give it up if you fail to do it the first time.
- pass away
	1. Let him go. He has passed away.
	2. My grandfather passed away over 10 years ago.
	3. There are hundreds of people passing away in this flood.
- in recognition of sb.
	1. In recognition of Rachel who opened the first woman's hospital.
	2. In recognition of Edison who invented the electric lamp.
	3. In recognition of Deng who has made it possible for us to not be hungry anymore.
	
** sentence
- write this story as a tribute to sb.
	1. I'm writing this story as a tribute to my classmate who had harmed many girls.
	2. The editors write stories as a tribute to the great chairman, Mao.
	3. He attempted to write the story as a tribute to his classmate who had never hurt him.
- make it possible for sb to have done
	1. The internet makes it possible for us to connect promptly.
	2. The manager makes it possible for me to achieve my goal.
	3. The manufacturer makes it possible for us to buy noodles in a remote village.

** grammar
- more than
- There I was.倒装
- were doing
- must have been
- how to
- had done


** tell the story
The writer drowned upside down in the swimming when he was only at three years old.
My mother had been giving me CPR.
Over more than twenty minutes, the ambulance had arrived and everybody was staring at my mother.
My father said: "Let him go, Olivia. It's over."
However, my mother never gave up.
The writer wrote the story a tribute to his mother who passed away only four years later.
And also in recognition of editors who made his mother to have read a story about CPR.
