#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* task7-prereading
еЃґеЇ≠дљЬдЄЪ:
жЭРжЦЩ:еЙСйЫЕ16зЬЯйҐШзђђдЄАе•Ч
1. [ењЕдњЃ] еЙСйЫЕ16зЬЯйҐШпЉМдЄЙзѓЗйШЕиѓїжЦЗзЂ†пЉМеП™зЬЛйҐШеЮЛгАВ
	иѓЈжАїзїУиАГзЪДжШѓдїАдєИйҐШеЮЛпЉМе∞ЭиѓХжАїзїУиАГеѓЯзЪДжКљи±°иГљеКЫsub-skillsжШѓдїАдєИ?
	 1. еЙСйЫЕйШЕиѓїдљУеЮЛжШѓдїАдєИ?
			еИ§жЦ≠~еНХйАЙ~е§ЪйАЙ~е°Ђз©Ї~йЕНеѓє
	 2. иАГеѓЯзЪДsubskillsжШѓдїАдєИ?
			- еРМдєЙиѓН
			- зРЖиІ£
			- е§Нињ∞
			- жАїзїУ
2. [ењЕдњЃ]з≤ЊиѓїзђђдЄАзѓЗжЦЗзЂ† why we need to protect polarbears
	 - еНГдЄЗеИЂеБЪйҐШ
	 - ж†ЗиЃ∞еЕ®жЦЗиѓ≠ж≥Х+зФЯиѓН+дє†жГѓзФ®ж≥Х (жШѓеР¶йА†еП•иЗ™йАЙ)
3.[ењЕдњЃ]жЧ†йЬАиЈЯиѓїпЉМдљЖеПНе§НйШЕиѓї50йБН+еБЪйҐШ (жЯ•зЬЛж≠£з°ЃзОЗ)
4.[йАЙдњЃ] йШЕиѓївАЭMeditation for DummiesвАЭдЄАдє¶дЄ≠вАЬFollowingYour BreathвАЭдЄАжЦЗгАВ
	еПѓдї•жЯ•йШЕеЖ•жГ≥зЪДе•ље§ДпЉМbingпЉМеТХеТХеТХгАВ
	еЖЩдљЬ&еП£иѓ≠еЖЕеЃєеЗЖе§Зtask0.5

** questions
1. з≤ЊиѓїжШѓж≥ЫиѓїзЪДеЯЇз°А,йЭЩеРђжШѓеР¶жШѓж≥ЫеРђзЪДеЯЇз°А?
2. йШЕиѓїжЧґжШѓеР¶и¶Бж≥®жДПжЦ≠еП•,жѓФе¶В /why we /need to protect polarbears/
** 1
*** R1: 1-13
1-7: 7 еИ§жЦ≠йҐШ
	- TRUE
	- FALSE
	- NOT GIVEN
	еРМдєЙиѓНиљђжНҐ+зРЖиІ£
8-13: 6 е°Ђз©ЇйҐШ
	е§Нињ∞иГљеКЫ
*** R2: 14-26
14-20:7 йЕНеѓєж†ЗйҐШйҐШ
	е§Нињ∞+жАїзїУ
21-24:4 е°Ђз©ЇйҐШ
	зРЖиІ£+жАїзїУ
25-26:2 е§ЪйАЙ
	зРЖиІ£+жАїзїУ
*** R3: 27-40
27-30: 4 еНХйАЙ
31-34: 4 е°Ђз©Ї
	е§Нињ∞+жАїзїУ
35-40: 6 йАЙжЛ©
	зРЖиІ£
** 2. Why we need protect polar bears?
Polar bears are being increasingly threatened by the effects of climate change,
	but their disappearance could have far-reaching consequences.
They are uniquely adapted /…ЩЋИd√¶pt/ to the extreme conditions of the Arctic Circle,
	where temperatures can reach -40¬∞C.
One reason for this is that they have up to 11 centimetres of fat underneath their skin.
Humans with comparative /k…ЩmЋИp√¶r…Щt…™v/ levels of adipose [√¶d…™po Кs] tissue
	would be considered obese [o КЋИbiЋРs]
	and would be likely to suffer from diabetes and heart disease.
Yet the polar bear experiences no such consequences.

A 2014 study by Shi Ping Liu and colleagues sheds light on this mystery.
They compared the genetic /d Т…™ЋИnet…™k/ structure of polar bears with
	that of their closest relatives from a warmer climate, the brown bears.
This allowed them to determine /d…™ЋИt…ЬЋРm…Щn/ the genes
	that have allowed polar bears to survive in one of the toughest environments on Earth.
Liu and his colleagues found the polar bears had a gene known as APoB,
	which reduces levels of low-density /ЋИdens…Щti/ lipoproteins /ЋИl…™p…Щpro КtiЋРn/ (LDLs)
	вАУ a form of вАШbadвАЩ cholesterol/k…ЩЋИlest…Щr…Тl/.
In humans, mutations/mjuЋРЋИte…™ Г…Щn/ of this gene are associated with increased risk of heart disease.
Polar bears may therefore be an important study model to understand heart disease in humans.

The genome/ЋИd ТiЋРn…Щ Кm/ of the polar bear may also provide the solution for another condition,
	one that particularly affects our older generation: osteoporosis/ЋМ…Тsti…Щ Кp…ЩЋИr…Щ Кs…Щs/.
This is a disease where bones show reduced density,
	usually caused by insufficient/ЋМ…™ns…ЩЋИf…™ Г…Щnt/ exercise, reduced calcium/ЋИk√¶lsi…Щm/ intake or food starvation.
Bone tissue is constantly being remodelled, meaning that bone is added or removed,
	depending on nutrient/ЋИnjuЋРtri…Щnt/ availability and the stress that the bone is under.
Female polar bears, however, undergo extreme conditions during every pregnancy.
Once autumn comes around, these females will dig maternity/m…ЩЋИt…ЬЋРn…Щti/ dens in the snow
	and will remain there throughout the winter, both before and after the birth of their cubs.
This process results in about six months of fasting,
	where the female bears have to keep themselves and their cubs alive,
	depleting/d…™ЋИpliЋРt/ their own calcium and calorie reserves.
Despite this, their bones remain strong and dense.

Physiologists Alanda Lennox and Allen Goodship found an explanation for this paradox/ЋИp√¶r…Щd…Тks/ in 2008.
They discovered that pregnant bears were able to increase the density of their bones
	before they started to build their dens.
In addition, six months later, when they finally emerged /…™ЋИm…ЬЋРd Т/ from the den with their cubs,
	there was no evidence of significant loss of bone density.
Hibernating/ЋИha…™b…Щne…™t/ brown bears do not have this capacity
	and must therefore resort/r…™ЋИz…ФЋРt/ to major bone reformation in the following spring.
If the mechanism/ЋИmek…Щn…™z…Щm/ of bone remodelling in polar bears can be understood,
	many bedridden humans, and even astronauts, could potentially benefit.

The medical benefits of the polar bear for humanity certainly
	have their importance in our conservation efforts,
	but these should not be the only factors taken into consideration.
We tend to want to protect animals we think are intelligent and possess emotions,
	such as elephants and primates.
Bears, on the other hand, seem to be perceived/p…ЩЋИsiЋРv/ as stupid and in many cases violent.
And yet anecdotal/ЋМ√¶n…™kЋИd…Щ Кtl/ evidence from the field challenges those assumptions,
	suggesting for example that polar bears have good problem-solving abilities.
A male bear called GoGo in Tennoji Zoo, Osaka,
	has even been observed making use of a tool to manipulate/m…ЩЋИn…™pj…Щle…™t/ his environment.
The bear used a tree branch on multiple occasions to dislodge/d…™sЋИl…Тd Т/ a piece of meat
	hung out of his reach.
Problem-solving ability has also been witnessed in wild polar bears,
	although not as obviously as with GoGo.
A calculated move by a male bear involved running and jumping onto barrels
	in an attempt to get to a photographer standing on a platform four metres high.

In other studies, such as one by Alison Ames in 2008,
	polar bears showed deliberate/d…™ЋИl…™b…Щr…Щt/ and focused manipulation.
For example, Ames observed bears putting objects in piles
	and then knocking them over in what appeared to be a game.
The study demonstrates/ЋИdem…Щnstre…™t/ that bears are capable of agile/ЋИ√¶d Тa…™l/ and thought-out behaviours.
These examples suggest bears have greater creativity
	and problem-solving abilities than previously thought.

As for emotions, while the evidence is once again anecdotal,
	many bears have been seen to hit out at ice and snow
	вАУ seemingly out of frustration/fr МЋИstre…™ Г…Щn/ вАУ
	when they have just missed out on a kill.
Moreover, polar bears can form unusual relationships with other species,
	including playing with the dogs used to pull sleds in the Arctic.
Remarkably, one hand-raised polar bear called Agee has formed a close relationship
		with her owner Mark Dumas to the point
	where they even swim together.
This is even more astonishing since polar bears are known to actively hunt humans in the wild.

If climate change were to lead to their extinction,
	this would mean not only the loss of potential breakthroughs in human medicine,
	but more importantly, the disappearance of an intelligent, majestic animal.
** all 28
far-ЋИreaching: having a great influence or effect
be adapted /…ЩЋИd√¶pt/ to: To be suited to a particular environment or situation.
consequence [ЋИk…СЋРns…Щ-kwens]: something that happens as a result of a particular action or set of conditions
centimetres [ЋИsent…™ЋМmiЋРt…Щ]: 1/100 metre
have up to: To be able to do or achieve something
comparative /k…ЩmЋИp√¶r…Щt…™v/: comparative figures/data
adipose [√¶d…™po Кs]: in storage
tissue [ЋИt…™ ГuЋР]: зїДзїЗ
obese [o КЋИbiЋРs]: very fat in a way that is unhealthy
diabetes [ЋМda…™…ЩЋИbiЋРtiЋРz]: a serious disease in which there is too much sugar in your blood
genetic /d Т…™ЋИnet…™k/: relating to genes or genetics
determine /d…™ЋИt…ЬЋРm…Щn/: to find out the facts about something
low-density /ЋИdens…Щti/: the degree to which an area is filled with people or things
cholesterol /k…ЩЋИlest…Щr…Тl/: a chemical substance found in your blood. Too much cholesterol in your body may cause heart disease.
mutations /mjuЋРЋИte…™ Г…Щn/:  a change in the genetic structure of an animal or plant that makes it different from others of the same kind
genome /ЋИd ТiЋРn…Щ Кm/:all the genes in one type of living thing
osteoporosis /ЋМ…Тsti…Щ Кp…ЩЋИr…Щ Кs…Щs/:a medical condition in which your bones become weak and break easily
insufficient /ЋМ…™ns…ЩЋИf…™ Г…Щnt/: not enough, or not great enough
calcium /ЋИk√¶lsi…Щm/: symbol Ca
intake /ЋИ…™nte…™k/: the amount of food, drink etc that you take into your body
starvation /st…СЋРЋИve…™ Г…Щn/: suffering or death caused by lack of food
remodel /ЋМriЋРЋИm…Тdl/: to change the shape, structure, or appearance of something, especially a building
nutrient /ЋИnjuЋРtri…Щnt/: a chemical or food that provides what is needed for plants or animals to live and grow
undergo /ЋМ Мnd…ЩЋИ…°…Щ К/: if you undergo a change, an unpleasant experience etc, it happens to you or is done to you
comes around:To arrive or appear at a particular place.
dig: dig a hole/trench/grave etc
maternity /m…ЩЋИt…ЬЋРn…Щti/: relating to a woman who is pregnant or who has just had a baby е≠Хе¶ЗзЪДпЉЫдЇІе¶ЗзЪД вЖТ paternity
dens: the home of some animals, for example lions or foxes
cub: the baby of a wild animal such as a lion or a bear
result in: to cause or bring about
deplete /d…™ЋИpliЋРt/: to reduce the amount of something that is present or available
reserve: a unit for measuring the amount of energy that food will produce
paradox /ЋИp√¶r…Щd…Тks/: a situation that seems strange because it involves two ideas or qualities that are very different
emerge /…™ЋИm…ЬЋРd Т/: to appear or come out from somewhere
hibernate /ЋИha…™b…Щne…™t/: if an animal hibernates, it sleeps for the whole winter 
resort to /r…™ЋИz…ФЋРt/: when you must use or depend on something because nothing better is available
mechanism /ЋИmek…Щn…™z…Щm/: part of a machine or a set of parts that does a particular job
bedridden /ЋИbedЋМr…™dn/: unable to leave your bed, especially because you are old or ill
potentially /p…ЩЋИten Г…Щli/: something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future
tend to:to be likely to do or have something
perceived /p…ЩЋИsiЋРv/: to notice, see, or recognize something
anecdotal /ЋМ√¶n…™kЋИd…Щ Кtl/: consisting of short stories based on someoneвАЩs personal experience
suggesting for example: to offer an example of something that is being suggeste
manipulate /m…ЩЋИn…™pj…Щle…™t/: to use skill in moving or handling something
dislodge /d…™sЋИl…Тd Т/: to force or knock something out of its position
be involved doing to: be actively engaged in an activity or task
deliberate /d…™ЋИl…™b…Щr…Щt/:  intended or planned
appeared to :something seemed to be the case, but it is not necessarily true.
demonstrate /ЋИdem…Щnstre…™t/: to show or prove something clearly
agile /ЋИ√¶d Тa…™l/:   someone who has an agile mind is able to think very quickly and intelligently 
thought-out:  carefully/well/badly thought-out
"hit out": can also be used to describe a physical attack
frustration /fr МЋИstre…™ Г…Щn/: the feeling of being annoyed, upset, or impatient, because you cannot control or change a situation, or achieve something
miss out: be used to describe a situation in which someone does not have the opportunity to do something. F
extinction /…™kЋИst…™≈Лk Г…Щn/: when a particular type of animal or plant stops existing
potential /p…ЩЋИten Г…Щl/: likely to develop into a particular type of person or thing in the future
breakthroughs: to manage to do something successfully when there is a difficulty that is preventing you
majestic /m…ЩЋИd Тest…™k/: very big, impressive, or beautiful
** 3еБЪйҐШ еЕ®еѓє
1-7  T F N
8-13 one word only
1. F
2. F
3. N
4. T
5. T
6. F
7. T
8. violent
9. tool
10. meat
11. photographer
12. game
13. frustration
