#+OPTIONS: \n:t num:nil html-postamble:nil
* task4: 精听+精读 听力
所⽤素材：
剑雅16 第⼀套真题听⼒第⼀题
1. 先听⽂章（⼀定不要先阅读听⼒脚本），答题，记录对错
2. 认真阅读听⼒脚本，标注所有⽣词（⽂中含义），语法（参考新概念英语及三本语法书），摘抄习惯⽤法（并造句）
3. 反复跟读edge或听⼒⾳频，⽆需熟读成诵，但请跟读到⾜够顺
畅。拿不准就跟读50遍。
4. 模拟考试，听⽂章，答题，记录对错。
5. 对⽐1&4 答题情况
6. 做完前5步，请思考并写下，【阅读与听⼒】的关系。
** 疑问
1. 学的音标是美音,听力是英音的该做什么?
2. 知道意思的习惯用法要不要抄?
3. + 跟读时会自己去记答案
** 阅读与听力的关系
阅读积攒单词,习惯用法,搞清楚语法.
听力的时候碰到这些才能更懂.
阅读是听力的基础,听力又比阅读多了语音.

今天下午我遇到了群外国人+中国人,让我帮忙拍照.
一时之间,我脑子里面涌现了海量的英语单词,但是我只说出来了.
	cheese, you're not inside, see you.
过后,我整个人虚脱了很久.
海量单词,我认为这是我跟其他老师新三学的.
但是他们是停留在我的脑子里面,意义知道的不是很清晰,也造不出来一句句子,我用不出来.
我也没有去practice口语.
就像一个自闭儿童,在学校学了再多中文,没有去说话,也是说不出来的.

** 一考
1. - 
	 F
2. tower
	 T
3. car
	 T
4. animals
	 T
5. bridge
	 T
6. 
	 F
7. delined
	 F
8.
	 F
9. Fradstone
	 T
10. ideas
		F
		
** 二考
all true
1. egg
2. tower
3. car
4. animals
5. bridge
6. movie
7. decorate
8. Wednesdays
9. Fradstone
10. parking

** Article
1: Hello. Children’s Engineering Workshops.

2: Oh hello.
I wanted some information about the workshops in the school holidays.

1: Sure.

2: I have two daughters who are interested.
The younger one’s Lydia, she’s four
– do you take children as young as that?

1: Yes, our Tiny Engineers workshop is for four to five-year-olds.

2: What sorts of activities do they do?

1: All sorts.
For example, they work together to design a special cover that goes round an egg,
	so that when it’s inside they can drop it from a height and it doesn’t break.
Well, sometimes it does break
	but that’s part of the fun!

2: Right. And Lydia loves building things.
Is there any opportunity for her to do that?

1: Well, they have a competition to see who can make the highest tower.
You’d be amazed how high they can go.

2: Right.

1: But they’re learning all the time as well as having fun.
For example, one thing they do is to design and build a car that’s attached to a balloon,
	and the force of the air in that actually powers the car
	and makes it move along.
They go really fast too.

2: OK, well, all this sounds perfect.

2: Now Carly, that’s my older daughter,
		has just had her seventh birthday,
	s	o presumably she’d be in a different group?

1: Yes, she’d be in the Junior Engineers.
That’s for children from six to eight.

2: And do they do the same sorts of activities?

1: Some are the same, but a bit more advanced.
So they work out how to build model vehicles, things like cars and trucks,
	but also how to construct animals using the same sorts of material and technique,
	and then they learn how they can program them and make them move.

2: So they learn a bit of coding?

1: They do.
They pick it up really quickly.
We’re there to help if they need it, but they learn from one another too.

2: Right. And do they have competitions too?

1: Yes, with the Junior Engineers,
	it’s to use recycled materials like card and wood to build a bridge,
		and the longest one gets a prize.

2: That sounds fun.
I wouldn’t mind doing that myself!

1: Then they have something a bit different,
	this is from Laokaoya website,
	which is to think up an idea for a five-minute movie and then film it,
	using special animation software.
You’d be amazed what they come up with.

2: And of course, that’s something they can put on their phone
	and take home to show all their friends.

1: Exactly.
And then they also build a robot in the shape of a human,
	and they decorate it
	and program it
		so that it can move its arms and legs.

2: Perfect.
	So, is it the same price as the Tiny Engineers?

1: It’s just a bit more: £50 for the five weeks

2: And are the classes on a Monday, too?

1: They used to be,
	but we found it didn’t give our staff enough time to clear up after the first workshop,
	so we moved them to Wednesdays.
The classes are held in the morning from ten to eleven.

2: OK. That’s better for me actually.
And what about the location?
Where exactly are the workshops held?

1: They’re in building 10A – there’s a big sign on the door,
	you can’t miss it,
	and that’s in Fradstone Industrial Estate.

2: Sorry?

1: Fradstone – that’s F-R-A-D-S-T-O-N-E

2: And that’s in Grasford, isn’t it?

1: Yes, up past the station.

2: And will I have any parking problems there?

1: No, there’s always plenty available.
So would you like to enrol Lydia and Carly now?

2: OK

1: So can I have your full name …

** 单词造句指南
- 网:v.+v.变化 情态动词+时态的转变
- 四句型转换
- 方式/地点/时间
- 结合其他习惯用法
- 其他单词+词性组合
- 原文摘抄+变

** words
- workshop: a room or building where tools and machines are used for making or repairing things
	1. What kinds of activities does the Children Engineering workshop have?
	2. How long did they clear up after the first workshop?
	3. What do you think of the activities after the first workshop?
- enrol: to officially arrange to join a school, university, or course, or to arrange for someone else to do this
	1. Harvard refused enrolling Jackie Ma ten times.
	2. He is ready to enroll his son.
	3. I enrolled in the course of IELTS 10 days ago.

** expression
- what sort of ...?
	1. What sorts of foods do they provide us?
	2. What sorts of cats are in the area?
	3. What sorts of temples are located on Mountain Feilai.
- work together to do sth.
	1. The team worked together to defeat EDG in a Lol race.
	2. The internet makes it possible for us to work together to achieve our goals.
	3. The search party worked together to reveal the secret.
- part of the fun
	1. Is that part of the fun?
	2. Why is that part of the fun?
	3. What is part of the fun?
- love doing
	1. I love swimming.
	2. I love swimming in the sea.
	3. My wife love watching Korean drama on weekends.
- all the time
	1. He is sitting on the chair all the time.
	2. He was sitting on the chair all the time yesterday.
	3. He is complaining about Rachel all the time.
- be to do
	1. I'm to go to the temple.
	2. She's to propose to Chandler tonight.
	3. I'm enrolling my daughter myself.
- be attached to sth
	1. The car is attached to balloon.
	2. The woman is staring at a cat that is attached to the tree.
	3. There is an ugly horse that is attached to the car.
- from six to eight
	1. The children from six to eight often take part in the junior engineers.
	2. The children from six to eight usually don't know how to swim.
	3. The children from six to eight are often not safe to walk alongside swimming pool alone.
- work out
	1. They work out how to achieve their goals and they do it.
	2. Reading the paper makes it possible for Mr. Leo to work out how to teach his students efficiently.
	3. They have worked out how to spend their holidays.
- pick it up
	1. Will we pick it up quickly?
	2. What will we pick up quickly?
	3. How will we pick it up?
- mind doing
	1. He doesn't mind kicking his wife's ass.
	2. Would you mind opening the door?
	3. He wouldn't mind giving strangers a lift.
- think up
	1. The activity is to think up an idea for taking care of a cat and then play with it.
	2. She thinks up an idea for swimming on a Sunday.
	3. She thinks up an idea for climbing on a Sunday so that her husband can lose his weight.
- come up with
	1. She came up with an idea for enrolling herself.
	2. She comes up with an idea for travelling herself.
	3. You must come up with some ideas for repairing the bike.
- the shape of a human
	1. They also build a robot in the shape of a cat.
	2. They are building a robot in the shape of a cat.
	3. They have built a robot in the shape of a cat.
- clear up
	1. It went wrong, for the reason that the data wasn't cleared up.
	2. I don't mind clearing it up.
	3. Monica must have cleared it up before she cooked.
- move sth. to st.
	1. Mr. Leo moved reading to morning.
	2. Why did Mr. Leo move reading to afternoon?
	3. It must have given the staff enough time to clear up
			after the boss moves the workshop to Wednesdays.
- up past the sp.
	1. The hospital is just up past the station.
	2. My wife wishes that she knew the hospital is just up past the station.
	3. Why is the workshop located up past the station.

** grammar
- in/at/on + 时间
- who...定语
- who ...宾从
- as ... as
- so that
- as ... 像
- how to
- would be
- how high they can go
- has done

