#+OPTIONS: \n:t num:nil html-postamble:nil

* task13-prereading 口语准备+写作复习
作业1：
汉语写作（可全英，或半英半汉）
1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。

作业2：与task12-prereading相同,但是由于完成比较高,这次只做改
读：
1. 审题+回顾评分标准
2. 泛读话题相关⽂章：总结内容+结构+表达
3. 精读⾼分范⽂（PDF⽂件） ：阅读内容+标记结构（句间+段内+段间+篇章outline）
3.5. 学习使⽤https://writing9.com （查找任意task1+task2真题范⽂）
练：
4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过
本步骤。
改：
5. 修改单词（同义词） +习惯⽤法+语法⼤结构（丰富程度）
6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。
6. 星座⼩组：共同准备，互相讨论，互相提供修改建议。


** 作业1：
汉语写作（可全英，或半英半汉）
*** 1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
口语=内容(输出)+结构(简单句与句的结构)+单词+习惯用法+语法(句子结构)+语音
阅读=内容(输入)+结构(句与句,段落的组织,段与段的转变,无意识地模仿)+单词+习惯用法+语法(句子结构+副词与介词)
听力=内容(输入)+结构(句与句,段落的组织,段与段的转变,无意识地模仿)+单词+习惯用法+语法(句子结构+副词与介词)+语音(语调(停顿)+语速+变音+音标+自然拼读法则,以句子为最小单位,不能割裂开来)
写作=内容(输出,但会倒逼泛读+泛听,形成输出倒逼输入)+结构(句与句,段落的组织,段与段的转变,有意识的模仿)+单词+习惯用法+语法(句子结构)

*** 2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
内容:1,
结构:2,
单词:3.1,
习惯用法:3.2,
语法:3.3,
语音:4
--------------------
- 单词造句 
	3
- Pattern Drill 写+读
	1,3+4
- 给自己讲解
	3.3
- 红皮书
	3.3
- 习惯用法造句
	3.2
- 跟读至背诵
	1+2+3+4
- Ask me if 写+读
	1+3+4
- 摘要写作
	1+2
- tell the story 口语
	1+2+3+4
- Topics for discussion
	1+2+3.1+3.2

*** 3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。
如何提升英语口语?
从英语口语What入手, 内容+结构+表达+语音
1. 内容方面,Topics for discussion 去大量泛读积累一些素材,尝试去写一些句子
2. 结构,不用过多准备,总分总.
3. 表达这个是大头
	 + 精读+精听,NCE2+3,红皮书,人在纽约
	 + 把之前学过的语法,整理出大语法结构,养成出句子的时候,用语法结构的习惯,搞清楚是什么意思,什么时候适合用,直到应用自如.
	 + 大量地泛读+泛听,reddit,wiki,附加值
4. 语音分为精听和泛听,精听NCE2+3,人在纽约,还有那些泛读中不太顺畅的文章.泛听注意不要只选标准英音或美音.
5. 等精读+精听NCE2+3后,付费去HelloTalk找外教上手.
6. 使用老外日常常用的词汇,让自己看到身边的物品,能够脑子里浮现英文
** 作业2：
*** DONE 1. 审题+回顾评分标准 -读
CLOSED: [2023-09-01 Fri 21:23]
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?
**** 评分标准
- 写作任务回应情况
	+ 全面地回应各部分写作任务
	+ 就写作任务中的问题, 提出充分展开的观点，并提出相关的、得以充分延伸的以及论据充分的论点
- 连贯与衔接
	+ 衔接手段运用自如，行文连贯
	+ 熟练地运用分段
- 词汇丰富程度
	+ 使用丰富的词汇，能自然地使用并掌握复杂的词汇特征:极少出现轻微错误，且仅属笔误
- 语法多样性及准确性
	+ 完全灵活且准确地运用丰富多样的语法结构;极少出现轻微错误，且仅属笔误
		
***** 内容
skimming+summary+outline
泛读+泛听

***** 结构
结构准备: 如何分段，段内如何组织(topic sentence),段间如何过渡n个段落如何排列，句子之间如何过渡，篇章的结构
常见结构
第一段:
复述题干主要内容(审题+复述) +提出自己的结论+支持的论点12
第二段:
论点1: topic sentences + details (例子+细节等)
第三段:
论点1:topic sentences + details (例子+细节等)
第四段:
重申+总结所有观点

***** 表达
表达准备: 单词+语法+习惯用法单词总量+同义词 (阅读听力口语) :精读(造句)+泛读
语法:整理大语法结构
	- 3大从句 (n.adj.adv.)
	- 非谓语 (to do & doing& done 定语状语)
	- 虚拟语气
	- 特殊句型(强调etc.)
	- 特殊结构(neednthave done +should have done etc)
	- 谓语结构(时态主动&时态被动&情态动词主动&情态动词被动&情态动词表推测)
		+ 时态主动
		+ 时态被动
		+ 情态动词主动
		+ 情态动词被动
		+ 情态动词表推测
习惯用法:如何摘抄+如何造句

*** DONE 2. 泛读话题相关⽂章：总结内容+结构+表达 -读
CLOSED: [2023-09-01 Fri 21:23]
1. Rehabilitation
2. Historical Designation
3. Curiosity
4. Connection
5. Save Money
Rehabilitation
Many older homes be stripped of their original charm
	and renovated to the "style of the moment" by previous owners.
By gaining an insight into a home's architectural timeline,
	have the ability to bring some of the original integrity and style.
Curiosity
the physical history of the house, the social history of the house
past occupants an so on...
Connection.
Discovering your roots and creating a connection with family bring personal meaning
	and emotional bond to so many.
Finding meaning through genealogy of the past owners of their old houses.
Save Money.
provide a better understanding of the condition of building materials, finishes, and utilities.
With this information, homeowners can develop a more accurate budget and timeline for major projects and regular maintenance.

Search the registry of deeds
 Go online to your local registrar’s website or visit the office in person to search for your property’s deed. 
The deed will list the name of the person they purchased the home from.
Contact previous owners
They can share what they know about the house’s history as well as memories of living there.
Explore the home and yard for clues
From the attic to the backyard, there may be a number of existing clues about the history of a home. previous owners may have left behind helpful personal items, such as photos, mementos, and newspaper articles in the attic, in the basement, or buried in the yard.

*** 3. 精读⾼分范⽂（PDF⽂件）：阅读内容+标记结构（句间+段内+段间+篇章outline） -读
*** 3.5. 学习使⽤https://writing9.com (查找任意task1+task2真题范⽂) -读
**** 3.5.1 band 8.5
*Nowadays*, citizens from several nations are being more curious about
	looking up stories of the places they own.
This writing will discuss
	reasons why landowners decide to have an interest in the buildings they live in
	and how they manage to have the information.

There are several reasons for this
	and one of the most preponderant points is
		that people want to make sure
			that they have houses
				which can make them feel safe and convenient to live in
					by knowing the possibility of natural disasters.
*For example*,
	owners will make some lists of floods or typhoons
		that might affect their buildings,
	therefore, they can try every possible way to minimise the effects
		and learn how to survive in particular situations.
*In addition*, individuals will consider the future economical prospect
	by knowing about the surrounding areas and their landmark prices.
*Therefore*, they can estimate the chance of selling their properties at a higher price
	resulting in gaining advantages for them. 

Buyers will have multiple methods of searching for the background of the house
	such as asking the previous owners or neighbourhood
		and surfing the internet to look up some information.
When buying flats or apartments,
	the majority of populations are asking about specifications of the landmarks to the seller or their neighbour
		in order to get the details.
*However*, if they could not ask anyone about it,
	they can also try to search up-to-date sources online.
Advanced technology like the Internet
	can accommodate many people to have useful knowledge including housing complex areas.

*In conclusion*, society is interested in finding out about the histories of the houses
	because they want to make sure that they choose the right places to live in the long term
		and when they decide to sell them in the future, they will gain profit from them.
*Furthermore*, they can also browse the internet
	or just ask the sellers for information about the buildings
	in order to get to know them better.

*** DONE 4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过本步骤。 -练
CLOSED: [2023-09-01 Fri 22:13]
换个方式抄原文,没有自己的观点
Rehabilitation
Save Money

contact previous owners
explore the home and yard for clues.
把2个原因和方式都写入总结

Nowadays, there are more and more increasing interest in researching the history of the houses people live in.
We will discuss the reason why people are interest in the past of resident
	and how they find out it.

What a great many of reasons!
One of most obvious points is that learning the history of their houses make it possible for them to rehabilitated.
Many older homes have been stripped of their original charm and renovated to the "style of the moment" by previous owners.
By gaining an insight into a house's architectural timeline, people was enabled to bring some of the original integrity and style of their houses.
In addition, the preponderant benefit of studying the history is to save money.
If you didn't know it well, you hadn't a good understanding of the condition of buildings materials, finishes, and utilities.
Without this information, a great many of costly surprises may be led to.

There are variety methods of searching for the experiences of the residences
	such as contacting previous owners or neighbors
		and exploring the attic and yard for clues.
When you ask previous owners or neighbors,
	they may be more likely to tell you more about what you want to.
Besides, exploring the attic and yard is often useful.
There are probably helpful personal items, such as photos, and newspaper articles in the attic, in the basement, or buried in the yard.

In conclusion, people become more and more interesting in finding out the history of the houses
	for reasons that they want to have the ability to rehabilitate them
		and save money while living in them.
Furthermore, residents can contact previous owners or neighbors
	and explore the attic and yard by themselves
	so that they acuqire a good knowledge of their houses.

*** DONE 5. 修改单词（同义词） +习惯⽤法+语法⼤结构（丰富程度） -改
CLOSED: [2023-09-04 Mon 09:57]
Nowadays, there are increasing interests in researching the history of the houses people live in.
We will discuss the reason why people are keen on the past of resident
	and how they figure out it.

What a great many of reasons!
One of most obvious points is that learning the history of their houses make it possible for them to rehabilitate.
Unfortunately, many older homes have been stripped of their original charm and renovated to the "style of the moment" by previous owners.
By gaining an insight into a house's architectural timeline, people was enabled to bring some of the original integrity and style of their houses.
In addition, the preponderant benefit of studying the history is to save money.
No one can disagree with the fact
	that if you don't find out the hostory,
		you can't have a good understanding of the condition of buildings materials, finishes, and utilities.
Without this information, you may cost more than what is expected to. 

There are variety methods of searching for the experiences of the residences
	such as contacting previous owners or neighbors
		and exploring the attic and yard for clues.
When you ask previous owners or neighbors,
	they may be more likely to tell you more about what you want.
Besides, exploring the attic and yard can be quite helpful.
There are potentially useful personal items, such as photos, and newspaper articles in the attic, in the basement, or buried in the yard.

In conclusion, people become more and more interesting in finding out the history of the houses
	for reasons that they want to have the ability to rehabilitate them
		and save money while living in them.
Furthermore, residents can contact previous owners or neighbors
	and explore the attic and yard by themselves
	so that they acuqire a good knowledge of their houses.

*** DONE 6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。 -改
CLOSED: [2023-09-04 Mon 10:24]
Nowadays, there are growing interests in researching the history of the houses people live in.
We will discuss the reasons why people are keen on the past of their residences
	and how they go about uncovering it.

People have numerous reasons to find out their home's history and one of most obvious points is that learning the history of their houses make it possible for them to rehabilitate for a better life.
Unfortunately, many older homes have been stripped of their original charm and renovated to the contemporary trends by previous owners.
By gaining an insight into a house's architectural timeline, people were enabled to bring some of the original integrity and style of their houses.
In my view, I want to learn about my home's history because it can tell me how to save money. 
No one can disagree with the fact
	that if you don't find out the history,
		you can't have a good understanding of the condition of buildings materials, finishes, and utilities.
Without this information, you may cost more than what is expected to. 

There are various methods of searching for the experiences of the residents
	such as contacting previous owners or neighbors
		and exploring the attic and yard for clues.
When you ask previous owners or neighbors,
	they may be more likely to tell you more about what you expect.
Besides, exploring the attic and yard can be quite helpful.
Potentially useful personal items, such as photos, and newspaper articles may appear in the attic, in the basement, or buried in the yard.

In conclusion, people become more and more interesting in finding out the history of the houses
	for reasons that they want to have the ability to rehabilitate them
		and save money while living in them.
Furthermore, residents can contact previous owners or neighbors
	and explore the attic and yard by themselves
	so that they acquire a good knowledge of their houses.
*** 7. 星座⼩组：共同准备，互相讨论，互相提供修改建议。 -改
