* task11-prereading

作业1： task2 ⼤作⽂
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?

读： 70%
1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
2. 泛读&泛听这个话题（尽量别看范⽂）
3. 随⼿记下新的内容+结构+表达
练： 20%
1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。（控制在500字左右，不限时间）
改： 10%
1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改，但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）
	 
** task10课上:为啥先教写作，而非口语?
写作=内容+结构+表达(单词~语法~习惯用法)
口语=内容+结构+表达(单词~语法~习惯用法)+语音(连读~语调~变音~自然拼读法则~音标)
从这方面可以认为写作是口语的基础.
而且写作的反复修改可以使人变得精确,更加的有逻辑性.由此带来的好处是口语更有逻辑性,不至于前言不搭后语.

** 读： 70%
1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
2. 泛读&泛听这个话题（尽量别看范⽂）
3. 随⼿记下新的内容+结构+表达

** 练： 20%
1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。（控制在500字左右，不限时间）

** 改： 10%
1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改，但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）

	 
** Benefits of Researching a Home’s History drift
Our old house turned 100 years old in 2016. 
Throw it a birthday party.
The motivation for me to research.
1. Rehabilitation.
2. Historical Designation.
3. Curiosity.
4. Connection.
5. Save money.
are practical and show tangible results.
possess a more emotional flavor.
am still in the process of learning.
gather information
piece together story.
embrace its quirks
*** 1. Rehabilitation
be strippped of
be renovated to

infuse historical charm back into their old houses
discover the timeline of their ol house
unearth original configuration and architectural details
What changed in the house over time?
Have the rooms always been in same place

gain an insight into
have the ability to
bring back
be cognizant that ...
be quite different as further detailed in ...
combine modern conveniences while still retaining their home's historic character
has modern conveniences with sth.
*** 2. Historic Designation
determine it's eligibility for a formal historic designation
a variety of historic designations through local, state, and national levels

demonstrate a significant connection to history, person, or architecture

uncover its role in history or culture

- Financial incentives via tax-credits
- Technical assistance from experts
- Special exemptions from building codes
*** 3. Curiosity
be plain inquisitive about
be curios about the physical aspects of the house
come across something weird during you renovations

The past occupations.
accomplishment
occupations
*** 4. Connection
Genealogy
Discovering your roots and create a connection with family
apply the same approach to finding meaning through genealogy of the past owners of their old houses
provide people with a sense of being part of a continuum, psychologically and emotionally healthy
give meaning to the present and future
*** 5 save money
provides a better understanding of the condition of building material, finishes, and utilities
electrical system update
asbestos or lead-based paint is still present.

lead to costly surprises
develop a proactive strategy
develop a more accurate budget and timeline for major projects and regular maintenance
let's face it, nobody wants to be in that situation
