#+OPTIONS: \n:t num:nil html-postamble:nil
* task10-prereading
雅思写作教学框架:
1.写作与阅读&听力的关系
2.如何提升写作能力?
3.雅思托福考试相关: 题型，评分标准，备考建议etc.

Task10 课前作业
材料:《葛传梨英文写作》
教学目标:
1.理解写作与阅读&听力的关系
2.理解写作包含哪些内容?
3.理解如何提升写作能力?
家庭作业:
1. 结合之前所有课程，汉语书写[写作与阅读&听力] 的关系
2. 泛读如下节选自《葛传英文写作》一书中的内容 (pdf文件) ，并用1-3句话总结 (可以用汉语) 每个篇章的核心内容。
	 1. 练习: skimming + summary，体验输出倒逼输入
	 2. 可以借助汉语: 直接全面先翻译成汉语并阅读
	 3. 边阅读思考《葛传梨英文写作》一书中的内容，边思考我的NCE23中，哪些环节对于提升英语写作是有帮助的，以及为什么?
	 4. [选修] 阅读张中行先生《作文杂谈》一书中“什么是作文”一文。感受下来自母语的铁拳暴击。

** 结合之前所有课程，汉语书写[写作与阅读&听力] 的关系
阅读和听力是写作的基础.
阅读和听力是输入,写作是输出.
阅读分为精读和泛读.精读可以积攒单词~习惯用法~语法,而写作需要这些.泛读大量积攒单词,积攒一些内容,和行文的结构.
单词不必多解释.内容的话脑中有东西,才能有话讲.行文结构,看别人这样多了,自己也会跟着模仿.
听力分为精听+泛听,精听是在加强单词~习惯用法~语法~内容和行为结构,事实上比精读更进一步做了加强.泛听和泛读类似.

** 泛读如下节选自《葛传英文写作》一书中的内容 (pdf文件) ，并用1-3句话总结 (可以用汉语) 每个篇章的核心内容。
*** 练习: skimming + summary，体验输出倒逼输入
完成

*** 可以借助汉语: 直接全面先翻译成汉语并阅读

*** 边阅读思考《葛传梨英文写作》一书中的内容，边思考我的NCE23中，哪些环节对于提升英语写作是有帮助的，以及为什么?
1. 单词造句
	 模仿性地造句,可以为写作积累素材.
2. 习惯用法造句
	 模仿性地造句,可以为写作积累素材.
3. 跟读
	 反复阅读,内化了单词和习惯用法
4. 摘要写作
	 提炼了原文,可以更好地看到有经验的作家是怎么组织自己的想法的.
5. Tell the story
	 同义转化,可以练就自己简单且清晰表达的能力
6. Topics for discussion
	 直接就联系写作了.从捕捉观点到,到大纲,再到写作的练习.

*** [选修] 阅读张中行先生《作文杂谈》一书中“什么是作文”一文。感受下来自母语的铁拳暴击。

** questions
1. 材料本身短,1-3句太多,感觉像翻译了.

** 材料
20. Something to Say.
Composition, as has been said in Section 1, is the art or practice of writing.
In other words, it is the art or practice of saying something in written words.
When nothing is to be said, no composition is possible.
You simply cannot learn composition if you always have nothing to say.
Since you are bent upon learning it, you must find something to say.
This finding is necessary to practice in composition.
When you come to think about it, it is not at all difficult to find something to say.
You may find it from a great many sources,
	the most common of which are perhaps personal experience, observation, conversation, and reading.
Of course you have occasion to speak and write the Han language every day.
Just ask yourself the question "How shall I say it in English?",
	and you will find something for practice in English composition.
You will find far more material than you have time for every day.”
Skimming + Summary：
要说些什么?
个人经验~观察~对话和阅读都是素材.日常生活中用汉语说的,换成英语来,这样每天就有很多材料了.
6

21. How to Say It.
Your question is not what to say but how to say it.
You may often have an idea or a thought that you do not know how to express.
For instance, you may not be able to express the idea of the glass tube	measuring temperature
	if you do not happen to know the word "thermometer".
To take another example, suppose you wish to apply for a position by letter but you cannot do so.
Now suppose you ask a friend to write the letter for you, and he writes it.
You read it and understand it all right.
You come to realize that you did not think of arranging those simple words in that simple order.
You did have something to say, but you did not know how to say it!
Hence the importance of studying composition.
Skimming + Summary：
怎么去说?
不会写信让朋友帮写,看了朋友的信,发现自己没有想过把简单的单词用简单的顺序组合起来.
这就是学习写作的重要性.
6

22. A Consolation.
I take it for granted that when you ask yourself the question
	"How shall I say it in English?", you often find that you cannot.
Well, let me give you a word of consolation.
Even experienced writers may sometimes find that they cannot say something that they wish to say.
As you are merely a young Chinese student of English,
	what cause have you to feel disappointed?
Skimming + Summary：
小安慰:
	即使是有经验的作家,有时候也说不出自己想说的,何况你仅仅是个中国学生,有什么理由失望.

23. Others May Have Said It before You.
As a matter of fact, many of the ideas and thoughts you often have occasion to express
	have already been expressed by others before you.
Read any page in any book carefully,
	and you will perhaps find some expressions that will help you to say things.
Many of such expressions may seem to you to be too simple to deserve much attention,
	but you cannot invent them, nor can you use them unless you have noted them.
There appear to be many Chinese students
	who have read a number of books on grammar and composition and done many exercises
		in correcting and improving sentences and yet cannot write even tolerable English.
The trouble is that they may either have not read widely enough or have not read carefully enough.”
Skimming + Summary：
其他人可能比你说的早:
中国学生,学了一堆语法和组合的书,经常不能说出蹩脚的英语.
原因是读得不够仔细,不够多.
书中有大量的表达,而你既不能自己创造,没有做好笔记又不能使用.


24. What to Read.
Since it is for the purpose of learning composition that you read,
	and since it is in present-day English prose that you ought to learn to express yourself,
	what you read must be present-day English prose.
Expressions in common use a hundred years ago may not be so at the present day.
Likewise, expressions in common use in verse may not be so in prose.
The term "present-day English prose", however, requires qualification here.
Since it is in standard English that you ought to learn to express yourself,
	what you read must not contain too much slang,
	whatever significance one may attach to the word.
Again, since it is things in everyday life that you ought to learn to write about,
	what you read must not be of a technical character.
One limitation more.
What you read must be fairly easy for you;
	too much time and energy spent in reading between the lines
	and finding out all kinds of references
	and allusions would very likely distract your mind from your purpose,
		which is to	learn English composition.
Skimming + Summary：
读什么.
读现代英语白话文,不要读那些口号过多的.
读那些跟你日常相关的,对你来说足够简单,太难会转移你学英语组合的注意力.

25. How to Read.
As you may have gathered from the above,
	in reading to learn English composition,
	you ought to regard the language as the main thing.
To quote from my A Word to the Wise:
	"When you read a story in English, do you read it for the story or for the English?
	This is a question that is not so foolish as it may seem.
	For I find that many students of English pay far more attention to the story
		than to the English.
They read and enjoy and for a long time afterwards remember the story,
	but do not care to study the use of words and phrases in it.
For instance, they cherish the memory of how the mystery of the eternal triangle is solved,
	but do not remember a single sentence in the story and cannot tell
		what preposition is used before or after a certain word in the speech of a certain character.”
Of course, it is all right to read and enjoy and remember a story,
	and so long as one wants to know the story only,
		one need not bother about the language.
But the case is quite different with a student of English.
I mean a student of English as distinguished from a student of stories
	or what is called the general reader”.
As you may also have gathered from the above, you ought to read very carefully.
Not only very carefully but also aloud,
	and that again and again till you know the passage by heart.
Skimming + Summary：
怎么阅读:
作为英语学习者,别光读故事.
要仔细的读里面的单词和习语,而且要反复朗读,知道内化这些单词和习语.
3

27. Self-cultivation.
Though it is not on the assumption
	that you are a self-taught student
	that I am writing this book,
	yet I have to point out that when it comes to reading with a view to learning composition,
	you ought to treat the matter as a form of self-cultivation.
The five selections in the above exercise are by no means
	all that you ought to read in the way indicated.
Nor should you confine yourself to what American teachers call "assignments".
Nor should you regard the reading as something to be done in a composition class.
Fortunately there is no lack of material
	in these days of easy access to various kinds of publications.
Your teacher is of course expected to be both able
	and willing to advise you in the choice of material.
Skimming + Summary：
自我修养:
	你不该把阅读看作是作业,也不应该当作组合课堂里的必须完成的事.
	把广泛且带学组合的视角去阅读当作自我修养.


28. Writing from Memory.
A very helpful exercise in composition is to write a passage from memory
	and correct your work in strict accordance with the passage.
This is tantamount to getting the author of that passage to correct your work.
Incidentally, you will do well to try this exercise in reading any passage
	just before you feel you can recite it correctly.
Skimming + Summary：
根据记忆写作:
	根据记忆写作,然后改正的自己的写作.
	这个练习要做到,你感觉任何短文看过之后都能正确复述出来.
5


29. Imitation, Conscious and Unconscious. （赶紧想想我们的NCE23+泛读）
The careful reading of suitable present-day English prose will help you
	in learning composition through imitation,
		which is either conscious or unconscious.
Things unconscious cannot be taught, of course.
Conscious imitation, however, is well worth discussing as an aid to composition.
Take the first sentence in the first selection in Exercise 1:
	"The Outline of History proved an extremely successful book",
	where the verb "proved" is a copulative one having "book" as its complement.
Now you may write as many sentences as you can in imitation of this single sentence; thus:
	1. The old man proved the father of the young man.
	2. The story proved true.
	3. The experiment proved a success.
	4. This book will prove very helpful to you.
	…
Skimming + Summary：
模仿~有意识和无意识:
	学习组合可以通过有意或无意的模仿.
	无意当然不用说了,有意地比如对于某个单词,模仿性地造句.
NCE23:
	有意识,造句,模仿,造句指南 v+v变化,四句型转化,how/where/when,结合其他习惯用法, 其他单词+词性,原文+变
泛读:
	无意识地模仿
1,2

31. Expressing Another Person's Thoughts.
Expressing another person's thoughts is a valuable training in English composition
	both because you may sometimes have occasion to do so
	and because it will help you to express your own.
The thoughts are there for you to express:
	there is something to say.
Besides, there are often some words and phrases for you to use.
Skimming + Summary：
表达其他人的想法:
	表达其他人的想法对你来讲也是很好的练习.
	有一些东西需要去说,同时也有单词和习语需要去用.

32. Paraphrasing Sentences.
Paraphrasing is a simple form of expressing another person’s thoughts.
It means giving the meaning of a passage in other words,
	that is, giving it a simpler and clearer expression.
It may be called close reproduction or close retelling.
But it is not mere substitution of words, nor mere sentence transformation.
Skimming + Summary：
同义句:
	同义句就是用更简单清楚的句子表达原先的意思.
	但是不仅仅是单词缩简一下,或者句式转换一下.

33. Suggestions for Paraphrasing.
In order to paraphrase well, it is necessary to follow a few simple suggestions:
	1. Study the passage carefully to get a thorough grasp of its meaning.
		 You can never paraphrase anything that you do not fully understand.
	2. Try to express the meaning in the simplest and clearest manner you can.
		 You may use any word or phrase in the original that you find simple and clear enough;
			do not avoid any word or phrase merely because it is in the original.
		 Similarly, while it is anything but necessary to follow the construction of the original,
		  it is not advisable to change merely for the sake of a change.
		 It is often better to paraphrase a sentence in two or more sentences.
	3. Get rid of all figurative language.
	4. Paraphrase a passage in as many ways as you can
			till you come to what you consider the best way.
		Though you may not be able to write such good English as the original,
			yet you ought to aim at doing so — remembering, however,
			that you must express the meaning in a simpler and clearer manner.
Skimming + Summary：
同义转化的建议:
	1. 仔细理解短文的意思
	2. 尽全力表达更简单和清楚,遵循原本的结构,造2-3个.
	3. 别修辞
	4. 多用几种方式对短文同义转化,直到你觉得那是最好的.
--------------------
36. Condensing.
Condensing is another form of expressing another person's thoughts.
It means giving the meaning of a passage, a story, an essay, a poem, or even a whole book,
	in one or more sentences.
It may be called summarizing, abstract-writing, or précis-writing.
Skimming + Summary：
压缩:
	用一句话或者多句话表示短文的意思,也叫总结~抽象
4

38. Suggestions for Condensing.
Below are some simple suggestions for condensing:
	1. Study the original carefully to get a thorough grasp or its meaning.
	2. Pick out the main points, and leave out all unnecessary points.
	3. If possible, arrange the points in the condensation in the same order as in the original.
	4. Unless the original is a short passage,
	  you had better write the main points down instead of merely picking them out mentally,
	  and arrange them in something like an outline.
	 This note-taking and outline-making will prepare you for original composition.
	 They will be treated further on in this chapter.
Skimming + Summary：
关于压缩的建议:
	1. 仔细学习理解主旨和意思
	2. 找出主要点,抛弃不要紧点
	3. 可以的话,把缩写点按原文顺序排列
	4. 不是的短文,有必要写下来,把他们做成大纲.
	记笔记和弄大纲为你准备原始的composition
Expressing your own ideas
	还可以靠自己去总结,不单单依赖文中的句子.

42. Choosing a Subject.
Composition is saying something about something.
This latter something is the subject. …
Skimming + Summary：
选个科目:
	写作就是说一些A关于B,B就是科目.

44. Taking Notes.
When you have chosen a subject, think about it hard.
Ideas will come into your mind.
Take a note of each as it comes.
The ideas are likely to come in a confusing manner:
	some may overlap, some may be unimportant, some may he irrelevant,
	some may be indefinite.
Never mind.
Note them all down.
Catch them before they may escape.
Do not stop until no more ideas come.
Suppose your subject is your family (whatever your title may be).
Such ideas as the following may come into your mind:
	1. My father.
	2. My mother.
	3. My brothers.
	4. My sisters.
	5. My grandfather, dead since 1939.
	6. My grandmother, an invalid, dead since 1937.
	7. My uncle, a widower since 1967.
	8. My aunt, an old maid.
	9. A distant relation, having been living with us for nearly twenty years.
	10. A cat and a dog.
	11. Recent removal into a new house.
	12. A small garden.
	13. Pleasant surroundings.
	14.Mutual love among all members of my family.
	15. Occasional tiffs between my younger brother and younger sister.
	16. Not rich, but nothing to worry about.
	17. My father's hobby.
Skimming + Summary：
做笔记:
记笔记:
	选个科目后,脑子想到什么记什么,不管有用没用,相关还是不相关
	

45. Making an Outline.
When you have taken enough notes about your subject,
	consider each to see whether it is closely connected with your subject.
The answer to this question depends partly upon how long your composition is to be. …
Skimming + Summary：
做大纲:
	捕捉想法后,看每个想法是否和主题相关,并且根据篇幅来做选择.

47. Making Outlines of What You Read.
Making outlines of what you read is a valuable training in making outlines;
	for it shows you how experienced writers arrange their ideas.
Skimming + Summary：
把读的做大纲:
	可以让你看到有经验的作家是怎么组织他们的想法.

48. Expanding an Outline.
When you have finished your outline,
	expand it into a composition,
	that is, do the actual writing.
You may be able to do it at a sitting,
	or you may have to stop from time to time.
In either case, you will do well to follow the following suggestions:
1. Do something more than merely expanding each point in your outline into a complete sentence.
	 Additional ideas are often necessary.
2. Do not follow your outline slavishly
	 if you find it desirable or necessary to make any omission or addition or alteration or adaptation.
3. As a rule expand each main point in your outline into a paragraph.
4. Consult one or more dictionaries as often as you need.
5. Do not drag in any word or idiom just to show off your knowledge of it. (注意思考)
6. Revise your work very carefully.
	 Do not be content with anything short of your best.
Skimming + Summary：
扩展大纲:
	1. 别一个点一句话,附加点经常很必要
	2. 别完全按大纲,增删改都正常
	3. 扩展一个主要观点为一个段落
	4. 查多个字典
	5. 别卖弄单词和习语
	6. 仔细检查
--------------------
224. What is a Paragraph? (认真思考，下⽂答案并不明晰，但是答案本身对提升写作分数帮助巨⼤)
A paragraph may be defined as a distinct part or section of any piece of writing,
	whether of one or more sentences,
	that deals with a particular point of the subject.
It is to a sentence what a sentence is to a word.
The term is also applied to a short composition
	consisting of a group of sentences dealing with a single topic
	and closely related to each other, such as a leaderette（这个单词不会，影响您理解整段⽂字梗概么？）in a newspaper.
Skimming + Summary：
啥是段落:
	段落是文章中单独的一小块,处理科目的一个点.
	段落之于句子就像句子之于单词.
	也被,几句话用在短文中处理单独主题,但是互相紧密联系.
--------------------
不影响
226. Paragraphs and Outline.
The third suggestion given in Section 48 on expanding an outline into a composition is:
	"As a rule expand each main point in your outline into a paragraph".
When you have made an outline carefully, therefore, you ought to have little difficulty in paragraphing.
Skimming + Summary：
段落和大纲:
	认真制作大纲的话,你搞段落就只有一点小困难了.
	

227. Topic Sentence. （可以回想polar bear 或者 ⻄⽅⽂明简史第三章的某些内容思考）
The main point to which a paragraph confines itself is called the topic,
	and when the topic is definitely stated in one of the sentences in the paragraph,
	that sentence is called the topic sentence.
It must not be supposed, however,
	that every paragraph must have a topic sentence.
While in a paragraph of exposition or argument the topic is as a rule definitely stated in a sentence,
	it is, in a paragraph of narration or description,
		usually implied father than stated.
The topic sentence occurs usually at the beginning of the paragraph,
	but sometimes at the end and sometimes in the middle.
Occasionally the topic is stated at or near the beginning and repeated,
	in different words, at or near the end.
Skimming + Summary：
主题句:
	表述整个段落的句子叫主题句,所有的段落都有主题句.有时候是暗示,而不是直接列出来.
	通常行文开始,或结束,有时候也在正中间,或者反复强调的句子.
	

229. Qualities of a Good Paragraph.
A paragraph should possess unity, coherence, and emphasis.
Unity, which is the fundamental quality, can be secured by sticking to the topic.
This is not difficult when you have a carefully made outline to follow.
Coherence can be secured by the use of connecting words
	and phrases and the avoidance of successive short sentences.
Emphasis can be secured by writing the topic sentence at the beginning
	or at the end, by giving more space to the central idea, and …
Skimming + Summary：
好段落的要点:
	一个段落应该有统一性,连贯性和强调点.
	统一性,小心按大纲就没问题.
	连贯性,用紧密联系的词和习语,避免用太多的短句.
	强调句,确定在文章开始和结束写主题句.


230. Transition between Paragraphs.
The transition between paragraphs should, needless to say, be as easy and smooth as possible,
	so that the reader will feel no break of thought but merely a natural step forward.
This result can usually be accomplished by the use of connecting words and phrases
	at the beginning of paragraphs.
Skimming + Summary：
段与段的转变:
	应该尽可能的平滑和简单.通常可以被相关联的词和习语联系起来.

以下篇章取⾃张中⾏先⽣《作⽂杂谈》⼀书
** summary
要说些什么?
个人经验~观察~对话和阅读都是素材.日常生活中用汉语说的,换成英语来,这样每天就有很多材料了.

怎么去说?
不会写信让朋友帮写,看了朋友的信,发现自己没有想过把简单的单词用简单的顺序组合起来.
这就是学习写作的重要性.

小安慰:
	即使是有经验的作家,有时候也说不出自己想说的,何况你仅仅是个中国学生,有什么理由失望.

其他人可能比你说的早:
中国学生,学了一堆语法和组合的书,经常不能说出蹩脚的英语.
原因是读得不够仔细,不够多.
书中有大量的表达,而你既不能自己创造,没有做好笔记又不能使用.

读什么.
读现代英语白话文,不要读那些口号过多的.
读那些跟你日常相关的,对你来说足够简单,太难会转移你学英语组合的注意力.

怎么阅读:
作为英语学习者,别光读故事.
要仔细的读里面的单词和习语,而且要反复朗读,知道内化这些单词和习语.

自我修养:
	你不该把阅读看作是作业,也不应该当作组合课堂里的必须完成的事.
	把广泛且带学组合的视角去阅读当作自我修养.
		
根据记忆写作:
	根据记忆写作,然后改正的自己的写作.
	这个练习要做到,你感觉任何短文看过之后都能正确复述出来.

模仿~有意识和无意识:
	学习组合可以通过有意或无意的模仿.
	无意当然不用说了,有意地比如对于某个单词,模仿性地造句.

表达其他人的想法:
	表达其他人的想法对你来讲也是很好的练习.
	有一些东西需要去说,同时也有单词和习语需要去用.

同义句:
	同义句就是用更简单清楚的句子表达原先的意思.
	但是不仅仅是单词缩简一下,或者句式转换一下.
同义转化的建议:
	1. 仔细理解短文的意思
	2. 尽全力表达更简单和清楚,遵循原本的结构,造2-3个.
	3. 别修辞
	4. 多用几种方式对短文同义转化,直到你觉得那是最好的.
			
压缩:
	用一句话或者多句话表示短文的意思,也叫总结~抽象
关于压缩的建议:
	1. 仔细学习理解主旨和意思
	2. 找出主要点,抛弃不要紧点
	3. 可以的话,把缩写点按原文顺序排列
	4. 不是的短文,有必要写下来,把他们做成大纲.
	记笔记和弄大纲为你准备原始的composition

	
选个科目:
	写作就是说一些A关于B,B就是科目.
记笔记:
	选个科目后,脑子想到什么记什么,不管有用没用,相关还是不相关
做大纲:
	捕捉想法后,看每个想法是否和主题相关,并且根据篇幅来做选择.
把读的做大纲:
	可以让你看到有经验的作家是怎么组织他们的想法.
扩展大纲:
	1. 别一个点一句话,附加点经常很必要
	2. 别完全按大纲,增删改都正常
	3. 扩展一个主要观点为一个段落
	4. 查多个字典
	5. 别卖弄单词和习语
	6. 仔细检查
啥是段落:
	段落是文章中单独的一小块,处理科目的一个点.
	段落之于句子就像句子之于单词.
	也被,几句话用在短文中处理单独主题,但是互相紧密联系.
段落和大纲:
	认真制作大纲的话,你搞段落就只有一点小困难了.
主题句:
	表述整个段落的句子叫主题句,所有的段落都有主题句.有时候是暗示,而不是直接列出来.
	通常行文开始,或结束,有时候也在正中间,或者反复强调的句子.
好段落的要点:
	一个段落应该有统一性,连贯性和强调点.
	统一性,小心按大纲就没问题.
	连贯性,用紧密联系的词和习语,避免用太多的短句.
	强调句,确定在文章开始和结束写主题句.
段与段的转变:
	应该尽可能的平滑和简单.通常可以被相关联的词和习语联系起来.
