* task12-prereading 写作2

作业1：
读：
1. 审题+回顾评分标准
2. 泛读话题相关⽂章：总结内容+结构+表达
3. 精读⾼分范⽂（PDF⽂件） ：阅读内容+标记结构（句间+段内+段间+篇章outline）
3.5. 学习使⽤https://writing9.com （查找任意task1+task2真题范⽂）
练：
4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过
本步骤。
改：
5. 修改单词（同义词） +习惯⽤法+语法⼤结构（丰富程度）
6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。
6. 星座⼩组：共同准备，互相讨论，互相提供修改建议。

作业2:
A类 G类 Task1:更简单粗暴的备考⽅案
1. 审题+精读范⽂=内容+结构+表达
2. 动笔写，即模考（前中后）
托福 Task1:更简单粗暴的备考⽅案
1. 审题=精读阅读材料（练习skimming） +精听听⼒脚本（练习take notes）
2. 精读范⽂=内容+结构+表达
3. 动笔写，即模考（前中后）
参考上⾯的⽅案：
1. 按考试类别，阅读3道真题的⾼分范⽂，并分析【结构】与【内容】

作业3：
汉语写作（可全英，或半英半汉）
1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。

** 课堂作业 整理语法大结构
语法大结构:
	- 3大从句 (n.adj.adv.)
	- 非谓语 (to do & doing& done 定语状语)
	- 虚拟语气
	- 特殊句型(强调etc,主语从句)
	- 特殊结构(needn't have done + should have done etc.)
	- 谓语结构 (时态主动&时态被动&情态动词主动&情态动词被动&情态动词表推测)

** 作业1：
*** 1. 审题+回顾评分标准 -读
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?
**** 评分标准
- 写作任务回应情况
	+ 全面地回应各部分写作任务
	+ 就写作任务中的问题, 提出充分展开的观点，并提出相关的、得以充分延伸的以及论据充分的论点
- 连贯与衔接
	+ 衔接手段运用自如，行文连贯
	+ 熟练地运用分段
- 词汇丰富程度
	+ 使用丰富的词汇，能自然地使用并掌握复杂的词汇特征:极少出现轻微错误，且仅属笔误
- 语法多样性及准确性
	+ 完全灵活且准确地运用丰富多样的语法结构;极少出现轻微错误，且仅属笔误
		
***** 内容
skimming+summary+outline
泛读+泛听

***** 结构
结构准备: 如何分段，段内如何组织(topic sentence),段间如何过渡n个段落如何排列，句子之间如何过渡，篇章的结构
常见结构
第一段:
复述题干主要内容(审题+复述) +提出自己的结论+支持的论点12
第二段:
论点1: topic sentences + details (例子+细节等)
第三段:
论点1:topic sentences + details (例子+细节等)
第四段:
重申+总结所有观点

***** 表达
表达准备: 单词+语法+习惯用法单词总量+同义词 (阅读听力口语) :精读(造句)+泛读
语法:整理大语法结构
	- 3大从句 (n.adj.adv.)
	- 非谓语 (to do & doing& done 定语状语)
	- 虚拟语气
	- 特殊句型(强调etc.)
	- 特殊结构(neednthave done +should have done etc)
	- 谓语结构(时态主动&时态被动&情态动词主动&情态动词被动&情态动词表推测)
		+ 时态主动
		+ 时态被动
		+ 情态动词主动
		+ 情态动词被动
		+ 情态动词表推测
习惯用法:如何摘抄+如何造句

*** 2. 泛读话题相关⽂章：总结内容+结构+表达 -读
1. Rehabilitation
2. Historical Designation
3. Curiosity
4. Connection
5. Save Money
Rehabilitation
Many older homes be stripped of their original charm
	and renovated to the "style of the moment" by previous owners.
By gaining an insight into a home's architectural timeline,
	have the ability to bring some of the original integrity and style.
Curiosity
the physical history of the house, the social history of the house
past occupants an so on...
Connection.
Discovering your roots and creating a connection with family bring personal meaning
	and emotional bond to so many.
Finding meaning through genealogy of the past owners of their old houses.
Save Money.
provide a better understanding of the condition of building materials, finishes, and utilities.
With this information, homeowners can develop a more accurate budget and timeline for major projects and regular maintenance.

Search the registry of deeds
 Go online to your local registrar’s website or visit the office in person to search for your property’s deed. 
The deed will list the name of the person they purchased the home from.
Contact previous owners
They can share what they know about the house’s history as well as memories of living there.
Explore the home and yard for clues
From the attic to the backyard, there may be a number of existing clues about the history of a home. previous owners may have left behind helpful personal items, such as photos, mementos, and newspaper articles in the attic, in the basement, or buried in the yard.


*** 3. 精读⾼分范⽂（PDF⽂件）：阅读内容+标记结构（句间+段内+段间+篇章outline） -读

*** 3.5. 学习使⽤https://writing9.com (查找任意task1+task2真题范⽂) -读
**** 3.5.1 band 8.5
*Nowadays*, citizens from several nations are being more curious about looking up stories of the places they own.
This writing will discuss reasons why landowners decide to have an interest in the buildings they live in and how they manage to have the information.

There are several reasons for this and one of the most preponderant points is that people want to make sure that they have houses which can make them feel safe and convenient to live in by knowing the possibility of natural disasters.
*For example*, owners will make some lists of floods or typhoons that might affect their buildings, therefore, they can try every possible way to minimise the effects and learn how to survive in particular situations.
*In addition*, individuals will consider the future economical prospect by knowing about the surrounding areas and their landmark prices.
*Therefore*, they can estimate the chance of selling their properties at a higher price resulting in gaining advantages for them. 

Buyers will have multiple methods of searching for the background of the house such as asking the previous owners or neighbourhood and surfing the internet to look up some information.
When buying flats or apartments, the majority of populations are asking about specifications of the landmarks to the seller or their neighbour in order to get the details.
*However*, if they could not ask anyone about it, they can also try to search up-to-date sources online.
Advanced technology like the Internet can accommodate many people to have useful knowledge including housing complex areas.

*In conclusion*, society is interested in finding out about the histories of the houses because they want to make sure that they choose the right places to live in the long term and when they decide to sell them in the future, they will gain profit from them.
*Furthermore*, they can also browse the internet or just ask the sellers for information about the buildings in order to get to know them better.

*** 4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过本步骤。 -练
*** 5. 修改单词（同义词） +习惯⽤法+语法⼤结构（丰富程度） -改
*** 6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。 -改
*** 7. 星座⼩组：共同准备，互相讨论，互相提供修改建议。 -改

** 作业2:
A类 G类 Task1:更简单粗暴的备考⽅案
1. 审题+精读范⽂=内容+结构+表达
2. 动笔写，即模考（前中后）
托福 Task1:更简单粗暴的备考⽅案
1. 审题=精读阅读材料（练习skimming） +精听听⼒脚本（练习take notes）
2. 精读范⽂=内容+结构+表达
3. 动笔写，即模考（前中后）
参考上⾯的⽅案：
*** 1. 按考试类别，阅读3道真题的⾼分范⽂，并分析【结构】与【内容】

** 作业3：
汉语写作（可全英，或半英半汉）
*** 1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
*** 2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
*** 3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。
