#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* task7-prereading
家庭作业:
材料:剑雅16真题第一套
1. [必修] 剑雅16真题，三篇阅读文章，只看题型。
	请总结考的是什么题型，尝试总结考察的抽象能力sub-skills是什么?
	 1. 剑雅阅读体型是什么?
			判断~单选~多选~填空~配对
	 2. 考察的subskills是什么?
			- 同义词
			- 理解
			- 复述
			- 总结
2. [必修]精读第一篇文章 why we need to protect polarbears
	 - 千万别做题
	 - 标记全文语法+生词+习惯用法 (是否造句自选)
3.[必修]无需跟读，但反复阅读50遍+做题 (查看正确率)
4.[选修] 阅读”Meditation for Dummies”一书中“FollowingYour Breath”一文。
	可以查阅冥想的好处，bing，咕咕咕。
	写作&口语内容准备task0.5

** questions
1. 题目出现看不懂怎么办?
** 1
*** R1: 1-13
1-7: 7 判断题
	- TRUE
	- FALSE
	- NOT GIVEN
	同义词转换+理解
8-13: 6 填空题
	复述能力
*** R2: 14-26
14-20:7 配对标题题
	复述+总结
21-24:4 填空题
	理解+总结
25-26:2 多选
	理解+总结
*** R3: 27-40
27-30: 4 单选
31-34: 4 填空
	复述+总结
35-40: 6 选择
	理解
** 2. Why we need protect polar bears?
Polar bears are being increasingly threatened by the effects of climate change,
	but their disappearance could have *far-reaching* consequences.
They are uniquely adapted to the extreme conditions of the Arctic Circle,
	where temperatures can reach -40°C.
One reason for this is that they have up to 11 centimetres of fat underneath their skin.
Humans with comparative levels of adipose tissue would be considered obese
	and would be likely to suffer from diabetes and heart disease.
Yet the polar bear experiences no such consequences.

A 2014 study by Shi Ping Liu and colleagues sheds light on this mystery.
They compared the genetic structure of polar bears with
	that of their closest relatives from a warmer climate, the brown bears.
This allowed them to determine the genes
	that have allowed polar bears to survive in one of the toughest environments on Earth.
Liu and his colleagues found the polar bears had a gene known as APoB,
	which reduces levels of low-density lipoproteins (LDLs) – a form of ‘bad’ cholesterol.
In humans, mutations of this gene are associated with increased risk of heart disease.
Polar bears may therefore be an important study model to understand heart disease in humans.

The genome of the polar bear may also provide the solution for another condition,
	one that particularly affects our older generation: osteoporosis.
This is a disease where bones show reduced density,
	usually caused by insufficient exercise, reduced calcium intake or food starvation.
Bone tissue is constantly being remodelled, meaning that bone is added or removed,
	depending on nutrient availability and the stress that the bone is under.
Female polar bears, however, undergo extreme conditions during every pregnancy.
Once autumn comes around, these females will dig maternity dens in the snow
	and will remain there throughout the winter, both before and after the birth of their cubs.
This process results in about six months of fasting,
	where the female bears have to keep themselves and their cubs alive,
	depleting their own calcium and calorie reserves.
Despite this, their bones remain strong and dense.

Physiologists Alanda Lennox and Allen Goodship found an explanation for this paradox in 2008.
They discovered that pregnant bears were able to increase the density of their bones
	before they started to build their dens.
In addition, six months later, when they finally emerged from the den with their cubs,
	there was no evidence of significant loss of bone density.
Hibernating brown bears do not have this capacity
	and must therefore resort to major bone reformation in the following spring.
If the mechanism of bone remodelling in polar bears can be understood,
	many bedridden humans, and even astronauts, could potentially benefit.

The medical benefits of the polar bear for humanity certainly
	have their importance in our conservation efforts,
	but these should not be the only factors taken into consideration.
We tend to want to protect animals we think are intelligent and possess emotions,
	such as elephants and primates.
Bears, on the other hand, seem to be perceived as stupid and in many cases violent.
And yet anecdotal evidence from the field challenges those assumptions,
	suggesting for example that polar bears have good problem-solving abilities.
A male bear called GoGo in Tennoji Zoo, Osaka,
	has even been observed making use of a tool to manipulate his environment.
The bear used a tree branch on multiple occasions to dislodge a piece of meat
	hung out of his reach.
Problem-solving ability has also been witnessed in wild polar bears,
	although not as obviously as with GoGo.
A calculated move by a male bear involved running and jumping onto barrels
	in an attempt to get to a photographer standing on a platform four metres high.

In other studies, such as one by Alison Ames in 2008,
	polar bears showed deliberate and focused manipulation.
For example, Ames observed bears putting objects in piles
	and then knocking them over in what appeared to be a game.
The study demonstrates that bears are capable of agile and thought-out behaviours.
These examples suggest bears have greater creativity
	and problem-solving abilities than previously thought.

As for emotions, while the evidence is once again anecdotal,
	many bears have been seen to hit out at ice and snow
	– seemingly out of frustration –
	when they have just missed out on a kill.
Moreover, polar bears can form unusual relationships with other species,
	including playing with the dogs used to pull sleds in the Arctic.
Remarkably, one hand-raised polar bear called Agee has formed a close relationship
		with her owner Mark Dumas to the point
	where they even swim together.
This is even more astonishing since polar bears are known to actively hunt humans in the wild.

If climate change were to lead to their extinction,
	this would mean not only the loss of potential breakthroughs in human medicine,
	but more importantly, the disappearance of an intelligent, majestic animal.
** all
far-ˈreaching: having a great influence or effect
be adapted to: To be suited to a particular environment or situation.
consequences: something that happens as a result of a particular action or set of conditions
centimetres: 1/100 metre
have up to: To be able to do or achieve something
comparative: comparative figures/data
adipose: in storage
tissue: 组织
obese: very fat in a way that is unhealthy
diabetes: a serious disease in which there is too much sugar in your blood
genetic: relating to genes or genetics
determine: to find out the facts about something
low-density: the degree to which an area is filled with people or things
cholesterol: a chemical substance found in your blood. Too much cholesterol in your body may cause heart disease.
mutations:  a change in the genetic structure of an animal or plant that makes it different from others of the same kind
genome:all the genes in one type of living thing
osteoporosis:a medical condition in which your bones become weak and break easily
insufficient: not enough, or not great enough
calcium: symbol Ca
intake: the amount of food, drink etc that you take into your body
starvation: suffering or death caused by lack of food
remodelled: to change the shape, structure, or appearance of something, especially a building
nutrient: a chemical or food that provides what is needed for plants or animals to live and grow
undergo: if you undergo a change, an unpleasant experience etc, it happens to you or is done to you
comes around:To arrive or appear at a particular place.
dig: dig a hole/trench/grave etc
maternity: relating to a woman who is pregnant or who has just had a baby 孕妇的；产妇的 → paternity
dens: the home of some animals, for example lions or foxes
cub: the baby of a wild animal such as a lion or a bear
result in: to cause or bring about
deplete: to reduce the amount of something that is present or available
reserve: a unit for measuring the amount of energy that food will produce
paradox: a situation that seems strange because it involves two ideas or qualities that are very different
emerged: to appear or come out from somewhere
hibernates: if an animal hibernates, it sleeps for the whole winter 
resort to: when you must use or depend on something because nothing better is available
mechanism: part of a machine or a set of parts that does a particular job
bedridden: unable to leave your bed, especially because you are old or ill
potentially: something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future
tend to:to be likely to do or have something
perceived: to notice, see, or recognize something
anecdotal: consisting of short stories based on someone’s personal experience
suggesting for example: to offer an example of something that is being suggeste
manipulate: to use skill in moving or handling something
dislodge: to force or knock something out of its position
be involved doing to: be actively engaged in an activity or task
deliberate:  intended or planned
appeared to :something seemed to be the case, but it is not necessarily true.
demonstrates: to show or prove something clearly
agile:   someone who has an agile mind is able to think very quickly and intelligently 
thought-out:  carefully/well/badly thought-out
"hit out": can also be used to describe a physical attack
frustration: the feeling of being annoyed, upset, or impatient, because you cannot control or change a situation, or achieve something
miss out: be used to describe a situation in which someone does not have the opportunity to do something. F
extinction: when a particular type of animal or plant stops existing
potential: likely to develop into a particular type of person or thing in the future
breakthroughs: to manage to do something successfully when there is a difficulty that is preventing you
majestic: very big, impressive, or beautiful
