#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-11-05 Why elephants never forget?
#+begin_verse
It's a common saying that elephants never forget,
	but these magnificent animals are more than giant walking hard drives.
The more we learn about elephants,
	the more it appears
		that their impressive memory is only one aspect of an incredible intelligence
			that makes them some of the most social, creative, and benevolent creatures on Earth.
			
Unlike many proverbs, the one about elephant memory is scientifically accurate.
Elephants know every member in their herd,
	able to recognize as many as 30 companions by sight or smell.
This is a great help when migrating or encountering other potentially hostile elephants.
They also remember and distinguish particular cues that signal danger
	and can recall important locations long after their last visit.
But it's the memories unrelated to survival that are the most fascinating.
Elephants remember not only their herd companions
	but other creatures who have made a strong impression on them.
In one case, two circus elephants that had briefly performed together rejoiced
	when crossing paths 23 years later.
This recognition isn't limited to others of their species.
Elephants have also recognized humans they've bonded with after decades apart.
All of this shows that elephant memory goes beyond responses to stimuli.

Looking inside their heads, we can see why.
The elephant boasts the largest brain of any land mammal,
	as well as an impressive encephalization quotient.
This is the size of the brain relative to what we'd expect for an animal's body size,
	and the elephant's EQ is nearly as high as a chimpanzee's.
And despite the distant relation,
	convergent evolution has made it remarkably similar to the human brain,
		with as many neurons and synapses and a highly developed hippocampus and cerebral cortex.
It is the hippocampus, strongly associated with emotion,
	that aids recollection by encoding important experiences into long-term memories.
The ability to distinguish this importance
	makes elephant memory a complex and adaptable faculty beyond rote memorization.
It's what allows elephants who survived a drought in their youth
		to recognize its warning signs in adulthood,
	which is why clans with older matriarchs have higher survival rates.
Unfortunately,
	it's also what makes elephants one of the few non-human animals
		to suffer from post-traumatic stress disorder.
The cerebral cortex, on the other hand, enables problem solving,
	which elephants display in many creative ways.
They also tackle problems cooperatively,
	sometimes even outwitting the researchers and manipulating their partners.
And they've grasped basic arithmetic,
	keeping track of the relative amounts of fruit in two baskets after multiple changes.
The rare combination of memory and problem solving
		can explain some of elephants' most clever behaviors,
	but it doesn't explain some of the things we're just beginning to learn about their mental lives.
	
Elephants communicate using everything from body signals and vocalizations,
	to infrasound rumbles that can be heard kilometers away.
And their understanding of syntax suggests that they have their own language and grammar.
This sense of language may even go beyond simple communication.
Elephants create art by carefully choosing and combining different colors and elements.
They can also recognize twelve distinct tones of music and recreate melodies.
And yes, there is an elephant band.
But perhaps the most amazing thing about elephants
	is a capacity even more important than cleverness:
		their sense of empathy, altruism, and justice.
Elephants are the only non-human animals to mourn their dead,
	performing burial rituals and returning to visit graves.
They have shown concern for other species, as well.
One working elephant refused to set a log down into a hole where a dog was sleeping,
	while elephants encountering injured humans have sometimes stood guard
		and gently comforted them with their trunk.
		
On the other hand,
	elephant attacks on human villages have usually occurred
		right after massive poachings or cullings,
	suggesting deliberate revenge.
When we consider all this evidence,
	along with the fact that elephants are one of the few species
		who can recognize themselves in a mirror,
	it's hard to escape the conclusion that they are conscious, intelligent, and emotional beings.
	
Unfortunately, humanity's treatment of elephants does not reflect this,
	as they continue to suffer from habitat destruction in Asia,
		ivory poaching in Africa, and mistreatment in captivity worldwide.
Given what we now know about elephants
		and what they continue to teach us about animal intelligence,
	it is more important than ever to ensure
		that what the English poet John Donne described as 'nature's great masterpiece'
			does not vanish from the world's canvas.
#+end_verse
	
** expression
walking hard drive: 移动硬盘
magnificent: very good or beautiful, and very impressive宏伟的
benevolent: kind and generous慈善的
proverb: a short well-known statement that gives advice or expresses something that is generally true.谚语
accurate: correct and true in every detail正确的, 精确的
encounter: to experience something, especially problems or opposition遭遇
hostile: angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
recall: to remember a particular fact, event, or situation from the past回想
herd: 兽群
companion: someone you spend a lot of time with, especially a friend同伴
drought: 干旱
circus: a group of people and animals who travel to different places performing skilful tricks as entertainment马戏团
rejoice: literary to feel or show that you are very happy(使)欣喜
boast: if a place, object, or organization boasts something, it has something that is very good以有...而自豪
encephalization quotient: Brain-To-Body脑化指数
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals哺乳动物
converge/convergent: to come from different directions and meet at the spoint to become one thing会聚
synapse: the place where nerve cells meet, especially in the brain突触
developed: a developed sense, system etc, is better, larger, or more advanced than others发达
hippocampus: 海马体
cerebral: medical relating to or affecting your brain大脑的
recollection: something from the past that you remember回忆
faculty: a natural ability, such as the ability to see, hear, or think clearly本能
rote: formal when you learn something by repeating it many times, without thinking about it carefully or without understanding it死记硬背, 机械的做法, 生搬硬套
clan: a large group of families who often share the namies 部落
matriarch: a woman, especially an older woman, who controls a family or a social group女家长
cooperative/cooperatively: willing to cooperate SYN helpful OPP uncooperative合作的
outwit: to gain an advantage over someone using tricks or clever plans瞒骗, 以智取胜
manipulate: to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them(熟练地)操作, 使用(机器等), 操纵
grasp: to take and hold something firmly SYN grip抓住, 抓紧, 掌握, 领会
post-traumatic stress disorder: 创伤后压力紊乱
arithmetic: the science of numbers involving adding, multiplying etc算术
vocalize/vocalization: to make a sound or sounds with your voice有声
infrasound: 次声
rumble: a series of long low sounds隆隆声
syntax: the way words are arranged to form sentences or phrases, or the rules of grammar which control this句法
tone: the way your voice sounds, which shows how you are feeling or what you mean语调
recreate: to make something from the past exist again in a new form or be experienced again SYN recapture再创造
melody: a song or tune悦耳的音调
altruism: when you care about or help other people, even though this brings no advantage to yourself利他
mourn: to feel very sad because something no longer exists or is no longer as good as it used to be哀悼
burial ritual: 葬礼仪式
log: a thick piece of wood from a tree原木
trunk: the very long nose of an ↑elephant象鼻
massive: very large, solid, and heavy厚重的, 大块的, 魁伟的, 结实的
poach: to do something that is someone else’s responsibility, especially when they do not want you to do it偷猎
cull: to kill animals so that there are not too many of them, or so that a disease does not spread猎杀
revenge: something you do in order to punish someone who has harmed or offended you复仇
ivory: the hard smooth yellowish-white substance from the ↑tusks (=long teeth) of an ↑elephant象牙
----------------------------------------
It's a common saying that + ...: 常言道...
it appears that + ...: 看起来似乎
as many as num. sth.: 多达num.个
make a strong impression on sb.: 给某人造成深刻的印象
In one case: 在某种情况下
cross paths (with sb.): (与某人)相遇
sth. isn't limited to sb.: 某物/能力不限于某人
after days/months/years/decades apart: 几十年分别之后
go beyond sth.: 超过某物
encode A. into B.: 把某物A编入某物B
in adulthood: 在成年期
tackle problems: 解决问题
keep track of sth.: 跟踪某事
shown concern for sth./sb.: 爱护某人/物
stand guard: 站岗守卫
comfort sb. with sth.: 用某物安慰某人
it's hard to escape the conclusion that + ...: 很难不得出结论...
in captivity: 在关押
Given what + ...: 鉴于...
It is more important than ever to do sth.: 做某事比以往任何时候更重要
vanish from sp.: 从...消失

** sentences
It's a common saying that + ...: 常言道...
- It's a common saying that it's never too old to learn.
- It's a common saying that where there is a will there is a way.
- It's a common saying that writing makes one precise.
it appears that + ...: 看起来似乎
- It appeared that she smashed everything in the kitchen into pieces.
- It appeared that the police had arrived on the scene in time.
- It appears that I am at work on time.
as many as num. sth.: 多达num.个
- My manager complained that as many as 5 workers have been late.
- As many as thousands of workers have been trapped in the mine.
- He told my parents that I had eaten as many as 5 apples.
make a strong impression on sb.: 给某人造成深刻的印象
- The lady who is eager to eat made a strong impression on me.
- The abortion of my wife last week made a strong impression on me.
- The portal embedded into the mountain made a strong impression on me.
In one case: 在某种情况下
- In one case, workers can't refuse to be in harsher working conditions.
- In one case, the number of coverages increases exponentially. 
- In one case, both hostile countries stuck together to defend enemies.
cross paths (with sb.): (与某人)相遇
- To my surprise, she crossed paths with her ex-girlfriend in the arcade.
- I crossed paths with a man who works for Apple.
- The hostile elephants crossed paths with each other on a creek bank. 
sth. isn't limited to sb.: 某物/能力不限于某人
- The ability to recognize colors isn't limited to human beings.
- The ability to get a good salary isn't limited to the mean you.
- The chance to develop a model for an atom isn't limited to Chemists.
after days/months/years/decades apart: 几十年分别之后
- You became less confident than before after decades apart.
- You have lost your attraction to me after years apart.
- He is flooded with business after days apart.
go beyond sth.: 超过某物
- His plan that the World Wide Web connects everyone in the world goes beyond ethnicity and sex.
- If you want to get a good grade, you must go beyond the requirements of your teacher.
- Going beyond limitation, she succeeded in breaking the world record again.
encode A. into B.: 把某物A编入某物B
- In one case, an elephant will encode his experiences into long memories.
- He encoded his emotions into his paintings, which enhanced his memories a great deal.
- This might explain why elephants encode their experiences into long memories.
in adulthood: 在成年期
- This special kind of bird is known for their enormous wingspan in adulthood.
- Some people used to dislike roller coasters in their youth, but love them in adulthood.
- It seems strange that I love rice in adulthood which I hated in the past.
tackle problems: 解决问题
- She is an expert at tackling English problems.
- Although he is receiving electric shocks, he is trying to tackle problems.
- He tackles problems faster and better when he has a lot of food than when he is hungry.
keep track of sth.: 跟踪某事
- It reminded me of some code I made when keeping track of his program.
- Keeping track of the bug you made, you learned a lot about computer programs.
- Keeping track of the rhythm of the music, the snake began to dance.
shown concern for sth./sb.: 爱护某人/物
- My aunt, Lucy, always shows concern for us when we are on our birthday.
- He must have shown concern for his brother.
- The host is showing concern for the actor who is nominated for the prize.
stand guard: 站岗守卫
- I would rather stand guard than wander around the street.
- You have the privilege of standing guard for the princess.
- While two detectives were standing guard in front of the door, they opened the parcel.
comfort sb. with sth.: 用某物安慰某人
- My father always comforts my daughter with candies while she is crying.
- Despite the fact that he has lost his lead, he still comforted others with kindness.
- It is no use comforting a man who is put out of business with candy.
it's hard to escape the conclusion that + ...: 很难不得出结论...
- It's hard to escape the conclusion that she has cheated on you.
- It's hard to escape the conclusion that the scissors are in the drawer.
- It's hard to escape the conclusion that the tiger leaped out at the man.
in captivity: 在圈养的
- My wife doesn't like going to the zoo, because these animals are in captivity.
- I suggest that the cat is not in captivity anymore.
- The cat in captivity is smelly.
Given what + ...: 鉴于...
- Given what you ate last night, we won't provide you with any food.
- Given what you have done at the fancy party, I decided to break up with you.
- Given what you provide me, I will give you a flavor and let you have it.
It is more important than ever to do sth.: 做某事比以往任何时候更重要
- It is more important than ever to take care of your wife after her abortion.
- It is more important than ever to give your mother a hand.
- It is more important than ever to be free from cheating.
vanish from sp.: 从...消失
- I have no idea of how she vanished from the street.
- The man who was being spied on vanished from the arcade just now.
- She vanished from our house where we used to live for 3 years.
