* 2015-03-13 Can robots be creative

How does this music make you feel?
Do you find it beautiful?
Is it creative?
Now, would you change your answers if you learned the composer was this robot?
Believe it or not,
	people have been grappling with the question of artificial creativity,
			alongside the question of artifcial intelligence,
		for over 170 years.
		
In 1843,
	Lady Ada Lovelace, an English mathematician considered the world's first computer programmer,
		wrote that a machine could not have human-like intelligence
			as long as it only did what humans intentionally programmed it to do.
According to Lovelace,
	a machine must be able to create original ideas if it is to be considered intelligent.
The Lovelace Test, formalized in 2001, proposes a way of scrutinizing this idea.
A machine can pass this test
	if it can produce an outcome that its designers cannot explain based on their original code.
The Lovelace Test is, by design, more of a thought experiment than an objective scientific test.

But it's a place to start.
At first glance,
	the idea of a machine creating high quality, original music in this way might seem impossible.
We could come up with an extremely complex algorithm using random number generators,
	chaotic functions, and fuzzy logic to generate a sequence of musical notes in a way
		that would be impossible to track.
But although this would yield countless original melodies never heard before,
	only a tiny fraction of them would be worth listening to.
With the computer having no way to distinguish
	between those which we would consider beautiful and those which we won't.
	
But what if we took a step back
	and tried to model a natural process that allows creativity to form?
We happen to know of at least one such process
	that has lead to original, valuable, and even beautiful outcomes: the process of evolution.
And evolutionary algorithms, or genetic algorithms that mimic biological evolution,
	are one promising approach to making machines generate original and valuable artistic outcomes.
So how can evolution make a machine musically creative?

Well, instead of organisms,
	we can start with an initial population of musical phrases, and a basic algorithm
		that mimics reproduction and random mutations
			by switching some parts, combining others, and replacing random notes.
Now that we have a new generation of phrases,
	we can apply selection using an operation called a fitness function.
Just as biological fitness is determined by external environmental pressures,
	our fitness function can be determined by an external melody chosen by human musicians,
			or music fans,
		to represent the ultimate beautiful melody.
The algorithm can then compare between our musical phrases and that beautiful melody,
	and select only the phrases that are most similar to it.
Once the least similar sequences are weeded out,
	the algorithm can reapply mutation and recombination to what's left,
		select the most similar, or fitted ones, again from the new generation,
		and repeat for many generations.
The process that got us there has so much randomness and complexity built in
	that the result might pass the Lovelace Test.
More importantly, thanks to the presence of human aesthetic in the process,
	we'll theoretically generate melodies we would consider beautiful.
	
But does this satisfy our intuition for what is truly creative?
Is it enough to make something original and beautiful,
	or does creativity require intention and awareness of what is being created?
Perhaps the creativity in this case is really coming from the programmers,
	even if they don't understand the process.
What is human creativity, anyways?
Is it something
	more than a system of interconnected neurons developed by biological algorithmic processes
		and the random experiences that shape our lives?
Order and chaos, machine and human.
These are the dynamos at the heart of machine creativity initiatives
	that are currently making music, sculptures, paintings, poetry and more.
The jury may still be out
	as to whether it's fair to call these acts of creation creative.
But if a piece of art can make you weep, or blow your mind, or send shivers down your spine,
	does it really matter who or what created it?
** expression
composer: someone who writes music ⇨ composition作曲家
artificial: not real or not made of natural things but made to be like something that is real or natural SYN false OPP natural人造的,人工的
creativity: the ability to use your imagination to produce new ideas, make things etc创造力, 创造
intelligence: the ability to learn, understand, and think about things智能
mathematician: someone who studies or teaches mathematics, or is a specialist in mathematics数学家
programmer: someone whose job is to write computer programs程序师
formalize: to make a plan, decision, or idea official, especially by deciding and clearly describing all the details使正式
scrutinize: to examine someone or something very carefully细察
algorithm: technical a set of instructions that are followed in a fixed order and used for solving a mathematical problem, making a computer program etc运算法则
generator: something that produces something else发生器
fuzzy: unclear or confused OPP clear模糊的
yield: to produce a result, answer, or piece of information生产
countless: too many to be counted无数的, 数不尽的
outcome: the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
artistic: relating to art or culture艺术的
mutation: a change in the ↑genetic structure of an animal or plant that makes it different from others of the skind(生物物种的)突变
fitness: the degree to which someone or something is suitable or good enough for a particular situation or purpose适应,适当
ultimate: someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最后的, 最终的, 根本的
complexity: the state of being complicated复杂性, 复杂的事物
aesthetic: connected with beauty and the study of beauty美学
theoretically: 理论上
intuition: the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
anyways: =anyway 不管怎样
dynamo: a machine that changes some other form of power directly into electricity发电机
initiative: the ability to make decisions and take action without waiting for someone to tell you what to do主动
weep: or literary to cry, especially because you feel very sad哭泣
--------------------
grapple with the question of sth.: 努力解决某事的问题
program sth. to do sth.: 编程让某事做某事
propose a way of doing sth.: 提出做某事的方法
a sequence of sth.: 一连串的某事
a tiny fraction of sth.: 某物的极小一部分
approach to doing sth.: 做某事的方法
an initial population of sth.: 某物的初始种群
a new generation of sth.: 新一代的某物
be weeded out: 被淘汰
the presence of sth.: 某物的存在
The jury may still be out: 目前还没有定论
blow your mind: 震撼你的思维
send shivers down your spine: 让你背脊发凉
** sentence
grapple with the question of sth.: 努力解决某事的问题
- 
- 
- 
program sth. to do sth.: 编程让某事做某事
- 
- 
- 
propose a way of doing sth.: 提出做某事的方法
- 
- 
- 
a sequence of sth.: 一连串的某事
- 
- 
- 
a tiny fraction of sth.: 某物的极小一部分
- 
- 
- 
approach to doing sth.: 做某事的方法
- 
- 
- 
an initial population of sth.: 某物的初始种群
- 
- 
- 
a new generation of sth.: 新一代的某物
- 
- 
- 
be weeded out: 被淘汰
- 
- 
- 
the presence of sth.: 某物的存在
- 
- 
- 
The jury may still be out: 目前还没有定论
- 
- 
- 
blow your mind: 震撼你的思维
- 
- 
- 
send shivers down your spine: 让你背脊发凉
- 
- 
- 
