#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Attacking Faulty Reasoning

* introduction
** studying a little logic
Critical thinking: a process, the goal of which is to make reasonable decisions
	about what to believe and what to do.
Learn not only the methods of recognizing bad arguments but also how to build good.

** organization of the text
4 chapters, which describe the nature of a good argument
5 major chapters describing specific fallacies
final chapter, which describes writting a logical essay.

It's difficult to know when to end discussion of an issue
	and make a decision about what to do or believe.
*Five criteria of a good argument* will solve it.

** reasons for using good arguments

** goals of the text
	
* Chapter 1 A Code of Intellectual Conduct
This chapter should help you to:
	discuss with others rationally, find your own fallibility, avoid linguistic confusion.

Understand "code of conduct", which represents two standards of behavior:
	a procedural and an ethical standard.

** An Effective Procedural Standard
A proceduarl standard describes the ground rules that,
	when followed, often lead us to more successful resolution of issues,
	which is productive in settling disputes, confirming judgements, and revising beliefs.

In the discussion of the "Code of Intellectual Conduct",
	the evolved consensus position is rarely one of the two original positions;
	it's usally a "third" and better one.

** An Important Ethical Standard
The ethical standard makes us argue fairly.
If we don't, it prevents the issue from being decided or at least further explored.

** A Code of Intellectual Conduct for Effective Discussion
In the "discussion", you should make the following principles a part of your intellectual style.

*** 1. The Fallibility Principle
Be willing to accept the fact that he or she is fallible,
	his or her initial view may not be the most defensible position on the question.

*** 2. The Truth-Seeking Principle
Each participant should search for the truth or the most defensible position
	so that everyone should examine alternative positions seriously and allow other to do so.

*** 3. The Clarity Principle
Avoid linguistic confusion and separate from other positions and issues.

*** 4. The Burden-of-Proof Principle
Not anyone but the proponent should provide an argument for his position when someone asks.

*** 5. The Principle of Charity
If an opponent's argument is reformulated, it should be expressed consitently.
And the paritcipant should be given the opportunity to amend it.

*** 6. The Structural Principle
An argument made by anticipants
	needs to meet the fundamental structural requirements of a well-formed argument.

*** 7. The Relevance Principle
The reasons you prvoides should be relevant to the conclusion.

*** 8. The Acceptability Principle
Reasons should be accepted by a mature, rational person
	and meet standard criteria of acceptability.

*** 9. The Sufficiency Principle
Reasons should be suffcient in number and weight to support the conclusion. 

*** 10. The Rebuttal Principle
One who provide an argument should rebut all serious criticism of the argument.

*** 11. The Suspension-of-Judgement Principle
If there is no position defended by a good argument or two or more positions by equal strength,
	suspend judgment about the issue.

*** 12. The Resolution Principle
When an argument is a structurally sound one
	that uses relevant and acceptable reasons
		that together provide sufficient grounds to justify the conclusion
		and that also includes an effective rebuttal to all serious criticisms.

** The Fallibility Principle
One's own initial view may not be very defensible so that he or she is fallible.

Accepting your own fallibility mans that you are willing to change your mind.

It's a neccessary condition of intellectual progress,
	making progresses among scientists, philosophers, and most other academics,
	however making so little progress in religion and politics.

If there is any doubt about the principle,
	choose an issue about which people hold conflicting opinions.

We think a position which we spent time developing and refining is defensible,
	so others think.

It not only calms the emotional waters surrounding the issues,
	but also it has the potential for opening our ears to different and better arguments.

Try to be the first to confess your own fallibility,
	your opponents' behavior will tell you that whether he is willing to have further conversation.

Even a critical thinker only have changed his mind about an important issue once in the past year.
It's more likely a person would turn out to be wrong on more issues than right.

** The Truth-Seeking Principle
-

We come to true knowledge only by frist recognizing our own ignorance or lack of knowledge,
	so we must condsider criticism of our own views in discussion.

The truth is not likely to be in our custody,
	but is the most defensible position supported by the strongest or best available argument.

To find out truth, we need not only to assume that we may not have the truth now
	but to listen to arguments for alternative positions and encourage criticism of our arguments.

After having done the hard work of investigation,
	we should not give the impression that we have an open mind about the issue
		and carry on a pseudo-discussion.
We could explain that to our opponent
	or join the debate when we think we might have missed something.

Because of hope of winning, we sometimes cheat to do it.
The truth comes at a price
	-- a willingness to look at all available options and the arguments in support of them.

Not try to win by ignoring or denying the counterevidence against your positions.

** The Clarity Principle
-

Even if we think what we say is perfectly clear to ourselves,
	it may be confusing, vague, ambiguous, or contradictory to others.

We must usually deal with one feature at a time
	so that each party must pay attention
		to keep other interesting issues, related issues from clouding the discussion.

We must not falter the potential resolution of an issue because of verbal confusion.

** Assignments
1. Discuss some of the obstacles of adopting the "Code of Conduct for Effective Discussion"
		as a means of resolving conflicts in our practical lives.
	 For example, why do you think good arguments so rarely seem to change minds?

	 We have deep emotions on our original minds
		so that we don't want to change them, even if we listened to a better argument.
	 Sometimes if we change our minds, others will think that we are weak or often make mistakes,
		which leads to the decline in status in society.

2. Do you agree that failure to follow the Code of Intellectual Conduct in discussion
		may be immoral?
	 Why or why not?

	 Yes, I do.
	 If others in discussion follow the code but you don't,
		they will make little progresses because of your failure.
	 They will receive less than they should be, may get frustrated.

3. Why is it inappropriate to continue in a serious discussion
		if you are not open to the possibility of changing your mind?

	 If you're not open to the possibility of changing your mind,
		there might be the emotional waters surrounding the issues
		and you won't open your ears to different and better arguments.

4. Are you a critical thinker?
	 If so, describe an occasion wherein you changed your position
		by force of argument on an important issue in the past twelve months.

	 I am probably a critical thinker in some aspect.
	 I used to insist that the tasks which my boss order should be done only in my way.
	 I changed my mind when I began to listen to other opinions,
		in which I learnt my own view is not the best way to solve problems.
	 It really makes me a better programmer and makes me get along with my colleagues better.
		 

5. The next time you are in a heated and unresolved discussion on an important issue,
		stop and confess that your position may be wrong.
	 If the other participants do not follow suit,
		ask them whether they are also open to the possibility of being wrong.

	 Ok, I will try it the next time when I discuss the tasks with my colleagues.

6. It has been claimed that an argument for a position is not a good one
		until the arguer has effectively rebutted anticipated serious criticisms
			that might be brought against it.
	 Since following this advice would call attention to flaws in your own argument,
		do you think this would tend to weaken it or the position it supports?
	 Why or Why not?

	 No, I don't.
	 Whether my argument or his is the most defensible is not a big deal to me.
	 Before being a winner, I'm a truth-seeker.
	 Therefore, it's more important to seek truth than to win.
	 Thanks to following this advice, it will help me to seek more defensible opinion better.





* Chapter 5 Fallacies that violate the structural criterion

- 用自己的语言,能够描述出违反structural的谬误的重要性质
	解: 你说这个谬误叫argue in a circle,最重要的性质是 前提和结论实际是一回事,前提证明结论,结论又证明前提,所以叫循环论证
- 在实际讨论中能够识别,叫出名字,解释谬误的形式是啥样的
	解: 我们在讨论刘亦菲是不是美女, 然后有个sb一直称呼刘亦菲是女神,所以是美女;我们这时候要说他犯了Question-begging language.还要说明,我们正在刘亦菲是女神,已经暗含了刘亦菲是美女的假设.
- 能够采取有效的效率attack这些谬误
	解: 魔术, 我们知道了自己犯了肯定后件的谬误, 然后attacking, 去想其它方式导致结论的原因.比如,助手的下半身和魔术师的上半身.


- Begging-the-Question Fallacies
	assume the truth of the conclusion in their premises
	+ arguing in a Circle
		asserting in the premise what is asserted in the conclusion
	+ question-begging language
		by means of language assume a position on the very question
	+ complex question
		presuposes in a question that a definite answer had already been given
	+ question-beggin definition ?
		disguised as an irrefutable empirical premise
- Fallacies of Inconsistency
	premises are incomppatible with one another or conclusion contradicts one premise
	+ incompatible premises
		inconsistent or incompatible premises
	+ contradiction between premise and conclusion
		a conclusion is incompatible at least one of premises
- Fallacies of Deductive Inference (well-established)
	violate well-established rules of deductive logic
	+ denying the antecedent 否定前件
	+ affirming the consequent 肯定后件
	+ false conversion 错误转换
	+ undistributed middle term 无关中项
	+ illicit distribution of an end term ?
	
	
违反这条规则的三种谬误: 丐题~不一致~违反演绎法则.

犯这种谬误,结论无法necessarily or probably来自于premises, 我们会在例子里解释为啥.

之所以叫structural one,是因为犯的谬误跟premises和conclusion的内容无关.如果用符号代替,我们也能发现从premises推不到结论.
	解: structural fallacy, 直接从structure(把命题换成符号)就能判断推导不了结论.
		例: 我老婆说: 老公爱你. 我老婆又说: 老公我讨厌你. 得不到任何结论.
			换成符号就是 A, not-A, 不需要看内容,就知道得不到任何结论.

丐题在前提中预先假设了结论;不一致是前提们不一致 或 前提和结论不一致; 违反演绎法则(well-established 也违反了acceptability principle -D)

** beggin-the-question fallacies 丐题
arguing-in-a-circle fallacy: 把结论当作其中一个前提
quetsion-begging-language fallacy: 用语言的方式,在问题中假设和结论一致的position
complex-question fallacy: 
	假定已经有答案了,
	假设对错了,有争议的问题(比如Lisa什么时候生二胎 -D)
question-begging definition fallacy: 定义中结论已经对了

论证根据定义是,一个结论被其它(different)前提支持,丐题并没有其它前提, 所以结构就犯错了.

*** arguing in a circle
循环论证的定义: 或明或暗地在前提里面确定 需要在结论里面确定的事物.
	解: 强调的某个前提和结论一致

最常见的谬误, 把结论当作其中一个前提: 例如: 你对手宣称自己的position是对的,因为它就是对的.
	解: 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.

Since A, Therefore A

arguing in a circle在实际情况往往是暗示的.
	解: 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.
		这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.

通常arguing in a circle不会用相同words和form, 实际上识别是非常困难的.
这种谬误有时候贯穿文章,章节,甚至足足一本书, 就更难识别了.

一旦识别"A is true because A is ture",这种谬误就会无比明显.

EXAMPLE: 最容易遇到的就是换换同义词
	使用带有渎神和淫秽的书是不道德的, 因为对于孩子来说听下流肮脏丑陋的词是不好的.
	解: 这里主语 渎神和淫秽的书 是 下流...的词是近义词; 不道德的 和 不好 的词又是近义词.

EXAMPLE: 这个大学在学生政策上是专制的. 因为他们对待学生像孩子. 这里仅仅是解释了专制的定义.
	解: 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.

EXAMPLE: (循环论证还从subP可以传递-D)
	he does not have the background and ability to evaluate it properly(subP)
	is biased against modern music(P)
	is an incompetent music critic(C)
	subP and C are the same things.
	解: 领导说要开除你, 理由是你不称职, 因为你做事不合格所以你对工作理解的不到位,你对工作理解不到位所以你不称职.

**** ATTACKING THE FALLACY
要注意有没有前提等同于结论,或者前提暗里假设了结论的事实.

要注意辨别你对手可疑的多义的claim.
必要时,转换成标准的格式,这样甚至能清晰地看到premise和conclusion是怎么一样的.

给个明显反例或荒谬的反例.

用丐题的人会真心觉得自己说的对.但是必须被提醒的一点,个人相信的不能当作证据.

-DDD
arguing in a circle简单,但是却难以识别.
保持注意力,注意假设和前提是不是一样; 把argument改成标准的形式更容易发现这个谬误.
	1. 前提和结论同义词换一下,实际一个意思
	2. 你问他要原因的时候, 他给你把名词解释一下
	3. subpremises其实和结论是相同的, 多走了一步想掩盖这个事实.

*** Question-begging language
定义: 通过语言的方式在特殊的提问中假设了立场,引导听众得到相同的答案.
	解: 利用语言诱导听众得到某个结论, 强调的是引诱,并没有给出答案

有意或不小心地把 未得到解决的事情 预设成 已经得到解决了.
语言本身带偏向导致预设了结论, 因此应该用描述性和中立的语言.
	解: 有意或者无意地把本来没有处理好的事情 预设成 已经得到确认的事情.
		比如: 
			1. 法庭上,女方说男方一点都不管家里.男的说我每个月给家里寄8千,女的说这是生孩子的,这里必须的,你没资格说这个.
			2. 知乎上,电车难题. 有个回答说,谁把电车偏轨就是谋杀. 需要合并下.
			3. the leading question: 

带有偏向的语言并没有给证据,所以也不能产生acceptable结论.

第一种类型: 靠煽动性语言
EXAMPLE: Natalia在法庭上喊我戴绿帽了, 所以法庭应该认为我戴绿帽了.
	解: 教师汪康夫被告强奸12名幼女,判刑10年, 伸冤54年后受害者均否认被强奸.

第二种类型: 把刘亦菲称为女神
EXAMPLE: 议题是胎儿是不是算是人类,一个辩方一直称呼胎儿为婴儿.

第三种类型: 用反问的语气好像这件事已经有定论了.
EXAMPLE: leading question(引导性问题-D) 你不是认真投票Professor Reiff作为年度教师,是吧.
	解: 这里用这种反问的语气,实际上是假设了不应该投票给Professor Reiff, 但是又没有解释.
		比如领导吩咐下一件事情需要我和同事做. 我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?

**** ATTACKING THE FALLACY
发现这个人是否犯这个谬误,注意他的语言是否阻止issue变得开放.
辩手持续使用这些词是不道德的 像: 严重的,震惊的,无法饶恕的.
	解: 像我老婆跟我争执的时候,经常用一些形容词,说我怎么怎么过分,但实质的行为却没有说多少.这种就是阻止issue开放.

总之,不要被丐题语言迷惑, 尤其是什么 众所周转, 明显的. 可以天真的来一句: 对我来说并不明显.
	解:像那种明显的,10岁小孩都直到,傻子都晓得.
		我遇到过一次,领导拉大家一起讨论问题的时候,我对于某个问题不懂的,但是领导说明显的. 这实际对于我来说并不明显. 我就说:我脑子笨,这件事我还没搞懂,能不能再解释一遍.

面对leading-question, 要找到方法去揭示他正在让你保证的预设是issue的一部分.
当然,如果这些预设,在其他地方被充分,那么就不算谬误了.

-DDD
1. 用那些情感色彩强的词,比如我被cheated, 让原来开放的issue倒向一边
2. 众所周知的,而你并不知道.比如胎儿称之婴儿. 你可以来一句, 对我来说不是明显的.
3. leading-question. 问题中有和issue有关的假设. 比如: 你投票给Professor有没有认真?(假设了你投票给Professor) 但是注意,如果假设被证实了,又不是谬误了.


*** complex question 复杂问题?
定义: 问题中有给定答案的假设, 或者问题中认为一系列的子问题都有相同的答案.
	解:强调的是给出了答案,或者所有子问题答案一致

第一种类型:
丐题的原因就是因为问题中假设了事实(未确认).
偷了手表后,你怎么处理手表的?
	解: 老师逮住学生,问,你是用左手抽烟还是右手抽烟.

值得注意的,如果回答人默认问题中的假设,那么这就不是丐题了.
丐题仅仅是当问题涉及的issue还是开放的.

第二种类型: 问题中多个claim,一否全否,一肯全肯
你会带我回去,在路上让我从商店里面买东西吗?
在这个问题里,假设了要么全答应,要么全不答应.
同样的只有回答人认同这个假设,才不是丐题.
	解: 我老婆问我,你爱不爱我,愿不愿意给我买最新的江南布衣的衣服.这里她就犯了复杂问题的错误.

解析下两个例子:
 因为你偷了我的手表(P)
 所以你偷了我的手表(C)
 
 因为你带我家所有的情况你都会带我去商店(P)
 所以你带回家的所有情况你都会带我去商店(C)
 
EXAMPLE: 
	What fraternity are you going to pledge?这里假设了要参加社团
	When are you going to settle down and get married? 两个问题.
 
EXAMPLE: 哈哈, 一口气提7个问题, 第二种类型(-D)
	Are you and Nancy going to the Keller-Trent wedding and to the reception next Saturday, even though you and she were not invited?
	2的7次方, 128种回答.
	
EXAMPLE: 为什么叫丐题(因为回答者被提问者乞讨去确认假设的事实-D)
	为啥离婚父母的孩子更加情绪化不问题比那些未离异的家庭?

**** Attacking the Fallacy
怎么样attack complex question?
1. 拒绝给直接肯定或否定的回答给这种complex question.
	如果问问题的人不明白你的不愿意回答, 反问它: "你有没有停止偷税"(这个要给个中文版的-D)
	解: 你这个问题我无法回答. 在你偷了井盖之后,你是怎么处理井盖的?
2. 指出问题中有问题的假设,告之假设还没有决定.
	给保证: 虽然如此,我愿意任何时候聊这个假设.
	解: 你这么说,xxx还没有确认,正在讨论中, 等xxx确认了, 我再回答你这个问题.
3. 必要时坚持把问题切割,一个一个回答.
	解: 坚持分开回答问题. 老婆, 我是爱你的, 但是我不想给买江南布衣的衣服.

*** Question-Begging Definition
定义: 把定义伪装成无法证伪的经验假设
	解: 注意定义是他自己给的定义,还是公众的定义.忠诚的狗不会冲主人狂吠,如果它冲主人狂吠了,那它就不是忠诚的狗.
		重新定义忠诚的狗.

经验前提和定义前提很容易迷惑.
定义前提应该是共用术语或者权威人士的思想.
	解: 比如说信佛的人不杀生.如果他杀生,那么他就不是真正信佛的人.
		大家普遍认可的信佛的人是去寺庙里拜的人.
		定义的信佛的人是不杀生的人.

经验前提做观察性或事实性的断言.
他的可接受性取决于我们的经验,相关权威的测试,以及恰当实验的结果.

定义前提假设成了经验前提,就犯了这种谬误

两条线索去发现这个谬误
1. arguer拒绝接受他经验前提的反证据
	解: 信佛的人不杀生
2. issue中的关键属术语,一直用修饰性词: true, real, genuine
	解: 真正信佛的人不杀生. be defined in an unconventional way

EXAMPLE: (线索1和2, 加修饰词,丐题顶替 -D)
issue是讨论基督教人喝不喝酒.
有人说看到基督教人喝酒.
然后有辩手定义, 如果他喝酒,那他就不是一个真正的基督教.

EXAMPLE: 
真爱不会离婚或分手.
如果离婚或者分手那么就不是真爱.
Eric可以这样定义真爱,但是这种奇怪也就无法被理性人反驳,也就没有意义了.
解: 这种奇怪的定义已经无法反驳了,也就没有讨论的意义.
	比如有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?
		偷的话: 按经验定义,不告而拿, 孔乙己定义是非读书人的不告而拿.

EXAMPLE:
true-blue 共和党人是一个人,从不离开共和党人.
对是对的,但是这种断言属于定义前提,不属于经验前提.
解: 恋爱中的男女往往对真爱的定义有偏见.
	她真爱你,她就会对你不离不弃.

ATTACK THE FALLACY:
问arguer这是定义前提和经验前提,如果他被你问着了,解释下不同.
还可以问下有没有证据支持他的前提,如果没有,很可能是定义前提.
解: 这个xx是你自己的定义的,还是大家都这么认为或者专家给出的定义?
	你这么说xx是xxx, 有没有证据来支持这个呀?
	
	如果两问题都答不上来,那么就是定义前提.
要这么定义也可以, 解释下为什么不用其它的定义, 比如通用的和相关专家的定义.
发现是定义前提后, beggar要愿意捍卫自己的定义(可能有共用术语或权威认证的).
解: 这个基督徒你定义成不喝酒的, 为什么不是每周去教会做礼拜的?
	如果你觉得你的定义更好,能说下你的理由吗?
	你看字典的定义是这样的,专家是这么说的.

***** 小总结:类型或例子(-D)
arguing in a circle:
	1. 前提和结论用同义词替换一下
	2. 你问他要原因,他给你解释名词
	3. 子前提和结论是相同的, 多绕了一下想掩盖丐题
question-begging language:
	1. 靠煽动性的语言:众所周知
		比如: 在法庭上,女性声泪俱下指责丈夫出轨,却不给证据
	2. 把刘亦菲称为女神:
		比如: 在讨论胎儿算不算人类时, 有辩方一直称呼胎儿为婴儿(婴儿已经属于人类的范畴)
	3. 引导性问题:(在问题中假设没有做过的事情, 和后面complex-question有交集 问Leo -D)
		比如: 老师问: 你是用左手抽烟还是右手抽烟啊
complex question:
	1. 问题中的两个子问题会导致 一个问题变成另一个问题的答案
		比如: 你什么结婚和安定下来? 结婚变成了安定下来的答案
	2. 问题中多个问题, 一否全否, 一肯全肯
		比如: 你爱我,愿意给我买房子吗? 
Question-Begging Definition: 首先有个经验前提和定义前提的概念
	1. 经常有true,real,genuine这种修饰语
		比如: 一个人爱国就不可能投降, 如果一个爱国的人投降了,那么就不是真正爱国.

**** Assignments
A. Begging-the-Question
1. Complex Question: 在问题中,假设在沃尔玛买东西等于勇气
2. Question-Begging Definition:
	这里定义真正的犯罪思想是渡过监狱岁月后仍然不会改正.
3. question-begging language:
	煽动性语言,没给证据
4. arguing in a circle
	因为圣经说自己是上帝显灵,所以圣经是上帝显灵
5. Complex Question:
	选民 支持士兵是增加总统国防预算的答案.
6. Question-Begging Definition:
	重新定义了sane是不会自杀的人
7. question-begging language(刘亦菲是女神)
	显然 生存下来的有机生物比没有的更适应环境
8. Question-Begging Definition
	重新定义在 价格范围的房子不包括tacky little house
	
	
** Fallacies of Inconsistency
前提们矛盾或者结论和某个前提矛盾, 这两种情况得不出有效的结论

这种不一致是不明显的.
如果某个前提可以被解释 和 另一个前提或者结论 相矛盾,那么可以认为不一致.
解: 不一致的谬误, 命题和命题之间矛盾.
	比如: 李洁是大学生,李洁不是大学生; 所以李洁上过高中.
		 李洁是服装设计师,李洁是大学生;所以李洁不是大学生.
		 
解: a perfect alibi
	嫌疑人的结论是自己有a perfect alibi
	理由 当犯罪发生时, 我正在8点去往伦敦的火车去工作
		我10点已经在伦敦了
			我工作时间是10点,而且我并没有迟到
	侦探的理由是:
		 8点去往伦敦的火车没运营
		 10点在伦敦可以坐8点25的车
	这里嫌疑犯的理由和实际情况相矛盾, 那么就推导不出他有perfect alibi.
	

*** incompatible premises
从不一致或矛盾的前提们,得出结论

这种情况得不出acceptable or true的结论:
	因为A,
	又 not-A,
	[哈哈,得不出结论]

EXAMPLE: 两个前提不一致, 又说上帝是全能的,所以没有罪恶; 又说有罪恶
	如果上帝是全能的~all-love, 那么就世界上没有罪恶.(A)
	世界上有罪恶.(not-A)
	所以,上帝不存在.
	解: 他们先假设上帝是全知,全能的,慈爱的;世界上没有罪恶 (A)
		世界上有罪恶(not-A)
		假如妈妈啥都会,啥都知道,又爱你,你的任何困难妈妈都会给你解决;
		实际上有些困难就没有给你解决.
		所以要么你妈妈不存在,要么你妈妈不是全知全能,且爱你.
	
EXAMPLE: 上帝说啥对啥就对, 这些行为道德上不对(而不是上帝说的), 两者冲突
	因为上帝说啥是对的,啥就是对的(A)(P)
	一些行为像谋杀, 上帝就不会说是对的(rebuttal P)
		因为他们是道德上不对的(not-A)(subP)
	解: 这里前提矛盾的情况是.
		上帝的说一项行为是正确的是决定事物是否正确的唯一标准.
		一些行为像强奸谋杀,上帝就不会说对的
			因为他们在道德上是不对的(注意这里除了上帝的宣言多了一项判断).

EXAMPLE:
	政治家为了拉选票,说会提升服务降低税费(A); 然后又说税负不变(not-A)

ATTACKING THE FALLACY:
把短句给他标准化, A和not-A,马上就能发现问题了.
辩论中,告诉对方一致性原则.

没病走两步, 让他从A和not-A推导出结论, 一般是退不出来的.
如果推出来了,那么他就是把其中一个当成对的,忽视了另外一个.如果他坚持not-A是对的,就有义务解释为什么不是相矛盾的.

现实中确实很难消除这种矛盾的前提.比如:我姑爷对我说,要把人往坏了想,不要去相信别人.那么他自身也在这个别人当中. 这就矛盾了.
	
	
*** Contradiction Between Premise and Conclusion
定义: 得出的结论和其中一个前提相反

形式: 
	Since A(P)
	Since B(P)
	Therefore, not-A (C)

为啥说这个错了, 因为一个论证里面不能A,又not-A这种情况出现

EXAMPLE:
	因为万事物有源头(A)(P)
	我们不能无限朔源(P)
		因为如果没有源头,我们不会出现(sub P)
	我们出现了(P)
	因此有个没有源头的起源(not-A),那就是上帝.(C)
	
	解: 一定是鸡生蛋,蛋再生鸡.
		但是鸡生蛋,蛋生鸡不可能无限循环
			因为如果无限循环,就不会有鸡和蛋
		有鸡和蛋
		因此肯定有个源头,蛋不是鸡生的,或者鸡不是蛋生的.
解: 蛋是由鸡生的,鸡又是由蛋变的
	但是鸡和蛋不会凭空产生
	所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

EXAMPLE:
	身体物理的且占空间(P) (A1)
	思想非物理的且不占空间(P) (A2)
	经历表明思想影响身体, 反之同样(implicit P)
	所以思想和身体相互交流(C)(not-A)
	解: 思想和身体相互交流, 但是因为非空间的物质和空间的物质不会互相交流,要么身体不是空间的, 要么思想是空间的.
	这样结论要么和A1矛盾,要么和A2矛盾.
	
EXAMPLE:
	所有生命都是神圣的, (P)(A)
	我们有义务不要destory it(P)
	流产destory it(P)
	因为流产是错误的,除了强奸(C)(not-A)
	解: 每条生命都是上天的礼物, 
		我们有义务不要摧毁它,
		流产摧毁了它
		所以流产是错误的, 除了强奸导致产生的孩子.
	
**** Attacking the fallacy
最好的方法去发现这个谬误,就是转换成A,not-A这种形式.
除非arguer不尊重这个不矛盾法则,否则他应该抛弃一个前提,或者找到方法解决前提和结论的矛盾.

*** Assignments
B. Fallacies of Inconsistency
1. 人类知识是建立的skepticism上的(P)(A)
   skepticism是观点, 人类永远不要知道任何事事正确的(P)(not-A)
   我们最好放弃研究(C)
   前提不一致!
   
2. 谁说我错了你对了关于吸大麻.(P)
    每个人要自己决定啥是对的(P)(A)
    我没看到用大麻有任何不道德.(P)
    你错了.(C)(notA)
    前提和结论不一致
3. 
	生命是珍贵的礼物,谁也没有权力拿走.(P)(A)
	一个谋杀其它的人正在destory it(P)
	所以我支持谋杀犯死刑(C)(not-A)
	前提和结论不一致
4.
	B: 你思考没灵感. 你认为如果观点们是相互矛盾的,就没有意义
	E: 我认为不矛盾是智力讨论的必要条件
	B: 没有理由认为矛盾就不能有意义
	E: 如果矛盾,就没有意义
	B: 如果矛盾,也可能有意义
	E: 如果矛盾, 就不会有意义
	B: 你在说什么哦
	前提和结论不一致, B的前提是 前提矛盾也会有意义, E的结论是 前提矛盾就没有意义
	根据B的前提,B的前提和E的结论会共存,所以是前提和结论不一致
	
** Fallacies of deductive inference 演绎逻辑谬误
	
*** Denying the Antecedent: fail to see other reasons 否定前件
well-formed deductive argument:
	If A, then B(P)
	A (P)
	B (C)

Denying the Antecedent:
	If A, then B (P)
	not-A (P)
	not-B (C)
	
这里关键错误在于假设A的出现一定会有B, 但是还有可能C的出现会有B
解: 正常的if then的推理是,
		如果A,那么B; A; 所以B
	否定前件是: 如果A,那么B; not-A, 所以not-B
	这里面犯的错误就是, 把A当作是唯一B的条件.
	如果抽烟,那么会短命. 但是不抽烟不代表不会短命, 因为还可以吸毒导致短命. 抽烟并不是短命的唯一条件.

EXAMPLE: 
	如果抽烟,就会短命 (A->B)(P)
	我不抽烟(not-A)(P)
	我不会短命(not-B)(C)
	解: 家中女性长辈,劝人不要抽烟,理由就是不要抽烟,抽你个短命鬼.
		家长男性长辈常常说,又不是抽烟一件事情会短命.
	
EXAMPLE:
	如果死刑减少人们犯重罪,那么就是正义的(A->B)(P)
	因为没有减少(not-A)(P)
	所以他不是正义的实践(not-B)(C)
	:这里还有其它理由,比如威慑有犯重罪意愿的人让他们不敢犯罪,可以使其称为正义的实践

EXAMPLE:
	如果期末考试过来, 那么课就过了
	因为我期末考试没过
	所以我课没过
	:还有其它理由导致课没过

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪不是狗.
	缪缪就不是动物了.

*** Affirming the Consequent 肯定后件
肯定后件后,肯定前件
Well-formed deductive argument
	If A, then B, (premise)
	and not-B, (premise)
	Therefore, not-A. (conclusion)
	
affirm the consequent
	If A, then B (premise)
	and B (premise)
	Therefore, A. (conclusion)

A不是B的唯一条件,即便是B正确时,A也正确,推理的结构也是错误的.
解: 正常的推理
	如果A, 那么B; not-B; 所以not-A
	肯定后件的推理:
	如果A, 那么B; B; 所以A
	同样的错误也是把A当作B发生的唯一条件
	举例: 如果缪缪是狗,那么缪缪是动物. 缪缪是动物,显然缪缪不一定是狗,还可能是猫. 值得一提的是,即便缪缪是狗,这项推理也是错误的.

EXAMPLE: 
	如果丈夫计划谋杀妻子,那么他会给妻子买保险(A->B)(P)
	丈夫买了保险(B)(P)
	因此,丈夫计划谋杀妻子(A)(C)
	其它理由对买保险也是充分的
解: 如果萍萍偷钱了,她就会买零食
	她买零食了
	偷没偷钱你自己想.

EXAMPLE:
	如果你SAT分数搞,你可能进入一个好大学(A->B)(P)
	你进入好大学: Centre College(B)(P)
	所以, 你SAT分数一定高(A)(C)
	这里假设了SAT分数高是进入好大学的唯一原因,还有可能是成绩高~体育和艺术特长
解: 如果你高考分数高,你可能进入北大
	你去北大了,
	所以,你高考分数高.
	撒贝宁表示北大保送也还行.

EXAMPLE:
	如果我吃红肉, 那么我生病(A->B)(P)
	我生病(B)(P)
	因此, 我肯定吃过红肉(A)(C)
	这里假设了吃红肉是生病的唯一原因

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪是动物.
	因此缪缪是狗.

*** False Conversion 错误转换
把if句中的前件和后件互换,或者把主语和宾语互换,并且认为命题的真假不变.

前件和后件转换:
	如果当开关开着灯亮了,那么灯泡是好的. 
	<转换> 如果灯泡是好的,那么当开关开着灯亮了.
换主语和谓语:
	所有的生物学家是科学家
	<不能转换> 所有的科学家是生物学家
	等价于: If one is a biologist, then one is a scientist.
	
	有些X不是Y<不能转换>很少犯,不用特意提
	
	可以转换:
		no X are Y
		some X are Y 
	
	到底可不可以转换, 去觉得主谓 都distributed or 都undistributed.那么就可以转换. 一个distributed一个undistributed不可以转换.
	distributed: term下的所有成员都明确了

EXAMPLE: 
	解: 所有宗教徒都是依赖外界的人
		所有依赖外界的人都是宗教徒<不能转换,例如:孩子>
	
EXAMPLE:
	所有吸冰的人都是吸大麻的人
	<不能转换>所有吸大麻的人都会吸冰
EXAMPLE:
	如果你是基督徒,那么你一定关爱他人
	因此, 如果你关爱他人, 那么你一定是基督徒
	
ATTACKING THE FALLACY
举反例:
	所有苹果都是水果
	<不能转换>所有水果都是苹果
	
	如果这个人是总统,他至少35岁且美国公民
	<不能转换>如果他至少35岁且美国公民,那他是总统

*** Undistributed Middle Term 无关中间项
定义: 从三段论中得出结论, 三段论中前提的中间项没有被distributed至少一次


1. structure of a syllogisms
	1.1. 3个statements 2个premises和1个conclusion
	1.2. middle term和end term
		所有term都出现且只出现两次
		middle term两次出现在premises里
		两个end term一定出现在conclusion里
2. the four types of statements used in syllogisms
	A. all X are Y
	E. no X are Y
	I. some X are Y
	O. some X are not Y
	universal: 全称
	particular: 特称
	affirmative: 肯定
	negative: 否定

3. the nature of distribution
	某个分类下的所有成员都被这个term包括
	例如: AsEbInOp
		- all X are Y. subject是distributed
		- no X are Y. both是distributed
		- some X are Y. neither term是distributed
		- some X are not Y. predicate是distributed.

4. the two main rules of syllogistic reasoning
	1. 中间项至少得distributed一次
	2. 在结论中是dirtibuted的term, 至少得在前提里面distributed一次
	
所有教授是技能丰富的人
没有技能丰富的人是underpaid
因此没有教授是underpaid
symbol化:
	P(A)C  (P)
	C(E)U  (P)
	P(E)U  (C)
	
EXAMPLE:
	PH (I) PDL (P)
	PR (I) PH (P)
	PR (I) PDL (C)
	中间项是PH, 两个premises都是I, 所以PH都是undistributed.和规则1相反

EXAMPLE:
	D (A) CLA
	J (A) CLA
	--------
	J (A) D
	
EXAMPLE:
	SK (A) PAG
	R (A) PAG
	--------
	R (I) SK
	
ATTACKING THE FALLACY
别人不知道符号标记这一套,所以得给别人举例子:比如: 教授读书;孩子也读书;所以孩子都是教授.
但是你自己得懂这一套,这样你用起来才能得心应手.

*** Illicit Distribution of an End Term 最后项的错误分布
a distributed end term in the conclusion is not distributed in the premises

EXAMPLE: 
	书上犯错了,Therefore, members of the jury are people who are likely to come to a false
judgment. (E) (conclusion)
	IRF (A) CFJ s
	JM (E) IRF both
	-------
	JM(E)CFJ both
	CFJ is undistributed
	
EXAMPLE:
	MR (As) J
	BGG (Op) J
	-------
	MR (Op) BGG
	BGG in conclusion is distributed, but in second premise is undistirbuted
	
EXAMPLE:
	NC (A) EX
	NC (A) EE
	------
	EE (A) EX
	the EE in conclusion is distributed, but in second premise is not.
	
ATTACKING THE FALLACY
还是一样, 自己要会用符号系统, 但是跟别人解释,还是举明显得反例
	所有父亲有孩子
	没有妈妈是父亲
	-------
	所以没有妈妈有孩子
	
ASSIGNMENTS
C. Fallacies of Deductive Inference
1. 
	如果毕加索的作品有艺术价值,那么会被大多数人欣赏 (P)
	被大多数人欣赏 (P)
	所以, 它有艺术价值 (C)
	If AM, then  A
	A
	--------
	since AM
	肯定后件
2.
	spheres always cast curved shadows(P)
	the earth casts a curved shadow on the moon during a lunar eclipse.(P)
	the earth is spherically shaped(C)
	S (A) CS As
	E (A) CS As
	--------
	E (A) S As
	CS undistributed middle term
3. 
	BT (E) T Eb
	T (A) C As
	---------
	BT (E) C Eb
	C is an undistributed middle term in second premise
4.
	If OL, then SOT
	SOT
	----------
	OL
	肯定后件
5.
	IF SL, then OV
	not-Sl
	--------
	not-OV
	否定前件
6.
	MJA (I) NV In
	ACD (I) MV In
	--------
	ACD (I) MJA In
	undistributed middle term and illicit distrubtion of an end Term
7.
	If M, then E
	not-M
	---------
	not-E
	否定前件
8. 
	If 控制垄断, then 公共好处增加
	想要公共好处增加
	--------
	所以控制垄断
	肯定后件
9.
	I can do anything I want.
	Nobody can tell me what to do and what not to do.
	
	你必须遵守法律啊.
	我必须遵守法律, 但是政府不能告诉我去做什么.
	-------------
	我可以做任何事情我想做的.
	前提不一致
10.
	E (A) V
	P (O) V
	--------
	E (I) V
	中间项不能出现在结论上
11.
	If he really loved her, he would insist on being the sole provider
	Question-Begging Definition
12.
	肯定后件
	If a cat licks antifreeze, the cat will die.
	I left my cat out last night and she died.
	--------
	She licks antifreeze.
13.
	Complex-Question:
		在问题中假定了事实, 我给你的5000块,你给丢在股票市场了.
14.
	UP (I) K
	RP (I) K
	-------
	UP (I) RP
	中间项一次都没有distributed.
15.
	Question-Begging Definition
	自己定义literally true.
16.
	Question-Begging Definition
	自己定义well-adjust people事那些不自杀的人
17.
	Question-Begging Language
	用stupid这种煽动性的语言
18.
	If the light was on, then he was at home.
	The light wasn't on.
	----------
	He wasn't at home.
	否定前件
19.
	Arguing in a Circle
	前提和结论一致
20.
	SHMW (I) D
	FP (E) SHMW
	---------
	FP (E) D
	D在结论是distributed, 但是在前提里面不是distributed.
	
21.
	前提不一致
22.
	Question-Begging Definition

** 四种丐题的区别
四种丐题的区别:
	arguing in a circle: 强调的某个前提和结论一致
		1. 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.
		2. 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.
		3. 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.
	Question-begging language: 强调利用语言引诱听众给出想要的结论. 强调的是引诱,并没有给出答案
		1. 我侄子哭得稀里哗啦地跟他妈妈告状,说别的小朋友带他.问他怎么打的,他又不说话.
		2. 读高中时,我们在讨论哪个女生是不是美女.到讨论到闵xx的时候,某个同学一直称呼闵xx为女神.
		3. 比如领导吩咐下一件事情需要我和同事做.我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?
	complex question: 强调的是在问题中给出了一些答案,或者所有子问题答案一致
		1. 老师逮住学生. 你是用左手抽烟还是右手抽烟?
		2. 我老婆问我,你爱不爱我,给不给我买最新的江南布衣的衣服?这里她就犯了复杂问题的错误.
	Question-Begging Definition: 关键在于定义是说话者自己的,还是公众的共识
		1. 邻居说他家狗很乖不会冲人狂吠. 然后我说狗昨天冲他叫了.邻居说,他冲你叫了但是没咬你,所以它不会冲人狂吠.
		2. 有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?

** 前提/结论不一致的案例
前提与前提不一致:
	1. 新二 a perfect alibi 那一课.
			嫌疑犯声称自己有a perfect alibi.
			嫌疑犯说:当谋杀发生时, 他正在8点去往伦敦的火车上, 理由是他10点已经在伦敦工作了.
			而侦探说: 他没有坐8点去往伦敦的火车,理由是8点去往伦敦的火车停运, 并且8点25的火车也可以10点前到达伦敦.
			这里嫌疑犯给出的前提和侦探给出的前提不一致,所以得不出他有perfect alibi.
	2. 上帝是全知全能的. 那么上帝能不能造出他举不起来的石头?
		 能不能造出举不起来的石头,分为两种情况, 一种是造出举不起来的石头, 和上帝全能矛盾.
			另一种是造不出举不起来的石头, 也和上帝全能矛盾.
		 因为前提和前提相矛盾, 我们不能得出任何结论.
前提和结论不一致:
	1. 蛋是由鸡生的,鸡又是由蛋变的
		 但是鸡和蛋不会凭空产生
		 所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

** 违反演绎推理
否定前件:
	1. 家中女性长辈,劝我不要抽烟.如果抽烟,那么就会打短命.不抽烟,那么就会活就一点.
		 不抽烟可能导致其他不良习惯,其他不良习惯同样也可以导致短命.
肯定后件:
	1. 如果平平偷钱了,那么她就会去买零食.
		她刚刚买了一堆零食.
		所以钱是她偷的.
	2. 如果你高考分数高,你可能进入北大
		 你去北大了,
		 所以,你高考分数高.
		 撒贝宁表示北大保送也还行.
	3. 我跟老婆有一天两个人都口臭,我们认为是前一晚都吃了金汤酸菜鱼的原因.
		 如果酸菜鱼有问题,那么我们会口臭.
		 我们一切口臭了.
		 那么那个酸菜鱼有问题.
错误转换: 
	 全部肯定换主谓语:
		所有的生物学家是科学家.
		所有的科学家是生物学家.
	 条件中, 前件和后件互换:
		如果我提前过户了二手房,那么卖家提前还款了.
		如果卖家提前还款了,那么我提前过户了二手房.(还可能卡其他环节啊,比如交契税)
无关中间项和错误分布的端项: 用处不大,用文氏图更直观
		AEIO: 分别是全部肯定,全部否定,部分肯定,部分否定
		AsEbInOp: s=subject, b=both, n=neither, p=predict,代表对应项是distributed
		Term: 中间项出现了前提两次, 两个端项一定出现在结论
		两条法则:
			1. 中间项至少distributed一次(按AsEbInOp判断)
			2. 端项在结论中是distributed,至少在premises中distributed一次.
无关中项和错误确定的端项:
	1. 首先要是三段论,两前提+一结论,前提和结论得是全部肯定~部分否定~全部否定~部分肯定的一种
		 解: 这里要非常注意AEIO和条件句的区别
			AEIO: 所有人都会死
			条件句: 如果他是人,那么他会死
			举例: 全部肯定:所有人都是会死的人
					 部分否定: 一些人不是女人
					 全部否定: 所有人都没有智商超过5w
					 部分肯定: 有些人智商超过200
	2. 全部肯定是主语,部分否定是谓语,全部否定都确定,部分肯定都不确定
		 全部肯定是主语: 所有人都是会死的人, 这里 "人"确定了范围(distributed)
		 部分否定是谓语: 一些人不是女人, 这里"女人"确定了范围
		 全部否定都确定: 所有人都没有智商超过5w, 这里"人"和"智商超过5w的人"确定了范围
		 部分肯定都不确认:有些人智商超过200, "人" 和 "智商超过200的人" 都没确定范围
		 这里记忆还有个技巧. 全部肯定的否定是部分否定, 由主语确定变成谓语确定;全部否定的否定是部分肯定, 由全部确定变成全部不确定.
	3. 两端项和中项各出现两次,中项不会在结论中出现
		 这里就是注意把主谓项规范成一致的.
			比如:
				所有人会死
				苏格拉底是人
				所以苏格拉底会死
				------规范后
				所有人都是会死的人
				苏格拉底是人
				所以苏格拉底是会死的人
				这里有三项且各自出现两次: 人 会死的人 苏格拉底
				人是中项,并且没有出现在结论里
	4. 两法则: 中项必须确定一次; 在结论中确定的端相必须在前提中确认至少一次
			继续上面的例子
				P1:所有人都是会死的人
				P2:苏格拉底是人
				C:所以苏格拉底是会死的人
				1. 根据中项必须确认一次判断, 人是中项
						P1:所有人都是会死的人
						-------
						全部肯定是主语, 人是确定的, 满足了规则
				2. 根据结论中确定的端项,必须在前提中确认至少一次
						C:所以苏格拉底是会死的人
						因为部分肯定都不确认
						所以不需要判断

					 
* Chapter 6 Fallacies That Violate the Relevance Criterion
- 用你自己的话描述不相干谬误
- 能发现,叫得出名,解释谬误的形式,当辩论或生活遇到的时候
- 用有效的策略去帮助别人纠正他们的不相干谬误
(1) fallacies of irrelevant premise
(2) fallacies of irrelevant appeal.

公输般

英国护卫

--------------------
- 用自己的话描述下那些违背相干性原则的谬误
- 在生活和辩论中遇到的时候,遇到了能辨识,叫得出名字,能够解释谬误的形式.
- 用有效的策略帮助别人纠正他们的不相干谬误

论证要有相干的证据.

两类不相干谬误,一种是用不相干的前提,另外一种是各种诉诸.

1. 不相干前提
   从前提推导不出结论:前提和结论没联系,或者前提到结论有跳跃性.
2. 诉诸
  
** Fallacies of Irrelevant Premise
1. 根据旧的情况推断新的事物,无视环境已经发生了变化
2. 用看似有理的原因而不是真正的原因去隐藏掉真实的想法和行为
3. 对理由去做另一番解释,目的是为了得出结论.
4. 为了得出结论,而去编造理由.
  
*** Genetic Fallacy 刻舟求剑
用过去的context去计算现在的事情,无视新旧之间已经发生了变化
wusd: 刻舟求剑

只考虑事情一开始是怎样的,因而忽视了事物的发展,退化,差异.
wusd: 要用发展的眼光看待问题,
什么人容易犯呢?
  1. 把过去看事物的老眼光:或积极或消极,用在现在了
     wusd:
			吴下阿蒙.
		  小米就是钓丝低端的,所以小米su7我完全不考虑买.
			我们经常会根据很久的经历去判断一个人现在到底怎么样,并且这种想法很难改变.
				比如人际交往,第一次如果留下坏印象了,后面就很难再改变看法.
  2. 一些宗教啊,根据原始教义不许做某事,但是到如今已经发生了变化了.
     wusd: 回族人不允许吃猪肉,原本是当时卫生不达标,猪肉脏,吃了易得病. 但是现在科学化养殖,仍然还是禁止吃猪肉.

这种谬误的模式就是:
  前提和结论是要相干的.现在的结论虽然和以前的前提相干,但是前提已经发生了变化,变得不相干了.

EXAMPLE:
	我不会给Don Reichard投任何票,我和他同学的时候,他在学校里完全就是个混子.
	实际上,Don有可能变成熟了,变成了和原先完全不一样的人.
	wusd: 对应了第一种例子.用老眼光看人.那我们同样也不应该用老眼光去看自己.
		因为Don在上学期间是混日子的.(P)
		上学混日子,当官员时会一直混日子(IP)
		所以Don在当官员时同样会混日子.(C)
EXAMPLE:
	因为结婚戒指原本是丈夫用来束缚他们妻子的标识(P)
	而且这个标识会一直做同样的事情(IP)
	这种行为实施了性虐待(P)
	所以,现在谁还用结婚戒指也是实施性虐待(C)

wusd: 这里讲的例子,是有可能变化,但是也有可能没变.所以对于Don能不能胜任官员,需要继续调查.
	对于结婚戒指实施性虐待需要更深入的统计数据
EXAMPLE:
	虽然我听说李医生是一个很帮的医生.但是我不会去李医生那里看病,我跟他同学的时候,他一直看黄片.
	wusd: 虽然吴教授是一个优秀的导师,但是我不会报考他的研究生,因为他以前上学时经常打架斗殴.

ATTACKING THE FALLACY
这些固有印象连接我们的思想,会在我们考虑的时候严重地影响我们对其的喜爱或厌恶.比如:让你去评价下前男友的装修和衣服.
但是当我们要深思熟虑的时候,就要想办法抵制这些因素的影响.
当辩手这么按这种方式想问题的时候,我们就可以反过来问他现在这事物有没有厌恶点或喜爱点.
wusd: 人是感情的动物,想要不受原本的固有印象影响去判断一件事非常困难,要想办法抵制掉这些因素的影响.
	当有人或者自己按这种方式考虑问题的时候,就可以反过来问下这件事当下有没有喜欢点和厌恶点会影响自己的判断.

假如拥有长期亲密关系的伴侣,最开始的约会或见面却是场乌龙或恶作剧.
这对伴侣,肯定不会以最开始的价值来评价现在关系的价值.
如果能够搞清楚这种情况,自然能够正确处理其他事情.

你说林师傅是大厨,但是小时候他弄个馅饼都搞得乱七八糟的,所以我不会吃他做的任何食物.

*** Rationalization 用fake理由去获取体面
用听起来很响亮但实际是假的理由去去主张某个立场,为了体面.
wusd: 两种fake,一种是事实上的fake;
	一种是个人理由的fake,不是这个原因不去做/不做某事,而是其他原因.(找理由说自己做某事,或者不做某事)

出于尴尬~恐惧~其他原因,真实的原因被隐藏了,而使用fake的reasons去推导出结论.

好的论证啊,是由证据推导到信念;而在rationalization里,信念已经有了,前提或理由根据信念捏造的.

因为前提或理由是捏造的,并不支持结论了,那么就和结论不相干.

EXAMPLE:
我考试一向成绩不好.P
考试也不能说明我的真实能力.P
考试前我收到影响我的坏消息.P
----------
我不应该被要求在Law School Admissions Test表现很好.

如果Xavier是个大二的哲学生,那么他可能已经通过大量考试了,否则他升不了大二.
如果他确实考试不行,教授应该早就知道原因,不用再提醒了.

这种坏消息的影响也不成立.
当考生遇到考不过的情况,大概率就是考试太难了.X需要努力提升必需的技能以便在今后的考试中顺利.
如果坚持给这个fake reasons的话,会阻止自己的进步.

wusd: 这我跟读英语的时候,有时候懒了,不想动了.
会自己给自己找各种理由辩解:比如工作累了;今天和老婆逛街了;要陪猫完;今天已经看了好几章的英语了.
实际上做完这些事情我仍然是有精力和时间去做这个跟读的.

EXAMPLE:
我早就计划把他甩了.跟他在一起真无聊.我早就应该甩了他,我觉得他很可悲.

wusd: 我跟我老婆吵架的时候,后面发现是她不对,我要求她道歉.她不想道歉,给的理由是,上次我没给她道歉.
但是实际上我当时道歉了,还转了红包.
这里她确信自己没错,不想道歉,然后认为当时我没道歉.

EXAMPLE:
我觉得本来应该去我侄子的婚礼,但是我们一直走的不是很近.
我只见过新娘一次,人家都不记得我.
我不知道要买什么给人家做结婚离婚,因为他们该有的都有.
而且很多人在这呢,压根不会想我.

真实原因可能就是不想买礼物;不想宿妆打扮;想去看球赛.
wusd: 同事的婚礼,我犹豫了很久要不要去.然后其他同事问我去不去.
我说不知道包多少红包.
不知道人家叫我去是客套还是真实.
人家亲戚朋友那么多,缺我一个不缺.
其实真实的理由就是: 她是在隔壁县办的婚礼,而我没有车,又不太好意思蹭其他同事车,害怕社交.但是又不敢真正说出口.

**** ATTACKING THE FALLACY:
狡辩者大概率是出于要面子,不肯说出真实理由,要让他们知道我知道他没有说实话(论证).

如果是错的或者没关系的,你是不是还是觉得结论是对的.
如果回答是yes,那么他已经承认自己错了.
如果回答是no,就需要找到方法去证明他的错误.最好的结果是,当事人放弃或改变观点了.
wusd: 如果说红包金额可以确认,然后人家真的是请你去,你去不去?
不去,那么就承认了自己有其他原因.
如果去,那么就说明红包金额可以和其他同事确认;告诉他人际交往请你就是真心要你去的.这样就会直面真正的问题,交通的问题.

如果这个人是故意给fake reasons,这个人道德上要被谴责的.
但是注意我们的目标是为了得出好的论证,不过过多聚焦让这人出丑上.

*** Drawing the Wrong Conclusion 搞不清楚重点,得到错误结论
定义:得到一个结论但是这个结论不是证据支持的.

这个谬误又叫搞不清楚重点.怎么个搞不清楚重点呢?各种证据都指向某个结论,但是arguer却说得到了另外一个结论.

有时候这种谬误是故意的.比如空方律师指控嫌疑人犯有强奸罪,而无视证据都指向的是强奸是重大罪行.

犯这种谬误有时候是忽略了一些信息,有时候因为微妙的~下意识的或者有偏见.
比如: arguer希望证明一些结论,但是目前的证据还不够证明.
	像: arguer非常关心社会对于女性的不平等待遇,所有性歧视的行为都被拿出来证明应该立法保护女性.
		但是实际可能仅仅说明文化有性歧视,还不足以到立法的程度.

EXAMPLE:
因为我坚信婚姻的神圣性.P
----------
所以,婚姻应该有一男一女.C

这里就是没有说清楚,婚姻的神圣性和婚姻应该是一男一女的关系.
然后像神圣这种事情,根据clarity principle 应该解释神圣的定义.

EXAMPLE:
靠管理员定期抽查来evaluate学校老师的方法是不合适的.P
如果老师非常差的话,是没有有效办法解雇他的.P
----------
老师应该按学期雇佣,再进入市场,然后再雇佣.C

或许是应该按学期雇佣老师,但是这里得不到这个结论.得到是,应该找更好的检查办法,把那些不合格的老师找出来.

wusd: 
公司副总要求员工不允许走消防门上下班.
理由是消防门开着会导致闲杂人等的进入.

得出的结论应该是应该加强消防门的管理,比如规定时间内消防门开着,员工进出需要关门,而不是禁止员工进出消防门.

EXAMPLE:
记者让消息公开,消息公开有助于正义伸张.P
记者同时有让官员诚实,并且暴光他们不当行为.P
----------
仅仅是因为他们没有披露信息来源就送去监狱,是法院对他们的不公.

wusd: 知乎上经常在社会有不公的事情,信息披露不透明的时候.
说平民批评那些公知,然后得出结论平民罪有应得,共知不该被批评.
实际上,应该区分具体的事情.有些公职经过时间检验确实是被无端怒骂,比如李开复当年的言论自由论.
但有些共知确实是做错了事情被骂.
得到的结论应该是,对于批评共知,要更好的社会规范.而不是说批评就是不对的.

记者对于社会的贡献并不能推导出法院对他们的不公.

**** ATTACKING THE FALLACY
当别人犯这种谬误的时候,告诉他这些证据可以得出什么结论.
因为他情感上可能不愿意接受嘛,慢慢罗列下证据和正确的结论.
如果他不管正确的结论,就告诉他原本的结论需要哪些证据.

对同事:你和我有共同喜欢的东西,两人住比一个人住要省,我们可以一起坐车上班.所以我们应该结婚.

*** Using The Wrong Reasons 先有结论,再去找理由
定义: 用不恰当的理由去支持结论.
wusd: conclusion再前,using the wrong reasons, conclusion在后的,drawing the wrong conclusion

Wrong Reasons 和 Conclusion转化成标准形式后看起来是一样的.
但是Wrong Reasons是先有了结论,再用错误的理由去支持结论.因为想要证明特定的结论,又没有找对理由.
而Wrong Conclusion是先有理由,再有结论.因为丢了理由的大意.

为啥会犯这种谬误呢?
arguer已经非常相信结论了,然后就把所有有关的理由都拿出来当证据,认为是恰当的.还有就是找不到恰当的理由.

wusd:
知乎上有人说楼下要装室外雨棚的时候,笑眯眯地,非常有礼貌.
但是当他要把衣帽间改成淋浴室的时候,就一直阻挡他不让他施工.
这里arguer认为自己把衣帽间改成淋浴间是对的,因为他也让楼下装室外雨棚.

wusd:
武林外传中,吕秀才刚分手的时候....

一些程序一些政策,经常被攻击没有达到某某效果,应该被取消.
一个是程序和政策的设计者,本身有时代的限制.
另外一个是程序和政策的目标是理想情况,并不难完全达到.
有些时候程序和政策的设计目地并不是要达到声称的效果.
比如:比如某某法律的存在,有人攻击说不能阻止犯罪的发生.但是可以起到威慑犯罪的作用,减少罪恶的发生,也达到了其目的.

EXAMPLE:
烟草证明造成癌症-P
烟草很贵-P
二手烟对其他人很冒犯-P
----------
特殊人群不该被投放烟草广告-C

这个得出的结论是不应该抽烟,得不出投放烟草广告的结论.
虽然结论本身是对的,但是需要其他理由.这个用了错误的理由.

EXAMPLE:
哲学不能解决所有问题-P
哲学家还在处理2500年前Socrates的问题.-P
----------
哲学是浪费时间-C

这里得出的结论只能说哲学很有很有很多问题没有解决,而且不能解决所有问题,并不能得到哲学是浪费时间.
这里已经有结论哲学是浪费时间,然后用了两个理由.但是哲学的目的并不是要解决问题.

wusd:
小时候,家长一看我们玩游戏,上网.就会说你又在浪费时间,玩游戏上网又不解渴又不管饱的,又没钱,又不能提高学期成绩.
也是强行把玩游戏上网添加了目的,要有生产力,和能提高学习成绩.

EXAMPLE:
控强法案的批评者: wrong reasons, 应该说空枪会和一些更重大原则起冲突,比如:民主?
	控抢不会阻止罪犯用枪犯罪-P
	----------
	没有理由去通过空枪-C
空枪法案的支持者:
	尽管空枪对于控制犯罪影响有限.
	但是重大犯罪会被严格销售和注册影响.
	可以减少国内的冲突.
	减少激情杀人的数量.
	----------
	尽管有限制,但是荏苒按应该通过空枪.


**** ATTACKING THE FALLACY
用wrong reasons的时候,大部分是conclusion非常对.
这时候你就可以说:你这个结论非常好,非常有意思,但是好像不是因为你给的理由.
然后再把你认为合适的理由抛出来.

对于程序或政策或活动,给他添加不相关的目标或功能的时候.
要想法设法地提醒他,活动~程序~政策本来就是有限的,这样有可能阻止arguer犯这种错误.
如果他坚持的话,就把他附加的不相关的目标或功能给他讲清楚来,让他知道自己在犯错误.

** ASSIGNMENTS
A. Fallacies of Irrelevant Premise
what? how?
1. Karen住社区,P
	 有孩子在学校,P
	 喜欢和孩子一起工作,P
	 在家委会也很活跃.P
	 应该雇佣她为老师.C
	 
	 Using the Wrong Reason 先有结论,再找理由.
		和Drawing the Wrong Conclusion的关键是先后顺序
	 这些都没有办法得出结论,她有能力胜任教师的工作,只能得出结论她很友好.
2. 因为婚纱象征着纯洁.P
	 你不纯洁.P
		因为你怀孕了.SP
	 因此, 你不应该穿婚纱. C.
	 
	 Genetic Fallacy 刻舟求剑
	 以前白色婚纱象征着纯净,但是现在已经发生了变化,只要对对方忠诚的就行了.
3. 我不屑跟那些势利眼相处.P
	 我造就滑雪两次了.P
	 因此,邀请我,我也不会去.C

	 Rationalization fake理由
	 要面子,不去的理由不是这些原因,就是因为没被邀请
	 
4. 因为我是为了看playboy有大幅的篇章关于伊拉克士兵战后创伤.P
	 所以我订阅playboy是为了看好的文章.C

	 Rationalization fake理由.
	 懂得都懂,好吧
5. 有博士学历的不一定能当好老师.P
		许多没博士学历的教师比有Phd的要强.SP
	 我认为我们不该请个博士在化学部.C

	 Drawing the Wrong Conclusion 丢失重点,得到错误结论
	 只能得出结论, 博士不是加分项.
6. 虽然节食后减肥了,我社交没有得到提升.P
	 节食没用.C

	 Using the wrong reason 先有结论,再为结论找理由
	 先有节食没用的结论, 再去找理由,社交没提升.
7. 我不想让孩子去BS. C
	 Boy Scount是非法的军事组织 P
		 他们以军队侦察兵指南训练孩子 SP
		 scouts指的就是军队的scouts SP

	 rationalization fake理由
	 可能就是没钱去,但是又不能说
8. 我们应该用pass-fail系统 C
	 分数说明不了学生的情况P
		 学生得到了B,只能说明很少关于她在这么课程的工作 SP.
	 
	 Drawing the wrong conclusion
	 应该得到的结论,是分数是有缺陷的,而不是该用Pass-fail

	 

** Fallacies of Irrelevant Appeal
靠不当权威,大多数人的意见,武力或威胁,个人利益,操纵这个人感激~态度~偏见.
这些都是没有提供实质性的证据去支持结论,都是不相干的.

*** Appeal to Irrelevant Authority
Definition:靠权威去支持自己的立场,要么是非该领域的权威,要么是未认证的权威,要么是有偏见的权威.

怎么样才能称得上是一个权威?
1. 专业要对口,而且还要足够的能力在这方面发表出正确的意见
2. 要没有偏见,并且没有个人利益的冲突.
wusd: 很多上其他课程的老师,声称新概念已经过时了.

靠该领域权威去支持自己的观点是非常好的方法.
但是当这个权威违反了CriticalThinking的原则,仍然是fallacious.
wusd: Sharleen老师举得那个老师在证明自己的观点的时候,这个老师本身在教育上小有成就,可以认为是一个权威.
但是他证明自己论点正确的时候,并没有用论证的方式,而是操纵大家的情感,大家害怕被人认为什么都不懂.

诉诸不当权威最可能出现的情况是跨领域,一个著名的受人尊重的人很有可能乱入其他的领域.
比如: 文体明星代言汽车消音器~除草剂;生物学家支持宗教的断言;政治家视为婚姻和家庭专家.
wusd: 经济学家王福重,农民懒惰愚昧不值得同情.

没有认证过的专家也不该被拿来支撑自己的观点.
wusd:佳洁士的广告,穿着白大褂的人士,做的那些牙龈实验. 未经证实的小报消息,无论是xx明星出轨了,政府要下达xx禁令了.

还有一些涉及到个人利益的权威,虽然说有足够的技能,专业也足够的对口.对其观点仍然是质疑的态度.
wusd: 有些老师声称新概念已经过时了.

总结下: 能力要够(没跨领域), 要认证的, 没有偏见的(利益相关的)

EXAMPLE: 
因为一些未认证的来源说政府要对50%以上的水污染负责.P
水污染是道德上错误的.ImplicitP
所以,政府错误地污染了国家的水供应.C

对于美国政府来说可能是这样的,但是其消息来自于未经认证的来源,无法判断消息的真假,所以应该是不予采纳.
除非能验证消息来源.
wusd: 但是有些消息虽然没有出处,也无法验证来源.需要衡量按照这些消息做事的利弊,如果利大于弊,还是应该按这样去做.
比如:口罩期间,传出来马上要丰城的消息,大家蜂拥出去屯粮食.

EXAMPLE:
我认为我们应该接受新的课程计划.
因为这些课程计划被学校理事会一直统一的.
这些人一直负责学校的运转,一定同样指导什么课程计划最好.

跨领域朗,学校理事会更多负责财务和人士组织的,而课程教学更多的下发给了下面的学院.专业不对口.
wusd: 程序员被人叫去修电脑.或者程序员在修电脑上面指导江山.

EXAMPLE:
议员,如果你认为FBI涉及到违法活动,为什么不让局的头和他的成员在法庭上作证?

大多数情况,是应该局头来调查的,因为是相关的权威,但是这些事情可能涉及到局本身,所以有利害相关.
wusd: 我在买房的时候,发现房子有租房的痕迹.问中介,中介说没有,说是自己在自住.

**** ATTACKING THE FALLACY
如果是未认证的权威,就问其要认证.
如果没认证的,就视为和claim无关好了.
如果经过认证的,就再具体看是否符合其他的标准.没有跨专业领域,是否利益相关,其他的推理标准.
wusd: 他说专家说,喝枸杞有助于增强心肺功能.
	那么我们就可以问下,是哪位专家的.
	如果他说,反正就是专家,那么直接无视掉就好了.
	如果他说了,是张文宏医生.我们一看他是病毒专家,并不是营养学专家,就可以对其论据存疑了.
	然后再看其言论是否有论证,是否符合论证的标准.

要慎重地判断这个权威是有偏见,因为经常会编造出一个权威专家是有偏见的,这样会阻碍真相的发现.
如果你怀疑一个专家有利益上的冲突,你应该指出来这种存在的可能,而不是直接指出说这个专家要么是偏见,要么是不诚实.

遇到这种跨领域权威就很好办.
直接问: 你会用姚明去支持健将的内裤吗?
如果他说,两者不一样.那么你就问两者到底哪里不一样.

最后,不要害怕名人名头大,不要怕这些人的光环效应.他们确实在自身领域非常优秀,但也仅限于自身领域.

*** Appeal to Common Opinion
定义:证明某个立场仅仅是很多人接受,或者反对某个立场仅仅是非常人接受它.

这个谬误有时候叫随波逐流,有时候又叫大众的支持.
然后,一个断言是否正确,不会因为有多少人支持它而改变.
wusd:有些特殊例子涉及博弈论,有个谣言说,食盐马上紧缺,赶紧去抢盐.
	大家都去抢盐,不相信谣言的人不去抢盐,就会倒霉.
	银行挤兑也是如此.

尽管,我们说电影,食物拍很长的队一般都会比较好吃的.
但是也要注意,人群不一定以擅长判断,而且还有很多其他因素而不是好吃能解释排了很长的队.
wusd: 比如,风景好网红打卡点,又或者店员很漂亮很帅吸引了很多异性.

用很多人支持/或很少人支持去证明/否定一个观点,都是不相干的引用.
一个好的argument必须要一些能支持观点的因素去决定.

EXAMPLE:
吸大麻没事,据华尔街报调查60%以上的美国成年人不觉得吸大麻有事.

wusd:吸大麻没事,美国那么多州都没有禁大麻.
	小时候有个姑姑不让吃辣条,有个叔叔说,好多人家都觉得吃辣条没事,人家的小孩都吃辣条,吃辣条就没问题.
	事实上,吃辣条确实是对身体不好.

EXAMPLE:
wusd: 正好遇到吴亦凡的粉丝刷榜....

**** ATTACKING THE FALLACY
这个fallacy日常很容易犯.所以你要经常提醒自己,从大众都支持某件事情,得不到这件事情的任何正确性.

你可以提醒arguer,大众的意见是善变的.
比如:关于某件事的意见,从支持到反对也才过了6个月,你是支持6个月前的大众意见,还是现在的.

如果arguer仍然不相信,你可以支持即便是科学和历史上有些事情被很多人认为是正确的,经过一定时间发展后改变朗看法.
最后的办法就是使用你对手的个人类似的经历.

*** Appeal to Force To Threat
定义:威胁人接受观点而不是提供证据.

告诉别人相信什么,做什么会导致什么样的后果是对的.
但是通过告诉别人后果来证明结论是对的,就犯了谬误.

相信某个权威的话,不是因为他有足够的技能,而是因为他有武力或影响力.
这个时候,充满威胁的demand就取代了要支持结论的证据.

AARP的说客要求国会议员投票某项法律,理由是AARP代表来1万多个投票者.
wusd:这就是某些组织机构,以权势压人,而不是靠证据说话. 梳头亚伯.

EXAMPLE:
性骚扰事件中,上位者威胁如果不发生性行为,就把你的未来搞黄.
虽然能达到目地,但是并没有证明事情的合理性.

EXAMPLE:
学生:为什么我们必须参加客座讲座,这是课外时间也没有列入到大纲里?
教授:因为这是我要求的.
wusd:公司组织周末参加团结.
	上学时,学生质疑老师的罚款行为.老师说我说的.

EXAMPLE:
当地女老板提醒报纸编辑: 我花了很多钱给你们报纸打公告.我期望我醉驾被逮捕,不要出现在报纸的故事里面.

**** ATTACKING THE FALLACY
我知道如果我不接受你打算对我做什么, 但是有没有什么好的原因让我去接受它?

wusd: 公输班
于是见公输盘。子墨子解带为城，以牒为械，公输盘九设攻城之机变，子墨子九距之。公输盘之攻械尽，子墨子之守圉（yù）有余。
公输盘诎（qū），而曰：“吾知所以距子矣，吾不言。”
子墨子亦曰：“吾知子之所以距我，吾不言。”
于是楚王召见公输盘，墨子先生解下衣带，用衣带当做城墙，用木片当做守城器械。公输盘多次用了攻城的巧妙战术，先生墨子多次抵御他。公输盘的攻城器械用尽了，墨子先生的抵御器械还有富余。
公输盘屈服了，却说：“我知道用来抵御你的方法，可我不说。”
墨子先生也说：“我知道你要用来抵御我的方法，我也不说。”

*** Appeal to Tradition
定义:尝试去说服别人靠对于传统的尊敬,而不用证据,尤其是很有更重要的原则.

按传统做事会很舒服,因为它是早期智慧的结晶,有很多事情直接就有了解决方案(比如社交).
但是传统并不是做事的最好方式,尤其是有什么更重要的原则出现的时候.
wusd:不听老人言,吃亏在眼前.确实是老人经历一系列事情,对于事物规律的总结.
	但是也要考虑到事物是否发现了比较大的变化.

许多传统有不好消极的一面,很多传统造就不公,还阻碍调整更好的方法去做事情.
如果指出,某个事情做是因为传统,那不算fallacy也不算matter.
但是,如果这个传统和经过深思的方案相违背了,就要认真考虑按传统做事的利弊了.
如果传统有严重的消极有害的事物,还继续拿它说事,就是fallacy了.

EXAMPLE:
在我们这,男孩按传统要割积极皮.P
没割皮的男孩早晚会发现自己的身体.P
[我们应该遵循传统,除非和一些更重要的事情冲突].IP
[没有更重要的事情].IP
因此,父母应该给它们孩子割包皮.C

1. 原来教会要求这些,现在已经不要求了.
2. 割包皮的好处不再被医生支持了.
3. 割包皮又痛又要花钱
wusd: 认真考虑做事的利弊,之前不被宗教歧视的利已经没了,又有坏处

wusd: 缠足

EXAMPLE:
	你们一家满门加入进会教,就你加入基督教.
wusd: 传统是家庭加入进会教. 更重要的事情是加入基督教的考量.

EXAMPLE:
	你要气死老祖宗吗?女子不能入学是规矩.
1. VMI是公立大学靠纳税人养的
2. VMI入学政策对女性歧视
3. 法庭已经声明不允许学校这么做.


**** ATTACKING THE FALLACY
告诉你对手按传统做事没错的,甚至要鼓励按传统做事.
但是当有更重要的事情出现时,就要重新考虑是否要按传统做事了.

*** Appeal to Self-Interest
定义: 让某人接受或反对某个观点,仅仅是出于它个人利益考量,尤其是还有更重要的事情要考虑的时候
wusd: 对比appeal to group loyalty, 有利益的损失

什么是更重要的事情?
就是对比个人,会影响更多人或者对社会有重大的影响.

如果没有与公众利益冲突,那么考虑个人利益是对的.
如果和公共利益冲突,还优先考虑公共利益,那么就犯了不相干谬误.
比如: 马云在杭州有两套房,不会影响他是否提议征收二套房的税,他应该考虑的是对公众的好处.

如果我们仅仅因为个人利益的考量,那我们是逻辑和道德都有问题的.

EXAMPLE:
因为这个政策会减少收入和增值税.P
这个政策对你有好处.P
	因为你收入高还有资产多.SP
所以,你应该支持这个政策

减少税,会影响政府的正常运作,增加国家债务,整个国家造成严重的经济问题.
wusd: 环保问题,少数国家出于本国利益工业生产,乱排乱放,最后全球的国家一起买单.

EXAMPLE:
我认为你会支持这个程序
因为你是女人
这个程序能帮助女人从男人手上拿回更多岗位.

wusd:比女人更重要的是,公众的利益.

EXAMPLE:
教授,如果没有语言要求,非常少学生会上这门语言课.以后你招生会困难.
所以你应该支持有这个语言要求.


*** Manipulation of Emotions
定义: 说服人靠操纵这人的情感而不是提供证据

这个fallacy又叫playing to the gallery, gallery指的是那些糊涂的公众,容易受感觉和偏见操纵.
想不想,就根据对于idea接受程度和被动接受,而不是根据证据.

- the appeal to pity 诉诸怜悯
- the use of flattery 奉承
- assigning guilt by association 敌人支持什么,我们就反对什么 
- appeal to group loyalty 诉诸对圈子忠诚,没有好处
- appeal to shame 诉诸羞耻
pity是常见的操作情感的方式,就是用自己的悲惨去说服别人接受/拒绝某事,而不是提供证据.
wusd:在孩子们打架的时候,往往更惨的孩子,会被认为没错.

虽然说诉诸同情不能解决问题,但是有些情况下因为可能伤害某人会改变自己的行为.
其实同情是一个隐藏的道德论证.
如果在当前情况下,除了道德考量有更重要的事情,或者没有道德考量,那么诉诸同情就是个fallacy

恭维讨好本身没问题,但是把恭维讨好当作证据的替代品就是fallacy了.

当你的对手说服你接受/拒绝position,靠得是你不喜欢的人/群体对这个position的态度.
因为喜欢一个人/群体就接受它们持有的观点,因为不喜欢一个人/群体就不接受它们的观点,都是非常愚蠢的,尤其是把这个当证据.
wusd:敌人越是反对,越是说明我们做对的.

我们一直给自己划圈子,也会去维护圈子的利益.
但是当有更重要的事情要考虑的时候,再去维护圈子的利益,就是一种fallacy了.
wusd:大义灭亲? 有人举报奶奶种麻.

当我们没做错啥也没有什么不对的时候,用让我们羞愧的方式,让我们去支持某些观点.
wusd: 聚会时,男A女免.
	
EXAMPLE:
the use of flattery

你非常懂股市,知道股市如何运作的. P
你不会没有研究我们是什么公司,就找到我们. P
所以,你应该使用我们公司的服务. C

这里马屁就在您非常懂股市,知道股市如何运作,会在找上公司前做研究.

EXAMPLE:
appeal to pity...

因为Nicole可怜又孤单.P
	因为她一年没约会,也没有去跳舞.SP
没人邀请她去春节舞会.IP
她愿意去舞会.IP
Brad能够并且还没带人去舞会.IP
因此,Brad应该带Nicole去舞会.C

这是一个moral论证,这里implicit moral前提没有明说.
是"一个人有义务去帮助另一个人排除孤单寂寞"还是"一个人应该花周末的时间去拜访可怜又孤单的教授呢".
如果说约会的意义,就在和对自己有吸引力的人一起度过快乐的时间.
而Brad因为同情就决定是否邀请Nicole, Nicole自己会不开心,这样是fallacy的.
如果Brad因为喜欢而邀请Nicole,那这样才不是fallacy.

EXAMPLE:
appeal to group loyalty

因为被指控的强奸犯是你姐夫.P
你知道他有罪.IP
因为你目睹了或知道他有罪.IP
你可以选择在法庭上说谎.IP
告诉事实可能把你姐夫送去监狱20年.P
出于对家庭的忠诚你应该撒谎.MP
因此,你应该撒谎.C

公正比对家庭的忠诚更重要.法大于情吧.

EXAMPLE:
appeal to shame

任何有素质的人刚才都会给女士开门.

男人不用为了不给人开门而羞愧,仅仅因为她是女的.

EXAMPLE:
assign guilt by association

你为什么给议员Hamilton投票?
每个Gay,lesbian都支持她.
[你非常讨厌Gay,Lesbian这些群体,所以它们支持的,你就要反对]
所以,你不给投票.


**** ATTACKING THE FALLACY
当一个人知道的少或没有鉴别力的时候,操纵情感是最有效的,即便是有思想的人也容易被自己情感的敏感点操纵.
所以,我们有必要做特殊努力不让自己被操纵.
被操纵情感并不必操纵者的罪过要少,更重要的是,不要让说话者操作我们的情感而是提供相关的证据.

对于the use of flattery,没有必要去攻击拍你马屁的人,但是要注意不要被马屁影响自己对事物的衡量.
即便你知道他拍马屁影响你的衡量,你可以说谢谢然后继续正确~合适地衡量事物.

对于诉诸同情的,可以公开承认确实唤起你的同情了,也特殊声明你不会让同情干涉你的判断.
指出,如果只考虑这些同情,就会有可能错过更重要的原则.

1. 可以直接了当地说,不论是谁说的,不管是不是敌人,只要说的有道理,那就要听.
2. 指出来,如果敌人反对什么,我就支持什么,敌人支持什么,我就反对什么.
	 敌人改变看法怎么办?那我岂不是要跟着转,跟个傻子一样.

因为这种不相关的谬误,很容易找出相关的证据来提升,可以告诉她,这是不相干的,能不能举出相关的证据.
如果她举不出来,你就带头重新审时这个论证,找出相关的证据.

*** ASSIGNMENTS
B. Fallacies of Irrelevant Appeal
1. 我不能投票给他C
	 我是Democrats,而他是Republican P
	 民主党不能投票给共和党 IP

	 manipulation of emotions-appeal to group loyalty
	 我要忠于民主党的圈子,不能投票给外部.那怕有更重要的原则出现,为人民考虑.

	 check:appeal to tradition
		have *always* been = have traditionally been

2. 你要以我的名字命名,结婚时候.C
	 你给我不尊重,就分手. P
	 如果我们结婚,你拒绝以我的名字命名,对我来讲非常尴尬. P
	 
	 appeal to force or threat
	 用分手来威胁,结婚时必须...

3. 你不应该反对联邦对于教会学校的帮助.C
	 我们天主教知道我们教会学校多缺钱.P
	 如果说这些经济援助没有通过,很多教会学校必须关门.P

	 manipulation of emotions-appeal to group loyalty
	 说话人试图利用圈子的利益操作情感

	 check:appeal to self-interest VS appeal to group loyalty

4. 你要买我们的度假房.C
	 我们带你飞去Florida没花你钱.P
	 我们在Gold Grown3天提供免费的肉给你吃.P
	 带你去Disney World. P

	 appeal to shame 诉诸羞耻
	 我给你免费的服务,所以你要给我买房子.否则你就要羞耻.

5. Dr. Chamberlain没法说明被告在犯罪时的精神状态. C
	 Dr. C是被告家庭的朋友很多年. P

	 assigning guilt by association 连坐罪
	 因为是朋友,所以没法出示证据,那怕是客观的证据.

	 check: Irrelvant authority
		Dr. 是一个和个人利益冲突的权威,无法作证.

6. 你不能去Annapolis.C
	 我们一家人always去西点. P

	 Appeal to tradition: always

7. 在你结婚时,你应该取你丈夫的名字. C
	 很多美国妻子结婚时,都取丈夫的名字. P.

	 appeal to Common opinion
	 大家都取丈夫的名字,所以你也取.

8. Professor B,你不应该公开反对课程计划. C
	 总统和主教在积极推动这件事. P
	 你的位置也还不稳. P

	 appeal to force or threat
		force是总统和主教, threat是位置不稳.

9. 
	 要支持我的重新选举. C
	 如果部支持我的选举,就没有好路哦. P
	 
 	appeal to self-interest: 好处是好路

10. 要给张老师年度教授. C
		他好可怜,他老伴死了好多年. P
		给他年度教授可以cheer him up. P

		appeal to pity: 可怜哦

11. 控枪是错的. C
		因为麻州的投票者抵制. P

		appeal to common opinion:
			很多人反对,所以是错的

12. 法律对婚约的干预是离婚的第一原因.C
		因为Oprah说的. P

		appeal to Irrelevant Authority:
			不当权威,Oprah专业不对口.

C. fallacies whihc violate relevant criterion
1. 你不应该让你爸妈同时走长廊. C
	 一贯没有人让自己母亲在婚礼上走长廊的. P

	 appeal to tradition:
		always

2. 我儿子要这个赛季要通过考核. C
	 如果没通过考核,我要重新考虑我们的50000项目资金. P

	 appeal to Force Or Threat:
		Threat: 要让你少50000项目资金

3. 你应该减少NCAA rule对运动员新生的要求. C
	 如果你减少了要求,那么你会有更大的生源,甚至成立学院. P.
	 你应该尽可能获取帮助. P

	 appeal to self interest:
		self interest: 有更大的生源了

4. 我要去Weight Watcher减肥. C
	 因为Weight Watcher说他们是唯一安全有效的方法. P

	 appeal to irrelevant Authority:
		Authority是Weight Watcher, 断言和自身利益相关

5. 我不会去EH 大学. C
	 它会对女性歧视. P
		因为它过去是完全男性大学.SP

	  Genetic Fallacy, 用老眼光看变化的事物

6. AIDS不会游泳时传播. C
	 没人相信外科医生说的AIDS不会在游泳时传播. P

	 appeal to irrelevant Authority:
		专业不对口,该找传染科
	 check: appeal to common opinion
		nobody believe

8. 我让Matt赢比赛的. C
	 我最近身体状态不好,不喜欢在太阳底下玩. P
	 早餐没吃. P

	 Rationalization 合理化
		事实可能有,但不是输比赛的原因.

9. 我不该学习,应该无视考试. C
	 无论多么努力学习,考试总考不好. P
	 总是在学错误的东西. P

	 Drawing the wrong conclusion:
		得出结论应该是改善学习方式和内容

10. 我是经济处罚的支撑者. C
		当前的纠正犯罪方法无效. P
		 因为释放的罪犯总是重回监狱. SP

		Using the wrong reason:
		 纠正犯罪方法无效,只能得出取消/改善纠正犯罪方法,的不出要支持经济处罚.

11. 让我们没票进去吧. C
		你阻止我是在执行公务. P
		如果我们有更多公仆像你一样,街道会更安全. P
		感谢你. P

		the use of flattery 拍马屁

12. 不应该改变签约程序. C
		我们用了30多年了,一直这么用. P

		appeal to tradition:
			一直!!!

13. 你应该考虑华盛顿*李大学 C
		如果你不去,我跟你妈不给学费. P

		appeal to force or threat:
		 赤裸裸的威胁

14. 新规划的区域不应该允许开饭店. C
		开了饭店,把我们顾客抢了,我们没钱赚了. P

		appeal to self interest:

15. 甜味剂有阿斯巴甜的都对你非常不好. C
		我听说阿斯巴甜甚至分解DNA. P

		Using the wrong reasons:
			有结论阿斯巴甜对身体不好,然后找理由 分解DNA.
		check: appeal to irrelevant authority
		 未经证实的消息	

16. 我不会加入女生会. C
		我妈说女生会有捉弄新人的习俗. P
		I hate 这种旧习. P

		genetic fallacy:
			从她玛到他上学,已经过去了几十年

17. 经济处罚道德上立得住的. C
		因为有70%以上的美国人同意. P

		appeal to common opinion

18. 我没通过考试是因为老师不喜欢我. C
		我在课上和他有过不同意见.P
		我和其他同学对过答案,人家答案和我一样,分数比我高. P
		而且, 我父母今年很困难,我无法集中学习. P

		Rationalization: fake理由
			没通过考试,找各种理由合理化自己.

19. 你应该和500ml VC每天. C
		V对我们日常diet很重要. P
		V可以帮我们补充日常所需. P

		Drawing the conclusion

20. 我们应该建游泳馆. C
		游泳是最有效提升心血管的运动之一. P
		游泳不需要特殊设备.P
		游泳馆可以终身使用.P

		Using the wrong Reasons

21. 不应该建立国家安全计划. C
	  这是Cliton一直不允许的社会医疗. P
		
		Appeal to Force or Threat:
			Force是Cliton
		check: manupulation of emtions
			appeal to group loyalty,而不管公民的利益

* Chapter 7 Fallacies that violate the Acceptability criterion
- 用你自己的话描绘违反了acceptability原则的fallacies
- 在讨论和日常对话中,能辨别出,叫得出名字,也能解释它的模式是怎么犯的谬误
- 用有效的策略去纠正或帮助别人去纠正这些谬误

某人支持或反对某个论点,应该使用能被理性~成熟的人接受的理由,理由要符合Acceptability标准

7条acceptability标准和5条unacceptability条件,满足一条标准又没有un条件,那么就是可接受的.
wusd: 7+5?

fallacies分为两组: 1.语言混乱的谬误; 2.无正当理由假设的谬误.

** Fallacies of Linguistic Confusion
什么是Fallacies of Linguistic Confusion?
前提里面有关键的单词和短语在意义上没有明确,这样的前提不可接受,那么论证也同样是错误的.

- equivocation: 在一个论证当中,对某个word or phrase用不同的含义,(歧义)
- ambiguity: 用word可以被解释成两个或两个以上的含义,(多义)
- misleading accent: 说话者在word phrase口音过重,导致unwarranted conclusion.(误导口音)
- illicit contrast(不当不同): 听者自己强调word和phrase,导致得出不同的结论
- argument by innuendo(映射): 用暗示结论去操作语言,而不是明确提出来.(含沙射影)
- misuse of a vague expression(误用模糊的表达): 从模糊的expression得到明确的推论,或者用模糊的expression捍卫某个论断
- 操纵语言,把没有不同的两件事,搞得好像有不同.

*** Equivocation 含混,偷换概念
定义:一个单词在论证中有两种含义,偷换概念,导致得出无正当理由的结论.

一个人故意或者不小心地改变了word的含义,这种情况在长的argument里尤其容易被隐藏.

单词有两个含义,含义A成立的前提,含义B不成立,得到关于含义B的结论就是错误的.

EXAMPLE:
gambling(赌博)应该合法化.C
人们每天都在gamble(冒险)P
gambling(冒险)是人类生活的一部分.P
gambling(冒险)是不可避免的.P

含义由冒险->赌博

EXAMPLE:
跟我们争辩的人,根据faith信念接受事物的人,和我们没有区别.C
他们也依赖宗教信念faith,P
他们的时角在对科学的信任faith.P

第一个faith指的是找某本书或人的武断的观点
第二个faith是指论证的力量.

EXAMPLE:
我不学逻辑.C
教授说学了逻辑,教你如何去argue.P
argue只会增加冲突.P

1-argue: reason推理
2-argue: 吵架


**** ATTACKING THE FALLACY
3方法attack:
1. 指出单词的两种含义.
	 如果他不同意,就让其明确定义.
	 如果定义不同,就会证明确实有这个fallacy
2. 就用第一个单词的含义,代入到第二个单词里面.
	 就会得到有错误的前提,或者前提和结论不一致.
3. 用明显荒谬的反例.这样别人就知道自己犯什么错误了.
	 Therefore, no women is rational. C
	 Since only man[human] is rational.P
	 and no woman is a man[male].P
	 wusd:
	 校长是我儿子.C
	 校长是中国人民的儿子.P
	 我是中国人民.P

*** AMBIGUITY 歧义,词汇和语法歧义
定义: 引导其他人得到无正当理由的结论,通过word pharse或者语法结构可以被多重解释,又不明确那种解释方法.

如果前提是多义的,那么得到的结论就是不可接受的.因为结论依赖于前提的acceptability.

semantic ambiguity:含义多义
绝大部分单词是多义的,用单词本身不是fallacious.
但是在论证中,单词用法没有确认,前提不是确定的,就会导致出现不合适或错误的结论.

syntactical ambiguity:语法多义
	- unclear pronoun reference: 不明确的代词
		Fred never argues with his father when he is drunk.
		wusd: 到底是他drunk,还是他爹drunk
	- elliptical construction: 晦涩的结构?有些单词不该被省略
		Susie loves teaching more than her husband.
		wusd: Susie 到底love teaching 超过他老公,还是Susie love teaching 超过他老公爱teach
			改成Susie loves teaching more than her husband does.
	- unclear modifier:不明确的修饰词
		I have to take my makeup test in an hour.
		wusd: in an hour可以指马上要考试了, 也可以指考试得在一小时内完成
			in an hour到底修饰什么
	- careless use of "only": 不小心用了only
		We only accept American Express Travelers Checks.
		wusd:  是不接受其他种类的check,还是连现金也不接受.
	- careless use of "all"
		All of the fish Doug caught weigh six pounds or more.
		wusd: 到底是Doug抓的所有的每条鱼都重6斤以上,还是Doug抓的所有鱼加起来6斤以上.

如果说只有多义的premise支持结论,那么结论肯定是错的.

EXAMPLE:
Fred的论证:
Ed的车在停车场. C
Ed提出要给我便车回家. P
我接受了这个便车. P
他不能提供我便车如果他的车不能用. IP

Ed的论证:
Fred的车一定在停车场. C
Fred同意我搭便车的要求. P
他不会同意,如果他的车不能用的话. P

wusd: 这个问题就出在 How about a ride home?
	How about giving me a ride home?
	How about taking you a ride home?
	elliptical construction

EXAMPLE:
Last term I took Logic and Introduction to Philosophy?
wusd: elliptical construction
	到底怎么断词的. Logic   Introduction to Philosophy, Logic and Introduction to Philosophy?
	这个前提搞不明白,的不出任何结论.
	
每逢节假日，他时常丢下工作和妹妹到公园玩耍。

EXAMPLE:
Personal Security for Women Has Been Canceled for the Rest of the Semester.
wusd:
女性住所走廊不会再有安保?
女性安保的排版不会在学期表上出现.
问题出现在 the rest of the semester, 到底是学期, 还是说是学期表.

EXAMPLE:
Doris should turn right here. C
Kenny knows how to get to the destination. P
Doris is willing to follow those directions. P
Kenny says to turn right here. P
wusd:
turn right here到底是现在转,还是在这里右转.这里是有歧义.

女孩给男孩打电话：如果你到了，我还没到，你就等着吧。
如果我到了，你还没到，你就等着吧!


**** ATTACKING THE FALLACY
wusd: 书中错误 equivocation->ambiguity
别人犯多义的问题,不论是意义的多义还是句法的多义,问清楚他到底是啥意思.
不要怕别人说你挑剔,这不挑剔.如果不懂文字的意思,那这个论证的价值也就无法体现.

如果说他不可能再澄清,那就靠你自己对他的认识,代入他猜可能的意思.
没有澄清的情况下是得不出结论的. 但是你没办法的时候,要去猜他是什么意思,得出相应的可疑的结论.
得到后面有更多信息的时候,你就很容易知道可疑的结论到底是什么了.

要注意不要冤枉别人犯了多义的错误,要多注意听了.比如"Pizzas免费配送",你就不要问Pizza免费还是配送免费了.
wusd: 怎么避免呢???手里有事或者心里有事的时候,叫别人先等等.在自己没有准备好之前,不要和别人沟通重要信息.
	胶囊-Halsey@胶囊助学计划 invited @你 to the group chat
	这个就是自己犯了多义的错误, 其实是明确的这个你是网名, 而不是代词代指你-sherwin.

别人误解你的给的前提得出不合适的结论,不要怕.
反过来问他,你那里说的有多义来着.

*** MISLEADING ACCENT 过分强调单词或短语和断章取义
定义: 特意强调某个word,phrase,特殊的角度,导致推导出毫无理由的结论.

这个fallacy不单单发生在广告~头条,还有日常生活.
- 头条,里面的标题可能与内容不符合. wusd:震惊...
- 广告,只强调质量,却不说溢价.只说优点方面,却不说致命的缺陷.
- 新闻文章只告诉我们一党在法院说了什么,却不说另一党也说了同样的话.
wusd: 雷军打电话给某个评测机构,小米手机的缺点你已经说了,那优点为什么不说?

断章取义了, 从一大片中取那么一小部分,然后缺乏上下文里面真正的含义.

EXAMPLE:
Clinton被弹劾期间,网上媒体说他1996年竞选收受10 millions不正当的捐款.
一天后,第二家媒体Clinton接受了10M,而Bob Dole接受了17M.
这里第一家报纸就是不完全报道,或者就是Mislead accent.

Clinton的竞选团队应该追责. IC
因为Clition的竞选团队非法收受10M美元. P
这种行为违法. IP
违法了就要被追责. IP

EXAMPLE:
父亲在跟别人聊三个孩子的时候,聊到大女儿.
如果强调, *She* 不乖.那就是说他大女儿不乖,其他都怪.

EXAMPLE:
老师告诉小明,叫小红感觉交作业,如果她今天不交,老师就再也不收她的作业了.
然后小明告诉小红,老师说他再也不收他的作业了.

A1:
小红想,我得赶紧交作业.C
如果她今天不交,老师就再也不收她的作业了.P
A2:
小红想,我不用交作业了.C
老师就再也不收她的作业了.P

**** ATTACKING THE FALLACY
这个fallacy犯的频率和歧义差不多.
当你怀疑是过分强调或断章取义的时候,问更多的上下文.

还可以打预防针,总在有更多上下文的时候得出结论.
比如:看头条时,看完标题一定要看看内容(更多上下文)才得出结论.

最好保持一个怀疑的态度,甚至被人认为太天真了或者无知的情况下.
遇到自己怀疑是过分强调或者是断章取义的,要问出更多上下文,再下自己的判断.


wusd:在如何对待老婆网购这件事情当中,我主动了这种fallacy.
	总是看家里有非常多的快递,和一笔笔花出去的钱.
	没有去看,家里多了那些东西,这些东西的质量如何,实际使用的体验又是如何.

wusd:
	最好是保持一个怀疑的态度,在任何人告诉你一件事情,你要得出结论之前.
	都需要问自己一个问题,这里的上下文足够得出结论吗?
	如果自己深信不疑,那么可以认为结论有一定的可接受度.
	但如果自己还要说服自己的时候,就需要再去问问更多的上下文,再修正自己的结论.

*** ILLICIT CONTRAST 错误相反
定义:听者从其他人的claim中得到另一个相关但是不同的结论, 通过特殊强调一个单词或phrase

简单来讲就是, 比如X对Y是正确的,那么非X对Y就不是正确的.
wusd:
有个人请客，看看时间过了，还有一大半的客人没来。
主人心里很焦急，便说：“怎么搞的，该来的客人还不来？”
一些敏感的客人听到了，心想：“该来的没来，那我们是不该来的啰？”于是悄悄地走了。
主人一看又走掉好几位客人，越发着急了，便说：“怎么这些不该走的客人，反倒走了呢？”
剩下的客人一听，又想：“走了的是不该走的，那我们这些没走的倒是该走的了！”于是又都走了。
最后只剩下一个跟主人较亲近的朋友，看了这种尴尬的场面，就劝他说：“你说话前应该先考虑一下，否则说错了，就不容易收回来了。”
主人大叫冤枉，急忙解释说：“我并不是叫他们走哇！”朋友听了大为光火，说：“不是叫他们走，那就是叫我走了。”说完，头也不回地离开了。

有时候说话的时候过于紧张,导致某个词说重了.
别人就会以为你是不是在说相反的方向,实际上你并没有这个意思.
虽然别人犯了这个错误,但是是因为你没有表达好.你犯了misleading accent导致别人犯了...

EXAMPLE:
女人经历场失败的恋爱经历说,男人都是麻木的野蛮人.很容易错误地得到结论,女人都非常敏感.
这个女人仅仅只是说她和男人的最近一次经历.
并且,即便女人说男人都是麻木的.也不得出结论,女人都非常敏感.

EXAMPLE:
神父玩弄童年是有罪的.
容易错误得出结论:神父玩女人和女孩是没罪的.


EXAMPLE:
我爸认为衣服穿我身上不好看. C
因为爸爸说我的以前衣服穿妹妹身上好看. P
尽管他没有说穿我身上不好看,他暗示穿我身上不好看. IP

Dad对妹妹: Well, it looks very nice on you.
wusd: 姐姐错误地以为Dad强调了you, 暗示穿她身上不好看.
	还有种情况,如果是Dad没有这个意思,但是又不小心地强调了you.就犯了Misleading accent.

**** ATTACKING THE FALLACY
如果对方认为你有这个反面的意思,你应该坚持让对方解释为什么说你有这个意思.
因为你本来就没有这个意思,天然就是有优势的.对方也知道你没有这么说,关键是你自己到底暗没暗示和愿不愿意defend it.
wusd:
作为speaker发现别人犯了这个谬误时,应该把举证的责任给对方.
你既然说我有相反的意思,那你就说一下.因为你本身没有这个意思,一定是占优的.
对方当然也知道你没有明说,关键是你到底有没有相反的意思和愿不愿辩解.

现实当中,当双方地位不平等的时候,对方又犯了这种错误的时候确实是很难去捍卫.
比如: 你老板误解你的意思;你女朋友误解你的意思;你没法defend it, 当众defend老板可以卷铺盖走人,defend女朋友,no sex tonight.

别人说你听错了,你可以清楚地说自己没搞错或者愿意去讨论未声明的claim.
然后,否认自己有这个unstated claim, 和这个否认unstated contrasting claim是两回事.
wusd:
作为listener时,别人说你错误地听出相反的意思了.你可以把未声明的判断说出来,可以拉出来讨论讨论.
但是,否定自己是否下这个判断,和这个判断本身是否正确就是两回事了.
比如: 我没有那个意思,你长得丑. 跟 你是否长得丑 是没有关系的.

*** ARGUMENT BY INNUENDO 影射 误导
定义: 通过有技巧性的语言选择暗示但实际上没明确结论,引导某人得出某个特殊,尤其是侮辱性的结论.
wusd: 说话人 有主动性了

影射的威力在于其产生的错觉,即便没有证据支持,未明说的论断依然是对的.
通常用于攻击某个人~某个组织当没有证据或很少的时候,被用来弥补没有证据.
根据arguer影射的暗示,得不到任何正确结论.

speaker想要通过没有证据得出结论,不是一个好的argument.
wusd:
小红发微信给老板: 我怀孕了.
然后被老板娘看到了,误以为...
小红后面又说, 我来请个假,怀孕了不能上班.

EXAMPLE:

MONICA: Tonya和James仍然一对吗?
PAM: 根据James, 他们是.
MONICA: Tonya在跟其他谁约会了?

PAM的话暗示, Tonya没有认为James和她是一对 或者 Tonya在跟其他人约会了
wusd: Illicit contrast?有点不同,因为PAM是故意的有这个意思.

James and Tonya现在不是情侣关系. IC
因为James认为他和Tonya是情侣关系. P
James不知道Tonya怎么认为, 或 怎么做. IP

wusd: James的话有问题,暗示 Tonya没有认为James和她是一对 或者 Tonya在跟其他人约会.
Monica直接把James没有证据的暗示的当真了.
两个人都有问题, james直接犯错, Monica把不该接受的premise当premise

EXAMPLE:
有些时候话多了一点,就会造成这种影射,即便话都是对的.
假设董事问学生主任,潜在的雇员加入学生时是否有任何纪律的问题.
学生主任,直接说没有,那没事了.但是学生主任说,没有,我们没有能力去判断是否有.
这样会减少雇员的就职机会,造成不良影响.
wusd: 这里就暗示雇员有.
可见话不要多说,多说会产生暗示的作用.

我想请领导过去吃饭,但是又不确定领导周末有没有空.!

如果学生主任说:没,目前还没.
董事就会得出错误的结论,但是学生主任并不会愿意负责,因为他没明说.
wusd: 学生主任意思是他后面会有.

EXAMPLE:
如果你知道候选人非法收受钱,是否会影响你投票的结论呢?
看一看我的对手竞选的资金来自于哪里.
事实可能会使你震惊.

wusd:如果你知道你未婚妻的历史,你是否会重新考虑结婚?
	看一看你未婚妻以前做过什么吧.
	事实可能会使你震惊.

EXAMPLE:
我经常见Iskra,但是没有和他老婆一起.

wusd: 暗示她跟Iskra有一腿.


**** ATTACKING THE FALLACY
没有arguer会为自己没说的话负责,所以你应该把你得到的结论跟arguer确认.
如果他不确认的话,就认为他没说过,结论不成立.

wusd: 待整理
没有arguer会为自己没说的话负责,所以你应该把你得到的结论跟arguer确认.
如果他不确认的话,就认为他没说过,结论不成立.不要去相信!
别人暗示归暗示,除非他暗示的,是对你有益的而且搞错了对你无害的.
否则都不要相信,更不要根据暗示采取行动.


*** MISUSE OF A VAGUE EXPRESSION 模糊表达的误用
定义: 试图去拥护某个立场,通过模糊的表达的方法; 或者是得到无正当理由的结论,通过把别人模糊的表达加上了精确的意义.
wusd:
 VS 含混: 没有明确的情况,直接使用了明确的定义

模糊表达使用没错,日常生活也常用.
但是如果把它用在重要的事情上,就错了.

模糊表达误用有两种:
1. 用来支持/反对某个立场的前提的关键字是模糊的.
	 根据可接受条件,前提无法被理解是不能支持其他claim.如果前提的关键字意思不明确,那么前提就无法被理解.
	 当然也不能被反驳.如果我们不知道关键字的范围,那么我们无法反驳.
		比如: 员工说自己过劳,首先要明确过劳是什么,然后才能反驳.
		
2. 从别人模糊的表达中得出结论.
	 从别人模糊的表达得不出他想要的含义.
	 想要得出结论,必然会给表达一个明确的意义,这都是武断的.
	 从武断的前提中得出的结论也必然是武断的.

含有模糊表达的前提是不用用来支持其他claim的,
同样的也不能得出任何明确的结论.

EXAMPLE:
公立学校学生不该被布置读那类文学书. C
州立宪法规定公立学校追求"道德教育"作为其目标. P
要求学生读文学,使用了有问题的语言或者有不道德行为描述的是违反了宪法的规定. P
	这些文学是"不道德教育"或教不道德. IP
学校理事会应该遵守宪法.IP

这里道德教育是模糊的.按有问题的语言或有不道德行为描述,那么圣经也是不道德.
这里批评家对于"州立宪法规定公立学校追求"道德教育"作为其目标."的道德教育模糊词,给了自己明确的意思,并且从其推出结论.
犯了第二种错误.

EXAMPLE:
校主席建议我们应该对那些差生更多关注,那些因为挂科而辍学的学生.
一个成员旧说,在主席强制让他给挂科的学生通过的分数前,他会辞职.

这个成员对校主席模糊的前提, "对那些差生更多关注"加上明确的定义.
犯了第二种错误.

EXAMPLE:
法律宣布"什么是色情的应该被社区公约所决定."
控方律师想控告, 书店老板把色情材料放地上是违背了规定.
	这玩意能对一半以上的人是冒犯的,那么就是色情

书店老板在地上摆成人杂志是违法的.C
如果违背了社区公约,那么就是色情的. P
书店老板的行为违背了社区公约.P
	书店老板行为对社区一半以上的人是冒犯的.subP
		(因为无偏见的投票是困难的)几个"平均市民"指认杂志是offensive.subsubP

1. 控方律师用模糊的表达"community standards",给其下定义 对社区一半以上的人是冒犯的.
2. 违反community standards,并不代表违法.

**** ATTACKING THE FALLACY
attack this fallacy和attack歧义谬误一样,当含义不明确或者范围不确定的时候,问别人明确的意义或者约定好.
如果这里模糊对argument影响很大是值得attack的,如果没影响,直接忽视模糊就好了.
wusd: 模糊跟歧义很类似, 模糊更强调是精确程度,某个含义本身不精确(比如范围), 而歧义更多强调有多个含义,而每个含义都是精确的.

想要避免自己犯模糊的问题,在重要或有争议的事情不要用模糊的语言.
去寻找新的词去代替原本模糊的表达,至少明确可能模糊的单词的意思让其清楚表达出你想表达出的意思.

你的模糊的语言天然就吸引其他人给明确的意义.
比如:有人跟你说:听说你很关心污染问题,周六你去帮我们捡高速上的垃圾.
这里关心污染问题,他就强加了含义,捡垃圾.
因为模糊的语言得不出任何结论,不要怕这种操纵人的技巧.
别人对你的话没有解释权.
wusd: 我的关心污染问题,不是去捡破烂. 你没有权力去解释我的话.
我不接受你解释我的话.
1. 不自证（反复提醒自己） 
2. 反问: 关心污染问题，只有去高速捡垃圾吗？

如果有人用带有模糊关键字的前提去支持claim的时候,同样去挑战前提的可接受度.
wusd:你用来支持结论的前提的关键字没有讲清楚,没有办法接受.

*** DISTINCTION WITHOUT A DIFFERENCE 换个说法,实际一样
定义: 尝试去捍卫某个行为或立场,不同于另外一个立场,实际上只是言语上有点区别但是没有本质的不同.
wusd: 我不反对男女平权,但是女士优先.
	有点像狡辩,狡辩是找不是理由的理由,而这里是避重就轻.

最有可能犯的场景是某人为了减少尴尬,当持有站不住脚的立场或者做了什么不好的行为.
所有人都自由地给自己的术语自己的含义,但是如果新的含义和原来一样,是没有实质的不同的.
通常这种情况发生在甲的观点受到挑战,甲换了个说法,实质上挑战并没有减少.

如果前提不明确意义的,不会是好的论证.
某个前提说它们是不一样的是可疑的,因此是不可接受的前提.

EXAMPLE:
我没有反对女权的意思,仅	仅只是认为男人应该是一家之主.

我没有反对女权. C
我相信男人应该是一家之主. P
男人是一家之主和女权没有矛盾. IP
wusd: 男人是一家之主 VS 反对女权

这里的论证,隐藏的前提, "男人是一家之主和女权没有矛盾", 实际上是错误的,虽然arguer认为是对的.
它至少代表了对于女权的误解.

EXAMPLE:
我不是一个差司机. C
我仅仅没有注意路. P
没有注意路和遵守路的规则没有矛盾. IP
wusd: 开车不注意路 VS 遵守路的规则

EXAMPLE:
我们应该根据Bible说了什么来判断问题,不该由我们认为他说了什么,或者专家认为它说了什么.

Bible说了什么,归根是有听者自己来解释这一步,无论是普通听众亦或是专家.

wusd: 
根据Bible说了什么判断问题(比如要有我们的理解)   VS  根据我们认为它说了什么


**** ATTACKING THE FALLACY
因为大部分人不清楚他们尝试性的区别没有实质的不同,第一步要做的是指出这样没有用.
如果他质疑你的指出,你可疑问两者在意义的区别在哪里.
如果你没有被他的解释说服,你可能需要教下他语言了.
可能效果不是很大,直接用反例好了.
我没有抄袭,只是用她的纸然后记下我的记忆.

*** Assignment
A.
Equivocation 含混 2 9
Ambiguity 歧义,词汇和语法歧义 14 7
Misleading Accent 过分强调(口音或者描述多)和断章取义 10 3
Illicit Contrast 错误相反 5 12
Argument by Innuendo 影射 误导 8 1
Misue of a Vague Expression 模糊表达的误用 13 6
Distinction Without a Difference 换个说法,实际一样 4 11
1. 
		你老公和新来的助理有一腿. IC
		你老公最近工作晚. P
		新来的助理也晚. P
		--------------------
		Argument by Innuendo:
		没有明显的证据,他老公和新来的有一腿.
		但是两个工作晚暗示有.
2. 
	 上帝存在. C
	 你知道风的存在,因为你可以feel感受到到风,即使你看不到它. P
	 你不能看到上帝,你能feel感受到上帝. P
		 --------------------
		含混: 这里feel的含义论证中被替换了,feel的风是有实际的触觉,而feel上帝是心里的感觉.
3. 
		洛杉机红衣主教有罪于性虐待. IC
		Los Angeles Cardinal Sorry for Sex Abuse. P
		--------------------
		MISLEADING ACCENT:
		标题只强调了sorry for,但是没有说具体的行为是给受虐的人民钱并致以歉意.
4. 
		我没有对你撒谎. C
		我只是夸大了事实. P
		 --------------------
	 DISTINCTION WITHOUT A DIFFERENCE 换个说法,实际一样:
	 内容上夸大了事实就是说谎,只是换了个说法
5. 
		Robin之前一直不舒服. C
		Robin今天感觉好舒服. P
		 --------------------
		ILLICIT CONTRAST 错误相反: 你今天很舒服, 相反地就是说你之前不舒服.
6. 
		我不会穿大衣和领带在餐厅. C
		大学手册包含餐厅礼仪:要穿得体的衣服. P
		--------------------
		Misue of a Vague Expression:得体的衣服种类很多,是模糊的概念.被说话者当明确定义用了.
7. 
	 John: Sofia教的烹饪课. C
		Laura: Sofia下周开始她的烹饪课. P
		--------------------
		Ambiguity:
		开始烹饪课有歧义的,可以是当学生,也可以是当老师.有歧义的关键字得不出结论.
8. 
		她没有参加慈善晚会. IC
		她来我们的会议了!(是否参加晚会的回答.) P
		 --------------------
		ARGUMENT BY INNUENDO 影射 误导 VS  Misleading Accent:???
		对于是否参加慈善晚会可以有明确的回答,Yes or No,单单说没有参加会议,给人误导她只参加会议,并没有参加慈善晚会.
9. 
	  对于William Smith总统的安全顾问的调查是通过媒体和国会去毁掉一个无辜的人的名声. C
		因为一个人是无辜直到被证明有罪. P
		--------------------
		Equivocation:
		这里无辜的定义被偷换了.
		前提的无辜是没有证据发现是否做错的无辜.
		后者的无辜是没有做错的无辜.
10. 
		 医生非常急缺. IC
		 两个医生要服务50,000病人. P
		 --------------------
		 AMBIGUITY 歧义,词汇和语法歧义:
		 医生和病人没有给明确的定义, 可以是普通医生和人,也可以是兽医和动物,属于词汇歧义.
		 --------------------
		 Misleading Accent:过分强调
		 只说了医生和病人的数量,但是没有说医生和病人的属性.只强调数量,没有说质量.属于过分强调
11. 
		 我不是在打击的自信. C
		 我只是认为你父母应该直到你告诉我什么. P
		 --------------------
		 Distinction Without a Difference
12.
		Depaki: 你认为我不努力学习. C
		Shandra: 我今天不外出,我要努力学习. P
		Depaki今天外出.
		--------------------
	  Illicit Contrast	:
		不外出就是努力学习 -> 外出是不努力学习.
13. 
		 Diss是个军事的批评者,我不投票给Diss. C
		 我不知道Diss期望他是个开明者. P
		 --------------------
		 Misleading Accent:
		 强调了其批评军事,但是投票的理由不仅仅是军事方面. 对Diss的评价断章取义,过分强调某一面了.
		 --------------------
	  Misue of a Vague Expression:
		由Diss不是开明者,很模糊的概念,推导出他是个军事批评者.
14. 
		 SELA得出结论:Dad又能又不能的很奇怪. C
		 Jolie问Dad帮忙微积分作业时,他说他不能. P
		 SELA说Dad对于微积分的理解对高中时候帮助很大. P
		 --------------------
		 Misue of a Vague Expression: .含混是偷换概念
			 Jolie说的帮助微积分作业没有明确定义,可能是直接写,也可能是教.
			 SELA直接理解成教了,然后得出结论. -> 用其他人模糊的表达得出结论.
		 --------------------
		 AMBIGUITY 歧义,词汇和语法歧义:
		 "不能"有歧义,可以是时间上不能,也可以是能力上不能.
		 
** Unwarranted Assumption Fallacies
这章讨论的谬误中的前提是建立一些很流行但是很可疑的假设.
因为假设不可接受,所以前提不可接受,论证也不可接受.

大学棒球队明年会有更好的教练,因为会辞掉旧的来新的.
这里的假设就是新的比旧的好,但是实际上不可接受.

这些假设是一些智慧,但是有时候是对的,有时候是错的.
1. fallacy of the continuum
	 连续的事物程度的小范围不同影响会微不足道.
2. fallacy of composition
	 部分是对的或是错的,所以整体也是对的或是错误的
3. fallacy of division
	 整体是对的或是错的,所以部分也是对的或是错的
4. is-ought fallacy
	 目前情况是这样,所以应该是这样
5. wishful thinking
	 一相情愿
6. fallacy of the mean
	 错误的中和
7. false analogy
	 错误类比

把这个不可接受假设暴露出来,重新构造这个argument,谬误就会非常的明显.
假设不可接受->找出前提的不接受,前提不可接受且是argument关键支撑部分,那么argument也不可接受.
	 
*** Fallacy of the continuum 连续体无法叠加和无法分界
定义: 错误的假设: 1. 在事物和其反面,做一点连续的不同,影响微不足道;
							  2. 因为在同一条线上的两个点,做不了区分,或者区分是很武断的.
wusd:微小的变化产生了巨大的影响,或者微小的变化导致事物已经变质(必须设定区别/界线).
	复利拐点,急于求成,耐心一点再耐心一点

只是程度问题.只是一点小改变没本质的不同.
经常会导致相反的结论,只是要和中间状态的一点不同相联系.
会导致无法认识到什么会导致巨大的不同,以及极端和相反的转折点.

"压死骆驼的最后一根稻草." "温暖和冷的夜晚的分界线" "少女怎么变成妇女"
尽管在连续的事物上细微的区别上做区分看起来有点武断,但是非常有必要做个区分.
如果没有做这个区分,就不知道微小的变化产生了巨大的影响,或者微小的变化导致事物已经变化.

多少毛算是胡子呢?
多少速度算超速呢?
给其一个分界线看似很武断,但是如果不做区分,没办法辨别有胡子还是没胡子,也没办法断定是否有罪超速.

"小变化不重要,小相反也没有什么不同."
这个假设是不可接受的,由此得到的前提,前提支撑的结论也不可接受.

EXAMPLE:
你可以买新手机.C
用卡刷新手机,卡每个只是由300->325.P
用卡付月费,卡由325->385.P
小变化不会产生大影响. IP

Aris可能卡本身有限额,或者支付不起月供.

EXAMPLE:
我应该加6分,这样我就60分不挂科了.C
如果他能加5分,就能加6分. P
	5分和6分差别很小.subP
Tim加了5分后就60分了,我加了才59.P
Tim不比我厉害多少.P

EXAMPLE:
什么戒烟和减肥的人没有被欺骗过,一只烟和一个甜品没有什么关系?

wusd:
我和我老婆最近发生的矛盾,我认为买个400块的电饭煲就够了.
我老婆认为既然花了400,那么再加个300买个好点的,也就加300块钱.
我认为太贵了,我老婆认为不贵.这里就没有明确的界线,到底怎么样算贵.
可能要根据这个月的支出,收入来判断这300块钱到底有没有产生质的变化.
--------------------
雅思6.5 VS 7: 是应用级别还是熟练级别

**** Attacking The Fallacy
犯这种谬误的人很容易被引导到荒谬的情况.
问他多少钱算有钱人?他说X,然后问他少1000算有钱人吗?
如果他说说,就一直减下去,知道后面变成X-X了.
他就明白了,微小的变化也会产生巨大的影响,或者导致事物的性质发生变化.

有时候这种事物的区别必须设定.
比如:一点分数觉得篮球的输赢,决定是否通过课程.
尽管看上去只是连续事物的一点小变化,但是是否挣这么一分钱决定产品是否有利可图,仅仅一点点速度决定你是否超速.
wusd:防微杜渐 & 遇到瓶颈耐心等待
	积累还不够多，拐点还没到水还没有煮到100度就不会沸腾

*** Fallacy of Composition 合成谬误
定义: 假设某个事物整体的部分是对的,因此整体也是对的.

wusd: 团队粘合剂型的人物!!!

这个假设虽然在某些情况下是对的,但是不能作为通用的断言.
任何前提使用这个假设都不是可接受的.

这个谬误主要发生在,因为各个部分相互关联~影响,使得整体的特性和各个部分的特性产生了不一样的变化.
一个整体的特性由各个部分特性所贡献,并不是仅仅是因为整体由部分组成.
比如: 棒球队的每个选手都非常优秀,并不一定队伍优秀,还需要队员把各自的技能融合到队伍里.

别把这个fallacy和从很少的例子推导到整体的fallacy搞混了,后者是证据很少,前者是整体的性质跟部分的性质一样.

这个fallacy的instances有些很容易察觉.
比如: Paul,你我都喜欢玩,我们一起度假肯定很开心.
比如: 我喜欢橙汁也喜欢牛奶,放一起肯定更好吃.
也有些fallacy很难识别.

EXAMPLE:
这课会很牛. C
这课会被教的很好. SC IP
	Pour教授和Warden教授打算一起上课. SP
	它们是最好的老师. SP
	因为部分牛,整体牛. ISP
教的好的课会很牛. IP

有可能教的好,是因为他俩对于课堂的把控好.
但是由于是团队控制课堂,和单人完全不一样,这样会导致控制力度消失.

EXAMPLE:
我们的合唱团会很牛. C
由30个很牛的歌手. P
因为部分牛,所以整体牛. IP

有可能歌手的声音互相干扰,导致声音合起来反而不好.

EXAMPLE:
dan和Rebecca会是一对好夫妇. C
Dan是好人. P
Rebecca是好人. P
因为部分好,所以整体好. IP

可能它们不合适.

wusd:
我想学会读单词,单词发音由音标组成,我把音标学好了,我的单词发音就会好.
我想英语造好句子,句子是由单词组成的,我把单词学好了,我就能造好句子.
文章是句子组成的,我把句子造好了,就能把文章学好.
就好比说,我认识26个字母,所有单词由字母组成,所以我认识单词.
我们会觉得非常可笑.
但是很多人学语音的时候,常常会犯错误,以为学会音标就够了.

**** Attacking The Fallacy
认识到整体并不总是等于局部的性质非常重要.
每碗里面的一勺是美味,并不代表整碗是美味.

有些场景,一个断言的证据是关于局部的事实.
你可以告诉对手,为什么他能根据局部的特性得到整体的特性,因为在有些时候局部确实提供了证据.
另一方面,你可以用例子给他诠释,这种方式的荒谬.
例子: Julie上衣漂亮,裤子漂亮,鞋漂亮.但是整体却不搭.
你应该指出来,这里错误的假设了局部的特性会自然的传导给整体.

*** Fallacy of Division 分解谬误 
定义:假设整体是对的,所以局部也是对的.
wusd:
	广东人都是包租婆;安徽人都很穷;上海人都排外;
	如果转换一下,几个上海人排外得出上海人都排外,那么就是合成谬误了.

分解谬误和合成谬误正好相反.
分解谬误是整体是对的,因此局部是对的.
合成谬误是局部是对的,因此整体是对的.
然而,整体和个体的性质总是差异很大.

在概括的时候,由整体的数据去推导局部的性质也是犯了谬误.
因为整体的只是统计概率,表示了整体的趋势,并没有额外地说明和局部个体之间的关系,因为不能用整体的性质来说明局部个体.
wusd: 可能这个局部是特殊的.

整体是对的,然后局部总是对的,是不成立的.
被概括的整体是对的,并不能推导出每个成员,特殊成员,或者一类是对的.

EXAMPLE:
我不想去维京大学. C
因为我不想去大学上大课. P
维京是很大的大学. IP
维京有大课. IP
	因为整体是对的,所以局部是对的. I SP
wusd:
我不想去维京大学. C
因为我不想去大学上大课. P
维京有大课. IP
	维京是很大的大学. SP
	很大的大学有大课. IP
	因为整体是对的,所以局部是对的. I SP

这里的谬误是从概括的整体里推导出某个个体.
而且,维京有大课,不代表你的专业要上大课.

EXAMPLE:

wusd: 刘亦菲长得很漂亮,所以她的鼻子,眉毛,耳朵,脸都很漂亮.

EXAMPLE:
尽管人是有意识的,但是我们不能得出每个细胞是有意识的.

**** Attacking The Fallacy
attacking分解和attack合成差不多.
告诉你的对手,你明白他为什么从整体的性质得出局部的性质,因为确实提供部分证据.
同时也告诉他,按这样会得出非常荒谬的结论.
比如:美国某个州是多元化的,因为美国整体是全球多元化的.

对于概括性的分解,比如:数据说电脑不会在使用的前三年就坏,得出你的电脑没可能在前三年坏是非常荒谬的.

*** False Alternatives 错误选项 
定义:过度限制对于问题的回应的选择,然后假设其中一个肯定是正确答案.

这种False ALternatives也叫非黑即白谬误~要么要么.,要么是问题过度简化导致看不到所有的答案,要么是把答案数量搞得太少,
而且还认为在这些答案中肯定有正确答案.
wusd: 先假设有正确答案,然后再做排除法,最后得到一个错误答案.
道法术器,过度,当然我说是过度,沉迷于器.实际上犯了这个谬误,隐藏的假设,要么不用工具,要么用最好的工具.
其实还有个选择,够用就好了.

这种要么要么,把contrary相反搞错成了完全相反contradictory,认为两个选项black and white没有中间状态.
wusd:
contradictory: 完全相反,hot or not-hot
contrary: 相反,黑白,中间还有灰色.

contrary有大量的中间状态,可能既不是黑的,也是黑的反义词白的,而是五颜六色的
比如有人说要么是黑的,要么是白的.实际可能都不对,是红的.

EXAMPLE:
流产是道德上禁止的. C
因为流产或是道德上允许的,或是道德上禁止的. P
仅仅只有一种道德选择. IP
没人在道德层面允许流产婴儿. P

还有一种选项, the moral permissibility of abortion

wusd:
我在公交车的时候,看到一个老人向一个男的寻求帮助,然后那个男的拒绝了.
后面那个老人向另外一个女的寻求帮助,女的帮忙把老人搀扶上车.
在车上,老人和女的一直对男的怒目而视.
这里好像就有一种非黑即白了.
帮老人就是善良的,不帮老人就是有罪的.

那还有一种可能,就是无功无过的.

EXAMPLE:
耶稣说,你不为我,那么你就是反对我.
你如果不是有神论者,那么你就是无神论者.还有种可能是不可知论者.

wusd:
在某个组织里面,要做某项决议的时候,某个领导说:举手表示反对,不举手表示同意.
那实际上还有第三种选择,表示中立.
这里还涉及到了诉诸武力或威胁!

EXAMPLE:
世界要么是神造的,要么是偶然产生的.
这里就把contrary当作contradictory,无视了中间状态,因果关系导致的世界产生.

**** Attacking The Fallacy
真正的完全相反的情景是很少的,当你面对仅仅有两个选择的,要保持一个怀疑的态度.
即便是arguer忽略掉多余的选项,多余的选项仍然是存在的.

对于这种限制性的选项的谬误,问arguer这些选项是否穷尽了有道理的选项.
如果arguer不愿意或不能提出新的选项,那么你就自己提出来,然后挑战arguer告诉其为什么他们不足以穷尽所有选项.
这样问题就变成了选更有道理~有证据的选项了.

*** Is-Ought Fallacy 存在即合理
定义:假设某事现在是这么做的,所以应该做;某事现在不在做,所以不应该做

事情现在是怎么的,就是最好的;事情应该这么做,因为它们就是这样.
并没有给出理由去支持事情应该这样,单纯假设事情是对的,因为它在,事情不在,那它就不应该在.

虽然和诉诸传统一样都是说维持现状,但各自的理由不同.
诉诸传统是因为要尊重传统,所以维持原状.Is-Ought是因为现在这样的,所以就应该这样做.
wusd: 从来如此,便是对的.  VS 现状如此,便是对的.

和诉诸公众的区别在于,诉诸公众是多人支持或反对,所以某个意见就是对的或错的.

前提里包含Is-Ought的假设是不可接受的,因为Is-Ought并没有提供为什么是对的证据.

EXAMPLE:
下个春天我们应该去法国以外的地方. C
因为我们的practice春天一直去不同的地方旅游. P
现行做法是这个做法,所以应该这么做. IP
我们已经去过法国了. P

我们一直去不同地方旅游,不能为现在不去相同的地方提供理由.

EXAMPLE:
大麻是违法的.如果它没问题的话,它就不会是违法的.

大麻现在违法的现状,并没有为大麻违法提供了任何理由.
wusd: 家长教育青少年的时候,说xxx行为不好,就说是违法的,并没有说明为什么是违法的.

EXAMPLE:
T: 在学校学生应该多参与决策的过程.
B: 事实就是学校没那么民主. 我们不要瞎搞那些机构的事情. 聚焦更值得我们注意的事.

B甚至没有想过把民主介绍给机构的可能性,仅仅是因为事情不是那么民主.

**** ATTCKING THE FALLACY
好的论证总是要证据和好的理由去支持结论的.
如果除了现行做法如此没有证据和理由去支持政策和做法,你应该指出arguer没有证据.
如果arguer把证据和理由说清楚了,你再考虑政策和做法是否值得你的支持.

现状是很多人被性别歧视,不能成为支持性别歧视的理由.
wusd:
当程序员发起996.icu项目的时候,很多人反驳是这样说的,工厂里面一个月只休息两天.
用现行做法就是加班不休息的普遍存在的情况,来维持996的合理性.

也可以举反例,因为很多司机超速了,所以司机应该超速.

*** Wishful Thinking 心想事成
定义: 假设因为某人相信某事会成,所以它就是对的或是将会成.相信某事会黄,所以某事会黄.
wusd:普信男
吵架的时候我就是知道
车刀山前必有路; 船到桥头自然直

想某事成是没错的.但是希望某事成,并把它当作前提去推导结论,那就错了.
前提建立在这种无道理的假设是不可接受的.

的确,有很多宗教和理想的信念建立在我们非常希望这些信念真成,所以wishful thinking又叫做信念的谬误.
我们经常被告诉,如果你坚信一个事情,那么这个事情会因你成真.
你坚信一个事情,会给你很大的动力去付出更多努力,最后导致事情真的成了.
但是,仅仅坚信一个事情,并不会改变事情.

和rationalization很难区分,但是wishful thinking是真的认为是真的,rationalization是用不相干的理由来让自己体面.

EXAMPLE:
死后肯定还有生命. C
因为很多人渴望死后有生命. P
人民希望什么,什么就是真的或就会是真的. IP

想象一下,大部分都希望自己比自己本身有钱,能成吗?

EXAMPLE:
我丈夫没有死. C
我丈夫失踪10年了. P
我希望他还活著. P

EXAMPLE:
如果你努力寻找,努力去做,你一定有完美的婚姻. C
对于每个人在世界上都有一个完美的伴侣. P
因为很多人希望有完美伴侣,所以有完美伴侣. IP

有些事情由于我们强烈的意愿以及采取的行动,确实是能决定是否能成,但是仅仅是那些我们能完全掌控的事情.

**** Attacking The Fallacy
当你的对手wishful thinking的时候,提出一个反对的证据.你的对手想反驳你的证据,就会提出其他证据,然后放弃掉自己的wish.

你对手wish去支持结论,那你就wish相反的去支持结论.
这样决定谁对谁错的时候,就会去找证据了.

仍然可以举反例: 如果一个女的不想自己怀孕,是否能得出结论她没怀孕.

*** Misuse of principle 规则没有例外
定义: 通过假定规则没有例外错误地使用规则.相反地,尝试去反驳某个规则,通过例外的情况.

几乎我们接受的原则都有例外,没有道理的假定是规则没有例外.
有两种方式:一是没有考虑到规则的适用范围和把其应用到不是用来处理的情况.

二是用例外的情况去反驳规则,也被称为意外谬误.
不管叫什么,使用这个假设(规则没有例外)都不是好argument.

EXAMPLE:
我应该可以在自己房子运行我的二手车生意. C
我想要在自己房子运行二手车生意. P
规则是自己房子我想干嘛就干吗. P
规则没有例外. IP

在自己房子想干嘛就干嘛是有限制的.
比如你不能在自家后院养猪,因为这会影响到你邻居.
这里假设规则没有例外是不可接受的前提.

EXAMPLE:
夫妇不能带婴儿看X-rated电影. C
婴儿18岁以下. P
规则是18岁以下不允许看X-rated电影. P
规则没有例外. IP

这里就是把规则运用在例外的情况.

EXAMPLE:
撒谎不是错的. C
心理医生为了不打击患者的信心对其说谎是正确的. P
规则是撒谎是错的. P
规则没有例外. IP

这里就是利用了撒谎的例外情况,去反驳撒谎是错的这条原则.
各种道德原则有时候是相互违背的,当其发生冲突的时候,要去选择更重要的.
wusd:
善意的谎言. 当谎言没有伤害到别人的时候,真话伤害到别人的时候.
谎言和友善两项道德标准相互冲突,那么友善是更好的选择.

**** Attacking The Fallacy
和你的对手小心地检查规则的意图.
可以展示有些例外情况完全可以接受,并没有违反规则,像婴儿车的例子.
也可以说有时候规则要让位于更重要的规则,像猪场的例子.

可以举对手容易接受的例子.
比如:你的对手同意父母可以按自己意愿抚养孩子,但是绝不会同意把虐待当作抚养方法.

*** Fallacy of the Mean 错误中和
定义:假定在两个极端的中间观点是对的或最好的,因为他是中间的观点.

这个谬误的别名又叫折中谬误.
大家把这种假设当作智慧,中和的是最好的,因为他是中和的.
中间的跟好不好是没有关系的,虽然在有些时候,中间是最好的~公正的,但更多时候看似极端~重大的是最好的处理方法.
任何带有这种假定的论证都不是好论证.

值得一体的是有时候妥协折中可能是唯一实用的解决争端的方法,可以避免持续的钱变少,流血或精神紧张.
尽管用折中的方式去解决这些争端不是错的,但是由此得出结论折中的方案一定是最好的就是fallacious.

EXAMPLE:
冰箱的价值应该是250. C
因为你要卖300. P
我只愿意出200. P
中间的是最好的. IP

看似250对Ray听公平的,但是不是最佳的解决方案.
一方面来讲,250可能是进价,卖家还要赚点利润,250卖家就亏了.
另一方面,200可能就是二手的市场价,已经非常公平,250买买家就亏了.

EXAMPLE:
最好的结论可能是决定论和非决定论之间. C
我无法接受决定论. P
我也无法接受非决定论. P
中间的是最好的或对的. IP

决定和非决定论是两个极端,但是它们也是完全相反的,两者必择其一,没有中间地带.
wusd:
在contradictory的情况下,中间状态有都没有,更不可能有所谓的中间的是最好的.

EXAMPLE:
某种折中妥协一定是最好的解决方案. C
以色列和巴勒斯坦的观点都是极端的. P
中间的是最好的或对的. IP

折中妥协可能能解决巴以冲突,和说折中妥协是最好的解决方案是不一样的.

**** Attacking The Fallacy
当你对手拿中间观点说是最好的,尝试挑战纠正他的立场--不涉及到中间状态.
即便是最后为了解决问题接受了居中的方法,也要让你对手明白,居中方案并不是最佳的.
你不是一个不开明的人,因为好的立场必然被好的argument支持.
wusd:
和老婆买东西有很多争议.
买电饭煲的时候,她想买个700-800的,我想买个200的,我说折中一下,买400的.
其实正确的做法,应该是明确想要什么功能,有没有多个品牌可供选择.
东西质量好虽然贵,但是能用很久,长远看反而省了.
折中的方案确实可以解决吵架,哈哈哈.

如果直接attack没成功,那就荒唐的反例.
比如: 在选票的时候,居中的方案就是所有党派都投.
如果他说某些党派不值得我的选票.你可以这么说你的居中方案也不值得我的选票.
wusd:???
在发工资的时候,你和小李平均一下.
小李干的活不如,凭什么拿我的工资.
那你的居中方案,也不值得拿我的工资.

*** Faulty Analogy 错误类比
定义: 假设因为两个事物在某方面相同,那么它们在其他方面也是相同的,当没有意思到他们的相同的不明显或有明显的不同.
wusd: iphone的广告, 唯一的不同是处处的不同

用类比论证一般用没有争议的事物和有争议的事物,指出它们的共同点,因为这些共同点所以他们在其他重要的方面也相同的.
比如: 拿偷钱和占公司便宜的行为做类比是错的.
用类比的人可能指出很多的相同点和很少的不同点,但是也不是一个好的类比论证.
一个好的类比论证,必须超过这些,比如在比较的时候,把涉及 *议题相关* 的证据提出来.

错误类比犯错的地方在错误地假设了事物在某些地方相同,那么其他地方也相同.
对比的事物可能仅仅表面或不重要的相同,或者在 议题相关的部分相当不同.
如果说没有 *重要相同* 被发现,或 *重要不同* 被找到, 类比马上就错了.
即便是类比里面有重要相同,只有一点重要不同,仍然是非常可疑的,
	因为类比性质就是暗示,甚至好的类比论证很少能做好的例子.
arguer还是要愿意提供其他证据.

EXAMPLE:
丰富的性关系而不只是一个伴侣,会使得体验更加激情和享受. C
一直吃相同的食物听相同的音乐会搞得好无聊. P
事物多样性使得体验更加激情和丰富. P
我们希望在性关系上更加激情和享受. IP
两个事物某方面相似,其他地方也相似. IP

这个类比看似有道理的,但是要成为好论证还得继续说明: 吃相同食物,听相同音乐 和 有相同伴侣的更多相同的地方.
因为涉及到人比食物和音乐这些经历复杂太多了,即便说出一些共同点也很难让人信服.

EXAMPLE:
学生考试应该开卷. C
医生是找信息去做诊断的. P
学生考试也是在解决问题. IP
两个事物某方面相似,其他地方也相似. IP

尽管在某些地方是相似的,都是在寻求帮助去解决问题.
但实际上在目的的区别很大,医生诊断是为了解决病人的疾病,而考试是为了测验学生的成绩.
医生的行医资格,早就检查过了.

EXAMPLE:
你不应该继续抽烟了. C
抽烟和吸砒霜一样都致死的. P
两个事物某方面相似,其他地方也相似. IP

尽管抽烟和吸砒霜一样都致死,但是抽烟要先得病再慢慢死,吸砒霜马上就死,类比不合适.

**** Attacking the Fallacy
找出明显的类比反例可以很好地削弱类比的力度.
比如教授那个例子:
	因为和子女~终身朋友的那种舒适愉悦的感觉值得终身珍视和维护.
	所以和其他人有这种感觉,和他的关系都应该终身珍视和维护

如果举不出类似好的反例,指出来两个事物仅仅是表面相同或者不重要的相同,得不到任何结论.

*** Assignments
B. Unwarranted Assumption Fallacies
Fallacy of the continuum 连续体无法叠加和无法分界 5 15
Fallacy of Composition 合成谬误 4 11
Fallacy of Division 分解谬误 6 13
False Alternatives 错误选项 7
Is-Ought Fallacy 存在即合理 8 18
Wishful Thinking 心想事成 9 3
Misuse of principle 规则没有例外 2 16
Fallacy of the Mean 错误中和 10 12
Faulty Analogy 错误类比 1 14
1. 
		喝咖啡的人和酗酒的人没区别. C
		喝咖啡的人每天早晨工作前要和杯咖啡, 酗酒的人每天早上要喝酒. P
		两个事物在某方面相似,那么其他方面也相似. IP
		Faulty Ananlogy 类比: 这里咖啡和喝酒的重大差异是,咖啡对身体有好处,而酗酒对身体有害.
		 咖啡没有啤酒成瘾大. 类比中没有体现
2. 
		欺骗不是道德错误的. C
		警察开没有标识的车抓超速者是对的. P
		骗朋友给其surprise birthday也没错. P
		规则没有例外. IP
		misuse of principle:
		 这里有道德原则上的冲突,要取更有价值的.
		 P1是驾驶安全>欺骗道德,P2是朋友没有因为欺骗受损.
3. 
	 一定是随机暴力或者认错人了. C
	 没人不喜欢我到足以划我的轮胎. P
		我确认这个. SP
	 我认为没人不喜欢我,所以没人不喜欢我到划轮胎. IP
	 wishful thinking:
	 这里对于推理的判断,基于speaker怎么认为的,没有居于事实和证据.
4. 
		这小说不是荒谬的. C
		这里没有单独的一件不可能发生的事件. P
		每个部分成立,整体也成立. IP
		Fallacy of composition:
		 单独每件可以发生,不代表合成起来不能发生.
5. 
		我们应该宽恕那些杀人. C
		吃肉的人默认宽恕杀动物. P
		我们无法把动物的生命和其他的划清界线. P
			在同一条线上的两个点,无法做区分.SIP
		Fallacy of the continum 连续体谬误:
		人和普通动物是可以很明显的界线的,违背了实际情况.
6. 
		Virginia一定有很好的哲学系. C
		Virginia是全美最好的大学之一. P
		整体是对的,局部也是对的. IP
		Fallacy of Devision:
7. 
		我们要么花大钱搞足球程序使得有竞争力,要么放弃. C
		两个选项中,肯定有一个是正确答案. IP
		False Alternatives:
		 把选项限定成两个 花大钱 和 放弃,且假设一定有正确答案.
		 也有可能不花钱,多花精力投入进去,也能对学校有益.
8. 
		GENE的论证:
		和某人做爱不是什么事情需要做理性决定的. IC
		人们做爱并没有理性决定. P
		现状如此,所以应该是这样的. IP
		Is-Ought:
			因为现状人们做爱随意,所以做爱不需要理性判断.
9. 
		上帝对你来说会是真的. C
		你相信它存在,并且在生活中接受它. P
		你相信它存在,所以它存在. IP
		Wishful thinking:
10. 
		 真相一定在两人的证词当中. C
		 有两个完全相反的证词出自两个重要的证人. P
		 两个极端的中间是好的或对的,因为它是中间的. IP
		 Fallacy of the mean:
11. 
		 Board of Trustees会练出处理机构事务的判断力和技能. C
		 他们每个成员都很擅长处理自己私人和商业事务. P
		 个体牛比,所以整体牛. IP
		 Fallacy of compistion:
12. 
		 宿舍开放12小时是最好的解决方案. C
		 有人说宿舍24小时开放. P
		 有人说宿舍完全封闭. P
		 两个极端的中间是好的或对的,因为它是中间的. IP
		 Fallacy of the mean:
		 这里得根据治安情况,学生的作息来定,而不是根据极端观点的中间来定.
13. 
		 民主党的代表Bouncher支持国家医保. C
		 因为民主党支持国家医保. P
		 全体支持,所以局部支持. IP
		 Fallacy of Division:
14. 
		 政体生命会随着时间越来越不活跃,并且最终会死. C
		 人的生命会随着时间越来越不活跃,并且最终会死. P
		 某个方面相同,其他方面也相同. IP
		 Faulty Anology:
			人的生命是有机体,整体生命不是有机体.不能得出这样的类比.
15. 
		 你可以举起一头牛,如果你每天从牛小举到大. C
		 牛小时候你可以举起,牛每天只张一点,你的肌肉也只张一点,你第二天举没有区别. P
			事物在连续的变化中,一点小变化没有什么影响. SIP
		 Fallacy of continuum:
			牛长的比你肌肉长的快,开始牛长的没有超过你肌肉的承受量没事,一旦超过这个界线,你就举不动了.
16.
		不能带导盲狗来这. C
		不允许带狗. P
		规则没有例外. IP
		Misuse of principle:
17.
		你投票给布什,要么是因为他共和当人,要么因为他支持干细胞研究. C
		只有两选项,必有其一. IP
		False Alternative:
18. 你不该给我贴罚单. C
		人们都停车停这,没有罚单. P
		我停了几个月了. P
		没有罚单标识在巷子里. P
		现状就是乱停车,所以乱停车是对的. IP
		Is-Ought:
C. fallacies in this chapter
Equivocation 含混,偷换概念 9 21
Ambiguity 歧义,词汇和语法歧义 27 25
Misleading Accent 过分强调(口音或者描述多)和断章取义 7? 29
Illicit Contrast 错误相反 16 19
Argument by Innuendo 影射 误导 1  17
Misue of a Vague Expression 模糊表达的误用 3 26
Distinction Without a Difference 换个说法,实际一样 5 23
Fallacy of the continuum 连续体无法叠加和无法分界 13 32
Fallacy of Composition 合成谬误 14 30
Fallacy of Division 分解谬误 10 24
False Alternatives 错误选项 6 20
Is-Ought Fallacy 存在即合理 2 18
Wishful Thinking 心想事成 4 22
Misuse of principle 规则没有例外 8 11
Fallacy of the Mean 错误中和 12 28
Faulty Analogy 错误类比15 31
1. 
		Joel得的A是抄袭的. IC
		Joel得了A. P
		Margaret坐Joel前面也得了A. P
		Argument by Innuendo 影射 误导:
		没有任何证据说Joel是抄袭的,但是在暗示.说他旁边的人得了A.
2. 
		Man被用作代词不应该被改变. C
		Man一直是被用作为代词. P
		现状如此,所以应该如此. IP
		Is-Ought Fallacy:
3. 
		政府除了支持救济金别无选择. C
		我认为如此,所以应该如此. IP
		Wishful thinking:
		并没有给出证据,而是自己的认为.
		--------------------
		政府必须支持救济金. C
		宪法明确规定政府有责任做事优化通常的救济金. P
		Misue of a Vague Expression 模糊表达的误用:
			宪法的优化救济金是模糊的表达,没有说就是支持.
			用模糊的表达去得出结论.
4. 
		Bobbie没有背叛我. C
		她不会不忠诚. P 
			她爱我. SP
		如果她给我戴绿帽,就会催毁美好的感情. P
		她不会这样对我. P
			她是我的全部生命. SP
		因为我相信,所以她是这样的. IP
		wishful Thinking:
		所以的前提都是speaker认为的,并没有实质的证据.
5. 
		我们没有搞审查. C
		我们只是保护学生免于道德有亏的阅读材料. P
		Distinction Without a Difference 换个说法,实际一样:
		不让看有问题的书 就等于 搞审查
6. 
		Dianna 要么在睡觉,要么不在家. C
		电话响个不停. P
		只有两个选项,必有正确答案. IP
		False Alternatives 错误选项:
7. 
		你不值得信任. C
		你是半夜到的,没有按合理时间来. P
		我们相信你,告诉你按恰当时间来. P
		Ambiguity 歧义,词汇和语法歧义:
		这里的恰当时间是有问题的
		--------------------
		misleading accent: 强调reasonable hour
8. 
		45岁的学生也必须留电话给公寓. C
		公司政策是学生必须留父母电话. P
		规则就是规则没有例外. SIP
9. 
	 很高兴民主党人正在清理反对者的坏政策. C
	 有共和党人实施的国会环境费用增长了很多. P
	 共和党人在搞错的,那么共和党人的对手民主党就在搞正确的. IP
	 Illicit Contrast 错误相反: X对Y是错误的, 非X对Y是正确的
	 --------------------含混
	 Worth:
	 民主党人导致了这些变化,应负责. C.
	 在由共和党引导的国会的变化,导致了费用的上升. P
	 Patrick:
	 共和党搞的变化,共和党负责. IC
	 在由共和党引导的国会的变化,导致了费用的上升. P
10. 
		 女方应该拿到孩子的监护权. C
		 因为孩子更需要善于养育的父母. P
		 女人通常比男人更善于养育. P
		 整体是这样,所以局部是这样. IP
		 分解谬误:
11. 
		我没有做错. C
		你给我戴绿帽子. P
		耶稣说:以眼还眼. P
		你搞我,我就搞你,这样就平横了. IP
		Fallacy of the Mean:
		--------------------
		我没有做错. C
		你给我戴绿帽子. P
		耶稣说:以眼还眼. P
		规则没有例外. IP
		Misuse of principle:
12. 
		 关于同性恋进部队,应该睁一只眼闭一只眼. C
		 有人说完全不应该同性恋进军队. P
		 有人说完全不限制同性恋进军队. P
		 两个极端的中间最好,因为是中间. IP
		 Fallacy of the Mean:
13. 
		 30m/h也是安全的. C
		 因为25m/h是安全的. P
		 多加5m/h没有什么影响. P
			 在连续体做一点增加/减少没有影响. SIP
		 Fallacy of the continuum 连续体无法叠加和无法分界
14. 
		 它们的孩子一定很漂亮. C
		 G非常有魅力. P
		 D也非常有魅力. P
		 部分是漂亮的,结合也一定是漂亮的. IP
		 Fallacy of Composition 合成谬误
15. 
		 赌马的人和买股票的人没有区别. C
		 他们都拿钱冒险,赚大利润的机会. P
		 错误类比:
		 赌马和买股票的虽然都有假设的这点相同,但实际两者有重大的差异.一个是投资,一个是相马.
16. 
		 JAMIE,你认为你自己不容易发怒. C
		 JED,你最近很容易发怒. P
		 X做Y,那么非X不做Y. IP
		 ILLICIT CONTRAST:错误相反
		 JED容易发怒, 那么 JAMIE(非JED)不容易发怒.
17. 
		 Benita偷钱了. IC
		 Jeannie说Benita一整天都在shopping. P
		 Debra的钱丢了. P
		 Argument by Innuendo 影射 误导:
		 Jeannie的说法暗示Benita偷钱后shopping
18. 
		 限速应该调高5m/h. C
		 限速是65m/h,大家都跑70m/h. P
		 现状如此,所以是对的. IP
		 Is-Ought Fallacy 存在即合理:
19. 
		 你说美国车不行. C
		 你说日本车行. P
		 你说A行,那么反过来就是说非A不行. IP
		 ILLICIT CONTRAST:错误相反
20. 
		 你要么是民主党,要么是共和党. C
		 选项两个,必有其一. IP
		 False Alternatives 错误选项: 预定假设
21. 
		 裁决会不公正. C
		 裁决会处理学生和管理员的矛盾时,支持了管理员. P
		 两个极端的中间是最好,因为是中间. IP
		 Fallacy of the Mean 错误中和:
		 --------------------
		 裁决会不公正. C
		 一个公正的裁决会在处理争端时是不偏不倚的. P1
		 裁决会处理学生和管理员的矛盾时,不公正. P2
			支持了管理员,停止了学生. SP
		 Equivocation: 公平 和 公正 的区别吧
		 对于公正的意义发生了改变.P1是没有立场,按道理讲话.P2是处理双方,手段一样
22. 
		 我父亲会从癌症中康复. C
		 因为他像钉子一样坚强. P
			 因为我想,所以他行. SIP
		 Wishful Thinking 心想事成:
		 没有拿证据,医生的诊断说事,而是按自己的意愿说话.
23. 
		 我没有和Angie昨晚约会. C
		 我仅仅只是带她吃晚饭,看电影. P
		 Distinction Without a Difference 换个说法,实际一样:
24. 
		 我们应该雇佣从Virginia University的生物系出来的毕业生. C
		 Virginia University的生物系很牛. P
		 整体牛,所以局部牛. IP
		 Fallacy of Division 分解谬误:
25. 
		 Naomi,你是信神的. C
		 Naomi你不是无神论者. P
		 两个选项,必有其一. IP
		 False Alternatives 错误选项:
		 --------------------
		 Naomi是无神论者. C
		 Naomi说:我不是非常信宗教. P
		 --------------------
		 Ambiguity:
		 不是非常信宗教歧义:可以有多个含义,不可知论,无神论,神权不干涉世俗.
26. 
		 有护照也不能点酒. C
		 我们没有看到你驾驶证. P
		 没有驾驶证不能点酒. P
		 规则没有例外. IP
		 Misuse of principle 规则没有例外:
		 --------------------
		 所以不能给酒. C
		 虽然有护照,但是没有驾驶证. P
		 不见驾驶证不给酒. P
		 Misue of a Vague Expression 模糊表达的误用:
			不见驾驶证不给酒: 指的是开车的情况下,没给驾驶证
27. 
		 Your wife have left her sister in the car. C
		 she(这里不知道是妻子,还是妻子的姐妹) hasn’t washed her hair for more than a week. P
		 Ambiguity 歧义,词汇和语法歧义:
			 语法歧义,不明确的代词
		--------------------
		 BARRY: My wife wouldn’t go into the grocery store with her sister because she hasn’t
			washed her hair for more than a week.
		 DENISE: Your wife could have left her sister in the car, couldn’t she?
28. 
		 最好的解决方法就是P和M在宗教观点各让一步. C
		 因为那边都不会有全部的事实. P
		 极端的中间是最好的,因为中间是中间. IP
		 Fallacy of the Mean 错误中和:
29. 
		 Tim's的非长女没有长女聪明. C
		 Tim's的长女非常聪明. P
		 Misleading Accent 过分强调(口音或者描述多)和断章取义:
		 错误强调长女聪明,导致得出结论其他没那么聪明
30. 
		 Teresa和Mark不会有开心的婚姻. C
		 T不开心. P
		 Mark也不开心. P
		 局部不行,所以整体也不行. IP
		 Fallacy of Composition 合成谬误:
31. 
		 谁选总统无所谓. C
		 国家像机器,无论谁掌控它,都会表现相同. P
		 错误类比:
			 国家很复杂,机器很简单.
32. 保安应该让21岁差2周的我进去. C
		差2周没啥影响. P
			连续体的小改变没有大影响. SIP
		Fallacy of the continuum 连续体无法叠加和无法分界:

* Chatper 8 Fallacies That Violate The Sufficiency Criterion
本章:
	- 用你自己的话描述不充分谬误的基本特性
	- 辨别,指认,解释在日常对话或辩论中犯的不充分fallicies
	- 利用有效策略去attack 不充分fallacies
		
提出的论证要提供相关~可接受,并且在质和量方面要充足的证据.

证据不充分导致论证出错,
	- 有些证据太少或压根没证据
	- 有些有偏见的证据或证据只出现
	- 有些忽略了关键其中的证据
有因果论证得到的结论关于因果关系并没有被适当的证据所支持.

每一种都是犯不充分谬误的方式, 数量, 种类, 分量.

两种: 1. 证据缺失 2. 因果谬误

** Fallacies of Missing Evidence
真实论证的研究结露许多论证证据很少或没证据.
犯的最多的不是我们的60个谬误,而是从名字和描述推论(忘文生义).
eg. 产品叫economy size, 所以他是economy size.
		某大学最牛比,因为一本书里说他最牛比.

insufficient sample: 从过少的样本推出结论
unrepresentative data: 从不具代表性的样本推出结论(幸存者偏差)
arguing from ignorance: 最有趣也最彻底没证据
contrary-to-fact by pothesis: what might have been or what might be
fallacy of popular wisdom: 用格言或老话,而不是证据
speical pleading: 把某人当作规则的例外,却没有给理由说为什么
omission of key evidence: 缺乏关键证据

*** Insuffcient Sample
定义: 从过少的样本推出结论或者泛化
wusd: 个人经历和个人的感觉,得到某一个事情的结论.
	比如小红书流行的听写学习英语效率高
	比如我们遇到某个地方的人不文明,进而得出结论这个地方的人都不文明
	我领导招聘招了个河南人,然后河南人没来,然后他就得出结论 河南人不讲诚信

不充足样本中,通常证据是相关且可接受的,但是不够,又叫做草率泛化.
人们通过根据一个独立的证据或个人经历来得出结论,这个叫孤立事实.

怎么样算充分得根据具体的上下文去决定.
但是不是说证据数量增加就一定能充分,因为增加的证据可能是无关紧要的.

在有些咨询的领域有熟练的指导原则来判断样本的充分性,比如投票和电视投票,但是大部分咩有.

EXAMPLE:
每天1gVC能预防感冒. C
我们家每天1gVC9个月了. P
我们没感冒. P
以前我们都感冒. P
我们家的例子是充足的样本对于所有人. IP

这个VC疗法看起来挺鼓动人的,但实际上论证并没有证明VC的有效性.
隐藏的假设,首先就是家庭都是一类人,而整体有很多类人.并且还可能有很多其他因素可能导致9个月没感冒.

EXAMPLE:
我应该/不应该换这家新店买东西. C
这家新店的一些产品比老店便宜/贵. P
新店的一些产品便宜/贵的例子是整体新店更便宜/贵的充分例子. IP

应该是根据每月最常买什么,然后再对比最常买的价格进行对比.

EXAMPLE:
我不会再结婚,也不会介绍别人结婚. C
我和前妻的经历非常糟糕. P
我的例子适用于所有人,所有婚姻. IP

他的失败婚姻仅仅是对他和他前妻,而不能是所有婚姻.例子太少了.

**** ATTACKING THE FALLACY
通常给你这种小样本论证的人非常确信,因为这个可能对他印象很深刻,尤其来自于个人经历的.
你应该给他澄清,个人内部视角离好论证差得远.

有可能人只是表达观点,并没是说论证.你可以问他:"你是在表达观点,还是在提供论证?"

如果他否认只是表达观点.把他的论证提取出来,把隐藏的假设搞出来,通常就能发现错误了.
也可以举反例: "学院的孩子都是顽劣儿童,因为我最近babysit的是顽劣儿童"

一旦用这个反例,他就知道问题在哪了.

wusd:
过节高铁票很好买,因为我买到票了.
中国人都英语很好,因为我英语很好

*** Unrepresentative Data
定义: 从不具代表性或偏见的样本推出结论
wusd: 央视采访过年是否大家买到了火车票,采访了很多人,都买到了,得出结论大家都买到了火车票.
	结果他是在火车上采访的.

什么叫代表性?数据要涉及到所有相关的子集.
比如:美国人对于某议题的态度,数据就得跨种族~年纪~教育背景~性别~地区,甚至是宗教信仰.
那头发和体重就没关系了.

偏见:
	1. 数据可能被收集者的偏见玷污.比如政党或团体收集的看法数据应该被质疑.
	2. 数据收集来自于小子集,并且这个子集有很强消极或积极的观念.
		 eg:校园运动的看法不能只采访运动协会的.
				看影评不能只看一个杂志,这个杂志可能是符合一小群人的兴趣和口味.
	3. 不要太信任网络~报纸和杂志电话或邮件投票,要选择那种声望好的投票建立在有代表性的群体.
		 
还有一种不具代表性的数据是不同质量的数据,用不同的方法.
比如: 2007美国的暴力犯罪和1947年美国的,这两者数据的比较,因为手段的不同非常值得质疑.

wusd: 人们普遍认为现在的食品安全事故比以前多,用的是食品安全事故过去统计和现在统计的数据,
两份比较的数据不具代表性.过去和现在的统计手段不同,认定方式也不同,质量不同.

EXAMPLE:
43%的美国人每天至少两小时娱乐. C
因为43%的Florida居民每天花两小时娱乐. P
Florida的居民代表全美国. IP

Florida很多退休人员,所以数据不具有代表性.

EXAMPLE:
她会赢11月的选举. C
超过两千学生投票她赢了. P
两千学生代表了投票人. IP

大学生很少视为有代表性的样本,尽管人数要多于专业的投票组织,与数量无关.

EXAMPLE:
52%的人每年在沙滩旁边待个5天. C
因为50,000个维京人,从不同小团队这么做. P
50,000个维京人代表全美. IP

代表不了全美,因为维京靠近海洋,数据不具代表性.

**** Attacking The Fallacy
和对付用太少的样本相似.
如果你发现有人用可疑的数据,你可以也用可疑的数据用相似的论证得到不同的结论.

比如:
大部分有狗. C
因为参与县城狗秀的一千个人当中,大部分有狗. P
狗秀中的人代表了全美. IP

如果他认为没毛病,那你就再说当地的护士家庭没有狗,又证明了大部分没狗.
两者矛盾,则必然有个有问题的.

wusd: 如果相同大小的样本可支持两个相互矛盾的结论，那么数据代表性有问题

*** Arguing From Ignorance 诉诸缺失
定义: 证明断言的正确或错误,因为没人证明其错误,或者对手无法或拒绝给出其反面的可信的证据.

诉诸缺失是人们经常用来证明自己信念的方法.
证明断言正确,只是靠没有被反证.同样地,证明断言错误,仅仅靠没有被证实.
这里就没有用证据,而是用了反面证据的缺失.

wusd: 你证明不了我偷吃了榴莲,所以我没有偷吃.

诉诸缺失也违反了举证责任,谁要证明某事谁就举证,而不是把责任推给对方,让对方去证反.
eg. 鬼存在,除非你能证明它们不存在.
如果对方不接受这个责任,它们就假设就不需要举证了,实际还是需要的,不然就违反了充分原则.

也有这种用这种情况的,
比如司法的清白直到被证明有罪.
这里的清白不是说真的就清白,而是说没有被视为有罪.

wusd: 王天一被举报软件作弊,然后举报的大师说看其能不能自证清白.
王天一直播的回答,人不可能自证清白.举个例子,你无法证明自己没有杀人.

诉诸缺失谬误迷惑性在于它和好的论证很相似.
eg. 我说我的房子有白蚁. 专家揭露说没有证据支持有白蚁. 我就该接受没有白蚁.
这里的推理不是,因为没有白蚁的证据,所以没有白蚁.而是专家经过了各种正面和反面的证据去判断是否有白蚁.

EXAMPLE:
我办公室每个女性都对工资少于男性满意. C
因为没有女性提出不满 P
如果没有提出不满,那么就没有不满. IP
没有不满的证据,那么就是满意 IP

这里的问题就是没有不满的表达当作满意的证据,这种谬误有个别名 沉默就是满意.
为什么没有不满的表达,可能确实有原因.

wusd: 
公司最近出了考勤制度,办公室主任开会说,没有提意见反对,说明大家都满意这个方案.

EXAMPLE:
我对手同意联邦控枪费用. C
因为他没有发表看法. P
没有同意的对立证据,那么就是同意. IP

非常有趣,这个论证也可以变成.
我对手反对联邦控枪费用. C
因为他没有发表看法. P
没有反对的相反证据,那么就是反对了. IP

EXAMPLE:
这块场地可以进出. C
因为没看到不允许进入的标识. P
没有进出的相反证据,那么就是允许进出. IP

没说不允许进入,并没有证明允许进入.

EXAMPLE:
我没有被录用. C
因为我没有受到回应在申请两个月后. P
没有 被录用 的证据,所以没有被录用.

也可以变成,因为没有被拒绝的证据, 所以被录用了.
wusd:
	小红答应做我女朋友了.因为上周前我发求爱信给她,她没有拒绝.

**** ATTACKING THE FALLACY
如果说没有被证反,就算被证明.那么很多荒谬的结论都会被证实.eg. 鬼存在,除非你证明鬼不存在.
而且,如果断言太蠢的话提都不会提,对方就会自然赢.

如果你的对手给你可疑的断言用诉诸缺失的方法证明,你可以用这种方式去证明他的反面.
eg. 鬼存在,没有证据鬼不存在.
你: 鬼不存在,因为没有证据鬼存在.

*** Contrary-To-Fact Hypothesis 事实相反假说
定义: 把假说当作事实的断言,通过做断言,
	这个断言是 如果过去怎么样,那么过去会发生什么, 或者如果未来怎么样,未来会发生什么?
wusd: 要不是我那几天没休息好,我肯定拿第一名.
	经常是过去虚拟语气,而且还有未来的可能情况.

对于断言的经验证据是不存在,明显也是不可用的,所以这些证据都要被认为是构想.
尽管不知道过去可能,未来可能发生什么,但是还是能提出这种假说构想.
这种构想对于理解过去和未来的事情是有益的,但是它仅仅是构想--可能的故事.

这个谬误经常用于过去事件,也被叫做马后炮.
足球粉丝经常说某个选手在上周的比赛,如果怎么样,就会怎么怎么样.
我们没法知道过去会发生什么,未来会发生什么,这些断言都是和过去相反的.
所以这些断言都没有充足证据,得到结论同样如此.

EXAMPLE:
与事实相反假说,过去虚拟语气.

即便是有理由去接受这些断言,我们也很少被给证据.即便给了,它们是不是证据也值得怀疑.

如果我(过去)练了反手击球,我(过去)赢了锦标赛. C
因为我没赢锦标赛 P
我没有充分练反手击球 P
练习反手击球对赢或输有很大不同. P

没办法知道如果练了反手击球会结果会怎么样.第三个前提没有证据.
练不练反手击球,只会减少miss,但是对于复杂的比赛的影响有多少,还很难说.

wusd: 如果不是那波一级团打亏了,我线上不会这么劣势.肯定能赢比赛.
	线上劣势,有很多因素.可能是英雄克制问题,可能是选手对线能力问题.可能是打野配合问题.不足以说明全部的问题

EXAMPLE:
我应该住校外. C
如果我住校外,我学习成绩去提升. P
	如果我住校外,我会学得更多. P
	如果我住校外,我会睡得更好. P

这些证据都是些猜想.

EXAMPLE:
如果希特勒没有侵略俄罗斯和开辟第二战争,他已经赢了二战.
如果1860的选举民主当赢了,联邦间的战争就不会爆发.
这些可疑的断言难以想象有那些充分的证据.

**** ATTACKING THE FALLACY
因为想象性的构想计划对于计划未来和从过去学习是非常重要的一步,所以不建议你去攻击这个.
但是如果你面临论证的时候,就要attack了.
并且这种attack能够引导其对于反对断言的开放,更加认真对待支持断言.

你可能是对的,但是我没有办法去判断他,我也想象不到你可能找到证据去支持断言.
这可能激发arguer去找证据,这样才可能有一场好的论证.

*** Fallacy of Popular Wisdom
定义: 用这些玩意,而不是相关证据.aphorisms: 格言, cliches: 老话, folk wisdom: 民间智慧, comman sense: 常识

用格言,老话啊这些当作论证的前提并且没有展示出这些的前提,而不是用相关的证据.
因为老话都是启发性的,不能当作论证;但是如果解释了为什么这些老话是河虎道理的,那这些老话对论证也没啥用,仅仅是表达的很好.

事实老话和格言之间经常互相矛盾提供附加的证据: 格言只提供了不充分的支持.
1. 两个脑袋好过一个. 太多厨师毁掉一锅粥
2. 哪里有烟哪里有火. 评价书不能靠封皮.
3. 犹豫就会败北. 傻瓜在天使不敢犯险的地方冲动.
4. 安全好过抱歉. 不冒险就没有收获.
5. 新拖把扫地干净.	旧小提琴拉出好音符.
6. 哪里有意愿,哪里就有路.	如果愿望是马,乞丐就会骑着.
7. 鸟兽成群结对. 异性相吸.
wusd: 中壬石材火眼高. 三个合适没水喝.
	经济基础决定上层建筑. 上梁不正下梁歪.

第二种还有种谬误就是文化中代代相传的民间智慧.
感冒吃,发热饿. 一天一个苹果赶跑医生.
即便持有观点的人多,但是没有证据支持.

第三种就是常识.
常识的观点通常没有定义或者缺乏证据.
arguer有时候可以提供证据也不提供,因为觉得是常识.
这种会营造一种感觉好像常识是足够的理由使得人们接受断言,比如:"运动对你高血压有害就是一个常识".

EXAMPLE
你必须切断一份关系. IC
因为你和两名男性有关系. P
你不能又持有蛋糕,又吃它. P

这里明显的问题是格言是否可以用在这个特殊的例子中.
又保存蛋糕又吃蛋糕,确实是前后矛盾的.
但是同时和两名异性有关系并没有这个逻辑矛盾,这个格言不能用在这里.
辅导员要告诉为什么这个关系是矛盾的,格言做不到.

EXAMPLE
如果你现在不懂,那么你就永远不懂.

就目前这个考试表现来说,一个努力的学生在考前几个小时能学到非常多的知识.

EXAMPLE 
common sense: 如果有钱就把贷款还清.

Jackie: 我们现在把房贷还清.
Tim: 别. 我觉得最好用来投资一些利率比房贷利率高的.这样我们能取得优势.
Jackie: 你疯了.如果有钱就把贷款还清.这是常识.

什么是常识?Tim的说法看起来有财政意义.
可以有财政意义但是没有常识意义马?
如果这样,常识值得是什么?
说一个事情有常识意义,并代表说的通.如果证据,通常是空话.

**** Attacking The Fallacy
你不应该为可疑的流行老话的智慧而担忧.
这些老话都需要证据支持其价值.
如果arguer用老话而不是证据支持断言,干它;或者直接用反的老话对抗.
	arguer必须告诉你为什么他的比你的好,那他必须使用证据了.

对于folk wisdom, "什么证据让你相信这个可以的民间智慧是真的"
对于common sense, "它是怎么成为常识的."
	一半来说如果真是常识,你们就不会讨论它了.

*** Special Pleading 特殊关照
定义: 把规则~原则标准用到别人身上,但是对于自己利益相关却不用,而且没有给出证据去支持这种异常的情况.

特殊关照者通常接受一个通用原则,但是却希望自己是例外.
特殊关照之所以是fallacy,因为没有证据去证明这个例外.
当特殊关照出现时,总是区别对待相似的事情.

EXAMPLE
你应该做所有家务. C
因为我工作一天很累. P
你工作一天也很累. P
指导原则是这个情况下每个伴侣都要做家务. IP
这个原则对你而不对我. IP

他把这个原则用到老婆身上,没有用到自己身上.又没有说任何理由.

wusd: 虽然你上学了一天很累. 但是妈妈工作了一天,这么累了.今天由你来洗碗.

EXAMPLE
我自信,你骄傲;
我有进取心,你冷酷;
我节约,你小气;
我坦率,你鲁莽;
我灵活,你前后不一;
我聪明,你串通;
我仔细,你挑剔;
我好奇,你好管闲事;
我激情,你歇斯底里;
我坚强,你顽固;
我友好,你轻挑;
我自由精灵,你考驾照去吧.

如果这些行为是一样的,我们如何能评价自己积极,评价别人消极.
当别人问时:那不一样.
如果不能令人信服地说出不一样,他们就犯了特殊关照了.

EXAMPLE
J: 关掉音乐吧, 我想打个顿.
K: 这也是我的房间, 我想听刚从油箱拿到的CD
J: 其他时间听吧, 我想打个顿

这里的原则是室友间的利益没有谁比谁高.但是J暗示他的利益高于K的.
大多数会认为J用了Special Pleading,因为他没有给令人信服的理由,他为什么有更高优先级.

wusd:
小红和小蓝约会.小红认为自己是女生迟到无所谓,但是小蓝迟到她就大发雷霆.

**** Attacking The Fallacy
对于这种最好的办法就是指控special-pleading双标或者前后不一致.
通常这种指控是无法用逻辑去理解,并且有很强的消极意义你的对手不愿意沾上的.
但是要非常注意小心解释为什么你认为他用了双重标准,仔细审查你的对手可以对于指控的反击.

有些情况确实使得他本人特例,但是很少,所以应该总是怀疑这种偏向对待.
问arguer为什么其值得区别对待,为什么不应该把规则用到他身上.
arguer通常有各种理由,问题是这些理由是否充分支持这种特殊对待.

反例来了:
纳税相关法律所有情况都适用. P
我是个例外,因为我需要钱干别的事. P
因此,纳税法律不应该用到我身上. C

*** Omission of Key Evidence
定义: 构造一个没有包含关键证据支持结论的论证.
wusd:
	我女朋友想买柯基.理由是很可爱,也不贵,狗粮也不贵,说了很多理由.
	实际缺乏了关键理由: 有没有精力遛狗,家里的隔音效果好不好-邻里矛盾,还有狗随地拉屎拉尿的处理.

好的论证的充分原则最多被违背,当对于支持结论关键性的证据缺席在论证中.
不像是混牛奶少了酒精,像披萨少了一块然后论证不完整了.

通常犯这个谬误也犯了Is-Ought的谬误.
好的论证要去支持道德判断,没有关键部分--道德前提是不可能的.

跟朋友前男友约会是不道德的. C
因为跟朋友前男友约会可能使她沮丧. P
我不想沮丧朋友. P

这里可以得出的结论是不想和她前男友约会,但是得不到这种行为是不道德的,因为没有道德前提.

EXAMPLE:
我们应该结婚. C
因为我们喜欢相同事物. P
我们喜欢你的狗. P
我们去同一个教堂. P
我们食物和电影口味相同. P
我们可以省生活费. P

这个论证的理由可能支持你去结婚你的妻子和最好的朋友.
但是缺少结论的关键证据: 是否爱彼此以及是否想共度余生.

EXAMPLE:
投票教授年度教师

非关键理由:
	她聪明;她被广泛报道;她献身于工作;她愿意和学生沟通;她总是对学生和蔼和照顾;她对于其专业富有热情.
缺少关键理由: 她教的怎么样?

EXAMPLE:
我可能会买邻居正在卖的车. C
车只买了两年,运行良好. P
我喜欢车的颜色和款式. P
车子的油耗也很好. P

缺乏关键理由: 车子的价格是否在合理范围之内.

**** Attacking the Faulty
attack的方式就是指出这个fallacy,指出你必须有的证据才有可能接受这个结论,尤其是那些声称对的美和道德前提缺少的情况.
相当有可能只是由于不小心产生的论证,这种情况,补一下就成了成功的一个了.

通常由于一些原因关键性前提被遗漏了.这种情况下指出这种缺失,只要眼不瞎都明白.
但是无论为什么确实关键证据,只要缺失了一定不是好的论证.

** Causal Fallacies

*** Confusion of A Necessary with A Sucient Condition
定义: 把事件的必要条件当成充分条件.
wusd: 谁过年不吃会饺子,谁长大成人不娶回媳妇.

必要条件是一个或多个,如果不存在事件就不出现.
充分条件是一个或多个,如果存在事件就一定存在.
但是必要条件存在,不代表事件一定出现,通常是多个必要条件组成充分条件导致事件存在.
wusd: 必要不在,事件一定不在;充分在,事件一定在.
			必要在,事件不一定在; 一般多个必要组合成充分条件.

比如: 毛毯被电子吸尘器清理的充分条件,
不单单包括几个必要条件: 电源,电子吸尘器,连接器
还有几个条件: 操作吸尘器的,比如机器人...
没有一个使必要的,但是他们组合起来,就是充分的.

很常见一些arguers出现这种错误,当必要条件在的时候,把必要搞错成充分的.
必要条件确实必须存在,但对于事件的发生不够充分.
仅仅根据必要条件推导事件成立,通常是因果分析错误,因此没有提供充足的证据,违反了好论证的充分原则.

EXAMPLE:
电池出毛病了. C
我放新电池到手电筒里. P
手电筒不亮. P
有好电池是手电筒亮的充分条件. IP

电池确实可能出问题了,但是更可能其他的因素导致手电不亮.
尽管好电池是手电筒亮的必要条件,却不是充分条件.arguer隐藏的假设,它是.

EXAMPLE:
我不应该被田进队裁掉. C
我必须1公里少于6分钟才能进入田进队. P
1公里少于6分钟是进入田进队的充分条件. IP

实际1公里6分钟只是必要条件,还有很多其他的要求.

EXAMPLE:
教授说.要想通过考试,必须经常上课,读每天的作业,参与课堂讨论,参加所有考试,交研究paper.
有些学生老实做了,但是仍然考试失败了.

这些都是必要的条件,是教授根据往年通过考试的学生的经验.
wusd:要想成绩好,往往必须要完成老师布置的作业.但是仅仅是完成老师的布置的作业是远远不够的.

**** Attacking The Fallacy
很多人搞错必要为充分因为他们不懂两者的区别.
澄清两者的区别就很可能有帮助了.比如取反例:
	一个女人说自己每天两小时练钢琴15年,因此一定是一个演唱会钢琴家.
	实际大量练习仅仅是必要条件,很可能需要天赋和良好的管理能力.
当这个例子一举,犯这个错误的人就知道自己犯相同错误了.

*** Causal Oversimplification 因果过度简化
定义: 过度简化事件的起因, 通过明确原因因素(这个因素不充分解释事件) 或者 过分强调其中的一个因素.

在因果解释中,经常把很明显的先行事件当作是事件的起因.
然后,事件往往是大量的因素共同作用产生的结果.仅仅是把其中的一个因素通常是过度简化因果的情况.
wusd:
	我开始对自己的听力不好,简单归结于自己的语音不好,不懂那些连读缩读等等,进而花大量时间去学那些发音规则.
	实际上,听力包括,拼写+语音+单词+习惯用法+语法+结构+内容,多方面的因素.
	推广一下很多事情.如果想要达到自己的目的,这样简单的归因,只是在某方面用功,往往会达不到自己的目的.

因为事件的因素总是非常多的,总是可以质疑一个因果解释.
但是不用过度追求每一个因素,因为这样浪费时间和精力.
wusd:
	比如做事要有行动意识.不要试图没开始就计划"完美",快行动.
	有个general idea后,就可以行动起来.做事的过程中更多是动态决策的过程.不可能有完美的计划,新情况会一直出现.先完成再完美.

EXAMPLE:
体罚学生应该被带回到公立学校里. IC
因为体罚在公立学校不再被运行. P
学生现在低自律和不尊重权威比以前. P
没有体罚学生充分解释学生今天的行为. IP

低自律和不尊重权威不是新问题,即便是新问题,也不能直接归因到取消体罚上.
因为这个问题是多方面的,这里隐藏的假设不够充分,不应该被接受.

EXAMPLE:
现在年轻人很胖和蠢的原因是 过去花5小时煅炼和阅读,现在看电视了.
年轻人更胖更蠢是一个复杂的现象,简单归因给看电视是不对的.

wusd:
	很多家长把孩子成绩不好,归根于电子游戏和手机的出现.
	实际上成绩不好是多方面的因素,即便没有手机,也会有其他的干扰因素,像以前小混混非常流行,不玩手机玩刀了.

EXAMPLE:
如果夫妻一起读圣经和每天祷告,对婚姻很有帮助. C
现在离婚好多. P
离婚的原因是没有做家庭祷告. P

即便两者都是事实,但是离婚也是多方面的原因,祷告并没有充分地作为归因.

**** Attacking The Fallacy
提醒犯这个谬误arguer,事件总是多个起因的,总是不错的.
很少有arguer会不同意这个说话.这样他接受其他因素的大门就打开了,甚至重新考虑自己的结论.

如果你怀疑因果是过度简化了,因为因素不足以接受事件或过去强调某个因素的作用.
可以提出你觉得增加的因素,确保arguer思考下你说的因素,然后他们会重新考虑自己归因的合理性.

wusd:
	1. 提醒下arguer事件有很多因素造成的,简化归因容易不充分
	2. 怀疑过度简化时,提出你觉得的其他原因,和arguer一起讨论下.

*** Post Hoc Fallacy 事后谬误
定义: 假设特殊事件B由其他事件A造成的,仅仅因为B发生在A后面(时间).

一个事件先于另一个事件发生,不足以说明是因果关系,仅仅是一种指示.
这种指示,还有空间的和规律的历史.
这种事后谬误也常见于迷信,比如坏运气,就是做某个事情后,会发生坏事.
这种思想错误的把巧合当作因果.
wusd: 左眼跳财,右眼跳灾.

经常容易把Post Hoc和Oversimplification搞错了.
Oversimplification是本身是事件的原因,但是并不充分.
Post Hoc仅仅是时间先后发生,一点因果关系都没有.

犯Post Hoc的人没有遵守充分原则.
声称这个因果论证,但是前提并没有明显的因果关系--仅仅是时间先后,这完全没有因果关系.

EXAMPLE:
我前夫一定说我坏话导致老板辞退我. IC
因果我前夫和我老板一起打在高夫赛上, P
在高夫赛后我主管辞退我. P
事件A先于事件B发生,事件A一定是事件B的起因. IP

为了这个女人知道她故事的那边,她必须做更好的工作去证明高夫赛和她被辞退的因果关系.
如果仅仅是先后的话,很能说明事情.
wusd: 有时候很难避免别人产生这种谬误,比如说,你被主管叫去聊天.然后你的同事被开除了.
	你同事怀恨在心,认为是因为你说了什么坏话导致他被开除.
wusd:
	说话有时候不小心得罪了同事,然后意识到这个问题,跟同事道歉.
	同事也说没问题,但是事后某些事情上不配和你.
	这时候就陷入了这种怀疑当中,又没办法去确认.

EXAMPLE:
你搬来导致锅炉坏了. C
我们之前锅炉没出过问题,你来了就出. P
事件A先于事件B发生,事件A一定是事件B的起因. IP

wusd:
有时候人搞不清楚情况,在情绪激动的时候,很容易做这种误判,迁怒于人.
比如有些家长: 下午我看你摸了我的模型的,晚上它就坏了,肯定是你弄坏的.

EXAMPLE:
不去教堂是生意不好的原因. C
自从不去教堂后,生意就不好. P
事件A先于事件B发生,事件A一定是事件B的起因. IP

**** Attacking The Fallacy
任何人都很难仅仅因为时间先后就直接把A当作B的原因,其实是因为背后有原因.
比如说:公寓的管理有理由认为租客胡乱摆弄锅炉.
	生意人非常相信神罚.
没有任何其他因素和设想的时候,仅仅只有时间先后时,需要更多信服的证据.

找反例很简单:
比如: 卡车来了后,电话响了.所以卡车响了是电话响来的原因.

wusd: 公鸡一叫,天就亮了.小男孩把公鸡叫当作是天亮的原因.

*** Confusion of Cause and Effect 因果倒置?
定义: 搞混了事件的原因和影响.
wusd: 因果倒置

现实世界中,解决这种因果倒置非常重要;可以协助我们理解经历和预测未来.
因果倒置的论证建立在错误的因果分析,因此也没有提供充分的立场,更谈不上对真实世界的理解.

EXAMPLE:
州长Kaine有直觉知道哪天有牛排. C
因为K总是在我们吃牛排那天来探视监狱. P
要么K有直觉或监狱官员被提前告之. IP
监狱官员不会被提前告之. IP

这里就是囚犯搞错了因果,不是因为州长知道有牛排所以来探监,而是因为州长来所以有牛排吃.
第三假设,搞错了事实.监狱官员一般会被提前告之.

wusd:
	有钱人之所以有钱,是因为他消费爱马仕,香奈儿等等奢侈品.
	其实搞反了,因为他有钱,所以才消费奢侈品.

EXAMPLE:
	N之所以考高分,因为她是老师的宠儿.
	搞反了,N是宠儿,是因为她考高分.

wusd:
	但是这里的话,又有点互相成就的感觉.
	因为她搞高分,所以老师喜欢她,给了她一些优待.
	因为给了她优待,所以她又考更高的分数,最后老师又更喜欢他....

EXAMPLE:
	上帝同意他,因为是道德上对的. Socrates的意见
	道德上对的,因为上帝同意他.

**** Attacking The Fallacy
任何因果倒置导致事实混乱的都应该被纠正.
比如: 孩子说,爸爸,树动了导致风吹了.
这就是个很好的机会,让孩子更好的了解风的属性.

但如果是成年人搞错了因果,比较危险因为成年人会影响其他人.
所以,这种因果倒置的纠正有助于排除困惑.

举反例: 这些人得不到工作,因为他们会焦躁易怒.
如果他意识到反例: 他们会焦躁易怒,是因为得不到工作,就会同样对待自己的论证.

因果倒置并不容易被觉察,反例好举,但是对于论证本身需要足够的知识量去辨别这种错误.
arguer可能知道这种问题但是仍然坚持,这时候有必要跟其说明纠正的意义.

*** Neglect of a Common Cause
定义: 没有意识到两个似乎有关系的事件实际没有因果关联,而是某个共同因素的作用.

当两个事件一起出现,我们会倾向一个是因一个是果,这样会忽视其他关系.
我们要开放有这种可能两个事件都是某个事件的果.
要察觉这种共同原因,对你对于因果关系的理解有很高的要求.

看到两个明显的事件,看不到不明显的事件实际上前两个的共同原因.
这种情况下,因果关系是不充分的.

EXAMPLE:
要么是教书激发成为家长的兴趣,要么是成为家长激发教书的兴趣. C
因为大多数小学老师有自己的孩子. P

很有可能是第三种原因出于对于孩子的爱,成为家长和小学老师.
wusd:
	比如我们说某个人,学习成绩好,游戏玩得好.
	所以是他游戏玩得好,导致他学习成绩好.或者学习成绩好导致游戏玩的好.
	其实还有第三种原因,他做事很专注,导致他游戏玩得好,学习成绩又好.

EXAMPLE:
要么是他胖导致压抑,要么是压抑导致他胖. C
这个大学生又胖,又压抑. P

还有种可能: 这个大学生有生理上的问题,导致其又胖又压抑.

EXAMPLE:
电影和电视节目导致道德退化. C
电影和电视节目和道德退化同时存在. P

可能: 多种因素导致这两种情况,不能简单怪电影制片人和电视节目者.

**** Attacking The Fallacy
要非常注意不要错误指控别人犯了neglect of a common use.
大多数因果关系中有那种次要的共同因素,忽略这个不算是犯fallacy.
	比如: 成为家长和小学老师之间的共同因素,成为成人.
但是当只提两件事有因果关系,又有第三件更充分的事情对两者共同有作用,这时确实犯fallacy了.

当你坚信这个解释是neglect of a common use,你应该解释共同的原因为什么更充分.
你这么一解释,arguer就要小心检查你的提案,然后努力去决定哪种解释更充分.

wusd:
	这里感觉更多依赖人生的经验和对于事物因果关系的认识.
	知道有这个谬误仅仅只是有这个意识.
	当真的看到有第三个共同原因时,先小心检查是否重要,比如:家长和小学老师的共同因素,成人.
	然后给别人提出后,要解释为什么是C同时是A和B的原因.
	给别人充足的时间去判断,当别人反驳时,要开放自己的思想,判断谁对谁错.

**** Domino Fallacy
定义: 没明显的证据,假设特殊的行为或事件是一些步骤导致一个不想要的后的第一步.

这个得名于孩子玩得多米诺牌.这种连锁反应在游戏中生效,但是不是所有的事件都是这样的.
任何情况下不能假设一个事件导致另一个事件,却没有因果因素在里面.

滑坡,在坡上的一端时,没办法挖住一个地方然后停止滑动.
像多米诺可以帮助描述这种fallacy thinking,代表对于因果关系的错误理解.
谁认为是这样的,得出没道理的结论,单一的事件可以当作一系列复杂因果事件的充分的解释.
wusd:
纣做象牙筷子让箕子感到恐惧。（他）认为：“象牙筷子肯定不会放在鉶（这样的土制的器皿）上，必然
要用犀牛角和玉做的杯子。用象牙筷子玉杯子不可能会以豆子豆叶（这样的普通蔬菜）作为食物，那么（食物）必然是
牦牛、大象、豹子幼崽（这样的珍馐佳肴）。（吃）牦牛、大象、豹子幼崽肯定不会穿粗布短衣在茅屋下用餐，肯定是
绫罗绸缎的衣服无数，房子做得很大台筑得很高。我担心他的结局，所以害怕他的开始。”

EXAMPLE:
我们不应该允许Gay和Lesbian婚姻. C
因为允许Gay和Lesbian结婚会导致群婚. P
	因为这两件事情有因果关系. ISP
群婚会到无婚. P
	因为群婚和无婚有因果关系. ISP
无婚可不好. IP(moral)

arguer并没有说明白因果关系,像Implicit subpremise提到的因果关系.
没有提供充足的证据去支持断言,所以没有达到好论证的充分条件,也得不出结论.
wusd: 这里关键是为什么会导致下一步,要有合适的证据.否则就不充分.

EXAMPLE:
如果我们允许政府限制每月买枪数,那么它们会限制酒~食物或汽车.
他们告诉我们能射杀多少鹿,下一步就是生多少孩子.
它们会持续到完全控制我们.

这些事件没有因果关系,可能确实有必要限制提到的这些事情.
但是是其他原因,而不是它们之间的因果关系.

EXAMPLE:
如果你让学生去教员委员会,下一步它们就会想成为部成员,再一步董事会.
最后,它们将会雇佣和辞退教员.

让学生去教员位会员有很多好的理由.
是否明智选学生去部成员或董事会需要分开的论证,因为这涉及了不同的问题.
这些问题需要不同的要求,然后根本没有逻辑或因果关系.

**** Attacking The Fallacy
如果你怀疑有点多米诺想法了,坚持要求arguer给每个独立事件解释.
还有种反例:
	如果你用信用卡买东西,你不久就会买超过你能负担的,你不能付你的账单,
	因为会停掉你的车,你会丢工作,然后抑郁,最后自杀.
	这一切仅仅是因为你用信用卡买东西.
没有会这样认为,然后会考虑自己的因果分析.

*** Gambler's Fallacy
定义: 论证因为几率事件已经在过去发生了,其在未来出现的可能显著改变了.
wusd: 我已经生了3个女儿了,第四个会生儿子的.

这个谬误是赌徒典型犯下的,错误地认为胜利的几率增大或者向他们有利变化,因为过去发生的事情.
比如loser说的: 我不会输,我手气火热. 我要转运了,已经输一碗上,这次全部赌上.
这些人没意识到,每次投掷硬币和塞子不会受之前的影响.
犯这种谬误,得出推论,错误地假设现在发生事件的几率受过去事件的影响.

考虑一对父母已经生了三个儿子,想要个女儿.认为这次生女儿几率要大的多,实际几率是50-50.

这种谬误一直引诱我们去犯,严重违背了好论证的充分原则.
错误地把统计意义的上概率和单个事件的概率混淆.

EXAMPLE
因此, 我的下个配对很可能非常好. C
因为我一直有7场坏的配对连续了. P
第8场的结果会被之前的消极7场 而改变 P

前面7场和第8场没有因果关系,第8场的结果好坏几率也不会改变.
每个事件独立.

EXAMPLE
我的时间来了. C
因为我之前没有赢到任何东西. P
我的这次会被之前没有赢到而改变. IP

他认为自己参与的次数会改变赢奖的几率,实际上每次抽将都是独立事件,不会改变.

EXAMPLE
这一次是head. C
连续5次tail了. P
这次head的几率会因为之前的连续5次tail而改变. IP

**** Attacking The Fallacy
attack这个非常难,你需要解释这里没有因果关系在这些概率事件.
比如翻硬币,统计数据30次的概率是各15次,但是这不是对于每次扔硬币之间的,而是对于一组扔硬币的概率.

即便是arguer接受了独立事件不互相影响,仍然是不知觉地违背这个论断.
比如: 投了15次硬币,15次是头,投第16次时,它们仍然会趋向认为尾的概率更大点.
你需要指出这种错误分析会导致一些错误的结论.

举个反例能得出矛盾的结论.
比如一个玩poker的一整晚运气差,越是运气差越会觉得今晚不是我的夜晚.
但是业有可能得出: 我的时间来了,我要开始运气好了.
两种想法都是错误的,无论是说运气会持续下去,还是说转运.相互矛盾了.
选择任一一个都是武断的.
wusd: 首先要指出这种事件之间是互相独立的,概率是关于多个事件,而不是事件与事件之间.
	然后arguer还是这么判断,就要指出这样错误假设会得出错误结论.
	还可以举反例: 如果今晚运气不好,你会认为坏运持续下去,还是马上转运.

* Chapter 9 Fallacies That Violate The Rebuttal Criterion
这章帮你:
	- 用自己的话定义或描述每个fallacy违背rebuttal标准的基本特征
	- 辨认~叫出名字和解释在这些谬误的推理模式,当在生活或讨论中遇到
	- 使用有效的策略去attack或帮助他人纠正其谬误推理
提出的论证要包含对于最有可能出现的强烈的批评的反驳

大多数论证没有这个反驳.但是为了满足这条原则,好的论证应该预估可能的批评,通过在前提里提出他们来削弱其.

三大类违反反驳原则:
	1. 反证谬误
	2. 人身攻击谬误
	3. 转移注意力谬误
** Fallacies of Counterevidence
反证谬误是通过没有老实地处理反证据或批评.要么拒绝考虑或不正当的减弱反证据,要么忽略或省略批评和反论证.
wusd: 证据, 和批评/反论证

*** Denying The Counterevidence
定义: 拒绝认真考虑或不公正地减弱证据

这条谬误最根本的形式是不愿意承认任何能反驳其立场的可信证据.
不是直率地承认反证据,而是拒绝考虑或不正当削弱,用解释掉的方式.

EXAMPLE:
圣经正确表达了人类怎么来的. C
因为你的生物书说人是从低等生物进化而来. P
你的书仅仅是一些人的观点. Rebuttal P
圣经说上帝创造人. P
圣经不是某些人的观点,而是表达事实. I Rebuttal P

没有证据能说服arguer关于生物进化,因为任何证据都被提前解释掉了,被当作仅仅是某些人的观点.
这种Rebuttal premise没有认真对待证据,因此也就无效.
再讨论也是浪费事件和精神能量.

EXAMPLE:
Debbie和Pat讨论大麻合法化.
Debbie注意到一部分近期政府研究表示适度使用大麻没有明显的证据表示有害.
Pat说她不关心什么政府的研究,大麻就是有害的,不应该合法化在任何情况下.

Pat压根就不认反证据.
如果问Pat什么能支持她的立场,她又会说没有反证据证明她错了.

EXAMPLE:
senator说: 同性恋就是后天习得的.你所谓的研究说是与生俱来的就是被左派编造的来让我们接受gay.

senator没有否认反证据,并且把反证据解释掉了,解释为左翼的工作.
这种反驳无效,arguer并没有严格对待这些证据.


**** Attacking The Fallacy
要证实arguer是否真诚地去反证据开放,你可以问他特殊的证据,如果提供,会减弱他的论证.
如果她不能或不愿意明确的话,那转移到别的话题会更有产出和更少失望.
然而,有时候确实想指出来跟一个不愿意接受反证据的人讨论是无用的.
如果他能明确,那么你可以尝试努力找这种证据并且摆在台上.

*** Ignoring The Counterevidence
定义: 忽略或者遗漏重要的且反对某人立场的证据,给一种错误没有明显的证据反对它.

没人喜欢输比赛,尤其是我们认为自己是最棒的.
我们也不喜欢输论证,但是我们知道好的论证是被所有的证据支持的,我们不想靠作弊(故意无视对我们不利的证据)去赢论证.
如果某人对某个立场有强的执念,就很容易有意或无意地掉入这个诱惑当中.

作为truth-seeker,我们应该欢迎任何减弱立场的证据.
如果任何证据都催毁不了我们的论证,我们就更确信自己的立场.
如果证据明显地催毁了我们的论证,我们应该感激,因为我们离错误远了,离真相更近了.
一个论证忽视反证据没有满足rebuttal原则,因为重要的相关证据没有被衡量进去.

EXAMPLE:
我们应该快速执行死刑对那些判刑的重犯. C
因为立刻杀死被判刑的重犯会减少其他市民的担忧. P
	因为他会避免危险人士社会. subP
会节省大量的钱用于维系管理判刑者在长期的审查程序中. P
也是对潜在的罪犯有效的威慑. P

快速死刑忽略了很多相关的考虑,至少不公正会完成通过避免申诉的权力.
受宪法保障的程序是一个标准也是司法合理的部分帮助正义得到伸张.
这样的一个论证,忽略掉了其他重要的考虑,不是好的论证.

EXAMPLE:
我认为大家不想买摩托. C
摩托危险. P
吵. P
一次只能骑两人. P
不能在雨天骑. P
还要戴不舒服的头盔. P
wsud: 像那种辩论赛中,很多人为了赢,仅仅只是谈对自己有利的一面,忽略对自己不利的证据.

还有反证据没考虑.
摩托是相对便宜的交通工具.
比车子要灵活.
容易找停车的地方.
很多人更喜欢摩托.

EXAMPLE:
我认为大家更远在家看电影而不是去影院. C
在家很容易租片子或者在线看. P
可以在私密的家里. P
有很多电影的选择. P
不用支付高额的影院费用. P
不用打扮. P
不用雇佣babysitter. P
不用赶交通或者买气油. P
不用支付高额的食物和饮料费. P

1. 租电影要等到影院上映几个月后
2. 许多人喜欢打扮然后办完外出
3. 大荧幕的体验
要评价去不去应该对比在家相对于在影院的好处.

**** Attacking The Fallacy
不要吃惊别人论证时没有提反证,很可能他考虑了反证据,但是认为不足以伤害自己的立场,也不值得去提.
我们极少数相信反证据能伤害我们的观点,所以我们要保持怀疑.
如果你怀疑别人忽略了反证据,确保他知道反证据并且可以证明到你满意.
如果他没有意识到反证据,你可能要指出来最致命的反证据,问他如何才能减弱这个力量.
如果他做不到,你可以建议arguer放弃他错误的观点.

一种聪明的方法是承认其然后编制一些小的反对,在其持续地提出片面的证据.
这会给人一种客观的感觉,有时候能能消解这个fallacy受害者的怒气.

** AD HOMINEM FALLACIES
没有满足rebuttal原则通过攻击批评者而不是他的批评或者证据,针对个人了.
三种: 1. 辱骂个人 2. 毒化井水(批评者的动机和个人环境) 3. 两人都犯错了(你也这么干了/想了)

在论证性的内容处理个人,非常重要的是区别证词和论证.
例如:
	一个出名的撒谎者和疯子在作证,他的身份确实和他证词的可信度相关,证词是对于事件描述.
	但是其做的论证,不会受其任何影响,只会受论证本身影响.
	无论作论证的是疯子,孩子,纳粹,即便是最疯的人都有可能作出好的论证.
eg:
	一个死囚犯论证反对死刑,并不会因为其来源影响其论证.
尽管一个人因为可疑的动机,个人性格,行为的问题可以影响我们对于其证词的评估,但是不会影响到我们对于其论证的评估.
如果允许这种影响我们对论证的评估,会导致我们犯人身攻击谬误.

靠攻击批评者逃避rebuttal counterargument的责任,也违背了相关性的原则.
因为个人性格,行为,动机不会影响其批评和反论证.

*** Abusive Ad Hominem 辱骂性人身攻击
定义: 攻击对手用私人的或者辱骂,作为忽视和损害其批评或论证.
wusd: 田文镜
https://www.bilibili.com/video/BV1MM411K75p/?spm_id_from=333.337.search-card.all.click&vd_source=2d6ae26ab97a922879712d346f464179

这种辱骂或个人攻击通常采用的注意批评者不好品质的形式.
取决于arguer在特殊场景下,恰好发现其不好的一点.
eg: messy,fat,smelly,academic,foreign,atheistic,feminist,liberal,convervative,
	a reader of the New York Times, a viewer of Fox News.
这种人身攻击不是只是用辱骂性的语言,而是通过这种方式去无视,损害,减弱其论证的力度.

EXAMPLE:
你关于性滥交的立场和论证无效. IC
因为你认为性滥交是道德可接受的. P
你从来没有和女人好好有过关系. P
因为你的立场起源于你缺乏好的性体验. IP

arguer用其认为是关于批评者的消极的个人事实,而不用认真考虑批评者的论证或断言.
wusd: 没有攻击这个批评者的批评,而是用批评者某个消极的事实,说其做的论证无效.

EXAMPLE:
Professor Lay's 观点狗屁不通. C
我没有看到任何她的作品位列于艺术展. P
她没有作品位于艺术展,所以没资格说艺术过程怎么弄. IP

EXAMPLE:
房东要求我们弄干净狗屁不通. C
他自己一件体惜穿一周. P
他自己不干净,所以他要求我们弄干净房子没道理. IP

Wayne没有回应房东给的论证,要保持公寓干净在展示期间(合同里有),他在用房东个人习惯去回避处理实质的断言.


**** Attacking the Fallacy
当我们被人侮辱式攻击时,很容易被诱惑去以相同辱骂的方式回击.
但是屈从于诱惑不会帮我们在辩论中取得优势.
最具有建设性的回应是指出arguer他是在侮辱,然后礼貌性地寻求对于你的论证或批评的估量性的回应.
有时,简单的"但是,你认为我的论证怎么样?"就能做到.

如果arguer坚持个人攻击而不是回应你的批评或论证,你应该尝试去鼓励他将人和人的想法或论证区分开来.
你可以指出我们都有可能经历许多不喜欢的人,这些人当中很多有很多好主意;
如果我们不能区分人和它们的主意,我们不能从很多好的视角里获益.
这样做后,你可能会发现abuser立场好的一面;也可能同样带动他的那一面.

*** Poisoning the Well 毒化井水
定义: 拒绝一个人提出的批评或论证,因为其个人背景或不当动机
wusd: 种族歧视???
	举贤不避亲
	非我族类,其心必异
wusd:
	LOL比赛,中国赛区LPL的队伍经常在世界赛上没有能拿个好名次,然后有很多人批评其打的不好.
	其粉丝的说法是,你连黄金段位都没有上过,没资格说话.
		你是韩国队的粉丝,去舔你的韩国爹去.

这个谬误被叫做毒化井水,因为他想要的效果是损害argument的来源,通过损害考虑这种立场的需要.
破坏来源,因为个人背景或动机,所以任何来自于这个来源的信息都不会被当作有价值地对待.
这里没有提供对批评的有效rebuttal,而是不当地破坏源头,不是好的论证.

EXAMPLE:
你对于我在流产的立场上不值得我的考虑. C
因为你批评我的论证关于流产的. IP
你不是女人. P
没有男人有任何有意义的事情去说流产. IP

不是女人的特殊背景不应该阻止男人批评或捍卫关于流产值得考虑的立场.
但是arguer不允许我们听这男人说什么,更不用说给其对其批评的反驳.

EXAMPLE:
你不能相信Professer说关于给老师更高工资. C
因为他本人就是老师,肯定会支持加薪. P

Professer是一个老师的背景不应该阻止他提出值得慎重考虑的论证.
唯一的问题是他是否有好的论证支持他的断言.

EXAMPLE:
你没有立场告诉我们是否该信守承诺. C
你不是女子俱乐部的人也不是教育界. P

这种频繁尝试去毒化井水不应该阻止我们指出其错误的属性.
论证或批评建立在其自身上,和是否来自一个女子俱乐部或教育界无关.

**** Attacking the Fallacy
井水对毒化后,非常难以attack.因为任何你的attack都会视作为来自被污染的水,不干净.
可能最有建设性的方法是直面问题:
	你已经认为我说的任何事情都是有毒的,甚至在我说之前.
	这是非常聪明的方法,我没有太多事情能做.
	但是我不打算这么简单沉默.
	一个你想要沉默我的理由是你认为我说的严重危害了你的立场.
	那我认为我确实有很重要的事情要说在这个问题上,我很好奇你对于它的回应.

当然也可以用简单的两个反例:
	1. 因为你们没有在这个班上当作老师,我不打算看你的课程评估.
	2. 因为你不是小说作家,你对于我小说的批评不值得我的考虑.

*** Two-Wrongs Fallacy
定义: 拒绝某人对于论证或行为的批评通过指责其也犯了类似的错误.
wusd:
巩汉林: 再看看我们有一些行业的收入,比方说某足球队.
	年收入三百万五百万甚至上千万了,球场上没有看到他们进球,完全给中国人丢脸.
董路: 有事儿说事儿,别总"丢脸丢脸"的,说得像平时走穴赚钱~春晚演个小品就能给中国人挣多少脸似的.

这个fallacy简单来说你也一样.
犯这个fallacy的人暗示说: 因为你也有错做你指责我的同样的事情,你的论证不值得我的考虑.
这种对于批评者的反击作为一种逃避rebut对其论证批评的一种方法.

几乎所有孩子都感觉正义在其有问题的行为时,如果回应其正在责备的父母,"但是是他先干的".
但是也总有成年人认为其行为是正义的,如果他们能对批评者说,你也这么干了.
尽管大多数的我们同意两错不会变对,但是当我们指责批评者也这么做了,会使自己觉得舒服点.

他们主要关心的不是用批评者的行为是正义化自己的行为,
也不是真的关心我们说和做不一致,尽管他们说我们是伪君子和应该实践自己宣传的.
他们正在做的是用批评者的行为作为理由去逃避自己rebut批评的责任.

EXAMPLE:
我不需要考虑你的论证. C
你做了论证反对我努力工作. P
你跟我一样努力工作. P
wusd:
	我跟我老婆经常为看手机的事情有过这种对话.
	老婆: 睡觉前不要看手机,你眼睛不要了.
	我: 昨晚你不也在床上看小说看得津津有味吗?

EXAMPLE:
老爹你的论证要戒酒不值得考虑. C
因为你现在站在这里喝酒. P

尽管非常容易诱惑儿子去指出其父亲说和做的不一致,但是正确做法是接受父亲的论证.
父亲没有实现其宣称的,没有抵消其论证的效力.
wusd:
	嫖客总喜欢劝小姐从良

EXAMPLE:
高尔夫教练让你把头低下,眼镜盯着球.
他自己没这么做,并不代表这么做是不对的.

wusd: 有可能他自己太熟了.
	eg. 比如Leo老师教我们要去做课后的习题,但是他自己并没有做.


**** Attacking The Fallacy
如果arguer指出你论证和行为的不一致,没有理由被吓到或因为这个冲击而沉默.
最好是承认冲击,面对犯这个谬误的arguer,坚持让其不考虑你可能的不一致而去估量你的批评或论证.
被察觉到的言行不一致不能解放arguer的rebut criticism的责任.

这里重要的点是其他人的无法原谅的行为不是arguer抛弃考虑批评或论证.
因为这么做的意向过于强烈,一个人通过无法完全分辨谬误性质直到被重新带到关注这里.
当然,这是你的责任.


**** ww
所有fallacy都是人性
所有人性在原始年代是对的, 在现在社会, 人的异化,神性

这本书3+1继续做
继续扩展类似的书
8月定,学什么
