#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Attacking Faulty Reasoning

* introduction
** studying a little logic
Critical thinking: a process, the goal of which is to make reasonable decisions
	about what to believe and what to do.
Learn not only the methods of recognizing bad arguments but also how to build good.

** organization of the text
4 chapters, which describe the nature of a good argument
5 major chapters describing specific fallacies
final chapter, which describes writting a logical essay.

It's difficult to know when to end discussion of an issue
	and make a decision about what to do or believe.
*Five criteria of a good argument* will solve it.

** reasons for using good arguments

** goals of the text

* Chapter 1 A Code of Intellectual Conduct
This chapter should help you to:
	discuss with others rationally, find your own fallibility, avoid linguistic confusion.

Understand "code of conduct", which represents two standards of behavior:
	a procedural and an ethical standard.

** An Effective Procedural Standard
A proceduarl standard describes the ground rules that,
	when followed, often lead us to more successful resolution of issues,
	which is productive in settling disputes, confirming judgements, and revising beliefs.

In the discussion of the "Code of Intellectual Conduct",
	the evolved consensus position is rarely one of the two original positions;
	it's usally a "third" and better one.

** An Important Ethical Standard
The ethical standard makes us argue fairly.
If we don't, it prevents the issue from being decided or at least further explored.

** A Code of Intellectual Conduct for Effective Discussion
In the "discussion", you should make the following principles a part of your intellectual style.

*** 1. The Fallibility Principle
Be willing to accept the fact that he or she is fallible,
	his or her initial view may not be the most defensible position on the question.

*** 2. The Truth-Seeking Principle
Each participant should search for the truth or the most defensible position
	so that everyone should examine alternative positions seriously and allow other to do so.

*** 3. The Clarity Principle
Avoid linguistic confusion and separate from other positions and issues.

*** 4. The Burden-of-Proof Principle
Not anyone but the proponent should provide an argument for his position when someone asks.

*** 5. The Principle of Charity
If an opponent's argument is reformulated, it should be expressed consitently.
And the paritcipant should be given the opportunity to amend it.

*** 6. The Structural Principle
An argument made by anticipants
	needs to meet the fundamental structural requirements of a well-formed argument.

*** 7. The Relevance Principle
The reasons you prvoides should be relevant to the conclusion.

*** 8. The Acceptability Principle
Reasons should be accepted by a mature, rational person
	and meet standard criteria of acceptability.

*** 9. The Sufficiency Principle
Reasons should be suffcient in number and weight to support the conclusion. 

*** 10. The Rebuttal Principle
One who provide an argument should rebut all serious criticism of the argument.

*** 11. The Suspension-of-Judgement Principle
If there is no position defended by a good argument or two or more positions by equal strength,
	suspend judgment about the issue.

*** 12. The Resolution Principle
When an argument is a structurally sound one
	that uses relevant and acceptable reasons
		that together provide sufficient grounds to justify the conclusion
		and that also includes an effective rebuttal to all serious criticisms.

** The Fallibility Principle
One's own initial view may not be very defensible so that he or she is fallible.

Accepting your own fallibility mans that you are willing to change your mind.

It's a neccessary condition of intellectual progress,
	making progresses among scientists, philosophers, and most other academics,
	however making so little progress in religion and politics.

If there is any doubt about the principle,
	choose an issue about which people hold conflicting opinions.

We think a position which we spent time developing and refining is defensible,
	so others think.

It not only calms the emotional waters surrounding the issues,
	but also it has the potential for opening our ears to different and better arguments.

Try to be the first to confess your own fallibility,
	your opponents' behavior will tell you that whether he is willing to have further conversation.

Even a critical thinker only have changed his mind about an important issue once in the past year.
It's more likely a person would turn out to be wrong on more issues than right.

** The Truth-Seeking Principle
-

We come to true knowledge only by frist recognizing our own ignorance or lack of knowledge,
	so we must condsider criticism of our own views in discussion.

The truth is not likely to be in our custody,
	but is the most defensible position supported by the strongest or best available argument.

To find out truth, we need not only to assume that we may not have the truth now
	but to listen to arguments for alternative positions and encourage criticism of our arguments.

After having done the hard work of investigation,
	we should not give the impression that we have an open mind about the issue
		and carry on a pseudo-discussion.
We could explain that to our opponent
	or join the debate when we think we might have missed something.

Because of hope of winning, we sometimes cheat to do it.
The truth comes at a price
	-- a willingness to look at all available options and the arguments in support of them.

Not try to win by ignoring or denying the counterevidence against your positions.

** The Clarity Principle
-

Even if we think what we say is perfectly clear to ourselves,
	it may be confusing, vague, ambiguous, or contradictory to others.

We must usually deal with one feature at a time
	so that each party must pay attention
		to keep other interesting issues, related issues from clouding the discussion.

We must not falter the potential resolution of an issue because of verbal confusion.

** Assignments
1. Discuss some of the obstacles of adopting the "Code of Conduct for Effective Discussion"
		as a means of resolving conflicts in our practical lives.
	 For example, why do you think good arguments so rarely seem to change minds?

	 We have deep emotions on our original minds
		so that we don't want to change them, even if we listened to a better argument.
	 Sometimes if we change our minds, others will think that we are weak or often make mistakes,
		which leads to the decline in status in society.

2. Do you agree that failure to follow the Code of Intellectual Conduct in discussion
		may be immoral?
	 Why or why not?

	 Yes, I do.
	 If others in discussion follow the code but you don't,
		they will make little progresses because of your failure.
	 They will receive less than they should be, may get frustrated.

3. Why is it inappropriate to continue in a serious discussion
		if you are not open to the possibility of changing your mind?

	 If you're not open to the possibility of changing your mind,
		there might be the emotional waters surrounding the issues
		and you won't open your ears to different and better arguments.

4. Are you a critical thinker?
	 If so, describe an occasion wherein you changed your position
		by force of argument on an important issue in the past twelve months.

	 I am probably a critical thinker in some aspect.
	 I used to insist that the tasks which my boss order should be done only in my way.
	 I changed my mind when I began to listen to other opinions,
		in which I learnt my own view is not the best way to solve problems.
	 It really makes me a better programmer and makes me get along with my colleagues better.
		 

5. The next time you are in a heated and unresolved discussion on an important issue,
		stop and confess that your position may be wrong.
	 If the other participants do not follow suit,
		ask them whether they are also open to the possibility of being wrong.

	 Ok, I will try it the next time when I discuss the tasks with my colleagues.

6. It has been claimed that an argument for a position is not a good one
		until the arguer has effectively rebutted anticipated serious criticisms
			that might be brought against it.
	 Since following this advice would call attention to flaws in your own argument,
		do you think this would tend to weaken it or the position it supports?
	 Why or Why not?

	 No, I don't.
	 Whether my argument or his is the most defensible is not a big deal to me.
	 Before being a winner, I'm a truth-seeker.
	 Therefore, it's more important to seek truth than to win.
	 Thanks to following this advice, it will help me to seek more defensible opinion better.





* Chapter 5 Fallacies that violate the structural criterion

- 用自己的语言,能够描述出违反structural的谬误的重要性质
	解: 你说这个谬误叫argue in a circle,最重要的性质是 前提和结论实际是一回事,前提证明结论,结论又证明前提,所以叫循环论证
- 在实际讨论中能够识别,叫出名字,解释谬误的形式是啥样的
	解: 我们在讨论刘亦菲是不是美女, 然后有个sb一直称呼刘亦菲是女神,所以是美女;我们这时候要说他犯了Question-begging language.还要说明,我们正在刘亦菲是女神,已经暗含了刘亦菲是美女的假设.
- 能够采取有效的效率attack这些谬误
	解: 魔术, 我们知道了自己犯了肯定后件的谬误, 然后attacking, 去想其它方式导致结论的原因.比如,助手的下半身和魔术师的上半身.


- Begging-the-Question Fallacies
	assume the truth of the conclusion in their premises
	+ arguing in a Circle
		asserting in the premise what is asserted in the conclusion
	+ question-begging language
		by means of language assume a position on the very question
	+ complex question
		presuposes in a question that a definite answer had already been given
	+ question-beggin definition ?
		disguised as an irrefutable empirical premise
- Fallacies of Inconsistency
	premises are incomppatible with one another or conclusion contradicts one premise
	+ incompatible premises
		inconsistent or incompatible premises
	+ contradiction between premise and conclusion
		a conclusion is incompatible at least one of premises
- Fallacies of Deductive Inference (well-established)
	violate well-established rules of deductive logic
	+ denying the antecedent 否定前件
	+ affirming the consequent 肯定后件
	+ false conversion 错误转换
	+ undistributed middle term 无关中项
	+ illicit distribution of an end term ?
	
	
违反这条规则的三种谬误: 丐题~不一致~违反演绎法则.

犯这种谬误,结论无法necessarily or probably来自于premises, 我们会在例子里解释为啥.

之所以叫structural one,是因为犯的谬误跟premises和conclusion的内容无关.如果用符号代替,我们也能发现从premises推不到结论.
	解: structural fallacy, 直接从structure(把命题换成符号)就能判断推导不了结论.
		例: 我老婆说: 老公爱你. 我老婆又说: 老公我讨厌你. 得不到任何结论.
			换成符号就是 A, not-A, 不需要看内容,就知道得不到任何结论.

丐题在前提中预先假设了结论;不一致是前提们不一致 或 前提和结论不一致; 违反演绎法则(well-established 也违反了acceptability principle -D)

** beggin-the-question fallacies 丐题
arguing-in-a-circle fallacy: 把结论当作其中一个前提
quetsion-begging-language fallacy: 用语言的方式,在问题中假设和结论一致的position
complex-question fallacy: 
	假定已经有答案了,
	假设对错了,有争议的问题(比如Lisa什么时候生二胎 -D)
question-begging definition fallacy: 定义中结论已经对了

论证根据定义是,一个结论被其它(different)前提支持,丐题并没有其它前提, 所以结构就犯错了.

*** arguing in a circle
循环论证的定义: 或明或暗地在前提里面确定 需要在结论里面确定的事物.
	解: 强调的某个前提和结论一致

最常见的谬误, 把结论当作其中一个前提: 例如: 你对手宣称自己的position是对的,因为它就是对的.
	解: 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.

Since A, Therefore A

arguing in a circle在实际情况往往是暗示的.
	解: 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.
		这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.

通常arguing in a circle不会用相同words和form, 实际上识别是非常困难的.
这种谬误有时候贯穿文章,章节,甚至足足一本书, 就更难识别了.

一旦识别"A is true because A is ture",这种谬误就会无比明显.

EXAMPLE: 最容易遇到的就是换换同义词
	使用带有渎神和淫秽的书是不道德的, 因为对于孩子来说听下流肮脏丑陋的词是不好的.
	解: 这里主语 渎神和淫秽的书 是 下流...的词是近义词; 不道德的 和 不好 的词又是近义词.

EXAMPLE: 这个大学在学生政策上是专制的. 因为他们对待学生像孩子. 这里仅仅是解释了专制的定义.
	解: 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.

EXAMPLE: (循环论证还从subP可以传递-D)
	he does not have the background and ability to evaluate it properly(subP)
	is biased against modern music(P)
	is an incompetent music critic(C)
	subP and C are the same things.
	解: 领导说要开除你, 理由是你不称职, 因为你做事不合格所以你对工作理解的不到位,你对工作理解不到位所以你不称职.

**** ATTACKING THE FALLACY
要注意有没有前提等同于结论,或者前提暗里假设了结论的事实.

要注意辨别你对手可疑的多义的claim.
必要时,转换成标准的格式,这样甚至能清晰地看到premise和conclusion是怎么一样的.

给个明显反例或荒谬的反例.

用丐题的人会真心觉得自己说的对.但是必须被提醒的一点,个人相信的不能当作证据.

-DDD
arguing in a circle简单,但是却难以识别.
保持注意力,注意假设和前提是不是一样; 把argument改成标准的形式更容易发现这个谬误.
	1. 前提和结论同义词换一下,实际一个意思
	2. 你问他要原因的时候, 他给你把名词解释一下
	3. subpremises其实和结论是相同的, 多走了一步想掩盖这个事实.

*** Question-begging language
定义: 通过语言的方式在特殊的提问中假设了立场,引导听众得到相同的答案.
	解: 利用语言诱导听众得到某个结论, 强调的是引诱,并没有给出答案

有意或不小心地把 未得到解决的事情 预设成 已经得到解决了.
语言本身带偏向导致预设了结论, 因此应该用描述性和中立的语言.
	解: 有意或者无意地把本来没有处理好的事情 预设成 已经得到确认的事情.
		比如: 
			1. 法庭上,女方说男方一点都不管家里.男的说我每个月给家里寄8千,女的说这是生孩子的,这里必须的,你没资格说这个.
			2. 知乎上,电车难题. 有个回答说,谁把电车偏轨就是谋杀. 需要合并下.
			3. the leading question: 

带有偏向的语言并没有给证据,所以也不能产生acceptable结论.

第一种类型: 靠煽动性语言
EXAMPLE: Natalia在法庭上喊我戴绿帽了, 所以法庭应该认为我戴绿帽了.
	解: 教师汪康夫被告强奸12名幼女,判刑10年, 伸冤54年后受害者均否认被强奸.

第二种类型: 把刘亦菲称为女神
EXAMPLE: 议题是胎儿是不是算是人类,一个辩方一直称呼胎儿为婴儿.

第三种类型: 用反问的语气好像这件事已经有定论了.
EXAMPLE: leading question(引导性问题-D) 你不是认真投票Professor Reiff作为年度教师,是吧.
	解: 这里用这种反问的语气,实际上是假设了不应该投票给Professor Reiff, 但是又没有解释.
		比如领导吩咐下一件事情需要我和同事做. 我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?

**** ATTACKING THE FALLACY
发现这个人是否犯这个谬误,注意他的语言是否阻止issue变得开放.
辩手持续使用这些词是不道德的 像: 严重的,震惊的,无法饶恕的.
	解: 像我老婆跟我争执的时候,经常用一些形容词,说我怎么怎么过分,但实质的行为却没有说多少.这种就是阻止issue开放.

总之,不要被丐题语言迷惑, 尤其是什么 众所周转, 明显的. 可以天真的来一句: 对我来说并不明显.
	解:像那种明显的,10岁小孩都直到,傻子都晓得.
		我遇到过一次,领导拉大家一起讨论问题的时候,我对于某个问题不懂的,但是领导说明显的. 这实际对于我来说并不明显. 我就说:我脑子笨,这件事我还没搞懂,能不能再解释一遍.

面对leading-question, 要找到方法去揭示他正在让你保证的预设是issue的一部分.
当然,如果这些预设,在其他地方被充分,那么就不算谬误了.

-DDD
1. 用那些情感色彩强的词,比如我被cheated, 让原来开放的issue倒向一边
2. 众所周知的,而你并不知道.比如胎儿称之婴儿. 你可以来一句, 对我来说不是明显的.
3. leading-question. 问题中有和issue有关的假设. 比如: 你投票给Professor有没有认真?(假设了你投票给Professor) 但是注意,如果假设被证实了,又不是谬误了.


*** complex question 复杂问题?
定义: 问题中有给定答案的假设, 或者问题中认为一系列的子问题都有相同的答案.
	解:强调的是给出了答案,或者所有子问题答案一致

第一种类型:
丐题的原因就是因为问题中假设了事实(未确认).
偷了手表后,你怎么处理手表的?
	解: 老师逮住学生,问,你是用左手抽烟还是右手抽烟.

值得注意的,如果回答人默认问题中的假设,那么这就不是丐题了.
丐题仅仅是当问题涉及的issue还是开放的.

第二种类型: 问题中多个claim,一否全否,一肯全肯
你会带我回去,在路上让我从商店里面买东西吗?
在这个问题里,假设了要么全答应,要么全不答应.
同样的只有回答人认同这个假设,才不是丐题.
	解: 我老婆问我,你爱不爱我,愿不愿意给我买最新的江南布衣的衣服.这里她就犯了复杂问题的错误.

解析下两个例子:
 因为你偷了我的手表(P)
 所以你偷了我的手表(C)
 
 因为你带我家所有的情况你都会带我去商店(P)
 所以你带回家的所有情况你都会带我去商店(C)
 
EXAMPLE: 
	What fraternity are you going to pledge?这里假设了要参加社团
	When are you going to settle down and get married? 两个问题.
 
EXAMPLE: 哈哈, 一口气提7个问题, 第二种类型(-D)
	Are you and Nancy going to the Keller-Trent wedding and to the reception next Saturday, even though you and she were not invited?
	2的7次方, 128种回答.
	
EXAMPLE: 为什么叫丐题(因为回答者被提问者乞讨去确认假设的事实-D)
	为啥离婚父母的孩子更加情绪化不问题比那些未离异的家庭?

**** Attacking the Fallacy
怎么样attack complex question?
1. 拒绝给直接肯定或否定的回答给这种complex question.
	如果问问题的人不明白你的不愿意回答, 反问它: "你有没有停止偷税"(这个要给个中文版的-D)
	解: 你这个问题我无法回答. 在你偷了井盖之后,你是怎么处理井盖的?
2. 指出问题中有问题的假设,告之假设还没有决定.
	给保证: 虽然如此,我愿意任何时候聊这个假设.
	解: 你这么说,xxx还没有确认,正在讨论中, 等xxx确认了, 我再回答你这个问题.
3. 必要时坚持把问题切割,一个一个回答.
	解: 坚持分开回答问题. 老婆, 我是爱你的, 但是我不想给买江南布衣的衣服.

*** Question-Begging Definition
定义: 把定义伪装成无法证伪的经验假设
	解: 注意定义是他自己给的定义,还是公众的定义.忠诚的狗不会冲主人狂吠,如果它冲主人狂吠了,那它就不是忠诚的狗.
		重新定义忠诚的狗.

经验前提和定义前提很容易迷惑.
定义前提应该是共用术语或者权威人士的思想.
	解: 比如说信佛的人不杀生.如果他杀生,那么他就不是真正信佛的人.
		大家普遍认可的信佛的人是去寺庙里拜的人.
		定义的信佛的人是不杀生的人.

经验前提做观察性或事实性的断言.
他的可接受性取决于我们的经验,相关权威的测试,以及恰当实验的结果.

定义前提假设成了经验前提,就犯了这种谬误

两条线索去发现这个谬误
1. arguer拒绝接受他经验前提的反证据
	解: 信佛的人不杀生
2. issue中的关键属术语,一直用修饰性词: true, real, genuine
	解: 真正信佛的人不杀生. be defined in an unconventional way

EXAMPLE: (线索1和2, 加修饰词,丐题顶替 -D)
issue是讨论基督教人喝不喝酒.
有人说看到基督教人喝酒.
然后有辩手定义, 如果他喝酒,那他就不是一个真正的基督教.

EXAMPLE: 
真爱不会离婚或分手.
如果离婚或者分手那么就不是真爱.
Eric可以这样定义真爱,但是这种奇怪也就无法被理性人反驳,也就没有意义了.
解: 这种奇怪的定义已经无法反驳了,也就没有讨论的意义.
	比如有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?
		偷的话: 按经验定义,不告而拿, 孔乙己定义是非读书人的不告而拿.

EXAMPLE:
true-blue 共和党人是一个人,从不离开共和党人.
对是对的,但是这种断言属于定义前提,不属于经验前提.
解: 恋爱中的男女往往对真爱的定义有偏见.
	她真爱你,她就会对你不离不弃.

ATTACK THE FALLACY:
问arguer这是定义前提和经验前提,如果他被你问着了,解释下不同.
还可以问下有没有证据支持他的前提,如果没有,很可能是定义前提.
解: 这个xx是你自己的定义的,还是大家都这么认为或者专家给出的定义?
	你这么说xx是xxx, 有没有证据来支持这个呀?
	
	如果两问题都答不上来,那么就是定义前提.
要这么定义也可以, 解释下为什么不用其它的定义, 比如通用的和相关专家的定义.
发现是定义前提后, beggar要愿意捍卫自己的定义(可能有共用术语或权威认证的).
解: 这个基督徒你定义成不喝酒的, 为什么不是每周去教会做礼拜的?
	如果你觉得你的定义更好,能说下你的理由吗?
	你看字典的定义是这样的,专家是这么说的.

***** 小总结:类型或例子(-D)
arguing in a circle:
	1. 前提和结论用同义词替换一下
	2. 你问他要原因,他给你解释名词
	3. 子前提和结论是相同的, 多绕了一下想掩盖丐题
question-begging language:
	1. 靠煽动性的语言:众所周知
		比如: 在法庭上,女性声泪俱下指责丈夫出轨,却不给证据
	2. 把刘亦菲称为女神:
		比如: 在讨论胎儿算不算人类时, 有辩方一直称呼胎儿为婴儿(婴儿已经属于人类的范畴)
	3. 引导性问题:(在问题中假设没有做过的事情, 和后面complex-question有交集 问Leo -D)
		比如: 老师问: 你是用左手抽烟还是右手抽烟啊
complex question:
	1. 问题中的两个子问题会导致 一个问题变成另一个问题的答案
		比如: 你什么结婚和安定下来? 结婚变成了安定下来的答案
	2. 问题中多个问题, 一否全否, 一肯全肯
		比如: 你爱我,愿意给我买房子吗? 
Question-Begging Definition: 首先有个经验前提和定义前提的概念
	1. 经常有true,real,genuine这种修饰语
		比如: 一个人爱国就不可能投降, 如果一个爱国的人投降了,那么就不是真正爱国.

**** Assignments
A. Begging-the-Question
1. Complex Question: 在问题中,假设在沃尔玛买东西等于勇气
2. Question-Begging Definition:
	这里定义真正的犯罪思想是渡过监狱岁月后仍然不会改正.
3. question-begging language:
	煽动性语言,没给证据
4. arguing in a circle
	因为圣经说自己是上帝显灵,所以圣经是上帝显灵
5. Complex Question:
	选民 支持士兵是增加总统国防预算的答案.
6. Question-Begging Definition:
	重新定义了sane是不会自杀的人
7. question-begging language(刘亦菲是女神)
	显然 生存下来的有机生物比没有的更适应环境
8. Question-Begging Definition
	重新定义在 价格范围的房子不包括tacky little house
	
	
** Fallacies of Inconsistency
前提们矛盾或者结论和某个前提矛盾, 这两种情况得不出有效的结论

这种不一致是不明显的.
如果某个前提可以被解释 和 另一个前提或者结论 相矛盾,那么可以认为不一致.
解: 不一致的谬误, 命题和命题之间矛盾.
	比如: 李洁是大学生,李洁不是大学生; 所以李洁上过高中.
		 李洁是服装设计师,李洁是大学生;所以李洁不是大学生.
		 
解: a perfect alibi
	嫌疑人的结论是自己有a perfect alibi
	理由 当犯罪发生时, 我正在8点去往伦敦的火车去工作
		我10点已经在伦敦了
			我工作时间是10点,而且我并没有迟到
	侦探的理由是:
		 8点去往伦敦的火车没运营
		 10点在伦敦可以坐8点25的车
	这里嫌疑犯的理由和实际情况相矛盾, 那么就推导不出他有perfect alibi.
	

*** incompatible premises
从不一致或矛盾的前提们,得出结论

这种情况得不出acceptable or true的结论:
	因为A,
	又 not-A,
	[哈哈,得不出结论]

EXAMPLE: 两个前提不一致, 又说上帝是全能的,所以没有罪恶; 又说有罪恶
	如果上帝是全能的~all-love, 那么就世界上没有罪恶.(A)
	世界上有罪恶.(not-A)
	所以,上帝不存在.
	解: 他们先假设上帝是全知,全能的,慈爱的;世界上没有罪恶 (A)
		世界上有罪恶(not-A)
		假如妈妈啥都会,啥都知道,又爱你,你的任何困难妈妈都会给你解决;
		实际上有些困难就没有给你解决.
		所以要么你妈妈不存在,要么你妈妈不是全知全能,且爱你.
	
EXAMPLE: 上帝说啥对啥就对, 这些行为道德上不对(而不是上帝说的), 两者冲突
	因为上帝说啥是对的,啥就是对的(A)(P)
	一些行为像谋杀, 上帝就不会说是对的(rebuttal P)
		因为他们是道德上不对的(not-A)(subP)
	解: 这里前提矛盾的情况是.
		上帝的说一项行为是正确的是决定事物是否正确的唯一标准.
		一些行为像强奸谋杀,上帝就不会说对的
			因为他们在道德上是不对的(注意这里除了上帝的宣言多了一项判断).

EXAMPLE:
	政治家为了拉选票,说会提升服务降低税费(A); 然后又说税负不变(not-A)

ATTACKING THE FALLACY:
把短句给他标准化, A和not-A,马上就能发现问题了.
辩论中,告诉对方一致性原则.

没病走两步, 让他从A和not-A推导出结论, 一般是退不出来的.
如果推出来了,那么他就是把其中一个当成对的,忽视了另外一个.如果他坚持not-A是对的,就有义务解释为什么不是相矛盾的.

现实中确实很难消除这种矛盾的前提.比如:我姑爷对我说,要把人往坏了想,不要去相信别人.那么他自身也在这个别人当中. 这就矛盾了.
	
	
*** Contradiction Between Premise and Conclusion
定义: 得出的结论和其中一个前提相反

形式: 
	Since A(P)
	Since B(P)
	Therefore, not-A (C)

为啥说这个错了, 因为一个论证里面不能A,又not-A这种情况出现

EXAMPLE:
	因为万事物有源头(A)(P)
	我们不能无限朔源(P)
		因为如果没有源头,我们不会出现(sub P)
	我们出现了(P)
	因此有个没有源头的起源(not-A),那就是上帝.(C)
	
	解: 一定是鸡生蛋,蛋再生鸡.
		但是鸡生蛋,蛋生鸡不可能无限循环
			因为如果无限循环,就不会有鸡和蛋
		有鸡和蛋
		因此肯定有个源头,蛋不是鸡生的,或者鸡不是蛋生的.
解: 蛋是由鸡生的,鸡又是由蛋变的
	但是鸡和蛋不会凭空产生
	所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

EXAMPLE:
	身体物理的且占空间(P) (A1)
	思想非物理的且不占空间(P) (A2)
	经历表明思想影响身体, 反之同样(implicit P)
	所以思想和身体相互交流(C)(not-A)
	解: 思想和身体相互交流, 但是因为非空间的物质和空间的物质不会互相交流,要么身体不是空间的, 要么思想是空间的.
	这样结论要么和A1矛盾,要么和A2矛盾.
	
EXAMPLE:
	所有生命都是神圣的, (P)(A)
	我们有义务不要destory it(P)
	流产destory it(P)
	因为流产是错误的,除了强奸(C)(not-A)
	解: 每条生命都是上天的礼物, 
		我们有义务不要摧毁它,
		流产摧毁了它
		所以流产是错误的, 除了强奸导致产生的孩子.
	
**** Attacking the fallacy
最好的方法去发现这个谬误,就是转换成A,not-A这种形式.
除非arguer不尊重这个不矛盾法则,否则他应该抛弃一个前提,或者找到方法解决前提和结论的矛盾.

*** Assignments
B. Fallacies of Inconsistency
1. 人类知识是建立的skepticism上的(P)(A)
   skepticism是观点, 人类永远不要知道任何事事正确的(P)(not-A)
   我们最好放弃研究(C)
   前提不一致!
   
2. 谁说我错了你对了关于吸大麻.(P)
    每个人要自己决定啥是对的(P)(A)
    我没看到用大麻有任何不道德.(P)
    你错了.(C)(notA)
    前提和结论不一致
3. 
	生命是珍贵的礼物,谁也没有权力拿走.(P)(A)
	一个谋杀其它的人正在destory it(P)
	所以我支持谋杀犯死刑(C)(not-A)
	前提和结论不一致
4.
	B: 你思考没灵感. 你认为如果观点们是相互矛盾的,就没有意义
	E: 我认为不矛盾是智力讨论的必要条件
	B: 没有理由认为矛盾就不能有意义
	E: 如果矛盾,就没有意义
	B: 如果矛盾,也可能有意义
	E: 如果矛盾, 就不会有意义
	B: 你在说什么哦
	前提和结论不一致, B的前提是 前提矛盾也会有意义, E的结论是 前提矛盾就没有意义
	根据B的前提,B的前提和E的结论会共存,所以是前提和结论不一致
	
** Fallacies of deductive inference 演绎逻辑谬误
	
*** Denying the Antecedent: fail to see other reasons 否定前件
well-formed deductive argument:
	If A, then B(P)
	A (P)
	B (C)

Denying the Antecedent:
	If A, then B (P)
	not-A (P)
	not-B (C)
	
这里关键错误在于假设A的出现一定会有B, 但是还有可能C的出现会有B
解: 正常的if then的推理是,
		如果A,那么B; A; 所以B
	否定前件是: 如果A,那么B; not-A, 所以not-B
	这里面犯的错误就是, 把A当作是唯一B的条件.
	如果抽烟,那么会短命. 但是不抽烟不代表不会短命, 因为还可以吸毒导致短命. 抽烟并不是短命的唯一条件.

EXAMPLE: 
	如果抽烟,就会短命 (A->B)(P)
	我不抽烟(not-A)(P)
	我不会短命(not-B)(C)
	解: 家中女性长辈,劝人不要抽烟,理由就是不要抽烟,抽你个短命鬼.
		家长男性长辈常常说,又不是抽烟一件事情会短命.
	
EXAMPLE:
	如果死刑减少人们犯重罪,那么就是正义的(A->B)(P)
	因为没有减少(not-A)(P)
	所以他不是正义的实践(not-B)(C)
	:这里还有其它理由,比如威慑有犯重罪意愿的人让他们不敢犯罪,可以使其称为正义的实践

EXAMPLE:
	如果期末考试过来, 那么课就过了
	因为我期末考试没过
	所以我课没过
	:还有其它理由导致课没过

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪不是狗.
	缪缪就不是动物了.

*** Affirming the Consequent 肯定后件
肯定后件后,肯定前件
Well-formed deductive argument
	If A, then B, (premise)
	and not-B, (premise)
	Therefore, not-A. (conclusion)
	
affirm the consequent
	If A, then B (premise)
	and B (premise)
	Therefore, A. (conclusion)

A不是B的唯一条件,即便是B正确时,A也正确,推理的结构也是错误的.
解: 正常的推理
	如果A, 那么B; not-B; 所以not-A
	肯定后件的推理:
	如果A, 那么B; B; 所以A
	同样的错误也是把A当作B发生的唯一条件
	举例: 如果缪缪是狗,那么缪缪是动物. 缪缪是动物,显然缪缪不一定是狗,还可能是猫. 值得一提的是,即便缪缪是狗,这项推理也是错误的.

EXAMPLE: 
	如果丈夫计划谋杀妻子,那么他会给妻子买保险(A->B)(P)
	丈夫买了保险(B)(P)
	因此,丈夫计划谋杀妻子(A)(C)
	其它理由对买保险也是充分的
解: 如果萍萍偷钱了,她就会买零食
	她买零食了
	偷没偷钱你自己想.

EXAMPLE:
	如果你SAT分数搞,你可能进入一个好大学(A->B)(P)
	你进入好大学: Centre College(B)(P)
	所以, 你SAT分数一定高(A)(C)
	这里假设了SAT分数高是进入好大学的唯一原因,还有可能是成绩高~体育和艺术特长
解: 如果你高考分数高,你可能进入北大
	你去北大了,
	所以,你高考分数高.
	撒贝宁表示北大保送也还行.

EXAMPLE:
	如果我吃红肉, 那么我生病(A->B)(P)
	我生病(B)(P)
	因此, 我肯定吃过红肉(A)(C)
	这里假设了吃红肉是生病的唯一原因

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪是动物.
	因此缪缪是狗.

*** False Conversion 错误转换
把if句中的前件和后件互换,或者把主语和宾语互换,并且认为命题的真假不变.

前件和后件转换:
	如果当开关开着灯亮了,那么灯泡是好的. 
	<转换> 如果灯泡是好的,那么当开关开着灯亮了.
换主语和谓语:
	所有的生物学家是科学家
	<不能转换> 所有的科学家是生物学家
	等价于: If one is a biologist, then one is a scientist.
	
	有些X不是Y<不能转换>很少犯,不用特意提
	
	可以转换:
		no X are Y
		some X are Y 
	
	到底可不可以转换, 去觉得主谓 都distributed or 都undistributed.那么就可以转换. 一个distributed一个undistributed不可以转换.
	distributed: term下的所有成员都明确了

EXAMPLE: 
	解: 所有宗教徒都是依赖外界的人
		所有依赖外界的人都是宗教徒<不能转换,例如:孩子>
	
EXAMPLE:
	所有吸冰的人都是吸大麻的人
	<不能转换>所有吸大麻的人都会吸冰
EXAMPLE:
	如果你是基督徒,那么你一定关爱他人
	因此, 如果你关爱他人, 那么你一定是基督徒
	
ATTACKING THE FALLACY
举反例:
	所有苹果都是水果
	<不能转换>所有水果都是苹果
	
	如果这个人是总统,他至少35岁且美国公民
	<不能转换>如果他至少35岁且美国公民,那他是总统

*** Undistributed Middle Term 无关中间项
定义: 从三段论中得出结论, 三段论中前提的中间项没有被distributed至少一次


1. structure of a syllogisms
	1.1. 3个statements 2个premises和1个conclusion
	1.2. middle term和end term
		所有term都出现且只出现两次
		middle term两次出现在premises里
		两个end term一定出现在conclusion里
2. the four types of statements used in syllogisms
	A. all X are Y
	E. no X are Y
	I. some X are Y
	O. some X are not Y
	universal: 全称
	particular: 特称
	affirmative: 肯定
	negative: 否定

3. the nature of distribution
	某个分类下的所有成员都被这个term包括
	例如: AsEbInOp
		- all X are Y. subject是distributed
		- no X are Y. both是distributed
		- some X are Y. neither term是distributed
		- some X are not Y. predicate是distributed.

4. the two main rules of syllogistic reasoning
	1. 中间项至少得distributed一次
	2. 在结论中是dirtibuted的term, 至少得在前提里面distributed一次
	
所有教授是技能丰富的人
没有技能丰富的人是underpaid
因此没有教授是underpaid
symbol化:
	P(A)C  (P)
	C(E)U  (P)
	P(E)U  (C)
	
EXAMPLE:
	PH (I) PDL (P)
	PR (I) PH (P)
	PR (I) PDL (C)
	中间项是PH, 两个premises都是I, 所以PH都是undistributed.和规则1相反

EXAMPLE:
	D (A) CLA
	J (A) CLA
	--------
	J (A) D
	
EXAMPLE:
	SK (A) PAG
	R (A) PAG
	--------
	R (I) SK
	
ATTACKING THE FALLACY
别人不知道符号标记这一套,所以得给别人举例子:比如: 教授读书;孩子也读书;所以孩子都是教授.
但是你自己得懂这一套,这样你用起来才能得心应手.

*** Illicit Distribution of an End Term 最后项的错误分布
a distributed end term in the conclusion is not distributed in the premises

EXAMPLE: 
	书上犯错了,Therefore, members of the jury are people who are likely to come to a false
judgment. (E) (conclusion)
	IRF (A) CFJ s
	JM (E) IRF both
	-------
	JM(E)CFJ both
	CFJ is undistributed
	
EXAMPLE:
	MR (As) J
	BGG (Op) J
	-------
	MR (Op) BGG
	BGG in conclusion is distributed, but in second premise is undistirbuted
	
EXAMPLE:
	NC (A) EX
	NC (A) EE
	------
	EE (A) EX
	the EE in conclusion is distributed, but in second premise is not.
	
ATTACKING THE FALLACY
还是一样, 自己要会用符号系统, 但是跟别人解释,还是举明显得反例
	所有父亲有孩子
	没有妈妈是父亲
	-------
	所以没有妈妈有孩子
	
ASSIGNMENTS
C. Fallacies of Deductive Inference
1. 
	如果毕加索的作品有艺术价值,那么会被大多数人欣赏 (P)
	被大多数人欣赏 (P)
	所以, 它有艺术价值 (C)
	If AM, then  A
	A
	--------
	since AM
	肯定后件
2.
	spheres always cast curved shadows(P)
	the earth casts a curved shadow on the moon during a lunar eclipse.(P)
	the earth is spherically shaped(C)
	S (A) CS As
	E (A) CS As
	--------
	E (A) S As
	CS undistributed middle term
3. 
	BT (E) T Eb
	T (A) C As
	---------
	BT (E) C Eb
	C is an undistributed middle term in second premise
4.
	If OL, then SOT
	SOT
	----------
	OL
	肯定后件
5.
	IF SL, then OV
	not-Sl
	--------
	not-OV
	否定前件
6.
	MJA (I) NV In
	ACD (I) MV In
	--------
	ACD (I) MJA In
	undistributed middle term and illicit distrubtion of an end Term
7.
	If M, then E
	not-M
	---------
	not-E
	否定前件
8. 
	If 控制垄断, then 公共好处增加
	想要公共好处增加
	--------
	所以控制垄断
	肯定后件
9.
	I can do anything I want.
	Nobody can tell me what to do and what not to do.
	
	你必须遵守法律啊.
	我必须遵守法律, 但是政府不能告诉我去做什么.
	-------------
	我可以做任何事情我想做的.
	前提不一致
10.
	E (A) V
	P (O) V
	--------
	E (I) V
	中间项不能出现在结论上
11.
	If he really loved her, he would insist on being the sole provider
	Question-Begging Definition
12.
	肯定后件
	If a cat licks antifreeze, the cat will die.
	I left my cat out last night and she died.
	--------
	She licks antifreeze.
13.
	Complex-Question:
		在问题中假定了事实, 我给你的5000块,你给丢在股票市场了.
14.
	UP (I) K
	RP (I) K
	-------
	UP (I) RP
	中间项一次都没有distributed.
15.
	Question-Begging Definition
	自己定义literally true.
16.
	Question-Begging Definition
	自己定义well-adjust people事那些不自杀的人
17.
	Question-Begging Language
	用stupid这种煽动性的语言
18.
	If the light was on, then he was at home.
	The light wasn't on.
	----------
	He wasn't at home.
	否定前件
19.
	Arguing in a Circle
	前提和结论一致
20.
	SHMW (I) D
	FP (E) SHMW
	---------
	FP (E) D
	D在结论是distributed, 但是在前提里面不是distributed.
	
21.
	前提不一致
22.
	Question-Begging Definition

** 四种丐题的区别
四种丐题的区别:
	arguing in a circle: 强调的某个前提和结论一致
		1. 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.
		2. 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.
		3. 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.
	Question-begging language: 强调利用语言引诱听众给出想要的结论. 强调的是引诱,并没有给出答案
		1. 我侄子哭得稀里哗啦地跟他妈妈告状,说别的小朋友带他.问他怎么打的,他又不说话.
		2. 读高中时,我们在讨论哪个女生是不是美女.到讨论到闵xx的时候,某个同学一直称呼闵xx为女神.
		3. 比如领导吩咐下一件事情需要我和同事做.我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?
	complex question: 强调的是在问题中给出了一些答案,或者所有子问题答案一致
		1. 老师逮住学生. 你是用左手抽烟还是右手抽烟?
		2. 我老婆问我,你爱不爱我,给不给我买最新的江南布衣的衣服?这里她就犯了复杂问题的错误.
	Question-Begging Definition: 关键在于定义是说话者自己的,还是公众的共识
		1. 邻居说他家狗很乖不会冲人狂吠. 然后我说狗昨天冲他叫了.邻居说,他冲你叫了但是没咬你,所以它不会冲人狂吠.
		2. 有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?

** 前提/结论不一致的案例
前提与前提不一致:
	1. 新二 a perfect alibi 那一课.
			嫌疑犯声称自己有a perfect alibi.
			嫌疑犯说:当谋杀发生时, 他正在8点去往伦敦的火车上, 理由是他10点已经在伦敦工作了.
			而侦探说: 他没有坐8点去往伦敦的火车,理由是8点去往伦敦的火车停运, 并且8点25的火车也可以10点前到达伦敦.
			这里嫌疑犯给出的前提和侦探给出的前提不一致,所以得不出他有perfect alibi.
	2. 上帝是全知全能的. 那么上帝能不能造出他举不起来的石头?
		 能不能造出举不起来的石头,分为两种情况, 一种是造出举不起来的石头, 和上帝全能矛盾.
			另一种是造不出举不起来的石头, 也和上帝全能矛盾.
		 因为前提和前提相矛盾, 我们不能得出任何结论.
前提和结论不一致:
	1. 蛋是由鸡生的,鸡又是由蛋变的
		 但是鸡和蛋不会凭空产生
		 所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

** 违反演绎推理
否定前件:
	1. 家中女性长辈,劝我不要抽烟.如果抽烟,那么就会打短命.不抽烟,那么就会活就一点.
		 不抽烟可能导致其他不良习惯,其他不良习惯同样也可以导致短命.
肯定后件:
	1. 如果平平偷钱了,那么她就会去买零食.
		她刚刚买了一堆零食.
		所以钱是她偷的.
	2. 如果你高考分数高,你可能进入北大
		 你去北大了,
		 所以,你高考分数高.
		 撒贝宁表示北大保送也还行.
	3. 我跟老婆有一天两个人都口臭,我们认为是前一晚都吃了金汤酸菜鱼的原因.
		 如果酸菜鱼有问题,那么我们会口臭.
		 我们一切口臭了.
		 那么那个酸菜鱼有问题.
错误转换: 
	 全部肯定换主谓语:
		所有的生物学家是科学家.
		所有的科学家是生物学家.
	 条件中, 前件和后件互换:
		如果我提前过户了二手房,那么卖家提前还款了.
		如果卖家提前还款了,那么我提前过户了二手房.(还可能卡其他环节啊,比如交契税)
无关中间项和错误分布的端项: 用处不大,用文氏图更直观
		AEIO: 分别是全部肯定,全部否定,部分肯定,部分否定
		AsEbInOp: s=subject, b=both, n=neither, p=predict,代表对应项是distributed
		Term: 中间项出现了前提两次, 两个端项一定出现在结论
		两条法则:
			1. 中间项至少distributed一次(按AsEbInOp判断)
			2. 端项在结论中是distributed,至少在premises中distributed一次.
无关中项和错误确定的端项:
	1. 首先要是三段论,两前提+一结论,前提和结论得是全部肯定~部分否定~全部否定~部分肯定的一种
		 解: 这里要非常注意AEIO和条件句的区别
			AEIO: 所有人都会死
			条件句: 如果他是人,那么他会死
			举例: 全部肯定:所有人都是会死的人
					 部分否定: 一些人不是女人
					 全部否定: 所有人都没有智商超过5w
					 部分肯定: 有些人智商超过200
	2. 全部肯定是主语,部分否定是谓语,全部否定都确定,部分肯定都不确定
		 全部肯定是主语: 所有人都是会死的人, 这里 "人"确定了范围(distributed)
		 部分否定是谓语: 一些人不是女人, 这里"女人"确定了范围
		 全部否定都确定: 所有人都没有智商超过5w, 这里"人"和"智商超过5w的人"确定了范围
		 部分肯定都不确认:有些人智商超过200, "人" 和 "智商超过200的人" 都没确定范围
		 这里记忆还有个技巧. 全部肯定的否定是部分否定, 由主语确定变成谓语确定;全部否定的否定是部分肯定, 由全部确定变成全部不确定.
	3. 两端项和中项各出现两次,中项不会在结论中出现
		 这里就是注意把主谓项规范成一致的.
			比如:
				所有人会死
				苏格拉底是人
				所以苏格拉底会死
				------规范后
				所有人都是会死的人
				苏格拉底是人
				所以苏格拉底是会死的人
				这里有三项且各自出现两次: 人 会死的人 苏格拉底
				人是中项,并且没有出现在结论里
	4. 两法则: 中项必须确定一次; 在结论中确定的端相必须在前提中确认至少一次
			继续上面的例子
				P1:所有人都是会死的人
				P2:苏格拉底是人
				C:所以苏格拉底是会死的人
				1. 根据中项必须确认一次判断, 人是中项
						P1:所有人都是会死的人
						-------
						全部肯定是主语, 人是确定的, 满足了规则
				2. 根据结论中确定的端项,必须在前提中确认至少一次
						C:所以苏格拉底是会死的人
						因为部分肯定都不确认
						所以不需要判断

					 
* Chapter 6 Fallacies That Violate the Relevance Criterion
- 用你自己的话描述不相干谬误
- 发现,叫得出名,解释谬误的形式,当辩论或生活遇到的时候
- 用有效的策略去帮助别人纠正他们的不相干谬误
(1) fallacies of irrelevant premise
(2) fallacies of irrelevant appeal.

公输般

英国护卫

--------------------
- 用自己的话描述下那些违背相干性原则的谬误
- 在生活和辩论中遇到的时候,遇到了能辨识,叫得出名字,能够解释谬误的形式.
- 用有效的策略帮助别人纠正他们的不相干谬误

论证要有相干的证据.

两类不相干谬误,一种是用不相干的前提,另外一种是各种诉诸.

1. 不相干前提
   从前提推导不出结论:前提和结论没联系,或者前提到结论有跳跃性.
2. 诉诸
  
** Fallacies of Irrelevant Premise
1. 根据旧的情况推断新的事物,无视环境已经发生了变化
2. 用看似有理的原因而不是真正的原因去隐藏掉真实的想法和行为
3. 对理由去做另一番解释,目的是为了得出结论.
4. 为了得出结论,而去编造理由.
  
*** Genetic Fallacy
用过去的context去计算现在的事情,无视新旧之间已经发生了变化
wusd: 刻舟求剑

只考虑事情一开始是怎样的,因而忽视了事物的发展,退化,差异.
wusd: 要用发展的眼光看待问题,
什么人容易犯呢?
  1. 把过去看事物的老眼光:或积极或消极,用在现在了
     wusd:
			吴下阿蒙.
		  小米就是钓丝低端的,所以小米su7我完全不考虑买.
			我们经常会根据很久的经历去判断一个人现在到底怎么样,并且这种想法很难改变.
				比如人际交往,第一次如果留下坏印象了,后面就很难再改变看法.
  2. 一些宗教啊,根据原始教义不许做某事,但是到如今已经发生了变化了.
     wusd: 回族人不允许吃猪肉,原本是当时卫生不达标,猪肉脏,吃了易得病. 但是现在科学化养殖,仍然还是禁止吃猪肉.

这种谬误的模式就是:
  前提和结论是要相干的.现在的结论虽然和以前的前提相干,但是前提已经发生了变化,变得不相干了.

EXAMPLE:
	我不会给Don Reichard投任何票,我和他同学的时候,他在学校里完全就是个混子.
	实际上,Don有可能变成熟了,变成了和原先完全不一样的人.
	wusd: 对应了第一种例子.用老眼光看人.那我们同样也不应该用老眼光去看自己.
		因为Don在上学期间是混日子的.(P)
		上学混日子,当官员时会一直混日子(IP)
		所以Don在当官员时同样会混日子.(C)
EXAMPLE:
	因为结婚戒指原本是丈夫用来束缚他们妻子的标识(P)
	而且这个标识会一直做同样的事情(IP)
	这种行为实施了性虐待(P)
	所以,现在谁还用结婚戒指也是实施性虐待(C)

wusd: 这里讲的例子,是有可能变化,但是也有可能没变.所以对于Don能不能胜任官员,需要继续调查.
	对于结婚戒指实施性虐待需要更深入的统计数据
EXAMPLE:
	虽然我听说李医生是一个很帮的医生.但是我不会去李医生那里看病,我跟他同学的时候,他一直看黄片.
	wusd: 虽然吴教授是一个优秀的导师,但是我不会报考他的研究生,因为他以前上学时经常打架斗殴.

ATTACKING THE FALLACY
这些固有印象连接我们的思想,会在我们考虑的时候严重地影响我们对其的喜爱或厌恶.比如:让你去评价下前男友的装修和衣服.
但是当我们要深思熟虑的时候,就要想办法抵制这些因素的影响.
当辩手这么按这种方式想问题的时候,我们就可以反过来问他现在这事物有没有厌恶点或喜爱点.
wusd: 人是感情的动物,想要不受原本的固有印象影响去判断一件事非常困难,要想办法抵制掉这些因素的影响.
	当有人或者自己按这种方式考虑问题的时候,就可以反过来问下这件事当下有没有值得的点和厌恶点.

假如拥有长期亲密关系的伴侣,最开始的约会或见面却是场乌龙或恶作剧.
这对伴侣,肯定不会以最开始的价值来评价现在关系的价值.
如果能够搞清楚这种情况,自然能够正确处理其他事情.

你说林师傅是大厨,但是小时候他弄个馅饼都搞得乱七八糟的,所以我不会吃他做的任何食物.

*** Rationalization 狡辩
用听起来很响亮但实际是假的理由去去主张某个立场.

出于尴尬~恐惧~其他原因,真实的原因被隐藏了,而使用fake的reasons去推导出结论.

好的论证啊,是由证据推导到信念;而在rationalization里,信念已经有了,前提或理由根据信念捏造的.

因为前提或理由是捏造的,并不支持结论了,那么就和结论不相干.

EXAMPLE:
我考试一向成绩不好.P
考试也不能说明我的真实能力.P
考试前我收到影响我的坏消息.P
----------
我不应该被要求在Law School Admissions Test表现很好.

如果Xavier是个大二的哲学生,那么他可能已经通过大量考试了,否则他升不了大二.
如果他确实考试不行,教授应该早就知道原因,不用再提醒了.

这种坏消息的影响也不成立.
当考生遇到考不过的情况,大概率就是考试太难了.X需要努力提升必需的技能以便在今后的考试中顺利.
如果坚持给这个fake reasons的话,会阻止自己的进步.

wusd: 这我跟读英语的时候,有时候懒了,不想动了.
会自己给自己找各种理由辩解:比如工作累了;今天和老婆逛街了;要陪猫完;今天已经看了好几章的英语了.
实际上做完这些事情我仍然是有精力和时间去做这个跟读的.

EXAMPLE:
我早就计划把他甩了.跟他在一起真无聊.我早就应该甩了他,我觉得他很可悲.

wusd: 我跟我老婆吵架的时候,后面发现是她不对,我要求她道歉.她不想道歉,给的理由是,上次我没给她道歉.
但是实际上我当时道歉了,还转了红包.
这里她确信自己没错,不想道歉,然后认为当时我没道歉.

EXAMPLE:
我觉得本来应该去我侄子的婚礼,但是我们一直走的不是很近.
我只见过新娘一次,人家都不记得我.
我不知道要买什么给人家做结婚离婚,因为他们该有的都有.
而且很多人在这呢,压根不会想我.

真实原因可能就是不想买礼物;不想宿妆打扮;想去看球赛.
wusd: 同事的婚礼,我犹豫了很久要不要去.然后其他同事问我去不去.
我说不知道包多少红包.
不知道人家叫我去是客套还是真实.
人家亲戚朋友那么多,缺我一个不缺.
其实真实的理由就是: 她是在隔壁县办的婚礼,而我没有车,又不太好意思蹭其他同事车,害怕社交.但是又不敢真正说出口.

**** ATTACKING THE FALLACY:
狡辩者大概率是出于要面子,不肯说出真实理由,要让他们知道我知道他没有说实话(论证).

如果是错的或者没关系的,你是不是还是觉得结论是对的.
如果回答是yes,那么他已经承认自己错了.
如果回答是no,就需要找到方法去证明他的错误.最好的结果是,当事人放弃或改变观点了.
wusd: 如果说红包金额可以确认,然后人家真的是请你去,你去不去?
不去,那么就承认了自己有其他原因.
如果去,那么就说明红包金额可以和其他同事确认;告诉他人际交往请你就是真心要你去的.这样就会直面真正的问题,交通的问题.

如果这个人是故意给fake reasons,这个人道德上要被谴责的.
但是注意我们的目标是为了得出好的论证,不过过多聚焦让这人出丑上.

*** Drawing the Wrong Conclusion
定义:得到一个结论但是这个结论不是证据支持的.

这个谬误又叫搞不清楚重点.怎么个搞不清楚重点呢?各种证据都指向某个结论,但是arguer却说得到了另外一个结论.

有时候这种谬误是故意的.比如空方律师指控嫌疑人犯有强奸罪,而无视证据都指向的是强奸是重大罪行.

犯这种谬误有时候是忽略了一些信息,有时候因为微妙的~下意识的或者有偏见.
比如: arguer希望证明一些结论,但是目前的证据还不够证明.
	像: arguer非常关心社会对于女性的不平等待遇,所有性歧视的行为都被拿出来证明应该立法保护女性.
		但是实际可能仅仅说明文化有性歧视,还不足以到立法的程度.

EXAMPLE:
因为我坚信婚姻的神圣性.P
----------
所以,婚姻应该有一男一女.C

这里就是没有说清楚,婚姻的神圣性和婚姻应该是一男一女的关系.
然后像神圣这种事情,根据clarity principle 应该解释神圣的定义.

EXAMPLE:
靠管理员定期抽查来evaluate学校老师的方法是不合适的.P
如果老师非常差的话,是没有有效办法解雇他的.P
----------
老师应该按学期雇佣,再进入市场,然后再雇佣.C

或许是应该按学期雇佣老师,但是这里得不到这个结论.得到是,应该找更好的检查办法,把那些不合格的老师找出来.

wusd: 
公司副总要求员工不允许走消防门上下班.
理由是消防门开着会导致闲杂人等的进入.

得出的结论应该是应该加强消防门的管理,比如规定时间内消防门开着,员工进出需要关门,而不是禁止员工进出消防门.

EXAMPLE:
记者让消息公开,消息公开有助于正义伸张.P
记者同时有让官员诚实,并且暴光他们不当行为.P
----------
仅仅是因为他们没有披露信息来源就送去监狱,是法院对他们的不公.

wusd: 知乎上经常在社会有不公的事情,信息披露不透明的时候.
说平民批评那些公知,然后得出结论平民罪有应得,共知不该被批评.
实际上,应该区分具体的事情.有些公职经过时间检验确实是被无端怒骂,比如李开复当年的言论自由论.
但有些共知确实是做错了事情被骂.
得到的结论应该是,对于批评共知,要更好的社会规范.而不是说批评就是不对的.

记者对于社会的贡献并不能推导出法院对他们的不公.

**** ATTACKING THE FALLACY
当别人犯这种谬误的时候,告诉他这些证据可以得出什么结论.
因为他情感上可能不愿意接受嘛,慢慢罗列下证据和正确的结论.
如果他不管正确的结论,就告诉他原本的结论需要哪些证据.

对同事:你和我有共同喜欢的东西,两人住比一个人住要省,我们可以一起坐车上班.所以我们应该结婚.

*** Using The Wrong Reasons
定义: 用不恰当的理由去支持结论.

Wrong Reasons 和 Conclusion转化成标准形式后看起来是一样的.
但是Wrong Reasons是先有了结论,再用错误的理由去支持结论.因为想要证明特定的结论,又没有找对理由.
而Wrong Conclusion是先有理由,再有结论.因为丢了理由的大意.

为啥会犯这种谬误呢?
arguer已经非常相信结论了,然后就把所有有关的理由都拿出来当证据,认为是恰当的.还有就是找不到恰当的理由.

wusd:
知乎上有人说楼下要装室外雨棚的时候,笑眯眯地,非常有礼貌.
但是当他要把衣帽间改成淋浴室的时候,就一直阻挡他不让他施工.
这里arguer认为自己把衣帽间改成淋浴间是对的,因为他也让楼下装室外雨棚.

wusd:
武林外传中,吕秀才刚分手的时候....

一些程序一些政策,经常被攻击没有达到某某效果,应该被取消.
一个是程序和政策的设计者,本身有时代的限制.
另外一个是程序和政策的目标是理想情况,并不难完全达到.
有些时候程序和政策的设计目地并不是要达到声称的效果.
比如:比如某某法律的存在,有人攻击说不能阻止犯罪的发生.但是可以起到威慑犯罪的作用,减少罪恶的发生,也达到了其目的.

EXAMPLE:
烟草证明造成癌症-P
烟草很贵-P
二手烟对其他人很冒犯-P
----------
特殊人群不该被投放烟草广告-C

这个得出的结论是不应该抽烟,得不出投放烟草广告的结论.
虽然结论本身是对的,但是需要其他理由.这个用了错误的理由.

EXAMPLE:
哲学不能解决所有问题-P
哲学家还在处理2500年前Socrates的问题.-P
----------
哲学是浪费时间-C

这里得出的结论只能说哲学很有很有很多问题没有解决,而且不能解决所有问题,并不能得到哲学是浪费时间.
这里已经有结论哲学是浪费时间,然后用了两个理由.但是哲学的目的并不是要解决问题.

wusd:
小时候,家长一看我们玩游戏,上网.就会说你又在浪费时间,玩游戏上网又不解渴又不管饱的,又没钱,又不能提高学期成绩.
也是强行把玩游戏上网添加了目的,要有生产力,和能提高学习成绩.

EXAMPLE:
控强法案的批评者: wrong reasons, 应该说空枪会和一些更重大原则起冲突,比如:民主?
	控抢不会阻止罪犯用枪犯罪-P
	----------
	没有理由去通过空枪-C
空枪法案的支持者:
	尽管空枪对于控制犯罪影响有限.
	但是重大犯罪会被严格销售和注册影响.
	可以减少国内的冲突.
	减少激情杀人的数量.
	----------
	尽管有限制,但是荏苒按应该通过空枪.


**** ATTACKING THE FALLACY
用wrong reasons的时候,大部分是conclusion非常对.
这时候你就可以说:你这个结论非常好,非常有意思,但是好像不是因为你给的理由.
然后再把你认为合适的理由抛出来.

对于程序或政策或活动,给他添加不相关的目标或功能的时候.
要想法设法地提醒他,活动~程序~政策本来就是有限的,这样有可能阻止arguer犯这种错误.
如果他坚持的话,就把他附加的不相关的目标或功能给他讲清楚来,让他知道自己在犯错误.

** Fallacies of Irrelevant Appeal
靠不当权威,大多数人的意见,武力或威胁,个人利益,操纵这个人感激~态度~偏见.
这些都是没有提供实质性的证据去支持结论,都是不相干的.

*** Appeal to Irrelevant Authority
Definition:靠权威去支持自己的立场,要么是非该领域的权威,要么是未认证的权威,要么是有偏见的权威.

怎么样才能称得上是一个权威?
1. 专业要对口,而且还要足够的能力在这方面发表出正确的意见
2. 要没有偏见,并且没有个人利益的冲突.
wusd: 很多上其他课程的老师,声称新概念已经过时了.

靠该领域权威去支持自己的观点是非常好的方法.
但是当这个权威违反了CriticalThinking的原则,仍然是fallacious.
wusd: Sharleen老师举得那个老师在证明自己的观点的时候,这个老师本身在教育上小有成就,可以认为是一个权威.
但是他证明自己论点正确的时候,并没有用论证的方式,而是操纵大家的情感,大家害怕被人认为什么都不懂.

诉诸不当权威最可能出现的情况是跨领域,一个著名的受人尊重的人很有可能乱入其他的领域.
比如: 文体明星代言汽车消音器~除草剂;生物学家支持宗教的断言;政治家视为婚姻和家庭专家.
wusd: 经济学家王福重,农民懒惰愚昧不值得同情.

没有认证过的专家也不该被拿来支撑自己的观点.
wusd:佳洁士的广告,穿着白大褂的人士,做的那些牙龈实验. 未经证实的小报消息,无论是xx明星出轨了,政府要下达xx禁令了.

还有一些涉及到个人利益的权威,虽然说有足够的技能,专业也足够的对口.对其观点仍然是质疑的态度.
wusd: 有些老师声称新概念已经过时了.

总结下: 能力要够(没跨领域), 要认证的, 没有偏见的(利益相关的)

EXAMPLE: 
因为一些未认证的来源说政府要对50%以上的水污染负责.P
水污染是道德上错误的.ImplicitP
所以,政府错误地污染了国家的水供应.C

对于美国政府来说可能是这样的,但是其消息来自于未经认证的来源,无法判断消息的真假,所以应该是不予采纳.
除非能验证消息来源.
wusd: 但是有些消息虽然没有出处,也无法验证来源.需要衡量按照这些消息做事的利弊,如果利大于弊,还是应该按这样去做.
比如:口罩期间,传出来马上要丰城的消息,大家蜂拥出去屯粮食.

EXAMPLE:
我认为我们应该接受新的课程计划.
因为这些课程计划被学校理事会一直统一的.
这些人一直负责学校的运转,一定同样指导什么课程计划最好.

跨领域朗,学校理事会更多负责财务和人士组织的,而课程教学更多的下发给了下面的学院.专业不对口.
wusd: 程序员被人叫去修电脑.或者程序员在修电脑上面指导江山.

EXAMPLE:
议员,如果你认为FBI涉及到违法活动,为什么不让局的头和他的成员在法庭上作证?

大多数情况,是应该局头来调查的,因为是相关的权威,但是这些事情可能涉及到局本身,所以有利害相关.
wusd: 大明王朝1566,浙江官员涉及到挥涕盐田的事情,小阁老严世蕃的主张是让他的手下颜貌请去查.
实际上惠帝盐田就是小阁老自己指挥的,本身就是利害相关的.

**** ATTACKING THE FALLACY
如果是未认证的权威,就问其要认证.
如果没认证的,就视为和claim无关好了.
如果经过认证的,就再具体看是否符合其他的标准.没有跨专业领域,是否利益相关,其他的推理标准.
wusd: 他说专家说,喝枸杞有助于增强心肺功能.
	那么我们就可以问下,是哪位专家的.
	如果他说,反正就是专家,那么直接无视掉就好了.
	如果他说了,是张文宏医生.我们一看他是病毒专家,并不是营养学专家,就可以对其论据存疑了.
	然后再看其言论是否有论证,是否符合论证的标准.

要慎重地判断这个权威是有偏见,因为经常会编造出一个权威专家是有偏见的,这样会阻碍真相的发现.
如果你怀疑一个专家有利益上的冲突,你应该指出来这种存在的可能,而不是直接指出说这个专家要么是偏见,要么是不诚实.

遇到这种跨领域权威就很好办.
直接问: 你会用姚明去支持健将的内裤吗?
如果他说,两者不一样.那么你就问两者到底哪里不一样.

最后,不要害怕名人名头大.他们确实在自身领域非常优秀,但也仅限于自身领域.

*** Appeal to Common Opinion

*** Appeal to Force To Threat

*** Appeal to Tradition

*** Appeal to Self-Interest

*** Manipulation of Emotions
