* L74 Out of the limelight
** DONE 单词造句
CLOSED: [2023-09-06 Wed 21:48]
limelight n. stay out of the limelight
1. Cristal Liu used to stay out of the limelight.
2. You needn't have stayed out the limelight.
3. She makes a big decision and stays out of the limelight for the rest of her life.
4. It's no use pretending that you haven't stayed out of the limelight.
5. He's always thinking about staying out of the limelight.
precaution n. take precaution
1. On the last day of the year, everyone was instructed to take great precaution.
2. "Take precaution!", the security shouted at the girl.
3. The foreigner refused to take precaution in Shanghai.
4. People in Disney land have to take every precaution before entering it.
5. Chinese were not allowed to take great precaution in USA.
fan n. sb. is a big/huge fan of a.
1. He's such a big fan of the truth that he refused to tell lies to people.
2. I'm a huge fan of your cooking, darlin.
3. Would you mind my following around you? I'm a huge fan of your movie. 
4. The police which is trying to keep order is a fan of the Greenwood Boys.
5. He's such a big fan of the actoress that he keep following her around all morning.
shady adj.
1. I have been reading aloud in that shady spot every afternoon for a long time.
2. A man in the shady spot is waving to us.
3. I had to take a rest in that shady spot, for I'm too exhausted.
4. They were hold the meeting in the shady spot.
5. He is busy looking for a insect in that shady spot.
sheriff n.
1. The sheriff continued to shout at the boy.
2. It's the sheriff who makes mistakes, not you.
3. The sheriff will arrest him as soon as he arrives at the airport.
4. The sheriff shouldn't have arrested the girl who has a clear conscience.
5. The sheriff return the stolen car to the young mother.
notice n.v. on such short notice
1. There is a notice sticking to the wall.
2. Thank you for your helping on such short notice.
3. We can't have done homework on such short notice.
4. It was you who put the notice on the wall, not your student.
5. It is said that the notice was put by a student who plays truent from school every day.
sneer n.v. with a sneer/ sneer at sb.
1. "You needn't have said that.", his wife said with a sneer.
2. The police double check his parcel with a sneer.
3. "It's you who are responsible for the whole thing, not me", she said with a sneer.
4. Don't sneer at me.
5. The officer sneered at the man who was bursting into tears.

** 反复听电影片段
** DONE Pattern Drill 写+读
CLOSED: [2023-09-06 Wed 21:48]
- 
	 1T: wearing your glasses -hate
	 S1: Why aren't you wearing your glasses?
	 S2: Because I hate wearing them.
	+ polishing the car--don't like
		Why aren't you polishing the car?
		Because I don't like polishing it.
	+ washing the dishes -- dislike
		Why aren't you washing the dishes?
		Because I dislike wasking them.
	+ talking to Frank -- hate
		Why aren't you talking to Frank?
		Because I hate talking to him.
	+ watching football--don't enjoy
		Why aren't you watching football?
		Because I don't enjoy watching it.
- 
	 2T: wears glasses
	 S1: John always wears glasses.
	 S2: Are you sure? He isn't wearing any today.
	+ takes a taxi
		John always takes a taxi.
		Are you sure? He isn't taking any today.
	+ catches a bus
		John always catches a bus.
		Are you sure? He isn't catching any today.
	+ smokes a cigar
		John always smokes a cigar.
		Are you sure? He isn't smoking any today.
	+ wear gloves
		John always wears gloves.
		Are you sure? He isn't wearing any today.
- 
	 3T: pen - No/Yes
	 S1: I'm using your pen. Do you mind?
	 S2: No, it's all right. I don't need it just now.
	 Yes, I do. I want to use it myself.
	+ computer - No/Yes
		I'm using your computer. Do you mind?
		Yes, I do. I want to use it myself.
	+ dictionary - Yes/No
		I'm using your dictionary. Do you mind?
		No, it's all right. I don't need it just now.
	+ ladder - Yes/No
		I'm using your ladder. Do you mind?
		Yes, I do. I want to use it myself.
	+ mirror - No/Yes
		I'm using your mirror. Do you mind?
		No, it's all right. I don't need it just now.
- 
	 4T: she's doing - see
	 S1: What's she doing?
	 S2: I don't know what she's doing. I can't see anything.
	+ he's saying --hear
		What's he saying?
		I don't know what he's saying. I can't hear anything.
	+ she's cooking --smell
		What's she cooking?
		I don't know what she's cooking. I can't smell anything.
	+ they're making --see
		What're they making.
		I don't know what they're making. I can't see anything.
	+ we're eating --taste
		What're we eating?
		I don't know what we're eating. I can't taste anything.
	 
** DONE 给自己讲解
CLOSED: [2023-09-06 Wed 21:50]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-06 Wed 22:06]
a party of
1. A party of children who played truant from school hitchhiked to Paris last night.
2. A part of women gather round and sang the same song over and over again.
3. In the meantime, a party of fans are meeting the group of singer at the station.
4. I was disappointed to learn that a party of student were arrested by the local authorities.
5. A party of student have difficulty in finishing homework.
why don't we
1. Why don't we turn our attention to the cat?
2. Why don't we go to disney land once more.
3. Why don't we stay out of limelight?
4. Why don't we connect the microphone to the big Ben?
5. Why don't we make the plan official?
carry sth. to sp.
1. The boy who played truant from school was carried to the border.
2. You're responsible for carrying the paper to office.
3. He refused to carry his homework to school.
4. He should have carried his homework to school.
5. The official should have carried the postcards to office.
make oneself comfortable
1. Please come in and make yourself comfortable.
2. Why don't we make ourselves comfortable first?
3. Why don't we set up the tent and make ourselves comfortable?
4. It's difficult for her to make herself comfortable in the hotel.
5. The landlord is making himself comfortable.
don't be too hard on us 
1. You shouldn't have been too hard on your child.
2. Don't be too hard on yourself, you aren't responsible for the mistake.
3. Don't be too hard on her, for she's very young.
4. Don't be too hard on us, you should turn attention to them.
5. If you hadn't been too hard on your child, you wouldn't have argued with him.
get out of here
1. Let us know when we can get out of here.
2. Would you mind my getting out of here?
3. Get out of here, for your safety.
4. The cow is charging at you, get out of here.
5. Get out of here. Ross yelled at Rachel.
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion

* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
