* L75 SOS
** DONE 单词造句
CLOSED: [2023-09-08 Fri 22:38]
thick adj.
1. We should take precautions when we walk on the ice, for it's not enough thick.
2. If the fog had not been so thick, we would have arrived in Beijing.
3. I was always being ordered to clean thick snow in our yard.
4. My grandfather instructed me to clean thick snow in the field.
5. I needn't have refused to clean thick snow.
signal n. send a signal
1. I am going to show you how to send a signal.
2. I will have sent a signal before the fire was put out.
3. I'm fairly confident that I am able to send a signal.
4. A party of film actors send a signal to ask for help in the thick fog.
5. He is sending a signal with a sneer.
stamp v. stamp out the fire
1. As soon as he had stamped out of the house, it began to rain.
2. We managed to stamp out of the fire on such short notice.
3. I saw you stamping out the fire.
4. We will have difficulty in stamping out the fire.
5. The boy was disappointed to learn that the fire had been stamped out.
helicopter n.
1. Following in his father's footsteps, he drives a helicopter called Bluebird.
2. Having been rescued, the young woman and her boyfriend both bursted into tears in the helicopter.
3. There is a parcel of daimond in the helicopter.
4. He has spent two years in driving a helicopter.
5. Mary turned her attention to the helicopter for her safety.
scene n. arrive on the scene
1. The sheriff who arrived on the scene managed to explain the notice to a party of actors.
2. The thief noticed that a police had arrived on the scene.
3. The police who arrived on the scene named the event X.
4. We will have arrived on the scene before the police come.
5. The police who first arrived on the scene will be responsible for the event.
survivor n.
1. The survivor needn't haven stayed out of the limelight.
2. If the survivor had stayed out of the limelight, it wouldn't have happened.
3. The newspapermen keep talking to survivor over and over again.
4. The survivor double checked whether his child was killed.
5. Even though house was burnt down, the survivor wasn't hurted fortunatly.
** DONE 反复听电影片段
CLOSED: [2023-09-09 Sat 10:14]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-09 Sat 10:21]
1. 
		1T: enter for a race - win
		S1: Did he enter for a race?
		S2: He entered for several and he even won one!
	 + write a story - publish/sell
		 Did he write a story?
		 He writed several stories and he even published one!
	 + see a thief - catch/arrest
		 Did he see a thief?
		 He saw several thieves and he even caught one!
	 + design a boat - build/fly
		 Did he design a boat?
		 He designed several boats and he even built one.
	 + take an exam - get through/pass
		 Did he take an exam?
		 He taked several exams and he even got through one.
2. 
	 2T: punish that boy
	 S1: Why did you punish that boy yesterday?
	 S2: I didn't punish him. No one did.
	 + arrest that woman
		 Why did you arrest that woman yesterday?
		 I didn't arrest her. No one did.
	 + buy that house
		 Why did you buy that house yesterday?
		 I didn't buy it. No one did.
	 + invite those people
		 Why did you invite those people yesterday?
		 I didn't invite them. No one did.
	 + do that job
		 Why did you do that job yesterday?
		 I didn't do it. No one did.
3. 
	 3T: hot - climbing
	 S1: You look hot. What've you been doing?
	 S2: I went climbing this morning and got very hot.
	 + thirsty - running
		 You look thirsty. What've you been doing?
		 I went running this morning and got very hot.
	 + dirty - riding
		 You look dirty. What've you been doing?
		 I went riding this morning and got very dirty.
	 + tired - swimming
		 You look tired. What've you been doing?
		 I went swimming this morning and got very tired.
	 + angry - shopping
		 You look angry. What've you been doing?
		 I went shopping this morning and got very angry.
4. 
	 4T: thank your host - politely
	 S1: Did you remember to thank your host?
	 S2: Yes. I thanked him as politely as I could.
	 + send my message - quickly
		 Did you remember to send my message?
		 Yes. I sent your message as quickly as I could.
	 + wrap up the parcel - carefully
		 Did you remember to wrap up the parcel?
		 Yes. I wrapped up it as carefully as I could.
	 + pack up the parcel - carefully
		 Did you remember to pack up the parcel?
		 Yes. I packed up it as carefully as I could.
	 + dust up your room - well
		 Did you remember to dust up your room?
		 Yes. I dusted up it as well as I could.
** DONE 给自己讲解
CLOSED: [2023-09-08 Fri 22:57]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-08 Fri 22:37]
fly off course
1. No matter what happens, the pilot refused to fly off course.
2. It's you who are responsible for flying off course, not him.
3. He was disappointed to learn that he had flew off course.
4. Would you mind pilot's flying off course.
5. If the plane hadn't flew off course, nobody would have been killed.
cover sb./sth/ with a.
1. My mom insisted on covering me with a blanket.
2. Let's suppose that you're covered with a blanket.
3. If you had covered yours wit a blanket, you wouldn't have got cold.
4. He managed to cover the tiger with a blanket.
5. You should have cover yourself with a blanket last night.
get adj.
1. He got very angry and turned round over and over again.
2. I wish that I get better.
3. It's getting cold.
4. The situation gets worse in China.
5. Let's suppose that she gets angry.
It was not long before...
1. It was not long before he was dressed in dark glasses.
2. It was not long before the captain set off.
3. It was not long before he made a speech.
4. It was not long before he spoke English fluently.
5. It was not long before he got hungry.
** DONE 跟读至背诵
CLOSED: [2023-09-09 Sat 10:14]
** DONE Ask me if 写+读
CLOSED: [2023-09-09 Sat 10:26]
1. A light passenger plane flew off course. What kind of
	 What kind of plane flew off course?
2. It crashed in the mountains.(Where)
	 Where did it crash?
3. Its pilot was killed.(Who)
	 Who was killed?
4. There were three passengers.(How many)
	 How many passengers were there?
5. The young woman and her two baby daughters were unhurt.(Who)
	 Who were unhurt?
6. It was the middle of winter.(What time of year)
	 What time of year was it?
7. Snow lay thick on the ground.(What)
	 What lay thick on the ground?
8. The nearest village was miles away.(How far)
	 How was the nearest village?
9. She turned a suitcase into a bed.(What)
	 What did she turn into a bed?
10. She put the children inside it.(Where)
		Where did she put the children?
** DONE 摘要写作
CLOSED: [2023-09-09 Sat 10:43]
A light passenger plane crashed in the mountains,
	but the only passengers, a woman and her two baby daughters, were not hurt.
It was Mid winter and extremely cold,
	so she put children in a case, covered them with clothes
		and kept close to them all night.
When planes passed overhead next morning, she stamped out 'SOS' in the snow.
This was seen by a pilot, who sent the message to nearest village,
	and the passengers were soon rescued by a helicopter.

When a plane crashed in the mountains,
	the only passengers, a young woman and her two baby daughters, were not hurt.
However, it was Mid-winter and extremely cold.
After putting her children in a case and covered them with clothes,
	the woman kept close to them all night.
On hearing the planes early next morning, the woman stamped out 'SOS' in the snow,
	which was seen by a pilot.
Message was sent and they were soon rescued by a helicopter.

** DONE tell the story 口语
CLOSED: [2023-09-09 Sat 10:46]
** Topics for discussion
* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
