#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 77 A successful operation

#+begin_verse
Did the doctors find out how the woman died?

The mummy of an Egyptian woman who died in 800 B.C. has just had an operation.
The mummy is that of Shepenmut who was once a singer in the Temple of Thebes.
As there were strange marks on the X-ray plates taken of the mummy,
	doctors have been trying to find out whether the woman died of a rare disease.
The only way to do this was to operate.
The operation, which lasted for over four hours,
		proved to be very difficult
	because of the hard resin which covered the skin.
The doctors removed a section of the mummy and sent it to a laboratory.
They also found something which the X-ray plates did not show:
	a small wax figure of the god Duamutef.
This god which has the head of a cow was normally placed inside a mummy.
The doctors have not yet decided how the woman died.
They feared that the mummy would fall to pieces when they cut it open,
	but fortunately this has not happened.
The mummy successfully survived the operation.
#+end_verse


** words
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple [ˈtemp(ə)l] n.庙
mark [mɑrk] n.斑点
plate [pleɪt] n.底片
disease [dɪˈziz] n.疾病
last [læst] v.持续
prove [pruv] v.显示出
resin [ˈrezɪn] n.树脂
skin [skɪn] n.皮,皮肤
section [ˈsekʃ(ə)n] n.切片
figure [ˈfɪɡjər] n.(人的)体形; 人像
normally [ˈnɔrm(ə)li] adv.通常地
survive [sərˈvaɪv] v.幸免于
