#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 78 The last one?
#+begin_verse
For how long did the writer give up smoking?

After reading an article entitled 'Cigarette Smoking and Your Health'
	I lit a cigarette to calm my nerves.
I smoked with concentration and pleasure
	as I was sure that this would be my last cigarette.
For a whole week I did not smoke at all
	and during this time, my wife suffered terribly.
I had all the usual symptoms of someone giving up smoking:
	a bad temper and an enormous appetite.
My friends kept on offering me cigarettes and cigars.
They made no effort to hide their amusement whenever I produced a packet of sweets from my pocket.
After seven days of this I went to a party.
Everybody around me was smoking and I felt extremely uncomfortable.
When my old friend Brian urged me to accept a cigarette, it was more than I could bear.
I took one guiltily, lit it and smoked with satisfaction.
My wife was delighted that things had returned to normal once more.
Anyway, as Brian pointed out, it is the easiest thing in the world to give up smoking.
He himself has done it lots of times!
#+end_verse

** words
entitle [ɪnˈtaɪt(ə)l] v.以...为名
calm [kɑm] v.使镇静
nerve [nɜrv] n.神经
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer [ˈsʌfər] v.受苦
symptom [ˈsɪmptəm] n.症状
temper [ˈtempər] n.脾气
appetite [ˈæpəˌtaɪt] n.胃口
produce [prəˈdus] v.拿出
urge [ɜrdʒ] v.怂恿
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted [dɪˈlaɪtəd] adj.欣喜的
