#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 79 By air 

#+begin_verse
Why did the plane turn back?

I used to travel by air a great deal when I was a boy.
My parents used to live in South America
	and I used to fly there from Europe in the holidays.
A flight attendant would take charge of me
	and I never had an unpleasant experience.
I am used to travelling by air
	and only on one occasion have I ever felt frightened.
After taking off, we were flying low over the city and slowly gaining height,
	when the plane suddenly turned round and flew back to the airport.
While we were waiting to land,
	a flight attendant told us to keep calm and to get off the plane quietly
		as soon as it had touched down.
Everybody on board was worried
	and we were curious to find out what had happened.
Later we learnt that there was a very important person on board.
The police had been told that a bomb had been planted on the plane.
After we had landed, the plane was searched thoroughly.
Fortunately, nothing was found
	and five hours later we were able to take off again.
#+end_verse

** words
parent [ˈperənt] n.父母亲
flight attendant [flaɪt-əˈtendənt] 空中乘务员
frightened [ˈfraɪt(ə)nd] adj.害怕,担惊
curious [ˈkjʊriəs] adj.急于了解,好奇的
bomb [bɑm] n.炸弹
plant [plænt] v.安放

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion

