#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 81 Escape
#+begin_verse
Why did the prisoner attack the driver?

When he had killed the guard,
	the prisoner of war quickly dragged him into the bushes.
Working rapidly in the darkness,
	he soon changed into the dead man's clothes.
Now, dressed in a blue uniform and with a rifle over his shoulder,
	the prisoner marched boldly up and down in front of the camp.
He could hear shouting in the camp itself.
Lights were blazing and men were running here and there:
	they had just discovered that a prisoner had escaped.
At that moment, a large black car with four officers inside it, stopped at the camp gates.
The officers got out
	and the prisoner stood to attention and saluted
	as they passed.
When they had gone,
	the driver of the car came towards him.
The man obviously wanted to talk.
He was rather elderly with grey hair and clear blue eyes.
The prisoner felt sorry for him,
	but there was nothing else he could do.
As the man came near,
	the prisoner knocked him to the ground with a sharp blow.
Then, jumping into the car,
	he drove off as quickly as he could.
#+end_verse

** words
prisoner [ˈprɪz(ə)nər] n.囚犯
bush [bʊʃ] n.灌木丛
rapidly ['ræpɪdli] adv.迅速地
uniform [ˈjunɪˌfɔrm] n.制服
rifle [ˈraɪf(ə)l] n.来福枪,步枪
shoulder [ˈʃoʊldər] n.肩
march [mɑrtʃ] v.行进
boldly ['bəʊldli] adv.大胆地
blaze [bleɪz] v.闪耀
salute [səˈlut] v.行礼
elderly [ˈeldərli] adj.上了年纪的
grey [ɡreɪ] adj.灰白的
sharp [ʃɑrp] adj.猛烈的
blow [bloʊ] n.打击

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
