#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 83 After the elections

#+begin_verse
Why did Patrick keep on asking the same question?

The former Prime Minister, Mr. Wentworth Lane, was defeated in the recent elections.
He is now retiring from political life and has gone abroad.
My friend, Patrick, has always been a fanatical opponent of Mr. Lane's Radical Progressive Party.
After the elections, Patrick went to the former Prime Minister's house.
When he asked if Mr. Lane lived there,
	the policeman *on duty* told him that since his defeat, the ex-Prime Minister had gone abroad.
*On the following day*, Patrick went to the house again.
The same policeman was just walking slowly past the entrance,
	when Patrick asked the same question.
Though a little suspicious this time, the policeman gave him the same answer.
The day after, Patrick went to the house once more and asked exactly the same question.
This time, the policeman lost his temper.
'I told you yesterday and the day before yesterday,' he shouted,
'Mr. Lane was defeated in the elections.
He has retired from political life and gone to live abroad!'
'I know,' answered Patrick, 'I *love to hear* you say it!'
#+end_verse

** words
election [ɪˈlekʃ(ə)n] n.选举
former [ˈfɔrmər] adj.从前的
defeat [dɪˈfit] v.打败
fanatical [fəˈnætɪk(ə)l] adj.狂热的
opponent [əˈpoʊnənt] n.反对者,对手
radical [ˈrædɪk(ə)l] adj.激进的
progressive [prəˈɡresɪv] adj.进步的
ex- [eks] prefix 前...
suspicious [səˈspɪʃəs] adj.怀疑的

** DONE 单词造句
CLOSED: [2023-09-23 Sat 21:17]
election n.win the election
1. If he was defeated in the election, I would offer 3000 dollars.
2. He used to win elections every time, but he was defeated this time.
3. The former president managed to win the election.
4. It is well known that she should have won the election.
5. Let's suppose that you won the election.
former adj.
1. The former president is still a shining example to us.
2. The former president has caught a peculiar fish out at sea.
3. The former president made every effort to win the election in any way.
4. The former president laughed at the workers who were striking.
5. The former president is fanatical about learing the culture of China.
defeat v.
1. If he hadn't been defeated in the finally game, he would have been the first champion of China.
2. If you defeat him in this game, we will offer you a large sum of money.
3. He claim to have defeated his opponent in the war.
4. He discovered that the player hadn't defeated his opponent/rival in the game.
5. He has defeated his rival with a sharp blow.
fanatical adj.be fanatical about sth./doing sth.
1. Joey's girl friend is fanatical about Chinese Kungfu.
2. Why are people so fanatical about TF boys?
3. The girl who played truent from school is a fanatical fan of TFBoys.
4. He is fanatical about playing basketball of all time.
5. The businessmen are always fanatical about making a profit in any way.
opponent n.
1. He discovered that his opponent had been defeated in the finally election.
2. He succeeded in knocking his opponent to the ground with a sharp blow.
3. His opponent was moving so rapidly that he couldn't turn attention to him.
4. He has to stand to attention, when his opponent got off.
5. He is not only my opponent, but a shining example to me as well.
radical adj.
1. He must have been shocked by his son's radical actions.
2. The doctors on duty were shocked by his radical views.
3. I should have made a radical change in my way of learning English.
4. It is known that making a radical change is usually dangerous.
5. This radical change was found to be right.
ex- prefix
1. My ex-girlfriend changed into the suit which I gave her last year.
2. My ex-boyfriend is wandering around the street.
3. She suddenly knocked her ex-boyfriend to the ground with a sharp blow.
4. She discovered that her ex-boyfriend had got married soon.
5. She urged her ex-husband to get marry to her once more.
suspicious adj.
1. He looked suspicious, for he walked up and down in front of the camp.
2. The policewoman told me that if I see anything suspicious, just call her.
3. The girl claim to have at times seen a suspicious man.
4. Seamen and fishermen often claim to have seen suspicious monsters.
5. The girl is used to meeting suspicious man.
** DONE 反复听电影片段
CLOSED: [2023-09-24 Sun 21:09]
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-23 Sat 21:24]
on duty
1. The policewoman on duty is asking me for a lift.
2. We don't allow you to drink alcohol on duty.
3. The policeman is used to handling accident on duty.
4. The flight attendant on duty took charge of this little baby.
5. The flight attendant on duty often loses her temper for some reasons.
on the following day
1. On the following day, she urged her brother to do housework.
2. On the following day, she had the nerve to take elevator.
3. On the following day, I was entitled to access the database system.
4. On the following day, I gave up smoking.
5. On the following day, the mummy will be cut open.
love to do sth.
1. I love to kiss my wife.
2. She doesn't love to have an operation.
3. The boy loves to stamp out the fire.
4. The boy loves to carry books to the courtyard.
5. My cat loves to charge at me, when I get home.
** DONE 跟读至背诵
CLOSED: [2023-09-24 Sun 20:38]
** DONE Ask me if 写+读
CLOSED: [2023-09-24 Sun 21:11]
1. Mr. Lane was Prime Minister. What/Who
	 What did Mr. Lane do?
	 Who was Prime Minister?
2. He was leader of the Radical Progressive Party. Which party/Who
	 Which party was he leader of?
	 Who was leader of the Radical Progressive Party?
3. He was defeated in the recent elections. When/Who
	 When was he defeated?
	 Who was defeated in the recent elections?
4. He's retiring from political life. Who
	 Who's retiring from political life?
5. He's gone abroad. Where/Why/Who
	 Where has he gone?
	 Why has he gone abroad?
	 Who's gone abroad?
6. Patrick's always been an opponent of Mr. Lane's party. How long/Who
	 How long has Patrick been an opponent of Mr. Lane's party?
	 Who's always been an opponent of Mr. Lane's party?
7. He went to Mr. Lane's house after the elections. Where/When/Why
	 Where did he go after the elections?
	 When did he go to Mr. Lane's house?
	 Why did he go to Mr. Lane's house after the elctions?
8. A policeman was there on duty. Why
	 Why was a policeman there?
9. Patrick asked the policeman if Mr. Lane lived there. What/Who
	 What did Patrick ask the policeman?
	 Who asked the policeman if Mr. Lane lived there?
** DONE 摘要写作
CLOSED: [2023-09-24 Sun 21:07]
After having been defeated in the recent elections,
	 the formar Prime Minister, Mr. Lane, retiring abroad.
My friend Patrick,
	who has always been a fanatical opponent of Mr. Lane's Radical Progressive Party,
	went to his house house three times
	and asked the policeman on duty whether it was Mr. Lane's house.
When he asked for the third time,
  the angry policeman told him again of Mr. Lane's defeat and retirement.
Patrick said that it was something he loved to hear.

Since being defeated in the recent elections,
	the formar Prime Minister, Mr. Wentwroth, has retired abroad.
As my friend Patrick has always been a fanatical opponent of Mr. Lane's Radical Progressive Party,
	he went to his house three times.
Each time he asked the policeman on duty if it was Mr. Lane's house.
The third time he was told again by the angry policeman of Mr. Lane's defeat and retirement,
	but Patrick said it was something he loved to hear.

** DONE tell the story 口语
CLOSED: [2023-09-24 Sun 21:13]
** Topics for discussion
