#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 83 After the elections

#+begin_verse
Why did Patrick keep on asking the same question?

The former Prime Minister, Mr. Wentworth Lane,
	was defeated in the recent elections.
He is now retiring from political life
	and has gone abroad.
My friend, Patrick, has always been a fanatical opponent of Mr. Lane's Radical Progressive Party.
After the elections, Patrick went to the former Prime Minister's house.
When he asked if Mr. Lane lived there,
	the policeman on duty told him
		that since his defeat, the ex-Prime Minister had gone abroad.
On the following day, Patrick went to the house again.
The same policeman was just walking slowly past the entrance,
	when Patrick asked the same question.
Though a little suspicious this time,
	the policeman gave him the same answer.
The day after, Patrick went to the house once more
	and asked exactly the same question.
This time, the policeman lost his temper.
'I told you yesterday and the day before yesterday,' he shouted,
'Mr. Lane was defeated in the elections.
He has retired from political life
	and gone to live abroad!’
'I know,' answered Patrick,
'but I love to hear you say it!'
#+end_verse

** words
election [ɪˈlekʃ(ə)n] n.选举
former [ˈfɔrmər] adj.从前的
defeat [dɪˈfit] v.打败
fanatical [fəˈnætɪk(ə)l] adj.狂热的
opponent [əˈpoʊnənt] n.反对者,对手
radical [ˈrædɪk(ə)l] adj.激进的
progressive [prəˈɡresɪv] adj.进步的
ex- [eks] prefix 前...
suspicious [səˈspɪʃəs] adj.怀疑的

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
