#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 84 On strike

#+begin_verse
Who will be driving the buses next week?

Busmen have decided to *go on strike* next week.
The strike *is due to* begin on Tuesday.
No one knows how long it will last.
*The busmen have stated*
	that the strike will continue
		until general *agreement is reached about* pay and working conditions.
Most people believe
	that the strike will last for at least a week.
Many owners of private cars are going to offer 'free rides' to people on their way to work.
This will *relieve pressure* on the trains *to some extent*.
Meanwhile, a number of university students have *volunteered to drive* buses
	while the strike lasts.
All the students are expert drivers,
	but before they drive any of the buses,
		they will have to *pass a special test*.
The students are going to *take the test* in two days' time.
Even so, people are going to find it difficult to get to work.
But so far, the public has *expressed its gratitude to* the students in letters to the Press.
*Only one or two people have objected*
	that the students will drive too fast!
#+end_verse

** words
strike [straɪk] n.罢工
busman ['bʌsmən] n.公交车司机
state [steɪt]	v.正式提出,宣布
agreement [əˈɡrimənt] n.协议
relieve [rɪˈliv] v.减轻
pressure [ˈpreʃər] n.压力,麻烦
extent [ɪkˈstent] n.程度
volunteer [ˌvɑlənˈtɪr] v.自动提出,自愿
gratitude [ˈɡrætɪˌtud] n.感激
Press [pres] n.新闻界
object [ɑbˈdʒekt] v.不赞成,反对

** DONE 单词造句
CLOSED: [2023-09-24 Sun 22:50]
strike n. go on strike
1. Workers are not allowed to go on strike in this country.
2. The drivers in the city love to go on strike.
3. On the following day, all the workers in the city went on strike.
4. The firemen on duty are going on strike for some reasons.
5. It is known that the teachers in the district have gone on strike for a month.
busman n. bus driver
1. Though a little suspicious, the bus driver gave the passenger the ticket.
2. The bus driver was found to be a gangster.
3. The bus driver has at times lost his temper while driving bus.
4. The bus driver discovered that the passenger was Prime Minister.
5. The bus driver knocked the policeman to the groud by a sharp blow.
state v. sb. have stated that + ...
1. The girl stated that she recognized the voice of her father's car enginee.
2. My bossed has stated that we will have a better salary as soon as we pass the exam.
3. My leader has stated that the program is full of mistakes.
4. He stated that his boss refused to put forward the plan.
5. He stated that he had planted a bom at the airport.
agreement n. agreement is reached about sth.  reach an agreement
1. The general agreement is reached about doing housework by my wife and me.
2. We are used to failing to reach an agreement.
3. We used to reach an agreement.
4. We needn't have reached an agreement.
5. He was curious to find out that his wife and his daughter reached a series of agreements.
relieve v. sb. be relieved to hear that + ...  relieve pressure
1. I was relieved to hear that Mr. Leo made a profit last year.
2. I was relieved to hear that my son had gone to college.
3. I was relieved to hear that the luxury was on display in the exhibition.
4. I was relieved to hear that the lady and her baby had been rescued in the mountains.
5. I was relieved to hear that the flight attandant will take charge of my baby.
pressure n. under a lot of pressure  relieve pressure
1. The kid is under a lot of pressure, for they are instructed to study day and night.
2. He was under so much pressure that I felt frightened. 
3. Don't be hard on us, we are under a lot of pressure.
4. He is always under a lot of pressure on board.
5. His parents make every effort to relive his pressure, even allow him to smoke.
extend  n. to some extend
1. To some extend, you're responsible for her failure.
2. To some extend, that's a splendid idea.
3. To some extend, I was disappointed to learn that I failed the test.
4. To some extend, I have followed in my father's footsteps.
5. To some extend, she has difficulty in swimming in public places.
volunteer v.n. volunteer to do sth.
1. I need a volunteer to save the soldier's life.
2. She used to volunteer to keep order in her twenties.
3. I volunteered to teach these volunteers English.
4. I intend to volunteer to do the dishes.
5. She shouldn't have volunteered to keep order.
gratitude n. expressed sb.'s gratitude to sb.
1. I would like to express my gratitude to my relatives who ever help me.
2. You should express your gratitude to anyone who help you.
3. The moment she help me, I will express my gratitude to her.
4. The kid was ordered to express her gratitude to Mr. Leo.
5. We should have expressed our gratitude to Mr. Leo.
press n.v.
1. He is sending the news to the press.
2. If you don't press the button, the radio won't start.
3. Leo was defeated in the recent elections and I read about it in the press.
4. The poor guy read about his wife's cheating in the press.
5. He discovered that his firm had ran into serious trouble in the press.
object v. objection n. sb. have objected that + ...  object to sth./sb.
1. He objected that student study at night.
2. I objected that he is expert at driving buses.
3. She objected to Prime Minister and rushed up to him.
4. We need objecting to prepared dishes.
5. He insisted on objecting to prepared dishes.
** DONE 反复听电影片段
CLOSED: [2023-09-25 Mon 20:22]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-25 Mon 20:16]
1. 
		1t: away - a month
		s1: How long will they be away?
		s2: They'll be away for a month.
	 - in Japan - about two weeks
		 How long will they be in Japan?
		 They'll be in Japan for about two weeks.
	 - by the sea - a fortnight
		 How long will they be by the sea?
		 They'll be by the sea for a fortnight.
	 - at the meeting - two hours
		 How long will they be at the meeting?
		 They'll be at the meeting for two hours.
	 - at the seaside - quite a while
		 How long will they be at the seaside?
		 They'll be at the seaside for quite a while.
2. 
		2t: climb the mountain-three weeks
		s1: How long will they take to climb the mountain?
		s2: They'll climb it in three weeks.
	 - decorate the house - three days
		 How long will they take to decorate the house?
		 They'll decorate it in three days.
	 - sail the Atlantic - about a month
		 How long will they take to sail the Atlantic?
		 They'll sail it in about a month.
	 - reply to the letter - a week
		 How long will they take to reply to the letter?
		 They'll reply to it in a week.
	 - mend the radio - about two days
		 How long will they take to mend the radio?
		 They'll mend it in about two days.
3. 
		3t: see the film
		s1: We're going to see the film. Do you want to come?
		s2: No thanks. I'll go and see it later.
	 - visit Mary
		 We're going to visit Mary. Do you want to come?
		 No thanks. I'll go and see it later.
	 - see the exhibition
		 We're going to see the exhibition. Do you want to come?
		 No thanks. I'll go and see it later.
	 - admire the view
		 We're going to admire the view. Do you want to come?
		 No thanks. I'll go and see it later.
	 - speak to the manager
		 We're going to speak to the manager. Do you want to come?
		 No thanks. I'll go and see it later.
4. 
		4t: go into hospital
		s1: He's going into hospital some time.
		s2: Is he? Let me know when he goes.
	 - set out for - the North Pole
		 He's setting out for the North Pole.
		 Is he? Let me know when he sets.
	 - come back from - South America
		 He's coming back from South America.
		 Is he? Let me know when he comes.
	 - return from - his holiday
		 He's returning from his holiday.
		 Is he? Let me know when he returns.
	 - arrive - in this country
		 He's arriving in this country.
		 Is he? Let me know when he arrives.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-24 Sun 22:55]
be due to do sth.
1. They are due to catch a flight on the following day.
2. They are due to have a long walk at the other side of West Lake.
3. They are due to watch a musical in two hours.
4. They are due to settle down in hometown.
5. We are due to stick to the plan.
pass/take the test
1. I should have taken the test.
2. I regretted taking the test.
3. I was relieved to hear that I passed the test.
4. He insisted on taking the test over and over again, even though he has already passed the test.
5. Students always inquire about how to pass the test.
** DONE 跟读至背诵
CLOSED: [2023-09-25 Mon 20:00]
** DONE Ask me if 写+读
CLOSED: [2023-09-25 Mon 20:00]
1. Busmen have decided to go on strike next week. When/Who
	 When have busmen decided to go on strike?
	 Who have decided to go on strike next week?
2. The strike will begin on Tuesday. Which day
	 Which day will the strike begin on?
3. Most people believe the strike will last for at least a week. How long
	 How long do most people belive the strike will last?
4. The busmen want more pay. What
	 What do the busmen want?
5. They also want better working conditions. What else
	 What else do the busmen want?
6. The strike will continue until agreement is reached. How long
	 How long will the strike continue?
7. Owners of private cars are going to offer 'free rides'. What
	 What are owners of private cars going to offer?
8. People will still get to work. Where
	 Where will people still get to?
** DONE 摘要写作
CLOSED: [2023-09-25 Mon 20:36]
The busmen's strike, which begins on Tuesday,
	may last for a week.
Because of this,
	 cars owners have offered to give rides to people going to work.
University students, too, have volunteered to drive the buses too
	but they will have to pass a special test.
Though it will be difficult to get to work, the public is grateful to the students.
Only one or two people have objected that the students will drive too fast.

Because the busmen's strike which begins on Tuesday may last a week,
	car owners have offered to give rides to people going to work.
University students who have volunteered to drive the buses will have to pass a special test.
Despite the fact that it will be difficult to get to work,
	the public is grateful to the students,
	except for one or two have objected that the students will dirve to fast
** DONE tell the story 口语
CLOSED: [2023-09-25 Mon 20:38]
** Topics for discussion
