#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 84 On strike 罢工

#+begin_verse
Who will be driving the buses next week?

Busmen have decided to go on strike next week.
The strike is due to begin on Tuesday.
No one knows how long it will last.
The busmen have stated that the strike will continue until general agreement is reached about pay and working conditions.
Most people believe that the strike will last for at least a week.
Many owners of private cars are going to offer‘free rides’to people on their way to work.
This will relieve pressure on the trains to some extent.
Meanwhile, a number of university students have volunteered to drive buses while the strike lasts.
All the students are expert drivers, but before they drive any of the buses, they  will have to pass a special test.
The students are going to take the test in two days' time.
Even so, people are going to find it difficult to get to work.
But so far, the public has expressed its gratitude to the students in letters to the Press.
Only one or two people have objected that the students will drive too fast!

#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
