#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 85 Never too old to learn

#+begin_verse
How long has Mr. Page been teaching?

I have just received a letter from my old school,
	informing me
		that my former headmaster, Mr. Stuart Page, will be retiring next week.
Pupils of the school, old and new, will be sending him a present to mark the occasion.
All those who have contributed towards the gift
	will sign their names in a large album
		which will be sent to the headmaster's home.
We shall all remember Mr. Page for his patience and understanding
	and for the kindly encouragement he gave us
		when we went so unwillingly to school.
A great many former pupils will be attending a farewell dinner in his honour next Thursday.
It is a curious coincidence
	that the day before his retirement,
	Mr. Page will have been teaching for a total of forty years.
After he has retired,
	he will devote himself to gardening.
For him, this will be an entirely new hobby.
But this does not matter,
	for, as he has often remarked,
		one is never too old to learn.
#+end_verse

** words
inform [ɪnˈfɔrm] v.告诉,通知
headmaster [ˈhedˌmæstər] n.校长
contribute [ˈkɑntrɪˌbjut] v.捐助,援助
gift [ɡɪft] n.礼物,赠品
album [ˈælbəm] n.签名簿,相册
patient [ˈpeɪʃ(ə)nt] n.耐心
encouragement [ɪnˈkʌrɪdʒmənt] n.鼓励
farewell [ferˈwel] n.告别
honour [ˈɑnər] n.敬意
coincidence [koʊˈɪnsɪdəns] n.巧合
total [ˈtoʊt(ə)l] n.总数
devote [dɪˈvoʊt] v.致力于
gardening [ˈɡɑrd(ə)nɪŋ] n.园艺
hobby [ˈhɑbi] n.爱好,嗜好
** 单词造句

** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
