#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 86 Out of control 失控
#+begin_verse
What was the danger?

As the man tried to swing the speedboat round,
	the steering wheel *came away* in his hands.
He waved desperately to his companion,
	who had been water skiing for the last fifteen minutes.
Both men had hardly had time to realize
		what was happening
	when they were thrown violently into the sea.
The speedboat had struck a buoy,
	but it continued to move very quickly across the water.
Both men had just begun to swim towards the shore,
	when *they noticed with dismay*
		that the speedboat was moving *in a circle*.
It now came straight towards them *at tremendous speed*.
In less than a minute, it roared past them only a few feet away.
After it had passed,
	they swam on as quickly as they could
	because they knew that the boat would soon return.
They had just had enough time to swim out of danger
	when the boat again completed a circle.
On this occasion, however, it had slowed down considerably.
The petrol had nearly all *been used up*.
*Before long*, the noise dropped completely
	and the boat began to drift gently across the water.
#+end_verse

** words
swing [swɪŋ] v.转向
speedboat [ˈspidˌboʊt] n.快艇
desperately [ˈdesp(ə)rət(ə)li] adv.绝望地
companion [kəmˈpænjən] n.同伙,伙伴
water ski [ˈwɔtər-,ski] 滑水
buoy [ˈbui] n.浮标
dismay [dɪsˈmeɪ] n.沮丧
tremendous [trəˈmendəs] adj.巨大的
petrol [ˈpetrəl] n.汽油
drift [drɪft] v.漂动,漂流
gently [ˈdʒentli] adv.缓慢地,轻轻地

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
