#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 87 A perfect alibi
#+begin_verse
What was wrong with the man's story?

'At the time the murder was committed,
	I was travelling on the 8 o'clock train to London,' said the man.
'Do you always catch such an early train?' asked the inspector.
'Of course I do,' answered the man.
'I must be at work at 10 o'clock.
My employer will confirm that I was there on time.'
'Would a later train get you to work on time?' asked the inspector.
'I suppose it would,
	but I never catch a later train.'
'At what time did you arrive at the station?'
'At ten to eight.
I bought a paper and waited for the train.'
'And you didn't notice anything unusual?'
'Of course not.'
'I suggest,' said the inspector,
	'that you are not telling the truth.
I suggest that you did not catch the 8 o'clock train,
	but that you caught the 8.25
		which would still get you to work on time.
You see, on the morning of the murder,
	the 8 o'clock train did not run at all.
It broke down at Ferngreen station
	and was taken off the line.'
#+end_verse
** words
alibi [ˈælɪˌbaɪ] n.不在犯罪现场
commit [kəˈmɪt] v.犯(罪~错)
inspector [ɪnˈspektər] n.探长
employer [ɪmˈplɔɪər] n.雇主
confirm [kənˈfɜrm] v.确认,证实
suggest [səɡˈdʒest] v.提醒
truth [truθ] n.真相
** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
