#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 88 Trapped in a mine

#+begin_verse
Why is the rescue taking so long?

Six men have been trapped in a mine for seventeen hours.
If they are not brought to the surface soon
	they may lose their lives.
However, rescue operations are proving difficult.
If explosives are used,
	vibrations will cause the roof of the mine to collapse.
Rescue workers are therefore drilling a hole on the north side of the mine.
They intend to bring the men up in a special capsule.
If there had not been a hard layer of rock beneath the soil,
	they would have completed the job in a few hours.
As it is, they have been drilling for sixteen hours
	and they still have a long way to go.
Meanwhile, a microphone, which was lowered into the mine two hours ago,
	has enabled the men to keep in touch with their closest relatives.
Though they are running out of food and drink,
	the men are cheerful and confident that they will get out soon.
They have been told
	that rescue operations are progressing smoothly.
If they knew how difficult it was to drill through the hard rock,
	they would lose heart.
#+end_verse

** words
trap [træp] v.陷入,使陷入困境
surface [ˈsɜrfəs] n.地面,表面
explosive [ɪkˈsploʊsɪv] n.炸药
vibration [vaɪˈbreɪʃ(ə)n] n.震动
collapse [kəˈlæps] v.坍塌
drill [drɪl] v.钻孔
capsule [ˈkæpˌsjul] n.容器
layer [ˈleɪr] n.层
beneath [bɪˈniθ] prep.在...之下
lower [ˈloʊr] v.放下,降低
progress [prəˈɡres] v.进展,进行
smoothly [ˈsmuːðli] adv.顺利地
** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
