#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 89 A slip of the tongue 口误

#+begin_verse
Who made the only funny joke that evening and why?

People will do anything to see a free show ---- even if it is a bad one.
When the news got round that a comedy show would be presented at our local cinema by the P. and YOU.Bird Seed Company, we all rushed to see it.
We had to queue for hours to get in and there must have been several hundred people present just before the show began.
Unfortunately, the show was one of the dullest we have ever seen.
Those who failed to get in need not have felt disappointed, as many of the artistes who should have appeared did not come.
The only funny things we heard that evening came from the advertiser at the beginning of the programme.
He was obviously very nervous and for some minutes stood awkwardly before the microphone.
As soon as he opened his mouth, everyone burst out laughing.
We all know what the poor man should have said, but what he actually said was: ‘This is the Poo and Ee Seed Bird Company.
Good ladies, evening and gentlemen!’
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
