#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 90 What's for supper?

#+begin_verse
What kind of fish are they?

Fish and chips has always been a favourite dish in Britain,
	but as the oceans have been overfished,
		fish has become more and more expensive.
So it comes as a surprise to learn
	that giant fish are terrifying the divers on North Sea oil rigs.
Oil rigs have to be repaired frequently
	and divers, who often have to work in darkness a hundred feet under water,
		have been frightened out of their wits
			by giant fish bumping into them as they work.
Now they have had special cages made to protect them from these monsters.
The fish are not sharks or killer whales,
	but favourite eating varieties like cod and skate
		which grow to unnatural sizes,
			sometimes as 10 much as twelve feet in length.
Three factors have caused these fish to grow so large:
	the warm water round the hot oil pipes under the sea;
	the plentiful supply of food thrown overboard by the crews on the rigs;
	the total absence of fishing boats around the oil rigs.
As a result, the fish just eat and eat and grow and grow in the lovely warm water.
Who eats who?
#+end_verse

** words
chip [tʃɪp] n.油煎土豆皮
overfish [ˌoʊvə'fɪʃ] v.过度捕捞
giant [ˈdʒaɪənt] adj.巨大的
terrify [ˈterəˌfaɪ] v.吓,使恐怖
diver [ˈdaɪvər] n.潜水员
oil rig [ɔɪl-rɪɡ] 石油钻塔
wit [wɪt] n.(复数)理智,头脑
cage [keɪdʒ] n.笼
shark [ʃɑrk] n.鲨鱼
whale [weɪl] n.鲸
variety [vəˈraɪəti] n.品种
cod [kɒd] n.鳕
skate [skeɪt] n.鳐
factor [ˈfæktər] n.因素
crew [kru] n.全体工作人员
** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
