#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 91 Three men in a basket

#+begin_verse
Where was the station's Commanding Officer?

A pilot noticed a balloon
	which seemed to be making for a Royal Air Force Station nearby.
He informed the station at once,
	but no one there was able to explain the mystery.
The officer in the control tower was very angry
		when he heard the news,
	because balloons can be a great danger to aircraft.
He said that someone might be spying on the station
	and the pilot was ordered to keep track of the strange object.
The pilot managed to circle the balloon for some time.
He could make out three men in a basket under it
	and one of them was holding a pair of binoculars.
When the balloon was over the station,
	the pilot saw one of the men taking photographs.
Soon afterwards, the balloon began to descend
	and it landed near an airfield.
The police were called in,
	but they could not arrest anyone,
	for the basket contained two Members of Parliament and the Commanding Officer of the station!
As the Commanding Officer explained later,
	one half of the station did not know what the other half was doing!
#+end_verse

** words
balloon [bəˈlun] n.气球
royal [ˈrɔɪəl] adj.皇家
spy [spaɪ] v.侦察
track [træk] n.轨迹,踪迹
binoculars [bɪˈnɑkjələrz] n.望远镜

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
