#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 92 Asking for trouble

#+begin_verse
Why did the policeman ask the writer to come to the police station?

It must have been about two in the morning when I returned home.
I tried to wake up my wife by ringing the doorbell,
	but she was *fast asleep*,
	so I got a ladder from the shed in the garden,
		put it against the wall,
		and began climbing towards the bedroom window.
I was almost there when a sarcastic voice below said,
	'I don't think the windows need cleaning at this time of the night.'
I looked down and nearly fell off the ladder
	when I saw a policeman.
I immediately regretted answering in the way I did,
	but I said, 'I enjoy cleaning windows at night.'
'So do I,' answered the policeman in the same tone.
'Excuse my interrupting you.
I *hate to interrupt* a man when he's busy working,
	but would you mind coming with me to the station?'
'Well, I'd prefer to stay here,' I said.
'You see. I've forgotten my key.'
'Your what?' he called.
'My key,' I shouted.
Fortunately, the shouting woke up my wife who opened the window
	just as the policeman had started to climb towards me.
#+end_verse

** words
fast [fæst] adv.熟(睡)
ladder [ˈlædər] n.梯子
shed [ʃed] n.棚子
sarcastic [sɑrˈkæstɪk] adj.讽刺的,讥笑的
tone [toʊn] n.语气,腔调

** DONE 单词造句
CLOSED: [2023-10-11 Wed 20:10]
fast [fæst] adv. fast asleep
1. He was fast asleep when his wife was frightened out of her wits.
2. He has watched a variety of videos before he was fast asleep.
3. He has been running out of his energy, he is fast asleep now.
4. When we saw the cat being fast asleep, we burst out laughing.
5. She felt disappointed, as her husband was fast asleep.
ladder [ˈlædər] n.
1. A fireman must get used to climbing the ladder up and down.
2. It comes as a surprise to learn that the policeman knocked him to the ground with a ladder.
3. You should protect your baby from the ladder.
4. The ladder is used to rescue people in the fire.
5. When the news get round, the ladder was soon sold out.
shed [ʃed] n.
1. They are due to have a lovely shed built in the yard.
2. Why is there a shed holding up the traffic?
3. This caused the shed to be burnt down.
4. The shed shouldn't have been burnt down.
5. As it is, we could afford to build a shed in our garden.
sarcastic [sɑrˈkæstɪk] adj. Are you being sarcastic?
1. Why are you being sarcastic?
2. "You're not playing truent from the school." The father said in a sarcastic voice.
3. We should have kept in touch with each other. His girlfriend said in a sarcastic voice.
4. The girl is always sarcastic.
5. The boy kept being sarcastic, in the end I couldn't stand it.
tone [toʊn] n. Don't take that tone with me!
1. Don't take that tone with me!
2. As long as you take that tone with me, I won't come to the station with you.
3. On the surface, he told the story to the girl in a friendly tone.
4. You had to talk to your collegue in a friendly tone. 
5. Don't take that tone with us, you're too hard on us.
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-11 Wed 20:10]
hate to do sth.
1. I hate to apologize to anyone when I am innocent.
2. Pupils of the school always hate to move in a circle about seven in the morning.
3. I hate to fill up his car over and over again.
4. She hate to make contribute to the hospital.
5. I hate to devote myself to the education.
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
