#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 93 A noble gift 崇高的礼物
#+begin_verse
Where was the Statue of Liberty made?

One of the most famous monuments in the world, the Statue of Liberty, was presented to the United States of America in the nineteenth century by the people of France.
The great statue, which was designed by the sculptor Auguste Bartholdi, took ten years to complete.
The actual figure was made of copper supported by a metal framework which had been especially constructed by Eiffel.
Before it could be transported to the United States, a site had to be found for it and a pedestal had to be built.
The site chosen was an island at the entrance of New York Harbour.
By 1884, a statue which was 151 feet tall had been erected in Paris.
The following year, it was taken to pieces and sent to America.
By the end of October 1886, the statue had been put together again and it was officially presented to the American people by Bartholdi.
Ever since then, the great monument has been a symbol of liberty for the millions of people who have passed through New York Harbour to make their homes in America.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
