#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 94 Future champions
#+begin_verse
What kind of race do the children compete in?

*Experiments have proved*
	that children can *be instructed in swimming* at a very early age.
At a special swimming pool in Los Angeles,
	children become expert at *holding their breath* under water even before they can walk.
Babies of two months old do not appear to *be reluctant to enter* the water.
It is not long before
	they *are so accustomed to swimming* that they can pick up weights from the floor of the pool.
A game that *is very popular with* these young swimmers is the underwater tricycle race.
Tricycles *are lined up* on the floor of the pool seven feet under water.
The children *compete against* each other to reach the other end of the pool.
Many pedal their tricycles, but most of them prefer to push or drag them.
Some children can cover the whole length of the pool without coming up for breath even once.
Whether they will ever become future Olympic champions, only time will tell.
Meanwhile, they should encourage those among us
	who cannot swim five yards before they are gasping for air.

#+end_verse

** words
instruct [ɪnˈstrʌkt] v.指导,传授
Los Angeles [lɔ:s-'ændʒələs] 洛杉矶
reluctant [rɪˈlʌktənt] adj.勉强的,不愿意的
weight [weɪt] n.重物
underwater [ˌʌndə(r)ˈwɔːtə(r)] adj.水下的
tricycle [ˈtraɪsɪk(ə)l] n.三轮车
compete [kəmˈpit] v.比赛,对抗
yard [jɑrd] n.码
gasp [ɡæsp] v.喘气

** DONE 单词造句
CLOSED: [2023-10-15 Sun 21:40]
instruct v. be instructed in doing sth.
1. He insisted on instructing his dog in putting his pow on the button.
2. He was instructed in removing this from his gate.
3. He was instructed in constructing a mental framework.
4. He was reluctant to be instrcuted in swimming.
5. Leo's job is to instruct us in English.
Los Angeles
reluctant adj. be reluctant to do sth.
1. I am reluctant to pay the bill.
2. French people are reluctant to represent the noble gift to America.
3. The artist is reluctant to take the monument to pieces.
4. The girl was reluctant to enter for the competition at the entrance of the theater.
5. He is reluctant to go to the camp site.
weight n.
1. The boy was called in to carry these heavy weights to the shady place under the tree.
2. Get out of here with these heavy weight.
3. The patient said that he hadn't lift any heavy weight.
4. We couldn't carry these heavy weights to there on such short notice.
5. The workers kept on carrying these heavy weight to the site.
underwater adj.
1. Why don't we swim underwater?
2. In the meantime, he had to remain underwater until the beer got out of here..
3. I have difficulty in holding my breath underwater.
4. When I saw the dolphin playing underwater, I bursted out laughing.
5. The worker double checked this pipe underwater.
tricycle n.
1. It is you who are responsible for the tricycle stolen, not him.
2. The father turned his attention to the tricycle.
3. For you safety, don't ride a tricycle in such condition.
4. He was unaware that his tricycle wasn't there any more.
5. There is a bulletin board in front of the tricycle.
compete v. compete against
1. It was not long before they competed against each other for the champion.
2. At the end of the harvesting, the villagers compete each other for the prize.
3. My parents always made us competed with each other.
4. On the bulletin board, it says that we should compete again each other.
5. Both of them have been competing against each other for the Command Officer of the station.
yard n. xx yards away
1. The garage is 100 yards away from my house.
2. The map says the nearest toilet we can use is 100 yards away. 
3. There is a police station 100 yards away.
4. A woman is sending a signal 100 yards away.
5. The soldier stood to attention 100 yards away.
gasp v.
1. When his wife suggests to travel abroad, he is always gasping.
2. The woman saw a ganster knocked her husband to the ground and she gasped.
3. My wife is used to gasping at wonderful view.
4. You needn't have gasped.
5. She may have already gasped.
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-15 Sun 21:39]
sb./sth. proved that + ...
1. He proved that the boy is lighting a cigarette.
2. Tests have proved that the practice works.
3. She proved that she was right and we were telling stories.
4. The girl proved that a bomb had been planted on the airplane.
5. The girl proved that she didn't feel frightened.
hold sb's breath
1. I can't hold my breath underwater for a long time.
2. Before losing my temper, I hold my breath.
3. I kept holding my breath to calm down.
4. He seems to be holding his breath.
5. You should have held your breath.
be accustomed to doing
1. I am accustomed to having an operation.
2. I am accustomed to cutting a mommy open.
3. I am accustomed to being covered with a rug.
4. She is accustomed to making herself comfortable in her brother's house.
5. The boss is accustomed to working overtime.
be popular with ...
1. The song is popular with young men and young women in the town.
2. The song must be popular with young men and young women.
3. It was not long before the cod is popular with Chinese.
4. It comes as a surprise to learn that the exam is popular with many countries.
5. Surfing is popular with the people of France.
be lined up
1. People are lined up to go on a strike.
2. People are lined up to take part in army.
3. They were lined up 100 yards away from the garage.
4. When the news get around, the crowd was lined up for the comedy show. 
5. Why are they lined up across the street? It is holding up the traffic.
** DONE 跟读至背诵
CLOSED: [2023-10-16 Mon 19:24]
** DONE Ask me if 写+读
CLOSED: [2023-10-16 Mon 19:36]
1. Children can be taught to swim at a very early age. At what age/When
	 At what age can children be taught to swim?
	 When can children be taught to swim?
2. This has been proved by experiments. How
	 How has this been proved?
3. There is a special swimming pool in Los Angeles. Where/What
	 Where is there a special swimming pool?
	 What is there in Los Angeles?
4. Children become expert. How good
	 How good do children become?
5. They hold their breath under water. Where
	 Where do they hold their breath?
6. They can do it before they can walk. What
	 What can they do before they can walk?
7. It's not long before they can swim. How long
	 How long is it before they can swim?
8. They can pick up weights. What
	 What can they pick up?
9. The weights are on the floor. Where
	 Where are the weights?
10. The tricycle race is popular. Which
		Which race is popular?
11. It's an underwater race. What kind
		What kind of race is it?
** DONE 摘要写作
CLOSED: [2023-10-16 Mon 19:48]
At a swimming pool in Los Angeles,
	children are taught to hold their breath under water before they can walk.
They begin learning when they are two months old and,
	in time, they can picked up weights from the bottom of pool.
They game they enjoy most is the tricycle race,
	which takes place seven feet under water.
Some children pedal tricycles, while others push or pull them,
	and a few can get across without coming up for air.

At a swimming pool in Los Angeles,
	children who are taught to hold their breath under water before they can walk
	often begin learning to swim when they are two months old.
Though they can pick up weights from the bottom of the pool,
	the game they enjoy most is the tricyle race.
This takes place seven feet under water and,
	while some children pedal tricylces, others push or pull them.
A few get across without coming up for air. 

** DONE tell the story 口语
CLOSED: [2023-10-16 Mon 19:50]
** Topics for discussion
