#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 94 Future champions 未来的冠军
#+begin_verse
What kind of race do the children compete in?

Experiments have proved that children can be instructed in swimming at a very early age.
At a special swimming pool in Los Angeles, children become expert at holding their breath under water even before they can walk.
Babies of two months old do not appear to be reluctant to enter the water.
It is not long before they are so accustomed to swimming that they can pick up weights from the floor of the pool.
A game that is very popular with these young swimmers is the underwater tricycle race.
Tricycles are lined up on the floor of the pool seven feet under water.
The children compete against each other to reach the other end of the pool.
Many pedal their tricycles, but most of them prefer to push or drag them.
Some children can cover the whole length of the pool without coming up for breath even once.
Whether they will ever become future Olympic champions, only time will tell.
Meanwhile, they should encourage those among us who cannot swim five yards before they are gasping for air.

#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
