#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 95 A fantasy
#+begin_verse
Why was the Ambassador particularly lucky?

When the Ambassador or Escalopia returned home for lunch,
	his wife got a shock.
He looked pale and his clothes were in a frightful state.
'What has happened?' she asked.
'How did your clothes get into such a mess?'
'A fire extinguisher, my dear,' answered the Ambassador drily.
'University students set the Embassy on fire this morning.'
'Good heavens!' exclaimed his wife.
'And where were you at the time?'
'I was in my office as usual,' answered the Ambassador.
'The fire broke out in the basement.
I went down immediately, of course,
	and that fool, Horst, aimed a fire extinguisher at me.
He thought I was on fire.
I must definitely get that fellow posted.'
The Ambassador's wife went on asking questions,
	when she suddenly noticed a big hole in her husband's hat.
'And how can you explain that?' she asked.
'Oh, that,' said the Ambassador.
'Someone fired a shot through my office window.
Accurate, don't you think?
Fortunately, I wasn't wearing it at the time.
If I had been,
	I would not have been able to get home for lunch.'
#+end_verse

** words
fantasy [ˈfæntəsi] n.幻想故事
ambassador [æmˈbæsədər] n.大使
Escalopia n.艾斯卡罗比亚
frightful [ˈfraɪtf(ə)l] adj.可怕的,令人吃惊的
fire extinguisher [faɪr-ɪkˈstɪŋɡwɪʃər] 灭火器
drily [ˈdraɪli] adv.冷淡地,枯燥无味地
embassy [ˈembəsi] n.大使馆
heaven [ˈhev(ə)n] n.天,天堂
basement [ˈbeɪsmənt] n.地下室
definitely [ˈdefənɪtli] adv.肯定地
post [poʊst] v.派任
shot [ʃɑt] n.子弹

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
