#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* meditation
** Following Your Breath
#+begin_verse
Drawn from the mindfulness tradition of Buddhism, this basic meditation practice develops concentration and uses the breath to teach you how to stay present from moment to moment, no matter where you are or what you may be doing.

For more-complete instructions (and more about mindfulness), see Chapter 7.
Or you can also listen to Track 4.

1. Begin by finding a comfortable sitting position that you can hold for 10 or 15 minutes.
	Take a few deep breaths and exhale slowly. Without trying to control your breath in any way, allow it to find its own natural depth and rhythm. Always breathe through your nose (unless you can’t for some reason).
	
2. Allow your attention to focus either on the sensation of your breath coming and going through your nostrils or on the rising and falling of your belly as you breathe.
	Although you’re welcome to alternate your focus from one session to the next, sticking with a single focus for the entire meditation is best. Eventually, you’re better off using the same focus each time you meditate.
	
3. Give your full attention to the coming and going of your breath.
	Pay attention to your breath the way a mother tracks the movements of her young child: lovingly yet persistently, softly yet precisely, and with relaxed yet focused awareness.
	
4. When you realize that your mind has wandered off and you’re engrossed in planning, thinking, or daydreaming, gently but firmly bring your mind back to your breath.
	Thoughts and images will almost certainly continue to skitter and swirl through your mind as you meditate, but don’t worry. Just patiently and persistently keep coming back to your breath. If you find it virtually impossible to follow your breath, you may want to begin with counting your breaths (see Chapter 7).

5. Continue this simple (but not easy!) exercise for the duration of your meditation.
	With repeated practice, you may find that your mind settles down more quickly and that you’re more present and focused in other areas of your life as well.
#+end_verse
** Yoga nidra
welcome to Yoga
Nidra find a quiet
place switch off the
phone and make sure you won't be
disturbed for the next 20 minutes or
so you can either lay on your
bed yoga mat or somewhere where you can
be a l
position in
Comfort on your
back with your knees slightly bent and
supported arms away from the body Palms
facing
upwards make sure that you are warm
enough and that your body is
comfortable during the practice remain
still awake and listen to the sound of
my my
voice this allows both your body and
brain to fully
relax I will take your awareness to
different parts of the
body try not to concentrate too
intensely as this may stop you from
relaxing if the body becomes overactive
with thoughts just come back to the
sound of my voice
become aware now of the feeling of your
body laying
down total awareness of your body lying
in perfect Stillness and
relaxation allow your eyes to gently
close and keep them closed now until the
end of practice
ice take a deep breath in through your
nose and out through your
nose and allow your awareness to settle
on your natural breathing
Rhythm feel the breathing slowing
down
feel your heart rate slowing
down and allow the mind to
quieten as you inhale deeply through the
nostrils feel the gentle rise of the
abdomen as you exhale fully feel the
abdomen sink down down towards the
mat inhale relaxation into the
body exhaling out tension
leaving
inhale relaxation into the
body exhale stress leaving the
body inhale relaxation into every every
cell of the
body
exhale Letting
Go Letting
Go letting
go I would like you now to think of a
short positive
statement it could be I am calm and
relaxed I am happy and
healthy I am confident and at ease with
myself or another short statement
positive and in the present
tense now you have your
intention I would like you to mentally
repeat it now three
times the intention you make during Yoga
Nidra plants a seed for Trans
transformation in your
life allow the breath now to come and go
at its own Rhythm at its own
pace I'm going to take your awareness
now to different parts of the
body notice the
area feel feel the
area relax the area but do not move the
body take the awareness to the right
hand feel the right
thumb index
finger ring
finger little
Finger palm of the
hand back of the
hand
wrist
forearm
elbow upper
arm
shoulder
armpit right side of the
waist
hip
thigh
knee
[Music]
calve
ankle
[Music]
heel top of the
foot sole of the
foot right big toe
second
toe third
toe fourth
toe little
toe left
hand feel the
thumb index
finger middle
finger ring
finger little finger

palm of the

[Music]

hand back of the

hand

wrist

[Music]

forearm

[Music]

elbow upper

arm

shoulder

armit

waist

hip

thigh

knee

[Music]

Cal

ankle

heel top of the

foot sole of the

foot left big

toe second

toe third toe

toe fourth

toe little

[Music]

toe take the awareness to the back of

the

head back of the

neck right shoulder

blade left shoulder

blade the length of the

spine

[Music]

right

buttock left

buttock right

thigh left

thigh right

[Music]

Cal left

calve right

heel left

heel now take take the awareness to the

front of the

body top of the
----------------------------------------

head

forehead right

Temple left

temple right

[Music]

ear left

[Music]

ear right

eyebrow left eyebrow

space between the

eyebrows right

eye and

eyelid left eye and

eyelid right

nostril left

nostril right

cheek left

cheek upper

lip lower

lip both lips touching

together

tongue inside the right

cheek inside the left

cheek chin

jaw

throat right

collarbone left collar

[Music]

bone right side of the

chest left side of the

chest upper

[Music]

abdomen

[Music]

Naval lower

abdomen right

[Music]

groin left

groin the pelvic

[Music]

floor the whole right

leg the whole left left

leg the whole right

arm the whole left

arm the whole

[Music]

face the whole

[Music]

head the whole

torso the whole

[Music]

body totally

relaxed the whole

body free from

[Music]

tension

[Music]

on your next

exhalation Imagine a wave of relaxation

flowing down through your body carrying

away

tensions as you you inhale feel a fresh

wave of relaxation flowing up through

your whole body bringing a sense of calm

to every

cell exhale feel a wave flowing down

through your body carrying away all

fears inhale a fresh wave of relaxation

flows up the body and brings Serenity

and

[Music]

[Music]

peace

[Music]

notice the body

now in its laying

[Music]

position notice how the body feels when

it's totally

relaxed

notice how the body feels when it's

free

[Music]

calm and

[Music]

relaxed

[Music]

gently become aware now of your body

laid

down totally

relaxed feel the contact of the

body with the mat or whatever your lying

on through the

heels

calves lower

back shoulder

blades back of the

arms back of the

head become totally aware of the

body

[Music]

gently begin to move your

fingers gently begin to move your

[Music]

toes slowly roll your head from side to

side and on an

inhalation stretch the body however it

wants to

stretch roll on to your side and stay

there keeping the eyes closed

[Music]

mentally repeat again three times your

positive

[Music]

intention really feel this positive

intention throughout the

body and know it to be

[Music]

[Music]

true

[Music]

when you're

ready slowly coming to a comfortable

sitting

position still keeping the eyes

closed so we keep the outside world out

that little bit

longer take three deep breaths

snow

in and out of the

[Music]

abdomen notice the effects The Yoga

Nidra has had on the

mind and the

body and when you're

ready slowly open your eyes

[Music]

e

