#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2-2 2 The psychodynamic approach
#+begin_verse
What Freud is almost universally acknowledged as a profoundly important intellectual figure.
He's also the object of considerable dislike.
This is in part because of his character.
He was highly ambitious in the cause of promoting psychoanalysis,
	often dishonest, sometimes brutal to his enemies
	and sometimes particularly brutal to his friends and his students.
More important that is the content of his views.
At the time, he was seen as a sexual renegade out
	to destroy the conception of people as good and rational people.
When the Nazis rose to power in the 1930's,
	Freud was seen as a Jew who was attempting to
		single-handedly destroys some of the most cherished notions of Christian morality.
Now, to some extent, many people see him this way,
	and to some extent this accusation has some truth to it.
	
Freud told us things about ourselves that are immensely uncomfortable
	and some things that many of us would rather not know.
So, what did he say?
Well, if you ask someone who hates Freud, they'll talk about the sillier stuff,
	and in fact Freud said a lot of things and some of them were wacky at the time,
		and many of them certainly did not survive the verdict of scientific history.
Many of his ideas were simply silly.
Possibly the dumbest thing he ever said,
		which is something which many people think of him and associate with his name,
	is the idea of penis envy.
So, penis envy is an account of a developmental progression.
The idea is that at some point in her development,
	a little girl discovers that she doesn't have a penis.
For her, this is a catastrophe because she infers, according to Freud, that she was castrated.
So, she turns to her father to get a penis substitute
		because he has a penis and rejects her mother who's equally unworthy,
	and Freud calls this process the Electra complex.
Now, if that's all you know about his work,
	if you think about Freud in terms of penis envy, or phallic symbols,
			or kind of pop interpretation of dreams,
		you won't have the highest opinion of him.
		
But at the root of Freud's work is a set of ideas of immense importance and significance
		that are worth taking very seriously,
	and very broadly these are the ideas of unconscious motivation,
		that there're unconscious reasons for your feelings and actions
			as well as the notion of unconscious dynamics.
That you are not one entity, you are many entities
	and the clash of these different systems inside your mind, inside your brain
		has all sorts of consequences leading among other things to dreams, to errors in speech,
			the sort of jokes you make and what you find funny, and often and in some cases to madness.
Now, certainly Freud wasn't the first to believe in unconscious motivations,
	unconscious reasons, unconscious dynamics.
You could find a lot of the same ideas in many scholars and elsewhere,
		like the plays of William Shakespeare,
	but Freud took it to an extreme and systematized it and turned it into science.
	
The first idea, that our unconscious reasons, unconscious motivation,
	is a rejection of the common sense conception that we know what we're doing.
So, suppose you fall in love with somebody and decide you wanted to marry that person,
	and suppose somebody was to ask you, "Why?"
You might say something like, "Well, I'm ready to get married.
It's time of my life.
I really like the person.
I want to make a life with that person, and so on," and maybe that's true.
But a Freudian would insist that your desires and motivations that govern your behavior,
	that you might simply not know about.
You might want to marry John because he reminds you of your father,
	or you want to get back at your mother for betraying you, or some other such reason,
	and if somebody was to tell you this you would deny it, and you'd sincerely deny and say,
	'No. That's not the reason.'
But this wouldn't deter a Freudian.
A Freudian might argue that these processes, these motivations, these reasons are unconscious
	and they happen without your awareness.
Now, this idea that you don't know how your mind works,
		you don't have access to the systems
			that give rise to your experiences, and beliefs, and actions
	is something we accept for other psychological domains,
		like language comprehension, and visual perception,
	and we'll talk about those later on in the course,
	and we'll learn,
		talk about different theories of how we come to, say, understand language or see the world.
They're going to propose all sorts of things that you have no awareness of, and you'll say,
	"Okay. Well, let's evaluate these theories on their merits."
But it's downright scary to assume that this sort of unconscious, unknowing system operates
	to explain the most significant choices of your life.
	
Now, the marriage case is extreme, but there are a lot of simpler examples.
Have you ever liked someone or disliked them and not known why?
You just find this either a sort of powerful attraction to a person or you find a person repellent,
	but if you had to articulate the reasons you couldn't really explain them.
Have you ever found yourself in a situation where you've asked,
	"What the hell am I doing here? Why am I doing this? Why did I get caught up in this?"
	and again not know the reasons.
Have you ever forgotten someone's name at exactly the wrong time?
	"Yes, nice to meet you. This is my wife,"
	and wondered later, "Why did I forget that?"
Have you ever forgotten an appointment?
And those cases actually, they're sort of an intuitive grounding for a Freudian theory.
Have you ever forgotten an appointment that you really didn't want to go to?
And rather than not go to it, you just slipped your mind somehow,
	and what this suggests is there's a lot more going on in our heads that we're aware of,
	and this is what Freud called the unconscious.
	
Now, this might be okay if the unconscious was a reasonable rational computer planning for you
		and always doing the right things,
	but according to Freud things aren't always so tidy.
According to Freud, there are three distinct processes going on in your head,
	and they're in violent internal conflict.
These processes are the id, the ego and the super-ego.
The id is present at birth.
It's the animal part of ourself.
It wants to eat, and drink, and poop, and pee, and get warm and get sensual pleasure.
So outrageously stupid.
It works in what Freud call the pleasure principle.
I want satisfaction and I want it now.
The problem is the world doesn't work that way.
One's desires, even as a baby, are rarely immediately satisfied.
You could want milk but the mother's breast isn't there,
	and this failure of the world to give you what you want leads to a set of reactions,
		lead to a whole another system in the head called the ego,
	and the ego has some understanding of reality and logic.
The ego works on the reality principle,
	which is it tries to pragmatically satisfy your desires or it suppresses them.
But either way, it deals with the way the world is and how to reconcile that with what you want,
	and for Freud your ego is you.
Your ego is your conscious self, and this is where consciousness emerges.
It is, as you go through your day and think about things, and remember things, and plan,
	that's all your ego.
Now, if that's all there was, all there was was an id and an ego, it will be a simpler world,
	but then there's the super-ego,
		and the super-ego is the part of the mind that has internalized rules of parents and society.
So, for instance, imagine a child who learns not to cheat in school,
	and one way to think about this is that the child learns that cheating,
		you get punished for it, you get caught, you get in trouble.
That's a very ego thing.
You may repress your desire to cheat because of worries about the consequences,
	but what really will happen is you come to internalize these moral rules
		and ultimately you believe you shouldn't cheat because it's wrong to cheat.
You would feel guilty or ashamed if you cheated.
In other words, it's not merely fear of consequences
	but rather you develop an understanding of what's right and wrong.
	
So, the ego then serves two masters.
It's stuck between raging animal desires on the one hand, the id,
	and a sort of moral conscience on other hand, the superego.
Now, it's tempting to think, as I'm framing it this way,
		that the id is dumb and animalistic and the super-ego is something advanced and civilized,
	but it's not so simple.
A lot of the prohibitions set up in the super-ego were setup early in development,
	and are grounded on the prejudices and beliefs of the society
		in which you're raised, not necessarily an accurate moral understanding.
So, for instance, it's very possible that you might believe, intellectually,
		that some act you engage in, some sort of sexual act for instance, is perfectly fine morally,
	but your super ego, which is developed in childhood, may scream at you.
As irrational as it is, it might scream at you,
	"You should be ashamed.
	That's disgusting.
	That's filthy."
So, part of what we do in our life, part of what we have to struggle with
		is the conflict between id and super-ego
	and to some extent your ego, yourself is stuck in the middle.
You could see it as an iceberg, where a lot of it, it should be submerged and unconscious,
	but what we experience is mostly ego and a bit of super-ego.
But a lot of what goes on into id, for Freud, is unconscious, and so desires trickle up,
	but often you don't really know what you want. You don't know what's driving you.
And this is particularly the case,
	as we'll see, if these drives, these desires are somehow forbidden.
#+end_verse
** expression
brutal [ˈbrut(ə)l]: adj. very cruel and violent残忍的
renegade [ˈrenˌɪɡeɪd]: n. someone who leaves one side in a war, politics etc in order to join the opposing side – used to show disapproval背教者, 变节者, 叛徒
single-handedly: adv. if one person does something single-handedly, they do it without help from anyone else SYN alone单独地
cherish [ˈtʃerɪʃ]: v. if you cherish something, it is very important to you珍爱
morality [məˈræləti]: n. beliefs or ideas about what is right and wrong and about how people should behave道德
silly [ˈsɪli]: adj. not sensible, or showing bad judgment愚蠢的
wacky [ˈwæki]: adj. silly in an exciting or amusing way SYN crazy古怪的
verdict [ˈvɜrdɪkt]: n. an official decision made in a court of law, especially about whether someone is guilty of a crime or how a death happened裁决
castrate [ˈkæˌstreɪt]: v. to remove the ↑testicles of a male animal or a man阉割,去掉最重要的部分
substitute [ˈsʌbstɪˌtut]: n. a person or thing that you use instead of the one that you usually have, because the usual one is not available替代品
broadly [ˈbrɔdli]: adv. in a general way, relating to the main facts rather than details大体上
clash [klæʃ]: n. if two armies, groups etc clash, they start fighting – used in news reports冲突
systematize [ˈsɪstəməˌtaɪz]: v. to put facts, numbers, ideas etc into a particular order系统化
betray [bɪˈtreɪ]: v. to be disloyal to someone who trusts you, so that they are harmed or upset出卖, 背叛
deter [dɪˈtɜr]: v. to stop someone from doing something, by making them realize it will be difficult or have bad results ⇨ deterrent阻止
evaluate [ɪˈvæljuˌeɪt]: v. to judge how good, useful, or successful something is SYN assess评价,评估
downright [ˈdaʊnˌraɪt]: adv. used to emphasize that something is completely bad or untrue彻底地
repellent [rɪˈpelənt]: adj. very unpleasant ⇨ repulsive排斥的
tidy [ˈtaɪdi]: adj. a tidy mind British English if someone has a tidy mind, the way they think is very organized and clear整洁的, 精简的
sensual [ˈsenʃuəl]: adj. relating to the feelings of your body rather than your mind感觉的
outrageous outrageously [aʊtˈreɪdʒəs]: adj.adv. very shocking and extremely unfair or offensive骇人的
pragmatic pragmatically [præɡˈmætɪk]: adj.adv. dealing with problems in a sensible practical way instead of strictly following a set of ideas ⇨ dogmatic务实的
repress [rɪˈpres]: v. to stop yourself from doing something you want to do抑制
master [ˈmæstər]: n. man with authority主人
raging [ˈreɪdʒɪŋ]: adj. very great and hard to control强烈的
prohibit [proʊˈhɪbɪt] prohibition: v.n. an order stopping something(法令)禁止
prejudice [ˈpredʒədɪs]: n. an unreasonable dislike and distrust of people who are different from you in some way, especially because of their race, sex, religion etc – used to show disapproval偏见
filthy [ˈfɪlθi]: very dirty污秽的
trickle [ˈtrɪk(ə)l]: v. if liquid trickles somewhere, it flows slowly in drops or in a thin stream流淌
submerge [səbˈmɜr(r)dʒ] submerged: v.adj. to cover something completely with water or another liquid淹没
--------------------
rise to power: 上台
sb. infers that + ... [ɪnˈfɜr]: 某人推断+...
turn to sb.: 向某人寻求帮助
common sense: 常识
scream at sb. [skrim]: 朝某人尖叫
get back at sb.: 向某人复仇
without sb's awareness: 在某人不知情下
have no awareness of sth./doing sth.: 对某事和做某事无意识
sth. slips sb's mind: 某人忘记了某事
reconcile A with B [ˈrekənˌsaɪl]: 调和A与B
** sentence
brutal [ˈbrut(ə)l]: adj. very cruel and violent残忍的
- It seems that the plantation class is born brutal.
- Our master would be burtal or gentle by a roll of the dice the next day.
- It implies that the master of the orchard is brutal to his servants.
renegade [ˈrenˌɪɡeɪd]: n. someone who leaves one side in a war, politics etc in order to join the opposing side – used to show disapproval背教者, 变节者, 叛徒
- The renegade who betrayed his home country rises to fame over the course of millennia.
- The benefits of being a renegade are beyond your imagination.
- A minority to turn to their fathers was regarded as renegades.
single-handedly: adv. if one person does something single-handedly, they do it without help from anyone else SYN alone单独地
- Thrown off by his mother, he leads a difficult life single-handedly.
- Your criticisms led to him going to hospital single-handedly.
- He is riding himself single-handedly in the opposite direction.
cherish [ˈtʃerɪʃ]: v. if you cherish something, it is very important to you珍爱
- The cherished church disappeared from the town, which reminds me of my grandfather.
- I will find whoever destoryed the cherished statue in the temple.
- Things play out, you are unwilling to take care of your grandson who used to be cherished.
morality [məˈræləti]: n. beliefs or ideas about what is right and wrong and about how people should behave道德
- He went to elementary school and developed a sense of morality simultaneously over time.
- With the cherished statue in his hands, he developed a sense of morality.
- Because of a sense of morality, he was eager to return the wallet to you.
silly [ˈsɪli]: adj. not sensible, or showing bad judgment愚蠢的
- Only does a silly child explain a cat as a toy.
- The silly girl is likely playing with her cat.
- Because of the silly behaviors in the meeting, he was chained up by his master.
wacky [ˈwæki]: adj. silly in an exciting or amusing way SYN crazy古怪的
- Why are you facing the wall, which looks very wacky?
- The famous actor is well-known for presenting his girl-friends wacky stones that give off.
- Let's pass by the wacky old man who is smoking as soon as possible.
verdict [ˈvɜrdɪkt]: n. an official decision made in a court of law, especially about whether someone is guilty of a crime or how a death happened裁决
- His children refused to pay for his expense of operation, which was regarded as a verdict.
- According to the verdict, you may have a difficult time paying your debts.
- He deliberated at length over length resisting an attempt to disobey it.
castrate [ˈkæˌstreɪt]: v. to remove the ↑testicles of a male animal or a man阉割,去掉最重要的部分
- He introduces the movie as an analogy of a castrated chicken.
- We have learnt that he had been castrated in the camp and committed a suicide.
- The castrated man in the palace are hostile to those whoever refer to it.
substitute [ˈsʌbstɪˌtut]: n. a person or thing that you use instead of the one that you usually have, because the usual one is not available替代品
- In the real life, it is almost impossible to find a substitute for an eminent teacher who is willing to teach in a small hamlet.
- Once a substitute is found by the king, you will be sentenced to die.
- He grew angry as he found his wife viewed him as a substitute for her ex-boyfriend.
broadly [ˈbrɔdli]: adv. in a general way, relating to the main facts rather than details大体上
- I deserve a warm welcome as I was going about our house chores broadly.
- Broadly a glimmer of light couldn't affect the outcome of the experiment.
- Broadly our master groups cats under livestock.
clash [klæʃ]: n. if two armies, groups etc clash, they start fighting – used in news reports冲突
- The king is going about the clash of the two clans.
- The clash of the two fighter punched a hole by accident in the chimney.
- At last, the policeman broke free from the clash of the two hamlets.
systematize [ˈsɪstəməˌtaɪz]: v. to put facts, numbers, ideas etc into a particular order系统化
- Sticking with research for minds, the psychology succeeded in systematizing his theory.
- Grappling with the question of mental health, he systematized a series of treatments.
- He proposed a way of systematizing management of those entrepreneurs.
betray [bɪˈtreɪ]: v. to be disloyal to someone who trusts you, so that they are harmed or upset出卖, 背叛
- A sequence of things shows evidence of his betraying you.
- God blessing, only a tiny fraction of our people betrayed us at the war.
- Master, I have no approach to betraying you under certain circumstances.
deter [dɪˈtɜr]: v. to stop someone from doing something, by making them realize it will be difficult or have bad results ⇨ deterrent阻止
- Nowadays, the authorities are detering young people from parading in public.
- An initial population of cats deterred these rat from overflowing the warehouse.
- A new generation of products invented by the company deters customers from choosing other brand.
evaluate [ɪˈvæljuˌeɪt]: v. to judge how good, useful, or successful something is SYN assess评价,评估
- It doesn't makes any meaning of evaluating the products that have been weeded out.
- Evaluating the presense of artificial intelligence becomes popular with people in China.
- The jury may still be out, it's hard to evaluate the value of artificial intelligence.
downright [ˈdaʊnˌraɪt]: adv. used to emphasize that something is completely bad or untrue彻底地
- The outcome of new AI model downright blew my mind and led to my thinking of my future career.
- He was downright scared to the horror movie which you presented him yesterday.
- The horror movie downright scares the hell out of me.
repellent [rɪˈpelənt]: adj. very unpleasant ⇨ repulsive排斥的
- What the repellent man did sent shivers down my spine.
- Due to the instructions from my superior, I have to resort to the repellent colleague.
- Your repellent teacher is not your ground for your playing truant from school.
tidy [ˈtaɪdi]: adj. a tidy mind British English if someone has a tidy mind, the way they think is very organized and clear整洁的, 精简的
- I picked up the cotton for you day in day out, and what I requested is only a tidy bed to rest on.
- As disgusting as it may sound, we have to make the toilet tidy before the dusk.
- The dog will make the floor tidy, who is fed off of infant's poop.
sensual [ˈsenʃuəl]: adj. relating to the feelings of your body rather than your mind感觉的
- His persuit of sensual pleasure and vanity is without limit.
- His persuit of sensual pleasure led to a sequence of catastrophes.
- The poor boy who lost his mother in his three-years-old tended to repress his desires of sensual pleasure.
outrageous outrageously [aʊtˈreɪdʒəs]: adj.adv. very shocking and extremely unfair or offensive骇人的,残暴的
- The garrison has no ability to resist the outrageous attack from the mobs. 
- What niggers suffered in the south is outrageous.
- When you heard some news outrageous, you'd better look for its source and credibility.
pragmatic pragmatically [præɡˈmætɪk]: adj.adv. dealing with problems in a sensible practical way instead of strictly following a set of ideas ⇨ dogmatic务实的
- The official regarded as pragmantic rose to power and set up a series of laws prohibiting some tradition rituals.
- My manager is so pragmatic that he never asked me to something useless.
- If you pragmatically deliberated at length over the project, you wouldn't stick to your plan.
repress [rɪˈpres]: v. to stop yourself from doing something you want to do抑制
- I did try to repress my sadness in front of my family, but in an outrageous manner.
- Worrying about being judged, I repressed my desires for food in my childhood.
- After I was judged by my grandfather I began to repress my desires for food.
master [ˈmæstər]: n. man with authority主人
- No one shall betray our good master.
- Because of the spread of the writing contrary to the holy church, the masters of orchards were gathered around waitting for the Inquisition.
- Under certain circumstances, even a good master had to beat his slave in front of others.
raging [ˈreɪdʒɪŋ]: adj. very great and hard to control强烈的
- The president had a raging appetite at the party when he was surrounded by those pretty girls.
- The president was said to have a raging sexual desire for underage girls.
- You can't communicate with anyone who is in a raging temper.
prohibit [proʊˈhɪbɪt] prohibition: v.n. an order stopping something(法令)禁止
- Because of the alcohol prohibition, there are a lot of gangs in the blocks.
- As an official working for the government, you should be aware that the king prohibited any shows in the subway.
- With foreign enterprises prohibited, we are facing economic depression when our neighbors are thriving.
prejudice [ˈpredʒədɪs]: n. an unreasonable dislike and distrust of people who are different from you in some way, especially because of their race, sex, religion etc – used to show disapproval偏见
- Your prejudice makes us find you repellent.
- We shouldn't invite a man full of prejudice to our party who is hardwired to break down our atmosphere.
- The authorities lost no time in prohibiting the spread of the writing full of prejudice about plantations.
filthy [ˈfɪlθi]: very dirty污秽的
- Due to the lack of raw sewage the town is not as filthy as before.
- Our cousin rated our room filthy, whose room is full of rubbish.
- Every piece of our room's floor is full of filthy vomiting.
trickle [ˈtrɪk(ə)l]: v. if liquid trickles somewhere, it flows slowly in drops or in a thin stream流淌
- The stream from the mountain trickling into the river became larger.
- With a knife stabbing in his arm, the red blood is trickling down it.
- The little stream from the tap is trickling, which gives me a sense of quietness.
submerge [səbˈmɜr(r)dʒ] submerged: v.adj. to cover something completely with water or another liquid淹没
- In my childhood, after I woke up I often found my house submerged because of a storm.
- Fearing that our house would be submeraged because of rain, my grandfather laid a high foundation of the house.
- All of the fields in our village has been submerged, and you can barely recognize the river.
--------------------
rise to power: 上台
- People in China often cherish the wish that an eminent official will rise to power and improve their lives. 
- The president who rose to power last week set up a series of laws prohibiting any alcohol beverage.
- No matter who rises to power, do your own business.
sb. infers that + ... [ɪnˈfɜr]: 某人推断+...
- I infer that our cat has been fed by our three-years-old son.
- She inferred that her husband was having an affair with his prior girlfriend in the university.
- My wife inferred that the couple who quarrelled bitterly on TV didn't get divorce after this.
turn to sb.: 向某人寻求帮助
- You should turn to your father who is willing to get you out of trouble.
- I must turn to my manager who asked me to follow his instruction.
- No matter who you are to turn to, you should try it single-handedly.
common sense: 常识
- It is a common sense that every man is blessed with a dick.
- It is a common sense that the price of real estate is depent on the market, not on your will.
- It is a common sense that the two villages have been hostile to each other for twenty years.
scream at sb. [skrim]: 朝某人尖叫
- It is your punishment, for you screammed at a holy priest in the church.
- When his wife screammed at him again, he lost his temper and attacked his wife.
- I am guilty, what I have done led to a lady screaming at me in the street.
get back at sb.: 向某人复仇
- My cousin got married to a poor boy so that she could get back at her family who neglected her.
- It was a father who got back at those who hurt his precious son.
- In case she gets back at us, we must pay attention to her imprisonment.
without sb's awareness: 在某人不知情下
- I fetched my pocket money from my father without his awareness.
- When I was wandering in the village fair, I was robbed almost without my awareness.
- My cat fell in love with our child with our awareness.
have no awareness of sth./doing sth.: 对某事和做某事无意识
- I have no awareness of taking the pencil from the supermarket.
- She claimed that she had no awareness of breaking down the atmosphere.
- My father told me that he had no awareness of what he had done in his condition.
sth. slips sb's mind: 某人忘记了某事
- Sadly, my best friend's birthday slipped my mind, which gave me a sense of guilt.
- The anniversary slipped my mind, which led to our raging quarrel.
- Don't let the date of the interview slip your mind.
reconcile A with B [ˈrekənˌsaɪl]: 调和A与B
- My grandfather punished us both without judgement to reconcile my cousin with me.
- What will happen next is a policeman who tries to reconcile you with the butcher.
- No matter what happens, don't try to reconcil me with him, who made such stupid remarks.
** sentence2
brutal [ˈbrut(ə)l]: adj. very cruel and violent残忍的
- It seems that the plantation class is born brutal.
- Our master would be brutal or gentle by a roll of the dice the next day.
- It implies that the master of the orchard is brutal to his servants.
renegade [ˈrenˌɪɡeɪd]: n. someone who leaves one side in a war, politics etc in order to join the opposing side – used to show disapproval背教者, 变节者, 叛徒
- The renegade who betrayed his home country rises to fame over the course of millennia.
- The benefits of being a renegade are beyond your imagination.
- A minority of children who turn to their fathers were regarded as renegades.
single-handedly: adv. if one person does something single-handedly, they do it without help from anyone else SYN alone单独地
- Thrown off by his mother, he leads a difficult life single-handedly.
- Your criticisms led to him going to the hospital single-handedly.
- He is riding himself single-handedly in the opposite direction.
cherish [ˈtʃerɪʃ]: v. if you cherish something, it is very important to you珍爱
- The cherished church disappeared from the town, which reminds me of my grandfather.
- I will find whoever destroyed the cherished statue in the temple.
- Things play out, you are unwilling to take care of your grandson who used to be cherished.
morality [məˈræləti]: n. beliefs or ideas about what is right and wrong and about how people should behave道德
- He went to elementary school and developed a sense of morality simultaneously over time.
- With the cherished statue in his hands, he developed a sense of morality.
- Because of a sense of morality, he was eager to return the wallet to you.
silly [ˈsɪli]: adj. not sensible, or showing bad judgment愚蠢的
- Only does a silly child explain a cat as a toy.
- The silly girl is likely playing with her cat.
- Because of the silly behaviors in the meeting, he was chained up by his master.
wacky [ˈwæki]: adj. silly in an exciting or amusing way SYN crazy古怪的
- Why are you facing the wall, which looks very wacky?
- The famous actor is well-known for presenting his girl-friends wacky stones that give off.
- Let's pass by the wacky old man who is smoking as soon as possible.
verdict [ˈvɜrdɪkt]: n. an official decision made in a court of law, especially about whether someone is guilty of a crime or how a death happened裁决
- His children refused to pay for his expense of operation, which was regarded as a verdict.
- According to the verdict, you may have a difficult time paying your debts.
- He deliberated at length over length resisting an attempt to disobey it.
castrate [ˈkæˌstreɪt]: v. to remove the ↑testicles of a male animal or a man阉割,去掉最重要的部分
- He introduces the movie as an analogy of a castrated chicken.
- We have learned that he had been castrated in the camp and committed suicide.
- The castrated men in the palace are hostile to those who refer to it.
substitute [ˈsʌbstɪˌtut]: n. a person or thing that you use instead of the one that you usually have, because the usual one is not available替代品
- In real life, it is almost impossible to find a substitute for an eminent teacher who is willing to teach in a small hamlet.
- Once a substitute is found by the king, you will be sentenced to die.
- He grew angry as he found his wife viewed him as a substitute for her ex-boyfriend.
broadly [ˈbrɔdli]: adv. in a general way, relating to the main facts rather than details大体上
- I deserve a warm welcome as I was going about our house chores broadly.
- Broadly a glimmer of light couldn't affect the outcome of the experiment.
- Broadly our master groups cats under livestock.
clash [klæʃ]: n. if two armies, groups etc clash, they start fighting – used in news reports冲突
- The king is going about the clash of the two clans.
- The clash of the two box-fighters punched a hole by accident in the chimney.
- At last, the policeman broke free from the clash of the two hamlets.
systematize [ˈsɪstəməˌtaɪz]: v. to put facts, numbers, ideas etc into a particular order系统化
- Sticking with research for minds, the psychologist succeeded in systematizing his theory.
- Grappling with the question of mental health, he systematized a series of treatments.
- He proposed a way of systematizing the management of those entrepreneurs.
betray [bɪˈtreɪ]: v. to be disloyal to someone who trusts you, so that they are harmed or upset出卖, 背叛
- A sequence of things shows evidence of his betraying you.
- God's blessing, only a tiny fraction of our people betrayed us at the war.
- Master, I have no approach to betraying you under certain circumstances.
deter [dɪˈtɜr]: v. to stop someone from doing something, by making them realize it will be difficult or have bad results ⇨ deterrent阻止
- Nowadays, the authorities are deterring young people from parading in public.
- An initial population of cats deterred these rats from overflowing the warehouse.
- A new generation of products invented by the company deters customers from choosing another brand.
evaluate [ɪˈvæljuˌeɪt]: v. to judge how good, useful, or successful something is SYN assess评价,评估
- It doesn't make any meaning of evaluating the products that have been weeded out.
- Evaluating the presence of artificial intelligence has become popular with people in China.
- The jury may still be out, it's hard to evaluate the value of artificial intelligence.
downright [ˈdaʊnˌraɪt]: adv. used to emphasize that something is completely bad or untrue彻底地
- The outcome of the new AI model downright blew my mind and led to my thinking of my future career.
- He was downright scared of the horror movie that you presented him yesterday.
- The horror movie downright scares the hell out of me.
repellent [rɪˈpelənt]: adj. very unpleasant ⇨ repulsive排斥的
- What the repellent man did send shivers down my spine.
- Due to the instructions from my superior, I have to resort to the repellent colleague.
- Your repellent teacher is not your ground for your playing truant from school.
tidy [ˈtaɪdi]: adj. a tidy mind British English if someone has a tidy mind, the way they think is very organized and clear整洁的, 精简的
- I picked up the cotton for you day in and day out, and what I requested is only a tidy bed to rest on.
- As disgusting as it may sound, we have to make the toilet tidy before dusk.
- The dog will make the floor tidy, he is fed off of the infant's poop.
sensual [ˈsenʃuəl]: adj. relating to the feelings of your body rather than your mind感觉的
- His pursuit of sensual pleasure and vanity is without limit.
- His pursuit of sensual pleasure led to a sequence of catastrophes.
- The poor boy who lost his mother in his three-years-old tended to repress his desires of sensual pleasure.
outrageous outrageously [aʊtˈreɪdʒəs]: adj.adv. very shocking and extremely unfair or offensive骇人的,残暴的
- The garrison has no ability to resist the outrageous attack from the mobs. 
- What servants suffered in the South is outrageous.
- When you hear some news outrageous, you'd better look for its source and credibility.
pragmatic pragmatically [præɡˈmætɪk]: adj.adv. dealing with problems in a sensible practical way instead of strictly following a set of ideas ⇨ dogmatic务实的
- The official regarded as pragmatic rose to power and set up a series of laws prohibiting some traditional rituals.
- My manager is so pragmatic that he has never asked me to do anything useless.
- If you pragmatically deliberated at length over the project, you wouldn't stick to your plan.
repress [rɪˈpres]: v. to stop yourself from doing something you want to do抑制
- I did try to repress my sadness in front of my family, but in an outrageous manner.
- Worrying about being judged, I repressed my desire for food in my childhood.
- After I was judged by my grandfather I began to repress my desires for food.
master [ˈmæstər]: n. man with authority主人
- No one shall betray our good master.
- Because they spread the writing contrary to the holy church, the masters of orchards were gathered around waiting for the Inquisition.
- Under certain circumstances, even a good master had to beat his slave in front of others.
raging [ˈreɪdʒɪŋ]: adj. very great and hard to control强烈的
- The president had a raging appetite at the party when he was surrounded by those pretty girls.
- The president was said to have a raging sexual desire for underage girls.
- You can't communicate with anyone who is in a raging temper.
prohibit [proʊˈhɪbɪt] prohibition: v.n. an order stopping something(法令)禁止
- Because of the alcohol prohibition, there are a lot of gangs in the blocks.
- As an official working for the government, you should be aware that the king prohibited any shows in the subway.
- With foreign enterprises prohibited, we are facing economic depression when our neighbors are thriving.
prejudice [ˈpredʒədɪs]: n. an unreasonable dislike and distrust of people who are different from you in some way, especially because of their race, sex, religion etc – used to show disapproval偏见
- Your prejudice makes us find you repellent.
- We shouldn't invite a man full of prejudice to our party who is hardwired to break down our atmosphere.
- The authorities lost no time in prohibiting the spread of the writing full of prejudice about plantations.
filthy [ˈfɪlθi]: very dirty污秽的
- Due to the lack of raw sewage the town is not as filthy as before.
- Our cousin rated our room filthy, whose room is full of rubbish.
- Every piece of our room's floor is full of filthy vomiting.
trickle [ˈtrɪk(ə)l]: v. if liquid trickles somewhere, it flows slowly in drops or in a thin stream流淌
- The stream from the mountain trickling into the river became larger.
- With a knife stabbing in his arm, the red blood is trickling down it.
- The little stream from the tap is trickling, which gives me a sense of quietness.
submerge [səbˈmɜr(r)dʒ] submerged: v.adj. to cover something completely with water or another liquid淹没
- In my childhood, after I woke up I often found my house submerged because of a storm.
- Fearing that our house would be submerged because of rain, my grandfather laid a high foundation for the house.
- All of the fields in our village have been submerged, and you can barely recognize the river.
--------------------
rise to power: 上台
- People in China often cherish the wish that an eminent official will rise to power and improve their lives. 
- The president who rose to power last week set up a series of laws prohibiting any alcoholic beverage.
- No matter who rises to power, do your own business.
sb. infers that + ... [ɪnˈfɜr]: 某人推断+...
- I infer that our cat has been fed by our three-year-old son.
- She inferred that her husband was having an affair with his prior girlfriend at the university.
- My wife inferred that the couple who quarreled bitterly on TV didn't get a divorce after this.
turn to sb.: 向某人寻求帮助
- You should turn to your father who is willing to get you out of trouble.
- I must turn to my manager who asked me to follow his instructions.
- No matter who you are to turn to, you should try it single-handedly.
common sense: 常识
- It is common sense that every man is blessed with a dick.
- It is common sense that the price of real estate is dependent on the market, not on your will.
- It is common sense that the two villages have been hostile to each other for twenty years.
scream at sb. [skrim]: 朝某人尖叫
- It is your punishment, for you screamed at a holy priest in the church.
- When his wife screamed at him again, he lost his temper and attacked his wife.
- I am guilty, what I have done led to a lady screaming at me in the street.
get back at sb.: 向某人复仇
- My cousin got married to a poor boy so that she could get back at her family who neglected her.
- It was a father who got back at those who hurt his precious son.
- In case she gets back at us, we must pay attention to her imprisonment.
without sb's awareness: 在某人不知情下
- I fetched my pocket money from my father without his awareness.
- When I was wandering in the village fair, I was robbed almost without my awareness.
- My cat fell in love with our child with our awareness.
have no awareness of sth./doing sth.: 对某事和做某事无意识
- I have no awareness of taking a pencil from the supermarket.
- She claimed that she had no awareness of breaking down the atmosphere.
- My father told me that he had no awareness of what he had done in his condition.
sth. slips sb's mind: 某人忘记了某事
- Sadly, my best friend's birthday slipped my mind, which gave me a sense of guilt.
- The anniversary slipped my mind, which led to our raging quarrel.
- Don't let the date of the interview slip your mind.
reconcile A with B [ˈrekənˌsaɪl]: 调和A与B
- My grandfather punished us without judgment to reconcile my cousin with me.
- What will happen next is a policeman who tries to reconcile you with the butcher.
- No matter what happens, don't try to reconcile me with him, who made such stupid remarks.
