#+OPTIONS: \n:t num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

*** Unrepresentative Data

Definition Drawing a conclusion based on data from an unrepresentative or biased sample.

Unrepresentative data are data that are not proportionately drawn from all relevant subclasses. For example, if one wished to generalize about the opinion of the American people on a particular issue, it would be necessary to consider data proportionately drawn from subclasses based on race, age, educational status, sex, geographical area, and perhaps even religion and political affiliation. In most cases, data from other subclasses, such as body weight and hair color, would not be relevant.

It is also important to avoid using data that may be biased. This can occur in at least three ways. First, the data collected may be tainted by virtue of the bias of the gatherer. Opinion data gathered by a political party or by an advocacy group should be immediately suspect. Second, data purporting to support claims about any matter are biased if collected from only one or a few subgroups of the target population, especially if data are collected from groups that might have strong positive or negative opinions about the matter at issue. For example, if one were interested in assessing campus opinions about college athletics, one should not survey just members of intercollegiate athletic teams. Neither should one survey just nonathletes. If you were interested in the quality of a recent film release, you should not form a judgment exclusively on the basis of evaluations collected from readers of a single magazine, since its subscribers are a subgroup with special interests and tastes. Third, you should not give much credence to the call-in or email polls frequently taken by networks, newspapers, and magazines these days. If you want to know what “the American people” think about a particular issue, go find a reputable poll that is based on the careful surveying of representative groups.

Another kind of unrepresentative data might be data of differing quality. If one compared statistics gathered with modern techniques of statistical reporting and analysis with statistics gathered under very different methodological and technical conditions, almost any conclusion would be highly questionable. For example, if one were to compare statistics on the number of violent crimes committed in the United States in 2007 with statistics about similar phenomena in 1947, the comparative conclusion would be quite suspect.

EXAMPLE “It has been concluded from a recent study involving more than one hundred thousand people in the state of Florida that 43 percent of the American people now spend at least two hours a day in some form of recreational activity.” A reconstruction of this argument in standard form clearly reveals the statistical flaw: 

Since 43 percent of Florida residents spend at least two hours a day in some form of recreational activity, (premise)
[and the people of Florida are representative of all other Americans,] (implicit premise)
Therefore, 43 percent of all Americans spend at least two hours a day in some form of recreational activity. (conclusion)

To draw such a conclusion about the leisure-time activities of all American people would not be warranted. The state of Florida is populated by a disproportionate number of retired and leisure-oriented people, so data based on a Florida population alone would be unrepresentative.

EXAMPLE “We had a mock election on campus today, and the Democratic candidate won. So I’m pretty confident that she will win the election in November, especially because more than two thousand students voted. That seems to be a big enough sample. Don’t you agree?”

A college population hardly qualifies as a representative sample of voters, even if the size of the sample is actually larger than the number usually polled by sophisticated polling organizations. If a sample is not drawn from relevant representative subclasses, its size is of no consequence.

EXAMPLE “A recent study of how Americans spend their vacations revealed that 52 percent of the people spend five or more days a year at ocean beaches.” This study was based on a sample of fifty thousand Virginians, drawn from every relevant subgroup of the population, but it is hardly representative. Most areas of Virginia are close to popular beaches within the state as well as in Maryland and North and South Carolina. For that reason, a disproportionate number of the residents of Virginia, when compared with people from many other states, vacation at the beach.

ATTACKING THE FALLACY
Suggestions for responding to arguers who use unrepresentative data are similar to those for dealing with arguers who use too small a sample. If you encounter a case in which someone has used suspect data, you might expose the flawed statistical assumption by making it part of a similar argument with an absurd conclusion. For example:

Since most of the one thousand people in attendance at the county dog show own dogs, (premise)
[and what is true of the people at the dog show is true of the entire population,] (implicit premise)
Therefore, most people own dogs.(conclusion)
If the arguer sees nothing wrong with the second premise, no attack against unrepresentative data may turn out to be very successful, but you might try one other strategy. Threaten the arguer with the possibility of your gathering another set of data of the same size from people living in local nursing homes as support for a claim that most people do not own dogs. If samples of equal size can support two contradictory conclusions, it should be clear that something must be wrong with the representative quality of the data.

*** Arguing From Ignorance
Definition Arguing for the truth (or falsity) of a claim because there is no
evidence or proof to the contrary or because of the inability or refusal of an
opponent to present convincing evidence to the contrary.

Arguing from ignorance is a tactic many people use to defend some of their favorite
beliefs. In the case of a positive belief, they simply point out that since a claim has
not been disproved, it must be true. Or in the case of a negative claim, they argue
that since the claim has not been proved, it is false. Those who argue in this way
base their argument not on knowledge but on ignorance, a lack of knowledge.
The principle of sufficiency, however, makes it clear that the absence of evidence
against a claim does not constitute sufficient evidence for it and the lack of evidence
for a claim does not constitute sufficient evidence against it.

Arguing from ignorance also violates the principle that the burden of proof for
any claim generally rests on the person who sets forth the claim. For example, if an
arguer claimed that “ghosts exist, unless you can prove that they don’t,” he or she
is attempting to shift the burden of proof to another person, usually to someone
who is dubious about the claim. This is typically done by insisting that those who
are unconvinced of the truth of the arguer’s claim have the responsibility to disprove it or to provide support for the contradictory claim. If the doubters don’t accept that responsibility, the arguer fallaciously assumes that no proof is needed for
the claim at issue. But proof is needed. An argument that employs an appeal to the
“evidence” of no evidence does not satisfy the sufficiency criterion of a good
argument.

There are some situations of inquiry in which this kind of reasoning seems to
be acceptable. In our judicial procedure, for example, a defendant is assumed to
be innocent unless proven guilty. But this is not a case of arguing from ignorance.
The principle of innocent until proven guilty is a highly technical judicial construct
that actually means not proven guilty. It does not mean that the person is innocent;
it simply means that a defendant is not deemed to be guilty unless he or she is
proven guilty.

The fallacy of arguing from ignorance probably gains some of its deceptive appearance as a good argument from its similarity to a legitimate way of arguing. For
example, suppose that I claimed that there were termites in my house. If a professional termite inspection revealed no evidence to support the claim, however, it
would then be justifiable for me to conclude that there are no termites in the house.
This sounds like a case of arguing from ignorance because the lack of evidence for a
claim (“there are termites”) is used as evidence that the claim is false (“there are no
termites”), but there is a crucial difference in this case. The negative claim is based
not on a lack of evidence, but on a thorough assessment of all of the positive and
negative evidence relevant to the question of whether there are termites in the
house.


EXAMPLE “What’s all this business about equal pay for women? The women who
work in my office must be satisfied with their salaries, because not one of them has
ever complained or asked for a raise.” A reconstruction of this argument in standard form will clearly reveal the faulty implicit premise:

Since the women in my office do not complain about receiving less pay than
their male counterparts, (premise)
[and where there is no expression of dissatisfaction, there is no dissatisfaction,]
(implicit premise)
[because the lack of evidence against satisfaction is evidence for satisfaction,]
(implicit subpremise)
Therefore, the women in my office are quite satisfied with receiving less pay
than the men in the office. (conclusion)

The arguer assumes that the situation of a group of people must be satisfactory simply because no complaints about that situation have been expressed. In other
words, the absence of evidence against the satisfactory character of a situation is
regarded as evidence for the satisfactory character of that situation. Making such
an inference is so distinctive a form of the fallacy of arguing from ignorance that
it is often given a separate name—the fallacy of quietism. But from the fact that a
person or group is “quiet”—that is, makes no complaint—one could not infer that
there is nothing to complain about. There may indeed be many good reasons why
the complaints are not openly voiced.

EXAMPLE “Since my opponent has not clearly indicated his opposition to the new
federal gun-control bill, he obviously is in favor of it.” The only “evidence” offered
in support of such a claim is the fact that the opponent has not addressed the issue.
Interestingly, the arguer could have defended the opposite claim with the same evidence: “Since my opponent has not clearly indicated his support for the new federal gun-control bill, he obviously is opposed to it.” Any evidence that could lead
to either a positive or negative conclusion with equal strength cannot be sufficient
grounds for one of the conclusions.

EXAMPLE “I didn’t see any ‘No Trespassing’ sign, so I assumed that it was alright
to walk through the field.” The fact that there is no sign indicating that an act is
not permissible does not entitle one to assume that the act is permissible.

EXAMPLE
CONNIE: Did you get that teaching job at the University of North Carolina at Chapel
Hill?
DOT: No. I sent in my application more than two months ago, and I never heard a word
from them.

Dot is assuming that the university has rejected her job application because there is
no evidence that she has been accepted. However, she could have just as easily argued from ignorance for the opposite claim—that she has been accepted because
there is no evidence that she has been rejected. Neither inference should be drawn,
however, because it would be inappropriate to conclude anything on the basis of
no communication from the university, especially in view of the fact that the institutional procedure required for filling a teaching position is usually a very long and
complex one.

ATTACKING THE FALLACY If the absence of proof against a claim could be regarded
as proof that it is true, then even the most bizarre of claims could be construed as
true. Moreover, if a claim were so absurd or trivial that others never bothered to
address it, a defender of such a claim would always win by default.

If an arguer makes what you consider to be a highly questionable claim and
supports it by pointing out the lack of evidence against it, try playing the same
game. You could demonstrate the faulty character of that kind of reasoning by
making the opposite of the arguer’s claim and supporting it with the same method
that he or she used. For example, suppose that someone claims that because psychokinesis has not been proved false, it must be true. You could then argue that
because psychokinesis has not been proved true, it must be false. Your opponent
should then be able to see that such reasoning would lead to the contradictory conclusion that psychokinesis is both true and false.

** Special Pleading
Definition: Applying principles, rules, or criteria to another person while failing or refusing to apply them to oneself or to a situation that is of personal interest, without providing sufficient evidence to support such an exception.

Special pleading occurs in a context in which it is assumed or understood that a rule, principle, or law applies to all people alike. The special pleader usually accepts the principle but wishes to make himself or herself or another an exception to it. What makes special pleading a fallacy that violates the criterion of sufficiency is the fact that no evidence is provided for making that exception. While special treatment may sometimes be called for, it is always the case that the action of treating differently what appear to be similar cases must be justified.

EXAMPLE:
Neel claims that he is too tired to share in the chores of cooking, cleaning, or caring for the children after working all day. If he claims that his wife should do those domestic jobs, even though she, too, is tired from her full-time job outside the home, he is engaged in special pleading. Let us look at this argument in standard form:

Since I work hard all day and am tired at the end of the day, (premise)
and you work hard all day and are tired at the end of the day, (premise)
[and the governing principle in such a situation is that each partner should share in the domestic chores,] (implicit premise)
[and the principle applies to you but not to me,] (implicit premise)
Therefore, you should do all the domestic chores. (conclusion)

Being tired from a full day’s work outside the home presumably excuses Neel from domestic chores, while it apparently does not excuse his wife. He is applying a principle to his wife that he is not willing to apply to himself, and, as can be clearly seen, he has presented no evidence for making that exception.

EXAMPLE:
Sometimes we make a special case of ourselves through a subtle use of language: “I am confident, you are arrogant; I am aggressive, you are ruthless; I am thrifty, you are cheap; I am frank, you are rude; I am flexible, you are inconsistent; I am clever, you are conniving; I am thorough, you are picky; I am curious, you are nosy; I am excited, you are hysterical; I am firm, you are pig-headed; I am friendly, you are flirtatious; and I am a free spirit, you take license.”

But if the behaviors in these cases are the same, how can we justify assessing
our own behavior positively and another’s negatively, without being inconsistent?
When charged with inconsistency, special pleaders often respond with, “Well, this
is different!” But if they cannot convincingly make the distinction stick, they are
clearly guilty of special pleading.

EXAMPLE:
Jessie and Katrina are college roommates. Let us imagine them engaged in the following conversation:

JESSIE: Would you please turn off your music? I want to take a nap.
KATRINA: This is my room, too. I want to listen to this new CD I just got in the mail.
JESSIE: Listen to it some other time. I want to take a nap.

The principle that most roommates accept is that one’s interest is not more important than the other’s, but Jessie is implicitly claiming that her interest is more important than Katrina’s. Most of us would probably agree that Jessie is engaged in special pleading because she gives no convincing reason why her interest should have a priority status. We are not saying that there is no way to resolve this or other similar issues; we are simply saying that in this particular exchange, Jessie is guilty of special pleading.

*** ATTACKING THE FALLACY
An attack that is most effective is to accuse your specialpleading opponent of applying a double standard or being inconsistent. Each of these charges is commonly understood outside logical circles and has strong negative connotations with which the arguer will not want to be associated. But you will need to explain carefully how you think the double standard has been employed and to scrutinize carefully any defense your opponent may make against the charge.

Some situations may call for making oneself a special case, but these are rare, so the careful thinker should always be suspicious of any preferential treatment claim. Ask the arguer to spell out the reasons why some people should be treated differently from others or why the principle should not apply in his or her particular case. The arguer, of course, will almost always have some kind of reason; the question is whether that reason is sufficient to support the preferential treatment desired. For the hard-to-convince, try an absurd counterexample:

Since the law with regard to the payment of income tax should be applied in all cases, (premise)
and I am an exception because my case is not like that of others, for I need that money for other things, (premise)
Therefore, the income tax law should not be applied to me. (conclusion)

The second premise should sound absurd to even the most inveterate special pleader, and the arguer should be prepared to show why the special treatment he or she is requesting is not equally absurd.
