* Thinking in English

** sherwin
Why should I think in English?
Thinking in English a key point
	to move from being intermediate to upper-intermediate, advanced and native speaker level.

*** daily routine:
1. reading time everyday
	 - repeat after audios
	 - review
2. while leaving home until arriving at work
	 - watch English books
3. spare time at work
	 - finish red cover books
	 - write essays
	 - read actively or just for fun
	 - review
4. spare time while waitting a bus and so on
	 - read books
	 - watch dramas, movies
	 - describe something around you in English
	 - publish moment
5. golden time
	 - learn NCE course
	 - learn intensive course
	 - talk to foreigner teachers
6. short time before sleeping
	 - watch youtube, read book and so on
	 - thinking exercise

*** somethings that I must obey
1. Don't use Chinese in short time before sleeping
2. stop translating while learning new concepts
	 - just google the new concept and go to images without translating it while learning it

*** do as best as I can:
1. Do fun stuff in English as much as possible
2. learn new concept in English straightaway
3. switch everything around you in English as possible as you can
4. thinking exercise

*** exercises
1. make sentences

** Leo
精读：上nce课；造句； 红皮书；重复间隔；
精听：跟读；nce电影片段
泛读：不求甚解地看书； 带着问题去找答案地看书；
泛听：电影；电视剧；广播；音乐；
写作：随意写点东西，比如朋友圈发点英文想法；以某个主题去搞素材，形成论证，比如雅思作文和topic For Disscussion.
口语：沉浸对话课程；对周边事物尝试用英语描述；hellotalk找母语者对话

我把这些事情分了什么时间做，以及按顺序排优先级（实在不想干某个事就换一下）。
工作划水时间：
       红皮书补全；作文写作；带问题泛读；重复间隔；不求甚解泛读

黄金时间（晚餐后直到休息前）：
      上nce；沉浸对话课程；hellotalk找外教

早中晚跟读时间：
       跟读；重复间隔

碎片时间：
       听美剧、看电影、电视剧；时不时用英语描述周边事物；发朋友圈

** linguamarina
So, thinking in English is a key thing for you
	to move *from being intermediate to upper-intermediate, advanced and native speaker level*.

I went to bed thinking in English, and I had a dream in English,
	and I woke up in the morning, and I realized I'm actually thinking in English.

rules for keeping thinking in English:
	1. travel to an English-speaking country.
	2. From now on I will only do fun stuff in English. YouTube video, Instagram, English books.
	3. learn the concept in English straightaway
	4. When you're learning a new concept you get rid of translation.
		 1. if you want to read more about photography or if you want to read more about filmmaking,
					blogging, do that in English.
		 2. if you encounter a new concept, you just Google it, you go to images,
					 and you read what that word means without translating it.
	5. Switch your phone, your smartphone, your laptop, to English.

** Luck's English mind
English brain is your ability to think in English while speaking English.

*** tips
Keep in mind:
	1. Learning something is often not enough, you have to learn and apply it.
		  Practice it many times.
	2. If you don't learn to think in English, you won't be fluent.
			This is the only way to be a fluent English speaker.
	3. Time doesn't equal success.
			You may spend a lot of doing wrong things.
three actions
	1. play: think creatively
	2. jump: without any reservations
	3. swim: immerse
daily routines:
	1. 30 minutes
	2. feedback AI
	3. lifestyle: enjoy it

*** reading
1. guess means of word in context
2. look up word by using all English dictionary

*** how to learn new words
1. guess means of word in context
2. learn all of the forms
3. learn in the context
4. make sentences

*** how to learn idioms
1. what it means
2. where to use it
3. who to use it

*** 4-word exercises

*** Variations
An example of variations of a sentence:
	origin: I think it might take a few days for me to help you book your tickets.
	v1: I think I can have your tickets booked in a few days.
	v2: Give me a few days to book your tickets.
	v3: I can reserve your tickets if you like, but it might take a few days.
	v4: If you give me a few days, I can book your tickets.

*** Full-Variations
A variation of a full paragraph.

*** listening exercise
1. Listen to a mp3 which you need to only understand 20-30% again and again.
2. 1 minutes

*** Thinking exercise


