#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Attacking Faulty Reasoning

** introduction
*** studying a little logic
Critical thinking: a process, the goal of which is to make reasonable decisions
	about what to believe and what to do.
Learn not only the methods of recognizing bad arguments but also how to build good.

*** organization of the text
4 chapters, which describe the nature of a good argument
5 major chapters describing specific fallacies
final chapter, which describes writting a logical essay.

It's difficult to know when to end discussion of an issue
	and make a decision about what to do or believe.
*Five criteria of a good argument* will solve it.

*** reasons for using good arguments

*** goals of the text

** Chapter 1 A Code of Intellectual Conduct
This chapter should help you to:
	discuss with others rationally, find your own fallibility, avoid linguistic confusion.

Understand "code of conduct", which represents two standards of behavior:
	a procedural and an ethical standard.

*** An Effective Procedural Standard
A proceduarl standard describes the ground rules that,
	when followed, often lead us to more successful resolution of issues,
	which is productive in settling disputes, confirming judgements, and revising beliefs.

In the discussion of the "Code of Intellectual Conduct",
	the evolved consensus position is rarely one of the two original positions;
	it's usally a "third" and better one.

*** An Important Ethical Standard
The ethical standard makes us argue fairly.
If we don't, it prevents the issue from being decided or at least further explored.

*** A Code of Intellectual Conduct for Effective Discussion
In the "discussion", you should make the following principles a part of your intellectual style.

**** 1. The Fallibility Principle
Be willing to accept the fact that he or she is fallible,
	his or her initial view may not be the most defensible position on the question.

**** 2. The Truth-Seeking Principle
Each participant should search for the truth or the most defensible position
	so that everyone should examine alternative positions seriously and allow other to do so.

**** 3. The Clarity Principle
Avoid linguistic confusion and separate from other positions and issues.

**** 4. The Burden-of-Proof Principle
Not anyone but the proponent should provide an argument for his position when someone asks.

**** 5. The Principle of Charity
If an opponent's argument is reformulated, it should be expressed consitently.
And the paritcipant should be given the opportunity to amend it.

**** 6. The Structural Principle
An argument made by anticipants
	needs to meet the fundamental structural requirements of a well-formed argument.

**** 7. The Relevance Principle
The reasons you prvoides should be relevant to the conclusion.

**** 8. The Acceptability Principle
Reasons should be accepted by a mature, rational person
	and meet standard criteria of acceptability.

**** 9. The Sufficiency Principle
Reasons should be suffcient in number and weight to support the conclusion. 

**** 10. The Rebuttal Principle
One who provide an argument should rebut all serious criticism of the argument.

**** 11. The Suspension-of-Judgement Principle
If there is no position defended by a good argument or two or more positions by equal strength,
	suspend judgment about the issue.

**** 12. The Resolution Principle
When an argument is a structurally sound one
	that uses relevant and acceptable reasons
		that together provide sufficient grounds to justify the conclusion
		and that also includes an effective rebuttal to all serious criticisms.

*** The Fallibility Principle
One's own initial view may not be very defensible so that he or she is fallible.

Accepting your own fallibility mans that you are willing to change your mind.

It's a neccessary condition of intellectual progress,
	making progresses among scientists, philosophers, and most other academics,
	however making so little progress in religion and politics.

If there is any doubt about the principle,
	choose an issue about which people hold conflicting opinions.

We think a position which we spent time developing and refining is defensible,
	so others think.

It not only calms the emotional waters surrounding the issues,
	but also it has the potential for opening our ears to different and better arguments.

Try to be the first to confess your own fallibility,
	your opponents' behavior will tell you that whether he is willing to have further conversation.

Even a critical thinker only have changed his mind about an important issue once in the past year.
It's more likely a person would turn out to be wrong on more issues than right.

*** The Truth-Seeking Principle
-

We come to true knowledge only by frist recognizing our own ignorance or lack of knowledge,
	so we must condsider criticism of our own views in discussion.

The truth is not likely to be in our custody,
	but is the most defensible position supported by the strongest or best available argument.

To find out truth, we need not only to assume that we may not have the truth now
	but to listen to arguments for alternative positions and encourage criticism of our arguments.

After having done the hard work of investigation,
	we should not give the impression that we have an open mind about the issue
		and carry on a pseudo-discussion.
We could explain that to our opponent
	or join the debate when we think we might have missed something.

Because of hope of winning, we sometimes cheat to do it.
The truth comes at a price
	-- a willingness to look at all available options and the arguments in support of them.

Not try to win by ignoring or denying the counterevidence against your positions.

*** The Clarity Principle
-

Even if we think what we say is perfectly clear to ourselves,
	it may be confusing, vague, ambiguous, or contradictory to others.

We must usually deal with one feature at a time
	so that each party must pay attention
		to keep other interesting issues, related issues from clouding the discussion.

We must not falter the potential resolution of an issue because of verbal confusion.

*** Assignments
1. Discuss some of the obstacles of adopting the "Code of Conduct for Effective Discussion"
		as a means of resolving conflicts in our practical lives.
	 For example, why do you think good arguments so rarely seem to change minds?

	 We have deep emotions on our original minds
		so that we don't want to change them, even if we listened to a better argument.
	 Sometimes if we change our minds, others will think that we are weak or often make mistakes,
		which leads to the decline in status in society.

2. Do you agree that failure to follow the Code of Intellectual Conduct in discussion
		may be immoral?
	 Why or why not?

	 Yes, I do.
	 If others in discussion follow the code but you don't,
		they will make little progresses because of your failure.
	 They will receive less than they should be, may get frustrated.

3. Why is it inappropriate to continue in a serious discussion
		if you are not open to the possibility of changing your mind?

	 If you're not open to the possibility of changing your mind,
		there might be the emotional waters surrounding the issues
		and you won't open your ears to different and better arguments.

4. Are you a critical thinker?
	 If so, describe an occasion wherein you changed your position
		by force of argument on an important issue in the past twelve months.

	 I am probably a critical thinker in some aspect.
	 I used to insist that the tasks which my boss order should be done only in my way.
	 I changed my mind when I began to listen to other opinions,
		in which I learnt my own view is not the best way to solve problems.
	 It really makes me a better programmer and makes me get along with my colleagues better.
		 

5. The next time you are in a heated and unresolved discussion on an important issue,
		stop and confess that your position may be wrong.
	 If the other participants do not follow suit,
		ask them whether they are also open to the possibility of being wrong.

	 Ok, I will try it the next time when I discuss the tasks with my colleagues.

6. It has been claimed that an argument for a position is not a good one
		until the arguer has effectively rebutted anticipated serious criticisms
			that might be brought against it.
	 Since following this advice would call attention to flaws in your own argument,
		do you think this would tend to weaken it or the position it supports?
	 Why or Why not?

	 No, I don't.
	 Whether my argument or his is the most defensible is not a big deal to me.
	 Before being a winner, I'm a truth-seeker.
	 Therefore, it's more important to seek truth than to win.
	 Thanks to following this advice, it will help me to seek more defensible opinion better.


