* Chapter 6 Fallacies That Violate the Relevance Criterion
- 用你自己的话描述不相干谬误
- 发现,叫得出名,解释谬误的形式,当辩论或生活遇到的时候
- 用有效的策略去帮助别人纠正他们的不相干谬误
(1) fallacies of irrelevant premise
(2) fallacies of irrelevant appeal.

公输般

英国护卫

--------------------
- 用自己的话描述下那些违背相干性原则的谬误
- 在生活和辩论中遇到的时候,遇到了能辨识,叫得出名字,能够解释谬误的形式.
- 用有效的策略帮助别人纠正他们的不相干谬误

论证要有相干的证据.

两类不相干谬误,一种是用不相干的前提,另外一种是各种诉诸.

1. 不相干前提
   从前提推导不出结论:前提和结论没联系,或者前提到结论有跳跃性.
2. 诉诸
   
** Fallacies of Irrelevant Premise
1. 根据旧的情况推断新的事物,无视环境已经发生了变化
2. 用看似有理的原因而不是真正的原因去隐藏掉真实的想法和行为
3. 对理由去做另一番解释,目的是为了得出结论.
4. 为了得出结论,而去编造理由.
 
** Genetic Fallacy
用过去的context去计算现在的事情,无视新旧之间已经发生了变化
wusd: 刻舟求剑

只考虑事情一开始是怎样的,因而忽视了事物的发展,退化,差异.
wusd: 要用发展的眼光看待问题,
什么人容易犯呢?
  1. 把过去看事物的老眼光:或积极或消极,用在现在了
     wusd:
			吴下阿蒙.
		  小米就是钓丝低端的,所以小米su7我完全不考虑买.
			我们经常会根据很久的经历去判断一个人现在到底怎么样,并且这种想法很难改变.
				比如人际交往,第一次如果留下坏印象了,后面就很难再改变看法.
  2. 一些宗教啊,根据原始教义不许做某事,但是到如今已经发生了变化了.
     wusd: 回族人不允许吃猪肉,原本是当时卫生不达标,猪肉脏,吃了易得病. 但是现在科学化养殖,仍然还是禁止吃猪肉.

这种谬误的模式就是:
  前提和结论是要相干的.现在的结论虽然和以前的前提相干,但是前提已经发生了变化,变得不相干了.

EXAMPLE:
	我不会给Don Reichard投任何票,我和他同学的时候,他在学校里完全就是个混子.
	实际上,Don有可能变成熟了,变成了和原先完全不一样的人.
	wusd: 对应了第一种例子.用老眼光看人.那我们同样也不应该用老眼光去看自己.
		因为Don在上学期间是混日子的.(P)
		上学混日子,当官员时会一直混日子(IP)
		所以Don在当官员时同样会混日子.(C)
EXAMPLE:
	因为结婚戒指原本是丈夫用来束缚他们妻子的标识(P)
	而且这个标识会一直做同样的事情(IP)
	这种行为实施了性虐待(P)
	所以,现在谁还用结婚戒指也是实施性虐待(C)

wusd: 这里讲的例子,是有可能变化,但是也有可能没变.所以对于Don能不能胜任官员,需要继续调查.
	对于结婚戒指实施性虐待需要更深入的统计数据
EXAMPLE:
	虽然我听说李医生是一个很帮的医生.但是我不会去李医生那里看病,我跟他同学的时候,他一直看黄片.
	wusd: 虽然吴教授是一个优秀的导师,但是我不会报考他的研究生,因为他以前上学时经常打架斗殴.

ATTACKING THE FALLACY
这些固有印象连接我们的思想,会在我们考虑的时候严重地影响我们对其的喜爱或厌恶.比如:让你去评价下前男友的装修和衣服.
但是当我们要深思熟虑的时候,就要想办法抵制这些因素的影响.
当辩手这么按这种方式想问题的时候,我们就可以反过来问他现在这事物有没有厌恶点或喜爱点.
wusd: 人是感情的动物,想要不受原本的固有印象影响去判断一件事非常困难,要想办法抵制掉这些因素的影响.
	当有人或者自己按这种方式考虑问题的时候,就可以反过来问下这件事当下有没有值得的点和厌恶点.

假如拥有长期亲密关系的伴侣,最开始的约会或见面却是场乌龙或恶作剧.
这对伴侣,肯定不会以最开始的价值来评价现在关系的价值.
如果能够搞清楚这种情况,自然能够正确处理其他事情.

你说林师傅是大厨,但是小时候他弄个馅饼都搞得乱七八糟的,所以我不会吃他做的任何食物.

** Rationalization

** Using The Wrong Reasons

