
* Chapter 5 Fallacies that violate the structural criterion

- 用自己的语言,能够描述出违反structural的谬误的重要性质
	解: 你说这个谬误叫argue in a circle,最重要的性质是 前提和结论实际是一回事,前提证明结论,结论又证明前提,所以叫循环论证
- 在实际讨论中能够识别,叫出名字,解释谬误的形式是啥样的
	解: 我们在讨论刘亦菲是不是美女, 然后有个sb一直称呼刘亦菲是女神,所以是美女;我们这时候要说他犯了Question-begging language.还要说明,我们正在刘亦菲是女神,已经暗含了刘亦菲是美女的假设.
- 能够采取有效的效率attack这些谬误
	解: 魔术, 我们知道了自己犯了肯定后件的谬误, 然后attacking, 去想其它方式导致结论的原因.比如,助手的下半身和魔术师的上半身.


- Begging-the-Question Fallacies
	assume the truth of the conclusion in their premises
	+ arguing in a Circle
		asserting in the premise what is asserted in the conclusion
	+ question-begging language
		by means of language assume a position on the very question
	+ complex question
		presuposes in a question that a definite answer had already been given
	+ question-beggin definition ?
		disguised as an irrefutable empirical premise
- Fallacies of Inconsistency
	premises are incomppatible with one another or conclusion contradicts one premise
	+ incompatible premises
		inconsistent or incompatible premises
	+ contradiction between premise and conclusion
		a conclusion is incompatible at least one of premises
- Fallacies of Deductive Inference (well-established)
	violate well-established rules of deductive logic
	+ denying the antecedent 否定前件
	+ affirming the consequent 肯定后件
	+ false conversion 错误转换
	+ undistributed middle term 无关中项
	+ illicit distribution of an end term ?
	
	
违反这条规则的三种谬误: 丐题~不一致~违反演绎法则.

犯这种谬误,结论无法necessarily or probably来自于premises, 我们会在例子里解释为啥.

之所以叫structural one,是因为犯的谬误跟premises和conclusion的内容无关.如果用符号代替,我们也能发现从premises推不到结论.
	解: structural fallacy, 直接从structure(把命题换成符号)就能判断推导不了结论.
		例: 我老婆说: 老公爱你. 我老婆又说: 老公我讨厌你. 得不到任何结论.
			换成符号就是 A, not-A, 不需要看内容,就知道得不到任何结论.

丐题在前提中预先假设了结论;不一致是前提们不一致 或 前提和结论不一致; 违反演绎法则(well-established 也违反了acceptability principle -D)

** beggin-the-question fallacies 丐题
arguing-in-a-circle fallacy: 把结论当作其中一个前提
quetsion-begging-language fallacy: 用语言的方式,在问题中假设和结论一致的position
complex-question fallacy: 
	假定已经有答案了,
	假设对错了,有争议的问题(比如Lisa什么时候生二胎 -D)
question-begging definition fallacy: 定义中结论已经对了

论证根据定义是,一个结论被其它(different)前提支持,丐题并没有其它前提, 所以结构就犯错了.

*** arguing in a circle
循环论证的定义: 或明或暗地在前提里面确定 需要在结论里面确定的事物.
	解: 强调的某个前提和结论一致

最常见的谬误, 把结论当作其中一个前提: 例如: 你对手宣称自己的position是对的,因为它就是对的.
	解: 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.

Since A, Therefore A

arguing in a circle在实际情况往往是暗示的.
	解: 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.
		这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.

通常arguing in a circle不会用相同words和form, 实际上识别是非常困难的.
这种谬误有时候贯穿文章,章节,甚至足足一本书, 就更难识别了.

一旦识别"A is true because A is ture",这种谬误就会无比明显.

EXAMPLE: 最容易遇到的就是换换同义词
	使用带有渎神和淫秽的书是不道德的, 因为对于孩子来说听下流肮脏丑陋的词是不好的.
	解: 这里主语 渎神和淫秽的书 是 下流...的词是近义词; 不道德的 和 不好 的词又是近义词.

EXAMPLE: 这个大学在学生政策上是专制的. 因为他们对待学生像孩子. 这里仅仅是解释了专制的定义.
	解: 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.

EXAMPLE: (循环论证还从subP可以传递-D)
	he does not have the background and ability to evaluate it properly(subP)
	is biased against modern music(P)
	is an incompetent music critic(C)
	subP and C are the same things.
	解: 领导说要开除你, 理由是你不称职, 因为你做事不合格所以你对工作理解的不到位,你对工作理解不到位所以你不称职.

**** ATTACKING THE FALLACY
要注意有没有前提等同于结论,或者前提暗里假设了结论的事实.

要注意辨别你对手可疑的多义的claim.
必要时,转换成标准的格式,这样甚至能清晰地看到premise和conclusion是怎么一样的.

给个明显反例或荒谬的反例.

用丐题的人会真心觉得自己说的对.但是必须被提醒的一点,个人相信的不能当作证据.

-DDD
arguing in a circle简单,但是却难以识别.
保持注意力,注意假设和前提是不是一样; 把argument改成标准的形式更容易发现这个谬误.
	1. 前提和结论同义词换一下,实际一个意思
	2. 你问他要原因的时候, 他给你把名词解释一下
	3. subpremises其实和结论是相同的, 多走了一步想掩盖这个事实.

*** Question-begging language
定义: 通过语言的方式在特殊的提问中假设了立场,引导听众得到相同的答案.
	解: 利用语言诱导听众得到某个结论, 强调的是引诱,并没有给出答案

有意或不小心地把 未得到解决的事情 预设成 已经得到解决了.
语言本身带偏向导致预设了结论, 因此应该用描述性和中立的语言.
	解: 有意或者无意地把本来没有处理好的事情 预设成 已经得到确认的事情.
		比如: 
			1. 法庭上,女方说男方一点都不管家里.男的说我每个月给家里寄8千,女的说这是生孩子的,这里必须的,你没资格说这个.
			2. 知乎上,电车难题. 有个回答说,谁把电车偏轨就是谋杀. 需要合并下.
			3. the leading question: 

带有偏向的语言并没有给证据,所以也不能产生acceptable结论.

第一种类型: 靠煽动性语言
EXAMPLE: Natalia在法庭上喊我戴绿帽了, 所以法庭应该认为我戴绿帽了.
	解: 教师汪康夫被告强奸12名幼女,判刑10年, 伸冤54年后受害者均否认被强奸.

第二种类型: 把刘亦菲称为女神
EXAMPLE: 议题是胎儿是不是算是人类,一个辩方一直称呼胎儿为婴儿.

第三种类型: 用反问的语气好像这件事已经有定论了.
EXAMPLE: leading question(引导性问题-D) 你不是认真投票Professor Reiff作为年度教师,是吧.
	解: 这里用这种反问的语气,实际上是假设了不应该投票给Professor Reiff, 但是又没有解释.
		比如领导吩咐下一件事情需要我和同事做. 我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?

**** ATTACKING THE FALLACY
发现这个人是否犯这个谬误,注意他的语言是否阻止issue变得开放.
辩手持续使用这些词是不道德的 像: 严重的,震惊的,无法饶恕的.
	解: 像我老婆跟我争执的时候,经常用一些形容词,说我怎么怎么过分,但实质的行为却没有说多少.这种就是阻止issue开放.

总之,不要被丐题语言迷惑, 尤其是什么 众所周转, 明显的. 可以天真的来一句: 对我来说并不明显.
	解:像那种明显的,10岁小孩都直到,傻子都晓得.
		我遇到过一次,领导拉大家一起讨论问题的时候,我对于某个问题不懂的,但是领导说明显的. 这实际对于我来说并不明显. 我就说:我脑子笨,这件事我还没搞懂,能不能再解释一遍.

面对leading-question, 要找到方法去揭示他正在让你保证的预设是issue的一部分.
当然,如果这些预设,在其他地方被充分,那么就不算谬误了.

-DDD
1. 用那些情感色彩强的词,比如我被cheated, 让原来开放的issue倒向一边
2. 众所周知的,而你并不知道.比如胎儿称之婴儿. 你可以来一句, 对我来说不是明显的.
3. leading-question. 问题中有和issue有关的假设. 比如: 你投票给Professor有没有认真?(假设了你投票给Professor) 但是注意,如果假设被证实了,又不是谬误了.


*** complex question 复杂问题?
定义: 问题中有给定答案的假设, 或者问题中认为一系列的子问题都有相同的答案.
	解:强调的是给出了答案,或者所有子问题答案一致

第一种类型:
丐题的原因就是因为问题中假设了事实(未确认).
偷了手表后,你怎么处理手表的?
	解: 老师逮住学生,问,你是用左手抽烟还是右手抽烟.

值得注意的,如果回答人默认问题中的假设,那么这就不是丐题了.
丐题仅仅是当问题涉及的issue还是开放的.

第二种类型: 问题中多个claim,一否全否,一肯全肯
你会带我回去,在路上让我从商店里面买东西吗?
在这个问题里,假设了要么全答应,要么全不答应.
同样的只有回答人认同这个假设,才不是丐题.
	解: 我老婆问我,你爱不爱我,愿不愿意给我买最新的江南布衣的衣服.这里她就犯了复杂问题的错误.

解析下两个例子:
 因为你偷了我的手表(P)
 所以你偷了我的手表(C)
 
 因为你带我家所有的情况你都会带我去商店(P)
 所以你带回家的所有情况你都会带我去商店(C)
 
EXAMPLE: 
	What fraternity are you going to pledge?这里假设了要参加社团
	When are you going to settle down and get married? 两个问题.
 
EXAMPLE: 哈哈, 一口气提7个问题, 第二种类型(-D)
	Are you and Nancy going to the Keller-Trent wedding and to the reception next Saturday, even though you and she were not invited?
	2的7次方, 128种回答.
	
EXAMPLE: 为什么叫丐题(因为回答者被提问者乞讨去确认假设的事实-D)
	为啥离婚父母的孩子更加情绪化不问题比那些未离异的家庭?

**** Attacking the Fallacy
怎么样attack complex question?
1. 拒绝给直接肯定或否定的回答给这种complex question.
	如果问问题的人不明白你的不愿意回答, 反问它: "你有没有停止偷税"(这个要给个中文版的-D)
	解: 你这个问题我无法回答. 在你偷了井盖之后,你是怎么处理井盖的?
2. 指出问题中有问题的假设,告之假设还没有决定.
	给保证: 虽然如此,我愿意任何时候聊这个假设.
	解: 你这么说,xxx还没有确认,正在讨论中, 等xxx确认了, 我再回答你这个问题.
3. 必要时坚持把问题切割,一个一个回答.
	解: 坚持分开回答问题. 老婆, 我是爱你的, 但是我不想给买江南布衣的衣服.

*** Question-Begging Definition
定义: 把定义伪装成无法证伪的经验假设
	解: 注意定义是他自己给的定义,还是公众的定义.忠诚的狗不会冲主人狂吠,如果它冲主人狂吠了,那它就不是忠诚的狗.
		重新定义忠诚的狗.

经验前提和定义前提很容易迷惑.
定义前提应该是共用术语或者权威人士的思想.
	解: 比如说信佛的人不杀生.如果他杀生,那么他就不是真正信佛的人.
		大家普遍认可的信佛的人是去寺庙里拜的人.
		定义的信佛的人是不杀生的人.

经验前提做观察性或事实性的断言.
他的可接受性取决于我们的经验,相关权威的测试,以及恰当实验的结果.

定义前提假设成了经验前提,就犯了这种谬误

两条线索去发现这个谬误
1. arguer拒绝接受他经验前提的反证据
	解: 信佛的人不杀生
2. issue中的关键属术语,一直用修饰性词: true, real, genuine
	解: 真正信佛的人不杀生. be defined in an unconventional way

EXAMPLE: (线索1和2, 加修饰词,丐题顶替 -D)
issue是讨论基督教人喝不喝酒.
有人说看到基督教人喝酒.
然后有辩手定义, 如果他喝酒,那他就不是一个真正的基督教.

EXAMPLE: 
真爱不会离婚或分手.
如果离婚或者分手那么就不是真爱.
Eric可以这样定义真爱,但是这种奇怪也就无法被理性人反驳,也就没有意义了.
解: 这种奇怪的定义已经无法反驳了,也就没有讨论的意义.
	比如有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?
		偷的话: 按经验定义,不告而拿, 孔乙己定义是非读书人的不告而拿.

EXAMPLE:
true-blue 共和党人是一个人,从不离开共和党人.
对是对的,但是这种断言属于定义前提,不属于经验前提.
解: 恋爱中的男女往往对真爱的定义有偏见.
	她真爱你,她就会对你不离不弃.

ATTACK THE FALLACY:
问arguer这是定义前提和经验前提,如果他被你问着了,解释下不同.
还可以问下有没有证据支持他的前提,如果没有,很可能是定义前提.
解: 这个xx是你自己的定义的,还是大家都这么认为或者专家给出的定义?
	你这么说xx是xxx, 有没有证据来支持这个呀?
	
	如果两问题都答不上来,那么就是定义前提.
要这么定义也可以, 解释下为什么不用其它的定义, 比如通用的和相关专家的定义.
发现是定义前提后, beggar要愿意捍卫自己的定义(可能有共用术语或权威认证的).
解: 这个基督徒你定义成不喝酒的, 为什么不是每周去教会做礼拜的?
	如果你觉得你的定义更好,能说下你的理由吗?
	你看字典的定义是这样的,专家是这么说的.

***** 小总结:类型或例子(-D)
arguing in a circle:
	1. 前提和结论用同义词替换一下
	2. 你问他要原因,他给你解释名词
	3. 子前提和结论是相同的, 多绕了一下想掩盖丐题
question-begging language:
	1. 靠煽动性的语言:众所周知
		比如: 在法庭上,女性声泪俱下指责丈夫出轨,却不给证据
	2. 把刘亦菲称为女神:
		比如: 在讨论胎儿算不算人类时, 有辩方一直称呼胎儿为婴儿(婴儿已经属于人类的范畴)
	3. 引导性问题:(在问题中假设没有做过的事情, 和后面complex-question有交集 问Leo -D)
		比如: 老师问: 你是用左手抽烟还是右手抽烟啊
complex question:
	1. 问题中的两个子问题会导致 一个问题变成另一个问题的答案
		比如: 你什么结婚和安定下来? 结婚变成了安定下来的答案
	2. 问题中多个问题, 一否全否, 一肯全肯
		比如: 你爱我,愿意给我买房子吗? 
Question-Begging Definition: 首先有个经验前提和定义前提的概念
	1. 经常有true,real,genuine这种修饰语
		比如: 一个人爱国就不可能投降, 如果一个爱国的人投降了,那么就不是真正爱国.

**** Assignments
A. Begging-the-Question
1. Complex Question: 在问题中,假设在沃尔玛买东西等于勇气
2. Question-Begging Definition:
	这里定义真正的犯罪思想是渡过监狱岁月后仍然不会改正.
3. question-begging language:
	煽动性语言,没给证据
4. arguing in a circle
	因为圣经说自己是上帝显灵,所以圣经是上帝显灵
5. Complex Question:
	选民 支持士兵是增加总统国防预算的答案.
6. Question-Begging Definition:
	重新定义了sane是不会自杀的人
7. question-begging language(刘亦菲是女神)
	显然 生存下来的有机生物比没有的更适应环境
8. Question-Begging Definition
	重新定义在 价格范围的房子不包括tacky little house
	
	
** Fallacies of Inconsistency
前提们矛盾或者结论和某个前提矛盾, 这两种情况得不出有效的结论

这种不一致是不明显的.
如果某个前提可以被解释 和 另一个前提或者结论 相矛盾,那么可以认为不一致.
解: 不一致的谬误, 命题和命题之间矛盾.
	比如: 李洁是大学生,李洁不是大学生; 所以李洁上过高中.
		 李洁是服装设计师,李洁是大学生;所以李洁不是大学生.
		 
解: a perfect alibi
	嫌疑人的结论是自己有a perfect alibi
	理由 当犯罪发生时, 我正在8点去往伦敦的火车去工作
		我10点已经在伦敦了
			我工作时间是10点,而且我并没有迟到
	侦探的理由是:
		 8点去往伦敦的火车没运营
		 10点在伦敦可以坐8点25的车
	这里嫌疑犯的理由和实际情况相矛盾, 那么就推导不出他有perfect alibi.
	

*** incompatible premises
从不一致或矛盾的前提们,得出结论

这种情况得不出acceptable or true的结论:
	因为A,
	又 not-A,
	[哈哈,得不出结论]

EXAMPLE: 两个前提不一致, 又说上帝是全能的,所以没有罪恶; 又说有罪恶
	如果上帝是全能的~all-love, 那么就世界上没有罪恶.(A)
	世界上有罪恶.(not-A)
	所以,上帝不存在.
	解: 他们先假设上帝是全知,全能的,慈爱的;世界上没有罪恶 (A)
		世界上有罪恶(not-A)
		假如妈妈啥都会,啥都知道,又爱你,你的任何困难妈妈都会给你解决;
		实际上有些困难就没有给你解决.
		所以要么你妈妈不存在,要么你妈妈不是全知全能,且爱你.
	
EXAMPLE: 上帝说啥对啥就对, 这些行为道德上不对(而不是上帝说的), 两者冲突
	因为上帝说啥是对的,啥就是对的(A)(P)
	一些行为像谋杀, 上帝就不会说是对的(rebuttal P)
		因为他们是道德上不对的(not-A)(subP)
	解: 这里前提矛盾的情况是.
		上帝的说一项行为是正确的是决定事物是否正确的唯一标准.
		一些行为像强奸谋杀,上帝就不会说对的
			因为他们在道德上是不对的(注意这里除了上帝的宣言多了一项判断).

EXAMPLE:
	政治家为了拉选票,说会提升服务降低税费(A); 然后又说税负不变(not-A)

ATTACKING THE FALLACY:
把短句给他标准化, A和not-A,马上就能发现问题了.
辩论中,告诉对方一致性原则.

没病走两步, 让他从A和not-A推导出结论, 一般是退不出来的.
如果推出来了,那么他就是把其中一个当成对的,忽视了另外一个.如果他坚持not-A是对的,就有义务解释为什么不是相矛盾的.

现实中确实很难消除这种矛盾的前提.比如:我姑爷对我说,要把人往坏了想,不要去相信别人.那么他自身也在这个别人当中. 这就矛盾了.
	
	
*** Contradiction Between Premise and Conclusion
定义: 得出的结论和其中一个前提相反

形式: 
	Since A(P)
	Since B(P)
	Therefore, not-A (C)

为啥说这个错了, 因为一个论证里面不能A,又not-A这种情况出现

EXAMPLE:
	因为万事物有源头(A)(P)
	我们不能无限朔源(P)
		因为如果没有源头,我们不会出现(sub P)
	我们出现了(P)
	因此有个没有源头的起源(not-A),那就是上帝.(C)
	
	解: 一定是鸡生蛋,蛋再生鸡.
		但是鸡生蛋,蛋生鸡不可能无限循环
			因为如果无限循环,就不会有鸡和蛋
		有鸡和蛋
		因此肯定有个源头,蛋不是鸡生的,或者鸡不是蛋生的.
解: 蛋是由鸡生的,鸡又是由蛋变的
	但是鸡和蛋不会凭空产生
	所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

EXAMPLE:
	身体物理的且占空间(P) (A1)
	思想非物理的且不占空间(P) (A2)
	经历表明思想影响身体, 反之同样(implicit P)
	所以思想和身体相互交流(C)(not-A)
	解: 思想和身体相互交流, 但是因为非空间的物质和空间的物质不会互相交流,要么身体不是空间的, 要么思想是空间的.
	这样结论要么和A1矛盾,要么和A2矛盾.
	
EXAMPLE:
	所有生命都是神圣的, (P)(A)
	我们有义务不要destory it(P)
	流产destory it(P)
	因为流产是错误的,除了强奸(C)(not-A)
	解: 每条生命都是上天的礼物, 
		我们有义务不要摧毁它,
		流产摧毁了它
		所以流产是错误的, 除了强奸导致产生的孩子.
	
**** Attacking the fallacy
最好的方法去发现这个谬误,就是转换成A,not-A这种形式.
除非arguer不尊重这个不矛盾法则,否则他应该抛弃一个前提,或者找到方法解决前提和结论的矛盾.

*** Assignments
B. Fallacies of Inconsistency
1. 人类知识是建立的skepticism上的(P)(A)
   skepticism是观点, 人类永远不要知道任何事事正确的(P)(not-A)
   我们最好放弃研究(C)
   前提不一致!
   
2. 谁说我错了你对了关于吸大麻.(P)
    每个人要自己决定啥是对的(P)(A)
    我没看到用大麻有任何不道德.(P)
    你错了.(C)(notA)
    前提和结论不一致
3. 
	生命是珍贵的礼物,谁也没有权力拿走.(P)(A)
	一个谋杀其它的人正在destory it(P)
	所以我支持谋杀犯死刑(C)(not-A)
	前提和结论不一致
4.
	B: 你思考没灵感. 你认为如果观点们是相互矛盾的,就没有意义
	E: 我认为不矛盾是智力讨论的必要条件
	B: 没有理由认为矛盾就不能有意义
	E: 如果矛盾,就没有意义
	B: 如果矛盾,也可能有意义
	E: 如果矛盾, 就不会有意义
	B: 你在说什么哦
	前提和结论不一致, B的前提是 前提矛盾也会有意义, E的结论是 前提矛盾就没有意义
	根据B的前提,B的前提和E的结论会共存,所以是前提和结论不一致
	
** Fallacies of deductive inference 演绎逻辑谬误
	
*** Denying the Antecedent: fail to see other reasons 否定前件
well-formed deductive argument:
	If A, then B(P)
	A (P)
	B (C)

Denying the Antecedent:
	If A, then B (P)
	not-A (P)
	not-B (C)
	
这里关键错误在于假设A的出现一定会有B, 但是还有可能C的出现会有B
解: 正常的if then的推理是,
		如果A,那么B; A; 所以B
	否定前件是: 如果A,那么B; not-A, 所以not-B
	这里面犯的错误就是, 把A当作是唯一B的条件.
	如果抽烟,那么会短命. 但是不抽烟不代表不会短命, 因为还可以吸毒导致短命. 抽烟并不是短命的唯一条件.

EXAMPLE: 
	如果抽烟,就会短命 (A->B)(P)
	我不抽烟(not-A)(P)
	我不会短命(not-B)(C)
	解: 家中女性长辈,劝人不要抽烟,理由就是不要抽烟,抽你个短命鬼.
		家长男性长辈常常说,又不是抽烟一件事情会短命.
	
EXAMPLE:
	如果死刑减少人们犯重罪,那么就是正义的(A->B)(P)
	因为没有减少(not-A)(P)
	所以他不是正义的实践(not-B)(C)
	:这里还有其它理由,比如威慑有犯重罪意愿的人让他们不敢犯罪,可以使其称为正义的实践

EXAMPLE:
	如果期末考试过来, 那么课就过了
	因为我期末考试没过
	所以我课没过
	:还有其它理由导致课没过

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪不是狗.
	缪缪就不是动物了.

*** Affirming the Consequent 肯定后件
肯定后件后,肯定前件
Well-formed deductive argument
	If A, then B, (premise)
	and not-B, (premise)
	Therefore, not-A. (conclusion)
	
affirm the consequent
	If A, then B (premise)
	and B (premise)
	Therefore, A. (conclusion)

A不是B的唯一条件,即便是B正确时,A也正确,推理的结构也是错误的.
解: 正常的推理
	如果A, 那么B; not-B; 所以not-A
	肯定后件的推理:
	如果A, 那么B; B; 所以A
	同样的错误也是把A当作B发生的唯一条件
	举例: 如果缪缪是狗,那么缪缪是动物. 缪缪是动物,显然缪缪不一定是狗,还可能是猫. 值得一提的是,即便缪缪是狗,这项推理也是错误的.

EXAMPLE: 
	如果丈夫计划谋杀妻子,那么他会给妻子买保险(A->B)(P)
	丈夫买了保险(B)(P)
	因此,丈夫计划谋杀妻子(A)(C)
	其它理由对买保险也是充分的
解: 如果萍萍偷钱了,她就会买零食
	她买零食了
	偷没偷钱你自己想.

EXAMPLE:
	如果你SAT分数搞,你可能进入一个好大学(A->B)(P)
	你进入好大学: Centre College(B)(P)
	所以, 你SAT分数一定高(A)(C)
	这里假设了SAT分数高是进入好大学的唯一原因,还有可能是成绩高~体育和艺术特长
解: 如果你高考分数高,你可能进入北大
	你去北大了,
	所以,你高考分数高.
	撒贝宁表示北大保送也还行.

EXAMPLE:
	如果我吃红肉, 那么我生病(A->B)(P)
	我生病(B)(P)
	因此, 我肯定吃过红肉(A)(C)
	这里假设了吃红肉是生病的唯一原因

**** ATTACKING THE FALLACY
解:
	我家有只猫叫缪缪.
	如果缪缪是狗,缪缪是动物
	缪缪是动物.
	因此缪缪是狗.

*** False Conversion 错误转换
把if句中的前件和后件互换,或者把主语和宾语互换,并且认为命题的真假不变.

前件和后件转换:
	如果当开关开着灯亮了,那么灯泡是好的. 
	<转换> 如果灯泡是好的,那么当开关开着灯亮了.
换主语和谓语:
	所有的生物学家是科学家
	<不能转换> 所有的科学家是生物学家
	等价于: If one is a biologist, then one is a scientist.
	
	有些X不是Y<不能转换>很少犯,不用特意提
	
	可以转换:
		no X are Y
		some X are Y 
	
	到底可不可以转换, 去觉得主谓 都distributed or 都undistributed.那么就可以转换. 一个distributed一个undistributed不可以转换.
	distributed: term下的所有成员都明确了

EXAMPLE: 
	解: 所有宗教徒都是依赖外界的人
		所有依赖外界的人都是宗教徒<不能转换,例如:孩子>
	
EXAMPLE:
	所有吸冰的人都是吸大麻的人
	<不能转换>所有吸大麻的人都会吸冰
EXAMPLE:
	如果你是基督徒,那么你一定关爱他人
	因此, 如果你关爱他人, 那么你一定是基督徒
	
ATTACKING THE FALLACY
举反例:
	所有苹果都是水果
	<不能转换>所有水果都是苹果
	
	如果这个人是总统,他至少35岁且美国公民
	<不能转换>如果他至少35岁且美国公民,那他是总统

*** Undistributed Middle Term 无关中间项
定义: 从三段论中得出结论, 三段论中前提的中间项没有被distributed至少一次


1. structure of a syllogisms
	1.1. 3个statements 2个premises和1个conclusion
	1.2. middle term和end term
		所有term都出现且只出现两次
		middle term两次出现在premises里
		两个end term一定出现在conclusion里
2. the four types of statements used in syllogisms
	A. all X are Y
	E. no X are Y
	I. some X are Y
	O. some X are not Y
	universal: 全称
	particular: 特称
	affirmative: 肯定
	negative: 否定

3. the nature of distribution
	某个分类下的所有成员都被这个term包括
	例如: AsEbInOp
		- all X are Y. subject是distributed
		- no X are Y. both是distributed
		- some X are Y. neither term是distributed
		- some X are not Y. predicate是distributed.

4. the two main rules of syllogistic reasoning
	1. 中间项至少得distributed一次
	2. 在结论中是dirtibuted的term, 至少得在前提里面distributed一次
	
所有教授是技能丰富的人
没有技能丰富的人是underpaid
因此没有教授是underpaid
symbol化:
	P(A)C  (P)
	C(E)U  (P)
	P(E)U  (C)
	
EXAMPLE:
	PH (I) PDL (P)
	PR (I) PH (P)
	PR (I) PDL (C)
	中间项是PH, 两个premises都是I, 所以PH都是undistributed.和规则1相反

EXAMPLE:
	D (A) CLA
	J (A) CLA
	--------
	J (A) D
	
EXAMPLE:
	SK (A) PAG
	R (A) PAG
	--------
	R (I) SK
	
ATTACKING THE FALLACY
别人不知道符号标记这一套,所以得给别人举例子:比如: 教授读书;孩子也读书;所以孩子都是教授.
但是你自己得懂这一套,这样你用起来才能得心应手.

*** Illicit Distribution of an End Term 最后项的错误分布
a distributed end term in the conclusion is not distributed in the premises

EXAMPLE: 
	书上犯错了,Therefore, members of the jury are people who are likely to come to a false
judgment. (E) (conclusion)
	IRF (A) CFJ s
	JM (E) IRF both
	-------
	JM(E)CFJ both
	CFJ is undistributed
	
EXAMPLE:
	MR (As) J
	BGG (Op) J
	-------
	MR (Op) BGG
	BGG in conclusion is distributed, but in second premise is undistirbuted
	
EXAMPLE:
	NC (A) EX
	NC (A) EE
	------
	EE (A) EX
	the EE in conclusion is distributed, but in second premise is not.
	
ATTACKING THE FALLACY
还是一样, 自己要会用符号系统, 但是跟别人解释,还是举明显得反例
	所有父亲有孩子
	没有妈妈是父亲
	-------
	所以没有妈妈有孩子
	
ASSIGNMENTS
C. Fallacies of Deductive Inference
1. 
	如果毕加索的作品有艺术价值,那么会被大多数人欣赏 (P)
	被大多数人欣赏 (P)
	所以, 它有艺术价值 (C)
	If AM, then  A
	A
	--------
	since AM
	肯定后件
2.
	spheres always cast curved shadows(P)
	the earth casts a curved shadow on the moon during a lunar eclipse.(P)
	the earth is spherically shaped(C)
	S (A) CS As
	E (A) CS As
	--------
	E (A) S As
	CS undistributed middle term
3. 
	BT (E) T Eb
	T (A) C As
	---------
	BT (E) C Eb
	C is an undistributed middle term in second premise
4.
	If OL, then SOT
	SOT
	----------
	OL
	肯定后件
5.
	IF SL, then OV
	not-Sl
	--------
	not-OV
	否定前件
6.
	MJA (I) NV In
	ACD (I) MV In
	--------
	ACD (I) MJA In
	undistributed middle term and illicit distrubtion of an end Term
7.
	If M, then E
	not-M
	---------
	not-E
	否定前件
8. 
	If 控制垄断, then 公共好处增加
	想要公共好处增加
	--------
	所以控制垄断
	肯定后件
9.
	I can do anything I want.
	Nobody can tell me what to do and what not to do.
	
	你必须遵守法律啊.
	我必须遵守法律, 但是政府不能告诉我去做什么.
	-------------
	我可以做任何事情我想做的.
	前提不一致
10.
	E (A) V
	P (O) V
	--------
	E (I) V
	中间项不能出现在结论上
11.
	If he really loved her, he would insist on being the sole provider
	Question-Begging Definition
12.
	肯定后件
	If a cat licks antifreeze, the cat will die.
	I left my cat out last night and she died.
	--------
	She licks antifreeze.
13.
	Complex-Question:
		在问题中假定了事实, 我给你的5000块,你给丢在股票市场了.
14.
	UP (I) K
	RP (I) K
	-------
	UP (I) RP
	中间项一次都没有distributed.
15.
	Question-Begging Definition
	自己定义literally true.
16.
	Question-Begging Definition
	自己定义well-adjust people事那些不自杀的人
17.
	Question-Begging Language
	用stupid这种煽动性的语言
18.
	If the light was on, then he was at home.
	The light wasn't on.
	----------
	He wasn't at home.
	否定前件
19.
	Arguing in a Circle
	前提和结论一致
20.
	SHMW (I) D
	FP (E) SHMW
	---------
	FP (E) D
	D在结论是distributed, 但是在前提里面不是distributed.
	
21.
	前提不一致
22.
	Question-Begging Definition

** 四种丐题的区别
四种丐题的区别:
	arguing in a circle: 强调的某个前提和结论一致
		1. 跟我老婆争论通天猫爬架时,她看中了一款1000多的,说那个质量好.我说为什么你觉得质量好,她说我就是觉得那个质量好,一看我就知道了.
		2. 小时候我不信佛,我婆婆说你不信佛,菩萨就不会保佑你.这里我婆婆说菩萨不会保佑你,暗含的意思是菩萨已经存在了.
		3. 同事说公司老总跟着封建家长一样, 为啥这么说, 因为他把自己当爷,对待我们跟对待他的儿子一样.
	Question-begging language: 强调利用语言引诱听众给出想要的结论. 强调的是引诱,并没有给出答案
		1. 我侄子哭得稀里哗啦地跟他妈妈告状,说别的小朋友带他.问他怎么打的,他又不说话.
		2. 读高中时,我们在讨论哪个女生是不是美女.到讨论到闵xx的时候,某个同学一直称呼闵xx为女神.
		3. 比如领导吩咐下一件事情需要我和同事做.我表现地很积极,但是同事想偷懒.有时候他就会来上一句, 你不是真的打算一周内做完吧?
	complex question: 强调的是在问题中给出了一些答案,或者所有子问题答案一致
		1. 老师逮住学生. 你是用左手抽烟还是右手抽烟?
		2. 我老婆问我,你爱不爱我,给不给我买最新的江南布衣的衣服?这里她就犯了复杂问题的错误.
	Question-Begging Definition: 关键在于定义是说话者自己的,还是公众的共识
		1. 邻居说他家狗很乖不会冲人狂吠. 然后我说狗昨天冲他叫了.邻居说,他冲你叫了但是没咬你,所以它不会冲人狂吠.
		2. 有人说孔乙己偷书了, 孔乙己说自己没偷书, 那是拿, 读书人的事情那能叫偷吗?

** 前提/结论不一致的案例
前提与前提不一致:
	1. 新二 a perfect alibi 那一课.
			嫌疑犯声称自己有a perfect alibi.
			嫌疑犯说:当谋杀发生时, 他正在8点去往伦敦的火车上, 理由是他10点已经在伦敦工作了.
			而侦探说: 他没有坐8点去往伦敦的火车,理由是8点去往伦敦的火车停运, 并且8点25的火车也可以10点前到达伦敦.
			这里嫌疑犯给出的前提和侦探给出的前提不一致,所以得不出他有perfect alibi.
	2. 上帝是全知全能的. 那么上帝能不能造出他举不起来的石头?
		 能不能造出举不起来的石头,分为两种情况, 一种是造出举不起来的石头, 和上帝全能矛盾.
			另一种是造不出举不起来的石头, 也和上帝全能矛盾.
		 因为前提和前提相矛盾, 我们不能得出任何结论.
前提和结论不一致:
	1. 蛋是由鸡生的,鸡又是由蛋变的
		 但是鸡和蛋不会凭空产生
		 所以肯定有鸡不会蛋变的或者蛋不是鸡生的.

** 违反演绎推理
否定前件:
	1. 家中女性长辈,劝我不要抽烟.如果抽烟,那么就会打短命.不抽烟,那么就会活就一点.
		 不抽烟可能导致其他不良习惯,其他不良习惯同样也可以导致短命.
肯定后件:
	1. 如果平平偷钱了,那么她就会去买零食.
		她刚刚买了一堆零食.
		所以钱是她偷的.
	2. 如果你高考分数高,你可能进入北大
		 你去北大了,
		 所以,你高考分数高.
		 撒贝宁表示北大保送也还行.
	3. 我跟老婆有一天两个人都口臭,我们认为是前一晚都吃了金汤酸菜鱼的原因.
		 如果酸菜鱼有问题,那么我们会口臭.
		 我们一切口臭了.
		 那么那个酸菜鱼有问题.
错误转换: 
	 全部肯定换主谓语:
		所有的生物学家是科学家.
		所有的科学家是生物学家.
	 条件中, 前件和后件互换:
		如果我提前过户了二手房,那么卖家提前还款了.
		如果卖家提前还款了,那么我提前过户了二手房.(还可能卡其他环节啊,比如交契税)
无关中间项和错误分布的端项: 用处不大,用文氏图更直观
		AEIO: 分别是全部肯定,全部否定,部分肯定,部分否定
		AsEbInOp: s=subject, b=both, n=neither, p=predict,代表对应项是distributed
		Term: 中间项出现了前提两次, 两个端项一定出现在结论
		两条法则:
			1. 中间项至少distributed一次(按AsEbInOp判断)
			2. 端项在结论中是distributed,至少在premises中distributed一次.
无关中项和错误确定的端项:
	1. 首先要是三段论,两前提+一结论,前提和结论得是全部肯定~部分否定~全部否定~部分肯定的一种
		 解: 这里要非常注意AEIO和条件句的区别
			AEIO: 所有人都会死
			条件句: 如果他是人,那么他会死
			举例: 全部肯定:所有人都是会死的人
					 部分否定: 一些人不是女人
					 全部否定: 所有人都没有智商超过5w
					 部分肯定: 有些人智商超过200
	2. 全部肯定是主语,部分否定是谓语,全部否定都确定,部分肯定都不确定
		 全部肯定是主语: 所有人都是会死的人, 这里 "人"确定了范围(distributed)
		 部分否定是谓语: 一些人不是女人, 这里"女人"确定了范围
		 全部否定都确定: 所有人都没有智商超过5w, 这里"人"和"智商超过5w的人"确定了范围
		 部分肯定都不确认:有些人智商超过200, "人" 和 "智商超过200的人" 都没确定范围
		 这里记忆还有个技巧. 全部肯定的否定是部分否定, 由主语确定变成谓语确定;全部否定的否定是部分肯定, 由全部确定变成全部不确定.
	3. 两端项和中项各出现两次,中项不会在结论中出现
		 这里就是注意把主谓项规范成一致的.
			比如:
				所有人会死
				苏格拉底是人
				所以苏格拉底会死
				------规范后
				所有人都是会死的人
				苏格拉底是人
				所以苏格拉底是会死的人
				这里有三项且各自出现两次: 人 会死的人 苏格拉底
				人是中项,并且没有出现在结论里
	4. 两法则: 中项必须确定一次; 在结论中确定的端相必须在前提中确认至少一次
			继续上面的例子
				P1:所有人都是会死的人
				P2:苏格拉底是人
				C:所以苏格拉底是会死的人
				1. 根据中项必须确认一次判断, 人是中项
						P1:所有人都是会死的人
						-------
						全部肯定是主语, 人是确定的, 满足了规则
				2. 根据结论中确定的端项,必须在前提中确认至少一次
						C:所以苏格拉底是会死的人
						因为部分肯定都不确认
						所以不需要判断

					 
					 

