* Chapter 6 Fallacies That Violate the Relevance Criterion
- 用你自己的话描述不相干谬误
- 发现,叫得出名,解释谬误的形式,当辩论或生活遇到的时候
- 用有效的策略去帮助别人纠正他们的不相干谬误
(1) fallacies of irrelevant premise
(2) fallacies of irrelevant appeal.

公输般

英国护卫

--------------------
- 用自己的话描述下那些违背相干性原则的谬误
- 在生活和辩论中遇到的时候,遇到了能辨识,叫得出名字,能够解释谬误的形式.
- 用有效的策略帮助别人纠正他们的不相干谬误

论证要有相干的证据.

两类不相干谬误,一种是用不相干的前提,另外一种是各种诉诸.

1. 不相干前提
   从前提推导不出结论:前提和结论没联系,或者前提到结论有跳跃性.
2. 诉诸
  
** Fallacies of Irrelevant Premise
1. 根据旧的情况推断新的事物,无视环境已经发生了变化
2. 用看似有理的原因而不是真正的原因去隐藏掉真实的想法和行为
3. 对理由去做另一番解释,目的是为了得出结论.
4. 为了得出结论,而去编造理由.
  
** Genetic Fallacy
用过去的context去计算现在的事情,无视新旧之间已经发生了变化
wusd: 刻舟求剑

只考虑事情一开始是怎样的,因而忽视了事物的发展,退化,差异.
wusd: 要用发展的眼光看待问题,
什么人容易犯呢?
  1. 把过去看事物的老眼光:或积极或消极,用在现在了
     wusd:
			吴下阿蒙.
		  小米就是钓丝低端的,所以小米su7我完全不考虑买.
			我们经常会根据很久的经历去判断一个人现在到底怎么样,并且这种想法很难改变.
				比如人际交往,第一次如果留下坏印象了,后面就很难再改变看法.
  2. 一些宗教啊,根据原始教义不许做某事,但是到如今已经发生了变化了.
     wusd: 回族人不允许吃猪肉,原本是当时卫生不达标,猪肉脏,吃了易得病. 但是现在科学化养殖,仍然还是禁止吃猪肉.

这种谬误的模式就是:
  前提和结论是要相干的.现在的结论虽然和以前的前提相干,但是前提已经发生了变化,变得不相干了.

EXAMPLE:
	我不会给Don Reichard投任何票,我和他同学的时候,他在学校里完全就是个混子.
	实际上,Don有可能变成熟了,变成了和原先完全不一样的人.
	wusd: 对应了第一种例子.用老眼光看人.那我们同样也不应该用老眼光去看自己.
		因为Don在上学期间是混日子的.(P)
		上学混日子,当官员时会一直混日子(IP)
		所以Don在当官员时同样会混日子.(C)
EXAMPLE:
	因为结婚戒指原本是丈夫用来束缚他们妻子的标识(P)
	而且这个标识会一直做同样的事情(IP)
	这种行为实施了性虐待(P)
	所以,现在谁还用结婚戒指也是实施性虐待(C)

wusd: 这里讲的例子,是有可能变化,但是也有可能没变.所以对于Don能不能胜任官员,需要继续调查.
	对于结婚戒指实施性虐待需要更深入的统计数据
EXAMPLE:
	虽然我听说李医生是一个很帮的医生.但是我不会去李医生那里看病,我跟他同学的时候,他一直看黄片.
	wusd: 虽然吴教授是一个优秀的导师,但是我不会报考他的研究生,因为他以前上学时经常打架斗殴.

ATTACKING THE FALLACY
这些固有印象连接我们的思想,会在我们考虑的时候严重地影响我们对其的喜爱或厌恶.比如:让你去评价下前男友的装修和衣服.
但是当我们要深思熟虑的时候,就要想办法抵制这些因素的影响.
当辩手这么按这种方式想问题的时候,我们就可以反过来问他现在这事物有没有厌恶点或喜爱点.
wusd: 人是感情的动物,想要不受原本的固有印象影响去判断一件事非常困难,要想办法抵制掉这些因素的影响.
	当有人或者自己按这种方式考虑问题的时候,就可以反过来问下这件事当下有没有值得的点和厌恶点.

假如拥有长期亲密关系的伴侣,最开始的约会或见面却是场乌龙或恶作剧.
这对伴侣,肯定不会以最开始的价值来评价现在关系的价值.
如果能够搞清楚这种情况,自然能够正确处理其他事情.

你说林师傅是大厨,但是小时候他弄个馅饼都搞得乱七八糟的,所以我不会吃他做的任何食物.

** Rationalization 狡辩
用听起来很响亮但实际是假的理由去去主张某个立场.

出于尴尬~恐惧~其他原因,真实的原因被隐藏了,而使用fake的reasons去推导出结论.

好的论证啊,是由证据推导到信念;而在rationalization里,信念已经有了,前提或理由根据信念捏造的.

因为前提或理由是捏造的,并不支持结论了,那么就和结论不相干.

EXAMPLE:
我考试一向成绩不好.P
考试也不能说明我的真实能力.P
考试前我收到影响我的坏消息.P
----------
我不应该被要求在Law School Admissions Test表现很好.

如果Xavier是个大二的哲学生,那么他可能已经通过大量考试了,否则他升不了大二.
如果他确实考试不行,教授应该早就知道原因,不用再提醒了.

这种坏消息的影响也不成立.
当考生遇到考不过的情况,大概率就是考试太难了.X需要努力提升必需的技能以便在今后的考试中顺利.
如果坚持给这个fake reasons的话,会阻止自己的进步.

wusd: 这我跟读英语的时候,有时候懒了,不想动了.
会自己给自己找各种理由辩解:比如工作累了;今天和老婆逛街了;要陪猫完;今天已经看了好几章的英语了.
实际上做完这些事情我仍然是有精力和时间去做这个跟读的.

EXAMPLE:
我早就计划把他甩了.跟他在一起真无聊.我早就应该甩了他,我觉得他很可悲.

wusd: 我跟我老婆吵架的时候,后面发现是她不对,我要求她道歉.她不想道歉,给的理由是,上次我没给她道歉.
但是实际上我当时道歉了,还转了红包.
这里她确信自己没错,不想道歉,然后认为当时我没道歉.

EXAMPLE:
我觉得本来应该去我侄子的婚礼,但是我们一直走的不是很近.
我只见过新娘一次,人家都不记得我.
我不知道要买什么给人家做结婚离婚,因为他们该有的都有.
而且很多人在这呢,压根不会想我.

真实原因可能就是不想买礼物;不想宿妆打扮;想去看球赛.
wusd: 同事的婚礼,我犹豫了很久要不要去.然后其他同事问我去不去.
我说不知道包多少红包.
不知道人家叫我去是客套还是真实.
人家亲戚朋友那么多,缺我一个不缺.
其实真实的理由就是: 她是在隔壁县办的婚礼,而我没有车,又不太好意思蹭其他同事车,害怕社交.但是又不敢真正说出口.

*** ATTACKING THE FALLACY:
狡辩者大概率是出于要面子,不肯说出真实理由,要让他们知道我知道他没有说实话(论证).

如果是错的或者没关系的,你是不是还是觉得结论是对的.
如果回答是yes,那么他已经承认自己错了.
如果回答是no,就需要找到方法去证明他的错误.最好的结果是,当事人放弃或改变观点了.
wusd: 如果说红包金额可以确认,然后人家真的是请你去,你去不去?
不去,那么就承认了自己有其他原因.
如果去,那么就说明红包金额可以和其他同事确认;告诉他人际交往请你就是真心要你去的.这样就会直面真正的问题,交通的问题.

如果这个人是故意给fake reasons,这个人道德上要被谴责的.
但是注意我们的目标是为了得出好的论证,不过过多聚焦让这人出丑上.

** Drawing the Wrong Conclusion
定义:得到一个结论但是这个结论不是证据支持的.

这个谬误又叫搞不清楚重点.怎么个搞不清楚重点呢?各种证据都指向某个结论,但是arguer却说得到了另外一个结论.

有时候这种谬误是故意的.比如空方律师指控嫌疑人犯有强奸罪,而无视证据都指向的是强奸是重大罪行.

犯这种谬误有时候是忽略了一些信息,有时候因为微妙的~下意识的或者有偏见.
比如: arguer希望证明一些结论,但是目前的证据还不够证明.
	像: arguer非常关心社会对于女性的不平等待遇,所有性歧视的行为都被拿出来证明应该立法保护女性.
		但是实际可能仅仅说明文化有性歧视,还不足以到立法的程度.

EXAMPLE:
因为我坚信婚姻的神圣性.P
----------
所以,婚姻应该有一男一女.C

这里就是没有说清楚,婚姻的神圣性和婚姻应该是一男一女的关系.
然后像神圣这种事情,根据clarity principle 应该解释神圣的定义.

EXAMPLE:
靠管理员定期抽查来evaluate学校老师的方法是不合适的.P
如果老师非常差的话,是没有有效办法解雇他的.P
----------
老师应该按学期雇佣,再进入市场,然后再雇佣.C

或许是应该按学期雇佣老师,但是这里得不到这个结论.得到是,应该找更好的检查办法,把那些不合格的老师找出来.

wusd: 
公司副总要求员工不允许走消防门上下班.
理由是消防门开着会导致闲杂人等的进入.

得出的结论应该是应该加强消防门的管理,比如规定时间内消防门开着,员工进出需要关门,而不是禁止员工进出消防门.

EXAMPLE:
记者让消息公开,消息公开有助于正义伸张.P
记者同时有让官员诚实,并且暴光他们不当行为.P
----------
仅仅是因为他们没有披露信息来源就送去监狱,是法院对他们的不公.

wusd: 知乎上经常在社会有不公的事情,信息披露不透明的时候.
说平民批评那些公知,然后得出结论平民罪有应得,共知不该被批评.
实际上,应该区分具体的事情.有些公职经过时间检验确实是被无端怒骂,比如李开复当年的言论自由论.
但有些共知确实是做错了事情被骂.
得到的结论应该是,对于批评共知,要更好的社会规范.而不是说批评就是不对的.

记者对于社会的贡献并不能推导出法院对他们的不公.

*** ATTACKING THE FALLACY
当别人犯这种谬误的时候,告诉他这些证据可以得出什么结论.
因为他情感上可能不愿意接受嘛,慢慢罗列下证据和正确的结论.
如果他不管正确的结论,就告诉他原本的结论需要哪些证据.

对同事:你和我有共同喜欢的东西,两人住比一个人住要省,我们可以一起坐车上班.所以我们应该结婚.

** Using The Wrong Reasons
定义: 用不恰当的理由去支持结论.

Wrong Reasons 和 Conclusion转化成标准形式后看起来是一样的.
但是Wrong Reasons是先有了结论,再用错误的理由去支持结论.因为想要证明特定的结论,又没有找对理由.
而Wrong Conclusion是先有理由,再有结论.因为丢了理由的大意.

为啥会犯这种谬误呢?
arguer已经非常相信结论了,然后就把所有有关的理由都拿出来当证据,认为是恰当的.还有就是找不到恰当的理由.

wusd:
知乎上有人说楼下要装室外雨棚的时候,笑眯眯地,非常有礼貌.
但是当他要把衣帽间改成淋浴室的时候,就一直阻挡他不让他施工.
这里arguer认为自己把衣帽间改成淋浴间是对的,因为他也让楼下装室外雨棚.

wusd:
武林外传中,吕秀才刚分手的时候....

一些程序一些政策,经常被攻击没有达到某某效果,应该被取消.
一个是程序和政策的设计者,本身有时代的限制.
另外一个是程序和政策的目标是理想情况,并不难完全达到.
有些时候程序和政策的设计目地并不是要达到声称的效果.
比如:比如某某法律的存在,有人攻击说不能阻止犯罪的发生.但是可以起到威慑犯罪的作用,减少罪恶的发生,也达到了其目的.

EXAMPLE:
烟草证明造成癌症-P
烟草很贵-P
二手烟对其他人很冒犯-P
----------
特殊人群不该被投放烟草广告-C

这个得出的结论是不应该抽烟,得不出投放烟草广告的结论.
虽然结论本身是对的,但是需要其他理由.这个用了错误的理由.

EXAMPLE:
哲学不能解决所有问题-P
哲学家还在处理2500年前Socrates的问题.-P
----------
哲学是浪费时间-C

这里得出的结论只能说哲学很有很有很多问题没有解决,而且不能解决所有问题,并不能得到哲学是浪费时间.
这里已经有结论哲学是浪费时间,然后用了两个理由.但是哲学的目的并不是要解决问题.

wusd:
小时候,家长一看我们玩游戏,上网.就会说你又在浪费时间,玩游戏上网又不解渴又不管饱的,又没钱,又不能提高学期成绩.
也是强行把玩游戏上网添加了目的,要有生产力,和能提高学习成绩.

EXAMPLE:
控强法案的批评者: wrong reasons, 应该说空枪会和一些更重大原则起冲突,比如:民主?
	控抢不会阻止罪犯用枪犯罪-P
	----------
	没有理由去通过空枪-C
空枪法案的支持者:
	尽管空枪对于控制犯罪影响有限.
	但是重大犯罪会被严格销售和注册影响.
	可以减少国内的冲突.
	减少激情杀人的数量.
	----------
	尽管有限制,但是荏苒按应该通过空枪.


*** ATTACKING THE FALLACY
用wrong reasons的时候,大部分是conclusion非常对.
这时候你就可以说:你这个结论非常好,非常有意思,但是好像不是因为你给的理由.
然后再把你认为合适的理由抛出来.

对于程序或政策或活动,给他添加不相关的目标或功能的时候.
要想法设法地提醒他,活动~程序~政策本来就是有限的,这样有可能阻止arguer犯这种错误.
如果他坚持的话,就把他附加的不相关的目标或功能给他讲清楚来,让他知道自己在犯错误.
