#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* table of contents
- 一.阅读的深度
	1. 阅读活动和艺术
	2. 阅读的等级
	3. 阅读的Lv1: Elementary Reading
	4. 阅读的Lv2: Inspectional Reading
	5. 如何成为有追求的阅读者
		 -------------------阅读的Lv3:Analytical Reading
	6. 书籍归类
	7. X-ray书
	8. 与作者妥协
	9. 找到作者的信息
	10. 公正的批判一本书
	11. 同意/不同意作者
	12. 看书的帮助
			-----------------阅读不同书的方法
	13. 读实践书
	14. 读幻想类文学作品(如:哈利波特)
	15. 故事/表演和诗歌
	16. 读历史书
	17. 读科学和数学
	18. 读哲学类
	19. 读社科
			-----------------阅读的终极目标
	20. 阅读的Lv4:Syntopical Reading
	21. 阅读与思维的成长
** inspectional reading 1: Systematic Skimming or Pre-reading
how:
	1. 快速看标题,有前言就看前言. 完成这步前,你应该知道这本书干嘛的,然后这本书归类于什么?
	2. Study目录, 目标要得出书的结构,作为导航的地图
	3. 对下索引
	4. 有外包装的看外包装
	5. 看你认为是中心的章节,一般是第一章和最后一章,看开头和结尾
	6. 打开书,看个一两章,或者几页,不要看太多了

** inspectional reading 2: Systematic Skimming or Pre-reading
看的书要学会ignore details


** preface
learning how to read;
a much more comprehensive and better-ordered analysis of the complex art of reading;
the flexible application of the basic rules to different types of reading to every variety of reading matter
the discovery and formulation of new rules of reading; and the conception of a pyramid of books to read, broad at the bottom and tapering at the top

** 1 THE ACTIVITY AND ART OF READING
这本书是为想有更好的understanding的读者写的.

We had to read because radio and television are never enough for curious and intelligent people.

Modern communications media hasn't much enhanced our understanding of the world.

We have so many facts that we can't understand it.

一些思想被打包成了磁带,我们成了录音机,按个按钮就播放,却没有想过适不适合.

*** Active Reading
这样阅读书的rules,follow和practice之后,可以用来读任何文本

阅读相当于啃肉,越积极越能啃点东西下来,还有得是肉,不是垃圾.

阅读和听不是像等待法庭的审批,而是像棒球手一样去接住作者的球.

写东西就是棒球的发球手, 读就是棒球的接球手, 唯一被动的是这个球.

阅读的技能就是接住各种各样的发球,不论是快球,旋转球,变球还有关节球.

非常值得注意的是, 写作和阅读是互相合作的,写作打出的球是为了让阅读能接到.换言之,故意不让接的球干脆别接.

写作的人比阅读的人(未训练的)更容易接到球

知识比球复杂,所以就有了接受的多少

Reading actively and more skillfully. 两者息息相关的

*** Reading as Learning: The Difference Between Learning By Instruction and Learning By Discovery
information和understand的不同

information知道是怎样就够了.understand要知道所有,为什么是这样,跟其他事情的联系,什么方面是相同,什么方面是不同的等等

information就是remember, understand是explain

~

书呆子,读太多书,又没读好. sophomores半吊子

business of reading and its relation to education?

Instruction就是别人教, discovery是自己发现

~

像农民种庄稼一样,最后评价标准一定是庄稼长大和长好.老师教学生也同样,最后一定是学生学习,然后grow his mind.

unaid discovery 和 aided discovery 包括了reading和listening

thinking和instruction和discovery是不同的学习

thinking在active instruction中也不缺少

reading包含了discovery中的一切活动: keenness of observation, readily available memory, range of imagination, and an intellect trained in analysis and reflection. 

*** Present and Absent Teachers
要阅读做discovery的第一优先,听做第二优先.因为阅读是没有老师的学习,听讲是有老师的学习.

问老师问题,老师会回答你,不懂老师会给你解释.
但如果问书问题,你就得问你自己,更像是真实世界,你必须自己思考和分析.

~

没老师的帮助,也得自己学习.

** 2 The Levels of Reading
1. Elementary Reading
2. Inspectional Reading
3. Analytical Reading
4. Syntopical Reading

阅读就是unaided discovery, 能学到多少, 取决于我们的努力还有知道how.

reading levels之间的区别搞不懂,就不会有阅读技能的提升.

reading levels是累积的,高级的一定包含了低级的.

--------------Elementary Reading
What does the sentence say?

Elementary Reading就是小学该学到的阅读技能.

Elementary Reading就是能理解字面意思.比如说猫蹲在帽子上,就知道哦猫,帽子,蹲在帽子上.

简单来说就是这句话讲啥了?

~

Elementary Reading遇到的困难主要是mechanical, 要靠提升速度解决, 具体第四章会讲.

--------------Inspectional Reading
What is the book about? or What is the structure of the book? or What are its parts?
What kind of book is it--a novel,a history,a scientific treatise?

Inspectional Reading要着重速度了,比如给5分钟阅读全文.

Inspectional Reading就是用最少的时间得到全文大意.

Inspectional Reading又叫Skimming或pre-reading,但是是系统性的Skimming.

Inspectional Reading的目标就是学到书中所有表面的东西.

~

~

----------------Analytical Reading
Analytical Reading的难度取决于文本本身的难度.

Inspectional Reading是限定时间内学得最好, Analytical Reading是无限时间学到最好.

Analytical Reading必须问许多有组织的问题.(Part Two会提)
Analytical Reading is always intensely active.
有些书尝尝味道就好,有些囫囵吞下,有些书需要反复咀嚼和慢慢消化直到书真正变成自己的.

Analytical Reading如果仅仅只是为了entertainment或information,是不需要的.
如果是为了understanding,不好意思,必须Analytical Reading

--------------------Syntopical Reading
最复杂和要求最多的阅读,怎么个要求多呢?即便是相当简单和知识不密集的text,对于读者都有非常重的要求.

Syntopical Reading别名是Comparative Reading, 需要看很多书,进行一个对比.
但是又不仅仅是对比,需要读者自己去construct一个新的analysis.

Syntopical Reading也有一堆规则不为人知.


** 21 Reading and the growth of the mind

More active reading is, the better it is.
Active reading is the asking of question.

Lower levels of reading is contained in higer ones.
Analytical reading is the most unfamiliar for most readers,
		whose things always applies syntopical reading with certain adaptations,
	so that we discussed it at a great length.

This is a practical books containing the rules of inspectional, analytical, and syntopical reading
	which you should practice on purpose if you accept.

*** What Good Books Can Do for Us
You should have not only the things you read but the method to apply to them as well. 

The method including analytical and syntopical reading doesn't apply to every book
	which do not require it.

You must read books beyond you or you will not be a better reader,
	for unless you stretch your mind you will not learn.

You mustn't expect to get any improvement in reading skills from the books
	that provide you with no more amusement.
Reading a book full of information doesn't either,
	for your mind is merely fuller of facts but not stretched when you read it.

Don't fear the books that make demands on you,
	because the rules we have described will tell to how to tackle them.
Besides, there are some very books you must find out
	which will continue to extend you no matter how good a reader you are.

The books that neverending challenge to your skills
	are not always ones in relatively unfamiliar fields or some scientific books.

If a book defies your efforts to analyze it, it's a bad book and no worth trying.

When you try to read a good book, you receive two kinds of reward:
	the improvement in your reading skill and the things about the world and yourself.

The greatest books can help you to think better about the knowledge beyond you,
	because the authors of these thought better than you.

*** The Pyramid of Books
There are more than 99 percent of books written in the Western tradition
		that don't impore your skill in reading and only provide amusement or information,
	as you don't have to read them analytical at all and only skim.

The good books which make severe demands on you and are worth read analytically once
	are less than one in a thousand.

How to know that if a book is only good book?
After having read it, you're grateful to what it has given you, but you know that's all.

There are of the few thousand such books even smaller number.
After reading it analyticall to the best of you ability and placing it back on the shelf,
		you keep thinking about it and your reaction to you
			so that you obligation as an analytical reader takes you back to the book to find more.

A return of the second class of book is inevitably disappointing,
	for the book has not changed but your mind is fuller.

It seems that the books of the highest class have grown with you,
	for you can always see something new that you didn't see before.

The great book may be so far above you that it can lift you over and over again until you die.

People have different tastes, so you may never feel about an author the way you feel about others.

We have listed those books that may have this kind of value for many readers.
You need to seek out the few books that can have this value for you.

*** The Life and Growth of the Mind
Which ten books would you select before
	being marooned on a desert island for the rest of your life?

List it, there would be just you and ten books.

To a extent, we are marooned on a desert island.

The mind doesn't cease growing before the brain itself loses its vigor.

If you mind is not used, it can atrophy.
Som people who were kept alive by external force like the demands of their work
	die so soon after their retiremnet.

As all the sources of amusement and informaion surrounding us are artificial props like drugs,
	if we get used to them, and they have little or no effect, we cease to grow and begin to die.

Reading actively is not the way to advance our career but keep our minds alive and growing.

*** questions
新概念并不是一本great的书,how to read a book说只需看一遍, 而我们却需要读百遍, 想知道这种区别在哪里?
