#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* table of contents
- 一.阅读的深度
	1. 阅读活动和艺术
	2. 阅读的等级
	3. 阅读的Lv1: Elementary Reading
	4. 阅读的Lv2: Inspectional Reading
	5. 如何成为有追求的阅读者
		 -------------------阅读的Lv3:Analytical Reading
	6. 书籍归类
	7. X-ray书
	8. 与作者妥协
	9. 找到作者的信息
	10. 公正的批判一本书
	11. 同意/不同意作者
	12. 看书的帮助
			-----------------阅读不同书的方法
	13. 读实践书
	14. 读幻想类文学作品(如:哈利波特)
	15. 故事/表演和诗歌
	16. 读历史书
	17. 读科学和数学
	18. 读哲学类
	19. 读社科
			-----------------阅读的终极目标
	20. 阅读的Lv4:Syntopical Reading
	21. 阅读与思维的成长
** inspectional reading 1: Systematic Skimming or Pre-reading
how:
	1. 快速看标题,有前言就看前言. 完成这步前,你应该知道这本书干嘛的,然后这本书归类于什么?
	2. Study目录, 目标要得出书的结构,作为导航的地图
	3. 对下索引
	4. 有外包装的看外包装
	5. 看你认为是中心的章节,一般是第一章和最后一章,看开头和结尾
	6. 打开书,看个一两章,或者几页,不要看太多了

** inspectional reading 2: Systematic Skimming or Pre-reading
看的书要学会ignore details


** preface
learning how to read;
a much more comprehensive and better-ordered analysis of the complex art of reading;
the flexible application of the basic rules to different types of reading to every variety of reading matter
the discovery and formulation of new rules of reading; and the conception of a pyramid of books to read, broad at the bottom and tapering at the top

** 1 THE ACTIVITY AND ART OF READING
这本书是为想有更好的understanding的读者写的.

We had to read because radio and television are never enough for curious and intelligent people.

Modern communications media hasn't much enhanced our understanding of the world.

We have so many facts that we can't understand it.

一些思想被打包成了磁带,我们成了录音机,按个按钮就播放,却没有想过适不适合.

*** Active Reading
这样阅读书的rules,follow和practice之后,可以用来读任何文本

阅读相当于啃肉,越积极越能啃点东西下来,还有得是肉,不是垃圾.

阅读和听不是像等待法庭的审批,而是像棒球手一样去接住作者的球.

写东西就是棒球的发球手, 读就是棒球的接球手, 唯一被动的是这个球.

阅读的技能就是接住各种各样的发球,不论是快球,旋转球,变球还有关节球.

非常值得注意的是, 写作和阅读是互相合作的,写作打出的球是为了让阅读能接到.换言之,故意不让接的球干脆别接.

写作的人比阅读的人(未训练的)更容易接到球

知识比球复杂,所以就有了接受的多少

Reading actively and more skillfully. 两者息息相关的

*** Reading as Learning: The Difference Between Learning By Instruction and Learning By Discovery
information和understand的不同

information知道是怎样就够了.understand要知道所有,为什么是这样,跟其他事情的联系,什么方面是相同,什么方面是不同的等等

information就是remember, understand是explain

~

书呆子,读太多书,又没读好. sophomores半吊子

business of reading and its relation to education?

Instruction就是别人教, discovery是自己发现

~

像农民种庄稼一样,最后评价标准一定是庄稼长大和长好.老师教学生也同样,最后一定是学生学习,然后grow his mind.

unaid discovery 和 aided discovery 包括了reading和listening

thinking和instruction和discovery是不同的学习

thinking在active instruction中也不缺少

reading包含了discovery中的一切活动: keenness of observation, readily available memory, range of imagination, and an intellect trained in analysis and reflection. 

*** Present and Absent Teachers
要阅读做discovery的第一优先,听做第二优先.因为阅读是没有老师的学习,听讲是有老师的学习.

问老师问题,老师会回答你,不懂老师会给你解释.
但如果问书问题,你就得问你自己,更像是真实世界,你必须自己思考和分析.

~

没老师的帮助,也得自己学习.

** 2 The Levels of Reading
1. Elementary Reading
2. Inspectional Reading
3. Analytical Reading
4. Syntopical Reading

阅读就是unaided discovery, 能学到多少, 取决于我们的努力还有知道how.

reading levels之间的区别搞不懂,就不会有阅读技能的提升.

reading levels是累积的,高级的一定包含了低级的.

--------------Elementary Reading
What does the sentence say?

Elementary Reading就是小学该学到的阅读技能.

Elementary Reading就是能理解字面意思.比如说猫蹲在帽子上,就知道哦猫,帽子,蹲在帽子上.

简单来说就是这句话讲啥了?

~

Elementary Reading遇到的困难主要是mechanical, 要靠提升速度解决, 具体第四章会讲.

--------------Inspectional Reading
What is the book about? or What is the structure of the book? or What are its parts?
What kind of book is it--a novel,a history,a scientific treatise?

Inspectional Reading要着重速度了,比如给5分钟阅读全文.

Inspectional Reading就是用最少的时间得到全文大意.

Inspectional Reading又叫Skimming或pre-reading,但是是系统性的Skimming.

Inspectional Reading的目标就是学到书中所有表面的东西.

~

~

----------------Analytical Reading
Analytical Reading的难度取决于文本本身的难度.

Inspectional Reading是限定时间内学得最好, Analytical Reading是无限时间学到最好.

Analytical Reading必须问许多有组织的问题.(Part Two会提)
Analytical Reading is always intensely active.
有些书尝尝味道就好,有些囫囵吞下,有些书需要反复咀嚼和慢慢消化直到书真正变成自己的.

Analytical Reading如果仅仅只是为了entertainment或information,是不需要的.
如果是为了understanding,不好意思,必须Analytical Reading

--------------------Syntopical Reading
最复杂和要求最多的阅读,怎么个要求多呢?即便是相当简单和知识不密集的text,对于读者都有非常重的要求.

Syntopical Reading别名是Comparative Reading, 需要看很多书,进行一个对比.
但是又不仅仅是对比,需要读者自己去construct一个新的analysis.

Syntopical Reading也有一堆规则不为人知.

** 3 The First Level of Reading: Elementary Reading
阅读时代的三个历史趋势:
	1. 美国扫盲
	2. 开始教授自己阅读
	3. 批评学校的教育
stages of Learning to Read
	1. 读可读的, 从出生到6-7岁
	2. 读非常简单的材料, 到后期可以带着喜爱独立阅读.会解除到抽象字符
	3. 建立词汇量,可以根据上文线索去理解.可以独立阅读, for fun, curiosity, expand one's horizon
	4. 增强以上的技能, 往后余生.
Stages and Levels
	stage1-4都包含level1
	high school work, 只是level1
Higher levels of Reading and Higher Education
	大学也很少有教超过level1的
Reading and the democratic ideal of education

70年代是阅读时代,关于阅读的研究和实验也是层出不穷.

三个历史原因造就了这个时代.
第一, 美国从建国开始就扫盲,并且当作是民主的基本国策.
	扫盲工作已经有很多成绩了,但是还是部分高动机而且大部分父母有文化的孩子学得好,离教育每个孩子不论动机和父母还是差得远.

第二,是教学法的改变,不再是希腊和罗马学校的教法.
	ABC组合法:先单个字母,再组合成语言.

Phonic法: word被识别为声音而不是字母(音标的出现)

visual法: 认整个单词,整个句子,而不是字母.
	但是发现oral reading和silent reading还是不同.会oral reading,不一定会silent reading, vice versa. 

这些方法有些学生成功,有些失败.失败引来了对于学校的批评.这是第三个历史原因.

批评家不总是对的,但是教育公民的问题显得很迫切,导致很多高中和大学的出现.
阅读不行是本人的事, 但是在学校也是老师和同学的事情.

因此,各种方法在当代就被不停实验.

*** Stages of Learning to Read
孩子成熟阅读的进程:
	1. reading readiness: 0-6 上幼儿园之前
		 注意,如果孩子不愿意去学,千万别强行教.强行教的后果是以后都不爱学了,甚至会带到成年.
	2. read very simple materials
	3. symbols: vocabulary building and increasing skill"根据上下文猜不认识的词"
	4. 1-3增强,可以从不同的材料中提取概念,看相同科目的不同的作者.
		 成熟期,应该在青少年达到,余生持续.

*** Stages and Levels
~

reading readiness对应学前教育
word master对应一年级
vocabulary growth and the utilization of conext对应二到五年级.
mature: 6-8年级
到成熟期后,可以在知识量不那么多的情况看所有书了.

可是即便是成熟期了,仍然只是在elementary level

stage4靠老师就够了,但是接下来就得靠他自己了.

*** Higher Levels of Reading and Higher Education

** 4 The Second Level of Reading: Inspectional Reading
Inspectional Reading是一个真正的阅读等级,和elementary reading,analytical reading完全不同, 但是他们存在逐级包含的关系.

想要Inspectional Reading, 那elementary reading必须过关.
不能查太多单词和语法,句子大致的意思得懂不用完全懂.
	wusd:看英文书某章之前,有必要完全扫一遍,搞定单词和语法.

~

What is involved in inspectional reading? How do you do it?
	wusd: Systematic Skimming & Superficial Reading

inspectional reading的技能是一个技能,但现在作为初学者,还是分开好,等有经验了再综合.

*** Inspectional Reading I: Systematic Skimming or Pre-reading
有本新书摆在你面前,第一件事你要做什么?

一种场景: 1.你不知道怎么书值不值得Analytical Reading, 是否有insight和information值得你去dig out

2. 你只有有限时间去搞清楚值不值这个事

在这种场景,一定要skim or pre-reading it.
能搞清是否值得继续读,即使不继续读也能得到书的很多信息.

skim书能让你知道作者大意是什么,书的类型是什么,这样时间没有被浪费.

Some suggestion about how to skim it:
	1. 快速看封面和前言.
		 注意看: 副标题~书内容的范围~书的目标~作者在这个subject的独特视角.
		 目标: 对subject了解,给书分类.
	2. 学!目录.
		 注意: 不要只在查内容的时候才看目录,大部分作者对目录都非常用心的
		 目标: 生成a road map
	3. 看索引
		 看索引的terms的范围,判断一下最重要的terms以及目录提到的terms
	4. 看发行商的书边
		 --------------------
		 做完这4步后,合下书,问问自己还看不看这本书了
	5. 看重要章节, 仔细看章节的开头和结尾总结性的句子.
	6. 开始看书的内容了,但是一次只能看个一两段,按顺序看.
		 不要漏掉最后几页,因为作者总是会总结一下.

这样看,几分钟绝对不超过一个小时(实际不止,因为英文水平不行).

多少次,你看未知领域的书一片茫然?
你按这个方法走, 绝对不会出现这种情况,这是非常积极主动的阅读.

把自己当作一个侦探在寻找书的主旨,任何能帮你实现这个目标的线索都要警醒.


*** Inspectional Reading II: Superficial Reading
标题是故意起Superficial的,而且我们是认真的

很多人第一次看难书总是非常挣扎,很自然得出结论自己看这种书是种错误.
其实看书不是错误,而是第一次看就不该带那么高期望,方法也错了.

正确的方法是: 第一次处理一本难书,从头到尾看一遍,不要去查也不会去深思不懂的东西.
wusd: 有点类似考试,也把容易的题目做了再说

简单来说,遇到不懂的就跳过,懂的就抓牢来.不要因为自己错过一些内容就灰心丧气,如果你自己想啃下难点,会被困在里面.
啃下难点,要等到第二步了.
wusd: 跟拼图一样,先把能拼好的拼好,不能拼好的一直卡着只会浪费时间,后面难拼的第二边也许就能拼好了.
	那么小时候坚持为什么就能行呢? 因为小时候没有遇到真正的困难!

这么略读的好处就是,之前懂的一部分,有助于你后面的部分;即便是没有有助你后面的部分,懂一部分总比卡住什么都不懂要好.

从小到大被教育要克服困难,不懂的词就查,不会的就查百科全书.
但是就阅读而言,这个只会阻碍我们读书.

~

太执着于细节,就会只见树木不见森林.You will not be reading well on any level.
wusd: 可以看Games Theory for general reader

*** On Reading Speeds
Inspection Reading就是在限制时间内得到书的主旨.
不论这个书他有多难,合格的reader会尽快的把inspectional reading完成.

the levels of reading and speed reading courses?

speed course仅仅是补一下elementary reading,不够

好的speed course应该是教你根据内容的性质和复杂程度来决定快慢的.

好多烂书连skimming都不配, speed reading可以解决它.
但是,阻碍理解的困难:wusd: 有必要放进去reading levels
	- does not know what to do when approaching a difficult ???
		跳过
	- does not know the rules of reading ???
		第一遍,懂得过,不懂的扔
	- does not know how to marshal his intellectual resources for the task
	- does not know what he is looking for and does not know when he has found it
		带着问题去读书

关于阅读速度,是能够用不同速度阅读,知道什么时候用合适的速度.
wusd: 好比是开车,要兼顾安全性和速度,有调速度的技能+要知道什么路该快~什么路该慢.
inspectional reading很快是因为读的内容少(目录/简言...),用不同的方法阅读(superficial),带着不同的目标(主旨)
analytical reading就要像老司机一样开不同的档了.

*** Fixations and Regressions
wusd: 不看

*** The Problem of Comprehension
阅读速度是上来了,理解呢?
wusd: 阅读的目地是为了理解

积极阅读的一个activity: with concentration

单单concentration只能解决elementary reading的问题.
speed reading courses并没有解决comprehension更高级的问题.

~

对于抽象和修辞的词,应该快速带过.

~

阅读速度的问题就是理解的问题. analytical reading就是解决理解的问题,没有analytical reading你就不能理解一本书.


*** Summary of Inspectional Reading
有能力按不同速度阅读+知道什么时候什么速度阅读是最理想的.
Every book should be read no more slowly than it deserves, and no more quickly than you can read it with satisfaction and comprehension.

skimming必做,可以得到书的主旨和结构.

不要第一次就尝试啥都懂,难书就要多读几遍.superficial on inspectional reading

--------------------
inspectional reading在syntopical reading很重要,到时候会回顾

inspectional reading是analytical readig 的两个stage
	1. systematical skimming: book's structure
	2. superficial reading: the first step in the interpretation of book's contents

下一步要谈谈read actively里的activities了.

** 5 How to be a Demanding Reader

** 21 Reading and the growth of the mind
	
More active reading is, the better it is.
Active reading is the asking of question.

Lower levels of reading is contained in higer ones.
Analytical reading is the most unfamiliar for most readers,
		whose things always applies syntopical reading with certain adaptations,
	so that we discussed it at a great length.

This is a practical books containing the rules of inspectional, analytical, and syntopical reading
	which you should practice on purpose if you accept.

*** What Good Books Can Do for Us
You should have not only the things you read but the method to apply to them as well. 

The method including analytical and syntopical reading doesn't apply to every book
	which do not require it.

You must read books beyond you or you will not be a better reader,
	for unless you stretch your mind you will not learn.

You mustn't expect to get any improvement in reading skills from the books
	that provide you with no more amusement.
Reading a book full of information doesn't either,
	for your mind is merely fuller of facts but not stretched when you read it.

Don't fear the books that make demands on you,
	because the rules we have described will tell to how to tackle them.
Besides, there are some very books you must find out
	which will continue to extend you no matter how good a reader you are.

The books that neverending challenge to your skills
	are not always ones in relatively unfamiliar fields or some scientific books.

If a book defies your efforts to analyze it, it's a bad book and no worth trying.

When you try to read a good book, you receive two kinds of reward:
	the improvement in your reading skill and the things about the world and yourself.

The greatest books can help you to think better about the knowledge beyond you,
	because the authors of these thought better than you.

*** The Pyramid of Books
There are more than 99 percent of books written in the Western tradition
		that don't impore your skill in reading and only provide amusement or information,
	as you don't have to read them analytical at all and only skim.

The good books which make severe demands on you and are worth read analytically once
	are less than one in a thousand.

How to know that if a book is only good book?
After having read it, you're grateful to what it has given you, but you know that's all.

There are of the few thousand such books even smaller number.
After reading it analyticall to the best of you ability and placing it back on the shelf,
		you keep thinking about it and your reaction to you
			so that you obligation as an analytical reader takes you back to the book to find more.

A return of the second class of book is inevitably disappointing,
	for the book has not changed but your mind is fuller.

It seems that the books of the highest class have grown with you,
	for you can always see something new that you didn't see before.

The great book may be so far above you that it can lift you over and over again until you die.

People have different tastes, so you may never feel about an author the way you feel about others.

We have listed those books that may have this kind of value for many readers.
You need to seek out the few books that can have this value for you.

*** The Life and Growth of the Mind
Which ten books would you select before
	being marooned on a desert island for the rest of your life?

List it, there would be just you and ten books.

To a extent, we are marooned on a desert island.

The mind doesn't cease growing before the brain itself loses its vigor.

If you mind is not used, it can atrophy.
Som people who were kept alive by external force like the demands of their work
	die so soon after their retiremnet.

As all the sources of amusement and informaion surrounding us are artificial props like drugs,
	if we get used to them, and they have little or no effect, we cease to grow and begin to die.

Reading actively is not the way to advance our career but keep our minds alive and growing.

*** questions
新概念并不是一本great的书,how to read a book说只需看一遍, 而我们却需要读百遍, 想知道这种区别在哪里?
