#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
** 21 Reading and the growth of the mind

More active reading is, the better it is.
Active reading is the asking of question.

Lower levels of reading is contained in higer ones.
Analytical reading is the most unfamiliar for most readers,
		whose things always applies syntopical reading with certain adaptations,
	so that we discussed it at a great length.

This is a practical books containing the rules of inspectional, analytical, and syntopical reading
	which you should practice on purpose if you accept.

*** What Good Books Can Do for Us
You should have not only the things you read but the method to apply to them as well. 

The method including analytical and syntopical reading doesn't apply to every book
	which do not require it.

You must read books beyond you or you will not be a better reader,
	for unless you stretch your mind you will not learn.

You mustn't expect to get any improvement in reading skills from the books
	that provide you with no more amusement.
Reading a book full of information doesn't either,
	for your mind is merely fuller of facts but not stretched when you read it.

Don't fear the books that make demands on you,
	because the rules we have described will tell to how to tackle them.
Besides, there are some very books you must find out
	which will continue to extend you no matter how good a reader you are.

The books that neverending challenge to your skills
	are not always ones in relatively unfamiliar fields or some scientific books.

If a book defies your efforts to analyze it, it's a bad book and no worth trying.

When you try to read a good book, you receive two kinds of reward:
	the improvement in your reading skill and the things about the world and yourself.

The greatest books can help you to think better about the knowledge beyond you,
	because the authors of these thought better than you.

*** The Pyramid of Books
There are more than 99 percent of books written in the Western tradition
		that don't impore your skill in reading and only provide amusement or information,
	as you don't have to read them analytical at all and only skim.

The good books which make severe demands on you and are worth read analytically once
	are less than one in a thousand.

How to know that if a book is only good book?
After having read it, you're grateful to what it has given you, but you know that's all.

There are of the few thousand such books even smaller number.
After reading it analyticall to the best of you ability and placing it back on the shelf,
		you keep thinking about it and your reaction to you
			so that you obligation as an analytical reader takes you back to the book to find more.

A return of the second class of book is inevitably disappointing,
	for the book has not changed but your mind is fuller.

It seems that the books of the highest class have grown with you,
	for you can always see something new that you didn't see before.

The great book may be so far above you that it can lift you over and over again until you die.

People have different tastes, so you may never feel about an author the way you feel about others.

We have listed those books that may have this kind of value for many readers.
You need to seek out the few books that can have this value for you.

*** The Life and Growth of the Mind
Which ten books would you select before
	being marooned on a desert island for the rest of your life?

List it, there would be just you and ten books.

To a extent, we are marooned on a desert island.

The mind doesn't cease growing before the brain itself loses its vigor.

If you mind is not used, it can atrophy.
Som people who were kept alive by external force like the demands of their work
	die so soon after their retiremnet.

As all the sources of amusement and informaion surrounding us are artificial props like drugs,
	if we get used to them, and they have little or no effect, we cease to grow and begin to die.

Reading actively is not the way to advance our career but keep our minds alive and growing.

*** questions
新概念并不是一本great的书,how to read a book说只需看一遍, 而我们却需要读百遍, 想知道这种区别在哪里?
