#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 21 Daniel Mendoza
#+begin_verse
How many unsuccessful attempts did Mendoza make before becoming Champion of all England?

Boxing matches were very popular in England two hundred years ago.
In those days, boxers fought with bare fists for prize money.
Because of this, they were known as 'prizefighters'.
However, boxing was very crued, for there were no rules
	and a prizefighter could be seriously injured or even killed during a match.

One of the most colourful figures in boxing history was Daniel Mendoza, who was born in 1764.
The use of gloves was not introduced until 1860,
	when the Marquis of Queensberry drew up the first set of rules.
Though he was technically a prizefighter,
		Mendoza did much to change crude prizefighting into a sport,
	for he brought science to the game.
In his day, Mendoza enjoyed tremendous popularity.
He was adored by rich and poor alike.

Mendoza rose to fame swiftly after a boxing match when he was only fourteen years old.
This attracted the attention of Richard Humphries who was then the most eminent boxer in England.
He offered to train Mendoza and his young pupil was quick to learn.
In fact, Mendoza soon became so successful that Humphries turned agaginst him.
The two men quarrelled bitterly and it was clear that the argument could only be settled by a fight.
A match was held at Stilton, where both men fought for an hour.
The public bet a great deal of money on Mendoza, but he was defeated.
Mendoza met Humphries in the ring on a later occasion and he lost for a second time.
It was not until his third match in 1790
	that he finally beat Humphries and became Champion of England.
Meanwhile, he founded a highly successful Academy and even Load Byron became one of his pupils.
He earned enormous sums of money and was paid as much as 100 dollars for a single appearance.
Despite this, he was so extravagant that he was always in debt.
After he was defated by a boxer called Gentleman Jackson, he was quickly forgotten.
He was sent to prison for failing to pay his debts and died in poverty in 1836.
#+end_verse

** words
boxing [ЛҲbЙ‘ЛҗksЙӘЕӢ] n. жӢіеҮ»
boxer [ЛҲbЙ‘ЛҗksЙҷr] n. жӢіеҮ»жүӢ
bare [ber] adj. иөӨиЈёзҡ„
prizefighter [ЛҲpraЙӘzfaЙӘtЙҷr] n. иҒҢдёҡжӢіеҮ»жүӢ
crude [kruЛҗd] adj. зІ—йҮҺзҡ„
marquis [ЛҲmЙ‘ЛҗrkwЙӘs] n. дҫҜзҲө
technically [ЛҲteknЙӘkli] adv. дёҘж јең°;жҠҖжңҜең°
science [ЛҲsaЙӘЙҷns] n. з§‘еӯҰ
popularity [ЛҢpЙ‘ЛҗpjuЛҲlГҰrЙҷti] n. еҗҚжңӣ
adore [ЙҷЛҲdЙ”Лҗr] v. еҙҮжӢң,зҲұжҲҙ
alike [ЙҷЛҲlaЙӘk] adv. дёҖж ·ең°
fame [feЙӘm] n. еҗҚеЈ°
eminent [ЛҲemЙӘnЙҷnt] adj. и‘—еҗҚзҡ„
bitterly [ЛҲbЙӘtЙҷrli] adv. еҺүе®іең°
bet [bet] v. жү“иөҢ
academy [ЙҷЛҲkГҰdЙҷmi] n. дё“дёҡеӯҰж Ў
extravagant [ЙӘkЛҲstrГҰvЙҷЙЎЙҷnt] adj. жөӘиҙ№зҡ„
poverty [ЛҲpЙ‘ЛҗvЙҷrti] n. иҙ«еӣ°зҡ„

** еҚ•иҜҚйҖ еҸҘ
** еҸҚеӨҚеҗ¬з”өеҪұзүҮж®өзӣҙеҲ°жҮӮе…ій”®еҸҘ
** еӨҚд№ дәҢеҶҢиҜӯжі•(з¬”и®°жҲ–и§Ҷйў‘) & зәўзҡ®д№Ұ
** д№ жғҜз”Ёжі•йҖ еҸҘ
** и·ҹиҜ» 50йҒҚ
** Comprehension еҸҚеӨҚз»ғд№ 
** Ask me if еҶҷ+иҜ»
** ж‘ҳиҰҒеҶҷдҪң еҶҷ & еҜ№зӯ”жЎҲ
** tell the story еҸЈиҜӯеӨҚиҝ°
** composition йҳ…иҜ» жҲ– еҶҷдҪң
** Topics for discussion
