#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L21 Daniel Mendoza
#+begin_verse
How many unsuccessful attempts did Mendoza make before becoming Champion of all England?

Boxing matches were very popular in England two hundred years ago.
In those days, boxers fought with bare fists for prize money.
Because of this, they were known as 'prizefighters'.
However, boxing was very crued, for there were no rules
	and a prizefighter could be seriously injured or even killed during a match.

One of the most colourful figures in boxing history was Daniel Mendoza, who was born in 1764.
The use of gloves was not introduced until 1860,
	when the Marquis of Queensberry drew up the first set of rules.
Though he was technically a prizefighter,
	Mendoza did much to change crude prizefighting into a sport,
	for he brought science to the game.
In his day, Mendoza enjoyed tremendous popularity.
He was adored by rich and poor alike.

Mendoza rose to fame swiftly after a boxing match when he was only fourteen years old.
This attracted the attention of Richard Humphries who was then the most eminent boxer in England.
He offered to train Mendoza and his young pupil was quick to learn.
In fact, Mendoza soon became so successful that Humphries turned agaginst him.
The two men quarrelled bitterly and it was clear that the argument could only be settled by a fight.
A match was held at Stilton, where both men fought for an hour.
The public bet a great deal of money on Mendoza, but he was defeated.
Mendoza met Humphries in the ring on a later occasion and he lost for a second time.
It was not until his third match in 1790
	that he finally beat Humphries and became Champion of England.
Meanwhile, he founded a highly successful Academy and even Load Byron became one of his pupils.
He earned enormous sums of money and was paid as much as $100 for a single appearance.
Despite this, he was so extravagant that he was always in debt.
After he was defated by a boxer called Gentleman Jackson, he was quickly forgotten.
He was sent to prison for failing to pay his debts and died in poverty in 1836.
#+end_verse

** words
boxing [ˈbɑːksɪŋ] n. 拳击
boxer [ˈbɑːksər] n. 拳击手
bare [ber] adj. 赤裸的
prizefighter [ˈpraɪzfaɪtər] n. 职业拳击手
crude [kruːd] adj. 粗野的
marquis [ˈmɑːrkwɪs] n. 侯爵
technically [ˈteknɪkli] adv. 严格地;技术地
science [ˈsaɪəns] n. 科学
popularity [ˌpɑːpjuˈlærəti] n. 名望
adore [əˈdɔːr] v. 崇拜,爱戴
alike [əˈlaɪk] adv. 一样地
fame [feɪm] n. 名声
eminent [ˈemɪnənt] adj. 著名的
bitterly [ˈbɪtərli] adv. 厉害地
bet [bet] v. 打赌
academy [əˈkædəmi] n. 专业学校
extravagant [ɪkˈstrævəɡənt] adj. 浪费的
poverty [ˈpɑːvərti] n. 贫困的
