#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 22 By heart
#+begin_verse
Which actor read the letter in the end, the aristocrat or the jailer?

Some plays are so successful that they run *for years on end*.
*In many ways*, this is unfortunate for the poor actors
	who *are required to go* on repeating the same lines night after night.
One would *expect them to know their parts by heart* and never *have cause to* falter.
Yet this is not always the case.

A famous actor in a highly successful play *was once cast in the role of* an aristocrat
	who had been imprisoned in the Bastille for twenty years.
In the last act, a jailer would always come on to the stage with a letter
	which he would hand to the prisoner.
Even though the noble was expected to read the letter at each performance,
	he always *insisted that it should be written out in full*.

One night, the jailer decided to *play a joke on* his colleague to find out
	if, after so many performances, he had managed to learn the contents of the letter by heart.
*The curtain went up* on the final act of the play
	and revealed the aristocrat sitting alone behind bars in his dark cell.
Just then, the jailer appeared with the precious letter in his hands.
He entered the cell and *presented the letter to* the aristocrat.
But the copy he gave him had not been written out in full as usual.
It was simply *a blank sheet of paper*.
The jailer *looked on* eagerly, *anxious to see* if his fellow actor had *at last* learnt his lines.
The noble *stared at* the blank sheet of paper for a few seconds.
Then, squinting his eyes, he said: 'The light is dim. Read the letter to me.'
And he promptly handed the sheet of paper to the jailer.
Finding that he could not remember a word of the letter either,
	the jailer replied: 'The light is indeed dim, sire. I must get my glasses.'
With this, he hurried off the stage.
*Much to the aristocrat's amusement*,
	the jailer returned a few moments later
		with a pair of glasses and the usual copy of the letter
			which he *proceeded to read to the prisoner*.
#+end_verse

** words
run [rʌn] v. 连演
lines [laɪnz] n. 台词
part [pɑːrt] n. 剧中的角色,台词
falter [ˈfɔːltər] v. 支吾
cast [kæst] v. 选派...扮演角色
role [roʊl] n. 角色
aristocrat [əˈrɪstəkræt] n. 贵族
imprison [ɪmˈprɪzn] v. 关押
Bastille [bæsˈtil] n. 巴士底狱
jailer [ˈdʒeɪlər] n. 监狱长
colleague [ˈkɑːliːɡ] n. 同事
curtain [ˈkɜːrt(ə)n] n. (舞台上的)幕布
reveal [rɪˈviːl] v. 使显露
cell [sel] n. 单人监房
blank [blæŋk] adj. 空白的
squint [skwɪnt] v. 眯着(眼)看,瞄 
dim [dɪm] adj. 昏暗
sire [ˈsaɪər] n. 陛下
proceed [proʊˈsiːd] v. 继续进行

** vocabulary
run: are performed regularly
on end: without a break, continuously
are required: are expected, have to
repeating: saying again
falter: make a mistake, say in a weak manner, stumble
role: part character
hand: give
in full: completely

** DONE 单词造句
CLOSED: [2023-11-29 Wed 18:59]
run ran run v.
1. It is clear that the play ran for years.
2. Although the play he made ran for years, he was still in debt.
3. Much to his surprise, the play has run for years.
4. He was required to repeat the same lines, because the play has been running for years.
5. After the agrument was settled, the play would run for years.
lines n.
1. He was tired of reading the same lines over and over again.
2. She is always repeating the same lines for one reason or another.
3. He is gonna stay out of limelight to prevent himself from reading the same lines.
4. The actor arrived on the scene and was quick to read the lines.
5. In fact, you has brought the lines to your life.
part n. role n.  play the role of
1. My aunt Jerry will be playing a part in a comedy show.
2. It is said that the famous actor doesn't know his parts at all.
3. You should have known your parts by heart.
4. I needn't have known my parts by heart.
5. I'm glad that you played a part in the movie. 
falter v.
1. My voice is always faltering when I apologize to anyone.
2. It was not until 3 years old that my voice didn't falter any more.
3. Because of being nervous, my voice was quick to falter.
4. Inspite of knowing the lines by hearts, his voice still faltered on the stage.
5. In his day, his voice never falter on a TV show.
cast cast cast v.  sb. be cast in the role of = cast sb. in the role of
1. In fact, the actor was soon cast in the role of Homes.
2. Technically speaking, he was never cast in the role of a waiter.
3. He will be cast in the role of Humphries who fought with his bare fists for prize money.
4. He was cast in the role of a kidnapper who took interest in a cat.
5. He has been cast in the role of a pilot who was picked up by a ship.
aristocrat n.
1. The aristocrat made an attempt to fly to Paris.
2. The aristocrat had his head cut because of angry crowd.
3. The aristocrat offered a basket of food to the poor.
4. The aristocrat was adored by poor and rich alike.
5. The aristocrat was supposed to win a prize of $1000.
imprison v.
1. I feared that I would be imprisoned by the local authorities.
2. The actor who was imprisoned rose to fame swiftly because of drugs.
3. She complained bitterly that the police imprison her husband who was innocent.
4. She claimed to have imprisoned her husband.
5. On the same day, the journalist was imprisoned by the government.
Bastille n.
jailer n.
1. It looked as if the jailer was fast asleep.
2. The jailer was forced to read the lines.
3. The jailer refused to offer paper to the aristocrat.
4. Somehow, the jailer has led a extravagant life.
5. The jailer was very kind in more ways than one.
colleague n.
1. The colleague was unwilling to follow his instructions.
2. The colleague got very worried and changed his mind.
3. The colleague was reluctant to share his meat with his boss.
4. The colleague was said to commit a murder.
5. The colleague made a complaint and remained anonymous.
curtain n.  the curtain goes up/rises/comes down/falls
1. However, when the curtain went up the actress was still naked.
2. After the curtain come down, the crowd left in an orderly fashion.
3. Although the curtain has went up, the group of pop singer was still fast asleep.
4. It astounded him that the curtain went up at the mignight.
5. The curtain went up, a kidnapper was asking a wealthy lady for a ransom of $1000.
reveal v.
1. He explained that this would reveal the secret of volcanoes.
2. It occurred to him to reveal the contents of the box. 
3. He revealed the money in microwave oven for safekeeping.
4. The curtain went up and revealed the dustman who worked for a big corporation.
5. The story reveals a special type of fish.
cell n.
1. The policeman threatened to keep me in a cell for a night.
2. Imagine the jailer's dismay when he found that the cell had been empty.
3. For your own protection, you'd better stay in the cell.
4. The aristocrat who died in the cell will be given a state funeral.
5. The dustman was impatient to clean up the cell because he was greeted by an unpleasant smell.
blank adj.  a blank sheet of paper
1. The couple quarrelled bittery and the boy handed a blank sheet of paper to his wife.
2. Why don't you present a blank sheet of paper to me?
3. He complained bitterly why the jailer had presented a black sheet of paper to him.
4. Don't hand in a blank sheet of paper.
5. The teacher was always complaining that his student handed in a blank sheet of paper.
squint v.  squinting at
1. Squinting at her, he said: "Don't be too hard on us."
2. Squinting his eyes, he tried to figure out who it was.
3. Tired of squinting at the black board, he asked his parent for glasses.
4. Squinting his eyes, he finally recognized that there was a cat.
5. He squinted his eyes and said in a weak voice.
dim adj.  in the dim light
1. I used to make myself comfortable in the dim light.
2. I am genuinely sorry that I set the house on fire in the dim light. 
3. He covered his car with blanket in the dim light.
4. He managed to read the lines by heart in the dim light.
5. He read the book over and over again in the dim light.
sire n.
proceed v.  proceed to do sth.
1. He proceeded to play truant form school.
2. He proceeded to take the exam.
3. The policeman arrived on the scene and kept order.
4. He proceeded to study English.
5. He proceeded to drink milk.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-29 Wed 20:01]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-29 Wed 18:59]
for days/hours/years on end
1. It may last for days on end.
2. The workers were trapped in the mine for hours on end.
3. You have been peeing for minutes on end.
4. The window has been open for years on end.
5. My colleague felt sorry for days on end.
in many ways
1. I and my wife deal with work alike in many ways.
2. He was regarded as a special type of hero in many ways.
3. The prizefighter was considered as a pioneer in many ways.
4. In many ways, we managed to make it official.
5. You did give me a surprise in many ways.
be required to do sth.
1. He was required to leave Zhengzhou promptly.
2. They are not require to make any remarks.
3. The bull was required to charge at the dog.
4. We have been requiring to wear masks for over two years.
5. You are required to stop while I am tapping on the window.
expect sb. to do sth./ sb. be expected to do sth.
1. I expected my examiner to tap on the window.
2. Let's suppose that you're expected to risk your life.
3. Let's suppose that your mother expected you to follow in your father's footstep. 
4. I never expected my father to offer me a house.
5. I was wondering what I was expected to do last weekends.
learn/know sth. by heart
1. I was wondering whether you had leant the lines by heart.
2. I needn't read it, for I have already known it by heart. 
3. If you knew the lines by heart, the girls would be following you around.
4. The noise you make is preventing me from learning the lines by heart.
5. It is no use pretending that you had learnt it by heart.
have cause to do sth.
1. I never have cause to prevent me from meeting him.
2. I never have cause to avoid doing housework.
3. He had cause to set up his camp.
4. I have cause to find out the fact.
5. I have cause to tell hime the story.
sb. insisted that + ...(should) do (虚拟语气)
1. He insisted that I deal with the task.
2. My boss insisted that we be on time.
3. He insisted that we book the seats in advance. 
4. My cat insisted that I play football with her.
5. She insisted that he be dressed up as a girl.
sb. insisted that + ...(非虚拟)
1. I insisted that he played truent from school.
2. She insisted that he squinted at her.
3. She insisted that he played a joke on her.
4. She insisted that there was a cat.
5. She insisted that the actress would be cast in the role of Homes.
be written out in full
1. It should have been written out in full.
2. Inspite of this, he always writes it out in full.
3. I'm genuinely sorry that I didn't write it out in full.
4. I'm gonna write it out in full.
5. There is an element of truth in this idea that it should be written out in full.
play a joke on sb.
1. She insisted on playing a joke on him.
2. We will have an opportunity to play a joke on him.
3. I realized to my horror that she had played a joke on me.
4. She is tolerent of being played jokes on.
5. Because she played a joke on her father, she was not allowed to ask for pocket money that week.
present sth. to sb.
1. Why don't you present a bottle of perfume to your wife.
2. As soon as the order is given, I will present the paper to him.
3. France presented the famous monument to America in 1993.
4. They have one thing in common: they all presented a gift to the woman.
5. I'm tired of presenting gifts to my wife.
look on
1. Would you mind my looking on?
2. It seemed that you just looked on when the robbery happened.
3. The workers looked on while the gangsters was going through the contents of bag.
4. Fearing of being hurt, everyone in bus just looked on and let the gangsters go.
5. Because everyone looked on, three kids died from the accident.
at last
1. At last, I have solved the problem of ventilation.
2. At last, they put forward a plan.
3. At last, she was on the way home.
4. At last, she has a large circle of friends.
5. At last, his father admired him for breaking the world record.
be anxious to do sth. = be eager to do sth.
1. He is anxious to make a speech.
2. He is anxious to tell stories at the reception.
3. He is anxious to get his children under control.
4. He is anxious to meet her.
5. He is anxious to remove the button from the gate.
stare at
1. She complained bitterly that a man was staring at her at the reception.
2. The fortune-teller stared at him and told him something in the future.
3. There was a beggar staring at me at a village fair. 
4. I used to stare at sweets at a village fair.
5. It seems that she is staring at something crystal clear.
read sth. to sb.
1. My father never failed to read the books to me.
2. I spent a hour reading articles to my cat.
3. I have trained my daughter to read the book to me.
4. I was required to read the book to my father on Friday afternoon.
5. The fortune-teller is reading mystery to me at a village fair.
much to sb's sth.
1. Much to my surprise, she has a habbit of wandering around.
2. Much to my amusement, she managed to drink the water in the toilet.
3. Much to my dismay, she didn't pass the test again.
4. Much to my dismay, she has objected that he should get a good salary.
5. Much to my dismay, I was fired.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-29 Wed 20:01]
** DONE Ask me if 写+读
CLOSED: [2023-11-29 Wed 20:09]
1. Some plays are so successful that they run for years on end. How successful
	 How successful are some plays?
2. Actors are expected to go on repeating the same lines night after night. What
	 What are actors expected to do night after night?
3. The aristocrat had been imprisoned in the Bastille for twenty years. How long
	 How long had the aristocrat been imprisoned in the Bastille?
4. The jailer always handed the prisoner a letter in the last act. Who
	 Who did the jailer always hand a letter in the last act?
	 Who always handed the prisoner a letter in the last act?
5. The prisoner always insisted that the letter should be written out in full. What
	 What did the prisoner always insist?
6. The jailer decided to play a joke on his colleague. Who
	 Who decided to play a joke on his colleague?
	 Who did the jailer decide to play a joke on?
7. The jailer handed the prisoner a blank sheet of paper. What
	 What did the jailer hand the prisoner?
8. The jailer went off stage to get his glasses. Who
	 Who went off stage to get his glasses?
9. The aristocrat was amused. Why
	 Why was the aristocrat amused?
10. The jailer read the letter to the prisoner. What
		What did the jailer read to the prisoner?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-29 Wed 20:22]
The aristocrat was setting along behind bars in his cell.
The jailer entered the cell and presented a black sheet of paper to the aristocrat.
After having stared at it for a few seconds,
	he asked the jailer to read the letter to him.
After handed the pater,
	the jailered hurried off the stage, for he couldn't remember a word of the letter either.
A few moments later, the jailer returned with the usual copy of the letter
	and read to the aristocrat.

The aristocrat was sitting in his cell
	when the gaoler entered and handed him the letter -- a blank sheet of paper.
The aristocrat looked at it, squinted and said: 'The light is dim. Read me the letter.'
He handed the letter back to the jailer, who said: 'The light is indeed dim. I'll get my glasses.'
He left the stage and returned with a pair of glasses and the real letter,
	which he read to the prisoner.

** DONE tell the story 口语复述
CLOSED: [2023-11-29 Wed 20:27]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-29 Wed 20:28]
A couple of years ago, a new play called The World Tomorrow
	was going to be shown in our local theatre.
There was a great deal of advertising for it
	and there was considerable public interest,
	mainly, I think, because the cast contained a number of famous actors and actresses.
Most actors and actresses are usually nervous on the first night of any play,
	and no one really knows what can go wrong or how the audience will react.
In the case of The World Tomorrow, no one forgot their lines,
	but the play was not well received.
It was a comedy, so it was supposed to be funny,
	but nobody laughed----not in the right places anyway ----
	and people even walked out before the end.

The cast suspected that they would get bad reviews the following day, and they did.
One review described it as 'the saddest comedy I've ever seen':
	another thought it was
		'the most professionally acted disaster we have ever seen on our local stage'
In spite of the reviews, however, the play still ran for six weeks.
The last performance, on the last Saturday evening, attracted a small audience,
	and the actors struggled through to the end.
At the end of six terrible weeks, however, there was one final moment of relief.
When the last line was spoken:
	'Our six short weeks have hastened to their end,
		the audience saw the funny side of it and laughed.
		Even the actors and actresses laughed.

** Topics for discussion
