#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L22 By heart
#+begin_verse
Which actor read the letter in the end, the aristocrat or the gaoler?

Some plays are so successful that they run for years on end.
In many ways, this is unfortunate for the poor actors
	who are required to go on repeating the same lines night after night.
One would expect them to know their parts by heart and never have cause to falter.
Yet this is not always the case.

A famous actor in a highly successful play was once cast in the role of an aristocrat
	who had been imprisoned in the Bastille for twenty years.
In the last act, a gaoler would always come on to the stage with a letter
	which he would hand to the prisoner.
Even though the noble was expected to read the letter at each performance,
	he always insisted that it should be written out in full.

One night, the gaoler decided to play a joke on his colleague to find out
	if, after so many performances, he had managed to learn the contents of the letter by heart.
The curtain went up on the final act of the play
	and revealed the aristocrat sitting alone behind bars in his dark cell.
Just then, the gaoler appeared with the precious letter in his hands.
He entered the cell and presented the letter to the aristocrat.
But the copy he gave him had not been written out in full as usual.
It was simply a blank sheet of paper.
The gaoler looked on eagerly, anxious to see if his fellow actor had at last learnt his lines.
The noble stared at the blank sheet of paper for a few seconds.
Then, squinting his eyes, he said: 'The light is dim. Read the letter to me.'
And he promptly handed the sheet of paper to the gaoler.
Finding that he could not remember a word of the letter either,
	the gaoler replied: 'The light is indeed dim, sire. I must get my glasses.'
With this, he hurried off the stage.
Much to the aristocrat's amusement,
	the gaoler returned a few moments later
		with a pair of glasses and the usual copy of the letter
			which he proceeded to read to the prisoner.
#+end_verse

** words
run [rКҢn] v. иҝһжј”
lines [laЙӘnz] n. еҸ°иҜҚ
part [pЙ‘Лҗrt] n. еү§дёӯзҡ„и§’иүІ,еҸ°иҜҚ
falter [ЛҲfЙ”ЛҗltЙҷr] v. ж”Ҝеҗҫ
cast [kГҰst] v. йҖүжҙҫ...жү®жј”и§’иүІ
role [roКҠl] n. и§’иүІ
aristocrat [ЙҷЛҲrЙӘstЙҷkrГҰt] n. иҙөж—Ҹ
imprison [ЙӘmЛҲprЙӘzn] v. е…іжҠј
Bastille [bГҰsЛҲtil] n. е·ҙеЈ«еә•зӢұ
gaoler [ЛҲdК’eЙӘlЙҷr] n. зӣ‘зӢұй•ҝ
colleague [ЛҲkЙ‘ЛҗliЛҗЙЎ] n. еҗҢдәӢ
curtain [ЛҲkЙңЛҗrt(Йҷ)n] n. (иҲһеҸ°дёҠзҡ„)е№•еёғ
reveal [rЙӘЛҲviЛҗl] v. дҪҝжҳҫйңІ
cell [sel] n. еҚ•дәәзӣ‘жҲҝ
blank [blГҰЕӢk] adj. з©әзҷҪзҡ„
squint [skwЙӘnt] v. зңҜзқҖ(зңј)зңӢ,зһ„ 
dim [dЙӘm] adj. жҳҸжҡ—
sire [ЛҲsaЙӘЙҷr] n. йҷӣдёӢ
proceed [proКҠЛҲsiЛҗd] v. з»§з»ӯиҝӣиЎҢ

** еҚ•иҜҚйҖ еҸҘ
** еҸҚеӨҚеҗ¬з”өеҪұзүҮж®ө
** Pattern Drill еҶҷ+иҜ»
** з»ҷиҮӘе·ұи®Іи§Ј
** зәўзҡ®д№Ұ
** д№ жғҜз”Ёжі•йҖ еҸҘ
** и·ҹиҜ»иҮіиғҢиҜө
** Ask me if еҶҷ+иҜ»
** ж‘ҳиҰҒеҶҷдҪң
** tell the story еҸЈиҜӯ
** Topics for discussion
