#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L22 By heart
#+begin_verse
Which actor read the letter in the end, the aristocrat or the gaoler?

Some plays are so successful that they run for years on end.
In many ways, this is unfortunate for the poor actors
	who are required to go on repeating the same lines night after night.
One would expect them to know their parts by heart and never have cause to falter.
Yet this is not always the case.

A famous actor in a highly successful play was once cast in the role of an aristocrat
	who had been imprisoned in the Bastille for twenty years.
In the last act, a gaoler would always come on to the stage with a letter
	which he would hand to the prisoner.
Even though the noble was expected to read the letter at each performance,
	he always insisted that it should be written out in full.

One night, the gaoler decided to play a joke on his colleague to find out
	if, after so many performances, he had managed to learn the contents of the letter by heart.
The curtain went up on the final act of the play
	and revealed the aristocrat sitting alone behind bars in his dark cell.
Just then, the gaoler appeared with the precious letter in his hands.
He entered the cell and presented the letter to the aristocrat.
But the copy he gave him had not been written out in full as usual.
It was simply a blank sheet of paper.
The gaoler looked on eagerly, anxious to see if his fellow actor had at last learnt his lines.
The noble stared at the blank sheet of paper for a few seconds.
Then, squinting his eyes, he said: 'The light is dim. Read the letter to me.'
And he promptly handed the sheet of paper to the gaoler.
Finding that he could not remember a word of the letter either,
	the gaoler replied: 'The light is indeed dim, sire. I must get my glasses.'
With this, he hurried off the stage.
Much to the aristocrat's amusement,
	the gaoler returned a few moments later
		with a pair of glasses and the usual copy of the letter
			which he proceeded to read to the prisoner.
#+end_verse

** words
run [rʌn] v. 连演
lines [laɪnz] n. 台词
part [pɑːrt] n. 剧中的角色,台词
falter [ˈfɔːltər] v. 支吾
cast [kæst] v. 选派...扮演角色
role [roʊl] n. 角色
aristocrat [əˈrɪstəkræt] n. 贵族
imprison [ɪmˈprɪzn] v. 关押
Bastille [bæsˈtil] n. 巴士底狱
gaoler [ˈdʒeɪlər] n. 监狱长
colleague [ˈkɑːliːɡ] n. 同事
curtain [ˈkɜːrt(ə)n] n. (舞台上的)幕布
reveal [rɪˈviːl] v. 使显露
cell [sel] n. 单人监房
blank [blæŋk] adj. 空白的
squint [skwɪnt] v. 眯着(眼)看,瞄 
dim [dɪm] adj. 昏暗
sire [ˈsaɪər] n. 陛下
proceed [proʊˈsiːd] v. 继续进行

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
