#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 23 One man's meat is another man's poison 
#+begin_verse
What was it about snails that made the writer collect them for his friend on that day in particular?

People become quite illogical when they try to decide what can be eaten and what cannot be eaten.
If you lived in the Mediterranean, *for instance*, you would consider octopus a great delicacy.
You would not be able to understand why some people find it repulsive.
On the other hand, your *stomach would turn* *at the idea of* frying potatoes in *animal fat*
	-- the normally accepted practice in many northern countries.
*The sad truth is that* most of us have *been brought up to eat* certain foods
	and we *stick to them* all our lives.

No creature has *received more praise and abuse than* the common garden snail.
Cooked in wine, snails are a great luxury in various parts of the world.
There are countless people
	who, ever since their early years, have learned to *associate snails with food*.
My friend, Robert, lives in a country where snails are despised.
As his flat is in a large town, he has no garden of his own.
For years he has been asking me to collect snails from my garden and take them to him.
The idea never *appealed to me* very much, but one day, *after a heavy shower*,
	I happened to be walking in my garden
		when I *noticed* a huge number of snails *taking a stroll* on some of my prize plants.
Acting on a sudden impulse,
	I collected several dozen, put them in a paper bag, and took them to Robert.
Robert *was delighted to see* me and equally pleased with my little gift.
I left the bag in the hall
	and Robert and I went into the living room where we talked for a couple of hours.
I had forgotten all about the snails when Robert suddenly said that I must *stay to dinner*.
Snails would, of course, be the main dish.
I did not fancy the idea and I reluctantly followed Robert out of the room.
*To our dismay*, we saw that there were snails everywhere:
	they had escaped from the paper bag and had *taken complete possession of* the hall!
I have never been able to look at a snail since then.
#+end_verse

** words
poison [ˈpɔɪz(ə)n] n. 毒药
illogical [ɪˈlɑdʒɪk(ə)l] adj. 不合逻辑的，无章法的
octopus [ˈɑktəpəs] n. 章鱼
delicacy [ˈdelɪkəsi] n. 美味，佳肴
repulsive [riˈpʌlsiv] adj. 令人反感的，令人生厌的
stomach [ˈstʌmək] n.胃
turn [tɜrn] v.感到恶心，翻胃
fry [fraɪ] v.油炸
fat [fæt] n.（动物、植物）油
abuse [əˈbjus] n. 辱骂，责骂
snail [sneɪl] n. 蜗牛
luxury [ˈlʌkʃ(ə)ri] n. 奢侈品，珍品
associate [əˈsoʊʃiət] v. 联想到
despise [dɪˈspaɪz] v. 鄙视
appeal [əˈpil] v. 引起兴致
shower [ˈʃaʊər] n. 陈雨
stroll [stroʊl] n. 溜达，散步
impulse [ˈɪmˌpʌls] n. 冲动
dozen [ˈdʌz(ə)n] n. 12个，一打
fancy [ˈfænsi] v. 喜爱，喜欢

** vocabulary
illogical: unreasonable
instance: example
repulsive: disgusting
stick: stay with, remain with
various: different
associate: connect
appealed to: attracted

** DONE 单词造句
CLOSED: [2023-12-01 Fri 20:07]
One man's meat is another man's poison
illogical adj.  it is illogical to do sth.
1. It is illogical to stand to attention.
2. It is illogical to play the role of an aristocrat.
3. It is illogical to be cast in the role of an aristocrat.
4. It is illogical to present me a blank sheet of paper.
5. It is illogical to proceed to read the letter.
octopus n.
1. He insisted that we eat octopus.
2. He played a joke on me to find out if I eat octopus.
3. I have the privilege of eating octopus in North Korea.
4. I kept on eating octopus for one cause or another.
5. On the hand, the octopus was consider as a great delicacy.
delicacy n.
1. Snails are said to be considered as a delicacy in Italia.
2. He insisted that octupus was a great delicacy.
3. Much to my surprise, he considered cat as a delicacy.
4. It is clear that she regarded snail as a great delicacy.
5. She complained bitterly that her boyfriend regarded octopus as a great delicacy.
repulsive adj.
1. Oddly enough, I didn't find it repulsive any more.
2. The food is so repulsive that I cannot bear it.
3. I was greeted by a repulsive smell which convinced me that there was a dead cat.
4. I find you repulsive in more ways than one.
5. When he was greeted by a repulsive smell, he changed his mind.
stomach n. turn v.  turn sb's stomach  sick to my stomach
1. Don't be hard on us, for it would turn my stomach.
2. Climb mountain always turns my stomach.
3. It should have turned my stomach.
4. I was forced to repeat the same lines, it turned my stomach a great deal.
5. He was picked up by a ship which has turned his stomach.
fry v.
1. My wife made every effort to fry a great piece of steek.
2. It looked as if I had fried your steek.
3. On the same day, we was forced to fry potatoes.
4. Considering the lack of oil, they decided not to fry potatoes tonight.
5. He explained that the steek had just been fried for a long time.
fat n.  animal fat
1. The food is full of animal fat and salt.
2. I am going to avoid food in high animal fat to lose my weight.
3. I bet you are avoiding food in high animal fat.
4. Both of you are avoiding food in high animal fat alike.
5. He insisted that we should eat more food in high animal fat.
abuse n.  a. received more abuse than
1. No one will receive more abuse than you after you fail to break the world record.
2. No one has received more abuse than the sportman who didn't become a champion in Olympics Games. 
3. I received more abuse than you who played truent from school.
4. I received more abuse than anyone who didn't pass the test.
5. The busmen who go on a strike have received more abuse than anyone in the town.
snail n. associate v.  associate a. with b.
1. It's no use pretenting that you hadn't eatten a snail.
2. I want to express my gratitude to a friend who have provided me with dozens of snails.
3. She has objected that we would eat snails in the dinner.
4. I was really under a lot of pressure when you asked me to eat a snail.
5. Techinally speaking, I found snails repulsive a great deal.
luxury n.
1. People in China always regard books as a necessity, not a luxury.
2. After making large sums of money, he succeeded in leading a life of great luxury.
3. The vicar is always raising money to lead a life of great luxury.
4. The vicar led such a life of luxury that he was always in debt.
5. I confirmed that she led a life of great luxury abroad.
despise v.
1. I hate to despise anyone.
2. She despised her neighbor who was trying to put her out of business.
3. If you took that tone with me, I would despise you.
4. It comes as a surprise to lean that my wife despises me.
5. She despised her husband and burst out laughing.
appeal v.  appeal to sb.
1. At the beginning of the programme, the host didn't appeal to me.
2. The idea of living abroad really appeals to me.
3. A variety of toys will appeal to your children in the mall.
4. The host will do anything to appeal to you.
5. The comedy show never failed to appeal to me.
shower n.  After a heavy shower ...  be in the shower/take a shower
1. After a heavy shower, she asked me to stay for a dinner.
2. As it is, I was being in the shower.
3. On the surface, he was taking a shower.
4. The girl loves to take a shower moving in a circle .
5. On the following morning, she has taken a shower.
stroll n.  take a stroll  go for a stroll
1. I'm reluctant to take a stroll with my grandparents.
2. She happened to be taking a stroll.
3. It is considered unlucky for people in Japan taking a stroll during the festival.
4. The lady claimed to see a puma taking a stroll.
5. It convinced me that my girlfriend was taking a stroll.
impulse n.  have the impulse to do sth.
1. I had the impulse to pay for my wife's journey to Maldives.
2. I always have the impulse to finish my work as quickly as possible.
3. I had the impulse to play piano last night.
4. I never had the impulse to quarrel with him.
5. I have had the impulse to take IELTS.
dozen n.  dozens of sth./sb.
1. I have got dozens of suit, but none of them is suit.
2. It cames as a surprise to lean that dozens of people was killed in the floods.
3. It seems that dozens of people was killed in the plane crush.
4. Dozens of boys gathered round in front of the police station.
5. It was said that dozens of workers were trapped in the mine.
fancy
1. I didn't fancy you told me the truth.
2. I didn't fancy the story you told me just now.
3. Fancy meeting you here.
4. I never fancy the idea of sharing a flat with her.
5. On the surface, she fancies the idea of fight with bare fists.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-01 Fri 20:19]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-01 Fri 20:07]
for instance
1. For instance, the doctor has commited a murder.
2. For instance, the old lady didn't have a perfect alibi.
3. For instance, your husband is telling the truth that he doesn't like you any more.
4. For instance, the train arrived on time.
5. For instance, everything goes smoothly.
at the idea of ...
1. My father was shocked at the idea of my breaking down his piano.
2. I was shocked at the idea of paying $1000 for my wife's vocation.
3. I am unhappy at the idea of his bothering me all day.
4. In spite of this, he was happy at the idea of his dear cat.
5. The detective was happy at the idea of having a perfect alibi.
The sad truth is that + ...
1. The sad truth is that we didn't get enough money to pay for a luxury vocation.
2. The sad truth is that the girl recognized a stranger as her boyfriend.
3. The sad truth is that the vicar is raising money for one cause or another.
4. The sad truth is that I have made tremendous mistakes.
5. The sad truth is that I don't pass the test once more.
be brought up to do sth.
1. I was not brought up to be polite in the dinner.
2. She was brought up to be responsible for what she had done.
3. We've been brought up to think that smoking in public is impolite.
4. She was brought up to fear operations.
5. I was brought up to fry chicken and steek.
stick to sth.
1. We should have sticked to our plan.
2. We needn't have sticked to our plan.
3. Leo is supposed to stick to the decision that he found a company.
4. We wasn't able to stick to our plan.
5. We managed to stick to our plan.
notice sb. doing sth.
1. I noticed him keeping calm.
2. I should have noticed him losing his nerve.
3. My teacher has noticed me losing my concentration.
4. He noticed the cat suffering from injury.
5. He noticed her losing her temper.
be delighted to do sth.
1. I am delight to light a cigarette.
2. She is delighted to offer me an audio player.
3. She was delighted to have an operation.
4. She was delighted to lead a normal life.
5. I am delighted to give him satisfaction in many ways.
stay to dinner = stay for dinner
1. You should have stayed to dinner.
2. May I ask you stay to dinner?
3. She explained that she just asked him to stay for dinner.
4. I was required to stay to dinner by my teacher.
5. Considering a heavy shower, I decided to stay to dinner.
to sb's dismay
1. To my dismay, she didn't follow in her mother's footstep.
2. To our dismay, she didn't keep her word again.
3. To my dismay, my cat yelled at me.
4. To my dismay, she bought the same type of dress on the same day.
5. To my dismay, I didn't win a prize of $1000.
take possession of sth.
1. If you didn't clean it up, snails would take possession of it.
2. If we can't pay for debts, the bank will take possession of our flat.
3. The monkey took possession the house, and forbid other to get close to it.
4. As soon as you take possession of the house property, you should have the locks changed.
5. She took possession of a room and double checked it.

** 跟读 50遍
** Comprehension 反复练习
** DONE Ask me if 写+读
CLOSED: [2023-12-01 Fri 20:26]
1. People in the Meterranean consider octopus a delicacy. Where
	 Where do peple consider octopus a delicacy?
2. Some people find octopus repulsive. What
	 What do some people find repulsive?
3. Most of us have been brought up to eat certain foods. How
	 How have most of us been brought up?
4. My friend Robert lives in a flat in a large town. Where
	 Where does your friend Robert live?
5. I noticed a huge number of snails in my garden. When
	 When did you notice a huge number of snails in your garden?
6. I collected several dozen and put them in a paper bag. How many ... and where
	 How many snails did you collect and where did you put them?
7. Robert was delighted to see me. Why
	 Why was Robert delighted to see you?
8. Robert and I spent a couple of hours talking in the living room. How long
	 How long did Robert and you spend talking in the living room?
9. I followed Robert reluctantly out of the room. Why
	 Why did you follow Robert reluctantly out of the room?
10. The snails had escaped from the paper bag. Where ... from
		Where had the snails escaped?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-01 Fri 20:36]
I took the snails to Robert.
I left the bag in the hall and Robert
	and I had been talking in the living room for a couple of hours.
After Robert asked me to stay to dinner,
	we went out of the room finding the snails taking possession of the hall.
Since then, I have never been able to look at a snail.

The writer collected several dozen snails,
	put them in a paper bag and took them to Robert
		who was delighted to see him, and pleased with the snails.
The writer left the bag in the hall
	and he and Robert went into the living room and talked for a couple of hours.
He had forgotten the snails until Robert invited him to dinner,
	and he followed Robert into the hall to find snails everywhere.
They had escaped from the bag.

** DONE tell the story 口语复述
CLOSED: [2023-12-01 Fri 20:39]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-01 Fri 20:43]
The snails had escaped from the paper bag and they were everywhere
	----on the walls, on the ceiling, on the carpet, and even on the large hall mirror.
When we began to look carefully, we found that they were even in coat pockets in the clothes
	hanging on the clothes hooks in the hall.
It was disgusting!
Snails move slowly but it's amazing how far they can travel in a couple of hours!
It took Robert and me ages to collect them.
He fetched a pair of steps for me and ladders for himself and we collected them in two buckets.

There were snail marks everywhere, too, and it took hours to clear up the mess
	----remember, there were several dozen of them.
Snails may not be fast, but we had been talking for a couple of hours,
	and they can travel.
Even now I am sure we didn't find them all: some are still crawling round Robert's house.
The ones that we did not find were lucky!
Robert was amused, but I wasn't.
He decided to cook the snails and invited me to stay.
I said before that I didn't fancy the idea, so I left him to his meal for one.
I just couldn't look at the snails and have never been able to face them since then.

** Topics for discussion
