#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 24 A skeleton in the cupboard
#+begin_verse
Who was Sebastian?

We often read in novels
	how a seemingly respectable person or family has some terrible secret
		which has *been concealed from* strangers for years.
The English language possesses a vivid saying to describe this sort of situation.
The terrible secret is called 'a skeleton in the cupboard'.
At some dramatic moment in the story, the terrible secret becomes known and a reputation is ruined.
The reader's *hair stands on end*
	when he reads in the final pages of the novel
		that the heroine, a dear old lady who had always been so kind to everybody,
			had, *in her youth*, poisoned every one of her five husbands.

*It is all very well* for such things to occur in fiction.
*To varying degrees*, we all have secrets
		which we do not want even our closest friends to learn,
	but few of us have skeletons in the cupboard.
The only person I know who has a skeleton in the cupboard is George Carlton,
	and he is very pround of the fact.
George studied medicine in his youth.
Instead of becoming a doctor, however, he became a successful writer of detective stories.
I once spent an uncomfortable weekend which I shall never forget at his house.
George *showed me to* the guestroom which, he said, was rarely used.
He told me to unpack my things and then come down to dinner.
After I had stacked my shirts and underclothes *in two empty drawers*,
	I decided to hang one of the two suits I had *brought with me* in the cupboard.
I opened the cupboard door and then stood in front of it petrified.
A skeleton was dangling before my eyes.
The sudden movement of the door made it sway slightly
	and *it gave me the impression that* it *was about to leap out at* me.
Dropping my suit, I dashed downstairs to tell George.
This was worse than 'a terrible secret'; this was a real skeleton!
But George was unsympathetic,
	'Oh, that,'	he said with a smile as if he were talking about an old friend.
'That's Sebastian. You forget that I was a *medical student once upon a time*.'
#+end_verse

** words
skeleton [ˈskelɪt(ə)n] n. 骷髅
seemingly [ˈsiːmɪŋli] adv. 表面上
respectable [rɪˈspektəbl] adj. 体面
conceal [kənˈsiːl] v. 隐藏
vivid [ˈvɪvɪd] adj. 生动的
dramatic [drəˈmætɪk] adj. 令人激动的,扣人心弦的
ruin [ˈruːɪn] v. 毁坏
heroine [ˈheroʊɪn] n. 女主人公
fiction [ˈfɪkʃ(ə)n] n. 小说
varying [ˈveriɪŋ; ˈværiɪŋ] adj. 不同的
medicine [ˈmedɪs(ə)n] n. 医学
guestroom [ˈɡestrʊm; ˈɡestruːm] n. (家中)客房
unpack [ˌʌnˈpæk] vt. 取出
stack [stæk] v. (整体地)堆放,排放
underclothes [ˈʌndərkloʊðz] n. 内衣
drawer [drɔːr] n. 抽屉
petrify [ˈpetrɪfaɪ] v. 使惊呆
dangle [ˈdæŋɡ(ə)l] v. 悬挂
sway [sweɪ] v. 摇摆
unsympathetic [ˌʌnˌsɪmpəˈθetɪk] adj. 不表同情的
medical [ˈmedɪk(ə)l] adj. 医学的

** vocabulary
seemingly: apparently
concealed: hidden
vivid saying: a memorable expression
reputation: a good name
ruined: destroyed
fiction: invented stories
to varying degrees: sometimes more, sometimes less

** DONE 单词造句
CLOSED: [2023-12-03 Sun 11:25]
skeleton n.  a skeleton in the cupboard/closet
1. We needn't have had a skeleton in the cupboard.
2. He was said to have a skeleton in the cupboard.
3. The girl who played truent from school has a skeleton in the cupboard.
4. The richest family in our town has a skeleton in the cupboard.
5. It is clear that this family has a skeleton in the cupboard.
seemingly adv. apparently
1. You just seemingly found me playing video games.
2. I was relieved to hear that she began to deal with the seemingly impossible task.
3. Seemingly, it convinced him that he believes in these mystery stroies.
4. Seemingly, I have a circle of friends.
5. Seemingly, I spot a cat pressing the button.
respectable adj.
1. This convinced me that the headmaster is a respectable teacher.
2. It is disturbing to think that you have yelled at a respectable doctor in public.
3. Some respectable experts began to take it seriously.
4. The respectable doctor confirmed that you have a cancel.
5. The respectable man claimed to have prevented people from war.
conceal v.  sth. be concealed from sb. = conceal sth. from sb.
1. I felt obliged to conceal my diseater from my family.
2. It is disturbing to think that your child is still concealing pockety money from you.
3. I have found a gangster concealing the bag from us.
4. Dana managed to conceal her pregancy from her family.
5. As time go on, I couldn't conceal your pregancy from my family any more.
vivid adj. vividly adv.
1. I always have a vivid dream that I am studying in high school.
2. I've got vivid memories of the girl who worked for the corporation.
3. She didn't get enough money to fulfill her vivid dream.
4. I had a vivid dream that I was equal to go to university.
5. After having had a vivid dream, I woke up with a start last night.
dramatic adj. drama n. dramatically adv.  drama queen
1. Her life changes dramatically when she was pregnant.
2. She always acts on such a sudden impulse that she is a dramatic queen.
3. What a dramatic queen.
4. It happened dramatically that all the sweets were sold out.
5. She has dramatically got enough money to move to Beijing.
ruin v. ruin my day
1. I was just wondering that the argument has almost ruined my day.
2. I am always ruining my day on weekends for one cause or another.
3. What's going on? I wished it hadn't ruined my day.
4. You just recognized me as a stranger. It hurts me and ruins my day.
5. You did give me a surprise which ruins my day.
heroine n. hero 
1. I'm glad that the heroine is still alive at the end of the story.
2. The heroine soon gets used to life at the monastery.
3. The heroine claimed that the room was used as a place of worship.
4. The heroine has disappeared on the promontory.
5. The heroine will have built the drainage system by the last day of this year.
fiction n.  science fiction
1. I'm gonna have a rest with a science fiction.
2. You'd better return the science fiction to me or I will go to the police.
3. The science fiction dating from 17th century turns out to be very interesting.
4. The film is said to be based on a science fiction.
5. She happened to read a science fiction these days.
varying adj.  to varying degrees
1. To varying degrees, we visited these sacred room.
2. To varying degrees, we both have identity cards of our own.
3. To varying degrees, we makes a discovery of ancient philosophies.
4. To varying degrees, we were equipped with weapons during the war.
5. To varying degrees, we do manual work for a long time.
medicine n.
1. The worker who do manual work has the impulse to study medicine.
2. I used to study medicine when I was in the university.
3. Equipped with new machine, they proceeded to study medicine.
4. Despite the fact that he had been studying medicine in the university.
5. I am amazed to find that my girlfriend gets accustomed to studying medicine.
guest room
1. You should have showed your relative to the guest room.
2. Let's me show you to the guest room.
3. Would I have the privilege of living in the guest room, mummy?
4. I was asked to keep a secret in this guest room.
5. Keep the status quo, live in the guest room.
unpack v.
1. After having unpacked several dozens of suitcases, I took a shower.
2. The worker unpacked far more boxes than you.
3. It was you who unpacked her suitcase, not me.
4. She was too embarrassed to unpack her suitcase.
5. I am not willing to unpack my suitcase.
stack v.
1. After having stacked my shirts and underclothes in two empty drawers, I received a warm welcome.
2. After I had stacked my shirts and underclothes, I was called in to do housework.
3. After I had stacked my shirts and underclothes, I attempted to study medicine.
4. After I had stacked my shirts and underclothes, the alarm to leave the house was given.
5. After she had stacked her shirts and underclothes, she died from a slip.
underclothes n. = underwear
1. They have onething in common: they don't wear underwear.
2. I'll change into the underwear you buy me as soon as possible.
3. She found him repulsive, for he hasn't changed his underwear for a week.
4. There is no shortage of underwears.
5. The boy learned to change underclothes by his own. 
drawer n.  in the drawer/ from the drawer
1. Let's put the letter in the drawer and keep a secret.
2. It seems that there is a button in the drawer.
3. There is no shortage of socks in the drawer.
4. The underwears in the drawer are yours, you can touch them.
5. She is likely to hide the snack in the drawer.
petrify v.  be petrified of sth.
1. She was so petrified of the Japanese horror movie that she had nightmares for a long time.
2. When my teacher shouted at me, I was petrified of fear.
3. I was petrified of fear, for I didn't get enough money to pay the bill.
4. I was petrified of fear, as the order to abandon ship was given.
5. I was petrified of fear when I was greeted by an unpleasant smell from the kitchen.
dangle v.
1. The long thin wire attacted to metal spheres was dangling in the centre of the hall.
2. I realized to my horror that a big spider was dangling in the guest room.
3. These days, I was tolerant of the big spider dangling in my guest room.
4. I was made to clean up the spider dangling in my room.
5. After I lit up, I found a spider dangling in the center of the hall.
sway v.
1. I got the vivid memories of the trees swaying in the wind in the my school.
2. I wished that the boat hadn't swayed from side to side out at sea.
3. For instance, I saw the spider swaying in the guest room.
4. He lost his concentration and kept seeing the tree swaying in the wind.
5. I am sure that it is swaying slightly.
unsympathetic adj.
1. I found you unsympathetic.
2. A man who is unsympathetic is not welcomed here. 
3. I don't mean to be unsympathetic, but it's very funny.
4. I don't mean to be unsympathetic, but everything should return to normal.
5. I don't mean to be unsympathetic, but we should make it official.
medical adj.  medical student/school
1. At last, the medical student lost his temper.
2. Do you hear about the medical student who is doing manual work now?
3. Do you hear about the medical student who takes charge of the school?
4. Do you hear about the medical student who used to play truent from school?
5. Do you hear about the medical student who concealed her pregancy from her family?

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-04 Mon 19:59]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-03 Sun 11:46]
It is all very well (and good)..., but not in reality
1. It is all very well that they are curious to find out the fact.
2. It is all very well that they go to the college.
3. It is all very well that the company makes a profit of all time.
4. It is all very well for you to look down on money.
5. It is all very well for you to have the impulse to study medicine.
make one's hair stand on end
1. The horror movie has made my hair stand on end.
2. The company hasn't made a profit yet. This made my hair stand on end.
3. The stoy which made my hair stand on end is based on a really event.
4. This is a special type of smell which really makes your hair stand on end.
5. This horror stoy is likely to make our hair stand on end.
in sb's youth
1. She was said to poison her husband in her youth.
2. She used to set houses on fire in her youth.
3. She made a study of ancient philosophy in her youth.
4. She has had a tremendous impact on people in America in her youth.
5. His father died from a cancer in her youth.
show sb. to sw.
1. Why don't we show you friend to the guest room?
2. Oddly enough, she didn't show me to the guest room.
3. Seemingly, she is showing me to the guest room.
4. It was your father who showed me to the guest room, not you.
5. He was impatient to show me to the guest room.
bring sth. with sb.
1. He always brings a torchlight with him for one reason or another.
2. As he put it, he brought his men with him near Florence.
3. He was impatient to bring a bottle of wine with him.
4. He brought a torchlight with him when he wandered around the street.
5. It was estimated that the commander has brought 1000 men with him.
it give sb. the impression that + ...
1. It gave me the impression that we were close friend.
2. It gave him the impression that she wanted to have sex with him.
3. It gave me the impression that she led a normally life.
4. It gave me the impression that the boat was loaed with goods.
5. It gave me the impression that you were yelling at me.
be about to do sth.
1. I am about to make myself comfortable. 
2. I am about to load the boat with foods.
3. I am about to pay money to the landlord.
4. I am about to fight against him.
5. I am about to reward the cat with a can.
leap out at sb.
1. Acting on a sudden impulse, he leaped out at her.
2. She claimed that he leaped out at her first.
3. Do you hear about the medical student who leaped out at a lady in public?
4. The puma was about to leap out at me.
5. My dog always leaps out at me when I arrive home.
once upon a time
1. Once upon a time, a girl who owns $10 wanted to exchange it for sweets.
2. Once upon a time, a lady was rubbing a boy's arm with soap and butter.
3. Once upon a time, there was an aunt who always gave her nephew fifty pence.
4. Once upon a time, there was a special type of perfume.
5. Once upon a time, there was a businessman who had the opportunity to meet the queen.

** 跟读 50遍
** Comprehension 反复练习
** DONE Ask me if 写+读
CLOSED: [2023-12-04 Mon 20:05]
1. A terrible secret is sometimes called 'a skeleton in the cupboard'. What
	 What is a terrible secret sometimes called?
2. The reader's hair stands on end when he reads the final pages of the novel. When
	 When does the reader's hair stand on end?
3. The dear old lady had poisoned every one of her five husbands. How many
	 How many husbands had the dear old lady poisoned?
4. We all have secrets that we don't want our closest friends to learn. What secrets
	 What kind of secrets do we all have?
5. George is proud of the fact that he has skeleton in the cupboard. Why
	 Why is George proud of the fact that he has skeleton in the cupboard?
6. George became a writer of detective stories. What
	 What did George become?
7. The guest room was used a lot. How often
	 How often was the guest room used?
8. A skeleton was dangling in the cupboard. What
	 What was dangling in the cupboard?
9. The movement of the door made it sway slightly. What
	 What made it sway slightly?
10. The writer dropped his suit. Who
		Who dropped his suit?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-04 Mon 20:15]
I was showed to the guest room which was rarely used.
After having stacked my shirts and underclothes in the drawers,
	I opened the cupboard door to hang my suit in the cupboard.
A skeleton was dangling before my eyes
	and it gave me the impression that it was about to leap out at me.
Dropping my suit, I rushed downstairs to tell George.
But George was unsympathetic and told me:
	'That's Sebastian. You forget that I was a medical student once upon a time'.

The writer started to unpack and put his shirts and underclothes into drawers
	and then decided to hang a suit in the cupboard.
He opened the cupboard and stood petrified: there, dangling in front of him, was a skeleton.
It was swaying and ready to leap out at him.
He dropped his suit and dashed downstairs to tell George.
Georage was unsympathetic and told the writer
	it was Sebastian, a skeleton he had when he was a medical student.

** DONE tell the story 口语复述
CLOSED: [2023-12-04 Mon 20:18]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-04 Mon 20:19]
Now that George had explained about the skeleton, I felt better,
	but I still didn't want to sleep in the room with a skeleton hanging in the cupboard.
I asked George to remove him, but he refused.
'There's nowhere else to put him,' said George, 'so he'll have to stay.'
I couldn't disagree of course,
	but the moment I lay down to sleep, I knew it was going to be an uncomfortable night.
In the end, I decided that I would take Sebastian somewhere for the night
	and bring him back up to my room early in the morning.
So I took him out of cupboard and walked around the house with him
	trying to find somewhere to put him.

George's maid was just going to bed as I walked along the landing.
She saw Sebastian apparently walking around, screamed and fainted.
She had obviously woken Carlton who appeared from his bedroom and,
	when the girl had regained consciousness, explained everything to her.
He accused me of being stupid and sent me and Sebastian back to our's room
	where I hung him up in the cupboard again.
Imagine my surprise when I picked up one of Carlton's detective stories two years later.
There I was, with Sebastianthe skeleton,
	as the main characters in one of his stories for the whole world to read.
Still, he didn't use my real name,so I should be glad of that!

** Topics for discussion
