#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L24 A skeleton in the cupboard
#+begin_verse
Who was Sebastian?

We often read in novels
	how a seemingly respectable person or family has some terrible secret
		which has been concealed from strangers for years.
The English language possesses a vivid saying to describe this sort of situation.
The terrible secret is called 'a skeleton in the cupboard'.
At some dramatic moment in the story, the terrible secret becomes known and a reputation is ruined.
The reader's hair stands on end
	when he reads in the final pages of the novel
		that the heroine, a dear old lady who had always been so kind to everybody,
			had, in her youth,
				poisoned every one of her five husbands.

It is all very well for such things to occur in fiction.
To varying degrees, we all have secrets
		which we do not want even our cloest friends to learn,
	but few of us have skeletons in the cupboard.
The only person I know who has a skeleton in the cupboard is George Carlton,
	and he is very pround of the fact.
George studied medicine in his youth.
Instead of becoming a doctor, however, he became of a s successful writer of detective stories.
I once spent an uncomfortable weekend which I shall never forget at his house.
George showed me to the guestroom which, he said, was rarely used.
He told me to unpack my things and then come down to dinner.
After I had stacked my shirts and underclothes in two empty drawers,
	I decide to hang one of the two suits I had brought with me in the cupboard.
I opened the cupboard door and then stood in front of it petrified.
A skeleto was dangling before my eyes.
The sudden movement of the door made it sway slightly
	and it gave me the impression that it was about to leap out at me.
Dropping my suit, I dashed downstairs to tell George.
This was worse than 'a terrible secret'; this was a real skeleton!
But George was unsympathetic,
	'Oh, that,'	he said with a smile as if he were talking about an old friend.
	'That's Sebastian. You forget that I was a medical student once upon a time.'
#+end_verse

** words
skeleton [ˈskelɪt(ə)n] n. 骷髅
seemingly [ˈsiːmɪŋli] adv. 表面上
respectable [rɪˈspektəbl] adj. 体面
conceal [kənˈsiːl] v. 隐藏
vivid [ˈvɪvɪd] adj. 生动的
dramatic [drəˈmætɪk] adj. 令人激动的,扣人心弦的
ruin [ˈruːɪn] v. 毁坏
heroine [ˈheroʊɪn] n. 女主人公
fiction [ˈfɪkʃ(ə)n] n. 小说
varying [ˈveriɪŋ; ˈværiɪŋ] adj. 不同的
medicine [ˈmedɪs(ə)n] n. 医学
guestroom [ˈɡestrʊm; ˈɡestruːm] n. (家中)客房
unpack [ˌʌnˈpæk] vt. 取出
stack [stæk] v. (整体地)堆放,排放
underclothes [ˈʌndərkloʊðz] n. 内衣
drawer [drɔːr] n. 抽屉
petrify [ˈpetrɪfaɪ] v. 使惊呆
dangle [ˈdæŋɡ(ə)l] v. 悬挂
sway [sweɪ] v. 摇摆
unsympathetic [ˌʌnˌsɪmpəˈθetɪk] adj. 不表同情的
medical [ˈmedɪk(ə)l] adj. 医学的
