#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L25 The Cutty Sark
#+begin_verse
What piece of bad luck prevented the Cutty Sark from winning the race?

One of the most famous sailing ships of the nineteenth century,
	the Cutty Sark, can be seen at Greenwich.
She stands on dry land and is visited by thousands of people each year.
She serves as an impressive reminder of the great ships of the past.
Before they were replaced by steamship,
	sailing vessels like the Cutty Sark were used to carry tea from China and wool from Australia.
The Cutty Sark was one of the fastest sailing ships that has ever been built.
The only other ship to match her was the Thermopylae.
Both these ships set out from Shanghai on June 18th, 1872 on an exciting race to England.
This race, which went on for exactly four months, was the last of its kind.
It marked the end of the great tradition of ships with sails and the beginning of a new era.

The first of the two ships to reach Java after the race had begun was the Thermopylae,
	but on the Indian Ocean, the Cutty Sark took the lead.
It seemed certain that she would be the first ship home,
	but during the race she had a lot of bad luck.
In August, she was struck by a very heavy storm during which her rudder was torn away.
The Cutty Sark rolled from side to side and it became impossible o steer her.
A temporary rudder was made on board from spare planks and it was fitted with great difficulty.
This greatly reduced the speed of the ship,
	for there was a danger that if she travelled too quickly,
	this rudder would be torn away as well.
Because of this the Cutty Sark lost her lead.
After crossing the Equatoer,
	the captain called in at a port to have a new rudder fitted,
	but by now the Thermopylae was over five hundred miles ahead.
Though the new rudder was fitted at tremendous speed, it was impossible for the Cutty Sark to win.
She arrived in England a week after the Thermopylae.
Even this was remarkable, considering that she had had so many delays.
There is no doubt that if she had not lost her rudder she would have won the race easily.
#+end_verse

** words
impressive [ɪmˈpresɪv] adj. 给人印象深刻的
steamship [ˈstiːmʃɪp] n. 蒸汽轮船
vessel [ˈves(ə)l] n. 轮船,大木船
era ˈɪrə n. 时期,时代
Java [ˈdʒɑːvə] n.爪哇
rudder [ˈrʌdər] n.舵
roll [roʊl] v.颠簸,摇摆
steer [stɪr] v.掌握方向
temporary [ˈtempəreri] adj.临时的
plank [plæŋk] n.大块木板
fit [fɪt] v.安装
equator [ɪˈkweɪtər] n.赤道
delay [dɪˈleɪ] n.耽误
