#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 26 Wanted: a large biscuit tin
#+begin_verse
Who won the prize for the biggest biscuit?

No one can *avoid being influenced by* advertisements.
Much as we may *pride ourselves on* our *good taste*,
		we *are no longer free to* choose the things we want,
	for advertising *exerts a subtle influence on* us.
*In their efforts to* persuade us to buy this or that product,
	advertisers have made a close study of human nature and have classified all our little weaknesses.

Advertisers discovered years ago that all of us love to *get something for nothing*.
An advertisement which begins with the *magic word* free can rarely go wrong.
These days, advertisers not only offer free samples,
	but free cars, free houses, and free trips round the world as well.
They devise hundreds of competitions which will *enable us to* win huge sums of money.
Radio and television have *made it possible for advertisers
	to capture the attention* of millions of people in this way.

During a radio programme,
	a company of biscuit manufacturers once asked listeners to bake biscuits
		and send them to their factory.
They offered to pay 10 dollars a pound for the biggest biscuit baked by a listener.
The response to this competition was tremendous.
Before long, biscuits of all shapes and sizes began arriving at the factory.
One lady brought in a biscuit on a wheelbarrow.
It weighed nearly 500 pounds.
A little later, a man *came along* with a biscuit which occupied *the whole boot of his car*.
All the biscuits that were sent were carefully weighed.
The largest was 713 pounds.
It seemed certain that this would win the prize.
But just before the competition closed,
	a lorry arrived at the factory with a truly colossal biscuit which weighed 2,400 pounds.
It had been baked by a college student
	who had used over 1,000 pounds of flour,
		800 pounds of sugar, 200 pounds of fat, and 400 pounds of various other ingredients.
It was so heavy that a crane had to be used to remove it from the lorry.
The manufacturers had to pay more money than they had anticipated,
	for they *bought the biscuit from the student* for 24,000 dollars.
#+end_verse

** words
influence [ˈɪnfluəns] v. 影响 
pride [praɪd] v. 骄傲
taste [teɪst] n. 鉴赏力
exert [ɪɡˈzɜːrt] v. 施加
subtle [ˈsʌt(ə)l] adj. 微妙的,难以捉摸的
advertiser [ˈædvərtaɪzər] n. 做广告的人
classify [ˈklæsɪfaɪ] v. 分类
magic [ˈmædʒɪk] adj. 有奇妙作用的
sample [ˈsæmp(ə)l] n. 样品
devise [dɪˈvaɪz] v. 设计,想出
capture [ˈkæptʃər] v. 吸引,赢得
manufacturer [ˌmænjuˈfæktʃərər] n. 生产厂家,制造商
wheelbarrow [ˈwiːlbæroʊ] n. 独轮手推车
boot [buːt] n. 行李箱
ingredient [ɪnˈɡriːdiənt] n. 配料
crane [kreɪn] n. 起重机
anticipate [ænˈtɪsɪpeɪt] v. 预期,预料

** vocabulary
no longer: not any more, not now
in their efforts to persuade us: in their attempts to influence us to do something
classified: put into categories
free: without any cost or payment
enable: make it possible for
capture: attract and hold

** DONE 单词造句
CLOSED: [2023-12-08 Fri 22:49]
influence v.n.
	bad/good/positive etc. influence (on sb.)  have an influence on sb./sth.  be influenced by ...
1. I turned out to be a bad influence on my son.
2. I'm genuinely sorry that your son were influenced by me.
3. His works claimed to have had an influence on many modern teachers.
4. There is no doubt that children are heavily influenced by advertising.
5. There is a danger that it will have a bad influence on young people in the country.
pride v. pride oneself on (doing) sth. = be pround of
1. I prided myself on the tremendous speed of my sailing vessel.
2. I prided myself on that, for he is the captail of a sailing ship.
3. I prided myself on taking the lead in my class.
4. I prided myself on breaking the world record.
5. I prided myself on fitting it with great difficulty.
taste n.v.  have good/bad taste in sth.
1. My wife is always complaining that I have bad taste in clothes.
2. Struck by a fashion exhibition, she began to have good taste in clothes.
3. She had had bad taste in men once upon a time.
4. It gave me the impression that she had good taste in bed.
5. It made my hair stand on end, for my daughter has bad taste in men.
exert v.  exert a subtle/some influence on/over sb.
1. You should have obeyed traffic rules, for it would exert some influence on your children.
2. It really exert some influence on me and ruined my day.
3. What a drama queen. It's impossible not to exert some influence on her daughter.
4. The skeleton he has seen last week exerted a subtle influence on the medical student.
5. The life abroad did exert some influence on the girl who are not willing to obey the rules.
subtle adj.  have a subtle mind
1. It seems that the snake could not tell the subtle differences between them.
2. Much as they have thing in common, there are still many subtle differences between them.
3. Noticing the subtle differences between them, he was petrified of the consequent.
4. Listen to me carefully, if you don't have a subtle mind.
5. Don't break your concentration, even if you have a subtle mind.
advertiser n.
1. To our dismay, the advertiser is willing to serve it.
2. The advertiser got very angry and knocked him to the ground.
3. I have the impulse to buy a pen at the idea of the advertiser.
4. For instance, the advertiser used to be a medical student.
5. The advertiser provided us with dozens of free samples of the perfume.
classify v.  classify a. as/under b.
1. Oddly enough, they classifies snails as a delicacy.
2. Hand the suit to me, I am gonna classify it.
3. He was strucked by a car while crossing the street.
	 The police arrived on the scene and classified it as an accident.
4. If I don't classify it in time, my stomach will turn.
5. Imagine my dismay when I found that she classified the meat as poison.
magic adj.  say the magic word
1. We all know what is magic word in business.
2. If I say magic word, my wife will take a shower.
3. These magic word which exert some influence on people never appeals to me.
4. These magic word received far more abuse than other.
5. It is illogical to say the magic word on that occassion.
sample n.  free samples of sth.
1. The old lady is anxious to eat free samples of ice cream.
2. Much to my surprise, this bottle is only free samples of the perfume.
3. It was not until a month later that she was giving out a lot of free samples of products.
4. As she received a lot of free samples of perfume, she never bought one.
5. Because of free samples of cakes, I am not hungry now.
divise v.  devise a way/plan to
1. These medical students devised a way to drink on the duty.
2. We should have devise a plan to prevent this from happening.
3. We devised a plan to make them turn against each other.
4. We devised a plan to go on a strike.
5. We devised a way to reach an agreement.
capture v.  capture the attention of sb. = capture sb's attention
1. Because of fantasy custom, she really captured the attention of people in the exhibition.
2. It is clear that the pretty girl captures their attention.
3. The police is trying to capture their attention and settle the argument.
4. In fact, you didn't capture my attention in the museum.
5. The man bet $2000 on Mendoza and capture the attention of other people.
manufacturer n.
1. Obviously if the manufacturer reduces his price, he'll not make a profit.
2. The manufacturer claimed to have made a profit last year.
3. I bet the manufacturer will not reduce his price by the last day of the year.
4. Technically speaking, the manufacturer has already made a profit.
5. The manufacturer rose to fame swiftly because of the advertisement.
wheelbarrow n.
1. I'm gonna bring a wheelbarrow to you.
2. Despite the fact that he got a new wheelbarrow for his father, he still received much abuse.
3. Despite the fact that he got a new wheelbarrow for his father,
		his father was tired of gardening.
4. Despite the fact that he got a new wheelbarrow for his father,
		they didn't finish the task on time.
5. Despite the fact that he got a new wheelbarrow for his father,
		his father still carries things with bare hands.
boot n.  in the boot of sb's car
1. Between you and me, there is a body in the boot of my car.
2. Leo complained that the cat was in the boot of his car.
3. I explained why the cat was in the boot of my car.
4. There used to be a hammer in the boot of my car.
5. Following your instructions, I put the money in the boot of my car.
ingredient n.
1. To our surprise, this kind of ingredient is regarded as unacceptable.
2. It looked as if it would taste better with the secret ingredient.
3. She made an attempt to cook without the ingredient.
4. She made every effort not to cook with the ingredient.
5. Considering the secret ingredient, she refused to eat it.
crane n.
1. I was astounded when I was told that the crane is over $5000.
2. Please drive these cranes in an orderly fashion.
3. It astounded me that you got the crane for nothing.
4. The crane is designed to move these boxes.
5. The idea that crane is easy to drive may be mistaken.
anticipate v.  It is anticipated that + ...  sb. anticipate that + ...
1. It is anticipated that she will remain anonymous.
2. It is anticipated that he will pay the bill. 
3. It is anticipated that the archaeologist will make a close study of it.
4. She anticipated that this basket is designed to carry fruits.
5. I anticipated that my father takes no interest in the crane toy.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 自己讲解语法
CLOSED: [2023-12-09 Sat 20:07]
as引导的倒装句 表 让步
	- Much as ..., ...
	- adj./n./v. + as ...,句子: adj-est.去the, n.去冠, v.用原型
	- 为什么要试试自己查语法书
** DONE 习惯用法造句
CLOSED: [2023-12-09 Sat 18:57]
avoid being done
1. She managed to avoid being spyed on.
2. Even though he tired to avoid being seen with me, we happened to meet his parents.
3. Even though he tired to avoid being seen with me, we happened to be stuck by an accident.
4. She managed to avoid being followed around.
5. I was able to avoid being ordered to do housework.
be free to do sth.
1. You are free to play jokes on me.
2. I am free to play the role of the show.
3. You are free to settle the argument.
4. I am not free to turn against him.
5. You are free to bring these fruits to your wife.
in sb's effort to do sth.
1. In his effort to follow in his father's footsteps, he runs a successful furniture business. 
2. In his effort to persuade me to buy it, I paid the bill.
3. In his effort to ask me for cardboard boxes, I gave him some.
4. In his effort to follow me around, we went shopping together.
5. In his effort to keep his word, he won a prize of $1000.
get sth. for nothing
1. Such is human nature that we all want to get something for nothing.
2. How do we get it for nothing?
3. It looked as if you could get the toys for nothing.
4. He explained that we can get the toys for nothing.
5. Follow my instructions, you will get a great many of sheets of paper for nothing.
enable sb. to do sth.
1. This operation may enable you to go for a walk.
2. Even though she has borrowed money from me, this wouldn't enable her to buy the house.
3. This will enable us to afford the car.
4. Following my instructions will enable him to keep his word.
5. This can't enable the microphone to be connected to the tower. 
a. has made it possible for sb. to do sth.
1. Your parents made it possible for you to go to university.
2. Our teacher makes it possible for us to make a sculpture.
3. Leo makes it possible for me to study abroad.
4. This has made it possible for me to give you electric shocks.
5. This made it possible for her to live in a desert island.
come along
1. You should have come along in a car and gave us a lift.
2. A man who was waving to us came along on road.
3. An old lady come along with her cat.
4. It is said that cats come along here.
5. He always comes along in his smart suit. 
buy sth. from sb.
1. I won so much prize money that I bought a purse from him.
2. I apologized to my friend for not buying computer from him.
3. I have dyed the book red which I bought from Leo.
4. I was astonished to find that you bought goods from the internet.
5. Even though China is at war with India, China authorities still buy goods from India.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-09 Sat 20:08]
** DONE Ask me if 写+读
CLOSED: [2023-12-09 Sat 20:29]
1. Anyone can avoid being influenced by advertisements. Why can't
	 Why can't anyone avoid being influenced by advertisements?
2. Some of us pride ourselves on our good taste. How many of us
	 How many of us pride ourselves on our good taste?
3. Advertisers have made a close study of human nature. Who
	 Who have made a close study of human nature?
4. Advertisers offer free samples, free cars and free houses. What
	 What do advertisers offer?
5. A biscuit company asked listeners to bake biscuits and send them in. What
	 What did a biscuit company ask listeners to do?
6. They offered to pay $10 a pound for the biggest biscuit. How much
	 How much did they offer to pay for the biggest biscuit?
7. One lady brought in a biscuit on a wheelbarrow. How
	 How did one lady bring in a biscuit?
8. The biggest biscuit weighed 2,400 pounds. How much
	 How much did the biggest biscuit weigh?
9. It had been baked by a college student. Who
	 Who had it been baked by?
10. The manufacturers had to pay the student $24,000. How much
		How much did the manufacturers have to pay the student?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-09 Sat 20:40]
A manufacturers asked listeners to bake biscuit
	and offered to pay $10 a pound for the biggest biscuit.
Biscuits of all shapes and sizes arrived at the factory.
One lady brought in a biscuit on a wheel barrow,
	which weighed nearly 500 pounds.
A man came along with a biscuit which occupied the whole boot of his car.
The largest of biscuits that were sent was 713 pounds.
Just before the competition closed,
	a lorry arrived	with a colossal biscuit which weighed 2,400 pounds.
The manufacturers had to pay $24,000 to the student who baked it.

A biscuit company asked its customers to bake biscuits and send them to the factory.
As a prize, they offered $10 a pound for the biggest biscuit they received.
The response was tremendous, with one biscuit weighing 500 pounds and another weighing 713 pounds.
They though that was the winner
	until a lorry delivered one which weighed 2,400 pounds baked by a college student.
A crane lifted it from the lorry and the manufacturers paid the student $24,000.

** DONE tell the story 口语复述
CLOSED: [2023-12-09 Sat 20:43]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-09 Sat 20:50]
The other evening I listened to a quiz show on the radio
	which was organised by a firm of soap manufacturers.
A member of the audience was invited to answer ten questions to win money.
He could take a money prize after each correct answer or go on to a more difficult question.
Each new question was worth twice the last question.
The man was very nervous in front of the audience, but he got the first question right.
Then he slowly answered all the questions correctly
	-- spelling questions, history questions,general knowledge, mathematics, ...
The audience was getting very excited as the question master got to question number 9.
'And your ninth question,' he said, 'is worth $1,024. Here it is.'

'Which nineteenth-century sailing ship won a race from Shanghai to England?'
'It was the Thermopylae,' the man said confidently. 'She beat the CuttySark.'
'Correct,' said the question master, and the audience went mad.
The question master had to ask them to be quiet.
'And here is your tenth and last question,' the host said, 'which is worth $2,048 exactly.'
'"Advertisement": how do you spell it?'
The man paused and then said: 'I think this is a trick question.
I can spell "advertisement", but I can also spell "it".
The answer is "I-T".'
'You're absolutely right,' the host said, 'and you have won $2,048! Congratulations!'

** Topics for discussion
