#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L27 Nothing to sell and nothing to buy
#+begin_verse
What is the most important thing for a tramp?

It has been said that everyone lives by selling something.
In the light of this statement, teachers live by selling knowledge,
	philosophers by selling wisdom and priests by selling spiritual comfort.
Though it may be possible to measure that value of material goods in terms of money,
	it is extremely difficult to estimate the true value of the services which people perform for us.
There are times when we would willingly give everything we possess to save our lives,
	yet we might grudge paying a surgeon a high fee for offering us precisely this service.
The conditions of society are such
	that skills have to be paid for in the same way that goods are paid for at a shop.
Everyone has something to sell.

Tramps seem to be the the only exception to this general rule.
Beggars almost sell themselves as human beings to arouse the pity of passers-by.
But real tramps are not beggars.
They have nothing to sell and require nothing from others.
In seeking independence, they do not sacrifice their human dignity.
A tramp may ask you for money, but he will never ask you to fell sorry for him.
He has deliberately chosen to lead the life he leads and is fully aware of the consequences.
He may never be sure where the next meal is coming from,
	but he is free from the thousands of anxieties with afflict other people.
His few material possessions make it possible for him to move from place to place with ease.
By having to sleep in the open,
	he gets far closer to the world of nature than most of us ever do.
He may hunt, beg, or steal occasionally to keep himself alive;
	he may even, in times of real need, do a little work;
	but he will never sacrifice his freedom.
We often speak of tramps with contempt and put them in the same class as beggars,
	but how many of us can honestly say that
		we have not felt a little envious of their simple way of life and their freedom from care?
#+end_verse

** words
philosopher [fəˈlɑːsəfər] n. 哲学家
wisdom [ˈwɪzdəm] n. 智慧
priest [priːst] n. 牧师
spiritual [ˈspɪrɪtʃuəl] adj. 精神上的
grudge [ɡrʌdʒ] v. 不愿给,舍不得给
surgeon [ˈsɜːrdʒən] n. 外科大夫
passer-by [ˌpæsər ˈbaɪ] n. 过路人
dignity [ˈdɪɡnəti] n. 尊严
deliberately [dɪˈlɪbərətli] adv. 故意地
consequence [ˈkɑːnsɪkwens] n. 后果
afflict [əˈflɪkt] v. 使苦恼,折磨
ease [iːz] n. 容易;舒适
nature [ˈneɪtʃər] n. 大自然
contempt [kənˈtempt] n. 蔑视
envious [ˈenviəs] adj. 羡慕的;嫉妒的
