#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L28 Five pounds too dear
#+begin_verse
Why was even five pounds 'too dear'?

Small boats loaded with wares sped to the great liner as she was entering the harbour.
Before she had anchored,
	the men from the boats had climbed on board
	and the decks were soon covered with colourful rugs from Persia,
		silks from India, copper coffee pots, and beautiful handmade silverware.
It was difficult not to be tempted.
Many of the tourists on board had begun bargaining with the tradesmen,
	but I decided not to buy anything until I had disembarked.

I had no sooner got off the ship
	than I was assailed by a man who wanted to sell me a diamond ring.
I had no intention of buying one,
	but I could not conceal the fact that I was impressed by the size of the diamonds.
Some of them were as big as marbles.
The man went to great lengths to prove that the diamonds were real.
As we were walking past a shop,
	he held a diamond firmly against the window and made a deep impression in the glass.
It took me over half an hour to get rid of him.

The next man to approach me was selling expensive pens and watches.
I examined one of the pens closely.
It certainly looked genuine.
At the base of the gold cap, the words 'made in the USA' had been neatly inscribed.
The man said that the pen was worth 50 dollars,
	but as a special favour, he would let me have it for 30 dollars.
I shook my head and held up five fingers indicating that I was willing to pay 5 dollars.
Gesticulating wildly, the man acted as if found my offer outrageous,
	but he eventually reduced the price to $10.
Shrugging my shoulders,
	I began to walk away when, a moment later, he ran after me and thrust the pen into my hands.
Though he kept throwing up his arms in despair, he readily accepted the 5 dollars I gave him.
I felt especially pleased with my wonderful bargain -- until I got back to the ship.
No matter how hard I tried,
	it was impossible to fill this beautiful pen with ink
	and to this day it has never written a single word!
#+end_verse

** words
wares [werz] n. 货物,商品
anchor [ˈæŋkər] v. 停航下锚
deck [dek] n. 甲板
silverware [ˈsɪlvərwer] n. 银器
tempt [tempt] v. 吸引;引诱
bargain [ˈbɑːrɡən] v. 讨价还价
disembark [ˌdɪsɪmˈbɑːrk] v. 下船上岸
assail [əˈseɪl] v. 纠缠
marble [ˈmɑːrb(ə)l] n. 小玻璃球
inscribe [ɪnˈskraɪb] v. 刻写,雕
favour [ˈfeɪvər] n. 好处,优惠
gesticulate [dʒeˈstɪkjuleɪt] v. (讲话时)打手势
outrageous [aʊtˈreɪdʒəs] adj. 出人意料的; 令人不悦的
thrust [θrʌst] v. 硬塞给

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
