#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 29 Funny or not?
#+begin_verse
What is the basis of 'sick' humour?

Whether we find a joke funny or not largely depends on where we have been brought up.
The sense of humour *is mysteriously bound up with* national characteristics.
A Frenchman, for instance, might *find it hard to laugh* at a Russian joke.
In the same way, a Russian might fail to see anything amusing in a joke
	which would make an Englishman *laugh to tears*.

Most funny stories are based on comic situations.
In spite of national differences, certain funny situations *have a universal appeal*.
No matter where you live, you would find it difficult not to laugh at,
	say, Charlie Chaplin's early films.
However, a new type of humour, which *stems largely from* the US, has recently *come into fashion*.
It is called 'sick humour'.
Comedians *base their jokes on* tragic situations like violent death or serious accidents.
Many people find this sort of joke distasteful.
The following example of 'sick humour' will enable you to *judge for yourself*.

A man who had broken his right leg was taken to hospital a few weeks before Christmas.
From the moment he arrived there,
	he kept on *pestering his doctor to tell* him when he would be able to go home.
He *dreaded having* to spend Christmas in hospital.
Though the doctor *did his best*, the patient's recovery was slow.
On Christmas Day, the man still had his right leg in plaster.
He spent a miserable day in bed thinking of all the fun he was missing.
The following day, however, the doctor consoled him by telling him
	that his chances of being able to leave hospital in time for New Year celebrations were good.
The man *took heart* and, sure enough, on New Year's Eve he was able to hobble along to a party.
To *compensate for* his unpleasant experiences in hospital,
	the man drank a little more than *was good for him*.
*In the process*, he enjoyed himself thoroughly
	and kept telling everybody how much he hated hospitals.
He was still mumbling something about hospitals at the end of the party
	when he slipped on a piece of ice and broke his left leg.
#+end_verse

** words
largely [ˈlɑːrdʒli] adv. 在很大程度上
comic [ˈkɑːmɪk] adj. 喜剧的,可笑的
universal [ˌjuːnɪˈvɜːrs(ə)l] adj. 普遍的
comedian [kəˈmiːdiən] n. 滑稽演员,喜剧演员
distasteful [dɪsˈteɪstf(ə)l] adj. 讨厌的
pester [ˈpestər] v. 一再要求,纠缠
dread [dred] v. 惧怕
recovery [rɪˈkʌvəri] n. 康复
plaster [ˈplæstər] n. 熟石膏
console [kənˈsoʊl] v. 安慰,慰问
hobble [ˈhɑːb(ə)l] v. 瘸着退走
compensate [ˈkɑːmpenseɪt] v. 补偿
mumble [ˈmʌmb(ə)l] v. 喃喃自语

** DONE 单词造句
CLOSED: [2023-12-15 Fri 22:34]
largely adv.
1. It is him who are largely responsible for the team's success, not you.
2. We are largely likely to make a profit this year.
3. I largely work with people who work in office.
4. I largely read science fiction to my daughter before she sleeps.
5. This largely indicates that she has got back to the ship.
comic adj.n.漫画  comic book/movie/novel
1. I spoted him reading comic books in the class.
2. She claimed to have not read comic books in the class. 
3. Our parents always put the comic books in the same class as harmful.
4. It is outrageous that she is interested in comic novels.
5. My friend thrust his comic book into my hands.
universal adj.  have a universal appeal
1. The songs which he made in his youth have a universal appeal all over the world.
2. It is all very well that a delicacy has a universal appeal.
3. She claimed that snails have a universal appeal as a dish.
4. We devised a plan to make a movie that has a universal appeal.
5. Countless people have been influenced by a song which has a universal appeal.
comedian n.
1. Damn it. I have recognized the comedian as a normal person in the market.
2. The comedian which play the role of a teacher gave us a surprise.
3. The comedian was cast in the role of a kidnappered.
4. The comedian proceed to stay out of the limelight.
5. The comedian insisted that the paper should be written out in full.
distasteful adj.
1. I insisted that the woman who made such distasteful remarks apologize to us.
2. You have played a joke on your husband at the party. I found this distasteful.
3. Don't bring your custom to my mouth. I found it distasteful.
4. If you found it distasteful, you should tell me.
5. It was not until an hour after the police arrived on the scene
		that he stop making distasteful remark.
pester v.  pester sb. to do sth.
1. My wife has been pestering me to travel abroad. 
2. Because I pestered him to go to university, we eventually reached an agreement.
3. Don't pester me to buy this or that product, I am under a lot of pressure.
4. I am relieved to hear that he stop pestering his father to check the garage.
5. My cat have been pestering me to play ball with her.
dread v.  dread doing sth.  dread sb. doing sth.
1. In fact, I really dread traveling abroad.
2. I am under a lot of pressure and dread my boss ordering me to finish it.
3. Much as she loved to go on a jourey, she dreaded asking his father for money.
4. The thief caught sight of policemen in front of his house and dreaded getting back home.
5. She woke up with a start and dreaded peeing in the midnight.
recovery n.  make a complete/quick/speedy/slow recovery
1. After an operation, he soon made a complete recovery.
2. The fact that my cat made a slow recovery afflicted me a great deal.
3. If you had an operation, you would make a complete recovery.
4. He made a complete recovery, for he refused to follow his doctor's instructions.
5. I'm glad that you made a full recovery.
plaster n.
1. She wasn't able to play truent from school, for her leg was still in plaster.
2. As my foot was in plaster at that time, I have a perfect alibi.
3. Whether my leg is in plaster or not is something that has no influence on taking the test.
4. Whether my leg is in plaster or not doesn't prevent me from watching TV.
5. Whether my leg is in plaster or not doesn't prevent me from being your husband.
console v.  console sb./yourself that + ...
1. I consoled myself that Miumiu is very dear to me.
2. I consoled myself that I would get a good salary in the future.
3. She consoled me that our daughter has said magic word.
4. I consoled my wife that the girl just classified us as beggars. 
5. I consoled my wife that our son would soon take heart.
hobble v.
1. I was strucked by a ball and had to hobble home.
2. As the medicine exerts some influence on him, he had to hobble across the park.
3. A old lady hobbled to the store to get samples of perfume for nothing.
4. The cat who is hobbling arose the pity of mine.
5. It is anticipated that he would hobble home afther he was hurt in the game.
compensate v.  compensate (for sth.) = make up for
1. In the university, my breakfast used to be compensated by lunch.
2. The busmen were compensated for better salary and less work time.
3. My wife was compensated for a nice dress which she expected to buy for a long time.
4. The fans of the singer were made up for some tickets.
5. You will be made up for studying abroad.
mumble v.
1. He seems to be mumbling his lover's name in sleep.
2. A woman who was making a speech in the open was mumbling, you made a spectacle of herself.
3. If you mumbled at that time, you might make a spectacle of yourself.
4. She was mumbling her cat's name to herself.
5. In going to office, I always mumble names of my wife and my cat.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
be bound up with
1. 
2. 
3. 
4. 
5. 
find it hard to do sth.
1. 
2. 
3. 
4. 
5. 
make sb. laugh to tears
1. 
2. 
3. 
4. 
5. 
stem from ...
1. 
2. 
3. 
4. 
5. 
come into fashion
1. 
2. 
3. 
4. 
5. 
base a. on b.
1. 
2. 
3. 
4. 
5. 
judge for yourself
1. 
2. 
3. 
4. 
5. 
do one's best (to do sth.)
1. 
2. 
3. 
4. 
5. 
take heart
1. 
2. 
3. 
4. 
5. 
be good for sb.
1. 
2. 
3. 
4. 
5. 
in the process
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
