#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 29 Funny or not?
#+begin_verse
What is the basis of 'sick' humour?

Whether we find a joke funny or not largely depends on where we have been brought up.
The sense of humour is mysteriously bound up with national characteristics.
A Frenchman, for instance, might find it hard to laugh at a Russian joke.
In the same way, a Russian might fail to see anything amusing in a joke
	which would make an Englishman laugh to tears.

Most funny stories are based on comic situations.
In spite of national differences, certain funny situations have a universal appeal.
No matter where you live, you would find it difficult
	not to laugh at, say, Charlie Chaplin's early films.
However, a new type of humour, which stems largely from the U.S., has recently come into fashion.
It is called 'sick humour'.
Comedians base their jokes on tragic situations like violent death or serious accidents.
Many people find this sort of joke distasteful.
The following example of 'sick humour' will enable you to judge for yourself.

A man who had broken his right leg was token to hospital a few weeks before Christmas.
From the moment he arrived there,
	he kept on pestering his doctor to tell him when he would be able to go home.
He dreaded having to spend Christmas in hospital.
Though the doctor did his best, the patient's recovery was slow.
On Christmas Day, the man still had his right leg in plaster.
He spent a miserable day in bed thinking of all the fun he was missing.
The following day, however, the doctor consoled him by telling him
	that his chances of being able to leave hospital in time for New Year celebrations were good.
The man took heart and, sure enough, on New Year's Eve he was able to hobble along to a party.
To compensate for his unpleasant experiences in hospital,
	the man drank a little more than was good for him.
In the process, he enjoyed himself thoroughly
	and kept telling everybody how much he hated hospitals.
He was still mumbling something about hospitals at the end of the party
	when he slipped on a piece of ice and broke his left leg.
#+end_verse

** words
largely [ˈlɑːrdʒli] adv. 在很大程度上
comic [ˈkɑːmɪk] adj. 喜剧的,可笑的
universal [ˌjuːnɪˈvɜːrs(ə)l] adj. 普遍的
comedian [kəˈmiːdiən] n. 滑稽演员,喜剧演员
distasteful [dɪsˈteɪstf(ə)l] adj. 讨厌的
pester [ˈpestər] v. 一再要求,纠缠
dread [dred] v. 惧怕
recovery [rɪˈkʌvəri] n. 康复
plaster [ˈplæstər] n. 熟石膏
console [kənˈsoʊl] v. 安慰,慰问
hobble [ˈhɑːb(ə)l] v. 瘸着退走
compensate [ˈkɑːmpenseɪt] v. 补偿
mumble [ˈmʌmb(ə)l] v. 喃喃自语

** 单词造句
largely adv.
1. 
2. 
3. 
4. 
5. 
comic adj.n.漫画  comic book/movie/novel
1. 
2. 
3. 
4. 
5. 
universal adj.  have a universal appeal
1. 
2. 
3. 
4. 
5. 
comedian n.
1. 
2. 
3. 
4. 
5. 
distasteful adj.
1. 
2. 
3. 
4. 
5. 
pester v.  pester sb. to do sth.
1. 
2. 
3. 
4. 
5. 
dread v.  dread dong sth.  dread sb. doing sth.
1. 
2. 
3. 
4. 
5. 
recovery n.  make a complete/quick/speedy/slow recovery
1. 
2. 
3. 
4. 
5. 
plaster n.
1. 
2. 
3. 
4. 
5. 
console v.  console sb./yourself that + ...
1. 
2. 
3. 
4. 
5. 
hobble v.
1. 
2. 
3. 
4. 
5. 
compensate v.  compensate (for sth.) = make up for
1. 
2. 
3. 
4. 
5. 
mumble v.
1. 
2. 
3. 
4. 
5. 

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
be bound up with
1. 
2. 
3. 
4. 
5. 
find it hard to do sth.
1. 
2. 
3. 
4. 
5. 
make sb. laugh to tears
1. 
2. 
3. 
4. 
5. 
stem from ...
1. 
2. 
3. 
4. 
5. 
come into fashion
1. 
2. 
3. 
4. 
5. 
base a. on b.
1. 
2. 
3. 
4. 
5. 
judge for yourself
1. 
2. 
3. 
4. 
5. 
do one's best (to do sth.)
1. 
2. 
3. 
4. 
5. 
take heart
1. 
2. 
3. 
4. 
5. 
be good for sb.
1. 
2. 
3. 
4. 
5. 
in the process
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
