#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L31 A lovable eccentric
#+begin_verse
Why did the shop assistant refuse to serve Dickie?

True eccentrics never deliberately set out to draw attention to themselves.
They disregard social conventions without being conscious that
	they are doing anything extraordinary.
This invariably wins them the love and respect of others,
	for they add colour to the dull routine of everyday life.

Up to the time of his death, Richard Colson was one of the most notable figures in our town.
He was a shrewd and wealthy businessman,
	but most people in the town hardly knew anything about this side of his life.
He was known to us all as Dickie and his eccentricity had become legendary long before he died.

Dickie disliked snobs intensely.
Though he owned a large car, he hardly ever used it, perferring always to go on foot.
Even when it was raining heavily, he refused to carry an umbrella.
One day, he walked into an expensive shop after having been caught in a particularly heavy shower.
He wanted to buy a $300 watch for his wife,
	but he was in such a bedraggled condition that an assistant refused to serve him.
Dickie left the shop without a word and returned carrying a large cloth bag.
As it was extremely heavy, he dumped it on the counter.
The assistant asked him to leave, but Dickie paid no attention to him and requested to see the manager.
Recognizing who the customer was,
	the manager was most apologetci and reprimanded the assistant severely.
When Dickie was given the watch, he presented the asssistant with the cloth bag.
It contained $300 in pennies.
He insisted on the assistant's counting the money before he left -- 30000 pennies in all!
On another occasion, he invited a number of important critics
	to see his private collection of modern paintings.
This exhibition received a great deal of attention in the press,
	for though the pictures were supposed to be the work of famous artists,
	they had in fact been painted by Dickie.
It took him four years to stage this elaborate joke simply to prove
	that critics do not always know what they are talking about.
#+end_verse

** words
lovable [ˈlʌvəbl] adj. 可爱的
eccentric [ɪkˈsentrɪk] n. (行为)古怪人
disregard [ˌdɪsrɪˈɡɑːrd] v. 不顾,漠视
convention [kənˈvenʃ(ə)n] n. 习俗,风俗
conscious [ˈkɑːnʃəs] adj. 感觉到的,意识到的
invariably [ɪnˈveriəbli] adv. 总是,经常地
routine [ruːˈtiːn] n. 常规;惯例
shrewd [ʃruːd] adj. 精明的
eccentricity [ˌeksenˈtrɪsəti] n. 怪癖
legendary [ˈledʒənderi] adj. 传奇般的
snob [snɑːb] n. 势力小人
intensely [ɪnˈtensli] adv. 强烈地
bedraggled [bɪˈdræɡ(ə)ld] adj. 拖泥带水的
dump [dʌmp] v. 把...砰的一声抛下
apologetic [əˌpɑːləˈdʒetɪk] adj. 道歉的
reprimand [ˈreprəmænd] v. 训斥
stage [steɪdʒ] v. 暗中策划
elaborate [ɪˈlæbərət] adj. 精心构思的

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
