#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 32 A lost ship
#+begin_verse
Did the crew of the Elkor find what they were looking for? Why?

The *salvage operation* had been a complete failure.
The small ship, Elkor, which had been searching the Barents Sea for weeks,
	was on its way home.
A radio message from the mainland had been received by the ship's captain
	instructing him to give up the search.
The captain knew that another attempt would be made later,
	for the sunken ship he was trying to find had been carrying *a precious cargo of* gold bullion.

Despite the message, the captain of the Elkor decided to try once more.
The sea bed was scoured with powerful nets
	and there was tremendous excitement on board when a chest was raised from the bottom.
Though the crew *were at first under the impression that* the lost ship had been found,
	the contents of the chest proved them wrong.
What they had in fact found was a ship which had been sunk many years before.

The chest contained the personal belongings of a seaman, Alan Fielding.
There were books, clothing and photographs,
	*together with* letters which the seaman had once received from his wife.
The captain of the Elkor ordered his men to salvage as much as possible from the wreck.
Nothing of value was found,
	but the numerous items which were brought to the surface proved to be of great interest.
From a heavy gun that was raised,
	the captain realized that the ship must have been a cruiser.
In another chest, which contained the belongings of a ship's officer,
	there was an unfinished letter which had been written on March 14th, 1943.
The captain leant from the letter that the name of the lost ship was the Karen.
The most valuable find of all was the ship's log book,
	parts of which it was still possible to read.
From this the captain was able to *piece together* all the information that had *come to light*.
The Karen had been sailing *in a convoy* to Russia when she was torpedoed by an enemy submarine.
This was later confirmed by *a naval official* at the Ministry of Defence
	after the Elkor had returned home.
All the items that were found were sent to the War Museum.
#+end_verse

** words
salvage [ˈsælvɪdʒ] v.救助,营救; 打捞
Barents ['bærənts] n.巴伦支(海)
sunken [ˈsʌŋkən] adj.沉没的
cargo n.货物
bullion [ˈbʊliən] n.金条;银条
scour [ˈskaʊər] v.彻底搜索
chest [tʃest] n.大箱子
contents [ˈkɑːntents] n.(复数)所装的东西
belongings [bɪˈlɔːŋɪŋz] n.(复数)所有物
item [ˈaɪtəm] n.物件
cruiser [ˈkruːzər] n.巡洋舰
find [faɪnd] n.找到的物品
log book [lɔːɡ-bʊk] 航海日志
piece [piːs] v.拼成整体
convoy [ˈkɑːnvɔɪ] n.护航
torpedo [tɔːrˈpiːdoʊ] v.用鱼雷攻击
submarine [ˈsʌbməriːn] n.潜水艇
naval [ˈneɪv(ə)l] adj.海军的
ministry [ˈmɪnɪstri] n.(政府的)部

** 单词造句
salvage v.n.  salvage operation
1. As we were struck by a rainstrom, the salvage operation was delayed for days.
2. Sure enough, there was a salvage operation in the open seas.
3. The salvage operation must have been gone on for sevaral days.
4. The salvage operation failed because of bad weather.
5. The salvage operation which was delayed for days should have gone on for weeks.
Barents n.
sunken adj.
1. These archaeologists never dreamed of finding a sunken ship which dates back to ancient times.
2. While the salvage operation was going on, a sunken ship had been found on the sea bed.
3. The captain was conscious that the sunken ship can't be found ever.
4. The captain found it impossible to find the sunken ship which they searched for weeks.
5. The captain kept the sunken ship in hiding until the end of the war.
cargo n.  a cargo of
1. The ship was gonna carry a cargo of fresh fruits and vegetables to London.
2. These workers had the impulse to unload a cargo of oranges from the ship.
3. The student in the university set a cargo of cell phones on fire last night. 
4. A worker felt sick to his stomach while waiting for a cargo of furniture. 
5. My boss got very angry when waitting for a cargo of furniture.
bullion n. un.
1. The pirate was delighted to unload gold bullion from the ship.
2. The boat was said to be loaded with silver bullion.
3. The boat was supposed to be loaded with gold bullion, together with silver bullion.
4. While I was taking a shower, I found a bullion in my bathroom.
5. It is illogical for your wife to throw away a gold bullion.
scour v.
1. I was anxious to scour my room to find my key to the truck.
2. My wife scoured our yard to clean up the snails.
3. The sad truth is that we scoured his room and found no evidence.
4. I noticed you scouring your room, why did you do that?
5. He scoured his drawer to find the pictures of his wife at the idea of his daughter.
chest n.
1. Going through the contents of chest, the pirate throw it into the sea.
2. I had the impulse to open the chest that belongs to my wife.
3. As he was tired of work, he dumpped his clothes on the chest.
4. He has received abuse from his mother, for he sat on the precious chest.
5. The chest was said to have numerous gold bullion.
contents n.
belongings n.
1. To my dismay, when we are about to drive you have not packed your belongings.
2. If you had packed your belongings in time, we wouldn't have been late for work.
3. For instance, he forgot to pack his belongings. 
4. My wife is brought up to pack her belongings by herself.
5. Don't forget your belongings just before you left the washroom. 
item n.
1. You are free to take these items with you.
2. Leo expressed his gratitude to me, for I let him have these items for free.
3. Make yourself comfortable. These items are free samples of perfume.
4. It is illogical to classify these items as something exempted from import duty.
5. The item I gave you last week is a mixture of wather and alcohol.
curiser n.
1. It used to be my job to fix curiser. 
2. We were greeted by an unpleasant smell when we repaired the curiser.
3. I felt guilty that I failed to repair the curiser.
4. On the other hand, the curiser was used to attack people without weapons.
5. There were a lot of excitement in the curiser after the salvage operation.
find n. thing
1. A gold bullion is always a find of value.
2. The order was given because of a valuable find. 
3. Armed with a torchlight in the cave, we indeed got valuable finds. 
4. The well-known archaeologist always gets valuable finds for one cause or another. 
5. On another occasion, he claimed that he got a valuable find in the cave.
log book
1. Waking up with a start, the captain begun to read the log book.
2. The seaman caught sight of a log book the captain was reading.
3. This seaman is equal to read the log book.
4. It is a pity that we didn't get enough money to read that log book in the museum.
5. We got used to reading the log book.
piece v.  piece together
1. After having pieced together what happened concerned with him, we all got very angry. 
2. The detective managed to piece together the information.
3. I'm sure that you had a perfect alibi, for I have pieced together what happened. 
4. I'm glad that you pieced together the fragments of the clock.
5. Equipped with a torchlight, he pieced together the fragments of paper.
convoy n.  in a convoy
1. In a convoy, these officers went to extremes to protect the president.
2. In a convoy, no one was allowed to walk on the street.
3. I was punished for the simple reason that they were in a convoy. 
4. In a convoy, the local police usually have a difficult time in keeping order.
5. Despite the fact that he was in a convoy, he put out the fire in the antique store.  
torpedo v. n.
1. I consloed the crew of the ship that we wasn't torpedoed by a submarine.
2. After several times, the captain found it hard to torpedo the ship out at sea.
3. Whether we are torpedoed or not largely depends on the damn weather.
4. The captain took heart and torpedoed the enemy ship.
5. To compensate for our loss, we must torpedo their ship.
submarine n.
1. The speical kind o submarine stems from the U.S.
2. The editor is so fanatical about submarines that he wrote an article on them.
3. His father claimed that he was killed in action in the submarine.
4. We might stay overnight in the submarine.
5. The expert went to great lengths to prove that the submarine hadn't been torpedoed.
naval adj. navy n.  a naval officer
1. A naval officer ordered his men to get rid of the submarine.
2. A naval officer claimed that he was impressed by the loss of the Titanic. 
3. I can't conceal the fact that the naval officer was killed in action.
4. A naval officer sped to the cruiser.
5. The naval officer had no intention of concealing it.
ministry
1. I used to work for the Ministry of Defence.
2. The teacher should be someone who used to work for the Ministry of Education.
3. A man who works for the Ministry of Defence asked me to do him a favor. 
4. It is outrageous that some students set the Ministry of Defence on fire. 
5. It is outrageous that a vendor bargained with passers-by in front of the Ministry of Education.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
sb. be under the impression that + ...
1. 
2. 
3. 
4. 
5. 
together with
1. 
2. 
3. 
4. 
5. 
come to light
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
