#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L32 A lost ship
#+begin_verse
Did the crew of the Elkor find what they were looking for? Why?

The salvage operation had been a complete failure.
The small ship, Elkor, which had been searching the Barents Sea for weeks,
	was on its way home.
A radio message from the mainland had been received by the ship's captain
	instructing him to give up the search.
The captain knew that another attempt would be made later,
	for the sunken ship he was trying to find had been carrying a precious cargo of gold bullion.

Desipte the message, the captain of the Elkor decided to try once more.
The sea bed was scoured with powerful nets
	and there was tremendous excitement on board when a chest was raised from the bottom.
Though the crew were at first under the impression that the lost ship had been found,
	the contents of the chest proved them wrong.
What they had in fact found was a ship which had been sunk many years before.

The chest contained the personal belongings of a seaman, Alan Fielding.
There were books, clothing and photographs,
	together with letters which the seaman had once received from his wife.
The captain of the Elkor ordered his men to salvages
	as much as possible from the wreck.
Nothing of value was found,
	but the numerous items which were brought to the surface proved to be of great interest.
For a heavy gun that was raised,
	the captain realized that the ship must have been a cruiser.
In another chest, which contained the belongings of a ship's officer,
	there was an unfinished letter which had been written on March 14th, 1943.
The captain leant from the letter that the name of the lost ship was the Karen.
The most valuable find of all was the ship's log book,
	parts of which it was still possible to read.
From this the captain was able to piece together all the information that had come to light.
The Karen had been sailing in a convoy to Russia when she was torpedoed by an enemy submarine.
This was later confirmed by a naval official at the Ministry of Defence
	after the Elkor had returned home.
All the items that were found were sent to the War Museum.
#+end_verse

** words
salvage [ˈsælvɪdʒ] v.救助,营救; 打捞
Barents ['bærənts] n.巴伦支(海)
sunken [ˈsʌŋkən] adj.沉没的
cargo n.货物
bullion [ˈbʊliən] n.金条;银条
scour [ˈskaʊər] v.彻底搜索
chest [tʃest] n.大箱子
contents [ˈkɑːntents] n.(复数)所装的东西
belongings [bɪˈlɔːŋɪŋz] n.(复数)所有物
item [ˈaɪtəm] n.物件
cruiser [ˈkruːzər] n.巡洋舰
find [faɪnd] n.找到的物品
log book [lɔːɡ-bʊk] 航海日志
piece [piːs] v.拼成整体
convoy [ˈkɑːnvɔɪ] n.护航
torpedo [tɔːrˈpiːdoʊ] v.用鱼雷攻击
submarine [ˈsʌbməriːn] n.潜水艇
naval [ˈneɪv(ə)l] adj.海军的
ministry [ˈmɪnɪstri] n.(政府的)部
