#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 33 A day to remember
#+begin_verse
What incident began the series of traffic accidents?

We have all experienced days when everything goes wrong.
A day may begin well enough, but suddenly everything seems to *get out of control*.
*What invariably happens is*
	that a great number of things choose to go wrong at precisely the same moment.
It is as if a single unimportant event *set up a chain of reactions*.
Let us suppose that you are preparing a meal and *keeping an eye on* the baby at the same time.
The telephone rings and this marks *the prelude to an unforseen series of* catastrophes.
While you *are on the phone*, the baby pulls the tablecloth off the table,
	smashing half your best crockery and cutting himself in the process.
You *hang up* hurriedly and *attend to* baby, crockery, et cetera.
Meanwhile, the meal gets burnt.
As if this were not enough to *reduce you to tears*,
	your husband arrives, unexpectedly bringing three guests to dinner.

Things can go wrong *on a big scale*,
	as a number of people recently discovered in Parramatta, *a suburb of Sydney*.
During the *rush hour* one evening two cars collided and both drivers began to argue.
The woman immediately behind the two cars happened to be a learner.
She suddenly *got into a panic* and stopped her car.
This made the driver following her brake hard.
His wife was sitting beside him holding a large cake.
As she was thrown forward, the cake went right through the windscreen and landed on the road.
Seeing a cake flying through the air,
	a lorry driver who was *drawing up alongside* the car,
		*pulled up all of a sudden*.
The lorry was loaded with empty beer bottles
	and hundreds of them *slid off* the back of the vehicle and on to the road.
This led to yet another angry argument.
Meanwhile, the traffic *piled up* behind.
It took the police nearly an hour to *get the traffic on the move* again.
In the meantime, the lorry driver had to *sweep up* hundreds of broken bottles.
Only two *stray dogs benefited from* all this confusion,
	for they greedily devoured what was left of the cake.
It was just one of those days!
#+end_verse

** words
prelude [ˈpreljuːd] n.序幕
unforeseen [ˌʌnfɔːrˈsiːn] adj.意料之外的
series [ˈsɪriːz] n.系列
catastrophe [kəˈtæstrəfi] n.大祸
crockery [ˈkrɑːkəri] n.陶器
suburb [ˈsʌbɜːrb] n.郊区
collide [kəˈlaɪd] v.猛撞
leaner [ˈliːnər] n.初学者
panic [ˈpænɪk] n.惊慌
windscreen [ˈwɪndskriːn] n.挡风玻璃
alongside [əˌlɔːŋˈsaɪd] prep.在...的旁边
slide [slaɪd] v.滑
stray [streɪ] adj.迷失的
confusion [kənˈfjuːʒ(ə)n] n.混乱的
greedily [ˈɡriːdɪli] adv.贪婪地
devour [dɪˈvaʊər] v.狼吞虎咽地吃

** 单词造句
prelude n.  a prelude to sth.
1. My wife claimed that reading fiction was a neccessary prelude to sleep.
2. Its setting out from the harbour was a prelude to the salvage operation.
3. The death of a naval officer might be a prelude to a war.
4. After they pieced together what happened, they suspected this was a prelude to a bigger attack.
5. I was under the impression
		that the arrival of my teacher was a prelude to the end of conversation.
unforeseen adj.  unforeseen + changes/problems/circumstances
1. Despite unforeseen changes, we have made a profit last year.
2. Despite unforeseen circumstances in the disater, the salvage operation proved to be successful.
3. Because of unforeseen problems, he at last failed the exam.
4. Due to unforeseen changes in the train schedule, he didn't have a perfect alibi any longer.
5. This manager was apologetic about sending the clothes late because of unforeseen weather.
series n.  a series of
1. I was conscious that a series of accidents was happening.
2. There used to be a series of activities in my daily routine.
3. This manager reprimanded the assistant for making a series of mistakes.
4. Although it took him three years to elaborate plan, he still made a series of mistakes.
5. The eccentric who disregards social conventions has made a series of mistakes.
catastrophe n.  be a catastrophe for sb.
1. Whether this would be a catastrophe for us or not, we should follow our father's instructions.
2. Failing the exam must have been a catastrophe for his academic future.
3. He has elaborated a plan which turned out to be a catastrophe for the life in his future.
4. He invited me to do math homework. This must be a catastrophe for me.
5. He added a sheet of paper in my collection. This may be a catastrophe for me.
crockery un.
1. It became an accepted fact that household wives love beautiful crockery.
2. The crockery was supposed to be smashed in the earthquake.
3. I stayed overnight to find her keep our crockery in hiding.
4. I found it impossible to sweep up the broken crockery in two hours.
5. She has a habit of collecting crockery for years.
suburb n.  in the suburbs/ a suburb of city
1. He claimed that his son was killed in action in the suburbs.
2. I love to wander in the suburbs in the moonlight.
3. We could not afford to the house in a suburb of New York.
4. He was said to be brought up in a suburb of New York.
5. Somehow, living in the suburbs is coming into fashion these days.
collide v.  collide with=run into
1. I felt sorry for the man whose car collided with the back of a truck last week.
2. She took heart, for she found that her car didn't run into the back of the truck.
3. For instance, she collided with another student in the process.
4. They collided with each other so that the teacher reprimanded them for this.
5. At the moment, the busman did his best not to collide with the car in front of him.
learner n.
1. You should not regard yourself as a learner and began to drive.
2. Whether you believe or not, regarding yourslef as a learner is not good for you.
3. It is important for a learner to judge for himself.
4. The great director based his film on a learner in London who has just passed the test.
5. The learner found it hard to drive as well as he thought.
panic n.  get into a panic
1. My wife got into a panic and pestered me to ask for a better salary.
2. These horror movies have a universal appeal which make us get into a panic swiftly.
3. Fearing of being put out of business, he soon got into a panic. 
4. The policeman consoled a person getting into a panic that everything was under control.
5. My tank wasn't filled with gas. This really made me get into a panic.
windscreen n. windshield
1. She has the impluse to clean the windscreen.
2. Though the windscreen reduced the price to $300, we still couldn't afford it.
3. She found her windscreen broken when she got back home.
4. My teacher used to order us to clean the windscreen.
5. He had the windscreen cleaned for free.
alongside prep. adv.  draw up alongside
1. He drew up alongside me and said: "Fancy meeting you here!"
2. I knew I might break the world record when I drew up alongside the fastest girl.
3. The policeman, who was drawing up alongside me, asked me to pull over.
4. It is disturbing to think that a truck is drawing up alongside you in the highway.
5. In the light of the chance of meeting her, I drew up alongside her.
slide slid slid v.  slide off/open
1. As the door slid open, he glanced at a man who was having an operation.
2. After the curtain went up, the glass slid off my knee and wake up my cat.
3. No one noticed that a glass slid off my knee in the dim light.
4. The glass slid off the table onto the floor and was broken.
5. As the door slid open, I saw my cat which was kidnappered a few days ago.
stray adj.  stray dogs
1. Because of stray dogs, she changed her mind of raising a cat.
2. Don't touch these stray dogs with your bare hands.
3. Technically speaking, they are not stray dogs.
4. Oddly enought, these stray dogs gained in popularity in those days.
5. A stray dog rose to fame swiftly because of his eccentricity.
confusion n.  There is some confusion about sth.
1. There is some confusion about what made your wife get into a panic.
2. There is some confusion about how to solve this problem.
3. There is some confusion about when I become fluent in English.
4. There is some confusion about whether he is a tramp or a beggar.
5. There is some confusion about who used to smoke in our family.
greedily adv. devour v.
1. My wife asked me not to greedily devour the pizza in the resturant.
2. My wife and me quarrled bitterly, for I greedily devoured pizza at the party.
3. People who live in poverty always greedily devour foods at the party.
4. I am starving to death and I am gonna devour the meal.
5. I am genuinely sorry that I greedily devoured the elaborated meal on your birthday.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
get out of control
1. We'd better  make it official,
	  otherwises everything will get out of control over and over again.
2. The fireplace got out of control and set the house on fire.
3. Everything on stage got out of control. This made customers laughed to tears.
4. These pumas found in America got out of control because of the rainstorms.
5. I consoled myself that nothing got out of control.
What invariably happens is that + ...
1. What invariably happens is
		that our senses of humor are bound up with our national characteristics.
2. What invariably happens is that everyone will die of illness or old age.
3. What invariably happens is that you must judge for yourself in a pariticuliar case.
4. What invariably happens is that your child pesters you to buy this or that product.
5. What invariably happens is that your daughter will fall in love with some guy in her youth. 
set up a chain of reactions
1. The boy dreaded having an operation and set up a chain of reactions.
2. The archaeologist made a complete recovery and set up a chain of reactions in the field.
3. This writer published a comic book and set up a chain of reactions in China.
4. To this day, this fire set up a chain of reactions.
5. My father indicate that my departure set up a chain of reactions at the party.
keep an eye on sb.
1. My girlfriend pestered me to keep on eye on her nephew.
2. I was filling my tank with gas and kept an eye on the baby at the same time.
3. If you keep an eye on the baby, I will let you have it.
4. At the base of the fact that she loves baby, I asked her to keep an eye on my baby.
5. I was impressed by a pretty mother who kept an eye on her baby.
be/speak/talk on the phone
1. If we spoke earlier on the phone, everything would go right.
2. She can't conceal the fact that she talked to her ex-boyfriend on the phone.
3. As a special favour, your will have an opportunity to talk to Leo on the phone. 
4. There is an element of truth that we should speak on the phone.
5. I felt guilty when I was speaking to her on the phone.
hang up (on sb.)
1. Before you hang up, you should say goodbye.
2. I realized to my horror that my wife hanged up and was frightened.
3. She hanged up on her boyfriend at the idea of his lie.
4. She hanged up on her parents and decided to gain her independence.
5. After hanging up on his wife, he realized to his horror that she was in difficulty. 
attend to sb./sth.
1. The nurse attempted to attend to the paitent who was injured in air crash.
2. Imagine his dismay when he found his wife attending to other man.  
3. There are lots of urgent businesses to attend to.
4. The moment he arrived in office, he attended to these tasks.
5. She was too busying attending to the baby to cook meal for us.
reduce sb. to tears
1. Just a moment earlier my shouting reduced my wife to tears.
2. If I reduce her to tears, I will apologize to her. 
3. As you smashed everything in the kitchen to pieces, this reduced her to tears. 
4. The background music which reminded her of her mother reduced her to tears.
5. The scrambled eggs reduced her to tears.
on a big/large/small scale
1. The mistake that is not big deal can make us run into serious trouble on a big scale. 
2. It takes me a long time to do the work on a big scale.
3. They decided to manufacture these kinds of biscuits on a large scale.
4. Your behavior has an influence on young people in China on a large scale.
5. The news that the actor stayed out of limelight capture people's attention on a big scale. 
drawing up alongside
1. The car which was drawing up alongside us pulled up all of a sudden.
2. There is a danger that a truck drawing up alongside us may collided with us.
3. The car which is drawing up alongside is likely to spy on us.
4. At first, the car draw up alongside us and then took the lead.
5. It gave us the impression that the car was drawing up alongside us.
rush hour
1. The rush hour is likely to start at 5.30 p.m. in China.
2. During rush hour, I found a lady following me rude.
3. During rush hour, I found a lady immediately behind me spying on me.
4. During rush hour, I used to read book to my child. 
5. During rush hour, I found it impossible to have a good seat.
pull up
1. There is no doubt that I must pull up at the idea of a flying cake.
2. He did his best to pull up in front of the garage.
3. The busman is about to pull up at the entrance of the street.
4. It is all very well you pulled up at the idea of accident.
5. After I pulled up, we set up our tent and had a picnic. 
all of a sudden = suddenly
1. It gave me the impression that we got everything under control all of a sudden. 
2. She died of a car accident all of a sudden. 
3. My stomach turned at the idea of meal she cooked yesterday all of a sudden.
4. It is illogical to decide to marry her all of a sudden.
5. It comes as a surprise to learn that I learnt it by heart all of a sudden.
pile up
1. The work began to pile up and drove me crazy.
2. Fearing that the problems piles up at work, she is anxious to attend to.
3. As the books began to pile up, my wife got very angry and asked me to throw away some of them.
4. Truman found it impossible to go through the bridge in an hour, for the traffic piled up.
5. The traffic piled up, you'd better choose to go another way. 
get the traffic on the move
1. She insisted that she got the traffic on the move.
2. You should not prevent the police from getting the traffic on the move.
3. She insisted that the police get the traffic on the move.
4. The police was anxious to get the traffic on the move.
5. The policeman was expected to get the traffic on the move.
sweep up
1. If you sweep up the broken bottles, we will not call the police.
2. The assistant insisted that he sweep up the broken bottles before he left.
3. The curtain went up, there was a old lady sweeping up her courtyard.
4. My grandmother used to sweep up the ground in the dim light.
5. I proceed to sweep up the ground.
benefit from sth.
1. It became an accepted fact that we all benefit from the advice Aristole gave.
2. You will benefit from the book about computer program in many years.
3. He claimed to have benefit from the news that a puma was at large. 
4. It is impossible to benefit from a blank sheet of paper.
5. It was not until the exam that she benefited from the advice from her teacher.

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
