#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 33 A day to remember
#+begin_verse
What incident began the series of traffic accidents?

We have all experienced days when everything goes wrong.
A day may begin well enough, but suddenly everything seems to get out of control.
What invariably happens is
	that a great number of things choose to go wrong at precisely the same moment.
It is as if a single unimportant event set up a chain of reactions.
Let us suppose that you are preparing a meal and keeping an eye on the bay at the same time.
The telephone rings and this marks the prelude to an unforseen series of catastrophes.
While you are on the phone, the bab pulls the tablecloth off the table,
	smashing half your best crockery and cutting imeself in the process.
You hang up hurriedly and attend to baby, crockery, ect.
Meanwhile, the meal gets burnt.
As if this were not enough to reduce you to tears,
	your husband arrives, unexpectedly bring three guests to dinner.

Things can go wrong on a big scale,
	as a number of people recently discovered in Parramatta, a suburb of Sydney.
During the rush hour one evening two cars collided and both drivers began to argue.
The woman immediately behind the two cars Happened to be a learner.
She suddenly got into a panic and stopped her car.
This made the driver following her brake hard.
His wife was sitting beside him holding a large cake.
As she was thrown forward, the cake went right through the windscreen and landed on the road.
Seeing a cake flying through the air,
	a lorry driver who was drawing up alongside the car,
#+end_verse

** words
prelude [ˈpreljuːd] n.序幕
unforeseen [ˌʌnfɔːrˈsiːn] adj.意料之外的
series [ˈsɪriːz] n.系列
catastrophe [kəˈtæstrəfi] n.大祸
crockery [ˈkrɑːkəri] n.陶器
suburb [ˈsʌbɜːrb] n.郊区
collide [kəˈlaɪd] v.猛撞
leaner [ˈliːnər] n.初学者
panic [ˈpænɪk] n.惊慌
windscreen [ˈwɪndskriːn] n.挡风玻璃
alongside [əˌlɔːŋˈsaɪd] prep.在...的旁边
slide [slaɪd] v.滑
stray [streɪ] adj.迷失的
confusion [kənˈfjuːʒ(ə)n] n.混乱的
greedily [ˈɡriːdɪli] adv.贪婪地
devour [dɪˈvaʊər] v.狼吞虎咽地吃

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
