#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 33 A day to remember
#+begin_verse
What incident began the series of traffic accidents?

We have all experienced days when everything goes wrong.
A day may begin well enough, but suddenly everything seems to *get out of control*.
*What invariably happens is*
	that a great number of things choose to go wrong at precisely the same moment.
It is as if a single unimportant event *set up a chain of reactions*.
Let us suppose that you are preparing a meal and *keeping an eye on* the baby at the same time.
The telephone rings and this marks *the prelude to an unforseen series of* catastrophes.
While you *are on the phone*, the baby pulls the tablecloth off the table,
	smashing half your best crockery and cutting himself in the process.
You *hang up* hurriedly and *attend to* baby, crockery, et cetera.
Meanwhile, the meal gets burnt.
As if this were not enough to *reduce you to tears*,
	your husband arrives, unexpectedly bringing three guests to dinner.

Things can go wrong *on a big scale*,
	as a number of people recently discovered in Parramatta, *a suburb of Sydney*.
During the *rush hour* one evening two cars collided and both drivers began to argue.
The woman immediately behind the two cars happened to be a learner.
She suddenly *got into a panic* and stopped her car.
This made the driver following her brake hard.
His wife was sitting beside him holding a large cake.
As she was thrown forward, the cake went right through the windscreen and landed on the road.
Seeing a cake flying through the air,
	a lorry driver who was *drawing up alongside* the car,
		*pulled up all of a sudden*.
The lorry was loaded with empty beer bottles
	and hundreds of them *slid off* the back of the vehicle and on to the road.
This led to yet another angry argument.
Meanwhile, the traffic *piled up* behind.
It took the police nearly an hour to *get the traffic on the move* again.
In the meantime, the lorry driver had to *sweep up* hundreds of broken bottles.
Only two *stray dogs benefited from* all this confusion,
	for they greedily devoured what was left of the cake.
It was just one of those days!
#+end_verse

** words
prelude [ˈpreljuːd] n.序幕
unforeseen [ˌʌnfɔːrˈsiːn] adj.意料之外的
series [ˈsɪriːz] n.系列
catastrophe [kəˈtæstrəfi] n.大祸
crockery [ˈkrɑːkəri] n.陶器
suburb [ˈsʌbɜːrb] n.郊区
collide [kəˈlaɪd] v.猛撞
leaner [ˈliːnər] n.初学者
panic [ˈpænɪk] n.惊慌
windscreen [ˈwɪndskriːn] n.挡风玻璃
alongside [əˌlɔːŋˈsaɪd] prep.在...的旁边
slide [slaɪd] v.滑
stray [streɪ] adj.迷失的
confusion [kənˈfjuːʒ(ə)n] n.混乱的
greedily [ˈɡriːdɪli] adv.贪婪地
devour [dɪˈvaʊər] v.狼吞虎咽地吃

** 单词造句
prelude n.  a prelude to sth.
1. My wife claimed that reading fiction was a neccessary prelude to sleep.
2. Its setting out from the harbour was a prelude to the salvage operation.
3. The death of a naval officer might be a prelude to a war.
4. After they pieced together what happened, they suspected this was a prelude to a bigger attack.
5. I was under the impression
		that the arrival of my teacher was a prelude to the end of conversation.
unforeseen adj.  unforeseen + changes/problems/circumstances
1. Despite unforeseen changes, we have made a profit last year.
2. Despite unforeseen circumstances in the disater, the salvage operation proved to be successful.
3. Because of unforeseen problems, he at last failed the exam.
4. Due to unforeseen changes in the train schedule, he didn't have a perfect alibi any longer.
5. This manager was apologetic about sending the clothes late because of unforeseen weather.
series n.  a series of
1. I was conscious that a series of accidents was happening.
2. There used to be a series of activities in my daily routine.
3. This manager reprimanded the assistant for making a series of mistakes.
4. Although it took him three years to elaborate plan, he still made a series of mistakes.
5. The eccentric who disregards social conventions has made a series of mistakes.
catastrophe n.  be a catastrophe for sb.
1. Whether this would be a catastrophe for us or not, we should follow our father's instructions.
2. Failing the exam must have been a catastrophe for his academic future.
3. He has elaborated a plan which turned out to be a catastrophe for the life in his future.
4. He invited me to do math homework. This must be a catastrophe for me.
5. He added a sheet of paper in my collection. This may be a catastrophe for me.
crockery un.
1. It became an accepted fact that household wives love beautiful crockery.
2. The crockery was supposed to be smashed in the earthquake.
3. I stayed overnight to find her keep our crockery in hiding.
4. I found it impossible to sweep up the broken crockery in two hours.
5. She has a habit of collecting crockery for years.
suburb n.  in the suburbs/ a suburb of city
1. He claimed that his son was killed in action in the suburbs.
2. I love to wander in the suburbs in the moonlight.
3. We could not afford to the house in a suburb of New York.
4. He was said to be brought up in a suburb of New York.
5. Somehow, living in the suburbs is coming into fashion these days.
collide v.  collide with=run into
1. I felt sorry for the man whose car collided with the back of a truck last week.
2. She took heart, for she found that her car didn't run into the back of the truck.
3. For instance, she collided with another student in the process.
4. They collided with each other so that the teacher reprimanded them for this.
5. At the moment, the busman did his best not to collide with the car in front of him.
learner n.
1. You should not regard yourself as a learner and began to drive.
2. Whether you believe or not, regarding yourslef as a learner is not good for you.
3. It is important for a learner to judge for himself.
4. The great director based his film on a learner in London who has just passed the test.
5. The learner found it hard to drive as well as he thought.
panic n.  get into a panic
1. My wife got into a panic and pestered me to ask for a better salary.
2. These horror movies have a universal appeal which make us get into a panic swiftly.
3. Fearing of being put out of business, he soon got into a panic. 
4. The policeman consoled a person getting into a panic that everything was under control.
5. My tank wasn't filled with gas. This really made me get into a panic.
windscreen n. windshield
1. She has the impluse to clean the windscreen.
2. Though the windscreen reduced the price to $300, we still couldn't afford it.
3. She found her windscreen broken when she got back home.
4. My teacher used to order us to clean the windscreen.
5. He had the windscreen cleaned for free.
alongside prep. adv.  draw up alongside
1. He drew up alongside me and said: "Fancy meeting you here!"
2. I knew I might break the world record when I drew up alongside the fastest girl.
3. The policeman, who was drawing up alongside me, asked me to pull over.
4. It is disturbing to think that a truck is drawing up alongside you in the highway.
5. In the light of the chance of meeting her, I drew up alongside her.
slide slid slid v.  slide off/open
1. As the door slid open, he glanced at a man who was having an operation.
2. After the curtain went up, the glass slid off my knee and wake up my cat.
3. No one noticed that a glass slid off my knee in the dim light.
4. The glass slid off the table onto the floor and was broken.
5. As the door slid open, I saw my cat which was kidnappered a few days ago.
stray adj.  stray dogs
1. Because of stray dogs, she changed her mind of raising a cat.
2. Don't touch these stray dogs with your bare hands.
3. Technically speaking, they are not stray dogs.
4. Oddly enought, these stray dogs gained in popularity in those days.
5. A stray dog rose to fame swiftly because of his eccentricity.
confusion n.  There is some confusion about sth.
1. There is some confusion about what made your wife get into a panic.
2. There is some confusion about how to solve this problem.
3. There is some confusion about when I become fluent in English.
4. There is some confusion about whether he is a tramp or a beggar.
5. There is some confusion about who used to smoke in our family.
greedily adv. devour v.
1. My wife asked me not to greedily devour the pizza in the resturant.
2. My wife and me quarrled bitterly, for I greedily devoured pizza at the party.
3. People who live in poverty always greedily devour foods at the party.
4. I am starving to death and I am gonna devour the meal.
5. I am genuinely sorry that I greedily devoured the elaborated meal on your birthday.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
get out of control
1. 
2. 
3. 
4. 
5. 
What invariably happens is that + ...
1. 
2. 
3. 
4. 
5. 
set up a chain of reactions
1. 
2. 
3. 
4. 
5. 
keep an eye on sb.
1. 
2. 
3. 
4. 
5. 
be/speak/talk on the phone
1. 
2. 
3. 
4. 
5. 
hang up (on sb.)
1. 
2. 
3. 
4. 
5. 
attend to sb./sth.
1. 
2. 
3. 
4. 
5. 
reduce sb. to tears
1. 
2. 
3. 
4. 
5. 
on a big/large/small scale
1. 
2. 
3. 
4. 
5. 
drawing up alongside
1. 
2. 
3. 
4. 
5. 
rush hour
1. 
2. 
3. 
4. 
5. 
pull up
1. 
2. 
3. 
4. 
5. 
all of a sudden = suddenly
1. 
2. 
3. 
4. 
5. 
pile up
1. 
2. 
3. 
4. 
5. 
get the traffic on the move
1. 
2. 
3. 
4. 
5. 
sweep up
1. 
2. 
3. 
4. 
5. 
benefit from sth.
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
