#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 34 A happy discovery
#+begin_verse
What was the 'happy discovery'?

*Antique shops exert a peculiar fascination on* a great many people.
The more expensive kind of antique shop
	where rare objects are beautiful displayed in glass cases to keep them free from dust
		is usually a *forbiding place*.
But no one has to *muster up courage to enter* a less pretentious antique shop.
*There is always hope*
	that *in its labyrinth of* musty, dark, disordered rooms
		a real rarity will be found amongst the piles of assorted junk that *litter the floors*.

No on discovers a rarity *by chance*.
A truly dedicated bargain hunter must have patience,
	and *above all*, the ability to recognize the worth of something when he sees it.
To do this, he must be at least as knowledgeable as the dealer.
Like a scientist *bent on making* a discovery,
	he must *cherish the hope that* one day he will be amply rewarded.

My old friend, Frank Halliday, is just such a person.
He has often *described to me how* he *picked up* a masterpiece of a mere 50 dollars.
One Saturday morning, Frank visited an antique shop in my neighbourhood.
As he had never been there before, he found a great deal to interest him.
The morning passed rapidly
	and Frank was about to leave when he noticed a large packing case lying on the floor.
The dealer told him that it had just come in,
	but that he *could not be bothered to open* it.
Frank *begged him to do* so and the dealer reluctantly *prised it open*.
The contents were disappointing.
Apart from an interesting-looking carved, the box was full of crockery, much of it broken.
Frank gently lifted the crockery out of the box
	and suddenly noticed a miniature painting *at the bottom of* the packing case.
As its composition and line reminded him of an Italian painting he knew well, he decided to buy it.
Glancing at it briefly, the dealer told him that it was worth 50 dollars.
Frank could hardly conceal his excitement,
	for he knew that he had made a real discovery.
The tiny painting proved to be an unknown masterpiece by Corrggio
	and was worth hundreds of thousands of pounds.
#+end_verse

** words
antique [ГҰnЛҲtiЛҗk] n. еҸӨи‘Ј,еҸӨзҺ©
fascination [ЛҢfГҰsЙӘЛҲneЙӘКғ(Йҷ)n] n.йӯ…еҠӣ,иҝ·жғ‘еҠӣ
forbidding [fЙҷrЛҲbЙӘdЙӘЕӢ] adj.жңӣиҖҢз”ҹз•Ҹзҡ„
muster [ЛҲmКҢstЙҷr] v.йј“иө·
pretentious [prЙӘЛҲtenКғЙҷs] adj.иҮӘе‘ҪдёҚеҮЎзҡ„
labyrinth [ЛҲlГҰbЙҷrЙӘnОё] n.иҝ·е®«
musty [ЛҲmКҢsti] adj.йҷҲи…җзҡ„,еҸ‘йңүзҡ„
rarity [ЛҲrerЙҷti] n.зЁҖдё–зҸҚе“Ғ
assorted [ЙҷЛҲsЙ”ЛҗrtЙӘd] adj.еҗ„ејҸеҗ„ж ·зҡ„
junk [dК’КҢЕӢk] n.з ҙзғӮиҙ§,еәҹе“Ғ
carve [kЙ‘Лҗrv] v.йӣ•еҲ»
dagger [ЛҲdГҰЙЎЙҷr] n.зҹӯеү‘
litter [ЛҲlЙӘtЙҷr] v.жқӮд№ұең°еёғж»Ў
dedicated [ЛҲdedЙӘkeЙӘtЙӘd] adj.дё“еҝғиҮҙеҝ—зҡ„
bargain [ЛҲbЙ‘ЛҗrЙЎЙҷn] hunter еҲ°еӨ„жүҫдҫҝе®ңиҙ§д№°зҡ„дәә
dealer [ЛҲdiЛҗlЙҷr] v.е•Ҷдәә
cherish [ЛҲtКғerЙӘКғ] v.жңҹжңӣ
amply [ЛҲГҰmpli] adv.и¶іеӨҹең°
masterpiece [ЛҲmГҰstЙҷrpiЛҗs] n.жқ°дҪң
mere [mЙӘr] adj.д»…д»…зҡ„
prise [praЙӘz] v.ж’¬ејҖ
miniature [ЛҲmЙӘnЙҷtКғЙҷr] adj.е°Ҹе·§зҡ„
composition [ЛҢkЙ‘ЛҗmpЙҷЛҲzЙӘКғ(Йҷ)n] n.жһ„еӣҫ

** DONE еҚ•иҜҚйҖ еҸҘ
CLOSED: [2023-12-27 Wed 23:04]
antique n.  antique shop/store/desk/jewelry
1. He showed me to his antique shop on Christmas day.
2. The only person who benefited from the antique desk is our cat, for she always sleeps on it.
3. The destory of the antique desk set up a chain of reactions.
4. The antique was set up on fire by students in the university and got out of control rapidly.
5. What invariably happens is that an antique jewelry can be broken.
fascination n.  hold/have a fascination for sb./sth.
1. I used to hold a fascination for Faker, a famous LoL player who won champions four times.
2. My wife seems to have a fascination for the room so that she swept it up all day.
3. The famous actor who stayed out of limelight has a fascination for antique jewelry.
4. It comes as a surprise to learn that she has a fascination for the albums of Leo.
5. I used to have a fascination for videos about traffic on rush hour.
forbidding adj.  forbidding place/look
1. A regiment of detectives are keeping guard in front of the door, it looks forbidding.
2. The forest must be a forbidding place which lives a witch.
3. The forbidding look of the policeman made it possible for him to get the traffic on the move.
4. He looked forbidding all of a sudden and pulled up.
5. The lorry driver who had a forbidding look was drawing up alongside our car.
muster v.  muster (up) the courage/confidence/to do sth.
1. If we mustered up the courage to build our country, we would be rich now.
2. The boy mustered up the courage to talk to his lover on the phone.
3. The action that he mustered up courage to tell her that he loves her
		 was a prelude to a series of catastrophes.
4. Fearing of unforeseen changes, he mustered up the courage to ask her out.
5. I decided to muster up the courage to propose to her in the suburbs.
pretentious adj.иҮӘе‘ҪдёҚеҮЎзҡ„;зӮ«иҖҖзҡ„
1. He is so pretentious that he was under the impression that girls in the class love him.
2. He is so pretentious that he refused to follow his boss's instructions.
3. He is so pretentious that he always pulls up all of a sudden.
4. I was so pretentious that I made every effort to laugh at some students who had bad grades.
5. She was so pretentious that she didn't follow in her father's footsteps.
labyrinth n.  in the labyrinth of sth.
1. I was curious to find out that there is a house in the labyrinth of trees.
2. In the labyrinth of traffic, she managed to go to work on time.
3. The police was told that a bomb was planted in the labyrinth of mall.
4. She might feel frightened in the labyrinth of trees.
5. In the labyrinth of items, I found a packet of sweets which my daughter kept in hidding.
musty adj.
1. I am sure that the clothes smells musty and you should change into another.
2. The room smells so musty that she lights a cigarette.
3. The lady kept on sweeping up these musty cigarette ends.
4. I am genuinely sorry that I offered you a musty room.
5. Everything in the room returns to normal and you will not find it musty anymore.
rarity n.
1. I am delighted that you made a discovery of a rarity in the antique shop.
2. This rarity he found in the antique shop gave him satisfaction a great deal.
3. He had a great appetite, for he got a rarity just then.
4. He lost his temper at the idea of the loss of a rarity.
5. He has suffered from the loss of a rarity for a few days.
assorted adj.
1. The assorted butterflies broke students' concentration and Mr. Leo got very angry.
2. I never have the nerve to handle assorted problems about friend relationships.
3. She noticed her aunt carrying a bag of assorted sweets to her room.
4. Rachel has the impluse to share assorted sweets with these children.
5. She went to great length to prove that there was a bag of assorted sweets on the table.
junk n.  junk mail
1. I am gonna go on a diet and refused to eat junk foods.
2. The surgeon had an operation and the room was full of junk.
3. It must be considered as a junk mail.
4. It gave me the impression that the junk mail was not important so I dropped it.
5. Oddly enough, my coworker pestered me to open the junk mail.
litter v.  be littered with sth.
1. The sign say: don't litter.
2. My wife never dreamed of litter the entrance hall with toys.
3. To compensate the experience in the school, she littered the living room with sweets.
4. She dreaded us littering the living room with junk.
5. Oddly enough, littering bed with flower has a universal appeal to girls.
dedicated adj.
1. I think of myself as a dedicated student, as I spend a few hours studying English.
2. It seems that a dedicated girl has a universal appeal to us.
3. I consoled my father that I am very dedicated.
4. My teacher indicated that I am the most dedicated student in our class.
5. The dedicated student eventually got rid of her classmate
		 who invited her to his house on rush hour.
bargain hunter
1. The bargain hunter was tempted to buy it from me.
2. It is outrageous that a bargain hunter buys something without comparing prices.
3. I was impressed by the bargain hunter who opened an antique shop.
4. It took me half an hour to get rid of the bargain hunter.
5. I have no intention of showing a bargain hunter to my antique shop.
dealer n.
1. The art dealer whose gallery was set on fire lived in poverty.
2. The art dealer threw up his arms and agreed to reduce the price to $300.
3. The art dealer always thinks of relationships in term of money.
4. The art dealer went to great lengths to prove
		that the diamond was real.
5. I can't conceal the fact that I bought it from the art dealer.
cherish v.  sb. cherish the hope that + ...
1. She cherishes the hope that the diamond as big as marbles is real.
2. She cherished the hope that she will not be assailed by her ex-boyfriend anymore.
3. She cherished the hope that the girl was tempted to eat the apple.
4. She cherished the hope that her keys ring was still on the desk.
5. She cherished the hope that she was free from housework.
amply adv.
1. She complained that the hotel didn't amply provide with Wi-Fi.
2. The love of my wife amply gave me spiritual comfort.
3. It is anticipated that hotels in China will amply provide us with Wi-Fi.
4. She was amply influenced by her mother who had recently studied English.
5. I amply pride myself on programming.
masterpiece n.
1. She devised a plan to buy a masterpiece abroad.
2. The painting was by no means considered to be a masterpiece.
3. They devised a way to turn these lesson into a masterpiece.
4. Whether you believe it or not, the masterpiece exerted a subtle influence on me.
5. Fulfilling my dream, I managed to turn it into a masterpiece.
mere adj.  The mere fact that + ... + 23456
1. The mere fact that she classified us as tramps is unacceptable.
2. The mere fact that she forgot to turn off the light set the house on fire.
3. The mere fact that a butterfly capture his attention makes him fail the exam.
4. The mere fact that she is so pretentious makes us get angry.
5. The mere fact that we were struck by storm made us fail to break the world record.
prise v.  prise sth. open
1. There is a danger that we must prise it open.
2. She managed to prise the lock open and take the lead.
3. Found that the lock coundn't be fitted with the key, she prised it open.
4. The mananger delayed in prising the door open.
5. The police arrived on the scene and prised it open with great ease.
carve v.  carve a. from/out of b.=a. be carved from/out of b.
1. There is no doubt that the statue was carved from a large stone.
2. It is clear that the Medoza was carved from a wood.
3. The man was able to carve a bear from the stone and took the lead.
4. Once upon a time, a sculptor carved a witch from a large stone.
5. It gave me the impression that the cat was carved from a skeleton.
dagger n.
1. I couldn't conceal the fact that I bought a toy dagger from a vendor.
2. There must have been a dagger in the drawer.
3. To varying degrees, the dagger must be carved from a large stone.
4. I won't let a lost dagger ruin my day.
5. Oddly enough, the medical student has a fascination on assorted daggers.
miniature adj.
1. I was strucked by a miniature train in the kindergarden.
2. My stomach would turn at the idea of miniature golf.
3. I noticed him playing with miniature train.
4. We used to play miniature train and stay for dinner in his house.
5. To my dismay, she didn't allow me to play her miniature train.
composition n.
1. The sad truth is that I can't take the composition of photographs into account.
2. My wife sticked to the composition of photographs.
3. It occurs to me to my wife at idea of composition of photographs.
4. My wife is always complaining that the composition of photographs are not good enough.
5. I didn't have the nerve to take the composition of photographs into account.

** еҸҚеӨҚеҗ¬з”өеҪұзүҮж®өзӣҙеҲ°жҮӮе…ій”®еҸҘ
** еӨҚд№ дәҢеҶҢиҜӯжі•(з¬”и®°жҲ–и§Ҷйў‘) & зәўзҡ®д№Ұ
** д№ жғҜз”Ёжі•йҖ еҸҘ
There is always hope that + ...
1. 
2. 
3. 
4. 
5. 
by chance
1. 
2. 
3. 
4. 
5. 
above all
1. 
2. 
3. 
4. 
5. 
be bent on doing sth.
1. 
2. 
3. 
4. 
5. 
sb. cherish the hope that + ...
1. 
2. 
3. 
4. 
5. 
described to sb. what/how + е®ҫд»Һ = describe sth. to sb.
1. 
2. 
3. 
4. 
5. 
pick up
1. 
2. 
3. 
4. 
5. 
sb. can't/couldn't be bothered to do sth.
1. 
2. 
3. 
4. 
5. 
beg sb. to do sth.
1. 
2. 
3. 
4. 
5. 
at the bottom of ...
1. 
2. 
3. 
4. 
5. 

** и·ҹиҜ» 50йҒҚ
** Comprehension еҸҚеӨҚз»ғд№ 
** Ask me if еҶҷ+иҜ»
** ж‘ҳиҰҒеҶҷдҪң еҶҷ & еҜ№зӯ”жЎҲ
** tell the story еҸЈиҜӯеӨҚиҝ°
** composition йҳ…иҜ» жҲ– еҶҷдҪң
** Topics for discussion
