#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 35 Justice was done
#+begin_verse
The word 'justice' is given two different meanings in the text.
What is the distinction between them?

The word justice is usually associated with *courts of law*.
We might say
	that *justice has been done* when a man's *innocence or guilt has been proved beyond doubt*.
Justice is part of the complex machinery of the law.
Those who seek it *undertake an arduous journey* and can never be sure that they will find it.
Judges, *however* wise or eminent, are human and can *make mistakes*.

*There are rare instances when* justice almost *ceases to be* an *abstract concept*.
Reward or punishment are *meted out* quite *independent of human interference*.
At such times, justice acts like a living force.
When we use a phrase like 'it serves him right',
	we are, *in part*, admitting
		that a certain set of circumstances has enabled justice to act *of its own accord*.

When a thief was caught *on the premises of* a large jewelery store one morning,
	the shop assistants must have found it impossible to resist the temptation
		to say 'it serves him right.'
The shop was an old converted house with many large, disused fireplaces and tall, narrow chimneys.
Towards midday, a girl heard a muffled cry coming from behind one of the walls.
As the cry was repeated several times,
	she *ran to tell* the manager who promptly *rang up* the fire brigade.
The cry had certainly come from one of the chimneys,
	but as there were so many of them, the fire fighters could not be certain which one it was.
They located the right chimney by *tapping at* the walls and *listening for* the man's cries.
After chipping through a wall which was eighteen inches thick,
	they found that a man had been trapped in the chimney.
As it was extremely narrow, the man was unable to move,
	but the fire fighters were eventually able to free him by cutting a huge hole in the wall.
The sorry-looking, blackened figure that emerged,
	admitted at once that he had tried to *break into* the shop during the night
		but had got stuck in the chimney.
He had been there for nearly ten hours.
Justice had been done even before the man *was handed over to* the police.
#+end_verse

** words
justice [ˈdʒʌstɪs] n.正义,公正;司法
court [kɔːrt] n.法院
law [lɔː] n.法律
innocence [ˈɪnəsns] n.无辜
undertake [ˌʌndərˈteɪk] v.承担;着手做
arduous [ˈɑːrdʒuəs] adj.艰苦的
abstract [ˈæbstrækt] adj.抽象的
concept [ˈkɑːnsept] n.概念,观念
mete [miːt] out 给予,处置
interference [ˌɪntərˈfɪrəns] n.干涉
accord [əˈkɔːrd] n.一致
premises [ˈpremɪsɪz] n.房屋
convert [kənˈvɜːrt] v.转变,改变
disused [ˌdɪsˈjuːzd] adj.不再用的,废弃的
fireplace [ˈfaɪərpleɪs] n.璧炉
muffle [ˈmʌf(ə)l] v.捂住,厌抑
chip [tʃɪp] v.砍
blacken [ˈblækən] v.使变黑
emerge [ɪˈmɜːrdʒ] v.(从某处)出现

** 单词造句
justice n.  justice has been done/served
1. I was bent on describing to my wife what happened in the court and how justice has been done.
2. He cherished the hope that justice would be done after the ganster was arrested.
3. The lawyer said that justice has been done and can't be bothered to help him anymore.
4. There is always hope that justice has been served by the authorities in China.
5. There was a time when justice was done in the society.
court n. law n.  court of law; courts of law
1. In the court of law, he managed to piece together all the information that had come to light.
2. In the court of law, the blacksmith carved a hero from the large stone.
3. In the court of law, the judge made a mistake by chance.
4. Above all, we are in the court of law and smoking is not allowed here.
5. She was bent on revealing the fact in the courts of law.
innocence n.  prove sb's innocence
1. In the court of law, the lawyer managed to prove her innocence. 
2. The teacher prised the box open and proved his students' innocence.
3. My room was littered with empty beer glasses and this proved my innocence.
4. She claimed that as she had a perfect alibi, she proved her innocence.
5. I'm glad that an unopned junk mail proved my innocence.
undertake v.  undertake a task/a project/research/a study/a journey
1. She undertook the task of cleaning up in the labyrinth of room.
2. The boy undertakes the task of cleaning up the room which was littered with flowers.
3. I mustered up the courage to undertake a journey to be fluent in English.
4. She undertookk a project which was expected to make a profit.
5. I undertook a journey to prove that she is innocent. 
arduous adj.
	arduous task of doing sth./arduous journey
	go through/embark on/begin arduous journey
1. The moment the order was given, he embarked on the arduous journey to break into the house.
2. The fire brigade arrived on the scene and begun arduous journey to rescue people.
3. Undertaking the project is an arduous task that has an influence on me for the rest of my life. 
4. Feeding the cat is not an arduous task that took you several hours.
5. She was going through the arduous journey to bring up her three children by her own.
abstract adj. concept n.  understand + abstract concept
1. I broke my attention so that I couldn't understand the abstract concept.
2. There was a time when I couldn't understand the abstract concept like love and happiness.
3. I made tremendous mistakes on these abstract concepts.
4. If you understood the abstract concept, you would have solved the problem.
5. It became accepted fact that he was bent on understanding these abstract concept in mathematic.
mete out
1. Mr. Leo meted out extra assignments to those students who played truent from school.
2. The students who cheated on the test must be meted out punishments.
3. The punishment was not meted out, for the guy has a perfect alibi.
4. Mr. Leo can't be bothered to mete out these students who talked on the phone in the class.
5. The poor girl cherished the hope that he would be meted out in the end.
interference n.  interference in sth.
	Sorry for the interference, + ...
	I hop you don't mind the interference, but + ...
1. Sorry for the interference, may I use your phone for a moment?
2. Sorry for the interference, I think you have lost your key.
3. Sorry for the interference, our company begins to make a profit.
4. I hope you don't mind the interference, but you have made some mistakes.
5. I hope you don't mind the interference, but your wife is having an operation.
accord n.  of sb's/sth's own accord
1. My child described to me of his own accord what happened in his school.
2. I picked up of my own accord in the station.
3. I decided to go to the antique shop of my own accord.
4. You must study hard of your own accord.
5. These passers-by got the traffic on the move again of their own accord.
premises n.  on the premises of a.
1. Whether you believed or not, the monster never dies on the premises.
2. Sure enough, smoking was not allowed to on the premises of a large jewelry.
3. She happened to make a real discovery on the premises of a large jewelry.
4. There is some confusion about the premises of our company.
5. Oddly enough, the lottery driver was drawing up alongside our boss on the premises. 
convert v.  convert a. to/into b.
1. She decribed to me how the old factory converted to a mall.
2. There is a store which was coverted into a bus station in the suburbs.
3. The authorities ordered the farmer to covert the field into forest.
4. It is a catastrophe for me that you and father converted my room into wash room.
5. It's outrageous that he converted a polluted factory into a house.
disused adj.
1. There are a disused rail station in my hometown.
2. We used to take a long walk alongside the disused rail way.
3. We should drive alongside the disused rail way until we arrived our hotel.
4. The disused chimney proved to be dangerous, for some stray dogs live there.
5. The cat used to live in the disused fireplace.
fireplace n.
1. She ran into fireplace while playing football.
2. This was a prelude to an accident which they set the fireplace on fire.
3. There are countless disused fireplaces in the suburbs.
4. The cat who was born in the fireplace was raised by me.
5. I was under the impression that the fireplace was useful.
muffle v.
1. 
2. 
3. 
4. 
5. 
chip v.
1. 
2. 
3. 
4. 
5. 
blacken v.
1. 
2. 
3. 
4. 
5. 
emerge v.  emerge from
1. 
2. 
3. 
4. 
5. 

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
beyond doubt
1. 
2. 
3. 
4. 
5. 
make mistakes
1. 
2. 
3. 
4. 
5. 
There are rare instances when + ...
1. 
2. 
3. 
4. 
5. 
cease to do
1. 
2. 
3. 
4. 
5. 
be independent of
1. 
2. 
3. 
4. 
5. 
in part
1. 
2. 
3. 
4. 
5. 
run to tell sb.
1. 
2. 
3. 
4. 
5. 
ring up
1. 
2. 
3. 
4. 
5. 
tap at sth.
1. 
2. 
3. 
4. 
5. 
listen for ...
1. 
2. 
3. 
4. 
5. 
be unable to do sth.
1. 
2. 
3. 
4. 
5. 
break into sp.
1. 
2. 
3. 
4. 
5. 
be handed over to
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
