#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L35 Justice was done
#+begin_verse
The word 'justice' is given two different meanings in the text.
What is the distinction between them?

The word justice is usually associated with courts of law.
We might say that justice has been done
	when a man's innocence or guilt has been proved beyond doubt.
Justice is part of the complex machinery of the law.
Those who seek it undertake an arduous journey
	and can never be sure that they will find it.
Judges, however wise or eminent, are human and can make mistakes.

There are rare instances when justice almost ceases to be an abstract concept.
Reward or punishment are meted out quite independent of human interference.
At such times, justice acts like a living force.
When we use a phrase like 'it serves him right', we are, in part,
	admitting that a certain set of circumstances has enabled justice to act of its own accord.

When a thief was caught on the premises of a large jewellery store one morning,
	the shop assistants must have found it
		impossible to resist the temptation to 'it serves him right.'
The shop was an old converted house with many large, disused fireplaces and tall, narrow chimneys.
Towards midday, a girl heard a muffled cry coming from behind one of the walls.
As the cry was repeated several times, she ran to tell the manager
	who promptly rang up the fire brigade.
The cry had certainly come from one of the chimneys,
	but as there were so many of them,
	the fire fighters could not be certain which one it was.
They located the right chimney by tapping at the walls and listening for the man's cries.
After chipping through a wall which was eighteen inches thick,
	they found that a man had been eventually able to free him by cutting a huge hole in the wall.
The sorry-looking, blackened figure that emerged, admitted at once
	that he had tried to break into the shop during the night
		but had got stuck in the chimney.
He had been there for nearly ten hours.
Justice had been done even before the man was handed over to the police.
#+end_verse

** words
justice [ˈdʒʌstɪs] n.正义,公正;司法
court [kɔːrt] n.法院
law [lɔː] n.法律
innocence [ˈɪnəsns] n.无辜
undertake [ˌʌndərˈteɪk] v.承担;着手做
arduous [ˈɑːrdʒuəs] adj.艰苦的
abstract [ˈæbstrækt] adj.抽象的
concept [ˈkɑːnsept] n.概念,观念
mete [miːt] out 给予,处置
interference [ˌɪntərˈfɪrəns] n.干涉
accord [əˈkɔːrd] n.一致
premises [ˈpremɪsɪz] n.房屋
convert [kənˈvɜːrt] v.转变,改变
disused [ˌdɪsˈjuːzd] adj.不再用的,废弃的
fireplace [ˈfaɪərpleɪs] n.璧炉
muffle [ˈmʌf(ə)l] v.捂住,厌抑
chip [tʃɪp] v.砍
blacken [ˈblækən] v.使变黑
emerge [ɪˈmɜːrdʒ] v.(从某处)出现

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
