#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 36 A chance in a million
#+begin_verse
What was the chance in a million?

We are less credulous than we used to be.
In the nineteenth century, a novelist would *bring his history to a conclusion*
	by presenting his readers with a series of coincidences -- most of them *wildly improbable*.
Readers happily *accepted the fact that* an obscure maidservant was really the hero's mother.
A long-lost brother, who *was presumed dead*, was really alive all the time
	and wickedly *plotting to bring about the hero's downfall*.
*And so on*.
Modern readers would find such naive solutions totally unacceptable.
Yet, in real life, circumstances do sometimes *conspire to* bring about coincidences
	which *anyone but* a nineteenth century novelist would find incredible.

When I was a boy,
	my grandfather told me
		how a German taxi driver, Franz Bussman, found a brother
			who *was thought to* have been killed twenty years before.
While on a walking tour with his wife, he *stopped to* talk to a workman.
After they had gone on,
	Mrs. Bussman *commented on the workman's close resemblance to her husband*
		and even *suggested that* he might be his brother.
Franz *poured scorn on* the idea,
	pointing out that his brother had been killed in action during the war.
Though Mrs. Bussman *was fully acquainted with* this story,
	she thought that *there was a chance in a million that* she might be right.
A few days later, she sent a boy to the workman to ask him
	if his name was Hans Bussman.
*Needless to say*, the man's name was Hans Bussman and he really was Franz's long-lost brother.
When the brothers *were reunited*, Hans explained how it was that he was still alive.
After having been wounded *towards the end of the war*,
	he had been sent to hospital and *was separated from* his unit.
The hospital had been bombed and Hans had *made his way back into* Western Germany on foot.
Meanwhile, his unit was lost and all records of him had been destroyed.
Hans *returned to* his family home,
	but the house had been bombed
		and no one in the neighbourhood knew what had *become of* the inhabitants.
*Assuming that* his family had been killed during an air raid,
	Hans settled down in a village fifty miles away where he had remained ever since.
#+end_verse

** words
credulous [ˈkredʒələs] adj.轻信的
improbable [ɪmˈprɑːbəbl] ad.不太可能的
obscure [əbˈskjʊr] adj.不起眼的
maidservant [ˈmeɪdsɜːrvənt] n.女仆
presume [prɪˈzuːm] v.假定
wickedly [ˈwɪkɪdli] adv.心眼坏地
plot [plɑːt] v.密谋
downfall [ˈdaʊnfɔːl] n.倒台
naive [naɪˈiːv] adj.天真的
unacceptable [ˌʌnəkˈseptəbl] adj.不能接受的
conspire [kənˈspaɪər] v.(事件)巧合促成
incredible [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance [rɪˈzembləns] n.相似
scorn [skɔːrn] n.嘲弄
acquaint [əˈkweɪnt] v.使了解
reunite [ˌriːjuˈnaɪt] v.使团聚
assume [əˈsuːm] v.假定,认为

** 单词造句
credulous adj.
1. He is less credulous than he used to be, for he has some opinions based on his values.
2. He is not credulous so that he avoided being fooled by authorities.
3. I am so credulous that I am unable to make a decision by myself.
4. The credulous boy played truent from school by listening to his partner.
5. If you were less credulous, you would make less mistakes.
improbable adj.  It seems (highly/wildly) improbable that + ...
1. It seems improbable that a pretty broke into the jewelry store during night.
2. It seems improbable that the gangster has been handed over to the US government.
3. It seems improbable that she has ran to tell her parents.
4. It seems improbable that she made no mistake on the exam.
5. It seems improbable that justice ceases to be an abstract concept in such situation.
obscure adj.
1. The obscure maidservant claimed that justice has been done in the courts of law.
2. The obscure prizefighter managed to prove his innocence.
3. The obscure artist who wanted to rise to fame undertook an ardulous task.
4. It is an obscure student who understands these abstract concepts.
5. The obscure grocer turned out to be the ganster who broke into the store.
maidservant n.
1. The maidservant went through arduous journey in the desert island of her own accord.
2. The maidservant was invited to do housework in a desert island.
3. In those days, maidservants were more likely to get a good salary.
4. The maidservant converted the house into her grocery.
5. A figure that emerged from the room was recognized as a maidservant.
presume v.  be presumed dead/innocent/guilty  presume that + ...
1. If he had been presumsed dead, his wife would have had a perfect alibi.
2. The gangster was presumed innocent by his lawyer in the courts of law.
3. I presumed that you had passed the exam.
4. She presumed that I cheated on her on vocation.
5. I begged my wife not to presumed that I had cheated on her in New York.
wickedly adv.
1. He wickedly described to me how to kidnap a lovable cat.
2. The witch wickedly begged the princess to drink some water in the well.
3. The evil boy wickedly prised the chest open.
4. Wickedly laughing, he kicked his partner's ass.
5. The witch wickedly carved a ghost out of the wood.
plot v.  plot to do sth.  plot against sb.
1. There is always hope that a ugly gilr plots against heroine in these stories.
2. He ploted to breakn into the antique shop.
3. In the labyrinth of the room, they ploted to play truent from school.
4. He cherished the hope that they ploted to betray against the king.
5. The mere fact that they ploted to cheat on exam has a bad influence in our school.
downfall n.  lead to sb's downfall  bring about sb's downfall
1. The mistakes she made in the contest led to her downfall by chance.
2. Above all, such stupid remarks might lead to your downfall.
3. My wife described to me how she brought about her boss' downfall.
4. No one but enemy will benefit from the accident which brought about his downfall.
5. The affairs piled up and led to his downfall.
naive adj.  it be naive enough to believe/think + ...  sb. be naive enough to believe/think + ...
1. I am naive enough to believe that kindness will always be rewarded.
2. She is naive enough to think that a man who runs a successful business is gonna marry her.
3. It is naive enough to believe that she collided with a car on April 1st.
4. It is naive enough to think that  a dog caused a series of accidents.
5. I am naive enough to believe that you have told me the truth.
unacceptable adj.  it be unacceptable to do sth.
1. It is unacceptable to reduce your wife to tears.
2. It is unacceptable to keep an eye on my neighbor while studying.
3. It is unacceptable to set the boat on fire.
4. It is unacceptable to set up a chain of reactions.
5. It is unacceptable to talk on the phone in the open air.
conspire v.  conspire to
1. They conspired to kill a regiment of stray dogs.
2. I was under the impression that they conspired to cheat on the exam.
3. This gave me the impression that they conspired to kidnap my cat.
4. They conspired to stay overnight in the hay.
5. I woke up to find that they conspired to keep me in hiding.
incredible adj.
	it is incredible (to sb.) that + ...
	it is incredible how + ...
	it is incredible to do sth.
1. 
2. 
3. 
4. 
5. 
resemblance n.
	bear a close/strong/striking resemblance to sb./sth.
	bear little/no resemblance to sb./sth.
	resemblance to ...
1. 
2. 
3. 
4. 
5. 
scorn n.  pour scorn on (idea/suggestion/plan/advice)
1. 
2. 
3. 
4. 
5. 
acquint v.  acquaint sb. with sth.  sb. be acquainted with sth.
1. 
2. 
3. 
4. 
5. 
reunite v.  be reunited with sb.
1. 
2. 
3. 
4. 
5. 
assume v.  assuming that + ...  it seems/is reasonable to assume that + ...
1. 
2. 
3. 
4. 
5. 

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
a chance in a million
1. 
2. 
3. 
4. 
5. 
bring ... to a conclusion
1. 
2. 
3. 
4. 
5. 
sb. accepted the fact that bring about
1. 
2. 
3. 
4. 
5. 
and so on
1. 
2. 
3. 
4. 
5. 
anyone but
1. 
2. 
3. 
4. 
5. 
be thought to
1. 
2. 
3. 
4. 
5. 
stop to do
1. 
2. 
3. 
4. 
5. 
comment on
1. 
2. 
3. 
4. 
5. 
suggest that + ...
1. 
2. 
3. 
4. 
5. 
there is/was a chance that + ...
1. 
2. 
3. 
4. 
5. 
needless to say
1. 
2. 
3. 
4. 
5. 
towards the end of + sth.
1. 
2. 
3. 
4. 
5. 
be separated from
1. 
2. 
3. 
4. 
5. 
make one's way back
1. 
2. 
3. 
4. 
5. 
return to
1. 
2. 
3. 
4. 
5. 
What become of
1. 
2. 
3. 
4. 
5. 

** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
