#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 36 A chance in a million
#+begin_verse
What was the chance in a million?

We are less credulous than we used to be.
In the nineteenth century, a novelist would bring his history to a conclusion
	by presenting his readers with a series of coincidences -- most of them wildly improbable.
Readers happily accepted the fact that an obscure maidservant was really the hero's mother.
A long-lost brother, who was presumed dead, was really alive all the time
	and wickedly plotting to bring about the hero's downfall.
And so on.
Modern readers would find such naive solutions totally unacceptable.
Yet, in real life, circumstances do sometimes conspire to bring about coincidences
	which anyone but a nineteenth century novelist would find incredible.

When I was a boy,
	my grandfather told me
		how a German taxi driver, Franz Bussman, found a brother
			who was thought to have been killed twenty years before.
While on a walking tour with his wife, he stopped to talk to a workman.
After they had gone on,
	Mrs. Bussman commented on the workman's close resemblance to her husband
		and even suggested that he might be his brother.
Franz poured scorn on the idea,
	pointing out that his brother had been killed in action during the war.
Though Mrs. Bussman was fully acquainted with this story,
	she thought that there was a chance in a million that she might be right.
A few days later, she sent a boy to the workman to ask him
	if his name was Hans Bussman.
Needless to say, the man's name was Hans Bussman and he really was Franz's long-lost brother.
When the brothers were reunited, Hans explained how it was that he was still alive.
After having been wounded towards the end of the war,
	he had been sent to hospital and was separated from his unit.
The hospital had been bombed and Hans had made his way back into Western Germany on foot.
Meanwhile, his unit was lost and all records of him had been destroyed.
Hans returned to his family home,
	but the house had been bombed
		and no one in the neighbourhood knew what had become of the inhabitants.
Assuming that his family had been killed during an air raid,
	Hans settled down in a village fifty miles away where he had remained ever since.
#+end_verse

** words
credulous [ЋИkred Т…Щl…Щs] adj.иљїдњ°зЪД
improbable […™mЋИpr…СЋРb…Щbl] ad.дЄНе§™еПѓиГљзЪД
obscure […ЩbЋИskj Кr] adj.дЄНиµЈзЬЉзЪД
maidservant [ЋИme…™ds…ЬЋРrv…Щnt] n.е•≥дїЖ
presume [pr…™ЋИzuЋРm] v.еБЗеЃЪ
wickedly [ЋИw…™k…™dli] adv.ењГзЬЉеЭПеЬ∞
plot [pl…СЋРt] v.еѓЖи∞Л
downfall [ЋИda Кnf…ФЋРl] n.еАТеП∞
naive [na…™ЋИiЋРv] adj.е§©зЬЯзЪД
unacceptable [ЋМ Мn…ЩkЋИsept…Щbl] adj.дЄНиГљжО•еПЧзЪД
conspire [k…ЩnЋИspa…™…Щr] v.(дЇЛдїґ)еЈІеРИдњГжИР
incredible […™nЋИkred…Щb(…Щ)l] adj.йЪЊдї•зљЃдњ°зЪД
resemblance [r…™ЋИzembl…Щns] n.зЫЄдЉЉ
scorn [sk…ФЋРrn] n.еШ≤еЉД
acquaint […ЩЋИkwe…™nt] v.дљњдЇЖиІ£
reunite [ЋМriЋРjuЋИna…™t] v.дљњеЫҐиБЪ
assume […ЩЋИsuЋРm] v.еБЗеЃЪ,иЃ§дЄЇ

** еНХиѓНйА†еП•
** еПНе§НеРђзФµељ±зЙЗжЃµзЫіеИ∞жЗВеЕ≥йФЃеП•
** е§Ндє†дЇМеЖМиѓ≠ж≥Х(зђФиЃ∞жИЦиІЖйҐС) & зЇҐзЪЃдє¶
** дє†жГѓзФ®ж≥ХйА†еП•
** иЈЯиѓї 50йБН
** Comprehension еПНе§НзїГдє†
** Ask me if еЖЩ+иѓї
** жСШи¶БеЖЩдљЬ еЖЩ & еѓєз≠Фж°И
** tell the story еП£иѓ≠е§Нињ∞
** composition йШЕиѓї жИЦ еЖЩдљЬ
** Topics for discussion
