#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L36 A chance in a million
#+begin_verse
What was the chance in a million?

We are less credulous than we used to be.
In the nineteenth century, a novelist would bring his history to a conclusion
	by presenting his readers with a series of coincidences -- most of them wildly improbable.
Readers happily accepted the fact that an obscure maidservant was really the hero's mother.
A long-lost brother, who was presumed dead, was really alive all the time
	and wickedly plotting to bring about the hero's downfall.
And so on.
Modern readers would find such naive solutions totally unacceptable.
Yet, in real life, circumstances do sometimes conspire to bring about coincidences
	which anyone but a nineteenth century novelist would find incredible.

When I was a boy,
	my grandfather told me
		how a German taxi driver, Franz Bussman, found a brother
			who was thought to have been killed twenty years before.
While on a walking tour with his wife, he stopped to talk to a workman.
After they had gone on,
	Mrs. Bussman commented on the workman's close resemblance to her husband
		and even suggested that he might be his brother.
Franz poured scorn on the idea,
	pointing out that his brother had been killed in action during the war.
Though Mrs. Bussman was fully acquainted with this story,
	she thought that there was a chance in a million that she might be right.
A few days later, she sent a boy to the workman to ask him
	if his name was Hans Bussman.
Needless to say, the man's name was Hans Bussman and he really was Franz's long-lost brother.
When the brothers were reunited, Hans explained how it was that he was still alive.
After having been wounded towards the end of the war,
	he had been sent to hospital and was separated from his unit.
The hospital had been bombed and Hans had made his way back into Western Germany on foot.
Meanwhile, his unit was lost and all records of him had been destroyed.
Hans returned to his family home,
	but the house had been bombed
		and no one in the neighbourhood knew what had become of the inhabitants.
Assuming that his family had been killed during an air raid,
	Hans settled down in a village fifty miles away where he had remained ever since.
#+end_verse

** words
credulous [ˈkredʒələs] adj.轻信的
improbable [ɪmˈprɑːbəbl] ad.不太可能的
obscure [əbˈskjʊr] adj.不起眼的
maidservant [ˈmeɪdsɜːrvənt] n.女仆
presume [prɪˈzuːm] v.假定
wickedly [ˈwɪkɪdli] adv.心眼坏地
plot [plɑːt] v.密谋
downfall [ˈdaʊnfɔːl] n.倒台
naive [naɪˈiːv] adj.天真的
unacceptable [ˌʌnəkˈseptəbl] adj.不能接受的
conspire [kənˈspaɪər] v.(事件)巧合促成
incredible [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance [rɪˈzembləns] n.相似
scorn [skɔːrn] n.嘲弄
acquaint [əˈkweɪnt] v.使了解
reunite [ˌriːjuˈnaɪt] v.使团聚
assume [əˈsuːm] v.假定,认为

