#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* L37 The Westhaven Express
#+begin_verse
What was the mistake the author made?

We have learnt to expect that trains will be punctual.
After years of conditioning,
	most of us have developed an unshakable faith in raily timetables.
Ships may be delayed by storms; flights may be cancelled because of bad weather;
	but trains must be on time.
Only an exceptionally heavy snowfall might temporarily dislocate railway services.
It is all too easy to blame the railway authorities when something does go wrong.
The truth is that when mistakes occur, they are more likely to be ours than theirs.

After consulting my railway timetable, I noted with satisfaction
	that there was an express train to Westhaven.
It went direct from my local station and the journey lasted a mere hour and seventeen minutes.
When I boarded the train, I could not help noticing that a great many local people got on as well.
At the time, this did not strike me as odd.
I reflected that there must be a great many people besides myself
	who wished to take advantage of this excellent service.
Neither was I surprised when the train stopped at Widley,
	a tiny station a few miles along the line.
Even a mighty express train can be held up by signals.
But when the train dawdled at station after station, I began to wonder.
It suddenly dawned on me that this express was not roaring down the line at ninety miles an hour,
	but barely chugging along at thirty.
One hour and seventeen minutes passed and we had not even covered half the distance.
I asked a passenger if this was the Westhaven Express,
	but he had not even heard of it.
I determined to lodge a complaint as soon as we arrived.
Two hours later, I was talking angrily to the station master at Westhaven.
When he denied the train's existence, I borrowed his copy of the timetable.
There was a note of triumph in my voice when I told him that it was there in black and white.
Glancing at it briefly, he told me to look again.
A tiny asterisk conducted me to a footnote at the bottom of the page.
It said: 'This service has been suspended.'
#+end_verse

** words
express [ɪkˈspres] n.快车
punctual [ˈpʌŋktʃuəl] adj.准时的
condition [kənˈdɪʃ(ə)n] v.使习惯于
unshakable [ʌnˈʃeɪkəbl] adj.不可动摇的
faith [feɪθ] n.信任
cancel [ˈkæns(ə)l] v.取消
exceptionally [ɪkˈsepʃənəli] adv.例外地
dislocate [ˈdɪsloʊkeɪt] v.打乱(计划等)
blame [bleɪm] v.责怪
consult [kənˈsʌlt] v.请教
direct [dəˈrekt] adv.径直地
odd [ɑːd] adj.奇怪的
reflect [rɪˈflekt] v.细想
advantage [ədˈvæntɪdʒ] n.优势
mighty [ˈmaɪti] adj.强大的
dawdle [ˈdɔːd(ə)l] v.慢吞吞地动
chug [tʃʌɡ] v.咔嚓喀嚓地响
lodge [lɑːdʒ] v.提出
complaint [kəmˈpleɪnt] n.抱怨
triumph [ˈtraɪʌmf] n.胜利
asterisk [ˈæstərɪsk] n.星号
conduct [kənˈdʌkt] v.引向
