#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 37 The Westhaven Express
#+begin_verse
What was the mistake the author made?

We have learnt to expect that trains will be punctual.
After years of conditioning,
	most of us have *developed an unshakable faith in* railway timetables.
Ships may be delayed by storms; flights may be cancelled because of bad weather;
	but trains must be on time.
Only an exceptionally heavy snowfall might temporarily dislocate railway services.
*It is all too easy to blame* the railway authorities when something does go wrong.
The truth is that when mistakes occur, they are more likely to be ours than theirs.

After *consulting my railway timetable*,
	I *noted with satisfaction that* there was an express train to Westhaven.
It *went direct* from my local station and the journey lasted a mere hour and seventeen minutes.
When I boarded the train, I *could not help noticing* that a great many local people got on as well.
At the time, this did not *strike me as odd*.
I *reflected that* there must be a great many people besides myself
	who *wished to take advantage of* this excellent service.
Neither was I surprised when the train stopped at Widley,
	a tiny station a few miles along the line.
Even a mighty express train can *be held up* by signals.
But when the train dawdled at station after station, I began to wonder.
*It suddenly dawned on me*
	that this express was not *roaring down* the line at ninety miles an hour,
		but barely chugging along at thirty.
One hour and seventeen minutes passed and we had not even covered half the distance.
I asked a passenger if this was the Westhaven Express,
	but he had not even *heard of* it.
I determined to *lodge a complaint* as soon as we arrived.
Two hours later, I was talking angrily to the station master at Westhaven.
When he denied the train's existence, I borrowed his *copy of* the timetable.
There was *a note of triumph* in my voice when I told him that it was there *in black and white*.
Glancing at it briefly, he told me to look again.
A tiny asterisk *conducted me to* a footnote *at the bottom of* the page.
It said: 'This service has been suspended.'
#+end_verse

** words
express [ɪkˈspres] n.快车
punctual [ˈpʌŋktʃuəl] adj.准时的
condition [kənˈdɪʃ(ə)n] v.使习惯于
unshakable [ʌnˈʃeɪkəbl] adj.不可动摇的
faith [feɪθ] n.信任
cancel [ˈkæns(ə)l] v.取消
exceptionally [ɪkˈsepʃənəli] adv.例外地
dislocate [ˈdɪsloʊkeɪt] v.打乱(计划等)
blame [bleɪm] v.责怪
consult [kənˈsʌlt] v.请教
direct [dəˈrekt] adv.径直地
odd [ɑːd] adj.奇怪的
reflect [rɪˈflekt] v.细想
advantage [ədˈvæntɪdʒ] n.优势
mighty [ˈmaɪti] adj.强大的
dawdle [ˈdɔːd(ə)l] v.慢吞吞地动
chug [tʃʌɡ] v.咔嚓喀嚓地响
lodge [lɑːdʒ] v.提出
complaint [kəmˈpleɪnt] n.抱怨
triumph [ˈtraɪʌmf] n.胜利
asterisk [ˈæstərɪsk] n.星号
conduct [kənˈdʌkt] v.引向

** vocabulary
punctual: on time
unshakable faith: a firm belief or trust
delayed: made late
cancelled: called off
temporarily dislocate: disrupt for a short time
consulting: reading,looking at
a mere: only, just

** DONE 单词造句
CLOSED: [2024-01-08 Mon 15:42]
express n. adj.
1. I had a glimpse of the express train at the station a few miles along the line.
2. This express was expected to be punctual.
3. We are conditioned to catch a express punctually.
4. If you don't hurry up, you might miss the express train.
5. We are gonna go to the theatre by an express bus.
punctual adj. punctually adv.  be punctual for
1. There is a chance that we can be punctual for the business meeting. 
2. The cat was punctual for making his way back home.
3. She was thought to be punctual for the task.
4. She was thought to be punctual for the appointment which they made last week.
5. Needless to say, he wasn't punctual for the meeting which was held by his father again.
condition v.  condition sb. to (do) sth.  sb. be conditioned to do sth.
1. This conditioned me to ask for help in difficulty.
2. This conditioned the dog to rescue people struck by snow storms.
3. The dog was conditioned to sit down with order given.
4. It seems improbable that I was conditioned to have a rest in the afternoon.
5. His mother was conditioned to conspire to his downfall.
unshakable adj.  develop an unshakable belief/faith in  have/lose faith in sb./sth.
1. She developed an unshakable belief in his father who was expected to break the world record. 
2. We must develop an unshakable faith in God.
3. I lost faith in my wife and don't expect her to help me anymore.
4. It is incredible that your daughter lost faith in you.
5. The man presumed guilty develop an unshakable faith in justice in the courts of law.
faith n.
1. I wished that he had had faith in me.
2. It is clear that he has lost his faith in us who are spying on him day and night.
3. Although this house was broken into, we must have faith in his downfall.
4. I have faith in my husband who managed to lead to her downfall.
5. I presumed that you have faith in your dream.
cancel v.
1. It seems highly improbable that the meeting will be cancelled because of your absence.
2. The meeting which was thought to be cancelled was held towards the end of this year.
3. We have to cancel the meeting, for we are separeted from our children.
4. The boss returned to his office and informed that the meeting had been cancelled.
5. No one know what become of the boss who was gonna to cancel the appointment.
exceptionally adv.
1. There is a chance in a million that a teacher in poverty explains it exceptionally clear.
2. Needless to say, she was exceptionally tired of work.
3. This bring his story to a conclusion that Leo was exceptionally excellent English teacher.
4. I was exceptionally with my father's characteristics.
5. Assuming that the weather was exceptionally cold, he carried a box of clothes to New York.
dislocate v.
1. It seems reasonable to assume that the snowfall will dislocate the railway service tomorrow.
2. He poured scorn on his idea, pointing out that the flight had been dislocated by a heavy fog.
3. It is incredible how a boy who played from school dislocated the railway service.
4. It is naive enough to belive that a rain can dislocate the railway service.
5. Even if this led to his downfall, we are determined to dislocate the flight.
blame v.  blame sb./sth. for  blame sth. on sb.
1. She blamed her loss in the mall on me. 
2. At that time, I was under the impression that you blamed this on me.
3. You are shamed of blaming everything on a young boy.
4. In my youth, my mother used to blame broken vases on me.
5. I was unable to blame me for what happened recently.
consult v.  consult the map/manual/dictionary
1. If you consulted the map, you would know the way to your hotel.
2. Leo reprimanded us for asking him questions before consulting the dictionary.
3. I am conscious of consulting the manual of the old machine.
4. He dumped it on the drawer after consulting the dicitonary.
5. You may consult the timetables which was elaborated by the crew.
direct adv.  go/fly direct
1. It occured to me that we could fly direct from the Carribean to Beijing.
2. The poor girl accepted the fact that her boyfriend went direct back to his hometown.
3. What happened to the girl who went direct back to her room?
4. The author brought his story to a conclusion
		that the young couples flied direct to their hometown.
5. Anyone but you flied direct from Shanghai to England.
odd adj.  It is/seems odd that + ...
1. It is odd that you are reunited with your husband.
2. It is odd that you poured scorn on such a beatiful girl.
3. It is odd that you bear little resemblance to your father.
4. It is odd that you are acquainted with my teacher, Mr. Leo.
5. It is odd that they conspire to bring about his downfall.
reflect v.  reflect that + ...  reflect on sth.
1. I reflected that there was a chance that she might be right.
2. I reflected that if I didn't pour scorn on her, it would be totally different.
3. I reflected that the railway service might be dislocated by the snowfall.
4. I reflected on the story which he told me last night.
5. I reflected on the woman who poisoned her five husbands in her youth.
advantage n.
1. Beyond doubt, online classes have the advantage that you can repeat it as many as you want.
2. One of the advantages of living in a hotel located	in town is that the traffic is convenient.
3. She took advantage of this material and listened it several times.
4. Disregarding social conventions, the eccentric took advantage of others' mercy.
5. I found it impossible to take advantage of this wood without sticks.
mighty adj.
1. The lady claimed to have seen a mighty puma at large.
2. I was conscious that there was still a mighty puma at large in the countryside.
3. A various of factors conspired to cause the death of a mighty lion.
4. It comes as a surprised to learn that a mighty lion was killed in the forest.
5. He denied that he didn't cut any mighty trees at the edge of a forest.
dawdle v.
1. My colleague is always asking me to dawdle on the task
		so that he could make his way back to his home on Friday afternoon.
2. I hated to dawdle in the process.
3. He accepted the fact that the express train dawdled at station after station.
4. He suggested that the express train was dawdled in the way to England.
5. If you dawdled in your work, your boss might reprimand you for you delay.
chug v.
1. Oddly enough, there is a boat chugging out at sea.
2. If the boat kept chugging out into the sea, it may turn my stomach.
3. I felt sick to my stomach, for the train chugging alongside the line.
4. The sad truth is that we have to catch the train which is chugging.
5. I have the impulse to leave the chugging train.
lodge v.  lodge a complaint  
1. It is illogical to lodge a comlaint when he gave you spiritual comfort.
2. After a heavy shower, I decided to lodge a complaint with his parents.
3. I have the impulse to lodge a complaint about the rude behaviors of the waiter.
4. Because I lodged a complaint with the manager, I received abuse from him.
5. Lodging a complaint about your rudeness really appeals to me.
complaint n.  have/make/receive/lodge a complaint
1. The waiter got very angry when he knew he received a complaint from the consumer.
2. I made a complaint so that justice will be done.
3. She hesitated to make a complaint, for the waiter threatened to kill her if she does.
4. She realized to her horror that she received a complaint from her student.
5. On the other hand, I was not willing to lodge a complaint.
triumph n.  a note of triumph
1. There was a note of triumph in my voice when I told my parent that I was gonna go to university.
2. I wish that you made a speech with a note of triumph in the open.
3. Passing the test, he made his way back to home with a note of triumph. 
4. There was a note of triumph in my voice when I received a warm welcome at the monastery.
5. There was a note of triumph in his voice when he won a prize for the best director at Oscar.
asterisk n.
1. There is an asterisk in black and white.
2. Put asterisks beside the names of those who believe in God.
3. My boss asked to put asterisks beside the names of those who follows his instructions. 
4. Attention to the asterisks. These often lead to some important extra informations.
5. So long as you pay attention to the asterisk, you would not make such mistakes.
conduct v.  conduct sb. to
1. This young woman conducted my father to the block of flats.
2. The kidnappers wickedly conducted the cat to a flat.
3. My boss shaked his head and conducted me to the corner.
4. It occured to me that it was him who conducted my cat to the bank of river.
5. The salesman conducted me to a tent where I signed for a reachment.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2024-01-08 Mon 20:05]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2024-01-08 Mon 15:42]
It is all too easy to do sth.
1. It is all too easy to blame everything on your boyfriend in China.
2. It is all too easy to cook scrambled eggs.
3. It is all too easy to smash a blank sheet of paper into pieces. 
4. It is all too easy to buy a pen from a vendor which couldn't write a single word.
5. It is all too easy to grab a beer after work.
sb. noted with satisfaction that + ...
1. She noted with satisfaction that she had passed the driver test.
2. I noted with satisfaction that my daughter managed to go to university.
3. She noted with satisfaction that the bus came at a fantastic speed. 
4. I noted with satisfaction that I smashed everything in the kitchen to pieces.
5. I noted with satisfaction that my wife and my daughter was wandering around the arcade.
can't help doing sth.
1. I can't help noticing that she made remarks on me.
2. I can't help grabbing a coffee while having a rest.
3. I can't help listening to music while working.
4. She can't help thinking of him all the day.
5. She can't help putting her money in the microwave oven for safekeeping.
strike sb as ...
1. He strikes me as a person who is very rude to women.
2. You didn't strike me as a kind of person who is responsible for his work.
3. My boss strikes me as a man who takes his job very seriously.
4. You struck me as a busman who is determined to go on a diet.
5. He struck me as an odd man who didn't carry umbrella while raining.
take advantage of
1. My wife was determined to take advantage of the discount and go on vacation in SanYa.
2. Considering taking advantage of the discount, we ordered more meals than we expected.
3. Following my boss' instrcutions, we took advantage of the laptop.
4. It astounded me that a bird took advantage of stones and managed to drink water in the bottle.
5. The kidnapper took advantage of his love to the cat and got a ransom of $100.
wish to do sth.
1. I don't wish to receive an anonymous letter.
2. I wish to leave in an orderly fashion.
3. She wished to share her room with her boyfriend.
4. I wishes to follow in my father's footstep.
5. She wishes to have a good time in the hotel.
hold up
1. We might be late for the meeting, the traffic began to be held up.
2. A series of coincidences caused a serious accident which had held up the traffic all the day.
3. I explained how the accident help up the traffic, but they didn't believe me. 
4. There was a man who was held up in the cave and starved to death.
5. There is a danger that we can be held up in the mountain and starve to death.
It dawned on me that + ...
1. It dawned on me that it was Mr. Leo who stole my lamb.
2. It dawned on me that Mr. Leo sent me an anonymous letter.
3. It dawned on me that we should go to the police.
4. It dawned on me that he didn't have a perfect alibi.
5. It dawned on me that the cat was still in safe hands.
roar down
1. She changed her mind and claimed to have seen a car roaring down the highway.
2. The car roaring down the highway is very dear to me.
3. Following my instructions, my child managed to see the train roaring down the line.
4. I used to see the train roaring downing behind my house in my youth.
5. It occured to me that an express train was roaring down the line.
not ... but ...
1. He was not a docter that we thought but a policeman.
2. He offered me not English books but Math books.
3. Not my grandfather but my father offered money to me.
4. Not the firefighter but his pupils rose to fame swiftly.
5. I am gonna changed my pocket money into not clothes but sweets.
hear of
1. After hearing of what become of his pupils, he turned against him.
2. All the arguments were settled when they heard of the news.
3. Sorry to interrupt, I never heard of books named Harry Potter.
4. I heard of an actor who was cast in the role of pirates of the Caribbean.
5. In the dim light, I heard of the fact that you poisoned your five husbands.
copy of ...
1. Would you like carry a copy of newspaper to me?
2. I am anxious to read a copy of timetables.
3. He was expected to hand a copy of paper to our boss.
4. She insited that the writer hand a copy of paper to her.
5. I don't cause to carry a copy of paper to you.
in black and white
1. The police gave me a ticket, informing that the rules had been written in black and white.
2. The prices have been written in black and white, you must pay the bill.
3. It is a pity that this hasn't been written in black and white.
4. I realized that the deal had been written in black and white.
5. She complained that the rules haven't been written in black and white.
at the bottom of ...
1. It is incredible how you add my name to the list at the bottom of the page.
2. There was an interesting carved dagger at the bottom of the chest.
3. It was Davy Jone's heart which was placed at the bottom of the chest.
4. It seems reasonable to assume that the password was written at the bottom of the page.
5. Because of the information at the bottom of the page I was reunited with my daughter.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2024-01-08 Mon 20:05]
** DONE Ask me if 写+读
CLOSED: [2024-01-08 Mon 20:10]
1. We have learnt to expect trains to be punctual. What
	 What have we learnt to expect?
2. Flights may be cancelled because of bad weather. Why
	 Why may flights be cancelled?
3. It is easy to blame the railway authorities. How easy
	 How easy is it to blame the railway authorities?
4. There was an express train to Westhaven. What kind of
	 What kind of train was there to Westhaven?
5. The journey should last an hour and seventeen minutes. How long
	 How long should the journey last?
6. A lot of local people got on the train as well. Who
	 Who got on the train as well?
7. The writer was surprised when the train stopped at Widley. Why wasn't
	 Why wasn't the writer surprised when the train stopped at Widley?
8. They had only gone half the distance after an hour and seventeen minutes. How far
	 How far had they only gone after an hour and seventeen minutes?
9. The station master denied the existence of the Westhaven Express. What
	 What did the station master deny?
10. A footnote said that the service had been suspended. What
		What did a footnote say?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2024-01-08 Mon 20:31]
When the writer boarded the train, he noticed that a lot of local people got on as well.
Nor was he surprised when the train stopped at Widley,
	for even an express train may be delayed by signals.
When the train dawdled at station after station,
	he realized that this express was chugging at thrity.
He didn't cover half the distance after one hour and seventeen minutes.
So he asked the passager, who told him that he didn't hear of the express.
Two hours later, he was arguing with the station master.
He told the master that the express was on the timetable in black and white.
However, a tiny asterisk conducted him to a footnote,
	which said: "This service has been suspended".

When many local people boarded the train with the writer,
	he was not surprised.
Nor was he surprised when the train stopped at Widley.
But when it stopped at each station, he began to wonder why it was going so slowly.
Finally, when the train reached Westhaven,
	the writer spoke to the station master who denied the existence of an express.
They argued and the writer was shown this timetable footnote,
	which said: 'This service has been suspended'.

** DONE tell the story 口语复述
CLOSED: [2024-01-08 Mon 20:31]
** composition 阅读 或 写作
When I finally boarded the train,
	I was looking forward to a pleasant journey to the village of Slowleigh
		where my friends live.
I sat in my seat got out a book and was already reading when the train started.
According to the timetable, the train was due to arrive in Slowleigh at 4.30.
I had been so interested in my book that I had a shock when I looked at my watch.
It was almost 4.30.
I closed my book and waited for the train to slow down.
It didn't.
In fact, the train was going very fast ----and that was Slowleigh, wasn't it?!
The train went straight on.
I asked the other passengers why the train hadn't stopped
	and they told me it was the express to the city.

I didn't believe it.
Then the ticket collector came along.
He looked at my ticket and I tried to explain,
	but in the end I had to pay the full fare to the city.
By the time we arrived in the city it was six o'clock.
The journey had lasted two hours and I was miles away from my original destination.
I rang my friends and said I would get a fast train back.
Then checked the timetable: there was no fast train back to Slowleigh,
	only a slow one, at 7 o'clock.
By the time I finally reached Slowleigh Station,
	it was nine o'clock at night.
My pleasant little train journey had taken 4.5 hours!

** Topics for discussion
