#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 03 Taking a shower
#+begin_verse
Dan pulls the shower curtain shut.
By turning the knob, he turns the water on.
He washes his hair with shampoo and the rest of his body with soap.
Then he rinses off with water.
After turning the water off, he steps out of the shower.
He takes a towel from the towel rack.
Then he dries himself off.
He wraps a towel around himself and he dries his hair.
He puts some deodorant under his arms.
#+end_verse

** expression
shampoo [ʃæmˈpuː]: a liquid soap for washing your hair洗发精
soap [səʊp]: the substance that you use to wash your body ⇨ detergent肥皂
deodorant [diˈoʊdərənt]: a chemical substance that you put on the skin under your arms to stop you from smelling bad ⇨ antiperspirant除臭剂
--------------------
pulls sth. shut: 关闭某物
turns sth. on/off: 打开/关闭某物
step out of sp.: 走出某地(bed/jail/line)
** sentence
shampoo [ʃæmˈpuː]: a liquid soap for washing your hair洗发精
- Our shampoo has been used up, we must go to buy one tonight.
- The shampoo is so useless that my head am still full of dandruff after using it.
- Dearling, we needn't have bought so much shampoo even though it was in promotion.
soap [səʊp]: the substance that you use to wash your body ⇨ detergent肥皂
- You must have forgetten to use soap while taking a shower.
- It is said that when you pick up your soap in the bathroom a gay may take an interest in your ass.
- You'd better not use my soap anymore, or I will call the police.
deodorant [diˈoʊdərənt]: a chemical substance that you put on the skin under your arms to stop you from smelling bad ⇨ antiperspirant除臭剂
- My aunt asked me to put some deodorant under my arms.
- I thought the deodorant is useless, so I threw it up in the rubbish bin.
- This kind of deodorant was soon admired by poor and rich alike.
--------------------
pulls sth. shut: 关闭某物
- If you don't other man see my body, you will pull the curtain shut.
- I pull the curtain shut with great care before sleeping.
- It seems that our cat has pulled the curtain shut in our bedroom.
turns sth. on/off: 打开/关闭某物
- When I was in kindergarden, one thing I expected everyday was to turn on TV and watch carton.
- Turning off the TV, I determined to pay all my attention to the course.
- Would you please help me turn on the TV? My aunt asked me in a weak voice.
step out of sp.: 走出某地(bed/jail/line)
- The movie is a story about how a innocent banker steps out of the jail in England.
- A woman stepped out of the line and shook my hands.
- My cat stepped out of the cardborad box and licked my hands.
** sentence2
shampoo [ʃæmˈpuː]: a liquid soap for washing your hair洗发精
- Our shampoo has been used up, we must go to buy one tonight.
- The shampoo is so useless that my head is still full of dandruff after using it.
- Dearling, we needn't have bought so much shampoo even though it was in promotion.
soap [səʊp]: the substance that you use to wash your body ⇨ detergent肥皂
- You must have forgotten to use soap while taking a shower.
- It is said that when you pick up your soap in the bathroom a gay may take an interest in your ass.
- You'd better not use my soap anymore, or I will call the police.
deodorant [diˈoʊdərənt]: a chemical substance that you put on the skin under your arms to stop you from smelling bad ⇨ antiperspirant除臭剂
- My aunt asked me to put some deodorant under my arms.
- I thought the deodorant was useless, so I threw it up in the rubbish bin.
- This kind of deodorant was soon admired by poor and rich alike.
-------------------
pulls sth. shut: 关闭某物
- If you don't want another man to see my body, you will pull the curtain shut.
- I pull the curtain shut with great care before sleeping.
- It seems that our cat has pulled the curtain shut in our bedroom.
turns sth. on/off: 打开/关闭某物
- When I was in kindergarten, one thing I expected every day was to turn on the TV and watch Carton.
- Turning off the TV, I determined to pay all my attention to the course.
- Would you please help me turn on the TV? My aunt asked me in a weak voice.
step out of sp.: 走出某地(bed/jail/line)
- The movie is a story about how an innocent banker steps out of jail in England.
- A woman stepped out of the line and shook my hands.
- My cat stepped out of the cardboard box and licked my hands.
