#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 5 No wrong numbers 
#+begin_verse
What does 'No wrong numbers' mean?

Mr. James Scott has a garage in Silbury
	and now he has just bought another garage in Pinhurst.
Pinhurst *is only five miles from* Silbury,
	but Mr. Scott cannot *get a telephone for his new garage*,
	so he has just bought twelve pigeons.
Yesterday, a pigeon carried the first message from Pinhurst to Silbury.
The bird *covered the distance in three minutes*.
*Up to now*, Mr. Scott has sent *a great many* requests for spare parts
	and other urgent messages from one garage to the other.
*In this way*, he has begun his own private telephone service.
#+end_verse
** expression
pigeon [ˈpɪdʒɪn] n.鸽子
message [ˈmesɪdʒ] n.信息
cover [ˈkʌvə(r)] v.越过
distance [ˈdɪstəns] n.距离
request [rɪˈkwest] n.要求,请求
spare [speə(r)] part [pɑːt] n.备件
service [ˈsɜːvɪs] n.业务,服务

leave sb. a message 给某人留了信息
customer service: 客户服务
cover the distance in st. 在一定时间内越过这个距离

--------------------
have done VS did: 用过去的事情说现在 VS 只说过去的事情

A is 5 miles from B
get sth. for sb.: 为某人取得某物
cover the distance in st.
a great many
send a request for sth.
up to now: 迄今
in this way


** 单词造句
pigeon n.
- I have received a pigeon from my wife, Lijie.
- Have you received a pen from your father?
- Who has received a pen from my father?
- When have you received a pen from your father?
- Why did you receive a pen from your father?
message n.
- I sent a message from JinXian to Xiabu.
- Did you send a message from Jinxian to Xiabu?
- Who sent a message from Jinxian to Xiabu?
- Why did you send a message from Jinxian to Xiabu?
- When did you send a message from Jinxian to Xiabu?
cover v.
- The airport covered the distance from NanChang to Hangzhou in an hour.
- Did the airport cover the distance from Nanchang to Hangzhou in an hour?
- How long did the airport cover the distance from Nanchang to Hangzhou?
- Where did the airport cover the distance in an hour?
- The pigeon covers the distance from the garage to another in ten minutes.
distance n.
-
-
-
-
-
request v.
- The beggar sent a request for a piece of cheese yesterday.
- Did the beggar send a request for a piece of cheese yesterday?
- When did the beggar send a request for a piece of cheese?
- What did the beggar send a request for?
- Why did the beggar send a request for a piece of cheese?
spare part
- I bought some spare parts for my car.
- Have you bought some spare parts for your car.
- Why do you buy some spare parts for your car?
- What do you buy some spare parts for?
- How did you buy some spare parts?
service n.
- We begin our service from 9 o'clock to 17 o'clock.
- Do you begin your service from 9 o'clock to 17 o'clock?
- Why do you begin your service from 9 o'clock to 17 o'clock?
- When do you begin your service?
- Where do you begin your service?
** 反复听电影片段
** Pattern Drill 写+读
-
		1T: the train left
		S1: Has the train left?
		S2: Yes, it's just left. It left a minute ago.
	 - John arrived
		 Has John arrived?
		 Yes, he's just arrived. He left a minute ago.
	 - the noise stopped
		 Has the noise stopped?
		 Yes, it's just stopped. It stopped a minute ago.
	 - the taxi came
		 Has the taxi come?
		 Yes, it's just come. It came a minute ago.
	 - the men returned
		 Has the men returned?
		 Yes, he's just returned. It returned a minute ago.
-
		2t: driven a Mercedes - last week
		s1: Have you ever driven a Mercedes?
		s2: Yes, I drove one last week.
	 - climbed a mountain - last year
		 Have you ever climbed a mountain?
		 Yes, I climbed one last year.
	 - won a prize - at school a year ago
		 Have you won a prize?
		 Yes, I won one at school a year ago.
	 - had an accident - in 1996
		 Have you had an accident?
		 Yes, I had one in 1996.
	 - read a Russian play - two years ago
		 Have you read a Russian play?
		 Yes, I read one two years ago.
-
		3t: go abroad
		s1: He's gone abroad.
		s2: Really? He went abroad last year too, didn't he?
	 - buy a new car
		 He's bought a new car.
		 Really? He bought a new car last year too, didn't he?
	 - paint his house
		 He's painted his house.
		 Really? He painted his house last year too, didn't he?
	 - sell some pigeons
		 He's sold some pigeons.
		 Really? He sold some pigeons last year too, didn't he?
	 - write a book
		 He's written a book.
		 Really? He wrote a book last year too, didn't he?
-
		4t: you - six months
		s1: How long have you been there?
		s2: I've been here for six months.
	 - she - a year
		 How long has she been there?
		 She's been here for a year.  
	 - he - two weeks
		 How long has he been there?
		 He's been here for two weeks.
	 - they - five months
		 How long have they been there?
		 They've been here for five months.
	 - John - ten minutes
		 How long has John been there?
		 He's been here for ten minutes.
** 给自己讲解
** 红皮书
** 习惯用法造句
A is 5 miles from B
- Up to now, the pigeon is 5 miles from here.
- Is the pigeon 5 miles from here up to now?
- Why is the pigeon 5 miles from here up to now?
- When is the pigeon 5 miles from here?
- Who is 5 miles from here up to now?
get sth. for sb.
- I get money for my wife every month.
- Do you get money for your wife every month?
- Why do you get money for your wife every month?
- How often do you get money for your wife?
- What do you get for your wife every month?
cover the distance in st.
-
-
-
-
-
a great many
- I had a great many pigeons at 7 years old.
- Did you have a great many pigeons at 7 years old?
- Why did you have a great many pigeons at 7 years old?
- When did you have a great many pigeons?
- Where did you buy a great many pigeons?
send a request for sth.
-
-
-
-
-
up to now
-
-
-
-
-
in this way
- I always get good grades in this way.
- Do you always get good grades in this way?
- Why do you always get good grades in this way?
- Who always gets good grades in this way?
- Where do you always get good grades in this way?
** 跟读至背诵
** Ask me if 写+读
1. James Scott has a garage in Silbury. Who
	 Who has a garage in Silbury?
2. He's just bought another garage. What
		What has he just bought?
3. His new one is in Pinhurst. Where
		Where is his new one?
4. Pinhurst is five miles from Silbury. How far
		How far is Pinhurst from Silbury?
5. He's just bought twelve pigeons. How many
		How many pigeons has he just bought?
6. They carry messages. What
	 What do they carry?
7. A pigeon carried the first message to Silbury yesterday. When/What
	 When did a pigeon carry the first message to Silbury yesterday?
	 What did a pigeon carry to Silbury yesterday?
8. It took three minutes. How long
	 How long did it take?
** 摘要写作
Mr. Scott has just bought another garage in Pinhurst,
	but he cannot get a telephone for his new garage,
	so he bought twelve pigeons.
The bird covers the distance in 3 minutes.
Up to now, Mr. Scott has sent a great many requests for spare parts
	and other urgent messages from one garage to the other.
In this way, he has begun his own private "telephone" service.
** tell the story 口语
** Topics for discussion
1. What do you have to do to get a telephone in your country?
2. Have you had any wrong numbers on the phone lately?
	 What else can go wrong when you use the phone?
3. What other ways of sending messages are there?
