#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 6 Percy Buttons 

#+begin_verse
Who is Percy Buttons?

I have just *moved to a house* in Bridge Street.
Yesterday a beggar *knocked at my door*.
He *asked me for a meal and a glass of beer*.
*In return for* this, the beggar *stood on his head* and sang songs.
I gave him a meal.
He ate the food and drank the beer.
Then he put a piece of cheese in his pocket and went away.
Later a neighbor told me about him.
Everybody knows him.
His name is Percy Buttons.
He *calls at* every house in the street *once a month*
	and always *asks for a meal and a glass of beer*.
#+end_verse
** expression
beggar [ˈbeɡə(r)] n.乞丐
food [fuːd] n.食物
pocket [ˈpɒkɪt] n.衣服口袋
call [kɔːl] v.拜访,光顾

pocket money 零花钱
call at = visit 拜访

--------------------
a/an VS the: 泛指 VS 特指
some VS any:
	1. 陈述句? 肯定some, 否定any
		 有任何的意思? any
	2. if从句? any
	3. 疑问句? 确认some, 不确认any

move to sw. 搬到某地
knock at the door 敲门
ask sb. for sth. 请求某人做某事
stand on sb's head 倒立
call at 拜访
in return for this: 作为对此的回报
once/twice a st.: 多久一/两次
ask for sth.: 请求某物


** 单词造句
beggar
- A dirty beggar asked me for some money yesterday.
- Did the dirty beggar ask you for some money yesterday?
- When did the beggar ask yo for some money?
- Why did the beggar ask you for some money?
- Where did the beggar ask you for some money?
food
- I have eaten some foods in the morning.
- Have you ever eaten any foods in the morning?
- Why haven't you eaten any foods in the morning?
- When have you eaten some foods?
- Where have you eaten some foods?
pocket
- I put a meat in my pocket.
- Did you put the meat in your pocket?
- Why did you put the meat in your pocket?
- When did you put the meat in your pocket?
- What happened to your pocket money?
call
- I called at my girlfriend once a week.
- Do you call at your girlfriend once a week?
- How often do you call at your girlfriend?
- Where do you call at your girlfriend?
- Why do you call at your girlfriend once a week?
** 反复听电影片段
** Pattern Drill 写+读
-
		s1: I need some ink
		s2: There's a bottle of ink in the desk.
	 - a bottle of milk - in the fridge
		 I need some milk.
		 There's a bottle of milk in the fridge.
	 - a pot of glue - in the cupboard
		 I need some glue.
		 There's a pot of glue in the cupboard.
	 - a bag of flour - on the table
		 I need some flour.
		 There's a bag of flour on the table.
	 - a can of oil - in the garage
		 I need some oil.
		 There's a can of oil in the garage.
-
		2T: tea
		s1: You drink a lot of tea, I must say!
		s2: I couldn't live without tea. It's my favourite drink.
	 - milk
		 You drink too much milk, I must say.
		 I couldn't live without milk, it's my favourite drink.
	 - water
		 You drink too much water, I must say.
		 I couldn't live without water, it's my favourite drink.
	 - coffee
		 You drink too much coffee, I must say.
		 I couldn't live without coffee, it's my favourite drink.
	 - Coca-Cola
		 You drink too much Coca-Cola, I must say.
		 I couldn't live without Coca-Cola, it's my favourite drink.
-
		3t: car - nice radio
		s1: I like that car. It has a nice radio.
		s2: I like the radio, but not the car!
	 - house - big garden
		 I like that house. It has a big garden.
		 I like the garden, but not the house.
	 - village - old church
		 I like that village. It has an old church.
		 I like the church, but not the village.
	 - room - fine view
		 I like that room. It has a fine view.
		 I like the view, but not the room.
	 - hotel - good restaurant
		 I like that hotel. It has a good restaurant.
		 I like that restaurant, but not the hotel.
-
		4t: a cup - over there
		s1: Give me a cup, will you?
		s2: The cup over there?
		s1: It doesn't matter - just give me a cup?
	 - a vase/plate - near the window
		 Give me a plate, will you?
		 The plate near the window?
		 It doesn't matter - just give me a plate.
	 - a tin of meat - on the shelf
		 Give me a tin of meat, will you?
		 The tin of meat on the shelf?
		 It doesn't matter - just give me a tin of meat.
	 - an umbrella - in the bedroom
		 Give me an umbrella, will you?
		 The umbrella in the bedroom.
		 It doesn't matter - just give me an umbrella.
	 - a comb - in the bathroom
		 Give me a comb, will you?
		 The comb in the bathroom.
		 It doesn't matter - just give me a comb.
** 给自己讲解
** 红皮书
** 习惯用法造句
move to sw.
- I have moved to a house in SanTang 3 months ago.
- Have you moved to the house in Santang?
- When have you moved to the house in Santang?
- Where have you moved?
- Why did you move to a house in Santang?
knock at the door
- The cat knocked at the door.
- Did the cat knock at the door?
- Why did the cat knock at the door?
- What knocked at the door?
- When did the cat knock at the door?
ask sb. for sth.
- Don't give him money, he has asked me for it.
- Has he asked you for some money?
- Why has he asked you for some money?
- What has he asked you for?
- Where has he asked you for some money?
stand on sb's head
- Miumiu is standing on her hand and playing it.
- Is Miumiu standing on her head?
- Why is Miumiu standing on her head?
- Where is Miumiu standing on her head?
- How does Miumiu stand on her head?
call at
-
-
-
-
-
in return for this
- In return for this, I knocked at the door.
- What did you do in return for this?
- Did you knock at the door in return for this?
- Why did you knock at the door in return for this?
- When did you knock at the door in return for this?
once a st.
- I wash the clothes once a week.
- Do you wash the clothes once a week?
- Why do you wash the clothes once a week?
- How often do you wash the clothes?
- Who washes the clothes once a week?
ask for sth.
-
-
-
-
-
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
I have just moved to an house in Bridge Street.
Yesterday a beggar knocked at my door, it asked me for a meat and a glass of beer.
In return for this, he stood on his head and sung songs.
He drank the beer and ate the food.
Later a neighbor told me about him.
He is Percy Button.
He calls at every house once a month
	and always asks for a meat and a glass of beer.
** tell the story 口语
** Topics for discussion
1. Do you think this story is true? Why/Why not?
2. How did people pay for things long ago, before we had money?
3. Imagine you are very hungry, but have no money for a meal. What would you do?
