#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 8 The best and the worst 

#+begin_verse
Why is Joe's garden the most beautiful one in the town?

Joe Sanders has the most beautiful garden in our town.
Nearly everybody *enters for* 'The Nicest Garden Competition' each year,
	but Joe wins every time.
Bill Frith's garden is larger than Joe's.
Bill works harder than Joe and grows more flowers and vegetables,
	but Joe's garden is more interesting.
He has *made neat paths* and has built a wooden bridge over a pool.
I like gardens too, but I do not like hard work.
Every year I *enter for* the garden competition too,
	and I always *win a little prize* for the worst garden in the town!
#+end_verse
** expression
competition [ˌkɒmpəˈtɪʃ(ə)n] n.比赛
neat [niːt] adj. 整齐的,整洁的
path [pɑːθ] n.路径
wooden [ˈwʊdn] adj.木头的
pool [puːl] n.水池

enter the competition 参加比赛
make a path 开辟路径
That's neat 这是整洁的

--------------------
adj. 比较级&最高级变化规则
	1. 单音节:+er/est
		 - 元+辅音字母结尾: 需双写辅音字母 big -> bigger
	2. 双音节:
		 - 辅音+y结尾: y变成i pretty -> prettier
	3. 多音节: + more/less, most/least
	4. 不规则:good/well~bad~much~little
比较状从:
	1. 主语 + be + the + adj.est + n. + I've ever met/seen
	2. 主语 + be + the + adj.est + n. + 范围
	3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)

enter for: 参加
make a path 开辟路径
build a bridge 建桥
win a prize 赢得奖品


** 单词造句
competition n.
- I entered for the competition yesterday.
- Did you enter for the competition yesterday?
- When did you enter for the competition?
- Why did you enter for the competition yesterday?
- Who entered for the competition yesterday?
neat
- He makes neat paths every year.
- He made neat paths last year.
- He has just made neat paths last year.
- He is making neat paths.
- While he was making neat paths, I was playing games.
path
-
-
-
-
-
wooden
- The beggar stood on the wooden desk yesterday.
- Did the biggar stand on the wooden desk yesterday?
- Why did the biggar stand on the wooden desk yesterday?
- When did the biggar stand on the wooden desk?
- Who stood on the wooden desk yesterday?
pool
- I swam in the swimming pool last weekend?
- Did you swim in the swimming pool last weekend?
- Why did you swim in the swimming pool last weekend?
- When did you swim in the swimming pool?
- I built a wooden bridge over the swimming pool.
  	 
** 反复听电影片段
** Pattern Drill 写+读
-
		 1t: Joe and Bill have large gardens. 
		 s1: But Joe's garden is larger than Bill's.
		 s2: No, Bill's is larger than Joe's.
	 - Joe and Bill have fast cars.
		 But Joe's cars are faster than Bill's.
		 No, Bill's are faster than Joe's.
	 - Jane and Mary have long hair
		 But Jane's hair is longer than Mary's.
		 No, Mary's is longer than Jane's.
	 - Tom and Jane have small flats
		 But Tom's flats are smaller than Jane's.
		 No, Jane's are smaller than Tom's.
	 - Joe and Bill have good watches
		 But Joe's watches are better than Bill's.
		 No, Bill's are better than Joe's.
-
	   t2: ripe orange  riper
		 s1: Which orange do you like?
		 s2: I like the riper one.
	 - soft carpet  softer
		 Which carpet do you like?
		 I like the softer one.
	 - pale color  paler
		 Which color do you like?
		 I like the paler one.
	 - thick coat  more thick
		 Which coat do you like?
		 I like the more thick one.
	 - hard mattress  harder
		 Which mattress do you like?
		 I like the harder one.
-
	   t3: interesting presents
		 s1: I've got more presents than you have.
		 s2: Well, mine are more interesting than yours.
	 - long letters
		 I've got more lotters than you have.
		 Well, mine are longer than yours.
	 - pretty dresses
		 I've got more dresses than you have.
		 Well, mine are prettier than yours.
	 - useful books
		 I've got more books than you have.
		 Well, mine are more useful than yours.
	 - talented children
		 I've got more children than you have.
		 Well, mine are more talented than yours.
-
		 t4: a hard worker
		 s1: Mary's a very hard worker.
		 s2: Yes, she's the hardest worker I've ever met.
	 - a quick writer
		 Mary's a very quick writer.
		 Yes, she's the most qucik writer I've ever met.
	 - a careful driver
		 Mary's a very careful driver.
		 Yes, she's the most careful driver I've ever met.
	 - a pretty girl
		 Mary's a very pretty girl.
		 Yes, she's the prettiest girl I've ever seen.
	 - a fast reader
		 Mary's a very fast reader.
		 Yes, she's the fastest reader I've ever known.
	 
** 给自己讲解
** 红皮书
** 习惯用法造句
enter for
- I'm going to enter for the competition.
- Are you going to enter for the competition?
- When did you enter for the competition?
- In return for this, I entered for the competition.
- Where did you enter for the competition?
make a path
- He made a wooden path for his wife.
- Did he make a wooden path?
- Why did he make a wooden path over the river?
- When did he make a wooden path?
- How did he make a wooden path?
build a bridge
- The firm built the bridge over ChangJiang.
- Did the firm build the bridge over ChangJiang?
- Why did the firm build the bridge over ChangJiang?
- How did the firm build the bridge over ChangJiang?
- When did the firm build the bridge over ChangJiang?
win a prize
- Gao wins a prize for the maximal grades in the class.
- Does Gao win a prize for the maximal grades?
- Where does Gao win a prize?
- Why does Gao win a prize?
- How does Gao win a prize for the maximal grades?
	 
** 跟读至背诵
** Ask me if 写+读
1. Who has the most beautiful garden in our town?
2. There is a garden competition every year.
		How often is there a garden competition?
		Where is a garden competition every year?
		What kind of competition is there every year?
3. Joe wins every time.
		Who wins every time?
		How often does Joe win?
4. Bill Frith's garden is bigger than Joe's.
		Whose garden is bigger than Joe's?
		How big is Bill Frith's garden?
5. He works hard than Joe.
		How hard does he work?
6. Joe's garden is more interesting.
	 Whose garden is more interesting?
7. He has made neat paths. What
	 What has he made?
	 
** 摘要写作
Joe Sander has the best garden in our town.
He wins the best garden competition each year.
Bill Frith has a fine garden too.
But Joe's garden is better than Bill's.
The writer's garden is terrible, and he always win a little prize for the worst competition.

** tell the story 口语
** Topics for discussion
1. Describe the most beautiful garden or park you've seen, and say why you liked it.
2. Are there a lot of parks and gardens in the towns in your country? Why/Why not?
3. Do you think competitions are a good idea? Why/why not?
