#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 13 The Greenwood Boys  

#+begin_verse
Why will the police have a difficult time?

The Greenwood Boys are *a group of* pop singer.
*At present*, they are visiting *all parts of the country*.
They will be arriving here tomorrow.
They will be coming by train
	and most of the young people in the town will be meeting them at the station.
Tomorrow evening they will be singing at the Workers' Club.
The Greenwood Boys will be staying for five days.
During this time, they will *give five performances*.
*As usual*, the police will *have a difficult time*.
They will be trying to *keep order*.
It is always the same *on these occasions*.  
#+end_verse
** expression
group [ɡruːp] n.小组,团体
pop [pɒp] singer [ˈsɪŋə(r)] n.流行歌手
club [klʌb] n.俱乐部
performance [pəˈfɔːməns] n.演出
occasion [əˈkeɪʒ(ə)n] n.场合

a group of 一组，一群
pop music/song/star 流行音乐/歌曲/明星
give a performance 进行一次演出
on this occasion 在这个场合

--------------------
will be doing: 1.未来动作正在进行;2.计划

a group of
at present 目前，现在
all parts of the country 全国各地
as usual 按照通常的方式或习惯
have a difficult time 遇到困难
give five performance 五项表演
keep order 维持秩序
on these occasions 在这种场合


** 单词造句
group
- A group of detectives is keeping guard at the airport.
- A group of pop singer is visiting all parts of the country.
- A group of waiters fly to Beijing.
- A group of pigeons covered the distance in two minutes time.
- A group of visitors has gathered in front of the museum.
club
- She refuses to go to the night club with him.
- He asks her to go to the night club.
- The night club was been damaged by the young people.
- Do you join the tennis club?
- She has joined the tennis club.
pop singer
- The pop singer will be arriving here tomorrow.
- The pop singer will be coming by the train.
- They will be meeting the pop singer at the station.
- The pop singer will give a performance tomorrow evening.
- The pop singer is knocking at the door.
performance
- The famous star gave a performance yesterday.
- Did the star give a performance yesterday?
- Why did the star give a performance yesterday?
- When did the star give a performance?
- The star was giving a performance when the police arrived on the scene.
occasion
- I take out the trash occasionaly.
- On these occasions, I always get very happy.
- On these occasions, I usually have a difficult time.
- On these occasions, he always asks for a meat and a glass of beer.
- On these occasions, the lawyers always keeps guard at the door.
** 反复听电影片段
** Pattern Drill 写+读
-
		1t:next year - talking my final exams
		s1:What will you be doing this time next year?
		s2:I'll be taking my final exams.
	 - next month - studying for my exams
		What will you be doing this time next month?
		I'll be studying for my exams.
	 - next month - working for my exams
		What will you be doing this time next month?
		I'll be working for my exams.
	 - next week - lying on the sand
		What will you be doing this time next week?
		I'll be lying on the sand.
	 - next year - starting a job
		 What will you be doing this time next year?
		 I'll be starting a job.
-
		2t:it's raining.
		s1:It's raining again.
		s2:I hope it won't still be raining tomorrow.
	 - she's crying
		She's crying again.
		I hope she won't still be crying tomorrow.
	 - they're drilling on the read
		They're drilling on the road again.
		I hope they won't still be drilling on the road tomorrow.
	 - It's snowing
		It's snowing again.
		I hope it won't still be snowing tomorrow.
	 - he's feeling ill
		He's feeling ill again.
		I hope he won't still be feeling ill tomorrow.
-
		3t:go to the station
		s1:I shall go to the station tomorrow.
		s2:I'll be seeing you then. I'll be going there too.
	 - go to the bank
		I shall go to the bank tomorrow.
		I'll be seeing you then. I'll be going there too.
	 - ride in the park
		I shall ride in the park tomorrow.
		I'll be seeing you then. I'll be riding there too.
	 - read in the library
		I shall read in the library tomorrow.
		I'll be seeing you then. I'll be reading there too.
	 - shop at Smith's
		I shall shop at Smith's tomorrow.
		I'll be seeing you then. I'll be shopping there too.
4.
	 4t:invitations to write
	 s1:What a lot of invitations to write.
	 s2:I'm afraid so. We'll probably be writing them all day.
	 - food to cook
		What a lot of food to cook.
		I'm afraid so. We'll probably be cooking it all day.
	 - work to do
		What a lot of work to do.
		I'm afraid so. We'll probably be doing it all day.
	 - papers to read
		What a lot of papers to read.
		I'm afraid so. We'll probably be reading them all day.
	 - clothes to wash
		What a lot of clothes to wash.
		I'm afraid so. We'll probably be washing them all day.

** 给自己讲解
** 红皮书
** 习惯用法造句
a group of
-
-
-
-
-
at present
- At present, he is doing his homework.
- At present, he is refusing to join the night club.
- At present, he is talking to his wife rudely.
- At present, the police is keeping order.
- At present, they're meeting a group of pop singer.
all parts of the country
- A fewer days earlier, they visited all parts of Beijing.
- The pop singer has visited all parts of our country.
- Did they visit all parts of the country?
- Why did they visit all parts of the country?
- How did they visit all parts of the country?
as usual
- As usual, they will take out the trash.
- As usual, she will play the clavichord.
- As usual, it will be damaged.
- As usual, it will be repaired.
- As usual, the school will be built.
have a difficult time
- I had a difficult time last year.
- I'm having a difficult time, but it'll pass.
- She was laughing at me when I had a difficult time.
- I hope he won't be having a difficult time.
- They will have a difficult time, they will be trying to keep order.
give five performance
-
-
-
-
-
keep order
- They'll be trying to keep order.
- Will they be trying to keep order?
- How do a crowd of people keep order?
- Why do a crowd of people keep order?
- At present, he is keeping order.
on these occassions
- On these occassions, I always get very angry.
- On these occassions, it's the same.
- On these occassions, he reads his book.
- On these occassions, he always asks for a meat.
- On these occassions, the night club is always open.
** 跟读至背诵
** Ask me if 写+读
1. The Greenwood Boys are a group of pop singers.
	 Who are the Greenwood Boys?
2. They are visiting all parts of the country at present.
		Which parts of the country are they visiting at present?
		When are they visiting all parts of the country?
3. They'll be arriving here tomorrow.
		When will they be arriving here?
4. They'll be coming by train.
		How will they be coming?
5. Most of the young people in the town will be meeting them.
		Who will most of the young people in the town be meeting?
		How many of the young people in the town will be meeting them?
6. They'll be waiting at the station.
	 Where will they be waiting?
7. The Greenwood Boys will be staying for five days.
	 How long will the Greenwood Boys be staying?
	 Where will the Greenwood Boys be staying for five days?
8. They will give five performances.
	 How many performances will they give?
	 Where will they give five performances?
	 Who will give five performances?
9. They'll be singing at the workers' club tomorrow.
	 Where will they be singing?
	 When will they be singing at the workers' club.
** 摘要写作
The Greenwood Boys are pop singers.
They will be arriving here tomorrow.
Most of the young people in the town will be meeting them at the station.
They will give five performances in five days.
As usual, police will be trying to keep order.
** tell the story 口语
** Topics for discussion
1. Describe a concert you have been to, or heard about.
2. What do you think you'll be doing this time next year?
3. Do you prefer pop or classical songs/singers? why?
