#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 14 Do you speak English?

#+begin_verse
Did the young man speak English?

I *had an amusing experience* last year.
After I had left a small village in the south of France, I *drove on* the next town.
*On the way*, a young man *waved to me*.
I stopped and he *asked me for a lift*.
As soon as he had got into the car,
	I said good morning to him *in French* and he replied in the same language.
*Apart from* a few words, I do not know any French at all.
Neither of us spoke during the journey.
I had nearly reached the town,
	when the young man suddenly said, very slowly,
		'Do you speak English?'
As I soon learnt, he was English himself!
#+end_verse
** expression
amusing [əˈmjuːzɪŋ] adj.好笑的,有趣的
experience [ɪkˈspɪəriəns] n.经历
wave [weɪv] v.招手
lift [lɪft] n.搭便车
reply [rɪˈplaɪ] v.回答
language [ˈlæŋɡwɪdʒ] n.语言
journey [ˈdʒɜːni] n.旅行

have an amusing experience 有一次有趣的经历
wave to sb. 向某人招手
take a lift/ ask for a lift 搭车/要求搭车
A give B a lift 让某人搭便车
reply to the email/letter 回复邮件/信件
go on a journey 进行一次旅行

--------------------
had + done: 1.过去的过去;2.过去A发生,对于过去B产生影响(A在B前);3.动作从过去A持续(重复)到过去B

drive on to sw. 继续开车到某地
on the way 在路上
ask sb. for a lift 问某人搭便车
apart from 除了...之外
in French 用法语


** 单词造句
amusing
- I find it amusing.
- She took part in an amusing car race last year.
- I'll be taking part in  an amusing car race next year.
- I entered for an amusing competition.
- Will you be taking part in the amusing car race tomorrow?
experience
- I had an amusing experience last year.
- I had an amusing experience after I had visited the Shanghai Disneyland.
- Did you have an amusing experience last year?
- When did you have an amusing experience?
- Where did you have an amusing experience last year?
wave
- Look, she's waving to you. Do you know her?
- Why is she waving to me. I don't know her.
- As soon as he had waved to me, I stopped.
- Why didn't the taxi stop after I had waved to it?
- Leo is waving to us when I open the video?
lift  hitchhike
- I took a lift on the way.
- She asked me for a lift.
- I wouldn't take a lift from a strange woman.
- You couldn't take a lift from a strange man in China.
- My boss gave me a lift yesterday.
reply
- The girl replied to her boyfriend's letter immediately.
- She always replys to the email after three days.
- Don't worry about it. I have replied to his letter.
- I'll be replying to his letter tomorrow?
- When will you be replying to his letter?
language
- What is your native language?
- My native language is Chinese.
- Is your native language Chinese?
- Why is your native language Chinese?
- He is English himself whose native language is English.
journey
- I will be going on a journey next week.
- I went on an amusing journey yesterday.
- We are going on an amusing journey tomorrow.
- When will you be going on a journey?
- How will you be going on a journey?
** 反复听电影片段
** Pattern Drill 写+读
-
		1t:angry - prepare lunch for him
		s1:Why was he so angry?
		s2:I hadn't prepared lunch for him.
	 - upset - give Mary his letter
		Why was she so upset?
		I hadn't given Mary his letter.
	 - annoyed - post his letters
		Why was he so annoyed?
		I hadn't posted his letters.
	 - pleased - reported him to the headmaster
		Why was he so pleased?
		I hadn't reported him to the headmaster.
	 - surprised - repair his bicycle
		Why was he so surprised?
		I hadn't repaired his bicycle.
-
		2t:see the film properly - my glasses
		s1:Why couldn't you see the film properly?
		s2:I hadn't taken my glasses with me.
	 - find his house - a map
		Why couldn't you find his house?
		I hadn't taken a map with me.
	 - see the show - any money
		Why couldn't you see the show?
		I hadn't taken any money with me.
	 - open the door - a key
		Why couldn't you open the door?
		I hadn't taken a key with me.
	 - sign the letter - a pen
		Why couldn't you sign the letter?
		I hadn't taken a pen with me.
-
		3t:tidy the garage - done
		s1:Why didn't John tidy the garage yesterday?
		s2:Because he'd already done it.
	 - listen to the play - heard
		Why didn't John listen to the plan yesterday?
		Because he'd already heard it.
	 - try the new restaurant - tried
		Why didn't John try the new restaurant yesterday?
		Because he'd already tried it.
	 - go to the film - seen
		Why didn't John go to the film  yesterday?
		Because he'd already seen it.
	 - look at these pictures - seen
		Why didn't John look at these pictures yesterday?
		Because he'd already seen it.
4.
	 4t:burn the letter
	 s1:Did you really burn the letter?
	 s2:It was a mistake. I realized it as soon as I'd burnt it.
	 - ring the police
		Did you really ring the police?
		It was a mistake. I realized it as soon as I'd rang it.
	 - let out the dogs
		Did you really let out the dogs?
		It was a mistake. I realized it as soon as I'd let them.
	 - tear up the notice
		Did you really tear up the notice?
		It was a mistake. I realized it as soon as I'd torn it.
	 - spend all your money
		Did you really spend all your money?
		It was a mistake. I realized it as soon as I'd spent it.
		
** 给自己讲解
** 红皮书
** 习惯用法造句
drive on to sw.
- Drive on, we don't have time to stop.
- After that, we drove on to Beijing.
- To my surprise, she drove on to the next town.
- We'll drive on to the street in twenty minutes' time.
- We drove on to Beijing on the last day of the year.
on the way
- We'll have plenty of time and we can talk about it on the way home.
- We'll have plenty of time on the way there.
- On the way, a young woman waved to me.
- Why did the young wave to me on the way?
- I'm speaking English on the way home.
ask sb. for a lift/ ask for a lift/ give sb. a lift
-
-
-
-
-
in French
- I'll try to say that in French.
- What do you say "I'll be away for two weeks" in Chinese?
- I say "good morning" to in English.
- It's written in French, so that I can't speak it.
- We began to speak in French.
apart from
- Apart from this watch, they are all made in China.
- Apart from a few words, I don't know any English at all.
- Apart from this prize, these are all won by John.
- Apart from this race, he takes part in all important competition.
- Apart from me, they succeeded in asking for a lift.
** 跟读至背诵
** Ask me if 写+读
1. I had an amusing experience last year.
	 When did you have an amusing experience?
	 Who had an amusing experience?
2. I was in the south of France.
	 Where were you?
3. I had left a small village.
	 What kind of village had you left?
4. A young man waved to me.
	 Who did a young man wave to?
	 Why did a young man wave to you?
5. He asked me for a lift.
	 What did he ask me for?
6. I said good morning to him.
	 What did I say to him?
7. I spoke in French.
	 What language did you speak in?
8. I know a few words of French.
	 How much French do you know?
9. He replied in French.
	 What language did he reply?
10. The young man spoke at the end of the journey.
		When did the young man speak?
		Who spoke at the end of the journey?
** 摘要写作
** tell the story 口语
** Topics for discussion
1. Have you ever asked for a lift, or given one? If so, describe the person you met.
2. Describe the various ways you are able to recognize a foreigner in your country.
3. Have you ever tried to talk to someone who didn't know your language? What happened?
