#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 15 Good news
#+begin_verse
What was the good news?

The secretary told me that Mr. Harmsworth would see me.
I felt very nervous when I went into his office.
He did not look up from his desk when I entered.
After I had sat down, he said that business was very bad.
He told me that the firm could not *afford to pay* such large salaries.
Twenty people had already left.
I knew that *my turn had come*.
'Mr. Harmsworth,' I said *in a weak voice*.
'Don't interrupt', he said.
Then he smiled and told me I would receive an extra thousand pounds a year!
#+end_verse
** expression
secretary [ˈsekrət(ə)ri] n.秘书
nervous [ˈnɜːvəs] adj.精神紧张的
afford [əˈfɔːd] v.负担得起
weak [wiːk] adj.弱的
interrupt [ˌɪntəˈrʌpt] v.插话,打断

be nervous about sth. / doing sth. 对某事/做某事紧张
afford sth. 负担某物
Sorry to interrupt, but... 很抱歉打断, 但是...

--------------------
宾语从句: 句子做宾语
直接引语变间接引语: 时态倒退一个时态,现在->过去,过去->过去完成;客观事实仍成立可不退

look up 抬头看
afford to pay 负担得起支付
my turn had come 轮到我了
in a weak voice 用微弱的声音


** 单词造句
secretary
- As soon as the secretary had entered the room, the boss waved to her.
- After the secretary had got off the car, she drove on to the next meeting.
- Before the secretary tried to pay for her dinner, he had already done that.
- While the secretary was keeping guard at the door, I opened the parcel.
- The secretary was not allowed to touch the clavichord.
nervous adj.
- Take it easy, I find you nervous.
- I'm not nervous about the exam at all.
- She is nervous about asking for a lift.
- I am nervous about working with beautiful girls.
- I felt very nervous, when I went into the office.
afford v.
- The house is too expensive for me to afford it.
- Can we afford that?
- We can't afford to pay that right now.
- The firm can't afford to pay such large salaries.
- He gets a good salary, but he still can't afford to pay such an expensive car.
weak adj.
- You're not weak, you're so strong.
- I feel weak. I think I must catch a cold.
- 'Give me a hand.' She said in a weak voice.
- A weak beggar is nervous about asking me for a meat.
- A weak beggar is standing on his head.
interrupt v.
- I'm replying a letter, don't interrupt me please.
- Sorry to interrupt, but is it your handbag?
- Sorry to interrupt, but my wife will meet me in 5 minutes' time.
- Sorry to interrupt, but smoking is not allowed there.
- Sorry to interrupt, but can I open the window?
extra adj.
- I could use some extra sleep.
- I could use some extra time.
- I could use some extra money.
- I could use some extra hand.
- I could use some extra help.
** 反复听电影片段
** Pattern Drill 写+读 see notebooks
** 给自己讲解
** 红皮书
** 习惯用法造句 none
afford to pay
my turn had come
in a weak voice
** 跟读至背诵
** Ask me if 写+读
1. Mr. Harmworth is my employer.
	 Who is your employer?
2. His secretary told me that he would see me.
	 What did his secretary tell you?
	 Who did his secretary tell you that would see you?
3. I went into his office. Where
	 Where did I go?
4. I felt very nervous.
	 How did I feel?
	 Why did I feel very nervous.
5. The firm couldn't afford to pay such large salaries.
	 What couldn't the firm afford to pay?
	 Why couldn't the firm afford to pay such large salaries?
6. Twenty people had left.
	 How many people had left?
7. I thought he would tell me to leave too.
	 What did you think he would tell you?
8. He told me not to interrupt.
	 What did he tell you not to do?
** 摘要写作
** tell the story 口语
Mr. Harmworth wanted to see me.
I felt very nervous about this, when I went into his office.
He said that business was very bad, the firm couldn't pay such large salaries.
Twenty people had left, but he didn't ask me to leave as well.
He offered me an extra thousand pounds a year.
** Topics for discussion
Describe an interview you have had.
Have you ever felt nervous? What makes you nervous?
What would you do with an extra $1,000 a year?
