* L20 One man in a boat
** articles
catch kætʃ v.
fisherman ˈfɪʃəmən n.  
boot buːt n.
waste weɪst n.
realize ˈriːəlaɪz v.

Fishing is my favourite sport. I often fish for hours without catching
anything. But this does not worry me. Some fishermen are unlucky.
Instead of cathing fish, they catch old boots and rubbish. I am even
less lucky. I never catch anything -- not even old boots. After having
spent whole mornings on the river, I always go home with an empty
bag. 'You must give up fishing!' my friends say. 'It's a waste of
time. 'But they don't realize one important thing. I'm not really
interested in fishing. I am only interested in sitting in a boat and
doing nothing at all.

without catching anything->fishermen catch old boots and rubbish->never catch anything  
->spent whole mornings, go home with an empty bag -> my friends say -> I'm interested in
sitting in a boat and doing nothing at all

** summary writing
   Fishing is my favourite sport.
   Some unlucky fishermen catch old boots and rubbish.
   I'm not so lucky as they are.
   He ever catch anything.
   He is not really interested in fishing.
   Sitting in a boat and doing nothing at all is the only thing that interests him.

** Topics for discussion
   1. What is your favourite pastime?
      Learning English, coding and playing chess is my favouriter pastime.
   2. Do you think the writer is wasting his time? Why/Why not?
      No, I don't.
      It's a way of life. Insteading of fishing, doing works is a waste of life.
   3. Do you think the writer would like to work as a fisherman? Would you? Why/Why not?
      No, I don't. I wouldn't.  
      It must be terrible to get up very early in the morning.

      
