* L22 A glass envelope [藞env蓹l蓹蕣p]
  dream dri藧m v.
  age e瑟d蕭 n.
  channel 藞t蕛忙nl n. 娴峰场
  throw 胃r蓹蕣 v.

** article
   My daughter, Jane, never dreamed of receving a letter from a girl
   of her own age in Holland. Last year, we were travelling across the
   Channel and Jane put a piece of paper with her name and address
   on it into a bottle. She threw the bottle into the sea. She never thought
   of it again, but ten months later, she received a letter from a girl in
   Holland. Both girls write to each other regularly now. However,
   they have decided to use the post office. Letters will cost a little
   more, but they will certainly travel faster.
   
** Topics for discussions
   1. Imagine a situation when it might be necessary to send a message in a bottle.

      Dirifting to a desert island.  
      Losting at sea like PI.  
      Sailing across the Atlantic.


   2. Students in England often work for the post office during the Christmas holidays.
      What sorts of jobs do students in your country do during their vacations?

      Be a worker in the factory.  
      Be a waiter in a restraurant.
      Be a teacher in a student's house.
      


