#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 23 A new house

#+begin_verse
Why is the new house special?

I *had a letter from my sister* yesterday.
She lives in Nigeria.
In her letter, she said that she would come to England next year.
If she comes, she will *get a surprise*.
We are now living in a beautiful new house in the country.
Work on it had begun before my sister left.
The house was completed five months ago.
In my letter, I told her that she could stay with us.
The house has many large rooms
	and there is a lovely garden.
It is a very modern house,
	so it looks strange to some people.
It must be the only modern house in the district.
#+end_verse
** expression
complete [kəmˈpliːt] v.完成
modern [ˈmɒd(ə)n] adj.新式的,与以往不同的
strange [streɪndʒ] adj.奇怪的
district [ˈdɪstrɪkt] n.地区

You complete me. 你完成了我
have a letter from sb. 收到某人的信
get a surprise 得到个惊喜


** 单词造句
complete [kəmˈpliːt] v.完成
- The modern station will be completed next year.
- The modern station must have been completed last year.
- When will the station be completed?
- Who will complete the station next year?
- Why will the station be completed next year?
modern [ˈmɒd(ə)n] adj.新式的,与以往不同的
- Instead of catching fish, they catch a modern chair.
- The man moved to the modern house yesterday.
- This house looks modern to me.
- I think about the modern chair every day.
- The modern bridge was built by the man in 1887.
strange [streɪndʒ] adj.奇怪的
- The picture looks strange to me.
- Doesn't the picture look strange?
- It must be terrible to ask a stranger for a lift.
- Why does the picture look strange?
- The stranger asked me for a meal and a glass of bear.
district [ˈdɪstrɪkt] n.地区
- I have lived in Jinxian district for 7 years.
- Did you live in Jinxian district?
- Why have you lived in Jinxian district for 7 years?
- How long did you live in Jinxian district?
- When did you live in Jinxian?
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
You complete me. 你完成了我
- 
- 
- 
- 
- 
have a letter from sb. 收到某人的信
- I had a letter from my father last week.
- Did you receive a letter from your father just then?
- What did you receive from your father?
- Who did you receive a letter from?
- Who received a letter from your father?
get a surprise 得到个惊喜
- I got a surprise from my girlfriend last birthday.
- You will get a surprise when you go to the theater.
- I got a surprise when I know that these tickets are for the next Wednesday performances.
- You will get a surprise when you find it yummy.
- You will get a surprise when you're taught a lesson.
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
What do you do to welcome a visitor to your home?
Would you rather live in an old house or a modern house? Why?
Imagine you are coming home after living abroad for some time. What would you want to do?
