* L26 The best art critics [ˈkrɪtɪk]
Who is the student's best critic?
I am an art student and I paint a lot of pictures. Many people
pretend that they understand modern art. They always tell you what
a picture is 'about'. Of course, many pictures are not 'about' anything.
They are just pretty patterns. We like them in the same way that we
like pretty curtain material. I think that young children
often appreciate [əˈpriːʃieɪt] modern pictures better than anyone else.
They notice more. My sister is only seven, but she always tells me
whether my pictures are good or not. She came into my room
yesterday.
'What are you doing?' she asked.
'I'm hanging this picture on the wall,' I answered. 'It's a new one. Do you like it?'
She looked at it critically for a moment. 'It's all right,' she said, 'but isn't it upside down?'
I looked at it again.She was right! It was!

Art student - paint - pictures
pretend - understand - art
tell - about - anything
patterns - the same way - curtain material
young children - appreciate - better
my sister - seven - good or not
came - my room - yesterday
hanging - new one - like
critically - a moment - upside down
again - right - was

* words
art [ɑːt] n.
critic [ˈkrɪtɪk] n.
paint [peɪnt] v.
pretend [prɪˈtend] v.
pattern [ˈpæt(ə)n] n.
curtain [ˈkɜːt(ə)n] n. 窗帘,幕布
material [məˈtɪəriəl] n.
appreciate [əˈpriːʃieɪt] v.
notice [ˈnəʊtɪs] v
wheather [ˈweðə(r)] conj.
hang [hæŋ] v.
critically [ˈkrɪtɪkli] adv
upside [ˈʌpsaɪd] down [daʊn]

* Grammar
We like them in the same way that we like pretty curtain material.
tell you what a picture is 'about'
whether my pictures are good or not

* Summary Writing
The writer studies art, and he paints a lot of pictures.
Many people do not really understand modern art.
Paintings do not always have a meaning.
They are sometimes pretty patterns.
Young children not only appreciate modern paintings better than anyone else,
  but notice more as well.
The writer's young sister went into his room yesterday, and she examined his new picture.
He had hung it upside down, and she noticed this immediately.

* Topics for discussions
1. How is your room at home decorated? What do you have on your walls?
   By hanging pictures. Some program pictures and some hangers. 

2. Name some 'modern' painters. Explain why you like or dislike their work.
   Sorry, I don't know anyone.
   I neither understand art nor like art. It's a waste of time for me to appreciate paints.

3. Do you think artists should try to 'please' other people? Why/Why not?
   Yes, I do.
   It's necessary to please other people for a living.

