* L27 A wet night
Late in the afternoon, the boys put up their tent in the middle of a field.
As soon as this was done, they cooked a meal over an open fire.
They were all hungry and the food smelled good.
After a wonderful meal, they told stories and sang songs by the campfire.
But some time later it began to rain.
The boys felt tired so they put out the fire and crept into their tent.
Their sleeping bags were warm and comfortable, so they all slept soundly.
In the middle of the night, two boys woke up and began shouting. The tent was full of water!
They all leapt out of their sleeping bags and hurried outside.
It was raining heavily and they found that a stream had formed in the field.
The stream wound its way across the field and then flowed right under their tent.

late - put - tent
cooked - meal - open fire
hungry - smell - good
stories - songs - campfire
rain
tired - crept - sleeping bag
warm - soundly
middle of the night - woke up - shouting
full of water
leapt - hurry - outside
heavily - stream - formed
wound - flow right - under tent

** words
tent [tent] n. 帐篷
field [fiːld] n. 田地
smell [smel] v. 闻起来
wonderful [ˈwʌndəf(ə)l] adj. 极好的
campfire [ˈkæmpfaɪə(r)] n. 营火
creep [kriːp] v. 爬行
sleeping [ˈsliːpɪŋ] bag 睡袋
comfortable [ˈkʌmftəbl; ˈkʌmfətəbl] adj. 舒适的
soundly [ˈsaʊndli] adv. 香甜的
leap [liːp] v. 跳跃
heavily [ˈhevɪli] adv. 大量的
stream [striːm] n. 小溪
form [fɔːm] v. 形成
wind [wɪnd] v. 蜿蜒
right [raɪt] adv. 正好

** Summary Writing
The boys put up their tent in the middle of a field, and they cooked a meal.
They told stories and sang songs after their meal, but it began to rain, so they crept into
  their tent.
The boys woke up in the middle of the night.
The tent was full of water, so they rushed outside.
A stream had formed in the field, and it flowed right under their tent.

** Topics for discussions
1. What must you take with you when you go on a camping expedition?
   I must take poker, fruits, phone, an open fire with me when I go on a camping expedition.
   
2. Imagine you are sitting round a campfire with some friends. Tell an entertaining story.
   Smith gets a good salary, but he always borrows money from his friends and never pays it
   back. I was having lunch in a restaurant, when he came in. He saw me and  sat down at the
   same table. I never lent him money, I asked him to lend me twenty pounds. To my surprise,
   he give the money immediately. 'I have never borrowed money from you' he said, 'now you can
   pay for my dinner!'

3. What are the advantages and disadvantages of a camping holiday?
   It's a good way to approach the nature.
   Sometimes ,however, it's unsafe.
  
