* L29 Taxi!
* article
Captain Ben Fawcett has bought an unusual taxi and has begun a new service.
The taxi is a small Swiss [swɪs] aeroplane called a 'Pilatus Porter'.
This wonderful plane can carry seven passengers.
The most surprising thing about it, however, is that it can land anywhere;
on snow, water, or even on a ploughed field.
Captain Fawcett's first passengers was a doctor
who flew from Birmingham to a lonely village in the Welsh mountains.
Since then, Captain Fawcett has flown passengers to many unusual places.
Once he landed on the roof of a block of flats and on another occasion,
he landed in a deserted car park.
Captain Fawcett has just refused a strange request from a businessman.
The man wanted to fly to Rockall, a lonely island in the Atlantic Ocean,
but Captain Fawcett did not take him because the trip was too dangerous.

* words
taxi [ˈtæksi]n.
Pilatus Porter n.
land [lænd] v.
plough [plaʊ] v.
lonely [ˈləʊnli] adj.
Welsh [welʃ] adj.
roof [ruːf] n.
block [blɒk] n.
flat [flæt] n.
desert [ˈdezət] v.

* Summary Writing
Captain Ben Fawcett has bought a small Swiss aeroplane and he uses it as a taxi.
It is called a 'Pilatus Porter'.
It can not only carry seven passengers, but also land anywhere. 
Captain Fawcett has taken passengers to many strange places in his plane.
He refused to fly a businessman to Rockall.
The journey was too dangerous.

* Topics
1. Have you ever flown in an aeroplane? Did you enjoy it? Why/Why not?
   I have flown to my girlfriend's home in an aeroplane.
   I did not enjoy it.
   The plane was late at night.
   When I arrived at the airport, I couldn't take public transport.

2. What are the advantages/disadvantages of air travel?
   Advantages:
   1. High Speed
   2. Comfortable and Quick Services.
   3. No Investment in Construction of Track.
   4. No Physical Barriers
   5. Easy Access.
   6. Emergency Services.
   7. Quick Clearance.

3. What do you think air travel will be like in the future
   (e.g. private helicopters, supersonic flight, journeys to the moon, etc.)?
   The cost of its operation is very high and thus it is suitable for only rich passengers.
   Private helicopters.
   Supersonic flight.
   Journeys to the moon.
   But it will never be suitable for pool passengers.

