#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 30 Football or polo?
#+begin_verse
What happened to the man in the boat?

The Wayle is a small river that cuts across the park near my home.
I like sitting by the Wayle on fine afternoons.
It was warm last Sunday, so I went and sat on the river bank as usual.
Some children were playing games on the bank and there were some people rowing on the river.
Suddenly, one of the children kicked a ball very hard and it went towards a passing boat.
Some people on the bank *called out to the man* in the boat, but he did not hear them.
The ball struck him so hard that he nearly fell into the water.
I turned to look at the children, but there weren't any in sight: they had all run away!
The man laughed when he realized what had happened.
He called out to the children and threw the ball back to the bank.
#+end_verse
** expression
polo [ˈpoʊloʊ] n.水球
Wayle n.
cut [kʌt] cut cut v.穿过
row [raʊ] v.划(船)
kick [kɪk] v.踢
towards [təˈwɒrd] prep.朝,向
nearly [ˈnɪrli] adv.几乎
sight [saɪt] n.眼界,视域

kick his ass 踢他的屁股

--------------------
doing现在分词做定语: 主动进行/主动一般
	- doing + n.
	- n. + doing
	- 常常和there be连用
	- 例句
		- the sinking ship=the ship that is sinking
		- the rising sun=the sun that is rising
		- the sleeping child=the child who is sleeping

call out to sb. 向某人呼喊



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
