* L30 Football or polo?
* Words
polo [ˈpəʊləʊ] n. 水球
Wayle n.
cut [kʌt] v. 穿过
row [rəʊ; raʊ] v. 划(船)
kick [kɪk] v. 踢
towards [təˈwɔːdz] prep. 朝,向
nearly [ˈnɪəli] adv. 几乎
sight [saɪt] n. 眼界
* article
What happened to the man in the boat?
The Wayle is a small river that cuts across the park near my home.
I like sitting by the Wayle on fine afternoons.
It was warm last Sunday, so I went and sat on the river bank as usual.
Some children were playing games on the bank and there were some people rowing on the river.
Suddenly, one of the children kicked a ball very hard and it went towards a passing boat.
Some people on the bank called out to the man in the boat, but he did not hear them.
The ball struck him so hard that he nearly fell into the water.
I turned to look at the children, but there weren't any in sight: they had all run away!
The man laughed when he realized what had happened.
He called out to the children and threw the ball back to the bank.

The man in the boat has been strucked by a ball.

Wayle - cut - park
sitting - by - afternoons
warm - went and sat - as usual
children - playing - some people rowing !!
kicked very hard - towards - passing
called out - did not hear
struck - hard - fell into
turn to- any in sight - run away
laughed - realize
call out - threw back

可能的语法:
1. 进行时做定语
2. 进行时做定语的位置
3. 过去进行时 L7
* Summary Writing
The writer sat by the river last Sunday.
Some children were playing games nearby.
One of the children kicked the ball hard and it went towards a passing boat.
The man in the boat neither saw the ball nor heard people shouting.
The ball hit the man and the children  ran away.
However, the man was not angry and he threw the ball back to the bank.

prep,可以不用逗号分割
neither nor,同一个人时,放在主语后面
* Topics for discussions
1. Imagine the following situation: The man in the story thought the children had
   kicked the ball towards him on purpose. Retell the rest of the story.
   The man shouted at the children when he realized what had happened.
   He got very angry, and he ask the children to apology to him for striking him.
   But there weren't any in sight: they had all ran away.
   Finally, the man left lonely.
   
2. What kind of games do you like playing? Why? Tell us how to play your favourite
   game.
   I like  sitting in the boat and doing nothing at all.
   It relaxes me a lot.

