* L32 Shopping made easy

** article
Who was the thief?

People are not so honest as they once were.
The temptation to steal is greater than ever before -- especially in large shops.
A detective recently watched a well-dressed woman who always went into a large store on Monday mornings.
One Monday, there were fewer people in the shop than usual when the woman came in,
  so it was easier for the detective to watch her.
The woman first bought a few small articles.
After a little time, she chose one of the most expensive dresses in the shop
  and handed it to an assistant who wrapped it up for her as quickly as possible.

Then the woman simply took the parcel and walked out of the shop without playing.
When she was arrested, the detective found out that the shop assistant was her daughter.
The girl gave her mother a free dress once a week!

honest
temptation - steal - than ever before
detective - well-dressed - Monday mornings
fewer than usual - came in - watch
bought - articles
chose - hand it to an assistant
parcel - walk - without playing


** words
once [wʌns] adv.
temptation [tempˈteɪʃ(ə)n] n.
article [ˈɑːtɪk(ə)l] n.
wrap [ræp] v.
simply [ˈsɪmpli] adv.
arrest [əˈrest] v.

** Asking questions
1. People are less honest than they once were. (Why, Who)
   Why are people less honest than they once were?
   Who are less honest than they once were?

2. The temptation to steal is greater than ever before.(What, Why)
   What is greater than ever before?
   Why is the temptation to steal is greater than ever before?

3. A woman was arrested recently. (Who)
   Who was arrested recently?

4. A detective watched her in a large store. (Who, Where)
   Who did a detective watch in a large store?
   Where did a detective watch her?

5. She always went there on Monday mornings.(When, Where, Why)
   When did she always go there?
   Where did she always go on Monday mornings?
   Why did she always go there on Monday mornings?

6. There were fewer people in the shop than usual. (How many, Where)
   How many people were there in the shop than usual?
   Where were there fewer people than usual?

7. It was easier to watch her.(Why)
   Why was it easier to watch her?

8. The woman bought a few small articles.(How many) (What kind)
   How many articles did the woman buy?
   What kind of articles did the woman buy?

** Tell the story

** Summary Writing
A detective watched a well-dressed woman in a large store one Monday.
She bought a few small articles and then she chose an expensive dress.
The assistant wrapped it up for her and the woman took it with her.
She did not pay for it, so the detective arrested her.
The assistant was her daughter.
She gave her mother a free dress once a week.

** Topics for discussions
1. Why do you think the temptation to steal is greater in a large store than a small shop?
   There are more expensive things in a large store than a small shop.
   It is easy to steal things in a large store than a small shop.
   
2. What times of the day/days of the week are the shops most crowded in your town? Why?
   At 8 o'clock of days, people have already got home and have a free time.
   In weekends, people don't have to work for their firms.
   
3. Do you agree that people are not so honest as before? Why/Why not?
   Yes.
   It is terrible for you to be honest when others are not.
   You might lose a lot.



