* L33 Out of the darkness
** articles
	Why was the girl in the hospital?

	Nearly a week passed before the girl was able to explain what had happened to her.
	One afternoon she set out from the coast in a small boat and was caught in a storm.
	Towards evening, the boat struck a rock and the girl jumped into the sea.
	Then she swam to the shore after spending the whole night in the water.
	Early next morning, she saw a light ahead.
	She knew she was near the shore because the light was high up the cliffs.
	On arriving at the shore, the girl struggled up the cliff towards the light she had seen.
	That was all she remembered.
	When she woke up a day later, she found herself in hospital.

	a week - before - explain
	one afternoon - set out - caught in a storm
	towards evening - struck a rock - jumped into the sea
	swam to the shore - spending whole night
	next morning - saw a light
	near the shore - light was high up
	struggled up the cliff
	remembered
	woke up - found in hospital

** New words and expressions
	darkness [ˈdɑːknəs] n.
	explain [ɪkˈspleɪn] v.
	coast [kəʊst] n.
	storm [stɔːm] n.
	towards [təˈwɔːdz] prep.
	rock n.
	shore [ʃɔː(r)] n.
	light n.
	ahead adv.
	cliff [klɪf] n
	struggle [ˈstrʌɡəl] v.
	hospital [ˈhɒspɪtl] n.

** Summary Writing
	The girl set out from the coast and was caught in a storm.
	Her boat struck a rock, so she jumped into the sea.
	She swim 8 miles that night.
	She reached the shore early next morning.
	She had seen a light high up on the cliffs and she climbed up.
	She found herself in hospital a day later.

** Topics for discussions
	1. Have you ever been out to sea in a small boat? Tell us about it.
		 Yes, I have.
		 The captain Alison entered an importance race across the Atlantic and he has given me a lift.

	2. What do you think happened to the from the time she reached the shore to the time
		 she woke up in hospital?
		 A man found out that a girl was sleeping soundly on the cliff.
		 He found she ill.
		 He made a decision to ask workmates to send her to hospital.
		 They had a difficult time to finish it.
		 Then the doctor had save her life.

	3. Imagine you are the girl. Give your 'story' to some newspaper reporters.
		 It's dangerous to sail in the sea, so I refuse to tell my story.
