#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 34 Quick work

#+begin_verse
How long had the police taken to find his bicycle?

Dan Robinson has been worried all week.
Last Tuesday he received a letter from the local police.
In the letter he was asked to *call at* the station.
Dan wondered why he was wanted by the police,
	but he went to the station yesterday and now he is not worried anymore.
At the station, he was told by a smiling policeman that his bicycle has been found.
Five days ago, the policeman told him,
	the bicycle was picked up in a small village four hundred miles away.
It is now being sent to his home by train.
Dan was most surprised when he heard the news.
He was amused too, because he never *expected the bicycle to be found*.
It was stolen twenty years ago when Dan was a boy of fifteen!
#+end_verse
** expression
station [ˈsteɪʃ(ə)n] n.警察局
most [moʊst] adv.相当,非常
--------------------
had been + done

call at = visit 不那么正式
except sth. to be found 期待某物被找到



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
