* L34 Quick work 破案神速

** articles
	Dan Robinson has been worried all week.
	Last Tuesday he received a letter from the local police.
	In the letter he was asked to call at the station.
	Dan wondered why he was wanted by the police,
		but he went to the station yesterday and now he is not worried anymore.
	At the station, he was told by a smiling policeman that his bicycle has been found.
	Five days ago, the policeman told him,
		the bicycle was picked up in a small village four hundred miles away.
	It is now being sent to his home by train.
	Dan was most surprised when he heard the news.
	He was amused too, because he never expected the bicycle to be found.
	It was stolen twenty years ago when Dan was a boy of fifteen!

** words
	station n.
	most

** Summary writing
	Dan Robinson was worried all week.
	He had received a letter from the local police.
	He went to the station yesterday.
	He is not worried anymore.
	The police have found his bicycle.
	Dan was not only surprised but amused as well.
	His bicycle was stolen twenty years ago.
	He was fifteen years old then.

** Topic for discussions
	1. Have you ever been worried because you had lost something? What was it?
		 Describe your feelings. Did you get it back? How?
		 Yes, my keys.
		 I felt nervous. If I lose them, I can't open my door.
		 I get it back from the Security Guards.
		 Someone had left them on the table of the Security Guards.

	2. How would you feel if you were asked to go to the police station? Why?
		 It is not 'about' anything to me.

	3. What are the advantages of owning a bicycle?
		 It's easy to ride a bicycle to the place having no public traffic.
