#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 35 Stop thief!
#+begin_verse
How did Roy stop the thieves?

Roy Trenton used to drive a taxi.
*A short while ago*, however, he became a bus driver and he has not *regretted it*.
He is finding his new work far more exciting.
When he was driving along Catford Street recently,
	he saw two thieves *rush out of* a shop and run towards a waiting car.
One of them was carrying a bag full of money.
Roy acted quickly and drove the bus straight at the thieves.
The one with money *got such a fright* that he dropped the bag.
As the thieves were trying to get away in their car, Roy drove his bus into the back of it.
While the battered car was moving away, Roy stopped his bus and telephoned the police.
The thieves' car was badly damaged and easy to recognized.
*Shortly afterwards*, the police stopped the car and both men were arrested.
#+end_verse
** expression
while [hwaɪl] n.一段时间
regret [rɪˈɡret] v.后悔
far [fɑr] adv.非常
rush [rʌʃ] v.冲
act [ækt] v.行动
straight [streɪt] adv.径直
fright [fraɪt] n.害怕
battered [ˈbætərd] adj.撞坏的
shortly [ˈʃɔrtli] adv.很快,不久
afterwards [ˈæftərwərdz] adv.以后

a short while ago 不久之前
regret sth./doing sth. 后悔做某事
rush out of/towards 冲出/奔向
go straight ahead 直走
give me a fright 吓我
get a fright 受到惊吓
Shortly afterwards 不久之后

--------------------
so + adj./adv. that = such + n. that: 如此以至于
see sb. do sth VS see sb. doing sth.



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
