* L35 Stop thief!

** articles
	How did Roy stop the thieves?

	Roy Trenton used to drive a taxi.
	A short while ago, however, he became a bus driver and he has not regretted it.
	He is finding his new work far more exciting.
	When he was driving along Catford Street recently,
		he saw two thieves rush out of a shop and run towards a waiting car.
	One of them was carrying a bag full of money.
	Roy acted quickly and drove the bus straight at the thieves.
	The one with money got such a fright that he dropped the bag.
	As the thieves were trying to get away in their car, Roy drove his bus into the back of it.
	While the battered car was moving away, Roy stopped his bus and telephoned the police.
	The thieves' car was badly damaged and easy to recognized.
	Shortly afterwards, the police stopped the car and both men were arrested.
	
** words
	while n.
	regret v.
	far adv.
	act v.
	straight adv.
	fright n.
	battered adj.
	shortly adv.
	afterwards adv.

** Pattern Drill
	1. She worked hard.
		 She worked so hard that she mad herself ill.
	2. It was a beautiful day.
		 It was such a beautiful day that we decided to go to the beach.
	3. I was tired.
		 I was so tired that I can't open my eyes.
	4. We had a good time on holiday.
		 We had such a good time on holiday that we didn't want to come home.
	5. She speaks English well.
		 She speaks English so well that you would think it was her native language.
	6. I've got a lot of things to do.
		 I've got such a lot of things to do that I don't know where to beign.
	7. The music was loud.
		 The music was so loud that you could hear it from miles away.
	8. I had a big breakfast.
		 I had such a big breakfast that I didn't eat anything else for the rest of the day.
	9. It was horrible weather.
		 It was such horrible weather that we spent the whole day indoors.
	clauses
	- You could hear it from miles away.
	- You would think it was her native language.
	- We spent the whole day indoors.
	- She mad herself ill.
	- I couldn't open my eyes.
	- I didn't eat anything else for the rest of the day.
	- We decided to go to the beach.
	- I don't know where to begin.
	- We didn't want to come home.

** Summary Writing
	Roy is finding his new job as a bus driver exciting.
	He saw two thieves on the Catford Street recently.
	They were running out of a shop and Roy drove his bus straight at them,
		so they dropped the stolen money and they got into a car.
	Roy drove his bus into the back of their car then and damaged it.
	After this he telephoned the police.
	Both men were arrested later.

** Topics for discussion
	1. In your experience which are the better drivers, taxi or bus driver? Why?
		 It's difficult to judge which are the better driver.
		 Because there are a great number of taxi and bus drivers.
		 In my opinion, I prefer bus drivers.
		 In my town, taxi drivers often break the traffic rules.

	2. Imagine you were a passenger on Roy Trenton's bus. Tell the story from your point of view.
		 I felt strange when Roy were turning around.
		 I wondered what had happened to him.
		 Then I got such a fright that I dropped my telephone.
		 He was droving his bus into the back of the car.
		 I worried about him.
		 Then he stopped his bus and called the police.
		 I realized what had happened to him, and I was not worried anymore.
		 I was proud of a brave driver.

	3. What would you do if you saw some thieves? Would you try to stop them? Why?
		 No, it's none of my business.
		 It's too dangerous to stop him.
