#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 36 Across the Channel

#+begin_verse
What is Debbie going to try to do?

Debbie Hart is going to swim across the English Channel tomorrow.
She is going to set out from the French coast at five o'clock in the morning.
Debbie is only eleven years old and she *hopes to set up a new world record*.
She is a strong swimmer and many people feel that she *is sure to succeed*.
Debbie's father will set out with her in a small boat.
Mr. Hart has trained his daughter for years.
Tomorrow he will be watching her anxiously as she swims the long distance to England.
Debbie *intends to take short rests* every two hours.
She will have something to drink but she will not eat any solid food.
Most of Debbie's school friends will be waiting for her on the English coast.
Among them will be Debbie's mother, who swam the Channel herself when she was a girl.
#+end_verse
** expression
record ['rekərd] n.记录
strong [strɔŋ] adj.强壮的
swimmer [ˈswɪmər] n.游泳运动员
succeed [səkˈsid] v.成功
train [treɪn] v.训练
anxiously ['æŋkʃəsli] adv.焦急地
intend [ɪnˈtend] v.打算
solid [ˈsɑlɪd] adj.固体的,硬的

set up a new world record 创造一项新的世界纪录
break the record 打破纪录
as strong as a horse 像马一样强壮
strong like a horse 像马一样强壮
succeed in doing sth. 成功做某事
train sb. to do sth. 训练某人做某事
intend to do sth. 打算做某事

--------------------
表述将来: 计划
be going to do(be due to)
will
intend to do

hope to do sth. 希望做某事
be sure to do sth. 务必做某事
take some rests/a rest 休息一下



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
