* L36 Across the Channel

** Asking questions
	1. Debbie Hart is going to swim across the English Channel. (Who When Why)
		 Who is going to swim across the English Channel?
		 When is Debbie Hart going to swim across the English Channel?
		 Why is Debbie Hart going to swim across the English Channel?
		 
	2. She is going to set out tomorrow. (When)
		 When is she going to set out?
		 
	3. She will leave from the French coast. (Which coast When Who)
		 Which coast will she leave from?
		 When will she leave from the French coast?
		 Who will leave from the French coast?

	4. She'll start at five o'clock in the morning. (What time)
		 What time will she start in the morning?

	5. Debbie is eleven years old. (How old)
		 How old is Debbie?

	6. She hopes to set up a new record. (What)
		 What does she hope to set up?

	7. She's a strong swimmer. (What kind of)
		 What kind of swimmer is she?

	8. Her father will set out with her.(Who)
		 Who will set out with her?

	9. He'll be in a small boat.(What Who)
		 What will he be in?
		 Who will be in a small boat?

	10. He's trained his daughter for years.(How long Who)
			How long has he trained his daughter?
			Who has he trained for years?
			
** Summary writing
	Debbie Hart is going to swim across the English Channel tomorrow.
	She is eleven years old and she is a strong swimmer.
	Debbie has been trained by her father.
	He will follow her in a small boat.
	Debbie's mother will be waiting on the English coast.
	She swam the Channel herself as a girl.

** Topics for discussion
	1. Debbie Hart illustrates the saying 'Like mother, like daughter'.
		 Tell us about someone you know who also illustrates this saying.
		 Xuyinchuan. His father is a champion of chess in a district, and he is a champion of chess in China.

	2. Do you 'train' for any sport? What does serious training for a sport involve?
		 Yes. I used to read chess books.

	3. Swimming is said to be the healthiest form of exercise. Do you agree? Why/Why not?
		 Yes, I do.
		 I can't refuse to swim in a river.
