#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 37 The Olympic Games
#+begin_verse
When was the last time this country hosted the Olympic Games?

*The Olympic Games will be held* in our country in four years' time.
As a great many people will be visiting the country,
	the government will be building new hotels, an immense stadium,
		and a new Olympic-standard swimming pool.
They will also be building new roads and a special railway line.
The Games will be held just outside the captial and the whole area will be called 'Olympic City'.
Workers will have completed the new roads by the end of this year.
By the end of next year, they will have finished work on the new stadium.
The fantastic modern buildings have been designed by Kurt Gunter.
Everybody will be watching anxiously as the new buildings go on.
We are all very excited and are *looking forward to the Olympic Games*
	because they have never held before in the country.
#+end_verse
** expression
Olympic adj.奥林匹克的
hold [hoʊld] v.召开
government [ˈɡʌvərnmənt] n.政府
immense [ɪˈmens] adj.巨大的
stadium [ˈsteɪdiəm] n.露天体育场
standard [ˈstændərd] n.标准
capital [ˈkæpɪt(ə)l] n.首都
fantastic [fænˈtæstɪk] adj.巨大的
design [dɪˈzaɪn] v.设计

hold a meeting 召开会议

--------------------
will have done: 1.动作持续(重复)到将来;2.动作截至到未来时间点前完成
have done VS had done VS will have done

look forward to doing sth. 期待做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
