* L38 Everything except the weather
Why did Harrison sell his house so quickly?

My old friend, Harrison, had lived in the Mediterranean
  for many years before he returned to England.
He had often dreamed of retiring in England and had planned to settle down in the country.
He had no sooner returned than he bought a house and went to live there.
Almost immediately he bagan to complain about the weather, for even though it was still summer,
  it rained continually and it was often bitterly cold.
After so many years of sunshine, Harrison got a shock.
He acted as if he had never lived in England before.
In the end, it was more than he could bear.
He had hardly had time to settle down when he sold the house and left the country.
The dream he had had for so many years ended there.
Harrison had thought of everything except the weather.

** Asking questions
1. Harrison is an old friend. who
   Who is an old friend?

2. He'd lived in the Mediterranean. Where
   Where had he lived?

3. He'd lived there for many years before he returned to England. How long/Where
   How long had he lived there before he returned to England?
   Where had he lived before he returned to England?

4. He'd often dreamed of retiring to England. What/Who
   What had he often dreamed of?
   Who had often dreamed of retiring to England?

5. He bought a house in the country. Where
   Where did he buy a house?

6. He went to live there. Where/Who
   Where did he go to live?
   Who went to live there?

7. He began to complain about the weather. What... about/Why/Who
   What did he begin to complain about?
   Why did he begin to complain about the weather?
   Who began to complain about the weather?

8. It rained continually. How often
   How often did it rain?

9. Harrison got a shock. Who/Why
   Who got a shock?
   Why did Harrison get a shock?

10. He sold the house. What/When
    What did he sell?
    When did he sell the house?

11. He left the country. Why/Who
    Why did he leave the country?
    Who left the country?
** Summary Writing
The writer's friend, Harrison, had spent many years in Mediterranean,
  but he wanted to retire in England, so he bought a house.
The writer's friend, Harrison, had spent many years in Mediterranean,
  but he wanted to retire in England so he bought a house.
The summer that year was very bad , and he complained about the weather.
The summer that year was very bad and he complained about the weather.
In the end, Harrison not only sold the house, but also left the country.
In the end Harrison not only sold the house but also left the country.
** Topics for discussion
1. Which foreign country would you like to live in? Why?
   I would like to live in American.
   Because not only their chicken were very cheap and but also it means freedom.

2. Have you ever looked forward to doing something and then been disappointed?
   Tell us about it.
   I have looked forward to getting score reports.
   I had hardly got them when I was disappointed.
   Because I tought it was a kind of food when I was very young.

3. What effect can weather have on the character of a people and their customs?
   I think England's weather makes people polite.
   In England, for it rained continually, they often take a umbrella all the time.

