#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 39 Am I all right?

#+begin_verse
Why did Mr. Gilbert telephone Dr. Millington?

While John Gilbert was in hospital,
	he asked his doctor to tell him whether his operation had been successful,
	but the doctor *refused to do so*.
The following day, the patient *asked for a bedside telephone*.
When he was alone, he telephoned the hospital exchange and asked for Doctor Millington.
When the doctor answered the phone,
	Mr. Gilbert said he was *inquiring about a certain patient*, a Mr. John Gilbert.
He asked if Mr. Gilbert's operation had been successful and the doctor told him that it had been.
He then asked when Mr. Gilbert would *be allowed to go* home
	and the doctor told him that he would have to stay in hospital for another two weeks.
Then Dr. Millington asked the caller if he was a relative of the patient.
'No,' the patient answered. 
'I am Mr. John Gilbert.'
#+end_verse
** expression
operation [ˌɑpəˈreɪʃ(ə)n] n.手术
successful [səkˈsesfəl] adj.成功的
following [ˈfɑloʊɪŋ] adj.下一个
patient [ˈpeɪʃ(ə)nt] n.病人
alone [əˈloʊn] adj.独自的
exchange [ɪksˈtʃeɪndʒ] n.(电话的)交换台
inquire [ɪnˈkwaɪr] v.询问,打听
certain [ˈsɜrt(ə)n] adj.某个
caller [ˈkɔlər] n.打电话的人
relative [ˈrelətɪv] n.亲戚

have an operation 动手术
leave me alone 离我远点
inquire about sth./sb. 询问某事/某人

--------------------
宾语从句
NCE1 L99 L101 L133 L135 L139

refuse to do sth. 拒绝做某事
ask for sth. 寻求某物
be allowed to do sth. 被允许做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
