* L39 Am I all right?

** story
While John Gilbert was in hospital, he asked his doctor to tell him
  wheather his operation had been succeeful, but the doctor refused to do so.
The following day, the patient asked for a bedside telephone.
When he was alone, he telephoned the hospital exchange and asked for Doctor Millington.
When the doctor answered the phone, Mr Gilbert said he was inquiring about a certain patient,
  a Mr. John Gilbert.
He asked if Mr. Gilbert's operation had been succeeful and the doctor told him that it had been.
He then asked when Mr. Gilbert would be allowed to go home and the doctor told him
  that he would have to stay in hospital for another two weeks.
Then Dr. Millington asked the caller if he was a relative of the patient. 'No,' the patient answered. 
"I am Mr. John Gilbert.'

** words
operation n. 手术
successful adj.
following adj. 下一个
patient n.
alone adj.
exchange n. (电话的)交换台
inquire v. 询问,打听
certain adj. 某个
caller n.
relative n. 亲戚

** Asking questions
1. John Gilbert was in hospital. Where
	 Where was John Gilbert?
	 
2. He'd had an operation. What
	 What had he had?
	 
3. He wanted to know whether it had been successful. What
	 What did he want to know?

4. He asked his doctor. Who
	 Who did he ask?

5. The doctor refused to tell him. What
	 What did the doctor refuse to do?

6. He asked for a bedside phone. What... for
	 What did he ask for?

7. He telephoned the hospital exchange when he was alone. When Where Why
	 When did he telephone the hospital exchange?
	 Where did he telephone when he was alone?
	 Why did he telephone the hospital exchange when he was alone?

8. He asked for Dr. Millington. Who... for
	 Who did he asked for?

9. He said he was enquiring about a patient. What Who... about
	 What was he enquiring about?
	 Who was he enquiring about?

10. The patient's name was John Gilbert. What
		What was the patient's name?
	 
** Summary writing
Dr. Millington refused to tell his patient, Mr. John Gilbert,
	whether his operation had been successful.
The patient telephone Dr. Millington next day and inquired about a certain patient,
	Mr. John Gilbert.
The doctor answered a number of questions about the patient and he asked whether the caller was
	a relative then.
The caller then told him who he was.

** Topics for discussion
1. Have you ever visited a hospital or had an operation? Tell us about it.
	 I had had an operation after I spent the whole holiday in my house.
	 I had hardly slept soundly when I began to have an operation.

2. Think of some other situations when, like Mr. Gilbert, you might pretend to be
		someone else on the telephone.
	 Wusd has already gone to school, and I knew that his grade was bad this time.

3. Should doctors always inform patients about their condition? Why/Why not?
	 No, doctors shouldn't.
	 Because it might be terrible to inform patients about their condition.

