#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 41 Do you call that a hat?

#+begin_verse
What kind of shopping does the writer enjoy, do you think?

'Do you call that a hat?' I said to my wife.
'You needn't be so rude about it,' my wife answered as she looked at herself in the mirror.
I sat down on one of those modern chairs with holes in it and waited.
We had been in the hat shop for half an hour and my wife was still in front of the mirror.
'We mustn't buy things we don't need,' I remarked suddenly.
I *regretted saying* it almost at once.
'You needn't have said that,' my wife answered.
'I needn't *remind you of that terrible tie* you bought yesterday.'
'I *find it beautiful*,' I said. 'A man can never have too many ties.'
'And a woman can't have too many hats,' she answered.
Ten minutes later we walked out of the shop together.
My wife was wearing a hat that looked like a lighthouse.
#+end_verse
** expression
rude [rud] adj.无礼的
mirror [ˈmɪrər] n.镜子
hole [hoʊl] n.孔
remark [rɪˈmɑrk] v.评说
remind [rɪˈmaɪnd] v.提醒
lighthouse [ˈlaɪtˌhaʊs] n.灯塔

remind sb. of sth./sb. 使某人想起某事

--------------------
need: 需要
needn't have done: 本不必如此,却做了,有后悔效果

regret doing sth. 后悔做某事
find sth. adj. 发现某事adj.



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
