* L41 Do you call that a hat?
'Do you call that a hat?' I said to my wife.

'You needn't be so rude about it,' my wife answered as she looked at herself in the mirror.

I sat down on one of those modern chairs with holes in it and waited.
We had been in the hat shop for half an hour and my wife was still in front of the mirror.

'We mustn't buy things we don't need,' I remarked suddenly.
I regretted saying it almost at once.

'You needn't have said that,' my wife answered. 'I needn't remind you of that terrible tie you
	bought yesterday.'

'I find it beautiful,' I said. 'A man can never have too may ties.'

'And a woman can't have too many hats,' she answered.

Ten minutes later we walked out of the shop together.
My wife was wearing a hat that looked like a lighthouse.

** Asking questions
1. I was in a hat shop. Where
	 Where was I?
	 
2. I was with my wife. Who
	 Who was I with?

3. She was trying on a hat. What
	 What was she trying on?

4. It looked terrible. How
	 How did it look?

5. We'd been in the shop for half an hour. How long
	 How long did we been in the shop?

6. I sat down on a modern chair. Where
	 Where did I sit down?

7. It had holes in it. What
	 What had holes in it?

8. My wife was looking at herself in the mirror. What ... doing
	 What was your wife doing?

9. I made a sudden remark. What ... do
	 What did you do?

10. I regretted saying it almost at once. How soon
		How soon did you regret saying it?

11. I said we mustn't buy things we don't need. What
		What did you say?
		
	 
** Summary writing
The writer's wife was tring on a hat but he didn't like it.
He sat down and he waited for her.
Then they begun arguing again.
He had bought a tie the day before but his wife didn't like it.
'A man can never have too many ties', he said.
His wife used exactly the same argument and she bought the hat.
It looked like a lighthouse.

** Topics for discussion
1. What kinds of things would you like that you don't really need?
	 Chess.
	 I am not interesting in winning prize, I am just interesting in staying with friends.

2. Who do you think are generally more extravagant, men or women? Why?
	 Men.
	 We must buy a house that we have to pay for it for thirty years.

3. What is meant by the proverb: 'Waste not, want not'? Give some examples.
	 If I didn't waste money, I could buy a car now. 
	 
