#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 42 Not very musical

#+begin_verse
What happened when the snake charmer began to play jazz?

As we had *had a long walk* through one of the markets of Old Delhi,
	we stopped at a square to have a rest.
After a time, we noticed a snake charmer with two large baskets *at the other side of* the square,
	so we went to have a look at him.
As soon as he saw us,
	he picked up a long pipe which was covered with coins and opened one of the baskets.
When he began to *play a tune*,
	we *had our first glimpse of the snake*.
It rose out of the basket and began to follow the movements of the pipe.
We were very much surprised when the snake charmer suddenly began to play jazz and modern pop songs.
The snake, however, *continued to 'dance'* slowly.
It obviously could not *tell the difference between Indian music and jazz*!
#+end_verse
** expression
musical [ˈmjuzɪk(ə)l] adj.精通音乐的
market [ˈmɑrkət] n.市场,集市
snake [sneɪk] charmer [ˈtʃɑrmər] 玩蛇者(借音乐控制)
pipe [paɪp] n.(吹奏的)管乐器
tune [tun] n.曲调
glimpse [ɡlɪmps] n.一瞥
snake [sneɪk] n.蛇
movement [ˈmuvmənt] n.动作
continue [kənˈtɪnju] v.继续
dance [dæns] v.跳舞
obviously [ˈɑbviəsli] adv.显然
difference [ˈdɪf(ə)rəns] n.差别
Indian [ˈɪndiən] adj.印度的

watch a musical 观看音乐剧
play a tune 演奏一曲
have a glimpse of sth./sb. 瞥见某物/某人
continue to do sth. 继续做某事
tell the difference from A and B / A be different from B 区别于A和B / A不同于B

--------------------
have 万能动词

have a long walk 长时间散步
at the other side of sw. 在...另一边



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
