#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 43 Over the South Pole
#+begin_verse
How was the plane able to clear the mountains?

In 1929, three years after his flight over the North Pole,
	the American explorer, R.E. Byrd, successfully flew over the South Pole for the first time.
Though, at first,
	Byrd and his men were able to take a great many photographs of the mountains that lay below,
	they soon *ran into serious trouble*.
*At one point*, *it seemed certain that* their plane would crash.
It could only get over the mountains if it rose to 10,000 feet.
Byrd at once *ordered his men to throw* out two heavy food sacks.
The plane was then able to rise and it cleared the mountains by 400 feet.
Byrd now knew that he would be able to reach the South Pole which was 300 miles away,
	for there were no more mountains in sight.
The aircraft was able to fly over the endless white plains without difficulty.
#+end_verse
** expression
pole [poʊl] n.(地球的)极
flight [flaɪt] n.飞行
explorer [ɪkˈsplɔrər] n.探险家
lie [laɪ] lay [leɪ] lain [leɪn] v.处于
serious [ˈsɪriəs] adj.严重的
point [pɔɪnt] n.地点
seem [sim] v.似乎,好像
crash [kræʃ] v.坠毁
sack [sæk] n.袋子
clear [klɪr] v.越过
aircraft [ˈerˌkræft] n.飞机
endless [ˈendləs] adj.无尽的
plain [pleɪn] n.平原

catch a flight 赶飞机
run into serious trouble 遇到严重的麻烦
one point 指出
It seems that ... 看来……

--------------------
- be able to: 有能力; 做成某事的案例
	+ can: 有能力(be able to的一般时);可能发生;
	+ could: 有能力(be able to的过去式);可能发生; 被允许; 没有!!!做成某事的案例
	+ was able to: 有能力(be able to的过去式); 做成某事的案例
	+ managed to do: 做成某事的案例
	+ 对比以上时态更多

order sb. to do sth. 命令某人做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
