* L44 Through the forest
How did Mrs. Sterling get her bag back?

Mrs. Anne Sterling did not think of the risk she was taking
	when she ran through a forest after two men.
They had rushed up to her while she was havig a picnic at the edge of a forest with her children
	and tried to steal her handbag.
In the struggle, the strap broke and, with the bag in their possession,
	both men started runnig through the trees.
Mrs. Sterling got so angry that she ran after them.
She was soon out of breath, but she continued to run.
When she caught up with them, she saw that they had sat down
	and were going through the contents of the bag, so she ran straight at them.
The men got such a fright that they dropped the bag and ran away.
"The strap needs mending," said Mrs. Sterling later, 'but thet did not steal anything."

** words
forest n.
risk n.
picnic
edge n.
strap n.
possession n.
breath n.
contents n.
mend v.

** Asking questions
1. Mrs. Anne Sterling was having a picnic. Who Where
	 Who was having a picnic?
	 Where was Mrs. Anne Sterling having a picnic?

2. She was with her children. Who... with
	 Who was she with?

3. They were sitting at the edge of a forest. Where Why Who
	 Where were they sitting?
	 Why were they sitting at the edge of a forest?
	 Who were sitting at the edge of a forest?

4. Tow men rushed up to her. How many
	 How many men rushed up to her?

5. They tried to steal her handbag. What
	 What did they try to steal?

6. The strap broke in the struggle. What
	 What broke in the struggle?

7. The men ran off with the bag. What
	 What did the men run off with?

8. They started running through the trees. Where Why Who
	 Where did they start running?
	 Why did they start running through the trees?
	 Who started running through the trees?

9. Mrs. Sterling was very angry. Why Who
	 Why was Mrs. Sterling very angry?
	 Who was very angry?

10. She ran after them. What... do
		What did she do?

11. She was soon out of breath. Why
		Why was she soon out of breath?

** Summary writing
Two men tried to steal Mrs. Sterling's handbag.
She was having a picnic at the edge of a forest with her children at the time.
They took the bag after a struggle and ran through the trees.
She ran after them and caught up with them.
The men had sat down and were going through the contents of her bag.
Mrs. Sterling ran straight at them so they ran away.

** Topics for discussion
1. What, do you think, were the contents of Mrs. Sterling's handbag?
	 What sort of things do you usually carry around in your handbag/pocket? Why?
	 Wallet and keys.
	 Phone and keys.
	 I open the door of my home by using keys.
	 I pay for my dinner by using phone.

2. Do you like going on picnics? What sort of places do you choose? Why?
	 I don't like going on picnics.
	 If I go on picnics, I will be very tired.

3. In what kinds of situations do ordinary people suddenly behave in an extraordinary way?
	 A woman was caught in a storm.
	 A woman who intended to swim across the Channel.

