* L45 A clear conscience
How did Sam get his money back?

The whole village soon learnt that a large sum of money had been lost.
Sam Benton, the local butcher, had lost his wallet while taking his savings to the post office.
Sam was sure that the wallet must have been found by one of the villagers,
	but it was not returned to him.
Three months passed, and then one morning, Sam found his wallet outside his front door.
It had been wrapped up in newspaper and it contained half the money he had list,
	together with a note which said:'A thief, yes, but only 50 percent a thief!'
Two months later, some more money was sent to Sam with another note:'Only 25 percent a thief now!'
In time, all Sam's money was paid back in this way.
The last note said: 'I am 100 percent honest now!'

** words
clear adj.
conscience n.
wallet n.
savings n.
villager n.
per cent

** asking questions
1. The whole village soon learnt the news. How quickly/ What/ Who
	 How quickly did the whole village learn the news?
	 What did the whole village soon learn?
	 Who soon learnt the news?

2. A large sum of money had been lost. What
	 What had been lost?

3. Sam Benton had lost his wallet. What
	 What had Sam Benton lost?

4. Sam was the local butcher. What/Who
	 What job was Sam?
	 Who was the local butcher?

5. He was taking his savings to the post office. Where/What/Who
	 Where was he taking his savings?
	 What was he taking to the post office?
	 Who was taking his savings to the post office?

6. The wallet was returned three months later. When/What
	 When was the wallet returned?
	 What was returned three months later?

7. Sam found the wallet outside his front door. What/Where/Who
	 What did Sam find outside his front door?
	 Where did Sam find the wallet?
	 Who found the wallet outside his front door?

8. It had been wrapped up in newspaper. What ... in
	 What had it been wrapped up in?

9. There was a note in it. What
	 What was there in it?

** Summary writing
The local butcher, Sam Benton, was taking his savings to the post office but lost his wallet.
Three months later ,Sam not only received half his money but a note as well.
The note said: 'A thief, yes. but only 50 percent a thief!'
The thief included a note every time he sent Sam more money.
The last note said: 'I am 100 percent honest now!'

** Topics for discussion
1. What would you do if you lost the equivalent of $1000?
	 Would you expect to get it back? Why/Why not?
	 I wouldn't except to get it back.
	 It's a waste of time and power.

2. Do you think anyone is '100% honest'?
	 Give examples to illustrate your answer.
	 Yes, I do.
	 A baby.

3. 'Honesty is the best policy.' Is this always true? Why/Why not?
	 No, this isn't.
	 If your wife ask you whether she is fat, it can be better to tell her a lie.
