* L48 Did you want to tell me something
Why did teh writer become very worried?

Dentists always ask questions when it is impossible for you to answer.
My dentist had just pulled out one of my teeth and had told me to rest for a while.
I tried to say something, but my mouth was full of cotton wool.
He knew I collected match boxes and asked me whether my collection was growing.
He then asked me how my brother was and whether I liked my new job in London.
In answer to these questions I either nodded or made strange noises.
Meanwhile, my tongue was busy searching out the hole where the tooth had been.
I suddenly felt very worried, but could not say anything.
When the dentist at last removed the cotton wool from my mouth,
	I was able to tell him that he had pulled out the wrong tooth.

** words
pull v.
cotton wool
collect v.
collection n.
nod
meanwhile

** asking questions
1. Dentists always ask questions when you can't answer. When/Who
	 When do dentist always ask questions?
	 Who always ask questions when you can't answer?

2. My dentist does this. Who/What
	 Who does this?
	 What does my dentist do?

3. He'd just pulled out a tooth. What
	 What had he just pulled out?

4. I had to rest for a while. How long
	 How long did you have to rest?

5. I tried to speak. What... do
	 Whatd did you try to do?

6. My mouth was full of cotton wool. What
	 What was my mouth full of?

7. I collect match boxes. What
	 What do I collect?

8. The dentist asked me about my collection. What... about/Who
	 What did the dentist ask you about?
	 Who asked you about your collection?

9. He wanted to know about my new job. What...about/Who
	 What did he want to know about?
	 Who wanted to know about your new job?

10. I answered him with nods and strange noises. How/Why
		How did you answer him?
		Why did you answer him with nods and strange noises?

** Summary writing
The dentist in the story had pulled out one of the writer's teeth
	and he told him to rest for a while.
He asked several questions but the writer could not answer them.
His mouth was full of cotton wool.
He suddenly discovered something wrong but he could not say anything.
The dentist eventually removed the cotton wool from his mouth
	and the writer told him he had pulled out the wrong tooth.

** Topics for discussion
1. How often do you go to the dentist's? Do you go regularly? Why/Why not?
	 I never go to the dentist's.My teeth is extremly because I wash them twice every day.
	 
2. What reasons might a dentist have for talking to his patients while treating them?
	 The patients are very worried or nervous.

3. People in some countries have much better teeth than those in others.
	 Can you suggest any reasons for this.
	 Don't drink water in the stream. Drink boiled water.
