* L50 Taken for a ride
Why did the writer not get off the bus at Woodford Green?

I love travelling in the country, but I don't like losing my way.
I went on excursion recently, but my trip took me longer than I expected.
'I'm going to Woodford Green,' I said to the conductor as I got on the bus,
	'but I don't know where it is.'
'I'll tell you where to get off,' answered the conductor.
I sat in the front of the bus to get a good view of the countryside.
After some time, the bus stopped.
	Looking round, I realized with a shock that I was the only passenger left on the bus.
'You'll have to get off here,' the conductor said. 'This is as far as we go.'
'Is this Woodford Green?' I asked.
'Oh dear,' said the conductor suddenly. 'I forgot to put you off.'
'It doesn't matter,' I said. 'I'll get off here.'
'We're going back now,' said the conductor.
'Well, in that case, I prefer to stay on the bus,' I answered.
	

love travelling
went on excursion
going to Woodford Green - conductor
sat in front of - a good view of countryside
After some time - stop - look around - was left
Is - woodford
Oh dear - suddenly- forgot to put you off
doesn't matter - get off here
are going back now
in that case - prefer to stay

** words
ride n.
excursion n.
conductor n.
view n.

** Asking questions
1. I love travelling in the country. What
	 What do you love in the country?
	 
2. I went on an excursion recently. When
	 When did you go on an excursion?

3. I went by bus. How/Where
	 How did you go?
	 Where did you go by bus?

4. My trip took longer than I excepted. How long/What/Why
	 How did my trip take?
	 What took longer than I excepted?
	 Why did my trip take longer than I excepted?

5. I wanted to get off at Woodford Green. Where/Why/Who
	 Where did I want to get off?
	 Why did I want to get off at Woodford Green?
	 Who wanted to get off at Woodford Green?

6. I told the conductor where I was going. Who/What
	 Who did I tell where I was going?
	 What did I tell the conductor?

7. He said he'd tell me where to get off. What/Why
	 What did he say?
	 Why did he say he'd tell me where to get off?

8. I sat in the front of the bus. Where
	 Where did I sit?

9. I got a good view of the countryside. What ... of/Who
	 What a good view of did I get?
	 Who got a good view of the countryside?
		
** Composition
1. I went into the kitchen. I turned on the light. It was dark. (On going...because)
	 On going into the kitchen, I turned on the light because it was dark.
	 
2. My brother shouted angrily. The lights went on. (When)
	 My brother shouted angrily when the lights went on.

3. I spoilt a film. He was developing it. (which)
	 I spoilt a film which he was developing.

** Summary writing
The writer wanted to go to Woodford Green,
	but he didn't know the way as the conductor promised to tell him where to get off.
When they arrived at bus terminus, the writer asked whether it is Woodford Green.
The conductor realized that he had forgot to put the writer off. 
The writer stayed on the bus because the bus were going back.

** Topics for discussion

