#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 54 Sticky fingers
#+begin_verse
What two interruptions did the writer have?

After breakfast, I *sent the children to school* and then I went to the shops.
It was still early when I returned home.
The children were at school, my husband was at work and the house was quiet.
So I *decided to make* some meat pies.
In a short time I *was busy mixing* butter and flour
	and my hands *were soon covered with sticky pastry*.
At exactly that moment, the telephone rang.
Nothing could have been more annoying.
I picked up the receiver between two sticky fingers
	and was dismayed when I *recognized the voice of Helen Bates*.
It *took me ten minutes to* *persuade her to ring* back later.
At last I *hung up* the receiver.
*What a mess*!
There was pastry on my fingers, on the telephone, and on the doorknobs.
I had no sooner got back to the kitchen than the doorbell rang loud enough to wake the dead.
This time it was the postman and he wanted me to *sign for a registered letter*!
#+end_verse
** expression
sticky [ˈstɪki] adj.粘的
finger [ˈfɪŋɡə(r)] n.手指
pie [paɪ] n.馅饼
mix [mɪks] v.混合,搅拌
pastry [ˈpeɪstri] n.面糊
annoying [əˈnɔɪɪŋ] adj.恼人的
receiver [rɪˈsiːvə(r)] n.电话的话筒
dismay [dɪsˈmeɪ] v.失望,泄气
recognize [ˈrekəɡnaɪz] v.认出,听出
persuade [pəˈsweɪd] v.说服,劝说
mess [mes] n.乱七八糟
doorknob [ˈdɔːnɒb] n.门把手
sign [saɪn] v.签字
register [ˈredʒɪstə(r)] v.挂号邮寄

stick to the plan 坚持计划
put my finger on it 把我的手指放在上面
point the finger at 指着某人
be dismayed to do sth. 对做某事感到沮丧
recognize the voice (of sb.) 听出(某人的)声音
persuade sb. (not) to do sth. 说服某人(不)做某事
What a mess! 一团糟
such a mess 一团糟
Sign here 在这里签名
sign for sth. 签收某物
a registered letter 挂号信

send sb. to sp. 把某人送到
decide to do sth. 决定做某事
be busy doing sth. 忙于做某事
be covered with sth. 被某物覆盖
take sb. st. to do sth. 花费某人时间去做某事
hang up 挂断电话
What a mess! 一团糟
sign for sth. 签收某物



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
