* L55 Not a gold mine
What did the team find?

Dreams of finding lost treasure almost came true recently.
A new machine called 'The Revealer' has been invented
	and it has been used to detect gold which has been buried in the ground.
The machine was used in a cave near the seashore where -- it is said - pirates used to hide gold.
The pirates would often bury gold in the cave and then fail to collect it.
Armed with the new machine, a search party went into the cave hoping to find buried treasure.
The leader of the party was examining the soil near the entrance to the cave
	when the machine showed that there was gold under the ground.
Very excited, the party dug a hole two feet deep.
They finally found a small gold coin which was almost worthless.
The party then searched the whole cave thoroughly
	but did not find anything except an empty tin trunk.
In spite of this, many people are confident
	that 'The Revealer' may reveal something of value fairly soon.

Dream - treasure - true
machine - invent - gold
a cave - pirates - hide gold
pirates - bury - fail
armed - a search party - cave hoping to find
leader - examinig - gold
excited - dug - two
a small gold coin - worthless
thoroughly - anything - tin trunk
spite - confident - reveal

** Pattern Drill
1T: eat sweets - dentist
S1: I used to eat a lot of sweets.
S2: So did I, until my dentist told me not to.

drink whisky - doctor
	I used to drink a lot of whisky.
	So did I, until my doctor told me not to.

buy clothes - father
	I used to buy a lot of clothes.
	So did I, until my father told me not to.

read comics - teacher
	I used to read a lot of comics.
	So did I, until my teacher told me not to.

smoke cigarette - mother
	I used to smoke a lot of cigarette.
	So did I, until my mother told me not to.

2T: drive so much - lorry driver
S1: It isn't good for him to drive so much!
S2: Don't worry, he's used to driving. He's a lorry driver.

run so hard - footballer
	It isn't good for him to run so hard!
	Don't worry, he's used to running. He's a footballer.

argue so much - policeman
	It isn't good for him to argue so much!
	Don't worry, he's used to argue. He's a policeman.

stay up so late - journalist
	It isn't good for him to stay up so late!
	Don't worry, he's used to stay up. He's journalist.

travel so much - businessman
	It isn't good for him to travel so much!
	Don't worry, he's used to travel. He's a businessman.

3T: have a dog - take it for walks
S1: They used to have a dog.
S2: Yes, and they were always taking it for walks!

own a car - polish it
	They used to own a car.
	Yes, and they were always polishing it.

be in politics - make speeches
	They used to be in politics.
	Yes, and they were always making speeches.

have a gun - shoot birds
	They used to have a gun.
	Yes, and they were always shooting birds.

play football - get hurt
	They used to play football.
	Yes, and they were always getting hurt.
