#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 56 Faster than sound!
#+begin_verse
How fast did the winning car go?

Once a year, a race is held for old cars.
A lot of cars entered for this race last year
	and there was a great deal of excitement just before it began.
One of the most handsome cars was a Rolls-Royce Silver Ghost.
The most unusual car was a Benz which had only three wheels.
Built in 1885, it was the oldest car taking part.
After a great many loud explosions, the race began.
Many of the cars *broke down* *on the course*
	and some drivers spent more time under their cars than in them!
A few cars, however, completed the race.
The winning car reached a speed of forty miles an hour - much faster than any of its rivals.
It sped downhill at the end of the race and its driver had a lot of trouble trying to stop it.
The race gave everyone *a great deal of* pleasure.
It *was very different from* modern car races but no less exciting.
#+end_verse
** expression
sound [saʊnd] n.声音
excitement [ɪkˈsaɪtmənt] n.激动,兴奋
handsome [ˈhænsəm] adj.漂亮的;美观的
Rolls-Royce [ˌrəʊlz ˈrɔɪs]
Benz [benz] n.
wheel [wiːl] n.轮子
explosion [ɪkˈspləʊʒ(ə)n] n.爆炸,轰鸣
course [kɔːs] n.跑道,行程
rival [ˈraɪv(ə)l] n.对手
speed [spiːd] v.疾驶
downhill [ˌdaʊnˈhɪl; ˈdaʊnhɪl] adv. adj.下坡

make a sound 发出声音
hear a sound 听到声音
on the course 在过程中
speed it/things/this up 加快速度
go downhill 走下坡路

--------------------
adj.er
adj.est
more + adj.
the most + adj.

a great deal of ... 不可数 大量的
a great many + 可数 相当多的
break down 停止运行
a be different form b. A不同于b



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
