* L57 Can I help you, madam?
Did the woman get what she wanted?

A woman in jeans stood at the window of an expensive shop.
Though she hesitated for a moment,
	she finally went in and asked to see a dress that was in the window.
The assistant who served her did not the way she was dressed.
Glancing at her scornfully, he told her that the dress was sold.
The woman walked out of the shop angrily and decided to punish the assistant next day.
She returned to the shop the following morning dressed in fur coat,
	with a handbag in one hand and a long umbrella in the other.
After seeking out the rude assistant, she asked for the same dress.
Not realizing who she was, the assistant was eager to serve her this time.
With great difficulty, he climbed into the shop window to get the dress.
As soon as she saw it, the woman she did not like it.
She enjoyed herself marking the assistant bring almost everything in the window
	before finally buying the dress she had first asked for.
	
** asking questions
1. A woman stood at a shop window. Who
	 Who stood at a shop window?

2. She was wearing jeans. What
	 What was she wearing?

3. It was an expensive shop. What kind of
	 What kind of shop was it?

4. She was looking at a dress. What
	 What was she looking at?

5. She hesitated for a moment. How long
	 How long did she hesitate?

6. She finally went into the shop. Where
	 Where did she finally go?

7. She asked to see the dress. What
	 What did she ask to see?

8. The assistant glanced at her scornfully. How/ Why/ Who
	 How did the assistant glance at her?
	 Why did the assistant glance at her scornfully?
	 Who glanced at her scornfully?

9. He told her the dress was sold. What
	 What did he tell her?

10. The woman walked out of the shop angrily. Why/Who
		Why did the woman walk out of the shop angrily?
		Who walked out of the shop angrily?

11. She returned to the shop the next day. When/Why/Who
		When did she return to the shop?
		Why did she return to the shop the next day?
		Who returned to the shop the next day?

** Summary Writing
Though the woman in jeans hesitated for a moment,
	she entered an expensive shop and asked to see a dress that was in the window.
An assistant told her the dress was sold.
On being told by an assistant the dress was sold,
	the woman returned to the shop the following morning dressed in a fur coat.
The assistant was eager to server her this time.
After making him bring almost everything in the window,
	the woman finally bought the dress she had first asked for.

** Topics for discussion
1. Describe an annoying experience you've had while being served in a shop.
	 I and my female counsin waited for my wife at a resturant that was in XiHu district.
	 The waiter asked me to order dishes three times.
	 I got very angry and told the assistant that I wouldn't do this until my wife arrived. 

2. Do you sympathize with the woman in the story? Why/Why not?
	 Yes.
	 She may buy a dress that she don't need at all, because she decided to punish the assistant.
	 It was a waste of money.

3. What are the advantages/disadvantages of shopping in large stores and small shops.
	 There are a lot of things in large stores.
	 No one bothers you when you are in shopping.
	 The large store was unusual far from our houses, but it is convenient to find out small shops.

