#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 58 A blessing in disguise?
#+begin_verse
Why does the vicar refuse to cut down the tree?

The tiny village of Frinley is said to possess a 'cursed tree'.
Because the tree was mentioned in a newspaper, the number of visitors to Frinley has now increased.
The tree was planted near the church fifty years ago,
	but it is only in recent years that it has gained an evil reputation.
It is said that if anyone touches the tree, he will have bad luck;
	if he picks a leaf, he will die.
Many villagers believe that the tree has already claimed *a number of* victims.
The vicar has been asked to have the tree cut down, but so far he has refused.
He has *pointed out that* the tree is a useful *source of income*,
	as tourists have been coming from all parts of the country to see it.
In spite of all that has been said,
	the tourists have been picking leaves and cutting their names on the tree-trunk.
So far, not one of them has been struck down by sudden death.
#+end_verse
** expression
blessing [ˈblesɪŋ] n.福分,福气
disguise [dɪsˈɡaɪz] n.伪装
tiny [ˈtaɪni] adj.极小的
possess [pəˈzes] v.拥有
cursed [kɜːst; ˈkɜːsɪd] adj.可恨的
increase [ɪnˈkriːs] v.增加
plant [plɑːnt] v.种植
church [tʃɜːtʃ] n.教堂
evil [ˈiːv(ə)l] adj.坏的
reputation [ˌrepjuˈteɪʃ(ə)n] n.名声
claim [kleɪm] v.以...为其后果
victim [ˈvɪktɪm] n.受害者,牺牲品
vicar [ˈvɪkə(r)] n.教区牧师
source [sɔːs] n.来源
income [ˈɪnkʌm] n.收入
trunk [trʌŋk] n.树干

It is a blessing that ... 这是一件幸事……
what a blessing 真是福气
God bless you 上帝保佑你
It's a blessing 这是一种祝福
a blessing in disguise 因祸得福
In one's possession 在某人手中
Go to church 参加教堂礼拜
Go to the church 去教堂
have a good/bad reputation 有好名声/坏名声
Have a reputation for... 有……的名声
baggage claim 行李领取区
source of income/information 收入来源/信息来源

--------------------
be said to do...: 据说
It is said that...: 据说

强调句:
	- It is(was) + 强调部分 + that(who) + 剩余部分?
	- do/does/did + v., (but + ...)
被动: 复习L34 & L10

a number of 大量
sb. point out that... 有人指出……



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
