* L58 A blessing in disguise?
Why does the vicar refuse to cut down the tree?

The tiny village of Frinley is said to possess a 'cursed tree'.
Because the tree was mentioned in a newspaper, the number of visitors to Frinley has now increased.
The tree was planted near the church fifty years ago,
	but it is only in recent years that it has gained an evil reputation.
It is said that if anyone touches the tree, he will have bad luck;
	if he picks a leaf, he will die.
Many villagers believe that the tree has already claimed a number of victims.
The vicar has been asked to have the tree cut down, but so far he has refused.
He has pointed out that the tree is a useful source of income,
	as tourists have been comming from all parts of the country to see it.
In spite of all that has been said,
	the tourists have been picking leaves and cutting their names on the tree-trunk.
So far, not one of them has been struck down by sudden death!

** words
blessing [ˈblesɪŋ]
disguise [dɪsˈɡaɪz]
tiny [ˈtaɪni]
possess [pəˈzes]
cursed [kɜːst; ˈkɜːsɪd]
increase [ɪnˈkriːs]
plant [plɑːnt]
church [tʃɜːtʃ]
evil [ˈiːv(ə)l]
reputation [ˌrepjuˈteɪʃ(ə)n]
claim [kleɪm]
victim [ˈvɪktɪm]
vicar [ˈvɪkə(r)]
source [sɔːs]
income [ˈɪnkʌm]
trunk [trʌŋk]

** Asking questions
1. The village of Frinley is tiny. How big
	 How big is the village of Frinley?

2. It's said to possess a 'cursed tree'. What
	 What is it said to possess?

3. It was mentioned in a newspaper. Where
	 Where was it mentioned?

4. There have been more visitors to Frinley since then. Since when/Why
	 Since when have there been more visitors to Frinley?
	 Why have there been more visitors to Frinley since then?

5. They come to see the tree. What/Why
	 What do they come to do?
	 Why do they come to see the tree?

6. It was planted fifty years ago. When
	 When was it planted?

7. It's near the church? Where/What
	 Where is it?
	 What is near the church?

8. It's gained an evil reputation. What
	 What has it gained?

9. The villagers say it's unlucky. What
	 What do the villagers say?

10. Anyone who touches the tree will have bad luck. What will happen to/ Who
		What will happen to anyone who touches the tree?
		Who will have bad luck?

11. The vicar's been asked to have it cut down. What/Why/Who
		What has the vicar been asked to do?
		Why has the vicar been asked to have it cut down?
		Who has been asked to have it cut down?

** Summary Writing
The number of visitors to the village of Frinley has increased
	because there is said to be a 'cursed tree' near a church.
Since the villagers believe that if anyone picks a leaf he will die,
	they have asked the vicar to have the tree cut down.
As the tree is a useful source of income,
	the vicar has refused to have the tree cut down.
Meanwhile, though tourists have been picking leaves, none of them have come to harm.

** Composition
1. A village well was said to be cursed. It was bought by a man. Which
	 A village well which was bought by a man was said to be cursed.

2. Tourists came to see it. There was not even any water in it. though
	 Tourists came to see it though there was not even any water in it.

3. The tourists could look into the well. They had to throw a coin in first. Before
	 Before the tourist could look into the well, they had to throw a coin in first.

** Topics for discussion
1. Do you know of a place/thing (real or in fiction) said to be 'cursed'? Tell us about it.
	 A cave near the railway is said to be cursed.
	 If anyone go into the entrance, he will die.

2. Imagine you are a villager and the vicar in the story.
	 Give your reasons for wishing and refusing to have the tree cut down.
	 Althought visitors who have been coming from all parts of the country have been picking leaves,
		none of them have been struck down by sudden death.

3. Tell us about some common superstitions in this country.
	 The Goddess of Mercy.

