* L59 In or out?
Why did Rex run away?

Our dog, Rex, used to sit outside our front gate and bark.
Every time he wanted to come into the garden he would bark until someone opened the gate.
As the neighbours complained of the noise,
	my husband spent weeks training him to press his paw on the latch to let himself in.
Rex soon became an expert at opening the gate.
However, when I was going out shopping last week, I noticed him in the garden near the gate.
This time he was barking so that someone would let him out!
Since then, he has developed another bad habit.
As soon as he opens the gate from the outside,
	he comes into the garden and waits until the gate shuts.
Then he sits and barks until someone lets him out.
After this he immediately lets himself in and begins barking again.
Yesterday my husband removed the gate and Rex got so annoyed we have not seen him since.

** words
bark [bɑːk] v.
press [pres] v.
paw [pɔː] n.
latch [lætʃ] n.
expert [ˈekspɜːt] n.
develop [dɪˈveləp] v.
habit [ˈhæbɪt] n.
remove [rɪˈmuːv] v.

sit - our front gate - bark
come into - bark - until
neighbours -  training to press - let in
expert - opening the gate
going out - notice - garden
barking - let in
since - develop - bad habit
opens - comes into - shuts
immediately - let in - begins barking
yesterday - remove - annoyed

** Pattern drill
1T: read the paper
S1: He's reading the paper, isn't he?
S2: Yes, he always reads the paper at this time of the day.
go to work
	He's going to work, isn't he?
	Yes, he always goes to work at this time of the day.

speak to his secretary
	He's speaking to his secretary, isn't he?
	Yes, he always speaks to his secretary at this time of the day.

dictate letters
	He's dictating letters, isn't he?
	Yes, he always dictates letters at this time of the day.

attend a meeting
	He's attending a meeting, isn't he?
	Yes, he always attends a meeting at this time of the day.

2T: play the piano
S1: She's playing the piano, isn't she?
S2: Yes, she's been playing the piano all morning.
Read - her library book
	She's reading her library book, isn't she?
	Yes, she's been reading her library book all morning.

Write - her report
	She's writing her report, isn't she?
	Yes, she's been writing her report all morning.

Work - in the library
	She's working in the library, isn't she?
	Yes, she's been working in the library all morning.

Do - a crossword
	She's doing a crossword, isn't she?
	Yes, she's been doing a crossword all morning.

3T: make films
S1: I was told that films were made here.
S2: They used to be made here, but they aren't any more.
grow tomatoes
	I was told that tomatoes were grown here.
	They used to be grown here, but they aren't any more.

sell tickets
	I was told that tickets were sold here.
	They used to be sold here, but they aren't any more.

build ships
	I was told that ships were built here.
	They used to be built here, but they aren't any more.

serve meals
	I was told that meals were served here.
	They used to be served here, but they aren't any more.

4T: stopped by the police
S1: You've taken your time! What on earth have you been doing?
S2: I'm sorry. We got stopped by the police.
Delayed - by fog
	You've taken your time! What on earth have you been doing?
	I'm sorry. We got delayed by fog.

Involved - in an accident
	You've taken your time! What on earth have you been doing?
	I'm sorry. We got involved in an accident.

Caught - in a storm
	You've taken your time! What on earth have you been doing?
	I'm sorry. We got caught in a storm.

Lost - on the way
	You've taken your time! What on earth have you been doing?
	I'm sorry. We got lost on the way.

** asking questions
1. Our dog is called Rex. What
	 What is your dog called?

2. He used to sit outside our front gate. Where/Why
	 Where did he use to sit?
	 Why did he use to sit outside our front gate?

3. He used to bark. What/Why
	 What did he use to do?
	 Why did he use to bark?

4. He'd bark until someone opened the gate. How long
	 How long would he bark?

5. The neighbours complained. Who
	 Who complained?

6. My husband spent weeks training Rex. How long/Who
	 How long did your husband spend?
	 Who spent weeks training Rex?

7. I noticed him near the gate. Where
	 Where did you notice her?

8. He was barking so that someone would let him out. What...doing/Why
	 What was he doing so that someone would let him out?
	 Why was he barking?

9. He's developed another bad habit. What else/Who
	 What else has he developed?
	 Who has developed another bad habit?

** Summary writing
Our dog, Rex, used to sit outside the front gate and bark so that someone would open the gate.
Ever since my husband trained him to open the gate himself, Rex has developed another bad habit.
When he is in the garden he barks so that someone lets him out.
After this he lets himself in and he barks until someone opens the gate again.
Now that my husband removed the gate, Rex has disappeared.

** Topics for discussion
1. Which animals make good/bad pets? Why?
	 Cats make good pets.
	 Cats are easy to be fed and they are often very quiet.

2. In what ways can animals be trained to be useful to men?
	 A dog helps police to search out the thieves.

3. Many people enjoy watching animals do tricks in circuses and seeing animals in cages in zoos.
	 Others say both are wrong. What is your opinion?
	 Both are wrong.
	 It's not free for them to live on the earth.

