#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 60 The future
#+begin_verse
Does what Madam Bellinsky said come true?

At a village fair, I decided to visit a fortune-teller called Madam Bellinsky.
I went into her tent and she told me to sit down.
After I had given her some money, she looked into a crystal ball and said:
'*A relation of yours* is coming to see you.
She will be arriving this evening and intends to stay for a few days.
The moment you leave this tent, you will get a big surprise.
A woman you know well will rush towards you.
She will speak to you	and then she will lead you away from this place.
That is all.'

As soon as I went outside,
	I forgot all about Madam Bellinsky because my wife hurried towards me.
'Where have you been hiding?' she asked impatiently.
'Your sister will be here in less than an hour and we must be at the station to meet her.
We are late already.'
As she walked away,	I followed her out of the fair.
#+end_verse
** expression
future [ˈfjutʃər] n.未来,前途
fair [fer] n.集市
fortune-teller [ˈfɔrtʃ(ə)n] n.算命人
crystal [ˈkrɪst(ə)l] n.水晶
relation [rɪˈleɪʃ(ə)n] n.亲属
impatiently [ɪmˈpeɪʃəntlɪ] adv.不耐烦的

in the future 在将来 
at a village fair 在一个乡村集市上
crystal clear 如水晶般清澈的
a relation of yours 你的一个亲戚

--------------------
A先B后
the moment A ... B...: 一A就B
	Everything stops the moment she walks in the room.
as soon as(主将从现): 一A就B(主从都表将来时,从句用现在时即可)
	As soon as the rain stops, we shall go out.
主将从现: 主从都表将来时,从句用现在时即可
	the moment/util/when/as soon as/while/before



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
