* L60 The future
Does what Madam Bellinsky said come true?

At a village fair, I decided to visit a fortune-teller called Madam Bellinsky.
I went into her tent and she told me to sit down.
After I had given her some money, she looked into a crystal ball and said:
'A relation of yours is coming to see you.
She will be arrriving this evening and intends to stay for a few days.
The moment you leave this tent, you will get a big surprise.
A woman you know well will rush towards you.
She will speak to you and then she will lead you away from this place.
That is all.'

As soon as I went outside, I forgot all about Madam Bellinsky because my wife hurried towards me.
'Where have you been hiding?' she asked impatiently.
'Your sister will be here in less than an hour and we must be at the station to meet her.
We are late already.'
As she walked away, I followed her out of the fair.

** words
future [ˈfjuːtʃə(r)] n.
fair [feə(r)] n.
fortune-teller n.
crystal [ˈkrɪst(ə)l] n.
relation [rɪˈleɪʃ(ə)n] n.
impatiently [ɪmˈpeɪʃntli] adv.

** Pattern Drill
1T: dinner - visiting Mary
S1: Can you come to dinner tonight?
S2: I'm sorry. I'm visiting Mary this evening.
the theatre - working late
	Can you come to the theatre tonight?
	I'm sorry. I'm working late this evening.

the lecture - watching TV
	Can you come to the lecture tonight?
	I'm sorry. I'm watching TV this evening.

the cinema - staying at home
	Can you come to the cinema tonight?
	I'm sorry. I'm staying at home this evening.

supper - meeting a friend
	Can you come to supper tonight?
	I'm sorry. I'm meeting a friend this evening.

2T: return
S1: He's returning soon, isn't he?
S2: Yes, he's returning in two days' time.
play in a concert
	He's playing in a concert, isn't he?
	Yes, he's playing in two days' time.

appear on TV
	He's appearing on TV, isn't he?
	Yes, he's appearing in two days' time.

catch a plane
	He's catching a plane, isn't he?
	Yes, he's catching a plane in two days' time.

make a speech
	He's making a speech, isn't he?
	Yes, he's making a speech in two days' time.

3T: clean his room
S1: He's coming home this evening. Have you cleaned this room?
S2: I'll clean it before he comes.
make his bed
	He's coming home this evening. Have you made his bed?
	I'll make it before he comes.

prepare a meal
	He's coming home this evening. Have you prepared a meal?
	I'll prepare it before he comes.

make a fire
	He's coming home this evening. Have you made a fire?
	I'll make it before he comes.

wash his shirt
	He's coming home this evening. Have you washed his shirt?
	I'll wash it before he comes.

4T: tired on arriving - look after her
S1: She'll be tired when she arrives.
S2: I'll look after her if she's tired.
angry on seeing the mess - calm her down
	She'll be angry on seeing the mess.
	I'll calm her down if she's angry.

sad on learning the news - comfort her
	She'll be sad on learning the news.
	I'll comfort her if she's sad.

hungry on returning - give her a meal
	She'll be hungry on returning.
	I'll give her a meal if she's hungry.

nervous on meeting you - be kind to her
	She'll be nervous on meeting you.
	I'll be kind to her if she's nervous.

** Asking questions
1. I went to a village fair. Where
	 Where did you go?

2. I visited a fortune-teller. Who
	 Who did you visit?

3. She was called Madam Bellinsky. What
	 What was she called?

4. I went into her tent. Where
	 Where did you go?

5. She told me to sit down. What/Who
	 What did she tell you?
	 Who told you to sit down?

6. I gave her some money. What/When
	 What did you give her?
	 When did you give her some money?

7. She looked into a crystal ball. What
	 What did she look into?

8. She told me my fortune. What
	 What did she told you?

9. A relation of mine was coming to see me. Who/When
	 Who was coming to see you?
	 When was a relation of yours coming to see you?

10. She would be arriving that evening. When
		When would she be arriving?

11. She intended to stay for a few days. How long/Where/Who
		How long did she intend to stay?
		Where did she intend to stay for a few days?
		Who intented to stay for a few days?

12. I'd get a big surprise. Who/When
		Who would get a big surprise?
		When would you get a big surprise?

** Summary writing
The writer visited a fortune-teller at a village fair
	who told him that a relation was coming to see him.
She added that a woman he knew well would speak to him when he left the tent
	and he would follow her out of the fair.
This came true because his wife spoke to him when he went outside.
She told him they had to meet his sister at the station and she led him out of the fair.

** Topics for discussion
1. Have you ever had your fortune told?
	 Describe the experience.
	 No, but my father have had his fortune told.
	 A fortune-teller told him that he would be very lazy when he grew up.
	 In fact, my father is not lazy.

2. When and why do people have fairs in your part of the country?
	 Describe one you have been to recently.
	 When the last number of days is 2 5 and 8, people used to have fairs at my village.
	 They sold goods at the village fair.

3. Do you believe that some people can really foretell the future? Why/Why not?
	 No, I don't.
	 Instead of believing in fortune-tellers, I believe in science.

