* L61 Trouble with the Hubble
What is the special importance of a telescope in space?

The Hubble telescope was lanuched into space by NASA on April 20, 1990
	at a cost of over a billion dollars.
Right from the start there was trouble with the Hubble.
The pictures it sent us were very disappointing because its main mirror was faulty!
NASA is now going to put the telescope right,
	so it will soon be sending up four astronauts to repair it.
The shuttle Endeavour will be talking the astronauts to the Hubble.
A robot-arm from the Endeavour will grab the telescope
	and hold it while the astronauts make the necessary repairs.
Of course, the Hubble is above the earth's atmosphere,
	so it will soon be sending us the clearest pictures of the stars and
	distant galaxies that we have ever seen.
The Hubble will tell us a great deal about the age and size of the universe.
By the time you read this, the Hubble's eagle eye will have sent us
	thousands and thousands of wonderful pictures.

Hubble telescope - lanuched - dollars
right - trouble - Hubble
pictures - disappointing - mirror
NASA - put - send up to repair
shuttle Endeavour - taking - astronauts
robot-arm - grab - hold - necessary repairs
above the earth's atmosphere - sends us - have ever seen
a great deal about age and size of universe
Hubble's eagle eye will have sent us KK wonderful pictures.
	
** words
Hubble [ˈpaʊəl] n.
telescope [ˈtelɪskəʊp] n. 望远镜
launch [lɔːntʃ] v. 发射
space [speɪs] n.
NASA [ˈnæsə] (National Aeronautics and Space Administration) n.
billion [ˈbɪljən] n.
faulty [ˈfɔːlti] adj. 有错误的
astronaut [ˈæstrənɔːt] n. 宇航员
shuttle [ˈʃʌt(ə)l] n. 航天飞机
endevour n. 奋进号
robot-arm n. 机器手
grab [ɡræb] v. 抓
atmosphere [ˈætməsfɪə(r)] n.
distant [ˈdɪstənt] adj.
galaxy [ˈɡæləksi] n.
universe [ˈjuːnɪvɜːs] n.
eagle [ˈiːɡ(ə)l] eye 

** Pattern Drill
will be doing
will have done
will have been doing

1T: making boats - a year
S1: Have you been making boats for long?
S2: By the time I've completed this one, I'll have been making them for a year.
designing bridges - ten years
	Have you been designing bridges for long?
	By the time I've completed this one, I'll have been designing them for a year.

writing books - six years
	Have you been writing books for long?
	By the time I've complete this one, I'll have been writing them for a year.

directing films - two years
	Have you been directing films for long?
	By the time I've completed this one, I'll have been directing them for a year.

producing plays - five years
	Have you been producing plays for long?
	By the time I've completed this one, I'll have been producing them for a year.

2T: make hats - thirteen
S1: How many hats have you made now?
S2: When I've made this one, I'll have made thirteen altogether.
do exercises - twenty
	How many exercises have you done now?
	When I've done this one, I'll have done thirteen altogether. 

build bridges - five
	How many bridges have you built now?
	When I've built this one, I'll have built thirteen altogether.

write novels - eight
	How many novels have you writen now?
	When I've writen this one, I'll have writen thirteen altogether.

review books - twelve
	How many books have you reviewed now?
	When I've reviewed this one, I'll have reviewed thirteen altogether.

3T: arrive - get lunch
S1: John'll be arriving soon.
S2: Let me know when he arrives. Then I'll get lunch.
return - get dressed
	John'll be returning soon.
	Let me know when he returns. Then I'll get dressed.

get up - cook breakfast
	John'll be getting up soon.
	Let me know when he gets up. Then I'll cook breakfast.

leave - come and see you
	John'll be leaving soon.
	Let me know when he leaves. Then I'll come and see you.

come back - borrow his car
	John'll be coming back soon.
	Let me know when he comes back. Then I'll borrow his car.

4T: post my letter - write
S1: When shall I post my letter?
S2: You can post it as soon as you've written it!
eat the cakes - make
	When shall I eat the cakes?
	You can eat it as soon as you've made it!

publish these reports - write
	When shall I publish these reports?
	You can publish them as soon as you've write them.

sell my bicycle - mend
	When shall I sell my bicycle?
	You can sell it as soon as you've mend it.

cook the fish - wash
	When shall I cook the fish?
	You can cook it as soon as you've washed it.

** Asking questions
1. The Hubble telescope was launched into space. What
	 What was launched into space?

2. The cost was over a billion dollars. How much
	 How much was the cost?

3. There was trouble right from the start. When
	 When was there trouble?

4. The pictures were very disappointing. Why
	 Why were the pictures very disappointing?

5. NASA will put the telescope right. How
	 How will NASA put the telescope right?

6. Four astronauts will be sent up to repair it. How many
	 How many astronauts will be sent up to repair it?

7. Endevour will take them into space. What
	 What will take them into space?

8. A robot-arm will grab the telescope. What
	 What will grab the telescope?

9. The Hubble is above the earth's atmosphere. Where
	 Where is the Hubble?

10. The Hubble will tell us about the age and size of the universe. What
		What will the Hubble tell us?

** Summary writing
When the Hubble telescope was launched into space on April 20 1990,
	the pictures it sent us were very disappointing,
	because its main mirror was faulty.
The four astronauts from the shuttle Endevour will be repairing the telescope
	and eventually the pictures from the Hubble
	will tell us a great deal about the age and size of the univerise.

** Topics for discussion
1. How much do you know about the universe?
	 The earth is a star.
	 The earth is a part of Galaxy.
	 The Galaxy is part of the universe.

2. Do you enjoy following the news about space exploration?
	 It's diffuilt for me who must work hard for the farm to enjoy following the news.

3. Are there any areas of modern science that interest you more?
	 If so, what are they, and why?
	 Computer science.
	 There is another world in Computer science.
	 I find it fantastic.

