#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 62 After the fire
#+begin_verse
What was the danger to the villagers after the fire?

Firemen had been fighting the forest fire for nearly three weeks
	before they could *get it under control*.
*A short time before*, great trees had covered the countryside *for miles around*.
Now, smoke still rose up from the warm ground over the desolate hills.
Winter was coming on and the hills threatened the surrounding villages with destruction,
	for heavy rain would not only wash away the soil
		but would cause serious floods as well.
When the fire had at last been put out,
	the forest authorities ordered several tons of a special type of grass-seed
		which would grow quickly.
The seed was sprayed over the ground in huge quantities by aeroplanes.
The planes had been planting seed for nearly a month when it began to rain.
By then, however, in many places the grass had already *taken root*.
*In place of* the great trees which had been growing there *for centuries*,
	patches of green had begun to appear in the blackened soil.
#+end_verse
** expression
control [kənˈtroʊl] n.控制
smoke [smoʊk] n.烟
desolate [ˈdesələt] adj.荒凉的
threaten [ˈθret(ə)n] v.威胁
surrounding [səˈraʊndɪŋ] adj.周围的
destruction [dɪˈstrʌkʃ(ə)n] n.破坏,毁灭
flood [flʌd] n.洪水,水灾
authority [ɔˈθɔrəti] n.(常用复数)当局
grass-seed [ɡræs] [sid] n.草籽
spray [spreɪ] v.喷撒
quantity [ˈkwɑntəti] n.量
root [rut] n.根
century [ˈsentʃəri] n.世纪
patch [pætʃ] n.小片
blacken [ˈblækən] v.变黑,发黑

get it under control 控制住它
be under control 得到控制
threaten sb. with sth. 用某事威胁某人
threaten to do sth. 威胁要做某事
have the authority to do sth. 有权力做某事
a large/small quantity of sth. 大量/少量的某物(nu.&nc.)
take root 生根
for centuries 几个世纪以来
a part of sth. 某物的一部分

--------------------
had been doing: 1.过去A进行的v.对过去B有影响;2.过去A进行的v.持续(重复)到过去B

A short time before 不久之前
for miles around 方圆数英里
in place of... 代替……



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
