* L62 After the fire
What was the danger to the villagers after the fire?

Firemen had been fighting the forest fire for nearly three weeks
	before they could get it under control.
A short time before, great trees had covered the countryside for miles around.
Now, smoke still rose up from the warm ground over the desolate hills.
Winter was coming on and the hills threatened the surrounding villages with destruction,
	for heavy rain would not only wash away the soil but would cause serious floods as well.
When the fire had at last been put out,
	the forest authorities ordered several tons of a special type of grass-seed
	which would grow quickly.
The seed was sprayed over the ground in huge quantities by aeroplanes.
The planes had been planting seed for nearly a month when it began to rain.
By then, however, in many places the grass had already taken root.
In place of the great trees which had been growing there for centuries,
	patches of green had begun to appear in the blackened soil.

	
** words
control [kənˈtrəʊl] n.
smoke [sməʊk] n.
desolate [ˈdesələt] adj. 荒凉的
threaten [ˈθret(ə)n] v. 威胁
surrounding [səˈraʊndɪŋ] adj.
destruction [dɪˈstrʌkʃ(ə)n] n. 破坏,毁灭
flood [flʌd] n. 水灾
authority [ɔːˈθɒrəti] n.
grass [ɡrɑːs]-seed n.
spray [spreɪ] v. 喷撒
quantity [ˈkwɒntəti] n.
root [ruːt] n.
century [ˈsentʃəri] n.
patch [pætʃ] n. 小片
blacken [ˈblækən] v.

** Pattern drill
1T: this afternoon - working
S1: What was Tom's excuse for being late this afternoon?
S2: He said he'd been working.
last night - reading
	What was Tom's excuse for being late last night?
	He said he'd been reading.

for lunch - teaching
	What was Tom's excuse for being late for lunch?
	He said he'd been teaching.

this evening - writing
	What was Tom's excuse for being late this evening?
	He said he'd been writing.

for the meeting - painting
	What was Tom's execues for being late the meeting?
	He said he'd been painting.

2T: anxious - thinking about the exams
S1: Mary looked very anxious this morning.
S2: I know. She'd been thinking about the exams.
worried - worrying about her son
	Mary looked very worried this morning.
	I know. She'd been worrying about her son. 

tired - working all night
	Mary looked very tired this morning.
	I know. She'd been working all night.

angry - arguing with John
	Mary looked angry this morning.
	I know. She'd been arguing with John.

dirty - cleaning out the shop
	Mary looked dirty this morning.
	I know. She'd been cleaning out the shop.

3T: finish the job
S1: Did the men finish the job this morning?
S2: Yes, they'd already finished it  when I arrived.
repair the pipes
	Did the men repair the pipes this morning?
	Yes, they'd already repaired them when I arrived.

spray the trees
	Did the men spray the trees this morning?
	Yes, they'd already sprayed them when I arrived.

hang the pictures
	Did the men hang the pictures this morning?
	Yes, they'd already hung them when I arrived.

plant the seeds
	Did the men plant the seeds this morning?
	Yes, they'd already planted them when I arrived.

** Asking questions
1. There was a forest fire recently. When
	 When was there a forest fire?

2. Firemen fought it for nearly three weeks. How long/ What/ Who
	 How long did firemen fight it?
	 What did firemen fight for nearly three weeks?
	 Who fought it for nearly three weeks?

3. There had been great trees for miles around. Where/What
	 Where had there been great trees?
	 What had there been for miles around?

4. They'd covered the countryside. What
	 What had they covered?

5. The hills were now desolate. What
	 What were now desolate?

6. Smoke still rose up from the warm ground. What
	 What did smoke still rise up from?

7. Winter was coming on. What
	 What was coming on?

8. The villages surrounding the hills were threatened. Which/Why
	 Which villages were threatened?
	 Why were the villages surrounding the hills threatened?

9. Heavy rain would wash away the soil from the hills. What
	 What would heavy rain wash away?
	 
** Summary writing
It took the firemen nearly three weeks to get the forest fire under control.
Now that all the great trees had been burnt,
	there was danger that heavy rain would cause serious floods
	which would destory the surrounding villages.
To prevent this, the forest authorities ordered grass-seed
	which was sprayed over the ground for nearly a month by planes.
By the time that it begun to rain, the grass had taken root in many places.

** Topics for discussion
1. Why are trees so important to industry, the countryside, animals and peole?
	 Many machine was made of wood and metal.
	 Villager need to feed their poultry.
	 Animals live in the forest.
	 The trees are reducing pollution.

2. Describe some of the ways in which land can be protected against flooding.
	 Spray the grass-seed.
	 Plant the trees.
	 Make dams.

3. Aeroplanes are now widely used for spraying insecticides, etc.
	 What are the advantages and disadvantages of this?
	 This is the sort of things that villagers love.
	 However, a number of people insist that it would cause pollution.
