* L64 The Channel Tunnel
Why was the first tunnel not completed?

In 1858, a French engineer, Aime Thome de Gamond,
	arrived in England with a plan for a twenty-one-mile tunnel under the English Channel.
He said that it would be possible to build a platform in the centre of the Channel.
This platform would serve as a port and a railway station.
The Tunnel would be well-ventilated if tall chimneys were built above sea level.
In 1860, a better plan was put forward by an Englishman, William Low.
He suggested that a double railway-tunnel should be built.
This would solve the problem of ventilation,
	for if a train entered this tunnel, it would draw in fresh air behind it.
Forty-two years later a tunnel was actually begun.
If, at the time, the British had not feared invasion, it would have been completed.
The world had to wait almost another 100 years for the Channel Tunnel.
It was officially opened on March 7, 1994, finally connecting Britian to the European continent.

In 1858 - arrive - tunnel
said - possible - centre
serve - port - railway station
Tunnel - well-ventilated - chimneys
better plan - put forward - Englishman
solve - ventilation - draw in
Forty-two year later
at the time - feared invasion - completed
another 100 years - the Channel Tunnel
officially - March 7, 1994, connecting continent

** words
tunnel [ˈtʌn(ə)l] n. 隧道
port [pɔːt] n. 港口
ventilate [ˈventɪleɪt] v. 通风
chimney [ˈtʃɪmni] n. 烟囱
sea level 海平面
ventilation [ˌventɪˈleɪʃn] n. 通风
fear [fɪə(r)] v. 害怕
invasion [ɪnˈveɪʒ(ə)n] n. 入侵
officially [əˈfɪʃəli] adv. 正式地
European [ˌjʊərəˈpiːən] adj. 欧洲的
continent [ˈkɒntɪnənt] n. 大陆的

** Pattern drill
1T: meet John - like
S1: What a pity they couldn't meet John!
S2: Yes, I'm sure they'd liked him very much if they had met him.
see the play - enjoy
	What a pity they couldn't see the play!
	Yes, I'm sure they'd enjoyed it very much if they had seen it.

visit the museum - enjoy
	What a pity they couldn't visit the museum!
	Yes, I'm sure they'd enjoyed it very much if they had visited it.

hear his lecture - like
	What a pity they couldn't hear his lecture!
	Yes, I'm sure they'd liked it very much if they had heard it.

try her cooking - like
	What a pity they couldn't try his cooking!
	Yes, I'm sure they'd liked it very much if they had tried it.

2T: made a mistake - listened to me
S1: She's made a mistake
S2: She wouldn't have made a mistake if she'd listened to me.
broken her arm - been more careful
	She broke her arm.
	She wouldn't have broken her arm if she'd been more careful.

lost her watch - mended the strap
	She lost her watch.
	She wouldn't have lost her watch if she'd mended the strap.

failed the exam - worked harder
	She failed the exam.
	She wouldn't have failed the exam if she'd worked harder.

lost her job - taken my advice
	She lost her job.
	She wouldn't have lost her job if she'd taken my advice.

3T: work hard - pass the exam
S1: He had to work hard to pass the exam.
S2: Yes, he wouldn't have passed it if he hadn't worked so hard.
drive carefully - avoid an accident
	He had to drive carefully to avoid an accident.
	Yes, he wouldn't have avoided an accident if he hadn't driven carefully.

look hard - find the money
	He had to look hard to find the money.
	Yes, he wouldn't have found the money if he hadn't looked hard.

run fast - catch the thief
	He had to run fast to catch the thief.
	Yes, he wouldn't have caught the thief if he hadn't ran fast.

fight hard - win the title
	He had to fight hard to win the title.
	Yes, he wouldn't have won the title if he hadn't fought hard.

4T: speak to John - find
S1: Why didn't you speak to John yesterday?
S2: I'd have spoken to him if I could've found him!
enjoy the lecture - understand
	Why didn't you enjoy the lecture yesterday?
	I'd have enjoyed it if I could've understood it!

arrest the thief - catch
	Why didn't you arrest the thief yesterday?
	I'd have arrested the thief if I could've caought it!

read the book - keep
	Why didn't you read the book?
	I'd have read the book if I could've kept it.

search the house - enter
	Why didn't you search the house?
	I'd have searched the house if I could'v entered it.

** Asking questions
1. Aime Thome de Gamond was French. What nationality
	 What nationalit was Aime Thome de Gamond?

2. He was an engineer. What/Who
	 What job was he?
	 Who was an engineer?

3. He came to England in 1858. When
	 When did he come to England?

4. He had a plan for a tunnel. What ... for
	 What did he have a plan for?

5. It would be twenty-one miles long. How long
	 How long would it be?

6. It would cross the English Channel. What
	 What would it cross?

7. A platform could be built in the centre of the Channel. Where/What
	 Where could a platform be built?
	 What could be built in the centre of the Channel?

8. The platform would serve as a port. What
	 What would the platform would serve as?

9. It would also serve as a railway station. What else
	 What else would it als serve as?

10. Ventilation would be a problem. What
		What would be a problem?

** Summary writing
The tunnel which was planned to build by a French engineer under the English Channel in 1858
	would be ventilated, if tall chamneys were build above sea level.
The tunnel,
	which the French engineer, Aime Thome, planned to build under the English Channel in 1858,
	would be ventilated by tall chimneys built above sea level.
An English man, Willam low, suggested a better plan two years later.
Passing trains would solve the problem of ventilation in his proposed double railway-tunnel
	because they would draw in fresh air bebind them.
Though work began forty-two years later, it was stopped because the Britian feared invasion.
However, the Channel Tunnel was officially opened on March 7, 1994.
	
** Topics for discussion
1. What are the advantages/disadvantages of living in a country surrounded by the sea?
	 Air temperature rarely changes a lot.
	 The businesses are conventient.

2. Would you like to travel twenty-one miles through a tunnel under the sea? Why/Why not?
	 Yes, I would.
	 The moment I read the story, I believed in the tunnel as mystery.
	 What a great tunnel it is.

3. What, in your opinion,
	 are the advantages to Britain and continental Europe of the Channel Tunnel?
	 The Britain feared invasion.
	 It will be more conventient for the Britain to make friends.
