#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 65 Jumbo versus the police
#+begin_verse
Why did the police have to push Jumbo off the main street?

Last Christmas, the circus owner, Jimmy Gates,
	decided to take some presents to a children's hospital.
*Dressed up as* Father Christmas and accompanied by a 'guard of honour' of six pretty girls,
	he *set off* down the main street of the city riding a baby elephant called Jumbo.
He should have known that the police would never allow this sort of thing.
A policeman approached Jimmy and told him he ought to have gone along a side street
	as Jumbo was *holding up the traffic*.
Though Jimmy *agreed to go* at once, Jumbo refused to move.
Fifteen policemen had to push very hard to get him off the main street.
The police had a difficult time, but they were most amused.
'Jumbo must weigh a few tons,' said a policeman afterwards,
	'so *it was fortunate that* we didn't have to carry him.
Of course, we should arrest him,
	but as he has a good record, we shall *let him off* this time.'
#+end_verse
** expression
versus [ˈvɜrsəs] prep.对
Christmas [ˈkrɪsməs] n.圣诞节
circus [ˈsɜrkəs] n.马戏团
present [ˈprezənt] n.礼物
accompany [əˈkʌmpəni] v.陪伴,随行
approach [əˈproʊtʃ] v.走进
ought [ɔt] modal verb.应该
weigh [weɪ] v.重
fortunate [ˈfɔrtʃənət] adj.幸运的

How much do you weigh? 你体重多少
It is fortunate that + 句子... 很幸运的是...

--------------------
should do/ought to do: 肯应该,否不应该
should have done/ought to have done: 本该做某事,却没有做,指责效果

be dressed up as... 打扮成……
set off 出发
hold up the traffic/line 阻塞交通
let sb. off 不惩罚某人
agreed to do sth. 同意做某事



** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
