* Lesson 65 Jumbo versus the police
Why did the police have to push Jumbo off the main street?

Last Christmas, the circus owner, Jimmy Gates,
	decided to take some presents to a children's hospital.
Dressed up as Father Christmas and accompanied by a 'guard of honour' of six pretty girls,
	he set off down the main street of the city riding a baby elephant called Jumbo.
He should have known that the police would never allow this sort of thing.
A policeman approached Jimmy and told him ought to have gone along a side street
	as Jumbo was holding up the traffic.
Though Jimmy agreed to go at once, Jumbo refused to move.
Fifteen police had to push very hard to get him off the main street.
The police had a difficult time, but they were most amused.
'Jumbo must weigh a few tons,' said a policeman afterwards,
	'so it was fortunate that we didn't have to carry him.
Of course, we should arrest him,
	but as he has a good record,
	we shall let him off this time.'

** words
versus prep. 对
Christmas n.
circus n. 马戏团
present n.
accompany v. 伴随
approach v. 走近
ought modal(情态) verb 应该
weigh v.
fortunate adj.

** Patter drill
1T: write that letter
S1: Do you have to write that letter now?
S2: I ought to write it, but I'm not going to!
prepare your speech
	Do you have to prepare your speech now?
	I ought to prepare it, but I'm not going to!
light the fire
	Do you have to light the fire now?
	I ought to write it, but I'm not going to!
do your homework
	Dou you have to do your homework now?
	I ought to do it, but I'm not going to!
burn the rubbish
	Do you have to burn the rubbish now?
	I ought to burn it, but I'm not going to!

2T: apologize
S1: Do you think he should apologize?
S2: It doesn't matter who apologizes, but someone's got to!
stay here
	Do you think he should stay here?
	It doesn't matter who stays here, but someone's got to!
pay them
	Do you think he ought to pay them?
	It doesn't matter who pays them, but someone's got to!
make a speech
	Do you think he should make a speech?
	It doesn't matter who makes it, but someone's got to!
finish the job
	Do you think he should finish the job?
	It doesn't matter who finishes it, but someone's got to!

3T: take a taxi
S1: Why didn't you take a taxi last night?
S2: I know I should have taken one, but I didn't think of it at the time.
wear a hat
	Why didn't you wear a hat last night?
	I know I should have weared one, but I didn't think of it at the time.
call on the Smiths
	Why didn't you call on the Smiths?
	I know I should have called on them, but I didn't think of it at the time.
book some seats
	Why didn't you book some seats?
	I know I should have book some, but I didn't think of it at the time.
ring the police
	Why didn't you ring the police?
	I know I should have rung them, but I didn't think of it at the time.

4T: arrive
S1: He ought to have arrived by now.
S2: He had to change his plans, but he should be arriving soon.
return
	He ought to have returned by now.
	He had to change his plans, but he should be returning soon.
phone us
	He ought to have phoned us by now.
	He had to change his plans, but he should be phoning us soon.
buy the goods
	He ought to have bought the goods by now.
	He had to change his plans, but he should be buying the goods soon.
	
** Asking questions
1. Jimmy Gates is a circus owner. Who
	 Who is a circus owner?

2. He decided to take some presents to a children's hospital last Christmas. When
	 When did he decide to take some presents to a children's hopspital?

3. He dressed up as Father Christmas. What
	 What did he dress up as?

4. He was accompanied by six pretty girls. How many/ Who...by
	 How many girls was he accompanied by?
	 Who was accompanied by six pretty girls?

5. They were his 'guard of honour'. What
	 What were his 'guard of honour'?

6. He set off down the main street of the city. Which way
	 Which way did he set off down?

7. He was riding a baby elephant. What
	 What was he riding?

8. The elephant was called Jumbo. What
	 What was the elephant called?

9. A policeman approached them. Who
	 Who approached them?

10. He told Jimmy that Jumbo was holding up the traffic. What
		What did he tell Jimmy?
		
** Summary writing
After having decided to take some presents to a chilren's hospital,
	the circus owner, Jimmy Gates, dressed up as a Santa and
	set off down the main street of the city riding an elephant called Jumbo.
On being told that he was holding up the traffic,
	Jimmy agreed to go at once but Jumbo refused to move,
	so fifteen policeman had to push him off the main street.
As he had a good record, however, Jumbo was not arrested.

** Topics for discussion
1. When have you seen a procession in the streets? Describe it.
	 When I was very young, I saw the po fighting a villager at a village fair.
	 "The po were fighting us!" a uncle shout loudly.
	 In the end, many villagers gathered round and the po let him off.

2. Have you ever been to a circus? Which act did you enjoy most? Why?
	 No.
	 I enjoy emperor most! Because I will have lots of power.

3. Are there any traffic problems where you live? Can you suggest any way to solve them?
	 The road was often holding up by some trucks.
	 I suggest that our gov enlarge the road.
