* L67 Volcanoes
Why does Tazieff risk his life like this?

Haroun Tazieff, the Polish scientist,
	has spent his lifetime studying active volcanoes and deep caves in all parts of the world.
In 1948, he went to Lake Kivu in the Congo to observe a new volcano which he later naemed Kituro.
Tazieff was able to set up his camp very close to the volcano while it was erupting violently.
Though he managed to take a number of brilliant photographs,
	he could not stay near the volcano for very long.
He noticed that a river of liquid rock was coming towards him.
It threatened to surround him completely, but Tazieff managed to escape just in time.
He waited until the volcano became quiet and he was able to return two days later.
This time, he managed to climb into the mouth of Kituro
	so that he could take photographs and measure temperatures.
Tazieff has often risked his life in this way.
He has been able to tell us more about active volcanoes than any man alive.

** words
volcano [vɒlˈkeɪnəʊ] n. 火山
active [ˈæktɪv] adj. 活动的
Kivu ['ki:vu:]
Congo
Kituro [nil] n.
erupt [ɪˈrʌpt] v. 喷发
violently [ˈvaɪələntli] adv. 剧烈地
manage [ˈmænɪdʒ] v.
brilliant [ˈbrɪliənt] adj. 精彩的
liquid [ˈlɪkwɪd] adj. 液态的
escape [ɪˈskeɪp] v. 逃脱
alive [əˈlaɪv] adj. 活着

** Asking questions
1. He has spent hislife time studying active volcanoes and deep caves? What/Who
	 What has he spent his lifetime doing?
	 Who has spent his lifetime studying active volcanoes and deep caves?
	 
2. In 1948, he went to Lake Kivu in the Congo. Where/Why/When
	 Where did he go in the Congo in 1948?
	 Why did he go to Lake Kivu in the Congo in 1948?
	 When did he go to Lake Kivu in the Congo?

3. Tazieff was able to set up his camp very close the volcano. Where/What
	 Where was Tazieff able to set up his camp?
	 What was Tazieff able to do?

4. He managed to take a number of brilliant photographs. What/How many
	 What did he manage to do?
	 How many brilliant photographs did he manage to take?

5. He could not stay near the volcano for very long. Why
	 Why couldn't he stay near the volcano for very long?

6. He noticed that a river of liquid  rock was coming towards him. What
	 What did he notice?

7. It threatened to surround him completely. How
	 How did it threaten to surround him?

8. He waited until the volcano became quiet. When
	 When did he wait?

9. He managed to climb into the mouth of Kituro. Where
	 Where did he manage to climb into?

10. Tazieff has often risked his life in this way. How
		How has Tazieff often risked his life?

11. He has been able to tell us more about active volcanoes than any man alive. Who
		Who has been able to tell us more about active volcanoes than any man alive?
	 
** expressions
spend st. doing sth.
	1. He often spends his worktime studying English.
	2. My husband has spent the whole week training Leo to press his paw on the latch to let himself in.
	3. You have spent the whole afternoon hiding somewhere.
	4. It's a waste of time for you to spend every morning catching boots.
	5. He managed to spend weekends taking parties.

close to sw.
	1. I sat very close to the house.
	2. I used to sit very close to the teacher.
	3. Why don't you sit close to your parents?
	4. In the end, Leo held a meeting very close to Beijing.
	5. He often risks his life very close to active volcanoes.

managed to do sth.
	1. He managed to refuse to serve this rude customer.
	2. A large crowd of people managed to gather round in the square.
	3. He managed to get a good salary in a big farm.
	4. He managed to return it back in the deadline.
	5. The captain managed to sail across the Pacific.
in time
	1. He set out in time and wasn't late for the meeting.
	2. He took part in the race in time.
	3. The police managed to keep order in time.
	4. The kind man always replys to the email in time.
	5. Sorry to interrupt, but we have to set out in time.

risk sb's life
	1. If I was very close to the active volcano, I would risk my life.
	2. The robbery has often risked his life in this way.
	3. He used to risk his life to get a good salary, when he was very young.
	4. No one could account for the fact that he risked his life in this way.
	5. If you don't pay attention to the street sign, you will risk your life.
