#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 68 Persistent
#+begin_verse
Why did Elizabeth tell Nigel that she was going to the dentist?

I crossed the street to *avoid meeting* him, but he saw me and came running towards me.
*It was no use pretending that* I had not seen him, so I waved to him.
I never *enjoy meeting* Nigel Dykes.
He never has anything to do.
*No matter how* busy you are,	he always *insists on coming* with you.
I had to think of a way of *preventing him from following me around* all morning.

'Hello, Nigel,' I said.
'*Fancy meeting you here*!'

'Hi, Elizabeth,' Nigel answered.
'*I was just wondering* how to spend the morning -- until I saw you.'
'You're not busy doing anything, are you?'

No, not at all, I answered.
'I'm going to...'

'*Would you mind my coming* with you?' he asked, before I had *finished speaking*.

'Not at all,' I lied, 'but I'm going to the dentist.'

'Then I'll come with you,' he answered.
'There's always plenty to read in the waiting room!'
#+end_verse
** expression
persistent [pərˈsɪstənt] adj.坚持的,固执的
avoid [əˈvɔɪd] v.避开
insist [ɪnˈsɪst] v.坚持做
cross [krɔs] v. across [əˈkrɔs] prep. 穿过

avoid doing sth. 避免做某事
insist on doing sth. 坚持做某事
It is no use pretending that + sentence 假装...是没有用的
prevent sb. from doing sth. 阻止某人做某事;
Fancy meeting you here. 没想到在这遇见你
--------------------
no matter how/what/where/whose/who/which/when ?
even though(although/though/as) VS even if

enjoy doing sth. 享受做某事
no matter how/what/where 无论如何/什么/在哪里
follow sb. around 围绕某人转/走
I was wondering.. + sentence 我在想...
would you mind my doing... 你介意我做……吗?
finish doing sth. 完成做某事



** 单词造句
persistent adj.
- She is a persistent girl.
- A persistent girl insists on going to the concert.
- I want to avoid meeting the persistent girl.
- What a persistent girl.
- The persistent girl has made a big decision on the last day.
avoid v. avoid doing sth.
- The waiter avoided teaching me any words.
- The search party avoids holding up the traffic.
- If you bought it yesterday, we would avoid being hungry now.
- If you had bought it yesterday, we would have avoided being hungry.
- You should have avoided smoking in the theater.
insist v. insist on doing sth.
- He insists on naming the lake Kituro.
- He insisted on making a speech, even though he noticed that he had made so many mistakes.
- He insisted on removing the tyre from the new car.
- He insisted on pointing out my mistakes, even though I was crying.
- He insisted on telling lies when Rachel had already known it.
cross v. across prep.
- I crossed the street to avoid meeting him.
- I crossed the street to seek out the thief.
- After you have arrived, she crosses the field to go for a walk.
- She used to live across the street.
- She has regretted moving to the house.
It is no use pretending that + sentence
- It is no use pretending that you work hard.
- It is no use pretending that you win every time.
- It is no use pretending that there is a party on the other side of the river.
- It is no use pretending that you don't fall in love with me.
- It is no use pretending that you haven't had breakfast.
prevent sb. from doing sth.
- I am always preventing my wife from buying new clothes.
- I always prevent my wife from buying new clothes.
- I succeeded in preventing my wife from running into serious trouble.
- Rachel has prevented Ross from catching the flight.
- He is always preventing his friends from shaking his hands.
Fancy meeting you here.
- Hey. Fancy meeting you here.

** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
enjoy doing sth.
- I enjoy watching the movie very much.
- I enjoyed getting up early today.
- Just then, the little girl enjoyed taking an elevator.
- Do you enjoy having breakfast?
- He enjoys his own telephone service very much.
no matter how/what/where
- No matter how angry his son was, he insisted on drinking a lot every day.
- No matter what she has done, she still loves you.
- No matter where the theater is, she avoids going to it.
- No matter how beautiful the village is, he insists on preventing his wife from going to it.
- No matter whose umbrella it is, I sent it to my child.
follow sb. around
- Stop following me around.
- You are following me around the whole day.
- He prevents himself from following his boss around.
- After following the girl around all morning, he received a cold welcome.
- I was wondering if you have been following me around all evening.
I was wondering.. + sentence
- I was wondering: what's wrong with you?
- I was wondering: It's none of your business.
- I was wondering: how to become a fluent speaker.
- I was wondering if the Greenwood boys will give five performances.
- I was wondering which songs I should listen to.
would you mind my doing...
- Do you mind my opening the window?
- Would you mind my smoking here?
- Would you mind my getting the remote control?
- Would you mind his talking loudly?
- Would you mind his leaving a message?
finish doing sth.
- I have already finished doing my homework.
- I finished studying the textbook, New Concept English.
- She has finished cooking dinner.
- Mr. Leo finishes explaining the reason to everyone.
- He finishes breaking the record.
** 跟读至背诵
** Ask me if 写+读
1. I saw Nigel Dykes coming towards me.(Who)
	 Who did you see coming towards you?
2. I crossed the street.(When)
		When did you cross the street?
3. I crossed the street to avoid meeting him.(What...do)(Why)
		What did you do?
		Why did you cross the street to avoid meeting him?
4. He saw me.(Who)
		Who saw you?
5. He came running towards me.(Who)
		Who came running towards you?
6. I waved to him.(Who...to)
	 Who did you wave to?
7. I don't enjoy meeting Nigel.(Why)
	 Why don't you enjoy meeting Nigel?
8. He always follows people around.(Who)
	 Who always follows people around?
9. I said, Hello, Nigel.(What)
	 What did you say?
10. I said I was going to the dentist.(What)(Where)
		What did you say?
		Where did you say you were going?
11. There's always plenty to read in the waiting room.(What)(Where)
		What is there in the waiting room?
		Where is there always plenty to read?
** 摘要写作
Even though Elizabeth tried to avoid meeting Nigel Dykes, she wasn't able to do so.
As he always insisted on accompanying her,
	she had to think of a way of preventing him from following her around all morning.
When she told him she was going to the dentist,
	he said he would come with her because there's always plenty to read in the waiting room.

** DONE tell the story 口语
CLOSED: [2023-09-16 Sat 15:55]
** Topics for discussion
What sort of people do you try to avoid? Why?
	I try to avoid some people who get angry easily.
	If someone is mad at me, I can't bear it.
What method would you use to try to avoid
	(a) meeting someone you didn't like
	or (b) doing something you didn't want to do?
	a. Because I always prevent myself from doing something I don't want to do.

If you didn't have to work for a living, would you work anyway? Why/ Why not?
	No, I didn't.
	If I didn't have to work for a living, I would spend time studying. 
