#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 73 The record-holder
#+begin_verse
Did the boy go where he wanted to?

Children who *play truant from school* are unimaginative.
A quiet day's fishing, or eight hours in a cinema seeing the same film *over and over again*,
	is usually as far as they get.
They have all *been put to shame* by a boy who, while playing truant, travelled 1,600 miles.
He *hitchhiked to Dover* and, towards evening, went into a boat to find somewhere to sleep.
When he woke up next morning,
	he discovered that the boat had, *in the meantime*, travelled to Calais.
No one noticed the boy as he crept off.
From there, he hitchhiked to Paris in a lorry.
The driver gave him a few biscuits and a cup of coffee and left him just outside the city.
The next car the boy stopped did not take him into the centre of Paris as he hoped it would,
	but to Perpignan on the French-Spanish border.
There he was picked up by a policeman and sent back to England by the local authorities.
He has surely set up a record for the thousands of children who dream of evading school.
#+end_verse
** expression
record-holder [ˈhoʊldər] n.记录保持者
truant [ˈtruənt] n.逃学的孩子
unimaginative [ˌʌnɪˈmædʒɪnətɪv] adj.缺乏想象力的
shame [ʃeɪm] n.惭愧,羞耻
hitchhike [ˈhitʃˌhaɪk] v.搭便车旅行
meantime [ˈminˌtaɪm] n.其间
lorry [ˈlɔri] n.卡车
border [ˈbɔrdər] n.边界
evade [ɪˈveɪd] v.逃避,逃离

play truant from school 逃学
be put to shame = put sb. to shame 把某人比下去
shame on you 真可耻
hitchhike to sw. 搭便车去某地
in the meantime 在此期间
--------------------
612345+6123456(6123456)

over and over again 反复不断地



** DONE 单词造句
CLOSED: [2023-09-04 Mon 21:42]
record-holder n.
- Sherwin, the world record-holder, breaks his record again.
- Sherwin, the world record-holder, succeeded in crossing the Channel.
- Sure that she has became the record-holder, she bursted into tears.
- Following in his father's footsteps, he become the new record-holder.
- She was unaware of becoming the record-holder after this competition.
truant n. play truant from school
- I have never dreamed of playing truant from school.
- You shouldn't have played truant from school for your safety.
- At the time, she was just a girl who played truant from school a lot.
- I felt for her, she has played truant from school once more.
- It's no use pretending that the truant hadn't made that stupid remark.
unimaginative adj.
- Don't following the steps in the forest, it's unimaginative.
- She is such an unimaginative girl that she stays at home on Weekends.
- He is such an unimaginative man that he always forgets their wedding anniversary.
- He is such an unimaginative man that he doesn't know the way to the hotel.
- She regrets getting married to that unimaginative man.
shame n. put sb. to shame, shame on you
- Your swimming put me to shame.
- Shame on you.
- I'm fairly confident that the event will put you to shame.
- His private collection put me to shame.
- I admit that your grade put me to shame.
hitchhike v. hitchhike to sw.
- Not knowing the way to the hotel, he hitchhikes to it in the end.
- He was able to hitchhike to the city everytime when he was a boy.
- I was astonishged at his hitchhiking to the town.
- It occurred to me that we could hitchhike to residence.
- His car hasn't broken down, he needn't have hitchhiked to the forest.
meantime n. in the meantime
- In the meantime, the lady ran straight at the two thieves.
- In the meantime, I have caught up with the bus at the last minute of the day.
- In the meantime, she was going through divorce.
- In the meantime, the cat smashed everything in the kitchen to pieces.
- In the meantime, a gust of wind swept the bed off the root.
lorry n.
- He must have been hit by a lorry yesterday.
- If he had paid attention to it, he wouldn't have been hit by the lorry.
- After taking truant from school, the boy hitchhiked to the centre of Paris in a lorry.
- There is a lorry parked in the courtyard.
- The lorry driver is on a diet and is forbidden to eat ice cream by his wife.
border n.
- It's impossible for us to hitchhike to the Russian border.
- People in this country is forbidden to get close to the Russian border.
- They hardly had reached the Russian border when they saw their wifes.
- A short while ago, a fire was put out at the border.
- To make matters worse, they have crossed the Russian border.
evade v.
- It's no use evading problem.
- He is trying to do housework for evading homework.
- You're simply trying to evade problem.
- Don't evade this question she has just asked you.
- The mother needn't have helped her son to evade the test.

** 反复听电影片段
** DONE Pattern Drill 写+读
CLOSED: [2023-09-04 Mon 22:06]
- 
	1T: found him-somewhere to sleep
	S1: What was he doing when you found him?
	S2: He was looking for somewhere to sleep.
	+ met him -- someone to talk to
		What was he doing when you met him?
		He was looking for someone to talk to.
	+ met them -- something to read
		What was they doing when you met them?
		They were looking for something to read.
	+ saw her -- somewhere to hide
		What was she doing when you saw her?
		She was looking for somewhere to hide.
	+ found him -- someone to help him
		What was he doing when you found him?
		He was looking for someone to help him.
- 
	2T: burnt your arm - ironing
	S1: Oh dear! You've burnt your arm!
	S2: Yes, I burnt it when I was ironing.
	+ broken the cup -- dusting the shelf
		Oh dear! You've broken the cup.
		Yes, I broke it when I was dusting the shelf.
	+ lost a glove -- chasing a thief
		Oh dear! You've lost a glove.
		Yes, I lost it when I was chasing a thief.
	+ torn your coat -- climbing a tree
		Oh dear! You've torn your coat.
		Yes, I tore it when I was climbing a tree.
	+ hurt your leg -- playing football
		Oh dear! You've hurted your leg.
		Yes, I hurted it when I was playing football.
- 
	3T: worn that dress - for the picnic
	S1: She hasn't worn that dress before.
	S2: Yes, she has. It's the dress she wore for the picnic last month.
	+ read this book -- in hospital
		She hasn't read this book before.
		Yes, she has. It's the book she read in hospital last month.
	+ spoken to that boy -- on the telephone
		She hasn't spoken to that boy before.
		Yes, she has. It's the boy she spoke to on the telephone last month.
	+ seen that film -- in London
		She hasn't seen that film before.
		Yes, she has. It's the film she saw in London last month.
	+ heard that song -- on the radio
		She hasn't heard that song before.
		Yes, she has. It's the song she heard on the radio last month.
- 
	4T: Paris - in a lorry
	S1: How did you get to Paris?
	S2: I got there in a lorry.
	+ the house -- in a taxi
		How did you get to the house?
		I got there in a taxi.
	+ Canada -- by plane
		How did you get to Canada?
		I got there by plane.
	+ the island -- in a boat
		How did you get to the island?
		I got there in a boat.
	+ the village -- by helicopter
		How did you get to the village.
		I got there by helicopter.
	
** DONE 给自己讲解
CLOSED: [2023-09-05 Tue 21:13]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-04 Mon 21:42]
over and over again
- Unaware of that, Chandler has explained everything to Joey over and over again.
- I read the story over and over again so that I could understand it.
- It was obvious that the bread had been cut off over and over again.
- Getting very angry, he kicked his wife's ass over and over again.
- The people by the river called out to him over and over again.
** DONE 跟读至背诵
CLOSED: [2023-09-05 Tue 21:12]
** DONE Ask me if 写+读
CLOSED: [2023-09-05 Tue 21:21]
1. Some children play truant from school. (Who)(What ... do)
	 Who play truant from school?
	 What do some children do?
2. Most of them are unimaginative. (How many)
		How many of them are unimaginative?
3. They spend a day fishing. (How)
		How do they spend a day?
4. They go to the cinema sometimes. (Where)
		Where do they go sometimes?
5. They see the same film over and over again. (How many times)
		How many times do they see the same film?
6. One boy has put them all to shame. Who
	 Who has one boy put to shame?
7. He traveled 1,600 miles while play truant. How far/ When
	 How far did he travel while play truant?
	 When did he traveled 1,600 miles.
8. He hitchhiked to Dover. Where
	 Where did he hitchhike?
9. He went into a boat towards evening. When/Where/Why
	 When did he go into a boat?
	 Where did he go towards evening?
	 Why did he go into a boat towards evening?
10. He wanted to sleep. What
		What did he want to do?
** 摘要写作
A boy who played truant traveled 1,600 miles.
He hitchhiked to Dover where he slept in a boat, only to find himself in Calais the next morning.
A lorry driver gave him a lift and something to eat, and the boy got off near Paris.
He stopped another car but,
	instead of being taken Paris, he was taken to Perpinan on the French-Spanish border.
After being picked up by a policeman, he was sent home by the local authorities.
--------------------
A boy played truant from school and travlled 1,600 miles.
After hitchhiking to Dover, he slept in a boat.
The next morning he found himself in Calais,
	where a lorry diver gave him a lift and something to eat.
On getting off near Paris,
	he stopped another car
		which didn't take him to Paris but to Perpinan on the French-Spanish border.
There he was picked up by a policeman and sent home by the local authorities.



** DONE tell the story 口语
CLOSED: [2023-09-05 Tue 21:41]
** Topics for discussion
