#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 74 Out of the limelight
#+begin_verse
Why was their disguise ‘too perfect’?

An ancient bus stopped by a dry river bed and *a party of* famous actors and actresses got off.
Dressed in dark glasses and old clothes,
	they had *taken special precautions* so that no one should recognize them.
But as they soon discovered, disguises can sometimes be too perfect.
'This is a wonderful place for a picnic,' said Gloria Gleam.
'It couldn't be better, Gloria,' Brinksley Meers agreed.
'No newspaper men, no film fans!
*Why don't we* come more often?'
Meanwhile, two other actors, Rockwall Slinger and Merlin Greeves,
	had *carried two large food baskets to* a shady spot under some trees.
When they had all *made themselves comfortable*, a stranger appeared.
He looked very angry.
'Now you get out of here, all of you!' he shouted.
'I'm sheriff here.
Do you see that notice? It says "No Camping" -- in case you can't read!'
'Look, sheriff,' said Rockwall, '*don't be too hard on us*.
I'm Rockwall Slinger and this is Merlin Greeves.'
'Oh, is it?' said the sheriff with a sneer.
'Well, I'm Brinksley Meers, and my other name is Gloria Gleam.
Now you *get out of here* fast!'
#+end_verse
** expression
limelight ['laɪmlaɪt] n.舞台灯光
precaution [prɪˈkɔʃ(ə)n] n.预防措施
fan [fæn] n.狂热谜,迷
shady [ˈʃeɪdi] adj.遮荫的
sheriff [ˈʃerɪf] n.司法长官
notice [ˈnoʊtɪs] n.v.告示
sneer [snɪr] n.v.冷笑

stay out of the limelight 避免引人注目
take precautions 采取预防
sb. is a big/huge fan of a. 某人是……的超级粉丝
on such short notice 在这么短的时间内
with a sneer/ sneer at sb. 对某人冷笑地
--------------------
a party of 一群
why don't we 为什么我们不
carry sth. to sw. 将某物带到某处
make oneself comfortable 别客气
don't be too hard on us 不要对我们太苛刻
get out of here 离开这里



** DONE 单词造句
CLOSED: [2023-09-06 Wed 21:48]
limelight n. stay out of the limelight
- Cristal Liu used to stay out of the limelight.
- You needn't have stayed out the limelight.
- She makes a big decision and stays out of the limelight for the rest of her life.
- It's no use pretending that you haven't stayed out of the limelight.
- He's always thinking about staying out of the limelight.
precaution n. take precaution
- On the last day of the year, everyone was instructed to take great precaution.
- "Take precaution!", the security shouted at the girl.
- The foreigner refused to take precaution in Shanghai.
- People in Disney land have to take every precaution before entering it.
- Chinese were not allowed to take great precaution in USA.
fan n. sb. is a big/huge fan of a.
- He's such a big fan of the truth that he refused to tell lies to people.
- I'm a huge fan of your cooking, darlin.
- Would you mind my following around you? I'm a huge fan of your movie.
- The police which is trying to keep order is a fan of the Greenwood Boys.
- He's such a big fan of the actoress that he keep following her around all morning.
shady adj.
- I have been reading aloud in that shady spot every afternoon for a long time.
- A man in the shady spot is waving to us.
- I had to take a rest in that shady spot, for I'm too exhausted.
- They were hold the meeting in the shady spot.
- He is busy looking for a insect in that shady spot.
sheriff n.
- The sheriff continued to shout at the boy.
- It's the sheriff who makes mistakes, not you.
- The sheriff will arrest him as soon as he arrives at the airport.
- The sheriff shouldn't have arrested the girl who has a clear conscience.
- The sheriff return the stolen car to the young mother.
notice n.v. on such short notice
- There is a notice sticking to the wall.
- Thank you for your helping on such short notice.
- We can't have done homework on such short notice.
- It was you who put the notice on the wall, not your student.
- It is said that the notice was put by a student who plays truent from school every day.
sneer n.v. with a sneer/ sneer at sb.
- "You needn't have said that.", his wife said with a sneer.
- The police double check his parcel with a sneer.
- "It's you who are responsible for the whole thing, not me", she said with a sneer.
- Don't sneer at me.
- The officer sneered at the man who was bursting into tears.

** 反复听电影片段
** DONE Pattern Drill 写+读
CLOSED: [2023-09-06 Wed 21:48]
- 
	 1T: wearing your glasses -hate
	 S1: Why aren't you wearing your glasses?
	 S2: Because I hate wearing them.
	+ polishing the car--don't like
		Why aren't you polishing the car?
		Because I don't like polishing it.
	+ washing the dishes -- dislike
		Why aren't you washing the dishes?
		Because I dislike wasking them.
	+ talking to Frank -- hate
		Why aren't you talking to Frank?
		Because I hate talking to him.
	+ watching football--don't enjoy
		Why aren't you watching football?
		Because I don't enjoy watching it.
- 
	 2T: wears glasses
	 S1: John always wears glasses.
	 S2: Are you sure? He isn't wearing any today.
	+ takes a taxi
		John always takes a taxi.
		Are you sure? He isn't taking any today.
	+ catches a bus
		John always catches a bus.
		Are you sure? He isn't catching any today.
	+ smokes a cigar
		John always smokes a cigar.
		Are you sure? He isn't smoking any today.
	+ wear gloves
		John always wears gloves.
		Are you sure? He isn't wearing any today.
- 
	 3T: pen - No/Yes
	 S1: I'm using your pen. Do you mind?
	 S2: No, it's all right. I don't need it just now.
	 Yes, I do. I want to use it myself.
	+ computer - No/Yes
		I'm using your computer. Do you mind?
		Yes, I do. I want to use it myself.
	+ dictionary - Yes/No
		I'm using your dictionary. Do you mind?
		No, it's all right. I don't need it just now.
	+ ladder - Yes/No
		I'm using your ladder. Do you mind?
		Yes, I do. I want to use it myself.
	+ mirror - No/Yes
		I'm using your mirror. Do you mind?
		No, it's all right. I don't need it just now.
- 
	 4T: she's doing - see
	 S1: What's she doing?
	 S2: I don't know what she's doing. I can't see anything.
	+ he's saying --hear
		What's he saying?
		I don't know what he's saying. I can't hear anything.
	+ she's cooking --smell
		What's she cooking?
		I don't know what she's cooking. I can't smell anything.
	+ they're making --see
		What're they making.
		I don't know what they're making. I can't see anything.
	+ we're eating --taste
		What're we eating?
		I don't know what we're eating. I can't taste anything.
	 
** DONE 给自己讲解
CLOSED: [2023-09-06 Wed 21:50]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-06 Wed 22:06]
a party of
- A party of children who played truant from school hitchhiked to Paris last night.
- A part of women gather round and sang the same song over and over again.
- In the meantime, a party of fans are meeting the group of singer at the station.
- I was disappointed to learn that a party of student were arrested by the local authorities.
- A party of student have difficulty in finishing homework.
why don't we
- Why don't we turn our attention to the cat?
- Why don't we go to disney land once more.
- Why don't we stay out of limelight?
- Why don't we connect the microphone to the big Ben?
- Why don't we make the plan official?
carry sth. to sp.
- The boy who played truant from school was carried to the border.
- You're responsible for carrying the paper to office.
- He refused to carry his homework to school.
- He should have carried his homework to school.
- The official should have carried the postcards to office.
make oneself comfortable
- Please come in and make yourself comfortable.
- Why don't we make ourselves comfortable first?
- Why don't we set up the tent and make ourselves comfortable?
- It's difficult for her to make herself comfortable in the hotel.
- The landlord is making himself comfortable.
don't be too hard on us 
- You shouldn't have been too hard on your child.
- Don't be too hard on yourself, you aren't responsible for the mistake.
- Don't be too hard on her, for she's very young.
- Don't be too hard on us, you should turn attention to them.
- If you hadn't been too hard on your child, you wouldn't have argued with him.
get out of here
- Let us know when we can get out of here.
- Would you mind my getting out of here?
- Get out of here, for your safety.
- The cow is charging at you, get out of here.
- Get out of here. Ross yelled at Rachel.
** DONE 跟读至背诵
CLOSED: [2023-09-08 Fri 19:41]
** DONE Ask me if 写+读
CLOSED: [2023-09-08 Fri 20:02]
1. An ancient bus stopped by a dry river bed. What kind of/Where
	 What kind of bus stopped by a dry river bed?
	 Where did an ancient bus stop?
2. A party of famous actors and actresses got off. Who/When
		Who got off?
		When did a party of famous actors and actresses get off?
3. They were dressed in dark glasses and old clothes. How/Why/Who
		How were they dressed in?
		Why were they dressed in dark glasses and old clothes?
		Who were dressed in dark glasses and old clothes?
4. They'd come for a picnic. What/Why
		What had they come for?
		Why had they come?
5. They had taken special precautions so that no one should recognize them. Why
		Why had they taken special precautions?
6. Disguises can sometimes be too perfect. What/Why
	 What can sometimes be too perfect?
	 Why can disguises sometimes be too perfect?
7. It was a wonderful place for a picnic. What kind of
	 What kind of place was it?
8. They got out their food. What
	 What did they get out?
** DONE 摘要写作
CLOSED: [2023-09-08 Fri 20:02]
After an ancient bus had stopped by a river bed, a party of famous film stars descended.
They were dressed in dark glasses and old clothes so as not to be recognized.
Two of the actors carried some picnic things to a shady spot and everyone sat down.
Just then a sheriff told them rudely that they must leave because camping was not allowed.
Even when they told him who they were, he did not believe them.

An ancient bus stopped by a dry river bed.
A party of famous film stars descended,
	dressed in dark glasses and old clothes in order that they wouldn't be recognized.
They carrid some picnic things to a shady spot.
Everyone had sat down,
	when a sheriff told them rudely that they must leave as camping was not allowed there.
The actors told him who they were but he did not believe them.



** DONE tell the story 口语
CLOSED: [2023-09-08 Fri 20:06]
** Topics for discussion

* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
