#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 77 A successful operation

#+begin_verse
Did the doctors find out how the woman died?

The mummy of an Egyptian woman who died in 800 B.C. has just had an operation.
The mummy is that of Shepenmut who was once a singer in the Temple of Thebes.
As there were strange marks on the X-ray plates taken of the mummy,
	doctors have been trying to find out whether the woman died of a rare disease.
The only way to do this was to operate.
The operation, which lasted for over four hours,
		proved to be very difficult because of the hard resin which covered the skin.
The doctors removed a section of the mummy and sent it to a laboratory.
They also found something which the X-ray plates did not show:
	a small wax figure of the god Duamutef.
This god which has the head of a cow was normally placed inside a mummy.
The doctors have not yet decided how the woman died.
They feared that the mummy would fall to pieces when they cut it open,
	but fortunately this has not happened.
The mummy successfully survived the operation.
#+end_verse
** expression
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple [ˈtemp(ə)l] n.庙
mark [mɑrk] n.斑点
plate [pleɪt] n.底片
disease [dɪˈziz] n.疾病
last [læst] v.持续
prove [pruv] v.显示出
resin [ˈrezɪn] n.树脂
skin [skɪn] n.皮,皮肤
section [ˈsekʃ(ə)n] n.切片
figure [ˈfɪɡjər] n.(人的)体形; 人像
normally [ˈnɔrm(ə)li] adv.通常地
survive [sərˈvaɪv] v.幸免于

have a rare disease 患有罕见的疾病
a section of ... 一部分
prove to be adj. 证明是…
--------------------
非限定定语从句: 解释,补充,说明
	- which非限整句:
		+ 位置: 句尾
		+ 指代被修饰词
	- as非限整句
		- 位置: 前中后
		- 指代整句
	- 非限定只能who/which/whose
		- none of/neither of/any of/either of + which/whom
		- some of/many of/much of/(a) few of + which/whom
		- both of/ half of /each of/one of/two of + which/whom

--------------------
have an operation 动手术
died of ... 死于……
fall to pieces 破碎
cut it open 把它切开




** words
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple [ˈtemp(ə)l] n.庙
mark [mɑrk] n.斑点
plate [pleɪt] n.底片
disease [dɪˈziz] n.疾病
last [læst] v.持续
prove [pruv] v.显示出
resin [ˈrezɪn] n.树脂
skin [skɪn] n.皮,皮肤
section [ˈsekʃ(ə)n] n.切片
figure [ˈfɪɡjər] n.(人的)体形; 人像
normally [ˈnɔrm(ə)li] adv.通常地
survive [sərˈvaɪv] v.幸免于

** DONE 单词造句
CLOSED: [2023-09-13 Wed 22:16]
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
- He has carried a few mummy to his country from Egyptian.
- The mummy which was sent here from Egyptian has been cut open.
- It's no use pretending that you were a big fan of the mummy.
- Leo was said to be a huge fan of the mummy.
- It's you who are responsible for the mummy, not Leo.
temple [ˈtemp(ə)l] n.庙
- He has paid a visit the temple over and over again.
- He has been visiting temples all over the world.
- Don't make that stupid remark in the temple.
- The is a bull charging at her in the temple.
- The temple will have been finished by the time.
mark [mɑrk] n.斑点
- There are some weird marks on the X-ray plates.
- She always complained abouth the dirty mark on her child trousers.
- She had a red mark on her arm because of the flood.
- She fears that she has a rare disease, for she has a red mark on her leg.
- It is possible to have a red mark on you face.
plate [pleɪt] n.底片
- Would you carry the X-ray plates to a shady spot under some trees.
- Take your plate and get out of here.
- Why don't we double check the X-ray plates?
- The nurse has glanced at the X-ray plates over and over again.
- We should have taken plates of the mummy.
disease [dɪˈziz] n.疾病 have a rare disease
- He had a rare disease which I forget its name.
- All has been put to shame by the rare disease.
- The rare disease takes its name from Doctor Wu and has been made official.
- If you drunk this water, you might have a rare disease.
- He was disappointed to learn that he had had a rare disease.
last [læst] v.持续
- Would you mind the meeting's lasting for over three hours?
- He noticed that the show lasted for over two hours.
- The harvesting lasted for the whole summar.
- The Asian Game will last in Hangzhou for two week.
- It will last for two hours. The teacher said with a sneer.
prove [pruv] v.显示出 prove to be adj.
- Although she insisted on playing piano, it proved to be difficult.
- The operation which the mummy survived has proved to be very difficult.
- The news bulletin on April 1st proved to be true.
- She proved to be great at the time.
- The bull proved to be very angry.
resin [ˈrezɪn] n.树脂
- It was not long before the body was covered with the resin.
- In the meantime, the woman's finger was covered with the resin.
- The child who played truant from school enjoy covering himself with the resin.
- You needn't have covered your pen with the resin.
- The famous actor carried the resin to a shedy spot under some trees.
skin [skɪn] n.皮,皮肤
- She might have died of a rare skin disease.
- Jackson had been trying to stay out of the limelight because of his skin disease.
- It was obvious that she had a skin disease.
- She covers her skin with perfume before she goes to sleep.
- The doctor refused to cut her skin off.
section [ˈsekʃ(ə)n] n.切片 a section of ...
- If you had just read a section of the book, you wouldn't have said that.
- The book takes its name from a section of your body.
- A section of the mummy has been smashed to pieces.
- This section of body proved to be his.
- You should have read a section of the book.
figure [ˈfɪɡjər] n.(人的)体形; 人像
- We saw two figures playing truant from school.
- We saw two figures break into the tears.
- It was so dark that I could only see a figure put out the fire.
- Let's suppose that there was a figure in front of the museum.
- The figure behind me was following me around.
normally [ˈnɔrm(ə)li] adv.通常地
- Normally, Leo would tell the story once more.
- I normally catch sight of the sign in the street.
- I am normally busy with studying English.
- Normally, student would turn their attention to Leo.
- Normally, he would make that stupid remark over and over again.
survive [sərˈvaɪv] v.幸免于
- These plants woul survive in such good condition.
- I was wondering wether the heroine would survive in the flood.
- Make yourself comfortable, we would survive this.
- If I don't survive this,  don't feel sorry for me.
- They survived apparently at the end of harvesting.

** DONE 反复听电影片段
CLOSED: [2023-09-13 Wed 22:33]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-14 Thu 20:35]
-
	 1T: play football
	 S1: I didn't know you played football!
	 S2: Didn't you? I've been playing it for some time now.
	 - wear glassess
		 I didn't know you weared glasses!
		 Didn't you? I've been weaing it for some time now.
	 - design dresses
		 I didn't know you designed dresses!
		 Didn't you? I've been designing them for some time now.
	 - teach chemistry
		 I didn't know you teach chemistry!
		 Didn't you? I've been teaching it for some time now.
	 - give concerts
		 I didn't know you give concerts!
		 Didn't you? I've been giving them for some time now.
-
		2T: sing solo
		S1: I didn't know she sang solo!
		S2: Didn't you? She's sung solo on several occassions now.
	 - swim, for the school team
		 I didn't know she swam!
		 Didn't you? She's swum for the school team now.
	 - act  in television plays
		 I didn't know she acted!
		 Didn't you? She's acted in television plays now.
	 - write  for this newspaper
		 I didn't know she wrote!
		 Didn't you? She's written for this newspaper now.
	 - read the news  on the radio
		 I didn't know she read!
		 Didn't you? She's read the news on the radio now.
-
		3T: cry - during the film
		S1: He's been crying, hasn't he?
		S2: Yes, he has. He cried during the film.
	 - ride - all the way here
		 He's been riding, hasn't he?
		 Yes, he has. He rode all the way here.
	 - eat garlic - at lunch
		 He's been eating garlic, hasn't he?
		 Yes, he has. He ate at lunch.
	 - sleep - on your bed for an hour
		 He's been sleeping, hasn't he?
		 Yes, he has. He slept on your bed for an hour.
	 - read - for a while after lunch
		 He's been reading, hasn't he?
		 Yes, he has. He read for a while after lunch.
-
		4T: play - tennis - at school
		S1: You've played tennis before, haven't you?
		S2: Yes, I played tennis at school.
	 - speak - on the radio - last month
		 You've spoken on the radio before, haven't you?
		 Yes, I spoke on the radio last month.
	 - mend - a bridge - during the war
		 You've mended a bridge  before, haven't you?
		 Yes, I mended a bridge during the war.
	 - travel - round the world - 5 years ago
		 You've traveled round the world before, haven't you?
		 Yes, I traveled round the world 5 years ago.
	 - take - this test - last
		 You've taken this test before, haven't you?
		 Yes, I taked this test last.
** DONE 给自己讲解
CLOSED: [2023-09-13 Wed 22:36]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-13 Wed 22:26]
have an operation
- You needn't have had an operation.
- She had a red mark on her leg and may have had an operation.
- She was instructed to have an operation by the local authorities.
- Let's suppose that you are having an operation.
- He is having an operation.
died of ...
- He must have died of heart disease.
- To make matters worse, all of them died of a rare disease.
- She feared that she would died of skin disease.
- A large number of people die of heart disease every year.
- He died of the car accident on the way home.
fall to pieces
- Threatened to kill his child, he falled to pieces.
- It was not long before he falled to pieces.
- A gust of wind swept the vase off the table and it fell to pieces.
- She is always falling to pieces on the way home.
- You shouldn't have fell to pieces.
cut it open
- He has solved the problem of cutting the mummy open.
- The mummy is having an operation and is cut open.
- The black was ordered to cut the watermelon open.
- All the doctors in the department admires Mr. Leo for cutting the mummy open.
- You should have cut it open.
** DONE 跟读至背诵
CLOSED: [2023-09-14 Thu 20:19]
** DONE Ask me if 写+读
CLOSED: [2023-09-14 Thu 20:35]
- Doctors have just operated on a mummy. What/Why/Who
	 What have doctors just done on a mummy?
	 Why have doctors just operated on a mummy?
	 Who have just operated on a mummy?
- The woman died in 800 B.C. When
	 When did the woman die?
- Her name was Shepenmut. What
	 What was her name?
- She was a singer. What/Who
	 What did she do?
	 Who was a singer?
- She used to sing in the Temple of Thebes. Where/Who
	 Where did she use to sing?
	 Who used to sing in the Temple of Thebes?
6. There were strange marks on the X-ray plates. What/Where
	 What were there on the X-ray plates?
	 Where were there strange marks?
7. Doctors have been trying to find out what she died of. What/Who
	 What have doctors been trying to find out?
8. They suspected a rare disease. What/Why
	 What did they suspect?
	 Why did they suspect a rare disease?
9. The operation lasted for over four hours. How long/Why/What
	 How long did the operation last?
	 Why did the operation last for over hour hours?
	 What lasted for over four hours?
** DONE 摘要写作
CLOSED: [2023-09-14 Thu 21:05]
Doctors have just operated on the mummy of an Egyptian woman who died in 800 B.C.
They wanted to find out whether the woman died of a rare disease.
After removing a section of the mummy, doctors sent it to a laboratory.
During the operation, doctors have unexpectedly found a small wax figure of a god.
Though they were afraid that it would fall to pieces, the mummy survived the operation.

Doctors have just operated on the mummy of an Egyptian woman who died in 800 B.C,
	in order to find out if she died of a rare disease.
They removed a section of the mumm,y which they sent to a laboratory.
Inside the mummy, they unexpected found a small wax figure of a god.
They were afraid that mummy would fall to pieces, but it survived the operation. 

** DONE tell the story 口语
CLOSED: [2023-09-14 Thu 21:08]
** Topics for discussion
