#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 78 The last one?
#+begin_verse
For how long did the writer give up smoking?

After reading an article entitled 'Cigarette Smoking and Your Health'
	I lit a cigarette to *calm my nerves*.
I smoked with concentration and pleasure as I *was sure that* this would be my last cigarette.
For a whole week I did not smoke at all and during this time, my wife suffered terribly.
I had all the usual symptoms of someone giving up smoking: a bad temper and an enormous appetite.
My friends *kept on offering me cigarettes and cigars*.
They *made no effort to hide* their amusement
	whenever I produced *a packet of* sweets from my pocket.
After seven days of this I went to a party.
Everybody around me was smoking and I felt extremely uncomfortable.
When my old friend Brian *urged me to accept* a cigarette, it was more than I could bear.
I took one guiltily, lit it and smoked with satisfaction.
My wife *was delighted that* things had *returned to normal* once more.
Anyway, as Brian pointed out, it is the easiest thing in the world to give up smoking.
He himself has done it lots of times!
#+end_verse
** expression
entitle [ɪnˈtaɪt(ə)l] v.以...为名
calm [kɑm] v.使镇静
nerve [nɜrv] n.神经
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer [ˈsʌfər] v.受苦
symptom [ˈsɪmptəm] n.症状
temper [ˈtempər] n.脾气
appetite [ˈæpəˌtaɪt] n.胃口
produce [prəˈdus] v.拿出
urge [ɜrdʒ] v.怂恿
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted [dɪˈlaɪtəd] adj.欣喜的

entitle sb. to do sth. 使某人有权利做某事
calm down 冷静下来
keep calm 保持冷静
calm my nerve calm my nerve
have/get the nerve to do sth.: To draw upon one's courage or resolve to do something 鼓起勇气做某事
lose sb's nerve: 失去某人的勇气
lose/break/have sb's concentration 某人无法集中注意力
suffer from 遭受
have a good/bad temper 有好/坏脾气
lose sb's temper 发脾气
have/get a good/great appetite 有个好胃口
lose sb's appetite 失去食欲
urge sb. to do sth. 敦促某人做某事
give him satisfaction 给他满足感
sb. be delighted that + ... 某人很高兴+……
--------------------
light a cigarette 点燃一支烟
sb. be sure that + ... 某人确信……
keep on doing sth. 继续做某事
offer sb. sth. 给某人提供某物
make no effort to do sth. 不努力做某事
a packet of... 一包……
return to normal 恢复正常



** words
entitle [ɪnˈtaɪt(ə)l] v.以...为名
calm [kɑm] v.使镇静
nerve [nɜrv] n.神经
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer [ˈsʌfər] v.受苦
symptom [ˈsɪmptəm] n.症状
temper [ˈtempər] n.脾气
appetite [ˈæpəˌtaɪt] n.胃口
produce [prəˈdus] v.拿出
urge [ɜrdʒ] v.怂恿
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted [dɪˈlaɪtəd] adj.欣喜的

** DONE 单词造句
CLOSED: [2023-09-14 Thu 22:38]
entitle [ɪnˈtaɪt(ə)l] v.以...为名
entitle sb. to do sth.
1. He has just published his new book entitled "Pirate Stories".
2. Get out of here no matter who entitled you to be my home.
3. He entitle this tower "Big Ben".
4. This ticket should have entitled me to travel second class.
5. People have never entitled the local authorities to do that.
calm [kɑm] v.使镇静
calm down
keep calm
- She refused to keep calm when she was talking to me.
- Please keep calm and don't get angry.
- She tried to keep calm when the young man and young woman talked loudly.
- Gather round and keep calm.
- She failed to keep calm when she turned her attention to the price.
nerve [nɜrv] n.神经
calm my nerve
have/get the nerve to do sth.
lose sb's nerve
- What would you like to do to calm your nerve?
- Although he made a decision, he finally lost his nerve and returned to China.
- I feared that my wife wouldn't have the nerve to ask for raise.
- After the beggar stood on his head, the woman lost he nerve.
- In return for this, he has the nerve to finish cutting the corn stalks.
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
lose/break/have sb's concentration
- If I had studied last night, I wouldn't had lost my concentration.
- I wish that I hadn't lost my concentration.
- I wish that I had had my concentration to study the course of Leo.
- She always has a splendid concentration during the class.
- Sorry to interrupt but you're breaking my concentration.
suffer [ˈsʌfər] v.受苦
suffer from
- After have been suffering from heart attack, she died of it.
- It was not long before she suffered from a skin illness.
- After having had an operation, she suffered from terribly for several month.
- After quitting smoking, I suffered from terribly for several months.
- As there are some strange marks on the X-ray plates taken of her,
		she are suffering from a rare disease.
symptom [ˈsɪmptəm] n.症状
- We must not only treat symptom, but also the cause.
- At the end of his life, her symptom was becoming weird.
- A party of children have the same symptom of depression.
- It was not long before she told me her symptom.
- She said her symptom to ask me for some help.
temper [ˈtempər] n.脾气
have a good/bad temper
lose sb's temper
- Have a good temper and don't be too hard on a cat.
- After the cat smashed everything to pieces, she lost her temper.
- The woman, which has a bad temper, has difficulty in talking to other.
- I was disappointed to learn that my wife have a bad temper.
- Losing his temper Leo instructed us to turn our attention to him.
appetite [ˈæpəˌtaɪt] n.胃口
have/get a good/great appetite
lose sb's appetite
- She had such a good appetite that she ate three bowls of rice.
- Having been swimming all the afternoon, he had a great appetite.
- It's you who are responsible for losing her appetite, not me.
- I feel sorry for you, you lost your appetite once more.
- He lost her appetite because of the mummy which he got close to in the morning.
produce [prəˈdus] v.拿出
- The lovely girl produced a apple from the basket and asked me to eat.
- He double checked his box and produced his key.
- He produced a book entitled "Story" and began to tell a pirate story.
- I was wondering weather he would produce his exercise book.
- Would you mind my producing the perfume.
urge [ɜrdʒ] v.怂恿
urge sb. to do sth.
- My cousin was always urging me to stole my father's money.
- She enjoys urging children to play truent from school.
- He has urged me to fish for over two hours.
- I am afraid that they would urge me to smoke once more.
- She urged us to go camping.
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
give him satisfaction
- He got satisfaction from setting up his tent.
- It is no use pretending that English had given you satisfaction.
- His mother avoids giving him satisfaction.
- It is worth giving some kind people satisfaction.
- The scientist got a satisfaction from naming the volcano "Kituro".
delighted [dɪˈlaɪtəd] adj.欣喜的
sb. be delighted that + ...
- He was delighted that he had broken the world record.
- My father was delighted that I had recited the story of New Concept English.
- She is delighted that her husband is as strong as a horse.
- She was delighted that her daughter succeeded in crossing the Channel.
- She was delighted that she had passed the driving test.

** DONE 反复听电影片段
CLOSED: [2023-09-15 Fri 20:08]
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-15 Fri 20:21]
light a cigarette
- As soon as you lit a ciagarette, he got out of here.
- She lit a ciagarette with a sneer.
- Who entitled you to light my cigarette?
- After having lost her nerves, she lit a cigarette.
- As soon as you lit a ciagarette, I knew that you were playing truent from school.
sb. be sure that + ...
keep on doing sth.
- She kept on having operations to make her prettier.
- The baby kept on smashing the paper to pieces.
- He keeps on cutting it open.
- He kept on expecting a splendid harvesting.
- He keeps on eating processed food.
offer sb. sth.
- The farmer have been offering the local authorities stalks.
- The police have offered the gangsters a helicopter.
- We couldn't offer you a job on such short notice.
- Why don't we have the nerve to offer him a job.
- He kept on offering me cigarettes.
make no effort to do sth.
- The doctors made every effort to have an operation on the mummy.
- The mummy made no effort to fall to pieces.
- The boy always makes no effort to find out the truth.
- The cat makes every effort to hide himself.
- My wife makes every effort to travel in the remote village.
a packet of...
- The policewoman asked me to calm down and gave me a packet of sweets.
- My wife glanced at a packet of candies with satisfaction.
- Two of the leading growers offered me a packet of corns.
- The farmers have gathered a packet of corn stalks.
- Don't be too hard on us and here is a packet of sweets.
return to normal...
- Don't be too hard on me and let everything return to normal.
- She wanted to stay out of the limelight to return to normal.
- We were eager to return to normal during the that period.
- I wish that your temper had returned to normal.
- I wish that your appetite returned to normal.
** DONE 跟读至背诵
CLOSED: [2023-09-15 Fri 20:31]
** DONE Ask me if 写+读
CLOSED: [2023-09-15 Fri 20:43]
- I read an article on cigarette smoking. What/Who
	 What did you read?
	 Who read an article on cigarette smoking?
- I lit a cigarette to calm my nerves. Why
	 Why did you light a cigarette?
- I smoked with concentration and pleasure. How/Why/Who
	 How did you smoke?
	 Why did you smoke with concentration and pleasure?
	 Who smoked with concentration and pleasure?
- I gave up smoking for a whole week. How long/What
	 How long did you give up smoking?
	 What did you give up for a whole week?
- My wife suffered during this time. When/Why/Who
	 When did your wife suffer?
	 Why did your wife suffer during this time?
	 Who suffered during this time?
6. She suffered terribly. How badly/Why
	 How badly did she suffer?
	 Why did she suffer terribly?
7. I had the usual symptoms. What symptoms
	 What symptoms did you have?
8. I had a bad temper. When/Why
	 When did you have a bad temper?
	 Why did you have a bad temper?
9. My friends kept on offering me cigarettes. What/Who
	 What did your friends keep on offering you?
	 Who kept on offering you cigarettes?
** 摘要写作
Having read an article on smoking,
	the writer smoked his last cigarette.
For a week he did not smoke and his wife suffered terribly
	because he had a bad temper and a large appetite.
Meanwhile, his friends offered him cigarettes
	and were amused to see him produce a packet of sweets from his pocket.
When he went to a party,
	the writer accepted a cigarette which was offered by his old friend,
	and since then things have returned to normal.

The writer read an article on smoking and smoked his last cigarette.
He did not smoke for a week
	and his wife suffered terribly because of her husband's bad temper and large appetite.
Whenever his friends offered him cigarettes
	they were amused because he would produce a packet of sweets from his pocket.
However, at a party he accepted a cigarette from his friend.
Now things have returned to normal.

** DONE tell the story 口语
CLOSED: [2023-09-15 Fri 21:02]
** Topics for discussion

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
