#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 79 By air 

#+begin_verse
Why did the plane turn back?

I used to travel by air *a great deal* when I was a boy.
My parents used to live in South America and I used to fly there from Europe in the holidays.
A flight attendant would *take charge of* me and I never had an unpleasant experience.
I *am used to travelling* by air and only on one occasion have I ever *felt frightened*.
After *taking off*, we were flying low over the city and slowly *gaining height*,
	when the plane suddenly turned round and flew back to the airport.
While we were waiting to land,
	a flight attendant told us to keep calm and to get off the plane quietly
		as soon as it had *touched down*.
Everybody *on board* was worried
	and we *were curious to find out* what had happened.
Later we learnt that there was a very important person on board.
The police had been told that *a bomb had been planted* on the plane.
After we had landed, the plane was searched thoroughly.
Fortunately, nothing was found and five hours later we were able to take off again.
#+end_verse
** expression
parent [ˈperənt] n.父母亲
flight [flaɪt] attendant [əˈtendənt] 空中乘务员
frightened [ˈfraɪt(ə)nd] adj.害怕,担惊
curious [ˈkjʊriəs] adj.急于了解,好奇的
bomb [bɑm] n.炸弹 plant v.安放

feel frightened 感觉害怕
sb. be curious to find out + ... 某人很想知道……
plant a bomb 安置炸弹
--------------------
Only部分倒装
1. Only(+其他部分3456)句首,并且不是修饰主语
	 Only police can come in. 不能倒装
2. 主句一般疑问句的语序
--------------------
a great deal 大量的
take charge of 负责某事
be used to doing 习惯做某事
take off 起飞
gain height 提升高度
touch down 着陆
on board 在船上



** words
parent [ˈperənt] n.父母亲
flight attendant [flaɪt-əˈtendənt] 空中乘务员
frightened [ˈfraɪt(ə)nd] adj.害怕,担惊
curious [ˈkjʊriəs] adj.急于了解,好奇的
bomb [bɑm] n.炸弹
plant [plænt] v.安放

** 单词造句
parent n.
- As a parent, I could bear that he insists on smoking near my children.
- My parents prevented me from living abroad.
- My parents kept carrying corn stalks to my house.
- After having an accident, my parents was trying to stay out of the limelight.
- My parents should have sent a signal to me.
flight attendant 
- All the flight attendants were put to shame by her.
- In the meantime, the flight attendant refused to offer him a blanket and sneered at him.
- The flight attendant took precaution so that nobody can recognize her.
- The flight attendant can't arrive on such short notice.
- The flight attendant is a huge fan of the rapper singer.
frightened adj. feel frightened
- Would you mind my smoking there? I feel frightened.
- When could I get out of here? I feel frightened a lot.
- She feels frightened over and over again because of her husband's heavy drink.
- It made me feel frightened that my grandfather was lying on the floor and talking rudely.
- Don't be too hard on me. You made me feel frightened.
curious adj. sb. be curious to find out + ...
- My wife is curious to find out whether I pass the exam.
- I am curious to find out why you take precaution a great deal.
- Mr. Leo is curious to find out who played truent from school last week.
- I am curious to find out how she hitchhiked to NewYork.
- I am curious to find out why my colleague is responsible for the undertake, not me.
bomb n. plant v. plant a bomb
- He was disappointed to learn that the bomb had not been planted at the airport.
- Following in his father footsteps, the gangster planted a bom in the railway station.
- Having planted the bomb , he burnt down the house.
- He double checked whether the bomb had been planted successfully.
- In the tower, a bomb needn't have been planted.
** DONE 反复听电影片段
CLOSED: [2023-09-17 Sun 21:00]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-17 Sun 21:18]
-
		1t: drive the car
		s1: John was driving the car this morning.
		s2: Was he really? He doesn't usually drive it, does he?
	 - help Mary
		 John was helping Mary this morning.
		 Was he really? He doesn't usually help her, does he?
	 - prepare lunch
		 John was preparing lunch this morning.
		 Was he really? He doesn't usually prepare it, does he?
	 - wash the car
		 John was washing the car this morning.
		 Was he really? He doesn't usually wash it, does he?
	 - clean his shoes
		 John was cleaning his shoes this morning.
		 Was he really? He doesn't usually clean it, does he?
-
		2t: talked
		s1: Mary hardly talked at all today.
		s2: I'm not surprised! She was talking all night.
	 - slept
		 Mary hardly slept at all today.
		 I'm not surprised! She was sleeping all night.
	 - cried
		 Mary hardly cried at all today.
		 I'm not surprised! She was crying all night.
	 - quarrelled
		 Mary hardly quarrelled at all today.
		 I'm not surprised! She was quarrelling all night.
	 - wrote
		 Mary hardly wrote at all today.
		 I'm not surprised! She was writing all night.
-
		3t: eating - very little - a lot
		s1: John has been eating very little recently.
		s2: So I noticed. He used to eat a lot.
	 - drinking - very little - a lot
		 John has been drinking very little recently.
		 So I noticed. He used to drink a lot.
	 - behaving - stupidly - sensibly
		 John has been behaving stupidly recently.
		 So I noticed. He used to behave sensibly.
	 - dressing - carelessly - carefully
		 John has been dressing carelessly recently.
		 So I noticed. He used to dress carefully.
	 - going to bed - late - early
		 John has been going to bed late recently.
		 So I noticed. He used to go to bed early.
-
		4t: thief - work in a bank
		s1: He used to be a thief, didn't he?
		s2: He used to be, but he was working in a bank the last time I saw him.
	 - pilot - drive a taxi
		 He used to a pilot, didn't he?
		 He used to be, but he was driving a taxi the last time I saw him.
	 - actress - look after her mother
		 She used to be an actress.
		 She used to be, but she was looking after her mother the last time I saw her.
	 - teacher - play a guitar
		 He used to be a teacher.
		 He used to be, but he was playing a guitar the last time I saw him.
	 - flight attendant - have a baby
		 She used to be a flight attendant.
		 She used to be, but she was having a baby the last time I saw her.
** DONE 给自己讲解
CLOSED: [2023-09-17 Sun 21:18]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-17 Sun 21:18]
a great deal
- The beauty of the West Lake is beyond description a great deal.
- He worked hard a great deal to get a better salary.
- He is sensitive about accepting criticism a great deal.
- I shouldn't have lost my temper a great deal.
- He has finished his housework a great deal.
take charge of
- Mr. Leo asked me to take charge of the class while he was away.
- I was instructed to take charge of those cows.
- Let's suppose that you are taking charge of the boy who play truent from school.
- I have been taking charge of the baby. She says with a sneer.
- I am pleased with taking charge of the cute cat.
be used to doing
- I am used to reading aloud in the afternoon.
- I am used to following my cousin around all weekends.
- He is used to stealing his aunt's books.
- He was used to setting up camps when he was very young.
- I am not used to cooking dinner.
take off
- The helicopter is taking off in the field.
- The helicopter took off suddenly at the airport.
- Before it had taken off, the plane was double checked.
- It is no use pretending that the plane had taken off.
- He noticed that the plane had not taken off.
gain height
- The plane failed to gain height.
- The plane managed to gain height in such terrible condition.
- The plane gained height when it crossed the forest.
- The plane is gaining height on the way home.
- The plane would gain height as soon as it takes off.
touch down
- When the plane touch down, a party of detectives were waiting at the airport.
- After touching off, the plane was covered with a big blanket.
- The moment the plane touches down, you will be arrested.
- It is said that the plane touched down in the field.
- The plane was said to touch down in the area.
on board
- The moment you are on board, the flight attendant will offer you some foods.
- The passenger on board has the nevers to ask for the flight attendant's phonenumber.
- The girl was taken charge of a flight attendant on board.
- I'm fairly confident that I am king of the world when I am on board.
- The captain would be on board in his thirties.
** DONE 跟读至背诵
CLOSED: [2023-09-17 Sun 21:18]
** Ask me if 写+读
1. I used to travel by air a great deal. How often/How
	 How often did you use to travel by air?
	 How did you use to travel a great deal?
2. That was when I was a boy. When
		When was that?
3. My parents used to live in South America. Where/Who
		Where did your parents use to live?
		Who used to live in South America?
4. I used to fly there in the summer holidays. When/Where
		When did you use to fly there?
		Where did you use to fly in the summer holidays?
5. A flight attendant took charge of me. Who
		Who took charge of you?
6. I'm used to travelling by air. What
	 What are you used to doing?
7. I felt frightened once. When
	 When did you feel frightened?
8. The plane had just taken off. What ... do
	 What had the plane just done?
9. It was flying low. How high
	 How high was it flying?
10. The plane turned round. What ... do
		What did the plane do?
1- It flew back to the airport. Where ... to
		Where did it fly back to?
** DONE 摘要写作
CLOSED: [2023-09-17 Sun 21:35]
The plane took off and flew low over the city.
When it was slowly gaining height, it suddenly had to return to the airport.
Meanwhile the passengers were told to keep calm.
After having disembarked, they learnt that there was an important person on board.
Someone had told the police that a bomb had been painted on the plane,
	but though the plane was searched thoroughly, nothing was found.
Five hours later, the plane took off again.


After having taken off, the plan flew low over the city.
Although it was slowly gaining height, it suddenly had to return to the airport.
During this time, the passengers were told to keep calm until they had disembarked.
They learnt that there was a very important person on board.
Because the police had been told that a bomb had been planted on the plane,
	the plane was searched thoroughly.
However, nothing was found, so five hours later it took off again.
** DONE tell the story 口语
CLOSED: [2023-09-17 Sun 21:37]
** Topics for discussion

