#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 85 Never too old to learn

#+begin_verse
How long has Mr. Page been teaching?

I have just received a letter from my old school,
	*informing me* that my former headmaster, Mr. Stuart Page, will be retiring next week.
Pupils of the school, old and new, will be sending him a present to *mark the occasion*.
All those who have *contributed towards* the gift
	will sign their names in a large album which will be sent to the headmaster's home.
We shall all *remember Mr. Page for* his patience and understanding
	and for the kindly encouragement he gave us when we went so unwillingly to school.
A great many former pupils will be attending a farewell dinner *in his honour* next Thursday.
*It is a curious coincidence that* the day before his retirement,
	Mr. Page will have been teaching for *a total of* forty years.
After he has retired, he will *devote himself to gardening*.
For him, this will be an entirely new hobby.
But this does not matter,
	for, as he has often remarked, one is never too old to learn.
#+end_verse
** expression
inform [ɪnˈfɔrm] v.告诉,通知
headmaster [ˈhedˌmæstər] n.校长
contribute [ˈkɑntrɪˌbjut] v.捐助,援助
gift [ɡɪft] n.礼物,赠品
album [ˈælbəm] n.签名簿,相册
patience [ˈpeɪʃəns] n.耐心
encouragement [ɪnˈkʌrɪdʒmənt] n.鼓励
farewell [ferˈwel] n.告别
honour [ˈɑnər] honor n.敬意
coincidence [koʊˈɪnsɪdəns] n.巧合
total [ˈtoʊt(ə)l] n.总数
devote [dɪˈvoʊt] v.致力于
gardening [ˈɡɑrd(ə)nɪŋ] n.园艺
hobby [ˈhɑbi] n.爱好,嗜好

sb. inform sb. that + ... 某人通知某人
make a contribution 做贡献
contribute to sth. 促成某事物
lose sb's patience 失去某人的耐心 
have a lot of patience 有很多耐心
give sb. encouragement 给某人鼓励
in one's honor: it is done specially to show appreciation of them 纪念某人
It is a curious coincidence that + ... 这是一个奇怪的巧合……
a total of ...(176) 总共176
devote oneself to sth./doing sth. 投身于某事/做某事
--------------------
mark the occassion 纪念这个场合
remember sb. for sth. 因某事记住某人


** words
inform [ɪnˈfɔrm] v.告诉,通知
headmaster [ˈhedˌmæstər] n.校长
contribute [ˈkɑntrɪˌbjut] v.捐助,援助
gift [ɡɪft] n.礼物,赠品
album [ˈælbəm] n.签名簿,相册
patient [ˈpeɪʃ(ə)nt] n.耐心
encouragement [ɪnˈkʌrɪdʒmənt] n.鼓励
farewell [ferˈwel] n.告别
honour [ˈɑnər] n.敬意
coincidence [koʊˈɪnsɪdəns] n.巧合
total [ˈtoʊt(ə)l] n.总数
devote [dɪˈvoʊt] v.致力于
gardening [ˈɡɑrd(ə)nɪŋ] n.园艺
hobby [ˈhɑbi] n.爱好,嗜好
** DONE 单词造句
CLOSED: [2023-09-26 Tue 21:47]
inform v. sb. inform sb. that + ...
- The student informed us that he have objected to driving buses.
- The student informed me that he volunteered to drive buses.
- Public was informed that this will relieve pressure on the trains.
- The busmen informed that they would go on strike.
- The busmen informed that the agreement was reached about pay and working condition.
headmaster n.
- The headmaster has stated that students who play a truent from school will be punished.
- The student refused to express his gratitude to the headmaster.
- The headmaster was fantical about football.
- The headmaster loves to drive buses.
- The headmaster is used to winning the election.
contribute v. make a contribution  contribute to sth.
- It is no use pretending that you haven't contributed to our family.
- The police on duty have contributed to the railway station.
- The headmaster stated that he has contribute to the school a great deal.
- I was relieved to hear that she begun to contribute to her family.
- Why did she object to contribute to helping the poor?
gift n.
- He refused to give his girlfriend a gift and knocked her to the ground.
- She claim to have been given a lot of gifts.
- It is known that she is always asking for a gift in any way.
- It was found to be a gift which will be given her son.
- He discovered that the gift her girlfriend gived him is a piano.
album n.
- The boy made every effort to send his father an album.
- While he was seeing the album, she felt frightened.
- He is curious to find out if the album has been made.
- I am sure that the headmaster will receive an album from his students.
- When they saw the album, they burst into cheers.
patience n. lose sb's patience  have a lot of patience
- Would you mind my asking for your patience.
- Don't be too hard on us, and thank you for your patience.
- In the end I lost my patience, I talked to him with a sneer.
- In spite of this, she made every effort not to lose her patience.
- He lost his patience and had a good appetite.
encouragement n. give sb. encouragement
- Sister Juan is used to giving her friends encouragement.
- If my father hadn't given me encouragement, I wouldn't have gone to college.
- If you had given him encouragement, he would had crossed the channel.
- She had a good temper and gave her children encouragement at times.
- She is suffering from a rare disease. We're going to give her some encouragement.
farewell n.
- She attended a farewell dinner and told some funny stories.
- She's going to have an operation in other country,
	 everyone in the town wil be attending a farewell dinner.
- Students are instructed to attend a farewell dinner.
- I never get the nerve to attend a farewell dinner.
- It was no long before she attended a farewell dinner.
honour honor n. in one's honor
- The building takes its name from the headmaster in his honor.
- We decide to name it her name in her honor.
- She was covered with the national flag in her honor.
- The games will be held in her honor.
- He will follow in his father's footsteps in his honor.
coincidence n. It is a curious coincidence that + ...
- It is a curious coincidence that the oarfish was caught out at sea.
- It is no coincidence that the man is following us around for an hour.
- It is no coincidence that the busmen go on strike after he won the election.
- It is a coincidence that he succeed in hitchhike to Paris.
- It is a coincidence that I am responsible for the accident.
total n. a total of ...
- A total of 5 house have been burnt down.
- There are a total of 5 lands in the world.
- A total of 5 people were killed in the flood in Beijing.
- A total of 5 students played truents from school last week.
- A total of 1000 soldiers stood to attention.
devote v. devote oneself to sth./doing sth.
- After his entirement, he devoted himself to gardening.
- After I had graduted, I failed to devote myself to research.
- He really enjoy speaking and writing, so he devoted himself to making stories.
- He has devoted himself to build the big clock.
- He insisted on devoting himself to helping the poor.
gardening n.
- She devoted herself to the gardening, I felt sorry for her.
- I'm not instered in the gardening, I'm instered in catching a good sight of view.
- She continued doing the gardening on Staurday afternoon.
- She is always pleased with doing the gardening.
- Let's suppose that you're doing the gardening.
hobby n.
- You should have had a hobby.
- Would you mind my talking about your hobby.
- For your healthy, you shouldn't devote yourself to the hobby.
- However, she is sensitive about others talk about her hobby.
- He is unaware of having the hobby for over 3 years.
** DONE 反复听电影片段
CLOSED: [2023-09-27 Wed 20:04]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-27 Wed 20:09]
-
	 1t: the library-read those papers
	 s1: How much longer will he be staying at the library?
	 s2: He'll have to stay here until he's read those papers.
	 - the hotel - buy a flat
		 How much longer will he be staying at the hotel?
		 He'll have to stay here until he's bought a flat.
	 - the hotel - rent a flat
		 How much longer will he be staying at the hotel?
		 He'll have to stay here until he's rented a flat.
	 - school - mark the tests
		 How much longer will he be staying at school?
		 He'll have to stay here until he's marked the tests.
	 - home - find a new job
		 How much longer will he be staying at home?
		 He'll have to stay here until he's found a new job.
-
	 2t: print invitations - wedding
	 s1: Will you be having invitations printed for the wedding?
	 s2: Yes, we will. I only hope they'll be printed in time.
	 - check the car - trip
		 Will you be having the car checked for the trip?
		 Yes, we will. I only hope they'll be checked in time.
	 - renew your passport - trip
		 Will you be having your passport renewed for the trip?
		 Yes, we will. I only hope they'll be renewed in time.
	 - put up decorations - dance
		 Will you be having decorations put up for the dance?
		 Yes, we will. I only hope they'll be put up in time.
	 - make costumes - play
		 Will you be having custumes made for the play?
		 Yes, we will. I only hope they'll be made in time.
-
		3t: have lunch
		s1: We can't visit the Smiths now. They'll be having lunch.
		s2: They'll have had lunch by now, surely?
	 - pack their bags
		 We can't visit the Smiths now. They'll be packing their bags.
		 They'll have packed their bags by now, surely?
	 - feed the horses
		 We can't visit the Smiths now. They'll be feeding the horses.
		 They'll have fed the horses by now, surely?
	 - read the papers
		 We can't visit the Smiths now. They'll be reading the papers.
		 They'll have read the papers by now, surely?
	 - put the children to bed
		 We can't visit the Smiths now. They'll be putting the children to bed.
		 They'll have put the children to bed by now, surely?
-
	 4t: working
	 s1: Shall we visit the Smiths tonight, or will they still be working?
	 s2: If they are, they'll have been working the whole day!
	 - painting
		 Shall we visit the Smiths tonight, or will they still be painting?
		 If they are, they'll have been painting the whole day!
	 - decorating
		 Shall we visit the Smiths tonight, or will they still be decorating?
		 If they are, they'll have been decorating the whole day!
	 - cleaning
		 Shall we visit the Smiths tonight, or will they still be cleaning?
		 If they are, they'll have been cleaning the whole day!
	 - packing
		 Shall we visit the Smiths tonight, or will they still be packing?
		 If they are, they'll have been packing the whole day!
** DONE 给自己讲解
CLOSED: [2023-09-27 Wed 19:34]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-26 Tue 21:47]
mark the occassion
- If you have marked the occassion, you would have done something to celebrate.
- All the students were instructed to mark the occassion.
- Let's suppose that we're marking the occassion.
- To mark the occassion, she made a big contribution.
- I am eager to tell stories to mark the occassion.
remember sb. for sth.
- I will remember him for our friendship.
- You should remember him for the encouragement he gave you.
- She claim to have remembered him for his contribution.
- You should have remember him for his patience.
- I will always remember my father for the love he gave me.
** DONE 跟读至背诵
CLOSED: [2023-09-27 Wed 19:34]
** DONE Ask me if 写+读
CLOSED: [2023-09-27 Wed 20:10]
1. I've just received a letter. What
	 What have you just received?
2. It was about Mr. Stuart Page, my former headmaster. What
		What was it about?
3. He will be retiring next week. When
		When will he be retiring?
4. His pupils will send him a present. Who
		Who will send him a present.
5. They'll be sending him a present to mark the occasion. Why/What/Who
		Why will they be sending him a present?
		What will they be sending him to mark the occasion?
		Who will be sending him a present to mark the occasion?
6. The contributors will sign their names in an album. Where/What
	 Where will the contributors sign their names?
	 What will the contributors sign in an album?
7. It will be sent to his home. Where
	 Where will it be sent?
8. We shall all remember Mr. Page for his patience and understanding. What
	 What will you all remember Mr. Page for?
9. He gave us kindly encouragement when we went to school. What/When
	 What did he give us when we went to school?
	 When did he give us kindly encoragement?
	 
** DONE 摘要写作
CLOSED: [2023-09-27 Wed 19:59]
Now that my former headmaster, Mr. Page, will be retiring,
	pupils of the school will be sending him a gift and an album with their signatures of those
		who have contributed.
A great many former pupils will be attending a farewell dinner in his honor.
After having completed forty years as a teacher,
	Mr. Page will devote himself to the gardening,
		which will be a new hobby for him,
	  but one is never too old to learn.

After twenty-eight years as headmaster, Mr. Page is retiring.
Pupils of the school will not only be sending him a gift,
	but also an album with their signatures.
Many former pupils will be attending a farewell dinner in honor of a man
	who has completed forty years as a teacher.
Now he will devote himself to the gardening.
Though  this is a new hobby, it doesn't matter because one is never too old to learn.

** DONE tell the story 口语
CLOSED: [2023-09-27 Wed 20:12]
** Topics for discussion
