#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 87 A perfect alibi
#+begin_verse
What was wrong with the man's story?

'At the time the murder was committed,
	I was travelling on the 8 o'clock train to London,' said the man.
'Do you always catch such an early train?' asked the inspector.
'Of course I do,' answered the man.
'I must be at work at 10 o'clock.
My employer will confirm that I was there on time.'
'Would a later train get you to work on time?' asked the inspector.
'I suppose it would, but I never catch a later train.'
'At what time did you arrive at the station?'
'At ten to eight.
I bought a paper and waited for the train.'
'And you didn't notice anything unusual?'
'Of course not.'
'I suggest,' said the inspector, 'that you are not telling the truth.
I suggest that you did not catch the 8 o'clock train,
	but that you caught the 8.25 which would still get you to work on time.
You see, on the morning of the murder, the 8 o'clock train did not run at all.
It broke down at Ferngreen station and was taken off the line.'
#+end_verse
** expression
alibi [ˈælɪˌbaɪ] n.不在犯罪现场
commit [kəˈmɪt] v.犯(罪,错)
inspector [ɪnˈspektər] n.探长
employer [ɪmˈplɔɪər] n.雇主
confirm [kənˈfɜrm] v.确认,证实
suggest [səɡˈdʒest] v.提醒
truth [truθ] n.真相

have a alibi 有不在场证明
commit a murder 犯下谋杀罪
sb. confirm that + ... 某人证实……
Are you suggesting + ... 你是在表示...
tell the truth 说实话
--------------------
on time 准时

** words
alibi [ˈælɪˌbaɪ] n.不在犯罪现场
commit [kəˈmɪt] v.犯(罪~错)
inspector [ɪnˈspektər] n.探长
employer [ɪmˈplɔɪər] n.雇主
confirm [kənˈfɜrm] v.确认,证实
suggest [səɡˈdʒest] v.提醒
truth [truθ] n.真相
** DONE 单词造句
CLOSED: [2023-09-29 Fri 15:04]
alibi n. have a alibi
- Because he didn't have a perfect alibi, the police was investigating him.
- He has such a perfect alibi that nobody found that he was suspicous.
- On the following day, he claimed to have a perfect alibi.
- If he had a perfect alibi, the police wouldn't continue to search his house.
- The inspector volunteered to find out whether he had a perfect alibi.
commit v. commit a murder
- If I had commited a murder, the police would have arrested me. He said in a strong voice.
- The fisherman stated that he had commited a murder out at sea.
- It is known that he commited a murder on the last day of the year.
- He admited that he commited a murder on Christmas day.
- It is possible for him to commit a murder.
inspector n.
- The inspector double checked his house and found nothing.
- The inspector feared that a murder would be commited again.
- The inspector enjoy finding out whether he had a perfect alibi.
- The inspector is following us around.
- I was wondering that the inspector had checked the place.
employer n.
- I'm a big fan of my employer.
- You will get a better salary. my employer said.
- Our employer is used to going to office very early.
- We're trying to avoid meeting our employer in the mall.
- Fancy meeting you here. My employer said hello to me.
confirm v. sb. confirm that + ...
- I confirmed that my cat hadn't eatten any food.
- I confirmed that she was pleased with her behavior.
- I confirmed that he had made that stupid remark.
- I confirmed that he love to hear this.
- I confirmed that he had stood to attention by then.
suggest v. Are you suggesting + ...
- Are you suggesting that I don't feel sorry for her?
- Are you suggesting that I am busy with my work?
- Are you suggesting that they has made it official?
- Are you suggesting that I am sensitive about accepting criticism?
- Are you suggesting that she had sent a signal for help?
truth n. tell the truth
- The local authorities keep on telling the truth to people.
- The boy who tapped on the window was instructed to tell the truth.
- Why are you so tired? I have been telling the truth.
- He has told the truth and explained it to everyone.
- He noticed with dismay that she hadn't told the the truth about the accident.
** DONE 反复听电影片段
CLOSED: [2023-09-30 Sat 21:31]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-30 Sat 21:26]
-
		1t: broke that plate
		s1: I wonder who broke that plate.
		s2: John told me he'd broken it.
	 - tore the curtain
		 I wonder who tore the curtain.
		 John told me he'd torn it.
	 - drew up the plan
		 I wonder who drew up the plan.
		 John told me he'd drown up it.
	 - posted the card
		 I wonder who posted the card.
		 John told me he'd posted it.
	 - sent the message
		 I wonder who sent the message.
		 John told me he'd sent it.
-
		2t: he'll be coming
		s1: Have you asked him when he'll be coming?
		s2: Yes, he said he'd be coming tomorrow.
	 - she'll be singing
		 Have you asked her when she'll be coming?
		 Yes, she said she'd be singing tomorrow.
	 - they'll be sailing
		 Have you asked them when they'll be sailing?
		 Yes, they said they'd be sailing tomorrow.
	 - she'll be teaching
		 Have you asked her when she'll be teaching?
		 Yes, she said she'd be teaching tomorrow.
	 - he'll be arriving
		 Have you asked him when he'll be arriving?
		 Yes, he said he'd be arriving tomorrow.
-
		3t: visit him
		s1: When will you visit him?
		s2: He hasn't asked me to visit him yet!
	 - teach them
		 When will you teach them?
		 They haven't asked me to teach them yet!
	 - go out with him
		 When will you go out with him?
		 He hasn't asked me to go out with them yet!
	 - sing for her
		 When will you sing for her?
		 She hasn't asked me to sing for her yet!
	 - photograph them
		 When will you photograph them?
		 They haven't asked me to photograph them yet!
-
		4t: sell this car
		s1: I think I'll have to sell this car.
		s2: I suggested you should sell it weeks ago!
	 - phone John
		 I think I'll have to phone John.
		 I suggested you should phone him weeks ago!
	 - apply for the job
		 I think I'll have to apply for the job.
		 I suggested you should apply for it weeks ago!
	 - apologize to Mary
		 I think I'll have to apologize to Mary.
		 I suggested you should apologize to her weeks ago!
	 - enter for the race
		 I think I'll have to enter for the race.
		 I suggested you should enter for it weeks ago!
** DONE 给自己讲解
CLOSED: [2023-09-30 Sat 21:32]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-29 Fri 15:04]
on time
- It's the last day of the year, I must be on duty on time.
- He insists on studying English on time.
- The girl agreed to meet him on time next time.
- The car has hold up the traffic and I didn't arrive on time.
- My aunt was dressed up as a young girl and arrived on the scene on time.
** DONE 跟读至背诵
CLOSED: [2023-09-30 Sat 21:33]
** Ask me if 写+读
1. The inspector was interviewing a man. Who/Why
	 Who was the inspector interviewing?
	 Why was the inspector interviewing a man?
2. The man said he was travelling to London. What/Where/Woh
		What did the man say?
		Where did the man said he was travelling?
		Who said he was travelling to London?
3. He was on the train. Where
		Where was he?
4. He always caught the early train. When/Which train/Why
		When did he always catch the train?
		Which train did he always catch?
		Why did he always catch the early train?
5. He had to be at work at 10 o'clock. At what time/Where
		At what time did he have to at work?
		Where did he have to be at 10 o'clock?
6. His employer would confirm that he was there on time. What/Who
	 What would his employer confirm?
	 Who would confirm that he was there on time?
7. A later train would get him to work on time. When
	 When would a later train get him to work?
8. He was at the station at 7.50. Where
	 Where was he at 7.50?
** DONE 摘要写作
CLOSED: [2023-09-30 Sat 21:52]
At the time of murder,
	the man claimed that
		he had ben travelling on the 8 o'clock train to London
		and had at work on time.
When the inspector asked him
	whether a later train would get him to work on time,
		the man agrred it would
			but said that he always travelled early.
The inspector suggested that he was lying
	because, that morning, the 8 o'clock train broke down,
	so the man must have caught the 8.25.

When the murder was commited,
	the man claimed that he was travelling on the 8 o'clock to London.
He said that he had been at work on time.
Then, the spector asked him
	if a later train would get him to work on time.
Though the man agreed it would, he said he always travelled early.
In reply, the inspector suggested he was lying,
	as, that morning, the 8 o'clock train broke down
	and therefore the man must have caught the 8.25.
** DONE tell the story 口语
CLOSED: [2023-09-30 Sat 21:56]
** Topics for discussion
