#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 88 Trapped in a mine

#+begin_verse
Why is the rescue taking so long?

Six men have been trapped in a mine for seventeen hours.
If they are not brought to the surface soon they may *lose their lives*.
However, rescue operations are proving difficult.
If explosives are used, vibrations will *cause the roof of the mine to collapse*.
Rescue workers are therefore drilling a hole on the north side of the mine.
They intend to bring the men up *in a special capsule*.
If there had not been *a hard layer of* rock beneath the soil,
	they would have completed the job in a few hours.
*As it is*, they have been drilling for sixteen hours and they still have a long way to go.
Meanwhile, a microphone, which was lowered into the mine two hours ago,
	has *enabled the men to keep in touch with* their closest relatives.
Though they are *running out of* food and drink,
	the men are cheerful and confident that they will get out soon.
They have been told that rescue operations are progressing smoothly.
If they knew how difficult it was to drill through the hard rock, they would *lose heart*.
#+end_verse
** expression
trap [træp] v.陷入,使陷入困境
surface [ˈsɜrfəs] n.地面,表面
explosive [ɪkˈsploʊsɪv] n.炸药
vibration [vaɪˈbreɪʃ(ə)n] n.震动
collapse [kəˈlæps] v.n.坍塌
drill [drɪl] v.n.钻孔
capsule [ˈkæpˌsjul] n.容器
layer [ˈleɪr] n.层
beneath [bɪˈniθ] prep.在...之下
lower [ˈloʊr] v.adj.放下,降低
progress [prəˈɡres] v.n.进展,进行
smoothly [ˈsmuːðli] adv.顺利地

on the surface 表面上
in a special capsule 在一个特殊的胶囊里
layers of 几层的...
a layer of 一层的...
make progress 取得进展
go/run smoothly 进展顺利
--------------------
wish型虚拟语气: 从句: should(可省略) do

lose one's life 死亡
As it is... 事实上(状语)
enable sb. to do sth. 使某人能够做某事
keep in touch with ... 与……保持联系
run out of ... 用完
lose heart ... 丧失信心
cause sb./sth/ to do sth. 造成某人做某事


** words
trap [træp] v.陷入,使陷入困境
surface [ˈsɜrfəs] n.地面,表面
explosive [ɪkˈsploʊsɪv] n.炸药
vibration [vaɪˈbreɪʃ(ə)n] n.震动
collapse [kəˈlæps] v.坍塌
drill [drɪl] v.钻孔
capsule [ˈkæpˌsjul] n.容器
layer [ˈleɪr] n.层
beneath [bɪˈniθ] prep.在...之下
lower [ˈloʊr] v.放下,降低
progress [prəˈɡres] v.进展,进行
smoothly [ˈsmuːðli] adv.顺利地
** DONE 单词造句
CLOSED: [2023-10-03 Tue 10:01]
trap v.
- How long have six men been trapped in the gold mine?
- The workers begun to complain of being trapped in a mine.
- The workers was trained to rescue themselves while trapped in a mine.
- I felt trapped in a place where I had to work hard.
- He pointed out that six worker had been trapped in a mine.
surface n.on the surface
- It is no use helping her on the surface.
- On the surface, he has followed his father's footstep.
- He enjoys helping others on the surface.
- No matter what you do on the surface, you wouldn't be fluent.
- He pointed out that his children is always studying hard on the surface.
explosive n.
- He has become an expert at explosives.
- The gangster has a habit of planting explosive on the place in where he had been.
- The expert managed to remove the explosives from the car.
- A number of explosives are planted on the plane.
- He had a bad reputation for planting explosives.
vibration n.
- I have been waking up by the vibration of the window.
- If you hadn't turned it up, our parents would have felt the vibration of music.
- If you turned it up, our parents would feel the vibration of music.
- Why can some animals feel vibrations in the sand?
- It is no use pretending that you hadn't felt the vibration of music.
collapse v.n.
- The heavy rain may cause the collapse of our camp.
- It is a blessing that the heavy rain hadn't caused the collapse of our houses.
- It is a blessing that the collapse of our tents weren't caused during the flood.
- It is you who are responsible for the collapse of the building,not her.
- He is eager to see the collapse of the bridge.
drill v.n.
- After drilling for several months, they eventually found a gold mine in the end.
- He is eager to drill holes in his bed.
- When he drilled a hole on his car door, it broke down.
- They were disappointed  to find out that nobody was drilling for them.
- My father hesitated to drill a hole.
capsule n.in a special capsule
- It is the most special capsule I've ever met.
- A party of young men and young women are walking in a circle around the special capsule.
- They continued to live in a special capsule.
- They couldn't tell the difference from capsule and container.
- Nobody account for the fact that they are standing in a circle around the capsule.
layer n.layers of/a layer of
- China must be packed in several layers of paper. I said in a weak voice.
- It occured to me that I weared several layers of clothes.
- He admitted that he weared several layers of clothes.
- There is still a layer of dust on the table. she said with a sneer.
- He turn his attention to a layer of dust.
beneath prep.
- Nobody account for the fact that the cat was beneath the air conditioner.
- We broke into cheers beneath a shady tree.
- We caught sight of rabbits beneath a shady tree.
- The boy was trapped beneath the bed once more.
- The boy must have been hidden beneath a thin layer of soil.
lower v.adj.
- We are ordered to lower our voice in his class.
- It is worth lowering the noise in public places.
- In reasonable condition, if we lower our voice, the baby will not wake up.
- Why don't we have the television lowered its voice?
- He agreed to lower his voice in the plane.
progress v.n.make progress
- We have solved the problem of noise population, and we're making progress.
- It is fortunate that we made progress last year.
- Dressed up as a gentleman, he was sure that he made progress this time.
- Even though we aren't finished yet, we make big progress.
- We must put forward a plan to make progress.
smoothly adv.go/run smoothly
- It is a glessing that everything runs smoothly.
- We must stick to our plan and everything will go smoothly.
- He was dismay to find that everything goes smoothly.
- I'm fairly certain that things go smoothly and both of us will write to each other soon.
- His dream came true and everything goes smoothly.
** 反复听电影片段
** DONE Pattern Drill 写+读
CLOSED: [2023-10-03 Tue 20:56]
-
		1t: catch the train - hurry
		s1: I can't possibly catch the train now!
		s2: You might catch it if you hurry!
	 - pass the exam - work hard
		 I can't pass the exam now!
		 You might pass it if you work hard!
	 - sell the car - mend it
		 I can't sell the car now!
		 You might sell it if you mend it!
	 - win the race - keep calm
		 I can't win the race now!
		 You might win it if you keep calm!
	 - finish in time - get help
		 I can't finish in time now!
		 You might finish it if you get help!
-
		2t: catch the train - pack
		s1: He won't catch the train if he doesn't pack soon!
		s2: He won't catch it now, even if he's already packed!
	 - be in time - leave
		 He won't be in the time if he doesn't leave soon!
		 He won't be in time now, even if he's already left!
	 - be in time - call a taxi
		 He won't be in time if he doesn't call a taxi soon!
		 He won't be in time now, even if he's already called!
	 - get the job - apply
		 He won't get the job if he doesn't apply!
		 He won't get it now, even if he's already applied!
	 - find his case - tell the police
		 He won't find his case if he doesn't tell the police!
		 He won't find it now, even if he's already told.
-
	 3t: go with him - ask
	 s1: Will you go with him?
	 s2: I'd go with him if he asked me to - but I don't think he will!
	 - clean his room - ask
		 Will you clean his room?
		 I'd clean it if he asked me to - but I don't think he will!
	 - enter for the race - advise
		 Will you enter for the race?
		 I'd enter it if he advised me to - but I don't think he will!
	 - join his team - invite
		 Will you join his team?
		 I'd join it if he invited me to - but I don't think he will!
	 - work late - tell
		 Will you work late?
		 I'd work late if he told me to - but I don't think he will!
-
	 4t: failed so badly - worked harder
	 s1: He shouldn't have failed so badly.
	 s2: He wouldn't have failed so badly if he'd worked harder.
	 - lost his way - had a map
		 He shouldn't have lost his way.
		 He wouldn't have lost his way if he'd had a map.
	 - died - gone into hospital
		 He shouldn't have died.
		 He wouldn't have died if he'd gone into hospital.
	 - been late - taken a taxi
		 He shouldn't have been late.
		 He wouldn't have been late if he'd taken a taxi.
	 - retired - had a good job
		 He shouldn't have retired.
		 He wouldn't have retired if he'd had a good job.
** DONE 给自己讲解
CLOSED: [2023-10-03 Tue 20:57]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-03 Tue 10:01]
lose one's life
- He lost his life in a rescue operation.
- It's a blessing that he didn't lose his life during the flood.
- Though a firefighter lost his life, all the people in the building were saved.
- He intended to commit a murder, but he lost his life during this.
- He confirmed that his son had lost his wife.
As it is...
- As it is, you did not catch the 8 o'clock train, but you caught the 8.2-
- As it is, he had a perfect alibi.
- As it is, I'm telling you the truth.
- We were hoping to have a holiday tomorrow as it is, it will rain.
- As it is, he has been at work on time.
enable sb. to do sth.
- This would enable you to cut it open.
- This enabled the boat to come towards them at tremendous speed.
- The new test will enable drivers to drive more carefully.
- He was enabled to devote himself to volcanoes.
- The encouragement he gives us enabled us to go to school.
keep in touch with ...
- Next week, they decided to keep in touch with each other.
- If you kept in touch with her, she might fall in love with you.
- If we had kept in touch with each other, we would have divorced.
- It is a curious coincidence that both of them keep in touch with each other.
- He has a lot of patience and kept in touch with the student who plays truent from school.
run out of ...
- She noticed with dismay that they had ran out of money on journey.
- She was due to run out of her pocket money.
- I object to her running out of money.
- To some extend, I has run out of my father's money.
- In the end, the flight attendent has run out of her patience and lost her temper.
lose heart ...
- I'll keep studying English and won't lose my heart.
- He has failed the test and lost his heart.
- After having been rescued for ten hours, the men lost their heart.
- Don't be hard on us, we'll lose our heart.
- Although he is a huge fans of soccer, he lost his heart in the games.
cause sb./sth/ to do sth.
- I confirm that the pepper caused me to sneeze.
- You've almost caused me to lose my life.
- The prisident caused the party to have a good reputation.
- This will cause the plane to gain height slowly.
- This can't cause the plane to touch down smoothly.
** DONE 跟读至背诵
CLOSED: [2023-10-03 Tue 20:32]
** DONE Ask me if 写+读
CLOSED: [2023-10-03 Tue 21:04]
1. Six men have been trapped in a mine. How many/Where
	 How many men have been trapped in a mine?
	 Where have six men trapped?
2. They've been there for seventeen hours. How long/Where
		How long have they been there?
		Where have they been for seventeen hours?
3. Rescue operations are proving difficult. What/Why
		What are proving difficult?
		Why are rescue operations proving difficult?
4. The men will lose their lives. Who
		Who will lose their lives?
5. The roof will collapse. What
		What will collapse?
6. Rescue workers are drilling a hole. What
	 What are rescue workers drilling?
7. They're drilling on the north side. Where
	 Where are they drilling?
8. They'll bring the men up in a special capsule. How/What kind/Who
	 How will they bring the men up?
	 What kind of capsule will they bring the men up in?
	 Who will bring the men up in a special capsule?
9. There's a hard layer of rock beneath the soil. What/Where
	 What is there beneath the soil?
	 Where is there a hard layer of rock?
** DONE 摘要写作
CLOSED: [2023-10-03 Tue 21:16]
Six men who have been trapped in a mine for seventeen hours
	may lose their lives
	because rescue operations are proving difficult.
Since explosive might cause the roof of the mine to collapse,
	rescue workers are drilling a hole through hard rock,
	but progress is slow.
Tow hours ago, a microphone was lowered into the mine
	and the men have been in touch with their closest relatives.
They are running short of food and drink
	but they are in good spirits.

Six men have been trapped in a mine for seventeen hours
	and may lose their lives.
Rescue operations are proving difficult
	as explosives might cause the roof of the mine to collapse.
Because of this, rescue workers are drilling a hole through hard rock,
	 yet progress is slow.
Now that a microphone has been lowered into the mine,
	the men are in touch with their closest relatives.
Though they are running short of food and drink,
	they are in good spirits.
** DONE tell the story 口语
CLOSED: [2023-10-03 Tue 21:19]
** Topics for discussion
