#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 91 Three men in a basket

#+begin_verse
Where was the station's Commanding Officer?

A pilot noticed a balloon which *seemed to be making for* a Royal Air Force Station nearby.
He informed the station at once, but no one there was able to explain the mystery.
The officer in the control tower was very angry when he heard the news,
	because balloons can be a great danger to aircraft.
He said that someone might be *spying on* the station
	and the pilot was ordered to *keep track of* the strange object.
The pilot managed to circle the balloon for some time.
He could *make out* three men in a basket under it and one of them was holding a pair of binoculars.
When the balloon was over the station, the pilot saw one of the men taking photographs.
*Soon afterwards*, the balloon began to descend and it landed near an airfield.
The police *were called in*, but they could not arrest anyone,
	for the basket contained two Members of Parliament and the Commanding Officer of the station!
As the Commanding Officer explained later,
	one half of the station did not know what the other half was doing!
#+end_verse
** expression
balloon [bəˈlun] n.气球
royal [ˈrɔɪəl] adj.皇家
spy [spaɪ] v.侦察
track [træk] n.轨迹,踪迹
binoculars [bɪˈnɑkjələrz] n.望远镜

spy on sb./sth. 监视某人/某物
keep track of 跟踪
--------------------
seem to be doing ... 似乎正在做……
make for sw. 向...前进
make out 弄清
soon afterwards 不久之后
be called in (to do) 被叫去做某事


** words
balloon [bəˈlun] n.气球
royal [ˈrɔɪəl] adj.皇家
spy [spaɪ] v.侦察
track [træk] n.轨迹,踪迹
binoculars [bɪˈnɑkjələrz] n.望远镜

** DONE 单词造句
CLOSED: [2023-10-09 Mon 21:50]
balloon n.
- It comes as a surprise to learn that my father sent me a total of 30 ballons.
- As a result, the balloon flew to Royal Air Force Station.
- The girl received a total of 30 ballons from her boyfriend.
- I found these ballons beautiful.
- There is a great many of ballons in the centre of the school.
royal adj.
- The royal palace shouldn't have been burnt down.
- The royal palace was destoryed by floods.
- A royal detective refused them to take photographs.
- The royal policeman took precaution so that no one can recognize hime.
- On such short notice, the royal police arrived on the scene.
spy v. spy on sb./sth.
- He stamped out the fire and began to spy on Miumiu.
- He covered himself with a blanket and spied on his wife.
- The detective kept on spying his wife for over three days.
- Make yourself comfortable. We are not going to spy on you.
- It is his job to spy on the woods.
track n. keep track of
- If you didn't wear a watch, you wouldn't keep track of time.
- As a programmer, I have to keep track of the latest development in Computer science.
- She is such a huge fan of the singer that she kept track of his daily life.
- On such short notice, we couldn't keep track of the total of the comedy show.
- Why don't we keep track of our program?
binoculars n.
- What he saw throught his binoculars were top secrets.
- Armed with my binoculars, I started to see the comedy show.
- Why did you carry a pair of binoculars to the cinema?
- We don't allow anyone to carry binoculars to the museum.
- Armed with his binoculars, he made for the royal palace.
** DONE 反复听电影片段
CLOSED: [2023-10-10 Tue 20:26]
** DONE Pattern Drill 写+读
CLOSED: [2023-10-10 Tue 20:41]
-
		1t: put these towels - in the cupboard
		s1: Where shall I put these towels?
		s2: You can put them in the cupboard.
	 - dry the wet clothes - in the sun
		 Where shall I dry the wet clothes?
		 You can dry them in the sun.
	 - write the report - in the library
		 Where shall I write the report?
		 You can write it in the library.
	 - park the car - in that car park
		 Where shall I park the car?
		 You can park it in that car park.
	 - get the medicine - from the chemist's
		 Where shall I get the medicine?
		 You can get it from the chemist's.
-
		2t: go and see Mary
		s1: Can you go and see Mary soon?
		s2: I may be able to go and see her tomorrow.
	 - come to see us
		 Can you come to see us soon?
		 I may be able to come to see you tomorrow.
	 - see the doctor
		 Can you see the doctor soon?
		 I may be able to see him tomorrow.
	 - wash my shirt
		 Can you wash yor shirt soon?
		 I may be able to wash it tomorrow.
	 - mend this strap
		 Can you mend this strap soon?
		 I may be able to mend it tomorrow.
-
		3t: jump over the stream - wide
		s1: Why didn't you jump over the stream?
		s2: I couldn't jump over it. It was too wide.
	 - carry the case - heavy
		 Why didn't you carry the case?
		 I couldn't carry it. It was too heavy.
	 - buy the flat - expensive
		 Why didn't you buy the flat?
		 I couldn't buy it. It was too expensive.
	 - move the table - big
		 Why didn't you move the table?
		 I couldn't move it. It was too big.
	 - drink your soup - hot
		 Why didn't you drink your soup?
		 I couldn't drink it. It was too hot.
-
		4t: the door was locked - open
		s1: The door was locked, wasn't it?
		s2: Yes, but I managed to open it in the end.
	 - he refused to agree - convince
		 He refused to agree, didn't he?
		 Yes, but I managed to convince him in the end.
	 - the horse ran way - catch
		 The horse ran way, didn't it?
		 Yes, but I managed to catch it in the end.
	 - the box was very heavy - lift
		 The box was very heavy, wasn't it?
		 Yes, but I managed to lift it in the end.
	 - the river was very wide - get across
		 The river was very wide, wasn't it?
		 Yes, but I managed to get across it in the end.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-09 Mon 21:50]
seem to be doing ...
- He seems to be following in his father's footsteps.
- The boys seem to be playing truant from school.
- The microphone seems to be being connected to the tower.
- The bull seems to get close to the drunk.
- My father seems to be repairing his bicycle.
make for sw.
- The military was instructed to make for Wuhan.
- Let's suppose that a dog makes for our car.
- I was wondering if you were making for the hosptial.
- It is no use pretending that you made for the school.
- Armed with his binoculars, the boy made for the camp.
make out
- It is too dark to make out anything.
- I can listen to most of this, but I can't make out the last part. Can you?
- Fancying meeting you here. I almost can't make out you.
- It is no use pretending that you have made out me.
- Turn it up, or we couldn't make out what they are talking about.
soon afterwards
- Her father complained that she had supper and wen out soon afterwards.
- Soon afterwards, the fisherman caught a giant fish.
- Soon afterwards, he has set up his tent.
- Soon afterwards, the thief was arrested.
- Soon afterwards, I have studied New Concept English textbook 2.
be called in (to do)
- The police were called in to keep order when it happened an accident.
- As the baby elephant is holding up the traffice, the police were called in.
- She had hardly stolen the bag when the policeman was called in.
- The firemen were called in to put out the big fire.
- The military was called to get the city under control.
** DONE 跟读至背诵
CLOSED: [2023-10-10 Tue 20:41]
** DONE Ask me if 写+读
CLOSED: [2023-10-10 Tue 20:48]
1. A pilot noticed a balloon. What/Who
	 What did a pilot notice?
	 Who noticed a balloon?
2. There was a Royal Air Force Station nearby. Where/What
		Where was there a Royal Air Force Station?
		What was there nearby?
3. The balloon was making for it. What
		What was making for it?
4. The pilot informed the station. Who
		Who informed the station?
5. The officer in the control tower heard the news. What/Who
		What did the officer in the control tower hear?
		Who heard the news?
6. He was angry at the news. Why
	 Why was he angry at the news?
7. Balloons can be a danger to aircraft. What
	 What can be a danger to aircraft?
8. The pilot was ordered to keep track of the object. What... do/Who
	 What was the pilot ordered to do?
	 Who was ordered to keep track of the object?
9. There were three men in the basket. How many/ Where
	 How many men were there in the basket?
	 Where were there three men?
** DONE 摘要写作
CLOSED: [2023-10-10 Tue 21:01]
While circling a balloon,
	the pilot saw three men in the basket
		one of whom was holding a pair of binoculars.
When it flew over the station, one of men took photographs.
Then it landed near an airfield,
	but the police couldn't arrest anyone
  because the basket contained two members of Parliament and the Commanding Officer of the station.
Afterwards the Commmanding Officer explained
	that one half of the station didn't know what the other half was doing.

The pilot circled the balloon
	under which there was a basket containing three men,
	one of whom was holding a pair of binoculars.
Before landing near an airfield, it flew over the station and one of men took photographs.
As two of the men were members of Parliment
		and the other was the Commanding Officer of the station,
	the police couldn't arrst anyone.
The mystery was explained
	when the Commanding Officer admitted
		that one half of the station did not know what the other half was doing.
** DONE tell the story 口语
CLOSED: [2023-10-10 Tue 21:04]
** Topics for discussion
