#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 92 Asking for trouble

#+begin_verse
Why did the policeman ask the writer to come to the police station?

It must have been about two in the morning when I returned home.
I tried to wake up my wife by ringing the doorbell,
	but she was *fast asleep*,
	so I got a ladder from the shed in the garden,
		put it against the wall, and began climbing towards the bedroom window.
I was almost there when a sarcastic voice below said,
	'I don't think the windows need cleaning at this time of the night.'
I looked down and nearly fell off the ladder when I saw a policeman.
I immediately regretted answering in the way I did,
	but I said, 'I enjoy cleaning windows at night.'
'So do I,' answered the policeman in the same tone.
'Excuse my interrupting you.
I *hate to interrupt* a man when he's busy working,
	but would you mind coming with me to the station?'
'Well, I'd prefer to stay here,' I said.
'You see. I've forgotten my key.'
'Your what?' he called.
'My key,' I shouted.
Fortunately, the shouting woke up my wife who opened the window
	just as the policeman had started to climb towards me.
#+end_verse
** expression
fast [fæst] adv.熟(睡)
ladder [ˈlædər] n.梯子
shed [ʃed] n.棚子
sarcastic [sɑrˈkæstɪk] adj.讽刺的,讥笑的
tone [toʊn] n.语气,腔调

fast asleep 熟睡的
Are you being sarcastic? 你是在讽刺吗?
Don't take that tone with me! 别用那种语气跟我说话!
--------------------
hate to do sth. 讨厌做某事



** words
fast [fæst] adv.熟(睡)
ladder [ˈlædər] n.梯子
shed [ʃed] n.棚子
sarcastic [sɑrˈkæstɪk] adj.讽刺的,讥笑的
tone [toʊn] n.语气,腔调

** DONE 单词造句
CLOSED: [2023-10-11 Wed 20:10]
fast [fæst] adv. fast asleep
- He was fast asleep when his wife was frightened out of her wits.
- He has watched a variety of videos before he was fast asleep.
- He has been running out of his energy, he is fast asleep now.
- When we saw the cat being fast asleep, we burst out laughing.
- She felt disappointed, as her husband was fast asleep.
ladder [ˈlædər] n.
- A fireman must get used to climbing the ladder up and down.
- It comes as a surprise to learn that the policeman knocked him to the ground with a ladder.
- You should protect your baby from the ladder.
- The ladder is used to rescue people in the fire.
- When the news get round, the ladder was soon sold out.
shed [ʃed] n.
- They are due to have a lovely shed built in the yard.
- Why is there a shed holding up the traffic?
- This caused the shed to be burnt down.
- The shed shouldn't have been burnt down.
- As it is, we could afford to build a shed in our garden.
sarcastic [sɑrˈkæstɪk] adj. Are you being sarcastic?
- Why are you being sarcastic?
- "You're not playing truent from the school." The father said in a sarcastic voice.
- We should have kept in touch with each other. His girlfriend said in a sarcastic voice.
- The girl is always sarcastic.
- The boy kept being sarcastic, in the end I couldn't stand it.
tone [toʊn] n. Don't take that tone with me!
- Don't take that tone with me!
- As long as you take that tone with me, I won't come to the station with you.
- On the surface, he told the story to the girl in a friendly tone.
- You had to talk to your collegue in a friendly tone.
- Don't take that tone with us, you're too hard on us.
** DONE 反复听电影片段
CLOSED: [2023-10-12 Thu 21:30]
** DONE Pattern Drill 写+读
CLOSED: [2023-10-12 Thu 21:47]
-
		1t: eating between meals
		s1: Eating between meals is bad for you.
		s2: But I like eating between meals!
	 - working all night
		 Working all night is bad for you.
		 But I like working all night!
	 - swimming after a meal
		 Swimming after a meal is bad for you.
		 But I like swimming after a meal!
	 - studying at night
		 Studying at night is bad for you.
		 But I like studying at night!
	 - going to bed late
		 Going to bed late is bad for you.
		 But I like going to bed late.
-
		2t: check these figures
		s1: Would you mind checking these figures?
		s2: It's no use asking me to check your figures.I'm busy checking my own!
	 - do my homework
		 Would you mind doing my homework?
		 It's no use asking me to do your homework. I'm busy doing my own!
	 - prepare my speech
		 Would you mind preparing my speech?
		 It's no use asking me to prepare your speech. I'm busy preparing my own!
	 - mend my radio
		 Would you mind mending my radio?
		 It's no use asking me to mend your radio. I'm busy mending my own!
	 - type these letters
		 Would you mind typing these letters?
		 It's no use asking  me to type your letters. I'm busy typing my own!
-
		3t: get into the car - drive
		s1: Did you see him getting into the car?
		s2: I didn't see him getting into the car, but I saw him driving it.
	 - open the window - climb towards
		 Did you see him opening the window?
		 I didn't see him opening the window, but I saw him climbing towards it.
	 - steal the money - count
		 Did you see him stealing the money?
		 I didn't see him stealing the money, but I saw him count it.
	 - enter the house - wait outside
		 Did you see him entering the house?
		 I didn't see him entering the house, but I saw him wait outside it.
	 - shoot the man - hit
		 Did you see him shooting the man?
		 I didn't see him shooting the man, but I saw him hit him.
-
		4t: give speeches
		s1: You must be used to giving speeches now!
		s2: I am, but I always look forward to giving another one!
	 - win elections
		 You must be used to winning elections now!
		 I am, but I always look forward to winning another one.
	 - see 'monsters'
		 You must be used to seeing 'monsters' now!
		 I am, but I always look forward to seeing another one.
	 - visit museums
		 You must be used to visiting museums now!
		 I am, but I always look forward to visiting another one.
	 - receive presents
		 You must be used to receiving presents now!
		 I am, but I always look forward to receiving another one.
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-11 Wed 20:10]
hate to do sth.
- I hate to apologize to anyone when I am innocent.
- Pupils of the school always hate to move in a circle about seven in the morning.
- I hate to fill up his car over and over again.
- She hate to make contribute to the hospital.
- I hate to devote myself to the education.
** DONE 跟读至背诵
CLOSED: [2023-10-12 Thu 21:47]
** DONE Ask me if 写+读
CLOSED: [2023-10-12 Thu 21:53]
1. I returned home late. When/Who
	 When did you return home?
	 Who returned home late?
2. It was about two in the morning. What time
		What time was it about?
3. I tried to wake my wife by ringing the doorbell. How/Who/When
		How did you try to wake your wife?
		Who did you try to wake by ringing the doorbell?
		When did you try to wake your wife by ringing the doorbell?
4. She was fast asleep. Who
		Who was fast asleep?
5. I got a ladder. What
		What did you get?
6. I got it from the garden shed. Where
	 Where did you get it?
7. I put it against the wall. Where
	 Where did you put it?
8. I began climbing towards the bedroom window. Which/Why
	 Which window did you begin climbing towards?
	 Why did you begin climbing towards the bedroom window?
9. I'd almost got to the top. How far
	 How far had you almost got?
10. I heard a voice. What
		What did you hear?
1- It was a policeman. Who
		Who was it?
** DONE 摘要写作
CLOSED: [2023-10-12 Thu 22:04]
The writer returned home at about 2.0 a.m. and rang doorbell.
Having failed to wake up his wife,
	he put the ladder against the wall
	and climbed towards the bedroom window.
Suddenly a policeman called out,
	but he answered rudely.
He told him that he had forgotten his key.
The shouting woke up his wife.
She opened the window
	just as the policeman began climbing the ladder after him.

On arriving home at about two in the morning,
	the writer rang the doorbell
	but failed to wake up his wife.
After having put a ladder against the wall,
	he was climbing towards the bedroom window
	when a policeman called out.
Answering him rudely,
	the writer told him that he had forgotten his key.
The shouting woke up his wife,
	who opened the window at the moment
		when the policeman started climbing the ladder after him.

** DONE tell the story 口语
CLOSED: [2023-10-12 Thu 22:07]
** Topics for discussion
