#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesion 93 A noble gift
#+begin_verse
Where was the Statue of Liberty made?

One of the most famous monuments in the world, the Statue of Liberty,
	was presented to the United States of America in the nineteenth century by the people of France.
The great statue, which was designed by the sculptor Auguste Bartholdi, took ten years to complete.
The actual figure was made of copper
	supported by a metal framework which had been especially constructed by Eiffel.
Before it could be transported to the United States,
	a site had to be found for it and a pedestal had to be built.
The site chosen was an island *at the entrance of* New York Harbour.
By 1884, a statue which was 151 feet tall had been erected in Paris.
The following year, it was *taken to pieces* and sent to America.
By the end of October 1886, the statue had been put together again
	and it was officially presented to the American people by Bartholdi.
Ever since then, the great monument has been a symbol of liberty for the millions of people
	who have passed through New York Harbour to make their homes in America.
#+end_verse
** expression
noble [ˈnoʊb(ə)l] adj.高尚的,壮丽的
monument [ˈmɑnjəmənt] n.纪念碑
statue [ˈstætʃu] n.雕像 liberty n.自由
present [ˈprezənt] v.赠送
sculptor [ˈskʌlptər] n.雕刻家
actual [ˈæktʃuəl] adj.实际的,真实的
copper [ˈkɑpər] n.铜
support [səˈpɔrt] v.支持,支撑
framework [ˈfreɪmˌwɜrk] n.构架,框架
transport [trænsˈpɔrt] v.运送
site [saɪt] n.场地
pedestal [ˈpedɪst(ə)l] n.底座

a noble gift/man 一个高贵的礼物/人
camp site 露营地
--------------------
at the entrance of ... 在……入口处
take sth. to pieces 把……拆散


** words
noble [ˈnoʊb(ə)l] adj.高尚的,壮丽的
monument [ˈmɑnjəmənt] n.纪念碑
statue [ˈstætʃu] n.雕像
liberty [ˈlɪbərti]	n.自由
present [ˈprezənt] v.赠送
sculptor [ˈskʌlptər] n.雕刻家
actual [ˈæktʃuəl] adj.实际的,真实的
copper [ˈkɑpər] n.铜
support [səˈpɔrt] v.支持,支撑
framework [ˈfreɪmˌwɜrk] n.构架,框架
transport [trænsˈpɔrt] v.运送
site [saɪt] n.场地
pedestal [ˈpedɪst(ə)l] n.底座

** DONE 单词造句
CLOSED: [2023-10-14 Sat 21:57]
noble adj. a noble gift/man
- Don't take that tone with the man, for he is not a noble man.
- The noble man was remembered by his patience and understanding.
- The noble man hates to betray his people.
- A noble gift was represented to America in 1889.
- As he is a noble man, we will admire him.
monument n.
- This monument frightened out of my wits at about two in the morning.
- In the absence of monument, less people go to the zoo.
- As a result, the comedy show will be presenting in front of the monument.
- The fire was put out in front of the monument.
- The students hate to stand to attention towards the monument.
statue n. liberty n.
- He was curious to find out that the statue of liberty was built in 1989.
- The statue of liberty was said to be planted a bomb.
- The architect made every effort to repair the statue of liberty.
- France has offered America a statue of liberty.
- Don't light a cigarette in front of the statue of liberty.
present v.
- He never has the nerve to present any gift to his classmate.
- In the end he lost his nerve and presented the postcard to his girlfriend.
- A French waiter presented a book to me, but I couldn't understand a word.
- The mother has a good temper and presents a gift to her children every Christma.
- All the books should have been presented to the poor children who couldn't afford to but any.
sculptor n.
- The sculptor lit a cigarette to calm his nerve.
- The sculptor feared that the statue would fall to pieces.
- The sculptor will have an operation because of his rare disease.
- The sculptor was ordered to cut his masterpiece open.
- It is said that the sculptor had a rare disease and died of it.
actual adj.
- Would you like to give your actual phone number this time?
- This is the boss' actual idea.
- The actual leading cause of his death is the flood.
- Those figures on the bulletin board are actual.
- Why don't we reply to the actual email?
copper n.
- The statue which is made of copper is cutting open.
- Don't take a risk in that copper mine any more.
- It is no use prentending that th copper don't belong to your family.
- It is fortunate that no one was trapped in the copper mine.
- It is well known that the pedestal is made of copper.
support v.
- I will support you no matter what you did.
- The woman confirmed that the policeman has supported in time.
- Before long, the student in the university volunteer to support the busmen.
- If I have understood you, I would have supported you.
- The workers will be supported in a special capsule.
framework n.
- The report has provided a framework for further research.
- The experience provides a framework for his further development in career.
- The bridge is said to have a copper framework.
- The bridge which was made of stone has a copper framework.
- The framework was taken to pieces to move to the statue of liberty.
transport v.
- It comes as a surprise to learn that the copper was transport out of Africa.
- We was able to transport the mummy to the nearest museum.
- The car enabled us to transport him to the nearest hospital.
- This caused him to transport his money abroad.
- He has nerve to transport a great deal of money abroad.
site n. camp site
- The new school was said to have found a new site.
- Last week, we move to a new site.
- The boys are telling stories at the camp site.
- As it is, the stream had formed at the camp site.
- On the surface, they are singing songs at the camp site.
pedestal n.
- A pedestal was made of copper and another was made of steel.
- It caused him to damage the pedestal of the statue.
- A pedestal should have been built yesterday.
- A pedestal will be being built by the Olympic Games.
- He covered the pedestal with a rug.

** DONE 反复听电影片段
CLOSED: [2023-10-14 Sat 21:43]
** DONE Pattern Drill 写+读
CLOSED: [2023-10-14 Sat 21:57]
-
		1t: send my case - to your home
		s1: Where will they be sending my case?
		s2: It'll be sent to your home.
	 - locate oil rig - in the North Sea
		 Where will they be locating oil rig?
		 It'll be located in the North Sea.
	 - give the lecture - in the town hall
		 Where will they be giving the lecture?
		 It'll be given in the town hall.
	 - build the stadium - at Wembley
		 Where will they be building the stadium?
		 It'll be built at Wembley.
	 - show the film - at the studios
		 Where will they be showing the film?
		 It'll be shown at the studios.
-
		2t: this camera
		s1: I can't get this camera to work. It must be broken.
		s2: Then it'll have to be repaired.
	 - this clock
		 I can't get this clock to work. It must be broken.
		 Then it'll have to be repaired.
	 - this machine
		 I can't get this machine to work. It must be broken.
		 Then it'll have to be repaired.
	 - these lights
		 I can't get these lights to work. They must be broken.
		 Then they'll have to be repaired.
	 - these scissors
		 I can't get these scissors to work. They must be broken.
		 Then they'll have to be repaired.
-
		3t: the luggage sent - weighed
		s1: Why can't the luggage be sent now?
		s2: It must be weighed before it can be sent.
	 - the men admitted - searched
		 Why can't the men be admitted now?
		 They must be searched before they can be admitted.
	 - the meat cooked - cut up
		 Why can't the meat be cooked now?
		 It must be cut up before it can be cooked.
	 - th house occupied - cleaned
		 Why can't the house occupied now?
		 It must be cleaned before it can be occupied.
	 - the notice put up - corrected
		 Why can't the notice be put up now?
		 It must be corrected before it can be put up.
-
		4t: the luggage - weighed - sent
		s1: What happened to the luggage?
		s2: It had to be weighed before it could be sent.
	 - the men - searched - admitted
		 What happened to the men?
		 They had to be searched before they could be admitted.
	 - the meat - cut up - cooked
		 What happened to the meat?
		 It had to be cut up before it could be cooked.
	 - the house - cleaned - occupied
		 What happened to the house?
		 It had to be cleaned before it could be occupied.
	 - the notice - corrected - put up
		 What happened to the notice?
		 It had to be corrected before it could be put up.
	 

** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-14 Sat 21:57]
at the entrance of ...
- There is a pretty girl at the entrance of the mall.
- Several artistes are standing at the entrance of the airport.
- We have ran out of our fishes and chip at the entrance of cinema.
- As a result, the workered went on a strike at the entrance of theater.
- The boy seems to be playing guitar at the entrance of the mall.
take sth. to pieces
- I took the computer to pieces so that I could figure out what went wrong.
- Despite taking the computer to pieces, I couldn't figure out what went wrong.
- The moment he took the wash machine to pieces, his wife lost heart.
- Ross took his sofa to pieces so that he could move it upstairs.
- His mother noticed with dismay that he had took the television to pieces.
** DONE 跟读至背诵
CLOSED: [2023-10-14 Sat 21:57]
** DONE Ask me if 写+读
CLOSED: [2023-10-14 Sat 22:07]
1. The Statue of Liberty is a world-famous monument. How famous/What
	 How famous is the Status of Liberty monument?
	 What is a world-famous monument?
2. It was presented to the U.S.A in the nineteenth century. When/What
		When was it presented to the U.S.A?
		What was presented to the U.S.A. in the nineteenth century?
3. It was given by the French. Who
		Who was it given by?
4. It was designed by Bartholdi. Who
		Who was it designed by?
5. He was a sculptor. Who/What
		Who was a sculptor.
		What did he do?
6. It took ten years to complete. How long
	 How long did it take to complete?
7. The figure was made of copper. What
	 What was made of copper?
8. It was supported by a metal framework. How/What
	 How was it supported?
	 What was it supported by?
9. The frame was constructed by Eiffel. Who
	 Who was the frame constructed by?
10. The statue was 151 feet tall. How tall
		How tall was the statue?
1- It was erected in 188- When
		When was it erected?
	 
** DONE 摘要写作
CLOSED: [2023-10-14 Sat 22:19]
The Statue of Liberty, which was presented to U.S.A by the people of French in the 19th century,
	was designed by Bartholdi
	and built on a mental frame constructed by Eiffel.
The site chosen for it was an island at the entrance of New York Harbour,
	where the pedestal had to be built.
The statue was erected in Paris in 1884
	and re-erected in America tow years later.
It was offically presented in October, 1886.

The statue of Liberty was presented to U.S.A. by French people in the 19th century.
Though designed by Bartholdi, it was built on a mental frame constructed by Eiffel.
The site chosen for it was an island at the entrance of New York Harbour
	and the Pedsetal had to be built there.
The statue was first erected in Paris in 1884,
	but it was re-erected two years later in America
	and officially presented in October, 1886.


** DONE tell the story 口语
CLOSED: [2023-10-14 Sat 22:21]
** Topics for discussion
