#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* Lesson 95 A fantasy
#+begin_verse
Why was the Ambassador particularly lucky?

When the Ambassador of Escalopia returned home for lunch, his wife got a shock.
He looked pale and his clothes were in a frightful state.
'What has happened?' she asked.
'How did your clothes *get into such a mess*?'
'A fire extinguisher, my dear,' answered the Ambassador drily.
'University students *set the Embassy on fire* this morning.'
'*Good heavens!*' exclaimed his wife.
'And where were you at the time?'
'I was in my office as usual,' answered the Ambassador.
'The fire broke out in the basement.
I went down immediately, of course, and that fool, Horst, aimed a fire extinguisher at me.
He thought I was on fire.
I must definitely get that fellow posted.'
The Ambassador's wife *went on asking* questions,
	when she suddenly noticed a big hole in her husband's hat.
'And how can you explain that?' she asked.
'Oh, that,' said the Ambassador.
'Someone *fired a shot* through my office window.
Accurate, don't you think?
Fortunately, I wasn't wearing it at the time.
If I had been,
	I would not have been able to get home for lunch.'
#+end_verse
** expression
fantasy [ˈfæntəsi] n.幻想故事
ambassador [æmˈbæsədər] n.大使
frightful [ˈfraɪtf(ə)l] adj.可怕的,令人吃惊的
fire [faɪr] extinguisher [ɪkˈstɪŋɡwɪʃər] 灭火器
drily [ˈdraɪli] adv.冷淡地,鼓噪无味地
embassy [ˈembəsi] n.大使馆
heaven [ˈhev(ə)n] n.天,天堂
basement [ˈbeɪsmənt] n.地下室
definitely [ˈdefənɪtli] adv.肯定地
post [poʊst] v.派任
shot [ʃɑt] n.子弹

live in a fantasy world 生活在幻想的世界里
Good heavens! 天哪
fire a shot 开一枪
--------------------
get into such a mess 陷入困境
set sth. on fire 放火烧某物
go on doing sth. 继续做某事

** words
fantasy [ˈfæntəsi] n.幻想故事
ambassador [æmˈbæsədər] n.大使
Escalopia n.艾斯卡罗比亚
frightful [ˈfraɪtf(ə)l] adj.可怕的,令人吃惊的
fire extinguisher [faɪr-ɪkˈstɪŋɡwɪʃər] 灭火器
drily [ˈdraɪli] adv.冷淡地,枯燥无味地
embassy [ˈembəsi] n.大使馆
heaven [ˈhev(ə)n] n.天,天堂
basement [ˈbeɪsmənt] n.地下室
definitely [ˈdefənɪtli] adv.肯定地
post [poʊst] v.派任
shot [ʃɑt] n.子弹

** DONE 单词造句
CLOSED: [2023-10-16 Mon 20:59]
fantasy n. live in a fantasy world
- If I hadn't lived in a fantasy world, I would have gone to a top university.
- My favourite fantasy is to be the headmaster of the university.
- You shouldn't have lived in a fantasy world.
- If I lived in a fantasy world, you would have a perfect alibi.
- I'm gonna live in a fantasy world in Disney land.
ambassador n.
- The ambassador was reluctant to live in a fantasy world.
- The ambassador had been instructed in English for a long time.
- The ambassadors compete against each other to get married to the girl.
- The ambassador is accustomed to getting home for lunch.
- The ambassador is popular with his people.
frightful adj.
- "Get out of here." she said in a frightful voice.
- I am accustomed to hearing frightful voices from his room.
- Don't take that tone with me. It hears frightful.
- I hate to hear the frightful voice over and over again.
- They looked frightful when they were trapped in a copper mine.
fire extinguisher
- You confirmed that she was able to use the fire extinguishier.
- The ambassador was instrcuted in using the fire extinguisher.
- A fire extinguisher was presented to his neighbour.
- There are a lot of fire extinguishers at the entrance of the embassy.
- The boy has took the fire extinguisher to pieces.
drily adv.
- Don't take this to pieces. She said drily.
- You get away from me. She answered drily.
- Are you being sarcastic? He said drily.
- I hate to swim in the lake. He said drily.
- I am being called in to do the chores. He said drily.
embassy n.
- A crowd have waitted in line in front of American Embassy.
- A crowd moved in circle outside the American Embassy.
- The American Embassy has been burnt down by local university students.
- The embassy was full of water in floods.
- He seems to be going to the American Embassy.
heaven n. Good heavens!
- Good heavens! How dare you!
- Good heavens! You get away from me.
- Good heavens! Why don't you keep in touch with the girl?
- Good heavens! We have ran out of our petrol.
- Good heavens! My son has lost his life in a copper mine.
basement n.
- The girl has been trapped in the basement for over 7 hours.
- When the news get around, he commited a murder in his basement.
- You must tell the truth in the basement.
- Unfortunately, the basement was burnt down.
- The foods in the basement is being used up.
definitely adv.
- He noticed with dismay that he would definitely fail the exam.
- The men will definitely lose their life if they are not rescued in time.
- He will definitely devote himself to gardening for the rest of his life.
- We should definitely remain him for the encouragement he give us
		 when we are so reluctant to go to school. 
- They will definitely send a gift to mark the occassion.
post v.
- You shouldn't have posted Tom to Beijing.
- Why don't we get him posted to China?
- The detectives were posted to the airport to protect the diamond from the thief.
- Thank you for posting me to my hometown.a
- The secretary informed me that I would be posted to South Africa.
shot n. fire a shot
- The ganster claimed that he fired a shot in the prime president's honor.
- The killer has a lot of patience to fire a shot.
- No one should have fired a shot through the window.
- He is fanatical about firing a shot.
- After winning the election, he was fired a shot.
** DONE 反复听电影片段
CLOSED: [2023-10-17 Tue 20:19]
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-16 Mon 21:07]
get into such a mess
- Leave her alone, don't get into any mess with her.
- The moment I win the election, I'll get into a mess with them.
- If you didn't go to the park, you wouldn't get into a mess.
- I discovered that she had gotten into such a mess.
- He is used to getting into a mess after taking part in race.
set sth. on fire
- She may have set the house on fire.
- No smoking. A spark can set the house on fire.
- He was curious to find out that no one set the palace on fire.
- When he knew how someone set the basement on fire, he felt frightened.
- He was going to set the whole village on fire armed with a torch.
go on doing sth.
- We must go on putting forward our plan.
- You should go on having your concentration.
- The plane is going on flying off course.
- The woman caught in a storm went on sending a signal.
- We can go on carrying the fruits to the shady spot.
** DONE 跟读至背诵
CLOSED: [2023-10-17 Tue 20:19]
** DONE Ask me if 写+读
CLOSED: [2023-10-17 Tue 20:26]
1. The Ambassador came home for lunch. Why/When/Who
	 Why did the Ambassador come home?
	 When did the Ambassador come home?
	 Who came home for lunch?
2. His wife got a shock. Why/Who
		Why did his wife get a shock?
		Who got a shock?
3. He looked pale. How/Who
		How did he look?
		Who looked pale?
4. His clothes were in a mess. What/Why
		What were in a mess?
		Why were his clothes in a mess?
5. Students set the Embassy on fire. What
		What did students set on fire?
6. The Ambassador was in his office. Where
	 Where was the Ambassador?
7. The fire broke out in the basement. Where/What/When
	 Where did the fire break out?
	 What broke out in the basement?
	 When did the fire break out in the basement?
8. The Ambassador went down immediately. Where/When/Who
	 Where did the Ambassador go down immediately?
	 When did the Ambassador go down?
	 Who went down immediately?
9. Horst aimed a fire extinguisher at him. What/Why/Who
	 What did Horst aim at him?
	 Why did Horst aim a fire extinguisher at him?
	 Who did Horst aim a fire extinguisher at?
10. There was a hole in his hat. Where
		Where was there a hole?
** DONE 摘要写作
CLOSED: [2023-10-17 Tue 20:36]
While the Ambassador of Escalopia was in his office,
	university students set the basement of the Embassy on fire.
When the Ambassador went to investigate,
	a man called Horst aimed a fire extinguisher at him
	because he thought the Ambassador was on fire.
Moreover, there was a hole in the Ambassador's hat
	which had been made when some fire a shot throught his office window.
The Ambassdor was lucky, for he was not wearing it at the time.

The Ambassdor of Escalopia was in his office
	when university students set the basement of the Embassy on fire.
After the Ambassador had gone to investigate,
	a man called Horst aimed a fire extinguisher at him
		under the impression that the Ambassador was on fire.
In addition to this, there was a hole in the Ambassador's hat.
It had been made when someone fired a shot through his office window.
It was lucky for the Ambassador that he was not wearing it at the time.

** DONE tell the story 口语
CLOSED: [2023-10-17 Tue 20:38]
** Topics for discussion
