* learn English by chatGPT

** words
指令-查词: 生成单词"xx"的信息,包括中文定义,英文定义,词源,词根词缀,用法,例句和短语搭配
指令-生成单词表: 请解释以下单词(至少包括词性,中文定义,例句和短语搭配),并建成excel表: apple, ambition...
指令-找六级的考纲单词: xxxx
指令-生成文章: 用以下单词生成一遍可读性强,有意思的文章,要求在文章里给以下词进行**加粗**标记: apple, ambition...
指令-辨别相近词: 请帮我解释A和B的区别和各自的用法
指令-用法:	look forward的动词用法


1. 挖坟式查词:
	生成单词"XXX"的信息,包括中文定义,英文定义,词源,词根词缀,用法,例句和短语搭配
2. 生成单词表:
	请解释以下单词(至少包括词性,中文定义,例句和短语搭配),并建成excel表: XXX, XXX...
3. 整理考纲单词:
	 请帮我找出这篇文章里的大学英语六级考纲单词,并做出释义: XXXXXX
4. 生成文章:
	 用以下单词生成一遍可读性强,有意思的文章,要求在文章里给以下词进行**加粗**标记: apple, ambition...
5. 辨别相近词:
	 请帮我解释A和B的区别和各自的用法
6. 短语搭配详解:
	 请帮我解释以下语法: xxx的动词用法

** voice
I want you to act as an English teacher and let's talk about friendship.
And please correct me if I make any mistakes.
What is a more natural way to say "I am very hungry".
Can you create a dialogue like the one in the movie "The Godfather" about negotiating a business deal.
From now on you are the character Nick in the movie "Zotopia", chat with me in his way.

1. 口语陪练
	 插件Voice Control for ChatGPT
2. 问地道表达
	 What is a more natural way to say "XXX"?
3. 影视剧台词
	 Can you create a dialogue like the one in the movie/book/... "xxx" about xxx?
4. 角色扮演
	 I want you to act as the character xx in the movie/book/..."xx", then chat with me.

** reading
I want you to act as an English teacher.
I will send you some English sentences and you will analyze them carefully as linguist.
Here are the sentences: ...
可以让其分析题目及答案
外刊精读
帮找外刊
我的四级成绩是,词汇量是4500, 可以阅读Harry Potter吗?

1. 分析长难句: -> 请帮我分析以下句子的语法成分: xxx.
	 I want you to act as an English teacher.
	 I will send you some English sentences and you will analyze them carefully as linguist.
	 Reply me in Chinese. Here are the sentences: XXXX
2. 分析考题:
	 I want you to act as an English teacher.
	 I am doing xxx reading questions in English, please help me analyze why the answer to this question is x.
	 Reply me in Chinese. The question is xxx, and the corresponding original text is xxx.
3. 精读外刊
	 Please help me analyze the following articles used as English study materials.
	 Reply me in Chinese.
	 The requirements include a summary of the articles, analysis of the structure of the article,
		understanding the key sentences and ong sentences in the article,
		and extracting the authentic usage of the article: XXX
4. 查找外刊:
	 I want you to act as the character xx in the movie/book/..."xx".
5. 筛选阅读材料:
	 我的四级成绩是xx分,词汇量xx,可以阅读xxx吗?

** writting
写作纠错:
	Please help me proofread and revise this email I wrote to my professor about missing a class.

** 学习计划
30天备考雅思...


** Summary
	 I want you to act as an English teacher. I'm going to ask you a few of English questions.
*** words
1. look up comprehensively:
		Could you provide me with details about the word 'XXX,'
		 including its phonetic symbol, different forms, definition,
		  etymology, root affix, usage, example sentences, and phrasing?
		Could you provide me with details about the word "pregnant",
			including its phonetic symbol,
			all of the forms of the word: noun, verb, adjective, adverbial,
			all of the meanings of all of the forms,
			root affix,
			usage,
			example sentences,
			and phrasing?

2. make a sentence:
	 Could you please use the word "XXX" in a sentence?

3. create an article:
	 Could you write an engaging article using the words 'egg', 'apple' and 'ambition'?
	 Please bold ** ** these words in the article to make them stand out.

4. difference between words:
	 Could you please help me understand the distinction between A and B
	 and how they are used in different contexts?

5. A detailed explanation of phrase collocation:
	 Please help me explain the following grammar: the usage of xxx
	 
*** voice
1. correct mistakes:
	 I want you to act as an English teacher and let's talk about friendship.
	 And please correct me if I make any mistakes.
1. more natural expressions:
	 What is a more natural way to say "XXX"?
2. Movie and TV lines
	 Can you create a dialogue like the one in the movie/book/... "xxx" about xxx?
3. Cosplay
	 I want you to act as the character xx in the movie/book/..."xx", then chat with me.
	 I want you to act as the character Ross in the TV shows "Friends", then chat with me.
*** reading
1. analyze sentences
	 I want you to act as an English teacher.
	 I will send you some English sentences and you will analyze them carefully as linguist.
	 Here are the sentences: XXXX
2. analyze questions:
	 I want you to act as an English teacher.
	 I am doing xxx reading questions in English, please help me analyze why the answer to this question is x.
	 The question is xxx, and the corresponding original text is xxx.
3. Read articles carefully:
	 Please help me analyze the following articles used as English study materials.
	 The requirements include a summary of the articles, analysis of the structure of the article,
		understanding the key sentences and ong sentences in the article,
		and extracting the authentic usage of the article: XXX
5. Check reading materials:
	 My CET4's grade is xx, my volumn of vocabulary is xx, can I read Harry Potter?

*** writting
Correct writting:
	Please help me proofread and revise this email I wrote to my professor about missing a class.

*** 学习计划
30天备考雅思...
