#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* table of contents
- 一.阅读的深度
	1. 阅读活动和艺术
	2. 阅读的等级
	3. 阅读的Lv1: Elementary Reading
	4. 阅读的Lv2: Inspectional Reading
	5. 如何成为有追求的阅读者
		 -------------------阅读的Lv3:Analytical Reading
	6. 书籍归类
	7. X-ray书
	8. 与作者妥协
	9. 找到作者的信息
	10. 公正的批判一本书
	11. 同意/不同意作者
	12. 看书的帮助
			-----------------阅读不同书的方法
	13. 读实践书
	14. 读幻想类文学作品(如:哈利波特)
	15. 故事/表演和诗歌
	16. 读历史书
	17. 读科学和数学
	18. 读哲学类
	19. 读社科
			-----------------阅读的终极目标
	20. 阅读的Lv4:Syntopical Reading
	21. 阅读与思维的成长
** inspectional reading 1: Systematic Skimming or Pre-reading
how:
	1. 快速看标题,有前言就看前言. 完成这步前,你应该知道这本书干嘛的,然后这本书归类于什么?
	2. Study目录, 目标要得出书的结构,作为导航的地图
	3. 对下索引
	4. 有外包装的看外包装
	5. 看你认为是中心的章节,一般是第一章和最后一章,看开头和结尾
	6. 打开书,看个一两章,或者几页,不要看太多了

** inspectional reading 2: Systematic Skimming or Pre-reading
看的书要学会ignore details

** The Third Stage of Analytical Reading
	----------I. The First Stage of Analytical Reading: Rules for Finding What a Book Is About
1. Classify the book according to kind and subject matter.
2. State what the whole book is about with the utmost brevity.
3. Enumerate its major parts in their order and relation, and outline these parts as you have outlined the whole.
4. Define the problem or problems the author has tried to solve.
	----------II. The Second Stage of Analytical Reading: Rules for Interpreting a Books Contents
5. Come to terms with the author by interpreting his key words.
6. Grasp the author's leading propositions by dealing with his most important sentences.
7. Know the author's arguments, by finding them in, or constructing them out of, sequences of sentences.
8. Determine which of his problems the author has solved, and which he has not; and of the latter, decide which the author knew he had failded to solve.
	----------III. The Third Stage of Analytical Reading: Rules for Criticizing a Book as a Communication of Knowledge
	-----A. General Maxims of Intellectual Etiquette
9. Do not begin criticism until you have completed your outline and your interpretation of the book. (Do not say you agree, disagree, or suspend judgment, until you can say "I understand.")
10. Do not disagree disputatiously or contentiously.
11. Demonstrate that you recognize the difference between knowledge and mere personal opinion by presenting good reasons for any critical judgment you make.
	 -----B. Special Criteria for Points of Criticism
12. Show wherein the author is uninformed
13. show wherein the author is misinformed.
14. show wherein the author is illogical.
15. show wherein the author's analysis or account is incomplete.
	Note: Of these last four, the first three are criteria for disagreement. Failing in all of these, you must agree, at least in part, although you may suspend judgment on the whole, in the light of the last point.

----------------------------------------
RULE 1. YOU MUST KNOW WHAT KIND OF BOOK YOU ARE READING, AND YOU SHOULD KNOW THIS AS EARLY IN THE PROCESS AS POSSIBLE, PREFERABLY BEFORE YOU BEGIN TO READ.
RULE 2. STATE THE UNITY OF THE WHOLE BOOK IN A SINGLE SENTENCE, OR AT MOST A FEW SENTENCES (A SHORT PARAGRAPH).
RULE 3. SET FORTH THE MAJOR PARTS OF THE BOOK, AND SHOW HOW THESE ARE ORGANIZED INTO A WHOLE, BY BEING ORDERED TO ONE ANOTHER AND TO THE UNITY OF THE WHOLE.
RULE 4. FIND OUT WHAT THE AUTHOR’S PROBLEMS WERE.
--------------------What is being said in detail, and how?
The Seond Stage of Analytical Reading, or Rules for Finding What a Book Says
RULE 5. FIND THE IMPORTANT WORDS AND THROUGH THEM COME TO TERMS WITH THE AUTHOR.
RULE 6. MARK THE MOST IMPORTANT SENTENCES IN A BOOK AND DISCOVER THE PROPOSITIONS THEY CONTAIN. 
RULE 7. LOCATE OR CONSTRUCT THE BASIC ARGUMENTS IN THE BOOK BY FINDING THEM IN THE CONNECTION OF SENTENCES.
RULE 8. FIND OUT WHAT THE AUTHOR’S SOLUTIONS ARE.
--------------------
The Third Stage of Analytical Reading: Rules for Criticizing a Book as a Communication of Knowledge

A. General Maxims of Intellectual Etiquette
RULE 9. YOU MUST BE ABLE TO SAY, WITH REASONABLE CERTAINTY, “I UNDERSTAND,” BEFORE YOU CAN SAY ANY ONE OF THE FOLLOWING THINGS: “I AGREE,” OR “I DISAGREE,” OR “I SUSPEND JUDGMENT.”
RULE 10. WHEN YOU DISAGREE, DO SO REASONABLY, AND NOT DISPUTATIOUSLY OR CONTENTIOUSLY.
RULE 11.RESPECT THE DIFFERENCE BETWEEN KNOWLEDGE AND MERE PERSONAL OPINION, BY GIVING REASONS FOR ANY CRITICAL JUDGMENT YOU MAKE.

B. Special Criteria for Points of Criticism

** preface
learning how to read;
a much more comprehensive and better-ordered analysis of the complex art of reading;
the flexible application of the basic rules to different types of reading to every variety of reading matter
the discovery and formulation of new rules of reading; and the conception of a pyramid of books to read, broad at the bottom and tapering at the top

** 1 THE ACTIVITY AND ART OF READING
这本书是为想有更好的understanding的读者写的.

We had to read because radio and television are never enough for curious and intelligent people.

Modern communications media hasn't much enhanced our understanding of the world.

We have so many facts that we can't understand it.

一些思想被打包成了磁带,我们成了录音机,按个按钮就播放,却没有想过适不适合.

*** Active Reading
这样阅读书的rules,follow和practice之后,可以用来读任何文本

阅读相当于啃肉,越积极越能啃点东西下来,还有得是肉,不是垃圾.

阅读和听不是像等待法庭的审批,而是像棒球手一样去接住作者的球.

写东西就是棒球的发球手, 读就是棒球的接球手, 唯一被动的是这个球.

阅读的技能就是接住各种各样的发球,不论是快球,旋转球,变球还有关节球.

非常值得注意的是, 写作和阅读是互相合作的,写作打出的球是为了让阅读能接到.换言之,故意不让接的球干脆别接.

写作的人比阅读的人(未训练的)更容易接到球

知识比球复杂,所以就有了接受的多少

Reading actively and more skillfully. 两者息息相关的

*** Reading as Learning: The Difference Between Learning By Instruction and Learning By Discovery
information和understand的不同

information知道是怎样就够了.understand要知道所有,为什么是这样,跟其他事情的联系,什么方面是相同,什么方面是不同的等等

information就是remember, understand是explain

~

书呆子,读太多书,又没读好. sophomores半吊子

business of reading and its relation to education?

Instruction就是别人教, discovery是自己发现

~

像农民种庄稼一样,最后评价标准一定是庄稼长大和长好.老师教学生也同样,最后一定是学生学习,然后grow his mind.

unaid discovery 和 aided discovery 包括了reading和listening

thinking和instruction和discovery是不同的学习

thinking在active instruction中也不缺少

reading包含了discovery中的一切活动: keenness of observation, readily available memory, range of imagination, and an intellect trained in analysis and reflection. 

*** Present and Absent Teachers
要阅读做discovery的第一优先,听做第二优先.因为阅读是没有老师的学习,听讲是有老师的学习.

问老师问题,老师会回答你,不懂老师会给你解释.
但如果问书问题,你就得问你自己,更像是真实世界,你必须自己思考和分析.

~

没老师的帮助,也得自己学习.

** 2 The Levels of Reading
1. Elementary Reading
2. Inspectional Reading
3. Analytical Reading
4. Syntopical Reading

阅读就是unaided discovery, 能学到多少, 取决于我们的努力还有知道how.

reading levels之间的区别搞不懂,就不会有阅读技能的提升.

reading levels是累积的,高级的一定包含了低级的.

--------------Elementary Reading
What does the sentence say?

Elementary Reading就是小学该学到的阅读技能.

Elementary Reading就是能理解字面意思.比如说猫蹲在帽子上,就知道哦猫,帽子,蹲在帽子上.

简单来说就是这句话讲啥了?

~

Elementary Reading遇到的困难主要是mechanical, 要靠提升速度解决, 具体第四章会讲.

--------------Inspectional Reading
What is the book about? or What is the structure of the book? or What are its parts?
What kind of book is it--a novel,a history,a scientific treatise?

Inspectional Reading要着重速度了,比如给5分钟阅读全文.

Inspectional Reading就是用最少的时间得到全文大意.

Inspectional Reading又叫Skimming或pre-reading,但是是系统性的Skimming.

Inspectional Reading的目标就是学到书中所有表面的东西.

~

~

----------------Analytical Reading
Analytical Reading的难度取决于文本本身的难度.

Inspectional Reading是限定时间内学得最好, Analytical Reading是无限时间学到最好.

Analytical Reading必须问许多有组织的问题.(Part Two会提)
Analytical Reading is always intensely active.
有些书尝尝味道就好,有些囫囵吞下,有些书需要反复咀嚼和慢慢消化直到书真正变成自己的.

Analytical Reading如果仅仅只是为了entertainment或information,是不需要的.
如果是为了understanding,不好意思,必须Analytical Reading

--------------------Syntopical Reading
最复杂和要求最多的阅读,怎么个要求多呢?即便是相当简单和知识不密集的text,对于读者都有非常重的要求.

Syntopical Reading别名是Comparative Reading, 需要看很多书,进行一个对比.
但是又不仅仅是对比,需要读者自己去construct一个新的analysis.

Syntopical Reading也有一堆规则不为人知.

** 3 The First Level of Reading: Elementary Reading
阅读时代的三个历史趋势:
	1. 美国扫盲
	2. 开始教授自己阅读
	3. 批评学校的教育
stages of Learning to Read
	1. 读可读的, 从出生到6-7岁
	2. 读非常简单的材料, 到后期可以带着喜爱独立阅读.会解除到抽象字符
	3. 建立词汇量,可以根据上文线索去理解.可以独立阅读, for fun, curiosity, expand one's horizon
	4. 增强以上的技能, 往后余生.
Stages and Levels
	stage1-4都包含level1
	high school work, 只是level1
Higher levels of Reading and Higher Education
	大学也很少有教超过level1的
Reading and the democratic ideal of education

70年代是阅读时代,关于阅读的研究和实验也是层出不穷.

三个历史原因造就了这个时代.
第一, 美国从建国开始就扫盲,并且当作是民主的基本国策.
	扫盲工作已经有很多成绩了,但是还是部分高动机而且大部分父母有文化的孩子学得好,离教育每个孩子不论动机和父母还是差得远.

第二,是教学法的改变,不再是希腊和罗马学校的教法.
	ABC组合法:先单个字母,再组合成语言.

Phonic法: word被识别为声音而不是字母(音标的出现)

visual法: 认整个单词,整个句子,而不是字母.
	但是发现oral reading和silent reading还是不同.会oral reading,不一定会silent reading, vice versa. 

这些方法有些学生成功,有些失败.失败引来了对于学校的批评.这是第三个历史原因.

批评家不总是对的,但是教育公民的问题显得很迫切,导致很多高中和大学的出现.
阅读不行是本人的事, 但是在学校也是老师和同学的事情.

因此,各种方法在当代就被不停实验.

*** Stages of Learning to Read
孩子成熟阅读的进程:
	1. reading readiness: 0-6 上幼儿园之前
		 注意,如果孩子不愿意去学,千万别强行教.强行教的后果是以后都不爱学了,甚至会带到成年.
	2. read very simple materials
	3. symbols: vocabulary building and increasing skill"根据上下文猜不认识的词"
	4. 1-3增强,可以从不同的材料中提取概念,看相同科目的不同的作者.
		 成熟期,应该在青少年达到,余生持续.

*** Stages and Levels
~

reading readiness对应学前教育
word master对应一年级
vocabulary growth and the utilization of conext对应二到五年级.
mature: 6-8年级
到成熟期后,可以在知识量不那么多的情况看所有书了.

可是即便是成熟期了,仍然只是在elementary level

stage4靠老师就够了,但是接下来就得靠他自己了.

*** Higher Levels of Reading and Higher Education

** 4 The Second Level of Reading: Inspectional Reading
Inspectional Reading是一个真正的阅读等级,和elementary reading,analytical reading完全不同, 但是他们存在逐级包含的关系.

想要Inspectional Reading, 那elementary reading必须过关.
不能查太多单词和语法,句子大致的意思得懂不用完全懂.
	wusd:看英文书某章之前,有必要完全扫一遍,搞定单词和语法.

~

What is involved in inspectional reading? How do you do it?
	wusd: Systematic Skimming & Superficial Reading

inspectional reading的技能是一个技能,但现在作为初学者,还是分开好,等有经验了再综合.

*** Inspectional Reading I: Systematic Skimming or Pre-reading
有本新书摆在你面前,第一件事你要做什么?

一种场景: 1.你不知道怎么书值不值得Analytical Reading, 是否有insight和information值得你去dig out

2. 你只有有限时间去搞清楚值不值这个事

在这种场景,一定要skim or pre-reading it.
能搞清是否值得继续读,即使不继续读也能得到书的很多信息.

skim书能让你知道作者大意是什么,书的类型是什么,这样时间没有被浪费.

Some suggestion about how to skim it:
	1. 快速看封面和前言.
		 注意看: 副标题~书内容的范围~书的目标~作者在这个subject的独特视角.
		 目标: 对subject了解,给书分类.
	2. 学!目录.
		 注意: 不要只在查内容的时候才看目录,大部分作者对目录都非常用心的
		 目标: 生成a road map
	3. 看索引
		 看索引的terms的范围,判断一下最重要的terms以及目录提到的terms
	4. 看发行商的书边
		 --------------------
		 做完这4步后,合下书,问问自己还看不看这本书了
	5. 看重要章节, 仔细看章节的开头和结尾总结性的句子.
	6. 开始看书的内容了,但是一次只能看个一两段,按顺序看.
		 不要漏掉最后几页,因为作者总是会总结一下.

这样看,几分钟绝对不超过一个小时(实际不止,因为英文水平不行).

多少次,你看未知领域的书一片茫然?
你按这个方法走, 绝对不会出现这种情况,这是非常积极主动的阅读.

把自己当作一个侦探在寻找书的主旨,任何能帮你实现这个目标的线索都要警醒.


*** Inspectional Reading II: Superficial Reading
标题是故意起Superficial的,而且我们是认真的

很多人第一次看难书总是非常挣扎,很自然得出结论自己看这种书是种错误.
其实看书不是错误,而是第一次看就不该带那么高期望,方法也错了.

正确的方法是: 第一次处理一本难书,从头到尾看一遍,不要去查也不会去深思不懂的东西.
wusd: 有点类似考试,也把容易的题目做了再说

简单来说,遇到不懂的就跳过,懂的就抓牢来.不要因为自己错过一些内容就灰心丧气,如果你自己想啃下难点,会被困在里面.
啃下难点,要等到第二步了.
wusd: 跟拼图一样,先把能拼好的拼好,不能拼好的一直卡着只会浪费时间,后面难拼的第二边也许就能拼好了.
	那么小时候坚持为什么就能行呢? 因为小时候没有遇到真正的困难!

这么略读的好处就是,之前懂的一部分,有助于你后面的部分;即便是没有有助你后面的部分,懂一部分总比卡住什么都不懂要好.

从小到大被教育要克服困难,不懂的词就查,不会的就查百科全书.
但是就阅读而言,这个只会阻碍我们读书.

~

太执着于细节,就会只见树木不见森林.You will not be reading well on any level.
wusd: 可以看Games Theory for general reader

*** On Reading Speeds
Inspection Reading就是在限制时间内得到书的主旨.
不论这个书他有多难,合格的reader会尽快的把inspectional reading完成.

the levels of reading and speed reading courses?

speed course仅仅是补一下elementary reading,不够

好的speed course应该是教你根据内容的性质和复杂程度来决定快慢的.

好多烂书连skimming都不配, speed reading可以解决它.
但是,阻碍理解的困难:wusd: 有必要放进去reading levels
	- does not know what to do when approaching a difficult ???
		跳过
	- does not know the rules of reading ???
		第一遍,懂得过,不懂的扔
	- does not know how to marshal his intellectual resources for the task
	- does not know what he is looking for and does not know when he has found it
		带着问题去读书

关于阅读速度,是能够用不同速度阅读,知道什么时候用合适的速度.
wusd: 好比是开车,要兼顾安全性和速度,有调速度的技能+要知道什么路该快~什么路该慢.
inspectional reading很快是因为读的内容少(目录/简言...),用不同的方法阅读(superficial),带着不同的目标(主旨)
analytical reading就要像老司机一样开不同的档了.

*** Fixations and Regressions
wusd: 不看

*** The Problem of Comprehension
阅读速度是上来了,理解呢?
wusd: 阅读的目地是为了理解

积极阅读的一个activity: with concentration

单单concentration只能解决elementary reading的问题.
speed reading courses并没有解决comprehension更高级的问题.

~

对于抽象和修辞的词,应该快速带过.

~

阅读速度的问题就是理解的问题. analytical reading就是解决理解的问题,没有analytical reading你就不能理解一本书.


*** Summary of Inspectional Reading
有能力按不同速度阅读+知道什么时候什么速度阅读是最理想的.
Every book should be read no more slowly than it deserves, and no more quickly than you can read it with satisfaction and comprehension.

skimming必做,可以得到书的主旨和结构.

不要第一次就尝试啥都懂,难书就要多读几遍.superficial on inspectional reading

--------------------
inspectional reading在syntopical reading很重要,到时候会回顾

inspectional reading是analytical readig 的两个stage
	1. systematical skimming: book's structure
	2. superficial reading: the first step in the interpretation of book's contents

下一步要谈谈read actively里的activities了.

** 5 How to be a Demanding Reader
看书时保持清醒比睡着了要困难的多.

是否捧在书里看书,决定是否能在昏暗烛光下保持清醒.

如果想从书里收获点东西,就需要尽可能地积极阅读.

把好书当催眠药是非常明显的浪费,如果说是为了有所收获,这样做只会达到打败自己的目的.

即便是知道自己看书是为了entertainment还是understanding, 但是如果不是一个demanding reader,仍然是很难从书中获益.

*** The Essence of Active Reading: The Four Basic Questions a Reader Asks
!!!积极阅读的核心在于: 在阅读的时候问问题,而且这些问题你必须自己尝试去回答.

这些问题不是瞎问的,要按正确的顺序问正确的问题.

四个主要问题:
1. 这本书主要讲的是什么?
	 书的主题是什么,拆分出哪些子主题,子主题之间的顺序又是怎么样的.
2. 详细说了什么,怎么说的?
	 作者是怎么论证他的主题的.
3. 这本书是全盘对的,还是部分对的?
	 看书是为了构建自己的思想,尽信书不如无书.
4. 那又如何?
	 为什么作者认为这个事很重要?对你来说很重要吗?
	 书如果即便没有告诉你,也启发了你,有必要去进一步探索.

demanding和undemanding reader的区别就在问不问问题了.

inspectional reading 倾向搞定问题1-2, 问题3涉及的少.
analytic reading搞定问题3
syntopical reading搞定问题4

光知道问题还不够,还得去做,还要准确回答这些问题.
有这个能力就是阅读的艺术.

~

*** How to Make a Book Your Own
问问题不够,还得回答它.用脑子想,不如用笔划,做的哪些标记就是警示器.

write between the lines???

完全拥有一本书的方法,是在里面做mark.

为什么mark好?
1. 让你的清醒地看书
2. 什么时候读书读懂了?
	 能够输出的时候!!!不能输出的话,你以为你自己懂了,实际上你是没有懂的.
	 mark就是一种输出!!!
3. mark可以记录下你当时想法.

理解是两方面的努力,问自己和问老师,有时候要跟老师争辩.
mark就是一种方式表明你自己和老师的分歧.

mark的方法!!!需要做笔记的时候,回头再看

书倒数第二天,可以outline一下.

*** The Three kinds of Note-making
3中note-making, 用那种取决于阅读level

inspectional reading在你脑子有新东西记录下很重要.

inspectional reading的问题:
	1. 这本书是什么类型?
	2. 书主要讲的是什么?
	3. 主题的框架是怎么样的?
把答案记录在目录页上.

这种笔记叫记框架.

inspectional reading搞定框架,但是不搞定细节.
analytic reading搞定细节,关注作者的概念还有你自己的概念和看书时衍生的概念

~

structural note和conceptual note.
syntopical note也是conceptual 的,但是是散布在多本书的

!!!还是没搞懂,等syntopical reading再回头看


*** Forming the Habit of Reading

*** From Many Rules to One Habit

** 6 Pigeonholing a book
不同书有不同的难度,所以要做个分类
rule1: 你必须知道你阅读书的种类,越早越好甚至在你读之前
	inspectional reading会帮你做到这里
标题能教我们很多,尤其理论和实践书差距很大
理论和实践的书有一套经典的划分,但是也有些是不分的.
理论的书有不同种的类型,需要用不同的方法去学.

我们说阅读的方法可以用在任意文本,但实际在part two只用在整本书.why?

答案就是看整本书比看其他任意文本难,会看整本书其他文本不在话下.

这些rules可以用到书上,你很容易调整用到其他材料上.

*** The importance of Classfying Books
rule 1: 必须在读这本书的时候知道书是什么类型,在读书这个过程中越早越好,甚至在你开始阅读之前.

这类型是小说还是说明文?这个看上去很容易知道,实际上并没有那么明显的界限.

上面的书都被划到了小说了,但是其实并不明确的.比如说:宇宙和爱隐士但,可以当小说读又是物理书.

说明文就是汇集了很多的知识,但是不同的说明文用的方法也不一样.

方法就是inspectional reading,然后再分类.

*** What You Can Learn from the Title of a Book
不注意signals的人数远超想象.我们一直问学生,书讲的是什么啊,书是什么类型.通常没有答案.

举个达尔文,物种起源的例子. 他的title是什么?

The Origin of Species VS The Origin of The Species(= The Descent of Man).
一字之差竟然差了这么多,很少人认真读标题然后思考标题到底是什么意思.

结合罗马帝国消亡史和第一章The Empire in the Age of the Antonines.
你就该知道Antonines是罗马皇帝最顶盛的时候,很遗憾很多读者不懂这个,接触很多新书也是同样如此.

前言和目录很重要啦,是作者煞费苦心地帮你去理解这个书是什么类型的.

要是读者忽略这些东西,那看不懂书只能怪自己了,回答不了那些问题也是自然的.

title虽然很重要,但是却不足以让你能够分类,还得靠你自己脑子里面有书的分类.

如果你不懂Elments Geometry Principle Psychology,你就不知道Euclid’s Elements of Geometry and William James’ Principles of Psychology是啥类型书?
如果你不知道现实问题是什么,现实有多少种问题,那么你也不知道亚里士多德的政治学和亚当斯密国富论的异同.

title有时候直接就告诉你分类了,比如: Euclid’s Elements, Descartes’ Geometry, and Hilbert’s Foundations of Geometry都是数学书.
但是有时要小心看章节才知道说什么了,比如: The City of God, Hobbes, Leviathan,and Rousseau’s Social Contract都是政治读本.

你必须自己创建分类,而且这些分类stand up to the test of time.

大致的分了下类, 故事/说明文, 说明文->历史vs哲学+科学vs数学

大多数书都可以扔到对应分类当中,但是总有书有例外.

麻烦的是我们分类的原则,我们更高级分类是会谈到这个原则.
但是,我们现在要面对一个区别,那就是理论和实践的书的区别.

*** Practical vs. Theoretical Books
practial就是要工作立即或一段时间内取得效果, theoretical就是讲理解这个事物.

action如何依赖于knowledge的呢?科学与技术就是完美的例子.

有些书和老师只专注于交流知识本身,但是有一些人既交流知识本身,又对知识的运用有独特的视角.

想要运用知识,就必须把知识转化成一系列行动的规则.
theoretical book告诉是什么, practical books告诉你怎么做或应该做什么.
wusd: 亚里士多德的伦理学,如何获得幸福

艺术说明书,实践手册书像:engineering~medicine~cooking,道德类书像:经济学~伦理学~政治学,
这些都是实践书,教你怎么做和该做什么.

有些人会说经济学不是practical book, because it was not true or would not work.

经济学书如果不准的,那么就是垃圾书.
伦理学书教我们什么要做,什么不要做,会有什么reward and punishment.
还有种书单纯告诉我们人们的行为,没有judge it, 那就是theoretical了.

经济学书的除了那些人们的行为,经济行为的数学分析,其他都在教个人,社会国家要做什么不要做什么.
我们尽管不认同他是practical,但是他就是.

~

~
wusd:这本书和"我有一个梦想"一样都在劝你做什么,相信什么, 也是实践的书.

政治演讲 和 口号鼓动做事情,又不一样.

"the art of" "how to", 道德类, 工商类, 经济学, 法律, 医学.都可以认为是practical

~

An Essay Concerning Human Understanding and A Treatise Concerning the Origin, Extent, and End of Civil Government.
这里title告诉了好多: understanding是theoretical, government是practical.
谈某个问题是theoretical, 谈如何激起这个问题又是practical

inspectional reading说还有必要看下,主要章节的首尾.

这是因为哦,有时后单单看书的首尾,是无法区分到底是什么书的.

practical book关键字: should, good, ends and means
theoretical book关键字: is

~

还是要看内容,作者会把搞不清楚两者的区别.

*** Kinds of Theoretical Books
大家都知道理论书分为三类:历史,科学,哲学;但是当真正想要准确区分的时候,就陷入麻烦了.

历史书不但描述过去某个时检点发生的事情,而且还有一段时期内的变化.
作者经常把自己的评论,视角,重要性给加上去.

历史就是特定时空存在的事物.

和历史不同,科学是大多数时空,或者任意时空发生的事物.

科学书和哲学书经常是专有名词的科目,比如:物理,心理学.
但是他们又有交叉,比如心理学既是科学的又是哲学的,又互相串门,比如牛顿的自然哲学,压力的物理.

科学和哲学是解决一类问题,而不像历史具体哪个事件.
哲学和科学思考问题的角度不同,因为解答问题的方式也是不同的.

区分科学和哲学有个好用的标准,如果是看得见摸得着的那么是科学的,否则是哲学.
wusd: 比如鸡生蛋,蛋生鸡的问题.就是哲学问题.

科学这玩意可以被重复观测.
wusd: 牛顿第一定律的斜坡实验,可以被重复观测.

不懂!!!

~

科学是实验的,而哲学仅仅是思考.科学有时候是超越日常的实验.

科学家和哲学家都需要观测和思考得出结论.科学家靠的是特殊实验~经历,哲学家考得是common experiences.

书里的内容也会告诉你是科学的还是哲学的.

~

历史书必要遵守讲故事的一系列规则.

这些分类重要吗?

不同类的课堂,老师会用不同方法教,你也会用不同的方法学.

哲学老师喜欢白纸,而科学老师喜欢经验丰富的.

这些不同类型的书和课程,要老师或作者按不同方式,同样的也要我们用不同恰当的方式去学.


** 7 X-raying a book
每本书都骨架隐藏在里面,把他找出来.

书都是皮肤包着骨架,皮肤穿着衣服.
你要做的就是就X-ray一样的眼睛去把骨架给找出来,这也是理解最重要的一步.

这个骨架是两个东西:大意(unity)和各部分的组织(an organization of parts),直指规则2和3.
任何值得一读的书都有这个骨架,而且还都不一样.如果书没有这个骨架,就是垃圾,不值得去读.

~

RULE 2. STATE THE UNITY OF THE WHOLE BOOK IN A SINGLE SENTENCE, OR AT MOST A FEW SENTENCES (A SHORT PARAGRAPH).
用一句话或者一小段说明全书大意.

这个和Rule1找出是什么科目或者类型是不一样的,简单来讲就是全书的主题或主要观点.

书作为一项艺术工作,跟画画音乐,小说和戏剧一样,都有无处不在的主题或主要观点(unity).

不要满足于我感觉到了unity,要用简洁的语言把它output出来.
如果一个读者说,我知道是什么,但是我只是说不出来.实际上他连骗自己懂了都做不到.

RULE 3. SET FORTH THE MAJOR PARTS OF THE BOOK, AND SHOW HOW THESE ARE ORGANIZED INTO A WHOLE, BY BEING ORDERED TO ONE ANOTHER AND TO THE UNITY OF THE WHOLE.
把主要的几个部分用有机的方式组合成一个整体,指向书的unity.

光知道一个个的部分是不够的,这些部分的组合起来才是一个整体或者就是个集合,没有任何意义.

书就好像房子一样,有不同的房间.
不同的房间有不同的大小,不同的装饰,不同的功能,房间内部又有自己的结构.
房间与房间之间也不是互相独立的,有交通阡陌的.
这些全部组合起来,才能够助人,而不是一堆砖块乱放一起.

好的房子内部的房间本身有一定的独立性,有内部的装饰,但是又和其他房间很好的结合起来.

好的书就是好的作者搭建的好的房子.
虽然这种房子很复杂,但是对比差房子,功能和结构很复杂,但是却组织地更好,更好一体化.

如果你要了解整个房子,你是作者当然知道游览计划了.
但是作为读者,你要靠自己找出这个游览计划来,这样才能更好地理解这本书.

*** Of Plots and Plans: Stating the Unity of a Book
规则二,揭示书的大意.给一些例子帮助你实践起来.

荷马的奥德赛里面充斥了大量的细节,海上和陆地的探险故事,各种场景.
但是即便是这样,也是有主线的有大意的.

亚里士多德坚称这是每个好故事的标志,还用几句话描述奥德赛举例.

奥德赛巴拉巴拉...

亚里士多德说这是最基础的主线,其他都是分集.

好的故事坏的故事都有个主线的.像一般的love story的,都是男孩遇到女孩,男孩错过女孩,男孩得到女孩.
好故事和坏故事的差别,就在于是否把主线发展的好.

你不用总是自己找主线,作者会帮你.
比如Jeremy Collier,题目就告诉你了他是讲不道德和渎神的事物.

作者有时候会在前言里告诉你unity.
教你的书和小说这方面就差别很大,不会让你觉得悬疑,恨不得第一段就把所有的都告诉你.

可以按作者给你的unity一步步探索,但是不要忘记最终这个unity还是需要你自己总结,等到看完整本书后忠实地总结自己的unity.
unity既有作者的一份任务,同样有读者的一份任务.

Herodotus’ history of the war between the Greeks and the Persians.

上面这个书就是研究Herodotus,希望不被世人遗忘希腊和Barbarians往日的荣耀.

~

~

~

Aristotle's Ethics

~

The Wealth of Nations.

如果读者写了国富论的大意,又同样写了资本论的大意,就能知道这两本最流行书的关系.

~

The Origin of Species.

听起来很拗口,但是实际的书更复杂,19世纪人们甚至搞不清楚到底它的大意是什么.

Concerning Human Understanding.

在开始前有两件事希望你注意.
1. 你可以经常期望作者把书的大意告诉你.遗憾的是很多读者不看作者的介绍,就像不看标题一样.
2. 注意,不要把我们给的大意当作唯一正确的,只要简洁~准确~解释性的大意都是可以的.

这个大意可以不同,因为对于每个读者来说书都是不一样的.
但是读者的大意仍然有客观的一个标准,因为书是一样的.

*** Mastering the Mulitiplicity: The Art of Outlining a Book
如果不去看各个部分,那么理解不了整体.但是如果不去看各个部分之间的关系,也理解不论整体.

为什么要分为unity和outlining两步呢?
为了更好地理解,第一步unity,可以看到major parts;第二步可以把每个part,当作一个小整体,有自己的unity和自己的复杂性.
类似于写程序, 先主方法,然后分方法里面有其作用和内部复杂性.

先写出unity,后面可能按这个outline???
	1-2-3-4,1-1.1-1.2-1.3, 1.1-1.1.1-1.1.2

好吧,这是一种方法.
但实际上一个读者不会显性地做这个事情,但是如果让他去outline,可能也是和这个方法差不多.

近似就够了,不用完全按这个来,不要有压力,够用就行.

不同书的性质和你的阅读目地,都会导致你outline的方法不同,但是你必须知道完整的方法,以便你可以大致按照这个来outline.

个人的生命是有限的,书的知识也有时效的.
所以,outline只要out书本身就好了,不要out书涉及的科目.
但是也不是说要偷懒,而是必须遵守这个规则.

举个outline的例子是很困难的.
unity一两句话撑死一小段搞定,但是要outline structural有时候要好几页才能达到理解和值得一看的程度.

一大堆的例子,outline比原文长.例如: 中世纪对亚里士多德的注解,注解版的撒施比亚,现代的纯粹理性批判....

~

美国宪法的outline:
1. 前言:宪法的目地
2. 文1:立法
3. 文2:执法
4. 文3:判法
5. 文4:联邦和州立政府
6. 文5-7:宪法修订,土地法,披覆
7. 10修订: 财物的权力
8. 其他修订

文1的outline:
1. Section1: 立法分为参议院和中医院
2. Secetion 2-3: 
3. Section 4-5:
4. Section 6:
5. Section 7:
6. Section 8:
7. Section 9:
8. Section 10:

像Article1一样,会分为许多topics和subtopics

你也可以把文1-3合并起来,因为它们处理的问题相同.
按这种方式,你可以有自己的分法.

~

~

作者按他的方法outline为了写好了,你按你地方法outline为了读好了.
你的outline可能比他差,但是也可能比他好,关键要靠自己去outline.
如果你们都完美outline,那么会你们的outline一模一样.

不要被动地只按作者给的章节分段,要把它当作一个指南去用.
很多作者章节分的并不好,有时候章节分的只是表面的框架,真实的框架还隐藏着,有待于你自己去挖掘.

按rule2去state unity,经常是碰运气的.你得按rule3去做,去检验你rule2做的对不对.
所以,rule2后面必须紧跟着做rule3.

按rule2去state unity就像小孩子学会了2+2=4,但是他不知道为什么,因为他不懂数学.
所以rule2做完后,必须紧跟rule3,根据outline知道unity的how和why.


*** The Reciprocal Arts of Reading and Writing
rule2和rule3在reading里面有,在writing当中也同样有.就像教课和被教.

reader就是发现隐藏在flesh里面的skeleton,而writer就是把skeleton隐藏在flesh下,而不是脂肪.
flesh要足够薄,避免松弛的flesh,这样关节的地方可以被识别,主要部分也可以被表达.

为啥还要写书,直接给大纲不就好了吗?
不能直接给大纲,有些读者不能或不愿意读大纲倒是次要的.
Flesh和skeleton都是书的一部分,一样的重要.
按照skeleton去增加flesh,就是在给书以前没有过的生命.

unity,clarity和coherence.
unity就是rule2.
clarity和coherence分别对应part之间是区分的和parts有好的顺序.

如果你很快明白了unity,却不能明白parts以及parts之间的关系,这本书很有可能不是本好书.
不要那么快下判断,也不要怕下判断.错误有可能是你的,也有可能是书的,有些作者没有按这些规则来写书.

rule2和3同样也可以用在记叙文的板块,因为独立,有自己的unity和自己complex.
记叙文和小说不一样,小说可能整本都看完了,但是仍然不明白大意在那里,因为诗在诗外.

*** Discovering the Author's Intensions 回去翻看倒数第二段,然后有些问题需要根据书不同改一下
rule4. FIND OUT WHAT THE AUTHOR'S PROBLEMS WERE.
实际上是rule2-3的另一种重复.但是这种重复很有用,它用另一种视角来看整体和各个部分.

rule4: 找到作者的问题是什么.
作者的书以一系列问题开始的,可能在书里有答案也可能没有.

作者可能会给明确的问题和答案,但是也可能不给.
如果不给的话,作为读者要靠自己去生成问题.
注意, 问题要既有总体的问题,也有各个部分的问题,而且还有有优先级.

rule2-3其实已经回答了问题,这样看rule4是rule2-3的延伸.

rule4和rule2-3有很大不同,甚至可以帮你克服一些困难的书.
但是不要用解读作者写书时心理的方法.
应用rule2-3,即便是技能再好的读者,也会犯一些错误.主题抓得不够明确,框架理解的不够.

all practical questions

*** The First Stage of Analytical Reading

** 8 Come to a term
analytical reading stages?
1. 大纲
2. 内容
3. 交流知识

analytical reading 的stage1有四条规则,能让你知道书大概说什么和列大纲.
stage2同样有四个规则,第一条, come to term.

come to term是交流知识的第一步,除非come to term了,否则是起不到传递知识的目的.

*** words vs terms
word不等于term,word可能作者表示一个意思,读者理解为另外一个意思.
如果这里存在模糊的话,那么交流就是不存在的,最好也是不完全的.

communication里的common,community指的是一群有共同的人.
communication指的是一个人把自己的想法~感受~知识分享给另外一个人,只有两方达成了共识才是成功交流.

come to term指的是用同样的单词和同样的意思,这样两人的脑子里面才会共享一个想法.

单词在不同场景下是不同意义的,所以要用的没歧义.
当读者和作者在使用单词只有同一个意义时,没有模糊的用法时,他们come to terms了.

Come to terms需要读者和作者共同努力, 作者要努力去避免模糊,而读者要努力去跟上作者对于word的用法.
terms也被称之为一种用于交流知识对于word的有技能的使用.

expository??
这里仅仅是说明文(汇聚知识的),而不是诗歌类的.诗歌类的就是要有歧义.

RULE5: Find the important words and through them come to terms with the author.
注意,分为两步,第一步找到关键词,第二步找到关键词作者的使用含义.

RULE5不同于RULE4的大纲,而是直接解释文章的内容.
不同于RULE6,是先处理语言,然后在挖掘语言背后的思想.

如果说这个单词没歧义,那么analyitical的stage2 interpretation就没有必要.

不可能的事,别想了.

语言是不完美的交流知识的中介,需要作者和读者共同去克服.
作者和读者的中间仿佛隔着一座山,两人要从山中打隧道互通,但是一人最多只能打一半,都完成自己的活还得是一个方向.

stage2 interpretation每条规则都有两步,语法和逻辑的步骤.
语法方面处理单词的,逻辑方面处理terms.
交流离不开思想和语言,只有语言没思想,啥也没交流,只有思想没语言,没法交流.
wusd: 语言words, 思想terms

一个word可以指多个term,一个term可以被多个word表示.
比如: word reading: 可以三个terms
	1. reading to be entertained
	2. reading to get information
	3. reading to achieve understanding

意思说,reading有三意思,在文章里作者提到reading的时候,我们作者作为读者知道它具体指的是哪个,而不是说停留在reading.
wusd: 类似于上课时,知道老师在具体讲什么,而不是停留在单词的字典意思上.

*** Finding the Key Words
现在给RULE5加上皮肤完善细节,怎么样找到关键词?

作者的大部分用词是不重要的,越是用法特殊越可能重要.
如果作者用词和日常用的一样,读者自然也会熟悉在不同语境下的单词的不同用法.

例如: Edington可以在书里用reading的日常含义,如果日常含义你不懂的话,现实你也没法沟通.

但是在我们的书里,reading却不能随便用日常含义,而是有特殊用法的.

作者会大部分词日常用法.
但是随着时间变迁,原来的日常用法也变了.还有些作者故意用古用法,又会加强了这种理解的困难,尤其是翻译外文.

这一章有 word term ambiguity communication. 显然term是最重要的,因为所有的单词都和它有关系.

如果你不能理解文章,那你找不到关键词.有点自相矛盾了,如果你找不到关键词,那么你就理解不了文章.
所以,找到让你疑惑的词,猜它是关键词,再继续往下.

给你造成最大麻烦的词很有可能是关键词.

业有可能不是,因为你本来就懂.如果你本来就懂关键词,那你已经come to terms with the author.


*** Technical Words and Special Vocabularis
目前我们的方法是扔掉不重要的词,找到那些不是日常用法困扰着你的词.
还有其他积极的法子找到他们吗?

第一最明显的方法就是作者在强调它们.
1. 可能是斜体,加"".
2. 也有些单词讨论它们不同的含义然后表明要用那种.
3. 还有告诉这个单词为什么这么命名.

Euclid在他的几何里, 点,线,面,...这些是最重要的.他明确在书最开始就告诉了.
你觉得不难,是因为是日常的词汇,Euclid正好用了它们.

如果都像Euclid一样,阅读就简单了,但实际上不是所有领域的知识都可以用数学的方法解释.
Euclid说的很对,每个领域都有自己的术语.作为读者,我们必须找到它们.

如果作者没有说关键词,读者也许可以靠对科目已有的了解找到它们.
这里RULE of structure就很有帮助, 什么是整体, 什么是重要部分, 对区分术语非常有帮助.
作者的title,chapter headings,preface也非常有帮助

找术语有点像挖花生.找到一个后,一个接一个地找到.

如果一个领域的知识有术语词汇表,那么就非常好找关键词了.你可以主动看这个领域的关键词,也可以被动找不认识的词.
但是有些没有,和生活用语混在一起.

哲学以有私有的词汇而臭名.
有些单词是因为历史原因.
有些单词所有作者没有达成一致,却是关键术语.
有些单词是作者造出来的,作为关键术语.有些作者考虑到有误解,会提前警告.

这方面来说,如果作者跟其他作者用法不同,且解释为什么不同.显然作者对这个词的理解有很大的不同.

关键词的理解不能过于狭隘,不是只有术语.
像那些表达作者的main ideas, leading concepts, special vocabulary, 对于作者都是关键的.
除此之外,还有那些困惑你的词.

对于读者最大的困难就是,对于自己理解困难的地方没有足够的注意力,没有区分自己懂的词和不懂的词.
如果读者自己不去努力标记~思考这些词,我们的方法没用,会变成理解的灾难.

如果你看能加强你understanding的书,那肯定有不懂的词.
如果只是看杂志,那肯定不会加强你理解.
如果你不愿意去努力理解,最好还是看看杂志了.

我们痴迷于被动阅读,造成对单词的不注意,最后没法和作者come to terms.

*** Finding the Meanings
把关键词找出来是第一步,仅仅是告诉你它在这里,接下来干嘛?这是rule5的第二步.
RULE5: Find the important words and through them come to terms with the author.

有两种可能,一种是严格限制单词只有一个意思,例Euclid;另一种是单词有几个意思,地方不同意思也会变.

根据这两种可能,第一步确定是否只有一个意思,如果有多个意思,第二步标记出来,然后根据上下文给的线索确定变化的意思.
后者会让你能够有弹性地跟上作者变化的意思的用法.

怎么找到这些的单词多个含义?
唯一的办法就是通过上下文你知道的单词的意思去推测你不知道的单词的含义.

比较好的例子就是Euclid的定义: A point is that which has no part.

这个定义如何让你和Euclid共用term,Euclid认为他定义的除了term每个单词都是精准的.

定义的例子就是你获取单词意思的典型过程,定义里的其他单词本身是定义好的,而且还得你懂的.
如果定义里的其他单词没定义好,或者你都不懂.那被定义的词你也搞不懂.

有人说书就跟范文一样,其实除了一些术语,其他都是日常熟悉的词.
这些熟悉的词就是context去搞懂这些术语,读者有做这个事情的所有材料.

搞懂这些术语是很难,但不是不可能的.
事实一本书能增长你的understanding就是对你很难读的,你必须搞懂这些术语,靠你自己瞎搞是不可能从理解少变得理解多的.

搞懂这些术语就跟拼图一样,试-犯错-再试,你拼的图越多,后面就越容易拼也就越容易搞懂后面的术语.
wusd:有点像复利,马太

过程中你肯定会犯错,你可能认为已经搞懂了术语却因为后面的小调整重新理解.
最终一定会改正所有的错误理解,因为理解错误了,一定会使得整体不对劲.
你和作者共用term以后,你才有能力去检查你自己,就不会错误以为自己懂了.

和拼图比的不恰当的地方,是拼图是完美的图片,书可不是哦.
good book才比较接近,有些bad book不可读在这个方面是这样的.

用一词多义的人不用词模糊吗? 不是
不是通常作者都用词一个意思,尤其是关键词? 是

用词模糊就没有区分它们的意思(必须important就没有说明对作者还是读者).作者这么干就没有使得读者come to term.
但是如果作者用critical word使得读者快速鉴别就是提供了term.

一词可以多个term,如果你把这个词的列搞上多个term,就知道作者vocabulary和terminology.

有几种复杂情况.
第一种:单词有不同的含义单一用或者组合用.
	eg. reading的含义: 1. Xa看各种各样的书 2. Xb看教做的书而不是娱乐的书 3. Xc看启迪的书而不是命令的书.
	
	这样reading可以组合起来用,比如同时三个含义XaXbXc;又或者Xb,Xc单一含义.

第二种: 同义词.
	文章反复用同一个词非常无聊,比如恐怖如斯.跟第一种情况正好相反.

	eg. enlightenment and insight都是一个意思,换了个表达.但是作为读者,你要能抓住这个意思.

两种情况非常重要,如果你认为作者换了单词就换了意思,当遇到这两种情况,那么你就很容易犯错.

第三种: 习语

习语和term的关系 等于 单词和term的关系.

习语通常更精确,作者用习语一般想让你准确把握他的意思.

	eg. the process of passing from understanding less to understanding more by the operation of your mind upon a book.
	这样总不会搞错了吧.

这一章不好讲,也不好理解.
因为阅读的规则不能被完全理解如果没有单词和terms的各种各样的语法和逻辑的解释.

这个问题我们涉及的比较少,只搞了一些重点确保在实践是有用的指南.随着你实践的越多,你就会越明白问题的复杂性.
1. 单词的直接和隐喻用法
2. 抽象和实际单词的区别
3. 定义的事情: 定义单词和定义事物的区别; 为什么一些单词没法定义,一些有定义.
4. 探险单词的情感用法: 用单词去唤起情感去影响人去行动或改变注意.
	 比如: 演讲都是影响精神的,几乎所有的单词有奇怪的但是明显感觉的到隐喻.

如果inspectional reaidng唤起你的兴趣,你可以想看这个科目的书去满足兴趣.
你会受益于看的这些书,因为你会带着自己阅读经历产生的问题去看.
学习这些语法和逻辑是使用的,仅仅当你能把它作用于实践.

可能不想再深入.但是只要你去找关键词,搞懂其变化的含义,come to terms,你会受益很多.
小习惯的改变有巨大的影响.

** 9 Determining an author's message
达成一致和制作条款商人之间发生,同样也在书本里.
条款要清晰和有吸引力,这样商人就达成了一致.

书里的条款就是作者的判断,某事是对的还是错的,是知识而不是作者的想法.
作者经常在前言里面承诺要教我们什么,只有看他的条款,才知道他有没有做到.

书的顺序跟商业的顺序相反,要先找到term知道作者在讲什么,再去找到其条款.
所以这也是第5条rule关于words和terms,第6条rule关于sentences和propositions.

第7rule和第6rule是相关的.
作者必须真诚把自己观点建立在事实上,作者的条款仅仅是自己的个人经验除非是有理由支持.
我们不但要知道作者的条款是什么,还要知道作者为什么认为我们要接受它.

第7rule处理所有类型的论证,每个论证都有相关连的命题,简单来说就是因为所以.

论证的出现经常由那些关联词暗示.
我们不再在学校了,没有老师了,如果想继续从书本学习,必须学会自己找这些关联词.

论证通常是背景和理由总结出来的一些命题,一段通常是表达一个论证.
结论有前提推导得出,但是不是说结论一定是对的,因为前提可能是错的.

有语法的也有逻辑的解释这些规则的顺序.
语法的: 从单词->句子->段落.
逻辑的: terms->proposition->argument
不能说书仅仅是单词组成的,而是句子(单词组成的)+段落(句子组成的).
没别的办法,只能这样发现作者的terms, proposition和arguments.

在这个stage(解释是目地)时,我们把整体切分成小块,在first stage(大纲是目地时),我们相反.
你可能怀疑这里有共同点,确实.
当你把主要部分切分成一个个点时,每个点是一个proposition,几个proposition就很有可能组成了一个argument.

提大纲和解释两者在propositions和argument相遇.
你深入propositions和argument通过切分,你浅出propositions和argument通过看其是如何组合.
当你完成这两步时,你才能说你知道了书的内容.

*** Sentences vs. Propositions
Sentences vs. Propostitions类似于Words vs. terms.
Words Sentences Paragraph, 语法单位.
terms, propositions, argument, 逻辑或知识单位.

这里遇到了上章的问题, 语言不是思想表达的完美中介,words和terms不是一一对应的.
一个word可以对应多个terms, 多个words可以只对应一个term.

数学上描述关系像一个扣子对应一个扣洞,但是语言不是这样的.
可能犯的最大错误就是认为语言和思想/知识是一对一的关系.

~

句子和命题的关系: 有些句子是问题, 命题是对问题的回答.也是为什么说命题是声明式的,而问题是疑问式的.
还有句子表达了期望和意愿,仅仅是给出了作者意图的信息,并没有给出作者想要说明的信息.

而且不是说所有的句子仅仅是一个命题.
1.单词是多义的, 比如 Reading is learning, 可能learning表示获取信息,也可以表示为理解. 这里命题就不一样了.

2.复合句可以表示多个命题,比如 and, if...then..., not only... but also...

举例:

~

1. the reason why the prince ought to inspire fear in a certain way is that he can endure being feared so long as he is not hated;
2. he can avoid being hated only by keeping his hands off the property of his citizens and their women.

这句子有三个命题,你可能同意第一个,不同意后两个. 你必须搞懂他到底在说什么,才能选择同意或者不同意他.	

律师非常懂这个,他们必须小心检查原告指控啥和被告否认啥.
小明昨天签了合同.可能小明签了合同,但是不是昨天.
有时候连同一个句子都有语法歧义的问题.

即使是同一个命题可以被不同的句子表达.

如果没有渗透过语言的表面,语言就不是交流的中介,而是交流的阻碍.
你会读单词,但是却收不到知识.

rule5:找到关键字,come to terms
rule6:找到关键句,发现包含的proposition
rule7:找到或构建基本的论证,通过找到terms和propostion在句子中的关系.

这些规则用在说明作品是如此的,但是诗歌类作品非常不同.
我们会讨论在用他们到诗歌类作品时,需要做的改变.

** 21 Reading and the growth of the mind
More active reading is, the better it is.
Active reading is the asking of question.

Lower levels of reading is contained in higer ones.
Analytical reading is the most unfamiliar for most readers,
		whose things always applies syntopical reading with certain adaptations,
	so that we discussed it at a great length.

This is a practical books containing the rules of inspectional, analytical, and syntopical reading
	which you should practice on purpose if you accept.

*** What Good Books Can Do for Us
You should have not only the things you read but the method to apply to them as well. 

The method including analytical and syntopical reading doesn't apply to every book
	which do not require it.

You must read books beyond you or you will not be a better reader,
	for unless you stretch your mind you will not learn.

You mustn't expect to get any improvement in reading skills from the books
	that provide you with no more amusement.
Reading a book full of information doesn't either,
	for your mind is merely fuller of facts but not stretched when you read it.

Don't fear the books that make demands on you,
	because the rules we have described will tell to how to tackle them.
Besides, there are some very books you must find out
	which will continue to extend you no matter how good a reader you are.

The books that neverending challenge to your skills
	are not always ones in relatively unfamiliar fields or some scientific books.

If a book defies your efforts to analyze it, it's a bad book and no worth trying.

When you try to read a good book, you receive two kinds of reward:
	the improvement in your reading skill and the things about the world and yourself.

The greatest books can help you to think better about the knowledge beyond you,
	because the authors of these thought better than you.

*** The Pyramid of Books
There are more than 99 percent of books written in the Western tradition
		that don't impore your skill in reading and only provide amusement or information,
	as you don't have to read them analytical at all and only skim.

The good books which make severe demands on you and are worth read analytically once
	are less than one in a thousand.

How to know that if a book is only good book?
After having read it, you're grateful to what it has given you, but you know that's all.

There are of the few thousand such books even smaller number.
After reading it analyticall to the best of you ability and placing it back on the shelf,
		you keep thinking about it and your reaction to you
			so that you obligation as an analytical reader takes you back to the book to find more.

A return of the second class of book is inevitably disappointing,
	for the book has not changed but your mind is fuller.

It seems that the books of the highest class have grown with you,
	for you can always see something new that you didn't see before.

The great book may be so far above you that it can lift you over and over again until you die.

People have different tastes, so you may never feel about an author the way you feel about others.

We have listed those books that may have this kind of value for many readers.
You need to seek out the few books that can have this value for you.

*** The Life and Growth of the Mind
Which ten books would you select before
	being marooned on a desert island for the rest of your life?

List it, there would be just you and ten books.

To a extent, we are marooned on a desert island.

The mind doesn't cease growing before the brain itself loses its vigor.

If you mind is not used, it can atrophy.
Som people who were kept alive by external force like the demands of their work
	die so soon after their retiremnet.

As all the sources of amusement and informaion surrounding us are artificial props like drugs,
	if we get used to them, and they have little or no effect, we cease to grow and begin to die.

Reading actively is not the way to advance our career but keep our minds alive and growing.

*** questions
新概念并不是一本great的书,how to read a book说只需看一遍, 而我们却需要读百遍, 想知道这种区别在哪里?
