* 前言
在一个共和国,由于公民所接受的是理性与说服力而不是暴力的引导,推理的艺术就是最重要的    --托马斯·杰弗逊  

在需要下判断是,理性是最可依赖的工具  

理智帮助判断真假,帮助从已知推未知.但是未知太大了,不得不求助权威.即使求助权威,仍然需要理智判断权威是否可信.任何智力需求都依赖于推
理.  

我们有推理的天赋.逻辑学就是把这些天赋揭示出来,并且严格刻画,运用它们去解决那些能够依靠理性解决的问题  

通过本书的学校,掌握正确推理的基础原理,对你的智力生涯产生重要而持久的影响  
* 第一部分 逻辑与语言
* A篇 推理
* 第1章 逻辑学的基本概念
** 1.1 什么是逻辑学
逻辑学是区分正确推理与不正确推理的方法和原理  
进行推理时,构造论证,提供理由.但是前提能够推出结论吗?逻辑学就回答了这个问题  
** 1.2 命题与论证
A. 命题  
有真有假是命题,无真无假非命题

命题按意义来辨别的,而不是按语言.不同的语言相同的意义是同一个命题

命题依赖于语境. 中国最大的城市是上海  

命题的结构: 
    联言命题:(合取)
        亚马逊河流域制造了大约全球百分之二十的氧气,产生了其流域内的绝大部分降水,并且拥有许多未知的物种  
    选言命题:(析取)  
        林肯写道:"巡回法庭或者是有用的,或者是无用的"  
    假言命题:(条件)  
        如果上帝不存在,则有必要造出一个上帝  
B.论证
推论:搭砖头上去    
论证:用理性的脚踹那些砖头搭建的稳不稳  
论证: 严格地指这样的一个命题组,一个命题从其他命题推出,后者给前者为真提供支持.对任一可能的推论,都有一个与之对应的论证  
前提:  
结论:  

关于结论真假的兴趣放在一边,聚焦于以下两点: 
    1. 关注论证的形式(form),来确定是否能产生保真结论的论证(理论上)  
    2. 关注论证的质(quality),来确定论证是否实际上产生了保真的论证(实际上)  
    
论证的复杂性:
    - 命题的结构或形式
    - 前提之间的关系
    - 前提合结论之间的关系
最简单的论证:
    在地球上最早出现生命时没有人存在.因此,任何关于生命起源的陈述都应该被视为理论的而非事实的陈述
假言命题看起来像论证,实际不是:论证的关键在于有几个断言,假言命题得到断言是,前者包含后者,并且两者都可能是假  
    eg. 如果我不喜欢人和蔼可亲,那么我就省去了喜欢他们的麻烦  
        我不喜欢人和蔼可亲,因为这省去了喜欢他们的麻烦  
****** 练习题
1. 管理得当的民兵组织对于一个自由国家的安全是必需的,因而人民保存和持有武器的权利不得侵犯  
前提: 管理得当的民兵组织对于一个自由国家的安全是必需的  
结论: 人民保存和持有武器的权利不得侵犯  
2. 我们可以预防大多数癌症,即使我们不能直接找到这些癌症的原因;癌症的预防研究比治疗更显重要  
前提: 我们可以预防大多数癌症,即使我们不能直接找到这些癌症的原因  
结论: 癌症的预防研究比治疗更显重要  
3. 托马斯论证道:人类理智是从上帝那儿得来的福祉,因此"运用人类的理智来理解世界非但不是对上帝的冒犯,而是一种令其满意的行为"  
前提:人类理智是从上帝那儿得来的福祉  
结论: 运用人类的理智来理解世界非但不是对上帝的冒犯,而是一种令其满意的行为  
4. 埃德蒙是一位英雄,不仅因为他第一个登上珠穆朗玛,还因为他从未忘记帮助夏尔巴人,一生帮助他们筹建医院和学校
前提:第一个登上珠穆朗玛  
前提:从未忘记帮助夏尔巴人,一生帮助他们筹建医院和学校  
结论:埃德蒙是一位英雄  
5. 标准化考试对于不同人种和民族有着根本不同的影响.白人和亚洲学生的平均成绩明显高于黑人和拉丁美洲籍同学.对于四年级考试以及书本各
种知识的考试而言,这是事实.如果种族间差距是种族歧视的证据,那么所有的考试都存在种族歧视  
前提: 对于四年级考试以及书本各种知识的考试而言,这是事实  
结论: 白人和亚洲学生的平均成绩明显高于黑人和拉丁美洲籍同学  

前提: 白人和亚洲学生的平均成绩明显高于黑人和拉丁美洲籍同学  
前提: 如果种族间差距是种族歧视的证据,那么所有的考试都存在种族歧视  
结论: 标准化考试对于不同人种和民族有着根本不同的影响  
6. 好的感觉能力是这个世界上分布最为平均的东西,因为所有的人都认为他们自己拥有的足够多,以至于即便是在其他事情上最不容易被满足的人
也不会要求更多的感觉能力  
前提: 所有的人都认为他们自己拥有的足够多,以至于即便是在其他事情上最不容易被满足的人也不会要求更多的感觉能力  
结论: 好的感觉能力是这个世界上分布最为平均的东西  
7. 对于美国来说,任何新词不是愚蠢的,就是外来的,因此没有所谓应该英语的东西,有的知识糟糕的英语  
前提: 任何新词不是愚蠢的,就是外来的  
结论: 没有所谓应该英语的东西,有的知识糟糕的英语  
** 1.3 论证的辨识
我们必须能在作品或演讲中辨识出论证性的语段  
A. 结论指示词和前提指示词  
    结论指示词:
    - 所以
    - 因此
    - 故而
    - 由此可见
    - 于是
    - 可得
    - 据此证明
    - 之所以
    - 为此缘故
    - 因而
    - 基于这些理由
    - 可推得
    - 我推断
    - 这表明
    - 这意味着
    - 据此可得
    - 这蕴涵
    - 据此我们可以推出
    - 据此可得结论
    - 我们可推出
    前提指示词:
    - 因为
    - 由于
    - 因
    - 根据
    - 从...推出
    - 正如...所表明
    - 缘于
    - 正如...所示
    - 理由是
    - 理由在于
    - 可从...推出
    - 可从...引申
    - 可从...得出
    - 有鉴于
B. 语境中的论证
实际论证不一定有指示词:
    eg. 因为我们派遣男女去伊拉克,其原有的领导人辞掉了职位.我们给与伊拉克人民消除不平的机会,他们却将其仍回来,砸我们脸上.伊拉克
        不值得我们帮助  
只有理解了某论证出现的语境之后,才能领会该论证的效力.  

C. 非陈述形式的前提
反诘问句:暗示或假定一个答案作为该论证的前提  
    eg. 我被正在发行的这一系列硬币所烦扰.虽然某些第一夫人的确影响了我们的国家,难道我们就应该将这份荣耀赠与那些未经选举,其唯一资质
        就是拥有杰出丈夫的人吗?  
    - 招致威胁论证质期望结论的答案
    - 当问题答案清晰确定无疑时,可以最为有效地起到前提的作用  
    - 反诘问句的论证通常都只是暗示某命题为真,回避了断定该命题的责任.
        八卦兴旺靠的就是暗示性的疑问句  
        这也不失为躲避某些问题的争论的聪明策略
命令句: 重塑命令句语句  
D. 未明确陈述的命题(隐含命题)  
论证者故意不将关键的前提陈述出来,通过保持对该前提的心照不宣能使它免于被攻击  
** 1.4 论证和说明
特定的语段究竟是论证还是说明,取决于这个语段服务的目的.
    - Q因为P, Q是未知的,语段的目的是为了证明Q为真
    - Q因为P, Q是已知的,那么语段的目的就是为了说明Q为什么是真的
有时候弄清作者的意图并不容易  
被说明的东西:  
说明的内容:  
** 1.5 演绎论证和归纳论证
两大种类的论证: 演绎和归纳
演绎论证: 
    有效性:如果演绎论证不是有效的,必定是无效的.如果不是无效的,必定是有效的  
        古典逻辑: 亚里士多德的分析工作,6~7~8  
        现代符号逻辑: 9~10~11  
归纳论证:  
    强弱:
    归纳理论~类推和因果推理的技巧~评估归纳论证的方法,以及量化和计算或然概率的方法,11~12~13~14  
    永远不能说归纳论证的结论完全确定,附加的信息可能强化或弱化这种或然性.新发现的事实使我们改变对或然性的评估,可能导致我们对归纳
论证的判定比原来更好或更差  
** 1.6 有效性和真实性
* 第2章 论证的分析 
分析:将系统分解为单个组件
** 第2章 论证的分析
*** 2.1 论证的解析
    日常生活的论证更复杂:
        1. 前提太多,顺序乱
        2. 前提可能累赘,重复
        3. 前提的意义不清晰
    解析: 用清楚的语言和逻辑顺序表明论证中的命题.
        关键在于: 正确`完全

    法院案例:
        1. 宪法有私人自由
        2. 申诉人在自由领域
        3. 德州没有合法利益而贬低了申诉人
        4. 德州错误否认了申诉人的权力,制定法令,所以因违宪被撤销

    哈代案例:
        1. 语言会消亡
        2. 艾库斯螺丝使用语言
        3. 艾库斯成果会消亡
        4. 数学理念不会消亡
        5. 阿基米德使用数学理念
        6. 阿基米德不会消亡
        7. 所以阿吉米德不会消亡
        8. 所以,阿基米德被永记,埃斯库被遗忘
****** 练习题
    1.
        1. 各方面比对方更强
        2. 活塞队失败了
        3. 因此活塞队失败不是因为能力不足.
        4. 每三场比赛赢马刺队两场
        5. NBA决赛最后一次失败
        6. NBA决赛已经赢前面两场
        7. 平均法则,活塞队失败了最后一场, 活塞队失败论
        8. 活塞队失败因为平均法则
        9. 活塞队失败不是因为能力不足,而是平均法则
    2.
        1. 大学生书面语言能力来自于大学写作课程
        2. 大学写作课程实际是女性主义,欺骗了学生
        3. 因此成千上万大学生无法用书面语言表达自己
    3.
        1. 人们被种族划分,不会觉得和其他人紧密联系,不相信互助
        2. 因此种族多的政府,要么拥有福利,要么多样
        3. 没有多样和福利,人们就不支持政府
        4. 种族多元比单一支持少
    4.
        1. 如果自由是自然,那么人类历史都是自由社会
        2. 人类社会是专制政府,不是自由社会
        3. 奥的观点:自由是自然--是错的
    5.
        1. 如果科学家能给过去发信号,那么我们已经收到未来科学家的信号
        2. 我们没收到
        3. 科学家不能给过去发信号
    6.
        1. 爱斯生存恶劣决定捕鲸是生存需要
        2. 人人有生存的基本权利
        3. 爱斯捕鲸是他的权力
        4. 日本可以选择其它事物,仍然捕鲸
        5. 现代社会没理由就猎杀应被严惩,因为鲸有限,这不是伪善
        6. 日本捕杀鲸鱼错误
        7. 记者将爱斯和日本猎杀鲸鱼等是错误的
    7.
        1. 太空中原子不可数,驱动力也不可数
        2. 不可数就有不同的世界`人类和动物
        3. 因此宇宙的其它部分存在不同的世界, 人类和动物
    8.
        1. 父母预先指定婚姻的国家,离婚率很高.
        2. 爱不离婚,不爱离婚
        3. 因此如果没爱情结婚,不意味这不会爱上伴侣
        1. 爱不离婚,不爱离婚
        2. 而爱情决定婚姻的国家,离婚率非常高.
        3. 因此如果你与爱的人结婚,不意味永远爱这个人而婚姻成功
        4. 如果没爱情结婚,不意味这不会爱上伴侣;如果你与爱的人结婚,不意味永远爱这个人而婚姻成功.
    9.
        1. 如果公众认为IRSD不能满足基本期望,那么税收风险会变得很高,难逆转
        2. 税收风险高且难逆转,税收体系就完蛋
        3. 因此税收体系依赖于纳税人信心
    10.
        1. 被种族问题困扰
        2. 面临问题置身事外,错误总是对方
        3. 争论不休
*** 2.2 论证的图示
    图示:
        适用于多种前提纠缠的复杂论证
        优点:
            1. 展示多个前提独立支持结论的论证
            2. 展示论证之间前提的关系,比如两前提并列才能支持论点
            3. 展示不便于用语言表示的
        2,(3,4) -> 1
    当隐含前提,用解析法把隐藏的复杂性给澄清了
    论证的数目取决于其中所含结论的个数
        - 相同的两个前提可能有两个结论
        - 一个前提可能有两个结论
    同一个命题既可在论证中做结论,又可在另外论证中做前提.
        前提和结论都是相对的
****** 练习题
******* A
    1.
        1. 市郊社区各个组成被相互分离
        2. 距离互相分离,市郊居民花钱从一地到另异地
        3. 几乎人人单独驾车
        4. 人口稀少产生只有传统城市才有的交通流量
        (1->2, 3) -> 4
    2.
        1. 图书馆计算机必须有过滤器
        2. 色情作品是社会灾难
        3. 图书管不能被用色人传送淫秽
        4. 有过滤器能过滤色情
        (2->3,4) ->1
    3.
        1. 约翰逊最优秀美总统
        2. 第二多民族正义
        3. 罗斯福之后社保最多
        4. 可能是最伟大立法
        5. 是最富抱负的思想家
        6. 约翰追求权力完成事业
        (2, 3, 4, 5), 6 ->1
    4.
        1. 已婚比单身更健康
        2. 经济更稳定
        3. 婚生子女指标更好
        4. 婚姻是负责任的行为
        5. 税收必须支持
        (1,2,3)->4->5
    5.
        1. 愿意购买真空吸尘器保证房子清洁
        2. 认为花销是必需的
        3. 街道吸尘器当作不必要的花费
        4. 房子是清洁的,街道不干净的
        (1->2,3)->4
    6.
        1. 欧元代替英镑
        2. 我们是欧洲一部分,欧洲直接影响我们
        3. 欧洲向我们期望的方向转变
        4. 执行领导力
        (2, 3)->5->1
    7.
        1. 加州法律2004年4月
        2. 1994-2002加州人数增加太多了
        3. 没有该法律的纽约州,人数增加315人
        4. 纽约犯罪下降20个百分点
        5. 犯罪率下降不能归功于法律.
        6. 有法律人照多
        7.无法律人照少
        (1,2)->6)->5
        (3,5)->7)->5
    8.
        1. 没词达其意
        2. 没辞尽其意
        3. 词语滑溜的
        4. 思想粘稠的
        (3,4)->1 (3,4)->2
    9.
        1. 听到了希望听到的东西
        2. 访谈带有充满好感的偏见
        1->2
    10.
        1. 没政府保证小股民同等
        2. 制定规则防止财政丑闻不诚实
        3. 市场中,没有规则能保证公正透明
        3->1 3->2
******* B
    1.
        1. 原子能垃圾对比矿物易处理
        2. 每年矿物270亿吨二氧化碳,可以堆积城小山
        3. 核裂变产生相同能量,浪费比矿物少20000倍, 16立方米
        4. 每年原子能废物1立方米, 安全封存在混泥土
        (2, 3, 4) -> 1
    2.
        1. 谴责贫富差距
        2. 不平等与政治不稳定
        3. 不平等与暴力犯罪
        4. 不平等与期望寿命缩短
        5. 公正.
        2->1 3->1 4->1 5->1
    3.
        1. 基因和蛋白被发现而不是发明
        2. 发明可以给专利,发现却不能
        3. 因此蛋白质专利本身有问题
        (1,2) ->3
    4.
        1. 长远看,捕鲸在日本消失和鲸高贵...无关,与经济学有关
        2. 调查结果.数千人,4%吃过鲸鱼肉
        3. 日本人不愿吃鲸鱼肉
        4. 不愿吃,不会买
        5. 不买,就不捕鲸
        2->3->4->5->1
    5.
        1. 无记忆, 无正义
        2. 无正义, 无未来
        3. 无记忆,无未来
        (1 , 2)->3
    6.
        1. 公共记录出色,私生活瑕疵
        2. 对手私生活故事,公共不行
        3. 对手继续经营私生活,克力继续公共领域
        4. 在那个领域擅长就该留在哪个领域
        (1,2,4)->3
    7.
        1. 二战解决纳粹,并与摧毁的国家达成联盟
        2. 美国战争解决纳税却无代表权,美国诞生
        3. 波斯湾解决伊拉克入侵科威特
        4. 美国内战解决奴隶制
        5. 这些战争创造了更好的世界
        6. 战争是战胜敌人的唯一途径
        7. 无论我们还是它们,能创造和平才是胜利方
        (1,2,3,4)->5
        (1,2,3,4)->6->7
    8.
        1. 不服从犯3错误
        2. 不服从我们就是不服从父母
        3. 我们是教育创始人
        4. 他达成一致意见,同意会及时听从我们的指挥
        (2, 3, 4)->1
    9.
        1. 钱会说话
        2. 相比没钱请代理的人,法官`陪审团...
        3. 饭店,衣着华丽...
        4. 人类本性就是将更好的东西
        2->4,3->4 4->1
    10.
        1. 法律,犯罪率几句下降不然
        2. 罪犯更愿意没有被枪击危险
        3. 罪犯猜想有法律的镇,对它们更严厉,推断其它地方更容易得手
        4. 如果3的话,其它采用类似法律的地方,也是为了不吸引罪犯
        5. 不吸引罪犯
        (2,3)->5->4->1
*** 2.3 复杂的论证性语段
    复杂:(几个论证多重复合)
        1. 有些命题只作为前提
        2. 有些命题又作为前提又作为分结论
        3. 命题被重复提起,虽然词语不同
        4. 可能有不同合理解释
    图示法比较合适,但不存在万能
****** 练习题
    1.
        1. 被爱戴和被畏惧统一比较困难,必须选一个,被畏惧更安全些
        2. 普通人是忘恩负义...
        3. 通过报偿得来的友谊不安全,真正需要时无法依靠
        4. 相信普通人承认而忽略其他防范很可能被摧毁
        5. 冒犯自己爱戴比冒险自己畏惧更多顾虑
        6. 人性的卑劣,维系友谊的责任会因为自身的利益随时被冲破
        7. 畏惧心,使人害怕被惩罚,反而能保持忠心
        2->3->4
        (6,7)->5
        (4,5)->1
    2.
        1. 民主法律保护多数人
        2. 源于大多数公民
        3. 公民易反错误,但不会站自己反面
        4. 寡头法律保护少数人
        5. 寡头政治由少数人建构起来
        6. 一般情况,民主政体立法比寡头政治立法对人类更有益
        7. 保护多数人比少数人更有益

        (2,3)->1
        5->4
        (1,4,7)->6
    3.
        1. 具有医务工作者的风度
        2. 军人气概
        3. 军医
        4. 刚从热带回来
        5. 脸色黝黑
        6. 不是原来的肤色
        7. 手腕的皮肤黑白分明
        8. 久病初遇又历尽艰辛
        9. 面容憔悴.左臂受过伤,现在动作僵硬
        10. 阿富汗来的
        (1,2)->3
        7->6
        (5,6)->4
        9->8
        (3,4,8)->10
    4.
        1. 东西不可解证,除非其反面是矛盾
        2. 没有东西是矛盾
        3. 无论设想存在是什么, 也可以设想它是不存在物
        4. 因此没有不存在性是矛盾的存在物
        5. 没有存在性是可解证的存在物

        1->2
        (2,3)->4
        (1,4)->5
    挑战.
        0. 自然没有偶然,一切都受神的本性的必然性而以一定方式存在和动作

        1. 神的样式由神的本性而出,非偶然而出
        2. 它们有什么动作
        3. 如果样式不是神决定,那么样式自己决定,不可能,非偶然
        4. 样式是神决定,那么样式被神决定,也不可能,非偶然

        (3,4)->1
        (1,2)->0
*** 2.4 推理中的问题
    推理是已知前提,推结论.
    为什么推结论?
        1. 决定自己如何行动
        2. 评价他人的行动
        3. 为道德或政治的信念进行辩护
    要建构自己的论证!
****** 技术
    矩阵
    存储已知信息和中间结论,能把已知信息和推出的信息整齐地记录下来,并随着推论数目不断增长.
***** 回溯分析:
    企图说明为何从过去的状况发展到现在的状况的推理

    现实中叙述不是很精确,错误描述引人误解,不能得到答案.遇到这种情况,原问题的部分陈述要加以拒绝或替换.
    也有可能是不完善的.可能依赖于某个新的科学发现.
    一部好的谋杀案侦探小说,必须给出足以得到答案的全部信息.
    现实问题最初经常是仅仅由于前后矛盾的情形或不平常事件的出现而被发现的
****** 练习题
    1.
        1. 政客从不说真话
        2. 非政客总是说真话
        3. 问第一个人: "你是政客吗?" 作了回答
        4. 第二个人转述第一个人的回答,他否认自己是政客
        5. 
        三个本地有几个政客?
*** 第2章概要
    本章 分析论证的技巧 在论证分析中遇到的一些困难
    技巧:
        困难: 1.前提太多`顺序乱;2.前提累赘`重复;3.前提意义不清晰
        解析: 用清楚的语言和逻辑顺序表明论证中的命题
    技巧:
        图示: 适用于多种前提纠缠的复杂论证
            优点: 1.展示多个前提独立支持结论的论证,2.展示论证之间前提的关系,3.展示不便于用语言表示的
    2.1节 解析
    2.2节 图示
    2.3节 复杂的论证性段落
    2.4节 推理问题.需要大量的论证和子论证
* B篇 非形式逻辑
** 第3章 语言和定义
*** 3.1 语言功能
语言: 用来表达信息,表达逻辑
    用法: 
        1. 信息性:进行推理--断言或否定命题,形成或评价论证
        2. 表达性
        3. 指令性
        --- 不普遍的
        4. 礼节性
        5. 述行性
    形式:
        - 陈述句: 推理, 起到指导行为的功能(天啊,要迟到了!)
        - 感叹句: 表达情感
        - 祈使句: 试图指导行为
        - 疑问句: 可以断定前提,可以表达态度(你什么意思?)
    区分句子构成的事实和说话者的事实.
        eg. - 某人说:战争始终是国际冲突的错误解决方案
                这也许是真的(句子事实),同时也是某人持有该信念的证据  
            - 某人说: "基于道德的考虑,我强烈反对我们参与这次战争"" 
                说话者可能为真的陈述,同时也是对这次战争的道德判断  
    多种功能的结合有些情况并不合适,甚至产生争议
        eg. - 法官John Harlan:案件表明许多语言表达具有双重交流功能:加上附带说明,可以精准表达思想,传达独一的情感.
              与情感力量一样,词语也常因为认知力量而被选用.宪法要关注个人言辞的认知内容,也要关心情感功能.不能纵容
              轻率假定: 禁止特殊言辞,同时又能不压制思想.
****** 练习题
A.
    1. 指令
    2. 信息~表达
    3. 信息~表达
    4. 信息
    5. 表达
    6. 指令~信息
    7. 表达
    8. 述行~信息
    9. 信息~表达
    10. 信息
B.  
    1. 信息
    2. 表达
    3. 信息
    4. 指令
    5. 表达
    6. 表达
    7. 指令
    8. 表达
    9. 表达
    10. 指令
    11. 指令
    12. 表达
    13. 表达
    14. 信息
    15. 信息
    16. 指令
    17. 信息
    18. 表达
    19. 表达
    20. 表达
C. 断定是什么命题,或打算引起什么行动,或读者可能会把他们视作提供了什么证据
    1. 即使提名我,我也不接受;即使选举我,我也不供职
        引起: 听众不提名,也不选举他.  
    2. 政府竟然英明地认为冰是一种"食品制物",这就意味着南极洲是世界上最主要的食品生产基地之一了.  
        命题: 政府认为冰是食品非常荒谬
    3. 人类在永恒的斗争中壮大,在永恒的和平中毁灭  
        命题: 对人类而言,斗争比和平要好
*** 3.2 情感语言~中性语言和论争
句子和锻炼功能多.聪明地使用语言可以使其具有欺骗性,不慎使用会导致不必要的误解和论争  
说的词语意思可能是中立和准确的,却有可能影响听者的情绪 
    用温和的词汇表达冷峻的现实:
        - 看门人-守护员-管理员
        - 招待-侍者-服务员
带情感色彩的语言
    在诗歌中合适的  
    在其他场合不适合  
        eg. - 调查的答案依赖于提问的词汇的使用
            - 无偏见的报道,别使用感情色彩浓厚的词语
            - 有时候却无法避免.关于堕胎道德性的冲突上
            - 广告行业:理清我们所面对语言的真正用法  
            - 政治宣传:理清我们所面对语言的真正用法  
论争: 可能源于双方对同一事实的不同信念.
    纯粹事实上的岐见: 死刑是事实上是否构成对谋杀的有效威慑 
    纯粹是态度上的:无论死刑的威慑作用有多大,国家处死刑犯是否正确
    态度和信念上都有分歧: 
    解决问题:明确双方论争的真正问题  
        1. 如果岐见是死刑是否起作用,那么首先要客观地确认这些事实--虽然很困难
        2. 如果岐见是国家授予死刑的正确性,那么仅仅就事实达成一致是不够的  
         
   
*** 3.3 论争和含混性
*** 3.4 定义及其用途
*** 3.5 定义的结构:外延和内涵
*** 3.6 属加种差定义
*** 第3章概要
** 第4章 谬误
*** 4.1 什么是谬误
逻辑学:找出诱发错误推理的方式  
谬误:
    - 广义: 任何推理的错误都是谬误
    - 狭义: 典型错误
论证与谬误:相当于对象和类的关系  
形式谬误:  
    错误模式: 如果任何P都是Q,并不能从某物是Q就推出它是P  
非形式谬误: 日常对语言的运用
    更难识别,具欺骗性的是语言,很可能被表面看似可信~实际毫无根据的推理所蒙骗    

自己注意不要犯这些错误,不要误判别人犯错误.看似是谬误的推理,应该追问各词项的真正含义.
有时谬误的职责不公平地对准这样的语段,作者想要表达的观点被批评者漏掉了    
*** 4.2 谬误的分类
非形式谬误种类繁多,最好的理解方式是分门别类,找出各类的可识别性特征  
相干谬误:前提与结论不相干,被看作是相干的  
    1. 诉诸情感
    2. 红色鲱鱼
    3. 稻草人
    4. 人身攻击
    5. 诉诸暴力
    6. 不得要领
不当归纳谬误:前提与结论相干但太弱,基于这些前提推出结论是愚蠢的  
    1. 诉诸无知
    2. 诉诸不当权威
    3. 虚假原因
    4. 轻率概括
    5. 预设谬误
        - 偶然
        - 复杂问句
        - 丐题
含混谬误:词语或表达式模棱两可  
    1. 歧义
    2. 双关
    3. 重音
    4. 合成
    5. 分解   
*** 4.3 相干谬误
相干谬误: 前提压根与结论没有真实关联.但是常常在心理上与结论是相干的,错误产生在 用语言的感情特征支持结论而并未给出客观理由  
****** R1. 诉诸情感
诉诸情感:用表达性语言和其他有计划的手段博取接受方的情感,激起支持或反对某事的热情,而不是提出证据和合理论证   
    定性:最糟糕,最常见  
    日常eg.  
        - 希特勒爱国主义下的可怕虐杀
            反例:接受方的信念本来就一致,激情只是为了激发听众做出支持该信念的行为,那么就起了很好的作用   
            结论:好不好看演讲者的目的,以及接受方本身的信念  
        - 商业广告,总是将产品跟美好的事物练习在一起  
        - 诉诸大众热情: 尤其愚蠢  
            - 大家都买了,所以你也应该买  
            - 本身带有情绪的词汇做调查问卷,这个已经不是问卷了,这些问卷本身就有答案.  
        - 诉诸同情:诉诸别人的慷慨和仁慈之心  
            - 审判时,不是鉴定犯罪时的环境和可能原因的分析,而是为了影响陪审团把有罪搞成无罪  
            - 民事诉讼中,原告律师为了赔偿金,说企业暴行或者说是官僚体制的无助受害者.甚至拖着受伤的腿走进法庭  
            - 苏格拉底死也不让家属出现在陪审团面前  
            - 杀害父母的辩护居然是,他现在成了一个孤儿
****** R2. 红色鲱鱼(The Red Herring)
红色鲱鱼: 能产生作用,靠的是转移注意力的谬误论证  
    在讨论的时候,听众被勾引专注于讨论话题的某方面,而这些方面可能和讨论的话题的真假无关,这样偏离了讨论的真正核心  
    场景:
        - 文学中,故意加上某些角色和事故误导读者和侦探
        - 政治目的和性丑闻那些让读者分神的东西
    应用技巧多种多样:
        - 你说收房产税,他说政府开赌场  
        - 你说市场经济好,他说有贫富差距. 但是,如果该团体大部分人都合理富裕,富裕的大多数和极少数人的巨大差距不能反驳  
        - 你说军事演习不好,他说你在反恐问题上立场软弱  
        - 立法强制公司保护员工养老基金,立法者提议急需为退休职工如何处理退休金提供更好的法案  
        - 杜克大学强奸案中,校员工的辩护是:真正的社会灾难是"百分之十八的美国公民生活在贫困线以下"  
****** R3. 稻草人
稻草人: 将对手立场解读为非常容易驳倒的论点再加以反驳 
    对比红色鲱鱼:
        相同:也是从真正的论点中将注意力转移.  
        不同:转移的方式不同,将不同阵营原本复杂的冲突转向新的不同冲突,而不是停留在原来的争论中  
    形式: 假设要攻击的立场采用了最极端的观点,任何行为或政策都会
    例子:
        - 强调扩大中央权力的人会被谬误地指责,试图将政府转变为"专制头目".专制头目就是稻草人  
        - 强调地方权力的人会被描述为高效政府的敌人  
    利弊:  
        搞得不好被人发现了,就编变成了低级粉高级黑  
****** R4. 人身攻击
人身攻击论证:最为致命.
    对比稻草人: 不仅不公,经常加给对手以严重的个人伤害,没留下任何机会给谴责难者揭露谬误或予以还击  
    类别:
        A. 诽谤:明显或暗含地指责对手缺乏一贯性  
            贬低对手的品格,否认他们的智力或推理能力,质疑他们的正直,等等.实际个人品格与命题在逻辑上无关联  
            单纯就意见的提出者是"激进派"或"保守派",意见可能被抨击为无价值的.  
            心里上,诽谤能激起听者对某提倡者的反对意见,促进听者的情感上的反对态度到该提倡者的观点  
            eg.
                抵制优先雇佣运动的人否认自己是种族主义者,事实是,他们真正的动机是种族歧视,认为非裔美国人天生低劣  
            变形: 
                - 特殊宗教或政治信仰  
        B. 背景谬误: 指责对手由于他属于某集团缺乏信任价值  
            将个人背景当做相反论证的前提  
            如果仅仅因为对手的职业~国籍~政治联系或其他背景,就固执地迫使对手接受或拒绝某个结论,那么这样的论证就是谬误的  
            eg.
                - 圣职人员必须接受某个给定观点,因为否定它就与圣经相矛盾,这是不公平的  
                - 若认为政党候选人必须支持某些政策,因为它是其所属政党纲领中公开宣示的,这也是不公正的
                - 我说你虐杀动物,你说我吃肉.批评者食肉与猎人为娱乐猎杀动物根本不沾边  
            看谁在说话: 你跟我一样糟糕,跟你抱怨的东西一样罪恶  
            eg. 
                - 本拉登,美国说你是恐怖分子. 本拉登说,美国才是恐怖分子,所以美国政府的话没有根据  
            污泉:  
                eg. 纽曼的主张不能信,因为他是牧师,首先要忠诚而不是真理.
                    纽曼反驳:这种人身攻击使他也使得所有天主教徒想要反驳而不得,因为一旦反驳就会被他人指责,污染了对话之泉  
        重要限定:
            人身攻击谬误建立在,对某人的攻击一般与这个人提供论证客观的价值没有关联  
            然而,某人做了个论断,这个论断如果为真将会支持结论,那么怀疑这个人的证词来怀疑结论是合理的  
            eg.
                法庭上,让陪审团注意证人的不可信是被允许的,能削弱证人证词支持的断言.证词被采纳给证人获得巨大的收益,削弱证词,也是
                背景的削弱
****** R5. 诉诸暴力
诉诸暴力: 强权即公理  
    暴力威胁不必是武力.红毛药酒  
    隐蔽的威胁:如果讨论的命题得不到完全赞同会有某种危险降临的暗示.
        没有人会被这种论证愚弄,但可以适当做出行动.    
        eg.
            总统仍然信任司法部长,我也信任司法部长,你们也应信任司法部长.谁反对,可以走了  
****** R6. 不得要领
不得要领:论证走歪,前提和结论之间出现"断裂"的时候,就犯了该谬误  
    可能是精巧骗术的工具,一般是思维凌乱的谬误  
    不得要领是错误的拒斥,提出者没有完全理解争论中的命题出现的混乱.  
    eg.
        - 一派提出支持P--减轻对资本的需求,另一派提出Q--关于学前教育重要性的命题  
        - 取消遗产继承税,因为被继承人获取他们以前就纳过税了.遗产税的支持者会说针对的只是承受该税的清单,而且国家需要这笔钱
            该论证指出重复征税不公平的.
        - 争论发展新的和非常昂贵的武器系统是否明智时. 简单地解释需要强大的国防.
            武器系统是否真正需要--国家安全~平衡的预算等  
 
** 概览
- R1. 诉诸情感
    对结论的支持通过不正常地听者的爱国心~同情心等类似感情达到
- R2. 红色鲱鱼
    将讨论的话题转移到讨论话题的某方面,从而脱离真正的话题
- R3. 稻草人
    将对手的观点极端化,对比原来的真人极端化的观点就像是稻草人.然后攻击极端化的观点
- R4. 人身攻击论证
    不攻击命题的根据,而攻击命题的提出者.诽谤他人或者根据特殊背景来定性某人.背景谬误常见的有看谁在说话,严重的有污泉
- R5. 诉诸暴力
    威权即正义
- R6. 不得要领
    反对者反对不是对手的观点,而是反对者强加给对手的观点,叫不得要领谬误.宏大叙事  
*** 4.4 不当归纳谬误
不当归纳:虽然前提与结论是相干的,但是相干的并不充分  
****** D1. 诉诸无知的论证
诉诸无知论证: 命题没有证明是真的,就不能断定它是真的.命题没有证明是假的,就不能断定它是假的    
    eg. 相传花岗岩是黑奴逃跑铁道的密码.历史学家没有找到任何证据.但是Miller认为它是真的  
    科学上: 无法找到断言为真的证据就断定为假,也是诉诸无知  
    伪科学: 国骗们坚持自己断言是真的,因为他们的批评者无法证明断言的假  
        eg. 
            - 伽利略观测到月亮的山脉和山谷,教会的水晶假说无法证伪  
              伽利略的反击,水晶上有山峰的假说,也无法证伪  
    社会变革: 无从知道是否起作用~是否安全,我们就必须不采用该变革.可行性和有效性的证明无法先行给出,经常用问句来暗示未知的风险  
        eg.
            如果Frankenstein博士坚持制造生物怪胎,我们怎么知道小野兽从实验室逃出将会发生什么?进而认为基因重组的实验都必须停止  
    政治变革: 可以被诉诸无知所反对,也可以被它所支持  
        eg. 威斯康星减少为孩子母亲提供额外利益.  
            有人问州长,有没有证据证明多生孩子为补贴.  
            州长: 没有,但是也没有反面证据  
    注意: 用适当的方式积极寻找并揭示证据或结果,最后没有证据或结果时,那么对于这个事实就可能有实质性的了解  
        不做结论与做出错误结论一样违反推理法则  
        eg. 用老鼠实验新药,没有毒性作用,那么可以认为可能对人类无毒的证据.  
    刑事的应用:
        证明某个人有罪之前,必须先假定无罪.因为宣判无罪者有罪的错误远比开释犯罪者错误更为严重  
        刑事案件中,辩护律师要求,如果被告除了合理怀疑外没有被证明有罪,那就应裁决无罪  
****** D2. 诉诸不当权威
诉诸不当权威:诉诸权威是对的,诉诸不当权威是错的:
    如果对某命题为真的断定以某人的权威为依据,而他在那个领域没有特殊的能力,那么这种错置诉诸权威就犯有谬误  
    - 找错了权威: 钱学森支持气功  
    - 广告
        eg. - 著名高尔夫球员推断汽车的优越性,某某名人为藏獒代言  
            - 电影明星为饮料代言
    - 危险的思维陷阱
        eg. 1. 把一位杰出物理学家强有力判断诉诸为某些国际条约的理据    
            2. 诉诸杰出小说,来决定真正的战争罪犯  
****** D3. 虚假原因
归纳逻辑和科学方法论:
    - 用假设,理解了原来不理解的特定因果关系  
    - 因果之间的本质联系  
    - 如何确定因果之间的关系是否存在  
虚假原因: 把实际不是某情形或事件的原因当作原因  
    缘出前物:错误地假定一事件是另一事件的原因,只因为另一事件在时间上紧随前者  
        eg. - 天狗食日,敲锣打鼓可以驱赶天狗  
            - 学校停止祷告,枪支~刀具~毒品和帮派就流行起来了.--将上帝赶出学校之后,我们送了一个人上月球  
            - 反常的天气状况归咎于不相关天象
            - 美国死刑带来的是,每100 000人中最高的反规律和数量最多的囚犯  
        滑坡谬误: 某个给定方向的第一步必然导致相同方向的进一步变化,由此带来严重后果,进而反驳  
            - 用来维持现状做辩护
            - 无论多么谨慎,只要是给定方向前进,就一定会产生沿该方向过度前进而产生的可怕后果  
            eg. 辅助自杀合法化的反驳. 
            反例,第一步构成了先例,进而使得该方向的行动变得更容易达到  
****** D4. 轻率概括
概括在推理中起着关键的作用,但是必须经过严格的审查,没有辩护就不能接受或假设它们是普遍适用的  
    eg. - 某人只因一次经历就对企业或国家下结论时,这个就是错误的概括
        - 特定国家和文化的人被冠以特定的形象
        - 吃炸透的食物导致胆固醇水平的提高.老板用他儿子例证  
        - 某些情况下一定的药物或食品可以是无害的,但是,并不是在所有情况下都无害.
        - 采访火车票的人
****** 概览
- D1. 诉诸无知论证
- D2. 诉诸不当权威
- D3. 虚假原因
- D4. 轻率概括
*** 4.5 预设谬误
假定未经证明的和无根据的前提为真  
留心那种偷偷溜进的假设及可疑之处与虚假性
****** P1. 偶然(Accident)
偶然谬误: 具体情况具体分析,总体上是真的概括在特殊环境(又叫偶然环境下)无法适用  
法律的普遍原理: 法庭外(传闻)证据是禁用的.但是当传闻证据的原说话人去世或者传闻证据的出现与报告传闻证据利益冲突时,该原则就不适用了.  
****** P2. 复杂问语(Complex Question)
复杂问语: 把预设某些论断为真到问句中来问问题.  
    问句本身不带判断的.但是严肃地提出问题,偷偷地引进预设,可以利用预设谬误达到提问者的目的  
    eg. - 与所有歇斯底里~恐惧和伪科学相伴,人为的全球变暖还是美国人遇到的最大谎言吗?  
            假定全球变暖是人为的  
        - 对多数租房不拥有房产又无需缴税的选民来说,你期望他们怎么关心要承担更不公平税负的人.  
            假定税负是不公平的,又假定租房人不受物业税的影响  
        - 将世界基因库沦落为专利的智力财富,受一小撮生命科学公司控制,其结果是什么?  
    应对: 这是一种欺骗设置,提问者提出的问题,回答者可以先澄清问题再回答,用解释问题中隐藏的前提来回答  
    报刊~头条: 法国接受贿赂了吗?  
        难道那位参议员能相信美国公众幼稚到会赞同任何权宜之计吗?  
    议会程序:
        - 推迟一年的提议,分开为是否要推迟,然后要推迟多久?可能我支持,但是我不支持推迟一年.  
    法庭:
        法官: 这表明,你的销售额的上升是这些骗人广告的结果.对吗?  
        证人: 它们没有这种效力!  
        法官: 那么你承认你的广告是骗人的啦.你这样做有多久?  
    否定孕蓄:
        问: 当你们吃冷焖羊肉时,你没有拿起斧头砍你妈妈四十下,又砍你爸爸四十一下?  
        答: 不对,那天我们吃的汤菜融干酪  
****** P3. 丐题
丐题: 假定了某人寻求证明的论题是真的错误.  
题: 争论中的问题  
丐题: 要求或者假设争论中的问题得到了承认的,我论证我自己  
    循环论证,构建很大并且具有迷惑性,很可能辨别不出来,逻辑错误因此在不知不觉中发生了  
    eg. - 总的来说,允许每个人都有不加限制的言论自由必定总是对国家有利的; 因为它非常有利于每个个体都毫无限制地享有表达其
            思想情感的自由,而这对社会共同体是有益的  
            因为自由好,所以自由好  
    有人用不同语言将伪装的起来的结论本身作为前提  
        eg. 没有不能诉诸实践的知识,因为不能诉诸实践的根本就算不上是知识  
    哲学史上的争议:  
        逻辑学家通过确证归纳原理为真,来寻求确证归纳程序的真实性  
        自然法则它们操纵今天一样也会操纵明天,本质上自然法则在基本方面是无变化的,因而我们可以依赖过去的经验指导我们未来的行为  
        未来本质上像过去一样.难以证明.为什么得出未来和过去一样? 回答道: "因为它总是和过去一样."  
        过去的未来的确都与过去一样:"我们怎么能够知道未来的未来和过去一样呢?"  
****** 概览
- P1. 偶然
- P2. 复杂问句
- P3. 丐题 
*** 4.6 含混谬误
含混谬误(诡辩):用心不转或者故意操作,论证过程中,词或短语的意义可能发生了变化.在前提一个意思,在结论却是另外一个意思  
****** A1. 歧义
歧义谬误: 有意无意地混淆词或短语的几个意义  
    eg. 国王: "你们谁走过这条路?"  
        送信人: "Nobody"  
        国王" "Nobody比你们走的慢"  
    有时歧义是机智的工具  
        eg. have faith in  
            have faith in 总统, 等于 断定,对于每个人来说显然知道有个人是总统,总统存在; 而他在断定他的信心,即总统总体来说会做于
            人民有益的事  
            have faith in 心灵感应, 不意味对心灵感应会做工作信心,而是说心灵感应存在  
            have faith in God, 两个意思: 如果上帝存在,那么他会做对人类有益的事是合理的. 无论有何证据,都相信完美的上帝存在  
    错误地适用相对性词项而来的错误  
        eg. - 象是动物,因此小象是小动物
            - 某某是好将军,因此会成为一个好总统
****** A2. 双关
双关谬误: 前提的语法结构问题,导致前提的表达有歧义  
    当以其为真的解释来表述论证前提,而以使其为假的解释得出结论  
    eg. - Women prefer Democrats to men.(女人比男人更喜欢民主党;女人更喜欢民主党而不是男人)  
        - The farmer blew out his brains after taking affectionate farewell of his family with a shotgun
****** A3. 重音  
重音谬误: 单个词语或短语的不同强调而变动.  
    有些拼法相同的词语基于其被发音或重读的方式而具有不同的意义  
    强调的谬误:
        我们不应当说朋友的坏话.  
        普通: 我们不应当去做说朋友坏话的事情  
        强调不: 我们可以说不是朋友的坏话  
        强调说坏话: 我们不应当说朋友的坏话,但是可以做坏事 
        强调我们: 意思使用的对象是我们,而不是其他人  
    把引用的语段从其语境拿出,再把它放入另外一种语境,从而得出根本不能从其最初语境得出的结论.  
        - 共和党指责民主党说: "在抽烟与肺癌之间没有已证联系"  
          完整陈述是: 烟草公司的科学家"面无表情地称在抽烟与肺癌之间没有已证联系..."  
        - 有人说林肯说过: "我从来没见哪两个人身上是真的,我必须承认从来没见过连体双胞胎"  
            实际上是林肯驳斥他人的观点  
    广告:
        - 今年百老汇出现的最滑稽的剧目!  
        - 印刷字体及图片, 新闻报道标题中的大号字敏感词汇,标题后面其他词汇以很小的字加以限制  
            注意小字印刷  
        - 政治宣称中,选择令人误解的敏感标题或使用部分省略的图片.  
        - 非常低的价格往往以非常大的字出现,后面却跟随着字体极小的完全说明
    操纵位置以重音来欺骗人  
        - 助手今天喝醉了,助手报复:船长今天清醒了  
****** A4. 合成
合成谬误:(质变)
    类似: 轻率概括(仅仅是量变)  
    1. 整体之部分的性质得到整体本身性质的推理  
       部分到整体的无效推广  
        eg. 由于某一剧本的每一场都是艺术完美的模范,所以该剧本作为一个整体也是艺术完美的  
            因为每条船都准备好了战斗所以整个舰队就一定准备好了战斗一样  
    2. 从一个汇集的单个元素或分子的性质得到该汇集总体或元素全部的性质的推理,分布式与汇集式用法  
       对一个词项的分布式断言是真的,因而该词项的汇集式断言也是真的  
       分子或元素到汇集的无效推广  
        eg. - 因为一辆公共汽车比一辆小汽车用油多,所以全部公共汽车的用油比全部小汽车的用油多
            - 虽然每学期大学上注册不超过六个不同的班级(分布式用法),但是,每学期大学生注册成百上千个不同班级也是真的(汇集式)  
            - 第二次世界大战中所投的原子弹比所投的常规炸弹造成的损害多  
****** A5. 分解
分解谬误:(有一个质的改变)
    类似: 偶然谬误(仅仅是量变)
    1. 断言对一个整体为真的东西一定对它的部分也是真  
        eg. - 因为某公司非常重要,并且某先生是那个公司的官员,因此某先生就非常重要  
            - 某机器沉重~复杂或贵重前提得出该机器的任何部分都一定沉重~复杂或者贵重
            - 学生一定住着大房子,因为该房间位于一座大楼中  
    2. 从元素的汇集性质而得出元素自身的性质
        eg. - 因为大学生(汇集)学习医学~法律~工程~牙科和建筑学,所以任何大学生(分布)都学习医学~法律~工程~牙科和建筑学  
            - 有效:狗是肉食的.阿富汗猎犬是狗.因此,阿富汗猎犬都是肉食的  
            - 分解谬误:经常在街道上遇到狗.阿富汗猎犬都是狗.因此,经常在街道上遇到阿富汗猎犬.  
            - 人都要死的.苏拉拉底是人.因此,苏格拉底是有死的.  
            - 分解谬误: 美国印地安人在消失.那个人是美国印第安人.因此,那个人在消失.  
****** 第4章概要
谬误是那种看起来正确实际经过考察证明并非如此的论证  
1. 相干谬误
    - R1. 诉诸情感
    - R2. 红色鲱鱼
    - R3. 稻草人
    - R4. 人身攻击
    - R5. 诉诸暴力
    - R6. 不得要领
2. 不当归纳谬误
    - D1. 诉诸无知
    - D2. 诉诸不当权威
    - D3. 虚假原因
    - D4. 轻率概括
3. 预设谬误
    - P1. 偶然
    - P2. 复杂问语
    - P3. 丐题
4. 含混谬误
    - A1. 歧义
    - A2. 双关
    - A3. 重音
    - A4. 合成
    - A5. 分解
* 第二部分 演绎
* A篇 古典逻辑
* B篇 现代逻辑
* 第三部分 归纳








































