#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 01 Ruins of the ancient Sumerian city of Uruk
#+begin_verse
In 1849,
	a daring young Englishman made a hazardous journey into the deserts and swamps of southern Iraq.
Moving south down the banks of the Euphrates River
		while braving high winds and temperatures that reached 120 degrees Fahrenheit,
	William Loftus led a small expedition in search of the roots of civilization.
As he said,
	'From our childhood we have been led to regard this place as the cradle of the human race.'
	
Guided by native Arabs into the southernmost reaches of Iraq,
	Loftus and his small group of explorers were soon overwhelmed by what they saw.
He wrote,
	'I know of nothing more exciting or impressive than the first sight of one of these great piles,
	looming in solitary grandeur from the surrounding plains and marshes.'
One of these piles, known to the natives as the mound of Warka,
	contained the ruins of Uruk,
		one of the first cities in the world and part of the world's first civilization.
		
Southwest Asia was one area in the world where civilization began.
Although Western civilization did not yet exist,
	its origins can be traced back to the ancient Near East,
	where people in Southwest Asia and in Egypt, in northeastern Africa,
		developed organized societies, invented writing,
		and created the ideas and institutions that we associate with civilization.
The later Greeks and Romans
		who played such a crucial role in the development of Western civilization,
	were nourished and influenced by these older Near Eastern societies.
It is appropriate, therefore,
	to begin our story of Western civilization
		with the early civilizations of Southwest Asia and Egypt.
Before considering them, however,
	we must briefly examine prehistory
		and observe how human beings made the shift from hunting and gathering
			to agricultural communities and ultimately to cities and civilization.
#+end_verse
** expression
dare [der] daring: v.adj. involving a lot of risk or danger, or brave enough to do risky things大胆的
hazardous [ˈhæzərdəs]: adj. dangerous, especially to people’s health or safety危险的, 冒险的
swamp [swɑmp]: n. land that is always very wet or covered with a layer of water沼泽, 湿地
brave [breɪv]: v. brave it out to deal bravely with something that is frightening or difficult勇敢地面对
expedition [ˌekspəˈdɪʃ(ə)n]: n. a long and carefully organized journey, especially to a dangerous or unfamiliar place, or the people that make this journey远征, 探险队
cradle [ˈkreɪd(ə)l]: n. a small bed for a baby, especially one that moves gently from side to side ⇨ cot摇篮, 发源地
southernmost [ˈsʌðərnˌmoʊst]: adj. furthest south最南的
solitary [ˈsɑləˌteri]: adj. used to emphasize that there is only one of something SYN single单一的,孤独的
grandeur [ˈɡrænˌdʒʊr]: n. impressive beauty, power, or size壮丽,雄伟
marsh [mɑrʃ]: n. an area of low flat ground that is always wet and soft ⇨ bog, swamp湿地, 沼泽
mound [maʊnd]: n. a pile of earth or stones that looks like a small hill山冈
crucial [ˈkruʃ(ə)l]: adj. something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
nourish [ˈnɜrɪʃ]: v. to give a person or other living thing the food and other substances they need in order to live, grow, and stay healthy滋养
prehistory [ˌpriˈhɪst(ə)ri]: n. the time in history before anything was written down史前史
agriculture [ˈæɡrɪˌkʌltʃər] agricultural: n.adj. the practice or science of farming农业的, 农艺的
community [kəˈmjunəti]: n. the people who live in the same area, town etc社区
ultimate [ˈʌltɪmət] ultimately: adj.adv. someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最终的
Fahrenheit [ˈferənˌhaɪt]: n. a scale of temperature in which water freezes at 32° and boils at 212°华氏温度计
--------------------
move south down sp.: 沿着某地南下
in search of sth.: 寻找某物
high winds: 强风
loom from sth.: 从...隐现
know of nothing more adj. than sth.: 不知道什么比某事更...
make the shift from A to B: 从A转变到B
the roots of sth.: 某事物的根源
human race: 人类
be appropriate to do sth.: 适宜做某事
** sentence
dare daring: v. adj. involving a lot of risk or danger, or brave enough to do risky things大胆的
- How dare you?
- A daring Englishman journeyed to the Mongol where he brought gunpowder to Europe.
- In my youth, a kid who plays truant from school was regarded as daring.
hazardous: adj. dangerous, especially to people’s health or safety危险的, 冒险的
- His hazardous trip reached its apogee when he crept into a boat which was sailing across the Atlantic. 
- Before your hazardous journey, you must take precaution so that no one can recognize you.
- It is hazardous to cook meth in such a hurry.
swamp: n. land that is always very wet or covered with a layer of water沼泽, 湿地
- At last, they decided to carry the body to the swamp.
- No one could account for the fact that they enact a ritual to bury body in the swamp.
- When winter comes in, these girls and boys like to ice skate on the freeze swamp.
brave: v. brave it out to deal bravely with something that is frightening or difficult勇敢地面对
- Don't be hard on me, I am braving bad grades at the semester.
- He couldn't brave the lung cancer on such short notice.
- When the steering wheel came away, the driver braved it and tried his best to make it under control.
expedition: n. a long and carefully organized journey, especially to a dangerous or unfamiliar place, or the people that make this journey远征, 探险队
- He leads a group of expedition to find buried treasures which were said to be buried by pirates.
- The high winds and temperatures exhausted expedition, which led to rebellions in the plain.
- The expedition must have sacked this village.
cradle: n. a small bed for a baby, especially one that moves gently from side to side ⇨ cot摇篮, 发源地
- You are a shoplifter who stole the cradle from a store.
- You must have the cradle repaired.
- All cradles must have been sold out, she exclaimed.
southernmost: adj. furthest south最南的
- Sorry to interrupt you, but the country is southernmost in Europe.
- He tried to drive to a southernmost halmet in this plain so that he could stay out of the limenight.
- You, the southernmost guy, get out of my house, now.
solitary: adj. used to emphasize that there is only one of something SYN single单一的,孤独的
- My house is the solitary modern house in the district.
- He noticed with dismay that his daughter did solitary work in the factory.
- He was the solitary boy who moved in a circle in the class.
grandeur: n. impressive beauty, power, or size壮丽,雄伟
- As soon as he goes to China, he will admire for the grandeur of the Great Wall.
- I was stunned by the grandeur of the mountains.
- The grandeur of the painting on the ceiling of the Sistine chapel must satisfy him as an artist.
marsh: n. an area of low flat ground that is always wet and soft ⇨ bog, swamp湿地, 沼泽
- Imagine his dismay when he found he couldn't ice skate on the marsh even though it froze.
- He often risks his life in this way to look at marshes.
- He must kill his wife who was thrown into the marsh.
mound: n. a pile of earth or stones that looks like a small hill山冈
- Patches of green appeared on the deserted mound.
- These mounds threated surrounding villages, for it would cause serious floods.
- Villagers tried to cultivate tomatoes on the mound.
crucial: adj. something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
- The profit our company made last year is so crucial that we began to dominate the market of this kind of product.
- Your disguise proved crucial, for these police haven't recognized you.
- The portion of the ingredient was so crucial that they managed to make cannons.
nourish: v. to give a person or other living thing the food and other substances they need in order to live, grow, and stay healthy滋养
- The soil near the river nourished the masses of the continent.
- The poor who work with their hands have no time to nourish their warfare skills.
- These street skills nourished a famous prizefighter who brought science to the box. 
prehistory: n. the time in history before anything was written down史前史
- He raised a fundamental question about prehistory.
- He published an article on prehistory which inspired awe in many historians.
- The prehistory of human race still remains a mystery.
agriculture agricultural: n.adj. the practice or science of farming农业的, 农艺的
- Pratices make your agricultural skills perfect.
- I don't have access to the archives of the Argicultural Bank.
- The agricultural civilization proved resilent, for it have continued for over 5000 years.
community: n. the people who live in the same area, town etc社区
- The sheriff in the community is always raising money for one cause or another.
- A fire extinguisher came away in our community.
- A daring Englishman will carry the weapon to our community.
ultimate ultimately: adj.adv. someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最终的
- The corporation proclaimed that the system they published yesterday would be the ultimate version.
- She likes to sneer at anyone who talks to her, ultimately let everyone dislike her in the community.
- The bull charged at him at tremendous speed, ultimately the poor guy had to go to hospital.
Fahrenheit: n. a scale of temperature in which water freezes at 32° and boils at 212°华氏温度计
- 
- 
- 
--------------------
move south down sp.: 沿着某地南下
- If our legions had moved south down the river, we wouldn't have ran into the lack of water.
- Move south down the road, you will find the library on your left.
- As the steering wheel came away, the car just moved south down the road.
in search of sth.: 寻找某物
- He is search of diamond which is worth $15.
- In search of $15 worth of fish he caught old boots.
- His wife cheated on he when he was in search of his private collection.
high winds: 强风
- A gust of high wind swept the matress out of his roof.
- In spite of high winds, he succeeded in sailing across the Atlantic.
- If there had not been high winds, they would have taken lead in the competition.
loom from sth.: 从...隐现
- Looming from a shady spot, a puma at large is hunting a rabbit.
- Looming from the tower, he pointed out that the priest had a skeleton in a cupboard.
- Looming from the dark, he admitted that he had kept his wife in hiding.
know of nothing more adj. than sth.: 不知道什么比某事更...
- I know of nothing more dear than my cat I shared my house with. 
- In her youth, she knew of nothing more important than good grades which qualified her.
- My wife exclaimed that she knew of nothing more delicious than this special kind of fish.
make the shift from A to B: 从A转变到B
- No one could account for the fact that the boy made the shift from a poor to a millionaire.
- No doubt, he made the shift from a manual worker to a white collar.
- It astounded him that his wife made the shift from a housewife to a CEO.
the roots of sth.: 某事物的根源
- I have no time to figure out the roots of every worker.
- He undertook the arduous project to search for the roots of the civilization.
- The police took precaution to figure out the root of the new meth.
human race: 人类
- The intellectual raised fundamental questions about the value and importance of human race.
- In pursuit of the happiness of human race, a group of scientists undertook the arduous project.
- The pope enacted a ritual to ask for the salvation of human race.
be appropriate to do sth.: 适宜做某事
- His wife complained it was not appropriate to buy a car on such short notice.
- Sir, it's not apporpriate to park on a no-parking area.
- You're appropriate to follow in your father's footstep.
** sentence2
dare daring: v. adj. involving a lot of risk or danger, or brave enough to do risky things大胆的
- How dare you?
- A daring Englishman journeyed to the Mongols where he brought gunpowder to Europe.
- In my youth, a kid who plays truant from school was regarded as daring.
hazardous: adj. dangerous, especially to people’s health or safety危险的, 冒险的
- His hazardous trip reached its apogee when he crept into a boat that was sailing across the Atlantic. 
- Before your hazardous journey, you must take precautions so that no one can recognize you.
- It is hazardous to cook meth in such a hurry.
swamp: n. land that is always very wet or covered with a layer of water沼泽, 湿地
- At last, they decided to carry the body to the swamp.
- No one could account for the fact that they enacted a ritual to bury the body in the swamp.
- When winter comes in, these girls and boys like to ice skate on the frozen swamp.
brave: v. brave it out to deal bravely with something that is frightening or difficult勇敢地面对
- Don't be hard on me, I am braving bad grades during the semester.
- He couldn't brave the lung cancer on such short notice.
- When the steering wheel came away, the driver braved it and tried his best to make it under control.
expedition: n. a long and carefully organized journey, especially to a dangerous or unfamiliar place, or the people that make this journey远征, 探险队
- He leads an expedition to find buried treasures that were said to be buried by pirates.
- The high winds and temperatures exhausted the expedition, which led to rebellions in the plain.
- The expedition must have sacked this village.
cradle: n. a small bed for a baby, especially one that moves gently from side to side ⇨ cot摇篮, 发源地
- You are a shoplifter who stole the cradle from a store.
- You must have the cradle repaired.
- All cradles must have been sold out, she exclaimed.
southernmost: adj. furthest south最南的
- Sorry to interrupt you, but the country is the southernmost in Europe.
- He tried to drive to one of the southernmost helmets in this plain so that he could stay out of the limelight.
- You, the southernmost guy, get out of my house, now.
solitary: adj. used to emphasize that there is only one of something SYN single单一的,孤独的
- My house is the solitary modern house in the district.
- He noticed with dismay that his daughter did solitary work in the factory.
- He was the solitary boy who moved in a circle in the class.
grandeur: n. impressive beauty, power, or size壮丽,雄伟
- As soon as he goes to China, he will admire the grandeur of the Great Wall.
- I was stunned by the grandeur of the mountains.
- The grandeur of the painting on the ceiling of the Sistine Chapel must satisfy him as an artist.
marsh: n. an area of low flat ground that is always wet and soft ⇨ bog, swamp湿地, 沼泽
- Imagine his dismay when he found he couldn't ice skate on the marsh even though it froze.
- He often risks his life in this way to look at marshes.
- He must kill his wife who was thrown into the marsh.
mound: n. a pile of earth or stones that looks like a small hill山冈
- Patches of green appeared on the deserted mound.
- These mounds threatened surrounding villages, for it would cause serious floods.
- Villagers tried to cultivate tomatoes on the mound.
crucial: adj. something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
- The profit our company made last year is so crucial that we began to dominate the market for this kind of product.
- Your disguise proved crucial, for these police haven't recognized you.
- The portion of the ingredient was so crucial that they managed to make cannons.
nourish: v. to give a person or other living thing the food and other substances they need in order to live, grow, and stay healthy滋养
- The soil near the river nourished the masses of the continent.
- The poor who work with their hands have no time to nourish their warfare skills.
- These street skills nourished a famous prizefighter who brought science to the box. 
prehistory: n. the time in history before anything was written down史前史
- He raised a fundamental question about prehistory.
- He published an article on prehistory which inspired awe in many historians.
- The prehistory of the human race still remains a mystery.
agriculture agricultural: n.adj. the practice or science of farming农业的, 农艺的
- Pratices make your agricultural skills perfect.
- I don't have access to the Agricultural Bank archives.
- The agricultural civilization proved resilient, for it has continued for over 5000 years.
community: n. the people who live in the same area, town etc社区
- The sheriff in the community is always raising money for one cause or another.
- A fire extinguisher came away in our community.
- A daring Englishman will carry the weapon to our community.
ultimate ultimately: adj.adv. someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最终的
- The corporation proclaimed that the system they published yesterday would be the ultimate version.
- She likes to sneer at anyone who talks to her, ultimately letting everyone dislike her in the community.
- The bull charged at him at tremendous speed, ultimately the poor guy had to go to hospital.
Fahrenheit: n. a scale of temperature in which water freezes at 32° and boils at 212°华氏温度计
- 
- 
- 
--------------------
move south down sp.: 沿着某地南下
- If our legions had moved south down the river, we wouldn't have run into the lack of water.
- Move south down the road, you will find the library on your left.
- As the steering wheel came away, the car just moved south down the road.
in search of sth.: 寻找某物
- He is in search of the diamond which is worth $15.
- In search of $15 worth of fish he caught old boots.
- His wife cheated on him when he was in search of his private collection.
high winds: 强风
- A gust of high wind swept the mattress out of his roof.
- In spite of high winds, he succeeded in sailing across the Atlantic.
- If there had not been high winds, they would have taken the lead in the competition.
loom from sth.: 从...隐现
- Looming from a shady spot, a puma at large is hunting a rabbit.
- Looming from the tower, he pointed out that the priest had a skeleton in a cupboard.
- Looming from the dark, he admitted that he had kept his wife in hiding.
know of nothing more adj. than sth.: 不知道什么比某事更...
- I know of nothing more dear than the cat I shared my house with. 
- In her youth, she knew of nothing more important than good grades which qualified her.
- My wife exclaimed that she knew of nothing more delicious than this special kind of fish.
make the shift from A to B: 从A转变到B
- No one could account for the fact that the boy made the shift from a poor to a millionaire.
- No doubt, he made the shift from a manual worker to a white collar.
- It astounded him that his wife made the shift from a housewife to a CEO.
the roots of sth.: 某事物的根源
- I have no time to figure out the roots of every worker.
- He undertook the arduous project to search for the roots of the civilization.
- The police took precautions to figure out the root of the new meth.
the human race: 人类
- The intellectual raised fundamental questions about the value and importance of the human race.
- In pursuit of the happiness of the human race, a group of scientists undertook the arduous project.
- The pope enacted a ritual to ask for the salvation of the human race.
be appropriate to do sth.: 适宜做某事
- His wife complained it was not appropriate to buy a car on such short notice.
- Sir, it's not appropriate to park in a no-parking area.
- You're appropriate to follow in your father's footsteps.
** summary
In 1849, a daring Englishman led a small expedition into the desert and swamps of the Iraq,
	which is regarded as the cradle of the human race.
Into the southernmost reaches of the Iraq,
	he and his group of explorers were overwhelmed by what they saw,
	one of the great piles looming in grandeur from the surrouding plains and marshes.
One of these piles called the mound of Warka contained the ruin of Uruk,
	one of the first cities in the world and part of the world's first civilization.
The origins of Western Civilization can be traced back to the ancient near Nest.
The later Greeks and Romans who play a crucial role in Western Civilization
	were nourished and influenced by these older near Nest socities.
Therefore, it is appropriate to begin our story with the ancient Near Nest.
Before that, we must briefly examine prehistory
	and obverse how human being made the shift from hunting and gathering
		to agricultural communities and ultimately to cities and cilivization.
** summary2
In 1849, a daring Englishman led a small expedition into the desert and swamps of Iraq,
	which is regarded as the cradle of the human race.
Into the southernmost reaches of Iraq,
	he and his group of explorers were overwhelmed by what they saw,
	one of the great piles looming in grandeur from the surrounding plains and marshes.
One of these piles called the mound of Warka contained the ruin of Uruk,
	one of the first cities in the world and part of the world's first civilization.
The origins of Western Civilization can be traced back to the ancient Near East.
The later Greeks and Romans who played a crucial role in Western Civilization
	were nourished and influenced by these older Near East societies.
Therefore, it is appropriate to begin our story with the ancient Near East.
Before that, we must briefly examine prehistory
	and observe how human beings made the shift from hunting and gathering
		to agricultural communities and ultimately to cities and civilization.
