#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* The coronation of Charlemagne by Pope Leo III
#+begin_verse
In 800, Charlemagne, the king of the Franks, journeyed to Rome to help Pope Leo III,
	who was barely clinging to power in the face of rebellious Romans.
On Christmas Day, Charlemagne and his family,
		attended by Romans, Franks, and even visitors from the Byzantine Empire,
	crowded into Saint Peter’s Basilica to hear Mass.
Quite unexpectedly, at least according to a Frankish writer,
	'as the king rose from praying before the tomb of the blessed apostle Peter,
		Pope Leo placed a golden crown on his head.'
In keeping with ancient tradition, the people in the church shouted,
	'Long life and victory to Charles Augustus,
		crowned by God the great and pacific Emperor of the Romans.'
Seemingly, the Roman Empire in the West had been reborn,
	and Charles had become the first western emperor since 476.
But this 'Roman emperor' was actually a German king,
	and he had been crowned by the head of the western Christian church.
In truth,
	the coronation of Charlemagne was a sign not of the rebirth of the Roman Empire
		but of the emergence of a new European civilization.

By the year of Charlemagne's coronation,
	the contours of this new European civilization were beginning to emerge in western Europe.
Increasingly, Europe would become the focus and center of Western civilization.
Building on a fusion of Germanic, GrecoRoman, and Christian elements,
	the medieval European world first became visible in the Carolingian Empire of Charlemagne.
The agrarian foundations of the eighth and ninth centuries
		proved inadequate to maintain a large monarchical system,
	however, and a new political and military order based on the decentralization of political power
		subsequently evolved to become an integral part of the political world of the Middle Ages.

European civilization began on a shaky and uncertain foundation, however.
In the ninth century, Vikings, Magyars, and Muslims posed threats
	that could easily have stifled the new society.
But European civilization absorbed the challenges.
The Vikings and Magyars were assimilated, and recovery slowly began.
By 1000, European civilization was ready to embark on a period of dazzling vitality and expansion.
#+end_verse
** expression
rebellious [rɪˈbeljəs]: adj. deliberately not obeying people in authority or rules of behaviour造反的, 反叛的
basilica [bəˈsɪlɪkə]: n. a church in the shape of a long room with a round end(古罗马)长方形会堂, 长方形基督教堂
pray [preɪ]: v. to speak to God in order to ask for help or give thanks ⇨ prayer祈祷
apostle [əˈpɑs(ə)l]: n. one of the 12 people chosen by Jesus Christ to teach and spread the Christian religion使徒(指耶稣十二使徒)
blessed [ˈblesəd]: adj. holy神圣的
pacific [pəˈsɪfɪk]: adj. peaceful and loving or wanting peace和平的
reborn [ˌriˈbɔrn]: v. to become active or popular again 再生
coronation [ˌkɔrəˈneɪʃ(ə)n]: n. the ceremony at which someone is officially made king or queen ⇨ crown加冕礼
rebirth [ˌriˈbɜrθ]: n. formal when an important idea, feeling, or organization becomes strong or popular again复兴
contour [ˈkɑnˌtʊr]: n. the shape of the outer edges of something such as an area of land or someone’s body轮廓
increasingly [ɪnˈkrisɪŋli]: adv. more and more all the time越来越多的
fusion [ˈfjuʒ(ə)n]: n. a combination of separate qualities or ideas熔合
medieval [ˌmediˈiv(ə)l]: adj. connected with the Middle Ages中世纪的
visible [ˈvɪzəb(ə)l]: adj. something that is visible can be seen OPP invisible看得见的, 明显的
agrarian [əˈɡreriən]: adj. relating to farming or farmers有关土地的
monarch [ˈmɒnə(r)k] monarchical [məˈnɑrkɪk(ə)l]: n.adj. a king or queen国王的
decentralize [diˈsentrəˌlaɪz] decentralization: v.n. to move parts of a government, organization etc from a central place to several different smaller ones OPP centralize分散
subsequently [ˈsʌbsɪkwəntli]: adv. after an event in the past OPP previously后来
shaky [ˈʃeɪki]: adj. weak and unsteady because of old age, illness, or shock虚弱的
stifle [ˈstaɪf(ə)l]: v. to stop something from happening or developing OPP encourage使窒息, 抑制
assimilate [əˈsɪmɪˌleɪt]: v. if people assimilate, or are assimilated into a country or group, they become part of that group and are accepted by the people in that group吸收
dazzling [ˈdæzlɪŋ]: adj. a light that is dazzling is very bright and makes you unable to see properly for a short time眼花缭乱的, 耀眼的
vitality [vaɪˈtæləti]: n. great energy and eagerness to do things活力
--------------------
journey to sp.: 旅行到某地
be barely clinging to power: 勉强抓住权力
be attended by sb.: 被某人陪伴
crowd into sp.: 涌入某地
rose from sth.: 从...起来
place a golden crown on sb's head: 给某人带上金冠
be crowned by sb.: 由某人加冕
prove inadequate to do sth.: 证明不足以做某事
evolve to become sth.: 演变成某物
pose threats: 构成威胁
** sentences
rebellious: deliberately not obeying people in authority or rules of behaviour造反的, 反叛的
- He used to be rebellious in his youth.
- It is not easy to settle his rebellious subjects without enough money.
- To my surprise, he turned out to be rebellious in the story.
pray: to speak to God in order to ask for help or give thanks ⇨ prayer祈祷
- There's at least one way to pay for food in a foreign country. 
- The woman who is at war is paying for her husband's safety.
- He spent large sums of money paying to the monks in the temple.
pacific: peaceful and loving or wanting peace和平的
- She never dreamed of a Pacific realm during the war. 
- These monks succeeded in developing a pacific community.
- The spokeswoman stated that the Chinese are always pacific when receiving a warm welcome.
reborn: to become active or popular again 再生
- The corpse which was said to be reborn at midnight had been executed beheadings. 
- The corpse was said to be reborn at midnight and suck the blood of passengers.
- This convinced the monk that the corpse in the coffin would be reborn at midnight.
coronation: the ceremony at which someone is officially made king or queen ⇨ crown加冕礼
- No need to worry, he is going to plan out the coronation to the last detail.
- He kept blaming his second son for the spoilt coronation.
- We consulted the map to find a place where the church would hold the coronation.
rebirth: formal when an important idea, feeling, or organization becomes strong or popular again复兴
- The emperor urged us to achieve the rebirth of his Empire.
- It seemed odd that the rebirth of nationalism in this region emerged at that time.
- This event was described as the rebirth of nationalism in this country.
contour: the shape of the outer edges of something such as an area of land or someone’s body轮廓
- It is not easy for me to recognize your contour in the dim light.
- Recognizing his contour behind the curtain,
		I was wondering whether he was playing the role of a prince.
- He blamed me for not recognizing his contour in the dim light.
increasingly: more and more all the time日益, 愈加
- Increasingly, I developed an unshakable faith in his method of studying English.
- Increasingly, she lost faith in my love so she broke up with me.
- Increasingly, he got familiar with reading long and dense books.
fusion: a combination of separate qualities or ideas熔合
- I love his work, which is a fusion of different styles. 
- A fusion of experiments and models must enhance my memory.
- This might explain why his work is full of fusions of different styles.
medieval: connected with the Middle Ages
- The medieval shield was said to be dug up in the tomb of a king.
- In the end, these medieval fragments were pieced together, and it turned out to be a scroll.
- Encountering storms, a cargo of medieval shields was sunken in the Pacific Ocean.
visible: something that is visible can be seen OPP invisible看得见的, 明显的
- It is composed of some visible glasses.
- It is visible that a rock hit the surface of the desktop.
- It is visible that you lost the faith in our love.
decentralize decentralization: to move parts of a government, organization etc from a central place to several different smaller ones OPP centralize分散
- After having decentralized its operations, the company claimed to go bankrupt. 
- In one study, 50% of people tend to decentralize their investments in business.
- Decentralizing our operations must be fatal for our company.
subsequently: after an event in the past OPP previously后来
- Earning enough money in a part-time job, he subsequently went to college by himself.
- These houses were subsequently the basic building blocks of their community.
- Going on a strike, they subsequently got paid in time.
shaky: weak and unsteady because of old age, illness, or shock虚弱的
- Because of infecting smallpox, he is mobilizing his immune system and becoming shaky.  
- The shaky lady deserves our help.
- These shaky slaves would be transported to the prison in the remote village.
stifle: to stop something from happening or developing OPP encourage使窒息, 抑制
- He was accused of stifling his wife in his youth.
- The brutal execution may stifle the prevailing crimes in this state.
- He cherished the hope that this law would stifle digging up coffins. 
assimilate: if people assimilate, or are assimilated into a country or group, they become part of that group and are accepted by the people in that group吸收
- Because of his hard work, he was assimilated into the United States
- Despite he was very popular with local people,
		 he was assimilated into the community.
- Assimilated into the country, she works as an engineer for a big firm.
dazzling: a light that is dazzling is very bright and makes you unable to see properly for a short time眼花缭乱的, 耀眼的
- My father told me that dazzling fireworks displays would be exhibited by the river.
- The dazzling paints were burnt down after a big fire.
- There are a lot of dazzling robots in this exhibition.
vitality: great energy and eagerness to do things活力
- Lisa, the City Comptroller, stated that the economic vitality of the city would be reborn next year.
- This law seems to stifle the economic vitality of the region.
- For the economic vitality of the country, the president propels these farmers into cities.
--------------------
journey to sp.: 旅行到某地
- My life can't help journeying to the beach on holidays.
- The legion journeyed to China to help the emperor who lost complete control over his provinces. 
- The legion journeyed to China to defend people against the Romans.
be barely clinging to power: 勉强抓住权力
- The emperor barely clinging to power was nervous throughout his life.
- The emperor who was barely clinging to power was killed when he was crowned.
- Losing complete control over the military, the emperor was barely clinging to power.
be attended by sb.: 被某人陪伴
- The old gentleman attended by his family is telling them pirate stories.
- I don't want to be attended by my wife when I'm dying.
- As soon as our cat is attended by us, she is happy.
crowd into sp.: 涌入某地
- Knowing the news that a group of pop singers would give performances,
		people in the town crowded into the station.
- Young people crowded into the exhibition to enjoy the fireworks display.
- A great many gangsters crowded into my store to ask for protect money.
rise from sth.: 从...起来
- The man rosing from the wheelchair turned out to be uninjured.
- You are supposed to rise from the seat while the old man is standing in front of you.
- Rosing from the seat, he said: 'Take my seat, sweet.'
place sth. on sb's head: 给某人带上某物
- What he placed on my head in the morning drove me mad.
- He refused to place a golden crown on the emperor's head.
- Placing a hat on his head, he waved to a taxi.
be crowned by sb.: 由某人加冕
- Crowned by a bishop, he had the authority to conduct his military.
- Crowned by a bishop, he was assimilated into this country.
- For centuries, kings had been crowned by the bishops of Rome.
prove inadequate to do sth.: 证明不足以做某事
- This proved inadequate to take a shower in the stream.
- This proved inadequate to assimilate so many foreign engineers.
- This proved inadequate to get it under control.
evolve to become sth.: 演变成某物
- This evolved to become a burial ritual in the local area.
- Giving food to the poor on the last day of the year evolved to become a tradition of our family.
- This evolved to become a habit of losing weight.
pose threats: 构成威胁
- It is hard to escape the conclusion that countries nearby are posing threats.
- Countries nearby posing threats don't scare us.
- The increasing crimes in our country are posing threats to our people.
