#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Street scene in a thirteenth-century English town
#+begin_verse
The new European civilization that had emerged in the ninth and tenth centuries
		began to come into its own in the eleventh and twelfth centuries
	as Europeans established new patterns that reached their zenith in the thirteenth century.
The High Middle Ages (1000--1300) was a period of recovery and growth for Western civilization,
	characterized by a greater sense of security and a burst of energy and enthusiasm.
New agricultural practices that increased the food supply
	helped spur a commercial and urban revival that,
			accompanied by a rising population,
		gave a new dynamism to a formerly static society.

Townspeople themselves were often great enthusiasts for their new way of life.
In the twelfth century,
	William Fitz-Stephen spoke of London as one of the noble cities of the world:
	'It is happy in the healthiness of its air, in the Christian religion,
		in the strength of its defences,
			the nature of its site, the honor of its citizens, the modesty of its women;
		pleasant in sports; fruitful of noble men.'
To Fitz-Stephen, London offered myriad opportunities and pleasures.
Fairs and markets were held regularly,
	and 'practically anything that man may need
		is brought daily not only into special places but even into the open squares.'
Any man, according to Fitz-Stephen,
	'if he is healthy and not a good-for-nothing,
		may earn his living expenses and esteem according to his station.'
Then, too, there are the happy inhabitants of the city:
	Where else has one 'ever met such a wonderful show of people
		this side or the other side of the sea'?
Sporting events and leisure activities are available in every season of the year:
	'In Easter holidays they fight battles on water.'
In summer, 'the youths are exercised in leaping, dancing, shooting, wrestling, casting the stone;
	the maidens dance as long as they can well see.'
In winter, 'when the great fen, or moor,
			which waters the walls of the city on the north side,
		is frozen,
	many young men play upon the ice;
	some, striding as wide as they may, do slide swiftly.'
To Fitz-Stephen, 'every convenience for human pleasure is known to be at hand' in London.
One would hardly know from his cheerful description
	that medieval cities faced overcrowded conditions,
		terrible smells from rotting garbage and raw sewage,
		and the constant challenge of epidemics and fires.

By the twelfth and thirteenth centuries,
	both the urban centers and the urban population of Europe were experiencing a dramatic expansion.
New forms of cultural and intellectual expression also arose in this new urban world.
Although European society in the High Middle Ages remained overwhelmingly agricultural,
	the growth of trade and cities
			along with the development of a money economy and new commercial practices and institutions
		constituted a veritable commercial revolution that affected most of Europe.
#+end_verse
** expression
spur [spɜr]: v. to encourage someone or make them want to do something鞭策, 刺激
defence [dɪˈfens]: n. all the systems, people, materials etc that a country uses to protect itself from attack防卫
modesty [ˈmɑdəsti]: n. a modest way of behaving or talking谦逊, 虚心
myriad [ˈmɪriəd]: adj. very many无数的
practically [ˈpræktɪkli]: adv. especially spoken almost几乎, 简直
good-for-nothing: adj. a good-for-nothing person is lazy and useless无用的, 无益的
esteem [ɪˈstim]: n. a feeling of respect for someone, or a good opinion of someone尊敬, 尊重
leisure [ˈleʒər]: n. time when you are not working or studying and can relax and do things you enjoy空闲
wrestle [ˈres(ə)l]: v. to fight someone by holding them and pulling or pushing them摔跤
maiden [ˈmeɪd(ə)n]: n. literary a young girl, or a woman who is not married SYN damsel少女, 处女
fen [fen]: n. an area of low flat wet land, especially in eastern England沼泽
moor [mʊr]: n. especially British English a wild open area of high land, covered with rough grass or low bushes and ↑heather, that is not farmed because the soil is not good enough沼地
stride [straɪd]: v. to walk quickly with long steps ⇨ march大步走
sewage [ˈsuɪdʒ]: n. the mixture of waste from the human body and used water, that is carried away from houses by pipes under the ground下水道, 污水
veritable [ˈverɪtəb(ə)l]: adj. a word used to emphasize a description of someone or something SYN real真正的
--------------------
come into sb's own: 充分展示自身价值
reach sb's zenith: 达到某人的顶峰
be characterized by sth.: 以某物为特征
a burst of sth.: 某物的突然爆发
give a new dynamism to sth.: 赋予某事物新的活力
be fruitful of sth.: 某物硕果累累
living expenses: 生活费
according to sb's station: 根据其地位
fight battles: 奋斗
be exercised in sth./doing sth.: 在某事中被锻炼
cast the stone: 扔石头
sth./sb. is known to do sth.: 某事物/某人做某事是已知的
be at hand: 即将发生/在手里
raw sewage: 未经处理的废水
** sentence
spur: v.to encourage someone or make them want to do something鞭策, 刺激
- My father spurred me to swim on my own when I was a kid.
- Mr. Leo is known to spur his students to read widely in English.
- My mother spurred me to save my pocket money in order to buy a bicycle.
defence: n.all the systems, people, materials etc that a country uses to protect itself from attack防卫
- The strength of defences is not enough to fight against these Asiatic armies.
- The defence of our capital city is vital for our realm. 
- I prefer to play in defence rather than attack others.
modesty: n.a modest way of behaving or talking谦逊, 虚心
- I really appreciated that you gave me a meal with your modesty.
- She always asks for inquiries with her modesty.
- The city is out of control, so no one will admire your modesty.
myriad: adj.very many无数的
- This ravaged city was dotted with myriad damaged bridges.
- This line turns out to be composed of myriad heads of people.
- The stone hit the surface of this building, which caused myriad fragments.
practically: adv.especially spoken almost几乎, 简直
- My aunt practically provides the supply of my pocket money.
- This so-called cursed tree is practically the source of income of this town.
- This special life practically perpetuates its existence in the extreme environment.
good-for-nothing: adj.a good-for-nothing person is lazy and useless无用的, 无益的
- A man in China who lost his job in middle age is practically regarded as good-for-nothing.
- I suggested that he is good-for-nothing for he missed it over and over again.
- Losing the game, Miss Lee accused her teammate of being good-for-nothing.
esteem: n.a feeling of respect for someone, or a good opinion of someone尊敬, 尊重
- Why doesn't she receive your esteem?
- Yes, she apologized to me in high esteem last night.
- The former headmaster used to be held in high esteem by his fellows.
leisure: n.time when you are not working or studying and can relax and do things you enjoy空闲
- In my leisure time, I have been studying English for over two years.
- My wife advised me to do housework in my leisure time.
- I am exercised in running in my leisure.
wrestle: v.to fight someone by holding them and pulling or pushing them摔跤
- She denied wrestling with boys in her leisure time.
- She denied that she hadn't wrestled with boys.
- She rolled up her sleeves and wrestled with the rude guy.
maiden: n.literary a young girl, or a woman who is not married SYN damsel少女, 处女
- The maiden the warrior married to turned out to be the long-lost daughter of the king.
- The maiden hopes for a knight who will rescue her from the dragon.
- Fingers crossed, the maiden will have the privilege of meeting a prince.
fen: n.an area of low flat wet land, especially in eastern England沼泽
- The airport by no means parks on the fen.
- The taxi driver refused a request from a businessman, for driving in the fen is too dangerous.
- She was astounded to find that the fen used to be a city.
moor: especially British English a wild open area of high land, covered with rough grass or low bushes and ↑heather, that is not farmed because the soil is not good enough沼地
- He won a prize for crossing the moor on his own.
- It is said that there are treasures left by pirates in the midst of the moor.
- A group of explorers examined the soil near the entrance of the moor with great care.
stride: to walk quickly with long steps ⇨ march大步走
- His father trained the disabled dog to stride on the plain.
- She must be exercised in striding in the summer workshop.
- Sweetie, I saw our baby striding just then.
sewage: n.the mixture of waste from the human body and used water, that is carried away from houses by pipes under the ground下水道, 污水
- How they dealt with sewage still remains a mystery.
- I don't expect sewage to be seen by our citizens. 
- She is an expert at dealing with sewage.
veritable: adj. a word used to emphasize a description of someone or something SYN real真正的
- In the pirate story, he turns out to be a veritable good man.
- A veritable gentleman won't let his girl cry.
- A veritable gentleman will be held in his esteem, even if he is defeated in a battle.
--------------------
come into sb's own: 充分展示自身价值
- Fulfilling his dream, he has come into his own.
- Breaking the world record,
		QuanHongchan, an 11-year-old girl, comes into her own at the Olympic games.
- Planning out the wedding to the last detail, she came into her own.
reach sb's zenith: 达到某人的顶峰
- Setting up a robot factory, the entrepreneur reached his zenith.
- The city may have reached its zenith when it became the center of trade in the world.
- The play reaches its zenith when the heroine is killed in action.
be characterized by sth.: 以某物为特征
- The city is characterized by the West Lake, regarded as the most beautiful scenery in China.
- The legion is characterized by a myriad of warriors who fight for our country.
- The street was characterized by myriad signs which are created by artists.
a burst of sth.: 某物的突然爆发
- They expressed their gratitude to the former City Comptroller in a burst of applause.
- The agreement must be reached about building the bridge in a burst of applause.
- After a burst of applause, she began to steal the diamonds in the exhibition.
give a new dynamism to sth.: 赋予某事物新的活力
- The article published yesterday gave a new dynamism to the career of an archaeologist.
- The new discoveries of fossils will give a new dynamism to the tasks of those paleontologists. 
- The invents of a new machine used to examine gold
		gives a new dynamism to the search for the lost treasure.
be fruitful of sth.: 某物硕果累累
- The school is fruitful of inventions.
- The city is fruitful of sophisticated knights.
- The athlete is fruitful of gold medals at this Olympic Games.
living expenses: 生活费
- After I quit my job, my manager offered me a part-time job to raise my living expenses.
- My father was unwilling to afford my living expenses when I was in the university.
- I am looking forward to my living expenses on the last day of the month.
according to sb's station: 根据其地位
- She thought she deserved a better position according to her station.
- She took her seat in the meeting according to her station.
- She will not be in obscurity in the town according to her station.
fight battles: 奋斗,作战
- You are lucky enough not to fight battles during the war.
- The knights were supposed to fight battles when the enemies pushed their way eastward.
- Quarrelling bitterly, two men fought battles in front of the museum,
		during which the crowd gathered round and the traffic was held up.
be exercised in sth./doing sth.: 在某事中被锻炼
- He must have been exercised in abduction by these gangsters and got rid of them.
- He must be exercised in crises of his family.
- It must be terrible to be exercised in a terrible accident.
cast the stone: 扔石头
- The scientist casts the stone with great care so that he can scrutinize its track.
- He is due to cast the stone on the plain at midnight.
- He had a hard time casting the stone after he got injured in a car accident.
sth./sb. is known to do sth.: 某事物/某人做某事是已知的
- Miss Lee is known to be an expert at playing tunes.
- I am known to tackle these math problems in our class.
- He is known to resist the temptation of the lord of the rings.
be at hand: 即将发生/在手里
- Mr. Lei believes that happiness is at hand.
- The spokesman claimed that as long as our warriors fought battles during the war,
		 the future of our state was at hand.
- There is a great deal of pleasure at hand if you try your best.
raw sewage: 未经处理的废水
- Even though the raw sewage has not been treated well,
		there is still enough supply of healthy water.
- It is more important than ever to treat the raw sewage in our drain system.
- We will treat the raw sewage through this process.
** summary
The High Middle Age (1000-1300) was a period of recovery and growth for Western civilization,
	characterized by a commercial and urban revival accompanied by a rising population
		which was spurred by the surplus of the food supply.
Townspeople were often great enthusiasts for their new way of life.
According to Fit-Stephen's descriptions, London offered myriad opportunities and pleasure,
	sporting events and leisure activities available in every season of the year.
	fairs and markets which were held regularly,
	and life expenses and esteem which were afforded as long as you were not a good-for-nothing.
However, medieval cities also faced overcrowded conditions,
	terrible smells, and the challenges of epidemics and fires.
Although European society remained overwhelmingly agricultural,
	the development of trade and cities
		accompanied the growth of a money economy and new commercial practices and institutions
	composed a veritable revolution that affected most of Europe.
