#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 10 A medieval abbot and his monks
#+begin_verse
The recovery and growth of European civilization in the High Middle Ages
	also affected the state and the church.
Both lords and vassals and the Catholic church
	recovered from the invasions and internal dissension of the Early Middle Ages.
Although lords and vassals seemed forever mired in endless petty conflicts,
	some medieval kings began to exert a centralizing authority
		and inaugurated the process of developing new kinds of monarchical states.
By the thirteenth century,
	European monarchs were solidifying their governmental institutions in pursuit of greater power.

The recovery of the Catholic church produced a reform movement
	that led to exalted claims of papal authority.
This increase in church power, coupled with the rise of monarchical states,
	made it almost inevitable that there would be conflicts between church and state.
At the same time,
	vigorous papal leadership combined with new dimensions of religious life
		to make the Catholic church a forceful presence in every area of life.
The role of the church in the new European civilization
	was quite evident in the career of a man named Samson,
	who became abbot or head of the great English abbey of Bury Saint Edmonds in 1182.
According to Jocelyn of Brakeland, a monk who assisted him,
	Abbot Samson was a devout man who wore undergarments of horsehair and a horsehair shirt.
He loved virtue and abhorred liars, drunkards and talkative folk.
His primary concern was the spiritual well-being of his monastery,
	but he spent much of his time working on problems in the world beyond the abbey walls.
Since the monastery had fallen into debt under his predecessors,
	Abbot Samson toiled tirelessly to recoup the abbey's fortunes by carefully supervising its manors.
He also rounded up murderers to stand trial in Saint Edmunds
	and provided knights for the king's army.
But his actions were not always tolerant or beneficial.
He was instrumental in driving the Jews from the town of Saint Edmunds
	and was not above improving the abbey's possessions at the expense of his neighbors:
He built up the bank of the fish-pond at Babwell so high,
		for the service of a new mill,
	that by the keeping back the water
		there is not a man, rich or poor, but has lost his garden and his orchards.
The abbot's worldly cares weighed heavily on him,
	but he had little choice
		if his abbey were to flourish and fulfill its spiritual and secular functions.
But he did have regrets; as he remarked to Jocelyn:
	If he could have returned to the circumstances he had enjoyed before he became a monk,
		he would never have become a monk or an abbot.
#+end_verse
** expression
vassal [ˈvæs(ə)l]: n. a man in the Middle Ages who was given land to live on by a lord in return for promising to work or fight for him封臣
dissension [dɪˈsenʃən]: n. disagreement among a group of people纠纷, 争执
petty [ˈpeti]: adj. a petty problem, detail etc is small and unimportant SYN trivial小的, 不重要的
centralize [ˈsentrəˌlaɪz]: v. to organize the control of a country, organization, or system so that everything is done or decided in one place OPP decentralize集聚, 集中, 施行中央集权
inaugurate [ɪˈnɔɡjəˌreɪt]: v. to open a building or start an organization, event etc for the first time开辟
solidify [səˈlɪdɪˌfaɪ]: v. to make an agreement, plan, attitude etc more definite and less likely to change SYN strengthen团结, 巩固
reform [rɪˈfɔrm]: v. a change or changes made to a system or organization in order to improve it改革
exalted [ɪɡˈzɔltəd]: adj. having a very high rank and highly respected尊贵的
papal [ˈpeɪp(ə)l]: adj. relating to the Pope罗马教皇的
vigorous [ˈviɡ(ə)rəs]: adj. strong and healthy精力旺盛的, 有力的, 健壮的
forceful [ˈfɔrsfəl]: adj. forceful arguments, reasons etc are strongly and clearly expressed SYN powerful有力的
abbot [ˈæbət]: n. a man who is in charge of a ↑monastery主持
abbey [ˈæbi]: n. a large church with buildings next to it where ↑monks and ↑nuns live or used to live修道院
devout [dɪˈvaʊt]: adj. someone who is devout has a very strong belief in a religion虔敬的
undergarment [ˈʌndərˌɡɑrmənt]: n. old-fashioned a piece of underwear内衣
abhor [əbˈhɔr] abhorred: v. to hate a kind of behaviour or way of thinking, especially because you think it is morally wrong憎恶, 痛恨
talkative [ˈtɔkətɪv]: adj. someone who is talkative talks a lot OPP quiet多嘴的
supervise [ˈsupərˌvaɪz]: v. to be in charge of an activity or person, and make sure that things are done in the correct way监督, 管理, 指导
secular [ˈsekjələr]: adj. not connected with or controlled by a church or other religious authority世俗的
--------------------
be mired in sth.: 陷入某事
be coupled with sth./sb.: 与...相结合
made it almost inevitable that + ...: 使得...几乎不可避免
fall into debt (under sb.): (在某人下)陷入债务
toil tirelessly: 不知疲倦地工作
round up sb.: 聚集某人
stand trial: 接受审判
be instrumental in doing sth.: 在做某事中起作用
drive sb. from sp.: 赶某人出某地
be not above doing sth.: 不高尚地做某事
** sentence
vassal: n. a man in the Middle Ages who was given land to live on by a lord in return for promising to work or fight for him封臣
- On arriving at the capital city, these vassals paid their lords a visit.
- The vassal who was supposed to fight against the Asiatic army received a warm welcome.
- These vassals were keeping guard at the entrance of the palace.
dissension: n. disagreement among a group of people纠纷, 争执
- She laughed at you scornfully, there must have been dissensions between you and her.
- My boss promised to protect me from internal dissensions in the company.
- Because of harsher working conditions, there was a burst of dissension yesterday.
petty: adj. a petty problem, detail etc is small and unimportant SYN trivial小的, 不重要的
- It reminds me of a petty mistake I made in my code.
- What a petty problem!
- His figure was so petty in the dime light that no one noticed his approach.
centralize: v. to organize the control of a country, organization, or system so that everything is done or decided in one place OPP decentralize集聚, 集中, 施行中央集权
- The emperor planned out these organizations to the last detail to centralize his vassals. 
- He found it relatively easy to centralize these subsidiaries.
- With the breakdown of his armies, he failed to centralize the provinces of the empire.
inaugurate: v. to open a building or start an organization, event etc for the first time开辟,举办
- The ceremony will be inaugurated next week,
		during which our City Comptroller will talk about new energy.
- China is allowed to inaugurate the next Olympic Games in Beijing.
- The growth of trade and cities inaugurated a new way of our lives.
monarch monarchical: adj. 国王的
- He established a set of monarchical laws prohibiting adultery.
- After being crowned by the pope, he drew up a set of monarchical laws to stimulate the birth rate.
- A set of monarchical laws was published in the press.
solidify: v. to make an agreement, plan, attitude etc more definite and less likely to change SYN strengthen团结, 巩固
- The instructor claimed that spaced repetitions are solidifying my memories.
- These vassals are solidifying the gate of the city to fight against Asiatic nomads.
- The priest is always raising money to solidify the bank of the fish pond.
reform: v.n. a change or changes made to a system or organization in order to improve it改革
- The century is regarded as fruitful of reforms.
- The reform movements reached their zenith in the last year of the century.
- The reform movements will come into their own when everyone gets acclimatized to it.
exalted: adj. having a very high rank and highly respected尊贵的
- The monk insists on the exalted claim of papal authorities.
- The king is so exalted that everyone in the state is subject to him.
- The exalted prince hopes for a knight who fights for his state.
papal: adj. relating to the Pope罗马教皇的
- According to the papal authorities, the grass will take root by then.
- The papal authorities are barely clinging to their power because of rebellious Romans.
- The papal authorities went out of their way to build the Gothic church.
vigorous: adj. strong and healthy精力旺盛的, 有力的, 健壮的
- I am not so vigorous as before I went to college.
- The prince had a major crush on a vigorous knight who used to keep guard for her.
- I might as well keep vigorous when running into serious troubles.
forceful: adj. forceful arguments, reasons etc are strongly and clearly expressed SYN powerful有力的
- Asiatic nomads who pushed their way westward became a forceful power in eastern Europe.
- Butchers are forceful because they are exercised in their work on a daily basis.
- No one could account for the fact that these nomads turned out to be forceful in action.
abbot: n. a man who is in charge of a ↑monastery主持
- The abbot was said to be killed in action.
- I felt obliged to protect the abbot from these invaders.
- The abbot who committed a murder was arrested by the monarchical knights.
abbey: n. a large church with buildings next to it where ↑monks and ↑nuns live or used to live修道院
- The life in the abbey tends to be simple in winter.
- I never dreamed of leading a life in the abbey.
- The abbey falls into debt under the greedy abbot.
devout: adj. someone who is devout has a very strong belief in a religion虔敬的
- It is impolite to look scornfully at a devout nun.
- A devout nun decided to dedicate herself to the god.
- I shall never be suspect of a devout abbot.
undergarment: n. old-fashioned a piece of underwear内衣
- Dressed in an undergarment, he went up the tower to figure out what had happened.
- Not dressed in an undergarment, he felt cool caught in the snow storms.
- I got my nerve to wear undergarments on my own.
abhor abhorred: v. to hate a kind of behaviour or way of thinking, especially because you think it is morally wrong憎恶, 痛恨
- I abhorred his habit of drinking heavily before sleeping.
- I needn't have abhorred your impolite behavior, for it's none of my business.
- I abhorred the man who lies to me over and over again.
talkative: adj. someone who is talkative talks a lot OPP quiet多嘴的
- Young man, if you were not so talkative, we would both enjoy our dinner.
- I abhorred the talkative guy who didn't keep my secret.
- Your mother got angry because you were talkative at the reception.
supervise: v. to be in charge of an activity or person, and make sure that things are done in the correct way监督, 管理, 指导
- The authorities fail to supervise these companies, for they are often family-controlled.
- It is necessary to supervise the growth of the grass in your courtyard.
- I abhor the video camera by which our boss can supervise us whenever he wants.
secular: adj. not connected with or controlled by a church or other religious authority世俗的
- For secular purposes, the papal pope placed a golden crown on his head. 
- For secular purposes, the abbot has to raise money to have the clock repaired.
- For secular purposes, the abbot built up the bank of the fish pond high.
--------------------
be mired in sth.: 陷入某事
- I needn't have been mired in such a murder you committed.
- The monarchical knight was said to be mired in a scandal.
- The experiment seems mired in the abuses of animals.
be coupled with sth./sb.: 与...相结合
- Coupled with Lee, we set up a robot factory in the suburb of the city.
- Coupled with Lee, we broke up a world record.
- Coupled with Lee, we developed a model to elaborate upon an atom in public. 
made it almost inevitable that + ...: 使得...几乎不可避免
- The growth of the university made it almost inevitable
		that there was a fight between students and people in the town.
- The development of trade made it almost inevitable
		that the cities began to emerge in the 11th century.
- The sudden death of the emperor made it almost inevitable
		that there was a series of dissensions in the empire.
fall into debt (under sb.): 陷入债务
- A burst of disasters has made the abbey fall into debt.
- You shouldn't have fallen into debt because I had given the living expenses.
- If you were not a good-for-nothing, you wouldn't fall into debt according to your station.
toil tirelessly: 不知疲倦地工作
- The devout abbot toiled tirelessly to spread the mightiness of the god.
- I used to toil tirelessly to get my work done.
- On arriving at the hotel, she toiled tirelessly to figure out the criminal.
round up sb.: 聚集某人
- The crowd was rounded up to reach a settlement about the working conditions and salaries.
- It is forbidden to round up people in public in this country.
- The priest rounded up people in the town to have the clock repaired.
stand trial: 接受审判
- The butcher is standing trial, for he deserted his regiment in action.
- With the lawyer being late for court, people in the court failed to stand trial.
- You are standing trial in front of your parents
	 because you played truant from school to kill your girlfriend.
be instrumental in doing sth.: 在做某事中起作用
- He was instrumental in making a profit this year.
- He was instrumental in publishing the article about the discovery of these fossils.
- He was instrumental in cleaning up the mass in the house.
drive sb. from sp.: 赶某人出某地
- She got so angry that she drove her nephew from her house.
- You needn't have driven our cat from our room because she won't jump on the bed.
- The abbot was instrumental in driving the Asiatic nomads from the province.
be not above doing sth.: 不怎么高尚地做某事
- He was not above building up his wall high.
- He was not above succeeding in setting up a new world record.
- he was not above following in his father's footsteps.
** summary
Because of the development and growth in the High Middle Ages,
	by the thirteenth century,
	monarchs began to exert a centralizing authority
			and inaugurated the process of new monarchical states
		so that they solidified their governmental institutions to pursue greater power.

At the same time,
	the papal leadership combined with new dimensions of religious life
		to make the church a vigorous presence in every area of life.
The increase in the Church power, coupled with the rise of monarchical states,
	made it inevitable that there would be conflicts between church and state.
Samson, an abbot in England,
	was a devout man who loved virtues and abhorred liars, drunkards, and talkative folks.
Although his primary concern is the well-being of his monastery,
	he had to spend more time working beyond the abbey walls
		because the monastery had fallen into debt under his predecessors.
He rounded up murders to stand trials and provided knights for the king's army.
However, he also played an important role in driving the Jews from his town
	and built up the bank of his fish pond to make others lose their gardens and orchards.
He regretted that if he had a chance, he would have never become an abbot. 
