#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 10 The rise of Kingdoms and the growth of church power
#+begin_verse
The period from 1000 to 1300 was a dynamic time in the development of Western civilization.
The nobles, whose warlike attitudes were rationalized
		by labeling themselves the defenders of Christian society,
	continued to dominate the medieval world politically, economically, and socially.
But kings gradually began to expand their powers.
Although the popes sometimes treated rulers condescendingly,
	by the thirteenth century, the monarchs were developing the machinery of government
		that would enable them to challenge exalted claims of papal power
			and assume political authority in Europe.
The actions of these medieval monarchs laid the foundation for the European kingdoms
	that in one form or another have dominated the European political scene ever since.

The Catholic church shared in the challenge of new growth
	by reforming itself and striking out on a path toward greater papal power,
		both within the church and over European society.
The High Middle Ages witnessed a spiritual renewal that led to numerous and even divergent paths:
	revived papal leadership,
	the development of centralized administrative machinery that buttressed papal authority,
	and new dimensions to the religious life of the clergy and laity.
At the same time,
	this spiritual renewal also gave rise to the crusading 'holy warrior' who killed for God,
		which created an animosity between Christians and Muslims
			that still has repercussions to this day.

The religious enthusiasm of the twelfth century continued well into the thirteenth
	as new orders of friars gave witness to spiritual growth and passion,
		but underneath lay seeds of discontent and change.
Dissent from church teaching and practices grew,
	leading to a climate of fear and intolerance
		as the church responded with inquisitorial procedures to enforce conformity to its teachings.
At the same time,
	papal claims of supremacy over secular authorities
		were increasingly challenged by the rising power of monarchical authorities,
			who, because of the growth of cities,
				the revival of trade, and the emergence of a money economy,
			were now able to hire soldiers and officials to carry out their wishes.

The High Middle Ages of the eleventh, twelfth, and thirteenth centuries
	had been a period of great innovation,
		evident in significant economic,
			social, political, religious, intellectual, and cultural changes.
And yet by the end of the thirteenth century,
	certain tensions had begun to creep into European society.
As we shall see in the next chapter, these tensions would soon bring a torrent of troubles.
#+end_verse
** expression
dynamic [daɪˈnæmɪk]: adj. full of energy and new ideas, and determined to succeed充满活力的
warlike [ˈwɔrˌlaɪk]: adj. liking war and being skilful in it好战的, 尚武的
dominate [ˈdɑmɪˌneɪt]: v. to control someone or something or to have more importance than other people or things支配
condescending [ˌkɑndəˈsendɪŋ] condescendingly: adj. adv. behaving as though you think you are better, more intelligent, or more important than other people – used to show disapproval SYN patronizing居高临下的
witness [ˈwɪtnəs]: v. to see something happen, especially a crime or accident目击
renewal [rɪˈnuəl]: n. when an activity, situation, or process begins again after a period when it had stopped复兴
diverge [daɪˈvɜrdʒ] divergent: v. adj. if similar things diverge, they develop in different ways and so are no longer similar分叉的
revive [rɪˈvaɪv]: v. to bring something back after it has not been used or has not existed for a period of time(使)复兴, (使)复活
administrative [ədˈmɪnɪˌstreɪtɪv]: adj. relating to the work of managing a company or organization管理的, 行政的
buttress [ˈbʌtrəs]: v. to support a system, idea, argument etc, especially by providing money扶持
clergy [ˈklɜrdʒi]: n. the official leaders of religious activities in organized religions, such as priests, ↑rabbis, and ↑mullahs ⇨ clerical神职人员
laity [ˈleɪəti]: n. the laity all the members of a religious group apart from the priests ⇨ layman普通信徒
animosity [ˌænɪˈmɑsəti]: n. strong dislike or hatred SYN hostility仇恨, 憎恶
repercussion [ˌripərˈkʌʃ(ə)n]: n. the effects of an action or event, especially bad effects that continue for some time ⇨ consequence反响
friar [ˈfraɪər]: n. a member of a religious group of Catholic men, who travelled around in the past teaching about Christianity and who were very poor ⇨ monk男修道士
passion [ˈpæʃ(ə)n]: n. a very strong feeling of sexual love ⇨ desire激情, 热情
underneath [ˌʌndərˈniθ]: prep. adv. directly under another object or covered by it在下面
discontent [ˌdɪskənˈtent]: n. a feeling of being unhappy and not satisfied with the situation you are in OPP contentment不满
innovation [ˌɪnəˈveɪʃ(ə)n]: n. a new idea, method, or invention改革, 创新
tension [ˈtenʃ(ə)n]: n. a nervous worried feeling that makes it impossible for you to relax ⇨ tense紧张
--------------------
label sb. sth.: 给某人贴上某物的标签
assume political authority: 承担政治权力
lay the foundation for sb./sth.: 为某人/某物打下基础
in one form or another: 以一种形式或另一种
in the challenge of sth.: 在...的挑战中
strike out on a path toward sp./sth.: 开辟通往某地的道路
lay seeds of sth.: 种下某事的种子
be dissent from sth.: 对某事持不同意见
respond with sth.: 以...回复
enforce conformity to sth.: 强制遵守某事
supremacy over sth.: 凌驾于某物
carry out sb's wishes: 实施某人的意愿
creep into sp.: 悄悄进入某地
a torrent of sth.: 一股...的洪流
** sentence
dynamic: adj. full of energy and new ideas, and determined to succeed充满活力的
- My son told me that he was very dynamic in his age.
- These dynamic youths shouldn't have been sold into slavery in North Africa.
- This dynamic cat is now developing a fever.
warlike: adj. liking war and being skillful in it好战的, 尚武的
- A group of vassals admired him for his warlike attitude.
- The knight is so warlike that he fights with other knights once a week.
- These warlike nomads declared the new Latin empire of Constantinople.
dominate: v. to control someone or something or to have more importance than other people or things支配
- He didn't expect his son to dominate the whole continent of Europe.
- The official has accused our products of dominating the market.
- The company that made a profit last year is dominating the market the world over.
condescending condescendingly: adj. adv. behaving as though you think you are better, more intelligent, or more important than other people – used to show disapproval SYN patronizing居高临下的
witness: v. to see something happen, especially a crime or accident目击
- 'What a mupulated bitch!', he said condescendingly.
- Not liking the way she dressed, the assistant told her condescendingly that the dress had been sold out. 
- The king was so condescending that he refused to be crowned by the pope.
renewal: n. when an activity, situation, or process begins again after a period when it had stopped复兴
- He is anxious to see the renewal of the empire.
- Encountering the renewal of the trade, the monarchy began to assume political authority.
- Encountering the renewal of the cities, the emperor is determined to dominate Europe.
diverge divergent: v. adj. if similar things diverge, they develop in different ways and so are no longer similar分叉的
- Divergent from his idea, I agreed that Mr. Leo won the election.
- Divergent from his wife, he must have quarreled bitterly with his wife yesterday.
- Two men holding divergent opinions quarreled bitterly in the royal court.
revive: v. to bring something back after it has not been used or has not existed for a period of time(使)复兴, (使)复活
- Our dream will have come true that our country will be revived by our people in the future.
- No one could account for the fact that the rise of trade in the cities revived the church power.
- The support of these vassals revived the exalted claim of papal authority.
administrative: adj. relating to the work of managing a company or organization管理的, 行政的
- He is known as an excellent administrative staff who works for a big firm.
- The administrative staff who sneaked out of his office during working time would be fined $2000. 
- I hate the administrative staff in the hospital who did body research twice.
buttress: v. to support a system, idea, argument etc, especially by providing money扶持
- The man in the boat used to buttress 2000 children who couldn't afford to pay their studying fares.
- With a star buttressing him, he succeeded in studying abroad and getting a doctorate degree at the university.
- The stranger who claimed to have buttressed him in his youth asked him for a large sum of money.
clergy: n. the official leaders of religious activities in organized religions, such as priests, ↑rabbis, and ↑mullahs ⇨ clerical神职人员
- A clergy in this district has the authority to meet the lord once a week.
- The clergy was accused of stealing the poor farmer a little lamb.
- The clergy is always raising money to have the clock repaired for one cause or another.
laity: n. the laity all the members of a religious group apart from the priests ⇨ layman普通信徒
- The king claimed that he was just a simple laity converted to Christianity.
- The hero never dreamed of living a normal life as a laity in a small village.
- These laities who ran into serious arguments with the knights left the town to settle down in the plain.
animosity: n. strong dislike or hatred SYN hostility仇恨, 憎恶
- There should not be any animosity between colleagues in our company.
- It astounded me that she has an animosity towards her husband.
- My wife has an animosity towards me, as I couldn't afford to go on a vacation in Sanya.
repercussion: n. the effects of an action or event, especially bad effects that continue for some time ⇨ consequence反响
- There must be a serious repercussion on his family because he died of cancer.
- The crusading army sacked the great capital city, which had a profound repercussion for the collapse of the empire.
- These knights who claimed to kill for god had repercussions for animosities between Muslims and Christians.
friar: n. a member of a religious group of Catholic men, who travelled around in the past teaching about Christianity and who were very poor ⇨ monk男修道士
- 
- 
- 
passion: n. a very strong feeling of sexual love ⇨ desire激情, 热情
- In one study, scientists find that the passion is crucial for someone in pursuit of his goal. 
- Reducing passion for making love with his wife, he cheated on her at a time when he was on a business trip.
- The ball reminds me of my passion for school basketball competition in my youth.
underneath: prep. adv. directly under another object or covered by it在下面
- They were talking about the article published in the press underneath the star.
- There is a complex drainage system underneath the street.
- The cat was left licking his wet fur underneath the basket.
discontent: n. a feeling of being unhappy and not satisfied with the situation you are in OPP contentment不满
- The king seems interesting with the growing discontent of townpeople with the church.
- He failed to express his discontent to his mother, who made him apply for an army service.
- Dare not to express his discontent in public, he stole his father's precious diamond.
innovation: n. a new idea, method, or invention改革, 创新
- The old programmer is always beset by the speed of innovation.
- He complained that there was not so much innovation in the exhibition.
- The official tends to buttress the technological innovation in this district.
tension: n. a nervous worried feeling that makes it impossible for you to relax ⇨ tense紧张
- In the end, I could not bear the tension among those officials.
- Despite tension between me and my wife, we went for a walk last Sunday. 
- The tensions bewteen those countries led to a lengthy war.
--------------------
label sb. sth.: 给某人贴上某物的标签
- About 2000 children who labeled themselves the defenders of the Christians made their way across the ChangJiang to NanJing.
- It is no use pretending that you are a knight by labeling yourself an unknown title.
- You needn't have labelled me an enemy just because I got a better salary than you.
assume political authority: 承担政治权力
- Now that the monarchy assumed political authority, the church couldn't insist on the exalted claim of the papal authority.
- The monarchy saw an opportunity to assume political authority under the papal control.
- Assuming political authority in his day, he decided to establish the Holy Roman Empire again.
lay the foundation for sb./sth.: 为某人/某物打下基础
- The purchase of the land laid the foundation for the king to assume political power. 
- The marriage between him and his wife laid the foundation for his career.
- The houses had been erected in the city, which laid the foundation for the renewal of population.
in one form or another: 以一种形式或另一种
- My father always helps me in one form or another
- Experiences in this adventure spured him to explore more in one form or another.
- I can't be bothered to fix up the bugs you made in one form or another.
in the challenge of sth.: 在...的挑战中
- He must be exercised in the challenge of financial crisis.
- The Comptroller was in the challenge of abduction by Asiatic nomads.
- In the challenge of warlike knights he has become a real warrior.
strike out on a path toward sp./sth.: 开辟通往某地的道路
- He won a prize for the best garden competition, for he struck out on a path toward his house.
- As the hill threatened these villages, people had to strike out a path toward the life in town.
- Working to his bone, he struck out on a path toward a new world record.
lay seeds of sth.: 种下某事的种子
- Cheating on her husband laid the seeds of animosities between their families.
- A series of disasters laid the seeds of the collapse of the great empire.
- His father who used to tell him stories laid the seeds of a great writer.
be dissent from sth.: 对某事持不同意见
- Dissent from the church, they laid seeds of animosities between each other.
- Dissent from his advice, I decided to perform experiments on my own.
- Dissent from his parents, he was left cleaning up the house by himself.
respond with sth.: 以...回复
- Although he received a warm welcome from the local people,
	 he responed with the swords and shields.
- He responded with a warm hug to welcome his wife at the station.
- The group of pop singers will respond with five performances during this time.
enforced conformity to sth.: 强制遵守某事
- She has enforced conformity to the rule that there was no parking area.
- When I was young, I had enforced conformity to the rules which my parents made.
- Everyone in the kingdom had been enforced conformity to the royal laws. 
supremacy over sth.: 凌驾于某物
- There is no supremacy over the royal laws in this kingdom.
- The king's claim of supremacy over the royal laws led to numerous attacks.
- The king's claim of supremacy over the church gave rise to a curious situation in this kingdom.
carry out sb's wishes: 实施某人的意愿
- He claimed to have carried out people's wishes.
- Carrying out his wishes, he struck out on a path toward establishing a great empire.
- Carrying out his wishes, his dream of dominating Europe came true.
creep into sp.: 悄悄进入某地
- The student crept into the office when the teacher fell asleep.
- I crept into my father's room to steal money from his locked drawer.
- I felt guilty after I crept into my father's room and stole his money.
a torrent of sth.: 潮水般的... 
- She ran into a torrent of troubles when she climbed the mountain.
- They are told to go home and receive a torrent of abuse.
- In spite of a torrent of abuse, the butcher succeeded in raising his two sons.
** summary
Over a period of 1000 to 1300, nobles continued to dominate the Medieval world.
Although they sometimes were treated condescendingly by popes,
	the kings developed a machinery of government
		that not only enabled them to challenge the exalted claim of papal power,
			but also made them dominate European politics in one form or another.
The High Middle Ages witnessed a new spiritual renewal which
	led to divergent paths:
		the revived papal leadership,
		the development of a centralized administrative system that buttressed papal authority,
		and the new dimensions of the religious life of the clergy and laity.
The renewal also gave rise to the crusading warriors
	who created an animosity between Christians and Muslims.
In the thirteenth century,
	friars gave witness to the spiritual growth
	and the growth of dissent from church teaching and practices
		to which the papal power responded with inquisitorial procedures.
At the same time,
	the exalted claims of papal power
		were gradually challenged by the rising power of monarchical authorities
			who could hire soldiers and officials because of the growth of trade and cities.
There was significant innovation in economic, political, cultural, and religious changes.
