#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 11 Mass burial and cremation of plague victims
#+begin_verse
As a result of their conquests in the thirteenth and fourteenth centuries,
	the Mongols assembled a vast empire stretching from Russia in the west to China in the east.
Mongol rule brought stability to the Eurasian trade routes;
	increased trade brought prosperity but also avenues for the spread of flea-infested rats
		that carried bubonic plague to both East Asia and Europe.
In the mid-fourteenth century,
	one of the most destructive natural disasters in history erupted---the Black Death.
One contemporary observer named Henry Knighton,
		a canon of Saint Mary-of-the-Meadow Abbey in Leicester, England,
	was simply overwhelmed by the magnitude of the catastrophe.
Knighton began his account of the great plague with these words:
	In this year [1348] and in the following one
		there was a general mortality of people throughout the whole world.
Few were left untouched;
	the plague struck even isolated monasteries:
		At Montpellier, there remained out of a hundred and forty friars only seven.
Knighton was also stunned by the economic and social consequences of the Black Death.
Prices dropped: And the price of everything was cheap, because of the fear of death;
	there were very few who took any care for their wealth, or for anything else.
Meanwhile, laborers were scarce, so their wages increased:
	In the following autumn,
		one could not hire a reaper at a lower wage than eight pence with food,
			or a mower at less than twelve pence with food.
Because of this, much grain rotted in the fields for lack of harvesting.
So many people died that some towns were deserted and some villages disappeared altogether:
	Many small villages and hamlets were completely deserted;
		there was not one house left in them, but all those who had lived in them were dead.
Some people thought the end of the world was at hand.

Plague was not the only disaster in the fourteenth century, however.
Signs of disintegration were everywhere:
	famine, economic depression, war, social upheaval, a rise in crime and violence,
	and a decline in the power of the universal Catholic church.
Periods of disintegration, however, are often fertile grounds for change and new developments.
Out of the dissolution of medieval civilization came a rebirth of culture
	that has come to be known as the Renaissance.
#+end_verse
** expression
vast [væst]: adj. extremely large SYN huge巨大的, 辽阔的
stable [ˈsteɪb(ə)l] stability: adj. n. steady and not likely to move or change OPP unstable ⇨ stability稳定的
route [rut]: n. a way between two places that buses, planes, ships etc regularly travel路线
avenue [ˈævəˌnu]: n. a possible way of achieving something方法, 途径
infested [ɪnˈfest]: adj. if insects, rats etc infest a place, there are a lot of them and they usually cause damage大批滋生的
plague [pleɪɡ]: n. v. a disease that causes death and spreads quickly to a large number of people瘟疫,折磨
contemporary [kənˈtɛmpəˌrɛri]: adj. belonging to the present time SYN modern当代的, 同时代的
untouched [ˌʌnˈtʌtʃt]: adj. not changed, damaged, or affected in any way未触及的, 未改变的
isolated [ˈaɪsəˌleɪtəd]: adj. an isolated building, village etc is far away from any others SYN remote隔离的,孤立的
scarce [skers]: adj. if something is scarce, there is not very much of it available缺乏的, 不足的
reaper [ˈripər]: n. 收割的人
mower [ˈmoʊr]: n. 割草的人
rot [rɑt]: v. to decay by a gradual natural process, or to make something do this(使)腐烂, (使)腐败
disintegrate [dɪsˈɪntɪˌɡreɪt] disintegration: v. n. to break up, or make something break up, into very small pieces(使)分解, (使)碎裂
famine [ˈfæmɪn]: n. a situation in which a large number of people have little or no food for a long time and many people die饥荒
universal [ˌjunɪˈvɜrs(ə)l]: adj. involving everyone in the world or in a particular group普遍的, 全体的
dissolution [ˌdɪsəˈluʃ(ə)n]: n. the process by which something gradually becomes weaker and disappears分解, 解散
--------------------
stretch from A to B: 从A延伸到B
be overwhelmed by sth.: 被某事淹没
the magnitude of sth.: 某事的巨大
be stunned by sth.: 被某事震惊
began sb's account of sth. with these words: 用这些话开始某人对某事的叙述
economic depression: 经济萧条
social upheaval: 社会动荡
be fertile grounds for sth.: 称为某物的沃土
** sentence
vast: adj. extremely large SYN huge巨大的, 辽阔的
- The east empire was said to possess a vast territory. 
- It is disturbing to think in the challenge of a vast empire.
- The vast empire was sacked by its neighbors, these Asiatic nomads.
stable stability: adj. n. steady and not likely to move or change OPP unstable ⇨ stability稳定的
- The rise in social status has brought stability to his family.
- The crusading knights brought stability to the Medieval world.
- I confirmed that turning to the pope would bring stability to our country and people. 
route: n. a way between two places that buses, planes, ships etc regularly travel路线
- I did not know the route to my hotel so I had to ask for helps.
- If you knew the route to our hotel, we wouldn't have had to ask for a lift.
- Not knowing the route to our hotel, we had lost in the forest and missed our reception.
avenue: n. a possible way of achieving something方法, 途径
- These sumggars may be the avenue for the spread of flea-infested rats.
- These visitors must be the avenue for the spread of strange pleagues. 
- Repeating 50 times is the avenue for the memory of this story.
infested: adj. if insects, rats etc infest a place, there are a lot of them and they usually cause damage大批滋生的
- My wife is alway complaining about infested mold found in our refrigeer.
- There are infested rats underneath the carpet.
- In fourteenth century, people suffering from Black Death got acclimated to infested rats in their houses.
plague: n. v. a disease that causes death and spreads quickly to a large number of people瘟疫,折磨
- Bad breath plagued him so much that he lost attraction to his girlfriend.
- The vicar spotted a plague erupting in the remote village.
- The village happened to erupt plague when a group of doctors were visiting it.
contemporary: adj. belonging to the present time SYN modern当代的, 同时代的
- It is disturbing to think that we don't have access to contemporary English in this country.
- He obviously could not tell the difference between contemporary music and jazz.
- The rapper responded with contemporary music to the brutal executions.
untouched: adj. not changed, damaged, or affected in any way未触及的, 未改变的
- Dissent from his family, he remains untouched.
- The crusading army sacked this city where only the monument remained untouched.
- Few remained untouched and other cities in the empire had bee conquered by Mongols.
isolated: adj. an isolated building, village etc is far away from any others SYN remote隔离的,孤立的
- He has been losting in an isolated island and missed his marriage with Lily.
- Pirates were said to bury treasure in isolated islands in the South pacific.
- The student is so isolated that he has to perform experiment by himself.
scarce: adj. if something is scarce, there is not very much of it available缺乏的, 不足的
- The labors in this farm is so scare that the boss instructed me to do manual works.
- In spite of scarce manual labors, the workers in the mine still get a lower wage.
- The food is so scarce that many children starve to death in a drought.
reaper: n. 收割的人
- 
- 
- 
mower: n. 割草的人
- 
- 
- 
rot: v. to decay by a gradual natural process, or to make something do this(使)腐烂, (使)腐败
- My neighbor blamed me for feeding his pig rotted apples.
- In my childhood, my grandmother often fed me rotted fruits like, apples, pineapples, and tomatoes.
- The moment the fruits are rotted, I will be allowed to have them.
disintegrate disintegration: v. n. to break up, or make something break up, into very small pieces(使)分解, (使)碎裂
- The disintegration of the republic gave rise to a trail of small countries in Europe.
- No one could account for the fact that the empire was disintegrated after its capital had been sacked.
- The president aimed for the disintegration of his enemy, a republic country in Asia.
famine: n. a situation in which a large number of people have little or no food for a long time and many people die饥荒
- Our people must have been exercised in the challenge of the famine.
- There was a serious famine in China which caused hundreds of millions of people starve to death.
- Because of lengthy famine, people in this country universally live in poverty.
universal universally: adj. involving everyone in the world or in a particular group普遍的, 全体的
- People suffering from famines are universally susceptible to be infected small pox.
- The exalted claim of papal power is increasingly challenged by the universal rise of the monarchical authorities. 
- These days our subsidiaries make universal progresses.
dissolution: n. the process by which something gradually becomes weaker and disappears分解, 解散
- The dissolution of his enterprise led to his loss of marriage.
- The dissolution of a great empire is often a fertile ground for many dynamic companies.
- At last, the dissolution of the scientists' team shocked our president.
--------------------
stretch from A to B: 从A延伸到B
- A large land strethcing from our town to next village is in the possession of the lord.
- Imagine my surprise when I was told that a field stretching from my foot to my father's belongs to our family.
- I am going to cross the plain stretching from China to Russia.
be overwhelmed by sth.: 被某事淹没
- Overwhelmed by mass coverages from the chaos, he was not able to figure out whether his wife was still alive.
- Overwhelmed by facts and statistics, the journalist developed a headache.
- I am susceptible to be overwhelmed by emotions.
the magnitude of sth.: 某事的巨大
- The maginitude of the monument inspired own in tens of thousands of tourists.
- The priest was shocked by the magnitude of refugees.
- The magnitude of the Children Crusade shocked the pope in Italy.
be stunned by sth.: 被某事震惊
- My father is stunned by me, who crept into his room to steal his money.
- I am stunned by my colleague who cheated on her husband.
- She must be stunned by the magnitude of the death people in the drought.
began sb's account of sth. with these words: 用这些话开始某人对某事的叙述
- She likes to begin her account of her story with these words at the reception.
- Everyone admires him for his great sense of humor and remembers that he always begins his account of his stories with these words.
- He changed his mind and began his account of the events with these words.
economic depression: 经济萧条
- Because of economic depression, our company didn't make a profit last year.
- Because of economic depression, prices universally dropped.
- Because of economic depression, we didn't get enough money to go on a vacation in Sanya.
social upheaval: 社会动荡
- In spite of social upheaval, the machinery of the government enabled the monarchs to assume political power.
- Our people are susceptible to be attcked by social upheaval.
- The Asiatic nomads pushed their way westward, which led to serious social upheaval in eastern Europe.
be fertile grounds for sth.: 称为某物的沃土
- The disintegration of the great empire has been fertile grounds for many kingdoms.
- The rise of cities, trade, and a money economy proved to be a fertile ground for the monarchical power.
- The plain must be a fertile grounds for infested rats.
** sentence2
vast: adj. extremely large SYN huge巨大的, 辽阔的
- The east empire was said to possess a vast territory. 
- It is disturbing to think of the challenge of a vast empire.
- The vast empire was sacked by its neighbors, these Asiatic nomads.
stable stability: adj. n. steady and not likely to move or change OPP unstable ⇨ stability稳定的
- The rise in social status has brought stability to his family.
- The crusading knights brought stability to the Medieval world.
- I confirmed that turning to the pope would bring stability to our country and people. 
route: n. a way between two places that buses, planes, ships etc regularly travel路线
- I did not know the route to my hotel so I had to ask for help.
- If you knew the route to our hotel, we wouldn't have had to ask for a lift.
- Not knowing the route to our hotel, we lost our way in the forest and missed our reception.
avenue: n. a possible way of achieving something方法, 途径
- These smugglers may be the avenue for the spread of flea-infested rats.
- These visitors must be the avenue for the spread of strange plagues. 
- Repeating 50 times is the avenue for the memory of this story.
infested: adj. if insects, rats etc infest a place, there are a lot of them and they usually cause damage大批滋生的
- My wife is always complaining about infested mold found in our refrigerator.
- There are infested rats underneath the carpet.
- In the fourteenth century, people suffering from the Black Death got acclimated to infested rats in their houses.
plague: n. v. a disease that causes death and spreads quickly to a large number of people瘟疫,折磨
- Bad breath plagued him so much that he lost attraction to his girlfriend.
- The vicar spotted a plague erupting in the remote village.
- The village happened to erupt a plague when a group of doctors were visiting it.
contemporary: adj. belonging to the present time SYN modern当代的, 同时代的
- It is disturbing to think that we don't have access to contemporary English in this country.
- He obviously could not tell the difference between contemporary music and jazz.
- The rapper responded with contemporary music to the brutal executions.
untouched: adj. not changed, damaged, or affected in any way未触及的, 未改变的
- Dissent from his family, he remains untouched.
- The crusading army sacked this city where only the monument remained untouched.
- Few remained untouched and other cities in the empire had been conquered by Mongols.
isolated: adj. an isolated building, village etc is far away from any others SYN remote隔离的,孤立的
- He has been lost on an isolated island and missed his marriage with Lily.
- Pirates were said to bury treasure in isolated islands in the South Pacific.
- The student is so isolated that he has to perform experiments by himself.
scarce: adj. if something is scarce, there is not very much of it available缺乏的, 不足的
- The laborers on this farm are so scarce that the boss instructed me to do manual work.
- In spite of scarce manual laborers, the workers in the mine still get a lower wage.
- The food is so scarce that many children starve to death in a drought.
reaper: n. 收割的人
- 
- 
- 
mower: n. 割草的人
- 
- 
- 
rot: v. to decay by a gradual natural process, or to make something do this(使)腐烂, (使)腐败
- My neighbor blamed me for feeding his pig rotted apples.
- In my childhood, my grandmother often fed me rotted fruits like apples, pineapples, and tomatoes.
- The moment the fruits are rotted, I will be allowed to have them.
disintegrate disintegration: v. n. to break up, or make something break up, into very small pieces(使)分解, (使)碎裂
- The disintegration of the republic gave rise to a trail of small countries in Europe.
- No one could account for the fact that the empire was disintegrated after its capital had been sacked.
- The president aimed for the disintegration of his enemy, a republic country in Asia.
famine: n. a situation in which a large number of people have little or no food for a long time and many people die饥荒
- Our people must have been exercised in the challenge of the famine.
- There was a serious famine in China which caused hundreds of millions of people to starve to death.
- Because of lengthy famine, people in this country universally live in poverty.
universal universally: adj. involving everyone in the world or in a particular group普遍的, 全体的
- People suffering from famines are universally susceptible to being infected with smallpox.
- The exalted claim of papal power is increasingly challenged by the universal rise of the monarchical authorities. 
- These days our subsidiaries make universal progress.
dissolution: n. the process by which something gradually becomes weaker and disappears分解, 解散
- The dissolution of his enterprise led to his loss of marriage.
- The dissolution of a great empire is often a fertile ground for many dynamic companies.
- At last, the dissolution of the scientists' team shocked our president.
--------------------
stretch from A to B: 从A延伸到B
- A large land stretching from our town to the next village is in the possession of the lord.
- Imagine my surprise when I was told that a field stretching from my foot to my father's belongs to our family.
- I am going to cross the plain stretching from China to Russia.
be overwhelmed by sth.: 被某事淹没
- Overwhelmed by mass coverage from the chaos, he was not able to figure out whether his wife was still alive.
- Overwhelmed by facts and statistics, the journalist developed a headache.
- I am susceptible to being overwhelmed by emotions.
the magnitude of sth.: 某事的巨大
- The magnitude of the monument inspired own in tens of thousands of tourists.
- The priest was shocked by the magnitude of refugees.
- The magnitude of the Children's Crusade shocked the pope in Italy.
be stunned by sth.: 被某事震惊
- My father is stunned by me, who crept into his room to steal his money.
- I am stunned by my colleague who cheated on her husband.
- She must be stunned by the magnitude of the deaths in the drought.
began sb's account of sth. with these words: 用这些话开始某人对某事的叙述
- She likes to begin her account of her story with these words at the reception.
- Everyone admires him for his great sense of humor and remembers that he always begins his account of his stories with these words.
- He changed his mind and began his account of the events with these words.
economic depression: 经济萧条
- Because of economic depression, our company didn't make a profit last year.
- Because of economic depression, prices universally dropped.
- Because of economic depression, we didn't get enough money to go on a vacation in Sanya.
social upheaval: 社会动荡
- In spite of social upheaval, the machinery of the government enabled the monarchs to assume political power.
- Our people are susceptible to being attacked by social upheaval.
- The Asiatic nomads pushed their way westward, which led to serious social upheaval in Eastern Europe.
be fertile grounds for sth.: 称为某物的沃土
- The disintegration of the great empire has been a fertile ground for many kingdoms.
- The rise of cities, trade, and a money economy proved to be a fertile ground for the monarchical power.
- The plain must be a fertile ground for infested rats.
** summary
Mogols rule brought prosperity but also flea-infested rats that carried bubonic pleagues.
According to a contemporary observer's words,
	there was a general mortality of people throughout the world over.
Few remained untouched, the plagues even attacked isolated monasteries.
People who had lived in some villages and hamlets were all dead.
Prices dropped, for no one took care of their wealth.
Because of scarce laborors, the laborors became so expensive that grain was rotted in the fields.
Some people thought the end of the world was at hand.
Signs of disintegration were everywhere:
	famine, economic depression, war, social upheaval, a rise in crime and violence,
	and a decline in the power of the univerisal Catholic church.
However, out of disolutions of the Medieval Civilization came a rebirth of culture
	known as the Renaissance.
** summary2
Mogols' rule brought prosperity but also flea-infested rats that carried bubonic plagues.
According to a contemporary observer's words,
	there was a general mortality of people throughout the whole world.
Few remained untouched, the plague even attacked isolated monasteries.
People who had lived in some villages and hamlets were all dead.
Prices dropped, for no one took care of their wealth.
Because of scarce laborers, the laborers became so expensive that grain was rotted in the fields.
Some people thought the end of the world was at hand.
Signs of disintegration were everywhere:
	famine, economic depression, war, social upheaval, a rise in crime and violence,
	and a decline in the power of the universal Catholic church.
However, out of the dissolution of the Medieval Civilization came a rebirth of culture
	known as the Renaissance.

