#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 11 The later Middle Ages, Crisis and Disintegration in the fourteenth century
#+begin_verse
European civilization developed many of its fundamental features
	in the eleventh, twelfth, and thirteenth centuries.
Territorial states, parliaments,
		capitalist trade and industry, banks, cities, and vernacular literatures
	were all products of that fertile period.
During the same time, the Catholic church under the direction of the papacy reached its apogee.
European society in the fourteenth century, however,
	was challenged by an overwhelming number of crises.
Devastating plague, decline in trade and industry, bank failures,
	peasant revolts pitting lower classes against the upper classes,
	seemingly constant warfare,
	aristocratic factional conflict that undermined political stability,
	the absence of the popes from Rome,
	and even the spectacle of two popes condemning each other as the Antichrist
	all seemed to overpower Europeans in this 'calamitous century.'
Not surprisingly,
	much of the art of the period depicted the Four Horsemen of the Apocalypse
		described in the New Testament book of Revelation: Death, Famine, Pestilence, and War.
To some people, no doubt, the last days of the world seemed to be at hand.

The new European society, however, proved remarkably resilient.
Periods of crisis usually give rise to new ideas and new practices.
Intellectuals of the period saw themselves
	as standing on the threshold of a new age
		and a rebirth of the best features of Classical civilization,
			an era widely referred to as the Renaissance.
#+end_verse
** expression
fundamental [ˌfʌndəˈment(ə)l]: adj. relating to the most basic and important parts of something基础的, 基本的
feature [ˈfitʃər]: n. a part of something that you notice because it seems important, interesting, or typical特征
capitalist [ˈkæpɪt(ə)lɪst]: adj. using or supporting capitalism ⇨ communist, socialist资本主义的
industry [ˈɪndəstri]: n. businesses that produce a particular type of thing or provide a particular service工业, 产业
vernacular [vərˈnækjələr]: adj. a form of a language that ordinary people use, especially one that is not the official language方言的
fertile [ˈfɜrt(ə)l]: adj. fertile land or soil is able to produce good crops肥沃的, 富饶的
revolt [rɪˈvoʊlt]: n. a refusal to accept someone’s authority or obey rules or laws SYN rebellion反抗, 起义
constant [ˈkɑnstənt]: adj. happening regularly or all the time SYN continual持续的
warfare [ˈwɔrˌfer]: n. the activity of fighting in a war – used especially when talking about particular methods of fighting战争, 作战, 冲突, 竞争
faction [ˈfækʃ(ə)n] factional: n.adj. a small group of people within a larger group, who have different ideas from the other members, and who try to get their own ideas accepted派别
spectacle [ˈspektək(ə)l]: n. an unusual or interesting thing or situation that you see or notice – used especially in order to show disapproval奇观
overpower [ˌoʊvərˈpaʊr]: v. to take control of someone physically because you are stronger制服, 压倒
calamity [kəˈlæməti] calamitous: n.adj. a terrible and unexpected event that causes a lot of damage or suffering SYN disaster灾难
revelation [ˌrevəˈleɪʃ(ə)n]: n. a surprising fact about someone or something that was previously secret and is now made known揭露
pestilence [ˈpestɪləns]: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
resilient [rɪˈzɪljənt]: adj. able to become strong, happy, or successful again after a difficult situation or event ⇨ tough有弹性的
intellectual [ˌɪnt(ə)lˈektʃuəl]: n.adj. an intelligent well-educated person who spends time thinking about complicated ideas and discussing them ⇨ academic知识分子
threshold [ˈθreʃˌhoʊld]: n. at the beginning of a new and important event or development SYN brink开始, 开端
--------------------
reach sb's apogee: 到达顶点
be challenged by sth./sb.: 被某人/某事物挑战
pit A against B: 使A与B竞争
condemn A as B: 谴责A为B
see sb. as doing sth.: 认为某人在做某事
** sentence
fundamental: adj. relating to the most basic and important parts of something基础的, 基本的
- People in the plague even didn't possess the fundamental right.
- Mongols' rule brought prosperity and the fundamental right to the local people.
- You have broken the fundamental law in this country while you were committed a murder.
feature: n. a part of something that you notice because it seems important, interesting, or typical特征
- No one could account for the features of a heart in the Medieval Ages.
- Although he spotted him stealing diamonds, he could not describe the features of the thief.
- I realized that it was my father whose feature of voice was so observant.
capitalist: adj. using or supporting capitalism ⇨ communist, socialist资本主义的
- The country which some scientist proved it socialist turns out to be capitalist.
- The monarchs were reluctant to bargain with these capitalist country.
- He began the account of his story with these words: there was a general mortality of people in the capitalist country in 1947.
industry: n. businesses that produce a particular type of thing or provide a particular service工业, 产业
- The silk industry was said to move to Jiaxing District.
- With the industry coming the increase of trade and cities, the local lord began to assume political power.
- He dreams of working in the computer industry and leading a happy life.
vernacular: adj. a form of a language that ordinary people use, especially one that is not the official language方言的
- Don't speak vernacular literature in the class, which will make a spectacle of yourself.
- At a reception, his vernacular story rewarded him with a burst of laughter.
- In my youth, I was eager to pile up vernacular stories in the library.
fertile: adj. fertile land or soil is able to produce good crops肥沃的, 富饶的
- The soil is so fertile that there are harvesting three times a year.
- The soil proved fertile, for the grain grew pretty well even in a drought.
- The fertile soil of the river bank gave rise to the habitat of a special type of birds.
revolt: n. a refusal to accept someone’s authority or obey rules or laws SYN rebellion反抗, 起义
- The authorities took the revolt seriously and executed their leaders.
- No matter how serious the revolt was, the rights they won were always short-life. 
- It occurs to the king that a peasant revolt was solved by a band of knights.
constant: adj. happening regularly or all the time SYN continual持续的
- I must prevent myself from his constant interruption while I am doing home work. 
- The constant war exhausted people in this state a great deal.
- I wish the rain would not be constant.
warfare: n. the activity of fighting in a war – used especially when talking about particular methods of fighting战争, 作战, 冲突, 竞争
- There must have been a gang warfare for who should ask local people for protection money.
- Once upon a time, there was a gang warefare in a remote country.
- As a result of theirs warfare in the thirteenth century, Mongols assembled a vast empire stretching from Russia in the west to China in the east.
faction factional: n.adj. a small group of people within a larger group, who have different ideas from the other members, and who try to get their own ideas accepted派别
- You shouldn't have quarreled with any factions when you took part in a new party.
- The conflicts of factions led to the dissolution of the scientists' team.
- The president seemed to be tiref of the conflicts of factions in the party.
spectacle: n. an unusual or interesting thing or situation that you see or notice – used especially in order to show disapproval奇观,闹剧
- The abbot piled up murderers to stand trail, which turned out to be a spectable.
- It is no use pretending that you haven't played truent from school, which has been a spectacle in our school.
- It reminded him of a spectacle of girls who published each other's naked pictures in the press.
overpower: v. to take control of someone physically because you are stronger制服, 压倒
- Don't try to overpower this barking dog, it's a waste of time.
- You must give up overpowering the Russia which is too big to get under control. 
- As soon as him arrived on the scene, the police drove into the car to overpower the murderer.
calamity calamitous: n.adj. a terrible and unexpected event that causes a lot of damage or suffering SYN disaster灾难
- The spokesman exclaimed that China was calamitous because of constant natural disasters like floods, earthquakes, and snow storms.
- The fortune-teller has a bad reputation for predicting calamities in our town.
- Because of serious constant calamities, some people were wondering whether the end of the world was at hand.
revelation: n. a surprising fact about someone or something that was previously secret and is now made known揭露
- The officials blamed the journalist on the revelation of a secret scandal of our prime minister.
- An article on the revelation of president's affairs has been published in the press.
- The observer was stunned by the revelation of a spectacle of two presidents.
pestilence: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
- Unfortunately, the pestilence also attacked isolated villages and halmets.
- Instead of getting away from the city, the doctor decided to research the pestilence on the scene.
- It was said that the mistakes the experiments made caused this constant pestilence.
resilient: adj. able to become strong, happy, or successful again after a difficult situation or event ⇨ tough有弹性的
- He was so resilient that he finished his homework in such a hurry.
- If you didn't hurry to do everything, you would be more resilient.
- The monarchs proved more resilient than those knights who almost lost their power after a pestilence.
intellectual: n.adj. an intelligent well-educated person who spends time thinking about complicated ideas and discussing them ⇨ academic知识分子
- The intellectuals should be responsible for this accident, for they have taken charge of the laboratory.
- The president tends to reprimand these intellectuals for their relevation of this experiment.
- These intellectuals in villages had a good reputation for initiating knownledge.
threshold: n. at the beginning of a new and important event or development SYN brink开始, 开端
- This warfare turns out to be the threshold of the empire's dissolution.
- The initiated Crusade is on the threshold of the civil war in Europe.
- A bad reputation is often the threshold of the collapse of a big company.
--------------------
reach sb's apogee: 到达顶点
- When the explorer flew over the South Pole, he and his men have reached their apogee.
- The Mongols reached their apogee and assembled a vast empire stretching from China to Russia.
- The gunpowder enabled them to reach their apogee and conquered the whole Europe.
be challenged by sth./sb.: 被某人/某事物挑战
- I am afraid you will be challenged by numerous warlike knights.
- This warlke knight began to be challenged by the local authorities.
- The silk industry is being challenged by the higher wages of laborers.
pit A against B: 使A与B竞争
- The desire for the champion pitted him against his rivals in the Olympics Games.
- The girl he had a major crush on pitted him against her husband.
- The low social status pitted him against some immigrants.
condemn A as B: 谴责A为B
- It is no use condemn your enemies as unhonest pigs.
- As he didn't catch his flight, he condemned the flight company as a robber.
- The kings condemned those rebellious infrantries as the source of disaster.
see sb. as doing sth.: 认为某人在做某事
- It is no use pretending that you saw yourself as learning.
- He saw himself as defending against evils.
- The queen saw herself as assumming political power.
** sentence2
fundamental: adj. relating to the most basic and important parts of something基础的, 基本的
- People in the plague didn't even possess the fundamental right.
- Mongol rule brought prosperity and fundamental rights to the local people.
- You have broken the fundamental law in this country while you were committing a murder.
feature: n. a part of something that you notice because it seems important, interesting, or typical特征
- No one could account for the features of a heart in the Medieval Ages.
- Although he spotted him stealing diamonds, he could not describe the features of the thief.
- I realized that it was my father whose feature of voice was so observant.
capitalist: adj. using or supporting capitalism ⇨ communist, socialist资本主义的
- The country that some scientists proved socialist turns out to be capitalist.
- The monarchs were reluctant to bargain with these capitalist countries.
- He began the account of his story with these words: there was a general mortality of people in the capitalist country in 1947.
industry: n. businesses that produce a particular type of thing or provide a particular service工业, 产业
- The silk industry was said to be moving to Jiaxing District.
- With the industry came the increase of trade and cities, and the local lord began to assume political power.
- He dreams of working in the computer industry and leading a happy life.
vernacular: adj. a form of a language that ordinary people use, especially one that is not the official language方言的
- Don't speak vernacular literature in the class, which will make a spectacle of yourself.
- At a reception, his vernacular story rewarded him with a burst of laughter.
- In my youth, I was eager to pile up vernacular stories in the library.
fertile: adj. fertile land or soil is able to produce good crops肥沃的, 富饶的
- The soil is so fertile that there are three harvestings a year.
- The soil proved fertile, for the grain grew pretty well even in a drought.
- The fertile soil of the river bank gave rise to the habitat of a special type of bird.
revolt: n. a refusal to accept someone’s authority or obey rules or laws SYN rebellion反抗, 起义
- The authorities took the revolt seriously and executed their leaders.
- No matter how serious the revolt was, the rights they won were always short-lived. 
- It occurs to the king that a peasant revolt was solved by a band of knights.
constant: adj. happening regularly or all the time SYN continual持续的
- I must prevent myself from his constant interruption while I am doing homework. 
- The constant war exhausted people in this state a great deal.
- I wish the rain would not be constant.
warfare: n. the activity of fighting in a war – used especially when talking about particular methods of fighting战争, 作战, 冲突, 竞争
- There must have been gang warfare for who should ask local people for protection money.
- Once upon a time, there was gang warfare in a remote country.
- As a result of their warfare in the thirteenth century, Mongols assembled a vast empire stretching from Russia in the west to China in the east.
faction factional: n.adj. a small group of people within a larger group, who have different ideas from the other members, and who try to get their own ideas accepted派别
- You shouldn't have quarreled with any factions when you took part in a new party.
- The conflicts of factions led to the dissolution of the scientists' team.
- The president seemed to be tired of the conflicts of factions in the party.
spectacle: n. an unusual or interesting thing or situation that you see or notice – used especially in order to show disapproval奇观,闹剧
- The abbot piled up murderers to stand trials, which turned out to be a spectacle.
- It is no use pretending that you haven't played truant from school, which has been a spectacle in our school.
- It reminded him of a spectacle of girls who published each other's naked pictures in the press.
overpower: v. to take control of someone physically because you are stronger制服, 压倒
- Don't try to overpower this barking dog, it's a waste of time.
- You must give up overpowering Russia which is too big to get under control. 
- As soon as he arrived on the scene, the police drove into the car to overpower the murderer.
calamity calamitous: n.adj. a terrible and unexpected event that causes a lot of damage or suffering SYN disaster灾难
- The spokesman exclaimed that China was calamitous because of constant natural disasters like floods, earthquakes, and snow storms.
- The fortune-teller has a bad reputation for predicting calamities in our town.
- Because of serious constant calamities, some people were wondering whether the end of the world was at hand.
revelation: n. a surprising fact about someone or something that was previously secret and is now made known揭露
- The officials blamed the journalist on the revelation of a secret scandal of our prime minister.
- An article on the revelation of the president's affairs has been published in the press.
- The observer was stunned by the revelation of a spectacle of two presidents.
pestilence: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
- Unfortunately, the pestilence also attacked isolated villages and hamlets.
- Instead of getting away from the city, the doctor decided to research the pestilence on the scene.
- It was said that the mistakes the experiments made caused this constant pestilence.
resilient: adj. able to become strong, happy, or successful again after a difficult situation or event ⇨ tough有弹性的
- He was so resilient that he finished his homework in such a hurry.
- If you didn't hurry to do everything, you would be more resilient.
- The monarchs proved more resilient than those knights who almost lost their power after a pestilence.
intellectual: n.adj. an intelligent well-educated person who spends time thinking about complicated ideas and discussing them ⇨ academic知识分子
- The intellectuals should be responsible for this accident, for they have taken charge of the laboratory.
- The president tends to reprimand these intellectuals for their revelation of this experiment.
- These intellectuals in villages had a good reputation for initiating knowledge.
threshold: n. at the beginning of a new and important event or development SYN brink开始, 开端
- This warfare turns out to be the threshold of the empire's dissolution.
- The initiated Crusade is on the threshold of the civil war in Europe.
- A bad reputation is often the threshold of the collapse of a big company.
--------------------
reach sb's apogee: 到达顶点
- When the explorer flew over the South Pole, he and his men reached their apogee.
- The Mongols reached their apogee and assembled a vast empire stretching from China to Russia.
- The gunpowder enabled them to reach their apogee and conquer the whole of Europe.
be challenged by sth./sb.: 被某人/某事物挑战
- I am afraid you will be challenged by numerous warlike knights.
- This warlike knight began to be challenged by the local authorities.
- The silk industry is being challenged by the higher wages of laborers.
pit A against B: 使A与B竞争
- The desire for the champion pitted him against his rivals in the Olympic Games.
- The girl he had a major crush on pitted him against her husband.
- The low social status pitted him against some immigrants.
condemn A as B: 谴责A为B
- It is no use condemning your enemies as dishonest pigs.
- As he didn't catch his flight, he condemned the flight company as a robber.
- The kings condemned those rebellious infantries as the source of disaster.
see sb. as doing sth.: 认为某人在做某事
- It is no use pretending that you see yourself as learning.
- He saw himself as defending against evils.
- The queen saw herself as assuming political power.
** summary
European Civilization produced terrotorial states,
	captilist trade and industry, banks, cities and vernacular literatures
	in the eleventh century, twelfth century, and thirteen century.
At the same time, the Catholic church reached its height under the direction of the papacy.
Subsequently, in the fourteenth century,
	devastating plagues, decline in trade and industry, peasant revolts, constant warfare,
	aristocratical factional conflicts,
	the absence of the popes from Rome,
	a spectacle of two popes condemning each other as the Antichrist
	seemingly overpowered Europeans.
The art of that period depicted it as the end of the world which some people thought to be at hand.
However, the European Civilization proved resilient,
	for those crises gave rise to new ideas, pratices, and an era,
		which is known as the Renaissance.
** summary2
European Civilization produced territorial states,
	capitalist trade and industry, banks, cities, and vernacular literature
	in the eleventh , twelfth , and thirteenth century.
At the same time, the Catholic church reached its height under the direction of the papacy.
Subsequently, in the fourteenth century,
	devastating plagues, decline in trade and industry, peasant revolts, constant warfare,
	aristocratical factional conflicts,
	the absence of the popes from Rome,
	a spectacle of two popes condemning each other as the Antichrist
	seemingly overpowered Europeans.
The art of that period depicted it as the end of the world which some people thought to be at hand.
However, the European Civilization proved resilient,
	for those crises gave rise to new ideas, practices, and an era,
		which is known as the Renaissance.

