#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 12 Recovery and rebirth, the Renaissance
#+begin_verse
The Renaissance was a period of transition
	that extended most of the economic, political, and social trends
		that had begun in the High Middle Ages.
It was also a movement
	in which intellectuals and artists proclaimed a new vision of humankind
		and raised fundamental questions about the value and importance of the individual.
Of course, intellectuals and artists wrote and painted for the upper classes,
	and the brilliant intellectual, cultural, and artistic accomplishments of the Renaissance
		were really products of and for the elite.
The ideas of the Renaissance did not have a broad base among the masses of the people.
As Lorenzo the Magnificent, ruler of Florence, once commented,
	'Only men of noble birth can obtain perfection.
	The poor, who work with their hands and have no time to cultivate their minds,
		are incapable of it.'
		
The Renaissance did, however, raise new questions about medieval traditions.
In criticizing current religious practices,
	the humanists raised fundamental issues about the Catholic church,
		which was still an influential institution.
As we shall see in the next chapter,
	the intellectual revolution of the fifteenth century gave way to a religious renaissance
		that touched the lives of people, including the masses, in new and profound ways.
After the Reformation,
	Europe would never again be the unified Christian commonwealth it once believed it was.
#+end_verse
** expression
transition [trænˈzɪʃ(ə)n]: n. formal when something changes from one form or state to another转变,过渡
extend [ɪkˈstend]: v. to continue for a longer period of time, or to make something last longer延伸
trend [trend]: n. a general tendency in the way a situation is changing or developing倾向, 趋势
proclaim [prəˈkleɪm]: v. to say publicly or officially that something important is true or exists宣布, 声明
humankind [ˌhjumənˈkaɪnd]: n. people in general SYN mankind人类
accomplishment [əˈkʌmplɪʃmənt]: n. something successful or impressive that is achieved after a lot of effort and hard work SYN achievement成就
elite [ɪˈlit]: n. a group of people who have a lot of power and influence because they have money, knowledge, or special skills精英
broad [brɔd]: adj. WIDE a road, river, or part of someone’s body etc that is broad is wide OPP narrow ⇨ adth宽的, 阔的
mass [mæs]: n. a large crowd群众
obtain [əbˈteɪn]: v. to get something that you want, especially through your own effort, skill, or work SYN get获得, 得到
cultivate [ˈkʌltɪˌveɪt]: v. to work hard to develop a particular skill, attitude, or quality培养, 耕作
influential [ˌɪnfluˈenʃəl]: adj. having a lot of influence and therefore changing the way people think and behave有影响的, 有势力的
institution [ˌɪnstɪˈtuʃ(ə)n]: n. an important system of organization in society that has existed for a long time公共机构, 协会, 制度
revolution [ˌrevəˈluʃ(ə)n]: n. a time when people change a ruler or political system by using force or violence ⇨ revolt, rebellion革命
profound [prəˈfaʊnd]: adj. having a strong influence or effect深刻的, 意义深远的
reformation [ˌrefərˈmeɪʃ(ə)n]: n. formal when something is completely changed in order to improve it改革, 革新
unify [ˈjunɪˌfaɪ] unified: v.adj. if you unify two or more parts or things, or if they unify, they are combined to make a single unit SYN unite OPP divide ⇨ unification统一
commonwealth [ˈkɑmənˌwelθ]: n. the official title of some countries made up of a group of states联邦
--------------------
a new vision of sth.: 对某事的新视野/认识
raise fundamental questions/issues about sth.: 提出关于某事的基本问题
upper classes: 上层阶级
with sb's hands: 用某人双手
be incapable of sth./doing sth.: 无法做某事
have no time to do sth.: 没有时间去做某事
give way to sth.: 让位于某事;被某事取代
** sentence
transition: n. formal when something changes from one form or state to another转变,过渡
- The period of transition gave rise to curious situations, as it did in the case of Mr. Leo, a peasant.
- The Asiatic nomads may sack the city which is in transition.
- While the European society was in transition, these Asiatic nomads pushed their way westward through the plain.
extend: v. to continue for a longer period of time, or to make something last longer延伸
- Exasparated by his brutal behaviors, his boss refused to extend the deadline of the task.
- The stick should be extended so that I could hang clothes by myself.
- His power was extended after his triumph of the civil war.
trend: n. a general tendency in the way a situation is changing or developing倾向, 趋势
- Lately there was a trend towards lower wages and losing jobs in transition.
- A trend towards the collapse of this vampire gave rise to some independent cities.
- Although he has worked to his bone, he has a trend towards giving up studying English.
proclaim: v. to say publicly or officially that something important is true or exists宣布, 声明
- The spokeswoman proclaimed that as soon as it was indentified, we would compensate for your loss of money.
- A fisherman proclaimed that he had lost his money while he was on his way to ticket office.
- The pope proclaimed that the German king would be crowned by him at the coronation.
humankind: n. people in general SYN mankind人类
- He never dreams of becoming an expert at explaining the actions of humankind.
- He published an article on the value and importance of humankind.
- No one thinks that this seeming disaster turns out to be the fortune of humankind.
accomplishment: n. something successful or impressive that is achieved after a lot of effort and hard work SYN achievement成就
- The king proclaimed that he shared his accomplishments with all of his subjects.  
- It is impossible for me to be jealous of his accomplishments.
- Jealous of his colleague's accomplishments, the artist had his colleague thrown down from the scaffolding.
elite: n. a group of people who have a lot of power and influence because they have money, knowledge, or special skills精华, 精锐, 中坚分子
- The artist's temperament forbid him to work for elites.
- The elite explained his experience in the war to his lord with modest.
- The elite never loses his temper and behaves in public with modest.
broad: adj. WIDE a road, river, or part of someone’s body etc that is broad is wide OPP narrow ⇨ adth宽的, 阔的
- The broad river used to be flooded with bodies during the war.
- He succeeded in making a broad path towards his house.
- Under the new Comptroller's control, the river becomes broader and cleaner.
mass: n. a large crowd群众
- The mass began to gather round and held up the traffic.
- The leader prevented the mass from being sold into slavery in Africa.
- Thanks to the wisdom of the mass, we built the tremendous suspension bridge in two years.
obtain: v. to get something that you want, especially through your own effort, skill, or work SYN get获得, 得到
- Obtaining good grades won't make us as happy as we think.
- He obtained skills in high school so that he could catch fishes with bare hands.
- He obtained the money which I had lost on my way home.
cultivate: v. to work hard to develop a particular skill, attitude, or quality培养, 耕作
- He is determined to cultivate his child's swimming skills.
- Failing to cultivate the crops in the field, the farmer began to get drunk every day.
- My leader told me that he would cultivate me so that I could undertake the project on my own.
influential: adj. having a lot of influence and therefore changing the way people think and behave有影响的, 有势力的
- The vast empire was so influential that many historians admire it.
- The man is so influential that he has a large circle of close friends.
- The invention of clocks proved influential, it developed Europeans' habit of doing stuff on time.
institution: n. an important system of organization in society that has existed for a long time公共机构, 协会, 制度
- My boss went out of his way to establish an institution that checks the fire extinguisher of enterprises on a daily basis.
- He pestered the institution on a regular basis about when the library would be elected in the prison.
- The king established a law prohibiting the institution which had broken his monarchical law regularly.
revolution: n. a time when people change a ruler or political system by using force or violence ⇨ revolt, rebellion革命
- The revelution in the thirteenth century no doubt continued into the fourteethth.
- There were elements of techonology which made the fourteenth century a period of revolution.
- A revolution erupting in China was so influential that it captured the attentions of people all over the world.
profound: adj. having a strong influence or effect深刻的, 意义深远的
- Sacrificing money for land exerted a profound influence on this monarchical state.
- The Black Death erupted in Europe through the flea-infested rats which was brought from China, which exerted a profound influence on Western Civilization. 
- His painting of the ceiling of the Sistine Chapel exerted a profound influence on the following arts.
reformation: n. formal when something is completely changed in order to improve it改革, 革新
- Even though the reformation turned out to be a failure, its profound influence inspired awe in many historians. 
- The reformation benifited many peasant who were free from fief which was dominated by old aristocracies.
- The reformation was expected to restor the warriors to new glory.
unify unified: v.adj. if you unify two or more parts or things, or if they unify, they are combined to make a single unit SYN unite OPP divide ⇨ unification统一
- Monogols unified a vast empire stretching from Russia in the west to China in the east.
- The unified territorial empire soon taught the Pope a lesson.
- The unified territorial empire couldn't bear the papal supremacy over secular authorties.
commonwealth: n. the official title of some countries made up of a group of states联邦
- At last, the pope unified a vast Christian commonwealth in Europe.
- The commonwealth constitutes many territorial states in the peninsula.
- The meeting of the commonwealth will be held at the promontory of the island.
--------------------
a new vision of sth.: 对某事的新视野/认识
- The new vision of math inspired awe in these intellectuals.
- He would not be satisfied until he got a new vision of the painting.
- A new vision of gunpower gave rise to a profound reformation in warfare.
raise fundamental questions/issues about sth.: 提出关于某事的基本问题
- My wife raised a fundamental question about who should pay for the hotel when we went on a date for the first time.
- Needless to say, he raised a fundamental question about the protection money which was provided by these merchants.
- The superior raised fundamental issues about the bugs I made.
upper classes: 上层阶级
- She managed to marry to a upper class.
- The man who has worked for our company for over 5 years turns out to be a long-lost child of a upper class in our town.
- The upper classes hired the great arist to paint the ceiling of the chapel.
with sb's hands: 用某人双手
- Lee said he would make your dream come ture with his hands.
- I hate to work with my hands in the field on summer holiday.
- I was instructed to wash my wife's underwears with my hands.
be incapable of sth./doing sth.: 无法做某事
- Our manager who claimed he was an accomplished programmer turns out to be incapable of programming.
- Everyone laughed at him who was incapable of programming.
- I am incapable of programming with my hands, so I quit.
have no time to do sth.: 没有时间去做某事
- In spite of graduating from school, my sister still has no time to babysit our child.
- We have no time to cultivate your English skills which cost so many time.
- I have no time to listen to your awful stories.
give way to sth.: 让位于某事;被某事取代
- The candle must give way to electrical light in my house.
- Our dog gave way to our cat which would never bark at passers-by.
- The complaints gave way to admiration, for it solved my problem on time.
** sentence2
transition: n. formal when something changes from one form or state to another转变,过渡
- The period of transition gave rise to curious situations, as it did in the case of Mr. Leo, a peasant.
- The Asiatic nomads may sack the city which is in transition.
- While the European society was in transition, these Asiatic nomads pushed their way westward through the plain.
extend: v. to continue for a longer period of time, or to make something last longer延伸
- Exasperated by his brutal behaviors, his boss refused to extend the deadline of the task.
- The stick should be extended so that I can hang clothes by myself.
- His power was extended after his triumph in the civil war.
trend: n. a general tendency in the way a situation is changing or developing倾向, 趋势
- Lately, there has been a trend towards lower wages and job loss in transition.
- A trend towards the collapse of this vampire gave rise to some independent cities.
- Although he has worked to his bone, he has a trend towards giving up studying English.
proclaim: v. to say publicly or officially that something important is true or exists宣布, 声明
- The spokeswoman proclaimed that as soon as it was identified, we would compensate for your loss of money.
- A fisherman proclaimed that he had lost his money while he was on his way to a ticket office.
- The pope proclaimed that the German king would be crowned by him at the coronation.
humankind: n. people in general SYN mankind人类
- He never dreams of becoming an expert at explaining the actions of humankind.
- He published an article on the value and importance of humankind.
- No one thinks that this seeming disaster turns out to be the fortune of humankind.
accomplishment: n. something successful or impressive that is achieved after a lot of effort and hard work SYN achievement成就
- The king proclaimed that he shared his accomplishments with all his subjects.  
- It is impossible for me to be jealous of his accomplishments.
- Jealous of his colleague's accomplishments, the artist had his colleague thrown down from the scaffolding.
elite: n. a group of people who have a lot of power and influence because they have money, knowledge, or special skills精华, 精锐, 中坚分子
- The artist's temperament forbids him to work for elites.
- The elite explained his experience in the war to his lord with modesty.
- The elite never loses his temper and behaves in public with modesty.
broad: adj. WIDE a road, river, or part of someone’s body etc that is broad is wide OPP narrow ⇨ adth宽的, 阔的
- The broad river used to be flooded with bodies during the war.
- He succeeded in making a broad path towards his house.
- Under the new Comptroller's control, the river becomes broader and cleaner.
mass: n. a large crowd群众
- The masses began to gather around and held up the traffic.
- The leader prevented the masses from being sold into slavery in Africa.
- Thanks to the wisdom of the masses, we built the tremendous suspension bridge in two years.
obtain: v. to get something that you want, especially through your own effort, skill, or work SYN get获得, 得到
- Obtaining good grades won't make us as happy as we think.
- He obtained skills in high school so that he could catch fish with bare hands.
- He obtained the money which I had lost on my way home.
cultivate: v. to work hard to develop a particular skill, attitude, or quality培养, 耕作
- He is determined to cultivate his child's swimming skills.
- Failing to cultivate the crops in the field, the farmer began to get drunk every day.
- My leader told me that he would cultivate me so that I could undertake the project on my own.
influential: adj. having a lot of influence and therefore changing the way people think and behave有影响的, 有势力的
- The vast empire was so influential that many historians admire it.
- The man is so influential that he has a large circle of close friends.
- The invention of clocks proved influential, it developed Europeans' habit of doing stuff on time.
institution: n. an important system of organization in society that has existed for a long time公共机构, 协会, 制度
- My boss went out of his way to establish an institution that checks the fire extinguisher of enterprises on a daily basis.
- He pestered the institution on a regular basis about when the library would be elected in the prison.
- The king established a law prohibiting the institution which had broken his monarchical law regularly.
revolution: n. a time when people change a ruler or political system by using force or violence ⇨ revolt, rebellion革命
- The revolution in the thirteenth century no doubt continued into the fourteenth.
- There were elements of technology that made the fourteenth century a period of revolution.
- A revolution erupting in China was so influential that it captured the attention of people all over the world.
profound: adj. having a strong influence or effect深刻的, 意义深远的
- Sacrificing money for land exerted a profound influence on this monarchical state.
- The Black Death erupted in Europe through the flea-infested rats that were brought from China, which exerted a profound influence on Western Civilization. 
- His painting of the ceiling of the Sistine Chapel exerted a profound influence on the following arts.
reformation: n. formal when something is completely changed in order to improve it改革, 革新
- Even though the reformation turned out to be a failure, its profound influence inspired awe in many historians. 
- The reformation benefited many peasants who were free from fief which was dominated by old aristocracies.
- The reformation was expected to restore the warriors to new glory.
unify unified: v.adj. if you unify two or more parts or things, or if they unify, they are combined to make a single unit SYN unite OPP divide ⇨ unification统一
- Mongols unified a vast empire stretching from Russia in the west to China in the east.
- The unified territorial empire soon taught the Pope a lesson.
- The unified territorial empire couldn't bear the papal supremacy over secular authorities.
commonwealth: n. the official title of some countries made up of a group of states联邦
- At last, the pope unified a vast Christian commonwealth in Europe.
- The commonwealth constitutes many territorial states in the peninsula.
- The meeting of the commonwealth will be held at the promontory of the island.
--------------------
a new vision of sth.: 对某事的新视野/认识
- The new vision of math inspired awe in these intellectuals.
- He would not be satisfied until he got a new vision of the painting.
- A new vision of gunpower gave rise to a profound reformation in warfare.
raise fundamental questions/issues about sth.: 提出关于某事的基本问题
- My wife raised a fundamental question about who should pay for the hotel when we went on a date for the first time.
- Needless to say, he raised a fundamental question about the protection money that was provided by these merchants.
- The superior raised fundamental issues about the bugs I made.
upper classes: 上层阶级
- She managed to marry the upper class.
- The man who has worked for our company for over 5 years turns out to be a long-lost child of the upper class in our town.
- The upper classes hired a great artist to paint the ceiling of the chapel.
with sb's hands: 用某人双手
- Lee said he would make your dream come true with his hands.
- I hate to work with my hands in the field on summer holidays.
- I was instructed to wash my wife's underwear with my hands.
be incapable of sth./doing sth.: 无法做某事
- Our manager who claimed he was an accomplished programmer turned out to be incapable of programming.
- Everyone laughed at him who was incapable of programming.
- I am incapable of programming with my hands, so I quit.
have no time to do sth.: 没有时间去做某事
- In spite of graduating from school, my sister still has no time to babysit our child.
- We have no time to cultivate your English skills.
- I have no time to listen to your awful stories.
give way to sth.: 让位于某事;被某事取代
- The candle must give way to electrical light in my house.
- Our dog gave way to our cat which would never bark at passers-by.
- The complaints gave way to admiration, for it solved my problem on time.
** summary
Renaissance was not only a period of transition
		that extended most of trends in the High Middle Ages,
	but also a movement
		in which intellectuals proclaimed new vision of humandkind
			and raised fundamental issues about the value and importance of individuals.
Of course, the brilliant intellectual, cultural, and artistic accomplishments
	were really product of and for the elite.
The poor who work with their hands have no time to obtain perfection.
The humanists also raised fundamental questions about the Catholic church.
In the next chapter,
	the intellectual revolution of the fifteenth century gave way to the religious Renaissance,
	which touched the lives of masses in new and profound ways.
After the Reformation, Europe would never again be the unified Christian commonwealth.
** summary2
Renaissance was not only a period of transition
		that extended most of the trends in the High Middle Ages,
	but also a movement
		in which intellectuals proclaimed a new vision of humankind
			and raised fundamental issues about the value and importance of individuals.
Of course, the brilliant intellectual, cultural, and artistic accomplishments
	were products of and for the elite.
The poor who work with their hands have no time to obtain perfection.
The humanists also raised fundamental questions about the Catholic church.
In the next chapter,
	the intellectual revolution of the fifteenth century gave way to the religious Renaissance,
	which touched the lives of the masses in new and profound ways.
After the Reformation, Europe would never again be the unified Christian commonwealth.
