#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 14 The hazardous voyage of Magellan
#+begin_verse
While many Europeans were occupied with the problems of dynastic expansion and religious reform,
	others were taking voyages that propelled Europeans far beyond the medieval walls
		in which they had been enclosed for almost a thousand years.
One of these adventurers was the Portuguese explorer Ferdinand Magellan.
Convinced that he could find a sea passage to Asia through America,
	Magellan persuaded the king of Spain to finance an exploratory voyage.
On August 10, 1519,
	Magellan set sail on the Atlantic with five ships and a Spanish crew of 277 men.
After a stormy and difficult crossing of the ocean,
	Magellan’s fleet moved down the coast of South America,
		searching for the strait that would take him through.
His Spanish ship captains thought he was crazy:
	'The fool is obsessed with his search for a strait,' one remarked.
'On the flame of his ambition he will crucify us all.'
At last, in October 1520, he found it,
	passing through a narrow waterway (later named the Strait of Magellan)
	and emerging into an unknown ocean that he called the Pacific Sea.
Magellan reckoned that it would then be a short distance to the Spice Islands of the East,
	but he was badly mistaken.
Week after week, he and his crew sailed on across the Pacific as their food supplies dwindled.
According to one account,
	'When their last biscuit had gone,
		they scraped the maggots out of the casks, mashed them and served them as gruel.
They made cakes out of sawdust soaked with the urine of rats
	---the rats themselves, as delicacies, had long since been hunted to extinction.'
At last they reached the Philippines (named after King Philip II of Spain),
	where Magellan met his death at the hands of the natives.
Although only one of his original fleet of five ships survived and returned to Spain,
	Magellan is still remembered as the first person to circumnavigate the world.

At the beginning of the sixteenth century,
	European adventurers like Magellan
		had begun launching small fleets into the vast reaches of the Atlantic Ocean.
They were hardly aware that they were launching a new era,
	not only for Europe, but for the peoples of Asia, Africa, and the Americas as well.
Nevertheless, the voyages of these Europeans marked the beginning of a process
	that led to radical changes in the political, economic, and cultural life of the entire world.

Between 1500 and 1800, European power engulfed the globe.
In the Americas, Europeans established colonies that spread their laws, religions, and cultures.
In the island regions of Southeast Asia, Europeans firmly implanted their rule.
Elsewhere in Asia and in many parts of Africa,
	their trading activities dramatically affected the lifeways of the local peoples.
#+end_verse
** expression
dynasty dynastic [dɪ'næstɪk]: n.adj. a family of kings or other rulers whose parents, grandparents etc have ruled the country for many years朝代, 王朝
propel [prəˈpel]: v. to move, drive, or push something forward ⇨ propulsion推进, 驱使
adventure adventurer [ədˈventʃərər]: n. an exciting experience in which dangerous or unusual things happen冒险
passage ['pæsɪdʒ]: n. a way through something通道, 通路
finance [fɪˈnæns]: v. to provide money, especially a lot of money, to pay for something SYN fund供给...经费, 负担经费
exploratory [ɪkˈsplɔrəˌtɔri]: adj. done in order to find out more about something探险的, 探测的
stormy [ˈstɔrmi]: adj. with strong winds, heavy rain, and dark clouds暴风雨的
strait [streɪt]: n. a narrow passage of water between two areas of land, usually connecting two seas海峡
crucify [ˈkrusɪˌfaɪ]: v. to kill someone by fastening them to a cross十字架上钉死
waterway [ˈwɔtərˌweɪ]: n. a river or ↑canal that boats travel on水路
spice [spaɪs]: n. a type of powder or seed, taken from plants, that you put into food you are cooking to give it a special taste ⇨ spicy香料, 调味品
dwindle [ˈdwɪnd(ə)l]: v. to gradually become less and less or smaller and smaller缩小
scrape [skreɪp]: v. to remove something from a surface using the edge of a knife, a stick etc刮, 擦
maggot [ˈmæɡət]: n. a small creature like a ↑worm that is the young form of a ↑fly and lives in decaying food, flesh etc蛆
cask [kæsk]: n. a round wooden container used for storing wine or other liquids, or the amount of liquid that it contains SYN barrel桶, 木桶
mash [mæʃ]: v. to crush something, especially a food that has been cooked, until it is soft and smooth捣碎
gruel [ɡrul]: n. a food made of ↑oats cooked in water or milk, which poor people ate in the past稀粥
sawdust [ˈsɔˌdʌst]: n. very small pieces of wood that are left when you have been cutting wood锯屑
urine [ˈjʊrɪn]: n. the yellow liquid waste that comes out of the body from the ↑bladder尿
extinction [ɪkˈstɪŋkʃ(ə)n]: n. when a particular type of animal or plant stops existing消失
circumnavigate [ˌsɜrkəmˈnævɪˌɡeɪt]: v. to sail, fly, or travel completely around the Earth, an island etc环航
engulf [ɪnˈɡʌlf]: v. to completely surround or cover something吞没,完全包围
implant [ˈɪmˌplænt]: v. to strongly fix an idea, feeling, attitude etc in someone’s mind or character灌输
elsewhere [ˈelsˌhwer]: adv. in, at, or to another place在别处
affect [əˈfekt]: v. to do something that produces an effect or change in something or in someone’s situati影响
--------------------
be occupied with sth.: 忙于做某事
set sail: 起航
be obsessed with sth.: 沉迷于某事
On the flame of sb's ambition: 在某人野心的火焰上
emerge into sp.: 出现在某地
sb. reckoned that + ...: 某人认为...
Week after week: 连续多周
be soaked with sth.: 被某物浸湿
at the hands of sb.: 在某人手上
Nevertheless, +...: 然而, ...
** sentence
dynasty dynastic [dɪ'næstɪk]: n.adj. a family of kings or other rulers whose parents, grandparents etc have ruled the country for many years朝代, 王朝
- His dynasty seemed to revive its fortunes by this reformation.
- The dynatsic expansion gave rise to a great number of colonies.
- It comes as a surprise to learn that the team's dynastic was ended in this competition.
propel [prəˈpel]: v. to move, drive, or push something forward ⇨ propulsion推进, 驱使
- Propelled by the papal authority, he lost no time in completing the commission.
- Propelled by his family, he has to fellow in his father's footsteps.
- Propelled by the invention of compass, people in Europe began to explore outside world.
adventure adventurer [ədˈventʃərər]: n. an exciting experience in which dangerous or unusual things happen冒险
- He was remembered as a great adventurer who travelled across the Atlantic alone.
- The adventurer is protecting himself from being arrested by the local monarchs.
- The bridge was named after an adventure who used to be a pirate.
passage ['pæsɪdʒ]: n. a way through something通道, 通路
- If the passage hadn't been burnt down, they wouldn't have lost their life in floods.
- I was scared out of my wits by the noise from the narrow passage.
- The businessman exclaimed that the bomb had been planted on the passage.
finance [fɪˈnæns]: v. to provide money, especially a lot of money, to pay for something SYN fund供给...经费, 负担经费
- I am sure that my parent would finance me if I went to university.
- The king was determined to finance the church, which enabled it to assume political power.
- Staying out of the limelight, the Queen financed the noble in the Netterlands.
exploratory [ɪkˈsplɔrəˌtɔri]: adj. done in order to find out more about something探险的, 探测的
- The prince urged the warrior to take an exploratory voyage as soon as he could.
- He led an exploratory team to dig up treasure near the seashore.
- The exploratory team held a grudge against their team leader.
stormy [ˈstɔrmi]: adj. with strong winds, heavy rain, and dark clouds暴风雨的
- What a stormy night.
- A stormy night can give rise to a series of disaters.
- In a stormy night, he lost his temper and had a bad appetite.
strait [streɪt]: n. a narrow passage of water between two areas of land, usually connecting two seas海峡
- The voyage on the strait proved dangerous, for a group of vessels had sunken there.
- The adventurer put forward a crazy plan to build a suspension bridge over the strait.
- The absence of whale in the strait caused our favourite fishes to live and grow.
crucify [ˈkrusɪˌfaɪ]: v. to kill someone by fastening them to a cross十字架上钉死
- The brutal ruler piled up some peasants to stand trials and then crucified them.
- Crucifing murderers gave the judge a special type of satisfaction.
- The murderer went out of his way to prevent himself from being crucified in the prison. 
waterway [ˈwɔtərˌweɪ]: n. a river or ↑canal that boats travel on水路
- The captain had a bad appetite because he lost his way in the waterway.
- If you don't pay protection money, they will put you out of business in the waterway.
- They must have bumped into a band of pirates in the waterway.
spice [spaɪs]: n. a type of powder or seed, taken from plants, that you put into food you are cooking to give it a special taste ⇨ spicy香料, 调味品
- He was delighted that his wife presented him a special type of spice.
- For the first time, he had the nerve to taste this spice.
- I am delighted that you mixed our dishes with spices.
dwindle [ˈdwɪnd(ə)l]: v. to gradually become less and less or smaller and smaller缩小
- He had a bad temper because of his dwindling pocket money.
- When the stream flows into my field, it already dwindles to nothing.
- Finding his food was dwindling, he lit a cigarette to calm his nerve.
scrape [skreɪp]: v. to remove something from a surface using the edge of a knife, a stick etc刮, 擦
- He is scraping pastry from his computer surface with great care.
- You should have scraped pastry from the cask.
- The expert scraped the dust from the antique.
maggot [ˈmæɡət]: n. a small creature like a ↑worm that is the young form of a ↑fly and lives in decaying food, flesh etc蛆
- Suffering from a rare disease, he resorted to a type of maggot.
- He condemned his son as a maggot.
- Maggots which are rarely associated with foods are regarded as delicacies in this country.
cask [kæsk]: n. a round wooden container used for storing wine or other liquids, or the amount of liquid that it contains SYN barrel桶, 木桶
- Someone fired a shot at the cask, so these detectives were scared out of their wits.
- Dressed up as a servant, my wife sat down on the cask.
- One thousand dollors worth of cask was burnt down during the fire.
mash [mæʃ]: v. to crush something, especially a food that has been cooked, until it is soft and smooth捣碎
- He mashed it so that he could mixed it with the perfume.
- My brother threatened to mash my precious stone.
- The grass has taken root in the mashed stone. 
gruel [ɡrul]: n. a food made of ↑oats cooked in water or milk, which poor people ate in the past稀粥
- In my youth, a hot cup of gruel had been regraded as a type of delicacy.
- The gruel she didn't hand to you proved to be poisonous.
- The detective succeeded in protecting his host from the poisonous gruel.
sawdust [ˈsɔˌdʌst]: n. very small pieces of wood that are left when you have been cutting wood锯屑
- He found some sawdust in the soil near the entrance of the cave.
- The sawdust may be a special evidence of the murder, the detective exclaimed.
- It is a pity that our sawdust has been used up.
urine [ˈjʊrɪn]: n. the yellow liquid waste that comes out of the body from the ↑bladder尿
- Over the period scientists were enclosed in the house full of the smell of urine.
- He was kept in a cell full of the smell of urine.
- He kept his brother in hiding in a room full of the smell of urine.
extinction [ɪkˈstɪŋkʃ(ə)n]: n. when a particular type of animal or plant stops existing消失
- The oil spills gave rise to the extinction of a type of animal.
- The extinction of tigers in China inspired awe in some people.
- The extinction of tigers in China makes the expert feels obliged to research it.
circumnavigate [ˌsɜrkəmˈnævɪˌɡeɪt]: v. to sail, fly, or travel completely around the Earth, an island etc环航
- My dream of circumnavigating the globe came true recently.
- My wife lost concentration when I was explaining to the experience of the circumnavigation of the world.
- Our ship is underway to circumnavigate the globe in the competition.
engulf [ɪnˈɡʌlf]: v. to completely surround or cover something吞没,完全包围
- The businessman complained that he was engulfed by peasants in the city.
- He held a grudge against the masses of poor who engulfed him because of the lack of food.
- The masses engulfed the Comptroller and held up the traffic.
implant [ˈɪmˌplænt]: v. to strongly fix an idea, feeling, attitude etc in someone’s mind or character灌输
- The implanted idea exerted an enormous influence on his career.
- He implanted the sense of humor in his children in their youth.
- I felt that a set of laws were implanted in me on such short notice.
elsewhere [ˈelsˌhwer]: adv. in, at, or to another place在别处
- We must find some water elsewhere in the desert.
- This is a no-parking area, you must park your car elsewhere in the park.
- The seat has been taken, please sit down elsewhere in the class.
affect [əˈfekt]: v. to do something that produces an effect or change in something or in someone’s situati影响
- Beyond doubts, the area has been affected by the reformation.
- The raising power of the monarchical states affected the temporal authority of the Catholic church.
- The eruption of the Black Death affects the history of Western Civilization a great deal.
--------------------
be occupied with sth.: 忙于做某事
- I was occupied with fixing bugs you had made by your negligence.
- Occupied with washing dishes, he grudged to wash his wife's underwear.
- Occupied with finding lost treasures, the pirates took no interest in sacking this village.
set sail: 起航
- It has been five weeks since he set sail from the port.
- The man who she fell in love with must have set sail.
- The man who used to play truant from school set sail from the port to take exploratory voyage.
be obsessed with sth.: 沉迷于某事
- Obsessed with political power, the king sacrificed his daughter for the friendship of his neighbor.
- The warlike knight was obssessed with meanless fights.
- Obsessed with the pirate story, he left his home alone and crept into a boat.
On the flame of sb's ambition: 在某人野心的火焰上
- On the flame of his ambition, he was rewared with his fourth champion in the world games.
- On the flame of his ambition, the king sacrificed money for land.
- On the flame of his ambition, the monk organized new form of churchs to fight against the Catholic churchs.
emerge into sp.: 出现在某地
- He emerged into the school to which he dedicated his life.
- The pirate who was said to die emerged into the square.
- The lost treasure emerged into the sight of these pirates.
sb. reckoned that + ...: 某人认为...
- He reckoned that he should be rewarded with more prize.
- He reckoned that he would receive a ransom of 1000 dollars.
- He reckoned that his wife should be subject to him.
Week after week: 连续多周
- Week after week, he has lost money in gambles. 
- Week after week, he has been reading English article aloud in mornings.
- Week after week, there has been a car parking in front of his gate.
be soaked with sth.: 被某物浸湿
- Needless to say, he is a worker, for his shirt is soaked with sewage.
- No one could account for the fact his shirt was soaked with sewage.
- I grudged to eat the tomatoes soaked with sweat.
at the hands of sb.: 在某人手上
- He will meet his deat at the hands of mine.
- He will be put out of business at the hands of mine.
- He will be kept in prison at the hands of mine.
Nevertheless, +...: 然而, ...
- Nevertheless, he reckoned that he received a cold welcome.
- Nevertheless, he catched old boots all morning.
- Nevertheless, he mustered up his courage to tell her he loved her.
** sentence2
dynasty dynastic [dɪ'næstɪk]: n.adj. a family of kings or other rulers whose parents, grandparents etc have ruled the country for many years朝代, 王朝
- His dynasty seemed to revive its fortunes by this reformation.
- The dynastic expansion gave rise to a great number of colonies.
- It comes as a surprise to learn that the team's dynastic was ended in this competition.
propel [prəˈpel]: v. to move, drive, or push something forward ⇨ propulsion推进, 驱使
- Propelled by the papal authority, he lost no time in completing the commission.
- Propelled by his family, he has to follow in his father's footsteps.
- Propelled by the invention of the compass, people in Europe began to explore the outside world.
adventure adventurer [ədˈventʃərər]: n. an exciting experience in which dangerous or unusual things happen冒险
- He was remembered as a great adventurer who traveled across the Atlantic alone.
- The adventurer is protecting himself from being arrested by the local monarchs.
- The bridge was named after an adventurer who used to be a pirate.
passage ['pæsɪdʒ]: n. a way through something通道, 通路
- If the passage hadn't been burnt down, they wouldn't have lost their life in floods.
- I was scared out of my wits by the noise from the narrow passage.
- The businessman exclaimed that the bomb had been planted on the passage.
finance [fɪˈnæns]: v. to provide money, especially a lot of money, to pay for something SYN fund供给...经费, 负担经费
- I am sure that my parent would finance me if I went to university.
- The king was determined to finance the church, which enabled it to assume political power.
- Staying out of the limelight, the Queen financed the noble in the Netherlands.
exploratory [ɪkˈsplɔrəˌtɔri]: adj. done in order to find out more about something探险的, 探测的
- The prince urged the warrior to take an exploratory voyage as soon as he could.
- He led an exploratory team to dig up treasure near the seashore.
- The exploratory team held a grudge against their team leader.
stormy [ˈstɔrmi]: adj. with strong winds, heavy rain, and dark clouds暴风雨的
- What a stormy night.
- A stormy night can give rise to a series of disasters.
- On a stormy night, he lost his temper and had a bad appetite.
strait [streɪt]: n. a narrow passage of water between two areas of land, usually connecting two seas海峡
- The voyage on the strait proved dangerous, for a group of vessels had sunken there.
- The adventurer put forward a crazy plan to build a suspension bridge over the strait.
- The absence of whales in the strait caused our favorite fishes to live and grow.
crucify [ˈkrusɪˌfaɪ]: v. to kill someone by fastening them to a cross十字架上钉死
- The brutal ruler piled up some peasants to stand trials and then crucified them.
- Crucifying murderers gave the judge a special type of satisfaction.
- The murderer went out of his way to prevent himself from being crucified in the prison. 
waterway [ˈwɔtərˌweɪ]: n. a river or ↑canal that boats travel on水路
- The captain had a bad appetite because he lost his way in the waterway.
- If you don't pay protection money, they will put you out of business in the waterway.
- They must have bumped into a band of pirates in the waterway.
spice [spaɪs]: n. a type of powder or seed, taken from plants, that you put into food you are cooking to give it a special taste ⇨ spicy香料, 调味品
- He was delighted that his wife presented him with a special type of spice.
- For the first time, he had the nerve to taste this spice.
- I am delighted that you mixed our dishes with spices.
dwindle [ˈdwɪnd(ə)l]: v. to gradually become less and less or smaller and smaller缩小
- He had a bad temper because of his dwindling pocket money.
- When the stream flows into my field, it already dwindles to nothing.
- Finding his food was dwindling, he lit a cigarette to calm his nerves.
scrape [skreɪp]: v. to remove something from a surface using the edge of a knife, a stick etc刮, 擦
- He is scraping pastry from his computer surface with great care.
- You should have scraped pastry from the cask.
- The expert scraped the dust from the antique.
maggot [ˈmæɡət]: n. a small creature like a ↑worm that is the young form of a ↑fly and lives in decaying food, flesh etc蛆
- Suffering from a rare disease, he resorted to a type of maggot.
- He condemned his son as a maggot.
- Maggots which are rarely associated with foods are regarded as delicacies in this country.
cask [kæsk]: n. a round wooden container used for storing wine or other liquids, or the amount of liquid that it contains SYN barrel桶, 木桶
- Someone fired a shot at the cask, so these detectives were scared out of their wits.
- Dressed up as a servant, my wife sat down on the cask.
- One thousand dollars worth of cask was burnt down during the fire.
mash [mæʃ]: v. to crush something, especially a food that has been cooked, until it is soft and smooth捣碎
- He mashed it so that he could mix it with the perfume.
- My brother threatened to mash my precious stone.
- The grass has taken root in the mashed stone. 
gruel [ɡrul]: n. a food made of ↑oats cooked in water or milk, which poor people ate in the past稀粥
- In my youth, a hot cup of gruel had been regarded as a type of delicacy.
- The gruel she didn't hand to you proved to be poisonous.
- The detective succeeded in protecting his host from the poisonous gruel.
sawdust [ˈsɔˌdʌst]: n. very small pieces of wood that are left when you have been cutting wood锯屑
- He found some sawdust in the soil near the entrance of the cave.
- The sawdust may be a special evidence of the murder, the detective exclaimed.
- It is a pity that our sawdust has been used up.
urine [ˈjʊrɪn]: n. the yellow liquid waste that comes out of the body from the ↑bladder尿
- Over the period scientists were enclosed in the house full of the smell of urine.
- He was kept in a cell full of the smell of urine.
- He kept his brother in hiding in a room full of the smell of urine.
extinction [ɪkˈstɪŋkʃ(ə)n]: n. when a particular type of animal or plant stops existing消失
- The oil spills gave rise to the extinction of a type of animal.
- The extinction of tigers in China inspired awe in some people.
- The extinction of tigers in China makes the expert feel obliged to research it.
circumnavigate [ˌsɜrkəmˈnævɪˌɡeɪt]: v. to sail, fly, or travel completely around the Earth, an island etc环航
- My dream of circumnavigating the globe came true recently.
- My wife lost concentration when I was explaining to the experience of the circumnavigation of the world.
- Our ship is underway to circumnavigate the globe in the competition.
engulf [ɪnˈɡʌlf]: v. to completely surround or cover something吞没,完全包围
- The businessman complained that he was engulfed by peasants in the city.
- He held a grudge against the masses of poor who engulfed him because of the lack of food.
- The masses engulfed the Comptroller and held up the traffic.
implant [ˈɪmˌplænt]: v. to strongly fix an idea, feeling, attitude etc in someone’s mind or character灌输
- The implanted idea exerted an enormous influence on his career.
- He implanted the sense of humor in his children in their youth.
- I felt that a set of laws were implanted in me on such short notice.
elsewhere [ˈelsˌhwer]: adv. in, at, or to another place在别处
- We must find some water elsewhere in the desert.
- This is a no-parking area, you must park your car elsewhere in the park.
- The seat has been taken, please sit down elsewhere in the class.
affect [əˈfekt]: v. to do something that produces an effect or change in something or in someone’s situation影响
- Beyond doubts, the area has been affected by the reformation.
- The raising power of the monarchical states affected the temporal authority of the Catholic church.
- The eruption of the Black Death affects the history of Western Civilization a great deal.
--------------------
be occupied with sth.: 忙于做某事
- I was occupied with fixing bugs you had made by your negligence.
- Occupied with washing dishes, he grudged to wash his wife's underwear.
- Occupied with finding lost treasures, the pirates took no interest in sacking this village.
set sail: 起航
- It has been five weeks since he set sail from the port.
- The man who she fell in love with must have set sail.
- The man who used to play truant from school set sail from the port to take the exploratory voyage.
be obsessed with sth.: 沉迷于某事
- Obsessed with political power, the king sacrificed his daughter for the friendship of his neighbor.
- The warlike knight was obssessed with meanless fights.
- Obsessed with the pirate story, he left his home alone and crept into a boat.
On the flame of sb's ambition: 在某人野心的火焰上
- On the flame of his ambition, he was rewarded with his fourth champion in the world Games.
- On the flame of his ambition, the king sacrificed money for land.
- On the flame of his ambition, the monk organized a new form of church to fight against the Catholic church.
emerge into sp.: 出现在某地
- He emerged into the school to which he dedicated his life.
- The pirate who was said to die emerged into the square.
- The lost treasure emerged into the sight of these pirates.
sb. reckoned that + ...: 某人认为...
- He reckoned that he should be rewarded with more.
- He reckoned that he would receive a ransom of 1000 dollars.
- He reckoned that his wife should be subject to him.
Week after week: 连续多周
- Week after week, he has lost money in gambles. 
- Week after week, he has been reading English articles aloud in the mornings.
- Week after week, there has been a car parking in front of his gate.
be soaked with sth.: 被某物浸湿
- Needless to say, he is a worker, for his shirt is soaked with sewage.
- No one could account for the fact his shirt was soaked with sewage.
- I grudged to eat the tomatoes soaked with sweat.
at the hands of sb.: 在某人手上
- He will meet his death at the hands of mine.
- He will be put out of business at the hands of mine.
- He will be kept in prison at the hands of mine.
Nevertheless, +...: 然而, ...
- Nevertheless, he reckoned that he received a cold welcome.
- Nevertheless, he caught old boots all morning.
- Nevertheless, he mustered up his courage to tell her he loved her.
** summary
While many Europeans were occupied with the problems of dynastic expansion and religious reforms,
	others were taking voyages beyond the wall which enclosed them for over a thousand years.
The Portuguese explorer Magellan was convinced that he could find a passway through America to Asia,
	he moved down the coast of south America, searching for the strait that would take him through. 
His ship captains thought he was obsessed with the strait and would crucify them all.
At last, he found it and emeraged into the Pacific Sea.
He thought in error it would be a short distance to Asia,
	before they sailed on the Ocean week after week and their food supplies dwindled.
In the end, they reached the Philippiness, where Magellan met his death at the hands of natives.
Although only one of the ships returned to Spain,
	he was still remembered as the first person to circumnavigate the world.
European adventurers like Magellan who launched small fleets into the reaches of the Atlantic
	marked the begining of a process that gave rise to radical changes in the world.
Within this process, European power began to engulf the globe.
** summary2
While many Europeans were occupied with the problems of dynastic expansion and religious reforms,
	others were taking voyages beyond the wall which enclosed them for over a thousand years.
The Portuguese explorer, Magellan,
		was convinced that he could find a passway through America to Asia,
	he moved down the coast of South America, searching for the strait that would take him through. 
His ship captains thought he was obsessed with the strait and would crucify them all.
At last, he found it and emerged into the Pacific Sea.
He felt in error it would be a short distance to Asia
	before they sailed on the ocean week after week and their food supplies dwindled.
In the end, they reached the Philippines, where Magellan met his death at the hands of natives.
Although only one of the ships returned to Spain,
	he was still remembered as the first person to circumnavigate the world.
European adventurers like Magellan that launched small fleets into the reaches of the Atlantic
	marked the beginning of a process that gave rise to radical changes in the world.
Within this process, European powers began to engulf the globe.
