#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 15 state building and the search for order in the seventeenth century
#+begin_verse
By the end of the sixteenth century,
	Europe was beginning to experience some decline in religious passions
		and a growing secularization that affected both the political and intellectual worlds. 
Some historians like to speak of the seventeenth century as
	a turning point in the evolution of the modern state system in Europe.
The ideal of a united Christian Europe
	gave way to the practical realities of a system of secular entities
		in which matters of state took precedence over the salvation of subjects' souls.
By the seventeenth century,
	the credibility of Christianity had been so weakened through religious wars
		that more and more Europeans came to think of politics in strictly secular terms.
		
One of the responses to the religious wars and other crises of the time was a yearning for order.
As the internal social and political rebellions and revolts died down,
	it became apparent
		that the privileged classes of society---the aristocrats---remained in control,
			although important differences in political forms existed in the various states.
In many places, the extension of monarchical power was viewed as a stabilizing force.
This development, which historians have called absolutism or absolute monarchy,
		was most evident in France during the flamboyant reign of Louis XIV,
	widely regarded as the perfect embodiment of an absolute monarch.
In his memoirs, the duc de Saint-Simon, who had firsthand experience of French court life,
	said that Louis was the very figure of a hero,
		so imbued with a natural but most imposing majesty
			that it appeared even in his most insignificant gestures and movements.
The king's natural grace gave him a special charm as well:
	He was as dignified and majestic in his dressing gown as when dressed in robes of state,
		or on horseback at the head of his troops.
His life was orderly:
	Nothing could be regulated with greater exactitude than were his days and hours.
His self-control was impeccable:
	He did not lose control of himself ten times in his whole life,
		and then only with inferior persons.
But even absolute monarchs had imperfections, and Saint-Simon had the courage to point them out:
	Louis XIV's vanity was without limit or restraint,
		which led to his distaste for all merit, intelligence, education, and, most of all,
			for all independence of character and sentiment in others,
				as well as his mistakes of judgment in matters of importance.

But absolutism was not the only response to the search for order in the seventeenth century.
Other states, such as England,
	reacted differently to domestic crisis, and another very different system emerged
		where monarchs were limited by the power of their representative assemblies.
Absolute and limited monarchy were the two poles of seventeenth-century state building.
#+end_verse
** expression
entity [ˈentəti]: n. formal something that exists as a single and complete unit ⇨ being实体
credibility [ˌkredɪˈbɪləti]: n. the quality of deserving to be believed and trusted可信性
yearn [jɜrn] yearning: v.n. literary to have a strong desire for something, especially something that is difficult or impossible to get SYN long渴望
internal [ɪnˈtɜrn(ə)l]: adj. within a particular country SYN domestic OPP external内在的, 国内的
extension [ɪkˈstenʃ(ə)n]: n. the process of making a road, building etc bigger or longer, or the part that is added延长
flamboyant [flæmˈbɔɪənt]: adj. brightly coloured and easily noticed辉煌的
embodiment [ɪmˈbɑdɪmənt]: n. the embodiment of something someone or something that represents or is very typical of an idea or quality SYN epitome化身
memoir [ˈmemˌwɑr]: n. a book by someone important and famous in which they write about their life and experiences回忆录
imposing [imˈpoʊziŋ]: adj. large, impressive, and appearing important壮观的
majesty [ˈmædʒəsti] majestic: n.adj. the quality that something big has of being impressive, powerful, or beautiful SYN grandeur王权, 雄伟
gesture [ˈdʒestʃər]: n. a movement of part of your body, especially your hands or head, to show what you mean or how you feel姿态
grace [ɡreɪs] graceful: n.adj. a smooth way of moving that looks natural, relaxed, and attractive SYN gracefulness优雅
charm [tʃɑrm] charming: n.adj. a special quality someone or something has that makes people like them, feel attracted to them, or be easily influenced by them – used to show approval ⇨ charming吸引力
dignified [ˈdiɡniˌfaɪd]: adj. behaving in a calm and serious way, even in a difficult situation, which makes people respect you有威严的
gown [ɡaʊn]: n. a long loose piece of clothing worn for special ceremonies by judges, teachers, lawyers, and members of universities SYN robe长袍
robe [roʊb]: n. a long loose piece of clothing, especially one worn for official ceremonies长袍
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
impeccable [ɪmˈpekəb(ə)l]: adj. without any faults and impossible to criticize SYN perfect没有缺点的
inferior [ɪnˈfɪriər]: adj. not good, or not as good as someone or something else OPP superior下等的, 下级的
imperfect [ɪmˈpɜrfɪkt] imperfection: adj.n. not completely correct or perfect SYN flawed有缺点的
restrain [rɪˈstreɪn] restraint: v.n. a rule or principle that limits what people can do克制
distaste [dɪsˈteɪst]: n. a feeling that something or someone is unpleasant or morally offensive讨厌, 嫌恶
merit [ˈmerɪt]: n. an advantage or good feature of something优点, 价值
intelligence [ɪnˈtelɪdʒəns]: n. the ability to learn, understand, and think about things智能,智慧
sentiment [ˈsentɪmənt]: n. feelings of pity, love, sadness etc that are often considered to be too strong or not suitable for a particular situation SYN emotion情感
domestic [dəˈmestɪk]: adj. relating to or happening in one particular country and not involving any other countries ⇨ foreign家庭的, 国内的
assembly [əˈsembli]: n. a group of people who are elected to make decisions or laws for a particular country, area, or organization议会
--------------------
a turning point: 转折点
the practical realities (of sth.): 某物的实际情况
take precedence over sth./sb.: 优先于某物/某人
in strictly secular terms: 在严格世俗角度上
it becomes apparent that: 某事显而易见
be imbued with sth.: 充满某物
lose control of sb.: 失去对某人的控制
have the courage to do sth.: 有勇气去做某事
** sentence
entity [ˈentəti]: n. formal something that exists as a single and complete unit ⇨ being实体
- The manager bought the rest stocks so that the subsidiary became a separate entity.
- After the forest fire was under control, the village had became a separate entity.
- The build which is made of iron and glass used to be viewed as a separate entity.
credibility [ˌkredɪˈbɪləti]: n. the quality of deserving to be believed and trusted可信性
- A slip of tongue by no means reduced the credibilty of what he told us.
- We still need to examine the credibility of these reports.
- The manager bought the rest stocks so that the subsidiary became a separate entity.
yearn [jɜrn] yearning: v.n. literary to have a strong desire for something, especially something that is difficult or impossible to get SYN long渴望
- His yearning for money led to a serious murder in which he killed his wife who is far older than him.
- When I first ran into my wife, I yearned to ask her out.
- Mr Leo yearns to make a profile so that he can fulfill his dream of setting up an educational empire.
internal [ɪnˈtɜrn(ə)l]: adj. within a particular country SYN domestic OPP external内在的, 国内的
- While many English were occupied with internal conflicts, others were exploring outside world.
- The emperor succeeded in starting a war to solve internal conflicts.
- The general is an expert at solving internal conflicts in this way in which he spurs domestic angries towards other country.
extension [ɪkˈstenʃ(ə)n]: n. the process of making a road, building etc bigger or longer, or the part that is added延长
- It is said that there will be the extension of metro line 3 in this district.
- The exntension of our passage turned out to be broke by our enemies.
- The sheriff has blamed him for the extension of the apartment which caused three passengers injure in the flood. 
flamboyant [flæmˈbɔɪənt]: adj. brightly coloured and easily noticed辉煌的
- The general was determined to sack the city, where the flamboyant palace had been burnt down.
- The flaboyant palace inspired awe in people the world over.
- The flamboyant museum was used to be in memory of our heroes who were killed in action.
embodiment [ɪmˈbɑdɪmənt]: n. the embodiment of something someone or something that represents or is very typical of an idea or quality SYN epitome化身
- In ancient time, the emperor of a country was regarded as the embodiment of the god.
- The statue regarded as the embodiment of beauty stood two feets high.
- The building fully made of iron and glass was the embodiment of technology and beauty.
memoir [ˈmemˌwɑr]: n. a book by someone important and famous in which they write about their life and experiences回忆录
- In his memoir, he was obsessed with the painting of the ceiling in the chapel.
- In his memoir, he had an idea of proceeding his close friend who was guilty of fraud.
- In his memoir, he was underway to spy on his superior.
imposing [imˈpoʊziŋ]: adj. large, impressive, and appearing important壮观的
- It is a pity that an imposing figure committed a murder for such tiny money.
- He lost no time in compeleting an imposing building.
- He have the ability to depict any normal buildings as imposing.
majesty [ˈmædʒəsti] majestic: n.adj. the quality that something big has of being impressive, powerful, or beautiful SYN grandeur王权, 雄伟
- The majesty of the Alps is beyond description.
- You can feel the majesty of the statue which holds that pose.
- The majesty of the mountain range is millions of years in the making.
gesture [ˈdʒestʃər]: n. a movement of part of your body, especially your hands or head, to show what you mean or how you feel姿态
- The shop assistant didn't like his gesture, so he was told that the suit had been sold out.
- His gesture proved graceful, for he captured the attention of many girl in the party. 
- When Mr. Leo learnt that his student mimicked his gesture in class, he got very angry.
grace [ɡreɪs] graceful: n.adj. a smooth way of moving that looks natural, relaxed, and attractive SYN gracefulness优雅
- A graceful swam is being trapped in the cage.
- A graceful lady received a warm welcome, when she came to work at the first day.
- A graceful lady dressed in block stocking waved to me while my wife was sitting beside me.
charm [tʃɑrm] charming: n.adj. a special quality someone or something has that makes people like them, feel attracted to them, or be easily influenced by them – used to show approval ⇨ charming吸引力
- They are charming, aren't they.
- A famous fossil millions of years in the making is extraordinarily charming.
- A charming girl never loses her attraction to her mate.
dignified [ˈdiɡniˌfaɪd]: adj. behaving in a calm and serious way, even in a difficult situation, which makes people respect you有威严的
- If you were dignified, you wouldn't be laughed at in your class.
- The warlike knight is so dignified that everyone in the legion is subject to him.
- The dignified father didn't heistate to push his child who played truant from school.
gown [ɡaʊn]: n. a long loose piece of clothing worn for special ceremonies by judges, teachers, lawyers, and members of universities SYN robe长袍
- Wearing a graceful gown, he yearned to explain the cospiracy of his enemy to people.
- Dressed in a charming gown, he has the nerve to take the plunge.
- With the gown comes power, and he ordered his men to throw the foods sacks away.
robe [roʊb]: n. a long loose piece of clothing, especially one worn for official ceremonies长袍
- The man who wears robe turns out to be our priest.
- The detective could figure out who committed the murder by the special type of robe.
- The type of robes made in Korea becomes popular with Chinese young people these days.
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
- The emporer drew up a set of laws to regulate these states.
- He is the CEO who is sent by our superior to regulate this subsidiary.
- On arriving in China, the elite dispatched a circle of officers to regulate the subsidiary.
impeccable [ɪmˈpekəb(ə)l]: adj. without any faults and impossible to criticize SYN perfect没有缺点的
- The breakdown of trust in the leaders led to a difficult sitatuion in which soilders thought of their enemies impeccable.
- The impeccable CEO tends to plan out his project to the last detail.
- The impeccable colossal ship sunk on her first voage, which was regarded as a tremendous tragedy.
inferior [ɪnˈfɪriər]: adj. not good, or not as good as someone or something else OPP superior下等的, 下级的
- He deserves a job of inferior status. 
- There is a job of inferior status which was paid well.
- My father urged me to accept a job of inferior status.
imperfect [ɪmˈpɜrfɪkt] imperfection: adj.n. not completely correct or perfect SYN flawed有缺点的
- I'm curious to find out what his imperfection is.
- The imperfection of our enemies is their breakdown of trust in their emperor.
- More recently, the imperfect project have run smoothly.
restrain [rɪˈstreɪn] restraint: v.n. a rule or principle that limits what people can do克制
- It seems that your child plays truant from school without restraint.
- He realized to his horror that his wife tended to waste money without restrain.
- The healthy alarm was given because he stay overnight without restrain.
distaste [dɪsˈteɪst]: n. a feeling that something or someone is unpleasant or morally offensive讨厌, 嫌恶
- His distaste of intellectuals led to a serious revolts.
- More recently, he paid for his distate of his teachers.
- The distate of his teachers is the price to the bad grade.
merit [ˈmerɪt]: n. an advantage or good feature of something优点, 价值
- The gentleman has the merit of a sense of humor.
- He has the merit of speaking well in public.
- My cat has the merit of hygiene obsessed.
intelligence [ɪnˈtelɪdʒəns]: n. the ability to learn, understand, and think about things智能,智慧
- To be fluent in English, you need a reasonable level of intelligence.
- My cat was able to prise it up at last, which showed her a level of intelligence.
- I never undermine my faith in the intelligence of my child.
sentiment [ˈsentɪmənt]: n. feelings of pity, love, sadness etc that are often considered to be too strong or not suitable for a particular situation SYN emotion情感
- He continued to neglect his wife's sentiment, which caused his wife cheat on her.
- The man who paid a ransom of 1000 dollars was susceptible to other's sentiment.
- The woman susceptible to other's sentiment has been contributing to a local school.
domestic [dəˈmestɪk]: adj. relating to or happening in one particular country and not involving any other countries ⇨ foreign家庭的, 国内的
- The domestic conflicts proved complicated, for it was associate with a large sum of money.
- The domestic quarrel in the monarchs led to the breakdown of subjects of trust in them.
- The police in China are said to be good at handling domestic conflicts.
assembly [əˈsembli]: n. a group of people who are elected to make decisions or laws for a particular country, area, or organization议会
- The assembly raised fundamental issues about the value and importance of individuals.
- The assembly drew up a set of laws prohibiting digging up the coffin.
- The assembly will have been helding for three weeks.
--------------------
a turning point: 转折点
- As a turning point, his inferiors gradually learnt that he had had a skeleton in cupborad.
- As a turning point, the cooker poisoned his wife who threatened to turn him in.
- As a turning point, the emperor lost his control of the city because of the Asiatic nomads.
the practical realities (of sth.): 某物的实际情况
- Sir, I've forgotten my key. This is the practical realities of why I was climbing the ladder against the window.
- The practical realities of so-call sales is another pyramid scheme. 
- The practical realities of the accident is an elaborated murder.
take precedence over sth./sb.: 优先于某物/某人
- Let our child play video games as much as he wants, he would let it take precedence over study.
- With having fun taking precedence over his work, he was put out of business.
- While he was competing with other merchants, the profit he made took precedence over his status in social.
in strictly secular terms: 在严格世俗角度上
- I hate to think of everything about in strictly secular terms.
- The project by no means let us make a profit in strictly secular terms. 
- We don't need to contribute to stary children in strictly secular terms.
it becomes apparent that: 某事显而易见
- It became apparent that the diamond had been stolen at the airport.
- It became apparent that the snake could not tell the difference between India music and jazz.
- It became apparent that he had five cats in all.
be imbued with sth.: 充满某物
- Imbued with grace, he offered his seat to a young lady.
- Imbued with honor, he defended his lord against these masses in the rebellions.
- Imbued with horror, she covered herself with three sheets of blankets. 
lose control of sb.: 失去对某人的控制
- Losing control of the snake, he was bited by snake and sent to hospital in emergency.
- Losing control of his inferiors, he was sensetive to accept these criticisms.
- Losing control of his armies, he was suseptitle to the revolts in the capital.
have the courage to do sth.: 有勇气去做某事
- I have the courage to accept criticisms of our masses in public.
- She has the courage to lose control of the armies. 
- The explorer has the courage to take hazardous voyage across the Atlantic.
** sentence2
entity [ˈentəti]: n. formal something that exists as a single and complete unit ⇨ being实体
- The manager bought the rest stocks so that the subsidiary became a separate entity.
- After the forest fire was under control, the village became a separate entity.
- The building which is made of iron and glass used to be viewed as a separate entity.
credibility [ˌkredɪˈbɪləti]: n. the quality of deserving to be believed and trusted可信性
- A slip of the tongue by no means reduced the credibility of what he told us.
- We still need to examine the credibility of these reports.
- The manager bought the rest stocks so that the subsidiary became a separate entity.
yearn [jɜrn] yearning: v.n. literary to have a strong desire for something, especially something that is difficult or impossible to get SYN long渴望
- His yearning for money led to a serious murder in which he killed his wife who is far older than him.
- When I first ran into my wife, I yearned to ask her out.
- Mr Leo yearns to make a profile so that he can fulfill his dream of setting up an educational empire.
internal [ɪnˈtɜrn(ə)l]: adj. within a particular country SYN domestic OPP external内在的, 国内的
- While many English were occupied with internal conflicts, others were exploring the outside world.
- The emperor succeeded in starting a war to solve internal conflicts.
- The general is an expert at solving internal conflicts in this way in which he spurs domestic anger towards other countries.
extension [ɪkˈstenʃ(ə)n]: n. the process of making a road, building etc bigger or longer, or the part that is added延长
- It is said that there will be an extension of metro line 3 in this district.
- The extension of our passage turned out to be broken by our enemies.
- The sheriff has blamed him for the extension of the apartment which caused three passengers injured in the flood. 
flamboyant [flæmˈbɔɪənt]: adj. brightly coloured and easily noticed辉煌的
- The general was determined to sack the city, where the flamboyant palace had been burnt down.
- The flamboyant palace inspired awe in people the world over.
- The flamboyant museum was in memory of our heroes who were killed in action.
embodiment [ɪmˈbɑdɪmənt]: n. the embodiment of something someone or something that represents or is very typical of an idea or quality SYN epitome化身
- In ancient times, the emperor of a country was regarded as the embodiment of the god.
- The statue regarded as the embodiment of beauty stood two feet high.
- The building fully made of iron and glass was the embodiment of technology and beauty.
memoir [ˈmemˌwɑr]: n. a book by someone important and famous in which they write about their life and experiences回忆录
- In his memoir, he was obsessed with the painting of the ceiling in the chapel.
- In his memoir, he had an idea of proceeding against his close friend who was guilty of fraud.
- In his memoir, he was underway to spy on his superior.
imposing [imˈpoʊziŋ]: adj. large, impressive, and appearing important壮观的
- It is a pity that an imposing figure committed a murder for such tiny money.
- He lost no time in completing an imposing building.
- He has the ability to depict any normal buildings as imposing.
majesty [ˈmædʒəsti] majestic: n.adj. the quality that something big has of being impressive, powerful, or beautiful SYN grandeur王权, 雄伟
- The majesty of the Alps is beyond description.
- You can feel the majesty of the statue which holds that pose.
- The majesty of the mountain range is millions of years in the making.
gesture [ˈdʒestʃər]: n. a movement of part of your body, especially your hands or head, to show what you mean or how you feel姿态
- The shop assistant didn't like his gesture, so he was told that the suit had been sold out.
- His gesture proved graceful, for he captured the attention of many girls in the party. 
- When Mr. Leo learned that his student mimicked his gesture in class, he got very angry.
grace [ɡreɪs] graceful: n.adj. a smooth way of moving that looks natural, relaxed, and attractive SYN gracefulness优雅
- A graceful swam is being trapped in the cage.
- A graceful lady received a warm welcome when she came to work on the first day.
- A graceful lady dressed in block stocking waved to me while my wife was sitting beside me.
charm [tʃɑrm] charming: n.adj. a special quality someone or something has that makes people like them, feel attracted to them, or be easily influenced by them – used to show approval ⇨ charming吸引力
- They are charming, aren't they?
- A famous fossil millions of years in the making is extraordinarily charming.
- A charming girl never loses her attraction to her mate.
dignified [ˈdiɡniˌfaɪd]: adj. behaving in a calm and serious way, even in a difficult situation, which makes people respect you有威严的
- If you were dignified, you wouldn't be laughed at in your class.
- The warlike knight is so dignified that everyone in the legion is subject to him.
- The dignified father didn't hesitate to push his child who played truant from school.
gown [ɡaʊn]: n. a long loose piece of clothing worn for special ceremonies by judges, teachers, lawyers, and members of universities SYN robe长袍
- Wearing a graceful gown, he yearned to explain the conspiracy of his enemy to people.
- Dressed in a charming gown, he has the nerve to take the plunge.
- With the gown came power, and he ordered his men to throw the food sacks away.
robe [roʊb]: n. a long loose piece of clothing, especially one worn for official ceremonies长袍
- The man who wears a robe turns out to be our priest.
- The detective could figure out who committed the murder by the special type of robe.
- The type of robes made in Korea become popular with Chinese young people these days.
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
- The Emporer drew up a set of laws to regulate these states.
- He is the CEO who is sent by our superior to regulate this subsidiary.
- On arriving in China, the elite dispatched a circle of officers to regulate the subsidiary.
impeccable [ɪmˈpekəb(ə)l]: adj. without any faults and impossible to criticize SYN perfect没有缺点的
- The breakdown of trust in the leaders led to a difficult situation in which soldiers thought their enemies were impeccable.
- The impeccable CEO tends to plan out his project to the last detail.
- The impeccable colossal ship sunk on her first voyage, which was regarded as a tremendous tragedy.
inferior [ɪnˈfɪriər]: adj. not good, or not as good as someone or something else OPP superior下等的, 下级的
- He deserves a job of inferior status. 
- There is a job of inferior status that was paid well.
- My father urged me to accept a job of inferior status.
imperfect [ɪmˈpɜrfɪkt] imperfection: adj.n. not completely correct or perfect SYN flawed有缺点的
- I'm curious to find out what his imperfection is.
- The imperfection of our enemies is their breakdown of trust in their emperor.
- More recently, the imperfect project has run smoothly.
restrain [rɪˈstreɪn] restraint: v.n. a rule or principle that limits what people can do克制
- It seems that your child plays truant from school without restraint.
- He realized to his horror that his wife tended to waste money without restraint.
- The health alarm was given because he stayed overnight without restraint.
distaste [dɪsˈteɪst]: n. a feeling that something or someone is unpleasant or morally offensive讨厌, 嫌恶
- His distaste for intellectuals led to a serious revolt.
- More recently, he paid for his distaste for his teachers.
- The distaste of his teachers is the price of the bad grades.
merit [ˈmerɪt]: n. an advantage or good feature of something优点, 价值
- The gentleman has the merit of a sense of humor.
- He has the merit of speaking well in public.
- My cat has the merit of being hygiene-obsessed.
intelligence [ɪnˈtelɪdʒəns]: n. the ability to learn, understand, and think about things智能,智慧
- To be fluent in English, you need a reasonable level of intelligence.
- My cat was able to prise it up at last, which showed her a level of intelligence.
- I never undermine my faith in the intelligence of my child.
sentiment [ˈsentɪmənt]: n. feelings of pity, love, sadness etc that are often considered to be too strong or not suitable for a particular situation SYN emotion情感
- He continued to neglect his wife's sentiment, which caused his wife to cheat on her.
- The man who paid a ransom of 1000 dollars was susceptible to other's sentiments.
- The woman susceptible to other's sentiments has been contributing to a local school.
domestic [dəˈmestɪk]: adj. relating to or happening in one particular country and not involving any other countries ⇨ foreign家庭的, 国内的
- The domestic conflicts proved complicated, for it was associated with a large sum of money.
- The domestic quarrel in the monarchs led to the breakdown of subjects of trust in them.
- The police in China are said to be good at handling domestic conflicts.
assembly [əˈsembli]: n. a group of people who are elected to make decisions or laws for a particular country, area, or organization议会
- The assembly raised fundamental issues about the value and importance of individuals.
- The assembly drew up a set of laws prohibiting digging up the coffin.
- The assembly will have been being held for three weeks.
--------------------
a turning point: 转折点
- As a turning point, his inferiors gradually learned that he had had a skeleton in the cupboard.
- As a turning point, the cooker poisoned his wife who threatened to turn him in.
- As a turning point, the emperor lost his control of the city because of the Asiatic nomads.
the practical reality (of sth.): 某物的实际情况
- Sir, I've forgotten my key. This is the practical reality of why I was climbing the ladder against the window.
- The practical reality of so-called sales is another pyramid scheme. 
- The practical reality of the accident on the surface is an elaborated murder.
take precedence over sth./sb.: 优先于某物/某人
- Let our child play video games as much as he wants, he would let it take precedence over study.
- With having fun taking precedence over his work, he was put out of business.
- While he was competing with other merchants, the profit he made took precedence over his social status.
in strictly secular terms: 在严格世俗角度上
- I hate to think of everything about moeny in strictly secular terms.
- The project by no means lets us make a profit in strictly secular terms. 
- We don't need to contribute to stary children in strictly secular terms.
it becomes apparent that: 某事显而易见
- It became apparent that the diamond had been stolen at the airport.
- It became apparent that the snake could not tell the difference between Indian music and jazz.
- It became apparent that he had five cats in all.
be imbued with sth.: 充满某物
- Imbued with grace, he offered his seat to a young lady.
- Imbued with honor, he defended his lord against these masses in the rebellions.
- Imbued with horror, she covered herself with three sheets of blankets. 
lose control of sb.: 失去对某人的控制
- Losing control of the snake, he was bitten by the snake and sent to the hospital in an emergency.
- Losing control of his inferiors, he was sensitive to accept these criticisms.
- Losing control of his armies, he was susceptible to the revolts in the capital.
have the courage to do sth.: 有勇气去做某事
- I have the courage to accept criticisms of our masses in public.
- She has the courage to lose control of the armies. 
- The explorer has the courage to take a hazardous voyage across the Atlantic.
** summary
By the end of sixteenth century, decline in religious passions paralleled a growing secularization.
The ideal of a united Christian Europe
	gave way to practical realities of a system of secular entities.
By the seventeenth century,
	the credibility of Christianity had been so weakened through religious wars
		that more and more Europeans came to think of politics in strictly secular terms.
As the internal social and political rebellions and revolts died down,
	the aristocrats reminded in control differently in the various states.
In many places, the extension of monarchical power called absolutism began.
It was so evident in France during the reign of Louis XIV
	that he was regarded as the perfect embodiment of absolutism.
In his memoirs, he was imbued with a natural but most imposing majesty.
Not only was his life orderly,
	but his self-control was so impeccable
		that he didn't lost control of himself ten times in his life.
As it is, he also had imperfections such as his unlimited vanity,
	distate for all merit,
		intelligence, education, and all independence of character and sentiment in others,
	as well as his mistaken judgement in important matters.
Beside, other states, such as English, developed another different system
	where monarchs were limited by the power of their representative assemblies.
** summary2
By the end of the sixteenth century,
	the decline in religious passions paralleled a growing secularization.
The ideal of a united Christian Europe
	gave way to the practical realities of a system of secular entities.
By the seventeenth century,
	the credibility of Christianity had been so weakened through religious wars
		that more and more Europeans came to think of politics in strictly secular terms.
As the internal social and political rebellions and revolts died down,
	the aristocrats remained in control differently in the various states.
In many places, the extension of monarchical power called absolutism began.
It was so evident in France during the reign of Louis XIV
	that he was regarded as the perfect embodiment of absolutism.
In his memoirs, he was imbued with a natural but most imposing majesty.
Not only was his life orderly,
	but his self-control was so impeccable
		that he didn't lose control of himself ten times in his life.
As it is, he also had imperfections such as his unlimited vanity,
	distaste for all merit,
		intelligence, education, and all independence of character and sentiment in others,
	as well as his mistaken judgment in important matters.
Besides, other states, such as England, developed another different system
	where monarchs were limited by the power of their representative assemblies.
