#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 17 The Social Environment of the Philosophes
#+begin_verse
The social backgrounds of the philosophes varied considerably,
	from the aristocratic Montesquieu to the lower-middle-class Diderot and Rousseau.
The Enlightenment was not the preserve of any one class,
	although obviously its greatest appeal
		was to the aristocracy and upper middle classes of the major cities.
The common people, especially the peasants, were little affected by the Enlightenment.

Of great importance to the Enlightenment
	was the spread of its ideas to the literate elite of European society.
Although the publication and sale of books and treatises were crucial to this process,
	the salon was also a factor.
Salons came into being in the seventeenth century but rose to new heights in the eighteenth.
These were elegant drawing rooms in the urban houses of the wealthy
	where philosophes and guests gathered to engage in witty,	sparkling conversations
		that often centered on the ideas of the philosophes.
In France's rigid hierarchical society,
	the salons were important in bringing together writers and artists
		with aristocrats, government officials, and wealthy members of the bourgeoisie.

As hostesses of the salons,
	women found themselves in a position to affect the decisions of kings,
		sway political opinion, and influence literary and artistic taste.
Salons provided havens for people and views unwelcome in the royal court.
When Diderot’s Encyclopedia was suppressed by the French authorities,
	Marie-Therese de Geoffrin (1699--1777), a wealthy bourgeois widow whose father had been a valet,
		welcomed the encyclopedists to her salon
			and offered financial assistance to complete the work in secret.
Madame Geoffrin was not without rivals, however.
The marquise du Deffand (1697--1780) had abandoned her husband in the provinces
		and established herself in Paris,
	where her ornate drawing room attracted many of the Enlightenment's great figures,
		including Montesquieu and Voltaire.

Although the salons were run by women,
	the reputation of a salon depended on the stature of the males a hostess was able to attract.
Despite this male domination, however,
	both French and foreign observers complained
		that females exerted undue influence in French political affairs.
Though exaggerated, this perception led to the decline of salons
	during the French Revolution toward the end of the century.
#+end_verse
** expression
literate [ˈlɪt(ə)rət]: adj. able to read and write OPP illiterate ⇨ numerate有文化的
publication [ˌpʌblɪˈkeɪʃ(ə)n]: n. the process of printing a book, magazine etc and offering it for sale ⇨ publish出版物, 出版
treatise [ˈtritɪs]: n. a serious book or article about a particular subject论文
guest [ɡest]: n. someone who is invited to an event or special occasion客人
witty: using words in a clever and amusing way诙谐的
sparkling: shining brightly with points of flashing light; full of life and intelligence闪烁的;充满生机的
hierarchy [ˈhaɪəˌrɑrki] hierarchical: n.adj. if a system, organization etc is hierarchical, people or things are divided into levels of importance等级的
haven [ˈheɪv(ə)n]: n. a place where people or animals can live peacefully or go to in order to be safe ⇨ sanctuary避难所
suppress [səˈpres]: v. to stop people from opposing the government, especially by using force镇压,查禁
encyclopedia [ɪnˌsaɪkləˈpidiə] encyclopedist: n. a book or ↑CD, or a set of these, containing facts about many different subjects, or containing detailed facts about one subject百科全书
bourgeois [ˈbʊrˌʒwɑ] bourgeoisie [ˌbʊrʒwɑˈzi]: adj.n. belonging to the ↑middle class中产阶级,资产阶级
widow [ˈwɪdoʊ]: n. a woman whose husband has died and who has not married again寡妇
valet [ˈvæleɪ]: n. a male servant who looks after a man’s clothes, serves his meals etc ⇨ maid(男人的)贴身男仆
ornate [ɔrˈneɪt]: adj. covered with a lot of decoration装饰的, 华丽的
stature [ˈstætʃər]: n. the degree to which someone is admired or regarded as important名声,声望
undue [ʌnˈdu]: adj. formal more than is reasonable, suitable, or necessary过分的
exaggerated [ɪɡˈzædʒəˌreɪtəd]: adj. if something is exaggerated, it is described as better, larger etc than it really is夸大的, 言过其实的
perception [pərˈsepʃən]: n. the way you think about something and your idea of what it is like理解,看法
--------------------
social background: 社会背景
the preserve of sb.: 某人的独有活动
Of great importance to sb. is sth.: 对某人非常重要的是...
come into being: 出现
rise to new heights: reach sb's zenith(顶峰), reach sb's apogee(顶点)上升到新的高度
engage in sth.: 参与某事
center on sth.: 以某事为中心
bring together A with B: 把A和B结合起来
a position to do sth.: 做某事的位置
financial assistance: 经济资助
in secret: 秘密地
in the provinces: 在地方上
** sentence
literate [ˈlɪt(ə)rət]: adj. able to read and write OPP illiterate ⇨ numerate有文化的
- These literate elites had a reputation for charity.
- These literate masses in ancient time created their prosperous civilization.
- The elite who was said to be literate turned out to be a thief.
publication [ˌpʌblɪˈkeɪʃ(ə)n]: n. the process of printing a book, magazine etc and offering it for sale ⇨ publish出版物, 出版
- My manager urged me to develop a system for the management of these publications.
- The bargain hunter is searching for the publications published ten years ago.
- Believe it or not, I am going to dedicate myself to these publications.
treatise [ˈtritɪs]: n. a serious book or article about a particular subject论文
- The professor denounced his rival's errors in his treatise.
- The treatise is full of smell of the urine of rats.
- The warlike pope condemn the scientist's treatises as heresy contrary to the church.
guest [ɡest]: n. someone who is invited to an event or special occasion客人
- It is not appropriate for a guest to enter in the bedroom without permission.
- The guest found the salon full of new ideas of the philosophes. 
- The guest was accused of stealing a rare book.
witty: using words in a clever and amusing way诙谐的
- I used to have witty conversations with him.
- Everyone admires him for his great sense of humor, for he always explains stories to people in a witty fashion.
- Exasperated by these witty words, the pope was determined to suppress these novels.
sparkling: shining brightly with points of flashing light; full of life and intelligence闪烁的;充满生机的
- These sparkling ideas from China inspired awe in the philosophes in Paris.
- I used to pester my father about sparkling fair tales in my youth.
- The pope told the Children Crusade a sparkling story about the lost holy land.
hierarchy [ˈhaɪəˌrɑrki] hierarchical: n.adj. if a system, organization etc is hierarchical, people or things are divided into levels of importance等级的
- Breaking rules will receive punishment in a hierarchical society.
- My wife is always complaining that she lives in a hierarchical society.
- My wife had a difficult time living in a hierarchical family in her youth.
haven [ˈheɪv(ə)n]: n. a place where people or animals can live peacefully or go to in order to be safe ⇨ sanctuary避难所
- The city is fruitful of havens for the refugees in floods.
- The papal authorty promised to offer thousands of havens for those masses whose family members were killed in the crusade.
- The church manifested as haven at the time when I was not able to pay for a hotel room.
suppress [səˈpres]: v. to stop people from opposing the government, especially by using force镇压,查禁
- According to your station, you don't have the authority to suppress my books.
- The books suppressed by the local authorities are full of sexual situations which are not appropriate to be published.
- As the peasant revolts and rebellions died down, the papal authorities reached their apogee in a gradual and piecemeal fashion.
encyclopedia [ɪnˌsaɪkləˈpidiə] encyclopedist: n. a book or ↑CD, or a set of these, containing facts about many different subjects, or containing detailed facts about one subject百科全书
- I failed to sell any encyclopedia before three months passed.
- The seller desperately found Joey could not afford to buy a set of encyclopedias.
- On my six year old birthday, my sister presented me a set of encyclopedias.
bourgeois [ˈbʊrˌʒwɑ] bourgeoisie [ˌbʊrʒwɑˈzi]: adj.n. belonging to the ↑middle class中产阶级,资产阶级
- Her dream of marrying a bourgeoisie almost came true recently.
- Beyond doubt, the salon's greatest appeal is to the bourgeoisies in urban.
- With the emergence of trade in cities, the bourgeoisies in town reached its zenith in a hierarchical society.
widow [ˈwɪdoʊ]: n. a woman whose husband has died and who has not married again寡妇
- Missing her husband, the elegant widow cast stones by the lake.
- The widow is known to be fanatical about holding salons in her house.
- The widow was so well received in Beijing that she thought the position to rise to fame was to be at hand. 
valet [ˈvæleɪ]: n. a male servant who looks after a man’s clothes, serves his meals etc ⇨ maid(男人的)贴身男仆
- Exasperated by the valet, the aristocracy lost control of himself twice yesterday.
- The aristocracy realized to his horror that his father's valet was regarded as the heir of the house.
- Exasperated by his low status in family, the valet tried to poison his master.
ornate [ɔrˈneɪt]: adj. covered with a lot of decoration装饰的, 华丽的
- It is not appropriate for the heir of the throne to live in such an ornate palace.
- Coupled with ornate statues, his house attracted many major figures of philosophes.
- Coupled with ornate paintings, the ceiling gave the pope satisfaction.
stature [ˈstætʃər]: n. the degree to which someone is admired or regarded as important名声,声望
- His stature persuaded the masses to give up attacking the palace.
- Monastery fell into debt under the abbot, which decreased his stature a great deal.
- In spite of his stature, soldiers were reluctant to cross the big plain.
undue [ʌnˈdu]: adj. formal more than is reasonable, suitable, or necessary过分的
- Without undue delay, the plane took off after the examination.
- The house should be cleaned out without undue delay.
- You homework should be completed without undue delay.
exaggerated [ɪɡˈzædʒəˌreɪtəd]: adj. if something is exaggerated, it is described as better, larger etc than it really is夸大的, 言过其实的
- This words proved exaggerated, for there is no puma at large.
- People in the High Middle Ages were attracted by exaggerated literary novels.
- My power is in fact exaggerated, for I don't have the authority to regulate the armies.
perception [pərˈsepʃən]: n. the way you think about something and your idea of what it is like理解,看法
- The perception of my status in social in error brought me a lot of troubles.
- People's perception of ideas from China led to a revolution.
- The mistaken perception of the Pacific Ocean cause him to meet his death at the hands of the local people.
--------------------
social background: 社会背景
- My superior urged me to figure out the social background of the lady in two days' time.
- The artist turned out to have a social background of lower-class.
- People who have social backgrounds of lower-class were forbid to exist in the urban. 
the preserve of sb.: 某人的独有活动
- Playing piano is no longer the preserve of wealthy families in China.
- Calling my daughter Miumiu is the preserve of our couples.
- Wearing a white collar is the preserve of the government officer in the past.
Of great importance to sb. is sth.: 对某人非常重要的是...
- Of great importance to the headmaster is his perception of his teaching.
- Of great importance to your study is what you see of yourself.
- Of great importance to my cat is to feed her up punctually.
come into being: 出现
- After meowing in the whole night, three pussies came into being.
- When he arrived on the scene, a vampire came into being.
- He was exasprated by the officer, a plan of abduction came into being.
rise to new heights: reach sb's zenith(顶峰), reach sb's apogee(顶点)上升到新的高度
- After we moved to the new house, our relationship rose to new heights.
- Wining the prize in the tournament, the team rose to new heights in the religion.
- Defeated by an unknown team and adjusting itself, the team rose to new heights.
engage in sth.: 参与某事
- I am reluctant to engage in the quarrel between you and our superior.
- The layman was astonished to find out that her husband had engaged in the rebellions.
- The journalist found his wife engaged in the scandal in which she had an affair with the officer.
center on sth.: 以某事为中心
- Turning their back on Christian orthodoxy, these intellectuals centered on the ideas of the Scientific Revolution.
- Our debate must center on whether we should buy things that we don't need.
- My wife center on whether I told a lie yesterday.
bring together A with B: 把A和B结合起来
- It is no use bringing together peasants with knight in a hierarchical society.
- An airplane crush brought tougher me with my future husband.
- The distate for the loneliness brought together me with my future wife at a salon.
a position to do sth.: 做某事的位置
- She found her in a position to determine if her mother had paid for it.
- I found myself in a position to quit and study English by myself.
- My cat found a position to enjoy landscape in front of the window.
financial assistance: 经济资助
- Without financial assistance, I might not be able to go to university.
- My aunt offered me financial assistance to obtain perfection.
- The widow offered you financial assistance to complete your work.
in secret: 秘密地
- The famous star couples stayed out of limelight and got divorced in secret.
- She was determined to buy a real estate in other city in secret.
- I was wondering if you had bought a real estate in secret.
in the provinces: 在地方上
- The emperor had a bad reputation in the provinces.
- The emperor doesn't have the privilege to order armies in the provinces.
- The emperor claimed to levy heavy taxes in the provinces.
** sentence2
literate [ˈlɪt(ə)rət]: adj. able to read and write OPP illiterate ⇨ numerate有文化的
- These literate elites had a reputation for charity.
- These literate masses in ancient times created their prosperous civilization.
- The elite who was said to be literate turned out to be a thief.
publication [ˌpʌblɪˈkeɪʃ(ə)n]: n. the process of printing a book, magazine etc and offering it for sale ⇨ publish出版物, 出版
- My manager urged me to develop a system for administrating of these publications.
- The bargain hunter is searching for the publications published ten years ago.
- Believe it or not, I am going to dedicate myself to these publications.
treatise [ˈtritɪs]: n. a serious book or article about a particular subject论文
- The professor denounced his rival's errors in his treatise.
- The treatise is full of the smell of the urine of rats.
- The warlike pope condemns the scientist's treatises as heresy contrary to the church.
guest [ɡest]: n. someone who is invited to an event or special occasion客人
- It is not appropriate for a guest to enter the bedroom without permission.
- The guest found the salon full of new ideas of the philosophes. 
- The guest was accused of stealing a rare book.
witty: using words in a clever and amusing way诙谐的
- I used to have witty conversations with him.
- Everyone admires him for his great sense of humor, for he always explains stories to people in a witty fashion.
- Exasperated by these witty words, the pope was determined to suppress these novels.
sparkling: shining brightly with points of flashing light; full of life and intelligence闪烁的;充满生机的
- These sparkling ideas from China inspired awe in the philosophes in Paris.
- I used to pester my father about sparkling fairy tales in my youth.
- The pope told the Children Crusade a sparkling story about the lost holy land.
hierarchy [ˈhaɪəˌrɑrki] hierarchical: n.adj. if a system, organization etc is hierarchical, people or things are divided into levels of importance等级的
- Breaking rules will cause punishment in a hierarchical society.
- My wife is always complaining that she lives in a hierarchical society.
- My wife had a difficult time living in a hierarchical family in her youth.
haven [ˈheɪv(ə)n]: n. a place where people or animals can live peacefully or go to in order to be safe ⇨ sanctuary避难所
- The city is full of havens for the refugees in floods.
- The papal authority promised to offer thousands of havens for those masses whose family members were killed in the crusade.
- The church manifested as a haven at the time when I was not able to pay for a hotel room.
suppress [səˈpres]: v. to stop people from opposing the government, especially by using force镇压,查禁
- According to your station, you don't have the authority to suppress my books.
- The books suppressed by the local authorities are full of sexual situations that are not appropriate to be published.
- As the peasant revolts and rebellions died down, the papal authorities reached their apogee in a gradual and piecemeal fashion.
encyclopedia [ɪnˌsaɪkləˈpidiə] encyclopedist: n. a book or ↑CD, or a set of these, containing facts about many different subjects, or containing detailed facts about one subject百科全书
- I failed to sell any encyclopedia before three months passed.
- The seller desperately found Joey could not afford to buy a set of encyclopedias.
- On my six-year-old birthday, my sister presented me with a set of encyclopedias.
bourgeois [ˈbʊrˌʒwɑ] bourgeoisie [ˌbʊrʒwɑˈzi]: adj.n. belonging to the ↑middle class中产阶级,资产阶级
- Her dream of marrying a bourgeoisie almost came true recently.
- Beyond doubt, the salon's greatest appeal is to the bourgeoisie in urban.
- With the emergence of trade in cities, the bourgeoisie in town reached its zenith in a hierarchical society.
widow [ˈwɪdoʊ]: n. a woman whose husband has died and who has not married again寡妇
- Missing her husband, the elegant widow cast stones by the lake.
- The widow is known to be fanatical about holding salons in her house.
- The widow was so well received in Beijing that she thought the position to rise to fame was to be at hand. 
valet [ˈvæleɪ]: n. a male servant who looks after a man’s clothes, serves his meals etc ⇨ maid(男人的)贴身男仆
- Exasperated by the valet, the aristocracy lost control of himself twice yesterday.
- The aristocracy realized to his horror that his father's valet was regarded as the heir of the house.
- Exasperated by his low status in the family, the valet tried to poison his master.
ornate [ɔrˈneɪt]: adj. covered with a lot of decoration装饰的, 华丽的
- It is not appropriate for the heir to the throne to live in such an ornate palace.
- Coupled with ornate statues, his house attracted many major figures of philosophes.
- Coupled with ornate paintings, the ceiling gave the pope satisfaction.
stature [ˈstætʃər]: n. the degree to which someone is admired or regarded as important名声,声望
- His stature persuaded the masses to give up attacking the palace.
- The monastery fell into debt under the abbot, which decreased his stature a great deal.
- In spite of his stature, soldiers were reluctant to cross the big plain.
undue [ʌnˈdu]: adj. formal more than is reasonable, suitable, or necessary过分的
- Without undue delay, the plane took off after the examination.
- The house should be cleaned out without undue delay.
- Your homework should be completed without undue delay.
exaggerated [ɪɡˈzædʒəˌreɪtəd]: adj. if something is exaggerated, it is described as better, larger etc than it really is夸大的, 言过其实的
- These words proved exaggerated, for there is no puma at large.
- People in the High Middle Ages were attracted by exaggerated literary novels.
- My power is in fact exaggerated, for I don't have the authority to regulate the armies.
perception [pərˈsepʃən]: n. the way you think about something and your idea of what it is like理解,看法
- The perception of my status in society in error brought me a lot of trouble.
- People's perception of ideas from China led to a revolution.
- The mistaken perception of the Pacific Ocean caused him to meet his death at the hands of the local people.
--------------------
social background: 社会背景
- My superior urged me to figure out the social background of the lady in two days' time.
- The artist turned out to have a social background of lower class.
- People who have social backgrounds of lower class were forbidden to exist in the urban. 
the preserve of sb.: 某人的独有活动
- Playing piano is no longer the preserve of wealthy families in China.
- Calling my daughter Miumiu is the preserve of our couples.
- Wearing a white collar is the preserve of the government officer in the past.
Of great importance to sb. is sth.: 对某人非常重要的是...
- Of great importance to the headmaster is his perception of his teaching.
- Of great importance to your study is what you see of yourself.
- Of great importance to my cat is to feed her punctually.
come into being: 出现
- After meowing in the whole night, three pussies came into being.
- When he arrived on the scene, a vampire came into being.
- He was exasperated by the officer and a plan of abduction came into being.
rise to new heights: reach sb's zenith(顶峰), reach sb's apogee(顶点)上升到新的高度
- After we moved to the new house, our relationship rose to new heights.
- Winning the prize in the tournament, the team rose to new heights in the religion.
- Defeated by an unknown team and adjusting itself, the team rose to new heights.
engage in sth.: 参与某事
- I am reluctant to engage in the quarrel between you and our superior.
- The layman was astonished to find out that her husband had engaged in the rebellions.
- The journalist found his wife engaged in the scandal in which she had an affair with the officer.
center on sth.: 以某事为中心
- Turning their back on Christian orthodoxy, these intellectuals centered on the ideas of the Scientific Revolution.
- Our debate must center on whether we should buy things that we don't need.
- My wife kept on centering on whether I told a lie yesterday.
bring together A with B: 把A和B结合起来
- It is no use bringing together peasants with knights in a hierarchical society.
- An airplane crash brought tougher me with my future husband.
- The distaste for the loneliness brought together me with my future wife at a salon.
a position to do sth.: 做某事的位置
- She found herself in a position to determine if her mother had paid for it.
- I found myself in a position to quit and study English by myself.
- My cat found a position to enjoy the landscape in front of the window.
financial assistance: 经济资助
- Without financial assistance, I might not be able to go to university.
- My aunt offered me financial assistance to obtain perfection.
- The widow offered you financial assistance to complete your work.
in secret: 秘密地
- The famous star couples stayed out of the limelight and got divorced in secret.
- She was determined to buy real estate in another city in secret.
- I was wondering if you had bought real estate in secret.
in the provinces: 在地方上
- The emperor had a bad reputation in the provinces.
- The emperor doesn't have the privilege to order armies in the provinces.
- The emperor claimed to levy heavy taxes in the provinces.
** summary
Although the Enlightment was not the perserve of any one class,
	obviously it greatly appealed to the aristocracy and the upper-middle-class
		and little affected the common people, especially peasants.
Not only the publication and the sales of books and treatises
		were important to the spread of the ideas of the Enlightment,
	but salons,
		which brought together writers and artists
			with aristocrats, government officials, and wealthy members of the bourgeoisie
				in France's rigid hierarchical society,
		was also a factor.
As hostesses of the salons, women often had chances to affect politics, arts, and literature.
They also provided havens for those ideas unwelcome by the authorities.
French and foreign observers complained
	that women exerted undue influence in French political affairs.
It was obvioulsy exaggerated,
	for even though salons were run by women, the reputation of a salon depend on the philosphes.
However, it led the decline of salons during the French Revolution toward the end of the century.
** summary2
Although the Enlightenment was not the perserve of any one class,
	it greatly appealed to the aristocracy and the upper-middle-class
		and little affected the common people, especially peasants.
Not only the publication and the sales of books and treatises
		were important to the spread of the ideas of the Enlightenment,
	but the salon,
		which brought together writers and artists
			with aristocrats, government officials, and wealthy members of the bourgeoisie
				in France's rigid hierarchical society,
		was also a factor.
As hostesses of the salons, women often had chances to affect politics, arts, and literature.
They also provided havens for those ideas suppressed by the authorities.
French and foreign observers complained
	that women exerted undue influence in French political affairs.
It was exaggerated because even though salons were run by women,
	the reputation of a salon depended on the philosophes.
However, it led to the decline of salons
	during the French Revolution toward the end of the century.
