#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 18 The eighteenth century that historians define
#+begin_verse
Historians often define the eighteenth century as the years from 1715 to 1789.
Politically, this makes sense,
	because 1715 marks the end of the age of Louis XIV
		and 1789 was the year in which the French Revolution erupted.
This period has often been portrayed as the final phase of Europe’s old order,
	swept away by the violent upheaval and reordering of society
		associated with the French Revolution.
Europe’s old order, still largely agrarian,
		dominated by kings and landed aristocrats,
		and grounded in privileges for nobles, clergy, towns, and provinces,
	seemed to continue a basic pattern that had prevailed in Europe since medieval times.
But new ideas and practices were beginning to emerge.
Just as a new intellectual order based on rationalism and secularism
		was evolving from the Scientific Revolution and the Enlightenment,
	demographic, economic, and social patterns were beginning to change in ways
		that heralded the emergence of a modern new order.

The ideas of the Enlightenment seemed to proclaim a new political age as well.
Catherine the Great, who ruled Russia from 1762 to 1796, wrote to Voltaire:
	'Since 1746 I have been under the greatest obligations to you.
	Before that period I read nothing but romances, but by chance your works fell into my hands,
		and ever since then I have never ceased to read them,
			and have no desire for books less well written than yours, or less instructive.'
The empress also invited Diderot to Russia and,
	when he arrived, urged him to speak frankly as man to man.
Diderot did, offering her advice for a far-ranging program of political and financial reform.
But Catherine's apparent eagerness to make enlightened reforms was tempered by skepticism.
She said of Diderot,
	'If I had believed him, everything would have been turned upside down in my kingdom;
	legislation, administration, finance--
		all would have been turned topsy-turvy to make room for impractical theories.'
For Catherine, enlightened reform remained more a dream than a reality,
	and in the end, the waging of wars to gain more power was more important.

In the eighteenth century,
	the process of centralization
			that had characterized the growth of states since the Middle Ages continued
	as most European states enlarged their bureaucratic machinery and consolidated their governments
		in order to collect the revenues and build the armies
			they needed to compete militarily with the other European states.
International competition continued to be the favorite pastime of eighteenth-century rulers.
Within the European state system,
	the nations that would dominate Europe until World War I
		--Britain, France, Austria, Prussia, and Russia--
		emerged as the five great powers of Europe.
Their rivalries led to major wars.
In the midst of this state building and warmaking,
	dramatic demographic, economic, and social changes
		gave rise to a radical transformation in the way Europeans would raise food and produce goods.
#+end_verse
** expression
phase [feɪz]: n. one of the stages of a process of development or change阶段
reorder [ˌriˈɔrdər]: v. to change the way that things are ordered or arranged重新排序,重新安排
prevail [prɪˈveɪl]: v. if a belief, custom, situation etc prevails, it exists among a group of people at a certain time流行, 盛行
rational [ˈræʃ(ə)nəl] rationalism: adj.n. rational thoughts, decisions etc are based on reasons rather than emotions OPP irrational
demographic [ˌdeməˈɡræfɪk]: adj. information about a group such as the people who live in a particular area人口统计学的
herald [ˈherəld]: v. to be a sign of something that is going to come or happen soon预报
instructive [ɪnˈstrʌktɪv]: adj. providing a lot of useful information SYN informative教育性的
frankly [ˈfræŋkli]: adv. used to show that you are saying what you really think about something坦白地, 真诚地
temper [ˈtempər]: v. formal to make something less severe or extreme调和, 调节
skepticism [ˈskeptɪˌsɪzəm]: n. an attitude of doubting that particular claims or statements are true or that something will happen怀疑论
legislate [ˈledʒɪˌsleɪt] legislation: v.n. a law or set of laws立法
topsy-turvy [tɑːpsi ˈtɜːrvi]: adj. in a state of complete disorder or confusion颠倒地, 乱七八糟地
enlarge [ɪnˈlɑrdʒ]: v. if you enlarge something, or if it enlarges, it increases in size or scale扩大, 放大
bureaucracy [bjəˈrɑkrəsi] bureaucratic: n.adj. involving a lot of complicated official rules and processes官僚政治的
consolidate [kənˈsɑlɪˌdeɪt]: v. to strengthen the position of power or success that you have, so that it becomes more effective or continues for longer巩固
revenue [ˈrevənju]: n. money that a business or organization receives over a period of time, especially from selling goods or services ⇨ income收入,税收
pastime [ˈpæsˌtaɪm]: n. something that you do because you think it is enjoyable or interesting ⇨ hobby消遣, 娱乐
rivalry [ˈraɪv(ə)lri]: n. a situation in which two or more people, teams, or companies are competing for something, especially over a long period of time, and the feeling of competition between them ⇨ competition竞争
transform [trænsˈfɔrm] transformation: v.n. a complete change in someone or something改变,改革
--------------------
define A as B: 定义A为B
mark the end of sth.: 标志着某事物的结束
portray A as B: 描绘A为B
be swept away by sth.: 被某事物冲走
nothing but sth.: 只有某物
fall into sb's hands: 落入某人的手中
have no desire for sth.: 对于某事物没有渴望
advice for sth.: 对于某事物的建议
turn upside down: 颠倒过来了
make room for sth.: 为某事物腾出空间
wage war: 发动战争
** sentence
phase [feɪz]: n. one of the stages of a process of development or change阶段
- He is taking a new drug that is still in experimental phase.
- The drug in experimental phase seems to have catastrophic side effects.
- Our new drug is stil in experimental phase, so we will delay in launching it.
reorder [ˌriˈɔrdər]: v. to change the way that things are ordered or arranged重新排序,重新安排
- Your room got into such a mess that you have to reorder everything before the fancy dress party.
- Without undue delay, he reorder his roof after his mattress had been swept off.
- His mother always complains that she has to reorder his room twice a week.
prevail [prɪˈveɪl]: v. if a belief, custom, situation etc prevails, it exists among a group of people at a certain time流行, 盛行
- When you return to your home, you will find fancy dress parties prevailing in the town.
- The box prevail in the masses of the major cities, for the prizefighter brought science to it.
- The new drug that help people lose their weight is supposed to prevail in no long future.
rational [ˈræʃ(ə)nəl] rationalism: adj.n. rational thoughts, decisions etc are based on reasons rather than emotions OPP irrational
- He made a rational decision that he stamped out the letters 'SOS' on the desert island.
- Failing to make rational decisions, the empoper instructed his men to sack the city which led to another war.
- Failing to make rational decisions, my wife investigated mental industry with which she as unfamiliar. 
demographic [ˌdeməˈɡræfɪk]: adj. information about a group such as the people who live in a particular area人口统计学的
- Demographic trends show that there is increasing number of people in China.
- The official realized to his horror that demographic trends show people are increasingly unwilling to bear children.
- The demographic changes in China have made houses difficult to be sold.
herald [ˈherəld]: v. to be a sign of something that is going to come or happen soon预报
- He slamed the door, which heralded a bitter quarrel between he and his wife.
- The number of bugs you made in the project heralds your salary.
- The stream wounded its way across the field, which herald the harvesting in this year.
instructive [ɪnˈstrʌktɪv]: adj. providing a lot of useful information SYN informative教育性的
- The instructive books that weakened the exalted claim of papel authority at last were suppressed.
- The manual proved instructive, for it benifits me in all my life.
- His bedroom is full of instructive books.
frankly [ˈfræŋkli]: adv. used to show that you are saying what you really think about something坦白地, 真诚地
- People are always asking you to talk to them frankly before they turn you in.
- Let's have a conversation frankly. Why did you mend window at midnight?
- I brought together you and your husband to let you communicate with each other frankly.
temper [ˈtempər]: v. formal to make something less severe or extreme缓和
- His angry must be tempered with an elaborated present.
- My embarrassment was tempered with the announcer's slip of the tongue.
- The hard time getting to work has been tempered with these expert students who volunteer to drive buses. 
skepticism [ˈskeptɪˌsɪzəm]: n. an attitude of doubting that particular claims or statements are true or that something will happen怀疑论
- As the religious faith and passions were replaced by skepticism, the salons in which people centered on the ideas of philosphes prevailed.
- At last skepticism took precedence over the religious passions because of the spread of the Scientific Revolution.
- The skepticism was emerging at a time when people were obsessed with the outside world depicted in travel logs.
legislate [ˈledʒɪˌsleɪt] legislation: v.n. a law or set of laws立法
- The House of Lords proclaimed that the legislation rights belonged to the Parliament, not the king.
- The king competed legislation with the Parliament after wars.
- The legislation about the abortion led to the increase of pregnancy rate in teenagers.
topsy-turvy [tɑːpsi ˈtɜːrvi]: adj. in a state of complete disorder or confusion颠倒地, 乱七八糟地
- The project is so topsy-turvy that I can not figure out where to begin.
- The items of our cat is so topsy-turvy that I have to reorder them.
- The servants went on strike, which caused my house hopsy-turvy.
enlarge [ɪnˈlɑrdʒ]: v. if you enlarge something, or if it enlarges, it increases in size or scale扩大, 放大
- She is eager to have an operation to enlarge her breast.
- The star denied that she had an operation to enlarge her breast.
- This kind of operation to enlarge women's breats prevail in Korea overnight.
bureaucracy [bjəˈrɑkrəsi] bureaucratic: n.adj. involving a lot of complicated official rules and processes官僚政治的
- The breakdown of trust in bureaucracy of the state heralded a series of disasters.
- A series of revailed scandals led to the breakdown of trust in bureaucracy.
- The bureaucratic office has been burned down by the masses out of rage.
consolidate [kənˈsɑlɪˌdeɪt]: v. to strengthen the position of power or success that you have, so that it becomes more effective or continues for longer巩固
- If you had consolidated what you learned last week, you would have passed the test.
- Losing control of four provinces, the empepor had the nerve to consolidate his power.
- Failing to consolidate his domestic power, the empepor waged war against his neighbor.
revenue [ˈrevənju]: n. money that a business or organization receives over a period of time, especially from selling goods or services ⇨ income收入,税收
- The empepor pointed out that the trade in cities was a source of revenue.
- It looked as if the monarchs couldn't have tax revenues without the Parliament.
- The masses began to complain about the increase of tax revenues.
pastime [ˈpæsˌtaɪm]: n. something that you do because you think it is enjoyable or interesting ⇨ hobby消遣, 娱乐
- Technically, reading was my favourite pastime in my youth.
- People adored the writer, for his pastime was speaking in public to spread new ideas from the philosophes.
- His pastime, writing pirate stories, makes him earn a large sum of money.
rivalry [ˈraɪv(ə)lri]: n. a situation in which two or more people, teams, or companies are competing for something, especially over a long period of time, and the feeling of competition between them ⇨ competition竞争
- The rivalry between me and my neighbor is becoming dramatic recently.
- There must be a rivalry between two popes which was a real spectacle.
- The rivalry between the brothers turned out to be a waste of time.
transform [trænsˈfɔrm] transformation: v.n. a complete change in someone or something改变,改革
- I had a difficult time transforming those data into string format.
- Transforming 3 dollars into candies, he was punished by his carelessness.
- While he was transforming the pastry into pie, his wife slammed the door all of a sudden.
--------------------
define A as B: 定义A为B
- She is always defining my care as brutal spying, which hurts me a great deal.
- No wonder she defined your approach as a fight, for you was dressed in red dress.
- She defined the quarrel as the sign of the divorce and asked the detective to spy on her husband.
mark the end of sth.: 标志着某事物的结束
- The revealed scandal marked the end of the president's power.
- My departure marked the end of the reception.
- The loss of this boat marked the end of the age of the sailboat.
portray A as B: 描绘A为B
- Portaried as a normal phenomenon, experts from the zoo didn't take it seriously.
- Portaried as an insanity, I have been confined to the hospital for twenty years.
- Portaried as a fortune-teller, she predicted that the girl's dream would come true soon.
be swept away by sth.: 被某事物冲走
- As the soil was being swept away by the wind, the hill threatened surrounding villages.
- His items were swept away by the water on the desert island at a wet midnight.
- The mattressed must have been swept by the wind on the roof.
nothing but sth.: 只有某物
- I spent the whole day reading nothing but the history book.
- The servant cooked nothing but the pie that tasted awful.
- She admires him for nothing but the independence of his sentiment.
fall into sb's hands: 落入某人的手中
- Once falling into my hands, you will meet your death.
- Falling into your hands marked the end of my country.
- Falling into the hands of his enemy, he was kept in hiding for twenty years.
have no desire for sth.: 对于某事物没有渴望
- It is no use putting me out of business, for I have no disire for fame and wealth.
- Staying out of the limelight, the actor apparently has no desire for fame and wealth.
- She must have no desire for perfect body.
advice for sth.: 对于某事物的建议
- The philosophe was eager to offer his advice for the legislation of the state.
- His advice for the source of revenues proved impractical.
- The empepor neglected the practical advice for new revenues from the lower class, especially peasants.
turn upside down: 颠倒过来了
- When everything I sorted turned upside down, I got very angry.
- Everything turned upside down, the faith and worship were replaced by reason.
- The child noticed everything in the mirror turned upside down.
make room for sth.: 为某事物腾出空间
- If you want to make money, you must make room for your development.
- She was able to make room for her study.
- He was reluctant to make room for our fancy party.
wage war: 发动战争
- Thousands of thousands of people were transformed into refugees because you waged war.
- The president proclaimed that he would wage war if the NATO didn't stop the supply of weapons to his enemies.
- The warlike general was always waging war.
** sentence2
phase [feɪz]: n. one of the stages of a process of development or change阶段
- He is taking a new drug that is still in the experimental phase.
- The drug in the experimental phase seems to have catastrophic side effects.
- Our new drug is still in the experimental phase, so we will delay in launching it.
reorder [ˌriˈɔrdər]: v. to change the way that things are ordered or arranged重新排序,重新安排
- Your room got into such a mess that you have to reorder everything before the fancy dress party.
- Without undue delay, he reordered his roof after his mattress had been swept off.
- His mother always complains that she has to reorder his room twice a week.
prevail [prɪˈveɪl]: v. if a belief, custom, situation etc prevails, it exists among a group of people at a certain time流行, 盛行
- When you return to your home, you will find fancy dress parties prevailing in the town.
- The box prevailed in the masses of the major cities, for the prizefighter brought science to it.
- The new drug that help people lose their weight is supposed to prevail in no long future.
rational [ˈræʃ(ə)nəl] rationalism: adj.n. rational thoughts, decisions etc are based on reasons rather than emotions OPP irrational
- He made a rational decision that he stamp out the letters 'SOS' on the desert island.
- Failing to make rational decisions, the emperor instructed his men to sack the city which led to another war.
- Failing to make rational decisions, my wife investigated the mental industry with which she was unfamiliar. 
demographic [ˌdeməˈɡræfɪk]: adj. information about a group such as the people who live in a particular area人口统计学的
- Demographic trends show that there is an increasing number of old people in China.
- The official realized to his horror that demographic trends show people are increasingly unwilling to bear children.
- The demographic changes in China have made houses difficult to sell.
herald [ˈherəld]: v. to be a sign of something that is going to come or happen soon预报
- He slammed the door, which heralded a bitter quarrel between him and his wife.
- The number of bugs you made in the project heralds your salary.
- The stream wounded its way across the field, which heralded the harvesting of this year.
instructive [ɪnˈstrʌktɪv]: adj. providing a lot of useful information SYN informative教育性的
- The instructive books that weakened the exalted claim of papal authority at last were suppressed.
- The manual proved instructive, for it benefits me in all my life.
- His bedroom is full of instructive books.
frankly [ˈfræŋkli]: adv. used to show that you are saying what you really think about something坦白地, 真诚地
- People are always asking you to talk to them frankly before they turn you in.
- Let's have a conversation frankly. Why did you mend windows at midnight?
- I brought together you and your husband to let you communicate with each other frankly.
temper [ˈtempər]: v. formal to make something less severe or extreme缓和
- His anger must be tempered with the elaborate present.
- My embarrassment was tempered with the announcer's slip of the tongue.
- The hard time getting to work has been tempered with these expert students who volunteer to drive buses. 
skepticism [ˈskeptɪˌsɪzəm]: n. an attitude of doubting that particular claims or statements are true or that something will happen怀疑论
- As religious faith and passions were replaced by skepticism, the salons in which people centered on the ideas of philosophes prevailed.
- At last, skepticism took precedence over religious passions because of the spread of the Scientific Revolution.
- The skepticism was emerging at a time when people were obsessed with the outside world depicted in travel logs.
legislate [ˈledʒɪˌsleɪt] legislation: v.n. a law or set of laws立法
- The House of Lords proclaimed that the legislation rights belonged to the Parliament, not the king.
- The king claimed to have the authority to legislate through the Parliament after wars.
- The legislation about abortion led to an increase in the pregnancy rate in teenagers.
topsy-turvy [tɑːpsi ˈtɜːrvi]: adj. in a state of complete disorder or confusion颠倒地, 乱七八糟地
- The project is so topsy-turvy that I can not figure out where to begin.
- The items of our cat are so topsy-turvy that I have to reorder them.
- The servants went on strike, which caused my house topsy-turvy.
enlarge [ɪnˈlɑrdʒ]: v. if you enlarge something, or if it enlarges, it increases in size or scale扩大, 放大
- She is eager to have an operation to enlarge her breast.
- The star denied that she had an operation to enlarge her breast.
- This kind of operation to enlarge women's breasts prevails in Korea overnight.
bureaucracy [bjəˈrɑkrəsi] bureaucratic: n.adj. involving a lot of complicated official rules and processes官僚政治的
- The breakdown of trust in the bureaucracy of the state heralded a series of disasters.
- A series of revealed scandals led to the breakdown of trust in bureaucracy.
- The bureaucratic office has been burned down by the masses out of rage.
consolidate [kənˈsɑlɪˌdeɪt]: v. to strengthen the position of power or success that you have, so that it becomes more effective or continues for longer巩固
- If you had consolidated what you learned last week, you would have passed the test.
- Losing control of four provinces, the emperor had the nerve to consolidate his power.
- Failing to consolidate his domestic power, the emperor waged war against his neighbor.
revenue [ˈrevənju]: n. money that a business or organization receives over a period of time, especially from selling goods or services ⇨ income收入,税收
- The emperor pointed out that the trade in cities was a source of revenue.
- It looked as if the monarchs couldn't have tax revenues without the Parliament.
- The masses began to complain about the increase in tax revenues.
pastime [ˈpæsˌtaɪm]: n. something that you do because you think it is enjoyable or interesting ⇨ hobby消遣, 娱乐
- Technically, reading was my favorite pastime in my youth.
- People adored the writer, for his pastime was speaking in public to spread new ideas from the philosophes.
- His pastime, writing pirate stories, makes him earn a large sum of money.
rivalry [ˈraɪv(ə)lri]: n. a situation in which two or more people, teams, or companies are competing for something, especially over a long period of time, and the feeling of competition between them ⇨ competition竞争
- The rivalry between me and my neighbor became dramatic recently.
- There must be a rivalry between the two popes which was a real spectacle.
- The rivalry between the brothers turned out to be a waste of time.
transform [trænsˈfɔrm] transformation: v.n. a complete change in someone or something改变,改革
- I had a difficult time transforming those data into string format.
- Transforming 3 dollars into candies, he was punished for his carelessness.
- While he was transforming the pastry into pies, his wife slammed the door all of a sudden.
--------------------
define A as B: 定义A为B
- She is always defining my care as brutal spying, which hurts me a great deal.
- No wonder she defined your approach as a fight, for you were dressed in a red dress.
- She defined the quarrel as the sign of the divorce and asked the detective to spy on her husband.
mark the end of sth.: 标志着某事物的结束
- The revealed scandal marked the end of the president's power.
- My departure marked the end of the reception.
- The loss of this boat marked the end of the age of the sailboat.
portray A as B: 描绘A为B
- Portrayed as a normal phenomenon, experts from the zoo didn't take it seriously.
- Portrayed as insanity, I have been confined to the hospital for twenty years.
- Portrayed as a fortune-teller, she predicted that the girl's dream would come true soon.
be swept away by sth.: 被某事物冲走
- As the soil was being swept away by the wind, the hill threatened the surrounding villages.
- His items were swept away by the water on the desert island at a wet midnight.
- The mattressed must have been swept by the wind on the roof.
nothing but sth.: 只有某物
- I spent the whole day reading nothing but the history book.
- The servant cooked nothing but the pie that tasted awful.
- She admires him for nothing but the independence of his sentiment.
fall into sb's hands: 落入某人的手中
- Once falling into my hands, you will meet your death.
- Falling into your hands marked the end of my country.
- Falling into the hands of his enemy, he was kept in hiding for twenty years.
have no desire for sth.: 对于某事物没有渴望
- It is no use putting me out of business, for I have no desire for fame and wealth.
- Staying out of the limelight, the actor apparently has no desire for fame and wealth.
- She must have no desire for the perfect body.
advice for sth.: 对于某事物的建议
- The philosophe was eager to offer his advice for the legislation of the state.
- His advice for the source of revenues proved impractical.
- The emperor neglected the practical advice for new revenues from the lower class, especially peasants.
turn upside down: 颠倒过来了
- When everything I sorted turned upside down, I got very angry.
- Everything turned upside down, the faith and worship were replaced by reason.
- The child noticed everything in the mirror turned upside down.
make room for sth.: 为某事物腾出空间
- If you want to make money, you must make room for your development.
- She was able to make room for her study.
- He was reluctant to make room for our fancy party.
wage war: 发动战争
- Thousands of thousands of people were transformed into refugees because you waged war.
- The president proclaimed that he would wage war if NATO didn't stop the supply of weapons to his enemies.
- The warlike general was always waging war.
** summary
The eighteenth century was politically defined as the years from 1715 to 1789,
	because in 1715 the age of Louis XIV ended and in 1789 the French Revolution erupted.
Europe's old order seemed to continue its patterns since medieval time,
	but a new intellectual order was evolving from the Scientific Revolution and the Englightenment.
The ideas of the Englightenment seemed to proclaim a new political age as well.
Catherine the Great wrote to Voltaire
	that she had never ceased to ream his works since she met them
		and had no desire for book less well written than his, or less instructive.
Besides, she invited Diderot to offer her advice
	for a far-ranging program of polictical and financial reform.
Diderot did, but she thought of the reform is so unrealistic that it would mess up her kingdom.
In the eighteenth century,
	the European states enlarged their bureaucratic machinery and consolidated their governments.
They collected the revenues and built the armies
	to compete militarily with the other European states.
Moreover, dramatic demographic, economic,
	and social changes led Europeans to raise food and produce goods.
** summary2
The eighteenth century was politically defined as the years from 1715 to 1789,
	as in 1715 the age of Louis XIV ended and in 1789 the French Revolution erupted.
Europe's old order seemed to continue its patterns since medieval times,
	but a new intellectual order was evolving from the Scientific Revolution and the Enlightenment.
The ideas of the Enlightenment seemed to proclaim a new political age as well.
Catherine the Great wrote to Voltaire
	that she had never ceased to read his works since she met them
		and had no desire for books less well written than his, or less instructive.
Besides, she invited Diderot to offer her
	advice for a far-ranging program of political and financial reform.
Diderot did, but she thought the reform was so unrealistic that it would mess up her kingdom.
In the eighteenth century,
	the European states enlarged their bureaucratic machinery and consolidated their governments.
They collected revenues and built armies
	to compete militarily with the other European states.
Moreover, dramatic demographic, economic,
	and social changes led Europeans to raise food and produce goods.
