#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 19 The French Revolution
#+begin_verse
On the morning of July 14, 1789,
	a Parisian mob of some eight thousand people in search of weapons streamed toward the Bastille,
		a royal armory filled with arms and ammunition.
The Bastille was also a state prison,
	and although it now contained only seven prisoners,
	in the eyes of these angry Parisians
		it was a glaring symbol of the government's despotic policies.
The armory was defended by the marquis de Launay and a small garrison of 114 men.
The attack began in earnest in the early afternoon,
	and after three hours of fighting, de Launay and the garrison surrendered.
Angered by the loss of ninety-eight of their members,
	the victorious mob beat de Launay to death, cut off his head,
		and carried it aloft in triumph through the streets of Paris.
When King Louis XVI was informed of the fall of the Bastille by the duke,
	he exclaimed, 'Why, this is a revolt.'
'No, Sire,' replied the duke, 'it is a revolution.'

Historians have long held
	that the modern history of Europe began with two significant transformations
	---the French Revolution and the Industrial Revolution.
Accordingly, the French Revolution has been portrayed as
		the major turning point	in European political and social history
	when the institutions of the 'old regime' were destroyed
	and a new order was created based on individual rights, representative institutions,
		and a concept of loyalty to the nation rather than the monarch.
This perspective has certain limitations, however.

France was only one of a number of places in the Western world
	where the assumptions of the old order were challenged.
Although some historians have used the phrase 'democratic revolution'
		to refer to the upheavals of the late eighteenth and nineteenth centuries,
	it is probably more appropriate to speak not of a democratic movement but of a liberal movement
			to extend political rights and power to the bourgeoisie 'possessing capital,'
		people not of the aristocracy
			who were literate
				and had become wealthy through capitalist enterprises in trade, industry, and finance.
The years preceding and accompanying the French Revolution
	included attempts at reform and revolt in the North American colonies,
		Britain, the Dutch Republic, some Swiss cities, and the Austrian Netherlands.
The success of the American and French Revolutions
	makes them the center of attention for this chapter.
Not all of the decadent privileges that characterized the old European regime
	were destroyed in 1789, however.
The revolutionary upheaval of the era, especially in France,
	did create new liberal and national political ideals,
		summarized in the French revolutionary slogan, 'Liberty, Equality, Fraternity,'
			that transformed France
				and were then spread to other European countries through the conquests of Napoleon.
#+end_verse
** expression
mob [mɑb]: n. a large noisy crowd, especially one that is angry and violent暴徒
armory [ˈɑrməri]: n. a place where weapons are stored军械库
ammunition [ˌæmjəˈnɪʃ(ə)n]: n. bullets, shells (↑shell) etc that are fired from guns军火, 弹药
glaring [ˈɡlerɪŋ]: adj. very bad and very noticeable SYN obvious刺眼的
despot [ˈdeˌspɑt] despotic: n.adj. someone, especially a ruler, who uses power in a cruel and unfair way SYN tyrant暴君
policy [ˈpɑləsi]: n. a way of doing something that has been officially agreed and chosen by a political party, a business, or another organization政策, 方针
garrison [ˈɡerɪs(ə)n]: n. a group of soldiers living in a town or ↑fort and defending it卫戍部队, 驻军
surrender [səˈrendər]: v. to say officially that you want to stop fighting, because you realize that you cannot win投降, 自首
victorious [vɪkˈtɔriəs]: adj. having won a victory, or ending in a victory获胜的, 胜利的
aloft [əˈlɔft]: adv. high up in the air在高处
regime [reɪˈʒim]: n. a government, especially one that was not elected fairly or that you disapprove of for some other reason政权
loyalty [ˈlɔɪəlti]: n. the quality of remaining faithful to your friends, principles, country etc忠诚, 忠心
democracy [dɪˈmɑkrəsi] democratic: n.adj. a system of government in which every citizen in the country can vote to elect its government officials民主政治, 民主主义
capital [ˈkæpɪt(ə)l]: n. money or property, especially when it is used to start a business or to produce more wealth资本
precede [prɪˈsid] preceding: v.adj. to happen or exist before something or someone, or to come before something else in a series ⇨ preceding先于
decadent [ˈdekədənt]: adj. having low moral standards and being more concerned with pleasure than serious matters颓废的
slogan [ˈsloʊɡən]: n. a short phrase that is easy to remember and is used in advertisements, or by politicians, organizations etc ⇨ catchphrase口号
fraternity [frəˈtɜrnəti]: n. the teaching/scientific/criminal etc fraternity all the people who work in a particular profession or share a particular interest博爱
--------------------
be filled with sth.: 充满了某物
in the eyes of sb.: 在某人的眼中
be angered by sth./sb.: 被某人某事所激怒
beat sb. to death: 打死某人
cut off sth.: 切断某物
in triumph: 凯旋地
sb. holds that + ...: 某人认为+...
Accordingly, + ...: 因此, +...
extend rights and power to sb.: 赋予某人权利和权力
the center of attention: focus 注意力中心
** sentence
mob [mɑb]: n. a large noisy crowd, especially one that is angry and violent暴徒
- The king waked up with a start hearting noises from the mob at midnight.
- A mob of thousands of busmen went on strike gathering around the Town Hall.
- A mob of hundreds o feasants streamed toward the museum and held up the traffic.
armory [ˈɑrməri]: n. a place where weapons are stored军械库
- There is a suspicious foreigner spying on the entrance of the armory.
- Two theives were beaten to death breaking into the armory.
- Waking up with a start, he realized to his horror that the armory was being defended by his inferiors.
ammunition [ˌæmjəˈnɪʃ(ə)n]: n. bullets, shells (↑shell) etc that are fired from guns军火, 弹药
- There is no shortage of ammunition in the South Africa.
- Short of ammunition, the general was killed in action.
- Short of ammunition, the regiment asked the king to check the armory.
glaring [ˈɡlerɪŋ]: adj. very bad and very noticeable SYN obvious刺眼的
- She could not bear the glaring tattoo on her face anymore.
- If you noticed the glaring sign on the wall, you wouldn't get a ticket in our city.
- The glaring scars on my face are reminding me of the injuries of the Black Death.
despot [ˈdeˌspɑt] despotic: n.adj. someone, especially a ruler, who uses power in a cruel and unfair way SYN tyrant暴君
- The despot is reminiscing about his dead wife.
- An eager is swirling around the despot who got very angry.
- The despotic law was rejected by the colonies and they declared their independence from the empire.
policy [ˈpɑləsi]: n. a way of doing something that has been officially agreed and chosen by a political party, a business, or another organization政策, 方针
- Obviously, the political policies and social changes led to the decrease brith rate in towns.
- The emperor was eager to put forward the policies: the state sacrificed money for more lands.
- These policies would turn upside down everything in my kingdom.
garrison [ˈɡerɪs(ə)n]: n. a group of soldiers living in a town or ↑fort and defending it卫戍部队, 驻军
- The garrison short of ammunition is easy to be defeated.
- The garrison joined in the war using their behaviors to swear their loyalty to the king.
- The garrison proved undisciplined, for there were so many drunks when the king checked it.
surrender [səˈrendər]: v. to say officially that you want to stop fighting, because you realize that you cannot win投降, 自首
- Even though the general surrenderred at the beginning of the battle, he had his head cut off by the mob.
- It is no use surrenderring because you will meet your death at the hands of our enemies.
- Portrayed as a gangster by his domestic political enemies, the warlike knight decided to betray his lord.
victorious [vɪkˈtɔriəs]: adj. having won a victory, or ending in a victory获胜的, 胜利的
- The victorious group must have planned out everything to the last detail.
- Equipped with new machine, the victorious group of explorers succeeded in finding buried treasures.
- The war reported being victorious, which brought a smile to the despot in the celebration.
aloft [əˈlɔft]: adv. high up in the air在高处
- The paw prints were snatched by my cat when I held her aloft.
- The victorious team held their coach aloft to express their pleasure.
- The balloon flying aloft can be a great threat to our aircraft.
regime [reɪˈʒim]: n. a government, especially one that was not elected fairly or that you disapprove of for some other reason政权
- The brutal regime drew up a set of laws prohibiting the freedom of speech and press.
- The brutal regime levied heavy taxes on those peasant who struggled for living.
- The brutal regime was short-living, with the breakdown of people's trust in it.
loyalty [ˈlɔɪəlti]: n. the quality of remaining faithful to your friends, principles, country etc忠诚, 忠心
- He didn't cheat on me when meeting the gorgeous widow, which proved his loyalty to our family.
- To prove his loyalty to their love, he jumped from the 19th floor of their apartment.
- The warlike knight swore his loyalty to his princess whom he resque from the revolt.
democracy [dɪˈmɑkrəsi] democratic: n.adj. a system of government in which every citizen in the country can vote to elect its government officials民主政治, 民主主义
- For Catherine the Great, democratic reforms remained more a dream than a reality.
- Diderot offered frankly her advice for a democratic program of political and financial reform.
- Despite democratic policies inside, the king built armies to compete militarily with other European states.
capital [ˈkæpɪt(ə)l]: n. money or property, especially when it is used to start a business or to produce more wealth资本
- Failing to attract the foreign capital, a great number of masses in this country lived in poverty.
- The Prime Minister, refered to as the Magnificent, was expert attracting foreign capital.
- The terrorist attack in Shenzhen repelled some foreign capital from China.
precede [prɪˈsid] preceding: v.adj. to happen or exist before something or someone, or to come before something else in a series ⇨ preceding先于
- My departure preceded your arrival, so I have no chance to steal your ring at the party.
- The preceding gift indeed gave me a surprise.
- The preceding terrorist abduction in America inspired awe in people the world over.
decadent [ˈdekədənt]: adj. having low moral standards and being more concerned with pleasure than serious matters颓废的
- Decandent I sat in a boat and did nothing at all.
- She pointed out that the monarchs were so decadent that they couldn't defend our subject against these Asisa nomads.
- On arriving his house, he was condemned as a decadent waste by his family.
slogan [ˈsloʊɡən]: n. a short phrase that is easy to remember and is used in advertisements, or by politicians, organizations etc ⇨ catchphrase口号
- The former Prime Minister is fanatical about inventing various slogans.
- The king was stunned by these terrifying slogans which heralded the emergence of another revolt.
- He pointed out that the slogan constituted a slip of the tong.
fraternity [frəˈtɜrnəti]: n. the teaching/scientific/criminal etc fraternity all the people who work in a particular profession or share a particular interest博爱
- The ideas of fraternity was spread through the French soldiers to the continent.
- The family full of fraternity was accused of the participation of the rebellion.
- The family full of fraternity is very strong in this village.
--------------------
be filled with sth.: 充满了某物
- Filled with wool, this kind of pillow became popular with peasants in China.
- Filled with sand and stones, the parcel was supposed to be full of diamonds.
- Filled with water, the car broke down in the highway.
in the eyes of sb.: 在某人的眼中
- I might be one of the kindest human being in the eyes of my cat.
- My cat is full of fascination in the eyes of my wife.
- The stary dog must be gorgeous in the eyes of my wife who decided to give him a home.
be angered by sth./sb.: 被某人某事所激怒
- Angered by decadent knights, the king established a law prohibiting drinking too much in the tavern.
- Angered by the heresy, the pope crucified them and hung their head aloft on the wall.
- Angered by my broken vase, I refused to feed him punctually.
beat sb. to death: 打死某人
- The war knight claimed to have beaten a nomad to death.
- Wusong was said to beat a tiger at large to death.
- The king had to establish a law prohibiting beating anyone to death in public.
cut off sth.: 切断某物
- Cutting off the rope while the worker was operating aloft, the woman was kept in prison for twenty year.
- If you cut off the rope, we can't keep in touch anymore.
- My grandfather found his pocket cut off and his money disappeared in the bus.
in triumph: 凯旋地
- The general was allowed to dance with his wife in triumph in the celebration.
- The owner of circus ride a baby elephant in triumph accompanied with a guard of honor of five pretty girls.
- The king promised to bring his enemy's head in triumph.
sb. holds that + ...: 某人认为+...
- I hold that you are not telling the truth.
- I hold that the right answer is supposed to be A.
- His wife held that she didn't get enough money to go on a vacation in Sanya.
Accordingly, + ...: 因此, +...
- Accordingly, the worker trapped in the mine lost their hearts.
- Accordingly, the ideas of the Enlightenment haven't capture the hearts of all Europeans.
- Accordingly, the enlightened reform remained more a dream than a reality for the Great.
extend rights and power to sb.: 赋予某人权利和权力
- The abbot's concern was to extend religious rights and power to monks in the monastery.
- The pope held that the expansion of the monasteries extended secular rights and power to the papal authority.
- The representative assembly extended political rights and power to the masses.
the center of attention: focus 注意力中心
- A slip of the tong made the announcer the center of attention.
- Though he trys to stay out of the limelight, his grandeur majesty always makes him the center of attention.
- His flame of ambition makes his kingdom the center of attention.
** sentence2
mob [mɑb]: n. a large noisy crowd, especially one that is angry and violent暴徒
- The king woke up with a start when hearing noises from the mob at midnight.
- A mob of thousands of busmen went on strike gathering around the Town Hall.
- A mob of hundreds of peasants streamed toward the museum and held up the traffic.
armory [ˈɑrməri]: n. a place where weapons are stored军械库
- There is a suspicious foreigner spying on the entrance of the armory.
- Two thieves were beaten to death breaking into the armory.
- Waking up with a start, he realized to his horror that the armory was being defended by his inferiors.
ammunition [ˌæmjəˈnɪʃ(ə)n]: n. bullets, shells (↑shell) etc that are fired from guns军火, 弹药
- There is no shortage of ammunition in South Africa.
- Short of ammunition, the general was killed in action.
- Short of ammunition, the regiment asked the king to check the armory.
glaring [ˈɡlerɪŋ]: adj. very bad and very noticeable SYN obvious刺眼的
- She could not bear the glaring tattoo on her face anymore.
- If you noticed the glaring sign on the wall, you wouldn't get a ticket in our city.
- The glaring scars on my face are reminding me of the injuries of the Black Death.
despot [ˈdeˌspɑt] despotic: n.adj. someone, especially a ruler, who uses power in a cruel and unfair way SYN tyrant暴君
- The despot is reminiscing about his dead wife.
- An eager was swirling around the despot who got very angry.
- The despotic law was rejected by the colonies and they declared their independence from the empire.
policy [ˈpɑləsi]: n. a way of doing something that has been officially agreed and chosen by a political party, a business, or another organization政策, 方针
- Obviously, the political policies and social changes led to a decrease birth rate in towns.
- The emperor was eager to put forward the policies: the state sacrificed money for more lands.
- These policies would turn upside down everything in my kingdom.
garrison [ˈɡerɪs(ə)n]: n. a group of soldiers living in a town or ↑fort and defending it卫戍部队, 驻军
- The garrison short of ammunition is easy to be defeated.
- The garrison joined in the war using their behaviors to swear their loyalty to the king.
- The garrison proved undisciplined, for there were so many drunks when the king checked it.
surrender [səˈrendər]: v. to say officially that you want to stop fighting, because you realize that you cannot win投降, 自首
- Even though the general surrendered at the beginning of the battle, he had his head cut off by the mob.
- It is no use surrendering because you will meet your death at the hands of our enemies.
- Portrayed as a gangster by his domestic political enemies, the warlike knight decided to betray his lord.
victorious [vɪkˈtɔriəs]: adj. having won a victory, or ending in a victory获胜的, 胜利的
- The victorious group must have planned out everything to the last detail.
- Equipped with the new machine, the victorious group of explorers succeeded in finding buried treasures.
- The war reported being victorious, which brought a smile to the despot in the celebration.
aloft [əˈlɔft]: adv. high up in the air在高处
- The paw prints were snatched by my cat when I held her aloft.
- The victorious team held their coach aloft to express their pleasure.
- The balloon flying aloft can be a great threat to our aircraft.
regime [reɪˈʒim]: n. a government, especially one that was not elected fairly or that you disapprove of for some other reason政权
- The brutal regime drew up a set of laws prohibiting the freedom of speech and press.
- The brutal regime levied heavy taxes on those peasants who struggled for life.
- The brutal regime was short-lived, with the breakdown of people's trust in it.
loyalty [ˈlɔɪəlti]: n. the quality of remaining faithful to your friends, principles, country etc忠诚, 忠心
- He didn't cheat on me when meeting the gorgeous widow, which proved his loyalty to our family.
- To prove his loyalty to their love, he jumped from the 19th floor of their apartment.
- The warlike knight swore his loyalty to his princess whom he rescued from the revolt.
democracy [dɪˈmɑkrəsi] democratic: n.adj. a system of government in which every citizen in the country can vote to elect its government officials民主政治, 民主主义
- For Catherine the Great, democratic reforms remained more a dream than a reality.
- Diderot offered frankly her advice for a democratic program of political and financial reform.
- Despite democratic policies inside, the king built armies to compete militarily with other European states.
capital [ˈkæpɪt(ə)l]: n. money or property, especially when it is used to start a business or to produce more wealth资本
- Failing to attract foreign capital, a great number of masses in this country lived in poverty.
- The Prime Minister, referred to as the Magnificent, was an expert at attracting foreign capital.
- The terrorist attack in Shenzhen repelled some foreign capital from China.
precede [prɪˈsid] preceding: v.adj. to happen or exist before something or someone, or to come before something else in a series ⇨ preceding先于
- My departure preceded your arrival, so I have no chance to steal your ring at the party.
- The preceding gift indeed gave me a surprise.
- The preceding terrorist abduction in America inspired awe in people the world over.
decadent [ˈdekədənt]: adj. having low moral standards and being more concerned with pleasure than serious matters颓废的
- Decadent those days I sat in a boat and did nothing at all.
- She pointed out that the monarchs were so decadent that they couldn't defend our subject against these Asisa nomads.
- On arriving at his house, he was condemned as a decadent waste by his family.
slogan [ˈsloʊɡən]: n. a short phrase that is easy to remember and is used in advertisements, or by politicians, organizations etc ⇨ catchphrase口号
- The former Prime Minister is fanatical about inventing various slogans.
- The king was stunned by these terrifying slogans which heralded the emergence of another revolt.
- He pointed out that the slogan constituted a slip of the tongue.
fraternity [frəˈtɜrnəti]: n. the teaching/scientific/criminal etc fraternity all the people who work in a particular profession or share a particular interest博爱
- The idea of fraternity was spread through the French soldiers to the continent.
- The family full of fraternity was accused of participating in the rebellion.
- The family full of fraternity is very strong in this village.
--------------------
be filled with sth.: 充满了某物
- Filled with wool, this kind of pillow became popular with peasants in China.
- Filled with sand and stones, the parcel was supposed to be full of diamonds.
- Filled with water, the car broke down on the highway.
in the eyes of sb.: 在某人的眼中
- I might be one of the kindest human beings in the eyes of my cat.
- My cat is full of fascination in the eyes of my wife.
- The stray dog must be gorgeous in the eyes of my wife who decided to give him a home.
be angered by sth./sb.: 被某人某事所激怒
- Angered by decadent knights, the king established a law prohibiting drinking too much in the tavern.
- Angered by the heresy, the pope crucified them and hung their head aloft on the wall.
- Angered by my broken vase, I refused to feed him punctually.
beat sb. to death: 打死某人
- The war knight claimed to have beaten a nomad to death.
- Wusong was said to beat a tiger at large to death.
- The king had to establish a law prohibiting beating anyone to death in public.
cut off sth.: 切断某物
- Cutting off the rope while the worker was operating aloft, the woman was kept in prison for twenty years.
- If you cut off the rope, we can't keep in touch anymore.
- My grandfather found his pocket cut off and his money disappeared on the bus.
in triumph: 凯旋地
- The general was allowed to dance with his wife in triumph in the celebration.
- The owner of the circus rode a baby elephant in triumph accompanied by a guard of honor of five pretty girls.
- The king promised to bring his enemy's head in triumph.
sb. holds that + ...: 某人认为+...
- I hold that you are not telling the truth.
- I hold that the right answer is supposed to be A.
- His wife held that she didn't get enough money to go on a vacation in Sanya.
Accordingly, + ...: 因此, +...
- Accordingly, the worker trapped in the mine lost their hearts.
- Accordingly, the ideas of the Enlightenment haven't captured the hearts and minds of all Europeans.
- Accordingly, the enlightened reform remained more a dream than a reality for the Great.
extend rights and power to sb.: 赋予某人权利和权力
- The abbot's concern was to extend religious rights and power to monks in the monastery.
- The pope held that the expansion of the monasteries extended secular rights and power to the papal authority.
- The representative assembly extended political rights and power to the masses.
the center of attention: focus 注意力中心
- A slip of the tongue made the announcer the center of attention.
- Though he tries to stay out of the limelight, his grandeur and majesty always make him the center of attention.
- His flame of ambition makes his kingdom the center of attention.
** summary
On July 14, 1789, a Parisian mob streamed toward the Bastille,
	a royal armory filled with arms and ammunition
		which was defended by the marquis de Launary.
Angered by the loss of ninety-eight of their members,
	the victorious mob beat the marquis to death,
		and carried his head aloft in triumph through the streets of Paris.
King Louis XVI was stunned by the fall of the Bastille
	and the duke thought it was a revolution.
The French Revolution has been portrayed as
	the major turning point in European political and social history
	when the old regimed was replaced by a new orer based on invidual rights,
		representative institutions,
		and loyalty to the nation rather than the monarch.
Though the pharse 'democratic revolution'
	has been used to refer to upheavals of the late eighteenth and ninetennth centuries,
	it is more appropriate to speak of a liberal movement
		to extend political rights and power to the bourgeoisie.
The revolutionary upheavl of the era, especially in Fance,
	created new liberal and national political ideals,
		summaried in the French revolutionary slogan, 'Liberty, Equality, Fraternity'.
** summary2
On July 14, 1789, a Parisian mob streamed toward the Bastille,
	a royal armory filled with arms and ammunition
		which was defended by the Marquis de Launary.
Angered by the loss of ninety-eight of their members,
	the victorious mob beat the Marquis to death,
		and carried his head aloft in triumph through the streets of Paris.
King Louis XVI was stunned by the fall of the Bastille
	and the duke thought it was a revolution.
The French Revolution has been portrayed as
	the major turning point in European political and social history
	when the old regime was replaced by a new order based on individual rights,
		representative institutions,
		and loyalty to the nation rather than the monarch.
Though the phrase 'democratic revolution'
	has been used to refer to upheavals of the late eighteenth and nineteenth centuries,
	it is more appropriate to speak of a liberal movement
		to extend political rights and power to the bourgeoisie.
The revolutionary upheaval of the era, especially in France,
	created new liberal and national political ideals,
		summarized in the French revolutionary slogan, 'Liberty, Equality, Fraternity'.
