#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2024-11-21 An agricultural revolution
#+begin_verse
The biggest change was the shift
	from hunting animals and gathering plants for sustenance (food gathering)
		to producing food by systematic agriculture (food production).
The planting of grains and vegetables provided a regular supply of food,
	while the domestication of animals, such as sheep, goats, cattle, and pigs,
		added a steady source of meat, milk, and fibers such as wool for clothing.
Larger animals could also be used as beasts of burden.
The growing of crops and the taming of food-producing animals
	created a new relationship between humans and nature.
Historians speak of this as an agricultural revolution.
Revolutionary change is dramatic and requires great effort,
	but the ability to acquire food on a regular basis
		gave humans greater control over their environment.
It also allowed them to give up their nomadic ways of life and begin to live in settled communities.

Systematic agriculture probably developed independently
	between 8000 and 7000 B.C. in various parts of the world.
Different plants were cultivated in each:
	wheat, barley, and lentils in the Near East; rice and millet in southern Asia;
	millet and yams in western Africa; and beans, potatoes, and corn in the Americas.
The Neolithic agricultural revolution needed a favorable environment.
In the Near East, the upland areas above the Fertile Crescent
		(present-day northern Iraq and southern Turkey)
	were more conducive to systematic farming than the river valleys.
This region received the necessary rainfall
	and was the home of two wild plant species (barley and wheat)
		and four wild animal species (pigs, cows, goats, and sheep) that humans eventually domesticated.
#+end_verse
** expression
sustenance [ˈsʌstənəns]: n. food that people or animals need in order to live食物
systematic [ˌsɪstəˈmætɪk]: adj. organized carefully and done thoroughly系统的
domesticate [dəˈmestɪˌkeɪt] domestication: v.n. to make an animal able to work for people or live with them as a pet ⇨ tame驯养
goat [ɡoʊt]: n. an animal that has horns on top of its head and long hair under its chin, and can climb steep hills and rocks. Goats live wild in the mountains or are kept as farm animals.山羊
cattle [ˈkæt(ə)l]: n. cows and ↑bulls kept on a farm for their meat or milk牛(总称)
steady [ˈstedi]: adj. continuing or developing gradually or without stopping, and not likely to change稳固的, 稳定的
fiber [ˈfaɪbər]: n. the parts of plants that you eat but cannot ↑digest. Fibre helps to keep you healthy by moving food quickly through your body纤维
crop [krɑp]: n. a plant such as wheat, rice, or fruit that is grown by farmers and used as food ⇨ GM庄稼
tame [teɪm]: v. to train a wild animal to obey you and not to attack people SYN domesticate驯服
wheat [hwit]: n. the grain that bread is made from, or the plant that it grows on小麦
barley [ˈbɑrli]: n. a plant that produces a grain used for making food or alcohol大麦
lentil [ˈlent(ə)l]: n. a small round seed like a bean, dried and used for food小扁豆
millet [ˈmɪlɪt]: n. the small seeds of a plant similar to grass, used as food小米
yam [jæm]: n. a tropical climbing plant grown for its root, which is eaten as a vegetable山药
favorable [ˈfeɪv(ə)rəb(ə)l]: adj. suitable and likely to make something happen or succeed适宜的
uplands [ˈʌplənd]: n. the parts of a country that are away from the sea and are higher than other areas高地,山地
crescent [ˈkrez(ə)nt]: n. a curved shape that is wider in the middle and pointed at the ends新月, 月牙
valley [ˈvæli]: n. an area of lower land between two lines of hills or mountains, usually with a river flowing through it(山)谷,流域
--------------------
beasts of burden: 干重力的畜生
speak of A as B: 认为A是B
in various parts of the world: 在世界各地
be conducive to sth./doing sth.: 有利于某事
** sentence
sustenance [ˈsʌstənəns]: n. food that people or animals need in order to live食物
- Without sustenance, our infantries that have overran the city will lost their hearts. 
- Without sustenance, the sieged soldiers were due to die fighting.
- Without sustenance, the poor boy who was locked in the room starved to death.
systematic [ˌsɪstəˈmætɪk]: adj. organized carefully and done thoroughly系统的
- Obviously, systematic cheats have happened to IELTS for years. 
- With evidence coming to light, there was a systematic cheat on the final exam.
- We will provide you with a systematic plan in the period of your pregnancy.
domesticate [dəˈmestɪˌkeɪt] domestication: v.n. to make an animal able to work for people or live with them as a pet ⇨ tame驯养
- This horse is one of the most proud one in my farm that no one has domesticated.
- Failing to domesticate the horse, the prince was so angry that he killed it.
- It is said that the house of Tagarian has once domesticated dragons.
goat [ɡoʊt]: n. an animal that has horns on top of its head and long hair under its chin, and can climb steep hills and rocks. Goats live wild in the mountains or are kept as farm animals.山羊
- Eating goat may be a taboo in some cultures which are different from Euro-American culture.
- If you lived in China, for example, you wouldn't consider goat as a delicacy.
- People in this village are brought up to eat goat.
cattle [ˈkæt(ə)l]: n. cows and ↑bulls kept on a farm for their meat or milk牛(总称)
- My father sold this cattle that ceases to produce milk.
- Fond of the cattle, the worker used to stay overnight in the crowshed.
- This farm rised to fame swiftly because of tremendous cattle it domesticated. 
steady [ˈstedi]: adj. continuing or developing gradually or without stopping, and not likely to change稳固的, 稳定的
- By learning Leo's course, my English is making steady progress.
- It is not wise to abondan the stock of a company which is making steady progress.
- If you give us protection money on a regular basis, we will return steady protection. 
fiber [ˈfaɪbər]: n. the parts of plants that you eat but cannot ↑digest. Fibre helps to keep you healthy by moving food quickly through your body纤维
- Short of fiber, you will have a difficult time in using toilet.
- These vegetables will provide us with a regular supply of fiber that we need.
- Your father is hospitalized short of fiber.
crop [krɑp]: n. a plant such as wheat, rice, or fruit that is grown by farmers and used as food ⇨ GM庄稼
- These farmhands were instructed to plant cash crop which is not suitable for the soil.
- Our people will not get a good harvest of crops this year because of floods and earthquake.
- We must take into account of the decline of the crops this year.
tame [teɪm]: v. to train a wild animal to obey you and not to attack people SYN domesticate驯服
- Consequently, the crippled boy tamed his wilf which he had asked his father not to kill.
- Failing to tame his cat, he realized that cats will not become submissive like dogs or horses.
- They tame the famous kind of dogs to help people who rush to cross the pass.
wheat [wit]: n. the grain that bread is made from, or the plant that it grows on小麦
- As a man in the southern China, I never consider wheat as a staple.
- Wheat that is found in the northern China is mainly used as the ingredient of flour.  
- I wish that today's breakfast didn't comprise any wheat food.
barley [ˈbɑrli]: n. a plant that produces a grain used for making food or alcohol大麦
- The bear's ingredients consist of barley, water, and so on.
- The food made of barley is admired by people in the north of China.
- The production of the barley this year is conducive to our food industry.
lentil [ˈlent(ə)l]: n. a small round seed like a bean, dried and used for food小扁豆
- It seemed that our cat had bitten the lentil.
- Noticing the breakfast comprising lentils, she slammed the door to express her disatisfcation.
- You could attend to lentils at your own pace.
millet [ˈmɪlɪt]: n. the small seeds of a plant similar to grass, used as food小米
- The millet soup used to be think of being good for your health.
- Tired of millet soup, her husband asked his wife to make differnt breakfast.
- These intellectuals feast on millet which people produce and don't any labor work at all.
yam [jæm]: n. a tropical climbing plant grown for its root, which is eaten as a vegetable山药
- In my youth, I always asked my father to cook yam for me.
- These days the price of yam in the market goes up. 
- The lawyer received a warm welcome regaled with yam by natives.
favorable [ˈfeɪv(ə)rəb(ə)l]: adj. suitable and likely to make something happen or succeed适宜的
- The plague spread from a romote village in China to Europe continent under these favorable conditions.
- We will let your brother step out of the jail under a favorable condition.
- My real business is to arrange a settlement under a favorable condition.
uplands [ˈʌplənd]: n. the parts of a country that are away from the sea and are higher than other areas高地,山地
- The kind of wheat is cultivated in upland area.
- The trees cultivated in upland area will take root in our urban.
- No entrepreneur will be willing to set up factories in upland area.
crescent [ˈkrez(ə)nt]: n. a curved shape that is wider in the middle and pointed at the ends新月, 月牙
- The coach called White Crescent was dismissed again after another defeat.
- A kind girl gave me a crescent of cookie when I was in rags.
- The crescent of cookie which his long-lost daughter gave was very dear to him.
valley [ˈvæli]: n. an area of lower land between two lines of hills or mountains, usually with a river flowing through it(山)谷,流域
- Two clans settling in the valley were at war with each other.
- I swore to my king, you would meet your death at the hands of mine in the valley.
- A clan of people lives in the valley which is blessed with fertile soil.
--------------------
beasts of burden: 干重力的畜生
- The horses which used as beasts of burden in China were often confiscated by army. 
- In place of horses, cows are used as beasts of burden in China.
- It is obvious that our farm workers are still short of beasts of burden.
speak of A as B: 认为A是B
- Historians spoke of the dead as white walkers.
- The king spoken of as the mad king ended up the dynasty of the house of dragon.
- No one speaks of you as a rebellious girl who can play truant from school.
in various parts of the world: 在世界各地
- Euro-American culture exerts a tremendous influence on people in various parts of the world.
- People enacted different rituals to mourn the dead in various parts of the world.
- In one way, the linux system plays different roles in various parts of the world.
be conducive to sth./doing sth.: 有利于某事
- Arguing with your wife is conducive to divorce, so you should communicate with your wife in another manner.
- Eating health food, like vegetables and fruits, is conducive to your health.
- Submitting protection money may be conducive to your business, my gentleman.
** sentence2
sustenance [ˈsʌstənəns]: n. food that people or animals need in order to live食物
- Without sustenance, our infantries that have overrun the city will lose their hearts. 
- Without sustenance, the sieged soldiers were due to die fighting.
- Without sustenance, the poor boy who was locked in the room starved to death.
systematic [ˌsɪstəˈmætɪk]: adj. organized carefully and done thoroughly系统的
- Obviously, systematic cheats have happened to IELTS for years. 
- With evidence coming to light, there was a systematic cheat on the final exam.
- We will provide you with a systematic plan for the period of your pregnancy.
domesticate [dəˈmestɪˌkeɪt] domestication: v.n. to make an animal able to work for people or live with them as a pet ⇨ tame驯养
- This horse is one of the proudest horses on my farm that no one has domesticated.
- Failing to domesticate the horse, the prince was so angry that he killed it.
- It is said that the house of Tagarian has once domesticated dragons.
goat [ɡoʊt]: n. an animal that has horns on top of its head and long hair under its chin, and can climb steep hills and rocks. Goats live wild in the mountains or are kept as farm animals.山羊
- Eating goats may be a taboo in some cultures which are different from Euro-American culture.
- If you lived in China, for example, you wouldn't consider goats as a delicacy.
- People in this village are brought up to eat goats.
cattle [ˈkæt(ə)l]: n. cows and ↑bulls kept on a farm for their meat or milk牛(总称)
- My father sold this cattle that ceased to produce milk.
- Fond of the cattle, the worker used to stay overnight in the cowshed.
- This farm rose to fame swiftly because of the tremendous number of cattle it domesticated. 
steady [ˈstedi]: adj. continuing or developing gradually or without stopping, and not likely to change稳固的, 稳定的
- By learning Leo's course, my English is making steady progress.
- It is not wise to abandon the stock of a company that is making steady progress.
- If you give us protection money on a regular basis, we will return steady protection. 
fiber [ˈfaɪbər]: n. the parts of plants that you eat but cannot ↑digest. Fibre helps to keep you healthy by moving food quickly through your body纤维
- Short of fiber, you will have a difficult time using a toilet.
- These vegetables will provide us with a regular supply of fiber that we need.
- Your father is hospitalized short of fiber.
crop [krɑp]: n. a plant such as wheat, rice, or fruit that is grown by farmers and used as food ⇨ GM庄稼
- These farmhands were instructed to plant cash crops which are not suitable for the soil.
- Our people will not get a good harvest of crops this year because of floods and an earthquake.
- We must take into account the decline of the crops this year.
tame [teɪm]: v. to train a wild animal to obey you and not to attack people SYN domesticate驯服
- Consequently, the crippled boy tamed his wolf which he had asked his father not to kill.
- Failing to tame his cat, he realized that cats will not become submissive like dogs or horses.
- They tame the famous kind of dogs to help people who rush to cross the pass.
wheat [wit]: n. the grain that bread is made from, or the plant that it grows on小麦
- As a man in southern China, I never consider wheat as a staple.
- Wheat that is found in the north of China is mainly used as the ingredient of flour.  
- I wish that today's breakfast didn't comprise any wheat food.
barley [ˈbɑrli]: n. a plant that produces a grain used for making food or alcohol大麦
- The bear's ingredients consist of barley, water, and so on.
- The food made of barley is admired by people in the north of China.
- The production of the barley this year is conducive to our food industry.
lentil [ˈlent(ə)l]: n. a small round seed like a bean, dried and used for food小扁豆
- It seemed that our cat had bitten the lentil.
- Noticing the breakfast comprising lentils, she slammed the door to express her dissatisfaction.
- You could attend to lentils at your own pace.
millet [ˈmɪlɪt]: n. the small seeds of a plant similar to grass, used as food小米
- The millet soup used to be thought of as healthy food.
- Tired of millet soup, her husband asked his wife to make a different breakfast.
- These intellectuals feast on millet which people produce and don't do any labor work at all.
yam [jæm]: n. a tropical climbing plant grown for its root, which is eaten as a vegetable山药
- In my youth, I always asked my father to cook yam for me.
- These days the price of yam in the market goes up. 
- The lawyer received a warm welcome regaled with yam by natives.
favorable [ˈfeɪv(ə)rəb(ə)l]: adj. suitable and likely to make something happen or succeed适宜的
- The plague spread from a remote village in China to the Europe continent under these favorable conditions.
- We will let your brother step out of jail under a favorable condition.
- My real business is to arrange a settlement under a favorable condition.
uplands [ˈʌplənd]: n. the parts of a country that are away from the sea and are higher than other areas高地,山地
- The kind of wheat cultivated in the upland area.
- The trees cultivated in the upland area will take root in our urban.
- No entrepreneur will be willing to set up factories in upland areas.
crescent [ˈkrez(ə)nt]: n. a curved shape that is wider in the middle and pointed at the ends新月, 月牙
- The coach called White Crescent was dismissed again after another defeat.
- A kind girl gave me a crescent of chocolate when I was in rags.
- The crescent of cookie which his long-lost daughter gave is very dear to him.
valley [ˈvæli]: n. an area of lower land between two lines of hills or mountains, usually with a river flowing through it(山)谷,流域
- Two clans settling in the valley were at war with each other.
- I swore to my king, you would meet your death at the hands of mine in the valley.
- A clan of people lives in the valley which is blessed with fertile soil.
--------------------
beasts of burden: 干重力的畜生
- The horses which used as beasts of burden in China were often confiscated by the army. 
- In place of horses, cows are used as beasts of burden in China.
- It is obvious that our farm workers are still short of beasts of burden.
speak of A as B: 认为A是B
- Historians spoke of the dead as white walkers.
- The king spoke of as cowards the soldiers who deserted their regiments.
- No one speaks of you as a rebellious girl who can play truant from school.
in various parts of the world: 在世界各地
- Euro-American culture exerts a tremendous influence on people in various parts of the world.
- People enacted different rituals to mourn the dead in various parts of the world.
- In one way, the Linux system plays different roles in various parts of the world.
be conducive to sth./doing sth.: 有利于某事
- Arguing with your wife is conducive to divorce, so you should communicate with your wife in another manner.
- Eating healthy food, like vegetables and fruits, is conducive to your health.
- Submitting protection money may be conducive to your business, my gentleman.
