#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 22 Proclamation of the German Empire in the Hall of Mirrors in the palace of Versailles
#+begin_verse
Across the continent, the revolutions of 1848 had failed.
The forces of liberalism and nationalism appeared to have been decisively defeated
	as authoritarian governments reestablished control almost everywhere in Europe by 1850.
And yet within twenty-five years,
	many of the goals sought by the liberals and nationalists during the first half of the century
		seemed to have been achieved.
National unity became a reality in Italy and Germany,
	and many European states were governed by constitutional monarchies,
		even though the constitutional-parliamentary features were frequently facades.

All the same, these goals were not achieved by liberal nationalist leaders
	but by a new generation of conservative leaders
		who were proud of being practitioners of Realpolitik, the 'politics of reality.'
One reaction to the failure of the revolutions of 1848 had been a new toughness of mind
	in which people prided themselves on being realistic in their handling of power.
The new conservative leaders used armies and power politics to achieve their foreign policy goals.
And they did not hesitate to manipulate liberal means to achieve conservative ends at home.
Nationalism had failed as a revolutionary movement in 1848--1849,
	but in the ensuing decades, these new leaders found a variety of ways to pursue nation building.
One of the most successful was the Prussian Otto von Bismarck,
	who used both astute diplomacy and war to achieve the unification of Germany.
On January 18, 1871,
	Bismarck and six hundred German princes, nobles,
			and generals filled the Hall of Mirrors in the palace of Versailles,
		12 miles outside the city of Paris.
The Prussian army had defeated the French,
	and the assembled notables were gathered
		for the proclamation of the Prussian king as the new emperor of a united German state.
When the words 'Long live His Imperial Majesty, the Emperor William.' rang out,
	the assembled guests took up the cry.
One participant wrote,
	'A thundering cheer, repeated at least six times, thrilled through the room
	while the flags and standards waved over the head of the new emperor of Germany.'
European rulers who feared the power of the new German state were not so cheerful.
'The balance of power has been entirely destroyed,' declared the British prime minister.
#+end_verse
** expression
proclamation [ˌprɑkləˈmeɪʃ(ə)n]: n. an official public statement about something that is important, or when someone makes such a statement ⇨ proclaim宣布,宣告
decisive [dɪˈsaɪsɪv] decisively: adj.adv. an action, event etc that is decisive has a big effect on the way that something develops决定性的
authoritarian [ɔˌθɔrɪˈteriən]: adj. strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
unity [ˈjunəti]: n. when a group of people or countries agree or are joined together统一
reality [riˈæləti]: n. what actually happens or is true, not what is imagined or thought真实
constitutional [ˌkɑnstɪˈtuʃ(ə)nəl]: adj. officially allowed or limited by the system of rules of a country or organization合乎宪法的
facades [fəˈsɑd]: n. A deceptive outward appearance外表
conservative [kənˈsɜrvətiv]: adj. not liking changes or new idea保守的, 守旧的
practitioner [prækˈtɪʃ(ə)nər]: n. someone who regularly does a particular activity实践者
toughness [tʌfnəs]: n. 韧性
manipulate [məˈnɪpjəˌleɪt]: v. to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them操纵,利用
ensuing [ɪnˈsuɪŋ]: adj. happening after a particular action or event, especially as a result of it SYN following随后的
astute [əˈstut]: adj. able to understand situations or behaviour very well and very quickly, especially so that you can get an advantage for yourself SYN clever机敏的, 狡猾的
assemble [əˈsemb(ə)l]: v. if you assemble a large number of people or things, or if they assemble, they are gathered together in one place, often for a particular purpose集合
thunder [ˈθʌndər]: v. if it thunders, there is a loud noise in the sky, usually after a flash of lightning打雷, 雷鸣
thrill [θrɪl]: v. to make someone feel excited and happy ⇨ thrilling使兴奋
cheerful [ˈtʃɪrf(ə)l]: adj. happy, or behaving in a way that shows you are happy愉快的, 高兴的
--------------------
reestablish control: 重新控制
within twenty-five years: 25年内
All the same: (尽管有变)总体不变
a new generation of sb./sth.: 某人/某事物的新一代
be realistic in sth.: 在某事上实事求是
achieve sb's goals: 达成某人的目标/目的
achieve sb's ends: 达成某人的目标/目的
12 miles outside sp.: 在某地外12英里远
ring out: 响起
take up the cry: 开始呼喊
** sentence
proclamation [ˌprɑkləˈmeɪʃ(ə)n]: n. an official public statement about something that is important, or when someone makes such a statement ⇨ proclaim宣布,宣告
- The mob of thousands of peasant were relieved to hear that the proclamation would be held two days later.
- The French people was appalled at the proclamation of the Prussia king as the emporer of the German Empire.
- The proclamation of the Prussia king as the emporer of the German Empire fulfilled his dream.
decisive [dɪˈsaɪsɪv] decisively: adj.adv. an action, event etc that is decisive has a big effect on the way that something develops决定性的
- The player hit the ball decisively, which gave the customers a sense of satisfaction.
- The invention of this kind of machine decisively initiated a quantum leap in production.
- The king drew up a series of laws prohibiting digging up coffin, which proved decisive.
authoritarian [ɔˌθɔrɪˈteriən]: adj. strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
- The authoritarian government succeeded in assuming political power after the revolution.
- Fear of the authoritarian government, he felt obligated to keep his brother in hiding.
- The authoritarian government carried out its wishes through a variety of movement.
unity [ˈjunəti]: n. when a group of people or countries agree or are joined together统一
- The sentiment of unity had been grown up within 25 years.
- The sentiment of unity has never ceased to decline under the control of the authoritarian government.
- The dream of the unity of the nation still remains a mystery.
reality [riˈæləti]: n. what actually happens or is true, not what is imagined or thought真实
- In reality on his flame of ambition, we will all be crucified.
- In reality I never admired you for your sense of humor.
- In reality his daughter has been thinking that these people were laughing at him.
constitutional [ˌkɑnstɪˈtuʃ(ə)nəl]: adj. officially allowed or limited by the system of rules of a country or organization合乎宪法的
- The breakdown of trust in the constitutional government led to scores of immigrations.
- The forces of change gave rise first to the collapse of the kingdom and then to the constitutional government.
- The supremacy of the constitutional government over the monarchs captured the minds and the hearts of people.
facades [fəˈsɑd]: n. A deceptive outward appearance外表
- Among a special commission, I was hired to paint the facades of the palace.
- We must raise money to have our building facades repaired.
- The building facades were painted by the artist who expressed his sentiment of his lover.
conservative [kənˈsɜrvətiv]: adj. not liking changes or new idea保守的, 守旧的
- These conservative experts continued into the next decade.
- Beyond doubt, these conservative rulers regain their control over domestic affairs and restored them to new glory.
- Nevertheless, the conversative pope hired the famous artist to paint in the ceil of the chapel.
practitioner [prækˈtɪʃ(ə)nər]: n. someone who regularly does a particular activity实践者
- In one sense, the practitioners of nationlism did achieve their goals.
- The practitioners of liberalism held the grudge on the monarchs who were eager to restore their old regime.
- The practitioners of liberalism lost no time in going on a strike.
toughness [tʌfnəs]: n. 韧性
- The hostess of salon had a reputation for toughness, which attracted many philosophes.
- I was wondering why people admired you for your toughness.
- Because of the lack of toughness, he failed to complete the task when running into serious trouble.
manipulate [məˈnɪpjəˌleɪt]: v. to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them操纵,利用
- She must be manipulating the controller to control the temperature in the bedroom.
- The cat lost no time in manipulating sand and stones to drink water in the bottle.
- Our soldiers manipulated the barrier of swamp to defend our city against these nomads.
ensuing [ɪnˈsuɪŋ]: adj. happening after a particular action or event, especially as a result of it SYN following随后的
- In the ensuing year, I will have achieved my goal - passing the exam.
- In the ensuing year, you will get a good salary abroad and work for a team in LPL.
- In the ensuing year, you will be kept in prison regretting what you have done.
astute [əˈstut]: adj. able to understand situations or behaviour very well and very quickly, especially so that you can get an advantage for yourself SYN clever机敏的, 狡猾的
- The astute business took advantages of the flaws of our domestic laws.
- My superior proves astute, for he has been lying to me about the working conditions.
- The astute puma was often found in a place in the morning, another place 12 miles away in the evening.
assemble [əˈsemb(ə)l]: v. if you assemble a large number of people or things, or if they assemble, they are gathered together in one place, often for a particular purpose集合
- Why did you assemble us at midnight? We don't think the clock need repairing at this time.
- Waking up with a start, the general assembled his men fast asleep in the square. 
- The mobs of thousands of peasants were assembled in front of the royal armory.
thunder [ˈθʌndər]: v. if it thunders, there is a loud noise in the sky, usually after a flash of lightning打雷, 雷鸣
- It's thundering, why don't you stay for dinner?
- It was thundering, which must give our baby a shock.
- It will be thundering.
thrill [θrɪl]: v. to make someone feel excited and happy ⇨ thrilling使兴奋
- His music never fails to thrill his customers at concerts.
- These public illuminations thrilled our kids a great deal, which made them unable to work for three days.
- My reaction thrilled the dog so much that he bit your shoe.
cheerful [ˈtʃɪrf(ə)l]: adj. happy, or behaving in a way that shows you are happy愉快的, 高兴的
- When news came to London zoo, the experts were cheerful.
- It was cheerful that we manipulated our new machine to find out gold in the soil.
- It was cheerful that our child began to take good care of himself.
--------------------
reestablish control: 重新控制
- Fearing that masses could be hurt, the police reestablished control over the stray dogs.
- After killing three of the mobs, the royal garrison reestablished control in the armory.
- Setting fire on the basement, these students reestablished control in the embassy.
within twenty-five years: 25年内
- Within twenty-five years, ten thousands of tall buildings have grew up in this city.
- Within twenty-five years, the servant in obscurity has poisoned her three husbands.
- Within twenty-five years, the workshop which used to employee five assistants has became a famous company related to business abroad.
All the same: (尽管有变)总体不变
- All the same, the new ideologies captured the hearts and minds of Europeans.
- All the same, I have the faith in our constitutional government.
- All the same, she takes the lead in our class.
a new generation of sb./sth.: 某人/某事物的新一代
- A new generation of people in China began to express their dislike of bureaucracy.
- The pop singer becomes popular with a new generation of people in China.
- A new generation of people in China is reluctant to buy houses.
be realistic in sth.: 在某事上实事求是
- I must be realistic in the bugs I made.
- I must be realistic in the stupid remark I made.
- Realistic in money, he got a divorce.
achieve sb's goals: 达成某人的目标/目的
- Achieving his goal, he brough his team to defeat the strong rivals.
- He has never achieved his goals in world hampionships.
- He wished that he had achieved his goal when he was trying to swim across the channel.
achieve sb's ends: 达成某人的目标/目的
- Your real business is to achieve your end.
- Achieving his ends, he made a visit to Viene where the representatives of all states arranged a final peace settlement.
- Achieving his ends, he made his son follow in his footsteps.
12 miles outside sp.: 在某地外12英里远
- The puma appeared to have been spotted in a small village, 12 miles outside the city of London.
- The Asiatic nomads settled down in the plain, 12 miles outside the city of Paris.
- The boy who play truant from school was left on the road, 12 miles outside the city of Paris.
ring out: 响起
- When I woke up with a start, a strange noise from the kitchen rang out.
- A strange buzz rang out in my ear, which has been disturbing for over 4 years.
- The word -The airport comes into use- rang out in the town.
take up the cry: 开始呼喊
- Noticing that a man was struck into the river, people began to take up the cry.
- As the situation became worse, customers began to take up the cry.
- Fearing that the drunk would be attacked by the bull, customers took up the cry.
** sentence2
proclamation [ˌprɑkləˈmeɪʃ(ə)n]: n. an official public statement about something that is important, or when someone makes such a statement ⇨ proclaim宣布,宣告
- The mob of thousands of peasants was relieved to hear that the proclamation would be held two days later.
- The French people were appalled at the proclamation of the Prussia king as the emporer of the German Empire.
- The proclamation of the Prussia king as the emporer of the German Empire fulfilled his dream.
decisive [dɪˈsaɪsɪv] decisively: adj.adv. an action, event etc that is decisive has a big effect on the way that something develops决定性的
- The player hit the ball decisively, which gave the customers a sense of satisfaction.
- The invention of this kind of machine decisively initiated a quantum leap in production.
- The king drew up a series of laws prohibiting digging up coffins, which proved decisive.
authoritarian [ɔˌθɔrɪˈteriən]: adj. strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
- The authoritarian government succeeded in assuming political power after the revolution.
- Fear of the authoritarian government, he felt obligated to keep his brother in hiding.
- The authoritarian government carried out its wishes through a variety of movements.
unity [ˈjunəti]: n. when a group of people or countries agree or are joined together统一
- The sentiment of unity had been grown up within 25 years.
- The sentiment of unity has never ceased to decline under the control of the authoritarian government.
- The dream of the unity of the nation still remains a mystery.
reality [riˈæləti]: n. what actually happens or is true, not what is imagined or thought真实
- In reality on his flame of ambition, we will all be crucified.
- In reality, I never admired you for your sense of humor.
- In reality, his daughter has been thinking that these people were laughing at him.
constitutional [ˌkɑnstɪˈtuʃ(ə)nəl]: adj. officially allowed or limited by the system of rules of a country or organization合乎宪法的
- The breakdown of trust in the constitutional government led to scores of immigrations.
- The forces of change gave rise first to the collapse of the kingdom and then to the constitutional government.
- The supremacy of the constitutional government over the monarchs captured the minds and the hearts of people.
facades [fəˈsɑd]: n. A deceptive outward appearance外表
- Among a special commission, I was hired to paint the facades of the palace.
- We must raise money to have our building facades repaired.
- The building facades were painted by the artist who expressed his sentiment of his lover.
conservative [kənˈsɜrvətiv]: adj. not liking changes or new idea保守的, 守旧的
- These conservative experts continued into the next decade.
- Beyond doubt, these conservative rulers regained their control over domestic affairs and restored them to new glory.
- Nevertheless, the conservative pope hired a famous artist to paint in the ceil of the chapel.
practitioner [prækˈtɪʃ(ə)nər]: n. someone who regularly does a particular activity实践者
- In one sense, the practitioners of nationalism did achieve their goals.
- The practitioners of liberalism held a grudge against the monarchs who were eager to restore their old regime.
- The practitioners of liberalism lost no time in going on a strike.
toughness [tʌfnəs]: n. 韧性
- The hostess of the salon had a reputation for toughness, which attracted many philosophes.
- I was wondering why people admired you for your toughness.
- Because of his lack of toughness, he failed to complete the task when running into serious trouble.
manipulate [məˈnɪpjəˌleɪt]: v. to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them操纵,利用
- She must be manipulating the controller to control the temperature in the bedroom.
- The cat lost no time in manipulating sand and stones to drink water in the bottle.
- Our soldiers manipulated the barrier of the swamp to defend our city against these nomads.
ensuing [ɪnˈsuɪŋ]: adj. happening after a particular action or event, especially as a result of it SYN following随后的
- In the ensuing year, I will have achieved my goal - passing the exam.
- In the ensuing year, you will get a good salary abroad and work for a team in LPL.
- In the ensuing year, you will be kept in prison regretting what you have done.
astute [əˈstut]: adj. able to understand situations or behaviour very well and very quickly, especially so that you can get an advantage for yourself SYN clever机敏的, 狡猾的
- The astute business took advantage of the flaws of our domestic laws.
- My superior proves astute, for he has been lying to me about the working conditions.
- The astute puma was often found in one place in the morning, and another place 12 miles away in the evening.
assemble [əˈsemb(ə)l]: v. if you assemble a large number of people or things, or if they assemble, they are gathered together in one place, often for a particular purpose集合
- Why did you assemble us at midnight? We don't think the clock needs repairing at this time.
- Waking up with a start, the general assembled his men fast asleep in the square. 
- The mobs of thousands of peasants were assembled in front of the royal armory.
thunder [ˈθʌndər]: v. if it thunders, there is a loud noise in the sky, usually after a flash of lightning打雷, 雷鸣
- It's thundering, why don't you stay for dinner?
- It was thundering, which must have given our baby a shock.
- It will be thundering.
thrill [θrɪl]: v. to make someone feel excited and happy ⇨ thrilling使兴奋
- His music never fails to thrill his customers at concerts.
- These public illuminations thrilled our kids a great deal, which made them unable to work for three days.
- My reaction thrilled the dog so much that he bit your shoe.
cheerful [ˈtʃɪrf(ə)l]: adj. happy, or behaving in a way that shows you are happy愉快的, 高兴的
- When news came to the London Zoo, the experts were cheerful.
- It was cheerful that we manipulated our new machine to find gold in the soil.
- It was cheerful that our child began to take good care of himself.
--------------------
reestablish control: 重新控制
- Fearing that masses could be hurt, the police reestablished control over the stray dogs.
- After killing three of the mobs, the royal garrison reestablished control in the armory.
- Setting the basement on fire, these students reestablished control in the embassy.
within twenty-five years: 25年内
- Within twenty-five years, ten thousand tall buildings have grown up in this city.
- Within twenty-five years, the servant in obscurity has poisoned her three husbands.
- Within twenty-five years, the workshop which used to employ five assistants has become a famous company related to business abroad.
All the same: (尽管有变)总体不变
- All the same, the new ideologies captured the hearts and minds of Europeans.
- All the same, I have faith in our constitutional government.
- All the same, she takes the lead in our class.
a new generation of sb./sth.: 某人/某事物的新一代
- A new generation of people in China began to express their dislike of bureaucracy.
- The pop singer becomes popular with a new generation of people in China.
- A new generation of people in China is reluctant to buy houses.
be realistic in sth.: 在某事上实事求是
- I must be realistic in the coverage of the catastrophes.
- I must be realistic in the stupid remark I made.
- Realistic in money, he got a divorce.
achieve sb's goals: 达成某人的目标/目的
- Achieving his goal, he brought his team to defeat the strong rivals.
- He has never achieved his goals in world championships.
- He wished that he had achieved his goal when he was trying to swim across the channel.
achieve sb's ends: 达成某人的目标/目的
- Your real business is to achieve your end.
- Achieving his ends, he made a visit to Viene where the representatives of all states arranged a final peace settlement.
- Achieving his ends, he made his son follow in his footsteps.
12 miles outside sp.: 在某地外12英里远
- The puma appeared to have been spotted in a small village, 12 miles outside the city of London.
- The Asiatic nomads settled down in the plain, 12 miles outside the city of Paris.
- The boy who played truant from school was left on the road, 12 miles outside the city of Paris.
ring out: 响起
- When I woke up with a start, a strange noise from the kitchen rang out.
- A strange buzz rang out in my ear, which has been disturbing for over 4 years.
- The word -The airport comes into use- rang out in the town.
take up the cry: 开始呼喊
- Noticing that a man was struck into the river, people began to take up the cry.
- As the situation became worse, customers began to take up the cry.
- Fearing that the drunk would be attacked by the bull, customers took up the cry.
** summary
The revolutions of 1848 had failed across the continent,
	and authoritarian governments reestablished control in Europe by 1850.
Yet within twenty-five years,
	not only did national unity become a reality in Italy and Germany,
		but many European states were governed by constitutional monarchies.
All the same, these goals were not achieved by liberal nationlist leaders
	but by a new generation of conservative leaders
		who used armies and power politics to achieve their foreign policy goals,
			and manipulated liberal means to achieve conservative ends at home.
One of the most successful rulers in pursuit of nation building was the Prussian Otto von Bismarck.
On January 18, 1871, Bismarck and the assembled notables were gathered
	for the proclamation of the Prussian king as the new emperor of a united German state.
As a result, European rulers thought the balance of power had been entirely destoryed.
** summary2
The revolutions of 1848 had failed across the continent,
	and authoritarian governments reestablished control in Europe by 1850.
Yet within twenty-five years,
	not only did national unity become a reality in Italy and Germany,
		but many European states were governed by constitutional monarchies.
All the same, these goals were not achieved by liberal nationalist leaders
	but by a new generation of conservative leaders
		who used armies and power politics to achieve their foreign policy goals,
			and manipulated liberal means to achieve conservative ends at home.
One of the most successful rulers in pursuit of nation-building was the Prussian Otto von Bismarck.
On January 18, 1871, Bismarck and the assembled notables were gathered
	for the proclamation of the Prussian king as the new emperor of a united German state.
As a result, European rulers thought the balance of power had been entirely destroyed.
