#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 23 Swimmers gather in front of concession stands at Coney Island
#+begin_verse
In the late nineteenth century, Europe was enjoying a dynamic age of material prosperity.
Bringing new industries, new sources of energy, and new goods,
	a second Industrial Revolution transformed the environment,
		dazzled Europeans,
		and led them to believe that their material progress was human progress.
Scientific and technological achievements, many naively believed,
	would improve the human condition and solve all problems.
The doctrine of progress became an article of faith. 

The new urban and industrial environment
		resulting from the rapid economic changes of the nineteenth century
	led to the emergence of a mass society.
With it came improvements for the lower classes,
	who benefited from the extension of voting rights,
		a better standard of living, and free education.
It also brought mass leisure.
New work patterns established the 'weekend' as a distinct time of recreation and fun,
	while new forms of mass transportation---railroads and streetcars---
		enabled even the lowest-paid workers to make brief excursions to beaches and amusement parks.
Coney Island was only 8 miles from central New York City;
	Blackpool in England was a short train ride from nearby industrial towns.
With their Ferris wheels and other daring rides that threw young men and women together,
	amusement parks offered a whole new world of entertainment.
Thanks to the railroad,
	seaside resorts, once the preserve of the wealthy,
		became accessible to more people for weekend visits,
	much to the disgust of one upper-class regular who described the new 'day-trippers':
	'They swarm upon the beach,
		wandering listlessly about with apparently no other aim than to get a mouthful of fresh air.'
Entrepreneurs in resort areas, however, welcomed the masses of new visitors
	and built piers laden with food, drink, and entertainment to serve them.

The coming of mass society also created new roles for the governments of European nation-states,
	which now fostered national loyalty, formed vast armies by conscription,
		and took more responsibility for public health and housing measures in their cities.
By 1871, the national state had become the focus of Europeans' lives.
Within many of these nation-states,
	the growth of the middle class had led to the triumph of liberal practices:
		constitutional governments, parliaments, and principles of equality.
The period after 1871 also witnessed the growth of political democracy
	as the right to vote was extended to all adult males;
		women, though, would still have to fight for their political rights.
With political democracy came a new mass politics and a new mass press.
Both would become standard features of the twentieth century.
#+end_verse
** expression
dazzle [ˈdæz(ə)l]: v. if a very bright light dazzles you, it stops you from seeing properly for a short time(使)眼花, 眩耀
leisure [ˈleʒər]: n. time when you are not working or studying and can relax and do things you enjoy闲暇
distinct [dɪˈstɪŋkt]: adj. clearly different or belonging to a different type独特的
recreation [ˌrekriˈeɪʃ(ə)n]: n. an activity that you do for pleasure or amusement ⇨ hobby, pastime, leisure消遣, 娱乐
railroad [ˈreɪlˌroʊd]: n. a railway or the railway铁路
streetcar [ˈstritˌkɑr]: n. a type of bus that runs on electricity along metal tracks in the road SYN tram British English有轨电车
brief [brif]: adj. continuing for a short time ⇨ vity简短的, 短暂的
seaside [ˈsiˌsaɪd]: adj.n. the seaside British English the areas or towns near the sea, where people go to enjoy themselves海边的, 海滨的
resort [rɪˈzɔrt]: n. a place where a lot of people go for holidays度假区
swarm [swɔrm]: v. a large group of insects, especially ↑bees, moving together涌往,密集
listless [ˈlɪstləs] listlessly: adj.adv. feeling tired and not interested in things冷漠的
mouthful [ˈmaʊθfʊl]: n. an amount of food or drink that you put into your mouth at one time一口
entrepreneur [ˌɑntrəprəˈnʊr]: n. someone who starts a new business or arranges business deals in order to make money, often in a way that involves financial risks企业家
pier [pɪr]: n. a structure that is built over and into the water so that boats can stop next to it or people can walk along it码头
foster [ˈfɑstər]: v. to help a skill, feeling, idea etc develop over a period of time SYN encourage, promote养育, 抚育, 培养
measure [ˈmeʒər]: v. to find the size, length, or amount of something, using standard units such as ↑inches, metres etc测量, 测度
conscription [kənˈskrɪpʃən]: n. when people are made to join the army, navy etc SYN draft征召
--------------------
concession stand: 小卖部
an article of sth.(furniture/a law): 一件/一条
result from sth.: 源自于...
the emergence of sth.: 某物的出现
Ferris wheels: 摩天轮
voting rights: 投票权
make brief excursion to sp.: 短途去某地
A be a short train ride from B: A离B有很短的火车距离
become accessible to sth.: 变得可以接触某物
be laden with sth.: be loaded with sth.装满了
national loyalty: 国家忠诚
take responsibility for sth.: 对某事负责
** sentence
dazzle [ˈdæz(ə)l]: v. if a very bright light dazzles you, it stops you from seeing properly for a short time(使)眼花, 眩耀
- The congenial host always regails his guest with dazzled public illuminations.
- The invention of new machines resulting from new source of energe dazzled people from the continent.
- A special kind of loom driven by the new steam engine dazzled masses in the Great Exhibition.
leisure [ˈleʒər]: n. time when you are not working or studying and can relax and do things you enjoy闲暇
- There will be more leisure facilities in our community.
- A new generation of people in China become more accessible to leisure facilities in their communities.
- The resort regailed its visitors with various of leisure facilities.
distinct [dɪˈstɪŋkt]: adj. clearly different or belonging to a different type独特的
- Virtually everyone appreciates the distinct favor of his food.
- Obviously, the distinct gate is used to exit and enter the Ferris wheels.
- His distinct performance may be the only funny thing on the show.
recreation [ˌrekriˈeɪʃ(ə)n]: n. an activity that you do for pleasure or amusement ⇨ hobby, pastime, leisure消遣, 娱乐
- The only recreation of my poor father was to grab a beer after work.
- She argued with her father: Saturday afternoon is for recreation.
- In spite of busy work, Saturday afternoon still remains for recreation.
railroad [ˈreɪlˌroʊd]: n. a railway or the railway铁路
- The railroad often had harsher working condition because of high temperature.
- I had to admit that I ran into my mother, who abandoned me on railroad when I was a bady.
- There are more accidents on railroad in the village.
streetcar [ˈstritˌkɑr]: n. a type of bus that runs on electricity along metal tracks in the road SYN tram British English有轨电车
- I will arrive your home by streetcar, you don't need to give me a lift.
- Going to work by streetcar, no wonder you have been late for meeting.
- We will move to our new house, which is convenient for us to take a streetcar.
brief [brif]: adj. continuing for a short time ⇨ vity简短的, 短暂的
- Five minutes before getting off work, let me make a brief speech.
- When the boss asked me to make a brief speech in front of a crew of workers, I quaked in every limb and in my soul.
- His brief explanation hasn't captured the hearts of his parents. 
seaside [ˈsiˌsaɪd]: adj.n. the seaside British English the areas or towns near the sea, where people go to enjoy themselves海边的, 海滨的
- The seaside mall is overcrowded because its customers come from all parts of England.
- The conservative ruler suffering from a rare disease is being treated at seaside resort.
- The various leisure facilities at seaside resort inspired awe in our family.
resort [rɪˈzɔrt]: n. a place where a lot of people go for holidays度假区
- Prices at seaside resort always rise dramatically on holidays.
- My wife is always asking me to make a visit to the resort hotel to which we still can't afford.
- I wish to go on a vacation with my cat at the resort hotel.
swarm [swɔrm]: v. a large group of insects, especially ↑bees, moving together涌往,密集
- It is said that the lost treasure was buried by the pirate near the seaside. This is why explorers swarmed upon the beach.
- You need to place the meat on the board where ants are swarming.
- The words is swarming on the bulletin board, which must be bug that a programmer made.
listless [ˈlɪstləs] listlessly: adj.adv. feeling tired and not interested in things没精打采的
- The pretty girl is listlessly replying letter to her ex-boyfriend who reported being killed in an action.
- He is not supposed to give the eulogy listlessly in public.
- The gangster listlessly asked for a ransom of 100 dollars.
mouthful [ˈmaʊθfʊl]: n. an amount of food or drink that you put into your mouth at one time一口
- He was asked to drink three mouthfuls of beer for being late. 
- You have only eaten a mouthful of meat in breakfast. You must be hungry now.
- It is obvious that our cat doesn't like your food, for she only ate a mouthful.
entrepreneur [ˌɑntrəprəˈnʊr]: n. someone who starts a new business or arranges business deals in order to make money, often in a way that involves financial risks企业家
- The authoritarian government was accused of leading its people to hate entrepreneurs.
- It is not easy for our country to foster a sophisticated entrepreneur.
- The Industrial Revolution added many entrepreneurs to the upper classes.
pier [pɪr]: n. a structure that is built over and into the water so that boats can stop next to it or people can walk along it码头
- We must park at the pier to have our boat repaired.
- Because of the former drowning examples, I was forbidden to chase at the pier.
- If the old pier inside the city hadn't been burnt down, the new pier outside the city wouldn't have been built.
foster [ˈfɑstər]: v. to help a skill, feeling, idea etc develop over a period of time SYN encourage, promote养育, 抚育, 培养
- The scientists in China went out their ways to foster new kind of wheat.
- The cat I have fostered since my youth is very precious to me.
- My manager told me that our company decided to foster me through new project.
measure [ˈmeʒər]: v. to find the size, length, or amount of something, using standard units such as ↑inches, metres etc测量, 测度
- The scientist was due to measure the iceburg which rose out over 100 feet of water at the Atlantic.
- Before assembling these parts, you'd better measure them.
- She has a habit of measuring chairs before she sits down.
conscription [kənˈskrɪpʃən]: n. when people are made to join the army, navy etc SYN draft征召
- The general planned out the conscription to the last detail.
- When news of conscription came to Beijing, people in northern cities didn't take it seriously.
- Beyond doubt, the so-called conscription turned out to be a pyramid scheme.
--------------------
concession stand: 小卖部
- I have a concession stand at the pier, this is why I made a large sum of money.
- The vicar immediately figured out that it was the owner of the concession stand.
- My grandfather dreamed of having a concession stand at seaside resort.
an article of sth.(furniture/a law): 一件/一条
- My wife complained that there was only an article of furniture in our new house. 
- The article of a law was used to levy taxes.
- Because my cat has broken several articles of furniture, I have to rent new apartment in New York.
result from sth.: 源自于...
- The player proclaimed his confidence resulted from his former performances.
- You don't need to be envious, his rise in salary resulted from his hard-working and you can also.
- His invention resulting from a daily complaint from a maid-servant led to the emergence of new kinds of factories.
the emergence of sth.: 某物的出现
- The emergence of evidence made the crime clear.
- The emergence of examiner scared out of my wits when I was cheating.
- The emergence of stray dogs at the edge of the forest frightened out of our wits.
Ferris wheels: 摩天轮
- The tickets of Ferris wheels have alreay been sold out.
- There must be thousands of visitors waiting in line for Ferris wheels.
- The photo of a couple making love in the compartment of Ferris wheels became popular in social media.
voting rights: 投票权
- Dwellers in our community are asking for voting rights.
- The absence of voting rights led to a serious revolts in the suburb of the city.
- A dweller lodged a complaint about the absence of voting rights.
make brief excursion to sp.: 短途去某地
- In my childhood, my parents always made brief excursion to Beijing.
- He was due to make brief execursion to Shanghai where he found amusement park exciting.
- She lost her temper when she found she was not able to make brief excursion to the resort hotel.
A be a short train ride from B: A离B有很短的火车距离
- Shanghai is only a short train ride from Hangzhou.
- The seaside must be a short train ride from our house.
- We like to make brief excursion to the resort hotel which is only a short train ride from our home.
become accessible to sth.: 变得可以接触某物
- Becoming accessible to computer, he indulged in playing video games.
- Becoming accessible to computer, he became skillful in programming.
- Becoming accessible to the microwave oven, she got familiar to cooking steak.
be laden with sth.: be loaded with sth.装满了
- Laden with vegetables and fruits, I drove to my aunt's house in town.
- The boat was laden with pumas, which are found in America.
- The boat was laden with sand and stones, which were used to build palace in Paris.
national loyalty: 国家忠诚
- No one could be suspicious of the national loyalty of the general.
- The authoritarian government failed to foster the national loyalty through a variety of movement.
- The break of trust in the national loyalty led to the collapse of the empire.
take responsibility for sth.: 对某事负责
- I must take responsibility for myself, which manifested in every manner.
- Fearing that she would be put out of business, she began to take responsibilty for what she did.
- The CEO must take responsiblity for the breakdown of guests' trust in our manufacturing goods.
** sentence2
dazzle [ˈdæz(ə)l]: v. if a very bright light dazzles you, it stops you from seeing properly for a short time(使)眼花, 眩耀
- The congenial host always regales his guest with dazzled public illuminations.
- The invention of new machines resulting from a new source of energy dazzled people from the continent.
- A special kind of loom driven by the new steam engine dazzled masses in the Great Exhibition.
leisure [ˈleʒər]: n. time when you are not working or studying and can relax and do things you enjoy闲暇
- There will be more leisure facilities in our community.
- A new generation of people in China becomes more accessible to leisure facilities in their communities.
- The resort regaled its visitors with various leisure facilities.
distinct [dɪˈstɪŋkt]: adj. clearly different or belonging to a different type独特的
- Virtually everyone appreciates the distinct flavor of his food.
- Obviously, the distinct gate is used to exit and enter the Ferris wheels.
- His distinct performance may be the only funny thing on the show.
recreation [ˌrekriˈeɪʃ(ə)n]: n. an activity that you do for pleasure or amusement ⇨ hobby, pastime, leisure消遣, 娱乐
- The only recreation of my poor father was to grab a beer after work.
- She argued with her father: Saturday afternoon is for recreation.
- In spite of busy work, Saturday afternoon still remains for recreation.
railroad [ˈreɪlˌroʊd]: n. a railway or the railway铁路
- The railroad often had harsher working conditions because of high temperatures.
- I had to admit that I ran into my mother, who abandoned me on the railroad when I was a baby.
- There are more accidents on the railroad in the village.
streetcar [ˈstritˌkɑr]: n. a type of bus that runs on electricity along metal tracks in the road SYN tram British English有轨电车
- I will arrive at your home by streetcar, you don't need to give me a lift.
- Going to work by streetcar, no wonder you have been late for the meeting.
- We will move to our new house, which is convenient for taking a streetcar.
brief [brif]: adj. continuing for a short time ⇨ vity简短的, 短暂的
- Five minutes before getting off work, let me make a brief speech.
- When the boss asked me to make a brief speech in front of a crew of workers, I quaked in every limb and in my soul.
- His brief explanation hasn't captured the hearts of his parents. 
seaside [ˈsiˌsaɪd]: adj.n. the seaside British English the areas or towns near the sea, where people go to enjoy themselves海边的, 海滨的
- The seaside mall is overcrowded because its customers come from all parts of England.
- The conservative ruler suffering from a rare disease is being treated at the seaside resort.
- The various leisure facilities at seaside resort inspired awe in our family.
resort [rɪˈzɔrt]: n. a place where a lot of people go for holidays度假区
- Prices at seaside resorts always rise dramatically on holidays.
- My wife is always asking me to make a visit to the resort hotel which we still can't afford.
- I wish to go on a vacation with my cat at the resort hotel.
swarm [swɔrm]: v. a large group of insects, especially ↑bees, moving together涌往,密集
- It is said that the lost treasure was buried by the pirate near the seaside. This is why explorers swarmed upon the beach.
- You need to place the meat on the board where ants are swarming.
- The words are swarming on the bulletin board, which must be a bug that a programmer made.
listless [ˈlɪstləs] listlessly: adj.adv. feeling tired and not interested in things没精打采的
- The pretty girl is listlessly replying letter to her ex-boyfriend who reported being killed in an action.
- He is not supposed to give the eulogy listlessly in public.
- The gangster listlessly asked for a ransom of 100 dollars.
mouthful [ˈmaʊθfʊl]: n. an amount of food or drink that you put into your mouth at one time一口
- He was asked to drink three mouthfuls of beer for being late. 
- You have only eaten a mouthful of meat for breakfast. You must be hungry now.
- It is obvious that our cat doesn't like your food, for she only ate a mouthful.
entrepreneur [ˌɑntrəprəˈnʊr]: n. someone who starts a new business or arranges business deals in order to make money, often in a way that involves financial risks企业家
- The authoritarian government was accused of leading its people to hate entrepreneurs.
- It is not easy for our country to foster a sophisticated entrepreneur.
- The Industrial Revolution added many entrepreneurs to the upper classes.
pier [pɪr]: n. a structure that is built over and into the water so that boats can stop next to it or people can walk along it码头
- We must park at the pier to have our boat repaired.
- Because of the former drowning examples, I was forbidden to chase at the pier.
- If the old pier inside the city hadn't been burnt down, the new pier outside the city wouldn't have been built.
foster [ˈfɑstər]: v. to help a skill, feeling, idea etc develop over a period of time SYN encourage, promote养育, 抚育, 培养
- The scientists in China went out of their way to foster new kinds of wheat.
- The cat I have fostered since my youth is very precious to me.
- My manager told me that our company decided to foster me through the new project.
measure [ˈmeʒər]: v. to find the size, length, or amount of something, using standard units such as ↑inches, metres etc测量, 测度
- The scientist was due to measure the iceberg which rose out over 100 feet of water at the Atlantic.
- Before assembling these parts, you'd better measure them.
- She has a habit of measuring chairs before she sits down.
conscription [kənˈskrɪpʃən]: n. when people are made to join the army, navy etc SYN draft征召
- The general planned out the conscription to the last detail.
- When news of conscription came to Beijing, people in northern cities didn't take it seriously.
- Beyond doubt, the so-called conscription turned out to be a pyramid scheme.
--------------------
concession stand: 小卖部
- I have a concession stand at the pier, this is why I made a large sum of money.
- The vicar immediately figured out that it was the owner of the concession stand.
- My grandfather dreamed of having a concession stand at a seaside resort.
an article of sth.(furniture/a law): 一件/一条
- My wife complained that there was only an article of furniture in our new house. 
- The article of a law was used to levy taxes.
- Because my cat has broken several articles of furniture, I have to rent a new apartment in New York.
result from sth.: 源自于...
- The player proclaimed his confidence resulted from his former performances.
- You don't need to be envious, his rise in salary resulted from his hard work and you can also.
- His invention resulting from a daily complaint from a maid-servant led to the emergence of new kinds of factories.
the emergence of sth.: 某物的出现
- The emergence of evidence made the crime clear.
- The emergence of an examiner scared me out of my wits when I was cheating.
- The emergence of stray dogs at the edge of the forest frightened us out of our wits.
Ferris wheels: 摩天轮
- The tickets for Ferris wheels have already been sold out.
- There must be thousands of visitors waiting in line for Ferris wheels.
- The photo of a couple making love in the compartment of Ferris wheels became popular on social media.
voting rights: 投票权
- Dwellers in our community are asking for voting rights.
- The absence of voting rights led to serious revolts in the suburbs of the city.
- A dweller lodged a complaint about the absence of voting rights.
make a brief excursion to sp.: 短途去某地
- In my childhood, my parents always made a brief excursion to Beijing.
- He was due to make a brief excursion to Shanghai where he found the amusement park exciting.
- She lost her temper when she found she was not able to make a brief excursion to the resort hotel.
A be a short train ride from B: A离B有很短的火车距离
- Shanghai is only a short train ride from Hangzhou.
- The seaside must be a short train ride from our house.
- We like to make a brief excursion to the resort hotel which is only a short train ride from our home.
become accessible to sth.: 变得可以接触某物
- Becoming accessible to computers, he indulged in playing video games.
- Becoming accessible to computers, he became skillful in programming.
- Becoming accessible to the microwave oven, she became an expert at cooking steak.
be laden with sth.: be loaded with sth.装满了
- Laden with vegetables and fruits, I drove to my aunt's house in town.
- The boat was laden with pumas, which are found in America.
- The boat was laden with sand and stones, which were used to build a palace in Paris.
national loyalty: 国家忠诚
- No one could be suspicious of the national loyalty of the general.
- The authoritarian government failed to foster national loyalty through a variety of movements.
- The break of trust in national loyalty led to the collapse of the empire.
take responsibility for sth.: 对某事负责
- I must take responsibility for myself, which manifested in every manner.
- Fearing that she would be put out of business, she began to take responsibility for what she did.
- The CEO must take responsibility for the breakdown of guests' trust in our manufacturing goods.
** summary
In the late nineteenth century,
	a second Industrial Revolution transformed the environment
		bringing new industries, new source of energy, and new goods.
Many believed that scientific and technological achievements would solve all problems.
With a mass society came improvements for the lower class, who also enjoyed mass leisure.
The emergence of weekend and mass transportation--railroads and streetcars--
	enabled even the lowest-paid workers to make brief execurions to beaches and amusement parks.
One disgusted upper-class complained the new day-trippers swarmed upon the beach
	wandering listlessly about.
However, entrepreneurs in resort areas
	built piers laden with food, drink, and entertainment to serve them.
The governments of European nation-states began to foster national loyalty,
	form vast armies by conscription,
	and take more responsiblity for public health and housing measures in their cities.
The growth of the middle class led to the triumph of liberal practices:
	constitutional government, parliaments, and principles of equality.
With political democracy came a new mass politics and a new mass press.
** summary2
In the late nineteenth century,
	a second Industrial Revolution transformed the environment
		bringing new industries, new sources of energy, and new goods.
Many believed that scientific and technological achievements would solve all problems.
With a mass society came improvements for the lower class, who also enjoyed mass leisure.
The emergence of weekend and mass transportation--railroads and streetcars--
	enabled even the lowest-paid workers to make brief excursions to beaches and amusement parks.
One disgusted upper class complained the new day-trippers swarmed upon the beach
	wanderring listlessly about.
However, entrepreneurs in resort areas
	built piers laden with food, drink, and entertainment to serve them.
The governments of European nation-states began to foster national loyalty,
	form vast armies by conscription,
	and take more responsibility for public health and housing measures in their cities.
The growth of the middle class led to the triumph of liberal practices:
	Constitutional government, parliaments, and principles of equality.
With political democracy came a new mass politics and a new mass press.
