#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 25 British troops in the trenches wait for the signal to attack
#+begin_verse
On July 1, 1916, British and French infantry forces attacked German defensive lines
	along a 25-mile front near the Somme River in France.
Each soldier carried almost 70 pounds of equipment,
	making it impossible to move much quicker than a slow walk.
German machine guns soon opened fire:
	'We were able to see our comrades move forward in an attempt to cross No-Man's Land,
		only to be mown down like meadow grass,' recalled one British soldier.
'I felt sick at the sight of this carnage and remember weeping.'
In one day, more than 21,000 British soldiers died.
After six months of fighting, the British had advanced 5 miles;
	one million British, French, and German soldiers had been killed or wounded.
Philip Gibbs, an English war correspondent,
	described what he saw in the German trenches that the British forces overran: Victory...
Some of the German dead were young boys, too young to be killed for old men's crimes,
	and others might have been old or young.
One could not tell because they had no faces, and were just masses of raw flesh in rags of uniforms.
Legs and arms lay separate without any bodies thereabout.

World War I (1914--1918) was the defining event of the twentieth century.
It devastated the prewar economic, social, and political order of Europe,
	and its uncertain outcome prepared the way for an even more destructive war.
Overwhelmed by the size of its battles,
		the extent of its casualties, and its effects on all facets of life,
	contemporaries referred to it simply as the 'Great War.'

The Great War was all the more disturbing to Europeans
	because it came after what many considered an age of progress.
There had been international crises before 1914,
	but somehow Europeans had managed to avoid serious and prolonged military confrontations.
Material prosperity and a fervid belief in scientific and technological progress
	had convinced many people
		that the world was on the verge of creating the utopia that humans had dreamed of for centuries.

After 1918, it was no longer possible
	to maintain naive illusions about the progress of Western civilization.
As World War I was followed by the destructiveness of World War II
		and the mass murder machines of totalitarian regimes,
	it became all too apparent that instead of a utopia, European civilization had become a nightmare.
The Great War resulted not only in great loss of life and property
	but also in the annihilation of one of the basic intellectual precepts
		on which Western civilization had been thought to have been founded---the belief in progress.
World War I and the revolutions it spawned
	can properly be seen as the first stage in the crisis of the twentieth century.
#+end_verse
** expression
troop [trup]: n. soldiers in an organized group军队[得复数形式]
trench [trentʃ]: n. a long narrow hole dug into the surface of the ground沟渠, 堑壕
infantry [ˈɪnfəntri]: n. soldiers who fight on foot步兵, 步兵团
defensive [dɪˈfensɪv]: adj. used or intended to protect someone or something against attack OPP offensive防御用的, 自卫的
front [frʌnt]: n. the area where fighting happens in a war SYN front line前线
comrade [ˈkɑmˌræd]: n. formal a friend, especially someone who shares difficult work or danger同志
meadow [ˈmedoʊ]: n. a field with wild grass and flowers草地
weep [wip]: v. or literary to cry, especially because you feel very sad哭泣
wound [waʊnd]: v. to injure someone with a knife, gun etc击伤
correspondent [ˌkɔrəˈspɑndənt]: n. someone who is employed by a newspaper or a television station etc to report news from a particular area or on a particular subject ⇨ reporter通讯记者, 通信者
overrun [ˌoʊvərˈrʌn]: v. if soldiers overrun a place, they take control of it占领
thereabout [ˌðerə'baʊt]: adv. near a particular time, place, number etc, but not exactly周围
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
prolonged [prəˈlɒŋd]: adj. continuing for a long time延长的, 拖延的
confrontation [ˌkɑnfrənˈteɪʃ(ə)n]: n. a situation in which there is a lot of angry disagreement between two people or groups对峙
fervid [ˈfɜrvɪd] fervidly: adj.adv. believing or feeling something too strongly过分热烈的
annihilate [əˈnaɪəˌleɪt] annihilation: v.n. to destroy something or someone completely消灭, 歼灭
spawn [spɔn]: v. to make a series of things happen or start to exist大量产生
--------------------
wait for the signal to do sth.: 等待信号去做某事
70 pounds of sth.: 70磅的某物
open fire: 开火
in an attempt to do sth.: (状语)尝试做某事
mown them down: 扫射
at the sight of sth.: 一看到某物
masses of sth.: 大块大量的某物
raw flesh: 生肉
in rags of uniforms: 穿着破烂的制服
the defining event: 决定性事件
prepare the way for sth./doing sth.: 为某物铺平道路
on all facets of life: 在生活的各个方面
on the verge of sth./doing sth.: 在某事/做某事的边缘
** sentence
troop [trup]: n. soldiers in an organized group军队[得复数形式]
- The general promised to dedicate himself to British troops.
- The statue has been elected in memory of the valient troops.
- The troops named after the prince was used as the body guard of the king.
trench [trentʃ]: n. a long narrow hole dug into the surface of the ground沟渠, 堑壕
- There was a time when soldiers fought in the trench.
- If majesty don't pay money to the noble, a band of troops in the trench will march into the city.
- The general made the remarkable discovery that soldiers hiding in the trench reduces the death rate.
infantry [ˈɪnfəntri]: n. soldiers who fight on foot步兵, 步兵团
- Only a single infantry? A member of his privy council exclaimed.
- Because of the loss of the infantry, two city-states were at war with each other.
- The lad was too young to be enrolled in the infantry.
defensive [dɪˈfensɪv]: adj. used or intended to protect someone or something against attack OPP offensive防御用的, 自卫的
- The Great Wall was a defensive measure against the attacks of the nomads.
- The League of Nations, conceived as a defensive measure to provide for collective securty, failed to work well.
- The gun, conceived as a defensive measure, shouldn't have brought outside your house.
front [frʌnt]: n. the area where fighting happens in a war SYN front line前线
- The front line is only 12 miles outside the city of Paris.
- The warrior came to be killed in an action in the front line.
- He soon made a name for himself, for he was brave in the front line.
comrade [ˈkɑmˌræd]: n. formal a friend, especially someone who shares difficult work or danger同志
- These days the word comrade was referred to as a gay in China.
- The so-called comrade was going to ask you for protection money.
- The comrade in obscurity turns out to be a spy.
meadow [ˈmedoʊ]: n. a field with wild grass and flowers草地
- There are vivid stories about the Red Army marching in meadows.
- The infantry will undertake an arduous journey that they will cross the vast meadow on foot.
- The explorer often risks his life to cross meadows on foot.
weep [wip]: v. or literary to cry, especially because you feel very sad哭泣
- The owner of the jewelry shop is weeping, for thousands of pounds of jewelry was stolen by gangsters.
- People affected by the Great Depression are weeping and need protection from our government.
- Listen, women who are forced to wear mask in public are weeping.
wound [waʊnd]: n.v. to injure someone with a knife, gun etc击伤
- The cat suffering from wound must have been abused.
- The prince who was wounded in the battle by no means assumed military power in the country.
- The prince dedicated his life to the country and died from wound in a battle against the Asia nomads.
correspondent [ˌkɔrəˈspɑndənt]: n. someone who is employed by a newspaper or a television station etc to report news from a particular area or on a particular subject ⇨ reporter通讯记者, 通信者
- The correspondent was hired to write an article about the situation of women who must wear mask in public.
- As long as the nineteenth century, regimes took correspondents seriously.
- The correspondent offered to pay him a large sum of money to keep the secrety.
overrun [ˌoʊvərˈrʌn]: v. if soldiers overrun a place, they take control of it占领
- Keep up with the command from the king, the British infantry had overrun the trenches in three days.
- A bang of gangster who didn't receive protection money overran the fancy dress party.
- The Young Crusades was impatient to overrun the aristocratic castle.
thereabout [ˌðerə'baʊt]: adv. near a particular time, place, number etc, but not exactly周围
- Finding no fruit thereabout, the man on the desert island starved to death.
- Without his mother thereabout, the boy let out a cry.
- Without my wife thereabout, my loneliness is killing me.
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
- I am genuinely sorry that the outcome of election is out of our imagination.
- The outcome of the meeting was to arrange a final peace settlement.
- The outcome of the meeting still remains a mystery.
prolonged [prəˈlɒŋd]: adj. continuing for a long time延长的, 拖延的
- A slip of the tongue led to the prolonged applause.
- The news of capturing the puma at large led to a prolonged applause. 
- The prolonged class let the poor guy be in his urine.
confrontation [ˌkɑnfrənˈteɪʃ(ə)n]: n. a situation in which there is a lot of angry disagreement between two people or groups对峙
- Overruning the territory in the plain, the king is risking the confrontation with Russia.
- Surrendering the castle to the gangster, the bourgeois avoided the confrontation.
- The prince was reluctant to pay protection money, there must be a confrontation between him and the signor Hookward.
fervid [ˈfɜrvɪd] fervidly: adj.adv. believing or feeling something too strongly过分热烈的
- In fact, he treated me fervidly, which gave me a sense of danger.
- I have a feeling of unease about his fervid welcome.
- I received a fervid welcome from my dog, who licked my hands and pounced on me.
annihilate [əˈnaɪəˌleɪt] annihilation: v.n. to destroy something or someone completely消灭, 歼灭
- To keep up with the command from our majesty, the troops must annihilate the Asiatic nomads overnight.
- With the infantry annihilated, our nation gained its indepence from the empire.
- With the infantry annihilated, both countries agreed on how to achive the clauses of the treaty.
spawn [spɔn]: v. to make a series of things happen or start to exist大量产生
- My wife is complaining about the spawned flies in the kitchen.
- The French Revolution spawned a lot of opportunties for peasants.
- The growth of industry in the twon spawned a lot of jobs.
--------------------
wait for the signal to do sth.: 等待信号去做某事
- It seems that the cat is wait for the signal to be fed up.
- You don't need to wait for the signal to do homework.
- The dealer must wait for the signal to make a deal.
70 pounds of sth.: 70磅的某物
- Carrying 70 pounds of gift, I was soon out of breath.
- Carrying 70 pounds of gift, he received a warm welcome in hometown.
- The dealers have stolne 70 pounds of ingredient for drug from the factory.
open fire: 开火
- The troops didn't hesitate to open fire.
- Not hesitating to open fire, he lost no time in overrunning the district.
- Not hesitating to open fire, he lost his wife who was kidnapped by the enemy.
in an attempt to do sth.: (状语)尝试做某事
- He wandered about the street in an attempt to ask for protection money.
- He sacrificed his wife for the position in an attempt to assum political power.
- My cat jumped from the desk in an attempt to get the snack.
mow them down: 扫射
- The enemy is trying to mow us down in the plain.
- The enemy goes out of its way to mow us down.
- Mowing them down, we will overrun the city in two days.
at the sight of sth.: 一看到某物
- I quaked in every limb and in my soul at the sight of the snake.
- I felt that it was worth traveling the city at the sight of the God statue.
- At the sight of the statue I recognized that it was made by a famous artist.
masses of sth.: 大块大量的某物
- Masses of flesh are being consummed by these tigers in the zoo. 
- There are masses of raw flesh in the cage.
- Masses of raw flesh were found in the trenches.
raw flesh: 生肉
- Eating raw flesh is good for your cat's health.
- My cat has a habit of eating raw flesh.
- Enjoying enough raw flesh, my cat began to stretch his body.
in rags of uniforms: 穿着破烂的制服
- My precious, you looks really sexy in rags of uniform.
- If you fought battles when the industry was growing, you wouldn't have been dressed in rags of uniform.
- In their misery, the unemployed worker begged for food in rags of overalls.
the defining event: 决定性事件
- The defining event of our school this year was that our headmaster decided to retire.
- The defining event of the zoo this year was that it rent pandas from China.
- The defining event of our family this year was that my wife and I were both unemployed.
prepare the way for sth./doing sth.: 为某物铺平道路
- The king had some of his ministers hung to prepare the way for his son's succession to the throne.
- Being exercised in battles prepared the way for his new job.
- Your mother prepared the way for you to go to university.
on all facets of life: 在生活的各个方面
- The death of his mother in his youth exerted tremendous effects on all facets of his life.
- Your wife is more sophisticated than you on all facets of life.
- The government exterted influences on all facets of masses life.
on the verge of sth./doing sth.: 在某事/做某事的边缘
- On the verge of getting angry, you'd better cease to talk to her now. 
- On the verge of getting angry, I breathed in a mouthful of air to calm down.
- On the verge of getting angry, I went oustide and calmed my nerve.
** sentence2
troop [trup]: n. soldiers in an organized group军队[得复数形式]
- The general promised to dedicate himself to British troops.
- The statue has been erected in memory of the valiant troops.
- The troops named after the prince were used as the bodyguard of the king.
trench [trentʃ]: n. a long narrow hole dug into the surface of the ground沟渠, 堑壕
- There was a time when soldiers fought in the trench.
- If majesty doesn't pay money to the noble, a band of troops in the trench will march into the city.
- The general made the remarkable discovery that soldiers hiding in the trench reduces the death rate.
infantry [ˈɪnfəntri]: n. soldiers who fight on foot步兵, 步兵团
- Only a single infantry? A member of his privy council exclaimed.
- Because of the loss of the infantry, two city-states were at war with each other.
- The lad was too young to be enrolled in the infantry.
defensive [dɪˈfensɪv]: adj. used or intended to protect someone or something against attack OPP offensive防御用的, 自卫的
- The Great Wall was a defensive measure against the attacks of the nomads.
- The League of Nations, conceived as a defensive measure to provide for collective securty, failed to work well.
- The gun, conceived as a defensive measure, shouldn't have been brought outside your house.
front [frʌnt]: n. the area where fighting happens in a war SYN front line前线
- The front line is only 12 miles outside the city of Paris.
- The warrior came to be killed in an action in the front line.
- He soon made a name for himself, for he was brave in the front line.
comrade [ˈkɑmˌræd]: n. formal a friend, especially someone who shares difficult work or danger同志
- These days the word comrade is referred to as gay in China.
- The so-called comrade was going to ask you for protection money.
- The comrade in obscurity turns out to be a spy.
meadow [ˈmedoʊ]: n. a field with wild grass and flowers草地
- There are vivid stories about the Red Army marching in meadows.
- The infantry will undertake an arduous journey, they will cross the vast meadow on foot.
- The explorer often risks his life to cross meadows on foot.
weep [wip]: v. or literary to cry, especially because you feel very sad哭泣
- The owner of the jewelry shop is weeping, for thousands of pounds of jewelry was stolen by gangsters.
- People affected by the Great Depression are weeping and need protection from our government.
- Listen, women who are forced to wear masks in public are weeping.
wound [waʊnd]: n.v. to injure someone with a knife, gun etc击伤
- The cat suffering from wounds must have been abused.
- The prince who was wounded in the battle by no means assumed military power in the country.
- The prince dedicated his life to the country and died from wounds in a battle against the Asia nomads.
correspondent [ˌkɔrəˈspɑndənt]: n. someone who is employed by a newspaper or a television station etc to report news from a particular area or on a particular subject ⇨ reporter通讯记者, 通信者
- The correspondent was hired to write an article about the situation of women who must wear masks in public.
- As long as the nineteenth century, regimes took correspondents seriously.
- The correspondent offered to pay him a large sum of money to keep the secret.
overrun [ˌoʊvərˈrʌn]: v. if soldiers overrun a place, they take control of it占领
- Keep up with the command from the king, the British infantry had overrun the trenches in three days.
- A bang of gangsters who didn't receive protection money overran the fancy dress party.
- The Young Crusades were impatient to overrun the aristocratic castle.
thereabout [ˌðerə'baʊt]: adv. near a particular time, place, number etc, but not exactly周围
- Finding no fruit thereabout, the man on the desert island starved to death.
- Without his mother thereabout, the boy let out a cry.
- Without my wife thereabout, my loneliness is killing me.
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
- I am genuinely sorry that the outcome of the election is out of our imagination.
- The outcome of the meeting was to arrange a final peace settlement.
- The outcome of the meeting still remains a mystery.
prolonged [prəˈlɒŋd]: adj. continuing for a long time延长的, 拖延的
- A slip of the tongue led to the prolonged applause.
- The news of capturing the puma at large led to a prolonged applause. 
- The prolonged class let the poor guy be in his urine.
confrontation [ˌkɑnfrənˈteɪʃ(ə)n]: n. a situation in which there is a lot of angry disagreement between two people or groups对峙
- Overrunning the territory in the plain, the king is risking a confrontation with Russia.
- Surrendering the castle to the gangster, the bourgeois avoided the confrontation.
- The prince was reluctant to pay protection money, there must be a confrontation between him and the signor Hookward.
fervid [ˈfɜrvɪd] fervidly: adj.adv. believing or feeling something too strongly过分热烈的
- In fact, he treated me fervidly, which gave me a sense of danger.
- I have a feeling of unease about his fervid welcome.
- I received a fervid welcome from my dog, who licked my hands and pounced on me.
annihilate [əˈnaɪəˌleɪt] annihilation: v.n. to destroy something or someone completely消灭, 歼灭
- To keep up with the command from our majesty, the troops must annihilate the Asiatic nomads overnight.
- With the infantry annihilated, our nation gained its independence from the empire.
- With the infantry annihilated, both countries agreed on how to achieve the clauses of the treaty.
spawn [spɔn]: v. to make a series of things happen or start to exist大量产生
- My wife is complaining about the spawned flies in the kitchen.
- The French Revolution spawned a lot of opportunities for peasants.
- The growth of industry in the town spawned a lot of jobs.
--------------------
wait for the signal to do sth.: 等待信号去做某事
- It seems that the cat is waiting for the signal to be fed up.
- You don't need to wait for the signal to do homework.
- The dealer must wait for the signal to make a deal.
70 pounds of sth.: 70磅的某物
- Carrying 70 pounds of gifts, I was soon out of breath.
- Carrying 70 pounds of gifts, he received a warm welcome in his hometown.
- The dealers have stolen 70 pounds of ingredients for drugs from the factory.
open fire: 开火
- The troops didn't hesitate to open fire.
- Not hesitating to open fire, he lost no time in overrunning the district.
- Not hesitating to open fire, he lost his wife who was kidnapped by the enemy.
in an attempt to do sth.: (状语)尝试做某事
- He wandered about the street in an attempt to ask for protection money.
- He sacrificed his wife for the position in an attempt to assume political power.
- My cat jumped from the desk in an attempt to get the snack.
mow them down: 扫射
- The enemy is trying to mow us down in the plain.
- The enemy goes out of its way to mow us down.
- Mowing them down, we will overrun the city in two days.
at the sight of sth.: 一看到某物
- I quaked in every limb and in my soul at the sight of the snake.
- I felt that it was worth traveling the city at the sight of the God statue.
- At the sight of the statue I recognized that it was made by a famous artist.
masses of sth.: 大块大量的某物
- Masses of flesh are being consumed by these tigers in the zoo. 
- There are masses of raw flesh in the cage.
- Masses of raw flesh were found in the trenches.
raw flesh: 生肉
- Eating raw flesh is good for your cat's health.
- My cat has a habit of eating raw flesh.
- Enjoying enough raw flesh, my cat began to stretch his body.
in rags of uniforms: 穿着破烂的制服
- My precious, you look really sexy in rags of uniform.
- If you fought battles when the industry was growing, you wouldn't have been dressed in rags of uniform.
- In their misery, the unemployed workers begged for food in rags of overall.
the defining event: 决定性事件
- The defining event of our school this year was that our headmaster decided to retire.
- The defining event of the zoo this year was that it rented pandas from China.
- The defining event of our family this year was that my wife and I were both unemployed.
prepare the way for sth./doing sth.: 为某物铺平道路
- The king had some of his ministers hung to prepare the way for his son's succession to the throne.
- Being exercised in battles prepared the way for his new job.
- Your mother prepared the way for you to go to university.
on all facets of life: 在生活的各个方面
- The death of his mother in his youth exerted tremendous effects on all facets of his life.
- Your wife is more sophisticated than you on all facets of life.
- The government exerted influences on all facets of the mass's life.
on the verge of sth./doing sth.: 在某事/做某事的边缘
- On the verge of getting angry, you'd better cease to talk to her now. 
- On the verge of getting angry, I breathed in a mouthful of air to calm down.
- On the verge of getting angry, I went outside and calmed my nerves.
** summary
On July 1, 1916, British and French infantry forces attacked German defensive lines
	along 25-mile front near the Somme River.
Because of heavy equipment,
	each soldier moved slowly and was mown down like meadow grass
		while German machine guns opened fire.
In one day, more than 21,000 British soldiers died.
After six months of fighting, the British had advanced 5 miles;
	one million British, French, and German soldiers had been killed.
World War I devastated the prewar economic, social, and political order of Europe,
	and was followed the World War II.
Before 1914, Europeans managed to avoid serious and prolonged military confrontations.
Material properity and scientific and technological progress convinced many people
	that creating the utopia was at hand.
After 1918, the Great War resulted not only in great loss of life and property
	but also in the annilation of the belief in progress.
** summary2
On July 1, 1916, British and French infantry forces attacked German defensive lines
	along a 25-mile front near the Somme River.
Because of heavy equipment,
	each soldier moved slowly and was mown down like meadow grass
		while German machine guns opened fire.
In one day, more than 21,000 British soldiers died.
After six months of fighting, the British had advanced 5 miles;
	one million British, French, and German soldiers had been killed.
World War I devastated the prewar economic, social, and political order of Europe,
	and was followed by the World War II.
Before 1914, Europeans had managed to avoid serious and prolonged military confrontations.
Material prosperity and scientific and technological progress convinced many people
	that creating a utopia was at hand.
After 1918, the Great War resulted not only in great loss of life and property
	but also in the annihilation of the belief in progress.
