#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 30 The disintegration of the Soviet Union and terrorist attacks
#+begin_verse
By 1985, after four decades of the Cold War,
	Westerners had become accustomed to a division of Europe between West and East
		that seemed to be permanent.
A prosperous Western Europe allied with the United States
	stood opposed to a still-struggling Eastern Europe
		that remained largely subject to the Soviet Union.
The division of Germany symbolized the new and seemingly well-established order.
Yet in just a few years,
	a revolutionary upheaval in the Soviet Union and Eastern Europe
		brought an end to the Cold War and to the division of postwar Europe.
Even the Soviet Union ceased to exist as a nation.
And much of this can be traced to the reform efforts of one man, Mikhail Gorbachev.

On August 19, 1991,
	a group of Soviet leaders opposed to reform arrested Gorbachev, the president of the Soviet Union,
		and tried to seize control of the government.
Spontaneously, hundreds of thousands of Russians, led by Boris Yeltsin,
	poured into the streets of Moscow and Leningrad to protest the attempted coup.
Some army units, sent out to enforce the wishes of the upstart leaders,
		defected to Yeltsin’s side,
	and within days, the usurpers were forced to surrender.
This failed attempt to seize power had unexpected results
	as Russia and many of the other Soviet republics turned their backs on the government
		and declared their independence.
By the end of 1991, the Soviet Union---one of the largest empires in world history---
		had come to an astonishingly swift end,
	and a new era of cooperation
		between the successor states of the old Soviet Union and the nations of the West had begun.

As the world adjusted to the transformation from Cold War to post--Cold War sensibilities,
	other changes shaped the Western outlook.
The demographic face of European countries changed
	as massive numbers of immigrants created more ethnically diverse populations.
New artistic and intellectual currents, the continued advance of science and technology,
		the emergence of the Digital Age, the surge of the women’s liberation movement---
	all spoke of a vibrant, ever-changing world.
At the same time, a devastating terrorist attack on the World Trade Center in New York City
		and the Pentagon outside Washington, D.C., in 2001
	made the Western world vividly aware of its vulnerability to international terrorism.
But most important of all,
	Western nations, like all nations on the planet,
		had become acutely aware of the political and economic interdependence of the world's nations
			and the global nature of the challenges of the twenty-first century.
#+end_verse
** expression
Westerner [ˈwestərnər]: n. someone from the western part of the world西方人
permanent [ˈpɜrmənənt]: adj. continuing to exist for a long time or for all the time in the future OPP temporary永久的, 持久的
symbolize [ˈsɪmbəˌlaɪz]: v. if something symbolizes a quality, feeling etc, it represents it象征, 用符号表现
spontaneously [spɔnˈtenɪəslɪ] spontaneous: adv.adj. something that is spontaneous has not been planned or organized, but happens by itself, or because you suddenly feel you want to do it自发的, 自然产生的
protest [prəˈtest]: v. something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products抗议
coup [ku]: n. a sudden and sometimes violent attempt by citizens or the army to take control of the government SYN coup d'état政变
usurp [juˈzɜrp]: v. formal to take someone else’s power, position, job etc when you do not have the right to篡夺, 篡位
successor [səkˈsesər]: n. someone who takes a job or position previously held by someone else ⇨ predecessor继承者, 接任者
outlook [ˈaʊtˌlʊk]: n. your general attitude to life and the world世界观
demographic [ˌdeməˈɡræfɪk]: adj. demographics [plural] information about a group such as the people who live in a particular area人口统计学的
ethnic [ˈeθnɪk] ethnically: adj.adv. relating to a particular race, nation, or tribe and their customs and traditions种族的
diverse [daɪˈvɜrs]: adj. very different from each other不同的
digital [ˈdɪdʒɪt(ə)l]: adj. using a system in which information is recorded or sent out electronically in the form of numbers, usually ones and zeros数字的
surge [sɜrdʒ]: v.n. to suddenly move very quickly in a particular direction汹涌, 澎湃,涌入
vibrant [ˈvaɪbrənt]: adj. full of activity or energy in a way that is exciting and attractive SYN lively活跃的
pentagon [ˈpentəˌɡɑn]: n. a flat shape with five sides and five angles五角形
acutely [əˈkjutli]: adv. feeling or noticing something very strongly剧烈地
--------------------
be allied with sb./sth.: 与某人结盟
be opposed to sb./sth.: 反对某事/某人
remain subject to sb./sth.: 继续服从于...
bring an end to sth.: 终结某事
be traced to sth.: 追溯到某事物
seize control of sth.: 控制某事物
pour into sp.: 涌入某地
enforce the wishes of sb.: 执行某人的意愿
defect to sb's side: 投靠某一边
turn one's back on sb./sth.: 背弃某人/某事物
come to an end: 结束
adjust to sth./sb.: 适应某事物/某人
most important of all, ...: 最重要的, ...
** sentence
Westerner [ˈwestərnər]: n. someone from the western part of the world西方人
- The bridge was said to be named after a Westerner in ancient times.
- Our government must take these Westerners into account for our safety.
- These Westerners used to be described as barbarians who behaved rudely.
permanent [ˈpɜrmənənt]: adj. continuing to exist for a long time or for all the time in the future OPP temporary永久的, 持久的
- The division between you and dad seems to remain permanent.
- THe noble ganster's name may remain permanent, for when he died people gave him a state funeral.
- He never dreams of being offered a permanent job in his university.
symbolize [ˈsɪmbəˌlaɪz]: v. if something symbolizes a quality, feeling etc, it represents it象征, 用符号表现
- The withering flower may symbolize your dying wife.
- The dog that symbolized our friendship was killed in an action.
- Needless to say, the statue which French people presented to America symbolized their friendship.
spontaneously [spɔnˈtenɪəslɪ] spontaneous: adv.adj. something that is spontaneous has not been planned or organized, but happens by itself, or because you suddenly feel you want to do it自发的, 自然产生的
- Spontaneously, I double check the program he made yesterday.
- Spontaneously, I drew the enormous object as faintly as possible.
- Spontaneously, my cat fell fast asleep on my legs.
protest [prəˈtest]: v.n. something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products抗议
- These protests in the streets proved effective, for the authoritarian regime soon gave up their policy about the pestilence.
- If the protest were unsettled, there would be a civil war in our country.
- These immigrants protested for unfair treatments in force market.
coup [ku]: n. a sudden and sometimes violent attempt by citizens or the army to take control of the government SYN coup d'état政变
- A fraction of the party was due to initiate a coup on National Day.
- The coup made the prince assume political and military power in the Holy Roman Empire.
- Fearing of a coup, the king ordered his men to kill the peasants in the palace.
usurp [juˈzɜrp]: v. formal to take someone else’s power, position, job etc when you do not have the right to篡夺, 篡位
- In spite of great achievement in domestic affairs, the king was still described as a usurper among people.
- The new king considered to be a usurper was protested by mobs of ten thousand of people in the streets.
- If your married the princess, we would increase the possibilities of usurping the throne.
successor [səkˈsesər]: n. someone who takes a job or position previously held by someone else ⇨ predecessor继承者, 接任者
- The monastery was expected to fall into debt under your successor.
- If the monastery fell into debt under your successor, you would have to devote yourself to money for the rest of your life.
- Your successor had a great vision, for he built numerous canals to keep in touch with other states.
outlook [ˈaʊtˌlʊk]: n. your general attitude to life and the world世界观
- If his outlook had been shaped, you are incapable of persuading him to go to university.
- Since his outlook had been shaped, we were becoming more and more unfamiliar with him.
- Reading enormous history books may have shaped my outlook.
demographic [ˌdeməˈɡræfɪk]: adj. demographics [plural] information about a group such as the people who live in a particular area人口统计学的
- The demographic face of Europe has been changing dramatically when the number of immigrants increased.
- With the number of old people increasing, the demographic face of China was not energetic any more.
- The scientists made a remarkable discovery that our demographic face had not changed a great deal during the war.
ethnic [ˈeθnɪk] ethnically: n.adj. adv. relating to a particular race, nation, or tribe and their customs and traditions种族的
- The authorities offer a series of advantages to the ethnic to solve problems.
- In our country, ethnic is in harmony with majority.
- Ethnic considered to be barbarians receives a sophicated education nowadays.
diverse [daɪˈvɜrs]: adj. very different from each other不同的
- On the flame of his ambition, entrepreneurs were led to set up diverse factories in the suburbs of the city.
- In my youth, my grandmother often asked me to attend a party where diverse foods were offered. 
- Our cat seems to realize that the box is full of diverse snacks.
digital [ˈdɪdʒɪt(ə)l]: adj. using a system in which information is recorded or sent out electronically in the form of numbers, usually ones and zeros数字的
- I hope that my father will present a digital watch on my birthday.
- I don't think the digital watch need mending, it works punctually.
- You have lost a thousand of dollars worth of digital watch.
surge [sɜrdʒ]: v.n. to suddenly move very quickly in a particular direction汹涌, 澎湃,涌入
- Keeping up with the surge of day-trippers, the owner of amusement park lost no time in building more tools.
- keeping up with the surge of refugees, the authorities set up numerous soup lines.
- People in HongKong is always complaining about the surge of tourists from mainland.
vibrant [ˈvaɪbrənt]: adj. full of activity or energy in a way that is exciting and attractive SYN lively活跃的
- The vibrant electron is hard to capture.
- These vibrant nomads pushed their way westward and overran a village twelve miles outside the city of Paris.
- The vibrant Catholic churches continued into the next century.
pentagon [ˈpentəˌɡɑn]: n. a flat shape with five sides and five angles五角形
- Instead of catching fishes, I caught an object like a pentagon.
- He is drawing a pentagon as faintly as possible.
- Obviously, the view of the pentagon captured the heart of your wife.
acutely [əˈkjutli]: adv. feeling or noticing something very strongly剧烈地
- The drunk was acutely aware that he was in danger in the ring.
- The prime minister was acutely aware that the protest must have been settled as quickly as possible.
- The pope was acutely aware that a group of soldiers had overrun the church.
--------------------
be allied with sb./sth.: 与某人结盟
- Allied with my daugter, I agreed on whether my wife would have an operation.
- She claimed that all nations allied with the United States were persperous.
- France allied with Britain prevented these peasant from revolts.
be opposed to sb./sth.: 反对某事/某人
- Opposed to the Western Imperialism, the Soviet Union was allied with many nations in Asia.
- Opposed to his father, he gave up following his father's footsteps.
- Opposed to my wife, I sneaked out of the room to play video games with my friends.
remain subject to sb./sth.: 继续服从于...
- Remaining subject to the Soviet Union makes our people suffer from starvation.
- Remaining subject to the Soviet Union makes our regime more stable.
- The authoritarian regime remained subject to the Soviet Union.
bring an end to sth.: 终结某事
- It is time to bring an end to the revolts from those peasants.
- A carnage has brought a radical end to the civil war from the division of religion.
- The death of the king brought an end to the authoritarian regime.
be traced to sth.: 追溯到某事物
- The company which employs three thousand people can be traced to a small workshop.
- The breakdown in the trust of the monarchs can be traced to a revolt from the division of religions.
- Your illness can be traced to a solitary mold in the back of fridge.
seize control of sth.: 控制某事物
- Seizing control of Eastern Europe, the Soviet Union began to collective private farms.
- Seizing control of the empire, the queen drew up a series of laws seeking for revenues.
- Seizing control of the gangster, the police began to collect evidences on the scene.
pour into sp.: 涌入某地
- Pouring into the arcade, these refugees took away one thousand dollars worth of diamonds.
- These tourists poured into beach and littered.
- As streams poured into the field, the field was soon full of water.
enforce the wishes of sb.: 执行某人的意愿
- The knights were reluctant to enforce the wishes of our king.
- The crusade claimed to enforce the wishes of god.
- Enforcing the wishes of king, the knights killed those innocent peasants.
defect to sb's side: 投靠某一边
- Defecting to our enemies' side, you will be punished by the king.
- Defecting to our enemies' side, you will be incapable of returning to your home.
- Defecting to our enemies' side, all members of your family will be beheaded in the square.
turn one's back on sb./sth.: 背弃某人/某事物
- Turning its back on the Soviet Union, the state formed a friendly relation with the United States.
- Turning its back on the Soviet Union, China tended to be allied with the United States.
- Turning his back on his classmates, he lodged a complaint about their cheats.
come to an end: 结束
- When the war came to an end, everyone in the streets embraced everyelse and someone sobbed aloud.
- The time of our king came to an end.
- The authoritarian regime came to an end.
adjust to sth./sb.: 适应某事物/某人
- Adjusting to a difficult leader, I must be on time for work.
- Adjusting to my wife's schedule, I must take a bath before 22 o'clock.
- My cat grew up her fur to adjust to the cold winter.
most important of all, ...: 最重要的, ...
- Most important of all, you lost your heart when you failed the exam.
- Most important of all, my cat survived the fire.
- Most important of all, you are not in debt.
** sentence2
Westerner [ˈwestərnər]: n. someone from the western part of the world西方人
- The bridge was said to be named after a Westerner in ancient times.
- Our government must take these Westerners into account for our safety.
- These Westerners used to be described as barbarians who behaved rudely.
permanent [ˈpɜrmənənt]: adj. continuing to exist for a long time or for all the time in the future OPP temporary永久的, 持久的
- The division between you and Dad seems to remain permanent.
- THe noble ganster's name may remain permanent, for when he died,  people gave him a state funeral.
- He never dreams of being offered a permanent job at his university.
symbolize [ˈsɪmbəˌlaɪz]: v. if something symbolizes a quality, feeling etc, it represents it象征, 用符号表现
- The withering flower may symbolize your dying wife.
- The dog that symbolized our friendship was killed in an action.
- Needless to say, the statue that the French people presented to America symbolized their friendship.
spontaneously [spɔnˈtenɪəslɪ] spontaneous: adv.adj. something that is spontaneous has not been planned or organized, but happens by itself, or because you suddenly feel you want to do it自发的, 自然产生的
- Spontaneously, I double-checked the program he made yesterday.
- Spontaneously, I drew the enormous object as faintly as possible.
- Spontaneously, my cat fell fast asleep on my legs.
protest [prəˈtest]: v.n. something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products抗议
- These protests in the streets proved effective, for the authoritarian regime soon gave up its policy about the pestilence.
- If the protest were unsettled, there would be a civil war in our country.
- These immigrants protested for unfair treatment in the force market.
coup [ku]: n. a sudden and sometimes violent attempt by citizens or the army to take control of the government SYN coup d'état政变
- A fraction of the party was due to initiate a coup on National Day.
- The coup made the prince assume political and military power in the Holy Roman Empire.
- Fearing a coup, the king ordered his men to kill the peasants in the palace.
usurp [juˈzɜrp]: v. formal to take someone else’s power, position, job etc when you do not have the right to篡夺, 篡位
- In spite of great achievements in domestic affairs, the king was still described as a usurper among people.
- The new king considered to be a usurper was protested by mobs of ten thousand of people in the streets.
- If you married the princess, we would increase the possibilities of usurping the throne.
successor [səkˈsesər]: n. someone who takes a job or position previously held by someone else ⇨ predecessor继承者, 接任者
- The monastery was expected to fall into debt under your successor.
- If the monastery fell into debt under your successor, you would have to devote yourself to money for the rest of your life.
- Your successor had a great vision, for he built numerous canals to keep in touch with other states.
outlook [ˈaʊtˌlʊk]: n. your general attitude to life and the world世界观
- If his outlook had been shaped, you are incapable of persuading him to go to university.
- Since his outlook had been shaped, we were becoming more and more unfamiliar with him.
- Reading enormous history books may have shaped my outlook.
demographic [ˌdeməˈɡræfɪk]: adj. demographics [plural] information about a group such as the people who live in a particular area人口统计学的
- The demographic face of Europe has been changing dramatically when the number of immigrants increased.
- With the number of old people increasing, the demographic face of China was not energetic anymore.
- The scientists made a remarkable discovery that our demographic face had not changed a great deal during the war.
ethnic [ˈeθnɪk] ethnically: n.adj. adv. relating to a particular race, nation, or tribe and their customs and traditions种族的
- The authorities offer a series of advantages to the ethnic to solve problems.
- In our country, ethnicity is in harmony with the majority.
- Ethnic considered to be barbarians receive a sophisticated education nowadays.
diverse [daɪˈvɜrs]: adj. very different from each other不同的
- On the flame of his ambition, entrepreneurs were led to set up diverse factories in the suburbs of the city.
- In my youth, my grandmother often asked me to attend a party where diverse foods were offered. 
- Our cat seems to realize that the box is full of diverse snacks.
digital [ˈdɪdʒɪt(ə)l]: adj. using a system in which information is recorded or sent out electronically in the form of numbers, usually ones and zeros数字的
- I hope that my father will present a digital watch on my birthday.
- I don't think the digital watch needs mending, it works punctually.
- You have lost thousands of dollars worth of digital watches.
surge [sɜrdʒ]: v.n. to suddenly move very quickly in a particular direction汹涌, 澎湃,涌入
- Keeping up with the surge of day-trippers, the owner of the amusement park lost no time in building more tools.
- keeping up with the surge of refugees, the authorities set up numerous soup lines.
- People in Hong Kong are always complaining about the surge of tourists from the mainland.
vibrant [ˈvaɪbrənt]: adj. full of activity or energy in a way that is exciting and attractive SYN lively活跃的
- The vibrant electron is hard to capture.
- These vibrant nomads pushed their way westward and overran a village twelve miles outside the city of Paris.
- The vibrant Catholic churches continued into the next century.
pentagon [ˈpentəˌɡɑn]: n. a flat shape with five sides and five angles五角形
- Instead of catching fish, I caught an object like a pentagon.
- He is drawing a pentagon as faintly as possible.
- Obviously, the view of the Pentagon captured the heart of your wife.
acutely [əˈkjutli]: adv. feeling or noticing something very strongly剧烈地
- The drunk was acutely aware that he was in danger in the ring.
- The prime minister was acutely aware that the protest must have been settled as quickly as possible.
- The pope was acutely aware that a group of soldiers had overrun the church.
--------------------
be allied with sb./sth.: 与某人结盟
- Allied with my daughter, I agreed on whether my wife would have an operation.
- She claimed that all nations allied with the United States were prosperous.
- France was allied with Britain to prevent these peasant from revolts.
be opposed to sb./sth.: 反对某事/某人
- Opposed to Western Imperialism, the Soviet Union was allied with many nations in Asia.
- Opposed to his father, he gave up following his father's footsteps.
- Opposed to my wife, I sneaked out of the room to play video games with my friends.
remain subject to sb./sth.: 继续服从于...
- Remaining subject to the Soviet Union makes our people suffer from starvation.
- Remaining subject to the Soviet Union makes our regime more stable.
- The authoritarian regime remained subject to the Soviet Union.
bring an end to sth.: 终结某事
- It is time to bring an end to the revolts from those peasants.
- A carnage has brought a radical end to the civil war from the division of religion.
- The death of the king brought an end to the authoritarian regime.
be traced to sth.: 追溯到某事物
- The company which employs three thousand people can be traced to a small workshop.
- The breakdown in the trust of the monarchs can be traced to a revolt from the division of religions.
- Your illness can be traced to a solitary mold in the back of a fridge.
seize control of sth.: 控制某事物
- Seizing control of Eastern Europe, the Soviet Union began to collect private farms.
- Seizing control of the empire, the queen drew up a series of laws seeking revenues.
- Seizing control of the gangster, the police began to collect evidence on the scene.
pour into sp.: 涌入某地
- Pouring into the arcade, these refugees took away one thousand dollars worth of diamonds.
- These tourists poured into the beach and littered.
- As streams poured into the field, the field was soon full of water.
enforce the wishes of sb.: 执行某人的意愿
- The knights were reluctant to enforce the wishes of our king.
- The crusade claimed to enforce the wishes of god.
- Enforcing the wishes of the king, the knights killed those innocent peasants.
defect to sb's side: 投靠某一边
- Defecting to our enemies' side, you will be punished by the king.
- Defecting to our enemies' side, you will be incapable of returning to your home.
- Defecting to our enemies' side, all members of your family will be beheaded in the square.
turn one's back on sb./sth.: 背弃某人/某事物
- Turning its back on the Soviet Union, the state formed a friendly relationship with the United States.
- Turning its back on the Soviet Union, China tended to be allied with the United States.
- Turning his back on his classmates, he lodged a complaint about their cheats.
come to an end: 结束
- When the war came to an end, everyone in the streets embraced everyone else and someone sobbed aloud.
- The time of our king came to an end.
- The authoritarian regime came to an end.
adjust to sth./sb.: 适应某事物/某人
- Adjusting to a difficult leader, I must be on time for work.
- Adjusting to my wife's schedule, I must take a bath before 22 o'clock.
- My cat grew up her fur to adjust to the cold winter.
most important of all, ...: 最重要的, ...
- Most important of all, you lost your heart when you failed the exam.
- Most important of all, my cat survived the fire.
- Most important of all, you are not in debt.
