* 14 Europe and the world, new encounters, 1500--1800

At the end of the fifteenth century, Europeans sailed out into the world in all directions.
Beginning with the handful of Portuguese ships
		that ventured southward along the West African coast in the mid-fifteenth century,
	the process accelerated
		with the epochal voyages of Christopher Columbus to the Americas
			and Vasco da Gama to the Indian Ocean in the 1490s.
Soon a number of other European states had joined in the adventure,
	and by the end of the eighteenth century,
		they had created a global trade network dominated by Western ships and Western power.
In less than three hundred years, the European Age of Exploration changed the shape of the world.
In some areas, such as the Americas and the Spice Islands,
	it led to the destruction of indigenous civilizations and the establishment of European colonies.
In others, as in Africa, India, and mainland Southeast Asia,
	it left native regimes intact
		but had a strong impact on local societies and regional trade patterns.
At the time, many European observers viewed the process in a favorable light.
It not only expanded wealth through world trade and exchanged crops
		and discoveries between the Old World and the New,
	they believed, but it also introduced 'heathen peoples' to the message of Jesus Christ.
The conquest of the Americas and expansion into the rest of the world
	brought out most of the worst and some of the best aspects of European civilization.
The greedy plundering of resources and the brutal repression and enslavement
	were hardly balanced by attempts to create new institutions,
		convert the natives to Christianity, and foster the rights of the indigenous peoples.
In any case,
	Europeans had begun to change the face of the world and increasingly saw their culture,
		with its religion, languages, and technology,
	as a coherent force to be exported to all corners of the earth.
** expression
