* 18 Enlightened Absolutism Revisited

Of the three major rulers most closely associated traditionally with enlightened absolutism
	---Joseph II, Frederick II, and Catherine the Great---
	only Joseph sought truly radical changes based on Enlightenment ideas.
Both Frederick and Catherine liked to be cast as disciples of the Enlightenment,
	expressed interest in enlightened reforms, and even attempted some.
But the policies of neither seemed seriously affected by Enlightenment thought.
Necessities of state and maintenance of the existing system took precedence over reform.
Indeed, many historians maintain
	that Joseph, Frederick, and Catherine were all guided primarily
			by a concern for the power and wellbeing of their states
		and that their policies were not all that different from those of their predecessors.
In the final analysis, state power was used to build armies and wage wars to gain even more power.
Nevertheless, in their desire to forge stronger state systems,
	these rulers did pursue such enlightened ideas as legal reform,
		religious toleration, and the extension of education,
	since these served to create more satisfied subjects
		and strengthened the state in significant ways.

It would be foolish, however, to overlook the fact
	that not only military but also political and social realities
		limited the ability of enlightened rulers to make reforms.
Everywhere in Europe, the hereditary aristocracy was still the most powerful class in society.
Enlightened reforms were often limited to changes in the administrative and judicial systems
	that did not seriously undermine the powerful interests of the European nobility.
Although aristocrats might join the populace
		in opposing monarchical extension of centralizing power,
	as the chief beneficiaries of a system based on traditional rights and privileges for their class,
	they were certainly not willing to support a political ideology
		that trumpeted the principle of equal rights for all.
