* 27 Adolf Hitler salutes military leaders and soldiers during a military rally

On February 3, 1933, only four days after he had been
appointed chancellor of Germany, Adolf Hitler met secretly with
Germany’s leading generals. He revealed to them his desire to remove the ‘‘cancer of democracy,’’ create a new authoritarian leadership, and forge a new domestic unity. All Germans would need to
realize that ‘‘only a struggle can save us and that everything else
must be subordinated to this idea.’’ Youth especially must be trained
and their will strengthened ‘‘to fight with all means.’’ Because
Germany’s living space was too small for its people, above all, Hitler
said, Germany must rearm and prepare for ‘‘the conquest of new
living space in the east and its ruthless Germanization.’’ Even before
he had consolidated his power, Adolf Hitler had a clear vision of his
goals, and their implementation meant another European war.
World War II was clearly Hitler’s war. Although other countries may
have helped make the war possible by not resisting Hitler’s Germany
earlier, Nazi Germany’s actions made World War II inevitable.

This chapter focuses on the European theater of war, but both
European and American armies were involved in fighting around
the world. World War II was actually two major conflicts, one provoked by the ambitions of Germany in Europe and the other by the
ambitions of Japan in Asia. By 1941, with the United States drawn
into both, the two had merged into a single global conflict.
Although World War I has been described as a total war, World
War II was even more so and was fought on a scale unheard of in
history. Almost everyone in the warring countries was involved in
one way or another: as soldiers; as workers in wartime industries; as
ordinary citizens subject to invading armies, military occupation, or
bombing raids; as refugees; or as victims of mass extermination.
The world had never witnessed such widespread intentional death
and destruction
