#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
'

CHAPTER OUTLINE
AND FOCUS QUESTIONS
The First Humans
Q How did the Paleolithic and Neolithic Ages differ, and how did the Neolithic Revolution affect the lives of men and women?

The Emergence of Civilization
Q What are the characteristics of civilization, and what are some explanations for why early civilizations emerged?

Civilization in Mesopotamia
Q How are the chief characteristics of civilization evident in ancient Mesopotamia?

Egyptian Civilization: 'The Gift of the Nile'
Q What are the basic features of the three major periods of Egyptian history? What elements of continuity are there in the three periods? What are their major differences?

CRITICAL THINKING
Q In what ways were the civilizations of Mesopotamia and Egypt alike? In what ways were they different?

IN 1849, A DARING YOUNG Englishman made a hazardous journey into the deserts and swamps of southern Iraq. Moving south down the banks of the Euphrates River while braving high winds and temperatures that reached 120 degrees Fahrenheit, William Loftus led a small expedition in search of the roots of civilization. As he said, 'From our childhood we have been led to regard this place as the cradle of the human race.'

Guided by native Arabs into the southernmost reaches of Iraq, Loftus and his small group of explorers were soon overwhelmed by what they saw. He wrote, 'I know of nothing more exciting or impressive than the first sight of one of these great piles, looming in solitary grandeur from the surrounding plains and marshes.' One of these piles, known to the natives as the mound of Warka, contained the ruins of Uruk, one of the first cities in the world and part of the world's first civilization.

Southwest Asia was one area in the world where civilization began. Although Western civilization did not yet exist, its origins can be traced back to the ancient Near East, where people in Southwest Asia and in Egypt, in northeastern Africa, developed organized societies, invented writing, and created the ideas and institutions that we associate with civilization. The later Greeks and Romans, who played such a crucial role in the development of Western civilization, were nourished and influenced by these older Near Eastern societies. It is appropriate, therefore, to begin our story of Western civilization with the early civilizations of Southwest Asia and Egypt. Before considering them, however, we must briefly examine prehistory and observe how human beings made the shift from hunting and gathering to agricultural communities and ultimately to cities and civilization.


The First Humans

Q Focus Question: How did the Paleolithic and Neolithic Ages differ, and how did the Neolithic Revolution affect the lives of men and women?

Historians rely primarily on documents to create their pictures of the past, but no written records exist for the prehistory of humankind. In their absence, the story of early humanity depends on archaeological and, more recently, biological information, which anthropologists and archaeologists use to formulate theories about our early past.


The earliest humanlike creatures---known as hominids--- existed in Africa as long as three to four million years ago. Known as Australopithecines, they flourished in East and South Africa and were the first hominids to make simple stone tools.


A second stage in early human development occurred around 1.5 million years ago when Homo erectus ('upright human being') emerged. Homo erectus made use of larger and more varied tools and was the first hominid to leave Africa and to move into both Europe and Asia.


Around 250,000 years ago, a third and crucial stage in human development began with the emergence of Homo sapiens ('wise human being'). By 100,000 B.C., two groups of Homo sapiens had developed. One type was the Neanderthal, whose remains were first found in the Neander valley in Germany. Neanderthal remains have since been found in both Europe and the Middle East and have been dated to between 100,000 and 30,000 B.C. Neanderthals relied on a variety of stone tools and were the first early people to bury their dead.


The first anatomically modern humans, known as Homo sapiens sapiens ('wise, wise human being'), appeared in Africa between 200,000 and 150,000 years ago. Recent evidence indicates that they began to spread outside Africa around 70,000 years ago. Map 1.1 shows probable dates for different movements, although many of these are still unconfirmed. By 30,000 B.C., Homo sapiens sapiens had replaced the Neanderthals, who had largely become extinct, and by 10,000 B.C., members of the Homo sapiens sapiens species could be found throughout the world. By that time, it was the only human species left. All humans today, be they Europeans, Australian Aborigines, or Africans, belong to the same subspecies.


The Hunter-Gatherers of the Old Stone Age


One of the basic distinguishing features of the human species is the ability to make tools. The earliest tools were made of stone, and the term Paleolithic (Greek for 'old stone') Age is used to designate this early period of human history (c. 2,500,000--10,000 B.C.).


For hundreds of thousands of years, humans relied on hunting and gathering for their daily food. Paleolithic peoples had a close relationship with the world around them, and over a period of time, they came to know which animals to hunt and which plants to eat. They did not know how to grow crops or raise animals, however. They gathered wild nuts, berries, fruits, and a variety of wild grains and green plants. Around the world, they hunted and consumed different animals, including buffalo, horses, bison, wild goats, and reindeer. In coastal areas, fish were a rich source of nourishment.


The hunting of animals and the gathering of wild plants no doubt led to certain patterns of living. Archaeologists and anthropologists have speculated that Paleolithic people lived in small bands of twenty to thirty. They were nomadic, moving from place to place to follow animal migrations and vegetation cycles. Hunting depended on careful observation of animal behavior patterns and required a group effort for success. Over the years, tools became more refined and more useful. The invention of the spear, and later the bow and arrow, made hunting considerably easier. Harpoons and fishhooks made of bone increased the catch of fish.


Both men and women were responsible for finding food---the chief work of Paleolithic people. Since women bore and raised the children, they generally stayed close to the camps, but they played an important role in acquiring food by gathering berries, nuts, and grains. Men hunted wild animals, an activity that often took them far from camp. Because both men and women played important roles in providing for the band's survival, scientists believe that a rough equality existed between men and women. Indeed, some speculate that both men and women made the decisions that affected the activities of the Paleolithic band.


Some groups of Paleolithic peoples, especially those who lived in cold climates, found shelter in caves. Over time, they created new types of shelter as well. Perhaps the most common was a simple structure of wood poles or sticks covered with animal hides. The systematic use of fire, which archaeologists believe began around 500,000 years ago, made it possible for the caves and humanmade structures to have a source of light and heat. Fire also enabled early humans to cook their food, making it taste better, last longer, and in the case of some plants, such as wild grain, easier to chew and digest.


The making of tools and the use of fire---two important technological innovations of Paleolithic peoples--- remind us how crucial the ability to adapt was to human survival. But Paleolithic peoples did more than just survive. The cave paintings of large animals found in southwestern France and northern Spain bear witness to the cultural activity of Paleolithic peoples. A cave discovered in southern France in 1994 (known as the Chauvet Cave, after the leader of the expedition that found it) contains more than three hundred paintings of lions, oxen, owls, bears, and other animals. Most of these are animals that Paleolithic people did not hunt, which suggests to some scholars that the paintings were made for religious or even decorative purposes. The discoverers were overwhelmed by what they saw: 'There was a moment of ecstasy. . . . They overflowed with joy and emotion. . . . These were moments of indescribable madness.'1


The Neolithic Revolution (C. 10,000--4000 B.C.)


The end of the last ice age around 10,000 B.C. was followed by what is called the Neolithic Revolution, a significant change in living patterns that occurred in the New Stone Age (Neolithic is Greek for 'new stone'). The name New Stone Age is misleading, however. Although Neolithic peoples made a new type of polished stone ax, this was not the major change that occurred after 10,000 B.C.


An Agricultural Revolution

The biggest change was the shift from hunting animals and gathering plants for sustenance (food gathering) to producing food by systematic agriculture (food production). The planting of grains and vegetables provided a regular supply of food, while the domestication of animals, such as sheep, goats, cattle, and pigs, added a steady source of meat, milk, and fibers such as wool for clothing. Larger animals could also be used as beasts of burden. The growing of crops and the taming of food-producing animals created a new relationship between humans and nature. Historians speak of this as an agricultural revolution. Revolutionary change is dramatic and requires great effort, but the ability to acquire food on a regular basis gave humans greater control over their environment. It also allowed them to give up their nomadic ways of life and begin to live in settled communities.


Systematic agriculture probably developed independently between 8000 and 7000 B.C. in various parts of the world. Different plants were cultivated in each: wheat, barley, and lentils in the Near East; rice and millet in southern Asia; millet and yams in western Africa; and beans, potatoes, and corn in the Americas. The Neolithic agricultural revolution needed a favorable environment. In the Near East, the upland areas above the Fertile Crescent (present-day northern Iraq and southern Turkey) were more conducive to systematic farming than the river valleys. This region received the necessary rainfall and was the home of two wild plant species (barley and wheat) and four wild animal species (pigs, cows, goats, and sheep) that humans eventually domesticated.


Consequences of the Neolithic Revolution

The growing of crops on a regular basis gave rise to more permanent settlements, which historians refer to as Neolithic farming villages or towns. One of the oldest and most extensive agricultural villages was C¸atal Hu¨yu¨k, located in modern-day Turkey. Its walls enclosed 32 acres, and its population probably reached six thousand inhabitants during its high point from 6700 to 5700 B.C. People lived in simple mudbrick houses that were built so close to one another that there were few streets. To get to their homes, people had to walk along the rooftops and then enter the house through a hole in the roof.


Archaeologists have discovered twelve cultivated products in C¸atal Hu¨yu¨k, including fruits, nuts, and three kinds of wheat. Artisans made weapons and jewelry that were traded with neighboring people. Religious shrines housing figures of gods and goddesses have been found at C¸ atal Hu¨yu¨k, as have a number of female statuettes. Molded with noticeably large breasts and buttocks, these 'earth mothers' perhaps symbolically represented the fertility of both 'mother earth' and human mothers. The shrines and the statues point to the role of religion in the lives of these Neolithic peoples.


The Neolithic Revolution had far-reaching consequences. Once people settled in villages or towns, they built permanent houses for protection and other structures for the storage of goods. As organized communities stockpiled food and accumulated material goods, they began to engage in trade. People also began to specialize in certain crafts, and a division of labor developed. Pottery was made from clay and baked in a fire to make it hard. The pots were used for cooking and to store grains. Woven baskets were also used for storage. Stone tools became refined as flint blades were employed to make sickles and hoes for use in the fields. Obsidian---a volcanic glass that was easily flaked---was also used to create very sharp tools. In the course of the Neolithic Age, many of the food plants still in use today began to be cultivated. Moreover, fibers from plants such as flax were used to make thread that was woven into cloth.


The change to systematic agriculture in the Neolithic


Age also had consequences for the relationship between men and women. Men assumed the primary responsibility for working in the fields and herding animals, jobs that kept them away from the home. Although women also worked in the fields, many remained behind to care for the children, weave clothes, and perform other tasks that required labor close to home. In time, as work outside the home was increasingly perceived as more important than work done at home, men came to play the more dominant role in society, a basic pattern that would persist until our own times.


Other patterns set in the Neolithic Age also proved to be enduring elements of human history. Fixed dwellings, domesticated animals, regular farming, a division of labor, men holding power---all of these are part of the human story. Despite all our modern scientific and technological progress, human survival still depends on the growing and storing of food, an accomplishment of people in the Neolithic Age. The Neolithic Revolution was truly a turning point in human history.


New Developments

Between 4000 and 3000 B.C., significant technical developments began to transform the Neolithic towns. The invention of writing enabled records to be kept, and the use of metals marked a new level of human control over the environment and its resources. Already before 4000 B.C., craftspeople had discovered that certain rocks could be heated to liquefy metals embedded in them. The metals could then be cast in molds to produce tools and weapons that were more refined than stone instruments. Although copper was the first metal to be made into tools, after 4000 B.C., craftspeople in western Asia discovered that combining copper and tin created bronze, a much harder and more durable metal than copper. Its widespread use has led historians to call the period from around 3000 to 1200 B.C. the Bronze Age; thereafter, bronze was increasingly replaced by iron.


At first, Neolithic settlements were mere villages. But as their inhabitants mastered the art of farming, more complex human societies began to emerge. As wealth increased, these societies began to develop armies and to build walled towns and cities. By the beginning of the Bronze Age, the concentration of larger numbers of people in the river valleys of Southwest Asia and Egypt was leading to a whole new pattern for human life.


The Emergence of Civilization


Q Focus Question: What are the characteristics of civilization, and what are some explanations for why early civilizations emerged? 


As we have seen, early human beings formed small groups that developed a simple culture that enabled them to survive. As human societies grew and developed greater complexity, a new form of human existence---called civilization---came into being. A civilization is a complex culture in which large numbers of human beings share a number of common elements. Historians have identified a number of basic characteristics of civilization. These include (1) an urban focus: cities became the centers of political, economic, social, cultural, and religious development; (2) a distinct religious structure: the gods were deemed crucial to the community's success, and professional priestly classes regulated relations with the gods; (3) new political and military structures: an organized government bureaucracy arose to meet the administrative demands of the growing population, and armies were organized to gain land and power and for defense; (4) a new social structure based on economic power: while kings and an upper class of priests, political leaders, and warriors dominated, there also existed a large group of free men (farmers, artisans, craftspeople) and at the very bottom, socially, a class of slaves; (5) the development of writing: kings, priests, merchants, and artisans used writing to keep records; and (6) new forms of significant artistic and intellectual activity: for example, monumental architectural structures, usually religious, occupied a prominent place in urban environments.


The civilizations that developed in Southwest Asia and Egypt, the forerunners of Western civilization, will be examined in detail in this chapter. But civilization also developed independently in other parts of the world. Between 3000 and 1500 B.C., the valleys of the Indus River in India supported a flourishing civilization that extended hundreds of miles from the Himalayas to the coast of the Arabian Sea. Two major cities, Harappa and Mohenjo-Daro, were at the heart of this South Asian civilization. Many written records of the Indus valley civilization exist, but their language has not yet been deciphered. This Indus valley civilization carried on extensive trade with cities in Southwest Asia. 


Another river valley civilization emerged along the Yellow River in northern China about 4,000 years ago. Under the Shang dynasty of kings, which ruled from 1750 to 1122 B.C., this civilization contained impressive cities with huge city walls, royal palaces, and large royal tombs. A system of irrigation enabled this early Chinese civilization to maintain a prosperous farming society ruled by an aristocratic class whose major concern was war.


Scholars have believed for a long time that civilization emerged only in four areas, in the fertile river valleys of the Tigris and Euphrates, the Nile, the Indus, and the Yellow River---that is, in Southwest Asia, Egypt, India, and China. Recently, however, archaeologists have discovered two other early civilizations. One of these flourished in Central Asia (in what are now the republics of Turkmenistan and Uzbekistan) around 4,000 years ago. People in this civilization built mudbrick buildings, raised sheep and goats, had bronze tools, used a system of irrigation to grow wheat and barley, and had a writing system.


Another early civilization was discovered in the Supe River valley of Peru. At the center of this civilization was the city of Caral, which flourished around 2600 B.C. It contained buildings for officials, apartment buildings, and grand residences, all built of stone. The inhabitants of Caral also developed a system of irrigation by diverting a river more than a mile upstream into their fields.


Why early civilizations developed remains difficult to explain. One theory maintains that challenges forced human beings to make efforts that resulted in the rise of civilization. Some scholars have argued that material forces, such as the growth of food surpluses, made possible the specialization of labor and development of large communities with bureaucratic organization. But the area of the Fertile Crescent (see Map 1.2), in which Mesopotamian civilization emerged, was not naturally conducive to agriculture. Abundant food could be produced only with a massive human effort to manage the water, an undertaking that required organization and led to civilized societies. Other historians have argued that nonmaterial forces, primarily religious, provided the sense of unity and purpose that made such organized living possible. And some scholars doubt that we will ever discover the actual causes of early civilization.


Civilization in Mesopotamia


Q Focus Question: How are the chief characteristics of civilization evident in ancient Mesopotamia?


The Greeks spoke of the valley between the Tigris and Euphrates Rivers as Mesopotamia, the 'land between the rivers.' The region receives little rain, but the soil of the plain of southern Mesopotamia was enlarged and enriched over the years by layers of silt deposited by the rivers. In late spring, the Tigris and Euphrates overflow their banks and deposit their fertile silt, but since this flooding depends on the melting of snows in the upland mountains where the rivers begin, it is irregular and sometimes catastrophic. In such circumstances, farming could be accomplished only with human intervention in the form of irrigation and drainage ditches. A complex system was required to control the flow of the rivers and produce the crops. Large-scale irrigation made possible the expansion of agriculture in this region, and the abundant food provided the material base for the emergence of civilization in Mesopotamia.


The City-States of Ancient Mesopotamia


The creators of Mesopotamian civilization were the Sumerians, a people whose origins remain unclear. By 3000 B.C., they had established a number of independent cities in southern Mesopotamia, including Eridu, Ur, Uruk, Umma, and Lagash. There is evidence that the Sumerians were not the first people in the region. A number of Sumerian agricultural and craft terms are not Sumerian in origin, indicating that the Sumerians adopted some aspects of preexisting settlements. As the Sumerian cities grew larger, they came to exercise political and economic control over the surrounding countryside, forming city-states. These city-states were the basic units of Sumerian civilization.


Sumerian Cities


Sumerian cities were surrounded by walls. Uruk, for example, occupied an area of approximately 1,000 acres encircled by a wall 6 miles long with defense towers located every 30 to 35 feet along the wall. City dwellings, built of sun-dried bricks, included both the small flats of peasants and the larger dwellings of the civic and priestly officials. Although Mesopotamia had little stone or wood for building purposes, it did have plenty of mud. Mudbricks, easily shaped by hand, were left to bake in the hot sun until they were hard enough to use for building. People in Mesopotamia were remarkably inventive with mudbricks, constructing some of the largest brick buildings in the world.


The most prominent building in a Sumerian city was the temple, which was dedicated to the chief god or goddess of the city and often built atop a massive stepped tower called a ziggurat. The Sumerians believed that gods and goddesses owned the cities, and much wealth was used to build temples as well as elaborate houses for the priests and priestesses who served the gods. Priests and priestesses, who supervised the temples and their property, had great power. The temples owned much of the city land and livestock and served not only as the physical center of the city but also its economic and political center. In fact, historians believe that in the early stages of a few citystates, priests and priestesses may have played an important role in ruling. The Sumerians believed that the gods ruled the cities, making the state a theocracy (government by a divine authority). However, ruling power was primarily in the hands of worldly figures known as kings. 


Kingship


Sumerians viewed kingship as divine in origin; they believed kings derived their power from the gods and were the agents of the gods. As one person said in a petition to his king, 'You in your judgment, you are the son of Anu [god of the sky]; your commands, like the word of a god, cannot be reversed; your words, like rain pouring down from heaven, are without number.'2 Regardless of their origins, kings had power---they led armies, initiated legislation, supervised the building of public works, provided courts, and organized workers for the irrigation projects on which Mesopotamian agriculture depended. The army, the government bureaucracy, and the priests and priestesses all aided the kings in their rule. 


Economy and Society


The economy of the Sumerian city-states was primarily agricultural, but commerce and industry became important as well. The people of Mesopotamia produced woolen textiles, pottery, and metalwork. Foreign trade, which was primarily a royal monopoly, could be extensive. Royal officials imported luxury items, such as copper and tin, aromatic woods, and fruit trees, in exchange for dried fish, wool, barley, wheat, and goods produced by Mesopotamian metalworkers. Traders traveled by land to the Mediterranean in the west and by sea to India in the east. The invention of the wheel around 3000 B.C. led to carts with wheels that made the transport of goods easier.


Sumerian city-states probably contained four major social groups: elites, dependent commoners, free commoners, and slaves. Elites included royal and priestly officials and their families. Dependent commoners included the elites' clients, who worked for the palace and temple estates. Free commoners worked as farmers, merchants, fishers, scribes, and craftspeople. Probably 90 percent or more of the population were farmers. They could exchange their crops for the goods of the artisans in town markets. Slaves belonged to palace officials, who used them mostly in building projects; temple officials, who used mostly female slaves to weave cloth and grind grain; and rich landowners, who used them for farming and domestic work.


Empires in Ancient Mesopotamia


As the number of Sumerian city-states grew and the states expanded, conflicts arose as city-state fought city-state for control of land and water. The fortunes of various citystates rose and fell over the centuries. The constant wars, with their burning and sacking of cities, left many Sumerians in deep despair, as is evident in the words of this Sumerian poem from the city of Ur: 'Ur is destroyed, bitter is its lament. The country's blood now fills its holes like hot bronze in a mold. Bodies dissolve like fat in the sun. Our temple is destroyed; the gods have abandoned us, like migrating birds. Smoke lies on our city like a shroud.'


Located on the flat land of Mesopotamia, the Sumerian city-states were also open to invasion. To the north of the Sumerian city-states lived the Akkadians. We call them a Semitic people because of the language they spoke (see Table 1.1). Around 2340 B.C., Sargon, leader of the Akkadians, overran the Sumerian city-states and established an empire that included most of Mesopotamia as well as lands westward to the Mediterranean. But the Akkadian empire eventually disintegrated, and its end by 2100 B.C. brought a return to the system of warring citystates until Ur-Nammu of Ur succeeded in reunifying most of Mesopotamia. But this final flowering of Sumerian culture collapsed with the coming of the Amorites. Under Hammurabi, the Amorites, or Old Babylonians, a large group of Semitic-speaking seminomads, created a new empire.


Hammurabi (1792--1750 B.C.) employed a welldisciplined army of foot soldiers who carried axes, spears, and copper or bronze daggers. He learned to divide his opponents and subdue them one by one. Using such methods, he gained control of Sumer and Akkad and reunified Mesopotamia almost to the old borders created by Sargon of Akkad. After his conquests, he called himself 'the sun of Babylon, the king who has made the four quarters of the world subservient,' and established a new capital at Babylon, north of Akkad. He also built temples, defensive walls, and irrigation canals; encouraged trade; and brought about an economic revival. Indeed, Hammurabi saw himself as a shepherd to his people: 'I am indeed the shepherd who brings peace, whose scepter is just. My benevolent shade was spread over my city. I held the people of the lands of Sumer and Akkad safely on my lap.'3 Hammurabi left his dynasty strong enough that it survived until the 1550s B.C., when the Kassites from the northeast took over.


The Code of Hammurabi


Hammurabi is best remembered for his law code, a collection of 282 laws. For centuries, laws had regulated people's relationships with one another in the lands of Mesopotamia, but only fragments of these earlier codes survive. Although many scholars today view Hammurabi's collection less as a code of laws and more as the attempt of Hammurabi to portray himself as the source of justice to the people, the code still gives us a glimpse of the Babylonian society of his time (see the box on p. 10).


The Code of Hammurabi reveals a society with a system of strict justice. Penalties for criminal offenses were severe and varied according to the social class of the victim. A crime against a member of the upper class (a noble) was punished more severely than the same offense against a member of the lower class. Moreover, the principle of 'an eye for an eye, a tooth for a tooth' was fundamental to this system of justice. This meant that punishments should fit the crime: 'If a freeman has destroyed the eye of a member of the aristocracy, they shall destroy his eye.' Hammurabi's code also had an impact on legal ideas in Southwest Asia for hundreds of years, as the following verse from the Hebrew Bible demonstrates: 'If anyone injures his neighbor, whatever he has done must be done to him: fracture for fracture, eye for eye, tooth for tooth. As he has injured the other, so he is to be injured' (Leviticus 24:19--20).


Hammurabi's code took the responsibilities of public officials very seriously. The governor of an area and city officials were expected to catch burglars. If they failed to do so, the officials in the district where the crime was committed had to replace the lost property. If murderers were not found, the officials had to pay a fine to the relatives of the murdered person.


The law code also furthered the proper performance of work with what amounted to consumer protection laws. Builders were held responsible for the buildings they constructed. If a house collapsed and caused the death of the owner, the builder was put to death. If the collapse caused the death of the son of the owner, the son of the builder was put to death. If goods were destroyed by the collapse, they had to be replaced and the house itself reconstructed at the builder's expense.  


The largest number of laws in the Code of Hammurabi focused on marriage and the family. Parents arranged marriages for their children. After marriage, the parties involved signed a marriage contract; without it, no one was considered legally married. The husband provided a bridal payment, and the woman's parents were responsible for a dowry to the new husband. 


As in many patriarchal societies, women had far fewer privileges and rights in marriage than men. A woman's place was in the home, and failure to fulfill her expected duties was grounds for divorce. If she was not able to bear children, her husband could divorce her, but he did have to return the dowry to her family. If his wife tried to leave home to engage in business, thus neglecting her house, her husband could divorce her and did not have to repay the dowry. Furthermore, a wife who was a 'gadabout, . . . neglecting her house [and] humiliating her husband,' could be drowned. We do know that in practice not all women remained at home. Some worked in the fields and others in business, where they were especially prominent in the running of taverns.


Women were guaranteed some rights, however. If a woman was divorced without good reason, she received the dowry back. A woman could seek divorce and get her dowry back if her husband was unable to show that she had done anything wrong. In theory, a wife was guaranteed use of her husband's property in the event of his death. The mother could also decide which of her sons would receive an inheritance.


Sexual relations were strictly regulated as well. Husbands, but not wives, were permitted sexual activity outside marriage. A wife and her lover caught committing adultery were pitched into the river, although if the husband pardoned his wife, the king could pardon the guilty man. Incest was strictly forbidden. If a father had incestuous relations with his daughter, he would be banished. Incest between a son and mother resulted in both being burned.


Fathers ruled their children as well as their wives. Obedience was duly expected: 'If a son has struck his father, they shall cut off his hand.' If a son committed a serious enough offense, his father could disinherit him, although fathers were not permitted to disinherit their sons arbitrarily.


The Culture of Mesopotamia


A spiritual worldview was of fundamental importance to Mesopotamian culture. To the peoples of Mesopotamia, the gods were living realities who affected all aspects of life. It was crucial, therefore, that the correct hierarchies be observed. Leaders could prepare armies for war, but success depended on a favorable relationship with the gods. This helps explain the importance of the priestly class and is the reason why even the kings took great care to dedicate offerings and monuments to the gods.


The Importance of Religion


One of the most famous accounts from the ancient Near East of the creation of the universe was the Babylonian creation epic known as the Enuma Elish. The name comes from the first three words of the first two lines of the poem:


When on high the heavens were not yet named, And below, the earth was not called by a name.


The Enuma Elish tells how the god Marduk was endowed with absolute power by the other gods to do battle with Tiamat, a primordial goddess who personified the forces of watery chaos. Marduk defeats Tiamat in battle and proceeds to create the universe by dividing Tiamat in two, one part becoming the heavens and the other the earth, with her breasts as mountains. From her eyes came the Tigris and Euphrates Rivers. The Enuma Elish was recited during the New Year festival celebrated in honor of Marduk in the city of Babylon, which the all-powerful god founded as an earthly residence for the gods after his creation of the universe.


The Mesopotamians viewed their city-states as earthly copies of a divine model and order. Each city-state was sacred because it was linked to a god or goddess. Hence Nippur, the earliest center of Sumerian religion, was dedicated to Enlil, the god of wind. Moreover, located at the heart of each city-state was a temple complex. Occupying several acres, this sacred area consisted of a ziggurat with a temple at the top dedicated to the god or goddess who owned the city. The temple complex was the true center of the community. The main god or goddess dwelt there symbolically in the form of a statue, and the ceremony of dedication included a ritual that linked the statue to the god or goddess and thus supposedly harnessed the power of the deity for the city's benefit. Considerable wealth was poured into the construction of temples and other buildings used for the residences of priests and priestesses who helped the gods. Although the gods literally owned the city, the temple complex used only part of the land and rented out the remainder. The temples dominated individual and commercial life, an indication of the close relationship between Mesopotamian religion and culture.


The physical environment had an obvious impact on the Mesopotamian view of the universe. Ferocious floods, heavy downpours, scorching winds, and oppressive humidity were all part of the local climate. These conditions and the resulting famines easily convinced Mesopotamians that this world was controlled by supernatural forces and that the days of human beings 'are numbered; whatever he may do, he is but wind,' as The Epic of Gilgamesh laments. In the presence of nature, Mesopotamians could easily feel helpless, as this poem relates:


The rampant flood which no man can oppose, Which shakes the heavens and causes earth to tremble, In an appalling blanket folds mother and child, Beats down the canebrake's full luxuriant greenery, And drowns the harvest in its time of ripeness.4  


The Mesopotamians discerned cosmic rhythms in the universe and accepted its order but perceived that it was not completely safe because of the presence of willful, powerful cosmic powers that they identified with gods and goddesses.


With its numerous gods and goddesses animating all aspects of the universe, Mesopotamian religion was polytheistic. The four most important deities were An, Enlil, Enki, and Ninhursaga. An was the god of the sky and hence the most important force in the universe. Since his basic essence was authority, he was also viewed as the source or active principle of all authority, including the earthly power of rulers and fathers alike. Enlil, god of wind, was considered the second greatest power of the visible universe. In charge of the wind and thus an expression of the legitimate use of force, Enlil became the symbol of the proper use of force on earth as well. Enki was god of the earth. Since the earth was the source of life-giving waters, Enki was also god of rivers, wells, and canals. More generally, he represented the waters of creativity and was responsible for inventions and crafts. Ninhursaga began as a goddess associated with soil, mountains, and vegetation. Eventually, however, she was worshiped as a mother goddess, a 'mother of all children,' who manifested her power by giving birth to kings and conferring the royal insignia on them. Human beings' relationship with their gods was based on subservience since, according to Sumerian myth, human beings were created to do the manual labor the gods were unwilling to do for themselves. Moreover, humans were insecure because they could never be sure what the gods would do. But humans did make attempts to circumvent or relieve their anxiety by discovering the intentions of the gods; these efforts gave rise to the development of the arts of divination.


Divination took a variety of forms. A common form, at least for kings and priests who could afford it, involved killing animals, such as sheep or goats, and examining their livers or other organs. Supposedly, features seen in the organs of the sacrificed animals foretold events to come. One handbook predicted that if the animal organ had shape x, the outcome of the military campaign would be y. Private individuals relied on cheaper divinatory techniques. These included interpreting patterns of smoke from burning incense or the pattern formed when oil was poured into water. The Mesopotamian arts of divination arose out of the desire to discover the purposes of the gods: if people could decipher the signs that foretold events, the events would be predictable, and humans could act wisely.


The Cultivation of New Arts and Sciences


The realization of writing's great potential was another aspect of Mesopotamian culture. The oldest Mesopotamian texts date to around 3000 B.C. and were written by the Sumerians, who used a cuneiform ('wedge-shaped') system of writing. Using a reed stylus, they made wedge-shaped impressions on clay tablets, which were then baked or dried in the sun. Once dried, these tablets were virtually indestructible, and the several hundred thousand that have been discovered have served as a valuable source of information for modern scholars. Sumerian writing evolved from drawings of physical objects to simplified and stylized signs, leading eventually to a phonetic system that made possible the written expression of abstract ideas.


Mesopotamian peoples used writing primarily for record keeping. They also produced monumental texts, documents that were intended to last forever, such as inscriptions etched in stone on statues and royal buildings. Numerous texts were prepared for teaching purposes. Schools for scribes were in operation by 2500 B.C. They were necessary because much time was needed to master the cuneiform system of writing. The primary goal of scribal education was to produce professionally trained scribes for careers in the temples and palaces, the military, and government. Pupils were male and primarily from wealthy families.


Writing was important because it enabled a society to keep records and maintain knowledge of previous practices and events. Writing also made it possible for people to communicate ideas in new ways, which is especially evident in Mesopotamian literary works. The most famous piece of Mesopotamian literature was The Epic of Gilgamesh, an elaborate poem that records the exploits of a legendary king of Uruk. Gilgamesh---wise, strong, and perfect in body, part man, part god---befriends a hairy beast named Enkidu. Together they set off in pursuit of heroic deeds. When Enkidu dies, Gilgamesh experiences the pain of mortality and embarks on a search for the secret of immortality. But his efforts fail (see the box above), and Gilgamesh remains mortal. The desire for immortality, one of humankind's great searches, ends in complete frustration. Everlasting life, this Mesopotamian epic makes clear, is only for the gods.


Mesopotamians also made outstanding achievements in mathematics and astronomy. In math, the Sumerians devised a number system based on 60, using combinations of 6 and 10 for practical solutions. Geometry was used to measure fields and erect buildings. In astronomy, the Sumerians made use of units of 60 and charted the heavenly constellations. Their calendar was based on twelve lunar months and was brought into harmony with the solar year by adding an extra month from time to time.


Egyptian Civilization: 'The Gift of the Nile'


Q Focus Questions: What are the basic features of the three major periods of Egyptian history? What elements of continuity are there in the three periods? What are their major differences?


Although contemporaneous with Mesopotamia, civilization in Egypt evolved along somewhat different lines. Of central importance to the development of Egyptian civilization was the Nile River. That the Egyptian people recognized its significance is apparent in this Hymn to the Nile (also see the box above): 'The bringer of food, rich in provisions, creator of all good, lord of majesty, sweet of fragrance. . . . He who . . . fills the magazines, makes the granaries wide, and gives things to the poor. He who makes every beloved tree to grow. . . .'5 Egypt, like Mesopotamia, was a river valley civilization.


The Impact of Geography


The Nile is a unique river, beginning in the heart of Africa and coursing northward for thousands of miles. It is the longest river in the world. Thanks to the Nile, an area several miles wide on both banks of the river was capable of producing abundant harvests. The 'miracle' of the Nile was its annual flooding. The river rose in the summer from rains in Central Africa and the Ethiopian highlands, crested in Egypt in September and October, and left a deposit of silt that enriched the soil. The Egyptians called this fertile land the 'Black Land' because it was dark from the silt and the lush crops that grew on it. Beyond these narrow strips of fertile fields lay the deserts (the 'Red Land').


Unlike the floods of Mesopotamia's rivers, the flooding of the Nile was gradual and usually predictable, and the river itself was seen as life-enhancing, not lifethreatening. Although a system of organized irrigation was still necessary, the small villages along the Nile could make the effort without the massive state intervention that was required in Mesopotamia. Egyptian civilization consequently tended to remain more rural, with many small population centers congregated along a narrow band on both sides of the Nile. About 100 miles before it empties into the Mediterranean, the river splits into two major branches, forming the delta, a triangular-shaped territory called Lower Egypt to distinguish it from Upper Egypt, the land upstream to the south (see Map 1.3). Egypt's important cities developed at the tip of the delta. Even today, most of Egypt's people are crowded along the banks of the Nile River.


The surpluses of food that Egyptian farmers grew in the fertile Nile valley made Egypt prosperous. But the Nile also served as a unifying factor in Egyptian history. In ancient times, the Nile was the fastest way to travel through the land, making both transportation and communication easier. Winds from the north pushed sailboats south, and the current of the Nile carried them north. Often when they headed downstream (north), people used long poles or paddles to propel their boats forward.


Unlike Mesopotamia, which was subject to constant invasion, Egypt was blessed by natural barriers that fostered isolation, protected it from invasion, and gave it a sense of security. These barriers included the deserts to the west and east; the cataracts (rapids) on the southern part of the Nile, which made defense relatively easy; and the Mediterranean Sea to the north. These barriers, however, were effective only when combined with Egyptian fortifications at strategic locations. Nor did they prevent the development of trade. Indeed, there is evidence of very early trade between Egypt and Mesopotamia.


In essence, Egyptian geography and topography played important roles in the early history of the country. The regularity of the Nile floods and the relative isolation of the Egyptians created a sense of security that was accompanied by a feeling of changelessness. To the ancient Egyptians, when the Nile flooded each year, 'the fields laugh and people's faces light up.' Unlike people in Mesopotamia, Egyptians faced life with a spirit of confidence in the stability of things. Egyptian civilization was characterized by a remarkable degree of continuity over thousands of years. 


The Old and Middle Kingdoms


The basic framework for the study of Egyptian history was provided by Manetho, an Egyptian priest and historian who lived in the early third century B.C. He divided Egyptian history into thirty-one dynasties of kings. Using Manetho's and other lists of kings, modern historians have divided Egyptian history into three major periods known as the Old Kingdom, the Middle Kingdom, and the New Kingdom. These were periods of long-term stability characterized by strong monarchical authority, competent bureaucracy, freedom from invasion, the construction of temples and pyramids, and considerable intellectual and cultural activity. But between the periods of stability were intervals known as the Intermediate Periods, characterized by weak political structures and rivalry for leadership, invasions, a decline in building activity, and a restructuring of society.


According to the Egyptians' own tradition, their land consisted initially of numerous populated areas ruled by tribal chieftains. Around 3100 B.C., the first Egyptian royal dynasty, under a king called Menes, united Upper and Lower Egypt into a single kingdom. Henceforth the king would be called 'king of Upper and Lower Egypt,' and one of his symbols would be the Double Crown, combining the White Crown of Upper Egypt and the Red Crown of Lower Egypt. Just as the Nile served to unite Upper and Lower Egypt physically, kingship served to unite the two areas politically.


The Old Kingdom


The Old Kingdom encompassed the third through sixth dynasties of Egyptian kings, lasting from around 2686 to 2181 B.C. It was an age of prosperity and splendor, made visible in the construction of the greatest and largest pyramids in Egypt's history. The capital of the Old Kingdom was located at Memphis, south of the delta.


Kingship was a divine institution in ancient Egypt and formed part of a universal cosmic scheme (see the box on p. 14): 'What is the king of Upper and Lower Egypt? He is a god by whose dealings one lives, the father and mother of all men, alone by himself, without an equal.'6 In obeying their king, subjects helped maintain the cosmic order. A breakdown in royal power could only mean that citizens were offending divinity and weakening the universal structure. Among the various titles of Egyptian kings, pharaoh (originally meaning 'great house' or 'palace') eventually came to be the most common.


Although they possessed absolute power, Egyptian kings were supposed to rule not arbitrarily but according to set principles. The chief principle was called Ma'at, a spiritual precept that conveyed the idea of truth and justice, especially right order and harmony. To ancient Egyptians, this fundamental order and harmony had existed throughout the universe since the beginning of time. Pharaohs were the divine instruments who maintained it and were themselves subject to it.


Although theoretically absolute in their power, in practice Egyptian kings did not rule alone. Initially, members of the king's family performed administrative tasks, but by the fourth dynasty, a bureaucracy with regular procedures had developed. Especially important was the office of vizier, 'steward of the whole land.' Directly responsible to the king, the vizier was in charge of the bureaucracy, with its numerous departments, including police, justice, river transport, and public works. Agriculture and the treasury were the most important departments. Agriculture was, of course, the backbone of Egyptian prosperity, and the treasury collected taxes, which were paid in kind. A careful assessment of land and tenants was undertaken to provide the tax base.


For administrative purposes, Egypt was divided into provinces or nomes, as they were later called by the Greeks---twenty-two in Upper Egypt and twenty in Lower Egypt. A governor, called by the Greeks a nomarch, was head of each nome and was responsible to the king and vizier. Nomarchs, however, tended to build up large holdings of land and power within their nomes, creating a potential rivalry with the pharaohs.


The Middle Kingdom


Despite the theory of divine order, the Old Kingdom eventually collapsed, ushering in a period of disorder. Eventually, a new royal dynasty managed to pacify all Egypt and inaugurated the Middle Kingdom, a new period of stability lasting from around 2055 to 1650 B.C. Several factors contributed to its vitality. The nome structure was reorganized. The boundaries of each nome were now settled precisely, and the obligations of the nomes to the state were clearly delineated. Nomarchs were confirmed as hereditary officeholders but with the understanding that their duties must be performed faithfully. These included the collection of taxes for the state and the recruitment of labor forces for royal projects, such as stone quarrying.


The Middle Kingdom was characterized by a new concern on the part of the pharaohs for the people. In the Old Kingdom, the pharaoh had been viewed as an inaccessible god-king. Now he was portrayed as the shepherd of his people with the responsibility to build public works and provide for the public welfare. As one pharaoh expressed it, 'He [a particular god] created me as one who should do that which he had done, and to carry out that which he commanded should be done. He appointed me herdsman of this land, for he knew who would keep it in order for him.'7


Society and Economy in Ancient Egypt


Egyptian society had a simple structure in the Old and Middle Kingdoms; basically, it was organized along hierarchical lines with the god-king at the top. The king was surrounded by an upper class of nobles and priests who participated in the elaborate rituals of life that surrounded the pharaoh. This ruling class ran the government and managed its own landed estates, which provided much of its wealth. 

Below the upper classes were merchants and artisans. Merchants engaged in active trade up and down the Nile as well as in town and village markets. Some merchants also engaged in international trade; they were sent by the king to Crete and Syria, where they obtained wood and other products. Expeditions traveled into Nubia for ivory and down the Red Sea to Punt for incense and spices. Egyptian artisans displayed unusually high standards of craftsmanship and beauty and produced an incredible variety of goods: stone dishes; beautifully painted boxes made of clay; wooden furniture; gold, silver, and copper tools and containers; paper and rope made of papyrus; and linen clothing.


The largest number of people in Egypt simply worked the land. In theory, the king owned all the land but granted portions of it to his subjects. Large sections were in the possession of nobles and the temple complexes. Most of the lower classes were serfs or common people who were bound to the land and cultivated the estates. They paid taxes in the form of crops to the king, nobles, and priests, lived in small villages or towns, and provided military service and forced labor for building projects.


The Culture of Egypt


Egypt produced a culture that dazzled and awed its later conquerors. The Egyptians' technical achievements alone, especially visible in the construction of the pyramids, demonstrated a measure of skill unique in the world at that time. To the Egyptians, all of these achievements were part of a cosmic order suffused with the presence of the divine.


Spiritual Life in Egyptian Society

The Egyptians had no word for religion because it was an inseparable aspect of existence in the world in which they lived. The Egyptians had a remarkable number of gods associated with heavenly bodies and natural forces---hardly unusual in view of the importance to Egypt's well-being of the sun, the river, and the fertile land along its banks. The sun was the source of life and hence worthy of worship. A sun cult developed, and the sun god took on different forms and names, depending on his specific function. He was worshiped as Atum in human form and as Re, who had a human body but the head of a falcon. The pharaoh took the title 'Son of Re' because he was regarded as the
earthly embodiment of Re.


River and land deities included Osiris and Isis with their child Horus, who was related to the Nile and to the sun as well. Osiris became especially important as a symbol of resurrection. A famous Egyptian myth told of the struggle between Osiris, who brought civilization to Egypt, and his evil brother Seth, who killed him, cut his body into fourteen parts, and tossed them into the Nile. Osiris' faithful wife, Isis, found the pieces and, with help from other gods, restored Osiris to life. As a symbol of resurrection and as judge of the dead, Osiris took on an important role for the Egyptians. By identifying with Osiris, one could hope to gain new life, just as Osiris had done. The dead, embalmed and mummified, were placed in tombs (in the case of kings, in pyramidal tombs), given the name of Osiris, and by a process of magical identification became Osiris. Like Osiris, they would then be reborn. The flood of the Nile and the new life it brought to Egypt were symbolized by Isis gathering all of Osiris' parts together and were celebrated each spring in the festival of the new land.


Later Egyptian spiritual practice began to emphasize morality by stressing Osiris' role as judge of the dead. The dead were asked to give an account of their earthly deeds to show whether they deserved a reward. Other means were also employed to gain immortality. Magical incantations, preserved in the Book of the Dead from the period of the New Kingdom, were used to ensure a favorable journey to a happy afterlife. Specific instructions explained what to do when confronted by the judge of the dead. These instructions had two aspects. The negative confession gave a detailed list of what one had not done:


I have not committed evil against men.
I have not mistreated cattle.
I have not blasphemed a god. . . .
I have not done violence to a poor man. . . .
I have not made anyone sick. . . .
I have not killed. . . .
I have not caused anyone suffering. . . .
I have not had sexual relations with a boy.
I have not defiled myself.8


Later the supplicant made a speech listing his good actions: 'I have done that which men said and that with which gods are content. . . . I have given bread to the hungry, water to the thirsty, clothing to the naked, and a ferry-boat to him who was marooned. I have provided divine offerings for the gods and mortuary offerings for the dead.'9


The Pyramids


One of the great achievements of Egyptian civilization, the building of pyramids, occurred in the time of the Old Kingdom. Pyramids were not built in isolation but as part of a larger complex dedicated to the dead---in effect, a city of the dead. The area included a large pyramid for the king's burial, smaller pyramids for his family, and mastabas, rectangular structures with flat roofs, as tombs for the pharaoh's noble officials. The tombs were well prepared for their residents. The rooms were furnished and stocked with numerous supplies, including chairs, boats, chests, weapons, games, dishes, and a variety of foods. The Egyptians believed that human beings had two bodies, a physical one and a spiritual one, which they called the ka. If the physical body was properly preserved (that is, mummified) and the tomb furnished with all the various objects of regular life, the ka could return and continue its life despite the death of the physical body.


To preserve the physical body after death, the Egyptians practiced mummification, a process of slowly drying a dead body to prevent it from decomposing. Special workshops, run by priests, performed this procedure, primarily for the wealthy families who could afford it. According to Herodotus, an ancient Greek historian (see Chapter 3) who visited Egypt around 450 B.C., 'The most refined method is as follows: first of all they draw out the brain through the nostrils with an iron hook. . . . Then they make an incision in the flank with a sharp Ethiopian stone through which they extract all the internal organs.'10 The liver, lungs, stomach, and intestines were placed in four special jars that were put in the tomb with the mummy. The priests then covered the corpse with a natural salt that absorbed the body's water. Later, they filled the body with spices and wrapped it with layers of linen soaked in resin. At the end of the process, which took about seventy days, a lifelike mask was placed over the head and shoulders of the mummy, which was then sealed in a case and placed in its tomb in a pyramid. 


The largest and most magnificent of all the pyramids was built under King Khufu. Constructed at Giza around 2540 B.C., this famous Great Pyramid covers 13 acres, measures 756 feet at each side of its base, and stands 481 feet high. Its four sides are almost precisely oriented to the four points of the compass. The interior included a grand gallery to the burial chamber, which was built of granite with a lidless sarcophagus for the pharaoh's body. The Great Pyramid still stands as a visible symbol of the power of Egyptian kings and the spiritual conviction that underlay Egyptian society. No later pyramid ever matched its size or splendor. But an Egyptian pyramid was not just the king's tomb; it was also an important symbol of royal power. It could be seen for miles as a visible reminder of the glory and might of the ruler, who was a living god on earth.


Art and Writing


Commissioned by kings or nobles for use in temples and tombs, Egyptian art was largely functional. Wall paintings and statues of gods and kings in temples served a strictly spiritual purpose. They were an integral part of the performance of ritual, which was thought necessary to preserve the cosmic order and hence the well-being of Egypt. Likewise, the mural scenes and sculptured figures found in the tombs had a specific function. They were supposed to aid the journey of the deceased into the afterworld. Egyptian art was also formulaic. Artists and sculptors were expected to observe a strict canon of proportions that determined both form and presentation. This canon gave Egyptian art a distinctive appearance for thousands of years. Especially characteristic was the convention of combining the profile, semiprofile, and frontal views of the human body in relief work and painting in order to represent each part of the body accurately. The result was an art that was highly stylized yet still allowed distinctive features to be displayed.


Writing in Egypt emerged during the first two dynasties. The Greeks later labeled Egyptian writing hieroglyphics, meaning 'priest carvings' or 'sacred writings.' Hieroglyphs were symbols that depicted objects and had a sacred value at the same time. Although hieroglyphs were later simplified into two scripts for writing purposes, they never developed into an alphabet. Egyptian hieroglyphs were initially carved in stone, but later the two simplified scripts were written on papyrus, a paper made from the papyrus reed that grew along the Nile. Most of the ancient Egyptian literature that has come down to us was written on papyrus rolls and wooden tablets.


Disorder and a New Order: The New Kingdom


The Middle Kingdom was brought to an end by a new period of instability. An incursion into the delta region by a people known as the Hyksos initiated this second age of disorder. The Hyksos, a Semitic-speaking people, infiltrated Egypt in the seventeenth century B.C. and came to dominate much of Egypt. However, the presence of the Hyksos was not entirely negative for Egypt. They taught the Egyptians to make bronze for use in new agricultural tools and weapons. The Hyksos also brought new aspects of warfare to Egypt, including the horse-drawn war chariot, a heavier sword, and the compound bow. Eventually, a new line of pharaohs---the eighteenth dynasty--- made use of the new weapons to throw off Hyksos domination, reunite Egypt, establish the New Kingdom (c. 1550--1070 B.C.), and launch the Egyptians along a new militaristic and imperialistic path. During the period of the New Kingdom, Egypt became the most powerful state in the Middle East. The Egyptians occupied Canaan and Syria but permitted local princes to rule under Egyptian control. Egyptian armies also moved westward into Libya and expanded Egypt's border to the south by conquering the African kingdom of Nubia.


The eighteenth dynasty was not without its own troubles, however. Amenhotep IV (c. 1364--1347 B.C.) introduced the worship of Aten, god of the sun disk, as the chief god and pursued his worship with great enthusiasm. Changing his own name to Akhenaten ('Servant of Aten'), the pharaoh closed the temples of other gods and especially endeavored to lessen the power of Amon-Re and his priesthood at Thebes. Akhenaten strove to reduce the priests' influence by replacing Thebes as the capital of Egypt with Akhetaten ('Horizon of Aten'), a new city located at modern Tell el-Amarna, 200 miles north of Thebes.


Akhenaten's attempt at religious change failed. It was too much to ask Egyptians to ignore their traditional ways and beliefs, especially since they saw the destruction of the old gods as subversive of the very cosmic order on which Egypt's survival and continuing prosperity depended. Moreover, the priests at Thebes were unalterably opposed to the changes, which diminished their influence and power. At the same time, Akhenaten's preoccupation with religion caused him to ignore foreign affairs and led to the loss of both Syria and Palestine. Akhenaten's changes were soon undone after his death by those who influenced his successor, the boy-pharaoh Tutankhamen (1347--1338 B.C.). Tutankhamen returned the government to Thebes and restored the old gods. The Aten experiment had failed to take hold, and the eighteenth dynasty itself came to an end in 1333 B.C.


The nineteenth dynasty managed to restore Egyptian power one more time. Under Rameses II (c. 1279--1213 B.C.), the Egyptians regained control of Palestine but were unable to reestablish the borders of their earlier empire. New invasions in the thirteenth century by the 'Sea Peoples,' as the Egyptians called them, destroyed Egyptian power in Palestine and drove the Egyptians back within their old frontiers. The days of Egyptian empire were ended, and the New Kingdom itself expired with the end of the twentieth dynasty in 1070 B.C. For the next thousand years, despite periodical revivals of strength, Egypt was dominated by Libyans, Nubians, Persians, and finally Macedonians after the conquest of Alexander the Great (see Chapter 4). In the first century B.C., Egypt became a province in Rome's mighty empire.


Daily Life in Ancient Egypt: Family and Marriage


Ancient Egyptians had a very positive attitude toward daily life on earth and followed the advice of the wisdom literature, which suggested that people marry young and establish a home and family. Monogamy was the general rule, although a husband was allowed to keep additional wives if his first wife was childless. Pharaohs were entitled to harems; the queen, however, was acknowledged as the Great Wife, with a status higher than that of the other wives. The husband was master in the house, but wives were very much respected and in charge of the household and education of the children. From a book of wise sayings came this advice:


If you are a man of standing, you should found your household and love your wife at home as is fitting. Fill her belly; clothe her back. Ointment is the prescription for her body. Make her heart glad as long as you live. She is a profitable field for her lord. You should not contend with her at law, and keep her far from gaining control. . . . Let her heart be soothed through what may accrue to you; it means keeping her long in your house.11


Women's property and inheritance remained in their hands, even in marriage. Although most careers and public offices were closed to women, some did operate businesses. Peasant women worked long hours in the fields and at numerous domestic tasks, especially weaving cloth. Upperclass women could function as priestesses, and a few queens even became pharaohs in their own right. Most famous was Hatshepsut in the New Kingdom. She served as regent for her stepson Thutmosis III but assumed the throne for herself and remained in power until her death.


Hatshepsut's reign was a prosperous one, as is especially evident in her building activity. She is most famous for the temple dedicated to herself at Deir el Bahri on the west bank of the Nile at Thebes. As pharaoh, Hatshepsut sent out military expeditions, encouraged mining, fostered agriculture, and sent a trading expedition to lower Africa. Hatshepsut's official statues sometimes show her clothed and bearded like a king. She was referred to as 'His Majesty.' That Hatshepsut was aware of her unusual position is evident from an inscription she had placed on one of her temples. It read, 'Now my heart turns to and fro, in thinking what will the people say, they who shall see my monument in after years, and shall speak of what I have done.'


Marriages were arranged by parents. The primary concerns were family and property, and clearly the chief purpose of marriage was to produce children, especially sons (see the box on p. 21). From the New Kingdom came this piece of wisdom: 'Take to yourself a wife while you are a youth, that she may produce a son for you.'12 Daughters were not slighted, however. Numerous tomb paintings show the close and affectionate relationship parents had with both sons and daughters. Although marriages were arranged, some of the surviving love poems from ancient Egypt indicate an element of romance in some marriages. Marriages could and did end in divorce, which was allowed, apparently with compensation for the wife. Adultery, however, was strictly prohibited, and punishments were severe, especially for women, who could have their noses cut off or be burned at the stake.


CONCLUSION


Although early civilizations emerged in different parts of the world, the foundations of Western civilization were laid by the Mesopotamians and Egyptians. They developed cities and struggled with the problems of organized states. They developed writing to keep records and created literature. They constructed monumental architecture to please their gods, symbolize their power, and preserve their culture for all time. They developed new political, military, social, and religious structures to deal with the basic problems of human existence and organization. These first literate civilizations left detailed records that allow us to view how they grappled with three of the fundamental problems that humans have pondered: the nature of human relationships, the nature of the universe, and the role of divine forces in the cosmos. Although later peoples in Western civilization would provide different answers from those of the Mesopotamians and Egyptians, it was they who first posed the questions, gave answers, and wrote them down. At the same time, although the concept of the West did not yet exist, the Mesopotamians' and Egyptians' development of writing and a system of numbers, their creation of law codes, and their practice of different roles based on gender would all eventually influence what became Western civilization.


By the middle of the second millennium B.C., the creative impulse of the Mesopotamian and Egyptian civilizations was beginning to wane. The invasion of the Sea Peoples around 1200 B.C. ushered in a whole new pattern of petty states and new kingdoms that would lead to the largest empires the ancient Near East had seen. 
