#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

CHAPTER 6 THE ROMAN EMPIRE

CHAPTER OUTLINE AND FOCUS QUESTIONS

The Age of Augustus (31 B.C.--A.D. 14)

Q In his efforts to solve the problems Rome had faced during the late Republic, what changes did Augustus make in Rome’s political, military, and social institutions?

The Early Empire (14--180)

Q What were the chief features of the Roman Empire at its height during the second century?

Roman Culture and Society in the Early Empire

Q What were the chief intellectual, artistic, and social developments in the Early Empire? How did these differ from the intellectual, artistic, and social developments of the Republic?

Transformation of the Roman World: Crises in the Third Century

Q What political, military, economic, and social problems did the Roman Empire face during the third century?

Transformation of the Roman World: The Rise of Christianity

Q What characteristics of Christianity enabled it to grow and ultimately to triumph?

CRITICAL THINKING
Q How did Christianity transform the Roman Empire?

Hadrian (with outstretched arms) entering Rome

With the victories of octavian, peace finally settled on the Roman world. Although civil conflict still erupted occasionally, the new imperial state constructed by Octavian experienced a period of remarkable stability for the next two hundred years. To the Romans, their divine mission was clearly to rule nations and peoples. Hadrian, an emperor during the second century A.D., was one of many Roman leaders who believed in Rome’s mission. He was a strong and intelligent ruler who took his responsibilities seriously. Between 121 and 132, he visited all of the provinces in the empire. According to his Roman biographer, Aelius Spartianus, ‘‘Hardly any emperor ever traveled with such speed over so much territory.’’ When he arrived in a province, Hadrian dealt firsthand with any problems and bestowed many favors on the local population. He also worked to establish the boundaries of the provinces and provide for their defense. New fortifications, such as the 80-mile-long Hadrian’s Wall across northern Britain, were built to defend the borders. Hadrian insisted on rigid discipline for frontier armies and demanded that the soldiers be kept in training, ‘‘just as if war were imminent.’’ He also tried to lead by personal example; according to his biographer, he spent time with the troops and ‘‘cheerfully ate out of doors such camp food as bacon, cheese, and vinegar.’’ Moreover, he ‘‘would walk as much as twenty miles fully armed.’’

The Romans imposed their peace on the largest empire established in antiquity. Indeed, Rome’s writers proclaimed that ‘‘by heaven’s will my Rome shall be capital of the world.’’1 Rome’s writers were not quite accurate, but few Romans were aware of the Han Chinese Empire, which flourished at the same time (202 B.C.--A.D. 221) and extended from Central Asia to the Pacific. Although there was little contact between them, the Han and Roman Empires had remarkable similarities: they lasted for centuries, they had great success in establishing centralized control, and they maintained their law and political institutions, their technical skills, and their languages throughout the empire.

By the third century A.D., however, Rome’s ability to rule began to weaken as the empire experienced renewed civil war, economic chaos, and invasions. At the same time, Christianity emerged in one of the most astonishing success stories of Western civilization.

The Age of Augustus
(31 B.C.--A.D. 14)

Q Focus Question: In his efforts to solve the problems Rome had faced during the late Republic, what changes did Augustus make in Rome’s political, military, and social institutions?

In 27 B.C., Octavian proclaimed the ‘‘restoration of the Republic.’’ He understood that only traditional republican forms would satisfy the senatorial aristocracy. At the same time, Octavian was aware that the Republic could not be fully restored and managed to arrive at a compromise that worked at least during his lifetime. In 27 B.C., the senate awarded him the title of Augustus, ‘‘revered one.’’ He preferred the title princeps, meaning ‘‘chief citizen’’ or ‘‘first among equals.’’ The system of rule that Augustus established is sometimes called the principate, conveying the idea of a constitutional monarch as coruler with the senate. But while Augustus worked to maintain this appearance, in reality power was heavily weighted in favor of the princeps.

The New Order

In the new constitutional order that Augustus created, the basic governmental structure consisted of the princeps (Augustus) and an aristocratic senate. Augustus retained the senate as the chief deliberative body of the Roman state. Its decrees, screened in advance by the princeps, now had the effect of law. The title of princeps carried no power in itself, but Augustus held the office of consul each year until 23 B.C., when he assumed the power of a tribune, which enabled him to propose laws and veto any item of public business. By observing proper legal forms for his power, Augustus proved highly popular. As the Roman historian Tacitus commented, ‘‘Indeed, he attracted everybody’s goodwill by the enjoyable gift of peace. . . . Opposition did not exist.’’2 No doubt the ending of the civil wars had greatly bolstered Augustus’ popularity (see the box on p. 110). At the same time, his continuing control of the army, while making possible the Roman peace, was a crucial source of his power.

The Military

Augustus was especially eager to stabilize the military and administrative structures of the Roman Empire. The peace of the empire depended on the army, and so did the security of the princeps. While primarily responsible for guarding the frontiers of the empire, the army was also used to maintain domestic order within the provinces. Augustus maintained a standing army of twenty-eight legions, or about 150,000 men. Roman legionaries were recruited only from the citizenry and, under Augustus, largely from Italy. Augustus also maintained a large contingent of auxiliary forces---around 130,000---enlisted from the subject peoples. Augustus was also responsible for establishing the praetorian guard. Although nominally a military reserve, these ‘‘nine cohorts of elite troops,’’ roughly nine thousand men, had the important task of guarding the person of the princeps. Eventually, the praetorian guard would play a weighty role in making and deposing emperors.

The role of the princeps as military commander gave rise to a title by which this ruler eventually came to be known. When victorious, a military commander was acclaimed by his troops as imperator. Augustus was so acclaimed on a number of occasions. Imperator is our word emperor. Although this title was applied to Augustus and his successors, Augustus continued to refer to himself as the princeps.

Roman Provinces and Frontiers

Augustus inaugurated a new system for governing the provinces. Under the Republic, the senate had appointed the provincial governors. Now certain provinces were allotted to the princeps, who assigned deputies known as legates to govern them. These legates were from the senatorial class and held office as long as the emperor chose. The senate continued to designate the governors of the remaining provinces, but the authority of Augustus enabled him to overrule the senatorial governors and establish a uniform imperial policy.

Augustus also stabilized the frontiers of the Roman Empire. He conquered the central and maritime Alps and then expanded Roman control of the Balkan peninsula up to the Danube River. His attempt to conquer Germany failed when three Roman legions under Varus were massacred in A.D. 9 in the Teutoburg Forest by a coalition of German tribes. The defeat severely dampened Augustus’ enthusiasm for continued expansion in central Europe. Thereafter, the Romans were content to use the Rhine as the frontier between the Roman province of Gaul and the German tribes to the east. In fact, Augustus’ difficulties had convinced him that ‘‘the empire should not be extended beyond its present frontiers.’’3 His defeats in Germany taught Augustus that Rome’s power was not unlimited. They also left him devastated; for months he beat his head against a door, shouting ‘‘Varus, give me back my legions!’’

Augustan Society

Society in the Early Roman Empire was characterized by a system of social stratification, inherited from the Republic, in which Roman citizens were divided into three basic classes: the senatorial, equestrian, and lower classes. Augustus had accepted the senatorial order as a ruling class for the empire. Senators filled the chief magistracies of the Roman government, held the most important military posts, and governed the provinces. One needed to possess property worth 1 million sesterces (an unskilled laborer in Rome received 3 sesterces a day; a Roman legionary, 900 sesterces a year in pay) to belong to the senatorial order. The equestrian order was open to all Roman citizens of good standing who possessed property valued at 400,000 sesterces. They, too, could now hold military and governmental offices, but the positions open to them were less important than those of the senators.

Citizens not of the senatorial or equestrian order belonged to the lower classes, who made up the overwhelming majority of the free citizens. The diminution of the power of the Roman assemblies ended whatever political power they may have possessed earlier in the Republic. Many of these people were provided with free grain and public spectacles to keep them from creating disturbances. Nevertheless, by gaining wealth and serving as lower officers in the Roman legions, it was sometimes possible for them to advance to the equestrian order.

Augustus’ belief that Roman morals had been corrupted during the late Republic led him to initiate social legislation to arrest the decline. He thought that increased luxury had undermined traditional Roman frugality and simplicity and led to a loosening of morals, evidenced by easy divorce, a falling birthrate among the upper classes, and lax behavior manifested in hedonistic parties and the love affairs of prominent Romans with fashionable women and elegant boys.

Through his new social legislation, Augustus hoped to restore respectability to the upper classes and reverse the declining birthrate as well. Expenditures for feasts were limited, and other laws made adultery a criminal offense. In fact, Augustus’ own daughter Julia was exiled for adultery. Augustus also revised the tax laws to penalize bachelors, widowers, and married persons who had fewer than three children.

The Augustan Age

The Augustan Age was a lengthy one. Augustus died in A.D. 14 after dominating the Roman world for forty-five years. He had created a new order while placating the old by restoring and maintaining traditional values, a fitting combination for a leader whose favorite maxim was ‘‘make haste slowly.’’ By the time of his death, his new order was so well established that few agitated for an alternative. Indeed, as the Roman historian Tacitus pointed out, ‘‘Actium had been won before the younger men were born. Even most of the older generation had come into a world of civil wars. Practically no one had ever seen truly Republican government. . . . Political equality was a thing of the past; all eyes watched for imperial commands.’’4 The Republic was now only a memory and, given its last century of warfare, an unpleasant one at that. The new order was here to stay.

The Early Empire (14--180)

Q Focus Question: What were the chief features of the Roman Empire at its height during the second century?

There was no serious opposition to Augustus’ choice of his stepson Tiberius as his successor. By designating a family member as princeps, Augustus established the JulioClaudian dynasty; the next four successors of Augustus were related either to his own family or to that of his wife, Livia.

The Julio-Claudians

Several major tendencies emerged during the reigns of the Julio-Claudians (14--68). In general, more and more of the responsibilities that Augustus had given to the senate were taken over by the emperors, who also instituted an imperial bureaucracy, staffed by talented freedmen, to run the government on a daily basis. As the Julio-Claudian successors of Augustus acted more openly as real rulers rather than ‘‘first citizens of the state,’’ the opportunity for arbitrary and corrupt acts also increased. Nero (54--68) freely eliminated people he wanted out of the way, including his own mother, whose murder he arranged. Without troops, the senators proved unable to oppose these excesses. However, Nero’s extravagances did provoke a revolt of the Roman legions. Abandoned by the guards, Nero chose to commit suicide by stabbing himself in the throat after uttering his final words: ‘‘What an artist the world is losing in me.’’ A new civil war erupted in 69, known as the year of the four emperors. Finally, Vespasian, commander of the legions in the east, established himself as sole ruler and his family as a new dynasty known as the Flavians, which ruled from 69 to 96. The significance of the year 69 was summed up precisely by Tacitus when he stated that ‘‘a well-hidden secret of the principate had been revealed: it was possible, it seemed, for an emperor to be chosen outside Rome.’’5

The Five ‘‘Good Emperors’’ (96--180)

At the beginning of the second century, a series of five socalled good emperors presided over a period of peace and prosperity that lasted almost a hundred years. These men---Nerva, Trajan, Hadrian, Antoninus Pius, and Marcus Aurelius---treated the ruling classes with respect, cooperated with the senate, ended arbitrary executions, maintained peace throughout the empire, and supported domestic policies generally beneficial to the empire. Though absolute monarchs, they were known for their tolerance and diplomacy. By adopting capable men as their successors, the first four good emperors reduced the chances of succession problems.

Under the five good emperors, the powers of the emperor continued to be extended at the expense of the senate. Increasingly, imperial officials appointed and directed by the emperor took over the running of the government. The good emperors also extended the scope of imperial administration to areas previously untouched by the imperial government. Trajan (98--117) established a program that provided state funds to assist poor parents in raising and educating their children.

The good emperors were widely praised by their subjects for their extensive building programs. Trajan and Hadrian (117--138) were especially active in constructing public works---aqueducts, bridges, roads, and harbor facilities---throughout the provinces and in Rome. Trajan built a new forum in Rome to provide a setting for his celebrated victory column. Hadrian’s Pantheon, a temple of ‘‘all the gods,’’ is one of the grandest ancient buildings surviving in Rome.

The Roman Empire at Its Height: Frontiers and Provinces

Although Trajan broke with Augustus’ policy of defensive imperialism by extending Roman rule into Dacia (modern Romania), Mesopotamia, and the Sinai peninsula, his conquests represent the high-water mark of Roman expansion (see Map 6.1). His successors recognized that the empire was overextended and pursued a policy of retrenchment. Hadrian withdrew Roman forces from much of Mesopotamia. Although he retained Dacia and Arabia, he went on the defensive in his frontier policy by reinforcing the fortifications along a line connecting the Rhine and Danube Rivers and by building a defensive wall 80 miles long to keep the Scots out of Roman Britain. By the end of the second century, the vulnerability of the empire had become apparent. Frontiers were stabilized, and the Roman forces were established in permanent bases behind the frontiers. But when one frontier was attacked, troops had to be drawn from other frontiers, leaving those borders vulnerable to attack. The empire lacked a real strategic reserve, and in the next century its weakness would be ever more apparent.

At its height in the second century, the Roman Empire was one of the greatest states the world had seen. It covered about 3.5 million square miles and had a population, like that of Han China, estimated at more than 50 million. While the emperors and the imperial administration provided a degree of unity, considerable leeway was given to local customs, and the privileges of Roman citizenship were extended to many people throughout the empire. In 212, the emperor Caracalla completed the process by giving Roman citizenship to every free inhabitant of the empire. Latin was the language of the western part of the empire, while Greek was used in the east. Although Roman culture spread to all parts of the empire, there were limits to Romanization because local languages persisted and many of the empire’s residents spoke neither Latin nor Greek.

Cities and Romanization

The administration and cultural life of the Roman Empire depended greatly on cities and towns. A provincial governor’s staff was not large, so local city officials were expected to act as Roman agents in carrying out many government functions, especially those related to taxes. Most towns and cities were not large by modern standards. The biggest was Rome, but there were also some large cities in the east: Alexandria in Egypt numbered over 300,000 inhabitants, Ephesus in Asia Minor had 200,000, and Antioch in Syria housed around 150,000. In the west, cities were usually small, with only a few thousand inhabitants. Cities were important in the spread of Roman culture, law, and the Latin language. They were also uniform in physical appearance, with similar temples, markets, amphitheaters, and other public buildings.

Magistrates and town councillors chosen from the ranks of the wealthy upper classes directed municipal administration. These municipal offices were unsalaried but were nevertheless sought by wealthy citizens because they conferred prestige and power at the local level as well as Roman citizenship. Roman municipal policy effectively tied the upper classes to Roman rule and ensured that these classes would retain control over the rest of the population.

The process of Romanization in the provinces was reflected in significant changes in the governing classes of the empire. In the course of the first century, there was a noticeable decline in the number of senators from Italian families. Increasingly, the Roman senate was being recruited from wealthy provincial equestrian families. The provinces also provided many of the legionaries for the Roman army and, beginning with Trajan, supplied many of the emperors.

The extent of Romanization varied widely in different parts of the empire. In the west, including Spain, Africa, and parts of Gaul, where Greeks and Phoenicians had established cities centuries before, Romanization occurred quickly. Temples, aqueducts, amphitheaters, and the Latin language rapidly became fixtures in these areas. Moreover, men from these western territories, especially Spain and parts of Gaul, began serving as officials in Rome as early as the first century A.D.

The process of Romanization was less extensive in other parts of the empire, especially in Asia, where towns and cities had their own traditions long before the arrival of the Romans. Their common language was Greek, not Latin, and many people outside urban areas spoke neither Latin nor Greek. However, although geography was important in determining the degree of Romanization, class status was even more important. By A.D. 200, the upper classes everywhere in the empire had become Romanized, sharing a common culture as well as similar economic and social interests.

Roman Law and Romanization

As Roman citizenship spread in the cities, new citizens themselves became subject to Roman law, which in itself became an important instrument in the process of Romanization. The Early Empire had experienced great progress in the study and codification of law. The second and early third centuries A.D. witnessed the ‘‘classical age of Roman law,’’ a period in which a number of great jurists compiled and classified basic legal principles that have remained extremely valuable in the Western world. Most jurists emphasized the emperor as the source of law: ‘‘What has pleased the emperor has the force of law.’’ The identification of the law of nations with natural law led to a concept of natural rights. According to the jurist Ulpian (d. 228), natural rights implied that all men are born equal and should therefore be equal before the law. In practice, however, that principle was not applied. The Romans did, however, establish standards of justice applicable to all people, many of which we would immediately recognize today. A person was regarded as innocent until proved otherwise. People accused of wrongdoing were allowed to defend themselves before a judge. A judge was expected to weigh evidence carefully before arriving at a decision. These principles lived on in Western civilization long after the fall of the Roman Empire.

For Roman citizens, Roman law provided a uniform system of principles by which they conducted their affairs and led their lives. When the emperor Caracalla gave Roman citizenship to every free person in the empire, Roman law became an even more significant factor in binding the entire empire together.

Prosperity in the Early Empire

The Early Empire was a period of considerable prosperity. Internal peace resulted in unprecedented levels of trade (see Map 6.2). Merchants from all over the empire came to the chief Italian ports of Puteoli on the Bay of Naples and Ostia at the mouth of the Tiber. The importation of large quantities of grain to feed the people of Rome and an incredible quantity of luxury items for the wealthy upper classes in the west led to a steady drain of gold and silver coins from Italy and the west to the eastern part of the empire.

Long-distance trade beyond the Roman frontiers also developed during the Early Empire. Developments in both the Roman and Chinese Empires helped foster the growth of this trade. Although both empires built roads chiefly for military purposes, these arteries also came to be used to facilitate trade. Moreover, by creating large empires, the Romans and Chinese not only established internal stability but also pacified bordering territories, thus reducing the threat that bandits posed to traders. As a result, merchants developed a network of trade routes that brought these two great empires into commercial contact. Most important was the overland Silk Road, a regular caravan route between West and East (see p. 117).

The Silk Road was the route used for Chinese exports to the West of silk cloth. Silk became a craze among Roman elites, leading to a vast outpouring of silver from Rome to China and provoking the Roman emperor Tiberius to grumble that ‘‘the ladies and their baubles are transferring our money to foreigners.’’ The silk trade also stimulated a degree of mutual curiosity between the two great civilizations but not much mutual knowledge or understanding. So far as is known, no personal or diplomatic contacts between the two civilizations ever took place during this era.

Increased trade helped stimulate manufacturing. The cities of the east still produced the items made in Hellenistic times. The first two centuries of the empire also witnessed the high point of industrial development in Italy. Some industries became concentrated in certain areas, such as bronze work in Capua and pottery in Arretium in Etruria. Other industries, such as brickmaking, were pursued in rural areas on large landed estates. Much production remained small-scale and was done by individual craftsmen, usually freedmen or slaves. In the course of the first century, Italian centers of industry began to experience increasing competition from the provinces.

Despite the extensive trade and commerce, agriculture remained the chief occupation of most people and the underlying basis of Roman prosperity. While the large landed estates called latifundia still dominated agriculture, especially in southern and central Italy, small peasant farms persisted, particularly in Etruria and the Po valley. Although large estates concentrating on sheep and cattle raising used slaves, the lands of some latifundia were worked by free tenant farmers who paid rent in labor, produce, or sometimes cash.

In considering the prosperity of the Roman world, it is important to remember the enormous gulf between rich and poor (see the box on p. 117). The development of towns and cities, so important to the creation of any civilization, is based in large degree on the agricultural surpluses of the countryside. In ancient times, the margin of surplus produced by each farmer was relatively small. Therefore, the upper classes and urban populations had to be supported by the labor of a large number of farmers who never found it easy to produce much more than for themselves. In lean years, when there were no surpluses, the townspeople often took what they wanted, leaving little for the peasants.

Roman Culture and Society in the Early Empire

Q Focus Questions: What were the chief intellectual, artistic, and social developments in the Early Empire? How did these differ from the intellectual, artistic, and social developments of the Republic?

The shift from republic to empire not only transformed the Roman political world but also affected its cultural and social life. Intellectuals found ways to accommodate the autocratic rule of emperors, while Roman architects created massive buildings befitting an empire. Gladiatorial games increased dramatically in the Early Empire, and upper-class women acquired greater independence.

The Golden Age of Latin Literature

The most distinguished poet of the Augustan Age was Virgil (70--19 B.C.). The son of a small landholder in northern Italy, he welcomed the rule of Augustus and wrote his greatest work in the emperor’s honor. Virgil’s masterpiece was the Aeneid, an epic poem clearly meant to rival the work of Homer. The connection between Troy and Rome is made explicitly. Aeneas, the son of Anchises of Troy, survives the destruction of Troy and eventually settles in Latium; hence Roman civilization is linked to Greek history. The character of Aeneas is portrayed as the ideal Roman---his virtues are duty, piety, and faithfulness. Virgil’s overall purpose was to show that Aeneas had fulfilled his mission to establish the Romans in Italy and thereby start Rome on its divine mission to rule the world.

Let others fashion from bronze more lifelike, breathing images---

For so they shall---and evoke living faces from marble; Others excel as orators, others track with their instruments

The planets circling in heaven and predict when stars will appear.

But, Romans, never forget that government is your medium!

Be this your art:---to practise men in the habit of peace, Generosity to the conquered, and firmness against aggressors

As Virgil expressed it, ruling was Rome’s gift.

Another prominent Augustan poet was Horace (65--8 B.C.), a friend of Virgil’s. Horace was a sophisticated writer whose overriding concern was to point out to his contemporaries the ‘‘follies and vices of his age.’’ In the Satires, a medley of poems on a variety of subjects, Horace is revealed as a detached observer of human weaknesses. He directed his attacks against movements, not living people, and took on such subjects as sexual immorality, greed, and job dissatisfaction (‘‘How does it happen, Maecenas, that no man alone is content with his lot?’’). Horace mostly laughs at the weaknesses of humankind and calls for forbearance: ‘‘Supposing my friend has got liquored and wetted my couch,. . . is he for such a lapse to be deemed less dear as a friend, or because when hungry he snatched up before me a chicken from my side of the dish?’’7

Ovid (43 B.C.--A.D. 18) was the last of the great poets of the golden age. He belonged to a youthful, privileged social group in Rome that liked to ridicule old Roman values. In keeping with the spirit of this group, Ovid wrote a frivolous series of love poems known as the Amores. Intended to entertain and shock, they achieved their goal. Another of Ovid’s works was The Art of Love. This was essentially a takeoff on didactic poems. Whereas authors of earlier didactic poems had written guides to farming, hunting, or some such subject, Ovid’s work was a handbook on the seduction of women (see the box on p. 119).

The most famous Latin prose work of the golden age was written by the historian Livy (59 B.C.--A.D. 17). Livy’s masterpiece was his History of Rome, covering the years from the foundation of the city (in the seventh century B.C.) to 9 B.C. Only 35 of the original 142 books have survived, although we do possess brief summaries of the whole work from other authors. Livy perceived history in terms of moral lessons. He stated in the preface that

the study of history is the best medicine for a sick mind; for in history you have a record of the infinite variety of human experience plainly set out for all to see; and in that record you can find for yourself and your country both examples and warnings: fine things to take as models, base things, rotten through and through, to avoid.8

For Livy, human character was the determining factor in history.

Livy’s history celebrated Rome’s greatness. He built scene upon scene that not only revealed the character of the chief figures but also demonstrated the virtues that had made Rome great. Of course, he had serious weaknesses as a historian. He was not always concerned about the factual accuracy of his stories. But he was an excellent storyteller, and his work remained the standard history of Rome for centuries.

The Silver Age of Latin Literature

In the history of Latin literature, the century and a half after Augustus is often labeled the ‘‘silver age’’ to indicate that the literary efforts of the period, though good, were not equal to the high standards of the Augustan golden age. The popularity of rhetorical training encouraged the use of clever literary expressions at the expense of original content. A good example of this trend can be found in the works of Seneca.

Educated in Rome, Seneca (c. 4 B.C.--A.D. 65) became strongly attached to the philosophy of Stoicism. In letters written to a young friend, he expressed the basic tenets of Stoicism: living according to nature, accepting events dispassionately as part of the divine plan, and universal love for all humanity. Thus ‘‘the first thing philosophy promises us is the feeling of fellowship, of belonging to mankind and being members of a community. . . . Philosophy calls for simple living, not for doing penance, and the simple way of life need not be a crude one.’’9 Viewed in retrospect, Seneca displays some glaring inconsistencies. While preaching the virtues of simplicity, he amassed a fortune and was ruthless at times in protecting it. His letters show humanity, benevolence, and fortitude, but his sentiments are often undermined by an attempt to be clever with words.

The greatest historian of the silver age was Tacitus (c. 56--120). His main works included the Annals and Histories, which presented a narrative account of Roman history from the reign of Tiberius through the assassination of Domitian (14--96). Tacitus believed that history had a moral purpose: ‘‘It seems to me a historian’s foremost duty to ensure that merit is recorded, and to confront evil deeds and words with the fear of posterity’s denunciations.’’10 As a member of the senatorial class, Tacitus was disgusted with the abuses of power perpetrated by the emperors and was determined that the ‘‘evil deeds’’ of wicked men would not be forgotten. Many historians believe he went too far in projecting the evils of his own day into his account of the past. His work Germania is especially important as a source of information about the early Germans. But it too is colored by Tacitus’ attempt to show the Germans as noble savages in comparison with the decadent Romans.

The Upper-Class Roman Family

By the second century A.D., significant changes were occurring in the Roman family. The foundations of the authority of the paterfamilias over his family, which had already begun to weaken in the late Republic, were further undermined. The paterfamilias no longer had absolute authority over his children; he could no longer sell his children into slavery or have them put to death. Moreover, the husband’s absolute authority over his wife also disappeared, a process that had begun in the late Republic. In the Early Empire, the idea of male guardianship continued to weaken significantly and by the late second century had become a formality.

Upper-class Roman women in the Early Empire had considerable freedom and independence. They had acquired the right to own, inherit, and dispose of property. Upper-class women could attend races, the theater, and events in the amphitheater, although in the latter two places they were forced to sit in sections apart from the men. Moreover, ladies of rank were still accompanied by maids and companions when they went out. Some women operated businesses, such as shipping firms. Women could still not participate in politics, but the Early Empire saw a number of important women who influenced politics through their husbands, including Livia, the wife of Augustus; Agrippina, the mother of Nero; and Plotina, the wife of Trajan.

Imperial Rome

At the center of the colossal Roman Empire was the ancient city of Rome (see Map 6.3). Truly a capital city, Rome had the largest population of any city in the empire. It is estimated that it was home to close to one million people by the time of Augustus. For anyone with political ambitions, Rome was the place to be. Extremely cosmopolitan, it was a magnet to people far and near. Nationalities from all over the empire resided there, with entire neighborhoods inhabited by specific groups, such as Greeks and Syrians.

But for all its sophistication, Rome was an overcrowded and noisy city. Because of the congestion, cart and wagon traffic was banned from the streets during the day. The noise from the resulting vehicular movement at night often made sleep difficult. Evening pedestrian travel was dangerous. Although Augustus had organized a police force, lone travelers could be assaulted, robbed, or soaked by filth thrown out of the upper-story windows of Rome’s massive apartment buildings.

An enormous gulf existed between rich and poor in the city of Rome. While the rich had comfortable villas, the poor lived in apartment blocks called insulae, which might be six stories high. Constructed of concrete, they were often poorly built and prone to collapse. The use of wooden beams in the floors and movable stoves, torches, candles, and lamps in the rooms for heat and light made the danger of fire constant. Once started, fires were extremely difficult to put out. The famous conflagration of 64, which Nero was unjustly accused of starting, devastated a good part of the city. Besides the hazards of collapse and fire, living conditions were also poor. High rents forced entire families into one room. The absence of plumbing and central heating made life so uncomfortable that poorer Romans spent most of their time outdoors in the streets.

Fortunately for these people, Rome boasted public buildings unequaled elsewhere in the empire. Its temples, forums, markets, baths, theaters, triumphal arches, governmental buildings, and amphitheaters gave parts of the city an appearance of grandeur and magnificence.

Though the center of a great empire, Rome was also a great parasite. Beginning with Augustus, the emperors accepted responsibility for providing food for the urban populace, with about 200,000 people receiving free grain. Even with the free grain, conditions were grim for the poor. Early in the second century, a Roman doctor noted that rickets was common among children in the city.

In addition to food, entertainment was provided on a grand scale for the inhabitants of Rome. The poet Juvenal said of the Roman masses, ‘‘But nowadays, with no vote to sell, their motto is ‘Couldn’t care less.’ Time was when their plebiscite elected generals, heads of state, commanders of legions: but now they’ve pulled in their horns, there’s only two things that concern them: Bread and Circuses.’’11 Public spectacles were provided by the emperor and other state officials as part of the great festivals---most of them religious in origin---celebrated by the state. More than one hundred days a year were given over to these public holidays. The festivals included three major types of entertainment. At the Circus Maximus, horse and chariot races attracted hundreds of thousands of spectators, while dramatic and other performances were held in theaters. But the most famous of all the public spectacles were the gladiatorial shows.

The Gladiatorial Shows

The gladiatorial shows were an integral part of Roman society. They took place in amphitheaters, the first permanent one of which had been constructed at Rome in 29 B.C. Perhaps the most famous was the Flavian amphitheater, called the Colosseum, which could seat fifty thousand spectators. Similar amphitheaters were built throughout the empire, with capacities ranging from a few thousand to tens of thousands. In most cities and towns, the amphitheaters were the biggest buildings, rivaled only by the circuses for races and the public baths. Where a society invests its money gives an idea of its priorities. Since the amphitheater was the primary location for the gladiatorial games, it is fair to say that public slaughter was an important part of Roman culture.

Gladiatorial games were held from dawn to dusk. Contests to the death between trained fighters formed the central focus of these games. Most gladiators were slaves or condemned criminals and were trained for combat in special gladiatorial schools.

Gladiatorial games included other forms of entertainment as well. Criminals of all ages and both sexes were sent into the arena without weapons to face certain death from wild animals who would tear them to pieces. Numerous kinds of animal contests were also staged: wild beasts against each other, such as bears against buffaloes; staged hunts with men shooting safely from behind iron bars; and gladiators in the arena with bulls, tigers, and lions. Reportedly, five thousand beasts were killed in one day of games when the emperor Titus inaugurated the Colosseum in A.D. 80. Enormous resources were invested in the capture and shipment of wild animals for slaughter, and whole species were hunted to extinction in parts of the empire.

These bloodthirsty spectacles were wildly popular with the Roman people. The Roman historian Tacitus said, ‘‘Few indeed are to be found who talk of any other subjects in their homes, and whenever we enter a classroom, what else is the conversation of the youths.’’12 But the gladiatorial games served a purpose beyond mere entertainment. Like the other forms of public entertainment, they fulfilled both a political and a social need by diverting thoughts of the idle masses from political unrest. It was said of the emperor Trajan that he understood that although the distribution of grain and money satisfied the individual, spectacles were necessary for the ‘‘contentment of the masses.’’

Transformation of the Roman World: Crises in the Third Century

Q Focus Question: What political, military, economic, and social problems did the Roman Empire face during the third century?

At the end of the second century, a number of natural catastrophes struck Rome. Floods of the Tiber, famine, and plague brought back from the east by the army led to considerable loss of population and a shortage of military manpower. To many Romans, these natural disasters seemed to portend an ominous future for Rome, and indeed, in the course of the third century, the Roman Empire came near to collapse.

Political and Military Woes

After a series of civil wars, Septimius Severus (193--211), who was born in North Africa and spoke Latin with an accent, used his legions to seize power. On his deathbed, Septimius Severus advised his sons, ‘‘Live in harmony, make the soldiers rich, and don’t give a damn for anything else.’’ His advice set the tone for the new dynasty he established. The Severan rulers (193--235) began to create a military monarchy. The army was expanded, soldiers’ pay was increased, and military officers were appointed to important government positions. A new stability seemed at hand, but the increased power of the military led new military leaders to aspire to become emperor, and the military monarchy of the Severan rulers degenerated into military anarchy.

For the next fifty years (235--284), the empire was mired in the chaos of continual civil war. Contenders for the imperial throne found that bribing soldiers was an effective way to become emperor. In these five decades, there were twenty-two emperors, only two of whom did not meet a violent end. At the same time, the empire was beset by a series of invasions, no doubt encouraged by the internal turmoil. In the east, the Sassanid Persians made inroads into Roman territory. A fitting symbol of Rome’s crisis was the capture of the Roman emperor, Valerian (253--260), by the Persians and his death in captivity, an event unprecedented in Roman history. Valerian’s body was displayed in the chief towns of Persia. Germanic tribes also poured into the empire. The Goths overran the Balkans and moved into Greece and Asia Minor. The Franks advanced into Gaul and Spain. Not until the reign of Aurelian (270--275) were most of the boundaries restored. Although he abandoned the Danubian province of Dacia, Aurelian reconquered Gaul and reestablished order in the east and along the Danube. Grateful citizens hailed him as ‘‘restorer of the world.’’

As civil wars and invasion wore down the central government, provinces began to break away from the empire. A military commander named Postumus seized control of Gaul and then gained the support of Britain and Spain. He defended his ‘‘Gallic empire’’ until he was killed by his own soldiers in 269. In the east, Zenobia, the wife of the ruler of Syria, seized power after his death and then in 270 extended her control over Egypt and much of Asia Minor. In 272, Emperor Aurelian ended this threat to imperial power by defeating Zenobia and her forces in Syria.

Economic and Social Crises

Invasions, civil wars, and plague came close to causing an economic collapse of the Roman Empire in the third century. The population declined drastically, possibly by as much as one-third. There was a noticeable decline in trade and small industry. The labor shortage created by plague affected both military recruiting and the economy. Farm production deteriorated significantly. Fields were ravaged by Germanic tribes and even more often by the defending Roman armies. Many farmers complained that Roman commanders and their soldiers were confiscating produce and livestock. Provincial governors seemed powerless to stop these depredations, and some even joined in the extortion. The monetary system began to show signs of collapse as a result of debased coinage and the beginnings of serious inflation.

Armies were needed more than ever, but financial strains made it difficult to enlist and pay the necessary soldiers. Short of cash, the imperial government paid its soldiers with produce, causing bitter resentment. Whereas in the second century the Roman army had been recruited among the inhabitants of frontier provinces, by the mid-third century the state had to rely on hiring barbarians to fight under Roman commanders. These soldiers had no understanding of Roman traditions and no real attachment to either the empire or the emperors. By the end of the third century, a new political structure would emerge (see Chapter 7).

Transformation of the Roman World: The Rise of Christianity

Q Focus Question: What characteristics of Christianity enabled it to grow and ultimately to triumph?

The advent of Christianity marks a fundamental break with the dominant values of the Greco-Roman world. Christian views of God, human beings, and the world were quite different from those of the Greeks and Romans. Nevertheless, to understand the rise of Christianity, we must first examine both the religious environment of the Roman world and the Jewish background from which Christianity emerged.

The Religious World of the Roman Empire

Augustus had taken a number of steps to revive the Roman state religion, which had declined during the turmoil of the late Republic. The official state religion focused on the worship of a pantheon of gods and goddesses. Observance of proper ritual by state priests theoretically established the proper relationship between Romans and the gods and guaranteed security, peace, and prosperity. The polytheistic Romans were extremely tolerant of other religions. The Romans allowed the worship of native gods and goddesses throughout their provinces and even adopted some of the local gods. In addition, the imperial cult of Rome and Augustus was developed to bolster support for the emperors. After Augustus, deceased emperors deified by the Roman senate were included in the official imperial cult.

The desire for a more emotional spiritual experience led many people to the mystery religions of the Hellenistic east, which flooded into the western Roman world during the Early Empire. The mystery religions offered secret teachings that promised their followers advantages unavailable through Roman religion: entry into a higher world of reality and the promise of a future life superior to the present one. They also featured elaborate rituals with deep emotional appeal. By participating in their ceremonies and performing their rites, an adherent could achieve communion with spiritual beings and undergo purification that opened the door to life after death. Although many mystery cults competed for the attention of the Roman world, perhaps the most important was Mithraism. Mithras was the chief agent of Ahuramazda, the supreme god of light in Persian Zoroastrianism (see Chapter 2). In the Roman world, Mithras came to be identified with the sun god and was known by his Roman title, the Unconquered Sun. Mithraism had spread rapidly in Rome and the western provinces by the second century A.D. and was especially favored by soldiers, who viewed Mithras as their patron deity. Mithraists paid homage to the sun on the first day of the week (Sunday), commemorated the sun’s birthday around December 25, and celebrated ceremonial meals. All of these practices had parallels in Christianity.

The Jewish Background

In Hellenistic times, the Jewish people had been granted considerable independence by their Seleucid rulers (see Chapter 4). Roman involvement with the Jews began in 63 B.C., and by A.D. 6, Judaea had been made a province and placed under the direction of a Roman procurator. But unrest continued, augmented by divisions among the Jews themselves. The Sadducees favored a rigid adherence to Hebrew law, rejected the possibility of personal immortality, and favored cooperation with the Romans. The Pharisees followed a strict adherence to Jewish ritual, and although they wanted Judaea to be free from Roman control, they did not advocate violent means to achieve this goal. The Essenes were a Jewish sect that lived in a religious community near the Dead Sea. As revealed in the Dead Sea Scrolls, a collection of documents first discovered in 1947, the Essenes, like many other Jews, awaited a Messiah who would save Israel from oppression, usher in the kingdom of God, and establish a true paradise on earth. A fourth group, the Zealots, were militant extremists who advocated the violent overthrow of Roman rule. A Jewish revolt in A.D. 66 was crushed by the Romans four years later. The Jewish Temple in Jerusalem was destroyed, and Roman power once more stood supreme in Judaea.

The Origins of Christianity

In the midst of the confusion and conflict in Judaea, Jesus of Nazareth (c. 6 B.C.--A.D. 30) began his public preaching. Jesus grew up in Galilee, an important center of the militant Zealots. Jesus’ message was straightforward. He reassured his fellow Jews that he did not plan to undermine their traditional religion: ‘‘Do not think that I have come to abolish the Law or the Prophets; I have not come to abolish them but to fulfill them.’’13 According to Jesus, what was important was not strict adherence to the letter of the law and attention to rules and prohibitions but the transformation of the inner person: ‘‘So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets.’’14 God’s command was simple---to love God and one another: ‘‘Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. The second is this: Love your neighbor as yourself.’’15 In his Sermon on the Mount, Jesus presented the ethical concepts---humility, charity, and brotherly love---that would form the basis for the value system of medieval Western civilization. As we have seen, these were not the values of classical Greco-Roman civilization.

Although some Jews welcomed Jesus as the Messiah who would save Israel from oppression and establish God’s kingdom on earth, Jesus spoke of a heavenly kingdom, not an earthly one: ‘‘My kingdom is not of this world.’’16 In this he disappointed the radicals. At the same time, conservative religious leaders believed that Jesus was another false Messiah who was undermining respect for traditional Jewish religion. To the Roman authorities of Palestine and their local allies, the Nazarene was a potential revolutionary who might transform Jewish expectations of a messianic kingdom into a revolt against Rome. Jesus thus found himself denounced on many sides and was given over to the Roman authorities. The procurator Pontius Pilate ordered his crucifixion. But that did not solve the problem. A few loyal disciples spread the story that Jesus had overcome death, had been resurrected, and had then ascended into heaven. The belief in Jesus’ resurrection became an important tenet of Christian doctrine. Jesus was now hailed by his followers as the ‘‘anointed one’’ (Christos in Greek), the Messiah who would return and usher in the kingdom of God on earth.

The Importance of Paul

Christianity began, then, as a religious movement within Judaism and was viewed that way by Roman authorities for many decades. Although tradition holds that one of Jesus’ disciples, Peter, founded the Christian church at Rome, the most important figure in early Christianity after Jesus was Paul of Tarsus (c. 5--c. 67). Paul reached out to non-Jews and transformed Christianity from a Jewish sect into a broader religious movement.

Called the ‘‘second founder of Christianity,’’ Paul was a Jewish Roman citizen who had been strongly influenced by Hellenistic Greek culture. He believed that the message of Jesus should be preached not only to Jews but to Gentiles (non-Jews) as well. Paul was responsible for founding Christian communities throughout Asia Minor and along the shores of the Aegean.

It was Paul who provided a universal foundation for the spread of Jesus’ ideas. He taught that Jesus was, in effect, a savior-God, the son of God, who had come to earth to save all humans, who were basically sinners as a result of Adam’s original sin of disobedience against God as recorded in the Old Testament. By his death, Jesus had atoned for the sins of all humans and made it possible for all men and women to experience a new beginning with the potential for individual salvation. By accepting Jesus Christ as their Savior, they too could be saved.

The Spread of Christianity

Christianity spread slowly at first. Although the teachings of early Christianity were disseminated primarily by the preaching of convinced Christians, written materials also appeared. Paul had written a series of epistles (letters) outlining Christian beliefs for different Christian communities. Some of Jesus’ disciples may also have preserved some of the sayings of the master in writing and would have passed on personal memories that became the basis of the written gospels---the ‘‘good news’’ concerning Jesus as recorded by Matthew, Mark, Luke, and John---which eventually became the authoritative record of Jesus’ life and teachings and formed the core of the New Testament. Recently, some scholars have argued that other gospels, such as that of Thomas, were rejected because they deviated from the beliefs about Jesus held by the emerging church leaders.

Although Jerusalem was the first center of Christianity, its destruction by the Romans in A.D. 70 left individual Christian churches with considerable independence. By 100, Christian churches had been established in most of the major cities of the east and in some places in the western part of the empire. Many early Christians came from the ranks of Hellenized Jews and the Greek-speaking populations of the east. But in the second and third centuries, an increasing number of followers came from Latinspeaking cultures. A Latin translation of the Greek New Testament that appeared soon after 200 aided this process.

Although some of the fundamental values of Christianity differed markedly from those of the Greco-Roman world, the Romans initially did not pay much attention to the Christians, whom they regarded at first as simply another sect of Judaism. The structure of the Roman Empire itself aided the growth of Christianity. Christian missionaries, including some of Jesus’ original twelve disciples, known as apostles, used Roman roads to travel throughout the empire spreading their ‘‘good news.’’

As the popular appeal of Christianity grew, the Roman attitude toward it began to change. The Romans were tolerant of other religions except when they threatened public order or public morals. Many Romans came to view Christians as harmful to the order of the Roman state. Because Christians held their meetings in secret and seemed to be connected to Christian groups in distant areas, the government could view them as potentially dangerous to the state.

Some Romans felt that Christians were overly exclusive and hence harmful to the community and public order. The Christians did not recognize other gods and therefore abstained from public festivals honoring these divinities. Finally, Christians refused to participate in the worship of the state gods and the imperial cult. Since the Romans regarded these as important to the state, the Christians’ refusal undermined the security of the state and hence constituted an act of treason, punishable by death. But to the Christians, who believed there was only one real God, the worship of state gods and the emperors was idolatry and would endanger their own salvation.

Roman persecution of Christians in the first and second centuries was never systematic but sporadic and local. It began during the reign of Nero. After the fire that destroyed much of Rome, the emperor used the Christians as scapegoats, accusing them of arson and hatred of the human race and subjecting them to cruel deaths in Rome. In the second century, Christians were largely ignored as harmless (see the box on p. 126). By the end of the reigns of the five good emperors, Christians still represented a small minority, but one of considerable strength.

The Growth of Christianity

The sporadic persecution of Christians by the Romans in the first and second centuries had done nothing to stop the growth of Christianity. It had, in fact, served to strengthen Christianity as an institution in the second and third centuries by causing it to shed the loose structure of the first century and move toward a more centralized organization of its various church communities. Crucial to this change was the emerging role of the bishops, who began to assume more control over church communities. The Christian church was creating a welldefined hierarchical structure in which the bishops and clergy were salaried officers separate from the laity or regular church members.

The Appeal of Christianity

Christianity grew slowly in the first century, took root in the second, and had spread widely by the third. Why was Christianity able to attract so many followers? First of all, the Christian message had much to offer the Roman world. The promise of salvation, made possible by Jesus’ death and resurrection, had immense appeal in a world full of suffering and injustice. Christianity seemed to imbue life with a meaning and purpose beyond the simple material things of everyday reality. Second, Christianity was not entirely unfamiliar. It could be viewed as simply another eastern mystery religion, offering immortality as the result of the sacrificial death of a savior-God. At the same time, it offered advantages that the other mystery religions lacked. Jesus had been a human figure, not a mythological one, such as Mithras. Moreover, Christianity had universal appeal. Unlike Mithraism, it was not restricted to men. Furthermore, it did not require a painful or expensive initiation rite as other mystery religions did. Initiation was accomplished simply by baptism---a purification by water---by which one entered into direct communion with Jesus. In addition, Christianity gave new meaning to life and offered what the Roman state religions could not---a personal relationship with God and a link to higher worlds.

Finally, Christianity fulfilled the human need to belong. Christians formed communities bound to one another in which people could express their love by helping each other and offering assistance to the poor, the sick, widows, and orphans. Christianity satisfied the need to belong in a way that the huge, impersonal, and remote Roman Empire could never do.

Christianity proved attractive to all classes. The promise of eternal life was for all---rich, poor, aristocrats, slaves, men, and women. As Paul stated in his Epistle to the Colossians: ‘‘And [you] have put on the new self, which is being renewed in knowledge in the image of its Creator. Here there is no Greek nor Jew, circumcised or uncircumcised, barbarian, Scythian, slave or free, but Christ is all, and is in all.’’17 Although it did not call for revolution or social upheaval, Christianity emphasized a sense of spiritual equality for all people.

Women and Early Christianity

As we have seen, firstcentury Christian communities had allowed both men and women to play significant roles. By the second century, however, men had gained control of church organization and relegated women to secondary roles. Women, as Paul had argued, should be subject to men. Nevertheless, many women found that Christianity offered them new roles and new forms of companionship with other women. Christian women fostered the new religion in their own homes and preached their convictions to other people in their towns and villages. Many also died for their faith. Perpetua was an aristocratic woman who converted to Christianity. Her pagan family begged her to renounce her new faith, but she refused. Arrested by the Roman authorities, she chose instead to die for her faith and was one of a group of Christians who were slaughtered by wild beasts in the arena at Carthage on March 7, 203.

The Failure of Persecution

As the Christian church became more organized, some emperors in the third century responded with more systematic persecutions, but their schemes failed to work. The last great persecution was by Diocletian at the beginning of the fourth century. But even he had to admit what had become apparent in the course of the third century: Christianity had become too strong to be eradicated by force.

CONCLUSION

The Roman Republic had created one of the largest empires in antiquity, but its republican institutions had proved inadequate for the task of ruling an empire. After a series of bloody civil wars, Augustus created a new order that began the Roman Empire, which experienced a lengthy period of peace and prosperity between 14 and 180. During this Pax Romana, trade flourished and the provinces were governed efficiently. In addition, within their empire, the Romans developed a remarkable series of achievements that were bequeathed to the future.

These achievements were fundamental to the development of Western civilization, which consisted largely of lands in Europe conquered by the Romans in which Roman cultural and political ideals were gradually spread. The Romance languages of today (French, Italian, Spanish, Portuguese, and Romanian) are based on Latin. Western practices of impartial justice and trial by jury owe much to Roman law. As great builders, the Romans left monuments to their skills throughout Europe, some of which, including aqueducts and roads, are still in use today. Other monuments provided models for public buildings in the West for hundreds of years. Aspects of Roman administrative practices survived in the Western world for centuries. The Romans also preserved the intellectual heritage of the Greco-Roman world of antiquity.

By the third century A.D., the Roman world was being buffeted by civil wars, invasions, and economic problems. At the same time, a new religion---Christianity---was spreading throughout the empire. As we shall see in the next chapter, the response to these developments slowly transformed the Roman Empire.
