* 为什么我们的雅思课程更有效
雅思高分需要什么?
智力+努力+高效率方法+备考方向+备考资料

** 1.智力,并不需要极高的智力
心理学（growth mindset）和脑神经学（neuroplasticity）的最新科研成果告诉您，智力水平是可以在成年后被提升的。而我会尝试这样去做。

** 2.努力水平
中国的学习比德国的努力,但成绩不如德国的
好的老师是可以通过提升您内心的学习动力来提升您的努力水平。
那么，一来我专门学习过教育心理学的相关知识，深知提升学习动力的技巧和手段。
二来过去的10年以上的教学经验告诉我，我可以提升大部分学员的学习动力，进而提升努力水平。

** 3.备考资料
因为我的课上会教您如何提升“搜商”—即搜索材料的能力，正所谓给您材料是给您鱼，而教您如何搜材料，是给您钓鱼技术。

** 4.高效率方法
这个是咱们真的稀缺的。
单词到底该如何记忆？怎么记单词效率才高，才能记住？
是否需要刷真题？雅思托福考试到底是考题难还是英语难？
背诵写作与口语模版对提分到低有多大帮助？
听不懂，读不懂到低能不能拿到分数？
有没有什么办法逆袭学霸？
如何做到备考雅思托福的同时一箭多雕？
而这些问题是我上课重点要讲解的内容。
我将尝试让您告别挂上一档猛轰油门的过去，轻装上阵，优雅的挂上五档轻点油门，一路狂飙。

** 5.备考方向
过分关注考试反而阻碍了能力的提升,结果是考试成绩低.
而课程中，我会尝试指出一个更符合雅思托福考试本质的备考方向，而非市面上最流行的方法。因为最流行的备考方法，让一个如此勤劳努力，智商在线的民族在雅思托福考试的平均分上却远远低于国际平均水平。

雅思托福这样的考试，到底是考题格外难，还是英语格外难？
英语本身难.

我们的所有考生的平均分，某种程度上宣判了市场上最流行的研究考题，把大量时间精力放到考题上的这个学习方法就是失败的。

我希望通过上面这个问题清楚的告诉您，我的课上几乎全部时间就是用在提升英语硬实力上的，而非研究考题上。因为再说一遍，雅思托福考的是英语的硬实力。英语硬实力提升了，雅思托福的分数自然就提升了。

考托福的人能报名么？能，因为我教的是提升英语硬实力的办法，而非关注考试或者考题本身，但因为硬实力提升，就能提升雅思和托福的成绩，所以并不矛盾。

没有雅思托福考试需求，甚至任何考试的需求，能报名么？能，因为我的课程最关注的是英语硬实力的提升。

