#+OPTIONS: \n:t num:nil html-postamble:nil

* task13-prereading-2
家庭作业2:Western Civilization: chapter3
1. [写作]: 回答问题[先完成再完美]
2. [泛读: 输出倒逼输入]再阅读n遍找答案skimming+outline+Paraphrase[看着原文答案改句子]
3. [泛听]确定topic + 查找油管
4. [口语]:跟读部分文章+朗读作文[1中]+summary+ 查找真题看看哪题能用[1中]

** 1. [写作]: 回答问题[先完成再完美]
1. Early Greece -
	 How did the geography of Greece affect Greek history?

	 Geography had an significant impact on Greek history,
		especially due to the presence the mountains and the sea.
	 The mountainous terrain isolated Greek from one another,
		therefore Greek communities were more care about their independence
			and were only too likely to fight other to gain advantage.
	 The sea also played an part in Greek society.
	 Greece boasted a long seacoast,
		which was dotted by bays and inlets that provided a great many of harbors.
	 This lead to that the Greek sailed out into the Aegean and the Mediterranean first
		so as to contact with the outside world and to establish colonies.
		
2. The Greeks in a Dark Age (c.1100-c.750 B.C.) -
	 Who was Homer, and why was his work used as the basis for Greek education?
	 Homer, who had composed the Iliad and the Odyssey, is a poet near the very end of a Dark Age.
   Homer's world display the values of aristocratic heroes
		and gave the Greeks a model of heroism, honor, and nobility.
	 Anxiosu to see their children develop into a good man,
		the Greeks males used his masterpieces as the sources of their education.

3. The World of the Creek City-States -
	 What were the chief features of the polis, or city-state,
		and how did the major city-state of Athens and Sparta differ?
	 The Greek polis is a primary institution in Greek society.
	 In a physical sense a polis, which varied greatly in size,
		included a town or city or even a village and its surrounding countryside.
	 As as community, the polis consisted of citizen with political rights,
		citizen with no political rights, and noncitizense
			which possessed basic rights and responsibilities.
	 The major city-state of Athens and Sparta vary in certain aspects, their origins,
		and how the crises of them are resloved.
	 The Spartans originally becamed unified into a single polis in Laconia.
	 They conquered their neighbours, Laconians and Messenia,
		and turned Laconia and Messenia into slaves.
	 The spartans created a military state so that they could take control of these slaves.
	 Futuremore, the Spartans choosed to isolated themselves from the external world
		to make their military state secure.
	 However, the situation in Athens was different from that in Sparta.
	 Athens established a unified a unified polis on the peninsula of Attica by 700 B.C
		and confronted political turmoil
			by serious economic problems near the end of seventh century B.C.
	 Solon was chosen to solve this crsis,
		 but his economic reforms and political measures were compromises.
	 Then, Cleisthenes continued to reform,
		and a major aim of his reforms was to weaken the power of traditional localities and regions.
	 To conclusion, Sparta transformed into a united city-state in Laconia
		and Athens on the peninsula of Attica.
	 To ensure their power and development Sparta build a military state
		and be close with the outside world.
	 To solve Athens economic crsis Solon and Cleisthenes continued reforming.

		
4. The High Point of Greek Civilization:Classical Greece -
	 What did the Greeks mean by democracy,
		and in what ways was the Athenian political system a democracy?
	 What effect did the two great conflicts of the fifth century B.C.
		-the Persian Wars and the Peloponnesian War - have on Greek civilization?
	 The Greeks called their form of government democracy that power was in the hands of the people.
	 Male citizen voted in the assemblies and served as jurors in the courts.
	 State pay for officeholders
		so that poor citizens could hold public office and afford to partcipate in pubic affairs.
	 After the defeat of the Persians,
		Athens provide new leadership against the Persians
			by forming a confederation named the Delian League.
	 The Athenians refused its members to departure
		and used the money in the league treasury
			 to build new temples in Athens without their approval.
	 The Delian League had become the Athenian Empire
		and resulted in a new war all Greece by alarming the other Greek states.
	 The Greek world divided into two major camps: Sparta and its supporters and the Athenian Empire.
	 They had fought against each other for a long time.
	 The war weakened the major Greek states and led to new alliances among the poleis.
		
5. CT:
	 Why is the civilization of the Greeks
		considered the cornerstone of the Western intellectual tradition?
	 There are several reasons
		that I think the civilization of the Greeks is regarded as the cornerstone of the Western intellectual tradition.
	 First, the Greeks sailed out into the Aegean and the Mediterranean first
	  so that they could contact with the outside world and to establish colonies.
	 Futhermore, Homer's masterpieces gave the Greeks a model of heroism, honor and nobility.
	 Moreover, the key aspect is democracy that power was in the hands of the people,
		and even poor citizens could hold public office and afford to partcipate in public affairs.
	 In conclusion, contacte with the external world, the values of courage and honor,
		as well as democracy, laid the cornerstone of the Western intellectual tradition.
		
** DONE 2. [泛读: 输出倒逼输入]再阅读n遍找答案skimming+outline+Paraphrase[看着原文答案改句子]
CLOSED: [2023-09-10 Sun 16:31]
** DONE 3. [泛听]: 确定topic + 查找油管
CLOSED: [2023-09-10 Sun 17:28]
Aristotle
涉猎很广
哲学家,物理学家,生物学家
定义幸福
政治体系
逻辑学

也有很多错误的观念
存在有原因
物体运动是因为有力推动
** 4. [口语]: 跟读部分文章+朗读作文[1中]+summary+ 查找真题看看哪题能用[1中]
