#+OPTIONS: \n:t
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
* Reading to Learn the Art of Expression

When you read a short story, you may read it merely for pleasure.
When you read a biographical sketch, you may read it merely for information.
But as you are a learner of English, I think you should often read to learn the art of expression.
And for this purpose you may read either a short story or a biographical sketch, either an essay or a news item, indeed, anything that is written in good current English.

Even from a short paragraph you may learn several forms of expression if you are observant enough.
Try to read the following paragraphs from BBC Modern English and notice the points of usage listed below;

Over 100 years ago she opened the first British hospital for women.
There are still very few of these hospitals in England.
This hospital is in Euston Road in London.
Its situation means that women from all over England can reach it quite easily.

Her aim when she opened the hospital was to provide a place where women could go and receive treatment from female doctors and nurses.
She also wanted the hospital to provide jobs for female doctors at a time when it was very difficult for them to find work.
Recently the authorities have tried to close the hospital.
They say that it is old-fashioned and wastes a lot of money.
However, the Government has decided that the hospital will stay open.
Many people feel very glad that the valuable service offered by this hospital will continue.

1. “Over” More than.
2. "in Euston Road" "in ... Road".
3. “means that ...” “Means” takes an object clause introduced by “that”.
4. “from all over England” “all over England” “from all over England”.
5. “receive treatment”. Patients receive treatment.
6. “wanted the hospital to provide ..."
“We want them to do it”.
7. “at a time when ...” “at a time when ..."
8. “Recently the authorities have tried.” The present perfect is here used with “recently”.
9. “the Government has” “the Government" can be considered singular.
10. “decided that ...” “Decide(d)” takes an object clause introduced by “that”.
11. “stay open”. “Stay” can be a copulative verb.

In this way you will learn the art of expression very quickly;
perhaps one or two paragraphs a day will teach you hundreds of forms of expression in a month, and these forms of expression will greatly improve your writing.
And if you can -- I believe you can -- commit to memory' one or two paragraphs a day
that you have already read in this way, the results will be still greater;
