#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 18th PREPARE FOR THE STORM
#+begin_verse
'This is the true athlete—the person in rigorous training against false impressions. Remain firm,
  you who suffer,
  don't be kidnapped by your impressions! The struggle is great,
  the task divine—to gain mastery,
  freedom,
  happiness,
  and tranquility.' —EPICTETUS,
  DISCOURSES,
  2.
18.
27–28 pictetus also used the metaphor of a storm,
  saying that our impressions are not unlike extreme weather that can catch us and whirl us about.
When we get worked up or passionate about an issue,
  we can relate.
But let's think about the role of the weather in modern times.
Today,
  we have forecasters and experts who can fairly accurately predict storm patterns.
Today,
  we're defenseless against a hurricane only if we refuse to prepare or heed the warnings.
If we don't have a plan,
  if we never learned how to put up the storm windows,
  we will be at the mercy of these external—and internal— elements.
We're still puny human beings compared with one-hundredmile-per-hour winds,
  but we have the advantage of being able to prepare —being able to struggle against them in a new way.
T
#+end_verse