#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 29th YOU CAN’T ALWAYS (BE) GET(TING) WHAT YOU WANT
#+begin_verse
'When children stick their hand down a narrow goody jar they can't get their full fist out and start crying. Drop a few treats and you will get it out! Curb your desire—don't set your heart on so many things and you will get what you need.' —EPICTETUS,
  DISCOURSES,
  3.
9.
22 e can have it all' is the mantra of our modern lives.
Work,
  family,
  purpose,
  success,
  leisure time—we want all of this,
  at the same time (right now,
  to boot).
In Greece,
  the lecture hall (scholeion) was a leisure center where students contemplated the higher things (the good,
  true,
  and beautiful) for the purpose of living a better life.
It was about prioritization,
  about questioning the priorities of the outside world.
Today,
  we're too busy getting things,
  just like kids jamming their hand down a jar of goodies,
  to do much of this questioning.
'Don't set your heart on so many things,
  ' says Epictetus.
Focus.
Prioritize.
Train your mind to ask:
  Do I need this thing?
What will happen if I do not get it?
Can I make do without it?
The answers to these questions will help you relax,
  help you cut out all the needless things that make you busy—too busy to be balanced or happy.
MARCH AWARENESSP
#+end_verse