#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 22nd WHAT’S BETTER LEFT UNSAID
#+begin_verse
'Cato practiced the kind of public speech capable of moving the masses,
  believing proper political philosophy takes care like any great city to maintain the warlike element. But he was never seen practicing in front of others,
  and no one ever heard him rehearse a speech. When he was told that people blamed him for his silence,
  he replied,
  'Better they not blame my life.
I begin to speak only when I'm certain what I'll say isn't better left unsaid.
'' —PLUTARCH,
  CATO THE YOUNGER,
  4 t's easy to act—to just dive in.
It's harder to stop,
  to pause,
  to think:
  No,
  I'm not sure I need to do that yet.
I'm not sure I am ready.
As Cato entered politics,
  many expected swift and great things from him— stirring speeches,
  roaring condemnations,
  wise analyses.
He was aware of this pressure—a pressure that exists on all of us at all times—and resisted.
It's easy to pander to the mob (and to our ego).
Instead,
  he waited and prepared.
He parsed his own thoughts,
  made sure he was not reacting emotionally,
  selfishly,
  ignorantly,
  or prematurely.
Only then would he speak—when he was confident that his words were worthy of being heard.
To do this requires awareness.
It requires us to stop and evaluate ourselves honestly.
Can you do that?
A
#+end_verse