#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 23rd CIRCUMSTANCES HAVE NO CARE FOR OUR FEELINGS
#+begin_verse
'You shouldn't give circumstances the power to rouse anger,
  for they don't care at all.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
38 significant chunk of Marcus Aurelius's Meditations is made up of short quotes and passages from other writers.
This is because Marcus wasn't necessarily trying to produce an original work—instead he was practicing,
  reminding himself here and there of important lessons,
  and sometimes these lessons were things he had read.
This particular quote is special because it comes from a play by Euripides,
  which,
  except for a handful of quoted fragments like this,
  is lost to us.
From what we can gather about the play,
  Bellerophon,
  the hero,
  comes to doubt the existence of the gods.
But in this line,
  he is saying:
  Why bother getting mad at causes and forces far bigger than us?
Why do we take these things personally?
After all,
  external events are not sentient beings—they cannot respond to our shouts and cries—and neither can the mostly indifferent gods.
That's what Marcus was reminding himself of here:
  circumstances are incapable of considering or caring for your feelings,
  your anxiety,
  or your excitement.
They don't care about your reaction.
They are not people.
So stop acting like getting worked up is having an impact on a given situation.
Situations don't care at all.
T
#+end_verse