#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 8th DID THAT MAKE YOU FEEL BETTER
#+begin_verse
'You cry,
  I'm suffering severe pain! Are you then relieved from feeling it,
  if you bear it in an unmanly way?' —SENECA,
  MORAL LETTERS,
  78.
17 he next time someone gets upset near you—crying,
  yelling,
  breaking something,
  being pointed or cruel—watch how quickly this statement will stop them cold:
  'I hope this is making you feel better.' Because,
  of course,
  it isn't.
Only in the bubble of extreme emotion can we justify any of that kind of behavior—and when called to account for it,
  we usually feel sheepish or embarrassed.
It's worth applying that standard to yourself.
The next time you find yourself in the middle of a freakout,
  or moaning and groaning with flulike symptoms,
  or crying tears of regret,
  just ask:
  Is this actually making me feel better?
Is this actually relieving any of the symptoms I wish were gone?
H
#+end_verse