#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 11th HERO OR NERO
#+begin_verse
'Our soul is sometimes a king,
  and sometimes a tyrant. A king,
  by attending to what is honorable,
  protects the good health of the body in its care,
  and gives it no base or sordid command. But an uncontrolled,
  desire-fueled,
  over-indulged soul is turned from a king into that most feared and detested thing—a tyrant.' —SENECA,
  MORAL LETTERS,
  114.
24 here is that saying that absolute power corrupts absolutely.
At first glance,
  that's true.
Seneca's pupil Nero and his litany of crimes and murders is a perfect example.
Another emperor,
  Domitian,
  arbitrarily banished all philosophers from Rome (Epictetus was forced to flee as a result).
Many of Rome's emperors were tyrants.
Yet,
  not many years later,
  Epictetus would become a close friend of another emperor,
  Hadrian,
  who would help Marcus Aurelius to the throne,
  one of the truest examples of a wise philosopher king.
So it's not so clear that power always corrupts.
In fact,
  it looks like it comes down,
  in many ways,
  to the inner strength and self-awareness of individuals—what they value,
  what desires they keep in check,
  whether their understanding of fairness and justice can counteract the temptations of unlimited wealth and deference.
The same is true for you.
Both personally and professionally.
Tyrant or king?
Hero or Nero?
Which will you be?
T
#+end_verse