#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 1st FOR THE HOT-HEADED MAN
#+begin_verse
'Keep this thought handy when you feel a fit of rage coming on —it isn't manly to be enraged. Rather,
  gentleness and civility are more human,
  and therefore manlier. A real man doesn't give way to anger and discontent,
  and such a person has strength,
  courage,
  and endurance—unlike the angry and complaining. The nearer a man comes to a calm mind,
  the closer he is to strength.' —MARCUS AURELIUS,
  MEDITATIONS,
  11.
18.
5b hy do athletes talk trash to each other?
Why do they deliberately say offensive and nasty things to their competitors when the refs aren't looking?
To provoke a reaction.
Distracting and angering opponents is an easy way to knock them off their game.
Try to remember that when you find yourself getting mad.
Anger is not impressive or tough—it's a mistake.
It's weakness.
Depending on what you're doing,
  it might even be a trap that someone laid for you.
Fans and opponents called boxer Joe Louis the 'Ring Robot' because he was utterly unemotional—his cold,
  calm demeanor was far more terrifying than any crazed look or emotional outburst would have been. Strength is the ability to maintain a hold of oneself. It's being the person who never gets mad,
  who cannot be rattled,
  because they are in control of their passions—rather than controlled by their passions.W
#+end_verse