#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 16th DON’T MAKE THINGS HARDER THAN THEY NEED TO BE
#+begin_verse
'If someone asks you how to write your name,
  would you bark out each letter? And if they get angry,
  would you then return the anger? Wouldn't you rather gently spell out each letter for them? So then,
  remember in life that your duties are the sum of individual acts. Pay attention to each of these as you do your duty . . . just methodically complete your task.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
26 ere's a common scenario.
You're working with a frustrating coworker or a difficult boss.
They ask you to do something and,
  because you dislike the messenger,
  you immediately object.
There's this problem or that one,
  or their request is obnoxious and rude.
So you tell them,
  'No,
  I'm not going to do it.' Then they retaliate by not doing something that you had previously asked of them.
And so the conflict escalates.
Meanwhile,
  if you could step back and see it objectively,
  you'd probably see that not everything they're asking for is unreasonable.
In fact,
  some of it is pretty easy to do or is,
  at least,
  agreeable.
And if you did it,
  it might make the rest of the tasks a bit more tolerable too.
Pretty soon,
  you've done the entire thing.
Life (and our job) is difficult enough.
Let's not make it harder by getting emotional about insignificant matters or digging in for battles we don't actually care about.
Let's not let emotion get in the way of kathêkon,
  the simple,
  appropriate actions on the path to virtue.
I
#+end_verse