#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 17th THE ENEMY OF HAPPINESS
#+begin_verse
'It is quite impossible to unite happiness with a yearning for what we don't have. Happiness has all that it wants,
  and resembling the well-fed,
  there shouldn't be hunger or thirst.' —EPICTETUS,
  DISCOURSES,
  3.
24.
17 'll be happy when I graduate,
  we tell ourselves. I'll be happy when I get this promotion,
  when this diet pays off,
  when I have the money that my parents never had. Conditional happiness is what psychologists call this kind of thinking. Like the horizon,
  you can walk for miles and miles and never reach it. You won't even get any closer. Eagerly anticipating some future event,
  passionately imagining something you desire,
  looking forward to some happy scenario—as pleasurable as these activities might seem,
  they ruin your chance at happiness here and now. Locate that yearning for more,
  better,
  someday and see it for what it is:
  the enemy of your contentment. Choose it or your happiness. As Epictetus says,
  the two are not compatible.E
#+end_verse