#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 2nd A PROPER FRAME OF MIND
#+begin_verse
'Frame your thoughts like this—you are an old person,
  you won't let yourself be enslaved by this any longer,
  no longer pulled like a puppet by every impulse,
  and you'll stop complaining about your present fortune or dreading the future.' —MARCUS AURELIUS,
  MEDITATIONS,
  2.
2 e resent the person who comes in and tries to boss us around.
Don't tell me how to dress,
  how to think,
  how to do my job,
  how to live.
This is because we are independent,
  self-sufficient people.
Or at least that's what we tell ourselves.
Yet if someone says something we disagree with,
  something inside us tells us we have to argue with them.
If there's a plate of cookies in front of us,
  we have to eat them.
If someone does something we dislike,
  we have to get mad about it.
When something bad happens,
  we have to be sad,
  depressed,
  or worried.
But if something good happens a few minutes later,
  all of a sudden we're happy,
  excited,
  and want more.
We would never let another person jerk us around the way we let our impulses do.
It's time we start seeing it that way—that we're not puppets that can be made to dance this way or that way just because we feel like it.
We should be the ones in control,
  not our emotions,
  because we are independent,
  self-sufficient people.
T
#+end_verse