#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 24th THE REAL SOURCE OF HARM
#+begin_verse
'Keep in mind that it isn't the one who has it in for you and takes a swipe that harms you,
  but rather the harm comes from your own belief about the abuse. So when someone arouses your anger,
  know that it's really your own opinion fueling it. Instead,
  make it your first response not to be carried away by such impressions,
  for with time and distance self-mastery is more easily achieved.' —EPICTETUS,
  ENCHIRIDION,
  20 he Stoics remind us that there really is no such thing as an objectively good or bad occurrence.
When a billionaire loses $1 million in market fluctuation,
  it's not the same as when you or I lose a million dollars.
Criticism from your worst enemy is received differently than negative words from a spouse.
If someone sends you an angry email but you never see it,
  did it actually happen?
In other words,
  these situations require our participation,
  context,
  and categorization in order to be 'bad.' Our reaction is what actually decides whether harm has occurred.
If we feel that we've been wronged and get angry,
  of course that's how it will seem.
If we raise our voice because we feel we're being confronted,
  naturally a confrontation will ensue.
But if we retain control of ourselves,
  we decide whether to label something good or bad.
In fact,
  if that same event happened to us at different points in our lifetime,
  we might have very different reactions.
So why not choose now to not apply these labels?
Why not choose not to react?
I
#+end_verse