#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 5th STEADY YOUR IMPULSES
#+begin_verse
'Don't be bounced around,
  but submit every impulse to the claims of justice,
  and protect your clear conviction in every appearance.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
22 hink of the manic people in your life.
Not the ones suffering from an unfortunate disorder,
  but the ones whose lives and choices are in disorder.
Everything is soaring highs or crushing lows;
  the day is either amazing or awful.
Aren't those people exhausting?
Don't you wish they just had a filter through which they could test the good impulses versus the bad ones?
There is such a filter.
Justice.
Reason.
Philosophy.
If there's a central message of Stoic thought,
  it's this:
  impulses of all kinds are going to come,
  and your work is to control them,
  like bringing a dog to heel.
Put more simply:
  think before you act.
Ask:
  Who is in control here?
What principles are guiding me?
I
#+end_verse