#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* February 21st WISH NOT, WANT NOT
#+begin_verse
'Remember that it's not only the desire for wealth and position that debases and subjugates us,
  but also the desire for peace,
  leisure,
  travel,
  and learning. It doesn't matter what the external thing is,
  the value we place on it subjugates us to another . . . where our heart is set,
  there our impediment lies.' —EPICTETUS,
  DISCOURSES,
  4.
4.
1–2;
  15 urely,
  Epictetus isn't saying that peace,
  leisure,
  travel,
  and learning are bad,
  is he?
Thankfully,
  no.
But ceaseless,
  ardent desire—if not bad in and of itself—is fraught with potential complications.
What we desire makes us vulnerable.
Whether it's an opportunity to travel the world or to be the president or for five minutes of peace and quiet,
  when we pine for something,
  when we hope against hope,
  we set ourselves up for disappointment.
Because fate can always intervene and then we'll likely lose our self-control in response.
As Diogenes,
  the famous Cynic,
  once said,
  'It is the privilege of the gods to want nothing,
  and of godlike men to want little.' To want nothing makes one invincible—because nothing lies outside your control.
This doesn't just go for not wanting the easy-to-criticize things like wealth or fame—the kinds of folly that we see illustrated in some of our most classic plays and fables.
That green light that Gatsby strove for can represent seemingly good things too,
  like love or a noble cause.
But it can wreck someone all the same.
When it comes to your goals and the things you strive for,
  ask yourself:
  Am I in control of them or they in control of me?
I
#+end_verse