#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 21st A MORNING RITUAL
#+begin_verse
'Ask yourself the following first thing in the morning:
  What am I lacking in attaining freedom from passion? What for tranquility? What am I? A mere body,
  estate-holder,
  or reputation? None of these things. What,
  then? A rational being. What then is demanded of me? Meditate on your actions. How did I steer away from serenity? What did I do that was unfriendly,
  unsocial,
  or uncaring? What did I fail to do in all these things?' —EPICTETUS,

  
Many successful people have a morning ritual.S
For some, it's meditation.
For others, it's exercise.
For many, it's journaling
  — just a few pages where they write down their thoughts, fears, hopes.
In these cases, the point is not so much the activity itself
  as it is the ritualized reflection.
The idea is to take some time to look inward and examine.

Taking that time is what Stoics advocated more than almost anything else.
We don't know whether Marcus Aurelius wrote his Meditations in the morning or at night,
  but we know he carved out moments of quiet alone time
  —and that he wrote for himself, not for anyone else.
If you're looking for a place to start your own ritual,
  you could do worse than Marcus's example and Epictetus's checklist.
  
Every day, starting today, ask yourself these same tough questions.
Let philosophy and hard work guide you to better answers,
  one morning at a time, over the course of a life.
#+end_verse
