#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 9th WHAT WE CONTROL AND WHAT WE DON’T
#+begin_verse
'Some things are in our control,
  while others are not.
We control our opinion, choice, desire, aversion, and, in a word,
  everything of our own doing.
We don't control our body, property, reputation, position, and, in a word,
  everything not of our own doing.
Even more, the things in our control are by nature free, unhindered, and unobstructed,
  while those not in our control are weak, slavish, can be hindered,
  and are not our own.' —EPICTETUS,

  
Today, you won't control the external events that happen.
Is that scary?
A little, but it's balanced
  when we see that we can control our opinion about those events.
You decide whether they're good or bad, whether they're fair or unfair.
You don't control the situation, but you control what you think about it.
See how that works?
Every single thing that is outside your control
  —the outside world, other people, luck, karma,
  whatever—still presents a corresponding area that is in your control.
This alone gives us plenty to manage, plenty of power.

Best of all, an honest understanding of what is within our control
  provides real clarity about the world:
  all we have is our own mind.
Remember that today when you try to extend your reach outward
  —that it's much better and more appropriately directed inward.
#+end_verse
