#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 11th IF YOU WANT TO BE UNSTEADY
#+begin_verse
'For if a person shifts their caution to their own reasoned choices and the acts of those choices,
  they will at the same time gain the will to avoid,
  but if they shift their caution away from their own reasoned choices to things not under their control,
  seeking to avoid what is controlled by others,
  they will then be agitated,
  fearful,
  and unstable.' —EPICTETUS,
  
The image of the Zen philosopher is the monk up in the green, quiet hills,
  or in a beautiful temple on some rocky cliff.
The Stoics are the antithesis of this idea.
Instead, they are the man in the marketplace,
  the senator in the Forum,
  the brave wife waiting for her soldier to return from battle,
  the sculptor busy in her studio.
Still, the Stoic is equally at peace.
Epictetus is reminding you
  that serenity and stability are results of your choices and judgment,
    not your environment.
If you seek to avoid all disruptions to tranquility—other people, external events, stress
  —you will never be successful.
Your problems will follow you wherever you run and hide.
But if you seek to avoid the harmful and disruptive judgments
    that cause those problems,
  then you will be stable and steady wherever you happen to be.
#+end_verse
