#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 6th WHERE, WHO, WHAT, AND WHY
#+begin_verse
'A person who doesn't know what the universe is,
  doesn't know where they are.
  A person who doesn't know their purpose in life doesn't know who they are or what the universe is.
  A person who doesn't know any one of these things doesn't know why they are here.
  So what to make of people who seek or avoid the praise of those who have no knowledge of where or who they are?' —MARCUS AURELIUS,
  
The late comedian Mitch Hedberg had a funny story he told in his act.
Sitting down for an on-air interview, a radio DJ asked him,
  'So, who are you?'
In that moment, he had to think,
Is this guy really deep or did I drive to the wrong station?

How often are we asked a simple question like
  'Who are you?' or 'What do you do?' or 'Where are you from?'
Considering it a superficial question—if we even consider it at all
  —we don't bother with more than a superficial answer.
  
But, gun to their head,
  most people couldn't give much in the way of a substantive answer.
Could you?
Have you taken the time to get clarity about who you are and what you stand for?
Or are you too busy chasing unimportant things,
  mimicking the wrong influences,
    and following disappointing or unfulling or nonexistent paths?
#+end_verse
