#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 24th PUSH FOR DEEP UNDERSTANDING
#+begin_verse
'From Rusticus . . . I learned to read carefully and not be satisfied with a rough understanding of the whole,
  and not to agree too quickly with those who have a lot to say about something.' —MARCUS AURELIUS,
  
  
The first book of Marcus Aurelius's Meditations begins with a catalog of gratitude.
He thanks, one by one, the leading influences in his life.
One of the people he thanks is Quintus Junius Rusticus,
  a teacher who developed in his student a love of deep clarity and understanding
  —a desire to not just stop at the surface when it comes to learning.
It was also from Rusticus that Marcus was introduced to Epictetus.
In fact, Rusticus loaned Marcus his personal copy of Epictetus's lectures.
Marcus clearly wasn't satisfied with just getting the gist of these lectures
  and didn't simply accept them on his teacher's recommendation.
Paul Johnson once joked that Edmund Wilson read books
  'as though the author was on trial for his life.'
That's how Marcus read Epictetus—and when the lessons passed muster,
  he absorbed them.
They became part of his DNA as a human being.
He quoted them at length over the course of his life,
  finding real clarity and strength in words,
  even amid the immense luxury and power he would come to possess.
  
That's the kind of deep reading and study we need to cultivate as well,
  which is why we're reading just one page a day instead of a chapter at a time.
So we can take the time to read attentively and deeply.
#+end_verse
