#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 22nd THE DAY IN REVIEW
#+begin_verse
'I will keep constant watch over myself and—most usefully— will put each day up for review. For this is what makes us evil —that none of us looks back upon our own lives. We reflect upon only that which we are about to do. And yet our plans for the future descend from the past.' —SENECA,


In a letter to his older brother Novatus,
  Seneca describes a beneficial exercise he borrowed from another prominent philosopher.
At the end of each day he would ask himself variations of the following questions:
  What bad habit did I curb today?
  How am I better? Were my actions just? How can I improve?
At the beginning or end of each day,
  the Stoic sits down with his journal and reviews:
  what he did, what he thought, what could be improved.
It's for this reason that Marcus Aurelius's Meditations is a somewhat inscrutable book
  —it was for personal clarity and not public benefit.
Writing down Stoic exercises was and is also a form of practicing them,
  just as repeating a prayer or hymn might be.
  
Keep your own journal,
  whether it's saved on a computer or in a little notebook.
Take time to consciously recall the events of the previous day.
Be unflinching in your assessments.
Notice what contributed to your happiness and what detracted from it.
Write down what you'd like to work on or quotes that you like.
By making the effort to record such thoughts,
  you're less likely to forget them.
An added bonus: you'll have a running tally to track your progress too.
#+end_verse
