#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 8th SEEING OUR ADDICTIONS
#+begin_verse
'We must give up many things to which we are addicted,
  considering them to be good. Otherwise,
  courage will vanish,
  which should continually test itself. Greatness of soul will be lost,
  which can't stand out unless it disdains as petty what the mob regards as most desirable. —SENECA,
  
  
What we consider to be harmless indulgences can easily become full-blown addictions.
We start with coffee in the morning,
  and soon enough we can't start the day without it.
We check our email because it's part of our job,
  and soon enough we feel the phantom buzz of the phone in our pocket every few seconds.
Soon enough, these harmless habits are running our lives.

The little compulsions and drives we have
  not only chip away at our freedom and sovereignty, they cloud our clarity.
We think we're in control—but are we really?
As one addict put it,
  addiction is when we've 'lost the freedom to abstain.'
Let us reclaim that freedom.

What that addiction is for you can vary:
  Soda? Drugs? Complaining? Gossip? The Internet? Biting your nails?
But you must reclaim the ability to abstain
  because within it is your clarity and self-control.
#+end_verse
