#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* January 4th THE BIG THREE
#+begin_verse
'All you need are these:
  certainty of judgment in the present moment;
  action for the common good in the present moment;
  and an attitude of gratitude in the present moment for anything that comes your way.' —MARCUS AURELIUS,

  
Perception, Action, Will.
Those are the three overlapping but critical disciplines of Stoicism
  (as well as the organization of this book and yearlong journey you've just begun).
There's more to the philosophy certainly
  —and we could spend all day talking about the unique beliefs of the various Stoics:
  'This is what Heraclitus thought ...'
  'Zeno is from Citium, a city in Cyprus, and he believed ...'
But would such facts really help you day to day?
What clarity does trivia provide?

Instead, the following little reminder sums up
    the three most essential parts of Stoic philosophy
  worth carrying with you every day, into every decision:
  
  Control your perceptions.
  Direct your actions properly.
  Willingly accept what's outside your control.
  
That's all we need to do.
#+end_verse
