#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 6th DON’T TELL YOURSELF STORIES
#+begin_verse
'In public avoid talking often and excessively about your accomplishments and dangers,
  for however much you enjoy recounting your dangers,
  it's not so pleasant for others to hear about your affairs.' —EPICTETUS,
  ENCHIRIDION,
  33.
14 odern philosopher Nassim Taleb has warned of the 'narrative fallacy'—the tendency to assemble unrelated events of the past into stories. These stories,
  however gratifying to create,
  are inherently misleading. They lead to a sense of cohesion and certainty that isn't real. If that's too heady,
  remember that as Epictetus points out,
  there is another reason not to tell stories about your past. It's boring,
  annoying,
  and self-absorbed. It might make you feel good to dominate the conversation and make it all about you,
  but how do you think it is for everyone else? Do you think people are really enjoying the highlights of your high school football days? Is this really the time for another exaggerated tale of your sexual prowess? Try your best not to create this fantasy bubble—live in what's real. Listen and connect with people,
  don't perform for them.S
#+end_verse