#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 1st WHERE PHILOSOPHY BEGINS
#+begin_verse
'An important place to begin in philosophy is this:
  a clear perception of one's own ruling principle.' —EPICTETUS,
  DISCOURSES,
  1.
26.
15 hilosophy is intimidating.
Where does one start?
With books?
With lectures?
With the sale of your worldly possessions?
None of these things.
Epictetus is saying that one becomes a philosopher when they begin to exercise their guiding reason and start to question the emotions and beliefs and even language that others take for granted.
It is thought that an animal has self-awareness when it is able to fully recognize itself in a mirror.
Perhaps we could say that we begin our journey into philosophy when we become aware of the ability to analyze our own minds.
Can you start with that step today?
When you do,
  you'll find that from it we really come alive,
  that we live lives—to paraphrase Socrates —that are actually worth living.
M
#+end_verse