#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 31st YOU’RE A PRODUCT OF YOUR TRAINING
#+begin_verse
'Chasing what can't be done is madness. But the base person is unable to do anything else.' —MARCUS AURELIUS,
  MEDITATIONS,
  5.
17 dog that's allowed to chase cars will chase cars.
A child who is never given any boundaries will become spoiled.
An investor without discipline is not an investor—he's a gambler.
A mind that isn't in control of itself,
  that doesn't understand its power to regulate itself,
  will be jerked around by external events and unquestioned impulses.
That can't be how you'd like tomorrow to go.
So you must be aware of that.
You must put in place training and habits now to replace ignorance and ill discipline.
Only then will you begin to behave and act differently.
Only then will you stop seeking the impossible,
  the shortsighted,
  and the unnecessary.
APRIL UNBIASED THOUGHTI
#+end_verse