#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 20th READY AND AT HOME
#+begin_verse
'I may wish to be free from torture,
  but if the time comes for me to endure it,
  I'll wish to bear it courageously with bravery and honor. Wouldn't I prefer not to fall into war? But if war does befall me,
  I'll wish to carry nobly the wounds,
  starvation,
  and other necessities of war. Neither am I so crazy as to desire illness,
  but if I must suffer illness,
  I'll wish to do nothing rash or dishonorable. The point is not to wish for these adversities,
  but for the virtue that makes adversities bearable.' —SENECA,
  MORAL LETTERS,
  67.
4 resident James Garfield was a great man—raised in humble circumstances,
  self-educated,
  and eventually a Civil War hero— whose presidency was cut short by an assassin's bullet.
In his brief time in office,
  he faced a bitterly divided country as well as a bitterly and internally divided Republican Party.
During one fight,
  which challenged the very authority of his office,
  he stood firm,
  telling an adviser:
  'Of course I deprecate war,
  but if it is brought to my door the bringer will find me at home.' That's what Seneca is saying here.
We'd be crazy to want to face difficulty in life.
But we'd be equally crazy to pretend that it isn't going to happen.
Which is why when it knocks on our door—as it very well may this morning—let's make sure we're prepared to answer.
Not the way we are when a surprise visitor comes late at night,
  but the way we are when we're waiting for an important guest:
  dressed,
  in the right head space,
  ready to go.
D
#+end_verse