#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 13th ONE DAY IT WILL ALL MAKE SENSE
#+begin_verse
'Whenever you find yourself blaming providence,
  turn it around in your mind and you will see that what has happened is in keeping with reason.' —EPICTETUS,
  DISCOURSES,
  3.
17.
1 art of the reason we fight against the things that happen is that we're so focused on our plan that we forget that there might be a bigger plan we don't know about.
Is it not the case that plenty of times something we thought was a disaster turned out to be,
  with the passage of time,
  a lucky break?
We also forget that we're not the only people who matter and that our loss might be someone else's gain.
This sense of being wronged is a simple awareness problem.
We need to remember that all things are guided by reason—but that it is a vast and universal reason that we cannot always see.
That the surprise hurricane was the result of a butterfly flapping its wings a hemisphere away or that misfortune we have experienced is simply the prelude to a pleasant and enviable future.
S
#+end_verse