#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 29th WHY DO YOU NEED TO IMPRESS THESE PEOPLE AGAIN
#+begin_verse
'If you should ever turn your will to things outside your control in order to impress someone,
  be sure that you have wrecked your whole purpose in life. Be content,
  then,
  to be a philosopher in all that you do,
  and if you wish also to be seen as one,
  show yourself first that you are and you will succeed.' —EPICTETUS,
  ENCHIRIDION,
  23 s there anything sadder than the immense lengths we'll go to impress someone?
The things we'll do to earn someone's approval can seem,
  when examined in retrospect,
  like the result of some temporary form of insanity.
Suddenly we're wearing uncomfortable,
  ridiculous clothes we've been told are cool,
  eating differently,
  talking differently,
  eagerly waiting for a call or text.
If we did these things because we liked it,
  that would be one thing.
But that's not what it is.
It's just a means to an end— to get someone to give us the nod.
The irony,
  as Marcus Aurelius points out repeatedly,
  is that the people whose opinion we covet are not all that great.
They're flawed— they're distracted and wowed by all sorts of silly things themselves.
We know this and yet we don't want to think about it.
To quote Fight Club again,
  'We buy things we don't need,
  to impress people we don't like.' Doesn't that sound pretty ridiculous?
But more than that,
  isn't it about as far as possible as you can get from the serenity and security that philosophy can provide?
I
#+end_verse