#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 21st THE BEST RETREAT IS IN HERE, NOT OUT THERE
#+begin_verse
'People seek retreats for themselves in the country,
  by the sea,
  or in the mountains. You are very much in the habit of yearning for those same things. But this is entirely the trait of a base person,
  when you can,
  at any moment,
  find such a retreat in yourself. For nowhere can you find a more peaceful and less busy retreat than in your own soul—especially if on close inspection it is filled with ease,
  which I say is nothing more than being well-ordered. Treat yourself often to this retreat and be renewed.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
3.
1 o you have a vacation coming up?
Are you looking forward to the weekend so you can have some peace and quiet?
Maybe,
  you think,
  after things settle down or after I get this over with.
But how often has that ever actually worked?
The Zen meditation teacher Jon Kabat-Zinn coined a famous expression:
  'Wherever you go,
  there you are.' We can find a retreat at any time by looking inward.
We can sit with our eyes closed and feel our breath go in and out.
We can turn on some music and tune out the world.
We can turn off technology or shut off those rampant thoughts in our head.
That will provide us peace.
Nothing else.
A
#+end_verse