#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 17th THE BEAUTY OF CHOICE
#+begin_verse
'You are not your body and hair-style,
  but your capacity for choosing well. If your choices are beautiful,
  so too will you be.' —EPICTETUS,
  DISCOURSES,
  3.
1.
39b–40a t's that line in the movie Fight Club:
  'You are not your job,
  you're not how much money you have in the bank. You are not the car you drive. You're not the contents of your wallet.' Obviously our friend Epictetus never saw that movie or read the book—but apparently the consumerism of the 1990s existed in ancient Rome too.
It's easy to confuse the image we present to the world for who we actually are,
  especially when media messaging deliberately blurs that distinction.
You might look beautiful today,
  but if that was the result of vain obsession in the mirror this morning,
  the Stoics would ask,
  are you actually beautiful?
A body built from hard work is admirable.
A body built to impress gym rats is not.
That's what the Stoics urge us to consider.
Not how things appear,
  but what effort,
  activity,
  and choices they are a result of.
O
#+end_verse