#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 18th IMPOSSIBLE WITHOUT YOUR CONSENT
#+begin_verse
'Today I escaped from the crush of circumstances,
  or better put,
  I threw them out,
  for the crush wasn't from outside me but in my own assumptions.' —MARCUS AURELIUS,
  MEDITATIONS,
  9.
13 n tough days we might say,
  'My work is overwhelming,
  ' or 'My boss is really frustrating.' If only we could understand that this is impossible.
Someone can't frustrate you,
  work can't overwhelm you— these are external objects,
  and they have no access to your mind.
Those emotions you feel,
  as real as they are,
  come from the inside,
  not the outside.
The Stoics use the word hypolêpsis,
  which means 'taking up'—of perceptions,
  thoughts,
  and judgments by our mind. What we assume,
  what we willingly generate in our mind,
  that's on us. We can't blame other people for making us feel stressed or frustrated any more than we can blame them for our jealousy. The cause is within us. They're just the target.I
#+end_verse