#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 19th TIMELESS WISDOM
#+begin_verse
'For there are two rules to keep at the ready—that there is nothing good or bad outside my own reasoned choice,
  and that we shouldn't try to lead events but to follow them.' —EPICTETUS,
  DISCOURSES,
  3.
10.
18 n the mid-twentieth century,
  there was an Indian Jesuit priest named Anthony de Mello.
Born in Bombay when it was still under British control,
  de Mello was an amalgam of many different cultures and perspectives:
  East,
  West;
  he even trained as a psychotherapist.
It's interesting when one sees timeless wisdom develop across schools,
  across epochs and ideas.
Here is a quote from de Mello's book,
  The Way to Love,
  that sounds almost exactly like Epictetus:
  'The cause of my irritation is not in this person but in me.' Remember,
  each individual has a choice.
You are always the one in control.
The cause of irritation—or our notion that something is bad— that comes from us,
  from our labels or our expectations.
Just as easily,
  we can change those labels;
  we can change our entitlement and decide to accept and love what's happening around us.
And this wisdom has been repeated and independently discovered in every century and every country since time began.
P
#+end_verse