#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 2nd ACCURATE SELF-ASSESSMENT
#+begin_verse
'Above all,
  it is necessary for a person to have a true selfestimate,
  for we commonly think we can do more than we really can.' —SENECA,
  ON TRANQUILITY OF MIND,
  5.
2 ost people resist the idea of a true self-estimate,
  probably because they fear it might mean downgrading some of their beliefs about who they are and what they're capable of.
As Goethe's maxim goes,
  it is a great failing 'to see yourself as more than you are.' How could you really be considered self-aware if you refuse to consider your weaknesses?
Don't fear self-assessment because you're worried you might have to admit some things about yourself.
The second half of Goethe's maxim is important too.
He states that it is equally damaging to 'value yourself at less than your true worth.' Is it not equally common to be surprised at how well we're able to handle a previously feared scenario?
The way that we're able to put aside the grief for a loved one and care for others —though we always thought we'd be wrecked if something were to happen to our parents or a sibling.
The way we're able to rise to the occasion in a stressful situation or a life-changing opportunity.
We underestimate our capabilities just as much and just as dangerously as we overestimate other abilities.
Cultivate the ability to judge yourself accurately and honestly.
Look inward to discern what you're capable of and what it will take to unlock that potential.
W
#+end_verse