#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 8th DON’T UNINTENTIONALLY HAND OVER YOUR FREEDOM
#+begin_verse
'If a person gave away your body to some passerby,
  you'd be furious. Yet you hand over your mind to anyone who comes along,
  so they may abuse you,
  leaving it disturbed and troubled —have you no shame in that?' —EPICTETUS,
  ENCHIRIDION,
  28 nstinctively,
  we protect our physical selves.
We don't let people touch us,
  push us around,
  control where we go.
But when it comes to the mind,
  we're less disciplined.
We hand it over willingly to social media,
  to television,
  to what other people are doing,
  thinking,
  or saying.
We sit down to work and the next thing you know,
  we're browsing the Internet.
We sit down with our families,
  but within minutes we have our phones out.
We sit down peacefully in a park,
  but instead of looking inward,
  we're judging people as they pass by.
We don't even know that we're doing this.
We don't realize how much waste is in it,
  how inefficient and distracted it makes us.
And what's worse—no one is making this happen.
It's totally self-inflicted.
To the Stoics,
  this is an abomination.
They know that the world can control our bodies—we can be thrown in jail or be tossed about by the weather.
But the mind?
That's ours.
We must protect it.
Maintain control over your mind and perceptions,
  they'd say.
It's your most prized possession.
J
#+end_verse