#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 26th WHAT RULES YOUR RULING REASON
#+begin_verse
'How does your ruling reason manage itself? For in that is the key to everything. Whatever else remains,
  be it in the power of your choice or not,
  is but a corpse and smoke.' —MARCUS AURELIUS,
  MEDITATIONS,
  12.
33 he Roman satirist Juvenal is famous for this question:
  Quis custodiet ipsos custodes?
(Who watches the watchmen?
) In a way,
  this is what Marcus is asking himself—and what you might ask yourself throughout the day.
What influences the ruling reason that guides your life?
This means an exploration of subjects like evolutionary biology,
  psychology,
  neurology,
  and even the subconscious.
Because these deeper forces shape even the most disciplined,
  rational minds.
You can be the most patient person in the world,
  but if science shows we make poor decisions on an empty stomach—what good is all that patience?
So don't stop at Stoicism,
  but explore the forces that drive and make Stoicism possible.
Learn what underpins this philosophy you're studying,
  how the body and mind tick.
Understand not only your ruling reason—the watchmen—but whoever and whatever rules that too.
Y
#+end_verse