#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 7th DON’T TRUST THE SENSES
#+begin_verse
'Heraclitus called self-deception an awful disease and eyesight a lying sense.' —DIOGENES LAERTIUS,
  LIVES OF THE EMINENT PHILOSOPHERS,
  9.
7 elf-awareness is the ability to objectively evaluate the self.
It's the ability to question our own instincts,
  patterns,
  and assumptions.
Oiêsis,
  self-deception or arrogant and unchallenged opinion,
  requires that we hold all our opinions up to hard scrutiny;
  even our eyes deceive us.
On the one hand,
  that's alarming.
I can't even trust my own senses?
!
Sure,
  you could think about it that way.
Or you could take it another way:
  because our senses are often wrong,
  our emotions overly alarmed,
  our projections overly optimistic,
  we're better off not rushing into conclusions about anything.
We can take a beat with everything we do and become aware of everything that's going on so we can make the right decision.
I
#+end_verse