#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 3rd (DIS)INTEGRATION
#+begin_verse
'These things don't go together. You must be a unified human being,
  either good or bad. You must diligently work either on your own reasoning or on things out of your control—take great care with the inside and not what's outside,
  which is to say,
  stand with the philosopher,
  or else with the mob!' —EPICTETUS,
  DISCOURSES,
  3.
15.
13 e're all complicated people.
We have multiple sides to ourselves —conflicting wants,
  desires,
  and fears.
The outside world is no less confusing and contradictory.
If we're not careful,
  all these forces— pushing and pulling—will eventually tear us apart.
We can't live as both Jekyll and Hyde.
Not for long,
  anyway.
We have a choice:
  to stand with the philosopher and focus strenuously on the inside,
  or to behave like a leader of a mob,
  becoming whatever the crowd needs at a given moment.
If we do not focus on our internal integration—on self-awareness— we risk external disintegration.
I
#+end_verse