#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 5th CUTTING BACK ON THE COSTLY
#+begin_verse
'So,
  concerning the things we pursue,
  and for which we vigorously exert ourselves,
  we owe this consideration—either there is nothing useful in them,
  or most aren't useful. Some of them are superfluous,
  while others aren't worth that much. But we don't discern this and see them as free,
  when they cost us dearly.' —SENECA,
  MORAL LETTERS,
  42.
6 f Seneca's many letters,
  this is probably one of the most important —and one of the least understood.
He's making a point that goes unheard in a society of ever-bigger houses and ever more possessions:
  that there's a hidden cost to all that accumulating.
And the sooner we're aware of it,
  the better.
Remember:
  even what we get for free has a cost,
  if only in what we pay to store it—in our garages and in our minds.
As you walk past your possessions today,
  ask yourself:
  Do I need this?
Is it superfluous?
What's this actually worth?
What is it costing me?
You might be surprised by the answers and how much we've been paying without even knowing it.
M
#+end_verse