#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 16th THAT SACRED PART OF YOU
#+begin_verse
'Hold sacred your capacity for understanding. For in it is all,
  that our ruling principle won't allow anything to enter that is either inconsistent with nature or with the constitution of a logical creature. It's what demands due diligence,
  care for others,
  and obedience to God.' —MARCUS AURELIUS,
  MEDITATIONS,
  3.
9 he fact that you can think,
  the fact that you can read this book,
  the fact that you are able to reason in and out of situations—all of this is what gives you the ability to improve your circumstances and become better.
It's important to appreciate this ability,
  because it's a genuine ability.
Not everyone is so lucky.
Seriously—what you take for granted,
  others wouldn't even think to dream of.
Take a little time today to remember that you're blessed with the capacity to use logic and reason to navigate situations and circumstances.
This gives you unthinkable power to alter your circumstances and the circumstances of others.
And remember that with power comes responsibility.
I
#+end_verse