#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* March 28th COWARDICE AS A DESIGN PROBLEM
#+begin_verse
'Life without a design is erratic. As soon as one is in place,
  principles become necessary. I think you'll concede that nothing is more shameful than uncertain and wavering conduct,
  and beating a cowardly retreat. This will happen in all our affairs unless we remove the faults that seize and detain our spirits,
  preventing them from pushing forward and making an all-out effort.' —SENECA,
  MORAL LETTERS,
  95.
46 he opposing team comes out strong,
  establishes an early lead,
  and you never had time to recover.
You walk into a business meeting,
  are caught off guard,
  and the whole thing goes poorly.
A delicate conversation escalates into a shouting match.
You switched majors halfway through college and had to start your coursework over and graduate late.
Sound familiar?
It's the chaos that ensues from not having a plan.
Not because plans are perfect,
  but because people without plans—like a line of infantrymen without a strong leader—are much more likely to get overwhelmed and fall apart.
The Super Bowl–winning coach Bill Walsh used to avoid this risk by scripting the beginning of his games.
'If you want to sleep at night before the game,
  ' he said in a lecture on game planning,
  'have your first 25 plays established in your own mind the night before that. You can walk into the stadium and you can start the game without that stress factor.' You'll also be able to ignore a couple of early points or a surprise from your opponent.
It's irrelevant to you—you already have your marching orders.
Don't try to make it up on the fly.
Have a plan.
I
#+end_verse