#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 谓语结构(时态主动&时态被动&情态动词主动&情态动词被动&情态动词表推测&本该)
** 时态主动
*** 一般现在时
N2-2,C2-1,2,3,4
am/is/are + doing: 1.动作正在发生;2.表计划(+未来时间)
do/does: 习惯动作/客观事实
am/is/are + doing VS do/does

*** 现在进行时
N2-2,C2-1,2,3,4
am/is/are + doing: 1.动作正在发生;2.表计划(+未来时间)
do/does: 习惯动作/客观事实
am/is/are + doing VS do/does

*** 一般过去时
N2-3,C2-5
was/were/did: 过去的状态(was/were)/动作发生在过去(did)

*** 过去进行时
N2-7,C2-6
was/were + doing

*** 现在完成时
N2-4,C2-7,8
have done: 1.过去事情对现在有影响; 2.从过去持续到现在
N2-5,C2-13,14
have done VS did
	- did: 过去的状态或动作
	- have done: 1.过去的v.对于现在的影响; 2.过去动作或状态持续(重复)到现在

*** 现在完成进行时
N2-52,C2-9,10
have been doing(不知持续与否): 1.过去进行的v.对现在有影响;2.从过去持续(重复!)到现在

*** 过去完成时
N2-14,C2-15
had + done: 1.过去的过去;2.过去A发生,对于过去B产生影响(A在B前);3.动作从过去A持续(重复)到过去B

N2-38,
一前就后
had hardly done ... when ...
had no sooner done ... than ...

*** 过去完成进行时
N2-62,C2-16
had been doing: 1.过去A进行的v.对过去B有影响;2.过去A进行的v.持续(重复)到过去B

*** 一般将来时
N2-12,C2-21,22
will do: 将/会(当机立断决定,而非计划)
shall do: 将/会(当机立断决定,而非计划) 

*** be going to(be due to) VS will do VS intend to do
N2-36,C2-19,20,23
表述将来: 计划
be going to do(be due to)
will
intend to do

*** 将来进行时
N2-13,C2-24
will be doing: 1.未来动作正在进行;2.计划

*** 将来完成时
N2-37,C2-24
will have done: 1.动作持续(重复)到将来;2.动作截至到未来时间点前完成
have done VS had done VS will have done

*** 将来完成进行时
N2-61,
will be doing
will have done
will have been doing: 动作持续(重复)到将来 ?

** 时态被动
N2-10,C2-42
am/is/are+done
was/were+done
N2-10,C2-43,44
am/is/are+being+done
have/has+been+done
N2-34,C2-43
had been + done
N2-69,
having been done

*** have sth. done
N2-66,C2-46
have something done: 1.使得某事被别人做;2.不幸的遭遇

** 情态动词主动
*** should & can must have to
N2-17,C2-26,28,31,37
must: 肯必须(主观);否禁止
have to: 肯必须(客观):否不必
've/have got to: 表必须

N2-65,C2-27,33,34
should/ought to do: 肯应该,否不应该


*** would do & would have done
N2-55,C2-36
常常和if连用表虚拟语气
would do 表假设; 过去经常进行的行为, VS used to
would have done 表过去的假设

*** can/could VS be able to VS managed to do
N2-43,67,C2-26!
- be able to: 有能力; 做成某事的案例
	+ can: 有能力(be able to的一般时);可能发生 
	+ could: 有能力(be able to的过去式);可能发生;被允许
	+ was able to:有能力(be able to的过去式); 做成某事的案例
	+ managed to do: 做成某事的案例
	+ 对比以上时态更多

** 情态动词被动
N2-21,
will/would be done
can/could be done
must be done
have to be done
must have been one

N2-45,
be done

** 情态动词表推测
*** must和can't(现在+过去) 肯否-推测
N2-17,C2-26,28,31,37
肯否猜测:
	- 现在猜测
		must: 一定是
		can't: 一定不是
	- 过去猜测
		must have done: 当时一定是
		can't have done: 当时一定不是

*** may和may not & can和could (现在+过去) 可能-推测
N2-19,C2-29,30
也许 现在-猜测: 
may/might (not)
can/could (没有not)

也许 过去-猜测: 
may/might (not) have done
can/could(没有not) have done: 过去有可能发生;可能发生,实际没有

** needn't have done & should/ought to have done & could have done
N2-41,C2-32
needn't have done: 本不必如此,却做了,有后悔效果
needn't do that: needn't当情态动词
need doing sth. = need to be done

N2-65,C2-27,33,34
should have done/ought to have done: 本该做某事,却没有做,指责效果

can/could(没有not) have done: 过去有可能发生;可能发生,实际没有

* 非谓语 (to do & doing & done 定语状语)
** 分词作状语
NCE-49,69,C2-68
分词作状语 没找到部分被动
1. (not) doing
	 主动进行/主动一般
	 (being) (not) + adj.
2. done
	 被动完成/被动一般/主动完成(少)
3. having done
	 主动完成(发生在主句之前)
	 having been + adj. (主句之前的状态)
4. having been done 在N2-69课
	 主动完成被动(发生在主句之前)

** doing & done做前置定语 & 后置定语 短语 + prep./done/doing
N2-29,C2-97
done做定语: 表被动一般/被动完成/主动完成(少)
	- done + n.
	- n. + done短语

N2-30,C2-97
doing现在分词做定语: 主动进行/主动一般
	- the sinking ship=the ship that is sinking
	- the rising sun=the sun that is rising
	- the sleeping child=the child who is sleeping

** to do & 动名词 v.+ing
N2-59,C2-64
⽬的状语从句
to

N2-20
动名词
构成: v.+ing
动词变成名词
I like fishing. 动名词
She is fishing. 现在分词

* 特殊结构(needn't have done + should have done etc.)
** see sb. do/doing sth.
N2-35,C2-67
see sb. do sth VS see sb. doing sth.

** used to do VS would do
C2-18
used to do sth.: 过去常常,但现在不做

C2-36
would do VS used to do
	- 过去状态只用used to do
	- used to do包含现在不发生了
	- used to do讨论过去习惯行为(不重要)
where & whose 引导的定语从句

** sb. be said to to/It is said that sb.
N2-58,C2-45
be said to do...: 据说
It is said that...: 据说

* 条件句+虚拟语气
N2-16,C2-38
if从句
	- 主将从现
	- 主情从现
	- 主祈从现

N2-40,C2-39
虚拟语气(现在): 与现在事实相反
	If + did/were, 主+would/should/could/might do

N2-64,C2-40
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
C2-41
suggest that ... (should) do ...
wish型虚拟语气: 从句: should(可省略) do

* 特殊句型(强调etc,主语从句)
** 强调句
N2-58
强调句:
	- It is(was) + 强调部分 + that(who) + 剩余部分?
	- do/does/did + v.

** 感叹句
N2-2	
感叹句: 关键词需要升调 ?
	What + (形容词) + n. (+ 主语 + 谓语)

* 名词性从句
** 宾语从句
N2-15,C2-47,48
宾语从句: 句子做宾语
直接引语变间接引语: 时态倒退一个时态,现在->过去,过去->过去完成;客观事实仍成立可不退

** 同位语从句
N2-46,
- 同位语: 补充说明的名词
I have just received a letter from my brother, Tim.

- 同位语从句: 完整(引导词不充当从句成分)句子补充说明名词.
No one could account for *the fact that* one of the boxes was extremely heavy.

- 同位语从句VS定语从句: 1.从句是否完整 2.是否补充说明
Scientists have reached *the conclusion that* the temperature on Earth is getting higher and higher.
We were all happy about the news that the experiment was very successful.
I have a theory that ...
I have no doubt that he will help me.
Tell us about a time when you went beyond what was defined or established. 

** 主语/表语从句
It's a pity that...
It is/was sb's job to do sth.
It is easy for sb. to do sth.
It seems that ...
It occurred to sb. that ...
It occurred to sb. to do sth.
It is impossible for sb. to do.
It was obvious that...
It is a blessing that ...
It is said that...
It is fortunate that + 句子...
It's hard to imagine ...
It is no use pretending that + sentence
N2-58,C2-45
It is said that...

* 形容词性从句
** 限定性定语从句
N2-28,C2-92,93,94,95,96
定语从句:
	1. 确定被修饰词
	2. 确定引导词,who/whom/which/that
	3. 是否可以省略(引导词在从句是宾语可省)
N2-55
where & whose 引导的定语从句
N2-46
What的定语从句 = the thing that/the person that

** 非限定性定语从句
N2-77
非限定性定语从句: 解释,补充,说明
	- which非限:
		+ 位置: 句尾
		+ 指代被修饰词
	- as非限
		- 位置: 前中后
		- 指代整句

* 副词性从句
** 比较状语从句
*** 最高级
N8,C2-105,106,108
adj. 比较级&最高级变化规则
	1. 单音节:+er/est
		 - 元+辅音字母结尾: 需双写辅音字母 big -> bigger
	2. 双音节:
		 - 辅音+y结尾: y变成i pretty -> prettier
	3. 多音节: + more/less, most/least
	4. 不规则:good/well~bad~much~little
比较状从:
	1. 主语 + be + the + adj.est + n. + I've ever met/seen
	2. 主语 + be + the + adj.est + n. + 范围
	3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)
N32,C2-107
as ... as VS so ... as(否): 同样的

** 方式状语从句 (in)
N2-57,C2-123,124,125	
in(可省) the way (+定从)... 状从 ?
	1. The assistant who served her did not like the way she was dressed.
	2. I don’t like the way (that) you talk to me.
	3. We want to know the way (in which) you learn new words.

N2-63
as: in the way or manner that 按照...方式
	You'll do as I say and ask no questions.
like
as if
as though

** 时间状语从句
N7,C2-6,25,116
when & while & just as: 当...

N2-60,
A先B后
the moment A ... B...: 一A就B
	Everything stops the moment she walks in the room.
as soon as(主将从现): 一A就B(主从都表将来时,从句用现在时即可)
	As soon as the rain stops, we shall go out.
主将从现: 主从都表将来时,从句用现在时即可
	the moment/util/when/as soon as/while/before
** 目的状语从句 so that
N2-59,C2-64
----------接do sth.
to
in order to
so as to
---------- 接句子
so that 目的状语从句
in order that: 目的

** 结果状语从句 so/such ... that
N2-35,C2-67,102
so + adj./adv. that = such + n. that: 如此以至于
see sb. do sth VS see sb. doing sth.

** 让步状语从句 no mather + 疑问词
N2-68,C2-113
no matter how/what/where/whose/who/which/when
even though(although/though/as) VS even if

* 句子构成(6123456+连词+分词作状语)
** 语序
NCE2-1,2,C2-109,C2-110
6123456:
	 6: When
	 1: 主
	 2: 谓/系
	 3: 宾/表
	 4: how
	 5: where
	 6: when
1. 如何造一个英语句子: 123 
2. 如何造一个好的英文句子: 123456
3. 英语语序: 
	频率adv.位置: 助动词后和动词前 & 动词后
	 
** 两短句的连词
NCE-25,C1-97
1. and,but,or,so,because: 连句子
2. both... and, either...or,neither...nor ?: 连两名词
3. not only... but also (as well) ?: 连句子

* 冠词与名词
** a/an VS the
N2-6,C2-72,85
a/an VS the
some VS any

** 动名词
N2-20,C2-53
动名词

* 副词与介词
** at/on/in(时间)
N2-9,C2-121,C122
at/on/in(时间)
	- on + 具体某一天
	- in + 年/季/月
	- at + 时间点

** v. + of/from/in/on
N2-22,C2-135,136
v. + of/from/in/on

** 及物VS不及物动词
及物动词,后面必须有动作的承受者(宾语),否则意思不完整.
	eg: I hit you.(意思完整) VS I hit.(意思不完整)
不及物动词,后面没有动作的承受者,意思已经完整了.
	eg. I wait.(意思完整) VS I wait for bus.(意思完整,且为了bus更加的丰富)
更多: 不能记listen to, 而是 listen 然后 to sb.
	- listen, to sb.
	- be afraid of sth.
