#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 03 An unknown goddess
#+begin_verse
How did the archaeologists know that the statue was a goddess?

Some time ago, *an interesting discovery was made* by archaeologists on the Aegean island of Kea.
An American team explored a temple
	which stands in an ancient city *on the promontory* of Ayia Irini.
The city at one time must have been prosperous,
	for it enjoyed a high level of civilization.
Houses -- often three storeys high -- were built of stone.
They had large rooms with beautifully decorated walls.
The city *was even equipped with* a *drainage system*,
	for a great many clay pipes were found beneath the narrow streets.

The temple which the archaeologists explored *was used as a place of worship*
	from the fifteenth century B.C. until Roman times.
In the most sacred room of the temple, clay fragments of fifteen statues were found.
Each of these represented a goddess and had, at one time, been painted.
The body of one statue was found among remains dating from the fifteen century B.C.
Its missing head *happened to be* among remains of the fifth century B.C.
This head must have been found in Classical times and carefully preserved.
It was very old and precious even then.
When the archaeologists reconstructed the fragments,
	they *were amazed to find that* the goddess *turned out be* a very modern-looking woman.
She stood three feet high and her hands rested on her hips.
She was wearing a full-length skirt which swept the ground.
*Despite her great age*, she was very graceful indeed,
	but, so far, the archaeologists have been unable to discover her identity.
#+end_verse
** expression
goddess: [ˈɡɑdəs] n.女神 god
archaeologist: [ˌɑrkiˈɑlədʒɪst] n. archaeology n.考古学家
Aegean: [i:'dʒi:ən] adj.爱琴海的
explore: [ɪkˈsplɔr] v.考察,勘探 explorer n. exploration n.
promontory: [ˈprɑmənˌtɔri] n.海角
prosperous: [ˈprɑsp(ə)rəs] adj.(经济上)繁荣的,昌盛的
civilization: [ˌsɪvɪlɪˈzeɪʃ(ə)n] n.文明
storey: [ˈstɔri] n. story 楼层
drainage: [ˈdreɪnɪdʒ] n.排水
worship: [ˈwɜrˌʃɪp] n.v.崇拜(神)
sacred: [ˈseɪkrəd] adj.宗教的,神圣的
fragment: [ˈfræɡmənt] n.碎片
remains: [rɪˈmeɪnz] n.遗物,遗迹,废墟
classical: [ˈklæsɪk(ə)l] adj.(希腊和罗马)古文化的
reconstruct: [ˌrikənˈstrʌkt] v. re... 修复
rest: [rest] n.v. hip n.放置
full-length: adj.拖地长的
graceful: [ˈɡreɪsfʊl] adj.优雅的
identity: [aɪˈdentəti] n.身份

A is/was used as a place of worship: A被用于崇拜的地方
on a/the promontory: 在海角
drainage system: 下水道
sacred room/template/place: 神圣的房间
have a rest: 休息一下
identity card: 身份证
--------------------
sb. make a (adj.) discovery of sth.: 某人发现了某物
a. be equipped with b.: 配置
equip sb. with sth.: 给某人装备某物
be used as: 被用作
date from ... date back to ...:追溯
happen to do sth.: you do it by chance碰巧做某事
be amazed to find that + ...: 惊讶地发现
turn out to be sth.: 原来是某物
despite + doing sth./despite the fact that ...: 尽管

** vocabulary
explored: examined
ancient: very old
prosperous: wealthy
storeys: floors
beneath: under
fragments: pieces
remains: surviving pieces
** words
goddness  n. 女神
archaeologist [ˌɑːkiˈɒlədʒɪst] n. 考古学家
Aegean [i:'dʒi:ən] adj. 爱琴海的
explore [ɪkˈsplɔː(r)] v. 考察
promontory [ˈprɒməntri] n. 海角
prosperous [ˈprɒspərəs] adj. 繁荣
civilization [ˌsɪvəlaɪˈzeɪʃ(ə)n] n. 文明
storey [ˈstɔːri] n. 楼层
drainage [ˈdreɪnɪdʒ] n. 排水
worship [ˈwɜːʃɪp] n. 崇拜
sacred [ˈseɪkrɪd] adj. 宗教的
fragment [ˈfræɡmənt] n. 碎片
remains [rɪˈmeɪnz] n. 碎片
classical [ˈklæsɪk(ə)l] adj. 古文明的
reconstruct [ˌriːkənˈstrʌkt] v. 修复
rest [rest] v. 倚放
hip [hɪp] n. 屁股
full-length adj. 拖地长的
graceful [ˈɡreɪsf(ə)l] adj. 优雅的
identity [aɪˈdentəti] n. 身份

** DONE 单词造句
CLOSED: [2023-10-23 Mon 22:35]
un...
- unhappy
- unusual
- unlikely
- uncertain
- uncover
- unpleasant
- unsettled
- unfinished
- unclear
re...
- revisit
- replay
- recreate
- reattempt
- reconnect
- reintroduce
- reread
- replenish
- reform
- rebuild
goddess n. god
- I never dreamed of dancing with my goddess.
- I look forward to meeting a goddess.
- Is Athena the Greek goddess of wisdom and war?
- The goddess was charming at her first party.
- All young woman in our town dream of being a Hollywood goddess.
archaeologist n. archaeology n.
- I'm glad that the archaeologist is not talking about the Greek goddess any more.
- These archaeologists get used to flying off course.
- These archaeologists were equipped with the new guns.
- These archaeologists were asked to wear helmets before they went into the cave.
- I recognized him as an archaeologist who makes an interesting discovery recently.
Aegean adj.
explore v. explorer n. exploration n.
- This archaeologist often risks his life to explore these caves.
- The archaeologist is always exploring the valcanoes for one cause or another.
- These explorers claimed to have seen a puma on the promontory.
- These explorers were trapped in a gold mine.
- These explorers convinced that there were a lot of pirates.
promontory n. on a/the promontory
- It is disturbing to think that your wife always wants to visit the promontory.
- The puma left a trail of dead on the promontory.
- I spotted him making a proposal to his girl friend on the promontory.
- These archaeology is talking about the history of the palace on the promontory.
- A comedy show will be held on the promontory next night.
prosperous adj.
- Don't live in a fantasy world. It's not a prosperous city.
- I am reluctant to move to a prosperous city.
- The city is popular with young men these days, it gets prosperous.
- The country can't be prosperous.
- What a prosperous city!
civilization n.
- How did it enjoy a high level of civilization?
- As it is, Chinese civilization is not the oldest in the world.
- Chinese civilization turns out to be the oldest in the world.
- Instead of modern civilizations, the team is insteret in ancient civilizations.
- China used to enjoy a high level of civilization? Are you being sarcastic?
storey n. story
- We moved to a house which has four stories.
- I used to live on the top story.
- He claimed to live on the top story on Wall Street.
- It is said that living on the top story will have a good luck.
- The man on the top story is spying on him for two days.
drainage n. drainage system
- The worker claimed to have repaired the drainage system.
- The cat has been trapped in the drainage system for two days.
- The floods cause these little animals to repair drainage system.
- On the surface, he is an expert at repairing drainage system.
- Well, she succeed in removing the pipe from drainage system.
worship n.v. a is/was used as a place of worship
- This room used to be used as a place of worship.
- On the surface, he worships God.
- My mother often spends two hours worshiping the god once a week.
- I hate to workship any god or goddess since I was very young.
- The archaeologist pointed out that this palace was used as a place of worship.
sacred adj. sacred room/temple/place
- For one reason or another, the sacred temple has been burnt down many years ago.
- The vicar often has a rest in the sacred room.
- The sacred room was used as a place of worship.
- Why is the cow a sacred man in India?
- The most sacred room is full of candles.
fragment n.
- The vicar has managed to get enough money to have the fragments reconstructed.
- The archaeologists found fragments of statues in the courtyard.
- The archaeologist found some fragments of tones underwater.
- The archaelogist is equal to reconstruct the fragments of the goddess.
- I caught sight of fragments of body in his room.
remains n.
- We'll have to visit the remains of the temple.
- The archaeologist happened to find the remains of an ancient city.
- These archaeologists convinced that this was the remains of an ancient civilization.
- It occured to me that this must be the remains of an ancient city.
- This may be the remains of the place of worship.
classical adj.
- Why don't we listen to some classical music?
- I find my daughter studying classical art.
- I felt obliged to learn some classical music.
- She said she prefers to study classical art than modern.
- This classical music sounds good.
reconstruct v. re...
- The archaeologist failed to reconstruct the fragments of Roman vase.
- The authorities rufused to reconstruct these broken building.
- Despite the fact that the city was destoryed during the war, it has been reconstructed soon.
- The archaeologist gets used to reconstructing fragments of a statu.
- The archaeologist returned China the fragments of vase.
rest n.v. hip n. have a rest
- My wife is always resting her head on my shoulder on the bed.
- I always rests my hands on my wife's hip when I am fast sleep.
- At the edge of a forest, I spotted a man a resting his hands on another's hips.
- Although he had a rest, he is still out of breath.
- You put your hands on your hips, didn't you?
full-length adj.
- She has trouble in wearing a full-length dress at the party.
- She watched a musical wearing a full-length dress.
- She is busy wearing a full-length dress.
- Will you be wearing a full-length dress?
- Why don't you wear a full-length dress?
graceful adj.
- The woman who is dancing with my wife is graceful.
- To be honest, she is not as graceful as a swan.
- She was so graceful last night that everyone wanted to dance with her.
- She was so graceful last night that I regreted not taking part in the party.
- She was so graceful last night that she became a Hollywoord goddess.
identity n. identity card
- I regreted losing my identity card.
- Show me your identity or get out of here.
- He was disappointed to learn that the police hasn't discovered her identity.
- I proved that this was my identity card indeed.
- Will you be carrying my identity card?
** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-10-24 Tue 20:12]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-10-24 Tue 10:07]
sb. make a (adj.) discovery of sth.
- Sometimes, they can even make a discovery in their courtyard.
- I was wondering whether you have made a new discovery.
- I get accustomed to listening to them, they always make new discoveries.
- The archaeologist has made a new interesting discovery of the remains.
- They are trying to make a new discovery in the prosperous town.
a. be equipped with b.  equip sb. with sth.
- Equipped with a torch, she went on exploring the caves.
- Equipped with a helmet, she continued riding the bicycle.
- The bicycle should have been equipped with a bell.
- After equipping me with a torch, she let me go upstairs to repair the roof.
- If they weren't equipped with these machine, they would lose their heart.
be used as
- I will buy you a car used as a taxi.
- The car was expected to be used as a taxi.
- If you used the car as a taxi, you wouldn't make a spectacle of yourself.
- It is well known that even people were used as guinea pigs during the war.
- The room used to be used as a place of worship.
date from ... date back to ...
- They are trying to make a discovery of the remains dating from fifth century B.C.
- This vase can date back to Roman times.
- This vase must date from modern times. She said with a sneer.
- This vase might date from fifteenth century B.C.
- The experts now confirmed that the vase dates back to twenty century B.C.
happen to do
- She happened to be equal to this task.
- I happened to pass the exam for one reason or another.
- She happened to wake up with a start at that time.
- I happened to meet our local grocer in the station last night.
- She happened to spot a puma at large.
be amazed to find that + ...
- I am amazed to find that these people are extraordinarily similar.
- I am amazed to find that the policeman arrive on the scene at first time.
- I am amazed to find that my child is doing chores.
- I am amazed to find that these songs are still popular with these young men.
- I am amazed to find that they are competing against each other to do homework.
turn out to be ...
- This turns out to be a pyramid.
- The play turns out to be boring.
- The fish turned out to be an oarfish.
- This animal which was spotted by a woman picking blackberries turned out to be a puma.
- This fur clinging to bushes turns out to be puma fur.
despite/despite the fact that ...
- Despite the fact that your sister laugh at me.
- Despite the fact that you got into such a mess.
- Despite the fact that she is living in a fantasy world.
- Despite the fact that someone fired a shot through the window.
- Despite the fact that she set the house on fire.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-10-24 Tue 20:13]
** Ask me if 写+读
1. An interesting archaeological discovery was made in the Aegean. Where
	 Where was an interesting archaological discovery made?
2. An American team explored a temple. What
		What did an American team explore?
3. The temple stands in an ancient city. Where
		Where did the temple stand?
4. The city was equipped with a drainage system. What
		What was the city equipped with?
5. The temple was used as a place of worship. How
		How was the temple used?
6. The goddesses had been painted. What colour
	 What colour had the goddesses been painted?
7. The head of one of the statues must have been found in Classical times. When
	 When must the head of one of the statues been found?
8. It had been carefully preserved. How
	 How had it been preserved?
9. The archaeologists reconstructed the fragments. How
	 How did the archaeologists reconstruct the fragments?
10. They were amazed. Why
		Why were they amazed?
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-10-24 Tue 20:25]
Archaeologists found clay fragments in an ancient temple.
These represented the fifteen statues of goddesses which had once been painted.
The body of one statue was found among remains dating from the fifteenth century BC
	while its head was found among remains dating back to the fifth century BC.
When the fragments were reconstructed, they turned out to a goddess which stood three feet high.
Her hands rested on her hips and she was wearing a full-length skirt.
Her identity is unknown.

** DONE tell the story 口语复述
CLOSED: [2023-10-24 Tue 20:27]
** composition 阅读 或 写作
After walking round the ancient city, the archaeologists discovered an ancient temple.
This temple had obviously been a place of worship because it contained a sacred room.
On entering the sacred room, the archaeologists found the clay fragments of fifteen statues,
	each of which was a goddess which had once been painted.
After this, workmen began digging and soon discovered the head of a statue among remains
	dating from the fifth century B.C.
They also found the body of this statue among remains from the fifteenth century B.C.
The archaeologists carefully put the fragments together.
They were astonished to find that the figure was a goddess.
The goddess was a modern-looking woman.
She had her hands on her hips and she was wearing a full-length skirt.
Although the archaeologists tried very hard to identify her,
	they were unable to find out her name.

** Topics for discussion
