#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 04 The double life of Alfred Bloggs
#+begin_verse
Why did Alf want a white-collar job?

*These days*,
	people who *do manual work* often receive *far more* money than people who work in offices.
People who work in offices
	*are frequently referred to as* '*white-collar workers*' *for the simple reason*
		that they usually wear a collar and tie to go to work.
*Such is human nature,*
	that a great many people *are often willing to sacrifice higher pay*
		for the privilege of becoming white-collar workers.
This can *give rise to* curious situations,
	as it did in the case of Alfred Bloggs who worked as a dustman for the Ellesmere Corporation.

When he got married, Alf *was too embarrassed to* say anything to his wife about his job.
He simply told her that he worked for the Corporation.
Every morning, he left home *dressed in* a smart black suit.
He then *changed into* overalls and spent the next eight hours as a dustman.
Before returning home at night, he *took a shower* and changed back into his suit.
Alf did this for over two years and his fellow dustmen kept his secret.
Alf's wife has never discovered that she married a dustman and she never will,
	for Alf has just found another job.
He will soon be working in an office.
He will be earning only *half as much as* he used to,
	but he feels that his rise in status is well worth the loss of money.
*From now on*, he will wear a suit all day and others will *call him Mr. Bloggs*, not Alf.
#+end_verse
** expression
manual: [ˈmænjuəl] adj. n.体力的
collar: [ˈkɑlər] n.衣领
sacrifice: [ˈsækrɪˌfaɪs] v. n.牺牲,献出
privilege: [ˈprɪvəlɪdʒ] n.好处
dustman: [ˈdʌstmən] n.清洁工
corporation: [ˌkɔrpəˈreɪʃ(ə)n] n.公司
overalls: [ˈoʊvərˌɔl] n.工作服
shower: [ˈʃaʊər] n.淋浴
secret: [ˈsikrət] n.秘密
status: [ˈstætəs] n.地位

do manual work: 做体力工作 
white-collar/blue-collar workers: 白领/蓝领工人
make a sacrifice: to surrender or give up, or permit injury or disadvantage to, for the sake of something else做出牺牲
sacrifice a. for b.:为B牺牲A
have the privilege of doing sth.: an opportunity to do something special or enjoyable有荣幸做某事
take a shower: 洗淋浴
keep a secret: 保密
the secret of success: 成功的秘诀
It's between you and me: 这是你我之间
social status: 社会地位
status quo: 保持原样
keep the status quo: 保持原样
--------------------
These days ...: 现在
Far more adj./n.: 非常...
A be referred to as ... B: regrad A as B 把A称作为B
refer to A as B: regrad A as B=speak of A as B 把A称作为B
for the simple reason that + ...: 仅仅因为 + ...
Such is human nature, that + ...: 这是人类的本性, ...
be willing to do sth.: 愿意做某事
give rise to: lead to; cause导致
too embarrassed to do sth.: 不好意思做某事
be dressed in: wear穿着
change into + [clothes]: 换上(衣服)
half as much as ...:是..的一般(充当adj.)
from now on: 从现在起
call me/him/her A: 称...作为A

** vocabulary
receive: get
sacrifice: give up
privilege: special advantage, honor
curious: strange
embarrassed: shy
discovered: found out
status: social position
** words
manual [ˈmænjuəl] adj. 体力的
collar [ˈkɒlə(r)] n. 衣领
sacrifice [ˈsækrɪfaɪs] v. 牺牲
privilege [ˈprɪvəlɪdʒ] n. 好处
dustman [ˈdʌstmən] n. 清洁工
corporation [ˌkɔːpəˈreɪʃ(ə)n] n. 公司
overalls [ˈəʊvərɔːlz] n. 淋浴
shower [ˈʃaʊə(r)] n. 淋浴
secret [ˈsiːkrət] n. 秘密
status [ˈsteɪtəs] n. 地位

** DONE 单词造句
CLOSED: [2023-10-26 Thu 20:04]
manual adj. n.  do manual work
- The former minister does manual work after entiring.
- He was tired of doing manual work in ploughed fields.
- I needn't have a rest. Despite the fact that I have been doing manual work for the whole morning.
- After staying out of limelight, the actor begins to do manual work.
- If you don't read the manual, don't ask me for anything.
collar n. white-collar/blue-collar workers
- I happend to be a white-collar worker after I graduated from school.
- She wanted to be a white-collar worker when she went to university.
- Why are you glancing at the white-collar worker?
- The privilege of becoming a white-collar worker is suspicious.
- The woman turned out to be a blue-collar worker.
sacrifice v. n. make a sacrifice  sacrifice a. for b.
- The authorities is always asking people to make a sarcifice.
- The soldier insisted on making a sacrifice.
- I hate to sacrifice my life for anyone else.
- She decided to sacrifice herself for the success of the war.
- He has sacrificed a lot of chances for you indeed.
privilege n. have the privilege of doing sth.
- Get out of here. You didn't have the privilege of meeting the chairman.
- Despite the fact that people have the privilege of driving on highway.
- The archaeologist has the privilege of explore the temple dating back to 5th century BC.
- I am amazed to find that I have the privilege of sacrifice myself for my love.
- Equipped with a torch, now you have the privilege of entering the cave.
dustman n.
- The dustman said that the museum was used as a place of worship for ten years.
- The dustman succeeded in repairing the drainage system.
- The dustman is having a rest on a shady spot under trees.
- The dustman has already carried a basket of fruits to the house.
- In the sacred room of the temple, there is a dustman worshiping the goddess.
corporation n.
- I get used to working for such a big corporation.
- What's going on? Why don't you work for the big corporation?
- I was wondering whether I apply for the big corporation.
- I'm glad that you succeed in working for a corporation.
- She didn't work for the big corporation for one reason or another.
overalls n.
- After waking up with a start, she changed into the overalls.
- I caught sight of a woman dressed in the overalls.
- She keeps on wearing her overalls even after her work.
- I don't get enough money to wear a overalls.
- The blue-collar worker is equal to make overalls.
shower n. take a shower
- My wife is always taking a shower before she goes to bed.
- My wife is always complaining that I don't take a shower before going to bed.
- The dog has a habit of taking a shower every Saturday afternoon..
- She has a bad reputation for not taking any shower for a week.
- It is a blessing that we can take a shower every day.
secret n. keep a secret  the secret of success  It's between you and me
- You have to believe in yourself. I don't think that's the secret of success.
- I guess you can't keep any secret.
- Now, it's not just between you and me.
- She pointed out that the woman must have kept a secret.
- It's worth keeping a secret.
status n. social status  status quo  keep the status quo
- I was wondering why older people were give higher social status in Japan.
- I'm fairly certain that his rise in status is well worth the loss of money.
- My dream come ture that I have kept the status quo for ten years.
- Even though he enjoys the status quo, we must make a change.
- She is used to keeping the status quo for many years.
** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-10-26 Thu 20:04]
** DONE 复习二册语法(笔记或视频) & 红皮书
CLOSED: [2023-10-26 Thu 20:06]
- 比较级前可以用:
	 + much/a lot/far(= a lot)
	 + a bit/a little/slightly(=a little)
** DONE 习惯用法造句
CLOSED: [2023-10-26 Thu 20:06]
These days...
- These days, people is not as honest as they once were.
- These days, people is used to phoning in public.
- These days, peple worship firemen a great deal.
- These days, English becomes a universal language.
- These days, people are willing to wait in line	for a cup of coffee.
Far more adj./n.
- Their lives are not far more valuable than mine.
- The problem proved to be far more difficult than we thought of.
- You can do work far more harder than actual.
- I find it far more exciting than I imaged.
- This story is far more insteresting than that one we heard last time.
a. be referred to as ... b.  refer to a. as b.
- California used to be referred to as a Gold State.
- Why did people refer to the city as the Paris of the east.
- People who work in office are often referred to as white-collar workers.
- My wife love me to referred to her as my baby.
- She was referred to as a bicth when she went to university.
for the simple reason that + ...
- I can't go on vacation for the simple reason that I didn't get enough money.
- I was dismayed to do it for the simple reason that you should have finished it.
- I am busy doing homework for the simple reason that my teacher has taught too much today.
- I get into such a mess for the simple reason that I played football just then.
- I get tired for the simple reason that I have been running.
Such is human nature, that + ...
- Such is human nature, that I don't like to do manual work in ploughed fields.
- Such is human nature, that people are often strict with their children.
- Such is human nature, that young men and young women often like something new.
- Such is human nature, that we often write out a long list of tasks at the begining of the term.
- Such is human nature, that people make every effort to take care of their children.
be willing to do sth.
- I am willing to sacrifice my time for my wife.
- She is willing to go on a diet.
- The cat is willing to play ping-pong.
- She isn't willing to buy some drinks.
- It was obvious that she is not willing to give you any pocket money.
give rise to = lead to = cause
- This can give rise to some strange situations.
- I was not surprised to see that this gave rise to some difficult problems.
- This can give rise to the situation
	  nobody who wants to sacrifice himself for the country anymore.
- This didn't give rise to any problems at all.
- This give rise to the problem
		that a great many students played truent from school.
too embarrassed to do sth.
- The cat was too embarrased to have dinner.
- I was too embarrased to ask for any money.
- She was too embarrased to visit her brother.
- She was too embarrased to talk to him.
- She was too embarrased to shake his hands.
be dressed in
- She will have to be dressed in block stockings in next play.
- It occurred to me that she should be dressed in red socks.
- She is being dressed in the suit that I return to her yesterday.
- Dressed in black suit at night, she can't be recognized.
- Dressed in helmet, she went into the cave.
change into + [clothes]
- She should have changed into a full-length skirt.
- She needn't have changed into a full-length skirt.
- She is always changing into polo-shirts.
- After I was wet, I changed into a jacket.
- You don't need to change into a suit at the party.
half as adv.(much/hard) as ...
- You didn't feed her half as often as I did.
- I'm silly half as much as you are.
- I costed money half as much as you did.
- You worked only half as hard as you can.
- You went to the museum half as often as I did.
from now on
- From now on, I'll finish homework everyday.
- From now on, I want you to get a good salary.
- From now on, I want you to be happy.
- Fron now on, call me Sherwin.
- From now on, don't ask for any meal.
call me/him/her a.
- Mr. Leo told me to call her Leo.
- The doctor who I met yesterday called me Sherwin.
- My brother-in-law calls me Sherwin.
- I look forward to being called Sherwin.
- I trained the dog to call me Sherwin.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-10-26 Thu 20:06]
** DONE Ask me if 写+读
CLOSED: [2023-10-26 Thu 20:13]
1. Manual workers receive more money than office workers. Why
	 Why do manual workers receive more money than office workers?
2. We refer to people who work in offices as 'white-collar workers'. How
		How do we refer to people who work in offices?
3. Some people are prepared to sacrifice higher pay to become office workers. Why
		Why are some people prepared to sacrifice higher pay?
4. Alf was too embarrassed to tell his wife about his job. Why
		Why was Alf too embarrassed to tell his wife about his job?
5. He is dressed in a smart black suit every morning. How
		How is he dressed every morning?
6. He changed into overalls when he got to work. When
	 When did he change into overalls?
7. His wife never discovered she'd married a dustman. Why...never
	 Why did his wife never discover she'd married a dustman?
8. He will soon be working in an office. Where
	 Where will he soon be working?
9. He will be earning half as much as he used to. How much
	 How much will he be earning?
10. People will call him 'Mr. Bloggs'. What
		What will people call him?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-10-26 Thu 20:25]
When they got married, Alfred Bloggs simply told his wife that he worked for the Corporation.
Though he was dressed in a smart black suit before he left home,
	he changed into overalls and spent the day as a dustman.
The he took a shower and changed back into the suit at night.
This lasted for over two years and his fellow dustmen kept his secret.
His wife will never learn the truth, for her husband will be working in an office in future.

** DONE tell the story 口语复述
CLOSED: [2023-10-26 Thu 20:27]
** DONE composition 阅读 或 写作
CLOSED: [2023-10-26 Thu 20:35]
One morning Alf and three other dustmen were collecting rubbish in Merton Street
	and they stopped outside Mrs. Frost's house.
Though Alf didn't know it, his wife was visiting Mrs. Frost at the time.
She and Mrs. Frost were old friends, though Mrs. Frost had never met Alf.
Alf was just getting out of the dust cart to go into Mrs. Frost's backyard
	when he saw his wife leaving Mrs. Frost's house.
He quickly returned to the dust cart and hid in the driving cabin.
While he was hiding, his fellow dustmen helped him by collecting Mrs. Frost's rubbish.

Meanwhile, Alf's wife and Mrs. Frost talked on the doorstep.
It looked as though their conversation would never end!
At last Mrs. Bloggs said goodbye to Mrs. Frost.
She waved to one of the dustmen whom she recognized
	and she went towards the dustcart to greet him.
The dustman waved back and gave her a big smile as the dustcart drove off.
Mrs. Bloggs stood on the pavement and watched the dustcart disappear down the street.
Then she began to walk home.
'It's all right, Alf', his friend said.
'She can't see you now.'
'Thanks, Jim,' Alf said. 'That was a luck escape!'

** Topics for discussion

