#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 08 A famous monastery
#+begin_verse
What are the St. Bernard dogs used for?

The Great St. Benard Pass *connects Switerland to Italy*.
At 2,473 metres, it is the highest mountain pass in Europe.
The famous monastery of St. Bernard, which was founded in the eleventh century,
	lies about a mile away.
*For hundreds of years*,
	St. Bernard dogs have saved the lives of travellers crossing the dangerous Pass.
These friendly dogs, which were first brought from Asia,
	were used as watchdogs even in Roman times.
*Now that* a tunnel has been build through the mountains, the Pass is less dangerous,
	but each year, the dogs are still sent out into the snow whenever a traveller *is in difficulty*.
Despite the new tunnel, there are still a few people who rashly *attempt to cross* the Pass on foot.

During the summer months, the monastery is very busy,
	for it is visited by thousands of people who cross the Pass in cars.
As there are so many people about, the dogs have to be kept in a special enclosure.
In winter, however, life at the monastery is quite different.
The temperature drops to minus 30 degrees and very few people attempt to cross the Pass.
The monks prefer winter to summer for they have more privacy.
The dogs have greater freedom, too,
	for they are allowed to wander outside their enclosure.
The only regular visitors to the monastery in winter are parties of skier
	who go there at Christmas and Easter.
These young people, who love the peace of the mountains,
	always *receive a warm welcome* at St. Bernard's monastery.
#+end_verse
** expression
monastery: [ˈmɑnəˌsteri] n. St. Bernard寺院,修道院
pass: [pæs] n. a high road or path that goes between mountains to the other side关隘
watchdog: [ˈwɑtʃˌdɔɡ] n.看门狗
rashly: adv.莽撞地,冒失地
enclosure: [ɪnˈkloʊʒər] n. an area surrounded by a wall or fence, and used for a particular purpose
monk: [mʌŋk] n. a member of an all-male religious group that lives apart from other people in a monastery围地,圈地
privacy: [ˈpraɪvəsi] n.  the state of being free from public attention隐私
skier: [ˈskiər] n.滑雪者
Easter: [ˈiːstə(r)] n.复活节

Can I get some privacy?: 我能有点隐私吗?
--------------------
connect a. to b. = a. be connected to b.: 连接A到B
for hundreds of years: 数百年来
Now that + ...(原因状从): 现在因为...
be in difficulty: run into serious trouble陷入困境
attempt to do sth.: try to do sth.尝试做某事
receive a warm/cold welcome: 受到热烈/冷淡的欢迎

** words
monastery [ˈmɒnəst(ə)ri] n. 寺庙
St. Bernard ['bə:nəd; bə'nɑ:d]
pass [pɑːs] n. 关隘
watchdog [ˈwɒtʃdɒɡ] n. 看门狗
rashly [ˈræʃli] adj. 鲁莽地
enclosure [ɪnˈkləʊʒə(r)] n. 围地
monk [mʌŋk] n. 和尚
privacy [ˈprɪvəsi] n. 清净
skier [ˈskiːə(r)] n. 滑雪者
Easter [ˈiːstə(r)] n. 复活节

** DONE 单词造句
CLOSED: [2023-11-01 Wed 21:09]
monastery n. St. Bernard
- He will live in a monastery for the rest of his life.
- Not only did they go to the monastery, but they went to the stream as well.
- Not only did they go to the monastery, but they raised money as well.
- Not only did they go to the monastery, but they went to theater as well.
- The monastery has been burnt down for some reasons.
pass n.
- The women and her babies were ordered to make for the mountain pass.
- We took a long time to cross the mountain pass.
- The monk is going to write an article on the famous Pass.
- We were amazed to find that the woman had crossed the pass alone.
- A party of skiers went to extremes to cross the pass.
watchdog n.
- If you deal with the watchdog, I'll deal with the guard.
- The watchdog was too embarrassed to go home.
- All of us were put to shame by the watchdog who plays football so well.
- The watchdog used to be called AngelaBaby.
- The watchdog dressed in a wire is kept in the back yard now.
rashly adv.
- The article shouldn't rashly go to press.
- I must have acted rashly.
- I rashly agree to reach an agreement.
- I confirmed that I rashly changed into black stockings.
- Such is human nature that we often regret what we rashly speak.
enclosure n.
- Trust me, the dog would prefer this enclosure to that one.
- The enclosure is the secret of success.
- I need to keep a secret that you bought the enclosure without parents' permission.
- Just stay in the enclosure and keep the status quo.
- How does she keep a horse in a special enclosure?
monk n.
- We are very proud of the monk.
- Imagine his dismay when the monk had to take a shower in such a bathroom.
- The monk goes to extremes to keep status quo in the monastery.
- The monk are often given higher status for one reason or another.
- The monk is expert at reading long dense books.
privacy n.  Can I get some privacy?
- You should read privacy police carefully.
- Oh, my dear. May I get some privacy?
- The authorities claimed that people needn't privacy at all.
- The CEO of the website stated that people in China prefer free service to privacy.
- Dad, get out of my room for the simple reason that I need some privacy.
skier n.
- These days this kind of equipment is very popular with skiers.
- These skiers often risk their life in this way that they cross the dangerous Pass by themselves.
- The skier has the privilege of feeding the dog kept in the enclosure.
- He turned out to be a skier.
- Despite the fact that you are a skier.

** vocabulary
famous: well-known
founded: established
lies: is
now that: since, because
rashly attempt: unthinkingly
quite: entirely
drops: falls

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-02 Thu 20:03]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-01 Wed 21:09]
connect a. to b. = a. be connected to b.
- The village which connects this village to world outside has broken down last night.
- The worker succeeded in connecting the pipe to the drainage system of the city.
- May I connect the wire to your computer?
- You shouldn't have connected the wire to your computer.
- The microphone made in China is connected to the tower.
for hundreds of years
- His family has had power in the country for hundreds of years.
- Their family has been worship the goddess for hundreds of years.
- This picture has been in my house for hundreds of years.
- This conviced me that my family has farmed in this area for hundreds of years.
- Our family has lived in about her for hundreds of years.
Now that + ...(原因状从)
- Now that you are a graduate, you will be free on a long vocation.
- Now that the entrance of the museum is closed, we shall go home.
- Now that you took money to pieces, we couldn't afford to take a bus.
- You certainly gave me a surprise now that you repair the clock.
- Now that the clerk is eager to get a better salary, he will do anything to sell it to you.
be in difficulty
- When I am in difficulty, it always remind me of my father.
- We should pay more attention to the people who are in difficulty.
- The nurse is in difficulty now that the patient is having an operation.
- I'm fairly certain that my wife is in difficulty.
- Our family used to be in difficulty.
attempt to do sth.
- Not only did he attempt to buy the house, but he attempted to hold the Games as well.
- Not only did he attempt to enter for the competition, but he intended to break the world record.
- What a mess! I attempted to clean it up.
- I attempted to train my cat pressing the button.
- I attempted to get close to my girlfriend in the crowd.
receive a warm welcome
- She was disappointed to find that she didn't receive a warm welcome.
- I was just wondering if I would receive a warm welcome.
- On that festive, every stranger coming to the village receive a warm welcome.
- This group of pop singer received a warm welcome at the station.
- If you made that stupid remark on the bulletin board, you wouldn't receive a warm welcome.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-02 Thu 19:58]
** DONE Ask me if 写+读
CLOSED: [2023-11-02 Thu 20:10]
1. The Great St. Bernard's Pass connects two countries. Which two countries
	 Which two countries does the Great St. Bernard's Pass connect?
2. It is the highest pass in Europe. Which
		Which is the highest pass in Europe?
3. The monastery was founded in the eleventh century. When
		When was the monastery founded?
4. St. Bernard's dogs have saved the lives of travellers for hundreds of years. How long
		How long have St. Bernard's dogs saved the lives of travellers?
5. The dogs were brought from Asia. Where
		Where were the dogs brought from?
6. The Pass is less dangerous now. Why
	 Why is the Pass less dangerous now?
7. The monastery is visited by thousands of people. When
	 When is the monastery visited by thousands of people?
8. The temperature drops to -30' in winter.
	 How low does the temperature drop in winter?
9. Very few people cross the Pass in winter.
	 Why do very few people cross the Pass in winter?
10. The monks prefer winter to summer. Why
		Why do the monks prefer winter to summer?

	 
** 摘要写作 写 & 对答案
The St. Bernard's monastery is visited by thousands of people in summar,
	who cross the Pass in cars.
Because there are so many people about, the dogs are kept in a special enclosure.
As the temperature in winter drops to -30,
	there are few visitors,
	so the monks prefer this season.
The dogs are also free to wander outside their enclosure.
Parties of skiers who regularly visit the monastery in winter,
	during Christmas and Easter when received a warm welcome.

** DONE tell the story 口语复述
CLOSED: [2023-11-02 Thu 20:23]
** composition 阅读 或 写作
One very cold morning, a monk took two St. Bernard's dogs out for exercise.
He immediately noticed that the dogs were very restless.
Suspecting at traveller might be in difficulty,
	the monk returned to the monastery to organize a search party.
The two dogs led four monks through the snow.
Two of the monks pulled a sledge behind them, in case they needed it.
There had been very high winds the previous night,
	but now everything was still and visibility was bad because there was a heavy fog.
Moreover, the temperature had fallen to -20 degrees.
The dogs led the monks towards the Pass and as the monks got near,
	they heard cries in the distance.
The dogs soon found a man who was trapped under the snow and immediately dragged him out.
The man was alive, but frozen stiff.
The monks strapped him to the sledge and took him back to the monastery.
The man was unconscious, but he soon recovered in the warm atmosphere of the monastery
	where he was given plenty of hot drinks and food.
When the traveller was able to speak,
	the monks listened with interest
		as he told them what had happened the previous night.
** Topics for discussion
