#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 15 Fifty pence worth of trouble
#+begin_verse
Did George get anything for his fifty pence? What?

Children always appreciate small gifts of money.
Mum or dad, of course, provide a regular *supply of* pocket money,
	but uncles and aunts are always a source of extra income.
With some children, small sums *go a long way*.
If fifty pence pieces *are not exchanged for* sweets, they rattle for months inside money boxes.
Only very thrifty children managed to *fill up* a money box.
For most of them, fifty pence is a small price to pay for a nice big bar of chocolate.

My nephew, George, has a money box but it is always empty.
Very few of the fifty pence pieces and pound coins I have given him have *found their way* there.
I gave him fifty pence yesterday and *advised him to save* it.
Instead he bought himself fifty pence worth of trouble.
*On his way to* the sweet shop, he dropped his fifty pence
	and it bounced along the pavement and then disappeared down a drain.
George took off his jacket,
	*rolled up* his sleeves and pushed his right arm through the drain cover.
He could not find his fifty pence piece anywhere, and *what is more*, he could not get his arm out.
A crowd of people gathered round him and a lady *rubbed his arm with* soap and butter,
	but George was firmly stuck.
The fire brigade was called and two fire fighters freed George using *a special type of* grease.
George was not too upset by his experience
	because the lady who owns the sweet shop *heard about* his troubles
		and *rewarded him with* a large box of chocolates.
#+end_verse
** expression
appreciate: [əˈpriʃiˌeɪt] v.欣赏,感激
pocket [ˈpɑkɪt] money: 零花钱
rattle: [ˈræt(ə)l] v. if you rattle something, or if it rattles, it shakes and makes a quick series of short sounds格格作响
thrifty: [ˈθrɪfti] adj. using money carefully and wisely节俭的
nephew: [ˈnefju] n.侄子,外甥
bounce: [baʊns] v. it immediately moves up or away from a surface after hitting it弹起,跳起
pavement: [ˈpeɪvmənt] n. sidewalk人行道
stick [stɪk]-stuck-stuck: v.卡住
fire brigade: n. 消防队
grease: [ɡris] n. a thick oily substance that is put on the moving parts of a car, machine etc to make it run or move smoothly润滑油

I appreciate your honesty.: 我感谢你的诚实
	understanding/interesting/concern/support/patience/trust/time/help/it/that ...
--------------------
supply of sth.: 某物的供给
go a long way: 维持很长时间
be exchanged for sth.  exchange a. for b.: 被交换成某物
fill up a. with b. 用B充满A
find one's way: reach a destination, especially with some difficulty or not as a matter of course到达
advise sb. to do sth.: 建议某人做某事
On one's way to sp.: 在去某地的路上
roll up one's sleeves: 卷起某人的袖子
What is more=what's more: 而且
rub a. with b.: 用B擦A
a special type of sth.: 一种特殊类型的某物
hear about sth.: 听说某事物
reward sb. with sth.: 用某物奖励某人

** words
appreciate [əˈpriːʃieɪt] v.欣赏
pocket [ˈpɑːkɪt] money 零用钱
rattle [ˈræt(ə)l] v.格格作响
thrifty [ˈθrɪfti] adj.节俭的
nephew [ˈnefjuː] n.侄子
bounce [baʊns] v.弹起,跳起
pavement [ˈpeɪvmənt] n.人行道
stick [stɪk] v.卡住
brigade [brɪˈɡeɪd] n.旅,(消防)队
grease [ɡriːs] n.润滑油

** vocabulary
appreciate: are pleased with
gifts: presents
extra income: additional money
rattle: make a noise
price: sum amount
gathered: collected
was firmly stuck: could not be moved

** DONE 单词造句
CLOSED: [2023-11-14 Tue 21:44]
appreciate v.  I appreciate your honesty.
- I appreciate you help.
- I appreciate that you closed the window.
- I appreciate that you gave us a performance.
- I appreciate that you kept order last night.
- I appreciate that you gave me a lift.
pocket money
- He waved to his uncle and asked for pocket money.
- On the way home, he found he had lost his pocket money.
- He was nervous about his pocket money that I gave him.
- You have enough pocket money and you can afford it.
- Sorry to interrupt, but I lost my pocket money just now.
rattle v.
- He slammed so hard that all the windows rattled.
- Keys rattled in his pocket while the landlord was walking.
- It seems that there are coins rattling in the washing machine.
- I heard something rattling in the washing machine.
- Rattling keys reminded me of my father.
thrifty adj.
- I always asked my wife to be more thrifty.
- Although he made large sums of money, he was still very thrifty.
- She is so thrifty that she never wastes any money.
- She is very thrifty and always asks for a life when she goes to work.
- She is very thrifty and always takes buses for work.
nephew n.
- It's a pity that our nephew died from a car accident yesterday.
- I hurried to Greenwich where my nephew grows up.
- My nephew may have replied a mail to us.
- My nephew realized to his horror that he had lost his money box.
- Instead of catching a bus, my nephew always takes a taxi.
bounce v.
- There is a coin bouncing along the road.
- She complained that his hair is always bouncing while she is walking.
- So long as I get home, I bounce a ball in the garden.
- She is mad at the girl who is bouncing a ball in the square.
- A great many of coins bounced along the street for some reason.
pavement n.
- You should have walked on the pavement.
- The pavement must be repaired yesterday.
- The pavement didn't come into use for some reason.
- I never dreamed of walking on a pavement which only appeared in the book.
- The villagers complain that the pavement is alwaying being broken.
stick-stuck-stuck
- She is telling a story in which a man was stuck in the mud.
- I woke up with a start, and realized that I was stuck in the mud.
- The boy pretended that he was stuck in the mud and asked for our help.
- After putting out the fire, they were all stuck in the mud.
- He called out to the boy who was stuck in the mud.
fire brigade n.
- The fire brigade is calling out to the man who was in the house.
- The fire brigade used to exercise very much.
- It's my job to call the fire brigade right now.
- When there was a snake in the station,
		the police called the fire brigade as quickly as possible.
- On calling the fire brigade, she aimed the fire extinguisher at the house.
grease n.
- The cup was filled up with grease.
- This convinced her that her son's legs were covered with grease.
- It's disturbing to think that your son is covered with grease.
- She claimed to have seen a special type of grease.
- The grease began to accumulate, soon the box was filled up with grease.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-15 Wed 20:04]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-14 Tue 21:44]
supply of
- There is no shortage of supply of blood in the hospital.
- They provide an enough supply of books to read in the waitting room.
- Waking up with a start, he realized that he didn't have enough supply of foods in the desert.
- The hospital doesn't keep an enough supply of blood for one cause or another.
- She is equal to take a large supply of foods on our journey.
go a long way
- People who do manual work in China always hope that their children go a long way.
- People in China often go to extremes to go a long way.
- You have a splendid mind, you will go a long way.
- She is very thrifty, and her pocket money goes a long way.
- The man gets a good salary and will go a longer way than us.
be exchanged for sth.  exchange a. for b.
- Where can I exchange RMB for dollar?
- People sometimes is unwilling to exchange their money for services.
- My mom is so thrifty that she exchanged all cans for money after the picnic.
- I'm glad that we can exchange money for petrol.
- Such is human nature, that people are often willing exchange money for rise in status.
fill up a. with b.
- Fill it up, I will pay the bill tomorrow.
- We should have filled up the petrol tank before we went.
- It seems that he didn't fill up the petrol tank.
- Not only did they fill up the glasses, but they found their way in the exhibition.
- Not only did they fill up the glasses, but they drove at a high speed.
find one's way
-
-
-
-
-
advise sb. to do sth.
- I advised my nephew to save his pocket money which I gave him.
- He advised his boss to put the poor man out of business.
- She was impatient to talk to him, and advised him to ask her colleaugue for help.
- I advised him to load his dinghy with a spear gun.
- I wish that I had advised him to go on a diet.
On one's way to sw.
- On my way to the mall, I grab a milk tea for you.
- On my way to museum, I had an opportunity to meet a famous actor.
- On my way to school, I was made to make a contribute.
- On my way to school, I realized that I had lost my keys.
- On my way to school, my boss gave me an order to solve bug.
roll up one's sleeves
- The moment the order was gave, everyone rolled up their sleeves and worked hard.
- I rolled up my sleeves, and began to do washing.
- She rolled up her sleeves, and bounced a ball with her cat.
- If you don't roll up your sleeves, you will get into such a mess.
- His mother makes an impact on him. He rolls up his sleeves whenever he does homework.
What is more=what's more
- What's more, the microphone has been connected to the tower.
- What's more, we received a warm welcome.
- What's more, the America gained its independence from England.
- What's more, the boat was sinking.
- What's more, it had fifteen water-tight compartments.
rub a. with b.
- A kind lady rubbed my arm with grease to get my arm out.
- She is too busy rubbing her ass with lotion.
- My wife always asks me to rub her ass with lotion.
- My wife stated that she was rubbing her face with fifteen pounds worth of lotion.
- They rubbed each other with oil with the fantastic background music.
a special type of sth.
- He is busy making a special type of butter.
- Her arm was covered with a special type of perfume.
- This special type of perfume is not exempt from import duty.
- She died of a special type of disease.
- He became an expert at making this special type of drug.
hear about sth.
- I'm likely to hear about the car accident.
- Soon, everyone in the village heard about the news that the vicar lost his money.
- I'm sorry that I heard about your injury.
- I'm sorry that I heard about the death of your father.
- I heard about the news that America gained its independence from England.
reward sb. with sth.
- She made a study of rewarding her student with sweets.
- These father have one thing in common: they all reward their children with sweets.
- Imagine his dismay when he found that his mother rewarded his rival with chocolates.
- Instead of fish, I rewarded my cat with a can of food.
- The bank manager rewarded the lady with 100 pounds worth of phone.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-15 Wed 20:04]
** DONE Ask me if 写+读
CLOSED: [2023-11-15 Wed 20:09]
1. Children always appreciate small gifts of money. What
	 What do children always appreciate?
2. Parents provide a regular supply of pocket money. What
		What do parents provide?
3. George has a money box. What
		What does George have?
4. It is always empty. Why
		Why is it always empty?
5. George bought fifty pence worth of trouble. What
		What did George buy?
6. The coin disappeared down a drain. Where
	 Where did the coin disappear?
7. George pushed his arm through the drain cover. Where
	 Where did George push his arm?
8. He could get his arm out. Why couldn't
	 Why couldn't he get his arm out?
9. A lady rubbed his arm with soap and butter. What
	 What did a lady rub his arm with?
10. The fire fighters freed George. How
		How did the fire fighters free George?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-15 Wed 20:20]
When George was going to the sweet shop, he lost his fifty pence down a drain.
After taking off his jacket,
	he put his arm through the drain cover.
He failed to find his fifty pence,
	what's more, he couldn't get his arm out.
A crowd of people gathered round him
	and a lady rubbed his arm with soap and butter.
She failed to free him, but the firemen succeeded using a special type of grease.
The owner of the sweet shop presented him with a large box of chocolates.

** DONE tell the story 口语复述
CLOSED: [2023-11-15 Wed 20:24]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-15 Wed 20:28]
I was walking along the street when I saw a crowd ahead of me.
I could hear people shouting and making a noise.
On arriving at the scene, I saw a small boy on the pavement with his arm in a drain cover.
A lady carrying a large bar of soap and a saucepan of water knelt down beside the boy.
She asked the boy if he was in pain and he said he wasn't.
 
Then she rubbed his arm with butter, but he couldn't get it free.
Meanwhile, someone had telephoned the fire brigade.
The boy had begun to cry, but when he saw the firemen, he cheered up.
At first the firemen decided to cut through the drain cover,
	but they changed their minds and rubbed the boy's arm with a special type of grease.
The boy was soon free and though his arm hurt, he was smiling.
 
** Topics for discussion
