#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 16 Mary had a little lamb
#+begin_verse
Was Dimitri right to apologize to his neighbour? Why not?

Mary and her husband Dimitri lived in the tiny village of Perachora in southern Greece.
One of Mary's prize possessions was a little white lamb which her husband had given her.
She kept it *tied to a tree* in a field during the day and went to fetch it every evening.
One evening, however, the lamb was missing.
The rope had been cut, so it was obvious that the lamb had been stolen.

When Dimitri came in from the fields, his wife told him what had happened.
Dimitri at once set out to find the thief.
He knew it would not prove difficult in such a small village.
After *telling several of his friends about the theft*,
	Dimitri found out that his neighbour, Aleko, had suddenly acquired a new lamb.
Dimitri immediately went to Aleko's house and angrily *accused him of stealing* the lamb.
He told him he had better return it or he would call the police.
Aleko *denied taking* it and led Dimitri into his backyard.
*It was true that* he had just bought a lamb, he explained, *but* his lamb was black.
*Ashamed of having acted* so rashly, Dimitri *apologized to Aleko for having accused* him.
While they were talking
	it began to rain and Dimitri stayed in Aleko's house until the rain stopped.
When he went outside half an hour later,
	he *was astonished to find that* the little black lamb was almost white.
Its wool, which had *been dyed black*, had been washed clean by the rain!
#+end_verse
** expression
prize: [praɪz] adj. very good or important珍贵的,宝贵的
tie: [taɪ] v.拴,系
accuse: [əˈkjuz] v.指控
theft: [θeft] n. an act of stealing something偷盗行为,偷盗案
deny: [dɪˈnaɪ] v. SAY STH IS NOT TRUE否认
ashamed: [əˈʃeɪmd] adj. feeling very sorry and embarrassed because of something you have done感到羞耻,忏愧
apologize: [əˈpɒləˌdʒaɪz] v.道歉
dye: [daɪ] v. to give something a different colour using a dye染

prize money: 奖金
tie sb. to sth. = sb. be tied to sth.: 把某人绑某物上
accuse sb. of doing sth.: 指控某人做了某事
deny doing.../sb. deny that + ...: 某人做某事/某人否认+...
be ashamed of sth./doing sth./having done sth.: 羞于某事/做某事/做过某事
apologize to sb. (for doing sth.): 对某人道歉
dye something + some-color.: eg. dye his hair red把某物染色
--------------------
tell sb. about sth.: 告诉某人关于某事
It's ture that + ..., but + ...: 虽然...,但是...
sb. be astonished to find (that) + ...: 某人很惊讶地发现+...
** Words
prize [praɪz] adj. 珍贵的，宝贵的
tie [taɪ] v. 拴，系
theft [θeft] n．偷盗行为，偷盗案
accuse [əˈkjuz] v. 指控
deny [dɪˈnaɪ] v. 否认
ashamed [əˈʃeɪmd] adj．感到羞耻，惭愧
apologize [əˈpɒləˌdʒaɪz] v. 道歉
dye [daɪ] v. 染

** vocabulary
tiny: very small
fetch: get
missing: gone
acquired: got obtained
denied: said it wasn't true
apologized: said he was sorry
dyed: colored

** DONE 单词造句
CLOSED: [2023-11-16 Thu 21:20]
prize adj.  prize money
- One of my prize possessions is a little cat.
- If you enter for the competition, you will win the prize money.
- It was obvious that your rival won the prize woney.
- It was he who won the prize money, not you.
- I did win the prize money in the competition.
tie v.  tie sb. to sth. = sb. be tied to sth.
- There is a special type of horse tied to the tree.
- After they were tied to the chair, John went through the contents of their bags.
- My grandfather ordered me to tie the dog to the gate.
- I was able to tie the bull to the tree.
- It seems that the horse wasn't tied to the fence.
accuse v.  accuse sb. of doing sth.
- He was accused of watching a political musical last night.
- Why don't we accuse him of murder?
- I regret accusing my nephew of stealing my money.
- My nephew was accused of stealing his parents' pocket money.
- The doctor who had an operation last night was accused of murder.
theft n.
- The boy who played truant from school yesterday was accused of theft.
- The relative of the patient is inquiring about theft.
- I advised him to accuse his wife of theft.
- The journalist is going to write an article on theft.
- She heard about a story which was about theft.
deny v.  deny doing.../sb. deny that + ...
- I denied filling up my father's petrol tank with water.
- She denied exchanging money for sweets last night.
- She denied that she killed her husband at the edge of forest.
- She denied that she offered to drive a bus.
- I denied that I paid money to him.
ashamed adj.  be ashamed of sth./doing sth./having done sth.
- Ashamed of having made my cat to drink water, I offered her a can of food.
- I was never ashamed of kicking his ass.
- I was deeply ashamed of my bad behavior at the party.
- The busmen are never ashamed of have gone on strike.
- It seems that Miumiu is ashamed of having eaten this.
apologize v.  apologize to sb. (for doing sth.)
- I have apologized to my cat for stamping her.
- I must apologize to my wife for forgeting our wedding anniversary again.
- I have difficult in apologizing to my coworkers after arguing with them.
- I was disappointed to learn that my son hadn't apologized to his sister.
- After I apologized to her, my wife bursted into tears.
dye v.  dye something + adj.
- We were all put to shame by the boy who dyed his hair green.
- Liu Xing claimed that he would dye his hair green.
- If you dye your hair red, your father will get very angry.
- We should dye it red, and then make it offical.
- The painter dyed the wall red, then double checked it.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-17 Fri 20:01]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-16 Thu 21:20]
tell sb. about sth.
- I have told you about the program over and over again.
- I have told you about turning your attention to the commander.
- She was told about a story on theft.
- She told me about her history that she was a pilot.
- The detective has already told me about your affairs.
It's ture that + ..., but + ...
- It's ture that I made that stupid remark, but I love my country.
- It's ture that I am sensitive about criticism, but I want to make a progress.
- It's ture that you got a good salary, but the company hadn't made a profit.
- It's ture that the toy is on show, but it is sold out.
- It's ture that I went to college, but I haven't learnt any skill yet.
be astonished to find (that) + ...
- I was astonished to find that my cat was in unhealthy condition.
- I was astonished to find that my nephew exchanged his fifty pence for a bar of chocolate.
- I was astonished to find that my rival said hello to me.
- I was astonished to find that the girl I had a crush on relied a letter to me.
- I was astonished to find that the cat was stuck in the mud.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-17 Fri 20:01]
** DONE Ask me if 写+读
CLOSED: [2023-11-17 Fri 20:07]
1. Mary and her husband lived in Perachora. Where
	 Where did Mary and her husband live?
2. Her husband had given her a lamb. What
		What had her husband given her?
3. Mary kept it in a field. Where
		Where did Mary keep it?
4. The rope had been cut. What
		What had been cut?
5. Aleko had acquired a new lamb. Who
		Who had acquired a new lamb?
6. Dimitri accused Aleko of stealing the lamb. What
	 What did Dimitri accuse Aleko of?
7. Aleko denied taking it. Why
	 Why did Aleko deny taking it?
8. He led Dimitri into his backyard. Where
	 Where did he lead Dimitri?
9. His lamb was black. What color
	 What color was his lamb?
10. Dimitri apologized to Aleko. Why
		Why did Dimitri apologize to Aleko?
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-17 Fri 20:17]
WHen Dimitri came home, Mary told him that her white lamb had been stolen.
On learning that his neighbour, Aleko, had acquired a lamb,
	Dimitri went to Aleko's house and accused him of stealing it.
When Aleko showed his lamb,
	Dimitri saw it was black,
	so he apologized.
After staying in Aleko's house for a while because it had begun to rain,
	Dimitri got a surprise outside when he found the lamb was almost white.
It had been dyed black!

	

** DONE tell the story 口语复述
CLOSED: [2023-11-17 Fri 20:23]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-17 Fri 20:26]
Dimitri was surprised to find that the lamb had turned white.
He took a close look at it and recognized it as his own.
This discovery immediately led to an angry scene between Dimitri and Aleko.
Dimitri repeated his accusation that Aleko had stolen the lamb,
	but Aleko still denied any theft.
During the violent argument,
	Dimitri said the rain had proved that the lamb had been dyed black
		and he recognized it immediately as the one he had given to his wife.
When Aleko finally admitted he had stolen the lamb, Dimitri called the police.
Aleko was arrested and Dimitri took his lamb home.
The story caused a lot of excitement in the village.
The villagers didn't often have the opportunity to talk about such an important event
	and they were greatly amused by what had happened.
Some thought Aleko had been very clever.
Others thought he had been extremely stupid.
Others said God had sent the rain to punish Aleko for his crime
	and to prove he was a thief.
They discussed the event at great length for a long time,
	as there wasn't much else to talk about in a village
		where nothing much ever happened.

** Topics for discussion
