#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 17 The longest suspension bridge in the world
#+begin_verse
How is the bridge supported?

Verrazano, an Italian *about whom little is known*,
	sailed into New York Harbour in 1524 and named it Angouleme.
He *described it as* 'a very *agreeable situation* *located within* two small hills
	*in the midst of* which flowed a great river.'
Though Verrazano *is by no means considered to be* a great explorer,
	his name will probably remain immortal,
	for on November 21st, 1964, the longest suspension bridge in the world *was named after* him.

The Verrazano Bridge, which was designed by Othmar Ammann, *joins Brooklyn to Staten Island*.
It has *a span of* 4,260 feet.
The bridge is so long that the shape of the earth had to *be taken into account* by its designer.
Two great towers support four huge cables.
The towers are built on immense underwater platforms made of steel and concrete.
The platforms extend to a depth of over 100 feet under the sea.
These alone took sixteen months to build.
Above the surface of the water, the towers rise to *a height of* nearly 700 feet.
They support the cables *from which the bridge has been suspended*.
Each of the four cables contains 26,108 *lengths of wire*.
*It has been estimated that* if the bridge *were packed with* cars,
		it would still only be carrying *a third of* its total capacity.
However, size and strength are not the only important things about this bridge.
Despite its immensity, it is both simple and elegant,
	*fulfilling its designer's dream* to create 'an enormous object drawn as faintly as possible'.
#+end_verse
** expression
suspension: [səˈspenʃ(ə)n] n. suspend v.悬挂,悬职
agreeable: [əˈɡriəb(ə)l] adj. situation n.宜人的风景
locate: [ˈloʊˌkeɪt] v. location n.坐落
immortal: [ɪˈmɔrt(ə)l] adj. so famous that it will never be forgotten永生的,流芳百世的
span: [spæn] n.  a period of time between two dates or events跨度
cable: [ˈkeɪb(ə)l] n. a plastic or rubber tube containing wires that carry telephone messages, electronic signals, television pictures etc缆索
concrete: [ˈkɑŋˌkrit] n.混凝土
length: [leŋθ] n.长
estimate: [ˈestɪmət] v.估计
capacity: [kəˈpæsəti] n.承受量
immensity: [ɪˈmensəti] n.巨大
elegant: [ˈelɪɡənt] adj.优美别致的
faintly: [ˈfeɪntli] adv.轻微地

agreeable/pleasant + situation/man/day: 宜人的环境
be located in/near: 坐落于/靠近...
a span of ...: ...的跨度
life span: 寿命
a length of/lengths of + rope/pipe/wire: 一段绳/管/线
It is estimated that + ...: 据估计+...
sb. estimates that + ...: 某人估计+...
--------------------
little/not much/not everything is known about a.: 对A知之甚少
describe A as B: 把A描述成B
in the midst of ...:在...的中间
by no means: not possible绝无可能
be considered to be adj./n.: 被认为是...
sth. be named after sb.: 某物以某人命名
join a. to b. = connect a. to b.: 连接A和B
be taken into account = take sth. into account 考虑某事
a height of ...: ...的高度
A be suspended from B: A悬挂于B
be packed with ...: to fill something with things or people of a particular type挤满,塞满
a third of sth: 某物的1/3
fulfill sb's dream: something or someone made your dream come true实现某人的梦想

** words
suspension [səˈspenʃ(ə)n] n.吊
agreeable [əˈɡriːəb(ə)l] adj.宜人的
situation [ˌsɪtʃuˈeɪʃ(ə)n] n.地点
locate [ˈloʊkeɪt] v.位于
immortal [ɪˈmɔːrt(ə)l] adj.永生的
Brooklyn [ˈbrʊklɪn; ˈbrʊklən] n.布鲁克林
Staten [nil] n.斯塔顿
span [spæn] n.跨度
cable [ˈkeɪb(ə)l] n.缆索
concrete [ˈkɑːnkriːt] n.混凝土
suspend [səˈspend] v.悬挂
length [leŋθ] n.根,段
estimate [ˈestɪmət] v.估计
capacity [kəˈpæsəti] n.承受量
immensity [ɪˈmensəti] n.巨大
elegant [ˈelɪɡənt] adj.优美别致的
faintly [ˈfeɪntli] adv.微细地

** vocabulary
agreeable situation: nice location
in the midst: in the middle of
considered: thought
remain immortal: never die
span: extent
taken into account: taken into consideration
support: hold

** DONE 单词造句
CLOSED: [2023-11-19 Sun 15:14]
suspension n. suspend v.
- There used to be a suspension bridge over the river.
- This suspension bridge is considered as an agreeable situation.
- He was tied to a chair on the suspension bridge.
- I will tell you about the history of the suspension bridge.
- I was astonished to find that the suspension bridge was damaged by army.
agreeable adj. situation n.  agreeable/pleasant + situation/man/day
- There is a long time when West Lake was considered as an agreeable situation.
- I spent an agreeable day at this hotel in the remote village.
- I was not allowed to meet her, for she is agreeable.
- What is more, this agreeable situation was filled up with people.
- The house's situation by the river is agreeable.
locate v. location n.  be located in/near
- My house used to be located near a river.
- He found his way at the hotel located near the lake.
- The city mall in a beautiful situation is very popular with these young people.
- Our stadium located in the park will have been built by the last day of this year.
- His house in a beautiful location has been sold last month.
immortal adj.
- Plato has claimed that the soul is immortal.
- He soon made a name for himself and would probably be immortal.
- After put out of business, the man remained immortal.
- The soldier which remains immortal made a name for himself during the war.
- There was a time when people there believed in an immortal goddess.
span n.  a span of  life span
- Over a span of ten years, Leo began to make a profit.
- It was obvious that the bridge has over a span of 100 meters.
- In a span of ten years, this country has been at war with his neighbor.
- If the bridge had a span of 100 meters, it wouldn't be enough strong.
- My cat's life span is over ten years.
cable n.
- If you damaged this cable, you would pay large sums of money to the authorities.
- There was a time when the electric cables were stolen by villagers.
- In times of war, the electric cables were damaged by fire.
- She wanted to devote herself to making discovery of cables.
- For your own protection, don't touch these cables.
concrete n.
- In memory of these hero, the authorities have built a concrete monument.
- The baby hit himself on the concrete floor and then let out a cry.
- The tall building is made of steel and concrete.
- He realized to his horror that his child hit himself on the concrete floor.
- This concrete wall was regarded as watertight.
length n.  a length of/lengths of + rope/pipe/wire
- The policeman arrived on the scene seeing a cut length of rope.
- I exchanged some money for lengths of wire.
- The worker was accused of stealing lengths of wire in the factory.
- I found the worker stealing lengths of wire.
- However, the worker denied taking all 500 lengths of wire.
estimate v.  It is estimated that + ...  sb. estimates that + ...
- It is estimated that the cat was tied to a chair.
- He estimated that small sums would go a long way.
- He estimated that
		the lady who owned the sweets shop would rewarded him with a bar of chocolate. 
- He estimates that they will have a enough supply of foods and water.
- It is estimated that the soldiers will leave if they are offered enough money.
capacity n.
- The bottle only has a capacity of a second of 1 liter.
- Do the water tanks provide a capacity of 1 liter?
- For your own protection, you'd better take the bottle which has a capacity of 1 liter.
- He made the remarkable discovery that the river has a capacity of two millions of liter.
- The stadium which will have been built by next year will have a seating capacity of 50,000.
immensity n.
- I wouldn't never realize the immensity of the earth, if I didn't go to university.
- I am very nervous about the immensity of the task.
- I realized the immensity of the task when I drived on to my friend's house.
- Despite of the immensity of task, she managed to finish it.
- I will have a difficult time because of the immmensity of my task.
elegant adj.
- Not only did he buy his wife an elegant dress, but he bougth his mother another.
- Not only did he buy his wife an elegant dress, but he gave her a splendid performance.
- The chairman was standing in the midst of these elegant women.
- These elegant women are going to give five performance.
- I waved to the elegant woman and asked for a lift.
faintly adv.
- He smiled faintly and knocked her to the ground suddenly.
- The sun always shines faintly through these leaves.
- He rolled up his sleeves faintly and began to do his work.
- It bounced faintly and disappeared down a drain.
- Although he glanced at the elegant woman faintly, his wife noticed this and got very angry.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-19 Sun 20:25]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-19 Sun 15:14]
little/not much/not everything is known about a.
- Little is known about the capicity of the bridge.
- Little is known about the immensity of the task.
- Little is known about the man who worked for the coporation.
- Not everything is known about the mummy made in 4th century.
- Little is known about the history of my house.
describe a. as b.
- We are used to describe a luck man as a lucky dog.
- The captain was described as a immortal hero.
- I described my youth as a time of fear and confusion.
- He stated that his children used to describe him as a good father.
- Why did you describe this rude man as elegant?
in the midst of
- There used to be a hut in the midst of the forest.
- A groud of singers will give five performance in the midst of the park.
- The chairman was standing in the midst of people.
- The building is located in the midst of the city.
- He will be working in the midst of the city.
by no means
- He is by no means proud of such a rude father.
- She will by no means be away from her children.
- I will be by no means nervous about telling stories in public.
- Sorry to interrupt, I by no means afford to pay the bill.
- She by no means looks up in any dictionary.
be considered to be adj./n.
- The tatanic was considered to be unsinkable, for she had 15 watertight compartments.
- She was considered to be right, but she made an tremendous mistake recently.
- I was considered to be best student of my class.
- She was considered to be the prettiest girl I have ever seen.
- My was considered to be ugly before she dyed her hair black.
sth. be named after sb.
- My children are not allowed to be named after me.
- My father claimed to have named me after the chair man.
- She made an impact on my monther, and my mother named me after her.
- It seems that I was named after the great leader.
- I am likely to name my son after my cat.
join a. to b. = connect a. to b.
- This mountain road joins our village to my wife's village.
- The bridge which is being built will join Shenzhen to Hongkong.
- There is a small bridge joining my house to the other side of the river.
- The tunnel joins the England to the mainland.
- This great suspension bridge joins the Blooklyn block to the Staten island.
be taken into account = take sth. into account
- You must take into account the fact
		that if we were fired, we would get enought money to pay the bill.
- She always takes a variety of factors into account.
- He took into account the fact that he was fired and ran out of his money.
- This lady took her husband into account and bought her husband a special type of play station.
- The captain took into account the fact that the ship was sinking.
a height of + (长度 100m)
- The aircraft was supposed to be flying at a height of 100 meters.
- The kite is not allowed to be flying at a height of 50 meters in this country.
- Imagine her dismay when she found that she couldn't eat at a height of 100 meters.
- The balloon which reached a height of 100 meters was damaged by a plane.
- They managed to catch a ballon which reached a height of 100 meters.
be suspended from a.
- There used to be a beautiful light suspended from the ceiling.
- She was suspended from school for 3 days, for she played truent from school.
- Ross complained that he was suspended from museum for his angry.
- The order to suspended the light from the ceiling was given.
- So long ago as ten days before, the policewoman was suspended from duty.
be packed with ...
- The station was packed with young men and women, for a group of pop singer arrived.
- The lot was soon packed with a lot of automobiles.
- He realized to his horror that the mall was packed with workers.
- Being packed with people, the house is not cold any more.
- It will be packed with the fans of Mr. Messi.
a third of sth
- Only a third of cat died from falling tall buildings.
- You have just finished a third of your homework.
- If we get married, I will keep only a third of money and the rest is for you.
- There is no shortage of fuel, I have only used a third of it.
- There was a third of workers who were trapped in the mine.
fulfill sb's dream
- I fulfilled my dream of getting marry to her.
- If you don't work hard, you will never fulling your dream of going to university.
- Now that you have enough money,
		it's time to fulfill your dream of travelling all over the world.
- Fulfilling his dream, he made an impact on young men all over the world.
- Fulfilling his dream, he made everything official.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-19 Sun 20:26]
** DONE Ask me if 写+读
CLOSED: [2023-11-19 Sun 20:36]
1. Verrazano sailed into New York Harbour in 152- When
	 When did Verrazano sail into New York Harbour?
2. Verrazano is considered to be a great explorer. Why isn't
		Why isn't Verrazano considered to be a great explorer?
3. The Verrazano bridge was designed by Othmar Ammann. Who
		Who was the Verrazano bridge designed by?
4. Two towers support four huge cables. How many towers
		How many towers support four huge cables?
5. The platforms extend to a depth of over 100 feet under the sea. How far
		How far do the platforms extend to a depth of under the sea?
6. The platforms took sixteen months to build. How long
	 How long did the platforms take to build?
7. They rise to nearly 700 feet. How far
	 How far do they rise to?
8. Each cable contains 26,108 lengths of wire. How many lengths
	 How many lengths of wire does each cable contain?
9. The bridge is packed with cars. How often
	 How often is the bridge packed with cars?
10. It fulfils its designer's dream. How
		How does it fulfil its designer's dream?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-19 Sun 20:47]
The Verrazano bridge, which joins Brooklyn to Staten Island,
	has a span of 4,260 feet.
Its two great towers support four huge cables.
The towers are built on the platfroms made of steel and concrete,
	extending over 100 feet under the sea
	and rising nearly 700 feet above the suface of the water.
The bridge is suspended from four huge cables,
	each of which contains 26,108 lengths of wire.
Not only is the birdge very strong, but simple and elegant as well.
	
** DONE tell the story 口语复述
CLOSED: [2023-11-19 Sun 20:54]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-19 Sun 20:57]
The bridge I know best is called the Sydney Harbour Bridge.
It joins either side of Sydney Harbour.
From far away it looks like a great arch,
	but when you get near, you can see a great deck under the arch.
It is made of steel and supported by two towers.
If you stand on the bridge early in the morning,
	you can see the Parramatta River to the west and the open sea to the east.
At this time everything is quiet.

During the day, however, the harbour becomes busy with small boats
	and largeships are moving in all directions.
I enjoy standing on the bridge at night
	when you see the magnificent Opera House looking like a great sailing ship.
In the darkness you can see the city lights.
In the stillness the traffic and the movement of the sea are the only sounds that can be heard.

** Topics for discussion
