#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 19 A very dear cat
#+begin_verse
Why was Rastus 'very dear' in more ways than one?

Kidnappers are rarely interested in animals,
	but they recently took considerable interest in Mrs. Eleanor Ramsay's cat.
Mrs. Eleanor Ramsay, a very wealthy old lady,
	has *shared a flat with* her cat, Rastus, for a great many years.
Rastus leads an orderly life.
He usually *takes a short walk* in the evenings and is always home by seven o'clock.
One evening, however, he failed to arrive.
Mrs. Ramsay *got very worried*.
She looked everywhere for him but could not find him.

Three days after Rastus' disappearance, Mrs. Ramsay received an anonymous letter.
The writer stated that Rastus was in safe hands
	and would be returned immediately if Mrs. Ramsay paid a ransom of 1,000 dollars.
Mrs. Ramsay was instructed to place the money in a cardboard box and to leave it outside her door.
*At first*, she decided to *go to the police*,
	but fearing that she would never see Rastus again
	-- the letter had *made that quite clear* --
	she *changed her mind*.
She withdrew 1,000 dollars from her bank and followed the kidnapper's instructions.
The next morning, the box had disappeared
	but Mrs. Ramsay was sure that the kidnapper would keep his word.
*Sure enough*, Rastus arrived punctually at seven o'clock that evening.
He looked very well, though he was rather thirsty, for he drank half a bottle of milk.
The police were astounded when Mrs. Ramsay told them what she had done.
*She explained that* Rastus *was very dear to* her.
*Considering the amount* she paid, he was dear *in more ways than one*!
#+end_verse
** expression
dear: [dɪr] adj.亲爱的;珍贵的;昂贵的
kidnapper: ['kɪdnæpə(r)] n.绑架者,拐骗者
considerable: [kənˈsɪd(ə)rəb(ə)l] adj.相当大的
wealthy: [ˈwelθi] adj. having a lot of money, possessions etc富的,有钱的
orderly: [ˈɔrdərli] adj. arranged or organized in a sensible or neat way有规律的
disappearance: [ˌdɪsəˈpɪrəns] n. disappear v.出现
anonymous: [əˈnɑnɪməs] adj. unknown by name匿名的
ransom: [ˈrænsəm] n.赎金
cardboard: [ˈkɑrdˌbɔrd] n. stiff thick brown paper, used especially for making boxes硬纸板
withdraw: [wɪðˈdrɔ] withdrew withdrawn(从银行)取钱
punctually: adv. on time准时地
astound: [əˈstaʊnd] v. astounded adj.使吃惊

be dear to somebody: 对某人很宝贵
a considerable amount/number of sth.: a lot of很多
in an orderly fashion/manner: in a well-organized and controlled way以有序的方式
anonymous letter/(phone) call: 匿名信/电话
remain anonymous: 匿名
a ransom of + (money): eg. a ransom of $100 ...的赎金
It astounded sb. that + ...: 使某人吃惊的是+...
--------------------
share sth. with sb.: 与某人分享某物
take a short/long walk: 走一小段路
get worried: 变得担心
in safe hands: they are being looked after by a reliable person and will not be harmed得到很好的照顾
at first: 一开始
go to the police: 报警
make sth. clear: 把某事搞的很清楚
change sb's mind: 改变主意
follow sb's instructions: 遵从某人的指示
keep sb's word: 说话算数
sure enough: 当然了
sb. explained that + ...: 某人解释到+...
Considering + n., + ...: 考虑到
in more ways than one: to have more than one meaning不止一种意义

** words
dear [dɪr] adj. 亲爱的；珍贵的；昂贵的
kidnapper ['kɪdnæpə(r)] n. 绑架者，拐骗者
considerable [kənˈsɪd(ə)rəb(ə)l] adj. 相当大的
wealthy [ˈwelθi] adj. 富的，有钱的
orderly [ˈɔrdərli] adj. 有规律的
disappearance [ˌdɪsəˈpɪrəns] n. 失踪
anonymous [əˈnɑnɪməs] adj. 匿名的
ransom [ˈrænsəm] n. 赎金
cardboard [ˈkɑrdˌbɔrd] n. 硬纸板
withdraw [wɪðˈdrɔ] (withdrew [wið'dru:],withdrawn [wið'drɔ:n]) v.(从银行)取钱
punctually ['pʌŋktʃuəli] adv. 准时地
astound [əˈstaʊnd] v. 使吃惊

** vocabulary
rarely: seldom
considerable: a great deal of
wealthy: rich
worried: concerned
stated: said
changed her mind: altered her opinion
word: promise

** DONE 单词造句
CLOSED: [2023-11-23 Thu 20:06]
dear adj.  be dear to somebody
- She explained that the foods in that resturant are good but dear.
- My wife is always very dear to me.
- Sure enough, Leo became a dear friend.
- On the surface, I'm very dear to you.
- I lost the ring which is very dear to me.
kidnapper n.
- In response to kidnapper's request, she paid $1000 to him.
- The kidnapper took no interest in poor man.
- The idea that a kidnapper is always a man is mistaken.
- The police's action was not taken into account by the kidnapper.
- The kidnapper is mistaken about that the man is as strong as a horse.
considerable adj.  a considerable amount/number of sth.
- The artist has made a considerable number of pieces of sculpture.
- Oddly enough, she ran out of a considerable amount of money.
- The archaeologist made a considerable number of discoveries of the mummy.
- There is a considerable number of statues in the famous monastery.
- The monastery makes a considerable amount of money every summar.
wealthy adj.
- The monk coming from a wealthy monastery is asking us for a meal.
- Even she comes from a wealthy family, she couldn't afford to it.
- I haven't bought the house, for the simple reason that I'm not wealthy.
- Imagine her dismay when she found that her boyfriend doesn't come from a wealth family.
- For safekeeping, the wealthy man went to the bank.
orderly adj.  in an orderly fashion/manner
- Because the police is trying to try order, everyone leave in an orderly fashion.
- People waitting in line for a comedy show is leaving in an orderly fashion.
- Fearing that people would be out of control,
		the commander instructed everyone to leave in an orderly fashion.
- I lead an orderly life and went for a short walk in every evenings.
- These ants is moving in a cirlce in an orderly fashion.
disappearance n. disappear v.
- Because of my cat's disappearance, my wife got very worried.
- In spite of her son's disappearance, she still had a lot of patience.
- So long as the policeman arrived on the scene, he will explain her disappearance to you.
- The old lady is conscious of her husband's disappearance.
- My mother will be sensitive about her cat's disappearance.
anonymous adj.  anonymous letter/(phone) call  remain anonymous
- If the article go to press, I must remain anonymous.
- How could you know that I made an anonymous call?
- My classmate accused me of making anonymous calls.
- I denied making anonymous calls.
- I apologized to him for sending an anonymous letter to him.
ransom n.  a ransom of + (money)
- She is unwilling to pay the ransom.
- She realized to her horror that she was asked for the ransom.
- Her son was killed, for she failed to pay the ransom.
- I was ordered to pay a ransom of $1000.
- Oddly enough, the ransom found its way there.
cardboard n.
- My cat must be hiding in that cardboard.
- The worker apologized to me for taking my cardboard boxes without permissions.
- Let's keep the status quo, I'm not gonna throw away thse cardboard boxes.
- In response to the worker's request, I opened the door and give her my cardboard boxes.
- I might be mistaken about the worker who took our cardboard boxes.
withdraw withdrew withdrawn
- The boy withdrew $5 to exchange it for sweets.
- She claimed to have withdrawn only $100 from her saving account.
- You can't withdraw money today because of broken machine.
- You could withdraw your money from you saving account whenever you come here.
- There was a time when people had difficulty in withdrawing money from the bank.
punctually adv.
- Not only do we pay punctually, but we are very polite.
- Not only do they pay punctually, but they carried some fruits to our office.
- Not only do they pay punctually, but they had a good temper.
- Our teacher lost his temper, for you	didn't finish your homework punctually.
- I confirmed that I arrived at the station punctually.
astound v. astounded adj.  It astounded sb. that + ...
- It astounded her that she didn't have an alibi.
- It astounded her that a polite doctor committed a murder.
- It astounded her that he didn't tell the truth.
- It astounded her that a considerable number of workers were trapped in the mine.
- It astounded her that it is not a slip of the tongue.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-23 Thu 20:06]
share sth. with sb.
- He is reluctant to share his pie with his sister.
- You'd better share your room with her.
- She claimed to have shared a flat with a new boyfriend.
- I found my cat sharing her food with the bird.
- I felt obliged to share my room with her.
take a short/long walk
- It convinced me that she had just took a short walk.
- The disabled attempted to take a short walk on his own.
- So long as I have difficult in studying, I will take a short walk in the street.
- The famous actor received a warm welcome while taking a short walk.
- These cats have one thing in common, that they take a short walk in every evenings.
get worried
- She got very worried in a period of time.
- She got very worried, for her son led a mysterious life.
- When she heard the film is based on a true story, she got worried.
- Because of my cat's appearace, I got worried.
- Fearing that I was likely to be fired, I got worried.
in safe hands
- The order was given, your money will be in safe hands.
- On the other hand, your money is in safe hands.
- The kidnappers informed that his cat was in safe hands.
- I was relieved to hear that Leo's company is in safe hands.
- The company is in safe hands, for the agreement is reached about salary.
at first
- At first the police lit up, then he was told that it was only a perfume.
- At first I was greeted by an unpleasant smell from the kitchen.
- At first I thought my house was set on fire.
- At first she claimed to have a perfert alibi.
- At first she saw a puma at large in the remote village.
go to the police
- I received an anonymous letter and felt obliged to go to the police.
- If you kept making anonymous calls, I would go to the police.
- Equipped with a torchlight, she went to the police.
- She was too embarrassed to go to the police.
- It took me a long time to go to the police.
make sth. clear
- I must make it clear that you had better return it or I will call the police.
- Let us make one thing clear -- I have lost $100 worth of ring.
- Let us make one thing clear -- I was too busy working to meet you.
- Let me make it clear that the cat has gained its independence.
- Let me make it clear that parents always make an impact on their children.
change sb's mind
- The order to abandon ship was give, but she didn't change her mind.
- So long as the alarm was given, she would change her mind.
- At first the policeman thought that she died from accident, then he changed his mind.
- If you work hard, your wife may change her mind.
- After greeted by a peculiar smell, the officer changed his mind.
follow sb's instructions
- If you had followed our instructions, you wouldn't have made such stupid remarks.
- Don't feel guilty, even if you didn't follow our instructions exactly.
- She was made to follow our instructions.
- Oddly enough, the boy managed to follow his father's instructions.
- I'm genuinelly sorry that we don't follow your instructions.
keep sb's word
- I was relieved to hear that she kept her word.
- Even though she didn't keep her word, she didn't feel guilty.
- I wished that you had kept your word.
- I will kept my word and give you fifty pence.
- For your own protection, you should keep your word.
sure enough
- Sure enough, they gave him a state funeral.
- Sure enough, she is going to dedicate herself to gardening.
- Sure enough, the cat is wandering outside punctually.
- She was unconscious of failing the exam sure enough.
- Sure enough, she broke the world record.
sb. explained that + ...
- I explained that everyone had the opportunity to meet her.
- She explained that the cat starved to death.
- I explained that my cat was wandering outside.
- She explained that she had a perfect alibi.
- She explained that she didn't set the museum on fire.
Considering + n., + ...
- Considering the fact that his company made a profit, she felt relieved.
- Considering the slow pace of life in the country, she moved to it.
- Considering a ransom of $1000, she withdrew it from her saving account.
- Considering his wife's dismay, he didn't go to the party.
- Considering eletric shocks, she didn't touch it any more.
in more ways than one
- You did give me a surprise in more ways than one.
- You make me comfortable in more ways than one.
- She is a winner in more ways than one.
- They will give your shocks in more ways than one.
- My cat is very dear to me in more ways than one.
** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-23 Thu 20:06]
** DONE Ask me if 写+读
CLOSED: [2023-11-23 Thu 20:15]
1. Kidnappers took an interest in Mrs. Ramsay's cat. Why
	 Why did kidnappers take an interest in Mrs. Ramsay's cat?
2. She has shared a flat with her cat for a great many years. Who
		Who has shared a flat with her cat for a great many years?
		Who has she shared a flat with for a great many years?
3. Rastus leads an orderly life. What kind of life
		What kind of life does Rastus lead?
4. He usually takes a short walk in the evenings. When
		When does he usually take a short walk?
5. Mrs. Ramsay got very worried one evening. Why
		Why did Mrs. Ramsay get very worried one evening?
6. She received an anonymous letter. What
	 What did she receive?
7. She withdrew $1000 from her bank. How much
	 How much did she withdraw from her bank?
8. The box had disappeared. Why
	 Why had the box disappeared?
9. He drank half a bottle of milk. How much milk
	 How much milk did he drink?
10. The police were astounded. Why
		Why were the police astounded?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-23 Thu 20:34]
Mrs. Ramsay received an anonymous letter three days after her cat's disappearance.
The writer of the letter demanded $1000 for the return of the cat,
	and warned that she would never see her cat again if she went to the police.
She had to put the money in a cardboard box and leave it outside her door.
After drawing $1000 from her bank, she acted on the kidnapper's instructions.
The money disappeared the following morning,
	and Rastus returned at seven o'clock that morning.

** DONE tell the story 口语复述
CLOSED: [2023-11-23 Thu 20:39]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-23 Thu 20:41]
In a bar one night, Mr. X was talking to a workman
	who told him that he often worked in Mrs. Ramsay's flat.
The workman added that Mrs. Ramsay was wealthy and she lived alone with her cat.
Every day, Mr. X stood outside Mrs. Ramsay's block of flats.
As the cat took a short walk every evening, he saw that it had regular habits.

He found out as much as he could about Mrs. Ramsay and learnt that she loved this cat very much.
One evening, as the cat was leaving the block of flats, he kidnapped it.
He took the cat to a secret address.
During the next three days, he walked past Mrs Ramsay's flat on several occasions
	and noticed that no other cat ever appeared.
Now he was sure he had the right cat, so he wrote a letter in which he stated his demands.

** Topics for discussion
