#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 20 Pioneer pilots
#+begin_verse
What was the name of the first plane to fly across the English Channel?

In 1908 Lord Northcliffe *offered a prize of 1,000 dollars to the first man*
	who would fly across the English Channel.
Over a year passed before the first *attempt was made*.
On July 19th, 1909, in the early morning,
	Hubert Latham took off from the French coast in his plane the 'Antoinette IV'.
He had travelled only seven miles across the Channel
	when his engine failed and he *was forced to* land on the sea.
The 'Antoinette' floated on the water until Latham *was picked up by* a ship.

Two days later, Louis Bleriot arrived near Calais with a plane called 'No. XI'.
Bleriot had been making planes since 1905 and this was his latest model.
A week before, he had completed a successful overland flight
	during which he covered twenty-six miles.
Latham, however, did not give up easily.
He, too, arrived near Calais *on the same day* with a new 'Antoinette'.
*It looked as if* there would be an exciting race across the Channel.
Both planes were going to take off on July 25th, but Latham failed to get up early enough.
After making a short test flight at 4.15 a.m., Bleriot set off half an hour later.
His great flight lasted thirty-seven minutes.
When he landed near Dover, the first person to greet him was a local policeman.
Latham made another attempt a week later and got within half a mile of Dover,
	but he was unlucky again.
His engine failed and he landed on the sea for the second time.
#+end_verse
** expression
pioneer: [ˌpaɪəˈnɪr] n. someone who is important in the early development of something, and whose work or ideas are later developed by other people先驱
lord: [lɒrd] n. a man who has a rank in the aristocracy勋爵
Calais: [kæ'leɪˌ 'kæleɪ] n.(法国港市)
overland: [ˈoʊvərˌlænd] adj. adv.across land, not by sea or air陆上的
--------------------
as if/though: 虚拟语气
--------------------
offer sth. to sb. = offer sb. sth.: provide sth. for sb.; provide sb. with sth.提供某物给某人
a prize of + (money): eg. a prize of $1,000多少的奖金
make an attempt to do sth.: attempt to do sth; try to do sth.尝试做某事
attempt to do sth.: 尝试做某事
be forced to do sth.: be made to do sth.被迫做某事
be picked up by ...: be rescued by被...营救
on the same day: 在同一天
It looked as if/though + 虚拟句:
	eg.	It looked as if there would be an exciting race across the Channel.
	eg.	It looked as though there would be an exciting race across the Channel.

** words
pioneer [ˌpaɪəˈnɪr] n. 先驱
lord [lɒrd] n. 对（英国）贵族的尊称；勋爵
Calais [kæ'leɪ] n. 加来（法国港市）
overland [ˈoʊvərˌlænd] adj. 陆上的

** vocabulary
forced to land: obliged to come down
picked up: rescued
completed: finished
covered: completed flown
test: trial
set off: started out; began his journey
failed: didn't work; stopped

** DONE 单词造句
CLOSED: [2023-11-24 Fri 20:46]
pioneer n.
- The pioneer had made that quite clear.
- The pioneer was carrying a basket of fruits to us.
- Following in his father's footstep, he became a pioneer of computer science.
- The pioneer decided to go to the police.
- He stated that the pioneer was in safe hands.
lord n.
Calais
overland adj. adv.
- Considering the dear ticket, she decided to travel overland to Beijing.
- At first, she decided to travel overland to Beijing.
- She spent a lot of time traveling overland to China.
- It astounded us that he travelled overland to Beijing.
- The trip was designed to travel overland to Shanghai.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-25 Sat 19:54]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-24 Fri 20:46]
offer sth. to sb. = offer sb. sth.
- The artist offered a sculpture to his son.
- I will offer a considerable amount of money to my daughter.
- I am mistaken about offering her some cardboard boxes.
- Oddly enough, she offered her some cardboard boxes.
- She offer a meat to the beggar in response to his request.
a prize of + (money)
- Oddly enough, Leo has made a prize of $1000.
- She managed to create a sculpture and won a prize of $1000.
- If you don't win a prize of $1000, I will give you electric shocks.
- Little is known about Leo who won a prize $1000.
- The player has won a prize of $1000 in a span of this year.
make an attempt to do sth.  attempt to do sth.
- She made an attempt to tell him about her stories.
- It's ture that she made an attempt to pass the exam, but she failed.
- I was astonished to find that she made an attempt to accuse her father of stealing.
- I made an attempt to reward him with a prize of $1000.
- She made an attempt to offer us a special type of fish.
be forced to do sth.
- I was forced to rub him with a special type of mixture.
- She was forced to hear about his story.
- I was forced to roll up my sleeves.
- She was forced to exchange her pocket money for sweets.
- I was forced to make money.
be picked up by ...
- She was picked up by a ship out at sea.
- I will be picked up by my father at the station.
- A large sums of money was picked up by the vicar.
- There was a time when drunk women were picked up by beggars outside the bar.
- She dedicated herself to pick up tea.
on the same day
- On the same day, he was given a state funeral by people in China.
- On the same day, the detectives were keeping guard.
- On the same day, the boat was loaded with a mixture of oil and water.
- On the same day, the perfume was exampted from import duty.
- On the same day, she was made to smoke.
It looked as if/though
- It looked as if you woke up with a start last night.
- It looks as if she is regarded as unsinkable.
- It looks as though the commander has given an order.
- It looks as if she has made tremendous mistakes.
- It looks as if the beggar is in difficulty.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-25 Sat 19:54]
** DONE Ask me if 写+读
CLOSED: [2023-11-25 Sat 20:04]
1. Lord Northcliffe offered a prize of $1000. Why
	 Why did Lord Northcliffe offer a prize of $1000?
2. Hubert Latham took off from the French coast in 1909. When
		When did Hubert Latham take off from the French coast?
3. He had travelled seven miles when his engine failed. How far
		How far had he travelled when his engine failed?
4. He was forced to land on the sea. Where
		Where was he forced to land?
5. Bleriot had been making planes since 190- How long
		How long had Bleriot been making planes?
6. He had completed a successful overland flight a week before. When
	 When had he completed a successful overland flight?
7. It looked as if there would be an exciting race. Why
	 Why did it look as if there would be an exciting race?
8. Both planes were going to take off on July 25th. When
	 When were both planes going to take off?
9. Bleriot set off at 4.45 a.m. When
	 When did Bleriot set off?
10. His flight lasted thirty-seven minutes. How long
		How long did his flight last? 

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-25 Sat 20:14]
Bleriot and Latham arrived in Calais on July 21st, 1909.
Though it looked as if there would be a race across the Channel on July 25th,
	Latham didn't take part, because he didn't get up early enough.
After making a short test flight,
	Bleriot crossed the Channel in thirty-seven minutes.
A policeman greeted him when he arrived in Dover.
Latham got within half a mile of Dover the following week.
	having to land on the sea for the second time because his engine failed.

** DONE tell the story 口语复述
CLOSED: [2023-11-25 Sat 20:20]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-25 Sat 20:24]
It was early morning.
I looked around, but there was no sign of Latham, so l decided to go on a test flight first.
At 4.15, I took off and flew over Calais for fifteen minutes.
When I landed there was still no sign of Latham.
At 4.45 I took off again.
This time I was determined to fly across the Channel.
When I looked down there was no sign of the ship below,
	which was supposed to be following me,
	I suddenly felt alone and was worried whether I was flying in the right direction.
All I could see was sea and sky.

I could feel the high winds against the plane and the engine got very hot.
Fortunately, it began to rain and the rain cooled my engine.
Suddenly, I could see land ahead.
Dover! I flew over Dover, looking for somewhere to land.
I saw a field below and brought the plane down.
I was still sitting in the cockpit,
	hardly able to believe the flight was so successful
	-- just thirty-seven minutes to cross from Calais --
	when a British policeman arrived.
He smiled broadly at me and said,'Good morning!
I smiled back and said, 'Bonjour!'

** Topics for discussion
