#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 21 Daniel Mendoza
#+begin_verse
How many unsuccessful attempts did Mendoza make before becoming Champion of all England?

Boxing matches were very popular in England two hundred years ago.
In those days, boxers fought *with bare fists* for prize money.
*Because of this*, they were known as 'prizefighters'.
However, boxing was very crued, for there were no rules
	and a prizefighter could be seriously injured or even killed during a match.

One of the most colourful figures in boxing history was Daniel Mendoza, who *was born in* 1764.
The use of gloves was not introduced until 1860,
	when the Marquis of Queensberry *drew up* the first *set of* rules.
Though he was technically a prizefighter,
		Mendoza did much to *change crude prizefighting into a sport*,
	for he *brought science to the game*.
*In his day*, Mendoza enjoyed tremendous popularity.
He was adored by rich and poor alike.

Mendoza *rose to fame* swiftly after a boxing match when he was only fourteen years old.
This attracted the attention of Richard Humphries,
	who was then the most eminent boxer in England.
He offered to train Mendoza and his young pupil *was quick to learn*.
*In fact*, Mendoza soon became so successful that Humphries *turned against him*.
The two men *quarrelled bitterly*
	and *it was clear that* the *argument could only be settled* by a fight.
A match was held at Stilton, where both men fought for an hour.
The public *bet a great deal of money on Mendoza*, but he was defeated.
Mendoza met Humphries in the ring on a later occasion and he lost for a second time.
*It was not until* his third match in 1790
	that he finally beat Humphries and became Champion of England.
Meanwhile, he founded a highly successful Academy and even Lord Byron became one of his pupils.
He earned enormous sums of money and was paid *as much as* 100 dollars for a single appearance.
Despite this, he was so extravagant that he *was always in debt*.
After he was defated by a boxer called Gentleman Jackson, he was quickly forgotten.
He was sent to prison for failing to pay his debts and died *in poverty* in 1836.
#+end_verse
** expression
boxing: [ˈbɑksɪŋ] n.拳击
boxer: [ˈbɑksər] n.拳击手
bare: [ber] adj. not covered with clothes赤裸的
prizefighter: [ˈpraɪzˌfaɪtər] n.古拳手
crude: [krud] adj. rude and offensive粗野的
marquis: [mɑrˈki] n. has a rank between duke and earl侯爵
technically: [ˈteknɪkli] adv.严格根据法律意义地
science: [ˈsaɪəns] n.科学
popularity: [ˌpɑpjəˈlerəti] n.名望
adore: [əˈdɔr] v. to love someone very much and feel very proud of them崇拜,爱戴
alike: [əˈlaɪk] adv. in a similar way  adj. very similar not before noun一样地
fame: [feɪm] n.名声
eminent: [ˈemɪnənt] adj. an eminent person is famous, important, and respected著名的,杰出的
bitterly: [ˈbɪtərli] adv. very厉害地
bet: [bet] bet betted v. to risk money on the result of a race, game, competition, or other future event打赌
academy: [əˈkædəmi] n.专业学校
extravagant: adj. spending or costing a lot of money, especially more than is necessary or more than you can afford浪费的,奢侈的
poverty: [ˈpɑvərti] n.贫困

with sb's bare hands: using only one's hands and no tools or weapons赤手空拳地
Technically speaking, + ...: According to the rules严格意义上说
gain/grow/increase in popularity:  something or someone is liked, enjoyed, or supported获得欢迎
great minds think alike: 英雄所见略同
rise to fame: make a name for oneself变得出名
quarrel/complain/be disappointed ... + bitterly: 吵架剧烈
bet ($) on sth.: 在某事打赌多少钱
I bet + ...: 我赌 + ...
live in poverty: 生活贫困
--------------------
Because of + n.: 因为某物
be born in + (year): 出生于
draw up: 起草
a set of sth.: a series of; a trail of一系列某物
change a. into b.: 把A变成B,而 exchange A for B是交换
bring a. to b.: eg. brought science to the game把A带给B
in sb's day: 在他的时代
be quick to do sth.: 很快做某事
in fact: 实际上
turn against sb.: 与某人反目
It is clear that + ...: 很明显
settle the argument: 解决争端
It was not until [stp.] that + ...: 直到某事+...
	stp. can not only be 'in 1790' but also 'third match' as well
as much as ...   half as much as: 一样多,一半多
be in debt: owe money在欠债

** words
boxing [ˈbɑːksɪŋ] n. 拳击
boxer [ˈbɑːksər] n. 拳击手
bare [ber] adj. 赤裸的
prizefighter [ˈpraɪzfaɪtər] n. 职业拳击手
crude [kruːd] adj. 粗野的
marquis [ˈmɑːrkwɪs] n. 侯爵
technically [ˈteknɪkli] adv. 严格地;技术地
science [ˈsaɪəns] n. 科学
popularity [ˌpɑːpjuˈlærəti] n. 名望
adore [əˈdɔːr] v. 崇拜,爱戴
alike [əˈlaɪk] adv. 一样地
fame [feɪm] n. 名声
eminent [ˈemɪnənt] adj. 著名的
bitterly [ˈbɪtərli] adv. 厉害地
bet [bet] v. 打赌
academy [əˈkædəmi] n. 专业学校
extravagant [ɪkˈstrævəɡənt] adj. 浪费的
poverty [ˈpɑːvərti] n. 贫困的

** vocabulary
bare: without gloves
injured: hurt
drew up: prepared and wrote
crude: basic, rough , not very skillful
enjoyed tremendous popularity: was extremely popular
adored: loved and respected
alike: in the same way

** DONE 单词造句
CLOSED: [2023-11-26 Sun 16:26]
boxing n.
- They will fight against each other in the boxing match.
- The police will have a difficult time in keeping order during the boxing match.
- He made a name for himself and became a boxing champion of the world.
- The boxing is so dangerous that it should be banned in US.
- These days, the boxing is very popular with young man.
boxer n.
- The boxer was picked up by police at the station.
- On the same day, the boxer was defeated.
- It looked as if he used to a boxer.
- We are gonna offer a prize of $1000 to the boxer.
- The boxer attempted to kick his rival's ass.
bare adj. not covered with clothes  with sb's bare hands
- I was allowed to walk on the floor with bare feet.
- She explained that the boxers fought with each other with bare fists.
- You should not carry the fruits to there with bare hands.
- It was not long before she walked on the beach with bare feet.
- A group of children walked on the squre with bare feet.
prizefighter n.
- The prizefighted was asked to pay a ransom of $1000.
- The prizefighter stated that he had received an anonymous letter.
- It was said that the cat was very dear to the prizefighter.
- It was rather like a prizefighter in boxing match.
- The prizefighter studied English on and off.
crude adj. rude and offensive
- The man was so crude that no one wanted to talk to him.
- You are mistaken about your crude behavior.
- Because of his crude languages, everyone took no interest in the drama.
- Oddly enough, she was not crude any more.
- The crude man may give you some eletric shocks.
marquis
technically adv.  Technically speaking, + ...
- Technically, this suspension bridge hadn't fulfilled his dream.
- Technically, the bridge are suspended from the towers.
- Technically, it will be only a third of its full capcity.
- Technically, the microphone isn't connected to the tower.
- Technically speaking, it's not my fault.
science n.
- It is said the film is based on science.
- I was astonished to find that they don't teach science at school anymore.
- It's ture that they don't teach science at school,
		but they still enjoyed a high level of civilization.
- My nephew always asks me to tell him about science stories.
- She denied that she teaches science at school.
popularity n.  gain/grow/increase in popularity
- These days, the group of pop singers is growing in popularity.
- However, after he stayed out of limelight, he gained in popularity.
- On the otherhand, prepared dishes are growing increase in popularity in China.
- This special kind of sweet is increasing in popularity.
- The boxer who was defeated in the boxing match is growing in popularity.
adore v.
- After fulfulling his dream that he built this bridge, he was adored by rich and poor alike.
- People who go a long way are ususally adored by their parents.
- I appreciate that you adore me.
- Why don't you adore that dress?
- As long as you adore him, you will believe in him.
alike adv. in a similar way  adj. very similar not before noun  great minds think alike
- It is said, great minds think alike.
- In times of peace, these two countries are alike in many ways.
- The behaviors of monkeys and people are alike in many ways.
- Both of them made large sums of money alike.
- These pop singers made names for themself alike.
fame n.  rise to fame (=make a name for oneself)
- Though she decided to stay out of limelight, she rised to fame swiftly.
- The titanic was regarded as unsinkable and rose to fame.
- The woman rised to fame as a teacher when she returned to China.
- She rose to fame when she was very young, for she used to be an actress.
- He made a discovery of a special type of fish and rose to fame.
eminent adj.
- Little is known about the eminent detective, for she remains anonymous.
- Not everything is known about the eminent actor who dated back to fifty century.
- On his way to home, the eminent lawyer decided to go to the police.
- As he made an such tremendous mistake, the eminent lawyer was put out of business.
- The eminent detective was mistaken about the fact that she didn't have a perfect alibi.
bitterly adv.  quarrel/complain/be disappointed ... + bitterly
- He was disappointed bitterly to find that the detective still remained anonymous.
- They needn't have quarrel bitterly.
- I complained bitterly that my wife spend too much money.
- I complained bitterly that the exhibition was prehistoric.
- I complained bitterly that she was mistaken about her child.
bet - bet betted v.  bet ($) on sth.  I bet + ...
- During the boxing match, I have bet $1000 on Anna.
- I bet you takes no interest in fishing.
- I bet she will cry in response to your yelling.
- I bet these lights will go on and off.
- I bet she managed to quit smoking.
academy n.
- Leo and Berlin was able to found an academy.
- I will be studying English at that academy.
- I'm going to that academy tomorrow.
- It was at that academy that you gave me electric shocks.
- It is my job to create a sculpture at the academy.
extravagant adj.
- I complained bitterly that my wife was so extravagant.
- She was so extravagant that she was always in debt.
- Oddly enough, the dustman led an extravagant.
- The kidnappers took interest in the woman who led an extravagant life.
- Little is known that the woman who used to lead an extravagant life.
poverty n.  live in poverty
- Because he was fired, he lived in poverty.
- She did by no means live in poverty.
- Little is known that the dustman who lives in poverty.
- She is ashamed of living in poverty.
- It is said that billions of people in China still live in poverty in 21 century.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-11-27 Mon 20:02]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-11-26 Sun 17:02]
Because of + n.
- Because of the ransome of $1000, she lived in poverty.
- Because of bad behaviours, the eminent lawyer was put out of business.
- Because of the suspension bridge, we arrived here on time.
- Because of good education, she passed the exam.
- Because of good salary, she is going to work for the corporation next year.
be born in + (year/place)
- It is said that she is born in 1993.
- Although she was borin in China, she leads an extravagant life in America.
- On her way to home, her son was born in the car.
- He was born in Xiabu, which is a remote village in China.
- The baby should be born in NewYork.
draw up
- There was a time when a set of rules was drawn up.
- After they reach an agreement, they drew up a set of plans.
- We will draw up plans in the meeting.
- These two countries who were at war with each other drew up a set of plans.
- The eminent volunteered to draw up a set of rules.
a set of sth.
- A set of toys was abandoned in the park.
- For your own protection, you need to wear a set of special types of clothes.
- She dedicated herself to a set of laws.
- A set of rules was drawn up in memory of the eminent lawyer.
- I am impatient to clean a set of keys.
change a. into b.
- The insect was supposed to be changed into a butterfly.
- I'm glad that you are changed into stone.
- I wished that you had been changed into stone.
- I was disappointed to find that my cat wasn't able to be changed into a beauty.
- The body of animals was changed into soils.
bring a. to b.
- The prizefighter managed to bring science to boxing.
- Could I bring my friends to the party?
- He asked me to bring everything to him.
- I refused to bring everything to him.
- They succeeded in bringing peace to this country.
in sb's day
- In his day, he drawn up a set of laws.
- In his day, a number of boxers was defeated by him.
- In his day, he made a large sums of money.
- In his day, he dedicated himself to education.
- In his day, he was adored by poor and rich alike.
be quick to do sth.
- The teacher explained that children is usually quick to learn that adults.
- Be patient. And you will be quick to deal with that.
- The child was quick to build a wood bridge.
- The eminent lawyer was quick to solve the problem.
- She was quick to get used to her work.
in fact
- In fact, I had an opportunity to talk to Leo.
- In fact, there is an element of truth in this idea that cats have nine lives.
- In fact, I starved to death at that time.
- In fact, I was genuinely sorry that I made such stupid remarks.
- In fact, the boat was loaded with diamonds.
turn against sb.
- The brothers turned against each other because of the house.
- They needn't have turned against each other.
- Why didn't you turn against with him.
- I wished that they hadn't turned against each other.
- They quarrelled bitterly and turned against each other.
It is clear that + ...
- It is clear that I didn't form an unrealistic picture of America.
- It is clear that the bag was full of sand and stone.
- It is clear that the order has been given.
- It is clear that our baby woke up with a start.
- It is clear that there is not shortage of water and foods.
settle the argument
- They should have settled the argument.
- They will settle the argument in the meeting.
- They have one thing in comman: they all want to settle the argument in peaceful way.
- If you didn't keep touch in each other, you wouldn't have settled the argument.
- I wished that the argument was settled in peaceful way.
It was not until ... that + ...
- It was not until 2015 that I gradated from university.
- It was not until that afternoon that she apologized to me.
- It was not until 2015 that she led an extravagant life.
- It was not until 1993 that she died of cancer.
- It was not until 2000 that the great ship sunk out at sea.
as much as ...   half as much as
- It rises to as much as 17 miles.
- Be enthusiasm as much as you can when you study English.
- You should use English as much as you can.
- My wife said it was cheap, but it costed me as much as $1000.
- The great ship has as much as 17 watertight compartments.
be in debt
- Although he led an extravagant life, he was usually in debt.
- She had to offer him her naked pictures, for she was in debt.
- It seems as if she was in debt these days.
- She is likely to be in debt.
- These women have one thing in common: they all are in debt.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-11-27 Mon 20:02]
** DONE Ask me if 写+读
CLOSED: [2023-11-27 Mon 20:08]
1. Boxing matches were popular 200 years ago. When
	 When were boxing matches popular?
2. A prizefighter could be killed during a match. Why
		Why could a prizefighter be killed during a match?
3. Daniel Mendoza was born in 176- Who
		Who was born in 1764?
4. Mendoza brought science to the game. What
		What did Mendoza bring to the game?
5. He was tremendously popular in his day. How popular
		How popular was he in his day?
6. Humphries offered to train young Mendoza. What
	 What did Humphries offer to do?
7. The men's argument could only be settled by a fight. How
	 How could the men's argument only be settled?
8. Humphries beat Mendoza twice. How many times
	 How many times did Humphries beat Mendoza?
9. Lord Byron was one of Mendoza's pupils. Who
	 Who was one of Mendoza's pupils?
10. Mendoza was sent to prison for failing to pay his debts. Why
		Why was Mendoza sent to prison?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-11-27 Mon 20:21]
Because Mendoza rose to fame swiftly after a boxing match,
	Richard Humphries offered to train the pupil.
He became so successful that the two men quarrelled bitterly.
Both men fought at a match, but Mendoza was defeated.
On a later occasion they met in the ring and Mendoza was defeated for another time.
Until 1790 he finally beat Humphries and became Champion of England.
Although he founded a highly successful Academy and earned enormous sums of money,
	he was so extravagant that he was always in debt.
He was sent to prison for failing to pay his debts and died in 1836.

When the two men quarrelled, they settled the arugment by a fight.
This took place at Stilton.
It lasted an hour and Humphries won.
When they met again, Mendoza lost again, but in their third match in 1790,
	Mendoza finally beat Humphries to become Champion of England.
He founded a successful boxing Academy and earned a lot of money,
	but was so extravagant he was always in debt.
He was finally sent to prison and died in porverty in 1836.

** DONE tell the story 口语复述
CLOSED: [2023-11-27 Mon 20:24]
** DONE composition 阅读 或 写作
CLOSED: [2023-11-27 Mon 20:28]
The first fight between Humphries and his pupil Mendoza,
	after a quarrel,
	was held at Stilton and attracted a lot of attention.
At the time, Richard Humphries was the most eminent boxer in England and had many supporters.
But the young Mendoza had his supporters, too.
The atmosphere before the fight was electric.
Half of the people there made bets on Humphries,
	the other half bet on Mendoza.
When the two fighters entered the ring,
	there was a lot of shouting and cheering.
The referee called both fighters to the middle of the ring,
	spoke to them and the fight started.
At first, both men were very wary.

After all, this was a fight between teacher and pupil
	so they knew very well what the other could do
	---- and they were fighting with bare fists.
Each of the boxers fought well for most of the match,
	but in the end Humphries was too strong and too experienced for the young Mendoza.
He knocked him down once: Mendoza got up.
He nocked him down again, and although Mendoza tried to get up, he just couldn't.
The referee counted ten and that was the end of the match.
When Mendoza got up, he was very angry, but eventually congratulated Humphries.
However, his defeat made him determined to go on and fight his teacher again
	so that he could finally become champion.

** Topics for discussion
