#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 25 The Cutty Sark
#+begin_verse
What piece of bad luck prevented the Cutty Sark from winning the race?

One of the most famous sailing ships of the 19th century,
	the Cutty Sark, can be seen at Greenwich.
She stands on dry land and is visited by thousands of people each year.
She serves as an impressive reminder of the great ships of the past.
Before they *were replaced by* steamships,
	sailing vessels like the Cutty Sark were used to carry tea from China and wool from Australia.
The Cutty Sark was one of the fastest sailing ships that has ever been built.
The only other ship to match her was the Thermopylae.
Both these ships set out from Shanghai on June 18th, 1872 on an exciting race to England.
This race, which went on for exactly four months, was the last of its kind.
It marked the end of the great tradition of ships with sails and *the beginning of a new era*.

The first of the two ships to reach Java after the race had begun was the Thermopylae,
	but on the Indian Ocean, the Cutty Sark *took the lead*.
It seemed certain that she would be the first ship home,
	but during the race she had a lot of bad luck.
In August, she *was struck by* a very heavy storm during which her rudder was torn away.
The Cutty Sark rolled *from side to side* and it *became impossible to* steer her.
A temporary rudder was made on board from spare planks and it *was fitted with great difficulty*.
This greatly reduced the speed of the ship,
	for *there was a danger that* if she travelled too quickly,
	this rudder would be torn away as well.
Because of this the Cutty Sark *lost her lead*.
After crossing the Equator,
	the captain called in at a port to have a new rudder fitted,
	but by now the Thermopylae was over five hundred miles ahead.
Though the new rudder was fitted at tremendous speed, it was impossible for the Cutty Sark to win.
She arrived in England a week after the Thermopylae.
Even this was remarkable, considering that she had had so many delays.
*There is no doubt that* if she had not lost her rudder she would have won the race easily.
#+end_verse
** expression
impressive: [imˈprɛsiv] adj. makes you You careless mistakes may manifest as the loss of money of our company one dayadmire it because it is very good, large, important etc给人深刻印象的
steamship: [ˈstimˌʃɪp] n.蒸汽轮船
vessel: [ˈves(ə)l] n. a ship or large boat轮船,大木船
era: [ˈɪrə] n.时代
Java: [ˈdʒɑvə] n.
rudder: [ˈrʌdər] n. a flat part at the back of a ship or aircraft that can be turned in order to control the direction in which it moves舵
roll: [roʊl] v.滚动
steer: [stɪr] v. to control the direction a vehicle is going, for example by turning a wheel掌握方向
temporary: [ˈtempəˌreri] adj.临时的
plank: [plæŋk] n.木板
fit: [fɪt] v.安装
equator: [ɪ'kweɪtə(r)] n.赤道
delay: [dɪˈleɪ] n.延误

a new era/ the beginning/end of an era: 新时代
A be fitted with B: A被装上了B
delay doing sth.: 延迟做某事
--------------------
A be replaced by B: A被B替换
take the lead (in doing sth.) lose one's lead: 领先做某事 失去领先
be struck by: to be very impressed by被...所打动
from side to side: moving to the left and then to the righ左右摇晃
it become impossible to do sth.: 做某事变得不可能
with great difficulty: 非常困难地
There is a danger that + ...: 有...的危险
call in on/at: visit拜访
by now: 目前为止
There is no doubt that + ...: 毫无疑问

** words
impressive [ɪmˈpresɪv] adj. 给人印象深刻的
steamship [ˈstiːmʃɪp] n. 蒸汽轮船
vessel [ˈves(ə)l] n. 轮船,大木船
era ˈɪrə n. 时期,时代
Java [ˈdʒɑːvə] n.爪哇
rudder [ˈrʌdər] n.舵
roll [roʊl] v.颠簸,摇摆
steer [stɪr] v.掌握方向
temporary [ˈtempəreri] adj.临时的
plank [plæŋk] n.大块木板
fit [fɪt] v.安装
equator [ɪˈkweɪtər] n.赤道
delay [dɪˈleɪ] n.耽误

** vocabulary
reminder: something that makes you remember
match: be equal to
era: an age or period
struck: hit
steer: guide
temporary: lasting for a short time
on board: on the ship

** DONE 单词造句
CLOSED: [2023-12-07 Thu 19:33]
impressive adj.
- There is a very impressive monument at NewYork Harbour.
- The longest suspension bridge in the world makes his achievement more impressive.
- He is so impressive that he hitchhiked to Paris when he was very young.
- The local grocer who has repaired the clock is very impressive.
- The order to abandon ship in the movie is very impressive.
steamship n.
- He realized to his horror that the steamship was stuck by a huge iceberg.
- The authorities have loaded the steamship with tea from China.
- Waking up with a start, he found himself tied to a chair in a steamship.
- On the one hand, he was the captain of the steamship.
- We were greeted by an unpleasant smell while we boarded the steamship at first.
vessel n.
- It is said that he set the sailing vessel on fire.
- He ordered his men to break down the sailing vessel.
- I felt guilty when I smoke on the vessel after I had quitted.
- I was made to clean up the vessel.
- As soon as the man boarded on the vessel, he lit up a cigrette.
era n.  a new era/ the beginning/end of an era
- The purchase of the cat marked the beginning of a new era.
- The moment when we lived abroad marked the beginning of a new era.
- The death of my grandfather marked the end of an era.
- We often form an unrealistic picture of a great man whose death marked the end of an era.
- The sad truth is that his death marked the end of an era.
Java n.
rudder n.
- It is my job to fix rudders in my youth.
- There is an element of truth in the idea that we should not touch the rudder.
- I am genuinely sorry that I haven't fixed the rudder.
- If we had to wait until you had fixed the rudder, we would have starved to death.
- I wished that the captain had had the rudder fixed.
roll v.
- My stomach would turn if the boat were rolling.
- I was sick to my stomach while the boat was rolling.
- The ship rolled so hard that we couldn't steer it.
- The harder the ship rolls, the more abuse the captain receives.
- Boarding a ship which rolls from side to side never appeal to me.
steer v.
- I noticed him steering the car with one hand.
- Much to my surprise, he was steering with one hand at tremendous speed.
- Because he is always steering with one hand, he has received many abuse.
- The sad truth is that he is too drunk to steer boat.
- My uncle was anxious to steer his new car after he had passed the test.
temporary adj.
- I told my wife it's temporary that we live in the apartment.
- I will read the pirate stories to you, but it's only temporary.
- You should have considered a temporary work until you decided what you want to do.
- Don't expect me to give you the cardboard boxes, it's only temporary.
- Although repairing bicycle is my temporary job, I took it seriously.
plank n.
- You are expected to fix the rudder with these planks.
- I am made to build the bridge with these planks.
- She stared at the bridge which is made of planks.
- Much to her surprise, the long bridge is made of planks.
- She insisted that the bridge should be made with planks.
fit v.  a. be fitted with b.
- It is said that each room of the hotel was fitted with a secret hole.
- I am about to fit the room with a lamb.
- The room which was not fitted with any lamb ruined my night.
- Imagine his dismay when he found that the room could be fitted with microwave oven.
- It is all very well the building would be fitted with elevator.
equator n.
delay n.  delay in doing sth.
- My wife is always delaying in taking a shower.
- Why do you delay in going to bed over and over again?
- I complained that my wife delayed in going to bed once more.
- In my youth, I never delayed in finishing my homework.
- Oddly enough, the train delayed in arriving.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-07 Thu 19:47]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-07 Thu 19:33]
a. be replaced by b.
- These days, watches have basically been replaced by mobile phones.
- The sad truth is that I'll be replace by AI.
- If you don't work hard, you will be replaced by someone who takes job seriously.
- Many workers in China have already been replaced by robots.
- The paper written out in full has been replaced by a blank sheet of paper.
take the lead (in doing sth.) lose one's lead
- I always took the lead in studying in my youth.
- We don't expect you to take the lead in your class.
- We don't have cause to take the lead in this.
- If you learn the lines by heart, you may take the lead.
- It is esay for you to lose your lead in class.
be struck by
- The man who was struck by lightening yet only suffered from a broken tooth.
- He explained that he was struck by a car.
- He was struck by his father in more ways than one.
- The man was struck by lightening and got very worried.
- He claimed to have been strucked by lightening three times.
from side to side
- He is dancing from side to side.
- The woman who danced from side to side won a prize of $1000 at the party.
- I made an attempt to wave my hands from side to side.
- It looked as if he shook his head from side to side.
- The cat on show is taking a stroll from side to side.
it became impossible to do sth.
- It became impossible to get out of it.
- It became impossible to have a perfert alibi.
- It became impossible to get a ransom of $1000.
- It became impossible to remain anonymous any more.
- It became impossible to stay married.
with great difficulty
- The injured man went to the police with great difficulty.
- The disabled took a long walk with great difficulty.
- It astounded me that she managed to break the world record with great difficulty.
- The cat is dear to me with some difficulty.
- The crowd left the theatre in an orderly fashion with great difficulty.
There is a danger that + ...
- There is a danger that she has changed her mind.
- There is a danger that he would follow in his father's footstep.
- There is a danger that she would never see her cat again.
- There is a danger that we might run into serious trouble.
- There is a danger that the family has a skeleton in the cupboard.
call in on/at
- I am gonna calling in on Lee on Saturday.
- Following my father's instructions, I called in on aunt, Lily.
- I will keep my word and call in at the museum on Saturday.
- Would you like call in at the shop for a cap of milk tea?
- He never calls in at home on duty.
by now
- I have remained anonymous by now.
- She hasn't paid a ransom of $1000 by now.
- She has shared a flat with her cat by now.
- The cat is still in safe hands by now.
- It hasn't made everything clear by now.
There is no doubt that + ...
- There is no doubt that she will keep her word.
- There is no doubt that I will not follow your instructions.
- There is no doubt that she made every effort not to hurt the fish.
- There is no doubt that I made a mistake here.
- There is no doubt that I didn't make such stupid remarks.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-07 Thu 19:34]
** DONE Ask me if 写+读
CLOSED: [2023-12-07 Thu 19:53]
1. The Cutty Sark can still be seen at Greenwich. Where
	 Where can the Cutty Sark still be seen?
2. The Cutty Sark was a sailing ship. What kind...
		What kind of ship was the Cutty Sark?
3. Ships like the Cutty Sark were used to carry tea and wool. What ...
		What were ships like the Cutty Sark used to do?
4. The race lasted for four months. How long
		How long did the race last?
5. The Thermopylae reached Java first. Which ship
		Which ship reached Java first?
6. The Cutty Sark had a lot of bad luck during the race. How much
	 How much bad luck did the Cutty Sark have during the race?
7. Her rudder was torn away during a heavy storm. When
	 When was her rudder torn away?
8. A temporary rudder was made on board from spare planks. How
	 How was a temporary rudder made on board?
9. The captain called in at a port. Why
	 Why did the captain call in at a port?
10. The Cutty Sark arrived in England a week after the Thermopylae. When
		When did the Cutty Sarrk arrive in England?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-07 Thu 20:02]
After the race had begun, the Thermopylae reached Java at first,
	but on the Indian Ocean, the Cutty Sark took the lead.
In August, the Cutty Sark was struck by a heavy storm
	during which her rudder was torn away.
This reduced the speed of the ship, she lost her lead.
After crossing the Equator, the captain called in at a port to have a new rudder fitted
	when the Thermopylae was over five hundred miles ahead.
Because of so many delays, she arrived in England a week after the Thermopylae.

The Thermopylae reaced Java first, but the Cutty Sark took the lead on the Indian Ocean.
When the Cutty Sark was struck by a heavy storm, her rudder was torn away.
A temporary rudder was made and fitted, but the ship lost the lead.
After crossing the Equator, they called in at a port to have a new rudder fitted.
Even with a new rudder, the Cutty Sark arrived in England a week after the Thermopylae,
	which was 500 miles ahead.

** DONE tell the story 口语复述
CLOSED: [2023-12-07 Thu 20:10]
** composition 阅读 或 写作
** Topics for discussion
