#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 27 Nothing to sell and nothing to buy
#+begin_verse
What is the most important thing for a tramp?

It has been said that everyone *lives by selling* something.
*In the light of* this statement, teachers live by selling knowledge,
	philosophers by selling wisdom and priests by selling *spiritual comfort*.
Though it may be possible to measure that value of material goods *in terms of money*,
	*it is extremely difficult to* estimate the true value of the services which people perform for us.
There are times when we would willingly give everything we possess to save our lives,
	yet we might *grudge paying* a surgeon a high fee for offering us precisely this service.
The conditions of society are such
	that skills have to be paid for in the same way that goods are paid for at a shop.
Everyone has something to sell.

Tramps *seem to be the only exception to this general rule*.
Beggars almost sell themselves as human beings to arouse the pity of passers-by.
But real tramps are not beggars.
They have nothing to sell and require nothing from others.
*In seeking independence*, they do not sacrifice their human dignity.
A tramp may ask you for money, but he will never ask you to fell sorry for him.
He has deliberately *chosen to lead* the life he leads and is fully aware of the consequences.
He may never be sure where the next meal is coming from,
	but he *is free from* the thousands of anxieties which afflict other people.
His few material possessions make it possible for him to move from place to place *with ease*.
By having to sleep *in the open*,
	he gets far closer to the world of nature than most of us ever do.
He may hunt, beg, or steal occasionally to keep himself alive;
	he may even, in times of real need, do a little work;
	but he will never sacrifice his freedom.
We often speak of tramps *with contempt* and put them in the same class as beggars,
	but how many of us can honestly say that
		we have not *felt a little envious of* their simple way of life and their freedom from care?
#+end_verse
** expression
philosopher: [fɪˈlɑsəfər] n.哲学家
wisdom: [ˈwɪzdəm] n.智慧
priest: [prist] n. vicar 神父
spiritual: [ˈspɪrɪtʃuəl] adj.精神上的
grudge: [ɡrʌdʒ] v.n. a feeling of dislike for someone because you cannot forget that they harmed you in the past不愿给
surgeon: [ˈsɜrdʒən] n. a doctor who does operations in a hospital外科大夫
passer-by: ['pɑːsə] n. passers-by过路人
dignity: [ˈdɪɡnəti] n.尊严
deliberately: [dɪˈlɪb(ə)rətli] adv.故意地
consequence: [ˈkɑnsəkwəns] n.后果,结果
afflict: [əˈflɪkt] v.折磨
ease: [iz] n. easy to do it容易
nature: [ˈneɪtʃər] n.大自然
contempt: [kənˈtempt] n.轻蔑
envious: [ˈenviəs] adj. wanting something that someone else has嫉妒的

question/doubt the wisdom of (doing) sth.: 质疑做某事是否明智
give sb. spiritual comfort: 给某人精神上的安慰
grudge doing sth.: 不愿意做某事
have/hold a grudge against sb.: 对某人怀恨在心
die/treat/do sth. with dignity: 有尊严地xx
have consequences: 产生后果
be afflicted with/by sth.: 被某事折磨
with great/considerable ease: 很容易地
love of nature: 热爱大自然
speak of/treat sb./sth. with contempt: 轻蔑对待/谈起某人
be/feel/get/become envious of sb.: 嫉妒某人
--------------------
live by doing sth.: 以做某事为生
in the light of sth./in light of: 鉴于某事
in terms of sth.: 从某物来说
It is difficult to do sth.: 做某事困难
seem to be/do sth.: 似乎是/做某事
be the exception to the rule: 规则的例外情况
in doing sth.: 结果是
choose to do sth.: 选择做某事
be free from sth.: 摆脱某事
in the open (air): 露天

** words
philosopher [fəˈlɑːsəfər] n. 哲学家
wisdom [ˈwɪzdəm] n. 智慧
priest [priːst] n. 牧师
spiritual [ˈspɪrɪtʃuəl] adj. 精神上的
grudge [ɡrʌdʒ] v. 不愿给,舍不得给
surgeon [ˈsɜːrdʒən] n. 外科大夫
passer-by [ˌpæsər ˈbaɪ] n. 过路人
dignity [ˈdɪɡnəti] n. 尊严
deliberately [dɪˈlɪbərətli] adv. 故意地
consequence [ˈkɑːnsɪkwens] n. 后果
afflict [əˈflɪkt] v. 使苦恼,折磨
ease [iːz] n. 容易;舒适
nature [ˈneɪtʃər] n. 大自然
contempt [kənˈtempt] n. 蔑视
envious [ˈenviəs] adj. 羡慕的;嫉妒的

** vocabulary
value: worth
estimate: assess
perform: do
possess: have, own
grudge: be unwilling to do sth.
precisely: exactly
skills: abilities

** DONE 单词造句
CLOSED: [2023-12-10 Sun 22:16]
philosopher n.
- I could not avoid being influenced by the philosopher.
- In his effort to sell wisdom, everyone soon get used to the philosopher.
- The philosopher never want to get something for nothing.
- My teacher enabled me to be a philosopher.
- The philosopher came along with a little lamb.
wisdom n.  question/doubt the wisdom of (doing) sth.
- People in the town began to question the wisdom of his prediction.
- I don't question the wisdom of our boss any longer.
- I question the wisdom of buying house from the real estate in China.
- Do you question the wisdom of my buying the weapon from America?
- It is anticipated that people will doubt the wisdom of the leader's decision at the beginning.
priest n.
- The priest is always rasing money for one cause or another.
- The priest who was naked captured the attention of people at the monostery.
- The priest devised a plan to have the clock repaired.
- The priest provided us with free samples of a special type of perfume.
- If the priest say the magic word, police will arrive on the scene.
spiritual adj.  give sb. spiritual comfort
- I pride myself on giving my wife spiritual comfort.
- I have been influenced by my aunt, for she gave me spiritual comfort in my youth.
- After given spiritual comfort, I felt I had a subtle mind.
- You should have given your lover spiritual comfort.
- There is no doubt that you should give your lover spiritual comfort when she is upset.
grudge v.n.  grudge doing sth.  have/hold a grudge against sb.
- I grudge giving my nephew pocket money on non-holidays.
- She grudges classifing tramps as beggars.
- She deviese a way to be free from import duty, for she grudges paying the taxes.
- There is a danger that she grudges paying the bill.
- My daughter grudges showing her uncle to the guest room.
6. I had ever held a grudge against my aunt who brought me up. 
surgeon n.
- The death of the surgeon marked the beginning of an era.
- The button was fitted with the gate by the surgeon.
- The surgeon delaid in having an operation because of traffic jam.
- The surgeon had always taken the lead in his class in his youth.
- The surgeon has been struck by a heavy car accident and is still unconscious.
passer-by n. passers-by
- There is a danger that a passer-by may spot us stealing the shop.
- There was a time when passers-by were very friendly.
- It gave me the impression that the passer-by was leaping out at me.
- These passers-by were showed to the camp.
- It made passers-by hair stood on end that they quarreled bitterly.
dignity n.  die/treat/do sth. with dignity
- It became impossible to treat us with dignity in other country.
- She was struck by a heavy storm during the competition and died with dignity.
- It is all very well that a soldier died with dignity.
- I am petrified of not being treated with dignity.
- To varying degrees, we all want to be treated with dignity.
deliberately adv.
- The medical student ruined my day deliberately.
- Why do you get into such a mess deliberately?
- Why do you take away my keys in the drawer deliberately?
- He concealed the sweets from me deliberately.
- He asked her to stay for dinner deliberately.
consequence n.  have consequences
- She knocked him to the ground without considering consequence.
- She concealed everything that happened yesterday from the police without considering consequence.
- Don't hide his underwears. It has consequences.
- My stomach will turn at the idea of consequences.
- The sad truth is that your action has consequences.
afflict v.  be afflicted with/by sth.
- I has been afflicted with this or that anxiety all the time.
- The heroine has been afflicted with a skeleton in the cupboard day and night.
- To my surprise, she was still afflicted with this rare disease.
- If you sticked to your plan, you would not be afflicted with fear.
- I am afflicted with fear at the idea of studying abroad.
ease n.  with great/considerable ease
- I noticed him reading science fiction with ease.
- The enemy will take possession of our city with considerable ease.
- She wrote dozens of postcard with easa in her room.
- After having an operation, she took a stroll with ease.
- People in China associated octopus with food with great ease.
nature n.  love of nature
- My parents often read novels on nature, as I have a great love of nature.
- She is eager to be close to the nature on weekends.
- The paper was written out in full and explained her love of nature.
- She was cast in the role of a woman who has a great love of nature.
- She would play the role of a prizefighter who has a great love of nature.
contempt n.  speak of/treat sb./sth. with contempt
- She has cause to speak of these English teacher with contempt.
- You needn't have spoken of them with contempt in public.
- You should treat your rival with contempt.
- She is always treating her friends with contempt, for she has a better salary than them.
- I insisted that I should not be treated with contempt.
envious adj.  be/feel/get/become envious of sb.
- I never get envious of other students who get a better salary than me.
- Colleagues were envious of her breaking the world record.
- I have cause to feel envious of him.
- I bet that you get envious of your sisiter.
- My wife became envious of my success, then we quarrel bitterly.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-11 Mon 21:30]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-10 Sun 22:16]
live by doing sth.
- She lives by fighting for prize money.
- She want to live by performance.
- I never dream of living by singing.
- She managed to live by programming.
- These gangster live by asking for protection money.
in the light of sth./in light of
- In the light of problems we're having, we have no choice but to put them out of business.
- In light of argument of them, they had to fight against each other.
- In light of everything that recently happened, both countries have to be at war with each other.
- In light of the statement, I am not the exception to the rule.
- In light of the statement, the agreement has reached.
in terms of
- I prefer to think of things in terms of friendship.
- She has a habit of thinking of everything in terms of friendship.
- It is clear that we must turn against each other in terms of money.
- A set of rules were drawn up in terms of fighters' health.
- You should have thought of it in terms of money.
It is difficult to do sth.
- It is difficult to take a shower after an operation.
- It is difficult to believe in god.
- It is difficult to stick to our plan all the time.
- It is difficult to read story to my brother.
- It is difficult to stare at the torchlight all the time.
seem to be/do sth.
- She seemed to play a joke on him.
- She seemed to present follower to him.
- In the dim light, she seemed to get angry.
- They seem to fight against each other with bare fists.
- They seemed to have settled the argument.
be the exception to the rule
- Because she had a rare disease, she was the exception to the rule.
- He wasn't the exception to the rule and died in poverty.
- She was disappointed bitterly that she was the exception to the rule.
- Techinically speaking, you are not the exception to the rule.
- On the same day, I was the exception to the rule.
in doing sth.
- In attempting to finish my work, I has learnt a lot.
- In keeping my word, she rewarded me with a large bar of chocolate.
- In offering her pocket money, I changed my mind.
- In going to the police, I was stuck by a car accident.
- In remaining anonymous, she studied abroad.
choose to do sth.
- I chose to give you electric shocks.
- She chooses to fish on weekends.
- I chose to study Java rather than JS while studying in Zhengzhou.
- I have an opportunity to become a surgeon, I chose to be a programmer.
- I have the impulse to hit him, I chose to get away from him.
be free from sth.
- Everything you bought is not free from taxes.
- Because of operation, she is totally free from pain.
- The mobile phone must be free from the computer while you are live.
- You should be free from fear.
- When the report came to London, people were free from fear of invasion.
in the open (air)
- They will give five performance in the open.
- Working in the open has given him a lot of satisfaction.
- I have the impulse to play out in the open.
- In working in the open, I have a good appetite.
- She may have a good appitite in the open.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-11 Mon 21:33]
** DONE Ask me if 写+读
CLOSED: [2023-12-11 Mon 21:39]
1. Teachers live by selling knowledge. How
	 How do teachers live?
2. It is difficult to estimate the value of services that people perform. How difficult
		How difficult is it to estimate the value of services that people perform?
3. We would give up everything to save our lives. Why
		Why would we give up everything?
4. Everyone's got something to sell. What
		What has everyone got to sell?
5. Beggars sell themselves as human beings. Why
		Why do beggars sell themselves as human beings.
6. A tramp will ask you for money. Who
	 Who will ask you for money?
7. A tramp has deliberately chosen the life he leads. What
	 What has a tramp deliberately chosen?
8. He is free from thousands of anxieties. Which anxieties
	 Which anxieties is he free from?
9. He gets closer to nature than most of us do. How
	 How does he get closer to nature than most of us do?
10. A tramp will do a little work. When
		When will a tramp do a little work.
	 
** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-11 Mon 21:55]
A tramp may ask you for money, but he will never ask you to feel sorry for him.
He may not be sure where the next meal is,
	but he is free from anxieties which afflict other people.
Because he has few material possessions, it is easy for him to move from place to place.
He has to sleep in the open.
To keep himself alive, he may hunt, beg, steal occassionaly and do a little work.

Unlike beggars, real tramps have nothing to sell and require nothing from others.
Although they seek independence, they will not sacrifice their human dignity.
They choose their own way of life and are aware of the consequences.
They may not know where the next meal is coming from,
	but they do not have the worries that others have.
They can travel easily because they have few possessions
	and when they sleep in the open, they are close to nature.

** DONE tell the story 口语复述
CLOSED: [2023-12-11 Mon 21:57]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-11 Mon 22:02]
The majority of adults in society contribute to society by working.
They work, earn money and pay taxes for the things we all need
	-- hospitals, schools, public transport, the fire brigade, law and order and so on.
We don't expect children or very old people to work and pay taxes.
But everyone else should.
So why should people like tramps and beggars be different?
Tramps say all they want is their freedom.
Well, they may be free, but their freedom is paid for by everyone else in society.
There are many unemployed people who simply cannot get a job
	-- but they would work if they could.
And many beggars are people who have turned to begging because they cannot find a job.

Tramps are not like them.
Tramps lead a very selfish way of life
	and it is a way of life that shows an unwillingness to assume responsibility for others.
The rest of us have a home, children, work, and so on.
But not tramps!
Tramps are lazy parasites on society,
	and if we all had their mentality, society would not exist for them or anyone else.
Although we might in someways be envious of tramps,
	and although we might envy their freedom,
	how many of us could be as selfish as them?
How many of us could say 'damn the rest of society!'? I couldn't.

** Topics for discussion
