#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 29 Funny or not?
#+begin_verse
What is the basis of 'sick' humour?

Whether we find a joke funny or not largely depends on where we have been brought up.
The sense of humour *is mysteriously bound up with* national characteristics.
A Frenchman, for instance, might *find it hard to laugh* at a Russian joke.
In the same way, a Russian might fail to see anything amusing in a joke
	which would make an Englishman *laugh to tears*.

Most funny stories are based on comic situations.
In spite of national differences, certain funny situations *have a universal appeal*.
No matter where you live, you would find it difficult not to laugh at,
	say, Charlie Chaplin's early films.
However, a new type of humour, which *stems largely from* the US, has recently *come into fashion*.
It is called 'sick humour'.
Comedians *base their jokes on* tragic situations like violent death or serious accidents.
Many people find this sort of joke distasteful.
The following example of 'sick humour' will enable you to *judge for yourself*.

A man who had broken his right leg was taken to hospital a few weeks before Christmas.
From the moment he arrived there,
	he kept on *pestering his doctor to tell* him when he would be able to go home.
He *dreaded having* to spend Christmas in hospital.
Though the doctor *did his best*, the patient's recovery was slow.
On Christmas Day, the man still had his right leg in plaster.
He spent a miserable day in bed thinking of all the fun he was missing.
The following day, however, the doctor consoled him by telling him
	that his chances of being able to leave hospital in time for New Year celebrations were good.
The man *took heart* and, sure enough, on New Year's Eve he was able to hobble along to a party.
To *compensate for* his unpleasant experiences in hospital,
	the man drank a little more than *was good for him*.
*In the process*, he enjoyed himself thoroughly
	and kept telling everybody how much he hated hospitals.
He was still mumbling something about hospitals at the end of the party
	when he slipped on a piece of ice and broke his left leg.
#+end_verse
** expression
largely: [ˈlɑrdʒli] adv.很大程度上
comic: [ˈkɑmɪk] adj.n.漫画
universal: [ˌjunɪˈvɜrs(ə)l] adj.普遍的
comedian: [kəˈmidiən] n.喜剧演员
distasteful: [dɪsˈteɪstfəl] adj.讨厌的
pester: [ˈpestər] v.纠缠
dread: [dred] v.惧怕
recovery: [rɪˈkʌvəri] n.康复
plaster: [ˈplæstər] n.熟石膏
console: [ˈkɑnˌsoʊl] v.安慰
hobble: [ˈhɑb(ə)l] v.瘸着腿走
compensate: [ˈkɑmpənˌseɪt] v.补偿
mumble: [ˈmʌmb(ə)l] v.喃喃自语

comic book/movie/novel: 漫画书/电影/小说
have a universal appeal: 有通用的吸引力
pester sb. to do sth.: 纠缠某人做某事
dread doing sth. 惧怕做某事
dread sb. doing sth.: 害怕某人做某事
make a complete/quick/speedy/slow recovery: xx恢复
console sb./yourself that + ...: 安慰某人道 + ...
compensate (for sth.) = make up for: 补偿
--------------------
whether/whether or not .../whether...or not 主从 VS 让步状语
	1. 主从Whether引导, 不可被if代替, 在句中做1的成分
	2. whether引导让步状语从句, 在句子中状语的成分
have: stay 原则:万能+猜
--------------------
be bound up with: 与...密切相关
find it hard to do sth.: 发现做某事困难
make sb. laugh to tears: 使某人笑出眼泪
stem from ...: 源于
come into fashion: 流行起来
base A on B: 建立A在B上
judge for yourself: 自己判断
do one's best (to do sth.): try my best to do sth.尽某人最大努力做某事
take heart: 获得鼓舞
be good for sb.: 对某人有好处
in the process: 在过程中

** words
largely [ˈlɑːrdʒli] adv. 在很大程度上
comic [ˈkɑːmɪk] adj. 喜剧的,可笑的
universal [ˌjuːnɪˈvɜːrs(ə)l] adj. 普遍的
comedian [kəˈmiːdiən] n. 滑稽演员,喜剧演员
distasteful [dɪsˈteɪstf(ə)l] adj. 讨厌的
pester [ˈpestər] v. 一再要求,纠缠
dread [dred] v. 惧怕
recovery [rɪˈkʌvəri] n. 康复
plaster [ˈplæstər] n. 熟石膏
console [kənˈsoʊl] v. 安慰,慰问
hobble [ˈhɑːb(ə)l] v. 瘸着退走
compensate [ˈkɑːmpenseɪt] v. 补偿
mumble [ˈmʌmb(ə)l] v. 喃喃自语

** vocabulary
brought up: raised
mysteriously bound up with: strangely connected to
universal appeal: international attraction
stems: comes
come into fashion: become popular
distasteful: unpleasant or offensive

** DONE 单词造句
CLOSED: [2023-12-15 Fri 22:34]
largely adv.
- It is him who are largely responsible for the team's success, not you.
- We are largely likely to make a profit this year.
- I largely work with people who work in office.
- I largely read science fiction to my daughter before she sleeps.
- This largely indicates that she has got back to the ship.
comic adj.n.漫画  comic book/movie/novel
- I spoted him reading comic books in the class.
- She claimed to have not read comic books in the class.
- Our parents always put the comic books in the same class as harmful.
- It is outrageous that she is interested in comic novels.
- My friend thrust his comic book into my hands.
universal adj.  have a universal appeal
- The songs which he made in his youth have a universal appeal all over the world.
- It is all very well that a delicacy has a universal appeal.
- She claimed that snails have a universal appeal as a dish.
- We devised a plan to make a movie that has a universal appeal.
- Countless people have been influenced by a song which has a universal appeal.
comedian n.
- Damn it. I have recognized the comedian as a normal person in the market.
- The comedian which play the role of a teacher gave us a surprise.
- The comedian was cast in the role of a kidnappered.
- The comedian proceed to stay out of the limelight.
- The comedian insisted that the paper should be written out in full.
distasteful adj.
- I insisted that the woman who made such distasteful remarks apologize to us.
- You have played a joke on your husband at the party. I found this distasteful.
- Don't bring your custom to my mouth. I found it distasteful.
- If you found it distasteful, you should tell me.
- It was not until an hour after the police arrived on the scene
		that he stop making distasteful remark.
pester v.  pester sb. to do sth.
- My wife has been pestering me to travel abroad.
- Because I pestered him to go to university, we eventually reached an agreement.
- Don't pester me to buy this or that product, I am under a lot of pressure.
- I am relieved to hear that he stop pestering his father to check the garage.
- My cat have been pestering me to play ball with her.
dread v.  dread doing sth.  dread sb. doing sth.
- In fact, I really dread traveling abroad.
- I am under a lot of pressure and dread my boss ordering me to finish it.
- Much as she loved to go on a jourey, she dreaded asking his father for money.
- The thief caught sight of policemen in front of his house and dreaded getting back home.
- She woke up with a start and dreaded peeing in the midnight.
recovery n.  make a complete/quick/speedy/slow recovery
- After an operation, he soon made a complete recovery.
- The fact that my cat made a slow recovery afflicted me a great deal.
- If you had an operation, you would make a complete recovery.
- He made a complete recovery, for he refused to follow his doctor's instructions.
- I'm glad that you made a full recovery.
plaster n.
- She wasn't able to play truent from school, for her leg was still in plaster.
- As my foot was in plaster at that time, I have a perfect alibi.
- Whether my leg is in plaster or not is something that has no influence on taking the test.
- Whether my leg is in plaster or not doesn't prevent me from watching TV.
- Whether my leg is in plaster or not doesn't prevent me from being your husband.
console v.  console sb./yourself that + ...
- I consoled myself that Miumiu is very dear to me.
- I consoled myself that I would get a good salary in the future.
- She consoled me that our daughter has said magic word.
- I consoled my wife that the girl just classified us as beggars.
- I consoled my wife that our son would soon take heart.
hobble v.
- I was strucked by a ball and had to hobble home.
- As the medicine exerts some influence on him, he had to hobble across the park.
- A old lady hobbled to the store to get samples of perfume for nothing.
- The cat who is hobbling arose the pity of mine.
- It is anticipated that he would hobble home afther he was hurt in the game.
compensate v.  compensate (for sth.) = make up for
- In the university, my breakfast used to be compensated by lunch.
- The busmen were compensated for better salary and less work time.
- My wife was compensated for a nice dress which she expected to buy for a long time.
- The fans of the singer were made up for some tickets.
- You will be made up for studying abroad.
mumble v.
- He seems to be mumbling his lover's name in sleep.
- A woman who was making a speech in the open was mumbling, you made a spectacle of herself.
- If you mumbled at that time, you might make a spectacle of yourself.
- She was mumbling her cat's name to herself.
- In going to office, I always mumble names of my wife and my cat.

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-17 Sun 20:29]
** DONE 讲语法
CLOSED: [2023-12-17 Sun 20:29]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-16 Sat 11:42]
be bound up with
- My problems are bound up with my mother's departure when I was three.
- His achivement is bound up with his philosophy.
- His breaking world record is bound up with the support from his father.
- Our progress will be bound up with our determination and plans.
- High civilization is bound up with our educational development.
find it hard to do sth.
- I found it hard to make a complete recovery.
- He was assailed by a vendor and found it hard to get back to the ship.
- My wife found it hard to reduce the price to $5.
- He found it hard to throw up his arms in plaster.
- I find it hard to get rid of the gangster who asked for protection money.
make sb. laugh to tears
- The comedian went to great lengths to make his customers laugh to tears.
- It should have made us laugh to tears.
- My wife used to make me laugh to tears in our attic.
- His little brother went to great lengths to prove that he had made his daughter laugh to tears.
- He lives by making his customers laugh to tears.
stem from ...
- This kind of jokes stem large from the U.S.
- When he told me that this sort of biscuit stems from the U.S,
		 I question the wisdom of his judgement.
- My problem stems from the fact that I was afflicted by anxieties every day.
- His problem stems from the fact that he didn't pass the test.
- My problem stems from the fact that I became envious of my wife.
come into fashion
- It is said that long shirts come into fashion these days.
- Long shirts do come into fashion in China.
- As this kind of clothes come into fashion again, my wife got a better salary.
- I question the wisdom of buying this kind of clothes which came into fashion last year.
- Whether you like it or not, it came into fashion again.
base a. on b.
- The director based his movie on a science fiction which came into fashion.
- It was not until a week after the book was published that the director based his film on this.
- The writer based his novel on a story
		that a prizefighter and his pupil turned against each other.
- He based his story on two countries which were at war with each other.
- He based his story on an aristocrat who was born in 14th B.C.
judge for yourself
- Leo grudged telling me the answer and asked me to judge for myself.
- It is clear that you are able to judge for yourself.
- He is so clever that he is quick to judge fro himself.
- He has already judged for himself and made it official.
- Technically speaking, you have been judging for yourself all the time.
do one's best (to do sth.)
- My wife claimed that she did her best to take care of me.
- Jackie Ma told us not to do our best to do anything worthless.
- There are countless people in China who do their best to achive their goals.
- He does his best to prevent his family from living in poverty.
- Obviously, Mendoza did his best and rose to fame swiftly.
be good for sb.
- Reading a great deal is good for your English.
- Working hard is good for us.
- Running daily is good for my health.
- It is clear that fresh fruits and vegetables are good for you.
- Playing football is good for my health.
in the process
- She was moving to New York and had an accident in the process.
- Our company will make a profit in the process.
- His rise in status happened in the process.
- This special type of cat gained in popularity in the process.
- The code has been cleaned up in the process.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-17 Sun 20:29]
** DONE Ask me if 写+读
CLOSED: [2023-12-17 Sun 20:36]
1. Our sense of humor is bound up with national characteristics. What
	 What is bound up with national characteristics?
	 What is our sense of humor bound up with?
2. A Frenchman will find it hard to laugh at a Russian joke. Why
		Why will a Frenchman find it hard to laugh at a Russian joke?
3. Most funny stories are based on comic situations. What
		What are based on comic situations?
		What are most funny stories based on?
4. Certain funny situations have a universal appeal. Why
		Why do certain funny situations have a universal appeal?
5. A new type of humor has recently come into fashion. What
		What has recently come into fashion?
6. A man was taken to hospital a few weeks before Christmas. When
	 When was a man taken to hospital?
7. He dreaded having to spend Christmas in hospital. Where
	 Where did he dread having to spend Christmas?
8. The doctor said he could go home for New Year. When
	 When did the doctor say he could go home?
9. The man drank a little more than was good for him. How much
	 How much did the man drink?
10. He was mumbling about hospitals when he slipped on a piece of ice. What
		What was he mumbling about when he slipped on a piece of ice?
	
** DONE Summary Writting 写 & 对答案
CLOSED: [2023-12-17 Sun 20:47]
A man who had broken his right leg a few weeks before Christmas
	kept on pestering his doctor to tell him when he could go home,
	beacuse he didn't want to spend Christams in hospiatl.
As his recovery was slow, on Christmas Day, he spent a miserable day in bed.
The next day, the doctor told him that he may be able to leave hospital for New Year celebrations.
Sure enough, on New Year's Eve he managed to hobble along to a party.
To compensate for his experiences in hospital, he drank a little more.
In the process, he told everybody how much he hated hospitals.
When he slipped on a piece of ice and broke his left leg,
	he wast still mumbling somethings about hospitals.

A man broke his right leg just before Christmas and was taken to hospital.
He wanted to know when he could go home.
On Chirstams Day he was still in hospital with his leg in plaster,
	but there was a good chance of leaving hospital for the New Year.
In fact, he was out in time to go to a New Year's Eve party where he drank too much,
	slipped on a piece of ice and broke his left leg.

** DONE tell the story 口语复述
CLOSED: [2023-12-17 Sun 20:49]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-17 Sun 20:58]
An aunt of mine lives in a small village in the country
	and tells this story of what happened to her once.
In order to understand the story, you should know a little about life in an English village.
For example, people often enjoy afternoon tea together,
	they still leave doors unlocked,
	and certain tradesmen are used to delivering goods and,
	with permission, leaving them inside the owner's house.
One day my aunt had invited some friends round for afternoon tea.
She had put some cakes in the oven to bake, and had gone upstairs to do some cleaning.
When she finished, she decided to have a bath before her friends arrived.

She was just about to get into the bath when she suddenly remembered the cakes.
She wrapped a bath towel round her, went down to the kitchen and took the cakes out of the oven.
Just then, there was a knock on the back door.
She was sure it was the baker,
	who would open the door, come in and leave the bread on the kitchen table.
She panicked, dashed into the cupboard under the stairs and closed the door.
Then, horrified, she heard footsteps coming to the cupboard.
The door opened and there stood the gasman who had come to read the meter
	-- which was in the cupboard.
My aunt blushed and said, 'I'm very sorry. I was expecting the baker.'
'Oh,' the gasman said."Sorry, madam".
He closed the door gently and left.

** Topics for discussion
