#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 31 A lovable eccentric
#+begin_verse
Why did the shop assistant refuse to serve Dickie?

True eccentrics never deliberately set out to *draw attention to themselves*.
They *disregard social conventions*
	without *being conscious that* they are doing anything extraordinary.
This invariably *wins them* the love and respect of others,
	for they *add colour to* the dull *routine of everyday life*.

*Up to the time of his death*, Richard Colson was one of the most notable figures in our town.
He was a shrewd and wealthy businessman,
	but most people in the town hardly knew anything about this side of his life.
He was known to us all as Dickie and his eccentricity had become legendary long before he died.

Dickie disliked snobs intensely.
Though he owned a large car, he hardly ever used it, perferring always to *go on foot*.
Even when it was raining heavily, he refused to carry an umbrella.
One day, he walked into an expensive shop after having *been caught in* a particularly heavy shower.
He wanted to buy a 300 dollars watch for his wife,
	but he was in such a bedraggled condition that an assistant refused to serve him.
Dickie left the shop without a word and returned carrying a large cloth bag.
As it was extremely heavy, he *dumped it on the counter*.
The assistant asked him to leave,
	but Dickie paid no attention to him and *requested to* see the manager.
Recognizing who the customer was,
	the manager was most apologetic and reprimanded the assistant severely.
When Dickie was given the watch, he *presented the asssistant with* the cloth bag.
It contained 300 dollars in cents.
He insisted on the assistant's counting the money before he left -- 30000 cents in all!
On another occasion,
	he *invited a number of important critics to see* his private collection of modern paintings.
This exhibition received a great deal of attention in the press,
	for though the pictures were supposed to be the work of famous artists,
	they had in fact been painted by Dickie.
It took him four years to stage this *elaborate joke*
	simply to prove that critics do not always know what they are talking about.
#+end_verse
** expression
lovable: [ˈlʌvəb(ə)l] adj.可爱的
eccentric: [ɪkˈsentrɪk] n.(行为)古怪人
disregard: [ˌdɪsrɪˈɡɑrd] v. to ignore something or treat it as unimportant不顾,漠视
convention: [kənˈvenʃ(ə)n] n.习俗,风俗
conscious: [ˈkɑnʃəs] adj. aware 感觉到的
invariably: [ɪnˈveriəbli] adv.总是
routine: [ˌruˈtin] n.常规;惯例
shrewd: [ʃrud] adj.精明的
eccentricity: [ˌeksenˈtrɪsəti] n.怪癖
legendary: [ˈledʒənˌderi] adj.传奇般的
snob: [snɑb] n.势力小人
intensely: [ɪn'tensli] adv.强烈地
bedraggled: [bɪˈdræɡ(ə)ld] adj.拖泥带水的
dump: [dʌmp] v.把...砰的抛下
apologetic: [əˌpɑləˈdʒetɪk] adj.道歉的
reprimand: [ˈreprɪˌmænd] v.训斥
stage: [steɪdʒ] v.n.暗中策划
elaborate: [ɪˈlæb(ə)rət] adj.精心构思的

disregard social conventions: 无视社会习俗
be conscious of (doing) sth.: 意识到做某事
sb. be conscious that + ...: 某人意识到+...
daily routine: 日常惯例
dump sth. on sth.: 扔某物在某物上
be apologetic about/for sth.: 为某事道歉
reprimand sb. for (doing) sth.: 斥责某人做某事
elaborate plan/design/meal: 精心制定计划
--------------------
draw attention to sb.: 引起某人的注意
win sb. sth.: 赢得某人某物
add a. to b.: 把A加到B
up to the time of sth.: 到...的时候
go on foot: 走路
be caught in: 淋雨
sb. request to do sth.: 某人请求做某事
present sb. with sth.: 送某人某物
invite sb. to do sth.: 邀请某人做某事


** words
lovable [ˈlʌvəbl] adj. 可爱的
eccentric [ɪkˈsentrɪk] n. (行为)古怪人
disregard [ˌdɪsrɪˈɡɑːrd] v. 不顾,漠视
convention [kənˈvenʃ(ə)n] n. 习俗,风俗
conscious [ˈkɑːnʃəs] adj. 感觉到的,意识到的
invariably [ɪnˈveriəbli] adv. 总是,经常地
routine [ruːˈtiːn] n. 常规;惯例
shrewd [ʃruːd] adj. 精明的
eccentricity [ˌeksenˈtrɪsəti] n. 怪癖
legendary [ˈledʒənderi] adj. 传奇般的
snob [snɑːb] n. 势力小人
intensely [ɪnˈtensli] adv. 强烈地
bedraggled [bɪˈdræɡ(ə)ld] adj. 拖泥带水的
dump [dʌmp] v. 把...砰的一声抛下
apologetic [əˌpɑːləˈdʒetɪk] adj. 道歉的
reprimand [ˈreprəmænd] v. 训斥
stage [steɪdʒ] v. 暗中策划
elaborate [ɪˈlæbərət] adj. 精心构思的

** DONE 单词造句
CLOSED: [2023-12-20 Wed 22:57]
lovable adj.
- Our lovable cat grudged taking a shower and put his paw on my hands.
- This lovable girl should be treated with dignity.
- Why does such a lovable kid hold a grudge against you?
- This lovable girl is questioning the wisdom of our ambassador.
- It is disturbing to think that your lovable cat is still at large.
eccentric n.
- Our eccentric boss is always asking us to do housework.
- The eccentric man still remained in hiding after the war as well.
- The eccentric found it impossible to get food for free in the restaurant.
- The eccentric billionare thought it his duty to raise money for his country.
- It became an accepted fact
		that the eccentric billionare had gave up his bussiness long before his death.
disregard v.  disregard social conventions
- The girl disregarded the advice her relatives given and became a medical student.
- The eccentric was supposed to disregard social conventions.
- The man who disregard social conventions in the town was none other than your son.
- I woke up to find that she disregard all the advice I gave her.
- Every time I disregard the advice my father gave, I fail.
convention n.
- It is just social convention that people didn't believe in god in China.
- I felt oblidged to greet him because of social conventions.
- It is social convention that men in the town stay overnight in the hay before Christmas.
- I often question the wisdom of the social convention that people believe in God.
- I refused to follow social convention and took a shower in January.
conscious adj. aware   be conscious of (doing) sth.  sb. be conscious that + ...
- The father was conscious that his son hadn't been killed in action.
- I was conscious of your touch me in the hay that night.
- I was conscious that my cat was kidnappered during the night.
- I was conscious that fresh fruits and vegetables are good for me.
- I was conscious that I had made tremendous mistakes in the process.
invariably adv.
- In seeking for truth, we invariably make this or that mistake.
- We invariably do our best to chase what we want in our lives.
- We invariably have to judge for ourselves for one reason or another.
- We invariably based our behavior on other's judgements.
- Wether we find a joke funny or not is invariably  bound up with our national characteristics.
routine n.  daily routine
- I was influenced by the eccentric who has a busy daily routine.
- In my daily routine, there is a danger that I might miss the train and be late for work.
- In my daily routine, there is no doubt that I read English material every noon.
- In my daily routine, I consoled my patient who was anxiously to leave hospital.
- In my daily routine, I have to pester my colleague to finish task in time.
shrewd adj.
- The shrewd businessman never failed to fascinate pretty girls.
- To compensate for his loss, the shrewd bussiman made profit on another occassion.
- The shrewd businessman put his wallet in the microwave oven for safekeeping.
- Imagine his dismay when he knew that his son, a shrewd businessman, was put out of business.
- So long as you give enough money,
		the shrewd businessman will present you with satisfying product.
eccentricity n.
- The legendary painting which was made 2 century BC will be on display in the exhibition.
- The poor man was given electric shocks because of his eccentricity.
- Everyone thought that he had a rare disease because of his eccentricity.
- Oddly enough, his eccentricity didn't capture the attention of the reporter.
- We didn't connect his eccentricity to the murder.
legendary adj.
- Leo who taught a great many people a course was regard as lengendary.
- The legendary prizefighter soon turned against his pupil.
- It is clear that the legendary player have won the prize for a second time.
- Faker who was regarded as legendary had won the elections over and over again.
- It was not until the 5th season games that the legendary retired.
snob n.
- Oddly enough, the snob rose to fame swiftly.
- The snob quarrelled bitterly with a customer who is bedraggled.
- In lighting cigarette, the snob happened to set the curtain on fire.
- The snob made no effort to laught at the poor man.
- Severing a poor lay, the snob lost his temper.
intensely adv.
- My wife dislikes to do the dishes intensely.
- His behavior intensely proved that he played truent from school.
- It is clear that your daughter hates you intensely.
- It comes as a surprise to learn that my wife loved me intensely when she was very young.
- On the surface, he loved his wife intensely.
bedraggled adj.
- After struck by a heavy shower, she was bedraggled and wet.
- She was so bedraggled that the assistant refused her to enter the store.
- There is no doubt that she was bedraggled when she got back home.
- Because he was bedraggled, he delayed in holding the meeting.
- I woke up to find a bedraggled figure who was touching my arm.
dump v.  dump sth. on sth.
- You needn't have dumped the letters on my table.
- After finishing his work, he dumpped his earphone and went out fishing.
- The gangster went through the contents of his bag and dumpped it on the ground.
- There is a danger that the students might dump their books on the ground.
- There is no doubt that the students will dump their books on the ground.
apologetic adj.  be apologetic about/for sth.
- I am apologetic for what I have done last night.
- My wife was apologetic about mistakes that she made.
- My wife should be apologetic about works she said just now.
- Technically speaking, the girl was apologetic about the eccentricity of her son in the mall.
- The manager was apologetic about his misunderstanding of the shop assistant.
reprimand v.  reprimand sb. for (doing) sth.
- He has never reprimand us for something wrong we did.
- I have the impulse to reprimand him for his error.
- It is illogical to reprimand him for a tiny mistake.
- My parents reprimanded me for staying for dinner at my friend home.
- To my dismay, my boss reprimanded me for what happened last month.
stage v.n.
- The sad truth is that the eccentric staged a elaborate joke.
- The museum doesn't have cause to stage an exhibition.
- I am anxious to stage an exhibition in which goods come from all over the world.
- He was expected to stage a successful exhibition.
- There is no doubt that these busmen who retired recently staged a strike.
elaborate adj.  elaborate plan/design/meal
- He put forward an elaborate plan from which everyone benefit.
- They devised an elaborate plan to build the project.
- I anticipated that my wife cooked an elaborate meal.
- She cooked such an elaborate meal that she became the head chef in the resturant.
- I must devise an elaborate plan before I take the interview.

** DONE vocabulary
CLOSED: [2023-12-21 Thu 20:58]
deliberately: on purpose, intentionally
disregard: ignore
conventions:habits, rules
conscious: aware
notable figures; famous people
shrewd: clever
elaborate: detailed, carefully planned

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-21 Thu 20:39]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-21 Thu 13:03]
draw attention to sb.
- The eccentricity of my cat never fails to draw attention to me.
- The flashing light on the road is used to draw attention to passers-by.
- The agreement which was reached last week drew attention to a detective.
- Leo is trying to draw attention to his young pupils in the class.
- You are supposed to draw attention to the public.
win sb. sth.
- The performance the pop singer gave won him loud cheers from the crowd.
- It became an accepted fact that she won her large sums of money in the competition.
- I thought it my duty to win me a gold medal.
- It was none other than Eric who won him a gold medal in Olympics.
- In seeking for truth, he won him a lot of praises.
add a. to b.
- He was anxious to add his name to the list.
- I used to add standing in my spare time to my daily routine.
- I found it impossible to add running in afternoon to my daily routine.
- My wife has just added a special type of dress to her shopping cart.
- The man kept his brother in hiding for over fifty years,
		 this experience added color to their life.
up to the time of sth.
- Up to the time of his death, he devoted himself to garden.
- Up to the time of his death, he dedicated his life to garden.
- Up to the time of his death, he spent large sums of money.
- Up to the time of his death, he was known to people in Florence as Dickie.
- Up to the time of his death, he suffered from serious injury.
go on foot
- I would prefer to go on foot rather than take a bus.
- I prefer to go on foot rather than take a bus.
- There was a time when people prefer to go on foot.
- The friend offered to go on foot when the car is full.
- You'd better go on foot or I will tell mom.
be caught in
- Afther caught in a snowstorm, we expected a warm welcome at the monastery.
- After caughht in a snowstorm, we made ourselves comfortable in front of fireplace.
- It is anticipated that the bus will be caught in snowstorm.
- These dogs are trained to help people who are caught in snowstorm.
- She complained that she was caught in rainstorm and was bedraggled.
sb. request to do sth.
- My wife requested to stay overnight in the hay.
- My wife requested to buy a house in Hangzhou.
- My wife requested to go on vocation to Hainan.
- My wife requested to bring fresh fuirts to her.
- My wife requested to provide her with background music in the restaurant.
present sb. with sth.
- I am gonna present my wife with a daimond as big as marble.
- Following my friend's instructions, I presented my wife with my pocket money.
- It gave me the impression that my wife would present me with a media player.
- I am eager to open the box which my wife presented me with yesterday.
- I am gonna present you with a book which I read to you yesterday.
invite sb. to do sth.
- She invited her daughter to attend the custom party.
- It is clear that your wife invited this guy to cook dinner.
- Much to my surprise, his wife invited her ex-boyfriend to appear her wedding.
- She has invited him to stay for dinner.
- She has been invited him to stay for dinner.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-21 Thu 20:27]
** DONE Ask me if 写+读
CLOSED: [2023-12-21 Thu 20:45]
1. True eccentrics disregard social conventions. Why
	 Why do true eccentrics disregard social conventions?
2. Eccentrics add color to the dull routine of everyday life. What
		What do eccentrics add to the dull routine of everyday life?
3. Richard Colson was a shrewd and wealthy businessman. What kind of
		What kind of businessman was Richard Colson?
4. His eccentricity had become legendary long before he died. When
		When had his eccentricity become legnedary?
5. He refused to carry an umbrella. What
		What did he refuse to carry?
6. He wanted to buy an expensive watch for his wife. Who
	 Who did he want to buy an expensive watch for?
7. Dickie asked to see the manager. Why
	 Why did Dickie ask to see the manager?
8. The cloth bag contained $300 in pennies. What
	 What contained $300 in pennies?
	 What did the cloth bag contain?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-21 Thu 20:54]
After a heavy shower, Dickie walked into an expensive shop
	where he wanted to a $300 watch for his wife.
However, he was so bedraggled that an assistant refused to serve him.
After leaving the shop, Dickie returned carrying a cloth bag
	which he dumped on the counter.
As the assistant asked him to leave, Dickie requested to see the manager,
	who aplogized to him and reprimanded the assistant.
Dickie insisted on the assistant's counting 30,000 pennies contanied in the cloth bag
	before he left.

Dickie had been caught in a heavy shower when he walked into an expensive shop.
He wanted a $300 watch for his wife,
	but he was so bedraggled that the assistant refused to serve him.
He left the shop and returned with a heavy cloth bag which he dumped on the counter.
Dickie asked for the manager.
When he was given the watch, he gave the assistant the bag which contained $300 in pennies,
	which the assistant had to count.

** DONE tell the story 口语复述
CLOSED: [2023-12-21 Thu 20:57]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-21 Thu 21:02]
Mr. Chew is a man who has lived in our small town for years.
He is a large man (some would say 'fat'),
	he has a round face, a big black moustache and a bald head.
He always wears the same clothes -- black trousers, a white shirt and a red waistcoat,
	and is always polite to everyone he meets.
He owns an antiques shop near the river, and he lives 'over the shop'.
No one knows where he gets his things,
	but there are always lots of different interesting antiques in the shop window every week.
Mr. Chew is interested in politics, too.
Every week he puts up strange notices in his shop window to passers-by.

Usually the notices are trying to make people
	save a local building or stop a plan to build a road through the town.
Every time there is a national election,
	he automatically stands for parliament
	and gives speeches almost every day in the town park
	saying what he would do if he were Prime Minister.
He usually says he would make sure that antiques dealers did not have to pay income Tax
	and that no cars should be allowed into our little town at all.
Every year he gets a few votes,
	but not enough to worry the serious candidates.
For most people Mr. Chew is a harmless eccentric,
	and everyone likes talking to him.
After all, he is someone who adds colour to the dull routine of their daily lives.

** Topics for discussion
