#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 32 A lost ship
#+begin_verse
Did the crew of the Elkor find what they were looking for? Why?

The *salvage operation* had been a complete failure.
The small ship, Elkor, which had been searching the Barents Sea for weeks,
	was on its way home.
A radio message from the mainland had been received by the ship's captain
	instructing him to give up the search.
The captain knew that another attempt would be made later,
	for the sunken ship he was trying to find had been carrying *a precious cargo of* gold bullion.

Despite the message, the captain of the Elkor decided to try once more.
The sea bed was scoured with powerful nets
	and there was tremendous excitement on board when a chest was raised from the bottom.
Though the crew *were at first under the impression that* the lost ship had been found,
	the contents of the chest proved them wrong.
What they had in fact found was a ship which had been sunk many years before.

The chest contained the personal belongings of a seaman, Alan Fielding.
There were books, clothing and photographs,
	*together with* letters which the seaman had once received from his wife.
The captain of the Elkor ordered his men to salvage as much as possible from the wreck.
Nothing of value was found,
	but the numerous items which were brought to the surface proved to be of great interest.
From a heavy gun that was raised,
	the captain realized that the ship must have been a cruiser.
In another chest, which contained the belongings of a ship's officer,
	there was an unfinished letter which had been written on March 14th, 1943.
The captain leant from the letter that the name of the lost ship was the Karen.
The most valuable find of all was the ship's log book,
	parts of which it was still possible to read.
From this the captain was able to *piece together* all the information that had *come to light*.
The Karen had been sailing *in a convoy* to Russia when she was torpedoed by an enemy submarine.
This was later confirmed by *a naval official* at the Ministry of Defence
	after the Elkor had returned home.
All the items that were found were sent to the War Museum.
#+end_verse
** expression
salvage: [ˈsælvɪdʒ] v.n. 救助;打捞
Barents: n.(海)
sunken: [ˈsʌŋkən] adj.沉没的
cargo: [ˈkɑrɡoʊ] n.一车/船货物
bullion: [ˈbʊljən] n. un. bars of gold or silver金条;银条
scour: [skaʊr] v.搜寻
chest: [tʃest] n.大箱子
contents: [kənˈtent] n.(复数)所装的东西
belongings: [bɪˈlɔŋɪŋz] n.(复数)所有物
item: [ˈaɪtəm] n.物件
cruiser: [ˈkruzər] n.巡洋舰
find: [faɪnd] n. thing找到的物品
log: [lɔɡ] book: 日志本
piece: [pis] v. 拼成整体
convoy: [ˈkɑnˌvɔɪ] n. 护航
torpedo: [tɔrˈpidoʊ] v. n. 用鱼雷攻击
submarine: [ˈsʌbməˌrin] n. 潜水艇
naval: [ˈneɪv(ə)l] adj. navy n.海军的
ministry: [ˈmɪnɪstri] n. (政府的)部
--------------------
salvage operation: 打捞行动
a cargo of: 一货...
piece together: 拼装起来
in a convoy: 在护航中
a naval officer: 一个海军军官
--------------------
sb. be under the impression that + ...: 某人在...幻觉/印象下
together with: 除了...还有
come to light: 披露出来

** words
salvage [ˈsælvɪdʒ] v.救助,营救; 打捞
Barents ['bærənts] n.巴伦支(海)
sunken [ˈsʌŋkən] adj.沉没的
cargo n.货物
bullion [ˈbʊliən] n.金条;银条
scour [ˈskaʊər] v.彻底搜索
chest [tʃest] n.大箱子
contents [ˈkɑːntents] n.(复数)所装的东西
belongings [bɪˈlɔːŋɪŋz] n.(复数)所有物
item [ˈaɪtəm] n.物件
cruiser [ˈkruːzər] n.巡洋舰
find [faɪnd] n.找到的物品
log book [lɔːɡ-bʊk] 航海日志
piece [piːs] v.拼成整体
convoy [ˈkɑːnvɔɪ] n.护航
torpedo [tɔːrˈpiːdoʊ] v.用鱼雷攻击
submarine [ˈsʌbməriːn] n.潜水艇
naval [ˈneɪv(ə)l] adj.海军的
ministry [ˈmɪnɪstri] n.(政府的)部

** DONE 单词造句
CLOSED: [2023-12-24 Sun 14:39]
salvage v.n.  salvage operation
- As we were struck by a rainstrom, the salvage operation was delayed for days.
- Sure enough, there was a salvage operation in the open seas.
- The salvage operation must have been gone on for sevaral days.
- The salvage operation failed because of bad weather.
- The salvage operation which was delayed for days should have gone on for weeks.
Barents n.
sunken adj.
- These archaeologists never dreamed of finding a sunken ship which dates back to ancient times.
- While the salvage operation was going on, a sunken ship had been found on the sea bed.
- The captain was conscious that the sunken ship can't be found ever.
- The captain found it impossible to find the sunken ship which they searched for weeks.
- The captain kept the sunken ship in hiding until the end of the war.
cargo n.  a cargo of
- The ship was gonna carry a cargo of fresh fruits and vegetables to London.
- These workers had the impulse to unload a cargo of oranges from the ship.
- The student in the university set a cargo of cell phones on fire last night.
- A worker felt sick to his stomach while waiting for a cargo of furniture.
- My boss got very angry when waitting for a cargo of furniture.
bullion n. un.
- The pirate was delighted to unload gold bullion from the ship.
- The boat was said to be loaded with silver bullion.
- The boat was supposed to be loaded with gold bullion, together with silver bullion.
- While I was taking a shower, I found a bullion in my bathroom.
- It is illogical for your wife to throw away a gold bullion.
scour v.
- I was anxious to scour my room to find my key to the truck.
- My wife scoured our yard to clean up the snails.
- The sad truth is that we scoured his room and found no evidence.
- I noticed you scouring your room, why did you do that?
- He scoured his drawer to find the pictures of his wife at the idea of his daughter.
chest n.
- Going through the contents of chest, the pirate throw it into the sea.
- I had the impulse to open the chest that belongs to my wife.
- As he was tired of work, he dumpped his clothes on the chest.
- He has received abuse from his mother, for he sat on the precious chest.
- The chest was said to have numerous gold bullion.
contents n.
belongings n.
- To my dismay, when we are about to drive you have not packed your belongings.
- If you had packed your belongings in time, we wouldn't have been late for work.
- For instance, he forgot to pack his belongings.
- My wife is brought up to pack her belongings by herself.
- Don't forget your belongings just before you left the washroom.
item n.
- You are free to take these items with you.
- Leo expressed his gratitude to me, for I let him have these items for free.
- Make yourself comfortable. These items are free samples of perfume.
- It is illogical to classify these items as something exempted from import duty.
- The item I gave you last week is a mixture of wather and alcohol.
curiser n.
- It used to be my job to fix curiser.
- We were greeted by an unpleasant smell when we repaired the curiser.
- I felt guilty that I failed to repair the curiser.
- On the other hand, the curiser was used to attack people without weapons.
- There were a lot of excitement in the curiser after the salvage operation.
find n. thing
- A gold bullion is always a find of value.
- The order was given because of a valuable find.
- Armed with a torchlight in the cave, we indeed got valuable finds.
- The well-known archaeologist always gets valuable finds for one cause or another.
- On another occasion, he claimed that he got a valuable find in the cave.
log book
- Waking up with a start, the captain begun to read the log book.
- The seaman caught sight of a log book the captain was reading.
- This seaman is equal to read the log book.
- It is a pity that we didn't get enough money to read that log book in the museum.
- We got used to reading the log book.
piece v.  piece together
- After having pieced together what happened concerned with him, we all got very angry.
- The detective managed to piece together the information.
- I'm sure that you had a perfect alibi, for I have pieced together what happened.
- I'm glad that you pieced together the fragments of the clock.
- Equipped with a torchlight, he pieced together the fragments of paper.
convoy n.  in a convoy
- In a convoy, these officers went to extremes to protect the president.
- In a convoy, no one was allowed to walk on the street.
- I was punished for the simple reason that they were in a convoy.
- In a convoy, the local police usually have a difficult time in keeping order.
- Despite the fact that he was in a convoy, he put out the fire in the antique store.
torpedo v. n.
- I consloed the crew of the ship that we wasn't torpedoed by a submarine.
- After several times, the captain found it hard to torpedo the ship out at sea.
- Whether we are torpedoed or not largely depends on the damn weather.
- The captain took heart and torpedoed the enemy ship.
- To compensate for our loss, we must torpedo their ship.
submarine n.
- The speical kind o submarine stems from the U.S.
- The editor is so fanatical about submarines that he wrote an article on them.
- His father claimed that he was killed in action in the submarine.
- We might stay overnight in the submarine.
- The expert went to great lengths to prove that the submarine hadn't been torpedoed.
naval adj. navy n.  a naval officer
- A naval officer ordered his men to get rid of the submarine.
- A naval officer claimed that he was impressed by the loss of the Titanic.
- I can't conceal the fact that the naval officer was killed in action.
- A naval officer sped to the cruiser.
- The naval officer had no intention of concealing it.
ministry
- I used to work for the Ministry of Defence.
- The teacher should be someone who used to work for the Ministry of Education.
- A man who works for the Ministry of Defence asked me to do him a favor.
- It is outrageous that some students set the Ministry of Defence on fire.
- It is outrageous that a vendor bargained with passers-by in front of the Ministry of Education.

** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-24 Sun 14:39]
sb. be under the impression that + ...
- I was under the impression that the dog was about to leap out at me.
- They were under the impression that they had finished their task.
- You should not be under the impression that he still fall in love with you.
- Everyone was under the impression that the naval officer was killed in action.
- We were under the impression that the salvage operation was a compelete failure.
together with
- Dickie presented his wife with a $300 watch,
	  together with a precious cell phone on her birthday.
- We was caught in a rainstorm, together with an air crash.
- Our friend, Joey, went on foot, together with his brother, Chandler.
- I am apologetic about my son's asking for money, together with meal.
- He dumped the heavy bag on the counter, together with a receipt.
come to light
- He managed to piece together all information that had come to light.
- Before this came to light, we all thought that cats have nine lives.
- Before the new evidence came to light, he had a perfect alibi.
- If this had come to light, he would have had a perfect alibi.
- If this evidence comes to light, you will be judged in the court.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-24 Sun 19:36]
** DONE Ask me if 写+读
CLOSED: [2023-12-24 Sun 19:44]
1. The salvage operation had been a complete failure. Why
	 Why had the salvage operation been a complete failure?
2. The radio message had instructed him to give up the search. What ... do
		What had the radio message instructed him to do?
3. The sunken ship had been carrying a cargo of gold. What
		What had the sunken ship been carrying?
		What had been carrying a cargo of gold?
4. The captain decided to try once more. Who
		Who decided to try once more?
5. A chest was raised from the bottom of the sea. Where
		Where was a chest raised?
6. The ship had been sunk many years before. When
	 When had the ship been sunk?
7. The chest had belonged to a seaman. Who
	 Who had the chest belonged to?
8. They knew that the ship had been a cruiser. How
	 How did they know that the ship had been a cruiser?
9. The lost ship had been called the Karen. What
	 What had been called the Karen?
	 What had the lost ship been called?
10. The Karen had been torpedoed by an enemy submarine. When
		When had the Karen been torpedoed by an enemy submarine?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-24 Sun 19:57]
A chest, which contained books, clothing, photographs and letters,
	was raised from the bottom of the sea.
Because this proved that it belonged to a seaman,
	the captain of the Elkor instructed his men to salvage as much as possible.
From a heavy gun that was raised, the captain knew the ship must have been a cruiser.
The captain learnt from the letter in another chest that the name of the lost ship was the Karen.
From the ship's log book, parts of which it was still able to read,
	the captain piece together all the information.
The Karen was torpedoed by an enemy submarine in a convoy to Russia.
All the items that were salvaged were sent to the War Museum.

The chest containing the personal belongings of Alan Fielding told them a lot,
	and there were other items of interest.
A heavy gun proved the ship was a cruiser.
Another chest belonging to a ship's officer
	contained an unfinished letter dated March 14th, 1943,
		from which they learnt the ship's name.
The most valuable find was the ship's log book,
	which told them the Karen had been sailing in convoy to Russia
	when she was torpedoed by an enemy submarine.

** DONE tell the story 口语复述
CLOSED: [2023-12-24 Sun 20:04]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-24 Sun 20:13]
The journey has gone well so far.
We are now on the way to Russia and hope that we arrive with no more problems.
But we are watching the sea and sky.
The convoy successfully fought off an air attack early this morning.
No ships were lost and we managed to shoot down three enemy aircraft
	before they broke off the attack.

At 10 a.m. this morning we were attacked by a U-boat.
This was the first time we had been attacked
	and for most men on board this was the first time they had been in action at sea.
We were fortunate, but the ship ahead of us, the Dauntless, was torpedoed and sunk.

After the ship sank, there were hundreds of men in the sea.
We picked up as many survivors as we could in the Karen.
In fact in the end we picked up 720 men.
Which meant that 50 men lost their lives in the attack on the Dauntless.
The Karen was packed with men, many crowded on the open decks,
	when we turned and attacked the U-boat.
Depth charges were dropped and the U-boat was put out of action.

It is now 3.15 p.m., the light is already beginning to fade and storm clouds are gathering.
We are about to be attacked by a second U-boat, this time from the north.
The captain has just announced.

** Topics for discussion
