#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 34 A happy discovery
#+begin_verse
What was the 'happy discovery'?

*Antique shops exert a peculiar fascination on* a great many people.
The more expensive kind of antique shop
		where rare objects are beautiful displayed in glass cases to keep them free from dust
	is usually a *forbiding place*.
But no one has to *muster up courage to enter* a less pretentious antique shop.
*There is always hope*
	that *in its labyrinth of* musty, dark, disordered rooms
		a real rarity will be found amongst the piles of assorted junk that *litter the floors*.

No one discovers a rarity *by chance*.
A truly dedicated bargain hunter must have patience,
	and *above all*, the ability to recognize the worth of something when he sees it.
To do this, he must be at least as knowledgeable as the dealer.
Like a scientist *bent on making* a discovery,
	he must *cherish the hope that* one day he will be amply rewarded.

My old friend, Frank Halliday, is just such a person.
He has often *described to me how* he *picked up* a masterpiece of a mere 50 dollars.
One Saturday morning, Frank visited an antique shop in my neighbourhood.
As he had never been there before, he found a great deal to interest him.
The morning passed rapidly
	and Frank was about to leave when he noticed a large packing case lying on the floor.
The dealer told him that it had just come in,
	but that he *could not be bothered to open* it.
Frank *begged him to do* so and the dealer reluctantly *prised it open*.
The contents were disappointing.
Apart from an interesting-looking carved dagger, the box was full of crockery, much of it broken.
Frank gently lifted the crockery out of the box
	and suddenly noticed a miniature painting *at the bottom of* the packing case.
As its composition and line reminded him of an Italian painting he knew well, he decided to buy it.
Glancing at it briefly, the dealer told him that it was worth 50 dollars.
Frank could hardly conceal his excitement,
	for he knew that he had made a real discovery.
The tiny painting proved to be an unknown masterpiece by Corrggio
	and was worth hundreds of thousands of dollars.
#+end_verse
** expression
antique: [ænˈtiːk] n.古董,古玩
fascination: [ˌfæsɪˈneɪʃ(ə)n] n.魅力,迷惑力
forbidding: [fəˈbɪd] adj.望而生畏的
muster: [ˈmʌstər] v.鼓起
pretentious: [prɪˈtenʃəs] adj.自命不凡的,绞饰的
labyrinth: [ˈlæbəˌrɪnθ] n.迷宫
musty: [ˈmʌsti] adj.陈腐的,发霉的
rarity: [ˈrerəti] n.稀世珍品
assorted: [əˈsɔrtəd] adj.各式各样的
junk: [dʒʌŋk] n.破落货,废品
litter: [ˈlɪtər] v.杂乱地布满
dedicated: [ˈdedɪˌkeɪtəd] adj.专心致志的
bargain: [ˈbɑrɡən] hunter 到处找便宜买的人
dealer: [ˈdilər] v.商人
cherish: [ˈtʃerɪʃ] v.期望,渴望
amply: ['æmpli] adv.足够地
masterpiece: [ˈmæstərˌpis] n.杰作
mere: [mɪr] adj.仅仅
prise: [praɪz] v.撬开
carve: [kɑrv] v.镌刻
dagger: [ˈdæɡər] n.短剑,匕首
miniature: [ˈmɪnɪtʃər] adj.小巧的,小型的
composition: [ˌkɑmpəˈzɪʃ(ə)n] n.构图

antique shop/store/desk/jewelry: 古董店
hold/have a fascination for sb./sth.: 对某人/某事物着迷
forbidding place/look: 冷冰冰的地方/脸
muster (up) the courage/confidence/to do sth.: 鼓起勇气/自信去某事
in the labyrinth of sth.: 在某物的迷宫中
junk mail: 垃圾邮件
be littered with sth.: 乱扔某物
sb. cherish the hope that + ...: 某人怀着希望+...
The mere fact that + ... + 23456: 事实(...)仅仅是
prise sth. open: 撬开某物
carve a. from/out of b.=a. be carved from/out of b.: 从B中雕刻出A
--------------------
There is always hope that + ...: 总有希望...
by chance: 偶然
above all: 所有之上,尤其是
be bent on doing sth.: 决心做某事
sb. cherish the hope that + ...: 某人怀着希望+...
describe to sb. what/how + 宾从 = describe sth. to sb. 向某人描述...
pick up: 捡起
sb. can't/couldn't be bothered to do sth.: 做某事不耐烦(不想做)
beg sb. to do sth.: 恳求某人做某事
at the bottom of ...: 在...的底部

** words
antique [ænˈtiːk] n. 古董,古玩
fascination [ˌfæsɪˈneɪʃ(ə)n] n.魅力,迷惑力
forbidding [fərˈbɪdɪŋ] adj.望而生畏的
muster [ˈmʌstər] v.鼓起
pretentious [prɪˈtenʃəs] adj.自命不凡的
labyrinth [ˈlæbərɪnθ] n.迷宫
musty [ˈmʌsti] adj.陈腐的,发霉的
rarity [ˈrerəti] n.稀世珍品
assorted [əˈsɔːrtɪd] adj.各式各样的
junk [dʒʌŋk] n.破烂货,废品
carve [kɑːrv] v.雕刻
dagger [ˈdæɡər] n.短剑
litter [ˈlɪtər] v.杂乱地布满
dedicated [ˈdedɪkeɪtɪd] adj.专心致志的
bargain [ˈbɑːrɡən] hunter 到处找便宜货买的人
dealer [ˈdiːlər] v.商人
cherish [ˈtʃerɪʃ] v.期望
amply [ˈæmpli] adv.足够地
masterpiece [ˈmæstərpiːs] n.杰作
mere [mɪr] adj.仅仅的
prise [praɪz] v.撬开
miniature [ˈmɪnətʃər] adj.小巧的
composition [ˌkɑːmpəˈzɪʃ(ə)n] n.构图

** DONE 单词造句
CLOSED: [2023-12-27 Wed 23:04]
antique n.  antique shop/store/desk/jewelry
- He showed me to his antique shop on Christmas day.
- The only person who benefited from the antique desk is our cat, for she always sleeps on it.
- The destory of the antique desk set up a chain of reactions.
- The antique was set up on fire by students in the university and got out of control rapidly.
- What invariably happens is that an antique jewelry can be broken.
fascination n.  hold/have a fascination for sb./sth.
- I used to hold a fascination for Faker, a famous LoL player who won champions four times.
- My wife seems to have a fascination for the room so that she swept it up all day.
- The famous actor who stayed out of limelight has a fascination for antique jewelry.
- It comes as a surprise to learn that she has a fascination for the albums of Leo.
- I used to have a fascination for videos about traffic on rush hour.
forbidding adj.  forbidding place/look
- A regiment of detectives are keeping guard in front of the door, it looks forbidding.
- The forest must be a forbidding place which lives a witch.
- The forbidding look of the policeman made it possible for him to get the traffic on the move.
- He looked forbidding all of a sudden and pulled up.
- The lorry driver who had a forbidding look was drawing up alongside our car.
muster v.  muster (up) the courage/confidence/to do sth.
- If we mustered up the courage to build our country, we would be rich now.
- The boy mustered up the courage to talk to his lover on the phone.
- The action that he mustered up courage to tell her that he loves her
		 was a prelude to a series of catastrophes.
- Fearing of unforeseen changes, he mustered up the courage to ask her out.
- I decided to muster up the courage to propose to her in the suburbs.
pretentious adj.自命不凡的;炫耀的
- He is so pretentious that he was under the impression that girls in the class love him.
- He is so pretentious that he refused to follow his boss's instructions.
- He is so pretentious that he always pulls up all of a sudden.
- I was so pretentious that I made every effort to laugh at some students who had bad grades.
- She was so pretentious that she didn't follow in her father's footsteps.
labyrinth n.  in the labyrinth of sth.
- I was curious to find out that there is a house in the labyrinth of trees.
- In the labyrinth of traffic, she managed to go to work on time.
- The police was told that a bomb was planted in the labyrinth of mall.
- She might feel frightened in the labyrinth of trees.
- In the labyrinth of items, I found a packet of sweets which my daughter kept in hidding.
musty adj.
- I am sure that the clothes smells musty and you should change into another.
- The room smells so musty that she lights a cigarette.
- The lady kept on sweeping up these musty cigarette ends.
- I am genuinely sorry that I offered you a musty room.
- Everything in the room returns to normal and you will not find it musty anymore.
rarity n.
- I am delighted that you made a discovery of a rarity in the antique shop.
- This rarity he found in the antique shop gave him satisfaction a great deal.
- He had a great appetite, for he got a rarity just then.
- He lost his temper at the idea of the loss of a rarity.
- He has suffered from the loss of a rarity for a few days.
assorted adj.
- The assorted butterflies broke students' concentration and Mr. Leo got very angry.
- I never have the nerve to handle assorted problems about friend relationships.
- She noticed her aunt carrying a bag of assorted sweets to her room.
- Rachel has the impluse to share assorted sweets with these children.
- She went to great length to prove that there was a bag of assorted sweets on the table.
junk n.  junk mail
- I am gonna go on a diet and refused to eat junk foods.
- The surgeon had an operation and the room was full of junk.
- It must be considered as a junk mail.
- It gave me the impression that the junk mail was not important so I dropped it.
- Oddly enough, my coworker pestered me to open the junk mail.
litter v.  be littered with sth.
- The sign say: don't litter.
- My wife never dreamed of litter the entrance hall with toys.
- To compensate the experience in the school, she littered the living room with sweets.
- She dreaded us littering the living room with junk.
- Oddly enough, littering bed with flower has a universal appeal to girls.
dedicated adj.
- I think of myself as a dedicated student, as I spend a few hours studying English.
- It seems that a dedicated girl has a universal appeal to us.
- I consoled my father that I am very dedicated.
- My teacher indicated that I am the most dedicated student in our class.
- The dedicated student eventually got rid of her classmate
		 who invited her to his house on rush hour.
bargain hunter
- The bargain hunter was tempted to buy it from me.
- It is outrageous that a bargain hunter buys something without comparing prices.
- I was impressed by the bargain hunter who opened an antique shop.
- It took me half an hour to get rid of the bargain hunter.
- I have no intention of showing a bargain hunter to my antique shop.
dealer n.
- The art dealer whose gallery was set on fire lived in poverty.
- The art dealer threw up his arms and agreed to reduce the price to $300.
- The art dealer always thinks of relationships in term of money.
- The art dealer went to great lengths to prove
		that the diamond was real.
- I can't conceal the fact that I bought it from the art dealer.
cherish v.  sb. cherish the hope that + ...
- She cherishes the hope that the diamond as big as marbles is real.
- She cherished the hope that she will not be assailed by her ex-boyfriend anymore.
- She cherished the hope that the girl was tempted to eat the apple.
- She cherished the hope that her keys ring was still on the desk.
- She cherished the hope that she was free from housework.
amply adv.
- She complained that the hotel didn't amply provide with Wi-Fi.
- The love of my wife amply gave me spiritual comfort.
- It is anticipated that hotels in China will amply provide us with Wi-Fi.
- She was amply influenced by her mother who had recently studied English.
- I amply pride myself on programming.
masterpiece n.
- She devised a plan to buy a masterpiece abroad.
- The painting was by no means considered to be a masterpiece.
- They devised a way to turn these lesson into a masterpiece.
- Whether you believe it or not, the masterpiece exerted a subtle influence on me.
- Fulfilling my dream, I managed to turn it into a masterpiece.
mere adj.  The mere fact that + ... + 23456
- The mere fact that she classified us as tramps is unacceptable.
- The mere fact that she forgot to turn off the light set the house on fire.
- The mere fact that a butterfly capture his attention makes him fail the exam.
- The mere fact that she is so pretentious makes us get angry.
- The mere fact that we were struck by storm made us fail to break the world record.
prise v.  prise sth. open
- There is a danger that we must prise it open.
- She managed to prise the lock open and take the lead.
- Found that the lock coundn't be fitted with the key, she prised it open.
- The mananger delayed in prising the door open.
- The police arrived on the scene and prised it open with great ease.
carve v.  carve a. from/out of b.=a. be carved from/out of b.
- There is no doubt that the statue was carved from a large stone.
- It is clear that the Medoza was carved from a wood.
- The man was able to carve a bear from the stone and took the lead.
- Once upon a time, a sculptor carved a witch from a large stone.
- It gave me the impression that the cat was carved from a skeleton.
dagger n.
- I couldn't conceal the fact that I bought a toy dagger from a vendor.
- There must have been a dagger in the drawer.
- To varying degrees, the dagger must be carved from a large stone.
- I won't let a lost dagger ruin my day.
- Oddly enough, the medical student has a fascination on assorted daggers.
miniature adj.
- I was strucked by a miniature train in the kindergarden.
- My stomach would turn at the idea of miniature golf.
- I noticed him playing with miniature train.
- We used to play miniature train and stay for dinner in his house.
- To my dismay, she didn't allow me to play her miniature train.
composition n.
- The sad truth is that I can't take the composition of photographs into account.
- My wife sticked to the composition of photographs.
- It occurs to me to my wife at idea of composition of photographs.
- My wife is always complaining that the composition of photographs are not good enough.
- I didn't have the nerve to take the composition of photographs into account.

** vocabulary
rare objects: very unusual things
displayed: shown, put on show
piles: stacks,(untidy) collections
assorted junk: mixed rubbish of all kinds
truly: really, seriously
bent on: determined to
amply: sufficiently

** DONE 反复听电影片段直到懂关键句
CLOSED: [2023-12-29 Fri 18:23]
** 复习二册语法(笔记或视频) & 红皮书
** DONE 习惯用法造句
CLOSED: [2023-12-28 Thu 20:29]
There is always hope that + ...
- There is always hope that we get a good salary.
- There is always hope that the gas will reduce price to $1 a liter.
- There is always hope that he will have a fascination for the course.
- There is always hope that he musters up the courage to ask her out.
- There is always hope that there is a rarity in the labyrinth of items in room.
by chance
- I have told you that I met her by chance.
- She cherished th hope that he will be killed in action by chance.
- I'm genuinely sorry that I prised the lock open by chance.
- I found a rarity in the antique shop by chance.
- We benefited from the cold weather by chance and made a profit.
above all
- Above all, we should get it under control at the beginning of the meeting.
- Above all, we need to draw up alongside his car.
- Above all, you needn't have reduced your mother to tears.
- Above all, you should attend to your baby at first.
- Above all, you asked your neighbor keep an eye on your baby.
be bent on doing sth.
- The archaeologist was bent on making a real discovery.
- The policeman arrived on the scene and was bent on keeping order.
- My wife was bent on sweeping up our room in hometown.
- My boss was bent on making a profit last year.
- The lady was bent on taking care of stray dogs.
sb. cherish the hope that + ...
described to sb. what/how + 宾从 = describe sth. to sb.
- I found it impossible to describe to Leo what set up a chain of reactions.
- My wife described to me what happened in her company.
- My child was trying to describe to me how he got everything in classroom under control.
- The lorry drive described to the police why he kept drawing up alongside the car.
- The captain described to us what had come to light.
pick up
- Wandering around the university, I always pick up some bargains from these students.
- I was under the impression that I picked up a rare book.
- He managed to pick up a nice suit which he changed into last night.
- The man picked up a car which was worth $1000.
- Such is human nature, that we are willing to pick up some bargains in the street.
sb. can't/couldn't be bothered to do sth.
- I can't be bothered to take a bath.
- She can't be bothered to buy nuts from a vendor.
- I couldn't be bothered to be dressed in that pants.
- She couldn't be bothered to keep the status quo.
- She couldn't be bothered to keep secret anymore.
beg sb. to do sth.
- I begged you to do me a flavor.
- She begged her husband to go to street with her.
- The cat begged me to offer her some foods.
- The captain begged us to keep the secret that he had killed a seaman.
- She begged the editor to publish an article on her story.
at the bottom of ...
- At the bottom of the desk, I spotted a lot of sweets.
- At the bottom of my heart, I couldn't conceal the fact that I was still love with him.
- At the bottom of the drawer, she found a rare carved dagger.
- Have you find anything unusual at the bottom the desk?
- There are his pocket money at the bottom of the desk. It's just between you and me.

** 跟读 50遍
** DONE Comprehension 反复练习
CLOSED: [2023-12-29 Fri 18:23]
** DONE Ask me if 写+读
CLOSED: [2023-12-29 Fri 20:38]
1. Antique shops fascinate a lot of people. Why
	 Why do antique shops fascinate a lot of people?
2. Anyone has to muster up courage to enter a cheap antique shop. Who
		Who has to muster up courage to enter a cheap antique shop?
3. Piles of assorted junk litter the floors. What kinds of junk
		What kinds of junk litter the floors?
4. A dedicated bargain hunter must have patience. What
		What must a dedicated bargain hunter have?
5. A bargain hunter is rather like a scientist. What ... like
		What is a bargain hunter like?
6. Frank visited an antique shop in the writer's neighbourhood. Where
	 Where did Frank visit an antique shop?
7. Frank noticed a large packing case on the floor. What
	 What did Frank notice on the floor?
8. The dealer opened the packing case reluctantly. How
	 How did the dealer open the packing case?
9. Frank noticed a miniature painting at the bottom of the packing case. What
	 What did Frank notice at the bottom of the packing case?
10. The painting proved to be an unknown masterpiece by Correggio. What
		What did the painting prove to be?

** DONE 摘要写作 写 & 对答案
CLOSED: [2023-12-29 Fri 20:56]
One Saturday morning, Frank Halliday visited an antique shop in my neighbour hood
	where he had never been before.
He was about to leave when he noticed a packing case lying on the floor,
	which had just come in,
	in which there are an carved dagger and broken crokery.
Frank lifted the crockey out of the box
	and found a miniature painting at the bottom.
He bought the painting from the dealer for mere $50,
	which proved to be an unknown masterpiece by Correggio
		and was wroth hundreds of thousands of dollars.


While visiting an antique shop one Saturday,
	Frank was about to leave when he saw a large packing case.
He asked the dealer to open it but the contents were disappointting
	until he lifted some crockery and noticed a miniature painting at the bottom.
He had already decided to buy it when the dealer told him it was $50.
Frank was excited because this was a real discovery.
The painting was an unknown masterpiece worth hundreds of thousands of dollars.

** DONE tell the story 口语复述
CLOSED: [2023-12-29 Fri 20:56]
** DONE composition 阅读 或 写作
CLOSED: [2023-12-29 Fri 21:01]
'The Antique Shop' has been in the little street near the church for years.
As you look at it from across the road, it draws you towards it.
It has one large window display designed to attract all sorts of customers.
There is expensive glass, porcelain and jewellery to attract people with a lot of money;
	there is secondhand furniture, modern silver and other things (hardly antique!)
		to attract those with not so much.
When you enter the shop, a little bell rings
	and the owner, a little grey-haired old lady called Mrs. Century,
		comes out from a room at the back
		and greets you like a lost relative!
She greets everyone the same and always with a smile.
The shop sells all kinds of antiques.

There are shelves full of old books along the back of the shop.
There are two large tables in the middle of the shop covered with pieces of glass and porcelain.
Then, around the walls on the floor are large pots, brass statues and things.
There are lots of painting on the walls, too.
At the weekend, the shop usually has five or six customers in it at one time.
You might find a professional antique collector,
	a holiday couple and a young mother(with child in pram) looking for a cheap antique
		for her husband's birthday.
We all like looking for unusual things
	and hope to find a bargain one day.
You might find one in Mrs. Century's 'Antique Shop'.

** Topics for discussion
