#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 38 The first calender
#+begin_verse
What is the importance of the dots, lines, and symbols engraved on stone, bones and ivory?

Future historians will be in a unique position
	when they come to record the history of our own times.
They will hardly know
	which facts to select from the great mass of evidence that steadily accumulates.
What is more,
	they will not have to rely solely on the written word, Films, videos, CDs and CD-ROMs
		are just some of the bewildering amount of information they will have.
They will be able, as it were, to see and hear us in action.
But the historian attempting to reconstruct the distant past is always faced with a difficult task.
He has to deduce what he can from the few scanty clues available.
Even seemingly insignificant remains can shed interesting light on the history of early man.

Up to now, historians have assumed that calendars came into being with the advent of agriculture,
	for then man was faceed with a real need to understand something about the seasons.
Recent scientific evidence seems to indicate that this assumption is incorrect.

Historians have long been puzzled by dots, lines and symbols
	which have been engraved on walls, bones and the ivory tusks of mammoths.
The nomads who made these markings lived by hunting and fishing
	during the last Ice	Age which began about 35,000 B.C. and ended about 10,000 B.C.
By correlating markings made in various parts of the world,
	historians have been able to read this difficult code.
They have found that it is connected with the passage of days and the phases of the moon.
It is, in fact, a primitive type of calendar.
It has long been known
	that the hunting scenes depicted on walls were not simply a form of artistic expression.
They had a definite meaning, for they were as near as early man could get to writing.
It is possible that there is a definite relation
	between these paintings and the markings that sometimes accompany them.
It seems that man was making a real effort
	to understand the seasons 20,000 years earlier than has been supposed.
#+end_verse

** words
calendar [ˈkælɪndər] n.日历
historian [hɪˈstɔːriən] n.历史学家
unique [juˈniːk] adj.无与伦比的
steadily [ˈstedəli] adv.不断地
solely [ˈsoʊlli] adv.唯一地
video [ˈvɪdioʊ] n.录像
CD-ROM [ˌsiː ˈdiː rɑːm] n.(只读)光盘驱动器
bewilder [bɪˈwɪldər] v.令人眼花缭乱
deduce [dɪˈduːs] v.推断
scanty [ˈskænti] adj.不足的,贫乏的
clue [kluː] n.线索
insignificant [ˌɪnsɪɡˈnɪfɪkənt] adj.不重要的
shed [ʃed] v.使流出
advent [ˈædvent] n.出现,到来,来临
agriculture [ˈæɡrɪkʌltʃər] n.农业
assumption [əˈsʌmpʃ(ə)n] n.假定,设想
dot [dɑːt] n.小圆点
symbol [ˈsɪmb(ə)l] n.符号
engrave [ɪnˈɡreɪv] v.雕刻
ivory [ˈaɪvəri] n.象牙制品
mammoth [ˈmæməθ]  n.(古)长毛象
tusk [tʌsk] n.獠牙,象牙
nomad [ˈnoʊmæd] n.游牧民
correlate [ˈkɔːrələt] v.使互相联系
phase [feɪz] n.月相,天象
primitive [ˈprɪmətɪv] adj.原始的
depict [dɪˈpɪkt] v.描画,描绘

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
