#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 39 Nothing to worry about
#+begin_verse
What was the difference between Bruce's behaviour and that of other people?

The rough road across the plain soon became so bad
	that we tried to get Bruce to drive back to the village we had come from.
Even though the road was littered with boulders and pitted with holes,
	Bruce was not in the least perturbed.
Glancing at his map,
	he informed us that the next village was a mere twenty miles away.
It was not that Bruce always underestimated difficulties.
He simply had no sense of danger at all.
No matter what the conditions were,
	he believed that a car should be driven as fast as it could possibly go.

As we bumped over the dusty track,
	we swerved to avoid large boulders.
The wheels scooped up stones which hammered ominously under the car.
We felt sure
	that sonner or later a stone would rip a hole in our petrol tank or damage the engine.
Because of this, we kept looking back,
	wondering if we were leaving a trail of oil and petrol behind us.

What a relief it was when the boulders suddenly disappeared,
	giving way to a stretch of plain where the only obstacles were clumps of bushes.
But there was worse to come.
Just ahead of us there was a huge fissure.
In response to renewed pleadings, Bruce stopped.
Though we all go out to examine the fissure, he remained in the car.
We informed him that the fissure extended for fifty yards and was two feet wide and four feet deep.
Even this had no effect.
Bruce went into a low gear and drove at a terrifying speed,
	keeping the front wheels astride the crack as he followed its zigzag course.
Before we had time to worry about what might happen,
	we were back on the plain again.
Bruce consulted the map once more and told us that the village was now only fifteen miles away.
Our next obstacle was a shallow pool of water about half a mile cross.
	giving way to a stretch of plain
		where the only obstacles were clumps of bushes.
But there was worse to come.
Just ahead of us there was a huge fissure.
In reponse to renewed pleadings, Bruce stopped.
Though we all got out to examine the fissure,
	he remained in the car.
We informed him
	that the fissure extended for fifty yards and was two feet wide and four feet deep.
Even this had no effect.
Bruce went into a low gear and drove at a terrifying speed,
	keeping the front wheels astride the crack
		as he followed its zigzag course.
Before we had time to worry about what might happen,
	we were back on the plain again.
Bruce consulted the map once more
	and told us
		that the village was now only fifteen miles away.
Our next obstacle was a shallow pool of water about half a mile across.
Bruce charged at it,
	but in the middle, the car came to a grinding halt.
A yellow light on the dashboard flashed angrily
	and Bruce cheerfully announced that there was no oil in the engine!
#+end_verse

** words
rough [rʌf] adj.崎岖不平的
boulder [ˈboʊldər] n.大石块
pit [pɪt] v.使得坑坑洼洼
perturb [pərˈtɜːrb] v.使不安
underestimate [ˌʌndərˈestɪmeɪt] v.低估
swerve [swɜːrv] v.急转变
scoop [skuːp] v.挖出
hammer [ˈhæmər] v.(用锤)击打,捶打
ominously [ˈɑːmɪnəsli] adv.有预兆的,不详的
rip [rɪp] v.划破,撕,扯
petrol [ˈpetrəl] n.汽油
stretch [stretʃ] n.一大片(平地或水)
obstacle [ˈɑːbstək(ə)l] n.障碍
clump [klʌmp] n.(一)丛(花)
fissure [ˈfɪʃər] n.(石,地的)深缝
renew [rɪˈnuː] v.重复
pleading [ˈpliːdɪŋ] n.恳求
gear [ɡɪr] n.(汽车)排档
astride [əˈstraɪd] prep.骑
crack [kræk] n.缝隙
zigzag [ˈzɪɡzæɡ] n."之"字型
shallow [ˈʃæloʊ] adj.浅得
grind [ɡraɪnd] v.摩擦
halt [hɔːlt] n.停
dashboard [ˈdæʃbɔːrd] n.(汽车上的)仪表盘

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
