#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 43 Fully insured
#+begin_verse
Who owned the pie dish and why?

Insurance companies are normally willing to insure anything.
Insuring public or private property is a standard practice in most countries in the world.
If, however, you were holding an open air garden party or a fete
	it would be equally possible to insure yourself in the event of bad weather.
Needless to say, the bigger the risk an insurance company takes, the higher the premium
	you will have to pay.
It is not uncommon to hear
	that a shipping company has made a claim for the cost of salvaging a sunken ship.
But the claim made by a local authority to recover the cost of
	salvaging a sunken pie dish	must surely be unique.

Admittedly it was an unusual pie dish, for it was eighteen feet long and six feet wide.
It had been purchased by a local authority
	so that an enormous pie could be baked for an annual fair.
The pie committe decided that the best way to transport the dish would be by canal,
	so they insured it for the trip.
Shortly after it was launched, the pie committee went to a local inn to celebrate.
At the same time, a number of teenagers climbed on to the dish
	and held a little party of their own.
Dancing proved to be more than the dish could bear,
	for during the party it capsized and sank in seven feet of #+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

The pie committee telephoned a local garage owner
	who arrived in a recovery truck to salvage the pie dish.
Shivering in their wet clothes,
	the teenagers looked on	while three men dived repeatedly into the water to locate the dish.
They had little difficulty in finding it,
	but hauling it out of the water proved to be a serious problem.
The sides of the dish were so smooth that it was almost impossible to attach hawsers
	and chains to the rim without damaging it.
Eventually chains were fixed to one end of the dish
	and a powerful winch was put into operation.
The dish rose to the surface
	and was gently drawn towards the canal bank.
For one agonizing moment,
	the dish was perched precariously on the bank of the canal,
	but it suddenly overbalanced and slid back into the water.
The men were now obliged to try once more.
This time they fixed heavy metal clamps to both sides of the dish
	so that they could fasten the chains.
The dish now had to be lifted vertically
	because one edge was resting against the side of the canal.
The winch was again put into operation
	and one of the men started up the truck.
Several minutes later,
	the dish was successfully hauled above the surface of the water.
Water streamed in torrents over its sides with such force
	that it set up a huge wave in the canal.
There was a danger that the wave would rebound off the other side of the bank
	and send the dish plunging into the water again.
By working at tremendous speed, the men managed to get the dish on to dry land
	before the wave returned.
#+end_verse

** words
insure [ɪnˈʃʊr] v.投保
fete [feɪt] n.游园会
premium [ˈpriːmiəm] n.保险费
recover [rɪˈkʌvər] v.使...得到补偿,弥补
admittedly [ədˈmɪtɪdli] adv.公认地
purchase [ˈpɜːrtʃəs] v.买
annual [ˈænjuəl] adj.一年一度的
teenager [ˈtiːneɪdʒər] n.青少年
capsize [ˈkæpsaɪz] v.(船)翻
shiver [ˈʃɪvər] v.打颤,发抖
dive [daɪv] v.(头向下)跳水
haul [hɔːl] n.托拽
hawser [ˈhɔːzər] n.粗缆绳
rim [rɪm] n.外沿,边
winch [wɪntʃ] n.绞车
agonizing [ˈæɡənaɪzɪŋ] adj.精神紧张的,提心吊胆的
perch [pɜːrtʃ] v.处于(高处)
precariously [prɪˈkeriəsli] adv.危险地,不稳固地
overbalance [ˌoʊvərˈbæləns] v.失去平衡
clamp [klæmp] n.夹钳,夹板
vertically [ˈvɜːrtɪkli] adv.垂直地
torrent [ˈtɔːrənt] n.激流,洪流
rebound [rɪˈbaʊnd] v.弹回

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
