#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 44 Speed and comfort
#+begin_verse
Which type of transport does the writer prefer, do you think?

People travelling long distances frequently have to decide
	whether they would prefer to go by land, sea, or air.
Hardly anyone can positively enjoy sitting in a train for more than a few hours.
Train compartments soon get cramped and stuffy.
It is almost impossible to take your mind off the journey.
Reading is only a partial solution,
	for the monotonous rhythm of the wheels clicking on the rails soon lulls you to sleep.
During the day, sleep comes in snatches.
At night, when you really wish to go to sleep,
	you rarely manage to do so.
If you are lucky enough to get a sleeper,
	you spend half the night staring at the small blue light in the ceiling,
		or fumbling to find your ticket for inspection.
Inevitably you arrive at your destination almost exhausted.
Long car journeys are even less pleasant,
	for it is quite impossible even to read.
On motorways you can, at least,
	travel fairly safely at high sppeeds, but more often than not,
	the greater part of the journey is spent on roads with few service stations and too much traffic.
By comparison, ferry trips or cruises offer a great variety of civilized comforts.
You can stretch your legs on the spacious desks, play games, meet interesting people
	and enjoy good food -- always assuming, of course, that the sea is calm.
If it is not, and you are likely to get seasick, no form of transport could be worse.
Even if you travel in ideal weather, sea journeys take a long time.
Relatively few people are prepared to sacrifice holiday time for the pleasure of travelling by sea.

Aeroplanes have the reputation of being dangerous
	and even hardened travellers are intimidated by them.
They also have the disadvantage of being an expensive form of transport.
But nothing can match them for speed and comfort.
Travelling at a height of 30,000 feet, far above the clouds,
	and at over 500 miles an hours is an exhilarating experience.
You do not have to devise ways of taking your mind off the journey,
	for an aeroplane gets you to your destination rapidly.
For a few hours, you settle back in a deep armchair to enjoy the flight.
The real escapist can watch a film and sip champagne on some services.
But even when such refinements are not available,
	there is plenty to keep you occupied.
An aeroplane offers you an unusual and breathtakig view of the world.
You soar effortlessly over high mountains and deep valleys.
You really see the shape of the land.
If the landscape is hidden from view,
	you can enjoy the extraordinary sight of unbroken cloud plains
		that strethc out for miles before you,
	while the sun shines brilliantly in a clear sky.
The journey is so smooth that there is nothing to prevent you from reading or sleeping.
However you decide to speed your time, one thing is certain:
	you will arrive at your destination fresh and uncrumpled.
You will not have to spend the next few days recovering from a long and arduous journey.
#+end_verse

** words
positively [ˈpɑːzətɪvli] adv.绝对地,完全地
compartment [kəmˈpɑːrtmənt] n.列车客车车厢内的分隔间(或单间)
cramped [kræmpt] adj.窄小的
stuffy [ˈstʌfi] adj.憋气的,闷气的
monotonous [məˈnɑːtənəs] adj.枯燥的,乏味的,单调的
rhythm [ˈrɪðəm] n.有节奏的运用
click [klɪk] v.发出咔嗒声
lull [lʌl] v.催人欲睡
snatch [snætʃ] n.短时,片刻
sleeper [ˈsliːpər] n.卧铺
fumble [ˈfʌmb(ə)l] v.乱摸,摸索
inspection [ɪnˈspekʃ(ə)n] n.检查
inevitably [ɪnˈevɪtəbli] adv.必然地
destination [ˌdestɪˈneɪʃ(ə)n] n.目的地
exhaust [ɪɡˈzɔːst] v.使精疲力尽
motorway [ˈmoʊtərweɪ] n.快车道
ferry [ˈferi] n.渡船
cruise [kruːz] n.巡游船
civilize [ˈsɪvəlaɪz] v.使文明
spacious [ˈspeɪʃəs] adj.宽敞的
seasick [ˈsiːsɪk] adj.晕船的
intimidate [ɪnˈtɪmɪdeɪt] v.恐吓
disadvantage [ˌdɪsədˈvæntɪdʒ] n.短处
exhilarating [ɪɡˈzɪləreɪtɪŋ] v.使人高兴的
escapist [ɪˈskeɪpɪst] n.逍遥者
sip [sɪp] v.嘬
champagne [ʃæmˈpeɪn] n.香槟酒
refinement [rɪˈfaɪnmənt] n.精心的安排
breathtaking [ˈbreθteɪkɪŋ] adj.激动人心的;不寻常的
soar [sɔːr] v.高飞
effortlessly [ˈefərtləsli] adv.不费力地
landscape [ˈlændskeɪp] n.景色
fresh [freʃ] adj.精神饱满的
uncrumpled [ʌn'krʌmpld] adj.没有垮下来

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
