#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 46 Do it yourself
#+begin_verse
Did the writer repair his lawn mower in the end? Why or Why not?

So great is our passion for doing things for ourselves,
	that we are becoming increasingly less dependent on specialized labour.
No one can plead ignorance of a subject any longer,
	for there are countless do-it-yourslef publications.
Armed with the right tools and materials,
	newlyweds gaily embark on the task of decorating their own homes.
Men, particularly, spend hours of their leisure time installing their own fireplaces,
	laying out their own gardens; building garages and making furniture.
Some really keen enthusiasts go so far as to build their own computers.
Shops cater for the do-it-yourself craze not only by running special advisory services for novices,
	but by offering consumers bits and pieces which they assemble at home.
Such things provide an excellent outlet for pent up creative energy,
	but unfortunately not all of us are born handymen.

Some wives tend to believe that their husbands are infinitely resourceful and can fix anything.
Even men who can hardly drive a nail in straight
	are supposed to be born electricians, carpenters, plumbers and mechanics.
When lights fuse, furniture gets rickety, pipes get clogged, or vacuum cleaners fail to operate,
	some women assume that their husbands will somehow put things right.
The worst thing about the do-it-yourself game is that sometimes even men live under the declusion
	that they can do anything, even when they have repeatedly been proved wrong.
It is a question of pride as much as anything else.

Last spring my wife suggested that I call in a man to look at our lawn mower.
It had broken down the previous summer, and though I promised to repair it,
	I had never got round to it.
I would not hear of the suggestion and said that I would fix it myself.
One Saturday afternoon, I hauled the machine into the garden and had a close look at it.
As far as I could see, it needed only a minor adjustment:
	a turn of a screw here, a little tightening up there, a drop of oil
		and it would be as good as new.
Inevitably the repair job was not quite so simple.
The mower firmly refused to mow, so I decided to dismantle it.
The garden was soon littered with chunks of metal which had once made up a lawn mower.
But I was extremely pleased wit myself.
I had traced the cause of the trouble.
One of the links in the chain that drives the wheels had snapped.
After buying a new chain
	I was faced with the insurmountable task of putting the confusing jigsaw puzzle together again.
I was not surprised to find that the machine still refused to work after I had reassembled it,
	for the simple reason that I was lef wit several curiously shaped bits of metal
		which did not seem to fit anywhere.
I gave up in despair.
The weeks passed and the grass grew.
When my wife nagged me to do something about it,
	I told her that either I would have to buy a new mower or let the grass grow.
Needless to say our house is now surrounded by a jungle.
Buried somewhere in deep grass there is a rusting lawn mower
	which I have promised to repair one day.
#+end_verse

** words
plead [pliːd] v.找(借口),辩解
ignorance [ˈɪɡnərəns] n.无知,不懂
publication [ˌpʌblɪˈkeɪʃ(ə)n] n.出版物
newlyweds [nil] n.新婚夫妇
gaily [ˈɡeɪli] adv.愉快地
leisure [ˈliːʒər] n.空闲
keen [kiːn] adj.热心的
advisory [ədˈvaɪzəri] adj.咨询的
novice [ˈnɑːvɪs] n.新手
consumer [kənˈsuːmər] n.消费者
assemble [əˈsemb(ə)l] v.装配
outlet [ˈaʊtlet] n.出路
creative [kriˈeɪtɪv] adj.创造性的
handyman [ˈhændimæn] n.手巧的人,能工巧匠
resourceful [rɪˈsɔːrsf(ə)l] adj.足智多谋的
fuse [fjuːz] v.短路(烧断保险丝)
rickety [ˈrɪkəti] adj.要散架的,晃动的
clog [klɑːɡ] v.堵塞
delusion [dɪˈluːʒn] n.错觉
lawn mower [lɔːn ˈmoʊər] n.割草机
adjustment [əˈdʒʌstmənt] n.调整
screw [skruː] n.螺丝钉
dismantle [dɪsˈmænt(ə)l] v.拆卸
chunk [tʃʌŋk] n.(厚)块
snap [snæp] v.绷断
insurmountable [ˌɪnsərˈmaʊntəb(ə)l] adj.不能克服的
jigsaw [ˈdʒɪɡsɔː] n.线锯
nag [næɡ] v.唠叨不休
rust [rʌst] v.生锈

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
