#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 49 The ideal servant
#+begin_verse
What was Bessie's‘little weakness’?

It is a good thing my aunt Harriet died years ago.
If she were alive today
	she would not be able to air her views on her favourite topic of conversation: domestic servants.
Aunt Harriet lived in that leisurely age
	when servants were employed to do housework.
She had a huge, rambling country house called‘The Gables’.
She was sentimentally attached to this house,
	for even though it was far too big for her needs,
	she persisted in living there long after her husband's death.
Before she grew old,
	Aunt Harriet used to entertain lavishly.
I often visited The Gables when I was a boy.
No matter how many guests were present,
	the great house was always immaculate.
The parquet floors shone like mirrors;
	highly polished silver was displayed in gleaming glass cabinets;
	even my uncle's huge collection of books was kept miraculously free from dust.
Aunt Harriet presided over an invisible army of servants
	that continuously scrubbed, cleaned, and polished.
She always referred to them as 'the shifting population',
	for they came and went with such frequency
		that I never even got a chance to learn their names.
Though my aunt pursued what was, in those days, an enlightened policy,
	in that she never allowed her domestic staff to work more than eight hours a day,
	she was extremely difficult to please.
While she always criticized the fickleness of human nature,
	she carried on an unrelenting search for the ideal servant to the end of her days,
	even after she had been sadly disillusioned by Bessie.

Bessie worked for Aunt Harriet for three years.
During that time she so gained my aunt's confidence,
	that she was put in charge of the domestic staff.
Aunt Harriet could not find words to praise Bessie's indus triousness and efficiency.
In addition to all her other qualifications,
	Bessie was an expert cook.
She acted the role of the perfect servant for three years
	before Aunt Harriet discovered her 'little weakness'.
After being absent from The Gables for a week,
	my aunt unexpectedly returned one afternoon with a party of guests
		and instructed Bessie to prepare dinner.
Not only was the meal well below the usual standard,
	but Bessie seemed unable to walk steadily.
She bumped into the furniture and kept mumbling about the guests.
When she came in with the last course -- a huge pudding --
	she tripped on the carpet and the pudding went flylng through the air,
		narrowly missed my aunt,
	and crashed on the dining table with considerable force.
Though this caused great mirth among the guests,
	Aunt Harriet was horrified.
She reluctantly came to the conclusion that Bessie was drunk.
The guests had, of course, realized this from the moment
	Bessie opened the door for them and, long before the final catastrophe,
		had had a difficult time trying to conceal their amusement.
The poor girl was dismissed instantly.
After her departure,
	Aunt Harriet discovered
	that there were piles of empty wine bottles of all shapes and sizes
		neatly stacked in what had once been Bessie's wardrobe.
They had mysteriously found their way there from the wine cellar!
#+end_verse

** words
rambling [ˈræmblɪŋ] adj.杂乱无章的
sentimentally  [ˌsentɪˈmentəli] adv.感情上,多情地
lavishly [ˈlæviʃli] adv.慷慨地,大方地
immaculate [ɪˈmækjələt] adj.清洁的,无污点的
parquet [ˌpɑrˈkeɪ] n.镶木的地板
gleam [ɡlim] v.发亮
preside [ˌpriˈzaɪd] v.指挥
invisible [ɪnˈvɪzəb(ə)l] adj.看不见的,无形的
scrub [skrʌb] v.擦拭,刷洗
enlightened [ɪnˈlaɪt(ə)nd] adj.开明的
fickleness ['fɪklnəs] n.变化无常
unrelenting [ˌʌnrɪˈlentɪŋ] adj.不屈不饶的
disillusion [ˌdɪsɪˈluʒ(ə)n] v.使幻想破灭
industriousness [ɪn'dʌstrɪəsnɪs] n.勤奋
qualification [ˌkwɑləfɪˈkeɪʃ(ə)n] n.资格,能力
mirth [mɜrθ] n.欢笑
stack [stæk] v.整齐地堆放
cellar [ˈselər] n.地窖

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
