#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 50 New Year resolutions
#+begin_verse
What marked the end of the writer's New Year resolutions?

The New Year is a time for resolutions.
Mentally, at least, most of us could compile formidable lists of 'dos' and 'don'ts'.
The same old favourites recur year in year out with monotonous regularity.
We resolve to get up earlier each morning,
	eat less,
	find more time to play with the children,
	do a thousand and one jobs abount house,
	be nice to people we don't like,
	drive carefully,
	and take the dog for a walk every day.
Past experience has taught us that certain accomplishments are beyond attainment.
If remained inveterate smokers,
	it is only because we have so often experienced that frustration that results from failure.
Most of us fail in our efforts at self-improvement
	because our schemes are too ambitious and we never have time to carry them out.
We also make the fundamental error of announcing our resolutions to everybody
	so that we look even more foolish when we slip back into our bad old ways.
Aware of these pitfalls, this year I attempted to keep my resolutions to myself.
I limited myself to two modest ambitions:
	to do physical exercises every morning and to read more of an evening.
An all-night party on New Year's Eve provided me with a good excuse for
	not carrying out either of these new resolutions on the first day of the year,
	but on the second, I applied myself assiduously to the task.

The daily exercises lasted only eleven minutes
	and I proposed to do them early in the morning before anyone had got up.
The self-discipline required to drag myself out of bed eleven minutes earlier than usual
	was considerable.
Nevertheless, I managed to creep down into the living room for two days
	before anyone found me out.
After jumping about on the carpet and twisting the human frame into uncomfortable positions,
	I sat down at the breakfast table in an exhausted condition.
It was this that betrayed me.
The next morning the whole family trooped in to watch the performance.
That was really unsettling, but I fended off the taunts and jibes of the family good-humoredly
	and soon everybody got used to the idea.
However, my ethusiasm waned.
The time I spent at exercises gardually diminished.
Little by little the eleven minutes fell to zero.
By January 10th, I was back to where I had started from.
I argued that if I spent less time exhausting myself at exercises in the morning,
	I would keep my mind fresh for reading when I got home from work.
Resisting the hypnotizing effect of television,
	I sat in my room for a few evenings with my eyes glued to a book.
One night, however, feeling cold and lonely,
	I went downstairs and sat in fromt of the television pretending to read.
That proved to be my undoing, for I soon got back to my old bad habit of
	dozing off in front of the screen.
I still haven't given up my resolution to do more reading.
In fact, I have just bought a book entitled How to Read a Thousand Words a Minute.
#+end_verse

** words
resolution [ˌrezəˈluʃ(ə)n] n.决心
mentally ['mentəli] adv.内心里
compile [kəmˈpaɪl] v.编辑,编制
formidable [fərˈmɪdəb(ə)l] adj.令人畏惧的
recur [rɪˈkɜr] v.再发生,又发生
regularity [ˌregju'lærəti] n.规律性
accomplishment [əˈkʌmplɪʃmənt] n.成就
attainment [əˈteɪnmənt] n.达到
inveterate [ɪnˈvetərət] adj.根深蒂固的
self-improvement n.自我完善
scheme [skim] n.简单的计划,方案
ambitious [æmˈbɪʃəs] adj.雄心勃勃的
pitfall [ˈpɪtˌfɔl] n.意外的困难
modest [ˈmɑdəst] adj.要求不过分的
assiduously [ə'sɪdjʊrslɪ] adv.刻苦地
self-discipline [ˈdɪsəplɪn] n.自我约束
frame [freɪm] n.躯体
betray [bɪˈtreɪ] v.暴露,显露
troop [trup] v.成群结队地走动
unsettle [ʌnˈset(ə)l] v.使不安
taunt [tɔnt] n.嘲笑
jibe [dʒaɪb] n.嘲弄,挖苦
good-humouredly ['hju:mərəsli] adv.和气地,心情好地
wane [weɪn] v.逐渐变小
diminish [dɪˈmɪnɪʃ] v.减少
hypnotize [ˈhɪpnəˌtaɪz] v.使欲睡
undoing [ʌnˈduɪŋ] n.祸根
screen [skrin] n.电视机屏幕

** 单词造句
** 反复听电影片段直到懂关键句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
