#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task15 8-2 方案整合 降维打击1
Task13 课前作业
家庭作业1:
Western Civilization: chapter3
1. [写作]:回答问题[先完成再完美]
2. [泛读:输出倒逼输入]:再阅读n遍找答案
	 skimming+outline+Paraphrase[看着原文答案改句子]
	 这里outline的意思,应该是原文的outline
3. [泛听]:确定topic+查找油管
4. [口语]:跟读部分文章+朗读作文[1中]+summary+查找真题看看哪题能用[1中]
** 1. [写作]:回答问题[先完成再完美]
Early Greece
Q: How did the geography of Greece affect Greek history?
The geography of Greece was compact.
It encompassed mountainous peninsual which encompassed only 45,000 square miles of territory.
The mountainous terrain isolated Greeks from one another,
	which casued that their communities became independent
		and were only ready to fight one another to gain advantage.
Besides, Greece had a long seacoast that provided numerous harbors.
For this reason, the Greeks became seafareres
	who interacted with the outside world and establish colonies
		that spread Greek civilization throughout the Mediterranean region.

The Greeks in a Dark Age (c. 1100--c. 750 B.C.)
Q: Who was Homer, and why was his work used as the basis for Greek education?
Homer has been viewed as one of the greatest poets of all time
	for his great epic poems of early Greece, the Iliad and the Odyssey.
Homer's world reflects the values of artistocratic heros, such courage and honor.
These masterpieces gave the Greeek an idealized past with a cast of heroes
	so that these came to be used as the basis for Greek education.

The World of the Greek City-States
(c. 750--c. 500 B.C.)
Q: What were the chief features of the polis, or city-state,
	and how did the major city-states of Athens and Sparta differ?
In a physical sense,
	the polis encompassed a town or city or even a village and its surrounding countryside.
As a community, the polis consisted of citzens with political rights(adult males),
	citzens with no political rights(women and children), and noncitizens(slaves and resident aliens).
All citizens of a polis possessed basic rights, but these were coupled with responsibilities.


	 The major city-state of Athens and Sparta vary in certain aspects, their origins,
		and how the crises of them are resloved.
	 The Spartans originally becamed unified into a single polis in Laconia.
	 They conquered their neighbours, Laconians and Messenia,
		and turned Laconia and Messenia into slaves.
	 The spartans created a military state so that they could take control of these slaves.
	 Futuremore, the Spartans choosed to isolated themselves from the external world
		to make their military state secure.
	 However, the situation in Athens was different from that in Sparta.
	 Athens established a unified polis on the peninsula of Attica by 700 B.C
		and confronted political turmoil
			by serious economic problems near the end of seventh century B.C.
	 Solon was chosen to solve this crsis,
		 but his economic reforms and political measures were compromises.
	 Then, Cleisthenes continued to reform,
		and a major aim of his reforms was to weaken the power of traditional localities and regions.
	 To conclusion, Sparta transformed into a united city-state in Laconia
		and Athens on the peninsula of Attica.
	 To ensure their power and development Sparta build a military state
		and be close with the outside world.
	 To solve Athens economic crsis Solon and Cleisthenes continued reforming.
	
	
The High Point of Greek Civilization:
Classical Greece
Q: What did the Greeks mean by democracy,
	and in what ways was the Athenian political system a democracy?
	What effect did the two great conflicts of the fifth century B.C.
	---the Persian Wars and the Peloponnesian War---have on Greek civilization?
	
	 The Greeks called their form of government democracy that power was in the hands of the people.
	 Male citizen voted in the assemblies and served as jurors in the courts.
	 State pay for officeholders
		so that poor citizens could hold public office and afford to partcipate in pubic affairs.
	 After the defeat of the Persians,
		Athens provide new leadership against the Persians
			by forming a confederation named the Delian League.
	 The Athenians refused its members to departure
		and used the money in the league treasury
			 to build new temples in Athens without their approval.
	 The Delian League had become the Athenian Empire
		and resulted in a new war all Greece by alarming the other Greek states.
	 The Greek world divided into two major camps: Sparta and its supporters and the Athenian Empire.
	 They had fought against each other for a long time.
	 The war weakened the major Greek states and led to new alliances among the poleis.

** 2. [泛读:输出倒逼输入]:再阅读n遍找答案
	 skimming+outline+Paraphrase[看着原文答案改句子]
** 3. [泛听]:确定topic+查找油管
Aristotle
涉猎很广
哲学家,物理学家,生物学家
定义幸福
政治体系
逻辑学

也有很多错误的观念
存在有原因
物体运动是因为有力推动

** 4. [口语]:跟读部分文章+朗读作文[1中]+summary+查找真题看看哪题能用[1中]
