#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task9 5-1 泛读实战2 教育心理学
家庭作业:
材料: Santrock,J.W. (2017).Educational psychology 6th. McGraw-Hill Education.
1. 泛读chapter 13 MOTIVATION, TEACHING, AND LEARNING 中第二部分AchievementProcesses，第四部分选读部分。
	 算算大概等于做了几套真题阅读? 先完成再完美，不要记录单词含义，不要摘抄习惯用法，不要造句。
2. 练习skimming/scanning/summary/段首尾/Features/1.5h/阅读速度。
3. 记录下实战中的所有问题或困惑
4. 阅读完请判断某水1中教育模式的利弊。
5. [选修]按照今天提供的申请学校的思路，去查找目标学校，学完立刻实践，否则容易忘。
** DONE 1. 泛读
CLOSED: [2024-07-19 Fri 15:13]
	1. chapter 13 MOTIVATION, TEACHING, AND LEARNING 中第二部分AchievementProcesses，第四部分选读部分。
	2. 算算大概等于做了几套真题阅读? 先完成再完美，不要记录单词含义，不要摘抄习惯用法，不要造句。

∙ What are extrinsic and intrinsic motivation? How are they involved in students’ achievement?
∙ What characterizes attribution theory and an attribution approach to students’ achievement?
∙ How does a mastery orientation compare with a helpless orientation and a performance orientation? Why is a growth mindset important in students’ achievement?
∙ What is self-efficacy? What types of instructional strategies benefit students’ self-efficacy?
∙ How are goal setting, planning, and self-monitoring important in improving students’ motivation to achieve?
∙ How can students’ and teachers’ expectations affect students’ motivation?
∙ What is delay of gratification and how does it influence developmental outcomes?
∙ What do values and purpose mean? Why is it important for students to develop a sense of purpose?


∙ How can low-achieving students with low achievement expectations be described and
	how can teachers help them?
∙ What are some strategies students use to protect their self-worth by avoiding failure?
	How can these students be helped?
∙ What characterizes students who procrastinate, and what are some strategies to
	help them?
∙ What characterizes students who are perfectionistic, and how can teachers help students with these	tendencies?
∙ What is anxiety, how does high anxiety interfere with achievement, and what type of
	programs can benefit students with high anxiety?
∙ How can teachers help students who are uninterested or alienated?

** DONE 2. 练习skimming/scanning/summary/段首尾/Features/1.5h/阅读速度。
CLOSED: [2024-07-19 Fri 15:13]

** 3. 记录下实战中的所有问题或困惑
- 仅仅只阅读跟问题相关的,是不是阅读两过少了
- 通过避免失败保持自我价值
- 拖延!

** 4. 阅读完请判断某水1中教育模式的利弊。
- extrinsic and intrinsic motivation: extrinsic motivation by itself is not a good strategy.
	- extrinsic motivation
		doing something to obtain something else(a means to an end)
		eg. study hard for a test in order to obtain a good grade
	- intrinsic motivation
		do something for its own sake(an end in itself)
		eg. study hard for a test because enjoys the content of the course
		four types:
		1. self-determination and personal choice
		2. optimal experiences and flow
		3. interest
		4. cognitive engagement and self-responsibility
- attribution theory
	1. locus: internal or external
	2. stability: remains the same or changes
	3. controllability: the extend to which I can control the cause
- mastery motivation and mindset
	+ orientation
		- mastery orientation
		- helpless orientation
		- performance orientation
	+ mindset
		- growth mindset
		- fixed mindset
- self-efficacy
- goal setting, planning, and self-monitoring
	+ long-term and short-term goals
	+ chanllenging goals
	+ developmental changes and goal-setting
	+ planning and self-monitoring
- delay of gratification
- values and purpose

** 5. [选修]按照今天提供的申请学校的思路，去查找目标学校，学完立刻实践，否则容易忘。
