<<<<<<< HEAD
* task5 3-2 阅读sub-skills
家庭作业:
材料: 剑雅17真题第一套
1. 【必修】剑雅17真题，三篇阅读文章，只看题型。请总结考的是什么题型，尝试总结考察的抽象能力sub-skils是什么?
	 1. 20m 1-13 13=填空 6+判断题(not given) 7
	 2. 20m 14-26 13=配对 4+ 填空题 5+ 多选题 2
	 3. 20m 27-40 14=填空 5+ 判断题 4+ 选择题 5
	 subskills:检索信息的能力,scanning
2. 【必修】精读第一篇文章 why we need to protect polar bears
	 1. 千万别做题
	 2. 标记全文语法+生词+习惯用法(是否造句自选)
3. 【必修】无需跟读，但反复阅读50遍 + 做题(查看正确率)
4. 【选修】阅读'Meditation for Dummies'一书中'Following Your Breath'一文。
	  可以查阅冥想的好处，bing，咕咕咕。写作&口语内容准备task0.5
** The development of the London underground railway 3
In the first half of the 1800s, London's population grew at an astonishing rate,
	and the central area became increasingly congested.
In addition, the expansion of the overground railway network
	resulted in more and more passengers arriving in the capital.
However, in 1846, a Royal Commission decided
	that the railways should not be allowed to enter the City,
		the capital's historic and business centre.
The result was that the overground railway stations formed a ring around the City.
The area within consisted of poorly built, overcrowded slums
	and the streets were full of horse-drawn traffc.
Crossing the City became a nightmare.
It could take an hour and a half to travel 8 km by horse-drawn carriage or bus.
Numerous schemes were proposed to resolve these problems, but few succeeded.

Amongst the most vocal advocates for a solution to London's trafic problems was Charles Pearson,
	who worked as a solicitor for the City of London.
He saw both social and economic advantages in building an underground railway
	that would link the overground railway stations together
		and clear London slums at the same time.
His idea was to relocate the poor workers
			who lived in the inner-city slums
		to newly constructed suburbs,
	and to provide cheap rail travel for them to get to work.
Pearson's ideas gained support amongst some businessmen
	and in 1851 he submitted a plan to Parliament.
It was rejected,
	but coincided with a proposal from another group for an underground connecting line,
		which Parliament passed.
		
The two groups merged and established the Metropolitan Railway Company in August 1854.
The company's plan was to construct an underground railway line
	from the Great Western Railway's (GWR) station at Paddington
		to the edge of the City at Farringdon Street - a distance of almost 5 km.
The organisation had diffculty in raising the funding for such a radical and expensive scheme,
	not least because of the critical articles printed by the press.
Objectors argued that the tunnels would collapse under the weight of traffc overhead,
	buildings would be shaken
	and passengers would be poisoned by the emissions from the train engines.
However, Pearson and his partners persisted.

The GWR, aware
		that the new line would finally enable them to run trains into the heart of the City,
	invested almost $250,000 in the scheme.
Eventually, over a five-year period, $1m was raised.
The chosen route ran beneath existing main roads to minimise the expense of demolishing buildings.
Originally scheduled to be completed in 21 months,
	the construction of the underground line took three years.
It was built just below street level using a technique known as 'cut and cover'.
A trench about ten metres wide and six metres deep was dug,
	and the sides temporarily held up with timber beams.
Brick walls were then constructed,
	and fnally a brick arch was added to create a tunnel.
A two-metre-deep layer of soil was laid on top of the tunnel and the road above rebuilt.

The Metropolitan line, which opened on 10th January 1863,
	was the world's first underground railway.
On its first day, almost 40,000 passengers were carried between Paddington and Farringdon,
	the journey taking about 18 minutes.
By the end of the Metropolitan's frst year of operation,
	9.5 million journeys had been made.
	
Even as the Metropolitan began operation,
	the frst extensions to the line were being authorised;
		these were built over the next five years,
		reaching Moorgate in the east of London and Hammersmith in the west.
The original plan was to pull the trains with steam locomotives,
		using firebricks in the boilers to provide steam,
	but these engines were never introduced.
Instead, the line used specially designed locomotives
	that were fitted with water tanks in which steam could be condensed.
However, smoke and fumes remained a problem,
	even though ventilation shafts were added to the tunnels.
	
Despite the extension of the underground railway,
	by the 1880s, congestion on London's streets had become worse.
The problem was partly
	that the existing underground lines formed a circuit around the centre of London
			and extended to the suburbs,
		but did not cross the capital's centre.
The 'cut and cover' method of construction was not an option in this part of the capital.
The only alternative was to tunnel deep underground.

Although the technology to create these tunnels existed,
	steam locomotives could not be used in such a confined space.
It wasn't until the development of a reliable electric motor,
		and a means of transferring power from the generator to a moving train,
	that the world's first deep-level electric railway, the City & South London, became possible.
The line opened in 1890, and ran from the City to Stockwell, south of the River Thames.
The trains were made up of three carriages and driven by electric engines.
The carriages were narrow and had tiny windows just below the roof
	because it was thought that passengers would not want to look out at the tunnel walls.
The line was not without its problems,
	mainly caused by an unreliable power supply.
Although the City & South London Railway was a great technical achievement,
	it did not make a profit.
Then, in 1900 the Central London Railway, known as the 'Tuppenny Tube',
	began operation using new electric locomotives.
It was very popular
	and soon afterwards new railways and extensions were added to the growing tube network.
By 1907, the heart of today's Underground system was in place.
** experession
In the first half of the 1800s
at an astonishing rate
congested: full of traffic
In addition
the expansion of sth.
the overground railway network
resulted in
more and more
sb. decide that + ...
The result was that + ...
formed a ring around sp.
within: during a certain period of time
consisted of
slums:a house or an area of a city that is in very bad condition, where very poor people live
were full of
horse-drawn traffc: vehicles are pulled by a horse
It take st. to do sth.
carriage:a vehicle with wheels that is pulled by a horse, used in the past
Numerous:many
were proposed to do sth.
resolve these problems

amongst sb. be sb.
vocal :expressing strong opinions publicly, especially about things that you disagree with 
advocates for:to publicly support a particular way of doing something
worked as sjob. for scompany.
solicitor :a type of lawyer in Britain who gives legal advice, prepares the necessary documents when property is bought or sold, and defends people, especially in the lower courts of law  lawyer, advocate, barrister
see xx advantages in doing sth.
an underground railway
at the same time:
sb's idea is to do sth
relocate sb. to sp.
provide sth. for sb.
get to work
gain support
submit a plan to ...
be coincided with sb.: to come together in position or happen at or near the same time
proposal:a plan or suggestion which is made formally to an official person or group, or the act of making it

establish scompany.
sb's plan was to do sth.
a distance of almost 5 km
have diffculty in doing sth.
raising the funding/money for sth.
radical 
not least
because of
A. be printed by B.
sb. argues that + ...
emissions: a gas or other substance that is sent into the air

be aware that + ...
enable sb. to do sth.
invest money.
in the scheme
main road
minimise the expense of sth.
be scheduled to do sth.
A. be known as B.
trench:a long narrow hole dug into the surface of the ground
dig a trench/ a trench is dug
timber:wood used for building or making things
beams:a long heavy piece of wood or metal used in building houses, bridges etc
Brick:a hard block of baked clay used for building walls, houses etc
A two-metre-deep layer of soil
on top of the tunnel

on its first day
sb. be carried between A. and B.
the journey taking ...: 独立主格
by the end of sth.


authorised:to give official permission for something
the first extensions to the line
reach placeA and placeB
use sth. to do sth.
introduced:to bring a plan, system, or product into use for the first time
locomotive:a railway engine
be fitted with
steam be condensed in: shortened
remain a problem
even though
A. be added to b.
shaft:a passage which goes down through a building or down into the ground, so that someone or something can get in or out

the extension of sth.
the problem was partly that + ..., but did not do sth.
the alternative is to do sth.
in a confined space
It wasn't until sth. that + ...
a means of
were made up of sth.
it is thought that + ...
want to do sth.
be without problems.
power supply
make a profit
be in place: working or ready to work; established.
=======
* Task 5 1-1
Task5 家庭作业：精听+精读
所⽤素材：剑雅16 第⼀套真题听⼒第四题
1. 听⽂章（⼀定不要先阅读听⼒脚本）,答题,记录对错
2. 认真阅读听⼒脚本,标注所有⽣词(⽂中含义),语法(参考新概念英语及三本语法书),摘抄习惯⽤法(不用造句)
3. 跟读⽂章edge * 50遍
4. 模拟考试，听⽂章，答题，记录对错。
5. 继续跟读 50遍 (task5+直播课程6结束后)
6. 模仿第4步。找到拿听⼒满分的理论信⼼
注意：请务必按照上⾯顺序⾛（5&6两步请直播课程6结束后进⾏）


** 剑雅17-位置
题:p15
脚本:100
答案:

** 总结
不再跟读50遍

** 疑惑
写出您在完成这个作业过程中产⽣的疑惑，然后带着这个疑惑去听课。
1. !我已经跟读完新2-3了,裸考仍然只能拿2分.如果要做到全部听懂,还需要跟读什么?
	 跟读学术类内容,具体学术类是什么素材? 后面精读要不要造句?
2. !由于泛读了很多内容,很多词看脚本能看懂,听还是听不懂,要做些什么? 不够熟,没有内化,泛听
	 泛读看到认识,听到不认识正常的
3. 审题这方面要怎么利用间隙处理好
4. 做题时,听的时候如何判断到哪里了
5. 为什么再读50遍?
	 peek experience
** 一考 2
1.
2. 
3. 
4. meditation
5. 
6. workingout
7. tree
8. 
9. bed
10. 
** 二考 10
1. puzzle
2. logic
3. confusion
4. meditation
5. stone
6. coins
7. tree
8. breathing
9. paper
10. anxiety

** audioscripts
#+begin_verse
Labyrinths have existed for well over 4,000 years.
Labyrinths and labyrinthine symbols have been found in regions
	as diverse as modern-day Turkey, Ireland, Greece, and India.
There are various designs of labyrinth
	but what they all have in common is a winding spiral path
		which leads to a central area.
There is one starting point at the entrance and the goal is to reach the central area.
Finding your way through a labyrinth involves many twists and turns,
	but it's not possible to get lost as there is only one single path.
	
In modern times, the word labyrinth has taken on a different meaning
	and is often used as a synonym for a maze.
A maze is quite different
	as it is a kind of puzzle with an intricate network of paths.
Mazes became fashionable in the 15th and 16th centuries in Europe,
	and can still be found in the gardens of great houses and palaces.
The paths are usually surrounded by thick, high hedges
	so that it's not possible to see over them.
Entering a maze usually involves getting lost a few times
	before using logic to work out the pattern
		and find your way to the centre and then out again.
There are lots of dead ends and paths which lead you back to where you started.
The word 'maze' is believed to come from a Scandinavian word for a state of confusion.
This is where the word 'amazing' comes from.

Labyrinths, on the other hand, have a very different function.
Although people now often refer to things they find complicated as labyrinths,
	this is not how they were seen in the past.
The winding spiral of the labyrinth has been used for centuries as a metaphor for life's journey.
It served as a spiritual reminder
	that there is purpose and meaning to our lives and helped to give people a sense of direction.
Labyrinths are thought to encourage a feeling of calm
	and have been used as a meditation and prayer tool in many cultures over many centuries.
	
The earliest examples of the labyrinth spiral pattern have been found carved into stone,
	from Sardinia to Scandinavia, from Arizona to India to Africa.
In Europe, these spiral carvings date from the late Bronze Age.
The Native American Pima tribe wove baskets with a circular labyrinth design
	that depicted their own cosmology.
In Ancient Greece, the labyrinth spiral was used on coins around four thousand years ago.
Labyrinths made of mosaics were commonly found
	in bathhouses, villas and tombs throughout the Roman Empire.
	
In Northern Europe, there were actual physical labyrinths designed for walking on.
These were cut into the turf or grass, usually in a circular pattern.
The origin of these walking labyrinths remains unclear,
	but they were probably used for fertility rites which may date back thousands of years.
Eleven examples of turf labyrinths survive today,
	including the largest one at Saffron Walden, England,
		which used to have a large tree in the middle of it.
		
More recently labyrinths have experienced something of a revival.
Some believe that walking a labyrinth promotes healing and mindfulness,
	and there are those who believe in its emotional and physical benefits,
		which include slower breathing and a restored sense of balance and perspective.
This idea has become so popular
	that labyrinths have been laid into the floors of spas,
		wellness centres and even prisons in recent years.
		
A pamphlet at Colorado Children's Hospital informs patients
	that 'walking a labyrinth can often calm people in the midst of a crisis'.
And apparently, it's not only patients who benefit.
Many visitors find walking a labyrinth less stressful than sitting in a corridor or waiting room.
Some doctors even walk the labyrinth during their breaks.
In some hospitals,
	patients who can't walk can have a paper 'finger labyrinth' brought to their bed.
The science behind the theory is a litle sketchy,
	but there are dozens of small-scale studies
		which support claims about the benefits of labyrinths.
For example, one study found
	that walking a labyrinth provided 'short-term calming, relaxation, and relief from anxiety'
		for Alzheimer's patients.
		
So, what is it about labyrinths that makes their appeal so universal? Well ...
#+end_verse

** expression
#+begin_verse
for st.: eg. for 1000 years
as diverse as: including many different types of people or things
have in common
lead to sp.
starting point
at the entrance
the goal is to do sth.
reach sp.
twists and turns: 玩玩扰扰
find sb's way (to sp.)
involve sth./doing sth.
it's not possible to do sth.
get adj.: be adj.
in modern times
take on: 用作
be used as: 被用作
a synonym for A: a word with the smeaning as another word in the slanguage
intricate: adj. containing many small parts or details that all work or fit together
a network of paths: 网状道路
become fashionable
be surrounded by sth.:
see over sp.: to walk around and examine (a place) carefully
hedges: a row of small bushes or trees growing close together, usually dividing one field or garden from another
use sth. to do sth.
work out
dead ends
be believed to do sth.
come from sp.
a state of confusion
refer to A as B
a metaphor for sth.
serve as: 被用于
a spiritual reminder: relating to your spirit rather than to your body or mind
purpose and meaning to our lives
help to do sth.
give sb. sth.
a sense of direction
be thought to do sth.
a feeling of sth.
the examples of sth.
be found done sth.: 被发现被做某事
be carved into stone: 被雕刻到石头
date from tp.
be used on sth.
around xx years ago
be made of
be designed for doing
be cut into
in a circular pattern
remain unclear: is unclear
fertility rites: 生育仪式
date back thousands of years
in the middle of sth.
experience a revival:
something of: to some degree
believe in sth.
a sense of sth.
be laid into: 被放置在
in recent years
inform sb. that ...
in the midst of sth.
find doing A adj.-er than doing B
during sb's breaks
be brought to sp.
dozens of sth.
for example
one study found that ...
relief from anxiety
make sth. adj.


winding: adj. 弯曲的
spiral: n. a line in the form of a curve that winds around a central point, moving further away from the centre all the time
labyrinth: labyrinthine  adj.
	a large network of paths or passages which cross each other, making it very difficult to find your way
Bronze:a hard metal that is a mixture of copper and tin
cosmology: the science of the origin and structure of the universe, especially as studied in astronomy
mosaics: a pattern or picture made by fitting together small pieces of coloured stone, glass etc
villa:a big house in the country with a large garden
tomb: a stone structure above or below the ground where a dead person is buried
turf:a surface that consists of soil with grass on top, or an artificial surface that looks like this
revival: a process in which something becomes active or strong again
promote:to help something to develop or increase
restored:feeling better and stronger
wellness:the state of being healthy
pamphlet:a very thin book with paper covers, that gives information about something
crisis:a situation in which there are a lot of problems that must be dealt with quickly so that the situation does not get worse or more dangerous
corridor:a long narrow passage on a train or between rooms in a building, with doors leading off it
sketch:not thorough or complete, and not having enough details to be useful
#+end_verse
>>>>>>> 82af5a975e3c2282ac539c40cc617aad1565daef
