#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Task5 2-1 听力满分计划
Task5 家庭作业：精听+精读
所⽤素材：剑雅16 第⼀套真题听⼒第四题
1. 听⽂章（⼀定不要先阅读听⼒脚本）,答题,记录对错
2. 认真阅读听⼒脚本,标注所有⽣词(⽂中含义),语法(参考新概念英语及三本语法书),摘抄习惯⽤法(不用造句)
3. 跟读⽂章edge * 50遍
4. 模拟考试，听⽂章，答题，记录对错。
5. 继续跟读 50遍 (task5+直播课程6结束后)
6. 模仿第4步。找到拿听⼒满分的理论信⼼
注意：请务必按照上⾯顺序⾛（5&6两步请直播课程6结束后进⾏）


** 剑雅17-位置
题:p15
脚本:100
答案:

** 总结
不再跟读50遍

** 疑惑
写出您在完成这个作业过程中产⽣的疑惑，然后带着这个疑惑去听课。
1. !我已经跟读完新2-3了,裸考仍然只能拿2分.如果要做到全部听懂,还需要跟读什么?
	 跟读学术类内容,具体学术类是什么素材? 后面精读要不要造句?
2. !由于泛读了很多内容,很多词看脚本能看懂,听还是听不懂,要做些什么? 不够熟,没有内化,泛听
	 泛读看到认识,听到不认识正常的
3. 审题这方面要怎么利用间隙处理好
4. 做题时,听的时候如何判断到哪里了
5. 为什么再读50遍?
	 peek experience
** 一考 2
1.
2. 
3. 
4. meditation
5. 
6. workingout
7. tree
8. 
9. bed
10. 
** 二考 10
1. puzzle
2. logic
3. confusion
4. meditation
5. stone
6. coins
7. tree
8. breathing
9. paper
10. anxiety

** audioscripts
#+begin_verse
Labyrinths have existed for well over 4,000 years.
Labyrinths and labyrinthine symbols have been found in regions
	as diverse as modern-day Turkey, Ireland, Greece, and India.
There are various designs of labyrinth
	but what they all have in common is a winding spiral path
		which leads to a central area.
There is one starting point at the entrance and the goal is to reach the central area.
Finding your way through a labyrinth involves many twists and turns,
	but it's not possible to get lost as there is only one single path.
	
In modern times, the word labyrinth has taken on a different meaning
	and is often used as a synonym for a maze.
A maze is quite different
	as it is a kind of puzzle with an intricate network of paths.
Mazes became fashionable in the 15th and 16th centuries in Europe,
	and can still be found in the gardens of great houses and palaces.
The paths are usually surrounded by thick, high hedges
	so that it's not possible to see over them.
Entering a maze usually involves getting lost a few times
	before using logic to work out the pattern
		and find your way to the centre and then out again.
There are lots of dead ends and paths which lead you back to where you started.
The word 'maze' is believed to come from a Scandinavian word for a state of confusion.
This is where the word 'amazing' comes from.

Labyrinths, on the other hand, have a very different function.
Although people now often refer to things they find complicated as labyrinths,
	this is not how they were seen in the past.
The winding spiral of the labyrinth has been used for centuries as a metaphor for life's journey.
It served as a spiritual reminder
	that there is purpose and meaning to our lives and helped to give people a sense of direction.
Labyrinths are thought to encourage a feeling of calm
	and have been used as a meditation and prayer tool in many cultures over many centuries.
	
The earliest examples of the labyrinth spiral pattern have been found carved into stone,
	from Sardinia to Scandinavia, from Arizona to India to Africa.
In Europe, these spiral carvings date from the late Bronze Age.
The Native American Pima tribe wove baskets with a circular labyrinth design
	that depicted their own cosmology.
In Ancient Greece, the labyrinth spiral was used on coins around four thousand years ago.
Labyrinths made of mosaics were commonly found
	in bathhouses, villas and tombs throughout the Roman Empire.
	
In Northern Europe, there were actual physical labyrinths designed for walking on.
These were cut into the turf or grass, usually in a circular pattern.
The origin of these walking labyrinths remains unclear,
	but they were probably used for fertility rites which may date back thousands of years.
Eleven examples of turf labyrinths survive today,
	including the largest one at Saffron Walden, England,
		which used to have a large tree in the middle of it.
		
More recently labyrinths have experienced something of a revival.
Some believe that walking a labyrinth promotes healing and mindfulness,
	and there are those who believe in its emotional and physical benefits,
		which include slower breathing and a restored sense of balance and perspective.
This idea has become so popular
	that labyrinths have been laid into the floors of spas,
		wellness centres and even prisons in recent years.
		
A pamphlet at Colorado Children's Hospital informs patients
	that 'walking a labyrinth can often calm people in the midst of a crisis'.
And apparently, it's not only patients who benefit.
Many visitors find walking a labyrinth less stressful than sitting in a corridor or waiting room.
Some doctors even walk the labyrinth during their breaks.
In some hospitals,
	patients who can't walk can have a paper 'finger labyrinth' brought to their bed.
The science behind the theory is a litle sketchy,
	but there are dozens of small-scale studies
		which support claims about the benefits of labyrinths.
For example, one study found
	that walking a labyrinth provided 'short-term calming, relaxation, and relief from anxiety'
		for Alzheimer's patients.
		
So, what is it about labyrinths that makes their appeal so universal? Well ...
#+end_verse

** expression
#+begin_verse
for st.: eg. for 1000 years
as diverse as: including many different types of people or things
have in common
lead to sp.
starting point
at the entrance
the goal is to do sth.
reach sp.
twists and turns: 玩玩扰扰
find sb's way (to sp.)
involve sth./doing sth.
it's not possible to do sth.
get adj.: be adj.
in modern times
take on: 用作
be used as: 被用作
a synonym for A: a word with the smeaning as another word in the slanguage
intricate: adj. containing many small parts or details that all work or fit together
a network of paths: 网状道路
become fashionable
be surrounded by sth.:
see over sp.: to walk around and examine (a place) carefully
hedges: a row of small bushes or trees growing close together, usually dividing one field or garden from another
use sth. to do sth.
work out
dead ends
be believed to do sth.
come from sp.
a state of confusion
refer to A as B
a metaphor for sth.
serve as: 被用于
a spiritual reminder: relating to your spirit rather than to your body or mind
purpose and meaning to our lives
help to do sth.
give sb. sth.
a sense of direction
be thought to do sth.
a feeling of sth.
the examples of sth.
be found done sth.: 被发现被做某事
be carved into stone: 被雕刻到石头
date from tp.
be used on sth.
around xx years ago
be made of
be designed for doing
be cut into
in a circular pattern
remain unclear: is unclear
fertility rites: 生育仪式
date back thousands of years
in the middle of sth.
experience a revival:
something of: to some degree
believe in sth.
a sense of sth.
be laid into: 被放置在
in recent years
inform sb. that ...
in the midst of sth.
find doing A adj.-er than doing B
during sb's breaks
be brought to sp.
dozens of sth.
for example
one study found that ...
relief from anxiety
make sth. adj.


winding: adj. 弯曲的
spiral: n. a line in the form of a curve that winds around a central point, moving further away from the centre all the time
labyrinth: labyrinthine  adj.
	a large network of paths or passages which cross each other, making it very difficult to find your way
Bronze:a hard metal that is a mixture of copper and tin
cosmology: the science of the origin and structure of the universe, especially as studied in astronomy
mosaics: a pattern or picture made by fitting together small pieces of coloured stone, glass etc
villa:a big house in the country with a large garden
tomb: a stone structure above or below the ground where a dead person is buried
turf:a surface that consists of soil with grass on top, or an artificial surface that looks like this
revival: a process in which something becomes active or strong again
promote:to help something to develop or increase
restored:feeling better and stronger
wellness:the state of being healthy
pamphlet:a very thin book with paper covers, that gives information about something
crisis:a situation in which there are a lot of problems that must be dealt with quickly so that the situation does not get worse or more dangerous
corridor:a long narrow passage on a train or between rooms in a building, with doors leading off it
sketch:not thorough or complete, and not having enough details to be useful
#+end_verse

** Stoicism
#+begin_verse
Ancient philosophy is not just about talking or lecturing,
	or even reading long, dense books.
In fact, it is something people have used throughout history
	– to solve their problems
		and to achieve their greatest triumphs.

Specifically, I am referring to Stoicism,
	which, in my opinion, is the most practical of all philosophies
		and therefore the most appealing.
Stoicism was founded in Ancient Greece by Zeno of Citium in the early 3rd century BC,
	but was practised by the likes of Epictetus, Cato, Seneca and Marcus Aurelius.
Amazingly, we still have access to these ideas,
	despite the fact that the most famous Stoics never wrote anything down for publication.
Cato definitely didn’t.
Marcus Aurelius never intended his Meditations to be anything but personal.
Seneca’s letters were, well,
	letters and Epictetus’ thoughts come to us by way of a note-taking student.

Stoic principles were based on the idea
	that its followers could have an unshakable happiness in this life
		and the key to achieving this was virtue.
The road to virtue, in turn, lay in understanding
	that destructive emotions, like anger and jealousy, are under our conscious control
		– they don’t have to control us,
	because we can learn to control them.
In the words of Epictetus:
	“external events I cannot control,
		but the choices I make with regard to them.
	I do control”.

The modern day philosopher and writer Nassim Nicholas Taleb defines a Stoic as someone
	who has a different perspective on experiences
		which most of us would see as wholly negative;
	a Stoic “transforms fear into caution,
		pain into transformation,
		mistakes into initiation and desire into undertaking”.
Using this definition as a model,
	we can see that throughout the centuries Stoicism has been practised in more recent history
			by kings, presidents, artists, writers and entrepreneurs.

The founding fathers of the United States were inspired by the philosophy.
George Washington was introduced to Stoicism by his neighbours at age seventeen,
	and later, put on a play based on the life of Cato to inspire his men.
Thomas Jefferson kept a copy of Seneca beside his bed.

Writers and artists have also been inspired by the stoics.
Eugène Delacroix, the renowned French Romantic artist
	(known best for his painting Liberty Leading the People) was an ardent Stoic,
	referring to it as his “consoling religion”.

The economist Adam Smith’s theories on capitalism were significantly influenced by the Stoicism
	that he studied as a schoolboy,
	under a teacher who had translated Marcus Aurelius works.

Today’s political leaders are no different,
	with many finding their inspiration from the ancient texts.
Former US president Bill Clinton rereads Marcus Aurelius every single year,
	and many have compared former President Obama’s calm leadership style to that of Cato.
Wen Jiabao the former prime minister of China,
	claims that Meditations is one of two books he travels with
	and that he has read it more than one hundred times over the course of his life.

Stoicism had a profound influence on Albert Ellis,
	who invented Cognitive Behaviour Therapy,
	which is used to help people manage their problems
		by changing the way that they think and behave.
It’s most commonly used to treat depression.
The idea is that we can take control of our lives
	by challenging the irrational beliefs
		that create our faulty thinking, symptoms and behaviours by using logic instead.

Stoicism has also become popular in the world of business.
Stoic principles can build the resilience and state of mind
		required to overcome setbacks
	because Stoics teach turning obstacles into opportunity.
A lesson every business entrepreneur needs to learn.

I would argue that studying Stoicism is as relevant today
	as it was 2,000 years ago,
	thanks to its brilliant insights into how to lead a good life.
At the very root of the thinking, there is a very simple way of living
	- control what you can and accept what you can’t.
This is not as easy as it sounds
	and will require considerable practice
	– it can take a lifetime to master.
The Stoics also believed the most important foundation
	for a good and happy life is not money, fame, power or pleasure,
	but having a disciplined and principled character
	– something which seems to resonate with many people today.
#+end_verse
