#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Task3 0-1 习惯用法+工具使用+英语学习框架复习 
家庭作业：
材料选择：“The Best Life Stories: 150 Real-life Tales of Resilience, Joy, and Hope
-all under 150 words ”
1. 读懂本⽂ （单词+语法+习惯⽤法）
2. 摘抄习惯⽤法+句型 (请务必等听完task1&task2 的直播课程后进⾏)
3. 跟读本⽂ （edge） 50遍+
4. 尝试⼜语复述本⽂（接受汉语复述）。 故事梗概
5. 英语长难句，英语为母语的⼈，⽇常⽣活到底使⽤与否？
		用
** questions
写出您在完成这个作业过程中产⽣的疑惑，然后带着这个疑惑去听课。
问题⼀:不认识的单词但不常用的,需要摘抄和造句吗?
问题⼆:?
问题三:?
* article
#+begin_verse
Lazy Summers

A single fly swooped around my head making that familiar buzzing sound.
I started to swat it away, but then stopped when I realized it made me happy.
How odd, I thought.
A fly is bringing a smile to my face.
I couldn't understand it until I heard the buzzing sound again.
Then I knew. It was the sound of summer.
It was that familiar buzzing that joined in the chorus of childhood laughter
	during so many lazy summers.
Suddenly I had memories of straw hats and bike rides and lazy rivers;
Fourth of July cookouts and campouts and hideouts; sunburns and secret forts and double-dog dares.
The memories swirled around my head like that fly, reminding me of some of my happiest days.
I decided
	the fly should stay with me today to accompany my thoughts while I reminisced some more. 
#+end_verse
** expression
swoop
- A single newbeen is swooping around my head.
- There are some flies swooping around the shit which you just stamped.
- If the police arrived on the scene, they would see a fly swooping around the shit.
buzz
- It's impossible for a cat to make a buzzing noise.
- I heard a buzzing sound in the morning which your iphone made.
- I heard a strange buzzing noise from the kitchen.
swat it away
- I wished I had swated it away at the first time.
- I tried to swat the fly away from my house.
- The woman who is swating a fly away is your English teacher.
bring a smile to my face
- The arrival of my friend, Zhangyan, always brings a smile to my face.
- It brought a smile to her face to receive a gift from her husband.
- He said he found Beijing very exciting, which brought a smile to my face.
A. join in the chorus of B.
- Just a moment earlier, some foreigners joined in the chorus of busmen who are striking.
- Some strange noises have joined in the chorus of these laughter.
- He joined in the chorus of the group to stand to attention.
have memories of
- After he had memories of life before his car accident, everything returned to normal.
- He makes no effort to have memories of the right answer.
- I'm glad that you have memories of your father's birthday.
swirl around
- The newbees swirled around her head, reminding her of some unpleasant time at the monastery.
- I couldn't fall asleep because the buzzing noises swirled around me last night.
- I attempted to prevent myself from the buzzing noises swirling around my head.
reminisce (about)
- A group of pop singer is reminiscing about the performance which they gave at the station.
- The captain has reminisced about the sinking colossal.
- A group of pianist was reminiscing about their hard early years.
