* task1
** 设置思路：
课前：⾃⼰按要求完成作业
课中：课上讲解思路
课后：再做⼀遍

** 家庭作业：
材料：阅读Humans of New York
要求：
1. 通读⽂章 + 查阅不会单词&习惯⽤法&语法
2. 学会使⽤edge浏览器的真⼈发⾳功能
3. 反复跟读⽂章,遍数不限（但需熟读成诵）
4. 习惯⽤法造句 x 3

*** 教学⽬标：
1. 学会查字典+语法书(三本语法书)+习惯⽤法(google)=建⽴读懂⼀切英⽂⽂本的信⼼和学会读懂⽂本的⽅法论。
2. 掌握edge 浏览器的真⼈发⾳功能，给以后跟读任何⽂本做技术铺垫。
3. ⼤概捋清阅读与听⼒的关系,以及提升听⼒的⽅法。

"He makes me want to know about little things, so that I can teach him.
Like when we sit by this lake,
	I wish I knew what kind of turtle that was, so I could tell him.
And I want to figure out what kind of duck that is,
	so I can tell him all about it the next time we come."
"What do you want most for him?"
"Whatever his dreams are, I'm down to ride for him."
"What's your biggest fear for him?"
"That he won't try.
If he doesn't try, I'll be hurt.
Cause then we'll never know how far he'd get."

*** 习惯用法造句
a so that b... N2L59
I wish I knew that ... (尝试查阅wish的⽤法)
sb. figure out sth.
be down to ride
if ⼀般现在时，⼀般将来时。 N2L16

*** Asking questions
1. Why does he want to know about little things?
	 so that he can teach his child.
2. Did the man know what kind of turtle that was?
	 No, he didn’t.
3. Why did the man want to know what kind of duck that was?
	 so he can tell his child all about it the next time they come.
4. What does the man want most for his child?
	 fulfill his dream.
5. What’s his biggest fear for the child?
	 He won’t even try.
	 

** 答疑解惑
写出您在完成这个作业过程中产⽣的疑惑，然后带着这个疑惑去听课。
问题⼀：？
问题⼆：？
问题三：？
…
解决问题优先级如下：
1. ⾃⼰尝试解决，请勿做伸⼿党。
2. 解决不了尝试群⾥请教。
3. 期待下次直播课程我会课上解决。
4. 直播课程会预留答疑解惑时间，可以问。
5. 直接私信我。（您⽆需⾛完前4步才找我，但我强烈建议经过前四步）

** 作业上交时间/地点
时间：下次直播课程开始前
地点： VX群
