#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task13 7-2 写作3 task2+task1
	In some countries, more and more people are becoming interested in finding out about the history of the house or building they live in.
	
	What are the reasons for this?
	
	How can people research this?

作业1：
读：
1. 审题+回顾评分标准
2. 泛读话题相关⽂章：总结内容+结构+表达
3. 精读⾼分范⽂（PDF⽂件） ：阅读内容+标记结构（句间+段内+段间+篇章outline）
3.5. 学习使⽤https://writing9.com （查找任意task1+task2真题范⽂）
练：
4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过本步骤。
改：
5. 修改单词（同义词）+习惯⽤法+语法⼤结构（丰富程度）
6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。
6. 星座⼩组：共同准备，互相讨论，互相提供修改建议。	 
	 
作业2:
A类 G类 Task1:更简单粗暴的备考⽅案
1. 审题+精读范⽂=内容+结构+表达
2. 动笔写，即模考（前中后）
托福 Task1:更简单粗暴的备考⽅案
1. 审题=精读阅读材料（练习skimming） +精听听⼒脚本（练习take notes）
2. 精读范⽂=内容+结构+表达
3. 动笔写，即模考（前中后）
参考上⾯的⽅案：
1. 按考试类别，阅读3道真题的⾼分范⽂，并分析【结构】与【内容】
	 
作业3：
汉语写作（可全英，或半英半汉）
1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。
** DONE 课间作业
CLOSED: [2024-08-02 Fri 09:53]
语法大结构:
	- 3大从句 (n.adj.adv.)
	- 非谓语 (to do & doing & done 定语状语)
	- 虚拟语气
	- 特殊句型(强调etc,主语从句)
	- 特殊结构(needn't have done + should have done etc.)
	- 谓语结构 (时态主动&时态被动&情态动词主动&情态动词被动&情态动词表推测)
** 作业1: Task2
*** DONE 读：1. 审题+回顾评分标准
CLOSED: [2024-08-02 Fri 09:56]
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?
- 词汇丰富程度: 单词+习惯用法
	+ 词汇丰富: 同义词汇/习惯用法总量大, 总词汇量大, 靠泛读解决
		eg. important, important, important VS important, of importance, crucial 
	+ 达意准确: 更具体的词汇要优于更抽象的词汇, 仍旧是总词汇要大
		eg. fruit VS apple
	+ 标点符号: 逗号+句号
	+ 拼写错误: morning vs monring,仍然可以得满分, 因为只要是人类就会有错误
	+ 词汇搭配错误: 习惯用法的介词有点错误,也没事
- 语法多样性及准确性: 语法
	+ 在精读的时候练,而不是写作的时候. NCE23+Pattern Drill+红皮书
	+ 丰富多样的语法结构: 整理出大语法结构,用大语法结构和作文去检查是否出现,没有就想法弄出来
	+ 语法错误: 语法的三单,单复数没问题,大语法结构没错就行
- 连贯与衔接: 结构(outline)
	+ 连贯
	+ 有条理地排序,推进
- 写作任务回应情况: 内容
	1. 题目问啥,作文就写啥.每个论点内容长度控制得差不多.
	2. 始终一个论点,不要缺乏论点
- 总结:
	+ 内容+结构: 可以脱离英语去练习,中文的水平一般是英文水平的上限
	+ 结构易拿高分(8-9). 词汇+语法需有些敬畏,母语者一般8-8.5. 内容只能靠积累.

*** DONE 读：2. 泛读话题相关⽂章：总结内容+结构+表达
CLOSED: [2024-08-02 Fri 09:59]

*** 读：3. 精读⾼分范⽂（PDF⽂件）： 阅读内容+标记结构（句间+段内+段间+篇章outline）

**** DONE 3.5. 学习使⽤https://writing9.com （查找任意task1+task2真题范⽂）
CLOSED: [2024-08-02 Fri 10:01]
**** 8
Purchasing a property such as a house or a building is categorized as a huge decision.
*So*, in some countries, many people try to determine the house's history
	before they have decided to move in.
wusd: 未复述题目,只回答了why,没回答how
	
There are many reasons why many residence owners find out about the building's background.
*For example*,
	a lot of countries particularly in Asia have similar mysterious myths about life after death.
They usually believe
	that buying a house
			where criminal situations have happened or people have suicide
		could give their life struck in disastrous luck.
*Moreover*, in some regions in Europe,
	most of the real estate were used as a palace before
	and the former owners probably were a royal family.
*Therefore*, a lot of assets have been used for several decades
	and deserve to be preserved in the museum.
wusd: 段首topic sentence
	
*However*, there are various ways to reach the residence's history.
*Firstly*, ask the information from local residents,
	especially those who have been living there for a long time
		because they could have enough pieces of information or experience about the house.
*As well as*, plenty of informative data could be discovered on online platforms.
*For instance*,
	the residence might have been sold by the previous owner or the oldest owners on the internet
		and they may provide the estate details
	*besides* if the building has been rented before,
		the tenants might write some housing reviews.
wusd: 段首topic sentence

*To conclude*, every home has its own history.
Inspecting the building's background could offer much beneficial information
	such as what we should do or what we should prepare before moving in.
wusd: 总结有瑕疵,只有分1,没有分2
--------------------
wusd: 词汇量大且丰富,达意准确,语法多样准确,内容也不错,结构微微瑕疵
**** 7
*Nowadays*, house owners became more excited about the past of their living places.
There are some reasons for this tendency and methods of investigation.
wusd: 复述提干+回答问题

*Firstly*, humans have a great sense of curiosity,
	and it is not a miracle
		that we would like to find out about the past of the constructions we live in.
Householders care about respect and knowledge of the history gives more satisfaction.
*Secondly*, architecture and design received the most common interests.
Forms and methods of structure and its construction
	gives pleasure and a deep understanding of the living place.
*For instance*,
	I figured out that a previous owner of my apartment was one of the richest Chinese,
		but by that time he was poor yet.
It gave me sensitivity and satisfaction in spending time there.
wusd: 没有topic sentence,内容2有点重复

How can we investigate house history?
*On one hand*,
	the best way is to have a real conversation with previous owners, talking to elders.
Facing the past itself gives more happiness.
*Moreover*, surfing the internet is another convenient method to get familiar with it.
*Although*, I think is more preferable to attend the local library,
	where I used to find real contacts and detailed information.
Everyone chooses their own way to search for it because the modern world helps enormously.
wusd: 有topic sentence,句子间的连接不够丝滑

*To conclude*, homeowners may easily research history houses,
	because there are plenty of opportunities.
A simple sense of curiosity and desire to have a fashionable lifestyle
	increase the number of people,
	who is interested in history and architecture.
It brings a positive impact on building's care
	and prevents rapid destroying by nature and the environment.
wusd: 总结分1,未总结分2
wusd: 词汇量少不丰富,结构词有点乱用,但是遵守了总分总的结构,复述回答提干也做的较好.语法和句式用的不够好,内容不够好
**** 7.5
People are indeed getting keen on exploring the hidden history of their houses in certain areas.
A variety of reasons might be relevant to the phenomenon,
	and there are several ways for them to perform the investigation.
wusd: 复述提干+回答问题

*Personally*, there are three possible explanations associated with this issue.
*Firstly*,
	people are curious about the past events in their childhood and adolescence in the household.
Even a naive painting on the wall
	will stir the golden memory of being loved and cared for
		as a little kid under their parents' wings.
*Secondly*,
	knowing the building's history can grant us
		a more realistic and thorough understanding of the apartments' advantages and disadvantages.
*In addition*, many buildings used to have signs of many historical figures or celebrities;
	hence it might be rather romantic to figure out these stories.
wusd: topic sentence+例子

To conduct an investigation, a number of sources can be useful.
Senior family members should be asked initially.
They have spent so many years in the building,
		leaving various traces of their own;
	*thus*, they are capable of sharing their life stories within the household.
*Moreover*, the building manager can provide helpful information on this problem,
	because their job requires a profound grasp of what once happened in the house.
*Finally*, online searching is always a good choice for gathering such knowledge,
	especially when your home might be a potentially important historical site
		with celebrities living in it.
wusd: topic sentence+例子

*In conclusion*, an inspection of household history may be resulted from multiple reasons,
	while certain steps can be taken to fulfil this goal.
wusd: 总结分1和分2
wusd: 词汇较丰富,不如8分的有很多好句子,结构优秀.句式语法也较为多变.内容较为出彩.

*** DONE 练：4. 罗列⼤纲+继续补⻬上次作业没写完的部分，如果上次作业写的⾜够完整，请略过本步骤。
CLOSED: [2024-08-02 Fri 10:51]
*** 改：5. 修改单词（同义词）+习惯⽤法+语法⼤结构（丰富程度）
In some states,
	there are more insteresting about researching the history of the residences.
There are several common reasons that people may have,
	and some methods to find out the history of these.

Some people undertake the task of learning about it merely for fun,
	during which they not only satisfy their curiosities,
		but also enjoy a feel of the house in the past.
This may extract some wonderful stories which have been mysteries,
	for a house usually holds a wealth of information.
It may also help to find our ancestors,
	so that we could fit with genealogical and family story research.
When you plan to renovate your house,
	the work of understanding the history of it is beneficial for you to save money.
Besides, it enlarges our understanding about the history of the area in which the house is located,
	we might learn more about the farci of a suburb, like how it developed and who lived and worked.

There are a good number of ways to dig up the history of the house.
For one thing, what you need to do is to indentify the era in which the structure was built.
With the help of an architecture book,
	you could discern a core style of the house
		by examining the style of the windows, doors and other features.
Another thing which is suitable for you is to invite experts to assess your home.
An architect or a historian studies the exterior and interior of the house,
	so that he could tell when the house was built
		by the style of it which were prevalent at a particular time.
Since the frame of a house is unlikely to have been altered
	since the time the house was built,
	you can pay attention to the construction by which you can estimate when it was built.
You can rough-date a house by stuffs in your house which help you confirm the date of your house,
		like nails, paint colors, hinge design and so on.
For example, you can date elements of ahouse by examining a cross section of a paint chip.

Accompanying the increasing number of people who are insterested in the history of their houses,
	there are more and more ways to shed light on the stories of their houses.
*** DONE 改：6. 对⽐⾃⼰写的和步骤3中的⾼分范⽂：【内容】【结构】，并修改。
CLOSED: [2024-08-02 Fri 14:26]
In some states,
	there are more insteresting about researching the history of the residences.
There are several common reasons that people may have,
	and some methods to find out the history of these.

There are many reasons why a good number of property owners find about the building's stories.
Firstly, Some people undertake the task of learning about it merely for fun,
	during which they not only satisfy their curiosities,
		but also enjoy a feel of the house in the past.
This may extract some wonderful stories which have been mysteries,
	for a house usually holds a wealth of information.
Secondly, it may also help to find our ancestors,
	so that we could fit with genealogical and family story research.
When you plan to renovate your house,
	the work of understanding the history of it is beneficial for you to save money.
In addition,
	it enlarges our understanding about the history of the area in which the house is located,
	we might learn more about the farci of a suburb, like how it developed and who lived and worked.

To dig up the history of the houses, a number of sources can be useful.
For one thing, what you need to do is to indentify the era in which the structure was built.
With the help of an architecture book,
	you could discern a core style of the house
		by examining the style of the windows, doors and other features.
Moreover, another thing which is suitable for you is to invite experts to assess your home.
An architect or a historian studies the exterior and interior of the house,
	so that he could tell when the house was built
		by the style of it which were prevalent at a particular time.
Finally, Since the frame of a house is unlikely to have been altered
	since the time the house was built,
	you can pay attention to the construction by which you can estimate when it was built.
You can rough-date a house by stuffs in your house which help you confirm the date of your house,
		like nails, paint colors, hinge design and so on.
For instance, you can date elements of ahouse by examining a cross section of a paint chip.

In conclusion,
	accompanying the increasing number of people who are insterested in the history of their houses,
	there are many ways to shed light on the stories of their houses.
*** 改：7. 星座⼩组：共同准备，互相讨论，互相提供修改建议。	 

** 作业2: G类 Task1:更简单粗暴的备考⽅案
*** 1. 审题+精读范⽂=内容+结构+表达
*** 2. 动笔写，即模考（前中后）

** 作业3 汉语写作（可全英，或半英半汉）
*** 1. 思考阅读&听⼒&写作对准备⼝语有什么帮助？
阅读&听力&写作,每一步都对准备口语非常有帮助,而且是层层递进增量的帮助.
阅读为口语提供了内容,表达和结构.阅读分为精读和泛读,精读主要目的是为了获取表达,这些表达是书面形式的,回头可以通过大量的跟读造句,用于到口语当中.而泛读则着重提供了内容,在泛读的过程中,我们学到了知识学到信息,增大了词汇量,这样我们张嘴就言之有物.

听力不但为口语提供了内容,表达和结构,还有语音.要知道口语毕竟是语言形式的,听力等于是把阅读这些文本形式转化成了语音形式.我们听多了,最后下意识的模仿,就成了自己的口语.

对比阅读和听力,写作几乎是口语的另一种形式,文本形式.
写作和口语一样,都是输出内容,表达和结构,但是口语多了一门语音.

*** 2. 思考NCE23中的练习与作业，哪些对⼝语提分有帮助？
内容:1,
结构:2,
单词:3.1,
习惯用法:3.2,
语法:3.3,
语音:4
--------------------
- 单词造句 
	3
- Pattern Drill 写+读
	1,3+4
- 给自己讲解
	3
- 红皮书
	3
- 习惯用法造句
	3
- 跟读至背诵
	1+2+3+4
- Ask me if 写+读
	1+3+4
- 摘要写作
	1+2
- tell the story 口语
	1+2+3+4
- Topics for discussion
	1+2+3
全部都有用,因为口语需要内容,结构,表达,语音,而每个环节都有所提供

*** 3. 思考如何提升英语⼝语？ 给出您的建议，请⾄少给3点。
首先从口语的what入手,再想想why,最后才是how

口语是什么? 和写作一样,广义的口语,shit既是;和口语考试,围绕一个topic展开对话.
为什么要提升口语? 1.表达自我的需求, 2.工作生活要用

如何提升英语口语?
主要两方面入手:
	1. 精读/泛读/泛听
	2. 写作
	3. 练广义的口语(用嘴造句),summary
	4. 练狭义的口语,先提纲,再扩展
