#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task14 8-1 口语1+口语2 实战演练

In some states,
	there are more interesting about researching the history of residences.
There are several common reasons that people may have,
	and some methods to find out the history of these.

There are many reasons why many property owners find out about the buildings' past events.
Firstly, Some people undertake the task of learning about it merely for fun,
	during which they not only satisfy their curiosities,
		but also enjoy a feel of the house in the past.
This may extract some wonderful stories that have been mysteries,
	since a house usually holds a wealth of information.
Secondly, it may also help to find our ancestors,
	so that we could fit with genealogical and family story research.
When you plan to renovate your house,
	the work of understanding the history of it is beneficial for you to save money.
In addition,
	it enlarges our understanding of the history of the area in which the house is located,
	we might learn more about the farce of a suburb, like how it developed and who lived and worked.

To dig up the history of the houses, a number of sources can be useful.
For one thing, what you need to do is to identify the era in which the structure was built.
With the help of an architecture book,
	you could discern the core style of the house
		by examining the style of the windows, doors, and other features.
Moreover, another thing which is suitable for you is to invite experts to assess your home.
An architect or a historian studies the exterior and interior of the house
	so that he can tell when the house was built
		by the style of it which were prevalent at a particular time.
Finally, Since the frame of a house is unlikely to have been altered
	since the time the house was built,
	you can pay attention to the construction by which you can estimate when it was built.
You can rough-date a house by stuffs in your house which help you confirm the date of your house,
		like nails, paint colors, hinge design, and so on.
For instance, you can date elements of a house by examining a cross-section of a paint chip.

In conclusion,
	accompanying the increasing number of people who are interested in the history of their houses,
	there are many ways to shed light on the stories of their houses.
