#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task11 6-2 写作1 what why how
材料：《葛传槼英⽂写作》
教学⽬标：
1. 理解写作与阅读&听⼒的关系
2. 理解写作包含哪些内容？
3. 理解如何提升写作能⼒？
家庭作业：
1. 结合之前所有课程，汉语书写【写作与阅读&听⼒】的关系
2. 泛读如下节选⾃《葛传槼英⽂写作》⼀书中的内容（pdf⽂件），并⽤1-3句话总
结（可以⽤汉语）每个篇章的核⼼内容。
	1. 练习： skimming + summary，体验输出倒逼输⼊
	2. 可以借助汉语：直接全⾯先翻译成汉语并阅读
3. 边阅读思考《葛传槼英⽂写作》⼀书中的内容，边思考我的NCE23中，哪些环节对于提升英语写作是有帮助的，以及为什么？
4. 【选修】阅读张中⾏先⽣《作⽂杂谈》⼀书中“什么是作⽂”⼀⽂。感受下来⾃⺟语的铁拳暴击。
写出您在完成这个作业过程中产⽣的疑惑，然后带着这个疑惑去听课。
问题⼀:?
问题⼆:?
问题三:?
...
解决问题优先级如下:
1. ⾃⼰尝试解决，请勿做伸⼿党。 
2. 解决不了尝试群⾥请教。 
3. 期待下次直播课程我会课上解决。 
4. 直播课程会预留答疑解惑时间，可以问。 
5. 直接私信我。 (您⽆需⾛完前4步才找我，但我强烈建议经过前四步)

** 1. 结合之前所有课程，汉语书写[写作与阅读&听力]的关系
写作=内容+结构+表达
阅读和听力积攒内容+结构+表达,其中泛读泛听更加偏向内容和结构,而精读精听偏向于表达
阅读和听力是输入,写作是输出,输入量够了,才能有输出.也可以用输出,来倒逼输入.简单来说就是阅读和听力足够多了,才有写作的素材.又因为写作的要求,去阅读和听力找素材.
** 2. 泛读如下节选自《葛传槼英文写作》一书中的内容(pdf文件)并用1-3句话总结(可以用汉语)每个篇章的核心内容。
1. 练习:skimming+summary，体验输出倒逼输入
2. 可以借助汉语:直接全面先翻译成汉语并阅读(软件)
	 
20. Something to Say.
Composition, as has been said in Section 1, is the art or practice of writing.
In other words, it is the art or practice of saying something in written words.
When nothing is to be said, no composition is possible.
You simply cannot learn composition if you always have nothing to say.
Since you are bent upon learning it, you must find something to say.
This finding is necessary to practice in composition.
When you come to think about it, it is not at all difficult to find something to say.
You may find it from a great many sources,
	the most common of which are perhaps personal experience, observation, conversation, and reading.
Of course you have occasion to speak and write the Han language every day.
Just ask yourself the question "How shall I say it in English?",
	and you will find something for practice in English composition.
You will find far more material than you have time for every day.”
Skimming + Summary：
说什么:
	组合是写作的艺术,写作也是说话的文本形式.如果没有话说,那么也没有东西可写.
	要说的东西来自于个人经验,观察,对话和阅读,你每天都要说汉语,如果问问自己怎么用英语说出来,你会发现每天有很多素材.

21. How to Say It.
Your question is not what to say but how to say it.
You may often have an idea or a thought that you do not know how to express.
For instance, you may not be able to express the idea of the glass tube	measuring temperature
	if you do not happen to know the word "thermometer".
To take another example, suppose you wish to apply for a position by letter but you cannot do so.
Now suppose you ask a friend to write the letter for you, and he writes it.
You read it and understand it all right.
You come to realize that you did not think of arranging those simple words in that simple order.
You did have something to say, but you did not know how to say it!
Hence the importance of studying composition.
Skimming + Summary：
怎么说:
	问题不在于说什么,而在于怎么说.
	你经常有想法,但是不知道怎么表达,比如:想表达测温度的透明管子,不知道温度计. --这是词汇量不够
	又或者,请人帮忙写求职信,写出来的你看得懂,但是不懂地如何组合这些简单的单词. --这是组合不行
	因此,学习组合非常重要.


22. A Consolation.
I take it for granted that when you ask yourself the question
	"How shall I say it in English?", you often find that you cannot.
Well, let me give you a word of consolation.
Even experienced writers may sometimes find that they cannot say something that they wish to say.
As you are merely a young Chinese student of English,
	what cause have you to feel disappointed?
Skimming + Summary：
一点安慰:
	即便是有native experienced writter有时候也表达不出自己的想法,你就一个中国英语学生,不要沮丧.
	

23. Others May Have Said It before You.
As a matter of fact, many of the ideas and thoughts you often have occasion to express
	have already been expressed by others before you.
Read any page in any book carefully,
	and you will perhaps find some expressions that will help you to say things.
Many of such expressions may seem to you to be too simple to deserve much attention,
	but you cannot invent them, nor can you use them unless you have noted them.
There appear to be many Chinese students
	who have read a number of books on grammar and composition and done many exercises
		in correcting and improving sentences and yet cannot write even tolerable English.
The trouble is that they may either have not read widely enough or have not read carefully enough.”
Skimming + Summary：
其他人可能在你之前说过了:
	很多想法早就被别人表达过了,你看任何文本都可能发现一些表达能帮助说东西.
	一些表达看似很简单,但是你自己造不出来,如果没标记出来又用不出来.
	很多中国学生看了一些语法和组合书但是不能说出还行的英语,就是因为读的量不够大或者不够仔细. --精读量不够大
	

24. What to Read.
Since it is for the purpose of learning composition that you read,
	and since it is in present-day English prose that you ought to learn to express yourself,
	what you read must be present-day English prose.
Expressions in common use a hundred years ago may not be so at the present day.
Likewise, expressions in common use in verse may not be so in prose.
The term "present-day English prose", however, requires qualification here.
Since it is in standard English that you ought to learn to express yourself,
	what you read must not contain too much slang,
		whatever significance one may attach to the word.
Again, since it is things in everyday life that you ought to learn to write about,
	what you read must not be of a technical character.
One limitation more.
What you read must be fairly easy for you;
	too much time and energy spent in reading between the lines
			and finding out all kinds of references and allusions
		would very likely distract your mind from your purpose,
			which is to	learn English composition.
Skimming + Summary：
读什么:
	因为目的是用英文当代散文来表达自己,所以要看当代的英语散文,别看过时的,也别看诗歌的.
	这些英文当代散文也需要些质量,不要有太多口号的,不要有太多技术特征的.
	最后,要阅读不是相对容易的,不需要在字外揣摩含义和太多引用还有暗喻,这些都不利于学组合.

25. How to Read.
As you may have gathered from the above,
	in reading to learn English composition,
	you ought to regard the language as the main thing.
To quote from my A Word to the Wise:
	"When you read a story in English, do you read it for the story or for the English?
	This is a question that is not so foolish as it may seem.
	For I find that many students of English pay far more attention to the story
		than to the English.
They read and enjoy and for a long time afterwards remember the story,
	but do not care to study the use of words and phrases in it.
For instance, they cherish the memory of how the mystery of the eternal triangle is solved,
	but do not remember a single sentence in the story
		and cannot tell what preposition is used before or after a certain word
			in the speech of a certain character.”
Of course, it is all right to read and enjoy and remember a story,
	and so long as one wants to know the story only,
		one need not bother about the language.
But the case is quite different with a student of English.
I mean a student of English as distinguished from a student of stories
	or what is called the general reader”.
As you may also have gathered from the above, you ought to read very carefully.
Not only very carefully but also aloud,
	and that again and again till you know the passage by heart.
Skimming + Summary：
怎么读:
	读英文故事的时候,你是为了故事读的还是为了英语读的.
	有些人读且享受很长一段时间都记得故事,但是记不住简单的话里单词前面的介词,你是英语生.
	你得非常仔细且大声地读,一遍又一遍直到你把文章熟记于心.
	

27. Self-cultivation.
Though it is not on the assumption
	that you are a self-taught student
	that I am writing this book,
	yet I have to point out
		that when it comes to reading with a view to learning composition,
			you ought to treat the matter as a form of self-cultivation.
The five selections in the above exercise are by no means all
	that you ought to read in the way indicated.
Nor should you confine yourself to what American teachers call "assignments".
Nor should you regard the reading as something to be done in a composition class.
Fortunately there is no lack of material
	in these days of easy access to various kinds of publications.
Your teacher is of course expected
	to be both able and willing to advise you in the choice of material.
Skimming + Summary：
自我修养:
	把阅读当作自我的修养,不要把自己限制在布置的作业或者是组合的课堂.
	现如今,没有材料限制.你的老师应该能够并且愿意给你选择一些材料. ---Leo的附加值
	

28. Writing from Memory.
A very helpful exercise in composition is to write a passage from memory
	and correct your work in strict accordance with the passage.
This is tantamount to getting the author of that passage to correct your work.
Incidentally, you will do well to try this exercise in reading any passage
	just before you feel you can recite it correctly.
Skimming + Summary：
从记忆中写作:
	学组合非常有用的练习,从记忆下写作然后根据文章严格地改.
	仅仅当你能背诵时,才能尝试这个练习.


29. Imitation, Conscious and Unconscious. （赶紧想想我们的NCE23+泛读）
The careful reading of suitable present-day English prose will help you
	in learning composition through imitation, which is either conscious or unconscious.
Things unconscious cannot be taught, of course.
Conscious imitation, however, is well worth discussing as an aid to composition.
Take the first sentence in the first selection in Exercise 1:
	"The Outline of History proved an extremely successful book",
	where the verb "proved" is a copulative one having "book" as its complement.
Now you may write as many sentences as you can in imitation of this single sentence; thus:
	1. The old man proved the father of the young man.
	2. The story proved true.
	3. The experiment proved a success.
	4. This book will prove very helpful to you.
	…
Skimming + Summary：
模仿,有意和无意:
	通过有意或无意地模仿当代英文散文会帮助你写作.
	无意就不提了,有意的比如说模仿造句.  ---泛读,无意+NCE23,造句

	
31. Expressing Another Person's Thoughts.
Expressing another person's thoughts is a valuable training in English composition
	both because you may sometimes have occasion to do so
	and because it will help you to express your own.
The thoughts are there for you to express: there is something to say.
Besides, there are often some words and phrases for you to use.
Skimming + Summary：
表达他人的想法:
	表达他人的想法也是组合的有价值的练习,一是有东西去说,二是这些单词和短语你也可以用. --他山之石

32. Paraphrasing Sentences.
Paraphrasing is a simple form of expressing another person’s thoughts.
It means giving the meaning of a passage in other words,
	that is, giving it a simpler and clearer expression.
It may be called close reproduction or close retelling.
But it is not mere substitution of words, nor mere sentence transformation.
Skimming + Summary：
改述句子:
	改述是表达他人想法更简单的形式,用其他的单词把句子变得更清楚更简单.
	不仅仅是换换单词,转变下句子.
	
33. Suggestions for Paraphrasing.
In order to paraphrase well, it is necessary to follow a few simple suggestions:
	1. Study the passage carefully to get a thorough grasp of its meaning.
		 You can never paraphrase anything that you do not fully understand.
	2. Try to express the meaning in the simplest and clearest manner you can.
		 You may use any word or phrase in the original that you find simple and clear enough;
			do not avoid any word or phrase merely because it is in the original.
		 Similarly, while it is anything but necessary to follow the construction of the original,
		  it is not advisable to change merely for the sake of a change.
		 It is often better to paraphrase a sentence in two or more sentences.
	3. Get rid of all figurative language.
	4. Paraphrase a passage in as many ways as you can
			till you come to what you consider the best way.
		 Though you may not be able to write such good English as the original,
			yet you ought to aim at doing so
			— remembering, however, that you must express the meaning in a simpler and clearer manner.
Skimming + Summary：
改述的建议:
	1. 要想复述,先得完全懂了
	2. 尽力去用最简单和清楚的方式去复述
		 不要为了改变而改变,所以不要避讳原文有的单词,有的结构顺序.
		 通常一句话改述成二句或更多合适.
	3. 避免比喻的语言,尽量平实
	4. 尽管不能和原文一样好,但要尽力做.用你能的多种方式改述,直到你认为找到最好的.
		 牢记,要清楚简单地表达意思.

--------------------
36. Condensing.
Condensing is another form of expressing another person's thoughts.
It means giving the meaning of a passage, a story, an essay, a poem, or even a whole book,
	in one or more sentences.
It may be called summarizing, abstract-writing, or précis-writing.
Skimming + Summary：
压缩:
	压缩就是总结~摘要~梗概写作,用一两句话表达段落~文章~故事甚至一整本书的意思.
	

38. Suggestions for Condensing.
Below are some simple suggestions for condensing:
	1. Study the original carefully to get a thorough grasp or its meaning.
	2. Pick out the main points, and leave out all unnecessary points.
	3. If possible, arrange the points in the condensation in the same order as in the original.
	4. Unless the original is a short passage,
	  you had better write the main points down instead of merely picking them out mentally,
	  and arrange them in something like an outline.
	 This note-taking and outline-making will prepare you for original composition.
	 They will be treated further on in this chapter.
Skimming + Summary：
压缩的建议:
	1. 仔细学完全抓住其意思
	2. 挑出主要内容,放弃所有不必要的细节.
	3. 可以的话,把这些点安排成原来的顺序
	4. 除非太短了,最好写出主要点而不是在脑子里面挑选出,把其搞成outline
	 
--------------------
43. Choosing a Subject.
Composition is saying something about something.
This latter something is the subject. …
Skimming + Summary：
选个主题:
	组合是说某些事物关于某些事物--主题.

44. Taking Notes.
When you have chosen a subject, think about it hard.
Ideas will come into your mind.
Take a note of each as it comes.
The ideas are likely to come in a confusing manner:
	some may overlap, some may be unimportant, some may he irrelevant,
	some may be indefinite.
Never mind.
Note them all down.
Catch them before they may escape.
Do not stop until no more ideas come.
Suppose your subject is your family (whatever your title may be).
Such ideas as the following may come into your mind:
	1. My father.
	2. My mother.
	3. My brothers.
	4. My sisters.
	5. My grandfather, dead since 1939.
	6. My grandmother, an invalid, dead since 1937.
	7. My uncle, a widower since 1967.
	8. My aunt, an old maid.
	9. A distant relation, having been living with us for nearly twenty years.
	10. A cat and a dog.
	11. Recent removal into a new house.
	12. A small garden.
	13. Pleasant surroundings.
	14. Mutual love among all members of my family.
	15. Occasional tiffs between my younger brother and younger sister.
	16. Not rich, but nothing to worry about.
	17. My father's hobby.
Skimming + Summary：
做记录:
	选了个主题后,开始使劲想.
	可能想法会重叠,不重要,不相关,模糊不清.别管,想到什么记录什么,直到没想法了. --搜?
	eg. 你的家庭...
	
--------------------
45. Making an Outline.
When you have taken enough notes about your subject,
	consider each to see whether it is closely connected with your subject.
The answer to this question depends partly upon how long your composition is to be. …
Skimming + Summary：
列大纲:
	做了足够多的记录,考虑是否和主题密切相关.问题取决于你要些多长的文章.

47. Making Outlines of What You Read.
Making outlines of what you read is a valuable training in making outlines;
	for it shows you how experienced writers arrange their ideas.
Skimming + Summary：
为你读的列大纲:
	为你读的列大纲是很好的练习,因为它会告诉你有经验的作家是怎么布置自己的想法.

48. Expanding an Outline.
When you have finished your outline, expand it into a composition, that is, do the actual writing.
You may be able to do it at a sitting, or you may have to stop from time to time.
In either case, you will do well to follow the following suggestions:
1. Do something more than merely expanding each point in your outline into a complete sentence.
	 Additional ideas are often necessary.
2. Do not follow your outline slavishly
		if you find it desirable or necessary
			to make any omission or addition or alteration or adaptation.
3. As a rule expand each main point in your outline into a paragraph.
4. Consult one or more dictionaries as often as you need.
5. Do not drag in any word or idiom just to show off your knowledge of it. (注意思考)
6. Revise your work very carefully.
	 Do not be content with anything short of your best.
Skimming + Summary：
扩展大纲:
	扩展大纲才是真正的写作,可能一口气完成,也可以不得不一次次停下来.下面是建议
	1. 不要仅仅只把一个点变成一句话,附加的想法通常很必要.
	2. 不要盲从你的outline,如果必要时,删~增~换~改.
	3. 作为一项规则,把每个outline主要点当作一段.
	4. 尽你所需地查字典. --搜商?
	5. 不要插入任何单词去显摆你懂. --我觉得一是作文是为了表达意思,插入其他单词会跑题,二是在雅思考官面前,没有拽的资格
	6. 小心修改你的作品,不要对不是最好的满足.


--------------------
224. What is a Paragraph? (认真思考，下⽂答案并不明晰，但是答案本身对提升写作分数帮助巨⼤)
A paragraph may be defined as a distinct part or section of any piece of writing,
	whether of one or more sentences, that deals with a particular point of the subject.
It is to a sentence what a sentence is to a word.
The term is also applied to a short composition
	consisting of a group of sentences dealing with a single topic and closely related to each other,
	such as a leaderette（这个单词不会，影响您理解整段⽂字梗概么？）in a newspaper.
Skimming + Summary：
--不影响,猜是段落,块的意思.
什么是段落?:
	一个段落被定义成写作的一块或者一节,不管一句或多句,解决主题的一个特殊点.
	段相对于句子,相当于句子对于单词.
	关键是一组相互关联的句子处理一个单一的话题,就像报纸的一则短评.
	

--------------------
226. Paragraphs and Outline.
The third suggestion given in Section 48 on expanding an outline into a composition is:
	"As a rule expand each main point in your outline into a paragraph".
When you have made an outline carefully,
	therefore, you ought to have little difficulty in paragraphing.
Skimming + Summary：
段落和大纲:
	当你仔细列了个大纲,你没有困难分段.因为每个大纲里的重要点,作为一段.
	

227. Topic Sentence. （可以回想polar bear 或者 ⻄⽅⽂明简史第三章的某些内容思考）
The main point to which a paragraph confines itself is called the topic,
	and when the topic is definitely stated in one of the sentences in the paragraph,
	that sentence is called the topic sentence.
It must not be supposed, however, that every paragraph must have a topic sentence.
While in a paragraph of exposition or argument
		the topic is as a rule definitely stated in a sentence,
	it is, in a paragraph of narration or description, usually implied father than stated.
The topic sentence occurs usually at the beginning of the paragraph,
	but sometimes at the end and sometimes in the middle.
Occasionally the topic is stated at or near the beginning and repeated,
	in different words, at or near the end.
Skimming + Summary：
-- 段首尾有可能是主题句!主题句是由于写作的方法来的,根据大纲写作.
主题句:
	段落限制到的主要点叫做主题,句中直接声明主题的是主题句.
	不是所有的段落都有,说明文和论证的段落通常有,而记叙文或描述的段落通常是暗示.
	经常是在段首尾附近,有时候在中间.
	

229. Qualities of a Good Paragraph.
A paragraph should possess unity, coherence, and emphasis.
Unity, which is the fundamental quality, can be secured by sticking to the topic.
This is not difficult when you have a carefully made outline to follow.
Coherence can be secured by the use of connecting words
	and phrases and the avoidance of successive short sentences.
Emphasis can be secured by writing the topic sentence at the beginning or at the end,
	by giving more space to the central idea, and …
Skimming + Summary：
好段落的品质:
	整体性~连贯性~强调.
	整体性: 可以被坚持主题所保证
	连贯性: 可以被联结词和避免连续的短句所保证
	强调: 可以被短首尾主题句,给更多中心主题更多空见...


230. Transition between Paragraphs.
The transition between paragraphs should, needless to say, be as easy and smooth as possible,
	so that the reader will feel no break of thought but merely a natural step forward.
This result can usually be accomplished by the use of connecting words and phrases
	at the beginning of paragraphs.
Skimming + Summary：
段落的过渡:
	过渡要简单和平滑,就是让读者思路不断,仅仅是一小步的前进.
	这样靠在段首的连接词.


** 3. 边阅读思考《葛传槼英文写作》一书中的内容，边思考我的NCE23中，哪些环节对于提升英语写作是有帮助的，以及为什么?

** 4. [选修]阅读张中行先生《作文杂谈》一书中'什么是作文'一文。感受下来自母语的铁拳暴击.
