* 如何改变自己性格懦弱,遇事畏畏缩缩的样子?
很多事情啊,就跟跳绳一样,有无数的细节.
靠你的大脑没有办法想清楚这无数的细节,也没有必要想清楚,重复练就好了,身体和本能会给你摸索出一条道路.
大脑会把控整体的方向,身体感受细节,诀窍就是重复无数次.

无数次地把自己暴露在社交当中,在社交中的分分秒秒尽自己的能力去表现.
经过无数次地暴露~无数次吃亏~无数次尴尬~无数次羞耻...
你的身体会自动学习的.
直到有一天,身边的人尊敬地看着你,自然地叫你一声大哥.
那时候,你已经蜕变了.

* 被女朋友打了应该还手吗?
不要问"女朋友"和"大众"怎么想,问问你自己想要什么?

作为一个成年人,问这种问题应该羞愧.总是在征求"权威"的意见,试图寻找"父母"的帮助.
你想怎样,就怎样,接受后果就行.
至于,你想要什么,付出什么,问自己就行不用问别人.

* 霸凌我的人人缘很好，我该从自己身上找原因吗？
大多数人喜欢又能吓唬他们,又能给他们好处的人.
所以,一个群体人缘好的人不是本身多优秀~做事对,而是胡萝卜和大棒用的好.

你会被人缘好的人霸凌,就是因为你大棒用的不如人家,能力问题而已,上升不到是非对错.

* 实验室博士师姐让我和她形式上领证，我大二要不要帮她?
即便是路面的疯子看到一个怒目而视的壮汉,也会不再发疯变成正常人.

作为男孩,希望别人在跟你说话前好好掂量掂量,平易近人会让对方感激,而不是理所应当.

* 为什么别人一眼就知道你是老实人?
决定你是不是老实人的关键,就在于你心里有没有谱,你的谱容不容易受别人的压力干扰.
如果你时刻心里有谱,知道自己的目的是什么,对自己非常相信,相信自己做的是对的.
那么即便是戴1000度的眼镜,沉默少言,他们也会说:"小吴看上去傻傻的,实际上猴精着呢."

所以,控制自己是美德,知道自己要什么,相信自己做的对,能做的到.就不随意被别人影响到自己,摘掉老实人的帽子.

有以下特点的人容易被欺负。

拥有特点条数越多，容易被欺负指数直线上升。9条全占的，我为你祈祷。

* 什么样的人会被欺负？

1. 害怕冲突
	明明有自己的意志，却不敢把自己的意志凌驾于别人的意志。当彼此意志冲突时习惯于退让。俗称讨好型人格。
2. 不自信
	自信的人，即使和很多人吵架，也不会觉得自己很差。自卑的人，如果人际关系变差，就会觉得是自己哪里做错了。这是形成第一点的一个原因。因为他们的自信是建立在维持人际关系上的,所以害怕人际关系的变差，不敢与人交恶。
	真正的自信，来源于对于自己无条件的认可。
3. 完美主义造成的过度思考
	这是很多聪明人的毛病。他们脑子很聪明，所以能把一件事的所有后果都考虑个遍。他们一点风险都不想背负。
	比如打架的后果：打轻了对方不怕，反而会助长对方威风；打重了，警察来了，拘留我咋办；骂脏话，有第三人听见，影响我绅士人设；这小子嘴碎，嚼我舌头；我刚到一个集体，第一印象很重要，先别打架；我这新买的一万元鞋子，踩脏了不值。
	而一般人：cnmd,打了再说！
	所以，有些人看起来很怂，有可能是他想得特别多。你多惹他几次，你就知道其实他不怂。
4. 理想主义者的错误认知
	他们相信，这世界应该充满爱，人人平等。他们不清楚，这世界的本质，就是强者或直接或间接地欺负弱者。
	所以他们特别追求和谐，以致于到了看起来娘的地步。因为他们过于尊重他人。
5. 早年创伤，变成一副怕怕脸
	小时候一直被欺负，所以长大后，心里还有创伤。这种人，无论现在强大还是弱小，总对别人抱有警惕感，害怕受人欺负。
	其实，你越警惕，坏蛋就越觉得你看起来怕怕的，你就越容易受欺负。
	这属于内心世界的感召。
6. 外貌性格有重大缺陷或不同之处
	身材极矮小，面貌极丑陋，举止娘娘腔，性取向小众的，都会成为一些贱货的猎物。
7. 太优秀了却无实力保护自己
	俊秀的寡妇、瘦弱的才子、刚正不阿的没有背景的年轻人....
	这些人太容易遭人妒忌，却太弱小，无法保护自己。
8. 没本事却不合群
	你小子牛比个啥呀，没见你有啥厉害的，还摆出一副清高样子？
	这在集体主义的我国，比较常见。
9. 缺乏社会经验、看不懂套路
	社会老油条在初见一个人时，喜欢先“探探深浅、盘盘道”，看看你的背景、家境、性格、目的、跟哪个大佬, 以方便进一步确定和你的相处方式。
	他会在小的事情上先试探你，比如开你一个不严重的玩笑、和你说话带几句脏字、不把自己当外人指使你做这做那....他这样做的目的，就是尝试着把自己放在高于你的位置，探探你的反应。
	你若巧妙地向他表示"傻比，别装了，再装老子就要抽你这雕丝了,". 他立即就会知趣地回到最一开始的社交地位上与你相处。
	但当你接受了他的试探，没有任何反应，他就判定，你没什么背景，或者就是个软柿子。
	那你等着瞧，一旦他把你当成low比，让你更生气的事就会接踵而至。
