* 目的
去交更多的朋友,使自己成为一个有影响力的人

* 已知
- 交朋友交心
- 真诚地关心他人
- 朋友危难时要及时伸出援手
- 做人不要太敏感了
- 要会说话,不要得罪人
- 要多聊别人,少聊自己

* 作者序 要成功,更要成长
人性1: 做错事的人会责备任何人,但绝不会责备自己
	不要批评~指责~抱怨任何人
人性2: 渴望别人觉得自己很重要
	不吝啬发自内心的~真诚的赞美
人性3: 人永远只关心自己吃什么
	"我怎么能让他自己想做这件事呢?"
		站在他的视角想问题,仿佛就是你自己的视角
	谈他想要得到的,并告诉他方法!
人性4: 让别人喜欢自己是徒劳,人们不在意你,也不在意我,只在意他们自己,而且不论早中晚!
	不关心别人的人会活得很哭,也害苦别人,人类的失败都来自于这些人.
	真的关心别人
人性5: 微笑能传递出我喜欢你
人性6: 记住别人的名字很重要,名字对一个人来说是最悦耳的声音
人性7: 聊天时,人们觉得自己的需要~问题才有趣,比你的有趣一百倍
	我的牙痛比非洲一百万人饥荒更重要,一颗小水痘抵得过非洲的40场大地震
	多让对方吹牛逼
* 一 基本技巧

** 01 待人接物的第一大忌
最凶恶的罪犯都认为自己毫无过错.你对他人的批评只能招来反击,让自己处于危险的位置,不能解决任何问题.

****** 原则一 不要批评~指责或抱怨任何人
平常大家都能保持,关键是情绪上头的时候.注意要对事而不对人.

** 02 这种说话方式非常值钱
1. 健康
2. 吃喝
3. 睡觉
4. 钱财
5. 来生
6. 性
7. 崽女幸福
8. 自我价值 难以满足
	 
给予赞美时要真诚.
****** 原则二 请不要吝啬发自内心的~不做作的赞美
1. 不要老想着自己多牛逼,看看别人的长处,这样夸赞和欣赏也就来力
2. 夸人要能说出理由出来

** 03 让整个世界前来为你助力
"首先要诉诸对方的内在需要.若能做到这一点,整个世界都会向你招手,否则整个世界都将离你而去."
****** 原则三 诉诸对方的内在需要
如果他人有求于你,又开过这个口了,那么就算是难也要去帮助朋友.
	1. 不要批评~指责或者抱怨任何人
	2. 不要舍不得发自内心真诚的赞美
	3. 注意发现对方的真正需求

* 二 如何让大家都喜欢你

** 04 这样做,谁会不喜欢你?
	狗狗不需要任何东西就能活着,因为它真的喜欢你,而没有任何别的企图.
	如果你真的喜欢别人,那么两个月内交到的朋友,要比努力让别人喜欢你在两年里交到的更多.
	很多人一辈子的最大的错误,就是只是想要别人喜欢自己.
		人们不在意你,也不在意我,人们在意他们自己,早上在意,中午在意,晚饭后也在意.

****** 原则一 真的喜欢别人
如果你想让别人喜欢你,如果你想获得真正的朋友,如果你想助人助己,

** 05 这能留下美好的第一印象
微笑传递的信息是: "我喜欢你,你让我高兴,看到你我真的很开心."
如果你微笑着打电话,你的微笑也会透过声音传递过去.

****** 原则二 你,一笑值千金

** 06 这会让人一下子喜欢上你

****** 原则三 记住对方的名字,因为名字对一个人来说时世界上最悦耳和最重要的声音

** 07 怎样才叫"会聊天"
他注视着你,仿佛不是用耳朵听,而是用眼睛.

****** 原则四 倾听, 鼓励对方多聊自己

** 08 提高你的影响力

****** 原则五 聊对方感兴趣的话题

** 09 一句话暖人心

****** 原则六 使对方感到自己是重要的,要真心实意

* 三 如何有逻辑地说服他人

* 四 成为一个领袖: 如何改变他人而不冒犯人或引起反感`愤怒或怨恨
