** 人类（或其他物种）社会，权力（权威）的来源是什么？
权力是制造差异的能力。

结构洞是很好的来源。

【第四次回答】

为什么要服从他？因为他能带来利益、保护利益、损害利益或者他就是价值。为什么要相信他能这样做？因为相信他他有能力+有意愿。

因此要构建一种叙事，在这种叙事中，【权力者有意愿有能力去带来、保护、损害利益，或者服从于他就是利益】。

同时，要用实际的物资来支援这种叙事（财富、暴力、信息工具）。

【能力：1.获取神或天命或历史规律等的巨大神秘力量的支持的能力（神秘领袖，他能召唤这种力量）；2.满足欲望的思想指导能力（思想领袖，听从他的就能达成目的）；3.打倒敌人的军事才能（军事领袖，服从他的指挥就能打败敌人）；4.带来优质管理的代理能力（代理领袖，交给他去做他就能做好且多方都能够接受）；5.带来伤害的恐怖统治能力；6.由于其社会地位（社会公认度，也就是社会对他的信任或者定位）、人际关系等带来利益的能力。

3是2的特殊情况。

特务，这群人杀人却说为了人们的生存，制造恐怖却说给人们带来安全，阻碍社会的进步却说了维持秩序和人们的幸福。声称他们杀害的人都是敌人。其本质是为了维持他与其他人的巨大权力优势和自己的资产还有将服从和忠诚视为价值（思想领袖）。

将追求的价值与统治者相挂钩。

无论哪种，信任即支配。】

【第三次回答】

微观上讲，权力即服从，来源于服从者心目中对被服从者中的定位。

被服从者的定位有四种：利益保护者、利益带来者、利益损害者、观念上认为应当服从的被服从者（认为这种服从是天经地义无可改变的）。

这四种在现实中往往是混合使用的。其中利益损害者总是尽量向其他三者靠拢，因为会积累怨恨成本，并在爆发时一并支付，同时还会对系统的持久性造成破坏。

被服从者也可以是虚构的，比如神什么的。这些虚构的被服从者更不容易有弱点。而有野心者只需要作为虚构的被服从者的代理人就行了。

要形成这四种定位，需要让服从者相信被服从者具有授权（包括天命或神授）、指导、能力、资源或工具的掌控、制度（一群人达成的认可）等，当然被服从者事实上具不具有这些并不是非常重要。

具体来讲，就是被服从者者通过对带来某种利益的许诺，换取了服从者的支持和服从。而这种许诺所能带来的交易成本=许诺的利益的重要程度X被许诺人认为通过此人实现该价值的可能性。交易成本越大，便越能获取服从者的支持和服从。

这也解释了手握武器的人有时不会取代没有直接掌握武器的被服从者，因为前者没有信心能够取代后者，让足够的被许诺人相信其能够带来此利益。

其一般过程是先用利益保护者、带来者的身份形成追随自己的核心利益集团，再武装和控制核心集团成为更多人的利益损害者。【利益保护者、利益带来者的最高等级是无条件信任，即“他一定是为我好，他没有理由骗你”，忽略了对方的意愿和能力，这就是神秘的作用。当然利益损害者的最高等级也是无条件信任，他什么都知道，他捏死我就像捏死一只蚂蚁。两者都是“造神”。】

【很多人，用一个简单易懂易于接受的逻辑和让他满意的结论就可以了，至于逻辑是否经得起推敲，并不重要。利益保护者和利益带来者让他获得想要的东西，而利益损害者的服从即不损害的承诺，让他获得安全感。或者为了集体的利益，必须牺牲个人的利益，领导者等于集体的利益。】

【当然，让你每天忙于生计，没那么闲也是一种方法。】

最后改造思想，让大多数人都认为服从本身是一种价值或者无可改变的规则。【这种东西无色无味】，根本察觉不到。我们通常是通过教育培训、媒体、和与身边人的社会交流来塑造三观（这里定义与通常语境不同。价值观，什么东西最重要，应当怎么样；世界观，认为世界哪些东西是存在的；方法观，世界的规则或者说联系、因果相关关系）。意即编一个谎言，让服从者老实，再拿武器去对付那些不老实的并威慑那些老实的（枪打出头鸟定律，原理是成本一人承担利益却一群人均摊）。同时必须小心翼翼地维护这个谎言。

另外，人们还会形成制度。稳定的制度是多方博弈的结果，一是让大家有安全感，二是省去博弈成本。其一定要形成既得利益集团来维护支持才能使其稳定。形成过程是一开始这种制度可满足既得利益集团的某种利益，后来干脆就让其成为一部分人的价值。

除此之外，被服从者之间、服从者之间都会存在竞争。

宏观上讲，对于系统的整体尤其是国家而言，权力是要素连接。一个系统有三个关键点：要素、要素连接和目的。国家的目的是生产财富和掌握暴力，其要素包括管理者、暴力工具使用者和生产者等，而将其连接的正是权力。注意隔断生产者与暴力工具持有者的联系，让其只与管理者有信息交流；还有造成而各个集团间的对立。

宏观理论会忽略掉微观理论的一部分因素，因为其在宏观上影响小。

暴力、财富、信息。

通常，掌握垄断暴力工具来支撑掌握垄断财富工具（生产工具和分配工具）和信息工具，实现肉体消灭和获得认可两大目的（获得部分人的认可，消灭压制不认可、不可控的人，注意认可包括屈服于暴力的人）。

财富分为生产和分配（交易是一种再分配方式）。

影响力力公式：被需要程度=带来利害的多少×操纵的利害的能力（对利益的控制度和可能性）÷被统治者可选择范围（其他竞争者）。不使用暴力（不损害）可以折算为带来利益，作为其与对象交易的筹码。

【第二次回答】

权力来源于威逼利诱和信息管控两种方式。

一、威逼利诱

每个人心目中都有许多重要的东西，这些东西按重要程度的排序叫做价值观或者说利益。每个人的利益不尽相同。

对一个人直接的控制就是威逼利诱，使其相信你能破坏他想要的，能帮他带来想要的。

为了实现对人的威逼利诱，还可以做两个前置的行动，一是改变价值观，二是塑造形象。

改造价值观，是指通过一系列手段（具体方式之后补充）改变其价值观或利益。

塑造形象，是指让其相信自己有威逼利诱其的能力，至于自己实际上有无此能力是另一回事。

二、信息管控

人是通过外界信息来行动的，控制了他人的信息摄取，使其相信，也就控制了其判断和行动。



【第一次回答】

首先感谢28berserk的答案，把我原来一直觉得缺少什么的地方补全了（就是人的意识形态可以通过外界来塑造）。

个人认为，权力来源于秩序，秩序来源于认可。

所谓秩序，其实就是一种被固化的利益结构。利益是人类用来满足自身欲望的一系列物质、精神的产品。人为了满足欲望追逐利益而采取行动做出选择。只要有人与人接触的地方，便会有人与人之间的利益交换和争夺，就会形成利益结构。这种利益结构下做出的选择，对个体而言，就是在这个时刻他所认为的可选择的选项中的最优解。

而权力，事实上就是在某个特定利益结构下，某个主体对其他主体的影响力。所以，权力大多数情况下是相互的，只有少数情况才是一边倒的绝对。

皇帝也好，董事长也好，某个黑涩会大佬也好，他们的权力，来源于他们在秩序中的位置，是秩序赋予的。而这种秩序，可以是国家，可以是公司（当然，公司是依靠更上层的秩序，国家或者说法律而组建），也可以是黑涩会等。

可秩序又是怎么来的？前面说过，是来源于人们对这种利益结构的认可。当然，这种认可不尽相同。一旦有势力不认可这种利益结构，就会反抗这种利益结构，就会和认同这种利益结构的势力起冲突。注意，并不一定是人多力量就大（后面的就不说了，大家都明白）。选择秩序的认可者，让他们掌握枪去消灭秩序的反抗者。

怎么样来构建秩序？

那就是取得人们对这种秩序的认可，方式有很多种，比如改变对方的利益（意识形态或者说价值观），暴力（大多数人都认可，本质是损害利益），物质利益的给予或分配，心理依赖，能预测对方的心理等。总结起来就是三句话：古今中外权术的要点，无外乎——1.承诺给人想要的利益并使他相信。2.威胁损害人不想受损的利益，并使他害怕。3.该兑现的时候要兑现。什么是该兑现的时候？承诺或者威胁的效果会受损的时候。频繁的兑现，也会使得效力大打折扣。

权力是最强大的。因为最大的本事，是制服人的本事。

而在利益结构中取得权力的人，则多会利用自己的权力来巩固这种利益结构。

怎么样来维持这种秩序？

古往今来多少王朝的崩溃，实际上是秩序的崩溃，是因为不认同秩序的势力的力量大于了认同秩序的势力的力量。所以，如果皇帝仅仅是想维护统治的话，喂饱能支持权力的那一帮人，使得他们的势力大于反抗者的势力就行了。

如果能让各个势力互相斗起来，并且都需要借助自己的力量才能存活，那就更好了，因为权力的本质就是依赖性，就是必不可少。
** 整你的人，会告诉为什么整你么？
侵犯收益（意愿）：掠夺、被侵犯者支付怨恨成本等。

侵犯成本（能力）：侵犯行动的成本、被被侵犯者反击的成本。

帮助收益、帮助成本同上。

整人，一般是出于三个目的：一种是利益斗争，一种是私人恩怨，一种是要你服从。第一种不用多说，两个人争一个位置，两个派系斗来斗去，很少有不掐架的。第二种要么是由于你之前得罪他了（一件事一句话），要么是嫉妒你。第三种是你冒犯了领导，或者某件事情让领导觉得你不服从他，内心反对他，于是敲打你，穿小鞋。

当然，还有些人就是觉得你好欺负，就是想欺负你。这种反而是最好对付的。
1: 那对于各种怎么应对？
2: 天知道，你先要看你惹不惹得起。最后一种，要么就在他整你前做好预防，甚至抓到他的痛处，让他知道你的厉害；要么就在惹得起的情况下, 第一次就把他弄痛，弄得他知道你不好惹。。
1: 不好惹，怎么办？
2: 惹不起和不好惹是两回事。惹不起，忍着。
1: 怎么让他觉得我不好惹，又让他不老是逮着我不放。
2: 要让他觉得你不好惹，就是在关键时刻收拾他。人总是有弱点的。但你要防着他之后报复你。


