* 读博获得的最大的收获是什么?

** wusd
1. 目的意识
	做任何事情前,首先问自己一个问题,我的目的是什么?
	并且后面要经常问自己,我现在在做的事情,和我的目的的关系是什么,有没有偏离我的目的?
	
	在做事情的时候会遇到各种各样的困难,我能不能依旧静下心来高效工作?
	答案是:心中装着优先级,知道什么是最重要的,就行.
	
	同理,你这一生要追求什么?
	不信任的人,就让它去.不重要的事,就让它去.
	你的人生,就是你的project,这是最重要的.
2. 独立意识
	 对于任何问题,首先要自己建立一个思路,再从别人和实践中借鉴和总结,改正或优化这个思路.
	 但是首先,自己要有一个思路.这是解决问题的起点,一切靠自己.
3. 主动意识
	 别人有很多自己的事情,只有你自己最了解自己.所以他很有可能给出误导性的判断,浪费了我们的时间.
	 你是你工作的主人,同时也是你生活的主任.你要为自己的事情负责.
	 做事情都是自我驱动的,没人拿鞭子赶着你.没有人告诉你该做什么,该如何做,该多快做,做到什么地步,要回答什么问题...
	 全靠你自己的主动性,把工作向前推进.
4. 实事求是
	我不这么认为。实事求是的人最有魅力。实事求是的意思是，你能吃几碗饭，就该有吃几碗饭的口气，不要多，也不要少。
	能吃几碗饭是你的绝对硬实力。

	你不能维护你的实力本来可以主张的东西，是愚蠢或者懦弱。愚蠢是指，你对后果的不确定性没有能力预测，或者没有勤奋去预测；然后你被不确定性吓跑了，不去伸张你本可以占有的权利。懦弱是指，你预测了不确定性，但没有胆魄去做。
	
	如果你的主张和脾气比你的实力要大，会遭到有能力的人的厌恶。因为你可能会损害他的利益。当他选择和你硬碰硬时，你就露馅了。当然，你可以“赌博”，就看运气好不好了。
	
	恰如其分地让脾气和实力相符，把自己手里的牌，打出最大的价值，是最有魅力的。 
5. 智力	
	 智力.这个智力不仅仅是数理化的智力,它是"在具体情况下分析出如何应对"的解决问题的综合能力.
	 它让一个人最大化地利用手里的资源~达到自己的目的,以及,趋利避害.
6. 行动意识
	 不要试图没开始就计划"完美",快行动.
	 有一个general idea后,就可以先行动来.在做事的过程当中,更多是一个动态决策的过程.在一开始就没有完美计划,也不可能有.因为新情况一直出现.
7. 试错意识
	 错误是纠正方法的窗口,是让我们接近真相的一件好事.所以,不要怕犯错.

8. 信息筛选和学习能力
	 如何快速甄别重要和不重要的信息,以及如何快速学习重要信息.


** 2
1. 永远要有主见，知道自己要去哪
	为自己的project负责的，只有我自己。导师有很多学生有很多事，并不是最了解我的工作的人。因此，他有可能给出误导性的判断。如果我们不知道自己的研究主线是什么，自己的主要兴趣是什么，自己到底想做什么，很容易被导师的个别错误性指导误导，因此浪费时间。
	不仅是在工作上，在生活里也是，知道自己要去哪，是最大的效率。

2. 人际交往能力，最重要的能力之一
	博士读得成不成功，直接取决于你和导师的个人关系如何，以及他愿意在你身上投入多少资源。同事关系，决定了你能得到多少支持和想法。朋友关系，决定了你有多少信息渠道。
	天才毕竟是少数。社会还是人的社会。即使是强调个人能力的学术界，人际能力也是最重要的能力之一。

3. 学习能力其实就是专注能力，静的能力
	越能静下来，越有idea。

4. 永远不要试图没开始就计划“完美”，快行动
	有一个general idea后，就可以先行动了。研究的过程，更多是一个动态决策的过程。在一开始就没有完美计划，也不可能有。因为新情况一直在出现。

5. 主动性
	机会、信息、想法、导师的指导，都是你越追求越多的。你越行动，你越有收获。
	对于实验学科来说，我感觉博士成不成功，很大程度上决定于兴趣和精力，而非智力。

6. 由研究得到的人生观
	 - 没有完美计划，做动态决策
		 人生亦如是。先上场，先行动。
	 - 我的眼里只有目的
		读博期间会遇见各种困难，你能不能依旧静下心来高效工作？心中装着优先级，知道什么是最重要的，就行。
		由此同理，你这一生要追求什么？
		不信任的人，就让它去。不重要的事，就让它去。
		你的人生，是你的project。这是最重要的。

		-	要喜欢和人交往，讨厌的，喜欢的
			你摆脱不了，就要学习共存，以实现目的。

		- 人生是非线性的
			前三年没发文章，博四发一篇顶刊、博后发一篇nature，然后找到很好教职的师兄，见过两个。博士读得不成功，就业赚大钱的人，大有人在。
			人生不是线性的。走着瞧。

** 1
最大的收获，其实是精神财富。

1. 目的意识
	做任何工作时，首先问自己一个问题，我的目的是什么？
	经常问自己，我现在做的事情，和我目的的关系是什么，有没有偏离我的目的？

2. 独立意识
	对于问题，首先要自己建立一个思路，再从别人和实践中借鉴和总结，改正或者优化这个思路。
	但首先，自己要有一个思路。这是解决问题的起点。一切靠自己。

3. 主动意识
	做研究都是自我驱动的。没人拿鞭子赶着你。没有人告诉你该做什么，该如何做，该多快做，做到什么地步，要回答什么问题....
	全靠你自己的主动性，在把工作向前推进。
	你是你工作的主人，同时你也是你生活的主人。你要为自己的事情负责。

4. 永远不要试图没开始就计划“完美”，快行动
	有一个general idea后，就可以先行动了。研究的过程，更多是一个动态决策的过程。在一开始就没有完美计划，也不可能有。因为新情况一直在出现。

5. 试错意识
	错误是纠正方法的窗口，是让我们接近真相的一件好事。所以，不要怕犯错。

6. 信息筛选和学习的能力
	在实践思路的过程中，总要学习新的知识。如何快速甄别重要的和不重要的信息，以及如何快速学习重要信息，是博士训练的内容。
	很多博士之所以毕业时变得特别自信了，就在于他在读博过程中变得独立了。他具有了独立解决问题的能力。
	独立解决问题的能力，是宝贵的精神力量。

