* Table of Contents                                                     :TOC:
- [[#前言][前言]]
- [[#第1章-学会提出好问题][第1章 学会提出好问题]]
  - [[#引言一切从批判性思维开始][引言:一切从批判性思维开始]]
  - [[#激发你的批判性思维][激发你的批判性思维]]
  - [[#两种思维方式-海绵式思维和淘金式思维][两种思维方式: 海绵式思维和淘金式思维]]
  - [[#淘金式思维举例-美国该禁枪吗][淘金式思维举例: 美国该禁枪吗?]]
  - [[#正确答案莫非只是神话][正确答案莫非只是神话]]
  - [[#最好先问一问关我什么事][最好先问一问"关我什么事"]]
  - [[#弱势批判性思维和强势批判性思维][弱势批判性思维和强势批判性思维]]
  - [[#亲自动手才更有乐趣][亲自动手才更有乐趣]]
  - [[#也许我们根本就问错了问题][也许我们根本就问错了问题]]
  - [[#价值观决定人与人之间的互动][价值观决定人与人之间的互动]]
  - [[#理智思考和感情用事][理智思考和感情用事]]
  - [[#让对话一直进行下去][让对话一直进行下去]]
  - [[#一厢情愿是批判性思维的最大劲敌][一厢情愿是批判性思维的最大劲敌]]
- [[#第2章-论题issue和结论是什么][第2章 论题issue和结论是什么]]
  - [[#是什么问题和应不应该问题]["是什么"问题和"应不应该"问题]]
  - [[#他到底在说什么啊][他到底在说什么啊]]
  - [[#他想让我相信什么结论][他想让我相信什么结论]]
  - [[#背-找到结论有线索可循][背! 找到结论有线索可循]]
  - [[#轮到你自己写时可得吸取教训][轮到你自己写时,可得吸取教训]]
- [[#第3章-理由是什么][第3章 理由是什么]]
  - [[#他为什么相信这个观点][他为什么相信这个观点]]
  - [[#找到理由有提示词][找到理由有提示词]]
  - [[#理由是模具结论据此成型][理由是模具,结论据此成型]]
  - [[#轮到你自己写时可得吸取教训-1][轮到你自己写时,可得吸取教训]]
- [[#第4章-哪些词语意思不明确][第4章 哪些词语意思不明确]]
  - [[#让人捉摸不透的多义词][让人捉摸不透的多义词]]
  - [[#找准关键词][找准关键词]]
  - [[#检查有没有歧义][检查有没有歧义]]
  - [[#判定歧义][判定歧义]]
  - [[#看看上下文这才是它的真实含义][看看上下文,这才是它的真实含义]]
  - [[#字典的定义不一定适合文章里的情境][字典的定义不一定适合文章里的情境]]
  - [[#小心那些饱含感情色彩的词语它会让你的思维短路][小心那些饱含感情色彩的词语,它会让你的思维短路]]
  - [[#谁想要说服你谁就得负责解释清楚][谁想要说服你,谁就得负责解释清楚]]
  - [[#轮到你自己写时可得吸取教训-2][轮到你自己写时,可得吸取教训]]
- [[#第5章-什么是价值观假设和描述性假设][第5章 什么是价值观假设和描述性假设]]
  - [[#到哪儿去找假设][到哪儿去找假设]]
  - [[#找出幕后遥控的价值观假设][找出幕后遥控的价值观假设]]
  - [[#两种价值观冲突时宁可要哪个][两种价值观冲突时宁可要哪个]]
  - [[#典型的价值观冲突][典型的价值观冲突]]
  - [[#对方的背景可以作为价值观假设的一个线索][对方的背景可以作为价值观假设的一个线索]]
  - [[#可能发生的结果是价值观假设的重要线索][可能发生的结果是价值观假设的重要线索]]
  - [[#如果争论的人采取相反的立场他们会关心什么][如果争论的人采取相反的立场,他们会关心什么]]
  - [[#一个例子关于竞争与合作的争论][一个例子:关于竞争与合作的争论]]
  - [[#使用这个关键问题][使用这个关键问题]]
  - [[#价值观及其相对性][价值观及其相对性]]
  - [[#找出没说出来的描述性假设][找出没说出来的描述性假设]]
  - [[#描述性假设展示][描述性假设展示]]
  - [[#找到描述性假设的一些线索][找到描述性假设的一些线索]]
  - [[#避免浪费时间分析无意义的假设][避免浪费时间分析无意义的假设]]
  - [[#轮到你自己写可得吸取教训][轮到你自己写,可得吸取教训]]
- [[#第6章-推理过程中有没有谬误][第6章 推理过程中有没有谬误]]
  - [[#不用死记硬背各种谬误的名称也能找到推理中的谬误][不用死记硬背各种谬误的名称也能找到推理中的谬误]]
  - [[#有可能假设是明显错误的][有可能假设是明显错误的]]
  - [[#推理理由谬误百出][推理理由谬误百出]]
  - [[#警惕分散注意力的干扰][警惕分散注意力的干扰]]
  - [[#愚弄人的循环论证][愚弄人的循环论证]]
  - [[#推理错误小汇总][推理错误小汇总]]
  - [[#轮到你自己写时可得吸取教训-3][轮到你自己写时,可得吸取教训]]
- [[#第7章-证据的效力如何-直觉个人经历典型案例当事人证词和专家意见][第7章 证据的效力如何: 直觉~个人经历~典型案例~当事人证词和专家意见]]
  - [[#为什么要相信它][为什么要相信它]]
  - [[#事实断言可靠吗][事实断言可靠吗]]
  - [[#证据从哪儿来][证据从哪儿来]]
  - [[#直觉作为证据可靠吗][直觉作为证据可靠吗]]
  - [[#个人经历作为证据可靠吗][个人经历作为证据可靠吗]]
  - [[#典型案例作为证据可靠吗][典型案例作为证据可靠吗]]
  - [[#当事人证词作为证据可靠吗][当事人证词作为证据可靠吗]]
  - [[#专家意见作为证据可靠吗][专家意见作为证据可靠吗]]
  - [[#轮到你自己写时可得吸取教训-4][轮到你自己写时,可得吸取教训]]
- [[#第8章-证据的效力如何-个人观察研究报告和类比][第8章 证据的效力如何: 个人观察~研究报告和类比]]
  - [[#个人观察作为证据可靠吗][个人观察作为证据可靠吗?]]
  - [[#研究报告作为证据可靠吗][研究报告作为证据可靠吗]]
  - [[#研究结果能采用吗][研究结果能采用吗]]
  - [[#样本能够代表整体吗][样本能够代表整体吗]]
  - [[#调查和问卷的回答真实吗][调查和问卷的回答真实吗]]
  - [[#一个例子-对取消终身教职的批判性评价][一个例子: 对取消终身教职的批判性评价]]
  - [[#类比作为证据可靠吗][类比作为证据可靠吗]]
  - [[#轮到你自己写时可得吸取教训-5][轮到你自己写时,可得吸取教训]]
- [[#第9章-有没有替代原因][第9章 有没有替代原因]]
  - [[#有果必有因][有果必有因]]
  - [[#可能的原因不止一个][可能的原因不止一个]]
  - [[#找出更多的替代原因][找出更多的替代原因]]
  - [[#唯一的原因还是原因之一][唯一的原因,还是原因之一]]
  - [[#组间差异的替代原因][组间差异的替代原因]]
  - [[#相关不能证明因果关系][相关不能证明因果关系]]
  - [[#在这之后不等于因为这个]["在这之后"不等于"因为这个"]]
  - [[#很多事件并非只有一种解释][很多事件并非只有一种解释]]
  - [[#哪个原因更合理][哪个原因更合理]]
  - [[#逐步缩小潜在原因的范围][逐步缩小潜在原因的范围]]
- [[#第10章-数据有没有欺骗性][第10章 数据有没有欺骗性]]
  - [[#不知来历的和带有偏见的数据][不知来历的和带有偏见的数据]]
  - [[#令人困惑的平均值][令人困惑的平均值]]
  - [[#把一个结论改头换面包装成另一个结论][把一个结论改头换面包装成另一个结论]]
  - [[#省略数据也是欺骗][省略数据也是欺骗]]
  - [[#表述方式不同效果更加动人][表述方式不同效果更加动人]]
  - [[#轮到你自己写时可得吸取教训-6][轮到你自己写时,可得吸取教训]]
- [[#第11章-有什么重要信息被省略了][第11章 有什么重要信息被省略了]]
  - [[#接受说服之前先打个问号][接受说服之前,先打个问号]]
  - [[#不完整的推理无法避免][不完整的推理无法避免]]
  - [[#识别省略信息的线索][识别省略信息的线索]]
  - [[#考虑是否有负面效果][考虑是否有负面效果]]
  - [[#面对信息缺失的现实][面对信息缺失的现实]]
  - [[#轮到你自己写时可得吸取教训-7][轮到你自己写时,可得吸取教训]]
- [[#第12章-能得出哪些合理的结论][第12章 能得出哪些合理的结论]]
  - [[#各种假设和多个结论][各种假设和多个结论]]
  - [[#两面还是多面][两面还是多面]]
  - [[#寻找多个结论][寻找多个结论]]
  - [[#某个条件下才合理的结论][某个条件下才合理的结论]]
  - [[#以解决问题为导向的可能结论][以解决问题为导向的可能结论]]
  - [[#让思维更加灵活][让思维更加灵活]]
  - [[#不是所有的结论都生来平等][不是所有的结论都生来平等]]
  - [[#更多可能的结论更多可能的自由选择][更多可能的结论,更多可能的自由选择]]

* 前言
* 第1章 学会提出好问题
** 引言:一切从批判性思维开始
-- 有点重复
对于所见所闻:
    一. 全盘接受,成为别人观点的奴隶  
    二. 做出评判,变成自己的观点  
通往合理结论的道路往往从问题开始,并且一路都有问题相随  
** 激发你的批判性思维
批判性思维:
    - 有问题的意识
    - 有主动利用问题的愿望
    - 有提出和回答问题的能力
** 两种思维方式: 海绵式思维和淘金式思维
-- 对于权威的教材,采用海绵式思维比较好.对于常见的日常的,批判性思维比较佳
海绵式思维:对于权威教材非常适合,比如本书  
    优点:
        1. 吸得多,可能用的上
        2. 被动吸收,如果材料本身很好的话,甚至比淘金式思维更有效
    缺点: 容易变成书呆子  
    逐字逐句地细读,关键句画线,用笔记概括主题和要点;经常温习画线部分,确保自己没有遗忘要点.记住作者说理论证的全部过程,但不对其做出评价.
		淘金式思维:自己掌握主动权,彷佛作者在想你细说原委,你随时与之辩驳(提一系列关键问题)  
		要求读者问自己一系列既定问题,目的要找出最佳判断.要质疑读者,提醒自己注意作者推理和论述中存在的问题.每时每刻都在与材料互动,
		目的要评价材料,在客观评价的基础上得出自己的结论.   
****** 背! 淘金式思维清单
- 作者是什么意图?
- 作者有问题的时候有没有记录下来
- 对作者的话有没有做客观评价
- 有没有在合理基础上形成自己的观点

** 淘金式思维举例: 美国该禁枪吗?
淘金式思维就是要参与进来,跟作者展开对话(提问题).

** 正确答案莫非只是神话
正确答案:
    自然科学:大家都能接受的"正确答案"  
    人文: 
        1. 动机复杂,党同伐异.  
        2.  而且关于人类行为本身就具有或然性.
            1和2导致,或然性导致我们必须接受那些与我们观点相反的人,而且要细细研究他们背后的理由
** 最好先问一问"关我什么事"
****** 行动! 巡检
检视一下自己日常的行为:问下自己日常的行为"关我什么事",然后换成其他的事情

** 弱势批判性思维和强势批判性思维
批判性思维:
    weak-sense弱势: 捍卫自己的观点  
        不关心接近真理和发扬美德,只为驳倒那些意见不同的人.摧毁了批判性思维人性和不断发展进步的特征  
    strong-sense强势: 评价和修正自己的初始观点  
        用关键问题一视同仁质疑一切主张,包括自己的主张.  
在思想上,开放与封闭的区别.  
真正值得自豪的观点,是那些透彻理解并且客观评价的观点

** 亲自动手才更有乐趣
亲自动手能带来很大的成就感.  
对于思想或观点接受还是拒绝,都胸有成竹.

*** 勤于练习的重要性

** 也许我们根本就问错了问题

****** 关键问题一览
关键是什么时间~怎样有效地提出这些问题:
    - 论题和结论是什么
    - 理由是什么
    - 哪些词语意思不明确
    - 什么是价值观假设和描述性假设
    - 推理过程中有没有谬误
    - 证据的效力如何
    - 有没有替代原因
    - 数据有没有欺骗性
    - 有什么重要信息被忽略了
    - 能得出哪些合理的结论
** 价值观决定人与人之间的互动
批判性思维很大程度是依赖听取别人意见来取长补短的

*** 价值标准和别人
价值观:什么东西更值,因为更值所以我们会这样选择,这样行动,同时想要别人也这么做    
我的一些价值观: 主动,好奇,礼貌,尊敬讲理者

别人就是我的知识库.因为价值观不同带来各种结论,我更倾向于价值观相同的人,排斥价值观不同的人.那么想要从别人那里获取知识,尤其要注意
那些价值观不同的人.因为按你的价值观得出的东西,和他的价值观得出的东西完全不同.

*** 批判性思考的人拥有的主要价值观
搞批判性思维的终极目标:寻求更好的结论,更好的看法,更好的决定.  
主要价值观:
1. 自主性.一方面要主动形成自己的结论,另一方面又要去寻求那些价值观不同的人结论
2. 好奇心.保持好奇心,对自己遇到的一切不断提问.对别人的意见或结论,只要符合正确推理的标准就要接受.
3. 谦虚.世界上哪怕最聪明的人也会犯下一堆错误,知道这一点,我们就有了和别人合作交流的平台.每个人各自擅长的不一样,每个人做的事情
    都非常有限. 苏格拉底说过:"我唯一所知的就是我一无所知".接受了这个现实,就可以在跟他人交往弥补一少部分我们当前认知的空缺.
4. 尊敬讲理的人.虽然想听取别人的声音,但也不是等同视之.一旦发现那些说理透彻~论据可靠的人,不论肤色~年龄~党派~财富~国籍,一定要毫无偏倚地信赖其观点.

** 理智思考和感情用事
遇到更强有力的分析推理能引导你进入全新方向时,有勇气当机立断地改变观点和立场,需要超乎常人的意志,下定决心发掘自己的最大潜能,塑造出
史上最强的自己.宁可在理由充分~证据确凿时反复无常,也不要在缺乏论据~强词夺理的结论上执迷不悟.  
思考是未来达到一定目的.思考的动机是为了同以前思考方向保持一致~毫不更改时,我们就在原地打转.更明智的做法,一旦思考,目的就是为了思想
更有深度,更加精确.那么就要锻炼自己,耐心倾听和我们意见相左的人的论证.  
这些过往的经历~梦想~价值观~所受训练~文化习俗,都是我们的包袱.

遇到更强有力的分析推理引导进入全新方向时,需要超人的意志,当机立断地改变观点和立场,塑造更强的自己.要做到这点,宁可在理由充分~证据确
凿时反复无常,也不要在缺乏论据~强词夺理的结论上执迷不悟.  
感情是包袱,思考的目的是为了思想更深~更精确.只有意思到这些包袱的存在,才能够听得进观点不同的人进行的论证.  

** 让对话一直进行下去
和我们交流的人价值观一样,那么大家面对问题,结伴同行.但是,有些人很不习惯别人追问自己.  
我们提供论证,是因为我们关心别人相信什么,做什么.而我们不断取得进步,也是得益于别人关心我们.  
进行批判性思考的时候,一定要让别人明白你好学上进.此外,要让他们相信你本意是好的,不管分歧有多严重,都不应以口诛笔伐收场.  
	
****** 背! 一些让对话进行下去的策略:
策略:  
    1. 尽量说明你对别人言论的理解,"我好像听你说过这个".
    2. 问一下别人,有没有证据能让他改变他的观点
    3. 提议暂停一段时间,我们可以尽量找到支撑自己结论的最佳证据
    4. 问一问别人,为什么认为我的证据不堪一击
    5. 弥合分歧,把两人的最好理由综合到一起
    6. 寻找共同价值观或其他一致同意的结论,以此为基础,找出分歧产生的起点
    7. 好奇心再强,也要表现的体贴关心和不温不火,讨论的语气升温,就要不断提醒自己,是来虚心学习,不是来舌战群儒的
    8. 确保表情和肢体动作都表现出谦恭的样子.
*** 营造交流会话的友好氛围

** 一厢情愿是批判性思维的最大劲敌
是不是因为我希望它是真的这事才是真的,还是有确凿无疑的证据证明它是真的?  
对我们共同面对或独自面对的种种问题产生的焦躁和恐惧情绪构成一道防护墙,屏蔽了我们生活在其中的真实的世界,让我们看不见其本质.  
奇迹式思考(magical thinking)是批判性思维的最大劲敌.  

* 第2章 论题issue和结论是什么
首先必须找出争议或论题,然后再找出作者推销给你的结论.别人的结论就是他试图传递给你的信息,目的塑造你的信念和行为.

****** ?关键问题: 论题和结论是什么?

** "是什么"问题和"应不应该"问题
论题: 引发讨论的问题或争议  
描述性论题descriptive issues:解答都是要描述世界万物过去~现在和未来的存在方式  
规定性论题prescriptive issues:什么是对什么是错~什么该有什么不该有~什么是好什么是坏  
	
** 他到底在说什么啊
找到论题的方法不止一种:只要找到全文论述的问题,以及这个问题与全文的练习.只要符合论题的标准就行.  
    - 作者直接告诉
    - 先找结论  

** 他想让我相信什么结论
结论:
    有关问题:
        1. 作者希望证明的是什么?
        2. 和我交流的这个人主要观点是什么?
        答案都是结论.作者的 !任意! 解答都是结论  
    寻找结论时,同时也是在寻找支持结论的一系列陈述  
    本质属性: 甲之所以成立是因为乙,甲是结论,乙是结论的支撑材料  
纯观点(mere opinion): 没有证据支持的断言是纯观点  
分析推理: 相信一个陈述成立是因为你认为它由其他看法支撑  

*** 使用这个关键问题
找到结论后,基于支撑结论的所有材料,我该不该接受这个结论?

** 背! 找到结论有线索可循
找到结论的线索:
    1. 问问论题是什么.首先,看看文章标题.其次,看看文章开头第一段
    2. 寻找指示词
        - 因此(consequently)
        - 表明(suggests that)
        - 由此可知(therefore)
        - 由此得出(thus)
        - 因此可以断定(it follow that)
        - 我要说的重点是
        - 显示出
        - 证明
        - 告诉我们
        - 问题的实质是
    3. 特定位置.文章的开头和结尾.如果文章又长又臭,直接跳到结尾去看
    4. 记住不可能作为结论的东西
        - 背景资料
        - 证据
        - 例句
        - 定义
        - 数据
    5. 检查交流的语境和作者的背景
    6. 问一问"所以呢?"

** 轮到你自己写时,可得吸取教训
读者不知道我们的价值观和背景,他们只有纸张或屏幕,所以我们要下工夫将自己意思表达得清清楚楚  
批判性思维的障碍是无法建立起沟通的桥梁.  

*** 写作之前先将论题的范围尽量缩小
建议:写作之前花时间确定论题.有没有一个明确的论题,是区别作家成熟与否的标志.尽管多个论题很诱人,但是往往贪多嚼不烂.  

*** 引导读者得出你的结论
老老实实地把结论写出来,节省了读者的精力,而且提高了文章的逻辑度.  
写作首要主题:竭尽所能地组织自己的思想,明白无误地表达出来.自己虽然洞若观火,但读者没有透彻的了解.努力在作者和读者之间架起沟通的桥梁.

写作的首要目的,组织好自己的思想表达出来.  
最好有一个明确的论题,太多了搂不住.  
表达方式,直接把结论写出来既节省读者的精力,又提高了文章的逻辑度  

****** 来,做做思维体操
****** 背! ?关键问题: 什么是论题和结论?
1. 论题找不到,找结论 -
2. 找开头和结尾 +
3. 找指示词 + 
4. 排除法,背证例定数. 在家教育子女是错误  
5. 补上论题
6. 论题的类型
7. 是不是结论:作者到底想告诉我什么?

缺少找论题这个动作.  
缺少排除不可能的

* 第3章 理由是什么
背! 理由: 用来支撑或证明结论的事物  
    - 看法
    - 证据
    - 隐喻
    - 类比
    - 其他陈述
背! 论证大厦的三大柱石
    1. 论题的必要方法
    2. 结论的必要方法
    3. 理由的各种技巧
一个人有没有思想,主要标志看他能否提供充足的证据来支撑他的看法.  
想要公正评价别人的结论,就要谦虚,容忍那些可能与我们不一致的观点.如果只评价结论,对推理过程不闻不问,就会坚持自己所持的结论,遇到那些
观点一致的结论就青睐,遇到不一致的就排斥.思想就封闭了,我们应该保持开放的心态和好奇心.  

****** 背! ?关键问题: 理由是什么?
理由...+结论=论证.  
单个结论那就是孤零零的断言,无可评价  
单个理由也构不成论证,也无法形成逻辑关系  
理由可以有多,但是结论只有一个  

论证的几个特点:
    - 论证必有其目的
    - 论证的质量有高有低
    - 论证有两个明显的必要构成部分
    - 花点时间找出论证之所在,再去评估,这样对提出论证的人才公平

** 他为什么相信这个观点
为什么这个结论有道理  
    是否作为理由的陈述,需要回答"为什么作者相信它".  

施惠原则:先把别人的分析推理过程找出来,这些理由信不信先放一边,后面再细细评价这一推理过程  

** 找到理由有提示词
理由的提示词:
    - 由于
    - 因为这个原因
    - 因为这个事实
    - 鉴于
    - 由以下材料支撑
    - 因为证据是
    - 研究显示
    - 第一,第二,第三

** 理由是模具,结论据此成型
很多理由是提供证据的一些陈述:
    证据: 人们用来其断言为真的某些事提供证明的具体信息
        行动! 自己摸索一套规则什么场合用什么类型证据特别管用  
        - 事实
        - 研究报告
        - 生活实例
        - 统计数据
        - 专家
        - 权威意见
        - 当事人证词
        - 类比
描述性论证:
    理由一般是证据  
规定性论证:
    描述性的看法(对于是什么的看法)  
    规定性的看法(对于应该怎样的看法)  

*** 让理由和结论一目了然
在复杂的论证中,难以将论证的结构在脑海里清晰地展现出来.为了克服难题,建立你自己的组织方式,将理由和结论分开,自成一套逻辑系统  
找到理由并有效组织的一些线索:
    1. 圈出指示词
    2. 标出理由和结论
    3. 给理由和结论编上序号
    4. 在文章结尾处按顺序列出所有理由
    
*** 使用这个关键问题
找到理由之后,深入阅读时需要一遍又一遍地重温这些理由.结论站不站得住脚取决于理由的扎实与否.  

*** 先有理由,再有结论
弱势的批判性思维,可能会导致现编理由,这就叫反向推理.  
我们本来就有大一堆的观点,遇到争议的时候就变成了我们的原始结论.因为我们期盼这些结论靠支撑的理由屹立不倒或轰然倒塌.我们必须要做自己
的审查官.避免出现弱势批判性思维的反向推理.记住:理由是模具,结论据此得以成型和修改.  

** 轮到你自己写时,可得吸取教训
因为理由至关重要,所以在写作前和写作中都要特别注意理由.
*** 在作出结论前要探究可能存在的种种理由
关心批判性思维的作者会考虑到可能存在的种种理由并掂量它们的分量,然后才会作出结论  
哪怕过去已经对这一论题下了工夫了,但还应该去探究其他可能存在的理由.
    - 以前没用批判性思维标准研究,可能主观和片面
    - 还有可能之前的研究跟不上形势和潮流
    
搜索引擎范围太大,过于笼统
*** 找到涵盖你的论题的主要刊物

*** 帮助读者确定你的理由
- 尽量使用指示词来提示理由
- 给读者提供梗概或提纲

****** 来, 做做思维体操
****** ?关键问题: 理由是什么?
论题:  
结论:  
理由:  
支撑理由:  

* 第4章 哪些词语意思不明确
理性思考的终极目标--形成自己的理性判断.  
如果没有仔细核对起决定性作用的术语或词组的意思,也许你所评价的观点和作者的原意压根儿就风马牛不相及  

****** ?关键问题: 哪些词或短语意思不明确?

** 让人捉摸不透的多义词
词的多重含义在判断一个论证的价值时可能会带来很大问题  
警告: 我们常常误解所读的文章或听到的言论的意思,因为我们想当然认为很多词的意思是显而易见的  
当词组意思不明确,我们需要有进一步的解释才能判断推理的过程是否恰当  
有时候含糊其次是故意的,只有这样才能与时俱进,比如美国宪法的"自由","携带武器"的不同含义才能适应不断发展的现实需求  
交流中意思表达不明确无法避免.但是我们能够避免而且应该避免论证中出现意思不明确的情况.  
谁想要说服我们相信某件事或动手做某件事,那个人首先有责任澄清任何可能存在的歧义. 

词语的多重含义:
    1. 对论证产生重要影响.
        我们常常误解文章或听到的言论,以为很多词显而易见.  
        交流中无法避免,但是论证要避免.谁要说服我们,必须得澄清可能存在的歧义  
    2. 多重含义,有可能是故意的.为了今后,或者下面的具体执行
    3. 要强迫自己去找意思不明确的词或短语

** 找准关键词
牢记你找关键词的目的: 因为有人要我接受他的结论,所以我只需要去那些影响我接受他结论的词或短语.其他就死一边去  
****** !背 找到关键词的线索小结
- 坚持论题有没有关键词
- 在理由和结论中寻找关键词或短语
- 留意抽象的词或短语
- 通过扮演作者相反的立场来判断别人怎样给词或短语下不同的定义

** 检查有没有歧义
我知不知道它的意思?
    需要克服的障碍:
        1. 自以为和作者表达的是同一个意思.
            养成不断提问的习惯,不停地问"你这样说是什么意思",而不是"我就知道你是这个意思"
        2. 认为术语只存在一个明显的定义
            这些术语有没有那个不同的意思?

判定是否找到重要的歧义,将这个词的不同含义替换到推理论证的结构中,看看这个词的意思是否对理由支撑结论的效度产生重要影响  

****** 使用这个关键问题
作为一个批判性思考的人,就是不能轻易同意他的分析推理,知道他将影响推理过程的那些意思不明确的地方解释清楚才行  

** 判定歧义
广告商们希望你把最具吸引力的意思安到这个意思不明确的词语上去,利用批判性思维为自己保驾护航.  
先找论题,结论,理由.将结论和理由的词逐个筛查.  

** 看看上下文,这才是它的真实含义
语境: 创作者的背景  
    eg. 人权:
            挪威领导: 就业权~免费医疗权和居住权  
            美国参议员: 言论自由权~宗教信仰权~旅行权以及和平集会权  
词语在论证中的习惯性用法,可能出现的歧义词前后的其他词语和陈述,这些因素合起来提供了线索.  
    eg. 游乐园的极大满足.游乐园游戏项目应有尽有.  

语境:
    - 创造者的背景. eg. 人权在不同国家的定义
    - 在论证中,歧义词的上下文. eg. 游乐园的极大满足,游戏项目应有尽有  

****** 使用这个关键问题
因为有歧义的存在,可以理直气壮地不同意某些推理论证.和持论者有词语意思上的偏差,首先要解决这些偏差,然后才能接受这些推理过程  
仔细检查上下文语境来判定关键词或短语的意思.意思难以确定,那么就发现了重要的歧义.如果意思很清楚,但是不认同,那么就要警惕这个论证  

** 字典的定义不一定适合文章里的情境
****** 背! 词语的表达方式
1. 同义替换
    忧虑就是感到紧张不安  
2. 举例说明
    忧虑就是候选人打开电视收看选举结果公布时的心情  
3. 具体标准定义(definition by specific criteria)
    忧虑是一种主观上的不适感,伴随有自主神经系统越来越强烈的感受

** 小心那些饱含感情色彩的词语,它会让你的思维短路
术语和词语的外延和内涵意义  
    外延意义: 词的约定俗成的外在描述性的指称对象  
    内涵意义: 我们对词附加的情感上的联想意义  
附加感情色彩的术语(loaded terms): 暂时让思维短路,通过直接连通情感路线来绕过描述性的意义通道,从而欺骗人们的思想  
我们隐藏在心中的感情可能被利用,他们可以使用正向激发的语言,也可以使用负面激发的语言达到其目的.  
    eg. 
        - 美国在阿富汗监狱的"惩罚自己的危险事故"的死亡类型  
        - 政治语言常常添加感情色彩而且模棱两可
            - 恢复: 同意征税提案
            - 公平: 改变
            - 恐怖分子: 野蛮~疯狂~未开化的
            - 改革: 期望的改变
** 谁想要说服你,谁就得负责解释清楚
如果他不能提供一幅清晰的说理论证的画面,那他就没有权力强迫你相信他

** 轮到你自己写时,可得吸取教训
写作时,容易忘记不同文化~不同经历和不同思想之间的巨大分歧,所有这一切都会给词语添加一层层含义  

*** 要时刻留意歧义
用反串的方法来检视你自己的文章.  
展开一场对话,把结论和理由拿出来和别人分享,看看使用术语的方法是否和你有明显的差别  
搞清楚你的读者和听众  

****** 来,做做思维体操
****** ?关键问题:哪些词或短语意思不明确?

* 第5章 什么是价值观假设和描述性假设
如果城市期望市民在行为上有所改变,城市的执法机构必然得强制实行这种改变.  
确实有道理,但是可能不足以支撑结论.  
如果制止乱丢垃圾是个人的责任而不是政府的责任呢?  
价值观的倾向: 集体责任大于个人责任  

粘合剂:  
    必须得有什么样的想法才能将理由和结论从逻辑上联系起来?  
    想法成千上万,哪些想法才有资格当作理由.只有提供这些联系后,才能真正理解这一论证.  

如果没找到这些潜在联系,就会发现自己不知不觉相信了一些观点,这些观点有可能稍加考虑就不会考虑. "洗脑"  

为什么要努力掌握本书的技能和态度?  
完全可以投掷硬币,或者问问专家该怎么办  
基于一些潜在的想法,我们认为批判性思维对我们有很多好处  
    批判性思考的人都相信自己做主~好奇心~通情达理等价值观是人类最重要的一些目标  
    批判性思维的最终结果是要求一个人虚心接受各种观点,理性评判这些观点,然后在理性判断的基础上决定接受哪些思想或采取哪些行动  

****** 背! 假设: 暗藏的把戏  
1. 隐藏或没有明说出来
2. 作者认为理所当然
3. 对判断其结论有较大影响
4. 可能有一定的欺骗性

****** ?关键问题: 什么是假设?

** 到哪儿去找假设
去哪找假设?  
    去论证结构中寻找这些假设  
两个特殊点:
    - 价值观假设:这个世界应该是怎么样的  
    - 描述性假设:这个世界过去~现在~未来是怎么样的  

** 找出幕后遥控的价值观假设
对于规定性论证,价值观会影响列举出的种种理由,因而也影响他的结论.  
只有把这些价值管假设添加到推理中,理由才能从逻辑上证实其结论  
你应该养成习惯,找出理由赖以成立的价值观假设.  

价值观假设: 一种想当然的看法,认为某些相互对立的价值观中一个比另一个更重要.  

** 两种价值观冲突时宁可要哪个
很多价值观是大家共有的,价值观本身不能成为理解的有力向导,能导致你对规定性论题做出不同回答的,取决于你对特定价值观的相对认同的程度.  

价值观冲突的时候,看看我们对论争的回应,就能明白我们对特定价值观的不同认同程度  

与论争有关的语境和事实问题也会影响我们的价值倾向.  

** 典型的价值观冲突
1. 忠实--诚实: 该不该告诉姑姑表兄打游戏?  不告诉忠实,告诉了诚实.  
2. 竞争--合作: 你是否支持评分制?  不支持评分制合作,支持竞争
3. 媒体自由--国家安全: 每周开总统新闻发布会是否明智  不支持开会媒体自由,支持开会国家安全
4. 平等--个人主义: 就业时的种族配额公不公平 不公平那就是个人主义,公平就是平等
5. 秩序--言论自由: 我们应不应该监禁那些有种族主义思想的人  监禁就是秩序,不监禁就是言论自由  
6. 理性--冲动: 打赌下注的时候该不该先查一查赔率  查理性,不查冲动  

1. 责任--自由
2. 义务--权利
3. 群体--个人
4. 和谐--冲突
5. 公平--效率

** 对方的背景可以作为价值观假设的一个线索
一个人的身份背景,代表这个人要追求的利益.  
追求自身利益并没有错误,但是这样的追求限制了作者所能包含的价值观假设  
    一家烟草业的大公司总裁不太可能特别重视对敏感人群的同情,如果这种对敏感人群同情的选择取代了对公司业绩稳定增长的选择,就有可能丢失自己的饭碗  

注意:并不是一个人作为团队的一员,就一定认同团队的特定价值取向.  

** 可能发生的结果是价值观假设的重要线索
结论到底能不能接受主要取决于潜在的各种结果发生的可能性大小和对这些结果的重视程度.  
判断价值观的手段:
    注意证实结论的各种理由,判断哪些价值取向导致作者认为这些理由比其他理由更可取,而其他理由本可以从论题的另一个方面论证  

理由带来一定的结果.这个结果对于某些价值观的能接受.  
其他理由带来另外一些结果.这个结果对于另外价值观的能接受.  
两者综合,对于某些价值观高于另外的价值观  

遇到有争议的主题,不断提醒自己作者放弃了什么,又得到了什么.抵制住一找到价值观就停止分析的过程.价值观是大家共有的,价值倾向才更重要  

** 如果争论的人采取相反的立场,他们会关心什么

这个冲突牵涉到个人有权以特定的方式行事,以及这种行事方式对集体幸福造成的影响  

****** 背! 找出价值观假设的其他线索
- 不断思考结论和理由之间存在的鸿沟  
- 原因产生的结果和其他原因产生的结果  
- 调查作者的背景
- 使用反串的方法
- 社会中类似的论证
- 找一找常见的价值观冲突

** 一个例子:关于竞争与合作的争论
结论一: 工作场所应该实行差别工资制  
理由: 涨工资的唯一依据就是工作效率,因此这种类型的工作场所为大家努力工作创造了最大的动力  

结论二: 工作场所应该团队协作的环境  
理由:工作环境健康,可以有效提高生产效率  

** 使用这个关键问题
每个关键问题的目的--为了使你最终能客观地评价推理过程!  
任何想要论证的人有必要提供一些解释,为什么我要接受论证中暗含的特定的价值观假设  

** 价值观及其相对性
虽然每个人都有一定的价值取向,但是选择价值取向也需要推理的过程.这种推理过程可能是有凭有据的,也可能是粗糙的.  

** 找出没说出来的描述性假设
找到价值观假设,就明白了作者希望这个世界是什么样的--什么样的目标认为重要.但是并不知道他对世界以及世人的本质是怎样想的  
描述性假设:对世界过去~现在或未来是什么样的想法  
    eg. 
        - 懒惰还是勤奋
        - 合作还是竞争
        - 由生理结构控制还是生长环境控制
        - 自私自利还是无私奉献
        - 理性还是反复无常
** 描述性假设展示
结论: 有了这辆汽车你想去哪里就去哪里  
理由: 这种型号的车在各种情况下都功能良好  
假设一: 年复一年,某个型号的汽车质量始终如一  时间    
    时间变化,但是事物没有发生改变  
假设二: 要用新车进行的试驾是由推荐这辆车的人亲自操作,与他之前的试驾完全一样 定义性假设  
    推荐者的驾驶意义与将要买车的人驾驶意义,假设相同  
 
找出连接假设.如果结论根据这些假设可以从理由推导出来.那么就可以推理完全正确,如果不可以,那么就不能证实结论.  

** 找到描述性假设的一些线索
找到假设的任务就是填补缺少的联系来重建推理的过程  
一旦头脑里有整体论证的全面图景,无论外在的还是内含的因素都得以体现出来,那么评价论证的强弱就游刃有余了  

****** 背! 找到价值观的线索
- 不断思考结论和理由之间存在的鸿沟  
    "你怎么从这个理由得出这个结论?"  
    "如果理由成立,要得出这个结论还需要哪些东西成立才行?"  
    "假设这些理由都成立,有没有可能这个结论仍然是错误的呢"  
- 寻找没有明说出来支撑理由的那些想法
    有时候给出的理由并没有明确的证据,为什么作者还用它当理由,因为作者有一些相关的描述性假设
- 将自己置于作者的立场
    假如你跟作者有同样的背景,你会怎么为这个结论辩护  
- 将自己置于反对的立场
- 认识到有可能存在其他方法来获取理由中提到的好处
    如果有多种途径都可以获得同样的好处,那么连接理由和结论的重要假设是,获得好处的最佳途径是作者所提倡的途径
- 避免表述不完全成立的理由来当作假设

** 避免浪费时间分析无意义的假设
无意义的假设: 不言自明的描述性假设  

刻意指出作者假设他们的理由都成立,这种就毫无意义  
指出作者相信理由和结论之间有逻辑联系也无意义  

** 轮到你自己写,可得吸取教训
是否要将想法抛在一边而只忠于事实?  
忠于事实?
    - 什么样的事实?
    - 你又怎么判断哪些事实对你而言最有力度?
    - 你又怎么判断哪些事实需要排除在外?
    - 你又怎么去解读事实并从中获得结论
    - 你认为这些事实当中蕴含的道理是什么?

你对于事实的反应受到你的价值倾向和描述性想法的影响,你想到的是大学的目的和团队运动在我们文化中的重要性    
如果没有价值观和描述性想法影响你的论证,你根本就不可能写作.  
因为我们的人生和经历的缘故,我们养成这些根深蒂固的想法.这些想法会以重要的形式影响到我们看世界的方式.  

作者应该特别注意这些想法在写作中造成的影响:
    - 这些想法常常没有明说出来或者假设成立的  
    - 给接受你的交流者一个公平的机会,来全面理解你的推理论证  

****** 来,做做思维体操
****** ?关键问题:什么是价值观假设和描述性假设?

论题: 该不该任何时候都诚实无欺?  
结论: 不该,诚实无欺未必是最好的选择
理由: 
    1. 真相并不是非说不可
    2. 对朋友说真话,可能会伤害朋友之间的情感  
价值观假设: 友情比诚实重要,安慰与勇气之间的冲突  

结论: 在特定情况下撒谎以不伤害别人的感情是正当行为  
理由: 说出真相也许会伤害友谊  
价值观假设: 强调伤害朋友关系的负面结果.因此论证的价值冲突就是诚实与和谐的人际关系  
            还有就是安慰和勇气之间的冲突  

结论: 大学生应该考虑加入联谊会  
理由: 
    1. 学生可以建立自己和他人间的坚强联系纽带
    2. 与他人交往建立人际关系网,对今后求职有帮助
    3. 联谊会活动锻炼了人的领导能力
    4. 联谊会促进了社交活动,同时还能寻欢作乐
价值取向: 归属感和找乐子比自律和学业成绩重要  
其他途径获得: 这些好处可以通过其他途径获得  
第一个理由:(描述性假设) 未来的老板把联谊会当成个人履历的一部分时才可以成立  
 
* 第6章 推理过程中有没有谬误
回顾下这些问题:
    1. 什么是论题和结论?
    2. 什么是理由?
    3. 哪些词或词组意思不明确?
    4. 什么是价值观假设和描述性假设?

按照提供的理由来看,这个结论到底多大程度上可以被接受?
    现在要做好准备全心全意集中火力进行评估  

现在我们的任务是将破铜烂铁从真金白银中挑选出来
    我们要分辨出最佳理由  

谬误:推理中的欺骗手段,作者有可能利用这个欺骗手段来说服你采取结论  
    三种常见的诡计花招
        1. 提供的推理需要明显 错误的或者让人不能接受的 假设才能成立,因此推理和结论显得毫无关系
        2. 把那些明明和结论无关的信息弄得好像和结论有关,以此来分散我们的注意力  
        3. 看似为结论找证据,而证据成立的前提则取决于结论本身已经成立  
        
****** ?关键问题: 推理中有没有谬误?

** 不用死记硬背各种谬误的名称也能找到推理中的谬误
只要问出恰当的问题,就能找到推理谬误,就算叫不出名字也无所谓.  
    因此采取的策略是着重强调自己提问自己的办法,而不是死记硬背一堆谬误的名称.但是了解常见的也是有很有必要  

** 有可能假设是明显错误的

(滑坡谬误)一旦我们基于一个案例的法理依据来采取行动,那么在类似案例中采取行动我们就再也无法阻止  
(追求完美解决方案谬误)

****** 背! 推理的结构:
1. 找出结论和理由  
2. 记住结论并思考你认为可能与其有关的理由,将你的理由与作者的理由作比较  
3. 如果结论支撑某个行为,那就去判断理由是否表明了某个特殊/具体的优点或不足,如果没有,就要当心  
4. 问下自己:"如果理由成立,一个人要相信什么才能从逻辑上支撑这个结论,他还得相信什么才能让理由成立?"从而找出任何可能存在的假设  
5. 问下自己:"这些假设有没有道理?"如果是明显错误的假设,那你就找出了推理中的一个谬误,这个推理也就可以放在一边不管了  
6. 看看有没有一些强烈诉诸你情感的词组可能干扰或分散你的注意力,让你没有考虑到相关理由  

** 推理理由谬误百出
共识:医疗界的共识  民间的共识  


** 警惕分散注意力的干扰
只要持论者防止别人太过详细地审视他的理由,就可以捍卫这一断言  
作者有没有通过转移我们的注意力来欺骗我们?    
光环效应: 美德词汇能让人产生正面积极的联想,而它们都很概括,简直读者想它们是什么意思就是什么意思.  
    和人身攻击谬误相反,是政客经常使用的手段  
** 愚弄人的循环论证
不过措施有所改变,愚弄那些单纯无知的人  
阅读传统教科书比阅读电子文本在学习效果上要好得多,因为以教材的形式来展现各种材料非常有利于学习  

让媒体对自己的新闻来源保密对于国家来说非常有利,因为这就增加了个人提供证据来举报权威人士的概率  

让媒体对自己的新闻来源保密对国家而言非常有利,因为个人有权向媒体提供信息而不必确认自己的身份,这样做将非常有助于大集体的利益  

****** 使用这个关键问题
因为我们是建设性批判性思考者,所以我们还要考虑论者提出的任何一个不是谬误的理由.  

** 推理错误小汇总
自己搞个谬误清单  
找出推理谬误的方法: 那些与论题相关的证据和道德原则,什么才是好的理由.  
    一旦推理中出现了错误假设~分散注意力或者支持已经假设结论是真理的结论,这一推理就该摒弃  
    一旦诉诸大众认可的观点或者诉诸权威,这样的推理也应该小心对待.
        "将这些说法当成说服人的证据有没有扎实过硬的理由?"  
** 轮到你自己写时,可得吸取教训
手头准备一份谬误清单,在构建自己的论证大厦时,小心检验  

******* 来,做做思维体操
******* ?关键问题: 推理论证中有没有什么谬误?
论题: 儿童该不该开展性教育  
结论: 卫生局局长不应该建议开展性教育  
理由:
    1. 不是他的职位权限
    2. 他是焦虑者
    3. 教育开展性教育,剥夺了家庭本该有的性教育,会对全国儿童造成损害  

结论: 性教育不该在学校开展  
理由:
    1. 卫生局长受到艾滋病恐慌和媒体渲染的影响  
        作者一开始就攻击卫生局长而不是驳斥论题.人身攻击  
    2. 报告完全排除了家庭的作用
        稻草人谬误.暗示性教育的目标就是包揽儿童性教育的一切  
    3. 性教育是父母的工作,这是自古的方式,今后也应该保持下去
        一厢情愿谬误,性教育应该由父母承担和决定并不意味着父母会提供这些教育  
    4. 要么有学校的性教育,要么面临价值观和道德观的剥夺     
        虚假的两难选择  

结论: 不应该禁养比特犬  
理由:
    1. 比特犬受到无理歧视,因为少数几例过激事件  
        人身攻击  
    2. 大多数特殊来自于恨犬人士  
        人身攻击  
    3. 我养了的狗七年多,表现良好
        轻率概括谬误  
    4. 金毛犬也咬人,单纯禁养比特犬并不能完全防止狗咬人
        完美方案谬误  
    5. 爱犬诊所的主任,绝大多数比特犬都不是好斗凶狠的
        绝大数?, 诉诸公众    
    6. 禁养比特犬法案通过,下一步是禁养一切可能咬人的狗
        滑坡谬误  

* 第7章 证据的效力如何: 直觉~个人经历~典型案例~当事人证词和专家意见
针对推理的一个具体部分提出关键问题:
    对事实的断言

****** ?关键问题: 证据的效力如何:直觉~个人经历~典型案例~当事人证词和专家意见?

** 为什么要相信它
事实断言(factual claims): 对于世界过去~现在~未来是什么样的,可能是结论,可能是理由,也可能是假设进行判断  
孤立论断: 断言需要证据却没有看到证据  
"证据的效力怎么样?"  
事实: 对于大部分断言,要证实它是绝对的真理或谬误非常困难.与其问一问是不是真的,不如去问问是不是可靠.
    断言的证据数量越多~质量越高,就越可以称这样的断言为"事实".  
确定事实的可靠性?  
    - 你的证明是什么?
    - 你怎么知道它是真的?
    - 证据在哪里?
    - 你为什么相信它?
    - 你确信它是真的吗?
    - 你能证明吗?
如果持论者想要你认真考虑这个论证,会用实质性的证据来证实其断言,希望你能渐渐认同他们的结论  
    相反如果对于出示证据的要求是怒火中烧或退避三舍,因为他们意识到没有证据,自己的看法不应该那样底气十足  
对于很多看法没有足够的证据证实或驳倒它们.这种情况下,要判断,证据数量在哪边,这样才能决定事实断言的可靠程度  

** 事实断言可靠吗
事实断言的分类:
    1. 描述性结论
    2. 用来证实描述性或规定性的理由
    3. 描述性假设

** 证据从哪儿来
三种情况下我们倾向于同意它是事实断言:
    1. 断言表现出无可置疑的常识  
        举重可以锻炼出身体的肌肉  
    2. 断言从无懈可击的论证得出的结论  
    3. 断言在同一场交流中被很多过硬的证据合理地加以证实  

证据的类型以及对应的问题:  
    - 直觉
    - 个人经验
    - 典型案例
    - 当事人证词
    - 权威意见
    - 个人观察
    - 研究报告
    - 类比
** 直觉作为证据可靠吗
当我们用直觉来证实一个断言,依赖的是"常识判断力",或者依靠"预感",或是依赖"第六感".  
    跟着心儿走,  
    跟着感觉走,  
    它会领着你到你想去的地方.  
    放飞理智吧,  
    去寻找你的直觉,  
    很容易你就找到它.  
直觉: 我们相信自己对某件事有直觉的洞察力,却不能有意识地说出理由的过程  
    问题: 私密性,别人无法判断它的可靠性  
            1. 凭直觉得来的看法会相互冲突,缺乏坚实的基础来判断该相信那些.要警惕这些断言  
            2. 但直觉其实也依赖于其他类型的证据.大量相关的个人经历和阅读经验,会不知不觉地从我们脑海的某个角落释放出来  
** 个人经历作为证据可靠吗
研究证据和样本的时候还要重温一下  

** 典型案例作为证据可靠吗
典型案例: 不厌其详而又引人入胜地描绘或是塑造一个或多个人物或事件来证实某个结论  
    eg. 通常基于观察或者访谈,有深度描述到表明走过场的  
    原理: 典型案例非常具体生动而又细致感人,很容易在脑海中浮现.丰富的细节会激发听众热烈的情感回应  
    对比个人经历: 关键是典型  
** 当事人证词作为证据可靠吗
当事人证词: 通过引述具体当事人的话,尤其是名人的话,来说明某个想法或产品的好坏,或者非比寻常的事情确实发生过,这些都是他们的亲身经历.  
    个人经历: 提供一种说法证明某产品~事件或服务的价值  
    用处不大  
    一些问题:
        - 选择性:"我们没机会听到的那些经历感受是什么样?"  
            商家会有选择性地选择当事人和证词.
        - 个人兴趣:那个作证的人是不是和提倡的东西有什么特殊关系,因此发现了强烈的偏见  
            当事人可能从商家那里拿了好处.  
        - 省略信息: 当事人没有提供足够的信息作为判断的基础,我们的评价标准很可能大不相同  
        - 人为因素: 当事人值得信任  
** 专家意见作为证据可靠吗
面对复杂的生活我们只能几个方面小有所成,要样样精通,既无时间也无知识储备.  
"我们为什么要相信这个专家呢?":
    - 在这个主题该专家拥有的专长~训练或特别知识到底有多少?
    - 这个主题是不是他潜心研究多年的成果?
    - 这个人有没有与此主题相关的丰富经历?
    -----------
    - 专家的地位是否有特别好的渠道来获取相关事实?
    - 有没有较好的理由让人相信专家的意见相对不会受到歪曲?
        - 有个人利益时需要警惕  
        - 不能完全因为个人利益放弃专家意见,"这个专家是不是因经常做出可靠的断言而名声在外?"  
    - 努力了解网站的建设目的~信誉以及与之有联系的发帖者的经历.检查网站是不是与声誉较高的其他网站有关系或链接

** 轮到你自己写时,可得吸取教训
*** 期待批判性的读者
如果你是读者,面对相关证据会怎么问,那就期待读者提出同样的关键问题,尽量未雨绸缪地回答这些问题.

*** 判定你要不要更多的证据
结论或是理由的争议性越大,就要费更多精力去提供证据  
要特别留意只依赖于个人经历~当事人证词~专家意见的证据  

*** 你的学术写作和证据
坚守一系列写作习惯和写作期待,比如说: 要避免前后矛盾或淫词艳语  

****** 来,做做思维体操
****** ?关键问题:证据效力如何:直觉~个人经历~典型案例~当事人证词和专家意见?
结论: 戴"前进"头盔提高了篮球明星的投篮命中率  
理由: 著名篮球运动员热烈谈论头盔的正面作用  

结论: 保妥适注射是安全的  
理由: 一个整形医生和国立专业机构都宣称保妥适安全  

* 第8章 证据的效力如何: 个人观察~研究报告和类比
****** ?关键问题: 证据的效力如何:个人观察~研究报告和类比?
** 个人观察作为证据可靠吗?
个人观察:因为我们对亲眼所见的事情会信心十足,因此倾向于依靠目击证人的证词作为证据.
    缺点: 不像特定的镜子,并不能给我们提供"纯粹"的观察
        - 经过特定的价值观~偏见~态度和期望值过滤
            - 我们见到和听到的都是我们愿意听到和见到的东西
            - 我们挑选和记住的经历的侧面都是和我们以前的经历和背景最相符的那些侧面  
        - 有各种重要障碍阻止我们看清楚发生的一切
            - 注意力不集中
            - 观察事件快速进行
            - 压力重重的环境
** 研究报告作为证据可靠吗
研究报告: 通常由训练有素的科研人员来系统地收集观察数据.  
科学研究: 最好的证据来源  
    - 可验证性
    - 可控性
        使用特别的程序来减少观察和研究成果的犯错率  
    - 精确性
** 研究结果能采用吗
一个问题即使应用了科学研究方法仍然不必然意味着研究证据就是可靠的.  
因此,对于研究报告而言,还要提出重要的问题,才能决定结论的可信度.
    - 研究的质量和人为因素变化非常大
        1. 研究的质量有高有低,差别很大.
            有的研究精细,有些头功减料.  
        7. 研究的人为程度到底怎么样常常也会导致研究的变化.
             常常为了达到控制实验的目的,使得研究失去了一部分现实世界的特征.  
    - 研究结果常常互相矛盾,事实会随着时间的流逝而发展
        2. 研究成果常常会互相矛盾  
            "其他的研究人员有没有核实过这些发现?"  
        6. 研究的事实会随着事件的流逝而发生改变  
    - 研究的结果只能支撑结论
        3. 研究结果并不能证明结论,充其量只能支撑结论.
            研究人员的结论不应当被当成证明了的真理. 遇到"研究结果表明...",应该重新解读为"研究人员解释了他们的研究结果表明了..."  
    - 科学研究是人类活动,会受歪曲,而且主观因素在所难免
        8. 对经济效益~社会地位~人身安全和其他因素的需求可能会影响到研究的结果  
        5. 作者常常歪曲后者简化结论.
             研究人员在原始研究报告中仔细限定了结论,只不过结论到了他人手里,这些限定马上被拿掉了  
        4. 跟我们一样,研究人员也有期望值~态度~价值观和需求,这使得他们所问的问题~做研究的方法~解释研究结果的方式都落下了偏见的印记.  
****** 背! 评价科学研究的一些线索
- 研究的质量和人为因素变化非常大
1. 报告的资源来源质量怎么样?
    最可靠的报告往往出自同行专家评定的期刊上的文章  
2. 交流中有没有其他线索显示这项研究完成的很出色?
    研究报告有没有提供足够的细节来说明此项研究  
8. 研究条件是不是人为制造的并因此遭到扭曲变形?"研究进行的客观条件和研究者概括的情境到底由多少相似之处"  

- 研究结果常常互相矛盾,事实会随着时间的流逝而发展
4. 这些研究的结果有没有被其他的研究重复过?
3. 研究进行的时间离现在多久,有没有理由让人相信研究结果会随时间的流逝改变?

- 研究的结果只能支撑结论
9. 根据研究样本,我们能概括的范围到底有多大  

- 科学研究是人类活动,会受歪曲,而且主观因素在所难免
6. 有没有强势批判性思维的证据.作者对于先前支持他的观点研究采取批判的态度.
7. 有没有理由让人蓄意要歪曲这项研究?我们要当心研究人员亟需找到特定结果的那些情况.
10. 研究人员使用的调查有没有偏见或者歪曲的现象存在?
5. 持论者选择研究的时候是怎样精挑细选的?比如,有没有相反结论被他忽略不计?研究人员是不是只选择支持他的观点的研究?

** 样本能够代表整体吗
概括性结论: 关于一般性事件的断言
    eg. "此例药物对75%的癌症患者治疗效果明显"并不是概括性的结论,而"此例药物可治疗胰腺癌"才是概括性结论  
概括的影响因素:没搞好,就会过度概括  
    抽样方式: 影响是至关重要的  
        - 样本数量
        - 覆盖各种类型率
        - 样本的随机性
        重要的考虑因素:
            1. 样本的覆盖率必须要大到足以产生概括得出结论的程度  
                研究1000名大学生比100名更有说服力
            2. 对于事件的类型,样本必须覆盖足够的范围或包含足够的多样性
                必须建立在各种不同类型的大学的各种不同类型的学生中进行抽样  
            3. 样本的随机性越大越好,可避免特定类型的有片面特征的样本  
            片面特征:
                1. 自愿报名接受访谈,讨论性行为的人  
                2. 只有有线电话的一群人  
                3. 一堂心理学导论课上的学生
                4. 特定电视网的观众
** 调查和问卷的回答真实吗
调查和问卷的可信度:
    - 要使调查的回答变得有意义,针对调查的回答必须是实话实说  
        要让人实话实说,而不是说认为应该说的话.或者让人对问题怀有敌意  
    - 调查问题的措辞含糊不清,可以做出多重解读  
        调查的措辞用字越含混,对调查结果的可信度就越要打折扣  
    - 调查本身就包含很多偏见  
        措辞偏见: 褒义或者贬义的词  
        语境偏见: 问卷调查的上下文存在偏见  
        问卷长度: 导致人们的不耐烦  
仔细盘查调查的程序,然后再接受调查的结果  
** 一个例子: 对取消终身教职的批判性评价
这个证据的证明效力怎么样?  
有没有什么过度概括的证据?  
调查的问题本身有没有存在偏见?  

** 类比作为证据可靠吗
类比(analogy): 论证用两件事物之间熟知的相似点作为基础,推导出关于其中一件事物的相对未知特征的结论,这样的论证叫做类比论证  
    我们了解甲事物很多,另一件乙事物和甲事物某些重要方面非常相似,如果两件事非常相似,那么它们在其他方面也会非常相似  
    乍一看非常有说服力,但是类比往往会欺骗我们  
    类比既能激发深刻的见解同时又能蒙蔽我们  
        eg. 老鼠的实验推导出在人身上的结论  
            相似法律案件的论断  
*** 识别和理解类比
怎么识别论证?
    具有人们熟知的某些特征的事物 被用来 帮助解释 和它具有类似特征的事物.  
类比论证时做的描述性假设:  
    如果 我们有兴趣要解释的事物 与 被拿来和它作比较的事物 在很多重要方面都很相似, 那么它在其他重要方面也会与那事物相似  
要当心:  
    框架类比(framing analogies): 不仅用于解释一个要点,同时影响讨论的方向  
        eg. 伊拉克战争比作越南战争,伊拉克战争比作二战  
        一定要经常寻找试图通过框架把人们反应引向一个特定目标的比较,通过仔细评价,可以避免潜在的具有欺骗性类比的误导  
    过度情绪化比较的论证:
        临终护理计划比作死亡专案小组  
*** 评价类比  
评价类比的质量的两个因素:
    1. 两个作比较的事物相同和相异的方式  
    2. 相似点和不同点之间的关联  
一种建设性方法找到自己的类比:
    1. 识别你正在研究的情况的一些主要特征  
    2. 尽量找出与上述情况有相同特征的你所熟悉的情况,开动脑筋,尽量想象出多种不同的情况
    3. 尽量判定熟悉的情况是否能为你提供不熟悉情况的一些洞见  
    
** 轮到你自己写时,可得吸取教训  
作研究:
    方法论: 在开始独立研究之前,研究者往往先建立一套程序或规则来指导研究的过程.  
        敲定方法时,避免出现片面的问卷调查和抽样中存在的问题  
    保留精确可随时查看的记录  
    记住研究结果存在的局限,注意过度概括的风险  
*** 科学研究和互联网
注意作者自身背景  
花点事件去查看一下资料的原始来源  
注意一些片段剥离原来的语境加以使用  
****** 来,做做思维体操
****** ?关键问题: 证据的效力如何: 个人观察~研究报告和类比?
没有批判性思维证据.细节不足.没有被其他研究重复过.  
样本的数量还行,覆盖率不行,从匿名戒酒会里面.随机率也不够.  
酒鬼含糊不清,而且带有措辞偏见.没有具体的问题细节  
不足为凭    

* 第9章 有没有替代原因
使用证据过程中的常见问题: 要想弄清楚一件事,就必须弄清楚引起这件事的原因  
    只有我们一开始就理解了某件事的前因后果,才能选择明智的办法来避免某个问题的发生,或者促进特别正面的结果出现  
****** ?关键问题: 有没有替代原因?
** 有果必有因
当你有足够理由相信作者使用证据来证实某件事的起因时,你就需要去寻找一些替代原因.  
因果关系的指示词:
    - 导致...
    - 影响了...
    - 与...有关
    - 阻止了...
    - 增加了...的可能
    - 决定了...
    - 与...有联系
    - 有...的效果
** 可能的原因不止一个
因果关系的事件:
    1. 我们日常的人际交往
    2. 以往或正在发生的世界大事
    3. 科学研究的结果
****** 得到的教训
1. 很多类型的事件都可以通过各种相互替代的原因来加以解释  
2. 专家可以检查同一个证据而发现不同的原因对其加以解释  
3. 大部分持论者只给你它们喜欢的原因,独立思考的读者或者听众必须自己找出替代原因  
4. 想出替代原因是个创造性的过程,通常这类证据不会是一目了然的  
5. 最后,特定因果断言的确定性和言之成理的替代原因的数量正好成反比.因此,找到多个替代原因可以让批判性思考的人真正变得理智而谦逊  

** 找出更多的替代原因
一些方法:
    - 我能不能找到其他方法来解读这个证据?  
    - 还有什么别的可能会引发这个行动或者导致这些发现?
    - 如果我从另一个角度来看这个问题,哪些东西我可能会当成重要的原因?
    - 如果这个解释是不正确的,还有什么别的解释可以说得通?
** 唯一的原因,还是原因之一
人们常犯的错误就是试图找出一件事的简单而又唯一的原因,而事实上这个原因是由许多共同起作用的原因联合起来的结果.  
事实上,几乎所有的因果解释都会过度简化.所以有些持论者即使没有提供每一种可能的原因,我们也得公平对待它们.  

** 组间差异的替代原因
组件差异的替代原因: "有没有可能存在替代原因也解释得了这种组间差异?"  
随机化实验设计: 将替代原因减到最少  

** 相关不能证明因果关系
由多种假设可以解释为什么甲乙相继发生
    1. 甲是乙的一个起因(吸烟确实杀死了病毒)
    2. 乙是甲的一个起因(从来不受流感病毒侵扰的人更有可能继续吸烟)
    3. 甲和乙有关系是因为丙(吸烟以后经常洗手阻碍了流感病毒)
        忽略常见原因谬误  
    4. 甲和乙相互影响(不常患感冒的人有吸烟的倾向,而吸烟有可能影响到一些潜在的疾病)  
        因果混淆谬误  
** "在这之后"不等于"因为这个"
人类诉诸于感性: 愿意相信如果两件事紧随前后发生,那么第一件事肯定导致了第二件事  
商界巨头喜欢把自己走上领导岗位之后发生的一切好事都揽到自己头上,而发生的一切坏事则推到其他人头上  
"除了一件事紧随在另一件事后面发生这个事实以外,还有没有什么其他过硬的证据"  

遇到这种事后归因时,要非常小心.小心地确认有没有过硬的证据再下判断.  
事后归因错误:  

** 很多事件并非只有一种解释
寻求历史事件的解释:
    - 同一事件有多种版本的故事能说通
    - 解释事件的方式深受各种社会力量和政治力量的影响,同时还受到信仰有关的个人心理视角的影响  
基本归因错误:    
一定要当心,不要贸然接受你遇到事件的第一个解释.我们必须接受这一事实,很多事件并不是只有一种解释  
 
** 哪个原因更合理
比较理由使用的标准:
    - 逻辑上的合理性
    - 和你所学其他知识之间的一致性
    - 以前解释或预测事件的成功率

** 逐步缩小潜在原因的范围
吸收到论证的文章是不是真的展现了因果关系.很可能被标题误导.  
****** 来,做做思维体操

* 第10章 数据有没有欺骗性
使用统计数据来支撑论证:
    - 揭示战争伤亡人数的增加或减少
    - 提醒公众注意发病率的变化
    - 估量一种新产品的销量
    - 判断某一只股票的赚钱能力
    - 决定下一张牌是A的概率
    - 来衡量不同大学的毕业率
    - 来记录不同年龄段的人们性生活的频率
    - ...
统计数据可能经常骗人!  

****** ?关键问题: 统计数据有没有欺骗你?
** 不知来历的和带有偏见的数据
作者是怎样得出这个估计的?
    统计数据只能是基于事实做出的一些估计,尽量找到足够多的关于数据是如何采集的信息

不知来历的统计数据: 用大量的数字给别人加深印象,但是这些数字的精确性却让人怀疑  
    在对这样的数据做出反应之前,要先问一声它们是怎么得来的.  

** 令人困惑的平均值
是平均数~中位数还是众数  
****** 平均值的种类及计算方法
- 平均数:
    个别高的收入会急剧拉高平均数,但对于中位数或众数影响不大  
- 中位数 
    如果是中位数或者众数,就有可能高估了平均的学习时间   
- 众数
- 全距: 最小与最大数值之间的差距  
- 数值分布: 每个数值出现的频率  

** 把一个结论改头换面包装成另一个结论
持论者欺骗我们,用数据来证明另一件性质完全不同的事 
    应对欺骗的策略:
        1. 对持论者的数据视而不见,然后问自己"什么样的统计数据作为证据证明他的结论方面会有帮助?"然后再与给出的数据做对比.  
            要加倍注意统计数据的措辞和结论的措辞是不是同一件事情  
        2. 不急于去看作者的结论而是先非常细心地检查作者的数据,然后问自己能得出什么合适的结论?
** 省略数据也是欺骗
统计数据经常因为不完整而欺骗我们.在数据推理找出缺陷非常有用的策略就是问一问:"在你判断数据的影响力之前还需要哪些进一步的信息?"  

当你遇到让人动心的数字或者百分比,一定要当心!
    - 当只有数值没有百分比的时候,问一问是不是百分比可能会帮你做更好的判断
    - 只有百分比没有数值的时候,问一问是不是绝对数值会丰富它们的含义  
相对比较的缺失: 这是和什么相比较?
    eg.
        - 美杜莎发胶,现在效果要好50%
            是对比自己之前的产品,还是对比其他品牌的产品
        - 运动型轿车很危险,不该上路.2006年,有4650名车主死于运动型叫策划事故  
            对比不使用运动型轿车能减少多少  
        - 电影预算简直骇人听闻.看看<哈利波特>308 000 000美元
            哈利波特对比其他电影预算呢?代表了整个电影产业吗?  
        - 我们的文化正在日益弱智化靠拢.年轻人知道美国内战从哪一年开始还不到一半  
            这个调查结果和20年钱类似的调查比起来又怎么样?
** 表述方式不同效果更加动人
统计数据在论证中的常见用法就是报告作为某种医疗干预后的风险降低情况.  
多种不同方式报告:极大影响到我们对于实际的风险降低数值的认识  
    - 相对方式
    - 绝对方式
    eg. 医生的三种治疗方法的相关统计数据
        1. 甲疗法减少33%的未来再次患中风的可能
        2. 乙疗法减少3%的绝对风险,从6%降低到3%
        3. 丙疗法,94%的女性在十年内不会再患第二次中锋,而没有接受这种疗法的病人有91%的人十年里不再患中风  
如果用绝对方式进行表述这些结果会有怎样的不同,会变得更加动人还是褪色不少   
** 轮到你自己写时,可得吸取教训
对于没有受过训练的读者而言,统计数据看起来像是权威事实,但是实际上事实是多么容易被人操纵.  

****** 背! 评估数据的一些线索
1. 数据的来历?
2. 数据的三种平均值,以及全距~数值分布
3. 数据是否真的能证明结论
    - 先不看数据,自己觉得应该需要什么数据和实际对比
    - 不看结论,自己总结数据
4. 判断什么信息缺少了,对于百分比或绝对数值的确实要特别当心  
****** 来,做做思维体操
****** !关键问题: 统计数据有没有欺骗你?

* 第11章 有什么重要信息被省略了
你看不到这些信息,但是它们对于你决定吃什么药治疗抑郁症有很大关心  
几乎所有结论都有正面的特点,那些持论者只会告诉我们正面的特点,并且不厌其烦~活灵活现.因此,我们要想独立思考必须寻找到作者隐瞒了什么
    信息,不论无心还是有意.  

****** ?关键问题: 有什么重要信息被省略了?

** 接受说服之前,先打个问号
问题: 几乎遇到的所有信息都有一个目的,那就是别人精心挑选和组织信息来说服你.  
对策: 说服你的人总是站在自己立场.因此,当你遇到很有说服力的理由时,犹豫片刻,想想作者可能没有告诉你的重要省略信息.  
    重要省略信息: 会影响你推理过程的信息  
    
** 不完整的推理无法避免
****** 背! 不完整的推理出现的原因
- 作者没有组织论证,并且受时间和空间的限制去展示理由
- 由于读者注意力集中时间的限制,作者必须尽快完成论证
- 作者自身的知识并不全面
- 作者为了利益进行欺骗
- 作者的价值观~信仰和态度都不一样,造成不一样的视角  
** 识别省略信息的线索
1. 要找省略信息
2. 要找什么省略信息
3. 怎么找到省略信息
****** 找到常见类型的重要信息的一些提示
1. 常见的反驳论证
    a. 反对的人会提供什么样的理由?
    b. 有没有研究和所说的研究相冲突?
    c. 有没有权威人士提供的反例~证词和观点被省略掉,或者反对的类比被省略?
2. 遗漏掉的定义
    如果关键词换个定义,论证是不是会不同?
3. 遗漏的价值观偏向或者视角
    a. 不同价值观是不是会产生不一样的处理方法?
    b. 与作者不同的价值观出发会产生怎样的结论?
4. 论证中所指的"事实"的来源
    a. "事实"的来源是什么?
    b. 事实断言是不是靠出色的研究或可靠的来源支撑?
5. 用来获得事实的程序细节
    a. 有多少人完成调查问卷?
    b. 调查的问题措辞?
    c. 调查对象有没有机会来提供不一样的答案
6. 收集或组织证据的其他方式
    a. 访谈得来的结果和书面问卷得来的结果有怎样的不同?
    b. 实验室会不会产生更丰富更可靠的结果?
7. 遗漏掉的或者不完整的数字~图表~表格或者数据
    a. 如果数据包含早期或后来的证据看起来会不会不一样?
    b. 作者有没有故意"拉长"数字让差距显得更大一些?
8. 省略的结果,不管是正面反面结果,短期长期结果,还是提倡和反对的结果
    a. 论证有没有遗漏提议的行动带来的重要的正面或反面的结果?代价是什么?好处又是什么?
    b. 需不需要知道行动对各个领域的影响: 政治~经济~社会~生物~精神~健康的或环境的?
9. 当为特殊的预测技巧进行辩护时省略掉预测的失败,或者预测的失误
    a. "通灵巫师",追问它们的预测不真实的概率有多少
    b. 需要知道权威人士预测失败的概率.  

** 考虑是否有负面效果
被提倡的行动的潜在负面效果:
    大部分行动有广泛的正面和负面影响,而支持者只说正面不说负面.我们要评价行动,就必须得找到潜在的负面影响
    - 谁掏钱?
    - 社会中谁没有受益?谁损失了?损失的人有什么话说?
    - 提议的行动对权力分配有什么影响?
    - 这个行动对健康的影响?
    - 这个行动怎么影响我们的人际关系?怎么影响我们与自然环境之间的关系?
    这个行动潜在长期的负面效果是什么?  
    eg. 建设一所面积大的新学校有什么可能的负面效果?
        - 增加的税负.
        - 房地产价值的影响.
        - 教育治疗的变化
        - 破坏环境

** 面对信息缺失的现实
面对信息缺少的现实.只要重要信息找不到就无法做出决断,也形成不了任何观点  

** 轮到你自己写时,可得吸取教训
省略信息难以避免,自己判断什么样的省略信息最重要.当省略信息能强烈影响读者对论证的立场,那么这个信息就非常重要.  
写作的建议:
    1. 回到你原来的研究当中,他们在争论的到底是什么关键点?
        eg. 2010奥斯卡最佳画面奖,你沉浸于顶尖评论家最喜欢的作品和为什么喜欢这些作品的争论中.意识到自己沉浸在这里,就可以发现自己
            原来忽略了其他优秀电影  
    2. 利用你生活当中的各色人等,尤其持有不同价值取向和世界观的人,问问他们需要什么信息才会接受你的结论  

*** 使用这个关键问题
一旦发现了论证遗漏了信息,那么去寻找这个信息.由于对缺少信息的不快,不断搜寻这个信息,或者同意这个推理,当且仅当论证比他的对手要好.  

****** 来,做做思维体操
****** ?关键问题:有什么重要信息被省略了?
这三群人相互之间在哪些方面还有区别?  
适量饮酒和过量饮酒有什么潜在的负面效果?记忆~婚姻满意度和工作表现  
这些结果在其他类型的研究有没有被发现?  
研究的参与对象怎么挑选的?比如,自愿参加和随机抽取的人的不同  
怎么样衡量喝酒的频率?这样的衡量准不准确?  

克隆器官的副作用?  
人们会不会不重视自己的身体?  
会不会导致滥用克隆人?会不会克隆出自己,让人口负担又加重一层?    
有没有发现没有一项研究在这里被引用.都全部是假设而已  

* 第12章 能得出哪些合理的结论
本章主要关于从单独一套理由中推断出多个备选结论  
发现了多个备选结论,就可以从中找出那个最符合你价值取向的  

****** ?关键问题:能得出什么合理的结论?

** 各种假设和多个结论
对理由的不同假设和不同解读会得出特殊的结论  
因为我们认知水平不同~参照体系不同~先验知识不同,取哪种假设看法也不一样.  

*** 二分式思维方法: 妨碍我们考虑多种可能性
二分思维方法: 用不是肯定就是否定的方式来思考问题的时候  
    可以通过限定条件,将各种结论放到具体语境来避免  
        1. 结论在什么时候是精确的?
        2. 结论在什么地方是精确的?
        3. 结论为什么或为了什么目的才是精确的?
一成不变的二分式思维极大地破坏了批判性思维  

** 两面还是多面
简单地回答"是"或"不是"就得出两个结论.但还有没有其他可能?是的,还有很多种可能!  

** 寻找多个结论
使用限定条件取寻找多个结论  
我们应当继续使用死刑,但是仅限于已经被判处终生监禁,而且杀害了监狱首位或者凡人  

** 某个条件下才合理的结论
if-clause 使用条件句来创造多种结论  

** 以解决问题为导向的可能结论
寻找这个潜在问题的不同解决方法就是这个论证可能得出的结论  
问题:
    我们该不该采取甲措施?  
    甲措施是不是可取?  
    掩盖的问题: 我们该怎样处理乙问题?  
出理由提出解决问题的方法 
不, 我们不需要关闭市中心的酒吧,相反,我们应该严格执行饮酒年龄的限制,对卖酒饮料给未成年人的网吧施加罚款  

** 让思维更加灵活
如果逻辑~事实~研究本身可以自圆其说,我们用请教老师来告诉我们应该持有的看法.  
逻辑和事实只能引导我们到一定地步,然后我们必须靠自己走完通向确定看法的剩余道路  
如何用逻辑和事实为我们提供帮助:
    寻找那些有可能存在的与我们逻辑和事实一致的各种结论  

** 不是所有的结论都生来平等
最值得相信的结论是那些对结论最具影响力的结论  

** 更多可能的结论,更多可能的自由选择

****** 来,做做思维体操
****** ?关键问题:能得出什么合理的结论?
