#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 对年轻人有什么忠告?

王老师用10年的从底层爬上来的血泪经验豪无保留的告诉你我的几条忠告。

如果你看不懂——那说明你认知能力不够。如果你能看懂，但是你做不到——那是你人性框架出了问题，好逸恶劳，理性抵抗不过安全，不可能跨越阶级从底层杀出仅此而已。

以下每一条——都事关你的命运，只要有一条你做不到，你就大概率会在未来被陷入到一个更大的困难中，并在几年后后悔——因为你会发现这几年你没有任何进步。而大部分人的人生其实都是当然后悔的时候就晚了。

第1——人必须要把自己长期的保持在一个中高风险的环境中，尤其是没钱的时候，绝对不能为了安全感去追求低风险。没钱的人追求低风险——不会有任何前途。

财富只回报风险，不回报努力、劳动和时间等等一切你以为值钱的东西。风险是最值钱的东西，因为它会激发你的潜力和带给你超额的回报。当然，如果失败了，也会带给你超人的痛苦，但是只要你不放弃，就有机会赢。

但是穷人避免风险——就会一无所有，因为他本来就一无所有。而大部分人从一开始就穷，却对风险没有任何忍受度。这注定了他们的命运。

第2——人必须要保持痛苦，绝对不能追求快乐。

追求快乐的人是没有任何前途的，有钱人、富二代可以追求快乐，虽然他也不会进步，但是有人给他承担成本。但是穷人追求快乐只会成为一个彻底的社会底层。痛苦在哲学上极高的价值，可以保持你的清醒和理性，让你不要忘乎所以。

快乐——使人毁灭。要时时刻刻警惕快乐。他是你人生最大的敌人。快乐是魔鬼的天使——而上帝派来的天使，是让你痛苦。

孟子说——生于忧患死于安乐。

第3——人必须要保持简单的生活方式。可用可不用的东西，一定不要用。可买可不买的东西，一定不要买。要把自己生活的环境始终保持在一个简单、必要、没有无用的东西环境中。

一个人只要进入复杂的物质环境中，就会失去奋斗的动力。而消费主义者的第一特征就是冲动消费，且会买很多自己根本用不上的东西——他们对生活的不方便，容忍度很低，但是对贫穷的容忍度，却很高。

尤其是很多女人，到了30岁，穿的都是名牌，用的都是高档货，但是一问，存款10万块。这样的人除了当捞女以外，不会有其他发财的路径了。

第4——一定要保持高额储蓄的习惯，一定不要超前消费。克服人性的虚荣心和投机心理。

只能用一年的收入买车，而且必须全款。克制自己的投机心理和虚荣心理。把所有的精力投入到个人能力的提升上，人才是最值得投资的，如果你自己都不值得投资，那没有任何事情是值得投资的。

永远不要相信不会花钱的人就不会赚钱，永远不要指望除了投资你自己以外的任何投资可以让你富有。因为其他任何投资都是别人做的局——而真正可以有钱的人，都是自己做局。

第5——一定要讲理，一定要学会思考别人为什么会这么想，到底有没有道理。如果真的没道理，那就坚持自己。如果真的比你更有道理，那就听人劝。

人有时候要听人劝吃饱饭，有时候要坚持自己，这个度很难把握——但是把握的关键在于，自己的判断力——而判断力高度依赖你自己的经验、智商、经历和你的长期目标。但无论如何，一定要讲理。

尤其是在你自己利益受损的情况下，也一定要讲理——这个世界上的绝大部分穷人，表面看都讲理，但其实一到自己哪怕是100块钱的利益受损，就变成泼妇了。这种人是没有任何前途的。高阶层的人是不会理他的。

讲理的关键就是自己的利益受损的时候——还能保持理性和讲客观的道理，能认清道理，这才是会被合作伙伴认可。

第6——一定要有自己的偶像，以自己的偶像的行为为标准要求自己。你想成为什么样的人，你就像什么样的人学习，绝对不要学别人。

你想成为富一代，你就向富一代学习。你想成为富二代，但是你父母没钱，那你想学富二代你就是傻逼。富一代去一线城市，你就去一线城市，富一代创业你就创业，富一代去互联网行业，你就去互联网行业，富一代做的不是关系生意，那你就不要做关系生意。

你做的事情是对是错——很简单——问问自己，如果我的偶像遇到这种情况会怎么做？如果你觉得他不会这么做，那就绝对不要做。

人必须要有偶像。偶像就是目标。偶像就是行为准则。没有偶像的人，是没有梦想的。梦想都是偶像带来的。

第7——一定要做很多自己情绪上不想做的事情——克服自己的幻觉、情绪、空想和道德偏好。

杨幂说“我已经把情绪戒了”。

真正成功的人，都是客观、理性和权衡利弊的，不会以自己个人的好恶和道德偏好评价任何人和事。那是吃瓜群众干的事——吃瓜群众70%月薪不到7000块钱。

很多事，只要不犯法，你就可以去做。哪怕自己不想做，也要刻意去做，这可以打开你的世界观，让你不再为低级的事情纠结。

第8——要强硬，要外向，要敢于表达自己，要敢于为自己的言行负责。

除了你自己以外，这个世界不会有任何人维护你的利益——包括你的父母和你的孩子。但是自己犯的错——自己的责任，必须要勇于承担。一个不敢承担责任的人，100%是一个社会底层的命运。

职场上的人，典型特征就是会甩锅，所以他们只能一辈子打工，为了要饭当一个没有人格的人。

很多人创业，自己都不敢自己投钱，拼了命的找父母和老公要钱，亏了算别人的，赚钱算自己的，这种人不可能成功。没有人会相信他。

简单吗？很简单。

难吗？极难。90%的人一辈子连这上面8条中的任何一条都做不到。所以他们只能像狗一样活着，到处占人便宜。成为一个泼妇，成为一个寄生虫，成为一个无法自食其力蝇营狗苟的人，在悔恨和麻木中虚度自己毫无价值的一生。
