* 猿猴的把戏
黑猩猩的生活则与群体中的其他成员交织在一起， 形成了一个严密的、 错综复杂的社会网络。 一只黑猩猩的任何一个举动都会在它的社会网络中对其他黑猩猩的生活产生影响， 不管其他黑猩猩愿不愿意， 喜不喜欢。

根本主题: 人性在社交层面展现更多
	1. 可以用成分收益分析法和博弈论去分析
	2. 由于环境,从祖先那遗传来的一些行为

** 第一章 电梯困境
电梯里大多数行为都不是理性思考的结果,而是针对这种场景的一种自发的~本能的反应.

*** 穴居人的遗产
个人空间就像一个看不见的肥皂泡一样， 每个人都随身携带着它。 这个肥皂泡的半径可大可小， 取决于他所处社会的个人规范或文化规范。 霍尔认为人类的个人空间可以等同于动物的领地； 个人空间被侵犯很容易引发攻击性反应， 这代表了一种试图捍卫个人领地的意图。

因为预感有危险而产生的焦虑对我们的身体健康会有损害，这种损害可以像身体受伤一样严重。
		
*** 战还是不战
当两只猕猴被关在一个小笼子里时，它们会想尽办法避免发生打斗。它们或小心翼翼地移动，或装作对对方无动于衷，还会抑制任何可能引发攻击的行为，这些对于解决笼中相处问题而言都是很好的短期策略。 

这些聪明个体的后代就从基因上遗传了允许他们在电梯里或在笼子里避免打斗的行为策略。
如果你是一只猕猴，发现自己与另一只猕猴同时被困在一个小笼子里，你就知道该做点什么了：露出你的牙齿，开始给对方理毛。如果你是人类中的一员，发现自己跟另一个陌生人一起搭乘电梯，从理论上说你可以跟猕猴做同样的事情（或对人类而言的同样的事）：微笑和闲聊。
然而，真正要做的时候，事情通常要比上述描写更复杂一点。

*** 电梯里的困境
目标分享是社会关系的一个重要方面。亲子关系、友谊或爱情都建立在一个共识上面，那就是两个人拥有同样的目标，愿意共同参与、一起行动去实现这个目标。这个西装男人的行为不是友谊或爱的举动，而是表达友好信号的一个重要步骤.

*** 猴子的把戏
男性在面对社会压力时表现出了一种“战斗还是逃跑”的反应：他们要么逃跑，以避开压力来源；要么留在原地进行战斗。另一方面，女性则“照顾他人做朋友”：她们留在原地，表现出友善行为，试图以此战胜敌人或化敌为友。

其中一只开始给另外一只理毛。不过，几秒钟之后她就停止劳作，立刻躺在对方面前，或把自己的腿、胳膊或屁股放在对方的眼前，要求回报。而另一只猴子呢，既然轮到自己，也就依样画葫芦，做了同样的事情：同样是给对方理毛几秒钟，接着就索要回报。

囚徒困境:
玩家1的第一步是合作，然后简单地重复玩家2在此之前的选择：如果玩家2合作，那么玩家1就合作；如果玩家2背叛，玩家1也会跟着背叛。
亲缘关系和支配关系

他更可能是一个情绪易感的人，很容易就体验到不安全感，因此他通过使用大量的“言语理毛行为”进行应对，试图讨好一个潜在的攻击者

** 第二章 痴迷权力和统治
无论是人类还是其他的灵长类,他们都不可救药地迷恋支配和统治,虽然他们不需要意识到这一点.
支配性深入人性的最深处,因此幻想没有支配性的社会关系是不现实的.

*** 新技术的老用途

人类处理社会关系有各种方式:面部表情,声音,触摸,理毛,拥抱,甚至扇耳光或者大拳头.
电子邮件的出现并没有改变这种社会关系,表现方式是沟通的不对称性:下级多,上级少.
这种不对称性不是时间的原因,而是支配结构的问题.

两只猩猩的理毛交流情景,上级A,下级B.
A正在做自己的事,B走近它,友善地微笑了好几次,接着开始给它理毛.
这可能带来回报:理毛~容忍,以及来自A的支持.
B手疼了后,停下来请求对方理毛.A并没有马上作出报答,而是若无其事.
B厌倦了等待,又继续给A理毛.过几分钟后再次停下来,A等了20秒,然后给B理毛--仅仅几秒钟,停下来等着B作出报答.
到某个时间点后,A终止对话,不做反应,直接走开.

猩猩的社会策略: 通过向强者谄媚提升社会地位,还是通过挑战强者权威和特权来实现这一目标.

*** 社会关系的问题与策略
在有限空间遇到不善的陌生人,是一种潜在的具有生命危险的情形.我们大脑倾向于做出适当的反应.
但是日常中我们遇到的大部分是熟人,我们建立了长期关系,从他们那里获得显而易见的好处.

社会关系可以是合作的和竞争的,可以是美好的和糟糕的.
但是都避不开利益冲突:人们以对自己有利的方式做事,但是这种方式会给他的同伴带来损失.
适用于任何关系: 亲子~手足~恋人~朋友和同事.
解决争端:不是每次都有效,可能对双方严重伤害,损害他们的关系,导致关系解体.同时要付出时间~精力~认知和情绪资源.
	- 武斗:最干脆打一架
	- 文斗:谈判,达成一致.
支配结构:文斗和武斗的代价,催生出了支配结构.聪明的支配者会好言安慰,或者是让渡一些利益.
	- 没有受伤的风险,没有时间~精力~认知或情绪资源的浪费.
	- 代价完全由从属者承担.

*** 人类和其他动物的支配关系
亲子关系:
	孩子很小的时候,大哭大闹就能获得支配地位.
	开始懂语言后,父母开始获得支配地位.随后几年内,孩子臣服于父母,因为啥也不会,这样最符合自己的利益.
	有些孩子用伤害自己来敲诈父母.
	支配地位的真正挑战开始于青春期.孩子开始用新的战术和父母争夺地盘.
	有些父母作出让步,不那么专断,但是仍然保持对孩子的支配性.
	有些孩子逆转了支配关系,开始发号施令.
	有些父母和孩子,余生吵个不停--或者不再说话.
手足关系:马太效应
	醍醐:两只雏鸟一只杀死另外一只
	般猎狗: 出生后开始厮杀
	鸟类: 老大吃最多,另外两只争剩饭
	猪: 高大又强壮的占据最多的前乳头.
	人类: 建立支配后
朋友的关系:
	两岁时,儿童开始竞争地位.
	年轻女孩喜欢用间接的竞争策略: 散布谣言.采取孤立~忽视和社会排斥的策略.破坏他人之间的结盟.
浪漫关系:
	最稳定的浪漫关系是一开始支配结构就明确的那种.
	伴侣的支配者决定所有的事情,从属者默许同意,扮演着支持性的角色.
	这种关系允许他们进行房屋和养育孩子的共同冒险,允许他们有机会专注于个人的事业而不必担心房间里的吵闹.
	婚姻稳定的秘密就在于,其中一个配偶愿意为这种稳定性付出不成比例的代价.
支配关系的结束:
	- 支配者或者双方失去对这段关系的兴趣,找寻新的关系
	- 支配者暴虐,从属者破釜沉舟,选择逃离.
支配关系的逆转:
	女仆成为女主人后把主人扫地出门.
	我们受制于自己的生存本能,也受制于周围其他人的生存本能.

*** 支配关系7x24小时
*** 支配结构的等级系统

*** 灵长类的支配结构

*** 鹰派策略和鸽派策略

*** 行为展示的模式

*** 输赢天注定?

** 第三章 我们都是黑手党
美国当代的裙带主义是一头另类的野兽,它仁慈而高贵,跟猿猴~世界各国的独裁者或欧洲人使用的裙带主义绝不相同

*** 意大利式推荐

*** 竞赛和学霸

*** 裙带主义的本质

*** 好的,坏的和丑的

*** 黑手党家族的价值观

** 第四章 出人头地
不管你是一只猿猴还是一个人,在进入新的圈子时,必须跟新圈子的陌生人发展关系,努力获得他们的支持.
当周围没有亲戚能帮你时,要想出人头地,无法靠裙带,而要靠政治.

*** 自食其力

*** 人类的故事

*** 马基雅维利式的策略家

*** 猴子的故事

*** 出人头地的策略模型

*** 灵长类的政治

*** 灵长类策略的社会应用

** 第五章 明里合作,暗中竞争
人们选择跟其他人合作时喜欢身处聚光灯下,以便每个人都能看到,都来欣赏,并希望每个人都能奖赏自己的行为.
相反,当人们选择背叛,选择伤害而不是帮助别人的时候,他们更喜欢暗箱操作.

*** 咖啡~茶和人性

*** 聚光灯下的利他者

*** 对背叛者的惩罚

*** 暗中竞争

*** 审稿人变为竞争者

*** 吸血鬼与狼人之战

** 第六章 爱情经济学和爱情进化生物学
对于配偶结合而言,最不可思议的心理适应机制是浪漫之爱.
他在人类的心灵中创造出一种对所爱之人的渴望和心理依恋,这与一个幼小的孩子和母亲之间存在的情感关系并无二致.

*** 比佛利山庄出了什么事?

*** 爱情经济学

*** 爱情进化生物学

*** 配偶关系的解体

*** 爱情的历史

** 第七章 联系测试
人们愿意承受来自好朋友的侮辱,但不愿承受来自陌生人的戏谑.
因此,对另一个体施加不利影响,能够给你提供可靠的信息,让你明白你跟他的关系到底怎么样.

*** 狒狒对承诺问题的解决之道

*** 联系测试的逻辑和累赘原理

*** 戳眼球~性和其他怪异的社会联系测试

*** 承诺问题能解决吗?

** 第八章 同伴选择的生物市场
群体竞争在人类社会性进化过程中可能扮演着跟群体合作同等重要的角色,
青睐自私~富有竞争性和攻击性个体的同伴可能代表了一种强大的选择力量,这种力量跟促进利他和亲社会行为的力量之间相互对抗.

*** 寻找正确的搭档

*** 人类择偶市场

*** 生物市场

*** 动物择偶市场

*** 性事以外的市场

*** 物种之间的交易:互助市场

** 第九章 人类社会行为的进化
对于一个来自火星的人类学家来说,所有的人类看起来都以相仿的方式进行交往,跟木星居民表现出的行为模式迥然不同.

*** 进化的行李

*** 人类中心主义和自由意志

*** 挤在我们脑袋里的算法

*** 情绪:启动器和程序协调器

*** 认知和行为算法

*** 人类社会行为的适应性和与其他动物的协同进化

*** 人类社会行为的种系史

*** 最近的过去

