#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 24th PILLAGE FROM ALL SOURCES
#+begin_verse
'I'll never be ashamed to quote a bad writer with a good saying.' —SENECA,
  ON TRANQUILITY OF MIND,
  11.
8 ne of the striking things about Seneca's letters and essays is how often he quotes the philosopher Epicurus.
Why is that strange?
Because Stoicism and Epicureanism are supposed to be diametrically opposed philosophies!
(In reality the differences while significant tend to be overblown.
) But this is true to form for Seneca.
He was looking for wisdom,
  period.
It didn't matter where it came from.
This is something that a lot of fundamentalists—in religion,
  philosophy,
  anything—seem to miss.
Who cares whether some bit of wisdom is from a Stoic,
  who cares whether it perfectly jibes with Stoicism?
What matters is whether it makes your life better,
  whether it makes you better.
What wisdom or help would you be able to find today if you stopped caring about affiliations and reputations?
How much more could you see if you just focused on merit?
T
#+end_verse