#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 27th LAUGH, OR CRY
#+begin_verse
'Heraclitus would shed tears whenever he went out in public— Democritus laughed. One saw the whole as a parade of miseries,
  the other of follies. And so,
  we should take a lighter view of things and bear them with an easy spirit,
  for it is more human to laugh at life than to lament it.' —SENECA,
  ON TRANQUILITY OF MIND,
  15.
2 s this observation the origin of that famous expression about frustrating news:
  'I don't know whether to laugh or cry?' The Stoics saw little purpose in getting angry or sad about things that are indifferent to our feelings.
Especially when those feelings end up making us feel worse.
It's also another bit of evidence that the Stoics were hardly some depressing,
  bitter group of old men.
Even when things were really bad,
  when the world made them want to weep in despair or rage,
  they chose to laugh about it.
Like Democritus,
  we can make that same choice.
There is more humor than hate to be found in just about every situation.
And at least humor is productive—making things less heavy,
  not more so.
E
#+end_verse