#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 4th NO BLAME, JUST FOCUS
#+begin_verse
'You must stop blaming God,
  and not blame any person. You must completely control your desire and shift your avoidance to what lies within your reasoned choice. You must no longer feel anger,
  resentment,
  envy,
  or regret.' —EPICTETUS,
  DISCOURSES,
  3.
22.
13 elson Mandela was imprisoned for resistance to the brutal apartheid regime in South Africa for twenty-seven years.
For eighteen of those years,
  he had a bucket for a toilet,
  a hard cot in a small cell,
  and once a year he was allowed a single visitor—for thirty minutes.
It was vicious treatment meant to isolate and break down the prisoners.
And yet,
  in spite of that,
  Mandela became a figure of dignity within the prison.
Though he was deprived of many things,
  he still found creative ways to assert his will.
As one of his fellow prisoners,
  Neville Alexander,
  explained on Frontline,
  'He [Mandela] always made the point,
  if they say you must run,
  insist on walking. If they say you must walk fast,
  insist on walking slowly. That was the whole point. We are going to set the terms.' He pretended to jump rope and shadowboxed to stay in shape.
He held his head higher than other prisoners,
  encouraged them when times got tough,
  and always retained his sense of self-assurance.
That self-assurance is yours to claim as well.
No matter what happens today,
  no matter where you find yourself,
  shift to what lies within your reasoned choices.
Ignore,
  as best you can,
  the emotions that pop up,
  which would be so easy to distract yourself with.
Don't get emotional— get focused.
R
#+end_verse