#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 25th RESPECT THE PAST, BUT BE OPEN TO THE FUTURE
#+begin_verse
'Won't you be walking in your predecessors' footsteps? I surely will use the older path,
  but if I find a shorter and smoother way,
  I'll blaze a trail there. The ones who pioneered these paths aren't our masters,
  but our guides. Truth stands open to everyone,
  it hasn't been monopolized.' —SENECA,
  MORAL LETTERS,
  33.
11 raditions are often time-tested best practices for doing something.
But remember that today's conservative ideas were once controversial,
  cutting-edge,
  and innovative.
This is why we can't be afraid to experiment with new ideas.
In Seneca's case,
  he might be embracing some new philosophical insight that improves on the writing of Zeno or Cleanthes.
In our case,
  perhaps a breakthrough in psychology improves on the writing of Seneca or Marcus Aurelius.
Or perhaps we have a breakthrough of our own.
If these ideas are true and better,
  embrace them—use them.
You don't need to be a prisoner of dead old men who stopped learning two thousand years ago.
Z
#+end_verse