#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 30th WHEN YOU FEEL LAZY
#+begin_verse
'Anything that must yet be done,
  virtue can do with courage and promptness. For anyone would call it a sign of foolishness for one to undertake a task with a lazy and begrudging spirit,
  or to push the body in one direction and the mind in another,
  to be torn apart by wildly divergent impulses.' —SENECA,
  MORAL LETTERS,
  31.
b–32 f you start something and right away feel yourself getting lazy and irritated,
  first ask yourself:
  Why am I doing this?
If it really is a necessity,
  ask yourself:
  What's behind my reluctance?
Fear?
Spite?
Fatigue?
Don't forge ahead hoping that someone will come along and relieve you of this task you don't want to do.
Or that someone else will suddenly explain why what you're doing matters.
Don't be the person who says yes with their mouth but no with their actions.
Steve Jobs told BusinessWeek in 2005,
  only midway through Apple's stunning rise to becoming one of the world's most valuable companies:
  'Quality is much better than quantity. . . . One home run is much better than two doubles.'E
#+end_verse