#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 22nd DON’T SWEAT THE SMALL STUFF
#+begin_verse
'It is essential for you to remember that the attention you give to any action should be in due proportion to its worth,
  for then you won't tire and give up,
  if you aren't busying yourself with lesser things beyond what should be allowed.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
32b n 1997,
  a psychotherapist named Richard Carlson published a book called Don't Sweat the Small Stuff .
.
.
and It's All Small Stuff.
It quickly became one of the fastest-selling books of all time and spent years on the bestseller lists,
  ultimately selling millions of copies in many languages.
Whether you read the book or not,
  Carlson's pithy articulation of this timeless idea is worth remembering.
Even Cornelius Fronto,
  Marcus Aurelius's rhetoric teacher,
  would have thought it a superior way of expressing the wisdom his student attempted in the quote above.
They both say the same thing:
  don't spend your time (the most valuable and least renewable of all your resources) on the things that don't matter.
What about the things that don't matter but you're absolutely obligated to do?
Well,
  spend as little time and worry on them as possible.
If you give things more time and energy than they deserve,
  they're no longer lesser things.
You've made them important by the life you've spent on them.
And sadly,
  you've made the important things—your family,
  your health,
  your true commitments—less so as a result of what you've stolen from them.
I
#+end_verse