#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 23rd IT’S IN YOUR SELF-INTEREST
#+begin_verse
'Therefore,
  explain why a wise person shouldn't get drunk—not with words,
  but by the facts of its ugliness and offensiveness. It's most easy to prove that so-called pleasures,
  when they go beyond proper measure,
  are but punishments.' —SENECA,
  MORAL LETTERS,
  83.
27 s there a less effective technique to persuading people to do something than haranguing them?
Is there anything that turns people off more than abstract notions?
That's why the Stoics don't say,
  'Stop doing this,
  it's a sin.' Instead they say,
  'Don't do this because it will make you miserable.' They don't say,
  'Pleasure isn't pleasurable.' They say,
  'Endless pleasure becomes its own form of punishment.' Their methods of persuasion hew the line in The 48 Laws of Power:
  'Appeal to People's Self-Interest Never to Their Mercy or Gratitude.' If you find yourself trying to persuade someone to change or do something differently,
  remember what an effective lever self-interest is.
It's not that this or that is bad,
  it's that it is in their best interest to do it a different way.
And show them—don't moralize.
And what happens when you apply this way of thinking to your own behavior?
O
#+end_verse