#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 29th WANT NOTHING = HAVE EVERYTHING
#+begin_verse
'No person has the power to have everything they want,
  but it is in their power not to want what they don't have,
  and to cheerfully put to good use what they do have.' —SENECA,
  MORAL LETTERS,
  123.
3 s there a person so rich that there is literally nothing they can't afford?
Surely there isn't.
Even the richest people regularly fail in their attempts to buy elections,
  to purchase respect,
  class,
  love,
  and any number of other things that are not for sale.
If obscene wealth will never get you everything you want,
  is that the end of it?
Or is there another way to solve for that equation?
To the Stoics,
  there is:
  by changing what it is that you want.
By changing how you think,
  you'll manage to get it.
John D.
Rockefeller,
  who was as rich as they come,
  believed that 'a man's wealth must be determined by the relation of his desires and expenditures to his income. If he feels rich on $10 and has everything he desires,
  he really is rich.' Today,
  you could try to increase your wealth,
  or you could take a shortcut and just want less.
I
#+end_verse