#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 7th PRAGMATIC AND PRINCIPLED
#+begin_verse
'Wherever a person can live,
  there one can also live well;
  life is also in the demands of court,
  there too one can live well.' —MARCUS AURELIUS,
  MEDITATIONS,
  5.
16 illiam Lee Miller,
  in his unique 'ethical biography' of Abraham Lincoln,
  makes an important point about this famous president:
  our deification of the man makes a point to pretend he wasn't a politician. We focus on his humble beginnings,
  his self-education,
  his beautiful speeches. But we gloss over his job,
  which was politics. That misses what was so truly impressive about him:
  Lincoln was all the things he was—compassionate,
  deliberate,
  fair,
  open-minded,
  and purposeful—while being a politician. He was what we admire in a profession we believe to be filled exclusively with the opposite of that type of person. Principles and pragmatism are not at odds. Whether you live in the snake pit of Washington,
  D.C.,
  work among the materialism of Wall Street,
  or grew up in a closed-minded small town,
  you can live well. Plenty of others have.H
#+end_verse