#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 31st CONSIDER YOUR FAILINGS TOO
#+begin_verse
'Whenever you take offense at someone's wrongdoing,
  immediately turn to your own similar failings,
  such as seeing money as good,
  or pleasure,
  or a little fame—whatever form it takes. By thinking on this,
  you'll quickly forget your anger,
  considering also what compels them—for what else could they do? Or,
  if you are able,
  remove their compulsion.' —MARCUS AURELIUS,
  MEDITATIONS,
  10.
30 arlier we were reminded of Socrates's tolerant belief that 'no one does wrong on purpose.' The clearest proof of that hypothesis?
All the times we did wrong without malice or intention.
Remember them?
The time you were rude because you hadn't slept in two days.
The time you acted on bad information.
The time you got carried away,
  forgot,
  didn't understand.
The list goes on and on.
This is why it is so important not to write people off or brand them as enemies.
Be as forgiving of them as you are of yourself.
Cut them the same slack you would for yourself so that you can continue to work with them and make use of their talents.
SEPTEMBER FORTITUDE AND RESILIENCEC
#+end_verse