#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 9th STICK WITH JUST THE FACTS
#+begin_verse
'Don't tell yourself anything more than what the initial impressions report. It's been reported to you that someone is speaking badly about you. This is the report—the report wasn't that you've been harmed. I see that my son is sick—but not that his life is at risk. So always stay within your first impressions,
  and don't add to them in your head—this way nothing can happen to you.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
49 t first,
  this can seem like the opposite of everything you've been taught.
Don't we cultivate our minds and critical thinking skills precisely so we don't simply accept things at face value?
Yes,
  most of the time.
But sometimes this approach can be counterproductive.
What a philosopher also has is the ability,
  as Nietzsche put it,
  'to stop courageously,
  at the surface' and see things in plain,
  objective form. Nothing more,
  nothing less. Yes,
  Stoics were 'superficial,
  ' he said,
  'out of profundity.
' Today,
  while other people are getting carried away,
  that's what you're going to practice. A kind of straightforward pragmatism— seeing things as their initial impressions make them.P
#+end_verse