#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 10th PERFECTION IS THE ENEMY OF ACTION
#+begin_verse
'We don't abandon our pursuits because we despair of ever perfecting them.' —EPICTETUS,
  DISCOURSES,
  1.
2.
37b sychologists speak of cognitive distortions—exaggerated thinking patterns that have a destructive impact on the life of the patient.
One of the most common is known as all-or-nothing thinking (also referred to as splitting).
Examples of this include thoughts like:
  If you're not with me,
  you're against me.
So-and-so is all good/bad.
Because this wasn't a complete success,
  it is a total failure.
This sort of extreme thinking is associated with depression and frustration.
How could it not be?
Perfectionism rarely begets perfection —only disappointment.
Pragmatism has no such hang-ups.
It'll take what it can get.
That's what Epictetus is reminding us.
We're never going to be perfect—if there is even such a thing.
We're human,
  after all.
Our pursuits should be
#+end_verse