#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* August 18th ONLY FOOLS RUSH IN
#+begin_verse
'A good person is invincible,
  for they don't rush into contests in which they aren't the strongest. If you want their property,
  take it—take also their staff,
  profession,
  and body. But you will never compel what they set out for,
  nor trap them in what they would avoid. For the only contest the good person enters is that of their own reasoned choice. How can such a person not be invincible?' —EPICTETUS,
  DISCOURSES,
  3.
6.
5–7 ne of the most fundamental principles of martial arts is that strength should not go against strength.
That is:
  don't try to beat your opponent where they are strongest.
But that's exactly what we do when we try to undertake some impossible task we haven't bothered to think through.
Or we let someone put us on the spot.
Or we say yes to everything that comes our way.
Some people think that 'choosing your battles' is weak or calculating. How could reducing the amount of times we fail or minimizing the number of needless injuries inflicted upon us be weak? How is that a bad thing? As the saying goes,
  discretion is the better part of valor. The Stoics call it reasoned choice. That means be reasonable! Think hard before choosing,
  and make yourself unbeatable.T
#+end_verse