#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* aimed at progress, however little that it’s possible for us to make.August 11th NO TIME FOR THEORIES, JUST RESULTS
#+begin_verse
'When the problem arose for us whether habit or theory was better for getting virtue—if by theory is meant what teaches us correct conduct,
  and by habit we mean being accustomed to act according to this theory—Musonius thought habit to be more effective.' —MUSONIUS RUFUS,
  LECTURES,
  5.
17.
31–32,
  5.
19.
1–2 As Hamlet says,
  'There are more things in heaven and earth,
  Horatio,
  Than are dreamt of in your philosophy.' There is no time to chop logic over whether our theories are correct.
We're dealing with the real world here.
What matters is how you're going to deal with this situation right in front of you and whether you're going to be able to move past it and onto the next one.
That's not saying that anything goes—but we can't forget that although theories are clean and simple,
  situations rarely are.
O
#+end_verse