#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 20th MADE FOR JUSTICE
#+begin_verse
'The unjust person acts against the gods. For insofar as the nature of the universe made rational creatures for the sake of each other,
  with an eye toward mutual benefit based on true value and never for harm,
  anyone breaking nature's will obviously acts against the oldest of gods.' —MARCUS AURELIUS,
  MEDITATIONS,
  9.
1.
1 e say of the most heinous acts that they are crimes against nature.
We consider certain things to be an affront against humanity,
  saying,
  'This violates everything we hold dear.' However much we differ in religion,
  upbringing,
  politics,
  class,
  or gender,
  we can come together in agreement there.
Why?
Because our sense of justice goes marrow deep.
We don't like it when people cut in line;
  we don't like freeloaders;
  we pass laws that protect the defenseless;
  and we pay our taxes,
  agreeing,
  in part,
  to redistribute our wealth to those in need.
At the same time,
  if we think we can get away with it,
  we might try to cheat or bend the rules.
To paraphrase Bill Walsh,
  when left to our own devices,
  many of us individuals seek lower ground like water.
The key,
  then,
  is to support our natural inclination to justice with strong boundaries and strong commitments—to embrace,
  as Lincoln urged a divided,
  angry nation to do,
  'the better angels of our nature.'I
#+end_verse