#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 10th LOVE THE HUMBLE ART
#+begin_verse
'Love the humble art you have learned,
  and take rest in it. Pass through the remainder of your days as one who wholeheartedly entrusts all possessions to the gods,
  making yourself neither a tyrant nor a slave to any person.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
31 top by a comedy club any weekend night in New York or Los Angeles and you're likely to find some of the world's biggest and most commercially successful comedians in there,
  workshopping their craft for just a handful of people.
Though they make a fortune in movies or on the road,
  there they are,
  practicing the most basic form of their art.
If you ask any of them:
  'Why are you doing this? Why do you still perform?' The answer is usually:
  'Because I'm good at it. Because I love it. Because I want to get better. Because I thrive on connecting with an audience. Because I just can't not do it.' It's not work for them to get up on stage at Carolines or the Comedy Cellar at 1 a.
m.
It's invigorating.
They don't have to do it.
They're free,
  and they choose this.
Whatever humble art you practice:
  Are you sure you're making time for it?
Are you loving what you do enough to make the time?
Can you trust that if you put in the effort,
  the rest will take care of itself?
Because it will.
Love the craft,
  be a craftsman.
T
#+end_verse