#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 11th THE START-UP OF YOU
#+begin_verse
'But what does Socrates say? 'Just as one person delights in improving his farm,
  and another his horse,
  so I delight in attending to my own improvement day by day.
'' —EPICTETUS,
  DISCOURSES,
  3.
5.
14 he rage these days is to start your own company—to be an entrepreneur.
There is no question,
  building a business from scratch can be an immensely rewarding pursuit.
It's why people put their whole lives into doing it,
  working countless hours and taking countless risks.
But shouldn't we be just as invested in building ourselves as we would be to any company?
Like a start-up,
  we begin as just an idea:
  we're incubated,
  put out into the world where we develop slowly,
  and then,
  over time,
  we accumulate partners,
  employees,
  customers,
  investors,
  and wealth.
Is it really so strange to treat your own life as seriously as you might treat an idea for a business?
Which one really is the matter of life and death?
S
#+end_verse