#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 1st DO YOUR JOB
#+begin_verse
'Whatever anyone does or says,
  for my part I'm bound to the good. In the same way an emerald or gold or purple might always proclaim:
  'whatever anyone does or says,
  I must be what I am and show my true colors.
'' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
15 he Stoics believed that every person,
  animal,
  and thing has a purpose or a place in nature.
Even in ancient Greek and Roman times,
  they vaguely understood that the world was composed of millions of tiny atoms.
It was this idea—this sense of an interconnected cosmos— that underpinned their sense that every person and every action was part of a larger system.
Everyone had a job—a specific duty.
Even people who did bad things—they were doing their job of being evil because evil is a part of life.
The most critical part of this system was the belief that you,
  the student who has sought out Stoicism,
  have the most important job:
  to be good!
To be wise.
'To remain the person that philosophy wished to make us.' Do your job today.
Whatever happens,
  whatever other people's jobs happen to be,
  do yours.
Be good.
W
#+end_verse