#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 5th NO ONE SAID IT’D BE EASY
#+begin_verse
'Good people will do what they find honorable to do,
  even if it requires hard work;
  they'll do it even if it causes them injury;
  they'll do it even if it will bring danger. Again,
  they won't do what they find base,
  even if it brings wealth,
  pleasure,
  or power. Nothing will deter them from what is honorable,
  and nothing will lure them into what is base.' —SENECA,
  MORAL LETTERS,
  76.
18 f doing good was easy,
  everyone would do it.
(And if doing bad wasn't tempting or attractive,
  nobody would do it.
) The same goes for your duty.
If anyone could do it,
  it would have been assigned to someone else.
But instead it was assigned to you.
Thankfully,
  you're not like everyone.
You're not afraid of doing what is hard.
You can resist superficially attractive rewards.
Can't you?
I
#+end_verse