#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 3rd TURN HAVE TO INTO GET TO
#+begin_verse
'The task of a philosopher:
  we should bring our will into harmony with whatever happens,
  so that nothing happens against our will and nothing that we wish for fails to happen.' —EPICTETUS,
  DISCOURSES,
  2.
14.
7 long To-Do list seems intimidating and burdensome—all these things we have to do in the course of a day or a week.
But a Get To Do list sounds like a privilege—all the things we're excited about the opportunity to experience.
This isn't just semantic playing.
It is a central facet of the philosopher's worldview.
Today,
  don't try to impose your will on the world.
Instead see yourself as fortunate to receive and respond to the will in the world.
Stuck in traffic?
A few wonderful minutes to relax and sit.
Your car broke down after idling for so long?
Ah,
  what a nice nudge to take a long walk the rest of the way.
A swerving car driven by a distracted,
  cellphone-wielding idiot nearly hit you as you were walking and soaked you head to toe with muddy water?
What a reminder about how precarious our existence is and how silly it is to get upset about something as trivial as being late or having trouble with your commute!
Kidding aside,
  it might not seem like it makes a big difference to see life as something you have to do versus get to do,
  but there is.
A huge,
  magnificent difference.
T
#+end_verse