#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 2nd ON DUTY AND CIRCUMSTANCE
#+begin_verse
'Never shirk the proper dispatch of your duty,
  no matter if you are freezing or hot,
  groggy or well-rested,
  vilified or praised,
  not even if dying or pressed by other demands. Even dying is one of the important assignments of life and,
  in this as in all else,
  make the most of your resources to do well the duty at hand.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
2 ill this make me rich?
Will people be impressed?
How hard do I need to try?
How long will this take?
What's in it for me?
Should I do this other thing instead?
These are the questions we ask ourselves amid the day's opportunities and obligations.
Marcus Aurelius had many responsibilities,
  as those who hold executive power do.
He judged cases,
  heard appeals,
  sent troops into battle,
  appointed administrators,
  approved budgets.
A lot rode on his choices and actions.
Should he do this or that?
What about this concern or that concern?
When would he get to enjoy himself?
The simple reminder above was a way to cut through the Gordian knot of incentives,
  complaints,
  fears,
  and competing interests.
It's what we must use to decide what to do in each and every phase of life.
Morality can be complicated—but the right thing is usually clear and intuitive enough to feel in our gut.
Our duty is rarely easy,
  but it is important.
It's also usually the harder choice.
But we must do it.
A
#+end_verse