#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 19th FORGIVE THEM BECAUSE THEY DON’T KNOW
#+begin_verse
'As Plato said,
  every soul is deprived of truth against its will. The same holds true for justice,
  self-control,
  goodwill to others,
  and every similar virtue. It's essential to constantly keep this in your mind,
  for it will make you more gentle to all.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
63 s he wound his way up Via Dolorosa to the top of Calvary Hill,
  Jesus (or Christus as he would have been known to Seneca and other Roman contemporaries) had suffered immensely.
He'd been beaten,
  flogged,
  stabbed,
  forced to bear his own cross,
  and was set to be crucified on it next to two common criminals.
There he watched the soldiers roll dice to see who would get to keep his clothes,
  listened as the people sneered and taunted him.
Whatever your religious inclinations,
  the words that Jesus spoke next —considering they came as he was subjected to unimaginable human suffering—send chills down your spine.
Jesus looked upward and said simply,
  'Father,
  forgive them,
  for they know not what they do.' That is the same truth that Plato spoke centuries earlier and that Marcus spoke almost two centuries after Jesus;
  other Christians must have spoken this truth as they were cruelly executed by the Romans under Marcus's reign:
  Forgive them;
  they are deprived of truth.
They wouldn't do this if they weren't.
Use this knowledge to be gentle and gracious.
W
#+end_verse