#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 21st MADE FOR WORKING TOGETHER
#+begin_verse
'Whenever you have trouble getting up in the morning,
  remind yourself that you've been made by nature for the purpose of working with others,
  whereas even unthinking animals share sleeping. And it's our own natural purpose that is more fitting and more satisfying.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
12 f a dog spends all day in bed—your bed,
  most likely—that's fine.
It's just being a dog.
It doesn't have anywhere to be,
  no other obligation other than being itself.
According to the Stoics,
  we humans have a higher obligation—not to the gods but to each other.
What gets us out of bed each morning—even when we fight it like Marcus did—is praxeis koinonikas apodidonai (to render works held in common).
Civilization and country are great projects we build together and have been building together with our ancestors for millennia.
We are made for cooperation (synergia) with each other.
So if you need an extra boost to get out of bed this morning,
  if you need something more than caffeine can offer,
  use this.
People are depending on you.
Your purpose is to help us render this great work together.
And we're waiting and excited for you to show up.
Y
#+end_verse