#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 7th OUR DUTY TO LEARN
#+begin_verse
'This is what you should teach me,
  how to be like Odysseus— how to love my country,
  wife and father,
  and how,
  even after suffering shipwreck,
  I might keep sailing on course to those honorable ends.' —SENECA,
  MORAL LETTERS,
  88.
7b any schoolteachers teach The Odyssey all wrong.
They teach the dates,
  they debate whether Homer was really the author or not,
  whether he was blind,
  they explain the oral tradition,
  they tell students what a Cyclops is or how the Trojan Horse worked.
Seneca's advice to someone studying the classics is to forget all that.
The dates,
  the names,
  the places—they hardly matter.
What matters is the moral.
If you got everything else wrong from The Odyssey,
  but you left understanding the importance of perseverance,
  the dangers of hubris,
  the risks of temptation and distraction?
Then you really learned something.
We're not trying to ace tests or impress teachers.
We are reading and studying to live,
  to be good human beings—always and forever.
'C
#+end_verse