#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 29th A CURE FOR THE SELF
#+begin_verse
'The person who has practiced philosophy as a cure for the self becomes great of soul,
  filled with confidence,
  invincible—and greater as you draw near.' SENECA,
  MORAL LETTERS,
  111.
2 hat is 'a cure for the self'? Perhaps Seneca means that,
  through nature and nurture,
  we develop a unique set of characteristics— some positive and some negative. When those negative characteristics begin to have consequences in our lives,
  some of us turn to therapy,
  psychoanalysis,
  or the help of a support group. The point? To cure certain selfish,
  destructive parts of ourselves. But of all the avenues for curing our negative characteristics,
  philosophy has existed the longest and helped the most people. It is concerned not just with mitigating the effects of a mental illness or a neurosis,
  but it is designed to encourage human flourishing. It's designed to help you live the Good Life. Don't you deserve to flourish? Wouldn't you like to be great of soul,
  filled with confidence,
  and invincible to external events? Wouldn't you like to be like the proverbial onion,
  packed with layers of greatness? Then practice your philosophy.W
#+end_verse