#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 28th CHECK YOUR PRIVILEGE
#+begin_verse
'Some people are sharp and others dull;
  some are raised in a better environment,
  others in worse,
  the latter,
  having inferior habits and nurture,
  will require more by way of proof and careful instruction to master these teachings and to be formed by them—in the same way that bodies in a bad state must be given a great deal of care when perfect health is sought.' —MUSONIUS RUFUS,
  LECTURES,
  1.
1.
33–1.
3.
1–3.
t the end of a frustrating exchange,
  you might find yourself thinking,
  Ugh,
  this person is such an idiot.
Or asking,
  Why can't they just do things right?
But not everyone has had the advantages that you've had.
That's not to say that your own life has been easy—you just had a head start over some people.
That's why it is our duty to understand and be patient with others.
Philosophy is spiritual formation,
  care of the soul.
Some need more care than others,
  just as some have a better metabolism or were born taller than others.
The more forgiving and tolerant you can be of others —the more you can be aware of your various privileges and advantages —the more helpful and patient you will be.
W
#+end_verse