#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* July 25th WHAT’S ON YOUR TOMBSTONE
#+begin_verse
'When you see someone often flashing their rank or position,
  or someone whose name is often bandied about in public,
  don't be envious;
  such things are bought at the expense of life. . . . Some die on the first rungs of the ladder of success,
  others before they can reach the top,
  and the few that make it to the top of their ambition through a thousand indignities realize at the end it's only for an inscription on their gravestone.' —SENECA,
  ON THE BREVITY OF LIFE,
  20 ometimes our professional commitments can become an end unto themselves.
A politician might justify the neglect of his family for his office,
  or a writer might believe her 'genius' excuses antisocial or selfish behavior. Anyone with some perspective can see that,
  in fact,
  the politician is really just in love with fame,
  and the writer enjoys being condescending and feeling superior. Workaholics always make excuses for their selfishness. While these attitudes can lead to impressive accomplishments,
  their cost is rarely justified. The ability to work hard and long is admirable. But you are a human being,
  not a human doing. Seneca points out that we're not animals. 'Is it really so pleasant to die in harness?
' he asked. Aleksandr Solzhenitsyn put it better:
  'Work is what horses die of.
Everybody should know that.
'H
#+end_verse