#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 9th NOTHING TO FEAR BUT FEAR ITSELF
#+begin_verse
'But there is no reason to live and no limit to our miseries if we let our fears predominate.' —SENECA,
  MORAL LETTERS,
  13.
12b n the early days of what would become known as the Great Depression,
  a new president named Franklin Delano Roosevelt was sworn in and gave his first inaugural address.
As the last president to hold office before the Twentieth Amendment was ratified,
  FDR wasn't able to take office until March—meaning that the country had been without strong leadership for months.
Panic was in the air,
  banks were failing,
  and people were scared.
You've probably heard the 'nothing to fear but fear itself' sound bite that FDR gave in that famous speech,
  but the full line is worth reading because it applies to many difficult things we face in life:
  'Let me assert my firm belief that the only thing we have to fear is fear itself—nameless,
  unreasoning,
  unjustified terror which paralyzes needed efforts to convert retreat into advance.
' The Stoics knew that fear was to be feared because of the miseries it creates. The things we fear pale in comparison to the damage we do to ourselves and others when we unthinkingly scramble to avoid them. An economic depression is bad;
  a panic is worse. A tough situation isn't helped by terror—it only makes things harder. And that's why we must resist it and reject it if we wish to turn this situation around.W
#+end_verse