#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 14th A DIFFERENT WAY TO PRAY
#+begin_verse
'Try praying differently,
  and see what happens:
  Instead of asking for 'a way to sleep with her,
  ' try asking for 'a way to stop desiring to sleep with her.
' Instead of 'a way to get rid of him,
  ' try asking for 'a way to not crave his demise.
' Instead of 'a way to not lose my child,
  ' try asking for 'a way to lose my fear of it.
'' —MARCUS AURELIUS,
  MEDITATIONS,
  9.
40.
(6) rayer has a religious connotation,
  but in life we all find ourselves hoping and asking for things.
In a tough situation,
  we might silently ask for help;
  or,
  after a tough break,
  for a second chance from above;
  during a sports game,
  we might sit on the edge of our seat wishing for some outcome.
'C'mon,
  c'mon,
  c'mon,
  ' we say.
'Please . . .' Even if it is to no one in particular,
  we're still praying.
Yet it's so revealing in these moments,
  when we're privately,
  powerfully yearning for something,
  just how nakedly selfish our requests usually are.
We want divine intervention so that our lives will magically be easier.
But what about asking for fortitude and strength so you can do what you need to do?
What if you sought clarity on what you do control,
  what is already within your power?
You might find your prayers have already been answered.
A
#+end_verse