#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 23rd THE MOST SECURE FORTRESS
#+begin_verse
'Remember that your ruling reason becomes unconquerable when it rallies and relies on itself,
  so that it won't do anything contrary to its own will,
  even if its position is irrational. How much more unconquerable if its judgments are careful and made rationally? Therefore,
  the mind freed from passions is an impenetrable fortress—a person has no more secure place of refuge for all time. —MARCUS AURELIUS,
  MEDITATIONS,
  8.48 ruce Lee once made an interesting claim:
  'I fear not the man who has practiced ten thousand kicks once,
  ' he said,
  'but I fear the man who has practiced one kick ten thousand times.
' When we repeat an action so often it becomes unconscious behavior,
  we can default to it without thinking. Training in the martial arts or combat is a deeply thoughtful study of movement. We sometimes think of soldiers as automatons,
  but what they've actually built is a steady pattern of unconscious behaviors. Any of us can build these. When Marcus says that a mind can get to a place where 'it won't do anything contrary to its own will,
  even if its position is irrational,
  ' what he means is that proper training can change your default habits. Train yourself to give up anger,
  and you won't be angry at every fresh slight. Train yourself to avoid gossip,
  and you won't get pulled into it. Train yourself on any habit,
  and you'll be able to unconsciously go to that habit in trying times. Think about which behaviors you'd like to be able to default to if you could. How many of them have you practiced only once? Let today be twice.I
#+end_verse