#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 19th FLEXIBILITY OF THE WILL
#+begin_verse
'Remember that to change your mind and to follow someone's correction are consistent with a free will. For the action is yours alone—to fulfill its purpose in keeping with your impulse and judgment,
  and yes,
  with your intelligence.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
16 hen you set your mind to a task,
  do you always follow through?
It's an impressive feat if you do.
But don't let yourself become a prisoner of that kind of determination.
That asset might become a liability someday.
Conditions change.
New facts come in.
Circumstances arise.
If you can't adapt to them—if you simply proceed onward,
  unable to adjust according to this additional information—you are no better than a robot.
The point is not to have an iron will,
  but an adaptable will—a will that makes full use of reason to clarify perception,
  impulse,
  and judgment to act effectively for the right purpose.
It's not weak to change and adapt.
Flexibility is its own kind of strength.
In fact,
  this flexibility combined with strength is what will make us resilient and unstoppable.
D
#+end_verse