#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 6th THEY CAN THROW YOU IN CHAINS, BUT . . .
#+begin_verse
'You can bind up my leg,
  but not even Zeus has the power to break my freedom of choice.' —EPICTETUS,
  DISCOURSES,
  1.
1.
23 t was said that Epictetus walked with a permanent limp as a result of being chained up as a slave.
Two thousand years later,
  James Stockdale also had his legs chained in irons (and his arms bound behind his back and pulled from the ceiling,
  repeatedly wrenching them from their sockets).
Future senator John McCain was in that same prison,
  subjected to much of the same abuse.
Because his father was famous,
  McCain was repeatedly offered by his captors a chance to abandon his men and be sent home early.
He too held tightly to his freedom of choice,
  declining to submit to that temptation even though it meant a loss of the physical freedom he must have ached for.
None of these men broke.
No one could make them sacrifice their principles.
That's the thing—someone can throw you in chains,
  but they don't have the power to change who you are.
Even under the worst torture and cruelties that humans can inflict on one another,
  our power over our own mind and our power to make our own decisions can't be broken—only relinquished.
T
#+end_verse