#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 11th WHAT WOULD LESS LOOK LIKE
#+begin_verse
'Let us get used to dining out without the crowds,
  to being a slave to fewer slaves,
  to getting clothes only for their real purpose,
  and to living in more modest quarters.' —SENECA,
  ON TRANQUILITY OF MIND,
  9.
3b he writer Stefan Zweig—known for his Stoic-esque wisdom—was at one point one of the bestselling authors in the world,
  only to have his life destroyed by the rise of Hitler.
It's a sad yet timeless rhythm of history:
  politicians are run out of office for taking a stand we later recognize as courageous.
Countless hardworking and prosperous couples have their money stolen by financial crooks.
Someone is accused of a crime but not vindicated until years later.
At any moment we may be toppled from our perch and made to do with less—less money,
  less recognition,
  less access,
  less resources.
Even the 'less-es' that come with age:
  less mobility,
  less energy,
  less freedom. But we can prepare for that,
  in some way,
  by familiarizing ourselves with what that might feel like. One way to protect yourself from the swings of fate—and from the emotional vertigo that can result—is by living within your means now. So today,
  we can try to get used to having and surviving on less so that if we are ever forced to have less,
  it would not be so bad.I
#+end_verse