#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 4th HOW CAN YOU KNOW WHETHER YOU’VE NEVER BEEN
#+begin_verse
TESTED?
'I judge you unfortunate because you have never lived through misfortune. You have passed through life without an opponent —no one can ever know what you are capable of,
  not even you.' —SENECA,
  ON PROVIDENCE,
  4.
3 ost people who have gone through difficult periods in their life come to later wear those experiences as badges of honor.
'Those were the days,
  ' they might say,
  even though now they live in much better circumstances.
'To be young and hungry again,
  ' another might say wistfully.
'It was the best thing that ever happened to me,
  ' or 'I wouldn't change a thing about it.' As tough as those periods were,
  they were ultimately formative experiences.
They made those people who they are.
There's another benefit of so-called misfortune.
Having experienced and survived it,
  we walk away with a better understanding of our own capacity and inner strength.
Passing a trial by fire is empowering because you know that in the future you can survive similar adversity.
'What does not kill me makes me stronger,
  ' Nietzsche said.
So today if things look like they might take a bad turn or your luck might change,
  why worry?
This might be one of those formative experiences you will be grateful for later.
A
#+end_verse