#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 2nd THE PHILOSOPHER’S SCHOOL IS A HOSPITAL
#+begin_verse
'Men,
  the philosopher's lecture-hall is a hospital—you shouldn't walk out of it feeling pleasure,
  but pain,
  for you aren't well when you enter it.' —EPICTETUS,
  DISCOURSES,
  3.
23.
30 ave you ever been to physical therapy or rehab?
No matter what the name implies or how many people you see lying about,
  getting massages,
  it's not a fun place to be.
It turns out that healing hurts.
The trained experts know exactly where to exert pressure and what to subject to stress so that they can strengthen where the patient is weak and help stimulate the areas that have atrophied.
Stoic philosophy is a lot like that.
Some observations or exercises will touch one of your pressure points.
It's nothing personal.
It's supposed to hurt.
That's how you'll develop the will to endure and persevere through life's many difficulties.
B
#+end_verse