#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 3rd FIRST, A HARD WINTER TRAINING
#+begin_verse
'We must undergo a hard winter training and not rush into things for which we haven't prepared.' —EPICTETUS,
  DISCOURSES,
  1.
2.
32 efore the advent of modern warfare,
  armies typically disbanded during the winter.
War was not the total war as we understand it today,
  but more like a series of raids punctuated by the rare decisive battle.
When Epictetus says we ought to go through 'hard winter training'—the Greek word is cheimaskêsai—he was disputing the notion that there is such a thing as part-time soldiering (or part-time anything for that matter). In order to achieve victory,
  one must dedicate every second and every resource into preparation and training. LeBron James doesn't take a summer break—he uses it to work on other aspects of his game. The U.S. military trains its soldiers day and night when not at war,
  in preparation for when they have to go to war;
  when they do go to war,
  they fight until it's over. The same is true for us. We can't do this life thing halfheartedly. There's no time off. There aren't even weekends. We are always preparing for what life might throw at us—and when it does,
  we're ready and don't stop until we've handled it.M
#+end_verse