#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 30th YOU CAN’T TOUCH ME
#+begin_verse
'If you lay violent hands on me,
  you'll have my body,
  but my mind will remain with Stilpo.' —ZENO,
  QUOTED IN DIOGENES LAERTIUS,
  LIVES OF THE EMINENT PHILOSOPHERS,
  7.
1.
24 eno is not claiming magic powers but simply that while his body can be victimized,
  philosophy protects his mind—cultivated under his teacher,
  Stilpo—with an inner fortress whose gates can never be broken from the outside,
  only surrendered.
Look at Rubin 'Hurricane' Carter,
  the boxer wrongly convicted of homicide who spent nearly twenty years in prison. He would say,
  'I don't acknowledge the existence of the prison.
It doesn't exist for me.
' Of course,
  the prison literally existed,
  and he was physically inside it. But he refused to let his mind be contained by it. That's a power that you have too. Hopefully you'll never have to use this power in a situation of violence or grave injustice;
  however,
  in the midst of any and every kind of adversity,
  it is there. No matter what's happening to your body,
  no matter what the outside world inflicts on you,
  your mind can remain philosophical. It's still yours. It's untouchable —and in a way,
  then,
  so are you.OCTOBER VIRTUE AND KINDNESSS
#+end_verse