#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 29th YOUR ACTUAL NEEDS ARE SMALL
#+begin_verse
'Nothing can satisfy greed,
  but even a small measure satisfies nature. So it is that the poverty of an exile brings no misfortune,
  for no place of exile is so barren as not to produce ample support for a person.' —SENECA,
  ON CONSOLATION TO HELVIA,
  10.
11b t can be beneficial to reflect on what you used to accept as normal.
Consider your first paycheck—how big it seemed then.
Or your first apartment,
  with its own bedroom and bathroom and the ramen you gladly scarfed down in the kitchen.
Today,
  as you've become more successful,
  these conditions would hardly feel sufficient.
In fact,
  you probably want even more than what you have right now.
Yet just a few years ago those paltry conditions were not only enough,
  they felt great!
When we become successful,
  we forget how strong we used to be.
We are so used to what we have,
  we half believe we'd die without it.
Of course,
  this is just the comfort talking.
In the days of the world wars,
  our parents and grandparents made do with rationed gas,
  butter,
  and electricity.
They were fine,
  just as you have been fine when you had less.
Remember today that you'd be OK if things suddenly went wrong.
Your actual needs are small.
There is very little that could happen that would truly threaten your survival.
Think about that—and adjust your worries and fears accordingly.
Z
#+end_verse