#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 26th WHAT TIME OFF IS FOR
#+begin_verse
'Leisure without study is death—a tomb for the living person.' —SENECA,
  MORAL LETTERS,
  82.
4 ou deserve a vacation.
You work hard.
You sacrifice.
You push yourself.
It's time for a break.
Hop a plane,
  check into your hotel,
  and head to the beach—but tuck a book under your arm (and not a trashy beach read).
Make sure you enjoy your relaxation like a poet—not idly but actively,
  observing the world around you,
  taking it all in,
  better understanding your place in the universe.
Take a day off from work every now and then,
  but not a day off from learning.
Maybe your goal is to make enough money so that you can retire early.
Good for you!
But the purpose of retirement is not to live a life of indolence or to run out the clock,
  as easy as that might be to do.
Rather,
  it's to allow for the pursuit of your real calling now that a big distraction is out of the way.
To sit around all day and do nothing?
To watch endless amounts of television or simply travel from place to place so that you might cross locations off a checklist?
That is not life.
It's not freedom either.
T
#+end_verse