#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* September 12th BE DOWN TO EARTH, OR BE BROUGHT DOWN
#+begin_verse
'Zeno always said that nothing was more unbecoming than putting on airs,
  especially with the young.' —DIOGENES LAERTIUS,
  LIVES OF THE EMINENT PHILOSOPHERS,
  7.
1.
22 socrates's famous letter to Demonicus (which later became the inspiration for Polonius's 'To thine own self be true' speech) holds a similar warning to Zeno. Writing to the young man,
  Isocrates advises:
  'Be affable in your relations with those who approach you,
  and never haughty;
  for the pride of the arrogant even slaves can hardly endure.
' One of the most common tropes in art—from ancient literature to popular movies—is the brash and overconfident young man who has to be taken down a peg by an older,
  wiser man. It's a cliché because it's a fact of life:
  people tend to get ahead of themselves,
  thinking they've got it all figured out and are better than those that don't. It becomes so unpleasant to put up with that someone has to drop some knowledge on them. But this is an entirely avoidable confrontation. If the bubble is never inflated,
  it won't need to be popped. Overconfidence is a great weakness and a liability. But if you are already humble,
  no one will need to humble you—and the world is much less likely to have nasty surprises in store for you. If you stay down to earth,
  no one will need to bring you— oftentimes crushingly so—back down.T
#+end_verse