#+OPTIONS: \n:t num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
- 结合其他语法
* Western Civilization
[[./Western Civilization/index.html]]
** 01 Ruins of the ancient Sumerian city of Uruk
[[./Western Civilization/01 Ruins of the ancient Sumerian city of Uruk.html]]
dare daring: v.adj. involving a lot of risk or danger, or brave enough to do risky things大胆的
hazardous: adj. dangerous, especially to people’s health or safety危险的, 冒险的
swamp: n. land that is always very wet or covered with a layer of water沼泽, 湿地
brave: v. brave it out to deal bravely with something that is frightening or difficult勇敢地面对
expedition: n. a long and carefully organized journey, especially to a dangerous or unfamiliar place, or the people that make this journey远征, 探险队
cradle: n. a small bed for a baby, especially one that moves gently from side to side ⇨ cot摇篮, 发源地
southernmost: adj. furthest south最南的
solitary: adj. used to emphasize that there is only one of something SYN single单一的,孤独的
grandeur: n. impressive beauty, power, or size壮丽,雄伟
marsh: n. an area of low flat ground that is always wet and soft ⇨ bog, swamp湿地, 沼泽
mound: n. a pile of earth or stones that looks like a small hill山冈
crucial: adj. something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
nourish: v. to give a person or other living thing the food and other substances they need in order to live, grow, and stay healthy滋养
prehistory: n. the time in history before anything was written down史前史
agriculture agricultural: n.adj. the practice or science of farming农业的, 农艺的
community: n. the people who live in the same area, town etc社区
ultimate ultimately: adj.adv. someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最终的
Fahrenheit: n. a scale of temperature in which water freezes at 32° and boils at 212°华氏温度计
--------------------
move south down sp.: 沿着某地南下
in search of sth.: 寻找某物
high winds: 强风
loom from sth.: 从...隐现
know of nothing more adj. than sth.: 不知道什么比某事更...
make the shift from A to B: 从A转变到B
the roots of sth.: 某事物的根源
human race: 人类
be appropriate to do sth.: 适宜做某事
** 08 The coronation of Charlemagne by Pope Leo III
[[./Western Civilization/08 The coronation of Charlemagne by Pope Leo III.html]]
rebellious: deliberately not obeying people in authority or rules of behaviour造反的, 反叛的
basilica: a church in the shape of a long room with a round end(古罗马)长方形会堂, 长方形基督教堂
pray: to speak to God in order to ask for help or give thanks ⇨ prayer祈祷
apostle: one of the 12 people chosen by Jesus Christ to teach and spread the Christian religion使徒(指耶稣十二使徒)
blessed: holy神圣的
pacific: peaceful and loving or wanting peace和平的
reborn: to become active or popular again 再生
coronation: the ceremony at which someone is officially made king or queen ⇨ crown加冕礼
rebirth: formal when an important idea, feeling, or organization becomes strong or popular again复兴
contour: the shape of the outer edges of something such as an area of land or someone’s body轮廓
increasingly: more and more all the time日益, 愈加
fusion: a combination of separate qualities or ideas熔合
medieval: connected with the Middle Ages中世纪的
visible: something that is visible can be seen OPP invisible看得见的, 明显的
agrarian: relating to farming or farmers有关土地的
monarch monarchical: a king or queen国王的
decentralize decentralization: to move parts of a government, organization etc from a central place to several different smaller ones OPP centralize分散
subsequently: after an event in the past OPP previously后来
shaky: weak and unsteady because of old age, illness, or shock虚弱的
stifle: to stop something from happening or developing OPP encourage使窒息, 抑制
assimilate: if people assimilate, or are assimilated into a country or group, they become part of that group and are accepted by the people in that group吸收
dazzling: a light that is dazzling is very bright and makes you unable to see properly for a short time眼花缭乱的, 耀眼的
vitality: great energy and eagerness to do things活力
--------------------
journey to sp.: 旅行到某地
be barely clinging to power: 勉强抓住权力
be attended by sb.: 被某人陪伴
crowd into sp.: 涌入某地
rose from sth.: 从...起来
place a golden crown on sb's head: 给某人带上金冠
be crowned by sb.: 由某人加冕
prove inadequate to do sth.: 证明不足以做某事
evolve to become sth.: 演变成某物
pose threats: 构成威胁
** 08 The Slavic peoples of Central and Eastern Europe
[[./Western Civilization/08 The Slavic peoples of Central and Eastern Europe.html]]
spacious:a spacious house, room etc is large and has plenty of space to move around in OPP cramped宽广的
Asiatic:from or connected with Asia亚洲(人)的
nomad:a member of a tribe that travels from place to place instead of living in one place all the time, usually in order to find grass for their animals游牧部落的人, 流浪者, 游牧民
westward: towards the west向西
terrorize: to deliberately frighten people by threatening to harm them, especially so they will do what you want使恐怖, 恐吓, 恐怖统治
plunder: to steal large amounts of money or property from somewhere, especially while fighting in a war抢劫
peasant: a poor farmer who owns or rents a small amount of land, either in past times or in poor countries农夫, 乡下人
ravage: to damage something very badly毁坏, 掠夺
successive: coming or following one after the other连续的
overthrow: to get rid of the rules, ideas, or systems of a society推翻, 颠覆
migration: when large numbers of people go to live in another area or country, especially in order to find work移民
--------------------
push sb's way westward: 向西推进
these successive waves of sth.: 某事物的连续的几波
be assimilated with sth./sb.: 被某物/人同化
divide into sth.(pl.): 分成...
** 09 Street scene in a thirteenth-century English town
[[./Western Civilization/09 Street scene in a thirteenth-century English town.html]]
spur: v.to encourage someone or make them want to do something鞭策, 刺激
defence: n.all the systems, people, materials etc that a country uses to protect itself from attack防卫
modesty: n.a modest way of behaving or talking谦逊, 虚心
myriad: adj.very many无数的
practically: adv.especially spoken almost几乎, 简直
good-for-nothing: adj.a good-for-nothing person is lazy and useless无用的, 无益的
esteem: n.a feeling of respect for someone, or a good opinion of someone尊敬, 尊重
leisure: n.time when you are not working or studying and can relax and do things you enjoy空闲
wrestle: v.to fight someone by holding them and pulling or pushing them摔跤
maiden: n.literary a young girl, or a woman who is not married SYN damsel少女, 处女
fen: n.an area of low flat wet land, especially in eastern England沼泽
moor: especially British English a wild open area of high land, covered with rough grass or low bushes and ↑heather, that is not farmed because the soil is not good enough沼地
stride: to walk quickly with long steps ⇨ march大步走
sewage: n.the mixture of waste from the human body and used water, that is carried away from houses by pipes under the ground下水道, 污水
veritable: adj. a word used to emphasize a description of someone or something SYN real真正的
--------------------
come into sb's own: 充分展示自身价值
reach sb's zenith: 达到某人的顶峰
be characterized by sth.: 以某物为特征
a burst of sth.: 某物的突然爆发
give a new dynamism to sth.: 赋予某事物新的活力
be fruitful of sth.: 某物硕果累累
living expenses: 生活费
according to sb's station: 根据其地位
fight battles: 奋斗
be exercised in sth./doing sth.: 在某事中被锻炼
cast the stone: 扔石头
sth./sb. is known to do sth.: 某事物/某人做某事是已知的
be at hand: 即将发生/在手里
raw sewage: 未经处理的废水
** 10 A medieval abbot and his monks
[[./Western Civilization/10 A medieval abbot and his monks.html]]
vassal: n. a man in the Middle Ages who was given land to live on by a lord in return for promising to work or fight for him封臣
dissension: n. disagreement among a group of people纠纷, 争执
petty: adj. a petty problem, detail etc is small and unimportant SYN trivial小的, 不重要的
centralize: v. to organize the control of a country, organization, or system so that everything is done or decided in one place OPP decentralize集聚, 集中, 施行中央集权
inaugurate: v. to open a building or start an organization, event etc for the first time开辟
monarch monarchical: adj. 国王的
solidify: v. to make an agreement, plan, attitude etc more definite and less likely to change SYN strengthen团结, 巩固
reform: v. a change or changes made to a system or organization in order to improve it改革
exalted: adj. having a very high rank and highly respected尊贵的
papal: adj. relating to the Pope罗马教皇的
vigorous: adj. strong and healthy精力旺盛的, 有力的, 健壮的
forceful: adj. forceful arguments, reasons etc are strongly and clearly expressed SYN powerful有力的
abbot: n. a man who is in charge of a ↑monastery主持
abbey: n. a large church with buildings next to it where ↑monks and ↑nuns live or used to live修道院
devout: adj. someone who is devout has a very strong belief in a religion虔敬的
undergarment: n. old-fashioned a piece of underwear内衣
abhor abhorred: v. to hate a kind of behaviour or way of thinking, especially because you think it is morally wrong憎恶, 痛恨
talkative: adj. someone who is talkative talks a lot OPP quiet多嘴的
supervise: v. to be in charge of an activity or person, and make sure that things are done in the correct way监督, 管理, 指导
secular: adj. not connected with or controlled by a church or other religious authority长期的
--------------------
be mired in sth.: 陷入某事
be coupled with sth./sb.: 与...相结合
made it almost inevitable that + ...: 使得...几乎不可避免
fall into debt (under sb.): 陷入债务
toil tirelessly: 不知疲倦地工作
round up sb.: 聚集某人
stand trial: 接受审判
be instrumental in doing sth.: 在做某事中起作用
drive sb. from sp.: 赶某人出某地
be not above doing sth.: 不怎么高尚地做某事
** 10 The Crusades of the Thirteenth Century
[[./Western Civilization/10 The Crusades of the Thirteenth Century.html]]
initiate: v. formal to arrange for something important to start, such as an official process or a new plan开始, 发动
succession: n. the act of taking over an official job or position, or the right to be the next to take it ⇨ accession继承, 继任
throne: n. a special chair used by a king or queen at important ceremonies王座
neutralize: v. to destroy something that is dangerous to you during a war摧毁
sack: v. if soldiers sack a place, they go through it destroying or stealing things and attacking people洗劫
recapture: v. to take control of a place again by fighting for it SYN retake夺回
territory: n. land that is owned or controlled by a particular country, ruler, or military force领土
conquer: v. to get control of a country by fighting征服
ideal: n.adj. 理想
warrior: n. a soldier or fighter who is brave and experienced – used about people in the past勇士
guardian: n. someone who guards or protects something护卫者, 监护人
--------------------
On sb's way to sp.: 某人去某地的路上
a dispute over sth.: 对某事的争端
see an opportunity to do sth.: 看到做某事的机会
be diverted to sp.: 被转移到某地
limp along: 艰难前行
sb. announced that + ...: 某人宣布...
inspire sb. to do sth.: 激励某人去做某事
lead sb. to sp.: 带领某人去某地
free A from B: 从B释放A

** 10 The rise of Kingdoms and the growth of church power
[[./Western Civilization/10 The rise of Kingdoms and the growth of church power.html]]
dynamic: adj. full of energy and new ideas, and determined to succeed充满活力的
warlike: adj. liking war and being skilful in it好战的, 尚武的
dominate: v. to control someone or something or to have more importance than other people or things支配
condescending condescendingly: adj. adv. behaving as though you think you are better, more intelligent, or more important than other people – used to show disapproval SYN patronizing居高临下的
witness: v. to see something happen, especially a crime or accident目击
renewal: n. when an activity, situation, or process begins again after a period when it had stopped复兴
diverge divergent: v. adj. if similar things diverge, they develop in different ways and so are no longer similar分叉的
revive: v. to bring something back after it has not been used or has not existed for a period of time(使)复兴, (使)复活
administrative: adj. relating to the work of managing a company or organization管理的, 行政的
buttress: v. to support a system, idea, argument etc, especially by providing money扶持
clergy: n. the official leaders of religious activities in organized religions, such as priests, ↑rabbis, and ↑mullahs ⇨ clerical神职人员
laity: n. the laity all the members of a religious group apart from the priests ⇨ layman普通信徒
animosity: n. strong dislike or hatred SYN hostility仇恨, 憎恶
repercussion: n. the effects of an action or event, especially bad effects that continue for some time ⇨ consequence反响
friar: n. a member of a religious group of Catholic men, who travelled around in the past teaching about Christianity and who were very poor ⇨ monk男修道士
passion: n. a very strong feeling of sexual love ⇨ desire激情, 热情
underneath: prep. adv. directly under another object or covered by it在下面
discontent: n. a feeling of being unhappy and not satisfied with the situation you are in OPP contentment不满
innovation: n. a new idea, method, or invention改革, 创新
tension: n. a nervous worried feeling that makes it impossible for you to relax ⇨ tense紧张
--------------------
label sb. sth.: 给某人贴上某物的标签
assume political authority: 承担政治权力
lay the foundation for sb./sth.: 为某人/某物打下基础
in one form or another: 以一种形式或另一种
in the challenge of sth.: 在...的挑战中
strike out on a path toward sp./sth.: 开辟通往某地的道路
lay seeds of sth.: 种下某事的种子
be dissent from sth.: 对某事持不同意见
respond with sth.: 以...回复
enforce conformity to sth.: 强制遵守某事
supremacy over sth.: 凌驾于某物
carry out sb's wishes: 实施某人的意愿
creep into sp.: 悄悄进入某地
a torrent of sth.: 一股...的洪流
** 11 Mass burial and cremation of plague victims
[[./Western Civilization/11 Mass burial and cremation of plague victims.html]]
vast: adj. extremely large SYN huge巨大的, 辽阔的
stable stability: adj. n. steady and not likely to move or change OPP unstable ⇨ stability稳定的
route: n. a way between two places that buses, planes, ships etc regularly travel路线
avenue: n. a possible way of achieving something方法, 途径
infested: adj. if insects, rats etc infest a place, there are a lot of them and they usually cause damage大批滋生的
plague: n. v. a disease that causes death and spreads quickly to a large number of people瘟疫,折磨
contemporary: adj. belonging to the present time SYN modern当代的, 同时代的
untouched: adj. not changed, damaged, or affected in any way未触及的, 未改变的
isolated: adj. an isolated building, village etc is far away from any others SYN remote隔离的,孤立的
scarce: adj. if something is scarce, there is not very much of it available缺乏的, 不足的
reaper: n. 收割的人
mower: n. 割草的人
rot: v. to decay by a gradual natural process, or to make something do this(使)腐烂, (使)腐败
disintegrate disintegration: v. n. to break up, or make something break up, into very small pieces(使)分解, (使)碎裂
famine: n. a situation in which a large number of people have little or no food for a long time and many people die饥荒
universal: adj. involving everyone in the world or in a particular group普遍的, 全体的
dissolution: n. the process by which something gradually becomes weaker and disappears分解, 解散
--------------------
stretch from A to B: 从A延伸到B
be overwhelmed by sth.: 被某事淹没
the magnitude of sth.: 某事的巨大
be stunned by sth.: 被某事震惊
began sb's account of sth. with these words: 用这些话开始某人对某事的叙述
economic depression: 经济萧条
social upheaval: 社会动荡
be fertile grounds for sth.: 称为某物的沃土
** 11 The later Middle Ages, Crisis and Disintegration in the fourteenth century
[[./Western Civilization/11 The later Middle Ages, Crisis and Disintegration in the fourteenth century.html]]
fundamental: adj. relating to the most basic and important parts of something基础的, 基本的
feature: n. a part of something that you notice because it seems important, interesting, or typical特征
capitalist: adj. using or supporting capitalism ⇨ communist, socialist资本主义的
industry: n. businesses that produce a particular type of thing or provide a particular service工业, 产业
vernacular: adj. a form of a language that ordinary people use, especially one that is not the official language方言的
fertile: adj. fertile land or soil is able to produce good crops肥沃的, 富饶的
revolt: n. a refusal to accept someone’s authority or obey rules or laws SYN rebellion反抗, 起义
constant: adj. happening regularly or all the time SYN continual持续的
warfare: n. the activity of fighting in a war – used especially when talking about particular methods of fighting战争, 作战, 冲突, 竞争
faction factional: n.adj. a small group of people within a larger group, who have different ideas from the other members, and who try to get their own ideas accepted派别
spectacle: n. an unusual or interesting thing or situation that you see or notice – used especially in order to show disapproval奇观
overpower: v. to take control of someone physically because you are stronger制服, 压倒
calamity calamitous: n.adj. a terrible and unexpected event that causes a lot of damage or suffering SYN disaster灾难
revelation: n. a surprising fact about someone or something that was previously secret and is now made known揭露
pestilence: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
resilient: adj. able to become strong, happy, or successful again after a difficult situation or event ⇨ tough有弹性的
intellectual: n.adj. an intelligent well-educated person who spends time thinking about complicated ideas and discussing them ⇨ academic知识分子
threshold: n. at the beginning of a new and important event or development SYN brink开始, 开端
--------------------
reach sb's apogee: 到达顶点
be challenged by sth./sb.: 被某人/某事物挑战
pit A against B: 使A与B竞争
condemn A as B: 谴责A为B
see sb. as doing sth.: 认为某人在做某事
** 12 Michelangelo's Creation of Adam on the Sistine Chapel ceiling
[[./Western Civilization/12 Michelangelo's Creation of Adam on the Sistine Chapel ceiling.html]]
continuation: n. something that continues or follows something else that has happened before, without a stop or change延续
position: n. the situation that someone is in, especially when this affects what they can and cannot do立场,位置
significant: adj. having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
humanism humanist: n. the belief that human problems can be solved through science rather than religion人本主义
neglect: v. to pay too little attention to something忽视, 疏忽
accomplished: adj. an accomplished writer, painter, singer etc is very skilful多才多艺的
landscape: n. the political/social landscape the general situation in which a particular activity takes place形势
titan: n. a very strong or important person SYN giant巨人
temperament: n. the emotional part of someone’s character, especially how likely they are to be happy, angry etc气质
lengthy: adj. continuing for a long time, often too long OPP brief冗长的, 过分的
commission: n. a request for an artist, designer, or musician to make a piece of art or music, for which they are paid委托
ceiling: n. the inner surface of the top part of a room ⇨ roof天花板
daunting: adj. frightening in a way that makes you feel less confident使人畏缩的
exasperate: v. to make someone very annoyed by continuing to do something that upsets them激怒
biographer: n. someone who writes a biography of someone else传记作者
scaffolding: n. a set of poles and boards that are built into a structure for workers to stand on when they are working on the outside of a building脚手架
historian: n. someone who studies history, or the history of a particular thing历史学家
emphasize: v. to say something in a strong way SYN stress强调
distinguish: v. to recognize and understand the difference between two or more things or people SYN differentiate区别
--------------------
continue into st.(the future): 持续到未来
restore sth. to new glory: 恢复某事的新荣耀(辉煌)
hire sb. to do sth.: 雇佣某人去做某事
pester sb. about sth.: 纠缠某人某事
on a regular basis: 定期的
sb. threatens that + ...: 某人威胁...
lose no time in doing sth.: 不浪费时间马上做某事
view of A as B: 把A视作为B的观点
** 12 Recovery and rebirth, the Renaissance
[[./Western Civilization/12 Recovery and rebirth, the Renaissance.html]]
transition: n. formal when something changes from one form or state to another转变,过渡
extend: v. to continue for a longer period of time, or to make something last longer延伸
trend: n. a general tendency in the way a situation is changing or developing倾向, 趋势
proclaim: v. to say publicly or officially that something important is true or exists宣布, 声明
humankind: n. people in general SYN mankind人类
accomplishment: n. something successful or impressive that is achieved after a lot of effort and hard work SYN achievement成就
elite: n. a group of people who have a lot of power and influence because they have money, knowledge, or special skills精华, 精锐, 中坚分子
broad: adj. WIDE a road, river, or part of someone’s body etc that is broad is wide OPP narrow ⇨ adth宽的, 阔的
mass: n. a large crowd群众
obtain: v. to get something that you want, especially through your own effort, skill, or work SYN get获得, 得到
cultivate: v. to work hard to develop a particular skill, attitude, or quality培养, 耕作
influential: adj. having a lot of influence and therefore changing the way people think and behave有影响的, 有势力的
institution: n. an important system of organization in society that has existed for a long time公共机构, 协会, 制度
revolution: n. a time when people change a ruler or political system by using force or violence ⇨ revolt, rebellion革命
profound: adj. having a strong influence or effect深刻的, 意义深远的
reformation: n. formal when something is completely changed in order to improve it改革, 革新
unify unified: v.adj. if you unify two or more parts or things, or if they unify, they are combined to make a single unit SYN unite OPP divide ⇨ unification统一
commonwealth: n. the official title of some countries made up of a group of states联邦
--------------------
a new vision of sth.: 对某事的新视野/认识
raise fundamental questions/issues about sth.: 提出关于某事的基本问题
upper classes: 上层阶级
with sb's hands: 用某人双手
be incapable of sth./doing sth.: 无法做某事
have no time to do sth.: 没有时间去做某事
give way to sth.: 让位于某事;被某事取代
* TED-Ed
** 2013-10-01 The uncertain location of electrons
[[./TED-Ed/2013-10-01 The uncertain location of electrons.html]]
particle: a very small piece of something 微粒
proton: a very small piece of matter with a positive electrical charge that is in the central part of an atom质子
neutral: not supporting any of the people or groups involved in an argument or disagreement中性的
nucleus: nuclei(复数) 原子核
indulge: to let yourself do or have something that you enjoy纵容
orbitals /ˈɔːbɪtl/ ring road 轨道
density: the degree to which an area is filled with people or things密度
quirk: a strange habit or feature of someone’s character, or a strange feature of something怪异
exponential exponentially: exponential growth/increase etc exponential growth, increase etc becomes faster as the amount of the thing that is growing increases指数
--------------------	
in a momentary tangent: to suddenly start talking or thinking about a completely new subject在片刻的切题中
develop a model for sth.: 发展某事物的模型
agree with sth.: 同意某事;符合某事
it might be time for sth./ to do sth.: 可能是做某事的时候了
there will be many more to do sth.: 将会有更多的事情要做
tend to do sth.: 倾向于做某事
stick together: 团结在一起
behave as/like sth.: 表现得像
perform experiment: 做实验
It's (not) that + ..., it's that + ..: 不是...,而是...
there's a certain probability of doing sth.: 做某事有一定的可能性
be 95% sure of doing sth.: 95%确信做某事
more or less: 或多或少
decrease/increase exponentially: 指数地减少/增加
approach zero: 接近0
hit zero: 到达0
there is some small, but non-zero, probability that + ..: 有很小但非0的概率...
for a very, very short period of time: 在非常短的时间
interact with sth./sb.: 与某人某物互动
surrender A to B: to give up something or someone, especially because you are forced to把A交给B
** 2013-10-03 Why extremophiles bode well for life beyond Earth
[[./TED-Ed/2013-10-03 Why extremophiles bode well for life beyond Earth.html]]
(in) outer space: 外太空
abduction by sb.: 被某人绑架
in the universe: 宇宙中
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose得到某物
form life: 形成生命
ancient religions: 古代宗教
be inhabited by sb.: 被某人居住
sth. be more like A than B: 某事更像A而不是B
mythical realms: 神话王国
parallel universes: 平行宇	宙
It is only within the last century that + ...: 只是在上个世纪, ...
undertake sth./ to do sth.: 承担某事/做某事
A is just the right distance from B: A到B的距离正好
support life: 维持生命
sth. is fatal for sb.: resulting in someone’s death某事对某人是致命的
in the dark depths of oceans/lakes/rivers: 在海洋/湖泊/河流的黑暗深处
on the flanks of volcanoes: the side of a hill, mountain, or very large building在火山的侧面
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things处于某事物的极端 
What is most remarkable about sth. is that + ...: 关于某事最值得注意的是...
hit the surface of sth.: 碰撞某事物的表面
be flowing with sth.: to have some liquid coursing on the surface or within someone or something流满某物
be composed of sth.: 由某物组成
be the basic building block of sth.: 成为某事物的基本组成部分
** 2013-10-08 The operating system of life
[[./TED-Ed/2013-10-08 The operating system of life.html]]
oak: 橡树, 橡木
acorn: the nut of the ↑oak tree橡树果
tadpole: a small creature that has a long tail, lives in water, and grows into a frog or toad蝌蚪
mold: a soft green, grey, or black substance that grows on food which has been kept too long, and on objects that are in warm wet air ⇨ mouldy:霉菌 
organism: an animal, plant, human, or any other living thing有机体
lifeform: 生物
machinery: 机器, 机械
mission: 使命, 任务
currency: the system or type of money that a country uses货币
blueprint: technical a pattern that all living cells contain, which decides how a person, animal, or plant develops and what it looks like蓝图
photocopy: 影印
block: 块
giant: extremely big, and much bigger than other things of the stype庞大的, 巨大的
furnace: a large container for a very hot fire, used to produce power, heat, or liquid metal熔炉
fuel: a substance such as coal, gas, or oil that can be burned to produce heat or energy燃料
scrap: to get rid of an old machine, vehicle etc, and use its parts in some other way拆毁
specialized: 专门的, 专科的
portal: 入口
deoxyribonucleic acid: DNA
protein: 蛋白质
amino: ['æminәu]氨基的
acid: a chemical substance that has a ↑pH of less than 7. Strong acids can burn holes in material or damage your skin酸
mineral: 矿物, 矿石
lipid: 脂质, 油脂[脂肪,乳酪]
a.k.a.: also known as, 又名..., 也叫作...
membrane: 膜, 隔膜
interaction: 交互作用, 交感
oxygen: 氧
phosphate: 磷酸盐
molecule molecular: the smallest unit into which any substance can be divided without losing its own chemical nature, usually consisting of two or more atoms分子
tote: informal to carry something, especially regularly手提, 背负, 携带
biochemistry: 生物化学
excess: a larger amount of something than is allowed or needed超额
glycogen: ['glaikәudʒen]肝糖, 糖原质
bacteria: very small living things, some of which cause illness or disease ⇨ virus细菌
--------------------
in the back of your fridge: 冰箱深处
sb. is a gleam in sb's eyes: A是B的构想
share the same basic goal: 拥有相同的基本目标
perpetuate sb's existence: 使某人永久存在
stay alive: 设法不死
set up a factory: 开办工厂
keep sb. doing sth.: 使某人做某事
assembly instructions: 装配说明
raw materials: 原材料
get paid: 获得报酬
send sth. off: to send a letter, document, or package by mail邮寄/发出某物
assemble A into B: 将A组装成B
be transported to sp.: 被运送到某地
draw energy from sth.: 从某物那里获取能量
harsher working conditions: 艰苦的工作环境
be walled off: 被隔离起来
the rest of sth.: 某物剩余部分
be embedded into sth.: 被嵌入到某物
be built from sth.: 由某物建造
are derived from: to come or develop from something 来源于
in a pinch: in an emergency在紧急情况下
minimum wage: 最低薪酬
be transferred between sth.(pl.): to move someone or something from one place, vehicle, person, or group to another在某物间转移
in the face of sth.: 面对某事物
extreme challenges: 极限挑战
mobilize the immune system: 激起防御系统
** 2013-10-08 What is the shape of a molecule
[[./TED-Ed/2013-10-08 What is the shape of a molecule.html]]
mass: a large amount or quantity of something群众的, 大规模的, 集中的
nucleus nuclei: 核子
discrete: clearly separate不连续的, 离散的
sausage: a small tube of skin filled with a mixture of meat, spices etc香肠, 腊肠
formula: a series of numbers or letters that represent a mathematical or scientific rule公式
favorable: suitable and likely to make something happen or succeed起促进作用的
--------------------
be concentrated in: 集中于
be bonded to sth./sb.: 与……紧密相连
there's at least one way to do sth.: 至少有一种方法可以做某事
maximize/minimize the attraction/repulsion of sth.(pl.): 使…的吸引/排斥最大化/最小化
A matter to B: A对B重要
A be the outermost one(s) from B: A是B最远的部分
in between sth.: 在...之间
be kind of like sth.: 有点像某物
be bunched up together: 被聚拢在一起
fly apart: 四分五裂,飞离
doesn't help anyone: 一点帮助都没有
decades before: 数年前
be arranged in 3D space: 在3维是如何被安排
bond with sth./sb.: 与他人建立紧密联系
draw sth. as a line: 把某物画成一条线
have a flat representation of sth.: 有某物的平面图
in three dimensions: 在三维空间
get A far away from B: 使A远离B
expand on our model of sth. to do sth.: 详述xx的模型去做某事
Spoiler alert: 剧透

** 2013-10-17 How we conquered the deadly smallpox virus
[[./TED-Ed/2013-10-17 How we conquered the deadly smallpox virus.html]]
marrow: the soft fatty substance in the hollow centre of bones髓, 骨髓
spleen: an organ near your stomach that controls the quality of your blood 脾脏
lymph nodes: 淋巴结
vomit: to bring food or drink up from your stomach out through your mouth, because you are ill呕吐
scar: 疤痕
scab: 痂
epidemic: a large number of cases of a disease that happen at the same time流行病
insidious insidiously: an insidious change or problem spreads gradually without being noticed, and causes serious harm暗中为害的, 阴险的
merchant: someone whose job is to buy and sell things商人
Buddhist: 佛教徒
nun: someone who is a member of a group of religious women that live together修女, 尼姑
providence: 深谋远虑, 天意, 上帝, 神的眷顾
variolation: 天花接种
sore: a part of your body that is sore is painful痛处
inoculate: to protect someone against a disease by putting a weak form of the disease into their body using a needle接种
foolproof: a foolproof method, plan, system etc is certain to be successful十分安全的
dairy: dairy products/produce milk, butter, cheese etc奶制品
apothecary: someone who mixed and sold medicines in the past药剂师, 药师
pockmarked: covered with hollow marks or holes麻子脸
udder: the part of a cow, female goat etc that hangs down between its back legs and that produces milk(牛、羊等的)乳房
pustule: 脓疱
vaccinate vaccination: to protect a person or animal from a disease by giving them a vaccine接种牛痘
establishment: formal an organization or institution, especially a business, shop etc公司, 军事组织
--------------------
spread through sth.: 通过某物传播
develop fevers, vomiting, rashes, smallpox: 发烧，呕吐，皮疹，天花
bear scars and scabs: 留下疤痕和结痂
spread sth. to sb.: 把某事传播给某人
devastate the civilization: 毁灭文明
make its way around the world via sb.: 通过某人环游世界
an estimated Axx to Bxx sth./sb.: 估计Axx到Bxx某事/某人
the fall of sb./sth. start: 某人/某物的失败开始了
It begins all the way back when + ...: 这要追溯到+…
grind up sth.: 磨碎某物
blow the powder into sp.: 把粉末吹到某个地方
up to xx percent of sth.: 高达某物的百分之xx
be exposed to sth.: you are in danger from it暴露于某物
be an apprentice to sjob.: pupil成为某职业的学徒
a pockmarked face: 一张麻子脸
protect against sth.: 防止某事
A be caught from B: 从B带来A(病毒)
challenge sb. with sth.: 用某事挑战某人
be immune to sth.: 对某事物免疫
with this procedure: 通过这个过程
deliberate at length over sth.: 仔细考虑某事
become prohibited: 变得被禁止
certify sth's eradication: 证明某物的根除
be forever remembered as ...: 被永远铭记为……
the father of -logy.: 某学之父
in this great adventure of sth.: 在...的伟大冒险中

** 2013-11-04 The deadly irony of gunpowder
[[./TED-Ed/2013-11-04 The deadly irony of gunpowder.html]]
epic: very large and impressive壮丽的, 大规模的
gunpowder: an explosive substance used in bombs and fireworks黑色火药
alchemist: a science studied in the Middle Ages, that involved trying to change ordinary metals into gold炼金术士
flame/ flammable/ flamethrower: literary to burn brightly火焰
cannon: a large heavy powerful gun that was used in the past to fire heavy metal balls 加农炮
barrel: a large curved container with a flat top and bottom, made of wood or metal, and used for storing beer, wine etc桶
canister: a metal container for keeping something in (放咖啡, 茶叶, 烟等的)小罐, 筒
channel: to control or direct people or things to a particular place, work, situation etc引导, 开导
wick: the piece of thread in a candle, that burns when you light it灯芯
ignite: formal to start burning, or to make something start burning 点火, 点燃
compound: a substance containing atoms from two or more elements 混合物
shape: to influence something such as a belief, opinion etc and make it develop in a particular way形成, 影响
upward-facing: 面向上
--------------------
fireworks displays: 烟火展
propel sth. into sp.: to move, drive, or push something forward推动某事到某地
begin back: to begin to return somewhere倒回
a potion for immortality: 永生药
the opposite of sth.: 某物的反面
In these early days: 在早些年代
the right proportions of ingredients: 配料的正确比例
evil spirits: 恶灵
defend sb. against sth./sb.: 保卫某人免于...
the invention of sth.: 某物的发明
field sb's attacks: 回击某人的攻击
on sb's conquests in sp.: 在某人某地的征服中
bringing sth. back to sp.: 把某物带回某地
From there: 从这里
left sb's mark on sth.: to have an effect that changes someone or something, usually in a bad way在某事上留下某人的印记
in contrast to: it is very different from it与……相反
be contained within/in: 包含在…之内
build up: accumulate积累
take an exit from sp.: 从...出去
** 2013-10-29 Vampires - Folklore, fantasy and fact
[[./TED-Ed/2013-10-29 Vampires - Folklore, fantasy and fact.html]]
vampire: in stories, a dead person that sucks people’s blood by biting their necks吸血鬼
shamble: to walk slowly and awkwardly, not lifting your feet much, for example because you are tired, weak, or lazy蹒跚地走
corpse: the dead body of a person尸体
dapper: used to show that you are talking about someone or something that has not been mentioned Debefore, or that your listener does not know about 整洁的
revenant: 幽灵, 亡魂
donkey: a grey or brown animal like a horse, but smaller and with long ears驴子
bloodthirsty: eager to kill and wound, or enjoying killing and violence嗜杀的, 残忍的
sever: to cut through something completely, separating it into two parts, or to become cut in this way切断
upper:in a higher position than something else上面的, 上部的
torso: your body, not including your head, arms, or legs躯干
sprout: if vegetables, seeds, or plants sprout, they start to grow, producing shoots, buds, or leaves萌芽
wing: one of the parts of a bird’s or insect’s body that it uses for flying翅膀
entrail: the inside parts of an animal’s or person’s body, especially their intestines内脏
bloodsucker / bloodsucking: a creature that sucks blood from the bodies of other animals吸血生物
trait: formal a particular quality in someone’s character特性
reanimated/reanimation: formal to give new strength to someone or something or the energy to start again 复活
folklore: the traditional stories, customs etc of a particular area or country民间传说
nocturnal: an animal that is nocturnal is active at night夜行的
grim: making you feel worried or unhappy 严酷的
supernatural: impossible to explain by natural causes, and therefore seeming to involve the powers of gods or magic超自然的
cadaver: technical a dead human body, especially one used for study SYN corpse死尸
bloated: if you describe an organization as bloated, you mean that it is too big and does not work effectively浮肿的
beheading: 斩首
decompose: to decay or make something decay分解, (使)腐烂
dehydrate: to remove the liquid from a substance such as food or a chemical(使)脱水
incorporate: to include something as part of a group, system, plan etc合并, 混合
garlic: a plant like a small onion, used in cooking to give a strong taste蒜头
stake: 树桩
attribute: 属性
crucifixes: a cross with a figure of Christ on it十字架
reflection: an image that you can see in a mirror, glass, or water映象
stalk: 潜伏
subsist: to stay alive when you only have small amounts of food or money SYN survive生存
sparkling: shining brightly with points of flashing light闪烁的
--------------------
What's the matter: 怎么了
extend as far back as prehistoric times: date back to可以追溯到史前时代
back then: at a particular time in the past that you are talking about当时
be simply described as sth.: 被简单地描述为……
have one common characteristic: 有个共同特性
sustain oneself by doing sth.: 通过做某事来维持生计
the life force of sth.: 某物的生命力
change with the times: 随时间而改变
With the dramatic increase of sth.: 随着某物的戏剧性增多
dig up <-> sth.: 挖掘
discern the cause of sth.: 查明某物的原因
at the corners of mouths: 在嘴角
feast on sth.: 享用某物
enact a ritual to do sth.: 制定仪式去做某事
stake the body to the coffin: 把尸体钉在棺材里
normal symptoms of sth.: 某事的正常现象
cause sb./sth. to do sth.: 造成某人/某事做某事
force out sth. through sth.: 通过某处挤出某物
establish a law prohibiting sth./doing sth.: 制定法律禁止某事
die down: 消亡
brutal executions: 残酷的死刑
inspire the main elements of sth.: 激发某事的主要元素
enact the age-old tradition of doing sth.: 延续做某事的古老传统
elaborate upon: 详细阐述
** 2013-12-16 The popularity, plight and poop of penguins
[[./TED-Ed/2013-12-16 The popularity, plight and poop of penguins.html]]
clumsy: moving or doing things in a careless way, especially so that you drop things, knock into things etc笨拙的
adorable: someone or something that is adorable is so attractive that they fill you with feelings of love可爱的
exceedingly: extremely非常地, 极度地
ornery: behaving in an unreasonable and often angry way, especially by doing the opposite of what people want you to do坏脾气的
precarious: a precarious situation or state is one which may very easily or quickly become worse不稳定的
closest: 最靠近的
albatross: a very large white sea bird信天翁
wingspan: 翼展
soar: to increase quickly to a high level高飞
evolutionary: relating to the way in which plants and animals develop and change gradually over a long period of time进化的
flipper-like: a flat part on the body of some large sea animals such as ↑seals, that they use for swimming鳍状的
dive: to swim under water using special equipment to help you athe潜水, 跳水
hemisphere: a half of the Earth, especially one of the halves above and below the equator半球
breed: if animals breed, they ↑mate in order to have babies繁殖
reproduce: 繁殖 
subantarctic: 亚南极(区)的
craggy: 多峭壁的, 崎岖的
lava: hot liquid rock that flows from a volcano, or this rock when it has become solid熔岩, 火山岩
burrow: a passage in the ground made by an animal such as a rabbit or ↑fox as a place to live洞穴
stick: a long thin piece of wood from a tree, which is no longer attached to the tree ⇨ branch, twig棍, 棒
incubate: if a bird incubates its eggs, or if the eggs incubate, they are kept warm until they hatch孵卵
approximate approximately: an approximate number, amount, or time is close to the exact number, amount etc, but could be a little bit more or less than it近似地, 大约
indicator: something that can be regarded as a sign of something else指示器
historically: 在历史上, 从历史观点上说
disturbance: 干扰
guano: 海鸟粪
fertilizer: a substance that is put on the soil to make plants grow肥料
marine: relating to the sea and the creatures that live there海的, 海产的
terrestrial: living on or relating to land rather than water陆地的
habitat: the natural home of a plant or animal栖息地
introduce: 引进
predator: an animal that kills and eats other animals ⇨ prey掠夺者
prey: an animal, bird etc that is hunted and eaten by another animal OPP predator被掠食者
entrapment: the practice of trapping someone by tricking them, especially to show that they are guilty of a crime诱捕的行动
plastic: a light strong material that is produced by a chemical process, and which can be made into different shapes when it is soft塑胶的
krill: small shellfish[动]磷虾
severe severity: severe problems, injuries, illnesses etc are very bad or very serious严峻的
conservation: the protection of natural things such as animals, plants, forests etc, to prevent them from being spoiled or destroyed SYN preservation保存, 保持
spills: 泄漏
vulnerable: someone who is vulnerable can be easily harmed or hurt易受攻击的
tuxedo: 燕尾服
current: 当前
--------------------
have long done sth.: 长久做某事
capture the imagination and the hearts of sb.: 抓住某人的想象力和心
the world over: 全世界的每个地方
depict A as B: describe A as B 把A描绘成B
endlessly abundant: 庞大数量的
in rapid free fall: 在快速自由落体
so to speak: 可以说
For one thing: 首先
evolve from sth.: 从什么进化
the ability to do sth.: 做某事的能力
fill an ecological niche: 占据生态位
contrary to sth.: 与某事相反的
be not restricted to sp.: 不限于某处
subtemperate/temperate regions: 亚热带/热带区域
off sp.: in the neighbor of sp.在…的邻居
molt their feathers: 退去自身的羽毛
in tussock grasses: 在草丛中
a clutch of sth./sb.: 一群/把/组
be listed as sth.: 被列为某物
decline by: 下降
be down to sth.: 下降到
in the coal mine: 在煤矿洞里
Simply put: 简单来说
be attributable to sth.: 对某事归因
due to sth.: [4]归因于
carry sb. too far away from sp.: 把某人带离某地太远
be underway to do sth.: 正在做某事
** 2014-01-06 How to fossilize yourself
[[./TED-Ed/2014-01-06 How to fossilize yourself.html]]
fossil: an animal or plant that lived many thousands of years ago and that has been preserved, or the shape of one of these animals or plants that has been preserved in rock化石
tour: to visit several parts of a country or areaa journey for pleasure, during which you visit several different towns, areas etc旅行
fawn: to praise someone and be friendly to them in an insincere way, because you want them to like you or give you something奉承, 讨好
exclusive: available or belonging only to particular people, and not shared独占的, 唯一的
fossilization: 化石作用
paleontologist: 古生物学者
highlight: to make a problem or subject easy to notice so that people pay attention to it加亮
sap: the watery substance that carries food through a plant树液
harden: to become firm or stiff, or to make something firm or stiff OPP soften使变硬
mountaintop: the top part of a mountain山顶
prairie: a wide open area of fairly flat land in North America which is covered in grass or wheat大草原
bury: to put something under the ground, often in order to hide it埋葬
scavenge: if someone scavenges, they search through things that other people do not want, for food or useful objects以(腐肉)为食
bog: an area of low wet muddy ground, sometimes containing bushes or grasses ⇨ marsh, swamp沼泽
shallow: measuring only a short distance from the top to the bottom OPP deep浅的, 浅薄的
muddy: covered with mud or containing mud多泥的, 泥泞的
sandy: covered with sand, or containing a lot of sand沙的
sediment: solid substances that settle at the bottom of a liquid沉淀物
permineralization: 完全矿化
mineral-rich: 富含矿物质
microscopic: extremely small and therefore very difficult to see用显微镜可见的
pore: one of the small holes in your skin that liquid, especially ↑sweat, can pass through, or a similar hole in the surface of a plant毛孔, 小孔, 气孔
subduct: 将（眼睛等）向下拉；撤去，除去，减去
surroundings: the objects, buildings, natural things etc that are around a person or thing at a particular time环境
erosion: the process by which rock or soil is gradually destroyed by wind, rain, or the sea腐蚀, 侵蚀
intrepid: willing to do dangerous things or go to dangerous places – often used humorously SYN brave无畏的, 勇猛的
amateur: someone who does an activity just for pleasure, not as their job OPP professional业余爱好者
fortuitous: happening by chance, especially in a way that has a good result偶然的, 幸运的
magnificent: very good or beautiful, and very impressive华丽的, 高尚的, 宏伟的
shed: GET RID OF to get rid of something that you no longer need or want摆脱
disintegrate: to ak up, or make something ak up, into very small pieces(使)分解, (使)碎裂
plate tectonics: 版块构造
--------------------
imagine doing/being sth.: 想象做某事/成为某物
inspire awe in sb.: 激起某人的惊叹
hordes of sb.: a large unorganized group of individuals成群的某人
forget about sth.: 忘记某事
listen up: 仔细听
(in) the Hall of sth. Fame: 名人堂
at some point: at an unspecified moment在某个时间点
get to sth.: 到达
A turn into B: be transformed into or become a particular kind of thing or person A变成B
survive intact: not broken or damaged完好无损地存活或幸存下来
sp. remain the domain of sb.: 遗留为某人的领地
The right place to be if you want to do sth. is wherever + ...: 你想做某事的正确地方是无论哪里...
hang around: to pass time idly or in relaxing or socializing闲逛
slow down (<-> sth.): 减缓
decay away: 逐渐腐烂
give you more time to do sth.: 给你更多的时间做某事
be lucky enough to do sth.: 有幸做某事
What's your next move: 你下一步要做什么
get saturated with sth.: to fill completely with something充满某物
Bit by bit: 一点点
precipitate out of these waters: 从水中析出
hope sb. do sth.: 希望某人做某事
create a perfect cast of sth.: 创造了某物的完美模型
You're not in the clear yet: 你还不能放松
a mountain range: 山脉
erode away sth.: 侵蚀消失某物
Fingers crossed + ...will: 希望成功+...
get gently lifted up: 被抬起
wipe away sth.: to remove (something) by rubbing擦去某物
scout for sth.: 搜寻，寻找
hope for sth.: 希望得到某物
whack away: 凿穿
in a creek bank: 小溪岸边
millions of years in the making: 历经数百万年形成
extract A from B: 从B中提取A
begin the complex task of doing sth.: 开始某事的复杂任务
in obscurity: 默默无闻
work oneself to the bone: to work extremely hard, especially for a long time拼命工作
hold that pose: 保持这个姿势
** 2014-02-12 The history of marriage
[[./TED-Ed/2014-02-12 The history of marriage.html]]
inspirational: providing encouragement or new ideas for what you should do 给予灵感的
hilarious hilariously: extremely funny滑稽的
cynical: 愤世嫉俗的
timeless: literary continuing for ever永恒的
humanity: people in general人性, 人类
sedentary: technical a sedentary group of people tend always to live in the splace不移栖的
simultaneous: things that are simultaneous happen at exactly the stime同时的, 同时发生的
adultery: sex between someone who is married and someone who is not their wife or husband通奸
demographic: 人口统计学的
ruler: someone such as a king or queen who has official power over a country or area统治者
concubine: a woman in the past who lived with and had sex with a man who already had a wife or wives, but who was socially less important than the wives 妾妾, 情妇
commoner: 平民
monogamy: 一夫一妻制
arrangement: 安排
prayer: words that you say when praying to God or gods祈祷
explicitly: expressed in a way that is very clear and direct ⇨ implicit明白地, 明确地
Adelphopoiesis: 兄弟结义
chapel: the religious services held in a chapel小礼拜堂
deceased: the deceased someone who has died, especially recently已故的
conduct: to carry out a particular activity or process, especially in order to get information or prove facts实施
lineage: 血统 
appease: make someone less angry or stop them from attacking you by giving them what they want安抚
restless: 不安宁的
young: 尚早的
practicality: 实用性
upperclass: 上层社会
industrialization: when a country or place develops a lot of industry工业化
urbanization: 都市化
household: 家庭
pursuit: when someone tries to get, achieve, or find something in a determined way ⇨ pursue追求
Pair bonding: 配对
----------------------------------------
what sb.(pl) have in common is that + ...: 某人(复数)的共同点是……
vary greatly between sth.(pl): 在事物中有很大的不同
take a quick look at sth.: express that you quickly glanced at something快速看一看某物
With the rise of sth.: 随着...的兴起
be a way of doing sth.: 某事是做某事的一种方法
secure rights to sth.: 保护有某物的权力
under certain circumstances: 在某些特殊环境下
designate A as B: 把A指派为B
a matter between sth.(pl): 关于某事的事情
be governed by: 受……支配/统治
punishments for sth.: 对某事的惩罚
the legal status of sb.: 某人的法律地位/身份
be born to sb.: 为某人所生
a quarter of sth.: 四分之一
the link between sth.(pl): 某事的联系
in practice: 实际上
the tables were turned: 形势逆转了
have relationships with sb.: 与某人有关系
in public ceremonies: 在公共仪式上
at stake: 利害攸关
became independent from sb./sth.: 独立于
be encouraged by: 被...鼓励
focus on A rather than B: 聚集于A而不是B
ease restrictions on sth.: 放松对某事的限制
be shaped by sth.: 受...影响
** 2014-04-18 Not all scientific studies are created equal
[[./TED-Ed/2014-04-18 Not all scientific studies are created equal.html]]
herb: a small plant that is used to improve the taste of food, or to make medicine ⇨ spice药草, 香草
liver: a large organ in your body that produces ↑bile and cleans your blood肝脏
vitamin: a chemical substance in food that is necessary for good health维生素
headline: the title of a newspaper report, which is printed in large letters above the report大字标题
attention-grabbing: 引人注意的
promising: showing signs of being successful or good in the future有前途的
dietary: related to the food someone eats饮食的
randomize: to choose things in a way that is not carefully controlled or planned in order to do a scientific test随机化
clinical: relating to treating or testing people who are sick临床的, 病房用的
trial: a process of testing to find out whether something works effectively and is safe试验, 审判
rigorous: careful, thorough, and exact严格的
medication: medicine or drugs given to people who are ill药物
placebo: a harmless substance given to a sick person instead of medicine, without telling them it is not real安慰剂
overall: considering or including everything全部的, 全面的
epidemiology/epidemiological: the study of the way diseases spread, and how to control them流行病学
nausea: the feeling that you have when you think you are going to ↑vomit (=bring food up from your stomach through your mouth) SYN sickness恶心
cohort: technical a group of people of the sage, social class etc, especially when they are being studied一群
substance: a particular type of solid, liquid, or gas物质
inherent: a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
flaw: a mistake, mark, or weakness that makes something imperfect SYN defect缺点
confounding: to confuse and surprise people by being unexpected混淆
pitfall: a problem or difficulty that is likely to happen in a particular job, course of action, or activity缺陷
eliminate: to defeat a team or person in a competition, so that they no longer take part in it SYN knock out淘汰
critical: something that is critical is very important because what happens in the future depends on it SYN crucial极其重要的
hazard: something that may be dangerous, or cause accidents or problems风险
asbestos: 石棉
Lead: 铅
cure: a medicine or medical treatment that makes an illness go away治愈
--------------------
Studies have shown that + ...: 研究证明
be bombarded with sth.: 被某物轰炸
be backed up by sth.: 被某物堆积
point the way towards sth.: 指出去某物/处的路
be assigned to sth./ assign sb. to sth.: 被分派到(组/队)
with headaches: 患头痛
be divided into sth.: 被分成...
a comparison group of ...: ...的对照组
have exposure to sth.: 接触某物
establish causal relationships between sth.(pl.): 建立某物之间的因果关系
in addition to: 除...之外
be combined with sth.: 与...结合
go out of sb's way to do sth.: 给自己带来不便或额外的麻烦去做超出要求的事情
take steps (to do sth.): 采取措施(去做某事)
induce changes within ...: 在...内部引起变化
demonstrate a correlation between sth.(pl.): 说明了事物间的相互关系
At the end of the day: 最终
alert sb. to sth.: 提醒某人注意某事
** 2014-05-15 How the heart actually pumps blood
[[./TED-Ed/2014-05-15 How the heart actually pumps blood.html]]
serve: to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应
thump: if your heart thumps, it beats very strongly and quickly because you are frightened or excited砰然地响
pump: to make liquid or gas move in a particular direction, using a pump泵
perish: formal or literary to die, especially in a terrible or sudden way毁灭
opaque: opaque glass or liquid is difficult to see through and often thick不透明的
crude: not exact or without any detail, but generally correct and useful ⇨ approximate粗略的
demonstrate: to show or describe how to do something or how something works示范
label: to use a word or phrase to describe someone or something, but often unfairly or incorrectly贴标签(贬)
grasp: to completely understand a fact or an idea, especially a complicated one掌握, 领会
potentially: something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals.哺乳动物
morphology: the structure of an object or system or the way it was formed形态学
signal: to make a sound or an action in order to give information or tell someone to do something信号
intimidate intimidating: making you feel worried and not confident胁迫,令人不安的(adj.)
complicated: difficult to understand or deal with, because many parts or details are involved SYN complex复杂的
medic: 实习医生
motion: the process of moving or the way that someone or something moves运动
immerse: to put someone or something deep into a liquid so that they are completely covered沉浸
squeeze: to press something firmly together with your fingers or hand压榨
mechanism: part of a machine or a set of parts that does a particular job机械装置
remaining: the remaining people or things are those that are left when the others have gone, been used, or been dealt with残留
superficial / superficially: not studying or looking at something carefully and only seeing the most noticeable things浅薄的
column: a tall solid upright stone post used to support a building or as a decoration圆柱
tap: a piece of equipment for controlling the flow of water, gas etc from a pipe or container水龙头
spectacular/spectacularly: very impressive引人入胜的, 壮观的
parachute: a piece of equipment fastened to the back of people who jump out of planes, which makes them fall slowly and safely to the ground降落伞
leak: if a container, pipe, roof etc leaks, or if it leaks gas, liquid etc, there is a small hole or crack in it that lets gas or liquid flow through泄漏
seamless seamlessly: 无缝地
unfold: if you unfold something that was folded, or if it unfolds, it opens out显露
rhythmical: having a strong rhythm节奏的
dependable: able to be trusted to do what you need or expect可靠的
caffeine: 咖啡因
four-chambered: 四腔的
dual-circulation: 双循环
atria: 心房
ventricle / ventricular: 心室
vein: 静脉
artery: one of the tubes that carries blood from your heart to the rest of your body ⇨ vein动脉
aorta: the largest ↑artery that takes blood away from your heart大动脉
pulmonary: 肺部的
tricuspid: (心脏的)三尖瓣
mitral: (心脏的)二尖瓣
blood vessels: 血管
heart valves: 心脏瓣膜
----------------------------------------
For most of history: 在历史大部分时间里
have no idea + ...: 不知道...
feel sb's heart beating: 感受某人的心跳
in surgery teams: 在外科医生团队
point to sth.: 指向指出某物
It's as if + ...: 似乎
Meaning that + ...: 意味着...
the next best thing is to do sth.: 下一个最好的办法是做某事
cut it open: 切开
in reality: 实际上
goes from sp.A to sp.B, back to sp.C: 从A出发到B,再回到C
make sb. wary of sth.: 使得某人提防某事
end up doing sth.: 最终做某事
That's when + ...A + as + ...B: 这是当B发生时A发生的时候.
What you (will) need to get started is sth.: 你需要开始的事是某事
do A enough for sb. to do B: 做A足够让某人去做某事
trim sth. down (to sp.): 删减某物到...
rise from sth.: 起源于...
run water into sp.: 把水流进...
close against sth.: 对某物关闭
inflate with sth.: 用某物膨胀
squirt out of sth.: 从某物喷出
with very little wear and tear: 非常少的磨损
give new resonance to sth.: 使...产生新的共鸣
run a race: 参与田径比赛
catch the eye of sb.: 引起某人的注目
** 2014-05-05 The science of attraction
[[./TED-Ed/2014-05-05 The science of attraction.html]]
spontaneous: something that is spontaneous has not been planned or organized, but happens by itself, or because you suddenly feel you want to do it自发的, 自然产生的
indescribable: it is too difficult to describe难以形容的
poetic: 诗歌的
fuzzy: unclear or confused OPP clear模糊的
veto: to refuse to accept a particular plan or suggestion否决
budding: beginning to develop萌芽的
component: one of several parts that together make up a whole machine, system etc SYN constituent成分
fertility: the ability of the land or soil to produce good crops肥沃
lustrous: shining in a soft gentle way有光泽的, 光辉的
reproductive: relating to the process of producing babies, young animals, or plants生殖的
fitness: when you are healthy and strong enough to do hard work or play sports适当
cologne: 科隆香水
pheromones: 信息素
physiology physiologyical: the science that studies the way in which the bodies of living things work生理学
recipient: someone who receives something接受者
saliva: the liquid that is produced naturally in your mouth SYN spit口水
testosterone: the ↑hormone in males that gives them their male qualities睾丸激素
odor: a smell, especially an unpleasant one气味
breathy: 缺少声量的
formant spacing: 共振峰间距
hypothetical: based on a situation that is not real, but that might happen假设的
unaffectionate: 没有感情的
infamous: well known for being bad or evil声名狼籍的
tactile: relating to your sense of touch触觉的
cue: 暗示
tunnel vision: 视野狭隘(引申义:封闭思想)
bloodstream: the blood flowing in your body血流
dilate: if a hollow part of your body dilates or if something dilates it, it becomes wider扩大
glucose: 葡萄糖
warp: 扭曲
----------------------------------------
think of A as B: 认为A是B
perceive A as B: 把A当作B
run a (complex) series of calculations: 进行一系列(复杂)的运算
within a matter of seconds: 在几秒钟之内
sounds quite as adj.: 听起来很像
Just because +... doesn't mean + ...:  仅仅因为 +...并不意味着 +...
all num. of sth.: 某物的全部几个
play a role in doing sth./sth.: 在某事上起作用
be in demand: 是需要的
pick up on sth.: 注意到某事
In one study: 在一项研究中
in sb's ovulation cycle: 在某人的排卵周期内
be randomly assigned to do sth.: 被随机派遣做某事
give sb. the nudge to do sth.: 给某人动力去做某事
be particularly attuned to sth.: 对某事非常熟悉 be familiar with
differ from sth.: 不同于某事某物
result in sth.(death/failure/contradiction): 导致某事
be correlated with sth.: 和某事相关
rate sb's personality: 评价某人的性格
lose sb's attraction to sb.: 丢失对某人的吸引力
be flooded with sth.: 被某事淹没
activate (sb's fight/flight/immune) system: 激活...系统
+..., not because +...,but because + ...: ...,不是因为..., 而是因为...
block out sth.: 遮挡
enhance sb's memory: 增强某人的记忆力
This might explain why + ...: 这可能解释了为什么
play matchmaker: 做媒
** 2014-05-06 What is the world wide web
[[./TED-Ed/2014-05-06 What is the world wide web.html]]
interchangeabe/interchangeably: things that are interchangeable can be used instead of each other可互换的
conference: a large formal meeting where a lot of people discuss important matters such as business, politics, or science, especially for several days讨论会, 协商会
skyscraper: a very tall modern city building摩天楼
know-how: knowledge, practical ability, or skill to do something实际经验
domain: an area of land owned and controlled by one person or government, especially in the past领域
virtual: made, done, seen etc on the Internet or on a computer, rather than in the real world虚的
hosting: to provide the place and everything that is needed for an organized event托管 
registrar: 登记员 
loose: not firmly fastened in place宽松的
interconnect: if two systems, places etc are interconnected, or if they interconnect, they are joined together使互相连接
mirror: if one thing mirrors another, it is very similar to it and may seem to copy or represent it SYN reflect反映, 映出
arrangement: 排列, 安排
hyperlink: a word or picture in a ↑website or computer document that will take you to another page or document if you ↑click on it超链接
encounter: to experience something, especially problems or opposition遭遇
reflect: to show or be a sign of a particular situation or feeling反射, 反映, 表现
boundary: the real or imaginary line that marks the edge of a state, country etc, or the edge of an area of land that belongs to someone边界, 分界线
ethnicity: 种族划分
----------------------------------------
be likely doing: 可能正在做某事
be used by sb. for sth.: 被某人使用做某事
chat with sb.: 和某人闲聊
use it from sth.: 通过某物用它
first of all: 首先
made a call to sb.: 打电话给某人
be all around sb.: 就在某人身边
There's another part to doing sth., without which + ...: 做某事还有令一部分, 没有它...
with no way of doing sth.: 没有办法做某事
a graphic interface: 一个图形界面
utility company: 共同服务公司
lie in sth.: 在于某事
be prior to sth.: 在...之前
in a linear fashion: 线形方式
in a straight line: 笔直地
redirect sb. to sp.: 重定向某人到某地
in content and structure: 在内容和结构上
** 2014-05-30 How does your brain respond to pain
[[./TED-Ed/2014-05-30 How does your brain respond to pain.html]]
stimulus: something that helps a process to develop more quickly or more strongly刺激
matter: v. to be important, especially to be important to you, or to have an effect on what happens有关系
sensory: relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
tissue: the material forming animal or plant cells组织
intensity: technical the strength of something such as light or sound强度
sharp: a sharp pain or feeling is sudden and severe OPP dull锐利的
dull: a dull pain is not severe but does not stop OPP sharp感觉或理解迟钝的
perception: the way you think about something and your idea of what it is like理解
damage-sensing: 疼痛感知
nociceptor: 伤害感受器
spinal cord: 脊髓
neuron: a type of cell that makes up the ↑nervous system and sends messages to other parts of the body or the brain SYN nerve cell神经元
glia: 神经胶质
superhighway: a very large road on which you can drive fast for long distances超级高速公路
electrical impulses: 电子脉冲
pathway: a path路
cortex: the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
salient / salience: the salient points or features of something are the most important or most noticeable parts of it易见的
modulate / modulation: to change a process or activity to make it more controlled, slower, less strong etc调制
endorphin: a chemical produced by your body that reduces pain and can make you feel happier内啡肽
enkephalin: 脑啡肽
regulate: to control an activity or process, especially by rules管制, 控制
sensitivity: 敏感, 灵敏(度), 灵敏性
efficacy: formal the ability of something to produce the right result SYN effectiveness OPP inefficacy功效, 效验
brain circuits: 脑回路
variable / variability: likely to change often ⇨ vary 可变性
roller coasters: 过山车
motion: the process of moving or the way that someone or something moves动作
target: to make something have an effect on a particular limited group or area针对
mild: a mild illness or health problem is not serious温和的
non-prescription: a non-prescription drug is one that you can buy in a shop without a written order from a doctor SYN over-the-counter无处方
anesthetic: a drug that stops you feeling pain麻药
severe: severe problems, injuries, illnesses etc are very bad or very serious严厉的
chronic: a chronic disease or illness is one that continues for a long time and cannot be cured ⇨ acute慢性的, 延续很长的
stimulate: 刺激, 激励
pain-sensing: 感受痛觉的
map: v. to discover or show information about something, especially about its shape or arrangement, or how it moves or works映射
personalize / personalized: to design or change something so that it is suitable for a particular person使成私人的
----------------------------------------
receive electric shocks to sb's hands/arms: 某人的手/胳膊受到点击
distract sb. from sth.: 分散某人对于某事的注意
do sth. faster and better when +... than when +...: 做某事更好快当A比当B
send sb's mind wandering: 使某人心烦意乱
be subjected to sth.: 遭受某事
describe sth. on a scale from A to B: 用从A到B程度来描述某物
respond to sth.: 对某事作出反应
cope with sth.: 应对某事
take sb. hand off sth.: 把某人的手从某物上拿开
act on sth.: 对...起作用
along with ways to do sth.: 伴随着做某事的方法
tailor sth. to sb.: 为某人量身定做
the key to doing sth.: 做某事的关键
** 2014-06-03 How to choose your news
[[./TED-Ed/2014-06-03 How to choose your news.html]]
absorb: to read or hear a large amount of new information and understand it吸收
broad-based: 基础深厚的
newspaper of record: 主流报纸
authoritarian: strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
censor: to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
scandal: talk about dishonest or immoral things that famous or important people are believed to have done丑闻
covert: secret or hidden隐蔽的
assassination: the act of murdering an important person暗杀
corruption: dishonest, illegal, or immoral behaviour, especially from someone with power贪污
narratives: a description of events in a story, especially in a ↑novel叙述
mainstream: the mainstream the most usual ideas or methods, or the people who have these ideas or methods主流
gatekeeper: someone whose job is to open and close a gate, and to allow or not allow people to go through it
outlet: a pipe or hole through which something such as a liquid or gas can flow out出路
unfiltered: 未滤过的
protest: something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products抗议
blog / blogger: a web page containing information or opinions from a particular person or about a particular subject, to which new information is added regularly SYN web log博客
polished: polite, confident, and graceful 精练的, 优美的
chaotic: a chaotic situation is one in which everything is happening in a confused way混乱的
terrorist: someone who uses violence such as bombing, shooting etc to obtain political demands恐怖分子
coverage: when a subject or event is reported on television or radio, or in newspapers报道
accusation: a statement saying that someone is guilty of a crime or of doing something wrong谴责
refute: to prove that a statement or idea is not correct SYN rebut驳倒, 反驳
bias: an opinion about whether a person, group, or idea is good or bad that influences how you deal with it偏见
anonymity: when other people do not know who you are or what your name is匿名
rumor: information or a story that is passed from one person to another and which may or may not be true流言
falsehood: a statement that is untrue SYN lie谎言
outrageous: very shocking and extremely unfair or offensive骇人的
curate: organize操持
flow: 流动
----------------------------------------
a click away: 用鼠标点击一下
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
compete with sb.: 同某人竞争
from various perspectives: 从各种各样的视角
More recently: 更近期地
multiply the amount of sth.: 倍增某物的数量
sb. keeps in mind that + ...: 某人牢记...
in real time: 实时
at several points in the day: 在一天的几个点
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
aim for sth.: 争取某物
tuning in to sth.: 收听某事
take a guess: 做猜测
watch out for sth.: 小心提防
have little connection to sth./sb.: 和某事/某物没关系
make sb. unaccountable for sth.: 使某人对于某物没有责任
with A comes B: 伴随A来的B
ensure that + ...: 确保...
leave sb. less informed than before + ...: 让某人比...之前更加无知
took the plunge: 冒险
** 2014-11-05 Why elephants never forget
[[./TED-Ed/2014-11-05 Why elephants never forget.html]]
walking hard drive: 移动硬盘
magnificent: very good or beautiful, and very impressive宏伟的
benevolent: kind and generous慈善的
proverb: a short well-known statement that gives advice or expresses something that is generally true.谚语
accurate: correct and true in every detail正确的, 精确的
encounter: to experience something, especially problems or opposition遭遇
hostile: angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
recall: to remember a particular fact, event, or situation from the past回想
herd: 兽群
companion: someone you spend a lot of time with, especially a friend同伴
drought: 干旱
circus: a group of people and animals who travel to different places performing skilful tricks as entertainment马戏团
rejoice: literary to feel or show that you are very happy(使)欣喜
boast: if a place, object, or organization boasts something, it has something that is very good以有...而自豪
encephalization quotient: Brain-To-Body脑化指数
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals哺乳动物
converge/convergent: to come from different directions and meet at the spoint to become one thing会聚
synapse: the place where nerve cells meet, especially in the brain突触
developed: a developed sense, system etc, is better, larger, or more advanced than others发达
hippocampus: 海马体
cerebral: medical relating to or affecting your brain大脑的
recollection: something from the past that you remember回忆
faculty: a natural ability, such as the ability to see, hear, or think clearly本能
rote: formal when you learn something by repeating it many times, without thinking about it carefully or without understanding it死记硬背, 机械的做法, 生搬硬套
clan: a large group of families who often share the namies部落
matriarch: a woman, especially an older woman, who controls a family or a social group女家长
cooperative/cooperatively: willing to cooperate SYN helpful OPP uncooperative合作的
outwit: to gain an advantage over someone using tricks or clever plans瞒骗, 以智取胜
manipulate: to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them操作
post-traumatic stress disorder: 创伤后压力紊乱
arithmetic: the science of numbers involving adding, multiplying etc算术, 算法
vocalize/vocalization: to make a sound or sounds with your voice成为有声
infrasound: 次声
rumble: a series of long low sounds隆隆声
syntax: the way words are arranged to form sentences or phrases, or the rules of grammar which control this句法
tone: the way your voice sounds, which shows how you are feeling or what you mean语调
recreate: to make something from the past exist again in a new form or be experienced again SYN recapture再创造
melody: a song or tune悦耳的音调
altruism: when you care about or help other people, even though this brings no advantage to yourself利他
mourn: to feel very sad because something no longer exists or is no longer as good as it used to be哀悼
burial ritual: 葬礼仪式
log: a thick piece of wood from a tree原木
trunk: the very long nose of an ↑elephant象鼻
massive: very large, solid, and heavy厚重的, 大块的, 魁伟的, 结实的
poach: to do something that is someone else’s responsibility, especially when they do not want you to do it偷猎
cull: to kill animals so that there are not too many of them, or so that a disease does not spread猎杀
revenge: something you do in order to punish someone who has harmed or offended you复仇
ivory: the hard smooth yellowish-white substance from the ↑tusks (=long teeth) of an ↑elephant象牙
----------------------------------------
It's a common saying that + ...: 常言道...
it appears that + ...: 看起来似乎
as many as num. sth.: 多达num.个
make a strong impression on sb.: 给某人造成深刻的印象
In one case: 在某种情况下
cross paths (with sb.): (与某人)相遇
sth. isn't limited to sb.: 某物/能力不限于某人
after days/months/years/decades apart: 几十年分别之后
go beyond sth.: 超过某物
encode A into B: 把某物A编入某物B
in adulthood: 在成年期
tackle problems: 解决问题
keep track of sth.: 跟踪某事
shown concern for sth./sb.: 爱护某人/物
stand guard: 站岗守卫
comfort sb. with sth.: 用某物安慰某人
it's hard to escape the conclusion that + ...: 很难不得出结论...
in captivity: 在关押
Given what + ...: 鉴于...
It is more important than ever to do sth.: 做某事比以往任何时候更重要
vanish from sp.: 从...消失
** 2014-12-18 What is a gift economy
[[./TED-Ed/2014-12-18 What is a gift economy.html]]
knit: to make clothing out of wool, using two ↑knitting needles编织
adopt: to take someone else’s child into your home and legally become its parent采用
contradictory: two statements, beliefs etc that are contradictory are different and therefore cannot both be true or correct矛盾因素, 对立物
obligation: a moral or legal duty to do something义务
social ties: 社交关系
canoe: a long light boat that is pointed at both ends and which you move along using a paddle独木舟
potlatch: 冬节
chief: the most important person, or one of the most important people, in a company or organization – used especially in job titles and in news reports首领
livestock: animals such as cows and sheep that are kept on a farm家畜
blanket: a cover for a bed, usually made of wool ⇨ duvet毯子
participant: someone who is taking part in an activity or event参与者
barter: to exchange goods, work, or services for other goods or services rather than for money物品交换
haggle: to argue when you are trying to agree about the price of something争价
norm: generally accepted standards of social behaviour标准, 规范
reciprocity: a situation in which two people, groups, or countries give each other similar kinds of help or special rights互惠
voluntarily: if you do something voluntarily, you do it willingly, without anyone telling you to do it志愿地
prestige: the respect and admiration that someone or something gets because of their success or important position in society声望
communal: shared by a group of people or animals, especially a group who live together公共的
taboo: a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing禁忌、避讳
financial: relating to money or the management of money财政的
potluck dinner: 自备餐
prevail: if a belief, custom, situation etc prevails, it exists among a group of people at a certain time流行
anthropology/anthropologist: the scientific study of people, their societies, cultures etc人类学
native: a person who was born in a particular place本地人
----------------------------------------
This holiday season: 这个假期
consign sth. to the closet: 把某物放入壁橱
expect sth. from sb.: 期待某人某物
become/ be involved in: 涉及到...
for free: adv.免费
without explicit conditions: 没有明显的条件
foster a system of sth.: 培养某事物的体系
be formed by: consist of由……组成
throughout human history: 贯穿人类历史
describe sb. doing sth.: 描述某人做某事
make a journey: 进行一次旅行
do sth. through this process: 通过这个过程做某事
carry an obligation to do sth.: 承担做某事的义务
give away sth.: 赠送某物
obligate sb. to do sth.: 迫使某人做某事
return the favor: 回报恩惠
take many forms: 多种形式
at sb's expense: 以某人的费用
gain sth. from sb./sth.: 从某人某物获得某物
be indebted to sb.: 对某人深表感激
be read as doing sth.: be regarded as被认为做某事
be exclusive to sth.: 专属于某物
social pay off: 社会回报
miss the point: 错过重点
** 2015-01-30 Why are some people left-handed
[[./TED-Ed/2015-01-30 Why are some people left-handed.html]]
left-handed: a left-handed person uses their left hand for writing, throwing etc OPP right-handed
proper: right, suitable, or correct左撇子
1/10: one-tenth
artifact: 历史文物
fetus: 胎儿
inborn: an inborn quality or ability is one you have had naturally since birth天生的
genetic: relating to ↑genes or ↑genetics遗传的, 起源的
identical: exactly the same, or very similar同一的
gene: 基因 
dominant: more powerful, important, or noticeable than other people or things支配的
consistent: 一致的
ratio: a relationship between two amounts, represented by a pair of numbers showing how much bigger one amount is than the other ⇨ proportion比率
odds: the odds how likely it is that something will or will not happen几率
millennium/millennia:a period of 1,000 years一千年
theory: 理论,假设hypothesis
competitive: determined or trying very hard to be more successful than other people or businesses ⇨ compete, competitor竞争的
competitor: 竞争者
combat: fighting, especially during a war战斗, 格斗
hitter: [棒球]击球员
hypothesis: an idea that is suggested as an explanation for something, but that has not yet been proved to be true SYN theory假设
athletes: someone who competes in sports competitions, especially running, jumping, and throwing运动员
frequency-dependent: 频率相关的
asset: the things that a company owns, that can be sold to pay debts资产
distribution: 分布状态
majority: 多数
equilibrium: a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly平衡
intrigue intriguing: something that is intriguing is very interesting because it is strange, mysterious, or unexpected SYN fascinating阴谋, 有迷惑力的
skewed: an opinion, piece of information, result etc that is skewed is incorrect, especially because it has been affected by a particular thing or because you do not know all the facts曲解的
pawedness: 爪侧性,对左爪或右爪的偏好
hunter-gatherer: 狩猎采集者
puzzle: 难题
----------------------------------------
chances are + ...: 很可能...
in many parts of the world: 在世界各地
the word for A: A这个单词
in the first place: 首先 For one thing
show evidence of sth./doing sth.: 显示做某事的证据
in the womb: 在子宫里
have a 17% chance of doing/being sth.: 有17%的机会做某事
be born adj.: 与生剧来...
by a roll of the dice: 靠投塞子
It implies that + ...: 这意味着...
over the course of millennia: 经过数千年的时间
The benefits of doing sth.: 做某事的好处
a minority to do sth.: 做某事的少数人
be thrown off: 被抛弃
lead to sb. doing sth.: 导致某人做某事
in the opposite direction: 朝相反方向
disappear from: 从...消失
play out: 发展,演变
simultaneously over time: 同时随着时间的推移
in sb's hands: 在某人手中
** 2015-03-12 Plato’s Allegory of the Cave
[[./TED-Ed/2015-03-12 Plato’s Allegory of the Cave.html]]
figurative/figuratively: 比喻的
thread: an idea, feeling, or feature that connects the different parts of an explanation, story etc线索
flicker: 摇曳, 闪烁
flit: to move lightly or quickly and not stay in one place for very long迁徙
cheery: happy or making you feel happy
allegory: a story, painting etc in which the events and characters represent ideas or teach a moral lesson寓言
Republic: a country governed by elected representatives of the people, and led by a president, not a king or queen共和国
envision: to imagine something that you think might happen in the future, especially something that you think will be good想象, 预想
cavern: a large ↑cave巨洞
faint: difficult to see, hear, smell etc虚落地
cast: literary to make light or a shadow appear somewhere投射
classify: to decide what group something belongs to分类
perceive: formal to notice, see, or recognize something ⇨ perceptive感知
entity: formal something that exists as a single and complete unit ⇨ being实体
disorienting: confusing you and making you not certain about what is happening around you使失去方向感, 使迷惑
reflection: an image that you can see in a mirror, glass, or water映象
adjust: to change or move something slightly to improve it or make it more suitable for a particular purpose调整
blind: unable to see瞎的
ignorance: lack of knowledge or information about something无知
disrupt: to prevent something from continuing in its usual way by causing problems使中断
disparaging: criticizing someone or something, and showing that you do not think they are very good or important蔑视的
promote: to try to persuade people to support or use something促进
rule: the government of a country or area by a particular group of people or using a particular system统治
parable: a short simple story that teaches a moral or religious lesson, especially one of the stories told by Jesus in the Bible寓言
stubborn: determined not to change your mind, even when people think you are being unreasonable顽固的
ignorant: not knowing facts or information that you ought to know无知的
dialogue: a conversation in a book, play, or film对话
flawed: spoiled by having mistakes, weaknesses, or by being damaged有缺陷的
roundness: 园
fundamental: very necessary and important基础的, 基本的
representation: 表现
theologian: someone who has studied theology神学者
linguistic: related to language, words, or linguistics语言上的
concrete: 具体的, 有形的
abstract: 抽象的
assumption: something that you think is true although you have no definite proof ⇨ assume假定
consolation: something that makes you feel better when you are sad or disappointed安慰
----------------------------------------
explain A as B: 把A解释为B
be like doing sth.: 就像是做某事
be chained up: 被锁起来
face a wall: 面对墙壁
give off: 发出(亮光)
pass by sb./sth.: 经过某人某物
have a hard time doing sth.: 做某事很困难
resist an attempt to do sth.: 抵制做某事的企图
introduce A as an analogy of B: 解释A当作B的比喻
be hostile to sb.: 对某人有敌意
the real life: 真实生活中
be sentenced to death/imprisonment: 被判处死刑
capture imaginations: 引起想象
view A as B: 把A看作是B
group A under B: 把A归类为B
go about sth.: 忙于某事
a glimmer of light: 一丝光
punch a hole: 打孔
break free (from sth.): 从某事中解脱出来
stick with sth.: 坚持使用某事
** 2015-03-13 Can robots be creative
[[./TED-Ed/2015-03-13 Can robots be creative.html]]
composer: someone who writes music ⇨ composition作曲家
artificial: not real or not made of natural things but made to be like something that is real or natural SYN false OPP natural人造的,人工的
creativity: the ability to use your imagination to produce new ideas, make things etc创造力, 创造
intelligence: the ability to learn, understand, and think about things智能
mathematician: someone who studies or teaches mathematics, or is a specialist in mathematics数学家
programmer: someone whose job is to write computer programs程序师
formalize: to make a plan, decision, or idea official, especially by deciding and clearly describing all the details使正式
scrutinize: to examine someone or something very carefully细察
algorithm: technical a set of instructions that are followed in a fixed order and used for solving a mathematical problem, making a computer program etc运算法则
generator: something that produces something else发生器
fuzzy: unclear or confused OPP clear模糊的
yield: to produce a result, answer, or piece of information生产
countless: too many to be counted无数的, 数不尽的
outcome: the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
artistic: relating to art or culture艺术的
mutation: a change in the ↑genetic structure of an animal or plant that makes it different from others of the skind(生物物种的)突变
fitness: the degree to which someone or something is suitable or good enough for a particular situation or purpose适应,适当
ultimate: someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最后的, 最终的, 根本的
complexity: the state of being complicated复杂性, 复杂的事物
aesthetic: connected with beauty and the study of beauty美学
theoretically: 理论上
intuition: the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
anyways: =anyway 不管怎样
dynamo: a machine that changes some other form of power directly into electricity发电机
initiative: the ability to make decisions and take action without waiting for someone to tell you what to do主动
weep: or literary to cry, especially because you feel very sad哭泣
--------------------
grapple with the question of sth.: 努力解决某事的问题
program sth. to do sth.: 编程让某事做某事
propose a way of doing sth.: 提出做某事的方法
a sequence of sth.: 一连串的某事
a tiny fraction of sth.: 某物的极小一部分
approach to doing sth.: 做某事的方法
an initial population of sth.: 某物的初始种群
a new generation of sth.: 新一代的某物
be weeded out: 被淘汰
the presence of sth.: 某物的存在
The jury may still be out: 目前还没有定论
blow your mind: 震撼你的思维
send shivers down your spine: 让你背脊发凉
** 2015-03-27 What causes bad breath
[[./TED-Ed/2015-03-27 What causes bad breath.html]]
curse:a word or sentence used to ask God or a magical power to do something bad to someone or something诅咒
plague: to cause pain, suffering, or trouble to someone, especially for a long period of time折磨
aromatic: having a strong pleasant smell SYN fragrant芬芳的
shell: the hard outer part that covers and protects an egg, nut, or seed壳
legal: if something is legal, you are allowed to do it or have to do it by law OPP illegal法定的, 合法
scourge: something that causes a lot of harm or suffering苦难的根源
halitosis: a condition in which someone’s ath smells very bad SYN bad breath口臭
feces: pl. solid waste material from the ↑bowels粪
microorganism: 微生物
moisture-rich: 湿气丰富的
vital:extremely important and necessary for something to succeed or exist SYN crucial至关重要的
digestion: the process of digesting food消化力
mucus: a thick liquid produced in parts of your body such as your nose粘液
food remnants: 残余
tissue: the material forming animal or plant cells组织
nutrient: a chemical or food that provides what is needed for plants or animals to live and grow营养
foul-smelling: 闻起来臭的
byproducts: 副产品
sulfide: 硫化物
cadaverine: 尸胺
unsuspecting: not knowing that something bad is happening or going to happen不怀疑的
intimate: private and friendly so that you feel comfortable亲密的
primal: primal feelings or actions seem to belong to a part of people’s character that is ancient and animal-like原始的
gram-negative: 革兰氏(染色)阴性
antibacterial: 抗菌的
mouthwash: 嗽口水
scraper: a tool used to remove something from a surface by rubbing刮刀
nasal: 鼻的
ailment: an illness that is not very serious疾病(尤指微恙)
diabete: a serious disease in which there is too much sugar in your blood糖尿病
excessive: much more than is reasonable or necessary过多的
alcohol consumption: 消费
originate:formal to come from a particular place or start in a particular situation起源, 发生
lick: to move your tongue across the surface of something in order to eat it, wet it, clean it etc舔
wrist: the part of your body where your hand joins your arm手腕
subjectively: 主观地
--------------------
resort to sth.: 诉诸于某事
grounds for sth.(divorce)/doing sth.: 做某事的理由
as disgusting as it may sound, ...: 虽然听起来很恶心,但...
feed off of sth.: 以某物为食
break down A into B: 把A分解成B
waft sb's way towards sp.: 飘荡到某地
interpretation of A as B: 把A解释为B
warn sb. of sth.: 警告某人某事
go on a date with sb.: 和某人约会
floss sb's teeth: 用牙线清洁牙齿
at bedtime: 睡前
in the first place: 最初
cup your hands over your mouth: 用手捂住嘴
be too acclimatized to sth. to do sth.: 
** 2015-05-15 Debunking the myths of OCD
[[./TED-Ed/2015-05-15 Debunking the myths of OCD.html]]
misconception: an idea which is wrong or untrue, but which people believe because they do not understand the subject properly SYN fallacy ⇨ preconception误解
meticulous meticulously: very careful about small details, and always making sure that everything is done correctly小心翼翼的
obsessive: thinking or worrying about something all the time, so that you do not think about other things enough – used to show disapproval强迫性的
compulsive: compulsive behaviour is very difficult to stop or control, and is often a result of or a sign of a mental problem ⇨ obsessive强制的, 强迫的
psychiatric: relating to the study and treatment of mental illness精神病学的
alike: very similar以同样的方式
repetitive: done many times in the sway, and boring重复的, 反复性的
ritualistic: ritualistic words or behaviour always follow the spattern, especially because they form part of a ritual仪式的
intrusive: affecting someone’s private life or interrupting them in an unwanted and annoying way打扰的
obsession: an extreme unhealthy interest in something or worry about something, which stops you from thinking about anything else痴迷
tendency: if someone or something has a tendency to do or become a particular thing, they are likely to do or become it倾向
debilitate debilitating: to make someone ill and weak使衰弱
distress: a feeling of extreme unhappiness悲痛
diagnostic: relating to or used for discovering what is wrong with someone or something诊断的
contamination: 污染
harm: to physically hurt a person or animal伤害
hygiene obsessed: 卫生着迷
clue: information that helps you understand the reasons why something happens线索
neurobiological: 神经生物学
serotonin: a chemical in the body that helps carry messages from the brain and is believed to make you feel happy血清素
neurotransmitter: 神经传递素
regulate: to control an activity or process, especially by rules控制, 调节
aggression: angry or threatening behaviour or feelings that often result in fighting进攻, 侵略
desensitize: to make someone react less strongly to something by making them become used to it使麻木
electroconvulsive: 电休克的
agonize agonizing: extremely painful痛苦难忍的
--------------------
plan out sth. to the last detail: 把某事计划到最后一个细节
debunk some myths: 破除一些迷思
A be synonymous with B: A于B同义
from time to time: 时不时地
have little or no control over sth.: 对某事几乎没有控制
interfere with sth. to the point of doing sth.: 干涉某事到做某事的地步
separates A from B: 从B分离A
manifest as sth.: 表现为...
preoccupations with sth.: 对某事的全神贯注
range from ... to ...: 从...到...的范围
quite well: 相当地
be hardwired to do sth.: 注定做某事
the underlying cause of sth.: 某事的根本原因
lie to sb.: 对某人说慌
** 2015-06-02 How people rationalize fraud
[[./TED-Ed/2015-06-02 How people rationalize fraud.html]]
trillion: the number 1,000,000,000,000 万亿
embezzle embezzlement: to steal money from the place where you work盗用, 挪用
insurance: 保险
triangle: a flat shape with three straight sides and three angles三角形
criminologist: 犯罪学者
rationalization: 合理化
addiction: the need to take a harmful drug regularly, without being able to stop沉溺, 上瘾
quota: an official limit on the number or amount of something that is allowed in a particular period限额
budget: the money that is available to an organization or person, or a plan of how it will be spent预算
fraudster: someone who has committed a fraud欺诈者
offenders: someone who is guilty of a crime罪犯
underpaid: earning less money than you deserve for your work所得报酬过低的
overworked: made to work too hard过度工作
victimless: 不侵害他人的
taxpayer: a person that pays tax纳税人
overbill: 超额收费
fabricate: to invent a story, piece of information etc in order to deceive someone捏造
falsify: to change figures, records etc so that they contain false information伪造
subsidiary: a company that is owned or controlled by another larger company子公司
corporate: belonging to or relating to a corporation公司的
governance: the act or process of governing管理
regulator:someone who makes sure that a system operates properly or fairly监督者
supervision: 监督
greed: a strong desire for more food, money, power, possessions etc than you need SYN avarice贪欲, 贪婪
quarter horse: 夸特马
breeder: someone who breeds animals or plants as a job饲者
finance: 金融
subsidize: if a government or organization subsidizes a company, activity etc, it pays part of its costs津贴
untangle: to make something less complicated解开
--------------------
lost [money] to sth.: 因某事损失钱
pyramid schemes: 金字塔骗局
be susceptible to sth.: 易受某事影响
commit fraud: 犯欺诈罪
make sth. likely: 使得某事可能
motivate sb. to do sth.: 激励某人去做某事
a sudden job loss: 突然失业
in the public/private sector: 在公有或私立部门
credit cards: 信用卡
on a daily basis: 每天
justify sth. to sb.: 向某人证明某事有理
feel entitled to sth.: 觉得有资格得到某物
resolve crisis: 解决危机
register as sth. to sb.: 对某人来说是某物
fudge expense reports: 捏造费用报告
report cash earnings: 报告先进收入
recoup losses/ losses be recouped: 弥补损失
divert money to sp.(an account): 把钱转到
go unnoticed: 不为人知的
run to sth.: 到达...
go bankrupt: 破产
to begin with: 在开始时
It is believed that + ...: 人们相信...
raise prices: 提高价格
be left doing sth.: 被留下做某事
* other(If they are too many, then split them)
** public speaking
feel nervous about doing sth.: 对做某事感到紧张
give a speech: 发表演讲
in good company: be in the same situation as someone important or respected不是一个人
suffer from sth.: 遭受
stage fright: nervousness before or during an appearance before an audience舞台恐惧
turn pale: their face looks a lighter color than usual, usually because they are ill, frightened, or shocked.脸色变白
at the outset of a speech: 在演讲开始时
quake in every limb and in my soul: 四肢和灵魂都在颤抖
report doing sth.: 报道做某事
speaking in public: 公众演讲
be nominated for: 被提名为
nerve-wracking experience: makes you feel very tense and worried非常伤脑筋的经验
in jest: 开玩笑
sb. be given a choice/give sb. a choice: 给某人一个选择
would rather do A than do B: 宁愿做A也不愿做B
give the eulogy: 致悼词

** the best life story
*** 01 Let him Go, Olivia
It's over.: 结束了
pass away: 去世
in recognition of sb.: 为了表彰某人
write this story as a tribute to sb.: 写这个故事以向某人致敬
make it possible for sb to have done: 使某人有可能做某事

*** 02 Lazy Summers
swoop: 向下猛冲
buzz: 嗡嗡
swat it away: 拍死它
bring a smile to my face: 让我脸上泛起微笑
A join in the chorus of B: A加入到B一起
have memories of:想起
swirl around: 盘旋在
reminisce (about): 缅怀

** Reading to Learn the Art of Expression
observant: good or quick at noticing things富有观察力的
clause: 子句
--------------------
biographical sketch: 传(记)略
forms of ...: ...的形式
from all over England: 来自英国各地
sb's aim is to do ...: 某人的目的是做……
receive treatment (from sb.): (从某人那里)接受治疗
at a time when ...: 在...的时候
stay adj.: 保持...

** humans of NewYork
*** 01 down to ride for you
be down to ride: support支持
*** 02 You're the best dad ever
pop up: 突然出现
what it's like: to be familiar with how it feels to be or do something它是什么样的?
rip out heart: 伤透了心
back off: 后退
get a flicker of: a feeling or expression of an emotion or quality that does not last very long得到一闪而过的

** Children’s Engineering Workshops.
workshop: 研习班
want some information about sth. :想要某物的信息
design a adj. cover that goes round sth. : 设计一个保护套包裹住某物
there is an opportunity for sb. to do sth.: 对某人有机会做某事
be amazed + ...: 对...吃惊
one thing sb. does is to do sth.:某人做的一件事是做某事
A be attached to B: B绑到A上
the force of air/water: 空气的力量
presumably: 估计是
advanced: 更高级的
construct A using B: 用B来构造A
pick sth. up: 某事进步
use A to do B: 用A来做B
come up with=think up an idea for sth.: 为某事想出主意
A in the shape of B: B形状的A
give sb. enough time to do sth.: 给某人足够的时间去做某事
up past sp.: 过了某处
enrol: 报名

** stoicism
achieve sb's triumphs: 取得某人的胜利
the likes of sth.: is used to refer to people or things of a similar type or category诸如此类事物
have access to sth.: possess the ability or permission to use, enter, or obtain something.能够获得某物
come to sb.: emphasizes the process of understanding or realization被某人想到
in turn: used to explain how a series of actions or circumstances are interconnected依次，轮流
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."关于某事物
put on ...: mean to organize, present, or perform a show, event, or production.上演
prime minister: the most important minister and leader of the government in some countries which have a parliament首相，总理
the course of ...: is used to describe the progression or development of something over a period of time.某事物的过程
at the root of sth.: refers to the fundamental or foundational essence of a concept, idea, problem, or situation在某事物的根源上
resonate with: if something such as an event or a message resonates, it seems important or good to people, or continues to do this与…产生共鸣
refer to A as B: regard sth. as sth. 把A称为B
* NCE2
** L01 A private conversation
[[./NCE2/L01 A private conversation.html]]
private: [ˈpraɪvət] adj.私人的
conversation: [ˌkɒnvəˈseɪʃ(ə)n] n.谈话
theatre: [ˈθɪətə(r)] n.戏院
seat: [siːt] n.座位
play: [pleɪ] n.戏
loudly: [ˈlaʊdli] n.大声地
angry: [ˈæŋɡri] adj.生气的
angrily: [ˈæŋɡrəli] adv.生气地
attention: [əˈtenʃ(ə)n] n.注意
bear: [beə(r)] v.容忍
business: [ˈbɪznəs] n.事
rudely: [ˈruːdli] adv.粗鲁地

have a conversation: 谈话
take a seat: 坐座位
Is the seat taken?: 这个位置被坐了吗
How can you bear that?: 你怎么忍受那个的?
Don't be rude: 别粗鲁
--------------------
6123456:
	 6: When
	 1: 主
	 2: 谓/系
	 3: 宾/表
	 4: how
	 5: where
	 6: when
give me that book VS give it to me
1. 如何造一个英语句子: 123 
2. 如何造一个好的英文句子: 123456
3. 英语语序

go to the theatre: 去看戏
have a good seat: 有好座位
get angry: 变得生气
turn round: 转身
pay attention: 注意
in the end: 最终
couldn't bear it: 忍不了了
It's none of your business: 与你无关

** L02 Breakfast or lunch?
[[./NCE2/L02 Breakfast or lunch.html]]
until: [ʌnˈtɪl] prep.直到
outside: [ˌaʊtˈsaɪd] adv.外面
ring: [rɪŋ] v.(铃)响
aunt: [ɑːnt] n.姑,姨
repeat: [rɪˈpiːt] v.重复

repeat after me: 重复我

--------------------
am/is/are + doing:
	1. 动作正在发生;
	2. 动作已经开始,但未完成;
	3. 表近期计划(+未来时间)
	4. 一段时间正在发生的事情: today/this week/this year(阶段)连用
	5. 一段时间正在发生的变化: get/change/become/increase/rise/fall/grow/improve/begin/start

do/does: 动作发生在说话时发生不重要
	1. 习惯动作(一直/重复发生的事情)
	2. 客观事实
	3. 行为靠说话完成. I promise,suggest,apologise,advise,insist,agree,refuse

am/is/are + doing VS do/does
	- 正在发生的行为还没有完成 VS 一直/重复发生的事情
	- 暂时的情况 VS 长久的情况
	- I always do(总是做某事) VS I'm always doing(总是做某事到不正常的程度)

感叹句: 形容词需要升调
	What + (形容词) + n. (+ 主语 + 谓语)

频率adv.位置: 
	1. 动词前,be/助/情态动词后
	2. is/will/did省略句前
	3. probably won't;

get up early/late: 起床早/晚
just then: at a particular time in the past在那时
have breakfast: 吃早餐

** L03 Please send me a card
[[./NCE2/L03 Please send me a card.html]]
send: [send] v.寄,送
postcard: [ˈpəʊstkɑːd] n.明信片
spoil: [spɔɪl] v. 使索然无味,损坏
museum: [mjuˈziːəm] n.博物馆
public: [ˈpʌblɪk] adj.公共的
friendly: [ˈfrendli] adj.友好的
waiter: [ˈweɪtə(r)] n.服务员
lend: [lend] v.借给
decision: [dɪˈsɪʒ(ə)n] n.决定
whole: [həʊl] adj.整个的
single: [ˈsɪŋɡ(ə)l] adj.唯一的,单一的

buy sb. sth. = buy sth. for sb. 买东西给某人
send sb. sth. = send sth. to sb. 送东西给某人
lend sb. sth. = lend sth. to sb. 借东西给某人
borrow sth. from sb. / borrow sb. sth. 从某人那借东西
make a decision: 做决定

--------------------
was/were/did: 过去的状态(was/were) & 动作发生在过去(did) & 和过去时间点连用

teach sb. sth.: 教某人某事
lend sb. sth.: 借给某人某物
think about sth./sb.: 想某人某物
on the last day: 在最后一天
make a decision: 做决定
send sth. to sb.: 送某人某物
spend st. sw.: 在某地花多少时间

** L04 An exciting trip
[[./NCE2/L04 An exciting trip.html]]
exciting: [ɪkˈsaɪtɪŋ] adj.令人兴奋的
receive: [rɪˈsiːv] v.接受
firm: [fɜːm] n.公司
different: [ˈdɪfrənt] adj.不同的
centre: [ˈsentə(r)] n.中心
abroad: [əˈbrɔːd] adv.国外地

have a great trip: 旅途愉快
receive sth. from sb.: 从某人收到某物
work for: 为(公司/某人)工作
A be different from B: A不同于B
in the centre of sp.: 在某地的中央
go abroad: 去国外
live abroad: 住国外
study abroad: 留学

--------------------
have done:
	1. 过去事情对现在有影响;
	2. 从过去持续到现在
	3. 与just~already和yet连用
		just: 刚刚
		already: 早就(预料之前)
		yet: 到目前为止(期待发生,只用疑问和否定句)
	4. 不用过去时间点连用
	5. have gone to 去了那里 & have been to 在那里

receive sth. from sb.: 从某人收到某物
work for sb.: 为(公司/某人)工作
a great number of: 大量+(nc.)
have gone to sp. VS have been to sp.: 动身去某地 VS 去过某地
fly to sp.: 飞去某地
find n. adj.: 发现某物/人怎么样

** L05 No wrong numbers
[[./NCE2/L05 No wrong numbers.html]]
pigeon: [ˈpɪdʒɪn] n.鸽子
message: [ˈmesɪdʒ] n.信息
cover: [ˈkʌvə(r)] v.越过
distance: [ˈdɪstəns] n.距离
request: [rɪˈkwest] n.要求,请求
spare [speə(r)] part [pɑːt]: n.备件
service: [ˈsɜːvɪs] n.业务,服务

leave sb. a message: 给某人留了信息
customer service: 客户服务
cover the distance in st.: 在一定时间内越过这个距离

--------------------
have done VS did: 用过去的事情说现在 VS 只说过去的事情

A is 5 miles from B: A距离B 5英里
get sth. for sb.: 为某人取得某物
cover the distance in st.: 在一段时间内越过这个距离
a great many: 大量+nc.
send a request for sth.: 发送某物的请求
up to now: 迄今
in this way: 用这种方式

** L06 Percy Buttons
[[./NCE2/L06 Percy Buttons.html]]
beggar: [ˈbeɡə(r)] n.乞丐
food: [fuːd] n.食物
pocket: [ˈpɒkɪt] n.衣服口袋
call: [kɔːl] v.拜访,光顾

pocket money: 零花钱
call at = visit: 拜访

--------------------
a/an VS the: 泛指 VS 特指
some VS any:
	1. 陈述句? 肯定some, 否定any
		 有任何的意思? any
	2. if从句? any
	3. 疑问句? 确认some, 不确认any

move to sw.: 搬到某地
knock at the door: 敲门
ask sb. for sth:. 请求某人做某事
stand on sb's head: 倒立
call at: 拜访
in return for this: 作为对此的回报
once/twice a st.: 多久一/两次
ask for sth.: 请求某物

** L07 Too late
[[./NCE2/L07 Too late.html]]
detective: [dɪˈtektɪv] n.侦探
airport: [ˈeəpɔːt] n.机场
expect: [ɪkˈspekt] v.期待,等待
valuable: [ˈvæljuəbl] adj.贵重的
parcel: [ˈpɑːs(ə)l] n.包裹
diamond: [ˈdaɪmənd] n.钻石
steal: [stiːl] stole [stəʊl] stolen [ˈstəʊlən] v.偷
main: [meɪn] adj.主要的
airfield: [ˈeəfiːld] n.飞机起落的场地
guard: [ɡɑːd] n.警戒,守卫
precious: [ˈpreʃəs] adj.珍贵的
stone: [stəʊn] n.石子
sand: [sænd] n.沙子

keep guard: 站岗

--------------------
was/were + doing: 过去正在进行
when & while & just as(正像,正当): 当...


all morning: 整个上午
	The plane was late and detectives were waiting at the airport all morning.
a parcel of sth:. 一包某物
a few hours earlier: 几小时前
keep guard: 站岗
to sb's surprise: 令某人吃惊的
try to do sth:. 尝试做某事
A be full of B: A充满了B

** L08 The best and the worst
[[./NCE2/L08 The best and the worst.html]]
competition: [ˌkɒmpəˈtɪʃ(ə)n] n.比赛
neat: [niːt] adj. 整齐的,整洁的
path: [pɑːθ] n.路径
wooden: [ˈwʊdn] adj.木头的
pool: [puːl] n.水池

enter the competition: 参加比赛
make a path: 开辟路径
That's neat: 这是整洁的

--------------------
adj. 比较级&最高级变化规则
	1. 单音节:+er/est
		 - 元+辅音字母结尾: 需双写辅音字母 big -> bigger
	2. 双音节:
		 - 辅音+y结尾: y变成i pretty -> prettier
	3. 多音节: + more/less, most/least
	4. 不规则:good/well~bad~much~little
比较状从:
	1. 主语 + be + the + adj.est + n. + I've ever met/seen
	2. 主语 + be + the + adj.est + n. + 范围
	3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)

enter for: 参加
make a path: 开辟路径
build a bridge: 建桥
win a prize: 赢得奖品

** L09 A cold welcome
[[./NCE2/L09 A cold welcome.html]]
welcome: [ˈwelkəm] v.n.欢迎.欢迎
crowd: [kraʊd] n.人群
gather: [ˈɡæðə(r)] v.聚集
hand: [hænd] n.(表或机器的)指针
shout: [ʃaʊt] v.喊叫
refuse: [rɪˈfjuːz] v.拒绝
laugh: [lɑːf] v.笑

a cold welcome: 冷遇
a warm welcome: 热遇
gather round: 聚集在一起
shout at sb:. 对某人大声呼叫
refuse to do sth:. 拒绝去做某事
laugh at sb:. 嘲笑某人

--------------------
at/on/in(时间)
	- on + 具体某一天
	- in + 年/季/月
	- at + 时间点

the last day of the year: 这一年的最后一天
a large crowd of: 大量的人群
in twenty minutes' time: 二十分钟后
refuse to do sth:. 拒绝去做某事
at that moment: 在那一刻
begin to do sth:. 开始做某事

** L10 Not for jazz
[[./NCE2/L10 Not for jazz.html]]
jazz: [dʒæz] n.爵士音乐
musical: [ˈmjuːzɪk(ə)l] adj.音乐的
instrument: [ˈɪnstrəmənt] n.乐器
clavichord: [ˈklævɪkɔːd] n.古钢琴
recently: [ˈriːs(ə)ntli] adv.最近
damage: [ˈdæmɪdʒ] v.损坏
key: [kiː] n.琴键
string: [strɪŋ] n.(乐器的)弦
shock: [ʃɒk] v.使不悦或生气,震惊
allow: [əˈlaʊ] v.允许,让
touch: [tʌtʃ] v.触摸

be allowed to do sth.: 被允许做某事
allow sb. to do sth.: 允许某人做某事

--------------------
am/is/are+done
was/were+done
am/is/are+being+done
have/has+been+done

be made in sw.: 某地制造
belong to sb.: 属于某人
play jazz: 弹爵士
be allowed to do sth.: 被允许做某事

** L11 One good turn deserves another
[[./NCE2/L11 One good turn deserves another.html]]
turn: [tɜːn] n.行为,举止
deserve: [dɪˈzɜːv] v.应得到,值得
lawyer: [ˈlɔɪə(r)] n.律师
bank: [bæŋk] n.银行
salary: [ˈsæləri] n.工资
immediately: [ɪˈmiːdiətli] adv.立刻

one good turn deserves another: 好的行为值得另一个好的
get a good salary: 获得不错的薪水
It's your turn: 轮到你了

get a good salary: 获得不错的薪水
borrow sth. from sb.: 从某人借某物
pay it back: 偿还回来
pay for sth.: 支付某物
ask sb. to do sth.: 问某人去做某事

** L12 Goodbye and good luck
[[./NCE2/L12 Goodbye and good luck.html]]
luck: [lʌk] n.运气,幸运
captain: [ˈkæptɪn] n.船长
sail: [seɪl] v.航行
harbour: [ˈhɑːbə(r)] n.港口
proud: [praʊd] adj.自豪
important: [ɪmˈpɔːt(ə)nt] adj.重要的

lucky dog: 幸运儿
be proud of: 以...为豪
I got a very important question to ask you: 我有一个非常重要的问题问你

--------------------
will do: 将/会(当机立断决定,而非计划)
shall do: 将/会(当机立断决定,而非计划) 

sail from sw.: 从某地航行
set out: 出发
have plenty of time: 有充足的时间
will be away: 将会离开
A be proud of B:  A以B为豪
say goodbye to sb.: 对某人说再见
take part in: 参加

** L13 The Greenwood Boys
[[./NCE2/L13 The Greenwood Boys.html]]
group: [ɡruːp] n.小组,团体
pop: [pɒp] singer [ˈsɪŋə(r)] n.流行歌手
club: [klʌb] n.俱乐部
performance: [pəˈfɔːməns] n.演出
occasion: [əˈkeɪʒ(ə)n] n.场合

a group of: 一组，一群
pop music/song/star: 流行音乐/歌曲/明星
give a performance: 进行一次演出
on this occasion: 在这个场合

--------------------
will be doing: 1.未来动作正在进行;2.计划

a group of:
at present: 目前，现在
all parts of the country: 全国各地
as usual: 按照通常的方式或习惯
have a difficult time: 遇到困难
give five performance: 五项表演
keep order: 维持秩序
on these occasions: 在这种场合

** L14 Do you speak English?
[[./NCE2/L14 Do you speak English.html]]
amusing: [əˈmjuːzɪŋ] adj.好笑的,有趣的
experience: [ɪkˈspɪəriəns] n.经历
wave: [weɪv] v.招手
lift: [lɪft] n.搭便车
reply: [rɪˈplaɪ] v.回答
language: [ˈlæŋɡwɪdʒ] n.语言
journey: [ˈdʒɜːni] n.旅行

have an amusing experience: 有一次有趣的经历
wave to sb.: 向某人招手
take a lift/ ask for a lift: 搭车/要求搭车
A give B a lift: 让某人搭便车
reply to the email/letter: 回复邮件/信件
go on a journey: 进行一次旅行

--------------------
had + done: 1.过去的过去;2.过去A发生,对于过去B产生影响(A在B前);3.动作从过去A持续(重复)到过去B

drive on to sw.: 继续开车到某地
on the way: 在路上
ask sb. for a lift: 问某人搭便车
apart from: 除了...之外
in French: 用法语

** L15 Good news
[[./NCE2/L15 Good news.html]]
secretary: [ˈsekrət(ə)ri] n.秘书
nervous: [ˈnɜːvəs] adj.精神紧张的
afford: [əˈfɔːd] v.负担得起
weak: [wiːk] adj.弱的
interrupt: [ˌɪntəˈrʌpt] v.插话,打断

be nervous about sth. / doing sth.: 对某事/做某事紧张
afford sth.: 负担某物
Sorry to interrupt, but...: 很抱歉打断, 但是...

--------------------
宾语从句: 句子做宾语
直接引语变间接引语: 时态倒退一个时态,现在->过去,过去->过去完成;客观事实仍成立可不退

look up: 抬头看
afford to pay: 负担得起支付
my turn had come: 轮到我了
in a weak voice: 用微弱的声音

** L16 A polite request
[[./NCE2/L16 A polite request.html]]
park: [pɑːk] v.停放(汽车)
traffic: [ˈtræfɪk] n.交通
ticket: [ˈtɪkɪt] n.交通违规罚款单
note: [nəʊt] n.便条
area: [ˈeəriə] n.地段
sign: [saɪn] n.指示牌
reminder: [rɪˈmaɪndə(r)] n.提示
fail: [feɪl] v.无视,忘记
obey: [əˈbeɪ] v.服从

make notes/ a note: 做笔记
leave a note: 留下便条
remind sb. of sth./sb.: 使得某人想起某事或某人
fail to do sth.: 失败做某事

--------------------
if从句
	- 主将从现
	- 主情从现
	- 主祈从现

park sb's car: 停某人的车
pay attention to: 注意到某事
	
** L17 Always young
[[./NCE2/L17 Always young.html]]
appear: [əˈpɪə(r)] n.v.登场,扮演
stage: [steɪdʒ] n.舞台
bright [braɪt] adj. + color [ˈkʌlə(r)] + n.: 鲜艳的颜色
stocking: [ˈstɒkɪŋ] n.(女用)长筒袜
sock [sɒk] n.短袜
grown-up [ˌɡrəʊn ˈʌp] adj. n.成年人

--------------------
must: 肯必须(主观);否禁止
have to: 肯必须(客观):否不必
've/have got to: 表必须

肯否猜测:
	- 现在猜测
		must: 一定是
		can't: 一定不是
	- 过去猜测
		must have done: 当时一定是
		can't have done: 当时一定不是

at least: 至少
in spite of this: 尽管这样
take part in: 参加(比赛)

** L18 He often does this
[[./NCE2/L18 He often does this.html]]
pub: [pʌb] n.小酒店
landlord: [ˈlændlɔːd] n.店主
bill: [bɪl] n.账单

pay the bill: 支付账单

--------------------
have: 万能动词

look for: 寻找
have a meal: 吃饭
pay the bill: 支付账单
in a few minutes: 在几分钟内

** L19 Sold out
[[./NCE2/L19 Sold out.html]]
hurry: [ˈhʌri] v.匆忙
ticket: [ˈtɪkɪt] office [ˈɒfɪs]售票处
pity: [ˈpɪti] n.令人遗憾的事
exclaim: [ɪkˈskleɪm] v.大声说
return: [rɪˈtɜːn] v.n.退回
sadly: [ˈsædli] adv.悲哀地,丧气地

hurry to sw.: 匆忙去某地
in a hurry: 匆忙地
What a pity: 多么遗憾
It's a pity that...: 非常遗憾...
Don't yell at me.: 别冲着我叫

--------------------
也许 现在-猜测: 
may/might (not)do
may/might (not)be adj./n.
may/might (not)be doing

也许 过去-猜测: 
may/might (not)have done
may/might (not)have been adj./n.
may/might (not)have been doing.

sold out: 售完
at once: (=immediately, soon)立刻
might/may as well: 最好

** L20 One man in a boat
[[./NCE2/L20 One man in a boat.html]]
catch [kætʃ] caught caught: v.抓到
fisherman: [ˈfɪʃəmən] n.钓鱼人,渔民
boot: [buːt] n.靴子
rubbish: [ˈrʌbɪʃ] n.垃圾
waste: [weɪst] n v.浪费
realize: [ˈriːəlaɪz] v.意识到

catch your eye: 引起你的注意
catch a bus: 赶公交车
watch your tongue: 小心言辞
That's rubbish: 这是垃圾
You're wasting time.: 你在浪费时间
sb. realized that...: 某人意识到...

--------------------
动名词:v-ing

instead of doing sth.: 而不是做某事
spend st. sw.: 在某地花费时间
give up doing sth.: 放弃做某事
be interesting in doing sth.: 对做某事赶兴趣
be keen on doing sth.: 对做某事感兴趣

** L21 Mad or not?
[[./NCE2/L21 Mad or not.html]]
mad: [mæd] adj.发疯
reason: [ˈriːz(ə)n] n.原因
sum: [sʌm] n.量
determined: [dɪˈtɜːmɪnd] adj.坚定的,下决心的

be mad at sb.: 对某人很恼火
for some reason: 因为一些原因
a large sum of money: 一大笔钱
be determined to do sth.: 决心做某事

--------------------
will/would be done
can/could be done
must be done
have to be done
must have been done

drive sb. mad: 使某人发狂
for some reason: 因为一些原因
come into use: 投入使用

** L22 A glass envelope
[[./NCE2/L22 A glass envelope.html]]
dream: [driːm] v.做梦,梦想
age: [eɪdʒ] n.年龄
channel: [ˈtʃæn(ə)l] n.海峡
throw: [θrəʊ] threw [θruː] thrown [θrəʊn] v.扔,抛
regularly: [ˈreɡjələli] adv.有规律地

dream of doing sth.: 梦想做某事
at my age: 以我的年纪
throw away: 丢弃

--------------------
v. + of/from/in/on

think of sth.: 考虑某事
write to sb.: 写给某人
decide to do sth.: 决定做某事

** L23 A new house
[[./NCE2/L23 A new house.html]]
complete: [kəmˈpliːt] v.完成
modern: [ˈmɒd(ə)n] adj.新式的,与以往不同的
strange: [streɪndʒ] adj.奇怪的
district: [ˈdɪstrɪkt] n.地区

You complete me.: 你完成了我
have a letter from sb.: 收到某人的信
get a surprise: 得到个惊喜

** L24 It could be worse
[[./NCE2/L24 It could be worse.html]]
manager: [ˈmænɪdʒə(r)] n.经理
upset: [ˌʌpˈset] adj.不安
sympathetic: adj.表示同情的
complain: [kəmˈpleɪn] v wicked [ˈwɪkɪd] adj.抱怨
contain: [kənˈteɪn] v.包含,内装
honesty: [ˈɒnəsti] n honest [ˈɒnɪst] adj.诚实

get/be upset about sth.: 对某事很沮丧
complain about sth.: 抱怨某事
start to do sth.: 开始做某事

** L25 Do the English speak English?
[[./NCE2/L25 Do the English speak English.html]]
railway: [ˈreɪlweɪ] n.铁路
porter: [ˈpɔːtə(r)] n.搬运公
several: [ˈsevrəl] q. 几个
foreigner: [ˈfɒrənə(r)] n.外国人
wonder: [ˈwʌndə(r)] v.感到奇怪

not know the way to sw.: 不知道去某地的路

--------------------
1. and,but,or,so,because(Because & ,because): 连句子
2. both... and, either...or,neither...nor: 连两名词
3. not only... but also (as well) ?: 连句子

** L26 The best art critics
[[./NCE2/L26 The best art critics.html]]
art: [ɑːt] n.艺术
critic: [ˈkrɪtɪk] n.评论家
paint: [peɪnt] v.画
pretend: [prɪˈtend] v.假装
pattern: [ˈpæt(ə)n] n.图案
curtain: [ˈkɜːt(ə)n] n.窗帘,幕布
material: [məˈtɪəriəl] n.材料
appreciate: [əˈpriːʃieɪt] v.鉴赏
notice: [ˈnəʊtɪs] v.注意到
whether: [ˈweðə(r)] conj.是否
hang [hæŋ] hung hung: v.悬挂,吊
critically: [ˈkrɪtɪkli] adv.批评地
upside: [ˈʌpsaɪd] down 上下颠倒地

sb. pretend that ...: 某人假装...
I really appreciate that.: 我真的感激.

** L27 A wet night
[[./NCE2/L27 A wet night.html]]
tent: [tent] n.帐篷
field: [fild] n.田地,田野
smell: [smel] smelt v.闻起来
wonderful: [ˈwʌndərfəl] adj.极好的
campfire: [ˈkæmpˌfaɪr] n.营火,篝火
creep: [krip] v.爬行
sleeping: [sliːp] bag 睡袋
comfortable: [ˈkʌmfərtəb(ə)l] adj.舒适的,安逸的
soundly: [ˈsaʊn(d)li] adv.香甜地
leap: [lip] v.跳跃,跳起
heavily: [ˈhevɪli] adv.大量地
stream: [strim] n.小溪
form: [fɔrm] v.形成
wind: [waɪnd] wound wound v.蜿蜒
right: [raɪt] adv.正好

put up the tent: 搭起帐篷
tell a story/stories: 讲个故事
put out the fire: 扑灭火焰
begin doing sth.: 开始做某事
wake up: 醒来

** L28 No parking
[[./NCE2/L28 No parking.html]]
rare: [rer] adj.罕见的
ancient: [ˈeɪnʃənt] adj.古代的,古老的
myth: [mɪθ] n.神话故事
trouble: [ˈtrʌb(ə)l] n.麻烦
effect: [ɪˈfekt] n.结果,效果
Medusa: n.美杜莎
Gorgon: n.

have trouble with sth:. 在某事上有困难
	He has had trouble with cars and their owners.
have no effect: 无效
have trouble doing sth.: 做某事有困难

--------------------
限定性定语从句:
	- 输出:
		1. 确定被修饰词
		2. 确定引导词, who/whom/which/that
		3. 是否可以省略(引导词在从句是宾语可省)
	- 有多个人或物时,起限定某个的作用
	- what = the thing(s) that(补充了主句成分)
	- where: 指代地点,介词不要了. a place where ... , 而不是 a place where ... in.
			还有to which, in which的变形,注意!!!
	- whose: her, his, their

** L29 Taxi!
[[./NCE2/L29 Taxi.html]]
taxi: [ˈtæksi] n.出租汽车
Pilatus: Porter
land: [lænd] v.着陆
plough: [plaʊ] v.耕地
lonely: [ˈloʊnli] adj.偏僻的,人迹罕至的
Welsh: [welʃ] adj.威尔士的
roof: [ruf] n.楼顶
block: [blɑk] n.一座大楼
flat: [flæt] n.公寓房
desert: [ˈdezərt] v.废弃

take a taxi: 乘坐出租车

--------------------
done做定语: 表被动一般/被动完成/主动完成(少)
	- done + n.
	- n. + done短语
	- 常常与there be句型连用
复习have done VS did

** L30 Football or polo?
[[./NCE2/L30 Football or polo.html]]
polo: [ˈpoʊloʊ] n.水球
Wayle: n.
cut: [kʌt] cut cut v.穿过
row: [raʊ] v.划(船)
kick: [kɪk] v.踢
towards: [təˈwɒrd] prep.朝,向
nearly: [ˈnɪrli] adv.几乎
sight: [saɪt] n.眼界,视域

kick his ass: 踢他的屁股

--------------------
doing现在分词做定语: 主动进行/主动一般
	- doing + n.
	- n. + doing
	- 常常和there be连用
	- 例句
		- the sinking ship=the ship that is sinking
		- the rising sun=the sun that is rising
		- the sleeping child=the child who is sleeping

call out to sb.: 向某人呼喊

** L31 Success story
[[./NCE2/L31 Success story.html]]
retire: [rɪˈtaɪr] v.退休
company: [ˈkʌmpəni] n.公司
bicycle: [ˈbaɪsɪk(ə)l] n.自行车
save: [seɪv] v.积蓄
workshop: [ˈwɜrkˌʃɑp] n.车间
helper: [ˈhelpər] n.帮手,助手
employ: [ɪmˈplɔɪ] v.雇佣
grandson: [ˈɡræn(d)ˌsʌn] n.孙子

save sb's life: 救某人的命
--------------------
used to do sth.: 过去常常,但现在不做

It is/was sb's job to do sth.: 做某事是某人的工作
in sb's twenties: 在某人二十多的时候

** L32 Shopping made easy
[[./NCE2/L32 Shopping made easy.html]]
once: [wʌns] adv.曾经,以前
temptation: [tempˈteɪʃ(ə)n] n.诱惑
article: [ˈɑrtɪk(ə)l] n.物品,东西
wrap: [ræp] v.包裹
simply: [ˈsɪmpli] adv.仅仅
arrest: [əˈrest] v.逮捕

once upon a time: 很久以前
resist the temptation: 抵制诱惑
wrap up sth.: 把某事包起来

--------------------
as ... as VS so ... as(否): 同样的

It is easy for sb. to do sth.: 对某人来说做某事很容易
hand sth. to sb.: 把某物交给某人
wrap sth. up: 把某事包起来:
as quickly as possible: 尽快

** L33 Out of the darkness
[[./NCE2/L33 Out of the darkness.html]]
darkness: [ˈdɑrknəs] n.黑暗
explain: [ɪkˈspleɪn] v.解释,叙述
coast: [koʊst] n.海岸
storm: [stɔrm] n.暴风雨
towards: [təˈwɒrd] prep.向,朝;接近
rock: [rɑk] n.岩石,礁石
shore: [ʃɔr] n.海岸
light: [laɪt] n.灯光
ahead: [əˈhed] adv.在前面
cliff: [klɪf] n.峭壁
struggle: [ˈstrʌɡ(ə)l] v.挣扎
hospital: [ˈhɑspɪt(ə)l] n.医院

struggle up: 艰难地爬起来
explain sth. to sb.: 向某人解释某事
go ahead: 前进
 
--------------------
be high up 高高在上:
On doing sth, ...: 一做完某事,就...

** L34 Quick work
[[./NCE2/L34 Quick work.html]]
station: [ˈsteɪʃ(ə)n] n.警察局
most: [moʊst] adv.相当,非常
--------------------
had been + done

call at: = visit 不那么正式
except sth. to be found: 期待某物被找到

** L35 Stop thief!
[[./NCE2/L35 Stop thief.html]]
while: [hwaɪl] n.一段时间
regret: [rɪˈɡret] v.后悔
far: [fɑr] adv.非常
rush: [rʌʃ] v.冲
act: [ækt] v.行动
straight: [streɪt] adv.径直
fright: [fraɪt] n.害怕
battered: [ˈbætərd] adj.撞坏的
shortly: [ˈʃɔrtli] adv.很快,不久
afterwards: [ˈæftərwərdz] adv.以后

a short while ago: 不久之前
regret sth./doing sth.: 后悔做某事
rush out of/towards: 冲出/奔向
go straight ahead: 直走
give me a fright: 吓我
get a fright: 受到惊吓
Shortly afterwards: 不久之后

--------------------
so + adj./adv. that = such + n. that: 如此以至于
see sb. do sth VS see sb. doing sth.: 看到某人做某事 VS 看到某人正在做某事

** L36 Across the Channel
[[./NCE2/L36 Across the Channel.html]]
record: ['rekərd] n.记录
strong: [strɔŋ] adj.强壮的
swimmer: [ˈswɪmər] n.游泳运动员
succeed: [səkˈsid] v.成功
train: [treɪn] v.训练
anxiously: ['æŋkʃəsli] adv.焦急地
intend: [ɪnˈtend] v.打算
solid: [ˈsɑlɪd] adj.固体的,硬的

set up a new world record: 创造一项新的世界纪录
break the record: 打破纪录
as strong as a horse: 像马一样强壮
strong like a horse: 像马一样强壮
succeed in doing sth.: 成功做某事
train sb. to do sth.: 训练某人做某事
intend to do sth.: 打算做某事

--------------------
表述将来: 计划
be going to do(be due to)
will
intend to do

hope to do sth.: 希望做某事
be sure to do sth.: 确定做某事
take some rests/a rest: 休息一下

** L37 The Olympic Games
[[./NCE2/L37 The Olympic Games.html]]
Olympic: adj.奥林匹克的
hold: [hoʊld] v.召开
government: [ˈɡʌvərnmənt] n.政府
immense: [ɪˈmens] adj.巨大的
stadium: [ˈsteɪdiəm] n.露天体育场
standard: [ˈstændərd] n.标准
capital: [ˈkæpɪt(ə)l] n.首都
fantastic: [fænˈtæstɪk] adj.巨大的
design: [dɪˈzaɪn] v.设计

hold a meeting: 召开会议

--------------------
will have done: 1.动作持续(重复)到将来;2.动作截至到未来时间点前完成
have done VS had done VS will have done

look forward to doing sth.: 期待做某事

** L38 Everything except the weather
[[./NCE2/L38 Everything except the weather.html]]
except: [ɪkˈsept] prep.除了
Mediterranean: [ˌmedɪtəˈreɪniən] n.地中海
complain: [kəmˈpleɪn] v.抱怨
continually: [kən'tɪnjʊəlɪ] adv.不断地
bitterly: [ˈbɪtərli] adv.刺骨地
sunshine: [ˈsʌnˌʃaɪn] n.阳光

complain about sth.: 抱怨某事
bitterly cold: 刺痛地寒冷

--------------------
一前就后,过去完成时的固定句式
had hardly done ... when ...
had no sooner done ... than ...

dream of doing sth.: 梦想做某事
plan to do: 计划做某事
settle down: 安顿下来

** L39 Am I all right?
[[./NCE2/L39 Am I all right.html]]
operation: [ˌɑpəˈreɪʃ(ə)n] n.手术
successful: [səkˈsesfəl] adj.成功的
following: [ˈfɑloʊɪŋ] adj.下一个
patient: [ˈpeɪʃ(ə)nt] n.病人
alone: [əˈloʊn] adj.独自的
exchange: [ɪksˈtʃeɪndʒ] n.(电话的)交换台
inquire: [ɪnˈkwaɪr] v.询问,打听
certain: [ˈsɜrt(ə)n] adj.某个
caller: [ˈkɔlər] n.打电话的人
relative: [ˈrelətɪv] n.亲戚

have an operation: 动手术
leave me alone: 离我远点
inquire about sth./sb.: 询问某事/某人

--------------------
宾语从句
NCE1 L99 L101 L133 L135 L139

refuse to do sth.: 拒绝做某事
ask for sth.: 寻求某物
be allowed to do sth.: 被允许做某事

** L40 Food and talk
[[./NCE2/L40 Food and talk.html]]
hostess: [ˈhoʊstəs] n.女主人
unsmiling: [ʌnˈsmaɪlɪŋ] adj.不笑的,严肃的
tight: [taɪt] adj.紧身的
fix: [fɪks] v.凝视
globe: [ɡloʊb] n.地球
despair: [dɪˈsper] n.绝望

in despair: 绝望地

--------------------
虚拟语气(现在): 与现在事实相反
	If + did/were, 主+would/should/could/might do

take my seat: 做我的座位
be busy doing sth.: 忙于做某事
Will you be doing sth?: 你会做某事吗?

** L41 Do you call that a hat?
[[./NCE2/L41 Do you call that a hat.html]]
rude: [rud] adj.无礼的
mirror: [ˈmɪrər] n.镜子
hole: [hoʊl] n.孔
remark: [rɪˈmɑrk] v.评说
remind: [rɪˈmaɪnd] v.提醒
lighthouse: [ˈlaɪtˌhaʊs] n.灯塔

remind sb. of sth./sb.: 使某人想起某事

--------------------
need: 需要
needn't have done: 本不必如此,却做了,有后悔效果

regret doing sth.: 后悔做某事
find sth. adj.: 发现某事adj.

** L42 Not very musical
[[./NCE2/L42 Not very musical.html]]
musical: [ˈmjuzɪk(ə)l] adj.精通音乐的
market: [ˈmɑrkət] n.市场,集市
snake: [sneɪk] charmer [ˈtʃɑrmər] 玩蛇者(借音乐控制)
pipe: [paɪp] n.(吹奏的)管乐器
tune: [tun] n.曲调
glimpse: [ɡlɪmps] n.一瞥
snake: [sneɪk] n.蛇
movement: [ˈmuvmənt] n.动作
continue: [kənˈtɪnju] v.继续
dance: [dæns] v.跳舞
obviously: [ˈɑbviəsli] adv.显然
difference: [ˈdɪf(ə)rəns] n.差别
Indian: [ˈɪndiən] adj.印度的

watch a musical: 观看音乐剧
play a tune: 演奏一曲
have a glimpse of sth./sb.: 瞥见某物/某人
continue to do sth.: 继续做某事
tell the difference from A and B / A be different from B: 区别于A和B / A不同于B

--------------------
have 万能动词

have a long walk: 长时间散步
at the other side of sw.: 在...另一边

** L43 Over the South Pole
[[./NCE2/L43 Over the South Pole.html]]
pole: [poʊl] n.(地球的)极
flight: [flaɪt] n.飞行
explorer: [ɪkˈsplɔrər] n.探险家
lie: [laɪ] lay [leɪ] lain [leɪn] v.处于
serious: [ˈsɪriəs] adj.严重的
point: [pɔɪnt] n.地点
seem: [sim] v.似乎,好像
crash: [kræʃ] v.坠毁
sack: [sæk] n.袋子
clear: [klɪr] v.越过
aircraft: [ˈerˌkræft] n.飞机
endless: [ˈendləs] adj.无尽的
plain: [pleɪn] n.平原

catch a flight: 赶飞机
run into serious trouble: 遇到严重的麻烦
one point: 指出
It seems that ...: 看来……

--------------------
- be able to: 有能力; 做成某事的案例
	+ can: 有能力(be able to的一般时);可能发生;
	+ could: 有能力(be able to的过去式);可能发生; 被允许; 没有!!!做成某事的案例
	+ was able to: 有能力(be able to的过去式); 做成某事的案例
	+ managed to do: 做成某事的案例
	+ 对比以上时态更多

order sb. to do sth.: 命令某人做某事

** L44 Through the forest
[[./NCE2/L44 Through the forest.html]]
forest: [ˈfɔrəst] n.森林
risk: [rɪsk] n.危险,冒险
picnic: [ˈpɪknɪk] n.野餐
edge: [edʒ] n.边缘
strap: [stræp] n.带,皮带
possession: [pəˈzeʃ(ə)n] n.所有
breath: [breθ] n.呼吸
contents: [kənˈtent] n.(常用复数)内有的物品
mend: [mend] v.修理

take a risk: 冒险
have a picnic: 野餐
at the edge of a forest: 在森林的边缘
in sb's possession: 在某人手中
out of breath: 喘不过气来

rush up to sb.: 冲向某人
catch up with sb.:  追上某人
go through: 翻遍
need doing sth.: 需要被做某事
run straight at sb.: 径直冲向某人

** L45 A clear conscience
[[./NCE2/L45 A clear conscience.html]]
clear: [klɪr] adj.无罪的,不亏心的
conscience: [ˈkɑnʃəns] n.良心,道德心
wallet: [ˈwɑlət] n.皮夹,钱夹
savings: [ˈseɪvɪŋ] n.存款
villager: [ˈvɪlɪdʒər] n.村民
percent: [pərˈsent] 百分之...

I have a clear conscience: 我问心无愧
Are you 100 percent sure about this?: 你百分百确定吗?

--------------------
be done

sb. learn that + 宾语从句: 某人得知
return sth. to sb.: 把某物归还给某人

** L46 Expensive and uncomfortable
[[./NCE2/L46 Expensive and uncomfortable.html]]
unload: [ʌnˈloʊd] v.卸(货)
wooden: [ˈwʊd(ə)n] adj.木制的
extremely: [ɪkˈstrimli] adv.非常,极其
occur: [əˈkɜr] v.发生
astonish: [əˈstɑnɪʃ] v.使惊讶
pile: [paɪl] n.堆
woolen: [ˈwʊlən] n.羊毛的
goods: [ɡʊdz] n.(常用复数)货物,商品
discover: [dɪˈskʌvər] v.发现
admit: [ədˈmɪt] v.承认
confine: [kənˈfaɪn] v.关在(一个狭小的空间里)
normal: [ˈnɔrm(ə)l] adj.正常的,通常的

It occurred to sb. that ...: 某人突然想到……
It occurred to sb. to do sth.: 某人突然想到做某事
be astonished at sth.: 对某事感到惊讶
admit doing sth.: 承认做过某事
sb. admit that...: 某人承认……

--------------------
- 同位语: 补充说明的名词
I have just received a letter from my brother, Tim.

- 同位语从句: 完整(引导词不充当从句成分)句子补充说明名词.
No one could account for *the fact that* one of the boxes was extremely heavy.

What = the thing that/the person that
sb. account for the fact that + 句子: 某人解释了这一事实

** L47 A thirsty ghost
[[./NCE2/L47 A thirsty ghost.html]]
thirsty: [ˈθɜrsti] adj.贪杯的
ghost: [ɡoʊst] n.鬼魂
haunt: [hɔnt] v.(鬼)来访,闹鬼
block: [blɑk] v.堵
furniture: [ˈfɜrnɪtʃər] n.家具
whisky: [ˈhwɪski] n.威士忌酒
suggest: [səɡˈdʒest] v.暗示
shake: [ʃeɪk] shook [ʃʊk] shaken [ˈʃeɪkən] v.摇动
accept: [əkˈsept] v.接受

shake sb's head: 摇头

be up for sale: 待售
hear sb./sth. doing sth.: 听到某人/某事正在做某事

** L48 Did you want to tell me something?
[[./NCE2/L48 Did you want to tell me something.html]]
pull: [pʊl] v.拔
cotton: [ˈkɑt(ə)n] wool [wʊl] (羊毛棉)药棉
collect: [kəˈlekt] v.搜集
collection: [kəˈlekʃ(ə)n] n.收藏品,收集品
nod: [nɑd] v.点头
meanwhile: [ˈminˌhwaɪl] adv.同时

private collection: 私人收藏

It is impossible for sb. to do: 做某事对某人来说是不可能的
... rest for a while: 稍作休息

** L49 The end of a dream
[[./NCE2/L49 The end of a dream.html]]
tired: [ˈtaɪəd] adj.厌烦的
real: [ˈriːəl; rɪəl] adj.真正的
owner: [ˈəʊnə(r)] n.主人 own v.拥有
spring: [sprɪŋ] n.弹簧
mattress: [ˈmætrəs] n.床垫
gust: [ɡʌst] n.一阵风
sweep: [swiːp] swept [swept] swept v. 扫,刮
courtyard: [ˈkɔːtjɑːd] n.院子
smash: [smæʃ] v.碰碎,摔碎
miraculously: [mɪˈrækjələsli] adv.奇迹般地
unhurt: [ʌnˈhɜːt] adj.没有受伤的
glance: [ɡlɑːns] v.扫视
promptly: [ˈprɒmptli] adv.迅速地

get/be tired of sth./doing sth.: 对某事/做某事感到厌倦
A gust of wind swept ...: 一阵风吹过……
in the courtyard: 在院子里
smash sth. to pieces: 把某物粉碎
glance at sth.: take a quick look at sth.扫一眼……

--------------------!!!
分词作状语 没找到部分被动
1. (not) doing
	 主动进行/主动一般
	 (being) (not) + adj.
2. done
	 被动一般/被动完成/主动完成(少)
3. having done
	 主动完成(发生在主句之前)
	 having been + adj. (主句之前的状态)
4. having been done 在N2-69课
	 主动完成被动(发生在主句之前)

save up for year to do sth.: 攒一年的钱做某事
for the first time in sb's life: 某人一生中第一次
go to sleep: 入睡

** L50 Taken for a ride
[[./NCE2/L50 Taken for a ride.html]]
ride: [raɪd] n.旅行
excursion: [ɪkˈskɜrʒ(ə)n] n.远足
conductor: [kənˈdʌktər] n.售票员
view: [vju] n.景色

--------------------
do/does
am/is/are+doing
--------------------
prefer
	- prefer to do sth. = prefer doing sth. = I'd prefer to do sth
	- prefer a to b  &  prefer doing a to doing b
	- prefer to do a rather than (do) b.  &  I'd prefer to do a. rather than (do) b.
	- would rather do A than do B

** L51 Reward for virtue
[[./NCE2/L51 Reward for virtue.html]]
reward: [rɪˈwɔːd] n. v. 奖赏
virtue: [ˈvɜːtʃuː] n. 美德
diet: [ˈdaɪət] n. 节食
forbid: [fəˈbɪd] forbade forbidden v. 禁止
hurriedly: [ˈhʌrɪdli] adv. 匆忙的
embarrass: [ɪmˈbærəs] v. 使尴尬
guiltily: [ˈɡɪltɪli] adv. 内疚地
strict: [strɪkt] adj. 严格的
occasionally: [əˈkeɪʒnəli] adv. 偶尔地

expect/receive/give + reward: 期待/接受/给予+奖励
go on a diet = be on a diet: 节食
forbid sb. to do sth.: 禁止某人做某事
A be strict with B: A对B严格
--------------------
L3 & L27
was/were/did

First of all,...: 首先
write out a long list of ...: 列出一长串的
pay sb. a visit: 拜访某人
was not surprised to see that...: 看到……我并不感到惊讶
It was obvious that...: 很明显……
ring the bell: 敲响警钟
** L52 A pretty carpet
[[./NCE2/L52 A pretty carpet.html]]
temporarily: [ˈtemprərəli] adv.暂时地
inch: [ɪntʃ] n.英寸(度量单位)
space: [speɪs] n.空间
actually: [ˈæktʃuəli] adv.实际上

every inch of sth.: 每一寸的
That's actually a good idea: 这确实是个好主意

--------------------
have been doing(不知持续与否):
	1. 过去进行的v.对现在有影响;
	2. 从过去持续(或重复!)到现在

get sth. in order: 把某事整理好
To make matters worse...: 使事情更糟糕,...
A short while ago...: 不久之前
gaze at sth.: 凝视某物
in sb's spare time...: 在某人的业余时间
help sb. to do sth.: 帮助某人做某事

** L53 Hot snake
[[./NCE2/L53 Hot snake.html]]
hot: [hɒt] adj.带电的,充电的
fireman: [ˈfaɪəmən] n.消防队员
cause: [kɔːz] v.引起 n.原因
examine: [ɪɡˈzæmɪn] v.检查
accidentally: [ˌæksɪˈdentəli] adv.意外地,偶然地
remains: [rɪˈmeɪnz] n.尸体,残骸
wire: [ˈwaɪə(r)] n.电线
volt: [vəʊlt] n.伏特(电压单位)
power line: [ˈpaʊə laɪn] 电力线
solve: [sɒlv] v.解决
mystery: [ˈmɪst(ə)ri] n.谜
snatch: [snætʃ] v.抓住
spark: [spɑːk] n.电火花

electrical wire / electric wire: 电线
discover a cause: 发现原因
the remains of a snake: 蛇的残骸
solve + problem/mystery: 解决问题/谜团
remain mystery: 保持谜

--------------------
did
have done
have been doing

find out: 发现
throw away: 丢弃

** L54 Sticky fingers
[[./NCE2/L54 Sticky fingers.html]]
sticky: [ˈstɪki] adj.粘的
finger: [ˈfɪŋɡə(r)] n.手指
pie: [paɪ] n.馅饼
mix: [mɪks] v.混合,搅拌
pastry: [ˈpeɪstri] n.面糊
annoying: [əˈnɔɪɪŋ] adj.恼人的
receiver: [rɪˈsiːvə(r)] n.电话的话筒
dismay: [dɪsˈmeɪ] v.失望,泄气
recognize: [ˈrekəɡnaɪz] v.认出,听出
persuade: [pəˈsweɪd] v.说服,劝说
mess: [mes] n.乱七八糟
doorknob: [ˈdɔːnɒb] n.门把手
sign: [saɪn] v.签字
register: [ˈredʒɪstə(r)] v.挂号邮寄

stick to the plan: 坚持计划
put my finger on it: 把我的手指放在上面
point the finger at: 指着某人
be dismayed to do sth.: 对做某事感到沮丧
recognize the voice (of sb.): 听出(某人的)声音
persuade sb. (not) to do sth.: 说服某人(不)做某事
What a mess!: 一团糟
such a mess: 一团糟
Sign here: 在这里签名
sign for sth.: 签收某物
a registered letter: 挂号信

send sb. to sp.: 把某人送到
decide to do sth.: 决定做某事
be busy doing sth.: 忙于做某事
be covered with sth.: 被某物覆盖
take sb. st. to do sth.: 带某人去做某事
hang up 挂断电话:
What a mess!: 一团糟
sign for sth.: 签收某物

** L55 Not a gold mine
[[./NCE2/L55 Not a gold mine.html]]
gold: [ɡəʊld] n.金子
mine: [maɪn] n.矿
treasure: [ˈtreʒə(r)] n.财宝
revealer: [rɪˈvi:lə] n.探测器
invent: [ɪnˈvent] v.发明
detect: [dɪˈtekt] v.探测
bury: [ˈberi] v.埋藏
cave: [keɪv] n.山洞
seashore: [ˈsiːʃɔː(r)] n.海岸
pirate: [ˈpaɪrət] n.海盗
arm: [ɑːm] v.武装
soil: [sɔɪl] n.泥土
entrance: [ˈentrəns] n.入口
finally: [ˈfaɪnəli] adv.最后
worthless: [ˈwɜːθləs] adj.毫无价值的
thoroughly: [ˈθʌrəli] adv.彻底地
trunk: [trʌŋk] n.行李箱
confident: [ˈkɒnfɪdənt] adj.有信心的
value: [ˈvæljuː] n.价值

own + a gold mine: 拥有一座金矿
a treasure map: 藏宝图
in a cave: 在山洞里
near/to the seashore: 靠近/靠近海岸
pirate stories: 海盗的故事
arm sb./sth. with sth.: 用某物武装某人
sb. be armed with sth.: 某人被某物武装
in dry soil: 在干燥的土壤中
find / miss + entrance: 找到/错过+入口
You're worthless.: 你一文不值
I'm not worthless.:  我不是一文不值
car trunk: 汽车后备箱
sb. be confident that ...: + 句子 某人确信……
something of value: 有价值的东西

--------------------
would do VS used to do
	- 过去状态只用used to do
	- used to do包含现在不发生了
	- used to do讨论过去习惯行为(不重要)
where & whose 引导的定语从句

dreams come true...: 梦想成真
be used to do sth.: 被用于做某事
fairly soon ...: 很快……
I'm fairly certain that +句子: 我很确定
I'm fairly confident that + 句子: 我很确信

** L56 Faster than sound!
[[./NCE2/L56 Faster than sound.html]]
sound: [saʊnd] n.声音
excitement: [ɪkˈsaɪtmənt] n.激动,兴奋
handsome: [ˈhænsəm] adj.漂亮的;美观的
Rolls-Royce: [ˌrəʊlz ˈrɔɪs]
Benz: [benz] n.
wheel: [wiːl] n.轮子
explosion: [ɪkˈspləʊʒ(ə)n] n.爆炸,轰鸣
course: [kɔːs] n.跑道,行程
rival: [ˈraɪv(ə)l] n.对手
speed: [spiːd] v.疾驶
downhill: [ˌdaʊnˈhɪl; ˈdaʊnhɪl] adv. adj.下坡

make a sound: 发出声音
hear a sound: 听到声音
on the course: 在过程中
speed it/things/this up: 加快速度
go downhill: 走下坡路

--------------------
adj.er
adj.est
more + adj.
the most + adj.

a great deal of ...: 不可数 大量的
a great many + 可数: 相当多的
break down: 停止运行
A be different form B: A不同于b

** L57 Can I help you, madam?
[[./NCE2/L57 Can I help you, madam.html]]
madam: [ˈmædəm] n.太太,夫人
jeans: [dʒiːnz] n.牛仔裤
hesitate: [ˈhezɪteɪt] v.犹豫,迟疑
serve: [sɜːv] v.接待(顾客)
scornfully: [ˈskɔːnfəli] adv.轻蔑地
punish: [ˈpʌnɪʃ] v.惩罚
fur: [fɜː(r)] n.裘皮
eager: [ˈiːɡə(r)] adj.热切的,热情的

hesitate to do sth.: 犹豫做某事
be eager to do sth.: 渴望做某事
ask/laugh/look at/ said + scornfully: 轻蔑地问/笑/看/说
look down on sb.: 看不起某人

--------------------
the way that/in which(可省略) + ...: 特殊的定语从句,从句修饰the way
	1. The assistant who served her did not like the way she was dressed.
	2. I don't like the way (that) you talk to me.
	3. We want to know the way (in which) you learn new words.

ask to do sth.: 请求做某事
be dressed in ...: 穿着
seek out: 寻找并找到
make sb. do sth.: 使(迫使)某人做某事

** L58 A blessing in disguise?
[[./NCE2/L58 A blessing in disguise.html]]
blessing: [ˈblesɪŋ] n.福分,福气
disguise: [dɪsˈɡaɪz] n.伪装
tiny: [ˈtaɪni] adj.极小的
possess: [pəˈzes] v.拥有
cursed: [kɜːst; ˈkɜːsɪd] adj.可恨的
increase: [ɪnˈkriːs] v.增加
plant: [plɑːnt] v.种植
church: [tʃɜːtʃ] n.教堂
evil: [ˈiːv(ə)l] adj.坏的
reputation: [ˌrepjuˈteɪʃ(ə)n] n.名声
claim: [kleɪm] v.以...为其后果
victim: [ˈvɪktɪm] n.受害者,牺牲品
vicar: [ˈvɪkə(r)] n.教区牧师
source: [sɔːs] n.来源
income: [ˈɪnkʌm] n.收入
trunk: [trʌŋk] n.树干

It is a blessing that ...: 这是一件幸事……
what a blessing: 真是福气
God bless you: 上帝保佑你
It's a blessing: 这是一种祝福
a blessing in disguise: 因祸得福
In one's possession: 在某人手中
Go to church: 参加教堂礼拜
Go to the church: 去教堂
have a good/bad reputation: 有好名声/坏名声
Have a reputation for...: 有……的名声
baggage claim: 行李领取区
source of income/information: 收入来源/信息来源

--------------------
be said to do...: 据说
It is said that...: 据说

强调句:
	- It is(was) + 强调部分 + that(who) + 剩余部分?
	- do/does/did + v.
被动: 复习L34 & L10

a number of: 大量
sb. point out that...: 有人指出……

** L59 In or out?
[[./NCE2/L59 In or out.html]]
bark: [bɑrk] v. 狗叫
press: [pres] v.按,压
paw: [pɔ] n.脚
latch: [lætʃ] n.门闩
expert: [ˈekˌspɜrt] n.专家
develop: [dɪˈveləp] v.养成
habit: [ˈhæbɪt] n.习惯
remove: [rɪˈmuv] v.拆掉,取下

become/be an expert at doing sth./sth.: 成为做某事的专家
have a habit of doing sth.: 有做某事的习惯
remove sth. from ...: 把某物从……移除

--------------------
表目的
	- + do sth.
		to
		in order to
		so as to
  - + ...(句子)
		so that 目的状语从句
		in order that: 目的

complained of ...: 抱怨……
complain that: 抱怨……
spend st. doing sth.: 花时间做某事;
train sb. to do sth.: 训练某人做某事

** L60 The future
[[./NCE2/L60 The future.html]]
future: [ˈfjutʃər] n.未来,前途
fair: [fer] n.集市
fortune-teller: [ˈfɔrtʃ(ə)n] n.算命人
crystal: [ˈkrɪst(ə)l] n.水晶
relation: [rɪˈleɪʃ(ə)n] n.亲属
impatiently: [ɪmˈpeɪʃəntlɪ] adv.不耐烦的

in the future: 在将来 
at a village fair: 在一个乡村集市上
crystal clear: 如水晶般清澈的
a relation of yours: 你的一个亲戚

--------------------
A先B后
the moment A ... B..: 一A就B
	Everything stops the moment she walks in the room.
as soon as(主将从现): 一A就B(主从都表将来时,从句用现在时即可)
	As soon as the rain stops, we shall go out.
主将从现: 主从都表将来时,从句用现在时即可
	the moment/util/when/as soon as/while/before

** L61 Trouble with the Hubble
[[./NCE2/L61 Trouble with the Hubble.html]]
Hubble: [hʌb(ə)l] n.哈勃
telescope: [ˈteləˌskoʊp] n.望远镜
launch: [lɔntʃ] v.发射
space: [speɪs] n.空间
NASA: [ˈnæsə] n. National Aeronautics and Space Administration
billion: [ˈbɪljən] n.10亿
faulty: [ˈfɔlti] adj.有错误的
astronaut: [ˈæstrənɔːt] n.宇航员
shuttle: [ˈʃʌt(ə)l] n.航天飞机
Endeavour: [ɪn'devər] n."奋进"号
robot-arm: [ˈroʊˌbɑt] [ɑrm] n.机器手
grab: [ɡræb] v.抓
atmosphere: [ˈætməˌsfɪr] n.大气层
distant: [ˈdɪstənt] adj.遥远的
galaxy: [ˈɡæləksi] n.星系
universe: [ˈjunɪvərs] n.宇宙
eagle [ˈɪɡ(ə)l] eye: 鹰眼

grab a beer/coffee: 喝杯啤酒/咖啡

--------------------
will be doing
will have done
will have been doing: 动作持续(重复)到将来 ?

right from the start: 从一开始

** L62 After the fire
[[./NCE2/L62 After the fire.html]]
control: [kənˈtroʊl] n.控制
smoke: [smoʊk] n.烟
desolate: [ˈdesələt] adj.荒凉的
threaten: [ˈθret(ə)n] v.威胁
surrounding: [səˈraʊndɪŋ] adj.周围的
destruction: [dɪˈstrʌkʃ(ə)n] n.破坏,毁灭
flood: [flʌd] n.洪水,水灾
authority: [ɔˈθɔrəti] n.(常用复数)当局
grass-seed: [ɡræs] [sid] n.草籽
spray: [spreɪ] v.喷撒
quantity: [ˈkwɑntəti] n.量
root: [rut] n.根
century: [ˈsentʃəri] n.世纪
patch: [pætʃ] n.小片
blacken: [ˈblækən] v.变黑,发黑

get it under control: 控制住它
be under control: 得到控制
threaten sb. with sth.: 用某事威胁某人
threaten to do sth.: 威胁要做某事
have the authority to do sth.: 有权力做某事
a large/small quantity of sth.: 大量/少量的某物(nu.&nc.)
take root: 生根
for centuries: 几个世纪以来
a part of sth.: 某物的一部分

--------------------
had been doing: 1.过去A进行的v.对过去B有影响;2.过去A进行的v.持续(重复)到过去B

A short time before: 不久之前
for miles around: 方圆数英里
in place of...: 代替……

** L63 She was not amused
[[./NCE2/L63 She was not amused.html]]
circle: [ˈsɜrk(ə)l] n.圈子
admire: [ədˈmaɪr] v.赞美,钦佩
close: [kloʊs] adj.亲密的
wedding: [ˈwedɪŋ] n.婚礼
reception: [rɪˈsepʃən] n.招待会
sort: [sɔrt] n.种类

a large circle of friends: 很大的朋友圈
admire sb. for sth./doing sth.: 钦佩某人做某事
close friend: 亲密的朋友
at the reception: 在招待会上
what sort of/what kind of...: 什么种类的
all sorts of/ all kinds of...: 各种各样的

--------------------
as: in the way or manner that: 按照...方式
	You'll do as I say and ask no questions.
like
as if
as though

sense of humour/humor: 幽默感/幽默感
make a speech: 发表演讲
a large number of ...: 大量的+nc.
on the way home: 在回家的路上

** L64 The Channel Tunnel
[[./NCE2/L64 The Channel Tunnel.html]]
tunnel: [ˈtʌn(ə)l] n.隧道
port: [pɔrt] n.港口
ventilate: [ˈvent(ə)lˌeɪt] v.通风
chimney: [ˈtʃɪmni] n.烟囱
sea:	level [ˈlev(ə)l] 海平面
double: [ˈdʌb(ə)l] adj.双的
ventilation: [ˌvent(ə)lˈeɪʃ(ə)n] n.通风
fear: [fɪr] v.害怕
invasion: [ɪnˈveɪʒ(ə)n] n.入侵,侵略
officially: [əˈfɪʃ(ə)li] adv.正式地
connect: [kəˈnekt] v.连接
European: [ˌjʊrəˈpiən] adj.欧洲的
continent: [ˈkɑntɪnənt] n.大陆

in the tunnel: 在隧道里
above/below sea level: 高于/低于海平面
double check: 仔细检查
Sb. fear that + 句子: 某人担心

--------------------
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
suggest that ... (should) do ...

it is possible to do sth...: 做某事是可能的
a serve as b: A当作B
solve the problem of a ...: 解决…的问题
put forward a plan ...: 提出一个计划

** L65 Jumbo versus the police
[[./NCE2/L65 Jumbo versus the police.html]]
versus: [ˈvɜrsəs] prep.对
Christmas: [ˈkrɪsməs] n.圣诞节
circus: [ˈsɜrkəs] n.马戏团
present: [ˈprezənt] n.礼物
accompany: [əˈkʌmpəni] v.陪伴,随行
approach: [əˈproʊtʃ] v.走进
ought: [ɔt] modal verb.应该
weigh: [weɪ] v.重
fortunate: [ˈfɔrtʃənət] adj.幸运的

How much do you weigh?: 你体重多少
It is fortunate that + 句子...: 很幸运的是...

--------------------
should do/ought to do: 肯应该,否不应该
should have done/ought to have done: 本该做某事,却没有做,指责效果

be dressed up as...: 打扮成……
set off: 出发
hold up the traffic/line: 阻塞交通
let sb. off: 不惩罚某人
agreed to do sth.: 同意做某事

** L66 Sweet as honey!
[[./NCE2/L66 Sweet as honey.html]]
Lancaster: [ˈlæŋkəstər] n.
bomber: [ˈbɑmər] n.轰炸机
remote: [rɪˈmoʊt] adj.偏僻的
Pacific: [pəˈsɪfɪk] n.太平洋
damage: [ˈdæmɪdʒ] v.毁灭
wreck: [rek] n.残骸
rediscover: [ˌridɪˈskʌvər] v.重新发现
aerial: [ˈeriəl] adj.航空的
survey: [ˈsɜrˌveɪ] n.调查
rescue: [ˈreskju] v.营救
package: [ˈpækɪdʒ] v.把...打包
enthusiast: [ɪnˈθuziæst] n.热心人
restore: [rɪˈstɔr] v.修复
imagine: [ɪˈmædʒɪn] v.想象
packing case: [ˈpækɪŋ] 包装箱
colony: [ˈkɑləni] n.群
bee: [bi] n.蜂
hive: [haɪv] n.蜂房
preserve: [prɪˈzɜrv] v.保护
beeswax: [ˈbizˌwæks] n.蜂蜡

remote control: 遥控
do a survey: 进行调查
Can you imagine that?: 你能想象吗?
It's hard to imagine.: 这很难想象
A colony of bees: 一群蜜蜂

--------------------
have sth. done = get sth. done: 1.使得某事被别人做;2.不幸的遭遇

over the years: 多年来
in reasonable condition: 在理想条件下
be worth doing...: 值得做……
turn A into B: 把a变成b。

** L67 Volcanoes
[[./NCE2/L67 Volcanoes.html]]
volcano: [vɑlˈkeɪnoʊ] n.火山
active: [ˈæktɪv] adj.活动的
Kivu: ['kivu] n. Congo ['kɒŋɡəʊ] n. Kituro n.
erupt: [ɪˈrʌpt] v.(火山)喷发
violently: [ˈvaɪələntli] adv. violent [ˈvaɪələnt] adj.猛烈地,剧烈地
manage: [ˈmænɪdʒ] v.设法
brilliant: [ˈbrɪljənt] adj.精彩的
liquid: [ˈlɪkwɪd] adj.液态的
escape: [ɪˈskeɪp] v.n.逃脱
alive: [əˈlaɪv] adj.活着的

What a brilliant idea!: 多棒的主意!
That's brilliant!: 那太棒了
--------------------
managed to do VS was able to do: 成功做成了某事(事例) VS ~ + 过去有能力做成某事

name sth. A: 命名某物为A
set up his camp/tent: 搭起他的帐篷
sb. noticed that + sentence: 某人注意到+...

** L68 Persistent
[[./NCE2/L68 Persistent.html]]
persistent: [pərˈsɪstənt] adj.坚持的,固执的
avoid: [əˈvɔɪd] v.避开
insist: [ɪnˈsɪst] v.坚持做
cross: [krɔs] v. across [əˈkrɔs] prep. 穿过

avoid doing sth.: 避免做某事
insist on doing sth.: 坚持做某事
It is no use pretending that + sentence: 假装...是没有用的
prevent sb. from doing sth.: 阻止某人做某事;
Fancy meeting you here.: 没想到在这遇见你
--------------------
no matter how/what/where/whose/who/which/when ?
even though(although/though/as) VS even if

enjoy doing sth.: 享受做某事
no matter how/what/where: 无论如何/什么/在哪里
follow sb. around: 围绕某人转/走
I was wondering.. + sentence: 我在想...
would you mind my doing...: 你介意我做……吗?
finish doing sth.: 完成做某事

** L69 But not murder
[[./NCE2/L69 But not murder.html]]
murder: [ˈmɜrdər] n.谋杀
instruct: [ɪnˈstrʌkt]  v.命令,指示
acquire: [əˈkwaɪr]  v.取得,获得
confidence: [ˈkɑnfɪdəns]  n. confident adj.信心
examiner: [ɪɡˈzæmɪnər] n.主考人
suppose: [səˈpoʊz] v.假设
tap: [tæp] v.轻敲
react: [riˈækt] v.反应
brake: [breɪk] n.刹车 pedal n.踏板
mournful: [ˈmɔrnfəl] adj.悲哀的

be instructed to do sth.: 被指示做某事
Let's suppose that...: 让我们假设……
tap on the window:  敲窗
--------------------
having been done

continue doing/ to do: 继续做/去做
be pleased with: 对……感到满意

** L70 Red for danger
[[./NCE2/L70 Red for danger.html]]
bullfight: [ˈbʊlˌfaɪt] n.斗牛 ring n.园形竞技场地
drunk: [drʌŋk] n.醉汉
wander: [ˈwɑndər] v.溜达,乱走
unaware: [ˌʌnəˈwer] adj.不知道的,未察觉的
bull: [bʊl] n.公牛 matador [ˈmætədɔr] n.斗牛士
remark: [rɪˈmɑrk] n.v.评论;言语 make that stupid remark
apparently: [əˈperəntli] adv.明显地
sensitive: [ˈsensətɪv] adj.敏感的
criticism: [ˈkrɪtɪˌsɪzəm] n.批评
charge: [tʃɑrdʒ] v.冲上去
clumsily: ['klʌmzɪli] adv.笨拙地
bow: [baʊ] v.鞠躬
safety: [ˈseɪfti] n.安全地带
sympathetically: [ˌsɪmpə'θetɪklɪ] adv.同情地

be unaware of …: 未意识到
be aware/conscious of …: 意识到……
make that stupid remark: 说那种愚蠢的话
be sensitive about sth.: 对某事敏感
accept criticism: 接受批评
charge at sb. = attack: 向某人冲去
for your safety: 为了您的安全
--------------------

be busy with sth.: 忙于某事
at the time: 在当时
catch sight of a.: 看到…
grow quiet...: 变得宁静
get close to a.: 接近A
step aside: 让开;走到一旁
break into cheers: 爆发出欢呼声
feel sorry for sb.: 为某人感到难过;同情某人
look on ...: 旁观
out of the way …: 不挡道
turn sb’s attention to a.: 把某人的注意力转移到…
once more: 再一次

** L71 A famous clock
[[./NCE2/L71 A famous clock.html]]
parliament [ˈpɑrləmənt]: n.议会,国会
erect [ɪˈrekt]: v.建起
accurate [ˈækjərət]: adj.准确的
official [əˈfɪʃ(ə)l]: n.adj.官员,行政人员
Greenwich [ˈgrɪnɪdʒ]: n.
observatory [əbˈzɜrvəˌtɔri]: n.天文台
check [tʃek]: v.n.检查
microphone [ˈmaɪkrəˌfoʊn]: n.扩音器,麦克风
tower [ˈtaʊr]: n.塔

make it official: 使其正式化
double check: 复查
--------------------

all over the world: 全世界
burn down: 烧毁
take its name from: 以……命名
be responsible for: 对……负责
be connected to: 与……相连
go wrong: 出错

** L72 A car called Bluebird
[[./NCE2/L72 A car called Bluebird.html]]
racing: [ˈreɪsɪŋ] n.竞赛
per: [pɜr] prep.每
Utah: ['ju:ta:] n.犹他(美国州)
horsepower: [ˈhɔrsˌpaʊr] n.马力
burst: [bɜː(r)st] v.爆裂
average: [ˈæv(ə)rɪdʒ] adj.平均的
footstep: [ˈfʊtˌstep] n.足迹

burst into tears: 突然哭起来
follow in sb't footsteps: 效法某人
--------------------
have difficulty in doing sth.: 做某事有困难
be disappointed to learn that: 某人了解到...很失望

** L73 The record-holder
[[./NCE2/L73 The record-holder.html]]
record-holder: [ˈhoʊldər] n.记录保持者
truant: [ˈtruənt] n.逃学的孩子
unimaginative: [ˌʌnɪˈmædʒɪnətɪv] adj.缺乏想象力的
shame: [ʃeɪm] n.惭愧,羞耻
hitchhike: [ˈhitʃˌhaɪk] v.搭便车旅行
meantime: [ˈminˌtaɪm] n.其间
lorry: [ˈlɔri] n.卡车
border: [ˈbɔrdər] n.边界
evade: [ɪˈveɪd] v.逃避,逃离

play truant from school: 逃学
be put to shame = put sb. to shame: 把某人比下去
shame on you: 真可耻
hitchhike to sw.: 搭便车去某地
in the meantime: 在此期间
--------------------
612345+6123456(6123456)

over and over again: 反复不断地

** L74 Out of the limelight
[[./NCE2/L74 Out of the limelight.html]]
limelight: ['laɪmlaɪt] n.舞台灯光
precaution: [prɪˈkɔʃ(ə)n] n.预防措施
fan: [fæn] n.狂热谜,迷
shady: [ˈʃeɪdi] adj.遮荫的
sheriff: [ˈʃerɪf] n.司法长官
notice: [ˈnoʊtɪs] n.v.告示
sneer: [snɪr] n.v.冷笑

stay out of the limelight: 避免引人注目
take precaution: 采取预防
sb. is a big/huge fan of a.: 某人是……的超级粉丝
on such short notice: 在这么短的时间内
with a sneer/ sneer at sb.: 对某人冷笑地
--------------------
a party of: 一群
why don't we: 为什么我们不
carry sth. to sw.: 将某物带到某处
make oneself comfortable: 别客气
don't be too hard on us: 不要对我们太苛刻
get out of here: 离开这里

** L75 SOS
[[./NCE2/L75 SOS.html]]
thick: [θɪk] adj.厚的
signal: [ˈsɪɡnəl] n.信号
stamp: [stæmp] v.踩,跺
helicopter: [ˈhelɪˌkɑptər] n.直升飞机
scene: [sin] n.现场
survivor: [sərˈvaɪvər] n.幸存者

send a signal: 发出信号
stamp out the fire: 扑灭大火
arrive on the scene: 到达现场
--------------------
fly off course: 偏离航线
cover sb./sth/ with a.: 用…盖住某人/某物
get adj.: 变得...
It was not long before...: 没过多久……

** L76 April Fool's Day
[[./NCE2/L76 April Fool's Day.html]]
fool: [ful] n.傻瓜
bulletin: [ˈbʊlətɪn] n.新闻简报
announcer: [əˈnaʊnsər] n.(电视,电台)播音员
macaroni: [ˌmækəˈroʊni] n.通心面,空心面条
leading: [ˈlidɪŋ] adj.主要的 + cause(s)
grower: [ˈɡroʊr] n.种植者
splendid: [ˈsplɛndid] adj.极好的 + idea/example/view/garden
stalk: [stɔk] n.梗
gather: [ˈɡæðər] v.收庄稼 thresh v.打(庄稼)
process: [prəˈses] v.加工
Signor: ['siːnjɔː] n.(意大利语)先生
present: [ˈprezənt] adj.目前的
champion: [ˈtʃæmpiən] n.冠军
studio: [ˈstudiˌoʊ] n.播音室

on the bulletin board: 在布告栏上
leading cause of ...:的主要原因
What a splendid/brilliant idea!: 多棒的主意啊!
--------------------
at the end of ...: 在……结束时

** L77 A successful operation
[[./NCE2/L77 A successful operation.html]]
mummy: [ˈmʌmi] n.木乃伊
Egyptian: [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple: [ˈtemp(ə)l] n.庙
mark: [mɑrk] n.斑点
plate: [pleɪt] n.底片
disease: [dɪˈziz] n.疾病
last: [læst] v.持续
prove: [pruv] v.显示出
resin: [ˈrezɪn] n.树脂
skin: [skɪn] n.皮,皮肤
section: [ˈsekʃ(ə)n] n.切片
figure: [ˈfɪɡjər] n.(人的)体形; 人像
normally: [ˈnɔrm(ə)li] adv.通常地
survive: [sərˈvaɪv] v.幸免于

have a rare disease: 患有罕见的疾病
a section of ...: 一部分
prove to be adj.: 证明是…
--------------------
非限定定语从句: 解释,补充,说明
	- which非限整句:
		+ 位置: 句尾
		+ 指代被修饰词
	- as非限整句
		- 位置: 前中后
		- 指代整句
	- 非限定只能who/which/whose
		- none of/neither of/any of/either of + which/whom
		- some of/many of/much of/(a) few of + which/whom
		- both of/ half of /each of/one of/two of + which/whom

--------------------
have an operation: 动手术
died of ...: 死于……
fall to pieces: 破碎
cut it open: 把它切开

** L78 The last one
[[./NCE2/L78 The last one.html]]
entitle: [ɪnˈtaɪt(ə)l] v.以...为名
calm: [kɑm] v.使镇静
nerve: [nɜrv] n.神经
concentration: [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer: [ˈsʌfər] v.受苦
symptom: [ˈsɪmptəm] n.症状
temper: [ˈtempər] n.脾气
appetite: [ˈæpəˌtaɪt] n.胃口
produce: [prəˈdus] v.拿出
urge: [ɜrdʒ] v.怂恿
satisfaction: [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted: [dɪˈlaɪtəd] adj.欣喜的

entitle sb. to do sth.: 使某人有权利做某事
calm down: 冷静下来
keep calm: 保持冷静
calm my nerve: 镇定我的神经
have/get the nerve to do sth.: To draw upon one's courage or resolve to do something 鼓起勇气做某事
lose sb's nerve: 失去某人的勇气
lose/break/have sb's concentration: 某人无法集中注意力
suffer from: 遭受
have a good/bad temper: 有好/坏脾气
lose sb's temper: 发脾气
have/get a good/great appetite: 有个好胃口
lose sb's appetite: 失去食欲
urge sb. to do sth.: 敦促某人做某事
give him satisfaction: 给他满足感
sb. be delighted that + ...: 某人很高兴+……
--------------------
light a cigarette: 点燃一支烟
sb. be sure that + ...: 某人确信……
keep on doing sth.: 继续做某事
offer sb. sth.: 给某人提供某物
make no effort to do sth.: 不努力做某事
a packet of...: 一包……
return to normal: 恢复正常

** L79 By air
[[./NCE2/L79 By air.html]]
parent: [ˈperənt] n.父母亲
flight [flaɪt] attendant [əˈtendənt]: 空中乘务员
frightened: [ˈfraɪt(ə)nd] adj.害怕,担惊
curious: [ˈkjʊriəs] adj.急于了解,好奇的
bomb: [bɑm] n.炸弹 plant v.安放

feel frightened: 感觉害怕
sb. be curious to find out + ...: 某人很想知道……
plant a bomb: 安置炸弹
--------------------
Only部分倒装
1. Only(+其他部分)句首,并且不是修饰主语
	 Only police can come in. 不能倒装
2. 主句一般疑问句的语序
--------------------
a great deal: 大量的
take charge of: 负责某事
be used to doing: 习惯做某事
take off: 起飞
gain height: 提升高度
touch down: 着陆
on board: 在船上

** L80 The Crystal Palace
[[./NCE2/L80 The Crystal Palace.html]]
palace: [ˈpæləs] n.宫殿
extraordinary: [ɪkˈstrɔrd(ə)nˌeri] adj.不平常的,非凡的
exhibition: [ˌeksɪˈbɪʃ(ə)n] n.展览
iron: [ˈaɪrn] n.铁
various: [ˈveriəs] adj.各种各样的
machinery: [məˈʃinəri] n.机器
display: [dɪˈspleɪ] n.展览
steam: [stim] n.蒸汽
profit: [ˈprɑfɪt] n.利润
college: [ˈkɑlɪdʒ] n.学院

on show/on display: 展览
make a profit: 赚取利润
go to college: 上大学
--------------------
be made of: 由……制成
of all time: 有史以来的
in all: 总共
** L81 Escape
	[[./NCE2/L81 Escape.html]]
prisoner: [ˈprɪz(ə)nər] n.囚犯
bush: [bʊʃ] n.灌木丛
rapidly: ['ræpɪdli] adv.迅速地
uniform: [ˈjunɪˌfɔrm] n.制服
rifle: [ˈraɪf(ə)l] n.来福枪,步枪
shoulder: [ˈʃoʊldər] n.肩
march: [mɑrtʃ] v.行进
boldly: ['bəʊldli] adv.大胆地
blaze: [bleɪz] v.闪耀
salute: [səˈlut] v.行礼
elderly: [ˈeldərli] adj.n.上了年纪的
grey: [ɡreɪ] adj.灰白的
sharp: [ʃɑrp] adj.猛烈的 blow n.打击

grow/change/move... + rapidly: 成长/改变/移动……+ 快速地
with a sharp blow: 用一记猛击
--------------------
change into ...: 换上...(衣服)
up and down ...: 上上下下
sb. discovered that: 某人发现
stand to attention: 立正
knock him to the ground: 击打某人在地
** L82 Monster or fish?
[[./NCE2/L82 Monster or fish.html]]
monster: [ˈmɑnstər] n.怪物
sailor: [ˈseɪlər] n.海员
sight: [saɪt] v.见到
creature: [ˈkritʃər] n.动物,生物
peculiar: [pɪˈkjuljər] adj.奇怪的,不寻常的
shining: [ˈʃaɪnɪŋ] adj.闪闪发光的
oarfish: ['ɔːfɪʃ] n.浆鱼

shining example: 光辉榜样 
--------------------
claim to have done sth.: 声称做过某事
laugh at ...: 嘲笑某人
it is (well) known that ...: 众所周知，……
at times: 有时候
out at sea: 在海上
in any way: 以任何方式
it was found to be ...: 它被发现是……
a depth of ...(34 ft): xx的深度
** L83 After the elections
[[./NCE2/L83 After the elections.html]]
election: [ɪˈlekʃ(ə)n] n.选举
former: [ˈfɔrmər] adj.从前的
defeat: [dɪˈfit] v.打败
fanatical: [fəˈnætɪk(ə)l] adj.狂热的
opponent: [əˈpoʊnənt] n.反对者,对手
radical: [ˈrædɪk(ə)l] adj.激进的
progressive: [prəˈɡresɪv] adj.进步的
ex-:  [eks] prefix 前...
suspicious: [səˈspɪʃəs] adj.怀疑的

win the election: 赢得选举
be fanatical about sth./doing sth.: 对某事/做某事狂热
--------------------
on duty: 在工作状态
on the following day: 第二天
love to do sth.: 喜欢做某事
** L84 On strike
[[./NCE2/L84 On strike.html]]
strike: [straɪk] n.罢工
busman: ['bʌsmən] n. bus driver公共汽车司机
state: [steɪt] v.正式提出,宣布
agreement: [əˈɡrimənt] n.协议
relieve: [rɪˈliv] v.减轻
pressure: [ˈpreʃər] n.压力,麻烦
extend: [ɪkˈstend] n.程度
volunteer: [ˌvɑlənˈtɪr] v.n.自动提出,自愿
gratitude: [ˈɡrætɪˌtud] n.感激
press: [pres] n.新闻界
object [ɑbˈdʒekt] v. objection n.:不赞成,反对

go on strike: 罢工
sb. have stated that + ...: 有人说……
agreement is reached about sth.: 就某事达成协议
reach an agreement: 达成协议
sb. be relieved to hear that + ...: 某人听到……感到宽慰
relieve pressure: 缓解压力
under a lot of pressure: 在很大压力下
to some extend: 在某种程度下
volunteer to do sth.: 自愿做某事
expressed sb.'s gratitude to sb.: 像某人表示某人的感谢
sb. have objected that + ...: 有人反对+……
object to sth./sb.: 反对某事/某人
--------------------
be due to do = be going to do

--------------------
be due to do sth.: 预定做某事
pass/take the test: 通过/参加考试
** L85 Never too old to learn
[[./NCE2/L85 Never too old to learn.html]]
inform: [ɪnˈfɔrm] v.告诉,通知
headmaster: [ˈhedˌmæstər] n.校长
contribute: [ˈkɑntrɪˌbjut] v.捐助,援助
gift: [ɡɪft] n.礼物,赠品
album: [ˈælbəm] n.签名簿,相册
patience: [ˈpeɪʃəns] n.耐心
encouragement: [ɪnˈkʌrɪdʒmənt] n.鼓励
farewell: [ferˈwel] n.告别
honour: [ˈɑnər] honor n.敬意
coincidence: [koʊˈɪnsɪdəns] n.巧合
total: [ˈtoʊt(ə)l] n.总数
devote: [dɪˈvoʊt] v.致力于
gardening: [ˈɡɑrd(ə)nɪŋ] n.园艺
hobby: [ˈhɑbi] n.爱好,嗜好

sb. inform sb. that + ...: 某人通知某人
make a contribution: 做贡献
contribute to sth.: 促成某事物
lose sb's patience: 失去某人的耐心 
have a lot of patience: 有很多耐心
give sb. encouragement: 给某人鼓励
in one's honor: it is done specially to show appreciation of them 纪念某人
It is a curious coincidence that + ...: 这是一个奇怪的巧合……
a total of ...(176): 总共176
devote oneself to sth./doing sth.: 投身于某事/做某事
--------------------
mark the occassion: 纪念这个场合
remember sb. for sth.: 因某事记住某人
** L86 Out of control
[[./NCE2/L86 Out of control.html]]
swing: [swɪŋ] swung v.转向
speedboat: [ˈspidˌboʊt] n.快艇
desperately: [ˈdesp(ə)rət(ə)li] adv.绝望地
companion: [kəmˈpænjən] n. 同伴,伙伴
water: [ˈwɔtər] ski [ski] (由快艇牵引)滑水
buoy: [ˈbui] n.浮标
dismay: [dɪsˈmeɪ] n.沮丧
tremendous: [trəˈmendəs] adj.巨大的
petrol: [ˈpetrəl] n.汽油
drift: [drɪft] v.漂动,漂流
gently: [ˈdʒentli] adv.缓慢地,轻轻地

sb. noticed with dismay that + ...: 某人惊慌地注意到……
at tremendous speed: 以惊人的速度
--------------------
come away: 脱落
move in a circle: 以圈移动
be used up: 用完
before long: 不久之后
** L87 A perfect alibi
[[./NCE2/L87 A perfect alibi.html]]
alibi: [ˈælɪˌbaɪ] n.不在犯罪现场
commit: [kəˈmɪt] v.犯(罪,错)
inspector: [ɪnˈspektər] n.探长
employer: [ɪmˈplɔɪər] n.雇主
confirm: [kənˈfɜrm] v.确认,证实
suggest: [səɡˈdʒest] v.提醒
truth: [truθ] n.真相

have a alibi: 有不在场证明
commit a murder: 犯下谋杀罪
sb. confirm that + ...: 某人证实……
Are you suggesting + ...: 你是在表示...
tell the truth: 说实话
--------------------
on time: 准时
** L88 Trapped in a mine
[[./NCE2/L88 Trapped in a mine.html]]
trap: [træp] v.陷入,使陷入困境
surface: [ˈsɜrfəs] n.地面,表面
explosive: [ɪkˈsploʊsɪv] n.炸药
vibration: [vaɪˈbreɪʃ(ə)n] n.震动
collapse: [kəˈlæps] v.n.坍塌
drill: [drɪl] v.n.钻孔
capsule: [ˈkæpˌsjul] n.容器
layer: [ˈleɪr] n.层
beneath: [bɪˈniθ] prep.在...之下
lower: [ˈloʊr] v.adj.放下,降低
progress: [prəˈɡres] v.n.进展,进行
smoothly: [ˈsmuːðli] adv.顺利地

on the surface: 表面上
in a special capsule: 在一个特殊的胶囊里
layers of: 几层的...
a layer of: 一层的...
make progress: 取得进展
go/run smoothly: 进展顺利
--------------------
wish型虚拟语气: 从句: should(可省略) do

lose one's life: 死亡
As it is...: 事实上(状语)
enable sb. to do sth.: 使某人能够做某事
keep in touch with ...: 与……保持联系
run out of ...: 用完
lose heart ...: 丧失信心
cause sb./sth/ to do sth.: 造成某人做某事
** L89 A slip of the tongue
[[./NCE2/L89 A slip of the tongue.html]]
slip: [slɪp] n.小错误
comedy: [ˈkɑmədi] n.喜剧
present: [ˈprezənt] v.演出 adj.出席,到场的
queue: [kju] v.n.排队
dull: [dʌl] adj.枯燥,无味
artiste: [ɑrˈtist] n.artist 艺人
advertiser: [ˈædvərˌtaɪzər] n.报幕员

a slip of the tongue: 口误
a comedy show: 喜剧表演
hold up the queue: 排队等候
--------------------
do anything to do sth.: 尽一切努力做某事
the news get around: 消息传开了
feel disappointed: 感到失望
at the beginning of a.: 在……的开始
burst out laughing: 突然大笑
** L90 What's for supper? 
[[./NCE2/L90 What's for supper.html]]
chip: [tʃɪp] n.油煎土豆片
overfish: [ˌoʊvə'fɪʃ] v.过度捕捞
giant: [ˈdʒaɪənt] adj.巨大的
terrify: [ˈterəˌfaɪ] v.吓,使恐怖
diver: [ˈdaɪvər] n.潜水员
oil: rig [ɔɪl] [rɪɡ] 石油钻塔
wit: [wɪt] n.(复数)理智,头脑
cage: [keɪdʒ] n.笼
shark: [ʃɑrk] n.鲨鱼
whale: [hweɪl] n.鲸
variety: [vəˈraɪəti] n.品种
cod: [kɒd] n.鳕 skate n.鳐
factor: [ˈfæktər] n.因素
crew: [kru] n.全体工作人员

be scared/frightened out of sb's wits: 把某人吓得魂不附体
a variety of: 各种各样的
--------------------
it comes as a surprise to learn that + ...: 得知...令人惊讶
protect a. from b.: 保护A远离B
in length: 在长度上(状语)
the (total) absence of ...: 没有...
as a result: 因此

** L91 Three men in a basket
[[./NCE2/L91 Three men in a basket.html]]
balloon: [bəˈlun] n.气球
royal: [ˈrɔɪəl] adj.皇家
spy: [spaɪ] v.侦察
track: [træk] n.轨迹,踪迹
binoculars: [bɪˈnɑkjələrz] n.望远镜

spy on sb./sth.: 监视某人/某物
keep track of: 跟踪
--------------------
seem to be doing ...: 似乎正在做……
make for sw.: 向...前进
make out: 弄清
soon afterwards: 不久之后
be called in (to do): 被叫去做某事
** L92 Asking for trouble
[[./NCE2/L92 Asking for trouble.html]]
fast: [fæst] adv.熟(睡)
ladder: [ˈlædər] n.梯子
shed: [ʃed] n.棚子
sarcastic: [sɑrˈkæstɪk] adj.讽刺的,讥笑的
tone: [toʊn] n.语气,腔调

fast asleep: 熟睡的
Are you being sarcastic?: 你是在讽刺吗?
Don't take that tone with me!: 别用那种语气跟我说话!
--------------------
hate to do sth.: 讨厌做某事

** L93 A noble gift
[[./NCE2/L93 A noble gift.html]]
noble: [ˈnoʊb(ə)l] adj.高尚的,壮丽的
monument: [ˈmɑnjəmənt] n.纪念碑
statue: [ˈstætʃu] n.雕像 liberty n.自由
present: [ˈprezənt] v.赠送
sculptor: [ˈskʌlptər] n.雕刻家
actual: [ˈæktʃuəl] adj.实际的,真实的
copper: [ˈkɑpər] n.铜
support: [səˈpɔrt] v.支持,支撑
framework: [ˈfreɪmˌwɜrk] n.构架,框架
transport: [trænsˈpɔrt] v.运送
site: [saɪt] n.场地
pedestal: [ˈpedɪst(ə)l] n.底座

a noble gift/man: 一个高贵的礼物/人
camp site: 露营地
--------------------
at the entrance of ...: 在……入口处
take sth. to pieces: 把……拆散

** L94 Future champions
[[./NCE2/L94 Future champions.html]]
instruct: [ɪnˈstrʌkt] v.指导,传授
Los Angeles:
reluctant: [rɪˈlʌktənt] adj.勉强的,不愿意的
weight: [weɪt] n.重物
underwater: [ˌʌndə(r)ˈwɔːtə(r)] adj.水下的
tricycle: [ˈtraɪsɪk(ə)l] n.三轮车
compete: [kəmˈpit] v.比赛,对抗
yard: [jɑrd] n.码
gasp: [ɡæsp] v.喘气

be instructed in doing sth.: 受指导做某事
be reluctant to do sth.: 不情愿做某事
compete against: 与…竞争
--------------------
sb./sth. proved that + ...: 某人/某事证明了+…
hold sb's breath: 屏住呼吸
be accustomed to doing: 习惯于做某事
be popular with ...: 受到……的欢迎
be lined up: 排队等候
** L95 A fantasy
[[./NCE2/L95 A fantasy.html]]
fantasy: [ˈfæntəsi] n.幻想故事
ambassador: [æmˈbæsədər] n.大使
frightful: [ˈfraɪtf(ə)l] adj.可怕的,令人吃惊的
fire: [faɪr] extinguisher [ɪkˈstɪŋɡwɪʃər] 灭火器
drily: [ˈdraɪli] adv.冷淡地,鼓噪无味地
embassy: [ˈembəsi] n.大使馆
heaven: [ˈhev(ə)n] n.天,天堂
basement: [ˈbeɪsmənt] n.地下室
definitely: [ˈdefənɪtli] adv.肯定地
post: [poʊst] v.派任
shot: [ʃɑt] n.子弹

live in a fantasy world: 生活在幻想的世界里
Good heavens!: 天哪
fire a shot: 开一枪
--------------------
get into such a mess: 陷入困境
set sth. on fire: 放火烧某物
go on doing sth.: 继续做某事

** L96 The dead return
[[./NCE2/L96 The dead return.html]]
festival: [ˈfestɪv(ə)l] n.节目
lantern: [ˈlæntə(r)n] n.灯笼
spectacle: [ˈspektək(ə)l] n.景象,壮观,场面
moving: [ˈmuvɪŋ] adj.

make a spectacle of oneself: 出洋相
--------------------
return to sp.: 回到某地
be expected to be: 被期待做某事
sth. is laid out: 某物被布置好了
it is considered unlucky for sb. doing: 做某事被认为是不吉利的
be placed into: 被放置进入

* NCE3 
** L01 A puma at large
[[./NCE3/L01 A puma at large.html]]
puma: [ˈpjumə] n.美洲狮
spot: [spɑt] v.n.发现
evidence: [ˈevɪdəns] n.证据
accumulate: [əˈkjumjəˌleɪt] v.积累
oblige: [əˈblaɪdʒ] v.使...感到必须
hunt: [hʌnt] n.v.追猎
blackberry: [ˈblækˌberi] n.黑莓
human: [ˈhjumən] being [ˈbiɪŋ] n.人类
corner: [ˈkɔrnər] v.使走投无路
trail: [treɪl] n.一串
print: [prɪnt] n.v.印痕
cling: [klɪŋ] clung clung v.粘
convince: [kənˈvɪns] v.使...信服
somehow: [ˈsʌmhaʊ] adv.不知怎么搞地
disturb: [dɪˈstɜrb] v.令人不安

spot sb. doing sth.: 发现某人正在做某事
feel obliged to do sth.: 感到必须做某事
a trail of: a series of: 一系列
cling to sb./sth.: 粘在某人/某物上
sth. convinced sb. that + ...: 某事使某人信服...
sb. was/were convinced that + ...: 某人确信...
It is disturbing to think that + ...: 想到...令人很不安
--------------------
at large: 在逃
be found in: 产于
take sth. seriously: 严肃对待某事
sth. proved adj.: 某事证明怎么样
sb. confirmed that + ...: 某人确定
claim to have done sth.: 声称做过某事
find sb. doing sth.: 发现某人在做某事
go on: continue

spotted: seen
accumulate: pile up
obliged to: bound to
claimed: stated
extraordinarily similar: surprisingly alike
immediately: at once
convinced: sure

** L02 Thirteen equals one
[[./NCE3/L02 Thirteen equals one.html]]
equal: [ˈikwəl] v. equally adv.等于
vicar: [ˈvɪkər] n.牧师
raise: [reɪz] v.募集,筹(款) + money
torchlight: [ˈtɔrtʃˌlaɪt] n.电筒灯光 torch n.
cause: [kɔz] n.原因,理由 v.导致,引起
wake up with a start: 一激灵醒来
bell: [bel] n. ring v.响铃
catch sight of a figure: 看到人影
recognize: [ˈrekəɡˌnaɪz] v.辨认
local grocer: [ˈɡroʊsər] n.当地杂货店老板

A be equal to B: A等于B
for one cause or another: for one reason or another因为这个那个理由
wake up with a start: 惊醒
catch sight of sb./sth.看见某人某物
--------------------
1. be always doing sth.: 频率过高令人生厌(非绝对,用于肯定句)
2. whatever:
	 - emphasize the speaker's surprise/astonishment/anger/irritation/dismay
	 - on earth/ in the world/ fucking
3. do/does/did: 强调v.
4. was/were doing 表礼貌
	 - I was hoping to do sth.
	 - I was just wondering + ...
	 - I was thinking + ...
--------------------
for one cause or another: for one reason or another因为这个那个理由
get enough money to do sth.: 有足够钱去做某事
sb. be armed with sth.: 装备
what's going on: 发生了什么
recognize A as B: 把A辨识为B
give sb. a surprise: 给某人一个惊喜
I'm glad that + ...: 我很高兴+...
get used to sth.: 习惯于

** L03 An unknown goddess
[[./NCE3/L03 An unknown goddess.html]]
goddess: [ˈɡɑdəs] n.女神 god
archaeologist: [ˌɑrkiˈɑlədʒɪst] n. archaeology n.考古学家
Aegean: [i:'dʒi:ən] adj.爱琴海的
explore: [ɪkˈsplɔr] v.考察,勘探 explorer n. exploration n.
promontory: [ˈprɑmənˌtɔri] n.海角
prosperous: [ˈprɑsp(ə)rəs] adj.(经济上)繁荣的,昌盛的
civilization: [ˌsɪvɪlɪˈzeɪʃ(ə)n] n.文明
storey: [ˈstɔri] n. story 楼层
drainage: [ˈdreɪnɪdʒ] n.排水
worship: [ˈwɜrˌʃɪp] n.v.崇拜(神)
sacred: [ˈseɪkrəd] adj.宗教的,神圣的
fragment: [ˈfræɡmənt] n.碎片
remains: [rɪˈmeɪnz] n.遗物,遗迹,废墟
classical: [ˈklæsɪk(ə)l] adj.(希腊和罗马)古文化的
reconstruct: [ˌrikənˈstrʌkt] v. re... 修复
rest: [rest] n.v. hip n.放置
full-length: adj.拖地长的
graceful: [ˈɡreɪsfʊl] adj.优雅的
identity: [aɪˈdentəti] n.身份

A is/was used as a place of worship: A被用于崇拜的地方
on a/the promontory: 在海角
drainage system: 下水道
sacred room/template/place: 神圣的房间
have a rest: 休息一下
identity card: 身份证
--------------------
sb. make a (adj.) discovery of sth.: 某人发现了某物
a. be equipped with b.: 配置
equip sb. with sth.: 给某人装备某物
be used as: 被用作
date from ... date back to ...:追溯
happen to do sth.: you do it by chance碰巧做某事
be amazed to find that + ...: 惊讶地发现
turn out to be sth.: 原来是某物
despite + doing sth./despite the fact that ...: 尽管

** L04 The double life of Alfred Bloggs
[[./NCE3/L04 The double life of Alfred Bloggs.html]]
manual: [ˈmænjuəl] adj. n.体力的
collar: [ˈkɑlər] n.衣领
sacrifice: [ˈsækrɪˌfaɪs] v. n.牺牲,献出
privilege: [ˈprɪvəlɪdʒ] n.好处
dustman: [ˈdʌstmən] n.清洁工
corporation: [ˌkɔrpəˈreɪʃ(ə)n] n.公司
overalls: [ˈoʊvərˌɔl] n.工作服
shower: [ˈʃaʊər] n.淋浴
secret: [ˈsikrət] n.秘密
status: [ˈstætəs] n.地位

do manual work: 做体力工作 
white-collar/blue-collar workers: 白领/蓝领工人
make a sacrifice: to surrender or give up, or permit injury or disadvantage to, for the sake of something else做出牺牲
sacrifice a. for b.:为B牺牲A
have the privilege of doing sth.: an opportunity to do something special or enjoyable有荣幸做某事
take a shower: 洗淋浴
keep a secret: 保密
the secret of success: 成功的秘诀
It's between you and me: 这是你我之间
social status: 社会地位
status quo: 保持原样
keep the status quo: 保持原样
--------------------
These days ...: 现在
Far more adj./n.: 非常...
A be referred to as ... B: regrad A as B 把A称作为B
refer to A as B: regrad A as B=speak of A as B 把A称作为B
for the simple reason that + ...: 仅仅因为 + ...
Such is human nature, that + ...: 这是人类的本性, ...
be willing to do sth.: 愿意做某事
give rise to: lead to; cause导致
too embarrassed to do sth.: 不好意思做某事
be dressed in: wear穿着
change into + [clothes]: 换上(衣服)
half as much as ...:是..的一般(充当adj.)
from now on: 从现在起
call me/him/her A: 称...作为A

** L05 The facts
[[./NCE3/L05 The facts.html]]
editor: [ˈedɪtər] n. edit v.编辑
extreme: [ɪkˈstrim] n.极端
statistics: [stə'tɪstɪks] n. statistic 统计数字
journalist: [ˈdʒɜrn(ə)lɪst] n.新闻记者
president: [ˈprezɪdənt] n.总统
palace: [ˈpæləs] n.王宫;宏伟的住宅
publish: [ˈpʌblɪʃ] v.出版
fax: [fæks] n.v.传真
impatient: [ɪmˈpeɪʃ(ə)nt] adj.不耐烦的
fire: [faɪr] v.解雇
originally: [əˈrɪdʒən(ə)li] adv.起初,原先,从前

go to extreme(s) to do sth.: 极端地做某事
publish + a book/an article/report: 出版一本书/一篇文章/报告
send sb. a fax: 给某人发传真
get impatient: 变得不耐烦
get/be fired: 被炒鱿鱼

--------------------
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until

--------------------
provide sb. with sth.: 为某人提供某物
sb. be instructed to do sth.: 某人被指示去做某事
instruct sb. to do sth.: 指示某人去做某事
write an article on/about sth.: 写一篇关于某事的文章
find out sth.: to discover, learn, or verify something发现,查明某事
sb. take a long time to do sth.: 某人花了很长时间去做某事
go to press: 送印
inform sb. that + ...: 通知某人+...

** L06 Smash-and-grab
[[./NCE3/L06 Smash-and-grab.html]]
smash-and-grab: n.砸橱窗抢劫
arcade: [ɑrˈkeɪd] n.有拱廊的街道(两旁常设商店)
jewellery: [ˈdʒuːəlri] n. jewelry 珠宝(总称)
necklace: [ˈnekləs] n. a string of jewels, beads etc or a thin gold or silver chain to wear around the neck项链
ring: [rɪŋ] n.戒指
background: [ˈbækˌɡraʊnd] n.背景
velvet: [ˈvelvət] n.天鹅绒
headlight: [ˈhedˌlaɪt] n.车头灯
blare: [bler] v.to make a very loud unpleasant noise发出嘟嘟声,吼叫
staff: [stæf] n.全体工作人员
raid: [reɪd] n.v. a short attack on a place by soldiers, planes, or ships, intended to cause damage but not take control偷袭
scramble: [ˈskræmb(ə)l] v. to climb up, down, or over something quickly and with difficulty, especially using your hands to help you爬行
fantastic: [fænˈtæstɪk] adj.非常大的
ashtray: [ˈæʃtreɪ] n. a small dish where you put used cigarettes烟灰缸

smash sth. to pieces: 撕某物成碎片
grab a beer/coffee: 喝杯啤酒/咖啡
go to the arcade: 去拱廊
background music: 背景音乐
scrambled eggs: 炒鸡蛋
at a fantastic speed: at a good speed以极快的速度
That's fantastic: 很棒
--------------------
独立主格
--------------------
only just: Just a moment earlier刚才
come to a stop: 停下来
be too busy doing sth. to do sth.: 忙于做某事而不能做某事
[money] + worth of + n.: eg. thousands of pounds worth of diamonds多少价值的某物
help oneself to sth.:
	1. to serve or provide oneself with (food, etc.)自己拿
	2. to take without asking or being given; steal.偷窃

** L07 Mutilated ladies
[[./NCE3/L07 Mutilated ladies.html]]
mutilate: [ˈmjut(ə)lˌeɪt] v. damage someone’s body, especially by cutting or removing part of it使残缺不全
chew: [tʃu] v. chew up  chewing gum咀嚼
fiance: [ˌfiən'seɪ] n.未婚夫
microwave: [ˈmaɪkrəˌweɪv] n.微波,微波炉
oven: [ˈʌv(ə)n] n.炉灶
safekeeping: [seɪfˈkipɪŋ] n.妥善保管
Newcastle: [ˈnjuːkɑːsl] n.
identify: [aɪˈdentɪˌfaɪ] v.鉴定,识别
spokeswoman: [ˈspoʊksˌwʊmən] n.女发言人

chewing gum: 口香糖
for safekeeping: 为了妥善保管
--------------------
deal with: 处理
go doing sth.: 去做某事
Imagine sb's dismay when + ...: 想象某人的沮丧当...
so long as + ..., sb. will do sth.: 只要...,某人就会做某事

** L08 A famous monastery
[[./NCE3/L08 A famous monastery.html]]
monastery: [ˈmɑnəˌsteri] n. St. Bernard寺院,修道院
pass: [pæs] n. a high road or path that goes between mountains to the other side关隘
watchdog: [ˈwɑtʃˌdɔɡ] n.看门狗
rashly: adv.莽撞地,冒失地
enclosure: [ɪnˈkloʊʒər] n. an area surrounded by a wall or fence, and used for a particular purpose
monk: [mʌŋk] n. a member of an all-male religious group that lives apart from other people in a monastery围地,圈地
privacy: [ˈpraɪvəsi] n.  the state of being free from public attention隐私
skier: [ˈskiər] n.滑雪者
Easter: [ˈiːstə(r)] n.复活节

Can I get some privacy?: 我能有点隐私吗?
--------------------
connect a. to b. = a. be connected to b.: 连接A到B
for hundreds of years: 数百年来
Now that + ...(原因状从): 现在因为...
be in difficulty: run into serious trouble陷入困境
attempt to do sth.: try to do sth.尝试做某事
receive a warm/cold welcome: 受到热烈/冷淡的欢迎

** L09 Flying cats
[[./NCE3/L09 Flying cats.html]]
fascinate: [ˈfæsɪˌneɪt] v. you are attracted to them and think they are extremely interesting迷住,吸引住
affectionate: [əˈfekʃənət] adj. showing in a gentle way that you love someone and care about them充满深情的,柔情的
mysterious: [mɪˈstɪriəs] adj.神秘的,难以理解的
submissive: [səbˈmɪsɪv] adj. always willing to obey someone and never disagreeing with them, even if they are unkind to you服从的,顺从的
feline: [ˈfiˌlaɪn] adj.  relating to cats or other members of the cat family, such as lions猫的
independence: [ˌɪndɪˈpendəns] n.独立,独立性
high-rise: adj. tall 高层的
windowsill: [ˈwɪndoʊˌsɪl] n. a shelf fixed along the bottom of a window窗槛
paratrooper: [ˈperəˌtrupər] n. a soldier who is trained to jump out of a plane using a parachute伞兵
squirrel: [ˈskwɪrəl] n.松鼠
air-resistance: [rɪˈzɪstəns] n.空气阻力
impact: [ɪmˈpækt] n.冲击力

gain its independence: it has its own government and is not ruled by any other country获得独立
have/make an impact on: 对...有影响
--------------------
the 比较级(eg. more) ..., the 比较级(eg.more) ...: 比较级在句子中做比较成分
yet...: conj.; 表惊讶的转折
--------------------
lead a adj. life: live a adj. life过一种怎样的生活
learn to do sth.: 学会做某事
a good deal of/a great deal of un.: VS a lot of; VS a great number of 大量+(un.)
be based on: to use information to support or prove an opinion or belief基于
make a study of sth: research研究某事物
a period of + st.: eg. a period of five months一段时间
have sth. in common: eg. have one experience in common有共同之处
died from(事故) / died of(病): 死于
there is no shortage of sth.: 不缺某物
It seems that + ...: 看来好像+...
be likely to do sth.: they will very probably do it可能做某事

** L10 The loss of the Titanic
[[./NCE3/L10 The loss of the Titanic.html]]
Southampton: [saʊθ'hæmptənˌ saʊ'θæmp-]
colossal: [kəˈlɑs(ə)l] adj.庞大的
watertight: [ˈwɔtərˌtaɪt] adj.不漏水的
compartment: [kəmˈpɑrtmənt] n.(轮船的)密封舱
flood: [flʌd] v.充满水
float: [floʊt] v.漂浮,漂浮
tragic: [ˈtrædʒɪk] adj.悲惨的
liner: [ˈlaɪnər] n. a large ship for passengers班船
voyage: [ˈvɔɪɪdʒ] n.航行
iceberg: [ˈaɪsˌbɜrɡ] n.冰山
lookout: [ˈlʊkˌaʊt] n. someone whose duty is to watch carefully for something, especially for danger瞭望员
collision: [kəˈlɪʒ(ə)n] n.碰撞
narrowly: [ˈneroʊli] adv.刚刚,勉强地
miss: [mɪs] v.避开
slight: [slaɪt] adj.轻微的
tremble: [ˈtremb(ə)l] v.  to shake slightly in a way that you cannot control, especially because you are upset or frightened震颤
faint: [feɪnt] adj.微弱的
horror: [ˈhɔrər] n.  to sb's horror  horror movie恐惧
abandon: [əˈbændən] v.抛弃
plunge: [plʌndʒ] v.投入, 跳入
lifeboat: [ˈlaɪfˌboʊt] n.救生船
--------------------
a crew of: eg. ~ workers; ~ painter; ~ waiters一群...
be regarded as + adj./n.: 被认为是
give an alarm: give a warn of danger发出警报
in time: not late; punctual.及时
realized to his horror that: 惊恐的意识到...
give an order: 下命令

** L11 Not guilty
[[./NCE3/L11 Not guilty.html]]
guilty: [ˈɡɪlti] adj.犯罪的,违法的
tolerant: [ˈtɑlərənt] adj.宽容的
declare: [dɪˈkler] v.申报
hardened: [ˈhɑː(r)d(ə)nd] adj. a criminal, police officer etc who has had a lot of experience of things that are shocking and is therefore less affected by them有经验的
professional: [prəˈfeʃ(ə)nəl] adj. n.职业的,专业的
smuggler: [ˈsmʌɡ(ə)lər] n.走私者
officious: [əˈfɪʃəs] adj.爱管闲事的
confidently: ['kɒnfədəntlɪ] adv.自信地
dreadful: [ˈdredfəl] adj. extremely unpleasant可怕的,一团糟的
pounce: [paʊns] v.to suddenly move forward and attack someone or something, after waiting to attack them猛抓,扑住
perfume: [ˈpɜː(r)fjuːm] n.香水
sarcastically: adv.讽刺地
exempt: [ɪɡˈzempt] adj.被免除的
import: [ɪmˈpɔrt] duty n.进口税
gel: [dʒel] n.胶
mixture: [ˈmɪkstʃər] n.混合物
unscrew: [ʌnˈskru] v.拧开
nostril: [ˈnɑstrəl] n.鼻孔
chalk: [tʃɔk] n.small sticks of a white or coloured substance like soft rock, used for writing or drawing粉笔
baggage: [ˈbæɡɪdʒ] n.行李

feel guilty: 感到内疚
be tolerant of: willing对...容忍
be exempted from: they do not have to follow it or do it免于...
mixture of A and B: A和B的混合物
--------------------
be made to do sth.: to be forced to do something被迫做某事
on the other hand/on the one hand: 一方面/另一方面
light up:  suddenly become animated with liveliness or joy照亮（脸上）
be greeted by sth.: to welcome someone with particular words or a particular action被某物问候

** L12 Life on a desert island
[[./NCE3/L12 Life on a desert island.html]]
desert: [ˈdezərt] island 荒岛
unrealistic: [ˌʌnriəˈlɪstɪk] adj.不真实的
paradise: [ˈperəˌdaɪs] n.天堂,乐土
wretched: [ˈretʃəd] adj. someone who is wretched is very unhappy or ill, and you feel sorry for them可怜的,艰苦的
starve: [stɑrv] v.挨饿
element: [ˈelɪmənt] n.成分
opportunity: [ˌɑpərˈtunəti] n.机会
coral: [ˈkɔrəl] n.珊瑚
Virgin: [ˈvɜrdʒɪn] Islands
Miami: [maɪ'æmi] n.
dinghy: [ˈdɪŋi] n.皮艇
Caribbean: [ˌkerɪˈbiən] n.加勒比海
spear: [spɪr] gun: 鱼叉枪
lobster: [ˈlɑbstər] n.龙虾
tanker: [ˈtæŋkər] n.油轮
genuinely: [ˈdʒenjuɪnli] adv.由衷地

have an opportunity to do sth.: have the privilege of doing sth.有机会做某事
an element of truth/danger: 有点..
starve to death: 饿死
sb. be genuinely sorry that + ...某人真的很抱歉+...

--------------------
wish that sb. did: 现在虚拟
wish that sb. had done: 过去虚拟

--------------------
formed an unrealistic picture of sth.:对某事有不切实际的想象
imagine sth./sb. to be n./adj.: 把某事想象成
a sort of: 某种程度上/一种
wish that + ...: 希望+...
load a. with b.: 用B装载A
As sb. put it: 如某人所说

** L13 It's only me
[[./NCE3/L13 It's only me.html]]
costume: [ˈkɑstum] n.化装服
consist: [kənˈsɪst] v.由...组成
sheet: [ʃit] n.a large piece of thin cloth that you put on a bed to lie on or lie under被单
effective: [ɪˈfektɪv] adj.有明显效果的,有作用的
comfortable: [ˈkʌmfərtəb(ə)l] adj.舒适的
storeroom: [ˈstɔrˌrum] n.储藏室
electricity: [ˌilekˈtrɪsəti] n. meter=metre n. 电表
pace: [peɪs] n.一步
flee: [fli] fled v. to leave somewhere very quickly, in order to escape from danger逃走
slam: [slæm] v. close砰地关上

consist of ...: to be formed or made up of 
make yourself comfortable: to sit, lie, move, or behave in a such a way that you are relaxed and free from pain
at your own pace: you do it at a speed that is comfortable for yo
The pace of life:
--------------------
fancy dress party: 化妆舞会
be impatient to do sth.: 急于做某事
let out a cry: 大叫一声

** L14 A noble gangster
[[./NCE3/L14 A noble gangster.html]]
gangster: [ˈɡæŋstər] n.歹徒,强盗
Chicago: [ʃɪ'kɑ n.
protection: [prəˈtekʃən] n.保护
promptly: [ˈprɑmptli] adv. immediately/on time准时地
destroy: [dɪˈstrɔɪ] v.毁掉;消灭
remarkable: [rɪˈmɑrkəb(ə)l] adj.unusual or surprising and therefore deserving attention or praise不寻常的
band: [bænd] n. a group of musicians, especially a group that plays popular music帮,团伙
Florence: ['flɔrəns] n. Florentine n.
city-state: n.城邦
hire: [ˈhaɪr] v. rent租出,雇给
prince: [prɪns] n. the son of a king, queen, or prince君王,诸侯
funeral: [ˈfjun(ə)rəl] n.葬礼
dedicate: [ˈdedɪˌkeɪt] v.献身于
memory: [ˈmem(ə)ri] n.纪念
valiant: [ˈvæliənt] adj.very brave, especially in a difficult situation英勇的

need protection: 需要保护
provide protection: 提供保护
for your own protection: keeping yourself safe from injury or damage为了你自己的安全
a band of: a group of一群,一伙
give him a state funeral: 给他一个国葬
dedicate yourself/your life to sth.: sacrifice a. for b.; devote oneself to sth./doing sth.投身/献身于某事/做某事
dedicate sth. to sb.: 献给某人某物
devote oneself to sth./doing sth.: 投身/献身于某事/做某事
in memory of sb. / to the memory of sb.: in sb's honor为了纪念某人
--------------------
when引导的定语从句
	1. 先行词必须为时间(time, day, year...)
	2. when必须在从句中充当[6]的成分.如果从句是[1][3],那么是which引导定语从句,而不是when
	3. 在非书面语中,用that或者直接去掉
	4. 注意区分when时间状语 VS when定语从句
	5. prep.+which=when, 类似的还有方式状语
whenever:
	1. when的强调
	2. every time or any time
if真实条件句和虚拟语气: 过去真实条件句和现在虚拟格式一致,只能结合上下文看.
	If did... , would do...
--------------------
There was a time when + ...: 曾经有一段时间……
pay money to sb.: 付钱给某人
large sums of money: 大笔大笔的钱
put sb. out of business: make (someone) go bankrupt, lose their shop or company使某人破产
as long ago as: in the distant past早在...就
make the remarkable discovery that + ...: 有显著的发现+...
would rather do A than do B: 更愿意做A而不是B
make a name for himself: to become well-known or famous; rise to fame成名
come to do sth.: they do it at the end of a long process or period of time最终来做某事
A be known to B as C: B calls A as C A被B称为C
A be known as B: A被称为B
be at war with ...: eg. China is at war with America.与...交战
in times of peace: 在和平时期
offer to do sth.: 主动提出做某事
make money: 赚钱
regard A as B: refer to A as B 把A看作B

** L15 Fifty pence worth of trouble
[[./NCE3/L15 Fifty pence worth of trouble.html]]
appreciate: [əˈpriʃiˌeɪt] v.欣赏,感激
pocket [ˈpɑkɪt] money: 零花钱
rattle: [ˈræt(ə)l] v. if you rattle something, or if it rattles, it shakes and makes a quick series of short sounds格格作响
thrifty: [ˈθrɪfti] adj. using money carefully and wisely节俭的
nephew: [ˈnefju] n.侄子,外甥
bounce: [baʊns] v. it immediately moves up or away from a surface after hitting it弹起,跳起
pavement: [ˈpeɪvmənt] n. sidewalk人行道
stick [stɪk]-stuck-stuck: v.卡住
fire brigade: n. 消防队
grease: [ɡris] n. a thick oily substance that is put on the moving parts of a car, machine etc to make it run or move smoothly润滑油

I appreciate your honesty.: 我感谢你的诚实
	understanding/interesting/concern/support/patience/trust/time/help/it/that ...
--------------------
supply of sth.: 某物的供给
go a long way: 维持很长时间
be exchanged for sth.  exchange a. for b.: 被交换成某物
fill up a. with b. 用B充满A
find one's way: reach a destination, especially with some difficulty or not as a matter of course到达
advise sb. to do sth.: 建议某人做某事
On one's way to sp.: 在去某地的路上
roll up one's sleeves: 卷起某人的袖子
What is more=what's more: 而且
rub a. with b.: 用B擦A
a special type of sth.: 一种特殊类型的某物
hear about sth.: 听说某事物
reward sb. with sth.: 用某物奖励某人

** L16 Mary had a little lamb
[[./NCE3/L16 Mary had a little lamb.html]]
prize: [praɪz] adj. very good or important珍贵的,宝贵的
tie: [taɪ] v.拴,系
accuse: [əˈkjuz] v.指控
theft: [θeft] n. an act of stealing something偷盗行为,偷盗案
deny: [dɪˈnaɪ] v. SAY STH IS NOT TRUE否认
ashamed: [əˈʃeɪmd] adj. feeling very sorry and embarrassed because of something you have done感到羞耻,忏愧
apologize: [əˈpɒləˌdʒaɪz] v.道歉
dye: [daɪ] v. to give something a different colour using a dye染

prize money: 奖金
tie sb. to sth. = sb. be tied to sth.: 把某人绑某物上
accuse sb. of doing sth.: 指控某人做了某事
deny doing.../sb. deny that + ...: 某人做某事/某人否认+...
be ashamed of sth./doing sth./having done sth.: 羞于某事/做某事/做过某事
apologize to sb. (for doing sth.): 对某人道歉
dye something + some-color.: eg. dye his hair red把某物染色
--------------------
tell sb. about sth.: 告诉某人关于某事
It's ture that + ..., but + ...: 虽然...,但是...
sb. be astonished to find (that) + ...: 某人很惊讶地发现+...

** L17 The longest suspension bridge in the world
[[./NCE3/L17 The longest suspension bridge in the world.html]]
suspension: [səˈspenʃ(ə)n] n. suspend v.悬挂,悬职
agreeable: [əˈɡriəb(ə)l] adj. situation n.宜人的风景
locate: [ˈloʊˌkeɪt] v. location n.坐落
immortal: [ɪˈmɔrt(ə)l] adj. so famous that it will never be forgotten永生的,流芳百世的
span: [spæn] n.  a period of time between two dates or events跨度
cable: [ˈkeɪb(ə)l] n. a plastic or rubber tube containing wires that carry telephone messages, electronic signals, television pictures etc缆索
concrete: [ˈkɑŋˌkrit] n.混凝土
length: [leŋθ] n.长
estimate: [ˈestɪmət] v.估计
capacity: [kəˈpæsəti] n.承受量
immensity: [ɪˈmensəti] n.巨大
elegant: [ˈelɪɡənt] adj.优美别致的
faintly: [ˈfeɪntli] adv.轻微地

agreeable/pleasant + situation/man/day: 宜人的环境
be located in/near: 坐落于/靠近...
a span of ...: ...的跨度
life span: 寿命
a length of/lengths of + rope/pipe/wire: 一段绳/管/线
It is estimated that + ...: 据估计+...
sb. estimates that + ...: 某人估计+...
--------------------
little/not much/not everything is known about a.: 对A知之甚少
describe A as B: 把A描述成B
in the midst of ...:在...的中间
by no means: not possible绝无可能
be considered to be adj./n.: 被认为是...
sth. be named after sb.: 某物以某人命名
join a. to b. = connect a. to b.: 连接A和B
be taken into account = take sth. into account 考虑某事
a height of ...: ...的高度
A be suspended from B: A悬挂于B
be packed with ...: to fill something with things or people of a particular type挤满,塞满
a third of sth: 某物的1/3
fulfill sb's dream: something or someone made your dream come true实现某人的梦想

** L18 Electric currents in modern art
[[./NCE3/L18 Electric currents in modern art.html]]
current: [ˈkʌrənt] n.  electric current 电流
sculpture: [ˈskʌlptʃə] n. an object made out of stone, wood, clay etc by an artist雕塑
mistaken: [miˈsteɪk] adj.错误的
gallery: [ˈɡæləri] n. a large building where people can see famous pieces of art美术馆
exhibit: [ɪɡˈzɪbɪt] n.v. exhibition n. to show something in a public place so that people can go to see it展品,陈列品
oddly: [ˈɑdli] adv. in a strange or unusual way古怪的
attach: [əˈtætʃ] v. to fasten or connect one object to another连,系
sphere: [sfɪr] n. a ball shape球体hemisphere
magnetize: [ˈmæɡnəˌtaɪz] v.使磁化
repel: [rɪˈpel] v.排斥
flicker: [ˈflɪkər] v. to burn or shine with an unsteady light that goes on and off quickly闪烁
emit: [ɪˈmɪt] v. to send out gas, heat, light, sound etc放射
flash: [flæʃ] v.闪光
prehistoric: [ˌpriˈhɪstɔrɪk] adj.史前的,老掉牙的
electronic: [ˌilekˈtrɑnɪk] adj.电子的
peculiar: [pɪˈkjuljər] adj. strange, unfamiliar, or a little surprising奇异的
shock: [ʃɑk] v.n.震惊
emotionally: [ɪˈmoʃənlɪ] adv. relating to your feelings or how you control them感情上

make a sculpture / create a sculpture: 制作雕塑
be mistaken about sth./sb.: confused or wrong about对某人/事物有误解
Oddly enough, + ...: Strangely, unexpectedly奇怪地, ...
be attached to sb./sth. = attach a. to b.: 把A绑到B上
get an electric shock: 被电击
receive an electric shock: 被电击
give you electric shocks: 给你电击
--------------------
not any more = not any longer = no longer: 不再
The idea that + ... is mistaken: 想法xx是错的
take no/ a great/an interest in: 对...不感兴趣
in response to sth.: 回应某事
be/sound/look/seem familiar to sb.: 对某人看起来很熟悉
go mad: 发疯
on and off: 断断续续
It was rather like ...: 这很像...
seem adj.(designed) to do sth.: be designed to do sth.似乎被设计去做某事
be designed to do sth.: seem designed to do sth.被设计成做某事

** L19 A very dear cat
[[./NCE3/L19 A very dear cat.html]]
dear: [dɪr] adj.亲爱的;珍贵的;昂贵的
kidnapper: ['kɪdnæpə(r)] n.绑架者,拐骗者
considerable: [kənˈsɪd(ə)rəb(ə)l] adj.相当大的
wealthy: [ˈwelθi] adj. having a lot of money, possessions etc富的,有钱的
orderly: [ˈɔrdərli] adj. arranged or organized in a sensible or neat way有规律的
disappearance: [ˌdɪsəˈpɪrəns] n. disappear v.出现
anonymous: [əˈnɑnɪməs] adj. unknown by name匿名的
ransom: [ˈrænsəm] n.赎金
cardboard: [ˈkɑrdˌbɔrd] n. stiff thick brown paper, used especially for making boxes硬纸板
withdraw: [wɪðˈdrɔ] withdrew withdrawn(从银行)取钱
punctually: adv. on time准时地
astound: [əˈstaʊnd] v. astounded adj.使吃惊

be dear to somebody: 对某人很宝贵
a considerable amount/number of sth.: a lot of很多
in an orderly fashion/manner: in a well-organized and controlled way以有序的方式
anonymous letter/(phone) call: 匿名信/电话
remain anonymous: 匿名
a ransom of + (money): eg. a ransom of $100 ...的赎金
It astounded sb. that + ...: 使某人吃惊的是+...
--------------------
share sth. with sb.: 与某人分享某物
take a short/long walk: 走一小段路
get worried: 变得担心
in safe hands: they are being looked after by a reliable person and will not be harmed得到很好的照顾
at first: 一开始
go to the police: 报警
make sth. clear: 把某事搞的很清楚
change sb's mind: 改变主意
follow sb's instructions: 遵从某人的指示
keep sb's word: 说话算数
sure enough: 当然了
sb. explained that + ...: 某人解释到+...
Considering + n., + ...: 考虑到
in more ways than one: to have more than one meaning不止一种意义

** L20 Pioneer pilots
[[./NCE3/L20 Pioneer pilots.html]]
pioneer: [ˌpaɪəˈnɪr] n. someone who is important in the early development of something, and whose work or ideas are later developed by other people先驱
lord: [lɒrd] n. a man who has a rank in the aristocracy勋爵
Calais: [kæ'leɪˌ 'kæleɪ] n.(法国港市)
overland: [ˈoʊvərˌlænd] adj. adv.across land, not by sea or air陆上的
--------------------
as if/though: 虚拟语气

--------------------
offer sth. to sb. = offer sb. sth.: provide sth. for sb.; provide sb. with sth.提供某物给某人
a prize of + (money): eg. a prize of $1,000多少的奖金
make an attempt to do sth.: attempt to do sth; try to do sth.尝试做某事
attempt to do sth.: 尝试做某事
be forced to do sth.: be made to do sth.被迫做某事
be picked up by ...: be rescued by被...营救
on the same day: 在同一天
It looked as if/though + 虚拟句:
	eg.	It looked as if there would be an exciting race across the Channel.
	eg.	It looked as though there would be an exciting race across the Channel.

** L21 Daniel Mendoza
[[./NCE3/L21 Daniel Mendoza.html]]
boxing: [ˈbɑksɪŋ] n.拳击
boxer: [ˈbɑksər] n.拳击手
bare: [ber] adj. not covered with clothes赤裸的
prizefighter: [ˈpraɪzˌfaɪtər] n.古拳手
crude: [krud] adj. rude and offensive粗野的
marquis: [mɑrˈki] n. has a rank between duke and earl侯爵
technically: [ˈteknɪkli] adv.严格根据法律意义地
science: [ˈsaɪəns] n.科学
popularity: [ˌpɑpjəˈlerəti] n.名望
adore: [əˈdɔr] v. to love someone very much and feel very proud of them崇拜,爱戴
alike: [əˈlaɪk] adv. in a similar way  adj. very similar not before noun一样地
fame: [feɪm] n.名声
eminent: [ˈemɪnənt] adj. an eminent person is famous, important, and respected著名的,杰出的
bitterly: [ˈbɪtərli] adv. very厉害地
bet: [bet] bet betted v. to risk money on the result of a race, game, competition, or other future event打赌
academy: [əˈkædəmi] n.专业学校
extravagant: adj. spending or costing a lot of money, especially more than is necessary or more than you can afford浪费的,奢侈的
poverty: [ˈpɑvərti] n.贫困

with sb's bare hands: using only one's hands and no tools or weapons赤手空拳地
Technically speaking, + ...: According to the rules严格意义上说
gain/grow/increase in popularity:  something or someone is liked, enjoyed, or supported获得欢迎
great minds think alike: 英雄所见略同
rise to fame: make a name for oneself变得出名
quarrel/complain/be disappointed ... + bitterly: 吵架剧烈
bet ($) on sth.: 在某事打赌多少钱
I bet + ...: 我赌 + ...
live in poverty: 生活贫困
--------------------
Because of + n.: 因为某物
be born in + (year): 出生于
draw up: 起草
a set of sth.: a series of; a trail of一系列某物
change a. into b.: 把A变成B,而 exchange A for B是交换
bring a. to b.: eg. brought science to the game把A带给B
in sb's day: 在他的时代
be quick to do sth.: 很快做某事
in fact: 实际上
turn against sb.: 与某人反目
It is clear that + ...: 很明显
settle the argument: 解决争端
It was not until [stp.] that + ...: 直到某事+...
	stp. can not only be 'in 1790' but also 'third match' as well
as much as ...   half as much as: 一样多,一半多
be in debt: owe money在欠债

** L22 By heart
[[./NCE3/L22 By heart.html]]
run: [rʌn] ran run v.(戏剧,电影等)连演,连映
lines:  [laɪn] n.台词
part: [pɑrt] n. role n.角色
falter: [ˈfɔltər] v.支吾,结巴说
cast: [kæst] cast cast v. to choose which people will act particular parts in a play, film etc选派...扮演角色
aristocrat: [əˈrɪstəˌkræt] n.someone who belongs to the highest social class贵族
imprison: [ɪmˈprɪz(ə)n] v. to put someone in prison or to keep them somewhere and prevent them from leaving关押
Bastille: [bæ'stiːl] n.
jailer: [ˈdʒeɪlər] n.监狱长,看守
colleague: [ˈkɒˌliːɡ] n.someone you work with – used especially by professional people同事
curtain: [ˈkɜrt(ə)n] n. a piece of hanging cloth that can be pulled across to cover a window, divide a room etc窗帘
reveal: [rɪˈvil] v.使显露
cell: [sel] n. a small room in a prison or police station where prisoners are kept单人监号
blank: [blæŋk] adj.空白的
squint: [skwɪnt] v. to look at something with your eyes partly closed in order to see better眯着(眼)看
dim: [dɪm] adj.昏暗
sire: [saɪr] n.陛下
proceed: [prəˈsid] v.继续进行

play the role of: 扮演...的角色
sb. be cast in the role of = cast sb. in the role of: 委派某人演...角色
the curtain goes up/rises/comes down/falls: 窗帘上/下
a blank sheet of paper: 一张白纸
squinte at sb./sth.: 眯眼看某人/某物
in the dim light: 在昏暗的光线下
proceed to do sth.: 继续做某事
--------------------
insist/suggest that + ... (should) do (虚拟语气)

--------------------
for days/hours/years on end: 一连好几天/小时/年
in many ways: to a great degree在许多方面
be required to do sth.: be ordered to do sth.被要求做某事
expect sb. to do sth./ sb. be expected to do sth.: want sb. to do sth.期望某人做某事
learn/know sth. by heart: to have learned or memorized something completely and perfectly熟记于心
have cause to do sth.: have a reason to do sth.有理由做某事
sb. insisted that + ...(should) do (虚拟语气) 要求
sb. insisted that + ...(非虚拟) 认为
be written out in full: 被写的满满当当
play a joke on sb.: to confuse someone or cause problem for them对某人开玩笑
present sth. to sb.: provide sth. for sb.把某物送给某人
look on: 旁观(看热闹)
at last: 终于
be anxious to do sth. = be eager to do sth. = can't help doing sth.急于做某事
stare at: 盯着
read sth. to sb.: 给某人读某事
much to sb's sth.[surprise/amusement/dismay/disappoint]: 使某人...

** L23 One man's meat is another man's poison
[[./NCE3/L23 One man's meat is another man's poison.html]]
poison: n.毒药
illogical: [ɪˈlɑdʒɪk(ə)l] adj.不合逻辑的,无章法的
octopus: [ˈɑktəpəs] n. a sea creature with eight tentacles (=arms)章鱼
delicacy: [ˈdelɪkəsi] n. something good to eat that is expensive or rare美味,佳肴
repulsive: [riˈpʌlsiv] adj. extremely unpleasant, in a way that almost makes you feel sick 令人反感的,令人生厌的
stomach: [ˈstʌmək] n.胃 turn v.感到恶心
fry: [fraɪ] v. to cook something in hot fat or oil, or to be cooked in hot fat or oil油炸
fat: [fæt] n.(动物,植物)油
abuse: [əˈbjus] n.辱骂,责骂
snail: [sneɪl] n.蜗牛
luxury: [ˈlʌkʃ(ə)ri] n.奢侈品,珍品
associate: [əˈsoʊʃiət] v.联想到
despise: [dɪˈspaɪz] v. to dislike and have a low opinion of someone or something鄙视
appeal: [əˈpil] v.引起兴致
shower: [ˈʃaʊər] n.阵雨
stroll: [stroʊl] n.溜达,散步
impulse: [ˈɪmˌpʌls] n. a sudden strong desire to do something without thinking about whether it is a sensible thing to do冲动
dozen: [ˈdʌz(ə)n] n. twelve,12个
fancy: [ˈfænsi] v. to like or want something, or want to do something喜爱,喜欢

One man's meat is another man's poison: 萝卜青菜,各有所爱
it is illogical to do sth.: 做某事不和逻辑
turn sb's stomach: 真的反胃
sick to my stomach: feeling very disgusted or angry.恶心到我
animal fat: 动物油
a. received more abuse than b.: a比b受到更多争议
associate a. with b.: connect a. to b.把A和B联系起来
appeal to sb.:  to attract, please, or interest吸引某人
After a heavy shower ...: 下大雨后
be in the shower: 淋雨
take a shower: to wash oneself in the shower洗澡
take a stroll / go for a stroll: take a short walk散步
have the impulse to do sth.:有冲动做某事
	a sudden strong wish or need to do something, without stopping to think about the results
dozens of sth./sb.: dozen是12个,几十个
--------------------
for instance: for example比如
at the idea of ...: 一想起
The sad truth is that + ...: 悲伤的事实是
be brought up to do sth.: 从小一直做某事
stick to sth.: continue doing or using (something) especially when it is difficult to do so坚持某事
notice sb. doing sth.: 注意到某人正在做某事
be delighted to do sth.: be willing to do sth.; be ready to do sth.非常愿意做某事
stay to dinner = stay for dinner: 留下来吃晚餐
to sb's dismay: disappointment使某人失望的
take possession of sp.: occupy sp.占据某地

** L24 A skeleton in the cupboard
[[./NCE3/L24 A skeleton in the cupboard.html]]
skeleton: [ˈskelɪt(ə)n] n. the structure consisting of all the bones in a human or animal body骷髅
seemingly: [ˈsimɪŋli] adv. apparently 似乎,好像
respectable: [rɪˈspektəb(ə)l] adj. someone who is respectable behaves in a way that is considered socially acceptable体面的,雅观的
conceal: [kənˈsil] v.隐藏,隐瞒
vivid: [ˈvɪvɪd] adj. vividly adv.生动的
dramatic: [drəˈmætɪk] adj. drama n. dramatically adv.  great and sudden令人激动的,扣人心弦的
ruin: [ˈruɪn] v.毁坏
heroine: [ˈheroʊɪn] n. hero 女主角
fiction: [ˈfɪkʃ(ə)n] n. books and stories about imaginary people and events小说
varying: [ˈveriɪŋ] adj. different不同的
medicine: [ˈmedɪsɪn] n.医学
guestroom: [ɡest] n.客房
unpack: [ʌnˈpæk] v.(从箱子)取出
stack: [stæk] v. to make things into a neat pile, or to form a neat pile堆放,排放
underclothes: [ˈʌndərˌkloʊðz] n. = underwear内衣
drawer: [ˈdrɔːə(r)] n.抽屉
petrify: [ˈpetrɪˌfaɪ] v. extremely frightened, especially so frightened that you cannot move or think使惊呆
dangle: [ˈdæŋɡ(ə)l] v. to hang or swing loosely, or to make something do this悬挂
sway: [sweɪ] v. to move slowly from one side to another摇摆
unsympathetic: [ˌʌnsɪmpəˈθetɪk] adj.不表同情的,无动于衷的
medical: [ˈmedɪk(ə)l] adj.医学的

a skeleton in the cupboard/closet: they are keeping secret a bad or embarrassing fact about themselves橱柜的骷髅,不为人知的秘密
sth. be concealed from sb. = conceal sth. from sb.对某人隐瞒某事
drama queen: 戏精
ruin my day: 毁了我一天
science fiction: 科幻小说
to varying degrees: 多种程度上
in the drawer/ from the drawer: 在抽屉
be petrified of sth.: 被某物惊呆
medical student/school: 医学生/院
--------------------
It is all very well (and good)..., but not in reality + ...: 一切都很好...,但是事实并非如此+...
make one's hair stand on end: 使某人汗毛耸立
in sb's youth: 在某人年轻时
show sb. to sp.: 带某人去某地
bring sth. with sb.: 随身携带某物
it give sb. the impression that + ...: 它给我一种印象+...
be about to do sth.: 要做某事
leap out at sb.: 扑向某人
once upon a time: 曾经

** L25 The Cutty Sark
[[./NCE3/L25 The Cutty Sark.html]]
impressive: [imˈprɛsiv] adj. makes you You careless mistakes may manifest as the loss of money of our company one dayadmire it because it is very good, large, important etc给人深刻印象的
steamship: [ˈstimˌʃɪp] n.蒸汽轮船
vessel: [ˈves(ə)l] n. a ship or large boat轮船,大木船
era: [ˈɪrə] n.时代
Java: [ˈdʒɑvə] n.
rudder: [ˈrʌdər] n. a flat part at the back of a ship or aircraft that can be turned in order to control the direction in which it moves舵
roll: [roʊl] v.滚动
steer: [stɪr] v. to control the direction a vehicle is going, for example by turning a wheel掌握方向
temporary: [ˈtempəˌreri] adj.临时的
plank: [plæŋk] n.木板
fit: [fɪt] v.安装
equator: [ɪ'kweɪtə(r)] n.赤道
delay: [dɪˈleɪ] n.延误

a new era/ the beginning/end of an era: 新时代
A be fitted with B: A被装上了B
delay in doing sth.: 延迟做某事
--------------------
A be replaced by B: A被B替换
take the lead (in doing sth.) lose one's lead: 领先做某事 失去领先
be struck by: to be very impressed by被...所打动
from side to side: moving to the left and then to the righ左右摇晃
it become impossible to do sth.: 做某事变得不可能
with great difficulty: 非常困难地
There is a danger that + ...: 有...的危险
call in on/at: visit拜访
by now: 目前为止
There is no doubt that + ...: 毫无疑问

** L26 Wanted, a large biscuit tin
[[./NCE3/L26 Wanted, a large biscuit tin.html]]
influence: [ˈɪnfluəns] v.n.影响
pride: [praɪd] v.骄傲
taste: [teɪst] n.v.品味
exert: [ɪɡˈzɜrt] v.施加
subtle: [ˈsʌt(ə)l] adj.微妙的
advertiser: [ˈædvərˌtaɪzər] n.做广告的人
classify: [ˈklæsɪˌfaɪ] v. to decide what group something belongs to 分类
magic: [ˈmædʒɪk] adj.有奇妙作用的
sample: [ˈsæmp(ə)l] n.样品
devise: [dɪˈvaɪz] v.设计
capture: [ˈkæptʃər] v.吸引,赢得
manufacturer: [ˌmænjəˈfæktʃərər] n.制造商
wheelbarrow: [ˈhwilˌberoʊ] n. a small cart with one wheel and two handles that you use outdoors to carry things, especially in the garden独轮手推车
boot: [but] n.(汽车尾部的)行李箱
ingredient: [ɪnˈɡridiənt] n.食材,成分
crane: [kreɪn] n. a large tall machine used by builders for lifting heavy things起重机
anticipate: [ænˈtɪsɪˌpeɪt] v. to expect that something will happen and be ready for it预期,预料

bad/good/positive etc. influence (on sb.): 坏/好/积极的影响对某人
have an influence on sb./sth.: 对某人/物有一个影响
be influenced by ...: 被...所影响
pride oneself on (doing) sth. = be pround of:自豪于某事物
have good/bad taste in sth.: 对某物有好的品味
exert a subtle/some influence on/over sb.: 在某人上施加微妙的影响
have a subtle mind: 拥有敏锐的思想
classify a. as/under b.: 把A归类为B
say the magic word: 说出咒语
free samples of sth.: 某物的免费的样品
devise a way/plan to do sth.:设计出方法/计划去做某事
capture the attention of sb. = capture sb's attention引起某人的注意
in the boot of sb's car: 在车的后备箱
It is anticipated that + ...: 据估计
sb. anticipate that + ...: 某人预估
--------------------
as引导的倒装句 表 让步
	- Much as ..., ...
	- adj./n./v. + as ...,句子: adj-est.去the, n.去冠, v.用原型
	- 为什么要试试自己查语法书
--------------------
avoid being done: 避免被做某事
be free to do sth.: 免于做某事
in sb's effort to do sth.: 在某人努力做某事下
get sth. for nothing: 免费得到东西
enable sb. to do sth.: 使得某人能做某事
a. has made it possible for sb. to do sth.: 使得某人能做某事
come along: arrive到达
buy sth. from sb.: 从某人那里买某物

** L27 Nothing to sell and nothing to buy
[[./NCE3/L27 Nothing to sell and nothing to buy.html]]
philosopher: [fɪˈlɑsəfər] n.哲学家
wisdom: [ˈwɪzdəm] n.智慧
priest: [prist] n. vicar 神父
spiritual: [ˈspɪrɪtʃuəl] adj.精神上的
grudge: [ɡrʌdʒ] v.n. a feeling of dislike for someone because you cannot forget that they harmed you in the past不愿给
surgeon: [ˈsɜrdʒən] n. a doctor who does operations in a hospital外科大夫
passer-by: ['pɑːsə] n. passers-by过路人
dignity: [ˈdɪɡnəti] n.尊严
deliberately: [dɪˈlɪb(ə)rətli] adv.故意地
consequence: [ˈkɑnsəkwəns] n.后果,结果
afflict: [əˈflɪkt] v.折磨
ease: [iz] n. easy to do it容易
nature: [ˈneɪtʃər] n.大自然
contempt: [kənˈtempt] n.轻蔑
envious: [ˈenviəs] adj. wanting something that someone else has嫉妒的

question/doubt the wisdom of (doing) sth.: 质疑做某事是否明智
give sb. spiritual comfort: 给某人精神上的安慰
grudge doing sth.: 不愿意做某事
have/hold a grudge against sb.: 对某人怀恨在心
die/treat/do sth. with dignity: 有尊严地xx
have consequences: 产生后果
be afflicted with/by sth.: 被某事折磨
with great/considerable ease: 很容易地
love of nature: 热爱大自然
speak of/treat sb./sth. with contempt: 轻蔑对待/谈起某人
be/feel/get/become envious of sb.: 嫉妒某人
--------------------
live by doing sth.: 以做某事为生
in the light of sth./in light of: 鉴于某事
in terms of sth.: 从某物来说
It is difficult to do sth.: 做某事困难
seem to be/do sth.: 似乎是/做某事
be the exception to the rule: 规则的例外情况
in doing sth.: 结果是
choose to do sth.: 选择做某事
be free from sth.: 摆脱某事
in the open (air): 露天

** L28 Five pounds too dear
[[./NCE3/L28 Five pounds too dear.html]]
wares [wer] n. silverware n.:器物  银器
anchor: [ˈæŋkər] v.n.停航下锚
deck: [dek] n.甲板
tempt: [tempt] v.吸引;引诱
bargain: [ˈbɑrɡən] v.n.讨价还价
disembark: [ˌdɪsɪmˈbɑrk] v. to get off a ship下船上岸
assail: [əˈseɪl] v.骚扰
marble: [ˈmɑrb(ə)l] n.大理石
inscribe: [ɪnˈskraɪb] v.雕刻
favour: [ˈfeɪvər] n. favor 优惠
gesticulate: [dʒəˈstɪkjəˌleɪt] v.做手势
outrageous: [aʊtˈreɪdʒəs] adj.不公的
thrust: [θrʌst] v.猛塞

on the deck: 在甲板上
tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.: 引诱某人做某事
bargain with sb.: 和某人讨价还价
make a bargain with ...: 和某人讨价还价
be assailed by sb.: 被某人骚扰
A be inscribed on B A被雕刻在B上
as a special/personal favor (to sb.): 作为对某人的特殊优惠
do me a favor: 帮我个忙
it is outrageous (that) + ...: xx使非常不公的
thrust sth. into sw. (especially my hands): 猛塞某物在某处 
--------------------
speed to sp.: 加速到某地
sb. have no intention of doing sth.: 某人无意做某事
I can't conceal the fact that + ...: 我无法隐藏事实+...
sb. be impressed by sth.: 某人对某事印象深刻/被打动
go to great lengths to do sth.: 努力做某事
prove that + ...: 证明+...
go to great lengths to prove that + ...: 努力证明
get rid of sb.: 摆脱某人
at the base of sth.: 在...的基础上
let me have it: 给我吧
indicate that + ...: 表示...
reduce the price to $: 减少价格到...
throw up one's arms: 举起胳膊
get back to sp.: 回到某地
fill a. with b.: 用B充满A
to this day: 直到今天 by now

** L29 Funny or not?
[[./NCE3/L29 Funny or not.html]]
largely: [ˈlɑrdʒli] adv.很大程度上
comic: [ˈkɑmɪk] adj.n.漫画
universal: [ˌjunɪˈvɜrs(ə)l] adj.普遍的
comedian: [kəˈmidiən] n.喜剧演员
distasteful: [dɪsˈteɪstfəl] adj.讨厌的
pester: [ˈpestər] v.纠缠
dread: [dred] v.惧怕
recovery: [rɪˈkʌvəri] n.康复
plaster: [ˈplæstər] n.熟石膏
console: [ˈkɑnˌsoʊl] v.安慰
hobble: [ˈhɑb(ə)l] v.瘸着腿走
compensate: [ˈkɑmpənˌseɪt] v.补偿
mumble: [ˈmʌmb(ə)l] v.喃喃自语

comic book/movie/novel: 漫画书/电影/小说
have a universal appeal: 有通用的吸引力
pester sb. to do sth.: 纠缠某人做某事
dread doing sth. 惧怕做某事
dread sb. doing sth.: 害怕某人做某事
make a complete/quick/speedy/slow recovery: xx恢复
console sb./yourself that + ...: 安慰某人道 + ...
compensate (for sth.) = make up for: 补偿
--------------------
whether/whether or not .../whether...or not 主从 VS 让步状语
	1. 主从Whether引导, 不可被if代替, 在句中做1的成分
	2. whether引导让步状语从句, 在句子中状语的成分
have: stay 原则:万能+猜
--------------------
be bound up with: 与...密切相关
find it hard to do sth.: 发现做某事困难
make sb. laugh to tears: 使某人笑出眼泪
stem from ...: 源于
come into fashion: 流行起来
base A on B: 建立A在B上
judge for yourself: 自己判断
do one's best (to do sth.): try my best to do sth.尽某人最大努力做某事
take heart: 获得鼓舞
be good for sb.: 对某人有好处
in the process: 在过程中

** L30 The death of a ghost
[[./NCE3/L30 The death of a ghost.html]]
labourer: ['leɪbərər] n. laborer劳动者
overnight: [ˈoʊvərˌnaɪt] adv.一夜之间
hay: [heɪ] n.干草
corn: [kɔrn] n.谷物
moonlight: [ˈmunˌlaɪt] n.月光
conscientious: [ˌkɑnʃiˈenʃəs] adj.认真的
suspect: [ˈsʌˌspekt] v.怀疑
desert: [ˈdezərt] v.开小差
regiment: [ˈredʒɪmənt] n.团(军队)
action: [ˈækʃ(ə)n] n.战斗
recluse: [ˈrekˌlus] n.隐士

stay overnight in the hay: to sleep somewhere for one night在干草中过夜
in the moonlight: 在月光下
suspect (that) + ...: 怀疑+...
a regiment of ...: 一团/群...
be killed in action: 战斗中牺牲
--------------------
every time: 时间状语 = whenever
wake up to find that + ...: 醒来发现+...
old elder eldest: 只能sb.,不能接sth.,也不能接than
	older oldest: 既能sb.,也能sth.
--------------------
for years: 数年
stay up (overnight): 熬夜
it became an accepted fact that + ...: 这已成为公认的事实+...
be supposed to be/do sth.: 应该是/做某事
remain in doing sth.: proceed to do sth.继续做某事
none other than: 不是其他人是
think it one's duty to do sth.: 认为做某事是某人的义务
keep sb. in hiding: 藏起某人
find it impossible to do sth.: 发现做某事不可能

** L31 A lovable eccentric
[[./NCE3/L31 A lovable eccentric.html]]
lovable: [ˈlʌvəb(ə)l] adj.可爱的
eccentric: [ɪkˈsentrɪk] n.(行为)古怪人
disregard: [ˌdɪsrɪˈɡɑrd] v. to ignore something or treat it as unimportant不顾,漠视
convention: [kənˈvenʃ(ə)n] n.习俗,风俗
conscious: [ˈkɑnʃəs] adj. aware 感觉到的
invariably: [ɪnˈveriəbli] adv.总是
routine: [ˌruˈtin] n.常规;惯例
shrewd: [ʃrud] adj.精明的
eccentricity: [ˌeksenˈtrɪsəti] n.怪癖
legendary: [ˈledʒənˌderi] adj.传奇般的
snob: [snɑb] n.势力小人
intensely: [ɪn'tensli] adv.强烈地
bedraggled: [bɪˈdræɡ(ə)ld] adj.拖泥带水的
dump: [dʌmp] v.把...砰的抛下
apologetic: [əˌpɑləˈdʒetɪk] adj.道歉的
reprimand: [ˈreprɪˌmænd] v.训斥
stage: [steɪdʒ] v.n.暗中策划
elaborate: [ɪˈlæb(ə)rət] adj.精心构思的

disregard social conventions: 无视社会习俗
be conscious of (doing) sth.: 意识到做某事
sb. be conscious that + ...: 某人意识到+...
daily routine: 日常惯例
dump sth. on sth.: 扔某物在某物上
be apologetic about/for sth.: 为某事道歉
reprimand sb. for (doing) sth.: 斥责某人做某事
elaborate plan/design/meal: 精心制定计划
--------------------
draw attention to sb.: 引起某人的注意
win sb. sth.: 赢得某人某物
add a. to b.: 把A加到B
up to the time of sth.: 到...的时候
go on foot: 走路
be caught in: 淋雨
sb. request to do sth.: 某人请求做某事
present sb. with sth.: 送某人某物
invite sb. to do sth.: 邀请某人做某事

** L32 A lost ship
[[./NCE3/L32 A lost ship.html]]
salvage: [ˈsælvɪdʒ] v.n. 救助;打捞
Barents: n.(海)
sunken: [ˈsʌŋkən] adj.沉没的
cargo: [ˈkɑrɡoʊ] n.一车/船货物
bullion: [ˈbʊljən] n. un. bars of gold or silver金条;银条
scour: [skaʊr] v.搜寻
chest: [tʃest] n.大箱子
contents: [kənˈtent] n.(复数)所装的东西
belongings: [bɪˈlɔŋɪŋz] n.(复数)所有物
item: [ˈaɪtəm] n.物件
cruiser: [ˈkruzər] n.巡洋舰
find: [faɪnd] n. thing找到的物品
log: [lɔɡ] book: 日志本
piece: [pis] v. 拼成整体
convoy: [ˈkɑnˌvɔɪ] n. 护航
torpedo: [tɔrˈpidoʊ] v. n. 用鱼雷攻击
submarine: [ˈsʌbməˌrin] n. 潜水艇
naval: [ˈneɪv(ə)l] adj. navy n.海军的
ministry: [ˈmɪnɪstri] n. (政府的)部
--------------------
salvage operation: 打捞行动
a cargo of: 一货...
piece together: 拼装起来
in a convoy: 在护航中
a naval officer: 一个海军军官
--------------------
sb. be under the impression that + ...: 某人在...幻觉/印象下
together with: 除了...还有
come to light: 披露出来

** L33 A day to remember
[[./NCE3/L33 A day to remember.html]]
prelude: [ˈpreljud] n. 前奏
unforeseen: [ˌʌnfɔrˈsin] adj.意料之外的
series: [ˈsɪriz] n.系列
catastrophe: [kəˈtæstrəfi] n.大灾
crockery: [ˈkrɑkəri] un.陶器
suburb: [ˈsʌˌbɜrb] n.郊区
collide: [kəˈlaɪd] v.猛撞
learner: [ˈlɜrnər] n.初学者
panic: [ˈpænɪk] n.恐慌
windscreen: [ˈwɪn(d)ˌskrin] n. windshield 挡风玻璃
alongside: [əˈlɔŋˌsaɪd] prep. adv.在...的旁边
slide: [slaɪd] slid slid v.滑
stray: [streɪ] adj. 迷失的,离群的
confusion: [kənˈfjuʒ(ə)n] n. 混乱
greedily: [ˈɡridɪlɪ] adv.贪婪地
devour: v. 狼吞虎咽地吃

a prelude to sth.: 某事的前奏
unforeseen + changes/problems/circumstances: 不可预见的改变/问题/情形
a series of: 一系列
be a catastrophe for sb.: 对某人来说大灾祸
in the suburbs/ a suburb of city: 在城区的郊区
collide with=run into: 碰撞
get into a panic: 陷入恐慌
draw up alongside sb.: 超车某人
slide off/open: 滑走/开
stray dogs: 流浪狗
There is some confusion about sth.: 对某事有些疑惑
--------------------
get out of control: 失去控制
What invariably happens is that + ... 总是发生的是+...
set up a chain of reactions: 建立一连串的反应
keep an eye on sb.: 留意某人
be/speak/talk on the phone: 在打电话
hang up (on sb.): 挂电话
attend to sb./sth.: 照料某人
reduce sb. to tears:  they make you feel so unhappy that you cry使某人落泪
on a big/large/small scale: 大规模地
drawing up alongside sb.: 超车某人
rush hour: 高峰期
pull up: 停车 (of a vehicle) come to a halt.
all of a sudden = suddenly: 突然地
pile up: accumulate积累
get the traffic on the move: 使得交通动起来
sweep up: 打扫干净
benefit from sth.: 得益于某事

** L34 A happy discovery
[[./NCE3/L34 A happy discovery.html]]
antique: [ænˈtiːk] n.古董,古玩
fascination: [ˌfæsɪˈneɪʃ(ə)n] n.魅力,迷惑力
forbidding: [fəˈbɪd] adj.望而生畏的
muster: [ˈmʌstər] v.鼓起
pretentious: [prɪˈtenʃəs] adj.自命不凡的,绞饰的
labyrinth: [ˈlæbəˌrɪnθ] n.迷宫
musty: [ˈmʌsti] adj.陈腐的,发霉的
rarity: [ˈrerəti] n.稀世珍品
assorted: [əˈsɔrtəd] adj.各式各样的
junk: [dʒʌŋk] n.破落货,废品
litter: [ˈlɪtər] v.杂乱地布满
dedicated: [ˈdedɪˌkeɪtəd] adj.专心致志的
bargain: [ˈbɑrɡən] hunter 到处找便宜买的人
dealer: [ˈdilər] v.商人
cherish: [ˈtʃerɪʃ] v.期望,渴望
amply: ['æmpli] adv.足够地
masterpiece: [ˈmæstərˌpis] n.杰作
mere: [mɪr] adj.仅仅
prise: [praɪz] v.撬开
carve: [kɑrv] v.镌刻
dagger: [ˈdæɡər] n.短剑,匕首
miniature: [ˈmɪnɪtʃər] adj.小巧的,小型的
composition: [ˌkɑmpəˈzɪʃ(ə)n] n.构图

antique shop/store/desk/jewelry: 古董店
hold/have a fascination for sb./sth.: 对某人/某事物着迷
forbidding place/look: 冷冰冰的地方/脸
muster (up) the courage/confidence/to do sth.: 鼓起勇气/自信去某事
in the labyrinth of sth.: 在某物的迷宫中
junk mail: 垃圾邮件
be littered with sth.: 乱扔某物
sb. cherish the hope that + ...: 某人怀着希望+...
The mere fact that + ... + 23456: 事实(...)仅仅是
prise sth. open: 撬开某物
carve a. from/out of b.=a. be carved from/out of b.: 从B中雕刻出A
--------------------
There is always hope that + ...: 总有希望...
by chance: 偶然
above all: 所有之上,尤其是
be bent on doing sth.: 决心做某事
sb. cherish the hope that + ...: 某人怀着希望+...
describe to sb. what/how + 宾从 = describe sth. to sb. 向某人描述...
pick up: 捡起
sb. can't/couldn't be bothered to do sth.: 做某事不耐烦(不想做)
beg sb. to do sth.: 恳求某人做某事
at the bottom of ...: 在...的底部

** L35 Justice was done
[[./NCE3/L35 Justice was done.html]]
justice: [ˈdʒʌstɪs] n.正义,公正;司法
court: [kɔrt] n.法院
law: n.法律
innocence: [ˈɪnəs(ə)ns] n.无辜
undertake: [ˌʌndərˈteɪk] v.承担;着手做
arduous: [ˈɑrdjuəs] adj.艰苦的
abstract: [æbˈstrækt] adj.抽象的
concept: n.概念,观念
mete: [mit] out 给予,处置
interference: [ˌɪntərˈfɪrəns] n.干涉
accord: [əˈkɔrd] n.一致
premises: [ˈpremɪsəz] n.房屋
convert: [ˈkɑnˌvɜrt] v.转变
disused: [dɪsˈjuzd] adj.废弃的
fireplace: [ˈfaɪrˌpleɪs] n.壁炉
muffle: [ˈmʌf(ə)l] v.捂住
chip: [tʃɪp] v.砍
blacken: [ˈblækən] v.使变黑
emerge: [ɪˈmɜrdʒ] v.(从某处)出现

justice has been done/served: 正义得到伸张
court of law; courts of law: 法庭
prove sb's innocence: 证明某人的无辜
undertake a task/a project/research/a study/a journey: 承担重任
arduous task of doing sth./arduous journey: 做某事的重任
go through/embark on/begin arduous journey: 开始艰辛的旅程
understand + abstract concept: 理解抽象概念
interference in sth.: 对某事的干涉
Sorry for the interference, + ...: 很抱歉打扰了, ...
I hope you don't mind the interference, but + ...: 我希望你不介意打扰,但是+...
of sb's/sth's own accord: you do it because you want to, without being asked or forced处于某人的自愿
on the premises of a.: 在A的前提下
convert a. to/into b.: 把A变成B
emerge from sp.: 从某处出现
--------------------
however = no matter how 让步状语
get + done 被动
--------------------
beyond doubt: 毫无疑问
make mistakes: 犯错
There are rare instances when + ...: 有极少例子当...
cease to do: 不再去做
be independent of: 独立于
in part: 部分地
run to tell sb.: 跑去告诉某人
ring up: call sb. by phone打电话
tap at sth.: 敲击某物
listen for ...: 为...而听
be unable to do sth.: 不能做某事
break into sp.: 破门而入
be handed over to sb.: 被移交给

** L36 A chance in a million
[[./NCE3/L36 A chance in a million.html]]
credulous: [ˈkredjələs] adj. 轻信的
improbable: [ɪmˈprɑbəb(ə)l] adj. 不大可能的
obscure: [əbˈskjʊr] adj. 不起眼的
maidservant: [ˈmeɪdˌsɜrvənt] n. 女仆
presume: [prɪˈzum] v. 假定
wickedly: ['wɪkɪdli] adv. 心眼坏地
plot: [plɑt] v. 密谋
downfall: [ˈdaʊnˌfɔl] n. 倒台
naive: [nɑˈiv] adj. 天真的
unacceptable: [ˌʌnəkˈseptəb(ə)l] adj.不能接受的
conspire: [kənˈspaɪr] v.巧合促成
incredible: [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance: [rɪˈzembləns] n.相似
scorn: [skɔrn] n.嘲弄
acquaint: [əˈkweɪnt] v.使了解
reunite: [ˌrijuˈnaɪt] v.使团聚
assume: [əˈsum] v.假定,认为

It seems (highly/wildly) improbable that + ...: 似乎不可能
be presumed dead/innocent/guilty: 假定死亡/无辜/有罪
presume that + ...: 假定...
plot to do sth.: 密谋做某事
plot against sb.: 暗算某人
lead to sb's downfall: 导致某人的垮台
bring about sb's downfall: 使某人垮台
it be naive enough to believe/think + ...: 相信/认为+...是足够天真的
sb. be naive enough to believe/think + ...:某人足够天真才会相信/认为+...
it be unacceptable to do sth.: 做某事是不可接受的
conspire to do sth.: 合谋做某事
it is incredible (to sb.) that + ...: 难以置信的
it is incredible how + ...: 难以置信多么地...
it is incredible to do sth.: 做某事是难以置信的
bear a close/strong/striking resemblance to sb./sth.: 对某人/物非常相似
bear little/no resemblance to sb./sth.: 对某人/物不相似
resemblance to ...: 对...的相似
pour scorn on: 嘲笑
pour scorn on the idea/suggestion/plan/advice: 嘲笑...
acquaint sb. with sth.: 使某人熟悉某事物
sb. be acquainted with sth.: 某人熟悉了某物
be reunited with sb.: 和某人团聚
assuming that + ...: 假设...
it seems/is reasonable to assume that + ...: 假设...是合理的
--------------------
to do 非谓语结构
--------------------
a chance in a million: 百万分之一
bring ... to a conclusion: 把...结束
sb. accepted the fact that: 某人接受事实...
bring about sth.: 引起某事
and so on: 等等
anyone but: 所有人除了...
be thought to: 被认为...
stop to do:停下来去做某事 VS stop doing sth: 停下来做的事情
comment on sth./sb.: 评论...
suggest that + ...: 建议虚拟语气; 假设不用虚拟语气
there is/was a chance that + ...: ...有可能
needless to say: 不用说
towards the end of + sth.: 接近...的结尾
be separated from: 与...分离
make one's way back to sp.: 回某地
return to: 回去
What become of: 怎么了

** L37 The Westhaven Express
[[./NCE3/L37 The Westhaven Express.html]]
express: [ɪkˈspres] n.快车 adj.高速的
punctual: [ˈpʌŋktʃuəl] adj. punctually adv.准时的
condition: [kənˈdɪʃ(ə)n] v.使习惯于
unshakable: [ʌn'ʃeɪkəbl] adj.不可动摇的
faith: [feɪθ] n.信任
cancel: [ˈkæns(ə)l] v.取消
exceptionally: [ɪkˈsepʃənli] adv.例外地
dislocate: [ˈdɪsləˌkeɪt] v.打乱(计划等)
blame: [bleɪm] v.责怪
consult: [kənˈsʌlt] v.请教,查阅
direct: [daɪˈrekt] adv.径直地
odd: [ɑd] adj.奇怪的
reflect: [rɪˈflekt] v.细想
advantage: [ədˈvæntɪdʒ] n.优势
mighty: [ˈmaɪti] adj.强大的,有力的
dawdle: [ˈdɔd(ə)l] v.慢吞吞地动或做
chug: [tʃʌɡ] v.喀嚓喀嚓地响
lodge: [lɑdʒ] v.提出
complaint: [kəmˈpleɪnt] n.抱怨
triumph: [ˈtraɪəmf] n.胜利
asterisk: [ˈæstərɪsk] n.星号
conduct: [ˈkɑnˌdʌkt] v.引向

be punctual for: 准时
condition sb. to (do) sth.: 训练某人做某事 
sb. be conditioned to do sth.: 某人(被训练)习惯于做某事
develop an unshakable belief/faith in sb./sth.: 对某人/某事有不可动摇的信心
have/lose faith in sb./sth.: 对某人/某事有信心
blame sb. for sth.: 责怪某人某事
blame sth. on sb.: 责怪某人某事
consult the map/manual/dictionary: 查地图/手册/字典
go/fly direct: 直接去
It is/seems odd that + ...: 似乎很奇怪
reflect that + ...: 反应出...
reflect on sth.: 思考某事
lodge a complaint: 投诉
have/make/receive/lodge a complaint: 投诉
a note of triumph: 胜利的音符
conduct sb. to sp.: 引导某人注意某处
--------------------
neither + 部分倒装
not... but ... 不是... 而是...
--------------------
It is all too easy to do sth.: 很容易做某事
sb. noted with satisfaction that + ...: 某人满意的发现
can't help doing sth.: 忍不住做某事
strike sb as sth./sb.: 使某人想起某人某物
take advantage of sth./sb.: 利用
wish to do sth.: 期望做某事
hold up: 堵住
It dawned on me that + ...: 我突然想到
roar down: 呼啸而下
not do sth. but + ...: 不但做某事,而且...
hear of: 听说
copy of sth.:	一本...
in black and white: 白纸黑字地
at the bottom of sth.: 在某物的底部 
