#+OPTIONS: \n:nerve-wrackingt num:nil html-postamble:nil
* TED-ED
** 2013-10-01 The uncertain location of electrons
in a momentary tangent: to start talking about something that is only slightly or indirectly related to the original subject
develop a model for sth.: 
agree with the model: 
it might be time for sth./ to do sth.: 
there will be many more to come: 
tend to do sth.: 
stick together: 
behave as/like sth.: 
perform experiment : 
It's (not) that + ..., it's that + ..: 
there's a certain probability of doing sth.: 
be 95% sure of doing: 
more or less:
decrease/increase exponentially: 
approach/hit zero: 
there is some small, but non-zero, probability that + ..: 
for a very, very short period of time: 
interact with: 
surrender A. to B.: to give up something or someone, especially because you are forced to
** 2013-10-03 Why extremophiles bode well for life beyond Earth
outer space:
abduction by sb.: 
in the universe: 
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose
form life: 
ancient religions: 
be inhabited by sb.: 
sth. be more like A. than B.: 
mythical realms: 神话王国
parallel universes: 
It is only within the last century that + ...: 
undertake sth./ to do sth.: 
A. is just the right distance from B.: 
support life: 
sth. is fatal for sb.: resulting in someone’s death
in the dark depths of oceans/lakes/rivers: 
on the flanks of volcanoes: the side of a hill, mountain, or very large building
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things 
What is most remarkable about sth. is that + ...: 
hit the surface of sth.: 
be flowing with: to have some liquid coursing on the surface or within someone or something
be composed of sth.: 
be the basic building block of sth.: 
** 2013-10-08 The operating system of life
in the back of your fridge: 
sb. is a gleam in sb's eyes: 
share the same basic goal: 
perpetuate sb's existence: 
stay alive: 
set up a factory: 
keep sb. doing sth.: 
assembly instructions: 
raw materials: 
get paid: 
send sth. off: 
assemble A. into B.: 
be transported to sp.: 
draw energy from sth.: 
harsher working conditions: 
be walled off: 
the rest of sth.: 
be embedded into sth.: 
be built from sth.: 
are derived from: to come or develop from something 来源于
in a pinch: in an emergency
minimum wage: 
be transferred between: to move someone or something from one place, vehicle, person, or group to another
in the face of sth.:
extreme challenges:
mobilize the immune system: 

* other(If they are too many, then split them)
** public speaking
feel nervous about doing sth.:
give a speech:
in good company: be in the same situation as someone important or respected.
suffer from:
stage fright: nervousness before or during an appearance before an audience
turn pale: their face looks a lighter color than usual, usually because they are ill, frightened, or shocked.
at the outset of a speech:
quake in every limb and in my soul:
report doing sth.:
speaking in public:
be nominated for:
nerve-wracking experience:makes you feel very tense and worried
in jest:
sb. be given a choice/give sb. a choice
would rather do A. than do B.
give the eulogy:

** the best life story
*** 02 Lazy Summers
swoop: 向下猛冲
buzz: 嗡嗡
swat it away: 拍死它
bring a smile to my face: 让我脸上泛起微笑
A. join in the chorus of B.: A加入到B一起
have memories of:想起
swirl around: 盘旋在
reminisce (about): 缅怀

** Reading to Learn the Art of Expression
observant
clause

biographical sketch
forms of ...
from all over England
sb's aim is to do ...
receive treatment (from sb.)
at a time when ...
stay adj.

** humans of NewYork
be down to ride: support
*** 01 You're the best dad ever
pop up
what it's like: to be familiar with how it feels to be or do something
rip out heart
back off
get a flicker of: a feeling or expression of an emotion or quality that does not last very long

** Let him Go, Olivia
It's over.
pass away
in recognition of sb.:褒奖
write this story as a tribute to sb.
make it possible for sb to have done

** Children’s Engineering Workshops.
workshop: 研习班
want some information about sth. :想要某物的信息
design a adj. cover that goes round sth. : 设计一个保护套包裹住某物
there is an opportunity for sb. to do sth.: 对某人有机会做某事
be amazed + ...: 对...吃惊
one thing sb. does is to do sth.:某人做的一件事是做某事
A. be attached to B.: B绑到A上
the force of air/water: 空气的力量
presumably: 估计是
advanced: 更高级的
construct A. using B.: 用B来构造A
pick sth. up: 某事进步
use A. to do B.: 用A来做B
come up with=think up an idea for sth.: 为某事想出主意
A. in the shape of B.: B形状的A
give sb. enough time to do sth.: 给某人足够的时间去做某事
up past sp.: 过了某处
enrol: 报名

** stoicism
achieve sb's triumphs
the likes of sth.: is used to refer to people or things of a similar type or category
have access to sth.: possess the ability or permission to use, enter, or obtain something.
come to sb.: emphasizes the process of understanding or realization
in turn: used to explain how a series of actions or circumstances are interconnected
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."
put on ...: mean to organize, present, or perform a show, event, or production.
prime minister: the most important minister and leader of the government in some countries which have a parliament
the course of ...: is used to describe the progression or development of something over a period of time.
at the root of sth.: refers to the fundamental or foundational essence of a concept, idea, problem, or situation
resonate with: if something such as an event or a message resonates, it seems important or good to people, or continues to do this
refer to a. as b.: regard sth. as sth.
* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
- 结合其他语法

* NCE2 homework
** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion

* NCE3 homework
** 单词造句
** 反复听电影片段直到懂关键句
** 给自己讲解语法
** 反复朗读语法例句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
* NCE2
** L01 A private conversation
private [ˈpraɪvət] adj.
conversation [ˌkɒnvəˈseɪʃ(ə)n] n.
theatre [ˈθɪətə(r)] n.
seat [siːt] n.
play [pleɪ] n.
loudly [ˈlaʊdli] n.
angry [ˈæŋɡri] adj.
angrily [ˈæŋɡrəli] adv.
attention [əˈtenʃ(ə)n] n.
bear [beə(r)] v.
business [ˈbɪznəs] n.
rudely [ˈruːdli] adv.

have a conversation
take a seat
Is the seat taken?
How can you bear that?
Don't be rude

--------------------
1. 如何造一个英语句子 6123456
2. 如何造一个好的英文句子
3. 英语语序

go to the theatre
have a good seat
get angry
turn round
pay attention
in the end
couldn't bear it
It's none of your business

** L02 Breakfast or lunch?
until [ʌnˈtɪl] prep.
outside [ˌaʊtˈsaɪd] adv.
ring [rɪŋ] v.
aunt [ɑːnt] n.
repeat [rɪˈpiːt] v.

repeat after me

--------------------
am/is/are + doing VS do/does
感叹句
频率adv.位置

get up early/late
just then
have breakfast

** L03 Please send me a card
send [send] v.
postcard [ˈpəʊstkɑːd] n.
spoil [spɔɪl] v.
museum [mjuˈziːəm] n.
public [ˈpʌblɪk] adj.
friendly [ˈfrendli] adj.
waiter [ˈweɪtə(r)] n.
lend [lend] v.
decision [dɪˈsɪʒ(ə)n] n.
whole [həʊl] adj.
single [ˈsɪŋɡ(ə)l] adj.

buy sb. sth. = buy sth. for sb.
send sb. sth. = send sth. to sb.
lend sb. sth. = lend sth. to sb.
borrow sth. from sb. / borrow sth.
make a decision

--------------------
was
were
did

teach sb. sth.
lend sb. sth.
think about sth./sb.
on the last day
make a decision
send sth. to sb.
spend st. sw.

** L04 An exciting trip
exciting [ɪkˈsaɪtɪŋ] adj.
receive [rɪˈsiːv] v.
firm [fɜːm] n.
different [ˈdɪfrənt] adj.
centre [ˈsentə(r)] n.
abroad [əˈbrɔːd] adv.

have a great trip
receive sth. from sb.
work for
A be different from B
in the centre of sw.
go abroad
live abroad
study abroad

--------------------
have done

receive sth. from sb.
work for sb.
a great number of
have gone to sw.
fly to sw.
find n. adj.

** L05 No wrong numbers
pigeon [ˈpɪdʒɪn] n.
message [ˈmesɪdʒ] n.
cover [ˈkʌvə(r)] v.
distance [ˈdɪstəns] n.
request [rɪˈkwest] n.
spare [speə(r)] part [pɑːt] n.
service [ˈsɜːvɪs] n.

leave sb. a message
customer service
cover the distance in st.

--------------------
have done VS did

A is 5 miles from B
get sth. for sb.
cover the distance in st.
a great many
send a request for sth.
up to now
in this way

** L06 Percy Buttons
beggar [ˈbeɡə(r)] n.
food [fuːd] n.
pocket [ˈpɒkɪt] n.
call [kɔːl] v.

pocket money
call at = visit

--------------------
a/an/the
some/any

move to sw.
knock at the door
ask sb. for sth.
stand on sb's head
call at
in return for this
once a st.
ask for sth.

** L07 Too late
detective [dɪˈtektɪv] n.
airport [ˈeəpɔːt] n.
expect [ɪkˈspekt] v.
valuable [ˈvæljuəbl] adj.
parcel [ˈpɑːs(ə)l] n.
diamond [ˈdaɪmənd] n.
steal [stiːl] stole [stəʊl] stolen [ˈstəʊlən] v.
main [meɪn] adj.
airfield [ˈeəfiːld] n.
guard [ɡɑːd] n.
precious [ˈpreʃəs] adj.
stone [stəʊn] n.
sand [sænd] n.

keep guard

--------------------
was/were + doing
when & while & just as


all morning
	The plane was late and detectives were waiting at the airport all morning.
a parcel of sth.
a few hours earlier
keep guard
to sb's surprise
try to do sth.
A be full of B

** L08 The best and the worst
competition [ˌkɒmpəˈtɪʃ(ə)n] n.
neat [niːt] adj. 整齐的,整洁的
path [pɑːθ] n.
wooden [ˈwʊdn] adj.
pool [puːl] n.

enter the competition
make a path
That's neat

--------------------
adj. 比较级&最高级变化规则
1. 主语 + be + the + adj.est + n. + I've ever met/seen
2. 主语 + be + the + adj.est + n. + 范围
3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)

enter for
make a path
build a bridge
win a prize

** L09 A cold welcome
welcome [ˈwelkəm] n.
crowd [kraʊd] n.
gather [ˈɡæðə(r)] v.
hand [hænd] n.
shout [ʃaʊt] v.
refuse [rɪˈfjuːz] v.
laugh [lɑːf] v.

a cold welcome
a warm welcome
gather round
shout at sb.
refuse to do sth.
laugh at sb.

--------------------
on + 具体某一天
in + 年/季/月
at + 时间点

the last day of the year
a large crowd of
in twenty minutes' time
refuse to do sth.
at that moment
begin to do sth.

** L10 Not for jazz
jazz [dʒæz] n.
musical [ˈmjuːzɪk(ə)l] adj.
instrument [ˈɪnstrəmənt] n.
clavichord [ˈklævɪkɔːd] n.
recently [ˈriːs(ə)ntli] adv.
damage [ˈdæmɪdʒ] v.
key [kiː] n.
string [strɪŋ] n.
shock [ʃɒk] v.
allow [əˈlaʊ] v.
touch [tʌtʃ] v.

be allowed to do sth.
allow sb. to do sth.

--------------------
am/is/are+done
was/were+done
am/is/are+being+done
have/has+been+done

be made in sw.
belong to sb.
play jazz
be allowed to do sth.

** L11 One good turn deserves another
turn [tɜːn] n.
deserve [dɪˈzɜːv] v.
lawyer [ˈlɔɪə(r)] n.
bank [bæŋk] n.
salary [ˈsæləri] n.
immediately [ɪˈmiːdiətli] adv.

one good turn deserves another.
get a good salary
It's your turn

get a good salary
borrow sth. from sb.
pay it back
pay for sth.
ask sb. to do sth.

** L12 Goodbye and good luck
luck [lʌk] n.
captain [ˈkæptɪn] n.
sail [seɪl] v.
harbour [ˈhɑːbə(r)] n.
proud [praʊd] adj.
important [ɪmˈpɔːt(ə)nt] adj.

lucky dog
be proud of
I got a very important question to ask you

--------------------
will do
shall do

sail from sw.
set out
have plenty of time
will be away
A be proud of B
say goodbye to sb.
take part in

** L13 The Greenwood Boys
group [ɡruːp] n.
pop [pɒp] singer [ˈsɪŋə(r)] n.
club [klʌb] n.
performance [pəˈfɔːməns] n.
occasion [əˈkeɪʒ(ə)n] n.

a group of
pop music/song/star
give a performance
on this occasion

--------------------
will be doing

a group of
at present
all parts of the country
as usual
have a difficult time
give five performance
keep order
on these occasions

** L14 Do you speak English?
amusing [əˈmjuːzɪŋ] adj.
experience [ɪkˈspɪəriəns] n.
wave [weɪv] v.
lift [lɪft] n.
reply [rɪˈplaɪ] v.
language [ˈlæŋɡwɪdʒ] n.
journey [ˈdʒɜːni] n.

have an amusing experience
wave to sb.
take a lift/ ask for a lift
A give B a lift
reply to the email/letter
go on a journey

--------------------
had + done

drive on to sw.
on the way
ask sb. for a lift
apart from
in French

** L15 Good news
secretary [ˈsekrət(ə)ri] n.
nervous [ˈnɜːvəs] adj.
afford [əˈfɔːd] v.
weak [wiːk] adj.
interrupt [ˌɪntəˈrʌpt] v.

be nervous about sth. / doing sth.
afford sth.
Sorry to interrupt, but...

--------------------
宾语从句
直接引语变间接引语

look up
afford to pay
my turn had come
in a weak voice

** L16 A polite request
park [pɑːk] v.
traffic [ˈtræfɪk] n.
ticket [ˈtɪkɪt] n.
note [nəʊt] n.
area [ˈeəriə] n.
sign [saɪn] n.
reminder [rɪˈmaɪndə(r)] n.
fail [feɪl] v.
obey [əˈbeɪ] v.

make notes/ a note
leave a note
remind sb. of sth./sb.
fail to do sth.

--------------------
if从句

park sb's car
pay attention to
	
** L17 Always young
appear [əˈpɪə(r)] n.
stage [steɪdʒ] n.
bright [braɪt] adj. + color [ˈkʌlə(r)] + n.
stocking [ˈstɒkɪŋ] n.
sock [sɒk] n.
grown-up [ˌɡrəʊn ˈʌp] adj. n.

--------------------
must
have to
can

at least
in spite of this
take part in

** L18 He often does this
pub [pʌb] n.
landlord [ˈlændlɔːd] n.
bill [bɪl] n.

pay the bill

--------------------
have 万能动词

look for
have a meal
pay the bill
in a few minutes

** L19 Sold out
hurry [ˈhʌri] v
ticket [ˈtɪkɪt] office [ˈɒfɪs]
pity [ˈpɪti] n.
exclaim [ɪkˈskleɪm] v.
return [rɪˈtɜːn] v n
sadly [ˈsædli] adv.

hurry to sw.
in a hurry
What a pity
It's a pity that...
Don't yell at me.

--------------------
现在
may/might (not) do
may/might (not) be adj./n.
may/might (not) be doing

过去
may/might (not) have done
may/might (not) have been adj./n.
may/might (not) have been doing.

sold out
at once (=immediately, soon)
might/may as well

** L20 One man in a boat
catch [kætʃ] caught caught v
fisherman [ˈfɪʃəmən] n
boot [buːt] n
rubbish [ˈrʌbɪʃ] n
waste [weɪst] n v
realize [ˈriːəlaɪz] v

catch your eye
catch a bus
watch your tongue
That's rubbish
You're wasting time.
sb. realized that...

--------------------
动名词

instead of doing sth.
spend st. sw.
give up doing sth.
be interesting in doing sth.
be keen on doing sth.

** L21 Mad of not?
mad [mæd] adj
reason [ˈriːz(ə)n] n
sum [sʌm] n
determined [dɪˈtɜːmɪnd] adj

be mad at sb.
for some reason
a large sum of money
be determined to do sth.

--------------------
will/would be done
can/could be done
must be done
have to be done
must have been done

drive sb. mad
for some reason
come into use

** L22 A glass envelope
dream [driːm] v.
age [eɪdʒ] n.
channel [ˈtʃæn(ə)l] n.
throw [θrəʊ] threw [θruː] thrown [θrəʊn] v.
regularly [ˈreɡjələli] adv.

dream of doing sth.
at my age
throw away

--------------------
v. + of/from/in/on

think of sth.
write to sb.
decide to do sth.

** L23 A new house
complete [kəmˈpliːt] v
modern [ˈmɒd(ə)n] adj
strange [streɪndʒ] adj
district [ˈdɪstrɪkt] n

You complete me.
have a letter from sb.
get a surprise

** L24 It could be worse
manager [ˈmænɪdʒə(r)] n
upset [ˌʌpˈset] adj 
complain [kəmˈpleɪn] v wicked [ˈwɪkɪd] adj
contain [kənˈteɪn] v
honesty [ˈɒnəsti] n honest [ˈɒnɪst] adj

get/be upset about sth.
complain about sth.
start to do sth.

** L25 Do the English speak English?
railway [ˈreɪlweɪ] n
porter [ˈpɔːtə(r)] n several [ˈsevrəl]
foreigner [ˈfɒrənə(r)] n
wonder [ˈwʌndə(r)] v

not know the way to sw.

--------------------
1. and,but,or,so
2. both... and, either...or,neither...nor
3. not only... but also (as well)

** L26 The best art critics
art [ɑːt] n.
critic [ˈkrɪtɪk] n.
paint [peɪnt] v.
pretend [prɪˈtend] v.
pattern [ˈpæt(ə)n] n.
curtain [ˈkɜːt(ə)n] n.
material [məˈtɪəriəl] n.
appreciate [əˈpriːʃieɪt] v.
notice [ˈnəʊtɪs] v.
whether [ˈweðə(r)] conj.(连词)
hang [hæŋ] hung hung v.
critically [ˈkrɪtɪkli] adv.
upside [ˈʌpsaɪd] down 

sb. pretend that ...
I really appreciate that.

** L27 A wet night
tent n.
field n.
smell smelt v.
wonderful adj.
campfire n.
creep v.
sleeping bag
comfortable adj.
soundly adv.
leap v.
heavily adv.
stream n.
form v.
wind wound wound v.
right adv.

put up the tent
tell a story/stories
put out the fire
begin doing sth.
wake up

** L28 No parking
rare adj.
ancient adj.
myth n.
trouble n.
effect n.
Medusa n.
Gorgon n.

have trouble with sth.
	He has had trouble with cars and their owners.
have no effect
have trouble doing sth.

--------------------
定语从句 NCE1 L121 & L123
whose引导的特殊疑问句
复习 have+done

** L29 Taxi!
taxi n.
Pilatus Porter
land v.
lonely adj.
Welsh adj.
roof n.
block n.
flat n.
desert v.

take a taxi

--------------------
done做定语
复习have done VS did

** L30 Football or polo?
polo n.
Wayle n.
cut cut cut v.
row v.
kick v.
towards prep.
nearly adv.
sight n.

kick his ass

--------------------
doing现在分词做定语

call out to sb.

** L31 Success story
retire v.
company n.
bicycle n.
save v.
workshop n.
helper n.
employ v.
grandson n.

save sb's life

--------------------
used to do sth.

It is/was sb's job to do sth.
in sb's twenties

** L32 Shopping made easy
once adv.
temptation n.
article n.
wrap v.
simply adv.
arrest v.

once upon a time
resist the temptation
wrap up sth.

--------------------
as ... as
not so ... as

It is easy for sb. to do sth.
hand sth. to sb.
wrap sth. up
as quickly as possible

** L33 Out of the darkness
darkness n.
explain v.
coast n.
storm n.
towards prep.
rock n.
shore n.
light n.
ahead adv.
cliff n.
struggle v.
hospital n.

struggle up
explain sth. to sb.
go ahead

--------------------
be high up
On doing sth, ...

** L34 Quick work
station n.
most adv.

call at = visit 不那么正式
except sth. to be found

** L35 Stop thief!
while n.
regret v.
far adv.
rush v.
act v.
straight adv.
fright n.
battered adj.
shortly adv.
afterwards adv.

a short while ago
regret sth./doing sth.
rush out of/towards
go straight ahead
give me a fright
get a fright
Shortly afterwards

--------------------
see sb. do sth
see sb. doing sth.

** L36 Across the Channel
record n.
strong adj.
swimmer n.
succeed v.
train v.
anxiously adv.
intend v.
solid adj.

set up a new world record
break the record
as strong as a horse
strong like a horse
succeed in doing sth.
train sb. to do sth.
intend to do sth.

--------------------
表述将来:
be going to do
will
intend to do

hope to do sth.
be sure to do sth.
take some rests/a rest

** L37 The Olympic Games
Olympic adj.
hold v.
governmen n.
immense adj.
stadium n.
standard n.
capital n.
fantastic adj.
design v.

hold a meeting

--------------------
will have done
have done VS had done VS will have done

look forward to doing sth.

** L38 Everything except the weather
except prep.
Mediterranean n.
complain v.
continuallly adv.
bitterly adv.
sunshine n.

complain about sth.
bitterly cold

--------------------
一前就后
had hardly done ... when ...
had no sooner done ... than ...

dream of doing sth.
plan to do
settle down

** L39 Am I all right?
operation n.
successful adj.
following adj.
patient n.
alone adj.
exchange n.
inquire v.
certain adj.
caller n.
relative n.

have an operation
leave me alone
inquire about sth./sb.

--------------------
宾语从句
NCE1 L99 L101 L133 L135 L139

refuse to do sth.
ask for sth.
be allowed to do sth.

** L40 Food and talk
hostess n.
unsmiling adj.
tight adj.
fix v.
globe n.
despair n.

in despair

--------------------
虚拟语气(现在)

take my seat
be busy doing sth.
Will you be doing sth?

** L41 Do you call that a hat?
rude adj.
mirror n.
hole n.
remark v.
remind v.
lighthouse n.

remind sb. of sth./sb.

--------------------
need
needn't have done

regret doing sth.
find sth. adj.

** L42 Not very musical
musical adj.
market n.
snake charmer
pipe n.
tune n.
glimpse n.
snake n.
movement n.
continue v.
dance v.
obviously adv.
difference n.
Indian adj.

watch a musical
play a tune
have a glimpse of sth./sb.
continue to do sth.
tell the difference from A and B / A be different from B

--------------------
have 万能动词

have a long walk
at the other side of sw.

** L43 Over the South Pole
pole n.
flight n.
explorer n.
lie lay lain v.
serious adj.
point n.
seem v.
crash v.
sackn.
clear v.
aircraft n.
endless adj.
plain n.

catch a flight
run into serious trouble
one point
It seems that ...

--------------------
be able to do sth.
时态
could VS was able to do sth.

order sb. to do sth.

** L44 Through the forest
forest n.
risk n.
picnic n.
edge n.
strap n.
possession n.
breath n.
contents n.(常用复数,内有的物品)
mend v.

take a risk
have a picnic
at the edge of a forest
in sb's possession
out of breath

rush up to sb.
catch up with sb.
go through
need doing sth.
run straight at sb.

** L45 A clear conscience
clear adj.
conscience n.
wallet n.
savings n.
villager n.
percent 

I have a clear conscience
Are you 100 percent sure about this?

--------------------
be done

sb. learn that + 宾语从句
return sth. to sb.

** L46 Expensive and uncomfortable
unload v.
wooden adj.
extremely adv.
occur v.
astonish v.
pile n.
woolen n.
goods n.
discover v.
admit v.
confine v.
normal adj.

It occurred to sb. that ...
It occurred to sb. to do sth.
be astonished at sth.
admit doing sth.
sb. admit that...

--------------------
同位语从句
区分定语从句与同位语从句

What = the thing that/the person that
sb. account for the fact that + 句子

** L47 A thirsty ghost
thirsty adj.
ghost n.
haunt v.
block v.
furniture n.
whisky n.
suggest v.
shake shook shaken v.
accept v.

shake sb's head

be up for sale
hear sb./sth. doing sth.

** L48 Did you want to tell me something?
pull v.
cotton wool
collect v.
collection n.
nod v.
meanwhile adv.

private collection

It is impossible for sb. to do
... rest for a while

** L49 The end of a dream
tired [ˈtaɪəd] adj.
real [ˈriːəl; rɪəl] adj.
owner [ˈəʊnə(r)] n. own v.
spring [sprɪŋ] n.
mattress [ˈmætrəs] n.
gust [ɡʌst] n.
sweep [swiːp] swept [swept] swept v. 扫,刮
courtyard [ˈkɔːtjɑːd] n.
smash [smæʃ] v.
miraculously [mɪˈrækjələsli] adv.
unhurt [ʌnˈhɜːt] adj.
glance [ɡlɑːns] v.
promptly [ˈprɒmptli] adv.

get/be tired of sth./doing sth.
A gust of wind swept ...
in the courtyard
smash sth. to pieces
glance at sth.

--------------------!!!
1. 分词作状语

save up for year to do sth.
for the first time in sb's life
go to sleep

*** L01
6123456

*** L25
1. 6123456 + 6123546
2. conj.
	 1. and,but,because,so,as,for
	 2. both...and...,either...or...,neither...nor...
	 3. not only ..., but also.../but... as well

** L50 Taken for a ride
reward n.
virtue n.
diet n.
forbid forbade forbidden v.
hurriedly adv.
embarrass [ɪmˈbærəs] v.
guiltily adv.
strict adj.
occasionally adv.

--------------------
do/does
am/is/are+doing
--------------------
prefer
	- prefer to do sth. = prefer doing sth. = I'd prefer to do sth
	- prefer a to b  &  prefer doing a to doing b
	- prefer to do a rather than (do) b.  &  I'd prefer to do a. rather than (do) b.

** L51 Reward for a virtue
reward [rɪˈwɔːd] n. v. 奖赏
virtue [ˈvɜːtʃuː] n. 美德
diet [ˈdaɪət] n. 节食
forbid [fəˈbɪd] forbade forbidden v. 禁止
hurriedly [ˈhʌrɪdli] adv. 匆忙的
embarrass [ɪmˈbærəs] v. 使尴尬
guiltily [ˈɡɪltɪli] adv. 内疚地
strict [strɪkt] adj. 严格的
occasionally [əˈkeɪʒnəli] adv. 偶尔地

expect/receive/give + reward
go on a diet = be on a diet
forbid sb. to do sth.
a be strict with b
--------------------
L3 & L27
was/were/did

First of all,...
write out a long list of ...
pay sb. a visit
was not surprised to see that...
It was obvious that...
ring the bell
** L52 A pretty carpet
temporarily [ˈtemprərəli] adv.
inch [ɪntʃ] n.
space [speɪs] n.
actually [ˈæktʃuəli] adv.

every inch of sth.
That's actually a good idea

--------------------
have been doing

get sth. in order
To make matters worse...
A short while ago...
gaze at sth.
in sb's spare time...
help sb. to do sth.

** L53 Hot snake
hot [hɒt] adj.
fireman [ˈfaɪəmən] n.
cause [kɔːz] v.
examine [ɪɡˈzæmɪn] v.
accidentally [ˌæksɪˈdentəli] adv.
remains [rɪˈmeɪnz] n.
wire [ˈwaɪə(r)] n.
volt [vəʊlt] n.
power line [ˈpaʊə laɪn]
solve [sɒlv] v.
mystery [ˈmɪst(ə)ri] n.
snatch [snætʃ] v.
spark [spɑːk] n.

electrical wire / electric wire
discover + cause
the remains of a snake
solve + problem/mystery
solve/remain + mystery

--------------------
did
have done
have been doing

find out
throw away

** L54 Sticky fingers
sticky [ˈstɪki] adj.
finger [ˈfɪŋɡə(r)] n.
pie [paɪ] n.
mix [mɪks] v.
pastry [ˈpeɪstri] n.
annoying [əˈnɔɪɪŋ] adj.
receiver [rɪˈsiːvə(r)] n.
dismay [dɪsˈmeɪ] v.
recognize [ˈrekəɡnaɪz] v.
persuade [pəˈsweɪd] v.
mess [mes] n.
doorknob [ˈdɔːnɒb] n.
sign [saɪn] v.
register [ˈredʒɪstə(r)] v.

stick to the plan
put my finger on it
point the finger at
be dismayed to do sth.
recognize the voice (of sb.)
persuade sb. (not) to do sth.
What a mess!
such a mess
Sign here
sign for sth.
a registered letter

send sb. to sp.
decide to do sth.
be busy doing sth.
be covered with sth.
take sb. st. to do sth.
hang up
What a mess!
sign for sth.

** L55 Not a gold mine
gold [ɡəʊld] n.
mine [maɪn] n.
treasure [ˈtreʒə(r)] n.
revealer [rɪˈvi:lə] n.
invent [ɪnˈvent] v.
detect [dɪˈtekt] v.
bury [ˈberi] v.
cave [keɪv] n.
seashore [ˈsiːʃɔː(r)] n.
pirate [ˈpaɪrət] n.
arm [ɑːm] v.
soil [sɔɪl] n.
entrance [ˈentrəns] n.
finally [ˈfaɪnəli] adv.
worthless [ˈwɜːθləs] adj.
thoroughly [ˈθʌrəli] adv.
trunk [trʌŋk] n.
confident [ˈkɒnfɪdənt] adj.
value [ˈvæljuː] n.

own + a gold mine
a treasure map
in a cave
near/to the seashore
pirate stories
arm sb./sth. with sth. =
sb. be armed with sth.
in dry soil
find / miss + entrance
You're worthless.
I'm not worthless.
car trunk
sb. be confident that ... + 句子
something of value

--------------------
would do VS used to do
where & whose 引导的定语从句

dreams come true...
be used to do sth.
fairly soon ...
I'm fairly certain that +句子
I'm fairly confident that + 句子

** L56 Faster than sound!
sound [saʊnd] n.
excitement [ɪkˈsaɪtmənt] n.
handsome [ˈhænsəm] adj.
Rolls-Royce [ˌrəʊlz ˈrɔɪs]
Benz [benz] n.
wheel [wiːl] n.
explosion [ɪkˈspləʊʒ(ə)n] n.
course [kɔːs] n.
rival [ˈraɪv(ə)l] n.
speed [spiːd] v.
downhill [ˌdaʊnˈhɪl; ˈdaʊnhɪl] adv. adj.

make a sound
hear a sound
on the course
speed it/things/this up
go downhill

--------------------
adj.er
adj.est
more + adj.
the most + adj.

a great deal of ... 不可数
a great many + 可数
break down
a be different form b.

** L57 Can I help you, madam?
madam [ˈmædəm] n
jeans [dʒiːnz] n.
hesitate [ˈhezɪteɪt] v.
serve [sɜːv] v.
scornfully [ˈskɔːnfəli] adv.
punish [ˈpʌnɪʃ] v.
fur [fɜː(r)] n.
eager [ˈiːɡə(r)] adj.

hesitate to do sth.
be eager to do sth.
ask/laugh/look at/ said + scornfully
look down on sb.

--------------------
(in) the way ...

ask to do sth.
be dressed in ...
seek out
make sb. do sth.

** L58 A blessing in disguise?
blessing [ˈblesɪŋ] n.
disguise [dɪsˈɡaɪz] n.
tiny [ˈtaɪni] adj.
possess [pəˈzes] v.
cursed [kɜːst; ˈkɜːsɪd] adj.
increase [ɪnˈkriːs] v.
plant [plɑːnt] v.
church [tʃɜːtʃ] n.
evil [ˈiːv(ə)l] adj.
reputation [ˌrepjuˈteɪʃ(ə)n] n.
claim [kleɪm] v.
victim [ˈvɪktɪm] n.
vicar [ˈvɪkə(r)] n.
source [sɔːs] n.
income [ˈɪnkʌm] n.
trunk [trʌŋk] n.

It is a blessing that ...
what a blessing
God bless you
It's a blessing
a blessing in disguise
In one's possession
Go to church
Go to the church
have a good/bad reputation
Have a reputation for...
baggage claim
source of income/information

--------------------
be said to do...
It is said that...
强调句
被动: 复习L34 & L10

a number of
sb. point out that...

** L59 In or out?
bark v. 狗叫
press v.
paw n. 脚
latch n. 门闩
expert n.
develop v.
habit n.
remove v.

become/be an expert at doing sth./sth.
have a habit of doing sth.
remove sth. from ...

--------------------
so that 目的状语从句

complained of ...
complain that
spend st. doing sth.
train sb. to do sth.

** L60 The future
future n.
fair n. 集市
fortune-teller n.
crystal n.
relation n.
impatiently adv. 不耐烦的

in the future
at a village fair
crystal clear
a relation of yours

--------------------
A先B后
the moment A ... B...
the moment 主将从现

** L61 Trouble with the Hubble
Hubble n.
telescope n. 望远镜
launch v.
space n.
NASA n.
billion n.
faulty adj.
astronaut n.
shuttle
Endeavour n.
robot-arm
grab v.
atmosphere n.
distant adj.
galaxy n.
universe n.
eagle eye

grab a beer/coffee

--------------------
will be doing
will have done
will have been doing

right from the start

** L62 After the fire
control n.
smoke n.
desolate adj.
threaten v.
surrounding adj.
destruction n.
flood n.
authority n.
grass-seed n.
spray v.
quantity n.
root n.
century n.
patch n.
blacken v.

get it under control
be under control
threaten sb. with sth.
threaten to do sth.
have the authority to do sth.
a large/small quantity of sth.
take root
for centuries
a part of sth.

--------------------
have been doing

A short time before
for miles around
in place of...

** L63 She was not amused
circle n.
admire v.
close adj.
wedding n.
reception n.
sort n.

a large circle of friends
admire sb. for sth./doing sth.
close friend
at the reception
what sort of/what kind of...
all sorts of/ all kinds of...

--------------------
as: in the way or manner that

sense of humour/humor
make a speech
a large number of ...
on the way home

** L64 The Channel Tunnel
tunnel n.
port n.
ventilate v.
chimney n.
sea level
double adj.
ventilation n.
fear v.
invasion n.
officially
connect v.
European adj.
continent n.

in the tunnel
above/below sea level
double check
Sb. fear that + 句子

--------------------
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
suggest that ... (should) do ...

it is possible to do sth...
a serve as b
solve the problem of a ...
put forward a plan ...

** L65 Jumbo versus the police
versus prep.
Christmas n.
circus n.
present n.
accompany v.
approach v.
ought modal verb.
weigh v.
fortunate adj.

How much do you weigh?
It is fortunate that + 句子...

--------------------
should do
should have done
ought to do
ought to have done

be dressed up as...
set off
hold up the traffic/line
let sb. off
agreed to do sth.

** L66 Sweet as honey!
Lancaster n.
bomber n.
remote adj.
Pacific n.
damage v.
wreck n.
rediscover v.
aerial adj.
survey n.
rescue v.
package v.
enthusiast n.
restore v.
imagine v.
packing case
colony n.
bee n.
hive n.
preserve v.
beeswax n.

remote control
do a survey
Can you imagine that?
It's hard to imagine.
A colony of bees

--------------------
have something done

over the years
in reasonable condition
be worth doing...
turn a into b.

** L67 Volcanoes
volcano n.
active adj.
Kivu n. Congo n. Kituro n.
erupt v.
violently adv. violent adj.
manage v.
brilliant adj.
liquid adj.
escape v.n.
alive adj.

What a brilliant idea!
That's brilliant!
--------------------
managed to do VS was able to do 成功做成了某事(事例) VS ~ + 过去由能力做成某事

name sth. a.
set up his camp/tent
sb. noticed that + sentence

** L68 Persistent
persistent adj.
avoid v. 
insist v. 
cross v. across prep.

avoid doing sth.
insist on doing sth.
It is no use pretending that + sentence
prevent sb. from doing sth.
Fancy meeting you here.
--------------------
no matter how

enjoy doing sth.
no matter how/what/where
follow sb. around
I was wondering.. + sentence
would you mind my doing...
finish doing sth.

** L69 But not murder
murder /ˈmɜːdə/ n.
instruct /ɪnˈstrʌkt/ v. 
acquire /əˈkwaɪr/ v.
confidence /ˈkɑːn-/ n. confident adj.
examiner /ɪɡˈzæmənə/ n.
suppose v. 
tap v. 
react v.
brake n. pedal n.
mournful adj.

be instructed to do sth.
Let's suppose that...
tap on the window
--------------------
having been done

continue doing/ to do
be pleased with

** L70 Red for danger
bullfight n. ring n.
drunk n.
wander v.
unaware adj.
bull n. matador n.
remark n.v. make that stupid remark
apparently adv.
sensitive adj.
criticism n.
charge v.
clumsily adv.
bow v.
safety n.
sympathetically adv.

be unaware of …
be aware/conscious of …
make that stupid remark
be sensitive about sth. accept criticism
charge at sb. = attack
for your safety
--------------------

be busy with sth.
at the time
catch sight of a.
grow quiet...
get close to a.
step aside
break into cheers
feel sorry for sb.
look on ...
out of the way …
turn sb’s attention to a.
once more

** L71 A famous clock
parliament n.
erect v.
accurate adj.
official n.adj.
Greenwich n.
observatory n.
check v.n.
microphone n.
tower n.

make it official
double check
--------------------

all over the world
burn down
take its name from
be responsible for
be connected to
go wrong

** L72 A car called Bluebird
racing n.
per prep.
Utah n.
horsepower n.
burst v.
average adj.
footstep n.

burst into tears
follow in sb't footsteps
--------------------
have difficulty in doing sth.
be disappointed to learn that

** L73 The record holder
record-holder n.
truant n.
unimaginative adj.
shame n.
hitchhike v.
meantime n.
lorry n.
border n.
evade v.

play truant from school
be put to shame = put sb. to shame
shame on you
hitchhike to sw.
in the meantime
--------------------
over and over again

** L74 Out of the limelight
limelight n.
precaution n.
fan n.
shady adj.
sheriff n.
notice n.v.
sneer n.v.

stay out of the limelight
take precaution
sb. is a big/huge fan of a.
on such short notice
with a sneer/ sneer at sb.
--------------------
a party of
why don't we
carry sth. to sw.
make oneself comfortable
don't be too hard on us 
get out of here

** L75 SOS
thick adj.
signal n.
stamp v.
helicopter n.
scene n.
survivor n.

send a signal
stamp out the fire
arrive on the scene
--------------------
fly off course
cover sb./sth/ with a.
get adj.
It was not long before...

** L76 April Fool's Day
fool n.
bulletin n.
announcer n.
macaroni n.
leading adj. + cause(s)
grower n.
splendid adj. + idea/example/view/garden
stalk n.
gather v. thresh v.
process v.
Signor n.
present adj.
champion n.
studio n.

on the bulletin board
leading cause of
What a splendid/brilliant idea!
--------------------
at the end of ...

** L77 A successful operation
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple [ˈtemp(ə)l] n.庙
mark [mɑrk] n.斑点
plate [pleɪt] n.底片
disease [dɪˈziz] n.疾病
last [læst] v.持续
prove [pruv] v.显示出
resin [ˈrezɪn] n.树脂
skin [skɪn] n.皮,皮肤
section [ˈsekʃ(ə)n] n.切片
figure [ˈfɪɡjər] n.(人的)体形; 人像
normally [ˈnɔrm(ə)li] adv.通常地
survive [sərˈvaɪv] v.幸免于

have a rare disease
a section of ...
prove to be adj.
--------------------
which非限 VS as非限
--------------------
have an operation
died of ...
fall to pieces
cut it open

** L78 The last one
entitle [ɪnˈtaɪt(ə)l] v.以...为名
calm [kɑm] v.使镇静
nerve [nɜrv] n.神经
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer [ˈsʌfər] v.受苦
symptom [ˈsɪmptəm] n.症状
temper [ˈtempər] n.脾气
appetite [ˈæpəˌtaɪt] n.胃口
produce [prəˈdus] v.拿出
urge [ɜrdʒ] v.怂恿
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted [dɪˈlaɪtəd] adj.欣喜的

entitle sb. to do sth.
calm down
keep calm
calm my nerve
have/get the nerve to do sth.: To draw upon one's courage or resolve to do something
lose sb's nerve
lose/break/have sb's concentration
suffer from
have a good/bad temper
lose sb's temper
have/get a good/great appetite
lose sb's appetite
urge sb. to do sth.
give him satisfaction
sb. be delighted that + ...
--------------------
light a cigarette
sb. be sure that + ...
keep on doing sth.
offer sb. sth.
make no effort to do sth.
a packet of...
return to normal...

** L79 By air
parent n.
flight attendant 
frightened adj.
curious adj.
bomb n. plant v.

feel frightened
sb. be curious to find out + ...
plant a bomb
--------------------
Only部分倒装
1. Only(+其他部分)句首,并且不是修饰主语
	 Only police can come in. 不能倒装
2. 主句一般疑问句的语序
--------------------
a great deal
take charge of
be used to doing
take off
gain height
touch down
on board

** L80 The Crystal Palace
palace n.
extraordinary adj.
exhibition n.
iron n.
various adj.
machinery n.
display n.
steam n.
profit n.
college n.

on show/on display
make a profit
go to college
--------------------
be made of
of all time
in all
** L81 escape
prisoner n.
bush n.
rapidly adv.
uniform n.
rifle n.
shoulder n.
march v.
boldly adv.
blaze v.
salute v.
elderly adj.n.
grey adj.
sharp adj. blow n.

grow/change/move... + rapidly
with a sharp blow
--------------------
change into ...
up and down ...
sb. discovered that
stand to attention
knock him to the ground
** L82 Monster or fish?
monster n.
sailor n.
sight v.
creature n.
peculiar adj.
shining adj.
oarfish n.

shining example
--------------------
claim to have done sth.
laugh at ...
it is (well) known that ...
at times
out at sea
in any way
it was found to be ...
a depth of ...
** L83 After the elections
election n.
former adj.
defeat v.
fanatical adj.
opponent n.
radical adj.
progressive adj.
ex- prefix
suspicious adj.

win the election
be fanatical about sth./doing sth.
--------------------
on duty
on the following day
love to do sth.
** L84 On strike
strike n.
busman n. bus driver
state v.
agreement n.
relieve v.
pressure n.
extend  n.
volunteer v.n.
gratitude n.
press n.
object v. objection n.

go on strike
sb. have stated that + ...
agreement is reached about sth.
reach an agreement
sb. be relieved to hear that + ...
relieve pressure
under a lot of pressure
to some extend
volunteer to do sth.
expressed sb.'s gratitude to sb.
sb. have objected that + ...
object to sth./sb.
--------------------
主将从现: 主从都表将来时,从句用现在时即可
	the moment/util/when/as soon as/while/before
will/be going to do
--------------------
be due to do sth.
pass/take the test
** L85 Never too old to learn
inform v.
headmaster n.
contribute v.
gift n.
album n.
patience n.
encouragement n.
farewell n.
honour honor n.
coincidence n.
total n.
devote v.
gardening n.
hobby n.

sb. inform sb. that + ...
make a contribution
contribute to sth.
lose sb's patience
have a lot of patience
give sb. encouragement
in one's honor: it is done specially to show appreciation of them
It is a curious coincidence that + ...
a total of ...
devote oneself to sth./doing sth.
--------------------
mark the occassion
remember sb. for sth.
** L86 Out of control
swing swung v.
speedboat n.
desperately adv.
companion n. 同伴
water ski
buoy n.
dismay n.
tremendous adj.
petrol n.
drift v.
gently adv.

sb. noticed with dismay that + ...
at tremendous speed
--------------------
come away
move in a circle
used up 
before long
** L87 a perfect alibi
alibi n.
commit v.
inspector n.
employer n.
confirm v.
suggest v.
truth n.

have a alibi
commit a murder
sb. confirm that + ...
Are you suggesting + ...
tell the truth
--------------------
on time
** L88 Trapped in a mine
trap v.
surface n.
explosive n.
vibration n.
collapse v.n.
drill v.n.
capsule n.
layer n.
beneath prep.
lower v.adj.
progress v.n.
smoothly adv.

on the surface
in a special capsule
layers of
a layer of
make progress
go/run smoothly
--------------------
lose one's life
As it is...
enable sb. to do sth.
keep in touch with ...
run out of ...
lose heart ...
cause sb./sth/ to do sth.
** L89 A slip of tongue
slip n.
comedy n.
present v.adj.
queue v.n.
dull adj.
artiste n.artist
advertiser n.

a slip of the tongue
a comedy show
hold up the queue
--------------------
do anything to do sth.
the news get around
feel disappointed
at the beginning of a.
burst out laughing
** L90 What's for supper?
chip n.
overfish v.
giant adj.
terrify v.
diver n.
oil rig
wit n.
cage n.
shark n.
whale n.
variety n.
cod n. skate n.
factor n.
crew n.

be scared/frightened out of sb's wits
a variety of
--------------------
it comes as a surprise to learn that + ...
protect a. from b.
in length
the (total) absence of ...
as a result

** L91 Three men in a basket
balloon n.
royal adj.
spy v.
track n.
binoculars n.

spy on sb./sth.
keep track of
--------------------
seem to be doing ...
make for sw.
make out
soon afterwards
be called in (to do)
** L92 Asking for trouble
fast [fæst] adv.
ladder [ˈlædər] n.
shed [ʃed] n.
sarcastic [sɑrˈkæstɪk] adj.
tone [toʊn] n.

fast asleep
Are you being sarcastic?
Don't take that tone with me!
--------------------
hate to do sth.

** L93 A noble gift
noble adj.
monument n.
statue n. liberty n.
present v.
sculptor n.
actual adj.
copper n.
support v.
framework n.
transport v.
site n.
pedestal n.

a noble gift/man
camp site
--------------------
at the entrance of ...
take sth. to pieces

** L94 Future champions
instruct v.
Los Angeles
reluctant adj.
weight n.
underwater adj.
tricycle n.
compete v.
yard n.
gasp v.

be instructed in doing sth.
be reluctant to do sth.
compete against
--------------------
sb./sth. proved that + ...
hold sb's breath
be accustomed to doing
be popular with ...
be lined up
** L95 A fantasy
fantasy n.
ambassador n.
frightful adj.
fire extinguisher
drily adv.
embassy n.
heaven n.
basement n.
definitely adv.
post v.
shot n.

live in a fantasy world
Good heavens!
fire a shot
--------------------
get into such a mess
set sth. on fire
go on doing sth.

** L96 The dead return
festival n.
lantern n.
spectacle n.
moving adj.

make a spectacle of oneself
--------------------
return to sp.
be expected to be
sth. is laid out
it is considered unlucky for sb. doing
be placed into

* NCE3 
** L01 A puma at large
puma n.美洲狮
spot v.n.发现
evidence n.证据
accumulate v.积累
oblige v.使...感到必须
hunt n.v.追猎
blackberry n.黑莓
human being n.人类
corner v.使走投无路
trail n.一串
print n.v.印痕
cling clung clung v.粘
convince v.使...信服
somehow adv.不知怎么搞地
disturb v.令人不安

spot sb. doing sth. 发现某人正在做某事
feel obliged to do sth. 感到必须做某事
a trail of: a series of 一系列
cling to sb./sth. 粘在某人/某物上
sth. convinced sb. that + ... 某事使某人信服...
sb. was/were convinced that + ... 某人确信...
It is disturbing to think that + ... 想到...令人很不安
--------------------
at large: 在逃
be found in: 产于
take sth. seriously: 严肃对待某事
sth. proved adj.: 某事证明怎么样
sb. confirmed that + ...: 某人确定
claim to have done sth. 声称做过某事
find sb. doing sth. 发现某人在做某事
go on: continue

spotted: seen
accumulate: pile up
obliged to: bound to
claimed: stated
extraordinarily similar: surprisingly alike
immediately: at once
convinced: sure

** L02 Thirteen equals one
equal v. equally adv.
vicar n.
raise v. + money
torchlight n. torch n.
cause n.原因,理由 v.导致,引起
wake up with a start
bell n. ring v.
catch sight of a figure: 看到人影
recognize v.
local grocer n.

A. be equal to B.
for one cause or another: for one reason or another
wake up with a start: 惊醒
catch sight of sb./sth.
--------------------
1. be always doing sth.: 频率过高令人生厌(非绝对,用于肯定句)
2. whatever:
	 - emphasize the speaker's surprise/astonishment/anger/irritation/dismay
	 - on earth/ in the world/ fucking
3. do/does/did: 强调v.
4. was/were doing 表礼貌
	 - I was hoping to do sth.
	 - I was just wondering + ...
	 - I was thinking + ...
--------------------
for one cause or another
get enough money to do sth.
sb. be armed with sth.: 装备
what's going on: 发生了什么
recognize A as B
give sb. a surprise
I'm glad that + ...
get used to sth.: 习惯于

** L03 An unknown goddess
goddess n. god
archaeologist n. archaeology n.考古学家
Aegean adj.
explore v. explorer n. exploration n.
promontory n.
prosperous adj.
civilization n.
storey n. story 层
drainage n.
worship n.v.崇拜(神)
sacred adj.神圣的
fragment n.碎片
remains n.遗迹
classical adj.古文化的
reconstruct v. re... 修复
rest n.v. hip n.放置
full-length adj.拖地长的
graceful adj.
identity n.

a is/was used as a place of worship
on a/the promontory: 在海角
drainage system: 下水道
sacred room/template/place: 神圣的房间
have a rest
identity card: 身份证
--------------------
sb. make a (adj.) discovery of sth.
a. be equipped with b.: 配置
equip sb. with sth.
be used as
date from ... date back to ...:追溯
happen to do sth.:  you do it by chance
be amazed to find that + ...
turn out to be sth.: 原来是某物
despite/despite the fact that ...:尽管

** L04 The double life of Alf Bloggs
manual adj. n.
collar n.
sacrifice v. n.
privilege n.
dustman n.
corporation n.
overalls n.
shower n.
secret n.
status n.

do manual work ...
white-collar/blue-collar workers
make a sacrifice:
	to surrender or give up, or permit injury or disadvantage to, for the sake of something else 
sacrifice a. for b.
have the privilege of doing sth.: an opportunity to do something special or enjoyable
take a shower
keep a secret
the secret of success
It's between you and me
social status: 社会地位
status quo: 保持原样
keep the status quo
--------------------
These days ...
Far more adj./n.: 非常...
A. be referred to as ... B.: regrad A. as B.
refer to A. as B.: regrad A. as B.
for the simple reason that + ...
Such is human nature, that + ...
be willing to do sth.
give rise to: lead to; cause
too embarrassed to do sth.
be dressed in: wear
change into + [clothes]
half as much as ...
from now on
call me/him/her a.

** L05 The facts
editor n. edit v.
extreme n.
statistics n. statistic 数据
journalist n.新闻记者
president n.
palace n.
publish v.
fax n.v.
impatient adj.
fire v.
originally adv.

go to extreme(s) to do sth.
publish + a book/an article/report
send sb. a fax
get impatient
get/be fired

--------------------
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until

--------------------
provide sb. with sth.
sb. be instructed to do sth.
instruct sb. to do sth.
write an article on/about sth.
find out sth.: to discover, learn, or verify something
sb. take a long time to do sth.
go to press: 
inform sb. that + ...: 

** L06 Smash-and-grab
smash-and-grab
arcade n.拱廊
jewellery n. jewelry
necklace n. a string of jewels, beads etc or a thin gold or silver chain to wear around the neck
ring n.
background n.
velvet n.天鹅绒
headlight n.车头灯
blare v.to make a very loud unpleasant noise
staff n.
raid n.v. a short attack on a place by soldiers, planes, or ships, intended to cause damage but not take control
scramble v. to climb up, down, or over something quickly and with difficulty, especially using your hands to help you
fantastic adj.
ashtray n. a small dish where you put used cigarettes

smash sth. to pieces
grab a beer/coffee
go to the arcade
background music
scrambled eggs
at a fantastic speed: at a good speed
That's fantastic
--------------------
独立主格
--------------------
only just: Just a moment earlier
come to a stop
be too busy doing sth. to do sth.
[money] + worth of + n.: eg. thousands of pounds worth of diamonds
help oneself to sth.:
	1. to serve or provide oneself with (food, etc.)
	2. to take without asking or being given; steal.

** L07 Mutilated ladies
mutilate v. damage someone’s body, especially by cutting or removing part of it
chew v. chew up  chewing gum
fiance n.
microwave n.
oven n.
safekeeping n.
Newcastle n.
identify v.
spokeswoman n.

chewing gum: 口香糖
for safekeeping: 为了妥善保管
--------------------
deal with
go doing sth.: 去做某事
imagine sb's dismay when + ...
so long as + ..., sb. will do sth.

** L08 A famous monastery
monastery n. St. Bernard
pass n. a high road or path that goes between mountains to the other side
watchdog n.
rashly adv.
enclosure n. an area surrounded by a wall or fence, and used for a particular purpose
monk n. a member of an all-male religious group that lives apart from other people in a monastery
privacy n.  the state of being free from public attention
skier n.
Easter n.

Can I get some privacy?
--------------------
connect a. to b. = a. be connected to b.
for hundreds of years
Now that + ...(原因状从)
be in difficulty: run into serious trouble
attempt to do sth.: try to do sth.
receive a warm/cold welcome

** L09 Flying cats
fascinate v. you are attracted to them and think they are extremely interesting
affectionate adj. showing in a gentle way that you love someone and care about them
mysterious adj.
submissive adj. always willing to obey someone and never disagreeing with them, even if they are unkind to you
feline adj.  relating to cats or other members of the cat family, such as lions
independence n.
high-rise adj. tall
windowsill n. a shelf fixed along the bottom of a window
paratrooper n. a soldier who is trained to jump out of a plane using a parachute
squirrel n.
air-resistance n.
impact n.

gain its independence: it has its own government and is not ruled by any other country
have/make an impact on: 对...有影响
--------------------
the 比较级(eg. more) ..., the 比较级(eg.more) ...: 比较级在句子中做比较成分
yet...: conj.; 表惊讶的转折
--------------------
lead a adj. life: live a adj. life
learn to do sth.
a good deal of/a great deal of un.: VS a lot of; VS a great number of
be based on: to use information to support or prove an opinion or belief
make a study of sth: research
a period of + st.: eg. a period of five months
have sth. in common: eg. have one experience in common
died from(事故) / died of(病)
there is no shortage of sth.:
It seems that + ...
be likely to do sth.: they will very probably do it

** L10 The loss of the Titanic
Southampton
colossal adj.
watertight adj.
compartment n.
flood v.
float v.
tragic adj.
liner n. a large ship for passengers
voyage n.
iceberg n.
lookout n. someone whose duty is to watch carefully for something, especially for danger
collision n.
narrowly adv.
miss v.
slight adj.
tremble v.  to shake slightly in a way that you cannot control, especially because you are upset or frightened
faint adj.
horror n.  to sb's horror  horror movie
abandon v.
plunge v.
lifeboat n.
--------------------
a crew of: eg. ~ workers; ~ painter; ~ waiters
be regarded as + adj./n.
give an alarm: give a warn of danger
in time: not late; punctual.
realized to his horror that: 
give an order

** L11 Not guilty
guilty adj.
tolerant adj.
declare v.
hardened adj. a criminal, police officer etc who has had a lot of experience of things that are shocking and is therefore less affected by them
professional adj. n.
smuggler n.
officious adj.
confidently adv.
dreadful adj. extremely unpleasant
pounce v.to suddenly move forward and attack someone or something, after waiting to attack them
perfume n.
sarcastically adv.
exempt adj.
import duty n.
gel n.胶
mixture n.
unscrew v.
nostril n.
chalk n.small sticks of a white or coloured substance like soft rock, used for writing or drawing
baggage n.

feel guilty
be tolerant of: willing
be exempted from: they do not have to follow it or do it
mixture of a. and b.
--------------------
be made to do sth.: to be forced to do something
on the other hand/on the one hand
light up:  suddenly become animated with liveliness or joy
be greeted by sth.: to welcome someone with particular words or a particular action

** L12 Life on a desert island
desert island
unrealistic adj.
paradise n.
wretched adj. someone who is wretched is very unhappy or ill, and you feel sorry for them
starve v.
element n.
opportunity n.
coral n.珊瑚
Virgin Islands
Miami n.
dinghy n.皮艇
Caribbean n.
spear gun: 鱼叉枪
lobster n.
tanker n.
genuinely adv.

have an opportunity to do sth.: have the privilege of doing sth.
an element of truth/danger: 有点..
starve to death: 饿死
sb. be genuinely sorry that + ...

--------------------
wish that sb. did: 现在虚拟
wish that sb. had done: 过去虚拟

--------------------
formed an unrealistic picture of sth.:对某事有不切实际的想象
imagine sth./sb. to be n./adj.: 把某事想象成
a sort of
wish that + ...
load a. with b.: 用B装载A
As sb. put it: 如某人所说

** L13 It's only me
costume n.
consist v.
sheet n.a large piece of thin cloth that you put on a bed to lie on or lie under
effective adj.
comfortable adj.
storeroom n.
electricity n. meter=metre n. 电表
pace n.
flee fled v. to leave somewhere very quickly, in order to escape from danger
slam v. close

consist of ...:  to be formed or made up of 
make yourself comfortable: to sit, lie, move, or behave in a such a way that you are relaxed and free from pain
at your own pace: you do it at a speed that is comfortable for yo
The pace of life
--------------------
fancy dress party: 化妆舞会
be impatient to do sth.
let out a cry: 大叫一声

** L14 A noble gangster
gangster n.
Chicago n.
protection n.
promptly adv. immediately/on time
destroy v.
remarkable adj.unusual or surprising and therefore deserving attention or praise
band n. a group of musicians, especially a group that plays popular music
Florence n. Florentine n.
city-state n.城邦
hire v. rent
prince n. the son of a king, queen, or prince
funeral n.
dedicate v.献身于
memory n.
valiant adj.very brave, especially in a difficult situation

need protection:
provide protection:
for your own protection: keeping yourself safe from injury or damage
a band of: a group of
give him a state funeral
dedicate yourself/your life to sth.: sacrifice a. for b.; devote oneself to sth./doing sth.
dedicate sth. to sb.: 
devote oneself to sth./doing sth.
in memory of sb. / to the memory of sb.: 
--------------------
when引导的定语从句
	1. 先行词必须为时间(time, day, year...)
	2. when必须在从句中充当[6]的成分.如果从句是[1][3],那么是which引导定语从句,而不是when
	3. 在非书面语中,用that或者直接去掉
	4. 注意区分when时间状语 VS when定语从句
	5. prep.+which=when, 类似的还有方式状语
whenever:
	1. when的强调
	2. every time or any time
if真实条件句和虚拟语气: 过去真实条件句和现在虚拟格式一致,只能结合上下文看.
	If did... , would do...
--------------------
There was a time when + ...
pay money to sb.
large sums of money
put sb. out of business: make (someone) go bankrupt, lose their shop or company
as long ago as: in the distant past
make the remarkable discovery that + ...
would rather do A. than do B.
make a name for himself: to become well-known or famous; rise to fame
come to do sth.: they do it at the end of a long process or period of time
A be known to B as C: B calls A as C
A be known as B:
be at war with ...: eg. China is at war with America.
in times of peace
offer to do sth.
make money
regard A as B: refer to A as B

** L15 Fifty pence worth of trouble
appreciate v.
pocket money: 零花钱
rattle v. if you rattle something, or if it rattles, it shakes and makes a quick series of short sounds
thrifty adj. using money carefully and wisely 
nephew n.
bounce v. it immediately moves up or away from a surface after hitting it
pavement n. sidewalk
stick-stuck-stuck v.卡住
fire brigade n. 消防队
grease n. a thick oily substance that is put on the moving parts of a car, machine etc to make it run or move smoothly 

I appreciate your honesty.
	understanding/interesting/concern/support/patience/trust/time/help/it/that ...
--------------------
supply of sth.: 某物的供给
go a long way: 维持很长时间
be exchanged for sth.  exchange a. for b.
fill up a. with b. 用B充满A
find one's way: reach a destination, especially with some difficulty or not as a matter of course
advise sb. to do sth.
On one's way to sp.
roll up one's sleeves: 卷起某人的袖子
What is more=what's more: 而且
rub a. with b.: 用B擦A
a special type of sth.
hear about sth.
reward sb. with sth.

** L16 Mary had a little lamb
prize adj. very good or important
tie v.
accuse v.
theft n. an act of stealing something
deny v. SAY STH IS NOT TRUE
ashamed adj. feeling very sorry and embarrassed because of something you have done
apologize v.
dye v. to give something a different colour using a dye

prize money
tie sb. to sth. = sb. be tied to sth.: 把某人绑某物上
accuse sb. of doing sth.
deny doing.../sb. deny that + ...
be ashamed of sth./doing sth./having done sth.
apologize to sb. (for doing sth.)
dye something + some-color.: eg. dye his hair red
--------------------
tell sb. about sth.
It's ture that + ..., but + ...
be astonished to find (that) + ...

** L17 The longest suspension bridge in the world
suspension n. suspend v.悬挂,悬职
agreeable adj. situation n.宜人的风景
locate v. location n.坐落
immortal adj. so famous that it will never be forgotten
span n.  a period of time between two dates or events
cable n. a plastic or rubber tube containing wires that carry telephone messages, electronic signals, television pictures etc
concrete n.
length n.长
estimate v.
capacity n.
immensity n.巨大
elegant adj.
faintly adv.轻微地

agreeable/pleasant + situation/man/day
be located in/near
a span of ...: ...的跨度
life span: 寿命
a length of/lengths of + rope/pipe/wire: 一段绳/管/线
It is estimated that + ...
sb. estimates that + ...
--------------------
little/not much/not everything is known about a.: 对A知之甚少
describe a. as b.
in the midst of
by no means: not possible
be considered to be adj./n.
sth. be named after sb.: 某物以某人命名
join a. to b. = connect a. to b.
be taken into account = take sth. into account 考虑某事
a height of ...: ...的高度
A. be suspended from B.: A悬挂于B
be packed with ...: to fill something with things or people of a particular type
a third of sth: 某物的1/3
fulfill sb's dream: something or someone made your dream come true

** L18 Electric current in modern art
current n.  electric current 电流
sculpture n. an object made out of stone, wood, clay etc by an artist
mistaken adj.
gallery n. a large building where people can see famous pieces of art
exhibit n.v. exhibition n. to show something in a public place so that people can go to see it
oddly adv. in a strange or unusual way
attach v. to fasten or connect one object to another 
sphere n. a ball shape
magnetize v.
repel v.
flicker v. to burn or shine with an unsteady light that goes on and off quickly
emit v. to send out gas, heat, light, sound etc
flash v.
prehistoric adj.
electronic adj.
peculiar adj. strange, unfamiliar, or a little surprising
shock v.n.震惊
emotionally adv. relating to your feelings or how you control them

make a sculpture / create a sculpture: 制作雕塑
be mistaken about sth./sb.: confused or wrong about
Oddly enough, + ...: Strangely, unexpectedly 
be attached to sb./sth. = attach a. to b.: 把A绑到B上
get an electric shock: 被电击
receive an electric shock
give you electric shocks
--------------------
not any more = not any longer = no longer
The idea that + ... is mistaken: 想法xx是错的
take no/ a great/an interest in
in response to sth.: 回应某事
be/sound/look/seem familiar to sb.: 对某人看起来很熟悉
go mad
on and off: 断断续续
It was rather like ...: 这很像...
seem adj.(designed) to do sth.: be designed to do sth.
be designed to do sth.: seem designed to do sth.

** L19 A very dear cat
dear adj.
kidnapper n.绑架者
considerable adj.
wealthy adj. having a lot of money, possessions etc
orderly adj. arranged or organized in a sensible or neat way
disappearance n. disappear v. 出现
anonymous adj. unknown by name
ransom n.
cardboard n. stiff thick brown paper, used especially for making boxes
withdraw withdrew withdrawn
punctually adv. on time
astound v. astounded adj.

be dear to somebody: 对某人很宝贵
a considerable amount/number of sth.: a lot of
in an orderly fashion/manner: in a well-organized and controlled way
anonymous letter/(phone) call
remain anonymous: 匿名
a ransom of + (money): eg. a ransom of $100
It astounded sb. that + ...
--------------------
share sth. with sb.
take a short/long walk
get worried
in safe hands: they are being looked after by a reliable person and will not be harmed
at first: 一开始
go to the police
make sth. clear: 把某事搞的很清楚
change sb's mind: 改变主意
follow sb's instructions: 遵从某人的指示
keep sb's word: 说话算数
sure enough: 当然了
sb. explained that + ...
Considering + n., + ...: 考虑到
in more ways than one: to have more than one meaning

** L20 Pioneer pilots
pioneer n. someone who is important in the early development of something, and whose work or ideas are later developed by other people
lord n. a man who has a rank in the aristocracy
Calais n.
overland adj. adv.across land, not by sea or air
--------------------
as if/though 虚拟语气

--------------------
offer sth. to sb. = offer sb. sth.: provide sth. for sb.; provide sb. with sth.
a prize of + (money): eg. a prize of $1,000
make an attempt to do sth.: attempt to do sth; try to do sth.
attempt to do sth.
be forced to do sth.: be made to do sth.
be picked up by ...: be rescued by
on the same day: 
It looked as if/though + 虚拟句:
	eg.	It looked as if there would be an exciting race across the Channel.
	eg.	It looked as though there would be an exciting race across the Channel.

** L21 Daniel Mendoza
boxing n.
boxer n.
bare adj. not covered with clothes
prizefighter n.
crude adj. rude and offensive
marquis n. has a rank between duke and earl
technically adv.
science n.
popularity n.
adore v. to love someone very much and feel very proud of them
alike adv. in a similar way  adj. very similar not before noun
fame n.
eminent adj. an eminent person is famous, important, and respected
bitterly adv. very
bet bet betted v. to risk money on the result of a race, game, competition, or other future event
academy n.
extravagant adj. spending or costing a lot of money, especially more than is necessary or more than you can afford
poverty n.

with sb's bare hands: using only one's hands and no tools or weapons
Technically speaking, + ...: According to the rules
gain/grow/increase in popularity:  something or someone is liked, enjoyed, or supported
great minds think alike: 英雄所见略同
rise to fame: make a name for oneself
quarrel/complain/be disappointed ... + bitterly:
bet ($) on sth.: 在某事打赌多少钱
I bet + ...: 我赌 + ...
live in poverty: 生活贫困
--------------------
Because of + n.
be born in + (year): 出生于
draw up: 起草
a set of sth.: a series of; a trail of
change a. into b.: 把A变成B,而 exchange A for B.是交换
bring a. to b.: eg. brought science to the game
in sb's day: 在他的时代
be quick to do sth.: 很快做某事
in fact
turn against sb.: 与某人反目
It is clear that + ...: 很明显
settle the argument: 解决争端
It was not until [stp.] that + ...:
	stp. can not only be 'in 1790' but also 'third match' as well
as much as ...   half as much as: 一样多,一半多
be in debt: owe money

** L22 by heart
run ran run v.
lines n.台词
part n. role n.角色
falter v.支吾,结巴说
cast cast cast v. to choose which people will act particular parts in a play, film etc 
aristocrat n.someone who belongs to the highest social class
imprison v. to put someone in prison or to keep them somewhere and prevent them from leaving
Bastille n.
jailer n.
colleague n.someone you work with – used especially by professional people
curtain n. a piece of hanging cloth that can be pulled across to cover a window, divide a room etc
reveal v.
cell n. a small room in a prison or police station where prisoners are kept
blank adj.
squint v. to look at something with your eyes partly closed in order to see better
dim adj.
sire n.
proceed v.

play the role of: 扮演...的角色
sb. be cast in the role of = cast sb. in the role of: 委派某人演...角色
the curtain goes up/rises/comes down/falls: 窗帘上/下
a blank sheet of paper: 一张白纸
squinte at sb./sth.: 眯眼看某人/某物
in the dim light: 在昏暗的光线下
proceed to do sth.: 继续做某事
--------------------
insist/suggest that + ... (should) do (虚拟语气)

--------------------
for days/hours/years on end: 一连好几天/小时/年
in many ways: to a great degree
be required to do sth.: be ordered to do sth.
expect sb. to do sth./ sb. be expected to do sth.: want sb. to do sth.
learn/know sth. by heart: to have learned or memorized something completely and perfectly
have cause to do sth.: have a reason to do sth.
sb. insisted that + ...(should) do (虚拟语气) 要求
sb. insisted that + ...(非虚拟) 认为
be written out in full: 被写的满满当当
play a joke on sb.: to confuse someone or cause problem for them
present sth. to sb.: provide sth. for sb.
look on: 旁观(看热闹)
at last
be anxious to do sth. = be eager to do sth. = can't help doing sth.
stare at: 盯着
read sth. to sb.
much to sb's sth.[surprise/amusement/dismay/disappoint]: 使某人...

** L23 One man's meat is another's poison
illogical adj.
octopus n. a sea creature with eight tentacles (=arms)
delicacy n. something good to eat that is expensive or rare
repulsive adj. extremely unpleasant, in a way that almost makes you feel sick 
stomach n. turn v.
fry v. to cook something in hot fat or oil, or to be cooked in hot fat or oil
fat n.
abuse n.
snail n.
associate v.
luxury n.
despise v. to dislike and have a low opinion of someone or something
appeal v.
shower n.
stroll n.
impulse n. a sudden strong desire to do something without thinking about whether it is a sensible thing to do
dozen n.  twelve
fancy v. to like or want something, or want to do something 

One man's meat is another man's poison: 萝卜青菜,各有所爱
it is illogical to do sth.: 做某事不和逻辑
turn sb's stomach: 真的反胃
sick to my stomach: feeling very disgusted or angry.
animal fat
a. received more abuse than b.: a比b受到更多争议
associate a. with b.: connect a. to b.
appeal to sb.:  to attract, please, or interest
After a heavy shower ...: 下大雨后
be in the shower: 淋雨
take a shower: to wash oneself in the shower
take a stroll / go for a stroll: take a short walk
have the impulse to do sth.:
	a sudden strong wish or need to do something, without stopping to think about the results
dozens of sth./sb.: 几十个
--------------------
for instance: for example
at the idea of ...: 一想起
The sad truth is that + ...: 悲伤的事实是
be brought up to do sth.: 从小一直做某事
stick to sth.: continue doing or using (something) especially when it is difficult to do so
notice sb. doing sth.
be delighted to do sth.: be willing to do sth.; be ready to do sth.
stay to dinner = stay for dinner: 留下来吃晚餐
to sb's dismay: disappointment
take possession of sp.: occupy sp.

** L24 A skeleton in the cupboard
skeleton n. the structure consisting of all the bones in a human or animal body
seemingly adv. apparently 似乎,好像
respectable adj. someone who is respectable behaves in a way that is considered socially acceptable
conceal v.
vivid adj. vividly adv.
dramatic adj. drama n. dramatically adv.  great and sudden
ruin v.
heroine n. hero
fiction n. books and stories about imaginary people and events
varying adj. different
medicine n.医学
guest room n.客房
unpack v.
stack v. to make things into a neat pile, or to form a neat pile
underclothes n. = underwear
drawer n.
petrify v. extremely frightened, especially so frightened that you cannot move or think
dangle v. to hang or swing loosely, or to make something do this
sway v. to move slowly from one side to another
unsympathetic adj.
medical adj.

a skeleton in the cupboard/closet: they are keeping secret a bad or embarrassing fact about themselves
sth. be concealed from sb. = conceal sth. from sb.
drama queen: 戏精
ruin my day
science fiction
to varying degrees: 多种程度上
in the drawer/ from the drawer: 在抽屉
be petrified of sth.: 被某物惊呆
medical student/school
--------------------
It is all very well (and good)..., but not in reality + ...
make one's hair stand on end: 使某人汗毛耸立
in sb's youth
show sb. to sp.: 带某人去某地
bring sth. with sb.: 随身携带某物
it give sb. the impression that + ...
be about to do sth.: 要做某事
leap out at sb.: 扑向某人
once upon a time: 曾经

** L25 The Cutty Sark
impressive adj. makes you admire it because it is very good, large, important etc
steamship n.
vessel n. a ship or large boat
era n.时代
Java n.
rudder n. a flat part at the back of a ship or aircraft that can be turned in order to control the direction in which it moves
roll v.滚动
steer v. to control the direction a vehicle is going, for example by turning a wheel
temporary adj.
plank n.木板
fit v.安装
equator n.赤道
delay n.延误

a new era/ the beginning/end of an era
a. be fitted with b. A被装上了B
delay in doing sth.
--------------------
a. be replaced by b.
take the lead (in doing sth.) lose one's lead: 领先做某事 失去领先
be struck by: to be very impressed by 
from side to side: moving to the left and then to the righ
it become impossible to do sth.
with great difficulty
There is a danger that + ...: 有...的危险
call in on/at: visit
by now: 目前为止
There is no doubt that + ...: 毫无疑问

** L26 Wanted: a large biscuit tin
influence v.n.
pride v.
taste n.v.品味
exert v.施加
subtle adj.微妙的
advertiser n.
classify v. to decide what group something belongs to 
magic adj.
sample n.
devise v.设计
capture v.吸引,赢得
manufacturer n.
wheelbarrow n. a small cart with one wheel and two handles that you use outdoors to carry things, especially in the garden
boot n.
ingredient n.食材,成分
crane n.  a large tall machine used by builders for lifting heavy things 
anticipate v. to expect that something will happen and be ready for it

bad/good/positive etc. influence (on sb.)
have an influence on sb./sth.
be influenced by ...
pride oneself on (doing) sth. = be pround of
have good/bad taste in sth. 对某物有好的品味
exert a subtle/some influence on/over sb. 在某人上施加微妙的影响
have a subtle mind: 拥有敏锐的思想
classify a. as/under b.: 把A归类为B
say the magic word
free samples of sth.: 某物的免费的样品
devise a way/plan to do sth.:设计出方法/计划去做某事
capture the attention of sb. = capture sb's attention
in the boot of sb's car: 在车的后备箱
It is anticipated that + ...: 据估计
sb. anticipate that + ...: 某人预估
--------------------
as引导的倒装句 表 让步
	- Much as ..., ...
	- adj./n./v. + as ...,句子: adj-est.去the, n.去冠, v.用原型
	- 为什么要试试自己查语法书
--------------------
avoid being done: 避免被做某事
be free to do sth.: 免于做某事
in sb's effort to do sth.: 在某人努力做某事下
get sth. for nothing: 免费得到东西
enable sb. to do sth.
a. has made it possible for sb. to do sth.
come along: arrive
buy sth. from sb.

** L27 Nothing to sell and nothing to buy
philosopher n.
wisdom n.
priest n. vicar 神父
spiritual adj.
grudge v.n. a feeling of dislike for someone because you cannot forget that they harmed you in the past
surgeon n. a doctor who does operations in a hospital
passer-by n. passers-by
dignity n.尊严
deliberately adv.
consequence n.
afflict v.折磨
ease n. easy to do it
nature n.
contempt n.轻蔑
envious adj. wanting something that someone else has

question/doubt the wisdom of (doing) sth.
give sb. spiritual comfort
grudge doing sth.: 不愿意做某事
have/hold a grudge against sb.: 对某人怀恨在心
die/treat/do sth. with dignity: 有尊严地xx
have consequences
be afflicted with/by sth.: 被某事折磨
with great/considerable ease
love of nature: 热爱大自然
speak of/treat sb./sth. with contempt: 轻蔑对待/谈起某人
be/feel/get/become envious of sb.
--------------------
live by doing sth.: 以做某事为生
in the light of sth./in light of: 鉴于某事
in terms of sth.: 从某物来说
It is difficult to do sth.
seem to be/do sth.
be the exception to the rule: 规则的例外情况
in doing sth.: 结果是
choose to do sth.
be free from sth.: 摆脱某事
in the open (air): 露天

** L28 Five pounds too dear
wares n. silverware n.器物  银器
anchor v.n.
deck n.
tempt v.鼓动
bargain v.n.讨价还价
disembark v. to get off a ship
assail v.骚扰
marble n.大理石
inscribe v.雕刻
favour n. favor 优惠
gesticulate v.做手势
outrageous adj.不公的
thrust v.猛塞

on the deck
tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.
bargain with sb.
make a bargain with ...
be assailed by sb.
A. be inscribed on B. A被雕刻在B上
as a special/personal favor (to sb.): 作为对某人的特殊优惠
do me a favor: 帮我个忙
it is outrageous (that) + ...: xx使非常不公的
thrust sth. into sw. (especially my hands): 猛塞某物在某处 
--------------------
speed to sp.
sb. have no intention of doing sth.
I can't conceal the fact that + ...
sb. be impressed by sth.
go to great lengths to do sth.: 努力做某事
prove that + ...
go to great lengths to prove that + ...: 努力证明
get rid of sb.: 摆脱某人
at the base of sth.: 在...的基础上
let me have it: 给我吧
indicate that + ...: 表示...
reduce the price to $: 减少价格到...
throw up one's arms: 举起胳膊
get back to sp.: 回到某地
fill a. with b.: 用B充满A
to this day: 直到今天 by now

** L29 Funny or not?
largely adv.很大程度上
comic adj.n.漫画
universal adj.普遍的
comedian n.喜剧演员
distasteful adj.讨厌的
pester v.纠缠
dread v.惧怕
recovery n.康复
plaster n.熟石膏
console v.安慰
hobble v.瘸着腿走
compensate v.补偿
mumble v.喃喃自语

comic book/movie/novel
have a universal appeal: 有通用的吸引力
pester sb. to do sth.
dread doing sth. 惧怕做某事
dread sb. doing sth.
make a complete/quick/speedy/slow recovery: xx恢复
console sb./yourself that + ... 安慰某人道 + ...
compensate (for sth.) = make up for: 补偿
--------------------
whether/whether or not .../whether...or not 主从 VS 让步状语
	1. 主从Whether引导, 不可被if代替, 在句中做1的成分
	2. whether引导让步状语从句, 在句子中状语的成分
have: stay 原则:万能+猜
--------------------
be bound up with: 与...密切相关
find it hard to do sth.
make sb. laugh to tears: 使某人笑出眼泪
stem from ...: 源于
come into fashion
base a. on b.: 建立A.在B.上
judge for yourself: 自己判断
do one's best (to do sth.): try my best to do sth.
take heart: 获得鼓舞
be good for sb.
in the process: 在过程中

** L30 The death of a ghost
labourer n. laborer
overnight adv.
hay n.
corn n.谷物
moonlight n.
conscientious adj.认真的
suspect v.
desert v.开小差
regiment n.团(军队)
action n.战斗
recluse n.隐士

stay overnight in the hay: to sleep somewhere for one night
in the moonlight
suspect (that) + ...
a regiment of ...: 一团/群...
be killed in action: 战斗中牺牲
--------------------
every time: 时间状语 = whenever
wake up to find that + ...
old elder eldest: 只能sb.,不能接sth.,也不能接than
	older oldest: 既能sb.,也能sth.
--------------------
for years
stay up
it became an accepted fact that + ...
be supposed to be/do sth.
remain in doing: proceed to do sth.
none other than: 不是其他人是
think it one's duty to do sth.
keep sb. in hiding: 藏起某人
find it impossible to do sth.

** L31 A lovable eccentric
lovable adj.
eccentric n.
disregard v. to ignore something or treat it as unimportant
convention n.习俗,风俗
conscious adj. aware 感觉到的
invariably adv.总是
routine n.常规;惯例
shrewd adj.精明的
eccentricity n.怪癖
legendary adj.传奇般的
snob n.势力小人
intensely adv.强烈地
bedraggled adj.拖泥带水的
dump v.把...砰的抛下
apologetic adj.道歉的
reprimand v.训斥
stage v.n.暗中策划
elaborate adj.精心构思的

disregard social conventions
be conscious of (doing) sth.
sb. be conscious that + ...
daily routine
dump sth. on sth.
be apologetic about/for sth.
reprimand sb. for (doing) sth.
elaborate plan/design/meal
--------------------
draw attention to sb.
win sb. sth.: 赢得某人某物
add a. to b.
up to the time of sth.: 到...的时候
go on foot
be caught in: 淋雨
sb. request to do sth.
present sb. with sth.
invite sb. to do sth.

** L32 A lost ship
salvage v.n. 救助;打捞
Barents n.
sunken adj.沉没的
cargo n.一车/船货物
bullion n. un. bars of gold or silver
scour v. 搜寻
chest n.
contents n.
belongings n. 所有物
item n.
cruiser n.巡洋舰
find n. thing
log book: 日志本
piece v. 拼成整体
convoy n. 护航
torpedo v. n. 用鱼雷攻击
submarine n. 潜水艇
naval adj. navy n.海军的
ministry n. (政府的)部
--------------------
salvage operation
a cargo of: 一货...
piece together: 拼装起来
in a convoy: 在护航中
a naval officer: 
--------------------
sb. be under the impression that + ...
together with: 除了...还有
come to light: 披露出来

** L33 A day to remember
prelude n. 前奏
unforeseen adj.意料之外的
series n.系列
catastrophe n.大灾
crockery un.陶器
suburb n.郊区
collide v.猛撞
learner n.初学者
panic n.
windscreen n. windshield 挡风玻璃
alongside prep. adv.在...的旁边
slide slid slid v.滑
stray adj. 迷失的,离群的
confusion n. 混乱
greedily adv. devour v. 狼吞虎咽地吃

a prelude to sth.
unforeseen + changes/problems/circumstances: 不可预见的改变/问题/情形
a series of
be a catastrophe for sb.: 对某人来说大灾祸
in the suburbs/ a suburb of city: 在城区的郊区
collide with=run into: 碰撞
get into a panic
draw up alongside sb.: 超车某人
slide off/open: 滑走/开
stray dogs: 流浪狗
There is some confusion about sth.
--------------------
get out of control
What invariably happens is that + ...
set up a chain of reactions
keep an eye on sb.: 留意某人
be/speak/talk on the phone: 在打电话
hang up (on sb.): 挂电话
attend to sb./sth.: 照料某人
reduce sb. to tears:  they make you feel so unhappy that you cry
on a big/large/small scale: 大规模地
drawing up alongside sb.: 超车某人
rush hour: 高峰期
pull up: 停车 (of a vehicle) come to a halt.
all of a sudden = suddenly
pile up: accumulate
get the traffic on the move: 使得交通动起来
sweep up: 打扫干净
benefit from sth.: 得益于某事

** L34 A happy discovery
antique n.
fascination n.
forbidding adj.
muster v.
pretentious adj.
labyrinth n.
musty adj.
rarity n.
assorted adj.
junk n.
litter v.
dedicated adj.
bargain hunter
dealer v.
cherish v.
amply adv.
masterpiece n.
mere adj.
prise v.
carve v.
dagger n.
miniature adj.
composition n.

antique shop/store/desk/jewelry
hold/have a fascination for sb./sth.
forbidding place/look
muster (up) the courage/confidence/to do sth.
in the labyrinth of sth.
junk mail
be littered with sth.
sb. cherish the hope that + ...
The mere fact that + ... + 23456
prise sth. open
carve a. from/out of b.=a. be carved from/out of b.
--------------------
There is always hope that + ...
by chance
above all
be bent on doing sth.
sb. cherish the hope that + ...
described to sb. what/how + 宾从 = describe sth. to sb.
pick up
sb. can't/couldn't be bothered to do sth.
beg sb. to do sth.
at the bottom of ...

** L35 Justice was done
justice n.
court n. law n.
innocence n.
undertake v.承担;着手做
arduous adj.艰苦的
abstract adj. concept n.
mete out 给予,处置
interference n.干涉
accord n.一致
premises n.房屋
convert v.转变
disused adj.废弃的
fireplace n.壁炉
muffle v.捂住
chip v.砍
blacken v.使变黑
emerge v.(从某处)出现

justice has been done/served: 正义得到伸张
court of law; courts of law: 法庭
prove sb's innocence
undertake a task/a project/research/a study/a journey: 承担重任
arduous task of doing sth./arduous journey: 做某事的重任
go through/embark on/begin arduous journey: 开始艰辛的旅程
understand + abstract concept
interference in sth.: 对某事的干涉
Sorry for the interference, + ...
I hope you don't mind the interference, but + ...
of sb's/sth's own accord: you do it because you want to, without being asked or forced
on the premises of a.: 在A的前提下
convert a. to/into b.: 把A变成B
emerge from sp.: 从某处出现
--------------------
however = no matter how 让步状语
get + done 被动
--------------------
beyond doubt
make mistakes
There are rare instances when + ...: 有极少例子当...
cease to do: 不再去做
be independent of: 独立于
in part: 部分地
run to tell sb.: 
ring up: call sb. by phone
tap at sth.: 敲击某物
listen for ...: 为...而听
be unable to do sth.
break into sp.: 破门而入
be handed over to sb.: 被移交给

** L36 A chance in a million
credulous adj. 轻信的
improbable adj. 不大可能的
obscure adj. 不起眼的
maidservant n. 女仆
presume v. 假定
wickedly adv. 心眼坏地
plot v. 密谋
downfall n. 倒台
naive adj. 天真的
unacceptable adj.不能接受的
conspire v.巧合促成
incredible adj.难以置信的
resemblance n.相似
scorn n.嘲弄
acquint v.使了解
reunite v.使囤聚
assume v.假定,认为

It seems (highly/wildly) improbable that + ... 似乎不可能
be presumed dead/innocent/guilty 假定死亡/无辜/有罪
presume that + ... 假定...
plot to do sth. 密谋做某事
plot against sb. 暗算某人
lead to sb's downfall 导致某人的垮台
bring about sb's downfall 使某人垮台
it be naive enough to believe/think + ...
sb. be naive enough to believe/think + ...
it be unacceptable to do sth.
conspire to do sth.: 合谋做某事
it is incredible (to sb.) that + ...: 难以置信的
it is incredible how + ...
it is incredible to do sth.
bear a close/strong/striking resemblance to sb./sth.: 对某人/物非常相似
bear little/no resemblance to sb./sth. 对某人/物不相似
resemblance to ... 对...的相似
pour scorn on: 嘲笑
pour scorn on the idea/suggestion/plan/advice
acquaint sb. with sth.: 使某人熟悉某事物
sb. be acquainted with sth. 某人熟悉了某物
be reunited with sb. 和某人团聚
assuming that + ... 假设...
it seems/is reasonable to assume that + ... 假设...是合理的
--------------------
to do 非谓语结构
--------------------
a chance in a million 百万分之一
bring ... to a conclusion: 把...结束
sb. accepted the fact that: 某人接受事实...
bring about sth.: 引起某事
and so on: 等等
anyone but: 所有人除了...
be thought to: 被认为...
stop to do:停下来去做某事 VS stop doing sth: 停下来做的事情
comment on sth./sb.: 评论...
suggest that + ...: 建议虚拟语气; 假设不用虚拟语气
there is/was a chance that + ...: ...有可能
needless to say: 不用说
towards the end of + sth.: 接近...的结尾
be separated from: 与...分离
make one's way back to sp.: 回某地
return to: 回去
What become of: 怎么了

** L37 The Westhaven Express
express n.快车 adj.高速的
punctual adj. punctually adv.准时的
condition v.使习惯于
unshakable adj.不可动摇的
faith n.信任
cancel v.取消
exceptionally adv.例外地
dislocate v.打乱(计划等)
blame v.责怪
consult v.请教,查阅
direct adv.径直地
odd adj.奇怪的
reflect v.细想
advantage n.优势
mighty adj.强大的,有力的
dawdle v.慢吞吞地动或做
chug v.喀嚓喀嚓地响
lodge v.提出
complaint n.抱怨
triumph n.胜利
asterisk n.星号
conduct v.引向

be punctual for: 准时
condition sb. to (do) sth.: 训练某人做某事 
sb. be conditioned to do sth.: 某人(被训练)习惯于做某事
develop an unshakable belief/faith in sb./sth.: 对某人/某事有不可动摇的信心
have/lose faith in sb./sth.: 对某人/某事有信心
blame sb. for sth.: 怪某人某事
blame sth. on sb.: 怪某人某事
consult the map/manual/dictionary: 查地图/手册/字典
go/fly direct: 直接去
It is/seems odd that + ...: 似乎很奇怪
reflect that + ...:
reflect on sth.: 思考某事
lodge a complaint: 投诉
have/make/receive/lodge a complaint: 投诉
a note of triumph: 胜利的音符
conduct sb. to sp.: 引导某人注意某处
--------------------
neither + 部分倒装
not... but ... 不是... 而是...
--------------------
It is all too easy to do sth.: 很容易做某事
sb. noted with satisfaction that + ...: 某人满意的发现
can't help doing sth.: 忍不住做某事
strike sb as sth./sb.: 使某人想起某人某物
take advantage of sth./sb.: 利用
wish to do sth.: 期望做某事
hold up: 堵住
It dawned on me that + ...: 我突然想到
roar down: 呼啸而下
not do sth. but + ...: 不但做某事,而且...
hear of: 听说
copy of sth.:	一本...
in black and white
at the bottom of sth.: 在某物的底部 
