#+OPTIONS: \n:t num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* TED-ED
** 2013-10-01 The uncertain location of electrons
particle: a very small piece of something 
proton: a very small piece of matter with a positive electrical charge that is in the central part of an atom
neutral: not supporting any of the people or groups involved in an argument or disagreement
nucleus: nuclei(复数) 原子核
indulge: to let yourself do or have something that you enjoy
orbitals /ˈɔːbɪtl/: ring road 轨道
density: the degree to which an area is filled with people or things密度
quirk: a strange habit or feature of someone’s character, or a strange feature of something怪异
exponentially /ˌekspəˈnenʃəl/: 指数地
--------------------	
in a momentary tangent: to suddenly start talking or thinking about a completely new subject
develop a model for sth.: 
agree with the model: 
it might be time for sth./ to do sth.: 
there will be many more to do sth.: 
tend to do sth.: 
stick together: 团结在一起
behave as/like sth.: 表现得像
perform experiment: 
It's (not) that + ..., it's that + ..: 
there's a certain probability of doing sth.: 
be 95% sure of doing: 
more or less:
decrease/increase exponentially:
approach zero: 
hit zero:
there is some small, but non-zero, probability that + ..:
for a very, very short period of time: 
interact with:
surrender A. to B.: to give up something or someone, especially because you are forced to
** 2013-10-03 Why extremophiles bode well for life beyond Earth
(in) outer space:
abduction by sb.: 
in the universe: 
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose得到
form life: 形成生命
ancient religions: 
be inhabited by sb.: 
sth. be more like A. than B.: 
mythical realms: 神话王国
parallel universes: 
It is only within the last century that + ...: 
undertake sth./ to do sth.: 
A. is just the right distance from B.: 
support life: 
sth. is fatal for sb.: resulting in someone’s death
in the dark depths of oceans/lakes/rivers: 
on the flanks of volcanoes: the side of a hill, mountain, or very large building
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things 
What is most remarkable about sth. is that + ...: 
hit the surface of sth.: 
be flowing with: to have some liquid coursing on the surface or within someone or something
be composed of sth.: 
be the basic building block of sth.: 成为某事物的基本组成部分
** 2013-10-08 The operating system of life
oak: 橡树, 橡木
acorn: the nut of the ↑oak tree
tadpole: a small creature that has a long tail, lives in water, and grows into a frog or toad
mold: a soft green, grey, or black substance that grows on food which has been kept too long, and on objects that are in warm wet air ⇨ mouldy:霉菌 
solitary: used to emphasize that there is only one of something SYN single 
organism: an animal, plant, human, or any other living thing有机体
lifeform: 生物
machinery: 机器, 机械
mission: 使命, 任务
currency: the system or type of money that a country uses
blueprint: technical a pattern that all living cells contain, which decides how a person, animal, or plant develops and what it looks like蓝图
photocopy: 影印
block: 块
giant: extremely big, and much bigger than other things of the stype
furnace: a large container for a very hot fire, used to produce power, heat, or liquid metal
fuel: a substance such as coal, gas, or oil that can be burned to produce heat or energy燃料
scrap: to get rid of an old machine, vehicle etc, and use its parts in some other way拆毁
specialized: 专门的, 专科的
portal: 入口
deoxyribonucleic acid: DNA
protein: 蛋白质
amino: ['æminәu]氨基的
acid: a chemical substance that has a ↑pH of less than 7. Strong acids can burn holes in material or damage your skin
mineral: 矿物, 矿石
lipid: 脂质, 油脂[脂肪,乳酪]
a.k.a.: also known as, 又名..., 也叫作...
membrane: 膜, 隔膜
interaction: 交互作用, 交感
crucial: something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
oxygen: 氧
phosphate: 磷酸盐
molecular: 
tote: informal to carry something, especially regularly手提, 背负, 携带
biochemistry: 生物化学
excess: a larger amount of something than is allowed or needed超额
glycogen: ['glaikәudʒen]肝糖, 糖原质
bacteria: very small living things, some of which cause illness or disease ⇨ virus细菌
--------------------
in the back of your fridge: 冰箱深处
sb. is a gleam in sb's eyes: A是B的构想
share the same basic goal: 拥有相同的基本目标
perpetuate sb's existence: 使某人永久存在
stay alive: 设法不死
set up a factory: 开办工厂
keep sb. doing sth.: 使某人做某事
assembly instructions: 装配说明
raw materials: 原材料
get paid: 获得报酬
send sth. off: to send a letter, document, or package by mail
assemble A. into B.: 将A组装成B
be transported to sp.: 被运送到某地
draw energy from sth.: 从某物那里获取能量
harsher working conditions: 艰苦的工作环境
be walled off: 被隔离起来
the rest of sth.: 某物剩余部分
be embedded into sth.: 被嵌入到某物
be built from sth.: 由某物建造
are derived from: to come or develop from something 来源于
in a pinch: in an emergency
minimum wage: 最低薪酬
be transferred between: to move someone or something from one place, vehicle, person, or group to another
in the face of sth.: 面对某事物
extreme challenges: 极限挑战
mobilize the immune system: 激起防御系统
** 2013-10-08 What is the shape of a molecule
molecule: 分子
mass: a large amount or quantity of something
nuclei: 
discrete: clearly separate
sausages: a small tube of skin filled with a mixture of meat, spices etc 
formula: a series of numbers or letters that represent a mathematical or scientific rule: 
favorable: suitable and likely to make something happen or succeed: 
--------------------
be concentrated in: 集中于
be bonded to: 与……紧密相连
there's at least one way to do sth.: 
maximize/minimize the attraction/repulsion of: 
A. matter to B.: A对B重要
A. be the outermost one(s) from B.: A是B最远的部分
in between sth.: 在...之间
be kind of like sth.: 
be bunched up together: 被聚拢在一起
fly apart: 四分五裂,飞离
doesn't help anyone: 一点帮助都没有
decades before: 数年前
be arranged in 3D space: 在3维是如何被安排
bond with sth./sb.: 与他人建立紧密联系
draw sth. as a line: 把某物画成一条线
have a flat representation of sth.: 有某物的平面图
in three dimensions: 
get A. far away from B.: 
expand on our model of sth. to do sth.: 详述xx的模型去做某事
Spoiler alert: 剧透

** 2013-10-17 How we conquered the deadly smallpox virus
marrow: the soft fatty substance in the hollow centre of bones 
spleen: an organ near your stomach that controls the quality of your blood 脾脏
lymph nodes: 淋巴结
vomiting: to bring food or drink up from your stomach out through your mouth, because you are ill 
scar: 疤痕
scab: 痂
epidemic: a large number of cases of a disease that happen at the same time
insidiously: an insidious change or problem spreads gradually without being noticed, and causes serious harm 
merchant: someone whose job is to buy and sell things
Buddhist: 佛教徒
nun: someone who is a member of a group of religious women that live together
providence: 深谋远虑, 天意, 上帝, 神的眷顾
variolation: 天花接种
sore: a part of your body that is sore is painful
inoculate: to protect someone against a disease by putting a weak form of the disease into their body using a needle 
foolproof: a foolproof method, plan, system etc is certain to be successful
dairy: dairy products/produce milk, butter, cheese etc
apothecary: someone who mixed and sold medicines in the past
pockmarked:covered with hollow marks or holes:  
udders: the part of a cow, female goat etc that hangs down between its back legs and that produces milk
pustule: 脓疱
vaccination: to protect a person or animal from a disease by giving them a vaccine
establishment: formal an organization or institution, especially a business, shop etc 
--------------------
spread through: 
developed fevers, vomiting, rashes, smallpox: 
bear scars and scabs: 
spread sth. to sb.: 
devastate the civilization: 
make its way around the world via sb.: 
an estimated A.xx to B.xx n.: 
the fall of sb./sth. start: 
It begins all the way back when + ...: 
grind up sth.: 磨碎莫物
blow the powder into sp.: 
up to xx percent of sth.: 
be exposed to sth.: you are in danger from it
be an apprentice to sjob.: pupil
a pockmarked face: 
protect against sth.: 
A. be caught from B.: 从B带来A(病毒)
challenge sb. with sth.: 
be immune to sth.: 对某事物免疫
with this procedure: 通过这个过程
deliberate at length over sth.: 仔细考虑某事
become prohibited: 变得被禁止
certify sth's eradication: 
be forever remembered as: 
the father of -logy.: 
in this great adventure of sth.: 

** 2013-11-04 The deadly irony of gunpowder
epic: very large and impressive: 
gunpowder: an explosive substance used in bombs and fireworks
alchemist: a science studied in the Middle Ages, that involved trying to change ordinary metals into gold 
flame/ flammable/ flamethrower: literary to burn brightly 
cannon: a large heavy powerful gun that was used in the past to fire heavy metal balls 加农炮
barrel:a large curved container with a flat top and bottom, made of wood or metal, and used for storing beer, wine etc  
canister: a metal container for keeping something in 
channel: to control or direct people or things to a particular place, work, situation etc
wick: the piece of thread in a candle, that burns when you light it
ignite: formal to start burning, or to make something start burning 
compound:a substance containing atoms from two or more elements 
shape: to influence something such as a belief, opinion etc and make it develop in a particular way
upward-facing: 面向上
--------------------
fireworks displays: 
propel sth. into sp.: to move, drive, or push something forward
begin back: to begin to return somewhere
a potion for immortality: 永生药
burn down: to destroy something with fire, or to be destroyed in this way
the opposite of sth.: 
In these early days: 在早些年代
the right proportions of ingredients: 
evil spirits: 
defend sb. against: 
the invention of sth.: 
field sb's attacks: 
on sb's conquests in sp.: 
bringing sth. back to sp.: 
From there: 
left sb's mark on sth.: to have an effect that changes someone or something, usually in a bad way
in contrast to: it is very different from it
be contained within/in: 
build up: accumulate
take an exit from sp.: 
** 2013-10-29 Vampires - Folklore, fantasy and fact
vampire: 
shambling: to walk slowly and awkwardly, not lifting your feet much, for example because you are tired, weak, or lazy
corpse: the dead body of a person
dapper: used to show that you are talking about someone or something that has not been mentioned Debefore, or that your listener does not know about 
revenant: 幽灵, 亡魂
donkey: a grey or brown animal like a horse, but smaller and with long ears
bloodthirsty: eager to kill and wound, or enjoying killing and violence
sever: to cut through something completely, separating it into two parts, or to become cut in this way
upper:in a higher position than something else
torso: your body, not including your head, arms, or legs 
sprout: if vegetables, seeds, or plants sprout, they start to grow, producing shoots, buds, or leaves
wing: one of the parts of a bird’s or insect’s body that it uses for flying
entrail: the inside parts of an animal’s or person’s body, especially their intestines
bloodsucker / bloodsucking: a creature that sucks blood from the bodies of other animals
trait: formal a particular quality in someone’s character
reanimated/reanimation: formal to give new strength to someone or something or the energy to start again 复活
folklore: the traditional stories, customs etc of a particular area or country
nocturnal: an animal that is nocturnal is active at night
grim: making you feel worried or unhappy 严酷的
plague: a disease that causes death and spreads quickly to a large number of people
supernatural: impossible to explain by natural causes, and therefore seeming to involve the powers of gods or magic
cadaver: technical a dead human body, especially one used for study SYN corpse
bloated: if you describe an organization as bloated, you mean that it is too big and does not work effectively
beheading: 斩首
decompose: to decay or make something decay
dehydrate: to remove the liquid from a substance such as food or a chemical
incorporate: to include something as part of a group, system, plan etc
garlic: a plant like a small onion, used in cooking to give a strong taste
stake: 树桩
attribute: 属性
crucifixes: a cross with a figure of Christ on it
reflection: an image that you can see in a mirror, glass, or water
stalk: 潜伏
subsist: to stay alive when you only have small amounts of food or money SYN survive
sparkling: shining brightly with points of flashing light
--------------------
What's the matter: 怎么了
extend as far back as prehistoric times: date back to
back then: at a particular time in the past that you are talking about
be simply described as sth.: 
have one common characteristic: 有个共同特性
sustain oneself by doing sth.: 通过做某事来维持生计
the life force of sth.: 某物的生命力
change with the times: 随时间而改变
With the dramatic increase of sth.: 随着某物的戏剧性增多
dig up <-> sth.: 
discern the cause of sth.: 查明某物的原因
at the corners of mouths: 在嘴角
feast on sth.: 享用某物
enact a ritual to do sth.: 制定仪式去做某事
stake the body to the coffin: 把尸体钉在棺材里
normal symptoms of sth.: 某事的正常现象
cause sb./sth. to do sth.: 
force out sth. through sth.: 通过某处挤出某物
establish a law prohibiting sth./doing sth.: 制定法律禁止某事
die down: 消亡
brutal executions: 残酷的死刑
inspire the main elements of sth.: 激发某事的主要元素
enact the age-old tradition of doing sth.: 延续做某事的古老传统
elaborate upon: 详细碳素
** 2013-12-16 The popularity, plight and poop of penguins
clumsy: moving or doing things in a careless way, especially so that you drop things, knock into things etc
adorable: someone or something that is adorable is so attractive that they fill you with feelings of love
exceedingly: extremely
ornery: behaving in an unreasonable and often angry way, especially by doing the opposite of what people want you to do
precarious: a precarious situation or state is one which may very easily or quickly become worse不稳定的
closest: 最靠近的
albatross: a very large white sea bird
wingspan: 翼展
soar: to increase quickly to a high level
evolutionary: relating to the way in which plants and animals develop and change gradually over a long period of time
flipper-like: a flat part on the body of some large sea animals such as ↑seals, that they use for swimming
dive: to swim under water using special equipment to help you athe: 
hemisphere: a half of the Earth, especially one of the halves above and below the equator
breed: if animals breed, they ↑mate in order to have babies: 
reproduce: 繁殖 
subantarctic: 亚南极(区)的
craggy: 多峭壁的, 崎岖的
lava: hot liquid rock that flows from a volcano, or this rock when it has become solid
burrow: a passage in the ground made by an animal such as a rabbit or ↑fox as a place to live
stick: a long thin piece of wood from a tree, which is no longer attached to the tree ⇨ branch, twig
incubate: if a bird incubates its eggs, or if the eggs incubate, they are kept warm until they hatch
approximately: an approximate number, amount, or time is close to the exact number, amount etc, but could be a little bit more or less than it
indicator: something that can be regarded as a sign of something else
historically: 在历史上, 从历史观点上说
disturbance: 干扰
guano: 海鸟粪
fertilizer: a substance that is put on the soil to make plants grow
marine: relating to the sea and the creatures that live there
terrestrial: living on or relating to land rather than water
habitat: the natural home of a plant or animal
introduce: 引进
predator: an animal that kills and eats other animals ⇨ prey
prey: an animal, bird etc that is hunted and eaten by another animal OPP predator
entrapment: the practice of trapping someone by tricking them, especially to show that they are guilty of a crime
plastic: a light strong material that is produced by a chemical process, and which can be made into different shapes when it is soft
krill: small shellfish
severe severity: severe problems, injuries, illnesses etc are very bad or very serious
conservation: the protection of natural things such as animals, plants, forests etc, to prevent them from being spoiled or destroyed SYN preservation
spills: 泄漏
vulnerable: someone who is vulnerable can be easily harmed or hurt
tuxedo: 燕尾服
current: 当前
--------------------
have long done sth.: 长久做某事
capture the imagination and the hearts of sb.: 
the world over: 
depict A. as B.: describe A. as B.
endlessly abundant: 庞大数量的
in rapid free fall: 在快速自由落体
so to speak: 可以说
For one thing: 首先
evolve from sth.: 从什么进化
the ability to do sth.: 做某事的能力
fill an ecological niche: 占据生态位
contrary to sth.: 与某事相反的
be not restricted to sp.: 不限于某处
subtemperate/temperate regions: 亚热带/热带区域
off sp.: in the neighbor of sp.
molt their feathers: 退去自身的羽毛
in tussock grasses: 在草丛中
a clutch of sth./sb.: 一群/把/组
be listed as sth.: 被列为某物
decline by: 下降
be down to sth.: 下降到
in the coal mine: 在煤矿洞里
Simply put: 简单来说
be attributable to sth.: 对某事归因
due to sth.: [4]归因于
carry sb. too far away from sp.: 
be underway to do sth.: 
** 2014-01-06 How to fossilize yourself
fossil: 
tour: to visit several parts of a country or area
fawn: to praise someone and be friendly to them in an insincere way, because you want them to like you or give you something
exclusive: available or belonging only to particular people, and not shared
fossilization: 化石作用
paleontologist: 古生物学者
highlight: to make a problem or subject easy to notice so that people pay attention to it
sap: the watery substance that carries food through a plant
harden: to become firm or stiff, or to make something firm or stiff OPP soften
mountaintop: the top part of a mountain
prairie: a wide open area of fairly flat land in North America which is covered in grass or wheat
bury: to put something under the ground, often in order to hide it
scavenge: if someone scavenges, they search through things that other people do not want, for food or useful objects
bog: an area of low wet muddy ground, sometimes containing bushes or grasses ⇨ marsh, swamp
shallow: measuring only a short distance from the top to the bottom OPP deep
muddy: covered with mud or containing mud
sandy: covered with sand, or containing a lot of sand
sediment: solid substances that settle at the bottom of a liquid
permineralization: 完全矿化
mineral-rich: 
microscopic: extremely small and therefore very difficult to see
pore: one of the small holes in your skin that liquid, especially ↑sweat, can pass through, or a similar hole in the surface of a plant毛孔, 小孔, 气孔
subduct: 将（眼睛等）向下拉；撤去，除去，减去
surroundings: the objects, buildings, natural things etc that are around a person or thing at a particular time
erosion: the process by which rock or soil is gradually destroyed by wind, rain, or the sea
intrepid: willing to do dangerous things or go to dangerous places – often used humorously SYN brave
amateur: someone who does an activity just for pleasure, not as their job OPP professional
fortuitous: happening by chance, especially in a way that has a good result
magnificent: very good or beautiful, and very impressive
shed: GET RID OF to get rid of something that you no longer need or want
disintegrate: to ak up, or make something ak up, into very small pieces
plate tectonics: 版块构造
--------------------
imagine doing/being sth.:
inspire awe in sb.: 激起某人的惊叹
hordes of sb.: a large unorganized group of individuals
forget about sth.: 
listen up: 
(in) the Hall of sth. Fame: 名人堂
at some point: at an unspecified moment
get to sth.: 到达
A. turn into B.: be transformed into or become a particular kind of thing or person
survive intact: not broken or damaged
sp. remain the domain of sb.: 遗留为某人的领地
The right place to be if you want to do sth. is wherever + ...: 你想做某事的正确地方是无论哪里...
hang around: to pass time idly or in relaxing or socializing
slow down (<-> sth.): 减缓
decay away: 逐渐腐烂
give you more time to do sth.: 
be lucky enough to do sth.: 
What's your next move: 
get saturated with sth.: to fill completely with something
Bit by bit: 一点点
precipitate out of these waters: 从水中析出
hope sb. do sth.: 希望某人做某事
create a perfect cast of sth.: 创造了某物的完美模型
You're not in the clear yet: 你还不能放松
a mountain range: 山脉
erode away sth.: 侵蚀消失某物
Fingers crossed + ...will: 希望成功+...
get gently lifted up: 被抬起
wipe away sth.: to remove (something) by rubbing
scout for sth.: 搜寻，寻找
hope for sth.: 希望得到某物
whack away: 凿穿
in a creek bank: 小溪岸边
millions of years in the making: 历经数百万年形成
extract A. from B.: 从B中提取A
begin the complex task of doing sth.: 开始某事的复杂任务
in obscurity: 默默无闻
work oneself to the bone: to work extremely hard, especially for a long time
hold that pose: 保持这个姿势
** 2014-02-12 The history of marriage
inspirational: providing encouragement or new ideas for what you should do 给予灵感的
hilariously: extremely funny
cynical: 愤世嫉俗的
timeless: literary continuing for ever
humanity: people in general
sedentary: technical a sedentary group of people tend always to live in the splace
agricultural: the practice or science of farming
simultaneous: things that are simultaneous happen at exactly the stime
institution: an important system of organization in society that has existed for a long time
adultery: sex between someone who is married and someone who is not their wife or husband
demographic: 人口统计学的
ruler: someone such as a king or queen who has official power over a country or area
elite: a group of people who have a lot of power and influence because they have money, knowledge, or special skills
concubines: a woman in the past who lived with and had sex with a man who already had a wife or wives, but who was socially less important than the wives 妾
commoner: 平民
monogamy: 一夫一妻制
arrangement: 安排
prayer: words that you say when praying to God or gods
explicitly: expressed in a way that is very clear and direct ⇨ implicit
Adelphopoiesis: 兄弟结义
chapel: the religious services held in a chapel
deceased: the deceased someone who has died, especially recently
conducte: to carry out a particular activity or process, especially in order to get information or prove facts 出现
lineage: 血统 
appease: make someone less angry or stop them from attacking you by giving them what they want安抚
restless: 不安宁的
young: 尚早的
practicality: 实用性
upperclass: 上层社会
industrialization: when a country or place develops a lot of industry
urbanization: 都市化
household: 家庭
pursuit: when someone tries to get, achieve, or find something in a determined way ⇨ pursue
Pair bonding: 配对
----------------------------------------
what sb.(pl) have in common is that + ...: 
vary greatly between sth.(pl): 在事物中有很大的不同
take a quick look at sth.: express that you quickly glanced at something
With the rise of sth.: 随着...的兴起
be a way of doing sth.: 某事是做某事的一种方法
secure rights to sth.: 保护有某物的权力
under certain circumstances: 在某些特殊环境下
designate A. as B.: 把A指派为B
a matter between sth.(pl): 关于某事的事情
be governed by: 受……支配/统治
punishments for sth.: 对某事的惩罚
the legal status of sb.: 某人的法律地位/身份
be born to sb.: 为某人所生
a quarter of sth.: 四分之一
the link between sth.(pl): 某事的联系
in practice: 实际上
the tables were turned: 形势逆转了
have relationships with sb.: 与某人有关系
in public ceremonies: 在公共仪式上
at stake: 利害攸关
became independent from sb./sth.: 独立于
be encouraged by: 被...鼓励
focus on A rather than B: 聚集于A而不是B
ease restrictions on sth.: 放松对某事的限制
be shaped by sth.: 受...影响
** 2014-04-18 Not all scientific studies are created equal
herb: a small plant that is used to improve the taste of food, or to make medicine ⇨ spice
liver: a large organ in your body that produces ↑bile and cleans your blood肝脏
vitamin: a chemical substance in food that is necessary for good health
headline: the title of a newspaper report, which is printed in large letters above the report
attention-grabbing: 引人注意的
proclaim: to say publicly or officially that something important is true or exists
promising: showing signs of being successful or good in the future有前途的
dietary: related to the food someone eats
randomized: to choose things in a way that is not carefully controlled or planned in order to do a scientific test
clinical: relating to treating or testing people who are sick临床的, 病房用的
trial: a process of testing to find out whether something works effectively and is safe
rigorous: careful, thorough, and exact
medication: medicine or drugs given to people who are ill
placebo: a harmless substance given to a sick person instead of medicine, without telling them it is not real. 
significant: having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
overall: considering or including everything
epidemiology/epidemiological: the study of the way diseases spread, and how to control them
nausea: the feeling that you have when you think you are going to ↑vomit (=bring food up from your stomach through your mouth) SYN sickness
cohort: technical a group of people of the sage, social class etc, especially when they are being studied
substance: a particular type of solid, liquid, or gas
inherent: a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
flaw: a mistake, mark, or weakness that makes something imperfect SYN defect
confounding: to confuse and surprise people by being unexpected混淆
pitfall: a problem or difficulty that is likely to happen in a particular job, course of action, or activity缺陷
eliminate: to defeat a team or person in a competition, so that they no longer take part in it SYN knock out淘汰
critical: something that is critical is very important because what happens in the future depends on it SYN crucial
hazard: something that may be dangerous, or cause accidents or problems
asbestos: 石棉
Lead: 铅
cure: a medicine or medical treatment that makes an illness go away
--------------------
Studies have shown that + ...: 研究证明
be bombarded with sth.: 被某物轰炸
be backed up by sth.: 被某物堆积
point the way towards sth.: 指出去某物/处的路
be assigned to sth./ assign sb. to sth.: 被分派到(组/队)
with headaches: 患头痛
be divided into sth.: 被分成...
a comparison group of ...: ...的对照组
have exposure to sth.: 接触某物
establish causal relationships between sth.(pl.): 建立某物之间的因果关系
in addition to: 除...之外
be combined with sth.: 与...结合
go out of sb's way to do sth.: 给自己带来不便或额外的麻烦去做超出要求的事情
take steps (to do sth.): 采取措施(去做某事)
induce changes within ...: 在...内部引起变化
demonstrate a correlation between sth.(pl.): 说明了事物间的相互关系
At the end of the day: 最终
alert sb. to sth.: 提醒某人注意某事
** 2014-05-15 How the heart actually pumps blood
serve: to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应
thump: if your heart thumps, it beats very strongly and quickly because you are frightened or excited砰然地响
pump: to make liquid or gas move in a particular direction, using a pump
perish: formal or literary to die, especially in a terrible or sudden way
opaque: opaque glass or liquid is difficult to see through and often thick不透明的
crude: not exact or without any detail, but generally correct and useful ⇨ approximate
demonstrate: to show or describe how to do something or how something works
label: to use a word or phrase to describe someone or something, but often unfairly or incorrectly
grasp: to completely understand a fact or an idea, especially a complicated one
four-chambered: 四腔的
potentially: something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals.
dual-circulation: 双循环
morphology: the structure of an object or system or the way it was formed
signal: to make a sound or an action in order to give information or tell someone to do something
intimidating: making you feel worried and not confident
complicated: difficult to understand or deal with, because many parts or details are involved SYN complex
medic: 实习医生
motion: the process of moving or the way that someone or something moves
immerse: to put someone or something deep into a liquid so that they are completely covered
squeeze: to press something firmly together with your fingers or hand
mechanism: part of a machine or a set of parts that does a particular job
atria: 心房
vein: 静脉
remaining: the remaining people or things are those that are left when the others have gone, been used, or been dealt with
artery: one of the tubes that carries blood from your heart to the rest of your body ⇨ vein动脉
aorta: the largest ↑artery that takes blood away from your heart大动脉
superficial/superficially: not studying or looking at something carefully and only seeing the most noticeable things浅薄的
pulmonary: 肺部的
column: a tall solid upright stone post used to support a building or as a decoration
tap: a piece of equipment for controlling the flow of water, gas etc from a pipe or container水龙头
spectacular/spectacularly: very impressive
tricuspid: (心脏的)三尖瓣
mitral: (心脏的)二尖瓣
parachute: a piece of equipment fastened to the back of people who jump out of planes, which makes them fall slowly and safely to the ground
leak: if a container, pipe, roof etc leaks, or if it leaks gas, liquid etc, there is a small hole or crack in it that lets gas or liquid flow through泄漏
seamlessly: 无缝合的
unfold: if you unfold something that was folded, or if it unfolds, it opens out
rhythmical: having a strong rhythm
dependable: able to be trusted to do what you need or expect可靠的
caffeine: 咖啡因
blood vessels: 血管
heart valves: 心脏瓣膜
ventricle / ventricular: 
----------------------------------------
For most of history: 在历史大部分时间里
have no idea + ...: 不知道...
feel sb's heart beating: 感受某人的心跳
in surgery teams: 在外科医生团队
point to sth.: 指向指出某物
It's as if + ...: 似乎
Meaning that + ...: 意味着...
the next best thing is to do sth.: 下一个最好的办法是做某事
cut it open: 切开
in reality: 实际上
goes from sp.A to sp.B, back to sp.C: 从A出发到B,再回到C
make sb. wary of sth.: 使得某人提防某事
end up doing sth.: 最终做某事
That's when + ...A + as + ...B: 这是当B发生时A发生的时候.
What you (will) need to get started is sth.: 你需要开始的事是某事
do A. enough for sb. to do B.: 做A足够让某人去做某事
trim sth. down (to sp.): 删减某物到...
rise from sth.: 起源于...
run water into sp.: 把水流进...
close against sth.: 对某物关闭
inflate with sth.: 用某物膨胀
squirt out of sth.: 从某物喷出
with very little wear and tear: 非常少的磨损
give new resonance to sth.: 使...产生新的共鸣
run a race: 参与田径比赛
catch the eye of sb.: 引起某人的注目
** 2014-05-05 The science of attraction
spontaneous: something that is spontaneous has not been planned or organized, but happens by itself, or because you suddenly feel you want to do it自发的, 自然产生的
indescribable: it is too difficult to describe
poetic: 诗歌的
fuzzy: unclear or confused OPP clear
veto: to refuse to accept a particular plan or suggestion
budding: beginning to develop萌芽的
component: one of several parts that together make up a whole machine, system etc SYN constituent
fertility: the ability of the land or soil to produce good crops肥沃
lustrous: shining in a soft gentle way有光泽的, 光辉的
reproductive: relating to the process of producing babies, young animals, or plants生殖的
fitness: when you are healthy and strong enough to do hard work or play sports
cologne: 科隆香水
pheromones: 信息素
physiologyical: the science that studies the way in which the bodies of living things work
recipient: someone who receives something接受者
saliva: the liquid that is produced naturally in your mouth SYN spit
testosterone: the ↑hormone in males that gives them their male qualities
odor: a smell, especially an unpleasant one
molecule / molecular: the smallest unit into which any substance can be divided without losing its own chemical nature, usually consisting of two or more atoms
breathy: 缺少声量的
formant spacing: 共振峰间距
hypothetical: based on a situation that is not real, but that might happen假设的
unaffectionate: 没有感情的
infamous: well known for being bad or evil
tactile: relating to your sense of touch
cue: 暗示
tunnel vision: 视野狭隘(引申义:封闭思想)
bloodstream: the blood flowing in your body
dilate: if a hollow part of your body dilates or if something dilates it, it becomes wider
glucose: 葡萄糖
warp: 扭曲
----------------------------------------
think of A. as B.: 认为A是B
perceive A. as B.: 把A当作B
run a (complex) series of calculations: 进行一系列(复杂)的运算
within a matter of seconds: 在几秒钟之内
sounds quite as adj.: 听起来很像
Just because +... doesn't mean + ...:  仅仅因为 +...并不意味着 +...
all num. of sth.: 某物的全部几个
play a role in doing sth./sth.: 在某事上起作用
be in demand: 是需要的
pick up on sth.: 注意到某事
In one study: 在一项研究中
in sb's ovulation cycle: 在某人的排卵周期内
be randomly assigned to do sth.: 被随机派遣做某事
give sb. the nudge to do sth.: 给某人动力去做某事
be particularly attuned to sth.: 对某事非常熟悉 be familiar with
differ from sth.: 不同于某事某物
result in sth.(death/failure/contradiction): 导致某事
be correlated with sth.: 和某事相关
rate sb's personality: 评价某人的性格
lose sb's attraction to sb.: 丢失对某人的吸引力
be flooded with sth.: 被某事淹没
activate (sb's fight/flight/immune) system: 激活...系统
+..., not because +...,but because + ...: ...,不是因为..., 而是因为...
block out sth.: 遮挡
enhance sb's memory: 增强某人的记忆力
This might explain why + ...: 这可能解释了为什么
play matchmaker: 做媒
** 2014-05-06 What is the world wide web
revolution: a time when people change a ruler or political system by using force or violence ⇨ revolt, rebellion革命
interchangeabe/interchangeably: things that are interchangeable can be used instead of each other
conference: a large formal meeting where a lot of people discuss important matters such as business, politics, or science, especially for several days
skyscraper: a very tall modern city building
know-how: knowledge, practical ability, or skill to do something
domain: an area of land owned and controlled by one person or government, especially in the past领域
virtual: made, done, seen etc on the Internet or on a computer, rather than in the real world
hosting: to provide the place and everything that is needed for an organized event托管 
registrar: 登记员 
loose: not firmly fastened in place宽松的
interconnect: if two systems, places etc are interconnected, or if they interconnect, they are joined together
mirror: if one thing mirrors another, it is very similar to it and may seem to copy or represent it SYN reflect
arrangement: 排列, 安排
hyperlink: a word or picture in a ↑website or computer document that will take you to another page or document if you ↑click on it
encounter: to experience something, especially problems or opposition
reflect: to show or be a sign of a particular situation or feeling: 
boundary: the real or imaginary line that marks the edge of a state, country etc, or the edge of an area of land that belongs to someone
ethnicity: 种族划分
----------------------------------------
be likely doing: 可能正在做某事
be used by sb. for sth.: 被某人使用做某事
chat with sb.: 和某人闲聊
use it from sth.: 通过某物用它
first of all: 首先
made a call to sb.: 打电话给某人
be all around sb.: 就在某人身边
There's another part to doing sth., without which + ...: 做某事还有令一部分, 没有它...
with no way of doing sth.: 没有办法做某事
a graphic interface: 一个图形界面
utility company: 共同服务公司
lie in sth.: 在于某事
be prior to sth.: 在...之前
in a linear fashion: 线形方式
in a straight line: 笔直地
redirect sb. to sp.: 重定向某人到某地
in content and structure: 在内容和结构上
** 2014-05-30 How does your brain respond to pain
stimulus: something that helps a process to develop more quickly or more strongly刺激
matter: v. to be important, especially to be important to you, or to have an effect on what happens
sensory: relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
tissue: the material forming animal or plant cells组织
intensity: technical the strength of something such as light or sound强度
sharp: a sharp pain or feeling is sudden and severe OPP dull
dull: a dull pain is not severe but does not stop OPP sharp
perceptions: the way you think about something and your idea of what it is like理解
damage-sensing: 疼痛感知
nociceptor: 伤害感受器
spinal cord: 脊髓
neuron: a type of cell that makes up the ↑nervous system and sends messages to other parts of the body or the brain SYN nerve cell神经元
glia: 神经胶质
superhighway: a very large road on which you can drive fast for long distances超级高速公路
electrical impulses: 电子脉冲
pathway: a path路
cortex: the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
salient / salience: the salient points or features of something are the most important or most noticeable parts of it
modulate / modulation: to change a process or activity to make it more controlled, slower, less strong etc调制
endorphin: a chemical produced by your body that reduces pain and can make you feel happier内啡肽
enkephalin: 脑啡肽
regulate: to control an activity or process, especially by rules
sensitivity: 敏感, 灵敏(度), 灵敏性
efficacy: formal the ability of something to produce the right result SYN effectiveness OPP inefficacy功效, 效验
brain circuits: 脑回路
variable / variability: likely to change often ⇨ vary 可变性
roller coasters: 过山车
motion: the process of moving or the way that someone or something moves动作
target: to make something have an effect on a particular limited group or area针对
mild: a mild illness or health problem is not serious
non-prescription: a non-prescription drug is one that you can buy in a shop without a written order from a doctor SYN over-the-counter无处方
anesthetic: a drug that stops you feeling pain麻药
severe: severe problems, injuries, illnesses etc are very bad or very serious
chronic: a chronic disease or illness is one that continues for a long time and cannot be cured ⇨ acute慢性的, 延续很长的
stimulate: 刺激, 激励
pain-sensing: 感受痛觉的
map: v. to discover or show information about something, especially about its shape or arrangement, or how it moves or works映射
personalize / personalized: to design or change something so that it is suitable for a particular person
----------------------------------------
receive electric shocks to sb's hands/arms: 某人的手/胳膊受到点击
distract sb. from sth.: 分散某人对于某事的注意
do sth. faster and better when +... than when +...: 做某事更好快当A比当B
send sb's mind wandering: 使某人心烦意乱
be subjected to sth.: 遭受某事
describe sth. on a scale from A. to B.: 用从A到B程度来描述某物
respond to sth.: 对某事作出反应
cope with sth.: 应对某事
take sb. hand off sth.: 把某人的手从某物上拿开
act on sth.: 对...起作用
along with ways to do sth.: 伴随着做某事的方法
tailor sth. to sb.: 为某人量身定做
the key to doing sth.: 做某事的关键
** 2014-06-03 How to choose your news
absorb: to read or hear a large amount of new information and understand it吸收
broad-based: 基础深厚的
newspaper of record: 主流报纸
authoritarian: strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
censor: to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
scandal: talk about dishonest or immoral things that famous or important people are believed to have done丑闻
revelation: a surprising fact about someone or something that was previously secret and is now made known揭露
covert: secret or hidden
assassination: the act of murdering an important person
corruption: dishonest, illegal, or immoral behaviour, especially from someone with power贪污
narratives: a description of events in a story, especially in a ↑novel叙述
mainstream: the mainstream the most usual ideas or methods, or the people who have these ideas or methods主流
gatekeeper: someone whose job is to open and close a gate, and to allow or not allow people to go through it
outlet: a pipe or hole through which something such as a liquid or gas can flow out出路
unfiltered: 未滤过的
protest: something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products
blog / blogger: a web page containing information or opinions from a particular person or about a particular subject, to which new information is added regularly SYN web log
polished: polite, confident, and graceful 精练的, 优美的
chaotic: a chaotic situation is one in which everything is happening in a confused way
terrorist: someone who uses violence such as bombing, shooting etc to obtain political demands
coverage: when a subject or event is reported on television or radio, or in newspapers
accusation: a statement saying that someone is guilty of a crime or of doing something wrong
refute: to prove that a statement or idea is not correct SYN rebut
bias: an opinion about whether a person, group, or idea is good or bad that influences how you deal with it偏见
anonymity: when other people do not know who you are or what your name is
rumor: information or a story that is passed from one person to another and which may or may not be true
falsehood: a statement that is untrue SYN lie
outrageous: very shocking and extremely unfair or offensive骇人的
curate: organize
flow: 流动
----------------------------------------
a click away: 用鼠标点击一下
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
compete with sb.: 同某人竞争
from various perspectives: 从各种各样的视角
More recently: 更近期地
multiply the amount of sth.: 倍增某物的数量
sb. keeps in mind that + ...: 某人牢记...
in real time: 实时
at several points in the day: 在一天的几个点
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
aim for sth.: 争取某物
tuning in to sth.: 收听某事
take a guess: 做猜测
watch out for sth.: 小心提防
have little connection to sth./sb.: 和某事/某物没关系
make sb. unaccountable for sth.: 使某人对于某物没有责任
with A. comes B.: 伴随A来的B
ensure that + ...: 确保...
leave sb. less informed than before + ...: 让某人比...之前更加无知
took the plunge: 冒险
** 2014-11-05 Why elephants never forget
walking hard drive: 移动硬盘
magnificent: very good or beautiful, and very impressive宏伟的
benevolent: kind and generous慈善的
proverb: a short well-known statement that gives advice or expresses something that is generally true.谚语
accurate: correct and true in every detail
encounter: to experience something, especially problems or opposition
hostile: angry and deliberately unfriendly towards someone, and ready to argue with them
recall: to remember a particular fact, event, or situation from the past回想
herd: 兽群
companion: someone you spend a lot of time with, especially a friend
drought: 干旱
circus: a group of people and animals who travel to different places performing skilful tricks as entertainment
rejoice: literary to feel or show that you are very happy
boast: if a place, object, or organization boasts something, it has something that is very good以有...而自豪
encephalization quotient: Brain-To-Body脑化指数
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals
converge/convergent: to come from different directions and meet at the spoint to become one thing会聚
synapse: the place where nerve cells meet, especially in the brain突触
developed: a developed sense, system etc, is better, larger, or more advanced than others发达
hippocampus: 海马体
cerebral: medical relating to or affecting your brain大脑的
recollection: something from the past that you remember
faculty: a natural ability, such as the ability to see, hear, or think clearly本能
rote: formal when you learn something by repeating it many times, without thinking about it carefully or without understanding it死记硬背, 机械的做法, 生搬硬套
clan: a large group of families who often share the namies: 
matriarch: a woman, especially an older woman, who controls a family or a social group
cooperative/cooperatively: willing to cooperate SYN helpful OPP uncooperative
outwit: to gain an advantage over someone using tricks or clever plans
manipulate: to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them
grasp: to take and hold something firmly SYN grip
post-traumatic stress disorder: 创伤后压力紊乱
arithmetic: the science of numbers involving adding, multiplying etc
vocalize/vocalization: to make a sound or sounds with your voice
infrasound: 次声
rumble: a series of long low sounds隆隆声
syntax: the way words are arranged to form sentences or phrases, or the rules of grammar which control this句法
tone: the way your voice sounds, which shows how you are feeling or what you mean语调
recreate: to make something from the past exist again in a new form or be experienced again SYN recapture再创造
melody: a song or tune
altruism: when you care about or help other people, even though this brings no advantage to yourself利他
mourn: to feel very sad because something no longer exists or is no longer as good as it used to be哀悼
burial ritual: 葬礼仪式
log: a thick piece of wood from a tree原木
trunk: the very long nose of an ↑elephant
massive: very large, solid, and heavy
poach: to do something that is someone else’s responsibility, especially when they do not want you to do it偷猎
cull: to kill animals so that there are not too many of them, or so that a disease does not spread猎杀
revenge: something you do in order to punish someone who has harmed or offended you复仇
ivory: the hard smooth yellowish-white substance from the ↑tusks (=long teeth) of an ↑elephant象牙
----------------------------------------
It's a common saying that + ...: 常言道...
it appears that + ...: 看起来似乎
as many as num. sth.: 多达num.个
make a strong impression on sb.: 给某人造成深刻的印象
In one case: 在某种情况下
cross paths (with sb.): (与某人)相遇
sth. isn't limited to sb.: 某物/能力不限于某人
after days/months/years/decades apart: 几十年分别之后
go beyond sth.: 超过某物
encode A. into B.: 把某物A编入某物B
in adulthood: 在成年期
tackle problems: 解决问题
keep track of sth.: 跟踪某事
shown concern for sth./sb.: 爱护某人/物
stand guard: 站岗守卫
comfort sb. with sth.: 用某物安慰某人
it's hard to escape the conclusion that + ...: 很难不得出结论...
in captivity: 在关押
Given what + ...: 鉴于...
It is more important than ever to do sth.: 做某事比以往任何时候更重要
vanish from sp.: 从...消失
** 2014-12-18 What is a gift economy
knit: to make clothing out of wool, using two ↑knitting needles编织
adopt: to take someone else’s child into your home and legally become its parent
contradictory: two statements, beliefs etc that are contradictory are different and therefore cannot both be true or correct
obligation: a moral or legal duty to do something义务
social ties: 社交关系
canoe: a long light boat that is pointed at both ends and which you move along using a paddle独木舟
potlatch: 冬节
chief: the most important person, or one of the most important people, in a company or organization – used especially in job titles and in news reports首领
livestock: animals such as cows and sheep that are kept on a farm
blanket: a cover for a bed, usually made of wool ⇨ duvet
participant: someone who is taking part in an activity or event
barter: to exchange goods, work, or services for other goods or services rather than for money
haggle: to argue when you are trying to agree about the price of something
norm: generally accepted standards of social behaviour标准, 规范
reciprocity: a situation in which two people, groups, or countries give each other similar kinds of help or special rights
voluntarily: if you do something voluntarily, you do it willingly, without anyone telling you to do it
prestige: the respect and admiration that someone or something gets because of their success or important position in society
communal: shared by a group of people or animals, especially a group who live together公共的
taboo: a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing
financial: relating to money or the management of money财政的
profit: money that you gain by selling things or doing business, after your costs have been paid OPP loss 
potluck dinner: 自备餐
prevail: if a belief, custom, situation etc prevails, it exists among a group of people at a certain time
anthropology/anthropologist: the scientific study of people, their societies, cultures etc
native: a person who was born in a particular place
----------------------------------------
This holiday season: 这个假期
consign sth. to the closet: 把某物放入壁橱
expect sth. from sb.: 期待某人某物
be involved in: 涉及到...
for free: adv.免费
without explicit conditions: 没有明显的条件
foster a system of sth.: 培养某事物的体系
be formed by: consist of
throughout human history: 贯穿人类历史
describe sb. doing sth.: 描述某人做某事
make a journey: 进行一次旅行
do sth. through this process: 通过这个过程做某事
carry an obligation to do sth.: 承担做某事的义务
give away sth.: 赠送某物
obligate sb. to do sth.: 迫使某人做某事
return the favor: 回报恩惠
take many forms: 多种形式
at sb's expense: 以某人的费用
gain sth. from sb./sth.: 从某人某物获得某物
be indebted to sb.: 对某人深表感激
be read as doing sth.: be regarded as
be exclusive to sth.: 专属于某物
social pay off: 社会回报
miss the point: 错过重点
** 2015-01-30 Why are some people left-handed?
left-handed: a left-handed person uses their left hand for writing, throwing etc OPP right-handed
proper: right, suitable, or correct
1/10: one-tenth
artifact: 历史文物
fetus: 胎儿
inborn: an inborn quality or ability is one you have had naturally since birth
genetic: relating to ↑genes or ↑genetics遗传的, 起源的
identical: exactly the same, or very similar
gene: 基因 
dominant: more powerful, important, or noticeable than other people or things支配的
consistent: 一致的
ratio: a relationship between two amounts, represented by a pair of numbers showing how much bigger one amount is than the other ⇨ proportion比率
odds: the odds how likely it is that something will or will not happen
millennium/millennia:a period of 1,000 years
theory: 理论,假设hypothesis
competitive: determined or trying very hard to be more successful than other people or businesses ⇨ compete, competitor竞争的
competitor: 竞争者
combat: fighting, especially during a war
hitter: [棒球]击球员
hypothesis: an idea that is suggested as an explanation for something, but that has not yet been proved to be true SYN theory
athletes: someone who competes in sports competitions, especially running, jumping, and throwing运动员
frequency-dependent: 频率相关的
asset: the things that a company owns, that can be sold to pay debts资产
distribution: 分布状态
majority: 多数
equilibrium: a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly
intriguing: something that is intriguing is very interesting because it is strange, mysterious, or unexpected SYN fascinating
skewed: an opinion, piece of information, result etc that is skewed is incorrect, especially because it has been affected by a particular thing or because you do not know all the facts
pawedness: 爪侧性,对左爪或右爪的偏好
hunter-gatherer: 狩猎采集者
puzzle: 难题
----------------------------------------
chances are + ...: 很可能...
in many parts of the world: 在世界各地
the word for A: A这个单词
in the first place: 首先 For one thing
show evidence of sth./doing sth.: 显示做某事的证据
in the womb: 在子宫里
have a 17% chance of doing/being sth.: 有17%的机会做某事
be born adj.: 与生剧来...
by a roll of the dice: 靠投塞子
It implies that + ...: 这意味着...
over the course of millennia: 经过数千年的时间
The benefits of doing sth.: 做某事的好处
a minority to do sth.: 做某事的少数人
be thrown off: 被抛弃
lead to sb. doing sth.: 导致某人做某事
in the opposite direction: 朝相反方向
disappear from: 从...消失
play out: 发展,演变
simultaneously over time: 同时随着时间的推移
in sb's hands: 在某人手中
** 2015-03-12 Plato’s Allegory of the Cave
figurative/figuratively: 比喻的
thread: an idea, feeling, or feature that connects the different parts of an explanation, story etc线索
flicker: 摇曳, 闪烁
flit: to move lightly or quickly and not stay in one place for very long
cheery: happy or making you feel happy
allegory: a story, painting etc in which the events and characters represent ideas or teach a moral lesson寓言
Republic: a country governed by elected representatives of the people, and led by a president, not a king or queen共和国
envision: to imagine something that you think might happen in the future, especially something that you think will be good想象, 预想
cavern: a large ↑cave
faint: difficult to see, hear, smell etc
cast: literary to make light or a shadow appear somewhere投射
classify: to decide what group something belongs to
perceive: formal to notice, see, or recognize something ⇨ perceptive感知
entity: formal something that exists as a single and complete unit ⇨ being实体
disorienting: confusing you and making you not certain about what is happening around you使失去方向感, 使迷惑
reflection: an image that you can see in a mirror, glass, or water映象
adjust: to change or move something slightly to improve it or make it more suitable for a particular purpose调整
ultimate: someone’s ultimate aim is their main and most important aim, that they hope to achieve in the future SYN final最终的
blind: unable to see
ignorance: lack of knowledge or information about something
disrupt: to prevent something from continuing in its usual way by causing problems
disparaging: criticizing someone or something, and showing that you do not think they are very good or important蔑视的
promote: to try to persuade people to support or use something
rule: the government of a country or area by a particular group of people or using a particular system统治
parable: a short simple story that teaches a moral or religious lesson, especially one of the stories told by Jesus in the Bible寓言
mass: a large crowd群众
stubborn: determined not to change your mind, even when people think you are being unreasonable顽固的
ignorant: not knowing facts or information that you ought to know无知的
dialogue: a conversation in a book, play, or film对话
flawed: spoiled by having mistakes, weaknesses, or by being damaged有缺陷的
roundness: 园
fundamental: very necessary and important基础的, 基本的
representation: 表现
theologian: someone who has studied theology神学者
linguistic: related to language, words, or linguistics
concrete: 具体的, 有形的
abstract: 抽象的
assumptions: something that you think is true although you have no definite proof ⇨ assume
consolation: something that makes you feel better when you are sad or disappointed
----------------------------------------
explain A. as B.: 把A解释为B
be like doing sth.: 就像是做某事
be chained up: 被锁起来
face a wall: 面对墙壁
give off: 发出(亮光)
pass by sb./sth.: 经过某人某物
have a hard time doing sth.: 做某事很困难
resist an attempt to do sth.: 抵制做某事的企图
introduce A. as an analogy of B.: 解释A当作B的比喻
be hostile to sb.: 对某人有敌意
the real life: 真实生活中
be sentenced to death/imprisonment: 被判处死刑
capture imaginations: 引起想象
view A. as B.: 把A看作是B
group A under B: 把A归类为B
go about sth.: 忙于某事
a glimmer of light: 一丝光
punch a hole: 打孔
break free (from sth.): 从某事中解脱出来
stick with sth.: 坚持使用某事
* other(If they are too many, then split them)
** public speaking
feel nervous about doing sth.:
give a speech:
in good company: be in the same situation as someone important or respected.
suffer from:
stage fright: nervousness before or during an appearance before an audience
turn pale: their face looks a lighter color than usual, usually because they are ill, frightened, or shocked.
at the outset of a speech:
quake in every limb and in my soul:
report doing sth.:
speaking in public:
be nominated for:
nerve-wracking experience:makes you feel very tense and worried
in jest:
sb. be given a choice/give sb. a choice
would rather do A. than do B.
give the eulogy:

** the best life story
*** 02 Lazy Summers
swoop: 向下猛冲
buzz: 嗡嗡
swat it away: 拍死它
bring a smile to my face: 让我脸上泛起微笑
A. join in the chorus of B.: A加入到B一起
have memories of:想起
swirl around: 盘旋在
reminisce (about): 缅怀

** Reading to Learn the Art of Expression
observant
clause

biographical sketch
forms of ...
from all over England
sb's aim is to do ...
receive treatment (from sb.)
at a time when ...
stay adj.

** humans of NewYork
be down to ride: support
*** 01 You're the best dad ever
pop up
what it's like: to be familiar with how it feels to be or do something
rip out heart
back off
get a flicker of: a feeling or expression of an emotion or quality that does not last very long

** Let him Go, Olivia
It's over.
pass away
in recognition of sb.:褒奖
write this story as a tribute to sb.
make it possible for sb to have done

** Children’s Engineering Workshops.
workshop: 研习班
want some information about sth. :想要某物的信息
design a adj. cover that goes round sth. : 设计一个保护套包裹住某物
there is an opportunity for sb. to do sth.: 对某人有机会做某事
be amazed + ...: 对...吃惊
one thing sb. does is to do sth.:某人做的一件事是做某事
A. be attached to B.: B绑到A上
the force of air/water: 空气的力量
presumably: 估计是
advanced: 更高级的
construct A. using B.: 用B来构造A
pick sth. up: 某事进步
use A. to do B.: 用A来做B
come up with=think up an idea for sth.: 为某事想出主意
A. in the shape of B.: B形状的A
give sb. enough time to do sth.: 给某人足够的时间去做某事
up past sp.: 过了某处
enrol: 报名

** stoicism
achieve sb's triumphs
the likes of sth.: is used to refer to people or things of a similar type or category
have access to sth.: possess the ability or permission to use, enter, or obtain something.
come to sb.: emphasizes the process of understanding or realization
in turn: used to explain how a series of actions or circumstances are interconnected
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."
put on ...: mean to organize, present, or perform a show, event, or production.
prime minister: the most important minister and leader of the government in some countries which have a parliament
the course of ...: is used to describe the progression or development of something over a period of time.
at the root of sth.: refers to the fundamental or foundational essence of a concept, idea, problem, or situation
resonate with: if something such as an event or a message resonates, it seems important or good to people, or continues to do this
refer to a. as b.: regard sth. as sth.
* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
- 结合其他语法

* NCE2 homework
** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion

* NCE3 homework
** 单词造句
** 反复听电影片段直到懂关键句
** 给自己讲解语法
** 反复朗读语法例句
** 复习二册语法(笔记或视频) & 红皮书
** 习惯用法造句
** 跟读 50遍
** Comprehension 反复练习
** Ask me if 写+读
** 摘要写作 写 & 对答案
** tell the story 口语复述
** composition 阅读 或 写作
** Topics for discussion
* NCE2
** L01 A private conversation
private [ˈpraɪvət] adj.私人的
conversation [ˌkɒnvəˈseɪʃ(ə)n] n.谈话
theatre [ˈθɪətə(r)] n.戏院
seat [siːt] n.座位
play [pleɪ] n.戏
loudly [ˈlaʊdli] n.大声地
angry [ˈæŋɡri] adj.生气的
angrily [ˈæŋɡrəli] adv.生气地
attention [əˈtenʃ(ə)n] n.注意
bear [beə(r)] v.容忍
business [ˈbɪznəs] n.事
rudely [ˈruːdli] adv.粗鲁地

have a conversation: 谈话
take a seat: 坐座位
Is the seat taken?: 这个位置被坐了吗
How can you bear that?: 你怎么忍受那个的?
Don't be rude: 别粗鲁
--------------------
6123456:
	 6: When
	 1: 主
	 2: 谓/系
	 3: 宾/表
	 4: how
	 5: where
	 6: when
give me that book VS give it to me
1. 如何造一个英语句子: 123 
2. 如何造一个好的英文句子: 123456
3. 英语语序

go to the theatre: 去看戏
have a good seat: 有好座位
get angry: 变得生气
turn round: 转身
pay attention: 注意
in the end: 最终
couldn't bear it: 忍不了了
It's none of your business: 与你无关

** L02 Breakfast or lunch?
until [ʌnˈtɪl] prep.直到
outside [ˌaʊtˈsaɪd] adv.外面
ring [rɪŋ] v.(铃)响
aunt [ɑːnt] n.姑,姨
repeat [rɪˈpiːt] v.重复

repeat after me: 重复我

--------------------
am/is/are + doing:
	1. 动作正在发生;
	2. 动作已经开始,但未完成;
	3. 表近期计划(+未来时间)
	4. 一段时间正在发生的事情: today/this week/this year(阶段)连用
	5. 一段时间正在发生的变化: get/change/become/increase/rise/fall/grow/improve/begin/start

do/does: 动作发生在说话时发生不重要
	1. 习惯动作(一直/重复发生的事情)
	2. 客观事实
	3. 行为靠说话完成. I promise,suggest,apologise,advise,insist,agree,refuse

am/is/are + doing VS do/does
	- 正在发生的行为还没有完成 VS 一直/重复发生的事情
	- 暂时的情况 VS 长久的情况
	- I always do(总是做某事) VS I'm always doing(总是做某事到不正常的程度)

感叹句: 形容词需要升调
	What + (形容词) + n. (+ 主语 + 谓语)

频率adv.位置: 
	1. 动词前,be/助/情态动词后
	2. is/will/did省略句前
	3. probably won't;

get up early/late: 起床早/晚
just then: at a particular time in the past在那时
have breakfast: 吃早餐

** L03 Please send me a card
send [send] v.寄,送
postcard [ˈpəʊstkɑːd] n.明信片
spoil [spɔɪl] v. 使索然无味,损坏
museum [mjuˈziːəm] n.博物馆
public [ˈpʌblɪk] adj.公共的
friendly [ˈfrendli] adj.友好的
waiter [ˈweɪtə(r)] n.服务员
lend [lend] v.借给
decision [dɪˈsɪʒ(ə)n] n.决定
whole [həʊl] adj.整个的
single [ˈsɪŋɡ(ə)l] adj.唯一的,单一的

buy sb. sth. = buy sth. for sb. 买东西给某人
send sb. sth. = send sth. to sb. 送东西给某人
lend sb. sth. = lend sth. to sb. 借东西给某人
borrow sth. from sb. / borrow sb. sth. 从某人那借东西
make a decision: 做决定

--------------------
was/were/did: 过去的状态(was/were) & 动作发生在过去(did) & 和过去时间点连用

teach sb. sth. 教某人某事
lend sb. sth. 借给某人某物
think about sth./sb. 想某人某物
on the last day 在最后一天
make a decision 做决定
send sth. to sb. 送某人某物
spend st. sw. 在某地花多少时间

** L04 An exciting trip
exciting [ɪkˈsaɪtɪŋ] adj.令人兴奋的
receive [rɪˈsiːv] v.接受
firm [fɜːm] n.公司
different [ˈdɪfrənt] adj.不同的
centre [ˈsentə(r)] n.中心
abroad [əˈbrɔːd] adv.国外地

have a great trip: 旅途愉快
receive sth. from sb. 从某人收到某物
work for 为(公司/某人)工作
A be different from B A不同于B
in the centre of sp. 在某地的中央
go abroad 去国外
live abroad 住国外
study abroad 留学

--------------------
have done:
	1. 过去事情对现在有影响;
	2. 从过去持续到现在
	3. 与just~already和yet连用
		just: 刚刚
		already: 早就(预料之前)
		yet: 到目前为止(期待发生,只用疑问和否定句)
	4. 不用过去时间点连用
	5. have gone to 去了那里 & have been to 在那里

receive sth. from sb. 从某人收到某物
work for sb. 为(公司/某人)工作
a great number of 大量+(nc.)
have gone to sp. VS have been to sp. 动身去某地 VS 去过某地
fly to sp. 飞去某地
find n. adj. 发现某物/人怎么样

** L05 No wrong numbers
pigeon [ˈpɪdʒɪn] n.鸽子
message [ˈmesɪdʒ] n.信息
cover [ˈkʌvə(r)] v.越过
distance [ˈdɪstəns] n.距离
request [rɪˈkwest] n.要求,请求
spare [speə(r)] part [pɑːt] n.备件
service [ˈsɜːvɪs] n.业务,服务

leave sb. a message 给某人留了信息
customer service: 客户服务
cover the distance in st. 在一定时间内越过这个距离

--------------------
have done VS did: 用过去的事情说现在 VS 只说过去的事情

A is 5 miles from B
get sth. for sb.: 为某人取得某物
cover the distance in st.
a great many
send a request for sth.
up to now: 迄今
in this way

** L06 Percy Buttons
beggar [ˈbeɡə(r)] n.乞丐
food [fuːd] n.食物
pocket [ˈpɒkɪt] n.衣服口袋
call [kɔːl] v.拜访,光顾

pocket money 零花钱
call at = visit 拜访

--------------------
a/an VS the: 泛指 VS 特指
some VS any:
	1. 陈述句? 肯定some, 否定any
		 有任何的意思? any
	2. if从句? any
	3. 疑问句? 确认some, 不确认any

move to sw. 搬到某地
knock at the door 敲门
ask sb. for sth. 请求某人做某事
stand on sb's head 倒立
call at 拜访
in return for this: 作为对此的回报
once/twice a st.: 多久一/两次
ask for sth.: 请求某物

** L07 Too late
detective [dɪˈtektɪv] n.侦探
airport [ˈeəpɔːt] n.机场
expect [ɪkˈspekt] v.期待,等待
valuable [ˈvæljuəbl] adj.贵重的
parcel [ˈpɑːs(ə)l] n.包裹
diamond [ˈdaɪmənd] n.钻石
steal [stiːl] stole [stəʊl] stolen [ˈstəʊlən] v.偷
main [meɪn] adj.主要的
airfield [ˈeəfiːld] n.飞机起落的场地
guard [ɡɑːd] n.警戒,守卫
precious [ˈpreʃəs] adj.珍贵的
stone [stəʊn] n.石子
sand [sænd] n.沙子

keep guard: 站岗

--------------------
was/were + doing: 过去正在进行
when & while & just as(正像,正当): 当...


all morning 整个上午
	The plane was late and detectives were waiting at the airport all morning.
a parcel of sth. 一包某物
a few hours earlier 几小时前
keep guard 站岗
to sb's surprise 令某人吃惊的
try to do sth. 尝试做某事
A be full of B A充满了B

** L08 The best and the worst
competition [ˌkɒmpəˈtɪʃ(ə)n] n.比赛
neat [niːt] adj. 整齐的,整洁的
path [pɑːθ] n.路径
wooden [ˈwʊdn] adj.木头的
pool [puːl] n.水池

enter the competition 参加比赛
make a path 开辟路径
That's neat 这是整洁的

--------------------
adj. 比较级&最高级变化规则
	1. 单音节:+er/est
		 - 元+辅音字母结尾: 需双写辅音字母 big -> bigger
	2. 双音节:
		 - 辅音+y结尾: y变成i pretty -> prettier
	3. 多音节: + more/less, most/least
	4. 不规则:good/well~bad~much~little
比较状从:
	1. 主语 + be + the + adj.est + n. + I've ever met/seen
	2. 主语 + be + the + adj.est + n. + 范围
	3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)

enter for: 参加
make a path 开辟路径
build a bridge 建桥
win a prize 赢得奖品

** L09 A cold welcome
welcome [ˈwelkəm] v.n.欢迎.欢迎
crowd [kraʊd] n.人群
gather [ˈɡæðə(r)] v.聚集
hand [hænd] n.(表或机器的)指针
shout [ʃaʊt] v.喊叫
refuse [rɪˈfjuːz] v.拒绝
laugh [lɑːf] v.笑

a cold welcome 冷遇
a warm welcome 热遇
gather round 聚集在一起
shout at sb. 对某人大声呼叫
refuse to do sth. 拒绝去做某事
laugh at sb. 嘲笑某人

--------------------
at/on/in(时间)
	- on + 具体某一天
	- in + 年/季/月
	- at + 时间点

the last day of the year 这一年的最后一天
a large crowd of 大量的人群
in twenty minutes' time 二十分钟后
refuse to do sth. 拒绝去做某事
at that moment 在那一刻
begin to do sth. 开始做某事

** L10 Not for jazz
jazz [dʒæz] n.爵士音乐
musical [ˈmjuːzɪk(ə)l] adj.音乐的
instrument [ˈɪnstrəmənt] n.乐器
clavichord [ˈklævɪkɔːd] n.古钢琴
recently [ˈriːs(ə)ntli] adv.最近
damage [ˈdæmɪdʒ] v.损坏
key [kiː] n.琴键
string [strɪŋ] n.(乐器的)弦
shock [ʃɒk] v.使不悦或生气,震惊
allow [əˈlaʊ] v.允许,让
touch [tʌtʃ] v.触摸

be allowed to do sth. 被允许做某事
allow sb. to do sth. 允许某人做某事

--------------------
am/is/are+done
was/were+done
am/is/are+being+done
have/has+been+done

be made in sw. 某地制造
belong to sb. 属于某人
play jazz 弹爵士
be allowed to do sth. 被允许做某事

** L11 One good turn deserves another
turn [tɜːn] n.行为,举止
deserve [dɪˈzɜːv] v.应得到,值得
lawyer [ˈlɔɪə(r)] n.律师
bank [bæŋk] n.银行
salary [ˈsæləri] n.工资
immediately [ɪˈmiːdiətli] adv.立刻

one good turn deserves another. 好的行为值得另一个好的
get a good salary 获得不错的薪水
It's your turn 轮到你了

get a good salary 获得不错的薪水
borrow sth. from sb. 从某人借某物
pay it back 偿还回来
pay for sth. 支付某物
ask sb. to do sth. 问某人去做某事

** L12 Goodbye and good luck
luck [lʌk] n.运气,幸运
captain [ˈkæptɪn] n.船长
sail [seɪl] v.航行
harbour [ˈhɑːbə(r)] n.港口
proud [praʊd] adj.自豪
important [ɪmˈpɔːt(ə)nt] adj.重要的

lucky dog 幸运儿
be proud of 以...为豪
I got a very important question to ask you 我有一个非常重要的问题问你

--------------------
will do: 将/会(当机立断决定,而非计划)
shall do: 将/会(当机立断决定,而非计划) 

sail from sw. 从某地航行
set out 出发
have plenty of time 有充足的时间
will be away 将会离开
A be proud of B  A以B为豪
say goodbye to sb. 对某人说再见
take part in 参加

** L13 The Greenwood Boys
group [ɡruːp] n.小组,团体
pop [pɒp] singer [ˈsɪŋə(r)] n.流行歌手
club [klʌb] n.俱乐部
performance [pəˈfɔːməns] n.演出
occasion [əˈkeɪʒ(ə)n] n.场合

a group of 一组，一群
pop music/song/star 流行音乐/歌曲/明星
give a performance 进行一次演出
on this occasion 在这个场合

--------------------
will be doing: 1.未来动作正在进行;2.计划

a group of
at present 目前，现在
all parts of the country 全国各地
as usual 按照通常的方式或习惯
have a difficult time 遇到困难
give five performance 五项表演
keep order 维持秩序
on these occasions 在这种场合

** L14 Do you speak English?
amusing [əˈmjuːzɪŋ] adj.好笑的,有趣的
experience [ɪkˈspɪəriəns] n.经历
wave [weɪv] v.招手
lift [lɪft] n.搭便车
reply [rɪˈplaɪ] v.回答
language [ˈlæŋɡwɪdʒ] n.语言
journey [ˈdʒɜːni] n.旅行

have an amusing experience 有一次有趣的经历
wave to sb. 向某人招手
take a lift/ ask for a lift 搭车/要求搭车
A give B a lift 让某人搭便车
reply to the email/letter 回复邮件/信件
go on a journey 进行一次旅行

--------------------
had + done: 1.过去的过去;2.过去A发生,对于过去B产生影响(A在B前);3.动作从过去A持续(重复)到过去B

drive on to sw. 继续开车到某地
on the way 在路上
ask sb. for a lift 问某人搭便车
apart from 除了...之外
in French 用法语

** L15 Good news
secretary [ˈsekrət(ə)ri] n.秘书
nervous [ˈnɜːvəs] adj.精神紧张的
afford [əˈfɔːd] v.负担得起
weak [wiːk] adj.弱的
interrupt [ˌɪntəˈrʌpt] v.插话,打断

be nervous about sth. / doing sth. 对某事/做某事紧张
afford sth. 负担某物
Sorry to interrupt, but... 很抱歉打断, 但是...

--------------------
宾语从句: 句子做宾语
直接引语变间接引语: 时态倒退一个时态,现在->过去,过去->过去完成;客观事实仍成立可不退

look up 抬头看
afford to pay 负担得起支付
my turn had come 轮到我了
in a weak voice 用微弱的声音

** L16 A polite request
park [pɑːk] v.停放(汽车)
traffic [ˈtræfɪk] n.交通
ticket [ˈtɪkɪt] n.交通违规罚款单
note [nəʊt] n.便条
area [ˈeəriə] n.地段
sign [saɪn] n.指示牌
reminder [rɪˈmaɪndə(r)] n.提示
fail [feɪl] v.无视,忘记
obey [əˈbeɪ] v.服从

make notes/ a note 做笔记
leave a note 留下便条
remind sb. of sth./sb. 使得某人想起某事或某人
fail to do sth. 失败做某事

--------------------
if从句
	- 主将从现
	- 主情从现
	- 主祈从现

park sb's car 停某人的车
pay attention to 注意到某事
	
** L17 Always young
appear [əˈpɪə(r)] n.v.登场,扮演
stage [steɪdʒ] n.舞台
bright [braɪt] adj. + color [ˈkʌlə(r)] + n.鲜艳的颜色
stocking [ˈstɒkɪŋ] n.(女用)长筒袜
sock [sɒk] n.短袜
grown-up [ˌɡrəʊn ˈʌp] adj. n.成年人

--------------------
must: 肯必须(主观);否禁止
have to: 肯必须(客观):否不必
've/have got to: 表必须

肯否猜测:
	- 现在猜测
		must: 一定是
		can't: 一定不是
	- 过去猜测
		must have done: 当时一定是
		can't have done: 当时一定不是

at least 至少
in spite of this 尽管这样
take part in 参加(比赛)

** L18 He often does this
pub [pʌb] n.小酒店
landlord [ˈlændlɔːd] n.店主
bill [bɪl] n.账单

pay the bill 支付账单

--------------------
have 万能动词

look for 寻找
have a meal 吃饭
pay the bill 支付账单
in a few minutes 在几分钟内

** L19 Sold out
hurry [ˈhʌri] v.匆忙
ticket [ˈtɪkɪt] office [ˈɒfɪs]售票处
pity [ˈpɪti] n.令人遗憾的事
exclaim [ɪkˈskleɪm] v.大声说
return [rɪˈtɜːn] v.n.退回
sadly [ˈsædli] adv.悲哀地,丧气地

hurry to sw. 匆忙去某地
in a hurry 匆忙地
What a pity 多么遗憾
It's a pity that... 非常遗憾...
Don't yell at me. 别冲着我叫

--------------------
也许 现在-猜测: 
may/might (not)do
may/might (not)be adj./n.
may/might (not)be doing

也许 过去-猜测: 
may/might (not)have done
may/might (not)have been adj./n.
may/might (not)have been doing.

sold out 售完
at once (=immediately, soon) 立刻
might/may as well 最好

** L20 One man in a boat
catch [kætʃ] caught caught v.抓到
fisherman [ˈfɪʃəmən] n.钓鱼人,渔民
boot [buːt] n.靴子
rubbish [ˈrʌbɪʃ] n.垃圾
waste [weɪst] n v.浪费
realize [ˈriːəlaɪz] v.意识到

catch your eye 引起你的注意
catch a bus 赶公交车
watch your tongue 小心言辞
That's rubbish 这是垃圾
You're wasting time. 你在浪费时间
sb. realized that... 某人意识到...

--------------------
动名词:v-ing

instead of doing sth. 而不是做某事
spend st. sw. 在某地花费时间
give up doing sth. 放弃做某事
be interesting in doing sth. 对做某事赶兴趣
be keen on doing sth. 对做某事感兴趣

** L21 Mad of not?
mad [mæd] adj.发疯
reason [ˈriːz(ə)n] n.原因
sum [sʌm] n.量
determined [dɪˈtɜːmɪnd] adj.坚定的,下决心的

be mad at sb. 对某人很恼火
for some reason 因为一些原因
a large sum of money 一大笔钱
be determined to do sth. 决心做某事

--------------------
will/would be done
can/could be done
must be done
have to be done
must have been done

drive sb. mad 使某人发狂
for some reason 因为一些原因
come into use 投入使用

** L22 A glass envelope
dream [driːm] v.做梦,梦想
age [eɪdʒ] n.年龄
channel [ˈtʃæn(ə)l] n.海峡
throw [θrəʊ] threw [θruː] thrown [θrəʊn] v.扔,抛
regularly [ˈreɡjələli] adv.有规律地

dream of doing sth. 梦想做某事
at my age 以我的年纪
throw away 丢弃

--------------------
v. + of/from/in/on

think of sth. 考虑某事
write to sb. 写给某人
decide to do sth. 决定做某事

** L23 A new house
complete [kəmˈpliːt] v.完成
modern [ˈmɒd(ə)n] adj.新式的,与以往不同的
strange [streɪndʒ] adj.奇怪的
district [ˈdɪstrɪkt] n.地区

You complete me. 你完成了我
have a letter from sb. 收到某人的信
get a surprise 得到个惊喜

** L24 It could be worse
manager [ˈmænɪdʒə(r)] n.经理
upset [ˌʌpˈset] adj.不安
sympathetic adj.表示同情的
complain [kəmˈpleɪn] v wicked [ˈwɪkɪd] adj.抱怨
contain [kənˈteɪn] v.包含,内装
honesty [ˈɒnəsti] n honest [ˈɒnɪst] adj.诚实

get/be upset about sth. 对某事很沮丧
complain about sth. 抱怨某事
start to do sth. 开始做某事

** L25 Do the English speak English?
railway [ˈreɪlweɪ] n.铁路
porter [ˈpɔːtə(r)] n.搬运公
several [ˈsevrəl] q. 几个
foreigner [ˈfɒrənə(r)] n.外国人
wonder [ˈwʌndə(r)] v.感到奇怪

not know the way to sw. 不知道去某地的路

--------------------
1. and,but,or,so,because(Because & ,because): 连句子
2. both... and, either...or,neither...nor: 连两名词
3. not only... but also (as well) ?: 连句子

** L26 The best art critics
art [ɑːt] n.艺术
critic [ˈkrɪtɪk] n.评论家
paint [peɪnt] v.画
pretend [prɪˈtend] v.假装
pattern [ˈpæt(ə)n] n.图案
curtain [ˈkɜːt(ə)n] n.窗帘,幕布
material [məˈtɪəriəl] n.材料
appreciate [əˈpriːʃieɪt] v.鉴赏
notice [ˈnəʊtɪs] v.注意到
whether [ˈweðə(r)] conj.是否
hang [hæŋ] hung hung v.悬挂,吊
critically [ˈkrɪtɪkli] adv.批评地
upside [ˈʌpsaɪd] down 上下颠倒地

sb. pretend that ... 某人假装...
I really appreciate that. 我真的感激.

** L27 A wet night
tent [tent] n.帐篷
field [fild] n.田地,田野
smell [smel] smelt v.闻起来
wonderful [ˈwʌndərfəl] adj.极好的
campfire [ˈkæmpˌfaɪr] n.营火,篝火
creep [krip] v.爬行
sleeping [sliːp] bag 睡袋
comfortable [ˈkʌmfərtəb(ə)l] adj.舒适的,安逸的
soundly [ˈsaʊn(d)li] adv.香甜地
leap [lip] v.跳跃,跳起
heavily [ˈhevɪli] adv.大量地
stream [strim] n.小溪
form [fɔrm] v.形成
wind [waɪnd] wound wound v.蜿蜒
right [raɪt] adv.正好

put up the tent 搭起帐篷
tell a story/stories 讲个故事
put out the fire 扑灭火焰
begin doing sth. 开始做某事
wake up 醒来

** L28 No parking
rare [rer] adj.罕见的
ancient [ˈeɪnʃənt] adj.古代的,古老的
myth [mɪθ] n.神话故事
trouble [ˈtrʌb(ə)l] n.麻烦
effect [ɪˈfekt] n.结果,效果
Medusa n.美杜莎
Gorgon n.

have trouble with sth. 在某事上有困难
	He has had trouble with cars and their owners.
have no effect 无效
have trouble doing sth. 做某事有困难

--------------------
限定性定语从句:
	- 输出:
		1. 确定被修饰词
		2. 确定引导词, who/whom/which/that
		3. 是否可以省略(引导词在从句是宾语可省)
	- 有多个人或物时,起限定某个的作用
	- what = the thing(s) that(补充了主句成分)
	- where: 指代地点,介词不要了. a place where ... , 而不是 a place where ... in.
			还有to which, in which的变形,注意!!!
	- whose: her, his, their

** L29 Taxi!
taxi [ˈtæksi] n.出租汽车
Pilatus Porter
land [lænd] v.着陆
plough [plaʊ] v.耕地
lonely [ˈloʊnli] adj.偏僻的,人迹罕至的
Welsh [welʃ] adj.威尔士的
roof [ruf] n.楼顶
block [blɑk] n.一座大楼
flat [flæt] n.公寓房
desert [ˈdezərt] v.废弃

take a taxi 乘坐出租车

--------------------
done做定语: 表被动一般/被动完成/主动完成(少)
	- done + n.
	- n. + done短语
	- 常常与there be句型连用
复习have done VS did

** L30 Football or polo?
polo [ˈpoʊloʊ] n.水球
Wayle n.
cut [kʌt] cut cut v.穿过
row [raʊ] v.划(船)
kick [kɪk] v.踢
towards [təˈwɒrd] prep.朝,向
nearly [ˈnɪrli] adv.几乎
sight [saɪt] n.眼界,视域

kick his ass 踢他的屁股

--------------------
doing现在分词做定语: 主动进行/主动一般
	- doing + n.
	- n. + doing
	- 常常和there be连用
	- 例句
		- the sinking ship=the ship that is sinking
		- the rising sun=the sun that is rising
		- the sleeping child=the child who is sleeping

call out to sb. 向某人呼喊

** L31 Success story
retire [rɪˈtaɪr] v.退休
company [ˈkʌmpəni] n.公司
bicycle [ˈbaɪsɪk(ə)l] n.自行车
save [seɪv] v.积蓄
workshop [ˈwɜrkˌʃɑp] n.车间
helper [ˈhelpər] n.帮手,助手
employ [ɪmˈplɔɪ] v.雇佣
grandson [ˈɡræn(d)ˌsʌn] n.孙子

save sb's life 救某人的命
--------------------
used to do sth.: 过去常常,但现在不做

It is/was sb's job to do sth.
in sb's twenties

** L32 Shopping made easy
once [wʌns] adv.曾经,以前
temptation [tempˈteɪʃ(ə)n] n.诱惑
article [ˈɑrtɪk(ə)l] n.物品,东西
wrap [ræp] v.包裹
simply [ˈsɪmpli] adv.仅仅
arrest [əˈrest] v.逮捕

once upon a time 很久以前
resist the temptation 抵制诱惑
wrap up sth. 把某事包起来

--------------------
as ... as VS so ... as(否): 同样的

It is easy for sb. to do sth. 对某人来说做某事很容易
hand sth. to sb. 把某物交给某人
wrap sth. up 把某事包起来
as quickly as possible 尽快

** L33 Out of the darkness
darkness [ˈdɑrknəs] n.黑暗
explain [ɪkˈspleɪn] v.解释,叙述
coast [koʊst] n.海岸
storm [stɔrm] n.暴风雨
towards [təˈwɒrd] prep.向,朝;接近
rock [rɑk] n.岩石,礁石
shore [ʃɔr] n.海岸
light [laɪt] n.灯光
ahead [əˈhed] adv.在前面
cliff [klɪf] n.峭壁
struggle [ˈstrʌɡ(ə)l] v.挣扎
hospital [ˈhɑspɪt(ə)l] n.医院

struggle up 艰难地爬起来
explain sth. to sb. 向某人解释某事
go ahead 前进
 
--------------------
be high up 高高在上
On doing sth, ... 一做完某事,就...

** L34 Quick work
station [ˈsteɪʃ(ə)n] n.警察局
most [moʊst] adv.相当,非常
--------------------
had been + done

call at = visit 不那么正式
except sth. to be found 期待某物被找到

** L35 Stop thief!
while [hwaɪl] n.一段时间
regret [rɪˈɡret] v.后悔
far [fɑr] adv.非常
rush [rʌʃ] v.冲
act [ækt] v.行动
straight [streɪt] adv.径直
fright [fraɪt] n.害怕
battered [ˈbætərd] adj.撞坏的
shortly [ˈʃɔrtli] adv.很快,不久
afterwards [ˈæftərwərdz] adv.以后

a short while ago 不久之前
regret sth./doing sth. 后悔做某事
rush out of/towards 冲出/奔向
go straight ahead 直走
give me a fright 吓我
get a fright 受到惊吓
Shortly afterwards 不久之后

--------------------
so + adj./adv. that = such + n. that: 如此以至于
see sb. do sth VS see sb. doing sth.

** L36 Across the Channel
record ['rekərd] n.记录
strong [strɔŋ] adj.强壮的
swimmer [ˈswɪmər] n.游泳运动员
succeed [səkˈsid] v.成功
train [treɪn] v.训练
anxiously ['æŋkʃəsli] adv.焦急地
intend [ɪnˈtend] v.打算
solid [ˈsɑlɪd] adj.固体的,硬的

set up a new world record 创造一项新的世界纪录
break the record 打破纪录
as strong as a horse 像马一样强壮
strong like a horse 像马一样强壮
succeed in doing sth. 成功做某事
train sb. to do sth. 训练某人做某事
intend to do sth. 打算做某事

--------------------
表述将来: 计划
be going to do(be due to)
will
intend to do

hope to do sth. 希望做某事
be sure to do sth. 务必做某事
take some rests/a rest 休息一下

** L37 The Olympic Games
Olympic adj.奥林匹克的
hold [hoʊld] v.召开
government [ˈɡʌvərnmənt] n.政府
immense [ɪˈmens] adj.巨大的
stadium [ˈsteɪdiəm] n.露天体育场
standard [ˈstændərd] n.标准
capital [ˈkæpɪt(ə)l] n.首都
fantastic [fænˈtæstɪk] adj.巨大的
design [dɪˈzaɪn] v.设计

hold a meeting 召开会议

--------------------
will have done: 1.动作持续(重复)到将来;2.动作截至到未来时间点前完成
have done VS had done VS will have done

look forward to doing sth. 期待做某事

** L38 Everything except the weather
except [ɪkˈsept] prep.除了
Mediterranean [ˌmedɪtəˈreɪniən] n.地中海
complain [kəmˈpleɪn] v.抱怨
continually [kən'tɪnjʊəlɪ] adv.不断地
bitterly [ˈbɪtərli] adv.刺骨地
sunshine [ˈsʌnˌʃaɪn] n.阳光

complain about sth. 抱怨某事
bitterly cold 刺痛地寒冷

--------------------
一前就后,过去完成时的固定句式
had hardly done ... when ...
had no sooner done ... than ...

dream of doing sth. 梦想做某事
plan to do 计划做某事
settle down 安顿下来

** L39 Am I all right?
operation [ˌɑpəˈreɪʃ(ə)n] n.手术
successful [səkˈsesfəl] adj.成功的
following [ˈfɑloʊɪŋ] adj.下一个
patient [ˈpeɪʃ(ə)nt] n.病人
alone [əˈloʊn] adj.独自的
exchange [ɪksˈtʃeɪndʒ] n.(电话的)交换台
inquire [ɪnˈkwaɪr] v.询问,打听
certain [ˈsɜrt(ə)n] adj.某个
caller [ˈkɔlər] n.打电话的人
relative [ˈrelətɪv] n.亲戚

have an operation 动手术
leave me alone 离我远点
inquire about sth./sb. 询问某事/某人

--------------------
宾语从句
NCE1 L99 L101 L133 L135 L139

refuse to do sth. 拒绝做某事
ask for sth. 寻求某物
be allowed to do sth. 被允许做某事

** L40 Food and talk
hostess [ˈhoʊstəs] n.女主人
unsmiling [ʌnˈsmaɪlɪŋ] adj.不笑的,严肃的
tight [taɪt] adj.紧身的
fix [fɪks] v.凝视
globe [ɡloʊb] n.地球
despair [dɪˈsper] n.绝望

in despair 绝望地

--------------------
虚拟语气(现在): 与现在事实相反
	If + did/were, 主+would/should/could/might do

take my seat 做我的座位
be busy doing sth. 忙于做某事
Will you be doing sth? 你会做某事吗?

** L41 Do you call that a hat?
rude [rud] adj.无礼的
mirror [ˈmɪrər] n.镜子
hole [hoʊl] n.孔
remark [rɪˈmɑrk] v.评说
remind [rɪˈmaɪnd] v.提醒
lighthouse [ˈlaɪtˌhaʊs] n.灯塔

remind sb. of sth./sb. 使某人想起某事

--------------------
need: 需要
needn't have done: 本不必如此,却做了,有后悔效果

regret doing sth. 后悔做某事
find sth. adj. 发现某事adj.

** L42 Not very musical
musical [ˈmjuzɪk(ə)l] adj.精通音乐的
market [ˈmɑrkət] n.市场,集市
snake [sneɪk] charmer [ˈtʃɑrmər] 玩蛇者(借音乐控制)
pipe [paɪp] n.(吹奏的)管乐器
tune [tun] n.曲调
glimpse [ɡlɪmps] n.一瞥
snake [sneɪk] n.蛇
movement [ˈmuvmənt] n.动作
continue [kənˈtɪnju] v.继续
dance [dæns] v.跳舞
obviously [ˈɑbviəsli] adv.显然
difference [ˈdɪf(ə)rəns] n.差别
Indian [ˈɪndiən] adj.印度的

watch a musical
play a tune
have a glimpse of sth./sb.
continue to do sth.
tell the difference from A and B / A be different from B

--------------------
have 万能动词

have a long walk
at the other side of sw.

** L43 Over the South Pole
pole [poʊl] n.(地球的)极
flight [flaɪt] n.飞行
explorer [ɪkˈsplɔrər] n.探险家
lie [laɪ] lay [leɪ] lain [leɪn] v.处于
serious [ˈsɪriəs] adj.严重的
point [pɔɪnt] n.地点
seem [sim] v.似乎,好像
crash [kræʃ] v.坠毁
sack [sæk] n.袋子
clear [klɪr] v.越过
aircraft [ˈerˌkræft] n.飞机
endless [ˈendləs] adj.无尽的
plain [pleɪn] n.平原

catch a flight
run into serious trouble
one point
It seems that ...

--------------------
- be able to: 有能力; 做成某事的案例
	+ can: 有能力(be able to的一般时);可能发生;
	+ could: 有能力(be able to的过去式);可能发生; 被允许; 没有!!!做成某事的案例
	+ was able to: 有能力(be able to的过去式); 做成某事的案例
	+ managed to do: 做成某事的案例
	+ 对比以上时态更多

order sb. to do sth.

** L44 Through the forest
forest [ˈfɔrəst] n.森林
risk [rɪsk] n.危险,冒险
picnic [ˈpɪknɪk] n.野餐
edge [edʒ] n.边缘
strap [stræp] n.带,皮带
possession [pəˈzeʃ(ə)n] n.所有
breath [breθ] n.呼吸
contents [kənˈtent] n.(常用复数)内有的物品
mend [mend] v.修理

take a risk
have a picnic
at the edge of a forest
in sb's possession
out of breath

rush up to sb.
catch up with sb.
go through
need doing sth.
run straight at sb.

** L45 A clear conscience
clear [klɪr] adj.无罪的,不亏心的
conscience [ˈkɑnʃəns] n.良心,道德心
wallet [ˈwɑlət] n.皮夹,钱夹
savings [ˈseɪvɪŋ] n.存款
villager [ˈvɪlɪdʒər] n.村民
percent [pərˈsent] 百分之...

I have a clear conscience
Are you 100 percent sure about this?

--------------------
be done

sb. learn that + 宾语从句
return sth. to sb.

** L46 Expensive and uncomfortable
unload [ʌnˈloʊd] v.卸(货)
wooden [ˈwʊd(ə)n] adj.木制的
extremely [ɪkˈstrimli] adv.非常,极其
occur [əˈkɜr] v.发生
astonish [əˈstɑnɪʃ] v.使惊讶
pile [paɪl] n.堆
woolen [ˈwʊlən] n.羊毛的
goods [ɡʊdz] n.(常用复数)货物,商品
discover [dɪˈskʌvər] v.发现
admit [ədˈmɪt] v.承认
confine [kənˈfaɪn] v.关在(一个狭小的空间里)
normal [ˈnɔrm(ə)l] adj.正常的,通常的

It occurred to sb. that ...
It occurred to sb. to do sth.
be astonished at sth.
admit doing sth.
sb. admit that...

--------------------
- 同位语: 补充说明的名词
I have just received a letter from my brother, Tim.

- 同位语从句: 完整(引导词不充当从句成分)句子补充说明名词.
No one could account for *the fact that* one of the boxes was extremely heavy.

What = the thing that/the person that
sb. account for the fact that + 句子

** L47 A thirsty ghost
thirsty [ˈθɜrsti] adj.贪杯的
ghost [ɡoʊst] n.鬼魂
haunt [hɔnt] v.(鬼)来访,闹鬼
block [blɑk] v.堵
furniture [ˈfɜrnɪtʃər] n.家具
whisky [ˈhwɪski] n.威士忌酒
suggest [səɡˈdʒest] v.暗示
shake [ʃeɪk] shook [ʃʊk] shaken [ˈʃeɪkən] v.摇动
accept [əkˈsept] v.接受

shake sb's head

be up for sale
hear sb./sth. doing sth.

** L48 Did you want to tell me something?
pull [pʊl] v.拔
cotton [ˈkɑt(ə)n] wool [wʊl] (羊毛棉)药棉
collect [kəˈlekt] v.搜集
collection [kəˈlekʃ(ə)n] n.收藏品,收集品
nod [nɑd] v.点头
meanwhile [ˈminˌhwaɪl] adv.同时

private collection

It is impossible for sb. to do
... rest for a while

** L49 The end of a dream
tired [ˈtaɪəd] adj.厌烦的
real [ˈriːəl; rɪəl] adj.真正的
owner [ˈəʊnə(r)] n.主人 own v.拥有
spring [sprɪŋ] n.弹簧
mattress [ˈmætrəs] n.床垫
gust [ɡʌst] n.一阵风
sweep [swiːp] swept [swept] swept v. 扫,刮
courtyard [ˈkɔːtjɑːd] n.院子
smash [smæʃ] v.碰碎,摔碎
miraculously [mɪˈrækjələsli] adv.奇迹般地
unhurt [ʌnˈhɜːt] adj.没有受伤的
glance [ɡlɑːns] v.扫视
promptly [ˈprɒmptli] adv.迅速地

get/be tired of sth./doing sth.
A gust of wind swept ...
in the courtyard
smash sth. to pieces
glance at sth.

--------------------!!!
分词作状语 没找到部分被动
1. (not) doing
	 主动进行/主动一般
	 (being) (not) + adj.
2. done
	 被动一般/被动完成/主动完成(少)
3. having done
	 主动完成(发生在主句之前)
	 having been + adj. (主句之前的状态)
4. having been done 在N2-69课
	 主动完成被动(发生在主句之前)

save up for year to do sth.
for the first time in sb's life
go to sleep

*** L01
6123456

*** L25
1. 6123456 + 6123546
2. conj.
	 1. and,but,because,so,as,for
	 2. both...and...,either...or...,neither...nor...
	 3. not only ..., but also.../but... as well

** L50 Taken for a ride
ride [raɪd] n.旅行
excursion [ɪkˈskɜrʒ(ə)n] n.远足
conductor [kənˈdʌktər] n.售票员
view [vju] n.景色

--------------------
do/does
am/is/are+doing
--------------------
prefer
	- prefer to do sth. = prefer doing sth. = I'd prefer to do sth
	- prefer a to b  &  prefer doing a to doing b
	- prefer to do a rather than (do) b.  &  I'd prefer to do a. rather than (do) b.

** L51 Reward for a virtue
reward [rɪˈwɔːd] n. v. 奖赏
virtue [ˈvɜːtʃuː] n. 美德
diet [ˈdaɪət] n. 节食
forbid [fəˈbɪd] forbade forbidden v. 禁止
hurriedly [ˈhʌrɪdli] adv. 匆忙的
embarrass [ɪmˈbærəs] v. 使尴尬
guiltily [ˈɡɪltɪli] adv. 内疚地
strict [strɪkt] adj. 严格的
occasionally [əˈkeɪʒnəli] adv. 偶尔地

expect/receive/give + reward
go on a diet = be on a diet
forbid sb. to do sth.
a be strict with b
--------------------
L3 & L27
was/were/did

First of all,...
write out a long list of ...
pay sb. a visit
was not surprised to see that...
It was obvious that...
ring the bell
** L52 A pretty carpet
temporarily [ˈtemprərəli] adv.暂时地
inch [ɪntʃ] n.英寸(度量单位)
space [speɪs] n.空间
actually [ˈæktʃuəli] adv.实际上

every inch of sth.
That's actually a good idea

--------------------
have been doing(不知持续与否):
	1. 过去进行的v.对现在有影响;
	2. 从过去持续(或重复!)到现在

get sth. in order
To make matters worse...
A short while ago...
gaze at sth.
in sb's spare time...
help sb. to do sth.

** L53 Hot snake
hot [hɒt] adj.带电的,充电的
fireman [ˈfaɪəmən] n.消防队员
cause [kɔːz] v.引起 n.原因
examine [ɪɡˈzæmɪn] v.检查
accidentally [ˌæksɪˈdentəli] adv.意外地,偶然地
remains [rɪˈmeɪnz] n.尸体,残骸
wire [ˈwaɪə(r)] n.电线
volt [vəʊlt] n.伏特(电压单位)
power line [ˈpaʊə laɪn] 电力线
solve [sɒlv] v.解决
mystery [ˈmɪst(ə)ri] n.谜
snatch [snætʃ] v.抓住
spark [spɑːk] n.电火花

electrical wire / electric wire
discover + cause
the remains of a snake
solve + problem/mystery
solve/remain + mystery

--------------------
did
have done
have been doing

find out
throw away

** L54 Sticky fingers
sticky [ˈstɪki] adj.粘的
finger [ˈfɪŋɡə(r)] n.手指
pie [paɪ] n.馅饼
mix [mɪks] v.混合,搅拌
pastry [ˈpeɪstri] n.面糊
annoying [əˈnɔɪɪŋ] adj.恼人的
receiver [rɪˈsiːvə(r)] n.电话的话筒
dismay [dɪsˈmeɪ] v.失望,泄气
recognize [ˈrekəɡnaɪz] v.认出,听出
persuade [pəˈsweɪd] v.说服,劝说
mess [mes] n.乱七八糟
doorknob [ˈdɔːnɒb] n.门把手
sign [saɪn] v.签字
register [ˈredʒɪstə(r)] v.挂号邮寄

stick to the plan
put my finger on it
point the finger at
be dismayed to do sth.
recognize the voice (of sb.)
persuade sb. (not) to do sth.
What a mess!
such a mess
Sign here
sign for sth.
a registered letter

send sb. to sp.
decide to do sth.
be busy doing sth.
be covered with sth.
take sb. st. to do sth.
hang up
What a mess!
sign for sth.

** L55 Not a gold mine
gold [ɡəʊld] n.金子
mine [maɪn] n.矿
treasure [ˈtreʒə(r)] n.财宝
revealer [rɪˈvi:lə] n.探测器
invent [ɪnˈvent] v.发明
detect [dɪˈtekt] v.探测
bury [ˈberi] v.埋藏
cave [keɪv] n.山洞
seashore [ˈsiːʃɔː(r)] n.海岸
pirate [ˈpaɪrət] n.海盗
arm [ɑːm] v.武装
soil [sɔɪl] n.泥土
entrance [ˈentrəns] n.入口
finally [ˈfaɪnəli] adv.最后
worthless [ˈwɜːθləs] adj.毫无价值的
thoroughly [ˈθʌrəli] adv.彻底地
trunk [trʌŋk] n.行李箱
confident [ˈkɒnfɪdənt] adj.有信心的
value [ˈvæljuː] n.价值

own + a gold mine
a treasure map
in a cave
near/to the seashore
pirate stories
arm sb./sth. with sth. =
sb. be armed with sth.
in dry soil
find / miss + entrance
You're worthless.
I'm not worthless.
car trunk
sb. be confident that ... + 句子
something of value

--------------------
would do VS used to do
	- 过去状态只用used to do
	- used to do包含现在不发生了
	- used to do讨论过去习惯行为(不重要)
where & whose 引导的定语从句

dreams come true...
be used to do sth.
fairly soon ...
I'm fairly certain that +句子
I'm fairly confident that + 句子

** L56 Faster than sound!
sound [saʊnd] n.声音
excitement [ɪkˈsaɪtmənt] n.激动,兴奋
handsome [ˈhænsəm] adj.漂亮的;美观的
Rolls-Royce [ˌrəʊlz ˈrɔɪs]
Benz [benz] n.
wheel [wiːl] n.轮子
explosion [ɪkˈspləʊʒ(ə)n] n.爆炸,轰鸣
course [kɔːs] n.跑道,行程
rival [ˈraɪv(ə)l] n.对手
speed [spiːd] v.疾驶
downhill [ˌdaʊnˈhɪl; ˈdaʊnhɪl] adv. adj.下坡

make a sound
hear a sound
on the course
speed it/things/this up
go downhill

--------------------
adj.er
adj.est
more + adj.
the most + adj.

a great deal of ... 不可数
a great many + 可数
break down
a be different form b.

** L57 Can I help you, madam?
madam [ˈmædəm] n.太太,夫人
jeans [dʒiːnz] n.牛仔裤
hesitate [ˈhezɪteɪt] v.犹豫,迟疑
serve [sɜːv] v.接待(顾客)
scornfully [ˈskɔːnfəli] adv.轻蔑地
punish [ˈpʌnɪʃ] v.惩罚
fur [fɜː(r)] n.裘皮
eager [ˈiːɡə(r)] adj.热切的,热情的

hesitate to do sth.
be eager to do sth.
ask/laugh/look at/ said + scornfully
look down on sb.

--------------------
in(可省) the way (+定从)... 状从 ?
	1. The assistant who served her did not like the way she was dressed.
	2. I don't like the way (that) you talk to me.
	3. We want to know the way (in which) you learn new words.

ask to do sth.
be dressed in ...
seek out
make sb. do sth.

** L58 A blessing in disguise?
blessing [ˈblesɪŋ] n.福分,福气
disguise [dɪsˈɡaɪz] n.伪装
tiny [ˈtaɪni] adj.极小的
possess [pəˈzes] v.拥有
cursed [kɜːst; ˈkɜːsɪd] adj.可恨的
increase [ɪnˈkriːs] v.增加
plant [plɑːnt] v.种植
church [tʃɜːtʃ] n.教堂
evil [ˈiːv(ə)l] adj.坏的
reputation [ˌrepjuˈteɪʃ(ə)n] n.名声
claim [kleɪm] v.以...为其后果
victim [ˈvɪktɪm] n.受害者,牺牲品
vicar [ˈvɪkə(r)] n.教区牧师
source [sɔːs] n.来源
income [ˈɪnkʌm] n.收入
trunk [trʌŋk] n.树干

It is a blessing that ...
what a blessing
God bless you
It's a blessing
a blessing in disguise
In one's possession
Go to church
Go to the church
have a good/bad reputation
Have a reputation for...
baggage claim
source of income/information

--------------------
be said to do...: 据说
It is said that...: 据说

强调句:
	- It is(was) + 强调部分 + that(who) + 剩余部分?
	- do/does/did + v.
被动: 复习L34 & L10

a number of
sb. point out that...

** L59 In or out?
bark [bɑrk] v. 狗叫
press [pres] v.按,压
paw [pɔ] n.脚
latch [lætʃ] n.门闩
expert [ˈekˌspɜrt] n.专家
develop [dɪˈveləp] v.养成
habit [ˈhæbɪt] n.习惯
remove [rɪˈmuv] v.拆掉,取下

become/be an expert at doing sth./sth.
have a habit of doing sth.
remove sth. from ...

--------------------
表目的
	- + do sth.
		to
		in order to
		so as to
  - + ...(句子)
		so that 目的状语从句
		in order that: 目的

complained of ...
complain that
spend st. doing sth.
train sb. to do sth.

** L60 The future
future [ˈfjutʃər] n.未来,前途
fair [fer] n.集市
fortune-teller [ˈfɔrtʃ(ə)n] n.算命人
crystal [ˈkrɪst(ə)l] n.水晶
relation [rɪˈleɪʃ(ə)n] n.亲属
impatiently [ɪmˈpeɪʃəntlɪ] adv.不耐烦的

in the future
at a village fair
crystal clear
a relation of yours

--------------------
A先B后
the moment A ... B...: 一A就B
	Everything stops the moment she walks in the room.
as soon as(主将从现): 一A就B(主从都表将来时,从句用现在时即可)
	As soon as the rain stops, we shall go out.
主将从现: 主从都表将来时,从句用现在时即可
	the moment/util/when/as soon as/while/before

** L61 Trouble with the Hubble
Hubble [hʌb(ə)l] n.哈勃
telescope [ˈteləˌskoʊp] n.望远镜
launch [lɔntʃ] v.发射
space [speɪs] n.空间
NASA [ˈnæsə] n. National Aeronautics and Space Administration
billion [ˈbɪljən] n.10亿
faulty [ˈfɔlti] adj.有错误的
astronaut [ˈæstrənɔːt] n.宇航员
shuttle [ˈʃʌt(ə)l] n.航天飞机
Endeavour [ɪn'devər] n."奋进"号
robot-arm [ˈroʊˌbɑt] [ɑrm] n.机器手
grab [ɡræb] v.抓
atmosphere [ˈætməˌsfɪr] n.大气层
distant [ˈdɪstənt] adj.遥远的
galaxy [ˈɡæləksi] n.星系
universe [ˈjunɪvərs] n.宇宙
eagle [ˈɪɡ(ə)l] eye 鹰眼

grab a beer/coffee

--------------------
will be doing
will have done
will have been doing: 动作持续(重复)到将来 ?

right from the start

** L62 After the fire
control [kənˈtroʊl] n.控制
smoke [smoʊk] n.烟
desolate [ˈdesələt] adj.荒凉的
threaten [ˈθret(ə)n] v.威胁
surrounding [səˈraʊndɪŋ] adj.周围的
destruction [dɪˈstrʌkʃ(ə)n] n.破坏,毁灭
flood [flʌd] n.洪水,水灾
authority [ɔˈθɔrəti] n.(常用复数)当局
grass-seed [ɡræs] [sid] n.草籽
spray [spreɪ] v.喷撒
quantity [ˈkwɑntəti] n.量
root [rut] n.根
century [ˈsentʃəri] n.世纪
patch [pætʃ] n.小片
blacken [ˈblækən] v.变黑,发黑

get it under control
be under control
threaten sb. with sth.
threaten to do sth.
have the authority to do sth.
a large/small quantity of sth.
take root
for centuries
a part of sth.

--------------------
had been doing: 1.过去A进行的v.对过去B有影响;2.过去A进行的v.持续(重复)到过去B

A short time before
for miles around
in place of...

** L63 She was not amused
circle [ˈsɜrk(ə)l] n.圈子
admire [ədˈmaɪr] v.赞美,钦佩
close [kloʊs] adj.亲密的
wedding [ˈwedɪŋ] n.婚礼
reception [rɪˈsepʃən] n.招待会
sort [sɔrt] n.种类

a large circle of friends
admire sb. for sth./doing sth.
close friend
at the reception
what sort of/what kind of...
all sorts of/ all kinds of...

--------------------
as: in the way or manner that 按照...方式
	You'll do as I say and ask no questions.
like
as if
as though

sense of humour/humor
make a speech
a large number of ...
on the way home

** L64 The Channel Tunnel
tunnel [ˈtʌn(ə)l] n.隧道
port [pɔrt] n.港口
ventilate [ˈvent(ə)lˌeɪt] v.通风
chimney [ˈtʃɪmni] n.烟囱
sea	level [ˈlev(ə)l] 海平面
double [ˈdʌb(ə)l] adj.双的
ventilation [ˌvent(ə)lˈeɪʃ(ə)n] n.通风
fear [fɪr] v.害怕
invasion [ɪnˈveɪʒ(ə)n] n.入侵,侵略
officially [əˈfɪʃ(ə)li] adv.正式地
connect [kəˈnekt] v.连接
European [ˌjʊrəˈpiən] adj.欧洲的
continent [ˈkɑntɪnənt] n.大陆

in the tunnel
above/below sea level
double check
Sb. fear that + 句子

--------------------
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
suggest that ... (should) do ...

it is possible to do sth...
a serve as b: A当作B
solve the problem of a ...
put forward a plan ...

** L65 Jumbo versus the police
versus [ˈvɜrsəs] prep.对
Christmas [ˈkrɪsməs] n.圣诞节
circus [ˈsɜrkəs] n.马戏团
present [ˈprezənt] n.礼物
accompany [əˈkʌmpəni] v.陪伴,随行
approach [əˈproʊtʃ] v.走进
ought [ɔt] modal verb.应该
weigh [weɪ] v.重
fortunate [ˈfɔrtʃənət] adj.幸运的

How much do you weigh?
It is fortunate that + 句子...

--------------------
should do/ought to do: 肯应该,否不应该
should have done/ought to have done: 本该做某事,却没有做,指责效果

be dressed up as...
set off
hold up the traffic/line
let sb. off
agreed to do sth.

** L66 Sweet as honey!
Lancaster [ˈlæŋkəstər] n.
bomber [ˈbɑmər] n.轰炸机
remote [rɪˈmoʊt] adj.偏僻的
Pacific [pəˈsɪfɪk] n.太平洋
damage [ˈdæmɪdʒ] v.毁灭
wreck [rek] n.残骸
rediscover [ˌridɪˈskʌvər] v.重新发现
aerial [ˈeriəl] adj.航空的
survey [ˈsɜrˌveɪ] n.调查
rescue [ˈreskju] v.营救
package [ˈpækɪdʒ] v.把...打包
enthusiast [ɪnˈθuziæst] n.热心人
restore [rɪˈstɔr] v.修复
imagine [ɪˈmædʒɪn] v.想象
packing case [ˈpækɪŋ] 包装箱
colony [ˈkɑləni] n.群
bee [bi] n.蜂
hive [haɪv] n.蜂房
preserve [prɪˈzɜrv] v.保护
beeswax [ˈbizˌwæks] n.蜂蜡

remote control
do a survey
Can you imagine that?
It's hard to imagine.
A colony of bees

--------------------
have sth. done = get sth. done: 1.使得某事被别人做;2.不幸的遭遇

over the years
in reasonable condition
be worth doing...
turn a into b.

** L67 Volcanoes
volcano [vɑlˈkeɪnoʊ] n.火山
active [ˈæktɪv] adj.活动的
Kivu ['kivu] n. Congo ['kɒŋɡəʊ] n. Kituro n.
erupt [ɪˈrʌpt] v.(火山)喷发
violently [ˈvaɪələntli] adv. violent [ˈvaɪələnt] adj.猛烈地,剧烈地
manage [ˈmænɪdʒ] v.设法
brilliant [ˈbrɪljənt] adj.精彩的
liquid [ˈlɪkwɪd] adj.液态的
escape [ɪˈskeɪp] v.n.逃脱
alive [əˈlaɪv] adj.活着的

What a brilliant idea!
That's brilliant!
--------------------
managed to do VS was able to do 成功做成了某事(事例) VS ~ + 过去有能力做成某事

name sth. a.
set up his camp/tent
sb. noticed that + sentence

** L68 Persistent
persistent [pərˈsɪstənt] adj.坚持的,固执的
avoid [əˈvɔɪd] v.避开
insist [ɪnˈsɪst] v.坚持做
cross [krɔs] v. across [əˈkrɔs] prep. 穿过

avoid doing sth.
insist on doing sth.
It is no use pretending that + sentence
prevent sb. from doing sth.
Fancy meeting you here.
--------------------
no matter how/what/where/whose/who/which/when ?
even though(although/though/as) VS even if

enjoy doing sth.
no matter how/what/where
follow sb. around
I was wondering.. + sentence
would you mind my doing...
finish doing sth.

** L69 But not murder
murder [ˈmɜrdər] n.谋杀
instruct [ɪnˈstrʌkt]  v.命令,指示
acquire [əˈkwaɪr]  v.取得,获得
confidence [ˈkɑnfɪdəns]  n. confident adj.信心
examiner [ɪɡˈzæmɪnər] n.主考人
suppose [səˈpoʊz] v.假设
tap [tæp] v.轻敲
react [riˈækt] v.反应
brake [breɪk] n.刹车 pedal n.踏板
mournful [ˈmɔrnfəl] adj.悲哀的

be instructed to do sth.
Let's suppose that...
tap on the window
--------------------
having been done

continue doing/ to do
be pleased with

** L70 Red for danger
bullfight [ˈbʊlˌfaɪt] n.斗牛 ring n.园形竞技场地
drunk [drʌŋk] n.醉汉
wander [ˈwɑndər] v.溜达,乱走
unaware [ˌʌnəˈwer] adj.不知道的,未察觉的
bull [bʊl] n.公牛 matador [ˈmætədɔr] n.斗牛士
remark [rɪˈmɑrk] n.v.评论;言语 make that stupid remark
apparently [əˈperəntli] adv.明显地
sensitive [ˈsensətɪv] adj.敏感的
criticism [ˈkrɪtɪˌsɪzəm] n.批评
charge [tʃɑrdʒ] v.冲上去
clumsily ['klʌmzɪli] adv.笨拙地
bow [baʊ] v.鞠躬
safety [ˈseɪfti] n.安全地带
sympathetically [ˌsɪmpə'θetɪklɪ] adv.同情地

be unaware of …
be aware/conscious of …
make that stupid remark
be sensitive about sth. accept criticism
charge at sb. = attack
for your safety
--------------------

be busy with sth.
at the time
catch sight of a.
grow quiet...
get close to a.
step aside
break into cheers
feel sorry for sb.
look on ...
out of the way …
turn sb’s attention to a.
once more

** L71 A famous clock
parliament n.议会,国会
erect v.建起
accurate adj.准确的
official n.adj.官员,行政人员
Greenwich n.
observatory n.天文台
check v.n.检查
microphone n.扩音器,麦克风
tower n.塔

make it official
double check
--------------------

all over the world
burn down
take its name from
be responsible for
be connected to
go wrong

** L72 A car called Bluebird
racing [ˈreɪsɪŋ] n.竞赛
per [pɜr] prep.每
Utah ['ju:ta:] n.犹他(美国州)
horsepower [ˈhɔrsˌpaʊr] n.马力
burst [bɜː(r)st] v.爆裂
average [ˈæv(ə)rɪdʒ] adj.平均的
footstep [ˈfʊtˌstep] n.足迹

burst into tears
follow in sb't footsteps
--------------------
have difficulty in doing sth.
be disappointed to learn that

** L73 The record holder
record-holder [ˈhoʊldər] n.记录保持者
truant [ˈtruənt] n.逃学的孩子
unimaginative [ˌʌnɪˈmædʒɪnətɪv] adj.缺乏想象力的
shame [ʃeɪm] n.惭愧,羞耻
hitchhike [ˈhitʃˌhaɪk] v.搭便车旅行
meantime [ˈminˌtaɪm] n.其间
lorry [ˈlɔri] n.卡车
border [ˈbɔrdər] n.边界
evade [ɪˈveɪd] v.逃避,逃离

play truant from school
be put to shame = put sb. to shame
shame on you
hitchhike to sw.
in the meantime
--------------------
612345+6123456(6123456)

over and over again

** L74 Out of the limelight
limelight ['laɪmlaɪt] n.舞台灯光
precaution [prɪˈkɔʃ(ə)n] n.预防措施
fan [fæn] n.狂热谜,迷
shady [ˈʃeɪdi] adj.遮荫的
sheriff [ˈʃerɪf] n.司法长官
notice [ˈnoʊtɪs] n.v.告示
sneer [snɪr] n.v.冷笑

stay out of the limelight
take precaution
sb. is a big/huge fan of a.
on such short notice
with a sneer/ sneer at sb.
--------------------
a party of
why don't we
carry sth. to sw.
make oneself comfortable 别客气
don't be too hard on us 
get out of here

** L75 SOS
thick [θɪk] adj.厚的
signal [ˈsɪɡnəl] n.信号
stamp [stæmp] v.踩,跺
helicopter [ˈhelɪˌkɑptər] n.直升飞机
scene [sin] n.现场
survivor [sərˈvaɪvər] n.幸存者

send a signal
stamp out the fire
arrive on the scene
--------------------
fly off course
cover sb./sth/ with a.
get adj.
It was not long before...

** L76 April Fool's Day
fool [ful] n.傻瓜
bulletin [ˈbʊlətɪn] n.新闻简报
announcer [əˈnaʊnsər] n.(电视,电台)播音员
macaroni [ˌmækəˈroʊni] n.通心面,空心面条
leading [ˈlidɪŋ] adj.主要的 + cause(s)
grower [ˈɡroʊr] n.种植者
splendid [ˈsplɛndid] adj.极好的 + idea/example/view/garden
stalk [stɔk] n.梗
gather [ˈɡæðər] v.收庄稼 thresh v.打(庄稼)
process [prəˈses] v.加工
Signor ['siːnjɔː] n.(意大利语)先生
present [ˈprezənt] adj.目前的
champion [ˈtʃæmpiən] n.冠军
studio [ˈstudiˌoʊ] n.播音室

on the bulletin board
leading cause of
What a splendid/brilliant idea!
--------------------
at the end of ...

** L77 A successful operation
mummy [ˈmʌmi] n.木乃伊
Egyptian [ɪ'dʒɪpʃ(ə)n] adj.埃及的
temple [ˈtemp(ə)l] n.庙
mark [mɑrk] n.斑点
plate [pleɪt] n.底片
disease [dɪˈziz] n.疾病
last [læst] v.持续
prove [pruv] v.显示出
resin [ˈrezɪn] n.树脂
skin [skɪn] n.皮,皮肤
section [ˈsekʃ(ə)n] n.切片
figure [ˈfɪɡjər] n.(人的)体形; 人像
normally [ˈnɔrm(ə)li] adv.通常地
survive [sərˈvaɪv] v.幸免于

have a rare disease
a section of ...
prove to be adj.
--------------------
非限定定语从句: 解释,补充,说明
	- which非限整句:
		+ 位置: 句尾
		+ 指代被修饰词
	- as非限整句
		- 位置: 前中后
		- 指代整句
	- 非限定只能who/which/whose
		- none of/neither of/any of/either of + which/whom
		- some of/many of/much of/(a) few of + which/whom
		- both of/ half of /each of/one of/two of + which/whom

--------------------
have an operation
died of ...
fall to pieces
cut it open

** L78 The last one
entitle [ɪnˈtaɪt(ə)l] v.以...为名
calm [kɑm] v.使镇静
nerve [nɜrv] n.神经
concentration [ˌkɑnsənˈtreɪʃ(ə)n] n.集中
suffer [ˈsʌfər] v.受苦
symptom [ˈsɪmptəm] n.症状
temper [ˈtempər] n.脾气
appetite [ˈæpəˌtaɪt] n.胃口
produce [prəˈdus] v.拿出
urge [ɜrdʒ] v.怂恿
satisfaction [ˌsætɪsˈfækʃ(ə)n] n.满足
delighted [dɪˈlaɪtəd] adj.欣喜的

entitle sb. to do sth.
calm down
keep calm
calm my nerve
have/get the nerve to do sth.: To draw upon one's courage or resolve to do something
lose sb's nerve: 失去某人的勇气
lose/break/have sb's concentration
suffer from
have a good/bad temper
lose sb's temper
have/get a good/great appetite
lose sb's appetite
urge sb. to do sth.
give him satisfaction
sb. be delighted that + ...
--------------------
light a cigarette
sb. be sure that + ...
keep on doing sth.
offer sb. sth.
make no effort to do sth.
a packet of...
return to normal...

** L79 By air
parent [ˈperənt] n.父母亲
flight [flaɪt] attendant [əˈtendənt] 空中乘务员
frightened [ˈfraɪt(ə)nd] adj.害怕,担惊
curious [ˈkjʊriəs] adj.急于了解,好奇的
bomb [bɑm] n.炸弹 plant v.安放

feel frightened
sb. be curious to find out + ...
plant a bomb
--------------------
Only部分倒装
1. Only(+其他部分)句首,并且不是修饰主语
	 Only police can come in. 不能倒装
2. 主句一般疑问句的语序
--------------------
a great deal
take charge of
be used to doing
take off
gain height
touch down
on board

** L80 The Crystal Palace
palace [ˈpæləs] n.宫殿
extraordinary [ɪkˈstrɔrd(ə)nˌeri] adj.不平常的,非凡的
exhibition [ˌeksɪˈbɪʃ(ə)n] n.展览
iron [ˈaɪrn] n.铁
various [ˈveriəs] adj.各种各样的
machinery [məˈʃinəri] n.机器
display [dɪˈspleɪ] n.展览
steam [stim] n.蒸汽
profit [ˈprɑfɪt] n.利润
college [ˈkɑlɪdʒ] n.学院

on show/on display
make a profit
go to college
--------------------
be made of
of all time
in all
** L81 escape
prisoner [ˈprɪz(ə)nər] n.囚犯
bush [bʊʃ] n.灌木丛
rapidly ['ræpɪdli] adv.迅速地
uniform [ˈjunɪˌfɔrm] n.制服
rifle [ˈraɪf(ə)l] n.来福枪,步枪
shoulder [ˈʃoʊldər] n.肩
march [mɑrtʃ] v.行进
boldly ['bəʊldli] adv.大胆地
blaze [bleɪz] v.闪耀
salute [səˈlut] v.行礼
elderly [ˈeldərli] adj.n.上了年纪的
grey [ɡreɪ] adj.灰白的
sharp [ʃɑrp] adj.猛烈的 blow n.打击

grow/change/move... + rapidly
with a sharp blow
--------------------
change into ...
up and down ...
sb. discovered that
stand to attention
knock him to the ground
** L82 Monster or fish?
monster [ˈmɑnstər] n.怪物
sailor [ˈseɪlər] n.海员
sight [saɪt] v.见到
creature [ˈkritʃər] n.动物,生物
peculiar [pɪˈkjuljər] adj.奇怪的,不寻常的
shining [ˈʃaɪnɪŋ] adj.闪闪发光的
oarfish ['ɔːfɪʃ] n.浆鱼

shining example
--------------------
claim to have done sth.
laugh at ...
it is (well) known that ...
at times
out at sea
in any way
it was found to be ...
a depth of ...
** L83 After the elections
election [ɪˈlekʃ(ə)n] n.选举
former [ˈfɔrmər] adj.从前的
defeat [dɪˈfit] v.打败
fanatical [fəˈnætɪk(ə)l] adj.狂热的
opponent [əˈpoʊnənt] n.反对者,对手
radical [ˈrædɪk(ə)l] adj.激进的
progressive [prəˈɡresɪv] adj.进步的
ex-  [eks] prefix 前...
suspicious [səˈspɪʃəs] adj.怀疑的

win the election
be fanatical about sth./doing sth.
--------------------
on duty
on the following day
love to do sth.
** L84 On strike
strike [straɪk] n.罢工
busman ['bʌsmən] n. bus driver公共汽车司机
state [steɪt] v.正式提出,宣布
agreement [əˈɡrimənt] n.协议
relieve [rɪˈliv] v.减轻
pressure [ˈpreʃər] n.压力,麻烦
extend [ɪkˈstend] n.程度
volunteer [ˌvɑlənˈtɪr] v.n.自动提出,自愿
gratitude [ˈɡrætɪˌtud] n.感激
press [pres] n.新闻界
object [ɑbˈdʒekt] v. objection n.不赞成,反对

go on strike
sb. have stated that + ...
agreement is reached about sth.
reach an agreement
sb. be relieved to hear that + ...
relieve pressure
under a lot of pressure
to some extend
volunteer to do sth.
expressed sb.'s gratitude to sb.
sb. have objected that + ...
object to sth./sb.
--------------------
be due to do = be going to do

--------------------
be due to do sth.
pass/take the test
** L85 Never too old to learn
inform [ɪnˈfɔrm] v.告诉,通知
headmaster [ˈhedˌmæstər] n.校长
contribute [ˈkɑntrɪˌbjut] v.捐助,援助
gift [ɡɪft] n.礼物,赠品
album [ˈælbəm] n.签名簿,相册
patience [ˈpeɪʃəns] n.耐心
encouragement [ɪnˈkʌrɪdʒmənt] n.鼓励
farewell [ferˈwel] n.告别
honour [ˈɑnər] honor n.敬意
coincidence [koʊˈɪnsɪdəns] n.巧合
total [ˈtoʊt(ə)l] n.总数
devote [dɪˈvoʊt] v.致力于
gardening [ˈɡɑrd(ə)nɪŋ] n.园艺
hobby [ˈhɑbi] n.爱好,嗜好

sb. inform sb. that + ...
make a contribution
contribute to sth.
lose sb's patience
have a lot of patience
give sb. encouragement
in one's honor: it is done specially to show appreciation of them
It is a curious coincidence that + ...
a total of ...
devote oneself to sth./doing sth.
--------------------
mark the occassion
remember sb. for sth.
** L86 Out of control
swing [swɪŋ] swung v.转向
speedboat [ˈspidˌboʊt] n.快艇
desperately [ˈdesp(ə)rət(ə)li] adv.绝望地
companion [kəmˈpænjən] n. 同伴,伙伴
water [ˈwɔtər] ski [ski] (由快艇牵引)滑水
buoy [ˈbui] n.浮标
dismay [dɪsˈmeɪ] n.沮丧
tremendous [trəˈmendəs] adj.巨大的
petrol [ˈpetrəl] n.汽油
drift [drɪft] v.漂动,漂流
gently [ˈdʒentli] adv.缓慢地,轻轻地

sb. noticed with dismay that + ...
at tremendous speed
--------------------
come away
move in a circle
be used up 
before long
** L87 a perfect alibi
alibi [ˈælɪˌbaɪ] n.不在犯罪现场
commit [kəˈmɪt] v.犯(罪,错)
inspector [ɪnˈspektər] n.探长
employer [ɪmˈplɔɪər] n.雇主
confirm [kənˈfɜrm] v.确认,证实
suggest [səɡˈdʒest] v.提醒
truth [truθ] n.真相

have a alibi
commit a murder
sb. confirm that + ...
Are you suggesting + ...
tell the truth
--------------------
on time
** L88 Trapped in a mine
trap [træp] v.陷入,使陷入困境
surface [ˈsɜrfəs] n.地面,表面
explosive [ɪkˈsploʊsɪv] n.炸药
vibration [vaɪˈbreɪʃ(ə)n] n.震动
collapse [kəˈlæps] v.n.坍塌
drill [drɪl] v.n.钻孔
capsule [ˈkæpˌsjul] n.容器
layer [ˈleɪr] n.层
beneath [bɪˈniθ] prep.在...之下
lower [ˈloʊr] v.adj.放下,降低
progress [prəˈɡres] v.n.进展,进行
smoothly [ˈsmuːðli] adv.顺利地

on the surface
in a special capsule
layers of
a layer of
make progress
go/run smoothly
--------------------
wish型虚拟语气: 从句: should(可省略) do

lose one's life
As it is...
enable sb. to do sth.
keep in touch with ...
run out of ...
lose heart ...
cause sb./sth/ to do sth.
** L89 A slip of tongue
slip [slɪp] n.小错误
comedy [ˈkɑmədi] n.喜剧
present [ˈprezənt] v.演出 adj.出席,到场的
queue [kju] v.n.排队
dull [dʌl] adj.枯燥,无味
artiste [ɑrˈtist] n.artist 艺人
advertiser [ˈædvərˌtaɪzər] n.报幕员

a slip of the tongue
a comedy show
hold up the queue
--------------------
do anything to do sth.
the news get around
feel disappointed
at the beginning of a.
burst out laughing
** L90 What's for supper?
chip [tʃɪp] n.油煎土豆片
overfish [ˌoʊvə'fɪʃ] v.过度捕捞
giant [ˈdʒaɪənt] adj.巨大的
terrify [ˈterəˌfaɪ] v.吓,使恐怖
diver [ˈdaɪvər] n.潜水员
oil rig [ɔɪl] [rɪɡ] 石油钻塔
wit [wɪt] n.(复数)理智,头脑
cage [keɪdʒ] n.笼
shark [ʃɑrk] n.鲨鱼
whale [hweɪl] n.鲸
variety [vəˈraɪəti] n.品种
cod [kɒd] n.鳕 skate n.鳐
factor [ˈfæktər] n.因素
crew [kru] n.全体工作人员

be scared/frightened out of sb's wits
a variety of
--------------------
it comes as a surprise to learn that + ...
protect a. from b.
in length
the (total) absence of ...
as a result

** L91 Three men in a basket
balloon [bəˈlun] n.气球
royal [ˈrɔɪəl] adj.皇家
spy [spaɪ] v.侦察
track [træk] n.轨迹,踪迹
binoculars [bɪˈnɑkjələrz] n.望远镜

spy on sb./sth.
keep track of
--------------------
seem to be doing ...
make for sw.
make out
soon afterwards
be called in (to do)
** L92 Asking for trouble
fast [fæst] adv.熟(睡)
ladder [ˈlædər] n.梯子
shed [ʃed] n.棚子
sarcastic [sɑrˈkæstɪk] adj.讽刺的,讥笑的
tone [toʊn] n.语气,腔调

fast asleep
Are you being sarcastic?
Don't take that tone with me!
--------------------
hate to do sth.

** L93 A noble gift
noble [ˈnoʊb(ə)l] adj.高尚的,壮丽的
monument [ˈmɑnjəmənt] n.纪念碑
statue [ˈstætʃu] n.雕像 liberty n.自由
present [ˈprezənt] v.赠送
sculptor [ˈskʌlptər] n.雕刻家
actual [ˈæktʃuəl] adj.实际的,真实的
copper [ˈkɑpər] n.铜
support [səˈpɔrt] v.支持,支撑
framework [ˈfreɪmˌwɜrk] n.构架,框架
transport [trænsˈpɔrt] v.运送
site [saɪt] n.场地
pedestal [ˈpedɪst(ə)l] n.底座

a noble gift/man
camp site
--------------------
at the entrance of ...
take sth. to pieces

** L94 Future champions
instruct [ɪnˈstrʌkt] v.指导,传授
Los Angeles
reluctant [rɪˈlʌktənt] adj.勉强的,不愿意的
weight [weɪt] n.重物
underwater [ˌʌndə(r)ˈwɔːtə(r)] adj.水下的
tricycle [ˈtraɪsɪk(ə)l] n.三轮车
compete [kəmˈpit] v.比赛,对抗
yard [jɑrd] n.码
gasp [ɡæsp] v.喘气

be instructed in doing sth.
be reluctant to do sth.
compete against
--------------------
sb./sth. proved that + ...
hold sb's breath
be accustomed to doing
be popular with ...
be lined up
** L95 A fantasy
fantasy [ˈfæntəsi] n.幻想故事
ambassador [æmˈbæsədər] n.大使
frightful [ˈfraɪtf(ə)l] adj.可怕的,令人吃惊的
fire [faɪr] extinguisher [ɪkˈstɪŋɡwɪʃər] 灭火器
drily [ˈdraɪli] adv.冷淡地,鼓噪无味地
embassy [ˈembəsi] n.大使馆
heaven [ˈhev(ə)n] n.天,天堂
basement [ˈbeɪsmənt] n.地下室
definitely [ˈdefənɪtli] adv.肯定地
post [poʊst] v.派任
shot [ʃɑt] n.子弹

live in a fantasy world
Good heavens!
fire a shot
--------------------
get into such a mess
set sth. on fire
go on doing sth.

** L96 The dead return
festival [ˈfestɪv(ə)l] n.节目
lantern [ˈlæntə(r)n] n.灯笼
spectacle [ˈspektək(ə)l] n.景象,壮观,场面
moving [ˈmuvɪŋ] adj.

make a spectacle of oneself
--------------------
return to sp.
be expected to be
sth. is laid out
it is considered unlucky for sb. doing
be placed into

* NCE3 
** L01 A puma at large
puma [ˈpjumə] n.美洲狮
spot [spɑt] v.n.发现
evidence [ˈevɪdəns] n.证据
accumulate [əˈkjumjəˌleɪt] v.积累
oblige [əˈblaɪdʒ] v.使...感到必须
hunt [hʌnt] n.v.追猎
blackberry [ˈblækˌberi] n.黑莓
human [ˈhjumən] being [ˈbiɪŋ] n.人类
corner [ˈkɔrnər] v.使走投无路
trail [treɪl] n.一串
print [prɪnt] n.v.印痕
cling [klɪŋ] clung clung v.粘
convince [kənˈvɪns] v.使...信服
somehow [ˈsʌmhaʊ] adv.不知怎么搞地
disturb [dɪˈstɜrb] v.令人不安

spot sb. doing sth. 发现某人正在做某事
feel obliged to do sth. 感到必须做某事
a trail of: a series of 一系列
cling to sb./sth. 粘在某人/某物上
sth. convinced sb. that + ... 某事使某人信服...
sb. was/were convinced that + ... 某人确信...
It is disturbing to think that + ... 想到...令人很不安
--------------------
at large: 在逃
be found in: 产于
take sth. seriously: 严肃对待某事
sth. proved adj.: 某事证明怎么样
sb. confirmed that + ...: 某人确定
claim to have done sth. 声称做过某事
find sb. doing sth. 发现某人在做某事
go on: continue

spotted: seen
accumulate: pile up
obliged to: bound to
claimed: stated
extraordinarily similar: surprisingly alike
immediately: at once
convinced: sure

** L02 Thirteen equals one
equal [ˈikwəl] v. equally adv.
vicar [ˈvɪkər] n.
raise [reɪz] v. + money
torchlight [ˈtɔrtʃˌlaɪt] n. torch n.
cause [kɔz] n.原因,理由 v.导致,引起
wake up with a start
bell [bel] n. ring v.
catch sight of a figure: 看到人影
recognize [ˈrekəɡˌnaɪz] v.
local grocer [ˈɡroʊsər] n.

A. be equal to B.
for one cause or another: for one reason or another
wake up with a start: 惊醒
catch sight of sb./sth.
--------------------
1. be always doing sth.: 频率过高令人生厌(非绝对,用于肯定句)
2. whatever:
	 - emphasize the speaker's surprise/astonishment/anger/irritation/dismay
	 - on earth/ in the world/ fucking
3. do/does/did: 强调v.
4. was/were doing 表礼貌
	 - I was hoping to do sth.
	 - I was just wondering + ...
	 - I was thinking + ...
--------------------
for one cause or another
get enough money to do sth.
sb. be armed with sth.: 装备
what's going on: 发生了什么
recognize A as B
give sb. a surprise
I'm glad that + ...
get used to sth.: 习惯于

** L03 An unknown goddess
goddess [ˈɡɑdəs] n. god
archaeologist [ˌɑrkiˈɑlədʒɪst] n. archaeology n.考古学家
Aegean [i:'dʒi:ən] adj.
explore [ɪkˈsplɔr] v. explorer n. exploration n.
promontory [ˈprɑmənˌtɔri] n.
prosperous [ˈprɑsp(ə)rəs] adj.
civilization [ˌsɪvɪlɪˈzeɪʃ(ə)n] n.
storey [ˈstɔri] n. story 层
drainage [ˈdreɪnɪdʒ] n.
worship [ˈwɜrˌʃɪp] n.v.崇拜(神)
sacred [ˈseɪkrəd] adj.神圣的
fragment [ˈfræɡmənt] n.碎片
remains [rɪˈmeɪnz] n.遗迹
classical [ˈklæsɪk(ə)l] adj.古文化的
reconstruct [ˌrikənˈstrʌkt] v. re... 修复
rest [rest] n.v. hip n.放置
full-length adj.拖地长的
graceful [ˈɡreɪsfʊl] adj.
identity [aɪˈdentəti] n.

a is/was used as a place of worship
on a/the promontory: 在海角
drainage system: 下水道
sacred room/template/place: 神圣的房间
have a rest
identity card: 身份证
--------------------
sb. make a (adj.) discovery of sth.
a. be equipped with b.: 配置
equip sb. with sth.
be used as
date from ... date back to ...:追溯
happen to do sth.:  you do it by chance
be amazed to find that + ...
turn out to be sth.: 原来是某物
despite/despite the fact that ...:尽管

** L04 The double life of Alf Bloggs
manual [ˈmænjuəl] adj. n.
collar [ˈkɑlər] n.
sacrifice [ˈsækrɪˌfaɪs] v. n.
privilege [ˈprɪvəlɪdʒ] n.
dustman [ˈdʌstmən] n.
corporation [ˌkɔrpəˈreɪʃ(ə)n] n.
overalls [ˈoʊvərˌɔl] n.
shower [ˈʃaʊər] n.
secret [ˈsikrət] n.
status [ˈstætəs] n.

do manual work ...
white-collar/blue-collar workers
make a sacrifice:
	to surrender or give up, or permit injury or disadvantage to, for the sake of something else 
sacrifice a. for b.
have the privilege of doing sth.: an opportunity to do something special or enjoyable
take a shower
keep a secret
the secret of success
It's between you and me
social status: 社会地位
status quo: 保持原样
keep the status quo
--------------------
These days ...
Far more adj./n.: 非常...
A. be referred to as ... B.: regrad A. as B.
refer to A. as B.: regrad A. as B.
for the simple reason that + ...
Such is human nature, that + ...
be willing to do sth.
give rise to: lead to; cause
too embarrassed to do sth.
be dressed in: wear
change into + [clothes]
half as much as ...
from now on
call me/him/her a.

** L05 The facts
editor [ˈedɪtər] n. edit v.
extreme [ɪkˈstrim] n.
statistics [stə'tɪstɪks] n. statistic 数据
journalist [ˈdʒɜrn(ə)lɪst] n.新闻记者
president [ˈprezɪdənt] n.
palace [ˈpæləs] n.
publish [ˈpʌblɪʃ] v.
fax [fæks] n.v.
impatient [ɪmˈpeɪʃ(ə)nt] adj.
fire [faɪr] v.
originally [əˈrɪdʒən(ə)li] adv.

go to extreme(s) to do sth.
publish + a book/an article/report
send sb. a fax
get impatient
get/be fired

--------------------
部分倒装:
	否定词 + 一般疑问句
	- example: Not only have I done it, ...
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until

--------------------
provide sb. with sth.
sb. be instructed to do sth.
instruct sb. to do sth.
write an article on/about sth.
find out sth.: to discover, learn, or verify something
sb. take a long time to do sth.
go to press: 
inform sb. that + ...: 

** L06 Smash-and-grab
smash-and-grab
arcade [ɑrˈkeɪd] n.拱廊
jewellery [ˈdʒuːəlri] n. jewelry
necklace [ˈnekləs] n. a string of jewels, beads etc or a thin gold or silver chain to wear around the neck
ring [rɪŋ] n.
background [ˈbækˌɡraʊnd] n.
velvet [ˈvelvət] n.天鹅绒
headlight [ˈhedˌlaɪt] n.车头灯
blare [bler] v.to make a very loud unpleasant noise
staff [stæf] n.
raid [reɪd] n.v. a short attack on a place by soldiers, planes, or ships, intended to cause damage but not take control
scramble [ˈskræmb(ə)l] v. to climb up, down, or over something quickly and with difficulty, especially using your hands to help you
fantastic [fænˈtæstɪk] adj.
ashtray [ˈæʃtreɪ] n. a small dish where you put used cigarettes

smash sth. to pieces
grab a beer/coffee
go to the arcade
background music
scrambled eggs
at a fantastic speed: at a good speed
That's fantastic
--------------------
独立主格
--------------------
only just: Just a moment earlier
come to a stop
be too busy doing sth. to do sth.
[money] + worth of + n.: eg. thousands of pounds worth of diamonds
help oneself to sth.:
	1. to serve or provide oneself with (food, etc.)
	2. to take without asking or being given; steal.

** L07 Mutilated ladies
mutilate [ˈmjut(ə)lˌeɪt] v. damage someone’s body, especially by cutting or removing part of it
chew [tʃu] v. chew up  chewing gum
fiance [ˌfiən'seɪ] n.
microwave [ˈmaɪkrəˌweɪv] n.
oven [ˈʌv(ə)n] n.
safekeeping [seɪfˈkipɪŋ] n.
Newcastle [ˈnjuːkɑːsl] n.
identify [aɪˈdentɪˌfaɪ] v.
spokeswoman [ˈspoʊksˌwʊmən] n.

chewing gum: 口香糖
for safekeeping: 为了妥善保管
--------------------
deal with
go doing sth.: 去做某事
imagine sb's dismay when + ...
so long as + ..., sb. will do sth.

** L08 A famous monastery
monastery [ˈmɑnəˌsteri] n. St. Bernard
pass [pæs] n. a high road or path that goes between mountains to the other side
watchdog [ˈwɑtʃˌdɔɡ] n.
rashly adv.
enclosure [ɪnˈkloʊʒər] n. an area surrounded by a wall or fence, and used for a particular purpose
monk [mʌŋk] n. a member of an all-male religious group that lives apart from other people in a monastery
privacy [ˈpraɪvəsi] n.  the state of being free from public attention
skier [ˈskiər] n.
Easter [ˈiːstə(r)] n.

Can I get some privacy?
--------------------
connect a. to b. = a. be connected to b.
for hundreds of years
Now that + ...(原因状从)
be in difficulty: run into serious trouble
attempt to do sth.: try to do sth.
receive a warm/cold welcome

** L09 Flying cats
fascinate [ˈfæsɪˌneɪt] v. you are attracted to them and think they are extremely interesting
affectionate [əˈfekʃənət] adj. showing in a gentle way that you love someone and care about them
mysterious [mɪˈstɪriəs] adj.
submissive [səbˈmɪsɪv] adj. always willing to obey someone and never disagreeing with them, even if they are unkind to you
feline [ˈfiˌlaɪn] adj.  relating to cats or other members of the cat family, such as lions
independence [ˌɪndɪˈpendəns] n.
high-rise adj. tall
windowsill [ˈwɪndoʊˌsɪl] n. a shelf fixed along the bottom of a window
paratrooper [ˈperəˌtrupər] n. a soldier who is trained to jump out of a plane using a parachute
squirrel [ˈskwɪrəl] n.
air-resistance [rɪˈzɪstəns] n.
impact [ɪmˈpækt] n.

gain its independence: it has its own government and is not ruled by any other country
have/make an impact on: 对...有影响
--------------------
the 比较级(eg. more) ..., the 比较级(eg.more) ...: 比较级在句子中做比较成分
yet...: conj.; 表惊讶的转折
--------------------
lead a adj. life: live a adj. life
learn to do sth.
a good deal of/a great deal of un.: VS a lot of; VS a great number of
be based on: to use information to support or prove an opinion or belief
make a study of sth: research
a period of + st.: eg. a period of five months
have sth. in common: eg. have one experience in common
died from(事故) / died of(病)
there is no shortage of sth.:
It seems that + ...
be likely to do sth.: they will very probably do it

** L10 The loss of the Titanic
Southampton [saʊθ'hæmptənˌ saʊ'θæmp-]
colossal [kəˈlɑs(ə)l] adj.
watertight [ˈwɔtərˌtaɪt] adj.
compartment [kəmˈpɑrtmənt] n.
flood [flʌd] v.
float [floʊt] v.
tragic [ˈtrædʒɪk] adj.
liner [ˈlaɪnər] n. a large ship for passengers
voyage [ˈvɔɪɪdʒ] n.
iceberg [ˈaɪsˌbɜrɡ] n.
lookout [ˈlʊkˌaʊt] n. someone whose duty is to watch carefully for something, especially for danger
collision [kəˈlɪʒ(ə)n] n.
narrowly [ˈneroʊli] adv.
miss [mɪs] v.
slight [slaɪt] adj.
tremble [ˈtremb(ə)l] v.  to shake slightly in a way that you cannot control, especially because you are upset or frightened
faint [feɪnt] adj.
horror [ˈhɔrər] n.  to sb's horror  horror movie
abandon [əˈbændən] v.
plunge [plʌndʒ] v.
lifeboat [ˈlaɪfˌboʊt] n.
--------------------
a crew of: eg. ~ workers; ~ painter; ~ waiters
be regarded as + adj./n.
give an alarm: give a warn of danger
in time: not late; punctual.
realized to his horror that: 
give an order

** L11 Not guilty
guilty [ˈɡɪlti] adj.
tolerant [ˈtɑlərənt] adj.
declare [dɪˈkler] v.
hardened [ˈhɑː(r)d(ə)nd] adj. a criminal, police officer etc who has had a lot of experience of things that are shocking and is therefore less affected by them
professional [prəˈfeʃ(ə)nəl] adj. n.
smuggler [ˈsmʌɡ(ə)lər] n.
officious [əˈfɪʃəs] adj.
confidently ['kɒnfədəntlɪ] adv.
dreadful [ˈdredfəl] adj. extremely unpleasant
pounce [paʊns] v.to suddenly move forward and attack someone or something, after waiting to attack them
perfume [ˈpɜː(r)fjuːm] n.
sarcastically adv.
exempt [ɪɡˈzempt] adj.
import [ɪmˈpɔrt] duty n.
gel [dʒel] n.胶
mixture [ˈmɪkstʃər] n.
unscrew [ʌnˈskru] v.
nostril [ˈnɑstrəl] n.
chalk [tʃɔk] n.small sticks of a white or coloured substance like soft rock, used for writing or drawing
baggage [ˈbæɡɪdʒ] n.

feel guilty
be tolerant of: willing
be exempted from: they do not have to follow it or do it
mixture of a. and b.
--------------------
be made to do sth.: to be forced to do something
on the other hand/on the one hand
light up:  suddenly become animated with liveliness or joy
be greeted by sth.: to welcome someone with particular words or a particular action

** L12 Life on a desert island
desert [ˈdezərt] island
unrealistic [ˌʌnriəˈlɪstɪk] adj.
paradise [ˈperəˌdaɪs] n.
wretched [ˈretʃəd] adj. someone who is wretched is very unhappy or ill, and you feel sorry for them
starve [stɑrv] v.
element [ˈelɪmənt] n.
opportunity [ˌɑpərˈtunəti] n.
coral [ˈkɔrəl] n.珊瑚
Virgin [ˈvɜrdʒɪn] Islands
Miami [maɪ'æmi] n.
dinghy [ˈdɪŋi] n.皮艇
Caribbean [ˌkerɪˈbiən] n.
spear [spɪr] gun: 鱼叉枪
lobster [ˈlɑbstər] n.
tanker [ˈtæŋkər] n.
genuinely [ˈdʒenjuɪnli] adv.

have an opportunity to do sth.: have the privilege of doing sth.
an element of truth/danger: 有点..
starve to death: 饿死
sb. be genuinely sorry that + ...

--------------------
wish that sb. did: 现在虚拟
wish that sb. had done: 过去虚拟

--------------------
formed an unrealistic picture of sth.:对某事有不切实际的想象
imagine sth./sb. to be n./adj.: 把某事想象成
a sort of
wish that + ...
load a. with b.: 用B装载A
As sb. put it: 如某人所说

** L13 It's only me
costume [ˈkɑstum] n.
consist [kənˈsɪst] v.
sheet [ʃit] n.a large piece of thin cloth that you put on a bed to lie on or lie under
effective [ɪˈfektɪv] adj.
comfortable [ˈkʌmfərtəb(ə)l] adj.
storeroom [ˈstɔrˌrum] n.
electricity [ˌilekˈtrɪsəti] n. meter=metre n. 电表
pace [peɪs] n.
flee [fli] fled v. to leave somewhere very quickly, in order to escape from danger
slam [slæm] v. close

consist of ...:  to be formed or made up of 
make yourself comfortable: to sit, lie, move, or behave in a such a way that you are relaxed and free from pain
at your own pace: you do it at a speed that is comfortable for yo
The pace of life
--------------------
fancy dress party: 化妆舞会
be impatient to do sth.
let out a cry: 大叫一声

** L14 A noble gangster
gangster [ˈɡæŋstər] n.
Chicago [ʃɪ'kɑ n.
protection [prəˈtekʃən] n.
promptly [ˈprɑmptli] adv. immediately/on time
destroy [dɪˈstrɔɪ] v.
remarkable [rɪˈmɑrkəb(ə)l] adj.unusual or surprising and therefore deserving attention or praise
band [bænd] n. a group of musicians, especially a group that plays popular music
Florence ['flɔrəns] n. Florentine n.
city-state n.城邦
hire [ˈhaɪr] v. rent
prince [prɪns] n. the son of a king, queen, or prince
funeral [ˈfjun(ə)rəl] n.
dedicate [ˈdedɪˌkeɪt] v.献身于
memory [ˈmem(ə)ri] n.
valiant [ˈvæliənt] adj.very brave, especially in a difficult situation

need protection:
provide protection:
for your own protection: keeping yourself safe from injury or damage
a band of: a group of
give him a state funeral
dedicate yourself/your life to sth.: sacrifice a. for b.; devote oneself to sth./doing sth.
dedicate sth. to sb.: 
devote oneself to sth./doing sth.
in memory of sb. / to the memory of sb.: 
--------------------
when引导的定语从句
	1. 先行词必须为时间(time, day, year...)
	2. when必须在从句中充当[6]的成分.如果从句是[1][3],那么是which引导定语从句,而不是when
	3. 在非书面语中,用that或者直接去掉
	4. 注意区分when时间状语 VS when定语从句
	5. prep.+which=when, 类似的还有方式状语
whenever:
	1. when的强调
	2. every time or any time
if真实条件句和虚拟语气: 过去真实条件句和现在虚拟格式一致,只能结合上下文看.
	If did... , would do...
--------------------
There was a time when + ...
pay money to sb.
large sums of money
put sb. out of business: make (someone) go bankrupt, lose their shop or company
as long ago as: in the distant past
make the remarkable discovery that + ...
would rather do A. than do B.
make a name for himself: to become well-known or famous; rise to fame
come to do sth.: they do it at the end of a long process or period of time
A be known to B as C: B calls A as C
A be known as B:
be at war with ...: eg. China is at war with America.
in times of peace
offer to do sth.
make money
regard A as B: refer to A as B

** L15 Fifty pence worth of trouble
appreciate [əˈpriʃiˌeɪt] v.
pocket [ˈpɑkɪt] money: 零花钱
rattle [ˈræt(ə)l] v. if you rattle something, or if it rattles, it shakes and makes a quick series of short sounds
thrifty [ˈθrɪfti] adj. using money carefully and wisely 
nephew [ˈnefju] n.
bounce [baʊns] v. it immediately moves up or away from a surface after hitting it
pavement [ˈpeɪvmənt] n. sidewalk
stick [stɪk]-stuck-stuck v.卡住
fire brigade n. 消防队
grease [ɡris] n. a thick oily substance that is put on the moving parts of a car, machine etc to make it run or move smoothly 

I appreciate your honesty.
	understanding/interesting/concern/support/patience/trust/time/help/it/that ...
--------------------
supply of sth.: 某物的供给
go a long way: 维持很长时间
be exchanged for sth.  exchange a. for b.
fill up a. with b. 用B充满A
find one's way: reach a destination, especially with some difficulty or not as a matter of course
advise sb. to do sth.
On one's way to sp.
roll up one's sleeves: 卷起某人的袖子
What is more=what's more: 而且
rub a. with b.: 用B擦A
a special type of sth.
hear about sth.
reward sb. with sth.

** L16 Mary had a little lamb
prize [praɪz] adj. very good or important
tie [taɪ] v.
accuse [əˈkjuz] v.
theft [θeft] n. an act of stealing something
deny [dɪˈnaɪ] v. SAY STH IS NOT TRUE
ashamed [əˈʃeɪmd] adj. feeling very sorry and embarrassed because of something you have done
apologize [əˈpɒləˌdʒaɪz] v.
dye [daɪ] v. to give something a different colour using a dye

prize money
tie sb. to sth. = sb. be tied to sth.: 把某人绑某物上
accuse sb. of doing sth.
deny doing.../sb. deny that + ...
be ashamed of sth./doing sth./having done sth.
apologize to sb. (for doing sth.)
dye something + some-color.: eg. dye his hair red
--------------------
tell sb. about sth.
It's ture that + ..., but + ...
be astonished to find (that) + ...

** L17 The longest suspension bridge in the world
suspension [səˈspenʃ(ə)n] n. suspend v.悬挂,悬职
agreeable [əˈɡriəb(ə)l] adj. situation n.宜人的风景
locate [ˈloʊˌkeɪt] v. location n.坐落
immortal [ɪˈmɔrt(ə)l] adj. so famous that it will never be forgotten
span [spæn] n.  a period of time between two dates or events
cable [ˈkeɪb(ə)l] n. a plastic or rubber tube containing wires that carry telephone messages, electronic signals, television pictures etc
concrete [ˈkɑŋˌkrit] n.
length [leŋθ] n.长
estimate [ˈestɪmət] v.
capacity [kəˈpæsəti] n.
immensity [ɪˈmensəti] n.巨大
elegant [ˈelɪɡənt] adj.
faintly [ˈfeɪntli] adv.轻微地

agreeable/pleasant + situation/man/day
be located in/near
a span of ...: ...的跨度
life span: 寿命
a length of/lengths of + rope/pipe/wire: 一段绳/管/线
It is estimated that + ...
sb. estimates that + ...
--------------------
little/not much/not everything is known about a.: 对A知之甚少
describe a. as b.
in the midst of
by no means: not possible
be considered to be adj./n.
sth. be named after sb.: 某物以某人命名
join a. to b. = connect a. to b.
be taken into account = take sth. into account 考虑某事
a height of ...: ...的高度
A. be suspended from B.: A悬挂于B
be packed with ...: to fill something with things or people of a particular type
a third of sth: 某物的1/3
fulfill sb's dream: something or someone made your dream come true

** L18 Electric current in modern art
current [ˈkʌrənt] n.  electric current 电流
sculpture [ˈskʌlptʃə] n. an object made out of stone, wood, clay etc by an artist
mistaken [miˈsteɪk] adj.
gallery [ˈɡæləri] n. a large building where people can see famous pieces of art
exhibit [ɪɡˈzɪbɪt] n.v. exhibition n. to show something in a public place so that people can go to see it
oddly [ˈɑdli] adv. in a strange or unusual way
attach [əˈtætʃ] v. to fasten or connect one object to another 
sphere [sfɪr] n. a ball shape
magnetize [ˈmæɡnəˌtaɪz] v.
repel [rɪˈpel] v.
flicker [ˈflɪkər] v. to burn or shine with an unsteady light that goes on and off quickly
emit [ɪˈmɪt] v. to send out gas, heat, light, sound etc
flash [flæʃ] v.
prehistoric [ˌpriˈhɪstɔrɪk] adj.
electronic [ˌilekˈtrɑnɪk] adj.
peculiar [pɪˈkjuljər] adj. strange, unfamiliar, or a little surprising
shock [ʃɑk] v.n.震惊
emotionally [ɪˈmoʃənlɪ] adv. relating to your feelings or how you control them

make a sculpture / create a sculpture: 制作雕塑
be mistaken about sth./sb.: confused or wrong about
Oddly enough, + ...: Strangely, unexpectedly 
be attached to sb./sth. = attach a. to b.: 把A绑到B上
get an electric shock: 被电击
receive an electric shock
give you electric shocks
--------------------
not any more = not any longer = no longer
The idea that + ... is mistaken: 想法xx是错的
take no/ a great/an interest in
in response to sth.: 回应某事
be/sound/look/seem familiar to sb.: 对某人看起来很熟悉
go mad
on and off: 断断续续
It was rather like ...: 这很像...
seem adj.(designed) to do sth.: be designed to do sth.
be designed to do sth.: seem designed to do sth.

** L19 A very dear cat
dear [dɪr] adj.
kidnapper ['kɪdnæpə(r)] n.绑架者
considerable [kənˈsɪd(ə)rəb(ə)l] adj.
wealthy [ˈwelθi] adj. having a lot of money, possessions etc
orderly [ˈɔrdərli] adj. arranged or organized in a sensible or neat way
disappearance [ˌdɪsəˈpɪrəns] n. disappear v. 出现
anonymous [əˈnɑnɪməs] adj. unknown by name
ransom [ˈrænsəm] n.
cardboard [ˈkɑrdˌbɔrd] n. stiff thick brown paper, used especially for making boxes
withdraw [wɪðˈdrɔ] withdrew withdrawn
punctually adv. on time
astound [əˈstaʊnd] v. astounded adj.

be dear to somebody: 对某人很宝贵
a considerable amount/number of sth.: a lot of
in an orderly fashion/manner: in a well-organized and controlled way
anonymous letter/(phone) call
remain anonymous: 匿名
a ransom of + (money): eg. a ransom of $100
It astounded sb. that + ...
--------------------
share sth. with sb.
take a short/long walk
get worried
in safe hands: they are being looked after by a reliable person and will not be harmed
at first: 一开始
go to the police
make sth. clear: 把某事搞的很清楚
change sb's mind: 改变主意
follow sb's instructions: 遵从某人的指示
keep sb's word: 说话算数
sure enough: 当然了
sb. explained that + ...
Considering + n., + ...: 考虑到
in more ways than one: to have more than one meaning

** L20 Pioneer pilots
pioneer [ˌpaɪəˈnɪr] n. someone who is important in the early development of something, and whose work or ideas are later developed by other people
lord [lɒrd] n. a man who has a rank in the aristocracy
Calais [kæ'leɪˌ 'kæleɪ] n.
overland [ˈoʊvərˌlænd] adj. adv.across land, not by sea or air
--------------------
as if/though 虚拟语气

--------------------
offer sth. to sb. = offer sb. sth.: provide sth. for sb.; provide sb. with sth.
a prize of + (money): eg. a prize of $1,000
make an attempt to do sth.: attempt to do sth; try to do sth.
attempt to do sth.
be forced to do sth.: be made to do sth.
be picked up by ...: be rescued by
on the same day: 
It looked as if/though + 虚拟句:
	eg.	It looked as if there would be an exciting race across the Channel.
	eg.	It looked as though there would be an exciting race across the Channel.

** L21 Daniel Mendoza
boxing [ˈbɑksɪŋ] n.
boxer [ˈbɑksər] n.
bare [ber] adj. not covered with clothes
prizefighter [ˈpraɪzˌfaɪtər] n.
crude [krud] adj. rude and offensive
marquis [mɑrˈki] n. has a rank between duke and earl
technically [ˈteknɪkli] adv.
science [ˈsaɪəns] n.
popularity [ˌpɑpjəˈlerəti] n.
adore [əˈdɔr] v. to love someone very much and feel very proud of them
alike [əˈlaɪk] adv. in a similar way  adj. very similar not before noun
fame [feɪm] n.
eminent [ˈemɪnənt] adj. an eminent person is famous, important, and respected
bitterly [ˈbɪtərli] adv. very
bet [bet] bet betted v. to risk money on the result of a race, game, competition, or other future event
academy [əˈkædəmi] n.
academy [əˈkædəmi] adj. spending or costing a lot of money, especially more than is necessary or more than you can afford
poverty [ˈpɑvərti] n.

with sb's bare hands: using only one's hands and no tools or weapons
Technically speaking, + ...: According to the rules
gain/grow/increase in popularity:  something or someone is liked, enjoyed, or supported
great minds think alike: 英雄所见略同
rise to fame: make a name for oneself
quarrel/complain/be disappointed ... + bitterly:
bet ($) on sth.: 在某事打赌多少钱
I bet + ...: 我赌 + ...
live in poverty: 生活贫困
--------------------
Because of + n.
be born in + (year): 出生于
draw up: 起草
a set of sth.: a series of; a trail of
change a. into b.: 把A变成B,而 exchange A for B.是交换
bring a. to b.: eg. brought science to the game
in sb's day: 在他的时代
be quick to do sth.: 很快做某事
in fact
turn against sb.: 与某人反目
It is clear that + ...: 很明显
settle the argument: 解决争端
It was not until [stp.] that + ...:
	stp. can not only be 'in 1790' but also 'third match' as well
as much as ...   half as much as: 一样多,一半多
be in debt: owe money

** L22 by heart
run [rʌn] ran run v.
lines  [laɪn] n.台词
part [pɑrt] n. role n.角色
falter [ˈfɔltər] v.支吾,结巴说
cast [kæst] cast cast v. to choose which people will act particular parts in a play, film etc 
aristocrat [əˈrɪstəˌkræt] n.someone who belongs to the highest social class
imprison [ɪmˈprɪz(ə)n] v. to put someone in prison or to keep them somewhere and prevent them from leaving
Bastille [bæ'stiːl] n.
jailer [ˈdʒeɪlər] n.
colleague [ˈkɒˌliːɡ] n.someone you work with – used especially by professional people
curtain [ˈkɜrt(ə)n] n. a piece of hanging cloth that can be pulled across to cover a window, divide a room etc
reveal [rɪˈvil] v.
cell [sel] n. a small room in a prison or police station where prisoners are kept
blank [blæŋk] adj.
squint [skwɪnt] v. to look at something with your eyes partly closed in order to see better
dim [dɪm] adj.
sire [saɪr] n.
proceed [prəˈsid] v.

play the role of: 扮演...的角色
sb. be cast in the role of = cast sb. in the role of: 委派某人演...角色
the curtain goes up/rises/comes down/falls: 窗帘上/下
a blank sheet of paper: 一张白纸
squinte at sb./sth.: 眯眼看某人/某物
in the dim light: 在昏暗的光线下
proceed to do sth.: 继续做某事
--------------------
insist/suggest that + ... (should) do (虚拟语气)

--------------------
for days/hours/years on end: 一连好几天/小时/年
in many ways: to a great degree
be required to do sth.: be ordered to do sth.
expect sb. to do sth./ sb. be expected to do sth.: want sb. to do sth.
learn/know sth. by heart: to have learned or memorized something completely and perfectly
have cause to do sth.: have a reason to do sth.
sb. insisted that + ...(should) do (虚拟语气) 要求
sb. insisted that + ...(非虚拟) 认为
be written out in full: 被写的满满当当
play a joke on sb.: to confuse someone or cause problem for them
present sth. to sb.: provide sth. for sb.
look on: 旁观(看热闹)
at last
be anxious to do sth. = be eager to do sth. = can't help doing sth.
stare at: 盯着
read sth. to sb.
much to sb's sth.[surprise/amusement/dismay/disappoint]: 使某人...

** L23 One man's meat is another's poison
illogical [ɪˈlɑdʒɪk(ə)l] adj.
octopus [ˈɑktəpəs] n. a sea creature with eight tentacles (=arms)
delicacy [ˈdelɪkəsi] n. something good to eat that is expensive or rare
repulsive [riˈpʌlsiv] adj. extremely unpleasant, in a way that almost makes you feel sick 
stomach [ˈstʌmək] n. turn v.
fry [fraɪ] v. to cook something in hot fat or oil, or to be cooked in hot fat or oil
fat [fæt] n.
abuse [əˈbjus] n.
snail [sneɪl] n.
associate [əˈsoʊʃiət] v.
luxury [ˈlʌkʃ(ə)ri] n.
despise [dɪˈspaɪz] v. to dislike and have a low opinion of someone or something
appeal [əˈpil] v.
shower [ˈʃaʊər] n.
stroll [stroʊl] n.
impulse [ˈɪmˌpʌls] n. a sudden strong desire to do something without thinking about whether it is a sensible thing to do
dozen [ˈdʌz(ə)n] n.  twelve
fancy [ˈfænsi] v. to like or want something, or want to do something 

One man's meat is another man's poison: 萝卜青菜,各有所爱
it is illogical to do sth.: 做某事不和逻辑
turn sb's stomach: 真的反胃
sick to my stomach: feeling very disgusted or angry.
animal fat
a. received more abuse than b.: a比b受到更多争议
associate a. with b.: connect a. to b.
appeal to sb.:  to attract, please, or interest
After a heavy shower ...: 下大雨后
be in the shower: 淋雨
take a shower: to wash oneself in the shower
take a stroll / go for a stroll: take a short walk
have the impulse to do sth.:
	a sudden strong wish or need to do something, without stopping to think about the results
dozens of sth./sb.: 几十个
--------------------
for instance: for example
at the idea of ...: 一想起
The sad truth is that + ...: 悲伤的事实是
be brought up to do sth.: 从小一直做某事
stick to sth.: continue doing or using (something) especially when it is difficult to do so
notice sb. doing sth.
be delighted to do sth.: be willing to do sth.; be ready to do sth.
stay to dinner = stay for dinner: 留下来吃晚餐
to sb's dismay: disappointment
take possession of sp.: occupy sp.

** L24 A skeleton in the cupboard
skeleton [ˈskelɪt(ə)n] n. the structure consisting of all the bones in a human or animal body
seemingly [ˈsimɪŋli] adv. apparently 似乎,好像
respectable [rɪˈspektəb(ə)l] adj. someone who is respectable behaves in a way that is considered socially acceptable
conceal [kənˈsil] v.
vivid [ˈvɪvɪd] adj. vividly adv.
dramatic [drəˈmætɪk] adj. drama n. dramatically adv.  great and sudden
ruin [ˈruɪn] v.
heroine [ˈheroʊɪn] n. hero
fiction [ˈfɪkʃ(ə)n] n. books and stories about imaginary people and events
varying [ˈveriɪŋ] adj. different
medicine [ˈmedɪsɪn] n.医学
guest [ɡest] room n.客房
unpack [ʌnˈpæk] v.
stack [stæk] v. to make things into a neat pile, or to form a neat pile
underclothes [ˈʌndərˌkloʊðz] n. = underwear
drawer [ˈdrɔːə(r)] n.
petrify [ˈpetrɪˌfaɪ] v. extremely frightened, especially so frightened that you cannot move or think
dangle [ˈdæŋɡ(ə)l] v. to hang or swing loosely, or to make something do this
sway [sweɪ] v. to move slowly from one side to another
unsympathetic [ˌʌnsɪmpəˈθetɪk] adj.
medical [ˈmedɪk(ə)l] adj.

a skeleton in the cupboard/closet: they are keeping secret a bad or embarrassing fact about themselves
sth. be concealed from sb. = conceal sth. from sb.
drama queen: 戏精
ruin my day
science fiction
to varying degrees: 多种程度上
in the drawer/ from the drawer: 在抽屉
be petrified of sth.: 被某物惊呆
medical student/school
--------------------
It is all very well (and good)..., but not in reality + ...
make one's hair stand on end: 使某人汗毛耸立
in sb's youth
show sb. to sp.: 带某人去某地
bring sth. with sb.: 随身携带某物
it give sb. the impression that + ...
be about to do sth.: 要做某事
leap out at sb.: 扑向某人
once upon a time: 曾经

** L25 The Cutty Sark
impressive [imˈprɛsiv] adj. makes you admire it because it is very good, large, important etc
steamship [ˈstimˌʃɪp] n.
vessel [ˈves(ə)l] n. a ship or large boat
era [ˈɪrə] n.时代
Java [ˈdʒɑvə] n.
rudder [ˈrʌdər] n. a flat part at the back of a ship or aircraft that can be turned in order to control the direction in which it moves
roll [roʊl] v.滚动
steer [stɪr] v. to control the direction a vehicle is going, for example by turning a wheel
temporary [ˈtempəˌreri] adj.
plank [plæŋk] n.木板
fit [fɪt] v.安装
equator [ɪ'kweɪtə(r)] n.赤道
delay [dɪˈleɪ] n.延误

a new era/ the beginning/end of an era
a. be fitted with b. A被装上了B
delay in doing sth.
--------------------
a. be replaced by b.
take the lead (in doing sth.) lose one's lead: 领先做某事 失去领先
be struck by: to be very impressed by 
from side to side: moving to the left and then to the righ
it become impossible to do sth.
with great difficulty
There is a danger that + ...: 有...的危险
call in on/at: visit
by now: 目前为止
There is no doubt that + ...: 毫无疑问

** L26 Wanted: a large biscuit tin
influence [ˈɪnfluəns] v.n.
pride [praɪd] v.
taste [teɪst] n.v.品味
exert [ɪɡˈzɜrt] v.施加
subtle [ˈsʌt(ə)l] adj.微妙的
advertiser [ˈædvərˌtaɪzər] n.
classify [ˈklæsɪˌfaɪ] v. to decide what group something belongs to 
magic [ˈmædʒɪk] adj.
sample [ˈsæmp(ə)l] n.
devise [dɪˈvaɪz] v.设计
capture [ˈkæptʃər] v.吸引,赢得
manufacturer [ˌmænjəˈfæktʃərər] n.
wheelbarrow [ˈhwilˌberoʊ] n. a small cart with one wheel and two handles that you use outdoors to carry things, especially in the garden
boot [but] n.
ingredient [ɪnˈɡridiənt] n.食材,成分
crane [kreɪn] n.  a large tall machine used by builders for lifting heavy things 
anticipate [ænˈtɪsɪˌpeɪt] v. to expect that something will happen and be ready for it

bad/good/positive etc. influence (on sb.)
have an influence on sb./sth.
be influenced by ...
pride oneself on (doing) sth. = be pround of
have good/bad taste in sth. 对某物有好的品味
exert a subtle/some influence on/over sb. 在某人上施加微妙的影响
have a subtle mind: 拥有敏锐的思想
classify a. as/under b.: 把A归类为B
say the magic word
free samples of sth.: 某物的免费的样品
devise a way/plan to do sth.:设计出方法/计划去做某事
capture the attention of sb. = capture sb's attention
in the boot of sb's car: 在车的后备箱
It is anticipated that + ...: 据估计
sb. anticipate that + ...: 某人预估
--------------------
as引导的倒装句 表 让步
	- Much as ..., ...
	- adj./n./v. + as ...,句子: adj-est.去the, n.去冠, v.用原型
	- 为什么要试试自己查语法书
--------------------
avoid being done: 避免被做某事
be free to do sth.: 免于做某事
in sb's effort to do sth.: 在某人努力做某事下
get sth. for nothing: 免费得到东西
enable sb. to do sth.
a. has made it possible for sb. to do sth.
come along: arrive
buy sth. from sb.

** L27 Nothing to sell and nothing to buy
philosopher [fɪˈlɑsəfər] n.
wisdom [ˈwɪzdəm] n.
priest [prist] n. vicar 神父
spiritual [ˈspɪrɪtʃuəl] adj.
grudge [ɡrʌdʒ] v.n. a feeling of dislike for someone because you cannot forget that they harmed you in the past
surgeon [ˈsɜrdʒən] n. a doctor who does operations in a hospital
passer-by ['pɑːsə] n. passers-by
dignity [ˈdɪɡnəti] n.尊严
deliberately [dɪˈlɪb(ə)rətli] adv.
consequence [ˈkɑnsəkwəns] n.
afflict [əˈflɪkt] v.折磨
ease [iz] n. easy to do it
nature [ˈneɪtʃər] n.
contempt [kənˈtempt] n.轻蔑
envious [ˈenviəs] adj. wanting something that someone else has

question/doubt the wisdom of (doing) sth.
give sb. spiritual comfort
grudge doing sth.: 不愿意做某事
have/hold a grudge against sb.: 对某人怀恨在心
die/treat/do sth. with dignity: 有尊严地xx
have consequences
be afflicted with/by sth.: 被某事折磨
with great/considerable ease
love of nature: 热爱大自然
speak of/treat sb./sth. with contempt: 轻蔑对待/谈起某人
be/feel/get/become envious of sb.
--------------------
live by doing sth.: 以做某事为生
in the light of sth./in light of: 鉴于某事
in terms of sth.: 从某物来说
It is difficult to do sth.
seem to be/do sth.
be the exception to the rule: 规则的例外情况
in doing sth.: 结果是
choose to do sth.
be free from sth.: 摆脱某事
in the open (air): 露天

** L28 Five pounds too dear
wares [wer] n. silverware n.器物  银器
anchor [ˈæŋkər] v.n.
deck [dek] n.
tempt [tempt] v.鼓动
bargain [ˈbɑrɡən] v.n.讨价还价
disembark [ˌdɪsɪmˈbɑrk] v. to get off a ship
assail [əˈseɪl] v.骚扰
marble [ˈmɑrb(ə)l] n.大理石
inscribe [ɪnˈskraɪb] v.雕刻
favour [ˈfeɪvər] n. favor 优惠
gesticulate [dʒəˈstɪkjəˌleɪt] v.做手势
outrageous [aʊtˈreɪdʒəs] adj.不公的
thrust [θrʌst] v.猛塞

on the deck
tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.
bargain with sb.
make a bargain with ...
be assailed by sb.
A. be inscribed on B. A被雕刻在B上
as a special/personal favor (to sb.): 作为对某人的特殊优惠
do me a favor: 帮我个忙
it is outrageous (that) + ...: xx使非常不公的
thrust sth. into sw. (especially my hands): 猛塞某物在某处 
--------------------
speed to sp.
sb. have no intention of doing sth.
I can't conceal the fact that + ...
sb. be impressed by sth.
go to great lengths to do sth.: 努力做某事
prove that + ...
go to great lengths to prove that + ...: 努力证明
get rid of sb.: 摆脱某人
at the base of sth.: 在...的基础上
let me have it: 给我吧
indicate that + ...: 表示...
reduce the price to $: 减少价格到...
throw up one's arms: 举起胳膊
get back to sp.: 回到某地
fill a. with b.: 用B充满A
to this day: 直到今天 by now

** L29 Funny or not?
largely [ˈlɑrdʒli] adv.很大程度上
comic [ˈkɑmɪk] adj.n.漫画
universal [ˌjunɪˈvɜrs(ə)l] adj.普遍的
comedian [kəˈmidiən] n.喜剧演员
distasteful [dɪsˈteɪstfəl] adj.讨厌的
pester [ˈpestər] v.纠缠
dread [dred] v.惧怕
recovery [rɪˈkʌvəri] n.康复
plaster [ˈplæstər] n.熟石膏
console [ˈkɑnˌsoʊl] v.安慰
hobble [ˈhɑb(ə)l] v.瘸着腿走
compensate [ˈkɑmpənˌseɪt] v.补偿
mumble [ˈmʌmb(ə)l] v.喃喃自语

comic book/movie/novel
have a universal appeal: 有通用的吸引力
pester sb. to do sth.
dread doing sth. 惧怕做某事
dread sb. doing sth.
make a complete/quick/speedy/slow recovery: xx恢复
console sb./yourself that + ... 安慰某人道 + ...
compensate (for sth.) = make up for: 补偿
--------------------
whether/whether or not .../whether...or not 主从 VS 让步状语
	1. 主从Whether引导, 不可被if代替, 在句中做1的成分
	2. whether引导让步状语从句, 在句子中状语的成分
have: stay 原则:万能+猜
--------------------
be bound up with: 与...密切相关
find it hard to do sth.
make sb. laugh to tears: 使某人笑出眼泪
stem from ...: 源于
come into fashion
base a. on b.: 建立A.在B.上
judge for yourself: 自己判断
do one's best (to do sth.): try my best to do sth.
take heart: 获得鼓舞
be good for sb.
in the process: 在过程中

** L30 The death of a ghost
labourer ['leɪbərər] n. laborer
overnight [ˈoʊvərˌnaɪt] adv.
hay [heɪ] n.
corn [kɔrn] n.谷物
moonlight [ˈmunˌlaɪt] n.
conscientious [ˌkɑnʃiˈenʃəs] adj.认真的
suspect [ˈsʌˌspekt] v.
desert [ˈdezərt] v.开小差
regiment [ˈredʒɪmənt] n.团(军队)
action [ˈækʃ(ə)n] n.战斗
recluse [ˈrekˌlus] n.隐士

stay overnight in the hay: to sleep somewhere for one night
in the moonlight
suspect (that) + ...
a regiment of ...: 一团/群...
be killed in action: 战斗中牺牲
--------------------
every time: 时间状语 = whenever
wake up to find that + ...
old elder eldest: 只能sb.,不能接sth.,也不能接than
	older oldest: 既能sb.,也能sth.
--------------------
for years
stay up (overnight): 熬夜
it became an accepted fact that + ...
be supposed to be/do sth.
remain in doing: proceed to do sth.
none other than: 不是其他人是
think it one's duty to do sth.
keep sb. in hiding: 藏起某人
find it impossible to do sth.

** L31 A lovable eccentric
lovable [ˈlʌvəb(ə)l] adj.
eccentric [ɪkˈsentrɪk] n.
disregard [ˌdɪsrɪˈɡɑrd] v. to ignore something or treat it as unimportant
convention [kənˈvenʃ(ə)n] n.习俗,风俗
conscious [ˈkɑnʃəs] adj. aware 感觉到的
invariably [ɪnˈveriəbli] adv.总是
routine [ˌruˈtin] n.常规;惯例
shrewd [ʃrud] adj.精明的
eccentricity [ˌeksenˈtrɪsəti] n.怪癖
legendary [ˈledʒənˌderi] adj.传奇般的
snob [snɑb] n.势力小人
intensely [ɪn'tensli] adv.强烈地
bedraggled [bɪˈdræɡ(ə)ld] adj.拖泥带水的
dump [dʌmp] v.把...砰的抛下
apologetic [əˌpɑləˈdʒetɪk] adj.道歉的
reprimand [ˈreprɪˌmænd] v.训斥
stage [steɪdʒ] v.n.暗中策划
elaborate [ɪˈlæb(ə)rət] adj.精心构思的

disregard social conventions
be conscious of (doing) sth.
sb. be conscious that + ...
daily routine
dump sth. on sth.
be apologetic about/for sth.
reprimand sb. for (doing) sth.
elaborate plan/design/meal
--------------------
draw attention to sb.
win sb. sth.: 赢得某人某物
add a. to b.
up to the time of sth.: 到...的时候
go on foot
be caught in: 淋雨
sb. request to do sth.
present sb. with sth.
invite sb. to do sth.

** L32 A lost ship
salvage [ˈsælvɪdʒ] v.n. 救助;打捞
Barents  n.
sunken [ˈsʌŋkən] adj.沉没的
cargo [ˈkɑrɡoʊ] n.一车/船货物
bullion [ˈbʊljən] n. un. bars of gold or silver
scour [skaʊr] v. 搜寻
chest [tʃest] n.
contents [kənˈtent] n.
belongings [bɪˈlɔŋɪŋz] n. 所有物
item [ˈaɪtəm] n.
cruiser [ˈkruzər] n.巡洋舰
find [faɪnd] n. thing
log [lɔɡ] book: 日志本
piece [pis] v. 拼成整体
convoy [ˈkɑnˌvɔɪ] n. 护航
torpedo [tɔrˈpidoʊ] v. n. 用鱼雷攻击
submarine [ˈsʌbməˌrin] n. 潜水艇
naval [ˈneɪv(ə)l] adj. navy n.海军的
ministry [ˈmɪnɪstri] n. (政府的)部
--------------------
salvage operation
a cargo of: 一货...
piece together: 拼装起来
in a convoy: 在护航中
a naval officer: 
--------------------
sb. be under the impression that + ...
together with: 除了...还有
come to light: 披露出来

** L33 A day to remember
prelude [ˈpreljud] n. 前奏
unforeseen [ˌʌnfɔrˈsin] adj.意料之外的
series [ˈsɪriz] n.系列
catastrophe [kəˈtæstrəfi] n.大灾
crockery [ˈkrɑkəri] un.陶器
suburb [ˈsʌˌbɜrb] n.郊区
collide [kəˈlaɪd] v.猛撞
learner [ˈlɜrnər] n.初学者
panic [ˈpænɪk] n.
windscreen [ˈwɪn(d)ˌskrin] n. windshield 挡风玻璃
alongside [əˈlɔŋˌsaɪd] prep. adv.在...的旁边
slide [slaɪd] slid slid v.滑
stray [streɪ] adj. 迷失的,离群的
confusion [kənˈfjuʒ(ə)n] n. 混乱
greedily [ˈɡridɪlɪ] adv. devour v. 狼吞虎咽地吃

a prelude to sth.
unforeseen + changes/problems/circumstances: 不可预见的改变/问题/情形
a series of
be a catastrophe for sb.: 对某人来说大灾祸
in the suburbs/ a suburb of city: 在城区的郊区
collide with=run into: 碰撞
get into a panic
draw up alongside sb.: 超车某人
slide off/open: 滑走/开
stray dogs: 流浪狗
There is some confusion about sth.
--------------------
get out of control
What invariably happens is that + ...
set up a chain of reactions
keep an eye on sb.: 留意某人
be/speak/talk on the phone: 在打电话
hang up (on sb.): 挂电话
attend to sb./sth.: 照料某人
reduce sb. to tears:  they make you feel so unhappy that you cry
on a big/large/small scale: 大规模地
drawing up alongside sb.: 超车某人
rush hour: 高峰期
pull up: 停车 (of a vehicle) come to a halt.
all of a sudden = suddenly
pile up: accumulate
get the traffic on the move: 使得交通动起来
sweep up: 打扫干净
benefit from sth.: 得益于某事

** L34 A happy discovery
antique [ænˈtiːk] n.
fascination [ˌfæsɪˈneɪʃ(ə)n] n.
forbidding [fəˈbɪd] adj.
muster [ˈmʌstər] v.
pretentious [prɪˈtenʃəs] adj.
labyrinth [ˈlæbəˌrɪnθ] n.
musty [ˈmʌsti] adj.
rarity [ˈrerəti] n.
assorted [əˈsɔrtəd] adj.
junk [dʒʌŋk] n.
litter [ˈlɪtər] v.
dedicated [ˈdedɪˌkeɪtəd] adj.
bargain [ˈbɑrɡən] hunter
dealer [ˈdilər] v.
cherish [ˈtʃerɪʃ] v.
amply ['æmpli] adv.
masterpiece [ˈmæstərˌpis] n.
mere [mɪr] adj.
prise [praɪz] v.
carve [kɑrv] v.
dagger [ˈdæɡər] n.
miniature [ˈmɪnɪtʃər] adj.
composition [ˌkɑmpəˈzɪʃ(ə)n] n.

antique shop/store/desk/jewelry
hold/have a fascination for sb./sth.
forbidding place/look
muster (up) the courage/confidence/to do sth.
in the labyrinth of sth.
junk mail
be littered with sth.
sb. cherish the hope that + ...
The mere fact that + ... + 23456
prise sth. open
carve a. from/out of b.=a. be carved from/out of b.
--------------------
There is always hope that + ...
by chance
above all
be bent on doing sth.
sb. cherish the hope that + ...
described to sb. what/how + 宾从 = describe sth. to sb.
pick up
sb. can't/couldn't be bothered to do sth.
beg sb. to do sth.
at the bottom of ...

** L35 Justice was done
justice [ˈdʒʌstɪs] n.
court [kɔrt] n. law n.
innocence [ˈɪnəs(ə)ns] n.
undertake [ˌʌndərˈteɪk] v.承担;着手做
arduous [ˈɑrdjuəs] adj.艰苦的
abstract [æbˈstrækt] adj. concept n.
mete [mit] out 给予,处置
interference [ˌɪntərˈfɪrəns] n.干涉
accord [əˈkɔrd] n.一致
premises [ˈpremɪsəz] n.房屋
convert [ˈkɑnˌvɜrt] v.转变
disused [dɪsˈjuzd] adj.废弃的
fireplace [ˈfaɪrˌpleɪs] n.壁炉
muffle [ˈmʌf(ə)l] v.捂住
chip [tʃɪp] v.砍
blacken [ˈblækən] v.使变黑
emerge [ɪˈmɜrdʒ] v.(从某处)出现

justice has been done/served: 正义得到伸张
court of law; courts of law: 法庭
prove sb's innocence
undertake a task/a project/research/a study/a journey: 承担重任
arduous task of doing sth./arduous journey: 做某事的重任
go through/embark on/begin arduous journey: 开始艰辛的旅程
understand + abstract concept
interference in sth.: 对某事的干涉
Sorry for the interference, + ...
I hope you don't mind the interference, but + ...
of sb's/sth's own accord: you do it because you want to, without being asked or forced
on the premises of a.: 在A的前提下
convert a. to/into b.: 把A变成B
emerge from sp.: 从某处出现
--------------------
however = no matter how 让步状语
get + done 被动
--------------------
beyond doubt
make mistakes
There are rare instances when + ...: 有极少例子当...
cease to do: 不再去做
be independent of: 独立于
in part: 部分地
run to tell sb.: 
ring up: call sb. by phone
tap at sth.: 敲击某物
listen for ...: 为...而听
be unable to do sth.
break into sp.: 破门而入
be handed over to sb.: 被移交给

** L36 A chance in a million
credulous [ˈkredjələs] adj. 轻信的
improbable [ɪmˈprɑbəb(ə)l] adj. 不大可能的
obscure [əbˈskjʊr] adj. 不起眼的
maidservant [ˈmeɪdˌsɜrvənt] n. 女仆
presume [prɪˈzum] v. 假定
wickedly ['wɪkɪdli] adv. 心眼坏地
plot [plɑt] v. 密谋
downfall [ˈdaʊnˌfɔl] n. 倒台
naive [nɑˈiv] adj. 天真的
unacceptable [ˌʌnəkˈseptəb(ə)l] adj.不能接受的
conspire [kənˈspaɪr] v.巧合促成
incredible [ɪnˈkredəb(ə)l] adj.难以置信的
resemblance [rɪˈzembləns] n.相似
scorn [skɔrn] n.嘲弄
acquaint [əˈkweɪnt] v.使了解
reunite [ˌrijuˈnaɪt] v.使囤聚
assume [əˈsum] v.假定,认为

It seems (highly/wildly) improbable that + ... 似乎不可能
be presumed dead/innocent/guilty 假定死亡/无辜/有罪
presume that + ... 假定...
plot to do sth. 密谋做某事
plot against sb. 暗算某人
lead to sb's downfall 导致某人的垮台
bring about sb's downfall 使某人垮台
it be naive enough to believe/think + ...
sb. be naive enough to believe/think + ...
it be unacceptable to do sth.
conspire to do sth.: 合谋做某事
it is incredible (to sb.) that + ...: 难以置信的
it is incredible how + ...
it is incredible to do sth.
bear a close/strong/striking resemblance to sb./sth.: 对某人/物非常相似
bear little/no resemblance to sb./sth. 对某人/物不相似
resemblance to ... 对...的相似
pour scorn on: 嘲笑
pour scorn on the idea/suggestion/plan/advice
acquaint sb. with sth.: 使某人熟悉某事物
sb. be acquainted with sth. 某人熟悉了某物
be reunited with sb. 和某人团聚
assuming that + ... 假设...
it seems/is reasonable to assume that + ... 假设...是合理的
--------------------
to do 非谓语结构
--------------------
a chance in a million 百万分之一
bring ... to a conclusion: 把...结束
sb. accepted the fact that: 某人接受事实...
bring about sth.: 引起某事
and so on: 等等
anyone but: 所有人除了...
be thought to: 被认为...
stop to do:停下来去做某事 VS stop doing sth: 停下来做的事情
comment on sth./sb.: 评论...
suggest that + ...: 建议虚拟语气; 假设不用虚拟语气
there is/was a chance that + ...: ...有可能
needless to say: 不用说
towards the end of + sth.: 接近...的结尾
be separated from: 与...分离
make one's way back to sp.: 回某地
return to: 回去
What become of: 怎么了

** L37 The Westhaven Express
express [ɪkˈspres] n.快车 adj.高速的
punctual [ˈpʌŋktʃuəl] adj. punctually adv.准时的
condition [kənˈdɪʃ(ə)n] v.使习惯于
unshakable [ʌn'ʃeɪkəbl] adj.不可动摇的
faith [feɪθ] n.信任
cancel [ˈkæns(ə)l] v.取消
exceptionally [ɪkˈsepʃənli] adv.例外地
dislocate [ˈdɪsləˌkeɪt] v.打乱(计划等)
blame [bleɪm] v.责怪
consult [kənˈsʌlt] v.请教,查阅
direct [daɪˈrekt] adv.径直地
odd [ɑd] adj.奇怪的
reflect [rɪˈflekt] v.细想
advantage [ədˈvæntɪdʒ] n.优势
mighty [ˈmaɪti] adj.强大的,有力的
dawdle [ˈdɔd(ə)l] v.慢吞吞地动或做
chug [tʃʌɡ] v.喀嚓喀嚓地响
lodge [lɑdʒ] v.提出
complaint [kəmˈpleɪnt] n.抱怨
triumph [ˈtraɪəmf] n.胜利
asterisk [ˈæstərɪsk] n.星号
conduct [ˈkɑnˌdʌkt] v.引向

be punctual for: 准时
condition sb. to (do) sth.: 训练某人做某事 
sb. be conditioned to do sth.: 某人(被训练)习惯于做某事
develop an unshakable belief/faith in sb./sth.: 对某人/某事有不可动摇的信心
have/lose faith in sb./sth.: 对某人/某事有信心
blame sb. for sth.: 怪某人某事
blame sth. on sb.: 怪某人某事
consult the map/manual/dictionary: 查地图/手册/字典
go/fly direct: 直接去
It is/seems odd that + ...: 似乎很奇怪
reflect that + ...:
reflect on sth.: 思考某事
lodge a complaint: 投诉
have/make/receive/lodge a complaint: 投诉
a note of triumph: 胜利的音符
conduct sb. to sp.: 引导某人注意某处
--------------------
neither + 部分倒装
not... but ... 不是... 而是...
--------------------
It is all too easy to do sth.: 很容易做某事
sb. noted with satisfaction that + ...: 某人满意的发现
can't help doing sth.: 忍不住做某事
strike sb as sth./sb.: 使某人想起某人某物
take advantage of sth./sb.: 利用
wish to do sth.: 期望做某事
hold up: 堵住
It dawned on me that + ...: 我突然想到
roar down: 呼啸而下
not do sth. but + ...: 不但做某事,而且...
hear of: 听说
copy of sth.:	一本...
in black and white
at the bottom of sth.: 在某物的底部 
