#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* meditation
** Following Your Breath
#+begin_verse
Drawn from the mindfulness tradition of Buddhism, this basic meditation practice develops concentration and uses the breath to teach you how to stay present from moment to moment, no matter where you are or what you may be doing.

For more-complete instructions (and more about mindfulness), see Chapter 7.
Or you can also listen to Track 4.

1. Begin by finding a comfortable sitting position that you can hold for 10 or 15 minutes.
	Take a few deep breaths and exhale slowly. Without trying to control your breath in any way, allow it to find its own natural depth and rhythm. Always breathe through your nose (unless you can’t for some reason).
	
2. Allow your attention to focus either on the sensation of your breath coming and going through your nostrils or on the rising and falling of your belly as you breathe.
	Although you’re welcome to alternate your focus from one session to the next, sticking with a single focus for the entire meditation is best. Eventually, you’re better off using the same focus each time you meditate.
	
3. Give your full attention to the coming and going of your breath.
	Pay attention to your breath the way a mother tracks the movements of her young child: lovingly yet persistently, softly yet precisely, and with relaxed yet focused awareness.
	
4. When you realize that your mind has wandered off and you’re engrossed in planning, thinking, or daydreaming, gently but firmly bring your mind back to your breath.
	Thoughts and images will almost certainly continue to skitter and swirl through your mind as you meditate, but don’t worry. Just patiently and persistently keep coming back to your breath. If you find it virtually impossible to follow your breath, you may want to begin with counting your breaths (see Chapter 7).

5. Continue this simple (but not easy!) exercise for the duration of your meditation.
	With repeated practice, you may find that your mind settles down more quickly and that you’re more present and focused in other areas of your life as well.
#+end_verse
