#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* profile
#+begin_verse
Hello, my name is Wu Shengdong, you can call me Sherwin.
I graduated from Nanchang Hangkong University with a degree in Aircraft Design and Engineering.
I'm very honored to take part in the interview today.

I'm from a county in Nanchang, Jiangxi Province,
	and I have settled down with my beloved wife in Hangzhou for a few years.
I moved to Hangzhou in April 2019
	and have worked as a Java backend developer for Hangzhou Bode ever since.

While leading the backend development of a barracks management system by myself,
	I built the framework from scratch, communicated directly with the project manager,
		and resolved various technical issues of the project.
As a result, our team succeeded in delivering the project with the hard work of all teammates.
During the project,
	I not only gained a lot of practical experience
		but also improved my technical skills significantly.
Then I was assigned to take responsibility for the backend development of other projects.

In May 2023, I signed a new contract with Zhongxiaokejie,
	which belongs to the same boss of Hangzhou Bode.
In reality, I’ve been working with the same team for nearly six years.
Toward the end of 2024, because of the lack of development and low profit,
	the boss laid off the Development team gradually.

Since then, I’ve been studying English on my own at home
	until I was able to read original English books.
It was only two weeks ago that I began actively looking for a new job.

Where did you work before Hangzhou?
Before coming to Hangzhou,
	I worked in Shenzhen as a Java backend developer for about a year and a half.

And before Shenzhen?
Before Shenzhen, from 2015 to 2016, I worked in Nanchang in automobile headliner design.

What are your future plans?
I hope to take advantage of my English reading skills to solve technical problems at work,
	which will improve my English and programming skills at the same time
		so that I can work as a programmer for the rest of my career.
#+end_verse
