#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 单词造句指南
- v+v.变化
- 四句型转换
- 方式/地点/时间
- 其他习惯用法
- 其他单词+词性
- 原文+变
- 6123456
- 结合其他语法
* Western Civilization
** 08 The coronation of Charlemagne by Pope Leo III
[[./Western Civilization/08 The coronation of Charlemagne by Pope Leo III.html]]
rebellious:
basilica:
pray:
apostle:
blessed:
pacific:
reborn:
coronation:
rebirth:
contour:
increasingly:
fusion:
medieval:
visible:
agrarian:
monarch monarchical:
decentralize decentralization:
subsequently:
shaky:
stifle:
assimilate:
dazzling:
vitality:
--------------------
journey to sp.:
be barely clinging to power:
be attended by sb.:
crowd into sp.:
rose from sth.:
place a golden crown on sb's head:
be crowned by sb.:
prove inadequate to do sth.:
evolve to become sth.:
pose threats:
** 08 The Slavic peoples of Central and Eastern Europe
[[./Western Civilization/08 The Slavic peoples of Central and Eastern Europe.html]]
spacious:
Asiatic:
nomad:
westward:
terrorize:
plunder:
peasant:
ravage:
successive:
overthrow:
migration:
--------------------
push sb's way westward:
these successive waves of sth.:
be assimilated with sth./sb.:
divide into sth.(pl.):
** 09 Street scene in a thirteenth-century English town
[[./Western Civilization/09 Street scene in a thirteenth-century English town.html]]
spur:
defence:
modesty:
myriad:
practically:
good-for-nothing:
esteem:
leisure:
wrestle:
maiden:
fen:
moor:
stride:
sewage:
veritable:
--------------------
come into sb's own:
reach sb's zenith:
be characterized by sth.:
a burst of sth.:
give a new dynamism to sth.:
be fruitful of sth.:
living expenses:
according to sb's station:
fight battles:
be exercised in sth./doing sth.:
cast the stone:
sth./sb. is known to do sth.:
be at hand:
raw sewage:
** 10 A medieval abbot and his monks
[[./Western Civilization/10 A medieval abbot and his monks.html]]
vassal:
dissension:
petty:
centralize:
inaugurate:
monarch monarchical:
solidify:
reform:
exalted:
papal:
vigorous:
forceful:
abbot:
abbey:
devout:
undergarment:
abhor abhorred:
talkative:
supervise:
secular:
--------------------
be mired in sth.:
be coupled with sth./sb.:
made it almost inevitable that + ...:
fall into debt (under sb.):
toil tirelessly:
round up sb.:
stand trial:
be instrumental in doing sth.:
drive sb. from sp.:
be not above doing sth.:
** 10 The Crusades of the Thirteenth Century
[[./Western Civilization/10 The Crusades of the Thirteenth Century.html]]
initiate:
succession:
throne:
neutralize:
sack:
recapture:
territory:
conquer:
ideal:
warrior:
guardian:
--------------------
On sb's way to sp.:
a dispute over sth.:
see an opportunity to do sth.:
be diverted to sp.:
limp along:
sb. announced that + ...:
inspire sb. to do sth.:
lead sb. to sp.:
free A from B:

* TED-Ed
** 2013-10-01 The uncertain location of electrons
[[./TED-Ed/2013-10-01 The uncertain location of electrons.html]]
particle:
proton:
neutral:
nucleus:
indulge:
orbitals /ˈɔːbɪtl/ ring road 轨道
density:
quirk:
exponential exponentially:
--------------------	
in a momentary tangent:
develop a model for sth.:
agree with sth.:
it might be time for sth./ to do sth.:
there will be many more to do sth.:
tend to do sth.:
stick together:
behave as/like sth.:
perform experiment:
It's (not) that + ..., it's that + ..:
there's a certain probability of doing sth.:
be 95% sure of doing sth.:
more or less:
decrease/increase exponentially:
approach zero:
hit zero:
there is some small, but non-zero, probability that + ..:
for a very, very short period of time:
interact with sth./sb.:
surrender A to B:
** 2013-10-03 Why extremophiles bode well for life beyond Earth
[[./TED-Ed/2013-10-03 Why extremophiles bode well for life beyond Earth.html]]
(in) outer space:
abduction by sb.:
in the universe:
draw on sth.:
form life:
ancient religions:
be inhabited by sb.:
sth. be more like A than B:
mythical realms:
parallel universes:
It is only within the last century that + ...:
undertake sth./ to do sth.:
A is just the right distance from B:
support life:
sth. is fatal for sb.:
in the dark depths of oceans/lakes/rivers:
on the flanks of volcanoes:
at extremes of sth.:
What is most remarkable about sth. is that + ...:
hit the surface of sth.:
be flowing with sth.:
be composed of sth.:
be the basic building block of sth.:
** 2013-10-08 The operating system of life
[[./TED-Ed/2013-10-08 The operating system of life.html]]
oak:
acorn:
tadpole:
mold:
solitary:
organism:
lifeform:
machinery:
mission:
currency:
blueprint:
photocopy:
block:
giant:
furnace:
fuel:
scrap:
specialized:
portal:
deoxyribonucleic acid:
protein:
amino:
acid:
mineral:
lipid:
a.k.a.:
membrane:
interaction:
crucial:
oxygen:
phosphate:
molecule molecular:
tote:
biochemistry:
excess:
glycogen:
bacteria:
--------------------
in the back of your fridge:
sb. is a gleam in sb's eyes:
share the same basic goal:
perpetuate sb's existence:
stay alive:
set up a factory:
keep sb. doing sth.:
assembly instructions:
raw materials:
get paid:
send sth. off:
assemble A into B:
be transported to sp.:
draw energy from sth.:
harsher working conditions:
be walled off:
the rest of sth.:
be embedded into sth.:
be built from sth.:
are derived from:
in a pinch:
minimum wage:
be transferred between sth.(pl.):
in the face of sth.:
extreme challenges:
mobilize the immune system:
** 2013-10-08 What is the shape of a molecule
[[./TED-Ed/2013-10-08 What is the shape of a molecule.html]]
mass:
nucleus nuclei:
discrete:
sausage:
formula:
favorable:
--------------------
be concentrated in:
be bonded to sth./sb.:
there's at least one way to do sth.:
maximize/minimize the attraction/repulsion of sth.(pl.):
A matter to B:
A be the outermost one(s) from B:
in between sth.:
be kind of like sth.:
be bunched up together:
fly apart:
doesn't help anyone:
decades before:
be arranged in 3D space:
bond with sth./sb.:
draw sth. as a line:
have a flat representation of sth.:
in three dimensions:
get A far away from B:
expand on our model of sth. to do sth.:
Spoiler alert:

** 2013-10-17 How we conquered the deadly smallpox virus
[[./TED-Ed/2013-10-17 How we conquered the deadly smallpox virus.html]]
marrow:
spleen:
lymph nodes:
vomit:
scar:
scab:
epidemic:
insidious insidiously:
merchant:
Buddhist:
nun:
providence:
variolation:
sore:
inoculate:
foolproof:
dairy:
apothecary:
pockmarked:
udder:
pustule:
vaccinate vaccination:
establishment:
--------------------
spread through sth.:
develop fevers, vomiting, rashes, smallpox:
bear scars and scabs:
spread sth. to sb.:
devastate the civilization:
make its way around the world via sb.:
an estimated Axx to Bxx sth./sb.:
the fall of sb./sth. start:
It begins all the way back when + ...:
grind up sth.:
blow the powder into sp.:
up to xx percent of sth.:
be exposed to sth.:
be an apprentice to sjob.:
a pockmarked face:
protect against sth.:
A be caught from B:
challenge sb. with sth.:
be immune to sth.:
with this procedure:
deliberate at length over sth.:
become prohibited:
certify sth's eradication:
be forever remembered as ...:
the father of -logy.:
in this great adventure of sth.:

** 2013-11-04 The deadly irony of gunpowder
[[./TED-Ed/2013-11-04 The deadly irony of gunpowder.html]]
epic:
gunpowder:
alchemist:
flame/ flammable/ flamethrower:
cannon:
barrel:
canister:
channel:
wick:
ignite:
compound:
shape:
upward-facing:
--------------------
fireworks displays:
propel sth. into sp.:
begin back:
a potion for immortality:
the opposite of sth.:
In these early days:
the right proportions of ingredients:
evil spirits:
defend sb. against sth./sb.:
the invention of sth.:
field sb's attacks:
on sb's conquests in sp.:
bringing sth. back to sp.:
From there:
left sb's mark on sth.:
in contrast to:
be contained within/in:
build up:
take an exit from sp.:
** 2013-10-29 Vampires - Folklore, fantasy and fact
[[./TED-Ed/2013-10-29 Vampires - Folklore, fantasy and fact.html]]
vampire:
shamble:
corpse:
dapper:
revenant:
donkey:
bloodthirsty:
sever:
upper:
torso:
sprout:
wing:
entrail:
bloodsucker / bloodsucking:
trait:
reanimated/reanimation:
folklore:
nocturnal:
grim:
plague:
supernatural:
cadaver:
bloated:
beheading:
decompose:
dehydrate:
incorporate:
garlic:
stake:
attribute:
crucifixes:
reflection:
stalk:
subsist:
sparkling:
--------------------
What's the matter:
extend as far back as prehistoric times:
back then:
be simply described as sth.:
have one common characteristic:
sustain oneself by doing sth.:
the life force of sth.:
change with the times:
With the dramatic increase of sth.:
dig up <-> sth.:
discern the cause of sth.:
at the corners of mouths:
feast on sth.:
enact a ritual to do sth.:
stake the body to the coffin:
normal symptoms of sth.:
cause sb./sth. to do sth.:
force out sth. through sth.:
establish a law prohibiting sth./doing sth.:
die down:
brutal executions:
inspire the main elements of sth.:
enact the age-old tradition of doing sth.:
elaborate upon:
** 2013-12-16 The popularity, plight and poop of penguins
[[./TED-Ed/2013-12-16 The popularity, plight and poop of penguins.html]]
clumsy:
adorable:
exceedingly:
ornery:
precarious:
closest:
albatross:
wingspan:
soar:
evolutionary:
flipper-like:
dive:
hemisphere:
breed:
reproduce:
subantarctic:
craggy:
lava:
burrow:
stick:
incubate:
approximate approximately:
indicator:
historically:
disturbance:
guano:
fertilizer:
marine:
terrestrial:
habitat:
introduce:
predator:
prey:
entrapment:
plastic:
krill:
severe severity:
conservation:
spills:
vulnerable:
tuxedo:
current:
--------------------
have long done sth.:
capture the imagination and the hearts of sb.:
the world over:
depict A as B:
endlessly abundant:
in rapid free fall:
so to speak:
For one thing:
evolve from sth.:
the ability to do sth.:
fill an ecological niche:
contrary to sth.:
be not restricted to sp.:
subtemperate/temperate regions:
off sp.:
molt their feathers:
in tussock grasses:
a clutch of sth./sb.:
be listed as sth.:
decline by:
be down to sth.:
in the coal mine:
Simply put:
be attributable to sth.:
due to sth.:
carry sb. too far away from sp.:
be underway to do sth.:
** 2014-01-06 How to fossilize yourself
[[./TED-Ed/2014-01-06 How to fossilize yourself.html]]
fossil:
tour:
fawn:
exclusive:
fossilization:
paleontologist:
highlight:
sap:
harden:
mountaintop:
prairie:
bury:
scavenge:
bog:
shallow:
muddy:
sandy:
sediment:
permineralization:
mineral-rich:
microscopic:
pore:
subduct:
surroundings:
erosion:
intrepid:
amateur:
fortuitous:
magnificent:
shed:
disintegrate:
plate tectonics:
--------------------
imagine doing/being sth.:
inspire awe in sb.:
hordes of sb.:
forget about sth.:
listen up:
(in) the Hall of sth. Fame:
at some point:
get to sth.:
A turn into B:
survive intact:
sp. remain the domain of sb.:
The right place to be if you want to do sth. is wherever + ...:
hang around:
slow down (<-> sth.):
decay away:
give you more time to do sth.:
be lucky enough to do sth.:
What's your next move:
get saturated with sth.:
Bit by bit:
precipitate out of these waters:
hope sb. do sth.:
create a perfect cast of sth.:
You're not in the clear yet:
a mountain range:
erode away sth.:
Fingers crossed + ...will:
get gently lifted up:
wipe away sth.:
scout for sth.:
hope for sth.:
whack away:
in a creek bank:
millions of years in the making:
extract A from B:
begin the complex task of doing sth.:
in obscurity:
work oneself to the bone:
hold that pose:
** 2014-02-12 The history of marriage
[[./TED-Ed/2014-02-12 The history of marriage.html]]
inspirational:
hilarious hilariously:
cynical:
timeless:
humanity:
sedentary:
agricultural:
simultaneous:
institution:
adultery:
demographic:
ruler:
elite:
concubine:
commoner:
monogamy:
arrangement:
prayer:
explicitly:
Adelphopoiesis:
chapel:
deceased:
conduct:
lineage:
appease:
restless:
young:
practicality:
upperclass:
industrialization:
urbanization:
household:
pursuit:
Pair bonding:
----------------------------------------
what sb.(pl) have in common is that + ...:
vary greatly between sth.(pl):
take a quick look at sth.:
With the rise of sth.:
be a way of doing sth.:
secure rights to sth.:
under certain circumstances:
designate A as B:
a matter between sth.(pl):
be governed by:
punishments for sth.:
the legal status of sb.:
be born to sb.:
a quarter of sth.:
the link between sth.(pl):
in practice:
the tables were turned:
have relationships with sb.:
in public ceremonies:
at stake:
became independent from sb./sth.:
be encouraged by:
focus on A rather than B:
ease restrictions on sth.:
be shaped by sth.:
** 2014-04-18 Not all scientific studies are created equal
[[./TED-Ed/2014-04-18 Not all scientific studies are created equal.html]]
herb:
liver:
vitamin:
headline:
attention-grabbing:
proclaim:
promising:
dietary:
randomize:
clinical:
trial:
rigorous:
medication:
placebo:
significant:
overall:
epidemiology/epidemiological:
nausea:
cohort:
substance:
inherent:
flaw:
confounding:
pitfall:
eliminate:
critical:
hazard:
asbestos:
Lead:
cure:
--------------------
Studies have shown that + ...:
be bombarded with sth.:
be backed up by sth.:
point the way towards sth.:
be assigned to sth./ assign sb. to sth.:
with headaches:
be divided into sth.:
a comparison group of ...:
have exposure to sth.:
establish causal relationships between sth.(pl.):
in addition to:
be combined with sth.:
go out of sb's way to do sth.:
take steps (to do sth.):
induce changes within ...:
demonstrate a correlation between sth.(pl.):
At the end of the day:
alert sb. to sth.:
** 2014-05-15 How the heart actually pumps blood
[[./TED-Ed/2014-05-15 How the heart actually pumps blood.html]]
serve:
thump:
pump:
perish:
opaque:
crude:
demonstrate:
label:
grasp:
potentially:
mammal:
morphology:
signal:
intimidate intimidating:
complicated:
medic:
motion:
immerse:
squeeze:
mechanism:
remaining:
superficial / superficially:
column:
tap:
spectacular/spectacularly:
parachute:
leak:
seamless seamlessly:
unfold:
rhythmical:
dependable:
caffeine:
four-chambered:
dual-circulation:
atria:
ventricle / ventricular:
vein:
artery:
aorta:
pulmonary:
tricuspid:
mitral:
blood vessels:
heart valves:
----------------------------------------
For most of history:
have no idea + ...:
feel sb's heart beating:
in surgery teams:
point to sth.:
It's as if + ...:
Meaning that + ...:
the next best thing is to do sth.:
cut it open:
in reality:
goes from sp.A to sp.B, back to sp.C:
make sb. wary of sth.:
end up doing sth.:
That's when + ...A + as + ...B:
What you (will) need to get started is sth.:
do A enough for sb. to do B:
trim sth. down (to sp.):
rise from sth.:
run water into sp.:
close against sth.:
inflate with sth.:
squirt out of sth.:
with very little wear and tear:
give new resonance to sth.:
run a race:
catch the eye of sb.:
** 2014-05-05 The science of attraction
[[./TED-Ed/2014-05-05 The science of attraction.html]]
spontaneous:
indescribable:
poetic:
fuzzy:
veto:
budding:
component:
fertility:
lustrous:
reproductive:
fitness:
cologne:
pheromones:
physiology physiologyical:
recipient:
saliva:
testosterone:
odor:
breathy:
formant spacing:
hypothetical:
unaffectionate:
infamous:
tactile:
cue:
tunnel vision:
bloodstream:
dilate:
glucose:
warp:
----------------------------------------
think of A as B:
perceive A as B:
run a (complex) series of calculations:
within a matter of seconds:
sounds quite as adj.:
Just because +... doesn't mean + ...:
all num. of sth.:
play a role in doing sth./sth.:
be in demand:
pick up on sth.:
In one study:
in sb's ovulation cycle:
be randomly assigned to do sth.:
give sb. the nudge to do sth.:
be particularly attuned to sth.:
differ from sth.:
result in sth.(death/failure/contradiction):
be correlated with sth.:
rate sb's personality:
lose sb's attraction to sb.:
be flooded with sth.:
activate (sb's fight/flight/immune) system:
+..., not because +...,but because + ...:
block out sth.:
enhance sb's memory:
This might explain why + ...:
play matchmaker:
** 2014-05-06 What is the world wide web
[[./TED-Ed/2014-05-06 What is the world wide web.html]]
revolution:
interchangeabe/interchangeably:
conference:
skyscraper:
know-how:
domain:
virtual:
hosting:
registrar:
loose:
interconnect:
mirror:
arrangement:
hyperlink:
encounter:
reflect:
boundary:
ethnicity:
----------------------------------------
be likely doing:
be used by sb. for sth.:
chat with sb.:
use it from sth.:
first of all:
made a call to sb.:
be all around sb.:
There's another part to doing sth., without which + ...:
with no way of doing sth.:
a graphic interface:
utility company:
lie in sth.:
be prior to sth.:
in a linear fashion:
in a straight line:
redirect sb. to sp.:
in content and structure:
** 2014-05-30 How does your brain respond to pain
[[./TED-Ed/2014-05-30 How does your brain respond to pain.html]]
stimulus:
matter:
sensory:
tissue:
intensity:
sharp:
dull:
perception:
damage-sensing:
nociceptor:
spinal cord:
neuron:
glia:
superhighway:
electrical impulses:
pathway:
cortex:
salient / salience:
modulate / modulation:
endorphin:
enkephalin:
regulate:
sensitivity:
efficacy:
brain circuits:
variable / variability:
roller coasters:
motion:
target:
mild:
non-prescription:
anesthetic:
severe:
chronic:
stimulate:
pain-sensing:
map:
personalize / personalized:
----------------------------------------
receive electric shocks to sb's hands/arms:
distract sb. from sth.:
do sth. faster and better when +... than when +...:
send sb's mind wandering:
be subjected to sth.:
describe sth. on a scale from A to B:
respond to sth.:
cope with sth.:
take sb. hand off sth.:
act on sth.:
along with ways to do sth.:
tailor sth. to sb.:
the key to doing sth.:
** 2014-06-03 How to choose your news
[[./TED-Ed/2014-06-03 How to choose your news.html]]
absorb:
broad-based:
newspaper of record:
authoritarian:
censor:
scandal:
revelation:
covert:
assassination:
corruption:
narratives:
mainstream:
gatekeeper:
outlet:
unfiltered:
protest:
blog / blogger:
polished:
chaotic:
terrorist:
coverage:
accusation:
refute:
bias:
anonymity:
rumor:
falsehood:
outrageous:
curate:
flow:
----------------------------------------
a click away:
undermine sb's faith in sth./sb.:
the breakdown of trust in sb./sth.:
compete with sb.:
from various perspectives:
More recently:
multiply the amount of sth.:
sb. keeps in mind that + ...:
in real time:
at several points in the day:
allow time for sth./sb. to do sth.:
aim for sth.:
tuning in to sth.:
take a guess:
watch out for sth.:
have little connection to sth./sb.:
make sb. unaccountable for sth.:
with A comes B:
ensure that + ...:
leave sb. less informed than before + ...:
took the plunge:
** 2014-11-05 Why elephants never forget
[[./TED-Ed/2014-11-05 Why elephants never forget.html]]
walking hard drive:
magnificent:
benevolent:
proverb:
accurate:
encounter:
hostile:
recall:
herd:
companion:
drought:
circus:
rejoice:
boast:
encephalization quotient:
mammal:
converge/convergent:
synapse:
developed:
hippocampus:
cerebral:
recollection:
faculty:
rote:
clan:
matriarch:
cooperative/cooperatively:
outwit:
manipulate:
post-traumatic stress disorder:
arithmetic:
vocalize/vocalization:
infrasound:
rumble:
syntax:
tone:
recreate:
melody:
altruism:
mourn:
burial ritual:
log:
trunk:
massive:
poach:
cull:
revenge:
ivory:
----------------------------------------
It's a common saying that + ...:
it appears that + ...:
as many as num. sth.:
make a strong impression on sb.:
In one case:
cross paths (with sb.):
sth. isn't limited to sb.:
after days/months/years/decades apart:
go beyond sth.:
encode A into B:
in adulthood:
tackle problems:
keep track of sth.:
shown concern for sth./sb.:
stand guard:
comfort sb. with sth.:
it's hard to escape the conclusion that + ...:
in captivity:
Given what + ...:
It is more important than ever to do sth.:
vanish from sp.:
** 2014-12-18 What is a gift economy
[[./TED-Ed/2014-12-18 What is a gift economy.html]]
knit:
adopt:
contradictory:
obligation:
social ties:
canoe:
potlatch:
chief:
livestock:
blanket:
participant:
barter:
haggle:
norm:
reciprocity:
voluntarily:
prestige:
communal:
taboo:
financial:
potluck dinner:
prevail:
anthropology/anthropologist:
native:
----------------------------------------
This holiday season:
consign sth. to the closet:
expect sth. from sb.:
become/ be involved in:
for free:
without explicit conditions:
foster a system of sth.:
be formed by:
throughout human history:
describe sb. doing sth.:
make a journey:
do sth. through this process:
carry an obligation to do sth.:
give away sth.:
obligate sb. to do sth.:
return the favor:
take many forms:
at sb's expense:
gain sth. from sb./sth.:
be indebted to sb.:
be read as doing sth.:
be exclusive to sth.:
social pay off:
miss the point:
** 2015-01-30 Why are some people left-handed
[[./TED-Ed/2015-01-30 Why are some people left-handed.html]]
left-handed:
proper:
1/10:
artifact:
fetus:
inborn:
genetic:
identical:
gene:
dominant:
consistent:
ratio:
odds:
millennium/millennia:
theory:
competitive:
competitor:
combat:
hitter:
hypothesis:
athletes:
frequency-dependent:
asset:
distribution:
majority:
equilibrium:
intrigue intriguing:
skewed:
pawedness:
hunter-gatherer:
puzzle:
----------------------------------------
chances are + ...:
in many parts of the world:
the word for A:
in the first place:
show evidence of sth./doing sth.:
in the womb:
have a 17% chance of doing/being sth.:
be born adj.:
by a roll of the dice:
It implies that + ...:
over the course of millennia:
The benefits of doing sth.:
a minority to do sth.:
be thrown off:
lead to sb. doing sth.:
in the opposite direction:
disappear from:
play out:
simultaneously over time:
in sb's hands:
** 2015-03-12 Plato’s Allegory of the Cave
[[./TED-Ed/2015-03-12 Plato’s Allegory of the Cave.html]]
figurative/figuratively:
thread:
flicker:
flit:
cheery:
allegory:
Republic:
envision:
cavern:
faint:
cast:
classify:
perceive:
entity:
disorienting:
reflection:
adjust:
ultimate:
blind:
ignorance:
disrupt:
disparaging:
promote:
rule:
parable:
mass:
stubborn:
ignorant:
dialogue:
flawed:
roundness:
fundamental:
representation:
theologian:
linguistic:
concrete:
abstract:
assumption:
consolation:
----------------------------------------
explain A as B:
be like doing sth.:
be chained up:
face a wall:
give off:
pass by sb./sth.:
have a hard time doing sth.:
resist an attempt to do sth.:
introduce A as an analogy of B:
be hostile to sb.:
the real life:
be sentenced to death/imprisonment:
capture imaginations:
view A as B:
group A under B:
go about sth.:
a glimmer of light:
punch a hole:
break free (from sth.):
stick with sth.:
** 2015-03-13 Can robots be creative
[[./TED-Ed/2015-03-13 Can robots be creative.html]]
composer:
artificial:
creativity:
intelligence:
mathematician:
programmer:
formalize:
scrutinize:
algorithm:
generator:
fuzzy:
yield:
countless:
outcome:
artistic:
mutation:
fitness:
ultimate:
complexity:
aesthetic:
theoretically:
intuition:
anyways:
dynamo:
initiative:
weep:
--------------------
grapple with the question of sth.:
program sth. to do sth.:
propose a way of doing sth.:
a sequence of sth.:
a tiny fraction of sth.:
approach to doing sth.:
an initial population of sth.:
a new generation of sth.:
be weeded out:
the presence of sth.:
The jury may still be out:
blow your mind:
send shivers down your spine:
** 2015-03-27 What causes bad breath
[[./TED-Ed/2015-03-27 What causes bad breath.html]]
curse:
plague:
aromatic:
shell:
legal:
scourge:
halitosis:
universally:
feces:
microorganism:
moisture-rich:
vital:
digestion:
mucus:
food remnants:
tissue:
nutrient:
foul-smelling:
byproducts:
sulfide:
cadaverine:
unsuspecting:
intimate:
primal:
gram-negative:
antibacterial:
mouthwash:
scraper:
nasal:
ailment:
diabete:
excessive:
alcohol consumption:
originate:
lick:
wrist:
subjectively:
--------------------
resort to sth.:
grounds for sth.(divorce)/doing sth.:
as disgusting as it may sound, ...:
feed off of sth.:
break down A into B:
waft sb's way towards sp.:
interpretation of A as B:
warn sb. of sth.:
go on a date with sb.:
floss sb's teeth:
at bedtime:
in the first place:
cup your hands over your mouth:
be too acclimatized to sth. to do sth.:
** 2015-05-15 Debunking the myths of OCD
[[./TED-Ed/2015-05-15 Debunking the myths of OCD.html]]
misconception:
meticulous meticulously:
obsessive:
compulsive:
psychiatric:
alike:
repetitive:
ritualistic:
intrusive:
obsession:
tendency:
debilitate debilitating:
distress:
diagnostic:
contamination:
harm:
hygiene obsessed:
clue:
neurobiological:
serotonin:
neurotransmitter:
regulate:
aggression:
desensitize:
electroconvulsive:
agonize agonizing:
--------------------
plan out sth. to the last detail:
debunk some myths:
A be synonymous with B:
from time to time:
have little or no control over sth.:
interfere with sth. to the point of doing sth.:
separates A from B:
manifest as sth.:
preoccupations with sth.:
range from ... to ...:
quite well:
be hardwired to do sth.:
the underlying cause of sth.:
lie to sb.:
** 2015-06-02 How people rationalize fraud
[[./TED-Ed/2015-06-02 How people rationalize fraud.html]]
trillion:
embezzle embezzlement:
insurance:
triangle:
criminologist:
rationalization:
addiction:
quota:
budget:
fraudster:
offenders:
underpaid:
overworked:
victimless:
taxpayer:
overbill:
fabricate:
falsify:
subsidiary:
corporate:
governance:
regulator:
supervision:
greed:
quarter horse:
breeder:
finance:
subsidize:
untangle:
--------------------
lost [money] to sth.:
pyramid schemes:
be susceptible to sth.:
commit fraud:
make sth. likely:
motivate sb. to do sth.:
a sudden job loss:
in the public/private sector:
credit cards:
on a daily basis:
justify sth. to sb.:
feel entitled to sth.:
resolve crisis:
register as sth. to sb.:
fudge expense reports:
report cash earnings:
recoup losses/ losses be recouped:
divert money to sp.(an account):
go unnoticed:
run to sth.:
go bankrupt:
to begin with:
It is believed that + ...:
raise prices:
be left doing sth.:
* other(If they are too many, then split them)
** public speaking
feel nervous about doing sth.:
give a speech:
in good company:
suffer from sth.:
stage fright:
turn pale:
at the outset of a speech:
quake in every limb and in my soul:
report doing sth.:
speaking in public:
be nominated for:
nerve-wracking experience:
in jest:
sb. be given a choice/give sb. a choice:
would rather do A than do B:
give the eulogy:

** the best life story
*** 01 Let him Go, Olivia
It's over.:
pass away:
in recognition of sb.:
write this story as a tribute to sb.:
make it possible for sb to have done:

*** 02 Lazy Summers
swoop:
buzz:
swat it away:
bring a smile to my face:
A join in the chorus of B:
have memories of:
swirl around:
reminisce (about):

** Reading to Learn the Art of Expression
observant:
clause:
--------------------
biographical sketch:
forms of ...:
from all over England:
sb's aim is to do ...:
receive treatment (from sb.):
at a time when ...:
stay adj.:

** humans of NewYork
*** 01 down to ride for you
be down to ride:
*** 02 You're the best dad ever
pop up:
what it's like:
rip out heart:
back off:
get a flicker of:

** Children’s Engineering Workshops.
workshop:
want some information about sth. :
design a adj. cover that goes round sth. :
there is an opportunity for sb. to do sth.:
be amazed + ...:
one thing sb. does is to do sth.:
A be attached to B:
the force of air/water:
presumably:
advanced:
construct A using B:
pick sth. up:
use A to do B:
come up with=think up an idea for sth.:
A in the shape of B:
give sb. enough time to do sth.:
up past sp.:
enrol:

** stoicism
achieve sb's triumphs:
the likes of sth.:
have access to sth.:
come to sb.:
in turn:
with regard to sth.:
put on ...:
prime minister:
the course of ...:
at the root of sth.:
resonate with:
refer to A as B:
* NCE2
** L01 A private conversation
[[./NCE2/L01 A private conversation.html]]
private:
conversation:
theatre:
seat:
play:
loudly:
angry:
angrily:
attention:
bear:
business:
rudely:

have a conversation:
take a seat:
Is the seat taken?:
How can you bear that?:
Don't be rude:
--------------------
6123456:
	 6: When
	 1: 主
	 2: 谓/系
	 3: 宾/表
	 4: how
	 5: where
	 6: when
give me that book VS give it to me
1. 如何造一个英语句子: 123 
2. 如何造一个好的英文句子: 123456
3. 英语语序

go to the theatre:
have a good seat:
get angry:
turn round:
pay attention:
in the end:
couldn't bear it:
It's none of your business:

** L02 Breakfast or lunch?
[[./NCE2/L02 Breakfast or lunch.html]]
until:
outside:
ring:
aunt:
repeat:

repeat after me:

--------------------
am/is/are + doing:
	1. 动作正在发生;
	2. 动作已经开始,但未完成;
	3. 表近期计划(+未来时间)
	4. 一段时间正在发生的事情: today/this week/this year(阶段)连用
	5. 一段时间正在发生的变化: get/change/become/increase/rise/fall/grow/improve/begin/start

do/does: 动作发生在说话时发生不重要
	1. 习惯动作(一直/重复发生的事情)
	2. 客观事实
	3. 行为靠说话完成. I promise,suggest,apologise,advise,insist,agree,refuse

am/is/are + doing VS do/does
	- 正在发生的行为还没有完成 VS 一直/重复发生的事情
	- 暂时的情况 VS 长久的情况
	- I always do(总是做某事) VS I'm always doing(总是做某事到不正常的程度)

感叹句: 形容词需要升调
	What + (形容词) + n. (+ 主语 + 谓语)

频率adv.位置: 
	1. 动词前,be/助/情态动词后
	2. is/will/did省略句前
	3. probably won't;

get up early/late: 起床早/晚
just then: at a particular time in the past在那时
have breakfast: 吃早餐

** L03 Please send me a card
[[./NCE2/L03 Please send me a card.html]]
send:
postcard:
spoil:
museum:
public:
friendly:
waiter:
lend:
decision:
whole:
single:

buy sb. sth. = buy sth. for sb. 买东西给某人
send sb. sth. = send sth. to sb. 送东西给某人
lend sb. sth. = lend sth. to sb. 借东西给某人
borrow sth. from sb. / borrow sb. sth. 从某人那借东西
make a decision:

--------------------
was/were/did:

teach sb. sth.:
lend sb. sth.:
think about sth./sb.:
on the last day:
make a decision:
send sth. to sb.:
spend st. sw.:

** L04 An exciting trip
[[./NCE2/L04 An exciting trip.html]]
exciting:
receive:
firm:
different:
centre:
abroad:

have a great trip:
receive sth. from sb.:
work for:
A be different from B:
in the centre of sp.:
go abroad:
live abroad:
study abroad:

--------------------
have done:
	1. 过去事情对现在有影响;
	2. 从过去持续到现在
	3. 与just~already和yet连用
		just:
		already:
		yet:
	4. 不用过去时间点连用
	5. have gone to 去了那里 & have been to 在那里

receive sth. from sb.:
work for sb.:
a great number of:
have gone to sp. VS have been to sp.:
fly to sp.:
find n. adj.:

** L05 No wrong numbers
[[./NCE2/L05 No wrong numbers.html]]
pigeon:
message:
cover:
distance:
request:
spare [speə(r)] part [pɑːt]:
service:

leave sb. a message:
customer service:
cover the distance in st.:

--------------------
have done VS did:

A is 5 miles from B:
get sth. for sb.:
cover the distance in st.:
a great many:
send a request for sth.:
up to now:
in this way:

** L06 Percy Buttons
[[./NCE2/L06 Percy Buttons.html]]
beggar:
food:
pocket:
call:

pocket money:
call at = visit:

--------------------
a/an VS the:
some VS any:
	1. 陈述句? 肯定some, 否定any
		 有任何的意思? any
	2. if从句? any
	3. 疑问句? 确认some, 不确认any

move to sw.:
knock at the door:
ask sb. for sth:
stand on sb's head:
call at:
in return for this:
once/twice a st.:
ask for sth.:

** L07 Too late
[[./NCE2/L07 Too late.html]]
detective:
airport:
expect:
valuable:
parcel:
diamond:
steal:
main:
airfield:
guard:
precious:
stone:
sand:

keep guard:

--------------------
was/were + doing:
when & while & just as(正像,正当):


all morning:
	The plane was late and detectives were waiting at the airport all morning.
a parcel of sth:
a few hours earlier:
keep guard:
to sb's surprise:
try to do sth:
A be full of B:

** L08 The best and the worst
[[./NCE2/L08 The best and the worst.html]]
competition:
neat:
path:
wooden:
pool:

enter the competition:
make a path:
That's neat:

--------------------
adj. 比较级&最高级变化规则
	1. 单音节:
		 - 元+辅音字母结尾:
	2. 双音节:
		 - 辅音+y结尾:
	3. 多音节:
	4. 不规则:
比较状从:
	1. 主语 + be + the + adj.est + n. + I've ever met/seen
	2. 主语 + be + the + adj.est + n. + 范围
	3. 主语 + be + adj.er + than + 比较对象 (I formal / me informal)

enter for:
make a path:
build a bridge:
win a prize:

** L09 A cold welcome
[[./NCE2/L09 A cold welcome.html]]
welcome:
crowd:
gather:
hand:
shout:
refuse:
laugh:

a cold welcome:
a warm welcome:
gather round:
shout at sb:
refuse to do sth:
laugh at sb:

--------------------
at/on/in(时间)
	- on + 具体某一天
	- in + 年/季/月
	- at + 时间点

the last day of the year:
a large crowd of:
in twenty minutes' time:
refuse to do sth:
at that moment:
begin to do sth:

** L10 Not for jazz
[[./NCE2/L10 Not for jazz.html]]
jazz:
musical:
instrument:
clavichord:
recently:
damage:
key:
string:
shock:
allow:
touch:

be allowed to do sth.:
allow sb. to do sth.:

--------------------
am/is/are+done
was/were+done
am/is/are+being+done
have/has+been+done

be made in sw.:
belong to sb.:
play jazz:
be allowed to do sth.:

** L11 One good turn deserves another
[[./NCE2/L11 One good turn deserves another.html]]
turn:
deserve:
lawyer:
bank:
salary:
immediately:

one good turn deserves another:
get a good salary:
It's your turn:

get a good salary:
borrow sth. from sb.:
pay it back:
pay for sth.:
ask sb. to do sth.:

** L12 Goodbye and good luck
[[./NCE2/L12 Goodbye and good luck.html]]
luck:
captain:
sail:
harbour:
proud:
important:

lucky dog:
be proud of:
I got a very important question to ask you:

--------------------
will do:
shall do:

sail from sw.:
set out:
have plenty of time:
will be away:
A be proud of B:
say goodbye to sb.:
take part in:

** L13 The Greenwood Boys
[[./NCE2/L13 The Greenwood Boys.html]]
group:
pop:
club:
performance:
occasion:

a group of:
pop music/song/star:
give a performance:
on this occasion:

--------------------
will be doing:

a group of:
at present:
all parts of the country:
as usual:
have a difficult time:
give five performance:
keep order:
on these occasions:

** L14 Do you speak English?
[[./NCE2/L14 Do you speak English.html]]
amusing:
experience:
wave:
lift:
reply:
language:
journey:

have an amusing experience:
wave to sb.:
take a lift/ ask for a lift:
A give B a lift:
reply to the email/letter:
go on a journey:

--------------------
had + done:

drive on to sw.:
on the way:
ask sb. for a lift:
apart from:
in French:

** L15 Good news
[[./NCE2/L15 Good news.html]]
secretary:
nervous:
afford:
weak:
interrupt:

be nervous about sth. / doing sth.:
afford sth.:
Sorry to interrupt, but...:

--------------------
宾语从句:
直接引语变间接引语:

look up:
afford to pay:
my turn had come:
in a weak voice:

** L16 A polite request
[[./NCE2/L16 A polite request.html]]
park:
traffic:
ticket:
note:
area:
sign:
reminder:
fail:
obey:

make notes/ a note:
leave a note:
remind sb. of sth./sb.:
fail to do sth.:

--------------------
if从句
	- 主将从现
	- 主情从现
	- 主祈从现

park sb's car:
pay attention to:
	
** L17 Always young
[[./NCE2/L17 Always young.html]]
appear:
stage:
bright [braɪt] adj. + color [ˈkʌlə(r)] + n.:
stocking:
sock [sɒk] n.短袜
grown-up [ˌɡrəʊn ˈʌp] adj. n.成年人

--------------------
must:
have to:
've/have got to:

肯否猜测:
	- 现在猜测
		must:
		can't:
	- 过去猜测
		must have done:
		can't have done:

at least:
in spite of this:
take part in:

** L18 He often does this
[[./NCE2/L18 He often does this.html]]
pub:
landlord:
bill:

pay the bill:

--------------------
have:

look for:
have a meal:
pay the bill:
in a few minutes:

** L19 Sold out
[[./NCE2/L19 Sold out.html]]
hurry:
ticket:
pity:
exclaim:
return:
sadly:

hurry to sw.:
in a hurry:
What a pity:
It's a pity that...:
Don't yell at me.:

--------------------
也许 现在-猜测:
may/might (not)do
may/might (not)be adj./n.
may/might (not)be doing

也许 过去-猜测:
may/might (not)have done
may/might (not)have been adj./n.
may/might (not)have been doing.

sold out:
at once:
might/may as well:

** L20 One man in a boat
[[./NCE2/L20 One man in a boat.html]]
catch [kætʃ] caught caught:
fisherman:
boot:
rubbish:
waste:
realize:

catch your eye:
catch a bus:
watch your tongue:
That's rubbish:
You're wasting time.:
sb. realized that...:

--------------------
动名词:

instead of doing sth.:
spend st. sw.:
give up doing sth.:
be interesting in doing sth.:
be keen on doing sth.:

** L21 Mad or not?
[[./NCE2/L21 Mad or not.html]]
mad:
reason:
sum:
determined:

be mad at sb.:
for some reason:
a large sum of money:
be determined to do sth.:

--------------------
will/would be done
can/could be done
must be done
have to be done
must have been done

drive sb. mad:
for some reason:
come into use:

** L22 A glass envelope
[[./NCE2/L22 A glass envelope.html]]
dream:
age:
channel:
throw:
regularly:

dream of doing sth.:
at my age:
throw away:

--------------------
v. + of/from/in/on

think of sth.:
write to sb.:
decide to do sth.:

** L23 A new house
[[./NCE2/L23 A new house.html]]
complete:
modern:
strange:
district:

You complete me.:
have a letter from sb.:
get a surprise:

** L24 It could be worse
[[./NCE2/L24 It could be worse.html]]
manager:
upset:
sympathetic:
complain:
contain:
honesty:

get/be upset about sth.:
complain about sth.:
start to do sth.:

** L25 Do the English speak English?
[[./NCE2/L25 Do the English speak English.html]]
railway:
porter:
several:
foreigner:
wonder:

not know the way to sw.:

--------------------
1. and,but,or,so,because(Because & ,because):
2. both... and, either...or,neither...nor:
3. not only... but also (as well) ?:

** L26 The best art critics
[[./NCE2/L26 The best art critics.html]]
art:
critic:
paint:
pretend:
pattern:
curtain:
material:
appreciate:
notice:
whether:
hang [hæŋ] hung hung:
critically:
upside:

sb. pretend that ...:
I really appreciate that.:

** L27 A wet night
[[./NCE2/L27 A wet night.html]]
tent:
field:
smell:
wonderful:
campfire:
creep:
sleeping:
comfortable:
soundly:
leap:
heavily:
stream:
form:
wind:
right:

put up the tent:
tell a story/stories:
put out the fire:
begin doing sth.:
wake up:

** L28 No parking
[[./NCE2/L28 No parking.html]]
rare:
ancient:
myth:
trouble:
effect:
Medusa:
Gorgon:

have trouble with sth:
	He has had trouble with cars and their owners.
have no effect:
have trouble doing sth.:

--------------------
限定性定语从句:
	- 输出:
		1. 确定被修饰词
		2. 确定引导词, who/whom/which/that
		3. 是否可以省略(引导词在从句是宾语可省)
	- 有多个人或物时,起限定某个的作用
	- what = the thing(s) that(补充了主句成分)
	- where:
			还有to which, in which的变形,注意!!!
	- whose:

** L29 Taxi!
[[./NCE2/L29 Taxi.html]]
taxi:
Pilatus:
land:
plough:
lonely:
Welsh:
roof:
block:
flat:
desert:

take a taxi:

--------------------
done做定语:
	- done + n.
	- n. + done短语
	- 常常与there be句型连用
复习have done VS did

** L30 Football or polo?
[[./NCE2/L30 Football or polo.html]]
polo:
Wayle:
cut:
row:
kick:
towards:
nearly:
sight:

kick his ass:

--------------------
doing现在分词做定语:
	- doing + n.
	- n. + doing
	- 常常和there be连用
	- 例句
		- the sinking ship=the ship that is sinking
		- the rising sun=the sun that is rising
		- the sleeping child=the child who is sleeping

call out to sb.:

** L31 Success story
[[./NCE2/L31 Success story.html]]
retire:
company:
bicycle:
save:
workshop:
helper:
employ:
grandson:

save sb's life:
--------------------
used to do sth.:

It is/was sb's job to do sth.:
in sb's twenties:

** L32 Shopping made easy
[[./NCE2/L32 Shopping made easy.html]]
once:
temptation:
article:
wrap:
simply:
arrest:

once upon a time:
resist the temptation:
wrap up sth.:

--------------------
as ... as VS so ... as(否):

It is easy for sb. to do sth.:
hand sth. to sb.:
wrap sth. up:
as quickly as possible:

** L33 Out of the darkness
[[./NCE2/L33 Out of the darkness.html]]
darkness:
explain:
coast:
storm:
towards:
rock:
shore:
light:
ahead:
cliff:
struggle:
hospital:

struggle up:
explain sth. to sb.:
go ahead:
 
--------------------
be high up 高高在上:
On doing sth, ...:

** L34 Quick work
[[./NCE2/L34 Quick work.html]]
station:
most:
--------------------
had been + done

call at:
except sth. to be found:

** L35 Stop thief!
[[./NCE2/L35 Stop thief.html]]
while:
regret:
far:
rush:
act:
straight:
fright:
battered:
shortly:
afterwards:

a short while ago:
regret sth./doing sth.:
rush out of/towards:
go straight ahead:
give me a fright:
get a fright:
Shortly afterwards:

--------------------
so + adj./adv. that = such + n. that:
see sb. do sth VS see sb. doing sth.:

** L36 Across the Channel
[[./NCE2/L36 Across the Channel.html]]
record:
strong:
swimmer:
succeed:
train:
anxiously:
intend:
solid:

set up a new world record:
break the record:
as strong as a horse:
strong like a horse:
succeed in doing sth.:
train sb. to do sth.:
intend to do sth.:

--------------------
表述将来:
be going to do(be due to)
will
intend to do

hope to do sth.:
be sure to do sth.:
take some rests/a rest:

** L37 The Olympic Games
[[./NCE2/L37 The Olympic Games.html]]
Olympic:
hold:
government:
immense:
stadium:
standard:
capital:
fantastic:
design:

hold a meeting:

--------------------
will have done:
have done VS had done VS will have done

look forward to doing sth.:

** L38 Everything except the weather
[[./NCE2/L38 Everything except the weather.html]]
except:
Mediterranean:
complain:
continually:
bitterly:
sunshine:

complain about sth.:
bitterly cold:

--------------------
一前就后,过去完成时的固定句式
had hardly done ... when ...
had no sooner done ... than ...

dream of doing sth.:
plan to do:
settle down:

** L39 Am I all right?
[[./NCE2/L39 Am I all right.html]]
operation:
successful:
following:
patient:
alone:
exchange:
inquire:
certain:
caller:
relative:

have an operation:
leave me alone:
inquire about sth./sb.:

--------------------
宾语从句
NCE1 L99 L101 L133 L135 L139

refuse to do sth.:
ask for sth.:
be allowed to do sth.:

** L40 Food and talk
[[./NCE2/L40 Food and talk.html]]
hostess:
unsmiling:
tight:
fix:
globe:
despair:

in despair:

--------------------
虚拟语气(现在):
	If + did/were, 主+would/should/could/might do

take my seat:
be busy doing sth.:
Will you be doing sth?:

** L41 Do you call that a hat?
[[./NCE2/L41 Do you call that a hat.html]]
rude:
mirror:
hole:
remark:
remind:
lighthouse:

remind sb. of sth./sb.:

--------------------
need:
needn't have done:

regret doing sth.:
find sth. adj.:

** L42 Not very musical
[[./NCE2/L42 Not very musical.html]]
musical:
market:
snake:
pipe:
tune:
glimpse:
snake:
movement:
continue:
dance:
obviously:
difference:
Indian:

watch a musical:
play a tune:
have a glimpse of sth./sb.:
continue to do sth.:
tell the difference from A and B / A be different from B:

--------------------
have 万能动词

have a long walk:
at the other side of sw.:

** L43 Over the South Pole
[[./NCE2/L43 Over the South Pole.html]]
pole:
flight:
explorer:
lie:
serious:
point:
seem:
crash:
sack:
clear:
aircraft:
endless:
plain:

catch a flight:
run into serious trouble:
one point:
It seems that ...:

--------------------
- be able to:
	+ can:
	+ could:
	+ was able to:
	+ managed to do:
	+ 对比以上时态更多

order sb. to do sth.:

** L44 Through the forest
[[./NCE2/L44 Through the forest.html]]
forest:
risk:
picnic:
edge:
strap:
possession:
breath:
contents:
mend:

take a risk:
have a picnic:
at the edge of a forest:
in sb's possession:
out of breath:

rush up to sb.:
catch up with sb.:
go through:
need doing sth.:
run straight at sb.:

** L45 A clear conscience
[[./NCE2/L45 A clear conscience.html]]
clear:
conscience:
wallet:
savings:
villager:
percent:

I have a clear conscience:
Are you 100 percent sure about this?:

--------------------
be done

sb. learn that + 宾语从句:
return sth. to sb.:

** L46 Expensive and uncomfortable
[[./NCE2/L46 Expensive and uncomfortable.html]]
unload:
wooden:
extremely:
occur:
astonish:
pile:
woolen:
goods:
discover:
admit:
confine:
normal:

It occurred to sb. that ...:
It occurred to sb. to do sth.:
be astonished at sth.:
admit doing sth.:
sb. admit that...:

--------------------
- 同位语:
I have just received a letter from my brother, Tim.

- 同位语从句:
No one could account for *the fact that* one of the boxes was extremely heavy.

What = the thing that/the person that
sb. account for the fact that + 句子:

** L47 A thirsty ghost
[[./NCE2/L47 A thirsty ghost.html]]
thirsty:
ghost:
haunt:
block:
furniture:
whisky:
suggest:
shake:
accept:

shake sb's head:

be up for sale:
hear sb./sth. doing sth.:

** L48 Did you want to tell me something?
[[./NCE2/L48 Did you want to tell me something.html]]
pull:
cotton:
collect:
collection:
nod:
meanwhile:

private collection:

It is impossible for sb. to do:
... rest for a while:

** L49 The end of a dream
[[./NCE2/L49 The end of a dream.html]]
tired:
real:
owner:
spring:
mattress:
gust:
sweep:
courtyard:
smash:
miraculously:
unhurt:
glance:
promptly:

get/be tired of sth./doing sth.:
A gust of wind swept ...:
in the courtyard:
smash sth. to pieces:
glance at sth.:

--------------------!!!
分词作状语 没找到部分被动
1. (not) doing
	 主动进行/主动一般
	 (being) (not) + adj.
2. done
	 被动一般/被动完成/主动完成(少)
3. having done
	 主动完成(发生在主句之前)
	 having been + adj. (主句之前的状态)
4. having been done 在N2-69课
	 主动完成被动(发生在主句之前)

save up for year to do sth.:
for the first time in sb's life:
go to sleep:

** L50 Taken for a ride
[[./NCE2/L50 Taken for a ride.html]]
ride:
excursion:
conductor:
view:

--------------------
do/does
am/is/are+doing
--------------------
prefer
	- prefer to do sth. = prefer doing sth. = I'd prefer to do sth
	- prefer a to b  &  prefer doing a to doing b
	- prefer to do a rather than (do) b.  &  I'd prefer to do a. rather than (do) b.
	- would rather do A than do B

** L51 Reward for virtue
[[./NCE2/L51 Reward for virtue.html]]
reward:
virtue:
diet:
forbid:
hurriedly:
embarrass:
guiltily:
strict:
occasionally:

expect/receive/give + reward:
go on a diet = be on a diet:
forbid sb. to do sth.:
A be strict with B:
--------------------
L3 & L27
was/were/did

First of all,...:
write out a long list of ...:
pay sb. a visit:
was not surprised to see that...:
It was obvious that...:
ring the bell:
** L52 A pretty carpet
[[./NCE2/L52 A pretty carpet.html]]
temporarily:
inch:
space:
actually:

every inch of sth.:
That's actually a good idea:

--------------------
have been doing(不知持续与否):
	1. 过去进行的v.对现在有影响;
	2. 从过去持续(或重复!)到现在

get sth. in order:
To make matters worse...:
A short while ago...:
gaze at sth.:
in sb's spare time...:
help sb. to do sth.:

** L53 Hot snake
[[./NCE2/L53 Hot snake.html]]
hot:
fireman:
cause:
examine:
accidentally:
remains:
wire:
volt:
power line:
solve:
mystery:
snatch:
spark:

electrical wire / electric wire:
discover a cause:
the remains of a snake:
solve + problem/mystery:
remain mystery:

--------------------
did
have done
have been doing

find out:
throw away:

** L54 Sticky fingers
[[./NCE2/L54 Sticky fingers.html]]
sticky:
finger:
pie:
mix:
pastry:
annoying:
receiver:
dismay:
recognize:
persuade:
mess:
doorknob:
sign:
register:

stick to the plan:
put my finger on it:
point the finger at:
be dismayed to do sth.:
recognize the voice (of sb.):
persuade sb. (not) to do sth.:
What a mess!:
such a mess:
Sign here:
sign for sth.:
a registered letter:

send sb. to sp.:
decide to do sth.:
be busy doing sth.:
be covered with sth.:
take sb. st. to do sth.:
hang up 挂断电话:
What a mess!:
sign for sth.:

** L55 Not a gold mine
[[./NCE2/L55 Not a gold mine.html]]
gold:
mine:
treasure:
revealer:
invent:
detect:
bury:
cave:
seashore:
pirate:
arm:
soil:
entrance:
finally:
worthless:
thoroughly:
trunk:
confident:
value:

own + a gold mine:
a treasure map:
in a cave:
near/to the seashore:
pirate stories:
arm sb./sth. with sth.:
sb. be armed with sth.:
in dry soil:
find / miss + entrance:
You're worthless.:
I'm not worthless.:
car trunk:
sb. be confident that ...:
something of value:

--------------------
would do VS used to do
	- 过去状态只用used to do
	- used to do包含现在不发生了
	- used to do讨论过去习惯行为(不重要)
where & whose 引导的定语从句

dreams come true...:
be used to do sth.:
fairly soon ...:
I'm fairly certain that +句子:
I'm fairly confident that + 句子:

** L56 Faster than sound!
[[./NCE2/L56 Faster than sound.html]]
sound:
excitement:
handsome:
Rolls-Royce:
Benz:
wheel:
explosion:
course:
rival:
speed:
downhill:

make a sound:
hear a sound:
on the course:
speed it/things/this up:
go downhill:

--------------------
adj.er
adj.est
more + adj.
the most + adj.

a great deal of ...:
a great many + 可数:
break down:
A be different form B:

** L57 Can I help you, madam?
[[./NCE2/L57 Can I help you, madam.html]]
madam:
jeans:
hesitate:
serve:
scornfully:
punish:
fur:
eager:

hesitate to do sth.:
be eager to do sth.:
ask/laugh/look at/ said + scornfully:
look down on sb.:

--------------------
the way that/in which(可省略) + ...:
	1. The assistant who served her did not like the way she was dressed.
	2. I don't like the way (that) you talk to me.
	3. We want to know the way (in which) you learn new words.

ask to do sth.:
be dressed in ...:
seek out:
make sb. do sth.:

** L58 A blessing in disguise?
[[./NCE2/L58 A blessing in disguise.html]]
blessing:
disguise:
tiny:
possess:
cursed:
increase:
plant:
church:
evil:
reputation:
claim:
victim:
vicar:
source:
income:
trunk:

It is a blessing that ...:
what a blessing:
God bless you:
It's a blessing:
a blessing in disguise:
In one's possession:
Go to church:
Go to the church:
have a good/bad reputation:
Have a reputation for...:
baggage claim:
source of income/information:

--------------------
be said to do...:
It is said that...:

强调句:
	- It is(was) + 强调部分 + that(who) + 剩余部分?
	- do/does/did + v.
被动:

a number of:
sb. point out that...:

** L59 In or out?
[[./NCE2/L59 In or out.html]]
bark:
press:
paw:
latch:
expert:
develop:
habit:
remove:

become/be an expert at doing sth./sth.:
have a habit of doing sth.:
remove sth. from ...:

--------------------
表目的
	- + do sth.
		to
		in order to
		so as to
  - + ...(句子)
		so that 目的状语从句
		in order that:

complained of ...:
complain that:
spend st. doing sth.:
train sb. to do sth.:

** L60 The future
[[./NCE2/L60 The future.html]]
future:
fair:
fortune-teller:
crystal:
relation:
impatiently:

in the future:
at a village fair:
crystal clear:
a relation of yours:

--------------------
A先B后
the moment A ... B..:
	Everything stops the moment she walks in the room.
as soon as(主将从现):
	As soon as the rain stops, we shall go out.
主将从现:
	the moment/util/when/as soon as/while/before

** L61 Trouble with the Hubble
[[./NCE2/L61 Trouble with the Hubble.html]]
Hubble:
telescope:
launch:
space:
NASA:
billion:
faulty:
astronaut:
shuttle:
Endeavour:
robot-arm:
grab:
atmosphere:
distant:
galaxy:
universe:
eagle [ˈɪɡ(ə)l] eye:

grab a beer/coffee:

--------------------
will be doing
will have done
will have been doing:

right from the start:

** L62 After the fire
[[./NCE2/L62 After the fire.html]]
control:
smoke:
desolate:
threaten:
surrounding:
destruction:
flood:
authority:
grass-seed:
spray:
quantity:
root:
century:
patch:
blacken:

get it under control:
be under control:
threaten sb. with sth.:
threaten to do sth.:
have the authority to do sth.:
a large/small quantity of sth.:
take root:
for centuries:
a part of sth.:

--------------------
had been doing:

A short time before:
for miles around:
in place of...:

** L63 She was not amused
[[./NCE2/L63 She was not amused.html]]
circle:
admire:
close:
wedding:
reception:
sort:

a large circle of friends:
admire sb. for sth./doing sth.:
close friend:
at the reception:
what sort of/what kind of...:
all sorts of/ all kinds of...:

--------------------
as:
	You'll do as I say and ask no questions.
like
as if
as though

sense of humour/humor:
make a speech:
a large number of ...:
on the way home:

** L64 The Channel Tunnel
[[./NCE2/L64 The Channel Tunnel.html]]
tunnel:
port:
ventilate:
chimney:
sea:
double:
ventilation:
fear:
invasion:
officially:
connect:
European:
continent:

in the tunnel:
above/below sea level:
double check:
Sb. fear that + 句子:

--------------------
If 主 had done ..., 主 would/could ... have done. L64与过去事实相反
If you could have made(=If you had been able to make)
suggest that ... (should) do ...

it is possible to do sth...:
a serve as b:
solve the problem of a ...:
put forward a plan ...:

** L65 Jumbo versus the police
[[./NCE2/L65 Jumbo versus the police.html]]
versus:
Christmas:
circus:
present:
accompany:
approach:
ought:
weigh:
fortunate:

How much do you weigh?:
It is fortunate that + 句子...:

--------------------
should do/ought to do:
should have done/ought to have done:

be dressed up as...:
set off:
hold up the traffic/line:
let sb. off:
agreed to do sth.:

** L66 Sweet as honey!
[[./NCE2/L66 Sweet as honey.html]]
Lancaster:
bomber:
remote:
Pacific:
damage:
wreck:
rediscover:
aerial:
survey:
rescue:
package:
enthusiast:
restore:
imagine:
packing case:
colony:
bee:
hive:
preserve:
beeswax:

remote control:
do a survey:
Can you imagine that?:
It's hard to imagine.:
A colony of bees:

--------------------
have sth. done = get sth. done:

over the years:
in reasonable condition:
be worth doing...:
turn A into B:

** L67 Volcanoes
[[./NCE2/L67 Volcanoes.html]]
volcano:
active:
Kivu:
erupt:
violently:
manage:
brilliant:
liquid:
escape:
alive:

What a brilliant idea!:
That's brilliant!:
--------------------
managed to do VS was able to do:

name sth. A:
set up his camp/tent:
sb. noticed that + sentence:

** L68 Persistent
[[./NCE2/L68 Persistent.html]]
persistent:
avoid:
insist:
cross:

avoid doing sth.:
insist on doing sth.:
It is no use pretending that + sentence:
prevent sb. from doing sth.:
Fancy meeting you here.:
--------------------
no matter how/what/where/whose/who/which/when ?
even though(although/though/as) VS even if

enjoy doing sth.:
no matter how/what/where:
follow sb. around:
I was wondering.. + sentence:
would you mind my doing...:
finish doing sth.:

** L69 But not murder
[[./NCE2/L69 But not murder.html]]
murder:
instruct:
acquire:
confidence:
examiner:
suppose:
tap:
react:
brake:
mournful:

be instructed to do sth.:
Let's suppose that...:
tap on the window:
--------------------
having been done

continue doing/ to do:
be pleased with:

** L70 Red for danger
[[./NCE2/L70 Red for danger.html]]
bullfight:
drunk:
wander:
unaware:
bull:
remark:
apparently:
sensitive:
criticism:
charge:
clumsily:
bow:
safety:
sympathetically:

be unaware of …:
be aware/conscious of …:
make that stupid remark:
be sensitive about sth.:
accept criticism:
charge at sb. = attack:
for your safety:
--------------------

be busy with sth.:
at the time:
catch sight of a.:
grow quiet...:
get close to a.:
step aside:
break into cheers:
feel sorry for sb.:
look on ...:
out of the way …:
turn sb’s attention to a.:
once more:

** L71 A famous clock
[[./NCE2/L71 A famous clock.html]]
parliament:
erect:
accurate:
official:
Greenwich:
observatory:
check:
microphone:
tower:

make it official:
double check:
--------------------

all over the world:
burn down:
take its name from:
be responsible for:
be connected to:
go wrong:

** L72 A car called Bluebird
[[./NCE2/L72 A car called Bluebird.html]]
racing:
per:
Utah:
horsepower:
burst:
average:
footstep:

burst into tears:
follow in sb't footsteps:
--------------------
have difficulty in doing sth.:
be disappointed to learn that:

** L73 The record-holder
[[./NCE2/L73 The record-holder.html]]
record-holder:
truant:
unimaginative:
shame:
hitchhike:
meantime:
lorry:
border:
evade:

play truant from school:
be put to shame = put sb. to shame:
shame on you:
hitchhike to sw.:
in the meantime:
--------------------
612345+6123456(6123456)

over and over again:

** L74 Out of the limelight
[[./NCE2/L74 Out of the limelight.html]]
limelight:
precaution:
fan:
shady:
sheriff:
notice:
sneer:

stay out of the limelight:
take precaution:
sb. is a big/huge fan of a.:
on such short notice:
with a sneer/ sneer at sb.:
--------------------
a party of:
why don't we:
carry sth. to sw.:
make oneself comfortable:
don't be too hard on us:
get out of here:

** L75 SOS
[[./NCE2/L75 SOS.html]]
thick:
signal:
stamp:
helicopter:
scene:
survivor:

send a signal:
stamp out the fire:
arrive on the scene:
--------------------
fly off course:
cover sb./sth/ with a.:
get adj.:
It was not long before...:

** L76 April Fool's Day
[[./NCE2/L76 April Fool's Day.html]]
fool:
bulletin:
announcer:
macaroni:
leading:
grower:
splendid:
stalk:
gather:
process:
Signor:
present:
champion:
studio:

on the bulletin board:
leading cause of ...:
What a splendid/brilliant idea!:
--------------------
at the end of ...:

** L77 A successful operation
[[./NCE2/L77 A successful operation.html]]
mummy:
Egyptian:
temple:
mark:
plate:
disease:
last:
prove:
resin:
skin:
section:
figure:
normally:
survive:

have a rare disease:
a section of ...:
prove to be adj.:
--------------------
非限定定语从句:
	- which非限整句:
		+ 位置:
		+ 指代被修饰词
	- as非限整句
		- 位置:
		- 指代整句
	- 非限定只能who/which/whose
		- none of/neither of/any of/either of + which/whom
		- some of/many of/much of/(a) few of + which/whom
		- both of/ half of /each of/one of/two of + which/whom

--------------------
have an operation:
died of ...:
fall to pieces:
cut it open:

** L78 The last one
[[./NCE2/L78 The last one.html]]
entitle:
calm:
nerve:
concentration:
suffer:
symptom:
temper:
appetite:
produce:
urge:
satisfaction:
delighted:

entitle sb. to do sth.:
calm down:
keep calm:
calm my nerve:
have/get the nerve to do sth.:
lose sb's nerve:
lose/break/have sb's concentration:
suffer from:
have a good/bad temper:
lose sb's temper:
have/get a good/great appetite:
lose sb's appetite:
urge sb. to do sth.:
give him satisfaction:
sb. be delighted that + ...:
--------------------
light a cigarette:
sb. be sure that + ...:
keep on doing sth.:
offer sb. sth.:
make no effort to do sth.:
a packet of...:
return to normal:

** L79 By air
[[./NCE2/L79 By air.html]]
parent:
flight [flaɪt] attendant [əˈtendənt]:
frightened:
curious:
bomb:

feel frightened:
sb. be curious to find out + ...:
plant a bomb:
--------------------
Only部分倒装
1. Only(+其他部分)句首,并且不是修饰主语
	 Only police can come in. 不能倒装
2. 主句一般疑问句的语序
--------------------
a great deal:
take charge of:
be used to doing:
take off:
gain height:
touch down:
on board:

** L80 The Crystal Palace
[[./NCE2/L80 The Crystal Palace.html]]
palace:
extraordinary:
exhibition:
iron:
various:
machinery:
display:
steam:
profit:
college:

on show/on display:
make a profit:
go to college:
--------------------
be made of:
of all time:
in all:
** L81 Escape
	[[./NCE2/L81 Escape.html]]
prisoner:
bush:
rapidly:
uniform:
rifle:
shoulder:
march:
boldly:
blaze:
salute:
elderly:
grey:
sharp:

grow/change/move... + rapidly:
with a sharp blow:
--------------------
change into ...:
up and down ...:
sb. discovered that:
stand to attention:
knock him to the ground:
** L82 Monster or fish?
[[./NCE2/L82 Monster or fish.html]]
monster:
sailor:
sight:
creature:
peculiar:
shining:
oarfish:

shining example:
--------------------
claim to have done sth.:
laugh at ...:
it is (well) known that ...:
at times:
out at sea:
in any way:
it was found to be ...:
a depth of ...(34 ft):
** L83 After the elections
[[./NCE2/L83 After the elections.html]]
election:
former:
defeat:
fanatical:
opponent:
radical:
progressive:
ex-:
suspicious:

win the election:
be fanatical about sth./doing sth.:
--------------------
on duty:
on the following day:
love to do sth.:
** L84 On strike
[[./NCE2/L84 On strike.html]]
strike:
busman:
state:
agreement:
relieve:
pressure:
extend:
volunteer:
gratitude:
press:
object [ɑbˈdʒekt] v. objection n.:

go on strike:
sb. have stated that + ...:
agreement is reached about sth.:
reach an agreement:
sb. be relieved to hear that + ...:
relieve pressure:
under a lot of pressure:
to some extend:
volunteer to do sth.:
expressed sb.'s gratitude to sb.:
sb. have objected that + ...:
object to sth./sb.:
--------------------
be due to do = be going to do

--------------------
be due to do sth.:
pass/take the test:
** L85 Never too old to learn
[[./NCE2/L85 Never too old to learn.html]]
inform:
headmaster:
contribute:
gift:
album:
patience:
encouragement:
farewell:
honour:
coincidence:
total:
devote:
gardening:
hobby:

sb. inform sb. that + ...:
make a contribution:
contribute to sth.:
lose sb's patience:
have a lot of patience:
give sb. encouragement:
in one's honor:
It is a curious coincidence that + ...:
a total of ...(176):
devote oneself to sth./doing sth.:
--------------------
mark the occassion:
remember sb. for sth.:
** L86 Out of control
[[./NCE2/L86 Out of control.html]]
swing:
speedboat:
desperately:
companion:
water:
buoy:
dismay:
tremendous:
petrol:
drift:
gently:

sb. noticed with dismay that + ...:
at tremendous speed:
--------------------
come away:
move in a circle:
be used up:
before long:
** L87 A perfect alibi
[[./NCE2/L87 A perfect alibi.html]]
alibi:
commit:
inspector:
employer:
confirm:
suggest:
truth:

have a alibi:
commit a murder:
sb. confirm that + ...:
Are you suggesting + ...:
tell the truth:
--------------------
on time:
** L88 Trapped in a mine
[[./NCE2/L88 Trapped in a mine.html]]
trap:
surface:
explosive:
vibration:
collapse:
drill:
capsule:
layer:
beneath:
lower:
progress:
smoothly:

on the surface:
in a special capsule:
layers of:
a layer of:
make progress:
go/run smoothly:
--------------------
wish型虚拟语气:

lose one's life:
As it is...:
enable sb. to do sth.:
keep in touch with ...:
run out of ...:
lose heart ...:
cause sb./sth/ to do sth.:
** L89 A slip of the tongue
[[./NCE2/L89 A slip of the tongue.html]]
slip:
comedy:
present:
queue:
dull:
artiste:
advertiser:

a slip of the tongue:
a comedy show:
hold up the queue:
--------------------
do anything to do sth.:
the news get around:
feel disappointed:
at the beginning of a.:
burst out laughing:
** L90 What's for supper? 
[[./NCE2/L90 What's for supper.html]]
chip:
overfish:
giant:
terrify:
diver:
oil:
wit:
cage:
shark:
whale:
variety:
cod:
factor:
crew:

be scared/frightened out of sb's wits:
a variety of:
--------------------
it comes as a surprise to learn that + ...:
protect a. from b.:
in length:
the (total) absence of ...:
as a result:

** L91 Three men in a basket
[[./NCE2/L91 Three men in a basket.html]]
balloon:
royal:
spy:
track:
binoculars:

spy on sb./sth.:
keep track of:
--------------------
seem to be doing ...:
make for sw.:
make out:
soon afterwards:
be called in (to do):
** L92 Asking for trouble
[[./NCE2/L92 Asking for trouble.html]]
fast:
ladder:
shed:
sarcastic:
tone:

fast asleep:
Are you being sarcastic?:
Don't take that tone with me!:
--------------------
hate to do sth.:

** L93 A noble gift
[[./NCE2/L93 A noble gift.html]]
noble:
monument:
statue:
present:
sculptor:
actual:
copper:
support:
framework:
transport:
site:
pedestal:

a noble gift/man:
camp site:
--------------------
at the entrance of ...:
take sth. to pieces:

** L94 Future champions
[[./NCE2/L94 Future champions.html]]
instruct:
Los Angeles:
reluctant:
weight:
underwater:
tricycle:
compete:
yard:
gasp:

be instructed in doing sth.:
be reluctant to do sth.:
compete against:
--------------------
sb./sth. proved that + ...:
hold sb's breath:
be accustomed to doing:
be popular with ...:
be lined up:
** L95 A fantasy
[[./NCE2/L95 A fantasy.html]]
fantasy:
ambassador:
frightful:
fire:
drily:
embassy:
heaven:
basement:
definitely:
post:
shot:

live in a fantasy world:
Good heavens!:
fire a shot:
--------------------
get into such a mess:
set sth. on fire:
go on doing sth.:

** L96 The dead return
[[./NCE2/L96 The dead return.html]]
festival:
lantern:
spectacle:
moving:

make a spectacle of oneself:
--------------------
return to sp.:
be expected to be:
sth. is laid out:
it is considered unlucky for sb. doing:
be placed into:

* NCE3 
** L01 A puma at large
[[./NCE3/L01 A puma at large.html]]
puma:
spot:
evidence:
accumulate:
oblige:
hunt:
blackberry:
human:
corner:
trail:
print:
cling:
convince:
somehow:
disturb:

spot sb. doing sth.:
feel obliged to do sth.:
a trail of:
cling to sb./sth.:
sth. convinced sb. that + ...:
sb. was/were convinced that + ...:
It is disturbing to think that + ...:
--------------------
at large:
be found in:
take sth. seriously:
sth. proved adj.:
sb. confirmed that + ...:
claim to have done sth.:
find sb. doing sth.:
go on:

spotted:
accumulate:
obliged to:
claimed:
extraordinarily similar:
immediately:
convinced:

** L02 Thirteen equals one
[[./NCE3/L02 Thirteen equals one.html]]
equal:
vicar:
raise:
torchlight:
cause:
wake up with a start:
bell:
catch sight of a figure:
recognize:
local grocer:

A be equal to B:
for one cause or another:
wake up with a start:
catch sight of sb./sth.看见某人某物
--------------------
1. be always doing sth.:
2. whatever:
	 - emphasize the speaker's surprise/astonishment/anger/irritation/dismay
	 - on earth/ in the world/ fucking
3. do/does/did:
4. was/were doing 表礼貌
	 - I was hoping to do sth.
	 - I was just wondering + ...
	 - I was thinking + ...
--------------------
for one cause or another:
get enough money to do sth.:
sb. be armed with sth.:
what's going on:
recognize A as B:
give sb. a surprise:
I'm glad that + ...:
get used to sth.:

** L03 An unknown goddess
[[./NCE3/L03 An unknown goddess.html]]
goddess:
archaeologist:
Aegean:
explore:
promontory:
prosperous:
civilization:
storey:
drainage:
worship:
sacred:
fragment:
remains:
classical:
reconstruct:
rest:
full-length:
graceful:
identity:

A is/was used as a place of worship:
on a/the promontory:
drainage system:
sacred room/template/place:
have a rest:
identity card:
--------------------
sb. make a (adj.) discovery of sth.:
a. be equipped with b.:
equip sb. with sth.:
be used as:
date from ... date back to ...:
happen to do sth.:
be amazed to find that + ...:
turn out to be sth.:
despite + doing sth./despite the fact that ...:

** L04 The double life of Alfred Bloggs
[[./NCE3/L04 The double life of Alfred Bloggs.html]]
manual:
collar:
sacrifice:
privilege:
dustman:
corporation:
overalls:
shower:
secret:
status:

do manual work:
white-collar/blue-collar workers:
make a sacrifice:
sacrifice a. for b.:
have the privilege of doing sth.:
take a shower:
keep a secret:
the secret of success:
It's between you and me:
social status:
status quo:
keep the status quo:
--------------------
These days ...:
Far more adj./n.:
A be referred to as ... B:
refer to A as B:
for the simple reason that + ...:
Such is human nature, that + ...:
be willing to do sth.:
give rise to:
too embarrassed to do sth.:
be dressed in:
change into + [clothes]:
half as much as ...:
from now on:
call me/him/her A:

** L05 The facts
[[./NCE3/L05 The facts.html]]
editor:
extreme:
statistics:
journalist:
president:
palace:
publish:
fax:
impatient:
fire:
originally:

go to extreme(s) to do sth.:
publish + a book/an article/report:
send sb. a fax:
get impatient:
get/be fired:

--------------------
部分倒装:
	否定词 + 一般疑问句
	- example:
	- not / nor / neither not only
	- never
	- no
	- hardly
	- little
	- no sooner ..
	- seldom
	- not until

--------------------
provide sb. with sth.:
sb. be instructed to do sth.:
instruct sb. to do sth.:
write an article on/about sth.:
find out sth.:
sb. take a long time to do sth.:
go to press:
inform sb. that + ...:

** L06 Smash-and-grab
[[./NCE3/L06 Smash-and-grab.html]]
smash-and-grab:
arcade:
jewellery:
necklace:
ring:
background:
velvet:
headlight:
blare:
staff:
raid:
scramble:
fantastic:
ashtray:

smash sth. to pieces:
grab a beer/coffee:
go to the arcade:
background music:
scrambled eggs:
at a fantastic speed:
That's fantastic:
--------------------
独立主格
--------------------
only just:
come to a stop:
be too busy doing sth. to do sth.:
[money] + worth of + n.:
help oneself to sth.:
	1. to serve or provide oneself with (food, etc.)自己拿
	2. to take without asking or being given; steal.偷窃

** L07 Mutilated ladies
[[./NCE3/L07 Mutilated ladies.html]]
mutilate:
chew:
fiance:
microwave:
oven:
safekeeping:
Newcastle:
identify:
spokeswoman:

chewing gum:
for safekeeping:
--------------------
deal with:
go doing sth.:
Imagine sb's dismay when + ...:
so long as + ..., sb. will do sth.:

** L08 A famous monastery
[[./NCE3/L08 A famous monastery.html]]
monastery:
pass:
watchdog:
rashly:
enclosure:
monk:
privacy:
skier:
Easter:

Can I get some privacy?:
--------------------
connect a. to b. = a. be connected to b.:
for hundreds of years:
Now that + ...(原因状从):
be in difficulty:
attempt to do sth.:
receive a warm/cold welcome:

** L09 Flying cats
[[./NCE3/L09 Flying cats.html]]
fascinate:
affectionate:
mysterious:
submissive:
feline:
independence:
high-rise:
windowsill:
paratrooper:
squirrel:
air-resistance:
impact:

gain its independence:
have/make an impact on:
--------------------
the 比较级(eg. more) ..., the 比较级(eg.more) ...:
yet...:
--------------------
lead a adj. life:
learn to do sth.:
a good deal of/a great deal of un.:
be based on:
make a study of sth:
a period of + st.:
have sth. in common:
died from(事故) / died of(病):
there is no shortage of sth.:
It seems that + ...:
be likely to do sth.:

** L10 The loss of the Titanic
[[./NCE3/L10 The loss of the Titanic.html]]
Southampton:
colossal:
watertight:
compartment:
flood:
float:
tragic:
liner:
voyage:
iceberg:
lookout:
collision:
narrowly:
miss:
slight:
tremble:
faint:
horror:
abandon:
plunge:
lifeboat:
--------------------
a crew of:
be regarded as + adj./n.:
give an alarm:
in time:
realized to his horror that:
give an order:

** L11 Not guilty
[[./NCE3/L11 Not guilty.html]]
guilty:
tolerant:
declare:
hardened:
professional:
smuggler:
officious:
confidently:
dreadful:
pounce:
perfume:
sarcastically:
exempt:
import:
gel:
mixture:
unscrew:
nostril:
chalk:
baggage:

feel guilty:
be tolerant of:
be exempted from:
mixture of A and B:
--------------------
be made to do sth.:
on the other hand/on the one hand:
light up:
be greeted by sth.:

** L12 Life on a desert island
[[./NCE3/L12 Life on a desert island.html]]
desert:
unrealistic:
paradise:
wretched:
starve:
element:
opportunity:
coral:
Virgin:
Miami:
dinghy:
Caribbean:
spear:
lobster:
tanker:
genuinely:

have an opportunity to do sth.:
an element of truth/danger:
starve to death:
sb. be genuinely sorry that + ...某人真的很抱歉+...

--------------------
wish that sb. did:
wish that sb. had done:

--------------------
formed an unrealistic picture of sth.:
imagine sth./sb. to be n./adj.:
a sort of:
wish that + ...:
load a. with b.:
As sb. put it:

** L13 It's only me
[[./NCE3/L13 It's only me.html]]
costume:
consist:
sheet:
effective:
comfortable:
storeroom:
electricity:
pace:
flee:
slam:

consist of ...:
make yourself comfortable:
at your own pace:
The pace of life:
--------------------
fancy dress party:
be impatient to do sth.:
let out a cry:

** L14 A noble gangster
[[./NCE3/L14 A noble gangster.html]]
gangster:
Chicago:
protection:
promptly:
destroy:
remarkable:
band:
Florence:
city-state:
hire:
prince:
funeral:
dedicate:
memory:
valiant:

need protection:
provide protection:
for your own protection:
a band of:
give him a state funeral:
dedicate yourself/your life to sth.:
dedicate sth. to sb.:
devote oneself to sth./doing sth.:
in memory of sb. / to the memory of sb.:
--------------------
when引导的定语从句
	1. 先行词必须为时间(time, day, year...)
	2. when必须在从句中充当[6]的成分.如果从句是[1][3],那么是which引导定语从句,而不是when
	3. 在非书面语中,用that或者直接去掉
	4. 注意区分when时间状语 VS when定语从句
	5. prep.+which=when, 类似的还有方式状语
whenever:
	1. when的强调
	2. every time or any time
if真实条件句和虚拟语气:
	If did... , would do...
--------------------
There was a time when + ...:
pay money to sb.:
large sums of money:
put sb. out of business:
as long ago as:
make the remarkable discovery that + ...:
would rather do A than do B:
make a name for himself:
come to do sth.:
A be known to B as C:
A be known as B:
be at war with ...:
in times of peace:
offer to do sth.:
make money:
regard A as B:

** L15 Fifty pence worth of trouble
[[./NCE3/L15 Fifty pence worth of trouble.html]]
appreciate:
pocket [ˈpɑkɪt] money:
rattle:
thrifty:
nephew:
bounce:
pavement:
stick [stɪk]-stuck-stuck:
fire brigade:
grease:

I appreciate your honesty.:
	understanding/interesting/concern/support/patience/trust/time/help/it/that ...
--------------------
supply of sth.:
go a long way:
be exchanged for sth.  exchange a. for b.:
fill up a. with b. 用B充满A
find one's way:
advise sb. to do sth.:
On one's way to sp.:
roll up one's sleeves:
What is more=what's more:
rub a. with b.:
a special type of sth.:
hear about sth.:
reward sb. with sth.:

** L16 Mary had a little lamb
[[./NCE3/L16 Mary had a little lamb.html]]
prize:
tie:
accuse:
theft:
deny:
ashamed:
apologize:
dye:

prize money:
tie sb. to sth. = sb. be tied to sth.:
accuse sb. of doing sth.:
deny doing.../sb. deny that + ...:
be ashamed of sth./doing sth./having done sth.:
apologize to sb. (for doing sth.):
dye something + some-color.:
--------------------
tell sb. about sth.:
It's ture that + ..., but + ...:
sb. be astonished to find (that) + ...:

** L17 The longest suspension bridge in the world
[[./NCE3/L17 The longest suspension bridge in the world.html]]
suspension:
agreeable:
locate:
immortal:
span:
cable:
concrete:
length:
estimate:
capacity:
immensity:
elegant:
faintly:

agreeable/pleasant + situation/man/day:
be located in/near:
a span of ...:
life span:
a length of/lengths of + rope/pipe/wire:
It is estimated that + ...:
sb. estimates that + ...:
--------------------
little/not much/not everything is known about a.:
describe A as B:
in the midst of ...:
by no means:
be considered to be adj./n.:
sth. be named after sb.:
join a. to b. = connect a. to b.:
be taken into account = take sth. into account 考虑某事
a height of ...:
A be suspended from B:
be packed with ...:
a third of sth:
fulfill sb's dream:

** L18 Electric currents in modern art
[[./NCE3/L18 Electric currents in modern art.html]]
current:
sculpture:
mistaken:
gallery:
exhibit:
oddly:
attach:
sphere:
magnetize:
repel:
flicker:
emit:
flash:
prehistoric:
electronic:
peculiar:
shock:
emotionally:

make a sculpture / create a sculpture:
be mistaken about sth./sb.:
Oddly enough, + ...:
be attached to sb./sth. = attach a. to b.:
get an electric shock:
receive an electric shock:
give you electric shocks:
--------------------
not any more = not any longer = no longer:
The idea that + ... is mistaken:
take no/ a great/an interest in:
in response to sth.:
be/sound/look/seem familiar to sb.:
go mad:
on and off:
It was rather like ...:
seem adj.(designed) to do sth.:
be designed to do sth.:

** L19 A very dear cat
[[./NCE3/L19 A very dear cat.html]]
dear:
kidnapper:
considerable:
wealthy:
orderly:
disappearance:
anonymous:
ransom:
cardboard:
withdraw:
punctually:
astound:

be dear to somebody:
a considerable amount/number of sth.:
in an orderly fashion/manner:
anonymous letter/(phone) call:
remain anonymous:
a ransom of + (money):
It astounded sb. that + ...:
--------------------
share sth. with sb.:
take a short/long walk:
get worried:
in safe hands:
at first:
go to the police:
make sth. clear:
change sb's mind:
follow sb's instructions:
keep sb's word:
sure enough:
sb. explained that + ...:
Considering + n., + ...:
in more ways than one:

** L20 Pioneer pilots
[[./NCE3/L20 Pioneer pilots.html]]
pioneer:
lord:
Calais:
overland:
--------------------
as if/though:

--------------------
offer sth. to sb. = offer sb. sth.:
a prize of + (money):
make an attempt to do sth.:
attempt to do sth.:
be forced to do sth.:
be picked up by ...:
on the same day:
It looked as if/though + 虚拟句:
	eg.	It looked as if there would be an exciting race across the Channel.
	eg.	It looked as though there would be an exciting race across the Channel.

** L21 Daniel Mendoza
[[./NCE3/L21 Daniel Mendoza.html]]
boxing:
boxer:
bare:
prizefighter:
crude:
marquis:
technically:
science:
popularity:
adore:
alike:
fame:
eminent:
bitterly:
bet:
academy:
extravagant:
poverty:

with sb's bare hands:
Technically speaking, + ...:
gain/grow/increase in popularity:
great minds think alike:
rise to fame:
quarrel/complain/be disappointed ... + bitterly:
bet ($) on sth.:
I bet + ...:
live in poverty:
--------------------
Because of + n.:
be born in + (year):
draw up:
a set of sth.:
change a. into b.:
bring a. to b.:
in sb's day:
be quick to do sth.:
in fact:
turn against sb.:
It is clear that + ...:
settle the argument:
It was not until [stp.] that + ...:
	stp. can not only be 'in 1790' but also 'third match' as well
as much as ...   half as much as:
be in debt:

** L22 By heart
[[./NCE3/L22 By heart.html]]
run:
lines:
part:
falter:
cast:
aristocrat:
imprison:
Bastille:
jailer:
colleague:
curtain:
reveal:
cell:
blank:
squint:
dim:
sire:
proceed:

play the role of:
sb. be cast in the role of = cast sb. in the role of:
the curtain goes up/rises/comes down/falls:
a blank sheet of paper:
squinte at sb./sth.:
in the dim light:
proceed to do sth.:
--------------------
insist/suggest that + ... (should) do (虚拟语气)

--------------------
for days/hours/years on end:
in many ways:
be required to do sth.:
expect sb. to do sth./ sb. be expected to do sth.:
learn/know sth. by heart:
have cause to do sth.:
sb. insisted that + ...(should) do (虚拟语气) 要求
sb. insisted that + ...(非虚拟) 认为
be written out in full:
play a joke on sb.:
present sth. to sb.:
look on:
at last:
be anxious to do sth. = be eager to do sth. = can't help doing sth.急于做某事
stare at:
read sth. to sb.:
much to sb's sth.[surprise/amusement/dismay/disappoint]:

** L23 One man's meat is another man's poison
[[./NCE3/L23 One man's meat is another man's poison.html]]
poison:
illogical:
octopus:
delicacy:
repulsive:
stomach:
fry:
fat:
abuse:
snail:
luxury:
associate:
despise:
appeal:
shower:
stroll:
impulse:
dozen:
fancy:

One man's meat is another man's poison:
it is illogical to do sth.:
turn sb's stomach:
sick to my stomach:
animal fat:
a. received more abuse than b.:
associate a. with b.:
appeal to sb.:
After a heavy shower ...:
be in the shower:
take a shower:
take a stroll / go for a stroll:
have the impulse to do sth.:
	a sudden strong wish or need to do something, without stopping to think about the results
dozens of sth./sb.:
--------------------
for instance:
at the idea of ...:
The sad truth is that + ...:
be brought up to do sth.:
stick to sth.:
notice sb. doing sth.:
be delighted to do sth.:
stay to dinner = stay for dinner:
to sb's dismay:
take possession of sp.:

** L24 A skeleton in the cupboard
[[./NCE3/L24 A skeleton in the cupboard.html]]
skeleton:
seemingly:
respectable:
conceal:
vivid:
dramatic:
ruin:
heroine:
fiction:
varying:
medicine:
guestroom:
unpack:
stack:
underclothes:
drawer:
petrify:
dangle:
sway:
unsympathetic:
medical:

a skeleton in the cupboard/closet:
sth. be concealed from sb. = conceal sth. from sb.对某人隐瞒某事
drama queen:
ruin my day:
science fiction:
to varying degrees:
in the drawer/ from the drawer:
be petrified of sth.:
medical student/school:
--------------------
It is all very well (and good)..., but not in reality + ...:
make one's hair stand on end:
in sb's youth:
show sb. to sp.:
bring sth. with sb.:
it give sb. the impression that + ...:
be about to do sth.:
leap out at sb.:
once upon a time:

** L25 The Cutty Sark
[[./NCE3/L25 The Cutty Sark.html]]
impressive:
steamship:
vessel:
era:
Java:
rudder:
roll:
steer:
temporary:
plank:
fit:
equator:
delay:

a new era/ the beginning/end of an era:
A be fitted with B:
delay in doing sth.:
--------------------
A be replaced by B:
take the lead (in doing sth.) lose one's lead:
be struck by:
from side to side:
it become impossible to do sth.:
with great difficulty:
There is a danger that + ...:
call in on/at:
by now:
There is no doubt that + ...:

** L26 Wanted, a large biscuit tin
[[./NCE3/L26 Wanted, a large biscuit tin.html]]
influence:
pride:
taste:
exert:
subtle:
advertiser:
classify:
magic:
sample:
devise:
capture:
manufacturer:
wheelbarrow:
boot:
ingredient:
crane:
anticipate:

bad/good/positive etc. influence (on sb.):
have an influence on sb./sth.:
be influenced by ...:
pride oneself on (doing) sth. = be pround of:
have good/bad taste in sth.:
exert a subtle/some influence on/over sb.:
have a subtle mind:
classify a. as/under b.:
say the magic word:
free samples of sth.:
devise a way/plan to do sth.:
capture the attention of sb. = capture sb's attention引起某人的注意
in the boot of sb's car:
It is anticipated that + ...:
sb. anticipate that + ...:
--------------------
as引导的倒装句 表 让步
	- Much as ..., ...
	- adj./n./v. + as ...,句子:
	- 为什么要试试自己查语法书
--------------------
avoid being done:
be free to do sth.:
in sb's effort to do sth.:
get sth. for nothing:
enable sb. to do sth.:
a. has made it possible for sb. to do sth.:
come along:
buy sth. from sb.:

** L27 Nothing to sell and nothing to buy
[[./NCE3/L27 Nothing to sell and nothing to buy.html]]
philosopher:
wisdom:
priest:
spiritual:
grudge:
surgeon:
passer-by:
dignity:
deliberately:
consequence:
afflict:
ease:
nature:
contempt:
envious:

question/doubt the wisdom of (doing) sth.:
give sb. spiritual comfort:
grudge doing sth.:
have/hold a grudge against sb.:
die/treat/do sth. with dignity:
have consequences:
be afflicted with/by sth.:
with great/considerable ease:
love of nature:
speak of/treat sb./sth. with contempt:
be/feel/get/become envious of sb.:
--------------------
live by doing sth.:
in the light of sth./in light of:
in terms of sth.:
It is difficult to do sth.:
seem to be/do sth.:
be the exception to the rule:
in doing sth.:
choose to do sth.:
be free from sth.:
in the open (air):

** L28 Five pounds too dear
[[./NCE3/L28 Five pounds too dear.html]]
wares [wer] n. silverware n.:
anchor:
deck:
tempt:
bargain:
disembark:
assail:
marble:
inscribe:
favour:
gesticulate:
outrageous:
thrust:

on the deck:
tempt sb. into doing sth.  tempt sb. to do sth.  be tempted to do sth.:
bargain with sb.:
make a bargain with ...:
be assailed by sb.:
A be inscribed on B A被雕刻在B上
as a special/personal favor (to sb.):
do me a favor:
it is outrageous (that) + ...:
thrust sth. into sw. (especially my hands):
--------------------
speed to sp.:
sb. have no intention of doing sth.:
I can't conceal the fact that + ...:
sb. be impressed by sth.:
go to great lengths to do sth.:
prove that + ...:
go to great lengths to prove that + ...:
get rid of sb.:
at the base of sth.:
let me have it:
indicate that + ...:
reduce the price to $:
throw up one's arms:
get back to sp.:
fill a. with b.:
to this day:

** L29 Funny or not?
[[./NCE3/L29 Funny or not.html]]
largely:
comic:
universal:
comedian:
distasteful:
pester:
dread:
recovery:
plaster:
console:
hobble:
compensate:
mumble:

comic book/movie/novel:
have a universal appeal:
pester sb. to do sth.:
dread doing sth. 惧怕做某事
dread sb. doing sth.:
make a complete/quick/speedy/slow recovery:
console sb./yourself that + ...:
compensate (for sth.) = make up for:
--------------------
whether/whether or not .../whether...or not 主从 VS 让步状语
	1. 主从Whether引导, 不可被if代替, 在句中做1的成分
	2. whether引导让步状语从句, 在句子中状语的成分
have:
--------------------
be bound up with:
find it hard to do sth.:
make sb. laugh to tears:
stem from ...:
come into fashion:
base A on B:
judge for yourself:
do one's best (to do sth.):
take heart:
be good for sb.:
in the process:

** L30 The death of a ghost
[[./NCE3/L30 The death of a ghost.html]]
labourer:
overnight:
hay:
corn:
moonlight:
conscientious:
suspect:
desert:
regiment:
action:
recluse:

stay overnight in the hay:
in the moonlight:
suspect (that) + ...:
a regiment of ...:
be killed in action:
--------------------
every time:
wake up to find that + ...:
old elder eldest:
	older oldest:
--------------------
for years:
stay up (overnight):
it became an accepted fact that + ...:
be supposed to be/do sth.:
remain in doing sth.:
none other than:
think it one's duty to do sth.:
keep sb. in hiding:
find it impossible to do sth.:

** L31 A lovable eccentric
[[./NCE3/L31 A lovable eccentric.html]]
lovable:
eccentric:
disregard:
convention:
conscious:
invariably:
routine:
shrewd:
eccentricity:
legendary:
snob:
intensely:
bedraggled:
dump:
apologetic:
reprimand:
stage:
elaborate:

disregard social conventions:
be conscious of (doing) sth.:
sb. be conscious that + ...:
daily routine:
dump sth. on sth.:
be apologetic about/for sth.:
reprimand sb. for (doing) sth.:
elaborate plan/design/meal:
--------------------
draw attention to sb.:
win sb. sth.:
add a. to b.:
up to the time of sth.:
go on foot:
be caught in:
sb. request to do sth.:
present sb. with sth.:
invite sb. to do sth.:

** L32 A lost ship
[[./NCE3/L32 A lost ship.html]]
salvage:
Barents:
sunken:
cargo:
bullion:
scour:
chest:
contents:
belongings:
item:
cruiser:
find:
log:
piece:
convoy:
torpedo:
submarine:
naval:
ministry:
--------------------
salvage operation:
a cargo of:
piece together:
in a convoy:
a naval officer:
--------------------
sb. be under the impression that + ...:
together with:
come to light:

** L33 A day to remember
[[./NCE3/L33 A day to remember.html]]
prelude:
unforeseen:
series:
catastrophe:
crockery:
suburb:
collide:
learner:
panic:
windscreen:
alongside:
slide:
stray:
confusion:
greedily:
devour:

a prelude to sth.:
unforeseen + changes/problems/circumstances:
a series of:
be a catastrophe for sb.:
in the suburbs/ a suburb of city:
collide with=run into:
get into a panic:
draw up alongside sb.:
slide off/open:
stray dogs:
There is some confusion about sth.:
--------------------
get out of control:
What invariably happens is that + ... 总是发生的是+...
set up a chain of reactions:
keep an eye on sb.:
be/speak/talk on the phone:
hang up (on sb.):
attend to sb./sth.:
reduce sb. to tears:
on a big/large/small scale:
drawing up alongside sb.:
rush hour:
pull up:
all of a sudden = suddenly:
pile up:
get the traffic on the move:
sweep up:
benefit from sth.:

** L34 A happy discovery
[[./NCE3/L34 A happy discovery.html]]
antique:
fascination:
forbidding:
muster:
pretentious:
labyrinth:
musty:
rarity:
assorted:
junk:
litter:
dedicated:
bargain:
dealer:
cherish:
amply:
masterpiece:
mere:
prise:
carve:
dagger:
miniature:
composition:

antique shop/store/desk/jewelry:
hold/have a fascination for sb./sth.:
forbidding place/look:
muster (up) the courage/confidence/to do sth.:
in the labyrinth of sth.:
junk mail:
be littered with sth.:
sb. cherish the hope that + ...:
The mere fact that + ... + 23456:
prise sth. open:
carve a. from/out of b.=a. be carved from/out of b.:
--------------------
There is always hope that + ...:
by chance:
above all:
be bent on doing sth.:
sb. cherish the hope that + ...:
describe to sb. what/how + 宾从 = describe sth. to sb. 向某人描述...
pick up:
sb. can't/couldn't be bothered to do sth.:
beg sb. to do sth.:
at the bottom of ...:

** L35 Justice was done
[[./NCE3/L35 Justice was done.html]]
justice:
court:
law:
innocence:
undertake:
arduous:
abstract:
concept:
mete:
interference:
accord:
premises:
convert:
disused:
fireplace:
muffle:
chip:
blacken:
emerge:

justice has been done/served:
court of law; courts of law:
prove sb's innocence:
undertake a task/a project/research/a study/a journey:
arduous task of doing sth./arduous journey:
go through/embark on/begin arduous journey:
understand + abstract concept:
interference in sth.:
Sorry for the interference, + ...:
I hope you don't mind the interference, but + ...:
of sb's/sth's own accord:
on the premises of a.:
convert a. to/into b.:
emerge from sp.:
--------------------
however = no matter how 让步状语
get + done 被动
--------------------
beyond doubt:
make mistakes:
There are rare instances when + ...:
cease to do:
be independent of:
in part:
run to tell sb.:
ring up:
tap at sth.:
listen for ...:
be unable to do sth.:
break into sp.:
be handed over to sb.:

** L36 A chance in a million
[[./NCE3/L36 A chance in a million.html]]
credulous:
improbable:
obscure:
maidservant:
presume:
wickedly:
plot:
downfall:
naive:
unacceptable:
conspire:
incredible:
resemblance:
scorn:
acquaint:
reunite:
assume:

It seems (highly/wildly) improbable that + ...:
be presumed dead/innocent/guilty:
presume that + ...:
plot to do sth.:
plot against sb.:
lead to sb's downfall:
bring about sb's downfall:
it be naive enough to believe/think + ...:
sb. be naive enough to believe/think + ...:
it be unacceptable to do sth.:
conspire to do sth.:
it is incredible (to sb.) that + ...:
it is incredible how + ...:
it is incredible to do sth.:
bear a close/strong/striking resemblance to sb./sth.:
bear little/no resemblance to sb./sth.:
resemblance to ...:
pour scorn on:
pour scorn on the idea/suggestion/plan/advice:
acquaint sb. with sth.:
sb. be acquainted with sth.:
be reunited with sb.:
assuming that + ...:
it seems/is reasonable to assume that + ...:
--------------------
to do 非谓语结构
--------------------
a chance in a million:
bring ... to a conclusion:
sb. accepted the fact that:
bring about sth.:
and so on:
anyone but:
be thought to:
stop to do:
comment on sth./sb.:
suggest that + ...:
there is/was a chance that + ...:
needless to say:
towards the end of + sth.:
be separated from:
make one's way back to sp.:
return to:
What become of:

** L37 The Westhaven Express
[[./NCE3/L37 The Westhaven Express.html]]
express:
punctual:
condition:
unshakable:
faith:
cancel:
exceptionally:
dislocate:
blame:
consult:
direct:
odd:
reflect:
advantage:
mighty:
dawdle:
chug:
lodge:
complaint:
triumph:
asterisk:
conduct:

be punctual for:
condition sb. to (do) sth.:
sb. be conditioned to do sth.:
develop an unshakable belief/faith in sb./sth.:
have/lose faith in sb./sth.:
blame sb. for sth.:
blame sth. on sb.:
consult the map/manual/dictionary:
go/fly direct:
It is/seems odd that + ...:
reflect that + ...:
reflect on sth.:
lodge a complaint:
have/make/receive/lodge a complaint:
a note of triumph:
conduct sb. to sp.:
--------------------
neither + 部分倒装
not... but ... 不是... 而是...
--------------------
It is all too easy to do sth.:
sb. noted with satisfaction that + ...:
can't help doing sth.:
strike sb as sth./sb.:
take advantage of sth./sb.:
wish to do sth.:
hold up:
It dawned on me that + ...:
roar down:
not do sth. but + ...:
hear of:
copy of sth.:
in black and white:
at the bottom of sth.:
