#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

Unrepresentative Data

Definition Drawing a conclusion based on data from an unrepresentative or biased sample.

Unrepresentative data are data that are not proportionately drawn from all relevant subclasses. For example, if one wished to generalize about the opinion of the American people on a particular issue, it would be necessary to consider data proportionately drawn from subclasses based on race, age, educational status, sex, geographical area, and perhaps even religion and political affiliation. In most cases, data from other subclasses, such as body weight and hair color, would not be relevant.

It is also important to avoid using data that may be biased. This can occur in at least three ways. First, the data collected may be tainted by virtue of the bias of the gatherer. Opinion data gathered by a political party or by an advocacy group should be immediately suspect. Second, data purporting to support claims about any matter are biased if collected from only one or a few subgroups of the target population, especially if data are collected from groups that might have strong positive or negative opinions about the matter at issue. For example, if one were interested in assessing campus opinions about college athletics, one should not survey just members of intercollegiate athletic teams. Neither should one survey just nonathletes. If you were interested in the quality of a recent film release, you should not form a judgment exclusively on the basis of evaluations collected from readers of a single magazine, since its subscribers are a subgroup with special interests and tastes. Third, you should not give much credence to the call-in or email polls frequently taken by networks, newspapers, and magazines these days. If you want to know what “the American people” think about a particular issue, go find a reputable poll that is based on the careful surveying of representative groups.

Another kind of unrepresentative data might be data of differing quality. If one compared statistics gathered with modern techniques of statistical reporting and analysis with statistics gathered under very different methodological and technical conditions, almost any conclusion would be highly questionable. For example, if one were to compare statistics on the number of violent crimes committed in the United States in 2007 with statistics about similar phenomena in 1947, the comparative conclusion would be quite suspect.

EXAMPLE “It has been concluded from a recent study involving more than one hundred thousand people in the state of Florida that 43 percent of the American people now spend at least two hours a day in some form of recreational activity.” A reconstruction of this argument in standard form clearly reveals the statistical flaw: 

Since 43 percent of Florida residents spend at least two hours a day in some form of recreational activity, (premise)
[and the people of Florida are representative of all other Americans,] (implicit premise)
Therefore, 43 percent of all Americans spend at least two hours a day in some form of recreational activity. (conclusion)

To draw such a conclusion about the leisure-time activities of all American people would not be warranted. The state of Florida is populated by a disproportionate number of retired and leisure-oriented people, so data based on a Florida population alone would be unrepresentative.

EXAMPLE “We had a mock election on campus today, and the Democratic candidate won. So I’m pretty confident that she will win the election in November, especially because more than two thousand students voted. That seems to be a big enough sample. Don’t you agree?”

A college population hardly qualifies as a representative sample of voters, even if the size of the sample is actually larger than the number usually polled by sophisticated polling organizations. If a sample is not drawn from relevant representative subclasses, its size is of no consequence.

EXAMPLE “A recent study of how Americans spend their vacations revealed that 52 percent of the people spend five or more days a year at ocean beaches.” This study was based on a sample of fifty thousand Virginians, drawn from every relevant subgroup of the population, but it is hardly representative. Most areas of Virginia are close to popular beaches within the state as well as in Maryland and North and South Carolina. For that reason, a disproportionate number of the residents of Virginia, when compared with people from many other states, vacation at the beach.

ATTACKING THE FALLACY
Suggestions for responding to arguers who use unrepresentative data are similar to those for dealing with arguers who use too small a sample. If you encounter a case in which someone has used suspect data, you might expose the flawed statistical assumption by making it part of a similar argument with an absurd conclusion. For example:

Since most of the one thousand people in attendance at the county dog show own dogs, (premise)
[and what is true of the people at the dog show is true of the entire population,] (implicit premise)
Therefore, most people own dogs.(conclusion)
If the arguer sees nothing wrong with the second premise, no attack against unrepresentative data may turn out to be very successful, but you might try one other strategy. Threaten the arguer with the possibility of your gathering another set of data of the same size from people living in local nursing homes as support for a claim that most people do not own dogs. If samples of equal size can support two contradictory conclusions, it should be clear that something must be wrong with the representative quality of the data.
