#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+begin_verse

This chapter should help you to:
 Define or describe in your own words the essential features of each of the
 named fallacies that violate the sufficiency criterion of a good argument.
 Recognize, name, and explain the faulty pattern of reasoning in each of these
 fallacies when it is encountered in ordinary discourse or discussion.
 Make use of effective strategies for attacking or helping others to correct their
 faulty reasoning when they commit any of these fallacies.
 One who presents an argument for or against a position should attempt to provide
 relevant and acceptable reasons of the right kind, that together are sufficient in
 number and weight to justify the acceptance of the conclusion.
 The fallacies discussed in this chapter are particular ways in which insufficient
 evidence can cause an argument to go wrong. Some arguments use too little evi
dence or no evidence at all; others use biased evidence or only the appearance of
 evidence; still others omit key or crucial evidence from the mix. Arguments that
 commit so-called causal fallacies draw conclusions about causal relationships that
 are not sufficiently supported by appropriate evidence.
 Each of these patterns of reasoning is a way in which an argument may violate
 the sufficiency criterion of a good argument by failing to provide sufficient grounds
 for its conclusion. If the premises are not sufficient in number, kind, and weight,
 they may not be strong enough to establish the truth of the conclusion.
 160
fallacies that violate the sufficiency criterion 161
 The fallacies that violate the sufficiency criterion are divided into two groups:
 (1) the fallacies of missing evidence, and (2) causal fallacies.







#+end_verse
