#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
#+begin_verse


Insufficient Sample
Definition Drawing a conclusion or generalization from too small a sample
of cases.
The evidence used in a case of insufficient sample is usually acceptable and relevant,
but there is not enough of it to establish the conclusion of the argument. This fallacy is sometimes called a hasty generalization because an arguer has been too
quick to draw a conclusion, given the skimpiness of the evidence. It is not uncommon for an arguer to draw a conclusion or generalization based on a single piece of
supporting evidence or even a personal anecdote, a move that might be described as
committing the fallacy of the lonely fact.
It is sometimes difficult to determine just what constitutes a “sufficient” number
of instances for drawing any particular conclusion. The sufficiency of a sample is
fallacies that violate the sufficiency criterion 161partially determined by each context of inquiry, but it should not be assumed that an
increase in the number of instances means that the claim for which they are evidence
will be more reliable. There is a point beyond which the increase in the number of instances has a negligible effect on the sufficiency of evidence.
Some areas of inquiry have quite sophisticated guidelines for determining the
sufficiency of a sample, such as in voter preference samples or television viewing
samples. In most areas, however, there are no such guidelines to assist us in determining what would be sufficient grounds for the truth of a particular conclusion.
EXAMPLE “Vitamin C really works. Every member of my family used to have at
least one winter cold every year. Last fall each of us started taking one thousand
milligrams of vitamin C a day, and there hasn’t been even a sniffle at our house
in more than nine months.” If we reconstruct this argument in standard form, we
have the following:
Since each member of my family for nine months has been taking one thousand milligrams of vitamin C daily, (premise)
and during that period we have had no colds, (premise)
and during the previous cold season, we each had at least one cold, (premise)
[and the sample of one family is a sufficient sample to determine what is true
for all people,] (implicit premise)
Therefore, a vitamin C therapy of one thousand milligrams daily will prevent
the common cold. (conclusion)
Such data may be interesting enough to encourage some people to consider experimenting with vitamin C therapy, but the argument hardly makes the case for the
program’s effectiveness. The claim made in the implicit fourth premise about the
sufficiency of a sample limited to one homogeneous family is highly questionable
and would not justify drawing any conclusion about the cold-preventing effects of
daily megadoses of vitamin C. It is quite possible that a number of other factors
could account for the no-cold phenomenon in the arguer’s family during that particular nine-month period.
EXAMPLE It is not unusual to pick up a few items at a grocery store other than the one
at which we normally shop and discover that the prices on those few items are lower
than the prices on the same items at our regular store. In such a situation we might
infer that we should switch grocery stores in order to save on our monthly grocery
bill. If we had found the prices on those few items to be higher, we might have inferred
that we should stick with our regular store. However, neither inference would be warranted because the samples used are too small. Only the results of a more comprehensive comparative survey of the prices on all the items we typically buy during the
month could possibly justify a conclusion about where to shop.
EXAMPLE “My experience with my ex-wife was such a bad one that I have no intention of ever marrying again. In fact, I wouldn’t recommend marriage to
anyone.” This reasoning is obviously based on a very small sample. This man’s
one experience with marriage apparently convinced him that marriage was not a
worthwhile institution for him, his friends, and probably everyone else. It is quite
possible, however, that his one negative experience with marriage could be attributed to his own flaws or to those of his wife, rather than to flaws in the institution
of marriage. It can at least be said that the conclusion concerning the value of marriage deserves a larger sample.
ATTACKING THE FALLACY Those who present you with an argument based on a
single case or an insufficient sample are usually quite convinced of the truth of
their claim. Perhaps the reason that it seems so convincing to them is that it often
comes out of a significant personal experience. You should, however, find some
way to make it clear that a personal insight falls far short of being a good
argument.
It is possible, in some cases, that what appears to be a one-instance generalization may not be intended as an argument at all; it may simply be the expression of
an opinion, accompanied by an illustration. To clarify the matter, you might ask,
“Are you just expressing an opinion, or are you presenting an argument?”
If the arguer denies that he or she is just expressing an opinion, a reconstruction of his or her argument may be helpful. A reconstruction of the argument, spelling out the implicit premise that is being used—namely, that one or a few cases constitute sufficient grounds for drawing a conclusion about all cases—should clearly
demonstrate to the arguer the flawed character of the argument. If it doesn’t, an
absurd counterexample might: “Faculty kids are real brats. I babysat with one the
other night, and he was spoiled, rude, and uncontrollable.” If necessary, put the argument into standard form:
Since the faculty child I babysat for recently was a brat, (premise)
[and one faculty child is a sufficient sample of faculty children to determine
what is true of all faculty children,] (implicit premise)
Therefore, all faculty children are brats. (conclusion)
It is highly unlikely that your opponent could embrace, without embarrassment, the
second premise, once it is spelled out; therefore, he or she could not continue to
hold to a similar premise in his or her own argument.



#+end_verse
