#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
** The World of the Greek City-States (c. 750--c. 500 B.C.)

Focus Question: What were the chief features of the polis, or city-state, and how did the major city-states of Athens and Sparta differ?


In the eighth century B.C., Greek civilization burst forth with new energies, beginning the period that historians have called the Archaic Age of Greece. Two major developments stand out in this era: the evolution of the polis as the central institution in Greek life and the Greeks’ colonization of the Mediterranean and Black Seas.

*** The Polis
The Greek polis (plural, poleis) developed slowly during the Dark Age and by the eighth century B.C. had emerged as a truly unique and fundamental institution in Greek society. In a physical sense, the polis encompassed a town or city or even a village and its surrounding countryside. But each had a central place where the citizens of the polis could assemble for political, social, and religious activities. In some poleis, this central meeting point was a hill, which could serve as a place of refuge during an attack and later in some sites came to be the religious center on which temples and public monuments were erected. Below this acropolis would be an agora, an open space that served both as a place where citizens could assemble and as a market.


Poleis varied greatly in size, from a few square miles to a few hundred square miles. The larger ones were the product of consolidation. The territory of Attica, for example, had once had twelve poleis but eventually became a single polis (Athens) through a process of amalgamation. The population of Athens grew to about 250,000 by the fifth century B.C. Most poleis were much smaller, consisting of only a few hundred to several thousand people.


Although our word politics is derived from the Greek term polis, the polis itself was much more than just a political institution. It was, above all, a community of citizens in which all political, economic, social, cultural, and religious activities were focused. As a community, the polis consisted of citizens with political rights (adult males), citizens with no political rights (women and children), and noncitizens (slaves and resident aliens). All citizens of a polis possessed basic rights, but these were coupled with responsibilities. The Greek philosopher Aristotle argued that the citizen did not just belong to himself; 'we must rather regard every citizen as belonging to the state.' The unity of citizens was important and often meant that states would take an active role in directing the patterns of life. However, the loyalty that citizens had to their poleis also had a negative side. Poleis distrusted one another, and the division of Greece into fiercely patriotic sovereign units helped bring about its ruin. Greece was not a united country but a geographical concept. The cultural unity of the Greeks did not mean much politically.

*** A New Military System: The Greek Way of War
As the polis developed, so did a new military system. In earlier times, wars in Greece had been fought by aristocratic cavalry soldiers---nobles on horseback. These aristocrats, who were large landowners, also dominated the political life of their poleis. But by the end of the eighth century and the start of the seventh, a new military order came into being that was based on hoplites, heavily armed infantrymen who wore bronze or leather helmets, breastplates, and greaves (shin guards). Each carried a round shield, a short sword, and a thrusting spear about 9 feet long. Hoplites advanced into battle as a unit, forming a phalanx (a rectangular formation) in tight order, usually eight ranks deep. As long as the hoplites kept their order, were not outflanked, and did not break, they either secured victory or, at the very least, suffered no harm. The phalanx was easily routed, however, if it broke its order. The safety of the phalanx depended on the solidarity and discipline of its members. As one seventh-century B.C. poet noted, a good hoplite was 'a short man firmly placed upon his legs, with a courageous heart, not to be uprooted from the spot where he plants his legs.'


The hoplite force had political as well as military repercussions. The aristocratic cavalry was now outdated. Since each hoplite provided his own armor, men of property, both aristocrats and small farmers, made up the new phalanx. Those who could become hoplites and fight for the state could also challenge aristocratic control.


In the new world of the Greek city-states, war became an integral part of the Greek way of life. The Greek philosopher Plato described war as 'always existing by nature between every Greek city-state.'6 The Greeks created a tradition of warfare that became a prominent element of Western civilization. For example, the Greeks devised excellent weapons and body armor, making effective use of technological improvements. Greek armies included a large number of citizen-soldiers, who gladly accepted the need for training and discipline, giving them an edge over their opponents’ often far larger armies of mercenaries. Moreover, the Greeks displayed a willingness to engage the enemy head-on, thus deciding a battle quickly and with as few casualties as possible. Finally, the Greeks demonstrated the effectiveness of heavy infantry in determining the outcome of battle. All of these features of Greek warfare remained characteristic of Western military tactics for centuries.


*** Colonization and the Growth of Trade
Between 750 and 550 B.C., large numbers of Greeks left to settle in distant lands. Poverty and land hunger created by the growing gulf between rich and poor, overpopulation, and the development of trade were all factors that led to the establishment of colonies. Some Greek colonies were simply trading posts or centers for the transshipment of goods to Greece. Most were larger settlements that included good agricultural land taken from the native populations in those areas. Each colony was founded as a polis and was usually independent of the metropolis ('mother polis') that had established it.


In the western Mediterranean, new Greek settlements were established along the coastline of southern Italy, southern France, eastern Spain, and northern Africa west of Egypt. To the north, the Greeks set up colonies in Thrace, where they sought good farmland to grow grains. Greeks also settled along the shores of the Black Sea and secured the approaches to it with cities on the Hellespont and Bosporus, most noticeably Byzantium, site of the later Constantinople (Istanbul). By establishing these settlements, the Greeks spread their culture throughout the Mediterranean basin. Colonization also led to increased trade and industry. The Greeks on the mainland sent their pottery, wine, and olive oil to these areas; in return, they received grains and metals from the west and fish, timber, wheat, metals, and slaves from the Black Sea region. In many poleis, the expansion of trade and industry created a new group of rich men who desired political privileges commensurate with their wealth but found them impossible to gain because of the power of the ruling aristocrats.


*** Tyranny in the Greek Polis
The desires of these new groups opened the door to the rise of tyrants in the seventh and sixth centuries B.C. They were not necessarily oppressive or wicked, as our word tyrant connotes. Greek tyrants were rulers who seized power by force and who were not subject to the law. Support for the tyrants came from the new rich, who made their money in trade and industry, as well as from poor peasants, who were in debt to landholding aristocrats. Both groups were opposed to the domination of political power by aristocratic oligarchies.


Tyrants usually achieved power by a local coup d’e´tat and maintained it by using mercenary soldiers. Once in power, they built marketplaces, temples, and walls that created jobs, glorified the city, and enhanced their own popularity. Tyrants also favored the interests of merchants and traders. Despite these achievements, however, tyranny fell out of favor by the end of the sixth century B.C. Its very nature as a system outside the law seemed contradictory to the ideals of the Greek community. Although tyranny did not last, it played a significant role in the course of Greek history by ending the rule of narrow aristocratic oligarchies. The end of tyranny opened the door to greater numbers of people in government. Although this trend culminated in the development of democracy in some communities, in other states expanded oligarchies of one kind or another managed to remain in power. Greek states exhibited considerable variety in their governmental structures; this can perhaps best be seen by examining the two most famous and most powerful Greek city-states, Sparta and Athens.


*** Sparta
The Spartans originally occupied four small villages in the southwestern Peloponnesus, in an area known as Laconia, that eventually became unified into a single polis. This unification made Sparta a strong community in the region and enabled the Spartans to conquer the neighboring Laconians. Many Laconians became periokoi, free inhabitants but not citizens who were required to pay taxes and perform military service for Sparta. Other Laconians became helots (the name is derived from a Greek word for 'capture'). They were bound to the land and forced to work on farms and as household servants for the Spartans.


When the land in Laconia proved unable to support the growing number of Spartan citizens, the Spartans looked for additional territory nearby and, beginning around 730 B.C., undertook the conquest of neighboring Messenia despite its larger size and population. Messenia possessed a large, fertile plain ideal for growing grain. After its conquest, which was not completed until the seventh century B.C., the Messenians were made helots and forced to work for the Spartans.


**** The New Sparta
To ensure control over their conquered Laconian and Messenian helots, the Spartans decided to create a military state. By the early sixth century B.C., they had transformed Sparta into a military camp (see the box on p. 52). The lives of all Spartans were now rigidly organized. At birth, each child was examined by state officials who decided whether it was fit to live. Infants judged unfit were left to die. Boys were taken from their mothers at the age of seven and put under control of the state. They lived in military-style barracks, where they were subjected to harsh discipline to make them tough and given an education that stressed military training and obedience to authority. At twenty, Spartan males were enrolled in the army for regular military service. Although allowed to marry, they continued to live in the barracks and ate all their meals in public dining halls with their fellow soldiers. Meals were simple; the famous Spartan black broth consisted of a piece of pork boiled in blood, salt, and vinegar, causing a visitor who ate in a public mess to remark that he now understood why Spartans were not afraid to die. At thirty, Spartan males were allowed to vote in the assembly and live at home, but they stayed in the army until the age of sixty.


While their husbands remained in military barracks until age thirty, Spartan women lived at home. Because of this separation, Spartan women had greater freedom of movement and greater power in the household than was common for women elsewhere in Greece. They were encouraged to exercise and remain fit to bear and raise healthy children. Like the men, Spartan women engaged in athletic exercises in the nude. Many Spartan women upheld the strict Spartan values, expecting their husbands and sons to be brave in war. The story is told that as a Spartan mother was burying her son, an old woman came up to her and said, 'You poor woman, what a misfortune.' 'No,' replied the other, 'because I bore him so that he might die for Sparta and that is what has happened, as I wished.'7 Another Spartan woman, as she was handing her son his shield, told him to come back carrying his shield or being carried on it.


**** The Spartan State
The Spartan government was headed by two kings, who led the Spartan army on its campaigns. A group of five men, known as the ephors, were elected each year and were responsible for the education of youth and the conduct of all citizens. A council of elders, composed of the two kings and twenty-eight citizens over the age of sixty, decided on the issues that would be presented to an assembly. This assembly of all male citizens did not debate but only voted on the issues put before it by the council of elders.


To make their new military state secure, the Spartans deliberately turned their backs on the outside world. Foreigners, who might bring in new ideas, were discouraged from visiting Sparta. Nor were Spartans, except for military reasons, encouraged to travel abroad where they might pick up new ideas that might prove dangerous to the stability of the state. Likewise, Spartan citizens were discouraged from studying philosophy, literature, or the arts---subjects that might encourage new thoughts. The art of war and of ruling was the Spartan ideal; all other arts were frowned on.


In the sixth century, Sparta used its military might and the fear it inspired to gain greater control of the Peloponnesus by organizing an alliance of almost all the Peloponnesian states. Sparta’s strength enabled it to dominate this Peloponnesian League and determine its policies. By 500 B.C., the Spartans had organized a powerful military state that maintained order and stability in the Peloponnesus. Raised from early childhood to believe that total loyalty to the Spartan state was the basic reason for existence, the Spartans viewed their strength as justification for their militaristic ideals and regimented society.


*** Athens
By 700 B.C., Athens had established a unified polis on the peninsula of Attica. Although early Athens had been ruled by a monarchy, by the seventh century it had fallen under the control of its aristocrats. They possessed the best land and controlled political and religious life by means of a council of nobles, assisted by a board of nine archons. Although an assembly of full citizens did exist, it possessed few powers.


Near the end of the seventh century B.C., Athens faced political turmoil because of serious economic problems. Many Athenian farmers found themselves sold into slavery when they were unable to repay the loans they had borrowed from their aristocratic neighbors, pledging themselves as collateral. Over and over, cries arose to cancel the debts and give land to the poor. Athens seemed on the verge of civil war.


**** The Reforms of Solon
The ruling Athenian aristocrats responded to this crisis by choosing Solon, a reform-minded aristocrat, as sole archon in 594 B.C. and giving him full power to make changes. Solon canceled all current land debts, outlawed new loans based on humans as collateral, and freed people who had fallen into slavery for debts. He refused, however, to carry out the redistribution of the land and hence failed to deal with the basic cause of the economic crisis.


Like his economic reforms, Solon’s political measures were also a compromise. Though by no means eliminating the power of the aristocracy, they opened the door to the participation of new people, especially the nonaristocratic wealthy, in the government. But Solon’s reforms, though popular, did not solve Athens’ problems. Aristocratic factions continued to vie for power, and the poorer peasants resented Solon’s failure to institute land redistribution. Internal strife finally led to the very institution Solon had hoped to avoid---tyranny. Pisistratus, an aristocrat, seized power in 560 B.C. Pursuing a foreign policy that aided Athenian trade, Pisistratus remained popular with the merchants. But the Athenians rebelled against his son and ended the tyranny in 510 B.C. Although the aristocrats attempted to reestablish an oligarchy, Cleisthenes, another aristocratic reformer, opposed this plan and, with the backing of the Athenian people, gained the upper hand in 508 B.C. The reforms of Cleisthenes now established the basis for Athenian democracy.


**** The Reforms of Cleisthenes
A major aim of Cleisthenes’ reforms was to weaken the power of traditional localities and regions, which had provided the foundation for aristocratic strength. He made the demes, the villages and townships of Attica, the basic units of political life. Cleisthenes enrolled all the citizens of the demes in ten new tribes, each of which contained inhabitants located in the rural districts of Attica, the coastal areas, and Athens. The ten tribes thus contained a cross section of the population and reflected all of Attica, a move that gave local areas a basic role in the political structure. Each of the ten tribes chose fifty members by lot each year for a new Council of Five Hundred, which was responsible for the administration of both foreign and financial affairs and prepared the business that would be handled by the assembly. This assembly of all male citizens had final authority in the passing of laws after free and open debate; thus Cleisthenes’ reforms strengthened the central role of the assembly of citizens in the Athenian political
system.


The reforms of Cleisthenes laid the foundations for Athenian democracy. More changes would come in the fifth century B.C. when the Athenians themselves would begin to use the word democracy to describe their system (from the Greek words demos, 'people,' and kratia, 'power,' thus 'power to the people'). By 500 B.C., Athens was more united than it had ever been and was about to assume a more important role in Greek affairs.
