* L15 Good news
What was the good news?

The secretary told me that Mr. Harmsworth would see me. I felt
very nervous when I went into his office. He did not look up from
his desk when I entered. After I had sat down, he said that business
was very bad. He told me that the firm could not afford to pay such
large salaries. Twenty people had already left. I knew that my turn
had come.
    'Mr. Harmsworth,' I said in a weak voice.
    'Don't interrupt', he said.
    Then he smiled and told me I would receive an extra thousand pounds a year!

** words
secretary /ˈsekrət(ə)ri/ n. 秘书  
nervous /ˈnɜːvəs/ adj. 精神紧张的  
afford /əˈfɔːd/ v. 负担得起  
weak /wiːk/ adj. 虚弱的  
interrupt /ˌɪntəˈrʌpt/ v. 插话,打断  

todo 抄到expressions本里面
情态动词:  
能力
- can could
可能
- may might
- must had to
意愿
- shall/will should/would  

shall 和 should(shall的过去式)
shall:(应当): 都建议,都表将来,shall更强调看法,而should更强调义务 
should:(应该)

must 和 have to
must 更正规, have to 非正式

    
宾语从句  

** Pattern drill
1T: The doctor's busy.
S1: Why can't you see the doctor now?
S2: His secretary says he's busy.
The boss is away/at lunch.
    Why can't you see the boss now.
    His secretary says he's away.

The manager's on holiday/isn't in.
    Why can't you see the manager now?
    His secretary says he's on holiday.

The headmaster's ill/isn't free.
    Why can't you see the headmaster now?
    His secretary says he isn't free.

The dentist can't/won't see anyone.  
    Why can't you see the dentist now?
    His secretary says he can't see anyone.


2T: The doctor's busy.
S1: Didn't the doctor see you?
S2: No, his secretary said he was busy.
The bank manager's away/at a meeting.
    Didn't the bank manager see you?
    No, his secretary said he was away.

Mr. Smith has gone home/on holiday.
    Didn't Mr. Smith go home?
    No, his secretary said he had gone on holiday.

Mr. Jones will see/call me later.
    Didn't Mr. Jones see you?
    No, his secretary said he would see me later.

The minister can't/ won't see anyone.
    Didn't the minister see you?
    No, his secretary said he couldn't see anyone. 


3T: Who broke that plate?
S1: Mary says John broke it.
S2: But I think Mary broke it.  ???
paid the bill(支付账单)
    Who paid the bill?
    Mary says John paid it.
    But I think Mary paid it.

washed the car
    Who washed the car?
    Mary says John washed it.
    But I think Mary washed it.

burnt the shirt
    Who burnt the shirt?
    Mary says John burnt it.
    But I think Mary burnt it.  

stained the carpet(玷污毛毯)
    Who stained the carpet?
    Marys says John stained it.
    But I think Mary stained it.  


4T: There's been an accident.
S1: What did he say? I didn't hear.
S2: He said there'd been an accident.
a sale of old books
    There's been a sale of old books.
    What did he say? I didn't hear.
    He said that there had been a sale of old books.  

a fall in sales (大降价)
    What did he say? I didn't hear.
    He said that there had been a fall in sales.

a discussion on TV
    What did he say? I didn't hear.
    He said that there had been a discussion on TV.

a rise in wages(salary)
    What did he say? I didn't hear.
    He said that there had been a rise in wages.


