* Lesson 17 Always young

My aunt Jennifer is an actress. She must be at least thirty-five years
old. In spite of this, she often appears on the stage as a young girl.
Jennifer will have to take part in a new play soon. This time, she
will be a girl of seventeen. In the play, she must appear in a bright
red dress and long black stockings. Last year in another play, she
had to wear short socks and a bright, orange-coloured dress. If anyone
ever asks her how old she is, she always answers, 'Darling, it must
be terrible to be grown up!'

appear əˈpɪə(r) v. 登场,表演
stage steɪdʒ n. 舞台
bright braɪt adj.
stocking ˈstɒkɪŋ n.
sock sɒk n.

here 和 there的区别

## ask questions
1. My aunt Jennifer is an actress. (What)
   What job is your aunt Jennifer.

2. She's over thirty years old. (How old)
   Hos old is she?

3. She often appears on the stage as a young girl.(What...as) (Who)
   What does she offten appear on the stage as?
   Who often appears on the stage as a young girl?

4. She will have to take part in a new play soon.(When) (What)
   When will she have to take part in a new play soon?
   What will she have to take part in soon?

5. She will be a girl of seventeen. (Who)
   Who will she be?

6. She'll wear a bright red dress.(What)
   What will she wear?

7. She'll appear in long black stockings. (What)
   What will she appear in?

8. She was in another play last year. (When)
   When was she in another play.

9. She had to wear short socks. (What)
   What did she have to wear?

10. She had to wear a bright dress. (What else)
	What else did she have to wear?

11. It was orange. (What colour)
	What colour was it?

## Summary writing
	My aunt Jennifer is an actress.She is over thirty years old.In spite of this, she often
	appears on the stage as a young girl.Jennifer will act the part of a girl of seventeen in
	a new play soon.She never tells anyone how old she really is.

## Topics for discussion
1. Who is your favourite actor/actress? Why do you think he/she is good?
   LiuDehua. I think he is hardworking.He has got a doctorate recently.

2. Is it true that most women tell lies about their age? Why do they? What about men?
   Yes, it is.They think it makes they look more beautiful.But men rarely do it.

3. Do you think it's terrible to be grown-up? Why or why not?
   No, I don't.Because we must grow up.If we become a grown-up, we will protect ourself and
   protect our family better.
