* Lesson 18 He often does this!
After I had had lunch at a village pub, I looked for my bag. I had
left it on a chair beside the door and now it wasn't there! As I was
looking for it, the landlord came in.
'Did you have a good meal?' he asked.
'Yes, thank you,' I answered, 'but I can't pay the bill. I haven't
got my bag.'
The landlord smiled and immmediately went out. In a few minutes
he returned with my bag and gave it back to me.
'I'm very sorry,' he said. 'My dog had taken it into the garden.
He often does this!'

** topics for discussion
   1. Have you ever lost any money?If so, tell us what happened.
      Yes, I have.At the afternoon,I lost my money.I couldn't surf

      the Internet on internet bar.But my friend surfed all the noon.

   2. Describe the best meal you've ever had.

      I have had a great meal in Hangzhou. It's the best meal I've ever had.
      It's delicious.

   3. 'The Dog is a man's best friend.'Do you agree with this
      saying?Why/Why not?
      
      I don't.If the dogs is hungry at outdoor, they will bite children.
      

