* L23 A new house
  
** words
   complete [kəmˈpliːt] v. adj.
   modern [ˈmɒd(ə)n] adj.
   strange [streɪndʒ] adj.
   district [ˈdɪstrɪkt] n. 

** article
   I had a letter from my sister yesterday. She lives in Nigeria[naɪˈdʒɪəriə]. In her
   letter, she said that she would come to England next year. If she
   comes, she will get a surprise. We are now living in a beautiful
   new house in the country. Work on it had begun before my sister
   left. The house was completed five months ago. In my letter, I told
   her that she could stay with us. The house has many large rooms
   and there is a lovely garden. It is a very modern house, so it looks
   strange to some people. It must be the only modern house in the
   district.

   主语从句???
   针对每句话要说出其语法,以及对应的结构

** topics
   1. What do you do to welcome a visitor to your home?
      Clean my house.
      Prepare fruits and foods.
      Organize games.
      Share videos.
      
   2. Would you rather live in an old house or an modern house? Why?
      I would rather live in an modern house.
      An modern house is often in the country. An old house is often in the town.
      It's convenient to visit many places in the country.

   3. Imagine you are coming home after living abroad for some time. What would you want to do?
      Instead of eating a lot of local foods, I spend all time with my family and my friends.

