* L25 Do the English speak English?
** words
railway [ˈreɪlweɪ] n.
porter [ˈpɔːtə(r)] n.
several [ˈsevrəl] quantifier
foreigner [ˈfɒrənə(r)] n.
wonder [ˈwʌndə(r)] v. 

** article
I arrived in London at last. The railway station was big, black and
dark. I did not know the way to my hotel, so I asked a porter. I not
only spoke English very carefully, but very clearly as well. The
porter, however, could not understand me. I repeated my question
several times and at last he understood. He answered me, but he
spoke neither slowly nor [nɔː(r)] clearly. 'I am a foreigner,' I said. Then he
spoke slowly, but I could not understand him. My teacher never
spoke Enlish like that! The porter and I looked at each other and
smiled. Then he said somethings and I understood it. 'You'll soon learn English!' he said, I wonder. In England,
each person speaks a different language. The English understand each other, but I don't understand them! Do
they speak English?
** movies
You either die a hero or you live long enough to see yourself become the villain [ˈvɪlən].
** Grammar
1. 并列关系
   - and
   - both ... and ...(只有复数)
   - neither ... nor ...:(三单)就近原则
2. 转折关系
   - but
   - however
   - yet
   - still
   - while
3. 选择关系
   - or
   - either ... or ...:(三单)就近原则
   - whether ... or ...(不管是哪项)
4. 因为关系
   - for (因为) ask sb. for sth.
   - so (所以)
** wz
I arrived in London at last, the railway station was big, black and dark.
I did not know the way to my hotel, so I asked a porter.
I not only spoke English very carefully,but very clearly as well.
The porter, however, couldn't understand me.
I repeated my question several times and at last he understood.
He answered me, but he spoke neither slowly nor clearly.
'I'm a foreigner', I said.
The he spoke slowly, but I couldn't understand him.
My teacher never speak English like that.
Both I and he looked at each other and smiled.
The he said somethings and I understood it.
'You'll soon learn English', he said, I wonder.
In England, each person speaks a different language.
The English can understand each other, but I couldn't understand them.
Do they speak English?
** Topics
1. A foreigner asks you the way from the station to your school. Explain it to him.
2. Have you ever been abroad? Describe some of your difficulties.
   No, I haven't.
   I don't understand their native language.
   It must be difficult to do as the Romans do.
   If I go abroad, I will worry about the money and the safety.
   It's possible to losing my money in abroad. 
3. 'In England each man speaks a different language.' What does this mean? Talk abount
   the different 'languages' in your country.
   Scheme is a dialect of the lisp language.
   There are a great sum of languages.
   There are Beijing dialect, Nanchang dialect and so on in China.

