* L31 Success story
What was Frank's first job?

Yesterday afternoon Frank Hawkins was telling me about his experience as a young man.
Before he retired, Frank was the head of a very large business company,
  but as a boy he used to work in a small shop.
It was his job to repair bicycles and at that time he used to work fourteen hours a day.
He saved money for years and in 1958 he bought a small workshop of his own.
In his twenties Frank used to make spare parts for aeroplanes.
At that time he had two helpers.
In a few years the small workshop had become a large factory
  which employed seven hundred and twenty-eight people.
Frank smiled when he remembered his hard early years and the long road to success.
He was still smiling when the door opened and his wife came in.
She wanted him to repair their grandson's bicycle!

telling - experience - a young man
retired - large company - small shop
repair bicycle - fourteen hours a day
save money - bought workshop
twenties - spare parts - aeroplanes, two helpers
large factory - employ - 728
hard early years - long road to success
door opened - his wife came in
want - repair grandson's bicycle

* words
retire v.
company n.
bicycle n.
save v.
workshop n.
helper n.
employ v.
grandson n.
* Asking questions
1. I was with Frank Hawkins yesterday afternoon. (Who, When)
   Who was you with yesterday afternoon?
   When was you with Frank Hawkins yesterday afternoon?

2. He was describing his experiences as a young man. (What, When, Who)
   What was he describing?
   When was he describing his experiences?
   Who was describing his experiences as a young man?

3. He's now head of a business company. (What, Who)
   What is he now head of?
   Who's now head of a business company.

4. It's very large. (How big, What)
   How big is it?
   What is very large?
   
5. He used to work in a small shop as a boy.(Where, When, Who)
   Where did he use to work as a boy?
   When did he use to work in a small shop?
   Who used to work in a small shop as a boy?
   
6. He repaired bicycles. (What, Where)
   What did he repair?
   Where did he repair bicycles.
   
7. He used to work fourteen hours a day.(How many, Who)
   How many hours did he use to work a day?
   Who used to work fourteen hours a day.
   
8. He saved money for years. (How long)
   How long did he save money?
   
9. He bought a small workshop. (What)
   What did he buy?
* Summary writing
1. Frank Hawkins was telling the writer about his experiences as a young man.
2. Frank used to work in a small shop as a boy.
3. He used to repair bicycles there.
4. In 1958 he bought his own shop and in his twenties he made spare parts for aeroplanes.
5. He employed a lot of people in a few years.
6. His wife came into the room after a while.
7. She wanted him to repair their grandson's bicycle.
* Topics for discussions
1. Describe some of the things you used to do when you were young.
   I used to live in Beijing.
   I used to study fourteen hours a day.
   I used to work for a factory.
   I used to play games all night.
   I used to have a girl friend.
   
2. What qualities must a person have to build up a successful business?
   Unique value.
   Tenacity
   Customer-centric approach
   good marketing
   Strong vision
   passionate leaders
   
3. What kind of success would you like to have in life? Talk about it.
   support my father well
   protect wife all my life
   teach child well
  
