* L37 The Olympic Games

** articles
When was the last time this country hosted the Olympic Games?

The Olympic Games will be held in our country in four years' time.
As a great many people will be visiting the country, the government will be building new hotels,
an immense stadium, and a new Olympic-standard swimming pool.
They will also be building new roads and a special railway line.
The Games will be held just outside the captial and the whole area will be called 'Olympic City'.
Workers will have completed the new roads by the end of this year.
By the end of next year, they will have finished work on the new stadium.
The fantastic modern buildings have been designed by Kurt Gunter.
Everybody will be watching anxiously as the new buildings go on.
We are all very excited and are looking forward to the Olympic Games
because they have never held before in the country.

** words
Olympic adj.
hold v.
government n.
immense adj.
stadium n.
standard n.
captial n.
fantastic adj.
design v.

** Summary Writing
The Olympic Games will be held in our country in four years' time,
so the government will be putting up new buildings just outside the captial.
Kurt Gunter has designed the buildings
and workers will have completed the new stadium by the end of next year.
The Games will be held in this country for the first time
and we are looking forward to them.

** Topics for discussion
1. Talk about some of the outstanding athletic achievements of the last Olympic Games.
	 Eileen Gu wins a gold medal in the Winter Olympic games in 2022.
	 It's the first time to win a gold medal in Chinese players.

2. Which is your favourite sporting event in the Games? Why?
	 Ping-pong is my favourite sporting event in the Games.
	 As there are many Ping-pong champions in China, we are all very pround of them.

3. Where and why were the first Olympic Games held? Do the Games still have a useful purpose?
	 Why / Why not?
	 The first modern Olympics were held in Athens Greece in 1896.
	 They wish, hope and pray for peace in the world.
	 The Games don't have a useful purpose,
		because many country misleading their people by using them.
