* L40 Food and talk
Was Mrs. Rumbold a good companion at dinner?

Last week at a dinner party, the hostess asked me to sit next to Mrs. Rumbold.
Mrs. Rumbold was a large, unsmiling lady in a tight black dress.
She did not even look up when I took my seat beside her.
Her eyes were fixed on her plate and in a short time, she was busy eating.
I tried to make conversation.
'A new play is coming to "The Globe" soon,' I said. "Will you be seeing it?"
'No,' she answered.
'Will you be spending your holidays abroad this year?' I asked.
'No,' she answered.
'Will you be staying in England?' I asked.
'No,' she answered.
In despair, I asked her whether she was enjoying her dinner.
'Young man,' she answered, 'if you ate more and talked less, we would both enjoy our dinner!'
** Asking questions
1. I went to a dinner party last week. When Where Who
	 When did you go to a dinner party?
	 Where did you go to a dinner party last week?
	 Who went to a dinner party last week?

2. The hostess asked me to sit next to a large, unsmiling lady. Where
	 Where did the hostess ask you to sit?

3. Her name was Mrs. Rumbold. What
	 What was her name?

4. She was wearing a tight black dress. What kind of Who
	 What kind of dress was she wearing?
	 Who was wearing a tight black dress?

5. Her eyes were fixed on her plate. What
	 What were her eyes fixed on?

6. She was busy eating in a short time. How soon Who
	 How was she busy eating?
	 Who was busy eating in a short time?

7. I tried to make conversation. What
	 What did you try to do?

8. I told her about a new play. What
	 What did you tell her about?

9. It was coming to 'The Globe'. Where
	 Where was it coming to?

10. It would start soon. When
		When would it start?
		
** Summary writing
The writer sat next to Mrs. Rumbold at the dinner party.
He tried to make conversation but she was busy eating.
He talked about the new play at 'The Globe' and about the holidays.
She answered his questions briefly.
Then he asked if she was enjoying her dinner and she answered,
	'Young man, if you ate more and talked less, we would both enjoy our dinner'.

** Topics for discussion
1. What subjects do you like talking about? Why?
	I like talking abount program.
	It's exciting to finish a program.
	
2. If you are at a party, which do you think is more important, meeting and talking to people
		or foods? Why?
	 I think meeting and talking to people is more important.
	 I can eat foods in other places.

3. 'Listening is as much part of "good conversation" as talking. 'Do you agree? Why/Why not?
	 Yes, I do.
	 If you are talking, there must be another listening.


