* L42 Not very musical

What happened when the sanke charmer began to play jazz?

As we had had a long walk through one of the markets of Old Delhi,
	we stopped at a square to have a rest.
After a time, we noticed a snake charmer with two large baskets at the other side of the square,
	so we went to have a look at him.
As soon as he saw us, he picked up a long pipe which was covered with coins
	and opened one of the baskets.
When he began to play a tune, we had our first glimpse of the snake.
It rose out of the basket and began to follow the movements of the pipe.
We were very much surprised
	when the snake charmer suddenly began to play jazz and modern pop songs.
The snake, however, continued to 'dance' slowly.
It obviously could not tell the difference between Indian music and jazz!

** words
musical adj.
market n.
snake charmer n.
pipe n.
tune n.
glimpse n.
snake n.
movement n.
continue v.
dance v.
obviously adv.
difference n.
Indian adj.

** Asking questions
1. We were in one of the markets of Old Delhi. Where
	 Where were you?

2. We'd had a long walk. What
	 What had we had?

3. We stopped at a square. Where,Why
	 Where did you stop?
	 Why did you stop at a square?

4. We needed a rest. What Why
	 What did you need?
	 Why did you need a rest?

5. We noticed a snake charmer. What Where
	 What did you notice?
	 Where did you notice a snake charmer?

6. He had two large baskets. How many
	 How many large baskets did he have?

7. He was sitting at the other side of the square. Where Who
	 Where was he sitting?
	 Who was sitting at the other side of the square?

8. We went to have a look at him. What... do
	 What did you do?

9. He picked up a long pipe. What When
	 What did he pick up?
	 When did he pick up a long pipe?

10. It was covered with coins. What... with
		What was covered with coins?

11. He opened one of the baskets. What
		What did he open?

12. He began to play a tune. What
		What did he begin to do?

** Summary writing
We watched a snake charmer in a square in Old Delhi.
He had a long pipe and two large baskets.
He played a tune and the snake rose out of in one of the baskets.
Then the snake charmer played modern tuns but the snake continued to dance slowly.
It did not know the difference between Indian music and jazz.

** Topics of discussion
1. Many people are afraid of snakes. Why do you think this is so? What about you?
	 If you are bit by snakes, you will lose your life.
	 I'm afraid of snakes too.

2. Have you seen other kinds of animals 'performing'? Where? What did they do?
	 No, I haven't.

3. What kind of music do you like when you want to relax, when you are dancing, at a concert?
		Give reasons for your choice.
   I like classic music when I want to relax.
	 It's easy for me to sleep soundly when I listen to classic music.
	 I like jazz when I am dancing.
	 I find jazz exciting.
	 I like piano at a concert.
	 It's difficult to play piano.

