* L43 Over the South Pole
How was the plane able to clear the mountains?

In 1929, three years after his flight over the North Pole,
	the American explorer, R.E. Byrd, successfully flew over the South Pole for the first time.
Though, at first, Byrd and his men were able to take a great many photographs of
	the mountains that lay below, they soon ran into serious trouble.
At one point, it seemed certain that their plane would crash.
It could only get over the mountains if it rose to 10,000 feet.
Byrd at once ordered his men to throw out two heavy food sacks.
The plane was then able to rise and it cleared the mountains by 400 feet.
Byrd now knew that he would be able to reach the South Pole which was 300 miles away,
	for there were no more mountains in sight.
The aircraft was able to fly over the endless white plains without difficulty.

** words
pole n.
flight n.
explorer n.
lie lay lain v.
serious adj.
point n.
seem v. 似乎
crash v. 坠毁
sack n. 袋子
clear v. 越过
aircraft n. 飞机
endless adj. 无尽
plain n. 平原

** Pattern drill
1. see
   When can you see me?
   I can see you tomorrow if you like.
   come shopping with
   When can you come shopping with me?
   I can come shopping with tomorrow if you like.

   choose a car for
   When can you choose a car for me
   I can choose a car for you tomorrow if you like.

   have a walk with
   When can you have a walk with me?
   I can have a walk with you tomorrow if you like.

   go to the zoo with
   When can you go to the zoo with me?
   I can go to the zoo with you tomorrow if you like.

2. The baby-walk
   Can the baby walk yet?
   No, but he'll be able to walk in a few months' time.
   Jane--swim
   Can Jane swim yet?
   No, but he'll be able to swim in a few months' time.

   Jane-drive
   Can Jane drive yet?
   No, but he'll be able to drive in a few months' time.

   John-speak German
   Can John speak German?
   No, but he'll be able to speak German in a few months' time.

   John-read French
   Can John read French?
   No, but he'll be able to read French in a few months' time.

3. swim -3
   When did you learn to swim?
   I could swim when I was three.
   ride a bicycle -8
   When did you ride a bicycle?
   I could ride a bicycle when I was eight.

   use a keyboard -17
   When did you use a keyboard?
   I could use a keyboard when I was 17.

   speak English -15
   When did you speak English?
   I could speak English when I was 15.

   read -7
   When did you read?
   I could read when I was 7.

4. see the play
   It's a pity he couldn't see the play.
   Oh, didn't you know? He was able to see after all.
   visit Mary
   It's a pity he couldn't visit Mary.
   Oh, didn't you know? He was able to visit Mary after all.

   go to the party
   It's a pity he couldn't go to the party.
   Oh, didn't you know? He was able to go to the party after all. 

   take the exams
   It's a pity he couldn't take the exams.
   Oh, didn't you know? He was able to take the exams after all.

   take you out
   It's a pity he couldn't take you out.
   Oh, didn't you know? He was able to take you out after all.
   
** Asking questions
1. R.E. Byrd was an explorer. Who
	 Who was an explorer?

2. He came from America. Where Who
	 Where did he come from?
	 Who came from America?

3. He was the first man to fly over the South Pole. Who
	 Who was the first man to fly over the South Pole?

4. He flew over it in 1929. When Who
	 When did he fly over it in 1929?
	 Who flew over it in 1929?

5. He had flown over the North Pole three years earlier. When Who
	 When had he flown over the North Pole?
	 Who had flown over the North Pole?

6. They were able to take a great many photographs. How many
	 How many photographs were they able to take?

7. They took photographs of the mountains below. What... of
	 What did they take photographs of?

8. They soon ran into difficulties. When
	 When did they run into difficulties?

9. They thought that their plane would crash. What Why
	 What did they think?
	 Why did they think that their plane would crash?

** Summary writing
In 1929, the American explorer, R.E. Byrd became the first man to fly over the South Pole.
He took a lot of photographs during the flight, but then he ran into difficulties.
His plane could not get over the mountains,
	so he ordered his men to throw out two heavy food sacks.
The plane then flew over the mountains and it continued without further trouble.

** Topics for discussion
1. What other famous explorers do you know about? Tell us about one of them.
	 YangLiwei is the first chinese from the space to the earth.

2. When and why can aerial photographs be useful?
	 If you don't your way to somewhere, you can find out it by using aerial photographs.

3. What are the main differences between 'modern' expeditions and those of fifty years ago or more?
		Do you think explorers were braver then? Why/Why not?
	 I don't think.
	 The science and technology have developed for many years.
	 Instead of using old technology, the explorer use the new technology.
