* L46 Expensive and uncomfortable

What did the man in this story do?
The man hided in the box before the plane left London.

When a plane from London arrived at Sydney airport,
	workers began to unload a number of wooden boxes which contained clothing.
No one could account for the fact that one of the boxes was extremely heavy.
It suddenly occurred to one of the workers to open up the box.
He was astonished at what he found.
A man was lying in the box on top of a pile of woollen goods.
He was so surprised at being discovered that he did not even try to run away.
After he was arrested, the man admitted hiding in the box before the plane left London.
He had had a long and uncomfortable trip,
	for he had been confined to the wooden box for over eighteen hours.
The man was ordered to pay $3500 for the cost of the trip.
The normal price of a ticket is $2000!

** words
unload v. 卸(货)
wooden adj.
extremely adv.
occur v.
astonish v.
pile n.
woollen n.
goods n.
discover v.
admit v.
confine v.
normal adj.

** Asking questions
1. The plane arrived at Sydney airport. Which airport/ What
	 Which airport did the plane arrive at?
	 What did arrive at Sydney airport?

2. It had come from London. Where
	 Where had it come from?

3. Workers began to unload some wooden boxes. What/When/Who
	 What did workers begin to unload?
	 When did workers begin to unload some wooden boxes?
	 Who began to unload some wooden boxes?

4. They contained clothing. What
	 What did they contain?

5. One box was extremely heavy. How heavy
	 How heavy was one box?

6. One of the workers had an idea. Who
	 Who had an idea?

7. The worker opened the box. What/Why
	 What did the worker open?
	 Why did the worker open the box?

8. He was astonished at what he found. Why
	 Why was he astonished at what he found?

9. A man was lying in the box. Who
	 Who was lying in the box?

10. He was on top of a pile of woollen goods. Where
		Where was he?

11. He stayed there. What... do
		What did he do?

** Summary writing
The plane from London arrived at Sydney airport and workers unload some wooden boxes from it.
They contained clothing.
One of the boxes was extremely heavy so a worker opened up it.
He found that a man was lying in the box on top of a pile of woollen goods.
The man was arrested.
He had travelled in the box from London.
He had to pay $3500.
An ordinary ticket costs $2000.

** Topics for discussion
1. If you found a stranger hiding somewhere in your house, what would you do?
	 If you find a stranger hiding somewhere in my house,
			I will leave it immediately and call the police.

2. If you wanted a free trip on a plane or a boat, how would you try to get one?
	 I would ask my friend for a free ticket.

3. Employees of many air and rail companies get free or reduced fares for themselves
	 and their families. Is this a good thing? Why/ Why not?
	 This is a normal thing.
	 If employees get free or reduced fares, they may work harder.
