* L47 A thirsty ghost
What evidence is there of a ghost?

A public house which was recently bought by Mr. Ian Thompson is up for sale.
Mr. Thompson is going to sell it because it is haunted.
He told me that he could not go to sleep one night
	because he heard a strange noise coming from the bar.
The next morning, he found that
	the doors had been blocked by chairs and the furniture had been moved.
Though Mr. Thompson had turned the lights off before he went to bed,
	they were on in the morning.
He also said that he had found five empty whisky bottles
	which the ghost must have drunk the night before.
When I suggested that some villagers must have come in for a free drink,
	Mr. Thompson shook his head.
The villagers have told him that they will not accept the pub even if he gives it away.

** words
thirsty adj. 贪杯的
ghost n.
haunt v.
block v.
furniture n.
whisky n.
suggest v.
shake v.
accept v.

** Asking questions
1. A public house is up for sale. What
	 What is up for sale?

2. It was recently bought by Mr. Ian Thompson. How long ago/Who... by
	 How long ago was it bought by Mr. Ian Thompson?
	 Who was it recently bought by?

3. He's going to sell it because it's haunted. Why
	 Why is he going to sell it because it's haunted?

4. He heard a strange noise one night. What
	 What did he hear one night?

5. It was coming from the bar. Where
	 Where was it coming from?

6. He stayed awake all night. How long
	 How long did he stay awake?

7. He went to the bar the next morning. When/Where
	 When did he go to the bar?
	 Where did he go the next morning?

8. The doors had been blocked by chairs. What/ What... by
	 What had been blocked by chairs?
	 What had the doors been blocked by?

9. The furniture had been moved. What
	 What had been moved?

10. The lights were on. What
		What were on?

** Summary writing
Mr. Ian Thompson recently bought a public house but it's haunted so he's going to sell it.
There was a strange noise in the bar one night and the room was in disorder next morning.
Mr. Thompson also found five empty whisky bottles.
He doesn't believe that any villagers broke into the bar and had a drink.
Nobody in the village wants to buy the pub.

** Topics for discussion
1. If you wanted to buy a house, what kinds of things would persude you to buy it and make you
	 decide not to buy it?
	 Cheap price and convenient transport.
	 It's haunted.
	 
2. Do you believe in ghosts? Why/Why not?
	 I don't believe in ghosts because I haven't seen it since I was born.

3. Have you ever had a strange experience you could not explain? Tell us about it.
	 I thought that I would success in passing exam, and then I did.

