#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-10-03 Why extremophiles bode well for life beyond Earth
#+begin_verse
Louisa Preston
1
We've all seen movies about terrible insects
		from outer space or stories of abduction by little green men,
	but the study of life in the universe, including the possibility of extraterrestrial life,
		is also a serious, scientific pursuit.
Astrobiology draws on diverse fields, such as physics, biology, astronomy, and geology,
		to study how life was formed on Earth,
	how it could form elsewhere, and how we might detect it.
Many ancient religions described other worlds inhabited by known human beings,
	but these are more like mythical realms or parallel universes
		than other planets existing in the same physical world.
It is only within the last century
	that scientists have been able to seriously undertake the search for extraterrestrial life.
2	
We know that at the most basic level organisms on Earth need three things:
	liquid water, a source of energy, and organic, carbon-based material.
We also know that the Earth is just the right distance from the Sun,
	so as not to be either frozen or molten.
So, planets within such a habitable range from their own stars may be able to support life.
But while we used to think that life could only exist in such Earth-like environments,
	one of the most amazing discoveries of astrobiology has been just how versatile life is.
We now know that life can thrive in some of the most extreme environments
	that'd be fatal for most known organisms.
Life is found everywhere,
	from black smoke of hydrothermal vents in the dark depths of Earth's oceans,
	to bubbling, hot, acidic springs on the flanks of volcanoes,
	to high-up in the atmosphere.
Organisms that live in these challenging environments are called extremophiles,
	and they can survive at extremes of temperature, pressure, and radiation,
			as well as salinity, acidity,
		and limited availability of sunlight, water, or oxygen.
What is most remarkable about these extremophiles is
	that they are found thriving in environments that mimic those on alien worlds.
3	
One of the most important of these worlds is our red and dusty neighbor, Mars.
Today, astrobiologists are exploring places
	where life might once have existed on Mars using NASA's Curiosity rover.
One of these is Gale Crater,
	an impact crater created
		when a meteor hit the surface of Mars nearly 3.8 billions years ago.
Evidence from orbit suggest past traces of water,
	which means the crater might once have supported life.
Planets are not the only places astrobiologists are looking at.
For example, Europa, one of the moons of Jupiter, and Enceladus and Titan, two of Saturn's moons,
	are all exciting possibilities.
Although these moons are extremely cold and two are covered in thick ice,
	there is evidence of liquid oceans beneath the shell.
4	
Could life be floating around in these oceans,
	or could it be living around black smoker vents at the bottom?
Titan is particularly promising
	as it has an atmosphere and Earth-like lakes, seas, and rivers flowing across the surface.
It is very cold, however, too cold for liquid water,
	so these rivers may instead be flowing with liquid hydrocarbons such as methane and ethane.
These are composed of hydrogen, and, more importantly, carbon,
	which is the basic building block of all life as we know it.
So, could life be found in these lakes?
Although instruments are being designed to study these distant worlds,
	it takes many years to build them and even longer to get them where they need to be.
In the meantime, astrobiologists work in our own natural laboratory, the Earth,
	to learn about all the weird and wonderful forms of life that can exist
	and to help us one day answer one of humanity's oldest questions: Are we alone?
#+end_verse
** expression
1
insect: a small creature such as a fly or ↑ant, that has six legs, and sometimes wings
outer space: 
abduction by sb.: 
in the universe: 
extraterrestrial: a creature that people think may exist on another planet
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose: 
diverse: 
forme life: 
ancient religions: 
be inhabited by sb.: 
sth. be more like A. than B.: 
mythical realms: 
parallel universes: 
in the same physical world: 
It is only within the last century that + ...: 
undertake sth.: 
2
organism: 
carbon-based: 
A. is just the right distance from B.: 
molten: 
habitable: 
support life: 
versatile: someone who is versatile has many different skills: 
thrive: to become very successful or very strong and healthy: 
sth. is fatal for sb.: resulting in someone’s death: 
in the dark depths of oceans/lakes/rivers: 
bubble: a ball of air or gas in liquid: 
acidic: very sour: 
on the flanks of volcanoes: the side of a hill, mountain, or very large building
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things: 
oxygen /ˈɒksɪdʒən $ ˈɑːk-/:
What is most remarkable about sth. is that + ...: 
mimic: to copy the way someone speaks or behaves, especially in order to make people laugh SYN imitate, take off: 
3
crater: a round hole in the ground made by something that has fallen on it or by an explosion: 
meteor: 
hit the surface of sth.: 
4
be flowing with: to have some liquid coursing on the surface or within someone or something
be composed of sth.: 
the basic building block of sth.: 
