#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-10-08 The operating system of life
George Zaidan and Charles Morton

#+begin_verse
1
Every chicken was once an egg, every oak tree an acorn, every frog a tadpole.
The patch of mold on that old piece of bread in the back of your fridge,
	not so long ago that was one, solitary cell.
Even you were once but a gleam in your parents' eyes.
All these organisms share the same basic goal: to perpetuate their own existence.
2
All lifeforms that we've discovered so far stay alive
	by using basically the same rules, materials, and machinery.
Imagine a factory full of robots.
These robots have two missions:
	one, keep the factory running, and two, when the time is right, set up an entirely new factory.
To do those things, they need assembly instructions, raw materials, plenty of energy,
	a few rules about when to work normally, when to work quickly, or when to stop,
	and some exchange currencies because even robots need to get paid.
Each factory has a high security office with blueprints
	for all the possible factory configurations and complete sets of instructions
		to make all the different types of robots a factory could ever need.
Special robots photocopy these instructions
	and send them off to help make the building blocks of more robots.
Their colleagues assemble those parts into still more robots,
	which are transported to the right location in the factory
		and given the tools they need to start working.
Every robot draws energy from the central power plant,
	a giant furnace that can burn regular fuel
		but also scrap materials if not enough regular fuel is available.
Certain zones in the factory have harsher working conditions,
	so these areas are walled off.
But the robots inside can at least communicate with the rest of the factory
	through specialized portals embedded directly into the walls.
3	
And as you've probably figured out,	what we're describing here is a cell.
The high security office is the nucleus.
It stores the blueprints and instructions as deoxyribonucleic acid, or DNA.
The photocopied instructions are RNA.
The robots themselves are mostly proteins built from amino acids,
	but they'll often use special tools that are, or are derived from, vitamins and minerals.
The walls between factory zones
	and around the factory itself are mostly made up of lipids, a.k.a. fats.
In most organisms, the primary fuel source are sugars,
	but in a pinch, fats and proteins can be broken down and burned in the furnace as well.
The portals are membrane proteins
	which allow very specific materials and information to pass through the walls at the right times.
Many interactions between robot proteins require some kind of push, think robot minimum wage.
A few small but crucial forms of money are transferred between proteins to provide this push.
Electrons, protons, oxygen, and phosphate groups are the main chemical currencies,
	and they're kept in small molecular wallets or larger tote bags to keep them safe.
This is biochemistry,
	the study of how every part of the factory interacts
		to keep your life running smoothly in the face of extreme challenges.
4		
Maybe there's too much fuel; your body will store the excess as glycogen or fat.
Maybe there's not enough; your body will use up those energy reserves.
Maybe a virus or bacteria tries to invade; your body will mobilize the immune system.
Maybe you touched something hot or sharp; your nerves will let you know so you can stop.
Maybe it's time to create a new cell or a new person.
Amazingly, oak trees, chickens, frogs,
	and, yes, even you share so many of the same basic robot and factory designs
		that biochemists can learn a lot about all of them all at the same time. 
#+end_verse
** expression
1
in the back of your fridge: 
solitary: 
sb. is a gleam in sb's eyes: 
share the same basic goal: 
perpetuate sb's own existence: 
2
stay alive: 
set up sth.: 
keep sb. doing sth.: 
assembly instructions: 
raw materials: 
get paid: 
send sth. off: 
assemble A. into B.: 
be transported to sp.: 
draw energy from sth.: 
harsher working conditions: 
be walled off: 
the rest of sth.: 
be embedded into sth.: 
3
be built from sth.: 
are derived from: 
in a pinch: in an emergency
minimum wage: 
are transferred between: 
in the face of sth.:
extreme challenges:
4	
mobilize the immune system: 
** expression
in the back of your fridge: 
- My wife complained that a patch of mold began to appear in the back of our fridge.
- His aim is to molten the big piece of ice in the back of his fridge.
- My mom left a bread in the back of my fridge in recognition of me.
sb. is a gleam in sb's eyes: 
- Our baby is still being a gleam in our eyes.
- The probability of lives in outer space is a gleam in our eyes.
- You used to be a gleam in your parents' eyes.
share the same basic goal: 
- The group of pop singer share the same basic goal: to make enough money to travel all over the world.
- It's hard for me to share my house with a girl who doesn't share the same basic goal.
- Sharing the same basic goal may be the basic building block of a marriage.
perpetuate sb's own existence: 
- Although he quaked in every limb and in his soul, he succeeded in perpetuating his own existence during the war.
- The first aim of every life is to perpetuate his own life.
- It reminds me of an ant
		which was trying to perpetuate its own existence while I played joken on it.
stay alive: 
- To stay his company alive, he fired hundreds of workers.
- It's a pity that he wasn't able to stay alive in the flood.
- It's incredible how he stayed alive when the volcanoes were erupting.
set up a factory: 
- In the end, he managed to set up a factory which launches telescope into space.
- He set up a factory which names after his daughter.
- It was wondering whether she succeed in setting up a robot factory. 
keep sb. doing sth.: 
- She has kept her son who deserted in the war hiding for over ten years. 
- He kept his daughter laughing at the reception.
- I admired him for keeping everyone around him staying positive.
assembly instructions: 
- When the police arrived on the scene, they found the assembly instructions.
- It was not long before that we received the assembly instructions.
- Following assembly instructions, he managed to piece those together.
raw materials: 
- The pretty girl invited me to collect raw materials.
- As raw materials began to accumulate, the warehouse soon became crowded.
- A cargo of raw materials will sail from Beijing to London.
get paid: 
- As soon as agreement is reached about the salary, you will get paid.
- I was relieved to hear that my wife got paid.
- I didn't get paid on time and I was under a lot of pressure.
send sth. off: 
- This advertisement was sent off to protect baby elephants.
- The manager sent assembly instructions off to help his staff work better.
- These pigeons are going to send these letters off.
assemble A. into B.: 
- He assembled these wood into a car under a lot of pressure.
- He volunteer to assemble these materials into a toy.
- He managed to assemble these parts into a model in time to pass the test.
be transported to sp.: 
- A cargo of raw materials has been transported to Space X.
- For your safety, your companion was transported to the hospital.
- I noticed with dismay that the golden watches hadn't been transported to abroad.
draw energy from sth.: 
- Your phone draws energy from battery inside. 
- All lives on the earth draws energy from the sun more or less. 
- While swimming across the Channel, she must draw energy from liquid foods.
harsher working conditions: 
- Workers can't stay alive in the harsher working conditions. 
- I might lose my life in the harsher working conditions.
- He often volunteer to repair bicycles in memory of his early harsher working conditions.
be walled off: 
- These rooms must have been walled off.
- The north area of London and the south area used to be walled off.
- She stated that the enclosure of these dog should have been walled off. 
the rest of sth.: 
- I will love you for the rest of my life.
- She tends to communicate with the rest of her classmates.
- I have eatten the rest of these meals.
be embedded into sth.: 
- The light is embedded into the ceiling.
- The battery is designed to be embedded into the phone.
- The bath was able to be embedded into your bathroom.
be built from sth.: 
- Proteins prove to be built from amino acids.
- The diamonds are built from stones and sands.
- The house is specially built from iron and glasses.
are derived from: to come or develop from something 来源于
- The assembly instructions are derived from the construction of the toy.
- The fats are derived from a special type of pigs.
- My pocket money is usually derived from my aunts.
in a pinch: in an emergency
- 
- 
- 
minimum wage: 
- 
- 
- 
are transferred between: 
- 
- 
- 
in the face of sth.:
- 
- 
- 
extreme challenges:
- 
- 
- 
mobilize the immune system: 
- 
- 
- 
