#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2013-10-29 Vampires - Folklore, fantasy and fact
#+begin_verse
Good evening! What's the matter?
Are you afraid of vampires?
He he, no need to worry, I'm not staying for dinner.
I'm here to guide you through a brief history of vampires,
	illustrating how our image has changed
		from a shambling corpse to the dapper gentleman you see before you.
Vampires are nearly as old as you humans.
Stories about us, revenants, appear in cultures extending as far back as prehistoric times.
But we weren't called vampires back then
	and most of us did not look the way we imagine vampires today.
	
Ha, far from it!
For example, the Mesopotamian Lamashtu was a creature with the head of a lion
		and the body of the donkey,
	and the ancient Greek Striges were simply described as bloodthirsty birds.
Others were even stranger.
The Philippine Manananggal would sever her upper torso and sprout huge, bat-like wings to fly.
The Malaysian Penanggalan was a flying female head with dangling entrails.
And the Australian Yara-ma-yha-who was a little red guy
	with a big head, a large mouth, and bloodsuckers on his hands and feet.
Oh, and let's not forget the Caribbean's Soucouyant,
	the West African obayifo, and the Mexican Tlahuelpuchi.
Charming, aren't they?
Though they may look vastly different, all of these beings have one common characteristic:
	They sustain themselves by consuming the life force of a living creature.
This shared trait is what defines a vampire -- all the other attributes change with the times.
So, how do we arrive at the reanimated fellow you see before you?

Our modern ideal emerges in 18th-century Eastern Europe.
With the dramatic increase of vampire superstitions, stories of bloodsucking,
	shadowy creatures become nightly bedside terrors.
And popular folklore,
		like the Moroi among the Romani people and the Lugat in Albania,
	provide the most common vampire traits known today,
		such as vampires being undead and nocturnal and shape-shifting.
You see, Eastern Europe in the 18th century was a pretty grim place
	with many deaths occurring from unknown diseases and plagues.
Without medical explanations,
	people searched for supernatural causes
		and found what looked like evidence in the corpses of the victims.
When villagers dug up bodies to discern the cause of the mysterious deaths,
	they would often find the cadavers looking very much alive
		-- longer hair and fingernails, bloated bellies, and blood at the corners of mouths.
Clearly, these people were not really dead.
Heh, they were vampires!
And they had been leaving their graves to feast on the living.
The terrified villagers would quickly enact a ritual to kill the undead.
The practices varied across the region,
	but usually included beheadings, burnings,
		and staking the body to the coffin to prevent it from getting up.
Grizzly stuff!
But what the villagers interpreted as unholy reanimation were actually normal symptoms of death.
When a body decomposes, the skin dehydrates, causing the hair and fingernails to extend.
Bacteria in the stomach creates gases that fill the belly,
	which force out blood and matter through the mouth.
Unfortunately, this science was not yet known, so the villagers kept digging.
In fact, so many bodies were dug up
	that the Empress of Austria sent her physician around to disprove the vampire stories,
		and she even established a law prohibiting grave tampering.
		
Still, even after the vampire hunts had died down,
	the stories of legends survived in local superstition.
This led to works of literature,
	such as Polidori's 'The Vampyre,' the Gothic novel 'Carmilla,'
		and, most famously, Bram Stoker's 'Dracula.'
Although Stoker incorporated historical material,
		like Elizabeth Báthory's virgin blood baths and the brutal executions of Vlad Dracul,
	it was these local myths that inspired the main elements of his story:
		the Transylvanian setting, using garlic to defend oneself, and the staking of the heart.
While these attributes are certainly familiar to us,
	elements he invented himself have also lasted over the years:
		fear of crucifixes, weakness in sunlight, and the vampire's inability to see their reflection.
By inventing new traits, Stoker perfectly enacted the age-old tradition of
	elaborating upon and expanding the myth of vampires.
As we saw, maybe you met my relatives,
	a huge of variety of creatures stalked the night before Dracula,
	and many more will continue to creep through our nightmares.
Yet, so long as they subsist off a living being's life force, they are part of my tribe.
Even sparkling vampires can be included.
After all, it's the continued storytelling and reimagining of the vampire legend
	that allows us to truly live forever.
#+end_verse
** expression
#+begin_verse
vampire: 
shambling: to walk slowly and awkwardly, not lifting your feet much, for example because you are tired, weak, or lazy
corpse: the dead body of a person
dapper: used to show that you are talking about someone or something that has not been mentioned before, or that your listener does not know about 
revenant: 幽灵, 亡魂
donkey: a grey or brown animal like a horse, but smaller and with long ears
bloodthirsty: eager to kill and wound, or enjoying killing and violence
sever: to cut through something completely, separating it into two parts, or to become cut in this way
upper:in a higher position than something else
torso: your body, not including your head, arms, or legs 
sprout: if vegetables, seeds, or plants sprout, they start to grow, producing shoots, buds, or leaves
wing: one of the parts of a bird’s or insect’s body that it uses for flying
entrail: the inside parts of an animal’s or person’s body, especially their intestines
bloodsucker / bloodsucking: a creature that sucks blood from the bodies of other animals
trait: formal a particular quality in someone’s character
reanimated/reanimation: formal to give new strength to someone or something or the energy to start again 复活
folklore: the traditional stories, customs etc of a particular area or country
nocturnal: an animal that is nocturnal is active at night
grim: making you feel worried or unhappy 严酷的
plague: a disease that causes death and spreads quickly to a large number of people
supernatural: impossible to explain by natural causes, and therefore seeming to involve the powers of gods or magic
cadaver: technical a dead human body, especially one used for study SYN corpse
bloated: if you describe an organization as bloated, you mean that it is too big and does not work effectively
beheading: 斩首
decompose: to decay or make something decay
dehydrate: to remove the liquid from a substance such as food or a chemical
incorporate: to include something as part of a group, system, plan etc
garlic: a plant like a small onion, used in cooking to give a strong taste
stake: 树桩
attribute: 属性
crucifixes: a cross with a figure of Christ on it
reflection: an image that you can see in a mirror, glass, or water
stalk: 潜伏
subsist: to stay alive when you only have small amounts of food or money SYN survive
sparkling: shining brightly with points of flashing light
--------------------
What's the matter: 怎么了
extend as far back as prehistoric times: date back to
back then: at a particular time in the past that you are talking about
be simply described as sth.: 
have one common characteristic: 有个共同特性
sustain oneself by doing sth.: 通过做某事来维持生计
the life force of sth.: 某物的生命力
change with the times: 随时间而改变
With the dramatic increase of sth.: 随着某物的戏剧性增多
dig up <-> sth.: 
discern the cause of sth.: 查明某物的原因
at the corners of mouths: 在嘴角
feast on sth.: 享用某物
enact a ritual to do sth.: 制定仪式去做某事
stake the body to the coffin: 把尸体钉在棺材里
normal symptoms of sth.: 某事的正常现象
cause sb./sth. to do sth.: 
force out sth. through sth.: 通过某处挤出某物
establish a law prohibiting sth./doing sth.: 制定法律禁止某事
die down: 消亡
brutal executions: 残酷的死刑
inspire the main elements of sth.: 激发某事的主要元素
enact the age-old tradition of doing sth.: 延续做某事的古老传统
elaborate upon: 详细碳素
#+end_verse
** sentences
What's the matter: 怎么了
- Everything in the kitchen was smashed into pieces. What's the matter?
- The car has broken down, what's the matter? 
- I find you very upset, what's the matter?
extend as far back as prehistoric times: date back to
- The invention of these tools could extend as far back as prehistoric times.
- The invention of these tools must extend as far back as prehistoric times.
- The practices became popular in cultures extending as far back as prehistoric times.
back then: at a particular time in the past that you are talking about
- It was all too easy to raise money back then. 
- Back then, I got enough money to travel all over the world.
- Back then, I woke up with a start.
be simply described as sth.: 
- The animal at large was simply described as cat-like.
- The colossal ship used to be simply described as unsinkable until his first voyage.
- These infected people shouldn't have been simply described as a number.
have one common characteristic: 有个共同特性
- We have one common characteristic: We are both fanatical about playing video games.
- We have one common characteristic: We love to go on a journey.
- We have one common characteristic: The noise from the airport drives us mad.
sustain oneself by doing sth.: 通过做某事来维持生计
- It is said that the obscure maidservant sustains herself by the life force of the living.
- He is said to sustain himself by running furniture business.
- There are rare instances when a creature sustains itself by bloodsucking.
the life force of sth.: 某物的生命力
- The cheap labor force is the life force of some developing countries.
- Loyalty is the life force of the regiment of soliders.
- Positive energy is the life force of the disabled girl.
change with the times: 随时间而改变
- It's not support to change with the times.
- Though I had a flat representation of the cave, it has changed with the times.
- I had a idea that I want to get him far away from my daughter,
		however, it has changed with the times.
With the dramatic increase of sth.: 随着某物的戏剧性增多
- With the increase of expenditure of households, he began to suspect his wife's behaviors.
- With the increase of income, he managed to move to London.
- With the increase of income, this company made a complete recovery.
dig up <-> sth.: 
- I dreaded digging up the body in the coffin.
- I dreaded my company digging up the corpse at midnight.
- My company pestered me to dig up the corpse in the cave.
discern the cause of sth.: 查明某物的原因
- In the end, she discerned the cause of the noises from the kicthen at midnight.
- He discerned the cause of soldiers' deserting.
- He discerned the cause of the loss of the Titanic.
at the corners of the mouth: 在嘴角
- There is a drop of blood at the corner of his mouth.
- I saw a drop of blood at the corner of his mouth.
- There're alway smiles at the corners of his mouth whenever you meet him.
feast on sth.: 享用某物
- The beggar was eager to feast on the foods in front of the coffin.
- The maidservant pretened that she hadn't feasted on those wine in the garage.
- I made my way back home to feast on my steak with my wife.
enact a ritual to do sth.: 制定仪式去做某事
- What we need to do is to enacta ritual to raise money.
- The writer enacted a ritual to bring his story to a conclusion.
- We have to enact a ritual to certify smallpox eradication.
stake the body to the coffin: 把尸体钉在棺材里
- The body must have been staked to the coffin.
- The vicars managed to stake the body to the coffin.
- The body was not allowed to be staked to the coffin.
normal symptoms of sth.: 某事的正常现象
- Not need to worry! These are the normal symptoms of having a cold.
- His behaviors are normal symptoms of passing test.
- Being nervous is a normal symptom of giving a speech in public.
cause sb./sth. to do sth.: 
- You caused these refugee to build up in the capital.
- You have caused your son to take an exit from the laboratory.
- You caused the ambassador to bring the gunpowder back to Europe.
force out sth. through sth.: 通过某处挤出某物
- I prevented my wife from forcing out my pimple.
- The little cat forced out wather through the pipe.
- It seems reasonable to assume that the water is forced out through the pipe.
establish a law prohibiting sth./doing sth.: 制定法律禁止某事
- The authorities established a law prohibiting variolation.
- The authorities established a law prohibiting bride price.
- The authorities established a law prohibiting smoking in public.
die down: 消亡
- The smallpox has died down before modern medicine.
- I'm sure that the smallpox has died before modern medicine.
- Staking the body to the coffin died down in modern times.
brutal executions: 残酷的死刑
- The two men who killed five innocent children must face brutal executions.
- I must prevent you from doing that, you'll face brutal executions. 
- The chemists who were seeking a potion for immortality would face brutal executions.
inspire the main elements of sth.: 激发某事的主要元素
- This inspires the main elements of the way to innoculate people.
- I was reminiscing about my father back then, which inspires the main elements of my story.
- The fireworks display inspires the main elements of his story.
enact the age-old tradition of doing sth.: 延续做某事的古老传统
- This village enacted the age-old tradition of asking for bride price.
- He enacted the age-old tradition of giving the eulogy at the funeral.
- She enacted the age-old tradition of raising money to have the clock repaired.
elaborate upon: 详细碳素
- She is one of those people who like to elaborate upon the myth of vampires.
- She felt obliged to elaborate upon the history of the civilization.
- My teacher elaborated upon the model of an atome in the process.
