#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-10-03 Why extremophiles bode well for life beyond Earth
#+begin_verse

We've all seen movies about terrible insects
		from outer space or stories of abduction by little green men,
	but the study of life in the universe, including the possibility of extraterrestrial life,
		is also a serious, scientific pursuit.
Astrobiology draws on diverse fields, such as physics, biology, astronomy, and geology,
		to study how life was formed on Earth,
	how it could form elsewhere, and how we might detect it.
Many ancient religions described other worlds inhabited by known human beings,
	but these are more like mythical realms or parallel universes
		than other planets existing in the same physical world.
It is only within the last century
	that scientists have been able to seriously undertake the search for extraterrestrial life.
	
We know that at the most basic level organisms on Earth need three things:
	liquid water, a source of energy, and organic, carbon-based material.
We also know that the Earth is just the right distance from the Sun,
	so as not to be either frozen or molten.
So, planets within such a habitable range from their own stars may be able to support life.
But while we used to think that life could only exist in such Earth-like environments,
	one of the most amazing discoveries of astrobiology has been just how versatile life is.
We now know that life can thrive in some of the most extreme environments
	that'd be fatal for most known organisms.
Life is found everywhere,
	from black smoke of hydrothermal vents in the dark depths of Earth's oceans,
	to bubbling, hot, acidic springs on the flanks of volcanoes,
	to high-up in the atmosphere.
Organisms that live in these challenging environments are called extremophiles,
	and they can survive at extremes of temperature, pressure, and radiation,
			as well as salinity, acidity,
		and limited availability of sunlight, water, or oxygen.
What is most remarkable about these extremophiles is
	that they are found thriving in environments that mimic those on alien worlds.
	
One of the most important of these worlds is our red and dusty neighbor, Mars.
Today, astrobiologists are exploring places
	where life might once have existed on Mars using NASA's Curiosity rover.
One of these is Gale Crater,
	an impact crater created
		when a meteor hit the surface of Mars nearly 3.8 billions years ago.
Evidence from orbit suggest past traces of water,
	which means the crater might once have supported life.
Planets are not the only places astrobiologists are looking at.
For example, Europa, one of the moons of Jupiter, and Enceladus and Titan, two of Saturn's moons,
	are all exciting possibilities.
Although these moons are extremely cold and two are covered in thick ice,
	there is evidence of liquid oceans beneath the shell.
Could life be floating around in these oceans,
	or could it be living around black smoker vents at the bottom?
Titan is particularly promising
	as it has an atmosphere and Earth-like lakes, seas, and rivers flowing across the surface.
It is very cold, however, too cold for liquid water,
	so these rivers may instead be flowing with liquid hydrocarbons such as methane and ethane.
These are composed of hydrogen, and, more importantly, carbon,
	which is the basic building block of all life as we know it.
So, could life be found in these lakes?
	
Although instruments are being designed to study these distant worlds,
	it takes many years to build them and even longer to get them where they need to be.
In the meantime, astrobiologists work in our own natural laboratory, the Earth,
	to learn about all the weird and wonderful forms of life that can exist
	and to help us one day answer one of humanity's oldest questions: Are we alone?
#+end_verse
** expression
insect: a small creature such as a fly or ↑ant, that has six legs, and sometimes wings
extraterrestrial: a creature that people think may exist on another planet
pursuit: when someone tries to get, achieve, or find something in a determined way ⇨ pursue追求
astrobiology: 太空生物学
diverse: very different from each other不同的, 变化多的
astronomy: the scientific study of the stars and ↑planets ⇨ astrology天文学
planet: a very large round object in space that moves around the Sun or another star行星 
organic: 有机的
organism: an animal, plant, human, or any other living thing有机体
carbon-based: 碳基
molten: molten metal or rock has been made into a liquid by being heated to a very high temperature熔化
habitable: good enough for people to live in
versatile: someone who is versatile has many different skills多才多艺的
thrive: to become very successful or very strong and healthy兴旺
hydrothermal: 热液的
vent: (出烟)孔
acidic acidity: very sour酸的, 酸性的
bubble: a ball of air or gas in liquid泡沫
oxygen /ˈɒksɪdʒən $ ˈɑːk-/:氧
spring: 泉
high-up: 
extremophile: /ɪkˈstriːməfɪl/极端微生物
radiation: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things辐射
salinity: 盐分, 盐度
mimic: to copy the way someone speaks or behaves, especially in order to make people laugh SYN imitate, take off 模仿
rover: 流浪者, 漫游者
crater: a round hole in the ground made by something that has fallen on it or by an explosion弹坑
impact: the effect or influence that an event, situation etc has on someone or something冲击
meteor: a piece of rock or metal that travels through space, and makes a bright line in the night sky when it falls down towards the Earth流星
trace: 踪迹
moon: 卫星
shell: 地壳
promise: to show signs of something预示
hydrocarbon: 碳氢化合物
methane: 甲烷
ethane: 乙烷
--------------------
outer space: 外太空
abduction by sb.: 被某人的绑架
in the universe: 在宇宙中
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose利用某物
form life: 形成生命
ancient religions: 古老的宗教
be inhabited by sb.: 被某人居住
sth. be more like A. than B.: 某物更像A而不是B
mythical realms: 神话王国
parallel universes: 平行宇宙
It is only within the last century that + ...: 只在最近一个世界
undertake sth./ to do sth.: 着手做某事
A. is just the right distance from B.: A从B是适当距离的
support life: 支持生命
sth. is fatal for sb.: resulting in someone’s death某物对某人是致命的
in the dark depths of oceans/lakes/rivers: 在海洋的黑暗深处
on the flanks of volcanoes: the side of a hill, mountain, or very large building在火山的侧面
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things处于某物的极端
What is most remarkable about sth. is that + ...: 关于某物最值得注意的是...
hit the surface of sth.: 击打某物的表面
be flowing with sth.: to have some liquid coursing on the surface or within someone or something流满某物
be composed of sth.: 有...组成consist of
be the basic building block of sth.: 是某物的基础组成部分
** expression
outer space: 外太空
- The authorities feel obliged to explore outer space.
- This convinced him that lives exist in outer space.
- It is disturbing to think that the shuttle is still in outer space.
abduction by sb.: 被某人的绑架
- It's time to tell a story of abduction by little green men.
- During this time, they will give a performance to tell a story of abduction by an English.
- On these occasions, he will tell stories of abduction by green men in outer space.
in the universe: 在宇宙中
- It reminded him of a planet in the universe.
- The astronaut claimed to have left a note in the universe.
- Let's pay attention to these monsters in the universe.
draw on sth.: draw on/upon something to use information, experience, knowledge etc for a particular purpose利用某物
- She drew on her knowledge to take advantage of her students.
- She drew on this information which is unknown to her husband to cheat on him.
- She drew on this experience to develop a model for an atom.
form life: 形成生命
- It is said that life was formed on the earth in billions BC. 
- It is a blessing that life was formed in the ocean.
- In spite of drawing on diverse fields, he fails to know how life was formed on the earth.
ancient religions: 古老的宗教
- Many ancient religions have a bad reputation. 
- Many ancient religions used to have a bad reputation.
- The ancient religion may have used this room as a place of worship.
be inhabited by sb.: 被某人居住
- The promontory was inhabited by him who comes from China.
- I was amazed to find that my house had been inhabited by my nephew when I was in the prison.
- This room which was used as a place of worship happened to be inhabited by a journalist.
sth. be more like A. than B.: 某物更像A而不是B
- The figure we saw last night was more like a cat than a dog.
- Equipped with this hat, you're more like a policeman than an official.
- Despite the fact that the sculpture is more like an insect than a butterfly.
mythical realms: 神话王国
- It turned out to be a mythical realm.
- It's more like a mythical realm than a real country.
- There are drainage systems in the mythical realm.
parallel universes: 平行宇宙
- I might be having a rest in a parallel universe.
- If I didn't go to the university, I might do manual work in a parallel universe.
- These days, more and more people believe in parallel universes
		which were described by ancient religions.
It is only within the last century that + ...: 只在最近一个世界
- It is only within the last century that the ancient religion explained this story to us.
- It is only within the last century that NASA launched the shuttle into outer space.
- It is only within the last century that people have a habit of grabbing a beer after work.
undertake sth./ to do sth.: 着手做某事
- She undertook to have her drainage system repaired.
- In the end, the artist undertook to make the sculpture of the President of America.
- She refused to undertake to develop a model for an atom.
A. is just the right distance from B.: A从B是适当距离的
- She noted with satisfaction that the chair is just the right distance from the table.
- Although the chair was just the right distance from the table,
		the manager still blamed this on me.
- It seems odd that the Earth is just the right distance from the sun.
support life: 支持生命
- There is plenty of water in the vase to support life.
- The star proved to be suitable to support life.
- A star which doesn't have liquid water is not possible to support life.
sth. is fatal for sb.: resulting in someone’s death某物对某人是致命的
- These rotten foods may be fatal for your baby.
- The mixture of water and hair gel must be fatal for you.
- The chemist was made to a special type of mixture which is fatal for a baby elephant.
in the dark depths of oceans/lakes/rivers: 在海洋的黑暗深处
- There are a number of snakes in the dark depths of lakes.
- The sailor claimed that he had seen a monster in the dark depths of the ocean.
- I'm 95% sure that life was formed in the dark depths of oceans.
on the flanks of volcanoes: the side of a hill, mountain, or very large building在火山的侧面
- A patch of green began to appear on the flank of the volcano.
- A party of scientists ran into serious trouble on the flank of the volcanoes.
- I'm genuinely sorry that I left you on the flank of a volcano.
at extremes of sth.: a form of energy that comes especially from ↑nuclear reactions, which in large amounts is very harmful to living things处于某物的极端
- She must starve to death at extremes of the lack of food.
- No life could thrive at extremes of temperature.
- I wished that they had survived at extremes of radiation.
What is most remarkable about sth. is that + ...: 关于某物最值得注意的是...
- What is most remarkable about an atom is that its electrons are free to move.
- What is most remarkable about the prizefighter is that he brought science to this sport.
- What is most remarkable about this guy is
		that he is one of the key founders of positive psychology movement.
hit the surface of sth.: 击打某物的表面
- I wish that the hammer didn't hit the surface of the table.
- I had an opportunity to hit the surface of the moon.
- There is an element of truth that the cat hit the surface of television.
be flowing with sth.: to have some liquid coursing on the surface or within someone or something流满某物
- The river must be flowing with some broken wood after a heavy shower.
- The river used to be flowing with some cigarette ends which were threw by inhabitants.
- It turned my stomach when I saw the river being flowing with these bodies.
be composed of sth.: 有...组成consist of
- The mixture is said to be composed of fruit juice and milk.
- I have the impulse to throw away the drink which is composed of orange juice and milk.
- It's well-known that an atom is composed of electrons, protons, and neutrons.
be the basic building block of sth.: 是某物的基础组成部分
- My teacher said that reading and listening is the basic building block of English skills.
- For instance, water is the basic building block of life.
- Good ingredients are the basic building block of a good meal. 
** summary writting
Astrobiology takes advantage of diverse fields, such as physics, biology, astronomy, and geology,
	to study the form of life on Earth and how to detect it.
Although there are many vivid says about other worlds in ancient religious,
	only within the last century
		scientists can undertake the search for extraterrestrial life.
We used to believe that life could only form in Earth-like environments,
	however, astrobiologist makes a discovery
		that extremophiles can survive at extremes of temperature, pressure, and radiation,
			as well as salinity, acidity, and limited availability of sunlight, water, or oxygen.
This environment mimics those on alien worlds.
Not only the planet, Mars, may exist life in Gale Crater which may support life,
	but the moons of some planets proved to have earth-like environments.
Astrobiologists are working to learn about these extremophiles on the earth
	to figure out whether there is extraterrestrial life in outer space.
