#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-10-08 What is the shape of a molecule
#+begin_verse
1
What is the shape of a molecule?
Well, a molecule is mostly empty space.
Almost all of its mass is concentrated in the extremely dense nuclei of its atoms.
And its electrons, which determine how the atoms are bonded to each other,
	are more like clouds of negative charge than individual, discrete particles.
So, a molecule doesn't have a shape in the same way that, for example, a statue has a shape.
But for every molecule,
	there's at least one way to arrange the nuclei and electrons
		so as to maximize the attraction of opposite charges
			and minimize the repulsion of like charges.
Now, let's assume
	that the only electrons that matter to a molecule's shape
		are the outermost ones from each participating atom.
And let's also assume
	that the electron clouds in between atoms,
		in other words, a molecule's bonds, are shaped kind of like sausages.
Remember that nuclei are positively charged and electrons are negatively charged,
	and if all of a molecule's nuclei were bunched up together
			or all of its electrons were bunched up together,
		they would just repel each other and fly apart, and that doesn't help anyone.
2		
In 1776, Alessandro Volta, decades before he would eventually invent batteries, discovered methane.
Now, the chemical formula of methane is CH4.
And this formula tells us
	that every molecule of methane is made up of one carbon and four hydrogen atoms,
	but it doesn't tell us what's bonded to what
		or how they atoms are arranged in 3D space.
From their electron configurations,
	we know that carbon can bond with up to four other atoms
		and that each hydrogen can only bond with one other atom.
So, we can guess that the carbon should be the central atom bonded to all the hydrogens.
Now, each bond represents the sharing of two electrons
	and we draw each shared pair of electrons as a line.
3	
So, now we have a flat representation of this molecule,
	but how would it look in three dimensions?
We can reasonably say
	that because each of these bonds is a region of negative electric charge
		and like charges repel each other,
	the most favorable configuration of atoms would maximize the distance between bonds.
And to get all the bonds as far away from each other as possible, the optimal shape is this.
This is called a tetrahedron.
4
Now, depending on the different atoms involved, you can actually get lots of different shapes.
Ammonia, or NH3, is shaped like a pyramid.
Carbon dioxide, or CO2, is a straight line.
Water, H2O, is bent like your elbow would be bent.
And chlorine trifluoride, or ClF3, is shaped like the letter T.
Remember that what we've been doing here
	is expanding on our model of atoms and electrons to build up to 3D shapes.
We'd have to do experiments to figure out
	if these molecules actually do have the shapes we predict.
Spoiler alert: most of the do, but some of them don't.
Now, shapes get more complicated as you increase the number of atoms.
All the examples we just talked about had one obviously central atom,
	but most molecules,
			from relatively small pharmaceuticals all the way up to long polymers like DNA or proteins,
		don't.
The key thing to remember is
	that bonded atoms will arrange themselves to maximize the attraction between opposite charges
		and minimize the repulsion between like charges.
Some molecules even have two or more stable arrangements of atoms,
	and we can actually get really cool chemistry from the switches between those configurations,
		even when the composition of that molecule,
			that's to say the number and identity of its atoms,
		has not changed at all.
#+end_verse

** expression
#+begin_verse
molecule: 
mass: a large amount or quantity of something
nuclei: 
discrete: clearly separate
sausages: a small tube of skin filled with a mixture of meat, spices etc 
formula: a series of numbers or letters that represent a mathematical or scientific rule: 
favorable: suitable and likely to make something happen or succeed: 
--------------------
be concentrated in: 
be bonded to: 与……紧密相连
there's at least one way to do sth.: 
maximize/minimize the attraction/repulsion of: 
A. matter to B.: A对B重要
A. be the outermost one(s) from B.: A是B最远的部分
in between sth.: 在...之间
be kind of like sth.: 
be bunched up together: 被聚拢在一起
fly apart: 四分五裂,飞离
doesn't help anyone: 
decades before: 
be arranged in 3D space: 
bond with sth./sb.: 与他人建立紧密联系
draw sth. as a line: 
have a flat representation of sth.: 
in three dimensions: 
get A. far away from B.: 
expand on our model of sth. to do sth.: 扩展xx的模型去做某事
Spoiler alert: 剧透
#+end_verse
** full expression
#+begin_verse
be concentrated in: 
- Almost all students in the town are concentrated in front of the museum.
- Almost all my pocket money is concentrated in the box.
- All my attention is concentrated on the beautiful girl. 
be bonded to: 与……紧密相连
- This Buddhist nun is bonded to the fall of smallpox.
- The vicar pointed out that the cursed tree is bonded to the source of income. 
- Bonded to the manager, he has a bad reputation.
there's at least one way to do sth.: 
- There's at least one way to complete this course.
- There's at least one way to be an expert at pressing the button.
- There's at least one way to fulfill your dream.
maximize/minimize the attraction/repulsion of: 
- She has a habit of reading in the subway, which maximizes the attraction of her husband and her.
- Removing the button from the door, he maximized the repulsion of his dog and him.
- I maximized the repulsion of my cat and me so that she smashed everything to pieces.
A. matter to B.: A对B重要
- I get tired of those tasks which matter to my English exam.
- A gust of wind swept the expensive bed which mattered to my grandfather.
- You should rest for a while now, which matters to your health.
A. be the outermost one(s) from B.: A是B最远的部分
- I seem to be the outermost one from our group.
- I don't want to be the outermost one from our class anymore.
- For the first time in my life, I was the outermost one from my family. 
in between sth.: 在...之间
- I took the seat in between the manager and my leader.
- I couldn't hear a word in between the young woman and the young man.
- It might be time to take a seat in between these couples.
be kind of like sth.: 
- The shape is kind of like some monsters from outer space.
- It's kind of like mythical realms inhabited by known human beings.
- He developed a model for an atom kind of like a water ripple.
be bunched up together: 被聚拢在一起
- These struck busmen were bunched up together to reach an agreement.
- The pen pals who have been interacting with each other were bunched up together last week.
- These particles may have been bunched up together.
fly apart: 四分五裂,飞离
- These organs began to fly apart at the extreme of pressure.
- The car hit the surface of the building and flew apart.
- The machinery is not supposed to fly apart on the flanks of volcanoes.
doesn't help anyone: 
- Stop complaining, it doesn't help anyone.
- Don't interrupt me, it doesn't help anyone.
- Although you make many building blocks of cars, these don't help anyone.
decades before: 
- Decades before he has been able to undertake the search of extremophiles.
- Decades before he proved that Mars might support life.
- Decades before smallpox had been fatal for us.
be arranged in 3D space: 
- What is remarkable about the robot is how its building blocks are arranged in 3D spaces.
- How these atoms are arranged in 3D space is still a mystery.
- She tries to figure out how these items are arranged in 3D space.
bond with sth./sb.: 与他人建立紧密联系
- With this procedure, we bonded with each other.
- I have some close friends who bond with me a great deal.
- The actor who bonds with the director was cast in the role of a new movie.
draw sth. as a line: 
- It's time to draw points A and B as a line.
- There's a certain probability of drawing the two electrons as a line.
- She draws points A and B as a line to develop a model for an atom.
have a flat representation of sth.: 
- The manager behaves like he has a flat representation of the layer of the building.
- There is some small, but non-zero, probability that he has a flat representation of this house.
- I have a flat representation of the house
		 that suggests this room is just the right distance from the dining room.
in three dimensions: 
- It looks kind of like a rabbit in three dimensions.
- What does it look like in three dimensions?
- Why does it look like a rabbit in three dimensions?
get A. far away from B.: 
- I must get my daughter far away from home.
- After getting her daughter far away from the castle, the king began to reminisce about her mother.
- I managed to get the colleague far away from me.
expand on our model of sth. to do sth.: 扩展xx的模型去做某事
- He expanded on his model of electrons and protons to explain this phenomenon to his students.
- He expanded on his model of cells to bring about the fall of smallpox.
- Telescopes make it possible for him to expand on his model of stars.
Spoiler alert: 
- Spoiler alert: I passed the test.
- Spoiler alert: he was killed in the end.
- Spoiler alert: he didn't marry Jim.
#+end_verse

