#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-10-08 The operating system of life
#+begin_verse
Every chicken was once an egg, every oak tree an acorn, every frog a tadpole.
The patch of mold on that old piece of bread in the back of your fridge,
	not so long ago was one solitary cell.
Even you were once but a gleam in your parents' eyes.
All these organisms share the same basic goal: to perpetuate their own existence.

All lifeforms that we've discovered so far
	stay alive by using basically the same rules, materials, and machinery.
Imagine a factory full of robots.
These robots have two missions:
	one, keep the factory running, and two, when the time is right, set up an entirely new factory.
To do those things, they need assembly instructions, raw materials, plenty of energy,
	a few rules about when to work normally, when to work quickly, or when to stop,
		and some exchange currencies because even robots need to get paid.
Each factory has a high security office with blueprints
	for all the possible factory configurations
		and complete sets of instructions to make all the different types of robots
			a factory could ever need.
Special robots photocopy these instructions and send them off
	to help make the building blocks of more robots.
Their colleagues assemble those parts into still more robots,
	which are transported to the right location in the factory
		and given the tools they need to start working.
Every robot draws energy from the central power plant,
	a giant furnace that can burn regular fuel
		but also scrap materials if not enough regular fuel is available.
Certain zones in the factory have harsher working conditions,
	so these areas are walled off.
But the robots inside can at least communicate with the rest of the factory
	through specialized portals embedded directly into the walls.
	
And as you've probably figured out,	what we're describing here is a cell.
The high security office is the nucleus.
It stores the blueprints and instructions as deoxyribonucleic acid, or DNA.
The photocopied instructions are RNA.
The robots themselves are mostly proteins built from amino acids,
	but they'll often use special tools that are, or are derived from, vitamins and minerals.
The walls between factory zones and around the factory itself
	are mostly made up of lipids, a.k.a. fats.
In most organisms, the primary fuel source are sugars,
	but in a pinch, fats and proteins can be broken down and burned in the furnace as well.
The portals are membrane proteins
	which allow very specific materials and information to pass through the walls at the right times.
Many interactions between robot proteins require some kind of push, think robot minimum wage.
A few small but crucial forms of money are transferred between proteins to provide this push.
Electrons, protons, oxygen, and phosphate groups are the main chemical currencies,
	and they're kept in small molecular wallets or larger tote bags to keep them safe.
This is biochemistry,
	the study of how every part of the factory interacts
		to keep your life running smoothly in the face of extreme challenges.
		
Maybe there's too much fuel; your body will store the excess as glycogen or fat.
Maybe there's not enough; your body will use up those energy reserves.
Maybe a virus or bacteria tries to invade; your body will mobilize the immune system.
Maybe you touched something hot or sharp; your nerves will let you know so you can stop.
Maybe it's time to create a new cell or a new person.
Amazingly, oak trees, chickens, frogs,
	and, yes, even you share so many of the same basic robot and factory designs
		that biochemists can learn a lot about all of them all at the same time. 
#+end_verse
** expression
oak [əʊk]: n. a large tree that is common in northern countries, or the hard wood of this tree橡树, 橡木
acorn [ˈeɪˌkɔrn]: n. the nut of the ↑oak tree[植]橡树果
tadpole [ˈtædˌpoʊl]: n. a small creature that has a long tail, lives in water, and grows into a frog or toad[动]蝌蚪
mold [moʊld]: n. a soft green, grey, or black substance that grows on food which has been kept too long, and on objects that are in warm wet air ⇨ mouldy:霉菌 
solitary [ˈsɑləˌteri]: adj. used to emphasize that there is only one of something SYN single孤独的
lifeform : n. 生物
machinery [məˈʃinəri]: n. machines, especially large ones[总称] 机器, 机械
mission [ˈmɪʃ(ə)n]: n. something that you feel you must do because it is your duty SYN calling, vocation使命, 任务
currency [ˈkʌrənsi]: n. the system or type of money that a country uses货币
blueprint [ˈbluˌprɪnt]: n. technical a pattern that all living cells contain, which decides how a person, animal, or plant develops and what it looks like蓝图
photocopy [ˈfoʊtoʊˌkɑpi]: v. to make a photographic copy of something影印
giant [ˈdʒaɪənt]: adj. extremely big, and much bigger than other things of the stype庞大的, 巨大的
furnace [ˈfɜrnɪs]: n. a large container for a very hot fire, used to produce power, heat, or liquid metal炉子, 熔炉
fuel [ˈfjuːəl]: n. a substance such as coal, gas, or oil that can be burned to produce heat or energy燃料
scrap [skræp]: v. to get rid of an old machine, vehicle etc, and use its parts in some other way拆毁
specialized [ˈspeʃ(ə)lˌaɪzd]: adj. trained, designed, or developed for a particular purpose, type of work, place etc专门的
portal [ˈpɔrt(ə)l]: n. literary a tall and impressive gate or entrance to a building入口
deoxyribonucleic [diˌɒksiraɪboʊnu'kliɪk] acid: DNA
protein [ˈproʊtin]: n. one of several natural substances that exist in food such as meat, eggs, and beans, and which your body needs in order to grow and remain strong and healthy[生化]蛋白质
amino [ə'mi:no]: adj. 氨基的
acid [ˈæsɪd]: n. a chemical substance that has a ↑pH of less than 7. Strong acids can burn holes in material or damage your skin[化]酸
mineral [ˈmɪn(ə)rəl]: n. a substance that is formed naturally in the earth, such as coal, salt, stone, or gold. Minerals can be dug out of the ground and used矿物, 矿石
lipid [ˈlɪpɪd]: n. technical one of several types of ↑fatty substances in living things, such as fat, oil, or ↑wax脂质, 油脂
a.k.a.: also known as, 又名..., 也叫作...
membrane [ˈmemˌbreɪn]: n. a very thin piece of skin that covers or connects parts of your body膜, 隔膜
interaction [ˌɪntərˈækʃən]: n. a process by which two or more things affect each other交互作用
crucial [ˈkruʃ(ə)l]: adj. something that is crucial is extremely important, because everything else depends on it SYN vital至关紧要的
phosphate [ˈfɑsˌfeɪt]: n. a substance containing a phosphate used for making plants grow better磷酸盐
molecule molecular [məˈlekjələr]: n.adj. the smallest unit into which any substance can be divided without losing its own chemical nature, usually consisting of two or more atoms[化]分子
tote [toʊt]: v. informal to carry something, especially regularly手提, 背负, 携带
biochemistry [ˌbaɪoʊˈkemɪstri]: n. the scientific study of the chemistry of living things生物化学
excess [ˈekˌses]: n. a larger amount of something than is allowed or needed超额
glycogen [ˈɡlaɪkədʒən]: n. 肝糖, 糖原质
bacteria [bækˈtɪriə]: n. very small living things, some of which cause illness or disease ⇨ virus细菌
-------------------
in the back of your fridge: 冰箱深处
sb. is a gleam in sb's eyes: A是B的构想
share the same basic goal: 拥有相同的基本目标
perpetuate sb's existence: 使某人永久存在
stay alive: 设法不死
set up a factory: 开办工厂
keep sb. doing sth.: 使某人做某事
assembly instructions: 装配说明
raw materials: 原材料
get paid: 获得报酬
send sth. off: to send a letter, document, or package by mail
assemble A. into B.: 将A组装成B
be transported to sp.: 被运送到某地
draw energy from sth.: 从某物那里获取能量
harsher working conditions: 艰苦的工作环境
be walled off: 被隔离起来
the rest of sth.: 某物剩余部分
be embedded into sth.: 被嵌入到某物
be built from sth.: 由某物建造
are derived from: to come or develop from something 来源于
in a pinch: in an emergency
minimum wage: 最低薪酬
be transferred between: to move someone or something from one place, vehicle, person, or group to another
in the face of sth.: 面对某事物
extreme challenges: 极限挑战
mobilize the immune system: 激起防御系统
** sentences
in the back of your fridge: 冰箱深处
- My wife complained that a patch of mold began to appear in the back of our fridge.
- His aim is to molten the big piece of ice in the back of his fridge.
- My mom left a piece of bread in the back of my fridge in recognition of me.
sb. is a gleam in sb's eyes: A是B的构想
- Our baby is still being a gleam in our eyes.
- The probability of living in outer space is a gleam in our eyes.
- You used to be a gleam in your parents' eyes.
share the same basic goal: 拥有相同的基本目标
- The group of pop singers share the same basic goal: to make enough money to travel all over the world.
- It's hard for me to share my house with a girl who doesn't share the same basic goal.
- Sharing the same basic goal may be the basic building block of a marriage.
perpetuate sb's existence: 使某人永久存在
- Although he quaked in every limb and in his soul, he succeeded in perpetuating his existence during the war.
- The first aim of every life is to perpetuate his own life.
- It reminds me of an ant
		which was trying to perpetuate its existence while I played jokes on it.
stay alive: 设法不死
- The ants have eaten plenty of food to stay alive in the desert.
- It's a pity that he wasn't able to stay alive in the flood.
- It's incredible how he stayed alive when the volcanoes were erupting.
set up a factory: 开办工厂
- In the end, he managed to set up a factory which launches a telescope into space.
- He set up a factory which named after his daughter.
- It was wondering whether she succeeded in setting up a robot factory. 
keep sb. doing sth.: 使某人做某事
- She has kept her son who deserted in the war hiding for over ten years. 
- He kept his daughter laughing at the reception.
- I admired him for keeping everyone around him staying positive.
assembly instructions: 装配说明
- When the police arrived on the scene, they found the assembly instructions.
- It was not long before that we received the assembly instructions.
- Following assembly instructions, he managed to piece those together.
raw materials: 原材料
- The pretty girl invited me to collect raw materials.
- As raw materials began to accumulate, the warehouse soon became crowded.
- A cargo of raw materials will sail from Beijing to London.
get paid: 获得报酬
- As soon as agreement is reached about the salary, you will get paid.
- I was relieved to hear that my wife got paid.
- I didn't get paid on time and I was under a lot of pressure.
send sth. off: to send a letter, document, or package by mail
- This advertisement was sent off to protect baby elephants.
- The manager sent assembly instructions off to help his staff work better.
- These pigeons are going to send these letters off.
assemble A. into B.: 将A组装成B
- He assembled these woods into a car under a lot of pressure.
- He volunteers to assemble these materials into a toy.
- He managed to assemble these parts into a model in time to pass the test.
be transported to sp.: 被运送到某地
- A cargo of raw materials has been transported to Space X.
- For your safety, your companion was transported to the hospital.
- I noticed with dismay that the golden watches hadn't been transported to England.
draw energy from sth.: 从某物那里获取能量
- Your phone draws energy from the battery inside. 
- All lives on the earth draw energy from the sun more or less. 
- While swimming across the Channel, she must draw energy from liquid foods.
harsher working conditions: 艰苦的工作环境
- Workers can't stay alive in the harsher working conditions. 
- I might lose my life in the harsher working conditions.
- He often volunteers to repair bicycles in memory of his early harsher working conditions.
be walled off: 被隔离起来
- These rooms must have been walled off.
- The north area of London and the south area used to be walled off.
- She stated that the enclosure of these dogs should have been walled off. 
the rest of sth.: 某物剩余部分
- I will love you for the rest of my life.
- She tends to communicate with the rest of her classmates.
- I have eaten the rest of these meals.
be embedded into sth.: 被嵌入到某物
- The light is embedded into the ceiling.
- The battery is designed to be embedded into the phone.
- The bath was able to be embedded into your bathroom.
be built from sth.: 由某物建造
- Proteins prove to be built from amino acids.
- The diamonds are built from stones and sand.
- The house is specially built from iron and glass.
are derived from: to come or develop from something 来源于
- The assembly instructions are derived from the construction of the toy.
- The fats are derived from a special type of pig.
- My pocket money is usually derived from my aunts.
in a pinch: in an emergency
- In a pinch, she began to fight with gangsters with her bare hands.
- In a pinch, these two men quarreled bitterly and that argument must be settled by a fight.
- In a pinch, she stood up to speak in public.
minimum wage: 最低薪酬
- His boss squinted at him and just paid the minimum wage. 
- If you keep paid the minimum wage, I will quit.
- His boss proceeded to pay her the minimum wage.
be transferred between: to move someone or something from one place, vehicle, person, or group to another
- These days, the singer is being transferred between group A and group B.
- The spare parts must be transferred between these garages.
- The spare parts might have been transferred between these garages.
in the face of sth.: 面对某事物
- They were separated from each other in the face of the war.
- He lodged a complaint in the face of the delay of the train.
- He is sensitive about accepting criticism in the face of his parents.
extreme challenges: 极限挑战
- She always stays positive in the face of extreme challenges. 
- After extreme challenges, our company began to make a profit.
- While we are in the face of extreme challenges, we must make these rules official. 
mobilize the immune system: 激起防御系统
- She died of a rare disease that disables her to mobilize the immune system.
- Your body is mobilizing the immune system to fight against the invasion of bacteria.
- She can't mobilize her immune system because of a special type of virus.
** summary writting
#+begin_verse
All organisms which were once one solitary cell share the same basic goal:
	to perpetuate their existence.
Image a factory full of robots have two missions:
	to keep the factory running and to set up a new factory at the right time.
It has an office with blueprints for its configurations
	and sets of instructions to make robots,
	some of which photocopy these instructions
		and send them off to help make the building block of more robots,
	some of which assemble those parts into more robots
		and give these robots the necessary tools to start working.
Every robot draws energy from a giant furnace
	that not only burn regular fuel but also scarp materials in a pinch.
Although the furnace is walled off,
	the robots inside can interact with the rest of the factory through specialized portals.
The factory we're describing here is a cell.
The blueprints, photocopied instructions, robots, and wall
	respectively are DNA, RNA, proteins, and fats.
They work together to keep our lives running smoothly in the face of some extreme challenges.
#+end_verse
