#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* The uncertain location of electrons
#+begin_verse
George Zaidan and Charles Morto
1
You probably know that all stuff is made up of atoms
	and that an atom is a really, really, really, really tiny particle.
Every atom has a core,
	which is made up of at least one positively charged particle called a proton,
	and in most cases, some number of neutral particles called neutrons.
That core is surrounded by negatively charged particles called electrons.
The identity of an atom is determined only by the number of protons in its nucleus.
Hydrogen is hydrogen because it has just one proton,
	carbon is carbon because it has six,
	gold is gold because it has 79, and so on.
2	
Indulge me in a momentary tangent.
How do we know about atomic structure?
We can't see protons, neutrons, or electrons.
So, we do a bunch of experiments and develop a model for what we think is there.
Then we do some more experiments and see if they agree with the model.
If they do, great.
If they don't, it might be time for a new model.
We've had lots of very different models for atoms since Democritus in 400 BC,
	and there will almost certainly be many more to come.
Okay, tangent over.
3
The cores of atoms tend to stick together,
	but electrons are free to move,
	and this is why chemists love electrons.
If we could marry them, we probably would.
But electrons are weird.
They appear to behave either as particles, like little baseballs, or as waves, like water waves,
	depending on the experiment that we perform.
One of the weirdest things about electrons is that we can't exactly say where they are.
It's not that we don't have the equipment,
	it's that this uncertainty is part of our model of the electron.
So, we can't pinpoint them, fine.
But we can say
	there's a certain probability of finding an electron in a given space around the nucleus.
And that means that we can ask the following question:
	If we drew a shape around the nucleus
			such that we would be 95% sure of finding a given electron within that shape,
		what would it look like?
4	
Here are a few of these shapes.
Chemists call them orbitals, and what each one looks like depends on, among other things,
	how much energy it has.
The more energy an orbital has, the farther most of its density is from the nucleus.
By they way, why did we pick 95% and not 100%?
Well, that's another quirk of our model of the electron.
Past a certain distance from the nucleus,
	the probability of finding an electron starts to decrease more or less exponentially,
		which means that while it will approach zero, it'll never actually hit zero.
So, in every atom, there is some small, but non-zero, probability that
	for a very, very short period of time,
		one of its electrons is at the other end of the known universe.
But mostly electrons stay close to their nucleus as clouds of negative charged density
	that shift and move with time.
5	
How electrons from one atom interact with electrons from another determines almost everything.
Atoms can give up their electrons, surrendering them to other atoms, or they can share electrons.
And the dynamics of this social network are what make chemistry interesting.
From plain old rocks to the beautiful complexity of life,
	the nature of everything we see, hear, smell, taste, touch, and even feel is
		determined at the atomic level. 
#+end_verse
** expression
1
particle: a very small piece of something 
proton: a very small piece of matter with a positive electrical charge that is in the central part of an atom
neutral: not supporting any of the people or groups involved in an argument or disagreement
The identity of sth.: 
nucleus: 
2
Indulge: to let yourself do or have something that you enjoy
in a momentary tangent: to start talking about something that is only slightly or indirectly related to the original subject
develop a model for sth.: 
agree with the model: 
it might be time for doing/sth.: 
there will be many more to come: 
3
tend to do sth.: 
stick together: 
behave either as particles: 
perform experiment : 
It's (not) that + ...: 
there's a certain probability of doing sth.: 
be 95% sure of doing: 
orbitals /ˈɔːbɪtl/: ring road
density: the degree to which an area is filled with people or things
quirk: a strange habit or feature of someone’s character, or a strange feature of something: 
exponentially /ˌekspəˈnenʃəl/: 
approach zero: 
hit zero: 
there is some small, but non-zero, probability that: 
for a very, very short period of time: 
interact with: 
surrender A. to B.: to give up something or someone, especially because you are forced to
at the atomic level: 
