#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

* 2013-11-04 The deadly irony of gunpowder
#+begin_verse
Everybody loves fireworks -- the lights, the colors, and, of course, the big boom.
But the history of fireworks isn't all hugs and celebrations.
Long before epic fireworks displays,
	chemists in China invented the key ingredient that propels those bright lights into the sky.
That invention was what we now call gunpowder.

Our story begins back in ancient China in the mid-ninth century
	where early Chinese alchemists were trying to create a potion for immortality.
Instead, what they created was a flammable powder that burned down many of their homes.
They quickly realized that this black powder,
		which they called fire medicine,
	was precisely the opposite of something that would make you live forever.
In these early days, the Chinese hadn't yet figured out how to make the powder explode;
	it was simply very flammable,
		and their armies used it to make flaming arrows and even a flamethrower.
But once they figured out the right proportions of ingredients to create a blast,
	they began using the powder even more,
		creating fireworks to keep evil spirits away
				and bombs to defend themselves against Mongol invaders.
It was these Mongols,
	most likely, who spread the invention of gunpowder across the world.
After fielding Chinese attacks,
	they learned how to produce the powder themselves
		and brought it with them on their conquests in Persia and India.
William of Rubruck, a European ambassador to the Mongols,
	was likely responsible for bringing gunpowder back to Europe around 1254.
From there, engineers and military inventors created all kinds of destructive weapons.
From bombs to guns to cannons,
	gunpowder left its mark on the world in some pretty terrible ways,
		in contrast to the beautiful marks it can leave in the air.
		
So, how does black powder propel fireworks into the sky?
You might have seen old Westerns or cartoons
	where a trail of gunpowder is lit and it leads to a large and obviously explosive barrel.
Once the fire gets to the barrel, a large boom occurs.
But why doesn't the trail itself explode?
The reason is that burning the powder releases energy and gases.
While the trail is burning, these are easily released into the surrounding air.
But when the gunpowder is contained within the barrel,
	the energy and gases cannot easily escape and build up until BOOM!
Firework canisters provide a single, upward-facing outlet to channel this explosive energy.
The wick ignites the gunpowder and the energy takes the easiest exit from the canister,
	launching the firework high into the sky.
The flame then makes its way through the firework's encasing
	and the same reaction occurs high above our heads.
So, while the Chinese alchemists never found the compound for eternal life,
	they did find something that would go on to shape all of civilization,
		something that has caused many tragic moments in human history,
			and yet still gives us hope when we look up in celebration at the colorful night sky.
#+end_verse
** expression
epic [ˈepɪk]: adj. very large and impressive壮丽的, 大规模的
gunpowder [ˈɡʌnˌpaʊdər]: n. an explosive substance used in bombs and fireworks黑色火药
alchemist [ˈælkəmɪst]: n. a science studied in the Middle Ages, that involved trying to change ordinary metals into gold炼金术士
flame [fleɪm] flammable [ˈflæməb(ə)l] : n.adj. literary to burn brightly火焰
cannon [ˈkænən]: n. a large heavy powerful gun that was used in the past to fire heavy metal balls 加农炮
barrel [ˈberəl]: n. a large curved container with a flat top and bottom, made of wood or metal, and used for storing beer, wine etc桶
canister [ˈkænɪstər]: n. a metal container for keeping something in (放咖啡, 茶叶, 烟等的)小罐, 筒
channel [ˈtʃæn(ə)l]: v. to control or direct people or things to a particular place, work, situation etc引导, 开导
wick [wɪk]: n. the piece of thread in a candle, that burns when you light it灯芯
ignite [ɪɡˈnaɪt]: v. formal to start burning, or to make something start burning 点火, 点燃
compound [ˈkɑmˌpaʊnd]: n. a substance containing atoms from two or more elements 混合物
shape [ʃeɪp]: v. to influence something such as a belief, opinion etc and make it develop in a particular way形成, 影响
upward-facing [ˈʌpwərd-feɪsɪŋ]: adj. 面向上
--------------------
fireworks displays: 烟火展
propel sth. into sp.: to move, drive, or push something forward推动某事到某地
begin back: to begin to return somewhere倒回
a potion for immortality: 永生药
the opposite of sth.: 某物的反面
In these early days: 在早些年代
the right proportions of ingredients: 配料的正确比例
evil spirits: 恶灵
defend sb. against sth./sb.: 保卫某人免于...
the invention of sth.: 某物的发明
field sb's attacks: 回击某人的攻击
on sb's conquests in sp.: 在某人某地的征服中
bringing sth. back to sp.: 把某物带回某地
From there: 从这里
left sb's mark on sth.: to have an effect that changes someone or something, usually in a bad way在某事上留下某人的印记
in contrast to: it is very different from it与……相反
be contained within/in: 包含在…之内
build up: accumulate积累
take an exit from sp.: 从...出去
** sentences
fireworks displays: 
- The authorities informed us that there would be some epic fireworks displays.
- There used to be a large number of fireworks displays in the vicinities of Hangzhou.
- The authorities decided to make an epic fireworks display to keep away evil spirits.
propel sth. into sp.: to move, drive, or push something forward
- He managed to propel these candles into the sky.
- Are you suggesting that we propel these candles into the sky?
- I must tell you the truth that we propelled these candles into the sky last night.
begin back: to begin to return somewhere
- Our story must begin back at a village fair.
- Our story may begin back at a village fair.
- Our story began back in ancient Greece when it was being invaded by the Hittites.
a potion for immortality: 永生药
- It is said that an alchemist contributed to a potion for immortality.
- He has a lot of patience to pursue a potion for immortality.
- Who encouraged you to make a potion for immortality?
burn down: to destroy something with fire, or to be destroyed in this way
- Honey, why do you get into such a mess? Our house has been just burnt down.
- If the palace hadn't been burnt down, we would have had a lot of evidence of our history.
- I have memories of the house which was burnt down last year.
the opposite of sth.: 
- Giving up practices is the opposite of something that makes you pass the test.
- Quarrelling bitterly is the opposite of something that settles the argument.
- Complaint is the opposite of something that gets you away from trouble.
In these early days: 
- In these early days, these merchants from Persia had to pay protection money.
- In these early days, if you didn't pay protection money, you would soon be put out of business.
- In these early days, he devoted himself to gardening.
the right proportions of ingredients: 
- Once they figure out the right proportions of ingredients,
		they will invade us and devastate our civilization.
- People in Florence gave him a state funeral in memory of the alchemist
		who figured out the right proportions of ingredients of the gunpowder.
- He dedicated himself to the right proportions of ingredients of the gunpowder.
evil spirits: 
- It's no use pretending that you are an evil spirit.
- The vicar pointed out that these saying evil spirits are a source of income.
- The Buddhist non has had a bad reputation for raising evil spirits.
defend sb. against sb.: 
- The soldiers from China succeeded in defending the people in South Korea against the Americans.
- It is a blessing that our soldiers defend themselves against the American invaders.
- These young men are eager to defend our country against these invaders.
the invention of sth.: 
- The invention of gunpowder may have a bad influence on us.
- He prides himself on the invention of the lamp.
- The invention of the map exerts a positive influence on us.
field sb's attacks: 
- The Mongols managed to field China's attacks.
- After fielding China's attacks, they bought a lot of gunpowder from China.
- I anticipate that we will not be able to field China's attacks.
on sb's conquests in sp.: 
- He became an expert at putting out fires on his conquests in China.
- He was infected with smallpox on his conquests in China.
- He must have been infected with smallpox on his conquests in China. 
bring sth. back to sp.: 
- I asked my grandfather to bring some meals back home.
- Sir, you can't bring our chairs back to your house.
- I really appreciate that you brought my skirt back to our school.
From there: 
- From there, they enjoyed studying in the school.
- From there, he played piano every day.
- From there, China has surrendered this island to England.
left sb's mark on sth.: to have an effect that changes someone or something, usually in a bad way
- The invention of gunpowder left its mark on the history of China.
- The headmaster who dedicated himself to teaching left his mark on the development of the school.
- The loss of the Titanic left its mark on the history of voyages.
in contrast to sth.: it is very different from it
- He is in contrast to his sister.
- In contrast to his father, aunts and uncles provided a regular supply of pocket money. 
- In contrast to sweets, he bought himself fifty dollars worth of trouble.
be contained within/in: 
- The soap and butter should have been contained in the box.
- The soap and butter needn't have been contained in the box.
- If the soap had been contained in the box, we wouldn't have left it at home.
build up: accumulate
- My anger had built up until she apologized to me.
- His knowledge began to build up so he passed the test.
- My pocket money builds up so that I can buy a PlayStation in the future.
take an exit from sp.: 
- I must take an exit from the office now.
- She insists on taking an exit from the office now.
- You shouldn't prevent me from taking an exit from the house.
