#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-02-12 The history of marriage
#+begin_verse
There have been many different things written and said about marriage.
From the sweetly inspirational to the hilariously cynical.
But what many of them have in common
	is that they sound like they express a universal and timeless truth,
	when in fact nearly everything about marriage,
		from its main purpose
			to the kinds of relationships it covers
			to the rights and responsibilities involved,
		has varied greatly between different eras, cultures and social classes.
So, let's take a quick look at the evolution of marriage.

Pair bonding and raising children is as old as humanity itself.
With the rise of sedentary agricultural societies about 10,000 years ago,
	marriage was also a way of securing rights to land and property
		by designating children born under certain circumstances as rightful heirs.
As these societies became larger and more complex,
	marriage became not just a matter between individuals and families,
		but also an official institution governed by religious and civil authorities.
And it was already well established by 2100 B.C.
	when the earliest surviving written laws in the Mesopotamian Code of Ur-Nammu
		provided many specifics governing marriage,
			from punishments for adultery to the legal status of children born to slaves.
	
Many ancient civilizations allowed some form of multiple simultaneous marriage.
And even today, less than a quarter of the world's hundreds of different cultures prohibit it.
But just because something was allowed doesn't mean it was always possible.
Demographic realities, as well as the link between marriage and wealth, meant that
	even though rulers and elites in Ancient Mesopotamia, Egypt and Israel
		had multiple concubines or wives,
	most commoners could only afford one or two tending towards monogamy in practice.
In other places, the tables were turned,
	and a woman could have multiple husbands as in the Himalayan Mountains
		where all brothers in a family marrying the same woman
			kept the small amount of fertile land from being constantly divided into new households.
			
Marriages could vary not only in the number of people they involved
	but the types of people as well.
Although the names and laws for such arrangements may have differed,
	publicly recognized same-sex unions have popped up in various civilizations throughout history.
Mesopotamian prayers included blessings for such couples,
	while Native American Two-Spirit individuals had relationships with both sexes.
The first instances of such arrangements actually being called 'Marriage' come from Rome,
	where the Emperors Nero and Elagabalus both married men in public ceremonies
		with the practice being explicitly banned in 342 A.D.
But similar traditions survived well into the Christian era,
	such as Adelphopoiesis,
		or "brother-making" in Orthodox churches,
		and even an actual marriage between two men recorded in 1061 at a small chapel in Spain.
Nor was marriage even necessarily between two living people.
Ghost marriages, where either the bride or groom were deceased,
	were conducted in China to continue family lineages or appease restless spirits.
And some tribes in Sudan maintain similar practices.

Despite all these differences, a lot of marriages throughout history did have one thing in common.
With crucial matters like property and reproduction at stake,
	they were way too important to depend on young love.
Especially among the upperclasses, matches were often made by families or rulers.
But even for commoners, who had some degree of choice, the main concern was practicality.
The modern idea of marriage as being mainly about love and companionship
	only emerged in the last couple of centuries.
With industrialization, urbanization and the growth of the middle class
	more people became independent from large extended families
		and were able to support a new household on their own.
Encouraged by new ideas from the Enlightenment,
	people began to focus on individual happiness and pursuits,
		rather than familial duty or wealth and status, at least some of the time.
And this focus on individual happiness soon led to other transformations,
	such as easing restrictions on divorce and more people marrying at a later age.
So, as we continue to debate the role and definition of marriage in the modern world,
	it might help to keep in mind that marriage has always been shaped by society,
		and as a society's structure, values and goals change over time,
			its ideas of marriage will continue to change along with them.
#+end_verse
** expression
inspirational: providing encouragement or new ideas for what you should do 给予灵感的
hilariously: extremely funny
cynical: 愤世嫉俗的
timeless: literary continuing for ever
humanity: people in general
sedentary: technical a sedentary group of people tend always to live in the splace
agricultural: the practice or science of farming
simultaneous: things that are simultaneous happen at exactly the stime
institution: an important system of organization in society that has existed for a long time
adultery: sex between someone who is married and someone who is not their wife or husband
demographic: 人口统计学的
ruler: someone such as a king or queen who has official power over a country or area
elite: a group of people who have a lot of power and influence because they have money, knowledge, or special skills
concubines: a woman in the past who lived with and had sex with a man who already had a wife or wives, but who was socially less important than the wives 妾
commoner: 平民
monogamy: 一夫一妻制
arrangement: 安排
prayer: words that you say when praying to God or gods
explicitly: expressed in a way that is very clear and direct ⇨ implicit
Adelphopoiesis: 兄弟结义
chapel: the religious services held in a chapel
deceased: the deceased someone who has died, especially recently
conducte: to carry out a particular activity or process, especially in order to get information or prove facts 出现
lineage: 血统 
appease: make someone less angry or stop them from attacking you by giving them what they want安抚
restless: 不安宁的
young: 尚早的
practicality: 实用性
upperclass: 上层社会
industrialization: when a country or place develops a lot of industry
urbanization: 都市化
household: 家庭
pursuit: when someone tries to get, achieve, or find something in a determined way ⇨ pursue
Pair bonding: 配对
----------------------------------------
what sb.(pl) have in common is that + ...: 
vary greatly between sth.(pl): 在事物中有很大的不同
take a quick look at sth.: express that you quickly glanced at something
With the rise of sth.: 随着...的兴起
be a way of doing sth.: 某事是做某事的一种方法
secure rights to sth.: 保护有某物的权力
under certain circumstances: 在某些特殊环境下
designate A. as B.: 把A指派为B
a matter between sth.(pl): 关于某事的事情
be governed by: 受……支配/统治
punishments for sth.: 对某事的惩罚
the legal status of sb.: 某人的法律地位/身份
be born to sb.: 为某人所生
a quarter of sth.: 四分之一
the link between sth.(pl): 某事的联系
in practice: 实际上
the tables were turned: 形势逆转了
have relationships with sb.: 与某人有关系
in public ceremonies: 在公共仪式上
at stake: 利害攸关
became independent from sb./sth.: 独立于
be encouraged by: 被...鼓励
focus on A rather than B: 聚集于A而不是B
ease restrictions on sth.: 放松对某事的限制
be shaped by sth.: 受...影响
** sentences
what sb.(pl) have in common is that + ...: 
- What atoms have in common is that their qualities are concentrated in their nuclei.
- What those people have in common is that they arrived at the station to meet the pop singer.
- What we have in common is that Miumiu is bonded to us.
vary greatly between sth.(pl): 在事物中有很大的不同
- Those days, marriage varies greatly between different areas in China.
- Decades before, languages in China varied greatly between its towns.
- Needless to say, vampires vary geatly between different cultures around the world.
take a quick look at sth.: express that you quickly glanced at something
- Let's take a quick look at the corporation for which I used to work.
- These students have taken a quick look at the island surrendered to Russia in 1919.
- He takes a quick look at the story to reconstruct how the heroine led a happy life.
With the rise of sth.: 随着...的兴起
- With the rise of losing weight, this special kind of food became popular with young people. 
- With the rise of global warmming, the population of penguins is in rapid free fall.
- With the rise of fancy dress party, she has been fanatical about marking up.
be a way of doing sth.: 某事是做某事的一种方法
- Metro is also a way of going to working in Beijing.
- Before the agreement was reached about salaries of these busmen,
		bus would not be a way of transport.
- My teacher pointed out that reading a lot of books is also a way of studying English.
secure rights to sth.: 保护有某物的权力
- I was always having difficulty in securing rights to my toys in my youth.
- If you followed in your father's footstep, you would secure rights to the island.
- The China Ambassador declared that China has secured rights to these islands since 1900.
under certain circumstances: 在某些特殊环境下
- The population of humanity will be in rapid free fall under certain circumstances.
- You was able to mobilize the immune system under certain circumstances.
- The portals embedded into the wall will open automatically under certain circumstances.
designate A. as B.: 把A指派为B
- She must have been designated as the new ambassador in Russia.
- She can't have been designated as the new ambassador in Russia.
- She may have been designated as the new ambassador in Russia.
a matter between sth.(pl): 关于某事的事情
- It's just a matter between you and me.
- It is only within the last century
		that marrage is depicted as a matter between love and companion.
- She refused to help me and said that it's only a matter between her mother and me.
be governed by: 受……支配/统治
- Whta is most remarable about ancient Greek is that everyone was governed by laws. 
- Governed by the authorities, these poor people couldn't perpetuate their existence.
- People in China used to be governed by these businessmen from America.
punishments for sth.: 对某事的惩罚
- The boy flied apart and it's the punishment for his carelessness.
- He doesn't bond with her daughter any more, which is the punishment for his divorce.
- These workers lost their heart trapped in the coal mine,
		which must have been the punishment for their carelessness.
the legal status of sb.: 某人的法律地位/身份
- He managed to write an article about the legal status of commoners in this countries.
- We must verify the legal status of those guies who claimed that they were police.
- You needn't have verified the legal status of us.
be born to sb.: 为某人所生
- These children born to slaves shouldn't secure the right to the lands.
- The child born to my first wife at last follows in my footsteps.
- The first child born to me will secure the right to the country.
a quarter of sth.: 四分之一
- A quarter of your lymph nodes may have been destoried.
- A quarter of the course have already been complete.
- A quarter of his scabs have been wiped away by this doctor.
the link between sth.(pl): 某事的联系
- The link between healthy and sleep means that we must sleep at least 7 hours a day.
- The link between healthy and smoking means that I must give up smoking right now.
- The link between healthy and sports means that I need to exercise every day.
in practice: 实际上
- The chance of hiting the surface of the desk approaches zero in practice.
- I can't speak to a native English speaker in China in practice.
- These parts can't be pieced together in practice.
the tables were turned: 形势逆转了
- He used to quarrel bitterly with his wife, the tables were turned.
- The tables may have already been turned.
- I bet the tables were turned.
have relationships with sb.: 与某人有关系
- You shouldn't have relationships with two men at the same time.
- She had relationships with the man who commited a murder.
- She is eager to have relationships with the guy who works for Apple.
in public ceremonies: 在公共仪式上
- Speaking in public ceremonies, I quaked in every limb and in my soul
- I focused on dresses in public ceremonies rather than those pretty girls.
- The vicar assembled those parts into a well-organized machine in public ceremonies.
at stake: 利害攸关
- We must pay attention to those facts at stake.
- Marriage is bonded to the wealths of their families at stake.
- Those people at stake will be bunched up together at the meeting.
became independent from sb./sth.: 独立于
- With the team flying apart, those players became independent from this club.
- It doesn't help anyone, since you became independent from our family.
- As you still receive money from your mother, you don't become independent from your family.
be encouraged by: 被...鼓励
- The worker was encouraged by his boss to undertake the task in harsher working conditions.
- Encouraged by his wife, the baker managed to set up a factory.
- While he decided to give up, he was encouraged by those assembly instructions.
focus on A rather than B: 聚集于A而不是B
- We focused on the lymph nodes rather than thse scabs.
- He focused on those pretty girls rather than money.
- I focused on these antique shops rather than those street signs.
ease restrictions on sth.: 放松对某事的限制
- It became an accepted fact that the authorities eased restrictions on sex before marriage.
- After easing restrictions on his watching TV, I went to work.
- While easing restrictions on vaccination,
		the authorities established a law prohibiting same-sex marriges.
be shaped by sth.: 受...影响
- The statue must have been shaped by the wind and rain.
- The statue must be shaped by the wind and rain.
- The statue may be shaped by the wind and rain.
