#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-05-05 The science of attraction
#+begin_verse
We like to think of romantic feelings as spontaneous and indescribable things
	that come from the heart.
But it's actually your brain running a complex series of calculations within a matter of seconds
	that's responsible for determining attraction.
Doesn't sound quite as poetic, does it?
But just because the calculations are happening in your brain
	doesn't mean those warm, fuzzy feelings are all in your head.
	
In fact, all five of your senses play a role, each able to vote for, or veto, a budding attraction.
The eyes are the first components in attraction.
Many visual beauty standards vary between cultures and eras,
	and signs of youth, fertility and good health,
			such as long lustrous hair, or smooth, scar-free skin,
		are almost always in demand
	because they're associated with reproductive fitness.
And when the eyes spot something they like,
	our instinct is to move closer so the other senses can investigate.
	
The nose's contribution to romance is more than noticing perfume or cologne.
It's able to pick up on natural chemical signals known as pheromones.
These not only convey important physical or genetic information about their source
	but are able to activate a physiological or behavioral response in the recipient.
In one study, a group of women at different points in their ovulation cycles
	wore the same T-shirts for three nights.
After male volunteers were randomly assigned to smell either one of the worn shirts,
		or a new unworn one,
	saliva samples showed an increase in testosterone in those
		who had smelled a shirt worn by an ovulating woman.
Such a testosterone boost may give a man the nudge to pursue a woman
	he might not have otherwise noticed.
A woman's nose is particularly attuned to MHC molecules, which are used to fight disease.
In this case, opposites attract.
When a study asked women to smell T-shirts that had been worn by different men,
	they preferred the odors of those whose MHC molecules differed from theirs.
This makes sense.
Genes that result in a greater variety of immunities may give offspring a major survival advantage.

Our ears also determine attraction.
Men prefer females with high-pitched, breathy voices, and wide formant spacing,
	correlated with smaller body size.
While women prefer low-pitched voices with a narrow formant spacing
	that suggest a larger body size.
	
And not surprisingly, touch turns out to be crucial for romance.
In this experiment, not realizing the study had begun,
	participants were asked to briefly hold the coffee, either hot or iced.
Later, the participants read a story about a hypothetical person,
	and were asked to rate their personality.
Those who had held the hot cup of coffee
	perceived the person in the story as happier, more social, more generous and better-natured
		than those who had held the cup of iced coffee,
			who rated the person as cold, stoic, and unaffectionate.
			
If a potential mate has managed to pass all these tests, there's still one more:
	the infamous first kiss, a rich and complex exchange of tactile and chemical cues,
		such as the smell of one's breath, and the taste of their mouth.
This magical moment is so critical
		that a majority of men and women have reported losing their attraction to someone
	after a bad first kiss.
Once attraction is confirmed,
	your bloodstream is flooded with norepinephrine,
	activating your fight or flight system.
Your heart beats faster, your pupils dilate, and your body releases glucose for additional energy,
	not because you're in danger
	but because your body is telling you that something important is happening.
To help you focus, norepinephrine creates a sort of tunnel vision,
	blocking out surrounding distractions,
	possibly even warping your sense of time, and enhancing your memory.
This might explain why people never forget their first kiss.

The idea of so much of our attraction being influenced by chemicals and evolutionary biology
		may seem cold and scientific rather than romantic,
	but the next time you see someone you like,
		try to appreciate how your entire body is playing matchmaker to decide
			if that beautiful stranger is right for you.
#+end_verse
** expression
indescribable [ˌɪndɪˈskraɪbəb(ə)l]: adj. it is too difficult to describe难以形容的
poetic [poʊˈetɪk]: adj. relating to poetry, or typical of poetry诗歌的
fuzzy [ˈfʌzi]: adj. unclear or confused OPP clear模糊的
veto [ˈvitoʊ]: v. to refuse to accept a particular plan or suggestion否决
budding [ˈbʌdɪŋ]: adj. beginning to develop萌芽的
component [kəmˈpoʊnənt]: n. one of several parts that together make up a whole machine, system etc SYN constituent成分
fertility [fɜrˈtɪləti]: n. the ability of the land or soil to produce good crops肥沃
lustrous [ˈlʌstrəs]: adj. shining in a soft gentle way有光泽的, 光辉的
reproductive [ˌriprəˈdʌktɪv]: adj. relating to the process of producing babies, young animals, or plants生殖的
fitness [ˈfɪtnəs]: n. when you are healthy and strong enough to do hard work or play sports健壮
cologne [kəˈloʊn]: n. liquid that smells slightly of flowers or plants, that you put on your neck or wrists ⇨ perfume古龙水
pheromones [ˈferəˌmoʊn]: n. a chemical that is produced by people’s and animals’ bodies and is thought to influence the behaviour of other people or animals信息素
physiological [ˌfɪziəˈlɑdʒɪk(ə)l]: adj. the science that studies the way in which the bodies of living things work生理学的
recipient [rɪˈsɪpiənt]: n. someone who receives something接受者
saliva [səˈlaɪvə]: n. the liquid that is produced naturally in your mouth SYN spit口水
testosterone [teˈstɑstəˌroʊn]: n. the ↑hormone in males that gives them their male qualities睾丸激素
odor [ˈoʊdər]: n. a smell, especially an unpleasant one气味
breathy [ˈbreθi]: adj. if someone’s voice is breathy, you can hear their breath when they speak带呼吸声的
formant ['fɔrmənt] spacing: 共振峰间距
hypothetical [ˌhaɪpəˈθetɪk(ə)l]: adj. based on a situation that is not real, but that might happen假设的
unaffectionate: adj. 没有感情的
infamous [ˈɪnfəməs]: adj. well known for being bad or evil声名狼籍的
tactile [ˈtækt(ə)l]: adj. relating to your sense of touch触觉的
cue [kju]: n. an action or event that is a signal for something else to happen暗示
norepinephrine [ˌnɔrɛpə'nɛfrɪn]: n. 去甲肾上腺素
tunnel [ˈtʌn(ə)l] vision: 视野狭隘(引申义:封闭思想)
bloodstream [ˈblʌdˌstrim]: n. the blood flowing in your body血流
dilate [daɪˈleɪt]: v. if a hollow part of your body dilates or if something dilates it, it becomes wider扩大
glucose [ˈɡluˌkoʊz]: n. a natural form of sugar that exists in fruit葡萄糖
warp [wɔrp]: v. if something warps, or if heat or cold warps it, it becomes bent or twisted, and loses its original shape扭曲
----------------------------------------
think of A. as B.: 认为A是B
perceive A. as B.: 把A当作B
run a (complex) series of calculations: 进行一系列(复杂)的运算
within a matter of seconds: 在几秒钟之内
sounds quite as adj.: 听起来很像
Just because +... doesn't mean + ...:  仅仅因为 +...并不意味着 +...
all num. of sth.: 某物的全部几个
play a role in doing sth./sth.: 在某事上起作用
be in demand: 是需要的
pick up on sth.: 注意到某事
In one study: 在一项研究中
in sb's ovulation cycle: 在某人的排卵周期内
be randomly assigned to do sth.: 被随机派遣做某事
give sb. the nudge to do sth.: 给某人动力去做某事
be particularly attuned to sth.: 对某事非常熟悉 be familiar with
differ from sth.: 不同于某事某物
result in sth.(death/failure/contradiction): 导致某事
be correlated with sth.: 和某事相关
rate sb's personality: 评价某人的性格
lose sb's attraction to sb.: 丢失对某人的吸引力
be flooded with sth.: 被某事淹没
activate (sb's fight/flight/immune) system: 激活...系统
+..., not because +...,but because + ...: ...,不是因为..., 而是因为...
block out sth.: 遮挡
enhance sb's memory: 增强某人的记忆力
This might explain why + ...: 这可能解释了为什么
play matchmaker: 做媒
** sentences
think of A. as B.: 认为A是B
- I regret thinking of these as the normal symptoms of the lack of sleep.
- I used to think of it as a stake.
- These local villagers made mistakes and thought of the corpse as a vampire.
perceive A. as B.: 把A当作B
- This local villagers perceived the poor butcher as a thief who stole money last night.
- This vicar perceived the figure as the local butcher.
- My nephew always perceives the pocket money I give him as something
	 exchanged for a piece of chocolate.
run a (complex) series of calculations: 进行一系列(复杂)的运算
- This computer is able to run a complex series of calculations in a second.
- He is said to run a series of calculations in a minute. 
- This computer broke down so that it can't run a complex series of calculations in a second.
within a matter of seconds: 在几秒钟之内
- The fire brigade put out the fire within a matter of seconds.
- Believe it or not, he fixed the bug within a matter of seconds.
- These guys who took part in a game stuck together within a matter of seconds.
sounds quite as adj.: 听起来很像
- It doesn't sound quite as difficult.
- It doesn't sound quite as great.
- It doesn't sound quite as romantic.
Just because +... doesn't mean + ...:  仅仅因为 +...并不意味着 +...
- Just because I love you doesn't mean I don't hate you anymore.
- Just because China surrendered the island to England doesn't mean they failed.
- Just because it approached zero doesn't mean it hit zero.
all num. of sth.: 某物的全部几个
- All 5 of the pop singers will be arriving at the station.
- All 5 of the engineers will be working hard on the scene.
- All 5 of the firefighters will be rescuing these kids in the flood.
play a role in doing sth./sth.: 在某事上起作用
- She played a role in combining her brother with her friend.
- Journalists play a role in bombarding people with medical studies.
- Studies have shown that taking vitamins every day plays a role in your health.
be in demand: 是需要的
- The food was in demand during this earthquake.
- This special type of herb ingredient is in demand in China.
- A piece of paper is always in demand when I am giving a speech in public.
pick up on sth.: 注意到某事
- The pianist who pretended to be blind picked up on the corpse behind the soft.
- I picked up on my salary is worse than his last week.
- The boy who picked up on a mosquito was trying to swat it away.
In one study: 在一项研究中
- In one study, this herb ingredient proved to be bad for your health.
- In one study, husbands were 50% sure of cheating on their wives when meeting a chance.
- In one study, all statistics agreed with the model which the professor developed.
in sb's ovulation cycle: 在某人的排卵周期内
- My wife claimed that she was in her ovulation cycle.
- My wife tends to get angry in her ovulation cycle.
- There is some small, but non-zero, probability that she is in her ovulation cycle.
be randomly assigned to do sth.: 被随机派遣做某事
- They are randomly assigned to interact with a girl.
- They have been assigned to build the bridge in their youth.
- These soldiers were assigned to plant bombs in action.
give sb. the nudge to do sth.: 给某人动力去做某事
- In the cinema, Her signals gave me the nudge to pursue her.
- I suspected that your behavior gave him the nudge to take the test.
- His encouragement must have given me the nudge to go to university.
be particularly attuned to sth.: 对某事非常熟悉 be familiar with
- In the process, I was attuned to the model he developed for an atom.
- I was particularly attuned to wolves in the face of many in the prairie.
- I am attuned to the museum built from iron and glass.
differ from sth.: 不同于某事某物
- The boy I dated yesterday must differ from my classmate in high school.
- The boy may differ from your ex-boyfriend in high school.
- The company which I am working for differs from the last one.
result in sth.(death/failure/contradiction): 导致某事
- The mistakes you made resulted in the failure of our team.
- These monks must have resulted in the spread of smallpox in China.
- Being exposed to poison air resulted in his cancer.
be correlated with sth.: 和某事相关
- The movie star, Bingbing Fan, is said to be correlated with the craze.
- The pustule may be correlated with smallpox.
- Beheading was always correlated with some brutal executions in ancient China.
rate sb's personality: 评价某人的性格
- I don't like to rate my colleague's personality.
- It's impolite to rate your wife's personality in public.
- He explained why he rated her personality.
lose sb's attraction to sb.: 丢失对某人的吸引力
- Cats never lose their attraction to human beings.
- He refused to stay with her after she lost her attraction to him.
- His daughter doesn't obey the rules which lose their attraction to her.
be flooded with sth.: 被某事淹没
- The street is being flooded with cats and dogs in the exhibition. 
- The village will be flooded with corpses in the flood next week.
- Arriving on the scene, he was flooded with rubbish in the house.
activate (sb's fight/flight/immune) system: 激活...系统
- For a very short period of time, it succeeded in activating its protection system.
- After being infected with smallpox, he succeeded in activating his immune system.
- When I realized that my phone had been stolen, I activated its protection system.
+..., not because +...,but because + ...: ...,不是因为..., 而是因为...
- I kissed you, not because I love you, but because it's fun.
- He developed a serious cold, not because he hasn't worn enough clothes,
		but because he has played with snow.
- He died from a car accident, not because he drove carelessly,
		but because it was bad weather.
block out sth.: 遮挡
- I blocked out the torchlight when they were laughing at me.
- I really want to remove these clothes, which block out sunlight.  
- It begins all the way back when he blocked out sunlight in front of her.
enhance sb's memory: 增强某人的记忆力
- Taking vitamins may enhance your memory.
- He developed a model for the material to enhance his memory.
- The pain I suffered from may have enhanced my memory.
This might explain why + ...: 这可能解释了为什么
- This might explain why this law became prohibited.
- This might explain why he continued to dig up corpses.
- This might explain why people conquered the deadly smallpox.
play matchmaker: 做媒
- You must avoid playing matchmaker for your single boss.
- I was wondering if you are playing matchmaker for us.
- Would you mind my playing matchmaker for your sister and my brother?
