#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-05-15 How the heart actually pumps blood
#+begin_verse
For most of history, humans had no idea what purpose the heart served.
In fact, the organ so confused Leonardo da Vinci, that he gave up studying it.
Although everyone could feel their own heart beating,
	it wasn't always clear what each thump was achieving.
	
Now we know that the heart pumps blood.
But that fact wasn't always obvious,
	because if a heart was exposed or taken out, the body would perish quickly.
It's also impossible to see through the blood vessels,
	and even if that were possible,
		the blood itself is opaque, making it difficult to see the heart valves working.
Even in the 21st century, only a few people in surgery teams have actually seen a working heart.
Internet searches for heart function, point to crude models, diagrams or animations
	that don't really show how it works.
It's as if there has been a centuries old conspiracy amongst teachers and students
	to accept that heart function cannot be demonstrated.
Meaning that the next best thing is simply to cut it open and label the parts.
That way students might not fully grasp the way it works, but can superficially understand it,
	learning such concepts as the heart is a four-chambered organ,
		or potentially misleading statements like, mammals have a dual-circulation:
			one with blood going to the lungs and back, and another to the body and back.
			
In reality, mammals have a figure-eight circulation.
Blood goes from one heart pump to the lungs,
	back to the second heart pump, which sends it to the body, and then back to the first pump.
That's an important difference because it marks two completely different morphologies.
This confusion makes many students wary of the heart in biology lessons,
	thinking it signals an intimidating subject full of complicated names and diagrams.
Only those who end up studying medicine completely understand how it all actually works.
That's when its functions become apparent
	as medics get to observe the motion of the heart's valves.

So, let's imagine you're a medic for a day.
What you'll need to get started is a whole fresh heart, like one from a sheep or pig.
Immerse this heart in water and you'll see that it doesn't pump when squeezed by hand.
That's because water doesn't enter the heart clearly enough for the pumping mechanism to work.
We can solve this problem in an extraordinarily simple way.
Simply identify the two atria and cut them off, trimming them down to the tops of the ventricles.
This makes the heart look less complicated because the atria have several incoming veins attached.
So without them there,
	the only vessels remaining are the two major heart arteries:
		the aorta and pulmonary artery, which rise like white columns from between the ventricles.
It looks -- and really is -- very simple.
If you run water into the right ventricle from a tap (the left also works, but less spectacularly),
	you'll see that the ventricular valve tries to close against the incoming stream.
And then ventricle inflates with water.
Squeeze the ventricle and a stream of water squirts out of the pulmonary artery.
The ventricular valves,
		called the tricuspid in the right ventricle and the mitral in the left,
	can be seen through the clear water opening and closing like parachutes
		as the ventricle is rhythmically squeezed.
This flow of water mimics the flow of blood in life.
The valves are completely efficient.
You'll notice they don't leak at all when the ventricles are squeezed.
Over time, they also close against each other with very little wear and tear,
	which explains how this mechanism continues to work seamlessly for more than 2 billion beats
		a heart gives in its lifetime.
		
Now, anyone studying the heart can hold one in their hands,
	make it pump for real and watch the action unfold.
So place your hand above your own and feel its rhymic beat.
Understanding how this dependable inner pump works gives new resonance to the feeling you get
	when you run a race, drink too much caffeine or catch the eye of the one you love.
#+end_verse
** expression
serve [sɜrv]: v. to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应
thump [θʌmp]: v. if your heart thumps, it beats very strongly and quickly because you are frightened or excited砰然地响
pump [pʌmp]: v. to make liquid or gas move in a particular direction, using a pump泵
perish [ˈperɪʃ]: v. formal or literary to die, especially in a terrible or sudden way毁灭,死亡
opaque [oʊˈpeɪk]: adj. opaque glass or liquid is difficult to see through and often thick不透明的
crude [krud]: adj. not exact or without any detail, but generally correct and useful ⇨ approximate粗糙的
demonstrate [ˈdemənˌstreɪt]: v. to show or describe how to do something or how something works示范
label [ˈleɪb(ə)l]: v. to use a word or phrase to describe someone or something, but often unfairly or incorrectly贴标签于
grasp [ɡræsp]: v. to completely understand a fact or an idea, especially a complicated one抓住, 抓紧, 掌握, 领会
four-chambered [fɔr]['tʃeɪmbəd]: adj. an enclosed space, especially in your body or inside a machine四室的
potentially [pəˈtenʃəli]: adv. something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
mammal [ˈmæm(ə)l]: adj. a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals.哺乳动物
dual-circulation [ˈduəlˌsɜrkjəˈleɪʃ(ə)n]: n. the movement of blood around your body双循环
morphology [mɔrˈfɑlədʒi]: n. the structure of an object or system or the way it was formed形态学
signal [ˈsɪɡnəl]: v. to make a sound or an action in order to give information or tell someone to do something发信号
intimidate [ɪnˈtɪmɪˌdeɪt]: v. making you feel worried and not confident胁迫
complicated [ˈkɑmplɪˌkeɪtəd]: adj. difficult to understand or deal with, because many parts or details are involved SYN complex复杂的
medic [ˈmedɪk]: n. British English informal a medical student实习医生
motion [ˈmoʊʃ(ə)n]: n. the process of moving or the way that someone or something moves运动
immerse [ɪˈmɜrs]: v. to put someone or something deep into a liquid so that they are completely covered沉浸
squeeze [skwiz]: v. to press something firmly together with your fingers or hand压榨
mechanism [ˈmekəˌnɪzəm]: n. part of a machine or a set of parts that does a particular job机械装置
atria [ˈeɪtriəm]: n. 心房
vein [veɪn]: n. one of the tubes which carries blood to your heart from other parts of your body ⇨ artery静脉
remaining [rɪˈmeɪnɪŋ]: n. the remaining people or things are those that are left when the others have gone, been used, or been dealt with剩余
artery [ˈɑrtəri]: n. one of the tubes that carries blood from your heart to the rest of your body ⇨ vein动脉
aorta [eɪˈɔrtə]: n. the largest ↑artery that takes blood away from your heart大动脉
superficial [ˌsupərˈfɪʃ(ə)l]/superficially: adj.adv. not studying or looking at something carefully and only seeing the most noticeable things浅薄的
pulmonary [ˈpʌlməˌneri]: adj. relating to the lungs, or having an effect on the lungs肺部的
column [ˈkɑləm]: n. a tall solid upright stone post used to support a building or as a decoration圆柱
tap [tæp]: n. a piece of equipment for controlling the flow of water, gas etc from a pipe or container水龙头
spectacular [spekˈtækjələr]/spectacularly: adj.adv. very impressive壮观的
tricuspid [traɪ'kʌspɪd]: n. (心脏的)三尖瓣
mitral ['maɪtrəl]: n. (心脏的)二尖瓣
parachute [ˈperəˌʃut]: n. a piece of equipment fastened to the back of people who jump out of planes, which makes them fall slowly and safely to the ground降落伞
leak [lik]: v. if a container, pipe, roof etc leaks, or if it leaks gas, liquid etc, there is a small hole or crack in it that lets gas or liquid flow through泄漏
seamless [ˈsimləs] seamlessly: adj.adv. done or made so smoothly that you cannot tell where one thing stops and another begins无缝合的
unfold [ʌnˈfoʊld]: v. if you unfold something that was folded, or if it unfolds, it opens out显露
rhythmical [ˈrɪðmɪk(ə)l]: adj. having a strong rhythm节奏的
dependable [dɪˈpendəb(ə)l]: adj. able to be trusted to do what you need or expect可靠的
caffeine [ˈkæˌfin]: n. a substance in tea, coffee, and some other drinks that makes you feel more active ⇨ decaffeinated咖啡因
blood vessels [ˈves(ə)l]: technical a ↑vein in your body血管
heart valves [vælv]: a part of a tube or pipe that opens and shuts like a door to control the flow of liquid, gas, air etc passing through it心脏阀
ventricle [ˈventrɪk(ə)l] / ventricular: n.adj. one of the two spaces in the bottom of your heart through which blood pumps out to your body ⇨ auricle心室的
----------------------------------------
For most of history: 在历史大部分时间里
have no idea + ...: 不知道...
feel sb's heart beating: 感受某人的心跳
in surgery teams: 在外科医生团队
point to sth.: 指向指出某物
It's as if + ...: 似乎
Meaning that + ...: 意味着...
the next best thing is to do sth.: 下一个最好的办法是做某事
cut it open: 切开
in reality: 实际上
goes from sp.A to sp.B, back to sp.C: 从A出发到B,再回到C
make sb. wary of sth.: 使得某人提防某事
end up doing sth.: 最终做某事
That's when + ...A + as + ...B: 这是当B发生时A发生的时候.
What you (will) need to get started is sth.: 你需要开始的事是某事
do A. enough for sb. to do B.: 做A足够让某人去做某事
trim sth. down (to sp.): 删减某物到...
rise from sth.: 起源于...
run water into sp.: 把水流进...
close against sth.: 对某物关闭
inflate with sth.: 用某物膨胀
squirt out of sth.: 从某物喷出
with very little wear and tear: 非常少的磨损
give new resonance to sth.: 使...产生新的共鸣
run a race: 参与田径比赛
catch the eye of sb.: 引起某人的注目
** sentences
For most of history: 在历史大部分时间里
- For most of history, marriage was not just a matter between individuals.
- For most of history, China hasn't had relationships with Western countries.
- For most of history, the practice had been prohibited.
have no idea + ...: 不知道...
- I have no idea the tables were turned.
- I have no idea whether he gets a good salary.
- I had no idea that he designated his son as his heir.
feel sb's heart beating: 感受某人的心跳
- Feeling her heart beating, I fell in love with her.
- It's time to feel my wife's heart beating.
- Imagine feeling your lover's heart beating in a public ceremony.
in surgery teams/ the surgery team: 在外科医生团队
- The doctor in surgery teams inspired awe in audiences in the basketball game.
- The doctor in the surgery team forgot about his anniversary of marriage,
		which upset his wife a great deal.
- The doctor in the surgery teams pointed out that the patient was infected with smallpox.
point to sth.: 指向指出某物
- Mr. Leo has already pointed to the mistakes which you made yesterday.
- I pointed to the worker who works for Apple.
- You needn't have pointed to answers directly.
It's as if + ...: 似乎
- It's as if she hopes I stay at the company.
- It's as if she is asking for a salary increase. 
- It's as if the diamond will precipitate out of these waters.
Meaning that + ...: 意味着...
- Meaning that the wind has eroded away the body for a long time.
- Meaning that the bone got saturated with a special type of mixture.
- Meaning that the fruits are decaying away.
the next best thing is to do sth.: 下一个最好的办法是做某事
- The next best thing is to have a drink and to do nothing at all.
- The next best thing is to extract silver from these waters.
- The next best thing is to whack away the wall of your bedroom.
cut it open: 切开
- You should have cut the watermelon open.
- Fingers crossed you will cut the box open with your knife.
- We'll cut the bread open in a creek bank.
in reality: 实际上
- In reality, the car has already been slowed down.
- In reality, the body hasn't turned into a fossil yet.
- In reality, he is in the Hall of LoL Fame.
goes from sp.A to sp.B, and back to sp.C: 从A出发到B,再回到C
- We will go from Hangzhou to London, and back to Beijing.
- With the rise of middle classes in the city,
		many young people go from Hangzhou to London, and back to Beijing.
- You're going to go from the bedroom to the living room, back to the kitchen in the ceremony.
make sb. wary of sth.: 使得某人提防某事
- My wife made me wary of my manager who didn't treat me well.
- You made me wary of the butcher who was said to steal in his youth.
- She made me wary of being fired.
end up doing sth.: 最终做某事
- He ends up researching fossils in a famous museum.
- I wanted to end up working for an IT company.
- She ended up completing her course. 
That's when + ...A + as + ...B: 这是当B发生时A发生的时候.
- That's when I bought some oranges as I met her at the station.
- That's when I fell in love with her as I met her for the first time.
- That's when I was in obscurity as I worked for a small factory.
What you (will) need to get started is sth.: 你需要开始的事是某事
- What you need to get started is the book, Critical Thinking 13rd.
- What you need to get started is to cut the watermelon open in the creek bank.
- What you need to get started is the meeting which will be held next week.
do A. enough for sb. to do B.: 做A足够让某人去做B
- I cleaned up the desktop enough for my son to do homework.
- We must stick together enough for our team to undertake the task. 
- She performed experiments enough for us to develop a model for an atom.
trim sth. down (to sp.): 删减某物到...
- The movie should have been trimmed down.
- The director trimmed the movie down a great deal behaving like a passer-by.
- There's a certain probability of trimming the tree down to its root.
rise from sth.: 起源于...
- It was said that smallpox rose from having sex with the same sex.
- The virus rising from India is spread through the air.
- The virus rising from India is spread to people around the world. 
run water into sp.: 把水流进...
- In rapid free fall, the water was run into the pipe.
- He ran water into his field.
- There's a certain probability that our cat ran water into his pot.
close against sth.: 对某物关闭
- The museum shouldn't have closed against these tourists on weekends.
- The library governed by the authorities closes against the local inhabitants.
- So to speak, the groceries close against beggars in China.
inflate with sth.: 用某物膨胀
- The sleeping bag should have inflated with the air before we departed.
- The sleeping bag may not have inflated with the air.
- The sleeping bag must inflate with the air.
squirt out of sth.: 从某物喷出
- In free fall, the water squirted out of the bottle.
- It is said that a spirit will squirt out of the bottle if you rub it.
- Given an electric shock his shit squirted out of his asshole. 
with very little wear and tear: 非常少的磨损
- The gas was used up with very little wear and tear.
- He ran out of pocket money with very little wear and tear.
- He performed experiments with very little wear and tear.
give new resonance to sth.: 使...产生新的共鸣
- The movie gave new resonance to the feeling when I sat beside my wife in the cinema.
- Touching her face gave new resonance to my heart beating.
- Feeling her heart beating gives new resonance to my feelings when I talk to her.
run a race: 参与田径比赛
- There will be many more to run a race.
- She tends to run the race in the future.
- My cat tends to run a race after I return home.
catch the eye of sb.: 引起某人的注目
- Woman, you succeeded in catching the eye of me.
- The abduction by green men caught the eye of everyone around the world.
- His high salary caught the eye of her.
