* 2014-05-15 How the heart actually pumps blood

For most of history, humans had no idea what purpose the heart served.
In fact, the organ so confused Leonardo da Vinci, that he gave up studying it.
Although everyone could feel their own heart beating,
	it wasn't always clear what each thump was achieving.
	
Now we know that the heart pumps blood.
But that fact wasn't always obvious,
	because if a heart was exposed or taken out, the body would perish quickly.
It's also impossible to see through the blood vessels,
	and even if that were possible,
		the blood itself is opaque, making it difficult to see the heart valves working.
Even in the 21st century, only a few people in surgery teams have actually seen a working heart.
Internet searches for heart function, point to crude models, diagrams or animations
	that don't really show how it works.
It's as if there has been a centuries old conspiracy amongst teachers and students
	to accept that heart function cannot be demonstrated.
Meaning that the next best thing is simply to cut it open and label the parts.
That way students might not fully grasp the way it works, but can superficially understand it,
	learning such concepts as the heart is a four-chambered organ,
		or potentially misleading statements like, mammals have a dual-circulation:
			one with blood going to the lungs and back, and another to the body and back.
			
In reality, mammals have a figure-eight circulation.
Blood goes from one heart pump to the lungs,
	back to the second heart pump, which sends it to the body, and then back to the first pump.
That's an important difference because it marks two completely different morphologies.
This confusion makes many students wary of the heart in biology lessons,
	thinking it signals an intimidating subject full of complicated names and diagrams.
Only those who end up studying medicine completely understand how it all actually works.
That's when its functions become apparent
	as medics get to observe the motion of the heart's valves.

So, let's imagine you're a medic for a day.
What you'll need to get started is a whole fresh heart, like one from a sheep or pig.
Immerse this heart in water and you'll see that it doesn't pump when squeezed by hand.
That's because water doesn't enter the heart clearly enough for the pumping mechanism to work.
We can solve this problem in an extraordinarily simple way.
Simply identify the two atria and cut them off, trimming them down to the tops of the ventricles.
This makes the heart look less complicated because the atria have several incoming veins attached.
So without them there,
	the only vessels remaining are the two major heart arteries:
		the aorta and pulmonary artery, which rise like white columns from between the ventricles.
It looks -- and really is -- very simple.
If you run water into the right ventricle from a tap (the left also works, but less spectacularly),
	you'll see that the ventricular valve tries to close against the incoming stream.
And then ventricle inflates with water.
Squeeze the ventricle and a stream of water squirts out of the pulmonary artery.
The ventricular valves,
		called the tricuspid in the right ventricle and the mitral in the left,
	can be seen through the clear water opening and closing like parachutes
		as the ventricle is rhythmically squeezed.
This flow of water mimics the flow of blood in life.
The valves are completely efficient.
You'll notice they don't leak at all when the ventricles are squeezed.
Over time, they also close against each other with very little wear and tear,
	which explains how this mechanism continues to work seamlessly for more than 2 billion beats
		a heart gives in its lifetime.
		
Now, anyone studying the heart can hold one in their hands,
	make it pump for real and watch the action unfold.
So place your hand above your own and feel its rhymic beat.
Understanding how this dependable inner pump works gives new resonance to the feeling you get
	when you run a race, drink too much caffeine or catch the eye of the one you love.
** expression
serve: to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应
thump: if your heart thumps, it beats very strongly and quickly because you are frightened or excited砰然地响
pump: to make liquid or gas move in a particular direction, using a pump
perish: formal or literary to die, especially in a terrible or sudden way
opaque: opaque glass or liquid is difficult to see through and often thick不透明的
crude: not exact or without any detail, but generally correct and useful ⇨ approximate
demonstrate: to show or describe how to do something or how something works
label: to use a word or phrase to describe someone or something, but often unfairly or incorrectly
grasp: to completely understand a fact or an idea, especially a complicated one
four-chambered: 四腔的
potentially: something that is potentially dangerous, useful etc is not dangerous etc now, but may become so in the future潜在地
mammal: a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals.
dual-circulation: 双循环
morphology: the structure of an object or system or the way it was formed
signal: to make a sound or an action in order to give information or tell someone to do something
intimidating: making you feel worried and not confident
complicated: difficult to understand or deal with, because many parts or details are involved SYN complex
medic: 实习医生
motion: the process of moving or the way that someone or something moves
immerse: to put someone or something deep into a liquid so that they are completely covered
squeeze: to press something firmly together with your fingers or hand
mechanism: part of a machine or a set of parts that does a particular job
atria: 心房
vein: 静脉
remaining: the remaining people or things are those that are left when the others have gone, been used, or been dealt with
artery: one of the tubes that carries blood from your heart to the rest of your body ⇨ vein动脉
aorta: the largest ↑artery that takes blood away from your heart大动脉
superficial/superficially: not studying or looking at something carefully and only seeing the most noticeable things浅薄的
pulmonary: 肺部的
column: a tall solid upright stone post used to support a building or as a decoration
tap: a piece of equipment for controlling the flow of water, gas etc from a pipe or container水龙头
spectacular/spectacularly: very impressive
tricuspid: (心脏的)三尖瓣
mitral: (心脏的)二尖瓣
parachute: a piece of equipment fastened to the back of people who jump out of planes, which makes them fall slowly and safely to the ground
leak: if a container, pipe, roof etc leaks, or if it leaks gas, liquid etc, there is a small hole or crack in it that lets gas or liquid flow through泄漏
seamlessly: 无缝合的
unfold: if you unfold something that was folded, or if it unfolds, it opens out
rhythmical: having a strong rhythm
dependable: able to be trusted to do what you need or expect可靠的
caffeine: 咖啡因
blood vessels: 血管
heart valves: 心脏瓣膜
ventricle / ventricular: 
----------------------------------------
For most of history: 在历史大部分时间里
have no idea + ...: 不知道...
feel sb's heart beating: 感受某人的心跳
in surgery teams: 在外科医生团队
point to sth.: 指向指出某物
It's as if + ...: 似乎
Meaning that + ...: 意味着...
the next best thing is to do sth.: 下一个最好的办法是做某事
cut it open: 切开
in reality: 实际上
goes from sp.A to sp.B, back to sp.C: 从A出发到B,再回到C
make sb. wary of sth.: 使得某人提防某事
end up doing sth.: 最终做某事
That's when + ...A + as + ...B: 这是当B发生时A发生的时候.
What you (will) need to get started is sth.: 你需要开始的事是某事
do A. enough for sb. to do B.: 做A足够让某人去做某事
trim sth. down (to sp.): 删减某物到...
rise from sth.: 起源于...
run water into sp.: 把水流进...
close against sth.: 对某物关闭
inflate with sth.: 用某物膨胀
squirt out of sth.: 从某物喷出
with very little wear and tear: 非常少的磨损
give new resonance to sth.: 使...产生新的共鸣
run a race: 参与田径比赛
catch the eye of sb.: 引起某人的注目
