#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-12-18 What is a gift economy
#+begin_verse
This holiday season, people around the world will give and receive presents.
You might even get a knitted sweater from an aunt.
But what if instead of saying 'thanks' before consigning it to the closet,
	the polite response expected from you was to show up to her house in a week with a better gift?
Or to vote for her in the town election?
Or let her adopt your firstborn child?

All of these things might not sound so strange if you are involved in a gift economy.
This phrase might seem contradictory.
After all, isn't a gift given for free?
But in a gift economy,
	gifts given without explicit conditions
		are used to foster a system of social ties and obligations.
While the market economies we know are formed by relationships between the things being traded,
	a gift economy consists of the relationships between the people doing the trading.
	
Gift economies have existed throughout human history.
The first studies of the concept came from anthropologists Bronislaw Malinowski and Marcel Mauss
	who describe the natives of the Trobriand islands
		making dangerous canoe journeys across miles of ocean to exchange shell necklaces and arm bands.
The items traded through this process, known as the kula ring,
		have no practical use,
	but derive importance from their original owners and carry an obligation to continue the exchange.
Other gift economies may involve useful items,
	such as the potlatch feast of the Pacific Northwest,
		where chiefs compete for prestige by giving away livestock and blankets.
We might say that instead of accumulating material wealth,
	participants in a gift economy use it to accumulate social wealth.
Though some instances of gift economies may resemble barter,
	the difference is that the original gift is given without any preconditions or haggling.
	
Instead, the social norm of reciprocity obligates recipients to voluntarily return the favor.
But the rules for how and when to do so vary between cultures,
	and the return on a gift can take many forms.
A powerful chief giving livestock to a poor man may not expect goods in return,
	but gains social prestige at the debtor's expense.
And among the Toraja people of Indonesia,
	the status gained from gift ceremonies even determines land ownership.
	
The key is to keep the gift cycle going, with someone always indebted to someone else.
Repaying a gift immediately, or with something of exactly equal value,
	may be read as ending the social relationship.
So, are gift economies exclusive to small-scale societies outside the industrialized world?
Not quite.
For one thing, even in these cultures,
	gift economies function alongside a market system for other exchanges.
And when we think about it, parts of our own societies work in similar ways.
Communal spaces, such as Burning Man, operate as a mix of barter and a gift economy,
	where selling things for money is strictly taboo.
In art and technology,
	gift economies are emerging as an alternative to intellectual property
		where artists, musicians, and open-source developers distribute their creative works,
			not for financial profit,
			but to raise their social profile or establish their community role.
And even potluck dinners and holiday gift traditions
	involve some degree of reciprocity and social norms.
	
We might wonder
	if a gift is truly a gift if it comes with obligations or involves some social pay off.
But this is missing the point.
Our idea of a free gift without social obligations prevails
	only if we already think of everything in market terms.
And in a commericalized world,
	the idea of strengthening bonds through giving and reciprocity
		may not be such a bad thing,
	wherever you may live.
#+end_verse
** expression
knit: to make clothing out of wool, using two ↑knitting needles编织
adopt: to take someone else’s child into your home and legally become its parent
contradictory: two statements, beliefs etc that are contradictory are different and therefore cannot both be true or correct
obligation: a moral or legal duty to do something义务
social ties: 社交关系
canoe: a long light boat that is pointed at both ends and which you move along using a paddle独木舟
potlatch: 冬节
chief: the most important person, or one of the most important people, in a company or organization – used especially in job titles and in news reports首领
livestock: animals such as cows and sheep that are kept on a farm
blanket: a cover for a bed, usually made of wool ⇨ duvet
participant: someone who is taking part in an activity or event
barter: to exchange goods, work, or services for other goods or services rather than for money
haggle: to argue when you are trying to agree about the price of something
norm: generally accepted standards of social behaviour标准, 规范
reciprocity: a situation in which two people, groups, or countries give each other similar kinds of help or special rights
voluntarily: if you do something voluntarily, you do it willingly, without anyone telling you to do it
prestige: the respect and admiration that someone or something gets because of their success or important position in society
communal: shared by a group of people or animals, especially a group who live together公共的
taboo: a taboo subject, word, activity etc is one that people avoid because it is extremely offensive or embarrassing
financial: relating to money or the management of money财政的
profit: money that you gain by selling things or doing business, after your costs have been paid OPP loss 
potluck dinner: 自备餐
prevail: if a belief, custom, situation etc prevails, it exists among a group of people at a certain time
anthropology/anthropologist: the scientific study of people, their societies, cultures etc
native: a person who was born in a particular place
----------------------------------------
This holiday season: 这个假期
consign sth. to the closet: 把某物放入壁橱
expect sth. from sb.: 期待某人某物
be involved in: 涉及到...
for free: adv.免费
without explicit conditions: 没有明显的条件
foster a system of sth.: 培养某事物的体系
be formed by: consist of
throughout human history: 贯穿人类历史
describe sb. doing sth.: 描述某人做某事
make a journey: 进行一次旅行
do sth. through this process: 通过这个过程做某事
carry an obligation to do sth.: 承担做某事的义务
give away sth.: 赠送某物
obligate sb. to do sth.: 迫使某人做某事
return the favor: 回报恩惠
take many forms: 多种形式
at sb's expense: 以某人的费用
gain sth. from sb./sth.: 从某人某物获得某物
be indebted to sb.: 对某人深表感激
be read as doing sth.: be regarded as
be exclusive to sth.: 专属于某物
social pay off: 社会回报
miss the point: 错过重点
** sentences
This holiday season: 这个假期
- This holiday season, the famous player, Faker, has been at the Hall of LoL Fame.
- This holiday season, my nephew made a complete recovery after receiving a long-term treatment.
- This holiday season, I have performed a lot of experiments about monkeys.
consign sth. to the closet: 把某物放入壁橱
- He may have consigned the T-shirt to the closet.
- She behaved as she consigned the cat to the closet.
- The cat consigned to the closet smashed everything into pieces.
expect sth. from sb.: 期待某人某物
- I never expected a letter from a girl of my age who lives abroad.
- The left-behind children in villages are expecting calls from their parents.
- It's not that I expected pocket money from you,
		it's that your daughter expected pocket money from you.
be involved in: 涉及到...
- The man you interacted with yesterday in your house may be involved in theft.
- The chance of her to be involved in murder approaches zero.
- The way to set up a factory must be involved in the local authorities.
for free: adv.免费
- Although the busmen are being on strike, I won't give you a lift for free.
- I have no idea of hitting the surface of the ball for free.
- I will provide you with some ingredient for free,
		for we share the same basic goal: complete the course.
foster a system of sth.: 培养某事物的体系
- In the process, he has fostered a system of studying English.
- The doctors who went through smallpox fostered a system of variolation.
- It begins all the way back when they fostered a system of medicine school.
be formed by: consist of
- Sir, your dinner will be formed by steaks and salads.
- The special band is formed by natives and foreigners.
- The law formed by punishment of thefts and murders became prohibited
		after the chief won the election.
throughout human history: 贯穿人类历史
- Beheading may have existed throughout human history.
- The habit of talking while having meal have existed throughout human history.
- Feasting on icy water in summar has existed throughout human history.
describe sb. doing sth.: 描述某人做某事
- He described his sister discerning the casue of the accident.
- He described her causing her daughter to play truent from school.
- He described the vampire feasting on the life force of the livestock.
make a journey: 进行一次旅行
- Why did you make a journey when your mother was having an operation in the hospital?
- He is performing a ritual that he is making a canoe journey across the lake.
- This holiday season, we loved to make a journey on weekends.
do sth. through this process: 通过这个过程做某事
- You can't fail to be fascinated by cats through this process.
- The American people gained their independence through this process.
- Mr. Leo must have made profits through this process.
carry an obligation to do sth.: 承担做某事的义务
- You can't ask me to carry an obligation to do the work of other colleagues.
- Carring an obligation to lead a happy life, he have completed this course.
- This has an enormous impact on her,
	 so that she carried an obligation to be responsible for the task.
give away sth.: 赠送某物
- My grandfather was alwaying giving away my toys in my youth.
- The toys he gave away belongs to me.
- She tended to give away the toys formed by woods and metal.
obligate sb. to do sth.: 迫使某人做某事
- No one but you can obligate you to work hard.
- The authority may have obligated the enterpreneur to make vehicles.
- The enterpreneur obligated these workers to operate in harsher working conditions.
return the favor: 回报恩惠
- He always receives a lot of gifts in Christmas, but never returns the favor.
- He gave away his livestock to return the favor.
- He give me a pen made in China to return the favor.
take many forms: 多种形式
- The sculptures he made took many forms in this exhibition.
- The mistakes which students made in the test took many forms.
- The way in which you receive an electric shocks will take many forms.
at sb's expense: 以某人的费用
- I never obligate you to give away livestock at my expense.
- You shouldn't have paid for your friends' meal at your parent's expense.
- The scientist is always delivering articles on biology at our academy's expense.
gain sth. from sb./sth.: 从某人某物获得某物
- You can only gain minimum wage from your boss so that you can fire him.
- I gained a lot of cleverness from my colleague in a pinch.
- You will gain a lot of knowledges from my course which you will take part in last week.
be indebted to sb.: 对某人深表感激
- I lent my classmate some money in a pinch so that her is indebted to me.
- I am always indebted to a man who give me a lot of help in emergency.
- You're protecting against a man who is indebted to you.
be read as doing sth.: be regarded as
- The rude behaviors in the cinema are read as complaints about the movie.
- The amount of pocket money you give to your nehpew is read as your love to him.
- The singals are read as the prelude of abortition.
be exclusive to sth.: 专属于某物
- The seat has been exclusive to our company.
- These donkeys may be exclusive to the chief in the tribe.
- The beheadhing is exclusive to the punishment of murder in this country.
social pay off: 社会回报
- You needn't have asked for social pay off.
- Despite of social pay off, he has devoted himself to education.
- Without social pay off, the contributor of the open source community lost his heart.
miss the point: 错过重点
- It's more important than ever not to miss the point at the point.
- The busmen on strike missed the point while reaching an agreement.
- He noticed with dismay that his children had missed the point in the process.
