* 2014-06-03 How to choose your news
#+begin_verse
How do you know what's happening in your world?
The amount of information just a click away may be limitless,
	but the time and energy we have to absorb and evaluate it is not.
All the information in the world won't be very useful unless you know how to read the news.
To your grandparents, parents, or even older siblings, this idea would have sounded strange.
Only a few decades ago, news was broad-based.
Your choices were limited to a couple of general interest magazines and newspaper of record,
	and three or four TV networks
		where trusted newscasters delivered the day's news at the same reliable time every evening.
		
But the problems with this system soon became apparent as mass media spread.
While it was known that authoritarian countries controlled and censored information,
	a series of scandals showed
		that democratic governments were also misleading the public, often with media cooperation.
Revelations of covert wars, secret assassinations, and political corruption
	undermined public faith in official narratives presented by mainstream sources.
This breakdown of trust in media gatekeepers
		lead to alternative newspapers, radio shows, and cable news
	competing with the major outlets and covering events from various perspectives.
More recently, the Internet has multiplied the amount of information and viewpoints,
		with social media, blogs, and online video
	turning every citizen into a potential reporter.
But if everyone is a reporter,
	nobody is,
	and different sources may disagree, not only opinions, but on the facts themselves.
So how do you get the truth, or something close?

One of the best ways is to get the original news unfiltered by middlemen.
Instead of articles interpreting a scientific study or a politician's speech,
	you can often find the actual material and judge for yourself.
For current events, follow reporters on social media.
During major events, such as the Arab Spring or the Ukrainian protests,
	newscasters and bloggers have posted updates and recordings from the midst of the chaos.
Though many of these later appear in articles or broadcasts,
	keep in mind that these polished versions
		often combine the voice of the person who was there with the input of editors who weren't.
			
At the same time, the more chaotic the story, the less you should try to follow it in real time.
In events like terrorist attacks and natural disasters,
	today's media attempts continuous coverage even when no reliable new information is available,
		sometimes leading to incorrect information or false accusations of innocent people.
It's easy to be anxious in such events,
	but try checking for the latest information at several points in the day,
		rather than every few minutes,
	allowing time for complete details to emerge and false reports to be refuted.
While good journalism aims for objectivity, media bias is often unavoidable.
When you can't get the direct story,
	read coverage in multiple outlets
		which employ different reporters and interview different experts.
Tuning in to various sources and noting the differences
	lets you put the pieces together for a more complete picture.
	
It's also crucial to separate fact from opinion.
Words like think, likely, or probably
	mean that the outlet is being careful or, worse, taking a guess.
And watch out for reports that rely on anonymous sources.
These could be people who have little connection to the story,
		or have an interest in influencing coverage,
	their anonymity making them unaccountable for the information they provide.
	
Finally, and most importantly, try to verify news before spreading it.
While social media has enabled the truth to reach us faster,
	it's also allowed rumors to spread before they can be verified
		and falsehoods to survive long after they've been refuted.
So, before you share that unbelievable or outrageous news item,
	do a web search to find any additional information or context you might have missed
		and what others are saying about it.
Today, we are more free than ever from the old media gatekeepers
	who used to control the flow of information.
But with freedom comes responsibility:
	the responsibility to curate our own experience
			and ensure that this flow does not become a flood,
		leaving us less informed than before we took the plunge. 
#+end_verse
** expression
absorb: to read or hear a large amount of new information and understand it吸收
broad-based: 基础深厚的
newspaper of record: 主流报纸
authoritarian: strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
censor: to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
scandal: talk about dishonest or immoral things that famous or important people are believed to have done丑闻
revelation: a surprising fact about someone or something that was previously secret and is now made known揭露
covert: secret or hidden
assassination: the act of murdering an important person
corruption: dishonest, illegal, or immoral behaviour, especially from someone with power贪污
narratives: a description of events in a story, especially in a ↑novel叙述
mainstream: the mainstream the most usual ideas or methods, or the people who have these ideas or methods主流
gatekeeper: someone whose job is to open and close a gate, and to allow or not allow people to go through it
outlet: a pipe or hole through which something such as a liquid or gas can flow out出路
unfiltered: 未滤过的
protest: something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products
blog / blogger: a web page containing information or opinions from a particular person or about a particular subject, to which new information is added regularly SYN web log
polished: polite, confident, and graceful 精练的, 优美的
chaotic: a chaotic situation is one in which everything is happening in a confused way
terrorist: someone who uses violence such as bombing, shooting etc to obtain political demands
coverage: when a subject or event is reported on television or radio, or in newspapers
accusation: a statement saying that someone is guilty of a crime or of doing something wrong
refute: to prove that a statement or idea is not correct SYN rebut
bias: an opinion about whether a person, group, or idea is good or bad that influences how you deal with it偏见
anonymity: when other people do not know who you are or what your name is
rumor: information or a story that is passed from one person to another and which may or may not be true
falsehood: a statement that is untrue SYN lie
outrageous: very shocking and extremely unfair or offensive骇人的
curate: organize
flow: 流动
----------------------------------------
a click away: 用鼠标点击一下
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
compete with sb.: 同某人竞争
from various perspectives: 从各种各样的视角
More recently: 更近期地
multiply the amount of sth.: 倍增某物的数量
sb. keeps in mind that + ...: 某人牢记...
in real time: 实时
at several points in the day: 在一天的几个点
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
aim for sth.: 争取某物
tuning in to sth.: 收听某事
take a guess: 做猜测
watch out for sth.: 小心提防
have little connection to sth./sb.: 和某事/某物没关系
make sb. unaccountable for sth.: 使某人对于某物没有责任
with A. comes B.: 伴随A来的B
ensure that + ...: 确保...
leave sb. less informed than before + ...: 让某人比...之前更加无知
took the plunge: 冒险
** sentences
a click away: 用鼠标点击一下
- 
- 
- 
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
- 
- 
- 
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
- 
- 
- 
compete with sb.: 同某人竞争
- 
- 
- 
from various perspectives: 从各种各样的视角
- 
- 
- 
More recently: 更近期地
- 
- 
- 
multiply the amount of sth.: 倍增某物的数量
- 
- 
- 
sb. keeps in mind that + ...: 某人牢记...
- 
- 
- 
in real time: 实时
- 
- 
- 
at several points in the day: 在一天的几个点
- 
- 
- 
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
- 
- 
- 
aim for sth.: 争取某物
- 
- 
- 
tuning in to sth.: 收听某事
- 
- 
- 
take a guess: 做猜测
- 
- 
- 
watch out for sth.: 小心提防
- 
- 
- 
have little connection to sth./sb.: 和某事/某物没关系
- 
- 
- 
make sb. unaccountable for sth.: 使某人对于某物没有责任
- 
- 
- 
with A. comes B.: 伴随A来的B
- 
- 
- 
ensure that + ...: 确保...
- 
- 
- 
leave sb. less informed than before + ...: 让某人比...之前更加无知
- 
- 
- 
took the plunge: 冒险
- 
- 
- 
