#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-06-02 How people rationalize fraud
#+begin_verse
If you ask people whether they think stealing is wrong, most of them would answer, "Yes."
And yet, in 2013,
	organizations all over the world lost an estimated total of 3.7 trillion dollars to fraud,
		which includes crimes like embezzlement, pyramid schemes, and false insurance claims.
This wasn't just the work of a few bad apples.
The truth is that many people are susceptible
	not only to the temptation to commit fraud
	but to convincing themselves that they've done nothing wrong.
		
So why does fraud happen?
While individual motivations may differ from case to case,
	the fraud triangle, a model developed by criminologist Donald Cressey,
		shows three conditions that make fraud likely: pressure, opportunity, and rationalization.
Pressure is often what motivates someone to engage in fraud to begin with.
It could be a personal debt, an addiction, an earnings quota, a sudden job loss,
	or an illness in the family.
As for opportunity, many people in both public and private sectors have access to tools
	that enable them to commit and conceal fraud:
		corporate credit cards, internal company data, or control over the budget.
The combination of pressure and being exposed to such opportunities on a daily basis
	can create a strong temptation.
	
But even with these two elements, most fraud still requires rationalization.
Many fraudsters are first time offenders,
	so in order to commit an act most would regard as wrong, they need to justify it to themselves.
Some feel entitled to the money
	because they are underpaid and overworked and others believe their fraud is victimless,
		perhaps even planning to return the money once their crisis is resolved.
Some of the most common types of fraud don't even register as such to the perpetrator.
Examples include employees fudging time sheets or expense reports,
	taxpayers failing to report cash earnings,
	or service providers overbilling insurance companies.
Though these may seem small, and can sometimes only involve hundreds of dollars,
	they all contribute to the big picture.
And then there's fraud on a massive scale.

In 2003, Italian dairy food giant Parmalat went bankrupt
	after it was found to have fabricated a 4 billion dollar bank account
			and falsified financial statements
		to hide the fact that its subsidiaries had been losing money.
Because it was family controlled, corporate governance and regulator supervision were difficult,
	and the company likely hoped that the losses could be recouped before anyone found out.
	
And it's not just corporate greed.
Governments and non-profits are also susceptible to fraud.
During her time as City Comptroller for Dixon, Illinois,
	Rita Crundwell embezzled over 53 million dollars.
Rita was one of the country's leading quarter horse breeders and winner of 52 world championships.
But the cost of maintaining the herd ran to 200,000 dollars per month.
Because her position gave her complete control over city finances,
	she was easily able to divert money to an account she used for private expenses,
		and the scheme went unnoticed for 20 years.
It is believed that Crundwell felt entitled to a lavish lifestyle based on her position,
	and the notoriety her winnings brought to the city.
	
It's tempting to think of fraud as a victimless crime
	because corporations and civic institutions aren't people.
But fraud harms real people in virtually every case:
	the employees of Parmalat who lost their jobs,
	the citizens of Dixon whose taxes subsidized horse breeding,
	the customers of companies which raise their prices to offset losses.
Sometimes the effects are obvious and devastating,
	like when Bernie Madoff caused thousands of people to lose their life savings.
But often they're subtle and not easy to untangle.
Yet someone, somewhere is left holding the bill.
#+end_verse
** expression
trillion: the number 1,000,000,000,000万亿
embezzle embezzlement: to steal money from the place where you work盗用, 挪用
insurance: 保险
triangle: a flat shape with three straight sides and three angles三角形
criminologist: 犯罪学者
rationalization: 合理化
addiction: the need to take a harmful drug regularly, without being able to stop沉溺, 上瘾
quota: an official limit on the number or amount of something that is allowed in a particular period限额
budget: the money that is available to an organization or person, or a plan of how it will be spent预算
fraudster: someone who has committed a fraud欺诈者
offenders: someone who is guilty of a crime罪犯
underpaid: earning less money than you deserve for your work所得报酬过低的
overworked: made to work too hard过度工作
victimless: 不侵害他人的
taxpayer: a person that pays tax纳税人
overbill: 超额收费
fabricate: to invent a story, piece of information etc in order to deceive someone捏造
falsify: to change figures, records etc so that they contain false information伪造
subsidiary: a company that is owned or controlled by another larger company子公司
corporate: belonging to or relating to a corporation公司的
governance: the act or process of governing管理
regulator:someone who makes sure that a system operates properly or fairly监督者
supervision: 监督
greed: a strong desire for more food, money, power, possessions etc than you need SYN avarice贪欲, 贪婪
quarter horse: 夸特马
breeder: someone who breeds animals or plants as a job饲者
finance: 金融
subsidize: if a government or organization subsidizes a company, activity etc, it pays part of its costs津贴
untangle: to make something less complicated解开
--------------------
lost [money] to sth.: 因某事损失钱
pyramid schemes: 金字塔骗局
be susceptible to sth.: 易受某事影响
commit fraud: 犯欺诈罪
make sth. likely: 使得某事可能
motivate sb. to do sth.: 激励某人去做某事
a sudden job loss: 突然失业
in the public/private sector: 在公有或私立部门
credit cards: 信用卡
on a daily basis: 每天
justify sth. to sb.: 向某人证明某事有理
feel entitled to sth.: 觉得有资格得到某物
resolve crisis: 解决危机
register as sth. to sb.: 对某人来说是某物
fudge expense reports: 捏造费用报告
report cash earnings: 报告先进收入
recoup losses/ losses be recouped: 弥补损失
divert money to sp.(an account): 把钱转到
go unnoticed: 不为人知的
run to sth.: 到达...
go bankrupt: 破产
to begin with: 在开始时
It is believed that + ...: 人们相信...
raise prices: 提高价格
be left doing sth.: 被留下做某事
** sentence
lost [money] to sth.: 因某事损失钱
- We lost a great deal of money to the experiment you performed last month. 
- My wife is unwilling to lose money to my company anymore.
- The chance of losing money to our new store is increasing exponentially.
pyramid schemes: 金字塔骗局
- Imagine his dismay when he realized this turned out to be a pyramid scheme.
- The police arrived on the scene and told the old lady this must be a pyramid scheme.
- Let's expand on pyramid schemes to make this event clear.
be susceptible to sth.: 易受某事影响
- She failed the exam, not because she was susceptible to video games,
		but because she was not good at swimming.
- I couldn't pay attention to the teacher, not because I was susceptible to birds outside,
		but because I developed a fever.
- This might explain why she was susceptible to the temptation of stealing clothes.
commit fraud: 犯欺诈罪
- It is within only last century that fraud is committed frequently.
- Being composed of finance in the public sector, she can't the temptation to commit fraud.
- These criminals had one thing in common: committed fraud in the public sector.
make sth. likely: 使得某事可能
- Because of the research into the brain, it makes treatment of OCD likely.
- Making digestion likely, these bacteria are vital for your body.
- 'Making a profit is the only approach to make our research likely.' she shouted at me.
motivate sb. to do sth.: 激励某人去做某事
- Mr. Leo always motivates us to read the history book at our own pace.
- My dad used to motivate me to resolve the puzzle by myself. 
- His encouragement motivated me to break the world record.
a sudden job loss: 突然失业
- A sudden job loss attacked my father, which led to a hard life in my youth.
- Before deciding to buy a house, we must deliberate at length over a sudden job loss.
- Despite a sudden job loss, he continued to spend a lot of money studying English.
in the public/private sector: 在公有或私立部门
- It is not likely to get a good salary in the public sector.
- It is more stable to work in the public sector than in the private sector.
- It implies that he has been working in the public sector for ten years.
credit cards: 信用卡
- Why do you keep interacting with my secretary who has access to corporate credit cards?
- In one study, up to 90% of meals are paid for by credit cards in America.
- They urged Rachel to stop using her father's credit cards.
on a daily basis: 每天
- The busmen go on strike on a daily basis this week.
- The vicar expresses his gratitude to the god on a daily basis.
- She is fanatical about the team on a daily basis.
justify sth. to sb.: 向某人证明某事有理
- The criminal failed to justify his behavior to the judge.
- My wife has been justifying the decoration of our room to me for a whole morning.
- He is trying to justify the arrangement of objects in this room to everyone in the party.
feel entitled to sth.: 觉得有资格得到某物
- It is no use pretending that you feel entitled to the job.
- Feeling entitled to the job, she applied for it just then.
- Feeling entitled to entrepreneur, he managed to set up a factory in the suburbs.
resolve crisis: 解决危机
- A series of factories set up in a suburb of the city eventually resolve crises.
- With skills comes a good job, and he gets a good salary to resolve crises.
- Making a profit this month, Mr. Leo managed to resolve crises in his company.
register as sth. to sb.: 对某人来说是某物
- The note registers as an important memory to our family.
- The clavichord registering as our friendship to us was broken down last week.
- This action may register as a criminal to people in China.
fudge expense reports: 捏造费用报告
- The boss kept his secretary fudging expense reports to avoid tax.
- The worker used to fudge expense reports.
- The worker can't resist the temptation to fudge expense reports.
report cash earnings: 报告现金收入
- The grocer failed to refuse to report cash earnings.
- The grocer doesn't report cash earnings so that he doesn't need to pay taxes.
- The grocer was accused of not reporting cash earnings on time.
recoup losses/ losses be recouped: 弥补损失
- So long as injury appears, it is impossible to recoup losses.
- With losses being recouped, she has been assigned to be the official again.
- She was assigned to recoup losses in this crisis.
divert money to sp.(an account): 把钱转到
- The old lady insisted on diverting her money to an unknown account.
- The boss has diverted his money to the account for public expense.
- Although the alarm was given, the old lady proceeded to divert her money to an unknown account.
go unnoticed: 不为人知的
- The fact that she poisoned her three husbands in her youth went unnoticed.
- You don't feel guilty, the fraud will go unnoticed.
- The poet going unnoticed for years published a masterpiece on history in the press.
run to sth.: 到达...
- On the journey, the plane ran to a height of 10,000 miles.
- It is estimated that the plane will run to a height of 10,000 miles.
- The plane running to a height of 10,000 miles was regarded as a great experiment.
go bankrupt: 破产
- The company is not being allowed to go bankrupt by the authorities.
- It is estimated that the company will go bankrupt in this economic crisis.
- After a big forest fire, the local authorities announced that they went bankrupt.
to begin with: 在开始时
- To begin with, she was astonished to find that he had poisoned his ex-wife.
- To begin with, a snake was wound around a length of electric wire.
- To begin with, a stream wound its way across the field.
It is believed that + ...: 人们相信...
- It is believed that these corpses feast on the life force of people.
- It is believed that these creatures sustain themselves by sucking blood.
- It is believed that the brutal executions were being carried out in the empire.
raise prices: 提高价格
- With workers digging up more gold, it is time to raise prices to make a profile.
- Mr. Leo raised the prices of his course randomly, which led to many complaints.
- The authorities had to establish a law prohibiting raising prices during the war. 
be left doing sth.: 被留下做某事
- Needless to say, I was left taking care of the baby.
- In China, many old men or women in villages are left taking care of children.
- You must elaborate upon why I will be left feeding dogs.
** summary
Although organizations all over the world have lost a great deal of money to fraud,
	many people guilty for this tend to believe that they are innocent.
The fraud triangle shows three conditions that make fraud likely:
	pressure, opportunity, and rationalization.
Pressesure,
		such as a job loss, an illness in family, and so on,
	movitates someone to engage in fraud to begin with.
Having access to tools in both public and privates sectors,
	many people have opportunities to commit and concel fraud.
As the act is often regarded as wrong,
	they also need to justify it to themselvess as first time offenders.
In business, Italian dairy reported farbricating a bank account and falsifying financial statements.
In government,
	Rita Crundwell, former City Comptroller for Dixon, Illinois, embezzled over 53 million dollars
		so that she could afford to her quarter horse breeding.
It's tempting to think of fraud as a victimless crime,
	however, frauds harms real people in virtually every case.
** summary2
Although organizations all over the world have lost a great deal of money to fraud,
	many people who are guilty of this tend to believe that they are innocent.
The fraud triangle shows three conditions that make fraud likely:
	pressure, opportunity, and rationalization.
Pressure,
		such as a job loss, an illness in the family, and so on,
	motivates someone to engage in fraud to begin with.
Having access to tools in both public and private sectors,
	many people have opportunities to commit and conceal fraud.
As the act is often regarded as wrong,
	they also need to justify it to themselves as first-time offenders.
In business, Italian dairy reported fabricating a bank account and falsifying financial statements.
In government,
	Rita Crundwell, former City Comptroller for Dixon, Illinois, embezzled over 53 million dollars
		so that she could afford her quarter horse breeding.
It's tempting to think of fraud as a victimless crime,
	however, fraud harms real people in virtually every case.
