#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-03-13 Can robots be creative
#+begin_verse
How does this music make you feel?
Do you find it beautiful?
Is it creative?
Now, would you change your answers if you learned the composer was this robot?
Believe it or not,
	people have been grappling with the question of artificial creativity,
			alongside the question of artifcial intelligence,
		for over 170 years.
		
In 1843,
	Lady Ada Lovelace, an English mathematician considered the world's first computer programmer,
		wrote that a machine could not have human-like intelligence
			as long as it only did what humans intentionally programmed it to do.
According to Lovelace,
	a machine must be able to create original ideas if it is to be considered intelligent.
The Lovelace Test, formalized in 2001, proposes a way of scrutinizing this idea.
A machine can pass this test
	if it can produce an outcome that its designers cannot explain based on their original code.
The Lovelace Test is, by design, more of a thought experiment than an objective scientific test.

But it's a place to start.
At first glance,
	the idea of a machine creating high quality, original music in this way might seem impossible.
We could come up with an extremely complex algorithm using random number generators,
	chaotic functions, and fuzzy logic to generate a sequence of musical notes in a way
		that would be impossible to track.
But although this would yield countless original melodies never heard before,
	only a tiny fraction of them would be worth listening to.
With the computer having no way to distinguish
	between those which we would consider beautiful and those which we won't.
	
But what if we took a step back
	and tried to model a natural process that allows creativity to form?
We happen to know of at least one such process
	that has lead to original, valuable, and even beautiful outcomes: the process of evolution.
And evolutionary algorithms, or genetic algorithms that mimic biological evolution,
	are one promising approach to making machines generate original and valuable artistic outcomes.
So how can evolution make a machine musically creative?

Well, instead of organisms,
	we can start with an initial population of musical phrases, and a basic algorithm
		that mimics reproduction and random mutations
			by switching some parts, combining others, and replacing random notes.
Now that we have a new generation of phrases,
	we can apply selection using an operation called a fitness function.
Just as biological fitness is determined by external environmental pressures,
	our fitness function can be determined by an external melody chosen by human musicians,
			or music fans,
		to represent the ultimate beautiful melody.
The algorithm can then compare between our musical phrases and that beautiful melody,
	and select only the phrases that are most similar to it.
Once the least similar sequences are weeded out,
	the algorithm can reapply mutation and recombination to what's left,
		select the most similar, or fitted ones, again from the new generation,
		and repeat for many generations.
The process that got us there has so much randomness and complexity built in
	that the result might pass the Lovelace Test.
More importantly, thanks to the presence of human aesthetic in the process,
	we'll theoretically generate melodies we would consider beautiful.
	
But does this satisfy our intuition for what is truly creative?
Is it enough to make something original and beautiful,
	or does creativity require intention and awareness of what is being created?
Perhaps the creativity in this case is really coming from the programmers,
	even if they don't understand the process.
What is human creativity, anyways?
Is it something
	more than a system of interconnected neurons developed by biological algorithmic processes
		and the random experiences that shape our lives?
Order and chaos, machine and human.
These are the dynamos at the heart of machine creativity initiatives
	that are currently making music, sculptures, paintings, poetry and more.
The jury may still be out
	as to whether it's fair to call these acts of creation creative.
But if a piece of art can make you weep, or blow your mind, or send shivers down your spine,
	does it really matter who or what created it?
#+end_verse
** expression
composer [kəmˈpoʊzər]: n. someone who writes music ⇨ composition作曲家
artificial [ˌɑrtɪˈfɪʃ(ə)l]: adj. not real or not made of natural things but made to be like something that is real or natural SYN false OPP natural人造的,人工的
creativity [ˌkrieɪˈtɪvəti]: n. the ability to use your imagination to produce new ideas, make things etc创造力, 创造
mathematician [ˌmæθ(ə)məˈtɪʃ(ə)n]: n. someone who studies or teaches mathematics, or is a specialist in mathematics数学家
programmer [ˈproʊˌɡræmər]: n. someone whose job is to write computer programs程序师
formalize [ˈfɔrməˌlaɪz]: v. to make a plan, decision, or idea official, especially by deciding and clearly describing all the details使正式
scrutinize [ˈskrut(ə)nˌaɪz]: v. to examine someone or something very carefully细察
algorithm [ˈælɡəˌrɪðəm]: n. technical a set of instructions that are followed in a fixed order and used for solving a mathematical problem, making a computer program etc运算法则
generator [ˈdʒenəˌreɪtər]: n. something that produces something else发生器
fuzzy [ˈfʌzi]: adj. unclear or confused OPP clear模糊的
yield [jild]: v. to produce a result, answer, or piece of information生产
countless [ˈkaʊntləs]: adj. too many to be counted无数的, 数不尽的
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
artistic [ɑrˈtɪstɪk]: adj. relating to art or culture艺术的
mutation [mjuˈteɪʃ(ə)n]: n. a change in the ↑genetic structure of an animal or plant that makes it different from others of the skind(生物物种的)突变
fitness [ˈfɪtnəs]: n. the degree to which someone or something is suitable or good enough for a particular situation or purpose适应,适当
complexity [kəmˈpleksəti]: n. the state of being complicated复杂性, 复杂的事物
aesthetic [esˈθetɪk]: n. connected with beauty and the study of beauty美学
theoretically [ˌθiəˈretɪkli]: adv. 理论上
intuition [ˌɪntuˈɪʃ(ə)n]: n. the ability to understand or know something because of a feeling rather than by considering the facts SYN instinct直觉
anyways [ˈeniˌweɪz]: adv. =anyway 不管怎样
dynamo [ˈdaɪnəˌmoʊ]: n. a machine that changes some other form of power directly into electricity发电机
initiative [ɪˈnɪʃətɪv]: n. the ability to make decisions and take action without waiting for someone to tell you what to do主动
--------------------
grapple with the question of sth.: 努力解决某事的问题
program sth. to do sth.: 编程让某事做某事
propose a way of doing sth.: 提出做某事的方法
a sequence of sth.: 一连串的某事
a tiny fraction of sth.: 某物的极小一部分
approach to doing sth.: 做某事的方法
an initial population of sth.: 某物的初始种群
a new generation of sth.: 新一代的某物
be weeded out: 被淘汰
the presence of sth.: 某物的存在
The jury may still be out: 目前还没有定论
blow your mind: 震撼你的思维
send shivers down your spine: 让你背脊发凉
** sentence
grapple with the question of sth.: 努力解决某事的问题
- The teacher who is grappling with the question of artificial intelligence is my father.
- She must have been grappling with the question her boss caused last week.
- Agreeing with the model, he was trying to grapple with the question of molecules.
program sth. to do sth.: 编程让某事做某事
- There's a certain probability of programming the truck to cook in the school.
- I am 100% sure that I can program it to complete our tasks.
- The chance of programming it to clean our house decreases exponentially.
propose a way of doing sth.: 提出做某事的方法
- He developed a model for the bridge and proposed a way of burning it down.
- Interacting with my boss,
		I proposed a way of refactoring the project which has already been rotten.
- The Prime Minister proposing a way of negotiating with our enemies
		in which we surrender the island to them.
a sequence of sth.: 一连串的某事
- Believe it or not, when I drove on to the company, a sequence of accidents happened.
- A sequence of abductions by terrorists makes this country more chaotic.
- A sequence of information on this natural disaster provided by anonymous persons
		 confused us a great deal.
a tiny fraction of sth.: 某物的极小一部分
- A tiny fraction of water may be enough to form life on this planet.
- This village used to be inhabited by a tiny fraction of elephants.
- A tiny fraction of shit must spoil the chicken soup.
an approach to doing sth.: 做某事的方法
- That's an approach to forming life in an extreme environment.
- The approach to training your dog to trigger the light may be fatal for him.
- The approach to getting along with the difficult companion
		is just to be the right distance from him.
an initial population of sth.: 某物的初始种群
- An initial population of tadpoles will be full of the pool in the future.
- No one could account for the fact
		 that an initial population of tadpoles survived a drought in the end.
- An initial population of tadpoles may increase exponentially in this pool.
a new generation of sth.: 新一代的某物
- So to speak, you are a new generation of Americans.
- Anyways, a new generation of Americans is higher than their parents.
- A new generation of mold began to appear in the back of your fridge.
be weeded out: 被淘汰
- Weeded out, he was rewarded with fifty pence worth of television.
- Bursting out tears, he was told that he hadn't been weed out of the competition.
- I appreciate your honesty, but you are weeded out because of your mistakes at work.
the presence of sth.: 某物的存在
- He proved that there should be the presence of God.
- The presence of my wife's support gave me the nudge to resign from office.
- The presence of my pocket money encouraged me to buy a new piano for my wife. 
The jury may still be out as to whether + ...: 目前还没有定论
- The jury may still be out as to whether our experiment agrees with our model for an atom.
- The jury may still be out as to whether he committed a murder.
- The jury may still be out as to whether I passed the test.
blow your mind: 震撼你的思维
- Filling up the parcel with diamonds, the rich man blew my mind.
- A note the police left reminding me of my father blew my mind.
- Mosquito grappling with getting out of the bottle blew my mind.
send shivers down your spine: 让你背脊发凉
- The story, which describes a woman poisoning her five husbands in her youth,
		 really sent shivers down my spine.
- I have no intention of sending shivers down your spine, so I won't tell you the terrible story.
- I am tempted to cheat on my wife in the bar, which sends shivers down my spine.
** summary
Do you believe that the music is composed by this robot?
People have been researching artificial intellengence and artificial creativity
	for over 170 years.
intellengence-intelligence
The Lovelace Test,
		which named after Lady Ada Lovelace,
			an English mathematician regarded as the first computer programmer,
	is formalized in 2001 which proprosed an approach to examine whether a machine is intelligent.
named after-be named after
proprosed-proposed
Although it may seems impossible that a machine creates original music,
	we can develop a complex algorthim using random generator, chaotic functions, and fuzzy logic
		to yield countless melodies never heard before.
seems impossible for sb./sth. to do sth.
The point is that only few of them are worth listening to.
few VS a few
little 不可数/ few 可数, 带a肯定,不带a否定
only few of them -> few of them, 带only就得带a
So let's take a step back and use evolutionary algorithms or genetic algorithms
	that mimics biological evolution that allows creativity to form.
mimics-mimic
We can start with an initial population of phrases
		and a basic algorithm used to switch some parts, combine others, and replace random notes
	so that we can have a new generation of phrases.
Then we apply selection using a fitness function which eliminates the least similar melody
	and repeat for many generations to get the ultimate beautiful melody.
It is unclear that these act of creation can be called creative.
act-acts
However, who care whether a piece of art shocking you is made by a robot or a human?
who cares
** summary2
Do you believe that the music is composed by this robot?
People have been researching artificial intelligence and artificial creativity
	for over 170 years.
The Lovelace Test,
		which was named after Lady Ada Lovelace,
			an English mathematician regarded as the first computer programmer,
	is formalized in 2001 which proposed an approach to examine whether a machine is intelligent.
Although it may seem impossible that a machine creates original music,
	we can develop a complex algorithm using random generators, chaotic functions, and fuzzy logic
		to yield countless melodies never heard before.
The point is that few of them are worth listening to.
So let's take a step back and use evolutionary algorithms or genetic algorithms
	that mimic biological evolution that allows creativity to form.
We can start with an initial population of phrases
		and a basic algorithm used to switch some parts, combine others, and replace random notes
	so that we can have a new generation of phrases.
Then we apply selection using a fitness function which eliminates the least similar melody
	and repeat for many generations to get the ultimate beautiful melody.
It is unclear that these acts of creation can be called creative.
However, who cares whether a piece of art shocking you is made by a robot or a human?
