#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-03-12 Plato’s Allegory of the Cave
#+begin_verse
What is reality, knowledge, the meaning of life?
Big topics you might tackle figuratively
	explaining existence as a journey down a road or across an ocean,
		a climb, a war, a book, a thread, a game, a window of opportunity,
			or an all-too-short-lived flicker of flame.
			
2,400 years ago, one of history's famous thinkers said life is like being chained up in a cave,
	forced to watch shadows flitting across a stone wall.
Pretty cheery, right?
That's actually what Plato suggested in his Allegory of the Cave,
	found in Book VII of 'The Republic,'
	in which the Greek philosopher envisioned the ideal society
		by examining concepts like justice, truth and beauty.
		
In the allegory, a group of prisoners have been confined in a cavern since birth,
	with no knowledge of the outside world.
They are chained, facing a wall, unable to turn their heads,
	while a fire behind them gives off a faint light.
Occasionally, people pass by the fire,
	carrying figures of animals and other objects that cast shadows on the wall.
The prisoners name and classify these illusions, believing they're perceiving actual entities.
Suddenly, one prisoner is freed and brought outside for the first time.
The sunlight hurts his eyes and he finds the new environment disorienting.
When told that the things around him are real, while the shadows were mere reflections,
	he cannot believe it.
The shadows appeared much clearer to him.
But gradually, his eyes adjust until he can look at reflections in the water,
	at objects directly, and finally at the Sun,
		whose light is the ultimate source of everything he has seen.
The prisoner returns to the cave to share his discovery,
	but he is no longer used to the darkness, and has a hard time seeing the shadows on the wall.
The other prisoners think the journey has made him stupid and blind,
	and violently resist any attempts to free them.
	
Plato introduces this passage as an analogy of what it's like to be a philosopher
	trying to educate the public.
Most people are not just comfortable in their ignorance but hostile to anyone who points it out.
In fact, the real life Socrates was sentenced to death by the Athenian government
		for disrupting the social order,
	and his student Plato spends much of 'The Republic' disparaging Athenian democracy,
		while promoting rule by philosopher kings.
		
With the cave parable,
	Plato may be arguing that the masses are too stubborn and ignorant to govern themselves.
But the allegory has captured imaginations for 2,400 years because it can be read in far more ways.
Importantly, the allegory is connected to the theory of forms,
	developed in Plato's other dialogues,
	which holds that like the shadows on the wall,
		things in the physical world are flawed reflections of ideal forms,
			such as roundness, or beauty.
In this way, the cave leads to many fundamental questions,
	including the origin of knowledge, the problem of representation,
		and the nature of reality itself.
For theologians, the ideal forms exist in the mind of a creator.
For philosophers of language viewing the forms as linguistic concepts,
	the theory illustrates the problem of grouping concrete things under abstract terms.
And others still wonder
	whether we can really know that the things outside the cave are any more real than the shadows.
	
As we go about our lives, can we be confident in what we think we know?
Perhaps one day, a glimmer of light may punch a hole in your most basic assumptions.
Will you break free to struggle towards the light,
		even if it costs you, your friends and family,
	or stick with comfortable and familiar illusions?
Truth or habit?
Light or shadow?
Hard choices, but if it's any consolation, you're not alone.
There are lots of us down here.  
#+end_verse
** expression
figurative [ˈfɪɡjərətɪv]/figuratively: adj.adv. a figurative word or phrase is used in a different way from its usual meaning, to give you a particular idea or picture in your mind ⇨ literal比喻的 
thread [θred]: n. an idea, feeling, or feature that connects the different parts of an explanation, story etc线索
flicker [ˈflɪkər]: v. to burn or shine with an unsteady light that goes on and off quickly摇曳, 闪烁
flit [flɪt]: v. to move lightly or quickly and not stay in one place for very long掠过
cheery [ˈtʃɪri]: adj. happy or making you feel happy愉快的
allegory [ˈæləɡəri]: n. a story, painting etc in which the events and characters represent ideas or teach a moral lesson寓言
Republic [rɪˈpʌblɪk]: n. a country governed by elected representatives of the people, and led by a president, not a king or queen共和国
envision [ɪnˈvɪʒ(ə)n]: n. to imagine something that you think might happen in the future, especially something that you think will be good想象, 预想
cavern [ˈkævərn]: n. a large ↑cave巨洞, 洞窟
faint [feɪnt]: adj. difficult to see, hear, smell etc虚弱的,微弱的
cast [kæst]: v. literary to make light or a shadow appear somewhere投射
classify [ˈklæsɪˌfaɪ]: v. to decide what group something belongs to分类
perceive [pərˈsiv]: v. formal to notice, see, or recognize something ⇨ perceptive感知
entity [ˈentəti]: n. formal something that exists as a single and complete unit ⇨ being实体
disorienting [dɪsˈɔriənt]: adj. confusing you and making you not certain about what is happening around you使失去方向感, 使迷惑
reflection [rɪˈflekʃ(ə)n]: n. an image that you can see in a mirror, glass, or water映象
adjust [əˈdʒʌst]: v. to change or move something slightly to improve it or make it more suitable for a particular purpose调整
blind [blaɪnd]: adj. unable to see瞎的, 盲目的
ignorance [ˈɪɡnərəns]: n. lack of knowledge or information about something无知
disrupt [dɪsˈrʌpt]: v. to prevent something from continuing in its usual way by causing problems使中断
disparaging [dɪˈsperɪdʒɪŋ]: adj. criticizing someone or something, and showing that you do not think they are very good or important蔑视的
promote [prəˈmoʊt]: v. to try to persuade people to support or use something促进, 发扬, 提升, 提拔
rule [rul]: v. the government of a country or area by a particular group of people or using a particular system统治
parable [ˈperəb(ə)l]: n. a short simple story that teaches a moral or religious lesson, especially one of the stories told by Jesus in the Bible寓言
mass [mæs]: n. a large crowd群众
stubborn [ˈstʌbərn]: adj. determined not to change your mind, even when people think you are being unreasonable顽固的
ignorant [ˈɪɡnərənt]: adj. not knowing facts or information that you ought to know无知的
dialogue [ˈdaɪəˌlɔɡ]: n. a conversation in a book, play, or film对话
flawed [flɔd]: adj. spoiled by having mistakes, weaknesses, or by being damaged有缺陷的
roundness [raʊndnəs]: n. 圆,圆满
fundamental [ˌfʌndəˈment(ə)l]: adj. very necessary and important基础的, 基本的
representation [ˌreprɪzenˈteɪʃ(ə)n]: n. the act of representing someone or something表现
theologian [ˌθiəˈloʊdʒən]: n. someone who has studied theology神学者
linguistic [lɪŋˈɡwɪstɪk]: adj. related to language, words, or linguistics语言上的
concrete [ˈkɑŋˌkrit]: adj. definite and specific ⇨ abstract具体的, 有形的
abstract [æbˈstrækt]: adj. existing only as an idea or quality rather than as something real that you can see or touch OPP concrete抽象的
assumption [əˈsʌmpʃ(ə)n]: n. something that you think is true although you have no definite proof ⇨ assume假定
consolation [ˌkɑnsəˈleɪʃ(ə)n]: n. something that makes you feel better when you are sad or disappointed安慰
----------------------------------------
explain A. as B.: 把A解释为B
be like doing sth.: 就像是做某事
be chained up: 被锁起来
face a wall: 面对墙壁
give off: 发出(亮光)
pass by sb./sth.: 经过某人某物
have a hard time doing sth.: 做某事很困难
resist an attempt to do sth.: 抵制做某事的企图
introduce A. as an analogy of B.: 解释A当作B的比喻
be hostile to sb.: 对某人有敌意
the real life: 真实生活中
be sentenced to death/imprisonment: 被判处死刑
capture imaginations: 引起想象
view A. as B.: 把A看作是B
group A under B: 把A归类为B
go about sth.: 忙于某事
a glimmer of light: 一丝光
punch a hole: 打孔
break free (from sth.): 从某事中解脱出来
stick with sth.: 坚持使用某事
** sentences
explain A. as B.: 把A解释为B
- He explained playing truant from school as an adventure.
- That's why he explained the seat as harsher working condition.
- Why do you explain his pocket money as yours?
be like doing sth.: 就像是做某事
- The philosopher claimed that life is like being chained up in a cavern.
- Devoting himself to education is like promoting plants in the garden.
- His behaviors at the fancy dress party were like playing the role of a detective.
be chained up: 被锁起来
- The man who is being chained up is your boss, who promised to give you a better salary.
- How dare the man chained up squinted at me when I arrived on the scene.
- After having seen a man chained up, the police proceed to search for evidence.
face a wall: 面对墙壁
- My father insisted that I stand and face a wall for my failure of the test.
- I was facing a wall yesterday, because of a blank sheet of paper in the test.
- It seemed reasonable to assume that a man were facing the wall at the monastery.
give off: 发出(亮光)
- The light is broken, which only gives off the dim light.
- The candle is being used up giving off the faint light.
- At midnight, the old lady is looking for the switch,
		with the torchlight giving off the faint light.
pass by sb./sth.: 经过某人某物
- She got very angry because a car had passed by her.
- My ex-girlfriend passed by me without any word, which made me lose my heart.
- The powerful engine made us pass by the taxi again.
have a hard time doing sth.: 做某事很困难
- The police often have a hard time keeping order, when the group is giving performances.
- I have a hard time keeping in touch with my difficult colleagues.
- The scientist had a hard time proving his theory of an atom true.
resist an attempt to do sth.: 抵制做某事的企图
- The king resisted an attempt to surrender the castle to his enemies.
- I can't resist an attempt to kiss my wife when she is fast asleep.
- I have resisted an attempt to bargain with the grocer
		with the accompany of my wife who used to be my girlfriend.
introduce A. as an analogy of B.: 解释A当作B的比喻
- Teachers in China usually introduce flowers in the garden as an analogy of children.
- The scientist introduces minimum wage as an analogy of these chemical substances.
- He likes to introduce a powerful engine as an analogy of his wife who is always hard-working.
be hostile to sb.: 对某人有敌意
- I can't recognize the men who are hostile to me.
- Driving in harsher working conditions, the busman was hostile to the passengers.
- He is always being hostile to people around him in a pinch.
In real life,: 真实生活中
- In real life, he has been put out of business.
- In real life, we have to be in the face of low salaries and the lack of jobs.
- In real life, the ability to make friends matters to your social status.
be sentenced to death/imprisonment: 被判处死刑/监禁
- The poor journalist who was instructed to figure out the number of steps to the palace
		was sentenced to imprisonment.
- The man who hit the surface of the artifact was sentenced to imprisonment.
- It seems odd that the philosopher is sentenced to death for spreading knowledge.
capture the imagination: 引起想象
- The article he wrote on the World Wide Web captured the imagination.
- A note of triumph coming from her mouth captured our imaginations.
- A faint smile on the face of the heroine at the end of the movie captured the imagination.
view A. as B.: 把A看作是B
- It seemed odd that you viewed my description as a complaint.
- You needn't have viewed this reminder as a ticket and lost your temper.
- It is a blessing that he always views difficulties as challenges.
group A under B: 把A归类为B
- The experts from the zoo group pumas under cat-like animals.
- I am delighted that you group your classmates under friends.
- I am sure that the animal is grouped under a mammal.
go about sth.: 忙于某事
- I am going about preparing for dinner, make yourself comfortable.
- Don't be too hard on me, I am going about the tasks you arranged last week.
- 'You are going about climbing stairs.' The police said with a sneer. 
a glimmer of light: 一丝光
- He has been reading for several nights, with a glimmer of light casting on his book.
- A glimmer of light? What a harsher working condition!
- She has been walled off and could only enjoy a glimmer of light.
punch a hole: 打孔
- Before assembling the leg into the body, we must punch a hole.
- My neighbor complained that I punched a hole across the wall.
- The worker will punch a hole in the wall to suspend your TV. 
break free (from sth.): 从某事中解脱出来
- You must break free from tremendous works to begin thinking.
- After breaking free from work, I will knock at your door.
- Little thing is known about how he broke free from the prison.
stick with sth.: 坚持使用某事
- I decided not to stick with working for this company.
- Fulfilling his dream, he sticks with the job which he dreamed of in his youth.
- Following in his father's footsteps, he stopped sticking with working for Apple.
