#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-01-30 Why are some people left-handed?
#+begin_verse
If you know an older left-handed person,
	chances are they had to learn to write or eat with their right hand.
And in many parts of the world,
	it's still common practice to force children to use their "proper" hand.
Even the word for right also means correct or good,
	not just in English, but many other languages, too.
	
But if being left-handed is so wrong,
	then why does it happen in the first place?
Today, about 1/10 of the world's population are left-handed.
Archeological evidence shows that it's been that way for as long as 500,000 years,
	with about 10% of human remains showing the associated differences in arm length and bone density,
	and some ancient tools and artifacts showing evidence of left-hand use.
	
And despite what many may think, handedness is not a choice.
It can be predicted even before birth based on the fetus' position in the womb.
So, if handedness is inborn, does that mean it's genetic?
Well, yes and no.
Identical twins, who have the same genes, can have different dominant hands.
In fact, this happens as often as it does with any other sibling pair.
But the chances of being right or left-handed
	are determined by the handedness of your parents in surprisingly consistent ratios.
If your father was left-handed but your mother was right-handed,
		you have a 17% chance of being born left-handed,
	while two righties will have a left-handed child only 10% of the time.
Handedness seems to be determined by a roll of the dice, but the odds are set by your genes.
All of this implies there's a reason
	that evolution has produced this small proportion of lefties,
		and maintained it over the course of millennia.
		
And while there have been several theories
		attempting to explain why handedness exists in the first place,
			or why most people are right-handed,
	a recent mathematical model suggests that the actual ratio reflects a balance
		between competitive and cooperative pressures on human evolution.
The benefits of being left-handed are clearest in activities involving an opponent,
	like combat or competitive sports.
For example, about 50% of top hitters in baseball have been left-handed.
Why?
Think of it as a surprise advantage.
Because lefties are a minority to begin with,
	both right-handed and left-handed competitors
		will spend most of their time encountering and practicing against righties.
So when the two face each other,
		the left-hander will be better prepared against this right-handed opponent,
	while the righty will be thrown off.
	
This fighting hypothesis,
		where an imbalance in the population
			results in an advantage for left-handed fighters or athletes,
	is an example of negative frequency-dependent selection.
But according to the principles of evolution,
	groups that have a relative advantage tend to grow until that advantage disappears.
If people were only fighting and competing throughout human evolution,
	natural selection would lead to more lefties being the ones
		that made it until there were so many of them, that it was no longer a rare asset.
So in a purely competitive world, 50% of the population would be left-handed.

But human evolution has been shaped by cooperation, as well as competition.
And cooperative pressure pushes handedness distribution in the opposite direction.
In golf, where performance doesn't depend on the opponent,
	only 4% of top players are left-handed,
	an example of the wider phenomenon of tool sharing.
Just as young potential golfers can more easily find a set of right-handed clubs,
	many of the important instruments that have shaped society
		were designed for the right-handed majority.
Because lefties are worse at using these tools, and suffer from higher accident rates,
	they would be less successful in a purely cooperative world,
		eventually disappearing from the population.
		
So by correctly predicting the distribution of left-handed people in the general population,
	as well as matching data from various sports,
	the model indicates
		that the persistence of lefties as a small but stable minority reflects an equilibrium
			that comes from competitive and cooperative effects playing out simultaneously over time.
And the most intriguing thing is what the numbers can tell us about various populations.
From the skewed distribution of pawedness in cooperative animals,
		to the slightly larger percentage of lefties in competitive hunter-gatherer societies,
	we may even find
		that the answers to some puzzles of early human evolution are already in our hands.
#+end_verse
** expression
left-handed: a left-handed person uses their left hand for writing, throwing etc OPP right-handed
proper: right, suitable, or correct
1/10: one-tenth
artifact: 历史文物
fetus: 胎儿
inborn: an inborn quality or ability is one you have had naturally since birth
genetic: relating to ↑genes or ↑genetics遗传的, 起源的
identical: exactly the same, or very similar
gene: 基因 
dominant: more powerful, important, or noticeable than other people or things支配的
consistent: 一致的
ratio: a relationship between two amounts, represented by a pair of numbers showing how much bigger one amount is than the other ⇨ proportion比率
odds: the odds how likely it is that something will or will not happen
millennium/millennia:a period of 1,000 years
theory: 理论,假设hypothesis
competitive: determined or trying very hard to be more successful than other people or businesses ⇨ compete, competitor竞争的
competitor: 竞争者
combat: fighting, especially during a war
hitter: [棒球]击球员
hypothesis: an idea that is suggested as an explanation for something, but that has not yet been proved to be true SYN theory
athletes: someone who competes in sports competitions, especially running, jumping, and throwing运动员
frequency-dependent: 频率相关的
asset: the things that a company owns, that can be sold to pay debts资产
distribution: 分布状态
majority: 多数
equilibrium: a balance between different people, groups, or forces that compete with each other, so that none is stronger than the others and a situation is not likely to change suddenly
intriguing: something that is intriguing is very interesting because it is strange, mysterious, or unexpected SYN fascinating
skewed: an opinion, piece of information, result etc that is skewed is incorrect, especially because it has been affected by a particular thing or because you do not know all the facts
pawedness: 爪侧性,对左爪或右爪的偏好
hunter-gatherer: 狩猎采集者
puzzle: 难题
----------------------------------------
chances are + ...: 很可能...
in many parts of the world: 在世界各地
the word for A: A这个单词
in the first place: 首先 For one thing
show evidence of sth./doing sth.: 显示做某事的证据
in the womb: 在子宫里
have a 17% chance of doing/being sth.: 有17%的机会做某事
be born adj.: 与生剧来...
by a roll of the dice: 靠投塞子
It implies that + ...: 这意味着...
over the course of millennia: 经过数千年的时间
The benefits of doing sth.: 做某事的好处
a minority to do sth.: 做某事的少数人
be thrown off: 被抛弃
lead to sb. doing sth.: 导致某人做某事
in the opposite direction: 朝相反方向
disappear from: 从...消失
play out: 发展,演变
simultaneously over time: 同时随着时间的推移
in sb's hands: 在某人手中
** sentences
chances are + ...: 很可能...
- Chances are he will behave as a police gentleman at the fancy dress party.
- Chances are life can be formed in outer space.
- Chances are that they have drawn on the answers to the puzzle.
in many parts of the world: 在世界各地
- Repaying the thing of equal value immediately
		is read as ending the relationship in many parts of the world. 
- In many parts of the world, china is the basic building block of tableware.
- In many parts of the world, tourists often receive a cold welcome.
the word for A: A这个单词
- These days, the word for entrepreneur in the world wide web of China is born guilty.
- The word for entrepreneurs in China means a group of vampires
		that are feasting on people's wealth.
- The word for poor in China means right.
in the first place: 首先 For one thing
- My father taught me a lesson that I should perpetuate my existence in the first place.
- You have mobilized your immune system in the first place.
- When you are in the face of gangster bangs on the street at midnight,
		call the police in the first place.
show evidence of sth./doing sth.: 显示做某事的证据
- These scars have shown evidence of his father's mistreatment.
- Showing evidence of his murder, he is forbidden to enter this country again.
- With this procedure, he shows evidence of the chance of the lives in outer space.
in the womb: 在子宫里
- My mother always complains that I had been running in the womb.
- I noticed with dismay that my child is not in the womb, which means that my wife may abort.
- The fetus in the womb is aborted because of her husband's mistreatment in captivity.
have a 17% chance of doing/being sth.: 有17%的机会做某事
- The player said that his team had a 50% chance of being the champion in this game.
- You have no chance of getting a good salary working for this company.
- I have a 99% chance of accumulating social wealth by giving away livestock.
be born adj.: 与生剧来...
- I seem to be born benevolent.
- These dogs that are born friendly are used as watchdogs.
- These dogs that are born strong are used as the power of transport in the snow.
by a roll of the dice: 靠投塞子
- He is likely to tackle problems of the program by a roll of the dice.
- Believe it or not, I predict his death in this adventure by a roll of the dice.
- I had hit the right option by a roll of the dice.
It implies that + ...: 这意味着...
- It implies that she fails to break the world record.
- It implies that I have the ability to speak English fluently.
- It implies that these cats from other continents fill an ecological niche in the city.
over the course of millennia: 经过数千年的时间
- The archaeologist developed a model for the city over the course of a year.
- The body of the chief in the tribe became a famous fossil over the course of millennia.
- The fossil decayed away by wind and rain over the course of millennia.
The benefits of doing sth.: 做某事的好处
- The benefit of completing this course is the chance of working for Apple.
- The benefit of exercising every day is to lead a happy life with your family.
- The benefit of studying English is the ability to work for foreign enterprises.
a minority to do sth.: 做某事的少数人
- The people in this village are a minority to contribute to the gift. 
- The group of paleontologists is a minority to dig up fossils in creek banks.
- You're a minority to hold that poss while taking the photograph.
be thrown off: 被抛弃
- The teams that came from have been throwing off early again in the competition.
- No one will be thrown off in this process.
- The prizefighter must have been thrown off at the beginning of the competition.
lead to sb. doing sth.: 导致某人做某事
- You shouldn't have crossed the road with the light red, which may lead to your children doing so.
- My father's advice led to me rubbing my scar with alcohol.
- This leads to her making a special type of mixture.
in the opposite direction: 朝相反方向
- He must have driven to the village in the opposite direction.
- The mall that is ten miles in the opposite direction is in the exhibition.
- This fool has stood to attention in the opposite direction.
disappear from: 从...消失
- When the police arrived on the scene, the killer had already disappeared from the airport.
- The parcel full of diamonds disappeared from the museum which was being spied on.
- Dressed in overalls, he disappeared from the tent which they put up.
play out: 进行
- The hardworking and lazy effects are playing out at the same time.
- The rescue of the fire brigade and the connection of their families
		might as well be playing out together.
- The experiment had been playing out over the course of a week.
simultaneously over time: 同时随着时间的推移
- They succeeded in sailing across the Atlantic Ocean simultaneously over time.
- They developed a model for an atom simultaneously over time.
- They have fallen into each other simultaneously over time.
in sb's hands: 在某人手中
- It reminded me of the book titled Harry Potter in his hands.
- I must lead a happy life in my hands.
- I always ask myself to be in charge of the code in my hands.
