#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-05-15 Debunking the myths of OCD
#+begin_verse
There's a common misconception
	that if you like to meticulously organize your things,
			keep your hands clean, or plan out your weekend to the last detail,
		you might have OCD.
In fact, OCD, which stands for obsessive compulsive disorder,
	is a serious psychiatric condition
		that is frequently misunderstood by society and mental health professionals alike.
		
So let's start by debunking some myths.
Myth one: repetitive or ritualistic behaviors are synonymous with OCD.
As its name suggests, obsessive compulsive disorder has two aspects:
	the intrusive thoughts, images, or impulses, known as obsessions,
	and the behavioral compulsions people engage in to relieve the anxiety the obsessions cause.
The kinds of actions that people often associate with OCD,
		like excessive hand washing, or checking things repeatedly,
	may be examples of obsessive or compulsive tendencies that many of us exhibit from time to time.
But the actual disorder is far more rare and can be quite debilitating.
People affected have little or no control over their obsessive thoughts and compulsive behaviors,
	which tend to be time consuming
		and interfere with work, school or social life to the point of causing significant distress.
This set of diagnostic criteria
	is what separates people suffering from OCD from those
		who may just be a bit more meticulous or hygiene obsessed than usual.
		
Myth two: the main symptom of OCD is excessive hand washing.
Although hand washing is the most common image of OCD in popular culture,
	obsessions and compulsions can take many different forms.
Obsessions can manifest as fears of contamination and illness,
	worries about harming others,
	or preoccupations with numbers, patterns, morality, or sexual identity.
And compulsions can range from excessive cleaning or double checking,
	to the fastidious arrangement of objects, or walking in predetermined patterns.
	
Myth three: individuals with OCD don't understand that they are acting irrationally.
Many individuals with OCD
	actually understand the relationship between their obsessions and compulsions quite well.
Being unable to avoid these thoughts and actions despite being aware of their irrationality
	is part of the reason why OCD is so distressing.
OCD sufferers report feeling crazy
	for experiencing anxiety based on irrational thoughts
		and finding it difficult to control their responses.
		
So what exactly causes OCD?
The frustrating answer is we don't really know.
However, we have some important clues.
OCD is considered a neurobiological disorder.
In other words, research suggests
		that OCD sufferers brains are actually hardwired to behave in a certain fashion.
Research has implicated three regions of the brain
	variously involved in social behavior and complex cognitive planning,
		voluntary movement, and emotional and motivational responses.
The other piece of the puzzle
	is that OCD is associated with low levels of serotonin,
		a neurotransmitter that communicates between brain structures
			and helps regulate vital processes,
				such as mood, aggression, impulse control, sleep, appetite, body temperature and pain.
But are serotonin and activity in these brain regions
	the sources of OCD or symptoms of an unknown underlying cause of the disorder.
We probably won't know until we have a much more intimate understanding of the brain.

The good news is there are effective treatments for OCD,
	including medications,
		which increase serotonin in the brain by limiting its reabsorption by brain cells,
	behavioral therapy that gradually desensitizes patients to their anxieties,
	and in some cases, electroconvulsive therapy, or surgery,
		when OCD doesn't respond to other forms of treatment.
Knowing that your own brain is lying to you
	while not being able to resist its commands can be agonizing.
But with knowledge and understanding comes the power to seek help,
	and future research into the brain may finally provide the answers we're looking for.
#+end_verse
** expression
misconception [ˌmɪskənˈsepʃ(ə)n]: n. an idea which is wrong or untrue, but which people believe because they do not understand the subject properly SYN fallacy ⇨ preconception误解
meticulous [mɪˈtɪkjələs] meticulously: adj.adv. very careful about small details, and always making sure that everything is done correctly小心翼翼的
obsessive [əbˈsesɪv]: adj. thinking or worrying about something all the time, so that you do not think about other things enough – used to show disapproval痴迷的
compulsive [kəmˈpʌlsɪv]: adj. compulsive behaviour is very difficult to stop or control, and is often a result of or a sign of a mental problem ⇨ obsessive强制的, 强迫的
psychiatric [ˌsaɪkiˈætrɪk]: adj. relating to the study and treatment of mental illness精神病学的
alike [əˈlaɪk]: adv. very similar以同样的方式
repetitive [rɪˈpetətɪv]: adj. done many times in the sway, and boring重复的, 反复性的
ritualistic [ˌrɪtʃuəˈlɪstɪk]: adj. ritualistic words or behaviour always follow the spattern, especially because they form part of a ritual仪式的
intrusive [ɪnˈtrusɪv]: adj. affecting someone’s private life or interrupting them in an unwanted and annoying way打扰的
obsession [əbˈseʃ(ə)n]: n. an extreme unhealthy interest in something or worry about something, which stops you from thinking about anything else痴迷
tendency [ˈtendənsi]: n. if someone or something has a tendency to do or become a particular thing, they are likely to do or become it倾向
debilitate [dɪˈbɪlɪˌteɪt] debilitating: v.adj. to make someone ill and weak使衰弱
distress [dɪˈstres]: n. a feeling of extreme unhappiness悲痛
diagnostic [ˌdaɪəɡˈnɑstɪk]: adj. relating to or used for discovering what is wrong with someone or something诊断的
contaminate [kənˈtæmɪˌneɪt] contamination [kənˈtæmɪˌneɪt][kənˌtæmɪ'neɪʃən]: v.n.to make a place or substance dirty or harmful by putting something such as chemicals or poison in it污染
hygiene obsessed [ˈhaɪdʒin]: 卫生着迷
clue [klu]: n. information that helps you understand the reasons why something happens线索
neurobiological [ˌnʊroʊˌbaɪəˈlɑːdʒɪkl]: adj. 神经生物学的
serotonin [ˌsɪrəˈtoʊnɪn]: n. a chemical in the body that helps carry messages from the brain and is believed to make you feel happy血清素
neurotransmitter ['njʊərəʊtrænzmɪtə(r)]: n. 神经传递素
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules控制, 调节
desensitize [diˈsensəˌtaɪz]: v. to make someone react less strongly to something by making them become used to it使麻木
electroconvulsive [ɪˌlektroʊkən'vʌlsɪv]: adj. 电休克的
agonize [ˈæɡəˌnaɪz] agonizing: v.adj. extremely painful痛苦难忍的
--------------------
plan out sth. to the last detail: 把某事计划到最后一个细节
debunk some myths: 破除一些迷思
A be synonymous with B: A于B同义
from time to time: 时不时地
have little or no control over sth.: 对某事几乎没有控制
interfere with sth. to the point of doing sth.: 干涉某事到做某事的地步
separates A from B: 从B分离A
manifest as sth.: 表现为...
preoccupations with sth.: 对某事的全神贯注
range from ... to ...: 从...到...的范围
quite well: 相当地
be hardwired to do sth.: 注定做某事
the underlying cause of sth.: 某事的根本原因
lie to sb.: 对某人说慌
** ch.
2015-05-15 打破强迫症的误区
有一种普遍的误解，如果你喜欢把东西整理得一丝不苟，保持双手干净，或者把周末计划得非常细致，你可能患有强迫症。
事实上，强迫症（OCD，强迫症障碍）是一种严重的精神障碍，通常被社会和心理健康专业人士误解。
所以，让我们从打破一些误区开始。
误区一：重复性或仪式性的行为与强迫症是同义的。
顾名思义，强迫症有两个方面：侵入性的思想、影像或冲动，被称为“强迫思维”，以及人们为缓解这些强迫思维所产生的焦虑而进行的行为强迫。
人们常常与强迫症联系在一起的行为，比如过度洗手或反复检查事物，可能是很多人偶尔表现出的强迫或强迫倾向的例子。
但实际的强迫症要罕见得多，且可能非常虚弱不堪。
受影响的人几乎无法控制自己的强迫思维和行为，这些行为通常会耗费大量时间，干扰工作、学习或社交生活，甚至造成显著的痛苦。
这一诊断标准将患有强迫症的人与那些可能只是比平时更注重细节或有洁癖的人区分开来。
误区二：强迫症的主要症状是过度洗手。
尽管洗手是大众文化中对强迫症的最常见印象，但强迫症的强迫思维和行为可以有多种不同的表现。
强迫思维可以表现为对污染和疾病的恐惧、对伤害他人的担忧、对数字、模式、道德或性别认同的困扰。
而强迫行为则可以从过度清洁或反复检查，到对物品的精确排列，或者按预定的路线行走等多种形式表现出来。
误区三：患有强迫症的人并不理解自己行为的非理性。
许多患有强迫症的人实际上非常清楚自己的强迫思维和行为之间的关系。
尽管意识到这些思维和行为的非理性，仍然无法避免它们，这也是为什么强迫症如此令人痛苦的原因之一。
强迫症患者报告说，自己因为基于非理性思维而产生焦虑，感觉自己变得疯狂，且发现难以控制自己的反应。
那么，究竟是什么导致了强迫症呢？
令人沮丧的答案是我们并不完全知道。
然而，我们有一些重要的线索。
强迫症被认为是一种神经生物学的疾病。
换句话说，研究表明，强迫症患者的大脑实际上被硬性编程，以某种方式运作。
研究已经发现，大脑中有三个区域与社会行为和复杂的认知规划、主动运动，以及情感和动机反应等方面相关。
另一个线索是，强迫症与低水平的5-羟色胺（即“血清素”）有关，这是一种在大脑结构之间传递信号的神经递质，有助于调节重要的生理过程，如情绪、攻击性、冲动控制、睡眠、食欲、体温和疼痛等。
但这些大脑区域的血清素活跃度是强迫症的根源，还是它的症状，或者是这种疾病某种未知根本原因的表现呢？
我们可能需要更深入理解大脑，才能知道答案。
好消息是，强迫症是有有效治疗方法的，包括药物治疗，药物通过限制血清素被大脑细胞再吸收来提高大脑中的血清素水平；行为疗法，通过逐渐使患者对其焦虑产生脱敏作用；以及在某些情况下，对于其他治疗方法无效的强迫症患者，电休克治疗或手术。
知道自己的大脑在欺骗自己，同时却无法抗拒它的指令，这种感受是痛苦的。
但通过了解和认识，我们就有了寻求帮助的力量，而未来对大脑的研究可能最终为我们提供我们所追求的答案。
** sentence
plan out sth. to the last detail: 把某事计划到最后一个细节
- He is so meticulous that he planned out his wedding to the last detail.
- It is no use planning out everything to the last detail, for things change with the times.
- The wedding he planned out to the last detail ran very successfully.
debunk some myths: 破除一些迷思
- The king dispatched some officials around to debunk some myths about vampires
		and established a law prohibiting digging up tombs.
- The doctor tried to discern the cause of the rare disease to debunk those myths.
- You are supposed to read the coverage, which may debunk some myths.
A be synonymous with B: A于B同义
- To permit somebody to do something is synonymous with to allow somebody to do something.
- What's the matter is synonymous with what's up.
- He insisted that what's the matter is not synonymous with what's wrong with you.
from time to time: 时不时地
- The beggar asks me for a meal from time to time on Weekends.
- The monster living in the mountain is said to feast on sacrificed children from time to time.
- I am tired that the vicar raises money to have the clock repaired from time to time.
have little or no control over sth.: 对某事几乎没有控制
- After his military declined, the king had little or no control over these provinces,
		which led to the collapse of the dynasty.
- With disaster comes weakness, the empire had little or no control over subjects.
- The terrorist claimed that he had little or no control over the bombs planted at the aircraft.
interfere with sth. to the point of doing sth.: 干涉某事到做某事的地步
- The dominant father interfered with the marriage of his son
		to the point of causing the death of lovers.
- My wife interferes with my daily life to the point of restricting my pocket money.
- The authorities interfere with public
		to the point of making them watch educational movies every week.
separates A from B: 从B分离A
- I have a difficult time separating nails from these sorts of metal.
- My cat is trying to separate meat from her food in the courtyard.
- A gust of wind swept off, separating clothes from baggage.
manifest as sth.: 表现为...
- The stupid marks you make always manifest as injury in others' hearts.
- The scientist developed a model for an atom, in which electrons manifested as baseballs.
- Your careless mistakes may manifest as the loss of money of our company one day.
preoccupations with sth.: 对某事的全神贯注
- I used to admire you for your preoccupations with your homework while I was playing video games.
- Without noticing his preoccupations with homework, I interrupted him from time to time.
- I am proud of my preoccupations with speaking in public.
range from ... to ...: 从...到...的范围
- He wrote a long list of foods, which range from chocolate to sweet, and so on.
- Last night, he told us stories ranging from history to pirates.
- My wife kept complaining about the things about this hotel
		ranging from the equipment to the service.
quite well: 相当地
- I was aware of my bad salary quite well.
- It is no use pretending that you appreciate modern art quite well.
- The result in the experiment agrees with the model quite well.
be hardwired to do sth.: 注定做某事
- Due to similar values and purposes,
		 we are hardwired to stick together in the face of economic crisis.
- His talent in leadership meant that he was hardwired to lead invaded people.
- It is said that Jesus is hardwired to heal the world.
the underlying cause of sth.: 某事的根本原因
- It is fortunate that we have discerned the underlying cause of the epidemic.
- The underlying cause of OCD remains a mystery.
- My leader inquired about the underlying cause of this online accident. 
lie to sb.: 对某人说慌
- Obviously, she is lying to you, for she doesn't want to settle down.
- He is accustomed to lying to his pupils.
- Lying to classmates, he is popular with them.
** summary
OCD, which stands for obsessive compulsive disorder,
	is a psychiatric condition
		which has been frequently mistunderstood as meticulously organizing things,
			keeping your hands clean, etc.
obsessive-compulsive, misunderstood,
It is time to debunk some myths.
Myth one: repetitive or ritualistic behaviors are equal to OCD.
In fact, people affected are not only more meticulous than usual,
	but they can't take control of their obseesive thoughts
		which force them to behave compulsively.
obsessive		
Myth two: the main symptom of OCD is excessive hand wishing.
It can manifest as fears, worries, preoccupations with something that is not necessary.
And it can behave as excessive cleaning and checking, fastidious arrangment of objects, and so on.
Myth three: individuals with OCD don't understand that they are acting irrationally.
Although people suffering from OCD are aware of their obsessions and compulsions quite well,
	they can't avoid these thoughts and actions, whch make them very distressing.
OCD is considered a neurobiogloical disorder
	that associated with low levels of serotonin and three regions of the brain.
Whether these are the sources of OCD or symptons of the disorder remains mystery.
However, there are effective treatments for OCD
	ranging from medications, behavioral therapy, to electroconvulsive therapy and surgery.
Maybe future research into the brain will give us the answers we are looking for.

** summary2
OCD, which stands for obsessive-compulsive disorder,
	is a psychiatric condition
		which has been frequently misunderstood as meticulously organizing things,
			keeping your hands clean, etc.
It is time to debunk some myths.
Myth one: repetitive or ritualistic behaviors are equal to OCD.
In fact, people affected are not only more meticulous than usual,
	but they can't take control of their obsessive thoughts,
		which forces them to behave compulsively.
Myth two: the main symptom of OCD is excessive hand-wishing.
It can manifest as fears, worries, or preoccupations with something that is not necessary.
It can behave as excessive cleaning and checking, fastidious arrangement of objects, and so on.
Myth three: individuals with OCD don't understand that they are acting irrationally.
Although people suffering from OCD are aware of their obsessions and compulsions quite well,
	they can't avoid these thoughts and actions, which make them very distressing.
OCD is considered a neurobiological disorder
	that is associated with low levels of serotonin in three regions of the brain.
Whether these are the sources of OCD or symptoms of the disorder remains a mystery.
However, there are effective treatments for OCD
	ranging from medications and behavioral therapy, to electroconvulsive therapy and surgery.
Maybe future research into the brain will give us the answers we are looking for.

