* 2015-06-26 History vs. Genghis Khan - Alex Gendler
He was one of the most fearsome warlords who ever lived, waging an unstoppable conquest across the Eurasian continent. But was Genghis Khan a vicious barbarian or a unifier who paved the way for the modern world? We'll see in "History vs. Genghis Khan." "Order, order. Now who's the defendant today? Khan!" "I see Your Honor is familiar with Genghis Khan, the 13th century warlord whose military campaigns killed millions and left nothing but destruction in their wake." "Objection. First of all, it's pronounced Genghis Kahn." "Really?" "In Mongolia, yes. Regardless, he was one of the greatest leaders in human history. Born Temüjin, he was left fatherless and destitute as a child but went on to overcome constant strife to unite warring Mongol clans and forge the greatest empire the world had seen, eventually stretching from the Pacific to Europe's heartland." "And what was so great about invasion and slaughter? Northern China lost 2/3 of its population." "The Jin Dynasty had long harassed the northern tribes, paying them off to fight each other and periodically attacking them. Genghis Khan wasn't about to suffer the same fate as the last Khan who tried to unite the Mongols, and the demographic change may reflect poor census keeping, not to mention that many peasants were brought into the Khan's army." "You can pick apart numbers all you want, but they wiped out entire cities, along with their inhabitants." "The Khan preferred enemies to surrender and pay tribute, but he firmly believed in loyalty and diplomatic law. The cities that were massacred were ones that rebelled after surrendering, or killed as ambassadors. His was a strict understanding of justice." "Multiple accounts show his army's brutality going beyond justice: ripping unborn children from mothers' wombs, using prisoners as human shields, or moat fillers to support siege engines, taking all women from conquered towns--" "Enough! How barbaric!" "Is that really so much worse than other medieval armies?" "That doesn't excuse Genghis Khan's atrocities." "But it does make Genghis Khan unexceptional for his time rather than some bloodthirsty savage. In fact, after his unification of the tribes abolished bride kidnapping, women in the Mongol ranks had it better than most. They controlled domestic affairs, could divorce their husbands, and were trusted advisors. Temüjin remained with his first bride all his life, even raising her possibly illegitimate son as his own." "Regardless, Genghis Khan's legacy was a disaster: up to 40 million killed across Eurasia during his descendents' conquests. 10% of the world population. That's not even counting casualties from the Black Plague brought to Europe by the Golden Horde's Siege of Kaffa." "Surely that wasn't intentional." "Actually, when they saw their own troops dying of the Plague, they catapulted infected bodies over the city walls." "Blech." "The accounts you're referencing were written over a hundred years after the fact. How reliable do you think they are? Plus, the survivors reaped the benefits of the empire Genghis Khan founded." "Benefits?" "The Mongol Empire practiced religious tolerance among all subjects, they treated their soldiers well, promoted based on merit, rather than birth, established a vast postal system, and inforced universal rule of law, not to mention their contribution to culture." "You mean like Hulagu Khan's annihilation of Baghdad, the era's cultural capital? Libraries, hospitals and palaces burned, irrigation canals buried?" "Baghdad was unfortunate, but its Kalif refused to surrender, and Hulagu was later punished by Berke Khan for the wanton destruction. It wasn't Mongol policy to destroy culture. Usually they saved doctors, scholars and artisans from conquered places, and transferred them throughout their realm, spreading knowledge across the world." "What about the devastation of Kievan Rus, leaving its people in the Dark Ages even as the Renaissance spread across Western Europe?" "Western Europe was hardly peaceful at the time. The stability of Mongol rule made the Silk Road flourish once more, allowing trade and cultural exchange between East and West, and its legacy forged Russia and China from warring princedoms into unified states. In fact, long after the Empire, Genghis Khan's descendants could be found among the ruling nobility all over Eurasia." "Not surprising that a tyrant would inspire further tyrants." "Careful what you call him. You may be related." "What?" "16 million men today are descended from Genghis Khan. That's one in ever 200." For every great conqueror, there are millions of conquered. Whose stories will survive? And can a leader's historical or cultural signifigance outweigh the deaths they caused along the way? These are the questions that arise when we put history on trial.

