* 2014-04-18 Not all scientific studies are created equal

Studies have shown that taking vitamins is good for your health and bad for your health.
That newly discovered herb can improve your memory or destroy your liver.
Headlines proclaim a promising new cancer treatment and never mention it again.
On a daily basis, we are bombarded with attention-grabbing news, backed up by scientific studies,
	but what are these studies?
How are they performed?
And how do we know whether they're reliable?

When it comes to dietary or medical information,
	the first thing to remember is
		that while studies on animals or individual cells can point the way towards further research,
			the only way to know how something will affect humans
				is through a study involving human subjects.
And when it comes to human studies,
	the scientific gold standard is the randomized clinical trial, or RCT.
The key to RCTs is that the subjects are randomly assigned to their study groups.
They are often blinded to make them more rigorous.
This process attempts to ensure
	that the only difference between the groups is the one the researchers are attempting to study.
For example, when testing a new headache medication,
	a large pool of people with headaches would be randomly divided into two groups,
		one receiving the medication and another receiving a placebo.
With proper randomization,
	the only significant overall difference between the two groups
		will be whether or not they received the medication,
			rather than other differences that could affect results.
Randomized clinical trials are incredible tools,
	and, in fact, the US Food and Drug Administration often requires at least two to be conducted
		before a new drug can be marketed.
		
But the problem is that an RCT is not possible in many cases,
	either because it's not practical or would require too many volunteers.
In such cases, scientists use an epidemiological study,
		which simply observes people going about their usual behavior,
	rather than randomly assigning active participants to control invariable groups.
Let's say we wanted to study whether an herbal ingredient on the market causes nausea.
Rather than deliberately giving people something that might make them nauseated,
	we would find those who already take the ingredient in their everyday lives.
This group is called the cohort.
We would also need a comparison group of people who do not have exposure to the ingredient.
And we would then compare statistics.
If the rate of nausea is higher in the herbal cohort,
	it suggests an association between the herbal supplement and nausea.
Epidemiological studies are great tools to study the health effects of almost anything,
	without directly interfering in people's lives
		or assigning them to potentially dangerous exposures.
		
So, why can't we rely on these studies
	to establish causal relationships between substances and their effects on health?
The problem is that even the best conducted epidemiological studies have inherent flaws.
Precisely because the test subjects are not randomly assigned to their groups.
For example, if the cohort in our herbal study consisted of people
		who took the supplement for health reasons,
	they may have already had higher rates of nausea than the other people in the sample.
Or the cohort group could've been composed of people
	who shop at health food stores and have different diets or better access to healthcare.
These factors that can affect results, in addition to the factor being studied,
	are known as confounding variables.
These two major pitfalls,
			combined with more general dangers, such as conflicts of interest or selective use of data,
		can make the findings of any particular epidemiological study suspect,
	and a good study must go out of its way to prove
		that its authors have taken steps to eliminate these types of errors.
		
But even when this has been done,
	the very nature of epidemiological studies,
			which examine differences between preexisting groups,
			rather than deliberately inducing changes within the same individuals,
		means that a single study can only demonstrate a correlation
				between a substance and a health outcome,
			rather than a true cause and effect relationship.
At the end of the day, epidemiological studies have served as excellent guides to public health,
	alerting us to critical health hazards, such as smoking, asbestos, lead, and many more.
But these were demonstrated through multiple, well-conducted epidemiological studies,
	all pointing in the same direction.
So, the next time you see a headline about a new miracle cure
		or the terrible danger posed by an everyday substance,
	try to learn more about the original study
			and the limitations inherent in any epidemiological study or clinical trial
		before jumping to conclusions.

** expression
herb: a small plant that is used to improve the taste of food, or to make medicine ⇨ spice
liver: a large organ in your body that produces ↑bile and cleans your blood肝脏
vitamin: a chemical substance in food that is necessary for good health
headline: the title of a newspaper report, which is printed in large letters above the report
attention-grabbing: 引人注意的
proclaim: to say publicly or officially that something important is true or exists
promising: showing signs of being successful or good in the future有前途的
dietary: related to the food someone eats
randomized: to choose things in a way that is not carefully controlled or planned in order to do a scientific test
clinical: relating to treating or testing people who are sick临床的, 病房用的
trial: a process of testing to find out whether something works effectively and is safe
rigorous: careful, thorough, and exact
medication: medicine or drugs given to people who are ill
placebo: a harmless substance given to a sick person instead of medicine, without telling them it is not real. 
significant: having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
overall: considering or including everything
epidemiology/epidemiological: the study of the way diseases spread, and how to control them
nausea: the feeling that you have when you think you are going to ↑vomit (=bring food up from your stomach through your mouth) SYN sickness
cohort: technical a group of people of the sage, social class etc, especially when they are being studied
substance: a particular type of solid, liquid, or gas
inherent: a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
flaw: a mistake, mark, or weakness that makes something imperfect SYN defect
confounding: to confuse and surprise people by being unexpected混淆
pitfall: a problem or difficulty that is likely to happen in a particular job, course of action, or activity缺陷
eliminate: to defeat a team or person in a competition, so that they no longer take part in it SYN knock out淘汰
critical: something that is critical is very important because what happens in the future depends on it SYN crucial
hazard: something that may be dangerous, or cause accidents or problems
asbestos: 石棉
Lead: 铅
cure: a medicine or medical treatment that makes an illness go away
--------------------
Studies have shown that + ...: 研究证明
On a daily basis: 每天
be bombarded with sth.: 被某物轰炸
be backed up by sth.: 被某物堆积
point the way towards sth.: 指出去某物/处的路
be assigned to sth./ assign sb. to sth.: 被分派到(组/队)
with headaches: 患头痛
be divided into sth.: 被分成...
a comparison group of ...: ...的对照组
have exposure to sth.: 接触某物
establish causal relationships between sth.(pl.): 建立某物之间的因果关系
in addition to: 除...之外
be combined with sth.: 与...结合
go out of sb's way to do sth.: 给自己带来不便或额外的麻烦去做超出要求的事情
taken steps (to do sth.): 采取措施(去做某事)
induce changes within ...: 在...内部引起变化
demonstrate a correlation between sth.(pl.): 说明了事物间的相互关系
At the end of the day: 最终
alert sb. to sth.: 提醒某人注意某事
