#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Docker 1
** Docker是什么?
Docker是Linux容器,可以理解成轻便的Linux虚拟机,只有需要的应用及其依赖.
** 为什么要使用Docker?
1. 构建和部署管道, 只需要一个命令就可以构建和部署到任何环境
2. 把微服务的基础设施变成可以执行和管理的代码去对待, Dockerfile和run.sh
3. 一旦创建了微服务镜像,确保它部署后永远不会改变
4. 如果在服务器上运行,服务器自身容易发生环境变量的改变,确保其不会发生改变
** Docker-compose
Docker-compose,用来简化Docker的操作
编写yml文件,使用镜像,指定容器内外端口(映射)和环境变量,管理实例(加载/卸载,运行,停止,删除)
** Docker-compose的使用?
使用Docker-compose, 选择image生成实例, 由容器内部的接口映射到容器外部(也就是服务器的接口), 并且提供相应环境变量.
例如 某个微服务 在容器内部是8080, 映射到服务器上是8081, 环境变量指定是正式环境
* 分库分表 1
** 什么是分库分表
分库分表,指把一张表水平分割,分为多个子表,放入不同的数据库内
** 如何切分库分表
水平分库分表: 表结构不变,按每条数据分割,把表分成多个子表,放入或不放入不同的库中
	记录数过多
垂直分库分表: 表的结构改变,按字段分割.
	一条记录的数据太多
** 为什么要分库分表
磁盘, CPU, 内存, 宽带, 连接数不够用了
** 切分策略
1. 范围,根据某字段的范围,比如ID,每百万放一张表
	 缺陷: 写入数据都是写新表,新表写入问题比较大
2. Hash切分, 用ID对总表数取余数, 决定库和表
	 解决了新表写入问题
	 缺陷: Hash算法如果不合理的话,会造成数据分布不均匀的情况. 还有跨表查询和分页的问题
3. 映射表
	 把每行数据的ID和分表映射记录下来
** 分库分表产生的问题
1. 查询数据难度增加,需要先查询映射表,再查询到数据
2. 分布式ID. UUID
3. 分布式事务, 之前的本地事务没法用了
		1. 在业务里避免分布式事务
		2. 用分布式框架sharding-jdbc
4. 跨表关联/分页/排序:
	 1. 在业务代码中分别查询,然后组装数据
	 2. Sharding-Proxy
5. 业务服务器直连, 数据库(代理). 都是把逻辑抽象封装,业务无需关心细节
** 分库分表如何落地?
* Mybatis 1
Mybatis我们项目用的是MybatisGenerator,尽量不写SQL,在Java代码中解决.
比如:用一张新表生成统计数据,定时执行.或者直接把数据存入Elasticsearch中,解决搜索和统计的问题.
** 一级缓存和二级缓存的区别
一级缓存范围在一个SqlSession内部,不是全局缓存
二级缓存是全局
如果二级缓存开启的话,执行顺序是先去二级缓存查询,二级缓存有,则直接返回.没有再去一级缓存查,有直接返回.没有的话,去数据库查.
多表查询的时候,多个sqlSession的时候,另外一个事务未提交的时候,二级缓存不生效.
一个事务已经提交的时候,二级缓存生效有50%的概率.
使用微服务框架的话,二级缓存和一级缓存的变量都可能不在同一台服务器上,容易出现脏读~幻读的现象.不建议使用.
* GC 1
** GCRoot
GCRoot指的是栈中,本地方法栈,方法区.
直接引用的对象,或者间接引用的对象.
没有被引用则会被删除
** GC算法
1. 标记-清理: 标记后直接清理
	 缺: 内存碎片
2. 标记-整理: 标记后删除,再前移动
	 缺: 移动频繁,开销大
3. 复制: 复制到另一块区域
	 缺: 内存开销大
** 实际GC
分为新生区,和老年区
新生区Young: 分为Edan, Survivor0, Survivor1. 因为很多对象生命周期短,所以是8:1:1
老年区Old: Old. 大对象直接出生在Old区,比如大数组.

实际GC:
	新创建的对象实例,在Edan.然后Young GC. 一次Edan+S1复制到S0.再一次GC由Edan+S0复制到S1.每一次复制,年龄+1.
	到Age=6的时候,复制到Old.
	Old满了,产生FullGC.用的是标记清理或标记整理的算法.
	- 如果Edan+S1复制到S0满了,直接进入Old区
* Java 三大特性:封装~继承~多态 0
** Java的多态是什么?
编译类型是一个类,实际类型可能不同(可以是当前类,也可以子类),实际会调用实际类型的方法,造成方法行为的不同.

** Java中变量,代码块,构造器之间的执行顺序是怎样的?
先父子静态变量;再父子静态代码块;先父普通成员变量+代码块+构造器;再子普通成员变量+代码块+构造器.

** final关键字有什么作用?
- 用于类时:类不能被继承,且所有方法也被final修饰
- 用于方法:方法不能被子类重写
- 用于变量:变量一旦初始化,不能被修改

** Integer类会进行缓存吗?
Integer 在-128到127之间,有一个共有的缓存数组. 所以会出现-128到127之间,会相等.

** 抽象类有那些特点?
1. 可以有抽象方法,由子类来实现
2. 不能被实例化
3. 抽象类可以被继承,子类没实现,则继续作为抽象类

** String, StringBuffer和StringBuilder的区别是什么?
String: 不可变,用final修饰,每次变化都会产生新的对象
StringBuilder和StringBuffer: 可变,StringBuffer读写用了synchronized修饰,线程安全.StringBuilder不安全.

** Object类有哪些自带方法?
- 获取class:
  + instance.getClass(): 返回对象运行时的类(实际的类,而不是编译的类)
  + Class.forName("")
	+ 类型+.class
*** hashCode()和equals()
**** hashCode()
	- 对对象做散列,比如: HashMap
	- 快速判断对象是否equals()
**** 为什么hashCode()和equals()方法一起重写?
- 只重写hashCode,会导致相等的对象但内存地址不同,HashMap无法去重
- 只重写equals方法,equals的对象HashCode不同,进入不同的数组,仍然无法去重
*** clone()方法
返回对象的副本,相等,但是存储位置不同
*** toString()方法
返回对象+@+hashCode的十六进制
*** wait()和notify() !!!

*** finalize()
gc调用的,有可能重新被引用,也可能被清理

** 编译型,解释型,和伪编译型语言的区别?
- 编译型: 根据平台编译成机器码,打包成可执行程序.如: C,C++
- 解释型: JavaScript, 对源码逐行解释且立即执行
- Java: 生成与JVM有关的字节码(.class文件),由不同平台的JVM解释执行
	
** Java中访问控制符有哪些?
- private: 类
- default: 包
- protected: 包+子类
- public: 任何

** Java的构造器有哪些特点?
1. 默认无参构造器
2. 可以多个构造器,传参不同

** Java的内部类是怎样的?
静态内部类: new OutClass.InnerClass()
非静态内部类 new OutClass().InnerClass()

** Java的注解是什么?
** 为什么hashCode和equal()方法要一起重写?
** Java有哪些数据类型?
** 包装类型和基本类型的区别是什么?
** 容器
*** HashMap
**** 1.HashMap的基本数据结构
- 1.7: 数组+链表
- 1.8: 数组+(链表|红黑树)
- HashMap用拉链法管理每个节点: 通过Node.next链表
- DEFAULT_INITIAL_CAPCITY=16,数组的默认长度
- 如果指定了capacity,会把这个值改为2的倍数,再创建数组
**** 2.为什么要进行树化?树化的规则?
- 树化意义
	1. TreeNode比Node占空间,尽量使用链表
	2. 防止链表过长,时间复杂度为O(N).红黑树是O(logN)
- 树化规则
	1. 如果链表长度大于TREEIFY_THRESHOLD(默认8)时,调用resize(),扩大数组的容量,减小链表的长度.
	2. 数组容量>=MIN_TREEIFY_CAPACITY(默认64)时,进行树化,把链表转换红黑树
- Note:
	- hash值足够随机的话,会在hash表内按泊松分布.
		扩容因子为0.75时,长度超过8的链表出现概率是千万分之6.树化几率很小.
	- 数组扩容还不到64,链表长度有可能超过8.
**** 3.HashMap的索引是如何计算的?
1. 计算对象的hashCode(),得到原始hash值
2. 调用hashMap的hash()方法进行二次hash,得到二次hash值
3. & (capacity - 1)得到索引,进行位与运算
**** 4.数组容量为何是2的n次幂?
- 计算索引时效率高,2的n次幂可以用位与运算取模
- 扩容时重新计算索引时效率更高
**** 5.为什么要进行二次hash?
- 二次hash(),让hash分布更均匀
- 二次hash也配合了 容量是2的n次幂
- 容量是2的n次幂计算索引效率高,但hash散列性不好,需要二次hash来补偿
**** 6.HashMap的put流程
1. 首次使用时才创建数组
2. 计算索引(桶下标)
3. 桶下标没被占用,则创建Node
4. 桶下标被占用
	 1. TreeNode,红黑树的添加或更新节点
	 2. 普通Node,走链表的添加或更新,如果链表长度大于TREEIFY,走树化逻辑
5. 返回前,检查容量是否超过阀值(扩容因子),超过就进行扩容
**** 7.HashMap如何进行扩容?
什么时候扩容?
	元素数量超过阀值则扩容,扩容的容量是之前的2倍
	容量有上限,最大1<<30,2的30次方
	

**** 8.扩容因子(factor)为何默认是0.75?
空间和时间的平衡
- 大于0.75,节省空间,但是链表长影响性能
- 小于0.75,冲突减少,但是扩容频繁,占用空间
**** 9.HashMap的key
1. hashMap的key可以为null,其他的不行
2. 作为key的对象,必须实现hashCode和equals,并且key的内容不能修改
3. key的hashCode要有良好的散列性
**** 10.总结HashMap1.7和1.8有什么不同?
1. 数据结构
	 - 1.7 数组+链表
	 - 1.8 数组+(链表|红黑树)
2. 初始化方式
	 - 1.7 resize()负责扩容,inflateTable()创建表
	 - 1.8 resize()负责扩容和创建表(为空时)
3. 扩容时机
	 1.7 插入数据之前扩容
	 1.8 插入数据之后
4. 插入方式
	 1.7 头插法
	 1.8 尾插法
* Redis 1
** 基础
*** 1.Redis是什么?
基于内存,并持久化的键值对数据库.

*** 2.Redis过期key是怎么样清理的?
1. 惰性清理: 查询时发现过期了,将key删除
2. 定时清理: 周期性地清理所有DB,从DB的expires字典(key对象,value过期时间)随机取出20个key,删除掉过期的.
		如果超过25%的话,就对整个db清理.没有就下一个.
3. 内存不够时清理:
	 1. 不处理,写入时报错
	 2. 从设置了过期时间的key中,进行淘汰.
	 3. 从所有key中挑选,进行淘汰.
			1. 随机挑选进行淘汰
			2. 根据使用时间最远的淘汰
			3. 使用频率最低的进行淘汰

*** 3.Redis为什么是单线程的?

*** 4.Redis的性能为什么这么高?
1. 完全基于内存,没有磁盘IO,速度快
2. 单线程,没有上下文的切换开销,不用考虑加锁释放锁,也没有死锁
3. 数据结构专门设计的
4. 监听多个IO流,空闲时把线程阻塞掉.有事件时,把阻塞唤醒,轮询发出事件的流,按顺序处理流.
	 单个线程处理多个连接请求,减少网络IO.

*** 5.Linux中IO模型一共有哪些?
*** 6.同步与异步的区别是什么?
*** 7.阻塞与非阻塞的区别是什么?
*** 8.如何解决Redis缓存穿透问题?
故意请求一些Redis不存在的key,请求打到数据库上,导致数据库压力过大.
1. 对传参进行校验,避免一些无效redis请求
2. 对于找不到的key,设置个短期过期时间
3. 把所有可能存在的数据放入到大的map中,通过map进行过滤

*** 9.如何解决Redis缓存击穿问题?
某个热点key过期,导致大量请求转向数据库,数据库压力过大
1. 热点key设置永不过期
2. 对于热点数据加锁(加在数据库上),每次只能取一次,每次等待100ms.

*** 10.如何解决Redis缓存雪崩问题?
短期内大量key失效,所有请求转向数据库
1. 给缓存失效时间加随机值,避免集体失效
2. 搞两个缓存,缓存B比缓存A长一点,如果缓存A失效了,去缓存B找数据,然后用个异步线程来更新缓存A

*** 11.如何解决缓存与数据库的数据一致性问题?
原因:
	1. 多个写请求的执行顺序不同导致脏数据.
	2. 先读了,再更新
	3. 数据库读写分离的,从库需要时间一定时间才能更新
错误解决方案:
	1. 先更新数据库,再更新缓存
	2. 先删除缓存,再更新数据
	3. 先更新数据库,再删除缓存
正确方案:
	1. 写请求之前要先获取分布式锁,才能更新,效率变低了
	2. 先更新数据库,异步删除缓存,删除失败后重试
** 数据结构
HashTable, List列表, Set无序集合, ZSet有序集合
** 持久化
*** 1.Redis的持久化是怎么实现的?
将数据写入磁盘,有两种模式,AOF和RDB
**** AOF持久化
把每次修改命令,添加到aof_buf缓存区的末尾,根据配置每秒写入AOF文件
**** RDB持久化
RDB持久化:把这个时间点的所有键值对生成dump.rdb文件,替换旧的
	fork一个子进程,对键值对遍历,生成rdb文件

*** 2.AOF和RDB的区别是什么?
AOF相当于操作日志,RDB相当于一次快照

*** 3.怎么防止AOF文件越来越大?
周期性AOF重写命令,等于大到一定程度,就去掉一部分操作日志,重新定义初始值.
1+2+3+4+5+6->6+4+5+6

*** 4.Redis持久化策略该如何选择?
RDB持久化时会阻塞Redis的主线程,有一定的IO压力
AOF持久化时aof_buf同步到磁盘有一定I/O压力,而且频率也高很多.
* Spring Boot 1
** 1. 什么是Spring Boot
Spring Boot是Spring组件的一站式解决方案,简化了Spring配置, 提供了各种启动器, 内嵌Web容器.
** 2. Spring Boot有哪些优点?(能实现什么)
1. 可以用@Configuration,再用@Bean工厂管理对象
2. JavaConfig 代替XML
3. 提供各种starter,避免maven大量导入~版本冲突问题, 为配置提供默认值
4. 内嵌Web容器,可以直接做微服务的最小单元
** 3. Spring Boot的核心配置文件哪几个?区别是什么
- application: 用于SB的自动化配置
- bootstrap:
	+ 使用Spring Cloud Config时, 在这个文件中增加外部配置中心的属性,eureka
	+ 一些固定不能被覆盖的属性
	+ 一些密钥
** 4. Spring Boot的核心注解是哪个?由哪些注解组成?
@SpringBootApplication,用于启动类,有三个注解组成:
1. @SpringBootConfiguration: 组合了@Configuration,实现配置文件的功能
2. @EnableAutoConfiguration: 打开自动配置的选项,可以exclude掉某个自动配置(类如数据库自动配置)
3. @ComponentScan: Spring组件扫描
* Spring cloud
* mysql 1
** 什么是关系型数据库?
建立在关系模型基础上的数据库,一对一,一对多,多对多的关系.
** mysql事务
事务就是多个操作打包在一起,要么都执行,要么都不执行
*** ACID
- A: 原子性: 事务是最小单位,要么全部完成,要么不起作用
- C: 一致性: 执行事务前后,数据保持一致.(事务前后两位转账人总额不变,是目的)
- I: 隔离性: 一个用户的事务不被其他事务所干扰
- D: 持久性: 事务被提交后,对于数据的改变是持久的
** 索引类型
主键,唯一索引,普通索引,全文索引
** 索引优化有哪些建议
1. 创建主键索引
2. 创建唯一索引: 避免重复数据的插入,且提升查询效率
3. 创建联合索引: 如果经常多个列一起查询的话. 注意把列的顺序,把更分散的列放在前面.
4. 创建前缀索引: 对于文本类型的列,只对文本前面一部分进行索引
5. 不要使用全文索引代替普通索引: 全文索引,不能用于排序和分组
6. 避免使用过多的列创建索引: 索引列越多,索引的大小就越大,维护代价越高
7. 避免含有Null值的列作为索引列: 含有NULL值的无法B-Tree索引
** Mysql性能优化
1. 慢SQL定位与分析
	 - 使用Mysql慢查询日志
	 - 使用Explain,分析下查询计划,索引的使用情况,是否有做全表扫描
2. 索引~表结构和SQL优化
	 - 索引优化:
		 + 合理设计索引：在WHERE、JOIN、ORDER BY字段上创建索引
		 + 复合索引顺序：如果经常多个列一起查询的话. 注意把列的顺序,把更分散的列放在前面.(最左前缀原则)
		 + 避免过度索引：索引会降低写入性能
		 + ---定期维护索引：重建碎片化严重的索引
	 - 表结构优化: 选择合适的字段类型~避免冗余字段~合适使用范式
	 - SQL优化:
		 + ----------select
		 + 避免使用SELECT *,只查询需要的字段
		 + ----------join
		 + 减少join操作: 必要时冗余字段
		 + 用连接代替子查询,减少查询次数
		 + ----------where
		 + 查询条件不使用函数
		 + 用union来代替or
		 + 使用limit分页: 大数据量使用id > ? limit ? 代替 limit offset, size
3. 架构优化
	 - 读写分离: 读多写少时,可以做读写分离
	 - 分库分表: 垂直分表,把大表分割成小表; 水平分表: 范围分表:按id范围,时间范围; 哈希分表
	 - 数据冷热分离:
	 - 缓存机制: 把热点数据缓存到内存中,redis
** 大数据量(超100万)的批量写会导致什么问题
1. 阻塞其他操作: 占用CPU,内存,磁盘,系统响应慢
2. 磁盘空间不足: 导致写操作失败
3. 日志过大: 写操作时,mysql生成事务日志保证数据的一致性.会导致日志过大,写入速度变慢
4. 死锁: 多个客户端批量写操作,操作数据范围重叠,可能会导致死锁
5. 数据库性能下降:
6. 主从延迟: 主从复制结构. 从服务器在处理写操作时遇到锁冲突,复制进程会被阻塞,导致主从延迟.
--------------------措施
1. 减少批量写的数据量, 分批进行写入
2. 预留足够的磁盘空间和系统资源,确保能正常执行
3. 优化表结构和索引, 提升写操作的性能和效率
4. 使用事务进行批量写操作,确保数据一致性
	 
** Mysql修改大表的表结构会出现什么问题
1. 长时间的阻塞: mysql会将表锁定,阻塞其他用户对表的读写操作,导致应用程序的延迟或响应时间变慢
2. 需要大量的空间和时间: 修改大表结构,需要为该表创建新的临时表复制到临时表里.这个过程需要大量的空间和时间.
3. 数据丢失: 发生错误,可能导致丢失或不一致,最好备份数据库
4. 应用程序问题: 应用程序依赖表的结构,导致应用程序出bug
* 消息队列
* mybatis
* Redis
- 分布式锁
* 项目
* 以往问题
** 高并发处理方式
*** 负载均衡 Nginx
*** 微服务拆分 Spring Cloud
*** 分布式缓存 Redis
*** 异步处理 多线程,MQ
*** 分库分表
** ssm框架的理解
是Spring + Spring MVC + Mybatis三个开源框架的整合
Spring 框架提供:
	- IoC管理对象的创建和依赖关系,通过依赖注入(DI)实现.
	- AOP面向切面编程,用于事务管理,日志等等. 通过代理实现
	- 整合其他框架,充当胶水的作用
Spring MVC框架:
	- 基于MVC的web框架
	- 利用DispatcherServlet处理所有请求
	- 最后再视图解析和数据处理
Mybatis框架是ORM框架,提供一系列功能: 灵活sql,动态sql的支持,缓存机制
** 登录鉴权怎么实现?
1. 用户提交用户名和密码
2. 服务器验证并且生成JWT(JSON Web Token)
3. 返回JWT给客户端
4. 客户端存储JWT(放localStorage或Cookie里)
5. 在Authorization中放JWT
6. 服务器验证JWT签名和有效期		
*** 优点
- 无状态,适合分布式系统
- 存储在客户端上,减少服务端存储压力
- 可以自定义数据
*** 缺点
- Token无法主动失效
- Token过期需要自己去刷新
* AMQP协议
** AMQP 0.9.1 模型解析
*** AMQP是什么
    AMQP: 高级消息队列协议,是网络协议
    application: 客户端应用
    messaging middleware broker:消息中间件代理
*** 消息代理和他们所扮演的角色
message brokers从publisher接收消息, 根据路由规则发送给consumer.
三者可以位于不同的设备上.
*** AMQP 0-9-1 模型简介
    Publisher:发布者
    Publish:发布
    Exchange:交换机
    Routes:路由
    Queue:队列
    Consumes: 消费
    Consumer:消费者

    message acknowledgements: 消息回执,消费者回执给消息代理,才会将消息从队列中删除
    延期操作`死信队列

    AMQP实体: 队列`交换机和绑定
*** AMQP是一个可编程的协议
*** 交换机和交换机类型
    交换机类型和绑定规则
    - Direct exchange 直连交换机
    - Fanout exchange 扇形
    - Topic exchange 主题
    - Headers exchange 头交换机
    Name
    Durability: 消息代理重启后,交换机是否存在
    Auto-delete: 当所有绑定的消息队列都用完了交换机,是否删除
    Arguments:

    状态: 持久durable,暂存transient
**** 默认交换机
	默认交换机: 名字为""的直连交换机.
		每个新建的队列queue自动绑定到默认交换机上, routing key与队列名称相同
**** 直连交换机
    直接交换机,根据消息的路由键,把消息投递给对应队列的.(队列有路由键,消息也有路由键)
**** 扇形交换机
    广播路由
    示例:
      1. 多用户在线游戏排行榜更新全局时间
      2. 体育新闻实时比分
      3. 分布式系统广播状态和配置更新
      4. 群聊分发
**** 主题交换机
    匹配的方式,多播路由.像bilibili订阅更新通知到所有订阅人.
**** 头交换机
    用头而不是路由键,简单来说就是根据头来匹配多个队列
*** 队列
    - Name
    - Durable
    - Exclusive
    - Auto-delete
    - Arguments
*** 队列名称
*** 队列持久化
	Durable: 持久化
*** 绑定
    绑定就是交换机到队列的路线
*** 消费者
    1. push API: 消息投递给应用
					订阅一个队列,可以注册多个消费者,也可以独享
    2. pull API: 应用主动获取消息
*** 消息确认
两种模式:
    1. 发送给应用后立即删除
    2. 受到回执再删除
*** 拒绝消息
    注意不要在一个消费者无限循环
*** Negative Acknowledgements
*** 预取消息
*** 消息属性和有效载荷(消息主体)
    消息(Message):属性,有效载荷(Payload:实际携带的数据)-不透明
*** 消息确认
*** AMQP 0-9-1方法
    交换机方法:
    - exchange.declare
    - exchange.declare-ok
    - exchange.delete
    - exchange.delete-ok
*** 连接
    tcp场连接,TLS(SSL)保护
*** 通道
    channels共享一个TCP连接的多个轻量化连接
*** 虚拟主机
*** AMQP是可扩展的
*** AMQP 0.9.1 客户端生态系统
** AMQP 0.9.1 快速参考指南
   客户端:消费者
   服务器端:生产者
   服务器:mq
*** Basic
    - basic.ack 确认消息
    - basic.cancel->cancel-ok 结束队列消费者
    - basic.consume->consume-ok  启动队列消费者
    - basic.deliver 消费者消息通知给客户端
    - basic.get 直接访问队列
    - basic.nack
    - basic.publish 发送单条消息
    - basic.qos->qos-ok 指定服务器端质量
    - basic.recover 重新投递未被确认的消息
    - basic.recover-async
*** Channel
    - channel.close->close-ok
    - channel.flow->启用/禁用对端流
    - channel.open->open-ok
*** Confirm
    - .select->select-ok 设置信道确认回执
*** Exchange
    - .bind 两个交换机进行绑定
    - declare->declare-ok 验证交换机是否存在,不存在就创建
    - delete->delete-ok 删除
    - unbind 解除绑定
*** Queue
    - bind: 队列绑定到交换机
    - declare->declare-ok 声明队列,不存在就创建
    - purge->purge-ok 清空队列
    - unbind 解除绑定  
*** Tx
    - commit->commit-ok 事务提交
    - rollback->rollback-ok 终止当前事物
    - select->select-ok 选择事务模式
* @Async: 实现异步方法调用
把任务分解成多个子任务,在后台或者其他线程去执行子任务,提高程序性能和响应能力

** @Async简介
是Spring提供的注解,标记方法为异步执行的方法.告诉Spring调用这个方法时,放到线程池中异步执行,而不是等待方法完成.
--------------------工作原理
调用被注解的方法时,Spring把方法的执行转移到线程池的一个线程中执行.
执行完成后,方法的返回值通过Future封装,获取返回结果.
--------------------优势
- 代码简化: 把异步执行的代码与业务逻辑分离
- 网络请求时,快速响应,提高系统的并发处理能力
- 耗时计算时,在后台执行计算过程,避免阻塞主线程,提高系统响应速度
- 可以同时执行多个任务,节省处理时间
** @Async源码解析
首先Spring要启用异步支持,Spring扫描容器的Bean,检查方法是否有@Async.
如果有@Async,把它封装成代理对象,实际是一个可执行的异步任务.
调用这个方法时,把这个异步任务放到线程池里去执行,返回Future对象.

** 异步方法与事务的关系
异步方法可以声明事务,但是事务只跟异步方法有关和主方法是无关.
需要非常注意逻辑的正确性,还有数据的一致性

** Async异常处理
直接设置异步方法的返回参数为Future<String>,使用Future.get(),处理异常.

** 最佳实践和注意事项
- 尽量简单,不涉及事务
- 执行时间不要过长,导致线程资源占用太多
- 注意和其他业务的一致,保证执行顺序和结果正确
* Spring
** Spring Bean的生命周期
** Spring AOP是怎么实现的?
Spring AOP可以设置切面,比如切一类方法,执行这些方法时,执行这些代码,比如:日志,事务啊.
三种实现方法: 静态代理,JDK的Proxy类实现动态代理,CGLIB实现动态代理

*** 静态代理
代理类去实现接口,并且内部变量为被代理类的. 外部执行方法时,代理类调用成员变量被代理类的方法,并且执行自身额外的操作.

*** JDK动态代理
1. 通过Proxy.newProxyInstance创建一个代理类()
2. 调用代理类,会执行InvocationHandler的invoke()方法.
	 可以做一些额外的操作,再调用目标类的方法(method.invoke(object, args))

*** CGLIB动态代理
创建一个代理类,继承原来的类,重写父类的方法(在interceptor里面). 缺点不能有final和private修饰的方法.

*** 三者的区别
1. 静态代理:直接就是一个实实在在的一个对象
2. 动态代理:调用处理类需要实现InvocationHandler,采用反射代理的方式,有点慢但灵活
3. cglib代理:直接生成类字节码(用新的子类继承被代理的类),比反射快,需要重写方法,所以不能有final~private修饰词
*** Spring中代理方式
1. 如果目标对象实现了接口,默认是JDK动态代理,可以强制使用CGLIB实现AOP
2. 如果目标对象没实现接口,必须用CGLIB
3. Spring会自动在JDK和CGLIB之间转换

** Spring IOC是什么?
IOC是控制反转的意思.假如对象A依赖对象B,对象A需要对象B时,需要声明创建对象B的实例.
有了IOC后,由Spring IOC容器负责对象B的创建和销毁,对象B创建后放在容器里,对象A需要的时候去取.
是由依赖注入技术实现的.

*** Spring IOC是怎么解决循环依赖问题的?
只能解决属性注入的循环依赖问题,无法解决构造器之间的循环依赖.

1->一~二~三都没有->创建1->把1添加到三->依赖注入2->一~二~三都没有->创建2->把2添加到3->依赖注入1->从三获取到,把1添加到二->2依赖注入成功->2添加到一->1依赖注入成功->把1添加一->结束.

*** Bean的生命周期是怎么样的?
1. Bean的实例化阶段: 调用类的构造器创建一个Bean实例
2. 属性赋值阶段: 在populateBean()中,对Bean的各项属性进行赋值
3. Bean的初始化阶段: 调用用花自定义自定义的init-Method
4. Bean的销毁阶段: 可以自定义destoryMethod(),Bean被销毁时被调用

*** BeanFactory和FactoryBean有什么区别?
BeanFactory定义IOC容器的接口,具体实现有DefaultListableBeanFactory~XmlBeanFactory~ApplicationContext等.

FactoryBean则是获取Bean对象的一个接口.

** Springboot启动过程
*** 构造SpringApplication实例
会确定WebApplicationType,是reactive web,还是servlet web
*** 执行run()方法
创建stopwatch,统计run()方法耗时
处理环境参数, java -jar xxx.jar jvm参数
*** 创建applicationContext
applicationContext也就是ioc容器
*** 执行prepareContext()方法
加载所有的Bean
*** 执行refreshContext()方法
*** afterRefresh()方法
* Mysql索引
mysql索引是一种数据结构,用来加快数据库查询的速度.
	类似于书籍的索引,通过存储指向数据行的指针,快速定位和访问表中的特定数据.
	实际上,索引也是一张表,该表保存了主键和索引字段,指向实体表的记录
单列索引和组合索引:
	- 单列索引, 一个索引只包含单个列,一个表可以有多个单列索引
	- 组合索引, 一个索引包含多个列
索引注意点:
	- 索引要额外占用空间
	- 对表修改时,索引也要维护,可能影响性能
	- 过多或不合理的索引会导致性能下降,谨慎选择
** 普通索引
在大型表中搜索时,通过使用索引,MySQL可以直接定位到满足查询条件的数据行,而不需要逐行扫描整个表
