#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

*  Lesson 80 The Crystal Palace
#+begin_verse
How many people visited the Great Exhibition of 1851?

Perhaps the most extraordinary building of the nineteenth century was the Crystal Palace,
	which was built in Hyde Park for the Great Exhibition of 1851.
The Crystal Palace was different from all other buildings in the world,
	for it *was made of* iron and glass.
It was one of the biggest buildings *of all time*
	and a lot of people from many countries came to see it.
A great many goods were sent to the exhibition from various parts of the world.
There was also a great deal of machinery *on display*.
The most wonderful piece of machinery on show was Nasmyth's steam hammer.
Though in those days, traveling was not as easy as it is today,
	steam boats carried thousands of visitors across the Channel from Europe.
On arriving in England, they were taken to the Crystal Palace by train.
There were six million visitors *in all*,
	and the profits from the exhibition were used to build museums and colleges.
Later, the Crystal Palace was moved to South London.
It remained one of the most famous buildings in the world until it was burnt down in 1936.

#+end_verse

** words
palace [ˈpæləs] n.宫殿
extraordinary [ɪkˈstrɔrd(ə)nˌeri] adj.不平常的,非凡的
exhibition [ˌeksɪˈbɪʃ(ə)n] n.展览
iron [ˈaɪrn] n.铁
various [ˈveriəs] adj.各种各样的
machinery [məˈʃinəri] n.机器
display [dɪˈspleɪ] n.蒸汽
profit [ˈprɑfɪt] n.利润
college [ˈkɑlɪdʒ] n.学院

** DONE 单词造句
CLOSED: [2023-09-18 Mon 21:40]
palace n.
1. They have been visiting the palace for a week.
2. Instead of the king, the palace takes its name from its builder.
3. They were afraid that the palace would be burnt down by the people.
4. 'Get out of here.' A security guard in front of the palace said.
5. The farmer carried ten tons of corn stalks to the palace.
extraordinary adj.
1. What an extraordinary women she is.
2. They have been expecting an extraordinary crop this year.
3. Leo pointed out that it was an extraordinary idea.
4. It must be the only extraordinary house in the village.
5. During this time, they will give five extraordinary performances.
exhibition n.
1. On arriving the exhibition, my wife begun to take a great many photographs.
2. My wife has not only enjoyed the exhibition, but the garden as well.
3. She is losing her temper in the exhibition.
4. She sometimes goes to the exhibition on Weekends.
5. She went to the exhibition last week.
iron n.
1. They have successfully turned gold into iron.
2. Rachel, whose aunt turned gold into iron, is crying.
3. The factory has been turning gold into iron.
4. He managed to escape with an abandoned iron bar.
5. He used to wander with an abandoned iron bar around there.
various adj.
1. I'm going to read various books in office hours.
2. We all were put to shame by him who had read various books in his spare time.
3. It occured to me that he knew various actors in the society.
4. The player has met various actors in the wedding.
5. After having read various books about technology, she turned her attention to education.
machinery n.
1. There is an expensive piece of machinery.
2. Is there any piece of machinery?
3. The working machinery is made of iron and glasses.
4. He would take charge of the machinery.
5. He was talking to the manager of a local factory where the machinery was made.
display n. on show/on display
1. Machinery like this should be on display at 8 o'clock.
2. The assistant who cleaned the window did not like the way the clothes were on display.
3. The machinery had been on display before the museum was closed.
4. It is said that various luxuries would be on display in the exhibition.
5. He saw an expensive piece of machinery be on display in the exhibition.
steam n.
1. Steam engine broke down so much that it can't be repaired.
2. As soon as the water boils, it turned into steam.
3. It is no use pretending that you had invented the steam engine.
4. He repaired the steam engine with satisfaction.
5. My wife urged me to have the steam engine repaired.
profit n. make a profit
1. The moment the company makes a profit, he will get a good salary.
2. The moment you finish the work, I will offer you a great deal of money.
3. Our company will be making a profit next year.
4. Our company will have made a profit by the day of this year.
5. Our company will have been making a profit during the next year.
college n. go to college
1. Why don't you go to college?
2. She said that she wouldn't go to college.
3. She had hardly gone to college when her brother was born.
4. She had no sooner gone to college than her brother was born.
5. If she had gone to college, she would have been more successful.
** DONE 反复听电影片段
CLOSED: [2023-09-19 Tue 21:54]
** DONE Pattern Drill 写+读
CLOSED: [2023-09-19 Tue 21:59]
1. 
		1t: sweet oranges - Spanish
		s1: These oranges aren't sweet enough.
		s2: Get some Spanish oranges. They'd be much sweeter.
	 - hard brushes - nylon
		 These brushes aren't hard enough.
		 Get some nylon brushes. They'd be much harder.
	 - strong bags - leather
		 These bags aren't strong enough.
		 Get some leather bags. They'd be much stronger.
	 - warm socks - woollen
		 These socks aren't warm enough.
		 Get some woollen socks. They'd be much warmer.
	 - cheap toys - plastic
		 These toys aren't cheap enough.
		 Get some plastic toys. They'd be much cheaper.
2. 
		2t: dirt on the floor
		s1: Was there much dirt on the floor?
		s2: No, it wasn't any dirtier than usual.
	 - noise in  the classroom
		 Was there much noise in the classroom.
		 No, it wasn't any noiser than usual.
	 - mist on  the hills
		 Was there much mist on the hills?
		 No, it wasn't any mistier than usual.
	 - wind on  the island
		 Was there much wind on the island?
		 No, it wasn't any windier than usual.
	 - clouds in  the sky
		 Was there much clouds in the sky?
		 No, it wasn't any cloudier in the sky.
3. 
		3t: attractive
		s1: She's the most attractive person I've ever met.
		s2: She's not as attractive as you are!
	 - interesting
		 She's the most interesting person I've ever met.
		 She's not as interesting as you are!
	 - delightful
		 She's the most delightful person I've ever met.
		 She's not as delightful as you are!
	 - hard-working
		 She's the most hard-working person I've ever met.
		 She's not as hard-working as you are!
	 - understanding
		 She's the most understanding person I've ever met.
		 She's not as understanding as you are!
4. 
		4t: drive - quickly
		s1: He drove as quickly as he could.
		s2: Yes, he couldn't have driven any more quickly.
	 - stay - long
		 He stayed as long as he could.
		 Yes, he couldn't have stayed any longer.
	 - walk - far
		 He walked as far as he could.
		 Yes, he couldn't have walked any farther.
	 - write - fast
		 He wrote as fast as he could.
		 Yes, he couldn't have written any faster.
	 - fight - hard
		 He fought as hard as he could.
		 Yes, he couldn't have fought any harder.
** DONE 给自己讲解
CLOSED: [2023-09-19 Tue 22:01]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-09-18 Mon 21:40]
be made of
1. The editor asked the journalist to figure out what the palace is made of.
2. The palace should have been made of iron and wood.
3. The palace may only be made of iron and glasses.
4. The machinery may have been made of iron and wood.
5. It's the bridge which is made of iron, not wood.
of all time
1. I might have fallen into love with her of all time.
2. He can't be the best player in the world of all time.
3. He remains the best player in the world of all time.
4. He was able to swim of all time.
5. He was regarded as one of the greatest poet of all time.
in all
1. There are two cups of milk tea in all.
2. It's said that there were 6,000 car parked in the street in all.
3. There might be 300 people in the middle of the exhibition in all.
4. It is said that there were 300 guards in front of the palace.
5. How many people stood here in all?
** DONE 跟读至背诵
CLOSED: [2023-09-19 Tue 22:01]
** DONE Ask me if 写+读
CLOSED: [2023-09-19 Tue 21:50]
1. The Crystal Palace was built in the nineteenth century. When/What
	 When was the Crystal Palace built?
	 What was built in the nineteenth century?
2. It was built in Hyde Park. Where
	 Where was it built?
3. It was built for the Great Exhibition of 1851. Why/What
	 Why was it built?
	 What was built for the Great Exhibition of 1851?
4. It was different from all other buildings in the world. What/How
	 What was it different from?
	 How was it different from all other buildings in the world?
5. It was made of iron and glass. What
	 What was it made of?
6. A lot of people came to see it. How many
	 How many people came to see it?
7. They came from many countries. Where
	 Where did they come from?
8. A great many goods were sent to the exhibition. How many
	 How many goods were sent to the exhibition?
9. They came from various parts of the world. Where
	 Where did they come from?
** DONE 摘要写作
CLOSED: [2023-09-19 Tue 22:17]
The Crystal Palace, which was built for the Great Exhibition of 1851,
	was different from all others in the world
	because it was made of iron and glass.
Goods from various parts of the world were on display as well as a great deal of machinery.
So many visitors came by boat and train
	that it was possible to build colleges and museums from the profits.
After the exhibition, the Crystal Palace was moved to South London,
	where it remained util it was burnt down in 1936.

The Crystal Palace was built for the Great Exhibition of 1851.
Made of iron and glass, it was different from all other buildings.
There were not only goods from various parts of the world on display
	but there was a great deal of machinery as well.
This attracted many visitors who travelled by boat and train.
Later, the colleges and museums were built from the profits.
The Crystal Palace was moved to South London and it remained util 1936, when it was burnt down.

** DONE tell the story 口语
CLOSED: [2023-09-19 Tue 22:19]
** Topics for discussion
