#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 73 The record-holder
#+begin_verse
Did the boy go where he wanted to?

Children who *play truant from school* are unimaginative.
A quiet day's fishing, or eight hours in a cinema seeing the same film *over and over again*,
	is usually as far as they get.
They have all *been put to shame* by a boy who, while playing truant, travelled 1,600 miles.
He *hitchhiked to Dover* and, towards evening, went into a boat to find somewhere to sleep.
When he woke up next morning,
	he discovered that the boat had, *in the meantime*, travelled to Calais.
No one noticed the boy as he crept off.
From there, he hitchhiked to Paris in a lorry.
The driver gave him a few biscuits and a cup of coffee and left him just outside the city.
The next car the boy stopped did not take him into the centre of Paris as he hoped it would,
	but to Perpignan on the French-Spanish border.
There he was picked up by a policeman and sent back to England by the local authorities.
He has surely set up a record for the thousands of children who dream of evading school.
#+end_verse

* Lesson 74 Out of the limelight
#+begin_verse
Why was their disguise ‘too perfect’?

An ancient bus stopped by a dry river bed and *a party of* famous actors and actresses got off.
Dressed in dark glasses and old clothes,
	they had *taken special precautions* so that no one should recognize them.
But as they soon discovered, disguises can sometimes be too perfect.
'This is a wonderful place for a picnic,' said Gloria Gleam.
'It couldn't be better, Gloria,' Brinksley Meers agreed.
'No newspaper men, no film fans!
*Why don't we* come more often?'
Meanwhile, two other actors, Rockwall Slinger and Merlin Greeves,
	had *carried two large food baskets to* a shady spot under some trees.
When they had all *made themselves comfortable*, a stranger appeared.
He looked very angry.
'Now you get out of here, all of you!' he shouted.
'I'm sheriff here.
Do you see that notice? It says "No Camping" -- in case you can't read!'
'Look, sheriff,' said Rockwall, '*don't be too hard on us*.
I'm Rockwall Slinger and this is Merlin Greeves.'
'Oh, is it?' said the sheriff with a sneer.
'Well, I'm Brinksley Meers, and my other name is Gloria Gleam.
Now you *get out of here* fast!'
#+end_verse

* Lesson 75 SOS
#+begin_verse
How did the woman get help?

When a light passenger plane *flew off course* some time ago,
	it crashed in the mountains and its pilot was killed.
The only passengers, a young woman and her two baby daughters, were unhurt.
It was the middle of winter.
Snow lay thick on the ground.
The woman knew that the nearest village was miles away.
When it grew dark,
	she turned a suitcase into a bed and put the children inside it,
	*covering them with* all the clothes she could find.
During the night, it got terribly cold.
The woman kept as near as she could to the children and even tried to get into the case herself,
	but it was too small.
Early next morning, she heard planes passing overhead and wondered how she could *send a signal*.
Then she had an idea.
She *stamped out* the letters 'SOS' in the snow.
Fortunately, a pilot saw the signal and sent a message by radio to the nearest town.
*It was not long before*
	a helicopter *arrived on the scene* to rescue the survivors of the plane crash.
#+end_verse

* Lesson 76 April Fool's Day
#+begin_verse
What was the joke?

'To end our special news bulletin,' said the voice of the television announcer,
	'we're going over to the macaroni fields of Calabria.
Macaroni has been grown in this area for over six hundred years.
Two of the leading growers, Giuseppe Moldova and Riccardo Brabante, tell me
	that they have been expecting a splendid crop this year
		and harvesting has begun earlier than usual.
Here you can see two workers who,
	between them, have just finished cutting three cartloads of golden brown macaroni stalks.
The whole village has been working day and night
	gathering and threshing this year's crop before the September rains.
On the right, you can see Mrs. Brabante herself.
She has been helping her husband for thirty years now.
Mrs .Brabante is talking to the manager of the local factory where the crop is processed.
This last scene shows you what will happen *at the end of the harvest*:
	the famous Calabrian macaroni-eating competition!
Signor Fratelli, the present champion, has won it every year since 1991.
And that ends our special bulletin for today, Thursday, April 1st.
We're now going back to the studio.'
#+end_verse

* Lesson 77 A successful operation

#+begin_verse
Did the doctors find out how the woman died?

The mummy of an Egyptian woman who died in 800 B.C. has just had an operation.
The mummy is that of Shepenmut who was once a singer in the Temple of Thebes.
As there were strange marks on the X-ray plates taken of the mummy,
	doctors have been trying to find out whether the woman died of a rare disease.
The only way to do this was to operate.
The operation, which lasted for over four hours,
		proved to be very difficult because of the hard resin which covered the skin.
The doctors removed a section of the mummy and sent it to a laboratory.
They also found something which the X-ray plates did not show:
	a small wax figure of the god Duamutef.
This god which has the head of a cow was normally placed inside a mummy.
The doctors have not yet decided how the woman died.
They feared that the mummy would fall to pieces when they cut it open,
	but fortunately this has not happened.
The mummy successfully survived the operation.
#+end_verse

* Lesson 78 The last one?
#+begin_verse
For how long did the writer give up smoking?

After reading an article entitled 'Cigarette Smoking and Your Health'
	I lit a cigarette to *calm my nerves*.
I smoked with concentration and pleasure as I *was sure that* this would be my last cigarette.
For a whole week I did not smoke at all and during this time, my wife suffered terribly.
I had all the usual symptoms of someone giving up smoking: a bad temper and an enormous appetite.
My friends *kept on offering me cigarettes and cigars*.
They *made no effort to hide* their amusement
	whenever I produced *a packet of* sweets from my pocket.
After seven days of this I went to a party.
Everybody around me was smoking and I felt extremely uncomfortable.
When my old friend Brian *urged me to accept* a cigarette, it was more than I could bear.
I took one guiltily, lit it and smoked with satisfaction.
My wife *was delighted that* things had *returned to normal* once more.
Anyway, as Brian pointed out, it is the easiest thing in the world to give up smoking.
He himself has done it lots of times!
#+end_verse

* Lesson 79 By air 

#+begin_verse
Why did the plane turn back?

I used to travel by air *a great deal* when I was a boy.
My parents used to live in South America and I used to fly there from Europe in the holidays.
A flight attendant would *take charge of* me and I never had an unpleasant experience.
I *am used to travelling* by air and only on one occasion have I ever *felt frightened*.
After *taking off*, we were flying low over the city and slowly *gaining height*,
	when the plane suddenly turned round and flew back to the airport.
While we were waiting to land,
	a flight attendant told us to keep calm and to get off the plane quietly
		as soon as it had *touched down*.
Everybody *on board* was worried
	and we *were curious to find out* what had happened.
Later we learnt that there was a very important person on board.
The police had been told that *a bomb had been planted* on the plane.
After we had landed, the plane was searched thoroughly.
Fortunately, nothing was found and five hours later we were able to take off again.
#+end_verse

*  Lesson 80 The Crystal Palace
#+begin_verse
How many people visited the Great Exhibition of 1851?

Perhaps the most extraordinary building of the nineteenth century was the Crystal Palace,
	which was built in Hyde Park for the Great Exhibition of 1851.
The Crystal Palace was different from all other buildings in the world,
	for it *was made of* iron and glass.
It was one of the biggest buildings *of all time*
	and a lot of people from many countries came to see it.
A great many goods were sent to the exhibition from various parts of the world.
There was also a great deal of machinery *on display*.
The most wonderful piece of machinery on show was Nasmyth's steam hammer.
Though in those days, traveling was not as easy as it is today,
	steam boats carried thousands of visitors across the Channel from Europe.
On arriving in England, they were taken to the Crystal Palace by train.
There were six million visitors *in all*,
	and the profits from the exhibition were used to build museums and colleges.
Later, the Crystal Palace was moved to South London.
It remained one of the most famous buildings in the world until it was burnt down in 1936.
#+end_verse

* Lesson 81 Escape
#+begin_verse
Why did the prisoner attack the driver?

When he had killed the guard, the prisoner of war quickly dragged him into the bushes.
Working rapidly in the darkness, he soon *changed into* the dead man's clothes.
Now, dressed in a blue uniform and with a rifle over his shoulder,
	the prisoner marched boldly *up and down* in front of the camp.
He could hear shouting in the camp itself.
Lights were blazing and men were running here and there:
	they had just *discovered that* a prisoner had escaped.
At that moment, a large black car with four officers inside it, stopped at the camp gates.
The officers got out and the prisoner *stood to attention* and saluted as they passed.
When they had gone, the driver of the car came towards him.
The man obviously wanted to talk.
He was rather elderly with grey hair and clear blue eyes.
The prisoner felt sorry for him, but there was nothing else he could do.
As the man came near,
	the prisoner *knocked him to the ground* *with a sharp blow*.
Then, jumping into the car, he drove off as quickly as he could.
#+end_verse

* Lesson 82 Monster or fish?
#+begin_verse
What was the monster called?

Fishermen and sailors sometimes *claim to have seen* monsters in the sea.
Though people have often *laughed at* stories told by seamen,
	*it is now known that*
		many of these 'monsters' which have *at times* been sighted are simply strange fish.
Occasionally, unusual creatures are washed to the shore,
	but they are rarely caught *out at sea*.
Some time ago, however, a peculiar fish was caught near Madagascar.
A small fishing boat was carried miles out to sea by the powerful fish as it pulled on the line.
Realizing that this was no ordinary fish,
	the fisherman made every effort not to damage it *in any way*.
When it was eventually brought to shore,
	*it was found to be* over thirteen feet long.
It had a head like a horse,
	big blue eyes, shining silver skin, and a bright red tail.
The fish, which has since been sent to a museum
		where it is being examined by a scientist,
	is called an oarfish.
Such creatures have rarely been seen alive by man as they live at *a depth of* six hundred feet.
#+end_verse

* Lesson 83 After the elections

#+begin_verse
Why did Patrick keep on asking the same question?

The former Prime Minister, Mr. Wentworth Lane, was defeated in the recent elections.
He is now retiring from political life and has gone abroad.
My friend, Patrick, has always been a fanatical opponent of Mr. Lane's Radical Progressive Party.
After the elections, Patrick went to the former Prime Minister's house.
When he asked if Mr. Lane lived there,
	the policeman *on duty* told him that since his defeat, the ex-Prime Minister had gone abroad.
*On the following day*, Patrick went to the house again.
The same policeman was just walking slowly past the entrance,
	when Patrick asked the same question.
Though a little suspicious this time, the policeman gave him the same answer.
The day after, Patrick went to the house once more and asked exactly the same question.
This time, the policeman lost his temper.
'I told you yesterday and the day before yesterday,' he shouted,
'Mr. Lane was defeated in the elections.
He has retired from political life and gone to live abroad!'
'I know,' answered Patrick, 'I *love to hear* you say it!'
#+end_verse

* Lesson 84 On strike

#+begin_verse
Who will be driving the buses next week?

Busmen have decided to *go on strike* next week.
The strike *is due to* begin on Tuesday.
No one knows how long it will last.
*The busmen have stated*
	that the strike will continue
		until general *agreement is reached about* pay and working conditions.
Most people believe that the strike will last for at least a week.
Many owners of private cars are going to offer 'free rides' to people on their way to work.
This will *relieve pressure* on the trains *to some extent*.
Meanwhile, a number of university students have *volunteered to drive* buses while the strike lasts.
All the students are expert drivers,
	but before they drive any of the buses, they will have to *pass a special test*.
The students are going to *take the test* in two days' time.
Even so, people are going to find it difficult to get to work.
But so far, the public has *expressed its gratitude to* the students in letters to the Press.
*Only one or two people have objected* that the students will drive too fast!
#+end_verse

* Lesson 85 Never too old to learn

#+begin_verse
How long has Mr. Page been teaching?

I have just received a letter from my old school,
	*informing me* that my former headmaster, Mr. Stuart Page, will be retiring next week.
Pupils of the school, old and new, will be sending him a present to *mark the occasion*.
All those who have *contributed towards* the gift
	will sign their names in a large album which will be sent to the headmaster's home.
We shall all *remember Mr. Page for* his patience and understanding
	and for the kindly encouragement he gave us when we went so unwillingly to school.
A great many former pupils will be attending a farewell dinner *in his honour* next Thursday.
*It is a curious coincidence that* the day before his retirement,
	Mr. Page will have been teaching for *a total of* forty years.
After he has retired, he will *devote himself to gardening*.
For him, this will be an entirely new hobby.
But this does not matter,
	for, as he has often remarked, one is never too old to learn.
#+end_verse

* Lesson 86 Out of control
#+begin_verse
What was the danger?

As the man tried to swing the speedboat round, the steering wheel *came away* in his hands.
He waved desperately to his companion, who had been water skiing for the last fifteen minutes.
Both men had hardly had time to realize what was happening
	when they were thrown violently into the sea.
The speedboat had struck a buoy,
	but it continued to move very quickly across the water.
Both men had just begun to swim towards the shore,
	when *they noticed with dismay* that the speedboat was moving *in a circle*.
It now came straight towards them *at tremendous speed*.
In less than a minute, it roared past them only a few feet away.
After it had passed,
	they swam on as quickly as they could because they knew that the boat would soon return.
They had just had enough time to swim out of danger
	when the boat again completed a circle.
On this occasion, however, it had slowed down considerably.
The petrol had nearly all *been used up*.
*Before long*, the noise dropped completely and the boat began to drift gently across the water.
#+end_verse

* Lesson 87 A perfect alibi
#+begin_verse
What was wrong with the man's story?

'At the time the murder was committed,
	I was travelling on the 8 o'clock train to London,' said the man.
'Do you always catch such an early train?' asked the inspector.
'Of course I do,' answered the man.
'I must be at work at 10 o'clock.
My employer will confirm that I was there on time.'
'Would a later train get you to work on time?' asked the inspector.
'I suppose it would, but I never catch a later train.'
'At what time did you arrive at the station?'
'At ten to eight.
I bought a paper and waited for the train.'
'And you didn't notice anything unusual?'
'Of course not.'
'I suggest,' said the inspector, 'that you are not telling the truth.
I suggest that you did not catch the 8 o'clock train,
	but that you caught the 8.25 which would still get you to work on time.
You see, on the morning of the murder, the 8 o'clock train did not run at all.
It broke down at Ferngreen station and was taken off the line.'
#+end_verse

* Lesson 88 Trapped in a mine

#+begin_verse
Why is the rescue taking so long?

Six men have been trapped in a mine for seventeen hours.
If they are not brought to the surface soon they may *lose their lives*.
However, rescue operations are proving difficult.
If explosives are used, vibrations will *cause the roof of the mine to collapse*.
Rescue workers are therefore drilling a hole on the north side of the mine.
They intend to bring the men up *in a special capsule*.
If there had not been *a hard layer of* rock beneath the soil,
	they would have completed the job in a few hours.
*As it is*, they have been drilling for sixteen hours and they still have a long way to go.
Meanwhile, a microphone, which was lowered into the mine two hours ago,
	has *enabled the men to keep in touch with* their closest relatives.
Though they are *running out of* food and drink,
	the men are cheerful and confident that they will get out soon.
They have been told that rescue operations are progressing smoothly.
If they knew how difficult it was to drill through the hard rock, they would *lose heart*.
#+end_verse

* Lesson 89 A slip of the tongue

#+begin_verse
Who made the only funny joke that evening and why?

People will *do anything to see* a free show ---- even if it is a bad one.
When *the news got round*
	that *a comedy show* would be presented at our local cinema by the P. and U. Bird Seed Company,
	we all rushed to see it.
We had to queue for hours to get in and there must have been several hundred people present
	just before the show began.
Unfortunately, the show was one of the dullest we have ever seen.
Those who failed to get in need not have *felt disappointed*,
	as many of the artistes who should have appeared did not come.
The only funny things we heard that evening
	came from the advertiser *at the beginning of the programme*.
He was obviously very nervous and for some minutes stood awkwardly before the microphone.
As soon as he opened his mouth, everyone *burst out laughing*.
We all know what the poor man should have said,
	but what he actually said was: 'This is the Poo and Ee Seed Bird Company.
Good ladies, evening and gentlemen!’
#+end_verse

* Lesson 90 What's for supper?

#+begin_verse
What kind of fish are they?

Fish and chips has always been a favourite dish in Britain,
	but as the oceans have been overfished, fish has become more and more expensive.
So it comes as a surprise to learn that giant fish are terrifying the divers on North Sea oil rigs.
Oil rigs have to be repaired frequently
	and divers, who often have to work in darkness a hundred feet under water,
		have *been frightened out of their wits* by giant fish bumping into them as they work.
Now they have had special cages made to *protect them from* these monsters.
The fish are not sharks or killer whales,
	but favourite eating varieties like cod and skate
		which grow to unnatural sizes, sometimes as much as twelve feet *in length*.
Three factors have caused these fish to grow so large:
	the warm water round the hot oil pipes under the sea;
	the plentiful supply of food thrown overboard by the crews on the rigs;
	*the total absence of* fishing boats around the oil rigs.
*As a result*, the fish just eat and eat and grow and grow in the lovely warm water.
Who eats who?
#+end_verse

* Lesson 91 Three men in a basket

#+begin_verse
Where was the station's Commanding Officer?

A pilot noticed a balloon which *seemed to be making for* a Royal Air Force Station nearby.
He informed the station at once, but no one there was able to explain the mystery.
The officer in the control tower was very angry when he heard the news,
	because balloons can be a great danger to aircraft.
He said that someone might be *spying on* the station
	and the pilot was ordered to *keep track of* the strange object.
The pilot managed to circle the balloon for some time.
He could *make out* three men in a basket under it and one of them was holding a pair of binoculars.
When the balloon was over the station, the pilot saw one of the men taking photographs.
*Soon afterwards*, the balloon began to descend and it landed near an airfield.
The police *were called in*, but they could not arrest anyone,
	for the basket contained two Members of Parliament and the Commanding Officer of the station!
As the Commanding Officer explained later,
	one half of the station did not know what the other half was doing!
#+end_verse

* Lesson 92 Asking for trouble

#+begin_verse
Why did the policeman ask the writer to come to the police station?

It must have been about two in the morning when I returned home.
I tried to wake up my wife by ringing the doorbell,
	but she was *fast asleep*,
	so I got a ladder from the shed in the garden,
		put it against the wall, and began climbing towards the bedroom window.
I was almost there when a sarcastic voice below said,
	'I don't think the windows need cleaning at this time of the night.'
I looked down and nearly fell off the ladder when I saw a policeman.
I immediately regretted answering in the way I did,
	but I said, 'I enjoy cleaning windows at night.'
'So do I,' answered the policeman in the same tone.
'Excuse my interrupting you.
I *hate to interrupt* a man when he's busy working,
	but would you mind coming with me to the station?'
'Well, I'd prefer to stay here,' I said.
'You see. I've forgotten my key.'
'Your what?' he called.
'My key,' I shouted.
Fortunately, the shouting woke up my wife who opened the window
	just as the policeman had started to climb towards me.
#+end_verse

* Lesion 93 A noble gift
#+begin_verse
Where was the Statue of Liberty made?

One of the most famous monuments in the world, the Statue of Liberty,
	was presented to the United States of America in the nineteenth century by the people of France.
The great statue, which was designed by the sculptor Auguste Bartholdi, took ten years to complete.
The actual figure was made of copper
	supported by a metal framework which had been especially constructed by Eiffel.
Before it could be transported to the United States,
	a site had to be found for it and a pedestal had to be built.
The site chosen was an island *at the entrance of* New York Harbour.
By 1884, a statue which was 151 feet tall had been erected in Paris.
The following year, it was *taken to pieces* and sent to America.
By the end of October 1886, the statue had been put together again
	and it was officially presented to the American people by Bartholdi.
Ever since then, the great monument has been a symbol of liberty for the millions of people
	who have passed through New York Harbour to make their homes in America.
#+end_verse

* Lesson 94 Future champions
#+begin_verse
What kind of race do the children compete in?

*Experiments have proved*
	that children can *be instructed in swimming* at a very early age.
At a special swimming pool in Los Angeles,
	children become expert at *holding their breath* under water even before they can walk.
Babies of two months old do not appear to *be reluctant to enter* the water.
It is not long before
	they *are so accustomed to swimming* that they can pick up weights from the floor of the pool.
A game that *is very popular with* these young swimmers is the underwater tricycle race.
Tricycles *are lined up* on the floor of the pool seven feet under water.
The children *compete against* each other to reach the other end of the pool.
Many pedal their tricycles, but most of them prefer to push or drag them.
Some children can cover the whole length of the pool without coming up for breath even once.
Whether they will ever become future Olympic champions, only time will tell.
Meanwhile, they should encourage those among us
	who cannot swim five yards before they are gasping for air.
#+end_verse

* Lesson 95 A fantasy
#+begin_verse
Why was the Ambassador particularly lucky?

When the Ambassador of Escalopia returned home for lunch, his wife got a shock.
He looked pale and his clothes were in a frightful state.
'What has happened?' she asked.
'How did your clothes *get into such a mess*?'
'A fire extinguisher, my dear,' answered the Ambassador drily.
'University students *set the Embassy on fire* this morning.'
'*Good heavens!*' exclaimed his wife.
'And where were you at the time?'
'I was in my office as usual,' answered the Ambassador.
'The fire broke out in the basement.
I went down immediately, of course, and that fool, Horst, aimed a fire extinguisher at me.
He thought I was on fire.
I must definitely get that fellow posted.'
The Ambassador's wife *went on asking* questions,
	when she suddenly noticed a big hole in her husband's hat.
'And how can you explain that?' she asked.
'Oh, that,' said the Ambassador.
'Someone *fired a shot* through my office window.
Accurate, don't you think?
Fortunately, I wasn't wearing it at the time.
If I had been,
	I would not have been able to get home for lunch.'
#+end_verse

* Lesson 96 The dead return
#+begin_verse
What happens to the lanterns at the end of festival?

A Festival for the Dead is held once a year in Japan.
This festival is a cheerful occasion,
	for on this day, the dead are said to *return to their homes* and they are welcomed by the living.
As they *are expected to be* hungry after their long journey,
	*food is laid out* for them.
Specially-made lanterns are hung outside each house to help the dead to find their way.
All night long, people dance and sing.
In the early morning,
	the food that had been laid out for the dead is thrown into a river or into the sea
	as *it is considered unlucky for anyone living* to eat it.
In towns that are near the sea,
	the tiny lanterns which had been hung in the streets the night before,
		*are placed into* the water when the festival is over.
Thousands of lanterns slowly drift out to sea
	guiding the dead on their return journey to the other world.
This is a moving spectacle,
	for crowds of people stand on the shore
		watching the lanterns drifting away until they can be seen no more.
#+end_verse
