#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task12 7-1 写作2 开始介绍+task2
+ 作业1： task2 ⼤作⽂
	In some countries, more and more people are becoming interested in finding out about the history of the house or building they live in.
	
	What are the reasons for this?
	
	How can people research this?
	1. 读： 70%
		 1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
		 2. 泛读&泛听这个话题（尽量别看范⽂）
		 3. 随⼿记下新的内容+结构+表达
	2. 练： 20%
		 1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
		 2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。
				（控制在500字左右，不限时间）
	3. 改： 10%
		 1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
		 2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改.
				但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
		 3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）
				
+ 作业2： task1 ⼩作⽂
虽然接下来我分了雅思A类， G类，托福。但是⽆论您考这三者中哪⼀个，都要全部看⼀下。实际操作可以选择⾃⼰的类别。
雅思A类：
1. 认真审题，标记核⼼词，短语，句⼦。
2. 学员汉语书写（150+） +查找⾼分范⽂（英⽂+去哪找？） + 对⽐⼆者【内容】【结构】上的差别。

雅思G类：
1. 认真审题，标记核⼼词，短语，句⼦。
2. 学员汉语书写（150+） +查找⾼分范⽂（英⽂+去哪找？）+对⽐⼆者【内容】【结构】上的差别。

托福：
1. 找来真题（TPO-⼩站托福app），熟悉流程（阅读+听⼒+写作）
	 1. 阅读skimming + summary + 标记核⼼观点
	 2. 听⼒+ take notes
2. 学员汉语书写（150-225字） +查找⾼分范⽂（英⽂+去哪找？） + 对⽐⼆者【内容】【结构】上的差别。
** 作业1： task2 ⼤作⽂
In some countries, more and more people are becoming interested in
	finding out about the history of the house or building they live in.
What are the reasons for this?
How can people research this?

1. 读： 70%
	 1. 务必仔细审题，就像阅读当年您的初恋写给您的情书⼀样，⼀个字都不要放过。
	 2. 泛读&泛听这个话题（尽量别看范⽂）
	 3. 随⼿记下新的内容+结构+表达
2. 练： 20%
	 1. 尝试⽤⾃⼰的⼤脑总结出⼀些符合您实际情况或认知的思路，并罗列⽂章⼤纲。
	 2. 随笔写，不⽤担⼼是否⼀次写完，不⽤担⼼是否哪⾥不会⽤英⽂表达，先⽤汉语凑合没问题。
			（控制在500字左右，不限时间）
3. 改： 10%
	 1. 在接下来的⼀段时间，每学习⼀些新的单词+语法+习惯⽤法就不定期回来看看尝试修改这篇⽂章
	 2. 实在忍不住，就直接去 grammaly + chatgpt +？ 去修改.
			但是，⼀定要对⽐修改完的⽂章 和您⾃⼰写的⽂章在表达，内容，结构上的差别。
	 3. 星座⼩组：共同准备，互相讨论，互相提供修改建议。（thesis）
*** 1.读
extract some of the wonderful stories
hold a wealth of information
people who lived, loved, worked or worshipped, solve mysteries
our ancestors, fit with genealogical and family story research
The design of a house, in what era something was built,
	what the space was used for
walls with several layers of paint or wall paper,
	display the fashion of the day, the wealth of the occupants of the time
give context about what was happening locally and globally at any given time

help to align our understanding about what was happening in the wider world during a certain period
H: by creating a timeline of everyone who has lived in a house

about the fabric of a suburb, how it developed and the people who lived and worked there

get a feel for what has come before
assist with planning permits and renovations

HOW:
when your home was built, who lived there, and how they changed it

identify the era in which the structure was built
With the help of an architecture book or two, discern a core style, by examining the style of the windows, doors, and other features

Invite Experts to Assess Your Home
studied the exterior and interior of the Schondorf house, an architect and historian
mean that the house was built then, were prevalent

Pay Attention to The Construction
since the frame of a house is unlikely to have been altered since the time the house was built, house's style

rough-date a house, nails, paint colors
help date elements of a house by examining a cross section of a paint chip

Inspect the Hardware
a hinge design matches the estimated date of a door, have no sign of having been changed, confirm the estimate
On the other hand, from the days of mass production.

Review Official Records
back up guesstimate about construction dates and alterations
maps, local newspapers and the genealogical information
 trace the sale of the property through the previous 23 owners at the town's deed office.
--Use Old Maps
maps in chornological order, pinpoint the date a house first appears in a town survey.
descriptions of size, layout, and materials for houses in more densely populated area.
--City Directories and Newspapaers
indexes for the years you think your house may have been built, buildings
lucky researcher may find how many rooms were on the frist floor.

Dig up Tax Property Records
per-acre land assessment on a piece of property goes up in a given year,

Peel Back the Paint
*** 写
**** 大纲

reasons:
	- extract some hidden wonderful stories
		hold a wealth of information
	- find our ancestors to fit with genealogical and family story research
	- align our understanding about what was happening in the wider wolrd during a certain period
		farci of a suburb, how it developed, who lived and worked
	- satisfy my curiosity, get a feel for what has come before
how:
	- identify the era in which the structure was built
		an architecture book, discern a core style, examinining the style of the windows
	- invite experts to assess my home
		An architect, study the exterior and interior of the house,
		the styles of the house were prevalent, indicate that
	- pay attention to the construction
		the frame of a house have rarely altered since the time the house was built
	- rough-date a house, nails, paint colors
		elements of a house by examining a cross section of a paint chip
	- use old maps
		pinpoint the date a house first appears in a town survey

**** 正文
In some countries, more and more people
	are becoming interested in finding out about the history of the house or building they live in.
There are several common reasons that people hold to do this,
	and some ways to research the history of their houses.

Some people undertake the task of researching it merely for fun,
	during which they not only satisfy their curiosities,
		but also enjoy a feel for the house in the past.
This extract some wonderful stories which have been mysteries,
	for a house indeed holds a wealth of information.
It may also help to find our ancestors,
	so that we could fit with genealogical and family story research.
When you plan to renovate you house, it must be the time to find out about the history of the house.
Besides, it enlarges our understanding about the history of the area in which the house is located,
	we might learn more about the farci of a suburb, like how it developed and who lived and worked.

There are a good number of ways to research the history of the house.
For one thing, what you need to do may be to indentify the era in which the structure was built.
With the help of an architecture book,
	you could discern a core style of the house
		by examining the style of the windows, doors and other features.
Another thing which is suitable for you is to invite experts to assess your home.
An architect or a historian studies the exterior and interior of the house,
	so that he could tell when the house was built
		by the style of it which were prevalent at a particular time.
Since the frame of a house is unlikely to have been altered
	since the time the house was built,
	you can pay attention to the construction by which you can estimate when it was built.
You can rough-date a house by stuffs in your house which help you confirm the date of your house,
		like nails, paint colors, hinge design and so on.
For example, you can date elements of ahouse by examining a cross section of a paint chip.
The most beneficial way to figure out it may be to use old maps.
Looking at maps in chornological order,
	you can pinpoint the date your house first appears in a town survery.
Even a map show you the detailed descriptions of size, layout and materials for houses.

There are more interesting about the history of the house in the world,
	which leads to more and more ways to reseach it.

**** 改1
** 作业2： task1 ⼩作⽂
雅思G类：
1. 认真审题，标记核⼼词，短语，句⼦。
2. 学员汉语书写（150+） +查找⾼分范⽂（英⽂+去哪找？）+对⽐⼆者【内容】【结构】上的差别。

WRITING TASK 1

You should spend about 20 minutes on this task.

A friend of yours is thinking of going on a camping holiday for the first time this summer.
HelShe has asked for your advice.

Write a letter to your friend. In your letter
- explain why you think your friend would enjoy a camping holiday
- describe some possible disadvantages
- say whether you would like to go camping with your friend this summer
	
Write at least 150 words.
You do NOT need to write any addresses.
Begin your letter as follows:

Dear HelShe,
*** 读
be considered the best time for camping for a number of reasons:
	1. weather warmer inclement
		 be exposed to the elements to a much greater degree than when at home
	2. days are longer
		 more time in a day to engage in various activities,
			such as hiking, rock climbing, fishing, etc.
	3. Accessibility, in China, we have access to mountains and camping in these is very popular
	4. recreational opportunities
		 swimming in a half frozen lake in winter is not so fun as swimming in the same lake in summer.
	5. vacation time
		 your kids are off school, accompany

disadvantages:
	1. upredictable weather,  rain, wind and extreme temperatures, uncomfortable and dangerous. check the weather forecast, prepare the right clothing and gear
	2. sleeping on a thin mat on the ground can be uncomfortable
	3. communal toilets and showers can be dirty
	4. bring you into close contact with bugs, annoying and potentially carry diseases.

*** 写
Dear HelShe,
		I am glad
			that you have asked for my advice about a camping holiday for the first time this summer.
		I think that you would enjoy your camping holiday,
			for summer is generally considered as the best time for camping.
		The days in summer are often longer than others,
			which means there is more time in a day to engage in various activities,
				such as hiking, rock climbing, fishing, etc.
		In China, we often have access to mountains
			and camping there is very popular with young people these days.
		It is also a good opportunity to swim in the lake.
		Imagining that swimming in a half frozen lake in winter is obviously not so fun as swimming in summer.
		As your kids are off school, you can spend more time accompanying with your family.

		However, if you pay attention to some disadvantages, you may enjoy your vocation better.
		There are some unpredictable weathers in summer, such as rain, wind and extreme temperatures.
		You would better check the weather forecast to prepare the right clothing and gear.
		Sleeping on a thin mat on the ground can be uncomfortable,
			so you can carry sleeping bags in your car trunk.
		Besides, camping can bring you into close contact with bugs
			that can be annoying and potentially carry diseases.

		Thanks for your invitation to the camping together,
			however, my children enrolled in a holiday workship so that I have to pick up them everyday.
		Hope you enjoy your holiday!

Best wishes,
	Sherwin Wu
*** 改
