#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* task7 3-2 阅读subskills
家庭作业:
材料: 剑雅17真题第一套
1. 【必修】剑雅17真题，三篇阅读文章，只看题型。请总结考的是什么题型，尝试总结考察的抽象能力sub-skils是什么?
	 1. 20m 1-13 13=填空 6+判断题(not given) 7
	 2. 20m 14-26 13=配对 4+ 填空题 5+ 多选题 2
	 3. 20m 27-40 14=填空 5+ 判断题 4+ 选择题 5
	 subskills:
		 单词+语法+习惯用法
		 同义词的能力
		 拆长难句的能力
		 猜上下文的能力
		 总结大纲的能力,skimming
		 检索信息的能力,scanning
2. 【必修】精读第一篇文章 why we need to protect polar bears
	 1. 千万别做题
	 2. 标记全文语法+生词+习惯用法(是否造句自选)
3. 【必修】无需跟读，但反复阅读50遍 + 做题(查看正确率)
4. 【选修】阅读'Meditation for Dummies'一书中'Following Your Breath'一文。
	  可以查阅冥想的好处，bing，咕咕咕。写作&口语内容准备task0.5
** 疑问
1. 为什么要阅读50遍? 记住体验
2. 实际要读到什么程度? 读懂了,能输出
3. 泛听要注意什么? 听力词汇,
** 做题 全对了
1. population
2. suburbs
3. businessmen
4. funding
5. press
6. soil
		--------------------T F Not Give
7. F
8. N
9. T
10. T
11. F
12. F
13. N
** The development of the London underground railway 15| 15| 5 5 5 4
In the first half of the 1800s, London's population grew at an astonishing rate,
	and the central area became increasingly congested.
In addition, the expansion of the overground railway network
	resulted in more and more passengers arriving in the capital.
However, in 1846, a Royal Commission decided
	that the railways should not be allowed to enter the City,
		the capital's historic and business centre.
The result was that the overground railway stations formed a ring around the City.
The area within consisted of poorly built, overcrowded slums
	and the streets were full of horse-drawn traffic.
Crossing the City became a nightmare.
It could take an hour and a half to travel 8 km by horse-drawn carriage or bus.
Numerous schemes were proposed to resolve these problems, but few succeeded.

Amongst the most vocal advocates for a solution to London's traffic problems was Charles Pearson,
	who worked as a solicitor for the City of London.
He saw both social and economic advantages in building an underground railway
	that would link the overground railway stations together
		and clear London slums at the same time.
His idea was to relocate the poor workers
			who lived in the inner-city slums
		to newly constructed suburbs,
	and to provide cheap rail travel for them to get to work.
Pearson's ideas gained support amongst some businessmen
	and in 1851 he submitted a plan to Parliament.
It was rejected,
	but coincided with a proposal from another group for an underground connecting line,
		which Parliament passed.
		
The two groups merged and established the Metropolitan Railway Company in August 1854.
The company's plan was to construct an underground railway line
	from the Great Western Railway's (GWR) station at Paddington
		to the edge of the City at Farringdon Street - a distance of almost 5 km.
The organisation had diffculty in raising the funding for such a radical and expensive scheme,
	not least because of the critical articles printed by the press.
Objectors argued that the tunnels would collapse under the weight of traffic overhead,
	buildings would be shaken
	and passengers would be poisoned by the emissions from the train engines.
However, Pearson and his partners persisted.

The GWR, aware
		that the new line would finally enable them to run trains into the heart of the City,
	invested almost $250,000 in the scheme.
Eventually, over a five-year period, $1m was raised.
The chosen route ran beneath existing main roads to minimise the expense of demolishing buildings.
Originally scheduled to be completed in 21 months,
	the construction of the underground line took three years.
It was built just below street level using a technique known as 'cut and cover'.
A trench about ten metres wide and six metres deep was dug,
	and the sides temporarily held up with timber beams.
Brick walls were then constructed,
	and finally a brick arch was added to create a tunnel.
A two-metre-deep layer of soil was laid on top of the tunnel and the road above rebuilt.

The Metropolitan line, which opened on 10th January 1863,
	was the world's first underground railway.
On its first day, almost 40,000 passengers were carried between Paddington and Farringdon,
	the journey taking about 18 minutes.
By the end of the Metropolitan's frst year of operation,
	9.5 million journeys had been made.
	
Even as the Metropolitan began operation,
	the first extensions to the line were being authorised;
		these were built over the next five years,
		reaching Moorgate in the east of London and Hammersmith in the west.
The original plan was to pull the trains with steam locomotives,
		using firebricks in the boilers to provide steam,
	but these engines were never introduced.
Instead, the line used specially designed locomotives
	that were fitted with water tanks in which steam could be condensed.
However, smoke and fumes remained a problem,
	even though ventilation shafts were added to the tunnels.
	
Despite the extension of the underground railway,
	by the 1880s, congestion on London's streets had become worse.
The problem was partly
	that the existing underground lines formed a circuit around the centre of London
			and extended to the suburbs,
		but did not cross the capital's centre.
The 'cut and cover' method of construction was not an option in this part of the capital.
The only alternative was to tunnel deep underground.

Although the technology to create these tunnels existed,
	steam locomotives could not be used in such a confined space.
It wasn't until the development of a reliable electric motor,
		and a means of transferring power from the generator to a moving train,
	that the world's first deep-level electric railway, the City & South London, became possible.
The line opened in 1890, and ran from the City to Stockwell, south of the River Thames.
The trains were made up of three carriages and driven by electric engines.
The carriages were narrow and had tiny windows just below the roof
	because it was thought that passengers would not want to look out at the tunnel walls.
The line was not without its problems,
	mainly caused by an unreliable power supply.
Although the City & South London Railway was a great technical achievement,
	it did not make a profit.
Then, in 1900 the Central London Railway, known as the 'Tuppenny Tube',
	began operation using new electric locomotives.
It was very popular
	and soon afterwards new railways and extensions were added to the growing tube network.
By 1907, the heart of today's Underground system was in place.
** experession
In the first half of the 1800s
at an astonishing rate
congested: full of traffic
In addition
the expansion of sth.
the overground railway network
resulted in
more and more
sb. decide that + ...
The result was that + ...
formed a ring around sp.
within: during a certain period of time
consisted of
slums:a house or an area of a city that is in very bad condition, where very poor people live
were full of
horse-drawn traffc: vehicles are pulled by a horse
It take st. to do sth.
carriage:a vehicle with wheels that is pulled by a horse, used in the past
Numerous:many
were proposed to do sth.
resolve these problems

amongst sb. be sb.
vocal :expressing strong opinions publicly, especially about things that you disagree with 
advocates for:to publicly support a particular way of doing something
worked as sjob. for scompany.
solicitor :a type of lawyer in Britain who gives legal advice, prepares the necessary documents when property is bought or sold, and defends people, especially in the lower courts of law  lawyer, advocate, barrister
see xx advantages in doing sth.
an underground railway
at the same time:
sb's idea is to do sth
relocate sb. to sp.
provide sth. for sb.
get to work
gain support
submit a plan to ...
be coincided with sb.: to come together in position or happen at or near the same time
proposal:a plan or suggestion which is made formally to an official person or group, or the act of making it

establish scompany.
sb's plan was to do sth.
a distance of almost 5 km
have diffculty in doing sth.
raising the funding/money for sth.
radical 
not least
because of
A. be printed by B.
sb. argues that + ...
emissions: a gas or other substance that is sent into the air

be aware that + ...
enable sb. to do sth.
invest money.
in the scheme
main road
minimise the expense of sth.
be scheduled to do sth.
A. be known as B.
trench:a long narrow hole dug into the surface of the ground
dig a trench/ a trench is dug
timber:wood used for building or making things
beams:a long heavy piece of wood or metal used in building houses, bridges etc
Brick:a hard block of baked clay used for building walls, houses etc
A two-metre-deep layer of soil
on top of the tunnel

on its first day
sb. be carried between A. and B.
the journey taking ...: 独立主格
by the end of sth.


authorised:to give official permission for something
the first extensions to the line
reach placeA and placeB
use sth. to do sth.
introduced:to bring a plan, system, or product into use for the first time
locomotive:a railway engine
be fitted with
steam be condensed in: shortened
remain a problem
even though
A. be added to b.
shaft:a passage which goes down through a building or down into the ground, so that someone or something can get in or out

the extension of sth.
the problem was partly that + ..., but did not do sth.
the alternative is to do sth.
in a confined space
It wasn't until sth. that + ...
a means of
were made up of sth.
it is thought that + ...
want to do sth.
be without problems.
power supply
make a profit
be in place: working or ready to work; established.
