#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Task4 1-1 听力
Task4 课前任务：
精听+精读
所⽤素材：
剑雅16 第⼀套真题听⼒第⼀题
1. 先听⽂章（⼀定不要先阅读听⼒脚本），答题，记录对错
2. 认真阅读听⼒脚本，标注所有⽣词（⽂中含义），语法（参考新概念英语及三本语法书），摘抄习惯⽤法（并造句）
3. 反复跟读edge或听⼒⾳频，⽆需熟读成诵，但请跟读到⾜够顺畅。拿不准就跟读50遍。
4. 模拟考试，听⽂章，答题，记录对错。
5. 对⽐1&4 答题情况
6. 做完前5步，请思考并写下，【阅读与听⼒】的关系。
** 阅读与听力
阅读是听力的基础.

** questions
1. 跟读多少内容,才能做到听力通杀,而不是听过的材料? 还要看学术类的
2. 单词单复数扣不扣分,同义词扣不扣分? 不扣
3. 跟读50遍后,有些地方仍然需要思考才能知道说什么.为什么? 没过脑子
** first
1. egg
	 t
2. tower
	 t
3. car
	 t
4. animal
	 animals
5. bridge
	 t
6. movie
	 t
7. decorate
	 t
8. wednesday
	 wednesdays
9. Fradstone
	 t
10. parking-lot
		parking
** second 10
1. egg
2. tower
3. car
4. animals
5. bridge
6. movie
7. decorate
8. Wednesdays
9. Fradstone
10. parking
** article
#+begin_verse
1: Hello. Children's Engineering Workshops.

2: Oh hello. I wanted some information about the workshops in the school holidays.

1: Sure.

2: I have two daughters who are interested.
The younger one's Lydia, she's four,
	do you take children as young as that?

1: Yes, our Tiny Engineers workshop is for four to five-year-olds.

2: What sorts of activities do they do?

1: All sorts. For example, they work together to *design a special cover that goes round an egg*,
	so that when it's inside they can drop it from a height and it doesn't break.
Well, sometimes it does break but that's part of the fun!

2: Right. And Lydia loves building things.
*Is there any opportunity for her to* do that?

1: Well, they have a competition to see who can make the highest tower.
You'd *be amazed* how high they can go.

2: Right.

1: But they're learning all the time as well as having fun.
For example, *one thing they do is to* design and build a car *that's attached to* a balloon,
	and the force of the air in that actually powers the car and makes it move along.
They go really fast too.

2: OK, well, all this sounds perfect.

2: Now Carly, that's my older daughter,
		has just had her seventh birthday,
	so presumably she'd be in a different group?

1: Yes, she'd be in the Junior Engineers.
That's for children from six to eight.

2: And do they do the same sorts of activities?

1: Some are the same, but a bit more advanced.
So they work out how to build model vehicles, things like cars and trucks,
	but also how to construct animals using the same sorts of material and technique,
	and then they learn how they can program them and make them move.

2: So they learn a bit of coding?

1: They do. They pick it up really quickly.
We're there to help if they need it, but they learn from one another too.

2: Right. And do they have competitions too?

1: Yes, with the Junior Engineers,
	it's to use recycled materials like card and wood to build a bridge,
		and the longest one gets a prize.

2: That sounds fun.
I wouldn't mind doing that myself!

1: Then they have something a bit different,
	this is from Laokaoya website,
	which is to think up an idea for a five-minute movie and then film it,
	using special animation software.
You'd be amazed what they come up with.

2: And of course, that's something they can put on their phone
	and take home to show all their friends.

1: Exactly.
And then they also build a robot in the shape of a human,
	and they decorate it and program it
		so that it can move its arms and legs.

2: Perfect.	So, is it the same price as the Tiny Engineers?

1: It's just a bit more: £50 for the five weeks

2: And are the classes on a Monday, too?

1: They used to be,
	but we found it didn't give our staff enough time to clear up after the first workshop,
	so we moved them to Wednesdays.
The classes are held in the morning from ten to eleven.

2: OK. That's better for me actually.
And what about the location?
Where exactly are the workshops held?

1: They're in building 10A – there's a big sign on the door,
	you can't miss it,
	and that's in Fradstone Industrial Estate.

2: Sorry?

1: Fradstone – that's F-R-A-D-S-T-O-N-E.

2: And that's in Grasford, isn't it?

1: Yes, up past the station.

2: And will I have any parking problems there?

1: No, there's always plenty available.
So would you like to enroll Lydia and Carly now?

2: OK.

1: So can I have your full name ...
#+end_verse
*** expressions
workshop: 研习班
- He decided that the workshop would be held last Friday. 
- He wanted his daughter to enroll for the workshop.
- He is reminiscing about the workshop in his childhood.
want some information about sth.: 想要某物的信息
- I want some information about Jack who works for Apple Corporation.
- He wanted some information about MBA from Harvard.
- When he wanted some information about the workshop, he didn't receive a warm welcome.
design a adj. cover that goes round sth. : 设计一个保护套包裹住某物
- He's aim is to design a special cover that goes round a computer.
- He managed to design a special cover that goes round an egg to prevent it from being broken.
- He designed a beautiful cover that goes round strawberries
		at a time when these were very popular.
there is an opportunity for sb. to do sth.: 对某人有机会做某事
- There is an opportunity for the application to pop up a video.
- There used to be an opportunity for the offical to back off.
- Is there any opportunity for me to apply for a MBA from Harvard.
be amazed + ...: 对...吃惊
- I am amazed that he wrote a story in recognition of his cat.
- I am amazed that he writes this story as a tribute to his dead wife.
- I am amazed that the loss of Titanic makes it impossible for me to meet her again. 
one thing sb. does is to do sth.:某人做的一件事是做某事
- One thing the group of pop singers is to give a performance at worker's club this night.
- One thing I do is to finish my homework in time.
- One thing he do is to complain about this wicked world.
A. be attached to B.: B绑到A上
- The car that's attached to a balloon is a gift for my wife.
- When she saw car attched to the balloon  which brought a smile to her face.
- I don't have a lot of patience to attach a balloon to a car.
the force of air/water: 空气的力量
- The force of air is powering the car and making it move.
- The force of air must have powered the car and made it move.
- The broken car reminded him of the force of air in the accident.
presumably: 估计是
- Presumably, his rise in salary gave him encouragement to ask for phone number of the girl.
- Presumably, our cat contribute to the broken vase.
- Presumably, they held a party to mark the occassion.
advanced: 更高级的
- The advanced workshop is a bit more expensive than another.
- We should all remember him for the advanced class that he developed in his early years.
- He decided to devote himself to the advanced English course.
construct A. using B.: 用B来构造A
- It is a curious coincidence that people in Ancient China constructed houses using wood and stone.
- In his honor, they constructed a bridge using wood purely.
- While he constructed a wooden pig using the special materials, he lost his patience.
pick sth. up: 某事进步
- Sorry to interrupt, but he picked it up very quickly.
- He devoted himself to the gardening after retire and picked it up very quickly.
- If you worked hard, you would also pick it up very quickly.
use A. to do B.: 用A来做B
- In the end, he managed to use the keyboard to input text in his computer.
- He noticed with dismay that he couldn't use the knife to cut the pineapple.
- He used the editor to write an article on engineering workshop at tremendous speed.
come up with=think up an idea for sth.: 为某事想出主意
- Believe it or not, it's your child who thought up an idea for playing truent from school.
- He managed to think up an idea for hunting for the puma at large.
- He always thinks up an idea for raising money.
A. in the shape of B.: B形状的A
- He succeeded in constructing a robot in the shape of human.
- My wife sent me a cake in the shape of a dog.
- A robot in the shape of human is moving in a circle in the exhibition.
give sb. enough time to do sth.: 给某人足够的时间去做某事
- The busy traffic didn't give him enough time to get away from the police. 
- If the police had arrived on scene at the first time,
		it wouldn't have given us enough time to escape.
- It gives him enough time to commit a murder.
up past sp.: 过了某处
- Our workshop is up past the station.
- There is a big sign on the build which is up past the station.
- Are you suggesting that the company is up past the mall.
enrol: 报名
- We will give you enough time to consider before you enrol in our workshop.
- I want to enrol my daughter for 'The Art of expression'.
- He hesitated to enrol in the IELTS course of Mr. Leo.
