#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 1 A private conversation
#+begin_verse
Why did the writer complain to the people behind him?

Last week I *went to the theatre*.
I *had a very good seat*.
The play was very interesting.

I did not enjoy it.
A young man and a young woman were sitting behind me.
They were talking loudly.

I *got very angry*.
I could not hear the actors.
I turned round.
I looked at the man and the woman angrily.
They did not pay any attention.

*In the end*, I could not bear it.
I turned round again.
'I can't hear a word!' I said angrily.
'*It's none of your business*,' the young man said rudely. 'This is a private conversation.'
#+end_verse

** 单词造句
private adj.
1. She goes to a private hospital.
2. Why does she go to a private hospital?
3. Don't go to a private hospital. It's dangerous!
4. When did she go to a private hospital!
5. She goes to a private hospital by bus.
conversation n.
1. I had a conversation with her yesterday.
2. This is a private conversation.
3. How did you have a conversation with her?
4. Why did you have a conversation with her yesterday?
5. Where did you have a conversation with her yesterday?
theatre n.
1. I've been to that theatre.
2. He has never been to that theatre.
3. Let's go to the theatre.
4. How do we go to the theatre?
5. When do we go to the theatre?
seat n.
1. I have a good seat at home.
2. Why did you have a good seat?
3. Is the seat taken?
4. I taked a seat in bedroom.
5. Why do you take a seat now?
play n.
1. It's interesting to watch a play.
2. I'm watching a play with her.
3. When did you watch a play?
4. How did you watch a play?
5. Why do you watch a play?
** 反复听电影片段
** Pattern Drill 写+读
1. 
		1T: walk - across the stage - show
		S1: How did she walk across the stage?
		S2: She walked very slowly across the stage.
	 - Behave - at the theatre - rude/bad
		 How did she behave at the theatre?
		 She behaved very rudely at the theatre?
	 - drive - through the park - quick/slow
		 How did she drive through the park?
		 She drived very slowly through the park.
	 - sleep - on the train - sound/quite
		 How did he sleep on the train?
		 He slept very quitely on the train.
	 - listen - to his story - patient/ careful
		 How did she listen to his story?
		 She listened carefully to his story.
2. 
		2T: hear the radio
		S1: I can hear the radio now. Can you?
		S2: Of course I can. I can hear it perfectly well.
	 - hear the actors
		 I can hear the actors now. Can you?
		 Of course I can. I can hear them perfectly well.
	 - see those men
		 I can see those men now. Can you?
		 Of course I can. I can see them perfectly well.
	 - see the theatre
		 I can see the theatre now. Can you?
		 Of course I can. I can see it perfectly well.
	 - see the police
		 I can see the policeman now. Can you?
		 Of course I can. I can see him perfectly well.
3. 
		3T: last night - a good talk on the radio - saw/heard
		S: I heard a good talk on the radio last night.
	 - just now - a voice/knock - at the door
		 I heard a knock at the door just now.
	 - last night - a cry/shout - outside
		 I heard a cry outside last night.
	 - at lunch - a fly/hair - in my soup
		 I saw a hair in my soup at lunch.
	 - last night - a camel/monkey - at the zoo.
		 I saw a camel at the zoo last week.
4. 
		4T: see the race - large - crowd
		S1: Didn't you see the race?
		S2: I couldn't. The crowd was too large.
	 - read the letter - small/bad - writing
		 Didn't you read the letter?
		 I couldn't. The writing was too small.
	 - see her face - poor/bad - light
		 Didn't you see her face?
		 I couldn't. The light was too poor.
	 - swim in the lake - could/deep - water.
		 Didn't you swim in the lake?
		 I couldn't. The water was too deep.
	 - finish your lunch - hot/salty - food
		 Didn't you finish your lunch?
		 I couldn't. The food was too salty.
** 给自己讲解
** 红皮书
** 习惯用法造句
go to the theatre
1. I went to the theatre on Saturday.
2. Did you go to the theatre on Saturday?
3. Who went to the theatre on Saturday?
4. When did you go to the theatre?
5. How did you go to the theatre on Saturday?
have a good seat
1. I had a good seat yesterday.
2. Did you have a good seat yesterday?
3. Who have a good seat yesterday?
4. When did you have a good seat?
5. How did you have a good seat?
get angry
1. I got very angry yesterday.
2. Why did you get angry yesterday?
3. When did you got angry?
4. Where did you get very angry?
5. Did you get very angry yesterday.
turn round
1. He always turns round in the class.
2. Who always turns round in the class?
3. How often does he turn round in the class?
4. Why does he always turn round in the class?
5. Where does he always turn round?
pay attention
1. They did not pay any attention.
2. Did they pay a attention?
3. Why didn't they pay any attention?
4. Who did not pay any attention?
5. When did not they pay any attention?
in the end
1. In the end, my mom and me went to the theatre.
2. Did your mom and you go to the theatre in the end?
3. Why did your mom and you go to the theatre in the end?
4. Where did your mom and you go in the end?
5. How did your mom and you go to the theatre in the end?
couldn't bear it
1. I couldn't bear it.
2. How could you bear it?
3. Why could you bear it?
4. Who could bear it?
5. When couldn't you bear it?
It's none of your business
1. 
2. 
3. 
4. 
5. 
** 跟读至背诵
** Ask me if 写+读
1. I went to the theatre last week. When
	 When did you go to the theatre?
2. I had a good seat. What kind of
	 What kind of seat did you have?
3. I saw an interesting play. What
	 What did you see?
4. A young man and a young woman was sitting behind me. Who/When
	 Who was sitting behind you?
	 When was the young man and the young woman sitting?
5. They were talking loudly. How
	 How were they talking?
6. I couldn't hear the actors. Who
	 Who couldn't hear the actors?
7. I turned round. What ... do
	 What did you do?
8. I looked at the man and the young woman angrily. How
	 How did you look at the man and the young woman?
** 摘要写作
The writer went to the theatre last week.
He did not enjoy the play.
A young man and a young woman were sitting behind me.
They were talking loudly, he couldn't hear the actors.
He turned around, and said "I can't hear a word".
The young man said "This is a private conversation".
** tell the story 口语
** Topics for discussion
