#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 14 Do you speak English?

#+begin_verse
Did the young man speak English?

I *had an amusing experience* last year.
After I had left a small village in the south of France, I *drove on* the next town.
*On the way*, a young man *waved to me*.
I stopped and he *asked me for a lift*.
As soon as he had got into the car,
	I said good morning to him *in French* and he replied in the same language.
*Apart from* a few words, I do not know any French at all.
Neither of us spoke during the journey.
I had nearly reached the town,
	when the young man suddenly said, very slowly,
		'Do you speak English?'
As I soon learnt, he was English himself!
#+end_verse

** 单词造句
amusing
1. I find it amusing.
2. She took part in an amusing car race last year.
3. I'll be taking part in  an amusing car race next year.
4. I entered for an amusing competition.
5. Will you be taking part in the amusing car race tomorrow?
experience
1. I had an amusing experience last year.
2. I had an amusing experience after I had visited the Shanghai Disneyland.
3. Did you have an amusing experience last year?
4. When did you have an amusing experience?
5. Where did you have an amusing experience last year?
wave
1. Look, she's waving to you. Do you know her?
2. Why is she waving to me. I don't know her.
3. As soon as he had waved to me, I stopped.
4. Why didn't the taxi stop after I had waved to it?
5. Leo is waving to us when I open the video?
lift  hitchhike
1. I took a lift on the way.
2. She asked me for a lift.
3. I wouldn't take a lift from a strange woman.
4. You couldn't take a lift from a strange man in China.
5. My boss gave me a lift yesterday.
reply
1. The girl replied to her boyfriend's letter immediately.
2. She always replys to the email after three days.
3. Don't worry about it. I have replied to his letter.
4. I'll be replying to his letter tomorrow?
5. When will you be replying to his letter?
language
1. What is your native language?
2. My native language is Chinese.
3. Is your native language Chinese?
4. Why is your native language Chinese?
5. He is English himself whose native language is English.
journey
1. I will be going on a journey next week.
2. I went on an amusing journey yesterday.
3. We are going on an amusing journey tomorrow.
4. When will you be going on a journey?
5. How will you be going on a journey?
** 反复听电影片段
** Pattern Drill 写+读
1. 
		1t:angry - prepare lunch for him
		s1:Why was he so angry?
		s2:I hadn't prepared lunch for him.
	 - upset - give Mary his letter
		Why was she so upset?
		I hadn't given Mary his letter.
	 - annoyed - post his letters
		Why was he so annoyed?
		I hadn't posted his letters.
	 - pleased - reported him to the headmaster
		Why was he so pleased?
		I hadn't reported him to the headmaster.
	 - surprised - repair his bicycle
		Why was he so surprised?
		I hadn't repaired his bicycle.
2. 
		2t:see the film properly - my glasses
		s1:Why couldn't you see the film properly?
		s2:I hadn't taken my glasses with me.
	 - find his house - a map
		Why couldn't you find his house?
		I hadn't taken a map with me.
	 - see the show - any money
		Why couldn't you see the show?
		I hadn't taken any money with me.
	 - open the door - a key
		Why couldn't you open the door?
		I hadn't taken a key with me.
	 - sign the letter - a pen
		Why couldn't you sign the letter?
		I hadn't taken a pen with me.
3. 
		3t:tidy the garage - done
		s1:Why didn't John tidy the garage yesterday?
		s2:Because he'd already done it.
	 - -
		Why didn't John  yesterday?
		Because he'd already it.
	 - -
		Why didn't John  yesterday?
		Because he'd already it.
	 - -
		Why didn't John  yesterday?
		Because he'd already it.
	 - -
		Why didn't John  yesterday?
		Because he'd already it.
4.
	 4t:burn the letter
	 s1:Did you really burn the letter?
	 s2:It was a mistake. I realized it as soon as I'd burnt it.
	 - 
		Did you really ?
		It was a mistake. I realized it as soon as I'd it.
	 - 
		Did you really ?
		It was a mistake. I realized it as soon as I'd it.
	 - 
		Did you really ?
		It was a mistake. I realized it as soon as I'd it.
	 - 
		Did you really ?
		It was a mistake. I realized it as soon as I'd it.
		
** 给自己讲解
** 红皮书
** 习惯用法造句
drive on to sw.
1. 
2. 
3. 
4. 
5. 
on the way
1. 
2. 
3. 
4. 
5. 
ask sb. for a lift/ ask for a lift/ give sb. a lift
1. 
2. 
3. 
4. 
5. 
in French
1. 
2. 
3. 
4. 
5. 
apart from
1. 
2. 
3. 
4. 
5. 
** 跟读至背诵
** Ask me if 写+读
1. 
2. 
3. 
4. 
5. 
6. 
7. 
8. 
9. 
10. 
** 摘要写作
** tell the story 口语
** Topics for discussion
