#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
* Lesson 17 Always young

#+begin_verse
Why doesn't Aunt Jennifer tell anyone how old she is?

My aunt Jennifer is an actress.
She must be *at least* thirty-five years old.
*In spite of this*, she often appears on the stage as a young girl.
Jennifer will have to *take part in* a new play soon.
This time, she will be a girl of seventeen.
In the play, she must appear in a bright red dress and long black stockings.
Last year in another play, she had to wear short socks and a bright, orange-coloured dress.
If anyone ever asks her how old she is, she always answers,
	'Darling, it must be terrible to be grown up!'
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
Who is your favourite actor/actress? Why do you think he/she is good?
Is it true that most women tell lies about their age? Why do they? What about men?
Do you think it's terrible to be grown up? Why/why not? 
