#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* Lesson 22 A glass envelope

#+begin_verse
How did Jane receive a letter from a stranger?

My daughter, Jane, never *dreamed of receiving* a letter from a girl *of her own age* in Holland.
Last year, we were travelling across the Channel
	and Jane put a piece of paper with her name and address on it into a bottle.
She threw the bottle into the sea.
She never *thought of* it again,
	but ten months later, she received a letter from a girl in Holland.
Both girls *write to each other* regularly now.
However, they have *decided to use* the post office.
Letters will cost a little more,
	but they will certainly travel faster.
#+end_verse
** ~
dream [driːm] v.做梦,梦想
age [eɪdʒ] n.年龄
channel [ˈtʃæn(ə)l] n.海峡
throw [θrəʊ] threw [θruː] thrown [θrəʊn] v.扔,抛
regularly [ˈreɡjələli] adv.有规律地

dream of doing sth. 梦想做某事
at my age 以我的年纪
throw away 丢弃

--------------------
v. + of/from/in/on

think of sth. 考虑某事
write to sb. 写给某人
decide to do sth. 决定做某事


** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
Imagine a situation when it might be necessary to send a message in a bottle.
Students in England often work for the post office during the Christmas holidays. What sorts of jobs do students in your country do during their vacations?
