* Lesson 1 A private conversation
#+begin_verse
Why did the writer complain to the people behind him?

Last week I *went to the theatre*.
I *had a very good seat*.
The play was very interesting.

I did not enjoy it.
A young man and a young woman were sitting behind me.
They were talking loudly.

I *got very angry*.
I could not hear the actors.
I turned round.
I looked at the man and the woman angrily.
They did not pay any attention.

*In the end*, I could not bear it.
I turned round again.
'I can't hear a word!' I said angrily.
'*It's none of your business*,' the young man said rudely. 'This is a private conversation.'
#+end_verse

* Lesson 2 Breakfast or lunch?
#+begin_verse
Why was the writer's aunt surprised?

It was Sunday.
I never *get up early* on Sundays.
I sometimes stay in bed until lunchtime.

Last Sunday I got up very late.
I looked out of the window.
It was dark outside.
'What a day!' I thought. 'It's raining again.'

*Just then*, the telephone rang.
It was my aunt Lucy.
'I've just arrived by train,' she said.
'I'm coming to see you.'
'But I'm still *having breakfast*,' I said.
'What are you doing?' she asked.
'I'm having breakfast,' I repeated.
'Dear me,' she said. 'Do you always get up so late? It's one o'clock!'
#+end_verse

* Lesson 3 Please send me a card.
#+begin_verse
How many cards did the writer send?

Postcards always spoil my holidays.
Last summer, I went to Italy.
I visited museums and sat in public gardens.
A friendly waiter *taught me a few words of Italian*.
Then he *lent me a book*.
I read a few lines, but I did not understand a word.
Every day I *thought about* postcards.
My holidays passed quickly, but I did not send cards to my friends.
*On the last day* I made a big decision.
I got up early and bought thirty-seven cards.
I *spent the whole day in my room*, but I did not write a single card!
#+end_verse

* Lesson 4 An exciting trip
#+begin_verse
Why is Tim finding this trip exciting?

I have just received a letter from my brother, Tim.
He is in Australia.
He has been there for six months.
Tim is an engineer.
He is working for a big firm and he has already visited *a great number of* different places in Australia.
He has just bought an Australian car and *has gone to Alice Springs*, a small town in the centre of Australia.
He will soon visit Darwin.
From there, he will *fly to Perth*.
My brother has never been abroad before, so he is *finding this trip very exciting*.
#+end_verse

* Lesson 5 No wrong numbers 
#+begin_verse
What does 'No wrong numbers' mean?

Mr. James Scott has a garage in Silbury
	and now he has just bought another garage in Pinhurst.
Pinhurst *is only five miles from* Silbury,
	but Mr. Scott cannot *get a telephone for his new garage*,
	so he has just bought twelve pigeons.
Yesterday, a pigeon carried the first message from Pinhurst to Silbury.
The bird *covered the distance in three minutes*.
*Up to now*, Mr. Scott has sent *a great many* requests for spare parts
	and other urgent messages from one garage to the other.
*In this way*, he has begun his own private telephone service.
#+end_verse
* Lesson 6 Percy Buttons 

#+begin_verse
Who is Percy Buttons?

I have just *moved to a house* in Bridge Street.
Yesterday a beggar *knocked at my door*.
He *asked me for a meal and a glass of beer*.
*In return for* this, the beggar *stood on his head* and sang songs.
I gave him a meal.
He ate the food and drank the beer.
Then he put a piece of cheese in his pocket and went away.
Later a neighbor told me about him.
Everybody knows him.
His name is Percy Buttons.
He *calls at* every house in the street *once a month*
	and always *asks for a meal and a glass of beer*.
#+end_verse
* Lesson 7 Too late 

#+begin_verse
Did the detectives save the diamonds?

The plane was late and detectives were waiting at the airport *all morning*.
They were expecting *a valuable parcel of diamond* from South Africa.
*A few hours earlier*, someone had told the police that thieves would *try to steal* the diamonds.
When the plane arrived, some of the detectives were waiting inside the main building
	while others were waiting on the airfield.
Two men took the parcel off the plane and carried it into the Customs House.
While two detectives were *keeping guard* at the door,
	two others opened the parcel.
*To their surprise*, *the precious parcel was full of stones and sand*!
#+end_verse
* Lesson 8 The best and the worst 

#+begin_verse
Why is Joe's garden the most beautiful one in the town?

Joe Sanders has the most beautiful garden in our town.
Nearly everybody *enters for* 'The Nicest Garden Competition' each year,
	but Joe wins every time.
Bill Frith's garden is larger than Joe's.
Bill works harder than Joe and grows more flowers and vegetables,
	but Joe's garden is more interesting.
He has *made neat paths* and has built a wooden bridge over a pool.
I like gardens too, but I do not like hard work.
Every year I *enter for* the garden competition too,
	and I always *win a little prize* for the worst garden in the town!
#+end_verse

* Lesson 9 A cold welcome

#+begin_verse
What does 'a cold welcome' refer to?

On Wednesday evening, we went to the Town Hall.
It was *the last day of the year*
	and *a large crowd of* people had gathered under the Town Hall clock.
It would strike twelve *in twenty minutes' time*.
Fifteen minutes passed and then, at five to twelve, the clock stopped.
The big minute hand did not move.
We waited and waited, but nothing happened.
Suddenly someone shouted, 'It's two minutes past twelve! The clock has stopped!'
I looked at my watch.
It was true.
The big clock *refused to welcome* the New Year.
*At that moment* everybody *began to laugh* and sing.
#+end_verse
* Lesson 10 Not for jazz 

#+begin_verse
What happened to the clavichord?

We have an old musical instrument.
It is called a clavichord.
It *was made in* Germany in 1681.
Our clavichord is kept in the living-room.
It has *belonged to* our family for a long time.
The instrument was bought by my grandfather many years ago.
Recently it was damaged by a visitor.
She tried to *play jazz* on it!
She struck the keys too hard and two of the strings were broken.
My father was shocked.
Now we *are not allowed to touch* it.
It is being repaired by a friend of my father's.
#+end_verse
* Lesson 11 One good turn deserve another

#+begin_verse
Who paid for Tony's dinner?

I was having breakfast in a restaurant, when Tony Steele came in.  
Tony worked in a lawyers' office years ago,
	but he is now working at a bank.  
He *gets a good salary*,
	but he always *borrows money from his friends*, and never *pays it back*.
He saw me and came and sat at the same table.  
He has never borrowed money from me.  
While he was eating, I *asked him to lend* twenty pounds.  
To my surprise, he gave the money immediately.  
"I have never borrowed money from you."
	he said: "so now you can *pay for my dinner*."  
#+end_verse
* Lesson 12 Goodbye and good luck

#+begin_verse
Where is Captain Alison going and how?

Our neighbour, Captain Charles Alison,will *sail from Portsmouth* tomorrow.
We'll meet him at the harbour early in the morning.
He will be in his small boat, Topsail.
Topsail is a famous little boat.
It has sailed across the Atlantic many times.
Captain Alison will *set out* at eight o'clock, so we'll *have plenty of time*.
We'll see his boat and then we'll *say goodbye to him*.
He *will be away* for two months.
We *are very proud of* him.
He will *take part in* an important race across the Atlantic.
#+end_verse
* Lesson 13 The Greenwood Boys  

#+begin_verse
Why will the police have a difficult time?

The Greenwood Boys are *a group of* pop singer.
*At present*, they are visiting *all parts of the country*.
They will be arriving here tomorrow.
They will be coming by train
	and most of the young people in the town will be meeting them at the station.
Tomorrow evening they will be singing at the Workers' Club.
The Greenwood Boys will be staying for five days.
During this time, they will *give five performances*.
*As usual*, the police will *have a difficult time*.
They will be trying to *keep order*.
It is always the same *on these occasions*.  
#+end_verse
* Lesson 14 Do you speak English?

#+begin_verse
Did the young man speak English?

I *had an amusing experience* last year.
After I had left a small village in the south of France, I *drove on* the next town.
*On the way*, a young man *waved to me*.
I stopped and he *asked me for a lift*.
As soon as he had got into the car,
	I said good morning to him *in French* and he replied in the same language.
*Apart from* a few words, I do not know any French at all.
Neither of us spoke during the journey.
I had nearly reached the town,
	when the young man suddenly said, very slowly,
		'Do you speak English?'
As I soon learnt, he was English himself!
#+end_verse
* Lesson 15 Good news
#+begin_verse
What was the good news?

The secretary told me that Mr. Harmsworth would see me.
I felt very nervous when I went into his office.
He did not look up from his desk when I entered.
After I had sat down, he said that business was very bad.
He told me that the firm could not *afford to pay* such large salaries.
Twenty people had already left.
I knew that *my turn had come*.
'Mr. Harmsworth,' I said *in a weak voice*.
'Don't interrupt', he said.
Then he smiled and told me I would receive an extra thousand pounds a year!
#+end_verse
* Lesson 16 A polite request

#+begin_verse
What was the polite request?

If you *park your car* in the wrong place, a traffic policeman will soon find it.
You will be very lucky if he lets you go without a ticket.
However, this does not always happen.
Traffic police are sometimes very polite.
During a holiday in Sweden, I found this note on my car:
	'Sir, we welcome you to our city.
This is a "No Parking" area.
You will enjoy your stay here if you *pay atention to* our street signs.
This note is only a reminder.'
If you receive a request like this, you cannot *fail to obey* it!
#+end_verse
* Lesson 17 Always young

#+begin_verse
Why doesn't Aunt Jennifer tell anyone how old she is?

My aunt Jennifer is an actress.
She must be *at least* thirty-five years old.
*In spite of this*, she often appears on the stage as a young girl.
Jennifer will have to *take part in* a new play soon.
This time, she will be a girl of seventeen.
In the play, she must appear in a bright red dress and long black stockings.
Last year in another play, she had to wear short socks and a bright, orange-coloured dress.
If anyone ever asks her how old she is, she always answers,
	'Darling, it must be terrible to be grown up!'
#+end_verse
* Lesson 18 He often does this!
#+begin_verse
What had happened to the writer's bag?

After I had had lunch at a village pub, I looked for my bag.
I had left it on a chair beside the door and now it wasn't there!
As I was *looking for* it, the landlord came in.
'Did you *have a good meal*?' he asked.
'Yes, thank you,' I answered,
	'but I can't *pay the bill*.
I haven't got my bag.'
The landlord smiled and immmediately went out.
*In a few minutes* he returned with my bag and gave it back to me.
'I'm very sorry,' he said.
'My dog had taken it into the garden.
He often does this!'
#+end_verse
* Lesson 19 Sold out
#+begin_verse
When will the writer see the play?

'The play may begin at any moment,' I said.
'It may have begun already,' Susan answered.
I *hurried to the ticket office*.
'May I have two tickets please?' I asked.
'I'm sorry, we've *sold out*,' the girl said.
'*What a pity*!' Susan exclaimed.
Just then, a man hurried to the ticket office.
'Can I return these two tickets?' he asked.
'Certainly,' the girl said.
I went back to the ticket office *at once*.
'Could I have those two tickets please?' I asked.
'Certainly,' the girl said, 'but they're for next Wednesday's performance.
Do you still want them?'
'I *might as well* have them,' I said sadly.
#+end_verse
* Lesson 20 One man in a boat

#+begin_verse
Why is fishing the writer's favourite sport?

Fishing is my favourite sport.
I often fish for hours without catching anything.
But this does not worry me.
Some fishermen are unlucky.
*Instead of catching fish*, they catch old boots and rubbish.
I am even less lucky.
I never catch anything -- not even old boots.
After having *spent whole mornings on the river*,
	I always go home with an empty bag.
'You must *give up fishing*!' my friends say.
'It's a waste of time.
'But they don't realize one important thing.
*I'm not really interested* in fishing.
I am only interested in sitting in a boat and doing nothing at all.
#+end_verse
* Lesson 21 Mad or not

#+begin_verse
Why do people think the writer is mad?

Aeroplanes are slowly *driving me mad*.
I live near an airport
	and passing planes can be heard night and day.
The airport was built years ago,
	but *for some reason* it could not be used then.
Last year, however, it *came into use*.
Over a hundred people must have been driven away from their homes by the noise.
I am one of the few people left.
Sometimes I think this house will be knocked down by a passing plane.
I have been offered *a large sum of money* to go away,
	but I *am determined to stay* here.
Everybody says I must be mad
	and they are probably right.
#+end_verse
* Lesson 22 A glass envelope

#+begin_verse
How did Jane receive a letter from a stranger?

My daughter, Jane, never *dreamed of receiving* a letter from a girl *of her own age* in Holland.
Last year, we were travelling across the Channel
	and Jane put a piece of paper with her name and address on it into a bottle.
She threw the bottle into the sea.
She never *thought of* it again,
	but ten months later, she received a letter from a girl in Holland.
Both girls *write to each other* regularly now.
However, they have *decided to use* the post office.
Letters will cost a little more,
	but they will certainly travel faster.
#+end_verse
* Lesson 23 A new house

#+begin_verse
Why is the new house special?

I *had a letter from my sister* yesterday.
She lives in Nigeria.
In her letter, she said that she would come to England next year.
If she comes, she will *get a surprise*.
We are now living in a beautiful new house in the country.
Work on it had begun before my sister left.
The house was completed five months ago.
In my letter, I told her that she could stay with us.
The house has many large rooms
	and there is a lovely garden.
It is a very modern house,
	so it looks strange to some people.
It must be the only modern house in the district.
#+end_verse
* Lesson 24 It could be worse

#+begin_verse
Had the writer's money been stolen?

I entered the hotel manager's office and sat down.
I had just lost $50 and I felt very upset.
'I left the money in my room,' I said, 'and it's not there now.'
The manager was sympathetic,
	but he could do nothing.
'Everyone's losing money these days,' he said.
He *started to* *complain about this wicked world*
	but was interrupted by a knock at the door.
A girl came in and put an envelope on his desk.
It contained $50.
'I found this outside this gentleman's room,' she said.
'Well,' I said to the manager, 'there is still some honesty in this world!'
#+end_verse
