#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 14th WHAT WE SHOULD KNOW BY THE END
#+begin_verse
'Soon you will die,
  and still you aren't sincere,
  undisturbed,
  or free from suspicion that external things can harm you,
  nor are you gracious to all,
  knowing that wisdom and acting justly are one and the same.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
37 rom what we understand,
  Marcus wrote many of his meditations later in life,
  when he was suffering from serious illnesses.
So when he says,
  'Soon you will die,
  ' he was speaking frankly to himself about his own mortality.
How scary that must have been.
He was staring at the real possibility of death and not liking what he saw in these last minutes.
Sure,
  he'd accomplished many things in his life,
  but his emotions were still the cause of discomfort,
  pain,
  and frustration.
He knew that with his limited time left,
  better choices would provide relief.
Hopefully,
  you have a lot more time left—but that makes it even more important to make headway while you still can.
We are unfinished products up until the end,
  as Marcus knew very well.
But the earlier we learn it,
  the more we can enjoy the fruits of the labor on our character— and the sooner we can be free (or freer) of insincerity,
  anxiety,
  ungraciousness,
  and un-Stoic-ness.
T
#+end_verse