#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 24th MEANINGLESS . . . LIKE A FINE WINE
#+begin_verse
'You know what wine and liqueur tastes like. It makes no difference whether a hundred or a thousand bottles pass through your bladder—you are nothing more than a filter.' —SENECA,
  MORAL LETTERS,
  77.
16 ere we have another contemptuous expression,
  this time from Seneca,
  who,
  given his reputation for opulence,
  probably enjoyed a nice drink from time to time.
His point will probably rattle anyone for whom success and adulthood has turned them into a wine snob (though the logic can be applied just as easily to foodies,
  techies,
  audiophiles,
  and the like).
As fun and exciting and pleasurable as these pleasures are,
  it's worth putting them in their place.
You don't get a prize at the end of your life for having consumed more,
  worked more,
  spent more,
  collected more,
  or learned more about the various vintages than everyone else.
You are just a conduit,
  a vessel that temporarily held or interacted with these fancy items.
If you find yourself lusting over them,
  this meditation might help reduce their luster just a smidge.
O
#+end_verse