#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 18th WHAT COMES TO US ALL
#+begin_verse
'Both Alexander the Great and his mule-keeper were both brought to the same place by death—they were either received into the all-generative reason,
  or scattered among the atoms.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
24 n a world that is in many ways becoming more and more unequal,
  there aren't many truly equalitarian experiences left.
When Benjamin Franklin observed that 'in this world nothing can be said to be certain,
  except death and taxes,
  ' he couldn't have known how good some people would get at avoiding their taxes.
But death?
That's still the one thing that everyone experiences.
We all face the same end.
Whether you conquer the known world or shine the shoes of the people who do,
  at the end death will be a radical equalizer—a lesson in abject humility.
Shakespeare had Hamlet trace out the logic in stark terms for both Alexander and Julius Caesar:
  'Imperious Caesar,
  dead and turn'd to clay,
  Might stop a hole to keep the wind away:
  O,
  that that earth,
  which kept the world in awe,
  Should patch a wall to expel the winter flaw!' The next time you feel yourself getting high and mighty—or conversely,
  feeling low and inferior—just remember,
  we all end up the same way.
In death,
  no one is better,
  no one is worse.
All our stories have the same finale.
T
#+end_verse