#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 31st GET ACTIVE IN YOUR OWN RESCUE
#+begin_verse
'Stop wandering about! You aren't likely to read your own notebooks,
  or ancient histories,
  or the anthologies you've collected to enjoy in your old age. Get busy with life's purpose,
  toss aside empty hopes,
  get active in your own rescue—if you care for yourself at all—and do it while you can.' —MARCUS AURELIUS,
  MEDITATIONS,
  3.
14 he purpose of all our reading and studying is to aid us in the pursuit of the good life (and death).
At some point,
  we must put our books aside and take action.
So that,
  as Seneca put it,
  the 'words become works.' There is an old saying that a 'scholar made is a soldier spoiled.' We want to be both scholars and soldiers—soldiers in the good fight.
That's what's next for you.
Move forward,
  move onward.
Another book isn't the answer.
The right choices and decisions are.
Who knows how much time you have left,
  or what awaits us tomorrow?
W STAYING STOIC e hope this book has lasted you a year (though we won't fault you if you read through it without regard to the date.
In fact,
  we'd be flattered).
So what's next?
We hope that you get involved with Stoicism and make it a daily practice in your life.
To that end,
  we've created DailyStoic.
com—a site full of interviews with Stoic practitioners,
  articles,
  exercises,
  and a daily email where you can get more Stoic wisdom delivered to your inbox every single day.
You can go to DailyStoic.
com right now or email hello@DailyStoic.
com to get a special package of Stoic bonuses,
  including what books to read next and more material that we couldn't fit in this book.
Hope to see you there soon!
L A MODEL OF LATE STOIC PRACTICE AND GLOSSARY OF KEY TERMS AND PASSAGES ate Stoic thought of the second century,
  as articulated in the writings of Epictetus and Marcus Aurelius,
  paints a vivid picture of the work of philosophy in producing both self-coherence and progress on the path to virtue.
As suggested in the work of Pierre Hadot and A.
A.
Long (see Suggestions for Further Reading),
  we have developed and formalized Epictetus's three disciplines into a chart that presents the progressive nature of the late Stoic prescription for handling ourselves and our actions in the world.
This chart brings together the three topoi (topics,
  or fields of study) and three different levels of training (askêsis) suggested by Epictetus and shows how they correlate (noted in Hadot) to the pursuit of virtue as expressed by Marcus Aurelius.
The chart itself comes from these key passages in Epictetus:
  'There are three areas in which the person who would be wise and good must be trained. The first has to do with desires and aversions—that a person may never miss the mark in desires nor fall into what repels them. The second has to do with impulses to act and not to act—and more broadly,
  with duty— that a person may act deliberately for good reasons and not carelessly. The third has to do with freedom from deception and composure and the whole area of judgment,
  the assent our mind gives to its perceptions. Of these areas,
  the chief and most urgent is the first which has to do with the passions,
  for strong emotions arise only when we fail in our desires and aversions.' —EPICTETUS,
  DISCOURSES,
  3.
2.
1–3a'That's why the philosophers warn us not to be satisfied with mere learning,
  but to add practice and then training.
For as time passes we forget what we learned and end up doing the opposite,
  and hold opinions the opposite of what we should.
' —EPICTETUS,
  DISCOURSES,
  2.9.13–14 We have placed key terms in each level of the chart. There is progress (prokopê) upward out of deception,
  false opinion,
  and error—through impulse control—to more clear judgments and knowledge (selfcoherence);
  and there is progress across the levels of training (study/manthanô,
  practice/meletaô,
  hard training/askeô) through the remediation of habit,
  acting more appropriately,
  and improving judgment toward living the virtues. We offer an annotated glossary of key Stoic terms and passages following the chart. Visit bit.ly/2dC85K1 for a larger version of this table. Adiaphora (ἀδιάφορα):
  indifferent things;
  neither good nor bad in an absolute moral sense. In Stoic thought,
  all things outside our sphere of reasoned choice (see prohairesis) are indifferent.In a relative sense,
  some of the things outside our control are preferred or dispreferred goods (proêgmena/aproêgmena). Marcus says (5.20) that people who thwart the progress of our reasoned choice,
  although normally our natural concern,
  also become indifferent to us. The term appears in Epictetus's Discourses seventeen times and once in Enchiridion;
  see Discourses 2.19.12b–13 and 3.3.1. In Marcus it appears six times;
  see also 8.56 (my prohairesis is indifferent to that of others,
  and vice versa). Agathos (ἀγαθός):
  good,
  or a proper object of desire. Epictetus upholds the classic Stoic position when he says that the good (and evil) are only to be found in us,
  in our prohairesis,
  not in external things (Discourses 2.16.1),
  and when he says,
  'God laid down this law,
  saying:
  if you want some good,
  get it from yourself' (1.
29.
4).
'Protect your own good in all that you do' (4.3.11). Anthrôpos (ἄνθρωπος):
  a human being,
  human beings in general. For Epictetus (Discourses 2.10.1),
  above all we are human beings whose power of reasoned choice (prohairesis) supervises all and is completely free. A 'beautiful human being' possesses the virtues (Discourses 3.
1.
6b– 9).
We must be a 'unified human being' (Discourses 3.15.13),
  what Hadot calls self-coherence (The Inner Citadel,
  pp. 130–31). In Marcus (see 5.1,
  5.20,
  8.1,
  8.5,
  8.26),
  the term is used in conjunction with an emphasis on what our proper concern and work should be. Apatheia (ἀπάθεια):
  passionless calm,
  peace of mind. In verb form,
  ἀπαθέω means to free from passion. Epictetus:
  Discourses (seven times noun,
  eleven times verb),
  see 4.3.8;
  twice in Enchiridion. Marcus uses it in verb form four times;
  see 6.16.2b–4a. In its single use as a noun,
  he says that the closer a person is to apatheia,
  the stronger they are (11.18.5b). See pathos. Aphormê (ἀφορμή):
  avoidance,
  disinclination,
  the impulse not to act (as a result of ekklisis). Opposite of hormê. Hormê/Aphormê is the second of the three areas of training for Epictetus (3.2.1–3a),
  and the term appears frequently in the Discourses. Marcus doesn't use the term in this sense,
  only hormê. Apotynchanô (ἀποτυγχάνω):
  to fail in gaining,
  hitting,
  achieving;
  to miss one's purpose or to err. It appears twenty-four times in Epictetus,
  often with orexis/oregô;
  see especially 3.2.1–3a. Diogenes Laertius says Zeno defined 'want' as failing to gain what we yearn for or reach out for (Lives of the Eminent Philosophers 7.
1.
113).
The term doesn't appear in Marcus.
This experience is a fundamental source of disturbance in life.
See also hamartanô.
Aproêgmena (ἀπροηγμένα):
  dispreferred things;
  indifferent in an absolute moral sense,
  but things of relative negative value and naturally undesirable things,
  such as illness.
Opposite of proêgmena.
These terms don't appear in either Epictetus or Marcus,
  but we know from Diogenes Laertius that they were common Stoic teaching from Zeno and Chrysippus through Posidonius (Lives of the Eminent Philosophers 7.
1.
102ff).
Cicero rehearses Zeno's use of the terms and offers the Latin equivalents of reiecta/praeposita (On the Ends of Good and Evil and Academica,
  1.
X.
36–39).
Seneca does not follow Cicero in this use,
  but uses commoda/incommoda (advantageous/disadvantageous).
'There are things in life which are advantageous and disadvantageous—both beyond our control' (Moral Letters 92.16). Cicero makes it a subclass of reiecta/praeposita (On the Ends of Good and Evil 3.21). Aretê (ἀρετή):
  Virtue,
  goodness,
  and human excellence;
  the source of absolute value. Hadot notes that the four cardinal virtues of Plato are not fully present in Arrian's presentation of Epictetus (The Inner Citadel,
  p. 238),
  but that in Marcus,
  who followed Epictetus closely,
  they have a clear articulation and correlation to what Hadot calls 'the three acts of the soul' (see chart).
Diogenes Laertius says that the four cardinal virtues were primary for the Stoics (Lives of the Eminent Philosophers,
  'Zeno,
  ' 7.
92b):
  σωφροσύνη/sôphrosunê/self-control,
  δικαιοσύνη/dikaiosunê/justice,
  ἀνδρεία/andreia/courage,
  φρόνησις/phronêsis/wisdom.
Chrysippus said that experiencing wisdom (phronimos) for even a moment is equal to an eternityof exercising aretê (Plutarch,
  Moralia 1062).
Musonius Rufus said,
  'The human being is born with an inclination toward virtue' (Lectures 1.7.1–2). Marcus mentions all four virtues in 3.6.1 and 5.12,
  and three (without courage) in 7.63,
  8.32,
  and 12.15. We present them here as the aims of moral progress to which all our activity in the world is directed. Marcus says we should let our virtues shine until we are extinguished (12.15). Epictetus does cite justice and self-control together in his discussion of virtue in 3.1.6b–9,
  where his use of σωφροσύνη is milder in the 'even-tempered' sense (contrasted by him with 'undisciplined'),
  and his preferred term for selfcontrol here (and elsewhere,
  appearing with wisdom/φρονίμῳ in 2.21.9) is ἐγκρατεῖς/egkrateis/mastery,
  or exercising control over (contrasted with ἀκρατεῖς/akrateis/uncontrolled). Seneca uses the Latin virtus and says that 'virtue is the only good' and is nothing less than 'true and steadfast judgment' (Moral Letters 7.32). Askêsis (ἄσκησις):
  exercise,
  practice,
  disciplined training designed to achieve virtue. Epictetus sees three areas of training (Discourses 3.2.1–3a,
  3.12.8)—the famous doctrine of three topics (topoi) that scholars think was Epictetus's unique contribution to late Stoicism (see Long's Epictetus:
  A Stoic and Socratic Guide to Life,
  pp. 112–118;
  Hadot's The Inner Citadel,
  pp. 89– 100). Before Epictetus,
  Seneca affirms the long-standing Stoic division of philosophy into three parts,
  which he calls 'the moral,
  the natural,
  and the rational' (Moral Letters 89.
9).
Epictetus,
  we argue,
  also sees three levels of discipline,
  moving from learning/study (μανθάνω/manthanô,
  appearing seventy-nine times) to practice (μελετάω/meletaô,
  appearing fifty-four times;
  see Discourses 2.
19.
29–34,
  where he says 'learn and diligently practice') to more rigorous training (ἀσκέω/ἄσκησις,
  appearing forty times). For the three levels of discipline,
  see 2.9.13–14. For Epictetus,
  the exercise and training analogies run from wrestling and athletics (see the 'invincible athlete' in 1.
18.
21–23;
  'true athlete in rigorous training' in 2.18.27–2),
  to the pankration (3.10.6–7),
  and the ultimate 'hard winter training' (χειμασκησαι/cheimaskêsai) of soldiers (1.
2.
32,
  4.
8.
35–37).
While each of these three areas of training and three levels of discipline reach into and inform one another,
  there is a clear sense of hierarchy in the acts of the soul,
  moving up from desire through action to assent,
  and of making forward progress in our actions in the world,
  from study to practice to hard training,
  toward virtue (see chart).
For Marcus,
  who is often derisive of mere study,
  books,
  and displays of learning (2.
2,
  3.
14,
  5.
5,
  5.
9),
  these words scarcely appear.
He seems more interested in simply getting straight to putting things to the test in everyday life by following the dictates of our guiding reason (hêgemonikon).
In this way he is very much in tune with Epictetus's memorable admonition against spouting what you've learned without having digested it (see Discourses 3.
21.
1–3).
For Marcus,
  the point of it all is to use our reason to produce in action the virtues of self-control,
  courage,
  justice,
  and wisdom,
  which correlate to the topoi of Epictetus (see chart).
Ataraxia (ἀταραξία):
  tranquility,
  freedom from disturbance by external things.
It is the fruit of following philosophy,
  according to Epictetus (Discourses 2.
1.
21–22).
It appears fourteen times in the Discourses and twice in the Enchiridion;
  see Discourses 2.
2 (Arrian's caption of section),
  2.
18.
28,
  4.
3.
6b–8,
  and 4.
6.
34–35.
It appears once in Marcus (9.
31;
  not here).
Axia (ἀξία):
  the true value or worth of things;
  the relative value of things preferential;
  of people,
  meaning reputation or what's deserved.
It appears eighteen times in Marcus;
  see 4.
32,
  5.
1,
  5.
36,
  9.
1.
1,
  and 12.
1.
Marcus quotes Epictetus on this concept in discussing how to use the power of assent in the area of our impulses (11.
37).
For Epictetus,
  the term appears twenty-nine times in the Discourses and twice in Enchiridion (36;
  not here).
See Discourses 1.
2.
5–7,
  4.
1.
170,
  4.
3.
6–8,
  and 4.
5.
34–37.
Overall,
  the idea is that we too often trade things of great value for things of very little value,
  an idea that goes back to the teachings of Diogenes of Sinope,
  the founder of the Cynic school,
  as described by Diogenes Laertius (Lives of the Eminent Philosophers 6.
2.
35b).
Daimôn (δαίμων):
  divine spirit within humans;
  our individual genius.
Chrysippus held that a happy and well-flowing life was the result 'when the affairs of life are in every way tuned to theharmony between the individual divine spirit and the will of the director of the universe' (Lives of the Eminent Philosophers 7.1.88). Epictetus tells us never to worry because we are never alone:
  God is always within,
  as is our own daimôn (Discourses 1.14.14;
  not here). Diairesis (διαίρεσις):
  analysis,
  division into parts. Used when distinguishing what is subject to our power of choice from what is not. Dianoia (διανοία):
  thought,
  intelligence,
  purpose,
  faculty of mind. Haines notes:
  'not affected by the motions of the pneuma.
' Dikaiosunê (δικαιοσύνη):
  justice,
  righteousness. Diogenes Laertius noted that for the Stoics,
  it meant 'being in harmony with the law and tending to bring people together' (Lives of the Eminent Philosophers 7.
99;
  not here).
It is one of the four cardinal virtues (i.
e.
,
  self-control,
  justice,
  courage,
  and wisdom).
The word is used seventeen times in Marcus,
  always in the spirit Diogenes Laertius outlines,
  where it appears with the other virtues (see especially 3.
6,
  5.
12,
  7.
63,
  and 12.
15).
Epictetus is notable in 3.
1.
6b–9,
  where he speaks of 'the just' as the kind of person we should strive to be. Dogma (δόγμα):
  that which seems to one;
  opinion or belief;
  philosophically,
  dogmata are principles or judgments established by reason and experience. Haines notes that 'what the sensations are to the body and impulses to the soul,
  dogmata are to the intelligence.
' Epictetus takes aim at the untested form of dogmata by framing them as τὰ πονηρὰ δόγματα,
  or oppressive or worthless opinions that must be rooted out by our reasoned choice (Discourses 3.3.18–19;
  see also 3.19.2–3) before they destroy our inner fortress (4.1.86). The term appears more than one hundred times in Epictetus (see Enchiridion 5,
  where he says that it's not things that disturb us,
  but our judgments/dogmata about them) and twenty-three times in Marcus (see especially 4.49,
  7.2,
  8.1,
  8.22,
  and 8.47,
  where he often talks about straightening out your principles). Marcus and Epictetus also use the word krima (κρῖμα) when talking about decisions and judgment (Marcus,
  Meditations 11.11,
  8.47;
  Epictetus,
  Discourses 4.11.7). Dokimazein (δοκιμάζω):
  to assay;
  to put to the test;
  to thoroughly examine. This is a key verb in understanding Epictetus's Stoicism (found ten times in the Discourses and once in the opening of the Enchiridion),
  but it was not used by Marcus. The word carries the meaning of the assayist,
  one who tests fine metals and coins to verify their authenticity. In one of the most memorable passages in Epictetus,
  he compares our need to test impressions to what is done with coins and how the skilled merchant can hear a counterfeit coin cast upon a table just as a musician would detect a sour note (Discourses 1.2.7–11ff). See also the exercises he gives for handling impressions (Discourses 2.18.24;
  Enchiridion 1.5). As sense impressions need to be put to the test,
  so too our judgments (dogmata/theôrêma) need a tough cross-examination (ἐλέγχω;
  used by both Epictetus and Marcus) to be fully tested. Doxa (δόξα):
  belief,
  opinion. Ekklisis (ἔκκλισις):
  aversion;
  inclination away from a thing. The opposite of,
  but often appearing with,
  orexis. This is the first level of self-coherence (see chart). Epictetus warns repeatedly that with aversions we must be careful to apply them only to our own concerns and not to those controlled by others (see Discourses 4.1.81–82ff;
  not here). The word appears fiftythree times in the Discourses. In a vivid metaphor of a sparring match,
  Marcus tells us we can avoid people who might have ill intent without being suspicious toward them (6.20). In step with Epictetus,
  Marcus urges us to limit our aversion to only those things in our power (8.7). See orexis. Ekpyrôsis (ἐκπύρωσις):
  cyclical conflagration (birth and rebirth) of the universe. This idea,
  central to Stoic physics and cosmology,
  goes back to Heraclitus (Marcus 3.3;
  not here). Stoicsequate this fire with the all-permeating reason (logos spermatikos) of the universe (see Marcus 6.24). Eleutheria (ἐλευθερία):
  freedom,
  liberty. The masses say that only the free can be educated,
  but the Stoic says that only the educated can be free (Discourses 2.1.21–22). Including the adjectival form,
  it appears more than one hundred times in the Discourses. Marcus uses the noun five times (see 5.9). Eph' hêmin (ἐφ' ἡμῖν):
  what is up to us;
  what is in our control;
  our correct use of impressions,
  impulses,
  and judgments.
The Enchiridion (or Handbook) of Epictetus opens with this most famous of all Stoic phrases.
Epictetus says when we want something outside our control,
  we are stricken with anxiety (Discourses 2.
13.
1).
Our judgments about what is up to us determine our freedom (3.
26.
34–35).
Epistêmê (ἐπιστήμη):
  certain and true knowledge,
  over and above that of katalêpsis.
Ethos (ἔθος):
  custom or habit.
See also hexis.
In late Stoic practice,
  there is a great focus on habit.
Musonius Rufus's ideas about education were aimed at addressing the upbringing,
  environment,
  and habits that vary from person to person (Lectures 1.
1).
Epictetus carries this focus on habit forward:
  'Since habit is such a powerful influence,
  and we're used to pursuing our impulses to gain and avoid outside our own choice,
  we should set a contrary habit against that,
  and where appearances are really slippery,
  use the counterforce of our training' (Discourses 3.12.6). He also talks about the importance of using a contrary,
  opposing habit in 1.27.4. The term appears seventeen times in Epictetus's Discourses. Marcus uses this term four times. Eudaimonia (εὐδαιμονία):
  happiness,
  flourishing,
  well-being. Epictetus says that God made human beings to be happy and stable/serene (εὐσταθεῖν/eustathein;
  Discourses 3.24.2b–3). Eudaimonia appears thirteen times in the Discourses and once in the Enchiridion. Epictetus holds that it is incompatible with yearning for what we don't have (Discourses 3.24.17). It appears twice in Marcus (7.67) in conjunction with 'life,
  ' which,
  he says,
  depends on the fewest possible things (see also 7.17). Marcus has one other equivalent word in his use of εὐζωήσεις/euzôêseis,
  or 'happy in life' (3.
12;
  none of these three reproduced here).
Eupatheia (εὐπάθεια):
  good passions or emotions (as contrasted with pathos),
  the result of correct judgments and virtuous actions.
Diogenes Laertius says,
  'The Stoics assert there are three good emotional states (eupatheia):
  joy,
  caution,
  and wishing . . . joy is rational elation . . . caution is rational avoidance . . .wishing is rational inclination . . .under wishing they place goodwill,
  benevolence,
  friendliness and affection;
  under caution,
  respect and modesty;
  under joy,
  delight,
  good cheer and contentment' (Lives of the Eminent Philosophers 7.116). Hamartanô (ἁμαρτάνω):
  to do wrong,
  err,
  fail one's purpose. The verb appears twenty-eight times in Epictetus and thirty-four times in Marcus. Also,
  hamartia (ἁμαρτία)—a failure,
  fault,
  error,
  to do wrong to another—appears three times in Marcus,
  notably in 10.30,
  when he talks about seeing another's wrongdoing from the standpoint of our own failings. Both Epictetus and Musonius Rufus often use the obverse as the ideal,
  being free from error,
  anamartêtos (ἀναμάρτητος),
  which,
  although not possible,
  is what we should strive for (see especially Discourses 4.12.19;
  Lectures 2.5.1). Since Aristotle's Poetics,
  the concept had been the fatal flaw or decision that leads to a tragic demise. The Stoics part ways with any tragic thinking,
  on the one hand,
  and,
  on the other,
  with any notion of original sin—all sin is the result of bad habit,
  following common opinion,
  and bad judgments. Philosophy is meant to help us scrape the accumulated errors of existence from our souls. Hêgemonikon (ἡγεμονικόν):
  ruling or guiding reason;
  ruling principle. A. A. Long says the term,
  meaning 'suited to command,
  ' was borrowed from Isocrates,
  the Athenian rhetorician,
  and was taken up by the early Stoics to represent the intellectual part of the soul as distinct from thesenses (Greek Models of Mind and Self,
  p. 89). Long notes that by the time of the late Stoics,
  Epictetus had applied it even to the souls of animals,
  which lack rationality (Epictetus:
  A Stoic and Socratic Guide to Life,
  p. 211),
  and said it means 'the governing faculty of the mind.
' Hadot calls it the superior or guiding part of the soul. Marcus uses it as a unique property of human beings (especially in 12.1 and 12.33). Epictetus's Discourses (twenty-six references):
  1.26.15,
  1.20.11,
  4.4.43,
  4.5.5. Marcus Aurelius (forty-six references):
  3.9,
  4.38,
  5.11,
  8.48,
  8.56,
  9.22,
  9.26,
  12.1,
  12.33. Whereas Epictetus leans heavily on prohairesis,
  Marcus prefers hêgemonikon:
  'How does your ruling reason manage itself?
For in that is the key to everything.
Whatever else remains,
  be it in the power of your choice or not,
  is but a corpse and smoke' (12.
33).
Heimarmenê (εἱμαρμένη):
  fate,
  destiny.
Stoics were compatibilists about the free will and determinism question—all things are determined,
  but our response is entirely our own.
See pronoia.
Hexis (ἕξις):
  abstract noun built on echein,
  to have,
  possess;
  a state of mind or habit,
  disposition toward something;
  of physical things,
  a natural property or tendency.
Epictetus says that habits must be 'first weakened and then obliterated' (Discourses 2.18.11b–14);
  otherwise,
  they become fuel for personal destruction (2.18.4–5). See ethos. Hormê (ὁρμή):
  positive impulse or appetite toward an object (as a result of orexis and our assent) that leads to action;
  the opposite of aphormê. These can be irrational impulses to act or a reasoned choice to act or exert effort toward an end. Quoting Epictetus,
  Marcus says that we 'must pay special attention to the sphere of our impulses—that they are subject to reservation ,
  to the common good (κοινωνικαί),
  and that they are in proportion to actual worth ' (11.37). This is the second level of self-coherence that gives rise to our actions (see chart). Marcus repeatedly ties the discipline of hormê to acts for the common good (see also 8.7) and the claims of justice (4.22). It appears thirty-four times in Epictetus's Discourses,
  three times in the Enchiridion,
  and thirty-five times in Marcus. Seneca uses the Latin equivalent impetus seventy-nine times in his letters (see Moral Letters 71.32,
  where he says virtue resides in our judgment,
  which gives rise to impulse and clarifies all appearances that give rise to impulse). Hulê (ὕλη):
  matter,
  material. This is a very common reference in Epictetus,
  appearing more than forty times,
  usually with the analogy of the material that craftspeople use as a way of talking about where our own focus should be,
  and where the evidence of our progress will be seen in the art of living (Discourses 1.15.2). He calls external things the raw material of our prohairesis (1.29.1–4a);
  elsewhere he says,
  'The raw material for the work of a good and excellent person is their own guiding reason (hêgemonikon)' (3.3.1). The term appears nineteen times in Marcus;
  see especially 8.35,
  where he talks about how we can 'convert any obstacle into the raw material for our own purpose.
' Sometimes used interchangeably with ousia. Hypolêpsis (ὑπόληψις):
  literally 'taking up' an opinion,
  assumption,
  conception,
  notion,
  understanding.
Hadot translates the term as 'value judgment' and sees a movement upward into higher-level value judgments,
  from prolêpsis to hypolêpsis to katalêpsis. See Marcus 4.3.4b and 9.13,
  where he talks about how our own assumptions can crush us,
  so we must throw them out. He also says that 'everything turns on our assumptions' (12.
22),
  and we should hold our power for understanding,
  or forming opinions,
  sacred (3.
9).
The term appears eight times in Epictetus's Discourses (see 2.
19.
13–14,
  where he says we hold opinions the opposite of what we should) and three times in the Enchiridion (see 20,
  where he talks about how our own opinions or assumptions are what fuel anger).
Kalos (καλός):
  beautiful;
  in the moral sense,
  noble,
  virtuous.
Seneca's equivalent term,
  used quite frequently,
  is honestum.
Katalêpsis (κατάληψις):
  true comprehension,
  clear perception,
  and firm conviction needed for right conduct.
Hadot translates the term as 'perception' or 'objective representation.
' Thisis a prominent term for Epictetus and stands in contrast to the Skeptic's notion that nothing could be known with certainty (ἀκατάληπτος). Epictetus says that true progress (prokopê) is about giving assent (see synkatathesis) only where there is katalêpsis (Discourses 3.8.4). Marcus uses the term in praising the character of Antoninus and his zeal for 'getting a true grasp of affairs' (6.
30.
2),
  as well as in 4.
22,
  where he says every impulse should be subject to the claims of justice and keeping our convictions clear.
Kathêkon (καθῆκον):
  duty,
  appropriate action on the path to virtue.
Diogenes Laertius says that Zeno was the first philosopher to use the term as relating to conduct in the sense of being incumbent upon an actor (Lives of the Eminent Philosophers,
  'Zeno,
  ' 7.
108).
Marcus says that every duty in life is a sum of acts that deserve methodical attention (6.
26).
Koinos (κοινός):
  common,
  shared in common.
As Haines noted,
  this term and its cognates appear more than eighty times in Marcus,
  and it is a very central part of his thinking and ethical orientation.
Community,
  partnership,
  fellowship,
  neighborliness,
  and cooperation are all heavily emphasized in terms ranging from κοινωνία (5.
16,
  and 'action for the common good in the present moment' in 9.6) to his own coined word κοινονοημοσύνη,
  regard for the feelings of others (1.16). In 6.30,
  Marcus tells us,
  'Life is short—the fruit of this life is a good character and acts for the common good.
' See also his morning ritual to remind ourselves that we've 'been made by nature for the purpose of working with others' (8.
12).
A related common term appearing in both Marcus and Epictetus is the word ἀλλήλων/allêlôn,
  which stresses how we are made 'for each other' or 'for one another' (twenty-six times in Marcus,
  especially 5.
16 and 6.
38;
  and twenty times in Epictetus,
  notably 2.
20).
Kosmos (κόσμος):
  all-encompassing order,
  world,
  universe.
Logos/Logikos (λόγος/λογικός):
  reason or rational;
  the ordering principle of the cosmos.
Logos spermatikos (λόγος σπερματικός) is the generative principle of the universe,
  which creates and takes back all things (see Marcus 6.
24).
Nomos (νόμος):
  law,
  custom.
Oiêsis (οἴησις):
  conceit,
  self-deception,
  illusion,
  arrogant opinion or notion.
Epictetus says (3.
14.
8) that two things must be rooted out of every human being:
  self-deception and mistrust/timidity (apistia).
Our conceit,
  arrogance,
  and false opinions are what must be removed (2.
17.
1),
  along with passion (pathos).
Epictetus sees a movement from preconception (prolêpsis) through conception (hypolêpsis) to our more firmly formed convictions (katalêpsis),
  and all can be subject to error (hamartia).
Heraclitus called self-deception 'an awful disease' (Diogenes Laertius,
  Lives of the Eminent Philosophers,
  9.7),
  and the Stoics offered their practices for overcoming it. Oikeiôsis (οἰκείωσις):
  self-ownership,
  appropriation to the individual's or species' needs. There is only one instance of this noun in Epictetus (Discourses 1.19.15),
  which pertains to selfpreservation,
  although it appears in a discussion of 'the common interest.
' Marcus also has one use,
  and it moves explicitly to the other pole of appropriation—namely,
  to that which lends to the 'care for others' or human fellowship (3.
9),
  and our ruling reason is what enables us to keep in accord with nature and effect such appropriation.
The related verbal and adjectival forms of 'appropriating' and being 'fitting or appropriate' are more common to both.
Orexis (ὄρεξις):
  desire,
  inclination toward a thing.
The opposite of ekklisis.
In Aristotle this was understood as 'appetence' and was something shared with animals and different from purposive choice (prohairesis),
  which involved both reason and deliberation. Epictetus says if we want to be free,
  we shouldn't desire something in someone else's control (Discourses 1.4.18–22). Orexis/ekklisis are the subject of the first of the three topoi,
  or areas of training that produce selfcoherence,
  the other two being hormê/aphormê and synkatathesis (3.2.1–3a). The word appearsfifty-six times in the Discourses and seven times in the Enchiridion. It appears five times in Marcus,
  once in saying principles need to be the source of desire and action (8.1.5) and be limited to only what's in our control (8.7). The verb form,
  ὀρέγω/oregô,
  meaning to reach out for,
  yearn for,
  often appears and in many instances it occurs with 'not missing the mark';
  see hamartanô and apotynchanô.
Ousia (οὐσία):
  substance or being,
  sometimes used interchangeably with hulê (matter,
  material).
Marcus speaks vividly of substance being 'like a river's unending flow,
  its activities constantly changing and causes infinitely shifting so that almost nothing at all stands still' (5.23),
  harkening back to Heraclitus (Lives of the Eminent Philosophers,
  9.8). Paideia (παιδεία):
  training,
  teaching,
  and education. Askeô,
  manthanô,
  and meletaô (see chart) are each a part of getting an education as outlined by Epictetus in Discourses 2.9.13–14. The daily disciplines are central to being educated for the Stoic,
  and only the educated are truly free (2.1.21–23 and 1.22.9–10a). Working over our preconceptions (prolêpsin) is the point of education (1.2.5–7). Pathos (πάθος):
  passion or emotion,
  often excessive and based on false judgments. Haines places passion as the 'affect' following from hormê that lead to acts against nature.
The four passions divide into two types:
  (1) for things not in present possession or anticipated in the future,
  which are desire (ἐπιθυμία) and fear (φόβος);
  and (2) for things presently engaging a person,
  which are pleasure (ἡδονή) and distress (λύπη).
Epictetus states the Stoic position most clearly in Discourses 4.
1.
175:
  'Freedom isn't secured by filling up on your heart's desire but by removing your desire.' Diogenes Laertius says that Zeno defined passion/emotion as an irrational and unnatural movement in the soul,
  or as excessive hormê (Lives of the Eminent Philosophers 7.
110).
Despite the popular misconception,
  the Stoics did celebrate certain passions as good (eupatheia),
  if in rational bounds:
  in particular,
  joy,
  caution,
  and wishing (Lives of the Eminent Philosophers 7.
116).
Phantasia (φαντασία):
  impression,
  appearance,
  perception.
Epictetus says (1.
1.
7–9) that the gods gave us one power that governs all the rest—'the ability to make the right use of appearances.' He also says that the first and greatest task of the philosopher is to test (δοκιμάζω,
  'to assay') and separate appearances (see also 2.18.24). He uses the metaphors of sweeping currents,
  battle,
  and the rigorous training of an athlete for the work we must do to hold our own against impressions (2.18.27–28). 'The task of the good and excellent person is to handle their impressions in harmony with nature' (3.
3.
1).
There are more than two hundred references to phantasia in the Discourses and nine in the Enchiridion (34).
The term appears about forty times in Marcus's Meditations (5.
2,
  5.
16,
  6.
13,
  8.
7,
  8.
26,
  8.
28–29).
Marcus has a great exercise for not telling yourself more than initial impressions ('report' in 8.49). Phronêsis (φρόνησις):
  practical wisdom,
  one of the four cardinal virtues. The term is used repeatedly by Marcus,
  most memorably in 4.37,
  where he says that 'wisdom and acting justly are one and the same,
  ' and in 5.9,
  where he says 'there is nothing so pleasing as wisdom itself.
' See arête. Physis (φύσις):
  nature,
  the natural order;
  of things,
  species,
  or kind:
  characteristic. Both Epictetus and Marcus repeatedly state that we must use our ruling principle to keep ourselves in harmony with nature (Discourses 4.4.43;
  Marcus 3.9). In Stoic thought,
  God and nature are one. Pneuma (πνεῦμα):
  air,
  breath,
  spirit;
  a principle in Stoic physics. The part of the soul set into disturbance by desires and aversions,
  which Haines calls the inferior part of the soul,
  distinct from nous (mind). Epictetus has a memorable image in Discourses 3.3.20–22,
  where he talks about the movement of a disturbed bowl of water being like the spirit in which things exist.Proêgmena (προηγμένα):
  preferred things;
  indifferent in an absolute moral sense,
  but of relative positive value,
  naturally desirable things,
  such as health. Opposite of aproêgmena. Prohairesis (προαίρεσις):
  reasoned or deliberative choice,
  our free will to choose,
  the sphere of choice. The term goes back to Aristotle's Ethics and has been traditionally translated there as 'purposive choice.
' A. A. Long,
  in an attempt to free it from modern moral concepts,
  translates it as 'volition,
  ' a term we find too remote from everyday understanding—for generations prior it was translated as 'moral purpose' (W.
A.
Oldfather,
  George Long,
  and others).
We are avoiding loading the term with either the moral sense of Christian tradition or the modernist sense of will,
  so heavily colored since Schopenhauer and Nietzsche.
A.
A.
Long sees this as Epictetus's preferred term for what distinguishes human beings from animals (which also have hêgemonikon in his reading of Epictetus;
  Epictetus:
  A Stoic and Socratic Guide to Life,
  p.
211),
  something not even the gods can touch (Discourses 1.
1.
23).
The term is used sixty-nine times in the Discourses (1.
4.
18–22,
  1.
18.
21–23,
  1.
22.
10,
  1.
29.
1–4a,
  2.
1.
12–13,
  2.
5.
4–5,
  2.
6.
25,
  2.
10.
1,
  2.
16.
1–2a,
  2.
22.
19–20,
  3.
1.
39b–40a,
  3.
3.
18–19,
  3.
7.
5,
  3.
10.
18,
  3.
19.
2–3,
  3.
21.
1–3,
  3.
22.
13,
  4.
4.
23,
  4.
5.
34– 37) and six times in the Enchiridion (13).
Marcus uses it five times in the negative (ἀπροαίρετα),
  or outside of our choice,
  and three times in the positive sense of deliberate choice (3.
6,
  6.
41,
  8.
56,
  12.
3,
  12.
33).
Where this is the focal point of Epictetus's system,
  Marcus leans heavily to hêgemonikon.
Prokopê (προκοπή):
  progress or improvement;
  on the path toward the virtues of selfcontrol,
  courage,
  justice,
  and wisdom.
See Epictetus,
  Discourses 1.
4,
  captioned 'on progress,
  ' especially 1.
4.
18–22;
  also 3.
19.
2–3.
The word appears fourteen times in Epictetus (most often in 1.
4).
Hanging out with the wrong people can limit our progress,
  according to Epictetus (4.
2.
1–5),
  and Musonius Rufus reminds us of the same (Lectures 11.
53.
21–22;
  losing our soul).
Prolêpsis (πρόληψις):
  a primary conception,
  or preconception,
  possessed by all rational beings.
Epictetus talks about keeping them ready like polished weapons (Discourses 4–5a,
  6b).
See also 1.
22 and 1.
2.
5–7,
  where he talks about working over our preconceptions and the true meaning of education.
Pronoia (πρόνοια):
  foreknowledge,
  foresight,
  divine providence.
Epictetus says we can praise providence if we have two qualities:
  seeing things clearly and gratitude (1.
6.
1–2).
Marcus talks about entrusting the future to providence in 12.
1.
The word appears ten times in Epictetus (see 3.
17.
1) and twelve times in Marcus.
Prosochê (προσοχή):
  attention,
  diligence,
  soberness.
See especially Discourses 4.
12.
1–21.
In 1.
20.
8–11,
  Epictetus says it is particularly needed for things that might steer us wrongly.
Marcus uses the term once in the body of his Meditations in speaking about what a short time we have in life to keep indifferent things from consuming our attention (11.
16;
  not here).
Psychê (ψυχή):
  state of mind,
  soul,
  life,
  living principle.
It appears forty-three times in the Discourses,
  and the laconic Marcus uses it sixty-nine times in his Meditations.
Marcus has a beautiful image of the rational soul as a sphere in 11.
12 (not here);
  Epictetus sees it as a bowl of water in 3.
3.
20–22.
Seneca's term is animus,
  the rational soul.
The Stoics were materialists,
  so the soul itself has substance.
Sophos (σοφός):
  wise person,
  virtuous sage,
  and the ethical ideal of a practicing Stoic.
Sympatheia (συμπάθεια):
  sympathy,
  affinity of parts to the organic whole,
  mutual interdependence.
Synkatathesis (συγκατάθεσις):
  assent;
  approval to impressions,
  conceptions,
  and judgments,
  enabling action to take place.
See Marcus quoting Epictetus in 11.
37 (in verb form) and how it relates to katalêpsis;
  also,
  in 5.
10 Marcus talks about how every assent to impressions is subject to error.
This is the third level of self-coherence,
  concerning the will and judgment and what wechoose to reject (see chart).
It appears eight times in noun form and twenty-one times in verb form in Epictetus:
  3.
2.
1–3a,
  3.
8.
4,
  and 4.
11.
6–7.
Technê (τέχνη):
  craft,
  art in the sense of profession or vocation.
Marcus says our technê is to be a good human being (11.
5).
Epictetus uses the analogies of crafts and trades quite often,
  particularly in drawing focus to the proper material of our work as human beings.
Telos (τέλος):
  the end goal or objective of life.
Theôrêma (θεώρημα):
  general principle or perception,
  a truth of science;
  used interchangeably with dogmata in discussing the mind's store of judgments.
Theos (θεός):
  god;
  the divine,
  creative power that orders the universe and gives human beings their reason and freedom of choice.
As far as theology goes,
  despite reflecting the polytheism of their culture and making references to gods of all stripes,
  the late Stoics were monists and pantheists:
  God = nature.
Further,
  they were materialists,
  so even the divine spark in us—and the soul—are corporeal.
Epictetus was a Phrygian by birth and had a very vivid,
  personalistic view of God.
He referred to God as a kindly father (see particularly Discourses 1.
6,
  3.
24).
A.
A.
Long,
  the foremost scholar of Epictetus,
  put it this way:
  'Whether [Epictetus] speaks of Zeus or God or Nature or the gods,
  he is completely committed to the belief that the world is providentially organized by a divine power whose creative agency reaches its highest manifestation in human beings' (Epictetus:
  A Stoic and Socratic Guide to Life,
  p. 134). Long thinks Epictetus was reviving Cleanthes's (successor to Zeno) strong religious sense. There is no transcendent god for any of the Stoics—a key difference from Christianity. Epictetus says we must seek to bind up our choice with the will of God (Discourses 4.1.89). Marcus tends to refer to the divine in a looser,
  often more polytheistic way (see 9.1.1),
  but he shares Epictetus's views,
  especially when he says,
  'hold sacred your capacity for understanding,
  ' a gift from God requiring obedience to God (3.9). Seneca,
  too,
  speaks often of the divine in plural,
  but all three are agreed that we must accept fate and seek to correct our own faults rather than blame others or the gods (Moral Letters 107.12). Tonos (τόνος):
  tension,
  a principle in Stoic physics accounting for attraction and repulsion;
  a way of seeing what gives rise to virtue and vice in the soul.A A WORD ON THE TRANSLATIONS,
  REFERENCES,
  AND SOURCES ll the translations in this volume were rendered with the aid of two primary and indispensable sources. The first is the incomparable treasure of the Loeb Classical Library (Harvard University Press),
  which has been the standard resource for the original language texts for generations. Today,
  in addition to the handsome green and red printed volumes loved by many,
  the full Greek and Latin texts are now available via online subscription,
  with terrific search capabilities in both languages,
  as well as in English for the general reader,
  at www.loebclassics.com. I have found this service to be a godsend in organizing and managing my work. From a lexical standpoint,
  the resources at www.perseus.tufts.edu have proved to be invaluable,
  offering,
  in addition to search capabilities,
  links to the superlative lexicon of Liddell and Scott (Greek) and the dictionary of Lewis and Short (Latin),
  along with comparative usage statistics and occurrences across authors and time periods. I also used extensively the print editions of both works (Oxford University Press) for particularly challenging passages and for source texts not available online (Musonius Rufus). Of course,
  the translations were informed by the excellent work of Loeb translators W. A. Oldfather,
  C. R. Haines,
  Richard M. Gummere,
  John W. Basore,
  and others. In the case of Epictetus,
  I especially enjoyed consulting the works of Thomas Wentworth Higginson,
  a fellow Harvard divinity graduate,
  and George Long (both available in print and at www.perseus.tufts.edu). There have been quite a few more recent translations of Marcus Aurelius,
  and among them Ryan and I both enjoy the lyrical Gregory Hays (Modern Library);
  for a more literal modernrendering,
  particularly for precision with philosophical terms,
  the Robin Hard translation (Oxford University Press) is hard to beat. With regard to the translations,
  the goal was to make the work of these late Stoic thinkers as accessible,
  digestible,
  and coherent as possible. In the major terms of Stoic thought and its development in Epictetus and Marcus,
  my effort has been placed on consistency and avoiding anachronism while pointing out any places of difference in emphasis or use as necessary. Apart from the core terminology,
  the translations have been made with an aim to remain as literal as possible,
  with only a few liberties taken when needed to make a point stand out or to avoid repeated images or phrases. A special thanks to Amanda C. Gregory for her review of my glossary and translations. All source and line references given,
  unless otherwise noted,
  are to the original texts as found on www.perseus.tufts.edu,
  and most of the remaining ones are to the Loeb texts (online version,
  which occasionally differs from the printed editions in line numbering). The pieces from Musonius Rufus came from an edition of the Greek text in Cora Lutz's 1947 work,
  Musonius Rufus,
  Lectures and Fragments (Yale),
  which I procured from a reprinter in India (but it contains only the Lectures and is missing her introduction,
  the Fragments,
  and much of the textual notes). I have spoken with the director of Yale University Press about possibly bringing that work back into print,
  and it is under review.I SUGGESTIONS FOR FURTHER READING n addition to the Loeb Classics and online resources at www.perseus.tufts.edu and the other printed translations mentioned previously,
  there are a handful of exceptional recent works by accessible scholars that you should read:
  Hadot,
  Pierre. The Inner Citadel:
  The Meditations of Marcus Aurelius,
  translated by Michael Chase (Cambridge,
  MA:
  Harvard University Press,
  2001). ———. What Is Ancient Philosophy? Translated by Michael Chase (Cambridge,
  MA:
  Harvard University Press,
  new edition,
  2004). Long,
  A. A. Epictetus:
  A Stoic and Socratic Guide to Life (New York:
  Oxford University Press,
  2004). ———. Greek Models of Mind and Self (Cambridge,
  MA:
  Harvard University Press,
  2015). Nussbaum,
  Martha. The Therapy of Desire:
  Theory and Practice in Hellenistic Ethics (Princeton,
  NJ:
  Princeton University Press,
  reissued 2009). Robertson,
  Donald. The Philosophy of Cognitive Behavioural Therapy (London:
  Karnac Books,
  2010).What's next on your reading list? Discover your next great read! Get personalized book picks and up-to-date news about this author. Sign up now.
#+end_verse