#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 2nd DON’T MIND ME, I’M ONLY DYING SLOW
#+begin_verse
'Let each thing you would do,
  say or intend be like that of a dying person.' —MARCUS AURELIUS,
  MEDITATIONS,
  2.
11.
1 ave you ever heard some ask:
  'What would you do if you found out tomorrow that you had cancer?' The question is designed to make you consider how different life might be if you were suddenly given just a few months or weeks to live.
There's nothing like a terminal illness to wake people up.
But here's the thing:
  you already have a terminal diagnosis.
We all do!
As the writer Edmund Wilson put it,
  'Death is one prophecy that never fails.' Every person is born with a death sentence.
Each second that passes by is one you'll never get back.
Once you realize this,
  it will have a profound impact on what you do,
  say,
  and think.
Don't let another day tick away in ignorance of the reality that you're a dying person.
We all are.
Can today be the day we stop pretending otherwise?
P
#+end_verse