#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 7th THE CARDS WE’RE DEALT
#+begin_verse
'Think of the life you have lived until now as over and,
  as a dead man,
  see what's left as a bonus and live it according to Nature. Love the hand that fate deals you and play it as your own,
  for what could be more fitting?' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
56–57 e have an irrational fear of acknowledging our own mortality.
We avoid thinking about it because we think it will be depressing.
In fact,
  reflecting on mortality often has the opposite effect—invigorating us more than saddening us.
Why?
Because it gives us clarity.
If you were suddenly told you had but a week to live,
  what changes would you make?
If you died but were resuscitated,
  how different would your perspective be?
When,
  as Shakespeare's Prospero puts it,
  'every third thought shall be my grave,
  ' there's no risk of getting caught up in petty matters or distractions.
Instead of denying our fear of death,
  let's let it make us the best people we can be.
Today.
W
#+end_verse