#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 5th THE BENEFITS OF SOBERING THOUGHTS
#+begin_verse
'Keep death and exile before your eyes each day,
  along with everything that seems terrible—by doing so,
  you'll never have a base thought nor will you have excessive desire.' —EPICTETUS,
  ENCHIRIDION,
  21 olitical winds could change in an instant,
  depriving you of the most basic freedoms you take for granted.
Or,
  no matter who you are or how safely you've lived your life,
  there's someone out there who would rob and kill you for a couple dollars.
As it's written in the timeless Epic of Gilgamesh:
  'Man is snapped off like a reed in the canebrake! The comely young man,
  the pretty young woman— All too soon in their prime Death abducts them!' Death is not the only unexpected interruption we might face—our plans can be dashed to pieces by a million things.
Today might be a bit more pleasant if you ignore those possibilities,
  but at what cost?
T
#+end_verse