#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 3rd THE PHILOSOPHER AS AN ARTISAN OF LIFE AND DEATH
#+begin_verse
'Philosophy does not claim to get a person any external possession. To do so would be beyond its field. As wood is to the carpenter,
  bronze to the sculptor,
  so our own lives are the proper material in the art of living.' —EPICTETUS,
  DISCOURSES,
  1.
15.
2 hilosophy is not some idle pursuit appropriate only for academics or the rich.
Instead,
  it is one of the most essential activities that a human being can engage in.
Its purpose,
  as Henry David Thoreau said a few thousand years after Epictetus,
  is to help us 'solve the problems of life,
  not only theoretically but practically.' This aligns nicely with Cicero's famous line:
  'To philosophize is to learn how to die.' You're not reading these quotes and doing these thought exercises for fun.
Though they may be enjoyable and help you lighten up,
  their aim is to help you sculpt and improve your life.
And because all of us have but one life and one death,
  we should treat each experience like a sculptor with his chisels,
  carving until,
  to paraphrase Michelangelo,
  we set free the angel in the marble.
We are trying to do this difficult thing—living and dying—as well as we can.
And to do that,
  we must remember what we've learned and the wise words we've been given.
T
#+end_verse