#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 17th KNOW THYSELF—BEFORE IT’S TOO LATE
#+begin_verse
'Death lies heavy upon one who,
  known exceedingly well by all,
  dies unknown to himself.' —SENECA,
  THYESTES,
  400 ome of the most powerful and important people in the world seem to have almost no self-awareness.
Although total strangers know endless amounts of trivia about them,
  celebrities—because they are too busy or because it hurts too much—appear to know very little about themselves.
We can be guilty of the same sin.
We ignore Socrates's dictum to 'know thyself'—often realizing we have done so at our peril,
  years later,
  when we wake up one day and realize how rarely we have asked ourselves questions like:
  Who am I? What's important to me? What do I like? What do I need? Now—right now—you have the time to explore yourself,
  to understand your own mind and body. Don't wait. Know yourself. Before it's impossibly late.I
#+end_verse