#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 10th DON’T SELL YOURSELF TOO CHEAPLY
#+begin_verse
'I say,
  let no one rob me of a single day who isn't going to make a full return on the loss.' —SENECA,
  ON TRANQUILITY OF MIND,
  1.
11b eople spend a lot more money when they use credit cards than when they have to pull out actual cash.
If you ever wondered why credit card companies and banks push cards so aggressively,
  this is why.
The more credit cards you have,
  the more you'll spend.
Do we treat the days of our lives like we treat our money?
Because we don't exactly know how many days we'll be alive,
  and because we try our hardest not to think about the fact that someday we'll die,
  we're pretty liberal with how freely we spend our time.
We let people and obligations impose on that time,
  only rarely asking:
  What am I getting in return here?
Seneca's maxim is the equivalent of cutting up your credit cards and switching to cash.
He says to put real thought into every transaction:
  Am I getting my money's worth here?
Is this a fair trade?
L
#+end_verse