#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 23rd WHAT ARE YOU SO AFRAID OF LOSING
#+begin_verse
'You are afraid of dying. But,
  come now,
  how is this life of yours anything but death?' —SENECA,
  MORAL LETTERS,
  77.
18 eneca tells an amazing story about an obscenely wealthy Roman who was carried around by slaves on a litter.
On one occasion,
  after being lifted out of a bath,
  the Roman asked,
  'Am I sitting down yet?' Seneca's point was essentially:
  What kind of sad pathetic life is it if you're so disconnected from the world that you don't even know whether you're on the ground?
How did the man know whether he was even alive at all?
Most of us are afraid of dying.
But sometimes this fear begs the question:
  To protect what exactly?
For a lot of people the answer is:
  hours of television,
  gossiping,
  gorging,
  wasting potential,
  reporting to a boring job,
  and on and on and on.
Except,
  in the strictest sense,
  is this actually a life?
Is this worth gripping so tightly and being afraid of losing?
It doesn't sound like it.
H
#+end_verse