#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 8th DON’T HIDE FROM YOUR FEELINGS
#+begin_verse
'It's better to conquer grief than to deceive it.' —SENECA,
  ON CONSOLATION TO HELVIA,
  17.
1b e've all lost people we were close to—a friend,
  a colleague,
  a parent,
  a grandparent.
While we were suffering from our grief,
  some well-meaning person did their best to take our mind off it or make us think about something else for a couple hours.
However kind,
  these gestures are misguided.
The Stoics are stereotyped as suppressing their emotions,
  but their philosophy was actually intended to teach us to face,
  process,
  and deal with emotions immediately instead of running from them.
Tempting as it is to deceive yourself or hide from a powerful emotion like grief—by telling yourself and other people that you're fine—awareness and understanding are better.
Distraction might be pleasant in the short term —by going to gladiatorial games,
  as a Roman might have done,
  for example.
Focusing is better in the long term.
That means facing it now.
Process and parse what you are feeling.
Remove your expectations,
  your entitlements,
  your sense of having been wronged.
Find the positive in the situation,
  but also sit with your pain and accept it,
  remembering that it is a part of life.
That's how one conquers grief.
T
#+end_verse