#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 15th A SIMPLE WAY TO MEASURE OUR DAYS
#+begin_verse
'This is the mark of perfection of character—to spend each day as if it were your last,
  without frenzy,
  laziness,
  or any pretending.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
69 he Stoics didn't think that anyone could be perfect.
The idea of becoming a sage—the highest aspiration of a philosopher—wasn't realistic.
This was just their Platonic ideal.
Still,
  they started every day hoping to get a little closer to that mark.
There was much to gain in the trying.
Can you actually live today like it is your last day?
Is it even possible to embody completeness or perfection in our ethos (character),
  effortlessly doing the right thing for a full twenty-four hours?
Is it possible for more than a minute?
Maybe not.
But if trying was enough for the Stoics,
  it should be enough for us too.
A
#+end_verse