#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 21st WHAT DO YOU HAVE TO SHOW FOR YOUR YEARS
#+begin_verse
'Many times an old man has no other evidence besides his age to prove he has lived a long time.' —SENECA,
  ON TRANQUILITY OF MIND,
  3.
8b ow long have you been alive?
Take the years,
  multiply them by 365,
  and then by 24.
How many hours have you lived?
What do you have to show for all of them?
The answer for many people is:
  not enough.
We had so many hours that we took them for granted.
All we have to show for our time on this planet are rounds of golf,
  years spent at the office,
  time spent watching mediocre movies,
  a stack of mindless books we hardly remember reading,
  and maybe a garage full of toys.
We're like the character in Raymond Chandler's The Long Goodbye:
  'Mostly,
  I just kill time,
  ' he says,
  'and it dies hard.' One day,
  our hours will begin to run out.
It would be nice to be able to say:
  'Hey,
  I really made the most of it.' Not in the form of achievements,
  not money,
  not status—you know what the Stoics think of all that—but in wisdom,
  insight,
  and real progress in the things that all humans struggle against.
What if you could say that you really made something of this time that you had?
What if you could prove that you really did live [insert number] years?
And not just lived them,
  but lived them fully?
M
#+end_verse