#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* December 22nd STAKE YOUR OWN CLAIM
#+begin_verse
'For it's disgraceful for an old person,
  or one in sight of old age,
  to have only the knowledge carried in their notebooks. Zeno said this . . . what do you say? Cleanthes said that . . . what do you say? How long will you be compelled by the claims of another? Take charge and stake your own claim—something posterity will carry in its notebook.' —SENECA,
  MORAL LETTERS,
  33.
7 using in his notebook about the topic of immortality,
  Ralph Waldo Emerson complained how writers dance around a difficult topic by relying on quotes.
'I hate quotation,
  ' he wrote.
'Tell me what you know.' Seneca was throwing down the same gauntlet some twenty centuries before.
It's easier to quote,
  to rely on the wise words of others.
Especially when the people you're deferring to are such towering figures!
It's harder (and more intimidating) to venture out on your own and express your own thoughts.
But how do you think those wise and true quotes from those towering figures were created in the first place?
Your own experiences have value.
You have accumulated your own wisdom too.
Stake your claim.
Put something down for the ages—in words and also in example.
S
#+end_verse