#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 20th BEHOLD, NOW AS EVER
#+begin_verse
'If you've seen the present,
  you've seen all things,
  from time immemorial into all of eternity. For everything that happens is related and the same.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
37 he events that will transpire today are the same as the things that have always occurred.
People living and dying,
  animals living and dying,
  clouds rolling in and rolling out,
  air sucked in and sucked out,
  as it has for aeons.
This moment right now,
  to paraphrase Emerson,
  is a quotation of the moments that have come before and will come ever after.
This idea is expressed nowhere more beautifully than in the Christianity hymn Gloria Patri.
'As it was in the beginning,
  and now,
  and always,
  and to the ages of ages.' This thought is not supposed to be depressing or uplifting.
It's just a fact.
However,
  it can have a calming,
  centering effect.
No need to get excited,
  no need to wait on pins and needles.
If you haven't seen this before,
  someone else has.
That can be a relief.
P
#+end_verse