#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 19th MAXIMS FROM THREE WISE MEN
#+begin_verse
'For any challenge we should hold three thoughts at our command:
  'Lead on God and Destiny,
  To that Goal fixed for me long ago.
I will follow and not stumble;
  even if my will is weak I will soldier on.
'' —CLEANTHES 'Whoever embraces necessity count as wise,
  skilled in divine matters.' —EURIPIDES 'If it pleases the gods,
  so be it. They may well kill me,
  but they can't hurt me.' —PLATO'S CRITO AND APOLOGY —EPICTETUS,
  ENCHIRIDION,
  53 hese three quotes compiled by Epictetus show us—in wisdom across history—the themes of tolerance,
  flexibility,
  and,
  ultimately,
  acceptance.
Cleanthes and Euripides evoke destiny and fate as concepts that help ease acceptance.
When one has a belief in a greater or higher power (be it God or gods),
  then there is no such thing as an event going contrary to plan.
Even if you don't believe in a deity,
  you can take some comfort in the various laws of the universe or even the circle of life.
What happens to us as individuals can seem random or upsetting or cruel or inexplicable,
  when in fact these events make perfect sense when our perspective is zoomed out,
  even just slightly.
Let's practice this perspective today.
Pretend that each event— whether desired or unexpected—was willed to happen,
  willedspecifically for you.
You wouldn't fight that,
  would you?
T
#+end_verse