#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 28th IT’S NOT ON THEM, IT’S ON YOU
#+begin_verse
'If someone is slipping up,
  kindly correct them and point out what they missed. But if you can't,
  blame yourself—or no one.' —MARCUS AURELIUS,
  MEDITATIONS,
  10.
4 good teacher knows that when a student is failing,
  the blame falls on the instructor,
  not the pupil.
How much more generous and tolerant would we be if we could extend this understanding to other spheres in our life?
To be able to see that if a friend is unreliable,
  maybe it's because they don't know what's wrong or because we haven't tried to help them fix their flaw.
If an employee is underperforming,
  just talk to them or figure out if they're lacking in support.
If someone is being annoying,
  try talking to them about the problem with their behavior,
  or ask yourself:
  Why am I being so sensitive?
And if this doesn't work,
  try letting it go.
It might be an isolated incident anyway.
T
#+end_verse