#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 23rd ATTACHMENTS ARE THE ENEMY
#+begin_verse
'In short,
  you must remember this—that if you hold anything dear outside of your own reasoned choice,
  you will have destroyed your capacity for choice.' —EPICTETUS,
  DISCOURSES,
  4.
4.
23 ccording to Anthony de Mello,
  'there is one thing and only one thing that causes unhappiness. The name of that thing is Attachment.' Attachments to an image you have of a person,
  attachments to wealth and status,
  attachments to a certain place or time,
  attachments to a job or to a lifestyle.
All of those things are dangerous for one reason:
  they are outside of our reasoned choice.
How long we keep them is not in our control.
As Epictetus realized some two thousand years before de Mello,
  our attachments are what make it so hard to accept change.
Once we have them,
  we don't want to let go.
We become slaves to maintaining the status quo.
We are like the Red Queen in Alice in Wonderland—running faster and faster to stay in the same place.
But everything is in a constant state of change.
We have certain things for a while and then lose them.
The only permanent thing is prohairesis,
  our capacity for reasoned choice.
The things we are attached to can come and go,
  our choice is resilient and adaptable.
The sooner we become aware of this the better.
The easier it will be to accept and adapt to what does happen.
A
#+end_verse