#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 1st ACCEPTING WHAT IS
#+begin_verse
'Don't seek for everything to happen as you wish it would,
  but rather wish that everything happens as it actually will—then your life will flow well.' —EPICTETUS,
  ENCHIRIDION,
  8 'It is easy to praise providence for anything that may happen if you have two qualities:
  a complete view of what has actually happened in each instance and a sense of gratitude. Without gratitude what is the point of seeing,
  and without seeing what is the object of gratitude?' —EPICTETUS,
  DISCOURSES,
  1.
6.
1–2 omething happened that we wish had not.
Which of these is easiest to change:
  our opinion or the event that is past?
The answer is obvious.
Accept what happened and change your wish that it had not happened.
Stoicism calls this the 'art of acquiescence'— to accept rather than fight every little thing. And the most practiced Stoics take it a step further. Instead of simply accepting what happens,
  they urge us to actually enjoy what has happened—whatever it is. Nietzsche,
  many centuries later,
  coined the perfect expression to capture this idea:
  amor fati (a love of fate). It's not just accepting,
  it's loving everything that happens. To wish for what has happened to happen is a clever way to avoid disappointment because nothing is contrary to your desires. But to actually feel gratitude for what happens? To love it? That's a recipe for happiness and joy.W
#+end_verse