#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 6th SOMEONE ELSE IS SPINNING THE THREAD
#+begin_verse
'If the breaking day sees someone proud,
  The ending day sees them brought low. No one should put too much trust in triumph,
  No one should give up hope of trials improving. Clotho mixes one with the other and stops Fortune from resting,
  spinning every fate around. No one has had so much divine favor That they could guarantee themselves tomorrow. God keeps our lives hurtling on,
  Spinning in a whirlwind.' —SENECA,
  THYESTES,
  613 he novelist Cormac McCarthy was living in a motel room when he heard a knock at the door.
It was a messenger—he'd been awarded the MacArthur 'genius' grant and $250,
  000. Unexpected events can be good as well as bad. Who could dream of such an unexpected twist? Who but Clotho,
  one of the three Greek goddesses of fate,
  who 'spins' the thread of human life?
To the ancients,
  she was the one who decided the course of the events of our lives—some good,
  some bad.
As the playwright Aeschylus wrote,
  'When the gods send evil,
  one cannot escape it.' The same was true for great destiny and good fortune.
Their resigned attitude might seem strange to us today,
  but they understood who was really in control (not them,
  not us!
).
No amount of prosperity,
  no amount of difficulty,
  is certain or forever.
A triumph becomes a trial,
  a trial becomes a triumph.
Life can change in an instant.
Remember,
  today,
  how often it does.
I
#+end_verse