#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 24th TRAIN TO LET GO OF WHAT’S NOT YOURS
#+begin_verse
'Whenever you experience the pangs of losing something,
  don't treat it like a part of yourself but as a breakable glass,
  so when it falls you will remember that and won't be troubled. So too,
  whenever you kiss your child,
  sibling,
  or friend,
  don't layer on top of the experience all the things you might wish,
  but hold them back and stop them,
  just as those who ride behind triumphant generals remind them they are mortal. In the same way,
  remind yourself that your precious one isn't one of your possessions,
  but something given for now,
  not forever . . .' —EPICTETUS,
  DISCOURSES,
  3.
24.
84–86a t a Roman triumph,
  the majority of the public would have their eyes glued to the victorious general at the front—one of the most coveted spots during Roman times.
Only a few would notice the aide in the back,
  right behind the commander,
  whispering into his ear,
  'Remember,
  thou art mortal.' What a reminder to hear at the peak of glory and victory!
In our own lives,
  we can train to be that whisper.
When there is something we prize—or someone that we love—we can whisper to ourselves that it is fragile,
  mortal,
  and not truly ours.
No matter how strong or invincible something feels,
  it never is.
We must remind ourselves that it can break,
  can die,
  can leave us.
Loss is one of our deepest fears.
Ignorance and pretending don't make things any better.
They just mean the loss will be all the more jarring when it occurs.
S
#+end_verse