#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 18th FOUR HABITS OF THE STOIC MIND
#+begin_verse
'Our rational nature moves freely forward in its impressions when it:
  1) accepts nothing false or uncertain;
  2) directs its impulses only to acts for the common good;
  3) limits its desires and aversions only to what's in its own power;
  4) embraces everything nature assigns it.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
7 f you notice,
  Marcus repeatedly reminds himself what Stoicism is.
These bullet points are helpful to those of us reading thousands of years later,
  but really they were intended to be helpful to him.
Maybe that day he had accepted a bad impression or had acted selfishly.
Maybe he had pinned his hopes on something outside his control or complained and fought against something that had happened.
Or maybe it had just been awhile since he'd thought about these things and wanted a reminder.
Whatever his case was,
  or whatever ours is today,
  let's align our minds along these four critical habits:
  1.
Accept only what is true.
2.
Work for the common good.
3.
Match our needs and wants with what is in our control.
4.
Embrace what nature has in store for us.
T
#+end_verse