#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 26th THE ALTAR OF NO DIFFERENCE
#+begin_verse
'We are like many pellets of incense falling on the same altar. Some collapse sooner,
  others later,
  but it makes no difference.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
15 hat's the difference between you and the richest person in the world?
One has a little more money than the other.
What's the difference between you and the oldest person in the world?
One has been around a little longer than the other.
Same goes for the tallest,
  smartest,
  fastest,
  and on down the line.
Measuring ourselves against other people makes acceptance difficult,
  because we want what they have,
  or we want how things could have gone,
  not what we happen to have.
But that makes no difference.
Some might see this line from Marcus as pessimistic,
  whereas others see it as optimistic.
It's really just truth.
We're all here and we're all going to leave this earth eventually,
  so let's not concern ourselves with petty differences in the meantime.
We have too much to do.
T
#+end_verse