#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 13th NEVER COMPLAIN, NEVER EXPLAIN
#+begin_verse
'Don't allow yourself to be heard any longer griping about public life,
  not even with your own ears!' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
9 ot only do even the most fortunate of us complain,
  it often seems like the more fortunate we are,
  the more time we have to do so.
Marcus Aurelius was a reluctant chief executive—just as you might be a reluctant accountant,
  kid's soccer coach,
  or lawyer.
Or perhaps you generally like your job,
  but you could do without a few of its attendant responsibilities.
Where does that thinking get you?
Nowhere,
  other than in a negative state of mind.
It calls to mind a motto of British prime minister Benjamin Disraeli:
  'Never complain,
  never explain.' He said this because,
  like Marcus,
  he knew that the burdens of responsibility were immense.
It's so easy to complain about this or that,
  or to try to make excuses and justifications for the things you've done.
But that doesn't accomplish anything—and it never lightens the load.
T
#+end_verse