#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 30th FOLLOW THE LOGOS
#+begin_verse
'The person who follows reason in all things will have both leisure and a readiness to act—they are at once both cheerful and self-composed.' —MARCUS AURELIUS,
  MEDITATIONS,
  10.
12b he guiding reason of the world—the Stoics called this the logos— works in mysterious ways.
Sometimes,
  the logos gives us what we want,
  other times it gives us precisely what we do not want.
In either case,
  they believed that the logos was an all-powerful force that governed the universe.
There is a helpful analogy to explain the logos:
  We are like a dog leashed to a moving cart.
The direction of the cart will determine where we go.
Depending on the length of the leash,
  we also have a fair amount of room to explore and determine the pace,
  but ultimately what each of us must choose is whether we will go willingly or be painfully dragged.
Which will it be?
Cheerful acceptance?
Or ignorant refusal?
In the end,
  they amount to the same.
DECEMBER MEDITATION ON MORTALITY'L
#+end_verse