#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 9th ALL IS FLUID
#+begin_verse
'The universe is change. Life is opinion.' —MARCUS AURELIUS,
  MEDITATIONS,
  4.
3.
4b n Plutarch's Life of Theseus,
  he describes how the ship of Theseus,
  an Athenian hero,
  was preserved by the people of Athens in battle-ready condition for many centuries.
Each time a board decayed,
  it would be replaced until eventually every stick of wood in it had been replaced.
Plutarch asks:
  Is it still the ship of Theseus,
  or is it a new one?
In Japan,
  a famous Shinto shrine is rebuilt every twenty-three years.
It's gone through more than sixty of those cycles.
Is it one shrine,
  1,
  400 years old?
Or sixty consecutive shrines?
Even the U.
S.
Senate,
  given its staggered elections,
  could be said to have never been fully turned over.
Is it the same body formed in the days of George Washington?
Our understanding of what something is is just a snapshot—an ephemeral opinion.
The universe is in a constant state of change.
Our nails grow and are cut and keep growing.
New skin replaces dead skin.
Old memories are replaced by new memories.
Are we still the same people?
Are the people around us the same?
Nothing is exempt from this fluidity,
  not even the things we hold most sacred.
E
#+end_verse