#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 11th IT’S NOT THE THING, IT’S WHAT WE MAKE OF IT
#+begin_verse
'When you are distressed by an external thing,
  it's not the thing itself that troubles you,
  but only your judgment of it. And you can wipe this out at a moment's notice.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
47 magine you've dreamed of a life in politics.
You're young,
  you're vigorous,
  and you've held increasingly powerful positions over the course of your career.
Then at thirty-nine,
  you start to feel run down.
Your doctors tell you that you have polio and your life will never be the same.
Your career is over—right?
This is the story of Franklin Delano Roosevelt,
  now widely regarded as one of America's greatest political leaders.
He was,
  at middle age,
  diagnosed with polio after spending years preparing for and dreaming about the presidency.
It's impossible to understand FDR without understanding this disability.
The 'external thing' was that he was crippled—this was a literal fact—but his judgment of it was that it did not cripple his career or his personhood. Though he was certainly the victim of a then incurable disease,
  he wiped away—almost immediately—the victim's mentality. Let's not confuse acceptance with passivity.A
#+end_verse