#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* November 12th THE STRONG ACCEPT RESPONSIBILITY
#+begin_verse
'If we judge as good and evil only the things in the power of our own choice,
  then there is no room left for blaming gods or being hostile to others.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
41 sign on President Harry Truman's desk read,
  THE BUCK STOPS HERE.
As president,
  with more power and control than pretty much anyone else,
  he knew that,
  good or bad,
  there wasn't anyone he could blame for stuff other than himself.
There was no one to pass the buck to.
The chain ended there,
  in the Oval Office.
As the president of our own lives—and knowing that our powers begin and end with our reasoned choice—we would do well to internalize this same attitude.
We don't control things outside that sphere,
  but we do control our attitudes and our responses to those events —and that's plenty.
It's enough that we go into each and every day knowing that there is no one to pass the buck to.
It ends with us.
N
#+end_verse