#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 30th WHO GETS THE LION’S SHARE
#+begin_verse
'Aren't you ashamed to reserve for yourself only the remnants of your life and to dedicate to wisdom only that time can't be directed to business?' —SENECA,
  ON THE BREVITY OF LIFE,
  3.
5b n one of his letters,
  Seneca tells a story about Alexander the Great.
Apparently as Alexander was conquering the world,
  certain countries would offer him pieces of their territory in hopes that he'd leave them alone in exchange.
Alexander would tell them,
  writes Seneca,
  that he hadn't come all the way to Asia to accept whatever they would give him,
  but instead they were going to have to accept whatever he chose to leave them.
According to Seneca,
  we should treat philosophy the same way in our lives.
Philosophy shouldn't have to accept what time or energy is left over from other occupations but instead we should graciously make time for those other pursuits only once our study is finished.
If real self-improvement is what we're after,
  why do we leave our reading until those few minutes before we shut off the lights and go to bed?
Why do we block off eight to ten hours in the middle of the day to be at the office or to go to meetings but block out no time for thinking about the big questions?
The average person somehow manages to squeeze in twenty-eight hours of television per week—but ask them if they had time to study philosophy,
  and they will probably tell you they're too busy.
T
#+end_verse