#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 7th A SELFISH REASON TO BE GOOD
#+begin_verse
'The person who does wrong,
  does wrong to themselves. The unjust person is unjust to themselves—making themselves evil.' —MARCUS AURELIUS,
  MEDITATIONS,
  9.
4 he next time you do something wrong,
  try to remember how it made you feel.
Rarely does one say,
  'I felt great!' There is a reason there's often vomit at crime scenes.
Instead of the catharsis the person thought they'd feel when they let themselves get out of control or when they got their revenge,
  they ended up making themselves sick.
We feel a version of this when we lie,
  when we cheat,
  when we screw someone over.
So in that split second before your ill-gotten gains kick in,
  ask:
  How do I feel about myself?
Is that moment when fear rises in your throat because you suspect you may get caught really worth it?
Self-awareness and wrongdoing rarely go together.
If you need a selfish reason to not do wrong—put yourself in touch with these feelings.
They're a powerful disincentive.
N
#+end_verse