#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 6th LOOKING OUT FOR EACH OTHER
#+begin_verse
'It's in keeping with Nature to show our friends affection and to celebrate their advancement,
  as if it were our very own. For if we don't do this,
  virtue,
  which is strengthened only by exercising our perceptions,
  will no longer endure in us.' —SENECA,
  MORAL LETTERS,
  109.
15 atching other people succeed is one of the toughest things to do— especially if we are not doing well ourselves.
In our huntergatherer minds,
  we suspect that life is a zero-sum game—that for someone to have more means that we might end up with less.
But like all parts of philosophy,
  empathy and selflessness are a matter of practice.
As Seneca observed,
  it's possible to learn to 'rejoice in all their successes and be moved by their every failure.' This is what a virtuous person does.
They teach themselves to actively cheer for other people—even in cases where that might come at their own expense—and to put aside jealousy and possessiveness.
You can do that too.
T
#+end_verse