#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 22nd IT’S EASY TO GET BETTER. BUT BETTER AT WHAT
#+begin_verse
'So someone's good at taking down an opponent,
  but that doesn't make them more community-minded,
  or modest,
  or well-prepared for any circumstance,
  or more tolerant of the faults of others.' —MARCUS AURELIUS,
  MEDITATIONS,
  7.
52 elf-improvement is a noble pursuit.
Most people don't even bother.
But among those who do,
  it's possible for vanity and superficiality to corrupt this process.
Do you want six-pack abs because you are challenging yourself and committing to a difficult goal?
Or is it because you want to impress people with your shirt off?
Are you running that marathon because you want to test your limits or because you're running away from your problems at home?
Our will shouldn't be directed at becoming the person who is in perfect shape or who can speak multiple languages but who doesn't have a second for other people.
What's the point of winning at sports but losing in the effort to be a good husband,
  wife,
  father,
  mother,
  son,
  or daughter?
Let's not confuse getting better at stuff with being a better person.
One is a much bigger priority than the other.
I
#+end_verse