#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 29th CHARACTER IS FATE
#+begin_verse
'Each person acquires their own character,
  but their official roles are designated by chance. You should invite some to your table because they are deserving,
  others because they may come to deserve it.' —SENECA,
  MORAL LETTERS,
  47.
15b n the hiring process,
  most employers look at where someone went to school,
  what jobs they've held in the past.
This is because past success can be an indicator of future successes.
But is it always?
There are plenty of people who were successful because of luck.
Maybe they got into Oxford or Harvard because of their parents.
And what about a young person who hasn't had time to build a track record?
Are they worthless?
Of course not.
This is why character is a far better measure of a man or woman.
Not just for jobs,
  but for friendships,
  relationships,
  for everything.
Heraclitus put it as a maxim:
  'Character is fate.' When you seek to advance your own position in life,
  character is the best lever—perhaps not in the short term,
  but certainly over the long term.
And the same goes for the people you invite into your life.
I
#+end_verse