#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 11th HONESTY AS OUR DEFAULT
#+begin_verse
'How rotten and fraudulent when people say they intend to 'give it to you straight.
' What are you up to,
  dear friend? It shouldn't need your announcement,
  but be readily seen,
  as if written on your forehead,
  heard in the ring of your voice,
  a flash in your eyes—just as the beloved sees it all in the lover's glance. In short,
  the straightforward and good person should be like a smelly goat—you know when they are in the room with you.' —MARCUS AURELIUS,
  MEDITATIONS,
  11.
15 ll of us have used phrases like that before.
'I'm going to be straightforward with you here . . .' 'I'll be honest . . .' 'No disrespect but . . .' Empty expressions or not,
  they prompt the question:
  If you have to preface your remarks with indicators of honesty or directness,
  what does that say about everything else you say?
If you say you're being honest now,
  does that mean you usually aren't?
What if,
  instead,
  you cultivated a life and a reputation in which honesty was as bankable as a note from the U.
S.
Treasury,
  as emphatic and explicit as a contract,
  as permanent as a tattoo?
Not only would it save you from needing to use the reassurances that other,
  less scrupulous people must engage in,
  it will make you a better person.
I
#+end_verse