#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 8th A HIGHER PLEASURE
#+begin_verse
'Yes,
  getting your wish would have been so nice. But isn't that exactly why pleasure trips us up? Instead,
  see if these things might be even nicer—a great soul,
  freedom,
  honesty,
  kindness,
  saintliness. For there is nothing so pleasing as wisdom itself,
  when you consider how sure-footed and effortless the works of understanding and knowledge are.' —MARCUS AURELIUS,
  MEDITATIONS,
  5.
9 obody can argue that pleasure doesn't feel good.
That's pretty much what it does by definition.
But today Marcus Aurelius is reminding you—just as he reminded himself—that those pleasures hardly stand up to virtue.
The dopamine rush that comes from sex is momentary.
So is the pride of an accomplishment or the hearty applause of a crowd.
These pleasures are powerful,
  but they wear off and leave us wanting more.
What lasts longer (and remains more within our circle of control)?
Wisdom,
  good character,
  sobriety,
  and kindness.
W
#+end_verse