#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 31st YOU WERE BORN GOOD
#+begin_verse
'The human being is born with an inclination toward virtue.' —MUSONIUS RUFUS,
  LECTURES,
  2.
7.
1–2 he notion of original sin has weighed down humankind for centuries.
In reality,
  we're made to help each other and be good to each other.
We wouldn't have survived as a species otherwise.
There is hardly an idea in Stoic philosophy that wouldn't be immediately agreeable to a child or that doesn't jibe with common sense.
The ideas within it go to the core of who we are and what we know to be true.
The only things they conflict with are the various inventions of society—which usually serve some selfish interest more than they benefit the common good.
You were born good.
'All of us have been made by nature,
  ' Rufus said,
  'so that we can live free from error and nobly—not that one can and another can't,
  but all.' You were born with an attraction to virtue and self-mastery.
If you've gotten far from that,
  it's not out of some inborn corruption but from a nurturing of the wrong things and the wrong ideas.
As Seneca has pointed out,
  philosophy is a tool to strip it all away—to get back to our true nature.
NOVEMBER ACCEPTANCE / AMOR FATIS
#+end_verse