#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 20th MARKS OF THE GOOD LIFE
#+begin_verse
'You have proof in the extent of your wanderings that you never found the art of living anywhere—not in logic,
  nor in wealth,
  fame,
  or in any indulgence. Nowhere. Where is it then? In doing what human nature demands. How is a person to do this? By having principles be the source of desire and action. What principles? Those to do with good and evil,
  indeed in the belief that there is no good for a human being except what creates justice,
  self-control,
  courage and freedom,
  and nothing evil except what destroys these things.' —MARCUS AURELIUS,
  MEDITATIONS,
  8.
1.
(5) hat's the meaning of life?
Why was I born?
Most of us struggle with these questions—sometimes when we're young,
  sometimes not until we're older.
Rarely do we find much in the way of direction.
But that's simply because we miss the point.
As Viktor Frankl points out in Man's Search for Meaning,
  it is not our question to ask.
Instead,
  it is we who are being asked the question.
It's our lives that are the answer.
No amount of travel or reading or clever sages can tell you what you want to know.
Instead,
  it is you who must find the answer in your actions,
  in living the good life—by embodying the self-evident principles of justice,
  self-control,
  courage,
  freedom,
  and abstaining from evil.
A
#+end_verse