#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 4th ALL FOR ONE, ONE FOR ALL
#+begin_verse
'That which isn't good for the hive,
  isn't good for the bee.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
54 nherent in the Stoic concept of sympatheia is the notion of an interconnected cosmos in which everything in the universe is part of a larger whole.
Marcus Aurelius was one of the first writers to articulate the notion of cosmopolitanism—saying that he was a citizen of the world,
  not just of Rome.
The idea that you're a bee in the hive is a reminder of this perspective.
Marcus even states the reverse of that idea later in his Meditations,
  just so he doesn't forget:
  'That which doesn't harm the community can't harm the individual.' Just because something is bad for you doesn't mean it's bad for everyone.
Just because something is good for you definitely doesn't mean it's good for everyone.
Think of the hedge fund managers who bet massively against the economy—they profited by rooting for essentially everyone and everything else to fail.
Is that who you want to be?
A good Stoic understands that proper impulses,
  and the right actions that arise from them,
  naturally carry the good of the whole,
  which is the wise person's only good.
Conversely,
  good and wise actions by the whole are what's good for the individual.
Y
#+end_verse