#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 23rd SHOW THE QUALITIES YOU WERE MADE FOR
#+begin_verse
'People aren't in awe of your sharp mind? So be it. But you have many other qualities you can't claim to have been deprived of at birth. Display then those qualities in your own power:
  honesty,
  dignity,
  endurance,
  chastity,
  contentment,
  frugality,
  kindness,
  freedom,
  persistence,
  avoiding gossip,
  and magnanimity.' —MARCUS AURELIUS,
  MEDITATIONS,
  5.
5 t's easy to blame our circumstances.
One person curses that they weren't born taller,
  another that they're not smarter,
  with a different complexion,
  or born in a different country.
It'd be hard to find a single person on this planet—from supermodels on down—who doesn't think they're deficient in at least some way.
But whatever your perceived deficits are,
  remember that there are positive qualities that you can develop that don't depend on genetic accidents.
You have the choice to be truthful.
You have the choice to be dignified.
You can choose to endure.
You can choose to be happy.
You can choose to be chaste.
You can choose to be thrifty.
You can choose to be kind to others.
You can choose to be free.
You can persist under difficult odds.
You can avoid trafficking in gossip.
You can choose to be gracious.
And honestly,
  aren't the traits that are the result of effort and skill more impressive anyway?
T
#+end_verse