#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 28th WE WERE MADE FOR EACH OTHER
#+begin_verse
'You'll more quickly find an earthly thing kept from the earth than you will a person cut off from other human beings.' —MARCUS AURELIUS,
  MEDITATIONS,
  9.
9.
3 aturally,
  Marcus Aurelius and the rest of the Stoics were not familiar with Newtonian physics.
But they knew that what went up must come down.
That's the analogy he's using here:
  our mutual interdependence with our fellow human beings is stronger than the law of gravity.
Philosophy attracts introverts.
The study of human nature can make you aware of other people's faults and can breed contempt for others.
So do struggle and difficulty—they isolate us from the world.
But none of that changes that we are,
  as Aristotle put it,
  social animals.
We need each other.
We must be there for each other.
We must take care of each other (and to allow others to care for us in return).
To pretend otherwise is to violate our nature,
  to be more or less than what it means to be a human being.
I
#+end_verse