#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 13th REVENGE IS A DISH BEST NOT SERVED
#+begin_verse
'The best way to avenge yourself is to not be like that.' —MARCUS AURELIUS,
  MEDITATIONS,
  6.
6 'How much better to heal than seek revenge from injury. Vengeance wastes a lot of time and exposes you to many more injuries than the first that sparked it. Anger always outlasts hurt. Best to take the opposite course. Would anyone think it normal to return a kick to a mule or a bite to a dog?' —SENECA,
  ON ANGER,
  3.
27.
2 et's say that someone has treated you rudely.
Let's say someone got promoted ahead of you because they took credit for your work or did something dishonest.
It's natural to think:
  Oh,
  that's how the world works,
  or One day it will be my turn to be like that.
Or most common:
  I'll get them for this.
Except these are the worst possible responses to bad behavior.
As Marcus and Seneca both wrote,
  the proper response—indeed the best revenge—is to exact no revenge at all.
If someone treats you rudely and you respond with rudeness,
  you have not done anything but prove to them that they were justified in their actions.
If you meet other people's dishonesty with dishonesty of your own,
  guess what?
You're proving them right—now everyone is a liar.
Instead,
  today,
  let's seek to be better than the things that disappoint or hurt us.
Let's try to be the example we'd like others to follow.
It's awful to be a cheat,
  to be selfish,
  to feel the need to inflict pain on our fellow human beings.
Meanwhile,
  living morally and well is quite nice.
T
#+end_verse