#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* October 2nd THE MOST VALUABLE ASSET
#+begin_verse
'But the wise person can lose nothing. Such a person has everything stored up for themselves,
  leaving nothing to Fortune,
  their own goods are held firm,
  bound in virtue,
  which requires nothing from chance,
  and therefore can't be either increased or diminished.' —SENECA,
  ON THE FIRMNESS OF THE WISE,
  5.
4 ome people put their money in assets—stocks,
  bonds,
  property.
Others invest in relationships or accomplishments,
  knowing that they can draw on these things just as easily as others can draw funds from a bank account.
But a third type,
  Seneca says,
  invests in themselves —in being a good and wise person.
Which of these assets is most immune to market fluctuations and disasters?
Which is most resilient in the face of trials and tribulations?
Which will never abandon you?
Seneca's own life is an interesting example.
He became quite wealthy as a friend of the emperor,
  but as Nero became more and more deranged,
  Seneca realized he needed to get out.
He offered Nero a deal:
  he would give Nero all his money and return all of Nero's gifts in exchange for complete and total freedom.
Ultimately,
  Nero rejected this offer,
  but Seneca left anyway,
  retiring in relative peace.
But one day,
  the executioners came with their mortal decree.
In that moment,
  what did Seneca rely on?
It wasn't his money.
It wasn't his friends,
  who,
  although they meant well,
  were a considerable source of grief and mourning.
It was his virtue and inner strength.
It was Seneca's most trying moment—his last and his finest.
A
#+end_verse