#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 08 The Slavic peoples of Central and Eastern Europe
#+begin_verse
North of Byzantium and east of the Carolingian Empire lay a spacious plain
	through which a number of Asiatic nomads,
		including the Huns, Bulgars, Avars, and Magyars, had pushed their way westward,
			terrorizing and plundering the settled peasant communities.
Eastern Europe was ravaged by these successive waves of invaders,
	who found it relatively easy to create large empires
		that were in turn overthrown by the next invaders.
Over a period of time,
	the invaders themselves were largely assimilated with the native Slavic peoples of the area.

The Slavs were originally a single people in central Europe who,
		through mass migrations and nomadic invasions,
	gradually divided into three major groups: the western, southern, and eastern Slavs.
#+end_verse
		
** expression
spacious [ˈspeɪʃəs]: adj. a spacious house, room etc is large and has plenty of space to move around in OPP cramped宽广的
Asiatic [ˌeɪziˈætɪk]: adj. from or connected with Asia亚洲(人)的
nomad [ˈnoʊˌmæd]: n. a member of a tribe that travels from place to place instead of living in one place all the time, usually in order to find grass for their animals游牧部落的人, 流浪者, 游牧民
westward [ˈwestwərd]: adv. towards the west向西
terrorize [ˈterəˌraɪz]: v. to deliberately frighten people by threatening to harm them, especially so they will do what you want使恐怖, 恐吓, 恐怖统治
plunder [ˈplʌndər]: v. to steal large amounts of money or property from somewhere, especially while fighting in a war抢劫
peasant [ˈpez(ə)nt]: n. a poor farmer who owns or rents a small amount of land, either in past times or in poor countries农夫, 乡下人
ravage [ˈrævɪdʒ]: v. to damage something very badly毁坏, 掠夺
successive [səkˈsesɪv]: adj. coming or following one after the other连续的
overthrow [ˈoʊvərˌθroʊ]: v. to get rid of the rules, ideas, or systems of a society推翻, 颠覆
migration [maɪˈɡreɪʃ(ə)n]: n. when large numbers of people go to live in another area or country, especially in order to find work移民
--------------------
push sb's way westward: 向西推进
these successive waves of sth.: 某事物的连续的几波
be assimilated with sth./sb.: 被某物/人同化
divide into sth.(pl.): 分成...
** sentences
spacious:a spacious house, room etc is large and has plenty of space to move around in OPP cramped宽广的
- These nomads used to live on a spacious plain. 
- There is an abduction by a group of gangsters who live on a spacious plain.
- She found it relatively difficult to take a bath on a spacious plain.
Asiatic:from or connected with Asia亚洲(人)的
- She claimed that these Asiatic warriors were vital for the success of the war. 
- There are some Asiatic foods in the back of your fridge.
- A group of Asiatic entrepreneurs will be setting up factories in the suburbs of the city.
nomad:a member of a tribe that travels from place to place instead of living in one place all the time, usually in order to find grass for their animals游牧部落的人, 流浪者, 游牧民
- Last week, I moved to the suburb of the city
		where a nomad was said to ask for a meal twice a week.
- I ran into a nomad who told me pirate stories.
- These stray dogs are barking at the nomad who ate their food in the trash can.
westward: towards the west向西
- She kept journeying westward to Rome to hear Mass in the Saint Peter's Basilica.
- Insidiously, smallpox made its way westward through these Asiatic merchants.
- It suddenly occurred to me to move westward.
terrorize: to deliberately frighten people by threatening to harm them, especially so they will do what you want使恐怖, 恐吓, 恐怖统治 be terrorized into doing something
- Terrorized into paying a ransom of $1000, she went to the police.
- I used to be terrorized into giving my pocket money at the corner of the school in my youth.
- I was terrorized into giving him the cat which is very dear to me.
plunder: to steal large amounts of money or property from somewhere, especially while fighting in a war抢劫
- Not receiving protection money, they threatened to plunder me at midnight.
- Following his boss's instructions,
		he plundered a small grocery, which caused him to be in prison for twenty years.
- It astounded the senate that the village had been plundered by an Asiatic army yesterday.
peasant: a poor farmer who owns or rents a small amount of land, either in past times or in poor countries农夫, 乡下人
- I don't want to share my food with a peasant.
- It astounded me that a peasant broke a world record in the competition.
- Keeping my word, I shared my food with the peasant who saved my life.
ravage: to damage something very badly毁坏, 掠夺
- It looked as if the city had been ravaged twice times.
- Seemingly, the ravaged city would have been reborn after the emergence of the City Comptroller.
- Once the airport parked on the roof of an apartment in a ravaged city.
successive: coming or following one after the other连续的
- Keeping in its word, the team performed successive experiments to prove it right.
- On the journey, the group of pop singers will give successive performances in this town.
- Forced to do successive works, she got very angry.
overthrow: to get rid of the rules, ideas, or systems of a society推翻, 颠覆
- The local people tended to overthrow the authorities who didn't respect their god.
- Following in his father's footsteps, he overthrew the government by plundering the city.
- Sticking together, they eventually overthrew the authorities who were too hard on their people.
migrate migration: when large numbers of people go to live in another area or country, especially in order to find work移民
- A migration involves not only your property and money but also your family.
- After his entire, he decided to migrate to Rome.
- 'You want to migrate after you poisoned your husband.' The detective spoke with a sneer.
--------------------
push sb's way westward: 向西推进
- We must push our way westward.
- We can't push our way westward because of these brutal lions who are going to feast on our bodies.
- Why don't we push our way westward?
these successive waves of sth.: 某事物的连续的几波
- These successive waves of fires burnt down the museum that I paid a visit to yesterday.
- These successive waves of invaders led to a great number of refugees.
- These successive waves of invaders led to the emergence of Western civilization.
be assimilated with sth./sb.: 被某物/人同化
- Needless to say, she was assimilated with the local people.
- Believe it or not, she must be assimilated with our enemies.
- To pursue his goals, he is ready to be assimilated with these warriors.
divide into sth.(pl.): 分成...
- Our students tend to divide into three groups.
- Dividing into three parts, she shared the cake with her close friends.
- His father divided the properties into two groups for him and his brother. 
