#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 10 The Crusades of the Thirteenth Century
#+begin_verse
After the death of Saladin in 1193, Pope Innocent III initiated the Fourth Crusade.
On its way to the east,
	the crusading army became involved in a dispute over the succession to the Byzantine throne.
The Venetian leaders of the Fourth Crusade
	saw an opportunity to neutralize their greatest commercial competitor, the Byzantine Empire.
Diverted to Constantinople,
	the crusaders sacked that great capital city in 1204
		and declared the new Latin Empire of Constantinople.
Not until 1261 did a Byzantine army recapture Constantinople.
The Byzantine Empire had been saved, but it was no longer a great Mediterranean power.
The restored empire now consisted only of the city of Constantinople
	and its surrounding territory along with some lands in Asia Minor.
Though reduced in size, the empire limped along for another 190 years
	until its weakened condition finally enabled the Ottoman Turks to conquer it in 1453.

Despite the failures, the crusading ideal was not yet completely lost.
In Germany in 1212, a youth known as Nicholas of Cologne announced
	that God had inspired him to lead a Children’s Crusade to the Holy Land.
Thousands of young people joined Nicholas
	and made their way down the Rhine and across the Alps to Italy,
	where the pope told them to go home.
Most tried to do so.
At about the same time,
	a group of about twenty thousand French children,
			also inspired by the desire to free the Holy Land from the Muslims,
		made their way to Marseilles,
			where two shipowners agreed to transport them to the Holy Land.
Seven ships packed with hymn-singing youths soon left the port.
Two of the ships sank in a storm near Sardinia;
	the other five sailed to North Africa, where the children were sold into slavery.
Four more Crusades of adult warriors over the next half-century were no more successful.
Finally, Europe’s Christians grudgingly accepted
	that they were not to be the guardians of the the Holy Land.
#+end_verse
** expression
initiate [ɪˈnɪʃiˌeɪt]: v. formal to arrange for something important to start, such as an official process or a new plan开始, 发动
succession [səkˈseʃ(ə)n]: n. the act of taking over an official job or position, or the right to be the next to take it ⇨ accession继承, 继任
throne [θroʊn]: n. a special chair used by a king or queen at important ceremonies王座
neutralize [ˈnutrəˌlaɪz]: v. to destroy something that is dangerous to you during a war摧毁
sack [sæk]: v. if soldiers sack a place, they go through it destroying or stealing things and attacking people洗劫
recapture [ˌriˈkæptʃər]: v. to take control of a place again by fighting for it SYN retake夺回
territory [ˈterəˌtɔri]: n. land that is owned or controlled by a particular country, ruler, or military force领土
conquer [ˈkɑŋkər]: v. to get control of a country by fighting征服
ideal [aɪˈdiəl]: n.adj. 理想
warrior [ˈwɔriər]: n. a soldier or fighter who is brave and experienced – used about people in the past勇士
guardian [ˈɡɑrdiən]: n. someone who guards or protects something护卫者, 监护人
--------------------
On sb's way to sp.: 某人去某地的路上
a dispute over sth.: 对某事的争端
see an opportunity to do sth.: 看到做某事的机会
be diverted to sp.: 被转移到某地
limp along: 艰难前行
sb. announced that + ...: 某人宣布...
inspire sb. to do sth.: 激励某人去做某事
lead sb. to sp.: 带领某人去某地
free A from B: 从B释放A
** sentence
initiate: v. formal to arrange for something important to start, such as an official process or a new plan开始, 发动
- The vassals were eager to initiate the conspiracy which was used to lead to the king's fall down.
- The progress will be initiated if you press the red button.
- They planned out the wedding to the last detail and will be initiating it next Sunday.
succession: n. the act of taking over an official job or position, or the right to be the next to take it ⇨ accession继承, 继任
- The knight went out of his way to prevent him from a dispute over the succession to the lord.
- He pointed out
		that the succession to the guardian of the city would lead to a series of disasters.
- It is said that the succession to the throne still remains a mystery.
throne: n. a special chair used by a king or queen at important ceremonies王座
- Even though he was on the throne, George still had his head cut because of a set of failures.
- Beyond doubt, no prince doesn't want the throne.
- He by no means has the access to the throne of the emperor.
neutralize: v. to destroy something that is dangerous to you during a war摧毁
- He was determined to neutralize these Asiatic nomads.
- It is a coincidence
		that the loss of the queen became the reason for neutralizing the great emperor.
- These states in Greece conspired to neutralize the great emperor.
sack: v. if soldiers sack a place, they go through it destroying or stealing things and attacking people洗劫
- The crusading army intended to sack a third of the territory of the great emperor.
- They have sacked several cities on their conquests in Asia. 
- After having been sacking this city for three days, they initiated a fireworks display.
recapture: v. to take control of a place again by fighting for it SYN retake夺回
- The general has the impulse to recapture the capital city of Rome.
- These soldiers were left recapturing the district which was sacked ten days ago.
- The success of action last week motivated him to recapture the capital city.
territory: n. land that is owned or controlled by a particular country, ruler, or military force领土
- You're not allowed to stand on my territory.
- The increase of the territory, coupled with the rise in status,
		the capital country became the center of trade in the world. 
- It all began back when a group of explorers appeared on the territory of the lord.
conquer: v. to get control of a country by fighting
- I must have conquered her last night.
- I can't have conquered such a great emperor over a period of three months.
- The emperor is busy conquering some small countries in Greece.
ideal: n.adj. 理想,理想的
- The ideal silk business has not been completed yet.
- The ideal marriage partner has not emerged in his life.
- He musters up the courage to lead an ideal life for the rest of his life.
warrior: n. a soldier or fighter who is brave and experienced – used about people in the past勇士
- It is a warrior's job to fight his lord against these nomads.
- The warrior grudged keeping guard in front of the entrance of the palace.
- The warrior turns out to be killed in action.
guardian: n. someone who guards or protects something护卫者, 监护人
- My ex-wife informed me that she has been the guardian of our daughter right from the start. 
- I have the impulse to be the guardian of the cute girl.
- They quarreled bitterly over who was the guardian of their son.
--------------------
On sb's way to sp.: 某人去某地的路上
- On my way to school, I ran into a beggar who asked me for a lift.
- On her way home, she realized that her husband had cheated on her.
- On its way to the kitchen, the cat smashed everything into pieces.
a dispute over sth.: 对某事的争端
- There are always disputes over the taxi fares, for they are not clear.
- I don't want a dispute between you and me, for I used to bargain with other.
- The tickets have been sold out, which led to a dispute between the manager and the clerk.
see an opportunity to do sth.: 看到做某事的机会
- I have seen an opportunity to predict the future.
- I haven't seen any opportunity to fulfill my dream.
- My wife have seen an opportunity to kiss me on New Year's Eve.
be diverted to sp.: 被转移到某地
- Diverted to Beijing, these workers will be given five performances.
- Diverted to America, he worked for a big firm.
- Diverted to America, he shared his house with a stray dog.
limp along: 艰难前行
- Although the gangster threatened to put her out of business, her furniture business is still limping along.
- Not making an ideal profit last year, our company is still limping along.
- Limping along for years, he eventually followed in his father's footsteps.
sb. announced that + ...: 某人宣布...
- I announced that I am fluent in English. 
- I announced that our wedding would be held next month.
- I announced that my son applied to Harvard University.
inspire sb. to do sth.: 激励某人去做某事
- The desire to lead a happy life inspired him to take adventure in his furniture business.
- The rise in salary inspired me to work to my bone.
- The reward for virtue inspired people to behave better in a daily routine.
lead sb. to sp.: 带领某人去某地
- In a daily routine, I led passengers to the airfield.
- Leading passengers to a strange place, the police asked them for all of their money.
- Sweetie, lead your uncle to our apartment to grab a cup of beer.
free A from B: 从B释放A
- He found it relatively easy to free himself from the prison.
- He has dug up the wall for twenty years and freed himself from the prison.
- You have committed a sin when you freed a criminal from here.
** summary
In 1913, Pope Innocent III initiated the Fourth Crusade.
As the Byzantine emperor was Venetian's greatest commercial competitor,
	the Venetian leaders of the Crusade sacked Constantinople
		and declared a new Latin empire of Constantinople.
Though Constantinople was recaptured by a Byzantine army,
	reducing in size,
	the empire limped along for 190 years until it was conquered by the Ottoman Turks.
Despite the failures, the crusading ideal was not completed.
In Germany in 1212,
	a Children's Crusade consisting of 2000 children
		made their way down the Rhine and across the Alps to Italy, where the pope told them to go home.
Another group of about 20,000 French children
	was promised to transport them to the Holy Land by two shipowners in Marseilles.
Two of their ships sank in a storm and other children were sold into slavery in Africa.
As four more Crusade of adult warriors were not more successful,
	Europe's Christians grudgingly accepted that they were not the guardians of the Holy Land.
