#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 12 Michelangelo's Creation of Adam on the Sistine Chapel ceiling
#+begin_verse
Were the fourteenth and fifteenth centuries a continuation of the Middle Ages
	or the beginning of a new era?
The answer is that both positions are true.
Although the disintegrative patterns of the fourteenth century continued into the fifteenth,
	at the same time there were elements of recovery
		that made the fifteenth century
			a period of significant political, economic, artistic, and intellectual change.
The humanists or intellectuals of the age
	considered their period (from the mid-fourteenth to the mid-sixteenth century) an age of rebirth,
	believing that they had restored arts and letters to new glory
		after they had been neglected or dead for centuries.
The humanists also saw their age as one of accomplished individuals
	who dominated the landscape of their time.
Michelangelo, the great Italian artist of the early sixteenth century,
	and Pope Julius II, the warrior pope, were two such titans.
The artist's temperament and the pope's temper
	led to many lengthy and often loud quarrels between the two.
Among other commissions,
	the pope had hired Michelangelo to paint the ceiling of the Sistine Chapel in Rome,
	a daunting task for a man long accustomed to being a sculptor.
Michelangelo undertook the project
	but refused for a long time to allow anyone, including the pope, to see his work.
Julius grew anxious,
	pestering Michelangelo on a regular basis about when the ceiling would be finished.
Exasperated by the pope's requests,
	Michelangelo once replied, according to Giorgio Vasari, his contemporary biographer,
		that the ceiling would be completed 'when it satisfies me as an artist.'
The pope responded,	'And we want you to satisfy us and finish it soon,'
	and then threatened that if Michelangelo did not finish the ceiling quickly
		the pope would have him thrown down from the scaffolding.
Fearing the pope's anger,
	Michelangelo lost no time in doing all that was wanted and quickly completed the ceiling,
		one of the great masterpieces of Western art.

The humanists' view of their age as
		a rebirth of the Classical civilization of the Greeks and Romans
	ultimately led historians to use the French word Renaissance to identify this age.
Although recent historians have emphasized the many elements of continuity
		between the Middle Ages and the Renaissance,
	the latter age was also distinguished by its own unique characteristics.
#+end_verse
** expression
continuation [kənˌtɪnjuˈeɪʃ(ə)n]: n. something that continues or follows something else that has happened before, without a stop or change延续
position [pəˈzɪʃ(ə)n]: n. the situation that someone is in, especially when this affects what they can and cannot do立场,位置
significant [sɪɡˈnɪfɪkənt]: adj. having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
humanism [ˈhjuməˌnɪzəm] humanist: n. the belief that human problems can be solved through science rather than religion人本主义
neglect [nəˈɡlekt]: v. to pay too little attention to something忽视, 疏忽
accomplished [əˈkʌmplɪʃt]: adj. an accomplished writer, painter, singer etc is very skilful多才多艺的
landscape [ˈlændˌskeɪp]: n. the political/social landscape the general situation in which a particular activity takes place形势
titan [ˈtaɪt(ə)n]: n. a very strong or important person SYN giant巨人
temperament [ˈtemp(ə)rəmənt]: n. the emotional part of someone’s character, especially how likely they are to be happy, angry etc气质
lengthy [ˈleŋθi]: adj. continuing for a long time, often too long OPP brief冗长的, 过分的
commission [kəˈmɪʃ(ə)n]: n. a request for an artist, designer, or musician to make a piece of art or music, for which they are paid委托
ceiling [ˈsilɪŋ]: n. the inner surface of the top part of a room ⇨ roof天花板
daunting [ˈdɔntɪŋ]: adj. frightening in a way that makes you feel less confident使人畏缩的
exasperate [ɪɡˈzæspəˌreɪt]: v. to make someone very annoyed by continuing to do something that upsets them激怒
biographer [baɪˈɑɡrəfər]: n. someone who writes a biography of someone else传记作者
scaffolding [ˈskæfoʊldɪŋ]: n. a set of poles and boards that are built into a structure for workers to stand on when they are working on the outside of a building脚手架
historian [hɪˈstɔriən]: n. someone who studies history, or the history of a particular thing历史学家
emphasize [ˈemfəˌsaɪz]: v. to say something in a strong way SYN stress强调
distinguish [dɪˈstɪŋɡwɪʃ]: v. to recognize and understand the difference between two or more things or people SYN differentiate区别
--------------------
continue into st.(the future): 持续到未来
restore sth. to new glory: 恢复某事的新荣耀(辉煌)
hire sb. to do sth.: 雇佣某人去做某事
pester sb. about sth.: 纠缠某人某事
on a regular basis: 定期的
sb. threatens that + ...: 某人威胁...
lose no time in doing sth.: 不浪费时间马上做某事
view of A as B: 把A视作为B的观点
** sentence
continuation: n. something that continues or follows something else that has happened before, without a stop or change延续
- The silk industry was seen as the continuation of the clothing industry.
- The suburban was said to be the continuation of the great city.
- It occurred to me that the island was the continuation of the land.
position: n. the situation that someone is in, especially when this affects what they can and cannot do立场,位置
- If I were in your position, I would not accept such stupid criticism.
- You'd better not laugh at somebody when you don't know his position.
- My position is at line 3, row 5 in the theater.
significant: adj. having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
- A new machine was used to detect gold proved significant because of subsequent discoveries of buried treasure.
- The pope enacted a significant ritual to crown the German king.
- The masterpiece is so significant that it exerted tremendous influences on modern arts.
humanism humanist: n. the belief that human problems can be solved through science rather than religion人本主义
- It was these humanists who saved us from this pleague, not the church.
- The humanist was said to possess a large manor.
- The humanist had a good reputation for educating his followers.
neglect: v. to pay too little attention to something忽视, 疏忽
- He neglected to do homework so that he could sit in a boat and do nothing at all.
- She neglected to feed their cat, which gave rise to the collapse of their marriage.
- The notes which you left prevented me from neglecting to do housework.
accomplished: adj. an accomplished writer, painter, singer etc is very skilful多才多艺的
- The well-educated experience in his youth makes him an accomplished intellectual.
- Beyond doubts, the accomplished intellectual has a skeleton in the cupboard.
- The man who won the prize for the best pianist is by no means regarded as an accomplished intellectual.
landscape: n. the political/social landscape the general situation in which a particular activity takes place形势
- The embassador was stunned by the political landscape of Europe.
- The senator tried to explain the political landscape of their country to people.
- The crowds gathered round so that they could communicate to figure out the landscape of their country.
titan: n. a very strong or important person SYN giant大师
- The tower named after Mr. Leo who is by no means a titan.
- Following his father's footstep, he became a titan in gardening.
- Captain, we must rise to 10000 feet so that we could fly over the titan.
temperament: n. the emotional part of someone’s character, especially how likely they are to be happy, angry etc气质
- No one could account for the fact that he was blessed with a gentleman's temperament.
- Because of the poet's temperament, he never fails to fascinate girls of his own age.
- His so-called poet's temperament led to the envy of the pope who confined him in prison for two years.
lengthy: adj. continuing for a long time, often too long OPP brief冗长的, 过分的
- It is no use writting such a lengthy article which won't be graded a high score.
- I was instructed to write a lengthy letter to my wife in order to celebrate our anniversity.
- He has a sense of humor and people won't feel tired of a lengthy story told by him.
commission: n. a request for an artist, designer, or musician to make a piece of art or music, for which they are paid委托
- He didn't hesitate to undertake the commission from the college for a god sculpture.
- Sensitive to criticism, the humanist refused to undertake another commission for the ceiling paint.
- Believe it or not, my husband will undertake the arduous commission for the ring.
ceiling: n. the inner surface of the top part of a room ⇨ roof天花板
- As soon as we bought the house, my wife complained about the broken ceiling.
- A group of enthusiasm is going to repair the broken ceiling in the chapel.
- The light in the ceiling is flashing angry on and off.
daunting: adj. frightening in a way that makes you feel less confident使人畏缩的
- The task of crusading states of Muslims is so daunting that our knights got scared. 
- The arduous journey seems to be daunting.
- He mustered up his courage to accept the daunting task.
exasperate: v. to make someone very annoyed by continuing to do something that upsets them激怒
- Exasperated by their laughter, he was determined to undertake the arduous task.
- Exasparated by the red cap, the bull turned its attention to the drunk and charged at him.
- Exasparated by my action, my cat eventually bited me firmly.
biographer: n. someone who writes a biography of someone else传记作者
- The biographer was not allowed to take part in the cornation of the emperor.
- According his contemporary biographer, the pope assummed political power during the period of the Crusade.
- The biographer ordered his men to give up these food sacks.
scaffolding: n. a set of poles and boards that are built into a structure for workers to stand on when they are working on the outside of a building脚手架
- He is having an operation, for he fell down from a scaffolding.
- It seems daunting to set up such a big scaffolding.
- I am expert at setting up big scaffoldings.
historian: n. someone who studies history, or the history of a particular thing历史学家
- The historian felt obligated to undertake those arduous translating work.
- The translating work is arduous that the historian had to employee several assistants. 
- The historian was confined to the ring to stand trails for his offsenive words towards the pope.
emphasize: v. to say something in a strong way SYN stress强调
- He emphasized that our people was able to surivive the daunting floods.
- My wife emphasized that our cat must be fed twice a day.
- It is no use emphasizing so many times.
distinguish: v. to recognize and understand the difference between two or more things or people SYN differentiate区别
- Obviously, the snake could not distinguish the difference between Indian music and jazz.
- This convinced me that our car could distinguish red and blue colors.
- It is not necessary to distinguish whether you are white or black in the states.
--------------------
continue into st.(the future): 持续到未来
- This is why the incline of trade and industry continued into the thirteenth century.
- The papal claims of supermacy over secular authorities continued into the next century.
- The lead she took in her class continued into the next semester.
restore sth. to new glory: 恢复某事的新荣耀(辉煌)
- The expert felt obligated to restore the zoo to new glory.
- He is determined to restore the silk industry to new glory so that he can win a large sum of money.
- He restored the monarchical state to new glory in pursuit of his power.
hire sb. to do sth.: 雇佣某人去做某事
- Women are not allowed to be hired to do manual work these days.
- I hate anyone who hired me to do manual work in such harsher working condition.
- He insisted on hiring the ill man to search for the case.
pester sb. about sth.: 纠缠某人某事
- My wife never pesters me about diamond which other girls dream of.
- I pestered my doctor about when I was allowed to leave hospital.
- My cat pestered me on a regular basis about a can which I gave her last week.
on a regular basis: 定期的
- The invention of clocks reimined people in the fourteenth century of finishing their work on a regular basis.
- Your body should be examined on a regular basis.
- I used to feed my cat on a regular basis.
sb. threatens that + ...: 某人威胁...
- He threatened that if I didn't give him the key, he would prise the drawer open.
- He threatened that he would jump from the building if anyone got close to him.
- He threatened that if she dived into the water, he would follow her.
lose no time in doing sth.: 不浪费时间马上做某事
- The girl lost no time in catching a flight after the alarm had been given.
- The cat lost no time in rushing up to me.
- Mrs. Leo lost no time in catching up with these thieves.
view of A as B: 把A视作为B的观点
- I admired him for his view of difficulties as chances.
- His view of difficulties as chances makes him resilient.
- His view of difficulties as chances inspired me to pursue my goal.
** sentence2
continuation: n. something that continues or follows something else that has happened before, without a stop or change延续
- The silk industry was seen as the continuation of the clothing industry.
- The suburban was said to be the continuation of the great city.
- It occurred to me that the island was the continuation of the land.
position: n. the situation that someone is in, especially when this affects what they can and cannot do立场,位置
- If I were in your position, I would not accept such stupid criticism.
- You'd better not laugh at somebody when you don't know his position.
- My position is at line 3, row 5 in the theater.
significant: adj. having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
- A new machine that was used to detect gold proved significant because of subsequent discoveries of buried treasure.
- The pope enacted a significant ritual to crown the German king.
- The masterpiece is so significant that it exerted tremendous influences on modern art.
humanism humanist: n. the belief that human problems can be solved through science rather than religion人本主义
- It was these humanists who saved us from this plague, not the church.
- The humanist was said to possess a large manor.
- The humanist had a good reputation for educating his followers.
neglect: v. to pay too little attention to something忽视, 疏忽
- He neglected to do homework so that he could sit in a boat and do nothing at all.
- She neglected to feed their cat, which gave rise to the collapse of their marriage.
- The notes which you left prevented me from neglecting to do housework.
accomplished: adj. an accomplished writer, painter, singer etc is very skilful多才多艺的
- The well-educated experience in his youth makes him an accomplished intellectual.
- Beyond doubt, the accomplished intellectual has a skeleton in the cupboard.
- The man who won the prize for the best pianist is by no means regarded as an accomplished intellectual.
landscape: n. the political/social landscape the general situation in which a particular activity takes place形势
- The ambassador was stunned by the political landscape of Europe.
- The senator tried to explain the political landscape of their country to people.
- The crowds gathered round so that they could communicate to figure out the landscape of their country.
titan: n. a very strong or important person SYN giant大师
- The tower is named after Mr. Leo who is by no means a titan.
- Following in his father's footsteps, he became a titan in gardening.
- Captain, we must rise to 10000 feet so that we can fly over the Titan.
temperament: n. the emotional part of someone’s character, especially how likely they are to be happy, angry etc气质
- No one could account for the fact that he was blessed with a gentleman's temperament.
- Because of the poet's temperament, he never fails to fascinate girls of his own age.
- His so-called poet's temperament led to the envy of the pope who confined him in prison for two years.
lengthy: adj. continuing for a long time, often too long OPP brief冗长的, 过分的
- It is no use writing such a lengthy article which won't be graded a high score.
- I was instructed to write a lengthy letter to my wife in order to celebrate our anniversary.
- He has a sense of humor and people won't feel tired of a lengthy story told by him.
commission: n. a request for an artist, designer, or musician to make a piece of art or music, for which they are paid委托
- He didn't hesitate to undertake the commission from the college for a god sculpture.
- Sensitive to criticism, the humanist refused to undertake another commission for the ceiling paint.
- Believe it or not, my husband will undertake the arduous commission for the ring.
ceiling: n. the inner surface of the top part of a room ⇨ roof天花板
- As soon as we bought the house, my wife complained about the broken ceiling.
- A group of enthusiasts is going to repair the broken ceiling in the chapel.
- The light in the ceiling is flashing angrily on and off.
daunting: adj. frightening in a way that makes you feel less confident使人畏缩的
- The task of crusading states of Muslims is so daunting that our knights got scared. 
- The arduous journey seems to be daunting.
- He mustered up his courage to accept the daunting task.
exasperate: v. to make someone very annoyed by continuing to do something that upsets them激怒
- Exasperated by their laughter, he was determined to undertake the arduous task.
- Exasperated by the red cap, the bull turned its attention to the drunk and charged at him.
- Exasperated by my action, my cat eventually bit me firmly.
biographer: n. someone who writes a biography of someone else传记作者
- The biographer was not allowed to take part in the coronation of the emperor.
- According to his contemporary biographer, the pope assumed political power during the period of the Crusade.
- The biographer ordered his men to give up these food sacks.
scaffolding: n. a set of poles and boards that are built into a structure for workers to stand on when they are working on the outside of a building脚手架
- He is having an operation, for he fell down from a scaffolding.
- It seems daunting to set up such a big scaffolding.
- I am an expert at setting up big scaffoldings.
historian: n. someone who studies history, or the history of a particular thing历史学家
- The historian felt obligated to undertake those arduous translating work.
- The translating work is so arduous that the historian had to employ several assistants. 
- The historian was confined to the ring to stand trials for his offensive words towards the pope.
emphasize: v. to say something in a strong way SYN stress强调
- He emphasized that our people were able to survive the daunting floods.
- My wife emphasized that our cat must be fed twice a day.
- It is no use emphasizing so many times.
distinguish: v. to recognize and understand the difference between two or more things or people SYN differentiate区别
- Obviously, the snake could not distinguish the difference between Indian music and jazz.
- This convinced me that our car could distinguish between red and blue colors.
- It is not necessary to distinguish whether you are white or black in the States.
--------------------
continue into st.(the future): 持续到未来
- This is why the incline of trade and industry continued into the thirteenth century.
- The papal claims of supremacy over secular authorities continued into the next century.
- The lead she took in her class continued into the next semester.
restore sth. to new glory: 恢复某事的新荣耀(辉煌)
- The expert felt obligated to restore the zoo to new glory.
- He is determined to restore the silk industry to new glory so that he can win a large sum of money.
- He restored the monarchical state to new glory in pursuit of his power.
hire sb. to do sth.: 雇佣某人去做某事
- Women are not allowed to be hired to do manual work these days.
- I hate anyone who hired me to do manual work in such harsher working conditions.
- He insisted on hiring the ill man to search for the case.
pester sb. about sth.: 纠缠某人某事
- My wife never pesters me about diamonds which other girls dream of.
- I pestered my doctor about when I was allowed to leave the hospital.
- My cat pestered me on a regular basis about a can I gave her last week.
on a regular basis: 定期的
- The invention of clocks reminded people in the fourteenth century of finishing their work on a regular basis.
- Your body should be examined on a regular basis.
- I used to feed my cat on a regular basis.
sb. threatens that + ...: 某人威胁...
- He threatened that if I didn't give him the key, he would prise the drawer open.
- He threatened that he would jump from the building if anyone got close to him.
- He threatened that if she dived into the water, he would follow her.
lose no time in doing sth.: 不浪费时间马上做某事
- The girl lost no time in catching a flight after the alarm had been given.
- The cat lost no time in rushing up to me.
- Mrs. Leo lost no time in catching up with these thieves.
view of A as B: 把A视作为B的观点
- I admired him for his view of difficulties as chances.
- His view of difficulties as chances makes him resilient.
- His view of difficulties as chances inspired me to pursue my goal.
** summary
Although the disintegrative patterns of the fourteenth century continued into the fifteenth,
	elements of recovery made the fifteenth
		a period of significant political, economic, artistic, and intellectual change.
Michaelongelo and Pope Julius II were two titans.
Among other commissions, the pope hired the artist to paint the ceiling of the Sistine Chapel
	which is a daunting task for Michaelongelo long accustomed to being a sculptor.
Because Michaelongelo didn't allow anyone to see his work before he finished it
	and Julius grew anxious,
	there were quarrels between them.
Michaelongelo said it would be finished until it satisfied him as an artist
	and Julius replied the artist must finish it soon
		otherwise he would have him thrown down from the scaffolding.
At last, the paint of the ceiling of the Sistine Chapel, one of greatest Western art,
	was finished quickly.
The humanists' view
		of the age as the rebirth of the Classical Civilization of the Greeks and Romans
	led historians to use the French word Renaissance to identify this age.
** summary2
Although the disintegrative patterns of the fourteenth century continued into the fifteenth,
	elements of recovery made the fifteenth
		a period of significant political, economic, artistic, and intellectual change.
Michaelongelo and Pope Julius II were two titans.
Among other commissions, the pope hired the artist to paint the ceiling of the Sistine Chapel
	which is a daunting task for Michaelongelo long accustomed to being a sculptor.
Because Michaelongelo didn't allow anyone to see his work before he finished it
	and Julius grew anxious,
	there were quarrels between them.
Michaelongelo said it would be finished until it satisfied him as an artist
	and Julius replied the artist must finish it soon otherwise, he would have him thrown down from the scaffolding.
At last, the painting of the ceiling of the Sistine Chapel, one of the greatest Western art,
	was finished quickly.
The humanists' view
		of the age as the rebirth of the Classical Civilization of the Greeks and Romans
	led historians to use the French word Renaissance to identify this age.
