#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 13 A sixteenth-century engraving of Martin Luther in front of Charles V at the Diet of Worms
#+begin_verse
On April 18, 1521,
	a lowly monk stood before the emperor and princes of the Holy Roman Empire in the city of Worms.
He had been called before this august gathering to answer charges of heresy,
	charges that could threaten his very life.
The monk was confronted with a pile of his books
	and asked if he wished to defend them all or reject a part.
Courageously, Martin Luther defended them all
	and asked to be shown where any part was in error on the basis of Scripture and plain reason.
The emperor was outraged by Luther's response and made his own position clear the next day:
'Not only I, but you of this noble German nation, would be forever disgraced
	if by our negligence not only heresy but the very suspicion of heresy were to survive.
After having heard yesterday the obstinate defense of Luther,
	I regret that I have so long delayed in proceeding against him and his false teaching.
I will have no more to do with him.'
Luther's appearance at Worms
	set the stage for a serious challenge to the authority of the Catholic church.
This was by no means the first crisis in the church's fifteen-hundred-year history,
	but its consequences were more far-reaching than anyone at Worms in 1521 could have imagined.

Throughout the Middle Ages,
	the medieval Christian church continued to assert its primacy of position.
It had overcome defiance of its temporal authority by emperors and kings
	while challenges to its doctrines had been crushed by the Inquisition
		and combated by new religious orders
			that carried its message of salvation to all the towns and villages of medieval Europe.
The growth of the papacy had paralleled the growth of the church,
	but by the end of the Middle Ages,
	challenges to papal authority from the rising power of monarchical states
		had resulted in a loss of papal temporal authority.
An even greater threat to papal authority and church unity arose in the sixteenth century
	when the unity of Christendom was shattered by the Reformation.

The movement begun by Martin Luther when he made his dramatic stand quickly spread across Europe,
	a clear indication of dissatisfaction with Catholic practices.
Within a short time, new religious practices, doctrines, and organizations,
		including Zwinglianism, Calvinism, Anabaptism, and Anglicanism,
	were attracting adherents all over Europe.
Seemingly helpless to stop the new Protestant churches,
	the Roman Catholic Church underwent a reformation
		and managed to revive its fortunes by the mid-sixteenth century.
Nevertheless,
	the doctrinal divisions between Protestants and Catholics
		became instrumental in triggering a series of religious wars
			that dominated the history of western Europe in the second half of the sixteenth century.
#+end_verse
** expression
lowly [ˈloʊli]: adj. low in rank, importance, or social class – sometimes used humorously SYN humble地位低的, 卑贱的
emperor [ˈemp(ə)rə(r)]: n. the man who is the ruler of an ↑empire皇帝, 君主
heresy [ˈherəsi]: n. a belief that disagrees with the official principles of a particular religion异端, 异教
defend [dɪˈfend]: v. to do something in order to protect someone or something from being attacked防护, 辩护
disgrace [dɪsˈɡreɪs]: v. to do something so bad that you make other people feel ashamed丢脸
obstinate [ˈɑbstɪnət]: determined not to change your ideas, behaviour, opinions etc, even when other people think you are being unreasonable SYN stubborn倔强的, 顽固的
far-reaching: adj. having a great influence or effect影响深远的
assert [əˈsɜrt]: v. assert your rights/independence/superiority etc to state very strongly your right to something主张,声称
primacy [ˈpraɪməsi]: n. formal if someone or something has primacy, they are the best or most important person or thing首位
defy [dɪˈfaɪ] defiance: v.n. behaviour that shows you refuse to do what someone tells you to do, especially because you do not respect them ⇨ defy挑战,违抗
temporal [ˈtemp(ə)rəl]: adj. related to practical instead of religious affairs世俗的
doctrine [ˈdɑktrɪn]: n. a set of beliefs that form an important part of a religion or system of ideas教条
Inquisition [ˌɪŋkwəˈzɪʃ(ə)n]: the Inquisition a Roman Catholic organization in the past whose aim was to find and punish people who had unacceptable religious beliefs
combat [ˈkɑmˌbæt]: v. to try to stop something bad from happening or getting worse – used especially in news reports防止,抑制
salvation [sælˈveɪʃ(ə)n]: n. something that prevents or saves someone or something from danger, loss, or failure拯救, 救助
papacy [ˈpeɪpəsi]: n. the papacy the position and authority of the Pope罗马教皇职位, 教皇的在位期间
parallel [ˈperəˌlel]: v. if one thing parallels another, they happen at the stime or are similar, and seem to be related相应, 平行
arise [əˈraɪz]: v. if a problem or difficult situation arises, it begins to happen出现, 发生
shatter [ˈʃætə(r)]: v. to break suddenly into very small pieces, or to make something break in this way粉碎
adherent [ədˈhɪrənt]: n. someone who supports a particular belief, plan, political party etc信徒
undergo [ˌʌndərˈɡoʊ]: v. if you undergo a change, an unpleasant experience etc, it happens to you or is done to you经历, 遭受
division [dɪˈvɪʒ(ə)n]: n. the act of separating something into two or more different parts, or the way these parts are separated or shared分裂
trigger [ˈtrɪɡər]: v. to make something happen very quickly, especially a series of events引发
--------------------
threaten sb's very life: 威胁某人的生命
be confronted with sth.: 面临某事
ask to be done sth.: 要求被做某事
in error: 错误地
on the basis of sth.: 在某事物的基础上
made sb's own position clear: 表明某人的立场
by sb's negligence: 由于某人的疏忽
proceed against sb.: 起诉某人
set the stage for sth.: 为某事准备舞台
revive its fortunes: 恢复某事物的繁荣
** sentence
lowly: adj. low in rank, importance, or social class – sometimes used humorously SYN humble地位低的, 卑贱的
- It can give rise to a series of curious situation, as it did in the cause of a lowly monk at the monastery.
- No one could account for the fact that a lowly monk sat down in front of the emporper and princes.
- The prince went out of his way to keep in touch with the daughter of a lowly peasant.
emperor: n. the man who is the ruler of an ↑empire皇帝, 君主
- Because of the failure of the leading war, the emperor may have lost heart.
- The emperor lost heart, which resulted in a series of disaters in this empire.
- The emperor was accused of sacking the city in the west of his empire.
heresy: n. a belief that disagrees with the official principles of a particular religion异端, 异教
- The Catholic church enacted the Equisition in the face of heresy. 
- The church was being challenged by the heresy which attracted the masses in Europe.
- There was a notice about the heresy on the bulletin board.
defend: v. to do something in order to protect someone or something from being attacked防护, 辩护
- Condemned on the thief, he failed to defend himself.
- It is appropriate to defend yourself against these boys who often play truant from school.
- Failing to defend himself against the spies, he was arrested in a hotel.
disgrace: v. to do something so bad that you make other people feel ashamed丢脸
- If you risked you life because of this, you would disgrace yourself in the school.
- The leading cause of disgrace s to mark such stupid remarks in public.
- A shit drifting on the swimming pool near him disgrace him a great deal.
obstinate: adj. determined not to change your ideas, behaviour, opinions etc, even when other people think you are being unreasonable SYN stubborn倔强的, 顽固的
- He was so obstinate that even though we gave him electrical shocks, he didn't change his mind.
- He was so obstinate that he moved south down the river in search of the first civilization. 
- At the end of the harvest, an obstinate boy tried to fire a shot.
far-reaching: adj. having a great influence or effect影响深远的
- The thief proved far-reaching, which put him out of business.
- His education in his youth was far-reaching, which enabled him to become a splendid peasant.
- The movement of sacrificing money for land was far-reaching.
assert: v. assert your rights/independence/superiority etc to state very strongly your right to something主张,声称
- The Catholic church grudged asserting the primacy of the monarchical position.
- As it is, the church asserted its supremacy over the secular authorities after having assumed political power.
- He asserted that someone in our village must have found his money.
primacy: n. formal if someone or something has primacy, they are the best or most important person or thing首位
- The church raised fundamental issues about the primacy of individuals.
- The primacy of what you should do is to keep in touch with your closest relatives.
- The primacy of what we need to do is to find the way to our hotel.
defy defiance: v.n. behaviour that shows you refuse to do what someone tells you to do, especially because you do not respect them ⇨ defy挑战,违抗
- The exalted claim of papal power resulted in the defiance of the monarchs.
- The defiance of the peasants failed to take control of the city.
- The victory of his election gave rise to a serious defiance of his enemies.
temporal: adj. related to practical instead of religious affairs世俗的
- A fraction of clergies is interested in temporal power.
- It is appropriate for the pope to pursue temporal power.
- Imagine his dismay when he found a friar turned out to be a temporal businessman.
doctrine: n. a set of beliefs that form an important part of a religion or system of ideas教条
- I'd rather regard the book as a series of doctrines than the manual of llife.
- The fraction of monks dedicated their life to a set of doctrines.
- The pope drew up a set of doctrines which was used to punish laymen.
Inquisition: the Inquisition a Roman Catholic organization in the past whose aim was to find and punish people who had unacceptable religious beliefs
- 
- 
- 
combat: v. to try to stop something bad from happening or getting worse – used especially in news reports防止,抑制
- The emergence of the cities in the high Middle Ages may have combated the decline of the monarchs.
- The nomads pushed their way westward through the plain, which combated the spread of the Black Death.
- The doctor confirms that the drug combats bad smells.
salvation: n. something that prevents or saves someone or something from danger, loss, or failure拯救, 救助
- His salvation inspired people the world over to raise money.
- The market in China turns out to the salvation of the clothing company.
- This style of clothes becomes popular with young men and women in China, which turns out to be the salvation of the industry.
papacy: n. the papacy the position and authority of the Pope罗马教皇职位, 教皇的在位期间
- He was by no means the succession of the papacy.
- In his papacy, people enacted a special ritual to bury dead.
- In his papacy, people were encouraged to bear more children.
parallel: v. if one thing parallels another, they happen at the stime or are similar, and seem to be related相应, 平行
- My arrivals always parrallel your departures.
- His collapse of marriage parallelled the progress of his career.
- His winning lottery parallelled the job loss.
arise: v. if a problem or difficult situation arises, it begins to happen出现, 发生
- The monarchical power was believed to arise from the cities.
- He lost his life, which arose from his carelessness.
- The death of five mine workers arose from a mine accident.
shatter: v. to break suddenly into very small pieces, or to make something break in this way粉碎
- The shattered rock proved there was a truck.
- I must shatter those food so that the kitten can be fed.
- Shattered in the machine, he lost his life.
adherent: n. someone who supports a particular belief, plan, political party etc信徒
- A so-called adherent is always asking me for a meal once a day.
- The adherent ran out of his water and food in the desert and began to lose his heart.
- As it is, the adherent got enough money to have the monastery repaired.
undergo: v. if you undergo a change, an unpleasant experience etc, it happens to you or is done to you经历, 遭受
- A fraction of lawyers underwent being kept in prison for a week.
- Even though the church underwent serious divisions, there were still many adherents.
- You mother is undergoing an operation which spends a lot of money.
division: n. the act of separating something into two or more different parts, or the way these parts are separated or shared分裂
- I and my wife is tring to figure out the divisions of labor between us.
- The divisions of labor between men and women contribute to our great society.
- The divisions of labor between those people arose from a new technology.
trigger: v. to make something happen very quickly, especially a series of events引发
- The steering wheel came away, which triggered two men's death.
- The curiosity of a stray dog triggered a car accident.
- The breakdown of trust in government triggered social upheaval.
--------------------
threaten sb's very life: 威胁某人的生命
- A group of hungry stray dogs threatened our very life.
- The plain crushed in the forest and the cold threatened his very life.
- He kept in touch with a spy who was threatening his life.
be confronted with sth.: 面临某事
- I wish that I be not confronted with my ex-girlfriend at the reception.
- It is appropriate to be confronted with these difficulties. 
- In spite of being confronted with job loss, he asserted that he went on a vocation in Sanya.
ask to be done sth.: 要求被做某事
- I asked to be shown the evidence that proved me guilty. 
- He asked to be shown the food which the assistant accussed him of stealing.
- He asked to be shown the money she had made. 
in error: 错误地
- He noticed with dismay that his answers were totally in error in the test.
- He noticed the boat moving in error. 
- Sir, you have sat in error in your father's seat.
on the basis of sth.: 在某事物的基础上
- He always publish articles on the basis of the facts and statistics.
- We should get a suitable salary on the basis of our work.
- You should have made remarks on the basis of the fact in public.
make sb's own position clear: 表明某人的立场
- It is appropriate to make your own positin clear.
- Fearing of the responsibilities she needs to take, she never makes her own position clear in public.
- The general at last made his own position clear and defended the succession of the throne against his enemies.
by sb's negligence: 由于某人的疏忽
- My wife blamed me for the death of our kitten by my negligence.
- People would laugh at us at the reception if you didn't wear a suitable by your negligence.
- My superior blamed me for the bugs I made by my negligence.
proceed against sb.: 起诉某人
- As soon as my lawyer arrives on the scene, I will proceed against you.
- He lost heart and proceeded against his neighbor who took possession of his land.
- He blamed the broken vase on his neighbor and was going to proceeded against him.
set the stage for sth.: 为某事准备舞台
- The accomplishments of the general set the stage for the great vampire.
- The flea-infested rats set the stage for the Black Death which erupted in Europe.
- The communications of these countries set the stage for the fusion of a great empire.
revive its fortunes: 恢复某事物的繁荣
- Following in his father's footsteps, he succeeded in reviving his family's fortunes.
- He devoted himself to revive his family's fortunes.
- The marriage between him and the long-daughter of an upper class revived his family's fortunes.
** sentence2
lowly: adj. low in rank, importance, or social class – sometimes used humorously SYN humble地位低的, 卑贱的
- It can give rise to a series of curious situations, as it did in the case of a lowly monk at the monastery.
- No one could account for the fact that a lowly monk sat down in front of the emperor and princes.
- The prince went out of his way to keep in touch with the daughter of a lowly peasant.
emperor: n. the man who is the ruler of an ↑empire皇帝, 君主
- Because of the failure of the leading war, the emperor may have lost his heart.
- The emperor lost his heart, which resulted in a series of disasters in this empire.
- The emperor was accused of sacking the city in the west of his empire.
heresy: n. a belief that disagrees with the official principles of a particular religion异端, 异教
- The Catholic church enacted the Inquisition in the face of heresy. 
- The church was being challenged by heresy which attracted the masses in Europe.
- There was a notice about the heresy on the bulletin board.
defend: v. to do something in order to protect someone or something from being attacked防护, 辩护
- Condemned on the thief, he failed to defend himself.
- It is appropriate to defend yourself against these boys who often play truant from school.
- Failing to defend himself against the spies, he was arrested in a hotel.
disgrace: v. to do something so bad that you make other people feel ashamed丢脸
- If you risked your life because of this, you would disgrace yourself in the school.
- The leading cause of disgrace to mark such stupid remarks in public.
- A shit drifting on the swimming pool near him disgraced him a great deal.
obstinate: adj. determined not to change your ideas, behaviour, opinions etc, even when other people think you are being unreasonable SYN stubborn倔强的, 顽固的
- He was so obstinate that even though we gave him electrical shocks, he didn't change his mind.
- He was so obstinate that he moved south down the river in search of the first civilization. 
- At the end of the harvest, an obstinate boy tried to fire a shot.
far-reaching: adj. having a great influence or effect影响深远的
- The thief proved far-reaching, which put him out of business.
- His education in his youth was far-reaching, which enabled him to become a splendid peasant.
- The movement of sacrificing money for land was far-reaching.
assert: v. assert your rights/independence/superiority etc to state very strongly your right to something主张,声称
- The Catholic church grudged asserting the primacy of the monarchical position.
- As it is, the church asserted its supremacy over the secular authorities after having assumed political power.
- He asserted that someone in our village must have found his money.
primacy: n. formal if someone or something has primacy, they are the best or most important person or thing首位
- The church raised fundamental issues about the primacy of individuals.
- The primacy of what you should do is to keep in touch with your closest relatives.
- The primacy of work is to find the way to our hotel.
defy defiance: v.n. behaviour that shows you refuse to do what someone tells you to do, especially because you do not respect them ⇨ defy挑战,违抗
- The exalted claim of papal power resulted in the defiance of the monarchs.
- The defiance of the peasants failed to take control of the city.
- The victory of his election gave rise to a serious defiance of his enemies.
temporal: adj. related to practical instead of religious affairs世俗的
- A fraction of clergies are interested in temporal power.
- It is appropriate for the pope to pursue temporal power.
- Imagine his dismay when he found a friar turned out to be a temporal businessman.
doctrine: n. a set of beliefs that form an important part of a religion or system of ideas教条
- I'd rather regard the book as a series of doctrines than the manual of life.
- The fraction of monks dedicated their lives to a set of doctrines.
- The pope drew up a set of doctrines which was used to punish laymen.
Inquisition: the Inquisition a Roman Catholic organization in the past whose aim was to find and punish people who had unacceptable religious beliefs
- 
- 
- 
combat: v. to try to stop something bad from happening or getting worse – used especially in news reports防止,抑制
- The emergence of the cities in the high Middle Ages may have combated the decline of the monarchs.
- The nomads pushed their way westward through the plain, which combated the spread of the Black Death.
- The doctor confirms that the drug combats bad smells.
salvation: n. something that prevents or saves someone or something from danger, loss, or failure拯救, 救助
- His salvation inspired people the world over to raise money.
- The market in China turns out to be the salvation of the clothing company.
- This style of clothes became popular with young men and women in China, which turned out to be the salvation of the industry.
papacy: n. the papacy the position and authority of the Pope罗马教皇职位, 教皇的在位期间
- He was by no means the succession of the papacy.
- In his papacy, people enacted a special ritual to bury the dead.
- In his papacy, people were encouraged to bear more children.
parallel: v. if one thing parallels another, they happen at the same time or are similar, and seem to be related相应, 平行
- My arrivals always parallel your departures.
- His collapse of marriage parallelled the progress of his career.
- His winning lottery parallelled the job loss.
arise: v. if a problem or difficult situation arises, it begins to happen出现, 发生
- The monarchical power was believed to arise from the cities.
- He lost his life, which arose from his carelessness.
- The death of five workers arose from a mine accident.
shatter: v. to break suddenly into very small pieces, or to make something break in this way粉碎
- The shattered rock proved there was a truck.
- I must shatter the food so that the kitten can be fed.
- Shattered in the machine, he lost his life.
adherent: n. someone who supports a particular belief, plan, political party etc信徒
- A so-called adherent is always asking me for a meal once a day.
- The adherent ran out of water and food in the desert and began to lose his heart.
- As it is, the adherent got enough money to have the monastery repaired.
undergo: v. if you undergo a change, an unpleasant experience etc, it happens to you or is done to you经历, 遭受
- A fraction of lawyers underwent being kept in prison for a week.
- Even though the church underwent serious divisions, there were still many adherents.
- Your mother is undergoing an operation which will cost a lot of money.
division: n. the act of separating something into two or more different parts, or the way these parts are separated or shared分裂
- I and my wife are trying to figure out the divisions of labor between us.
- The divisions of labor between men and women contribute to our great society.
- The divisions of labor between those people arose from a new technology.
trigger: v. to make something happen very quickly, especially a series of events引发
- The steering wheel came away, which triggered two men's death.
- The curiosity of a stray dog triggered a car accident.
- The breakdown of trust in government triggered social upheaval.
--------------------
threaten sb's very life: 威胁某人的生命
- A group of hungry stray dogs threatened our very life.
- The plain was crushed in the forest and the cold threatened his very life.
- He kept in touch with a spy who was threatening his life.
be confronted with sth.: 面临某事
- I wish that I was not confronted with my ex-girlfriend at the reception.
- It is appropriate to be confronted with these difficulties. 
- In spite of being confronted with job loss, he asserted that he went on a vacation in Sanya.
ask to be done sth.: 要求被做某事
- I asked to be shown the evidence that proved me guilty. 
- He asked to be shown the food which the assistant accused him of stealing.
- He asked to be shown the money she had made. 
in error: 错误地
- He noticed with dismay that his answers were totally in error in the test.
- He noticed the boat moving in error. 
- Sir, you have sat in error in your father's seat.
on the basis of sth.: 在某事物的基础上
- He always publishes articles on the basis of facts and statistics.
- We should get a suitable salary on the basis of our work.
- You should have made remarks on the basis of the fact in public.
make sb's own position clear: 表明某人的立场
- It is appropriate to make your own position clear.
- Fearing of the responsibilities she needs to take, she never makes her own position clear in public.
- The general at last made his own position clear and defended the succession of the throne against his enemies.
by sb's negligence: 由于某人的疏忽
- My wife blamed me for the death of our kitten by my negligence.
- People would laugh at us at the reception if we didn't wear a suitable by your negligence.
- My superior blamed me for the bugs I made by my negligence.
proceed against sb.: 起诉某人
- As soon as my lawyer arrives on the scene, I will proceed against you.
- He lost heart and proceeded against his neighbor who took possession of his land.
- He blamed the broken vase on his neighbor and was going to proceed against him.
set the stage for sth.: 为某事准备舞台
- The accomplishments of the general set the stage for the great vampire.
- The flea-infested rats set the stage for the Black Death which erupted in Europe.
- The communications of these countries set the stage for the fusion of a great empire.
revive its fortunes: 恢复某事物的繁荣
- Following in his father's footsteps, he succeeded in reviving his family's fortunes.
- He devoted himself to reviving his family's fortunes.
- The marriage between him and the long-lost daughter of an upper class revived his family's fortunes.
** summary
Martin Luther was asked to answer charges of heresy
	before the emperor and prince of the Holy Roman Empire at the City of Worms.
Confronted with a piles of his books,
	he asked to be shown where any part was in error on the basis of Scripture and reason.
The emperor was outraged by his defenses
	and exclaimed that if the heresy and the very suspicion of heresy were to survive,
		he and the princes would be forever disgraced.
This was not the first chanllenge to the authority of the Catholic church,
	but its consequences was far more-reaching than anyone at Worms could have imagined.
	
Throughout the Middle Ages, the medieval Chritian church asserted its primacy of position
	and overcome the defiance of its temporal authority by emperors and kings
	and combated the challenges to its doctrines by the Inquistion and new religious orders.
By the end of the Middle Ages, however,
	the rising power of monarchical states had resulted in a loss of papal temporal authority.
Greater threat to papal authority and church unity arose in the sixteenth century
	when the unity of Christendom was shattered by the Reformation.
	
The movement begun by Martin Luther quickly spread across Europe.
Consequently,
	new religious practices, doctrines, and organizations were attracting adherets all over Europe.
The Roman Catholic Church underwent a reformation
	and managed to revive its fortunes by the mid-sixteenth century.
Nevertheless,
	the doctrinal divisions between Protestants and Catholics
		became instrumental in triggering a series of religious war.
** summary2
Martin Luther was asked to answer charges of heresy
	before the emperor and princes of the Holy Roman Empire at Worms.
Confronted with a pile of his books,
	he asked to be shown where any part was in error on the basis of Scripture and reason.
The emperor was outraged by his defenses
	and exclaimed that if the heresy and the very suspicion of heresy were to survive,
		he and the princes would be forever disgraced.
This was not the first challenge to the authority of the Catholic church,
	but its consequences were far more-reaching than anyone at Worms could have imagined.
	
Throughout the Middle Ages, the medieval Christian church asserted its primacy of position
	and overcame the defiance of its temporal authority and the challenges to its doctrines.
By the end of the Middle Ages, however,
	the rising power of monarchical states had resulted in a loss of papal temporal authority.
A greater threat to papal authority and church unity arose in the sixteenth century
	when the unity of Christendom was shattered by the Reformation.
	
The movement started by Martin Luther spread across Europe quickly.
Consequently,
	new religious practices, doctrines, and organizations were attracting adherents all over Europe.
The Roman Catholic Church underwent a reformation
	and managed to revive its fortunes by the mid-sixteenth century.
Nevertheless,
	the doctrinal divisions between Protestants and Catholics
		became instrumental in triggering a series of religious wars.
