* 14 The voyage of Magellan
While many Europeans were occupied with the problems of dynastic expansion and religious reform,
	others were taking voyages that propelled Europeans far beyond the medieval walls
		in which they had been enclosed for almost a thousand years.
One of these adventurers was the Portuguese explorer Ferdinand Magellan.
Convinced that he could find a sea passage to Asia through America,
	Magellan persuaded the king of Spain to finance an exploratory voyage.
On August 10, 1519,
	Magellan set sail on the Atlantic with five ships and a Spanish crew of 277 men.
After a stormy and difficult crossing of the ocean,
	Magellan’s fleet moved down the coast of South America,
		searching for the strait that would take him through.
His Spanish ship captains thought he was crazy:
	'The fool is obsessed with his search for a strait,' one remarked.
'On the flame of his ambition he will crucify us all.'
At last, in October 1520, he found it,
	passing through a narrow waterway (later named the Strait of Magellan)
	and emerging into an unknown ocean that he called the Pacific Sea.
Magellan reckoned that it would then be a short distance to the Spice Islands of the East,
	but he was badly mistaken.
Week after week, he and his crew sailed on across the Pacific as their food supplies dwindled.
According to one account,
	'When their last biscuit had gone,
		they scraped the maggots out of the casks, mashed them and served them as gruel.
They made cakes out of sawdust soaked with the urine of rats
	---the rats themselves, as delicacies, had long since been hunted to extinction.'
At last they reached the Philippines (named after King Philip II of Spain),
	where Magellan met his death at the hands of the natives.
Although only one of his original fleet of five ships survived and returned to Spain,
	Magellan is still remembered as the first person to circumnavigate the world.

At the beginning of the sixteenth century,
	European adventurers like Magellan
		had begun launching small fleets into the vast reaches of the Atlantic Ocean.
They were hardly aware that they were launching a new era,
	not only for Europe, but for the peoples of Asia, Africa, and the Americas as well.
Nevertheless, the voyages of these Europeans marked the beginning of a process
	that led to radical changes in the political, economic, and cultural life of the entire world.

Between 1500 and 1800, European power engulfed the globe.
In the Americas, Europeans established colonies that spread their laws, religions, and cultures.
In the island regions of Southeast Asia, Europeans firmly implanted their rule.
Elsewhere in Asia and in many parts of Africa,
	their trading activities dramatically affected the lifeways of the local peoples.
** expression
dynasty
dynastic [dɪ'næstɪk]: a family of kings or other rulers whose parents, grandparents etc have ruled the country for many years朝代, 王朝
propel [prəˈpel]: to move, drive, or push something forward ⇨ propulsion推进, 驱使
adventure
adventurer [ədˈventʃərər]: an exciting experience in which dangerous or unusual things happen冒险
passage ['pæsɪdʒ]: a way through something通道, 通路
finance [fɪˈnæns]: to provide money, especially a lot of money, to pay for something SYN fund供给...经费, 负担经费
exploratory [ɪkˈsplɔrəˌtɔri]: done in order to find out more about something探险的, 探测的
stormy [ˈstɔrmi]: with strong winds, heavy rain, and dark clouds暴风雨的
strait [streɪt]: a narrow passage of water between two areas of land, usually connecting two seas海峡
crucify [ˈkrusɪˌfaɪ]: to kill someone by fastening them to a cross十字架上钉死
waterway [ˈwɔtərˌweɪ]: a river or ↑canal that boats travel on水路
spice [spaɪs]: a type of powder or seed, taken from plants, that you put into food you are cooking to give it a special taste ⇨ spicy香料, 调味品
dwindle [ˈdwɪnd(ə)l]: to gradually become less and less or smaller and smaller缩小
scrape [skreɪp]: to remove something from a surface using the edge of a knife, a stick etc刮, 擦
maggot [ˈmæɡət]: a small creature like a ↑worm that is the young form of a ↑fly and lives in decaying food, flesh etc蛆
cask [kæsk]: a round wooden container used for storing wine or other liquids, or the amount of liquid that it contains SYN barrel桶, 木桶
mash [mæʃ]: to crush something, especially a food that has been cooked, until it is soft and smooth捣碎
gruel [ɡrul]: a food made of ↑oats cooked in water or milk, which poor people ate in the past稀粥
sawdust [ˈsɔˌdʌst]: very small pieces of wood that are left when you have been cutting wood锯屑
urine [ˈjʊrɪn]: the yellow liquid waste that comes out of the body from the ↑bladder尿
extinction [ɪkˈstɪŋkʃ(ə)n]: when a particular type of animal or plant stops existing消失
circumnavigate [ˌsɜrkəmˈnævɪˌɡeɪt]: to sail, fly, or travel completely around the Earth, an island etc环航
engulf [ɪnˈɡʌlf]: to completely surround or cover something吞没,完全包围
implant [ˈɪmˌplænt]: to strongly fix an idea, feeling, attitude etc in someone’s mind or character灌输
elsewhere [ˈelsˌhwer]: in, at, or to another place在别处
affect [əˈfekt]: to do something that produces an effect or change in something or in someone’s situati影响
--------------------
be occupied with sth.: 忙于做某事
set sail: 起航
be obsessed with sth.: 沉迷于某事
On the flame of sb's ambition: 在某人野心的火焰上
emerge into sth.: 浮现某物
sb. reckoned that + ...: 某人认为...
Week after week: 连续多周
be soaked with sth.: 被某物浸湿
at the hands of sb.: 在某人手上
Nevertheless, +...: 然而, ...
