#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 16 The trial of Galileo
#+begin_verse
In addition to political, economic, and social crises,
	the seventeenth century witnessed an intellectual one.
The Scientific Revolution questioned and ultimately challenged conceptions and beliefs
		about the nature of the external world and reality
	that had crystallized into a rather strict orthodoxy by the Later Middle Ages.
Derived from the works of ancient Greeks and Romans and grounded in Christian thought,
	the medieval worldview had become almost overpowering.
But the breakdown of Christian unity during the Reformation and the subsequent religious wars
	had created an environment
		in which Europeans became more comfortable with
			challenging both the ecclesiastical and political powers that be.
Should it surprise us that a challenge to intellectual authority soon followed?

The Scientific Revolution taught Europeans to view the universe and their place in it in a new way.
The shift from an earthcentered to a sun-centered cosmos
	had an emotional as well as intellectual effect on those who understood it.
Thus the Scientific Revolution, popularized in the eighteenth-century Enlightenment,
	stands as the major force in the transition to the largely secular, rational,
		and materialistic perspective that has defined the modern Western mentality in modern times.

The transition to a new worldview was far from easy, however.
In the seventeenth century,
	the Italian scientist Galileo Galilei, an outspoken advocate of the new worldview,
		found his ideas strongly opposed by the authorities of the Roman Catholic Church.
Galileo's position was clear:
	'I hold the sun to be situated motionless in the center of the revolution of the celestial bodies,
	while the earth rotates on its axis and revolves about the sun.'
Moreover, 'nothing physical that sense-experience sets before our eyes
	ought to be called in question (much less condemned) upon the testimony of biblical passages.'
But the church had a different view,
	and in 1633, Galileo, now sixty-eight and in ill health,
		was called before the dreaded Inquisition in Rome.
He was kept waiting for two months before he was tried and found guilty of heresy and disobedience.
Completely shattered by the experience, he denounced his errors:
	'With a sincere heart and unfeigned faith
		I curse and detest the said errors and heresies contrary to the Holy Church.'
Legend holds that when he left the trial rooms, Galileo muttered to himself:
	'And yet it does move!'
In any case, Galileo had been silenced,
	but his writings remained, and they began to circulate through Europe.
The actions of the Inquisition
	had failed to stop the spread of the new ideas of the Scientific Revolution.

In one sense, the Scientific Revolution was not a revolution.
It was not characterized by the explosive change and rapid overthrow of traditional authority
	that we normally associate with the word revolution.
The Scientific Revolution did overturn centuries of authority,
	but only in a gradual and piecemeal fashion.
Nevertheless, its results were truly revolutionary.
The Scientific Revolution
	was a key factor in setting Western civilization on its modern secular and material path.
#+end_verse
** expression
orthodoxy [ˈɔrθəˌdɑksi]: n. an idea or set of ideas that is accepted by most people to be correct and right正统
worldview [PDF]: n. someone’s opinions and attitudes relating to the world and things in general世界观
cosmos ['kɒzmɒs]: n. the cosmos the whole universe, especially when you think of it as a system ⇨ cosmic宇宙
popularize [ˈpɑpjələˌraɪz]: v. to make something well known and liked普及
materialistic [məˌtɪriəˈlɪstɪk]: adj. concerned only with money and possessions rather than things of the mind such as art, religion, or moral beliefs – used in order to show disapproval唯物论的
mentality [menˈtæləti]: n. a particular attitude or way of thinking, especially one that you think is wrong or stupid智力, 精神, 心理, 思想情况
outspoken [aʊtˈspoʊkən]: adj. expressing your opinions honestly and directly, even when doing this might annoy some people OPP reticent坦率直言的
advocate [ˈædvəkət]: v. to publicly support a particular way of doing something提倡, 鼓吹
motionless [ˈmoʊʃ(ə)nləs]: adj. not moving at all SYN still不动的, 静止的
celestial [səˈlestʃəl]: adj. relating to the sky or heaven天上的
sense-experience: n. 感官体验
testimony [ˈtestəˌmoʊni]: n. a formal statement saying that something is true, especially one a ↑witness makes in a court of law证词,宣言, 陈述
biblical [ˈbɪblɪk(ə)l]: adj. relating to or written in the Bible圣经的
passage ['pæsɪdʒ]: n. a short part of a book, poem, speech, piece of music etc(一)段, (一)节
disobedient [ˌdɪsəˈbidiənt] disobedience: adj.n. deliberately not doing what you are told to do by your parents, teacher, etc OPP obedient不服从的
denounce [dɪˈnaʊns]: v. to express strong disapproval of someone or something, especially in public ⇨ denunciation公开指责, 公然抨击
sincere [sɪnˈsɪr]: adj. someone who is sincere is honest and says what they really feel or believe OPP insincere诚挚的, 真诚的
unfeigned [ʌnˈfeɪnd]: adj. 真实的
curse [kɜrs]: v. a word or sentence used to ask God or a magical power to do something bad to someone or something诅咒, 咒骂
detest [dɪˈtest]: v. to hate something or someone very much厌恶, 憎恨
mutter [ˈmʌtər]: v. to speak in a low voice, especially because you are annoyed about something, or you do not want people to hear you嘀咕
circulate [ˈsɜrkjəˌleɪt]: v. if information, facts, ideas etc circulate, they become known by many people流通,传播
overturn [ˌoʊvərˈtɜrn]: v. to suddenly remove a government from power, especially by using violence SYN overthrow颠覆
--------------------
crystallize into sth.: 结晶成某物
be grounded in sth.: 建立在某物上
become comfortable with doing sth.: 变得适应做某事
stand as sth.: 作为某物的存在
be far from easy: 远不容易
find A opposed by B: 发现A被B反对
be situated sw.: 位于...
hold sth. to be + ...: 认为某物是...
rotate on its axis: 绕轴旋转
revolve about the sun: 绕太阳转
be called in question (upon sth.): 根据某事...被传唤质疑
in ill health: 身体不好
in one sense: 从某种意义来说

** sentence
orthodoxy [ˈɔrθəˌdɑksi]: n. an idea or set of ideas that is accepted by most people to be correct and right正统
- The course Mr. Leo taught us is challenging the educational orthodoxy in China.
- His teaching method was in the face of the educational orthodoxy of his time.
- The educational orthodoxy proved efficient, for a great number of peasant became well-educated.
worldview [PDF]: n. someone’s opinions and attitudes relating to the world and things in general世界观
- By the end of the sixteenth century, the decline of religious passions paralleled the changes of people's worldview.
- At last, he decided to defend his worldview against the religous orthodoxy of his time.
- Finding his worldview heretic, the knight of the Inquisition knocked him to the ground with a sharp blow.
cosmos ['kɒzmɒs]: n. the cosmos the whole universe, especially when you think of it as a system ⇨ cosmic宇宙
- It turns out to be an abduction by strange creatures in the cosmos.
- The shuttle in the cosmos runs smoothly.
- The philosopher tends to depict the cosmos as a titanic sphere.
popularize [ˈpɑpjələˌraɪz]: v. to make something well known and liked普及
- Popularized in all parts of China, many dialects are gradually disappearing.
- As the sexual knowledge is being popularize, the rate of pregnancy of teenagers in China drops a great deal.
- With the invention of lights popularized, people get used to staying overnight.
materialistic [məˌtɪriəˈlɪstɪk]: adj. concerned only with money and possessions rather than things of the mind such as art, religion, or moral beliefs – used in order to show disapproval唯物论的
- I was so materialistic that I didn't believe in a word in the Bible. 
- The results of experiments agreed with his materialistic theory.
- Accepting his materialistic theory, my religious passion began to decline.
mentality [menˈtæləti]: n. a particular attitude or way of thinking, especially one that you think is wrong or stupid智力, 精神, 心理, 思想情况
- I can't figure out the mentality of passers-by who spotted a girl lying on the ground and did nothing.
- You might as well spy on the mentality of your daughter.
- The mentality of these scientists who are confined in cow sheds full of the smell of urine got worse.
outspoken [aʊtˈspoʊkən]: adj. expressing your opinions honestly and directly, even when doing this might annoy some people OPP reticent坦率直言的
- He is outspoken so that he can always make close friends.
- He was so outspoken that in pulic he pointed out the bugs his superior made.
- He is so outsopken that everyone admires for his sense of sincere.
advocate [ˈædvəkət]: v. to publicly support a particular way of doing something提倡, 鼓吹
- The guy who advocates violence never though that he would be killed in action.
- He always advocates wars in strictly secular terms.
- He saluted towards the general who advocates violence.
motionless [ˈmoʊʃ(ə)nləs]: adj. not moving at all SYN still不动的, 静止的
- The stupid guy stood motionless before I knocked him to the ground.
- If you had stood moitionless at the stage for two minutes, I would pay for your dinner.
- When he saw a man lying motionless on the ground, he stamped out the letter 'SOS'.
celestial [səˈlestʃəl]: adj. relating to the sky or heaven天上的
- The strange celestial events led to masses' breakdown of trust in the monarch in China.
- People in the square witnessed the strange celestial event and stood to attention.
- At the entrance of the cave the celestial event could be observed by a pair of binoculars.
sense-experience: n. 感官体验
- 
- 
- 
testimony [ˈtestəˌmoʊni]: n. a formal statement saying that something is true, especially one a ↑witness makes in a court of law证词,宣言, 陈述
- It became apparent that the writer refused to give testimony in the court.
- His boss threatens to kill his all family if he gives testimony in the court.
- The testimony he gives in the court is at your stake.
biblical [ˈbɪblɪk(ə)l]: adj. relating to or written in the Bible圣经的
- 
- 
- 
passage ['pæsɪdʒ]: n. a short part of a book, poem, speech, piece of music etc(一)段, (一)节
- He discovered that his daughter read out the passage of his book in the class.
- A passage of the Bible was carved in the pedestal of the statue.
- Mr. Leo instructed us to recite the passage of his book.
disobedient [ˌdɪsəˈbidiənt] disobedience: adj.n. deliberately not doing what you are told to do by your parents, teacher, etc OPP obedient不服从的
- My grandfather used to condemn me as a disobedient child.
- The disobedient solider was kept in hiding in the prison.
- Because of lack of foods and money, the disobedient people gathered around in the City Hall and asked to talk to the officer.
denounce [dɪˈnaʊns]: v. to express strong disapproval of someone or something, especially in public ⇨ denunciation公开指责, 公然抨击,告发
- Yearning to get a large sum of money, he denounced his wife to the authorities.
- The teacher denounced the student as a thief who crept into his house.
- Her sister denounced her as a shoplifer who stole a diamond ring as a present.
sincere [sɪnˈsɪr]: adj. someone who is sincere is honest and says what they really feel or believe OPP insincere诚挚的, 真诚的
- His sincere attitude caused him to get a good salary.
- He always admires for his friends' sincere attitude on the surface.
- People tends to admire for your sincere attitude on the surface and then sell you out.
unfeigned [ʌnˈfeɪnd]: adj. 真实的
- He broke the world record with unfeigned pleasure.
- He accepted sharp criticisms in public with unfeigned pleasure.
- I like the food you cook with unfeigned pleasure.
curse [kɜrs]: v. a word or sentence used to ask God or a magical power to do something bad to someone or something诅咒, 咒骂
- Finding his toy taken to pieces, he was cursing day and night.
- The captain ships cursed him: On his flame of ambition, he would crucify us all.
- I told him a story about the cursed crew on an unsinkable colossal ship.
detest [dɪˈtest]: v. to hate something or someone very much厌恶, 憎恨
- Because of his vanity, he detest all independence of character and sentiment in others.
- He knocked the officer to the ground, for he dester him for a long time.
- No one can account for the fact that the officer people detest won the election.
mutter [ˈmʌtər]: v. to speak in a low voice, especially because you are annoyed about something, or you do not want people to hear you嘀咕
- Fearing that they would be arrested by the local authorities, people muttered about the domestic inflation.
- I have already completed my work, I muttered to myself.
- He deserved it, the girl muttered to herself.
circulate [ˈsɜrkjəˌleɪt]: v. if information, facts, ideas etc circulate, they become known by many people流通,传播
- The contents of the petition have circulated through these merchants.
- As the gunpowder circulated in Europe, the castle was no long regarded as safety.
- As the Black Death circulated in Europe, many people thought the end of the world was at hand.
overturn [ˌoʊvərˈtɜrn]: v. to suddenly remove a government from power, especially by using violence SYN overthrow颠覆
- The crusade sacked the city and overturned the Byzantine empire.
- The rebellions and revolts from peasant at last overturned the local authorities.
- The spread of scientific knowledge insidiously overturned the secular power of the Christianity.
--------------------
crystallize into sth.: 结晶成某物
- The substances flowing with the river crystallized into a strange rock.
- The liquid crystallized into a special type of food which is popular with Chinese.
- Crystallizing into a fossil is millions of year in the making.
be grounded in sth.: 建立在某物上
- His imposing majesty turned out to be grounded in the power of regulating the armies.
- His confidence is grounded in the statue he sculptured for the U.S.
- The statue is grounded in the mental framework which is built by a famous architect, Effel.
become comfortable with doing sth.: 变得适应做某事
- Week after week, he became comfortable with cooking meth.
- After a great number of exercises, he became comfortable with speaking in public.
- The entrepreneur became comfortable with setting up factories in suburbs of the city.
stand as sth.: 作为某物的存在
- The girl who used to quarrel bitterly in pubic stands as an successful entrepreneur.
- He stood as an officer at the representative assembly.
- He stands as a hard-working husband in the family.
be far from easy: 远不容易
- Feeding a disobedient cat is far from easy.
- Babysitting twins is far from easy, don't be too hard on me.
- As he has just been nominated for the prize, staying out of limelight is far from easy.
find A opposed by B: 发现A被B反对
- He found his theory opposed by his beloved family.
- He became comfortable with finding his treatise opposed by his instructor.
- Finding his observation opposed by the pope, he denounced it as bullshit.
be situated sw.: 位于...
- I yearned to have a house situated on the top of a mountain.
- The hotel situated on the bottom of the mountain is very convenient.
- The statue used to be situated at the entrance of the harbour was transported to the City Hall.
hold sth. to be + ...: 认为某物是...
- He held the thief to be a local butcher.
- Your wife tends to hold the prize to her gift.
- I hold the answer to be A, which proved right.
rotate on its axis: 绕轴旋转
- The balls rotating on their axis repelled each other.
- The spheres which were rotating on their axis have been magnetized to attract each other.
- It became apparent that the earth is rotating on its axis.
revolve about the sun: 绕太阳转
- Desiring to get snacks, my cat is revolving about the chair.
- The earth is revolving about the sun.
- The earth must be revolving about the sun.
be called in question (upon sth.): 根据某事...被传唤质疑
- The driver was said to be called in question upon the rule of traffic.
- As the frist man arriving on the scene, he was called in question.
- Suspected that he was the shoplifter, he was called in question.
in ill health: 身体不好
- My father was in ill health, when he got fired.
- My cat has been in ill health, after he was fed by a stranger.
- I am in ill health, so I'm not at work today.
in one sense: 从某种意义来说
- In one sense, the prizefighter was a great boxer.
- In one sense, he was killed in action.
- In one sense, he is the father of immunology.
** sentence2
orthodoxy [ˈɔrθəˌdɑksi]: n. an idea or set of ideas that is accepted by most people to be correct and right正统
- In one sense, the course Mr. Leo taught us is challenging the educational orthodoxy in China.
- His teaching method was in the face of the educational orthodoxy of his time.
- The educational orthodoxy proved efficient, for a great number of peasants became well-educated.
worldview [PDF]: n. someone’s opinions and attitudes relating to the world and things in general世界观
- By the end of the sixteenth century, the decline of religious passions paralleled the changes in people's worldview.
- At last, he decided to defend his worldview against the religious orthodoxy of his time.
- Finding his worldview heretic, the knight of the Inquisition knocked him to the ground with a sharp blow.
cosmos ['kɒzmɒs]: n. the cosmos the whole universe, especially when you think of it as a system ⇨ cosmic宇宙
- It turns out to be an abduction by strange creatures in the cosmos.
- The shuttle in the cosmos runs smoothly.
- The philosopher tends to depict the cosmos as a titanic sphere.
popularize [ˈpɑpjələˌraɪz]: v. to make something well known and liked普及
- Popularized in all parts of China, many dialects are gradually disappearing.
- As sexual knowledge is being popularized, the rate of pregnancy among teenagers in China drops a great deal.
- With the invention of lights popularized, people got used to staying overnight.
materialistic [məˌtɪriəˈlɪstɪk]: adj. concerned only with money and possessions rather than things of the mind such as art, religion, or moral beliefs – used in order to show disapproval唯物论的
- I was so materialistic that I didn't believe in a word in the Bible. 
- The results of experiments agreed with his materialistic theory.
- Accepting his materialistic theory, my religious passion began to decline.
mentality [menˈtæləti]: n. a particular attitude or way of thinking, especially one that you think is wrong or stupid智力, 精神, 心理, 思想情况
- I can't figure out the mentality of passers-by who spotted a girl lying on the ground and did nothing.
- You might as well spy on the mentality of your daughter.
- The mentality of these scientists who are confined in cow sheds full of the smell of urine got worse.
outspoken [aʊtˈspoʊkən]: adj. expressing your opinions honestly and directly, even when doing this might annoy some people OPP reticent坦率直言的
- He is outspoken so he can always make close friends.
- He was so outspoken that in public he pointed out the bugs his superior made.
- He is so outspoken that everyone admires him for his sense of sincerity.
advocate [ˈædvəkət]: v. to publicly support a particular way of doing something提倡, 鼓吹
- The guy who advocates violence never thought that he would be killed in action.
- He always advocates wars in strictly secular terms.
- He saluted towards the general who advocates violence.
motionless [ˈmoʊʃ(ə)nləs]: adj. not moving at all SYN still不动的, 静止的
- The stupid guy stood motionless before I knocked him to the ground.
- If you had stood motionless at the stage for two minutes, I would pay for your dinner.
- When he saw a man lying motionless on the ground, he stamped out the letter 'SOS'.
celestial [səˈlestʃəl]: adj. relating to the sky or heaven天上的
- The strange celestial events led to the masses' breakdown of trust in the monarch in China.
- People in the square witnessed the strange celestial event and stood to attention.
- At the entrance of the cave the celestial event could be observed by a pair of binoculars.
sense-experience: n. 感官体验
- 
- 
- 
testimony [ˈtestəˌmoʊni]: n. a formal statement saying that something is true, especially one a ↑witness makes in a court of law证词,宣言, 陈述
- It became apparent that the writer refused to give testimony in court.
- His boss threatens to kill his all family if he gives testimony in court.
- The testimony he gives in court is at your stake.
biblical [ˈbɪblɪk(ə)l]: adj. relating to or written in the Bible圣经的
- 
- 
- 
passage ['pæsɪdʒ]: n. a short part of a book, poem, speech, piece of music etc(一)段, (一)节
- He discovered that his daughter read out the passage of his book in the class.
- A passage from the Bible was carved on the pedestal of the statue.
- Mr. Leo instructed us to recite the passage of his book.
disobedient [ˌdɪsəˈbidiənt] disobedience: adj.n. deliberately not doing what you are told to do by your parents, teacher, etc OPP obedient不服从的
- My grandfather used to condemn me as a disobedient child.
- The disobedient soldier was kept in hiding in the prison.
- Because of the lack of food and money, the disobedient people gathered around in the City Hall and asked to talk to the officer.
denounce [dɪˈnaʊns]: v. to express strong disapproval of someone or something, especially in public ⇨ denunciation公开指责, 公然抨击,告发
- Yearning to get a large sum of money, he denounced his wife to the authorities.
- The teacher denounced the student as a thief who crept into his house.
- Her sister denounced her as a shoplifter who stole a diamond ring as a present.
sincere [sɪnˈsɪr]: adj. someone who is sincere is honest and says what they really feel or believe OPP insincere诚挚的, 真诚的
- His sincere attitude caused him to get a good salary.
- He always appreciates his friends' sincerity on the surface.
- People tend to appreciate your sincere attitude on the surface and then sell you out.
unfeigned [ʌnˈfeɪnd]: adj. 真实的
- He broke the world record with unfeigned pleasure.
- He accepted sharp criticisms in public with unfeigned pleasure.
- I like the food you cook with unfeigned pleasure.
curse [kɜrs]: v. a word or sentence used to ask God or a magical power to do something bad to someone or something诅咒, 咒骂
- Finding his toy taken to pieces, he was cursing day and night.
- The captain ships cursed him: On his flame of ambition, he would crucify us all.
- I told him a story about the cursed crew on an unsinkable colossal ship.
detest [dɪˈtest]: v. to hate something or someone very much厌恶, 憎恨
- Because of his vanity, he detests all independence of character and sentiment in others.
- He knocked the officer to the ground, for he detested him for a long time.
- No one can account for the fact that the officer people detest won the election.
mutter [ˈmʌtər]: v. to speak in a low voice, especially because you are annoyed about something, or you do not want people to hear you嘀咕
- Fearing that they would be arrested by the local authorities, people muttered about the domestic inflation.
- I have already completed my work, I muttered to myself.
- He deserved it, the girl muttered to herself.
circulate [ˈsɜrkjəˌleɪt]: v. if information, facts, ideas etc circulate, they become known by many people流通,传播
- The contents of the petition have circulated through these merchants.
- As the gunpowder circulated in Europe, the castle was no longer regarded as safe.
- As the Black Death circulated in Europe, many people thought the end of the world was at hand.
overturn [ˌoʊvərˈtɜrn]: v. to suddenly remove a government from power, especially by using violence SYN overthrow颠覆
- The crusade sacked the city and overturned the Byzantine empire.
- The rebellions and revolts from peasants at last overturned the local authorities.
- The spread of scientific knowledge insidiously overturned the secular power of Christianity.
--------------------
crystallize into sth.: 结晶成某物
- The substances flowing with the river crystallized into a strange rock.
- The liquid crystallized into a special type of food which is popular with the Chinese.
- Crystallizing into a fossil is millions of years in the making.
be grounded in sth.: 建立在某物上
- His imposing majesty turned out to be grounded in the power of regulating the armies.
- His confidence is grounded in the statue he sculptured for the U.S.
- The statue is grounded in the mental framework which is built by a famous architect, Effel.
become comfortable with doing sth.: 变得适应做某事
- Week after week, he became comfortable with cooking meth.
- After a great number of exercises, he became comfortable with speaking in public.
- The entrepreneur became comfortable with setting up factories in the suburbs of the city.
stand as sth.: 作为某物的存在
- The girl who used to quarrel bitterly in public stands as a successful entrepreneur.
- He stood as an officer at the representative assembly.
- He stands as a hard-working husband in the family.
be far from easy: 远不容易
- Feeding a disobedient cat is far from easy.
- Babysitting twins is far from easy, don't be too hard on me.
- As he has just been nominated for the prize, staying out of the limelight is far from easy.
find A opposed by B: 发现A被B反对
- He found his theory opposed by his beloved family.
- He became comfortable with finding his treatise opposed by his instructor.
- Finding his observation opposed by the pope, he denounced it as bullshit.
be situated sw.: 位于...
- I yearned to have a house situated on the top of a mountain.
- The hotel situated at the bottom of the mountain is very convenient.
- The statue used to be situated at the entrance of the harbor and was transported to the City Hall.
hold sth. to be + ...: 认为某物是...
- He held the thief to be a local butcher.
- Your wife tends to hold the prize to her gift.
- I hold the answer to be A, which proved right.
rotate on its axis: 绕轴旋转
- The balls rotating on their axis repelled each other.
- The spheres which were rotating on their axis have been magnetized to attract each other.
- It became apparent that the earth is rotating on its axis.
revolve about the sun: 绕太阳转
- Desiring to get snacks, my cat is revolving about the chair.
- The earth revolves about the sun.
- The earth must be revolving about the sun.
be called in question (upon sth.): 根据某事...被传唤质疑
- The driver was said to be called in question upon the rule of traffic.
- As the first man arriving on the scene, he was called in question.
- Suspected that he was the shoplifter, he was called in question.
in ill health: 身体不好
- My father was in ill health when he got fired.
- My cat has been in ill health after he was fed by a stranger.
- I am in ill health, so I'm not at work today.
in one sense: 从某种意义来说
- In one sense, the prizefighter was a great boxer.
- In one sense, he was killed in action.
- In one sense, he is the father of immunology.
** summary
In the seventeenth century,
	the Scientific Revolution questioned and challenged the conceptions and beliefs
		about the external world and realities
	that had crystallized into a strict arthodoxy by the Later Middle Ages.
Though derived from ancient Greeks and Romans and grouded in Christian thought
		the worldview had become almost over-powering,
	the breakdown of Christian unity created an environment
		in which people got used to challenging the authorities.
The shift from earthcentered to sun-centered
	had an emotional as well as intellectual effect on those who understood it.
Therefore, the Scientific Revolution stood as a major force
	in the transition to a largely secular, rational, materialistic perspective
		that has defined the modern Western mentality.
In the seventeenth century, Gelileo held the sun to be situated motionless
	in the center of the revolution of the celestial bodies.
But the church had a different view
	and Gelileo was called before the dreaded Inquisition before he was kept waiting for two months.
Shattered by the experience, Geolileo denounced his errors and kept silenced ever since.
However, his writings began to circulate through Europe,
	so the actions of Equisition failed to stop the spread of new ideas.
In one sense, the Scientific Revolution was not a revolution,
	for it did overturn centuries of authorities, but in a gradual and piecemeal fashion.
** summary2
In the seventeenth century,
	the Scientific Revolution questioned and challenged the conceptions and beliefs
		about the external world and realities
	that had crystallized into a strict orthodoxy by the Later Middle Ages.
Though derived from ancient Greeks and Romans and grounded in Christian thought
		the worldview had become almost over-powering,
	the breakdown of Christian unity created an environment
		in which people got used to challenging the authorities.
The shift from earth-centered to sun-centered
	had an emotional as well as intellectual effect on those who understood it.
Therefore, the Scientific Revolution stood as a major force
	in the transition to a largely secular, rational, materialistic perspective
		that has defined the modern Western mentality.
In the seventeenth century, Galileo held the sun to be situated motionless
	in the center of the revolution of the celestial bodies.
But the church had a different view
	and Galileo was called before the dreaded Inquisition before he was kept waiting for two months.
Shattered by the experience, Geolileo denounced his errors and remained silent.
However, his writings began to circulate through Europe,
	so the actions of the Inquisition failed to stop the spread of new ideas.
In one sense, the Scientific Revolution was not a revolution,
	for it did overturn centuries of authorities, but in a gradual and piecemeal fashion.
