#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 17 The Parisian salon of Madame Geoffrin
#+begin_verse
The earth-shattering work of the natural philosophers in the Scientific Revolution
	had affected only a relatively small number of Europe's educated elite.
In the eighteenth century, this changed dramatically
	as a group of intellectuals known as the philosophes
		popularized the ideas of the Scientific Revolution
		and used them to undertake a dramatic examination of all aspects of life.
In Paris, the cultural capital of Europe,
	women took the lead
		in bringing together groups of men and women to discuss the new ideas of the philosophes.
At her fashionable home in the Rue SaintHonore,
	Marie-Therese de Geoffrin, the wife of a wealthy merchant,
		held sway over gatherings that became the talk of France and even Europe.
Distinguished foreigners, including a future king of Sweden and a future king of Poland,
	competed to receive invitations.
When Madame Geoffrin made a visit to Vienna, she was so well received that she exclaimed,
	'I am better known here than a couple of yards from my own house!'
Madame Geoffrin was an amiable but firm hostess
	who allowed wide-ranging discussions as long as they remained in good taste.
When she found that artists and philosophers did not mix particularly well
	(the artists were high-strung and the philosophers talked too much),
	she set up separate meetings: artists were invited on Mondays, philosophers on Wednesdays.
These gatherings were but one of many avenues for the spread of the ideas of the philosophes.
And those ideas had such a widespread impact on their society
	that historians ever since have called the eighteenth century the Age of Enlightenment.

For most of the philosophes, enlightenment included the rejection of traditional Christianity.
The religious wars and intolerance of the sixteenth and seventeenth centuries
	had left intellectuals so disgusted with religious fanaticism
		that they were open to the new ideas of the Scientific Revolution.
Whereas the great scientists of the seventeenth century believed that their work exalted God,
	the intellectuals of the eighteenth century read the same conclusions a different way
		and increasingly turned their backs on Christian orthodoxy.
Consequently, European intellectual life in the eighteenth century
	was marked by the emergence of the secularization
		that has characterized the modern Western mentality ever since.
Ironically,
	at the same time that reason and materialism were beginning to replace faith and worship,
	a great outburst of religious sensibility manifested itself in music and art.
Clearly, the growing secularization of the eighteenth century
	had not yet captured the hearts and minds of all Europeans.
#+end_verse
** expression
earth-shattering [ˈʃætə(r)]: adj. surprising or shocking and very important惊天动地
philosophe: n. Generally. A philosopher, a thinker; a man of letters, an intellectual. Now rare.启蒙思想家
fashionable [ˈfæʃ(ə)nəb(ə)l]: adj. popular, especially for a short period of time OPP unfashionable流行的, 时髦的
gathering [ˈɡæð(ə)rɪŋ]: n. a meeting of a group of people聚会
distinguished [dɪˈstɪŋɡwɪʃt]: adj. successful, respected, and admired卓著的, 著名的, 高贵的
amiable [ˈeɪmiəb(ə)l]: adj. friendly and easy to like亲切的, 和蔼可亲的
firm [fɜrm]: adj. strongly fixed in position, and not likely to move SYN secure坚定的
high-strung [strʌŋ]: adj. 高度紧张的,容易兴奋的
widespread [ˈwaɪdˌspred]: adj. existing or happening in many places or situations, or among many people分布广泛的, 普遍的
reject [ˈriˌdʒekt] rejection: v.n. to refuse to accept, believe in, or agree with something OPP accept拒绝, 抵制
intolerant [ɪnˈtɑlərənt] intolerance: adj.n. not willing to accept ways of thinking and behaving that are different from your own OPP tolerant不宽容的
whereas [hwerˈæz]: conj. formal used to say that although something is true of one thing, it is not true of another尽管
sensibility [ˌsensəˈbɪləti]: n. the way that someone reacts to particular subjects or types of behaviour感情
manifest [ˈmænɪˌfest]: v. to show a feeling, attitude etc表现
--------------------
bring sb. to do sth.: 带领某人去做某事
hold sway (over sth./sb.): 支配某物/某人
the talk of sp.: 某地的话题
receive an invitation: 收到邀请
make a visit to sp.: 拜访某地
a couple of + ...: 两个/几个事物
in good taste: 得体的
ever since: 从那时起
be disgusted with sth.: 对某事物反感
be open to sth.: 对某事物开放
do sth. a different way: 用不同地方式做某事
turn sb's back on sth.: 背弃某物
Consequently, + ...: 因此, + ...
Ironically, + ...: 讽刺地, + ...
capture the heart of sb.: 捕获某人的心
** sentence
earth-shattering [ˈʃætə(r)]: adj. surprising or shocking and very important惊天动地
- The breakdown of trust in the authorities led to an earth-shattering event.
- The earth-shattering paint only exists in your fantasy world.
- The coverages of the earth-shattering event tend to be increasingly chaotic.
philosophe: n. Generally. A philosopher, a thinker; a man of letters, an intellectual. Now rare.启蒙思想家
- The philosophe born in Paris contributed to the establishment of the US.
- The philosophe is fanatical about smashing history books to pieces.
- The philosophe took these pieces together and restored the statue.
fashionable [ˈfæʃ(ə)nəb(ə)l]: adj. popular, especially for a short period of time OPP unfashionable流行的, 时髦的
- A great number of fashionable clothes have been stolen, which must be worth 10000 dollars.
- The clerk wrapped the fashionable dress as soon as she could and handed it to her boyfriend.
- It becomes fashionable to share your apartment with your cat these days.
gathering [ˈɡæð(ə)rɪŋ]: n. a meeting of a group of people聚会
- The expert from the gathering raised fundamental questions about our political sensibility.
- The lady is fanatical about setting up gatherings.
- You needn't have attended a gathering in which you didn't receive an invitation.
distinguished [dɪˈstɪŋɡwɪʃt]: adj. successful, respected, and admired卓著的, 著名的, 高贵的
- The invention of the machine which is used to search gold is grounded in the work of a distinguished scientist.
- Clearly, she is by no means a distinguished swimmer who can swim across the Channel on her own.
- Our distinguished headmaster will retire from teaching three months later.
amiable [ˈeɪmiəb(ə)l]: adj. friendly and easy to like亲切的, 和蔼可亲的
- The Prime Minister regarded as amiable lost his temper this time.
- The woman who looks amiable turned out to poison her five husbands in her youth.
- Imagine his dismay when he found his amiable aunt turned out to be a criminal.
firm [fɜrm]: adj. strongly fixed in position, and not likely to move SYN secure坚定的
- He realized to his horror that his fellow was a firm layman.
- He was so firm that even though he had been trapped in mine for two days, he didn't lose his heart.
- My wife's shift from a firm to a suspicious layman gave me satisfaction.
high-strung [strʌŋ]: adj. 高度紧张的,容易兴奋的
- I have to cooperate with such a high-strung colleague that I was not able to point out his errors sometimes.
- The high-strung painter exclaimed that the comission would be finished until it satisfied him as an artist.
- He was chanllenged by a high-strung knight who used to be defeated.
widespread [ˈwaɪdˌspred]: adj. existing or happening in many places or situations, or among many people分布广泛的, 普遍的
- The actions of the Inquisition failed to stop the widespread ideas of the Scientific Revolution.
- The widespread temples in the country were used as places of worship.
- The widespread chapel in Europe were used as sleeping places of refugees.
reject [ˈriˌdʒekt] rejection: v.n. to refuse to accept, believe in, or agree with something OPP accept拒绝, 抵制
- He rejected these invitations and claimed that he would never accept any commission.
- He rejected its offer, for he detests the harsher working condition in this office.
- He lost time in rejecting his brother's request, for he had been in China for three years.
intolerant [ɪnˈtɑlərənt] intolerance: adj.n. not willing to accept ways of thinking and behaving that are different from your own OPP tolerant不宽容的
- Intolerant of children who cheat on his test, he gave them bad grades.
- Intolerant of my carelessness, the examiner didn't let me pass the test.
- Intolerant of the independence charater in his wife, he made a spectacle of himself when he instructed his wife to throw away rubbish in public.
whereas [hwerˈæz]: conj. formal used to say that although something is true of one thing, it is not true of another尽管
- Whereas his clothes got into such mess, he was enthusiastic about taking part in the concert.
- Whereas the killer set your house on fire, he didn't fire a shot at you.
- Whereas he won the election, he decided to retire from political life.
sensibility [ˌsensəˈbɪləti]: n. the way that someone reacts to particular subjects or types of behaviour感情
- The house is equiped with the statue of Virgin Mary which inspired his religious sensibility.
- Not allowed to go to university, he devoted his sensibility to his work.
- My political sensibility could date back to my youth when I first read history of the world.
manifest [ˈmænɪˌfest]: v. to show a feeling, attitude etc表现
- I am always too eager to manifest myself in front of my superiors.
- When I want to manifest myself in public, I always make a spectacle of myself.
- His passions manifested as the painting on the ceiling of his apartment.
--------------------
bring sb. to do sth.: 带领某人去做某事
- In my childhood, my amiable uncle always brought us to swim in the river on Summer holidays.
- The amiable Prime Minister brought a gathering to set the Embassy on fire.
- My aimable as well as firm aunt brought me to go to school in town when I played truant from school in rural village.
hold sway (over sth./sb.): 支配某物/某人
- The firm philosophes was able to hold sway over the high-strung masses.
- Intolerant of disorder in his house, he began to hold sway over members of his family.
- The exalted claim of the papal authority held sway over the monarchs.
the talk of sp.: 某地的话题
- The breakdown of Christian unity through the Reformation and religious wars became the talk of Europe.
- The fantasy world which was depicted in his writings became the talk of Europe.
- The secert far-reached land where gold is everywhere became the talk of Europe.
receive an invitation: 收到邀请
- He claimed condescendingly that he had received the invitation of the monarch.
- If he had received an invitation, he would have been condescending.
- You're forbid to attend the party if you don't receive an invitation.
make a visit to sp.: 拜访某地
- Sir, you may as well make a visit to China where the masses is suffering from floods.
- The general made a visit to Tokyo which he conquered with his father in his youth.
- Elizabeth made a visit to Beijing where the agreement about the lands was made.
a couple of + ...: 两个/几个事物
- The butcher accussed me of freeing a couple of pigs from the cage.
- I denounced the errors that a couple of scientist made in their article. 
- There are a couple of apples on my desktop.
in good taste: 得体的
- Staying out of the limelight, they still behaved in good taste.
- My wife condemns me as a rude warrior who doesn't behave in good taste.
- If you were in good taste, you wouldn't change into such a tight dress at the party.
ever since: 从那时起
- Galileo was called in question before the Inquisition, and the ideas of Scientific Revolution have been implanted ever since.
- My aunt brought me to go to school in town, I have owned her a lot ever since.
- He has ever since fell into love with the amiable girl. 
be disgusted with sth.: 对某事物反感
- Disgusted with shopping online, he held sway over members of his family and urged them not to buy anything online.
- Disgusted with the spread of meth, he left the US where he has been for six years.
- Disgusted with the disvison, he didn't keep in touch with his wife any more.
be open to sth.: 对某事物开放
- The monk is open to the ideas from the outside world.
- The girl is open to the love of every boy she runs into.
- The president is open to the spread of these ideas divergent from main stream.
do sth. a different way: 用不同地方式做某事
- The Scientific Revolution did overturn centuries of authority a different way.
- The flight attendant claimed to have take charge of me a different way.
- The breakdown of trust in the government happened a different way.
turn sb's back on sth.: 背弃某物
- His wife turned her back on their marriage when she cheated on him.
- The townman realized to his horror that their country was turning its back on the outside world.
- The actions of the Inquisition turned its back on the new ideas of the Scientific Revolution.
Consequently, + ...: 因此, + ...
- Consequently, he succeeded in breaking world record because of these liquid foods.
- Consequently, I shared my apartment with this stary cat.
- Consequently, she got married to your dentist.
Ironically, + ...: 讽刺地, + ...
- Ironically, the husband risked his life to save her in floods.
- Ironically, a patch of green began to appear on the desert hill.
- Ironically, the people they regarded as barbarian devastated their civilization.
capture the heart of sb.: 捕获某人的心
- Cats in the market never fail to capture the heart of my wife.
- Failing to capture the heart of his wife, he decided to get divorce.
- This clumsy kind of animal captures the heart of my wife in the exhibition.
** sentence2
earth-shattering [ˈʃætə(r)]: adj. surprising or shocking and very important惊天动地
- The breakdown of trust in the authorities led to an earth-shattering event.
- The earth-shattering paint only exists in your fantasy world.
- The coverages of the earth-shattering event tend to be increasingly chaotic.
philosophe: n. Generally. A philosopher, a thinker; a man of letters, an intellectual. Now rare.启蒙思想家
- The philosophe born in Paris contributed to the establishment of the US.
- The philosophe is fanatical about smashing history books to pieces.
- The philosophe took these pieces together and restored the statue.
fashionable [ˈfæʃ(ə)nəb(ə)l]: adj. popular, especially for a short period of time OPP unfashionable流行的, 时髦的
- A great number of fashionable clothes have been stolen, which must be worth 10000 dollars.
- The clerk wrapped the fashionable dress as soon as she could and handed it to her boyfriend.
- It has become fashionable to share your apartment with your cat these days.
gathering [ˈɡæð(ə)rɪŋ]: n. a meeting of a group of people聚会
- The expert from the gathering raised fundamental questions about our political sensibility.
- The lady is fanatical about setting up gatherings.
- You needn't have attended a gathering in which you didn't receive an invitation.
distinguished [dɪˈstɪŋɡwɪʃt]: adj. successful, respected, and admired卓著的, 著名的, 高贵的
- The invention of the machine which is used to search gold is grounded in the work of a distinguished scientist.
- Clearly, she is by no means a distinguished swimmer who can swim across the Channel on her own.
- Our distinguished headmaster will retire from teaching three months later.
amiable [ˈeɪmiəb(ə)l]: adj. friendly and easy to like亲切的, 和蔼可亲的
- The Prime Minister regarded as amiable lost his temper this time.
- The woman who looks amiable turned out to poison her five husbands in her youth.
- Imagine his dismay when he found his amiable aunt turned out to be a criminal.
firm [fɜrm]: adj. strongly fixed in position, and not likely to move SYN secure坚定的
- He realized to his horror that his fellow was a firm layman.
- He was so firm that even though he had been trapped in mine for two days, he didn't lose his heart.
- My wife's shift from a firm to a suspicious layman gave me satisfaction.
high-strung [strʌŋ]: adj. 高度紧张的,容易兴奋的
- I have to cooperate with such a high-strung colleague that I am not able to point out his errors sometimes.
- The high-strung painter exclaimed that the commission would be finished until it satisfied him as an artist.
- He was challenged by a high-strung knight who used to be defeated.
widespread [ˈwaɪdˌspred]: adj. existing or happening in many places or situations, or among many people分布广泛的, 普遍的
- The actions of the Inquisition failed to stop the widespread ideas of the Scientific Revolution.
- The widespread temples in the country were used as places of worship.
- The widespread chapels in Europe were used as sleeping places for refugees.
reject [ˈriˌdʒekt] rejection: v.n. to refuse to accept, believe in, or agree with something OPP accept拒绝, 抵制
- He rejected these invitations and claimed that he would never accept any commission.
- He rejected its offer, for he detests the harsher working conditions in this office.
- He lost time in rejecting his brother's request, for he had been in China for three years.
intolerant [ɪnˈtɑlərənt] intolerance: adj.n. not willing to accept ways of thinking and behaving that are different from your own OPP tolerant不宽容的
- Intolerant of children who cheat on his test, he gave them bad grades.
- Intolerant of my carelessness, the examiner didn't let me pass the test.
- Intolerant of the independence of character in his wife, he made a spectacle of himself when he instructed his wife to throw away rubbish in public.
whereas [hwerˈæz]: conj. formal used to say that although something is true of one thing, it is not true of another尽管
- Whereas his clothes got into such a mess, he was enthusiastic about taking part in the concert.
- Whereas the killer set your house on fire, he didn't fire a shot at you.
- Whereas he won the election, he decided to retire from political life.
sensibility [ˌsensəˈbɪləti]: n. the way that someone reacts to particular subjects or types of behaviour感情
- The house is equipped with the statue of the Virgin Mary which inspired his religious sensibility.
- Not allowed to go to university, he devoted his sensibility to his work.
- My political sensibility dates back to my youth when I first read the history of the world.
manifest [ˈmænɪˌfest]: v. to show a feeling, attitude etc表现
- I am always too eager to manifest myself in front of my superiors.
- When I want to manifest myself in public, I always make a spectacle of myself.
- His passions manifested as the painting on the ceiling of his apartment.
--------------------
bring sb. to do sth.: 带领某人去做某事
- In my childhood, my amiable uncle always brought us to swim in the river on Summer holidays.
- The amiable Prime Minister brought a gathering to set the Embassy on fire.
- My amiable as well as firm aunt brought me to go to school in town when I played truant from school in a rural village.
hold sway (over sth./sb.): 支配某物/某人
- The firm philosophe was able to hold sway over the high-strung masses.
- Intolerant of disorder in his house, he began to hold sway over members of his family.
- The exalted claim of the papal authority held sway over the monarchs.
the talk of sp.: 某地的话题
- The breakdown of Christian unity through the Reformation and religious wars became the talk of Europe.
- The fantasy world that was depicted in his writings became the talk of Europe.
- The secret far-reached land where gold is everywhere became the talk of Europe.
receive an invitation: 收到邀请
- He claimed condescendingly that he had received the invitation of the monarch.
- If he had received an invitation, he would have been condescending.
- You're forbidden to attend the party if you don't receive an invitation.
make a visit to sp.: 拜访某地
- Sir, you may as well make a visit to China where the masses are suffering from floods.
- The general made a visit to Tokyo which he conquered with his father in his youth.
- Elizabeth made a visit to Beijing where the agreement about the lands was made.
a couple of + ...: 两个/几个事物
- The butcher accused me of freeing a couple of pigs from the cage.
- I denounced the errors that a couple of scientists made in their article. 
- There are a couple of apples on my desktop.
in good taste: 得体的
- Staying out of the limelight, they still behaved in good taste.
- My wife condemns me as a rude warrior who doesn't behave in good taste.
- If you were in good taste, you wouldn't change into such a tight dress at the party.
ever since: 从那时起
- Galileo was called into question before the Inquisition, and the ideas of the Scientific Revolution have been implanted ever since.
- My aunt brought me to go to school in town, I have owned her a lot ever since.
- He has ever since fallen in love with the amiable girl. 
be disgusted with sth.: 对某事物反感
- Disgusted with shopping online, he held sway over members of his family and urged them not to buy anything online.
- Disgusted with the spread of meth, he left the US where he has been for six years.
- Disgusted with the division, he hasn't kept in touch with his wife.
be open to sth.: 对某事物开放
- The monk is open to the ideas from the outside world.
- The girl is open to the love of every boy she runs into.
- The president is open to the spread of these ideas divergent from the mainstream.
do sth. a different way: 用不同地方式做某事
- The Scientific Revolution did overturn centuries of authority in a different way.
- The flight attendant claimed to have taken charge of me in a different way.
- The breakdown of trust in the government happened a different way.
turn sb's back on sth.: 背弃某物
- His wife turned her back on their marriage when she cheated on him.
- The townman realized to his horror that their country was turning its back on the outside world.
- The actions of the Inquisition turned its back on the new ideas of the Scientific Revolution.
Consequently, + ...: 因此, + ...
- Consequently, he succeeded in breaking a world record because of these liquid foods.
- Consequently, I shared my apartment with this stray cat.
- Consequently, she got married to your dentist.
Ironically, + ...: 讽刺地, + ...
- Ironically, the husband risked his life to save her in floods.
- Ironically, a patch of green began to appear on the desert hill.
- Ironically, the people they regarded as barbarian devastated their civilization.
capture the heart of sb.: 捕获某人的心
- Cats in the market never fail to capture the heart of my wife.
- Failing to capture the heart of his wife, he decided to get a divorce.
- This clumsy kind of animal captures the heart of my wife in the exhibition.
** summary
The Scientific Revolution had affected only a small number of educated ilites,
	which changed dramtically
		as the philosophes popularized the new ideas and used them to examine all aspects of life.
In Paris, women took the lead in holding salon to discuss the ideas of the philosophes.
Geoffrian, the wife of a wealthy merchant,
	held sway gatherings that became the talk of France and even Europe.
She was so well received that she exclaimed she was better known in Viena than yards from her house.
Not only did she allow wide-ranging discussions in good taste,
	but she made separated meeting for high-strung artists and philosophers who talked too much.
Those ideas had such a widespread impact on their society
	that historians called the eighteenth century the Age of Enlightenment.
Whereas the scientists of the seventeenth century believed that their work exalted god,
	the intellectuals of the eighteenth century read the same conclusions a different way
		and increasingly turned their backs on Christian orthodoxy.
At the same time that reason and materialism were beginning to replace faith and worship,
	religious sensibility greatly manifested itself in music and art.
It was obvious that the growing secularization had not captured the heart of minds of all Europeans.
** summary2
The Scientific Revolution had affected only a small number of educated elites,
	which changed dramatically
		as the philosophes popularized the new ideas and used them to examine all aspects of life.
In Paris, women took the lead in holding salons to discuss the ideas of the philosophes.
Geoffrin, the wife of a wealthy merchant,
	held sway gatherings that became the talk of France and even Europe.
She was so well received in Viena
	that she exclaimed she was better known here than yards from her house.
Not only did she allow wide-ranging discussions in good taste,
	but she also made separate meetings for high-strung artists and philosophers who talked too much.
Those ideas had such a widespread impact on their society
	that historians called the eighteenth century the Age of Enlightenment.
Whereas the scientists of the seventeenth century believed that their work exalted god,
	the intellectuals of the eighteenth century read the same conclusions in a different way
		and increasingly turned their backs on Christian orthodoxy.
At the same time that reason and materialism were beginning to replace faith and worship,
	a lot of religious sensibility manifested itself in music and art.
The growing secularization had not captured the hearts and minds of all Europeans.
