#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
CHAPTER 2 THE ANCIENT NEAR EAST: PEOPLES AND EMPIRES

CHAPTER OUTLINE AND FOCUS QUESTIONS

On the Fringes of Civilization


Q What is the significance of Indo-European-speaking peoples?


The Hebrews: ‘‘The Children of Israel’’


Q In what ways was the Jewish faith unique in the ancient Near East, and how did it evolve over time? Who were the neighbors of the Israelites, and what was their significance?


The Assyrian Empire


Q What methods and institutions did the Assyrians use to amass and maintain their empire?


The Persian Empire


Q What methods and institutions did the Persians use to amass and maintain their empire, and how did these differ from those of the Assyrians?


CRITICAL THINKING


Q What is the relationship between the political history of the Israelites and the evolution of their religious beliefs?


A medieval Italian manuscript version of the judgment of Solomon


AROUND 970 B.C., Solomon came to the throne of Israel, a small state in western Asia. He was lacking in military prowess but excelled in many other ways. Through trade and a series of foreign alliances, he created a strong, flourishing state. But he was especially famed for his skill as a judge. When two women came before him, each claiming that the same infant was her natural child, Solomon ordered his servant to cut the child in half and give half to each woman. The first woman objected: ‘‘Please, my lord, give her the living baby! Don’t kill him!’’ The second woman replied, ‘‘Neither I nor you shall have him. Cut him in two!’’ Then Solomon rendered his judgment: ‘‘Give the living baby to the first woman. Do not kill him; she is his mother.’’ According to the biblical account, ‘‘When all Israel heard the verdict the king had given, they held the king in awe, because they saw that he had wisdom from God to administer justice.’’ After Solomon’s death, Israel began to disintegrate. But how had such a small nation been able to survive as long as it did in a Near East dominated by mighty empires?


The weakening of Egypt around 1200 B.C. left no dominant powers in the Near East, allowing a patchwork of petty kingdoms and city-states to emerge, especially in Syria and Canaan. One of these small states, the Hebrew nation known as Israel, has played a role in Western civilization completely disproportionate to its size. The Hebrews played a minor part in the politics of the ancient Near East, but their spiritual heritage, in the form of Judeo-Christian values, is one of the basic pillars of Western civilization.


The small states did not last. Ever since the first city-states had arisen in the Near East around 3000 B.C., there had been a movement toward the creation of larger territorial states with more sophisticated systems of control. This process reached a high point in the first millennium B.C. with the assembling of vast empires. Between 1000 and 500 B.C., the Assyrians, the Chaldeans, and the Persians all established empires that encompassed large areas of the ancient Near East. Each had impressive and grandiose capital cities that emphasized the power and wealth of its rulers. Each brought peace and order for a time by employing new administrative techniques. Each eventually fell to other conquerors. In the long run, these large empires had less impact on Western civilization than the Hebrew people. In human history, the power of ideas is often more significant than the power of empires.


On the Fringes of Civilization


Q Focus Question: What is the significance of IndoEuropean-speaking peoples?


Western civilization took root in Mesopotamia and Egypt, but significant developments were also taking place on the fringes of these cultures. Farming had spread into the Balkan peninsula of Europe by 6500 B.C., and by 4000 B.C. it was well established in southern France, central Europe, and the coastal regions of the Mediterranean. Although migrating farmers from the Near East may have brought some farming techniques into Europe, historians now believe that the Neolithic peoples of Europe domesticated animals and began to farm largely on their own.


One outstanding feature of late Neolithic Europe was the building of megalithic structures. Megalith is Greek for ‘‘large stone.’’ Radiocarbon dating, a technique that allows scientists to determine the age of objects, shows that the first megalithic structures were built around 4000 B.C., more than a thousand years before the great pyramids were built in Egypt. Between 3200 and 1500 B.C., standing stones that were placed in circles or lined up in rows were erected throughout the British Isles and northwestern France. Other megalithic constructions have been found as far north as Scandinavia and as far south as the islands of Corsica, Sardinia, and Malta. Some archaeologists have demonstrated that the stone circles were used as observatories to detect not only such simple astronomical phenomena as the midwinter and midsummer sunrises but also such sophisticated observations as the major and minor standstills of the moon.


By far the most famous of these megalithic constructions is Stonehenge in England. Stonehenge consists of a series of concentric rings of standing stones. Its construction sometime between 2100 and 1900 B.C. was no small accomplishment. The eighty bluestones used at Stonehenge, for example, weigh 4 tons each and were transported to the site from their original source 135 miles away. Like other megalithic structures, Stonehenge indicates a remarkable awareness of astronomy on the part of its builders, as well as an impressive coordination of workers.


The Impact of the Indo-Europeans


For many historians, both the details of construction and the purpose of the megalithic structures of Europe remain a mystery. Also puzzling is the role of Indo-European people. The name Indo-European refers to people who used a language derived from a single parent tongue. IndoEuropean languages include Greek, Latin, Persian, Sanskrit, and the Germanic languages (see Table 2.1). It has been suggested that the original Indo-European-speaking peoples were based somewhere in the steppe region north of the Black Sea or in southwestern Asia, in modern Iran or Afghanistan. Although there had been earlier migrations, around 2000 B.C. these people began major nomadic movements into Europe (including present-day Italy and Greece), India, and western Asia. One group of IndoEuropeans who moved into Asia Minor and Anatolia (modern Turkey) around 1750 B.C. coalesced with the native peoples to form the Hittite kingdom with its capital at Hattusha (Bogazkoy in modern Turkey).


The Hittite Empire


Starting around 1600 B.C., the Hittites assembled their own empire in western Asia and even threatened the power of the Egyptians. The Hittites were the first of the Indo-European peoples to make use of iron, enabling them to construct weapons that were stronger and cheaper to make because of the widespread availability of iron ore. Hittite power faltered around 1200 B.C., in part due to internal problems but also as a result of attacks from the west by the Sea Peoples, groups of unknown origin who moved across the Mediterranean in the late thirteenth and early twelfth centuries B.C., and also by an aggressive tribe known as the Gasga, who raided Hittite cities. By 1190 B.C., Hittite power was at an end.


During its heyday, however, the Hittite Empire was one of the great powers in western Asia. The Hittite ruler, known as the Great King, controlled the core areas of the kingdom but in western and southern Anatolia and Syria allowed local rulers to swear allegiance to him as vassals. Constant squabbling over succession to the throne, however, tended to weaken royal authority at times. 


During its height, the Hittite Empire also demonstrated an interesting ability to assimilate other cultures into its own. In languages, literature, art, law, and religion, the Hittites borrowed much from Mesopotamia as well as the native peoples that they had subdued. Recent scholarship has stressed the important role of the Hittites in transmitting Mesopotamian culture, as they transformed it, to later Western civilization in the Mediterranean area, especially to the Mycenaean Greeks (see Chapter 3).


The crumbling of the Hittite kingdom and the weakening of Egypt after 1200 B.C. left a power vacuum in western Asia, allowing a patchwork of petty kingdoms and city-states to emerge, especially in the area at the eastern end of the Mediterranean Sea. The Hebrews were one of these peoples.


The Hebrews: ‘‘The Children of Israel’’


Q Focus Questions: In what ways was the Jewish faith unique in the ancient Near East, and how did it evolve over time? Who were the neighbors of the Israelites, and what was their significance?


The Hebrews were a Semitic-speaking people who had a tradition concerning their origins and history that was eventually written down as part of the Hebrew Bible, known to Christians as the Old Testament. Describing themselves originally as nomads organized in clans, the Hebrews’ tradition states that they were descendants of the patriarch Abraham, who had migrated from Mesopotamia to Canaan, where they became identified as the ‘‘Children of Israel.’’ Again according to tradition, a drought in Canaan caused many Hebrews to migrate to Egypt, where they lived peacefully until they were enslaved by pharaohs who used them as laborers on building projects. These Hebrews remained in bondage until Moses led them eastward out of Egypt in the Exodus, which some historians have argued would have occurred in the first half of the thirteenth century B.C. According to the biblical account, the Hebrews then wandered for many years in the desert until they entered Canaan. Organized into twelve tribes, they became embroiled in conflict with the Philistines, a people who had settled in the coastal area of Canaan but were beginning to move into the inland areas.


Many scholars today doubt that the early books of the Hebrew Bible reflect the true history of the early Israelites. They argue that the early books of the Bible, written centuries after the events described, preserve only what the Israelites came to believe about themselves and that recent archaeological evidence often contradicts the details of the biblical account. Some of these scholars have even argued that the Israelites were not nomadic invaders but indigenous peoples in the Canaanite hill country. What is generally agreed, however, is that between 1200 and 1000 B.C., the Israelites emerged as a distinct group of people, possibly organized in tribes or a league of tribes, who established a united kingdom known as Israel.  


The United Kingdom


The first king of the Israelites was Saul (c. 1020--1000 B.C.), who initially achieved some success in the ongoing struggle with the Philistines. But after his death in a disastrous battle with this enemy, a brief period of anarchy ensued until one of Saul’s lieutenants, David (c. 1000--970 B.C.), reunited the Israelites, defeated the Philistines, and established control over all of Canaan (see Map 2.1). According to the biblical account, some of his conquests led to harsh treatment for the conquered people: ‘‘David also defeated the Moabites. He made them lie down on the ground and measured them off with a length of cord. Every two lengths of them were put to death, and the third length was allowed to live. So the Moabites became subject to David and brought tribute.’’1 Among David’s conquests was the city of Jerusalem, which he made into the capital of a united kingdom. David centralized Israel’s political organization and accelerated the integration of the Israelites into a settled community based on farming and urban life.


David’s son Solomon (c. 970--930 B.C.) did even more to strengthen royal power. He expanded the political and military establishments and was especially active in extending the trading activities of the Israelites. Solomon is best known for his building projects, the most famous of which was the Temple in Jerusalem. The Israelites viewed the Temple as the symbolic center of their religion and hence of the kingdom of Israel itself. The Temple now housed the Ark of the Covenant, a holy chest containing the sacred relics of the Hebrew religion and, symbolically, the throne of the invisible God of Israel. Under Solomon, ancient Israel was at the height of its power, but his efforts to extend royal power throughout his kingdom led to dissatisfaction among some of his subjects.


The Divided Kingdom


After Solomon’s death, tensions in Israel between the northern and southern tribes led to the establishment of two separate kingdoms---the kingdom of Israel, composed of the ten northern tribes, with its capital eventually at Samaria, and the southern kingdom of Judah, consisting of two tribes, with its capital at Jerusalem. In 722 or 721 B.C., the Assyrians destroyed Samaria, overran the kingdom of Israel, and deported many Israelites to other parts of the Assyrian Empire. These dispersed Israelites (the ‘‘ten lost tribes’’) merged with neighboring peoples and gradually lost their identity.

The southern kingdom of Judah was also forced to pay tribute to Assyria but managed to retain its independence as Assyrian power declined. A new enemy, however, appeared on the horizon. The Chaldeans brought the final destruction of Assyria, conquered the kingdom of Judah, and completely destroyed Jerusalem in 586 B.C. Many people from Judah were deported to Babylonia; the memory of their exile is still evoked in the stirring words of Psalm 137:


By the rivers of Babylon, we sat and wept when we remembered Zion. . . .
How can we sing the songs of the Lord while in a foreign land?
If I forget you, O Jerusalem, may my right hand forget its skill.
May my tongue cling to the roof of my mouth if I do not remember you, if I do not consider Jerusalem my highest joy.


But the Babylonian captivity of the people of Judah did not last. A new set of conquerors, the Persians, destroyed the Chaldean kingdom but allowed the people of Judah to return to Jerusalem and rebuild their city and temple. The revived kingdom of Judah remained under Persian control until the conquests of Alexander the Great in the fourth century B.C. The people of Judah survived, eventually becoming known as the Jews and giving their name to Judaism, the religion of Yahweh, the Israelite God.


The Spiritual Dimensions of Israel


The spiritual perspective of the Israelites evolved over time. Early Israelites probably worshiped many gods, including nature spirits dwelling in trees and rocks. For some Israelites, Yahweh was the chief god of Israel, but many, including kings of Israel and Judah, worshiped other gods as well. It was among the Babylonian exiles that Yahweh, the God of Israel, came to be regarded as the only God. After the return of these exiles to Judah, their point of view eventually became dominant, and pure monotheism, the belief that there is only one God, came to be the major tenet of Judaism.


‘‘I Am the Lord Your God’’: Ruler of the World


According to the Jewish conception, there is but one God, whom the Jews called Yahweh. God is the creator of the world and everything in it. To the Jews, the gods of all other peoples were merely idols. The Jewish God ruled the world; he was subject to nothing. All peoples were his servants, whether they knew it or not. This God was also transcendent. He had created nature but was not in nature. The stars, moon, rivers, wind, and other natural phenomena were not divinities or suffused with divinity, as other peoples of the ancient Near East believed, but they were God’s handiwork. All of God’s creations could be admired for their awesome beauty but not worshiped as gods.


This omnipotent creator of the universe was not removed from the life he had created, however, but was a just and good God who expected goodness from his people. If they did not obey his will, they would be punished. But he was also a God of mercy and love: ‘‘The Lord is gracious and compassionate, slow to anger and rich in love. The Lord is good to all; he has compassion on all he has made.’’3 Despite the powerful dimensions of God as creator and sustainer of the universe, the Jewish message also emphasized that each person could have a personal relationship with this powerful being. As the psalmist sang, ‘‘My help comes from the Lord, the Maker of heaven and earth. He will not let your foot slip---he who watches over you will not slumber.’’4


‘‘You Only Have I Chosen’’: Covenant and Law


Three aspects of the Hebrew religious tradition had special significance: the covenant, law, and the prophets. The Israelites believed that during the Exodus from Egypt, when Moses supposedly led his people out of bondage into the ‘‘promised land,’’ a special event occurred that determined the Jewish experience for all time. According to tradition, God entered into a covenant or contract with the tribes of Israel, who believed that Yahweh had spoken to them through Moses (see the box on p. 30). The Israelites promised to obey Yahweh and follow his law. In return, Yahweh promised to take special care of his chosen people, ‘‘a peculiar treasure unto me above all people.’’


This covenant between Yahweh and his chosen people could be fulfilled, however, only by obedience to the law of God. Law became a crucial element of the Jewish world and had a number of different dimensions. In some instances, it set forth specific requirements, such as payments for offenses. Most important, since the major characteristic of God was his goodness, ethical concerns stood at the center of the law. Sometimes these took the form of specific standards of moral behavior: ‘‘You shall not murder. You shall not commit adultery. You shall not steal.’’5 But these concerns were also expressed in decrees that regulated the economic, social, religious, and political life of the community, since God’s laws of morality applied to all areas of life. These laws made no class distinctions and emphasized the protection of the poor, widows, orphans, and slaves.


The Prophets


The Israelites believed that certain religious leaders or ‘‘holy men,’’ called prophets, were sent by God to serve as his voice to his people. The golden age of the prophets began in the mid-eighth century B.C. and continued during the time when the people of Israel and Judah were threatened by Assyrian and Chaldean conquerors. These ‘‘men of God’’ went through the land warning the Israelites that they had failed to keep God’s commandments and would be punished for breaking the covenant: ‘‘I will punish you for all your iniquities.’’ Amos prophesied the fall of the northern kingdom of Israel to Assyria; twenty years later, Isaiah said the kingdom of Judah too would fall (see the box on p. 31).


Out of the words of the prophets came new concepts that enriched the Jewish tradition and ultimately Western civilization, including a notion of universalism and a yearning for social justice. Although the Jews’ religious practices gave them a sense of separateness from other peoples, the prophets transcended this by embracing a concern for all humanity. All nations would someday come to the God of Israel: ‘‘All the earth shall worship you.’’ A universal community of all people under God would someday be established by Israel’s effort. This vision encompassed the elimination of war and the establishment of peace for all the nations of the world. In the words of the prophet Isaiah, ‘‘He will judge between the nations and will settle disputes for many people. They will beat their swords into plowshares and their spears into pruning hooks. Nation will not take up sword against nation, nor will they train for war anymore.’’6


The prophets also cried out against social injustice. They condemned the rich for causing the poor to suffer, denounced luxuries as worthless, and warned of dire punishments for these sins. God’s command was to live justly, share with one’s neighbors, care for the poor and the unfortunate, and act with compassion. When God’s command was not followed, the social fabric of the community was threatened. These proclamations by Israel’s prophets became a source for Western ideals of social justice, even if they have never been perfectly realized.


Although the prophets eventually developed a sense of universalism, the demands of the Jewish religion---the obligation to obey their God---encouraged a separation between the Jews and their non-Jewish neighbors. Unlike most other peoples of the Near East, Jews could not simply be amalgamated into a community by accepting the gods of their conquerors and their neighbors. To remain faithful to the demands of their God, they might even have to refuse loyalty to political leaders.


The Neighbors of the Israelites


The Israelites were not the only people living in Canaan. The Philistines, who invaded from the sea, established five towns on the coastal plain of the region. They settled down as farmers and eventually entered into conflict with the Israelites. Although the Philistines were newcomers to the area, the Phoenicians had resided there for some time but now found themselves with a new independence. A Semitic-speaking people, the Phoenicians resided along the Mediterranean coast on a narrow band of land 120 miles long. They had rebuilt their major cities after destruction by the Sea Peoples. Their newfound political independence helped the Phoenicians expand the trade that was already the foundation of their prosperity. In fact, the Phoenician city of Byblos had been the principal distribution center for Egyptian papyrus outside Egypt (the Greek word for book, biblos, is derived from the name Byblos).


The chief cities of Phoenicia---Byblos, Tyre, and Sidon---were ports on the eastern Mediterranean, but they also served as distribution centers for the lands to the east in Mesopotamia. The Phoenicians themselves produced a number of goods for foreign markets, including purple dye, glass, wine, and lumber from the famous cedars of Lebanon. In addition, the Phoenicians improved their ships and became great international sea traders. They charted new routes, not only in the Mediterranean but also in the Atlantic Ocean, where they sailed south along the west coast of Africa. The Phoenicians established a number of colonies in the western Mediterranean, including settlements in southern Spain, Sicily, and Sardinia. Carthage, the Phoenicians’ most famous colony, was located on the North African coast.


Culturally, the Phoenicians are best known as transmitters. Instead of using pictographs or signs to represent whole words and syllables as the Mesopotamians and Egyptians did, the Phoenicians simplified their writing by using twenty-two different signs to represent the sounds of their speech. These twenty-two characters or letters could be used to spell out all the words in the Phoenician language. Although the Phoenicians were not the only people to invent an alphabet, theirs would have special significance because it was eventually passed on to the Greeks. From the Greek alphabet was derived the Roman alphabet that we still use today (see Table 2.2). The Phoenicians achieved much while independent, but they ultimately fell subject to the Assyrians, Chaldeans, and Persians.


The Assyrian Empire


Q Focus Question: What methods and institutions did the Assyrians use to amass and maintain their empire?


The existence of independent states in Canaan was possible only because of the power vacuum existing in the ancient Near East after the demise of the Hittite kingdom and the weakening of Egypt. But this condition did not last; new empires soon came to dominate vast stretches of the ancient Near East. The first of these empires emerged in Assyria, an area whose location on the upper Tigris River brought it into both cultural and political contact with southern Mesopotamia.


Although part of Mesopotamia, Assyria, with its hills and adequate, if not ample, rainfall, had a different terrain and climate. The Assyrians were a Semiticspeaking people who exploited the use of iron weapons to establish an empire by 700 B.C. that included Mesopotamia, parts of the Iranian plateau, sections of Asia Minor, Syria, Canaan, and Egypt down to Thebes (see Map 2.2). Ashurbanipal (669--626 B.C.) was one of the strongest Assyrian rulers, but it was already becoming apparent during his reign that the Assyrian Empire was greatly overextended. Internal strife intensified as powerful Assyrian nobles gained control of vast territories and waged their own private military campaigns. Moreover, subject peoples, such as the Babylonians, greatly resented Assyrian rule and rebelled against it. Soon after Ashurbanipal’s reign, the Assyrian Empire began to disintegrate rapidly. The capital city of Nineveh fell to a coalition of Chaldeans and Medes in 612 B.C., and in 605 B.C. the rest of the empire was finally divided between the coalition powers.


Organization of the Empire


At its height, the Assyrian Empire was ruled by kings whose power was considered absolute. Under their leadership, the empire became well organized. By eliminating governorships held by nobles on a hereditary basis and instituting a new hierarchy of local officials directly responsible to the king, the Assyrian kings gained greater control over the resources of the empire. The Assyrians also developed an efficient system of communication to administer their empire more effectively. A network of posting stages was established throughout the empire that used relays of horses (mules or donkeys in mountainous terrain) to carry messages. The system was so effective that a provincial governor anywhere in the empire (except Egypt) could send a query and receive an answer from the king within a week.


The Assyrian Military Machine


The ability of the Assyrians to conquer and maintain an empire was due to a combination of factors. Over many years of practice, the Assyrians developed effective military leaders and fighters. They were able to enlist and deploy troops numbering in the hundreds of thousands, although most campaignswere not conducted onsuch a largescale.In 845 B.C., an Assyrian army of 120,000 men crossed the Euphrates on a campaign. Size alone was not decisive, however. The Assyrian army was extremely well organized and disciplined. It included a standing army of infantrymen as its core, accompanied by cavalrymen and horse-drawn war chariots that were used as mobile platforms for shooting arrows. Moreover, the Assyrians had the advantage of having the first large armies equipped with iron weapons. The Hittites had been the first to develop iron metallurgy, but iron came to be used extensively only after new methods for hardening it became common after 1000 B.C.


Another factor in the army’s success was its ability to use various military tactics (see the box above). The Assyrians were skilled at waging guerrilla war in the mountains and set battles on open ground and were especially renowned for siege warfare. They would hammer a city’s walls with heavy, wheeled siege towers and armored battering rams while sappers dug tunnels to undermine the walls’ foundations and cause them to collapse. The besieging Assyrian armies learned to cut off supplies so effectively that if a city did not fall to them, the inhabitants could be starved into submission.


A final factor in the effectiveness of the Assyrian military machine was its ability to create a climate of terror as an instrument of war. The Assyrians became famous for their terror tactics, although some historians believe that their policies were no worse than those of other conquerors. As a matter of regular policy, the Assyrians laid waste the land in which they were fighting, smashing dams, looting and destroying towns, setting crops on fire, and cutting down trees, particularly fruit trees. The Assyrians were especially known for committing atrocities on their captives. King Ashurnasirpal II recorded this account of his treatment of prisoners: 


3000 of their combat troops I felled with weapons. . . . Many of the captives taken from them I burned in a fire. Many I took alive; from some of these I cut off their hands to the wrist, from others I cut off their noses, ears and fingers; I put out the eyes of many of the soldiers. . . . I burned their young men and women to death.7


After conquering another city, the same king wrote, ‘‘I fixed up a pile of corpses in front of the city’s gate. I flayed the nobles, as many as had rebelled, and spread their skins out on the piles. . . . I flayed many within my land and spread their skins out on the walls.’’8 (Obviously not a king to play games with!) Note that this policy of extreme cruelty to prisoners was not used against all enemies but was reserved primarily for those who were already part of the empire and then rebelled against Assyrian rule.


Assyrian Society and Culture


Unlike the Hebrews, the Assyrians were not fearful of mixing with other peoples. In fact, the Assyrian policy of deporting many prisoners of newly conquered territories to Assyria created a polyglot society in which ethnic differences were not very important. It has been estimated that over a period of three centuries, between four and five million people were deported to Assyria, resulting in a population that was very racially and linguistically mixed. What gave identity to the Assyrians themselves was their language, although even that was akin to that of their southern neighbors in Babylonia, who also spoke a Semitic tongue. Religion was also a cohesive force. Assyria was literally ‘‘the land of Ashur,’’ a reference to its chief god. The king, as the human representative of the god Ashur, provided a unifying focus.


Agriculture formed the principal basis of Assyrian life. Assyria was a land of farming villages with relatively few significant cities, especially in comparison to southern Mesopotamia. Unlike the river valleys, where farming required the minute organization of large numbers of people to control irrigation, Assyrian farms received sufficient moisture from regular rainfall. Trade was second to agriculture in economic importance. For internal trade, metals, such as gold, silver, copper, and bronze, were used as a medium of exchange. Various agricultural products also served as a form of payment or exchange. Because of their geographical location, the Assyrians served as middlemen and participated in an international trade in which they imported timber, wine, and precious metals and stones while exporting textiles produced in palaces, temples, and private villas.


Assyrian culture was a hybrid. The Assyrians assimilated much of Mesopotamian civilization and saw themselves as guardians of Sumerian and Babylonian culture. Ashurbanipal, for example, established a large library at Nineveh that included the available works of Mesopotamian history. Assyrian religion reflected this assimilation of other cultures as well. Although the Assyrians’ national god Ashur was their chief deity, virtually all the other gods and goddesses were Mesopotamian.


Among the best-known objects of Assyrian art are the relief sculptures found in the royal palaces in three of the Assyrian capital cities, Nimrud, Nineveh, and Khorsabad. These reliefs, which were begun in the ninth century B.C. and reached their high point in the reign of Ashurbanipal in the seventh, depicted two different kinds of subject matter: ritual or ceremonial scenes, revolving around the person of the king, and scenes of hunting and war. The latter show realistic action scenes of the king and his warriors engaged in battle or hunting animals, especially lions. These pictures depict a strongly masculine world where discipline, brute force, and toughness are the enduring values, indeed, the very values of the Assyrian military monarchy.


The Persian Empire


Q Focus Question: What methods and institutions did the Persians use to amass and maintain their empire, and how did these differ from those of the Assyrians?


The Chaldeans, a Semitic-speaking people, had gained ascendancy in Babylonia by the seventh century and came to form the chief resistance to Assyrian control of Mesopotamia. After the collapse of the Assyrian Empire, the Chaldeans, under their king Nebuchadnezzar II (605--562 B.C.), regained for Babylonia a position as the leading power in the ancient Near East. 


Nebuchadnezzar rebuilt Babylon as the center of his empire, giving it a reputation as one of the great cities of the ancient world. Babylon was surrounded by great walls, 8 miles in length, encircled by a moat filled by the Euphrates River. The city was adorned with temples and palaces; most famous of all were the Hanging Gardens, known as one of the Seven Wonders of the ancient world. These were supposedly built to satisfy Nebuchadnezzar’s wife, a princess from the land of Media, who missed the mountains of her homeland. A series of terraces led to a plateau, an artificial mountain, at the top of which grew the lush gardens irrigated by water piped to the top. According to the account of a first-century A.D. author, the impression of the gardens from a distance was quite remarkable:


On the top of the citadel are the hanging gardens, a wonder celebrated in the tales of the Greeks. . . . Columns of stone were set up to sustain the whole work, and on these was laid a floor of squared blocks, strong enough to hold the earth which is thrown upon it to a great depth, as well as the water with which they irrigate the soil; and the structure supports trees of such great size that the thickness of their trunks equals a measure of eight cubits [about 12 feet]. They tower to a height of fifty feet, and they yield as much fruit as if they were growing in their native soil. . . . To those who look upon the trees from a distance, real woods seem to be overhanging their native mountains.9 But the splendor of the Neo-Babylonian Empire proved to be short-lived when Babylon fell to the Persians in 539 B.C. The Persians were an Indo-European-speaking people related to the Medes. Both peoples probably formed part of the great waves of Indo-European migrations into the Mediterranean, the Near East, and India. The Persians lived to the southeast of the Medes, who occupied the western Iranian plateau south of the Caspian Sea. Primarily nomadic, both Medes and Persians were organized in clans. Leaders of both peoples were petty kings assisted by a group of warriors who formed a class of nobles.


By 735 B.C., the Medes had begun to form a confederation of the various tribes, and around the beginning of the seventh century, they became unified under a monarchy. The Persians did likewise under the Achaemenid dynasty established in Persis in southern Iran. About fifty years later, the Persians were made subject to the Medes. The Medes now constituted a powerful state and joined the Babylonians in attacking the Assyrians. After the capture of Nineveh in 612 B.C., King Cyaxares established a Median empire, the first Iranian empire known to the ancient Near East.


Cyrus the Great (559--530 B.C.)


In 559 B.C., Cyrus became the leader of the Persians, united them under his rule, and went on the offensive against the Medes. In 550 B.C., he established Persian control over Media, making it the first Persian satrapy, or province. Three years later, Cyrus defeated the prosperous Lydian kingdom in western Asia Minor, and Lydia became another Persian satrapy (see Map 2.3). Cyrus’ forces then went on to conquer the Greek city-states that had been established on the Ionian coast. Cyrus then turned eastward, subduing the eastern part of the Iranian plateau, Sogdiana, and even western India. His eastern frontiers secured, Cyrus entered Mesopotamia in 539 and captured Babylon. His treatment of Babylonia showed remarkable restraint and wisdom. Babylonia was made into a Persian province under a Persian satrap, but many government officials were kept in their positions. Cyrus took the title ‘‘King of All, Great King, Mighty King, King of Babylon, King of the Land of Sumer and Akkad, King of the Four Rims [of the earth], the Son of Cambyses the Great King, King of Anshan’’10 and insisted that he stood in the ancient, unbroken line of Babylonian kings. By appealing to the vanity of the Babylonians, he won their loyalty. Cyrus also issued an edict permitting the Jews, who had been brought to Babylon in the sixth century B.C., to return to Jerusalem with their sacred temple objects and to rebuild their temple as well.


To his contemporaries, Cyrus the Great was deserving of his epithet. The Greek historian Herodotus recounted that the Persians viewed him as a ‘‘father,’’ a ruler who was ‘‘gentle, and procured them all manner of goods.’’11 Certainly, Cyrus must have been an unusual ruler for his time, a man who demonstrated considerable wisdom and compassion in the conquest and organization of his empire. Cyrus gained the favor of the priesthoods in his conquered lands by restoring temples and permitting religious toleration. He won approval by using not only Persians but also native peoples as government officials in their own states. Unlike the Assyrian rulers of an earlier empire, he had a reputation for mercy. Medes, Babylonians, and Hebrews all accepted him as their legitimate ruler. Indeed, the Hebrews regarded him as the anointed one of God:


I am the Lord who says of Cyrus, ‘‘He is my shepherd and will accomplish all that I please’’; he will say of Jerusalem, ‘‘Let it be rebuilt’’; and of the temple, ‘‘Let its foundations be laid.’’ This is what the Lord says to his anointed, to Cyrus, whose right hand I take hold of to subdue nations before him.12 


Cyrus had a genuine respect for ancient civilizations---in building his palaces, he made use of Assyrian, Babylonian, Egyptian, and Lydian practices.


Expanding the Empire


Cyrus’ successors extended the territory of the Persian Empire. His son Cambyses (530--522 B.C.) undertook a successful invasion of Egypt and made it into a satrapy with Memphis as its capital. Darius (521--486 B.C.) added a new Persian province in western India that extended to the Indus River and moved into Europe proper, conquering Thrace and making the Macedonian king a vassal. A revolt of the Ionian Greek cities in 499 B.C. resulted in temporary freedom for these communities in western Asia Minor. Aid from the Greek mainland, most notably from Athens, encouraged the Ionians to invade Lydia and burn Sardis, center of the Lydian satrapy. This event led to Darius’ involvement with the mainland Greeks. After reestablishing control of the Ionian Greek cities, Darius undertook an invasion of the Greek mainland, which culminated in the famous Athenian victory in the Battle of Marathon in 490 B.C. (see Chapter 3).


Governing the Empire


By the reign of Darius, the Persians had created the largest empire the world had yet seen. As noted earlier, it not only included all the old centers of power in the Near East, Egypt, Mesopotamia, and Assyria but also extended into Thrace and Asia Minor in the west and into India in the east. For administrative purposes, the empire had been divided into around twenty satrapies. Each of these provinces was ruled by a governor or satrap, literally, a ‘‘protector of the kingdom.’’ Although Darius had not introduced the system of satrapies, he organized it more rationally. He created a sensible system for calculating the tribute that each satrapy owed to the central government and gave satraps specific civil and military duties. They collected tributes, were responsible for justice and security, raised military levies for the royal army, and normally commanded the military forces within their satrapies. In terms of real power, the satraps were miniature kings with courts imitative of the Great King’s. 


From the time of Darius on, satraps were men of Persian descent. The major satrapies were given to princes of the royal family, and their position became essentially hereditary. The minor satrapies were placed in the hands of Persian nobles. Their offices, too, tended to pass from father to son. The hereditary nature of the governors’ offices made it necessary to provide some checks on their power. Consequently, royal officials at the satrapal courts acted as spies for the Great King.


An efficient system of communication was crucial to sustaining the Persian Empire. Well-maintained roads facilitated the rapid transit of military and government personnel. One in particular, the so-called Royal Road, stretched from Sardis, the center of Lydia in Asia Minor, to Susa, the chief capital of the Persian Empire. Like the Assyrians, the Persians established staging posts equipped with fresh horses for the king’s messengers.


The Great King


In this vast administrative system, the Persian king occupied an exalted position. All subjects were the king’s servants, and he was the source of all justice, possessing the power of life and death over everyone. Persian kings were largely secluded and not easily accessible. They resided in a series of splendid palaces. Darius in particular was a palace builder on a grand scale. His description of the construction of a palace in the chief Persian capital of Susa demonstrated what a truly international empire Persia was: 


This is the . . . palace which at Susa I built. From afar its ornamentation was brought. . . . The cedar timber was brought from a mountain named Lebanon; the Assyrians brought it to Babylon, and from Babylon the Carians and Ionians brought it to Susa. Teakwood was brought from Gandara and from Carmania. The gold which was used here was brought from Sardis and from Bactria. The stone---lapis lazuli and carnelian---was brought from Sogdiana. . . . The silver and copper were brought from Egypt. The ornamentation with which the wall was adorned was brought from Ionia. The ivory was brought from Ethiopia, from India, and from Arachosia. The stone pillars were brought from . . . Elam. The artisans who dressed the stone were Ionians and Sardians. The goldsmiths who wrought the gold were Medes and Egyptians. . . . Those who worked the baked brick [with figures] were Babylonians. The men who adorned the wall were Medes and Egyptians. At Susa here a splendid work was ordered; very splendid did it turn out.13


But Darius was unhappy with Susa. He did not really consider it his homeland, and it was oppressively hot in the summer months. He built another residence at Persepolis, a new capital located to the southeast of the old one at a higher elevation. 


The policies of Darius also tended to widen the gap between the king and his subjects. As the Great King himself said of all his subjects, ‘‘What was said to them by me, night and day it was done.’’14 Over a period of time, the Great Kings in their greed came to hoard immense quantities of gold and silver in the various treasuries located in the capital cities. Both their hoarding of wealth and their later overtaxation of their subjects are seen as crucial factors in the ultimate weakening of the Persian Empire (see the box above).


In its heyday, however, the empire stood supreme, and much of its power depended on the military. By the time of Darius, the Persian monarchs had created a standing army of professional soldiers. This army was truly international, composed of contingents from the various peoples who made up the empire. At its core was a cavalry force of ten thousand and an elite infantry force of ten thousand Medes and Persians known as the Immortals because they were never allowed to fall below ten thousand in number. When one was killed, he was immediately replaced. The Persians made effective use of their cavalry, especially for operating behind enemy lines and breaking up lines of communication.


Persian Religion


Of all the Persians’ cultural contributions, the most original was their religion, Zoroastrianism. According to Persian tradition, its founder, Zoroaster (also known as Zarathustra), was born in 660 B.C. After a period of wandering and solitude, he experienced revelations that caused him to be revered as a prophet of the ‘‘true religion.’’ His teachings were eventually written down in the third century A.D. in the Zend Avesta.


Like the Hebrews’, Zoroaster’s spiritual message was monotheistic. To Zoroaster, Ahuramazda was the only god, and the religion he preached was the only perfect one. Ahuramazda (‘‘Wise Lord’’) was the supreme deity who brought all things into being: This I ask of You, O Ahuramazda; answer me well: Who at the Creation was the first father of Justice?--- Who assigned their path to the sun and the stars?--- Who decreed the waxing and waning of the moon, if it was not You?--- . . . Who has fixed the earth below, and the heaven above with its clouds that it might not be moved?--- Who has appointed the waters and the green things upon the earth?--- Who has harnessed to the wind and the clouds their steeds?--- . . . Thus do I strive to recognize in You, O Wise One, Together with the Holy Spirit, the Creator of all things.15


According to Zoroaster, Ahuramazda also possessed abstract qualities or states that all humans should aspire to, such as good thought, right, and piety. Although Ahuramazda was supreme, he was not unopposed. At the beginning of the world, the good spirit of Ahuramazda was opposed by the evil spirit, known as Ahriman.


Humans also played a role in this cosmic struggle between good and evil. Ahuramazda, the creator, gave all humans free will and the power to choose between right and wrong. The good person chooses the right way of Ahuramazda. Zoroaster taught that there would be an end to the struggle between good and evil. Ahuramazda would eventually triumph, and at the last judgment at the end of the world, the final separation of good and evil would occur. Individuals, too, would be judged. Each soul faced a final evaluation of its actions. If a person had performed good deeds, he or she would achieve paradise; if evil deeds, the soul would be thrown into an abyss of torment.


CONCLUSION


Around 1200 B.C., the decline of the Hittites and the Egyptians had created a void in the Near East that allowed a number of small states to emerge and flourish temporarily. All of them were eventually overshadowed by the rise of the great empires of the Assyrians, Chaldeans, and Persians. The Assyrian Empire was the first to unite almost all of the ancient Near East. Even larger, however, was the empire of the Great Kings of Persia. Although it owed much to the administrative organization created by the Assyrians, the Persian Empire had its own peculiar strengths. Persian rule was tolerant as well as efficient. Conquered peoples were allowed to keep their own religions, customs, and methods of doing business. The many years of peace that the Persian Empire brought to the Near East facilitated trade and the general wellbeing of its peoples. It is no wonder that many peoples expressed their gratitude for being subjects of the Great Kings of Persia.


The Hebrews were one of these peoples. They created no empire and were dominated by the Assyrians, Chaldeans, and Persians. Nevertheless, they left a spiritual legacy that influenced much of the later development of Western civilization. The evolution of Hebrew monotheism helped Judaism become one of the world’s great religions; it influenced the development of both Christianity and Islam. When we speak of the Judeo-Christian heritage of Western civilization, we refer not only to the concept of monotheism but also to ideas of law, morality, and social justice that have become important parts of Western culture. On the western fringes of the Persian Empire, another relatively small group of people, the Greeks, were evolving cultural and political ideals that would also have an important impact on Western civilization. It is to the Greeks that we now turn.
