#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 20 Power looms in an English textile factory
#+begin_verse
The French Revolution dramatically altered the political structure of France;
	the Napoleonic conquests then spread many of the revolutionary principles to other parts of Europe.
At the same time, during the late eighteenth and early nineteenth centuries,
	another revolution---an industrial one---
		was transforming the economic and social structure of Europe,
			although somewhat less radically and rapidly.

The Industrial Revolution initiated a quantum leap in industrial production.
New sources of energy and power, especially coal and steam,
	replaced wind and water to run laborsaving machines
		that dramatically decreased the use of human and animal muscle power
			and at the same time increased productivity.
This, in turn, called for new ways of organizing human labor
		to maximize the benefits and profits from the new machines
	as factories replaced artisanal workshops and the cottage industry.
Many early factories were dreadful places with difficult working conditions.
Reformers, appalled at these conditions,
	were especially critical of the treatment of married women.
One reported,
	'We have repeatedly seen married females,
		in the last stage of pregnancy, slaving from morning to night beside these never-tiring machines,
	and when they were obliged to sit down to take a moment's ease,
			and being seen by the manager,
		were fined for the offense.'
But some factories were well run.
William Cobbett described one in Manchester in 1830:
	'In this room, which is lighted in the most convenient and beautiful manner,
		there were five hundred pairs of looms at work,
			and five hundred persons attending those looms;
			and, owing to the goodness of the masters, the whole looking healthy and well-dressed.'

During the Industrial Revolution,
	Europe experienced a shift from a traditional, labor-intensive economy
			based on farming and handicrafts
		to a more capital-intensive economy
			based on manufacturing by machines, specialized labor, and industrial factories.
Although the Industrial Revolution took decades to spread,
	it was truly revolutionary in the way
		it fundamentally changed Europeans, their society, and their relationship to other peoples.
The development of large factories encouraged mass movements of people from the countryside to urban areas
	where impersonal coexistence replaced the traditional intimacy of rural life.
Higher levels of productivity led to a search for new sources of raw materials,
	new consumption patterns,
	and a revolution in transportation
		that allowed raw materials and finished products to be moved quickly around the world.
The rise of a wealthy industrial middle class
		and a huge industrial working class (or proletariat)
	substantially transformed traditional social relationships.
#+end_verse
** expression
alter [ˈɔltər]: v. to change, or to make someone or something change改变
principle [ˈprɪnsəp(ə)l]: n. a moral rule or belief about what is right and wrong, that influences how you behave法则, 原则, 原理
somewhat [ˈsʌmwɑt]: adv. more than a little but not very稍微, 有点, 有些
coal [koʊl]: n. a hard black mineral which is dug out of the ground and burnt to produce heat煤
muscle [ˈmʌs(ə)l]: n. one of the pieces of flesh inside your body that you use in order to move, and that connect your bones together肌肉
maximize [ˈmæksɪˌmaɪz]: v. to increase something such as profit or income as much as possible OPP minimize最大化
artisan [ˈɑrtɪzən]: n. someone who does skilled work, making things with their hands SYN craftsman工匠, 技工
slave [sleɪv]: v. to work very hard with little time to rest辛勤努力
lighted [laɪt]: adj. a lighted window, room etc is bright because there is a light on inside明亮的
convenient [kənˈviniənt]: adj. useful to you because it saves you time, or does not spoil your plans or cause you problems OPP inconvenient便利的
loom [lum]: n. a machine on which thread is woven into cloth纺织机
handicraft [ˈhændiˌkræft]: n. an activity such as sewing or making baskets, in which you use your hands in a skilful way to make things手工艺
intensive [ɪnˈtensɪv]: adj. involving a lot of activity, effort, or careful attention in a short period of time密集的
cottage [ˈkɑtɪdʒ]: n. a small house in the country村舍, 小别墅
manufacture [ˌmænjəˈfæktʃər]: v. to use machines to make goods or materials, usually in large numbers or amounts制造, 加工
impersonal [ɪmˈpɜrs(ə)nəl]: adj. not showing any feelings of sympathy, friendliness etc冷漠的,没人情味的
intimacy [ˈɪntɪməsi]: n. a state of having a close personal relationship with someone亲密
consume [kənˈsum] v. consumption:to use time, energy, goods etc ⇨ consumption消耗, 消费
transport [trænsˈpɔrt] transportation: v.n. to take goods, people etc from one place to another in a vehicle传送, 运输
proletariat [ˌprəʊləˈterɪət]: n. the class of workers who own no property and work for wages, especially in factories, building things etc – used in ↑socialist writings无产阶级
substantially [səbˈstænʃ(ə)li]: adv. very much or a lot SYN considerably充分地
--------------------
many of sth.: 许多xx
a quantum leap in sth.: 某事物量子的突破
replace sth./sb. to do sth.: 代替某人/事物去做某事
call for sth.: 要求某事
be appalled at sth.: 对某事感到震惊
be critical of sth.: 批判某事
from morning to night: 从早到晚
at work: 在工作中
owe to sth./sb.: 由于某人/事物
coexistence of sth./sb.: 某人/事的共存
** sentence
alter [ˈɔltər]: v. to change, or to make someone or something change改变
- Nothing can alter the fact that he loves going whoring.
- Running into the car accident, her face has altered beyond recognition.
- With her face altering in the operation, we couldn't identity her in the railway station.
principle [ˈprɪnsəp(ə)l]: n. a moral rule or belief about what is right and wrong, that influences how you behave法则, 原则, 原理
- The leading principle is that our soliders shoule be equipped with guns and ammunition before the battle.
- The basic principle is that we should keep our princess in hiding.
- The basic principle is that you should make an apologize after we quarrel.
somewhat [ˈsʌmwɑt]: adv. more than a little but not very稍微, 有点, 有些
- The mother of Fangsiyu is somewhat pretty, and you are somewhat funny.
- I must confess you are somewhat charming dressed in a full-length skirt.
- On changing into the overall, the worker looked somewhat cheerful.
coal [koʊl]: n. a hard black mineral which is dug out of the ground and burnt to produce heat煤
- The worker must have been trapped in the coal mine. 
- The coal mine is a place with the harsher working conditions.
- They expected to dig up gold in the coal mine.
muscle [ˈmʌs(ə)l]: n. one of the pieces of flesh inside your body that you use in order to move, and that connect your bones together肌肉
- His house was equipped with those machines after he declared that he was going to strength his muscles.
- He was amazed to find that his muscle had been strengthed in the coal mine.
- The man full of muscles is as strong as a horse.
maximize [ˈmæksɪˌmaɪz]: v. to increase something such as profit or income as much as possible OPP minimize最大化
- Mr. Leo goes out of his way to maximize his profits from these subscribers.
- The oven maximized the use of electrical power.
- The solider stood to attention and maximized his honor to the general as possible as he could.
artisan [ˈɑrtɪzən]: n. someone who does skilled work, making things with their hands SYN craftsman工匠, 技工
- The cornered artisan was forced to drink the urine of rats by these gangsters.
- The artisan in obscurity turned out to be our chief executive officer in our parent company.
- The artisan's apartment was used as a place of worship for the local Christanity.
slave [sleɪv]: v. to work very hard with little time to rest辛勤努力
- Slaving from morning to afternoon, he hasn't said a word.
- Slaving from morning to night, you must feel tired.
- The note reminded me of my mother slaving from morning to night in my youth.
lighted [laɪt]: adj. a lighted window, room etc is bright because there is a light on inside明亮的
- I used to dream of buying an apartment with lighted bedroom.
- A lighted classroom still remains a dream for some children in remote villages.
- The only lighted room in the rural school was used as a place of worship for the natives.
convenient [kənˈviniənt]: adj. useful to you because it saves you time, or does not spoil your plans or cause you problems OPP inconvenient便利的
- Owing to convenient transportation, I and my wife chose the house.
- Your apartment is convenient which is only 5 miles from the supermarket.
- I want to lend a convenient apartment because I may be working from morning to night in our subsidiary.
loom [lum]: n. a machine on which thread is woven into cloth纺织机
- The factory was sacked by the local gangsters and the lost looms were worth 2000 dollars.
- The spread of this kind of looms in Europe marked the end of the old regime.
- This kind of looms spread through these merchants from Europe to India.
handicraft [ˈhændiˌkræft]: n. an activity such as sewing or making baskets, in which you use your hands in a skilful way to make things手工艺
- After retire, the headmaster devoted his life to the handicraft.
- It is a handicraft my parents presented with me on my birthday.
- The handicraft named after a famous scientist.
intensive [ɪnˈtensɪv] intensively: adj. involving a lot of activity, effort, or careful attention in a short period of time密集的
- After studying intensively, I got familiar with these ideas of philophes.
- The beggar knocked intensively at my door to ask for meals.
- The homework proved intensive, for I made progresses a great deal.
cottage [ˈkɑtɪdʒ]: n. a small house in the country村舍, 小别墅
- Our cottage must be the only modern house in the district.
- If the cottage had been burnt down, we wouldn't have lived in poverty.
- The cottage used as a place of worship has been burnt down by the natives.
manufacture [ˌmænjəˈfæktʃər]: v. to use machines to make goods or materials, usually in large numbers or amounts制造, 加工
- You'd better eat healthy food rather than eat manufactured food.
- The sacks were full of manufactured food.
- My wife complained that we had been eating manufactured food weeks after weeks.
impersonal [ɪmˈpɜrs(ə)nəl]: adj. not showing any feelings of sympathy, friendliness etc冷漠的,没人情味的
- The lawyer regarded as impersonal gave me a hand when I ran into serious trouble.
- My wife is so impersonal that she always borrows other money and never pays it back.
- His impersonal behavior in public led to the punishment from the mob of artisans.
intimacy [ˈɪntɪməsi]: n. a state of having a close personal relationship with someone亲密
- Because of the intimacy in my hometown, my father was reluctant to share with my house in the city.
- The intimacy between he and his girlfriend gave rise to the envy of his roommate.
- The intimacy of the marriage was damaged by his lies.
consume [kənˈsum] v. consumption:to use time, energy, goods etc ⇨ consumption消耗, 消费
- This kind of cars is said to consume less fuel on the highway.
- The paper we consume will be recycled by the manufacturer.
- The manufacturer consumes a lot of water, which led to the owner's death which met at the hands of the natives.
transport [trænsˈpɔrt] transportation: v.n. to take goods, people etc from one place to another in a vehicle传送, 运输
- It is no use transporting these silks to the area where the earthquake erupted.
- We were commissioned to transport these children to the bank of the river.
- Needless to say, the boy who played truant from school was transported to the border, not Paris which he dreamed of.
proletariat [ˌprəʊləˈterɪət]: n. the class of workers who own no property and work for wages, especially in factories, building things etc – used in ↑socialist writings无产阶级
- The meeting must extend more political rights and power to the proletariat.
- The prolatariat in the most wealthy country of the world still lives in poverty.
- Angered by the ignorance of the Parliament, the proletariat decided to go on a strike.
substantially [səbˈstænʃ(ə)li]: adv. very much or a lot SYN considerably充分地
- The birth rate in teenagers in this country has decreased substantially.
- It rains substantially, for the stream wound its way in the field which used to be dried.
- She took advantage of the invention substantially and made a profit.
--------------------
many of sth.: 许多xx
- There are many of passenagers who stands in the compartment of the train.
- The ideas of the Enlightenment haven't captured hearts and minds of many of Europeans.
- Many of pots in China are manufactured in this town.
a quantum leap in sth.: 某事物量子的突破
- A quantum leap in the treatment of cancer saved his life.
- A quantum leap in science led to the collapse of the papal power.
- Studying from morning to night, he made a quantum leap in English.
replace sth./sb. to do sth.: 代替某人/事物去做某事
- Mr. Fredo, don't worry. I'll replace you to send the lord of the rings to Mordor.
- He reckoned that his wife would replace him to keep his guilty soldier in hiding.
- The cat will replace me to accompany you for the rest of your life.
call for sth.: 要求某事
- His wife is always calling for the vocation abroad.
- The mob called for guns and ammunition to defend against the despotic policies.
- The cat may be calling for more snacks.
be appalled at sth.: 对某事感到震惊
- Appalled at the harsher working conditions, the journalist published an articles which captured the hearts of people around the world.
- Appalled at his failure, he followed in his father's footsteps. 
- Appalled at his manager's betray, he quited and found another job.
be critical of sth.: 批判某事
- My wife is always being critical of the enviorment around our cottage.
- The writer is critical of the curtain patterns, which led to a bitter quarrel.
- My boss is critical of the bugs we make which is impossible to avoid.
from morning to night: 从早到晚
- She has been working from morning to night.
- My father has been preparing dinner for us from morning to night.
- She has been seeking snails from morning to night and caught nothing.
at work: 在工作中
- The cooker is at work, don't touch it.
- The cooker is at work in difficult working conditions, this is why it has been burnt down.
- My grandmother used to be at work overnight in the field owing to the drought.
owe to sth./sb.: 由于某人/事物
- Owing to the loss of their members, the mob beat the Marquis to death and cut off his head.
- Owing to the despotic policies, the king had his head cut off.
- Owing to the salvation, the layman rest in peace.
coexistence of sth./sb.: 某人/事的共存
- The coexistence of the dog and chick in the closure proved difficult.
- The coexistence of my mother and my wife in the house exhausted me a great deal.
- The coexistence of my child and my cat in our apartment was rejected by my wife.
** sentence2
alter [ˈɔltər]: v. to change, or to make someone or something change改变
- Nothing can alter the fact that he loves going whoring.
- Running into the car accident, her face has altered beyond recognition.
- With her face altering during the operation, we couldn't identify her at the railway station.
principle [ˈprɪnsəp(ə)l]: n. a moral rule or belief about what is right and wrong, that influences how you behave法则, 原则, 原理
- The leading principle is that our soldiers should be equipped with guns and ammunition before the battle.
- The basic principle is that we should keep our princess in hiding.
- The basic principle is that you should make an apology after we quarrel.
somewhat [ˈsʌmwɑt]: adv. more than a little but not very稍微, 有点, 有些
- The mother of Fangsiyu is somewhat pretty, and you are somewhat funny.
- I must confess you are somewhat charming dressed in a full-length skirt.
- On changing into the overall, the worker looked somewhat cheerful.
coal [koʊl]: n. a hard black mineral which is dug out of the ground and burnt to produce heat煤
- The worker must have been trapped in the coal mine. 
- The coal mine is a place with harsher working conditions.
- They expected to dig up gold in the coal mine.
muscle [ˈmʌs(ə)l]: n. one of the pieces of flesh inside your body that you use in order to move, and that connect your bones together肌肉
- His house was equipped with those machines after he declared that he was going to strengthen his muscles.
- He was amazed to find that his muscle had been strengthed in the coal mine.
- The man is full of muscles and as strong as a horse.
maximize [ˈmæksɪˌmaɪz]: v. to increase something such as profit or income as much as possible OPP minimize最大化
- Mr. Leo goes out of his way to maximize his profits from these subscribers.
- The oven maximized the use of electrical power.
- The soldier stood to attention and maximized his honor to the general as much as he could.
artisan [ˈɑrtɪzən]: n. someone who does skilled work, making things with their hands SYN craftsman工匠, 技工
- The cornered artisan was forced to drink the urine of rats by these gangsters.
- The artisan in obscurity turned out to be our chief executive officer in our parent company.
- The artisan's apartment was used as a place of worship for the local Christianity.
slave [sleɪv]: v. to work very hard with little time to rest辛勤努力
- Slaving from morning to afternoon, he hasn't said a word.
- Slaving from morning to night, you must feel tired.
- The note reminded me of my mother slaving from morning to night in my youth.
lighted [laɪt]: adj. a lighted window, room etc is bright because there is a light on inside明亮的
- I used to dream of buying an apartment with a lighted bedroom.
- A lighted classroom still remains a dream for some children in remote villages.
- The only lighted room in the rural school was used as a place of worship for the natives.
convenient [kənˈviniənt]: adj. useful to you because it saves you time, or does not spoil your plans or cause you problems OPP inconvenient便利的
- Owing to convenient transportation, my wife and I chose the house.
- Your apartment is convenient which is only 5 miles from the supermarket.
- I want to rent a convenient apartment because I may be working from morning to night in our subsidiary.
loom [lum]: n. a machine on which thread is woven into cloth纺织机
- The factory was sacked by the local gangsters and the lost looms were worth 2000 dollars.
- The spread of this kind of looms in Europe marked the end of the old regime.
- This kind of looms spread through these merchants from Europe to India.
handicraft [ˈhændiˌkræft]: n. an activity such as sewing or making baskets, in which you use your hands in a skilful way to make things手工艺
- After retirement, the headmaster devoted his life to the handicraft.
- It is a handicraft my parents presented to me on my birthday.
- The handicraft is named after a famous scientist.
intensive [ɪnˈtensɪv] intensively: adj. involving a lot of activity, effort, or careful attention in a short period of time密集的
- After studying intensively, I got familiar with these ideas of philophes.
- The beggar knocked intensively at my door to ask for meals.
- The homework proved intensive, for I made progress a great deal.
cottage [ˈkɑtɪdʒ]: n. a small house in the country村舍, 小别墅
- Our cottage must be the only modern house in the district.
- If the cottage had been burnt down, we wouldn't have lived in poverty.
- The cottage used as a place of worship has been burnt down by the natives.
manufacture [ˌmænjəˈfæktʃər]: v. to use machines to make goods or materials, usually in large numbers or amounts制造, 加工
- You'd better eat healthy food rather than eat manufactured food.
- The sacks were full of manufactured food.
- My wife complained that we had been eating manufactured food week after week.
impersonal [ɪmˈpɜrs(ə)nəl]: adj. not showing any feelings of sympathy, friendliness etc冷漠的,没人情味的
- The lawyer regarded as impersonal gave me a hand when I ran into serious trouble.
- My wife is so impersonal that she always borrows other money and never pays it back.
- His impersonal behavior in public led to the punishment from the mob of artisans.
intimacy [ˈɪntɪməsi]: n. a state of having a close personal relationship with someone亲密
- Because of the intimacy in my hometown, my father was reluctant to share my house with me in the city.
- The intimacy between him and his girlfriend gave rise to the envy of his roommate.
- The intimacy of the marriage was damaged by his lies.
consume [kənˈsum] v. consumption:to use time, energy, goods etc ⇨ consumption消耗, 消费
- This kind of car is said to consume less fuel on the highway.
- The paper we consume will be recycled by the manufacturer.
- The manufacturer consumes a lot of water, which led to the owner's death which met at the hands of the natives.
transport [trænsˈpɔrt] transportation: v.n. to take goods, people etc from one place to another in a vehicle传送, 运输
- It is no use transporting these silks to the area where the earthquake erupted.
- We were commissioned to transport these children to the bank of the river.
- Needless to say, the boy who played truant from school was transported to the border, not Paris which he dreamed of.
proletariat [ˌprəʊləˈterɪət]: n. the class of workers who own no property and work for wages, especially in factories, building things etc – used in ↑socialist writings无产阶级
- The meeting must extend more political rights and power to the proletariat.
- The proletariat in the most wealthy country of the world still lives in poverty.
- Angered by the ignorance of the Parliament, the proletariat decided to go on a strike.
substantially [səbˈstænʃ(ə)li]: adv. very much or a lot SYN considerably充分地
- The birth rate in teenagers in this country has decreased substantially.
- It rains substantially, for the stream wound its way in the field which used to be dried.
- She took advantage of the invention substantially and made a profit.
--------------------
many of sth.: 许多xx
- There are many of passengers who stand in the compartment of the train.
- The ideas of the Enlightenment haven't captured the hearts and minds of many of Europeans.
- Many of pots in China are manufactured in this town.
a quantum leap in sth.: 某事物量子的突破
- A quantum leap in the treatment of cancer saved his life.
- A quantum leap in science led to the collapse of the papal power.
- Studying from morning to night, he made a quantum leap in English.
replace sth./sb. to do sth.: 代替某人/事物去做某事
- Mr. Fredo, don't worry. I'll replace you to send the lord of the Rings to Mordor.
- He reckoned that his wife would replace him to keep his guilty soldier in hiding.
- The cat will replace me to accompany you for the rest of your life.
call for sth.: 要求某事
- His wife is always calling for a vocation abroad.
- The mob called for guns and ammunition to defend against the despotic policies.
- The cat may be calling for more snacks.
be appalled at sth.: 对某事感到震惊
- Appalled at the harsher working conditions, the journalist published an article that captured the hearts of people around the world.
- Appalled at his failure, he followed in his father's footsteps. 
- Appalled at his manager's betrayal, he quit and found another job.
be critical of sth.: 批判某事
- My wife is always being critical of the envivorment around our cottage.
- The writer is critical of the curtain patterns, which led to a bitter quarrel.
- My boss is critical of the bugs we make which is impossible to avoid.
from morning to night: 从早到晚
- She has been working from morning to night.
- My father has been preparing dinner for us from morning to night.
- She has been seeking snails from morning to night and caught nothing.
at work: 在工作中
- The cooker is at work, don't touch it.
- The cooker is at work in difficult working conditions, this is why it has been burnt down.
- My grandmother used to be at work overnight in the field owing to the drought.
owe to sth./sb.: 由于某人/事物
- Owing to the loss of their members, the mob beat the Marquis to death and cut off his head.
- Owing to the despotic policies, the king had his head cut off.
- Owing to the salvation, the layman rest in peace.
coexistence of sth./sb.: 某人/事的共存
- The coexistence of the dog and chick in the closure proved difficult.
- The coexistence of my mother and my wife in the house exhausted me a great deal.
- The coexistence of my child and my cat in our apartment was rejected by my wife.

