#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 21 A meeting of the Congress of Vienna
#+begin_verse
In September 1814,
	hundreds of foreigners began to converge on Vienna, the capital city of the Austrian Empire.
Many were members of European royalty---kings, princes, archdukes, and their wives---
	accompanied by their diplomatic advisers and scores of servants.
Their congenial host was the Austrian emperor Francis I,
	who never tired of regaling Vienna's guests with concerts,
		glittering balls, sumptuous feasts, and hunting parties.
One participant remembered, 'Eating, fireworks, public illuminations.
For eight or ten days, I haven't been able to work at all. What a life!'
Of course, not every waking hour was spent in pleasure during this gathering of notables,
	known to history as the Congress of Vienna.
These people were also representatives of all the states that had fought Napoleon,
	and their real business was to arrange a final peace settlement after almost a decade of war.
On June 8, 1815, they completed their task.

The forces of upheaval unleashed during the French revolutionary and Napoleonic wars
		were temporarily quieted in 1815
	as rulers sought to restore stability
		by reestablishing much of the old order to a Europe weary of war.
Kings, landed aristocrats, and bureaucratic elites regained their control over domestic governments,
	while internationally the forces of conservatism tried to maintain the new status quo;
		some states even used military force
			to intervene in the internal affairs of other countries in their desire to crush revolutions.

But the Western world had been changed, and it would not readily go back to the old system.
New ideologies, especially liberalism and nationalism,
		both products of the revolutionary upheaval initiated in France,
	had become too powerful to be contained.
Not content with the status quo,
	the forces of change gave rise first to the revolts and revolutions
			that periodically shook Europe in the 1820s and 1830s
		and then to the widespread revolutions of 1848.
Some of the revolutions and revolutionaries were successful; most were not.
Although the old order usually appeared to have prevailed,
	by 1850 it was apparent that its days were numbered.
This perception was reinforced by the changes wrought by the Industrial Revolution.
Together the forces unleashed by the French Revolution and the Industrial Revolution
	made it impossible to turn back.
Nevertheless,
	although these two revolutions initiated what historians like to call the modern European world,
		remnants of the old persisted in the midst of the new.
#+end_verse
** expression
convergent [kən'vɜrdʒənt] convergent: v.adj. to come from different directions and meet at the spoint to become one thing会聚
diplomatic [ˌdɪpləˈmætɪk]: adj. relating to or involving the work of diplomats外交的
adviser [ədˈvaɪzər]: n. someone whose job is to give advice because they know a lot about a subject, especially in business, law, or politics顾问
congenial [kənˈdʒiniəl]: adj. pleasant in a way that makes you feel comfortable and relaxed性格相似的, 适意的
concert [ˈkɑnsərt]: n. a performance given by musicians or singers音乐会
glitter [ˈɡlɪtər]: v. to shine brightly with flashing points of light SYN sparkle闪烁
sumptuous [ˈsʌmptʃuəs]: adj. very impressive and expensive奢侈的, 华丽的
participant [pɑrˈtɪsɪpənt]: n. someone who is taking part in an activity or event参与者
illuminations [ɪˌlumɪˈneɪʃ(ə)n]: n. illuminations [plural] British English a show of coloured lights used to make a town bright and colourful灯彩
notables [ˈnoʊtəb(ə)lz]: n. important or famous people名人
representative [ˌreprɪˈzentətɪv]: n. someone who has been chosen to speak, vote, or make decisions for someone else SYN delegate代表
unleash [ʌnˈliʃ]: v. to suddenly let a strong force, feeling etc have its full effect释放
readily [ˈredɪli]: adv. quickly, willingly, and without complaining乐意地, 欣然
ideology [ˌɪdiˈɑlədʒi]: n. a set of beliefs on which a political or economic system is based, or which strongly influence the way people behave ⇨ philosophy意识形态
liberal [ˈlɪb(ə)rəl] liberalism: n.n. supporting or allowing gradual political and social changes OPP conservative自由主义者
nationalist [ˈnæʃən(ə)lɪst] nationalism: n.n. someone who is involved in trying to gain or keep political independence for their country and people国家主义者, 民族主义者
numbered [ˈnʌmbər]: adj. 有限的, 时日无多的
reinforce [ˌriɪnˈfɔrs]: v. to give support to an opinion, idea, or feeling, and make it stronger加强
--------------------
scores of sb./sth.: 许多的...
regale sb. with sth.: 用某物款待某人
sb's real business is to do sth.: 某人真正要做的事情是
arrange a peace settlement: 达成和平协议
be weary of sth.: 对某事感到厌倦
regain sb's control over sth.: 重获对某事的控股权
maintain the new status quo: 维持新的现状
be content with sth.: 对某事满足
intervene in sth.: 干涉/干预某事
in sb's desire to do sth.: 由于某人渴望做某事
appear to have done sth.: 似乎已经做了某事
remnants of sth.: 剩余部分
** sentence
convergent [kən'vɜrdʒənt] convergent: v.adj. to come from different directions and meet at the spoint to become one thing会聚
- The mob of thousands of peasants converge in the tennis court.
- The water converged winding its way across the field.
- So long as the police arrive on the scene, the gangsters will converge to fight against them.
diplomatic [ˌdɪpləˈmætɪk]: adj. relating to or involving the work of diplomats外交的
- The diplomatic adviser was sentenced to death while counting the number of ants in the cell. 
- The country was initially so weak that the diplomatic work was in difficulty.
- The diplomatic work ran into serious trouble, which terrorized the new-born revolution.
adviser [ədˈvaɪzər]: n. someone whose job is to give advice because they know a lot about a subject, especially in business, law, or politics顾问
- As a result of the lack of profit, the adviser got fired.
- The adviser sneaked into the CEO's office and was sentenced to death.
- The adviser stemming from a peasant family came into his own.
congenial [kənˈdʒiniəl]: adj. pleasant in a way that makes you feel comfortable and relaxed性格相似的, 适意的
- I was relieved to hear that our new superior was congenial.
- All students in our class made progress in last test under the new congenial teacher.
- The congenial teacher decided to devote himself to gardening after he retired.
concert [ˈkɑnsərt]: n. a performance given by musicians or singers音乐会
- These days, concerts of pop singers become popular with these young people from rural villages in the city.
- The chief executive officer planned out the concert to last detail.
- A slip of the tongue in the concert did give us a surprise.
glitter [ˈɡlɪtər]: v. to shine brightly with flashing points of light SYN sparkle闪烁
- If the indicator is glittering, you can connect your phone to the bluetooth earphone.
- The power hasn't been run out of, for the light is still glittering.
- When she opened the box, I had a glimpse of the glittering crystal ball.
sumptuous [ˈsʌmptʃuəs]: adj. very impressive and expensive奢侈的, 华丽的
- The sumptuous stuffs to which the prizefighter got accustomed no longer made him happy.
- Beyond doubts, he is willing to sacrifice his savings for a sumptuous house in the inter-ring of the city.
- I dream of having a house with a sumptuous garden in suburbs of the city.
participant [pɑrˈtɪsɪpənt]: n. someone who is taking part in an activity or event参与者
- The partcipants regained their control over the city, which led to other revolts in other cities.
- The participants urged the king to restore the old regime.
- The participants should have had their heads cut at the village fair. 
illuminations [ɪˌlumɪˈneɪʃ(ə)n]: n. illuminations [plural] British English a show of coloured lights used to make a town bright and colourful灯彩
- The sumptuous illuminations were used to be in memory of those who were killed in an action during the war.
- The sumptuous illuminations gave us a great sense of happiness in the celebration.
- Our cat appeared to have admired the sumptuous illuminations.
notables [ˈnoʊtəb(ə)lz]: n. important or famous people名人
- This guy must be a notable, for he sang so well last night at the pub.
- Such is human nature, that notables are often willing to sacrifice money for the rise in status.
- There are notables attending these looms in the exhibition.
representative [ˌreprɪˈzentətɪv]: n. someone who has been chosen to speak, vote, or make decisions for someone else SYN delegate代表
- I used to be a representative of my school taking part in the competition. 
- After these representatives discussed the settlement, we would have a quantum leap in our working condition.
- The representatives are reluctant to enter for the meeting which will be in the palace.
unleash [ʌnˈliʃ]: v. to suddenly let a strong force, feeling etc have its full effect释放
- Unleashing his dog, he instructed his dog to bite me.
- The dog will have a greater freedom, for they are unleashed and wander outside the enclosure.
- The French revolution exerted a tremendous influence on countries in Europe, for it unleashed the force for change.
readily [ˈredɪli]: adv. quickly, willingly, and without complaining乐意地, 欣然
- Imagine his dismay when he found that his wife readily cheated on him while runing into a handsome man.
- His inferior readily replaced him to complete the task.
- Critical of the treatment of pregant women in factories, he readily drew up the petition.
ideology [ˌɪdiˈɑlədʒi]: n. a set of beliefs on which a political or economic system is based, or which strongly influence the way people behave ⇨ philosophy意识形态
- Fear that the new ideology based on individualism will destory old regime, the monarch established laws prohibiting his treatises. 
- The pope denounced his book full of a new ideology which was guilty of heresy.
- The widespread of the new ideology gave rise to a new party stemming from the peasants.
liberal [ˈlɪb(ə)rəl] liberalism: n.n. supporting or allowing gradual political and social changes OPP conservative自由主义者
- The liberals composed of middle classes played a primary role in the French revolution.
- In order to restore old regime, the monarch exiled those liberals abroad.
- The host of the salon charmed many of philosophes, including liberals, and nationalists.
nationalist [ˈnæʃən(ə)lɪst] nationalism: n.n. someone who is involved in trying to gain or keep political independence for their country and people国家主义者, 民族主义者
- It was the nationalists who played a crucial role in the revolution of 1830. 
- Crossing the Pass, these nationalists received a warm welcome at St. Bernard Monastery.
- Holding a grudge against those nationalists, the king sentenced them to hang as long as he came to power.
numbered [ˈnʌmbərd]: adj. 有限的, 时日无多的
- Aware that my life was numbered, I dedicated all my properties to my wife.
- I realized that my cat's life was numbered  while she was walking clumsily toward me.
- Because of the numbered food, the mixture of the urine of rats and maggots was regarded as cake.
reinforce [ˌriɪnˈfɔrs]: v. to give support to an opinion, idea, or feeling, and make it stronger加强
- He was praised by his boss in public, so his status in the company was reinforced.
- The village reinforced their fence fearing of the attacks of wolves at night.
- The emergence of new ideology caused our king to reinforce censorships.
--------------------
scores of sb./sth.: 许多的...
- Guilt of possessing scores of fields, the abbot was beaten to death at the hands of local village.
- Scores of royal servants met their death at the hands of mobs of peasants.
- Scores of cats fell off high-rise windowsill not dieding from shock or injuries.
regale sb. with sth.: 用某物款待某人
- In one sense, you have regaled your parent with good grades which they expected.
- Regaling his friends with funny stories, he did plan out the party to the last detail.
- It occurred to me that people in some remote villages regaled their guest with their wives.
sb's real business is to do sth.: 某人真正要做的事情是
- Obviously, their real business is to reach agreement about better working condition and higher pay.
- It occurred to me that my cat's real business was to steal my barbecue when he sneaked into the kitchen.
- The lawyer's real business is to prove our testimony to be a lie.
arrange a peace settlement: 达成和平协议
- A peace settlement should be arranged in the meeting after decades of war.
- Although they arranged a peace settlement, the Asiatic nomads continued to push their way westward through the plain.
- After the peace settlement arranged, a country who started a war would be attacked by all other countries.
be weary of sth.: 对某事感到厌倦
- Weary of being homeless, the beggar sought for a apprentice to the baker.
- Weary of criticism of his superior, he quit his job.
- Weary of home sick, he moved to Paris where he had spent a lot of time with his children.
regain sb's control over sth.: 重获对某事的控股权
- Making a profit, our CEO regained his control over these subsidiary.
- Our family ran into serious trouble and my mother restored it to new glory, during which she regain her control over the finance.
- Promising to restore the corporation to new glory, he regained his control over these subsidiaries..
maintain the new status quo: 维持新的现状
- If a sophisticated police had arrived on the scene, he would had maintained the status quo.
- You're better maintain the status quo, or I would reduce your pocket money this month.
- I prefer to change rather than maintain the status quo.
be content with sth.: 对某事满足
- Not content with her husband, she was due to poison him.
- Not content with the new status, she sold her house and moved to Paris.
- Not content with the philosophes, the hostess of salon ceased to offer them money.
intervene in sth.: 干涉/干预某事
- You're intervening in my domestic affairs.
- The spokeswoman denounced that the US was intervening in other countries' domestic affairs.
- You needn't have intervened in their quarrel, it's none of your business.
in sb's desire to do sth.: 由于某人渴望做某事
- He would crucify us all in his desire to find the strait.
- The nun mashed the herb in her desire to save my life.
- He regaled me with his wife and daughter in his desire to gain his control over the company.
appear to have done sth.: 似乎已经做了某事
- Our cat appeared to have fallen off the windowsill.
- Your sister appeared to have smashed the article to pieces.
- My wife appeared to have washed the dishes.
remnants of sth.: 剩余部分
- Remnants of the bomber is worth rescuing now.
- Remnants of drugs may be 10000 dollars worth.
- After the revolution, remnants of monarchs was eager to restore it to new glory.
** sentence2
convergent [kən'vɜrdʒənt] convergent: v.adj. to come from different directions and meet at the spoint to become one thing会聚
- The mob of thousands of peasants converge on the tennis court.
- The water converged winding its way across the field.
- So long as the police arrive on the scene, the gangsters will converge to fight against them.
diplomatic [ˌdɪpləˈmætɪk]: adj. relating to or involving the work of diplomats外交的
- The diplomatic adviser was sentenced to death while counting the number of ants in the cell. 
- The country was initially so weak that diplomatic work was in difficulty.
- The diplomatic work ran into serious trouble, which terrorized the newborn revolution.
adviser [ədˈvaɪzər]: n. someone whose job is to give advice because they know a lot about a subject, especially in business, law, or politics顾问
- As a result of the lack of profit, the adviser got fired.
- The adviser sneaked into the CEO's office and was sentenced to death.
- The adviser stemming from a peasant family came into his own.
congenial [kənˈdʒiniəl]: adj. pleasant in a way that makes you feel comfortable and relaxed性格相似的, 适意的
- I was relieved to hear that our new superior was congenial.
- All students in our class made progress in the last test under the new congenial teacher.
- The congenial teacher decided to devote himself to gardening after he retired.
concert [ˈkɑnsərt]: n. a performance given by musicians or singers音乐会
- These days, concerts of pop singers become popular with young people from rural villages in the city.
- The chief executive officer planned out the concert to the last detail.
- A slip of the tongue at the concert did give us a surprise.
glitter [ˈɡlɪtər]: v. to shine brightly with flashing points of light SYN sparkle闪烁
- If the indicator is glittering, you can connect your phone to the Bluetooth earphone.
- The power hasn't been used up, for the light is still glittering.
- When she opened the box, I had a glimpse of the glittering crystal ball.
sumptuous [ˈsʌmptʃuəs]: adj. very impressive and expensive奢侈的, 华丽的
- The sumptuous stuff to which the prizefighter got accustomed no longer made him happy.
- Beyond doubt, he is willing to sacrifice his savings for a sumptuous house in the inter-ring of the city.
- I dream of having a house with a sumptuous garden in the suburbs of the city.
participant [pɑrˈtɪsɪpənt]: n. someone who is taking part in an activity or event参与者
- The participants regained their control over the city, which led to other revolts in other cities.
- The participants urged the king to restore the old regime.
- The participants should have had their heads cut at the village fair. 
illuminations [ɪˌlumɪˈneɪʃ(ə)n]: n. illuminations [plural] British English a show of coloured lights used to make a town bright and colourful灯彩
- The sumptuous illuminations were used to be in memory of those who were killed in an action during the war.
- The sumptuous illuminations gave us a great sense of happiness in the celebration.
- Our cat appeared to have admired the sumptuous illuminations.
notables [ˈnoʊtəb(ə)lz]: n. important or famous people名人
- This guy must be one of the notables, for he sang so well last night at the pub.
- Such is human nature, that notables are often willing to sacrifice money for the rise in status.
- There are notables attending these looms in the exhibition.
representative [ˌreprɪˈzentətɪv]: n. someone who has been chosen to speak, vote, or make decisions for someone else SYN delegate代表
- I used to be a representative of my school taking part in the competition. 
- After these representatives discussed the settlement, we would have a quantum leap in our working conditions.
- The representatives are reluctant to enter for the meeting which will be in the palace.
unleash [ʌnˈliʃ]: v. to suddenly let a strong force, feeling etc have its full effect释放
- Unleashing his dog, he instructed his dog to bite me.
- The dog will have greater freedom, for they are unleashed and wander outside the enclosure.
- The French Revolution exerted a tremendous influence on countries in Europe, for it unleashed the force for change.
readily [ˈredɪli]: adv. quickly, willingly, and without complaining乐意地, 欣然
- Imagine his dismay when he found that his wife readily cheated on him while running into a handsome man.
- His inferior readily replaced him to complete the task.
- Critical of the treatment of pregnant women in factories, he readily drew up the petition.
ideology [ˌɪdiˈɑlədʒi]: n. a set of beliefs on which a political or economic system is based, or which strongly influence the way people behave ⇨ philosophy意识形态
- Fear that the new ideology based on individualism will destroy the old regime, the monarch established laws prohibiting his treatises. 
- The pope denounced his book full of a new ideology which was guilty of heresy.
- The widespread of the new ideology gave rise to a new party stemming from the peasants.
liberal [ˈlɪb(ə)rəl] liberalism: n.n. supporting or allowing gradual political and social changes OPP conservative自由主义者
- The liberals composed of the middle classes played a primary role in the French Revolution.
- In order to restore the old regime, the monarch exiled those liberals abroad.
- The host of the salon charmed many philosophes, including liberals, and nationalists.
nationalist [ˈnæʃən(ə)lɪst] nationalism: n.n. someone who is involved in trying to gain or keep political independence for their country and people国家主义者, 民族主义者
- It was the nationalists who played a crucial role in the revolution of 1830. 
- Crossing the Pass, these nationalists received a warm welcome at St. Bernard Monastery.
- Holding a grudge against those nationalists, the king sentenced them to hang as long as he came to power.
numbered [ˈnʌmbərd]: adj. 有限的, 时日无多的
- Aware that my life was numbered, I dedicated all my properties to my wife.
- I realized that my cat's life was numbered while she was walking clumsily toward me.
- Because of the numbered food, the mixture of the urine of rats and maggots was regarded as cake.
reinforce [ˌriɪnˈfɔrs]: v. to give support to an opinion, idea, or feeling, and make it stronger加强
- He was praised by his boss in public, so his status in the company was reinforced.
- The village reinforced their fence fearing the attacks of wolves at night.
- The emergence of a new ideology caused our king to reinforce censorship.
--------------------
scores of sb./sth.: 许多的...
- Guilty of possessing scores of fields, the abbot was beaten to death at the hands of villagers.
- Scores of royal servants met their death at the hands of mobs of peasants.
- Scores of cats fell off high-rise windowsill not dying from shock or injuries.
regale sb. with sth.: 用某物款待某人
- In one sense, you have regaled your parent with good grades which they expected.
- Regaling his friends with funny stories, he did plan out the party to the last detail.
- It occurred to me that people in some remote villages regaled their guests with their wives.
sb's real business is to do sth.: 某人真正要做的事情是
- Obviously, their real business is to reach an agreement about better working conditions and higher pay.
- It occurred to me that my cat's real business was to steal my barbecue when he sneaked into the kitchen.
- The lawyer's real business is to prove our testimony to be a lie.
arrange a peace settlement: 达成和平协议
- A peace settlement should be arranged in the meeting after decades of war.
- Although they arranged a peace settlement, the Asiatic nomads continued to push their way westward through the plain.
- After the peace settlement was arranged, a country that started a war would be attacked by all other countries.
be weary of sth.: 对某事感到厌倦
- Weary of being homeless, the beggar sought for an apprentice to the baker.
- Weary of criticism of his superior, he quit his job.
- Weary of homesick, he moved to Paris where he had spent a lot of time with his children.
regain sb's control over sth.: 重获对某事的控股权
- Making a profit, our CEO regained his control over these subsidiaries.
- Our family ran into serious trouble and my mother restored it to new glory, during which she regained her control over the finances.
- Promising to restore the corporation to new glory, he regained his control over these subsidiaries.
maintain the new status quo: 维持新的现状
- If a sophisticated police had arrived on the scene, he would have maintained the status quo.
- You'd better maintain the status quo, or I would reduce your pocket money this month.
- I prefer to change rather than maintain the status quo.
be content with sth.: 对某事满足
- Not content with her husband, she was due to poison him.
- Not content with the new status, she sold her house and moved to Paris.
- Not content with the philosophes, the hostess of the salon ceased to offer them money.
intervene in sth.: 干涉/干预某事
- You're intervening in my domestic affairs.
- The spokeswoman denounced that the US was intervening in other countries' domestic affairs.
- You needn't have intervened in their quarrel, it's none of your business.
in sb's desire to do sth.: 由于某人渴望做某事
- He would crucify us all in his desire to find the strait.
- The nun mashed the herb in her desire to save my life.
- He regaled me with his wife and daughter in his desire to gain control over the company.
appear to have done sth.: 似乎已经做了某事
- Our cat appeared to have fallen off the windowsill.
- Your sister appeared to have smashed the article to pieces.
- My wife appeared to have washed the dishes.
remnants of sth.: 剩余部分
- Remnants of the bomber are worth rescuing now.
- Remnants of drugs may be 10000 dollars worth.
- After the revolution, remnants of monarchs were eager to restore it to new glory.
** summary
In September 1814, many members of European royalty began to converge on Vienna
	accompanied by their diplomatic advisers and scores of servants.
Their congenial host, Francis I,
	regaled them with concerts, glittering balls, sumptuous feasts, and hunting parties.
However, not every working hours were spent in pleasure,
	and as the representatives of all the states that had fought Napoleon
		their real business was to arrange a final peace settlement.
The gathering of the notables was known to history as Congress of Vienna.
In 1815, kings, landed aristocrats, and bureaucratic elites
		regained their control over domestic governments,
	while some states used military forces to crush revolutions in other coutries.
New ideaologies, especially liberalism and nationalism, were too powerful to be contained.
They gave rise first to periodically revolts and revolutions in the 1820s and 1830s
	and then to widespread revolutions of 1848.
It was apparent that the days of the old order was numbered.
These two revolutions initiated what historians call the modern European world.
** summary2
In September 1814, many members of European royalty began to converge in Vienna
	accompanied by their diplomatic advisers and scores of servants.
Their congenial host, Francis I,
	regaled them with concerts, glittering balls, sumptuous feasts, and hunting parties.
However, not every warking hour was spent in pleasure,
	and as the representatives of all the states that had fought Napoleon
		their real business was to arrange a final peace settlement.
The gathering of the notables was known to history as the Congress of Vienna.
In 1815, kings, landed aristocrats, and bureaucratic elites
		regained their control over domestic governments,
	while some states used military forces to crush revolutions in other countries.
New ideologies, especially liberalism and nationalism, were too powerful to be contained.
They gave rise first to periodic revolts and revolutions in the 1820s and 1830s
	and then to the widespread revolutions of 1848.
It was apparent that the day of the old order was numbered.
These two revolutions initiated what historians call the modern European world.
