#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 24 Police stop women from entering Buckingham Palace to present a petition to the king
#+begin_verse
Many Europeans after 1894 continued to believe they lived in an era of material and human progress.
For some, however, progress entailed much struggle.
Emmeline Pankhurst, who became the leader of the women's suffrage movement in Britain,
	said that her determination to fight for women's rights stemmed from a childhood memory:
	My father bent over me, shielding the candle flame with his big hand,
		and I heard him say, somewhat sadly, 'What a pity she wasn't born a lad.'
Eventually, Emmeline Pankhurst and her daughters marched and fought for women's right to vote.
The struggle was often violent:
	'They came in bruised, hatless, faces scratched, eyes swollen, noses bleeding,'
	one of the Pankhurst daughters recalled.
Arrested and jailed in 1908, Pankhurst informed her judges,
	'If you had the power to send us to prison,
			not for six months, but for six years, or for our lives,
		the Government must not think they could stop this agitation.
It would go on!'
It did go on, and women in Britain did eventually receive the right to vote;
	to some, this was yet another confirmation of Europe's progress.

But the period after 1894 was not just a time of progress;
	it was also a time of great tension
		as imperialist adventures, international rivalries,
			and cultural uncertainties disturbed the apparent calm.
After 1880, Europeans engaged in a great race for colonies around the world.
This competition for lands abroad greatly intensified existing antagonisms among European states.

Ultimately, Europeans proved incapable of finding constructive ways
	to cope with their international rivalries.
The development of two large alliance systems---the Triple Alliance and the Triple Entente---
		may have helped preserve peace for a time,
	but eventually the alliances made it easier for the European nations
		to be drawn into the catastrophic carnage of World War I.

The cultural life of Europe in the decades before 1914 reflects similar dynamic tensions.
The advent of mass education produced better-informed citizens
	but also made it easier for governments
		to stir up the masses by nationalistic appeals through the new mass journalism.
At the same time, despite the appearance of progress,
	European philosophers, writers, and artists were advancing cultural expressions
		that questioned traditional ideas and values and undermined public confidence.
Leading up to 1914,
	many intellectuals had a sense of unease about the direction in which society was heading
		and a feeling of imminent catastrophe.
They proved remarkably prophetic.
#+end_verse
** expression
petition [pəˈtɪʃ(ə)n]: n. a written request signed by a lot of people, asking someone in authority to do something or change something请愿
entail [ɪnˈteɪl]: v. to involve something as a necessary part or result使必需, 使蒙受
suffrage [ˈsʌfrɪdʒ]: n. the right to vote in national elections
shield [ʃild]: v. to protect someone or something from being harmed or damaged保护, 防护
lad [læd]: n. old-fashioned informal a boy or young man ⇨ lass少年
bruise [bruz]: v. if part of your body bruises, or if you bruise part of your body, it gets hit or hurt and a bruise appears瘀伤
hatless ['hætlɪs]: adj. 不戴帽子的
scratch [skrætʃ]: v. to rub your skin with your nails because it feels uncomfortable ⇨ itch搔, 抓
swollen [ˈswoʊlən]: adj. a part of your body that is swollen is bigger than usual, especially because you are ill or injured肿胀的
bleeding [ˈblidɪŋ]: adj. an offensive way of emphasizing something when you are angry流血的
recall [ˈriˌkɔl]: v. to remember a particular fact, event, or situation from the past回想
agitation [ˌædʒɪˈteɪʃ(ə)n]: n. public argument or action for social or political change请求变革
imperial [ɪmˈpɪriəl] imperialist: n.n. relating to an ↑empire or to the person who rules it皇帝的
uncertainty [ʌnˈsɜrt(ə)nti]: n. when you feel doubt about what will happen不确定
intensify [ɪnˈtensɪˌfaɪ]: v. to increase in degree or strength, or to make something do this加强
antagonism [ænˈtæɡəˌnɪzəm]: n. hatred between people or groups of people SYN hostility对抗
alliance [əˈlaɪəns]: n. an arrangement in which two or more countries, groups etc agree to work together to try to change or achieve something联盟, 联合
triple [ˈtrɪp(ə)l]: adj. having three parts or involving three groups, people, events etc ⇨ double三倍的
carnage [ˈkɑrnɪdʒ]: n. when a lot of people are killed and injured, especially in a war残杀, 大屠杀
advance [ədˈvæns]: v. if scientific or technical knowledge advances, or if something advances it, it develops and improves推进
imminent [ˈɪmɪnənt]: adj. an event that is imminent, especially an unpleasant one, will happen very soon即将来临的, 逼近的
prophetic [prəˈfetɪk]: adj. correctly saying what will happen in the future预言的
--------------------
bent over sb.: 俯身于某人
receive the right to do sth.: 获取权利去做某事
prove incapable of doing sth.: 证明不足以做某事
for a time: 暂时地
be drawn into sth.: 被卷入到某事
The advent of sth.: 某事物的出现
stir up sb.: 煽动某人
Leading up to 1914: 直到1914
unease about sth.: 对某事的不安
** sentence
petition [pəˈtɪʃ(ə)n]: n. a written request signed by a lot of people, asking someone in authority to do something or change something请愿
- The woman outside the palace wanted to present a petition to you, majesty.
- Despite of the petition of thousands of peasants, the king still levied taxes without parliament.
- He insisted the woman was guilty of the petition.
entail [ɪnˈteɪl]: v. to involve something as a necessary part or result使必需, 使蒙受
- Because my parents got divorce and my mother left me in my childhood, I entailed many struggles when I askes for the rights to do something.
- Entailing many struggles, he insisted that his son should go to school in town.
- Entailing many struggles, he brought his team to win the world champion.
suffrage [ˈsʌfrɪdʒ]: n. the right to vote in national elections
- Out of the disgust of a woman who asked for suffrage: we have received unfair treatments in domestic affairs.
- The mob who asked for suffrage was streaming towards the royal armory.
- Because of the lack of evidence, I gave up the suffrage in the court.
shield [ʃild]: v. to protect someone or something from being harmed or damaged保护, 防护
- The special iron board was used to shield you from arrows when you fought for your family.
- Shielding candle flame from my cat, my left hand got injuried.
- Shielding gangsters from his daughter, he was put out of business.
lad [læd]: n. old-fashioned informal a boy or young man ⇨ lass少年
- The lad had an opportunity to meet our majesty.
- The lad, on the other hand, is guilty of sneaking into the palace.
- It seems that our majesty is quite tolerant of the lad who defends against the Asiatic nomads.
bruise [bruz]: v. if part of your body bruises, or if you bruise part of your body, it gets hit or hurt and a bruise appears瘀伤
- If you bruise in an action, you must eat the pill, even thought it has some side effect.
- When she found her child bruise, she got very angry.
- If your body bruises, you must try our drug which works a great deal.
hatless ['hætlɪs]: adj. 不戴帽子的
- The lad noticed a hatless girl drinking a special kind of drug.
- I'd rather be hatless than wear a hat like a lighthouse.
- The clerk doesn't like the way she dressed, especially hatless.
scratch [skrætʃ]: v. to rub your skin with your nails because it feels uncomfortable ⇨ itch搔, 抓
- Your dog pounced on me and then scratched my hands.
- I was made by gangsters to scratch her face, I confessed to my god father.
- Envious of her friend's perfect face, she insidiously poisoned her friend through her friend's daily drink.
swollen [ˈswoʊlən]: adj. a part of your body that is swollen is bigger than usual, especially because you are ill or injured肿胀的
- Our cat's paw is swollen, she must have scratched the beehive in the ceiling.
- Hiting the surface of the desk dramatically, his hands must have been swollen.
- Your son's face is swollen because your so-called friend tried to beat him to death.
bleeding [ˈblidɪŋ]: adj. an offensive way of emphasizing something when you are angry流血的
- He tried to keep his bleeding hand from his daughter's face.
- On arriving on the scene, the police found a broken bleeding arm.
- He lost no time in coping with his bleeding legs.
recall [ˈriˌkɔl]: v. to remember a particular fact, event, or situation from the past回想
- It's unpleasant to recall something bad in my childhood.
- When she tried to recall the answers, she heard strange notes of music.
- You must recall the phone number which she provided you yesterday.
agitation [ˌædʒɪˈteɪʃ(ə)n]: n. public argument or action for social or political change请求变革
- Fearing of the agitation, the authorities purchases a special kind of seeds which would take root quickly.
- Fearing of the agitation, the authorities lost no time in keeping the leaders in prison.
- The agitation manifested itself in more frequent strikes in the coal mine.
imperial [ɪmˈpɪriəl] imperialist: n.n. relating to an ↑empire or to the person who rules it皇帝的
- The authoritarian government often condemns other countries as imperialists.
- The determination of imperialist to destory our republic government never dies.
- The imperial government formed vast armies by conscription.
uncertainty [ʌnˈsɜrt(ə)nti]: n. when you feel doubt about what will happen不确定
- If you don't plan the coronation to the last detail, it will still have uncertainties. 
- Because of the uncertainties of mob, the king ordered his men to kill them as quickly as possible.
- Because of the uncertainties of the succession to the throne, the ministers haven't decided to support whom.
intensify [ɪnˈtensɪˌfaɪ]: v. to increase in degree or strength, or to make something do this加强
- When I was left doing homework, my loneliness intensified.
- Because of her intensified lonliness, she had a habit of cheating on her husband.
- The communication between me and my aunt intensify, which gave me a sense of happiness.
antagonism [ænˈtæɡəˌnɪzəm]: n. hatred between people or groups of people SYN hostility对抗
- The antagonism between Muslims and Christians continued into the twentith century.
- The antagonism between him and his old brother led to a bitterly fight.
- The antagonism between the two villages caused a series of tragics.
alliance [əˈlaɪəns]: n. an arrangement in which two or more countries, groups etc agree to work together to try to change or achieve something联盟, 联合
- As long as our member was attacked, we would provide weapon for it, the spokesman of the alliance declaimed.
- The spokesman of the alliance was assassinated in the course of his house.
- The countries of the alliance will be exempt from import duty.
triple [ˈtrɪp(ə)l]: adj. having three parts or involving three groups, people, events etc ⇨ double三倍的
- If you delayed in relieving the kid, you would obtain triple ransom.
- Exasperated by the relation's calling the police, the kidnapper asked for triple ransom.
- Exasperated by the increased import duty of China, the president asked for triple import duty.
carnage [ˈkɑrnɪdʒ]: n. when a lot of people are killed and injured, especially in a war残杀, 大屠杀
- The man who survived carnage is receiving a treatment in the seaside resort. 
- Fearing of carnage, the king decided to arrange a peace settlement as soon as possible.
- According to the coverage, there must be at least ten thousand people killed in the carnage.
advance [ədˈvæns]: v. if scientific or technical knowledge advances, or if something advances it, it develops and improves推进
- Some scientists are advancing the search for the cat-like animal.
- Our reformations must be advanced in our army which spent two-third of our taxes every year.
- Advancing reformations in armies, he was hated by some landed-aristocratics.
imminent [ˈɪmɪnənt]: adj. an event that is imminent, especially an unpleasant one, will happen very soon即将来临的, 逼近的
- I determined to face the imminent challenges from new philosophes.
- The imminent catastrophe gave our government a shock.
- The student pestered his teacher about the imminent gift.
prophetic [prəˈfetɪk]: adj. correctly saying what will happen in the future预言的
- The prophetic words was not taken seriously, which led to a series of troubles.
- The prophetic warning was regarded as a joke, in one sense.
- I figured out that our majesty admired your for your prophetic warning.
--------------------
bend over sb.: 俯身于某人
- Bending over me, my father touched my head and asked me to study hard.
- Bending over my classmate, Mr. Leo threatened that if he didn't complete his task, he would get fired.
- Bending over my cat, I heard a strange noise from his stomach.
receive the right to do sth.: 获取权利去做某事
- I never receive the right to arrange my room.
- She must receive the right to study abroad.
- She can't receive the right to study abroad.
prove incapable of doing sth.: 证明不足以做某事
- I proved incapable of hurting cats that were affectionate towards me.
- She prove incapable of swimming across the Channel by her own.
- The cat prove incapable of scratching the meat who was hung from the ceiling.
for a time: 暂时地
- I was just unemployed for a time.
- I want to borrow you some money for a time.
- The kind of perfume was exempted from import duty for a time.
be drawn into sth.: 被卷入到某事
- If you hadn't asked for a lift, you wouldn't have been drawn into the murder.
- The blind was by no mean drawn into a murder which happened outside the city twelve miles away.
- Drawn into a bitterly quarrel, she played truant from school.
The advent of sth.: 某事物的出现
- The advent of mass leisure led to a series of complaints from the upper class.
- The advent of the revolution ended the regime of the monarch.
- The advent of his ex-girlfriend led to an embarrassed atomsphere in the dinner room.
stir up sb.: 煽动某人
- The authrotarian government never ceases to stir up masses through the distort coverages.
- Stirring up masses, the authorities succeeded in starting a war.
- Being stirred up, the masses beated the officials to death.
Leading up to 1914: 直到1914
- Leading up to 2024, there still haven't been a champion team totally consisting of Chinese.
- Leading up to 2024, I haven't achieve my end which I made in my childhood.
- Leading up to 2024, she hasn't passed the test.
unease about sth.: 对某事的不安
- I have a sense of unease about unemployment.
- Having a sense of unease about unemployment, he beared unfair treatment in the company.
- Having a sense of unease about unemployment, she canceled the brief excursion to amusement park. 
** sentence2
petition [pəˈtɪʃ(ə)n]: n. a written request signed by a lot of people, asking someone in authority to do something or change something请愿
- The woman outside the palace wanted to present a petition to you, majesty.
- Despite the petition of thousands of peasants, the king still levied taxes without parliament.
- He insisted the woman was guilty of the petition.
entail [ɪnˈteɪl]: v. to involve something as a necessary part or result使必需, 使蒙受
- Because my parents got divorced and my mother left me in my childhood, I entailed many struggles when I asked for the right to do something.
- Entailing many struggles, he insisted that his son should go to school in town.
- Entailing many struggles, he brought his team to win the world championship.
suffrage [ˈsʌfrɪdʒ]: n. the right to vote in national elections
- Out of the disgust of a woman who asked for suffrage: we have received unfair treatment in domestic affairs.
- The mob who asked for suffrage was streaming towards the royal armory.
- Because of the lack of evidence, I gave up the suffrage in the court.
shield [ʃild]: v. to protect someone or something from being harmed or damaged保护, 防护
- The special iron board was used to shield you from arrows when you fought for your family.
- Shielding candle flame from my cat, my left hand got injured.
- Shielding gangsters from his daughter, he was put out of business.
lad [læd]: n. old-fashioned informal a boy or young man ⇨ lass少年
- The lad had an opportunity to meet our majesty.
- The lad, on the other hand, is guilty of sneaking into the palace.
- It seems that our majesty is quite tolerant of the lad who defends against the Asiatic nomads.
bruise [bruz]: v. if part of your body bruises, or if you bruise part of your body, it gets hit or hurt and a bruise appears瘀伤
- If you bruise in an action, you must eat the pill, even though it has some side effects.
- When she found her child bruised, she got very angry.
- If your body bruises, you must try our drug which works a great deal.
hatless ['hætlɪs]: adj. 不戴帽子的
- The lad noticed a hatless girl drinking a special kind of drug.
- I'd rather be hatless than wear a hat like a lighthouse.
- The clerk didn't like the way she dressed, especially when she was hatless.
scratch [skrætʃ]: v. to rub your skin with your nails because it feels uncomfortable ⇨ itch搔, 抓
- Your dog pounced on me and then scratched my hands.
- I was made by gangsters to scratch her face, I confessed to my godfather.
- Envious of her friend's perfect face, she insidiously poisoned her friend through her friend's daily drink.
swollen [ˈswoʊlən]: adj. a part of your body that is swollen is bigger than usual, especially because you are ill or injured肿胀的
- Our cat's paw is swollen, she must have scratched the beehive in the ceiling.
- Hitting the surface of the desk dramatically, his hands must have been swollen.
- Your son's face is swollen because your so-called friend tried to beat him to death.
bleeding [ˈblidɪŋ]: adj. an offensive way of emphasizing something when you are angry流血的
- He tried to keep his bleeding hand from his daughter's face.
- On arriving on the scene, the police found a broken bleeding arm.
- He lost no time in coping with his bleeding legs.
recall [ˈriˌkɔl]: v. to remember a particular fact, event, or situation from the past回想
- It's unpleasant to recall something bad in my childhood.
- When she tried to recall the answers, she heard strange notes of music.
- You must recall the phone number which she provided you yesterday.
agitation [ˌædʒɪˈteɪʃ(ə)n]: n. public argument or action for social or political change请求变革
- Fearing the agitation, the authorities purchased a special kind of seeds which would take root quickly.
- Fearing the agitation, the authorities lost no time in keeping the leaders in prison.
- The agitation manifested itself in more frequent strikes in the coal mine.
imperial [ɪmˈpɪriəl] imperialist: n.n. relating to an ↑empire or to the person who rules it皇帝的
- The authoritarian government often condemns other countries as imperialists.
- The determination of imperialists to destroy our republic government never dies.
- The imperial government formed vast armies by conscription.
uncertainty [ʌnˈsɜrt(ə)nti]: n. when you feel doubt about what will happen不确定
- If you don't plan the coronation to the last detail, it will still have uncertainties. 
- Because of the uncertainties of the mob, the king ordered his men to kill them as quickly as possible.
- Because of the uncertainties of the succession to the throne, the ministers haven't decided to support whom.
intensify [ɪnˈtensɪˌfaɪ]: v. to increase in degree or strength, or to make something do this加强
- When I was left doing homework, my loneliness intensified.
- Because of her intensified loneliness, she had a habit of cheating on her husband.
- The communication between me and my aunt intensified these days, which gave me a sense of happiness.
antagonism [ænˈtæɡəˌnɪzəm]: n. hatred between people or groups of people SYN hostility对抗
- The antagonism between Muslims and Christians continued into the twentieth century.
- The antagonism between him and his old brother led to a bitter fight.
- The antagonism between the two villages caused a series of fights.
alliance [əˈlaɪəns]: n. an arrangement in which two or more countries, groups etc agree to work together to try to change or achieve something联盟, 联合
- As long as our member was attacked, we would provide the weapon for it, the spokesman of the alliance declaimed.
- The spokesman of the alliance was assassinated in the course of his house.
- The countries of the alliance will be exempt from import duty.
triple [ˈtrɪp(ə)l]: adj. having three parts or involving three groups, people, events etc ⇨ double三倍的
- If you delay in relieving the kid, you will obtain triple ransom.
- Exasperated by the relation's calling the police, the kidnapper asked for triple ransom.
- Exasperated by the increased import duty of China, the president asked for triple import duty.
carnage [ˈkɑrnɪdʒ]: n. when a lot of people are killed and injured, especially in a war残杀, 大屠杀
- The man who survived carnage is receiving treatment in the seaside resort. 
- Fearing carnage, the king decided to arrange a peace settlement as soon as possible.
- According to the coverage, there must be at least ten thousand people killed in the carnage.
advance [ədˈvæns]: v. if scientific or technical knowledge advances, or if something advances it, it develops and improves推进
- Some scientists are advancing the search for a cat-like animal.
- Our reformations must be advanced in our army which spends two-thirds of our taxes every year.
- Advancing reformations in armies, he was hated by some landed aristocratics.
imminent [ˈɪmɪnənt]: adj. an event that is imminent, especially an unpleasant one, will happen very soon即将来临的, 逼近的
- I am determined to face the imminent challenges of new philosophes.
- The imminent catastrophe gave our government a shock.
- The student pestered his teacher about the imminent gift.
prophetic [prəˈfetɪk]: adj. correctly saying what will happen in the future预言的
- The prophetic words were not taken seriously, which led to a series of troubles.
- The prophetic warning was regarded as a joke, in one sense.
- I figured out that our majesty admired you for your prophetic warning.
--------------------
bend over sb.: 俯身于某人
- Bending over me, my father touched my head and asked me to study hard.
- Bending over my classmate, Mr. Leo threatened that if he didn't complete his task, he would get fired.
- Bending over my cat, I heard a strange noise from his stomach.
receive the right to do sth.: 获取权利去做某事
- I never receive the right to arrange my room.
- She must receive the right to study abroad.
- She can't receive the right to study abroad.
prove incapable of doing sth.: 证明不足以做某事
- I proved incapable of hurting cats that were affectionate towards me.
- She proved incapable of swimming across the Channel on her own.
- The cat proved incapable of scratching the meat that was hung from the ceiling.
for a time: 暂时地
- I was just unemployed for a time.
- I want to borrow you some money for a time.
- The kind of perfume was exempted from import duty for a time.
be drawn into sth.: 被卷入到某事
- If you hadn't asked for a lift, you wouldn't have been drawn into the murder.
- The blind was by no means drawn into a murder that happened outside the city twelve miles away.
- Drawn into a bitter quarrel, she played truant from school.
The advent of sth.: 某事物的出现
- The advent of mass leisure led to a series of complaints from the upper class.
- The advent of the revolution ended the regime of the monarch.
- The advent of his ex-girlfriend led to an embarrassing atmosphere in the dinner room.
stir up sb.: 煽动某人
- The authoritarian government never ceases to stir up masses through the distorted coverages.
- Stirring up masses, the authorities succeeded in starting a war.
- Being stirred up, the masses beat the officials to death.
Leading up to 1914: 直到1914
- Leading up to 2024, there still hasn't been a champion team totally consisting of Chinese.
- Leading up to 2024, I haven't achieved the end that I made in my childhood.
- Leading up to 2024, she hasn't passed the test.
unease about sth.: 对某事的不安
- I have a sense of unease about unemployment.
- Having a sense of unease about unemployment, he bore unfair treatment in the company.
- Having a sense of unease about unemployment, she canceled the brief excursion to the amusement park. 
** summary
Many Europeans after 1894 believed they lived in an era of material and human progress.
Women, on the other hand, still need to fight for the rights to vote.
Pankhurst, the leader of the women's suffrage movement who was arrested and jailed,
	informed her judges that even though they sent her to prison, the agitation could not be stopped.
Eventually, women in Britain received the right to vote.
After 1860, Europeans engaged in a great race for colonies around the world,
	which intensified existing antagonisms among European states.
Two large alliance system--the Triple Alliance and the Triple Entente--
	may have preserved peace for a time,
	but they made it easier for the European nations to be drawn into the World War I.
Mass education also made governments easier to stir up the masses by nationalistic appeals.
Many intellectuals had a sense of unease about the direction of the society
	and a feeling of imminent catastrophe.
** summary2
Many Europeans after 1894 believed they lived in an era of material and human progress.
Women, on the other hand, still need to fight for the right to vote.
Pankhurst, the leader of the women's suffrage movement who was arrested and jailed,
	informed her judges that even though they sent her to prison, the agitation could not be stopped.
Eventually, women in Britain received the right to vote.
After 1860, Europeans engaged in a great race for colonies around the world,
	which intensified existing antagonisms among European states.
Two large alliance systems--the Triple Alliance and the Triple Entente--
	may have preserved peace for a time,
	but they made it easier for the European nations to be drawn into World War I.
Mass education also made it easier to stir up the masses with nationalistic appeals.
Many intellectuals had a sense of unease about the direction of society
	and a feeling of imminent catastrophe.
