#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 26 Men are served in a soup line in Berlin in 1930
#+begin_verse
In the 1920s,
	many people in the West assumed that they were about to enter a new era of world peace,
		economic growth, and political democracy.
In all of these areas, the optimistic hopes of the 1920s failed to be realized.
After 1919, most people wanted peace but were unsure about how to maintain it.
The League of Nations, conceived as a new instrument to provide for collective security,
	failed to work well.
New treaties that renounced the use of war looked good on paper but had no means of enforcement.
Virtually everyone favored disarmament, but few could agree on how to achieve it.

Europe faced severe economic and social challenges after World War I.
The European economy did not begin to recover from the war until 1922,
	and even then it was beset by financial problems left over from the war and,
		most devastating of all, the severe economic crisis that began at the end of 1929.
The Great Depression brought untold misery to millions of people.
Begging for food on the streets became widespread,
	especially when soup kitchens were unable to keep up with the demand.
Larger and larger numbers of people were homeless
	and moved from place to place looking for work and shelter.
In the United States,
	the homeless set up shantytowns
		they named 'Hoovervilles' after the American president, Herbert Hoover.
In their misery, some people saw but one solution, as one unemployed person expressed it:
	Today, when I am experiencing this for the first time,
		I think that I should prefer to do away with myself,
			to take gas, to jump into the river, or leap from some high place.
	Would I really come to such a decision? I do not know.
	Animals die, plants wither, but men always go on living.
Social unrest spread rapidly,
	and some of the vast numbers of unemployed staged hunger marches to get attention.
In democratic countries,
	more and more people began to listen to and vote for radical voices calling for extreme measures.

According to U.S. President Woodrow Wilson,
	World War I had been fought to make the world safe for democracy,
		and for a while after 1919, political democracy seemed well established.
But hope soon faded
	as authoritarian regimes spread into Italy and Germany and across eastern Europe.
#+end_verse
** expression
soup [sup]: n. cooked liquid food, often containing small pieces of meat, fish, or vegetables汤
optimistic [ˌɑptɪˈmɪstɪk]: adj. believing that good things will happen in the future OPP pessimistic乐观的
collective [kəˈlektɪv]: adj. shared or made by every member of a group or society集体的
treaty [ˈtriti]: n. a formal written agreement between two or more countries or governments条约, 谈判
renounce [rɪˈnaʊns]: v. if you renounce an official position, title, right etc, you publicly say that you will not keep it any more SYN give up摒弃,放弃
enforce [ɪnˈfɔrs] enforcement: v.n. when people are made to obey a rule, law etc执行, 强制
favor [ˈfeɪvər]: v. PREFER to prefer someone or something to other things or people, especially when there are several to choose from支持, 赞成
disarm [dɪsˈɑrm] disarmament: v.n. when a country reduces the number of weapons it has, or the size of its army, navy etc裁军
severe [sɪˈvɪr] severity: adj.v. severe problems, injuries, illnesses etc are very bad or very serious严峻的
devastate [ˈdevəˌsteɪt]: v. to damage something very badly or completely毁坏
untold [ˌʌnˈtoʊld]: adj. used to emphasize that an amount or quantity is very large数不清的
misery [ˈmɪzəri]: n. great suffering that is caused for example by being very poor or very sick痛苦, 苦恼, 悲惨, 穷困
shelter [ˈʃeltər]: n. a place to live, considered as one of the basic needs of life庇护所
shantytown [ˈʃæntiˌtaʊn]: n. a very poor area in or near a town where people live in small houses made from thin sheets of wood, ↑tin etc棚户
wither [ˈwɪðər]: v. if plants wither, they become drier and smaller and start to die枯萎
unrest [ʌnˈrest]: n. a political situation in which people protest or behave violently不安的状态, 动荡的局面
march [mɑrtʃ]: n. an organized event in which many people walk together to express their ideas or protest about something游行
fade [feɪd]: v. (also fade away) to gradually disappear减弱下去
--------------------
be served in sp.: 在...提供食物
be unsure about sth./how to do sth.: 对某事不确认
be conceived as sth.: 被认为是某物
on paper: 理论上
agree on sth.: 在某事上达成一致
recover from sth.: 从...中恢复
be beset by sth.: be afflicted with/by sth. 被某事困扰
beg for sth.: 乞讨某物
keep up with the command/request: 跟上要求
from place to place: 从一个地方到另一个地方
but one + n.: 只有...
do away with sth.: 废除,破除某事(oneself自杀)
come to a decision: 做出决定
** sentence
soup [sup]: n. cooked liquid food, often containing small pieces of meat, fish, or vegetables汤
- Why don't you prepare soup for dinner?
- Would you like some soup?
- My wife is fanatical about drinking soup before meal.
optimistic [ˌɑptɪˈmɪstɪk]: adj. believing that good things will happen in the future OPP pessimistic乐观的
- The prizefight who lives in poverty is optimistic about life.
- People tend to form an optimistic view of life on a desert island.
- At the that time, I was optimistic about life and though the town is the paradise which provided me with new forms of entertainment.
collective [kəˈlektɪv]: adj. shared or made by every member of a group or society集体的
- For collective health, smoking in public places must be forbidden as soon as possible.
- The abbot is such a devout man that what he cares about is collective interest.
- Everyone in our community felt obliged to maintain collective environment.
treaty [ˈtriti]: n. a formal written agreement between two or more countries or governments条约, 谈判
- All the presentatives of the nations that had fought France was due to sign a treaty in Paris.
- As long as the treaty was signed, all clauses would be enforced on time.
- As the treaty was signed, Germans had to pay for starting the war and the losses of the Allied nations.
renounce [rɪˈnaʊns]: v. if you renounce an official position, title, right etc, you publicly say that you will not keep it any more SYN give up摒弃,放弃
- If you renounced your master degree, you would have a difficult time in finding work.
-	It occurs to him to renounce the party because of the emergence of a new ideology.
- He was determined to renounce the school where students were given electrical shocks.
enforce [ɪnˈfɔrs] enforcement: v.n. when people are made to obey a rule, law etc执行, 强制
- Our leader will not have the opportunity to enforce his rule.
- The police have the privilege of enforcing a law in the country these days.
- The enforcement of the law proved difficult, for the parliament hasn't supported it.
favor [ˈfeɪvər]: v. PREFER to prefer someone or something to other things or people, especially when there are several to choose from支持, 赞成
- Obviously, he will favor your opinion, for he is very proud of you.
- My wife favors a special kind of hair gel which she made herself.
- The clause you favor is benefit for the United States.
disarm [dɪsˈɑrm] disarmament: v.n. when a country reduces the number of weapons it has, or the size of its army, navy etc裁军
- The country appeared to have disarmed.
- The chairman claimed that the disarmament would be finished in three years. 
- The disarmament in China led to a series of complaints from soliers who used to fight for people.
severe [sɪˈvɪr] severity: adj.v. severe problems, injuries, illnesses etc are very bad or very serious严峻的
- Because the emperor is suffering from severe illness, we must lost no time in determining the concession to the throne.
- Suffering from severe illness, the king renounced the Triple Alliance.
- The cat who suffered from severe injured fell off from the windowsill.
devastate [ˈdevəˌsteɪt]: v. to damage something very badly or completely毁坏
- Two cities in Japan were devastated by nuclear weapon.
- The king must have been devastated by the death of his long-lost son who used to be regarded as the concession to the throne.
- The prisoner spread small poxes to the Europeans who devastated their civilization.
untold [ˌʌnˈtoʊld]: adj. used to emphasize that an amount or quantity is very large数不清的
- There are untold beautiful girls in the fancy party.
- There are untold vivid words about the stories of love.
- He imagines a desert island to be a sort of paradise full of untold lobsters and fishes.
misery [ˈmɪzəri]: n. great suffering that is caused for example by being very poor or very sick痛苦, 苦恼, 悲惨, 穷困
- The mistake majesty made then cause the misery between me and Ziwei. 
- If you could see the misery of people, you wouldn't publish such a law.
- The carnage of World War I led to the untold misery of people all over the world.
shelter [ˈʃeltər]: n. a place to live, considered as one of the basic needs of life庇护所
- The house used to be a shelter for heretics. 
- The leader of the party raised a large sum of money to have these shelters repaired.
- The cave I digged up in my courtyard becomes a shelter for a kitty.
shantytown [ˈʃæntiˌtaʊn]: n. a very poor area in or near a town where people live in small houses made from thin sheets of wood, ↑tin etc棚户
- Shantytowns transformation became popular with those inhabitants who were in pursuit of a better shelter.
- To achieve his ends, the general ordered his men to devastate the shantytown.
- The shantytown was devastated by a bomb, which cause severe injuries.
wither [ˈwɪðər]: v. if plants wither, they become drier and smaller and start to die枯萎
- I can't stand that my beloved girl looks like a withering flower.
- The withering plants aside the road were replaced by new kinds of grass overnight.
- Like a withering flower, she desired to fall in love with her boy.
unrest [ʌnˈrest]: n. a political situation in which people protest or behave violently不安的状态, 动荡的局面
- There is a growing unrest in the town 12 miles away outside the city of Paris.  
- When the sophisticated king assmued the power, the unrest in the countryside was soon settled.
- When the unrest of peasants erupted in the square, the leader lost no time in dispatching tanks to settle it.
march [mɑrtʃ]: n. an organized event in which many people walk together to express their ideas or protest about something游行
- The lad imagined the hunger march to be a sort of daily activity.
- I wished that the hunger march achieved its ends.
- The hunger marches organized by the party intensified the anatagonism between classes.
fade [feɪd]: v. (also fade away) to gradually disappear减弱下去
- Hopes of her marring to a upper class is beginning to fade.
- As hopes of a peace settlement began to fade, the nations in Europe ceased to disarm.
- As hopes of getting better working conditions began to fade, the workers were due to go on a general strike.
--------------------
be served in sp.: 在...提供食物
- Served in the resturant, you are not supposed to carry outside food.
- Served in the soup kitchen, masses are supposed to wait in line.
- Served in the soup kitchen, you should be grateful to the government.
be unsure about sth./how to do sth.: 对某事不确认
- I am unsure about how to communicate with other in public.
- She is unsure about how to cook meal with the oven.
- My cat is still unsure about how to use her paws.
be conceived as sth.: 被认为是某物
- Conceived as the pillar of the family, he tries his best to make money.
- Conceived as the best player, he wished that he had won the championship.
- Conceived as the best player of China, he was expected to bring the trophy to China.
on paper: 理论上
- The team A is stronger than the team B on paper, so I will chose team A as the winner of the competition.
- There should be no bug on paper, what goes wrong?
- I will pass the exam in three month on paper if I study hard.
agree on sth.: 在某事上达成一致
- French and Germany agreed on the peace settlement.
- After several stikes, the workers and the entrepreneurs agreed on better working conditions and higher pay.
- My wife and me agreed on how to go on a vacation in Sanya.
recover from sth.: 从...中恢复
- Recovering from the injury, the cat likes to wander on the high-rise windowsill.
- Recovering from the operation, the puma was examined by the experts from the zoo.
- Recovering from the disease, Europe proved resilient.
be beset by sth.: be afflicted with/by sth. 被某事困扰
- Beset by his daughter's request, he couldn't concentrate on his driving.
- Beset by my wife's flirting, I couldn't help taking a bath.
- Beset by the dog's pee in the elevator, I argued with its master.
beg for sth.: 乞讨某物
- You imagined me to be a sort of man who begged for a soup.
- Put out of business, he was begging for food in the street.
- My cat was just begging for the snack in my hand.
keep up with the command/request: 跟上要求
- Keeping up with the command of the peace settlement, the nation must disarm.
- Keeping up with my daughter's request, I must improve myself and get a better salary.
- Keeping up with the request, the reformation in our armies must be achieved in three years.
from place to place: 从一个地方到另一个地方
- The hunt for puma proved difficult, for it moved from place to place in the plain.
- The beggar moved from place to place, begging for a shelter.
- The merchant moved from place to place, seeking for the profit.
but one + n.: 只有...
- I can see but one apple on the table.
- I have but one opportunity to achieve my goal for my life.
- She has but one pen which her husband present her.
do away with sth.: 废除,破除某事(oneself自杀)
- The king was reluctant to do away with himself and tried to escape in disguise.
- The king prefered to do away with himself rather than be humiliated by the peasants.
- The king succeeded in doing away with himself after the collapse of his kingdom.
come to a decision: 做出决定
- He lost no time in coming to a decision.
- Coming to a decision, he was anxious to find the strait of America.
- Coming to a decision, he led the fleet to search for new land.
** sentence2
soup [sup]: n. cooked liquid food, often containing small pieces of meat, fish, or vegetables汤
- Why don't you prepare soup for dinner?
- Would you like some soup?
- My wife is fanatical about drinking soup before meals.
optimistic [ˌɑptɪˈmɪstɪk]: adj. believing that good things will happen in the future OPP pessimistic乐观的
- The prizefight who lives in poverty is optimistic about life.
- People tend to form an optimistic view of life on a desert island.
- At that time, I was optimistic about life and thought the town was a paradise where I could pursue my happiness.
collective [kəˈlektɪv]: adj. shared or made by every member of a group or society集体的
- For collective health, smoking in public places must be forbidden as soon as possible.
- The abbot is such a devout man that what he cares about is collective interest.
- Everyone in our community felt obliged to maintain a collective environment.
treaty [ˈtriti]: n. a formal written agreement between two or more countries or governments条约, 谈判
- All the representatives of the nations that had fought France were due to sign a treaty in Paris.
- As long as the treaty was signed, all clauses would be enforced on time.
- As the treaty was signed, Germans had to pay for starting the war and the losses of the Allied nations.
renounce [rɪˈnaʊns]: v. if you renounce an official position, title, right etc, you publicly say that you will not keep it any more SYN give up摒弃,放弃
- If you renounced your master's degree, you would have a difficult time finding work.
-	It occurs to him to renounce the party because of the emergence of a new ideology.
- He was determined to renounce the school where students were given electrical shocks.
enforce [ɪnˈfɔrs] enforcement: v.n. when people are made to obey a rule, law etc执行, 强制
- Our leader will not have the opportunity to enforce his rule.
- The police have the privilege of enforcing a law in the country these days.
- The enforcement of the law proved difficult, for the parliament hasn't supported it.
favor [ˈfeɪvər]: v. PREFER to prefer someone or something to other things or people, especially when there are several to choose from支持, 赞成
- Obviously, he will favor your opinion, for he is very proud of you.
- My wife favors a special kind of hair gel which she made herself.
- The clause you favor is beneficial for the United States.
disarm [dɪsˈɑrm] disarmament: v.n. when a country reduces the number of weapons it has, or the size of its army, navy etc裁军
- The country appeared to have disarmed.
- The chairman claimed that the disarmament would be finished in three years. 
- The disarmament in China led to a series of complaints from soldiers who used to fight for people.
severe [sɪˈvɪr] severity: adj.v. severe problems, injuries, illnesses etc are very bad or very serious严峻的
- Because the emperor is suffering from severe illness, we must lose no time in determining the concession to the throne.
- Suffering from severe illness, the king renounced the Triple Alliance.
- The cat who suffered from severe injury fell from the high-rise windowsill.
devastate [ˈdevəˌsteɪt]: v. to damage something very badly or completely毁坏
- Two cities in Japan were devastated by nuclear weapons.
- The king must have been devastated by the death of his long-lost son who used to be regarded as the concession to the throne.
- The prisoner spread smallpoxes to the Europeans who devastated their civilization.
untold [ˌʌnˈtoʊld]: adj. used to emphasize that an amount or quantity is very large数不清的
- There are untold beautiful girls at the fancy party.
- There are untold vivid words about the stories of love.
- He imagines a desert island to be a sort of paradise full of untold lobsters and fishes.
misery [ˈmɪzəri]: n. great suffering that is caused for example by being very poor or very sick痛苦, 苦恼, 悲惨, 穷困
- The mistake Majesty made then caused misery between me and Ziwei. 
- If you could see the misery of people, you wouldn't publish such a law.
- The carnage of World War I led to the untold misery of people all over the world.
shelter [ˈʃeltər]: n. a place to live, considered as one of the basic needs of life庇护所
- The house used to be a shelter for heretics. 
- The leader of the party raised a large sum of money to have these shelters repaired.
- The cave I dug up in my courtyard becomes a shelter for a kitty.
shantytown [ˈʃæntiˌtaʊn]: n. a very poor area in or near a town where people live in small houses made from thin sheets of wood, ↑tin etc棚户
- Shantytown transformation became popular with those inhabitants who were in pursuit of a better shelter.
- To achieve his ends, the general ordered his men to devastate the shantytown.
- The shantytown was devastated by a bomb, which caused severe injuries.
wither [ˈwɪðər]: v. if plants wither, they become drier and smaller and start to die枯萎
- I can't stand that my beloved girl looks like a withering flower.
- The withering plants aside the road were replaced by new kinds of grass overnight.
- Like a withering flower, she desired to fall in love with her boy.
unrest [ʌnˈrest]: n. a political situation in which people protest or behave violently不安的状态, 动荡的局面
- There is a growing unrest in the town 12 miles away outside the city of Paris.  
- When the sophisticated king assumed power, the unrest in the countryside was soon settled.
- When the unrest of peasants erupted in the square, the leader lost no time in dispatching tanks to settle it.
march [mɑrtʃ]: n. an organized event in which many people walk together to express their ideas or protest about something游行
- The lad imagined the hunger march to be a sort of daily activity.
- I wished that the hunger march had achieved its end.
- The hunger marches organized by the party intensified the antagonism between classes.
fade [feɪd]: v. (also fade away) to gradually disappear减弱下去
- Hopes of her marrying to an upper class are beginning to fade.
- As hopes of a peace settlement began to fade, the nations in Europe ceased to disarm.
- As hopes of getting better working conditions began to fade, the workers were due to go on a general strike.
--------------------
be served in sp.: 在...提供食物
- Served in the restaurant, you are not supposed to carry outside food.
- Served in the soup kitchen, masses are supposed to wait in line.
- Served in the soup kitchen, you should be grateful to the government.
be unsure about sth./how to do sth.: 对某事不确认
- I am unsure about how to communicate with others in public.
- She is unsure about how to cook meals with the oven.
- My cat is still unsure about how to use her paws.
be conceived as sth.: 被认为是某物
- Conceived as the pillar of the family, he tries his best to make money.
- Conceived as the best player, he wished that he had won the championship.
- Conceived as the best player of China, he was expected to bring the trophy to China.
on paper: 理论上
- Team A is stronger than Team B on paper, so I will choose Team A as the winner of the competition.
- There should be no bug on paper, what goes wrong?
- I will pass the exam in three months on paper if I study hard.
agree on sth.: 在某事上达成一致
- France and Germany agreed on the peace settlement.
- After several strikes, the workers and the entrepreneurs agreed on better working conditions and higher pay.
- My wife and I agreed on how to go on a vacation in Sanya.
recover from sth.: 从...中恢复
- Recovering from the injury, the cat likes to wander on the high-rise windowsill.
- Recovering from the operation, the puma was examined by the experts from the zoo.
- Recovering from the disease, Europe proved resilient.
be beset by sth.: be afflicted with/by sth. 被某事困扰
- Beset by his daughter's request, he couldn't concentrate on his driving.
- Beset by my wife's flirting, I couldn't help taking a bath.
- Beset by the dog's pee in the elevator, I argued with its master.
beg for sth.: 乞讨某物
- You imagined me to be a sort of man who begged for a spoon of soup.
- Put out of business, he was begging for food in the street.
- My cat was just begging for the snack in my hand.
keep up with the command/request: 跟上要求
- Keeping up with the command of the peace settlement, the nation must disarm.
- Keeping up with my daughter's request, I must improve myself and get a better salary.
- Keeping up with the request, the reformation of our armies must be achieved in three years.
from place to place: 从一个地方到另一个地方
- The hunt for puma proved difficult, for it moved from place to place in the plain.
- The beggar moved from place to place, begging for shelter.
- The merchant moved from place to place, seeking for the profit.
but one + n.: 只有...
- I can see but one apple on the table.
- I have but one opportunity to achieve my goal for my life.
- She has but one pen which her husband presenst her.
do away with sth.: 废除,破除某事(oneself自杀)
- The king was reluctant to do away with himself and tried to escape in disguise.
- The king preferred to do away with himself rather than be humiliated by the peasants.
- The king succeeded in doing away with himself after the collapse of his kingdom.
come to a decision: 做出决定
- He lost no time in coming to a decision.
- Coming to a decision, he was anxious to find the strait of America.
- Coming to a decision, he led the fleet to search for new land.
** summary
The optimistic hopes of 1920s,
		entering a new era of world peace, economic growth, and political democracy,
	failed to be realized.
After 1919, the Legue of Nations proved incapable of working well,
	and new treaties that renounced the use of war had no means of enforcement.
Besides,
	the European economy was best by financial problems caused by the war and the Great Depression.
Larger and larger numbers of people were homeless, begged for food,
	and moved from place to place looking for work and shelter.
In their misery, some people even have an impluse of doing away with themselves
	after they had been unemployed.
The vast numbers of unemployed staged hunger marches to get attention.
In democratic countries, more and more people began to call for extreme measures.
For a while after 1919, political democracy seemed well established,
	but then authoritarian regimes spread into Italy and Germany and across eastern Europe.
** summary2
The optimistic hopes of the 1920s,
		entering a new era of world peace, economic growth, and political democracy,
	failed to be realized.
After 1919, the League of Nations proved incapable of working well,
	and new treaties that renounced the use of war had no means of enforcement.
Besides,
	the European economy was beset by financial problems caused by the war and the Great Depression.
Larger and larger numbers of people were homeless, begged for food,
	and moved from place to place looking for work and shelter.
In their misery, some people even had an impulse to do away with themselves
	after they had been unemployed.
The vast numbers of unemployed staged hunger marches to get attention.
In democratic countries, more and more people began to call for extreme measures.
For a while after 1919, political democracy seemed well established,
	but then authoritarian regimes spread into Italy, Germany, and across Eastern Europe.
