#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 28 The end of World War II
#+begin_verse
The end of World War II in Europe was met with great joy.
One visitor to Moscow reported,
	'I looked out of the window at 2 A.M., almost everywhere there were lights in the window
		---people were staying awake.
	Everyone embraced everyone else, someone sobbed aloud.'
But after the victory parades and celebrations, Europeans awoke to a devastating realization:
	their civilization was in ruins.
Some wondered if Europe would ever regain its former prosperity and importance.
Winston Churchill wrote,
	'What is Europe now?
	A rubble heap, a charnel house, a breeding ground of pestilence and hate.'
There was ample reason for his pessimism.
Forty million people (both soldiers and civilians) had been killed during the last six years.
Massive air raids and artillery bombardments
	had reduced many of the great cities of Europe to heaps of rubble.
An American general described Berlin:
	'Wherever we looked we saw desolation.
	It was like a city of the dead.
	Suffering and shock were visible in every face.
	Dead bodies still remained in canals and lakes and were being dug out from under bomb debris.'
Millions of Europeans faced starvation
	because grain harvests were only half of what they had been in 1939.
Millions were also homeless.
In the parts of the Soviet Union that had been occupied by the Germans,
	almost 25 million people were without homes.
The destruction of bridges, roads, and railroads had left transportation systems paralyzed.
Eleven million prisoners of war had to be returned to their native countries,
	and fifteen million Germans and Eastern Europeans were driven out of countries
		where they were no longer wanted.
Yet despite the chaos, Europe was soon on the road to a remarkable recovery.
Already by 1950, Europe's industrial and agricultural output was 30 percent above prewar levels.

World War II had also destroyed European supremacy in world affairs.
After 1945, the colonial empires of the European nations rapidly disintegrated,
	and Europe's place in the world changed radically.
As the Cold War conflict between the world's two superpowers
		---the United States and the Soviet Union---intensified,
	the European nations were divided into two armed camps
		dependent on one or the other of these two major powers.
The United States and the Soviet Union,
		whose rivalry raised the specter of nuclear war,
	seemed to hold the survival of Europe and the world in their hands.
#+end_verse
** expression
embrace [ɪmˈbreɪs]: v. to put your arms around someone and hold them in a friendly or loving way SYN hug拥抱
sob [sɑb]: v. to cry noisily while athing in short sudden bursts哭泣
parade [pəˈreɪd]: n. a public celebration when musical bands, brightly decorated vehicles etc move down the street游行,阅兵
rubble [ˈrʌb(ə)l]: n. broken stones or bricks from a building or wall that has been destroyed碎石
heap [hip]: n. a large untidy pile of things堆
pestilence [ˈpestɪləns]: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
ample [ˈæmp(ə)l]: adj. more than enough SYN sufficient OPP insufficient充足的, 丰富的
pessimism [ˈpesəˌmɪzəm]: n. a tendency to believe that bad things will happen OPP optimism悲观,悲观主义
artillery [ɑrˈtɪl(ə)ri]: n. large guns, either on wheels or fixed in one place大炮, 炮兵
bombard [bɑmˈbɑrd] bombardment: v.n. to attack a place for a long time using large weapons, bombs etc炮轰；轰击
canal [kəˈnæl]: n. a long passage dug into the ground and filled with water, either for boats to travel along, or to take water to a place运河
debris [dəˈbri]: n. the pieces of something that are left after it has been destroyed in an accident, explosion etc碎片, 残骸
grain [ɡreɪn]: n. the seeds of crops such as corn, wheat, or rice that are gathered for use as food, or these crops themselves谷物
homeless [ˈhoʊmləs]: adj. without a home无家的, 无家可归的
paralyzed [ˈperəˌlaɪzd]: adj. unable to move part or all of your body or feel it瘫痪的,麻痹的
chaos [ˈkeɪˌɑs] chaotic: n.adj. a chaotic situation is one in which everything is happening in a confused way混乱的
output [ˈaʊtˌpʊt]: n. the amount of goods or work produced by a person, machine, factory etc ⇨ production产量, 输出
affairs [əˈfer]: n. public or political events and activities事务, 事件
--------------------
with great joy: 怀着极大的喜悦
stay awake: 保持清醒
awake to sth.: 意识到某事
in ruins: 一片废墟
charnel house: 尸骨堆积处
an air raid: 空袭
be without homes: 无家可归
be on the road to sp.: 在通往某处的路上
be dependent on sth./sb.: 依赖某人/某物
the specter of sth.: 某物的幽灵(引起发生某事的恐惧)
** sentence
embrace [ɪmˈbreɪs]: to put your arms around someone and hold them in a friendly or loving way SYN hug拥抱
- A short time before, they embraced with great joy.
- When news came to London, people in the streets embraced everyone else.
- Mobs who were going on a strike embraced everyone else for miles around.
sob [sɑb]: to cry noisily while athing in short sudden bursts哭泣
- The man grabbed a beer and then began to sob.
- The girl embraced her cat sobbing aloud.
- He noticed that the gangsters had stolen two thousands dollars of his jewelery, and began to sob aloud.
parade [pəˈreɪd]: a public celebration when musical bands, brightly decorated vehicles etc move down the street游行,阅兵
- In some totalitarian countries, parades are still forbidden in public.
- With the authorities not meeting their demands, they were due to initiate a parade in the street.
- Exspareated by the authorities, the mobs armed with weapons initiated a parade in the festival.
rubble [ˈrʌb(ə)l]: n. broken stones or bricks from a building or wall that has been destroyed碎石
- The rubble of the mountained were soon used up by the village who desired to build their houses.
- The rubble bounced along the pavement and then disappear in the drain.
- Don't use rubble to attack my dog even if he is barking.
heap [hip]: n. a large untidy pile of things堆
- I complained that my house was full of rubbish heaps.
- She lost no time in cleaning the rubbish heap.
- There used to be a stone heap on my way to school.
pestilence [ˈpestɪləns]: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
- The pestilence Japanese spread devastated our cilivization.
- Stunned by the pestilence, the priest prayed for the help from god.
- Appalled at the pestilence, the spokesman condemned those unfriendly countries as brtual animals.
ample [ˈæmp(ə)l]: adj. more than enough SYN sufficient OPP insufficient充足的, 丰富的
- Beyond doubt, the church would provide these refugees with ample shelters.
- Ample industrial output made the regime continued into the next century.
- I felt entitled to make ample money with my hands.
pessimism [ˈpesəˌmɪzəm]: n. a tendency to believe that bad things will happen OPP optimism悲观,悲观主义
- If you are always having pessimism about future, you will not lead a happy life.
- Due to the extend of the war's casualties, there is a deep pessimism about the progress of Western cilivazation.
- Unemployed workers in 1970s had a deep pessimism about the economic depression.
artillery [ɑrˈtɪl(ə)ri]: n. large guns, either on wheels or fixed in one place大炮, 炮兵
- The royal armory was said to be full of artillery.
- These knights defended the king against the Asiatic nomads using a special kind of artillery.
- This kind of artillery was invented without no other aim than to attack the wall.
bombard [bɑmˈbɑrd] bombardment: v.n. to attack a place for a long time using large weapons, bombs etc炮轰；轰击
- The military confrontation may lead to a prominent bombardment.
- Bombarded with machine guns for two days, the city was virtually lost.
- Being bombarded with machine guns, we can't advance any more without new equipment.
canal [kəˈnæl]: n. a long passage dug into the ground and filled with water, either for boats to travel along, or to take water to a place运河
- My wife and I used to walk on the pavement along the canal.
- It was near the canal that we met our first cat, Miumiu.
- On holidays, people swamped upon the park near the cannal having picnics with their friends or families.
debris [dəˈbri]: n. the pieces of something that are left after it has been destroyed in an accident, explosion etc碎片, 残骸
- Because of the iron debris left in your stomach, we shall have a operation as soon as possible.
- If the police arrived on the scene, they would find nothing but the debris.
- This is why I spent a lot of time dealing with the debris of the body.
grain [ɡreɪn]: n. the seeds of crops such as corn, wheat, or rice that are gathered for use as food, or these crops themselves谷物
- Obviously, the grain is not your precious daughter's favorite food.
- Indeed, the grain harvest will bring our people to the next vitory.
- On that occasion, people will hold a celebration to expect the grain harvest next year.
homeless [ˈhoʊmləs]: adj. without a home无家的, 无家可归的
- If you keep gambling, we will be homeless.
- The beautiful dog seems to be homeless, maybe we can adopt her.
- It occurs to my wife to figure out whether the cat is homeless or not.
paralyzed [ˈperəˌlaɪzd]: adj. unable to move part or all of your body or feel it瘫痪的,麻痹的
- The man who fought for our country is paralyzed for the rest of his life.
- After the accident, I was afflicted by the paralyzed leg.
- Afflicted by the paralyzed leg, the soldier tried to do away with himself but failed.
chaos [ˈkeɪˌɑs] chaotic: n.adj. a chaotic situation is one in which everything is happening in a confused way混乱的
- Because of political chaos, a new law is often opposite to the former law.
- Suffering from political chaos, the empire lost control of its two colonies in Africa.
- People all over England are concern about the military chaos in Eastern Europe.
output [ˈaʊtˌpʊt]: n. the amount of goods or work produced by a person, machine, factory etc ⇨ production产量, 输出
- The output of industry is expected to triple by next year.
- The new kind of tomato scientist cultivated is expected to double output.
- The output of calculator doesn't agree on our calculation.
affairs [əˈfer]: n. public or political events and activities事务, 事件
- The United State is reluctant to intervene in domestic affairs in other countries.
- Our domestic affiars are none of your business, the spokesman claimed.
- The two superpowers promised not to intervene in African affairs.
--------------------
with great joy: 怀着极大的喜悦
- My wife told me she was pregnant with great joy.
- My dog pounced on me and licked my hands with great joy.
- The hunter realized that it must be a puma at large with great joy.
stay awake: 保持清醒
- On that occasion, you'd better stay awake.
- I am grateful to those who asked me to stay awake when I was in the face of a pyramid scheme. 
- Staying awake, he went up the tower to see what had happened.
awake to sth.: 意识到某事
- Awaking to the failure of the game, the player let out a cry.
- Awaking to the danger in the ring, the drunk stepped aside to avoid the attack of the cow.
- Awaking to the seriousness of the event, he lost no time in informing his superior.
in ruins: 一片废墟
- The city in ruins used to a shelter for millions of peasants.
- The city in ruins was being bombarded with long-last artillery.
- The nomads pushed their way westward and made the city in ruins.
charnel house: 尸骨堆积处
- The house used to be a charnel house for a hospital.
- Military chaos turned the palace into a charnel house.
- You shall send your dead child to a charnel house.
an air raid: 空袭
- He hasn't been killed in the air raid.
- In an air raid, he expressed his love to the girl and promised to marry her in a few years.
- In an air raid, the teacher succeeded in teaching the children the last lesson.
be without homes: 无家可归
- People without homes was appalled at the prosperity of the palace.
- People without homes gathered round the City Hall and asked for food.
- People without homes organized a number of marches.
be on the road to sp.: 在通往某处的路上
- 'I am on the road to school', I said in a weak voice.
- She may be on the road to school.
- She must be on the road to school.
be dependent on sth./sb.: 依赖某人/某物
- I am dependent on the supply of pocket money which my parent give on a daily basis.
- She is dependent on the money her boyfriend offer.
- The philosophes were dependent on the money the hostess of the salon offered.
the specter of sth.: 某物的幽灵(引起发生某事的恐惧)
- The military confrontation between two regimes raised the spector of civil war.
- The priest burnt a church down, which raised the spector of civil war.
- Their rivalry raised the specter of nuclear war.
** sentence2
embrace [ɪmˈbreɪs]: to put your arms around someone and hold them in a friendly or loving way SYN hug拥抱
- A short time before, they embraced with great joy.
- When news came to London, people in the streets embraced everyone else.
- Mobs going on a strike embraced everyone else for miles around.
sob [sɑb]: to cry noisily while athing in short sudden bursts哭泣
- The man grabbed a beer and then began to sob.
- The girl embraced her cat sobbing aloud.
- He noticed that the gangsters had stolen two thousand dollars of his jewelry, and began to sob aloud.
parade [pəˈreɪd]: a public celebration when musical bands, brightly decorated vehicles etc move down the street游行,阅兵
- In some totalitarian countries, parades are still forbidden in public.
- With the authorities not meeting their demands, they were due to initiate a parade in the street.
- Exspareated by the authorities, the mobs armed with weapons initiated a parade in the festival.
rubble [ˈrʌb(ə)l]: n. broken stones or bricks from a building or wall that has been destroyed碎石
- The rubble of the mountain was soon used up by the villagers who desired to build their houses.
- The rubble bounced along the pavement and then disappeared down the drain.
- Don't use rubble to attack my dog even if he is barking.
heap [hip]: n. a large untidy pile of things堆
- I complained that my house was full of rubbish heaps.
- She lost no time in cleaning the rubbish heap.
- There used to be a stone heap on my way to school.
pestilence [ˈpestɪləns]: n. literary a disease that spreads quickly and kills a lot of people SYN plague瘟疫
- The pestilence the Japanese spread devastated our civilization.
- Stunned by the pestilence, the priest prayed for help from god.
- Appalled at the pestilence, the spokesman condemned those unfriendly countries as brutal animals.
ample [ˈæmp(ə)l]: adj. more than enough SYN sufficient OPP insufficient充足的, 丰富的
- Beyond doubt, the church would provide these refugees with ample shelter.
- Ample industrial output made the regime continue into the next century.
- I felt entitled to make ample money with my hands.
pessimism [ˈpesəˌmɪzəm]: n. a tendency to believe that bad things will happen OPP optimism悲观,悲观主义
- If you are always having pessimism about the future, you will not lead a happy life.
- Due to the extent of the war's casualties, there is a deep pessimism about the progress of Western civilization.
- Unemployed workers in the 1970s had a deep pessimism about the economic depression.
artillery [ɑrˈtɪl(ə)ri]: n. large guns, either on wheels or fixed in one place大炮, 炮兵
- The royal armory was said to be full of artillery.
- These knights defended the king against the Asiatic nomads using a special kind of artillery.
- This kind of artillery was invented with no other aim than to attack the wall.
bombard [bɑmˈbɑrd] bombardment: v.n. to attack a place for a long time using large weapons, bombs etc炮轰；轰击
- The military confrontation may lead to a prominent bombardment.
- Bombarded with machine guns for two days, the city was virtually lost.
- Being bombarded with machine guns, we can't advance anymore without new equipment.
canal [kəˈnæl]: n. a long passage dug into the ground and filled with water, either for boats to travel along, or to take water to a place运河
- My wife and I used to walk on the pavement along the canal.
- It was near the canal that we met our first cat, Miumiu.
- On holidays, people swamped upon the park near the canal having picnics with their friends or families.
debris [dəˈbri]: n. the pieces of something that are left after it has been destroyed in an accident, explosion etc碎片, 残骸
- Because of the iron debris left in your stomach, we shall have an operation as soon as possible.
- If the police arrived on the scene, they would find nothing but the debris.
- This is why I spent a lot of time dealing with the debris of the body.
grain [ɡreɪn]: n. the seeds of crops such as corn, wheat, or rice that are gathered for use as food, or these crops themselves谷物
- Obviously, the grain is not your precious daughter's favorite food.
- Indeed, the grain harvest will bring our people to the next victory.
- On that occasion, people will hold a celebration to expect the grain harvest next year.
homeless [ˈhoʊmləs]: adj. without a home无家的, 无家可归的
- If you keep gambling, we will be homeless.
- The beautiful dog seems to be homeless, maybe we can adopt her.
- It occurs to my wife to figure out whether the cat is homeless or not.
paralyzed [ˈperəˌlaɪzd]: adj. unable to move part or all of your body or feel it瘫痪的,麻痹的
- The man who fought for our country is paralyzed for the rest of his life.
- After the accident, I was afflicted by the paralyzed leg.
- Afflicted by the paralyzed leg, the soldier tried to do away with himself but failed.
chaos [ˈkeɪˌɑs] chaotic: n.adj. a chaotic situation is one in which everything is happening in a confused way混乱的
- Because of political chaos, a new law is often opposite to the former law.
- Suffering from political chaos, the empire lost control of its two colonies in Africa.
- People all over England are concerned about the military chaos in Eastern Europe.
output [ˈaʊtˌpʊt]: n. the amount of goods or work produced by a person, machine, factory etc ⇨ production产量, 输出
- The output of industry is expected to triple by next year.
- The new kind of tomato scientists cultivated is expected to double output.
- The output of a calculator doesn't agree with our calculation.
affairs [əˈfer]: n. public or political events and activities事务, 事件
- The United States is reluctant to intervene in domestic affairs in other countries.
- Our domestic affairs are none of your business, the spokesman claimed.
- The two superpowers promised not to intervene in African affairs.
--------------------
with great joy: 怀着极大的喜悦
- My wife told me she was pregnant with great joy.
- My dog pounced on me and licked my hands with great joy.
- The hunter realized that it must be a puma at large with great joy.
stay awake: 保持清醒
- On that occasion, you'd better stay awake.
- I am grateful to those who asked me to stay awake when I was in the face of a pyramid scheme. 
- Staying awake, he went up the tower to see what had happened.
awake to sth.: 意识到某事
- Awaking to the failure of the game, the player let out a cry.
- Awaking to the danger in the ring, the drunk stepped aside to avoid the attack of the cow.
- Awaking to the seriousness of the event, he lost no time in informing his superior.
in ruins: 一片废墟
- The city in ruins used to be a shelter for millions of peasants.
- The city in ruins was being bombarded with long-last artillery.
- The nomads pushed their way westward and left the city in ruins.
charnel house: 尸骨堆积处
- The house used to be a charnel house for a hospital.
- Military chaos turned the palace into a charnel house.
- You shall send your dead child to a charnel house.
an air raid: 空袭
- He hasn't been killed in the air raid.
- In an air raid, he expressed his love to the girl and promised to marry her in a few years.
- In an air raid, the teacher succeeded in teaching the children the last lesson.
be without homes: 无家可归
- People without homes were appalled at the prosperity of the palace.
- People without homes gathered around the City Hall and asked for food.
- People without homes organized a number of marches.
be on the road to sp.: 在通往某处的路上
- 'I am on the road to school', I said in a weak voice.
- She may be on the road to school.
- She must be on the road to school.
be dependent on sth./sb.: 依赖某人/某物
- I am dependent on the supply of pocket money which my parent give on a daily basis.
- She is dependent on the money her boyfriend offers.
- The philosophes were dependent on the money the hostess of the salon offered.
the specter of sth.: 某物的幽灵(引起发生某事的恐惧)
- The military confrontation between two regimes raised the specter of civil war.
- The priest burnt a church down, which raised the specter of civil war.
- Their rivalry raised the specter of nuclear war.
** summary
The end of World War II was met by great joy.
But after the victory parades and celebrations, Europeans realized that their civilization in ruins.
As Winston Churchil put it,
	Europe was now a rubble heap, a charnel house, a breeding groud of pestilence and hate.
Forty million people had been killed and many of the great cities remained heaps of rubble.
Millions of Europeans not only were homeless, but also faced starvation.
Yet despite the chaos, Europe was soon recovering.
Besides, the colonial empires of the European nations rapidly disintegrated.
At the Cold War the conflict between the United States and the Soviet Union
	divided these nations into two armed camps.
Their rivalry raised the spector of nuclear war.
** summary2
The end of World War II was met with great joy.
But after the victory parades and celebrations,
	Europeans realized that their civilization was in ruins.
As Winston Churchill put it,
	Europe was now a rubble heap, a charnel house, a breeding ground of pestilence and hate.
Forty million people had been killed and many of the great cities remained heaps of rubble.
Millions of Europeans not only were homeless but also faced starvation.
Yet despite the chaos, Europe was soon recovering.
Besides, the colonial empires of the European nations rapidly disintegrated.
During the Cold War, the conflict between the United States and the Soviet Union
	divided these nations into two armed camps.
Their rivalry raised the specter of nuclear war, which seemed to destroy the world.
