* 25 British troops in the trenches wait for the signal to attack

ON JULY 1, 1916, British and French infantry forces attacked
German defensive lines along a 25-mile front near the Somme River
in France. Each soldier carried almost 70 pounds of equipment,
making it ‘‘impossible to move much quicker than a slow walk.’’
German machine guns soon opened fire: ‘‘We were able to see our
comrades move forward in an attempt to cross No-Man’s Land,
only to be mown down like meadow grass,’’ recalled one British soldier. ‘‘I felt sick at the sight of this carnage and remember weeping.’’1 In one day, more than 21,000 British soldiers died. After six
months of fighting, the British had advanced 5 miles; one million
British, French, and German soldiers had been killed or wounded.

Philip Gibbs, an English war correspondent, described what he
saw in the German trenches that the British forces overran:
‘‘Victory! . . . Some of the German dead were young boys, too young
to be killed for old men’s crimes, and others might have been old or
young. One could not tell because they had no faces, and were just
masses of raw flesh in rags of uniforms. Legs and arms lay separate
without any bodies thereabout.’’2

World War I (1914--1918) was the defining event of the twentieth century. It devastated the prewar economic, social, and political
order of Europe, and its uncertain outcome prepared the way for
an even more destructive war. Overwhelmed by the size of its battles, the extent of its casualties, and its effects on all facets of life,
contemporaries referred to it simply as the ‘‘Great War.’’

The Great War was all the more disturbing to Europeans because it came after what many considered an age of progress. There
had been international crises before 1914, but somehow Europeans
had managed to avoid serious and prolonged military confrontations. Material prosperity and a fervid belief in scientific and technological progress had convinced many people that the world was
on the verge of creating the utopia that humans had dreamed of for
centuries. The historian Arnold Toynbee expressed what the pre--
World War I era had meant to his generation:

[We had expected] that life throughout the World would become more rational, more humane, and more democratic and
that, slowly, but surely, political democracy would produce
greater social justice. We had also expected that the progress of
science and technology would make mankind richer, and that
this increasing wealth would gradually spread from a minority
to a majority. We had expected that all this would happen
peacefully. In fact we thought that mankind’s course was set for
an earthly paradise.3

After 1918, it was no longer possible to maintain naive illusions about the progress of Western civilization. As World War I
was followed by the destructiveness of World War II and the mass
murder machines of totalitarian regimes, it became all too apparent
that instead of a utopia, European civilization had become a nightmare. The Great War resulted not only in great loss of life and
property but also in the annihilation of one of the basic intellectual
precepts on which Western civilization had been thought to have
been founded---the belief in progress. World War I and the revolutions it spawned can properly be seen as the first stage in the crisis
of the twentieth century
