* 01 Ruins of the ancient Sumerian city of Uruk

IN 1849, A DARING YOUNG Englishman made a hazardous
journey into the deserts and swamps of southern Iraq. Moving
south down the banks of the Euphrates River while braving high
winds and temperatures that reached 120 degrees Fahrenheit,
William Loftus led a small expedition in search of the roots of civilization. As he said, ‘‘From our childhood we have been led to regard
this place as the cradle of the human race.’’
Guided by native Arabs into the southernmost reaches of Iraq,
Loftus and his small group of explorers were soon overwhelmed by
what they saw. He wrote, ‘‘I know of nothing more exciting or impressive than the first sight of one of these great piles, looming in
solitary grandeur from the surrounding plains and marshes.’’ One
of these piles, known to the natives as the mound of Warka, contained the ruins of Uruk, one of the first cities in the world and
part of the world’s first civilization.
Southwest Asia was one area in the world where civilization
began. Although Western civilization did not yet exist, its origins
can be traced back to the ancient Near East, where people in Southwest Asia and in Egypt, in northeastern Africa, developed organized
societies, invented writing, and created the ideas and institutions
that we associate with civilization. The later Greeks and Romans
who played such a crucial role in the development of Western civilization, were nourished and influenced by these older Near Eastern
societies. It is appropriate, therefore, to begin our story of Western
civilization with the early civilizations of Southwest Asia and Egypt.
Before considering them, however, we must briefly examine prehistory and observe how human beings made the shift from hunting
and gathering to agricultural communities and ultimately to cities
and civilization.
