#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>

CHAPTER 5 THE ROMAN REPUBLIC


CHAPTER OUTLINE AND FOCUS QUESTIONS


The Emergence of Rome


Q What impact did geography have on the history of Rome, and what influence did the Etruscans and Greeks have on early Roman history?


The Roman Republic (c. 509--264 B.C.)


Q What were the major political institutions of the Roman Republic, and what policies and institutions help explain the Romans’ success in conquering Italy?


The Roman Conquest of the Mediterranean (264--133 B.C.)


Q How did Rome achieve its empire from 264 to 133 B.C., and what is meant by the phrase ‘‘Roman imperialism’’?


Society and Culture in the Roman World


Q How did the acquisition of an empire affect Roman social and economic institutions, values and attitudes, and art and literature?


The Decline and Fall of the Roman Republic (133--31 B.C.)


Q What were the main problems Rome faced during the last century of the Republic, and how were they ultimately resolved?


CRITICAL THINKING


Q What did the Roman poet Horace mean when he wrote, ‘‘Captive Greece took captive her rude conqueror’’?


EARLY ROMAN HISTORY is filled with legendary tales of the heroes who made Rome great. One of the best known is the story of Horatius at the bridge. Threatened by attack from the neighboring Etruscans, Roman farmers abandoned their fields and moved into the city, where they would be protected by the walls. One weak point in the Roman defenses, however, was a wooden bridge over the Tiber River. Horatius was on guard at the bridge when a sudden assault by the Etruscans caused many Roman troops to throw down their weapons and flee. Horatius urged them to make a stand at the bridge to protect Rome; when they hesitated, as a last resort he told them to destroy the bridge behind him while he held the Etruscans back. Astonished at the sight of a single defender, the confused Etruscans threw their spears at Horatius, who caught them on his shield and barred the way. By the time the Etruscans had regrouped and were about to overwhelm the lone defender, the Roman soldiers brought down the bridge. When Horatius heard the bridge crash into the river behind him, he dived fully armed into the water and swam safely to the other side through a hail of arrows. Rome had been saved by the courageous act of a Roman who knew his duty and was determined to carry it out. Courage, duty, determination---these qualities would also serve the many Romans who believed that it was their mission to rule nations and peoples.


In the first millennium B.C., a group of Latin-speaking people established a small community on the plain of Latium on the Italian peninsula. This community, called Rome, was one of the numerous settlements founded by Latin-speaking peoples throughout Latium and the rest of Italy. Roman history is basically the story of the Romans’ conquest of the plain of Latium, then Italy, and finally the entire Mediterranean region. How were they able to do this? The Romans made the right decisions at the right time; in other words, they had political wisdom.


They were also practical. Unlike the Greeks, who reserved their citizenship for small, select groups, the Romans often offered citizenship to the peoples they conquered, thus laying the groundwork for a strong, integrated empire. The Romans also did not hesitate to borrow ideas and culture from the Greeks. Roman strength lay in government, law, and engineering. The Romans knew how to govern people, establish legal structures, and construct the roads that took them to the ends of the known world. Throughout their empire, they carried their law, their political institutions, their engineering skills, and their Latin language. And even after the Romans were gone, those same gifts continued to play an important role in the civilizations that came after them.


The Emergence of Rome


Q Focus Question: What impact did geography have on the history of Rome, and what influence did the Etruscans and Greeks have on early Roman history?


Italy is a peninsula extending about 750 miles from north to south (see Map 5.1). It is not very wide, however, averaging about 120 miles across. The Apennine Mountains traverse the peninsula from north to south, forming a ridge down the middle that divides west from east. Nevertheless, Italy has some fairly large fertile plains ideal for farming. Most important were the Po River valley in the north, probably the most fertile agricultural area; the plain of Latium, on which Rome was located; and Campania, to the south of Latium. To the east of the Italian peninsula is the Adriatic Sea, and to the west, the Tyrrhenian Sea with the nearby large islands of Corsica and Sardinia. Sicily lies just west of the toe of the boot-shaped Italian peninsula.


Geography had an impact on Roman history. Although the Apennines bisect Italy, they are less rugged than the mountain ranges of Greece and so did not divide the peninsula into many small isolated communities. Italy also possessed considerably more productive farmland than Greece, enabling it to support a large population. Rome’s location was favorable from a geographical point of view. Located 18 miles inland on the Tiber River, Rome had access to the sea and yet was far enough inland to be safe from pirates. Built on seven hills, it was easily defended. Situated where the Tiber could be readily forded, Rome became a natural crossing point for north-south traffic in western Italy. All in all, Rome had a good central location in Italy from which to expand.


Moreover, the Italian peninsula juts into the Mediterranean, making it an important crossroads between the western and eastern parts of that sea. Once Rome had unified Italy, involvement in affairs throughout the region was natural. And after the Romans had conquered their Mediterranean empire, Italy’s central location made their task of governing that empire considerably easier.


The Greeks in Italy


We know little about the Indo-European peoples who moved into Italy during the second half of the second millennium B.C. By the first millennium B.C., other peoples had also settled in Italy, the two most notable being the Greeks and the Etruscans. The Greeks arrived on the Italian peninsula in large numbers during the age of Greek colonization (750-- 550 B.C.; see Chapter 3). Initially, the Greeks settled in southern Italy and gradually migrated around the coast and up the peninsula as far as Brindisi. They also occupied the eastern two-thirds of Sicily. Ultimately, the Greeks had considerable influence on Rome. They cultivated olives and grapes, passed on their alphabetic system of writing, and provided artistic and cultural models through their sculpture, architecture, and literature. Indeed, many historians view Roman culture as a continuation of Greek culture. Whereas Greek influence had initially touched Rome indirectly through the Etruscans, the Roman conquest of southern Italy and Sicily brought the Romans into direct contact with Greeks.


The Etruscans


The initial development of Rome was influenced most by the Etruscans, who had settled north of Rome in Etruria. The origins of the Etruscans are not clear, but after 650 B.C., they expanded in Italy and became the dominant cultural and economic force in a number of areas. To the north, they moved into north-central Italy, including the Po valley. To the south, according to Roman tradition and archaeological evidence, they controlled Rome and possibly all of Latium. From Latium they moved south and came into direct conflict with Greek colonists in southern Italy. In the sixth century B.C., the Etruscans were at the height of their power. But by 480 B.C., their power had begun to decline, and by 400 B.C., they were confined to Etruria itself. Later they were invaded by Celts from Gaul and then conquered by the Romans. But by then the Etruscans had made an impact. By transforming villages into towns and cities, they brought urbanization to northern and central Italy (as the Greeks had done in southern Italy). Rome was the Etruscans’ most enduring product. 


Early Rome


According to Roman legend, Rome was founded by twin brothers, Romulus and Remus, in 753 B.C., and archaeologists have found that around that time, there was a settlement consisting of huts on the tops of several of Rome’s hills. The early Romans, basically a pastoral people, spoke Latin, which, like Greek, belongs to the Indo-European family of languages (see Table 2.1 in Chapter 2). The Roman historical tradition also maintained that early Rome (753--509 B.C.) had been under the control of seven kings and that two of the last three had been Etruscans. Some historians believe that the king list may have some historical accuracy. What is certain is that Rome did fall under the influence of the Etruscans for about one hundred years during the period of the kings.


By the beginning of the sixth century, under Etruscan influence, Rome began to change from a pastoral community to an actual city. The Etruscans were responsible for an outstanding building program. They constructed the first roadbed of the chief street through Rome---the Sacred Way---before 575 B.C. and oversaw the development of temples, markets, shops, streets, and houses. By 509 B.C., the date when the monarchy was supposedly overthrown and a republican form of government was established, a new Rome had emerged, essentially as a result of the fusion of Etruscan and native Roman elements. After Rome had expanded over its seven hills and the valleys in between, the Servian Wall was built to surround the city in the fourth century B.C.  


The Roman Republic (c. 509--264 B.C.)


Q Focus Question: What were the major political institutions of the Roman Republic, and what policies and institutions help explain the Romans’ success in conquering Italy?


The transition from a monarchy to a republican government was not easy. Rome felt threatened by enemies from every direction and, in the process of meeting these threats, embarked on a course of military expansion that led to the conquest of the entire Italian peninsula. During this period of expansion in Italy, the Roman Republic developed political institutions that were in many ways determined by the social divisions that existed within the community.


The Roman State


In politics and law, as in conquest, the Romans took a practical approach and fashioned political institutions in response to problems as they arose. Hence it is important to remember that the political institutions we will discuss evolved over a period of centuries.


Political Institutions


The chief executive officers of the Roman Republic were the consuls and praetors. Two consuls, chosen annually, administered the government and led the Roman army into battle. They possessed imperium, ‘‘the right to command.’’ In 366 B.C., a new office, that of the praetor, was created. The praetor also possessed imperium and could govern Rome when the consuls were away from the city and could also lead armies. The praetor’s primary function, however, was the execution of justice. He was in charge of the civil law as it applied to Roman citizens. In 242 B.C., reflecting Rome’s growth, another praetor was added to judge cases in which one or both people were noncitizens.


As Rome expanded into the Mediterranean, additional praetors were established to govern the newly conquered provinces (two in 227, two more in 197). But as the number of provinces continued to grow, the Romans devised a new system in which ex-consuls and expraetors who had served their one-year terms were given the title of proconsul and propraetor and sent out as provincial governors. This demonstrates once again the Romans’ practical solution to an immediate problem. It was reasonable to assume that officials with governmental experience would make good provincial administrators, although this was not always true in practice due to the opportunities for financial corruption in the provinces.


The Roman state also had administrative officials with specialized duties. Quaestors were assigned to assist consuls and praetors in the administration of financial affairs. Aediles supervised the public games and watched over the grain supply of the city, a major problem for a rapidly growing urban community that relied on imported grain to feed its population.


The Roman senate held an especially important position in the Roman Republic. The senate, or council of elders, was a select group of about three hundred men who served for life. The senate was not a legislative body and could only advise the magistrates. The advice of the senate was not taken lightly, however, and by the third century B.C., it had virtually the force of law. No doubt the prestige of the senate’s members furthered this development. But it also helped that the senate met continuously, whereas the chief magistrates changed annually and the popular assemblies operated slowly and met only periodically.


The Roman Republic possessed a number of popular assemblies. The most important was the centuriate assembly, essentially the Roman army functioning in its political role. Organized by classes based on wealth, it was structured in such a way that the wealthiest citizens always had a majority. The centuriate assembly elected the chief magistrates and passed laws. Another assembly, the council of the plebs, came into being in 471 B.C. as a result of the struggle of the orders (see the next section).


The government of the Roman Republic, then, consisted of three major elements. Two consuls and later other elected officials served as magistrates and ran the state. An assembly of adult males (the centuriate assembly), controlled by the wealthiest citizens, elected these officials, while the senate, a small group of large landowners, advised them. The Roman state, then, was an aristocratic republic controlled by a relatively small group of privileged people.


The Struggle of the Orders: Social Divisions in the Roman Republic


The most noticeable element in the social organization of early Rome was the division between two groups---the patricians and the plebeians. The patrician class in Rome consisted of families who were descended from the original senators appointed during the period of the kings. Their initial prominence was probably due to their wealth as great landowners. Thus patricians constituted an aristocratic governing class. Only they could be consuls, magistrates, and senators. Through their patronage of large numbers of dependent clients, they could control the centuriate assembly and many other facets of Roman life.


The plebeians constituted the considerably larger group of ‘‘independent, unprivileged, poorer, and vulnerable men’’ as well as large nonpatrician landowners, less wealthy landholders, craftspeople, merchants, and small farmers. Although they were citizens, they did not possess the same rights as the patricians. Both patricians and plebeians could vote, but only the patricians could be elected to governmental offices. Both had the right to make legal contracts and marriages, but intermarriage between patricians and plebeians was forbidden. At the beginning of the fifth century B.C., the plebeians began a struggle to seek both political and social equality with the patricians.


The first success of the plebeians came in 494 B.C., when they withdrew physically from the state. The patricians, realizing that they could not defend Rome by themselves, were forced to compromise. Two new officials known as tribunes of the plebs were instituted (later raised to five and then ten in number). These tribunes were given the power to protect plebeians against arrest by patrician magistrates. Moreover, after a new popular assembly for plebeians only, called the council of the plebs, was created in 471 B.C., the tribunes became responsible for convoking it and placing proposals before it.


If adopted, these measures became plebiscita (‘‘it is the opinion of the plebs’’), but they were binding only on the plebeians, not the patricians. Nevertheless, the council of the plebs gave the plebeians considerable political leverage. After 445 B.C., when a law allowed patricians and plebeians to intermarry, the division between the two groups became less important. In the fourth century B.C., the consulship was opened to the plebeians. The climax of the struggle between the orders came in 287 B.C. with passage of a law that stipulated that all plebiscita passed by the council of the plebs had the force of law and were binding on the entire community, including patricians.


The struggle between the orders, then, had a significant impact on the development of the Roman constitution. Plebeians could hold the highest offices of state, they could intermarry with the patricians, and they could pass laws binding on the entire Roman community. Although the struggle had been long, the Romans had handled it by compromise, not violent revolution. Theoretically, by 287 B.C., all Roman citizens were equal under the law, and all could strive for political office. But in reality, as a result of the right of intermarriage, a select number of patrician and plebeian families formed a new senatorial aristocracy that came to dominate the political offices. The Roman Republic had not become a democracy.


The Roman Conquest of Italy


At the beginning of the Republic, Rome was surrounded by enemies, including the Etruscans to the north and the Sabines, Volscians, and Aequi to the east and south. The Latin communities on the plain of Latium posed an even more immediate threat. If we are to believe Livy, one of the chief ancient sources for the history of the early Roman Republic, Rome was engaged in almost continuous warfare with its neighbors for the next hundred years.


In his account of these years, Livy provided a detailed narrative of Roman efforts. Many of Livy’s stories were legendary in character and indeed were modeled on events in Greek history. But Livy, writing in the first century B.C., used such stories to teach Romans the moral values and virtues that had made Rome great. These included tenacity, duty, courage, and especially discipline (see the box on p. 90). Indeed, Livy recounted stories of military leaders who executed their own sons for leaving their place in battle, a serious offense, since the success of the hoplite infantry depended on maintaining a precise order. These stories had little basis in fact, but like the story of George Washington and the cherry tree in American history, they provided mythic images to reinforce Roman patriotism.


By 338 B.C., Rome had crushed the Latin states in Latium. During the next fifty years, the Romans waged a fierce struggle with the Samnites, a hill people from the central Apennines, some of whom had settled in Campania, south of Rome. Rome was again victorious. The conquest of the Samnites gave Rome considerable control over a large part of Italy and also brought it into direct contact with the Greek communities of southern Italy. Soon after their conquest of the Samnites, the Romans were involved in hostilities with some of these Greek cities and by 267 B.C. had completed their conquest of southern Italy. After overrunning the remaining Etruscan states to the north in 264 B.C., Rome had conquered all of modern Italy except the extreme north.


To rule Italy, the Romans devised the Roman Confederation. Under this system, Rome allowed some peoples---especially the Latins---to have full Roman citizenship. Most of the remaining communities were made allies. They remained free to run their own local affairs but were required to provide soldiers for Rome. Moreover, the Romans made it clear that loyal allies could improve their status and even aspire to becoming Roman citizens. Thus the Romans had found a way to give conquered peoples a stake in Rome’s success.


The Romans’ conquest of Italy can hardly be said to be the result of a direct policy of expansion. Much of it was opportunistic. The Romans did not hesitate to act when they felt that their security was threatened. And surrounded by potential enemies, Rome in a sense never felt secure. Yet once embarked on a course of expansion, the Romans pursued consistent policies that help explain their success. The Romans excelled at making wise diplomatic decisions. Though firm and even cruel when necessary---rebellions were put down without mercy--- they were also shrewd in extending citizenship and allowing autonomy in domestic affairs. In addition, the Romans were not only good soldiers but persistent ones as well. The loss of an army or a fleet did not cause them to quit but instead spurred them on to build new armies and new fleets. Finally, the Romans had a practical sense of strategy. As they conquered, they settled Romans and Latins in new communities outside Latium. By 264 B.C., the Romans had established fortified towns at all strategic locations. By building roads to these settlements and connecting them, the Romans assured themselves of an impressive military and communications network that enabled them to rule effectively and efficiently. Insisting on military service from the allies in the Roman Confederation, Rome essentially mobilized the entire military manpower of all Italy for its wars.


The Roman Conquest of the Mediterranean (264--133 B.C.)


Q Focus Question: How did Rome achieve its empire from 264 to 133 B.C., and what is meant by the phrase ‘‘Roman imperialism’’? 


After their conquest of the Italian peninsula, the Romans found themselves face to face with a formidable Mediterranean power---Carthage. Founded around 800 B.C. by Phoenicians from Tyre, Carthage in North Africa was located in a favorable position for commanding Mediterranean trade routes and had become an important commercial center (see Map 5.2). It had become politically and militarily strong as well. By the third century B.C., the Carthaginian empire included the coast of northern Africa, southern Spain, Sardinia, Corsica, and western Sicily. With its monopoly of western Mediterranean trade, Carthage was the largest and richest state in the area. The presence of Carthaginians in Sicily made the Romans apprehensive about Carthaginian encroachment on the Italian coast. In 264 B.C., mutual suspicions drove the two powers into a lengthy struggle for control of the western Mediterranean.


The Struggle with Carthage


The First Punic War (264--241 B.C.) (the Latin word for Phoenician was Punicus) began when the Romans decided to intervene in a struggle between two Sicilian cities by sending an army to Sicily. The Carthaginians, who considered Sicily within their own sphere of influence, deemed this just cause for war. In going to war, both sides determined on the conquest of Sicily. The Romans realized that the war would be long and drawn out if they could not supplement land operations with a navy and promptly developed a substantial naval fleet. The Carthaginians, for their part, had difficulty finding enough mercenaries to continue the fight. After a long struggle in which both sides lost battles in northern Africa and Sicily, a Roman fleet defeated the Carthaginian navy off Sicily, and the war quickly came to an end. In 241 B.C., Carthage gave up all rights to Sicily and had to pay an indemnity.


Hannibal and the Second Punic War


After the war, Carthage made an unexpected recovery and extended its domains in Spain to compensate for the territory lost to Rome. The Carthaginians proceeded to organize a formidable land army in the event of a second war with Rome, because they realized that defeating Rome on land was essential to victory. When the Romans encouraged one of Carthage’s Spanish allies to revolt against Carthage, Hannibal, the greatest of the Carthaginian generals, struck back, beginning the Second Punic War (218--201 B.C.). This time the Carthaginians decided to bring the war home to the Romans by fighting in their own backyard. Hannibal went into Spain, moved east, and crossed the Alps with an army of thirty to forty thousand men and six thousand horses and elephants. The Alps took a toll on the Carthaginian army; most of the elephants did not survive the trip. The remaining army, however, posed a real threat. At Cannae in 216 B.C., the Romans lost an army of almost forty thousand men. Rome seemed on the brink of disaster but refused to give up, raised yet another army, and gradually recovered. Although Hannibal remained free to roam in Italy, he had neither the men nor the equipment to lay siege to the major cities, no less Rome itself. The Romans began to reconquer some of the Italian cities that had rebelled against Roman rule after Hannibal’s successes. More important, the Romans pursued a strategy that aimed at undermining the Carthaginian empire in Spain. By 206 B.C., the Romans had pushed the Carthaginians out of Spain.


The Romans then took the war directly to Carthage. Late in 204 B.C., a Roman army under Publius Cornelius Scipio, later known as Scipio Africanus, moved from Sicily into northern Africa and forced the Carthaginians to recall Hannibal from Italy. At the Battle of Zama in 202 B.C., the Romans decisively defeated Hannibal’s forces, and the war was essentially over. Eventually, Hannibal left Carthage and went to help Antiochus, the ruler of the Seleucid kingdom, in his struggle with Rome. After Antiochus made peace with the Romans, Hannibal fled to Bithynia, near the Black Sea. Pursued by the Romans, Hannibal declared, ‘‘Let us free Rome of her dread of one old man,’’ and committed suicide.


By the peace treaty signed in 201 B.C. by the Carthaginians and the Romans, Carthage lost Spain, agreed to pay an indemnity, and promised not to go to war without Rome’s permission. Spain, like Sicily, Corsica, and Sardinia earlier, was made into a Roman province. Rome had become the dominant power in the western Mediterranean.  


The Destruction of Carthage


But some Romans wanted even more. A number of prominent Romans, especially the conservative politician Cato, advocated the complete destruction of Carthage. Cato ended every speech he made to the senate with the words, ‘‘And I think Carthage must be destroyed.’’ When the Carthaginians technically broke their peace treaty with Rome by going to war against one of Rome’s North African allies who had been encroaching on Carthage’s home territory, the Romans declared war. Roman forces undertook their third and last war with Carthage (149--146 B.C.). This time Carthage was no match for the Romans, who in 146 B.C. seized this opportunity to carry out the final destruction of Carthage. The territory was made a Roman province called Africa.


The Eastern Mediterranean


During the Punic Wars, Rome had become acutely aware of the Hellenistic states of the eastern Mediterranean when the king of Macedonia made an alliance with Hannibal after the Roman defeat at Cannae. But Rome was preoccupied with the Carthaginians, and it was not until after the defeat of Carthage that Rome became involved in the world of Hellenistic politics as an advocate of the freedom of the Greek states. This support of the Greeks brought the Romans into conflict with both


Macedonia and the kingdom of the Seleucids. Roman military victories and diplomatic negotiations rearranged the territorial boundaries of the Hellenistic kingdoms and brought the Greek states their freedom in 196 B.C. For fifty years, the Romans tried to be a power broker in the affairs of the Greeks without direct control of their lands. When the effort failed, the Romans changed their policy. Macedonia was made a Roman province in 148 B.C., and when some of the Greek states rose in revolt against Rome’s restrictive policies, Rome acted decisively. The city of Corinth, leader of the revolt, was destroyed in 146 B.C. to teach the Greeks a lesson, and Greece was placed under the control of the Roman governor of Macedonia. Thirteen years later, in 133 B.C., the king of Pergamum deeded his kingdom to Rome, giving Rome its first province in Asia. Rome was now master of the Mediterranean Sea. 

The Nature of Roman Imperialism


Rome’s empire was built in three stages: the conquest of Italy, the conflict with Carthage and expansion into the western Mediterranean, and the involvement with and domination of the Hellenistic kingdoms in the eastern Mediterranean. The Romans did not have a master plan for the creation of an empire; as it had been in Italy, much of their continued expansion was opportunistic, in response to perceived threats to their security. The more they expanded, the more threats to their security appeared on the horizon, involving them in yet more conflicts. Indeed, the Romans liked to portray themselves as declaring war only for defensive reasons or to protect allies. That is only part of the story, however. It is likely, as some historians have suggested, that at some point a group of Roman aristocratic leaders emerged who favored expansion both for the glory it offered and for the economic benefits it provided. Certainly, by the second century B.C., aristocratic senators perceived new opportunities for lucrative foreign commands, enormous spoils of war, and an abundant supply of slave labor for their growing landed estates. By that same time, the destruction of Corinth and Carthage indicated that Roman imperialism had become more arrogant and brutal as well. Rome’s foreign success also had enormous repercussions for the internal development of the Roman Republic.


Evolution of the Roman Army


By the fourth century B.C., the Roman army consisted of four legions, each made up of four thousand to five thousand men; each legion had about three hundred cavalry and the rest infantry. The infantry consisted of three lines of battle. The hastati (spearmen), consisting of the youngest recruits, formed the front line; they were armed with heavy spears and short swords and were protected by a large oval shield, helmet, breastplate, and greaves (shin guards). The principes (chief men), armed and protected like the hastati, formed the second line. The third line of battle was formed by the triarii (third-rank men), who knelt behind the first two lines, ready to move up and fill any gaps. A fourth group of troops, poor citizens who wore cloaks but no armor and were lightly armed, functioned as skirmishers who usually returned to the rear lines after their initial contact with the enemy to form backup reserves.


In the early Republic, the army was recruited from citizens between the ages of eighteen and forty-six who had the resources to equip themselves for battle. Since most of them were farmers, they enrolled only for a year, campaigned during the summer months, and returned home in time for the fall harvest. Later, during the Punic Wars of the third century B.C., the period of service had to be extended, although this was resisted by farmers whose livelihoods could be severely harmed by a long absence. Nevertheless, after the disastrous battle of Cannae in 216 B.C., the Romans were forced to recruit larger armies, and the number of legions rose to twenty-five. Major changes in recruitment would not come until the first century B.C. with the military reforms of Marius (see ‘‘A New Role for the Roman Army: Marius and Sulla’’ later in this chapter).


Society and Culture in the Roman World


Q Focus Question: How did the acquisition of an empire affect Roman social and economic institutions, values and attitudes, and art and literature?


One of the most noticeable aspects of Roman culture and society is the impact of the Greeks. The Romans had experienced Greek influence early on through the Greek cities in southern Italy. By the end of the third century B.C., however, Greek civilization was playing an ever-increasing role in Roman culture. Greek ambassadors, merchants, and artists traveled to Rome and spread Greek thought and practices. After their conquest of the Hellenistic kingdoms, Roman military commanders shipped Greek manuscripts and artworks back to Rome. Multitudes of educated Greek slaves were used in Roman households. Virtually every area of Roman life, from literature and philosophy to religion and education, was affected by Greek models. Rich Romans hired Greek tutors and sent their sons to Athens to study. As the Roman poet Horace said, ‘‘Captive Greece took captive her rude conqueror.’’ Greek thought captivated the less sophisticated Roman mind, and the Romans became willing transmitters of Greek culture---not, however, without some resistance from Romans who had nothing but contempt for Greek politics and who feared the end of old Roman values. Even those who favored Greek culture blamed the Greeks for Rome’s new vices, including a taste for luxury and homosexual practices.


Roman Religion


Every aspect of Roman society was permeated with religion. The official state religion focused on the worship of a pantheon of gods and goddesses, including Jupiter, Juno, Minerva, and Mars. As Rome developed and came into contact with other peoples and gods, the community simply adopted new deities. Hence the Greek Hermes became the Roman Mercury. Eventually, a complete amalgamation of Greek and Roman religion occurred, giving the Romans and the Greeks essentially a single ‘‘Greco-Roman’’ religion.


Roman religion focused on the worship of the gods for a very practical reason---human beings were thought to be totally dependent on them. The exact performance of ritual was crucial to establishing a right relationship with the gods. What was true for individuals was also valid for the state: it also had to observe correct ritual to receive its reward. Accurate performance of ritual was performed by a college of priests or pontiffs, who thus bore responsibility for maintaining the right relationship between the state and the gods. If the rituals were performed correctly, the Romans would obtain the ‘‘peace of the gods.’’ No doubt the Roman success in creating an empire was a visible confirmation of divine favor. As Cicero, the first-century B.C. politician and writer, claimed, ‘‘We have overcome all the nations of the world, because we have realized that the world is directed and governed by the gods.’’1


Just as the state had an official cult, so did families. Because the family was regarded as a small state within the state, it had its own household cults, which included Janus, the spirit of the doorway, and Vesta, goddess of the hearth. Here, too, proper ritual was important, and it was the responsibility of the paterfamilias as head of the family to ensure that religious obligations were properly fulfilled.


Religious festivals were an important part of Roman religious practice. There were two kinds: public festivals ordained and paid for by the state and private festivals celebrated by individuals and families. By the mid-second century B.C., six public festivals were celebrated annually, each lasting several days. The practice of holding games also grew out of religious festivals. The games were inaugurated in honor of Jupiter Optimus Maximus (‘‘best and greatest’’), the patron deity of Rome, but had become annual events by 366 B.C. In the late Republic, both the number of games and the number of days they lasted were increased. Originally, the games consisted of chariot racing in the Circus Maximus; later, animal hunts and theatrical performances were added. In the empire, gladiatorial contests would become the primary focus (see Chapter 6).


The Growth of Slavery


Slavery was a common institution throughout the ancient world, but no people possessed more slaves or relied so much on slave labor as the Romans eventually did. Before the third century B.C., a small Roman farmer might possess one or two slaves who would help farm his few acres and perform domestic chores. These slaves would most likely be from Italy and be regarded as part of the family household. Only the very rich would have large numbers of slaves.


The Roman conquest of the Mediterranean brought a drastic change in the use of slaves. Large numbers of foreign slaves were brought back to Italy. During the Republic, then, the chief source of slaves was from capture in war, followed by piracy. Of course, the children of slaves also became slaves. While some Roman generals brought back slaves to be sold to benefit the public treasury, ambitious generals of the first century B.C., such as Pompey and Caesar, made personal fortunes by treating slaves captured by their armies as private property.


Slaves were used in many ways in Roman society. The rich, of course, owned the most and the best. In the late Republic, it became a badge of prestige to be attended by many slaves. Greeks were in much demand as tutors, musicians, doctors, and artists. Roman businessmen would employ them as shop assistants or artisans. Slaves were also used as farm laborers; in fact, huge gangs of slaves living in pitiful conditions worked the large landed estates known as latifundia. Cato the Elder argued that it was cheaper to work slaves to death and then replace them than to treat them well. Many slaves of all nationalities were used as menial household workers, such as cooks, valets, waiters, cleaners, and gardeners. Roads, aqueducts, and other public facilities were constructed by contractors using slave labor. The total number of slaves is difficult to judge---estimates vary from 20 to 30 percent of the population.


It is also difficult to generalize about the treatment of Roman slaves. There are numerous instances of humane treatment by masters and situations where slaves even protected their owners from danger out of gratitude and esteem. But slaves were also subject to severe punishments, torture, abuse, and hard labor that drove some to run away or even revolt against their owners. The Republic had stringent laws against aiding a runaway slave. The murder of a master by a slave might mean the execution of all the other household slaves. Near the end of the second century B.C., large-scale slave revolts occurred in Sicily, where enormous gangs of slaves were subjected to horrible working conditions on large landed estates. Slaves were branded, beaten, inadequately fed, worked in chains, and housed at night in underground prisons. It took three years (135--132 B.C.) to crush a revolt of seventy thousand slaves, and the great revolt on Sicily (104--101 B.C.) involved most of the island and took a Roman army of seventeen thousand men to suppress. The most famous revolt on the Italian peninsula occurred in 73 B.C. Led by Spartacus, a slave who had been a Thracian gladiator, the revolt broke out in southern Italy and involved seventy thousand slaves. Spartacus managed to defeat several Roman armies before he was finally trapped and killed in southern Italy in 71 B.C. Six thousand of his followers were crucified, the traditional form of execution for slaves.


The Roman Family


At the heart of the Roman social structure stood the family, headed by the paterfamilias---the dominant male. The household also included the wife, sons with their wives and children, unmarried daughters, and slaves. A family was virtually a small state within the state, and the power of the paterfamilias was parallel to that of the state magistrates over the citizens. Like the Greeks, Roman males believed that the weakness of the female sex necessitated male guardians (see the box above). The paterfamilias exercised that authority; on his death, sons or close male relatives assumed the role of guardians. By the late Republic, however, although the rights of male guardians remained legally in effect, upper-class women found numerous ways to circumvent the power of their guardians.


Fathers arranged the marriages of daughters, although there are instances of mothers and daughters having influence on the choice. In the Republic, women married cum manu, ‘‘with legal control’’ passing from father to husband. By the mid-first century B.C., the dominant practice had changed to sine manu, ‘‘without legal control,’’ which meant that married daughters officially remained within the father’s legal power. Since the fathers of most married women were dead, not being in the ‘‘legal control’’ of a husband made possible independent property rights that forceful women could translate into considerable power within the household and outside it. Traditionally, Roman marriages were intended to be for life, but divorce was introduced in the third century B.C. and became relatively easy to obtain: either party could initiate it, and no one needed to prove the breakdown of the marriage. Divorce became especially prevalent in the first century B.C.---a period of political turmoil---when marriages were used to cement political alliances.


Some parents in upper-class families provided education for their daughters. Some girls had private tutors, and others may have gone to primary schools. But at the age when boys were entering secondary schools, girls were pushed into marriage. The legal minimum age was twelve, although fourteen was a more common age in practice. Although some Roman doctors warned that early pregnancies could be dangerous for young girls, early marriages persisted due to the desire to benefit from dowries as soon as possible and the reality of early mortality. A good example is Tullia, Cicero’s beloved daughter. She was married at sixteen, widowed at twentytwo, remarried one year later, divorced at twenty-eight, remarried at twenty-nine, and divorced at thirty-three. She died at thirty-four, not a particularly young age for females in Roman society.


The Evolution of Roman Law


One of Rome’s chief gifts to the Mediterranean world of its day and to succeeding generations was its development of law. The Twelve Tables of 450 B.C. were the first codification of Roman law (see the box on p. 99), and although inappropriate for later times, they were never officially abrogated and were still memorized by schoolboys in the first century B.C. Civil law derived from the Twelve Tables proved inadequate for later Roman needs, however, and gave way to corrections and additions by the praetors. On taking office, a praetor issued an edict listing his guidelines for dealing with different kinds of legal cases. The praetors were knowledgeable in law, but they also relied on Roman jurists---amateur law experts--- for advice in preparing their edicts. The interpretations of the jurists, often embodied in the edicts of the praetors, created a body of legal principles.


In 242 B.C., the Romans appointed a second praetor who was responsible for examining suits between a Roman and a non-Roman as well as between two nonRomans. The Romans found that although some of their rules of law could be used in these cases, special rules were often needed. These rules gave rise to a body of law known as the law of nations, defined by the Romans as ‘‘that part of the law which we apply both to ourselves and to foreigners.’’ But the influence of Greek philosophy, primarily Stoicism, led Romans in the late Republic to develop the idea of the law of nature---or universal divine law derived from right reason. The Romans came to view their law of nations as derived from or identical to this law of nature, thus giving Roman jurists a philosophical justification for systematizing Roman law according to basic principles.


The Development of Literature


The Romans produced little literature before the third century B.C., and the Latin literature that emerged in that century was strongly influenced by Greek models. The demand for plays at public festivals eventually led to a growing number of native playwrights. One of the best known was Plautus (c. 254--184 B.C.), who used plots from Greek New Comedy (see Chapter 4) for his own plays. The actors wore Greek costumes and Greek masks and portrayed the same basic stock characters: lecherous old men, skillful slaves, prostitutes, young men in love. Plautus wrote for the masses and became a very popular playwright in Rome.


In the last century of the Republic, the Romans began to produce a new poetry, less dependent on epic themes and more inclined to personal expression. Latin poets were now able to use various Greek forms to express their own feelings about people, social and political life, and love. The finest example of this can be seen in the work of Catullus (c. 87--54 B.C.), Rome’s ‘‘best lyric poet’’ and one of the greatest in world literature.


Catullus became a master at adapting and refining Greek forms of poetry to express his emotions. He wrote a variety of poems on, among other things, political figures, social customs, the use of language, the death of his brother, and the travails of love. Catullus became infatuated with Clodia, the promiscuous sister of a tribune and wife of a provincial governor, and addressed a number of poems to her (he called her Lesbia), describing his passionate love and hatred for her (Clodia had many other lovers besides Catullus):


You used to say that you wished to know only Catullus, Lesbia, and wouldn’t take even Jove before me! I didn’t regard you just as my mistress then: I cherished you as a father does his sons or his daughters’ husbands. Now that I know you, I burn for you even more fiercely, though I regard you as almost utterly worthless. How can that be, you ask? It’s because such cruelty forces lust to assume the shrunken place of affection2


Catullus’ ability to express in simple fashion his intense feelings and curiosity about himself and his world had a noticeable impact on later Latin poets.


The development of Roman prose was greatly aided by the practice of oratory. Romans had great respect for oratory since the ability to persuade people in public debate meant success in politics. Oratory was brought to perfection in a literary fashion by Cicero (106--43 B.C.), the best exemplar of the literary and intellectual interests of the senatorial elite of the late Republic and, indeed, the greatest prose writer of that period. For Cicero, oratory was not simply skillful speaking. An orator was a statesman, a man who achieved his highest goal by pursuing an active life in public affairs.


Later, when the turmoil of the late Republic forced him into semiretirement politically, Cicero became more interested in the writing of philosophical treatises. He served a most valuable purpose for Roman society by popularizing and making understandable the works of Greek philosophers. In his philosophical works, Cicero, more than anyone else, transmitted the classical intellectual heritage to the Western world. Cicero’s original contributions came in the field of politics. His works On the Laws and On the Republic provided fresh insights into political thought, including the need for a mixed constitution: ‘‘a moderate and well-balanced form of government which is a combination of the three simple good forms (monarchy, aristocracy, and democracy) is preferable even to monarchy.’’3 His emphasis on the need to pursue an active life to benefit and improve humankind would greatly influence the later Italian Renaissance.


Roman Art


The Romans were also dependent on the Greeks for artistic inspiration. During the third and second centuries B.C., they adopted many features of the Hellenistic style of art. The Romans developed a taste for Greek statues, which they placed not only in public buildings but also in their homes. Once demand outstripped the supply of original works, reproductions of Greek statues became fashionable. The Romans’ own portrait sculpture was characterized by an intense realism that included even unpleasant physical details. Wall paintings and frescoes in the houses of the rich realistically depicted landscapes, portraits, and scenes from mythological stories.


The Romans excelled in architecture, a highly practical art. Although they continued to employ Greek styles and made use of colonnades, rectangular structures, and post-and-lintel construction, the Romans were also innovative. They made considerable use of curvilinear forms: the arch, vault, and dome. The Romans were also the first people in antiquity to use concrete on an enormous scale. By combining concrete and curvilinear forms, they were able to construct massive buildings---public baths and amphitheaters, the most famous of which was the Coliseum in Rome, capable of seating fifty thousand spectators. These large buildings were made possible by Roman engineering skills. These same skills were put to use in constructing roads (the Romans built a network of 50,000 miles of roads throughout their empire), aqueducts (in Rome, almost a dozen aqueducts kept a population of one million supplied with water), and bridges.


Values and Attitudes


The Romans were by nature a conservative people. They were very concerned about maintaining the mos maiorum, the customs or traditions of their ancestors. They emphasized parental authority and, above all, their obligations to the state. The highest virtue was pietas---the dutiful execution of one’s obligations to one’s fellow citizens, to the gods, and to the state.


By the second century B.C., however, the assembling of an empire had begun to weaken the old values. The Romans began to focus more on affluence, status, and material possessions. Emphasis shifted toward individualism and away from collective well-being, the old public spirit that had served Rome so well. Observers worried about the decline of the old values blamed it on different causes. Some felt that after the destruction of Carthage, the Romans no longer had any strong enemies to challenge them. Others believed that the Romans had simply been overwhelmed by the affluence afforded by the new empire. And some blamed everything on the Greeks for importing ideas and practices baneful to the Romans. Of course, there were also many Romans who, though desirous of maintaining traditional values, were also well aware that the acquisition of an empire had created a new world with new demands and values.


The Decline and Fall of the Roman Republic (133--31 B.C.)


Q Focus Question: What were the main problems Rome faced during the last century of the Republic, and how were they ultimately resolved?


By the mid-second century B.C., Roman domination of the Mediterranean Sea was well established. Yet the process of building an empire had weakened and threatened the internal stability of Rome. This internal instability characterizes the period of Roman history from 133 until 31 B.C., when the armies of Octavian defeated Mark Antony and stood supreme over the Roman world. By that time, the constitution of the Roman Republic was in shambles.


Social, Economic, and Political Problems


By the second century B.C., the senate had become the effective governing body of the Roman state. It consisted of three hundred men, drawn primarily from the landed aristocracy; they remained senators for life and held the chief magistracies of the Republic. During the wars of the third and second centuries, the senate came to exercise enormous power. It directed the wars and took control of both foreign and domestic policy, including financial affairs.


Moreover, the magistracies and senate were increasingly controlled by a relatively select circle of wealthy and powerful families, both patrician and plebeian, called the nobiles (‘‘nobles’’). In the hundred years from 233 to 133 B.C., 80 percent of the consuls came from twenty-six families; moreover, 50 percent came from only ten families. Hence the nobiles constituted a governing oligarchy that managed, through its landed wealth, system of patronage, and intimidation, to maintain its hold over the magistracies and senate and thus guide the destiny of Rome while running the state in its own interests.


By the end of the second century B.C., two types of aristocratic leaders, called the optimates (‘‘the best men’’) and the populares (‘‘favoring the people’’), became prominent. Optimates and populares were terms of political rhetoric that were used by individuals within the aristocracy against fellow aristocratic rivals to distinguish one set of tactics from another. The optimates controlled the senate and wished to maintain their oligarchical privileges, while the populares were usually other ambitious aristocrats who used the people’s assemblies as instruments to break the domination of the optimates. The conflicts between these two types of aristocratic leaders and their supporters engulfed the first century B.C. in political turmoil.


Of course, the aristocrats formed only a tiny minority of the Roman people. The backbone of the Roman state and army had traditionally been the small farmers. But economic changes that began in the period of the Punic Wars increasingly undermined the position of that group. Their lands had been severely damaged during the Second Punic War when Hannibal invaded Italy. Moreover, in order to win the wars, Rome had to increase the term of military service from two to six years. When they returned home, many farmers found their farms so deteriorated that they chose to sell out instead of remaining on the land. By this time, capitalistic agriculture was also increasing rapidly. Landed aristocrats had been able to develop large estates (the latifundia) by taking over state-owned land and by buying out small peasant owners. These large estates relied on slave and tenant labor and frequently concentrated on cash crops, such as grapes for wine, olives, and sheep for wool, which small farmers could not afford to do. Thus the rise of the latifundia contributed to the decline in the number of small citizen farmers. Because the latter group traditionally provided the foundation of the Roman army, the number of men available for military service declined. Moreover, many of these small farmers drifted to the cities, especially Rome, forming a large class of day laborers who possessed no property. This new urban proletariat was a highly unstable mass with the potential for making trouble in depressed times.


The Reforms of the Gracchi


In 133 B.C., Tiberius Gracchus, himself a member of the aristocracy and a new tribune, came to believe that the underlying cause of Rome’s problems was the decline of the small farmer. Consequently, Tiberius bypassed the senate, where he knew his rivals would oppose his proposal, and had the council of the plebs pass a land reform bill that authorized the government to reclaim public land held by large landowners and to distribute it to landless Romans. Many senators, themselves large landowners whose estates included large tracts of public land, were furious, and a group of them took the law into their own hands and assassinated Tiberius.


The efforts of Tiberius Gracchus were continued by his brother Gaius, elected tribune for 123 and 122 B.C. Gaius, too, pushed for the distribution of land to displaced farmers. But he broadened his reform program with measures that would benefit the equestrian order, a rising group of wealthy people who wanted a share in the political power held by the ruling aristocracy. Many senators, hostile to Gaius’ reforms and fearful of his growing popularity, instigated mob action that resulted in the death of the reformer and many of his friends in 121 B.C. The attempts of the Gracchus brothers to bring reforms had opened the door to more instability and further violence.


A New Role for the Roman Army: Marius and Sulla


In the closing years of the second century B.C., a series of military disasters gave rise to a fresh outburst of popular anger against the old leaders of the senate. Military defeats in northern Africa under a senate-appointed general encouraged Marius---a ‘‘new man’’ from the equestrian order--- to run for the consulship on a ‘‘win the war’’ campaign slogan. Marius won and became a consul for 107 B.C. Marius took command of the army in Africa and brought the war to a successful conclusion. He was then called on to defeat the Celts, who threatened an invasion of Italy. Marius was made consul for five years, from 104 to 100 B.C.; raised a new army; and decisively defeated the Celts, leaving him in a position of personal ascendancy in Rome.


In raising a new army, Marius initiated military reforms that proved to have drastic consequences. The Roman army had traditionally been a conscript army of small landholders. Marius recruited volunteers from both the urban and rural proletariat who possessed no property. These volunteers swore an oath of loyalty to the general, not the senate, and thus inaugurated a professional-type army that might no longer be subject to the state. Moreover, to recruit these men, a general would promise them land, so the generals had to play politics to get legislation passed that would provide land for their veterans. Marius left a powerful legacy. He had created a new system of military recruitment that placed much power in the hands of the individual generals.


Lucius Cornelius Sulla was the next general to take advantage of the new military system. The senate had placed him in charge of a war in Asia Minor, but when the council of the plebs tried to transfer command of this war to Marius, a civil war ensued. Sulla won and seized Rome itself in 82 B.C. He forced the senate to grant him the title of dictator to ‘‘reconstitute the Republic.’’ After conducting a reign of terror to wipe out all opposition, Sulla revised the constitution to restore power to the senate and eliminated most of the powers of the popular assemblies and the tribunes of the plebs. In 79 B.C., believing that he had created a firm foundation for the traditional Republic governed by a powerful senate, he retired. But his real legacy was quite different from what he had intended. His example of using an army to seize power would prove most attractive to ambitious men.


The Collapse of the Republic


For the next fifty years, Roman history would be characterized by two important features: the jostling for power by a number of strong individuals and the civil wars generated by their conflicts. Three men came to hold enormous military and political power---Crassus, Pompey, and Julius Caesar. Crassus, who was known as the richest man in Rome, had successfully put down the major slave rebellion led by Spartacus. Pompey had returned from a successful military command in Spain in 71 B.C. and had been hailed as a military hero. Julius Caesar had been a spokesman for the populares from the beginning of his political career and had a military command in Spain. In 60 B.C., Caesar joined with Crassus and Pompey to form a coalition that historians call the First Triumvirate.


Though others had made political deals before, the combined wealth and power of these three men was enormous, enabling them to dominate the political scene and achieve their basic aims: Pompey received lands for his veterans and a command in Spain, Crassus was given a command in Syria, and Caesar was granted a special military command in Gaul (modern France). When Crassus was killed in battle in 53 B.C., his death left two powerful men with armies in direct competition. Caesar had used his time in Gaul wisely. He had conquered all of Gaul and gained fame, wealth, and military experience as well as an army of seasoned veterans who were loyal to him. When leading senators fastened on Pompey as the less harmful to their cause and voted for Caesar to lay down his command and return as a private citizen to Rome, Caesar refused. He chose to keep his army and moved into Italy by illegally crossing the Rubicon, the river that formed the southern boundary of his province. (‘‘Crossing the Rubicon’’ is a phrase used to this day to mean taking a decisive action and being unable to turn back.) According to his ancient biographer Suetonius, Caesar said to his troops, ‘‘Even now we could turn back; but once we cross that tiny bridge, then everything will depend on armed force.’’4 Caesar marched on Rome, starting a civil war between his forces and those of Pompey and his allies. The defeat of Pompey’s forces left Caesar in complete control of the Roman government.


Caesar had officially been made dictator in 47 B.C., and three years later, he was made dictator for life. He continued to hold elections for offices but saw to it that his supporters chose the people he recommended. Upon becoming Rome’s ruler, he quickly instituted a number of ambitious reforms. He increased the senate to nine hundred members by filling it with many of his supporters and granted citizenship to a number of people in the provinces who had helped him. By establishing colonies of Roman citizens in North Africa, Gaul, and Spain, he initiated a process of Romanization in those areas. He also reorganized the administrative structures of cities in Italy in an attempt to create a sense of order in their government. Caesar was a generous victor and pardoned many of the republican leaders who had opposed him, allowing them to return to Rome. He also reformed the calendar by introducing the Egyptian solar year of 365 days (with changes implemented in A.D. 1582, it became the basis of our current calendar). He planned much more in the way of building projects and military adventures in the east, but in 44 B.C., a group of leading senators who resented his domination assassinated him in the belief that they had struck a blow for republican liberty (see the box on p. 103). In truth, they had set the stage for another civil war that delivered the death blow to the Republic.


Within a few years after Caesar’s death, two men had divided the Roman world between them---Octavian, Caesar’s heir and grandnephew, taking the west, and Antony, Caesar’s ally and assistant, the east. But the empire of the Romans, large as it was, was still too small for two masters, and Octavian and Antony eventually came into conflict. Antony allied himself with the Egyptian queen Cleopatra VII, with whom, like Caesar before him, he fell in love. Octavian began a propaganda campaign, accusing Antony of catering to Cleopatra and giving away Roman territory to this ‘‘whore of the east.’’ Finally, at the Battle of Actium in Greece in 31 B.C., Octavian’s forces smashed the army and navy of Antony and Cleopatra. Both fled to Egypt, where, according to the account of the Roman historian Florus, they committed suicide a year later:


Antony was the first to commit suicide, by the sword. Cleopatra threw herself at Octavian’s feet, and tried her best to attract his gaze: in vain, for his self-control was impervious to her beauty. It was not her life she was after, for that had already been granted, but a portion of her kingdom. When she realized this was hopeless and that she had been earmarked to feature in Octavian’s triumph in Rome, she took advantage of her guard’s carelessness to get herself into the mausoleum, as the royal tomb is called. Once there, she put on the royal robes which she was accustomed to wear, and lay down in a richly perfumed coffin beside her Antony. Then she applied poisonous snakes to her veins and slipped into death as though into a sleep.5


Octavian, at the age of thirty-two, stood supreme over the Roman world (see Map 5.3). The civil wars had ended. And so had the Republic.



CONCLUSION



In the eighth and seventh centuries B.C., the pastoral community of Rome emerged as a city. Between 509 and 264 B.C., the expansion of this city led to the union of almost all of Italy under Rome’s control. Even more dramatically, between 264 and 133 B.C., Rome expanded to the west and east and became master of the Mediterranean Sea.


After 133 B.C., however, Rome’s republican institutions proved inadequate for the task of ruling an empire. In the breakdown that ensued, ambitious individuals saw opportunities for power unparalleled in Roman history and succumbed to the temptations. After a series of bloody civil wars, peace was finally achieved when Octavian defeated Antony and Cleopatra. Octavian’s real task was at hand: to create a new system of government that seemed to preserve the Republic while establishing the basis for a new order that would rule the empire in an orderly fashion. Octavian proved equal to the task of establishing a Roman imperial state.
