#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 49 The end of a dream
#+begin_verse
How did the dream end?

*Tired of sleeping* on the floor, a young man in Teheran *saved up for years to buy* a real bed.
*For the first time in his life*, he became the proud owner of a bed
	which had springs and a mattress.
Because the weather was very hot, he carried the bed on to the roof of his house.
He slept very well for the first two nights, but on the third night, a storm blew up.
*A gust of wind swept* the bed off the roof and sent it crashing *into the courtyard* below.
The young man did not wake up until the bed had struck the ground.
Although the bed *was smashed to pieces*, the man was miraculously unhurt.
When he woke up, he was still on the mattress.
*Glancing at* the bits of wood and metal that lay around him,
	the man sadly picked up the mattress and carried it into his house.
After he had put it on the floor, he promptly *went to sleep* again.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
