#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 59 In or out?
#+begin_verse
Why did Rex run away?

Our dog, Rex, used to sit outside our front gate and bark.
Every time he wanted to come into the garden
	he would bark until someone opened the gate.
As the neighbours *complained of* the noise,
	my husband *spent weeks training him to press* his paw on the latch to let himself in.
Rex soon became an expert at opening the gate.
However, when I was going out shopping last week,
	I noticed him in the garden near the gate.
This time he was barking so that someone would let him out!
Since then, he has developed another bad habit.
As soon as he opens the gate from the outside,
	he comes into the garden and waits until the gate shuts.
Then he sits and barks until someone lets him out.
After this he immediately lets himself in and begins barking again.
Yesterday my husband removed the gate
	and Rex got so annoyed we have not seen him since.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
