#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 60 The future
#+begin_verse
Does what Madam Bellinsky said come true?

At a village fair, I decided to visit a fortune-teller called Madam Bellinsky.
I went into her tent and she told me to sit down.
After I had given her some money, she looked into a crystal ball and said:
'*A relation of yours* is coming to see you.
She will be arrriving this evening and intends to stay for a few days.
The moment you leave this tent, you will get a big surprise.
A woman you know well will rush towards you.
She will speak to you and then she will lead you away from this place.
That is all.'

As soon as I went outside, I forgot all about Madam Bellinsky because my wife hurried towards me.
'Where have you been hiding?' she asked impatiently.
'Your sister will be here in less than an hour and we must be at the station to meet her.
We are late already.'
As she walked away, I followed her out of the fair.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
