#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 63 She was not amused
#+begin_verse
Why did Jenny want to leave the wedding reception?

Jeremy Hampden has *a large circle of friends* and is very popular at parties.
Everybody *admires him for* his great *sense of humour*
	- everybody, that is, except his six-year-old daughter, Jenny.
Recently, one of Jeremy's *closest friends* asked him to *make a speech* *at a wedding reception*.
This is *the sort of* thing that Jeremy loves.
He prepared the speech carefully
	and went to the wedding with Jenny.
He had included *a large number of* funny stories in the speech and,
	of course, it was great success.
As soon as he had finished,
	Jenny told him she wanted to go home.
Jeremy was a little disappointed by this
	but he did as his daughter asked.
*On the way home*, he asked Jenny if she had enjoyed the speech.
To his surprise, she said she hadn't.
Jeremy asked her why this was so
	and	she told him that she did not like to see so many people laughing at him.
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
