#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 65 Jumbo versus the police
#+begin_verse
Why did the police have to push Jumbo off the main street?

Last Christmas, the circus owner, Jimmy Gates,
	decided to take some presents to a children's hospital.
*Dressed up as* Father Christmas and accompanied by a 'guard of honour' of six pretty girls,
	he *set off* down the main street of the city riding a baby elephant called Jumbo.
He should have known that the police would never allow this sort of thing.
A policeman approached Jimmy and told him ought to have gone along a side street
	as Jumbo was *holding up the traffic*.
Though Jimmy *agreed to go* at once, Jumbo refused to move.
Fifteen police had to push very hard to get him off the main street.
The police had a difficult time, but they were most amused.
'Jumbo must weigh a few tons,' said a policeman afterwards,
	'so *it was fortunate that* we didn't have to carry him.
Of course, we should arrest him,
	but as he has a good record,
	we shall *let him off* this time.'
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
