#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 66 Sweet as honey!
#+begin_verse
What was 'sweet as honey' and why?

In 1963 a Lancaster bomber crashed on Wallis Island,
	a remote place in the South Pacific,
	a long way west of Samoa.
The plane wasn't too badly damaged,
	but *over the years*,	the crash was forgotten and the wreck remained undisturbed.
Then in 1989, twenty-six years after the crash,
	the plane was accidentally rediscovered in an aerial survey of the island.
By this time, a Lancaster bomber *in reasonable condition* was rare and *worth rescuing*.
The French authorities had the plane packaged
	and moved in parts back to France.
Now a group of enthusiast are going to have the plane restored.
It has four Rolls-Royce Merlin engines,
	but the group will need to have only three of them rebuilt.
Imagine their surprise and delight
	when they broke open the packing cases
	and found that the fourth engine was sweet as honey
		- still in perfect condition.
*A colony of bees* had *turned the engine into a hive*
	and it was totally presevered in beeswax!
#+end_verse

** 单词造句
** 反复听电影片段
** Pattern Drill 写+读
** 给自己讲解
** 红皮书
** 习惯用法造句
** 跟读至背诵
** Ask me if 写+读
** 摘要写作
** tell the story 口语
** Topics for discussion
