#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil

* Lesson 69 But not murder!
#+begin_verse
Do you think that the writer passed his driving test? Why?

I was being tested for a driving licence for the third time.
I had been asked to drive in heavy traffic and had done so successfully.
After having *been instructed to drive* out of town, I began to acquire confidence.
Sure that I had passed, I was almost beginning to enjoy my test.
The examiner must have *been pleased with* my performance,
	for he smiled and said,‘Just one more thing, Mr. Eames.
*Let us suppose that* a child suddenly crosses the road in front of you.
As soon as I *tap on the window*, you must stop within five feet.’
I *continued driving* and after some time, the examiner tapped loudly.
Though the sound could be heard clearly, it took me a long time to react.
I suddenly pressed the brake pedal hard and we were both thrown forward.
The examiner looked at me sadly.
‘Mr. Eames,’ he said, in a mournful voice, ‘you have just killed that child!’
#+end_verse

** DONE 单词造句
CLOSED: [2023-08-28 Mon 16:48]
murder /ˈmɜːdə/ v.n.
1. It's in twenty minutes' time that he has murdered his wife.
2. He has been said to murder his wife.
3. He refused to admit for murder his wife.
4. He couldn't have murder his wife in this way.
5. Shouting at his wife, he murdered her yesterday.
instruct /ɪnˈstrʌkt/ v. be instructed to do sth.
1. He was instructed to take part in the competition.
2. Having been instructed to drive out of town, he suddenly press the brake pedal quickly.
3. The poor boy was instructed to give a performance in front of his family.
4. I am always being instructed to work hard to earn money.
5. After having been instructed to drink, I was nervous about my behavior.
acquire /əˈkwaɪr/ v.
1. You should have acquired a good knowledge of volcanoes.
2. If you had acquired a good knowledge of volcanoes, you would have enjoyed it.
3. Sorry to interrupt, but we should acquire more knowledge of the real world.
4. After finishing fish, I acquired a lot of confidence.
5. If you pay more attention to your teacher in the class,
		you will acquire a better knowledge of English.
confidence /ˈkɑːn-/ n. confident adj.
1. I am confident that she must have murdered her husband.
2. If you were more confident, you would be more successful.
3. After have received a warm welcome, he began to acquire confidence.
4. She was confident that she could get along with others in the school.
5. If you had been confident, you wouldn't have parked your car in the wrong place.
examiner /ɪɡˈzæmənə/ n.
1. The examiner began to pay attention to the girl.
2. The examiner hurried to the museum.
3. The examiner is determined to hand the paper to the student.
4. The examiner was give a fright by a student who was cheating.
5. The examiner excepted the lost paper to be found in twenty minutes'.
suppose v. Let's suppose that...
1. Let's suppose that someone is tapping on the window.
2. Let's suppose that some is knocking at your door at midnight./
3. Let's suppose that you haven't finished your homework.
4. Let's suppose that you don't mind my coming with you.
5. Let's suppose that Nigel have been following you around all morning.
tap v. tap on the window
1. She does enjoy tapping on the window which watching TV.
2. Sorry to interrupt, but I am driven mad by tapping on the table all the time.
3. The boy was instructed to tap on the window.
4. I was wondering why you are tapping on the window all morning.
5. If you tap on the window, don't follow me around this morning.
react v.
1. I really don't know how to react to you when you get very angry.
2. He always reacts right when his wife gets angry.
3. It is no use pretending that you react quickly in the class.
4. No matter how he says, his wife doesn't react.
5. If you had acquired a good knowledge of English, you would have reacted right.
brake n. pedal n.
1. Don't press the brake pedal suddenly.
2. The girl fears that she wouldn't press the brake pedal immediately.
3. A short time before, the brake pedal has been stolen.
4. The student has a reputation for pressing the brake pedal suddenly.
5. The car broke down because of the bad brake pedal.
mournful adj.
1. I couldn't stand her mournful look on her face.
2. I'm fairly certain that she was mournful.
3. You look so mournful. What happen to you?
4. Her mournful look is a source of information.
5. Her mournful look disappear because her dream comes true.

** DONE 反复听电影片段
CLOSED: [2023-08-28 Mon 20:06]
** DONE Pattern Drill 写+读
CLOSED: [2023-08-28 Mon 20:15]
+ 1T: confess-arrested
	S1: Did the man *confess*?
	S2: Yes, but only after being *arrested*
	- leave the restaurant -- thrown out
		Did the man leave the restaurant?
		Yes, but only after being thrown out.
	- give up the flight -- knocked out
		Did the man give up the flight?
		Yes, but only after being knocked out.
	- become well known -- murdered
		Did the man become well known?
		Yes, but only after being murdered.
	- call the police/guard -- robbed
		Did the man call the police?
		Yes, but only after being robbed.

+ 2T: become famous -- his murder.
	S1: He became famous after his murder.
	S2: Oh no! He became famous before being murdered.
	- confessed/killed the guard -- his arrest
		He confessed after his arrest.
		Oh no! He confessed before being arrested.
	- called the police/fell down -- the attack
		He called the police after the attack.
		Oh on! He called the police before being attacked.
	- phoned Mary/saw Tom -- his interview
		He phoned Mary after his interview.
		Oh no! He phoned Mary before being interviewed.
	- fell ill/became rich -- his election
		He felt ill after his election.
		Oh no! He felt ill before being elected.

+ 3T: send the fax to Hong Kong
	S1: When do you want the fax sent to Hong Kong?
	S2: It should be sent some time today.
	- return -- the books to the library
		When do you want the books returned to the library?
		They should be returned some time today.
	- send -- the goods to the shop
		When do you want the goods sent to the shop?
		They should be sent some time today.
	- collect -- the luggage from the hotel
		When do you want the luggage collected from the hotel.
		It should be collected some time today. 
	- announce -- the result to the Press
		When do you want the result announced to the Press?
		It should be announced some time today.

+ 4T: ask -- your report
	S1: I'd like to ask you about your report.
	S2: Not again! I was being asked about my report all day yesterday!
	- consult -- our sales figures
		I'd like to consult you about your sales figures.
		Not again! I was being consulting about our sales figures all day yesterday!
	- question -- your latest film
		I'd like to question you about your latest film.
		Not again! I was being questioning about my latest film all day yesterday!
	- advise -- the need for economy
		I'd like to advise you about the need for economy.
		Not again! I was being advised about the need for economy all day yesterday!
	- inform -- the firm's future plans
		I'd like to inform you about the firm's future plans.
		Not again! I was being informed about the firm's future plans all day yesterday!

** DONE 给自己讲解
CLOSED: [2023-08-28 Mon 17:01]
** 红皮书
** DONE 习惯用法造句
CLOSED: [2023-08-28 Mon 17:07]
continue doing/ to do
	1. The examiner continue instructing him to drive out of the town.
	2. After having pressed the brake pedal, the examiner continued to tap on the window.
	3. He noticed that he continues to make same mistakes.
	4. If you continued study a good knowledge of English, you would be fluent.
	5. The policeman continues to threaten to arrest the thief.
be pleased with
	1. Why aren't you pleased with his hard work?
	2. Why aren't you always pleased with the cat's performance?
	3. Aren't you pleased with the cat's performance?
	4. I'm not pleased with this.
	5. I'm not pleased with my homework.
** DONE 跟读至背诵
CLOSED: [2023-08-28 Mon 17:08]
** DONE Ask me if 写+读
CLOSED: [2023-08-28 Mon 20:33]
1. I was being tested for my driving license.(What...for)(Why)
	 What was you being tested for?
	 Why was you being tested for your driving license?
2. It was my third test.(Which)
	 Which test was it?
3. I'd been asked to drive in heavy traffic(Where)
	 Where had you been ask to drive?
4. I'd done so successfully.(How)
	 How had you done so?
5. I began to acquire confidence.(What)
	 What did you begin to acquire?
6. I'd been instructed to drive out of town.(Which way)(Who)
	 Which way had you been instructed to drive?
	 Who had been instructed to drive out of town?
7. I was almost beginning to enjoy my test(What)(Why)
	 What was you almost beginning to enjoy?
	 Why was you almost beginning to enjoy your test?
8. The examiner must have been pleased with my performance.(What...with)(Why)
	 What must the examiner have been pleased with?
	 Why must the examiner have been pleased with your performance?
9. He smiled.(What...do)(Why)
	 What did he do?
	 Why did he smile?
** DONE 摘要写作
CLOSED: [2023-08-28 Mon 20:43]
Mr Eames had driven successfully in heavy traffic during his third driving test
	when the examiner instructed him to drive out of town.
The examiner told him to suppose that a child would suddenly cross the road in front of him.
Mr. Eames would have to stop within five feets
	when the examiner tapped on the window.
Though the examiner tapped loudly,
	Mr Eames didn't react quickly enough and was told that he had just killed that child. 


** DONE tell the story 口语
CLOSED: [2023-08-28 Mon 20:43]
** Topics for discussion
Have you ever been over-confident andmade a mistake? Tell us about it.

What particular things would you lookout for if you were giving someone adriving test?

Apart from bad driving, what else cancause road accidents? How can we try toprevent these?
