* 如何学习的书评
如何快速高效的学习,是我的问题,我带着这一问题阅读了大量的书籍.而这本中系统的方法,给我打开新世界的大门.

我的问题说准点, 如何最快速,最有效率的进行自学,并且在考试中取得高分

这本书针对美国学校,提出的更多是如何学习,对于如何拿分不是特别倚重. 是一种系统化的进攻性学习.

我来改造一下,使它适合自学的特殊性.

首先,学习是什么,我的理解是: 理解和记忆. 我们的努力都是为了达到两者,或者同时达到两者.
那学习方法是什么,就是最快速~高效的理解和以及.光有学习方法仍然不够,要完成我的目标"最快速,最有效率的自学,并且考试拿高分".
应该靠3个方面: 1.最快速~高效的学习方法 2.最明确~细致的考试策略 3.最有效的精力和时间管理

接下来是对12问题的解读
1. 我学这个的目的是什么?
	 书中,作者给它的定义是预热.
	 我认为这是一个非常重要的问题.在心理学叫启动效应,在学习过程中,要完成这个目的,注意这个目的.

2. 对这个话题我已经知道什么?
	 开始联系过去的知识.
	 用高速公路理论说,通往一个地方的路越多,越容易记忆,理解.

3. 这里大框架是什么?
	 通过略读,大致了解整篇文章的内容,有一个概念的框架

	 这三步是起步

4. 作者接下要说什么?
	 我认为在看一些结构散漫的材料或许有用,但教科书没那么多时间猜的.
	 作者的观点可能是, 看困了,因为你大脑觉得很无聊.
	 这一步应该是有余力的时候再去做,其他时候要略去,专注其他的问题.

5. 专家会提什么问题?
6. 针对信息,我能提什么个人的问题?
	 这两个问题,用一个词描述,叫对话式的阅读.
	 要理解,首先要通过阅读.但是如何达到更好的理解呢?作者给出了答案,对话式的阅读.
	 通过提出问题,来和作者对话.不是在记录答案,而是提出问题,让作者来解答.
	 这是一种主动的阅读,而不是被动的被填鸭.
	 
7. 这里重要信息是什么
8. 针对这些信息,我要如何进行改述和总结
9. 我应该如何组织这些信息
10. 我如何用图表来说明这些信息
		这个四个问题,归类到增进理解和记忆的共同的区间
		这里再讲几个提高记忆的方法
		1. 排序(不是单纯标数字)
		2. 图表化,联想~比喻~编故事等小技巧
		3. 艺造
		4. 重复(主动地重复)
		这4个问题,可以分成
			 1. 收集资料(路线图)
			 2. 对这些资料进行一次小费曼
			 3. 分类
			 4. 图表化信息
		视觉是人类最敏感的感觉,在线性笔记的基础上进行延展,分别是对重要问题进行费曼方法,另外又重新分类,把问题肢解分类,
		一方面为图表化提供素材,一方面更加深入的理解.最后依然要定期的重复,这里说的用测试来代替重复,本质上还是重复.这里
		我们似乎反思之前笔记是否可以做的更好,有更加优质的联想或者其他助记方法的加入,并且这里的测试,也应该是自己测试自己,
		对自己进行提问,而不是单纯的做题.

11. 对我而言,这些信息的记忆点是什么
12. 这些信息如何才能与我已知的知识结合起来
		这两部分归为记忆. 首先各个问题之间的顺序不必那么死板,有些增进记忆的方法,比如联想和比喻,同时还可以增进理解,
		那么在之前可以运用这种小技巧.在之后,我们可以再审视一些难点,加上一些小技巧.
		而其后所说的把所有内容总结到一张纸上,也是非常好的.是不是可以不断地把知识浓缩成一个记忆点?是否可以通过一个浓缩点,
		回忆起整本书呢?

按照这些问题,学习的步骤是这样的
	1. 进行启动效应的预热
	2. 对话式阅读
	3. 信息收集分类--重点部分费曼--信息再归类--图表化笔记--重复测试(如果达到一定程度,可以直接图表化)
	4. 添加记忆点--不断1纸压缩

对比传统学习方法
	线性阅读+线性笔记+机械重复,有效率的多
	
这本的作者,12个问题背后隐藏着,基本上人类至今所有行之有效的学习技巧.不过对于我而言,或许还不是终点.

* 预热
让自己进入状态

** 1. 目的是什么?
根据题目望文生义去制造2-3个问题.
带着问题是阅读和听课

** 2. 我已经知道了什么?
1. 不论是生活还是学习,还是其他的,但凡有点关系的都写上. 一个番茄钟写一个
2. 这个问题和第12个问题一样,要伴随始终

** 3. 大纲是什么?
有目录用目录,没目录自己选章节,总之要弄出个大纲来

* 对话式阅读
提问,然后去文章里找答案

** 4. 专家问题?
1. 导读问题
	 - 内涵
	 - 外延
	 - 类型
	 - 联系
	 - 比较
2. 专业问题 

** 5. 我的问题? !!!
1. 如果我使用A会怎么样?
2. 如果我改变A,B会怎么变化?
3. 如何把自己代入进去?
4. 让我联想到什么? !!!

* 信息处理

** 6. 哪些东西要记得,怎么做分类?
** 7. 是否需要费曼一下?
** 8. 是否需要肢解再分类信息?
** 9. 是否需要用笔记流方法?

* 总结
** 10. 怎么添加记忆点?
1. 图片~模式~节奏~故事
2. 联系
3. 情绪
4. 感官
5. 环境
6. 多用
7. 常温习
** 11. 如何结合以前的知识一纸压缩?

* 啰嗦时
** - 下一步可能讲什么?

