* 怎样提升自己的独立思考能力和逻辑思维能力
在实际生活中,每当我面对自己和周围的人或事,发现自己看问题常常不是过于片面或者表面,而且想问题也没有条理.
自己的判断会随着他人见解而改变.
具体表现: 在阅读时看到作者的观点,自己觉得很有道理,但是当看到评论区其他人的观点,又觉得这个人反驳的有道理,自己为什么没想到.

千叶:
确定范围和目标 + 大量吸收信息 + 批判性思考,三者缺一不可

1. 确定范围和目标
	 什么是独立思考能力和逻辑能力?
	 提高到何种程度(目标), 在哪些领域拥有这些能力(范围)
	 假设想获得 对生活时间(周围的人和事)和在阅读中(例:社会科学)拥有全面地分析和客观地评价的能力.这实际是逻辑思维的体现.

	 全面地分析: 观点拥有强的解释力和适用性(狭隘的观点只能解释一方面)
	 客观地评价: 对事物和其他部分的联系(事物的意义不可能脱离其他事物而独立)作出 *自洽的* , *同一的* , *排中* 的解释.

2. 大量吸收信息
	 独立思考能力常常被误以为是单纯的思考技能,事实恰恰相反,独立思考能力离不开对某一领域大量知识的摄入.

	 拥有独立思考能力意味着拥有严密的,自洽的知识体系,知识体系组成要素是一条条经过吸收无数信息交集形成的信念,信念相互切合,且往往是隐形的,公式的而不是文本的. 它们能和新的信息结合而产生新结论.形成新结论的速度和可靠性取决于知识体系的积木--信念经过了多少信息的筛选,总结,提炼.

	 隐形的信念优势在于当你需要解决,思考现实问题时,能够快速将你引向正确的方向,从而大大节省思维的成本.

	 你形成的归类和范畴的心理表征称为概念. 原型是你对所有信息的心理表征所提炼出来的信息的集合.你拥有的原型产生于你对范畴成员的所有体验,每当你遇到一个范畴内的新成员时,你的原型就发生了精细变化,原型是作为你的样本库的平均而出现的,如:至今你遇到的所有的狗都有助于你形成你的原型狗的心理表征, 如果今天再遇到一条狗,那么心中狗的原型又会稍加调整.
	 概念这个理论有什么用?
	 例如,你发现化学中特列原理和物理中的惯性定律有相似之处,再后来学到了生物体的负反馈调节,综合三者共同之处,看看我们的生活,会惊奇地发现它是如此的普遍和跨领域.会发现增反减同,是宇宙间一条广泛的,本质的法则,再经过反复的确认和发现,这一信念不断地内化进知识体系,你会发自内心的感叹世界之神奇,学习之趣味.它是思考时一幅巨大的背景画,它是无数问题的前提和假设,它是纷繁世象背后的永恒真理.于是在接触,加工新信息时,我们有十足的理由从这一角度展开.(能量守恒定律,热力学第一,第二定律同理)

	 这些宏大的信念可以通过日常生活的勤于思考而反复振荡,确认而获得加强,我们发现这些信念与其他领域产生的连接点越多,思考时被唤醒的速度和强度也越高,为解决问题提高快速的,优质的思路,表现出来的便是: 才思敏捷,出口成章,一针见血.

	 如何获得新信息?
	 在同一领域中,尽量广泛地涉猎不同派的优秀的,经过时间沉淀的书籍和观点,并对不同的观点进行分析,对比,综合.摒弃急于求成的功利心和快餐文化的浮躁心,假以时日,拥有独到的见解并非难事.

3. 批判性思考
	 批判性思维远不只是一个工具,更像是一种人格特质.它应用范围之广,剖析问题之严谨,远非工具两字可以概括.
	 引用知乎的话: 批判性思维指的是技能和思想态度,批判性思维既是一种思维技能,也是一种人格或气质;技能体现思维水平,也凸显人文精神.

	 *批判性思维的内涵是什么?*
	 批判性思维翻译是有偏差的,它让人误以为是批判性的,怀疑性的,然而它更多的是一种正确,有序的思考方式,内涵有:

	 提炼结论和论据
	 辨析模糊词的含义
	 反推假设和前提(描述性假设和价值观假设)
	 分析推理环节是否有谬误
	 证据是否有力
	 是否有竞争性原因
	 统计数据是否可靠,可靠的原则是什么
	 是否有竞争性结论

	 批判性思维在生活中会遇到什么困难?
	 我遇到的问题:
	 1. 辨析模糊词过于关注不重要词语的内涵,浪费时间和精力而忽略主要问题
	 2. 反推假设和前提容易把握不好尺度以至于要么陷入虚无(究竟源头),要么陷入复杂中不能自拔.
	 3. 现实中往往推测不出别的竞争性原因或结论
	 4. 逻辑谬误的顽固性远超我想象
	 经过长期的反思,理由如下
	 1. 思考量不足,接受信息量不足,同时对养成批判性思维的难度没有正确的认识!
	 2. 分不清哪个是需要辨析的关键词语说明不清楚这个语境下通常来说哪些词是关键的
	 3. 反推假设和前提不能把握尺度说明对分析的目标需要怎样的前提没有预先的思考
	 4. 现实中往往推测不出其他原因和结论更是说明我被表面现象所蒙蔽,没有对常见的偏见和困惑进行总结,一个领域内产生的偏见和误解往往有共性的,你的误解可能前人早就体会到并作出解读.
	 5. 至于逻辑谬误的顽固,更是说明学以致用本来就是世界上极难的事情,尤其要反观自己的想法,因此更需要有寻根究底的精神.
	 不过遇到的困难也恰恰说明,自己在知行合一而没有将批判性思维束之高阁.只要在进步,养成理性严谨的思维也为时不远了.困难越大,克服之后的提高也就越大.

	 最后,锻炼逻辑思维完全不必拘泥于学科,打造自主的知识体系就是要不怕未知,不怕困难,在广泛的知识和领域中接受检验,才能越发体现其价值.学以致用,知行合一.
