#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 1-1 1.3 Relationships, self and happiness
#+begin_verse
Well, relationships are also important because they do not only meet our needs,
	but they also help us define who we are.
In a way, it's actually quite fair to say
	that like we become who we are as a result of the relationships that we have.
As children we got exposed to like people who took care of us like our parents
	and they might tell us like that we are smart or we are ugly or we are pretty
		or like we are stupid, that we are selfish or like we have wonderful, nice characters.
So all this feedback that we got like from relationships
	will fit into this sense of self that we now carry.
So it is really important to look at like
	how relationships are impacting on who we think we are, what we think we are.

Well, relationships are the key to our happiness, quality of life and our sense of well-being.
There is actually like significant research evidence pointing in the direction
	that like the quality of your relationship
		actually has a direct impact on your overall quality of life.
And, whatever we are thinking of, like in our quest for happiness,
	it has to be negotiated through building relationships with other people.
So, that's why it is so important for us
	to be paying more attention to understanding how relationships work in our lives.
#+end_verse
** expression
character [ˈkerəktər]: n. the particular combination of qualities that makes someone a particular type of person ⇨ characteristic性格
feedback [ˈfidˌbæk]: n. advice, criticism etc about how successful or useful something is反馈
quality [ˈkwɑləti]: n. something that is typical of one thing and makes it different from other things, for example size, colour etc质量
negotiate [nəˈɡoʊʃiˌeɪt]: v. to discuss something in order to reach an agreement, especially in business or politics商议, 谈判
--------------------
meet sb's needs: 满足某人的需要
In a way + ...: 在某种程度上
It's quite fair to say that + ...: 很公平地说
as a result of sth.: 由于某物
get exposed to sth.: 接触于某物;暴露于某物
fit into sth.: 融入到某事物
impact on sth./sb.: 影响到某物/某人
point in the direction of sth.: 指出某物的方向
** sentence
character [ˈkerəktər]: n. the particular combination of qualities that makes someone a particular type of person ⇨ characteristic性格
- The coach assessed that the famous player is blessed with a great character.
- The player blessed with a great character felt guilty for the loss of the tournament.
- More and more audiences began to blame the player on his coward character.
feedback [ˈfidˌbæk]: n. advice, criticism etc about how successful or useful something is反馈
- In the interview, the player was complaining about the lack of feedback in the game.
- The more optimistic feedback you give, the more progresses your children will make.
- If you leave the feedback of the product, we will present you with a tiny gift.
quality [ˈkwɑləti]: n. something that is typical of one thing and makes it different from other things, for example size, colour etc质量
- The low quality of the spicy sauce led to the drop of its sales this year.
- The spicy sauce must have changed its ingredients, for its flavor changes a lot and the quality drops.
- The quality of wedding gave the girl a sense of satisfication.
negotiate [nəˈɡoʊʃiˌeɪt]: v. to discuss something in order to reach an agreement, especially in business or politics商议, 谈判
- Short of negotiation skills, I am reluctant to bargain with butcher in the village fair.
- I am going to enter a course pointing in the direction of negotiation.
- As the workers are going on a strike, all we need to do is to negotiate with them as soon as possible.
--------------------
meet sb's needs: 满足某人的需要
- Meeting his needs, he locked the door of warehouse.
- My precious, I can't figure out how to meet your needs when you are mad at me.
- You have to offer your cat some entertainments to meet her needs.
In a way + ...: 在某种程度上
- In a way I didn't go to university.
- In a way the suspencious bridge fulfilled his dream because of its faint enormousess.
- In a way Ned Stark is still alive, for his children followed in his footsteps and accomplished his dreams.
It's quite fair to say that + ...: 很公平地说
- It's quite fair to say that I shouldn't take responsibility for the mine disater.
- It's quite fair to say that I have tried my best to offer you a good education.
- It's quite fair to say that there are abundant evidence to prove his crime.
as a result of sth.: 由于某物
- As a result of being boring, the girl manupulated her robot to clean up the house.
- As a result of turning against her parents, she left for New York.
- As a result of quarreling bitterly with his tutor, he asked for a fight in the ring.
get exposed to sth.: 接触于某物;暴露于某物
- Geting exposed to the vicious king, the knight decided to break his oath.
- Geting exposed to my vicious king, I became inconfident and lack of high self-esteem.
- Geting exposed to the crazy criminal, the girl who played truant from school was raped in the park.
fit into sth.: 融入到某事物
- It's quite fair to say that your child has fit into the ambiance of the kindergarten.
- Fitting into the company, I succeeded in negotiating about my pay and working condition..
- In a way I have never fit into the company full of drunks and liars.
impact on sth./sb.: 影响到某物/某人
- With the ambiance impacting on us, everyone around the table in the meeting became silent.
- If your kept impacting on your stupid boy, he would have killed all of us in the flame of his ambition.
- With the witch impacting on our lord, he began to execute innocents.
point in the direction of sth.: 指出某物的方向
- The research may point in the direction of how to build a high quality relationship.
- The research aims to point in the direction of how to negotiate with difficult superiors.
- The scientists made a remakable discovery pointing in the direction of the evolution of this kind of bird.
** sentence2
character [ˈkerəktər]: n. the particular combination of qualities that makes someone a particular type of person ⇨ characteristic性格
- The coach assessed that the famous player is blessed with a great character.
- The player blessed with a great character felt guilty for the loss of the tournament.
- More and more audiences began to blame the player for his cowardly character.
feedback [ˈfidˌbæk]: n. advice, criticism etc about how successful or useful something is反馈
- In the interview, the player complained about the lack of feedback in the game.
- The more optimistic feedback you give, the more progress your children will make.
- If you leave feedback on the product, we will present you with a tiny gift.
quality [ˈkwɑləti]: n. something that is typical of one thing and makes it different from other things, for example size, colour etc质量
- The low quality of the spicy sauce led to a drop in its sales this year.
- The spicy sauce must have changed its ingredients, for its flavor changes a lot and the quality drops.
- The quality of the wedding gave the girl a sense of satisfaction.
negotiate [nəˈɡoʊʃiˌeɪt]: v. to discuss something in order to reach an agreement, especially in business or politics商议, 谈判
- Short of negotiation skills, I am reluctant to bargain with butchers at the village fair.
- I am going to enter a course pointing in the direction of negotiation.
- As the workers are going on strike, all we need to do is to negotiate with them as soon as possible.
--------------------
meet sb's needs: 满足某人的需要
- Meeting his needs, he locked the door of the warehouse.
- My precious, I can't figure out how to meet your needs when you are mad at me.
- You have to offer your cat some entertainment to meet her needs.
In a way, + ...: 在某种程度上
- In a way, I didn't go to university.
- In a way, the suspension bridge fulfilled his dream because of its faint enormous.
- In a way, Ned Stark is still alive, for his children followed in his footsteps and accomplished his dreams.
It's quite fair to say that + ...: 很公平地说
- It's quite fair to say that I shouldn't take responsibility for the mine disaster.
- It's quite fair to say that I have tried my best to offer you a good education.
- It's quite fair to say that there is abundant evidence to prove his crime.
as a result of sth.: 由于某物
- As a result of being bored, the girl manipulated her robot to clean up the house.
- As a result of turning against her parents, she left for New York.
- As a result of quarreling bitterly with his tutor, he asked for a fight in the ring.
get exposed to sth.: 接触于某物;暴露于某物
- Getting exposed to the vicious king, the knight decided to break his oath.
- Getting exposed to my vicious king, I became unconfident and lacked high self-esteem.
- Getting exposed to the crazy criminal, the girl who played truant from school was raped in the park.
fit into sth.: 融入到某事物
- It's quite fair to say that your child has fit into the ambiance of the kindergarten.
- Fitting into the company, I succeeded in negotiating my pay and working conditions.
- In a way, I have never fit into a company full of drunks and liars.
impact on sth./sb.: 影响到某物/某人
- With the ambiance impacting on us, everyone around the table in the meeting became silent.
- If you kept impacting on your stupid boy, he would have killed all of us in the flame of his ambition.
- With the witch impacting on our lord, he began to execute innocents.
point in the direction of sth.: 指出某物的方向
- The research may point in the direction of how to build a high-quality relationship.
- The research aims to point in the direction of how to negotiate with difficult superiors.
- The scientists made a remarkable discovery pointing in the direction of the evolution of this kind of bird.
** summary
Relationships not only meet our needs,
	but also help us identify ourselves in a way
		that we become someone as a result of relationships we have.
Children, for example,
	got exposed to people who told them that they are ugly, or smart, and so on.
This feedback from relationships will fit into their sense of self.
Relationships are also the key to our happiness.
There is research evidence
	proving that our equality of relationships has a direct impact on our overall quality of life.
Happiness has to be negotiated through building relationships with other people.
Therefore,
	it's crucial for us to pay more attention to understanding how relationships work in our lives.
** summary2
Relationships not only meet our needs
	but also help us identify ourselves in a way
		that we become someone as a result of our relationships.
Children, for example,
	got exposed to people who told them that they were ugly, or smart, and so on.
This feedback from relationships will fit into their sense of self.
Relationships are also the key to our happiness.
There is research evidence
	proving that our equality of relationships has a direct impact on our overall quality of life.
Happiness has to be negotiated through building relationships with other people.
Therefore, we must pay more attention to understanding how relationships work in our lives.
