#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-1 3.1 The 4 Content Areas
#+begin_verse
We will now be talking about receptive skills.
And when reading the book,
	I noticed that both reception and expression sort of targeted four main content areas
		and they were both the same.
So, they were facts, attitudes, emotions, and needs for both.
And I'm sort of wondering why this similarity?

Okay, so first of all, we probably will have to explain
	why these four content areas of all the possible content areas are chosen, right.
I would say that this is probably based on our experience, helping people manage emotional issues.
Very often, when people were trying to communicate, they want to establish facts.
But then we understand that facts were never totally objective.
If you go to any household and ask who has done a big share of housework,
	you will not have the same answer from everyone.
And if you ask a couple about some simple facts like are we spending enough time together
	and you get very different answers.
	
Because facts are always colored and conditioned by our emotional needs and our attitudes.
And sometimes we will be sort of constructing reality according to our needs and emotional state.
So the reason why we put all this together is,
	we start off with something
		that looks like it is straightforward, objective, neutral and help people appreciate that.
That is not always the case.
And from that onwards, we'll leap onto this idea
	that whatever we are communicating,
		we have to be paying attention to the kind of attitudes that people have taken,
			the values that are weaved into the message,
And very often, emotions are important.
And back to the SSLD core concept, SSLD is always focused on needs,
	because why do we even want to be communicating with each other?
Because there's something that we need from that interaction,
	and there's something that we want to attain or accomplish in that conversation.
So this is why we have got these four content areas chosen.
As mentioned,
	the four key content areas that we should pay attention to when we are listening to others are:
		Facts, which can be subjective, depending on your attitudes and emotions and of course,
			the core concept of the N3C analysis, your needs.
There's often something that we want to accomplish or attain when we engage in conversations,
	and that's because we have needs.
#+end_verse
** expression
receptive [rɪˈseptɪv]: adj. willing to consider new ideas or listen to someone else’s opinions善于接受的, 能接纳的
target [ˈtɑrɡət]: v. to make something have an effect on a particular limited group or area针对
objective [əbˈdʒektɪv]: adj. based on facts, or making a decision that is based on facts rather than on your feelings or beliefs OPP subjective客观的
household [ˈhaʊsˌhoʊld]: n. all the people who live together in one house SYN house一家人, 家庭, 家族, 王室
colored [ˈkʌlə(r)d]: adj. brightly/highly/richly etc coloured having a bright colour such as red, blue, or yellow etc, or a deep shade of a particular colour, but not black, white, or plain有色的
conditioned [kənˈdɪʃ(ə)n]: adj. 有条件的
straightforward [ˌstreɪtˈfɔrwərd]: adj. simple and easy to understand OPP complicated简单的, 易懂的, 直接了当的
neutral [ˈnutrəl]: adj. IN AN ARGUMENT ETC not supporting any of the people or groups involved in an argument or disagreement ⇨ partisan中立的
interaction [ˌɪntərˈækʃən]: n. a process by which two or more things affect each other交流
attain [əˈteɪn]: v. to succeed in achieving something after trying for a long time得到,达到
subjective [səbˈdʒektɪv] subjectively: adj.adv. a statement, report, attitude etc that is subjective is influenced by personal opinion and can therefore be unfair OPP objective主观的
analysis [əˈnæləsɪs]: n. a careful examination of something in order to understand it better分析
--------------------
from ... onwards: from ... onwards beginning at a particular time or age and continuing after that从那继续
Very often, + ...: 通常, +...
a big share of sth.: 某物的很大一部分
start off with sth.: 以某物开始
leap onto the idea that + ...: 跳跃到这个想法...
take ... attitude: 采取什么的态度
A be weaved into B: A被织入B
be focused on sth.: 专注于某事
** sentence
receptive [rɪˈseptɪv]: adj. willing to consider new ideas or listen to someone else’s opinions善于接受的, 能接纳的
- If you don't have basic receptive skills and jump in, you will probably get severely hurt.
- These receptive skills teacher taught needs practicing a great deal.
- The queen was so receptive that she decided to be allied with the king in the north.
target [ˈtɑrɡət]: v. to make something have an effect on a particular limited group or area针对
- Obviously, these TV series were designed to target housewives. 
- Our cookies are supposed to target those people who are reluctant to make breakfast.
- The toothpaste which is designed to target housewives is adored by poor and rich alike.
objective [əbˈdʒektɪv]: adj. based on facts, or making a decision that is based on facts rather than on your feelings or beliefs OPP subjective客观的
- If you run into serious trouble, you'd better calm your nerve and be objective.
- When the queen is in the face of the death of her son, she will never be objective and crucify us all.
- On an objective perspective, you don't have to stay up overnight in the hay.
household [ˈhaʊsˌhoʊld]: n. all the people who live together in one house SYN house一家人, 家庭, 家族, 王室
- No one could account for the fact why the mad king killed the household. 
- The household that fought bravely in the battle should have been rewarded with a fief in the east.
- The household that put forward a plan of killed the king in the north in the wedding has been poisoned by one of his widow.
colored [ˈkʌlə(r)d]: adj. brightly/highly/richly etc coloured having a bright colour such as red, blue, or yellow etc, or a deep shade of a particular colour, but not black, white, or plain有色的
- A colored regiment of households won't agree with our fair plan.
- The colored legion has already been killed in action.
- Our warriors died fighting against these colored infantries.
conditioned [kənˈdɪʃ(ə)n]: adj. 有条件的
- Our needs is so subjective that it's often conditioned by our emotions and circumstances.
- Sadly, the love from my father is conditioned.
- Our marriage is conditioned, that you have to offer me one million dollars as a gift.
straightforward [ˌstreɪtˈfɔrwərd]: adj. simple and easy to understand OPP complicated简单的, 易懂的, 直接了当的
- It reminds me of a straightforward saying, one man's meat is another man's poison.
- Your words are always so straightforward that I can't think of what can resist your request.
- Give me a straightforward answer, otherwise there will still be confusion.
neutral [ˈnutrəl]: adj. IN AN ARGUMENT ETC not supporting any of the people or groups involved in an argument or disagreement ⇨ partisan中立的
- A country who tries to remain neutral will always be beneficial for its people. 
- Remaining neutral, her sister was not tempted into jumping into the battle of the bastards.
- Remaining neutral, he will not stand our side.
interaction [ˌɪntərˈækʃən]: n. a process by which two or more things affect each other交流
- Our interaction should be kept in secret.
- My girlfriend asked to prevent our interaction from our parents.
- There's a very real possibility that our interaction has been found out by our parents.
attain [əˈteɪn]: v. to succeed in achieving something after trying for a long time得到,达到
- I always attained some snacks or pocket money from my grandfather after I have done his work.
- Failing to attain lands from these kings, the nomads pushed their way westward in the plain.
- Because of his obedience, he never fails to attain pocket money from his aunts or uncles.
subjective [səbˈdʒektɪv] subjectively: adj.adv. a statement, report, attitude etc that is subjective is influenced by personal opinion and can therefore be unfair OPP objective主观的
- Why don't you take it subjectively?
- He is so subjective that he always follows his heart when he makes some decisions.
- Being subjective is not equal to spontaneity or following your heart.
analysis [əˈnæləsɪs]: n. a careful examination of something in order to understand it better分析
- A detailed analysis of our sales in last year proves his hard work.
- A political analysis of seven kingdoms has revealed his ambition.
- He can't resist the temptation to jump into reading the analysis.
--------------------
from ... onwards: from ... onwards beginning at a particular time or age and continuing after that从...起
- From the day onwards, I never lose my lead in exams in my class.
- From the year onwards, the two countries have been at war with each other.
- From the day onwards, the widow was determined to poison everyone who slaughtered her household.
Very often, + ...: 通常, +...
- Very often, people are unwilling to sacrifice all their savings for the service of surgeons.
- Very often, the officials in the community will put forward a plan to improve our situation.
- Very often, the officious Officer will regard you as a smuggler when you are nervous across the Green Channel.
a big share of sth.: 某物的很大一部分
- A big share of pocket money was exchanged for chocolates in the shop.
- A big share of income of our family comes from our jewelry shop.
- A big share of tourists come here for admiring the beautiful scene in the West Lake.
start off with sth.: 以某物开始
- Starting off with Kasha, then he should end up with Kasha.
- Starting off with a series of parades, our celebration has been inaugurated with cheers.
- Starting off with a fight, he began to dominate the battles in the continent.
leap onto the idea that + ...: 跳跃到这个想法...
- The worker leapt onto the idea that why the box was so heavy that there must have been something hidden.
- My wife leapt onto the idea that she could go on a vacation at seaside resort.
- I leapt onto the idea that we invited the household to play hockey in my house.
take ... attitude: 采取什么的态度
- The assistant didn't like the attitude the customer took and told her that it has been sold out.
- The manager will reprimand you for the attitude you took to your customer.
- The positive attitude I had taken after I lost in a game has been reprimanded by my grandfather.
A be weaved into B: A被织入B
- When the king's attitude weaved into his letter comes to London, no one takes it seriously.
- His love to his wife has been waved into letters he sent to her for years.
- The truth of the murder has been weaved into an article which was published by a journalist, the criminal.
be focused on sth.: 专注于某事
- I am focused on finishing my job, don't interrupt me any more.
- The cat is focused on drinking, so you can touch it softly.
- My grandmother seems to be focus on worship, let's keep quiet.
** sentence2
receptive [rɪˈseptɪv]: adj. willing to consider new ideas or listen to someone else’s opinions善于接受的, 能接纳的
- If you don't have basic receptive skills and jump in, you will probably get severely hurt.
- These receptive skills the teacher taught need practicing a great deal.
- The queen was so receptive that she decided to be allied with the king in the north.
target [ˈtɑrɡət]: v. to make something have an effect on a particular limited group or area针对
- Obviously, these TV series were designed to target housewives. 
- Our cookies are supposed to target those people who are reluctant to make breakfast.
- The toothpaste which is designed to target housewives is adored by poor and rich alike.
objective [əbˈdʒektɪv]: adj. based on facts, or making a decision that is based on facts rather than on your feelings or beliefs OPP subjective客观的
- If you run into serious trouble, you'd better calm your nerves and be objective.
- When the queen is in the face of the death of her son, she will never be objective and crucify us all.
- From an objective perspective, you don't have to stay up overnight in the hay.
household [ˈhaʊsˌhoʊld]: n. all the people who live together in one house SYN house一家人, 家庭, 家族, 王室
- No one could account for the fact the mad king killed the household. 
- The household that fought bravely in the battle should have been rewarded with a fief in the east.
- The household that put forward a plan of killing the king in the north at the wedding has been poisoned by one of his widows.
colored [ˈkʌlə(r)d]: adj. brightly/highly/richly etc coloured having a bright colour such as red, blue, or yellow etc, or a deep shade of a particular colour, but not black, white, or plain有色的
- A colored regiment of households won't agree with our fair plan.
- The colored legion has already been killed in action.
- Our warriors died fighting against these colored infantries.
conditioned [kənˈdɪʃ(ə)n]: adj. 有条件的
- Our needs are so subjective that it's often conditioned by our emotions and circumstances.
- Sadly, the love from my father is conditioned.
- Our marriage is conditioned, that you have to offer me one million dollars as a gift.
straightforward [ˌstreɪtˈfɔrwərd]: adj. simple and easy to understand OPP complicated简单的, 易懂的, 直接了当的
- It reminds me of a straightforward saying, one man's meat is another man's poison.
- Your words are always so straightforward that I can't think of what can resist your request.
- Give me a straightforward answer, otherwise, there will still be confusion.
neutral [ˈnutrəl]: adj. IN AN ARGUMENT ETC not supporting any of the people or groups involved in an argument or disagreement ⇨ partisan中立的
- A country that tries to remain neutral will always be beneficial for its people. 
- Remaining neutral, her sister was not tempted into jumping into the battle of the bastards.
- Remaining neutral, he will not stand our side.
interaction [ˌɪntərˈækʃən]: n. a process by which two or more things affect each other交流
- Our interaction should be kept secret.
- My girlfriend asked to prevent our interaction with our parents.
- There's a very real possibility that our interaction has been found out by our parents.
attain [əˈteɪn]: v. to succeed in achieving something after trying for a long time得到,达到
- I always attain some snacks or pocket money from my grandfather after I have done his work.
- Failing to attain lands from these kings, the nomads pushed their way westward in the plain.
- Because of his obedience, he never fails to attain pocket money from his aunts or uncles.
subjective [səbˈdʒektɪv] subjectively: adj.adv. a statement, report, attitude etc that is subjective is influenced by personal opinion and can therefore be unfair OPP objective主观的
- Why don't you take it subjectively?
- He is so subjective that he always follows his heart when he makes some decisions.
- Being subjective is not equal to spontaneity or following your heart.
analysis [əˈnæləsɪs]: n. a careful examination of something in order to understand it better分析
- A detailed analysis of our sales last year proves his hard work.
- A political analysis of seven kingdoms has revealed his ambition.
- He can't resist the temptation to jump into reading the analysis.
--------------------
from ... onwards: from ... onwards beginning at a particular time or age and continuing after that从...起
- From that day onwards, I never lose my lead in exams in my class.
- From that year onwards, the two countries have been at war with each other.
- From that day onwards, the widow was determined to poison everyone who slaughtered her household.
Very often, + ...: 通常, +...
- Very often, people are unwilling to sacrifice all their savings for the service of surgeons.
- Very often, the officials in the community will put forward a plan to improve our situation.
- Very often, the officious Officer will regard you as a smuggler when you are nervous across the Green Channel.
a big share of sth.: 某物的很大一部分
- A big share of pocket money was exchanged for chocolates in the shop.
- A big share of income in our family comes from our jewelry shop.
- A big share of tourists come here to admire the beautiful scene in the West Lake.
start off with sth.: 以某物开始
- Starting off with Kasha, then he should end up with Kasha.
- Starting off with a series of parades, our celebration has been inaugurated with cheers.
- Starting off with a fight, he began to dominate the battles on the continent.
leap onto the idea that + ...: 跳跃到这个想法...
- The worker leaped onto the idea that the box was so heavy that there must have been something hidden.
- My wife leaped onto the idea that she could go on a vacation at a seaside resort.
- I leaped onto the idea that we invited the household to play hockey in my house.
take ... attitude: 采取什么的态度
- The assistant didn't like the attitude the customer took and told her that it had been sold out.
- The manager will reprimand you for the attitude you took to your customer.
- The positive attitude I had taken after I lost in a game has been reprimanded by my grandfather.
A be weaved into B: A被织入B
- When the king's attitude weaved into his letter comes to London, no one takes it seriously.
- His love for his wife has been waved into letters he sent to her for years.
- The truth of the murder has been weaved into an article which was published by a journalist, the criminal.
be focused on sth.: 专注于某事
- I am focused on finishing my job, don't interrupt me anymore.
- The cat is focused on drinking, so you can touch it softly.
- My grandmother seems to be focused on worship, let's keep quiet.
** summary
The receptive skills, reception and expression, both targeted the same four main content areas:
	facts, attitudes, emotions, and needs.
It is actually based on our experience, helping people manage emotional issues.
Very often, people try to establish facts at the beginning of communication.
But facts are so subjective that they are always conditioned by our emotional needs and attitudes.
For example,
	if you ask who has done a big share of housework, you will not have the same answer from everyone.
So whatever we are communicating,
	we have to pay attention to attitudes that people take,
		the values weaved into the message, emotions they have.
Back to SSLD core concept, SSLD is always focused on needs,
	for the reason why we want to commnuicate with each other is
		there is something we need from the interaction.
In sum, the four key content areas are:
	facts which can be subjective, depending on our attitudes, emotions, and our needs.
** summary2
The reception and expression skill both targeted the same four main content areas:
	Facts, attitudes, emotions, and needs.
It is based on our experience, helping people manage emotional issues.
Very often, people try to establish facts at the beginning of communication.
But facts are so subjective that they are always conditioned by our emotional needs and attitudes.
For example, if you ask who has done a big share of the housework,
	you will not get the same answer from everyone.
So whatever we are communicating,
	we have to pay attention to the attitudes that people take,
		the values weaved into the message and the emotions they have.
Back to the SSLD core concept, SSLD is always focused on needs,
	for the reason why we want to communicate with each other is
		there is something we need from the interaction.
In sum, the four key content areas are:
	Facts can be subjective, depending on our attitudes, emotions, and needs.
