#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.10 Attributions 1 - Introduction
#+begin_verse
In your book, you talk about how one way to make sense of people's attitudes and opinions is
	to take a look at their attributional frame.
I'm wondering if you can sort of explain what that is.

Well, yeah, when people experience something, see something,
	they usually will make some attribution,
		that's trying to explain it,
			or trying to point out or find out what the cause or what we are experiencing might be.
So I'm an immigrant in this country,
	so I remember when I first came to this country
		and people were blaming the immigrants for driving up the housing prices.
And then it was so interesting that within the same newspaper that I read,
	[LAUGH] on the same day, there was another commentary saying that,
		this neighbourhood is now having a lot of immigrants coming in.
There are minorities, and it is driving the real estate prices down.
[LAUGH]

So you can always attribute something to something, whether it is factually true or not.
And then, obviously, when I was going through that, I was going, okay, all right,
	when you say that the immigrants are driving up the real estate prices,
		so who are paying the high prices?
Mm-hm.
It would be the immigrants.
Who are getting those high prices?
[LAUGH] Yeah.
[LAUGH] The people who are selling the real estate, right?
So why is it a problem?

But then you can very often see people making attributions like that.
And then very often, we also make attributions in relationships.
Say for example, in a breakup situation, people would try to figure out why are we breaking up?
Why is she or why is he leaving me?
And people usually want to attribute it to something simple, right?
So he is leaving me for a younger woman, right?
And you're attributing it to age, right?
Mm-hm.
When you're saying that he doesn't need my financial support anymore,
	you're attributing it to a financial reason for this relationship breakup.
Yeah.
So this may or may not be true.
We don't know, right?

But my general approach to this is
	that when someone tells you something, the person is always attributing.
Attribution is something that we constantly do.
So whenever you ask the reason why,
	when you ask the reason for a decision to be made, of an action to be taken,
		there is always attribution involved.
And this is important for us to be able to figure this out.

Here's a definition of the concept introduced in this lecture.
Attribution: it's when one is regarding something as being caused by something else.
This can happen in any situation when you try to explain the cause of an experience,
	whether it is factually true or not.
For example, let's say a couple has broken up and the man is now with a much younger girl.
You might think that he left the previous partner for a younger woman,
	and attributing the cause of their breakup to age.
#+end_verse
** expression
attribution [ˌætrɪˈbjuʃ(ə)n]: n. 归因
immigrant [ˈɪmɪɡrənt]: n. someone who enters another country to live there permanently ⇨ emigrant移民
commentary [ˈkɑmənˌteri]: n. a spoken description of an event, given while the event is happening, especially on the television or radio实况报道
minority [maɪˈnɔrəti]: n. a small group of people or things within a much larger group OPP majority少数, 少数民族
breakup [ˈbreɪkˌʌp]: n. the act of ending a marriage or relationship分手,(关系)破裂
financial [faɪˈnænʃ(ə)l]: adj. relating to money or the management of money财政的
--------------------
make sense of sth./sb.: 弄清某人某事
take a look at sth.: 看一看某物
drive up/down ... prices: 抬高/抬低价格
attribute A to B: 把A归因于B
** sentence
attribution [ˌætrɪˈbjuʃ(ə)n]: n. 归因
- When you cease to make useless attributions and pay attention to our next action, we will get out of trouble.
- The CEO of the company has a habit of making attributions after scandals.
- These scientists can do nothing but make useless attributions to explain what has happened.
immigrant [ˈɪmɪɡrənt]: n. someone who enters another country to live there permanently ⇨ emigrant移民
- Justice has been done when the immigrants in this state are no longer mistreated. 
- It must be the immigrants who drove up the real estatel prices in the suburb of the city.
- Being an expert at education, the immigrant received a warm welcome at the remote village.
commentary [ˈkɑmənˌteri]: n. a spoken description of an event, given while the event is happening, especially on the television or radio实况报道
- You should have taken a look at the commentary about our royal scandal.
- Noticing the contents of the commentary is factually false, the prince was shocked and threatened to hang the journalist.
- The crowd were appalled at the contents of the commentary.
minority [maɪˈnɔrəti]: n. a small group of people or things within a much larger group OPP majority少数, 少数民族
- My grace, you're admired by poor and rich alike, so you're not minority.
- A minority of the party organized parades to protest your decisions about the war.
- A minority of the party is under our control now, lord commander.
breakup [ˈbreɪkˌʌp]: n. the act of ending a marriage or relationship分手,(关系)破裂
- The breakup of my sister and him is beyond my imagination.
- A mistaken understanding about the last word of the king before his death led to the breakup of the capital and the island.
- I have done many things wrong in my life, but not including the breakup with your sister.
financial [faɪˈnænʃ(ə)l]: adj. relating to money or the management of money财政的
- The talkshow actress is determined to get divorced with her husband who gave her financial assistance when she was going to university.
- The actress was abused by the student who she ceased to give financial assistance.
- Beyond doubt, our allies will give us financial assistance when we are at war with the North.
--------------------
make sense of sth./sb.: 弄清某人某事
- You still haven't made sense of our father, you're not the true heir to the Iron Throne.
- Making sense of last breakup, she committed to a new romantic relationship.
- It may be hard to make sense of our cat who gets used to do acitivities at night.
take a look at sth.: 看一看某物
- Take a look at our products which are on the promotion.
- If you have taken a look at your history book, you wouldn't have failed your exam again.
- Darling, take a look at our baby, he has broken your favorite crockery.
drive up/down ... prices: 抬高/抬低价格
- Natives abuse us blaming us for driving up the real estate prices.
- Natives are parading blaming us for driving down the real estate prices.
- These manufacturers were sentensed to death for driving up sustenance prices during the war.
attribute A to B: 把A归因于B
- It is unfair that your grace attributes the failure of the war to your unborn son.
- Attributing the failure of the war to the lack of sustenance, the king encouraged peasants to cultivate new kinds of spieces.
- Attributing her unhappiness to me, my wife abused me every day.
** sentence2
attribution [ˌætrɪˈbjuʃ(ə)n]: n. 归因
- When you cease to make useless attributions and pay attention to your next action, you will get out of trouble.
- The CEO of the company has a habit of making attributions after scandals.
- These scientists can do nothing but make useless attributions to explain what has happened.
immigrant [ˈɪmɪɡrənt]: n. someone who enters another country to live there permanently ⇨ emigrant移民
- Justice has been done when the immigrants in this state are no longer mistreated. 
- It must be the immigrants who drove up the real estate prices in the suburbs of the city.
- Being an expert at education, the immigrant received a warm welcome at the remote village.
commentary [ˈkɑmənˌteri]: n. a spoken description of an event, given while the event is happening, especially on the television or radio实况报道
- You should have taken a look at the commentary about our royal scandal.
- Noticing the contents of the commentary is factually false, the prince was shocked and threatened to hang the journalist.
- The crowd was appalled at the contents of the commentary and burst into tears.
minority [maɪˈnɔrəti]: n. a small group of people or things within a much larger group OPP majority少数, 少数民族
- My grace, you're admired by poor and rich alike, so you're not a minority.
- A minority of the party organized parades to protest your decisions about the war.
- A minority of the party is under our control now, lord commander.
breakup [ˈbreɪkˌʌp]: n. the act of ending a marriage or relationship分手,(关系)破裂
- The breakup of my sister and him is beyond my imagination.
- A mistaken understanding of the last word of the king before his death led to the breakup of the capital and the island.
- I have done many things wrong in my life, but not including the breakup with your sister.
financial [faɪˈnænʃ(ə)l]: adj. relating to money or the management of money财政的
- The talk show actress is determined to get divorced from her husband who gave her financial assistance when she was going to university.
- The actress was abused by a student who she ceased to give financial assistance to.
- Beyond doubt, our allies will give us financial assistance when we are at war with the North.
--------------------
make sense of sth./sb.: 弄清某人某事
- You still haven't made sense of our father, you're not the true heir to the Iron Throne.
- Making sense of the last breakup, she committed to a new romantic relationship.
- It may be hard to make sense of our cat who gets used to doing activities at night.
take a look at sth.: 看一看某物
- Take a look at our products which are on the promotion.
- If you have taken a look at your history book, you wouldn't have failed your exam again.
- Darling, take a look at our baby, he has broken your favorite crockery.
drive up/down ... prices: 抬高/抬低价格
- Natives abuse us blaming us for driving up the real estate prices.
- Natives are parading blaming us for driving down the real estate prices.
- These manufacturers were sentenced to death for driving up sustenance prices during the war.
attribute A to B: 把A归因于B
- It is unfair that your grace attributes the failure of the war to your unborn son.
- Attributing the failure of the war to the lack of sustenance, the king encouraged peasants to cultivate new kinds of species.
- Attributing her unhappiness to me, my wife abused me every day.
** summary
One way to make sense of people's attitudes and opinions is to look at their attributional frame.
When something happens to people, they usually will make some attributions,
	trying to explain it or find out the cause.
For example, when I first came to this country as an immigrant,
	people were blaming immigrants for driving up the real estate both up and down.
So you can always attribute something to something, whether it is factually true or not.
Very often, we also make attributions in relationships.
Such as, attributing a breakup to age or a financial reason.
Attriubtion is sort of something that we constantly do
	and it's important for us to be able to figure this out.
** summary2
One way to make sense of people's attitudes and opinions is to look at their attributional frame.
When something happens to people, they usually will make some attributions,
	trying to explain it or find out the cause.
For example, when I first came to this country as an immigrant,
	it was interesting
		that people blamed immigrants for driving the real estate prices both up and down.
So you can always attribute something to something, whether it is factually true or not.
Very often, we also make attributions in relationships.
Such as attributing a breakup to age or a financial reason.
Attribution is sort of something that we constantly do
	and we need to be able to figure this out.
