#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.8 Reception - Importance of understanding someone's needs
#+begin_verse
In reception,
	the ability to listen is really important but also the ability to understand the other person.
I'm wondering if you could sort of comment more on that.

Yes, of course.
An important experience that I have over the last ten, twelve years, is
	I go to different places and talk to people about relationships
		and I very often ask the audience the same question.
I ask them to indicate how many people in your life do really understand you,
	especially with regard to your needs?
And I think that the general impression that I've got is
	that very few people would indicate that they've got five persons or more who can do that.
Most people have only one or two and there's actually a large number of people saying
	that I don't really have anyone in my life who really understands me and understands my needs.
So it shows us how important it is,
	if you can become the person who can understand another person well
		especially with regard to that person's need.
You are already in a very special position to develop a significant relationship with this person.
Right? So this is why we really want to be emphasizing that understanding is so important.
Because we understand
	that when you have achieved this kind of understanding the other person feels understood
		and you know exactly what his or her needs are.
Trust will develop and it will be a very important condition for a good relationship.
The ability to listen and to understand the other persons need is very important.
If you're able to understand someone else's need,
	you're already in a significant position of that person's life
		as not many people actually do understand the needs of others.
Trust will develop at this way.
And that's
	why having good receptive skills is an important condition of a healthy and good relationship.
#+end_verse
** expression
audience [ˈɔdiəns]: n. a group of people who come to watch and listen to someone speaking or performing in public听众, 观众
--------------------
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."关于某事物
It shows sb. that + ...: 它向某人表明 + ...
be already in a ... position to do sth.:  已处于...的位置做某事
** sentence
audience [ˈɔdiəns]: n. a group of people who come to watch and listen to someone speaking or performing in public听众, 观众
- Beyond doubts, the fighting ring will be full of audiences.
- Short of audiences, the theater seems to go bankrupt.
- Appalled at the defeat of shame, the audiences in the ring began to throw their bottles.
--------------------
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."关于某事物
- Have you ever heart your father carefully, especially with regard to your education?
- Short of sustenance, our soilders will lose their hearts with regard to the victory of the war.
- Inspired by his wife's words, he took hearts again with regard to English skills.
It shows sb. that + ...: 它向某人表明 + ...
- It shows me how these snails take possession of the hall from the paper bag. 
- It shows me that our people are always starving to death.
- It shows me how vicious our king are who wanted to set the city on fire.
be already in a ... position to do sth.:  已处于...的位置做某事
- Don't be hard on your child, he is already in a favorable position to seize power.
- Following in his father's footsteps, the king is already in a special position to inherit the Iron Throne.
- Overruning the capital of the empire, the army is already in a advanced position to control the country.
** sentence2
audience [ˈɔdiəns]: n. a group of people who come to watch and listen to someone speaking or performing in public听众, 观众
- Beyond doubt, the fighting ring will be full of audiences.
- Short of audiences, the theater seems to go bankrupt.
- Appalled at the defeat of shame, audiences in the ring began to throw their bottles.
--------------------
with regard to sth.: be used synonymously with phrases like "concerning," "in relation to," or "regarding."关于某事物
- Have you ever heard your father carefully, especially with regard to your education?
- Short of sustenance, our soldiers will lose their hearts with regard to the victory of the war.
- Inspired by his wife's words, he took hearts again with regard to English skills.
It shows sb. that + ...: 它向某人表明 + ...
- It shows me how these snails take possession of the hall from the paper bag. 
- It shows me that our people are always starving to death.
- It shows me how vicious our king is who wanted to burn down the city.
be already in a ... position to do sth.:  已处于...的位置做某事
- Don't be hard on your child, he is already in a favorable position to seize power.
- Following in his father's footsteps, the king is already in a special position to inherit the Iron Throne.
- Overrunning the capital of the empire, the army is already in an advanced position to control the country.

