#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.3 Reception overview
#+begin_verse
In terms of reception,
	if you are talking to another person, and you're really trying to understand them,
		what are some of the things that you should be paying attention to?
Well obviously, the one thing that almost everyone will pay attention to is the factual content
	that this person is communicating.
If someone is telling you about oil prices, real estate prices going up or down.
It's telling you about whether you're paying any attention to the facts.

Actually, talking about the weather is a good example
	because when the people talk about the weather, they are not really talking about the weather.
So this leads us to this very important position
	that the facts are not always the most important aspect of the communication.
But that is one of the things
	that most people without special training or education or learning
		would almost be automatically paying attention to.
And this is also something that I've been learning since elementary school.
So that is one thing that people know, and we probably won't be spending too much time on.
But the other aspects of the communication, the other dimensions that are less obvious,
	like emotional content, the kind of needs that people are trying to express.
And there is a huge area that we can be exploring.
It's helping people
	by saying something or actually communicating with positions that they're coming from.
They may be also telling you about their values, their preferences.
So, those are the things that we want to be paying attention to.
#+end_verse

** expression
factural [ˈfæktʃuəl]: based on facts or relating to facts事实的, 实际的
aspect [ˈæspekt]: one part of a situation, idea, plan etc that has many parts方面
automatic [ˌɔtəˈmætɪk] automatically: an automatic machine is designed to work without needing someone to operate it for each part of a process ⇨ manual自动的
elementary [ˌeləˈment(ə)ri]: simple or basic初步的, 基本的
preference [ˈpref(ə)rəns]: if you have a preference for something, you like it more than another thing and will choose it if you can ⇨ prefer偏爱, 优先选择
--------------------
real estate: 不动产
price go up/down: 上升/下降
** sentence
factual [ˈfæktʃuəl]: based on facts or relating to facts事实的, 实际的
- No one could neglect the factural existence of the white walker.
- The factural bastard led to severe wars in the seven kingdom.
- There are always some outdated factural events on the newspaper.
aspect [ˈæspekt]: one part of a situation, idea, plan etc that has many parts方面
- Communication is the critical aspect of our interaction on a daily basis.
- Kindness is said to the important aspect of his characteristics.
- The dark aspect of his characteristics can give rise to another war on the continent.
automatic [ˌɔtəˈmætɪk] automatically: an automatic machine is designed to work without needing someone to operate it for each part of a process ⇨ manual自动的
- The entrepreneur will set up a factory in the suburb of the city equipped with automatic machine.
- My roommates voted for buying a fully automatic wash machine in our dormitory.
- It appeared to have worked automatically.
elementary [ˌeləˈment(ə)ri]: simple or basic初步的, 基本的
- When I was in the elementary school, I thought that I would be grown-up in the high school.
- They sacked our city burning down the elementary school.
- Nowadays, playing truant from the elementary school becomes popular with these children.
preference [ˈpref(ə)rəns]: if you have a preference for something, you like it more than another thing and will choose it if you can ⇨ prefer偏爱, 优先选择
- My cousin accused his father of the preference for another cousin.
- My husband has had a preference for his cat and neglects my health.
- Having a preference for his daughter, he reprimanded only his son for the loss of the ship.
--------------------
real estate: 不动产
- My wife had dreamt of possessing a real estate in the city before we got married.
- When the price of real estate in the suburb began to drop, my wife regretted ignoring my advise.
- The price of real estate is under the control of our government, so it's impossible to drop.
price go up/down: 上升/下降
- With price going up, I decided to give up something unneccessary. 
- With price going up, these poor are starving to death because of the war you started.
- With price going down, the housewife emptied her cart on a promotion day.
** sentence2
factual [ˈfæktʃuəl]: based on facts or relating to facts事实的, 实际的
- No one could neglect the factual existence of the white walker.
- The factual bastard led to severe wars in the seven kingdoms.
- There are always some outdated factual events in the newspaper.
aspect [ˈæspekt]: one part of a situation, idea, plan etc that has many parts方面
- Communication is a critical aspect of our interaction on a daily basis.
- Kindness is said to be an important aspect of his characteristics.
- The dark aspect of his characteristics can give rise to another war on the continent.
automatic [ˌɔtəˈmætɪk] automatically: an automatic machine is designed to work without needing someone to operate it for each part of a process ⇨ manual自动的
- The entrepreneur will set up a factory in the suburb of the city equipped with automatic machines.
- My roommates voted to buy a fully automatic wash machine in our dormitory.
- It appeared to have worked automatically.
elementary [ˌeləˈment(ə)ri]: simple or basic初步的, 基本的
- When I was in elementary school, I thought that I would be grown-up in high school.
- They sacked our city burning down the elementary school.
- Nowadays, playing truant from elementary school has become popular with these children.
preference [ˈpref(ə)rəns]: if you have a preference for something, you like it more than another thing and will choose it if you can ⇨ prefer偏爱, 优先选择
- My cousin accused his father of a preference for another cousin.
- My husband has had a preference for his cat and neglects my health.
- Having a preference for his daughter, he reprimanded only his son for the loss of the ship.
--------------------
real estate: 不动产
- My wife had dreamt of possessing a real estate in the city before we got married.
- When the price of real estate in the suburb began to drop, my wife regretted ignoring my advice.
- The price of real estate is under the control of our government, so it's impossible to drop.
price go up/down: 上升/下降
- With the price going up, I decided to give up something unnecessary. 
- With the price going up, these poor are starving to death because of the war you started.
- With the price going down, the housewife emptied her cart on a promotion day.
** summary
What are some of the things that we should pay attention to when we communicate with a person?
Almost everyone will pay attention to the factual content that this person is expressing.
Like oil prices, real estate prices going up or down.
It's focused on whether you're paying attention to the facts.
However, the facts are not always the most important aspects of the communication.
For example, talking about the weather is not really talking about the weather.
What we are focused on are emotional content, and needs that people are trying to express.
Sometimes, people also tell us about their positions, values, and preferences.
Those are the things that we want to pay attention to.
