#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.6 Reception - Ideas 3 - Opinions
#+begin_verse
It sounds like there are almost patterns
	that you can pick up with people
	based on how they present facts
		and the kind of underlying attitudes and positions that they take.
Yes.
So that takes us on to the other dimension.
So say for example you may sometimes hear a couple fighting.
And then someone will be accusing the other person.
I never know this, whatever that is,
	like income or your looks or the size of your breasts or whatever is so important to you.
But very often, when you think back on how this person talks about other persons,
	this is what we call characterization, right?
Right.
It's telling you a lot about what is important to this person.

Say for example, this person who is telling you about his or her friends,
	and every time you mention someone he or she knows
		it will always be referring to this person's profession, income.
That means to this person, professional status and income are important.
Or someone is telling you about his or her friends.
Constantly referring to this person's physical features.
Height, hair color, body shape.
So that also tells you that to him or her, these are important.
If someone tells you about someone always where this person comes from.
	which country, or ethnicity, or religion for that matter.
Then that tells you more about this person than the people that this person is talking about.

So, giving you an example, like if I tell you that Jane is such an animal lover, right?
That means animal lover is a label that has significance for me, right?
And if I, for another person, they would not be animal lover.
For another person is like, Jane is such a music lover, right?
Yeah.
So when I tell you something about Jane, I'm actually telling you something about me.
Okay.
So this is like what we refer to as like the characterization frame.

Right, right.
And I guess then, in what a person tells you can also affect how they are seeing you.
Yeah, exactly.
I am referring constantly to these dimensions.
You're right.
I may actually be using the same parameters or same dimension.
In my assessment of you, who you are and your value as a human being.
As a friend I may be actually be referring to this.
Say for example
	if I think that education is important
		and then I'm interacting with someone who is less educated.
If I keep referring to people's educational credentials and background
	you have sense that like, where do I stand?
[LAUGH]
Yeah, exactly.
Yeah, so I guess that sort of answers this question
but what is the benefit of being able
	to pick up on something in your interactions with individuals.
Well, I would say that most people actually were able to do that.
What we are trying to say here is to basically draw your attention to those different dimensions.
So when we are listening to people,
	we understand that we shouldn't just be paying attention to facts.
We know that there are other dimensions as well
	and that we pay attention to those dimensions
	and sometimes when we're asked questions like, why is this person saying this?
It will actually help us to gain a more in-depth understanding of what the other person is up to.
Right.
Yeah.
#+end_verse
** expression
breast [brest]: n. one of the two round raised parts on a woman’s chest that produce milk when she has a baby胸部
characterization [ˌkerəktərɪˈzeɪʃ(ə)n]: n. the way in which the character of a real person or thing is described描述
profession [prəˈfeʃ(ə)n]: n. a job that needs a high level of education and training职业,专业
religion [rɪˈlɪdʒən]: n. a particular system of this belief and all the ceremonies and duties that are related to it宗教,信仰
label [ˈleɪb(ə)l]: n. a word or phrase which is used to describe a person, group, or thing, but which is unfair or not correct标签
parameter [pəˈræmɪtər]: n. a set of fixed limits that control the way that something should be done界限,范围
assessment [əˈsesmənt]: n. a process in which you make a judgment about a person or situation, or the judgment you make评估
credentials [krəˈdenʃ(ə)lz]: n. someone’s education, achievements, experience etc that prove they have the ability to do something资格,资格证书
in-depth [depθ]: adj. thorough, complete, and considering all the details深入的
---------------------
refer to: 提及,称为
That means to sb. + ...: 那对于某人意味着...
for that matter: 说到那一点
sb. guesses that + ...: 某人猜测...
be up to sth.: Be able to do or deal with 能做某事,处理某事
** sentence
breast [brest]: n. one of the two round raised parts on a woman’s chest that produce milk when she has a baby胸部
- His girlfriend accused him of caring about the size of her breast too much. 
- It is said that the size of breat will be enlarged after pregnancy.
- In the end, she couldn't bear her husband who is also complaining about her breast.
characterization [ˌkerəktərɪˈzeɪʃ(ə)n]: n. the way in which the character of a real person or thing is described描述
- The characterization of his father was so vivid that I recognized his father when we first met.
- The characterization of his pirate story added on piece to his legendary life. 
- The detective has spent many time reflecting on the characterization of the thief.
profession [prəˈfeʃ(ə)n]: n. a job that needs a high level of education and training职业,专业
- He is a good man who makes friends whatever his or her profession is.
- He delayed in publishing an article on his profession in the press.
- What invariably happens is that we miss out on the opportunities to do work about our profession.
religion [rɪˈlɪdʒən]: n. a particular system of this belief and all the ceremonies and duties that are related to it宗教,信仰
- She apologized to me that she should've respected my religion.
- Even though the king sentenced him to death, he still insisted on his religion.
- The religion of people on the isolated island is very different from people on the continent.
label [ˈleɪb(ə)l]: n. a word or phrase which is used to describe a person, group, or thing, but which is unfair or not correct标签
- These days, men are often attracted the 'sexist' label because of some inappropriate speaking in public.
- Noticing that he was attracted the 'coward' label, he slammed the door and refused to attend the council.
- The soldier attracted the 'coward' label died fighting in the battle.
parameter [pəˈræmɪtər]: n. a set of fixed limits that control the way that something should be done界限,范围
- These watchdogs shall be keep within the parameters our master laid down.
- Reek, you are forbidden to wander outside the parameters your master laid down.
- Because of monsters in the mountain, the monk only moved with the parameters his apprentice laid down.
assessment [əˈsesmənt]: n. a process in which you make a judgment about a person or situation, or the judgment you make评估
- In my assessment of my father, he is a very great man.
- Our assessment of you shows that you are not up to our job.
- Sorry to inform you that the assessment of your ability is not so well.
credentials [krəˈdenʃ(ə)lz]: n. someone’s education, achievements, experience etc that prove they have the ability to do something资格,资格证书
- My manager asked me to develop a function which can generate credentials after taking exam.
- Although the man has many credentials, he was not able to deal with his emotion and relationships with his colleagues.
- The credentials are useless, for I haven't found a job for a long time.
in-depth [depθ]: adj. thorough, complete, and considering all the details深入的
- It comes on suddenly that he didn't have an in-depth understanding of his wife.
- Not having an in-depth understanding of his wife, he presented his wife with a gift which she doesn't like.
- After we have an in-depth understanding of the project, everything goes smoothly.
---------------------
refer to: 提及,称为
- Why are you keep referring to the size of my breast? It's none of your business.
- As you referred to your father, he is a man with honor who never breaks his oath.
- As you referred to our house, it is me who paid for it, not you.
That means to sb. + ...: 那对于某人意味着...
- That means to me I can't go on a vacation with you at seaside resort.
- That means to me I lost in the gamble.
- That means to me I am gonna be crucified in front of our people.
for that matter: 说到那一点
- For that matter, it reminds me of our worker who used to clear up our table.
- For that matter, it reminds me of your lover who betrayed you twice.
- For that matter, your wife has poisoned five her husbands in her youth.
sb. guesses that + ...: 某人猜测...
- I guess that you have lost your temper when you received a cold welcome in the restaurant.
- I guess that your stray cat have been found.
- I guess that our rubbish was thrown away by a kind worker.
be up to sth.: Be able to do or deal with 能做某事,处理某事
- Are you up to a walk after dinner?
- I am up to a walk, even though I climbed mountain yesterday.
- Our cat is up to eat punctually, don't be too hard on yourself.
** sentence2
breast [brest]: n. one of the two round raised parts on a woman’s chest that produce milk when she has a baby胸部
- His girlfriend accused him of caring about the size of her breasts too much. 
- It is said that the size of breasts will be enlarged after pregnancy.
- In the end, she can't bear her husband who is always complaining about her breasts.
characterization [ˌkerəktərɪˈzeɪʃ(ə)n]: n. the way in which the character of a real person or thing is described描述
- The characterization of his father was so vivid that I recognized his father when we first met.
- The characterization of his pirate story added on piece to his legendary life. 
- The detective has spent much time reflecting on the characterization of the thief.
profession [prəˈfeʃ(ə)n]: n. a job that needs a high level of education and training职业,专业
- He is a good man who makes friends whatever his or her profession is.
- He delayed publishing an article on his profession in the press.
- What invariably happens is that we miss out on the opportunities to do work about our profession.
religion [rɪˈlɪdʒən]: n. a particular system of this belief and all the ceremonies and duties that are related to it宗教,信仰
- She apologized to me that she should've respected my religion.
- Even though the king sentenced him to death, he still insisted on his religion.
- The religion of people on the isolated island is very different from people on the continent.
label [ˈleɪb(ə)l]: n. a word or phrase which is used to describe a person, group, or thing, but which is unfair or not correct标签
- These days, men are often attracted to the 'sexist' label because of inappropriate speaking in public.
- Noticing that he was attracted to the 'coward' label, he slammed the door and refused to attend the council.
- The soldier attracted the 'coward' label died fighting in the battle.
parameter [pəˈræmɪtər]: n. a set of fixed limits that control the way that something should be done界限,范围
- These watchdogs shall be kept within the parameters our master laid down.
- Reek, you are forbidden to wander outside the parameters your master laid down.
- Because of monsters in the mountain, the monk only moved with the parameters his apprentice laid down.
assessment [əˈsesmənt]: n. a process in which you make a judgment about a person or situation, or the judgment you make评估
- In my assessment of my father, he is a very great man.
- Our assessment of you shows that you are not up to our job.
- I'm sorry to inform you that the assessment of your ability is not so well.
credentials [krəˈdenʃ(ə)lz]: n. someone’s education, achievements, experience etc that prove they have the ability to do something资格,资格证书
- My manager asked me to develop a function that can generate credentials after taking exams.
- Although the man has many credentials, he is not able to deal with his emotions and relationships with his colleagues.
- The credentials are useless, for I haven't found a job for a long time.
in-depth [depθ]: adj. thorough, complete, and considering all the details深入的
- It comes on suddenly that he didn't have an in-depth understanding of his wife.
- Not having an in-depth understanding of his wife, he presented his wife with a gift that she didn't like.
- After we have an in-depth understanding of the project, everything goes smoothly.
---------------------
refer to: 提及,称为
- Why do you keep referring to the size of my breasts? It's none of your business.
- As you referred to your father, he is a man with honor who never breaks his oath.
- As you referred to our house, it is me who paid for it, not you.
That means to sb. + ...: 那对于某人意味着...
- That means to me I can't go on a vacation with you at a seaside resort.
- That means to me I lost in the gamble.
- That means to me I am gonna be crucified in front of our people.
for that matter: 说到那一点
- For that matter, it reminds me of our worker who used to clear up our table.
- For that matter, it reminds me of your lover who betrayed you twice.
- For that matter, your wife has poisoned five of her husbands in her youth.
sb. guesses that + ...: 某人猜测...
- I guess that you lost your temper when you received a cold welcome in the restaurant.
- I guess that your stray cat has been found.
- I guess that our rubbish was thrown away by a kind worker.
be up to sth.: Be able to do or deal with 能做某事,处理某事
- Are you up to a walk after dinner?
- I am up to a walk, even though I climbed a mountain yesterday.
- Our cat is up to eat punctually, don't be too hard on yourself.
** summary
There are almost patterns
	based on how people present facts, their underlying attitudes and positions.
Very often, when you think back on how this person talks about other persons,
	which is also telling you about something important to this person.
For example, every time you mention someone this person knows,
	he or she is always referring to profession, and income.
That means to this person, professional status and income are important.
For another exmple, I tell you that Jane is an animal lover,
	which means to me animal lover has significance for me.
For another person who is not an animal lover, Jane is such a music lover.
So, when I tell you something about Jane, I'm actually telling you something about me.
Besides, when I assess someone, I may be using the same dimension in my assessment of you.
If we pay attention to those, they will help us to gain a more in-depth understanding of the person.
** summary2
There are almost patterns
	based on how people present facts, and their underlying attitudes and positions.
Very often, when you think back on how this person talks about other people,
	which also tells you about something important to this person.
For example, every time you mention someone this person knows,
	he or she always refers to profession and income.
That means to this person, professional status and income are important.
For another example, I tell you that Jane is an animal lover,
	which means to me that animal lover has significance for me.
But for another person who is not an animal lover, Jane is such a music lover.
So, when I tell you something about Jane, I'm actually telling you something about me.
Besides, when I assess someone, I may be using the same dimension in my assessment of you.
If we pay attention to those, they will help us to gain a more in-depth understanding of the person.

