#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.4 Reception - Ideas 1 - Attitudes
#+begin_verse
So we kind of talked about how factual content is pretty straightforward
	and we learn about it throughout most of our lives.
Yeah.
What about the underlying attitudes that people have when they say things,
	and how does that sort of affect the interpersonal understanding of others?
	
When people talk about facts, as we said, they're not really only talking about facts.
Say for example,
	when people are talking about the weather in the elevator and like sort of a communication,
		like of I'm your friend, I mean no harm, you can feel safe.
Sometimes it can also be, I'm interested in talking to you.
So, the facts are rarely just facts.

And how facts are being presented and what facts are selectively used
	are also very important ways for people to be telling you something important about themselves.
Say for example, when we have someone trying to tell you about marriage and divorce,
	and when someone says >> more and more people >> are getting divorced.
Yeah.
Which may or may not be factually accurate depending on where you're are,
	but when someone tells you something like that,
		we wonder, you are asking the question, why is this person telling me this?
What attitude is communicated?
If someone is saying, you know, the increased divorce rate in the case like social disintegration,
	that shows you this person's values and this person's worldview.
If someone tells you that, you know,
	rising divorce rates means that more people are now exercising their agency and autonomy
		when the relationship is not working,
			I walk out and I'm not going to put up with things that I don't tolerate, I don't enjoy.
So, there are different ways of using the same fact, right?
Mm-hm.

So this is like how when we're listening for facts, we always ask, like why is it selected?
What is this person talking about?
Like you have a discussion of minimum wage,
	for instance, some people will say that, you know, this is going to hurt the economy.
Then you will know that this person probably is speaking from the position of an employer.
Mm-hm.
Like someone who runs a business,
	rather than from the position of an employee or from labor rights and interests.
So, you have things like that.
I can come up with tons of examples.
Usually, when people state the fact, the fact is selected, and it is stated with the purpose.
It is important for us to be able to decipher what kind of position the person is assuming,
	the purpose of using this fact, what effect this person is expecting this utterance to have.
#+end_verse
** expression
elevator [ˈeləˌveɪtər]: n. a machine that takes people and goods from one level to another in a building SYN lift British English电梯, 升降机
harm [hɑrm]: n. to physically hurt a person or animal伤害
selective [sɪˈlektɪv] selectively: adj.adv. affecting or relating to the best or most suitable people or things from a larger group选择的, 选择性的
agency [ˈeɪdʒənsi]: n. an organization or department, especially within a government, that does a specific job代理权
autonomy [ɔˈtɑnəmi]: n. the ability or opportunity to make your own decisions without being controlled by anyone else SYN independence自治
tolerate [ˈtɑləˌreɪt]: v. to be able to accept something unpleasant or difficult, even though you do not like it ⇨ tolerant, tolerance SYN stand, bear忍受, 容忍
decipher [dɪˈsaɪfər]: v. to find the meaning of something that is difficult to read or understand ⇨ indecipherable译解(密码等), 解释
utterance [ˈʌt(ə)rəns]: n. something you say言论
---------------------
throughout most of sb's life: 贯穿某人一生
get divorced: 离婚
... rate rises: 某某率上升
tons of sth.: 大量的某物
put up with sth.: 忍受某事 
speak from the position of sb.: 从某人的立场讲话
labor rights and interests: 劳工权益
come up with sth.=think up an idea for sth.: 想出某事
** sentence
elevator [ˈeləˌveɪtər]: n. a machine that takes people and goods from one level to another in a building SYN lift British English电梯, 升降机
- There are freaks in the elevator pissing off when nobody is there.
- My wife can't stand the smell of urine of dogs.
- After her dog piss off in the elevator, he feels obliged to clean it up right away.
harm [hɑrm]: n. to physically hurt a person or animal伤害
- Your supremacy over me on a daily basis is always doing harm to me.
- You have done harm to me everytime when you isolate me after we are divergent.
- He touched the slave's face to mean no harm to him.
selective [sɪˈlektɪv] selectively: adj.adv. affecting or relating to the best or most suitable people or things from a larger group选择的, 选择性的
- Ming always does his homework selectively, which annoys his teacher a great deal.
- The king selectively sentenced some murderers to death, which led to discontent of his officials.
- The lord selectively paid his debt under his reign.
agency [ˈeɪdʒənsi]: n. an organization or department, especially within a government, that does a specific job代理权
- Obviously, our king is old enough to exercise his agency.
- Failing to exercise his agency, the king gets obession with hunting.
- The queen and queen's mother are at war with each other for the youth king's agency. 
autonomy [ɔˈtɑnəmi]: n. the ability or opportunity to make your own decisions without being controlled by anyone else SYN independence自治
- While exercising his autonomy, the lord of Winterfall levied heavy taxes from his people.
- I asked my grandfather for the key of my room to exercise my autonomy.
- Our autonomy will never be exercised without the chains broken.
tolerate [ˈtɑləˌreɪt]: v. to be able to accept something unpleasant or difficult, even though you do not like it ⇨ tolerant, tolerance SYN stand, bear忍受, 容忍
- I can't tolerate those people who talk loudly in the theater.
- Discontent with his wife, he can't tolerate the marriage anymore even if they are raising three children.
- Discontent with the customer, he can't tolerate the boring work and request to quit at once.
decipher [dɪˈsaɪfər]: v. to find the meaning of something that is difficult to read or understand ⇨ indecipherable译解(密码等), 解释
- Being able to decipher the underlying meaning what people are expressing is a neccessary condition for a healthy relationship.
- Deciphering the meaning of the gesture, he stopped to hug his wife and kiss her face.
- Deciphering the meaning of the treasure map, a group of explorers took hearts and began to dig up the cave.
utterance [ˈʌt(ə)rəns]: n. something you say言论
- Angered by his wife's utterance, the king sentenced a servant of his wife to death to alarm her.
- Ignoring your father's public utterance, he always has to say what he disagree with as the lord of Winterfall.
- The son of the lord has been regarded as a useless person by his public utterance.
---------------------
throughout most of sb's life: 贯穿某人一生
- I am always worring about something that may happen or may not happen through most of my life.
- The leader of the party is organizing protests for human rights throughout most of his life.
- The expert from the zoo shares an apartment with a monkey throughout most of his life.
get divorced: 离婚
- She got the nerve to live by herself and requested to get divorced.
- Because of new law, we can't get divorced in three months.
- I got divorced everytime when I found I couldn't build a healthy relationship with my husband.
... rate rises: 某某率上升
- The rate of abortion in teenagers is obviously rising.
- Our sales rate is rising after our new CEO came to power.
- People parade to blame the authorities for the rising taxes rate.
tons of sth.: 大量的某物
- My dear, I am afraid that I couldn't take part in the fancy dress party, for I've got tons of work to do. 
- Because of the war you started, tons of people are gathering around the palace.
- In floods, tons of people in this country have to be served in soup lines.
put up with sth.: 忍受某事 
- The king couldn't put up with men served in a soup line and ordered his men to force them out.
- I couldn't put up with the marriage only with regard to politics.
- The employer can't put up with workers who stay up overnight.
speak from the position of sb.: 从某人的立场讲话
- In fact, the queen never speaks from the position of her people even though she is admired by these poor.
- If you didn't speak from the position of workers, you couldn't represent the underlying interests of our party.
- Why the politician began to speak from the position of empolyee remains a mystery.
labor rights and interests: 劳工权益
- Labor rights and interests never take grants in this slavery country.
- Speaking from the position of labor rights and interests, our leader is being attcked by those aristocrats.
- The authorities are taking interest in labor rights and interests.
come up with sth.=think up an idea for sth.: 想出某事
- He is supposed to come up with how to assassinate the daugther of former king as the hand of the king.
- The lawyer came up with a plan which could meet both our needs.
- The butcher's boy came up with a idea about how to practice swords.
** sentence2
elevator [ˈeləˌveɪtər]: n. a machine that takes people and goods from one level to another in a building SYN lift British English电梯, 升降机
- There are freaks in the elevator pissing off when nobody is there.
- My wife can't stand the smell of urine of dogs.
- After her dog pisses off in the elevator, he feels obliged to clean it up right away.
harm [hɑrm]: n. to physically hurt a person or animal伤害
- Your supremacy over me on a daily basis is always doing harm to me.
- You have done harm to me when you isolated me after we were divergent.
- He touched the slave's face to mean no harm to him.
selective [sɪˈlektɪv] selectively: adj.adv. affecting or relating to the best or most suitable people or things from a larger group选择的, 选择性的
- Ming always does his homework selectively, which annoys his teacher a great deal.
- The king selectively sentenced some murderers to death, which led to discontent among his officials.
- The lord selectively paid his debt under his reign.
agency [ˈeɪdʒənsi]: n. an organization or department, especially within a government, that does a specific job代理权
- Obviously, our king is old enough to exercise his agency.
- Failing to exercise his agency, the king gets obsessed with hunting.
- The queen and queen's mother are at war with each other for the youth king's agency. 
autonomy [ɔˈtɑnəmi]: n. the ability or opportunity to make your own decisions without being controlled by anyone else SYN independence自治
- While exercising his autonomy, the lord of Winterfall levied heavy taxes on his people.
- I asked my grandfather for the key to my room so I could exercise my autonomy.
- Our autonomy will never be exercised without the chains broken.
tolerate [ˈtɑləˌreɪt]: v. to be able to accept something unpleasant or difficult, even though you do not like it ⇨ tolerant, tolerance SYN stand, bear忍受, 容忍
- I can't tolerate those people who talk loudly in the theater.
- Discontent with his wife, he can't tolerate the marriage anymore even if they are raising three children.
- Discontent with the customer, he can't tolerate the boring work and requests to quit at once.
decipher [dɪˈsaɪfər]: v. to find the meaning of something that is difficult to read or understand ⇨ indecipherable译解(密码等), 解释
- Being able to decipher the underlying meaning of what people are expressing is a necessary condition for a healthy relationship.
- Deciphering the meaning of the gesture, he stopped to hug his wife and kiss her face.
- Deciphering the meaning of the treasure map, a group of explorers took hearts and began to dig up the cave.
utterance [ˈʌt(ə)rəns]: n. something you say言论
- Angered by his wife's utterance, the king sentenced a servant of his wife to death to alarm her.
- Ignoring your father's public utterance, he always has to say what he disagrees with as the lord of Winterfell.
- The son of the lord has been regarded as a useless person by his public utterance.
---------------------
throughout most of sb's life: 贯穿某人一生
- I am always worrying about something that may happen or may not happen throughout most of my life.
- The leader of the party has been organizing protests for human rights throughout most of his life.
- The expert from the zoo has shared an apartment with a monkey throughout most of his life.
get divorced: 离婚
- She got the nerve to live by herself and requested to get divorced.
- Because of the new law, we can't get divorced in three months.
- I got divorced when I found I couldn't build a healthy relationship with my husband.
... rate rises: 某某率上升
- The rate of abortion in teenagers is obviously rising.
- Our sales rate is rising after our new CEO came to power.
- People parade to blame the authorities for the rising tax rate.
tons of sth.: 大量的某物
- My dear, I am afraid that I can't take part in the fancy dress party, for I've got tons of work to do. 
- Because of the war you started, tons of people are gathering around the palace.
- In floods, tons of people in this country have to be served in soup lines.
put up with sth.: 忍受某事 
- The king couldn't put up with men served in a soup line and ordered his men to force them out.
- I couldn't put up with the marriage only with regard to politics.
- The employer can't put up with workers who stay up overnight.
speak from the position of sb.: 从某人的立场讲话
- In fact, the queen never speaks from the position of her people even though she is admired by the poor.
- If you didn't speak from the position of workers, you couldn't represent the underlying interests of our party.
- Why the politician began to speak from the position of an employee remains a mystery.
labor rights and interests: 劳工权益
- Labor rights and interests never take grants in this slaver country.
- Speaking from the position of labor rights and interests, our leader is being attacked by those aristocrats.
- The authorities are taking an interest in labor rights and interests.
come up with sth.=think up an idea for sth.: 想出某事
- He is supposed to come up with how to assassinate the daughter of the former king as the hand of the king.
- The lawyer came up with a plan which could meet both our needs.
- The butcher's boy came up with a idea about how to practice swords.
** summary
What's the underlying attitudes people have when they say things,
	and how does that affect interpersonal understanding of others?
People are not really only talking about facts.
For example, when people are talking to you in the elevator,
	it means they're your friends and you can feel safe.
Besides, how facts are presented and what facts are selected
	are also important ways for people to tell you something of value about themselves.
For example, when someone tells you that more and more people are getting divorced.
You wonder why this person is telling me this and what attitude he has.
There are different ways of using the same fact.
Like someone says that minimum wage is going to hurt the economy.
You can infer that he is speaking from the position of an employer, not an employee.
In all, the fact is usually selected with some purpose.
It is important to be able to decipher the position, and purpose of the talker.
** summary2
What are the underlying attitudes people have when they say things,
	and how does that affect interpersonal understanding of others?
People are not only talking about facts.
For example, when people are talking to you in the elevator,
	it means they're your friends so that you can feel safe.
Besides, how facts are presented and what facts are selected
	are also important ways for people to tell you something of value about themselves.
For example, when someone tells you that more and more people are getting divorced.
You wonder why this person is telling me this and what attitude he has.
There are different ways of using the same fact.
Like someone says that minimum wage is hurting the economy.
You can infer that he is speaking from the position of an employer, not an employee.
In all, facts are usually selected with some purpose.
It is important to be able to decipher the position, and purpose of the talker.
