#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.11 Attributions 2 - Multiple Contingencies Thinking
#+begin_verse
It sounds almost like a way of
	sort of simplifying the world or simplifying a situation for yourself to understand.
Well yeah, I think that is a good way to put it.
Most people actually are seeking simple attributions,
	but what we're advocating in the SSLD is that we introduce multiple contingencies thinking,
		meaning that we recognize that most human realities are more complicated
			than a simple one to one relationship.
So when a relationship breaks down, it's normally not just because of one reason.

It's usually because of multiple reasons but sometimes we make attributions simple because one,
	it takes time and energy to deal with more complicated attributions.
Two is that the kind of attributions people choose
	were actually more often related to their own needs.
I make attributions that will make me feel better.
I make attributions that's more consistent with my view of the world.

Say for example, if I am a xenophobic person,
	I really do not like to see these immigrants or people who are different in my neighbourhood.
So if anything goes wrong,
	I would just say, okay, this is because of these people who are different.
That's causing my discomfort.
And we find it all the time.
Say for example,
	if you see a black person doing something violent and you attribute it to their race.
But when we look at global statistics on violence,
	then we find, it is not really race, it is like ancient trend,
		young men are more likely to be violent than any other demographic combination.
But then in a context like North America we are more likely to be attributing it to,
	you know, ethno-racial characteristics which might be totally irrelevant in another context.
But that is, sort of a very common attribution that we make.

And of course, when people make this kind of attribution
	we sometimes we refer to that as an attribution error.
Yeah.
Right, because it's not accurate.
Of course.

In SSLD, we believe in multiple contingencies thinking
	meaning that the cause of something cannot be explained by just one simple attribution
		and there are usually many other underlying factors.
For example, there are actually multiple reasons of relationship failure
	rather than the simple attribution that we tend to make.
People make simple attribution,
	because it takes time and energy to deal with the more complicated ones,
		and we tend to make attributions that will make us feel better.
#+end_verse
** expression
simplify [ˈsɪmplɪˌfaɪ]: v. to make something easier or less complicated简单化
multiple [ˈmʌltɪp(ə)l]: adj. many, or involving many things, people, events etc多样的, 多重的
contingency [kənˈtɪndʒənsi]: n. possiblity 可能性
complicated [ˈkɑmplɪˌkeɪtəd]: adj. difficult to understand or deal with, because many parts or details are involved SYN complex复杂的
xenophobia [ˌzenəˈfoʊbiə] xenophobic: n.adj. strong fear or dislike of people from other countries仇外, 惧外者
combination [ˌkɑmbɪˈneɪʃ(ə)n]: n. two or more different things that exist together or are used or put together ⇨ combine结合, 联合
race [reɪs] racial: n.adj. relating to the relationships between different races of people who now live in the same country or area人种
--------------------
be related to sth./sb.: 与某人/某事有关
be consistent with sth./sb.: 与某人/某事一致
** sentence
simplify [ˈsɪmplɪˌfaɪ]: v. to make something easier or less complicated简单化
- We tend to simplify the cause of breakup of a relationship to understand it. 
- What invariably happens is to simplify the situation ignoring whether justice has been done.
- Let's me simpify what she puts, it serves him right.
multiple [ˈmʌltɪp(ə)l]: adj. many, or involving many things, people, events etc多样的, 多重的
- Our army is in the face of multiple crises, like lack of sustenance, weapons, and so on.
- When you faced multiple issues on emotions, you'd better focus on the most salient one at first.
- One piece of cake flying through the street caused multiple accidents this morning.
contingency [kənˈtɪndʒənsi]: n. possiblity 可能性
- The second contingency is that I take the throne and burn the city down.
- The salient contingency is that our soldiers lost their hearts because of rude commands.
- The obvious contingency is that his aunt provided him with 5 dollars to exchange for a big bar of chocolate.
complicated [ˈkɑmplɪˌkeɪtəd]: adj. difficult to understand or deal with, because many parts or details are involved SYN complex复杂的
- If you asked me how to study English, I would answer that it's complicated to be expert at a language.
- The coomplicated event led to the changing order of things in our capital. 
- The labyrinth is so complicated that we couldn't find our way to the castle for three days.
xenophobia [ˌzenəˈfoʊbiə] xenophobic: n.adj. strong fear or dislike of people from other countries仇外, 惧外者
- The diplomatic policy is supposed to diminish the xenophobia from our people.
- The xenophobia has already taken root in the boy who saw his family killed in a raid.
- It is hard to build a relationship with a xenophobic officer who started a war.
combination [ˌkɑmbɪˈneɪʃ(ə)n]: n. two or more different things that exist together or are used or put together ⇨ combine结合, 联合
- A combination of wisdom and hard work give rise to our prosperous motherland.
- A combination of opportunities and hard work rewarded him with a job working for Apple.
- A combination of talent and hard work will never be mistreated by fate.
race [reɪs] racial: n.adj. relating to the relationships between different races of people who now live in the same country or area人种
- The dustman who works for our company was accused of racial remarks in public.
- You needn't have mentioned racial advantages and disadvantages.
- You must make sense of your racial advantages in the context.
--------------------
be related to sth./sb.: 与某人/某事有关
- He can't be bothered to deal with what is not related to his job.
- Raising up three boys alone is related to a combination of love and brave.
- What you get used to eating is related to what you're brought up to eat.
be consistent with sth./sb.: 与某人/某事一致
- Consistent with our queen, I ride the dragon to the battle field.
- Consistent with the king in the North, the prince led his army to fight against these Asiatic nomads.
- Consistent with what we expected, the result of the experiment proved his theory to be true.
** sentence2
simplify [ˈsɪmplɪˌfaɪ]: v. to make something easier or less complicated简单化
- We tend to simplify the cause of the breakup of a relationship to understand it. 
- What invariably happens is to simplify the situation ignoring whether justice has been done.
- Let me simplify what she puts, it serves him right.
multiple [ˈmʌltɪp(ə)l]: adj. many, or involving many things, people, events etc多样的, 多重的
- Our army is in the face of multiple crises, like lack of sustenance, weapons, and so on.
- When you face multiple issues about emotions, you'd better focus on the most salient one at first.
- One piece of cake flying through the street caused multiple accidents this morning.
contingency [kənˈtɪndʒənsi]: n. possiblity 可能性
- The second contingency is that I take the throne and burn the city down.
- The salient contingency is that our soldiers lost their hearts because of rude commands.
- The obvious contingency is that his aunt provided him with 5 dollars to exchange for a big bar of chocolate.
complicated [ˈkɑmplɪˌkeɪtəd]: adj. difficult to understand or deal with, because many parts or details are involved SYN complex复杂的
- If you asked me how to study English, I would answer that it's complicated to be expert at a language.
- The complicated event led to the changing order of things in our capital. 
- The labyrinth is so complicated that we couldn't find our way to the castle for three days.
xenophobia [ˌzenəˈfoʊbiə] xenophobic: n.adj. strong fear or dislike of people from other countries仇外, 惧外者
- The diplomatic policy is supposed to diminish the xenophobia from our people.
- The xenophobia has already taken root in the boy who saw his family killed in a raid.
- It is hard to build a relationship with a xenophobic officer who started a war.
combination [ˌkɑmbɪˈneɪʃ(ə)n]: n. two or more different things that exist together or are used or put together ⇨ combine结合, 联合
- A combination of wisdom and hard work give rise to our prosperous motherland.
- A combination of opportunities and hard work rewarded him with a job working for Apple.
- A combination of talent and hard work will never be mistreated by fate.
race [reɪs] racial: n.adj. relating to the relationships between different races of people who now live in the same country or area人种
- The dustman who works for our company was accused of racial remarks in public.
- You needn't have mentioned racial advantages and disadvantages.
- You must make sense of your racial advantages in the context.
--------------------
be related to sth./sb.: 与某人/某事有关
- He can't be bothered to deal with the things that are not related to his job.
- Raising up three boys alone is related to a combination of love and bravery.
- What you get used to eating is related to what you're brought up to eat.
be consistent with sth./sb.: 与某人/某事一致
- Consistent with our queen, I ride the dragon to the battlefield.
- Consistent with the king in the North, the prince led his army to fight against these Asiatic nomads.
- Consistent with what we expected, the result of the experiment proved his theory to be true.
