#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-2 3.5 Reception - Ideas 2 - Position
#+begin_verse
It sounds like the importance is not just what the fact is telling us, or the fact itself.
But it's, why was that fact selected?
And what is the person's position on that particular fact?

Yeah, exactly.
So, especially when people are thinking of developing a more significant relationship,
	it is actually important to understand that.
Because some people, say for example,
	they start building relationship and then all of a sudden relates to the person involved.
It comes on suddenly,
	that, I've never thought that this person actually values his or her family so much.
To the extent that I added on piece to his or her life
	because to him or her the family is weigh more important than me or than this relationship.
	
And when people find themselves in this situation and then when they think back,
	actually maybe in the eight months they were dating,
		this message has been communicated to this person maybe 800 times, right?
Yeah.
But you just missed it, right?
So the person may be saying that like I have to do this because his family, right?
Or, I am not going to care what is going to happen, Thanksgiving? I'm back to Calgary.
So this is selective presentation, or framing of facts,
	and they do not listen between the lines and are missing out on the most important piece.
If someone is telling you that this Thanksgiving I have to go to New York or Calgary, or wherever.
It is not just a fact or that I am doing it.
It is also telling you this is important.
This is what is important in my life. 
#+end_verse
** expression
frame [freɪm]: v. formal to carefully plan the way you are going to ask a question, make a statement etc表达
--------------------
relate to sb.: 与某人建立联系/产生共鸣
add on piece to sb's life: 为某人生活增添色彩
think back: 回想
between the lines: 字里行间
miss out on sth.: 错过某事物
** sentence
frame [freɪm]: v. formal to carefully plan the way you are going to ask a question, make a statement etc表达
- In my youth, I was wondering how to frame a question to a teacher who gets angry.
- After quarreling bitterly, you are supposed to frame the fact with great care.
- My official has already framed the question about the scandal of corruption.
--------------------
relate to sb.: 与某人建立联系/产生共鸣
- When the lawyer tried to relate to his girlfriend, he found out that he was a little umfamiliar with her history.
- The prince has related to the lady of Winterfell overnight and got divorced with the princess.
- When you succeeded in relating to your wolf, he will follow no other than your instructions.
add on piece to sb's life: 为某人生活增添色彩
- To add on piece to her life, she is determined to go on vacations at different seaside resorts.
- Adding on piece to her life, she survived the operation after a servere car accident.
- This indeed added on piece to his life, for he spent a month on the desert island with bare hands.
think back: 回想
- You must think back what happened to you when you lost your keys ring.
- Don't be too hard on yourself, don't think back the man who hurt you.
- When he thought back, he found out that the old lady who is always so kind to everyone turns out to be the criminal.
between the lines: 字里行间
- The king kept flattering his uncle between the lines because his uncle used to threaten him.
- There must be some secrets between the lines of them.
- Between the lines of our abbot, we can infer that Jon Snow is not a bastard, but the true heir to the Iron Throne.
miss out on sth.: 错过某事物
- We will compensate you for your missing out on the birthday party.
- Missing out on the opportunity to work for Apple, the student broke up with his girl and left the city.
- Missing out on the opportunity to meet the Queen, the knight commited a murder in public and was standing trial.
** sentence2
frame [freɪm]: v. formal to carefully plan the way you are going to ask a question, make a statement etc表达
- In my youth, I wondered how to frame a question to a teacher who gets angry.
- After quarreling bitterly, you are supposed to frame the fact with great care.
- My official has already framed the question about the corruption scandal.
--------------------
relate to sb.: 与某人建立联系/产生共鸣
- When the lawyer tried to relate to his girlfriend, he realized to his horror that he was a little unfamiliar with her history.
- The prince has related to the lady of Winterfell overnight and got divorced from the princess.
- When you succeed in relating to your wolf, he will follow no other than your instructions.
add on piece to sb's life: 为某人生活增添色彩
- To add on piece to her life, she is determined to go on vacations at different seaside resorts.
- Adding on piece to her life, she survived the operation after a severe car accident.
- This indeed added on piece to his life, for he spent a month on the desert island with bare hands.
think back: 回想
- You must think back to what happened to you when you lost your key ring.
- Don't be too hard on yourself, don't think back to the man who hurt you.
- When he thinks back, he finds out that the old lady who is always so kind to everyone turns out to be a criminal.
between the lines: 字里行间
- The king kept flattering his uncle between the lines because his uncle used to threaten him.
- There must be some secrets between the lines of them.
- Between the lines of our abbot, we can infer that Jon Snow is not a bastard, but the true heir to the Iron Throne.
miss out on sth.: 错过某事物
- We will compensate you for your missing out on the birthday party.
- Missing out on the opportunity to work for Apple, the student broke up with his girl and left the city.
- Missing out on the opportunity to meet the Queen, the knight committed a murder in public and was standing trial.
** summary
Not only the importance is what the fact is tell us or itself,
	but also why was it selected and the person's position on the fact.
It is especially important when people are developing a significant relationship.
For example, it suddenly occur to someone
	that his partner values her family so much
		and he is weigh less important than her family.
However, when he thinks back he realizes that the message has been communicated to him many times.
He just missed it.
Like when his partner states that she is going to somewhere or do something because of her family.
It is not just a fact, it is also telling him her family is important in her life.
** summary2
Not only of importance is what the fact is telling us or itself,
	but also why is it selected and the person's position on the fact.
It is critical when people are developing a significant relationship.
For example, it suddenly occurs to someone
	that his partner values her family so much
		and he weighs less important than her family.
However, when he thinks back he realizes that the message has been communicated to him many times.
He just missed it.
Like when his partner states that she is going somewhere or doing something because of her family.
It is not just a fact, but it is also telling him her family is important in her life.
