#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 Conclusion
#+begin_verse
We have reached the end of session three.
In this session we've covered the two basic building blocks of relationships.
These are receptive skills and expressive skills.
Through these skills, we learned that, by being able to really understand and hear people,
	we will be able to understand their underlying needs.
In doing so, we can just develop more trusting and better relationships with others.
On the other hand, through expression,
	we learn that by being able to better express our facts, ideas, emotions, and needs,
		we can better reach our goals.
Now something that I found really interesting with learning all the things in Session Three
	was Attributional frames and how some people make sense of reality through these frames.
Most of us don't really even stop to think about it.
So I'll definitely be paying more attention to
		my own attributional frame and the attributional frames of other people in my life,
	and try to understand myself and others better through that.
The other thing that I really found interesting in this session
	was how heavily regulated our self-expression of our emotions is by society.
And how there are many emotions we don't express,
	and many emotions we suppress because of what society tells us.
And there are even cultural differences in how we express ourselves and how we understand others.
And this is also definitely something I'll be paying attention to in the future.
#+end_verse
