#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.20 Expression - Emotions 1 - Experience, Expression and Feedback
#+begin_verse
We've talked about expressing factual information
	and also expressing ideas and how to do it effectively.
Now coming up next is emotions,
	and I somehow feel that emotions aren't as easy to express effectively.
Yeah, because when we are doing course like this,
	we're making an assumption that we ourselves will challenge.
That is, we're making this assumption that's obviously not valid.
We assume that people will behave rationally.
And if you take a course like this on relationship,
	then you'll be following the principles, and the rules, and doing it in your real life.
I would say most people probably won't be able to do that.
When we are in the situation when we have to express or communicate emotions,
	well, the first things is that we become emotional.
When we become emotional,
	it almost doesn't really make sense for us to say
		that you should do this or you shouldn't do that.
So for us to really be in the position
	where we can feel better about ourselves, and be able to be who we are emotionally,
		and then express ourselves emotionally.
I wouldn't say that even in an appropriate way,
	but in a way that we feel comfortable with, a way that we like,
we have to recognize, the expression of emotion itself,
	it's not always and cannot be always rational [LAUGH].
Mm-hm.
That is the basic principle.

When we do that, the most important thing is,
	when we're expressing emotions, unlike expressing ideas or facts,
		we are not only trying to communicate something to the other person,
			we are also dealing with our internal state.
Usually when we express emotions,
	the very act of expressing emotion, itself, will change the emotion that we expressing.
Say for example, I'm expressing anger to you.
I have the opportunity to let all this anger out,
	and I find that you're not reacting with anger and aggression,
		but you're more accommodating and understanding.
Then I'll feel less angry, right?
But if I'm expressing jealousy
	and then you are telling me more things [LAUGH] about how wonderful your life is and all that.
[LAUGH] That will make me more jealous [LAUGH], right?
So the expression and feedback that we’ve got
	will immediately feed into the emotional experience that we have.
	
I think there are a couple of key concepts that we have in SSLD.
One of course, is a simple mechanism of emotional regulation
	which deals with the current emotion that we're experiencing.
And the other one we will call it emotional work,
	which is a more elaborate process
		in which we try to get understanding of our own emotional experience
			and deal with some of this difficult emotions that might even have a long history.
It can be childhood trauma.
It can be some unfinished emotional business or emotional baggages
	that we have been carrying in our life for a long period of time.
#+end_verse
** expression
valid [ˈvælɪd]: adj. a valid ticket, document, or agreement is legally or officially acceptable OPP invalid有效的
aggression [əˈɡreʃ(ə)n]: n. angry or threatening behaviour or feelings that often result in fighting进攻, 侵略
accommodate [əˈkɑməˌdeɪt]: v. to accept someone’s opinions and try to do what they want, especially when their opinions or needs are different from yours迎合,迁就
jealous [ˈdʒeləs] jealousy: adj.n. feeling unhappy because someone has something that you wish you had ⇨ envious嫉妒
mechanism [ˈmekəˌnɪzəm]: n. part of a machine or a set of parts that does a particular job机械装置,机制
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
trauma [ˈtrɔmə]: n. a mental state of extreme shock caused by a very frightening or unpleasant experience创伤
--------------------
make a assumption that + ...: 假设...
take a course (on sth.): 参加课程
It doesn't make sense for sb. to do sth.: 
feed into sth.: 流入/汇入某物
** sentence
valid [ˈvælɪd]: adj. a valid ticket, document, or agreement is legally or officially acceptable OPP invalid有效的
- The diplomatic policy proved valid, for countries in the neighborhood are trying to build relationships with us.
- This is a valid strategy to deal with the chaos in floods.
- He became fluent in English because the exercises Mr. Leo has asked are valid.
aggression [əˈɡreʃ(ə)n]: n. angry or threatening behaviour or feelings that often result in fighting进攻, 侵略
- No one can account for the fact that the cat, who had been very kind to everyone, reacted with aggression.
- What you have done on a daily basis will encourage aggression of our son.
- The stray dog is expression aggression to us because of some trauma he ran into after he had been abandoned.
accommodate [əˈkɑməˌdeɪt]: v. to accept someone’s opinions and try to do what they want, especially when their opinions or needs are different from yours迎合,迁就
- The actress who stayed out of limelight tried to accommodate an entrepreneur in the activity.
- I had to accommodate my cousin who shared his apartment with me.
- No one is willing to accommodate an entrepreneur who is put out of business.
jealous [ˈdʒeləs] jealousy: adj.n. feeling unhappy because someone has something that you wish you had ⇨ envious嫉妒
- Jealous of the queen, the mother of the king plotted to keep her in prison.
- Jealous of her cousin who has an affair with her husband, the queen asked the witch to murder her.
- I shall never be jealous of you, my best friend who has helped when I was trapped in debt.
mechanism [ˈmekəˌnɪzəm]: n. part of a machine or a set of parts that does a particular job机械装置,机制
- The specialist provided us a simple mechanism to regulate our emotions.
- The mechanism is designed to protect us against virus.
- When the mechanims of protecting against Asiatic nomads is not valid, we have to round up to defend ourself.
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
- The authorities were blamed for asking for too much budget to regulate the spread of epidemic.
- The authorities are always raising money to regulate epidemic.
- Obviously, officials fail to regulate the population in the town.
trauma [ˈtrɔmə]: n. a mental state of extreme shock caused by a very frightening or unpleasant experience创伤
- My childhood trauma causes me not to argue with people even if I am right.
- The trauma of refugees may accompany with them for the rest of their lives.
- The bog reacted with aggression because of the trauma in his youth.
--------------------
make an assumption that + ...: 假设...
- The policeman made an assumption that those people going camp in the park are actors and actresses.
- The detective made an assumption that there were a woman and her children who were robbed by a group of gangsters.
- My wife made an assumption that our cat had drunk her water.
take a course (on sth.): 参加课程
- Ignoring remarks her family made, she took a course on psychology with her friend.
- If I could have paid for the fee, I would have taken a course on driver with you in the university.
- After taking a course on relationships, he became an expert at making friends.
It doesn't make sense for sb. to do sth.: 
- It doesn't make sense for you to surf the internet outside home.
- It doesn't make sense for you to react with aggression.
- It doesn't make sense for me to have an affair with a women who is less charming than my wife.
feed into sth.: 流入/汇入某物
- All water from streams will feed into the river in the village
- As visitors fed into the scenic spot, it was too crowded to catch a sight of scenery.
- The snacks that fed into my bag inspired his jealousy.
** sentence2
valid [ˈvælɪd]: adj. a valid ticket, document, or agreement is legally or officially acceptable OPP invalid有效的
- The diplomatic policy proved valid, for countries in the neighborhood are trying to build relationships with us.
- This is a valid strategy for dealing with the chaos in floods.
- He became fluent in English because the exercises Mr. Leo asked were valid.
aggression [əˈɡreʃ(ə)n]: n. angry or threatening behaviour or feelings that often result in fighting进攻, 侵略
- No one can account for the fact that the cat, who had been very kind to everyone, reacted with aggression.
- What you have done on a daily basis will encourage aggression of our son.
- The stray dog is expressing aggression to us because of some trauma he ran into after he had been abandoned.
accommodate [əˈkɑməˌdeɪt]: v. to accept someone’s opinions and try to do what they want, especially when their opinions or needs are different from yours迎合,迁就
- The actress who stayed out of the limelight tried to accommodate an entrepreneur in the activity.
- I had to accommodate my cousin who shared his apartment with me.
- No one is willing to accommodate an entrepreneur who is put out of business.
jealous [ˈdʒeləs] jealousy: adj.n. feeling unhappy because someone has something that you wish you had ⇨ envious嫉妒
- Jealous of the queen, the mother of the king plotted to keep her in prison.
- Jealous of her cousin who had an affair with her husband, the queen asked the witch to murder her.
- I shall never be jealous of you, my best friend who has helped me when I was trapped in debt.
mechanism [ˈmekəˌnɪzəm]: n. part of a machine or a set of parts that does a particular job机械装置,机制
- The specialist provided us with a simple mechanism to regulate our emotions.
- The mechanism is designed to protect us against viruses.
- When the mechanisms of protecting against Asiatic nomads are not valid, we have to round up to defend ourselves.
regulate [ˈreɡjəˌleɪt]: v. to control an activity or process, especially by rules管制, 控制
- The authorities were blamed for asking for too much budget to regulate the spread of the epidemic.
- The authorities are always raising money to regulate the epidemic.
- Obviously, officials fail to regulate the population in the town.
trauma [ˈtrɔmə]: n. a mental state of extreme shock caused by a very frightening or unpleasant experience创伤
- My childhood trauma causes me not to argue with people even if I am right.
- The trauma of refugees may accompany them for the rest of their lives.
- The bog reacted with aggression because of the trauma in his youth.
--------------------
make an assumption that + ...: 假设...
- The policeman made an assumption that those people going camp in the park were actors and actresses.
- The detective made an assumption that there were a woman and her children who were robbed by a group of gangsters.
- My wife made an assumption that our cat had drunk her water.
take a course (on sth.): 参加课程
- Ignoring remarks her family made, she took a course on psychology with her friend.
- If I could have paid the fee, I would have taken a course on driving with you at the university.
- After taking a course on relationships, he became an expert at making friends.
It doesn't make sense for sb. to do sth.: 
- It doesn't make sense for you to surf the internet outside your home.
- It doesn't make sense for you to react with aggression.
- It doesn't make sense for me to have an affair with a woman who is less charming than my wife.
feed into sth.: 流入/汇入某物
- All water from streams will feed into the river in the village
- As visitors fed into the scenic spot, it was too crowded to catch sight of the scenery.
- The snacks that fed into my bag inspired his jealousy.
