#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.23 Expression - Needs
#+begin_verse
You've written in the book
	that expressing needs is so incredibly important
		because that's someone's way to get their needs met is by expressing them.
Mm-hm.
So what are some successful ways to express needs?

Well before we talk about successful ways or better ways to express needs,
	maybe we want to first think about why is it difficult to express needs?
Like emotions, right?
When you are emotional,
	it's difficult for you to figure out how am I going to express my emotions appropriately?
	
And understanding yourself is a condition for effective or appropriate expression.
With needs, there is this similar process here because when you have needs, then you're needy.
When you have needs that are not met
		and you're trying to get the other person to help you address your needs,
	very often it will make people feel inadequate.
Some people may feel vulnerable and that's why not everyone is comfortable expressing their needs.
And then the other thing is because when we're in the relationship,
		especially when you're in the relationship with a certain history
	and there are negative experiences in the past.
A lot of people do not want to express their needs
	because they're afraid of being disappointed, or frustrated.
In some extreme cases, some people were very afraid of expressing their needs
	because the expression of needs may lead to punishment, or aggression, or abuse.
So, some people will find it really difficult.
And they would rather hide their needs or conceal them,
	or express them in some other ways that are not explicit, that are not direct.
That is like the condition a lot of people may find themselves in.

Once you get to understand your needs, and you know you have to express them,
	then you will be able to learn a thing or two from the SSLD system.
The first thing of course,
		we have been repeating this many, many times, maybe too many times already in this course,
	is that you have to first distinguish between
		what is the thing that you want and what is the thing that you need.
Because what you want may not be what you need.
If you already know what you need,
	then you understand that there are usually multiple ways for that need to be addressed.
	
When you're expressing that need to someone,
	you want to express that in a way that the other person can understand.
Sometimes you want to express it in such a way that the other person can reasonably respond to.
Say for example, you're traveling and you're in a strange country,
	and then you are feeling sort of lost and also insecure.
And what you need would be a sense of safety and protection.
But you do not go around telling people,
	I'm really scared in this place, I'm feeling very insecure, and I want to feel protected.
Maybe you don't want to do that, right?
So what you might want to do is that you'll be looking for the next person,
	who might seem like a good company, who would not create more difficulty or challenge for you.
And then you would just go up to this person and start negotiating an initial relationship.
What you are actually looking for may be a sense of security and maybe some direction,
	but you may not be expressing that need right from the onset.
You will be showing some kind of affiliation needs or being friendly to people.
Or you may even be asking for some kind of help, like directions.
You may be like doing it in an incremental manner.
That is also a strategy that a lot of people adopt.

What we find
	is that when you have an important need, you do not necessarily always express it right away.
When we look at how beautiful dramas evolved in human relationships that we read in literature.
Very often these relationships go through a process.
And then it is the relationship
	that creates the opportunity for people to become more aware of their own needs.
It is not a linear process.
It is the same thing with emotion I would have to say.
When we talk about emotions, we probably didn't get into this too much.
We were talking about how to express emotions,
	actually one of the things that is great about relationships,
		is that if I am in a relationship
			that provides me with space where I can just freely express my emotions
				without being afraid of being judged, being attacked, that would be wonderful.
I would say the same thing about needs.
My relationship with that is a space, a trusting safe space for me to just express my needs.
It would be wonderful.
It is not just how we do it.
We want to be doing it nicely, doing it well.
But we also are looking forward to developing relationships
	that would open up the space for this kind of expression to happen more freely and spontaneously.
	
And I guess the more complex the need, or the more emotions involved,
	the better relationship you have have to be able to express it.
Very true.
And then we can also say the same thing about
	the more able you are to do that, it will help to build a relationship.
In a relationship when both parties can express their needs and their emotions freely,
	then I think, both parties are open and embracing and accepting.
Then, I think, the relationship would grow.
So, you're right.
And it will then start a virtuous cycle,
	things getting better, out of self-understanding, more effective communication,
		like expanding the shared space in the relationship.
That would be wonderful.
#+end_verse
** expression
needy [ˈnidi]: adj. needing and wanting a lot of love and attention需要关爱的
inadequate [ɪnˈædəkwət]: adj. someone who feels inadequate thinks other people are better, more skilful, more intelligent etc than they are不足的
frustrated [ˈfrʌˌstreɪtəd]: adj. feeling annoyed, upset, and impatient, because you cannot control or change a situation, or achieve something失望的
explicit [ɪkˈsplɪsɪt] explicitly: adj.adv. expressed in a way that is very clear and direct ⇨ implicit明白地, 明确地
insecure [ˌɪnsəˈkjʊr]: adj. not feeling at all confident about yourself, your abilities, or your relationships with people不安全的
scared [skerd]: adj. frightened of something, or nervous about something SYN afraid恐惧的
company [ˈkʌmpəni]: n. when you are with other people and not alone陪伴
affiliation [əˌfɪliˈeɪʃ(ə)n]: n. the connection or involvement that someone or something has with a political, religious etc organization附属,归属
adopt [əˈdɑpt]: v. to take someone else’s child into your home and legally become its parent采用
linear [ˈlɪniər]: adj. consisting of lines, or in the form of a straight line线性的
virtuous [ˈvɜrtʃuəs]: adj. formal behaving in a very honest and moral way OPP wicked良性的
cycle [ˈsaɪk(ə)l]: n. a number of related events that happen again and again in the same order ⇨ cyclic循环
--------------------
a condition for sth./doing sth.: 做某事的条件
be comfortable doing sth.: 舒适/乐于做某事
go up to sb.: 去找某人
from the onset: 从一开始
in an incremental manner: 以渐进的方式
** sentence
needy [ˈnidi]: adj. needing and wanting a lot of love and attention需要关爱的
- The stary dog is so needy that I can't leave him for a while.
- After earthquake, there are many needy children suffering from the disasters.
- She was so needy that she believed in a stranger who promised to take care of her.
inadequate [ɪnˈædəkwət]: adj. someone who feels inadequate thinks other people are better, more skilful, more intelligent etc than they are不足的
- The butcher's boy proved inadequate to become a knight.
- My pocket money is inadequate to pay the ticket for Taylor Swift's concert.
- With inadequate sustenance, our enemies began to lose their hearts.
frustrated [ˈfrʌˌstreɪtəd]: adj. feeling annoyed, upset, and impatient, because you cannot control or change a situation, or achieve something失望的
- His father felt frustrated as he hadn't pointed out the mistakes he made.
- When his boyfriend went to extermes to steal his money, he felt frustrated and went to police.
- Because the gift that his father presented with is not a puppy he inevitably felt frustrated.
explicit [ɪkˈsplɪsɪt] explicitly: adj.adv. expressed in a way that is very clear and direct ⇨ implicit明白地, 明确地
- Mr. Leo explicitly pointed out that the method he used to improve English is not effective.
- The policeman explicitly asked for money from a woman whose child had been abducted.
- I don't need to tell the nuance of the gestures explicitly, he can feel it on his own.
insecure [ˌɪnsəˈkjʊr]: adj. not feeling at all confident about yourself, your abilities, or your relationships with people不安全的
- Insecure about the party, she begged her boyfriend drove away from this house.
- Insecure about the throne, the princess was eager to start a civil war.
- You should be insecure about the game of the throne.
scared [skerd]: adj. frightened of something, or nervous about something SYN afraid恐惧的
- I was scared of the terror movie which my cousin introduced me.
- Apparently, your cat is scared of highup on the ladder.
- Consequent, you were scared of the ghost which Mr. Leo played by a blank sheet.
company [ˈkʌmpəni]: n. when you are with other people and not alone陪伴
- The cat is a good company with our child, as she has never bitten us even if we touch her closely.
- The tiger appeared to have been a good company with the boxer, however, everything changed with a piece of meat.
- The girl used to a good company with me since I went to high school.
affiliation [əˌfɪliˈeɪʃ(ə)n]: n. the connection or involvement that someone or something has with a political, religious etc organization附属,归属
- The hospital which has affiliation with the university is fruitful of eminent surgeons.
- Nowadays, people in China prefer hospitals which have affiliation with the universities.
- The journalist investigated a scandal about the hospital which has affiliation with the university.
adopt [əˈdɑpt]: v. to take someone else’s child into your home and legally become its parent采用
- The diplomatic policy our king adpot will benefit our trade across the sea.
- Our king shall never adopt a policy that disregards civil rights.
- Fear of invasion from the French, the plan of building a channel was not adopted back then.
linear [ˈlɪniər]: adj. consisting of lines, or in the form of a straight line线性的
- Student who feel comfortable with linear thinking have a difficult time solving this problem.
- The young wife is always blaming her husband for linear thinking.
- The car charged at him in a linear manner, scaring out of his wits. 
virtuous [ˈvɜrtʃuəs]: adj. formal behaving in a very honest and moral way OPP wicked良性的
- A virtuous waiter returned my lost money back to me.
- A virtuous noble will provide you with protection, as long as you pay for it on time. 
- The virtuous headmaster devoted himself to education, cultivating a great number of engineers and politicians.
cycle [ˈsaɪk(ə)l]: n. a number of related events that happen again and again in the same order ⇨ cyclic循环
- The aroused robot went to extremes to break the cycle of violence in the park.
- The politician has been regarded as a great leader who broke the cycle of violence for hundreds years in China.
- The death of their son broke the cycle of quarrel between the couple.
--------------------
a condition for sth./doing sth.: 做某事的条件
- Obviously, our house doesn't have a condition for manufacturing bulbs.
- The field is blessed with a condition for cultivating the new spiece of tomatoes.
- The cursed tree is a condition for attracting new visitors.
be comfortable doing sth.: 舒适/乐于做某事
- I am not comfortable making a speech in public.
- He is comfortable resolving conflicts between his superiors.
- My wife is comfortable going on a vacation at a seaside resort.
from the onset: 从一开始
- From the onset, you shouldn't have referred to me.
- From the onset, the general got obessed with the power.
- From the onset, he pretended to love his boyfriend.
go up to sb.: 去找某人
- Stop him, he must go up to the king.
- He is going up to his father, telling him the truth about the scandal.
- If you had gone up to me, you wouldn't have suffered so much in floods.
in an incremental manner: 以渐进的方式
- The firework display is supposed to display in an incremental manner.
- He read English academic books in an incremental manner.
- In my youth, I tended to use my pocket money in an incremental manner.
** sentence2
needy [ˈnidi]: adj. needing and wanting a lot of love and attention需要关爱的
- The stray dog is so needy that I can't leave him for a while.
- After the earthquake, many needy children were suffering from the disasters.
- She was so needy that she believed in a stranger who promised to take care of her.
inadequate [ɪnˈædəkwət]: adj. someone who feels inadequate thinks other people are better, more skillful, more intelligent etc than they are不足的
- The butcher's boy proved inadequate to become a knight.
- My pocket money is inadequate to pay for a ticket for Taylor Swift's concert.
- With inadequate sustenance, our enemies began to lose their hearts.
frustrated [ˈfrʌˌstreɪtəd]: adj. feeling annoyed, upset, and impatient, because you cannot control or change a situation, or achieve something失望的
- His father felt frustrated as he hadn't pointed out the mistakes he made.
- When his boyfriend went to extremes to steal his money, he felt frustrated and went to the police.
- Because the gift that his father presented with was not a puppy he inevitably felt frustrated.
explicit [ɪkˈsplɪsɪt] explicitly: adj.adv. expressed in a way that is very clear and direct ⇨ implicit明白地, 明确地
- Mr. Leo explicitly pointed out that the method he used to improve English was not effective.
- The policeman explicitly asked for money from a woman whose child had been abducted.
- I don't need to tell the nuance of the gestures explicitly, he can feel it on his own.
insecure [ˌɪnsəˈkjʊr]: adj. not feeling at all confident about yourself, your abilities, or your relationships with people不安全的
- Insecure about the party, she begged her boyfriend to drive away from this house.
- Insecure about the throne, the princess was eager to start a civil war.
- You should be insecure about the game of the throne.
scared [skerd]: adj. frightened of something, or nervous about something SYN afraid恐惧的
- I was scared of the horror movie that my cousin introduced me to.
- Apparently, your cat is scared of high up on the ladder.
- Consequently, you were scared of the ghost which Mr. Leo played by a blank sheet.
company [ˈkʌmpəni]: n. when you are with other people and not alone陪伴
- The cat is a good company with our child, as she has never bitten us even if we touch her closely.
- The tiger appeared to have been a good company with the boxer, however, everything changed with a piece of meat.
- The girl used to a good company with me since I went to high school.
affiliation [əˌfɪliˈeɪʃ(ə)n]: n. the connection or involvement that someone or something has with a political, religious etc organization附属,归属
- The hospital which has affiliation with the university is fruitful of eminent surgeons.
- Nowadays, people in China prefer hospitals that have affiliation with the universities.
- The journalist investigated a scandal about the hospital which has affiliation with the university.
adopt [əˈdɑpt]: v. to take someone else’s child into your home and legally become its parent采用
- The diplomatic policy our king adopts will benefit our trade across the sea.
- Our king shall never adopt a policy that disregards civil rights.
- Fear of invasion from the French, the plan of building a channel was not adopted back then.
linear [ˈlɪniər]: adj. consisting of lines, or in the form of a straight line线性的
- Students who feel comfortable with linear thinking have a difficult time solving this problem.
- The young wife is always blaming her husband for linear thinking.
- The car linearly charged at him, scaring him out of his wits. 
virtuous [ˈvɜrtʃuəs]: adj. formal behaving in a very honest and moral way OPP wicked良性的
- A virtuous waiter returned my lost money to me.
- A virtuous noble will provide you with protection, as long as you pay for it on time. 
- The virtuous headmaster devoted himself to education, cultivating a great number of engineers and politicians.
cycle [ˈsaɪk(ə)l]: n. a number of related events that happen again and again in the same order ⇨ cyclic循环
- The aroused robot went to extremes to break the cycle of violence in the park.
- The politician has been regarded as a great leader who broke the cycle of violence for hundreds of years in China.
- The death of their son broke the cycle of quarrels between the couple.
--------------------
a condition for sth./doing sth.: 做某事的条件
- Obviously, our house doesn't have a condition for manufacturing bulbs.
- The field is blessed with a condition for cultivating the new species of tomatoes.
- The cursed tree is a condition for attracting new visitors.
be comfortable doing sth.: 舒适/乐于做某事
- I am not comfortable making a speech in public.
- He is comfortable resolving conflicts between his superiors.
- My wife is comfortable going on a vacation at a seaside resort.
from the onset: 从一开始
- From the onset, you shouldn't have referred to me.
- From the onset, the general got obsessed with the power.
- From the onset, he pretended to love his boyfriend.
go up to sb.: 去找某人
- Stop him, he must go up to the king.
- He is going up to his father, telling him the truth about the scandal.
- If you had gone up to me, you wouldn't have suffered so much in floods.
in an incremental manner: 以渐进的方式
- The fireworks display is supposed to be displayed in an incremental manner.
- He read English academic books in an incremental manner.
- In my youth, I tended to use my pocket money in an incremental manner.
