#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.18 Expression - Ideas 2 - Technical Tips
#+begin_verse
In this negotiation between two people,
	I'm wondering if you have any technical tips or strategies for
		how to express one's idea effectively to the other person?
		
We have talked about focusing on the other person's needs,
	and that is primary, primary, most important.
Other than that, one of the things that we want to be paying attention to is,
	are we using language or metaphors or illustrations
		that are easily understood by the other party?
Because we all grow up and got educated in different context,
	and sometimes we think that what we have taken for granted to be understood or easy
		may not be what the other person's idea of the same thing.
And we sometimes use simple examples like spending time together.
And so, one person's idea of spending time together
	can be totally different than another person's idea of what is spending time together.
So clarifying what we want to, communication is important.
It is also important to understand
	what the familiar language or metaphors that the other person is using.
	
I very often use this analogy.
If you're in early childhood education,
	for example, you want to be explaining some very complex ideas to younger children.
You sort of break it down into smaller parts
	and then you use metaphors that the child can understand.
And sometimes we are not preoccupied with the technical accuracy of what you're conveying.
If you're trying to explain the concept of time [LAUGH] to a young child,
	or you're trying to deal with epistemological issues.
	
I can give you a wonderful example.
I was out in Sichuan helping with the disaster relief after the 2008 earthquake,
	and I was in high school.
And this high school headmaster actually taught an epistemology class.
Some people don't even understand the word epistemology, which refers to the theory of knowledge.
And I asked, how do you teach grade six students?
They have a very different system there.
He said that I went to the classroom with an apple, and then I ask my students, what is this?
And they all say apple, so and then I ask them, so what is an apple?
And then they will say fruit.
And then he will, at that point, take the apple and then throw it at another student.
And then, so the student will take the apple and catch it,
	and then he'll ask the student, throw it to someone else.
And after a few rounds, he'll be asking the class again, so what is an apple?

Right. What is the apple now?
So he's using that to convey an idea.
And trying to use it within the context.
Why people would have a different language and metaphor,
	but they were getting this idea that an apple is not always a fruit.
The apple can also be a toy.
Therefore, in this case, can function like a ball.
So, you know, that is an example of how we utilize different language,
	metaphors, and circumstantial reality to convey ideas in a creative way.
#+end_verse
** expression
technical [ˈteknɪk(ə)l]: adj. technical language is language that is difficult for most people to understand because it is connected with one particular subject or used in one particular job技术的, 技术上的
strategy [ˈstrætədʒi]: n. a planned series of actions for achieving something策略
metaphor [ˈmetəˌfɔr]: n. a way of describing something by referring to it as something different and suggesting that it has similar qualities to that thing ⇨ simile暗喻, 比喻
illustrate [ˈɪləˌstreɪt] illustration: v.n. the act or process of illustrating something说明,举例说明
clarify [ˈklerɪˌfaɪ]: v. formal to make something clearer or easier to understand ⇨ clarification澄清, 阐明
epistemology [ɪˌpɪstə'mɒlədʒi]: n. [哲]认识论
convey [kənˈveɪ]: v. to communicate or express something, with or without using words传达
function [ˈfʌŋkʃ(ə)n]: v. if something functions in a particular way, it works in that way作用
circumstantial [ˌsɜrkəmˈstænʃ(ə)l]: adj. based on something that appears to be true but is not proven间接的
--------------------
Other than that, + ...: 除那之外
get educated: 接受教育
in different context: 在不同背景下
take sth. for granted to be done/adj.: 认为某事理所应当被../是...
break sth. down into smaller parts: 分解某物成更小的部分
be preoccupied with sth.: 专注于某事
After a few rounds, + ...: 几个回合后, ...
** sentence
technical [ˈteknɪk(ə)l]: adj. technical language is language that is difficult for most people to understand because it is connected with one particular subject or used in one particular job技术的, 技术上的
- There are still some technical issues in this project, we have to delay in publishing it.
- Our manager put forward a plan existing some technical issues.
- I asked my uncle for some technical tips, but he hesitated to teach me a lesson.
strategy [ˈstrætədʒi]: n. a planned series of actions for achieving something策略
- The police planned out the strategy for dealing with crime in the town to the last detail. 
- Our essential strategy to pass the exam is by no other than learning knowledge.
- His strategy to overrun Winterfell proved to be effective.
metaphor [ˈmetəˌfɔr]: n. a way of describing something by referring to it as something different and suggesting that it has similar qualities to that thing ⇨ simile暗喻, 比喻
- What a brilliant metaphor that has clarified the contents of the story.
- The metaphor is designed to teach children who can't understand complex ideas directly.
- Mr. Leo took the matphor for granted to be understood by his students. Obviously, it's not the case.
illustrate [ˈɪləˌstreɪt] illustration: v.n. the act or process of illustrating something说明,举例说明
- Mr. Leo has a habit of illustrating ideas in his class when his students are comfused with them.
- The asterisk conducted him to a illustration in the next page.
- The combination of illustrations and experiments helps our student study in different dimensions.
clarify [ˈklerɪˌfaɪ]: v. formal to make something clearer or easier to understand ⇨ clarification澄清, 阐明
- The knight had to clarify the fact that the princess hadn't committed suicide because she was betrothed to a crippled.
- Consequently, our king failed to clarify whether this boy is his bastard or not.
- Realizing that he couldn't clarify the crime, he went abroad secretly.
convey [kənˈveɪ]: v. to communicate or express something, with or without using words传达
- What your wife was conveying yesterday may be the idea of going to a shopping mall.
- The message will be conveyed to King's Landing, five thousands miles away, in three days.
- The day before being betrothed to a mutilated lord, the princess sent her knights off to convery her love to the general.
function [ˈfʌŋkʃ(ə)n]: v. if something functions in a particular way, it works in that way作用
- The blanket now functions as my cat's nest in winter.
- The apple that functioned like a ball was being throwing between students.
- The mutilated coat hangers function as fuel in the fireplace.
circumstantial [ˌsɜrkəmˈstænʃ(ə)l]: adj. based on something that appears to be true but is not proven间接的
- He is naive enough to believe that circumstantial evidences can prove a lord's crime.
- Circumstantial evidences show us that the shape of molecule is a pyramid.
- Because of these circumstantial evidences, the elf will never give up hunting for Sauron.
--------------------
Other than that, + ...: 除那之外
- Other than that, Winterfell is the outermost city from the Seven Kingdom.
- Other than that, Sansa is not a virgin because she got married to the king, Renly.
- Other than that, like charges will try to minmize the repulsion between each other.
get educated: 接受教育
- He can't make friends with this immigrants who got educated in different culture.
- He has an idead of having his child get educated in the town.
- Getting educated abord in his youth, he can't get along with people around when he's home.
in different context: 在不同背景下
- A single word may have different meaning in different context.
- Although getting edcucated in different context, they both have a merciful heart.
- It's difficult to imagine that people in different context are bunched up together in the castle.
take sth. for granted to be done/adj.: 认为某事理所应当被../是...
- My wife is always taking a good job for granted to be found in the context.
- He takes her love for granted to be selfless.
- My cat seems to take her food for granted to be offered on time.
break sth. down into smaller parts: 分解某物成更小的部分
- Even if he broke his father precious clock down into smaller parts and it was broken, his father hadn't blamed him.
- The clock that was broken down into smaller parts can't be assembled together anymore.
- The boy has a habit of breaking his clock down into smaller parts on Saturday and assembling them together on the next day.
be preoccupied with sth.: 专注于某事
- Preoccupied with his work, he missed the meeting in which he was promoted as the new leader.
- Preoccupied with his homework, he didn't answer his mother's call.
- Preoccupied with the details, he can't form a complete picture of labyrinth.
After a few rounds, + ...: 几个回合后, ...
- After a few rounds, the knight was knocked to the ground.
- After a few rounds, my cat can't be bothered to go to bed.
- After a few rounds, the local grocer agreed to do me a favor.
** sentence2
technical [ˈteknɪk(ə)l]: adj. technical language is language that is difficult for most people to understand because it is connected with one particular subject or used in one particular job技术的, 技术上的
- There are still some technical issues in this project, so we have to delay publishing it.
- Our manager put forward a plan regarding some technical issues.
- I asked my uncle for some technical tips, but he hesitated to teach me a lesson.
strategy [ˈstrætədʒi]: n. a planned series of actions for achieving something策略
- The police planned out the strategy for dealing with crime in the town to the last detail. 
- Our essential strategy to pass the exam is no other than learning knowledge.
- His strategy to overrun Winterfell proved to be effective.
metaphor [ˈmetəˌfɔr]: n. a way of describing something by referring to it as something different and suggesting that it has similar qualities to that thing ⇨ simile暗喻, 比喻
- What a brilliant metaphor that has clarified the contents of the story.
- The metaphor is designed to teach children who can't understand complex ideas directly.
- Mr. Leo took the metaphor for granted to be understood. Obviously, it's not the case.
illustrate [ˈɪləˌstreɪt] illustration: v.n. the act or process of illustrating something说明,举例说明
- Mr. Leo has a habit of illustrating ideas in his class when his students are confused with them.
- The asterisk conducted him to an illustration on the next page.
- The combination of illustrations and experiments helps our students study in different dimensions.
clarify [ˈklerɪˌfaɪ]: v. formal to make something clearer or easier to understand ⇨ clarification澄清, 阐明
- The knight had to clarify the fact that the princess hadn't committed suicide because she was betrothed to a crippled.
- Consequently, our king failed to clarify whether this boy was his bastard or not.
- Realizing that he couldn't clarify the crime, he went abroad secretly.
convey [kənˈveɪ]: v. to communicate or express something, with or without using words传达
- What your wife was conveying yesterday may be the idea of going to a shopping mall.
- The message will be conveyed to King's Landing, five thousand miles away, in three days.
- The day before being betrothed to a mutilated lord, the princess sent her knights off to convey her love to the general.
function [ˈfʌŋkʃ(ə)n]: v. if something functions in a particular way, it works in that way作用
- The blanket now functions as my cat's nest in winter.
- The apple that functioned like a ball was being thrown between students.
- The mutilated coat hangers function as fuel in the fireplace.
circumstantial [ˌsɜrkəmˈstænʃ(ə)l]: adj. based on something that appears to be true but is not proven间接的
- He is naive enough to believe that circumstantial evidence can prove a lord's crime.
- Circumstantial evidence proved that the shape of the molecule is a pyramid.
- Because of this circumstantial evidence, the elf will never give up hunting for Sauron.
--------------------
Other than that, + ...: 除那之外
- Other than that, Winterfell is the outermost city of the Seven Kingdoms.
- Other than that, Sansa is not a virgin because she got married to the king, Renly.
- Other than that, like charges will try to minimize the repulsion between each other.
get educated: 接受教育
- He can't make friends with these immigrants who got educated in different cultures.
- He has an idea of having his child get educated in the town.
- Getting educated abroad in his youth, he can't get along with people around when he's home.
in a different context: 在不同背景下
- A single word may have different meanings in different contexts.
- Although getting educated in different contexts, they both have a merciful heart.
- It's difficult to imagine that people in different contexts are bunched up together in the castle.
take sth. for granted to be done/adj.: 认为某事理所应当被../是...
- My wife is always taking a good job for granted to be found in the context.
- He takes her love for granted to be selfless.
- My cat seems to take her food for granted to be offered on time.
break sth. down into smaller parts: 分解某物成更小的部分
- Even if he broke his father's precious clock down into smaller parts and it was broken, his father hadn't blamed him.
- The clock that was broken down into smaller parts can't be assembled together anymore.
- The boy has a habit of breaking his clock down into smaller parts on Saturday and assembling them together on the next day.
be preoccupied with sth.: 专注于某事
- Preoccupied with his work, he missed the meeting in which he was promoted as the new leader.
- Preoccupied with his homework, he didn't answer his mother's call.
- Preoccupied with the details, he can't form a complete picture of the labyrinth.
After a few rounds, + ...: 几个回合后, ...
- After a few rounds, the knight was knocked to the ground.
- After a few rounds, my cat can't be bothered to go to bed.
- After a few rounds, the local grocer agreed to do me a favor.
