#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 3-3 3.22 Expression - Emotions 3 - Emotional Work

Previously, you talked about emotional work.
The concept just seems so intriguing and interesting in terms of,
	would emotional work allow people to be better able to self-regulate their own emotions?
That's something definitely I want to learn more about.
Yeah, I'm glad that you're interested.
I may just say a couple things and then I'll let you figure this out more.
When we talk about emotional work,
	we're talking about a more extensive or elaborate process than emotional regulation.
Say for example, if I'm in a situation and then something triggers a certain emotion in me
	and I feel anxious or nervous or threatened or angry.
Then after a while, I was able to express that emotion,
	hopefully, not in an overly destructive manner, I return to a homeostatic state.
Then I have reasonably good emotion regulation.
But emotional work refers to a more extensive process.
Say for example,
	if I find that I'm chronically anxious or chronically depressed
			or whenever I come across, say for example, authority figures,
		I will become angry and aggressive.
Or whenever I'm in the company of someone that I am interested in erotically,
	I would freeze or I would have this immense tension that I'd stutter and couldn't speak.
Then I understand there might be a long-term problem that I have.
It's a pattern that might have been around for a while.
In order to work on it, to free myself from this pattern is what we mean by emotional work.
I'm happy that you're interested, so maybe you can explore this further.
Yeah, looking forward to it.
