#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-1 4.2 Value Reconsidered
#+begin_verse
Okay, so given the obvious limitations that Kahneman's prospect theory really sheds light on,
	what are some of the insights that SSLD can bring to the table?
I think the key question that we would raise is the whole idea of value.
In economics, you have like a set of standards to determine what value might be,
	like the market determines the value of a stock.
But then in interpersonal relationships, that doesn't really work that way.
One of the things that I always use as an example when I'm teaching my face-to-face class [LAUGH]
	is bringing gifts on Valentine's Day.
Let's suppose that you have a couple, they started dating and this is the first Valentine's Day.
The guy spent $100, bring some flowers and chocolate.
The woman was delighted
	and then she would be talking to her friends and showing it off to people at work or whatever.
So that gift carries a certain value,
	and the excitement generated is maybe extremely valuable to this person.
And then the guy would also feel very gratified
	when he gets feedback from the woman with regard to like how much she enjoyed receiving that gift.
So let us go like two, three, four years down the road, right?

Inflation and everything kicked in, maybe the guy, this time, spent $200 on similar gift.
And well, even with inflation,
	if you're spending $200, this would be a better looking bunch of flowers and chocolates.
But we're not sure
	that the value that is experienced by the woman
		would have gone up by almost 100%, right or 50%, or 30%.
I think there is a very good chance
	that the overall value would be less than the first time when it was experienced, right?
Even though they were only spending $100 back then.

So what the subjective experience of the value,
	or like some economists would call this utility, right?
Does not actually bear a simple relationship to the monetary market value of something.
So that actually would give us a lot of insight
	when we are looking at the arithmetic of love, so to speak, in any relationships.
	
Another important point that I want to emphasize, coming from a SSLD perspective,
	is that what is being valued varies from person to person.
Like someone who grows up with like privilege and easy access to material resources
	may not value material stuff that much.
But this person may, for instance, value autonomy because my parents are rich and powerful.
They're running my life and I'm well furnished with whatever I need,
	but I really would love to have more space for myself, right?
So that person would value this more.
But then, for someone who's like raised in a sort of a relatively deprived environment,
	then some of these material goods would carry more value for him or her.
You know, this is something that I always wished to have, but didn't, right?
So when we look at value, we have to pay attention to individuals.
And then the other thing that we always talk about, obviously,
	in SSLD is like because our needs do change, right?
So what we value actually would change as our needs change.
#+end_verse
** expression
prospect [prəˈspekt]: n. a particular event which will probably or definitely happen in the future – used especially when you want to talk about how you feel about it前景
insight [ˈɪnˌsaɪt]: n. the ability to understand and realize what people or situations are really like眼光
stock [stɒk]: n. a ↑share in a company股票
generate [ˈdʒenəˌreɪt]: v. to produce or cause something SYN create产生
gratify [ˈɡrætɪˌfaɪ]: v. to make someone feel pleased and satisfied满足
inflation [ɪnˈfleɪʃ(ə)n]: n. a continuing increase in prices, or the rate at which prices increase通货膨胀
overall [ˈoʊvərˌɔl]: adj. considering or including everything全部的, 全面的
monetary [ˈmʌnəˌteri]: adj. relating to money, especially all the money in a particular country货币的, 金融的
arithmetic [əˈrɪθmətɪk]: n. the science of numbers involving adding, multiplying etc算术, 算法
deprived [dɪˈpraɪvd]: adj. not having the things that are necessary for a comfortable or happy life贫穷的
--------------------
Given sth., + ...: 鉴于某事, + ...
shed light on sth.: 揭秘某事物
down the road: 在未来
kick in: 发生了
a bunch of flowers: 一串花
be furnished with sth.: 被供应某物/被配置某物

** sentence
prospect [prəˈspekt]: n. a particular event which will probably or definitely happen in the future – used especially when you want to talk about how you feel about it前景
- Because of the Prospect Theory, the professor was rewarded with the Nobel Prize.
- Many entreprenuers take advantage of the Prospect Theory to make big decisions about business.
- My wife is looking forward to the prospect of her shop in the Internet.
insight [ˈɪnˌsaɪt]: n. the ability to understand and realize what people or situations are really like眼光
- His insight of politics trend on the continent made him rise to fame swiftly.
- The king admired him for the general's insight of battlefield.
- His insight of learning English is very different from all who take the course.
stock [stɒk]: n. a ↑share in a company股票
- I have been assailed by a man who want to sell stocks to me.
- With two countries starting a war, the stocks of the company became worthless and it went bankrupt.
- My wife can't resist the temptation to buy the stocks from her classmate.
generate [ˈdʒenəˌreɪt]: v. to produce or cause something SYN create产生
- The code shall generate a series of random numbers as veritification code.
- The generated poop can be an ingredient in fertilizer and gunpowder.
- He suffered from the generated side effect by these pills.
gratify [ˈɡrætɪˌfaɪ]: v. to make someone feel pleased and satisfied满足
- When he took another angle to look at his son's grade, he got gratified.
- Customers usually get gratified because of the comprehensive service of the staff in the restaurant.
- A vacation at a seaside resort may gratify your wife.
inflation [ɪnˈfleɪʃ(ə)n]: n. a continuing increase in prices, or the rate at which prices increase通货膨胀
- The workers was underway to parade to protest against inflation.
- The inflation parallelled the war the vicious king started.
- I can't afford to real estate deby anymore because of the inflation.
overall [ˈoʊvərˌɔl]: adj. considering or including everything全部的, 全面的
- The overall value of the bridge is hard to be estimated.
- The overall score of the test means that I can't study abroad, which drives me mad.
- My overall score of the test is beyond the average score.
monetary [ˈmʌnəˌteri]: adj. relating to money, especially all the money in a particular country货币的, 金融的
- Before we move to London, maybe we can throw some objects of little monetary value away.
- She values some objects which is of little monetary in our eyes.
- I have to pay more to buy the real estate because of the new monetary policy.
arithmetic [əˈrɪθmətɪk]: n. the science of numbers involving adding, multiplying etc算术, 算法
- My aunt likes raising some questions about arithmetic. 
- The article on arithmetic inspired awe in an eminent scientist.
- I am afraid I am not so good at arithmetic as you think.
deprived [dɪˈpraɪvd]: adj. not having the things that are necessary for a comfortable or happy life贫穷的
- In China, children are difficult to go to university in deprived environments.
- Living in a deprived environment in his youth, he is very thrifty even though he is an entrepreneur now.
- Children in deprived environments still can't afford to go to university in this country.
--------------------
Given sth., + ...: 鉴于某事, + ...
- Given what you played truant from school yesterday, the headmaster will round up you to stand trial in front of all staff.
- Given the limitations of meeting the queen, we shall have a conversation before.
- Given the stage fright, you have two opportunities to speak in public.
shed light on sth.: 揭秘某事物
- The detective shed light on the criminal, who turned out to be the local grocer.
- The funeral shed light on the ghost at Endly farm, Frank who was supposed to be killed in action.
- The experts from the zoo shed light on the puma at large, which was in the possession of a private collector.
down the road: 在未来
- There is a certain hope that we can afford to a vacation at a seaside resort down the road.
- The inflation will be tackled by the new regime down the road.
- Almost everyone will lead a happy life down the road.
kick in: 发生了
- The monetary policy will kick in four years down the road.
- When an affair kicked in, she didn't choose to get divorced.
- A series of catastrophes kicked in in the suburb of the city.
a bunch of flowers: 一串花
- My wife was delight that I presented her with a bunch of flowers on Valentina's Day.
- The leader came to hospital to console him with a bunch of flowers.
- I caught sight of a bunch of flowers in your room.
be furnished with sth.: 被供应某物/被配置某物
- Furnished with whatever he wants, the prince has no mercy with his people.
- Furnished with a spear gun, two men on the desert island feasted on lobsters everyday.
- The ship that is furnished with 16 water-tight compartments was regarded as unsinkable.
** sentence2
prospect [prəˈspekt]: n. a particular event which will probably or definitely happen in the future – used especially when you want to talk about how you feel about it前景
- Because of the Prospect Theory, the professor was rewarded with the Nobel Prize.
- Many entrepreneurs take advantage of the prospect theory to make big decisions about businesses.
- My wife is looking forward to the prospect of her shop on the Internet.
insight [ˈɪnˌsaɪt]: n. the ability to understand and realize what people or situations are really like眼光
- His insight into political trends on the continent made him rise to fame swiftly.
- The king admired him for the general's insight of the battlefield.
- His insight into learning English is very different from that of all who take the course.
stock [stɒk]: n. a ↑share in a company股票
- I have been assailed by a man who wants to sell stocks to me.
- With two countries starting a war, the stocks of the company became worthless and it went bankrupt.
- My wife can't resist the temptation to buy the stocks from her classmate.
generate [ˈdʒenəˌreɪt]: v. to produce or cause something SYN create产生
- The code shall generate a series of random numbers as verification code.
- The generated poop can be an ingredient in fertilizer and gunpowder.
- He suffered from the generated side effects of these pills.
gratify [ˈɡrætɪˌfaɪ]: v. to make someone feel pleased and satisfied满足
- When he took another angle to look at his son's grade, he got gratified.
- Customers usually get gratified because of the comprehensive service of the staff in the restaurant.
- A vacation at a seaside resort may gratify your wife.
inflation [ɪnˈfleɪʃ(ə)n]: n. a continuing increase in prices, or the rate at which prices increase通货膨胀
- The workers were underway to parade to protest against inflation.
- The inflation parallelled the war the vicious king started.
- I can't afford real estate debt anymore because of the inflation.
overall [ˈoʊvərˌɔl]: adj. considering or including everything全部的, 全面的
- The overall value of the bridge is hard to estimate.
- The overall score on the test means that I can't study abroad, which drives me mad.
- My overall score on the test is beyond the average score.
monetary [ˈmʌnəˌteri]: adj. relating to money, especially all the money in a particular country货币的, 金融的
- Before we move to London, maybe we can throw some objects of little monetary value away.
- She values some objects of little monetary in our opinions.
- I have to pay more to buy real estate because of the new monetary policy.
arithmetic [əˈrɪθmətɪk]: n. the science of numbers involving adding, multiplying etc算术, 算法
- My aunt likes raising some questions about arithmetic. 
- The article on arithmetic inspired awe in an eminent scientist.
- I am afraid I am not as good at arithmetic as you think.
deprived [dɪˈpraɪvd]: adj. not having the things that are necessary for a comfortable or happy life贫穷的
- In China, children in deprived environments find it difficult to go to university.
- Living in a deprived environment in his youth, he is very thrifty even though he is an entrepreneur now.
- Children in deprived environments still can't afford to go to university in this country.
--------------------
Given sth., + ...: 鉴于某事, + ...
- Given that you played truant from school yesterday, the headmaster will round up you to stand trial in front of all staff.
- Given the limitations of meeting the queen, we shall have a conversation before.
- Given your stage fright, you have another chance to speak in public.
shed light on sth.: 揭秘某事物
- The detective shed light on the criminal, who turned out to be the local grocer.
- The funeral shed light on the ghost at Endly farm, Frank who was supposed to be killed in action.
- The experts from the zoo shed light on the puma at large, which was in the possession of a private collector.
down the road: 在未来
- There is a certain hope that we can afford a vacation at a seaside resort down the road.
- The inflation will be tackled by the new regime down the road.
- Almost everyone will lead a happy life down the road.
kick in: 发生了
- The monetary policy will kick in four years down the road.
- When an affair kicked in, she didn't choose to get divorced.
- A series of catastrophes kicked in in the suburbs of the city.
a bunch of flowers: 一串花
- My wife was delighted that I presented her with a bunch of flowers on Valentine's Day.
- The leader came to the hospital to console him with a bunch of flowers.
- I caught sight of a bunch of flowers in your room.
be furnished with sth.: 被供应某物/被配置某物
- Furnished with whatever he wants, the prince has no mercy on his people.
- Furnished with a spear gun, two men on the desert island feasted on lobsters every day.
- The ship that is furnished with 16 water-tight compartments was regarded as unsinkable.
