#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-1 4.1 Social Exchange Theory and Beyond
#+begin_verse
So a really predominant theory for understanding relationships, actually since the 1950s,
	has been George Homans' Social Exchange Theory.
So basically this theory posits that human beings are rational creatures.
We're only in relationships if the pros outweigh the cons.
Essentially we do a cost benefit analysis and decide to ourselves.
Does this relationship satisfy my needs?
And I'm getting enough out of it?
Or if I'm not getting enough out of it, then I'm leaving the relationship.
So, Professor Tsang, does that theory really comprehensively explain relationships?

Well, first of all, I have to say that like we probably still do not have a theory
	that comprehensively explains relationships.
[LAUGH] Maybe not even SSLD.
We're all trying to get different aspects of relationships better understood.
But getting back to social exchange theory, I think you're right,
	like there are formulas that are using to help us understand what is happening.
And you're right in pointing out that you're making the assumption
	that human beings are behaving rationally in a very logical, calculating manner.
	
I just want to point out there are actually two formulas that are relevant here.
The first one, obviously is weighing the cost benefit,
	like putting in so much and not getting enough.
But very often when people get into relationship,
	they will also taking another angle to look at the so-called exchange.
It's like how much have you put in and how much have I put in?
Maybe I have put in not a lot and getting a lot out of that.
But if I am sitting there looking at you and find that you are not putting in as much,
	the person may still feel dissatisfied because they're saying, oh that's not fair.
So there are actually two sets of calculations that are supposedly going on.

But as you have already pointed out, that has to assume that human beings are really rational.
And I think we have all the reasons to believe that human beings actually aren't that rational.
Interestingly, in year 2000, a Nobel Prize in economics was awarded to a psychologist or someone
	who did the experimental social psychology research.
Daniel Kahneman put forward the Prospect Theory and that won him the Nobel Prize back in 2002.
So what he actually is trying to point out,
	it's that like human beings actually rarely behave totally rationally.
And he has decades of experimental findings to back up this claim.
So this is also the same assumption made by a communist for a long time.
That people they do things to maximize utility
	so they do those cost benefit analysis
		and make sure that I'm gaining the maximum possible out of any deal.
		
But I think we now have a fair bit of evidence to show that like people do not really do that.
So instead of looking at exchange,
	we may want to be understanding why people continue doing what they're doing.
And then when we are in social services,
	for example, we find a lot of people sticking around in abusive relationships.
Relationships that actually undermines their sense of self-worth.
Relationships that are outright damaging, destructive,
	and people seem to stick around for a long time, right?
So we really need to understand relationships
	beyond just looking at this like simple, rational exchange formula.
And we have to be careful when we say that as well,
	because we do not want to give people this simple black, white, either, or.
I'm not saying that the social exchange dimension is totally irrelevant.
I'm saying that it may explain a certain percentage of variance.
Some aspects of the relationship might be explainable with like social exchange formulation
	but relationships are obviously more complicated than that.
#+end_verse
** expression
predominant [prɪˈdɑmɪnənt]: adj. more powerful, more common, or more easily noticed than others支配的
outweigh [aʊtˈweɪ]: v. to be more important or valuable than something else在重量(或价值等)上超过
comprehensive [ˌkɑmprəˈhensɪv] comprehensively: adj.adv. including all the necessary facts, details, or problems that need to be dealt with SYN thorough全面的
formula [ˈfɔrmjələ]: n. a series of numbers or letters that represent a mathematical or scientific rule式子
relevant [ˈreləvənt]: adj. directly relating to the subject or problem being discussed or considered OPP irrelevant相关的
supposedly [səˈpoʊzədli]: adv. used when saying what many people say or believe is true, especially when you disagree with them想像上, 按照推测
communist ['kɑmjənɪst]: n. someone who is a member of a political party that supports communism, or who believes in communism ⇨ capitalist, socialist共产主义者
undermine [ˌʌndərˈmaɪn]: v. to gradually make someone or something less strong or effective削弱
outright [ˈaʊtˌraɪt]: adv. complete and total彻底的, 完全的
variance [ˈveriəns]: n. the amount by which two or more things are different or by which they change 〔数量的〕差异,变化幅度
--------------------
sb. posits that + ...: 某人假定+...
pros and cons: 优点和缺点
put in: 投入
sb is right in doing sth.: ,某人在做某事是对的
take another angle to look at sth.: 换一个角度去看待某事
have all the reasons to believe that + ...: 完全有理由去相信 + ...
back up sth.: 支持某物
stick around: 逗留,停留
** sentence
predominant [prɪˈdɑmɪnənt]: adj. more powerful, more common, or more easily noticed than others支配的
- The predominant power on the continent shall be the French government now.
- The company was fined a million dollars for its predominant position in the market.
- Obviously, he is predominant in the relationship with his wife.
outweigh [aʊtˈweɪ]: v. to be more important or valuable than something else在重量(或价值等)上超过
- You shall be in possesion of the dog before it outweighs 50 kilogram.
- You are right in finding yourselve outweigh 50 kilogram. 
- Maybe the fish your father caught yesterday outweigh all caught in the town last year.
comprehensive [ˌkɑmprəˈhensɪv] comprehensively: adj.adv. including all the necessary facts, details, or problems that need to be dealt with SYN thorough全面的
- It seemed as if our police comprehensively had gone through our house.
- The patient will be comprehensively examined in the hospital.
- Our community will be comprehesively got rid of rats because of these pills.
formula [ˈfɔrmjələ]: n. a series of numbers or letters that represent a mathematical or scientific rule式子
- Not acquinted with the knowledge, you can't remeber the formula when you are taking an exam.
- This formula is related with a model of relationship.
- The scientist utilized the formula to design a machine which was used to clear up houses.
relevant [ˈreləvənt]: adj. directly relating to the subject or problem being discussed or considered OPP irrelevant相关的
- All evidence you provided me is not relevant, it doesn't make sense.
- Because of the lack of relevant evidence, the boy steped out of the cell.
- The conversation you had with your son may lead to a relevant fallacy.
supposedly [səˈpoʊzədli]: adv. used when saying what many people say or believe is true, especially when you disagree with them想像上, 按照推测
- How can a supposedly kind actress be so mean to the staff in the spot?
- The supposedly kind old lady has a skeleton in the cupboard that she poisoned an opponent of her son.
- The supposedly adorable bird has a habit of feasting on maggots.
communist ['kɑmjənɪst]: n. someone who is a member of a political party that supports communism, or who believes in communism ⇨ capitalist, socialist共产主义者
- The scientist who put forward a plan about nuclear weapon was being accused of being a communist.
- I never dream of being a communist working for our people.
- The communist devoted himself to the constrution work in his country.
undermine [ˌʌndərˈmaɪn]: v. to gradually make someone or something less strong or effective削弱
- It is your mercy that undermines the power of the garrison.
- Well, the hairstyle may have undermined your beauty.
- Talking aloud in public must have undermined the beauty of the lady in your heart.
outright [ˈaʊtˌraɪt]: adv. complete and total彻底的, 完全的
- The spokesman claimed that Taiwan is outright part and parcel of China mainland.
- When the workers got outright angry, they broke into the armory and burned down it.
- The patient outright lost his minds and killed his three kids in the fire.
variance [ˈveriəns]: n. the amount by which two or more things are different or by which they change 〔数量的〕差异,变化幅度
- The factory can't bear a price variance of 5%.
- A price variance of 5% of the apartment led to the quarrel between the couple.
- The vicar pointed out that a price variance of 5% is key point.
--------------------
sb. posits that + ...: 某人假定+...
- Mr. Leo posits that we are grown-ups when we take the course.
- Let's posits that there are a child in front of you.
- The teacher posits that his wife has an affair with her classmate.
pros and cons: 优点和缺点
- The boy made a list of pros and cons of losing weight.
- When pros outweighs cons, we should change our minds.
- Trying to figure out the pros of cons of building the bridge, the engineer has been investgating for three weeks.
put in: 投入
- My wife is always complaining that she has put in too much in our relationship.
- What I put in in family has already outweighed what you do.
- What I put in is rewarded with your abuse.
sb is right in doing sth.: ,某人在做某事是对的
- Mr. Leo is right in pointing out that the cursed tree is a source of income.
- The workers are right in overunning the armory.
- Our soldiers are right in burning down the sustanance of our enemy.
take another angle to look at sth.: 换一个角度去看待某事
- She took another angle to look at the issues the student raised.
- The abbot took another angle to look at the debt and though it his duty to get monastery free from debt problems.
- Taking another angle to look at your needs, you will find a differnt way to get it met.
have all the reasons to believe that + ...: 完全有理由去相信 + ...
- Our mother has all the reasons to believe that we have stayed overnight playing video games.
- She has all the reasons to believe that the monastery is still under heavy debt.
- I have all the reasons to believe that we can pay the debt for the rest of life.
back up sth.: 支持某物
- There is no relevant evidence backing up your conclusion in the scene.
- The results of experiments back up the theory the scientist published.
- The formula backed up your result of caculation.
stick around: 逗留,停留
- It's outright not worth sticking around in the relationship.
- The girl sticked around in the relationship with a bullier and got pregnant.
- The lady has sticked around in the mall for two hours.
** sentence2
predominant [prɪˈdɑmɪnənt]: adj. more powerful, more common, or more easily noticed than others支配的
- The predominant power on the continent now shall be the French government.
- The company was fined a million dollars for its predominant position in the market.
- Obviously, he is predominant in the relationship with his wife.
outweigh [aʊtˈweɪ]: v. to be more important or valuable than something else在重量(或价值等)上超过
- You shall be in possession of the dog before it outweighs 50 kilograms.
- You are right in finding that she outweighs 50 kilograms. 
- Maybe the fish your father caught yesterday outweighs all the fish caught in town last year.
comprehensive [ˌkɑmprəˈhensɪv] comprehensively: adj.adv. including all the necessary facts, details, or problems that need to be dealt with SYN thorough全面的
- It seemed as if our police comprehensively had gone through our house.
- The patient will be comprehensively examined in the hospital.
- Our community will be comprehensively got rid of rats because of these pills.
formula [ˈfɔrmjələ]: n. a series of numbers or letters that represent a mathematical or scientific rule式子
- Not acquainted with the knowledge, you can't remember the formula when you are taking an exam.
- This formula is related to a model of relationship.
- The scientist utilized the formula to design a machine that was used to clear up houses.
relevant [ˈreləvənt]: adj. directly relating to the subject or problem being discussed or considered OPP irrelevant相关的
- All evidence you provided me is not relevant, it doesn't make sense.
- Because of the lack of relevant evidence, the boy stepped out of the cell.
- The conversation you had with your son may lead to a relevant fallacy.
supposedly [səˈpoʊzədli]: adv. used when saying what many people say or believe is true, especially when you disagree with them想像上, 按照推测
- How can a supposedly kind actress be so mean to the staff in the spot?
- The supposedly kind old lady has a skeleton in the cupboard that she poisoned an opponent of her son.
- The supposedly adorable bird has a habit of feasting on maggots.
communist ['kɑmjənɪst]: n. someone who is a member of a political party that supports communism, or who believes in communism ⇨ capitalist, socialist共产主义者
- The scientist who put forward a plan about nuclear weapons was being accused of being a communist.
- I never dream of being a communist working for our people.
- The communist devoted himself to the construction work in his country.
undermine [ˌʌndərˈmaɪn]: v. to gradually make someone or something less strong or effective削弱
- It is your mercy that undermines the power of the garrison.
- Well, the hairstyle may have undermined your beauty.
- Talking aloud in public must have undermined the beauty of the lady in your heart.
outright [ˈaʊtˌraɪt]: adv. complete and total彻底的, 完全的
- The spokesman claimed that Taiwan is outright part and parcel of China mainland.
- When the workers got outright angry, they broke into the armory and burned down it.
- The patient outright lost his mind and killed his three kids in the fire.
variance [ˈveriəns]: n. the amount by which two or more things are different or by which they change 〔数量的〕差异,变化幅度
- The factory can't bear a price variance of 5%.
- A price variance of 5% of the apartment led to the quarrel between the couple.
- The vicar pointed out that a price variance of 5% is the key point.
--------------------
sb. posits that + ...: 某人假定+...
- Mr. Leo posits that we are grown-ups when we take the course.
- Let's posit that there is a child in front of you.
- The teacher posits that his wife has an affair with her classmate.
pros and cons: 优点和缺点
- The boy made a list of pros and cons of losing weight.
- When the pros outweigh the cons, we should change our minds.
- Trying to figure out the pros of cons of building the bridge, the engineer has been investigating for three weeks.
put in: 投入
- My wife is always complaining that she has put in too much.
- What I put in in family has already outweighed what you do.
- What I put in is rewarded with your abuse.
sb is right in doing sth.: 某人在做某事是对的
- Mr. Leo is right in pointing out that the cursed tree is a source of income.
- The workers are right in overrunning the armory.
- Our soldiers are right in burning down the sustenance of our enemy.
take another angle to look at sth.: 换一个角度去看待某事
- She took another angle to look at the issues the student raised.
- The abbot took another angle to look at the debt and thought it his duty to get the monastery free from debt problems.
- Taking another angle to look at your needs, you will find a different way to get it met.
have all the reasons to believe that + ...: 完全有理由去相信 + ...
- Our mother has all the reasons to believe that we have stayed overnight playing video games.
- She has all the reasons to believe that the monastery is still under heavy debt.
- I have all the reasons to believe that we can pay the debt for the rest of life.
back up sth.: 支持某物
- There is no relevant evidence backing up your conclusion in the scene.
- The results of experiments back up the theory the scientist published.
- The formula backed up your result of the calculation.
stick around: 逗留,停留
- It's outright not worth sticking around in the relationship.
- The girl stuck around in the relationship with a bullier and got pregnant.
- The lady has stuck around in the mall for two hours.
