#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-1 4.5 Power, Balance and Giving
#+begin_verse
Okay, so relationships are complex
	and the whole idea of one person intrinsically having more power than the other.
You're ultimately saying that's not a given.
So with this in mind,
	is there a way for a relationship to be totally equitable and reciprocal in terms of power?
I have to be very careful here,
	like if I say that we don't have to be like always fair
		and relationships do not have to be equitable,
	I can probably get myself into deep trouble, right?
[LAUGH] So I have to be very careful here.
Well obviously, we do not want to see any relationship turning into something that is oppressive.
That is exploitative.
That is grossly unfair for one or both of the participants.
But having said that, we have to understand
	that like the whole concept of fairness and equity probably
		needs some kind of like careful, critical re-thinking.
		
You know, in the relationship, like very often, ideal relationships would have this element of love.
And this element of love, according to my own understanding,
	can very often entail one party making certain sacrifices, so to speak.
Imagine like a mother waking up like 3 AM in the morning to a crying baby, all right?
Then, the mother will, obviously, be forgoing some of her own needs, like the need for rest,
	like may have something important to deal with in the morning or whatever.
But then in an ideal situation, the mother will actually feel good after pacifying a baby.
And then, the baby is not crying again and she then goes back to sleep.
So in this particular act, the mother gives and the baby receives.
But then maybe the mother derives a bigger sense of satisfaction than the baby,
	we don't know, all right?
I cannot be sure.
But that's just how it may work.
And then when we look at any like ideal loving relationship.
That's what we hope will happen.

And people are not calculating like I've given this much and you have not.
Like put in your fair share.
And I've done so much for you and you don't really care for me.
We hear that a lot when couples are fighting and to me,
	when people start operating in this mode, something is already missing in the relationship.
But of course, I'm also aware
	that there are like people who are involved in relationships that are abusive,
		that are exploitative.
Like one person is always expected to give, to the extent that the person is damaged.
That person's personal space and freedom and autonomy are all compromised.
And there is like one person who is constantly demanding for his or her needs to be met.
That, of course, is problematic as well, right?

But I think in an ideal relationship, people should be fully autonomous,
	and they actually should be able to derive pleasure and satisfaction through the act of giving.
And if you for some reason are not able to do that,
	or you're not	either when you're giving, not because you want to but you're made to
		or you do not experience fulfillment from your giving.
Then, I think it is probably time for you to be re-examining the relationship.
#+end_verse
** expression
intrinsic [ɪnˈtrɪnsɪk] intrinsically: adj.adv. being part of the nature or character of someone or something OPP extrinsic固有的, 内在的, 本质的
given [ˈɡɪv(ə)n]: n. a basic fact that you accept as being true固有事实
equity [ˈekwəti] equitable: n.adj. n.adj. treating all people in a fair and equal way OPP inequitable公平的
reciprocal [rɪˈsɪprək(ə)l]: adj. a reciprocal arrangement or relationship is one in which two people or groups do or give the same things to each other ⇨ mutual互惠的
oppressive [əˈpresɪv]: adj. powerful, cruel, and unfair压迫的
exploit [ɪkˈsplɔɪt] exploitative: v.adj. to treat someone unfairly by asking them to do things for you, but giving them very little in return – used to show disapproval剥削
gross [ɡroʊs] grossly: adj.adv. clearly wrong and unacceptable过分的
forgo [fɔrˈɡoʊ]: v. to not do or have something pleasant or enjoyable SYN go without放弃
pacify [ˈpæsɪˌfaɪ]: v. to make someone calm, quiet, and satisfied after they have been angry or upset安抚
derive [dɪˈraɪv]: v. to get something, especially an advantage or a pleasant feeling, from something得到
compromise [ˈkɑmprəˌmaɪz]: v. to reach an agreement in which everyone involved accepts less than what they wanted at first妥协
problematic [ˌprɑbləˈmætɪk]: adj. involving problems and difficult to deal with有问题的
autonomous [ɔˈtɑnəməs]: adj. an autonomous place or organization is free to govern or control itself SYN independent自治的
--------------------
with sth. in mind: 考虑到某事
in sb's fair share: 在某人的公平份额
in this mode: 在这种模式下
** sentence
intrinsic [ɪnˈtrɪnsɪk] intrinsically: adj.adv. being part of the nature or character of someone or something OPP extrinsic固有的, 内在的, 本质的
- The love from the dying lion was so intrinsic that even the hunter was unwilling to kill her infant.
- It is the intrinsic interest of the story that people admire for, not you.
- I have been studying English for two years, enjoying the intrinsic interest of English stories.
given [ˈɡɪv(ə)n]: n. a basic fact that you accept as being true固有事实
- Living in poverity in his youth is not a given.
- The detective found out that what she told was not a given, she made it.
- These days, people regard women receiving more priorities in public as a given.
equity [ˈekwəti] equitable: n.adj. n.adj. treating all people in a fair and equal way OPP inequitable公平的
- When you presented a gift to your nephew and not to you niece, it was obviously equitable.
- It was equitable that my sister received a warmer welcome at grandmother's home.
- The parents go out of their ways to provide equitable conditions with the twin brothers.
reciprocal [rɪˈsɪprək(ə)l]: adj. a reciprocal arrangement or relationship is one in which two people or groups do or give the same things to each other ⇨ mutual互惠的
- I have benefited from reciprocal ideas which my father taught me in my youth.
- The workers were due to go on a strike so that they could reach reciprocal agreements with entrepreneurs.
- I had no idea why you treated a reciprocal agreement as oppressive.
oppressive [əˈpresɪv]: adj. powerful, cruel, and unfair压迫的
- The vicious king drew up a set of oppressive laws, which inspired rebellions.
- She was in an oppressive relationship in high school, which got her into serious trouble.
- On coming to power, the prime minister prohibited a series of oppressive laws.
exploit [ɪkˈsplɔɪt] exploitative: v.adj. to treat someone unfairly by asking them to do things for you, but giving them very little in return – used to show disapproval剥削
- If we don't exploit your people, how can you feast on your ceremonies and so many concubines?
- You should re-examine the relationship that's exploitative in your opinion.
- With the price of real estate going up, there is an increasing number of people feeling exploitative.
gross [ɡroʊs] grossly: adj.adv. clearly wrong and unacceptable过分的
- The gross treatment from his father made him burst into tears.
- It was incredible that your girl friend asked for a grossly expensive gift in a week.
- I was naive enough to believe that my wife would only ask for a grossly expensive gift in a year.
forgo [fɔrˈɡoʊ]: v. to not do or have something pleasant or enjoyable SYN go without放弃
- She went to the party which her close friend held forgoing the date.
- It is unacceptable for the single mother to forgo her children.
- You bore a strong resemblance to your lord father, forgoing your lover for the position.
pacify [ˈpæsɪˌfaɪ]: v. to make someone calm, quiet, and satisfied after they have been angry or upset安抚
- Only being reunited with its mother will pacify the baby dragon.
- There's a certain probability that your mother have pacified your brother in the morning.
- The chance of using a toy to pacify your sister hit zero.
derive [dɪˈraɪv]: v. to get something, especially an advantage or a pleasant feeling, from something得到
- Your father is communicating with your uncle to derive the toy you desire for.
- Surrender the island to our king, or you will derive no peace from our cavalry.
- The scientist expected to derive some special material from the outer space.
compromise [ˈkɑmprəˌmaɪz]: v. to reach an agreement in which everyone involved accepts less than what they wanted at first妥协
- What is most remarkable about the new prime minister is that he tends to compromise with these nomads rather than start a war. 
- After two countries were compromised, their cavalries were just the right distance from each other.
- I am aware that she has no intention of compromising in the project.
problematic [ˌprɑbləˈmætɪk]: adj. involving problems and difficult to deal with有问题的
- Why the ball had hit the surface of the refrigerator was problematic.
- It was problematic that your child played truant from school.
- It was problematic that your child lost his heart after failing the exam.
autonomous [ɔˈtɑnəməs]: adj. an autonomous place or organization is free to govern or control itself SYN independent自治的
- The local grocer was so autonomous that he refused to pay protection money.
- The province is so autonomous that the king has no right to order its cavalry.
- The king feels unease about the autonomous colony after he fails to levy taxes.
--------------------
with sth. in mind: 考虑到某事
- With your safety in mind, I had to pay a ransom of 1000 dollars to the kidnapper.
- With the fate of his family in mind, the chemistry teacher having cancer in high school cooked meth to make money.
- With your emotion in mind, I don't dare to express my needs.
in sb's fair share: 在某人的公平份额
- Needless to say, she didn't put in her fair share.
- Whether the student put in his fair share is contingent on the rules or the punishments you set up.
- I will only assemble these building block into robots in my fair share.
in this mode: 在这种模式下
- You will never derive pleasure from the relationship in this mode.
- People will fall into heavy debts in this mode.
- Tree saps remain the domain of insects or tiny animals in this mode.
** sentence2
intrinsic [ɪnˈtrɪnsɪk] intrinsically: adj.adv. being part of the nature or character of someone or something OPP extrinsic固有的, 内在的, 本质的
- The love from the dying lion was so intrinsic that even the hunter was unwilling to kill her infant.
- It is the intrinsic interest of the story that people admire, not you.
- I have been studying English for two years, enjoying the intrinsic interest of English stories.
given [ˈɡɪv(ə)n]: n. a basic fact that you accept as being true固有事实
- Living in poverty in his youth is not a given.
- The detective found out that what she told was not a given, she made it.
- These days, people regard women receiving more priority in public as a given.
equity [ˈekwəti] equitable: n.adj. n.adj. treating all people in a fair and equal way OPP inequitable公平的
- When you presented a gift to your nephew and not to your niece, it was obviously not equitable.
- It was not equitable that my sister received a warmer welcome at her grandmother's home.
- The parents go out of their way to provide the twin brothers with equitable conditions.
reciprocal [rɪˈsɪprək(ə)l]: adj. a reciprocal arrangement or relationship is one in which two people or groups do or give the same things to each other ⇨ mutual互惠的
- I have benefited from reciprocal ideas which my father taught me in my youth.
- The workers were due to go on a strike so that they could reach reciprocal agreements with entrepreneurs.
- I had no idea why you treated a reciprocal agreement as oppressive.
oppressive [əˈpresɪv]: adj. powerful, cruel, and unfair压迫的
- The vicious king drew up a set of oppressive laws, which inspired rebellions.
- She was in an oppressive relationship in high school, which got her into serious trouble.
- On coming to power, the prime minister prohibited a series of oppressive laws.
exploit [ɪkˈsplɔɪt] exploitative: v.adj. to treat someone unfairly by asking them to do things for you, but giving them very little in return – used to show disapproval剥削
- If we don't exploit your people, how can you feast on your ceremonies and so many concubines?
- You should re-examine the relationship that's exploitative in your opinion.
- With the price of real estate going up, there is an increasing number of people feeling exploitative.
gross [ɡroʊs] grossly: adj.adv. clearly wrong and unacceptable过分的
- The gross treatment from his father made him burst into tears.
- It was incredible that your girlfriend asked for a grossly expensive gift in a week.
- I was naive enough to believe that my wife would only ask for a grossly expensive gift in a year.
forgo [fɔrˈɡoʊ]: v. to not do or have something pleasant or enjoyable SYN go without放弃
- She went to the party which her close friend held forgoing the date.
- It is unacceptable for the single mother to forgo her children.
- You bore a strong resemblance to your lord father, forgoing your lover for the position.
pacify [ˈpæsɪˌfaɪ]: v. to make someone calm, quiet, and satisfied after they have been angry or upset安抚
- Only being reunited with its mother will pacify the baby dragon.
- There's a certain probability that your mother has pacified your brother in the morning.
- The chance of using a toy to pacify your sister hit zero.
derive [dɪˈraɪv]: v. to get something, especially an advantage or a pleasant feeling, from something得到
- Your father is communicating with your uncle to derive the toy you desire.
- Surrender the island to our king, or you will derive no peace from our cavalry.
- The scientist expected to derive some special material from outer space.
compromise [ˈkɑmprəˌmaɪz]: v. to reach an agreement in which everyone involved accepts less than what they wanted at first妥协
- What is most remarkable about the new prime minister is that he tends to compromise with these nomads rather than start a war. 
- After the two countries were compromised, their cavalries were just the right distance from each other.
- I am aware that she has no intention of compromising on the project.
problematic [ˌprɑbləˈmætɪk]: adj. involving problems and difficult to deal with有问题的
- Why the ball had hit the surface of the refrigerator was problematic.
- It was problematic that your child played truant from school.
- It was problematic that your child lost his heart after failing the exam.
autonomous [ɔˈtɑnəməs]: adj. an autonomous place or organization is free to govern or control itself SYN independent自治的
- The local grocer was so autonomous that he refused to pay protection money.
- The province is so autonomous that the king has no right to order its cavalry.
- There is unease about the autonomous colony in the palace after the king fails to levy taxes.
--------------------
with sth. in mind: 考虑到某事
- With your safety in mind, I had to pay a ransom of 1000 dollars to the kidnapper.
- With the fate of his family in mind, the chemistry teacher having cancer in high school cooked meth to make money.
- With your emotions in mind, I don't dare to express my needs.
in sb's fair share: 在某人的公平份额
- Needless to say, she didn't put in her fair share.
- Whether the student put in his fair share is contingent on the rules or the punishments you set up.
- I will only assemble these building blocks into robots in my fair share.
in this mode: 在这种模式下
- You will never derive pleasure from the relationship in this mode.
- People are supposed to fall into heavy debt in this mode.
- Tree saps remain the domain of insects or tiny animals in this mode.
