#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-1 4.4 The Issue of Power
#+begin_verse
So we have a really good overview of more theoretical points.
But if we're really applying these to practical example on a relationship,
	important concept that comes up for me is that element of power in relationships,
		and how that really can dominate how people interact within a relationship.
And I was wondering if you could just tell me more about how this would fit into your framework.

Yeah, like when we are doing this within academia,
	it is obviously not possible to even talk about relationships
		without talking about power.
You know, feminist scholars have always drawn our attention to
	how important it is in conditioning almost anything.
And like from the queer community
	like they question the understanding of power within the heteronormal framework.
	
So, we do not use that much jargon or conceptual, technical ideas,
	and just get really down to earth, right?
We understand that like power is associated with certain social positions and conditions.
Like say for example, if you're a man, you may have more power generally than a woman.
And then, if you're white, you may have generally more power than a person of colour.
And then, if you are straight, and you may have more privilege than someone who is not, and so on.
And then, you can talk about like age, right?
If you are younger, maybe it's a little bit better.
It depends on how young though, right?
Like if you're 14, then you may not have a lot of advantage.
But if you're 34, maybe.
But if you were 84, you would have lost some of that power.
And then, we talk about income level and social status and social capital and all that.
So, but then when you put all these together, right, in a relationship,
	all these are put together, right?
So, you're there, you're not just representing a skin colour, a gender,
	or a sexual orientation, an income level, or, you know.
	
So, people will be like performing themselves within this really complex set of forces.
And it is not unusual for us to see,
		in our work I guess especially couple counselling,
	to see someone who, on paper,
		might be occupying privilege, powerful positions,
		but feeling relatively helpless and frustrated in a relationship.
And someone who might not have a lot of power on paper
	can actually be playing sort of more dominant role.
Yeah, you can say that statistically that is not as likely, but it does happen, right?

So, and when we're dealing relationships,
		obviously with all these general observations about power,
	we have to be very conscious of them.
But then, when we look at two individuals interacting,
	we would be paying more attention to what I generally call
	 like personalized, or individual, strategies of being, strategies of identification or identity.
And when power is involved, there are also strategies of resistance.
So you may find, say for example,
	a woman who is from a middle class background, well-educated,
			in a relationship with person of colour, man who is low income, not well educated
		but still feel like limited, oppressed, or even abused in that relationship.
And then to us, we will have to figure out how did that happen, you know.
And so, this is like a very different take on power.
We always look at very personalized individual circumstances
	being mindful, of course, of the social, political reality
		associated with some of these markers of power, so to speak.
#+end_verse
** expression
overview [ˈoʊvərˌvju]: n. a short description of a subject or situation that gives the main ideas without explaining all the details概况,总览
theoretical [ˌθiəˈretɪk(ə)l] theoretically: adj.adv. relating to the study of ideas, especially scientific ideas, rather than with practical uses of the ideas or practical experience ⇨ theory, practical, applied理论的
feminist [ˈfemɪnɪst]: n. someone who supports the idea that women should have the same rights and opportunities as men女权主义者
scholar [ˈskɑlər]: n. someone who has been given a scholarship to study at a school or college学者
condition [kənˈdɪʃ(ə)n]: v. formal to control or decide the way in which something can happen or exist SYN determine决定
queer [kwɪr]: adj. taboo an offensive word used to describe someone who is ↑homosexual, especially a man. Do not use this word.同性恋的
heteronormal [ˈhetəroʊ]: adj. 异性恋本位
jargon [ˈdʒɑrɡən]: n. words and expressions used in a particular profession or by a particular group of people, which are difficult for other people to understand – often used to show disapproval ⇨ argot行话
conceptual [kənˈseptʃuəl]: adj. dealing with ideas, or based on them概念上的
orientation [ˌɔriənˈteɪʃ(ə)n]: n. sexual orientation the fact that someone is ↑heterosexual or ↑homosexual(性)取向
counsel [ˈkaʊns(ə)l]: v. to listen and give support to someone with problems专业咨询
personalize [ˈpɜrsənəlˌaɪz] / personalized: v.adj. to design or change something so that it is suitable for a particular person个性化的
oppress [əˈpres]: v. to treat a group of people unfairly or cruelly, and prevent them from having the same rights that other people in society have压迫, 压抑
identification [aɪˌdentɪfɪˈkeɪʃ(ə)n]: n. how others define people VS identity身份(他人定义)
--------------------
applying A to B: 将A应用于B
come up for sb.: (想法/主意)找上某人
get down to earth: 脚踏实地
be mindful of sth.: 注意到,考虑到某事
** sentence
overview [ˈoʊvərˌvju]: n. a short description of a subject or situation that gives the main ideas without explaining all the details概况,总览
- She claimed that she caught sight of an overview of the plan.
- An overview of the seaside scenery didn't satisfy her curiosity.
- You'd better read the overview of the book before you jump into it.
theoretical [ˌθiəˈretɪk(ə)l] theoretically: adj.adv. relating to the study of ideas, especially scientific ideas, rather than with practical uses of the ideas or practical experience ⇨ theory, practical, applied理论的
- I am acquainted with the theoretical ideas our manager came up with.
- Getting obsessed with theoretical policy brought about the king's downfall.
- The scholar can't be persumed guilt because of some theoretical concepts.
feminist [ˈfemɪnɪst]: n. someone who supports the idea that women should have the same rights and opportunities as men女权主义者
- The woman who has been very kind to every men around her turned out to be a feminist on the Internet.
- A group of feminists were due to parade along the street.
- A group of feminists designed advertisements attacking innocent men who haven't taken advantge of them.
scholar [ˈskɑlər]: n. someone who has been given a scholarship to study at a school or college学者
- The knight regarded as a coward on battlefield dreams of being a scholar in the university.
- The scholar was adored by students and professors alike in academia.
- It was incredible that the dapper scholar was accused of sexual harassments.
condition [kənˈdɪʃ(ə)n]: v. formal to control or decide the way in which something can happen or exist SYN determine决定
- Who you were born to conditions your property and rights in such a society.
- How much you exercise a week conditions your sperm count.
- The money you spend will condition the emotion of your partner at a seaside resort.
queer [kwɪr]: adj. taboo an offensive word used to describe someone who is ↑homosexual, especially a man. Do not use this word.同性恋的;奇怪的
- Saying the word, nigar, is a taboo in a queer community in Canada.
- Adopting children from China became popular with people in the queer community.  
- There are many eminent doctors in the queer community.
heteronormal [ˈhetəroʊ]: adj. 异性恋本位
- 
- 
- 
jargon [ˈdʒɑrɡən]: n. words and expressions used in a particular profession or by a particular group of people, which are difficult for other people to understand – often used to show disapproval ⇨ argot行话
- An entrepreneur criticized programmers' words full of jargons.
- Nowadays, a company full of jargons is hard to make a profit in the market.
- The jargons are designed for us to better interact with each other.
conceptual [kənˈseptʃuəl]: adj. dealing with ideas, or based on them概念上的
- Once you figure out its conceptual model, you will get used to it.
- A range of conceptual models get our minds into mess.
- Whether the conceptual model works or not is still contingent on the experiments our students perform.
orientation [ˌɔriənˈteɪʃ(ə)n]: n. sexual orientation the fact that someone is ↑heterosexual or ↑homosexual(性)取向
- His sexual orientation is contingent on his experience in his youth.
- The princess was betrothed to a man whose sexual orientation was not straight.
- The lady of the house is determined to marry the prince whose sexual orientation is not straight. 
counsel [ˈkaʊns(ə)l]: v. to listen and give support to someone with problems专业咨询,建议
- The hand of the king counseled the king not to marry a man in public ceremony.
- The man from the flea bottom counseled the general to use wildfire to defend against the nomads.
- The lord who used to be a smuggler counseled his king to join the battle beyond the wall.
personalize [ˈpɜrsənəlˌaɪz] / personalized: v.adj. to design or change something so that it is suitable for a particular person个性化的
- It is the personalized counsels that helps me understand the book.
- It is not your personalized counsels that helps me defend against these nomads on the battlefield.
- All I need is the personalized plan of losing weight fitting into my habit of life.
oppress [əˈpres]: v. to treat a group of people unfairly or cruelly, and prevent them from having the same rights that other people in society have压迫, 压抑
- A man who got married to an adopted daughter from a wealth family often felt oppressed.
- No one in the world dares to oppress our people anymore.
- The people in the north turned their backs on the nomads who oppressed them occasionally.
identification [aɪˌdentɪfɪˈkeɪʃ(ə)n]: n. how others define people VS identity身份(他人定义)
- The man kept talking to me asking for my identification number.
- These days, every application is asking for users' identification number in this or that way.
- We can use published identification number to complete the forms.
--------------------
apply A to B: 将A应用于B
- I know that I will have a difficult time applying the knowledge to practical questions.
- These steam engines will be applied to industry after the exhibition.
- The money the vicar raised would be applied to the broken clock in the tower.
come up for sb.: (想法/主意)找上某人
- The idea that came up for the worker was why the box was extremely heavy.
- The idea that came up for me while we were walking along the river bank was why we spent so much money on our apartment. 
- It comes up for the child that the can must be very delicious.
get down to earth: 脚踏实地
- Instead of focusing on the grade, I chose to get down to earth doing every homework carefully.
- The girl wanted to get married with a boy who got down to earth.
- The local grocer who used to get down to earth lost heart and began to take gambles every day.
guess sb. to do sth.: 猜测某人做某事
- I guess Miumiu to keep in hiding in the box.
- She guessed her father to have her betrothed to the prince.
- The king guessed the knight to betray on the battlefield because of his father.
** sentence2
overview [ˈoʊvərˌvju]: n. a short description of a subject or situation that gives the main ideas without explaining all the details概况,总览
- She claimed that she caught sight of an overview of the plan.
- An overview of the seaside scenery didn't satisfy her curiosity.
- You'd better read the overview of the book before you jump into it.
theoretical [ˌθiəˈretɪk(ə)l] theoretically: adj.adv. relating to the study of ideas, especially scientific ideas, rather than with practical uses of the ideas or practical experience ⇨ theory, practical, applied理论的
- I am acquainted with the theoretical ideas our manager came up with.
- Getting obsessed with theoretical policy brought about the king's downfall.
- The scholar can't be presumed guilty because of some theoretical concepts.
feminist [ˈfemɪnɪst]: n. someone who supports the idea that women should have the same rights and opportunities as men女权主义者
- The woman who has been very kind to every men around her turned out to be a feminist on the Internet.
- A group of feminists were due to parade along the street.
- A group of feminists designed advertisements attacking innocent men who haven't taken advantage of them.
scholar [ˈskɑlər]: n. someone who has been given a scholarship to study at a school or college学者
- The knight regarded as a coward on the battlefield dreams of being a scholar at the university.
- The scholar was adored by students and professors alike in academia.
- It was incredible that the dapper scholar was accused of sexual harassment.
condition [kənˈdɪʃ(ə)n]: v. formal to control or decide the way in which something can happen or exist SYN determine决定
- Who you were born to conditions your property and rights in such a society.
- How much you exercise a week conditions your sperm count.
- The money you spend will condition the emotion of your partner at a seaside resort.
queer [kwɪr]: adj. taboo an offensive word used to describe someone who is ↑homosexual, especially a man. Do not use this word.同性恋的;奇怪的
- Saying the word, nigar, is taboo in a queer community in Canada.
- Adopting children from China became popular with people in the queer community.  
- There are many eminent doctors in the queer community.
heteronormal [ˈhetəroʊ]: adj. 异性恋本位
- 
- 
- 
jargon [ˈdʒɑrɡən]: n. words and expressions used in a particular profession or by a particular group of people, which are difficult for other people to understand – often used to show disapproval ⇨ argot行话
- An entrepreneur criticized programmers' words that were full of jargon.
- Nowadays, a company full of jargon is hard to make a profit in the market.
- The jargon is designed for us to better interact with each other.
conceptual [kənˈseptʃuəl]: adj. dealing with ideas, or based on them概念上的
- Once you figure out its conceptual model, you will get used to it.
- A range of conceptual models get our minds into a mess.
- Whether the conceptual model works or not is still contingent on the experiments our students perform.
orientation [ˌɔriənˈteɪʃ(ə)n]: n. sexual orientation the fact that someone is ↑heterosexual or ↑homosexual(性)取向
- His sexual orientation is contingent on his experience in his youth.
- The princess was betrothed to a man whose sexual orientation was not straight.
- The lady of the house is determined to marry the prince whose sexual orientation is not straight. 
counsel [ˈkaʊns(ə)l]: v. to listen and give support to someone with problems专业咨询,建议
- The hand of the king counseled the king not to marry a man in the public ceremony.
- The man from the flea bottom counseled the general to use wildfire to defend against the nomads.
- The lord who used to be a smuggler counseled his king to join the battle beyond the wall.
personalize [ˈpɜrsənəlˌaɪz] / personalized: v.adj. to design or change something so that it is suitable for a particular person个性化的
- It is the personalized counsel that helps me understand the book.
- It is not your personalized counsel that helps me defend against these nomads on the battlefield.
- All I need is a personalized plan for losing weight that fits into my life habits.
oppress [əˈpres]: v. to treat a group of people unfairly or cruelly, and prevent them from having the same rights that other people in society have压迫, 压抑
- A man who got married to an adopted daughter from a wealthy family often felt oppressed.
- No one in the world dares to oppress our people anymore.
- The people in the north turned their backs on the nomads who oppressed them occasionally.
identification [aɪˌdentɪfɪˈkeɪʃ(ə)n]: n. how others define people VS identity身份(他人定义)
- The man kept talking to me asking for my identification number.
- These days, every application is asking for users' identification numbers in this or that way.
- We can use a published identification number to complete the forms.
--------------------
apply A to B: 将A应用于B
- I know that I will have a difficult time applying the knowledge to practical questions.
- These steam engines will be applied to industry after the exhibition.
- The money the vicar raised would be applied to the broken clock in the tower.
come up for sb.: (想法/主意)找上某人
- The idea that came up for the worker was why the box was extremely heavy.
- The idea that came up for me while we were walking along the river bank was why we spent so much money on our apartment. 
- It comes up for the child that the can must be very delicious.
get down to earth: 脚踏实地
- Instead of focusing on the grade, I chose to get down to earth doing every homework carefully.
- The girl wanted to get married to a boy who got down to earth.
- The local grocer who used to get down to earth lost heart and began to take gambles every day.
be mindful of sth.: 注意到,考虑到某事
- He is very mindful of what happened to his wife.
- Being mindful of the mistakes he made, he decided to review the code of the project.
- Being mindful of his cat, he always presents some gift to her when he is on a business trip.
