#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-2 4.6 Compatibility - Needs
#+begin_verse
Okay, so that gives me a really good idea about how power fits into relationships.
What about the concept of compatibility?
Yeah, I think this is like very important for us to understand
	how this whole sequence of concepts link together, right?
So we talk about power,
	and then obviously, like power has something to do with these ideas of fairness and equity.
And then when you talk about fairness and equity,
	you're looking at some kind of balance in the relationship.
	
And obviously, we want to be paying attention to compatibility.
And when we look at compatibility,
	we're also actually implicitly asking the question of sustainability, of feasibility.
Is it going to work? Right?
So, and then, as we know in SSLD analysis, we will start with needs.
The N3C.
Exactly, yeah.
So we will be starting with N3C, and the first thing is needs.

So basically, when we have like two individuals that are attracted to each other,
	one of the things that we always speculate
		is that some kind of needs are being met either at a very conscious level
			or at like a not so conscious level.
Someone may be like looking for some compensation of the lack of security
		that this person experienced as a child,
	and so this person wants to be in a very stable relationship.
Some people are trying to sort of like compensate for the incomplete family that he or she had
	and was fascinated or obsessed with this idea of a healthy family.
So you also have people who are like abused as a child,
	who got very confused
		and think that someone who is strong, dominating, and protective would be attractive, you know.
And then, there are like people with a similar background really scared of people
	who are strong and like you know, dominating.
So these different needs, right, will all be operated.
And the problem is in a lot of situations,
	people are not even aware that they're driven by these needs.
So it is really important, in the beginning phase of a relationship,
	for people to pay more attention to what needs are being triggered, like the need, compatible.
	
And I just want to point out a few important processes from SSLD perspective.
One is that there are always irrational needs.
So we do not need to be worried about them,
	we just need to be more conscious of them and deal with them.
The other thing is needs do change.
And in an ideal situation, when you are involved in a good relationship,
	the relationship would actually help you grow and develop better understanding.
You'll feel better about yourself, you become more capable of communicating your needs.
And you've also become like more capable of understanding the needs of your partner,
	and both of you will grow.
And then some of these needs will be met.
And then when some of these needs are met,
	say for example, an insecure person having his or her security needs met, right?
And then it will prepare this person to move forward and develop a stronger intimate relationship,
	and the person may also be more driven towards like self-improvement, and growth and all that.
So the need profile of each participant, ideally, can also change and even improve, yeah.
#+end_verse
** expression
compatible [kəmˈpætəb(ə)l] compatibility: adj.n. able to exist or be used together without causing problems ⇨ compatibility兼容的
link [lɪŋk]: v. be linked if two things are linked, they are related in some way连结, 联合
implicit [ɪmˈplɪsɪt] implicitly: adj.adv. suggested or understood without being stated directly OPP explicit暗中的
sustainable [səˈsteɪnəb(ə)l] sustainability: adj.n. able to continue for a long time可持续的
feasible [ˈfizəb(ə)l] feasibility: adj.n. a plan, idea, or method that is feasible is possible and is likely to work SYN possible可行的, 切实可行的
speculate [ˈspekjəˌleɪt]: v. to guess about the possible causes or effects of something, without knowing all the facts or details猜测
intimate [ˈɪntɪmət]: adj. private and friendly so that you feel comfortable亲密的
profile [ˈproʊˌfaɪl]: n. a short description that gives important details about a person, a group of people, or a place轮廓,简介
** sentence
compatible [kəmˈpætəb(ə)l] compatibility: adj.n. able to exist or be used together without causing problems ⇨ compatibility兼容的
- The controller is so compatible that it controls my new computer.
- I desire for a compatible controller so that I can play and pause media without leaving my chair.
- The battery is compatible, so you don't need to buy another one when you change your phone.
link [lɪŋk]: v. be linked if two things are linked, they are related in some way连结, 联合
- Once you figure out how these concepts link, you will not ask so stupid questions.
- With the clue in mind, the detective succeeded in linking all evidence together.
- It is hard to link a kind lady to a criminal who has poisoned her all three of husbands.
implicit [ɪmˈplɪsɪt] implicitly: adj.adv. suggested or understood without being stated directly OPP explicit暗中的
- You still don't make sense of his words containing an implicit threat.
- The board of the park believed in that there is an implicit storyline.
- Those workers who were going on a strike implicitly express their gratitude to the journalist.
sustainable [səˈsteɪnəb(ə)l] sustainability: adj.n. able to continue for a long time可持续的
- The president proclaimed that we would do more to promote sustainable agriculture and industry.
- The authorities purchased a special kind of grass seed which took root in the hill for sustainable agriculture.
- This kind of cars that consume sustainable energe is being promoted.
feasible [ˈfizəb(ə)l] feasibility: adj.n. a plan, idea, or method that is feasible is possible and is likely to work SYN possible可行的, 切实可行的
- We still have a chance to put forward a feasible plan.
- The project of an airport in the suburb proved feasible, and it will put into use next year.
- Although it will run out of labors in the zoo, the hunt for puma is feasible.
speculate [ˈspekjəˌleɪt]: v. to guess about the possible causes or effects of something, without knowing all the facts or details猜测
- My grandfather refused to speculate about the lost phone.
- He refused to speculate about the rumors of his wife who he married last year.
- The lady speculated that her husband had an affair with his former colleague.
intimate [ˈɪntɪmət]: adj. private and friendly so that you feel comfortable亲密的
- My wife's intimate friend is always complaining about her naive husband.
- The manager who had an intimate relationship with the engineer has been killed in the hill.
- Would you like to speculate your intimate husband is cooking meth?
profile [ˈproʊˌfaɪl]: n. a short description that gives important details about a person, a group of people, or a place轮廓,简介
- Why don't we use those published identification numbers to fulfill our profile?
- The fool detective will get exposure to my empty profile on the social website.
- The empty profile means that she tends to hide herself in social media.
** sentence2
compatible [kəmˈpætəb(ə)l] compatibility: adj.n. able to exist or be used together without causing problems ⇨ compatibility兼容的
- The controller is so compatible that it controls my new computer.
- I desire a compatible controller so that I can play and pause media without leaving my chair.
- The battery is compatible, so you don't need to buy another one when you change your phone.
link [lɪŋk]: v. be linked if two things are linked, they are related in some way连结, 联合
- Once you figure out how these concepts link, you will not ask so stupid questions.
- With the clue in mind, the detective succeeded in linking all the evidence together.
- It is hard to link a kind lady to a criminal who has poisoned her all three of husbands.
implicit [ɪmˈplɪsɪt] implicitly: adj.adv. suggested or understood without being stated directly OPP explicit暗中的
- You still don't make sense of his words containing an implicit threat.
- The park board believed that there was an implicit storyline written by the dead engineer.
- Those workers going on strike implicitly expressed their gratitude to the journalist.
sustainable [səˈsteɪnəb(ə)l] sustainability: adj.n. able to continue for a long time可持续的
- The president proclaimed that we would do more to promote sustainable agriculture and industry.
- The authorities purchased a special kind of grass seed which took root in the hill for sustainable agriculture.
- This kind of car that consumes sustainable energy is being promoted.
feasible [ˈfizəb(ə)l] feasibility: adj.n. a plan, idea, or method that is feasible is possible and is likely to work SYN possible可行的, 切实可行的
- We still have a chance to put forward a feasible plan.
- The project of an airport in the suburb proved feasible, and it will be put into use next year.
- Although it will run out of labor in the zoo, the hunt for puma is feasible.
speculate [ˈspekjəˌleɪt]: v. to guess about the possible causes or effects of something, without knowing all the facts or details猜测
- My grandfather refused to speculate about the lost phone.
- He refused to speculate about the rumors of his wife who he married last year.
- The lady speculated that her husband had an affair with his former colleague.
intimate [ˈɪntɪmət]: adj. private and friendly so that you feel comfortable亲密的
- My wife's intimate friend is always complaining about her naive husband.
- The manager who had an intimate relationship with the engineer has been killed on the hill.
- Would you like to speculate your intimate husband is cooking meth?
profile [ˈproʊˌfaɪl]: n. a short description that gives important details about a person, a group of people, or a place轮廓,简介
- Why don't we use those published identification numbers to fulfill our profile?
- The fool detective will get exposed to my empty profile on the social website.
- The empty profile means that she tends to hide herself in social media.
