#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-2 4.8 Compatibility - Characteristics & Capacity
#+begin_verse
Okay, so what I'm hearing
	is as circumstances change, the ability to really be compatible actually changes too.
So, we don't just start off compatible and always stay compatible
	without essentially finding ways to deal with the changing life events in our relationship.
Is that right?

Yeah, I think you have actually got to the key point in this.
Yes, of course like circumstances change right?
If you imagine how a lot of like love stories start, right?
You know, you have like a couple met in college,
	and then like back then they we're like very compatible,
		because life circumstances is pretty similar
			and then aspiration, social cycle and values and stuff.
But then as they move on in life
	like there can be significant career changes
		that might even require resettling in another country for instance.
There may be changes like in a person's family circumstances
	and you may have like a family member or an aging parent that you may need to take care of.
And then people's value can also change,
	you may have like people who were sort of like politically very compatible,
		and they are in college and as activist, you know, more left-leaning
		and after 10, 12 years, they may be still politically together
			or they might have gone very different pathways, right?
So, yeah, things do change.
So what it comes down as it's like when circumstances change, right, our needs will change, right?
And even who we are like characteristics like values, politics, you know, might change.

And then the key challenge then
	is like how capable, what capacity do we have to deal with these changes.
And the other thing of course is are we really interested in dealing with the changes.
So I think that would be like a personal characteristic.
Some people would say no, I don't really want to do a lot of work here.
When something is making me uncomfortable,
	I'll just leave and go on to another relationship, right?
For some people they are actually interested in understanding the differences.
They may be interested in negotiating like a new way to work with those differences.

And one of the things makes all this discussion sort of like not easy
	is that because relationship is not just something that is affected by changes.
Relationship, we believe, like in SSLD,
	we do believe if you are good at managing, building a relationship.
The relationship itself can be an agent of change.
The relationship can cause change.
Some people actually they find a personality change, their value system changes,
	and when they're in a good relationship and they grow, and you know, they become better person.
Yeah, and so we do not just look at
	like how this changes and compatibility or impacting the relationship.
We are also hoping
	that we will be learning skills and developing capacities to deal with differences,
		to express ourselves more effectively,
		to try to appreciate the other person better
			and try to negotiate and find creative, innovative ways of being together.
So that is I think the SSLD dream.
#+end_verse
** expression
aspiration [ˌæspɪˈreɪʃ(ə)n]: n. a strong desire to have or achieve something SYN ambition志向
resettle [ˌriˈset(ə)l]: v. to go to live in a new country or area, or to help people do this(使)重新定居
lean [lin] left-leaning: v.adj. to move or bend your body in a particular direction倾斜
pathway [ˈpæθˌweɪ]: n. a path路
innovative [ˈɪnəˌveɪtɪv]:  adj. an innovative idea or way of doing something is new, different, and better than those that existed before创新的
--------------------
start off: 开始
move on: =continue继续
** sentence
aspiration [ˌæspɪˈreɪʃ(ə)n]: n. a strong desire to have or achieve something SYN ambition志向
- He can't resist the temptation to reveal his aspiration in public.
- The aspiration of the party is to unbind people all over the world.
- Obviously, his aspiration of sailing across the world didn't satisfy his lord father.
resettle [ˌriˈset(ə)l]: v. to go to live in a new country or area, or to help people do this(使)重新定居
- My old classmate's aspiration is to work for a company abroad and resettle in another country.
- People who live in poverty in China tend to resettle in another country.
- Once your characteristics have changed, you will lead a happy life in China and not think of resettling in another country.
lean [lin] left-leaning: v.adj. to move or bend your body in a particular direction倾斜
- The girl had a chance to lean towards the boy she fell in love in an activity.
- The woman assailed by a drunk exclaimed that he leaned towards her in the subway.
- The faction of the party is left-leaning, eager to start a war.
pathway [ˈpæθˌweɪ]: n. a path路
- There is a labyrinth in my hometowm full of wooden pathways.
- The amusement full of wooden pathways will come into use in September.
- In the pathway with your case, we're no longer shouting at each other.
innovative [ˈɪnəˌveɪtɪv]:  adj. an innovative idea or way of doing something is new, different, and better than those that existed before创新的
- The monetary policy proved innovative, which helped a lot of workers find a job.
- The king admired her for her innovative diplomatic policies.
- The innovative way of cultivating new species of tomato is popular in the US. 
--------------------
start off: 开始
- Let's start off by driving across the bridge.
- He hesitated to start off by coding.
- Sometimes, it's important to start off by a crude plan.
move on: 继续前进
- The parade moved on burning the ambassy down out of their anger.
- The parade moved on exposed to the armory of the authorities.
- She decided to move on trying to fit into his family members.
** sentence2
aspiration [ˌæspɪˈreɪʃ(ə)n]: n. a strong desire to have or achieve something SYN ambition志向
- He can't resist the temptation to reveal his aspiration in public.
- The aspiration of the party is to unbind people all over the world.
- Obviously, his aspiration of sailing across the world didn't satisfy his lord father.
resettle [ˌriˈset(ə)l]: v. to go to live in a new country or area, or to help people do this(使)重新定居
- My old classmate's aspiration is to work for a company abroad and resettle in another country.
- People who live in poverty in China tend to resettle in another country.
- Once your characteristics have changed, you will lead a happy life in China and not think of resettling in another country.
lean [lin] left-leaning: v.adj. to move or bend your body in a particular direction倾斜
- The girl had a chance to lean towards the boy she fell in love with in an activity.
- The woman assailed by a drunk exclaimed that he leaned towards her in the subway.
- The faction of the party is left-leaning eager to start a war.
pathway [ˈpæθˌweɪ]: n. a path路
- There is a labyrinth in my hometown that's full of wooden pathways.
- The amusement park full of wooden pathways will come into use in September.
- In the pathway with your case, we're no longer shouting at each other.
innovative [ˈɪnəˌveɪtɪv]:  adj. an innovative idea or way of doing something is new, different, and better than those that existed before创新的
- The monetary policy proved innovative, which helped a lot of workers find a job.
- The king admired her for her innovative diplomatic policies.
- The innovative way of cultivating new species of tomato is popular in the US. 
--------------------
start off: 开始
- Let's start off by driving across the bridge.
- He hesitated to start off by coding.
- Sometimes, it's important to start off with a crude plan.
move on: 继续前进
- The parade moved on burning the embassy down out of their anger.
- The parade moved on getting exposed to the armory of the authorities.
- She decided to move on trying to fit into his family members.
