#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-2 4.7 Compatibility - Circumstances
#+begin_verse
Okay, and then, when you're talking about the changing of needs,
	a lot of that time, it applies to circumstances, right?
The first C of the N3Cs.
So how does circumstances and compatibility fit in together?

Yeah, this is a very good question
	because very often, when we think of needs,
		we think of them as something that is stable that pertains to the individual, right?
But when you bring in circumstance,
	then you see the interesting interaction between the person and the circumstances.
	
Say for example, I work a lot with the immigrants.
When someone comes from a different country to a new country, circumstances change.
And because the circumstances change, right, a person's needs may also change.
So say for example that someone is a respected scholar from South Asia coming to Canada
	and then cannot find a job in a respectable university here, alright.
So, the person's need for esteem, for respect, for social recognition
		was actually very adequately met
	when he was back in his home country.
And then he obviously didn't experience a strong need for those, alright?
But after coming here, all of a sudden, you're in a new set of circumstances,
	and the means for gratifying those needs have disappeared.
Then you will be looking forward to situations
	in which you can have your need for esteem, need for recognition, gratified.
So, and before this person even realizes, Like his relationship style might have already changed.
And he is all of a sudden seeking more approval, more recognition,
	in his intimate relationship than before, right?
And then if the partner is not aware,
	because like the partner might have his or her own needs as well, right?
Then the circumstances can actually create a challenge for the relationship.
And then you can easily think of other circumstantial challenges,
	like say for example, a car accident, or someone who suddenly got laid off, right,
	or an acute illness.
All these changes in circumstances
	can obviously impact on the partner's needs and also on how they deal with the relationship.
#+end_verse
** expression
recognition [ˌrekəɡˈnɪʃ(ə)n]: n. the act of realizing and accepting that something is true or important认可
acute [əˈkjut]: adj. an acute problem is very serious急性的
--------------------
pertain to sb.: 属于某人
get laid off: 被裁员
** sentence
recognition [ˌrekəɡˈnɪʃ(ə)n]: n. the act of realizing and accepting that something is true or important认可
- There is a general recognition of the need for the management of real estate in China.
- His sincere speech gained recognition of the local tribe.
- For years on end, my wife and I gradually gained recognition of the stray cat.
acute [əˈkjut]: adj. an acute problem is very serious急性的
- An acute illness changed everything, from his wife's leaving, and getting laid off, to the death of his parents.
- An acute illness paralleled the abortion of her infant.
- An acute illness struck his wife, which led to the abortion of his infant.
--------------------
pertain to sb.: [pərˈteɪn] 属于某人
- The iPad that used to pertain to your sister is yours if you gained her recognition.
- Don't apply the ships that pertains to me to your ambition of conquering the land.
- It is said that the stick used to pertain to an infamous witch.
get laid off: 被裁员
- Due to economy crisis, she got laid off after the company she worked for didn't make a profit.
- She got laid off because she cheated on her profile.
- In China, women who gets pregnant usually gets laid off because of the lack of the enforcement of related laws.
** sentence2
recognition [ˌrekəɡˈnɪʃ(ə)n]: n. the act of realizing and accepting that something is true or important认可
- There is a general recognition of the need for the management of real estate in China.
- His sincere speech gained recognition from the local tribe.
- For years, my wife and I gradually gained recognition of the stray cat.
acute [əˈkjut]: adj. an acute problem is very serious急性的
- An acute illness changed everything, from his wife's leaving, and getting laid off, to the death of his parents.
- An acute illness paralleled the abortion of her infant.
- An acute illness struck his wife, which led to the abortion of his infant.
--------------------
pertain to sb.: [pərˈteɪn] 属于某人
- The iPad that used to pertain to your sister is yours if you gained her recognition.
- Don't apply the ships that pertain to me to your ambition of conquering the land.
- It is said that the stick used to pertain to an infamous witch.
get laid off: 被裁员
- Due to economy crises, she got laid off after the company she worked for didn't make a profit.
- She got laid off because she cheated on her profile.
- In China, women who get pregnant usually get laid off because of the lack of enforcement of related laws.
