#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-2 4.9 Compatibility, Differences and Changes
#+begin_verse
Well, I really like this expression of the SSLD dream but from what I know,
	the SSLD dream would kind of entail the concept of self-efficacy and really harnessing that,
	so could you kind of expand on that for me?
Wow, this is a [LAUGH] difficult question.
Yeah, I think it's almost philosophical.
Well, actually it is philosophical.
Yes, SSLD actually is a very personalized
	and in some way it is also a very individualistic way of imagining things.
But we also realize that for an individual
	to be effectively addressing his or her needs
		and realizing his or her potential to achieve happiness and well-being in life.
It sounds very individualistic
	but we also understand that within human world you cannot do it on your own.
It has to happen within the context of relationship.
Right.
So what we're advocating is that we hope that like in most of these relationships,
	people would come together and there would be a win-win situation for everyone involved.
So that when we have two partners in the relationship,
	both of them would have their needs met, and have that potential realized
		and attain a state of well-being and experience happiness and joy
	so that it is our dream for it.
Yeah.

But how does that work?
Well, I think the key idea here is that,
	we really have to put in some hardwork that's just like combine naturally.
And when we look around it is actually quite sad
	because managing relationships,
		managing the challenges, differences
			and potential incompatibilities
				and changing circumstances, changing characteristics and all that.
There are so much part of life but it seems that like no one is really teaching us how to do it.
You don't see it happening in schools,
	you don't see it at home and sometimes parents are not exactly the best examples for the children.
When it comes to, how do we deal with the differences?
How do we deal with incompatibilities and relationship challenges.
How we deal with challenges that come with changing circumstances.
So this is why I think we need to have SSLD programs,
	so that people actually would be given the opportunity to put some time and effort towards this,
		figure out what their own needs are.
What is that they want to accomplish?
What do they want to make out of relationships, and I think this is why we're here, right?
Definitely.
#+end_verse
** expression
harness [ˈhɑrnəs]: v. to control and use the natural force or power of something治理
individualistic [ˌɪndɪˌvɪduəˈlɪstɪk]: adj. someone who does things in their own way and has different opinions from most other people独特的
potential [pəˈtenʃ(ə)l]: n. the possibility that something will develop in a particular way, or have a particular effect潜能
joy [dʒɒɪ]: n. great happiness and pleasure喜悦
combine [ˈkɑmˌbaɪn]: v. if you combine two or more different things, or if they combine, they begin to exist or work together ⇨ combination(使)结合
--------------------
on sb's own: 独自地
come together: 团结,联合
** sentence
harness [ˈhɑrnəs]: v. to control and use the natural force or power of something治理
- Our job requires the capacity for harnessing services.
- In a way, the authorities go out their way to harness the local wind power.
- It's quite fair to say that he fails to harness the source of income.
individualistic [ˌɪndɪˌvɪduəˈlɪstɪk]: adj. someone who does things in their own way and has different opinions from most other people独特的
- Obviously, the official is unwilling to meet your individualistic needs.
- As a result of his individualistic needs, his mother commited a murder.
- Getting exposed to individualistic ideas, he didn't believe in god anymore.
potential [pəˈtenʃ(ə)l]: n. the possibility that something will develop in a particular way, or have a particular effect潜能
- He succeeded in fitting his potential into the development of relationship.
- The potential of the company impacts on its price of stock.
- The new-discovered fossils point in the direction of the research of the machine's potential.
joy [dʒɒɪ]: n. great happiness and pleasure喜悦
- When he is in the face of challenge, he always embraces diversity with joy.
- The first in being a father is to accept your long-lost son with joy.
- The baby takes in from his father's education with great joy.
combine [ˈkɑmˌbaɪn]: v. if you combine two or more different things, or if they combine, they begin to exist or work together ⇨ combination(使)结合
- Having access to new ideas from Enlightment, the philosopher combined it with old traditions.
- Otherwise, the nomads in the plain will combine with the pirates in the island.
- Combining the house of Stark and the house of Oldtown, the lady developed an intimacy relationship with the lord.
--------------------
on sb's own: 独自地
- The poor girl couldn't go to sleep on her own after her father was behead in front of the crowd.
- The prison couldn't step out of the cell on his own.
- The boy used to cook on his own when his parents worked to their bone.
come together: 团结,联合
- The proletariats all over the world come together.
- If the proletariats come together, no power in the world can stop them.
- The proletariats come together going on a strike in order to get better work conditions.
** sentence2
harness [ˈhɑrnəs]: v. to control and use the natural force or power of something治理
- Our job requires the capacity to harness services.
- In a way, the authorities go out of their way to harness the local wind power.
- It's quite fair to say that he fails to harness the source of income.
individualistic [ˌɪndɪˌvɪduəˈlɪstɪk]: adj. someone who does things in their own way and has different opinions from most other people独特的
- Obviously, the official is unwilling to meet your individualistic needs.
- As a result of his individualistic needs, his mother committed a murder.
- Getting exposed to individualistic ideas, he didn't believe in god anymore.
potential [pəˈtenʃ(ə)l]: n. the possibility that something will develop in a particular way, or have a particular effect潜能
- He succeeded in fitting his potential into the development of relationships.
- The potential of the company impacts the monetary value of its stock.
- The newly discovered fossils point in the direction of the research of the machine's potential.
joy [dʒɒɪ]: n. great happiness and pleasure喜悦
- When he is in the face of challenge, he always embraces diversity with joy.
- The first in being a father is to accept your long-lost son with joy.
- The baby takes in from his father's stories with great joy.
combine [ˈkɑmˌbaɪn]: v. if you combine two or more different things, or if they combine, they begin to exist or work together ⇨ combination(使)结合
- Having access to new ideas from the Enlightenment, the philosopher combined it with old traditions.
- Otherwise, the nomads in the plain will combine with the pirates on the island.
- Combining the house of Stark and the house of Oldtown, the lady developed an intimate relationship with the lord.
--------------------
on sb's own: 独自地
- The poor girl couldn't go to sleep on her own after her father was beheaded in front of the crowd.
- The prison couldn't step out of the cell on his own.
- The boy used to cook on his own when his parents worked to their bone.
come together: 团结,联合
- The proletariats all over the world come together.
- If the proletariats come together, no power in the world can stop them.
- The proletariats come together going on a strike in order to get better work conditions.
** summary
The SSLD dream entails the concept of self-efficacy and harnessing it.
SSLD is not only an individual but also individualistic way of imagining things,
	in which you have to address your needs and realize your potential to achieve happiness
		within the context of relationship.
We advocate that people in the relationship come together
	in order to achieve a win-win situation for everyone involved.
However, we have to put in some hardwork to make it combined naturally,
	for there're so much part of life and no one teach us how to do it,
So we need to have SSLD programs,
	so that we would have the chance to put time and effort
		towards differences and potential incompatibilities,
			and challenges with changing circumstances.
In the process, we figure out what our needs are, our goals,
	and what we want to make out of relationships.
This is why we are here.
** summary2
The SSLD dream entails the concept of self-efficacy and harnessing it.
SSLD is not only an individual but also an individualistic way of imagining things,
	in which you have to address your needs and realize your potential to achieve happiness
		only within the context of relationships.
We advocate that people in the relationship come together
	to achieve a win-win situation for everyone involved.
However, we have to put in some hard work to make it combine naturally,
	for there are so many parts of life and no one teaches us how to do them.
So we need to have SSLD programs,
	so that we would have the chance to put time and effort
		towards differences and potential incompatibilities,
			and challenges with changing circumstances.
In this process, we figure out what our needs are, our goals,
	and what we want to make out of relationships.
This is why we are here.
