#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.11 Idea of Intimacy 1
#+begin_verse
All right, so I'm really glad that you kind of drove home the point
	that everyone has their own subjective ideals.
And I guess with that said, I'm kind of curious to know what are your relationship ideals?
Well yeah, I have to really say this.
Only until very recently that I have become aware
	that the ideal that I subscribe to is not actually very popularly shared.
So like in this course we have talking about, you know, social scripts,
	and you know like how people are like heavily influenced by what they learn.
And the kind of ideals that the society reinforces.

So my personal take, I think it can be summarized in a few keywords.
The first important idea that I have is Being.
And to me an ideal relationship, when you're really close with someone.
The most important thing is for you
	to be able to be who you really are and to be accepted as who you are and what you stand for.
I think that is the ideal relationship.
Because an ideal relationship is one in which both parties can become fully who they really are.
So I think that is the first thing.

The other point, which is sort of like sometimes creates a tension with what I just said, right?
Because who and what you are, it can change, because we grow.
But then, not everyone wants to grow.
Some people are actually afraid of growing, because growth involves change.
And it also involves in many cases taking risk, moving into uncertainty.
It can also mean danger, or like you're moving into the unfamiliar.
But to me a good relationship should be growth-enhancing.
There are like theologians and you know, counselors, psychotherapists and theorists,
	specifically I'm talking about people like Carl Rogers.
Who believe that if a relationship is not growth-enhancing,
	it probably isn't even a relationship that's worth having.
And you probably should think of like quitting and be somewhere else.
That's kind of extreme but I tend to agree with him.
Like I think a good relationship should be growth-enhancing.
So that is the other keyword.

For that to happen, of course, the relationship has to develop sort of like a life of its own.
So that it has the power, the capacity,
	to actually support or enhance the participants to grow in it.
And I would say, I already mentioned about acceptance.
And the other key thing is that although people do change, a certain level of trust is important.
So that you feel that like this is a safe space for me to be who I am
	and I can like express certain aspects of myself.
Without worrying about being judged, being rejected, being punished for being who I am.
So I think that is another key idea.
And, of course, when you bring all this back together in the SSLD model,
	we will always say
		that for this to really happen, you obviously need to have a very good communication.
Because you know, how you're going to express yourself.
Is your expression of self-being accurately understood or received?
So those are the things that we cover in this course.
#+end_verse
** expression
being [ˈbiɪŋ]: n. come into being/be brought into being to start to exist存在
uncertainty [ʌnˈsɜrt(ə)nti]: n. a situation which you are not sure about because you do not know what will happen不确定性
growth-enhancing [ɡroʊθ][ɪnˈhæns]: adj. 促进成长的
theologian [ˌθiəˈloʊdʒən]: n. someone who has studied theology神学者
psychotherapy [ˌsaɪkoʊˈθerəpi] psychotherapist: n.n. the treatment of mental illness, for example ↑depression, by talking to someone and discussing their problems rather than giving them drugs精神疗法, 心理疗法
theorist [ˈθiərɪst]: n. someone who develops ideas within a particular subject that explain why particular things happen or are true理论家
quit [kwɪt]: v. especially American English to stop doing something, especially something that is bad or annoying ⇨ give up离开, 辞职, 停止
acceptance [əkˈseptəns]: n. the ability to accept an unpleasant situation which cannot be changed, without getting angry or upset about it接纳
self-being [self] [ˈbiɪŋ]: n. 自我存在
--------------------
drove home the point: 强化这个观点
subscribe to sth.: 同意某事
be close with sb.: 与某人亲近
For sb. to do sth. + ...: 为了某人做某事, ...
** sentence
being [ˈbiɪŋ]: n. come into being/be brought into being to start to exist存在
- The being of a great number of immigrants in this country drives the price of real estate up.
- The price of rice goes up because of the being of plague.
- The being of the walking dead scared the hell out of his wits.
uncertainty [ʌnˈsɜrt(ə)nti]: n. a situation which you are not sure about because you do not know what will happen不确定性
- He tries to avoid uncertainty through most of his life.
- Wary of the uncertainty about their foods, the mobs gathered around in front of the City Hall.
- There is still uncertainty about their marriage which drove their child mad.
growth-enhancing [ɡroʊθ][ɪnˈhæns]: adj. 促进成长的
- His father's lesson is growth-enchancing through most of his life.
- The marriage rate rises, which is growth-enhancing according to his definition.
- There were tons of relatives who were growth-enhancing in your youth.
theologian [ˌθiəˈloʊdʒən]: n. someone who has studied theology神学者
- The monk accused him of speaking in the position of the theologian.
- The book published by a theologian tried to prove the being of the god.
- The theologian can't put up with the ideas from the Enlightenment.
psychotherapy [ˌsaɪkoʊˈθerəpi] psychotherapist: n.n. the treatment of mental illness, for example ↑depression, by talking to someone and discussing their problems rather than giving them drugs精神疗法, 心理疗法
- The psychotherapist takes no interest in labor rights and interest.
- It is a psychotherapist who takes no interest in labor rights and interest.
- The psychotherapy came up with a set of values which represent an ideal relationship.
theorist [ˈθiərɪst]: n. someone who develops ideas within a particular subject that explain why particular things happen or are true理论家
- The theorist come up with a series of monetary policies to resolve the economy crises.
- The theorist relates with a psychotherapy who used to attack him in public.
- The theorist fails to relate with the high-up official.
quit [kwɪt]: v. especially American English to stop doing something, especially something that is bad or annoying ⇨ give up离开, 辞职, 停止
- His experience of quitting smoking added on piece to his life.
- When you think back, you won't regret quitting the relationship.
- Thinking back, I am glad that I quitted smoking when I am 21 years old.
acceptance [əkˈseptəns]: n. the ability to accept an unpleasant situation which cannot be changed, without getting angry or upset about it接纳
- Becasue of the acceptance of the bastard of her husband, she won herself the heart of her husband.
- His sacrifice for his lord father led to the acceptance from his mother.
- For the acceptance of who you are to happen, you need to follow your heart.
self-being [self] [ˈbiɪŋ]: n. 自我存在
- He trys to desribe the concept of well-being between the line.
- The teacher missed out on the concept of well-being.
- It concerns the concept of well-being, and the acceptance of what you stand for.
--------------------
drove home the point: 强化这个观点
- Thanks to his driving home the point, I have passed the exam.
- Because of my question, the teacher drove home the point.
- He drove home the point that some people don't have to have an intimacy relationship.
subscribe to sth.: 同意某事
- The ideas that the theologian subscribed to are broad-based now.
- The psychotherapist subscribed to the theory which his wife came up with.
- No one subscribes to your plan that you buy a new car instead of real estate.
be close with sb.: 与某人亲近
- The boy who was adopted at his aunt's home is not really close with his father.
- The stary cat tends to be close with people who pet him.
- Being close with his bastard brother, he was punished by his mother.
For sb. to do sth. + ...: 为了某人做某事, ...
- For you to forget about your study, maybe you go on a vacation with your mother.
- For the stary cat to have a shelter, he makes boxes out of useless cardboard.
- For my cat to drink more water, I always left a bowl of water on the desktop.
** sentence2
being [ˈbiɪŋ]: n. come into being/be brought into being to start to exist存在
- The being of a large number of immigrants in this country drives the price of real estate up.
- The price of rice goes up because of the being of plague.
- The being of the walking corpse scared the hell out of his wits.
uncertainty [ʌnˈsɜrt(ə)nti]: n. a situation which you are not sure about because you do not know what will happen不确定性
- He tries to avoid uncertainty throughout most of his life.
- Wary of the uncertainty about their food, the mobs gathered around in front of the City Hall.
- There is still uncertainty about their marriage which drove their child mad.
growth-enhancing [ɡroʊθ][ɪnˈhæns]: adj. 促进成长的
- His father's lesson is growth-enhancing throughout most of his life.
- The marriage rate rises, which is growth-enhancing according to his definition.
- There were tons of relatives who were growth-enhancing in your youth.
theologian [ˌθiəˈloʊdʒən]: n. someone who has studied theology神学者
- The monk accused him of speaking in the position of the theologian.
- The book published by a theologian tried to prove the being of the god.
- The theologian can't put up with the ideas from the Enlightenment.
psychotherapy [ˌsaɪkoʊˈθerəpi] psychotherapist: n.n. the treatment of mental illness, for example ↑depression, by talking to someone and discussing their problems rather than giving them drugs精神疗法, 心理疗法
- The psychotherapist takes no interest in labor rights and interest.
- It is a psychotherapist who takes no interest in labor rights and interest.
- The psychotherapy came up with a set of values that represent an ideal relationship.
theorist [ˈθiərɪst]: n. someone who develops ideas within a particular subject that explain why particular things happen or are true理论家
- The theorist comes up with a series of monetary policies to resolve the economic crises.
- The theorist relates with a psychotherapist who used to attack him in public.
- The theorist fails to relate with the high-up official.
quit [kwɪt]: v. especially American English to stop doing something, especially something that is bad or annoying ⇨ give up离开, 辞职, 停止
- His experience of quitting smoking added on piece to his life.
- When you think back, you won't regret quitting the relationship.
- Thinking back, I am glad that I quit smoking when I was 21 years old.
acceptance [əkˈseptəns]: n. the ability to accept an unpleasant situation which cannot be changed, without getting angry or upset about it接纳
- Because of the acceptance of the bastard of her husband, she won herself the heart of her husband.
- His sacrifice for his lord father led to the acceptance from his mother.
- For the acceptance of who you are to happen, you need to follow your heart.
self-being [self] [ˈbiɪŋ]: n. 自我存在
- He tries to describe the concept of well-being between the lines.
- The teacher missed out on the concept of well-being.
- It concerns the concept of well-being and the acceptance of who you are.
--------------------
drove home the point: 强化这个观点
- Thanks to his driving home the point, I passed the exam.
- Because of my question, the teacher drove home the point.
- He drove home the point that some people don't have to have an intimate relationship.
subscribe to sth.: 同意某事
- The ideas that the theologian subscribed to are broad-based now.
- The psychotherapist subscribed to the theory which his wife came up with.
- No one subscribes to your plan that you buy a new car instead of real estate.
be close with sb.: 与某人亲近
- The boy who was adopted at his aunt's home is not really close with his father.
- The stray cat tends to be close with people who pet him.
- Close with his bastard brother, he was punished by his mother.
For sb. to do sth. + ...: 为了某人做某事, ...
- For you to forget about your studies, maybe you go on a vacation with your mother.
- For the stray cat to have shelter, he makes boxes out of useless cardboard.
- For my cat to drink more water, I always left a bowl of water on the desktop.
