#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.17 Intimacy and Sharing of Personal Difficulties
#+begin_verse
So, I guess we have a pretty good idea of
	how physical intimacy can work on multiple levels
		with kind of emotional or psychological intimacy.
What other tips and suggestions do you have in terms of fostering intimacy in relationships?
Well, I think one of the things that we desire in a relationship for a lot of people
	is just this very sense of feeling, being accepted and being supported.
And support can range from really physical,
	like giving me rides, or making dinner, or nursing me when I'm not well.
So you can have that kind of support.

And then all of us, in our life, will go through times of difficult, frustrating, stressful.
And we find that it's actually quite interesting
	there are people
		who prefer that their partner do not know about the kind of stress that they're going through.
And they just keep it to themselves and you know, sort of insulate that from their partner.
And we cannot say that it is bad or good.
You can say that they're not communicating, they're not developing intimacy.
But this person can also say
	that I'm trying to protect him or her from being overwhelmed by my issues.
So it really depends on like what these participants in the relationship are preferring.
So this is why we always emphasize individual N3Cs when we talk about such things.

But then, like in sort of my ideal construction,
	obviously it would be wonderful if anyone is going through difficult moments in time,
		you will find your partner a source of support.
And you can, you know, utilize that space to sort of like,
	express, articulate some of your feelings and your frustrations,
		and feel the support, and get sort of energized so that you can move on.
That I think would be ideal, it would be like a good, intimate state to be in, right.

Knowing that some people would not necessarily prefer it.
And then we can also be talking about another very idealistic concept.
Not everyone is seeking that.
Actually, some people do not want that to happen.
Some people actually move into relationships to prevent that from happening.
What am I talking about?
I'm talking about personal growth and change.
#+end_verse
** expression
articulate [ɑrˈtɪkjuleɪt]: v. formal to express your ideas or feelings in words表达
energize [ˈenərˌdʒaɪz]: v. to make someone feel more determined and energetic使活跃
--------------------
times of difficult: 困难时期
keep sth. to oneself: 独自保留某事
insulate sth. from sb.: 使某事物与某人隔绝
** ch.
4-3 4.17 亲密关系与分享个人困境

所以，我想我们已经对身体上的亲密关系如何与情感或心理上的亲密关系相结合，有了一个相当清楚的认识。
那么，在促进关系中的亲密感方面，你还有哪些建议和提示呢？
嗯，我认为，对很多人来说，在一段关系中，我们渴望的一件事情就是被接受和被支持的感觉。
而支持可以是多种形式的，非常具体的，比如接送我、为我做饭，或者在我不舒服的时候照顾我。
所以，你可以有这种形式的支持。

然后，我们每个人在生活中都会经历困难、沮丧或压力大的时期。
而有趣的是，有些人不希望他们的伴侣知道自己正在经历的压力。
他们只是选择自己承担，把这些事情隔离在伴侣之外。
对此，我们无法简单地说这好还是坏。
有人可能会说，这种做法缺乏沟通，无法发展亲密关系。
但另一些人可能会认为，他们是在试图保护对方，不让对方被自己的问题压垮。
所以，这实际上取决于关系中的参与者的偏好。
因此，这也是为什么我们在谈论这些问题时，总是强调个体的 N3C（需求、愿望、能力和选择）。

但是，在我理想的构想中，显然，如果任何人在经历困难时，能找到伴侣作为支持的来源，那将是非常美好的。
你可以利用这种空间来表达和阐述你的感受和挫折，感受到支持，并获得能量，让自己可以继续前行。
我认为那将是理想的，也是良好亲密关系的一种状态，对吧？

当然，有些人可能并不一定喜欢这样。
然后，我们还可以谈到另一个非常理想化的概念。
并不是每个人都在寻求这种状态。
事实上，有些人并不希望这样发生。
有些人甚至进入关系，是为了避免这种情况的发生。
我在说什么呢？
我在谈论个人的成长与改变。
** sentence
articulate [ɑrˈtɪkjuleɪt]: v. formal to express your ideas or feelings in words表达
- If you had articulate your ideas, your pocket money would have returned to the same level.
- His knowledge of math is predicated on whether Mr. Leo articulates it in the class.
- It is sure that he has the capacity to articulate his opinion in public in a proper way.
energize [ˈenərˌdʒaɪz]: v. to make someone feel more determined and energetic使活跃
- The lovely ambiance is a condition for energizing him after hard working.
- Comfortable enjoying mass lesiure, the president has been energized.
- Obviously, he has been energized and went up to his cousin.
--------------------
times of difficult: 困难时期
- The spokeswoman for the authorities claimed that there were a million of people dying in times of difficult.
- Your boyfriend started a war with us, now we are in times of difficult.
- Because of crowd of walkers, we are in times of difficult.
keep sth. to oneself: 独自保留某事
- He preferred to keep it to himself rather than share with his young daughter.
- You can't keep it to yourself because they all have previlege of knowing it now.
- I have no idea that you keep our son's death to yourself.
insulate sth. from sb.: 使某事物与某人隔绝
- They are aiming at building a fence insulating them from walkers.
- A two-point gap insulated him from the important high school in his town.
- My cousin insisted that I should be insulated from his house in the pestilence.
** sentence2
articulate [ɑrˈtɪkjuleɪt]: v. formal to express your ideas or feelings in words表达
- If you had articulated your ideas, your pocket money would have returned to the same level.
- His math score is predicated on whether Mr. Leo articulates it in the class.
- It is sure that he has the capacity to articulate his opinion in public in a proper way.
energize [ˈenərˌdʒaɪz]: v. to make someone feel more determined and energetic使活跃
- The lovely ambiance is a condition for him to be energized after hard work.
- Comfortable enjoying mass leisure, the president has been energized.
- Obviously, he has been energized and went up to his cousin.
--------------------
times of difficulty: 困难时期
- The spokeswoman for the authorities claimed that there were a million people dying in times of difficulty.
- Your boyfriend started a war with us, we are in times of difficulty.
- Because of crowds of walkers, we are in times of difficulty.
keep sth. to oneself: 独自保留某事
- He preferred to keep it to himself rather than share it with his young daughter.
- You can't keep it to yourself because they all have the privilege of knowing it now.
- I have no idea that you keep our son's death to yourself.
insulate sth. from sb.: 使某事物与某人隔绝
- They are aiming at building a fence insulating them from walkers.
- A two-point gap insulated him from the important high school in his town.
- My cousin insisted that I should be insulated from his house in the pestilence.
