#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.19 SSLD Strategies for Building & Maintaining Relationships
#+begin_verse
So, so far we've talked a lot about the key concepts in building a relationship.
But of course with SSLD it's all about strategies and skills really applied to a relationship.
So, what are some ways that we can really apply this to building and maintaining a relationship?

Well, actually in SSLD, we have extensive experience working with people in various contexts.
Like, we have helped people who have difficulties in engaging in interpersonal relationships.
Like, some people who might have like long history of mental health concerns
	and we also work with people with social phobia.
We also work with people who do not have like clinical challenges
	and we have been running like dating workshops in different parts of the world for people
		who want to start a relationship through dating.
We also have extensive experience working with couples
		who are like either going through some challenging moments in their relationship
	or people who just want to be enhancing their relationship.
And I have to say, we really need to thank all those people who have come to us.
Because I think,
	while they think that they learned a lot from us and benefited from the experience,
	I think we actually learned a lot from them and through this working with them,
		we have gained very valuable lessons.
		
We do have quite a few very like specific procedures
	that we are utilizing in this different context.
We have like listening exercise for instance,
	which I learned can be traced back to people like Carl Rogers.
Getting people to learn to listen carefully before they speak
	so that they will always like have accurate understanding of their partner's message
		and then like the topic doesn't get shifted and displaced.
		
We also have like simple procedures like taking what we call behavioural diary,
	which will record your experience of the relationship.
And I just want to give you this example.
Maybe I've already used it before in this course, I can't remember.
But like we gave a behavioural diary
	for a couple to be recording their activity for one week, right.
Basically, they have to account for every hour.
And then you will have like one person
	coming back saying that like these are the hours that I spend with my partner.
And then the partner will give us another record which shows a very different tally all the time.
Because, the guy thinks
	that like sitting in the family room watching hockey is spending time with his partner.
And the woman who is working in the kitchen doesn't really think that is spending time together.
So that actually helps them to understand better,
	we also ask them to colour code diary
	so that they have like an indication of how satisfied or how happy they are with this experience
	so that they would have some clue
		with regard to what are the things that they enjoy doing together
			and what are the things that they hate doing together, right.
So, that is one example of very specific procedures that we use.

I can give you a third example, which is something we call the 3D appreciation exercise.
The 3D refers to discover, document, and display.
So, basically you have to discover something that you appreciate in your partner.
And then you have to document it.
And then you stage a display, you know, to openly recognized.
It doesn't have to be public.
It can be just like two of you, or you know, close friends or family, it doesn't matter.
Like you decide, but it would be an event
	in which one person would be displaying appreciation for another person.
So like we have very specific procedures that are in a way time-tested.
We have like asked people in very different circumstances to try to use them,
	usually with very encouraging results.
	
The SSLD procedures on building and maintaining relationships shared in lecture are:
	One, the listening exercises by Carl Rogers
		that would allow you to reconstruct the speakers' thinking and feeling
			and being able to relate their understanding back to the speaker.
Another one is behavioural diary,
	which helps you to assess the activities, events and experiences of the relationship.
This helps a couple understand each other's needs and feelings better
	by comparing daily activities and subjective moments together.
Lastly, we introduce a 3D appreciation exercise,
	where the 3Ds stand for discover, document, and display.
This helps the couple appreciate each other more
	by discovering the things you appreciate of your partner,
		document it, and display openly to each other of your gratefulness or appreciation.
#+end_verse
** expression
extensive [ɪkˈstensɪv]: adj. large in size, amount, or degree广泛的
concern [kənˈsɜrn]: n. a feeling of worry about something important担心,关心
clinical [ˈklɪnɪk(ə)l]: adj. relating to treating or testing people who are sick临床的, 病房用的
shift [ʃɪft]: v. if someone’s opinions, beliefs etc shift, they change改变
displace [dɪsˈpleɪs]: v. to take the place or position of something or someone SYN replace转移,置换
procedure [prəˈsidʒər]: n. a way of doing something, especially the correct or usual way ⇨ process过程,程序
diary [ˈdaɪəri]: n. a book in which you write down the things that happen to you each day SYN journal日记
tally [ˈtæli]: n. a record of how much you have spent, won etc by a particular point in time账
clue [klu]: n. information that helps you understand the reasons why something happens线索
time-tested: adj. That has been tested by time; of which the effectiveness, worth, etc., has been established over time.经受时间考验的
--------------------
be traced back to ...: 追述到...
get sb. to do sth.: 让某人做某事
** ch.
4-3 4.19 SSLD 构建与维系关系的策略

到目前为止，我们已经讨论了很多关于构建关系的关键概念。
但当然，在SSLD中，更重要的是如何将策略和技能真正应用到关系中。
那么，有哪些方法可以真正将这些策略应用于构建和维系关系呢？

实际上，在SSLD中，我们在各种情境中与人合作的经验非常丰富。
例如，我们帮助过一些在建立人际关系方面有困难的人。
这些人可能有着长期的心理健康问题历史，
我们还与患有社交恐惧症的人合作。
同时，我们也与没有临床问题的人合作。
我们曾在世界不同地区举办约会工作坊，
帮助那些希望通过约会开始一段关系的人。
此外，我们还在帮助情侣方面经验丰富，
无论是正在经历关系挑战的伴侣，
还是那些希望提升关系质量的人。
我必须感谢那些曾经向我们寻求帮助的人们，
因为我觉得，虽然他们认为从我们这里学到了很多并从中受益，
但实际上，我们也从他们身上学到了很多。
通过与他们的合作，我们获得了非常宝贵的经验教训。

我们确实在不同情境中采用了许多非常具体的程序。
例如，我们有一种叫倾听练习的方法，
它可以追溯到卡尔·罗杰斯（Carl Rogers）。
通过这种练习，人们可以在开口说话前学会认真倾听，
这样他们就能准确理解对方的意思，
从而避免话题被转移或偏离。

此外，我们还使用了像行为日记这样的简单程序，
用来记录你在关系中的经历。
我想举个例子，或许我之前在课程中已经提到过，但我记不太清了。
我们让一对伴侣记录一周的活动，
基本上，他们需要记录每个小时的活动内容。
然后，我们会发现一个人记录的“和伴侣一起的时间”，
和对方记录的往往完全不一致。
比如，男方可能认为，坐在家庭房里看冰球比赛就是和伴侣在一起的时间，
而女方在厨房忙碌时并不觉得那是共同度过的时光。
这帮助他们更好地理解彼此。
我们还要求他们用颜色标记日记，
以显示他们对某段经历的满意度或幸福感，
这样他们可以知道哪些活动是双方享受的，
而哪些是他们不喜欢一起做的。
这就是我们使用的一个具体程序的例子。

我还可以再举一个例子，叫做3D欣赏练习。
3D代表“发现（Discover）”、“记录（Document）”和“展示（Display）”。
基本上，你需要发现伴侣身上让你欣赏的某件事情，
然后把它记录下来，接着策划一个展示活动。
展示可以是公开的，也可以只是两个人之间的，
或者与亲密的朋友或家人一起，形式由你决定。
但关键是这会成为一个特殊的时刻，
一个人向另一个人表达欣赏和感激的时刻。
因此，我们有很多这样的具体程序，
它们经过时间的验证，我们也曾在各种情况下邀请人们尝试使用，
通常都取得了非常令人鼓舞的效果。

课堂中分享的SSLD在构建和维系关系方面的程序包括：

卡尔·罗杰斯的倾听练习，
这可以帮助你重构讲话者的想法和感受，
并将你对他们的理解反馈给讲话者。
行为日记，这有助于评估关系中的活动、事件和经历，
帮助伴侣通过比较日常活动和主观感受更好地理解彼此的需求和感情。
3D欣赏练习，其中3D代表“发现”、“记录”和“展示”，
帮助伴侣通过发现、记录和公开展示对彼此的欣赏，
增强彼此的感激之情和关系质量。
** sentence
extensive [ɪkˈstensɪv]: adj. large in size, amount, or degree广泛的
- No need to worry, this prison is furnished with extensive food.
- The walkers are attcking the prison that's furnished with extensive food.
- The teacher admired the girl who had extensive interests outdoor.
concern [kənˈsɜrn]: n. a feeling of worry about something important担心,关心
- The majority whip shows concern about the scandal of which the president is mindful.
- With your safety in mind, his concern for ransom had never reduced.
- Whether she has paid in her fair share is my concern now.
clinical [ˈklɪnɪk(ə)l]: adj. relating to treating or testing people who are sick临床的, 病房用的
- This kind of clinical medicine is forbidden to be sold in the market.
- The clincial medicine will prevail in the market in this mode.
- The special clinical medicine pertains to the patient.
shift [ʃɪft]: v. if someone’s opinions, beliefs etc shift, they change改变
- As the circumstances have shifted, the poor programmer gets laid off in no time.
- While the circumstances have shifted, the naive boy refused to grow up.
- With circumstances shifting, he moves on to get married to his colleague.
displace [dɪsˈpleɪs]: v. to take the place or position of something or someone SYN replace转移,置换
- You needn't have displaced the apartment on your own.
- Let's come together, refuse to displace our post in the office.
- The request for displacing the computer is come up as the signal of firing the programmer.
procedure [prəˈsidʒər]: n. a way of doing something, especially the correct or usual way ⇨ process过程,程序
- The programmer gets to make the procedure for paying section.
- We see eye to eye about promoting the procedure.
- After a few rounds, the programmer is satisfied with the efficacy of the procedure.
diary [ˈdaɪəri]: n. a book in which you write down the things that happen to you each day SYN journal日记
- I had a habit of keeping a diary until I found my mother looked at it secretly.
- The research for the diary that a vicar kept works out.
- In his diary, the archaeologist drove home the point that the tree was a source of income.
tally [ˈtæli]: n. a record of how much you have spent, won etc by a particular point in time账
- The tally you got is totally different from your wife's.
- How much is the final tally?
- We all subscribe to that we can't afford the final tally.
clue [klu]: n. information that helps you understand the reasons why something happens线索
- Close with the peasant, the policeman tried to find more clues about the murder.
- For the police to find less clues, the murderer was going to burn the apartment down.
- With clues accumulating, the expert from zoo felt obliged to hunt for the animal.
time-tested: adj. That has been tested by time; of which the effectiveness, worth, etc., has been established over time.经受时间考验的
- My wife is striking toward a time-tested friendship.
- Stay the same, our friendship must be time-tested.
- The knight has kept the secret for the rest of his life, his loylty is time-tested.
--------------------
be traced back to ...: 追述到...
- The jewelry is said to be traced back to a French king.
- The lost treasure can be traced back to a ship which was sacked by pirates.
- The school can be traced back to an infamous general during last dynasty.
get sb. to do sth.: 让某人做某事
- You have the chance to get your husband to bring you a coat.
- He failed to get his cat to drink water.
- The professor gets me to explore more about relationships.
** sentence2
extensive [ɪkˈstensɪv]: adj. large in size, amount, or degree广泛的
- No need to worry, this prison is furnished with extensive food.
- The walkers are attacking the prison that's furnished with extensive food.
- The teacher admired the girl who had extensive interests in the outdoors.
concern [kənˈsɜrn]: n. a feeling of worry about something important担心,关心
- The majority whip shows concern about the scandal of which the president is mindful.
- With your safety in mind, his concern for ransom had never been reduced.
- Whether she has paid her fair share is my concern now.
clinical [ˈklɪnɪk(ə)l]: adj. relating to treating or testing people who are sick临床的, 病房用的
- This kind of clinical medicine is forbidden from being sold in the market.
- The clinical medicine will prevail in the market in this mode.
- The special clinical medicine pertains to the patient.
shift [ʃɪft]: v. if someone’s opinions, beliefs etc shift, they change改变
- As the circumstances have shifted, the poor programmer gets laid off in no time.
- While the circumstances have shifted, the naive boy refused to grow up.
- With circumstances shifting, he moves on to get married to his colleague.
displace [dɪsˈpleɪs]: v. to take the place or position of something or someone SYN replace转移,置换
- You needn't have displaced the apartment on your own.
- Let's come together, and refuse to displace our post in the office.
- The request to displace the computer is come up as the signal of firing the programmer.
procedure [prəˈsidʒər]: n. a way of doing something, especially the correct or usual way ⇨ process过程,程序
- The programmer gets to make the procedure for the paying section.
- We see eye to eye about promoting the procedure.
- After a few rounds, the programmer is satisfied with the efficacy of the procedure.
diary [ˈdaɪəri]: n. a book in which you write down the things that happen to you each day SYN journal日记
- I had a habit of keeping a diary until I found my mother looked at it secretly.
- The research for the diary that a vicar kept works out.
- In his diary, the archaeologist drove home the point that the tree was a source of income.
tally [ˈtæli]: n. a record of how much you have spent, won etc by a particular point in time账
- The tally you got is totally different from your wife's.
- How much is the final tally?
- We all subscribe to that we can't afford the final tally.
clue [klu]: n. information that helps you understand the reasons why something happens线索
- The policeman who is close to the peasant tries to find more clues about the murder.
- For the police to find fewer clues, the murderer was going to burn the apartment down.
- With clues accumulating, the expert from the zoo felt obliged to hunt for the animal.
time-tested: adj. That has been tested by time; of which the effectiveness, worth, etc., has been established over time.经受时间考验的
- My wife is striking toward a time-tested friendship.
- Stay the same, our friendship must be time-tested.
- The knight has kept the secret for the rest of his life, his loyalty is time-tested.
--------------------
be traced back to ...: 追述到...
- The jewelry is said to be traced back to a French king.
- The lost treasure can be traced back to a ship that was sacked by pirates.
- The school can be traced back to an infamous general during the last dynasty.
get sb. to do sth.: 让某人做某事
- You have the chance to get your husband to bring you a coat.
- He failed to get his cat to drink water.
- The professor gets me to explore more about relationships.
