#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.16 The Role of Physical Intimacy
#+begin_verse
It's interesting kind of how you say it, become a little more intimate.
So that actually sort of moves my mind to the idea of more like physical intimacy.
So how does physical intimacy play into all of it?
Like, you know, do you have tips around that as well?
Well, you know, like physical intimacy is probably another topic
	that we may have to set up another discussion around.
But for our purpose here, I think it's important to deal with this.

There are obviously huge cultural differences. Right.
And then even within the same context that we are in.
Like in North America, like one of the big cosmopolitan centres in North America,
	you have people coming from so many different places.
When it comes to physical intimacy.
	you have almost like puritanical, conservative positions taken by people.
And you have people very open-minded, very liberated.
And even in the city you can find probably hundreds of different opinions, position people take.

I just want to point this out,
	the relation between physical intimacy and emotional and psychological intimacy
		is a very fluid one and it is like also very contingent, meaning that it is not fixed.
It is not that likely to be physically more intimate,
	then we will be simultaneously emotionally intimate.
Some people can actually get very intimate physically without ever getting intimate emotionally.
And some people can be very intimate emotionally without even touching each other's fingers.
Right, so we have to understand
	that like there are two sort of like relatively independent concepts at least in theory.
	
But of course in real life, we understand that like if you get close to another person,
	it can trigger your emotional feelings.
And some people may actually feel more intimate with another person
	after being physically intimate with that person.
So that happens too.
And for some people, emotional intimacy is actually a condition for physical intimacy,
	I don't like go to bed with someone unless I feel emotionally close with that person.
And speaking from my personal experience, I have to add this.
Depending on who your partner is,
	some people actually would have to get physically intimate first
		before they can develop enough trust and a level of comfort
			to be talking about certain things.
So, and I would say that it is probably true to say
	that like some people would talk to people in order to get to sleep with them.
But it is also true that some people will have to sleep with someone first
	before they can really talk to them, right.
And I would say both can happen.
#+end_verse
** expression
cosmopolitan [ˌkɑzməˈpɑlɪt(ə)n]: adj. a cosmopolitan place has people from many different parts of the world – use this to show approval世界性的,全球(各地)的
puritanical [ˌpjʊrɪˈtænɪk(ə)l]: adj. very strict about moral matters, especially sex – used in order to show disapproval清教徒的
fluid [ˈfluɪd]: adj. a situation that is fluid is likely to change易变的
simultaneous[ˌsaɪm(ə)lˈteɪniəs] simultaneously: adj.adv. things that are simultaneous happen at exactly the same time同时的
** ch.
4-3 4.16 身体亲密的角色

很有趣，你提到变得更加亲密。
这让我想到更多关于身体亲密的概念。那么身体亲密在其中扮演什么角色呢？
比如说，你对此有没有一些建议呢？
嗯，你知道吗，身体亲密可能是另一个需要我们专门展开讨论的话题。
但就我们这里的目的而言，我认为讨论这一点还是很重要的。

显然，不同文化之间存在巨大的差异，对吧。
即使是在我们所处的同一个文化背景中也是如此。
比如在北美，在北美的一些大都市中心，
你会看到来自不同地方的人，涉及身体亲密时，
有些人采取了几乎清教徒式的保守立场，
而另一些人则非常开放，非常自由化。
即使在同一个城市里，你也能找到可能上百种不同的意见和立场。

我想指出的一点是，身体亲密与情感和心理亲密之间的关系是非常流动的，
而且是非常依赖具体情况的，这意味着它并不是固定的。
并不是说身体上变得更加亲密，我们就会同时变得情感上更亲密。
有些人实际上可以在身体上非常亲密，却从未在情感上亲密。
也有些人可以在情感上非常亲密，却连手指都没有碰过对方，对吧。
所以我们需要理解，至少在理论上，这两个概念是相对独立的。

但当然，在现实生活中，我们明白如果你接近另一个人，
这可能会引发你的情感反应。
有些人在与他人身体上亲密后，
可能会感到更加情感上的亲密，这种情况也会发生。
而对另一些人来说，情感上的亲密实际上是身体亲密的前提，
他们会说，"我不会和某人上床，除非我对那个人有情感上的亲近感。"

从我的个人经验来说，我必须补充一点，
这取决于你的伴侣是谁。
有些人实际上必须先在身体上亲密，
然后才能发展出足够的信任和舒适感，
去谈论某些事情。

所以，我会说，这种情况可能是真的：
有些人会为了上床而与他人交谈。
但同样也是真的，有些人必须先与某人发生性关系，
然后才能真正与那人交谈，对吧。
而且我会说，这两种情况都可能发生。
** sentence
cosmopolitan [ˌkɑzməˈpɑlɪt(ə)n]: adj. a cosmopolitan place has people from many different parts of the world – use this to show approval世界性的,全球(各地)的
- The school is cosmopolitan full of undergrad students who are from all parts of the world.
- Shanghai is regarded as a cosmopolitan city in my opinion.
- The reforming government is determined to foster a cosmopolitan city.
puritanical [ˌpjʊrɪˈtænɪk(ə)l]: adj. very strict about moral matters, especially sex – used in order to show disapproval清教徒的
- Your top-down approach is so puritanical that your daughter can't follow it first.
- She makes an assumption that she lives in a city full of puritanical laws.
- The girl who used to study abroad refused to take a course on puritanical traditions.
fluid [ˈfluɪd]: adj. a situation that is fluid is likely to change易变的
- It doesn't make sense for you to be fluid about merging two schools.
- My wife is really fluid in her ovulation cycle.
- You should have taken the fluid chance to study abroad.
simultaneous[ˌsaɪm(ə)lˈteɪniəs] simultaneously: adj.adv. things that are simultaneous happen at exactly the same time同时的
- As many as 20 guests have simultaneous access to our website.
- Water, corpses, and gas simultaneously feed into the river which lies in front of our house.
- It appeared that two murders had happened simultaneously.
** sentence2
cosmopolitan [ˌkɑzməˈpɑlɪt(ə)n]: adj. a cosmopolitan place has people from many different parts of the world – use this to show approval世界性的,全球(各地)的
- The school is cosmopolitan full of undergrad students who are from all parts of the world.
- Shanghai is regarded as a cosmopolitan city in my opinion.
- The reforming government is determined to foster a cosmopolitan city.
puritanical [ˌpjʊrɪˈtænɪk(ə)l]: adj. very strict about moral matters, especially sex – used in order to show disapproval清教徒的
- Your top-down approach is so puritanical that your daughter can't follow it first.
- She makes an assumption that she lives in a city full of puritanical laws.
- The girl who used to study abroad refused to take a course on puritanical traditions.
fluid [ˈfluɪd]: adj. a situation that is fluid is likely to change易变的
- It doesn't make sense for you to be fluid about merging two schools.
- My wife is really fluid in her ovulation cycle.
- You should have taken the fluid chance to study abroad.
simultaneous[ˌsaɪm(ə)lˈteɪniəs] simultaneously: adj.adv. things that are simultaneous happen at exactly the same time同时的
- As many as 20 guests have simultaneous access to our website.
- Water, corpses, and gas simultaneously feed into the river in front of our house.
- It appeared that two murders had happened simultaneously.
