#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.10 Intimacy
#+begin_verse
We've talked a couple of times or it's sort of come up as this notion of what's ideal in SSLD
	but really if there's anything we've learned so far,
		everyone has their own definition of what's ideal, right?
So, and for me for example
	I think a lot about the notion of intimacy and challenges in relationships.
So some people might just kind of want, like easy-going relationship
	in terms of, you know, what they get up to, maybe watching TV, Netflix and chill.
Whereas I don't know,
	I personally kind of like the challenge of maybe we don't see eye to eye politically.
And having that ability to really talk it out and debate.
And even sometimes maybe get a little mad.
But for me I sort of need that.
So, I mean people have different standards in what is ideal for them, right?

That's very true.
You know, that is exactly why we always emphasis individual differences
	instead of saying that everyone has to get to this level of intimacy.
Everyone has to attain this level of intensity
	and everyone needs
		to experience this phenomenal self-understanding and growth and development in a relationship.
So I think those are sort of like ideals
	that different people, authors, scholars have tried to portray.
	
But you're right, in a real life situation, people actually have different preferences.
Some people do not want to have intimacy.
Some people dread intimacy.
Or at least the kind of intimacy that we're talking about.
So it is important, therefore, to start with every individual's N3Cs as we have always said, right?
And if someone wants a pretty instrumental almost relationship
	like I just want to have someone to share the house, share the expenses,
			and like provide some basic support to each other in life,
		then we don't talk about detailed stuff at all.
I don't even have to know about your childhood experience and your family of origin, you know?
We're fine.
I don't see why this is a problem.
If both partners are satisfied with that arrangement.
So and I think it's perfectly okay for them to be building a relationship like that.
And if it works out and they are both happy, then I think it is fantastic.

So what we are trying to say here with regard to, you know,
	intimacy, obviously represents a certain set of values that maybe I have.
[LAUGH] Thinking that people can move on and develop a certain kind of intimacy and deep sharing,
	and understanding each other, doing creative fun things, and all of those.
And I think it is good that you have asked that question.
So that we can make it clear to people not everyone has to have this kind of relationship.
Okay.
Like you just basically go into a relationship and get what you want out of it.
Make the best of it, according to your own definition, right, your own standard.
I think yeah, that's a very important point.
#+end_verse
** expression
notion [ˈnoʊʃ(ə)n]: n. an idea, belief, or opinion观念
definition [ˌdefəˈnɪʃ(ə)n]: n. a phrase or sentence that says exactly what a word, phrase, or idea means ⇨ define定义
chill [tʃɪl]: v.n. a feeling of being cold, caused by being ill着凉
intensity [ɪnˈtensɪti]: n. the quality of being felt very strongly or having a strong effect强度
phenomenal [fəˈnɑmɪn(ə)l]: adj. very great or impressive显著的
expense [ɪkˈspens]: n. the amount of money that you spend on something
arrangement [əˈreɪndʒmənt]: n. plans and preparations that you must make so that something can happen安排
--------------------
be come up as sth.: 被认为是某物
get up to sth./doing sth.: 着手做某事
see eye to eye: 是意见一致
be satisfied with sth.: 对某物满意
work out: 成功,顺利进行
** sentence
notion [ˈnoʊʃ(ə)n]: n. an idea, belief, or opinion观念
- The notion of what's intimacy is part and parcel of the course about relationship.
- The notion of what's well-being varys on the individual level.
- Follow your heart, figure out the notion of what's your purpose.
definition [ˌdefəˈnɪʃ(ə)n]: n. a phrase or sentence that says exactly what a word, phrase, or idea means ⇨ define定义
- The definition of heart may be mistaken in China on a broader level.
- Say, for example, some students can't remember the definition of a complicated concept without using it in real life.
- These students are up for studying the definition of a newly discovered material.
chill [tʃɪl]: v.n. a feeling of being cold, caused by being ill着凉
- After going in the fancy dress party, both my sister and I caught a chill.
- She took care of the baby who caught a chill.
- The prince couldn't take a plunge because of a serious chill.
intensity [ɪnˈtensɪti]: n. the quality of being felt very strongly or having a strong effect强度
- There is a very real possibility that the intensity of the storm is beyond what the station can resist.
- The station is capable to measure the intensity of the wind after bringing in the new machine.
- Very often, measuring the intensity of the wind is a good way of predicting the harvest.
phenomenal [fəˈnɑmɪn(ə)l]: adj. very great or impressive显著的
- I have to confess that I am envious of your phenomenal success.
- The phenomenal success of his expertise inspired awe in his colleagues.
- His phenomenal success is a big share of bringing science to the box.
expense [ɪkˈspens]: n. the amount of money that you spend on something
- To develop a good relationship with your classmates, start off with sharing rent expense.
- The cute girl leapt onto the idea that her boyfriend could move to her apartment and share rent expense.
- He takes a positive attitude on finding a roommate to share rent expense.
arrangement [əˈreɪndʒmənt]: n. plans and preparations that you must make so that something can happen安排
- His lords were not satisfied with the arrangement that the king married a man in public ceremony.
- The teacher who has devoted himself to the school has to be focus on the arrangment about his retirement.
- If I had knew the arrangment, I wouldn't have asked you for a lift.
--------------------
be come up as sth.: 被认为是某物
- He was come up as a shrewd businessman in his hometown.
- The woman who was come up as a traitor turned out to be a spy.
- The prisoner who was come up as a spy would be beheaded in the square.
get up to sth./doing sth.: 着手做某事
- He gets up to learning ice-skating. 
- Get up to cooking, or face your father's anger when he comes back.
- Get up to clear it out, or our room will be full of the smell of urine.
see eye to eye: 是意见一致
- She is going to marry a man who sees eye to eye politically.
- If we saw eye to eye politically, we would conquer the land.
- If the nomads and we saw eye to eye politically, we wouldn't fight against them with gunpowder.
be satisfied with sth.: 对某物满意
- My aunt is very satisfied with the wife which my cousin married.
- The medic in the surgery team is very satisfied with the operation he had yesterday.
- Satisfied with his son's new girlfriend, he presented her with a big red pocket.
work out: 成功,顺利进行
- If it works out and our company makes a profit, we will get promoted.
- He planed it to the last detail to ensure it works out.
- Whether it works out or not depends on how much effort and time you put in.
** sentence2
notion [ˈnoʊʃ(ə)n]: n. an idea, belief, or opinion观念
- The notion of what's intimacy is part and parcel of the course about relationships.
- The notion of what's well-being varies on the individual level.
- Follow your heart, and figure out the notion of the Enlightenment.
definition [ˌdefəˈnɪʃ(ə)n]: n. a phrase or sentence that says exactly what a word, phrase, or idea means ⇨ define定义
- The definition of heart may be mistaken in China on a broader level.
- Say, for example, some students can't remember the definition of a complicated concept without using it in real life.
- These students are up for studying the definition of a newly discovered material.
chill [tʃɪl]: v.n. a feeling of being cold, caused by being ill着凉
- After going to the fancy dress party, both my sister and I caught a chill.
- She took care of the baby who caught a chill.
- The prince couldn't take a plunge because of a serious chill.
intensity [ɪnˈtensɪti]: n. the quality of being felt very strongly or having a strong effect强度
- There is a very real possibility that the intensity of the storm is beyond what the station can resist.
- The station is capable of measuring the intensity of the wind after bringing in the new machine.
- Very often, measuring the intensity of the wind is a good way of predicting the harvest.
phenomenal [fəˈnɑmɪn(ə)l]: adj. very great or impressive显著的
- I have to confess that I am envious of your phenomenal success.
- The phenomenal success of his expertise inspired awe in his colleagues.
- His phenomenal success is a big share of bringing science to the box.
expense [ɪkˈspens]: n. the amount of money that you spend on something
- To develop a good relationship with your classmates, start off with sharing rent expenses.
- The cute girl leaped onto the idea that her boyfriend could move to her apartment and share rent expenses.
- He takes a positive attitude on finding a roommate to share rent expenses.
arrangement [əˈreɪndʒmənt]: n. plans and preparations that you must make so that something can happen安排
- His lords were not satisfied with the arrangement that the king married a man in a public ceremony.
- The teacher who has devoted himself to the school has to be focused on the arrangement of his retirement.
- If I had known the arrangement, I wouldn't have asked you for a lift.
--------------------
come up as sth.: 被认为是某物
- He has come up as a shrewd businessman in his hometown.
- The woman who came up as a traitor turned out to be a spy.
- The prisoner who was come up as a spy would be beheaded in the square.
get up to sth./doing sth.: 着手做某事
- He gets up to exercising ice skating. 
- Get up to cooking, or face your father's anger after he goes home.
- Get up to clear it out, otherwise our room will be full of the smell of urine.
see eye to eye: 是意见一致
- She decided to marry the noble who sees eye to eye politically.
- If we saw eye to eye politically, we would conquer the land.
- If the nomads and we saw eye to eye politically, we wouldn't fight against them with gunpowder.
be satisfied with sth.: 对某物满意
- My aunt is extremely satisfied with the wife who my cousin married.
- The medic in the surgery team is very satisfied with the operation he had yesterday.
- Satisfied with his son's new girlfriend, he presented her with a big red pocket.
work out: 成功,顺利进行
- If it works out and our company makes a profit, we will get promoted.
- He planned it to the last detail to ensure it worked out.
- Whether it works out depends on how much effort and time you put in.
** summary
Everyone has their own definition of intimacy and what's ideal.
So we emphasis individual differences
	instead of saying that everyone has to attain this level of intensity
		that they have to experience self-understanding, growth, and development in a relationship.
It is ideals portraied by many people that represent a certain set of values.
Because people actually have different preferences about intimacy,
	like some don't want to have intimacy, even dread it.
If both partners are satisfied with the arrangement,
	it is not a problem that they don't have intimacy.
So you can basically go into a relationship and get what you need out of it
	according to your own definition.
** summary2
Everyone has a different definition of intimacy and what's ideal.
So we emphasize individual differences
	instead of saying that everyone has to attain this level of intensity
		that they experience self-understanding, growth, and development in a relationship.
It is ideals portrayed by many people that represent a certain set of values.
Because people have different preferences about intimacy,
	some don't want to have intimacy, or even dread it.
If both partners are satisfied with the arrangement,
	it is not a problem that they don't have intimacy in the relationship.
So you can go into a relationship and get what you need out of it according to your definition.
