#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-3 4.15 Building Intimacy
#+begin_verse
Okay, so far what we know with intimacy
		is everyone's idea of intimacy and standards for what they're looking for is subjective.
And some people might not want intimacy at all, and that's okay, too.
But for people who are looking to maybe foster and grow intimacy in the relationship,
	do we have some helpful tips for them?
Well, I think the simple answer is yes, but I have to say this first.
We already said it.
We do not think that everyone has to be aiming at the same level of intimacy,
	and they should probably choose the level of intimacy that they're comfortable with.
	
But if you really want to do it right,
	then you have to understand that the idea of intimacy itself can have its own problems.
The idea of intimacy originally refers to the inmost, innermost, the deepest.
So we are sort of like reaching into the deepest corners of our being, or the ground of being,
	and then when two individuals are becoming very intimate,
		like the distance between them, or the boundary even between them will disappear,
		and they sort of like merge, right?
And is it desirable?

It depends on how you look at it.
Like some people think that it is too enmeshed,
	then people lose their individuality, which is not necessarily a good thing.
So there is like some kind of balance that we need to achieve.
A psychologist who wrote a very well-known book back in the 50s, Erich Fromm, had this to say.
He said, in love, the paradox occurs that the two beings become one and yet remain two.
So he's sort of like pointing out
	there should be a balance between like merging together and becoming one person,
		and then maintaining your own individuality, your own being, or your own personality.
So I think that is a key starting point.

So as we want to do that, right, one of the things that I always encourage
	is for people to have a safe space created between them
		so that they will feel free to negotiate what kind of distance we want to maintain.
And I can ask a participant in this relationship
	openly, directly, honestly communicate to you, what am I comfortable with and what do I want.
And when we have that safe space created,
	right, then it increases the chance of
		us negotiating the optimum distance or intimacy that we have.
		
But that's a condition for that to happen, right?
And that condition itself can be considered a measure of intimacy itself,
	that is condition of trust.
So I need to feel safe, I need to be able to trust you.
And for people to achieve trust,
	it also involves some level of understanding, sharing, communication.
And it is actually quite interesting
	when I'm talking like this, it may come over as convoluted, but that actually is a cycle.
So if you have more trust, you build a space,
	and a space will allow you negotiate your intimacy more easily,
	but how do you start having trust in the first place, right?
It will involve the participants to move in and share something.

And one of the findings that we have paid attention to in social psychology
	is how trust can be connected to self-disclosure.
If you would let the other person know more about you,
	you are more likely to get the other person to trust you.
But then, like, as you can easily see,
	the very process of doing it itself increases intimacy, right?
So in a way, when I say that you have to create a condition of trust,
	I'm already suggesting that you become a little bit more intimate, right.
Before you even move on to negotiate, like what is intimate.
#+end_verse
** expression
inmost [ˈɪnˌmoʊst]: adj. your inmost feelings, desires etc are your most personal and secret ones心底的
innermost [ˈɪnə(r)ˌməʊst]: adj. your innermost feelings, desires etc are your most personal and secret ones内心的
merge [mɜrdʒ]: v. if two things merge, or if one thing merges into another, you cannot clearly see them, hear them etc as separate things合并
desirable [dɪˈzaɪrəb(ə)l]: adj. formal something that is desirable is worth having or doing值得拥有的
enmeshed [ɪnˈmeʃt] (in/with): v. adj. very involved in an unpleasant or complicated situation使陷入的
paradox [ˈperəˌdɑks]: n. a situation that seems strange because it involves two ideas or qualities that are very different悖论
optimum [ˈɑptɪməm]: adj. adj. the best or most suitable for a particular purpose or in a particular situation最适宜的
convoluted [ˈkɑnvəˌlutəd]: adj. complicated and difficult to understand费解的
disclosure [dɪsˈkloʊʒər]: n. a secret that someone tells people, or the act of telling this secret公开,披露
--------------------
so far: 目前为止
know with sth.: 熟悉某事
look to do sth.: 期待做某事
aim at sth.: 旨在于某事
come over as adj.: 显得是...
** ch.
4-3 4.15 建立亲密关系

好，迄今为止，我们对亲密关系的理解是，每个人对亲密的定义和他们在关系中追求的标准都是主观的。有些人可能根本不想要亲密关系，这也没问题。但对于那些想要在关系中培养和发展亲密的人，我们有没有一些有帮助的建议呢？

嗯，我想简单的答案是有的，但我得先说清楚。我们之前已经说过了，我们不认为每个人都必须追求相同层次的亲密关系，他们应该选择一个让自己感到舒适的亲密层次。

但如果你真的想做到最好，那么你必须理解亲密本身的概念可能会带来一些问题。亲密的概念最初指的是最内心、最深处的部分。所以我们就像是要触及到自己存在的最深处或最根本的地方，当两个人变得非常亲密时，他们之间的距离，甚至是界限，会消失，他们就像是融合在一起了，对吧？这种融合是值得追求的吗？

这取决于你怎么看。有些人认为这太过于纠缠，最终导致人们失去自己的个性，这未必是好事。因此，我们需要在其中找到一种平衡。20世纪50年代写了本非常著名书籍的心理学家埃里希·弗洛姆曾这样说过，他说，在爱情中，出现了一个悖论，那就是两个人成为一体，但又依然保持着各自的独立性。所以，他指出，应该在融合成为一个整体与保持自我个性、自我存在或自我性格之间找到平衡。我认为这是一个关键的起点。

所以，如果我们想做到这一点，我总是鼓励大家在彼此之间创造一个安全空间，这样他们就能自由地商量我们希望保持多远的距离。我可以直接、诚实地向这段关系中的另一方表达，我感到舒适的是什么，我想要的是什么。当我们创造了这样的安全空间时，就会增加我们协商出最适合的距离或亲密度的机会。

但这是发生这一切的前提，对吧？而这个前提本身可以看作是亲密的一个衡量标准，那就是信任的条件。所以，我需要感到安全，我需要能够信任你。而要建立信任，涉及到某种程度的理解、分享和沟通。实际上，这非常有趣，当我这样说的时候，可能听起来有些复杂，但这实际上是一个循环。如果你有更多的信任，你就能建立一个空间，而这个空间能让你更容易地协商你们的亲密度。但你如何开始建立信任呢？这会要求参与者走得更近，去分享一些东西。

在社会心理学中，我们关注到的一个发现是，信任如何与自我揭露相关联。如果你让对方更多地了解你，你更有可能让对方信任你。但正如你很容易看见的那样，进行这一过程本身就会增加亲密关系。所以从某种意义上讲，当我说你必须创造信任的条件时，我已经在暗示你变得更加亲密了，在你甚至开始商量“亲密”是什么之前。
** sentence
inmost [ˈɪnˌmoʊst]: adj. your inmost feelings, desires etc are your most personal and secret ones心底的
- He never has the idea of talking about his inmost secret.
- The other way around, he devoted himself to you because of his inmost love for you.
- You need to adressed your need, disclosing your inmost love for her. 
innermost [ˈɪnə(r)ˌməʊst]: adj. your innermost feelings, desires etc are your most personal and secret ones内心的
- Other than that, his innermost secret makes him scared of the authorities.
- The boy who gets edcuated in town is not likely to disclose his innermost love for the girl.
- The express of our innermost love for our child varied in different context.
merge [mɜrdʒ]: v. if two things merge, or if one thing merges into another, you cannot clearly see them, hear them etc as separate things合并
- People in the town take the two hospitals for granted to be merged.
- The headmaster aimed at merging his school with another.
- There is a tiny chance that your company merges with your wife's.
desirable [dɪˈzaɪrəb(ə)l]: adj. formal something that is desirable is worth having or doing值得拥有的
- The robot that has been broken into small parts is still desirable.
- The seriousness that he expressed when he was occupied with his homework is desirable.
- After a few rounds, the boxer realized that the desirable victory was often not easy.
enmeshed [ɪnˈmeʃt] (in/with): v. adj. very involved in an unpleasant or complicated situation使陷入的
- The lady enmeshed in a marriage is often abused by her drunk husband.
- The police enmeshed in a serious car accident was asked to pay a large amount of damage compensation.
- There is a huge chance that they are being enmeshed in a trap.
paradox [ˈperəˌdɑks]: n. a situation that seems strange because it involves two ideas or qualities that are very different悖论
- The boy stayed attuned to the paradox that his parents couldn't explain to him in his childhood.
- The professor brought the paradox in to explain intimacy.
- The theory takes in a famous paradox.
optimum [ˈɑptɪməm]: adj. adj. the best or most suitable for a particular purpose or in a particular situation最适宜的
- Don't get close to me, let's keep the optimum distance.
- There is no optimum answer about whether we should provide him with shelter.
- Tired of walkers' chase, the leader thought that the prison must have been the optimum shelter for them.
convoluted [ˈkɑnvəˌlutəd]: adj. complicated and difficult to understand费解的
- The question is so convoluted that even our best student hasn't answered it properly.
- He tried to ask the teacher about a convoluted question, which was taked as questioning.
- He deciced to solve the convoluted after he finished other questions.
disclosure [dɪsˈkloʊʒər]: n. a secret that someone tells people, or the act of telling this secret公开,披露
- The journalist related to the disclose of royal scandals was murdered in his apartment. 
- Beyond doubt, the journalist aimed at the disclosure of water pollution.
- The disclosure of the corruption led to his downfall.
--------------------
so far: 目前为止
- So far, we have received any money from our parents.
- So far, talking loudly in public is mistake in the educational setting.
- So far, the method have been used in the educational setting.
know with sth.: 熟悉某事
- Knowing with the trouble he ran into, we must be on the same page.
- We need a soldier who knows with the matter in forest.
- The boy who claimed to know with chess was defeated quickly.
look to do sth.: 期待做某事
- He is looking to foster intimacy with the girl who is betrothed to him.
- My cat is obviously looking to feast on snacks.
- These kids are looking to receive pocket money on New Year's Eve.
aim at sth.: 旨在于某事
- He makes an assumption that the headmaster used to aim at merge the two schools.
- He aims at working for Apple.
- The undergrad student who aimed at working for Apple committed suicide after his failure.
come over as adj.: 显得是...
- The answer comes over as difficult.
- The vessel that had 16 watertight compartment came over as unsinkable.
- The cat comes over as brave.
** sentence2
inmost [ˈɪnˌmoʊst]: adj. your inmost feelings, desires etc are your most personal and secret ones心底的
- He never has the idea of talking about his inmost secret.
- The other way around, he devoted himself to you because of his inmost love for you.
- You need to address your need, disclosing your inmost love for her. 
innermost [ˈɪnə(r)ˌməʊst]: adj. your innermost feelings, desires etc are your most personal and secret ones内心的
- Other than that, his innermost secret makes him scared of the authorities.
- The boy who gets educated in town is not likely to disclose his innermost love for the girl.
- The expression of our innermost love for our child varied in different contexts.
merge [mɜrdʒ]: v. if two things merge, or if one thing merges into another, you cannot clearly see them, hear them etc as separate things合并
- People in the town take the two hospitals for granted to be merged.
- The headmaster aimed at merging his school with another.
- There is a tiny chance that your company merges with your wife's.
desirable [dɪˈzaɪrəb(ə)l]: adj. formal something that is desirable is worth having or doing值得拥有的
- The robot that has been broken into small parts is still desirable.
- The seriousness that he expressed when he was occupied with his homework is desirable.
- After a few rounds, the boxer realized that the desirable victory was often not easy.
enmeshed [ɪnˈmeʃt] (in/with): v. adj. very involved in an unpleasant or complicated situation使陷入的
- The lady enmeshed in a marriage is often abused by her drunk husband.
- The policeman enmeshed in a serious car accident was asked to pay a large amount of damage compensation.
- There is a huge chance that they are being enmeshed in a trap.
paradox [ˈperəˌdɑks]: n. a situation that seems strange because it involves two ideas or qualities that are very different悖论
- The boy stayed attuned to the paradox that his parents couldn't explain to him in his childhood.
- The professor brought the paradox in to explain intimacy.
- The theory takes in a famous paradox.
optimum [ˈɑptɪməm]: adj. adj. the best or most suitable for a particular purpose or in a particular situation最适宜的
- Don't get close to me, let's keep the optimum distance.
- There is no optimum answer about whether we should provide him with shelter.
- Tired of walkers' chase, the leader thought that the prison must have been the optimum shelter for them.
convoluted [ˈkɑnvəˌlutəd]: adj. complicated and difficult to understand费解的
- The question is so convoluted that even our best student hasn't answered it properly.
- He tried to ask the teacher about a convoluted question, which was taken as questioning.
- He decided to solve the convoluted question after he finished the others.
disclosure [dɪsˈkloʊʒər]: n. a secret that someone tells people, or the act of telling this secret公开,披露
- The journalist related to the disclosure of royal scandals was murdered in his apartment. 
- Beyond doubt, the journalist aimed at the disclosure of water pollution.
- The disclosure of the corruption led to his downfall.
--------------------
so far: 目前为止
- So far, we haven't received any money from our parents.
- So far, talking loudly in public is mistaken in the educational setting.
- So far, the method has been used in the educational setting.
know with sth.: 熟悉某事
- Knowing with the trouble he ran into, we must be on the same page.
- We need a soldier who knows with the maze.
- The boy who claimed to know with his opponent was defeated quickly.
look to do sth.: 期待做某事
- He is looking to foster intimacy with the girl who is betrothed to him.
- My cat is obviously looking to feast on snacks.
- These kids are looking to receive pocket money on New Year's Eve.
aim at sth.: 旨在于某事
- He makes an assumption that the headmaster used to aim at merging the two schools.
- He aims at a post for Apple.
- The undergrad student who aimed at a post for Apple committed suicide after his failure.
come over as adj.: 显得是...
- The answer comes over as difficult.
- The vessel that had 16 watertight compartments came over as unsinkable.
- The cat comes over as brave.
