#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-4 4.22 Stability or Excitement?
#+begin_verse
Okay, so we're talking about how people spend time together
	and how it ultimately impacts a relationship,
		and hopefully will serve a purpose to make the relationship enjoyable for both parties.
But as I see it, you can kind of fall on any part of the spectrum, right?
So, on one end of the spectrum,
	we have people who maybe are just kind of looking for that sense of security, or stability maybe?
And they're not necessarily looking for excitement
	and kind of lots of crazy challenging experiences with their partner, right?
	
Yeah, of course, I'm sort of biased towards the other [LAUGH] end of the spectrum.
But let us start with the couple who sort of like wanting to have more stability.
And not necessarily security, but we can say that too.
Very often, when people stay in long-term stable relationships,
	they may sometimes also have like special events, memorable moments.
But then some of the people would just enjoy doing certain things.
I remember when I was small,
	I used to watch a TV show and that was like,
		and then every episode started off with this couple having breakfast at the breakfast table.
And I was going like, is that even real? you know?
But then, that's just me.
But later on I find out
	things like that can actually deliver a sense of order, a sense of stability.
And people feel very comfortable and then they think, things are like that.
And I have actually spoken to even very young people, contemporary young people,
	who tell me that well you know, this is what I'm looking forward to.
I just want to go home to this person that I know well,
	and after a long day, I don't really need to do anything special.
I just need to have some place to go to.
And there's someone there who I know loves me,
	and that person doesn't really have to do anything special, just be there for me, right?
And that can be very reassuring, it can be very attractive.
And then I have actually seen people
		who have chosen that over a more eventful, exciting relationship,
	because that may not be what they really want.
	
But for someone like me,
	who is constantly thinking that you should be growing, you should be changing,
		life is full of opportunities, and you should spend time and create new activities together.
Don't get bogged down with routines and you know, have a lot of happenings.
That is obviously a biased opinion, [LAUGH]right, that's my opinion.
But I think the important thing is for people to figure out what they really need,
	and be able to communicate with their partner so that they get what they need.
#+end_verse
** expression
serve [sɜrv]: v. to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应,提供
spectrum [ˈspektrəm]: n. a complete range of opinions, people, situations etc, going from one extreme to its opposite范围
memorable [ˈmem(ə)rəb(ə)l]: adj. very good, enjoyable, or unusual, and worth remembering值得纪念的,难忘的
deliver [dɪˈlɪvər]: v. to take goods, letters, packages etc to a particular place or person释放
reassuring [ˌriəˈʃʊrɪŋ]: adj. making you feel less worried or frightened SYN comforting安心的
--------------------
fall on sp./sth.: 落在某地/某事物
on one end of the spectrum: 在范围的一端
get bogged down with sth.: 陷入某事run into sth.
be biased towards sth./sb.: 偏向于某事/某人
** ch.
4-4 4.22 稳定还是兴奋？

好吧，我们今天讨论的是人们如何一起度过时光，以及这最终如何影响一段关系，目的是希望能让双方的关系变得愉快。
但我认为，实际上你可以处于这个光谱的任何一端，对吧？
在光谱的一端，我们有一些人可能只是寻求那种安全感，或者说是稳定感？
他们不一定在寻找兴奋，也不一定想要和伴侣经历许多疯狂且具有挑战性的事情，对吧？
当然，我可能更偏向光谱的另一端（笑）。
但我们从那些希望拥有更多稳定关系的情侣说起吧。
并不一定是安全感，但我们也可以这么说。
很常见的是，当人们处于长期稳定的关系中时，他们有时也会经历一些特别的事件和难忘的时刻。
但有些人则只是享受做一些特定的事情。
我记得小时候，我曾经看过一个电视节目，每一集的开头都有一对夫妻在早餐桌上吃早餐。
我当时就在想，这真的现实吗？你知道吗？
不过那是我个人的想法。
但后来我发现，像这样的事情确实能带来一种秩序感，一种稳定感。
人们会觉得非常舒服，然后他们就会觉得事情就是这样。
有时我甚至和一些非常年轻的当代人交谈，他们告诉我说：“你知道吗，我就是在期待这样的生活。”
“我只想回到那个我非常熟悉的人身边，在忙碌的一天之后，我不需要做什么特别的事。”
“我只需要有一个地方可以去。”
“那里有一个我知道爱我的人，而那个人不需要做任何特别的事情，只要在那儿陪着我就好。”
这可以带来很大的安慰，也可以非常吸引人。
我确实见过一些人选择了这种稳定的关系，而不是选择一个更有事件性、更加刺激的关系，因为他们可能并不真心想要那种东西。
但像我这样的人，总是认为你应该不断成长，你应该不断变化，生活充满了机会，你应该一起花时间，创造新的活动。
不要被日常琐事困住，要有更多的发生。
显然，这是一种有偏见的观点（笑），对吧？这是我的看法。
但我认为，最重要的是，人们要弄清楚自己真正需要什么，并能够与伴侣沟通，以确保他们能得到自己需要的东西。
** sentence
serve [sɜrv]: v. to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应,提供
- The soup served in line comes down to charity.
- The ship served as a souvenir used to fall to a infamous pirate.
- The relationship will serve a purpose for you to pursue.
spectrum [ˈspektrəm]: n. a complete range of opinions, people, situations etc, going from one extreme to its opposite范围
- The ethnic spectrum of America fits into well in the control of our government.
- The ethnic spectrum of America is being broken now.
- The adorable animal becomes popular with the ethnic spectrum of America.
memorable [ˈmem(ə)rəb(ə)l]: adj. very good, enjoyable, or unusual, and worth remembering值得纪念的,难忘的
- It is a memorable event in which we express appreciation to each other.
- It is a memorable experience in which we first go out together.
- It is a memorable experience in which I sit next to an eminent boxer.
deliver [dɪˈlɪvər]: v. to take goods, letters, packages etc to a particular place or person释放
- Going off his wife, he delivered a sense of insecurity.
- The tree traced back to a thousand years ago delivered a sense of order.
- You succeeded in getting the squirrel to deliver a signal.
reassuring [ˌriəˈʃʊrɪŋ]: adj. making you feel less worried or frightened SYN comforting安心的
- I am reassuring, for our headmaster is committed to the air conditioners.
- In my sense, you should be reassuring because of the promise I made.
- Whether your wife is reassuring is up to your words.
--------------------
fall on sp./sth.: 落在某地/某事物
- With an apple falling on the ground, the scientist worked through the puzzle that had confused formers for hundreds of years.
- My wife asked to pick up the apple that fell on the ground.
- The apple falling on the ground may be poisonous.
on one end of the spectrum: 在范围的一端
- On one end of the spectrum, people violently refused anyone who tries to free them.
- On one end of the spectrum, some people are unwilling to sacrifice their money for an operation.
- On one end of the spectrum, some people give up what pertain to them.
get bogged down with sth.: 陷入某事run into sth.
- He must get bogged down with debt because of my request.
- The cat would get bogged down with traps in the forest.
- I get bogged down with dull routine after I got married.
be biased towards sth./sb.: 偏向于某事/某人
- My wife is biased towards our son, even if he makes some stupid mistakes.
- I am biased towards my wife, when she and my son quarrelled.
- She is biased towards the eminent lawyer who claimed to have fell love with her.
** sentence2
serve [sɜrv]: v. to give someone food or drink, especially as part of a meal or in a restaurant, bar etc供应,提供
- The soup served in line comes down to charity.
- The ship served as a souvenir used to fall to an infamous pirate.
- The relationship will serve a purpose for you to pursue.
spectrum [ˈspektrəm]: n. a complete range of opinions, people, situations etc, going from one extreme to its opposite范围
- The ethnic spectrum of America fits well in the control of our government.
- The ethnic spectrum of America is being broken now.
- The adorable animals become popular among the ethnic spectrum of America.
memorable [ˈmem(ə)rəb(ə)l]: adj. very good, enjoyable, or unusual, and worth remembering值得纪念的,难忘的
- It is a memorable event in which we express appreciation to each other.
- It is a memorable experience in which we first go out together.
- It is a memorable experience in which I sit next to an eminent boxer.
deliver [dɪˈlɪvər]: v. to take goods, letters, packages etc to a particular place or person释放
- Going off his wife, he delivered a sense of insecurity.
- The tree traced back to a thousand years ago delivered a sense of order.
- You succeeded in getting the squirrel to deliver a signal.
reassuring [ˌriəˈʃʊrɪŋ]: adj. making you feel less worried or frightened SYN comforting安心的
- Our headmaster who is committed to the air conditioners is reassuring.
- In my sense, you should be reassuring because of the promise I made.
- Whether your wife is reassuring is up to your words.
--------------------
fall on sp./sth.: 落在某地/某事物
- With an apple falling on the ground, the scientist worked through the puzzle that had confused formers for hundreds of years.
- My wife asked to pick up the apple that fell on the ground.
- The apple falling on the ground may be poisonous.
on one end of the spectrum: 在范围的一端
- On one end of the spectrum, people violently refuse anyone who tries to free them.
- On one end of the spectrum, some people are unwilling to sacrifice their money for an operation.
- On one end of the spectrum, some people give up what pertains to them.
get bogged down with sth.: 陷入某事run into sth.
- He must get bogged down with debt because of my request.
- The cat would get bogged down with traps in the forest.
- I got bogged down with a dull routine after I got married.
be biased towards sth./sb.: 偏向于某事/某人
- My wife is biased towards our son, even if he makes some stupid mistakes.
- I was biased towards my wife when she and my son quarreled.
- She is biased towards the eminent lawyer who claimed to have fell love with her.
