#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 4-4 4.20 To Grow or Not to Grow?
#+begin_verse
One of my mentors when I was in grad school told me that growth is treason
	because like when you grow, you become different
		and what you want, >> Yeah. what committed you, you may not be committed to that again.
And like one story that I love to share with people is you know like how young children,
	when they want to express their love or appreciation or gratitude for their caregiver,
	it can be like a parent or someone else.
Say for example is that in this stage
	the child is really fascinated with trains or buses or airplanes or whatever, right?
The child may be telling his caregiver, you're so nice to me.
When I grow up, I’ll buy you an airplane.
At that point in this child's life, he or she is like 100% honest, committed to that statement.
Had he or she got the capacity,
	this child might actually give you an airplane, or bus, or train, right?
That'd be really cool.
Yeah, but then the thing is,
	when this child grows up, he realizes I can not really afford to buy you an airplane, too.
It may not be the best way to express my love for you, right?
Maybe I should do something else.
Maybe I should find you a comfortable nursing home, right?
So, the person changes and the commitment and the promises do not necessarily hold.

So as we grow and change, this is what a good relationship should enhance,
	but some people are so afraid of change that they don't want their partner to grow.
They don't want their partner to change, right, so they do whatever to keep their partner the same.
So is that good or is that bad? Right?
Some people actually prefer stability.
I've actually seen couples like that.
They do not change.
They do not necessarily grow, in my sense of the word, but they're happy, right?
They keep the same stable, simple relationship that they have
	and they support each other and they sort of happy where they are.
Who am I to judge that is not an ideal relationship?

But if you ask me, I would say you know, I personally would prefer seeing people growing.
Another big name in psychology,
	Carl Rogers actually has this idea
		that I think he probably got inspired by the theologian Paul Tillich.
He talks about relationship as something that should get people to keep growing
	and if you find yourself in a relationship that is not helping you grow,
		you should probably leave that relationship, right.
That's probably a pretty extreme position to take and >> Right.
I kind of resonate with that but I am very conscious that not everyone needs to do that.
So, how much growth and how much change you want to achieve in your relationship with someone,
	and whether you think an intimate relationship should enhance that, again,
		is up to the individual.
#+end_verse
** expression
mentor [ˈmentər]: n. an experienced person who advises and helps a less experienced person导师
treason [ˈtriz(ə)n]: n. the crime of being disloyal to your country or its government, especially by helping its enemies or trying to remove the government using violence ⇨ treachery背叛
caregiver [ˈkerˌɡɪvər]: n. someone who takes care of a child or sick person看护人
--------------------
be committed to sth./doing sth.: 承诺做某事
in my sense: 在我看来
be up to sb.: 取决于某人
** ch.
4-4 4.20 成长还是不成长？

当我还是研究生的时候，我的一位导师告诉我，成长是一种背叛。因为当你成长时，你会变得不同，你的追求和承诺可能会发生变化，甚至不再坚持最初的承诺。

我特别喜欢和人们分享一个故事，就是关于小孩子如何表达他们对照顾者的爱、感激或感恩。照顾者可以是父母，也可以是其他人。比如说，在某个阶段，这个孩子特别喜欢火车、公共汽车或飞机等交通工具。于是，孩子可能会对他的照顾者说：“你对我这么好，将来我长大了会给你买一架飞机。”

在孩子生命中的这个阶段，他（或她）是百分之百诚实且真心承诺这句话的。如果他（或她）有能力，这个孩子真的可能会送你一架飞机、公共汽车或者火车，对吧？那会很酷。然而，问题是，当这个孩子长大后，他意识到，实际上我可能买不起飞机。而且，这也许并不是表达我对你的爱最好的方式。也许我应该做一些其他的事情，比如给你找一家舒适的养老院，对吧？

所以，随着人们成长和变化，承诺和许诺不一定会维持不变。一个好的关系应该促进这种成长和变化，但有些人非常害怕改变，他们不希望伴侣成长或改变。因此，他们会尽一切努力让伴侣保持原样。那么，这种做法是好是坏呢？

有些人其实更喜欢稳定。我确实见过一些情侣，他们不改变，也不按我的理解去“成长”。但是他们很幸福。他们保持着同样稳定而简单的关系，互相支持，并满足于自己的现状。谁又有资格去评判那不是一种理想的关系呢？

但如果你问我，我会说，我个人更希望看到人们成长。心理学中的另一位大人物，卡尔·罗杰斯（Carl Rogers），实际上提出过一个观点——我觉得他可能受到神学家保罗·蒂利希（Paul Tillich）的启发。他认为，关系应该是让人不断成长的。如果你发现自己处在一个无法帮助你成长的关系中，你可能应该离开那个关系。

这是一个相当极端的立场。我有点认同这一点，但我也非常清楚，并不是每个人都需要这样。那么，在一段关系中，你想要多少成长和变化，或者你是否认为亲密关系应该促进这种成长，归根结底是个人的选择。
** sentence
mentor [ˈmentər]: n. an experienced person who advises and helps a less experienced person导师
- Our mentor is striking towards the fund of our experiments.
- You can ask our mentor to keep the secret all the time.
- Tied down by his mentor, the undergrad student chose to quit the school.
treason [ˈtriz(ə)n]: n. the crime of being disloyal to your country or its government, especially by helping its enemies or trying to remove the government using violence ⇨ treachery背叛
- So far we can't judge whether what he has done is treason.
- Knowing with your treason, the king ordered me to cut your throat.
- The crowd looks to kill the lord who committed treason.
caregiver [ˈkerˌɡɪvər]: n. someone who takes care of a child or sick person看护人
- Obviously, he is a caregiver who is aiming at providing his child with best education.
- It comes over as convoluted from a caregiver's perspective.
- As a caregiver, I am trapped in times of difficulty.
--------------------
be committed to sth./doing sth.: 承诺做某事
- He was committed to finishing the house chore before we arrive home.
- I was commited to taking care of my girlfriend.
- The girl was commited to feeding her cat every day.
in my sense of sth.: 以我对某事/某物的理解
- In my sense of my wife, she will yell at me if I tell her the truth.
- In my sense of my sibling, he is unwilling to share his apartment with you.
- In my sense of my wife, she has never given me a quiet environment in which I can study carefully.
be up to sb.: 取决于某人
- Whether I can study English longer is up to my wife, which disgusts me a great deal.
- The price of real estate is up to the market, not to me.
- Whether they sack the castle is up to you, who keep a treasure map in hide.
** sentence2
mentor [ˈmentər]: n. an experienced person who advises and helps a less experienced person导师
- Our mentor is striking towards the fund of our experiments.
- You can ask our mentor to keep the secret all the time.
- Tied down by his mentor, the undergrad student chose to quit the school.
treason [ˈtriz(ə)n]: n. the crime of being disloyal to your country or its government, especially by helping its enemies or trying to remove the government using violence ⇨ treachery背叛
- So far we can't judge whether what he has done is treason.
- Knowing with your treason, the king ordered me to cut your throat.
- The crowd looks to kill the lord who committed treason.
caregiver [ˈkerˌɡɪvər]: n. someone who takes care of a child or sick person看护人
- Obviously, he is a caregiver who is aiming at providing his child with the best education.
- It comes over as convoluted from a caregiver's perspective.
- As a caregiver, I am trapped in times of difficulty.
--------------------
be committed to sth./doing sth.: 承诺做某事
- He was committed to finishing the house chores before we arrived home.
- I was committed to taking care of my girlfriend.
- The girl was committed to feeding her cat every day.
in my sense: 在我看来
- In my sense, my wife will yell at me if I tell her the truth.
- In my sense, my sibling is unwilling to share his apartment with you.
- In my sense, my wife has never given me a quiet environment in which I can study carefully.
be up to sb.: 取决于某人
- Whether I can study English longer is up to my wife, which disgusts me a great deal.
- The price of real estate is up to the market, not to me.
- Whether they sack the castle is up to you, who keeps a treasure map in hiding.
