#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.6 Mutual Needs
#+begin_verse
Professor Tsang, you bring up a point about
	how some transformations might be negative but others can be positive
		and then maybe others just sort of are neither or fall in between.
So, whether it's positive or negative, what are some of those key learning points
	that we want to take home to understand transformations and relationships?
Well, following the SSLD logic that we enter the relationships
	because there are needs that we wish to address through those relationships.
The key idea still is are our needs being met?

So when a relationship is going through transformation and change right
	in an ideal situation it's that both parties or all parties involved in that relationship
			would be looking after his or her own needs as well as the mutual collective needs.
But we understand that it is not always possible
	like in a hostile breakup or divorce, separation situation, then it is not possible.
But in a lot of transformation situations,
	it actually is possible, and it's actually almost like central to the idea.
Say for example if people're making the transformation
	from you know being acquaintances to being lovers or friends to being business partners.
That is like a transformation that they have to go through.
And going through an explict process of like negotiating what is the best arrangement
	so that our respective needs would be met would be the best thing to do.
#+end_verse
** expression
positive [ˈpɑzətɪv]: adj. if you are positive about things, you are hopeful and confident, and think about what is good in a situation rather than what is bad OPP negative积极的
acquaintance [əˈkweɪntəns]: n.  someone you know, but who is not a close friend熟人
exquisite [ˈekskwɪzɪt]: adj. extremely beautiful and very delicately made精致的
respective [rɪˈspektɪv]: adj. used before a plural noun to refer to the different things that belong to each separate person or thing mentioned分别的, 各自的
--------------------
bring up sth.: 提出某事
look after sb.: 照顾某人
** ch.
5-1 5.6 互相需求
曾教授，您提到了一点，即某些转变可能是负面的，但也有可能是正面的，还有一些可能既不是正面也不是负面，或者介于两者之间。
那么，不论是正面还是负面，我们有哪些关键的学习点可以帮助我们更好地理解转变和关系呢？
根据SSLD的逻辑，我们进入关系是因为我们希望通过这些关系满足某些需求。
核心思想仍然是：我们的需求是否得到了满足？
当关系经历转变和变化时，在理想情况下，关系中的双方或所有参与者都能够关注自己的需求以及共同的集体需求。
但我们也明白，这并不总是可能的，比如在充满敌意的分手或离婚、分居情况下，这是无法实现的。
然而，在许多转变的情境中，这实际上是可能的，而且几乎是核心理念的一部分。
例如，人们从认识到成为恋人，或者从朋友到成为商业伙伴。
这是一种他们必须经历的转变。
在这种情况下，经历一个精细的过程，比如协商出最佳安排，以确保我们各自的需求得到满足，这是最好的做法。
** sentence
positive [ˈpɑzətɪv]: adj. if you are positive about things, you are hopeful and confident, and think about what is good in a situation rather than what is bad OPP negative积极的
- When we were running out of my money to buy the apartment, my wife was positive about the life in the future.
- Positive emotions are spreading through news about the victories on the battlefield.
- The boy who develops fevers is still positive about his illness.
acquaintance [əˈkweɪntəns]: n.  someone you know, but who is not a close friend熟人
- One of my acquaintances is bearing scars and scabs throught the rest of his life after he has had smallpox.
- One of my acquaintances spread the news on the battlefield to our village.
- One of my acquaintances told me a story about how these nomads devastated a civilization by gunpowder.
exquisite [ˈekskwɪzɪt]: adj. extremely beautiful and very delicately made精致的
- The exquisite kind of watches made its way around the world via these merchants.
- There is an estimated 1000 to 2000 exquisite watches in the truck.
- The fall of the hero started because of an exquisite plot his twin brothers made for him.
respective [rɪˈspektɪv]: adj. used before a plural noun to refer to the different things that belong to each separate person or thing mentioned分别的, 各自的
- It begins all the way back when they didn't address respective needs during the divorce.
- The peasants of two villages grinded up respective wheat in secret to revenge each other.
- If we looked after respective children, we would be both happy.
--------------------
bring up sth.: 提出某事
- He brought up a point that his ex-wife had sex with others during their marriage.
- Why don't you bring up the issue that you raised in our conversation?
- My wife brought up an idea that we could keep a cat in our house.
look after sb.: 照顾某人
- Failing to look after his sister, he felt very guilt and was worried about his parents' complaints.
- If you look after my baby, I will give you 5 dollars.
- He was very joyful when he ran into the cat that he used to look after.
** sentence2
positive [ˈpɑzətɪv]: adj. if you are positive about things, you are hopeful and confident, and think about what is good in a situation rather than what is bad OPP negative积极的
- When we were running out of money to buy the apartment, my wife was positive about life in the future.
- Positive emotions are spreading through news about the victories on the battlefield.
- The boy who develops fevers is still positive about his illness.
acquaintance [əˈkweɪntəns]: n.  someone you know, but who is not a close friend熟人
- One of my acquaintances is bearing scars and scabs through the rest of his life after he had smallpox.
- One of my acquaintances spread the news on the battlefield to our village.
- One of my acquaintances told me a story about how these nomads devastated a civilization by gunpowder.
exquisite [ˈekskwɪzɪt]: adj. extremely beautiful and very delicately made精致的
- The exquisite kind of watches made its way around the world via these merchants.
- There are an estimated 1000 to 2000 exquisite watches in the truck.
- The fall of the hero started because of an exquisite plot his twin brothers made for him.
respective [rɪˈspektɪv]: adj. used before a plural noun to refer to the different things that belong to each separate person or thing mentioned分别的, 各自的
- It begins all the way back when they didn't address their respective needs during the divorce.
- The peasants of two villages ground up respective wheat in secret to revenge each other.
- If we looked after our respective children, we would be both happy.
--------------------
bring up sth.: 提出某事
- He brought up a point that his ex-wife had sex with others during their marriage.
- Why don't you bring up the issue that you raised in our conversation?
- My wife brought up the idea that we could keep a cat in our house.
look after sb.: 照顾某人
- Failing to look after his sister, he felt very guilty and was worried about his parents' attitudes.
- If you look after my baby, I will give you 5 dollars.
- He was very joyful when he ran into the cat that he used to look after.
