#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 5.1 Culture, History, and Technology
#+begin_verse
Okay, and kind of when we're talking about especially these time-limited relationships,
	culturally do they kind of translate differently and look a little different
		depending on where the context is taking place?
Yeah I think so, like I think depending on the culture, right? Certain kinds of working together.
Say for example, if you serve in the Army together,
	it is very different than you in the same sales team together
		or you're in the same data processing pool together, right?
So certain relationships tend to engender a more intense bonding, right?

And then in some cultures, say for example,
	in East Asian cultures, if you have a relationship with your teacher,
		that can sometimes turn into a lifetime relationship.
People may start it off being teacher and student
	and then after the program has completed, the person has graduated,
	they can continue on in this teacher-mentor kind of relationship for a long time.
That is sort of like more common and more encouraged in East Asian cultures.
I believe there might be other cultures in other parts of world that do that too
	in comparison to what is the typical situation here in North America or in Europe.
		
So yeah, I know I'm over-generalizing
	but there are obviously some cultural patterns that would be associated with,
		you know, certain relationship like tending to stay for longer.
We can also say the same thing almost about marriage
	because in some cultures, they make it very difficult for people to divorce.
Some cultures actually would basically make it not possible, almost to divorce legally.
So in those cultures, changing the very nature of the relationship would be more challenging.
But I believe that relationships would still be transformed when people move through those phases.
#+end_verse
** expression
engender [ɪnˈdʒendər]: v. formal to be the cause of a situation or feeling造成
intense [ɪnˈtens]: adj. having a very strong effect or felt very strongly强烈的
lifetime [ˈlaɪfˌtaɪm]: n. the period of time during which someone is alive or something exists ⇨ lifespan一生
typical [ˈtɪpɪk(ə)l]: adj. having the usual features or qualities of a particular group or thing典型的
generalize [ˈdʒen(ə)rəˌlaɪz] overgeneralize: v. to form a general principle or opinion after considering only a small number of facts or examples概括
--------------------
take place: 发生
** ch.
5-1 5.1 文化、历史与技术

好的，当我们谈论尤其是这些有时间限制的关系时，文化上它们是否会根据发生的环境有所不同，看起来有点不一样？
是的，我认为是的，取决于文化，对吧？
有些合作方式，比如举个例子，如果你们一起服役于军队，这和你们在同一个销售团队，或者在同一个数据处理小组工作是完全不同的，对吧？
所以某些关系往往会激发更强烈的情感纽带，对吧？
然后在一些文化中，比如东亚文化，如果你和你的老师有一种关系，这种关系有时可以转变成一生的关系。
人们可能一开始是师生关系，之后课程结束，学生毕业后，他们可以继续保持这种师徒关系，可能会维持很长时间。
这种情况在东亚文化中更为常见，而且更为鼓励。
我相信在世界其他地方也可能有类似的文化，和北美或欧洲的典型情况相比。
所以，是的，我知道我有些过于泛化，但显然有一些文化模式与某些关系的延续有关，比如更倾向于保持更长时间。
我们几乎也可以对婚姻说同样的话，因为在某些文化中，他们让离婚变得非常困难。
一些文化甚至基本上让离婚几乎不可能，从法律上讲几乎无法离婚。
所以在这些文化中，改变这种关系的本质会更加具有挑战性。

但我相信，即使如此，关系还是会在不同阶段之间发生转变。
** sentence
engender [ɪnˈdʒendər]: v. formal to be the cause of a situation or feeling造成
- Drawing on these mobs engenders bitterly quarrels with natives.
- The difference between two ancient religions engendered a civil war.
- The tree inhabited by these nomads engendered the forest fire.
intense [ɪnˈtens]: adj. having a very strong effect or felt very strongly强烈的
- The intense sense of insecurity made me fear a lot.
- The wind is so intense that I almost can't close the door.
- I had the intense feeling of affiliation when I first came to this country.
lifetime [ˈlaɪfˌtaɪm]: n. the period of time during which someone is alive or something exists ⇨ lifespan一生
- In East Asian culture, the relationship between teacher and student sometimes can be a lifetime relationship.
- Being unable to work for Apple is my lifetime sore.
- The relationship between you and your girlfriend is more like time-limited than lifetime.
typical [ˈtɪpɪk(ə)l]: adj. having the usual features or qualities of a particular group or thing典型的
- What you portrayed is a typical monster in mythical realms.
- This is a typical creature surviving at extreme of salinity.
- He is a typical student who gets used to play truant from school.
generalize [ˈdʒen(ə)rəˌlaɪz] overgeneralize: v. to form a general principle or opinion after considering only a small number of facts or examples概括
- My wife tends to generalize from my little mistakes to all stuffs.
- The scientist is going out of his way to generalize from the results of experiments.
- My teacher asked me to generalize from these questions.
--------------------
take place: 发生
- No matter what you regret, it took place and caused a series of catastrophes.
- If anything else takes place, you should send the signal and we will arrive in time after seeing that.
- He posits that I am the usurper since the coup took place.
** sentence2
engender [ɪnˈdʒendər]: v. formal to be the cause of a situation or feeling造成
- Drawing on these mobs engenders bitter quarrels with natives.
- The difference between the two ancient religions engendered a civil war.
- The tree inhabited by these nomads engendered the forest fire.
intense [ɪnˈtens]: adj. having a very strong effect or felt very strongly强烈的
- The intense sense of insecurity made me fear a lot.
- The wind is so intense that I almost can't close the door.
- I had an intense feeling of affiliation when I first came to this country.
lifetime [ˈlaɪfˌtaɪm]: n. the period of time during which someone is alive or something exists ⇨ lifespan一生
- In East Asian culture, the relationship between teacher and student sometimes can be a lifetime relationship.
- Being unable to work for Apple is my lifetime sore.
- The relationship between you and your girlfriend is more like time-limited than lifetime.
typical [ˈtɪpɪk(ə)l]: adj. having the usual features or qualities of a particular group or thing典型的
- What you portrayed is a typical monster in mythical realms.
- This is a typical creature surviving at extremes of salinity.
- He is a typical student who gets used to playing truant from school.
generalize [ˈdʒen(ə)rəˌlaɪz] overgeneralize: v. to form a general principle or opinion after considering only a small number of facts or examples概括
- My wife tends to generalize from my little mistakes to all stuff.
- The scientist is going out of his way to generalize from the results of experiments.
- My teacher asked me to generalize from these questions.
--------------------
take place: 发生
- No matter what you regret, it took place and caused a series of catastrophes.
- If anything else takes place, you should send the signal and we will arrive in time after seeing that.
- He posits that I am the usurper since the coup took place.
