#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-1 Overview of Module 5
#+begin_verse
So as we know from previous sessions, people really do change.
And as we grow and develop within a relationship,
	we have to find ways to transform that relationship
		in order to make sure that is mutually gratifying for both parties.
So in this session,
	one of the things we're going to be talking about are some of the strategies and methods
		that we can use in order to help transform relationships.
But before we even get there, Dr. Tsang,
	maybe you can explain what kind of relationships would need to be transformed.
	
That's a good question.
I think the tempting answer would be every relationship, right?
[LAUGH] But like we also talk about people
	who would prefer to keep a relationship for a long time
		without necessarily making any significant change to them.
Those relationships do exist and they are valued by some people.
So I guess there might be some relationships that do not necessarily need drastic transformation.
But even with those I would add that
	like it might not be a bad idea to be checking in every now and then
		to make sure that the relationship is actually working.
And this is why we always emphasize good communication between the partners in any relationship.
But other than that I would say most relationships would go through some kind of transformation.

If you think of a sort of like normal socially scripted relationship in the Western world,
	it would be like people who met and dated and you know, decided to be together.
They might go through a phase of engagement.
Some people would start living together for a while.
And then maybe they get married or they don't but they stay together.
Some people would like decide to have children and raise a family.
Some people don't.
And then the feeling, the mode of interaction, and the kind of things that they do together,
	I believe, would change, right?
So even if we're talking about like personal significant relationship
		that is supposed to last for a long time,
	there would be changes.
	
And then of course there are relationships that are by nature time-limited,
	like the friends you have at kindergarten, [LAUGH] or elementary school or high school or college,
	your relationship with your teachers, your ballet instructor, or whoever.
And people that you work with, like if you work in a company and your coworkers,
	your relationship with them would last for so long, right.
And then your relationship with your teachers, and you know, maybe even other family members.
And then the current state of family life,
	and you know that there are people that you're connected with through marriage.
And then all of a sudden your cousin, or your brother, or your sister gets divorced
	and then you're no longer related to these people in the same way.
So, those relationships would change, right?
So, there are all sorts of transformations that we can imagine.
#+end_verse
** expression
previous [ˈpriviəs]: adj. having happened or existed before the event, time, or thing that you are talking about now以前的
session [ˈseʃ(ə)n]: n. a period of time used for a particular activity, especially by a group of people阶段(一段时间)
tempting [ˈtemptɪŋ]: adj. something that is tempting seems very good and you would like to have it or do it诱惑人的
engagement [ɪnˈɡeɪdʒmənt]: n. an agreement between two people to marry, or the period of time they are engaged约会,订婚
time-limited [taɪm] [ˈlɪmɪtəd]: adj. 有时间限制的
kindergarten [ˈkɪndərˌɡɑrd(ə)n]: n. a school or class for children aged five幼儿园
instructor [ɪnˈstrʌktər]: n. someone who teaches a sport or practical skill教练
coworker ['kəʊˌwɜːkə]: n. someone who works with you and has a similar position SYN colleague同事
cousin [ˈkʌz(ə)n]: n. the child of your ↑uncle or ↑aunt ⇨ ↑first cousin, ↑kissing cousin, SECOND COUSIN堂兄弟姊妹, 表兄弟姊妹
--------------------
add that + ...: 补充+...
by nature: 自然地
** ch.
5-1 模块概览
正如我们从之前的课程中了解到的，人们确实会发生变化。
当我们在一段关系中成长和发展时，我们必须找到方法来转变这段关系，以确保双方都能从中获得满足感。
在这一课中，我们将讨论一些我们可以用来帮助转变关系的策略和方法。
但在我们深入探讨之前，曾博士，也许您可以解释一下，哪些类型的关系需要转变呢？
这是个好问题。我想诱人的回答是所有关系都需要改变，对吧？[笑]
但我们也讨论过一些人可能希望保持一段关系很长时间，而不一定要对其做出重大改变。
这种关系确实存在，并且对某些人来说非常重要。
所以，我猜也有一些关系可能不需要彻底的转变。
但即便是那些关系，我也认为定期检查一下，确保关系真正运作良好，并不是一个坏主意。
这就是为什么我们总是强调任何关系中伴侣之间要有良好的沟通。
除此之外，我会说，大多数关系都会经历某种形式的转变。
如果你想到西方社会中的常见社会化关系，可能是像人们相识、约会、决定在一起。
他们可能会经历一段订婚的阶段。有些人会开始同居一段时间。
然后他们可能结婚，或者不结婚但继续在一起。有些人可能决定生孩子并养育家庭，有些人则不这么做。
然后他们的互动方式、彼此之间的感觉以及共同做的事情，我相信都会发生变化，对吧？
所以即使我们谈论的是那些本应维持很长时间的个人重要关系，它们也会发生变化。
当然，也有一些关系本质上是有限时效的，比如你在幼儿园时的朋友，[笑] 或小学、高中、大学的朋友，
你与老师的关系、芭蕾舞导师的关系等等。
还有你工作中的人际关系，比如你在公司里工作的同事，你与他们的关系只会持续一段时间，对吧？
然后是你与老师的关系，甚至可能是你与其他家庭成员的关系。
再比如当前家庭生活的状况，你知道有些人通过婚姻与他人建立了联系。
然后突然间，你的表兄、哥哥或姐姐离婚了，你与这些人的关系也不再是原来的那种方式。
这些关系会发生变化，对吧？
所以，我们可以想象到各种各样的转变。
** sentence
previous [ˈpriviəs]: adj. having happened or existed before the event, time, or thing that you are talking about now以前的
- He behaved as having met me on a previous occassion.
- The previous experiment we performed didn't agree on the theory.
- It's not that I have met you on a previous occassion, it's that you become popular with people in our town.
session [ˈseʃ(ə)n]: n. a period of time used for a particular activity, especially by a group of people阶段(一段时间)
- There is a certain probability of passing test through the training session.
- I am 95% sure of passing test through that training session.
- He got familiar to cooking skills more or less in the training session.
tempting [ˈtemptɪŋ]: adj. something that is tempting seems very good and you would like to have it or do it诱惑人的
- It is tempting that the sales of this kind of clothes increases exponentially. 
- It is tempting for gay couples to adopt a child from China or Vietnam.
- It is tempting to take advantage of a weak man who takes raising family as granted.
engagement [ɪnˈɡeɪdʒmənt]: n. an agreement between two people to marry, or the period of time they are engaged约会,订婚
- The chance of my wife selling our engagement ring approaches zero.
- There is small, but non-zero probability that they will announce their engagement at the party.
- Waking up with a start, the vicar realized that there was an engagement waiting for him.
time-limited [taɪm] [ˈlɪmɪtəd]: adj. 有时间限制的
- The laboratory is so time-limited that we can only perform our experiment for a very short period of time.
- The relationship between you and your gross leader is time-limited.
- The ship we rent is time-limited, so we will be fined if we are late for returning.
kindergarten [ˈkɪndərˌɡɑrd(ə)n]: n. a school or class for children aged five幼儿园
- My son intends to interact with girls in the kindergarten.
- Our boss decided to surrender the kindergarten to the company because of our debts.
- The kindergarten was hit by a stone from out space.
instructor [ɪnˈstrʌktər]: n. someone who teaches a sport or practical skill教练
- Our instructor has been abducted by a student who he bullied.
- Our instructor enjoys telling our story about strange creatures in the universe.
- It is only within last century that ballet instructors receive a warm welcome in China.
coworker ['kəʊˌwɜːkə]: n. someone who works with you and has a similar position SYN colleague同事
- Our coworker is undertaking a new project about psychotherapy.
- Our coworkers are just the right distance from each other.
- My coworker is parading in front of the City Hall.
cousin [ˈkʌz(ə)n]: n. the child of your ↑uncle or ↑aunt ⇨ ↑first cousin, ↑kissing cousin, SECOND COUSIN堂兄弟姊妹, 表兄弟姊妹
- What my cousin has done in high school is fatal for his career.
- One of my cousins used to explore in the dark depths of the lake.
- My cousin often risks his life on the flanks of volcanoes.
--------------------
add that + ...: 补充+...
- The professer added that in most stiuation, a good negotiation and a good communication can maintain a transforming relationship.
- My wife added that we would go on a vacation at a seaside resort when we made enough money.
- I added that my cat was sitting in the boat and doing nothing.
by nature: 自然地 
- When someone asks how he is able to lose weight, he always tells he makes it by nature.
- He explained that he could speak English fluently by nature.
- He started exercising with a song by nature.
** sentence2
previous [ˈpriviəs]: adj. having happened or existed before the event, time, or thing that you are talking about now以前的
- He behaved as having met me on a previous occasion.
- The previous experiment we performed didn't agree with the theory.
- It's not that I have met you on a previous occassion, it's that you become popular with people in our town.
session [ˈseʃ(ə)n]: n. a period of time used for a particular activity, especially by a group of people阶段(一段时间)
- There is a certain probability of passing the test through the training session.
- I am 95% sure of passing the test through that training session.
- He got more or less familiar with cooking skills in the training session.
tempting [ˈtemptɪŋ]: adj. something that is tempting seems very good and you would like to have it or do it诱惑人的
- It is tempting that the sales of this kind of clothes increase exponentially. 
- It is tempting for gay couples to adopt a child from China or Vietnam.
- It is tempting to take advantage of a weak man who takes raising his family for granted.
engagement [ɪnˈɡeɪdʒmənt]: n. an agreement between two people to marry, or the period of time they are engaged约会,订婚
- The chance of my wife selling our engagement ring approaches zero.
- There is a small, but non-zero probability that they will announce their engagement at the party.
- Waking up with a start, the vicar realized that there was an engagement waiting for him.
time-limited [taɪm] [ˈlɪmɪtəd]: adj. 有时间限制的
- The laboratory is so time-limited that we can only perform our experiment for a very short period of time.
- The relationship between you and your gross leader is time-limited.
- The ship we rent is time-limited, so we will be fined if we are late for returning.
kindergarten [ˈkɪndərˌɡɑrd(ə)n]: n. a school or class for children aged five幼儿园
- My son intends to interact with girls in the kindergarten.
- Our boss decided to surrender the kindergarten to the company because of our debts.
- The kindergarten was hit by a stone from outer space.
instructor [ɪnˈstrʌktər]: n. someone who teaches a sport or practical skill教练
- Our instructor has been abducted by a student who he bullied.
- Our instructor enjoys telling our story about strange creatures in the universe.
- It is only within the last century that ballet instructors received a warm welcome in China.
coworker ['kəʊˌwɜːkə]: n. someone who works with you and has a similar position SYN colleague同事
- Our coworker is undertaking a new project about psychotherapy.
- Our coworkers are just the right distance from each other.
- My coworker is parading in front of the City Hall.
cousin [ˈkʌz(ə)n]: n. the child of your ↑uncle or ↑aunt ⇨ ↑first cousin, ↑kissing cousin, SECOND COUSIN堂兄弟姊妹, 表兄弟姊妹
- What my cousin has done in high school is fatal for his career.
- One of my cousins used to explore in the dark depths of the lake.
- My cousin often risks his life on the flanks of volcanoes.
--------------------
add that + ...: 补充+...
- The professer added that in most stiuation, a good negotiation and a good communication can maintain a transforming relationship.
- My wife added that we would go on a vacation at a seaside resort when we made enough money.
- I added that my cat was sitting in the boat and doing nothing.
by nature: 自然地 
- When someone asks how he is able to lose weight, he always answers he does it by nature.
- He explained that he could speak English fluently by nature.
- He started exercising with a song by nature.
