#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-2 5.8 Separation-Individuation 2
#+begin_verse
So your earlier examples were really focusing more on
	kind of a parent-child relationship and that form of separation individuation.
But the same concept is totally useful for understanding Intimate Partner Relationships.
Yes, absolutely.
I think I also mentioned that like in Intimate Partner Relationships,
	sometimes they can be like replicating very similar dynamics as like a parent-child relationship.
And when it goes through a separation and individuation process,
	because of the significance of the relationship.
		when part of it I would also attribute to Social Scripting
And you know like we tend to invest a lot in this kind of intimate relationship,
	because that's what society encourages us to do.
	
So in the extreme case and that you have a relationship
	in which one person is really dependent on the other person to meet his or her needs.
And I think an extreme example would be in an abusive relationship.
We know that there is this pattern.
Like it's not universal. But it happens a lot.
It's a dominating, controlling partner.
It can be like the typical cases,
	in the heterosexual relationship, the man is trying to control the woman.
You also find it in the same sex relationship as well.
Like the dominant partner is trying to control the less powerful partner.
And one of the things that the partner will do
	is to sort of like restrict the life space of this person
		so that you do not have opportunity
			to address your needs, to develop and grow outside of this relationship,
So like you're not allowed to see your friends.
Like you're discouraged from visiting your parents
		or you know having your own time with your girlfriends or whatever,
	and you have to like be home all the time.
And when I want to see you always be there.
So that is the kind of setup
	that basically reduces your chance of like having you needs met elsewhere, right.
And making it difficult for the abused partner to move that relationship.

But usually the kind of person who would do that
		also has some very strong, powerful needs for attention, affiliation
	and there is also a deep feel of abandonment or losing someone.
And this is why when the partner wants to leave, these people can actually become very angry.
Sometimes they can be very aggressive
	and they can be out of control and do impulsive things that they may even later regret.
So that is like a more dramatic scenario
	basically showing us like how two individuals are in a situation
		when their needs are met, by a, I would say, you know, dysfunctional arrangement.
		
And from the SSLD perspective, we believe that this situation is most effectively resolved
	when both parties can learn alternate ways of addressing their needs
		so that the needs will be met.
So that they do not have to like invest everything into this relationship
	and then one party will be like have more freedom
		to move out and do something and become separated and individuated.
And the other party would not feel so threatened and abandoned.
Because he or she can also be deriving gratification from other relationships.
#+end_verse
** expression
replicate [ˈreplɪˌkeɪt]: v. formal if you replicate someone’s work, a scientific study etc, you do it again, or try to get the same result again复制
abusive [əˈbjusɪv]: adj. using cruel words or physical violence辱骂的,虐待
heterosexual [ˌhetəroʊˈsekʃuəl]: adj. sexually attracted to people of the opposite sex SYN straight ⇨ bisexual, homosexual异性爱的
impulsive [ɪmˈpʌlsɪv]: adj. someone who is impulsive does things without considering the possible dangers or problems first ⇨ rash冲动的
scenario [səˈnɛrioʊ]: n. a situation that could possibly happen情景,情节
dysfunctional [dɪsˈfʌŋkʃən(ə)l]: adj. not working properly or normally OPP functional功能障碍的
alternate [ɔlˈtɜrnət]: adj. used to replace another thing of the same type SYN alternative交替的,备用的
--------------------
(a/this/that) form of sth.: 某物的形式
in the extreme case: 在极端情况下
outside of sth.: 除...之外
be discouraged from doing sth.: 不被鼓励做某事
have more freedom to do sth.: 有更多自由做某事
** ch.
所以你之前的例子主要是关注于一种亲子关系的分离-个体化过程。
但同样的概念完全适用于理解亲密伴侣关系。
是的，完全正确。
我也提到过，在亲密伴侣关系中，有时会复制出类似于亲子关系的动态。
而当关系经历分离-个体化的过程时，由于这种关系的重要性，它会变得更加复杂。
其中一部分我认为可以归因于社会脚本。
我们倾向于对这种亲密关系投入很多，因为社会鼓励我们这样做。
在极端情况下，可能会出现一方极度依赖另一方来满足自己的需求的关系。
一个极端的例子就是在虐待关系中。
我们知道，这种模式是存在的。
虽然不是普遍现象，但确实经常发生。
通常是一方占主导地位并控制另一方。
典型案例可能是异性恋关系中，男性试图控制女性。
但在同性关系中也可以看到类似的情况，
即占主导地位的一方试图控制较弱势的一方。
其中一种控制手段就是限制对方的生活空间，
让对方没有机会在关系之外满足自己的需求、发展和成长。
比如不允许对方见朋友，
劝阻对方去看望父母，
或者阻止对方与闺蜜相处的时间，
要求对方一直待在家里，
并且随时都要满足自己的需求。
这种安排基本上减少了受虐一方在关系之外满足需求的机会，
从而使得受虐一方很难摆脱这段关系。
通常会这样做的人本身也有很强烈的需求，
比如对关注和亲密关系的强烈渴望，
并且有深深的被抛弃或失去对方的恐惧。
因此，当伴侣想要离开时，
这些人可能会变得非常愤怒，
有时甚至会表现出极端的攻击性和失控行为，
做出一些冲动的事情，
甚至事后会感到后悔。
这是一种更具戏剧性的情境，
展现了两个个体如何在一种我称之为“功能失调”的关系安排中满足彼此需求。
从SSLD的角度来看，我们认为这种情况最有效的解决方式，
是让双方都学习到其他方式来满足自己的需求，
这样他们的需求可以得到满足，
而不需要把所有的一切都投入到这段关系中。
这样，一方可以有更多的自由去发展自己，完成分离-个体化的过程，
而另一方也不会感到极度受威胁或被抛弃，
因为他们也可以从其他关系中获得满足感。
** sentence
replicate [ˈreplɪˌkeɪt]: v. formal if you replicate someone’s work, a scientific study etc, you do it again, or try to get the same result again复制
- After deliberating at length over the process, the company succeeded in replicating the medication.
- Digging up the original design blueprint, the archaeologists go out their way to replicate the goddess statue.
- Staking the body to the coffin, these villagers replicated the ritual to mourn the dead.
abusive [əˈbjusɪv]: adj. using cruel words or physical violence辱骂的,虐待
- Getting divorce is only a normal symptom of an abusive relationship.
- The abusive marriage of which she can't get rid caused the lady to commit a murder.
- The relationship is abusive, in which his husband often forced out food through her mouth.
heterosexual [ˌhetəroʊˈsekʃuəl]: adj. sexually attracted to people of the opposite sex SYN straight ⇨ bisexual, homosexual异性爱的
- Once upon a time, there was a country in which heterosexual marriages were prohibited.
- Believe it or not, heterosexual relationships before marriage are prohibited in this country.
- The guy is born withering in the heterosexual relationship.
impulsive [ɪmˈpʌlsɪv]: adj. someone who is impulsive does things without considering the possible dangers or problems first ⇨ rash冲动的
- When you grow up, you won't do such thing impulsive that you regret later.
- I must confess that a quarter of my decisions are impulsive.
- The link between your marriage and his divorce is that you are both impulsive.
scenario [səˈnɛrioʊ]: n. a situation that could possibly happen情景,情节
- In practice, that form of scenarios is never going to happen.
- The moment he saw the scenario, he realized that the tables were turned.
- In that scenario, it is embarrassed to admit that I have a relationship with you.
dysfunctional [dɪsˈfʌŋkʃən(ə)l]: adj. not working properly or normally OPP functional功能障碍的,反常的
- You are like a chimpanzee with a dysfunctional machine gun.
- The machine gun that you held on in the public ceremony was dysfunctional.
- Whether the pills are dysfunctional when we get hurt is at stake.
alternate [ɔlˈtɜrnət]: adj. used to replace another thing of the same type SYN alternative交替的,备用的
- It doesn't worry me because I found an alternate way to get my homework finished.
- Independent from his parents, he has an alternate relationship with his girlfriend to meet his needs.
- Alternate jobs are not encouraged by our parents because of economy crises.
--------------------
(a/this/that) form of sth.: 某物的形式
- The article should be translate into Chinese taking the form of sentence by sentence.
- That form of romantic relationship is not what I desired in my youth.
- That form of social crises struck the authorities a great deal.
in the extreme case: 在极端情况下
- I will not exchange the necklace for food unless in the extreme case.
- This kidnappers might have killed those children in the extreme case.
- Some impulsive wives may turn in their husband in the extreme case.
outside of sth.: 除...之外
- The house should be neat outside of my bedroom before we come home.
- He carried everything to his house outside of the printer.
- Everyone was telling lies about the fraud outside the sincere girl.
be discouraged from doing sth.: 不被鼓励做某事
- I discouraged my wife from being intimate with my cousin.
- He has been discouraged from competing with his classmates in terms of clothes and shoes.
- The girl was dicouraged from marrying the lawyer because of his evil reputation.
have more freedom to do sth.: 有更多自由做某事
- You will have more freedom to achieve you dream if you take the 20,000 dollars.
- He has more freedom to choose his partner with a huge number of compensation.
- My wife will have more freedom to dance in our back courtyard.
** sentence2
replicate [ˈreplɪˌkeɪt]: v. formal if you replicate someone’s work, a scientific study etc, you do it again, or try to get the same result again复制
- After deliberating at length over the process, the company succeeded in replicating the medication.
- Digging up the original design blueprint, the archaeologists go out of their way to replicate the goddess statue.
- Staking the body to the coffin, these villagers replicated the ritual to mourn the dead.
abusive [əˈbjusɪv]: adj. using cruel words or physical violence辱骂的,虐待
- Getting a divorce is only a normal symptom of an abusive relationship.
- The abusive marriage of which she can't get rid caused the lady to commit a murder.
- The relationship is abusive, in which his husband often forces food out through her mouth.
heterosexual [ˌhetəroʊˈsekʃuəl]: adj. sexually attracted to people of the opposite sex SYN straight ⇨ bisexual, homosexual异性爱的
- Once upon a time, there was a country in which heterosexual marriages were prohibited.
- Believe it or not, heterosexual relationships before marriage are prohibited in this country.
- The guy is born withering in a heterosexual relationship.
impulsive [ɪmˈpʌlsɪv]: adj. someone who is impulsive does things without considering the possible dangers or problems first ⇨ rash冲动的
- When you grow up, you won't do such impulsive things that you regret later.
- I must confess that a quarter of my decisions are impulsive.
- The link between your marriage and his divorce is that you are both impulsive.
scenario [səˈnɛrioʊ]: n. a situation that could possibly happen情景,情节
- In practice, that form of scenario is never going to happen.
- The moment he saw the scenario, he realized that the tables were turned.
- In that scenario, it is embarrassed to admit that I have a relationship with you.
dysfunctional [dɪsˈfʌŋkʃən(ə)l]: adj. not working properly or normally OPP functional功能障碍的,反常的
- You are like a chimpanzee with a dysfunctional machine gun.
- The machine gun that you held in the public ceremony was dysfunctional.
- Whether the pills are dysfunctional when we get hurt is at stake.
alternate [ɔlˈtɜrnət]: adj. used to replace another thing of the same type SYN alternative交替的,备用的
- It doesn't worry me because I found an alternate way to get my homework finished.
- Independent from his parents, he has an alternate relationship with his girlfriend to meet his needs.
- Alternate jobs are not encouraged by our parents because of economic crises.
--------------------
(a/this/that) form of sth.: 某物的形式
- The article should be translated into Chinese taking the form of sentence by sentence.
- That form of romantic relationship is not what I desired in my youth.
- That form of social crisis struck the authorities a great deal.
in the extreme case: 在极端情况下
- I will not exchange the necklace for food unless in the extreme case.
- These kidnappers might have killed those children in the extreme case.
- Some impulsive wives may turn in their husbands in extreme cases.
outside of sth.: 除...之外
- The house should be neat outside of my bedroom before we come home.
- He carried everything to his house outside of the printer.
- Everyone was telling lies about the fraud outside the sincere girl.
be discouraged from doing sth.: 不被鼓励做某事
- I discouraged my wife from being intimate with my cousin.
- He has been discouraged from competing with his classmates in terms of clothes and shoes.
- The girl was discouraged from marrying the lawyer because of his evil reputation.
have more freedom to do sth.: 有更多自由做某事
- You will have more freedom to achieve your dreams if you take the 20,000 dollars.
- He has more freedom to choose his partner with a great deal of compensation.
- My wife will have more freedom to dance in our back courtyard.
