#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-2 5.9 How can we deal with each other's unmet needs?
#+begin_verse
With the interrelationship kind of how do we deal with that acknowledgment and needs not being met?
So yeah, this is the constant SSLD question, you know.
When things change, how do we address our needs within this changed context, right.
And we always talk about you know N3C.
So and when a relationship changes
	like we can be related to Like changes in the characteristics of one or both of the partners.
It can be also related to the change in the circumstances and it can also be like changing needs.
So what now we are dealing with is the last C,
	that is like building the capacity
		to negotiate these changes and the differences created by these changes.
So the key process still will a be very effective open direct communication.

Okay, with this open direct communication how is that effectively played out in our lives?
Well, first of all, we realized that the purpose is to communicate to the other party that one,
	I'm aware of certain changes have happened.
I am like wanting to do the best regarding our relationship,
	that can be, you know like negotiating a new pattern of interaction
		that is what we call a transformation,
And we can also be like communicating the fact that I want my needs to be met.
I am also respectful of the fact that your needs have to be addressed as well.
So we want to have like an open communication
	regarding how the two of us can work together, all right, to make modifications to relationship
		so that it would like be functional or helpful or beneficial to both of us.
So that is likely the general spirit and in order to do that,
A key principle is like when we're communicating,
	we focus on this intention of helping each other to understand our needs better
		and it's not an exercise in you know placing blame, and who has done wrong.
And like whether you owe me or you have done things to hurt me.
Try to stay away from the blaming and accusation.
Right.
But more focused on what are my needs, what are your needs.
#+end_verse
** expression
interrelationship [ˌɪntərɪˈleɪʃ(ə)nˌʃɪp]: n. a connection between two things that makes them affect each other相互关系
acknowledgment [əkˈnɑlɪdʒmənt]: n. the act of admitting or accepting that something is true承认,认知
modification [ˌmɑdɪfɪˈkeɪʃ(ə)n]: n. a small change made in something such as a design, plan, or system SYN alteration修改, 修正
--------------------
regarding sth.: 关于某事
be respectful of the fact that + ...: 尊重这个事实 + ...
stay away from sth./doing sth.: 远离某事/做某事
** ch.
如何处理彼此未满足的需求？
在这种相互关系中，我们如何处理这种认知和需求未被满足的问题呢？
所以，这就是不断的SSLD问题，你知道的。
当事情发生变化时，我们如何在这个变化的背景下处理我们的需求，对吧？
我们总是谈论N3C。
所以当一段关系发生变化时，它可能与一个或两个伴侣的特征变化有关，也可能与环境的变化有关，甚至可能是需求的变化。
所以现在我们处理的是最后一个C，即建立应对这些变化以及这些变化所带来的差异的能力。
所以关键的过程仍然是非常有效的、开放的直接沟通。
好的，在这种开放直接的沟通中，它如何在我们的生活中有效地体现出来呢？
首先，我们意识到，沟通的目的是让对方知道，首先，我意识到某些变化已经发生。
我是想尽力为我们的关系做得更好，这可以是，像协商一种新的互动模式。
如果那就是我们所说的转变，我们也可以传达这样的事实：我希望我的需求能够得到满足，我也尊重你的需求也必须得到关注。
所以我们想要进行开放的沟通，讨论我们俩如何一起合作，对关系进行调整，使其对我们俩都具有功能性、帮助性或有益性。
这个大致的精神和要做的事情就是这样的。
一个关键原则是，在沟通时，我们专注于帮助彼此更好地理解我们的需求，而不是进行责备和指责，或者讨论是谁错了，谁欠我什么，谁伤害了我。
尽量避免指责和控诉。
对吧？而是更多地关注：我的需求是什么，你的需求是什么。
** sentence
interrelationship [ˌɪntərɪˈleɪʃ(ə)nˌʃɪp]: n. a connection between two things that makes them affect each other相互关系
- With the interrelationship even the monarch can't establish a law prohibiting the rituals in countries.
- With the interrelationship both of the fossils would die down more quickly.
- With the interrelationship this kind execution that's brutal gradually died down.
acknowledgment [əkˈnɑlɪdʒmənt]: n. the act of admitting or accepting that something is true承认
- Your acknowledgment inspired main elements of his dream of being a lawyer.
- This acknowledgment enacts the age-old tradition of presenting pocket money to children on New Year's Eve.
- It is time to elaborate upon why he gained your acknowledgment.
modification [ˌmɑdɪfɪˈkeɪʃ(ə)n]: n. a small change made in something such as a design, plan, or system SYN alteration修改, 修正
- There is a tiny modification on the time of firework displays on New Year's Eve.
- The significant modification propelled the crused plane to the surface of the sea.
- It is your modification that cause the failure of the potion for immortality.
--------------------
regarding sth.: 关于某事
- The chemist was talking about regarding the potion for immortality.
- Regarding the disagreement with you and your brother even an eminent judge can't figure it out.
- Regarding how to go on a vacation at a seaside resort I must come up with the lack of money.
be respectful of the fact that + ...: 尊重这个事实 + ...
- She is respectful of the fact that her girl has individuated and become an own person.
- I am respectful of the fact that I don't get you out of the trouble.
- I am respectful of the fact that my father has to have an operation right now.
stay away from sth./doing sth.: 远离某事/做某事
- Staying away from me, you are such a pervert.
- Staying away from blaming, both of us settled down and nursed each other on the desert island.
- A wise king always stays away from a so-called potion for immortality.
** sentence2
interrelationship [ˌɪntərɪˈleɪʃ(ə)nˌʃɪp]: n. a connection between two things that makes them affect each other相互关系
- With the interrelationship, even the monarch can't establish a law prohibiting the rituals in countries.
- With the interrelationship, both of the fossils would die down more quickly.
- With the interrelationship, this kind of execution that's brutal gradually died down.
acknowledgment [əkˈnɑlɪdʒmənt]: n. the act of admitting or accepting that something is true承认
- Your acknowledgment inspired the main elements of his dream of being a lawyer.
- This acknowledgment enacts the age-old tradition of presenting pocket money to children on New Year's Eve.
- It is time to elaborate upon why he gained your acknowledgment.
modification [ˌmɑdɪfɪˈkeɪʃ(ə)n]: n. a small change made in something such as a design, plan, or system SYN alteration修改, 修正
- There is a tiny modification on the time of firework displays on New Year's Eve.
- The significant modification propelled the crushed plane to the surface of the sea.
- It is your modifications that mess all up.
--------------------
regarding sth.: 关于某事
- The chemist was talking about raw material regarding the potion for immortality.
- Regarding the disagreement with you and your brother even an eminent judge can't figure it out.
- Regarding how to go on a vacation at a seaside resort I must come up with the lack of money.
be respectful of the fact that + ...: 尊重这个事实 + ...
- She is respectful of the fact that her girl has individuated and become her own person.
- I am respectful of the fact that I don't get you out of trouble.
- I am respectful of the fact that my father has to have an operation right now.
stay away from sth./doing sth.: 远离某事/做某事
- Staying away from me, you are such a pervert.
- Staying away from blaming, both of us settled down and nursed each other on the desert island.
- A wise king always stays away from a so-called potion for immortality.
