#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-2 5.10 Aging - Part 1
#+begin_verse
So when we talk about people who are older or growing older in life.
Obviously, we will be looking at the changing N3C as well.
So like circumstances change, and you know, when people grow older, their needs will change, right.
Say for example, some of us will be needing assistance to just move around.
Some of us may even need help to address our basic physical needs for survival, you know.
So obviously not every aging person needs that.
Like some people can be very healthy and very active.
And not only can they take care of themselves, they can also take care of other people.
They may still continue to do wonderful things, creative things
		like making significant contribution to humankind,
	so there's a diversity of needs.
	
And in our society, we have this arrangement,
	which is also gradually being transformed itself, the institution of retirement, right?
So the concept itself is being redefined and you know, stretched.
But then we also understand that like people are going through some kind of transformation,
	like maybe you are working full time at a place, and then you become part time.
Or you stop working and you become self-employed, or you stop working.
Obviously your relationship with your co-workers would be transformed.
Mm-hm.
Right, like take me as an example.
I'm working in a university.
And if I stop doing this,
	then my relationship with my students and my co-workers, it will be changed.
So that is the kind of transformation that we expect.

What is like more challenging about this situation
	is that very often people do not understand the changing needs.
And then certain needs will therefore go neglected.
The couple of examples that I can give
	will be you know the need for the personal space, for your autonomy, for your agency,
		to assert itself, like taking risks for example.
In a lot of situations we encourage younger people to take risks.
Say for example, you have a toddler walking and falls.
The toddler will be encouraged to stand up and walk again.
You have a 90-year old person like walking and falls.
Then people will be encouraging him or her to use a wheelchair.
Right.
All right, so that is a very different understanding.
And young people can get into high risk or high impact sports,
	but if an older person wants to take risks with
			what he or she wants to do in a long-term care facility,
		that person usually is discouraged.
So some of the needs would be neglected.

Another big topic that I always talk about is the sexual and intimacy needs, right,
	which is one of the key topics that we are interested in this course.
And you know like older people also have like sexual needs and needs for intimacy,
	but those are usually not recognized.
Yeah, I think I feel like a lot of society doesn't believe that,
	you know, we become asexual once we've hit a certain age.
Or it's considered strange if you have, I don't know, sexual desires and that kind of thing, yeah.

So and then the other thing is
	other than that
		you find that because of the ageist discourse and practice that we have around us,
			like older people are usually scripted in sort of like a passive role.
You have like even TV commercials
	showing you know old people waiting around during Christmas for the family to visit
		or you know like waiting for grandchildren to call.
And they're expected to be thrilled when that happened.
And I think there is some systematic bias here, right,
	Imagining their lives to be without content, without fun.
And I believe that a lot can be done by society and also by the older people themselves
		to change that impression and also to enrich their lives
	so that you know the characteristics as older people
		will be positively valued rather than pathologized.
		
And then we also have to recognize that they have capacity that can be developed.
I have been like working a lot in the last few years with people with dementia.
And one of the things that I am fully convinced with many, many examples
	is that people even when they're diagnosed with dementia,
		many of these people can actually still continue to learn and develop.
Like when we are expected to think of them as generally deteriorating in all aspects of life,
	well, which do happen, right?
They do experience some deterioration or some decline in some functions.
But it doesn't mean that they cannot learn new stuff,
	and it doesn't mean that their lives cannot be enriched by doing things differently.
So I believe that the transformation, right, of their own condition
	and the relationship with the world can be reimagined.
#+end_verse
** expression
aging [ˈeɪdʒɪŋ]: n. the process of getting old变老
institution [ˌɪnstɪˈtuʃ(ə)n]: n. an important system of organization in society that has existed for a long time制度
toddler [ˈtɑdlər]: n. a very young child who is just learning to walk学走路的儿童
wheelchair [ˈhwilˌtʃer]: n. a chair with wheels, used by people who cannot walk轮椅
facility [fəˈsɪləti]: n. a place or building used for a particular activity or industry, or for providing a particular type of service场所
asexual [eɪˈsekʃuəl]: adj. technical not having sexual organs or not involving sex无性的
ageist [ˈeɪdʒɪst]: adj. treating older people unfairly because of a belief that they are less important than younger people歧视老年人的
discourse [ˈdɪsˌkɔrs]: n. a serious speech or piece of writing on a particular subject谈论
passive [ˈpæsɪv]: adj. someone who is passive tends to accept things that happen to them or things that people say to them, without taking any action ⇨ impassive被动的
commercial [kəˈmɜrʃ(ə)l]: n. an advertisement on television or radio广告
thrilled [θrɪld]: adj. very excited, happy, and pleased极为兴奋,激动
enrich [ɪnˈrɪtʃ]: v. to improve the quality of something, especially by adding things to it丰富
pathologize [pəˈθɒlədʒaiz]: v. 归于病态
dementia [dɪˈmenʃə]: n. an illness that affects the brain and memory, and makes you gradually lose the ability to think and behave normally[医] 痴呆
deteriorate [dɪˈtɪriəreɪt] deterioration: v.n. to become worse恶化,退化
--------------------
full time: adj./adv. 全职
part time: adj./adv. 兼职的
take sb. as an example: 拿某人举例
go neglected: 被忽视
wait (around) for sb. to do sth.: 等待某人做某事
be diagnosed with sth.: 被诊断患有...
** ch.
5-2 5.10 老龄化 - 第一部分
当我们谈论年长者或步入老年的人时，显然，我们也会关注N3C的变化。
随着环境的变化，人们的需求也会发生改变，对吧。
比如说，有些人可能需要帮助才能四处走动。
有些人甚至需要协助来满足基本的生存需求。
当然，并不是所有老年人都需要这些帮助。
有些人可能仍然非常健康和活跃。
他们不仅能够照顾自己，还能照顾他人。
他们甚至可以继续做出卓越的贡献，创造有意义的事物，为人类社会做出重大贡献。
所以，老年人的需求是多样化的。

在我们的社会中，存在着这样一种制度——退休制度，而它本身也在逐步发生转变。
退休的概念正在被重新定义和拓展。
与此同时，我们也看到人们正在经历某种转变。
比如，一个人原本是全职工作，然后变成兼职。
或者他完全停止工作，成为自由职业者，或者直接退休。
很显然，他与同事之间的关系也会因此发生变化。
嗯哼。
就拿我自己来说吧，我在大学工作。
如果我不再做这份工作，那么我和我的学生、同事之间的关系也会改变。
这种变化是可以预见的。

然而，这种情况更具挑战性的一点是，很多时候，人们并不了解老年人需求的变化。
因此，某些需求往往被忽视。
举几个例子，比如个人空间、独立性、自主性以及自我表达的需求，比如冒险精神。
在很多情况下，我们鼓励年轻人去冒险。
比如，一个蹒跚学步的幼儿摔倒了，我们会鼓励他站起来再试一次。
但是，如果一个90岁的老人摔倒了，人们则会建议他坐上轮椅。
对吧？
这是一种完全不同的理解。
年轻人可以从事高风险或高冲击性的运动，
但如果一个老人在长期护理机构中想要冒险尝试自己想做的事情，
通常他会被劝阻。
因此，某些需求就被忽略了。

另一个我经常谈论的重要话题是性与亲密关系的需求。
这是本课程中我们关注的关键问题之一。
老年人同样有性需求和亲密关系的需求，
但这些需求往往得不到认可。
我觉得社会上很多人认为，
一旦到了某个年纪，我们就会变得“无性化”。
或者，如果老年人仍然有性需求，
人们会觉得这很奇怪，对吧？

除此之外，由于社会存在年龄歧视的话语和实践，
老年人往往被描绘成一种被动的角色。
比如，我们在电视广告中看到，
老年人坐在那里，等着家人圣诞节来探望，
或者等着孙子孙女打电话。
当家人真的来看望他们时，他们被期待表现得欣喜若狂。
但我认为，这里存在某种系统性的偏见。
这种刻板印象将老年人的生活想象成无趣、无内容的状态。
我相信，无论是社会还是老年人自身，
都可以做很多事情来改变这种印象，同时也丰富老年人的生活。
这样一来，老年人的特质将被积极地看待，而不是被病态化。

此外，我们也必须认识到，老年人依然有可以发展的能力。
在过去几年里，我一直与失智症患者合作。
通过大量实例，我深信，
即使是被诊断患有失智症的人，
他们中的许多人依然可以继续学习和成长。
虽然我们倾向于认为，他们的各方面能力都会全面退化，
的确，他们在某些方面会经历衰退或功能下降，
但这并不意味着他们无法学习新事物。
这也不意味着，他们的生活无法通过不同的方式变得更加丰富。
因此，我相信，
他们自身的状态以及他们与世界的关系，
都可以被重新想象和塑造。

** sentence
aging [ˈeɪdʒɪŋ]: n. the process of getting old变老
- What the make-up brought is the oppsite of what you want, the aging.
- In these early days, people regarded the aging as a normal thing.
- The right propotions of ingredients will prevent you from the aging.
institution [ˌɪnstɪˈtuʃ(ə)n]: n. an important system of organization in society that has existed for a long time制度
- In the institution of defending vampires, the evil spirits will die down in no time.
- The institution is designed to defend aging people against risks of illness.
- The invention of institution caused the evil practices die down.
toddler [ˈtɑdlər]: n. a very young child who is just learning to walk学走路的儿童
- The toddler mumbled a great deal as he was fielding your so-called attacks.
- Even toddlers have been executed on his conquests in India.
- It is my duty to bring those toddlers back to their home country.
wheelchair [ˈhwilˌtʃer]: n. a chair with wheels, used by people who cannot walk轮椅
- From there the wheelchairs were not allowed to used.
- The scientist left his marks on this kind of wheelchair designed for aging people.
- The wheelchair is designed for toddlers in contrast to olders.
facility [fəˈsɪləti]: n. a place or building used for a particular activity or industry, or for providing a particular type of service场所
- It doesn't worry me, the wheelchair is also contained in the nursing facility.
- As the buckets built up in the facility, the olders lodged a complaint about their behaviors.
- The truck is hard to take an exit from the facility because of its tremendous shape.
asexual [eɪˈsekʃuəl]: adj. technical not having sexual organs or not involving sex无性的
- A new promising treatment captures the imagination and the hearts of those asexual people.
- Having long tolerated asexual marriage, she becomes sensitive about any potential partner.
- There are a lot of asexual marriages in which couples suffer a great deal.
ageist [ˈeɪdʒɪst]: adj. treating older people unfairly because of a belief that they are less important than younger people歧视老年人的
- You depicted him as asexual because of his aging, which is ageist.
- There are endlessly abundant ageist commerials on TV during Christmas.
- In the institution of retirement, the number of ageist discourses is in rapid free fall.
discourse [ˈdɪsˌkɔrs]: n. a serious speech or piece of writing on a particular subject谈论
- So to speak, the discourse didn't prove anything in terms of aging.
- For one thing, your discourse in public is really offensive.
- The discourse is about how penguins evolve from high-fly birds.
passive [ˈpæsɪv]: adj. someone who is passive tends to accept things that happen to them or things that people say to them, without taking any action ⇨ impassive被动的
- The ability to listen to others is just a passive skill.
- Contrary to his brother, he played a more passive role in the insitution of retirement.
- Being restricted to the school, he behaves very passively in the class.
commercial [kəˈmɜrʃ(ə)l]: n. an advertisement on television or radio广告
- This form of beer commercial becomes extremely popular with people in subtemperate regions.
- This form of oral commerical is forbidden off the nursing facility.
- This commercial is how penguins molt their feathers and why we should protect them from hunting.
thrilled [θrɪld]: adj. very excited, happy, and pleased极为兴奋,激动
- When he found an egg in tussock grasses, he felt very thrilled.
- The reason why he felt so thrilled was he found an egg in tussock grasses.
- As the evidence began to accumulate, the detective became very thrilled.
enrich [ɪnˈrɪtʃ]: v. to improve the quality of something, especially by adding things to it丰富
- A clutch of singers enriched the performance for free.
- Stuffs we found were being listed as raw materials, which enriched our food in the forest.
- The arrival of these toddlers enriched the performance beyond doubt.
pathologized [pəˈθɒlədʒaiz]: v. 归于病态
- You can't pathologize your father because his behaviors doesn't fit into your interests.
- The aging man expressed his sexual desires, which was pathologized by his co-workers.
- The request about the vacation was so excessive that I almost pathologized it.
dementia [dɪˈmenʃə]: n. an illness that affects the brain and memory, and makes you gradually lose the ability to think and behave normally[医] 痴呆
- The worker who used to work in the coal mine was diagnosed with dementia.
- The lady with dementia is hiding herself in the coal mine.
- Simply put, even if he is with dementia, he still has the capacity to learn new stuff.
deteriorate [dɪˈtɪriəreɪt] deterioration: v.n. to become worse恶化,退化
- The deterioration in all aspects of his life forced him to live in a nursing facility. 
- His bad memory is contributable to the deterioration of his brain.
- The deterioration of his listening misled him to take part in the competition.
--------------------
full time: adj./adv. 全职
- I want a full time job from which I can have a steady monthly income.
- Because of the aging, my grandfather gave up his full time job.
- My wife works full time, so she can afford a vacation at a seaside resort.
part time: adj./adv. 兼职的
- It's not easy to find a part time job because of economic crisis.
- I was asked to find a part time job in a city far away from my hometown.
- Sorry to interrupt, but the part time job has been taken.
go neglected: 被忽视
- His dedication to the family always goes neglected.
- With his needs going neglected, he played truant from school.
- With his needs going neglected, he lodged a complain about the mistreatment in the nursing facility.
wait (around) for sb. to do sth.: 等待某人做某事
- I wait for my wife to cook when I am watching TV in English.
- My cat is waitting around for me to open the can up.
- The lady is waitting for her husband to peresent a gift to her.
be diagnosed with sth.: 被诊断患有...
- When she was diagnosed with dementia, she got very angry.
- My father was diagnosed with psychiatric condition in my youth.
- Because my father was diagnosed with psychiatric condition, my father got divorced with him in my childhood.
** sentence2
aging [ˈeɪdʒɪŋ]: n. the process of getting old变老
- What the make-up brings is the opposite of what you want, the aging.
- In these early days, people regarded aging as a normal thing.
- The right proportions of ingredients will prevent you from aging.
institution [ˌɪnstɪˈtuʃ(ə)n]: n. an important system of organization in society that has existed for a long time制度
- In the institution of defending vampires, the evil spirits will die down in no time.
- The institution is designed to defend aging people against risks of illness.
- The invention of the institution caused the evil practices to die down.
toddler [ˈtɑdlər]: n. a very young child who is just learning to walk学走路的儿童
- The toddler mumbled a great deal as he was fielding your so-called attacks.
- Even toddlers were executed on his conquests in India.
- It is my duty to bring those toddlers back to their home country.
wheelchair [ˈhwilˌtʃer]: n. a chair with wheels, used by people who cannot walk轮椅
- From there wheelchairs were not allowed to be used.
- The scientist left his marks on this kind of wheelchair designed for aging people.
- The wheelchair is designed for toddlers in contrast to elders.
facility [fəˈsɪləti]: n. a place or building used for a particular activity or industry, or for providing a particular type of service场所
- It doesn't worry me, the wheelchair is also contained in the nursing facility.
- As the buckets built up in the facility, the elders lodged a complaint about their behaviors.
- The truck is hard to take an exit from the facility because of its tremendous shape.
asexual [eɪˈsekʃuəl]: adj. technical not having sexual organs or not involving sex无性的
- A new promising treatment captures the imagination and the hearts of those asexual people.
- Having long tolerated asexual marriage, she becomes sensitive about any potential partner.
- There are a lot of asexual marriages in which couples suffer a great deal.
ageist [ˈeɪdʒɪst]: adj. treating older people unfairly because of a belief that they are less important than younger people歧视老年人的
- You depicted him as asexual because of his aging, which is ageist.
- There are endlessly abundant ageist commercials on TV during Christmas.
- In the institution of retirement, the number of ageist discourses is in rapid free fall.
discourse [ˈdɪsˌkɔrs]: n. a serious speech or piece of writing on a particular subject谈论
- So to speak, the discourse didn't prove anything in terms of aging.
- For one thing, your discourse in public is really offensive.
- The discourse is about how penguins evolved from high-fly birds.
passive [ˈpæsɪv]: adj. someone who is passive tends to accept things that happen to them or things that people say to them, without taking any action ⇨ impassive被动的
- The ability to listen to others is just a passive skill.
- Contrary to his brother, he played a more passive role in the institution of retirement.
- Being restricted to the school, he behaves very passively in class.
commercial [kəˈmɜrʃ(ə)l]: n. an advertisement on television or radio广告
- This form of beer commercial has become extremely popular with people in sub-temperate regions.
- This form of oral commerical is forbidden off the nursing facility.
- This commercial is about how penguins molt their feathers and why we should protect them from hunting.
thrilled [θrɪld]: adj. very excited, happy, and pleased极为兴奋,激动
- When he found an egg in tussock grasses, he felt very thrilled.
- The reason why he felt so thrilled was he found an egg in tussock grasses.
- As the evidence began to accumulate, the detective became very thrilled.
enrich [ɪnˈrɪtʃ]: v. to improve the quality of something, especially by adding things to it丰富
- A clutch of singers enriched the performance for free.
- The stuff we found was listed as raw materials, which enriched our food in the forest.
- The arrival of these toddlers enriched the performance beyond doubt.
pathologized [pəˈθɒlədʒaiz]: v. 归于病态
- You can't pathologize your father because his behavior doesn't fit into your interests.
- The aging man expressed his sexual desires, which were pathologized by his co-workers.
- The request about the vacation was so excessive that I almost pathologized it.
dementia [dɪˈmenʃə]: n. an illness that affects the brain and memory, and makes you gradually lose the ability to think and behave normally[医] 痴呆
- The worker who used to work in the coal mine was diagnosed with dementia.
- The lady with dementia is hiding herself in the coal mine.
- Simply put, even if he is with dementia, he still has the capacity to learn new stuff.
deteriorate [dɪˈtɪriəreɪt] deterioration: v.n. to become worse恶化,退化
- The deterioration in all aspects of his life forced him to live in a nursing facility. 
- His bad memory is contributable to the deterioration of his brain.
- The deterioration of his listening misled him to take part in the competition.
--------------------
full time: adj./adv. 全职
- I want a full-time job from which I can have a steady monthly income.
- Because of the aging, my grandfather gave up his full-time job.
- My wife works full time, so she can afford a vacation at a seaside resort.
part time: adj./adv. 兼职的
- It's not easy to find a part-time job because of the economic crisis.
- I was asked to find a part-time job in a city far away from my hometown.
- Sorry to interrupt, but the part-time job has been taken.
go neglected: 被忽视
- His dedication to the family always goes neglected.
- With his needs going neglected, he played truant from school.
- With his needs going neglected, he lodged a complaint about the mistreatment in the nursing facility.
wait (around) for sb. to do sth.: 等待某人做某事
- I wait for my wife to cook when I am watching TV in English.
- My cat is waiting around for me to open the can up.
- The lady is waiting for her husband to present a gift to her.
be diagnosed with sth.: 被诊断患有...
- When she was diagnosed with dementia, she got very angry.
- My father was diagnosed with a psychiatric condition in my youth.
- Because my father was diagnosed with a psychiatric condition, my mother got divorced from him in my childhood.
