#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-2 5.7 Separation-Individuation 1
#+begin_verse
So when we're looking at transforming relationships,
	an important aspect that comes up is a process of Separation-Individuation.
And so traditionally that comes from Attachment Theory.
Where we look at the child's slowly but surely kind of becoming their own person
	and separating from their very enmeshed relationship with their caregiver.
But in SSLD we kind of understand it differently, right?
Yeah, I think Attachment Theory actually makes a significant contribution
	to our understanding of relationship from like childhood onwards.
And I think
	Separation Individuation provides a good conceptual structure for making sense of things.
	
But given our experience working not only with children, with their caregiver or parent,
	we also work with like people
		who are older and deal with issues that are discovered later in life.
We have a slightly different take on this.
First of all, when we talk about Separation Individuation,
	we find that not everyone completes that process when they're in their childhood.
Some people actually will take way longer.
You have people
	who are very dependent on a parent or parental figure for a long time
		and doesn't really complete the separation individuation until much older.
And then we also have the other side of the story which is like the parent not being able to let go.
And then when the child is supposed to leave,
	the parent is sort of holding on and not allowing that separation individuation to happen.
We also see that in relationships that are enmeshed
	and then you have two persons involved in a relationship
		which is like in a way resembling a parent-child situation.
And then like you have the same, or not exactly the same, but like very similar dynamics.
And one person is like making the decisions, like taking care and providing,
	and then the other person is dependent on that other person.
And when this person wants to gradually move out of that relationship and becomes independent,
	there will be a lot of tension and reluctance maybe.
And sometimes can be even like outright conflict, aggression, hostility.
So yeah like Separation Individuation
	is a very useful conceptual frame or metaphor for understanding relationships.
	
Maybe you can tell us a little bit about why it is so difficult for some people
	to really engage in this process of separation and individuation in relationship?
Well, like you know,
	in the SSLD framework we always use this one little interesting concept of needs, right?
And then like, how does it work?
Our analysis goes something like this.
When someone is heavily invested in a relationship and cannot let go,
	and cannot leave that relationship and become like more independent.
It usually means that this person doesn't have a lot of options from other sources
	or from other relationships to address his or her needs.
So if you imagine there's a parent like who can not let go of her child.
Well, it can happen to men, too, I'm not saying that only mothers do that.
There's fathers who cannot let their child go.
So the parent is heavily invested in this relationship.
Meaning that many of his or her needs are met through this relationship
	and those needs can not be effectively met by other relationships.
And that's why when the child is about to go,
	the parent will become nervous, anxious, and controlling, and want to hold onto the child.
So, but then if you are talking about someone who has multiple sources of gratification,
		like many gratifying relationships in his or her life,
	and life is rich and pleasant.
I believe this person will have less of a problem
	allowing this other person go and separate and individuate.
So I think the key idea we have is you know, whether the person's needs are met.

We can also talk about the person who is leaving.
It's the same thing.
For some people, they stay in the relationship and they cannot individuate or separate.
Because they're largely dependent on this one relationship to meet most of their needs.
And they may not have the confidence,
	they may not even believe that it is possible for them to have those needs met
		when they step out of the relationship.
So they stay in that relationship,
	even when it is like, stifling, and oppressive, and sometimes even abusive.
So our approach to this is to help empower the person who has to separate and individuate.
And one of the things that we do is to let this person
	develop a wider repertoire of skills and a wider range of working, functioning relationships.
So that his or her needs are being met.
Then it makes it easier for this person
	to go through this transition of like separation and individuation.
#+end_verse
** expression
separation [ˌsepəˈreɪʃ(ə)n]: n. when something separates or is separate分离, 分开
individuate [ˌɪndɪˈvɪdʒuˌeɪt] individuation: v.n. to make someone or something clearly different from others of the same kind使个体化
enmesh [ɪn'meʃ]: v. involve (someone) in a difficult situation from which it is hard to escape使陷入
resemble [riˈzɛmb(ə)l]: v. to look like or be similar to someone or something象, 类似
dynamics [daɪ'næmɪks]: n. the way in which things or people behave, react, and affect each other动力
reluctance [rɪ'lʌktəns]: n. when someone is unwilling to do something, or when they do something slowly to show that they are not very willing不愿意
invest [ɪnˈvest]: v. to buy shares, property, or goods because you hope that the value will increase and you can make a profit投资,投入
stifle [ˈstaɪf(ə)l]: v. to stop something from happening or developing OPP encourage压抑
empower [emˈpaʊr]: v. to give someone more control over their own life or situation使自主
repertoire [ˈrepərˌtwɑ:r]: n. the total number of things that someone or something is able to do全部才能
--------------------
take way longer: 花更长时间
hold on/onto sb.: 抓住某人不放
let go (of her child): 放手(某人)
** ch.
5-2 5.7 分离-个体化 1
所以，当我们在探讨关系转变时，一个重要的方面就是分离-个体化的过程。
这通常来源于依附理论。
在这个理论中，我们关注的是孩子逐渐成为自己独立的个体，并从与照顾者的密切关系中分离出来。
但在SSLD中，我们对这一点有不同的理解，对吗？
是的，我认为依附理论实际上对我们理解从儿童时期开始的关系有着重要贡献。
而且，我认为分离-个体化为我们提供了一个很好的概念框架来理解这些事情。
但是，考虑到我们不仅与儿童及其照顾者或父母合作，还与那些在晚年发现自己存在问题的成年人合作，
我们对这一点有些不同的看法。
首先，当我们谈到分离-个体化时，我们发现并不是每个人都能在儿童时期完成这个过程。
有些人实际上会花更长的时间才能完成这一过程。
有些人会长期依赖父母或父母式的人物，直到很大年纪才完成分离-个体化。
而另一方面，父母也可能无法放手。
当孩子应该离开时，父母会拉住不放，不允许这个分离-个体化的过程发生。
我们还在那些关系密切的情境中看到这种现象，
两个参与者的关系类似于一种父母与孩子的关系。
然后就会有类似的动态，虽然不完全一样。
一个人可能会做决定，照顾和提供，而另一个人则依赖于对方。
当这个人想逐渐脱离这段关系并变得独立时，就会出现很多紧张、抵触，甚至可能是直接的冲突、攻击或敌意。
所以，分离-个体化是一个非常有用的概念框架或隐喻，用来理解关系。
也许你可以告诉我们，为什么对于某些人来说，真正参与到这个分离和个体化的过程里是如此困难？
嗯，你知道的，在SSLD的框架下，我们总是使用一个有趣的概念——需求，对吧？
那它是如何运作的呢？
我们的分析大致是这样的：当一个人深深投入一段关系，无法放手，无法离开这段关系并变得更加独立时，
通常意味着这个人没有从其他来源或其他关系中获得满足自己需求的选择。
比如你想象一下有一个父母无法放手自己的孩子，
这也可能发生在男性身上，我并不是说只有母亲才会这样。
父亲也有无法放手孩子的情况。
所以，父母深深投入这段关系，意味着他们的很多需求是通过这段关系来满足的，而这些需求无法通过其他关系得到有效满足。
因此，当孩子准备离开时，父母会变得紧张、焦虑、控制，并试图抓住孩子不放。
但如果我们谈的是一个拥有多种满足来源的人，
比如有很多让自己愉快的关系，并且生活丰富、愉快，我相信这个人就会更容易允许另一个人离开，去独立和个体化。
所以，我认为我们所强调的关键点是，这个人的需求是否得到了满足。
我们也可以谈谈离开的那个人，情况也是一样的。
有些人待在关系中，无法完成个体化或分离，
因为他们在很大程度上依赖这一段关系来满足大部分需求。
他们可能缺乏信心，甚至不相信自己在脱离这段关系后能够满足这些需求。
所以，他们会继续待在这段关系中，即便这段关系让他们窒息、压抑，有时甚至是有害的。
因此，我们的做法是帮助那些需要分离和个体化的人赋能。
我们做的其中一件事是，让这个人发展更广泛的技能和更广泛的工作、功能性关系。
这样，他们的需求就能够得到满足。
然后，这就能让这个人更容易经历分离和个体化的转变。
** sentence
separation [ˌsepəˈreɪʃ(ə)n]: n. when something separates or is separate分离, 分开
- After our long time separation, I blew the powder into the cavern.
- Within the separation process, up to 80 percent of water will be dried.
- Exposed to a long time separatio, she desired for another Romantic relationship.
individuate [ˌɪndɪˈvɪdʒuˌeɪt] individuation: v.n. to make someone or something clearly different from others of the same kind使个体化
- The boy who is an apprentice to the baker tries to individuate.
- Obviously, she individuated herself and refused some of her parents' demands.
- Ironically a pockmarked face individuated her when she was in high school.
enmesh [ɪn'meʃ]: v. involve (someone) in a difficult situation from which it is hard to escape纠缠
- He succeeded in protecting against the detective who is enmeshed in a crime.
- The docter is being enmeshed with a kind of virus that's caught from a cow.
- It is stupid to challenge a woman enmeshed in a romantic relationship with her career.
resemble [riˈzɛmb(ə)l]: v. to look like or be similar to someone or something象, 类似
- He is immune to cowpox resembling smallpox.
- With the procedure, he can recognize some words resembling difficult notes.
- The teacher deliberates at length over the knowledge resembling concepts in previous session.
dynamics [daɪ'næmɪks]: n. the way in which things or people behave, react, and affect each other动态
- As long as the dynamics of the family changed dramatically, the law should become prohibited.
- The dynamics of the family certified the eradication of the tradition.
- The dynamics of the family proved that the couple had stolen over a million dollars.
reluctance [rɪ'lʌktəns]: n. when someone is unwilling to do something, or when they do something slowly to show that they are not very willing不愿意
- The reluctance she expressed has been forever remembered by her child. 
- The father of immunelogy published an article about the virus with reluctance.
- With reluctance, she took part in the great adventure of voyage.
invest [ɪnˈvest]: v. to buy shares, property, or goods because you hope that the value will increase and you can make a profit投资,投入
- What's the matter, why do you invest so much in the relationship?
- What the household invested in the school can extend as far back as middle ages.
- Back then, she was reluctant to invest in a boxer school.
stifle [ˈstaɪf(ə)l]: v. to stop something from happening or developing OPP encourage压抑
- What she went through in the marriage is simple described as a stifling times.
- Believe it or not, those who suffer in stifle relationships have one common characteristic.
- She has to sustain herself by whoring, which is very stifling.
empower [emˈpaʊr]: v. to give someone more control over their own life or situation使自主
- The force of the laws is supposed to empower minority groups in our country. 
- The efficacy of the law empowering miniority groups is changing with the times.
- With the dramatic increase of immigrants, there is increasing laws empowering them.
repertoire [ˈrepərˌtwɑ:r]: n. the total number of things that someone or something is able to do全部才能
- He is still suspicious about the repertoire of his brother's skills as a lawyer.
- Jimmy is tring to take advantage of the repertoire of his law skills in the court.
- The eminent lawyer reported worrying about the repertoire of his law skill.
--------------------
take way longer: 花更长时间
- I always take way longer to complete my homework than my brother.
- My wife takes way longer to take a shower than me.
- My grandfather takes way longer to feast on dinner.
hold on/onto sb.: 抓住某人不放
- Holding onto the attorney, the police discerned the cause of the murder.
- Why do you hold onto an innocent citizen?
- If you hold on the attorney who is familiar with the household, you may find more hints.
let go (of her child): 放手(某人)
- She begged her father to let go of her and her boyfriend in public.
- I shall let go of a child who doesn't care for the family.
- The relationship is transforming, I have to let go of my daughter.
** sentence2
separation [ˌsepəˈreɪʃ(ə)n]: n. when something separates or is separate分离, 分开
- After our long-time separation, I blew the powder into the cavern.
- Within the separation process, up to 80 percent of water will be dried.
- Exposed to a long-time separation, she desired another Romantic relationship.
individuate [ˌɪndɪˈvɪdʒuˌeɪt] individuation: v.n. to make someone or something clearly different from others of the same kind使个体化
- The boy who is an apprentice to the baker tries to individuate.
- Obviously, she individuated herself and refused some of her parents' demands.
- Ironically a pockmarked face individuated her when she was in high school.
enmesh [ɪn'meʃ]: v. involve (someone) in a difficult situation from which it is hard to escape纠缠
- He succeeded in protecting against the detective enmeshed in a crime.
- The doctor is being enmeshed with a kind of virus that's caught from a cow.
- It is stupid to challenge a woman enmeshed in a romantic relationship with her career.
resemble [riˈzɛmb(ə)l]: v. to look like or be similar to someone or something象, 类似
- He is immune to cowpox resembling smallpox.
- With the procedure, he can recognize some words resembling difficult notes.
- The teacher deliberates at length over the knowledge resembling concepts in the previous session.
dynamics [daɪ'næmɪks]: n. the way in which things or people behave, react, and affect each other动态
- As long as the dynamics of the family change dramatically, the law should become prohibited.
- The dynamics of the family certified the eradication of the tradition.
- The dynamics of the family proved that the couple had stolen over a million dollars.
reluctance [rɪ'lʌktəns]: n. when someone is unwilling to do something, or when they do something slowly to show that they are not very willing不愿意
- The reluctance she expressed has been forever remembered by her child. 
- The father of immunology published an article about the virus, with reluctance.
- With reluctance, she took part in the great adventure of the voyage.
invest [ɪnˈvest]: v. to buy shares, property, or goods because you hope that the value will increase and you can make a profit投资,投入
- What's the matter, why do you invest so much in the relationship?
- What the household invested in the school can extend as far back as the middle ages.
- Back then, she was reluctant to invest in a boxing school.
stifle [ˈstaɪf(ə)l]: v. to stop something from happening or developing OPP encourage压抑
- What she went through in the marriage is simply described as stifling times.
- Believe it or not, those who suffer in stifle relationships have one common characteristic.
- She has to sustain herself by whoring, which is very stifling.
empower [emˈpaʊr]: v. to give someone more control over their own life or situation使自主
- The force of the laws is supposed to empower minority groups in our country. 
- The efficacy of the law empowering minority groups is changing with the times.
- With the dramatic increase of the immigrants, there are increasing laws empowering them.
repertoire [ˈrepərˌtwɑ:r]: n. the total number of things that someone or something is able to do全部才能
- He is still suspicious about the repertoire of his brother's skills as a lawyer.
- Jimmy is trying to take advantage of the repertoire of his law skills in the court.
- The eminent lawyer reported worrying about the repertoire of his law skills.
--------------------
take way longer: 花更长时间
- I always take way longer to complete my homework than my brother.
- My wife takes way longer to take a shower than me.
- My grandfather takes way longer to feast on dinner.
hold on/onto sb.: 抓住某人不放
- Holding onto the attorney, the police discerned the cause of the murder.
- Why do you hold onto an innocent citizen?
- If you hold onto an attorney who is familiar with the household, you may find more hints.
let go (of her child): 放手(某人)
- She begged her father to let go of her and her boyfriend in public.
- I shall let go of a child who doesn't care for the family.
- The relationship is transforming, I have to let go of my daughter.
