#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 5-3 5.12 Transformation & Termination
#+begin_verse
So clearly not all relationships can really be worked out and continue in the same way.
Maybe sometimes there's a breakup or a divorce or even tragically a partner passes away.
So, I guess, would that be an example of termination?
Yeah, I know
	that like in theory we can talk about like, termination as very different than transformation.
Transformation meaning that the two partners who are still staying in a relationship of some sort.
Like they may be transformed,
	right, from like being lovers to being friends or from being colleagues to being lovers.
Those are transformations.
Termination means that we are stopping or terminating a certain relationship.

But I tend to think of termination as one outcome of transformation
	or maybe even one kind of transformation.
Because you know, it is not that we have never heard about people
	who have sort of like broken up or decided to terminate a certain relationship.
It could be like a lovers' relationship or marriage, or like a business partnership.
And then later on in life, they want to be you know together or they start something different.
So then you can look at it as a transformation as well.

And then for some people, the relationship can actually go on
	even when the other partner is no longer there physically, you know.
We have heard about people
	who are sort of maintaining a relationship with a deceased partner or family member or loved one,
		not necessarily in a morbid, pathological way,
		but they can also be in a healthy, growth-enhancing way.
So somehow this deceased person still has some presence in the person's current life.
So I tend to sort of like use transformation as a framework more.

But of course I recognize that for some relationships,
	it would be just like okay, we break up, or I don't see you anymore,
		and then you are no longer any part of my life and I just move on.
And then until like my life expires, this person is no longer present.
That is also imaginable and it happens, right,
	so I think it is meaningful to talk about termination in that sense.
But I see a lot of parallels and overlaps in the dynamics
	or in the process of the two kinds of changes.
#+end_verse
** expression
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
deceased [dɪˈsist]: adj. the deceased someone who has died, especially recently已故的
morbid [ˈmɔrbɪd]: adj. with a strong and unhealthy interest in unpleasant subjects, especially death有死志的
pathological [ˌpæθəˈlɑdʒɪk(ə)l]: adj. a mental or physical condition that is pathological is caused by disease病态的
parallel [ˈperəˌlel]: n. a relationship or similarity between two things, especially things that exist or happen in different places or at different times类似
overlap [ˈoʊvərˌlæp]: n. if two or more things overlap, part of one thing covers part of another thing重叠
expire [ɪkˈspaɪr]: v. if a period of time when someone has a particular position of authority expires, it ends终止
--------------------
in theory: theoritically理论上
It is meaningful to do sth.: 做某事很有意义
** ch.
5-3 5.12 转变与终结

显然，并非所有关系都能真正维持下去，并以相同的方式继续下去。
有时候，可能会发生分手或离婚，甚至是更为悲剧的情况，比如伴侣去世。
那么，我想，这算是终结的一个例子吗？
是的，我知道，从理论上来说，我们可以将终结视为与转变完全不同的概念。
转变意味着两个仍然保持某种关系的伙伴关系发生了变化。
比如，他们可能从恋人转变为朋友，或者从同事转变为恋人。
这些都是转变。
终结意味着我们正在停止或终止某种关系。

但我倾向于将终结视为转变的一种结果，甚至可能是一种转变的形式。
因为，我们并不是从未听说过这样的人，他们曾经分手，或决定终止某种关系。
这种关系可能是恋人关系、婚姻，或者商业合作关系。
然后，在他们人生的某个阶段，他们又想要重新在一起，或者开始另一种不同的关系。
所以，从这个角度来看，我们也可以将其视为一种转变。
对于某些人来说，甚至在另一方不再现实存在时，关系仍然可以继续。
我们听说过一些人，他们仍然在某种程度上维持着与已故伴侣、家人或所爱之人的关系。
这并不一定是病态的或不健康的。
它也可以是一种健康的、促进成长的方式。
因此，这位逝去的人在他们当前的生活中仍然有一定的存在感。
所以，我更倾向于将转变作为一个理解关系变化的框架。
当然，我也认识到，对于某些关系来说，情况可能只是单纯的终结。
比如，我们分手了，我再也不会见到你。
你不再是我生活的一部分，我继续前行。
直到我的生命结束，这个人都不再出现在我的生活中。
这种情况当然是可以想象的，并且确实会发生。
所以，我认为在这个意义上，讨论终结也是有意义的。
不过，我认为，在这两种变化的动态或过程中，有很多相似性和重叠之处。
** sentence
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
- The detective began the complex task of the crime to seek for a good outcome.
- The outcome of the test means that you will be in obscurity in five years.
- Working himself to the bone, he didn't deserve such a terrible outcome.
deceased [dɪˈsist]: adj. the deceased someone who has died, especially recently已故的
- Because his family was broken he had to marry a deceased girl.
- What both fishes have in common is that they are deceased.
- He took a quick look at the list of deceased people's names in the town.
morbid [ˈmɔrbɪd]: adj. with a strong and unhealthy interest in unpleasant subjects, especially death有死志的
- With the rise of mainstream culture, people don't lead morbid lives in the country.
- Fighting on the battlefield is a morbid way of dedicating yourself to your country.
- In a morbid way he violently secured rights to his belongs in the motel.
pathological [ˌpæθəˈlɑdʒɪk(ə)l]: adj. a mental or physical condition that is pathological is caused by disease病态的
- Under certain circumstances, pathological behaviors are regarded as normal.
- His brother designated him as a soldier in a pathological way.
- A matter between the actor and his girlfriend was a pathological relationship.
parallel [ˈperəˌlel]: n. a relationship or similarity between two things, especially things that exist or happen in different places or at different times类似
- On arriving on the island, he found the parallel with his hometown.
- Without noticing the parallel, he made some stupid remarks in public.
- The child succeeded in pointing out the parallel between two paintings.
overlap [ˈoʊvərˌlæp]: n. if two or more things overlap, part of one thing covers part of another thing重叠
- The overlap between two roads should be governed by both of us.
- The authorities refused to regulate the overlap between two roads.
- What is the size of overlap between the triangle and the circle.
expire [ɪkˈspaɪr]: v. if a period of time when someone has a particular position of authority expires, it ends终止
- When the clock expire, punishments for adultery will be executed.
- If the regime of the Queen expires, you will recover your legal status.
- You'll have to commit your paper as the test expires.
--------------------
in theory: theoritically理论上
- In theory, there is a chance that he is still the father of the boy.
- In theory, a large amount of ransom still does the trick.
- In theory, there will still be moon in the skill tomorrow night.
It is meaningful to do sth.: 做某事很有意义
- It is meaningful for me to make surprises for my wife.
- It is meaningful for me to share apartment with a cat.
- It is meaningful for you to commit your answers on time.
** sentence2
outcome [ˈaʊtˌkʌm]: n. the final result of a meeting, discussion, war etc – used especially when no one knows what it will be until it actually happens SYN result结果
- The detective began the complex task of the crime to seek a good outcome.
- The outcome of the test means that you will remain in obscurity for five years.
- Working himself to the bone, he didn't deserve such a terrible outcome.
deceased [dɪˈsist]: adj. the deceased someone who has died, especially recently已故的
- Because his family was broken he had to marry a deceased girl.
- What both fishes have in common is that they are deceased.
- He took a quick look at the list of names of deceased people in the town.
morbid [ˈmɔrbɪd]: adj. with a strong and unhealthy interest in unpleasant subjects, especially death有死志的
- With the rise of mainstream culture, people don't lead morbid lives in the country.
- Fighting on the battlefield is a morbid way of dedicating yourself to your country.
- In a morbid way he violently secured rights to his belongs in the motel.
pathological [ˌpæθəˈlɑdʒɪk(ə)l]: adj. a mental or physical condition that is pathological is caused by disease病态的
- Under certain circumstances, pathological behaviors are regarded as normal.
- His brother designated him as a soldier in a pathological way.
- A matter between the actor and his girlfriend was a pathological relationship.
parallel [ˈperəˌlel]: n. a relationship or similarity between two things, especially things that exist or happen in different places or at different times类似
- On arriving on the island, he found some parallel with his hometown.
- Without noticing the parallel, he made some stupid remarks in public.
- The child succeeded in pointing out the parallel between the two paintings.
overlap [ˈoʊvərˌlæp]: n. if two or more things overlap, part of one thing covers part of another thing重叠
- The overlap between two roads should be governed by both of us.
- The authorities refused to regulate the overlap between the two roads.
- What is the size of the overlap between the triangle and the circle?
expire [ɪkˈspaɪr]: v. if a period of time when someone has a particular position of authority expires, it ends终止
- When the clock expires, punishments for adultery will be executed.
- If the regime of the Queen expires, you will recover your legal status.
- You'll have to commit your paper as the test expires.
--------------------
in theory: theoritically理论上
- In theory, there is a chance that he is still the father of the boy.
- In theory, a large amount of ransom still does the trick.
- In theory, there will still be the moon in the skill tomorrow night.
It is meaningful to do sth.: 做某事很有意义
- It is meaningful for me to make surprises for my wife.
- It is meaningful for me to share an apartment with a cat.
- It is meaningful for you to commit your answers on time.
