#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2013-12-16 The popularity, plight and poop of penguins
#+begin_verse
Penguins have long captured the imagination and the hearts of people the world over.
But while popular culture depicts them
		as clumsy, adorable birds with endlessly abundant populations,
	the truth is that penguins are exceedingly graceful, often ornery,
		and their populations are in rapid free fall.
Their real life situation is far more precarious than people think.
And if current trends do not change,
	it may not be long before penguins can only be found in movies.
	
There are many things about penguins that make them odd birds, so to speak.
For one thing, they are one of the few bird species that cannot fly,
	having evolved from flight-capable birds about 60 million years ago.
Surprisingly, their closest living relative is the albatross,
	a bird known for its enormous wingspan and extraordinary soaring abilities.
It may seem strange that losing the ability to fly would be an evolutionary advantage,
	but the penguin's short, flipper-like wings and solid bones
		allow them to swim faster and dive deeper than any other bird on Earth,
	filling an ecological niche that no other bird can.
Penguins inhabit the southern hemisphere,
	being one of the few bird species able to breed in the coldest environments.
But contrary to popular belief,
	they are not restricted to cold regions nor are there any at the North Pole.
In fact, only 4 of the 18 penguin species regularly live and breed in Antarctica.
Most penguins live in subtemperate to temperate regions.
And the Galapagos penguin even lives and breeds
	right near the equator off the coast of South America.
They are also found in South Africa, Namibia, Australia, and New Zealand,
	as well as on a number of islands	in the southern Atlantic, Pacific, Indian, and Antarctic Oceans.
		
Although penguins spend 75% of their lives at sea,
	they must come to shore every year to reproduce and to molt their feathers.
They do this in a variety of places,
	from the temporary ice sheets of the Antarctic to the beaches of South Africa and Namibia,
		to the rocky shores of subantarctic islands,
		to the craggy lava surfaces in the Galapagos.
Different penguin species have different nesting practices.
Some dig burrows into dirt, sand, or dried guano;
	some nest in tussock grasses;
	some build nests out of small rocks, sticks, and bones;
	while others don't build any nests at all. 
Although most penguins lay a clutch of two eggs,
	the two largest species, the King and the Emperor,
		lay a single egg that they incubate on top of their feet for approximately two months.
	
Unfortunately, 15 of the 18 penguin species are currently listed as threatened,
	near-threatened, or endangered by the International Union for Conservation of Nature. 
In the last several decades,
	we have seen the world populations of most penguin species decline by up to 90%,
		with two of them,
			the Yellow-eyed and Galapagos penguins, down to just a few thousand birds.
Penguins are an indicator species, the proverbial "canary in the coal mine." 
Simply put, if penguins are dying, it means our oceans are dying. 

And sadly, most of this decline is attributable to human activities. 
Historically, penguins have had to deal with multiple disturbances. 
The mass collection of penguin eggs and the harvesting of the seabird guano they nested in
	caused the dramatic decline of several penguin species.
If you're wondering what humans would want with seabird poop, 
	it was used as an ingredient in fertilizer and in gunpowder, 
		being so valuable that in the 19th century, 
	it was known as white gold. 
Current threats to penguins
	include the destruction of both marine and terrestrial habitats,
			introduced predators, entrapment in fishing nets,
		and pollution from plastics and chemicals. 
There have also been several large-scale oil spills over the past 50 years 
	that have killed or impacted tens of thousands of penguins around the world. 
	
But the two major threats to penguins today are global warming and overfishing. 
Global warming impacts penguins in multiple ways, 
	from interrupting the production of krill
		due to decreased sea ice formation in the Antarctic,
	to increasing the frequency and severity of storms that destroy nests,
	to shifting the cold water currents
		carrying the penguins' prey too far away from penguin breeding and foraging grounds. 
Even though humans may be the greatest threat to penguins, 
	we are also their greatest hope. 
Many research and conservation projects are underway to protect penguin habitats
	 and restore vulnerable populations.
With a little help from us and some changes in the practices
		that impact our planet and oceans,
	there is hope that our tuxedo-clad friends will still be around in the next century.
#+end_verse
** expression
clumsy [ˈklʌmzi]: adj. moving or doing things in a careless way, especially so that you drop things, knock into things etc笨拙的
adorable [əˈdɔrəb(ə)l]: adj. someone or something that is adorable is so attractive that they fill you with feelings of love可崇拜的, 可爱的
exceedingly [ɪkˈsidɪŋli]: adv. extremely非常地
ornery [ˈɔrnəri]: adj. behaving in an unreasonable and often angry way, especially by doing the opposite of what people want you to do爱争吵的
precarious [prɪˈkeriəs]: adj. a precarious situation or state is one which may very easily or quickly become worse不稳定的
albatross [ˈælbəˌtrɔs]: n. a very large white sea bird信天翁
wingspan [ˈwɪŋˌspæn]: n. the distance from the end of one wing to the end of the other翼展
soar [sɔr]: v. to increase quickly to a high level高飞
evolutionary [ˌevəˈluʃ(ə)nˌeri]: adj. relating to the way in which plants and animals develop and change gradually over a long period of time进化的
flipper-like [ˈflɪpər]: adj. a flat part on the body of some large sea animals such as ↑seals, that they use for swimming鳍状肢
dive [daɪv]: v. to swim under water using special equipment to help you breathe潜水
hemisphere [ˈhemɪˌsfɪr]: n. a half of the Earth, especially one of the halves above and below the equator半球
breed [brid]: v. if animals breed, they ↑mate in order to have babies交配繁殖
reproduce [ˌriprəˈdus]: v. if an animal or plant reproduces, or reproduces itself, it produces young plants or animals繁殖
subantarctic [sʌb-æn'tɑ:ktɪk] : adj. 亚南极(区)的
craggy [ˈkræɡi]: adj. a mountain that is craggy is very steep and covered in rough rocks崎岖的
lava [ˈlɑvə]: n. hot liquid rock that flows from a volcano, or this rock when it has become solid熔岩
burrow [ˈbʌroʊ]: n. a passage in the ground made by an animal such as a rabbit or ↑fox as a place to live洞穴
stick [stɪk]: n. a long thin piece of wood from a tree, which is no longer attached to the tree ⇨ branch, twig木棍
incubate [ˈɪŋkjəˌbeɪt]: v. if a bird incubates its eggs, or if the eggs incubate, they are kept warm until they hatch孵卵
approximately [əˈprɑksɪmətli]: adv. an approximate number, amount, or time is close to the exact number, amount etc, but could be a little bit more or less than it近似地, 大约
indicator [ˈɪndɪˌkeɪtər]: n. something that can be regarded as a sign of something else指示器
historical [hɪˈstɔrɪk(ə)l] historically: adj.adv. connected to the study of history在历史上, 从历史观点上说
disturbance [dɪˈstɜrbəns]: n. something that interrupts what you are doing, or the act of making this happen干扰
guano [ˈɡwɑnoʊ]: n. solid waste from sea birds, put on soil to help plants grow海鸟粪
fertilizer [ˈfɜrt(ə)lˌaɪzər]: n. a substance that is put on the soil to make plants grow肥料
marine [məˈrin]: adj. relating to the sea and the creatures that live there海的
terrestrial [təˈrestriəl]: adj. living on or relating to land rather than water陆地的
habitat [ˈhæbɪˌtæt]: n. the natural home of a plant or animal栖息地
introduce [ˌɪntrəˈdus]: v. to bring a plan, system, or product into use for the first time引进
predator [ˈpredətər]: n. an animal that kills and eats other animals ⇨ prey掠食者
prey [preɪ]: n. an animal, bird etc that is hunted and eaten by another animal OPP predator被掠食者
entrapment [ɪnˈtræpmənt]: n. the practice of trapping someone by tricking them, especially to show that they are guilty of a crime诱捕的行动
plastic [ˈplæstɪk]: adj. a light strong material that is produced by a chemical process, and which can be made into different shapes when it is soft塑胶的
krill [krɪl]: n. small shellfish磷虾
conservation [ˌkɑnsərˈveɪʃ(ə)n]: n. the protection of natural things such as animals, plants, forests etc, to prevent them from being spoiled or destroyed SYN preservation保护
spills [spɪl]: n. when you spill something, or an amount of something that is spilled泄漏 
vulnerable [ˈvʌln(ə)rəb(ə)l]: adj. someone who is vulnerable can be easily harmed or hurt易受攻击的,脆弱的
tuxedo [tʌkˈsidoʊ]: n. a man’s ↑jacket that is usually black, worn on formal occasions燕尾服
--------------------
have long done sth.: 长久做某事
capture the imagination and the hearts of sb.: 抓住某人的想象力和心 
the world over: 全世界每个地方
depict A. as B.: describe A. as B.描述A为B
endlessly abundant: 庞大数量的
in rapid free fall: 在快速自由落体
so to speak: 可以说
For one thing: 首先
evolve from sth.: 从什么进化
the ability to do sth.: 做某事的能力
fill an ecological niche: 占据生态位
contrary to sth.: 与某事相反的
be not restricted to sp.: 不限于某处
subtemperate/temperate regions: 亚热带/热带区域
off sp.: in the neighbor of sp.在..附近
molt their feathers: 退去自身的羽毛
in tussock grasses: 在草丛中
a clutch of sth./sb.: 一群/把/组
be listed as sth.: 被列为某物
decline by: 下降
be down to sth.: 下降到
in the coal mine: 在煤矿洞里
Simply put: 简单来说
be attributable to sth.: 对某事归因
due to sth.: [4]归因于
carry sb. too far away from sp.: 把某人带得远离某地
be underway to do sth.: 正在做某事
** sentences
have long done sth.: 长久做某事
- He has long played piano.
- None other than the puma have long been at large.
- He has long captured the heart of his girlfriend.
capture the imagination and the hearts of sb.: 
- It becomes an accepted fact that pandas which are found in China capture the hearts of people.
- This insect is not supposed to capture the hearts of students. 
- He managed to capture the heart of the girl last year.
the world over: 
- For years, people the world over come to London.
- People the world over are watching TV now.
- People the world over have a habit of staying up.
depict A. as B.: describe A. as B.
- The colossal ship is depicted as unsinkable.
- She used to depict her husband as a potato.
- I find it impossible to depict her as a pretty girl.
endlessly abundant: 庞大数量的
- Endlessly abundant populations have been killed in action.
- They have a glimpse of endlessly abundant snakes on the beach.
- There are endlessly abundant cats in this exhibition.
in rapid free fall: 在快速自由落体
- Nobody saw her in rapid free fall at midnight.
- We're in difficulty, we're in rapid free fall.
- She attempted to rescue a cat which is in rapid free fall.
so to speak: 可以说
- So to speak, she leads a happy life after she has married him.
- So to speak, advertisements make an impact on us every day.
- So to speak, she learned to speak English in her youth.
For one thing: 首先
- For one thing, I make a study of flying cats.
- For one thing, I haven't raised a great amount of money.
- For one thing, the alarm has been given for the first time.
evolve from sth.: 从什么进化
- Humans are said to have evolved from a special kind of monkey.
- She realized to her horror that human beings evolved from a special kind of monkey.
- For one thing, rabbits didn't evolve from monkeys.
the ability to do sth.: 做某事的能力
- Do you have the ability to give an eulogy at the funeral?
- He lost the ability to give a speech in public.
- I lose the ability to ask for a lift at a village fair.
fill an ecological niche: 占据生态位
- Sustaining themselves by consuming mosquitos makes them fill an ecological niche.
- Because of our activities, cats fill an ecological niche in the city.
- Cats must fill an ecological niche in the city.
contrary to sth.: 与某事相反的
- Contrary to my idea, he bought him fifty dollars worth of trouble. 
- Contrary to our plan, many villagers are still keeping digging up bodies.
- Contrary to the traffic law, he crossed the street when the light was red.
be not restricted to sp.: 不限于某处
- To our surprise, penguins are not restricted to cold regions.
- Not restricted to Beijing, we found them in Hangzhou.
- As penguins are not restricted to cold regions, they're transported to England.
subtemperate/temperate regions: 亚热带/热带区域
- My wife loves to travel on the beach in temperate regions.
- This statue used to be located in temperate regions.
- These animals which are found in temperate regions are in the exhibition held up in England.
off sp.: in the neighbor of sp.
- The petrol has been used up when we're off campus.
- He has already moved to a flat off campus.
- The fire brigade is off campus now.
molt their feathers: 退去自身的羽毛
- These birds have a habit of molting their feathers.
- These birds which are molting their feathers are depicted as monsters by local villagers.
- The bird must be molting its feathers.
in tussock grasses: 在几簇草丛中
- He is always asking me to hide in tussock grasses.
- They may be hiding in tussock grasses to attack us.
- The puma is being cornered in tussock grasses.
a clutch of sth./sb.: 一群/把/组
- The bird gathered a clutch of sticks to nest in our house.
- A clutch of sticks convinced me that the bird was due to nest in my house.
- I carried a clutch of sticks to a shady spot under the tree.
be listed as sth.: 被列为某物
- The animal must be listed as threatened.
- The boat used to be listed as a colossal ship.
- There is some small, but non-zero, probability that the bird is listed as threatened.
decline by: 下降
- The students who played truant from school last week declined by 1%.
- The price of this kind of cat declined by up to $100.
- The price of apartments in China has declined by up to 20%.
be down to sth.: 下降到
- The members of the band were down to two persons.
- The animals in the zoo have been down to a lion and two pandas.
- The crew of the restaurant is down to only three persons.
in the coal mine: 在煤矿洞里
- These workers are still being trapped in the coal mine.
- These workers have been trapped in the coal mine for nearly three hours.
- We must rescue those workers trapped in the coal mine.
Simply put: 简单来说
- Simply put, he managed to play truant from school.
- Simply put, he never lost his heart.
- Simply put, she captured the heart of the noble gangster.
be attributable to sth.: 对某事归因
- The ritual that local villagers enact to kill undead is attributable to evil reanimation.
- These cadavers weren't attributable to the diseases in London.
- Beheading is attributable to the reduction of crime in town.
due to sth.: [4]归因于
- Due to his fishing, we have fish every day.
- Due to the bacteria, the blood and matter were forced out through the mouth. 
- Due to the gases and energy, the fireworks are launched into the sky.
carry sb. far away from sp.: 
- I must carry my daughter far away from the factory.
- The authorities must carry the factory far away from us.
- The authorities should have carried the factory far away from us.
be underway to do sth.: 
- They are underway to make a study of flying cats.
- I'm underway to undertake the search for extraterrestrial life.
- The experts from the zoo are underway to hunt for the puma.
