#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* The uncertain location of electrons
#+begin_verse
You probably know that all stuff is made up of atoms
	and that an atom is a really, really, really, really tiny particle.
Every atom has a core,
	which is made up of at least one positively charged particle called a proton,
	and in most cases, some number of neutral particles called neutrons.
That core is surrounded by negatively charged particles called electrons.
The identity of an atom is determined only by the number of protons in its nucleus.
Hydrogen is hydrogen because it has just one proton,
	carbon is carbon because it has six,
	gold is gold because it has 79, and so on.
	
Indulge me in a momentary tangent.
How do we know about atomic structure?
We can't see protons, neutrons, or electrons.
So, we do a bunch of experiments and develop a model for what we think is there.
Then we do some more experiments and see if they agree with the model.
If they do, great.
If they don't, it might be time for a new model.
We've had lots of very different models for atoms since Democritus in 400 BC,
	and there will almost certainly be many more to come.
Okay, tangent over.

The cores of atoms tend to stick together,
	but electrons are free to move,
	and this is why chemists love electrons.
If we could marry them, we probably would.
But electrons are weird.
They appear to behave either as particles, like little baseballs, or as waves, like water waves,
	depending on the experiment that we perform.
One of the weirdest things about electrons is that we can't exactly say where they are.
It's not that we don't have the equipment,
	it's that this uncertainty is part of our model of the electron.
So, we can't pinpoint them, fine.
But we can say
	there's a certain probability of finding an electron in a given space around the nucleus.
And that means that we can ask the following question:
	If we drew a shape around the nucleus
			such that we would be 95% sure of finding a given electron within that shape,
		what would it look like?
	
Here are a few of these shapes.
Chemists call them orbitals, and what each one looks like depends on, among other things,
	how much energy it has.
The more energy an orbital has, the farther most of its density is from the nucleus.
By they way, why did we pick 95% and not 100%?
Well, that's another quirk of our model of the electron.
Past a certain distance from the nucleus,
	the probability of finding an electron starts to decrease more or less exponentially,
		which means that while it will approach zero, it'll never actually hit zero.
So, in every atom, there is some small, but non-zero, probability that
	for a very, very short period of time,
		one of its electrons is at the other end of the known universe.
But mostly electrons stay close to their nucleus as clouds of negative charged density
	that shift and move with time.
	
How electrons from one atom interact with electrons from another determines almost everything.
Atoms can give up their electrons, surrendering them to other atoms, or they can share electrons.
And the dynamics of this social network are what make chemistry interesting.
From plain old rocks to the beautiful complexity of life,
	the nature of everything we see, hear, smell, taste, touch, and even feel is
		determined at the atomic level. 
#+end_verse
** expression
particle [ˈpɑrtɪk(ə)l]: n. a very small piece of something粒子
proton [ˈproʊˌtɑn]: n. a very small piece of matter with a positive electrical charge that is in the central part of an atom[核]质子
neutral [ˈnutrəl]: adj. not supporting any of the people or groups involved in an argument or disagreement中性的,中立的
nucleus [ˈnukliəs] nuclear: n. the central part of an atom, made up of ↑neutrons, ↑protons, and other ↑elementary particles原子核
indulge [ɪnˈdʌldʒ]: v. to let yourself do or have something that you enjoy纵容
orbitals [ˈɔrbɪt(ə)l]: n. ring road 轨道
pinpoint [ˈpɪnˌpɒɪnt]: v. to discover or explain exactly the real facts about something or the cause of a problem查明
density [ˈdensəti]: n. the degree to which an area is filled with people or things密度
quirk [kwɜrk]: n. a strange habit or feature of someone’s character, or a strange feature of something怪异
exponential [ˌekspəˈnenʃ(ə)l] exponentially: adj.adv. exponential growth/increase etc exponential growth, increase etc becomes faster as the amount of the thing that is growing increases指数的
----------------------------------------	
in a momentary tangent: to suddenly start talking or thinking about a completely new subject在片刻的切题中
develop a model for sth.: 为某物发展出模型
agree with the model: 与这个模型相符
it might be time for sth./ to do sth.: 可能是做某事的时间
there will be many more (sth.) to come: 有更多(某事物)到来
tend to do sth.: 倾向于做某事
stick together: 聚集在一起
behave as/like sth.: 表现得像某物
perform experiment: 做实验
It's not that + ..., it's that + ..: 不是...,而是...
there's a certain probability of doing sth.: 有确定的可能做某事
be 95% sure of doing: 95%的确信做某事
more or less: 或多或少
decrease/increase exponentially: 减少或增加指数级
approach zero: 接近0
hit zero: 到达0
there is some small, but non-zero, probability that + ..: 有很小但不是0的可能...
for a very, very short period of time: 很短的时间
interact with sb.: 与某人互动
surrender A. to B.: to give up something or someone, especially because you are forced to割让A给B
** sentences
in a momentary tangent: to suddenly start talking or thinking about a completely new subject
- He is reading another book in the course in a momentary tangent.
- If you kept in a momentary tangent, you would get a bad grade in this subject.
- It dawned on me that we were in a momentary tangent.
develop a model for sth.: 
- He noted with satisfaction that his child developed a model for an atom.
- It strikes him as developing a model for an atom.
- He succeeded in taking advantage of his imagination to develop a model for a cat.
agree with the model:
- It is all too easy to agree with the model without thinking carefully.
- He held up and stopped agreeing with the model.
- You said you agreed with the model in black and white.
it might be time for sth./ to do sth.:
- It might be time to reflect on the last bad experience.
- It might be time for lodgeing a complaint.
- It might be time to consult your dictionary instead of complaining anymore.
there will be many more to do sth.: 
- There will be many more to consult the map.
- There will be many more to be conditioned to play truant from school.
- There will be many more to reflect on the war.
tend to do sth.:
- She tends to fly directly to Beijing.
- I tended to return to my hometown after working in the city for years.
- There is a chance in a million that she tends to raise the kid.
stick together:
- Needless to say, these tomatoes stuck together.
- Sticking together, they are difficult to be separated from each other.
- It is incredible how these liquid foods stuck together.
behave as/like sth.:
- The cat used to behave like a dog, asking me to play ball with her.
- After acquainted with each other, they behaved like close friends.
- It is incredible for a cat to behave as a dog to be so friendly to humans.
perform experiment:
- The experiment which was performed bears no resemblance to the last one.
- The experiment which was performed bears a close resemblance to that one in 1990. 
- He is naive enough to believe that he could perform experiments after his retirement.
It's not that + ..., it's that + ..:
- It's not that I don't love you, it's that I hate you.
- It's not that he plotted to lead his father's downfall,
		it's that he offered much help to his father.
- It's not that your daughter brought about your downfall, it's that you led to your downfall.
there's a certain probability of doing sth.:
- There's a certain probability of winning a prize for the best teacher.
- There's a certain probability of acquainting him with the model of an atom.
- It seems reasonable to assume
		that there's a certain probability of living a good life on a desert island. 
be 95% sure of doing:
- I could be 95% sure that she would pay a ransom of $100.
- She's 95% sure of passing the exam.
- I was 95% sure of completing this course.
more or less:
- She is dear to me more or less. 
- She has shared her house with me more or less.
- I got worried about the IELTS exam more or less.
decrease/increase exponentially:
- The population of China increased exponentially in the 1980s.
- She explained that the population of China had increased exponentially.
- The number of these rabbits may increase exponentially in such a good environment.
approach zero: 
- The probability of meeting approached zero.
- Following his instructions, the probability of playing truant from school approaches zero.
- The probability of making mistakes will approach zero in this way.
hit zero:
- There are rare instances when the probability of an accident hits zero.
- I hope you don't mind the interference, but the probability of passing the exam hits zero.
- The probability of my understanding these abstract concepts hits zero.
there is some small, but non-zero, probability that + ..:
- There is some small, but non-zero, probability that the cat set his house on fire.
- There is some small, but non-zero, probability
		that the footnote conducted him to the bottom of the note.
- There is some small, but non-zero, probability that she is taking advantage of you.
for a very, very short period of time: 
- I have wished to get a good salary for a very short period of time.
- It dawned on me that she fell in love with me for a very short period of time.
- I can't help thinking of that embarrassing experience for a very short period of time.
interact with:
- How to interact with people around me is still disturbing me.
- She suggested that I interact with that pretty girl.
- We can't help interacting with each other towards the end of the party. 
surrender A. to B.: to give up something or someone, especially because you are forced to
- She complained that her boss ordered her to surrender her project to her workmate.
- He made his way back to surrender his play station to his wife.
- Separated from his wife, he still surrendered his property to his wife.
** Summary
#+begin_verse
All stuff is made up of atoms and an atom is a really tiny particle.
It has a core called a nucleus,
	which is made up of at least a proton and some number of neutrons in most cases
		and is surrounded by electrons.
The identity of an atom only depends on the number of protons.
In addition, we can't see those particles
	so we do a series of experiments to develop a model,
		which is examined by more experiments later.
The cores of atoms tend to stick together,
	but electrons,
			which behave either as particles, like little baseballs, or as waves, like water waves,
		are free to move.
So we can't exactly say where electrons are and that's part of our model of the electron.
However, we could draw a shape called an orbital around the nucleus
	within which we would be 95% sure of finding a given electron.
Most of its density from the nucleus is obviously determined by the energy an orbital has.
The reason why we pick 95% and not 100% is
	one of its electrons could be a random position in the known universe.
The nature of everything we see, hear, smell, and so on,
	is determined at the atomic level.
#+end_verse
