#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2013-10-17 How we conquered the deadly smallpox virus
#+begin_verse
10,000 years ago, a deadly virus arose in northeastern Africa.
The virus spread through the air,
	attacking the skin cells, bone marrow, spleen, and lymph nodes of its victims.
The unlucky infected developed fevers, vomiting, and rashes.
30% of infected people died during the second week of infection.
Survivors bore scars and scabs for the rest of their lives.
Smallpox had arrived.

In 1350 B.C., the first smallpox epidemics hit during the Egypt-Hittite war.
Egyptian prisoners spread smallpox to the Hittites,
	which killed their king and devastated his civilization.
Insidiously, smallpox made its way around the world via Egyptian merchants,
	then through the Arab world with the Crusades,
	and all the way to the Americas with the Spanish and Portuguese conquests.
Since then, it has killed billions of people
	with an estimated 300 to 500 million people killed in the 20th century alone.
	
But smallpox is not unbeatable.
In fact, the fall of smallpox started long before modern medicine.
It began all the way back in 1022 A.D.
According to a small book, called "The Correct Treatment of Small Pox,"
	a Buddhist nun living in a famous mountain
			named O Mei Shan in the southern providence of Sichuan
		would grind up smallpox scabs and blow the powder into nostrils of healthy people.
She did this after noticing that those who managed to survive smallpox never got it again,
	and her odd treatment worked.
The procedure, called variolation, slowly evolved and by the 1700's,
	doctors were taking material from sores
		and putting them into healthy people through four or five scratches on the arm.
This worked pretty well as inoculated people would not get reinfected, but it wasn't foolproof.
Up to three percent of people would still die after being exposed to the pass.

It wasn't until English physician Edward Jenner noticed something interesting about dairy maids
	that we got our modern solution.
At age 13, while Jenner was apprentice to a country surgeon and apothecary in Sodbury, near Bristol,
	he heard a dairy maid say,
	"I shall never have smallpox, for I have had cowpox.
	I shall never have an ugly, pockmarked face."
Cowpox is a skin disease that resembles smallpox and infects cows.
Later on, as a physician, he realized that she was right,
	women who got cowpox didn't develop the deadly smallpox.
Smallpox and cowpox viruses are from the same family.
But when a virus infects an unfamiliar host,
	in this case cowpox infecting a human, it is less virulent,
	so Jenner decided to test whether the cowpox virus could be used to protect against smallpox.
In May 1796, Jenner found a young dairy maid, Sarah Nelmes,
	who had fresh cowpox lesions on her hand and arm caught from the utters of a cow named Blossom.
Using matter from her pustules,
	he inoculated James Phipps, the eight-year-old son of his gardener.
After a few days of fever and discomfort, the boy seemed to recover.
Two months later, Jenner inoculated the boy again,
	this time with matter from a fresh smallpox lesion.
No disease developed, and Jenner concluded that protection was complete.
His plan had worked.
Jenner later used the cowpox virus in several other people
		and challenged them repeatedly with smallpox,
	proving that they were immune to the disease.
With this procedure, Jenner invented the smallpox vaccination.

Unlike variolation, which used actual smallpox virus to try to protect people,
	vaccination used the far less dangerous cowpox virus.
The medical establishment, cautious then as now,
	deliberated at length over his findings before accepting them.
But eventually vaccination was gradually accepted
	and variolation became prohibited in England in 1840.
After large vaccination campaigns throughout the 19th and 20th centuries,
	the World Health Organization certified smallpox's eradication in 1979.
Jenner is forever remembered as the father of immunology,
	but let's not forget the dairy maid Sarah Nelmes, Blossom the cow, and James Phipps,
		all heroes in this great adventure of vaccination who helped eradicate smallpox.
#+end_verse
** expressions
marrow [ˈmeroʊ]: n. the soft fatty substance in the hollow centre of bones骨髓
spleen [splin]: n. an organ near your stomach that controls the quality of your blood 脾脏
lymph [lɪmf] nodes [noʊd]: n. 淋巴结
vomit [ˈvɒmit]: v. to bring food or drink up from your stomach out through your mouth, because you are ill呕吐
scar [skɑr]: n. 疤痕
scab [skæb]: n. 痂
epidemic [ˌepɪˈdemɪk]: n. a large number of cases of a disease that happen at the same time传染病
insidiously [ɪn'sɪdɪrslɪ]: adv. an insidious change or problem spreads gradually without being noticed, and causes serious harm暗中为害地
merchant [ˈmɜrtʃənt]: n. someone whose job is to buy and sell things商人
Buddhist ['bʊdɪst]: n. 佛教徒
nun [nʌn]: n. someone who is a member of a group of religious women that live together尼姑
providence ['prɒvɪdəns]: n. a force which is believed by some people to control what happens in our lives and to protect us ⇨ fate深谋远虑, 天意, 上帝, 神的眷顾
variolation [vəraɪə'leɪʃ(ə)n]: n. 天花接种
sore [sɔr]: adj. a part of your body that is sore is painful疼痛的
inoculate [ɪˈnɑkjəˌleɪt]: v. to protect someone against a disease by putting a weak form of the disease into their body using a needle打预防针
foolproof [ˈfulˌpruf]: adj. a foolproof method, plan, system etc is certain to be successful万无一失的
dairy [ˈderi]: n. dairy products/produce milk, butter, cheese etc
apothecary [əˈpɑθəˌkeri]: n. someone who mixed and sold medicines in the past药剂师
pockmarked : adj. covered with hollow marks or holes麻子的
udders [ˈʌdər]: n. the part of a cow, female goat etc that hangs down between its back legs and that produces milk牛奶子
pustule [ˈpʌsˌtjʃ(ə)l]: n. a small raised spot on your skin containing ↑pus脓疱
lesion [ˈliʒ(ə)n]: n. damage to someone’s skin or part of their body such as their stomach or brain, caused by injury or illness损害
vaccinate [ˈvæksɪˌneɪt] vaccination: v.n. to protect a person or animal from a disease by giving them a vaccine牛痘疫苗
establishment [ɪˈstæblɪʃmənt]: n. formal an organization or institution, especially a business, shop etc机构
--------------------
spread through: 通过...传播
develop fevers, vomiting, rashes, smallpox: 发烧,呕吐,皮疹,天花
bear scars and scabs: 忍受疤和痂
spread sth. to sb.: 传播某物到某人
devastate the civilization: 摧毁文明
make its way around the world via sb.: 通过某人传播到世界
an estimated A.xx to B.xx sth.: 预估A到B的某物
the fall of sb./sth. start: 某人/某物的倒台开始了
It begins all the way back when + ...: 这要追溯到...
grind up sth.: 磨碎某物
blow the powder into sp.: 吹粉末到某地
up to xx percent of sth.: 高达某物的百分比
be exposed to sth.: you are in danger from it暴露于某物
be an apprentice to sjob.: pupil做某职业的学徒
a pockmarked face: 麻子脸
protect against sth.: 抵御某物
A. be caught from B.: 从B带来A(病毒)
challenge sb. with sth.: 用某物去挑战某人
be immune to sth.: 对某物免疫
with this procedure: 通过这个过程
deliberate at length over sth.: 仔细考虑某事
become prohibited: 被禁止
certify sth's eradication: 证明某物已被根除
be forever remembered as: 永久被记住为...
the father of -logy.: ...之父
in this great adventure of sth.: 在某事的伟大冒险中
** sentence
spread through: 
- I cherish the hope that this knowledge spreads through the social media.
- It is said that the deadly virus spread through the drainage system.
- The deadly virus has already spread through the air.
developed fevers, vomiting, rashes, smallpox: 
- My wife always has a fascination for me, when I develop a fever.
- When he developed fevers, he mobilized his immune system.
- If you kept eating so many times a day, you would develop vomiting.
bear scars and scabs: 
- I couldn't bear scars and scabs for the rest of my life.
- I couldn't bear scars and scabs after I developed smallpox.
- I was reminiscing about these days when I was bearing scars and scabs.
spread sth. to sb.: 
- These prisoners succeeded in spreading cowpox to their enemies.
- The entrepreneur stated that he would spread fear to everyone in China.
- While you were quaking in every limb, you spread emotions to everyone at the reception.
devastate the civilization: 
- It's a pity that the Hittites devastated the civilization of Egyptian.
- He's giving the eulogy in memories of the devastated civilization.
- The civilization which was devastated may date back to 1700 BC.
make its way around the world via sb.: 
- The arab number made its way around the world via Arabs in the 17th century.
- The tea which is found in China made its way around the world via English merchants.
- This special kind of pen makes its way around China via Wenzhou merchants.
an estimated A.xx to B.xx n.: 
- An estimated 100 to 200 thousand people went on vocations in the festive.
- It was incredible that an estimated 10 to 20 thousand people took part in the competition.
- An estimated 10 to 20 students's experiences bear a close resemblance to his.
the fall of sb./sth. start: 
- The fall of the emperor must start in 1975.
- He poured scorn on the idea that the fall of the emperor started in 1975.
- The fall of smallpox might start in 1975.
It begins all the way back when + ...: 
- It began all the way back at a time when people had to pay protection money to these gangsters.
- It began all the way back when I received an anonymous letter.
- It began all the way back when I shared my house with her.
grind up sth.: 
- He ground up the body to conceal it from the police.
- The pepper which was ground up is in the drawer.
- He is trying his best to grind up these bones.
blow the powder into sp.: 
- What a drama queen. I just blew the powder into your mouth.
- After blowing the powder into his room, he began reading books.
- The child blew the powder into his room, concealing his footsteps from his parents.
up to xx percent of sth.: 
- Up to 3 percent of people passed this exam.
- Up to 3 percent of science fiction was in the exhibition.
- Up to 99 percent of soldiers stood to attention.
be exposed to sth.: you are in danger from it
- Exposed to the enemies, he went up and down in front of the camp.
- Exposed to the soldier, he knocked him to the ground.
- She discovered that she had already been exposed to the teacher.
be an apprentice to sjob.: pupil
- My son used to be an apprentice to a baker in Beijing.
- I was curious to find out that my father used to be an apprentice to a barkery.
- You must have been an apprentice to a cook.
a pockmarked face: 
- In the end, she couldn't bear a pockmarked face so she had an operation.
- She tends to have an operation because of her pockmarked face.
- The probability of having a pockmarked face after the operation approaches zero.
protect against sth.: 
- She drew on her wisdom to protect against these gangsters.
- If you hadn't paid attention in the course,
		you wouldn't have protected against the enemies in the action. 
- She couldn't protect herself against the virus so she died of it.
A. be caught from B.: 从B带来A(病毒)
- If I hadn't stayed overnight in the hay,
		the virus wouldn't have been caught from the udders of the cow.
- Thanks to your carelessness, the virus has been caught from the laboratory.
- It became an accepted fact that this kind of virus was caught from monkeys in Africa.
challenge sb. with sth.: 
- My wife used to challenge me with my bad grades in our childhood.
- When I challenged her with a frog, she burst into tears.
- I was disappointed to learn that you challenged her with a frog.
be immune to sth.: 
- Having had an operation, you must be immune to smallpox. 
- We needn't have been immune to smallpox.
- You should have been immune to smallpox.
with this procedure: 
- With this procedure, he has developed a model for an atom.
- With this procedure, he set up a world record.
- With this procedure, he became fluent in English.
deliberate at length over sth.: 
- These scientists deliberated at length over his discovery before they decided to give him a prize.
- I felt disappointed that you guys deliberated at length over something useless.
- I'd rather deliberate at length over it than make stupid mistakes.
become prohibited: 
- Smoking became prohibited in public in 2004 in China.
- Smoking should become prohibited in public in China.
- This asterisk conducted me to the footnote,
		which says: 'Smoking became prohibited in London's subway.'
certify sth's eradication: 
- After having been fighting for over three months,
		the firefighters certified forest fire's eradication.
- The flight attendant has certified the bombs' eradication.
- After the authorities certified the smallpox's eradication, everything returned to normal.
be forever remembered as: 
- Mr. Leo will be forever remembered as our teacher.
- He is forever remembered as a state hero so that people gave him a state funeral.
- I'm sure that Mr. Leo will be forever remembered as our teacher.
the father of -logy.: 
- He was delighted that he was remembered as the father of astrology.
- LiaoXuefeng stated on his website that he is the father of Java.
- He got the nerve to call himself the father of Java. 
in this great adventure of sth.: 
- This gives him satisfaction in this great adventure of the voyage.
- It's a pity that she was killed in this great adventure of voyage.
- A regiment of soldiers risked their lives in this great adventure of conquest.

** summary
#+begin_verse
10,000 years ago, a deadly virus called smallpox,
		which spread through the air and attacks many organs of its victims
	arose in northeastern Africa.
Up to 30% of infected died during the second week of infection
	and survivors bore scars and scabs for the rest of their lives.
In 1350 B.C., the first smallpox epidemics hit
	because Egyptian prisoners spread smallpox to their invaders, the Hittites.
As time went on, smallpox arrived all over the world,
	which has killed billions of people.
However, smallpox is not unbeatable and its fall started long before modern medicine.
In 1022 AD, a Buddhist nun in Sichuan would grind up smallpox scabs
	to blow the powder into the nostrils of healthy people.
It worked pretty well, but up to three percent of inoculated people would still die of the virus.
It was English physician Edward Jenner who found vaccination
	that led to the eradication of smallpox.
According to the words of a dairy maid,
	he realized that people who have cowpox wouldn't have smallpox.
In May 1796, a young dairy maid, Sarah Nelmes,
	was infected with cowpox from the udders of a cow named Blossom.
Using matter from her pustules, he inoculated James Phipps
	and challenged him with smallpox to prove that it did work.
He achieved his triumph and repeated it several times.
In the end, the vaccination was gradually accepted.
After large vaccination campaigns,
	the World Health Organization certified smallpox eradication in 1979.
#+end_verse
