#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-01-06 How to fossilize yourself
#+begin_verse
Imagine being a fossil: touring the world's great museums,
	inspiring awe in onlookers of all ages, posing for hordes of fawning photographers.
Sound like something you'd like?
Well, good luck!
At least 99.9% of creatures that have ever lived aren't preserved in the fossil record.
But forget about them, everyone else will, and listen up!
If you want your corpse in the exclusive 0.01% Club, the Hall of Preserved Fossil Fame,
	it will not be easy.
You better work!
Step one: die.
It's a cold, hard fact of fossilization.
Everything paleontologists find was once alive and, at some point, died.
We'll skip the details and assume you had a long, fulfilling life
	so we can get to what is really important -- how you die.
	
There are many ways to become a fossil, so let's highlight your top death options.
You could get yourself trapped in tree sap,
	which, when hardens, turns into amber and can survive intact for millions of years.
But unless you find a really big tree to sit under,
	amber preservation will likely remain the domain of insects and other very small animals.
Generally, the right place to be if you want to end up a fossil
	is wherever sediment is actively being deposited, like a lake or an ocean floor.
A mountaintop or prairie? Not good!
You need to get buried, the faster the better,
	because the longer you hang around on the surface,
		the more likely you'll get eaten, scavenged, or otherwise destroyed
			before ever having a chance to get preserved.
If you can get buried someplace with little to no oxygen,
		like a bog or a deep lake bottom,
	even better.
That lack of oxygen will slow down your decay and give you more time to fossilize.
So, let's say you're lucky enough to die and get buried
	in a shallow sea under muddy, sandy sediments.
What's your next move?

One option is a process called permineralization.
While all your soft parts decay away, your bones get saturated with mineral-rich waters.
Bit by bit, microscopic crystals precipitate out of these waters
	to fill in the empty spaces and pores in your bones.
Otherwise, you'd better hope the sediments around you harden
	while your bones decay away
			and another sediment or mineral fills in the spaces your bones leave behind,
		creating a perfect cast of your skeleton.
Over time, the sediments around your fossil will lithify or turn into rock.

But you're not in the clear yet!
Many things could happen to those sedimentary rocks
	that might destroy your chances of getting discovered.
They could get uplifted into a mountain range
		and eroded away or carried along in an oceanic plate
		and subducted back into the Earth's mantle, melting your fossil into hot mush.
Fingers crossed your rock surroundings will get gently lifted up by plate tectonics,
	sea levels will change,
	and you'll end up under dry land close to the surface,
			but not so close that erosion from wind and rain wipes you away
		before someone can come to find you.
		
The last step in this long process, an intrepid paleontologist has to come find you.
Maybe she's a research scientist scouting for fossils your age and type
	or just an amateur collector hoping for a fortuitous find.
She whacks away at layers of rock above you
	or spots your fossil exposed in a creek bank after a flood.
And there you are, a magnificent scientific discovery, millions of years in the making!
She and her colleagues gently extract you from the surrounding sediment,
	measure and photograph all the bits and pieces they find,
	and begin the complex task of reconstructing
		how and when you lived based on the evidence they find in your bones.
Paleontologists will be some of your biggest fans
	along with all those admiring crowds at the museum.
	
You made it!
You spent years underground in obscurity, shedding blood, sweat, tears, and your internal organs.
You worked yourself to the bone
	until your bones disintegrated and were replaced by minerals and sediments.
But it was all worth it because you're a famous fossil!
Now, you better hold that pose! 
#+end_verse
** expression
fossil [ˈfɑs(ə)l]: n. an animal or plant that lived many thousands of years ago and that has been preserved, or the shape of one of these animals or plants that has been preserved in rock化石
tour [tʊr]: v. to visit several parts of a country or area旅游
fawn [fɔn]: v. to praise someone and be friendly to them in an insincere way, because you want them to like you or give you something奉承, 讨好
exclusive [ɪkˈsklusɪv]: adj. available or belonging only to particular people, and not shared独占的
fossilize [ˈfɑsəlˌaɪz] fossilization: v.n. to become or form a ↑fossil by being preserved in rock变成化石
paleontology [ˌpæliɑnˈtɑlədʒi] paleontologist: n. the study of ↑fossils (=ancient bones, plants etc that have been preserved in rock)古生物学
highlight [ˈhaɪˌlaɪt]: v. to make a problem or subject easy to notice so that people pay attention to it高亮
sap [sæp]: n. the watery substance that carries food through a plant树液
harden [ˈhɑrd(ə)n]: v. to become firm or stiff, or to make something firm or stiff OPP soften变硬
mountaintop [ˈmaʊnt(ə)nˌtɑp]: n. the top part of a mountain山顶
prairie [ˈpreri]: n. a wide open area of fairly flat land in North America which is covered in grass or wheat大草原
bury [ˈberi]: v. to put something under the ground, often in order to hide it埋葬
scavenge [ˈskævəndʒ]: v. if someone scavenges, they search through things that other people do not want, for food or useful objects以(腐肉)为食
bog [bɔɡ]: n. an area of low wet muddy ground, sometimes containing bushes or grasses ⇨ marsh, swamp沼泽
shallow [ˈʃæloʊ]: adj. measuring only a short distance from the top to the bottom OPP deep浅的
muddy [ˈmʌdi]: adj. covered with mud or containing mud泥泞的
sandy [ˈsændi]: adj. covered with sand, or containing a lot of sand沙的
sediment [ˈsedəmənt]: n. solid substances that settle at the bottom of a liquid沉淀物
permineralization : n. 完全矿化
mineral-rich [ˈmɪn(ə)rəl]: adj. 富含矿物质
microscopic [ˌmaɪkrəˈskɑpɪk]: adj. extremely small and therefore very difficult to see用显微镜可见的
pore [pɔr]: n. one of the small holes in your skin that liquid, especially ↑sweat, can pass through, or a similar hole in the surface of a plant毛孔, 小孔, 气孔
subduct ['sʌbdʌkt]: v. 俯冲
surroundings [səˈraʊndɪŋz]: n. the objects, buildings, natural things etc that are around a person or thing at a particular time环境
erosion [ɪˈroʊʒ(ə)n]: n. the process by which rock or soil is gradually destroyed by wind, rain, or the sea腐蚀
intrepid [ɪnˈtrepɪd]: adj. willing to do dangerous things or go to dangerous places – often used humorously SYN brave无畏的
amateur [ˈæməˌtʃʊr]: n. someone who does an activity just for pleasure, not as their job OPP professional业余爱好者
fortuitous [fɔrˈtuɪtəs]: adj. happening by chance, especially in a way that has a good result偶然的, 幸运的
magnificent [mæɡˈnɪfɪs(ə)nt]: adj. very good or beautiful, and very impressive华丽的
shed [ʃed]: adj. GET RID OF to get rid of something that you no longer need or want摆脱
disintegrate [dɪsˈɪntɪˌɡreɪt]: v. to ak up, or make something ak up, into very small pieces(使)分解
plate tectonics [tek'tɒnɪks]: 版块构造
--------------------
imagine doing/being sth.: 想象做某事
inspire awe in sb.: 激起某人的惊叹
hordes of sb.: a large unorganized group of individuals成群的...人
forget about sth.: 忘记某事
listen up: 仔细听
the Hall of sth. Fame: 名人堂
at some point: at an unspecified moment在某个不确定的点
get to sth.: 到达
A. turn into B.: be transformed into or become a particular kind of thing or person A变成B
survive intact: not broken or damaged存活完好
sp. remain the domain of sb.: 遗留为某人的领地
The right place to be if you want to do sth. is wherever + ...: 你想做某事的正确地方是无论哪里...
hang around: to pass time idly or in relaxing or socializing闲逛
slow down (<-> sth.): 减缓
decay away: 逐渐腐烂
give you more time to do sth.: 给你更多时间去做某事
be lucky enough to do sth.: 足够幸运去做某事
What's your next move: 你的下一步是什么
get saturated with sth.: to fill completely with something充满某物
Bit by bit: 一点点
precipitate out of these waters: 从水中析出
hope sb. do sth.: 希望某人做某事
create a perfect cast of sth.: 创造了某物的完美模型
You're not in the clear yet: 你还不能放松
a mountain range: 山脉
erode away sth.: 侵蚀消失某物
Fingers crossed + ...will: 希望成功+...
get gently lifted up: 被抬起
wipe away sth.: to remove (something) by rubbing擦去某物
scout for sth.: 搜寻，寻找
hope for sth.: 希望得到某物
whack away: 凿穿
in a creek bank: 小溪岸边
millions of years in the making: 历经数百万年形成
extract A. from B.: 从B中提取A
begin the complex task of doing sth.: 开始某事的复杂任务
in obscurity: 默默无闻
work oneself to the bone: to work extremely hard, especially for a long time努力到骨子里
hold that pose: 保持这个姿势
** sentences
imagine doing/being sth.:
- Imagine being a programmar working for Apple.
- Imagine staying up all night.
- Imagine setting up a factory.
inspire awe in sb.: 激起某人的惊叹
- There's at least one way to inspire awe in tourists in the West Lake.
- The machine which draws enery from these ants inspires awe in tourists.
- The door embedded into the wall inspires awe in him.
hordes of sb.: a large unorganized group of individuals
- Hordes of fans will meet him at the station.
- Hordes of fans have gathered round in front of the hall on the last of the year.
- During this time, hordes of tourists are being visiting this palace.
forget about sth.: 
- I forgot about our anniversary so that my wife got very angry.
- I forgot about the test which was held last Monday. 
- You have forgotten about what we experienced together.
listen up: 
- Listen up, it's none of your business.
- Listen up, there used to be a beggar asking for a meal once a day.
- Listen up, there was a palace only built from glasses and iron.
the Hall of sth. Fame: 名人堂
- Needless to say, the player, Faker, must be in the Hall of LoL Fame.
- The player, Faker, which has been in the Hall of LoL Fame, is in the face of his loss again.
- The statue of the player in the Hall of LoL Fame will be embedded into the map of this Game.
at some point: at an unspecified moment
- At some point, he was able to mobilize the immune system.
- At some point, he became familiar with those extreme chanllenges.
- At some point, I became expert at writting in English.
get to sth.: 到达
- Listen up, I'll get to the station in a few minutes.
- Decades before, she got to the town where she ran into her husband in the future.
- The fire couldn't get to the forest.
A. turn into B.: be transformed into or become a particular kind of thing or person
- Spoiler alert: the man who cheated on his wife turns into a stone.
- The man turned into a stone after he agreed with my enemy.
- It might be time for you to turn into a frog.
survive intact: not broken or damaged
- There's a certain probability of surviving intact after you paid a ransom of $1000.
- He managed to survive intact in a serious flood.
- For centuries, the palace only built from glasses and iron has survived intact.
sp. remain the domain of sb.: 遗留为某人的领地
- If you kept paying minimum wage, the factory would remain the domain of angry struck workers.
- The kitchen needn't have remained the domain of these ants.
- The bog is said to remian the domian of frogs.
The right place to be if you want to do sth. is wherever + ...: 你想做某事的正确地方是无论哪里...
- The right place to be if you want to study English is wherever there is a computer.
- The right place to be if you want to set up a factory
		is where the authorities don't ask for high taxes.
- The right place to be if you want to sing is where you can't hear any noises.
hang around: to pass time idly or in relaxing or socializing
- I like to hang around by the lake on weekends.
- Decades before, there was a beggar hanging around by the lake.
- My mother got me far away from those beggar hanging around.
slow down (<-> sth.): 减缓
- We're late for work because the craggy road slowed us down.
- The attacks on lymph nodes have slowed his recovery from smallpox.
- He pointed out the growth in sales might have slowed down last year.
decay away: 逐渐腐烂
- The bodies that were dug up by the local villagers decayed away swiftly.
- They should have found the body decay away.
- Fielding China's attacks, these Mongols made their lamb decay away.
give you more time to do sth.: 
- You should have given him more time to satisfy his curiosity.
- He hasn't been give more time to develop a model for an atom.
- My mother gave me more time to watch TV on weekends.
be lucky enough to do sth.: 
- I'm lucky enough to give up smoking.
- She's lucky enough to run a furniture business.
- You're lucky enough to surrender your seat to the boss.
What's your next move: 
- What's your next move? I'm gonna attend a fancy dress party.
- What's your next move? I have no idea.
- What's your next move? Make myself comfortable.
get saturated with sth.: to fill completely with something
- The machine used to get saturated with mineral-rich water on a lake floor.
- Saturated with this special kind of mixture, you'll feel better.
- The electricity meter in the storeroom gets saturated with water.
Bit by bit: 一点点
- Bit by bit, he made a name for himself decades before.
- Bit by bit, these firefighters got the fire under control.
- Bit by bit, he has the authority to look up the database.
precipitate out of these waters: 从水中析出
- He poured scorn on the idea that diamonds will precipitate out of these waters.
- No one could account for the fact that the diamond precipitated out of these waters.
- There was a note of triumph in his voice when the diamond precipitated out of these waters.
hope sb. do sth.: 希望某人做某事
- I hope you pass the test.
- I hope she achive her triumph.
- I hope him make a large sums of money.
create a perfect cast of sth.: 创造了某物的完美模型
- He is an expert at creating casts of these old buildings.
- He created a cast of the old house in momery of his mother.
- He devotes himself to creating casts of these old buildings.
You're not in the clear yet: 你还不能放松
- Though you passed the test, you're not in the clear yet.
- Though you get a better salary, you're not in the clear yet.
- Though your daughter begins to make money, you're not in the clear yet.
a mountain range: 山脉
- There is a mountain range known as the Alpa.
- The mountain range is said to be called the Alpa.
- We have been driving for three days to cross the mountain range.
erode away sth.: 侵蚀消失某物
- It's said that a diamond will never be eroded away.
- I heard about a tree which got eroded away through the centuries.
- I must discern the cause of the tree which is said to get eroded away.
Fingers crossed + ...will: 希望成功+...
- Fingers crossed you will have the authority to meet the princess.
- Fingers crossed you will get to the mythical realms.
- Fingers crossed you will undertake the important task of searching for exterrestrial lives.
get gently lifted up: 被抬起
- The baggage must get gently lifted up.
- With the order given, the baggage got gently lifted up.
- The soft should have gotten gently lifted up.
wipe away sth.: to remove (something) by rubbing
- The authorities are trying to wipe away these street signs.
- I saw you wipe away those signs, you must be an apprentice to a baker.
- I kept wiping away my wife's tears.
scout for sth.: 搜寻，寻找
- He is scounting for the soldier hiding in tussock grasses.
- While scounting for the soldier, he was knocked to the ground.
- These soldiers are scount for a prisoner at large up and down in front of the camp.
hope for sth.: 希望得到某物
- I have hoped for a gun in my youth.
- She hoped for a factory in her hard early years.
- The medical student hopes for a vacation for a period of time.
whack away: 凿穿
- The wall should have been whacked away.
- He whacked away the wall to rescue his cat.
- He whacked away the wall so that he could break into the mall.
in a creek bank: 小溪岸边
- A businessman claimed that he had seen the puma in a creek bank.
- There are a lot of excitements in a creek bank.
- We have made a big mistake in a creek bank.
millions of years in the making: 历经数百万年形成
- The fossil is millions of years in the making.
- The fossil turns out to be millions of years in the making.
- There is a mountain called the Alpa, millions of years in the making.
extract A. from B.: 从B中提取A
- I failed to extract the archive from the compressed file.
- The scientist undertook the arduous task of extracting the skeleton from the surround sediment.
- He went through arduous process of extracting the fossil from the rock.
begin the complex task of doing sth.: 开始某事的复杂任务
- He began the complex task of developing a model for an atom.
- These scientists began the complex task of searching for extraterrestrial lives.
- He began the complex task of translating the textbook into Chinese.
in obscurity: 默默无闻
- The maidservant in obscurity has killed five of her husbands in her youth.
- It is incredible that the writer in obscurity makes a large sum of money.
- The student in obscurity has completed the arduous course.
work oneself to the bone: to work extremely hard, especially for a long time
- My teacher used to ask me to work myself to the bone.
- Although I work myself to the bone, I don't get a good salary.
- I poured scorn on the idea that she decided to work herself to the bone.
hold that pose: 保持这个姿势
- Following my instruction, my wife held that pose so that I could take photographs.
- You looked beautiful while you were holding that pose.
- I anticipated that she couldn't hold that pose for a long time.
