#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-05-06 What is the world wide web
#+begin_verse
The World Wide Web, where you're likely watching this video,
	is used by millions of people every day for everything
		from checking the weather, ordering food,
			and chatting with friends to raising funds, sharing news, or starting revolutions.
We use it from our computers, our phones, even our cars.
It's just there, all around us, all the time.
But what is it exactly?

Well first of all, the World Wide Web is not the Internet,
	even though the terms are often used interchangeably.
The Internet is simply the way computers connect to each other in order to share information.
When the Internet first emerged, computers actually made direct calls to each other.
Today, networks are all around us, so computers can communicate seamlessly.
The communication enabled through the Internet has many uses,
	such as email, file transfer, and conferencing.
	
But the most common use is accessing the World Wide Web.
Think of the Web as a bunch of skyscrapers, each representing a web server,
	a computer always connected to the Internet,
		specifically designed to store information and share it.
When someone starts a website,
	they are renting a room in this skyscraper,
		filling it with information
		and linking that information together in an organized way for others to access.
The people who own these skyscrapers and rent space in them are called web hosts,
	but anyone can set up a web server with the right equipment, a bit of know-how.
	
There's another part to having a website,
	without which we would be lost in the city with no way of finding what we need.
This is the website address, which consists of domain names.
Just like with a real life address, a website address lets you get where you want to go.
The information stored in the websites is in web languages, such as HTML and JavaScript.
When we find the website we're looking for,
	our web browser is able to take all the code on the site
		and turn it into words, graphics, and videos.
We don't need to know any special computer languages
	because the web browser creates a graphic interface for us.
So, in a lot of ways,
	the World Wide Web is a big virtual city
			where we communicate with each other in web languages,
		with browsers acting as our translators.
		
And just like no one owns a city, no one owns the Web; it belongs to all of us.
Anyone can move in and set up shop.
We might have to pay an Internet service provider to gain access,
	a hosting company to rent web space,
	or a registrar to reserve our web address.
Like utility companies in a city, these companies provide crucial services,
	but in the end, not even they own the Web.
	
But what really makes the Web so special lies in its very name.
Prior to the Web, we used to consume most information in a linear fashion.
In a book or newspaper article,
	each sentence was read from beginning to end, page by page, in a straight line
		until you reached the end.
But that isn't how our brains actually work.
Each of our thoughts is linked to other thoughts, memories, and emotions
	in a loose interconnected network, like a web.
Tim Berners-Lee, the father of the World Wide Web,
	understood that we needed a way to organize information that mirrored this natural arrangement.
And the Web accomplishes this through hyperlinks.
By linking several pages within a website
		or even redirecting you to other websites to expand on information or ideas immediately
			as you encounter them,
	hyperlinks allow the Web to operate along the same lines as our thought patterns.
	
The Web is so much a part of our lives
	because in content and structure, it reflects both the wider society and our individual minds.
And it connects those minds across all boundaries,
	not only ethnicity, gender, and age but even time and space. 
#+end_verse
** expression
interchangeable [ˌɪntərˈtʃeɪndʒəb(ə)l]/interchangeably: adj.adv. things that are interchangeable can be used instead of each other可互换的
conference [ˈkɑnf(ə)rəns]: n. a large formal meeting where a lot of people discuss important matters such as business, politics, or science, especially for several days协商会
skyscraper [ˈskaɪˌskreɪpər]: n. a very tall modern city building摩天楼
know-how: n. knowledge, practical ability, or skill to do something实际知识
virtual [ˈvɜrtʃuəl]: adj. made, done, seen etc on the Internet or on a computer, rather than in the real world虚的
hosting [hoʊst]: n. to provide the place and everything that is needed for an organized event托管 
registrar [ˌredʒɪˈstrɑr]: n. someone who is in charge of official records of births, marriages, and deaths登记员
loose [lus]: adj. not firmly fastened in place宽松的
interconnect [ˌɪntərkəˈnekt]: v. if two systems, places etc are interconnected, or if they interconnect, they are joined together使互相连接
mirror [ˈmɪrər]: v. if one thing mirrors another, it is very similar to it and may seem to copy or represent it SYN reflect反映
arrangement [əˈreɪndʒmənt]: n. plans and preparations that you must make so that something can happen排列, 安排
hyperlink [ˈhaɪpərˌlɪŋk]: n. a word or picture in a ↑website or computer document that will take you to another page or document if you ↑click on it超链接
encounter [ɪnˈkaʊntər]: v. to experience something, especially problems or opposition遭遇
reflect [rɪˈflekt]: v. to show or be a sign of a particular situation or feeling反射
boundary [ˈbaʊnd(ə)ri]: n. the real or imaginary line that marks the edge of a state, country etc, or the edge of an area of land that belongs to someone边界
ethnicity [eθˈnɪsəti]: n. 种族划分
----------------------------------------
be likely doing: 可能正在做某事
be used by sb. for sth.: 被某人使用做某事
chat with sb.: 和某人闲聊
use it from sth.: 通过某物用它
first of all: 首先
made a call to sb.: 打电话给某人
be all around sb.: 就在某人身边
There's another part to doing sth., without which + ...: 做某事还有令一部分, 没有它...
with no way of doing sth.: 没有办法做某事
a graphic interface: 一个图形界面
utility company: 共同服务公司
lie in sth.: 在于某事
be prior to sth.: 在...之前
in a linear fashion: 线形方式
in a straight line: 笔直地
redirect sb. to sp.: 重定向某人到某地
in content and structure: 在内容和结构上
** sentences
be likely doing: 可能正在做某事
- The curtain is likely going up.
- Your sister is likely playing matchmaker for us.
- You are likely taking advantage of me.
be used by sb. for sth.: 被某人使用做某事
- Smallpox is used by the Chinese for infecting their invaders.
- The model is being used by professors for teaching their students nowadays.
- The box is used by our child for collecting his pocket money.
chat with sb.: 和某人闲聊
- I have chatted with my father about mythical realms.
- After sending these emails off, I chatted with my colleagues.
- Chatting with my brother, I assembled these parts into a bicycle.
use it from sth.: 通过某物用它
- I have no idea how to use it from this computer.
- You can use it from the computer.
- You might as well use it from your phone.
first of all: 首先
- First of all, no woman could bear scars and scabs for the rest of her life.
- First of all, these Greeks devastated our civilization.
- First of all, the smallpox made its way around the world via these businessmen.
made a call to sb.: 打电话给某人
- In a momentary tangent, I make a call to my father.
- Having developed a model for an atom, he made a call to his teacher immediately. 
- If you agreed with the model, you would make a call to your father.
be all around sb.: 就在某人身边
- He said that the ghost was all around us.
- He behaved as if a ghost was all around him.
- I was performing experiments all around you.
There's another part to doing sth., without which + ...: 做某事还有令一部分, 没有它...
- There's another part to connect to the internet,
		 without which you can't chat with your friends online.
- There's another part to agree with the model, without which you can't be 100% sure.
- There's another part to perform experiments, without which these students can't stick together.
with no way of doing sth.: 没有办法做某事
- I am lost in the city with no way of taking a taxi.
- The chance of finishing this homework approaches zero
		with no way of reading articles about biology.
- We must be lost in outer space with no way of connecting to the earth.
a graphic interface: 一个图形界面
- A good graphic interface will be designed to check the weather.
- These staff drew on a graphic interface to input their results.
- The graphic interface shows how life is formed on the earth. 
utility company: 共同服务公司
- The utility company will undertake telephone service in two months. 
- It is only within the last century that some countries began to set up utility companies.
- The utility company was said to be inhabited by a group of monks.
lie in sth.: 在于某事
- The key to attraction may lie in your first kiss.
- Your marriage may lie in the same basic goal that you share together.
- Your success might lie in setting up a factory in your youth.
be prior to sth.: 在...之前
- His death prior to 65 shocked me a great deal.
- Prior to the cat, the dog has been staying here since two months ago.
- Prior to the woman, I have been waiting in line for two hours.
in a linear fashion: 线形方式
- My teacher complained that I always read articles in a linear fashion.
- You shouldn't keep your students reading books in a linear fashion.
- You can't assemble these parts into a bicycle in a linear fashion.
in a straight line: 笔直地
- I asked him to give me a lift in a straight line.
- He hit the surface of the desktop in a straight line.
- If the police arrived on the scene, they would notice the gangster run away in a straight line.
redirect sb. to sp.: 重定向某人到某地
- I am glad that it redirected me to the right website.
- It is used to redirect you to pornographic websites.
- Once the order is confirmed, you will be redirected to the payment page.
in content and structure: 在内容和结构上
- In content and structure, it reminds me of the story a journalist in China wrote.
- In content and structure, it expands on our model of an atom.
- In content and structure, I rate it poetic.
