#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-06-03 How to choose your news
#+begin_verse
How do you know what's happening in your world?
The amount of information just a click away may be limitless,
	but the time and energy we have to absorb and evaluate it is not.
All the information in the world won't be very useful unless you know how to read the news.
To your grandparents, parents, or even older siblings, this idea would have sounded strange.
Only a few decades ago, news was broad-based.
Your choices were limited to a couple of general interest magazines and newspaper of record,
	and three or four TV networks
		where trusted newscasters delivered the day's news at the same reliable time every evening.
		
But the problems with this system soon became apparent as mass media spread.
While it was known that authoritarian countries controlled and censored information,
	a series of scandals showed
		that democratic governments were also misleading the public, often with media cooperation.
Revelations of covert wars, secret assassinations, and political corruption
	undermined public faith in official narratives presented by mainstream sources.
This breakdown of trust in media gatekeepers
		lead to alternative newspapers, radio shows, and cable news
	competing with the major outlets and covering events from various perspectives.
More recently, the Internet has multiplied the amount of information and viewpoints,
		with social media, blogs, and online video
	turning every citizen into a potential reporter.
But if everyone is a reporter,
	nobody is,
	and different sources may disagree, not only opinions, but on the facts themselves.
So how do you get the truth, or something close?

One of the best ways is to get the original news unfiltered by middlemen.
Instead of articles interpreting a scientific study or a politician's speech,
	you can often find the actual material and judge for yourself.
For current events, follow reporters on social media.
During major events, such as the Arab Spring or the Ukrainian protests,
	newscasters and bloggers have posted updates and recordings from the midst of the chaos.
Though many of these later appear in articles or broadcasts,
	keep in mind that these polished versions
		often combine the voice of the person who was there with the input of editors who weren't.
			
At the same time, the more chaotic the story, the less you should try to follow it in real time.
In events like terrorist attacks and natural disasters,
	today's media attempts continuous coverage even when no reliable new information is available,
		sometimes leading to incorrect information or false accusations of innocent people.
It's easy to be anxious in such events,
	but try checking for the latest information at several points in the day,
		rather than every few minutes,
	allowing time for complete details to emerge and false reports to be refuted.
While good journalism aims for objectivity, media bias is often unavoidable.
When you can't get the direct story,
	read coverage in multiple outlets
		which employ different reporters and interview different experts.
Tuning in to various sources and noting the differences
	lets you put the pieces together for a more complete picture.
	
It's also crucial to separate fact from opinion.
Words like think, likely, or probably
	mean that the outlet is being careful or, worse, taking a guess.
And watch out for reports that rely on anonymous sources.
These could be people who have little connection to the story,
		or have an interest in influencing coverage,
	their anonymity making them unaccountable for the information they provide.
	
Finally, and most importantly, try to verify news before spreading it.
While social media has enabled the truth to reach us faster,
	it's also allowed rumors to spread before they can be verified
		and falsehoods to survive long after they've been refuted.
So, before you share that unbelievable or outrageous news item,
	do a web search to find any additional information or context you might have missed
		and what others are saying about it.
Today, we are more free than ever from the old media gatekeepers
	who used to control the flow of information.
But with freedom comes responsibility:
	the responsibility to curate our own experience
			and ensure that this flow does not become a flood,
		leaving us less informed than before we took the plunge. 
#+end_verse
** expression
absorb [əbˈzɔrb]: v. to read or hear a large amount of new information and understand it吸收
broad-based [brɔd]: adj. 基础深厚的
newspaper of record: 主流报纸
authoritarian [ɔˌθɔrɪˈteriən]: adj. strictly forcing people to obey a set of rules or laws, especially ones that are wrong or unfair独裁的, 独裁主义的
censor [ˈsensər]: v. to examine books, films, letters etc to remove anything that is considered offensive, morally harmful, or politically dangerous审查
scandal [ˈskænd(ə)l]: n. talk about dishonest or immoral things that famous or important people are believed to have done丑闻
revelation [ˌrevəˈleɪʃ(ə)n]: n. a surprising fact about someone or something that was previously secret and is now made known揭露
covert [koʊˈvɜrt]: adj. secret or hidden隐蔽的, 偷偷摸摸的
assassination [əˌsæsɪˈneɪʃ(ə)n]: n. the act of murdering an important person暗杀
corruption [kəˈrʌpʃ(ə)n]: n. dishonest, illegal, or immoral behaviour, especially from someone with power贪污
narrative [ˈnerətɪv]: n. a description of events in a story, especially in a ↑novel叙述
mainstream [ˈmeɪnˌstrim]: n. the mainstream the most usual ideas or methods, or the people who have these ideas or methods主流
gatekeeper [ˈɡeɪtˌkiːpə(r)]: n. someone whose job is to open and close a gate, and to allow or not allow people to go through it看门人
outlet [ˈaʊtˌlet]: n. a pipe or hole through which something such as a liquid or gas can flow out出路
unfiltered [ʌn'fɪltəd]: adj. 未滤过的
protest [prəˈtest: v. something that you do to show publicly that you think that something is wrong and unfair, for example taking part in big public meetings, refusing to work, or refusing to buy a company’s products抗议
blog [blɒɡ] / blogger: n.n. a web page containing information or opinions from a particular person or about a particular subject, to which new information is added regularly SYN web log博客
polished [ˈpɑlɪʃt]: adj. polite, confident, and graceful 精练的, 优美的
chaotic [keɪˈɑtɪk]: adj. a chaotic situation is one in which everything is happening in a confused way混乱的, 无秩序的
terrorist [ˈterərɪst]: n. someone who uses violence such as bombing, shooting etc to obtain political demands恐怖分子
coverage [ˈkʌv(ə)rɪdʒ]: n. when a subject or event is reported on television or radio, or in newspapers新闻报告
accusation [ˌækjəˈzeɪʃ(ə)n]: n. a statement saying that someone is guilty of a crime or of doing something wrong谴责
refute [rɪˈfjut]: v. to prove that a statement or idea is not correct SYN rebut驳倒
bias [ˈbaɪəs]: n. an opinion about whether a person, group, or idea is good or bad that influences how you deal with it偏见
anonymity [ˌænəˈnɪməti]: n. when other people do not know who you are or what your name is匿名
rumor [ˈrumər]: n. information or a story that is passed from one person to another and which may or may not be true流言
falsehood [ˈfɔlsˌhʊd]: n. a statement that is untrue SYN lie谬误
outrageous [aʊtˈreɪdʒəs]: adj. very shocking and extremely unfair or offensive骇人的
curate [kjəˈreɪt]: v. organize操持
flow [floʊ]: v. when a liquid, gas, or electricity flows, it moves in a steady continuous stream流动
----------------------------------------
a click away: 用鼠标点击一下
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
compete with sb.: 同某人竞争
from various perspectives: 从各种各样的视角
More recently: 更近期地
multiply the amount of sth.: 倍增某物的数量
sb. keeps in mind that + ...: 某人牢记...
in real time: 实时
at several points in the day: 在一天的几个点
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
aim for sth.: 争取某物
tuning in to sth.: 收听某事
take a guess: 做猜测
watch out for sth.: 小心提防
have little connection to sth./sb.: 和某事/某物没关系
make sb. unaccountable for sth.: 使某人对于某物没有责任
with A. comes B.: 伴随A来的B
ensure that + ...: 确保...
leave sb. less informed than before + ...: 让某人比...之前更加无知
took the plunge: 冒险
** sentences
a click away: 用鼠标点击一下
- Rating our application is just a click away on your computer.
- Your computer will run a complex series of calculations just a click away.
- Shopping in China is just a click away on your cell phone.
undermine sb's faith in sth./sb.: 减弱某人对某事/某人的信任
- Rateing his personality behind his back must undermine his faith in you.
- These events I learned from the newspaper have undermined my faith in shopping on the internet.
- What he told me yesterday undermined my faith in his product.
the breakdown of trust in sb./sth.:  对某人某物信任的崩溃
- The product hasn't enhanced his memory, which leads to his breakdown of trust in it.
- This might explain why it leads to the breakdown of trust in mainstream sources in China.
- The breakdown of trust in his boss put him out of business.
compete with sb.: 同某人竞争
- Don't compete with anyone but you in the past.
- Decades before, I set up a furniture factory to compete with my wife.
- These workers must have competed with each other in harsher working conditions.
from various perspectives: 从各种各样的视角
- You can describe your pain from various perspectives.
- He reported cheating on his wife from various perspectives.
- This event sent my mind wandering from various perspectives.
More recently: 更近期地
- More recently, the terms the Internet and the World Wide Web are used interchangeably.
- More recently, basketball was popular with young men in China.
- More recently, people in China use the World Wide Web from their cell phones.
multiply the amount of sth.: 倍增某物的数量
- Spoiled food that you left in the kitchen last night multiplied the amount of flies.
- The pain stimulation multiplied the amount of the chemicals released by the network in his brain.
- The rise of malls on the internet has multiplied the amount of workers who lost their jobs.
sb. keeps in mind that + ...: 某人牢记...
- I keep in mind that I borrowed 1300 dollars from you.
- You should keep in mind that I have done you a favor just now.
- Keep in mind that if we work together to undertake the task, it will be finished soon.
in real time: 实时
- It couldn't be faster, because it runs a series of calculations in real time.
- We can't cut it down, sir. It's live in real time.
- The application can interact with you in real time.
at several points in the day: 在一天的几个点
- He likes to wander around the arcade at several points in the day.
- For current events, what we need to do is to watch TV news at several points in the day.
- The doctor performs experiments at several points in the day.
allow time for sth./sb. to do sth.:  给某人/某物留时间去做某事
- My boss doesn't allow time for me to perform experiments.
- Your mother tends to allow time for you to have a rest.
- We must allow time for us to stick together to go on strike.
aim for sth.: 争取某物
- The journalist aimed for an article on the puma at large in London.
- You achieve your triumphs better and faster
		when you're aiming for pleasure than when for success. 
- He always changes his job, aiming for a higher salary.
tune in to sth.: 倾听/收听某事
- Tuning in to various sources may be good for your judgments.
- Tuning in to my own spiritual need, I don't try to interact with him anymore.
- Although I have already been an adult, I still have no idea how to tune in to my inner world.
take a guess: 做猜测
- Taking a guess without any evidence is not responsible for yourself.
- What is most remarkable about him is that he has taken a great guess.
- Taking a guess may be the basic building block of studying anything.
watch out for sth.: 小心提防
- Watch out for your coworker who rates your personality behind your back.
- Watch out for the lady who is trying to steal the clothes.
- Watch out for the lady who is said to poison her five husbands in her youth.
have little connection to sth./sb.: 和某事/某物没关系
- Although we share the same basic goal, we have little connection to each other.
- She claimed that she had little connection to our boss.
- She must have little connection to the murder which was committed yesterday.
make sb. unaccountable for sth.: 使某人对于某物没有责任
- You can't make yourself unaccountable for the task you undertook.
- He has made himself unaccountable for the project to prevent himself from getting fired.
- He made her unaccountable for the loss of the ship, in return for this, she rewarded him with sex.
with A. comes B.: 伴随A来的B
- With salary comes work, I have to go to work in the subway every day.
- With the loss of money comes the rise in status, they call me Mr. Wu, not Dong.
- With privileges comes responsibilities, I must lead my people to a happy life as the leader.
ensure that + ...: 确保...
- I ensured that the virus mobilized his immune system.
- I ensured that I hadn't left my keys in the living room.
- He ensured that his boss agreed with his model of people's behaviors in public.
leave sb. less informed than before + ...: 让某人比...之前更加无知
- The tremendous mistakes which he made left him less informed
		than before he performed experiments. 
- Your help left him less informed than before he did it by himself.
- Watching TV a great deal left him less informed than before he went to university.
took the plunge: 冒险
- I decided to take the plunge.
- When I was very young, I was encouraged by my father to take the plunge.
- I was shaped by taking the plunge.
