#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-12-18 What is a gift economy
#+begin_verse
This holiday season, people around the world will give and receive presents.
You might even get a knitted sweater from an aunt.
But what if instead of saying 'thanks' before consigning it to the closet,
	the polite response expected from you was to show up to her house in a week with a better gift?
Or to vote for her in the town election?
Or let her adopt your firstborn child?

All of these things might not sound so strange if you are involved in a gift economy.
This phrase might seem contradictory.
After all, isn't a gift given for free?
But in a gift economy,
	gifts given without explicit conditions
		are used to foster a system of social ties and obligations.
While the market economies we know are formed by relationships between the things being traded,
	a gift economy consists of the relationships between the people doing the trading.
	
Gift economies have existed throughout human history.
The first studies of the concept came from anthropologists Bronislaw Malinowski and Marcel Mauss
	who describe the natives of the Trobriand islands
		making dangerous canoe journeys across miles of ocean to exchange shell necklaces and arm bands.
The items traded through this process, known as the kula ring,
		have no practical use,
	but derive importance from their original owners and carry an obligation to continue the exchange.
Other gift economies may involve useful items,
	such as the potlatch feast of the Pacific Northwest,
		where chiefs compete for prestige by giving away livestock and blankets.
We might say that instead of accumulating material wealth,
	participants in a gift economy use it to accumulate social wealth.
Though some instances of gift economies may resemble barter,
	the difference is that the original gift is given without any preconditions or haggling.
	
Instead, the social norm of reciprocity obligates recipients to voluntarily return the favor.
But the rules for how and when to do so vary between cultures,
	and the return on a gift can take many forms.
A powerful chief giving livestock to a poor man may not expect goods in return,
	but gains social prestige at the debtor's expense.
And among the Toraja people of Indonesia,
	the status gained from gift ceremonies even determines land ownership.
	
The key is to keep the gift cycle going, with someone always indebted to someone else.
Repaying a gift immediately, or with something of exactly equal value,
	may be read as ending the social relationship.
So, are gift economies exclusive to small-scale societies outside the industrialized world?
Not quite.
For one thing, even in these cultures,
	gift economies function alongside a market system for other exchanges.
And when we think about it, parts of our own societies work in similar ways.
Communal spaces, such as Burning Man, operate as a mix of barter and a gift economy,
	where selling things for money is strictly taboo.
In art and technology,
	gift economies are emerging as an alternative to intellectual property
		where artists, musicians, and open-source developers distribute their creative works,
			not for financial profit,
			but to raise their social profile or establish their community role.
And even potluck dinners and holiday gift traditions
	involve some degree of reciprocity and social norms.
	
We might wonder
	if a gift is truly a gift if it comes with obligations or involves some social pay off.
But this is missing the point.
Our idea of a free gift without social obligations prevails
	only if we already think of everything in market terms.
And in a commericialized world,
	the idea of strengthening bonds through giving and reciprocity
		may not be such a bad thing,
	wherever you may live.
#+end_verse
** expression
knit [nɪt]: v. to make clothing out of wool, using two ↑knitting needles编织
adopt [əˈdɑpt]: v. to take someone else’s child into your home and legally become its parent领养
contradictory [ˌkɑntrəˈdɪktəri]: adj. two statements, beliefs etc that are contradictory are different and therefore cannot both be true or correct相互矛盾的
obligation [ˌɑblɪˈɡeɪʃ(ə)n]: n. a moral or legal duty to do something义务
social ties: 社交关系
canoe [kəˈnu]: n. a long light boat that is pointed at both ends and which you move along using a paddle独木舟
potlatch ['pɒtˌlætʃ]: n. 冬节
chief [tʃif]: n. the most important person, or one of the most important people, in a company or organization – used especially in job titles and in news reports首领
livestock [ˈlaɪvˌstɑk]: n. animals such as cows and sheep that are kept on a farm家畜, 牲畜
blanket [ˈblæŋkɪt]: n. a cover for a bed, usually made of wool ⇨ duvet毯子
participant [pɑrˈtɪsɪpənt]: n. someone who is taking part in an activity or event参与者
barter [ˈbɑrtər]: v. to exchange goods, work, or services for other goods or services rather than for money物品交换, 实物交易
haggle [ˈhæɡ(ə)l]: v. to argue when you are trying to agree about the price of something争价bargain
norm [nɔrm]: n. generally accepted standards of social behaviour标准, 规范
reciprocity [ˌresəˈprɑsəti]: n. a situation in which two people, groups, or countries give each other similar kinds of help or special rights互惠
voluntarily ['vɒləntrəli]: adv. if you do something voluntarily, you do it willingly, without anyone telling you to do it志愿地
prestige [preˈstiʒ]: n. the respect and admiration that someone or something gets because of their success or important position in society声望
communal [kəˈmjun(ə)l]: adj. shared by a group of people or animals, especially a group who live together公共的
financial [faɪˈnænʃ(ə)l]: adj. relating to money or the management of money财政的
profit [ˈprɑfɪt]: n. money that you gain by selling things or doing business, after your costs have been paid OPP loss利润
potluck [pɑtˈlʌk] dinner: 自备餐
anthropology [ˌænθrəˈpɑlədʒi]/anthropologist: n.n. the scientific study of people, their societies, cultures etc人类学
native [ˈneɪtɪv]: n. a person who was born in a particular place本地人
----------------------------------------
This holiday season: 这个假期
consign sth. to the closet: 把某物放入壁橱
expect sth. from sb.: 期待某人某物
be involved in: 涉及到...
for free: adv.免费
without explicit conditions: 没有明显的条件
foster a system of sth.: 培养某事物的体系
be formed by: consist of
throughout human history: 贯穿人类历史
describe sb. doing sth.: 描述某人做某事
make a journey: 进行一次旅行
do sth. through this process: 通过这个过程做某事
carry an obligation to do sth.: 承担做某事的义务
give away sth.: 赠送某物
obligate sb. to do sth.: 迫使某人做某事
return the favor: 回报恩惠
take many forms: 多种形式
at sb's expense: 以某人的费用
gain sth. from sb./sth.: 从某人某物获得某物
be indebted to sb.: 对某人深表感激
be read as doing sth.: be regarded as
be exclusive to sth.: 专属于某物
social pay off: 社会回报
miss the point: 错过重点
** ch.
2014-12-18 什么是礼物经济？

在这个假日季节，世界各地的人们将互赠礼物。你甚至可能会收到一件阿姨织的毛衣。但如果你在收下礼物后，不是说“谢谢”然后把它丢进衣橱，而是需要在一周后带着更好的礼物去她家，或者在镇上的选举中为她投票，甚至是让她收养你的第一个孩子，这该怎么办？

如果你参与的是礼物经济，这些听起来可能就不那么奇怪了。这个词组可能让人觉得自相矛盾。毕竟，礼物不是免费赠送的吗？但在礼物经济中，没有明确条件的赠与是用来促进社会关系和义务的形成的。与我们所知的市场经济通过交易的物品建立关系不同，礼物经济则是通过交易的人的关系来构建的。

礼物经济在整个人类历史中都有存在。最早关于这一概念的研究来自人类学家布罗尼斯劳·马林诺夫斯基（Bronislaw Malinowski）和马塞尔·莫斯（Marcel Mauss），他们描述了特罗布里恩群岛的原住民们如何冒着生命危险，穿越数英里的海洋，交换贝壳项链和臂环。这一过程被称为库拉环（kula ring），这些交换的物品没有实际用途，但它们从原主人的身份中获得重要性，并带有继续交换的义务。

其他形式的礼物经济可能涉及有用的物品，例如太平洋西北部的“波特拉奇”盛宴（potlatch），在这里，酋长通过赠送家畜和毛毯来争夺声望。我们可以说，礼物经济的参与者并不是通过积累物质财富，而是通过积累社会财富。虽然某些礼物经济的例子可能类似于物物交换（barter），但区别在于，原始的礼物是没有任何前提或讨价还价地赠送的。

相反，互惠的社会规范要求接受礼物的人自愿回赠。但如何以及何时回赠的规则因文化而异，回赠的形式也有很多种。一位强大的酋长给一位贫穷的人家畜，可能并不期望物质回报，但却能在债务人的代价上获得社会声望。在印尼托拉贾（Toraja）人中，礼物仪式获得的地位甚至决定了土地的所有权。

关键是保持礼物循环的持续进行，总有一个人欠另一个人。立即回赠礼物，或者用等值的物品回赠，可能会被视为结束了社会关系。那么，礼物经济仅限于工业化世界之外的小规模社会吗？其实不然。一方面，即使在这些文化中，礼物经济也与市场系统共同存在，用于其他交换。

如果我们仔细想想，自己社会的一部分也以类似的方式运作。像“燃烧人”（Burning Man）这样的共同体空间，既是物物交换也是礼物经济的结合体，在那里，用钱交易的行为是严格禁忌的。在艺术和技术领域，礼物经济作为知识产权的替代方式正逐渐兴起，艺术家、音乐家和开源开发者们分发他们的创作作品，不是为了经济利益，而是为了提升自己的社会形象或建立自己的社区角色。甚至像是聚餐晚宴和节日赠礼这样的传统，也涉及到某种程度的互惠和社会规范。

我们可能会想，如果一份礼物带有义务或涉及某种社会回报，它是否还真算是礼物呢？但这是没有抓住重点。我们对于“没有社会义务的免费礼物”的想法，只有在我们已经习惯将一切都看作市场交易时才会存在。而在一个商业化的世界里，通过赠与和互惠来加强人际关系的想法，或许并不是坏事，无论你身处何地。
** sentences
This holiday season: 这个假期
- This holiday season, the famous player, Faker, has been in the Hall of LoL Fame.
- This holiday season, my nephew made a complete recovery after receiving a long-term treatment.
- This holiday season, I have performed a lot of experiments with monkeys.
consign sth. to the closet: 把某物放入壁橱
- He may have consigned the T-shirt to the closet.
- She behaved as she consigned the cat to the closet.
- The cat consigned to the closet smashed everything into pieces.
expect sth. from sb.: 期待某人某物
- I never expected a letter from a girl in my age who lives abroad.
- The left-behind children in villages are expecting calls from their parents.
- It's not that I expected pocket money from you,
		it's that your daughter expected pocket money from you.
be involved in: 涉及到...
- The man you interacted with yesterday in your house may be involved in theft.
- The chance of her being involved in murder approaches zero.
- The way to set up a factory must be involved in the local authorities.
for free: adv.免费
- Although the busmen are being on strike, I won't give you a lift for free.
- I have no idea of hitting the surface of the ball for free.
- I will provide you with some ingredients for free,
		for we share the same basic goal: complete the course.
foster a system of sth.: 培养某事物的体系
- In the process, he has fostered a system of studying English.
- The doctors who went through smallpox fostered a system of variolation.
- It begins all the way back when they fostered a system of medicine school.
be formed by: consist of
- Sir, your dinner will be formed by steaks and salads.
- The special band is formed by natives and foreigners.
- The law formed by punishments of thefts and murders became prohibited
		after the chief won the election.
throughout human history: 贯穿人类历史
- Beheading may have existed throughout human history.
- The habit of talking while having meals has existed throughout human history.
- Feasting on icy water in summer has existed throughout human history.
describe sb. doing sth.: 描述某人做某事
- He described his sister looking for the cause of the accident.
- He described her causing her daughter to play truant from school.
- He described the vampire feasting on the life force of the livestock.
make a journey: 进行一次旅行
- Why did you make a journey when your mother was having an operation in the hospital?
- He is performing a ritual that he is making a canoe journey across the lake.
- This holiday season, we loved to make a journey on weekends.
do sth. through this process: 通过这个过程做某事
- You can't fail to be fascinated by cats through this process.
- The American people gained their independence through this process.
- Mr. Leo must have made profits through this process.
carry an obligation to do sth.: 承担做某事的义务
- You can't ask me to carry an obligation to do the work of other colleagues.
- Carrying an obligation to lead a happy life, he has completed this course.
- This had an enormous impact on her so she carried an obligation to be responsible for the task.
give away sth.: 赠送某物
- My grandfather was always giving away my toys in my youth.
- The toys he gave away belong to me.
- She tended to give away the toys formed by wood and metal.
obligate sb. to do sth.: 迫使某人做某事
- No one but you can obligate you to work hard.
- The authority may have obligated the entrepreneur to make vehicles.
- The entrepreneur obligated these workers to operate in harsher working conditions.
return the favor: 回报恩惠
- He always receives a lot of gifts on Christmas day but never returns the favor.
- He gave away his livestock to return the favor.
- He gave me a pen made in China to return the favor.
take many forms: 多种形式
- The sculptures he made took many forms in this exhibition.
- The mistakes that students made in the test took many forms.
- The way in which you receive electric shocks will take many forms.
at sb's expense: 以某人的费用
- I never obligate you to give away livestock at my expense.
- You shouldn't have paid for your friends' meal at your parent's expense.
- The scientist is always delivering articles on biology at our academy's expense.
gain sth. from sb./sth.: 从某人某物获得某物
- You can only gain minimum wage from your boss so that you can fire him.
- I gained a lot of cleverness from my colleague in a pinch.
- You will gain a lot of knowledge from my course which you will take part in last week.
be indebted to sb.: 对某人深表感激
- I lent my classmate some money in a pinch so that she was indebted to me.
- I am always indebted to a man who gives me a lot of help in an emergency.
- You're protecting against a man who is indebted to you.
be read as doing sth.: be regarded as
- The rude behaviors in the cinema are read as complaints about the movie.
- The amount of pocket money you give to your nephew is read as your love for him.
- The signals are read as the prelude of abortition.
be exclusive to sth.: 专属于某物
- The seat has been exclusive to our company.
- These donkeys may be exclusive to the chief of the tribe.
- The beheading is exclusive to the punishment of murder in this country.
social payoff: 社会回报
- You needn't have asked for a social payoff.
- With social payoffs, he has devoted himself to education.
- Without any social payoff, the contributor of the open source community lost his heart.
miss the point: 错过重点
- It's more important than ever not to miss the point at the point.
- The busmen on strike missed the point while reaching an agreement.
- He noticed with dismay that his children had missed the point in the process.
