#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-05-30 How does your brain respond to pain
#+begin_verse
Let's say that it would take you ten minutes to solve this puzzle.
How long would it take
	if you received constant electric shocks to your hands?
Longer, right?
Because the pain would distract you from the task.
Well, maybe not; it depends on how you handle pain.
Some people are distracted by pain.
It takes them longer to complete a task, and they do it less well.
Other people use tasks to distract themselves from pain,
	and those people actually do the task faster and better when they're in pain
		than when they're not.
Some people can just send their mind wandering to distract themselves from pain.
How can different people be subjected to the exact same painful stimulus
	and yet experience the pain so differently?
And why does this matter?

First of all, what is pain?
Pain is an unpleasant sensory and emotional experience,
	associated with actual or potential tissue damage.
Pain is something we experience, so it's best measured by what you say it is.
Pain has an intensity;
	you can describe it on a scale from zero, no pain, to ten, the most pain imaginable.
But pain also has a character, like sharp, dull, burning, or aching.
What exactly creates these perceptions of pain?

Well, when you get hurt,
	special tissue damage-sensing nerve cells, called nociceptors,
		fire and send signals to the spinal cord and then up to the brain.
Processing work gets done by cells called neurons and glia.
This is your Grey matter.
And brain superhighways carry information as electrical impulses from one area to another.
This is your white matter.
The superhighway that carries pain information from the spinal cord to the brain
	is our sensing pathway that ends in the cortex,
		a part of the brain that decides what to do with the pain signal.
		
Another system of interconnected brain cells called the salience network
	decides what to pay attention to.
Since pain can have serious consequences,
	the pain signal immediately activates the salience network.
Now, you're paying attention.
The brain also responds to the pain and has to cope with these pain signals.
So, motor pathways are activated to take your hand off a hot stove, for example.
But modulation networks are also activated that deliver endorphins and enkephalins,
		chemicals released when you're in pain or during extreme exercise,
	creating the runner's high.
These chemical systems help regulate and reduce pain.
All these networks and pathways work together to create your pain experience,
		to prevent further tissue damage, and help you to cope with pain.
	
This system is similar for everyone,
	but the sensitivity and efficacy of these brain circuits
		determines how much you feel and cope with pain.
This is why some people have greater pain than others
	and why some develop chronic pain that does not respond to treatment, while others respond well.
Variability in pain sensitivities is not so different
	than all kinds of variability in responses to other stimuli.
Like how some people love roller coasters, but other people suffer from terrible motion sickness.

Why does it matter that there is variability in our pain brain circuits?
Well, there are many treatments for pain, targeting different systems.
For mild pain, non-prescription medications can act on cells where the pain signals start.
Other stronger pain medicines and anesthetics work
	by reducing the activity in pain-sensing circuits or boosting our coping system, or endorphins.
Some people can cope with pain using methods
	that involve distraction, relaxation, meditation, yoga,
		or strategies that can be taught, like cognitive behavioral therapy.
For some people who suffer from severe chronic pain,
		that is pain that doesn't go away months after their injury should have healed,
	none of the regular treatments work.
Traditionally, medical science has been about testing treatments on large groups
	to determine what would help a majority of patients.
But this has usually left out some
	who didn't benefit from the treatment or experienced side effects.
Now, new treatments
		that directly stimulate or block certain pain-sensing attention or modulation networks
	are being developed,
		along with ways to tailor them to individual patients,
		using tools like magnetic resonance imaging to map brain pathways.
Figuring out how your brain responds to pain is the key to finding the best treatment for you.
That's true	personalized medicine.
#+end_verse
** expression
stimulus [ˈstɪmjələs]: n. something that helps a process to develop more quickly or more strongly刺激
matter [ˈmætər]: v. to be important, especially to be important to you, or to have an effect on what happens
sensory [ˈsensəri]: adj. relating to or using your senses of sight, hearing, smell, taste, or touch感觉的, 感官的
tissue [ˈtɪʃu]: n. the material forming animal or plant cells组织
intensity [ɪnˈtensɪti]: n. technical the strength of something such as light or sound强度
dull [dʌl]: adj. a dull pain is not severe but does not stop OPP sharp迟钝的,枯燥的
damage-sensing [ˈdæmɪdʒ][sensɪŋ]: adj. 疼痛感知
nociceptor [ˌnoʊsɪ'septə]: n. 伤害感受器
spinal cord [ˈspaɪn(ə)l][kɔrd]: 脊髓
neuron [ˈnʊˌrɑn]: n. a type of cell that makes up the ↑nervous system and sends messages to other parts of the body or the brain SYN nerve cell神经元
glia ['glaɪə]: n. 神经胶质
superhighway [ˌsupərˈhaɪˌweɪ]: n. a very large road on which you can drive fast for long distances超级高速公路
electrical impulses [ɪˈlektrɪk(ə)l][ˈɪmˌpʌls] : 电子脉冲
cortex [ˈkɔrˌteks]: n. the outer layer of an organ in your body, especially your brain(脑或肾的)皮层, 皮质
salient [ˈseɪliənt] / salience: adj.n. the salient points or features of something are the most important or most noticeable parts of it
modulate [ˈmɑdʒəˌleɪt] / modulation: v.n. to change a process or activity to make it more controlled, slower, less strong etc调制
endorphin [enˈdɔrfɪn]: n. a chemical produced by your body that reduces pain and can make you feel happier内啡肽
enkephalin [en'kefəlɪn]: n. 脑啡肽
sensitivity [ˌsensəˈtɪvəti]: n. 敏感, 灵敏(度), 灵敏性
brain circuits [ˈsɜrkɪt]: 脑回路
roller coasters [ˈroʊlər][ˈkoʊstər]: 过山车
motion [ˈmoʊʃ(ə)n]: v. the process of moving or the way that someone or something moves动作
target [ˈtɑrɡət]: v. to make something have an effect on a particular limited group or area针对
mild [maɪld]: adj. a mild illness or health problem is not serious温和的
non-prescription [prɪˈskrɪpʃ(ə)n]: n. a non-prescription drug is one that you can buy in a shop without a written order from a doctor SYN over-the-counter无处方
anesthetic [ˌænəsˈθetɪk]: n. a drug that stops you feeling pain麻药
pain-sensing: adj. 感受痛觉的
map [mæp]: v. to discover or show information about something, especially about its shape or arrangement, or how it moves or works映射
----------------------------------------
receive electric shocks to sb's hands/arms: 某人的手/胳膊受到点击
distract sb. from sth.: 分散某人对于某事的注意
do sth. faster and better when +... than when +...: 做某事更好快当A比当B
send sb's mind wandering: 使某人心烦意乱
be subjected to sth.: 遭受某事
describe sth. on a scale from A. to B.: 用从A到B程度来描述某物
respond to sth.: 对某事作出反应
cope with sth.: 应对某事
take sb. hand off sth.: 把某人的手从某物上拿开
act on sth.: 对...起作用
along with ways to do sth.: 伴随着做某事的方法
tailor sth. to sb.: 为某人量身定做
the key to doing sth.: 做某事的关键
** sentences
receive electric shocks to sb's hands/arms: 某人的手/胳膊受到点击
- I can't pay attention to Mr. Leo when I receive electric shocks to my legs.
- After receiving electric shocks to our ass together in the prison,
		we have been bonded to each other.
- He received electric shocks to his hands in the face of the security of the supermarket.
distract sb. from sth.: 分散某人对于某事的注意
- The nurse succeeded in distracting the girl from the needle.
- If the bird hadn't distracted me from the course, I would have passed the test.
- You needn't have distracted you from the drop in salary.
do sth. faster and better when +... than when +...: 做某事更好快当A比当B
- I find out that I finish homework faster and better
		when I have had a good sleep than when I haven't.
- She cooks faster and better when she is at home than when she is at her friend's apartment.
- You behave better when you're in a good mood than when you lose your temper.
send sb's mind wandering: 使某人心烦意乱
- Getting his children far away from him has sent his mind wandering a great deal.
- What my wife communicated with me sent my mind wandering.
- My car has broken down and it sends my mind wandering.
be subjected to sth.: 遭受某事
- These workers needn't have been subjected to harsher working conditions.
- My niece is being subjected to a serious injury.
- People all over the world will be subjected to smallpox.
describe sth. on a scale from A. to B.: 用从A到B程度来描述某物
- We usually describe the English level on a CEFR scale from A1 to C2.
- We'd better describe the job rank on a scale from one to three.
- We describe the English level on a CEFR scale from A1 to C2
		so that we can judge our English level by ourselves.
respond to sth.: 对某事作出反应
- The best way to respond to your wife's violence is to ignore it.
- He failed to respond to her smile.
- The treatment may not respond to you.
cope with sth.: 应对某事
- She will have to cope with scars and scabs for the rest of her life.
- Coping with the pustules immediately is good for your health.
- His body developed fevers to cope with the rare virus. 
take sb. hand off sth.: 把某人的手从某物上拿开
- Take your hand off my hip, she shouted at him.
- You must take your hand off the bucket when its wick ignites.
- You should take your hand off the corpse.
act on sth.: 对...起作用
- They believed that beheading acted on the so-called vampires.
- The mixture acted on his bone to prevent it from decomposing in the air.
- They're performing experiments to examine whether the medicine acts on the cell.
along with ways to do sth.: 伴随着做某事的方法
- My English is improving along with ways to read, listen, write, and speak daily.
- His triumphs in business are achieved along with ways to set up a furniture factory.
- The evidence is accumulating along with ways to search the scene.
tailor sth. to sb.: 为某人量身定做
- The tiger is feasting on the foods tailored to it.
- His wife is tailoring a shirt to him.
- He used to sustain himself by tailoring clothes to others.
the key to doing sth.: 做某事的关键
- The key to finishing the task is to divide it into several steps.
- The key to cooking this dish is mixing the salt at the right point.
- The key to making a profit is to establish a law prohibiting parking in public.
