#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-04-18 Not all scientific studies are created equal
#+begin_verse
Studies have shown that taking vitamins is good for your health and bad for your health.
That newly discovered herb can improve your memory or destroy your liver.
Headlines proclaim a promising new cancer treatment and never mention it again.
On a daily basis, we are bombarded with attention-grabbing news, backed up by scientific studies,
	but what are these studies?
How are they performed?
And how do we know whether they're reliable?

When it comes to dietary or medical information,
	the first thing to remember is
		that while studies on animals or individual cells can point the way towards further research,
			the only way to know how something will affect humans
				is through a study involving human subjects.
And when it comes to human studies,
	the scientific gold standard is the randomized clinical trial, or RCT.
The key to RCTs is that the subjects are randomly assigned to their study groups.
They are often blinded to make them more rigorous.
This process attempts to ensure
	that the only difference between the groups is the one the researchers are attempting to study.
For example, when testing a new headache medication,
	a large pool of people with headaches would be randomly divided into two groups,
		one receiving the medication and another receiving a placebo.
With proper randomization,
	the only significant overall difference between the two groups
		will be whether or not they received the medication,
			rather than other differences that could affect results.
Randomized clinical trials are incredible tools,
	and, in fact, the US Food and Drug Administration often requires at least two to be conducted
		before a new drug can be marketed.
		
But the problem is that an RCT is not possible in many cases,
	either because it's not practical or would require too many volunteers.
In such cases, scientists use an epidemiological study,
		which simply observes people going about their usual behavior,
	rather than randomly assigning active participants to control invariable groups.
Let's say we wanted to study whether an herbal ingredient on the market causes nausea.
Rather than deliberately giving people something that might make them nauseated,
	we would find those who already take the ingredient in their everyday lives.
This group is called the cohort.
We would also need a comparison group of people who do not have exposure to the ingredient.
And we would then compare statistics.
If the rate of nausea is higher in the herbal cohort,
	it suggests an association between the herbal supplement and nausea.
Epidemiological studies are great tools to study the health effects of almost anything,
	without directly interfering in people's lives
		or assigning them to potentially dangerous exposures.
		
So, why can't we rely on these studies
	to establish causal relationships between substances and their effects on health?
The problem is that even the best conducted epidemiological studies have inherent flaws.
Precisely because the test subjects are not randomly assigned to their groups.
For example, if the cohort in our herbal study consisted of people
		who took the supplement for health reasons,
	they may have already had higher rates of nausea than the other people in the sample.
Or the cohort group could've been composed of people
	who shop at health food stores and have different diets or better access to healthcare.
These factors that can affect results, in addition to the factor being studied,
	are known as confounding variables.
These two major pitfalls,
			combined with more general dangers, such as conflicts of interest or selective use of data,
		can make the findings of any particular epidemiological study suspect,
	and a good study must go out of its way to prove
		that its authors have taken steps to eliminate these types of errors.
		
But even when this has been done,
	the very nature of epidemiological studies,
			which examine differences between preexisting groups,
			rather than deliberately inducing changes within the same individuals,
		means that a single study can only demonstrate a correlation
				between a substance and a health outcome,
			rather than a true cause and effect relationship.
At the end of the day, epidemiological studies have served as excellent guides to public health,
	alerting us to critical health hazards, such as smoking, asbestos, lead, and many more.
But these were demonstrated through multiple, well-conducted epidemiological studies,
	all pointing in the same direction.
So, the next time you see a headline about a new miracle cure
		or the terrible danger posed by an everyday substance,
	try to learn more about the original study
			and the limitations inherent in any epidemiological study or clinical trial
		before jumping to conclusions.
#+end_verse
** expression
herb [ɜrb]: n. a small plant that is used to improve the taste of food, or to make medicine ⇨ spice药草
liver [ˈlɪvər]: n. a large organ in your body that produces ↑bile and cleans your blood肝脏
vitamin [ˈvaɪtəmɪn]: n. a chemical substance in food that is necessary for good health维他命, 维生素
headline [ˈhedˌlaɪn]: n. the title of a newspaper report, which is printed in large letters above the report大字标题
attention-grabbing: adj. 引人注意的
proclaim [prəˈkleɪm]: v. to say publicly or officially that something important is true or exists声明
promising [ˈprɑmɪsɪŋ]: adj. showing signs of being successful or good in the future有前途的
dietary [ˈdaɪəˌteri]: adj. related to the food someone eats饭食的
randomized [ˈrændəmaɪz]: adj. to choose things in a way that is not carefully controlled or planned in order to do a scientific test随机化的
clinical [ˈklɪnɪk(ə)l]: adj. relating to treating or testing people who are sick临床的, 病房用的
trial [ˈtraɪəl]: n. a process of testing to find out whether something works effectively and is safe试验
rigorous [ˈrɪɡərəs]: adj. careful, thorough, and exact严格的
medication [ˌmedɪˈkeɪʃ(ə)n]: n. medicine or drugs given to people who are ill药物治疗
placebo [pləˈsiboʊ]: n. a harmless substance given to a sick person instead of medicine, without telling them it is not real. 安慰剂
significant [sɪɡˈnɪfɪkənt]: adj. having an important effect or influence, especially on what will happen in the future OPP insignificant有意义的, 重大的, 重要的
overall [ˈoʊvərˌɔl]: adj. considering or including everything全部的, 全面的
epidemiology [ˌepɪdimiˈɑlədʒi]/epidemiological: n.adj. the study of the way diseases spread, and how to control them流行病学
nausea [ˈnɔːziə]: n. the feeling that you have when you think you are going to ↑vomit (=bring food up from your stomach through your mouth) SYN sickness反胃
cohort [ˈkoʊˌhɔrt]: n. technical a group of people of the sage, social class etc, especially when they are being studied一群(组)
substance [ˈsʌbstəns]: n. a particular type of solid, liquid, or gas物质
inherent [ɪnˈherənt]: adj. a quality that is inherent in something is a natural part of it and cannot be separated from it固有的, 内在的, 与生俱来的
flaw [flɔ]: n. a mistake, mark, or weakness that makes something imperfect SYN defect瑕疵
confound [kənˈfaʊnd]: v. to confuse and surprise people by being unexpected混淆
pitfall [ˈpɪtˌfɔl]: n. a problem or difficulty that is likely to happen in a particular job, course of action, or activity缺陷
eliminate [ɪˈlɪməˌnet]: v. to defeat a team or person in a competition, so that they no longer take part in it SYN knock out淘汰
critical [ˈkrɪtɪk(ə)l]: adj. something that is critical is very important because what happens in the future depends on it SYN crucial至关重要的
hazard [ˈhæzərd]: n. something that may be dangerous, or cause accidents or problems冒险
asbestos [æzˈbestəs]: n. a grey mineral that does not burn easily, that was used in the past as a building material or in protective clothing石棉
lead [lid]: n. a soft heavy grey metal that melts easily and is poisonous, used to cover roofs, or in the past, for water pipes. It is a chemical ↑element: symbol Pb铅
cure [kjʊr]: v.n. a medicine or medical treatment that makes an illness go away治愈
--------------------
Studies have shown that + ...: 研究证明
be bombarded with sth.: 被某物轰炸
be backed up by sth.: 被某物堆积
point the way towards sth.: 指出去某物/处的路
be assigned to sth./ assign sb. to sth.: 被分派到(组/队)
with headaches: 患头痛
be divided into sth.: 被分成...
a comparison group of ...: ...的对照组
have exposure to sth.: 接触某物
establish causal relationships between sth.(pl.): 建立某物之间的因果关系
in addition to: 除...之外
be combined with sth.: 与...结合
go out of sb's way to do sth.: 给自己带来不便或额外的麻烦去做超出要求的事情
take steps (to do sth.): 采取措施(去做某事)
induce changes within ...: 在...内部引起变化
demonstrate a correlation between sth.(pl.): 说明了事物间的相互关系
At the end of the day: 最终
alert sb. to sth.: 提醒某人注意某事
** sentences
Studies have shown that + ...: 研究证明
- Studies have shown that a fossil is often millions of years in the making.
- Studies have shown that holding that pose for half an hour a day is good for your health.
- Studies have shown that taking vitamins is beneficial for your teeth.
be bombarded with sth.: 被某物轰炸
- Bombarded with a bomb, he must have been killed in action.
- Bombarded with a bomb, the enemies must have lost their hearts.
- We must deliberate over the chance of being bombarded with bombs.
be backed up by sth.: 被某物堆积
- Our garage has been backed up by the bodies of pigeons.
- In this great adventure of crossing the Atlantic, our compartment has been backed up by food.
- The door shall not be backed up by anything.
point the way towards sth.: 指出去某物/处的路
- In these early days, there were some people in Shanghai
		pointing the way towards the destinations of tourists to make money.
- This experiment points the way toward the right proportions of ingredients.
- The search for extraterrestrial life points the way toward cancer treatment.
be assigned to sth./ assign sb. to sth.: 被分派到(组/队)
- I have been long assigned to the fans of Jay Chou.
- Assigned to the 'guard of honor', he was practicing in harsher working conditions.
- Assigned to the 'guard of honor', he caught the eye of the one he loved.
with headaches: 患头痛
- With a headache, I must draw energy from healthy foods.
- With a headache, he stopped to ask for leave.
- With a headache, he couldn't deliberate at length over his job.
be divided into sth.: 被分成...
- The stake might be divided into several parts if you hit the surface of it.
- She got very angry and the toy was divided into three parts.
- Fingers crossed the computer will not be divided into several pieces after the earthquake.
a comparison group of ...: ...的对照组
- A comparison group of viruses will infect these people.
- The comparison group of foods might have been thrown away.
- A comparison group of foods has already decayed away.
have exposure to sth.: 接触某物
- She had exposure to the fossil on a creek bank.
- Until you have exposure to her hands, you're not in the clear yet.
- Having had exposure to a special kind of mixture, he extracted gold from these sands.
establish causal relationships between sth.(pl.): 建立某物之间的因果关系
- These scientists were trying to establish causal relationships between cancers and smoking.
- I can't establish causal relationships between weather and food shortage in the earth.
- He established causal relationships between monogamy and democracy.
in addition to: 除...之外
- In addition to him, we played truant from school.
- In addition to the election, he has been eliminated all the time.
- In addition to his studies, he became independent from his family.
be combined with sth.: 与...结合
- My manager always asks me to combine our project with more extensions in another platform.
- It tastes great. The bread is combined with milk.
- His money was combined with his father's idea so that he ran a successful furniture business.
go out of sb's way to do sth.: 给自己带来不便或额外的麻烦去做超出要求的事情
- In my youth, I always went out of my way to finish my homework.
- I get tired of going out of my wife to ask for your happiness.
- He went out of his way to ease restrictions on drugs in this state.
take steps (to do sth.): 采取措施(去做某事)
- He took steps to improve the life force of the ant.
- The vampire hasn't taken steps to feast on the life force of humans.
- They have one common characteristic: they take steps to make money in their youth.
induce changes within ...: 在...内部引起变化
- The stalk of the enemy might have induced changes in our party.
- As the brutal executions have been prohibited,
		it has induced changes within people in this state.
- The stalk of the enemy must have induced changes in our party.
demonstrate a correlation between sth.(pl.): 说明了事物间的相互关系
- The doctor demonstrates a correlation between the lungs and heart.
- Mr. Leo demonstrated a correlation between reading and speaking in English in his course.
- Mr. Leo demonstrated a correlation between wisdom and Critical Thinking last Saturday.
At the end of the day: 最终
- At the end of the day, he sustains himself by running a furniture business.
- At the end of the day, he discerned the cause of these people who have committed a murder.
- At the end of the day, the authorities established a law prohibiting digging up corpses.
alert sb. to sth.: 提醒某人注意某事
- He alerted me to the meeting which would be held last Saturday.
- I'm tired of being alerted to the bugs you made because of your carelessness.
- I alerted him to the blood at the corners of his mouth.
