#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2014-11-05 Why elephants never forget?
#+begin_verse
It's a common saying that elephants never forget,
	but these magnificent animals are more than giant walking hard drives.
The more we learn about elephants,
	the more it appears
		that their impressive memory is only one aspect of an incredible intelligence
			that makes them some of the most social, creative, and benevolent creatures on Earth.
			
Unlike many proverbs, the one about elephant memory is scientifically accurate.
Elephants know every member in their herd,
	able to recognize as many as 30 companions by sight or smell.
This is a great help when migrating or encountering other potentially hostile elephants.
They also remember and distinguish particular cues that signal danger
	and can recall important locations long after their last visit.
But it's the memories unrelated to survival that are the most fascinating.
Elephants remember not only their herd companions
	but other creatures who have made a strong impression on them.
In one case, two circus elephants that had briefly performed together
	rejoiced when crossing paths 23 years later.
This recognition isn't limited to others of their species.
Elephants have also recognized humans they've bonded with after decades apart.
All of this shows that elephant memory goes beyond responses to stimuli.

Looking inside their heads, we can see why.
The elephant boasts the largest brain of any land mammal,
	as well as an impressive encephalization quotient.
This is the size of the brain relative to what we'd expect for an animal's body size,
	and the elephant's EQ is nearly as high as a chimpanzee's.
And despite the distant relation,
	convergent evolution has made it remarkably similar to the human brain,
		with as many neurons and synapses and a highly developed hippocampus and cerebral cortex.
It is the hippocampus, strongly associated with emotion,
	that aids recollection by encoding important experiences into long-term memories.
The ability to distinguish this importance
	makes elephant memory a complex and adaptable faculty beyond rote memorization.
It's what allows elephants who survived a drought in their youth
		to recognize its warning signs in adulthood,
	which is why clans with older matriarchs have higher survival rates.
Unfortunately,
	it's also what makes elephants one of the few non-human animals
		to suffer from post-traumatic stress disorder.
The cerebral cortex, on the other hand, enables problem solving,
	which elephants display in many creative ways.
They also tackle problems cooperatively,
	sometimes even outwitting the researchers and manipulating their partners.
And they've grasped basic arithmetic,
	keeping track of the relative amounts of fruit in two baskets after multiple changes.
The rare combination of memory and problem solving
		can explain some of elephants' most clever behaviors,
	but it doesn't explain some of the things we're just beginning to learn about their mental lives.
	
Elephants communicate using everything from body signals and vocalizations,
	to infrasound rumbles that can be heard kilometers away.
And their understanding of syntax suggests that they have their own language and grammar.
This sense of language may even go beyond simple communication.
Elephants create art by carefully choosing and combining different colors and elements.
They can also recognize twelve distinct tones of music and recreate melodies.
And yes, there is an elephant band.
But perhaps the most amazing thing about elephants
	is a capacity even more important than cleverness:
		their sense of empathy, altruism, and justice.
Elephants are the only non-human animals to mourn their dead,
	performing burial rituals and returning to visit graves.
They have shown concern for other species, as well.
One working elephant refused to set a log down into a hole where a dog was sleeping,
	while elephants encountering injured humans have sometimes stood guard
		and gently comforted them with their trunk.
		
On the other hand,
	elephant attacks on human villages have usually occurred
		right after massive poachings or cullings,
	suggesting deliberate revenge.
When we consider all this evidence,
	along with the fact that elephants are one of the few species
		who can recognize themselves in a mirror,
	it's hard to escape the conclusion that they are conscious, intelligent, and emotional beings.
	
Unfortunately, humanity's treatment of elephants does not reflect this,
	as they continue to suffer from habitat destruction in Asia,
		ivory poaching in Africa, and mistreatment in captivity worldwide.
Given what we now know about elephants
		and what they continue to teach us about animal intelligence,
	it is more important than ever to ensure
		that what the English poet John Donne described as 'nature's great masterpiece'
			does not vanish from the world's canvas.
#+end_verse
** expression
walking hard drive: 行走硬盘
magnificent [mæɡˈnɪfɪs(ə)nt]: adj. very good or beautiful, and very impressive宏伟的
benevolent [bəˈnevələnt]: adj. kind and generous慈善的
proverb [ˈprɑˌvɜrb]: n. a short well-known statement that gives advice or expresses something that is generally true.谚语
accurate [ˈækjərət]: adj. correct and true in every detail正确的, 精确的
encounter [ɪnˈkaʊntər]: v. to experience something, especially problems or opposition遭遇
hostile [ˈhɑst(ə)l]: adj. angry and deliberately unfriendly towards someone, and ready to argue with them敌对的
recall [ˈriˌkɔl]: v. to remember a particular fact, event, or situation from the past回想
herd [hɜrd]: n. a group of animals of one kind that live and feed together ⇨ flock兽群, 牧群
companion [kəmˈpænjən]: n. someone you spend a lot of time with, especially a friend同伴
drought [draʊt]: n. a long period of dry weather when there is not enough water for plants and animals to live干旱
circus [ˈsɜrkəs]: n. a group of people and animals who travel to different places performing skilful tricks as entertainment马戏团
rejoice [rɪˈdʒɔɪs]: v. literary to feel or show that you are very happy(使)欣喜
boast [boʊst]: v. if a place, object, or organization boasts something, it has something that is very good以有...而自豪
encephalization quotient: Brain-To-Body脑化指数
mammal [ˈmæm(ə)l]: n. a type of animal that drinks milk from its mother’s body when it is young. Humans, dogs, and whales are mammals哺乳动物
converge [kənˈvɜrdʒ]/convergent: v.adj. to come from different directions and meet at the spoint to become one thing会聚
synapse [ˈsɪnæps]: n. the place where nerve cells meet, especially in the brain突触
developed [dɪˈveləpt]: adj. a developed sense, system etc, is better, larger, or more advanced than others发达
hippocampus [ˌhɪpə'kæmpəs]: n. 海马体
cerebral [səˈribrəl]: adj. medical relating to or affecting your brain大脑的
recollection [ˌrekəˈlekʃ(ə)n]: n. something from the past that you remember回忆
faculty [ˈfæk(ə)lti]: n. a natural ability, such as the ability to see, hear, or think clearly本能
rote [roʊt]: v. formal when you learn something by repeating it many times, without thinking about it carefully or without understanding it死记硬背, 机械的做法, 生搬硬套
clan [klæn]: n. a large group of families who often share the namies 部落
matriarch [ˈmeɪtriˌɑrk]: n. a woman, especially an older woman, who controls a family or a social group女家长
cooperative [koʊˈɑp(ə)rətɪv]/cooperatively: adj.adv. willing to cooperate SYN helpful OPP uncooperative合作的
outwit [aʊtˈwɪt]: v. to gain an advantage over someone using tricks or clever plans瞒骗, 以智取胜
manipulate [məˈnɪpjəˌleɪt]: v. to make someone think and behave exactly as you want them to, by skilfully deceiving or influencing them(熟练地)操作, 使用(机器等), 操纵
grasp [ɡræsp]: v. to take and hold something firmly SYN grip抓住, 抓紧, 掌握, 领会
post-traumatic stress disorder: 创伤后压力紊乱
arithmetic [əˈrɪθmətɪk]: n. the science of numbers involving adding, multiplying etc算术
vocalize [ˈvoʊk(ə)lˌaɪz]/vocalization: v.n. to make a sound or sounds with your voice有声
infrasound ['ɪnfrəˌsaʊnd]: n. 次声
rumble [ˈrʌmb(ə)l]: n. a series of long low sounds隆隆声
syntax [ˈsɪnˌtæks]: n. the way words are arranged to form sentences or phrases, or the rules of grammar which control this句法
tone [toʊn]: n. the way your voice sounds, which shows how you are feeling or what you mean语调
recreate [ˌrikriˈeɪt]: v. to make something from the past exist again in a new form or be experienced again SYN recapture再创造
melody [ˈmelədi]: n. a song or tune悦耳的音调
altruism [ˈæltrʊˌiz(ə)m]: n. when you care about or help other people, even though this brings no advantage to yourself利他
mourn [mɔrn]: v. to feel very sad because something no longer exists or is no longer as good as it used to be哀悼
burial ritual: 葬礼仪式
log [lɔɡ]: n. a thick piece of wood from a tree原木
trunk [trʌŋk]: n. the very long nose of an ↑elephant象鼻
massive [ˈmæsɪv]: adj. very large, solid, and heavy厚重的, 大块的, 魁伟的, 结实的
poach [poʊtʃ]: v. to do something that is someone else’s responsibility, especially when they do not want you to do it偷猎
cull [kʌl]: v. to kill animals so that there are not too many of them, or so that a disease does not spread猎杀
revenge [rɪˈvendʒ]: v. something you do in order to punish someone who has harmed or offended you复仇
ivory [ˈaɪvəri]: n. the hard smooth yellowish-white substance from the ↑tusks (=long teeth) of an ↑elephant象牙
----------------------------------------
It's a common saying that + ...: 常言道...
it appears that + ...: 看起来似乎
as many as num. sth.: 多达num.个
make a strong impression on sb.: 给某人造成深刻的印象
In one case: 在某种情况下
cross paths (with sb.): (与某人)相遇
sth. isn't limited to sb.: 某物/能力不限于某人
after days/months/years/decades apart: 几十年分别之后
go beyond sth.: 超过某物
encode A. into B.: 把某物A编入某物B
in adulthood: 在成年期
tackle problems: 解决问题
keep track of sth.: 跟踪某事
shown concern for sth./sb.: 爱护某人/物
stand guard: 站岗守卫
comfort sb. with sth.: 用某物安慰某人
it's hard to escape the conclusion that + ...: 很难不得出结论...
in captivity: 在关押
Given what + ...: 鉴于...
It is more important than ever to do sth.: 做某事比以往任何时候更重要
vanish from sp.: 从...消失
** ch.
2014-11-05 为什么大象永远不忘记？

“大象永远不忘记”是一个常见的说法，但这些雄伟的动物远不止是巨大的行走硬盘。我们对大象了解得越多，越能发现它们令人印象深刻的记忆力只是它们非凡智慧的一个方面，使得它们成为地球上最具社交性、最具创造力和最富有慈善心的生物之一。

与许多谚语不同，关于大象记忆的说法是科学上准确的。大象能记住它们群体中的每一个成员，能够通过视力或嗅觉认出多达30个同伴。当迁徙或遇到其他可能敌对的大象时，这种记忆力非常有帮助。它们还能记住并区分出危险信号，并能够在很久没有去过的地方回忆起重要的地点。但最令人着迷的是与生存无关的记忆。大象不仅记得它们群体中的同伴，还记得那些给它们留下深刻印象的其他生物。在一个案例中，曾一起短暂演出的两只马戏团大象，在23年后重逢时欣喜若狂。这种认知不仅限于同种动物之间。大象也能认出与它们建立了联系的人类，即便是分离了几十年后。所有这些都表明，大象的记忆力超越了对刺激的反应。

那么，为什么会这样呢？让我们从大象的大脑来看。大象拥有所有陆地哺乳动物中最大的脑袋，以及令人印象深刻的脑容量商（EQ）。脑容量商是指动物大脑的大小与其体型所期望的大小之比，大象的脑容量商几乎与黑猩猩相当。尽管它们之间有着较远的亲缘关系，但趋同进化使得大象的大脑在许多方面与人类的大脑非常相似，大象的大脑拥有相当多的神经元和突触，以及高度发达的海马体和大脑皮层。海马体与情感密切相关，它通过将重要的经历编码为长期记忆来帮助回忆。能够区分这些重要性，使得大象的记忆力成为一种复杂且适应性强的能力，远远超出了死记硬背。这也是为什么那些在年轻时经历过干旱的大象，能在成年后识别其警告信号，并且为什么拥有年长母象的族群具有更高的生存率。不幸的是，这也是为什么大象是少数几种患有创伤后应激障碍（PTSD）非人类动物之一。

另一方面，大脑皮层使大象能够进行问题解决，大象通过许多创造性的方式展示了这一点。它们还会合作解决问题，有时甚至会智胜研究人员，操控它们的伙伴。而且它们掌握了基本的算术，能够在多次变化后保持对两个篮子中水果相对数量的记录。记忆力和问题解决能力的罕见结合，能够解释大象一些最聪明的行为，但它并不能解释一些我们刚开始了解的大象精神世界的事物。

大象通过各种方式进行交流，从身体信号和声音，到能够传播数公里的次声波。它们对句法的理解表明，它们拥有自己的语言和语法。这种语言感甚至可能超越简单的交流。大象通过精心选择和组合不同的颜色和元素来创作艺术。它们还能识别出12种不同的音乐音调并重新演绎旋律。没错，大象确实有一个乐队。但也许大象最令人惊叹的地方在于它们拥有比聪明才智更重要的能力：它们的同理心、利他主义和正义感。大象是唯一会为死去的同伴哀悼的非人类动物，它们会举行葬礼仪式并返回墓地祭拜。它们也对其他物种表现出了关心。有一只工作大象拒绝将一根木头放进狗正在睡觉的洞里，而在遇到受伤的人类时，大象有时会守护在旁，并用它们的象鼻轻轻安慰他们。

另一方面，大象对人类村庄的攻击通常发生在大规模偷猎或屠宰之后，表明它们有意进行报复。当我们考虑所有这些证据，以及大象是少数能够在镜子中认出自己影像的物种之一时，我们很难不得出结论：它们是有意识、聪明且富有情感的生物。

不幸的是，人类对待大象的方式并未体现这一点，它们仍然在亚洲遭受栖息地破坏，在非洲遭受象牙偷猎，且在全球范围内遭受圈养虐待。鉴于我们现在对大象的了解，以及它们继续向我们展示动物智慧的方式，确保我们英格兰诗人约翰·多恩所描述的“自然伟大杰作”不从世界的画布上消失，比以往任何时候都更加重要。
** sentences
It's a common saying that + ...: 常言道...
- It's a common saying that it's never too old to learn.
- It's a common saying that where there is a will there is a way.
- It's a common saying that writing makes one precise.
it appears that + ...: 看起来似乎
- It appeared that she smashed everything in the kitchen into pieces.
- It appeared that the police had arrived on the scene in time.
- It appears that I am at work on time.
as many as num. sth.: 多达num.个
- My manager complained that as many as 5 workers have been late.
- As many as thousands of workers have been trapped in the mine.
- He told my parents that I had eaten as many as 5 apples.
make a strong impression on sb.: 给某人造成深刻的印象
- The lady who is eager to eat made a strong impression on me.
- The abortion of my wife last week made a strong impression on me.
- The portal embedded into the mountain made a strong impression on me.
In one case: 在某种情况下
- In one case, workers can't refuse to be in harsher working conditions.
- In one case, the number of coverages increases exponentially. 
- In one case, both hostile countries stuck together to defend enemies.
cross paths (with sb.): (与某人)相遇
- To my surprise, she crossed paths with her ex-girlfriend in the arcade.
- I crossed paths with a man who works for Apple.
- The hostile elephants crossed paths with each other on a creek bank. 
sth. isn't limited to sb.: 某物/能力不限于某人
- The ability to recognize colors isn't limited to human beings.
- The ability to get a good salary isn't limited to the mean you.
- The chance to develop a model for an atom isn't limited to Chemists.
after days/months/years/decades apart: 几十年分别之后
- You became less confident than before after decades apart.
- You have lost your attraction to me after years apart.
- He is flooded with business after days apart.
go beyond sth.: 超过某物
- His plan that the World Wide Web connects everyone in the world goes beyond ethnicity and sex.
- If you want to get a good grade, you must go beyond the requirements of your teacher.
- Going beyond limitation, she succeeded in breaking the world record again.
encode A. into B.: 把某物A编入某物B
- In one case, an elephant will encode his experiences into long memories.
- He encoded his emotions into his paintings, which enhanced his memories a great deal.
- This might explain why elephants encode their experiences into long memories.
in adulthood: 在成年期
- This special kind of bird is known for their enormous wingspan in adulthood.
- Some people used to dislike roller coasters in their youth, but love them in adulthood.
- It seems strange that I love rice in adulthood which I hated in the past.
tackle problems: 解决问题
- She is an expert at tackling English problems.
- Although he is receiving electric shocks, he is trying to tackle problems.
- He tackles problems faster and better when he has a lot of food than when he is hungry.
keep track of sth.: 跟踪某事
- It reminded me of some code I made when keeping track of his program.
- Keeping track of the bug you made, you learned a lot about computer programs.
- Keeping track of the rhythm of the music, the snake began to dance.
shown concern for sth./sb.: 爱护某人/物
- My aunt, Lucy, always shows concern for us when we are on our birthday.
- He must have shown concern for his brother.
- The host is showing concern for the actor who is nominated for the prize.
stand guard: 站岗守卫
- I would rather stand guard than wander around the street.
- You have the privilege of standing guard for the princess.
- While two detectives were standing guard in front of the door, they opened the parcel.
comfort sb. with sth.: 用某物安慰某人
- My father always comforts my daughter with candies while she is crying.
- Despite the fact that he has lost his lead, he still comforted others with kindness.
- It is no use comforting a man who is put out of business with candy.
it's hard to escape the conclusion that + ...: 很难不得出结论...
- It's hard to escape the conclusion that she has cheated on you.
- It's hard to escape the conclusion that the scissors are in the drawer.
- It's hard to escape the conclusion that the tiger leaped out at the man.
in captivity: 在圈养的
- My wife doesn't like going to the zoo, because these animals are in captivity.
- I suggest that the cat is not in captivity anymore.
- The cat in captivity is smelly.
Given what + ...: 鉴于...
- Given what you ate last night, we won't provide you with any food.
- Given what you have done at the fancy party, I decided to break up with you.
- Given what you provide me, I will give you a flavor and let you have it.
It is more important than ever to do sth.: 做某事比以往任何时候更重要
- It is more important than ever to take care of your wife after her abortion.
- It is more important than ever to give your mother a hand.
- It is more important than ever to be free from cheating.
vanish from sp.: 从...消失
- I have no idea of how she vanished from the street.
- The man who was being spied on vanished from the arcade just now.
- She vanished from our house where we used to live for 3 years.
