#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-06-02 How people rationalize fraud
#+begin_verse
If you ask people whether they think stealing is wrong, most of them would answer, "Yes."
And yet, in 2013,
	organizations all over the world lost an estimated total of 3.7 trillion dollars to fraud,
		which includes crimes like embezzlement, pyramid schemes, and false insurance claims.
This wasn't just the work of a few bad apples.
The truth is that many people are susceptible
	not only to the temptation to commit fraud
	but to convincing themselves that they've done nothing wrong.
		
So why does fraud happen?
While individual motivations may differ from case to case,
	the fraud triangle, a model developed by criminologist Donald Cressey,
		shows three conditions that make fraud likely: pressure, opportunity, and rationalization.
Pressure is often what motivates someone to engage in fraud to begin with.
It could be a personal debt, an addiction, an earnings quota, a sudden job loss,
	or an illness in the family.
As for opportunity, many people in both public and private sectors have access to tools
	that enable them to commit and conceal fraud:
		corporate credit cards, internal company data, or control over the budget.
The combination of pressure and being exposed to such opportunities on a daily basis
	can create a strong temptation.
	
But even with these two elements, most fraud still requires rationalization.
Many fraudsters are first time offenders,
	so in order to commit an act most would regard as wrong, they need to justify it to themselves.
Some feel entitled to the money
	because they are underpaid and overworked and others believe their fraud is victimless,
		perhaps even planning to return the money once their crisis is resolved.
Some of the most common types of fraud don't even register as such to the perpetrator.
Examples include employees fudging time sheets or expense reports,
	taxpayers failing to report cash earnings,
	or service providers overbilling insurance companies.
Though these may seem small, and can sometimes only involve hundreds of dollars,
	they all contribute to the big picture.
And then there's fraud on a massive scale.

In 2003, Italian dairy food giant Parmalat went bankrupt
	after it was found to have fabricated a 4 billion dollar bank account
			and falsified financial statements
		to hide the fact that its subsidiaries had been losing money.
Because it was family controlled, corporate governance and regulator supervision were difficult,
	and the company likely hoped that the losses could be recouped before anyone found out.
	
And it's not just corporate greed.
Governments and non-profits are also susceptible to fraud.
During her time as City Comptroller for Dixon, Illinois,
	Rita Crundwell embezzled over 53 million dollars.
Rita was one of the country's leading quarter horse breeders and winner of 52 world championships.
But the cost of maintaining the herd ran to 200,000 dollars per month.
Because her position gave her complete control over city finances,
	she was easily able to divert money to an account she used for private expenses,
		and the scheme went unnoticed for 20 years.
It is believed that Crundwell felt entitled to a lavish lifestyle based on her position,
	and the notoriety her winnings brought to the city.
	
It's tempting to think of fraud as a victimless crime
	because corporations and civic institutions aren't people.
But fraud harms real people in virtually every case:
	the employees of Parmalat who lost their jobs,
	the citizens of Dixon whose taxes subsidized horse breeding,
	the customers of companies which raise their prices to offset losses.
Sometimes the effects are obvious and devastating,
	like when Bernie Madoff caused thousands of people to lose their life savings.
But often they're subtle and not easy to untangle.
Yet someone, somewhere is left holding the bill.
#+end_verse
** expression
trillion [ˈtrɪljən]: n. the number 1,000,000,000,000万亿,兆
embezzle [ɪmˈbez(ə)l] embezzlement: v.n. to steal money from the place where you work盗用, 挪用
insurance [ɪnˈʃʊrəns]: n. an arrangement with a company in which you pay them money, especially regularly, and they pay the costs if something bad happens, for example if you become ill or your car is damaged ⇨ assurance, third party insurance保险
triangle [ˈtraɪˌæŋɡ(ə)l]: n. a flat shape with three straight sides and three angles三角形
criminology [ˌkrɪmɪˈnɑlədʒi] criminologist: n.n. the scientific study of crime and criminals犯罪学
rationalize [ˈræʃ(ə)nəˌlaɪz] rationalization: v.n. if you rationalize behaviour that is wrong, you invent an explanation for it so that it does not seem as bad合理化
addiction [əˈdɪkʃ(ə)n]: n. the need to take a harmful drug regularly, without being able to stop沉溺, 上瘾
quota [ˈkwoʊtə]: n. an official limit on the number or amount of something that is allowed in a particular period限额
budget [ˈbʌdʒət]: n. the money that is available to an organization or person, or a plan of how it will be spent预算
fraudster [ˈfrɔdstər]: n. someone who has committed a fraud欺诈者
offender [əˈfendər]: n. someone who is guilty of a crime罪犯
underpaid [ˌʌndərˈpeɪd]: adj. earning less money than you deserve for your work所得报酬过低的
overworked [ˌoʊvərˈwɜrkt]: adj. made to work too hard过度工作
victimless [ˈvɪktɪmləs]: adj. 不侵害他人的
taxpayer [ˈtæksˌpeɪr]: n. a person that pays tax纳税人
overbill: v. 超额收费
fabricate [ˈfæbrɪˌkeɪt]: v. to invent a story, piece of information etc in order to deceive someone捏造
falsify [ˈfɔlsɪˌfaɪ]: v. to change figures, records etc so that they contain false information伪造
subsidiary [səbˈsɪdiˌeri]: n. a company that is owned or controlled by another larger company子公司
corporate [ˈkɔrp(ə)rət]: adj. belonging to or relating to a corporation公司的
governance [ˈɡʌvərnəns]: n. the act or process of governing管理
regulator [ˈreɡjəˌleɪtər]: n. someone who makes sure that a system operates properly or fairly监督者
supervision [ˌsupərˈvɪʒ(ə)n]: n. when you supervise someone or something监督
greed [ɡrid]: n. a strong desire for more food, money, power, possessions etc than you need SYN avarice贪欲, 贪婪
quarter horse: 夸特马
breeder [ˈbridər]: n. someone who breeds animals or plants as a job饲者
finance [fɪˈnæns]: n. 金融
subsidize [ˈsʌbsɪˌdaɪz]: v. if a government or organization subsidizes a company, activity etc, it pays part of its costs津贴
untangle [ʌnˈtæŋɡ(ə)l]: v. to make something less complicated解开
--------------------
lost [money] to sth.: 因某事损失钱
pyramid schemes: 金字塔骗局
be susceptible to sth.: 易受某事影响
commit fraud: 犯欺诈罪
make sth. likely: 使得某事可能
motivate sb. to do sth.: 激励某人去做某事
a sudden job loss: 突然失业
in the public/private sector: 在公有或私立部门
credit cards: 信用卡
on a daily basis: 每天
justify sth. to sb.: 向某人证明某事有理
feel entitled to sth.: 觉得有资格得到某物
resolve crisis: 解决危机
register as sth. to sb.: 对某人来说是某物
fudge expense reports: 捏造费用报告
report cash earnings: 报告先进收入
recoup losses/ losses be recouped: 弥补损失
divert money to sp.(an account): 把钱转到
go unnoticed: 不为人知的
run to sth.: 到达...
go bankrupt: 破产
to begin with: 在开始时
It is believed that + ...: 人们相信...
raise prices: 提高价格
be left doing sth.: 被留下做某事
** ch.
2015-06-02 人们如何为欺诈行为找理由
如果你问人们是否认为偷窃是错误的，大多数人会回答：“是的。”
然而，2013年，全球各地的组织因欺诈损失了大约3.7万亿美元，这其中包括挪用公款、庞氏骗局和虚假保险索赔等犯罪。
这并不是几颗坏苹果的结果。
事实上，许多人不仅容易受到犯罪诱惑，还会说服自己他们并没有做错事。
那么，为什么会发生欺诈呢？
虽然每个案件的动机可能不同，但犯罪学家唐纳德·克雷西（Donald Cressey）提出的“欺诈三角”模型展示了三种使欺诈变得可能的条件：压力、机会和合理化。
压力通常是促使人们开始从事欺诈行为的动因。
它可能是个人债务、上瘾、业绩配额、突如其来的失业，或者家庭成员生病。
至于机会，许多人在公共和私营部门都有机会接触到可以实施和掩盖欺诈的工具：企业信用卡、内部公司数据，或对预算的控制。
压力和日复一日暴露于此类机会的结合，可能会产生强烈的诱惑。
然而，即使具备这两种因素，大多数欺诈行为仍然需要合理化。
许多欺诈犯是初犯，所以为了实施那些大多数人认为错误的行为，他们需要对自己进行辩解。
有些人觉得自己有权拿走这笔钱，因为他们的工资低且工作繁重，另一些人则认为他们的欺诈行为是无害的，甚至打算在危机解决后将钱还回去。
一些最常见的欺诈类型，实施者甚至都不认为自己在做欺诈。
比如员工篡改工作时间表或费用报销单，纳税人未申报现金收入，或者服务提供商多收保险公司费用。
虽然这些行为看起来很小，且有时只涉及几百美元，但它们都在影响大局。
然后是大规模的欺诈行为。
2003年，意大利乳制品巨头帕玛拉特（Parmalat）因虚构了一个40亿美元的银行账户和伪造财务报表来掩盖其子公司亏损的事实而破产。
由于公司由家族控制，企业治理和监管监督非常困难，公司可能希望在任何人发现之前，通过弥补亏损来挽回局面。
而这不仅仅是公司贪婪的表现。
政府和非营利组织同样容易发生欺诈。
在担任伊利诺伊州迪克森市（Dixon, Illinois）市审计长期间，丽塔·克伦德威尔（Rita Crundwell）挪用了超过5300万美元。
丽塔是美国领先的四分之一马繁育商，并赢得了52个世界冠军。
但维持马群的费用高达每月20万美元。
由于她的职位让她完全掌控城市财政，她轻松地将资金转入自己用于私人开销的账户，而且这个计划持续了20年都未被察觉。
人们普遍认为克伦德威尔认为自己基于职务和她的胜利为城市带来的声望，理应享受奢华的生活方式。
我们常常会觉得欺诈是“无害的犯罪”，因为企业和公共机构不是个人。
然而，几乎在每个案例中，欺诈都会伤害到真实的人：
比如帕玛拉特的员工失去了工作，迪克森市的居民用税款资助了马匹繁育，某些公司提高价格来弥补损失。
有时其后果显而易见且毁灭性强，比如伯尼·麦道夫（Bernie Madoff）让成千上万的人失去了毕生积蓄，
但往往这些后果是微妙的，且不容易理清。
然而，无论如何，总会有某个人在承担这个账单。
** sentence
lost [money] to sth.: 因某事损失钱
- We lost a great deal of money to the experiment you performed last month. 
- My wife is unwilling to lose money to my company anymore.
- The chance of losing money to our new store is increasing exponentially.
pyramid schemes: 金字塔骗局
- Imagine his dismay when he realized this turned out to be a pyramid scheme.
- The police arrived on the scene and told the old lady this must be a pyramid scheme.
- Let's expand on pyramid schemes to make this event clear.
be susceptible to sth.: 易受某事影响
- She failed the exam, not because she was susceptible to video games,
		but because she was not good at swimming.
- I couldn't pay attention to the teacher, not because I was susceptible to birds outside,
		but because I developed a fever.
- This might explain why she was susceptible to the temptation of stealing clothes.
commit fraud: 犯欺诈罪
- It is within only last century that fraud is committed frequently.
- Being composed of finance in the public sector, she can't the temptation to commit fraud.
- These criminals had one thing in common: committed fraud in the public sector.
make sth. likely: 使得某事可能
- Because of the research into the brain, it makes treatment of OCD likely.
- Making digestion likely, these bacteria are vital for your body.
- 'Making a profit is the only approach to make our research likely.' she shouted at me.
motivate sb. to do sth.: 激励某人去做某事
- Mr. Leo always motivates us to read the history book at our own pace.
- My dad used to motivate me to resolve the puzzle by myself. 
- His encouragement motivated me to break the world record.
a sudden job loss: 突然失业
- A sudden job loss attacked my father, which led to a hard life in my youth.
- Before deciding to buy a house, we must deliberate at length over a sudden job loss.
- Despite a sudden job loss, he continued to spend a lot of money studying English.
in the public/private sector: 在公有或私立部门
- It is not likely to get a good salary in the public sector.
- It is more stable to work in the public sector than in the private sector.
- It implies that he has been working in the public sector for ten years.
credit cards: 信用卡
- Why do you keep interacting with my secretary who has access to corporate credit cards?
- In one study, up to 90% of meals are paid for by credit cards in America.
- They urged Rachel to stop using her father's credit cards.
on a daily basis: 每天
- The busmen go on strike on a daily basis this week.
- The vicar expresses his gratitude to the god on a daily basis.
- She is fanatical about the team on a daily basis.
justify sth. to sb.: 向某人证明某事有理
- The criminal failed to justify his behavior to the judge.
- My wife has been justifying the decoration of our room to me for a whole morning.
- He is trying to justify the arrangement of objects in this room to everyone in the party.
feel entitled to sth.: 觉得有资格得到某物
- It is no use pretending that you feel entitled to the job.
- Feeling entitled to the job, she applied for it just then.
- Feeling entitled to entrepreneur, he managed to set up a factory in the suburbs.
resolve crisis: 解决危机
- A series of factories set up in a suburb of the city eventually resolve crises.
- With skills comes a good job, and he gets a good salary to resolve crises.
- Making a profit this month, Mr. Leo managed to resolve crises in his company.
register as sth. to sb.: 对某人来说是某物
- The note registers as an important memory to our family.
- The clavichord registering as our friendship to us was broken down last week.
- This action may register as a criminal to people in China.
fudge expense reports: 捏造费用报告
- The boss kept his secretary fudging expense reports to avoid tax.
- The worker used to fudge expense reports.
- The worker can't resist the temptation to fudge expense reports.
report cash earnings: 报告现金收入
- The grocer failed to refuse to report cash earnings.
- The grocer doesn't report cash earnings so that he doesn't need to pay taxes.
- The grocer was accused of not reporting cash earnings on time.
recoup losses/ losses be recouped: 弥补损失
- So long as injury appears, it is impossible to recoup losses.
- With losses being recouped, she has been assigned to be the official again.
- She was assigned to recoup losses in this crisis.
divert money to sp.(an account): 把钱转到
- The old lady insisted on diverting her money to an unknown account.
- The boss has diverted his money to the account for public expense.
- Although the alarm was given, the old lady proceeded to divert her money to an unknown account.
go unnoticed: 不为人知的
- The fact that she poisoned her three husbands in her youth went unnoticed.
- You don't feel guilty, the fraud will go unnoticed.
- The poet going unnoticed for years published a masterpiece on history in the press.
run to sth.: 到达...
- On the journey, the plane ran to a height of 10,000 miles.
- It is estimated that the plane will run to a height of 10,000 miles.
- The plane running to a height of 10,000 miles was regarded as a great experiment.
go bankrupt: 破产
- The company is not being allowed to go bankrupt by the authorities.
- It is estimated that the company will go bankrupt in this economic crisis.
- After a big forest fire, the local authorities announced that they went bankrupt.
to begin with: 在开始时
- To begin with, she was astonished to find that he had poisoned his ex-wife.
- To begin with, a snake was wound around a length of electric wire.
- To begin with, a stream wound its way across the field.
It is believed that + ...: 人们相信...
- It is believed that these corpses feast on the life force of people.
- It is believed that these creatures sustain themselves by sucking blood.
- It is believed that the brutal executions were being carried out in the empire.
raise prices: 提高价格
- With workers digging up more gold, it is time to raise prices to make a profile.
- Mr. Leo raised the prices of his course randomly, which led to many complaints.
- The authorities had to establish a law prohibiting raising prices during the war. 
be left doing sth.: 被留下做某事
- Needless to say, I was left taking care of the baby.
- In China, many old men or women in villages are left taking care of children.
- You must elaborate upon why I will be left feeding dogs.
** summary
Although organizations all over the world have lost a great deal of money to fraud,
	many people guilty for this tend to believe that they are innocent.
The fraud triangle shows three conditions that make fraud likely:
	pressure, opportunity, and rationalization.
Pressesure,
		such as a job loss, an illness in family, and so on,
	movitates someone to engage in fraud to begin with.
Having access to tools in both public and privates sectors,
	many people have opportunities to commit and concel fraud.
As the act is often regarded as wrong,
	they also need to justify it to themselvess as first time offenders.
In business, Italian dairy reported farbricating a bank account and falsifying financial statements.
In government,
	Rita Crundwell, former City Comptroller for Dixon, Illinois, embezzled over 53 million dollars
		so that she could afford to her quarter horse breeding.
It's tempting to think of fraud as a victimless crime,
	however, frauds harms real people in virtually every case.
** summary2
Although organizations all over the world have lost a great deal of money to fraud,
	many people who are guilty of this tend to believe that they are innocent.
The fraud triangle shows three conditions that make fraud likely:
	pressure, opportunity, and rationalization.
Pressure,
		such as a job loss, an illness in the family, and so on,
	motivates someone to engage in fraud to begin with.
Having access to tools in both public and private sectors,
	many people have opportunities to commit and conceal fraud.
As the act is often regarded as wrong,
	they also need to justify it to themselves as first-time offenders.
In business, Italian dairy reported fabricating a bank account and falsifying financial statements.
In government,
	Rita Crundwell, former City Comptroller for Dixon, Illinois, embezzled over 53 million dollars
		so that she could afford her quarter horse breeding.
It's tempting to think of fraud as a victimless crime,
	however, fraud harms real people in virtually every case.
