#+OPTIONS: \n:t toc:nil num:nil html-postamble:nil
#+HTML_HEAD_EXTRA: <style>body {background: rgb(193, 230, 198) !important;}</style>
* 2015-03-27 What causes bad breath
#+begin_verse
There is a curse that has plagued humanity since ancient times.
The Greeks fought it by chewing aromatic resins, while the Chinese resorted to egg shells.
In the ancient Jewish Talmud, it's even considered legal grounds for divorce.
This horrible scourge is halitosis, otherwise known as bad breath.
But what causes it, and why is it so universally terrifying?
Well, think of some of the worst odors you can imagine, like garbage, feces or rotting meat.
All of these smells come from the activity of microorganisms, particularly bacteria,
	and, as disgusting as it may sound,
		similar bacteria live in the moisture-rich environment of your mouth.
		
Don't panic.
The presence of bacteria in your body is not only normal,
	it's actually vital for all sorts of things, like digestion and disease prevention.
But like all living things, bacteria need to eat.
The bacteria in your mouth feed off of mucus, food remnants, and dead tissue cells.
In order to absorb nutrients through their cell membranes,
	they must break down the organic matter into much smaller molecules.
For example, they'll break proteins into their component, amino acids
	and then break those down even further into various compounds.
Some of the foul-smelling byproducts of these reactions, such as hydrogen sulfide and cadaverine,
	escape into the air and waft their way towards unsuspecting noses.
Our sensitivity to these odors and interpretation of them as bad smells
	may be an evolutionary mechanism warning us of rotten food and the presence of disease.
	
Smell is one of our most intimate and primal senses,
	playing a huge role in our attraction to potential mates.
In one poll,
	59% of men and 70% of women said they wouldn't go on a date with someone who has bad breath,
	which may be why Americans alone spend $1 billion a year on various breath products.
Fortunately, most bad breath is easily treated.
The worst smelling byproducts come from gram-negative bacteria
	that live in the spaces between gums and teeth and on the back of the tongue.
By brushing and flossing our teeth,
		using antibacterial mouthwash at bedtime,
		gently cleaning the back of the tongue with a plastic scraper
			and even just eating a healthy breakfast,
	we can remove many of these bacteria and their food sources.
In some cases,
	these measures may not be enough due to dental problems, nasal conditions, or rarer ailments,
		such as liver disease and uncontrolled diabetes.
Behaviors like smoking and excessive alcohol consumption also have a very recognizable odor.
Regardless of cause,
	the bad smell almost always originates in the mouth and not the stomach or elsewhere in the body.
	
But one of the biggest challenges lies in actually determining
		how our breath smells in the first place,
	and it's unclear why.
It may be that we're too acclimatized to the smell inside our own mouths to judge it.
And methods like cupping your hands over your mouth, or licking and smelling your wrist
	don't work perfectly either.
One study showed that even when people do this,
	they tend to rate the smell subjectively according to how bad they thought it was going to be.
But there's one simple, if socially difficult, way of finding out how your breath smells:
	just take a deep breath and ask a friend.
#+end_verse
** expression	
curse [kɜrs]: n. a word or sentence used to ask God or a magical power to do something bad to someone or something诅咒
plague [pleɪɡ]: n. to cause pain, suffering, or trouble to someone, especially for a long period of time祸根
aromatic [ˌærəˈmætɪk]: adj. having a strong pleasant smell SYN fragrant芬芳的
shell [ʃel]: n. the hard outer part that covers and protects an egg, nut, or seed壳
legal [ˈliɡ(ə)l]: adj. if something is legal, you are allowed to do it or have to do it by law OPP illegal法定的, 合法
scourge [skɜrdʒ]: n. something that causes a lot of harm or suffering祸根
halitosis [ˌhælɪˈtoʊsɪs]: n. a condition in which someone’s ath smells very bad SYN bad breath口臭
universally [ˌju:nɪ'vɜ:səli]: adj. 普遍地
feces [ˈfisiz]: n. pl. solid waste material from the ↑bowels粪
microorganism [ˌmaɪkroʊˈɔrɡəˌnɪzəm]: n. a living thing that is so small that it cannot be seen without a ↑microscope微生物
moisture-rich [ˈmɔɪstʃə(r)] [rɪtʃ]: adj. small amounts of water that are present in the air, in a substance, or on a surface湿气丰富的
digestion [daɪˈdʒestʃ(ə)n]: n. the process of digesting food消化力
mucus [ˈmjukəs]: n. a thick liquid produced in parts of your body such as your nose粘液
food remnants: 残余
tissue [ˈtɪʃu]: n. the material forming animal or plant cells组织
nutrient [ˈnutriənt]: adj. a chemical or food that provides what is needed for plants or animals to live and grow营养的
foul-smelling [faʊl]: adj. having an extremely unpleasant smell闻起来臭的
byproduct [ˈbaɪˌprɑdʌkt]: n. 副产品
sulfide [ˈsʌlˌfaɪd]: n. 硫化物
cadaverine [kə'dævəˌrin]: n. 尸胺
unsuspecting [ˌʌnsəˈspektɪŋ]: adj. not knowing that something bad is happening or going to happen不怀疑的
primal [ˈpraɪm(ə)l]: adj. primal feelings or actions seem to belong to a part of people’s character that is ancient and animal-like原始的
gram-negative [ɡræm][ˈneɡətɪv]: adj. 革兰氏(染色)阴性的
antibacterial [ˌæntibækˈtɪriəl]: adj. 抗菌的
mouthwash [ˈmaʊθˌwɔʃ]: n. a liquid used to make your mouth smell fresh or to get rid of infection in your mouth嗽口水
scraper [ˈskreɪpər]: n. a tool used to remove something from a surface by rubbing刮刀
nasal [ˈneɪz(ə)l]: adj. related to the nose鼻的
ailment [ˈeɪlmənt]: n. an illness that is not very serious疾病(尤指微恙)
diabetes [ˌdaɪəˈbiːtiːz]: n. a serious disease in which there is too much sugar in your blood糖尿病
excessive [ɪkˈsesɪv]: adj. much more than is reasonable or necessary过多的
alcohol consumption [ˈælkəˌhɔl]: 消费
originate [əˈrɪdʒəˌneɪt]: v. formal to come from a particular place or start in a particular situation起源, 发生
lick [lɪk]: v. to move your tongue across the surface of something in order to eat it, wet it, clean it etc舔
wrist [rɪst]: n. the part of your body where your hand joins your arm手腕
subjectively: adv. 主观地
--------------------
resort to sth.: 诉诸于某事
grounds for sth.(divorce)/doing sth.: 做某事的理由
as disgusting as it may sound, ...: 虽然听起来很恶心,但...
feed off of sth.: 以某物为食
break down A into B: 把A分解成B
waft sb's way towards sp.: 飘荡到某地
interpretation of A as B: 把A解释为B
warn sb. of sth.: 警告某人某事
go on a date with sb.: 和某人约会
floss sb's teeth: 用牙线清洁牙齿
at bedtime: 睡前
in the first place: 最初
cup your hands over your mouth: 用手捂住嘴
be too acclimatized to sth. to do sth.: 对某事太熟悉而不能做某事
** sentence
resort to sth.: 诉诸于某事
- Because the vicar is always raising money, but the clock hasn't been repaired,
		he may resort to the lie.
- It is no use resorting to your parents while you are late for school.
- He must have resorted to the lie, for he hadn't finished his homework.
grounds for sth.(divorce)/doing sth.: 做某事的理由
- The ground for not providing you with pocket money
		is that you smashed everything in the kitchen into pieces yesterday.
- The ground for asking for a lift is that my car has broken down.
- The ground for paying the bill is that he has paid for my dinner.
as disgusting as it may sound, ...: 虽然听起来很恶心,但...
- As disgusting as it may sound, we have to clean up the house full of feces in time.
- As disgusting as it may sound, we should pay for the meal mixed with a hair.
- As disgusting as it may sound, the vicar is raising money now.
feed off of sth.: 以某物为食
- It is no use pretending that your cat feeds off of vegetables.
- These tourists prevented the wolf from feeding off of wild rabbits.
- Instead of meals, the dog fed off of feces in his youth.
break down A into B: 把A分解成B
- You broke down the bike into parts, which shocked Mommy very much.
- The worker refused to break down his bike into parts.
- It will have been broken down into pieces in twenty minutes.
waft sb's way toward sp.: 飘荡到某地
- While we were going for a walk alongside the path,
		 the smell of oak wafted its way toward our noses.
- I am tired of the smell of meals from my neighbor wafting its way toward my nose at bedtime.
- So long as the odor wafted its way toward your nose, you will mobilize your immune system.
interpretation of A as B: 把A解释为B
- His interpretation of my kindness as recreance annoyed me a great deal.
- My interpretation of the coverage as a fact caused me to make that stupid remark.
- The interpretation of atoms as baseballs helps us to make progress. 
warn sb. of sth.: 警告某人某事
- The FBI always warns me of pirated movies at the beginning.
- The editor is warning you of bugs that are obvious.
- With the editor warning him of bugs, he continued to program it to act.
go on a date with sb.: 和某人约会
- I prefer to go on a date with that cute girl I met yesterday.
- She prefers going on a date with Mike than Chandler.
- She prefers to die than go on a date with Chandler.
floss sb's teeth: 用牙线清洁牙齿
- It reminded me of flossing my teeth at bedtime.
- She has trained her daughter to floss her teeth for weeks.
- My wife's dentist forbade her to floss her teeth.
at bedtime: 睡前
- I used to tell my son pirate stories at bedtime.
- First of all, I really wanted to go to sleep at bedtime yesterday.
- Stop making a call to me at bedtime, leave me alone. 
in the first place: 最初
- In the first place, we thought of the task of reading as extremely difficult.
- In the first place, we proposed a way of rescuing them in a special capsule. 
- In the first place, the prizefighter lived in poverty in the USA.
cup your hands over your mouth: 用手捂住嘴
- With the corpse coming, everyone cupped his hands over his mouth to hold his breath.
- If you cup your hands over your mouth and smell your breath,  you will find it terrible.
- She was cupping her hands over her mouth to avoid making any voice while witnessing a murder.

** summary
Halitosis, also known as bad breath, has plagued humanity all over the world since ancient times.
The activities of microorganisms,
		especially bacteria living in the moisture-rich environment of your mouth,
	are the leading causes.
In fact, the bacteria in your mouth are similar to those existing in terrible conditions,
	such as garbage, feces, and rotting meat.
In fact----~~~
Don't panic,
	because the presence of bacteria in your body is not only normal
		but actually vital for digestion and disease prevention.
actually---~~~;
In order to absort nutrients through their cell membrains,
	they break down the organic matter in your mouth into much smaller molecuels,
		during which they produce the foul-smelling byproduct, like hydrogen sulfide an cadaverine.
In order to---To; absort---absorb; membrains--membranes; molecuels---molecules;
the foul-smelling---foul-smelling
For they generally live in between our gums and teeth, and on the back of the tongue,
	it is easy for us to remove them and their food sources.
But other health problems can also lead to it.
But---~~~
However, as we tend to rate the smell subjectively,
	one of the biggest challenges is to determine how our smell at the beginning.
how our smell --- how our smell is
It still remains a mystery,
	but there is one simple but socially difficult way: take a deep breath and ask your friend.
still---~~~

** summary2
Halitosis, known as bad breath, has plagued humanity worldwide since ancient times.
The activities of microorganisms,
		especially bacteria living in the moisture-rich environment of your mouth,
	are the leading causes.
The bacteria in your mouth are similar to those existing in terrible conditions,
	such as garbage, feces, and rotting meat.
Don't panic,
	because the presence of bacteria in your body is not only normal
		but vital for digestion and disease prevention.
To absorb nutrients through their cell membranes,
	they break down the organic matter in your mouth into much smaller molecules,
		during which they produce foul-smelling byproducts, like hydrogen sulfide and cadaverine.
For they generally live in between our gums and teeth and on the back of the tongue,
	it is easy for us to remove them and their food sources.
Other health problems can also lead to it.
However, as we tend to rate the smell subjectively,
	one of the biggest challenges is to determine how our smell is at the beginning.
It remains a mystery,
	but there is one simple but socially difficult way: take a deep breath and ask your friend.

