* Task5家庭作业: 精听+精读
1. 听文章(不能看脚本),答题,记录对错
2. 阅读听力脚本,标注所有生词,语法,摘除习惯用法(并造句)
3. 跟读文章edgeX50遍
4. 模拟考试,听文章,答题,记录对错
5. 继续跟读50遍(task5+直播课程6结束后)
6. 模拟第4步.找到拿听力满分的理论信心

写出完成作业的疑惑,带着疑惑去听课


** Part 4
Ancient philosophy is not just about talking or lecturing, or even reading long, dense books.
In fact, it is something people have used throught history
	- to solve their problems and to achive their greatest triumphs.

Specifically, I am referring to Stoicism, in my opinion,
	is _the most paractical of all philosophies_ and therefore the most appealing.
Stoicism was founded in Ancient Greece by Zeno of Citium in the early 3rd century BC,
	but was practised by the likes of Epictetus, Cato, Seneca and Marcus Aurelius.
Amazingly, we still have access to these ideas, despite the fact
	_that the most famous Stoics never wrot anything down for publication._
Cato definitely didn't.
Marcus Aurelius never intended his Meditations to be anything but personal.
Seneca's letters were, well, letters and Epictetus' thoughts
	come to us by way of note-talking studeent.

Stoic principles were based on the idea
	that its followers could have an unshakable happiness	in this life
		and the key to achieving this was virtue.
The road to virtue, in turn,
	lay in understanding that destructive emotions, like anger and jealousy,
	are under our conscious control
	- they don't have to control us, because we can learn to control them.
In the words of Epictetus:
	"external events I cannot control, but the choices I make with regard to them, I do control".

The modern day philosopher and writer Nassim Nichiolas Taleb defines a Stoic as someone
	who has _a different perspeactive on experiences which most of us would see as wholly negative;_
	a Stoic "transforms fear into caution, pain into transformation, mistakes into initiation
		and desire into undertaking".
Using this definition as a model, we can see that throughtout the centuries
	Stoicism has been practised in more recent history
		by kings, presidents, artists, writers and entrepreneus.


------------------------------------------
The founding fathers of the United States were inspired by the philosophy.
George Washington was introduced to Stoicism
	by his neighbours at age seventeen,
	_and later, put on a play based on the life of Cato to inspire his men._
Thomas Jefferson kept a copy of Seneca beside his bed.

Writers and artists have also been inspired by the stoics.
Eugene Delacroix, the renowned French Romantic artist
	(known best for his painting Liberty Leading the People) was ardent Stoic,
	referring to it as his "consoling religion".
	
The economist Adam Smith's theories on capitalism were significanly influenced by the Stoicism
	that he studied as a schoolboy, under a teacher who had translated Marcus Aurelius' works.

Today's political leaders are no different,
	with many finding their inspiration from the ancient texts.
Former US president Bill Clinton rereads Marcus Aurlius every single year,
	and many have compared former President Obama's calm leadership style to that of Cato.
Wen Jiabao, the former prime minister of China, claims that Meditations is one of two books
	he travels with
	and that he has read it more than one hundred times over the course of his life.

Stoicism had a profound influence on Albert Ellis,
	who invented Congnitive Behaviour Therapy,
	which is used to help people manage their problemsj by changing the way
		that they think and behave.
It's most commonly used to treat depression.
The idea is that we can take control of our lives
	by challenging the irrational beliefs
		that create our faulty thinking, symptoms and behaviours by using logic instead.

Stoicism has also become popular in the world of business.
Stoic principles can build the resilience and state of mind required to overcome setbacks
	because Stoics teach turning obstacles into opportunity.
A lesson every business entrepreneur needs to learn.

I would argue that studing Stocism is as relevant today as it was 2,000 years ago,
	thanks to its brilliant _insights into how to lead a good life._
At the very root of the thinking, there is a very simple way of living
	- control what you can and accept what you can't.
This is not as easy as it sounds and will require considerate practice
	- it can take a lifetime to master.
The Stoics also believed the most important foundation for a good and happy life
	is not money, fame, power or pleasure, but having a disciplined and principled character
	- something which seems to resonate with many people today.
		
** 问题
1. 不看脚本前,只能听到几个单词,提前听的意义在哪里?
2. 跟读文章edgeX50
